return
{

	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "まだ壊れてねェよ！",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "どう考えても、ムリだろーが！",
			GENERIC = "そいつァ、それねェだろーがよ！",
			NOBITS = "そるもん、残ってねェだろーが！",
		},
		STORE =
		{
			GENERIC = "これ以上は、入らねェぞ！",
			NOTALLOWED = "そこには、入れらんねェぞ！",
		},
		RUMMAGE =
		{	
			GENERIC = "やなこっただ！",	
		},
        COOK =
        {
            GENERIC = "メシ作ってる場合じゃねェだろーが！",
            TOOFAR = "手が届かねェ！",
        },
        GIVE =
        {
            DEAD = "死んでるゼ",
            SLEEPING = "寝てるゼ",
            BUSY = "こいつ、ワシを無視しやがるゼ！",
        },
        WRITE =
        {
            GENERIC = "ワシが書けるのは、“X”マークだけだゼ！",
        },
        CHANGEIN =
        {
            GENERIC = "今日は着替えるつもりはねェ！",
            BURNING = "ゴウゴウ燃えてやがるゼ！",
        },
		TEACH =
        {
            KNOWN = "ヨーホーホー…",
            CANTLEARN = "ヨーホーホー！！",
        },
	},
	ACTIONFAIL_GENERIC = "そいつァ、ムリだな！",
	ANNOUNCE_MAGIC_FAIL = "ここじゃムリみてェだな！",
	ANNOUNCE_ACCOMPLISHMENT = "ワーッハッハー！ワシはな、すげェんだぞォ！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "船員どもに自慢してェなァ！",
	ANNOUNCE_ADVENTUREFAIL = "しくじったゼ…また挑戦するしかねェな",
	ANNOUNCE_BEES = "ちびっこい怪物めッ！シッシッ！",
	ANNOUNCE_BOAT_DAMAGED = "マズい！浸水してきやがったッ！",
	ANNOUNCE_BOAT_SINKING = "沈むぞーッ！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "ついにワシも、海の藻クズか…",
	ANNOUNCE_BOOMERANG = "なんだ、このめんどくせェ武器はッ！",
	ANNOUNCE_BURNT = "痛ッた！",
	ANNOUNCE_CANFIX = "\nフン…これならワシにも直せそうだゼ",
	ANNOUNCE_CHARLIE = "うォいッ！なんだ、いまのはッ！",
	ANNOUNCE_CHARLIE_ATTACK = "ウガッ！かみつかれたぞッ！",
	ANNOUNCE_COLD = "ガアアァ！寒みィゼ！",
	ANNOUNCE_CRAB_ESCAPE = "クソッ、カニの野郎…どこ行きやがった…",
	ANNOUNCE_CRAFTING_FAIL = "材料が足りねェみてェだな！",
	ANNOUNCE_DAMP = "海賊ズボンがぬれちまうゼ！",
	ANNOUNCE_DEERCLOPS = "でけェ怪物が襲ってきやがるゼ！",
	ANNOUNCE_DUSK = "水平線の彼方から、闇が迫ってくるゼ…",
	ANNOUNCE_EAT =
	{
		GENERIC = "カーッ！うめェな！",
		INVALID = "んなもん、ワシは食わねェぞ！",
		PAINFUL = "うぅ～腹がいてェ…",
		SPOILED = "食ったら、腹壊しそうだゼ",
		STALE = "賞味期限、切れてやがったゼ…",
	},
	ANNOUNCE_ENTER_DARK = "真っ暗だゼ！",
	ANNOUNCE_ENTER_LIGHT = "見えるようになったゼ！",
	ANNOUNCE_FREEDOM = "脱出できたゼ！",
	ANNOUNCE_HIGHRESEARCH = "今日は頭がさえてやがるゼ！",
	ANNOUNCE_HOT = "暑ちィな…氷はねェのか…？",
	ANNOUNCE_HOUNDS = "あァ？ありャ、なんの音だァ？",
	ANNOUNCE_HUNGRY = "腹減ったゼ…",
	ANNOUNCE_HUNT_BEAST_NEARBY = "こいつァ、新しい足跡だな…獲物は近いゼ",
	ANNOUNCE_HUNT_LOST_TRAIL = "足跡、見失っちまったゼ…",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "チッ…雨で足跡が消えてやがるゼ…",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "肥やしをやらねェとダメだゼ…",
	ANNOUNCE_INV_FULL = "これ以上は、持てねェな！",
	ANNOUNCE_KNOCKEDOUT = "うぐぐゥ…頭がガンガンしやがるゼ…",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "ケッ…電撃なんかに、やられッかよッ！",
	ANNOUNCE_LOWRESEARCH = "んなこたァ、もう知ってるゼ…",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "霧の海に、分け入るゼ…",
	ANNOUNCE_MAPWRAP_RETURN = "世界の端から、反対側に戻ってきたゼ！",
	ANNOUNCE_MAPWRAP_WARN = "霧のベールが迫ってきやがるゼ…",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"字が薄れて読めねェな…",
	},
	ANNOUNCE_MORETREASURE = "また、お宝だァ！お宝、ザクザクだゼェ！",
	ANNOUNCE_MOSQUITOS = "吸血怪物めッ！寄るんじゃねェ！",
	ANNOUNCE_NODANGERSIESTA = "昼寝してる場合じゃねェだろーが！",
	ANNOUNCE_NODANGERSLEEP = "寝てる場合じゃねェだろーが！",
	ANNOUNCE_NODAYSLEEP = "明るいうちから寝れッかよ！",
	ANNOUNCE_NODAYSLEEP_CAVE = "まだ眠くねェよ！",
	ANNOUNCE_NOHUNGERSIESTA = "腹が減りすぎて、眠れねェな！",
	ANNOUNCE_NOHUNGERSLEEP = "腹が鳴る音がうるさくて、眠れねェぞ！",
	ANNOUNCE_NONIGHTSIESTA = "夜に昼寝だァ？意味がわからねェな！",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "こんなとこで昼寝だァ？冗談じゃねェゼ！",
	ANNOUNCE_NOSLEEPONFIRE = "燃えてる寝床で寝る趣味はねェな！",
	ANNOUNCE_NO_TRAP = "楽勝だゼ！",
	ANNOUNCE_OTHER_WORLD_PLANT = "この草、別の世界のじゃねェか？",
	ANNOUNCE_OTHER_WORLD_TREASURE = "この地図、この国のじゃねェな",
	ANNOUNCE_PECKED = "ガー！何しやがる、てめェ！",
	ANNOUNCE_QUAKE = "地面がゲップしてやがるゼ",
	ANNOUNCE_RESEARCH = "頭の体操になったゼ",
	ANNOUNCE_SHARX = "こいつら…ワシを食いに来やがったなッ！",
	ANNOUNCE_SHELTER = "この木のおかげで、助かったゼ！",
	ANNOUNCE_SOAKED = "骨まで、ずぶぬれだゼ！",
	ANNOUNCE_THORNS = "…ッてッ！刺しやがったな、このヤロウッ！",
	ANNOUNCE_TOOL_SLIP = "クソッ…ツルツルすべりやがって…！",
	ANNOUNCE_TORCH_OUT = "クソッ…明かりが消えちまったゼ！",
	ANNOUNCE_TRAP_WENT_OFF = "ガアアァーッ！",
	ANNOUNCE_TRAWL_FULL = "獲物が、たっぷりかかったゼ！",
	ANNOUNCE_TREASURE = "印の場所に、お宝が眠ってやがるゼ！",
	ANNOUNCE_UNIMPLEMENTED = "こいつァ、まだ造りかけだな！",
	ANNOUNCE_VOLCANO_ERUPT = "悪魔が火を吹いてやがるゼ！",
	ANNOUNCE_WAVE_BOOST = "大海原を駆ける風の気分だゼ！",
	ANNOUNCE_WET = "海賊シャツが、ずぶぬれだゼ！",
	ANNOUNCE_WETTER = "水は、船底より上に来てもらっちゃ困るゼ",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "近くに、でけェ怪物がいやがるゼ",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "怪物の痕跡、見失っちまったゼ…",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "こう海が荒れてちゃ、追跡はムリだゼ…",
	ANNOUNCE_WORMHOLE = "われながら、正気とは思えねェな！",
	ANNOUNCE_TREASURE_DISCOVER = "お宝のニオイがするゼ…！",
	BATTLECRY =
	{
		GENERIC = "ワシが相手だアアァ！",
		PIG = "今夜の晩メシは、ハムだゼェッ！",
		PREY = "くたばりやがれィッ！",
		SPIDER = "義足でブッつぶしてやるゼッ！",
		SPIDER_WARRIOR = "義足でブッつぶしてやるゼッ！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "海賊にケンカ売るたァ、ふてェ野郎だゼ…",
		PIG = "ケッ…ハムにすんのは、また今度だな…",
		PREY = "義足で追うには、すばしっこすぎるゼ…",
		SPIDER = "多足の悪魔め…！次はタダじゃおかねェぞ！",
		SPIDER_WARRIOR = "多足の悪魔め…！次はタダじゃおかねェぞ！",
	},
	DESCRIBE =
	{
		--ABIGAIL = "A lady spectre!",
		ACCOMPLISHMENT_SHRINE = "大海賊ウッドレッグス様の功績を見ろッ！",
		ACORN =
		{
			GENERIC = "振るとカラカラ音がするゼ",
			PLANTED = "将来は木になるに違げェねェ",
		},
		ACORN_COOKED = "陸の食料にしちゃ、悪くねェな！",
		ADVENTURE_PORTAL = "こいつァ…新手のワナか？",
		AERODYNAMICHAT = "倍の速さで歩けるゼ！",
		AMULET = "首にかけときャ、保険になるゼ",
		ANCIENT_ALTAR = "こいつァ、大昔にできた像だゼ",
		ANCIENT_ALTAR_BROKEN = "壊れてやがるゼ",
		ANCIENT_STATUE = "こいつの気配…どうも気に入らねェゼ…",
		ANIMAL_TRACK = "この足跡たどりャ、きっと獲物がいるゼ？",
		ANTIVENOM = "ワシぁ、死ぬときャ海の上と決めてンだ",
		ARMORDRAGONFLY = "敵を丸焼きにできるゼ！",
		ARMORGRASS = "船乗りは、草のよろいなんか着ねェゼ！",
		ARMORLIMESTONE = "こいつァ、海に入れたら間違いなく沈むゼ",
		ARMORMARBLE = "こいつァ、海に入れたら間違いなく沈むゼ",
		ARMOROBSIDIAN = "重めェし、熱ちィゼ！",
		ARMORRUINS = "お宝を着てるみてェだな！",
		ARMORSEASHELL = "こンなもん着たら、笑いモンだゼ…",
		ARMORSLURPER = "こンなん着てまで、身を守りてェか…？",
		ARMORSNURTLESHELL = "カメみてェに隠れろだァ？やなこった！",
		ARMORWOOD = "ま、木は水に浮くからな",
		ARMOR_LIFEJACKET = "こんなモン着る船乗りは、半人前だゼ",
		ARMOR_SANITY = "着ると気分がよくなるゼ…",
		ARMOR_SNAKESKIN = "こンなら、雨を弾いてくれるだろーよ",
		ARMOR_WINDBREAKER = "風を切り進む海の男たァ、ワシのことよ！",
		ARMOUREDBOAT = "こいつァ、じょうぶな船だゼ",
		ASH =
		{
			GENERIC = "炎に持ってかれちまったな…",
			REMAINS_EYE_BONE = "ワシの目玉、燃えなくてよかったゼ…",
			REMAINS_GLOMMERFLOWER = "この花ァ、移動に向いてねェみてェだな",
			REMAINS_THINGIE = "ただの灰とは、思えねェけどな…",
		},
		AXE = "オノれー！このオノを食らえィ！",
		BABYBEEFALO = "マヌケな獣にしちャ、かわいいじゃねェか！",
		BABYOX = "立派な海の男になれよ！",
		BACKPACK = "さて、荷造りでもするかな！",
		BACONEGGS = "朝メシは、ちゃァんと食わねェとな！",
		BALLPHIN = "こいつら、なかなか賢いンだゼ？",
		BAMBOO = "つまようじ…にしちゃ、デカすぎンな…",
		BAMBOOTREE =
		{
			BURNT = "ありゃァもう、生えてこねェな…",
			CHOPPED = "しばらく待たねェと、生えてこねェな！",
			GENERIC = "あの木、あっというまに伸びやがるゼ",
		},
		BANDAGE = "海賊にャ、こンなもん必要ねェゼ",
		BASALT = "ずいぶん硬てェ岩だな！",
		BAT = "空飛ぶネズ公め！シッシッ！",
		BATBAT = "こいつで敵をブン殴ってやるゼ！",
		BATWING = "ブルーチーズソースは、ねェのか？",
		BATWING_COOKED = "鶏肉みてェな味だゼ",
		BEARDHAIR = "あごに生えるヒゲみてェだな！",
		BEARGER = "怪物め！こっち来ンじゃねェぞ！",
		BEARGERVEST = "着ると体がホカホカするゼ",
		BEARGER_FUR = "獣くせェな…",
		BEDROLL_FURRY = "獣の夢が見れそうだゼ",
		BEDROLL_STRAW = "ちと湿っぽいゼ…",
		BEE =
		{
			GENERIC = "ハチミツ作る連中だゼ",
			HELD = "オイ！お宝を渡しやがれッ！",
		},
		BEEBOX =
		{
			BURNT = "ハチミツの焦げたニオイがするゼ…",
			FULLHONEY = "中に、黄金の蜜が詰まってやがるゼ！",
			GENERIC = "ハチどものすみかだゼ",
			NOHONEY = "黄金の蜜は…一滴もたまってねェな…",
			SOMEHONEY = "黄金の蜜は…チビっとしかたまってねェな…",
		},
		BEEFALO =
		{
			FOLLOWER = "そうともよ！ワシがてめェのご主人様よ！",
			GENERIC = "お！牛肉がいやがるゼ！",
			NAKED = "ヘヘッ…マヌケなザマだゼ…",
			SLEEPING = "すげェいびきだ…死人もよみがえるゼ…",
		},
		BEEFALOHAT = "これで、耳を冷やさずに済むゼ！",
		BEEFALOWOOL = "ケモノくせェな…",
		BEEHAT = "こんなモン、死んでもかぶらねェぞ！",
		BEEHIVE = "ハチミツ作る連中の巣だゼ",
		BEEMINE = "踏むと、足ィ、ブッ刺されるゼ！",
		BEEMINE_MAXWELL = "踏むと、足ィ、ブッ刺されるゼ！",
		BELL = "うるせェ音で鳴りやがるゼ！",
		BELL_BLUEPRINT = "ワシにァ、さっぱりわからねェな！",
		BERMUDATRIANGLE = "どこへつながってるかって？知るかよッ！",
		BERRIES = "シャツに染みがついちまうゼ…",
		BERRIES_COOKED = "パンの耳につけて、食いてェな！",
		BERRYBUSH =
		{
			BARREN = "肥やしィ、かけてやらねェとダメだゼ",
			GENERIC = "うまそうに熟してるゼ",
			PICKED = "待ってりャ、また実がなるんじゃねェか？",
			WITHERED = "暑さに負けちまったみてェだな",
		},
		BIGFOOT = "てめェ！気ィつけて歩きやがれ！",
		BIOLUMINESCENCE = "こりャ、希望の光だゼ！",
		BIRCHNUTDRAKE = "木の実にしちャ、ずいぶん凶暴じゃねェか！",
		BIRDCAGE =
		{
			GENERIC = "ワシのオウムは、カゴなんかにャ入らねェ",
			OCCUPIED = "よう！オリん中は、どんな具合だ？",
			SLEEPING = "ヘヘ…鳥の野郎、スヤスヤ寝てやがるゼ…",
			HUNGRY = "なんだてめェ、腹減ってんのか？",
			STARVING = "うるせェ！ワシだって腹減ってんだ！",
			DEAD = "死んだヤツの魂は、海に還ってくんだゼ",
			SKELETON = "デイヴィ・“ボーンズ”ってか？",
		},
		BIRDTRAP = "一度入ェッたら、二度と出られねェゼ…",
		BIRD_EGG = "鳥の卵だゼ",
		BIRD_EGG_COOKED = "パンの耳といっしょに、食いてェな！",
		BISHOP = "全身サビついてやがる…油差したらどうだ？",
		BISHOP_NIGHTMARE = "ブリキの怪物め！あっち行きやがれィ！",
		BLOWDART_FIRE = "火ィ吹けるゼ！",
		BLOWDART_FLUP = "この目ン玉…生きてンのかァ？",
		BLOWDART_PIPE = "海の男にャ、ふさわしくねェ武器だゼ",
		BLOWDART_POISON = "海の男にャ、ふさわしくねェ武器だゼ",
		BLOWDART_SLEEP = "敵を眠らしちまう武器だゼ",
		BLUBBER = "ワシの腹は、こんなにたるんでねェぞ！",
		BLUBBERSUIT = "これを着ろだァ？冗談じゃねェ！",
		BLUEAMULET = "寒い。",
		BLUEGEM = "海みてェに真っ青だゼ！",
		BLUEPRINT = "ワシァ、学者じゃねェからよ！",
		BLUE_CAP = "食いモンには…見えねェな…",
		BLUE_CAP_COOKED = "ニオイは、うまそうだけどよ…",
		BLUE_MUSHROOM =
		{
			GENERIC = "ありゃァ…食えンのか…？",
			INGROUND = "夜しか出てこねェのか？",
			PICKED = "また生えてくンのか？",
		},
		BOARDS = "まっすぐ平らな、いい板だゼ",
		BOAT = "ちと小せェが、丈夫なのには違ェねェ",
		BOATCANNON = "6ポンド砲だゼ！",
		BOATREPAIRKIT = "航海の必需品だゼ",
		BOAT_LANTERN = "これで夜も海に出られるゼ",
		BOAT_TORCH = "船につけりャ、夜の海を照らせるゼ",
		BONESHARD = "骨だが…粉々に砕けてやがるゼ",
		BONESTEW = "壊血病予防になるゼ",
		BOOMERANG = "自分の頭ァ直撃する武器は、苦手だゼ…",
		BOTTLELANTERN = "空きビンのランプか…おもしれェな！",
		BUGNET = "うっとうしい虫どもを捕まえる道具だゼ",
		BUNNYMAN = "耳の長げェ野郎は、信用ならねェな！",
		BUOY = "いいよなァ、てめェは…気楽でよゥ…",
		BURIEDTREASURE = "お宝掘り出す瞬間に勝るモンはねェな！",
		BUSHHAT = "陸モンに成りすますゼ！",
		BUSH_VINE =
		{
			BURNT = "燃えちまったら、ただの炭だゼ！",
			CHOPPED = "切っちまったら、ただの草だゼ！",
			GENERIC = "ゴチャゴチャにこんがらがってやがるゼ",
		},
		BUTTER = "バタバタッと作ってみたゼ",
		BUTTERFLY =
		{
			GENERIC = "きれェだ…海に沈む夕日みてェだな…",
			HELD = "きれェな虫、捕まえたゼ！",
		},
		BUTTERFLYMUFFIN = "羽根つきの焼き菓子だゼ",
		BUTTERFLYWINGS = "一番きれェなとこだけ、いただいたゼ",
		BUZZARD = "屍肉をあさる悪魔めッ！",
		CACTUS =
		{
			GENERIC = "トゲのあるヤツだゼ",
			PICKED = "サボテンのヤツ、サボッてやがるゼ…",
		},
		CACTUS_FLOWER = "近づきすぎると、目にトゲが刺さるゼ…",
		CACTUS_MEAT = "トゲはあるが、肉には違げェねェゼ",
		CACTUS_MEAT_COOKED = "意外と、マズくはねェな！",
		CAMPFIRE =
		{
			EMBERS = "火も、腹が減ってんじゃねェか？",
			GENERIC = "海の歌でも歌おうゼ！",
			HIGH = "バチバチ燃えてやがるゼ！",
			LOW = "消えちまいそうだゼ！",
			NORMAL = "あったけェな…",
			OUT = "消えちまったゼ…",
		},
		CANE = "ワシァ、両足に杖がついてるゼ！",
		CAPTAINHAT = "ワシが船長だッ！野郎ども、働けィ！",
		CARGOBOAT = "お宝、たんまり運べるゼ！",
		CARROT = "これ食うと、目がよくなるって話だゼ！",
		CARROT_COOKED = "やらけェから、歯がなくても食えるゼ！",
		CARROT_PLANTED = "あれも、お宝か？",
		CARROT_SEEDS = "陸の生きモンにャ、興味ねェな！",
		CATCOON = "ゴミ集めンのが好きとみえるな",
		CATCOONDEN =
		{
			EMPTY = "奥のほうに隠れてンじゃねェか？",
			GENERIC = "ほんとに動物が住んでンのかァ？",
		},
		CATCOONHAT = "船乗り仲間にャ、見られたくねェ帽子だゼ…",
		CAVE_BANANA = "こいつァ、ホントにバナナか…？",
		CAVE_BANANA_COOKED = "なかなかイケるゼ",
		CAVE_BANANA_TREE = "こんなとこに、バナナの木だァ…？",
		CAVE_ENTRANCE =
		{
			GENERIC = "ワシァ、海の男だ！洞窟なんぞ、ごめんだゼ！",
			OPEN = "地面の下にァ、海は、ねェよな…？",
		},
		CAVE_EXIT = "こっから外へ出られるゼ",
		CAVE_FERN = "日も当たらねェのに、てェしたモンだゼ",
		CHARCOAL = "すっかり炭になってやがるゼ",
		CHESSJUNK1 = "往生際の悪りィヤツだゼ",
		CHESSJUNK2 = "往生際の悪りィヤツだゼ",
		CHESSJUNK3 = "往生際の悪りィヤツだゼ",
		CHESTER = "てめェ…なにモンだ…？",
		CHESTER_EYEBONE =
		{
			GENERIC = "こいつ、なかなかいい目してやがるゼ",
			WAITING = "昼寝中みてェだな",
		},
		CHIMINEA = "これで、風が吹いても火が消えねェな！",
		CLOTHSAIL = "なかなか立派な帆じゃねェか！",
		COCONADE =
		{
			BURNING = "こいつ、果物のクセに爆発しやがるゼ！",
			GENERIC = "トロピカルに弾けるゼ！",
		},
		COCONUT = 
		{
		    GENERIC = "果物ンなかじゃ、一番気に入ってるゼ！",
		    PLANTED = "これじゃもう、食えねェな！",
		},
		COCONUT_COOKED = "火であぶると、風味が増すんだゼ？",
		COFFEE = "ガーッハッハ！見ろ！お宝発見だゼ！",
		COFFEEBEANS = "あとは水を加えるだけだゼ",
		COFFEEBEANS_COOKED = "湯は、ねェのかよ？",
		COFFEEBUSH =
		{
			BARREN = "肥やしィ、かけてやらねェとダメだゼ",
			GENERIC = "黒くて苦げェ汁が作れるゼ！",
			PICKED = "しばらく待ちャ、また実がなるのか？",
			WITHERED = "元気ねェな…コーヒーでもどうだ？",
		},
		COLDFIRE =
		{
			EMBERS = "火が消えちまうゼ",
			GENERIC = "これで暗闇を追っ払えるゼ！",
			HIGH = "この火なら、船に燃え移る心配はねェゼ",
			LOW = "火が、くたばってきたゼ？",
			NORMAL = "ヒンヤリするゼ…",
			OUT = "消えちまったゼ…",
		},
		COLDFIREPIT =
		{
			EMBERS = "火が消えちまうゼ",
			GENERIC = "これで暗闇を追っ払えるゼ！",
			HIGH = "この火なら、船に燃え移る心配はねェゼ",
			LOW = "火が、くたばってきたゼ？",
			NORMAL = "ヒンヤリするゼ…",
			OUT = "消えちまったゼ…",
		},

		COMPASS =
		{
			E = "東だァッ！",
			GENERIC = "羅針盤だゼ",
			N = "北だァッ！",
			NE = "北東だァッ！",
			NW = "北西だァッ！",
			S = "南だァッ！",
			SE = "南東だァッ！",
			SW = "南西だァッ！",
			W = "西だァッ！",
		},
		COOKEDMANDRAKE = "人みてェな草、焼いてみたゼ…",
		COOKEDMEAT = "こいつァ、うまそうだゼ",
		COOKEDMONSTERMEAT = "食ったら腹壊しそうだゼ…",
		COOKEDSMALLMEAT = "こんなんじゃ、食った気しねェゼ…",
		COOKPOT =
		{
			BURNT = "鍋ごと焦げちまったゼ…",
			COOKING_LONG = "気長に待つしかねェな",
			COOKING_SHORT = "もうすぐできるゼ",
			DONE = "うし、食えるゼ！",
			EMPTY = "鍋は、からっぽだゼ",
		},
		COONTAIL = "あのアライグマ、しっぽ落としやがったゼ！",
		CORAL = "ぶつかると、船に穴があくゼ！",
		CORALREEF = "座礁しねェように、気をつけねェとな…",
		CORAL_BRAIN = "ワシを出し抜こうったって、ムダだゼ！",
		CORAL_BRAIN_ROCK = "こいつが、海のブレーンってヤツだな！",
		CORN = "トウモロコシか！今日はツイてるゼ！",
		CORN_COOKED = "焼きトウモロコシは大好物だゼ！",
		CORN_SEEDS = "土に植えりャ、トウモロコシになるゼ！",
		CRAB =
		{
			GENERIC = "お！うまそうな晩メシが歩いてやがるゼ！",
			HIDDEN = "カニの野郎、近くにいやがるゼ…",
		},
		CRABHOLE = "カニの野郎、いいとこに住んでやがるな…",
		CROW =
		{
			GENERIC = "あのオウム、油でもかぶったのか？",
			HELD = "このオウム、洗ってもきれいにならねェな",
		},
		CUTGRASS = "こいつァ、役に立ちそうだゼ",
		CUTLASS = "ハハハーッ！海賊にふさわしい剣だゼ！",
		CUTLICHEN = "こりャ、海藻か…？",
		CUTREEDS = "アシ？ワシには、足はねェけどな！",
		CUTSTONE = "平らに切り出した石だゼ",
		DEADLYFEAST = "こいつァ、食ったらタダじゃすまねェゼ",
		DEAD_SWORDFISH = "いい勝負だったゼ！",
		DECIDUOUSTREE =
		{
			BURNING = "そのうち燃え尽きちまうだろーよ",
			BURNT = "あれじゃ、使いモンにならねェな",
			CHOPPED = "てめェは、いい船になるだろーよ",
			GENERIC = "きれーな髪してンじゃねェか！",
			POISON = "あの木は…味方じゃなさそうだゼ？",
		},
		DEERCLOPS = "カンベンしてくれよ、オイ…",
		DEERCLOPS_EYEBALL = "でけェ目玉だな！",
		DEPLETED_GRASS =
		{
			GENERIC = "あれじゃ、使えねェな",
		},
		DEVTOOL = "こいつァ、摩訶不思議な代物だゼ！",
		DEVTOOL_NODEV = "こいつァ、摩訶不思議な代物だゼ！",
		DIRTPILE = "この下にお宝が眠ってるに違ェねェ！",
		DIVININGROD =
		{
			COLD = "このヘンじゃねェみてェだな…",
			GENERIC = "こいつで、お宝の場所を探り当てるゼ！",
			HOT = "どこだ！？お宝はどこにあるッ！？",
			WARM = "お宝の場所へ連れてってくれィ！",
			WARMER = "お宝が近ェぞ！",
		},
		DIVININGRODBASE =
		{
			GENERIC = "こいつァ、ナゾだゼ…",
			READY = "カギ穴だゼ…",
			UNLOCKED = "っしゃ！開いたゼ！",
		},
		DIVININGRODSTART = "この棒はきっと、お宝だゼ！",
		DOUBLE_UMBRELLAHAT = "作ったヤツは、正気とは思えねェな！",
		DOYDOY = "マヌケなツラしてやがるゼ",
		DOYDOYBABY = "マヌケなツラしたチビ鳥だゼ",
		DOYDOYEGG = "食いモン、見つけたゼ！",
		DOYDOYEGG_CRACKED = "これじゃもう、ただのゴミだゼ",
		DOYDOYFEATHER = "鳥の羽根で作った帆だゼ",
		DOYDOYNEST = "鳥のすみかだゼ",
		DRAGONFLY = "おい！お宝はどこだッ！",
		DRAGONFLYCHEST = "こん中に、お宝がしまってあンだな？",
		DRAGONFRUIT = "こいつァ、おったまげたゼ！",
		DRAGONFRUIT_COOKED = "こいつァ、うまそうだなッ！",
		DRAGONFRUIT_SEEDS = "土に埋めてやらねェとな",
		DRAGONPIE = "こいつァ、パイのお宝だゼ！",
		DRAGON_SCALES = "こいつァ、すげェお宝だゼ！",
		DRAGOON = "おい！ワシに向かって火ィ吹くんじゃねェ！",
		DRAGOONDEN = "お宝、ため込んでんじゃねェか…？",
		DRAGOONEGG = "嵐になりそうだゼ…",
		DRUMSTICK = "うまそうな肉が手に入ェッたゼ！",
		DRUMSTICK_COOKED = "焼きたての肉だ！晩メシにぴったりだゼ！",
		DUBLOON = "お宝だゼ！",
		DUG_BAMBOOTREE = "どっかの地面に植えねェとなァ…",
		DUG_BERRYBUSH = "どっかの地面に植えねェとなァ…",
		DUG_COFFEEBUSH = "どっかの地面に植えねェとなァ…",
		DUG_ELEPHANTCACTUS = "どっかの地面に植えねェとなァ…",
		DUG_GRASS = "どっかの地面に植えねェとなァ…",
		DUG_MARSH_BUSH = "どっかの地面に植えねェとなァ…",
		DUG_SAPLING = "どっかの地面に植えねェとなァ…",
		DURIAN = "こんなクセェもんが、食べ物のわけねェゼ！",
		DURIAN_COOKED = "焼いたら、よけいクサくなったゼ…",
		DURIAN_SEEDS = "こいつァ…種だな",
		EARMUFFSHAT = "クークー音がするゼ…？",
		EARRING = "ワシがなくしたイヤリングだゼ！",
		EEL = "ブキミな魚だゼ！",
		EEL_COOKED = "ブキミな魚を焼いたゼ！",
		EGGPLANT = "きれーな紫色してやがるゼ！",
		EGGPLANT_COOKED = "ハハハ！うまそうにできたゼ！",
		EGGPLANT_SEEDS = "こいつァ…種だな",
		ELEPHANTCACTUS = "用心したほうがよさそうだゼ…",
		ELEPHANTCACTUS_ACTIVE = "ずいぶん血の気の多い草だゼ！",
		ELEPHANTCACTUS_STUMP = "次の攻撃に備えて、力蓄えてやがるゼ…",		
		EVERGREEN =
		{
			BURNING = "これじゃもう、ただのゴミだゼ…",
			BURNT = "種ごと燃えちまったゼ…",
			CHOPPED = "切り株だけは、ずーっと残ってやがるゼ",
			GENERIC = "こいつァ、いい船になりそうだゼ",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "木が燃えてるゼ",
			BURNT = "これじゃ、船造りには使えねェな",
			CHOPPED = "木にしちャ、ちと短すぎるゼ",
			GENERIC = "ずいぶんゴツゴツしてやがるゼ…",
		},
		EYEBRELLAHAT = "しっかり見張れよッ！",
		EYEPLANT = "こっち見てやがるゼ…",
		EYETURRET = "魔法の大砲だゼ",
		EYETURRET_ITEM = "どっかに設置しねェと、意味ねェな…",
		FABRIC = "こいつァ、いい帆になりそうだゼ！",
		FARMPLOT =
		{
			BURNT = "真っ黒焦げだゼ",
			GENERIC = "ここに種ェ植えると、育つらしいゼ？",
			GROWING = "ニョキニョキ育ってやがるゼ",
			NEEDSFERTILIZER = "この土、腹ァ減ってるみてェだな",
		},
		FEATHERFAN = "顔に風ェ集める帆みてェなもんだ",
		FEATHERHAT = "鳥のお宝でできた帽子だゼ",
		FEATHERSAIL = "羽根みてェに軽りィな！",
		FEATHER_CROW = "油かぶったみてェに、真っ黒だゼ",
		FEATHER_ROBIN = "ワシァ、くすぐられても笑わねェぞ！",
		FEATHER_ROBIN_WINTER = "おい！色は、どこいっちまったんだァ？",
		FEM_PUPPET = "オメェさん、相当困ってるみてェだな",
		FERTILIZER = "草に栄養やりてェときに使うんだ",
		FIREFLIES =
		{
			GENERIC = "星座か？ちっこすぎて、目印にァならねェな",
			HELD = "ちっこい星を捕まえたゼ！",
		},
		FIREHOUND = "ワシの足に近寄るな！燃えちまうだろーが！",
		FIREPIT =
		{
			EMBERS = "燃え尽きそうだゼ",
			GENERIC = "足に燃え移らねェようにしねェとな",
			HIGH = "船に燃え移ったら大変だゼ…",
			LOW = "薪を足したほうがよくねェか？",
			NORMAL = "あんまり近づくと危ねェぞ",
			OUT = "消えちまったゼ…",
		},
		FIRESTAFF = "火遊びすると、ロクなことねェぞ？",
		FIRESUPPRESSOR =
		{
			LOWFUEL = "燃料が切れかけてるゼ",
			OFF = "今、火事が起きたらおしまいだゼ…",
			ON = "これで火事の心配はねェな",
		},
		FISH = "ワシは、魚も好物だゼ！",
		FISHINGROD = "便利な道具だゼ",
		FISHINHOLE = "釣りスポットだ！地図に印つけろィ！",
		FISHSTICKS = "魚を、棒っ切れみてェにしたゼ",
		FISHTACOS = "カリカリしてて、うめェじゃねェか！",
		FISH_COOKED = "絶妙な焼き加減だゼ！",
		FISH_MED = "ただの切り身になっちまったゼ",
		FISH_MED_COOKED = "生よりャマシになったゼ",
		FISH_RAW = "火ィ通したほうがいいんじゃねェか？",
		FISH_RAW_SMALL = "これじゃ腹の足しになんねェな…",
		FISH_RAW_SMALL_COOKED = "生よりャマシになったゼ",
		FLAMEGEYSER = "「火の海」ってなァ、こいつのことか？",
		FLINT = "ずいぶんトガッた石だゼ！",
		FLOTSAM = "船の残骸だゼ",
		FLOWER = "きれいな花じゃねーか",
		FLOWERHAT = "きれいな花で作った帽子だゼ",
		FLOWERSALAD = "きれいな花で作った飯だゼ",
		FLOWER_CAVE = "きれいな花が咲いてやがるゼ",
		FLOWER_CAVE_DOUBLE = "きれいな花が咲いてやがるゼ",
		FLOWER_CAVE_TRIPLE = "きれいな花が咲いてやがるゼ",
		FLOWER_EVIL = "こいつァ、まともな花じゃねェな！",
		FLUP = "てめェは、泥ンなか潜ってろィ！",
		FOLIAGE = "地べたに生えてる草だゼ",
		FOOTBALLHAT = "これかぶってりャ、頭は安全だゼ",
		FROG =
		{
			DEAD = "死人は海の底に沈んでろィ！",
			GENERIC = "こっち来んじゃねェぞ！",
			SLEEPING = "悪魔の使いが、寝てやがるゼ…",
		},
		FROGGLEBUNWICH = "両生類のサンドイッチだゼ！",
		FROGLEGS = "どっかに、義足つけたカエルがいるゼ！",
		FROGLEGS_COOKED = "弾力のある鶏肉ってとこだな！",
		FROG_POISON = "毒ガエルめ、こっち来んじゃねェぞ！",
		GASHAT = "頭にかぶりャ、空気がさわやかになるゼ",
		GEMSOCKET =
		{
			GEMS = "宝石がはまってるゼ",
			VALID = "お宝が足りねェみてェだ",
		},
		GHOST = "ワシァ、オメェさんに用はねェよ！",
		GLOMMER = "ワシの船の一等航海士にしてやるゼ！",
		GLOMMERFLOWER =
		{
			DEAD = "すっかり干からびちまってるゼ",
			GENERIC = "なんかと、つながってるみてェだな…",
		},
		GLOMMERFUEL = "甲板が汚れるが、嫌いじゃねェぞ！",
		GLOMMERWINGS = "ネチョネチョのお宝を落としやがった！",
		GOATMILK = "海じゃ、新鮮な牛乳は、なかなか飲めねェ！",
		GOLDENAXE = "お宝の使い道としちャ、珍しいな",
		GOLDENMACHETE = "ずっしり重いゼ…",
		GOLDENPICKAXE = "ずいぶん柔らけェ金属でできてンなァ…",
		GOLDENPITCHFORK = "こんなお宝で掘られる土は、ラッキーだゼ",
		GOLDENSHOVEL = "お宝埋めンのに、ちょうどいいゼ！",
		GOLDNUGGET = "黄金見てッと、心が落ち着くゼ…",
		GOOSE_FEATHER = "ずいぶん、でけェ鳥がいるみてェだな！",
		GRASS =
		{
			BARREN = "あれじゃ、使えねェな",
			BURNING = "あんまり近寄ると、脚が燃えちまうゼ",
			GENERIC = "草が生えてやがるゼ",
			PICKED = "とっとと生えてきやがれィ！",
			WITHERED = "あれじゃァ、使いモンにならねェな",
		},
		GRASS_UMBRELLA = "チビッとぬれるぐれェ、どーってことねェ",
		GRASS_WATER = "ずいぶん、喉が渇ェてるみてェだな！",
		GREENAMULET = "賢くなった気分だゼ！",
		GREENGEM = "お宝だ！エメラルドだゼ！",
		GREENSTAFF = "便利な魔術は、ジャンジャン活用するゼ！",
		GREEN_CAP = "他に食うモンねェなら、しかたねェな…",
		GREEN_CAP_COOKED = "まじない師に、これと似た薬もらったなァ…",
		GREEN_MUSHROOM =
		{
			GENERIC = "海じゃ、なかなかお目にかかれねェな",
			INGROUND = "海抜ゼロ以下に沈んじまってるゼ",
			PICKED = "留守みてェだ…海に出てンのかもなァ",
		},
		GUACAMOLE = "コーンチップスがありャ、完ぺきだゼ！",
		GUNPOWDER = "破壊力バツグンだゼ！",
		HAIL_ICE = "義足がガタガタ震えるゼ…！",
		HAMBAT = "最高級肉でつくった、強力な武器だゼ！",
		HAMMER = "こいつで殴りャ、船にも穴があくだろーよ！",
		HAWAIIANSHIRT = "軽い着心地の、しゃれたシャツだゼ",
		HEALINGSALVE = "傷をいやす薬だゼ",
		HEATROCK =
		{
			COLD = "ワシの大事な石だ！ひんやりしてやがるゼ",
			FROZEN = "ワシの大事な石だ！氷みてェに冷てェ！",
			GENERIC = "こいつァ、ワシの大事な石だ！",
			HOT = "ワシの大事な石だ…ちと熱ちィな",
			WARM = "ワシの大事な石だ！あったけェ！",
		},
		HOME = "船長室だゼ",
		HOMESIGN =
		{
			BURNT = "なんかの目印だったんだろーよ…",
			GENERIC = "何か、重要なモンのありかの印だろーな…",
		},
		HONEY = "ベタベタしてて、甘いゼ",
		HONEYCOMB = "中にャ、ウジ虫がウヨウヨしてるゼ",
		HONEYHAM = "海賊にぴったりのごちそうだゼ！",
		HONEYNUGGETS = "こいつァ、黄金の塊か！？",
		HORN = "ビーファローの歌を吹こうゼ！",
		HOTCHILI = "ワシの舌は木製だから、からいモンも平気だ！",
		HOUND = "怪物が来やがったゼ",
		HOUNDBONE = "なんかの骨だろーよ",
		HOUNDMOUND = "ハウンドどものすみかだゼ",
		HOUNDSTOOTH = "こいつを集めりャ、入れ歯作れるゼ！",
		ICE = "航海に持ってくにャ、向いてねェな",
		ICEBOX = "食料入れとくと、長持ちするゼ",
		ICECREAM = "暑ちィ日に食うと格別だゼ",
		ICEHAT = "頭が冷えて気持ちいいゼ",
		ICEHOUND = "あいつの牙は、氷みてェに冷てェんだ",
		ICEMAKER =
		{
			HIGH = "絶好調だゼ",
			LOW = "プスプス言ってやがるゼ…",
			NORMAL = "ちゃァんと動いてるゼ",
			OUT = "ガス欠だゼ",
			VERYLOW = "虫の息だゼ",
		},
		ICEPACK = "北の海みてェに、冷たてェカバンだゼ",
		ICESTAFF = "氷みてェに冷てェ杖だゼ",
		INSANITYROCK =
		{
			ACTIVE = "近くに寄ると、頭が痛てェゼ…",
			INACTIVE = "不気味なオーラが漂ってるゼ…",
		},
		IRONWIND = "船は帆船に限るゼ",
		JAMMYPRESERVES = "うまそうじゃねェか",
		JELLYFISH = "ビビるほどブヨブヨだゼ",
		JELLYFISH_COOKED = "ビビるほどうめェぞ",
		JELLYFISH_DEAD = "ビビるほど動かねェな",
		JELLYFISH_PLANTED = "ビビるほど危険な魚だゼ",
		JELLYJERKY = "干しても食えるたァ、驚いたゼ",
		JUNGLETREE =
		{
			BURNING = "明々と燃えてやがるゼ",
			BURNT = "炭みてェなニオイだゼ",
			CHOPPED = "お宝はもう、取り尽くしちまったゼ",
			GENERIC = "この木からは、いろんなお宝が手に入るゼ",
		},
		JUNGLETREESEED =
        {
            GENERIC = "木に育ったら、新しい義足でも作るか…",
            PLANTED = "義足を4、5本に増やすのも、いいかもナ！",
        },
		KABOBS = "海賊にふさわしいメシだゼ！",
		KILLERBEE =
		{
			GENERIC = "あいつァ、仲間って雰囲気じゃねェな",
			HELD = "ヘヘヘ…捕まえてやったゼ…",
		},
		KNIGHT = "騎兵隊が来やがったゼ！",
		KNIGHTBOAT = "海軍が出てきやがったゼ…！",
		KNIGHT_NIGHTMARE = "どした？具合悪いそうだゼ？",
		KOALEFANT_SUMMER = "あの毛皮ァ、あったかそうだゼ",
		KOALEFANT_WINTER = "あの毛皮ァ、モフモフで、あったかそうだゼ",
		KRAMPUS = "ワシが何をしたってんだ、アア？",
		KRAMPUS_SACK = "ワシのお宝、取り返せてよかったゼ…",
		LANTERN = "こいつァ、いいランプだゼ",
		LAVAPOOL = "踏んだら、義足が燃えちまうゼ",
		LAVASPIT =
		{
			COOL = "もう、踏んでも大丈夫そうだゼ",
			HOT = "ありゃァ、ずいぶん熱そうだゼ",
		},
		LEIF = "義足まで怪物にならなくて、よかったゼ！",
		LEIF_SPARSE = "義足まで怪物にならなくて、よかったゼ！",
		LICHEN = "しかたねェ…食うか…",
		LIGHTBULB = "これで、夜でも周りが見えるゼ",
		LIGHTNINGGOAT =
		{
			CHARGED = "あんまり近づくと、危ねェな…",
			GENERIC = "すげェ形のツノだな…",
		},
		LIGHTNINGGOATHORN = "殴んのにちょうどいいゼ",
		LIGHTNING_ROD =
		{
			CHARGED = "助かったゼ！",
			GENERIC = "天罰から守ってくれるゼ",
		},
		LIMESTONE = "船造りには、使えそうにねェな",
		LIMPETROCK =
		{
			GENERIC = "あの岩、うまそうなモンに覆われてやがる…",
			PICKED = "貝がついてねェと、ただの岩だな",
		},
		LIMPETS = "すぐに食ってやるゼ…",
		LIMPETS_COOKED = "こいつァ、うめェええ！",
		LITTLE_WALRUS = "あのチビ、いい海賊になりそうだゼ",
		TREEGUARD = "ワシの足も木製だ！オメェとは親戚だゼ！",
		LIVINGJUNGLETREE = "あの木の目つき、気に入らねェ…",
		LIVINGLOG = "こいつァ、呪われてやがるゼ",
		LIVINGTREE = "起こさねェようにな…",
		LOBSTER = "ワシから逃げようたァ、いい度胸だゼ！",
		LOBSTERHOLE = "エビの野郎のすみかだゼ",
		LOBSTER_DEAD = "うし！食ってやるゼッ！",
		LOBSTER_DEAD_COOKED = "これぞ、海の幸だゼ！",
		LOCKEDWES = "誰か、捕まってやがるゼ！",
		LOG =
		{
			BURNING = "近づくと危ねェぞ！",
			GENERIC = "ワシの義足の兄弟だな！",
		},
		LOGRAFT = "すぐ壊れちまいそうだな…",
		LUGGAGECHEST = "黄金が入ってるかもしれねェ…",
		LUREPLANT = "人のモンくすねる草だ…油断ならねェゼ",
		LUREPLANTBULB = "盗賊草の心臓だゼ",
		MACHETE = "切れ味バツグンだゼ！",
		MAGIC_SEAL = "こいつァ…なんだ？",
		MAGMAROCK = "掘ったら、なんか出てくるかもな",
		MAGMAROCK_GOLD = "黄金の岩だゼ！",
		MALE_PUPPET = "誰か、捕まってやがるゼ！",
		MANDRAKE =
		{
			DEAD = "これで静かになったゼ",
			GENERIC = "伝説の草だゼ",
			PICKED = "キーキーうるせェな！",
		},
		MANDRAKESOUP = "魔法の水薬だゼ",
		MANDRAKE_COOKED = "ワシの手料理だゼ！",
		MANGROVETREE = "このヘンは浅瀬になってやがるゼ",
		MANGROVETREE_BURNT = "こんがり焼けちまってるゼ…",
		MANRABBIT_TAIL = "幸運のお守りだゼ！",
		MARBLE = "スベスベの頑丈な石だゼ",
		MARBLEPILLAR = "こいつァ、巨人の義足じゃねェか？",
		MARBLETREE = "妙な木だゼ…",
		MARSH_BUSH =
		{
			BURNING = "燃えてるゼ",
			GENERIC = "細っこい剣で武装してやがるゼ",
			PICKED = "てめェ、よくも刺してくれたな！",
		},
		MARSH_PLANT = "人魚姫の瞳みてェな色だゼ…",
		MARSH_PLANT_TROPICAL = "人魚姫の瞳みてェな色だゼ…",
		MARSH_TREE =
		{
			BURNING = "燃えてるゼ",
			BURNT = "義足まで燃えなくてよかったゼ！",
			CHOPPED = "切り株だけになっちまったゼ…",
			GENERIC = "短剣で武装してやがるゼ",
		},
		MAXWELL = "あンの野郎…！海に突き落としてやる…！",
		MAXWELLHEAD = "悪そうな目ェしてやがるゼ…",
		MAXWELLLIGHT = "黒い炎だゼ…",
		MAXWELLLOCK = "宝箱じゃァ、なさそうだゼ…",
		MAXWELLPHONOGRAPH = "つい、聞き入っちまうゼ…",
		MAXWELLTHRONE = "あすこに座りてェとは、思わねェな",
		MEAT = "獣の肉だゼ",
		MEATBALLS = "昼メシにぴったりだゼ！",
		MEATRACK =
		{
			BURNT = "燃えちまったゼ…",
			DONE = "完成だゼ！",
			DRYING = "待ち遠しいゼ…！",
			DRYINGINRAIN = "これじゃ、渇かねェな…",
			GENERIC = "肉をつるしャ、干し肉作れるゼ",
		},
		MEAT_DRIED = "長げェ航海にも持ってけるゼ！",
		MERM = "フン！半人前が…",
		MERMFISHER = "魚釣ってくれンなァ、ありがてェけどよ",
		MERMHEAD =
		{
			BURNT = "こんがり焼けてるゼ",
			GENERIC = "用心したほうがいいゼ…",
		},
		MERMHOUSE =
		{
			BURNT = "ああせいせいした。",
			GENERIC = "こいつらは、信用ならねェ…",
		},
		MERMHOUSE_FISHER = "ワシよりクセェやつらがいたとはな！",
		MESSAGEBOTTLE = "ヒヒヒ…こいつァ、宝の地図かもな！",
		MESSAGEBOTTLEEMPTY = "からっぽだゼ",
		MINERHAT = "暗い海も照らせるゼ",
		MINOTAUR = "こいつの伝説は、聞いたことあるゼ…",
		MINOTAURCHEST = "こんなでけェ箱、どうやって船に乗せンだ！？",
		MINOTAURHORN = "こいつァ正真正銘、お宝だゼ！",
		MOLE =
		{
			ABOVEGROUND = "なんのニオイを嗅いでやがンだ？",
			HELD = "おとなしくしやがれィ！",
			UNDERGROUND = "土ン中を泳いでやがるゼ！",
		},
		MOLEHAT = "夜でも、幽霊みてェに目が利くゼ",
		MOLEHILL = "土ン中で寝てやがるゼ",
		MONKEY = "手がフックになったサル、見たことあるゼ",
		MONKEYBARREL = "中にお宝隠してやがるに違ェねェ",
		MONSTERLASAGNA = "できれば遠慮してェとこだな…",
		MONSTERMEAT = "ちと、酸っぺェな",
		MONSTERMEAT_DRIED = "魔物を日干しにしてやったゼ",
		MOOSE = "ワシの船に近づくんじゃねェぞ！",
		MOOSEEGG = "中に魔物が潜んでやがる！",
		MOSQUITO =
		{
			GENERIC = "ブンブンうっとうしィ音させやがって…",
			HELD = "ワシのポケット、食い破らねェだろーな…",
		},
		MOSQUITOSACK = "ブヨブヨして、クラゲみてェだな",
		MOSQUITOSACK_YELLOW = "気色悪りィ色だゼ…",
		MOSQUITO_POISON = "シッ！あっちいけ、害虫め！",
		MOSSLING = "でっけェ、アヒルだゼ！",
		MOUND =
		{
			DUG = "お宝があンなら、掘らねェ手はねェよ！",
			GENERIC = "銀貨の隠し場所としちャ、上等だな",
		},
		MULTITOOL_AXE_PICKAXE = "1本で2役だゼ",
		MUSHTREE_MEDIUM = "キノコの木ィ？意味がわからねェな…",
		MUSHTREE_SMALL = "光ってやがるゼ！",
		MUSHTREE_TALL = "キノコにしちャ、ちと、でかくねェか…？",
		MUSSEL = "ワシの大好物だゼ！",
		MUSSEL_COOKED = "海賊のごちそうだゼ！",
		MUSSEL_FARM =
		{
			GENERIC = "根こそぎ、いただこうゼ！",
			STICKPLANTED = "待ってるだけってなァ、性に合わねェゼ…",
		},
		MUSSEL_STICK = "これで、ムール貝をおびき寄せるゼ…",
		NEEDLESPEAR = "短剣の一種だろーよ",
		NIGHTLIGHT = "どうも心がざわつくゼ…",
		NIGHTMAREFUEL = "これとよく似たモンを、海で見たことあるゼ…",
		NIGHTMARELIGHT = "こいつァ、見るからに怪しいゼ…",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "静かなモンだゼ",
			DAWN = "そろそろ終わりそうだゼ…",
			NOMAGIC = "反応ナシだゼ",
			STEADY = "悪夢のまっただ中だゼ！",
			WANING = "少し収まってきたんじゃねェか…？",
			WARN = "どうもおかしな気配がしやがるゼ…",
			WAXING = "魔力が強くなってやがる…！",
		},
		NIGHTSTICK = "光る剣だゼ！",
		NIGHTSWORD = "ワシの愛剣、「呪いのカットラス」だゼ！",
		NITRE = "砲弾の材料だゼ",
		OBSIDIAN = "こいつァ、すげェ力を秘めてるゼ…",
		OBSIDIANAXE = "義足が燃えねェように気ィつけねェと！",
		OBSIDIANCOCONADE = "なかなかの爆発力だゼ！",
		OBSIDIANFIREPIT =
		{
			EMBERS = "燃え尽きそうだゼ",
			GENERIC = "足に燃え移らねェようにしねェとな",
			HIGH = "船に燃え移ったら大変だゼ…",
			LOW = "薪を足したほうがよくねェか？",
			NORMAL = "普通の火ィより熱ィゼ！",
			OUT = "消えちまったゼ…",
		},
		OBSIDIANMACHETE = "触るとヤケドしそうだゼ！",
		OBSIDIANSPEARGUN = "炎を撃ち込む武器だゼ！",
		OBSIDIAN_WORKBENCH = "伝説は本当だったみてェだな…",
		OCTOPUSCHEST = "さァて、お宝をいただくゼ…",
		OCTOPUSKING = "おメェさんも、海の男だな！",
		ONEMANBAND = "なんのイミがあんだァ…？",
		ORANGEAMULET = "魔法のペンダントだゼ",
		ORANGEGEM = "ワシァ、宝石全般に目がなくてよ！",
		ORANGESTAFF = "魔法の義足だゼ！",
		OX = "海賊の仲間を欲しがってるみてェだな！",
		PACKIM = "ワシの相棒だゼ！",
		PACKIM_FISHBONE = "ワシの相棒の、心臓みてェなもンだ",
		PALMLEAF = "なんかの材料に使えそうだゼ…",
		PALMLEAF_HUT = "ハンモックがありャ、言うことねェけどな！",
		PALMLEAF_UMBRELLA = "海賊も、傘ぐれェさすんだゼ？",
		PALMTREE =
		{
			BURNING = "明々と燃えてやがるゼ",
			BURNT = "炭みてェなニオイだゼ",
			CHOPPED = "お宝はもう、取り尽くしちまったゼ",
			GENERIC = "木陰に入ると涼しいゼ…",
		},
		PANDORASCHEST = "ヨーホーホー！お宝だゼ！",
		PANFLUTE = "音色を聞くと、魔法の眠りに落ちちまうゼ…",
		PAPYRUS = "まっさらな地図だゼ！",
		PARROT = "賢い鳥だゼ",
		PENGUIN = "こいつは、海が凍ってる証拠だゼ",
		PERD = "クソいまいましい鳥だゼ！",
		PEROGIES = "宝箱一杯分でも食えるゼ！",
		PETALS = "摘んじまった花は、もう生き返らねェ",
		PETALS_EVIL = "不気味な花だゼ",
		PICKAXE = "お宝を掘り当てるゼ！",
		PIGGUARD = "ブーブーうるせェな！",
		PIGGYBACK = "ブタの皮で作った袋だゼ",
		PIGHEAD =
		{
			BURNT = "パリパリ。",
			GENERIC = "ときどき、目が光るゼ…",
		},
		PIGHOUSE =
		{
			BURNT = "すっかり火に飲まれちまったな…",
			FULL = "オーイ、ブタ公！出てきやがれィ！",
			GENERIC = "こいつァ、便所じゃねェのかよ？",
			LIGHTSOUT = "寝る時間だとよ",
		},
		PIGKING = "ずいぶん羽振りがよさそうだな",
		PIGMAN =
		{
			DEAD = "おつかれさん",
			FOLLOWER = "オイ、ブタ公！ついてこい！",
			GENERIC = "こいつァ…ラテン語でしゃべんのか？",
			GUARD = "ブーブーうるせェな！",
			WEREPIG = "こいつ、様子がおかしいゼ…！",
		},
		PIGSKIN = "皮だけになっちまったゼ…",
		PIGTENT = "中に誰かいンのか？",
		PIGTORCH = "ずいぶんと豪華な明かりじゃねェか…",
		PIKE_SKULL = "見なかったことにしようゼ",
		PINECONE =
		{
			GENERIC = "木の種だゼ",
			PLANTED = "木に育ったら、船用の木材になるゼ",
		},
		PIRATEHAT = "ヨーホーホー！",
		PIRATEPACK = "フゥ…なくしたかと思ったゼ…！",
		PIRATIHATITATOR =
		{
			BURNT = "もったいねェな…",
			GENERIC = "その帽子、よく似合ってるゼ！",
		},
		PITCHFORK = "こいつでお宝掘れんのか？",
		PLANTMEAT = "この肉、怪しいゼ…",
		PLANTMEAT_COOKED = "焼いてみたゼ",
		PLANT_NORMAL =
		{
			GENERIC = "こいつァ、食えンのか…？",
			GROWING = "いつまで待ちャいいンだよ…？",
			READY = "うし！食えるゼ！",
			WITHERED = "暑すぎて、くたばっちまったみてェだな",
		},
		POISONHOLE = "近づくと痛ェ目に遭うゼ",
		POMEGRANATE = "食べると、心臓にいいンだとよ",
		POMEGRANATE_COOKED = "種が多い。",
		POMEGRANATE_SEEDS = "種ばっかしの果物の種だ",
		POND = "船は入れそうにねェな",
		POND_ALGAE = "船は入れそうにねェな",
		POOP = "誰だ、こんなとこでクソしたのは！",
		PORTAL_SHIPWRECKED = "こいつァ、愉快な船だゼ！",
		POTTEDFERN = "草の家ェ？ンなもん、なんに使うんだ？",
		POWCAKE = "こいつァ、食えンのか？",
		PRIMEAPE = "割れた鏡で見たワシの顔そっくりだゼ",
		PRIMEAPEBARREL = "掃除は、しねェ主義とみえるな",
		PUMPKIN = "砲弾の代わりに使えそうだゼ",
		PUMPKINCOOKIE = "歯がねェから、硬ェモン食うのは大変だ",
		PUMPKIN_COOKED = "シナモンかけると、うめェらしいゼ？",
		PUMPKIN_LANTERN = "ランプにしちャ、ちと重ェな",
		PUMPKIN_SEEDS = "畑仕事は好かねェが、カボチャは食いてェな",
		PURPLEAMULET = "ワシによく似合うゼ！",
		PURPLEGEM = "ヘヘヘ…宝石はいいもんだゼ？",
		RABBIT =
		{
			GENERIC = "プルプル震えてやがるゼ",
			HELD = "捕まえたゼ",
		},
		RABBITHOLE =
		{
			GENERIC = "中に、お宝があるかもしれねェな…",
			SPRING = "これじゃ、ウサ公どもが出てこれねェな…",
		},
		RABBITHOUSE =
		{
			BURNT = "燃え尽きちまってるゼ",
			GENERIC = "ずいぶん、でけェニンジンだな",
		},
		RAFT = "こんなモンに乗ったら、海賊の名がすたるゼ！",
		RAINCOAT = "シャツがぬれずに済むゼ",
		RAINHAT = "頭がぬれずに済むゼ",
		RAINOMETER =
		{
			BURNT = "火事の予測は、つかなかったとみえるな！",
			GENERIC = "空模様を読むなァ、船乗りの仕事だゼ！",
		},
		RATATOUILLE = "壊血病が一発で治るゼ！",
		RAWLING = "前に飼ってたオウムを思い出すゼ",
		RAZOR = "海賊は、ヒゲをそらねェもんだ",
		REDBARREL = "このマークには、親しみを覚えるゼ…",
		REDGEM = "太陽みてェに光ってやがるゼ！",
		RED_CAP = "赤は警告の色じゃねェのか…？",
		RED_CAP_COOKED = "赤いキノコが、一番好きだゼ",
		RED_MUSHROOM =
		{
			GENERIC = "赤か…食っても平気なのか…？",
			INGROUND = "しばらく潜っていてェ気分らしいゼ",
			PICKED = "もう摘んじまったゼ",
		},
		REEDS =
		{
			BURNING = "すげェ勢いで燃えてやがるゼ！",
			GENERIC = "こいつァ、いい笛になりそうだゼ！",
			PICKED = "全部、摘んじまったゼ",
		},
		REFLECTIVEVEST = "おてんとさんの光をはね返すゼ！",
		RELIC =
		{
			BROKEN = "これじゃ、金貨1枚分にもなりャしねェ",
			GENERIC = "闇市場で売れるかもしれねェな",
		},
		RESEARCHLAB =
		{
			BURNT = "カガクも、火にはかなわねェってか？",
			GENERIC = "こりャ、カガクってヤツだな？",
		},
		RESEARCHLAB2 =
		{
			BURNT = "どう見ても壊れてるゼ…",
			GENERIC = "こいつァ、なんの道具だ？",
		},
		RESEARCHLAB3 =
		{
			BURNT = "黒魔術も、火にはかなわねェってか？",
			GENERIC = "こりャ、呪術の道具だな！",
		},
		RESEARCHLAB4 =
		{
			BURNT = "面倒くせェ名前だったから、せいせいしたゼ",
			GENERIC = "ぱいれー…つぇ…歯がねェから言いにくいゼ",
		},
		RESURRECTIONSTATUE =
		{
			BURNT = "身代わりが先にくたばっちゃ、世話ねェな…",
			GENERIC = "ちっともワシに似てねェな！",
		},
		RESURRECTIONSTONE = "呪術のニオイがプンプンするゼ…",
		ROBIN =
		{
			GENERIC = "おめェさん、しゃべれねェのか？",
			HELD = "ワシが、ちゃァんと面倒見てやッからよ",
		},
		ROBIN_WINTER =
		{
			GENERIC = "きれーな鳥じゃねェか",
			HELD = "冷てェ鳥だな、オイ",
		},
		ROBOT_PUPPET = "あいつ、捕まってやがるゼ！",
		ROCK = "船に当たったら、穴が開いちまうゼ",
		ROCKS = "海に落とすと沈むゼ",
		ROCKY = "ハサミの怪物め！あっち行きやがれィ！",
		ROCK_CHARCOAL = "盛大にバーベキューできそうだゼ",
		ROCK_ICE =
		{
			GENERIC = "船でぶつかると、沈没しかねねェからな",
			MELTED = "水ンなっちまってるゼ",
		},
		ROCK_ICE_MELTED = "寒くなったら、また凍るんじゃねェか？",
		ROCK_LIGHT =
		{
			GENERIC = "火の水たまり…てこたァ…「火だまり」か",
			LOW = "消えちまってるゼ",
			NORMAL = "ここらでちょいと、一休みしねェか？",
			OUT = "消えてるゼ",
		},
		ROCK_OBSIDIAN = "火の山が吐き出した、火の岩だゼ",
		ROOK = "突進してきやがるゼ！",
		ROOK_NIGHTMARE = "ありゃ、呪われた魔物だゼ…",
		ROPE = "物をしばるのに使う道具だゼ",
		ROTTENEGG = "ワシの船の船員室も、こんなニオイだったゼ",
		ROWBOAT = "手こぎィ？んなモン、子どものおもちゃだゼ！",
		RUBBLE = "ガレキの山だゼ",
		RUINSHAT = "こいつァ、お宝ン中のお宝だゼ！",
		RUINS_BAT = "こいつァ、見事なお宝だゼ！",
		RUINS_RUBBLE = "修理できそうだゼ",
		SAIL = "こいつで、風を捕まえるゼ！",
		SAIL_STICK = "こいつがありャ、いつでも追い風だゼ！",
		SAND = "陸のかけらだゼ",
		SANDBAG = "こいつを置きャ、水を食い止められるゼ！",
		SANDBAGSMALL = "こいつを置きャ、水を食い止められるゼ！",
		SANDBAG_ITEM = "こいつを置きャ、水を食い止められるゼ！",
		SANDHILL = "義足の裏に心地いいゼ…",
		SAND_CASTLE =
		{
			GENERIC = "砂の城造りなら、ワシに任しとけィ！",
			SAND = "砂の城造りなら、誰にも負けねェゼ！",
		},
		SANITYROCK =
		{
			ACTIVE = "妙な形した岩だゼ…",
			INACTIVE = "前はもっとデカくなかったか…？",
		},

		SAPLING =
		{
			BURNING = "ちっせェ木が燃えてるゼ",
			GENERIC = "ちっせェ木だな",
			PICKED = "しばらく生えてこねェだろーな",
			WITHERED = "ラム酒でも飲んで、元気出しやがれィ！",
		},
		SEAGULL = "うっとうしい害鳥だゼ",
		SEAGULL_WATER = "おめェさんも、海の男だな！",
		SEASACK = "航海には、うってつけの袋だゼ",
		SEASHELL = "波の音が聞こえてくるゼ",
		SEASHELL_BEACHED = "海のお宝だゼ",
		SEATRAP = "海賊は、こうやって食料確保すんだゼ",
		SEAWEED = "索具に絡まるとやっかいだゼ",
		SEAWEED_COOKED = "こんなのは、食いモンじゃねェ！",
		SEAWEED_DRIED = "干し肉だと思って食えってか？",
		SEAWEED_PLANTED = "索具に絡まるとやっかいだゼ",
		SEEDS = "土いじりは陸モンの仕事だゼ！",
		SEEDS_COOKED = "ワシの腹ン中に埋めてやるゼ",
		SEWING_KIT = "縫いモンなんざァ、下っ端の仕事だゼ",
		SHARKITTEN = "そんな目で見ねェでくれよ、頼むゼ…",
		SHARKITTENSPAWNER =
		{
			GENERIC = "中で子ネコがツメ研いでやがるゼ",
			INACTIVE = "オーイ、ニャンコロ！いねェのか？",
		},
		SHARK_FIN = "魔物が舵を落としやがったゼ",
		SHARK_GILLS = "死んだ魚にャ、必要ねェな！",
		SHARK_TEETHHAT = "魔物の歯を頭にかぶるだァ？正気か？",
		SHARX = "海の魔物が出やがったゼ！",
		SHOVEL = "黄金を掘り当てるゼ！",
		SIESTAHUT =
		{
			BURNT = "これじゃァもう、昼寝はできねェな",
			GENERIC = "陸で寝るのは、落ち着かねェゼ…",
		},
		SILK = "上等な海賊シャツが作れそうだゼ！",
		SKELETON = "運に見放されたか…残念だったな",
		SKELETON_PLAYER = "こいつ、どっかで見たことあるゼ…",
		SKULLCHEST = "中に、どんなお宝が眠ってんだ…？",
		SLOTMACHINE = "ワシの人生、運任せよ！",
		SLURPER = "気色悪りィな…",
		SLURPERPELT = "ひでェニオイだゼ！",
		SLURPER_PELT = "ひでェニオイだゼ！",
		SLURTLE = "気色悪りィ連中だゼ…",
		SLURTLEHAT = "こいつを、かぶれだァ…？",
		SLURTLEHOLE = "ヌルついた連中のたまり場だゼ",
		SLURTLESLIME = "咳したときに出るヤツじゃねェのか？",
		SLURTLE_SHELLPIECES = "ワシァ、パズルは苦手だゼ…",
		SMALLBIRD =
		{
			GENERIC = "こいつァ…どういう種類の鳥だ？",
			HUNGRY = "どうした？腹ァ減ってんのか？",
			STARVING = "このままじゃ、餓死しちまうゼ",
		},
		SMALLMEAT = "ちっせェが、肉には変わりねェ",
		SMALLMEAT_DRIED = "うまそうな干し肉だゼ！",
		SNAKE = "舌が2枚…てめェ、悪魔だな！",
		SNAKEDEN =
		{
			BURNT = "燃えちまったら、ただの炭だゼ！",
			CHOPPED = "切っちまったら、ただの草だゼ！",
			GENERIC = "ゴチャゴチャにこんがらがってやがるゼ",
		},
		SNAKEOIL = "こいつァ、買わなきゃ損だゼ！",
		SNAKESKIN = "こいつで、新しい服が作れそうだゼ！",
		SNAKESKINHAT = "こいつを、かぶれだァ…？",
		SNAKE_POISON = "悪魔の手先め…あっち行きやがれィ！",
		SNURTLE = "船がありャ、てめェなんざ一撃だゼ！",
		SOLOFISH = "おめェさんも、海の男だな！",
		SPEAR = "こいつァ、なかなかいい武器だゼ",
		SPEARGUN = "敵のドテッ腹にぶち込んでやるゼ！",
		SPEARGUN_POISON = "フンッ！こいつァ、臆病モンの武器だゼ",
		SPEAR_OBSIDIAN = "突くのと燃やすの、両方だゼ！",
		SPEAR_POISON = "卑怯モンの武器だゼ",
		SPIDER =
		{
			DEAD = "うし！",
			GENERIC = "脚が多いな！よほど陸の上が好きと見える",
			SLEEPING = "ワシに踏みつぶされる夢でも見てんのか？",
		},
		SPIDERDEN = "盗賊の巣窟なら、喜んで入ェるけどよ…",
		SPIDEREGGSACK = "虫の世話なんか、誰がするかよ！",
		SPIDERGLAND = "もっとひでェモン、食ったことあるゼ",
		SPIDERHAT = "クモを頭にかぶれだァ？ケッ！",
		SPIDERHOLE = "何が住んでようと、知ったこっちゃねェな",
		SPIDERQUEEN = "ワシァ、誰にもひれ伏す気ァねェゼ！",
		SPIDER_DROPPER = "卑怯な野郎だゼ！",
		SPIDER_HIDER = "隠れて待ち伏せたァ、卑怯だゼ！",
		SPIDER_SPITTER = "ワシァ、もっと遠くへツバを飛ばせるゼ",
		SPIDER_WARRIOR =
		{
			DEAD = "ケッ！見かけ倒しだな！",
			GENERIC = "8本脚だァ？ケッ！かかってきやがれィ！",
			SLEEPING = "ハエを食う夢でも見てンのか？",
		},
		SPOILED_FISH = "悪魔の屁みてェにクセェな！",
		SPOILED_FOOD = "もっとひでェモン、食ったことあるゼ",
		STAFFLIGHT = "人が星を操れるわけがねェよ！",
		STAFF_TORNADO = "邪悪な気配がするゼ…",
		STALAGMITE = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_FULL = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_LOW = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_MED = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_TALL = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_TALL_FULL = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_TALL_LOW = "岩ってなァ、地上に転がってるモンだろ？",
		STALAGMITE_TALL_MED = "岩ってなァ、地上に転がってるモンだろ？",
		STATUEGLOMMER =
		{
			EMPTY = "壊れちまったゼ",
			GENERIC = "ずいぶん、見てくれの悪りィ像だな",
		},
		STATUEHARP = "頭はどこ行っちまったんだァ？",
		STATUEMAXWELL = "あの野郎のツラは、一生忘れねェ…！",
		STINGER = "ハチが、ケツを落としていきやがったゼ",
		STRAWHAT = "船長帽じゃねェが、かぶると涼しいゼ",
		STUFFEDEGGPLANT = "何が詰めてあンだ？",
		STUNGRAY = "屁こき魚め！あっち行きやがれ！",
		SUNKBOAT = "乗ってたヤツらは、ツイてなかったな…",
		SUNKEN_BOAT =
		{
			ABANDONED = "船員の姿は、見えねェな",
			GENERIC = "釣りざおがありャ、届きそうだゼ",
		},
		SUNKEN_BOAT_BURNT = "沈んだ揚げ句に燃えるたァ、ツイてねェな",
		SUNKEN_BOAT_TRINKET_1 = "有能な船長にャ、こんなモンは必要ねェ",
		SUNKEN_BOAT_TRINKET_2 = "チビ海賊用だな",
		SUNKEN_BOAT_TRINKET_3 = "ろうそくと水は、相性最悪だゼ？",
		SUNKEN_BOAT_TRINKET_4 = "こいつァ、バッタモンだゼ！",
		SUNKEN_BOAT_TRINKET_5 = "ワシにャ、片方だけで十分だゼ",
		SUPERTELESCOPE = "水平線の彼方まで、よォ～く見えるゼ！",
		BANANAPOP = "こいつでクギが打てるか、試してみようゼ！",
		BISQUE = "こいつァ、いくらでも飲み干せそうだゼ！",
		CEVICHE = "海の生きモンが、ごちそうに変身したゼ！",
		SEAFOODGUMBO = "ペロッと食ってやるゼ！",
		SURFNTURF = "ワシはシーフードだけで十分だゼ",
		SHARKFINSOUP = "今度はワシがテメェにかみつく番だゼ！",
		LOBSTERDINNER = "ワシの大好物だゼ！",
		LOBSTERBISQUE = "これで壊血病も怖くねェな！",
		JELLYOPOP = "ワシの得意料理だゼ！",
		SWEATERVEST = "海の男ァ、こんなモン着ねェよ",
		SWEET_POTATO = "甘いイモだな！ワシの好物だ！",
		SWEET_POTATO_COOKED = "アツアツ、ホクホクで、うめェぞ！",
		SWEET_POTATO_PLANTED = "うめェイモも、お宝も、土に埋まってんだゼ！",
		SWEET_POTATO_SEEDS = "畑仕事なんざ、ごめんだゼ",
		SWORDFISH = "その鼻の剣で戦うのか？上等だゼ！",
		TAFFY = "歯にくっつくゼ…",
		TALLBIRD = "その脚、ブッたぎってやりてェな…",
		TALLBIRDEGG = "鳥は、いつ出てくンだ？",
		TALLBIRDEGG_COOKED = "黄身は半熟にかぎるゼ！",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "鳥のケツで、温めねェとダメだな",
			GENERIC = "ヒナが出てくンのか？",
			HOT = "固ゆで卵は、好きじゃねェな",
			LONG = "ヒナが出てくるまで、まだまだかかるゼ",
			SHORT = "もうすぐヒナが出てくるゼ！",
		},
		TALLBIRDNEST =
		{
			GENERIC = "デケェ卵だな！",
			PICKED = "卵のカゴは、からっぽだゼ",
		},
		TEENBIRD =
		{
			GENERIC = "脚の長さは、まだそこそこだな",
			HUNGRY = "食いモン、探してこねェとなァ…",
			STARVING = "ワシは、食ってもうまくねェぞ！",
		},
		TELEBASE =
		{
			GEMS = "紫色の宝石が足りねェみてェだ",
			VALID = "準備が整ったゼ！",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "動き出したみてェだな！",
			GENERIC = "地球の果てへの入り口かもしれねェな！",
			LOCKED = "部品が足りねェみてェだ",
			PARTIAL = "まだ完成してねェぞ",
		},
		TELEPORTATO_BOX = "ワシァ、海賊だ！機械のこたァわからねェ！",
		TELEPORTATO_CRANK = "なんかを回すハンドルじゃねェのか？",
		TELEPORTATO_POTATO = "ずいぶん変わったよろいじゃねェか",
		TELEPORTATO_RING = "ケッ！宝石がついてねェじゃねェか！",
		TELEPORTATO_SW_BASE = "こいつァ…なんだ？",
		TELEPORTATO_SW_BOX = "中にすげェ秘密が入ってるに違ェねェ",
		TELEPORTATO_SW_CRANK = "なんかのハンドルかもしれねェな",
		TELEPORTATO_SW_POTATO = "かぶとみてェなイモ…？ナゾだゼ",
		TELEPORTATO_SW_RING = "こりゃ、どう見ても黄金じゃねェな",
		TELESCOPE = "“アイ”アイサー！",
		TELESTAFF = "速ェ船と追い風に勝るもンはねェよ",
		TENT =
		{
			BURNT = "だから陸で居眠りすんのは嫌れェなンだ…",
			GENERIC = "ウォーターベッドに勝るもンはねェよ",
		},
		TENTACLE = "こいつ…夢で見たことあるゼ…！",
		TENTACLESPIKE = "気色悪ィ怪物が、武器になったゼ！",
		TENTACLESPOTS = "イボイボだゼ…こんなモン、何に使うんだ？",
		TENTACLE_GARDEN = "こいつァ…スライムってヤツだな！",
		TENTACLE_PILLAR = "ヌルヌルだが、いいマストになりそうだゼ！",
		TENTACLE_PILLAR_ARM = "こいつァ…スライムだな！",
		THATCHPACK = "ヤシの葉も、立派な袋になるじゃねェか！",
		THULECITE = "こいつァ…お宝か？",
		THULECITE_PIECES = "お宝っぽいニオイがするゼ…",
		TIDALPOOL = "水面に、ワシの未来が見えるゼ…",
		TIDAL_PLANT = "潮が育てた草だゼ",
		TIGERSHARK = "シマシマの怪物め！かかってきやがれィ！",
		TOPHAT = "海賊も、たまにはダンディにキメてェんだ",
		TORCH = "これで、暗闇でもお宝見つけられるゼ！",
		TOUCAN = "てめェの名前…サムじゃねェよな…？",
		TRAILMIX = "海の旅用のおやつは、ねェのか？",
		TRANSISTOR = "こいつァ…なんだ？",
		TRAP = "ワシは真っ向勝負のほうが好きだゼ",
		TRAP_TEETH = "鋭い歯がついてやがる…うらやましいゼ",
		TRAP_TEETH_MAXWELL = "あんなもンに、ひっかかってたまるかよ",
		TRAWLNET = "海底のお宝、ごっそりいただくゼ",
		TRAWLNETDROPPED =
		{
			GENERIC = "積み荷を寄こしやがれィ！",
			SOON = "積み荷はいただくゼ…",
			SOONISH = "積み荷を寄こせィ！",
		},
		TREASURECHEST =
		{
			BURNT = "ワシのお宝があああぁッ！",
			GENERIC = "ヘヘ…コイツのために生きてるゼ…",
		},
		TREASURECHEST_TRAP = "宝箱に、“たばかられた”ゼ！",
		TREECLUMP = "そこをどきやがれィ！",
		TRIDENT = "まさか、ホントにあるとは思わなかったゼ…",
		TRINKET_1 = "溶けてくっついてやがるゼ",
		TRINKET_10 = "願いがかなったゼ！",
		TRINKET_11 = "こいつ、適当なことばっかり言いやがるゼ！",
		TRINKET_12 = "あァ…？なんだ、こいつァ？",
		TRINKET_13 = "ソーダ水ってヤツだな！",
		TRINKET_14 = "ワシァ、呪術には手ェ出さねェ主義だゼ",
		TRINKET_15 = "弾き方、サッパリわかんねェな",
		TRINKET_16 = "ヘンな板だゼ",
		TRINKET_17 = "ワシには必要ねェな",
		TRINKET_18 = "古美術品やらの価値は、よくわかんねェな",
		TRINKET_19 = "薬でボンヤリが治んのかァ？",
		TRINKET_2 = "ケッ…ホンモノじゃねェのかよ…",
		TRINKET_23 = "どっちみち、使い方がわからねェな！",
		TRINKET_3 = "これをほどけだァ？なんのためだよ？",
		TRINKET_4 = "赤帽の悪魔が現れたゼ！",
		TRINKET_5 = "「船」？これがかァ？",
		TRINKET_6 = "ロープ結ぼうとして、切れちまったのか…？",
		TRINKET_7 = "最新のゲーム機だゼ！",
		TRINKET_8 = "カチコチだゼ",
		TRINKET_9 = "そろってなくても、文句はねェよ",
		TROPICALFAN = "こいつであおげば、涼しくなるゼ",
		TROPICAL_FISH = "ワシの大好物だゼ！",
		TRUNKVEST_SUMMER = "鼻で作った服だゼ！",
		TRUNKVEST_WINTER = "鼻で作った服だゼ！",
		TRUNK_COOKED = "もっと気色悪ィ鼻、食ったことあるゼ？",
		TRUNK_SUMMER = "この鼻ン中に、お宝が入ってンのか？",
		TRUNK_WINTER = "この鼻ン中に、お宝が入ってンのか？",
		TUMBLEWEED = "草ってのは、じっとしてるモンだろーが",
		TUNACAN = "缶に魚が詰まってやがるゼ！",
		TURBINE_BLADES = "使い道がありそうだゼ？",
		TURF_SANDY = "ワシァ、陸モンじゃねェ",
		TURF_ASH = "ワシァ、陸モンじゃねェ",
		TURF_BADLANDS = "ワシァ、陸モンじゃねェ",
		TURF_BEACH = "ワシァ、陸モンじゃねェ",
		TURF_CARPETFLOOR = "ワシァ、陸モンじゃねェ",
		TURF_CAVE = "ワシァ、陸モンじゃねェ",
		TURF_CHECKERFLOOR = "ワシァ、陸モンじゃねェ",
		TURF_DECIDUOUS = "ワシァ、陸モンじゃねェ",
		TURF_DESERTDIRT = "ワシァ、陸モンじゃねェ",
		TURF_DIRT = "ワシァ、陸モンじゃねェ",
		TURF_FOREST = "ワシァ、陸モンじゃねェ",
		TURF_FUNGUS = "ワシァ、陸モンじゃねェ",
		TURF_FUNGUS_GREEN = "ワシァ、陸モンじゃねェ",
		TURF_GRASS = "ワシァ、陸モンじゃねェ",
		TURF_JUNGLE = "ワシァ、陸モンじゃねェ",
		TURF_MARSH = "ワシァ、陸モンじゃねェ",
		TURF_MEADOW = "ワシァ、陸モンじゃねェ",
		TURF_MUD = "ワシァ、陸モンじゃねェ",
		TURF_ROAD = "ワシァ、陸モンじゃねェ",
		TURF_ROCKY = "ワシァ、陸モンじゃねェ",
		TURF_SAVANNA = "ワシァ、陸モンじゃねェ",
		TURF_SINKHOLE = "ワシァ、陸モンじゃねェ",
		TURF_SNAKESKINFLOOR = "ワシァ、陸モンじゃねェ",
		TURF_SWAMP = "ワシァ、陸モンじゃねェ",
		TURF_UNDERROCK = "ワシァ、陸モンじゃねェ",
		TURF_VOLCANO = "悪魔の地面だゼ",
		TURF_WOODFLOOR = "義足で歩くと、ギシギシいうゼ",
		TURKEYDINNER = "こいつァ、うまそうな鶏だゼ！",
		TWIGS = "細っこすぎて、義足には向かねェな",
		TWISTER = "すげェ風だ！魔物のクシャミみてェだな！",
		TWISTER_SEAL = "頼むから、そんな目で見んなよ…",
		UMBRELLA = "ま、ぬれねェに越したこたァねェな",
		UNAGI = "こいつを食うのか？もう朝メシの時間かよ",
		UNIMPLEMENTED = "まだ作りかけみてェだな",
		VENOMGLAND = "ここで毒が作られンだな",
		VINE = "敵を絞め殺すのに使えそうだゼ",
		VOLCANO = "ワシが閉じ込められてた山だゼ",
		VOLCANOSTAFF = "火山の野郎ッ！ワシのいうことを聞けィ！",
		VOLCANO_ALTAR =
		{
			GENERIC = "火山にささげ物すりゃ、ご機嫌取れるゼ？",
			OPEN = "ささげ物、いつでも持ってこいとよ！",
		},
		VOLCANO_ALTAR_BROKEN = "これじゃ、火山様のご機嫌取れねェな！",
		VOLCANO_EXIT = "とっととズラかろうゼ…",
		VOLCANO_SHRUB = "すっかりコゲちまってるゼ",
		WAFFLES = "お袋がよく、出来合いのを買ってきたゼ…",
		WALLYINTRO_DEBRIS = "船は沈んだが、ワシだけは助かったゼ…",
		WALL_HAY =
		{
			BURNT = "ワラは燃えンに決まってんだろーが",
			GENERIC = "閉じ込められンのは、もうゴメンだゼ…",
		},
		WALL_HAY_ITEM = "野生の馬に体当たりされたら、終わりだゼ",
		WALL_LIMESTONE = "ケッ！壁なんか見たくもねェ！",
		WALL_LIMESTONE_ITEM = "オリん中は、もうゴメンだゼ…",
		WALL_RUINS = "ワシが生まれるより前にできた壁だゼ！",
		WALL_RUINS_ITEM = "お宝を守る、いにしえの壁だゼ",
		WALL_STONE = "海に落としたら沈むゼ",
		WALL_STONE_ITEM = "石の壁だ。陸でしか使えねェな",
		WALL_WOOD =
		{
			BURNT = "これじゃもう、壁とは呼べねェな",
			GENERIC = "陸を守りたきゃ、こいつを建てンだな",
		},
		WALL_WOOD_ITEM = "陸に建てるモンだ。船乗りにゃ必要ねェ",
		WALRUS = "何をそんなにイラついてやがンだ？",
		WALRUSHAT = "ワシの趣味じゃねェな",
		WALRUS_CAMP =
		{
			EMPTY = "陸モンの家だな…今は空き屋だゼ",
			GENERIC = "家に住むなんてのァ、陸モンのすることだ",
		},
		WALRUS_TUSK = "新しい義足が作れそうだゼ",
		WARG = "陸じゃ威張ってても、海じゃ魚のエサだゼ",
		WASPHIVE = "あいつにゃ、近づかねェほうがいいゼ",
		WATERMELON = "赤くてみずみずしい…ワシの心みてェだ！",
		WATERMELONHAT = "スイカは好きだが…こいつァねェゼ",
		WATERMELONICLE = "ワシの大好物を凍らせたゼ！",
		WATERMELON_COOKED = "思ったよりうめェじゃねェか",
		WATERMELON_SEEDS = "なんで水ン中じゃ育たねェんだ？",
		WEBBERSKULL = "こいつァまた、ずいぶん変わったドクロだ！",
		WETGOOP = "ワシァ、食事当番、外されてたからなァ…",
		WHALE_BLUE = "悪魔め…ワシを海の底へ引き込みに来たな？",
		WHALE_BUBBLES = "海の底に、悪魔が潜んでやがるゼ！",
		WHALE_CARCASS_BLUE = "クセェな！とっとと沈みやがれ！",
		WHALE_CARCASS_WHITE = "腐臭もクジラ級だゼ！",
		WHALE_WHITE = "てめェと戦って死ねるなら本望だゼ！",
		WILBUR_CROWN = "ずいぶんちっせェ冠だゼ！",
		WILBUR_UNLOCK = "こじゃれたサルだゼ！",
		WILDBORE = "アイツにャ、近づかねェほうがいいゼ",
		WILDBOREHOUSE = "中で楽しく騒いでやがるゼ…",
		WIND_CONCH = "嵐を呼ぶゼ！",
		WINTERHAT = "これで、頭は寒くねェな",
		WINTEROMETER =
		{
			BURNT = "これじゃ、ただのゴミだゼ",
			GENERIC = "どんだけ寒みィか、測る装置だゼ",
		},
		WORM =
		{
			DIRT = "汚い土。",
			PLANT = "うまそうに熟してるゼ",
			WORM = "でけェミミズだゼ！",
		},
		WORMHOLE =
		{
			GENERIC = "あれに入るやつァ、どうかしてるゼ",
			OPEN = "ありャァ、どこへ、つながってんだ？",
		},
		WORMHOLE_LIMITED = "ありャァ、今にもくたばりそうだな",
		WORMLIGHT = "食うと腹ン中が明るくなるゼ",
		YELLOWAMULET = "まるで歩く灯台だゼ！",
		YELLOWGEM = "ワシの歯とおんなじ色だゼ！",
		YELLOWSTAFF = "人が星を操れるわけがねェよ！",
		WOODLEGSBOAT = "ワシのカワイイ「シー・レッグス」号だゼ！",
		WOODLEGSHAT = "ワシの幸運の帽子だゼ！",

		ARMORCACTUS = "どっからでも、かかってきやがれィ！",
		BIGFISHINGROD = "こんなモン、でけェうちに入らねェよ！",
		--BOOK_METEOR = "Devil magic thet summons demons from th'sky!",
		BRAINJELLYHAT = "ワシの頭にぴったりだゼ！",
		COCONUT_HALVED = "果肉も、うまそうだゼ！",
		COFFEEBOT = "これでコーヒー煎れられるゼ！",
		CRATE = "木箱だゼ",
		DEPLETED_BAMBOOTREE = "ぜーんぶ切っちまったゼ",
		DEPLETED_BUSH_VINE = "昼寝中みてェだな",
		DEPLETED_GRASS_WATER = "しばらく生えてこなそうだゼ？",
		DOYDOYEGG_COOKED = "“鳥の素”を焼いたゼ！",
		DRAGOONHEART = "雄々しい怪物の心臓だゼ",
		DRAGOONSPIT = "そこらじゅうにツバ吐くたァ、上等だゼ！",
		DUG_BUSH_VINE = "いっしょに連れてってやるゼ…",
		FRESHFRUITCREPES = "やっとまともなメシにありつけたゼ",
		FRUITMEDLEY = "こいつァ、うめェ！",
		GEARS = "ワシの頭ン中にも、こんなのがあンのか？",
		GUANO = "怪物のケツから出てきたモンだ！",
		HOUNDFIRE = "メラメラ燃えてやがるゼ",
		INVENTORYGRAVE = "誰か、ワシの島に入りやがったな？",
		INVENTORYMOUND = "誰か、ワシの島に入りやがったな？",
		KRAKEN = "海の王者が現れたゼ！",
		KRAKENCHEST = "これぞ海賊暮らしの醍醐味だゼ！",
		KRAKEN_TENTACLE = "かかってきやがれッ！",
		MAGMAROCK_FULL = "お宝のニオイがプンプンするゼ…！",
		MAGMAROCK_GOLD_FULL = "お宝のニオイがプンプンするゼ…！",
		MONKEYBALL = "ちとブキミだゼ…",
		MONSTERTARTARE = "こりャ…食いモンか？",
		MUSSELBOUILLABAISE = "高級料理だゼ",
		MYSTERYMEAT = "今夜はごちそうだゼ！",
		OXHAT = "ウシのツノで作った帽子だゼ",
		OX_FLUTE = "こいつを吹くと、雨が降るゼ",
		OX_HORN = "毛むくじゃらの獣のツノだゼ",
		PARROT_PIRATE = "おめェ…！ポリーじゃねェか！",
		PEACOCK = "ずいぶんと派手な鳥だゼ！",
		PEG_LEG = "予備にとっとこうゼ",
		PIRATEGHOST = "海賊暮らしは、死んでも続くんだゼ",
		SANDBAGSMALL_ITEM = "こいつがありャ、洪水になっても安心だゼ",
		SHADOWSKITTISH_WATER = "魔物が出やがったゼッ！",
		SHIPWRECKED_ENTRANCE = "さあ、出港だゼ！",
		SHIPWRECKED_EXIT = "そろそろ陸に上がるか…",
		SNAKESKINSAIL = "上等な帆だゼ",
		SNAKE_FIRE = "ありャァ、悪魔の手先だゼ",
		SPEAR_LAUNCHER = "ヤリを遠くへスッ飛ばす道具だゼ",
		SWEETPOTATOSOUFFLE = "クランペットにしちゃ、やけにフワフワだゼ",
		SWIMMINGHORROR = "海の底に帰ェりやがれ！",
		TIGEREYE = "昔の仲間、“ワイルドアイ”・ウェストンを思い出すゼ",
		TRINKET_20 = "海ィ渡るときの必需品だゼ！",
		TRINKET_21 = "こいつァ、まがいモンだゼ！",
		TRINKET_22 = "ワインは、どこいっちまったンだァ？",
		TURF_FUNGUS_RED = "ワシァ、陸モンじゃねェ",
		TURF_MAGMAFIELD = "ワシァ、陸モンじゃねェ",
		TURF_TIDALMARSH = "ワシァ、陸モンじゃねェ",
		VOLCANO_ALTAR_TOWER = "こいつァきっと、悪魔が造ったモンだゼ…",
		WATERYGRAVE = "海の男の、理想の最期だゼ",
		WHALE_TRACK = "クジラだぞォー！",
		WILDBOREHEAD = "ジロジロ見んじゃねェ！",
		WOODLEGSSAIL = "ワシのお気に入りの帆だゼ！",
		WOODLEGS_CAGE = "見るのもイヤだゼ…",
		WOODLEGS_KEY1 = "なんの役にも立たねェゼ",
		WOODLEGS_KEY2 = "なんの役にも立たねェゼ",
		WOODLEGS_KEY3 = "なんの役にも立たねェゼ",
		WRECK = "おつかれさん…ゆっくり休めよ",
		CALIFORNIAROLL = "こじゃれたシーフードスナックだゼ",

	},
	DESCRIBE_GENERIC = "こいつァ…なんだ？",
	DESCRIBE_SMOLDERING = "燃えかけてるゼ",
	DESCRIBE_TOODARK = "暗くて、なンも見えねェぞ！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "殻ごと食ってやるゼ！",
	},
}