return
{

	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "¡Está como nuevo!",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "¡Patapalo no es idiota!",
			GENERIC = "No es día de afeitarse.",
			NOBITS = "No tiene nada que afeitar.",
		},
		STORE =
		{
			GENERIC = "Está lleno.",
			NOTALLOWED = "Esto no es de aquí.",
		},
		RUMMAGE =
		{	
			GENERIC = "¡No me hace falta! ¡Arrr!",	
		},
        COOK =
        {
            GENERIC = "¡Esta no es hora de cocinar!",
            TOOFAR = "¡Está a leguas de distancia!",
        },
        GIVE =
        {
            DEAD = "Está muerto.",
            SLEEPING = "Está durmiendo.",
            BUSY = "¡Ignora al viejo Patapalo!",
        },
        WRITE =
        {
            GENERIC = "¡Lo único que sé escribir es una \"X\"!",
        },
        CHANGEIN =
        {
            GENERIC = "¡Patapalo no cambiará hoy!",
            BURNING = "¡Está escupiendo fuego!",
        },
		TEACH =
        {
            KNOWN = "Arrr.",
            CANTLEARN = "¡Arrrrrr!",
        },
	},
	ACTIONFAIL_GENERIC = "No puedo hacer eso.",
	ANNOUNCE_MAGIC_FAIL = "¡Eso no es para esta tierra!",
	ANNOUNCE_ACCOMPLISHMENT = "¡Gloria para el viejo Patapalo!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "¡Si mis camaradas de a bordo pudieran verme ahora!",
	ANNOUNCE_ADVENTUREFAIL = "Esto no ha salido según lo planeado. Tal vez vuelva a intentarlo.",
	ANNOUNCE_BEES = "¡Atrás, pequeños diablos con alas!",
	ANNOUNCE_BOAT_DAMAGED = "¡Se está empapando!",
	ANNOUNCE_BOAT_SINKING = "¡Se está hundiendoooo!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "¿Será este el día en que el mar me reclame?",
	ANNOUNCE_BOOMERANG = "¡Arma infernal!",
	ANNOUNCE_BURNT = "¡Ay!",
	ANNOUNCE_CANFIX = "\nPuedo arreglarlo, creo.",
	ANNOUNCE_CHARLIE = "¡Pero qué demonios era eso!",
	ANNOUNCE_CHARLIE_ATTACK = "¡Me han atacado!",
	ANNOUNCE_COLD = "¡Arrrr, brrrrr!",
	ANNOUNCE_CRAB_ESCAPE = "¿Dónde se ha metido ese pequeño diablo?",
	ANNOUNCE_CRAFTING_FAIL = "Me faltan las partes necesarias, arrr.",
	ANNOUNCE_DAMP = "¡Mis pantalones están empapados!",
	ANNOUNCE_DEERCLOPS = "¡Algún diablo grande está sobre mí!",
	ANNOUNCE_DUSK = "Se está haciendo tarde. El horizonte se está oscureciendo.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Arrr, qué bueno.",
		INVALID = "No voy a comerme eso.",
		PAINFUL = "No me siento muy bien.",
		SPOILED = "Eso no le gustará a mi estómago.",
		STALE = "Esto ya ha caducado.",
	},
	ANNOUNCE_ENTER_DARK = "¡Está oscuro!",
	ANNOUNCE_ENTER_LIGHT = "¡Puedo ver otra vez!",
	ANNOUNCE_FREEDOM = "¡Soy libre!",
	ANNOUNCE_HIGHRESEARCH = "¡El viejo Patapalo le ha estado dando hoy al coco!",
	ANNOUNCE_HOT = "Me hace falta un... cubito o dos...",
	ANNOUNCE_HOUNDS = "¿Qué indicará ese ruido?",
	ANNOUNCE_HUNGRY = "Tengo hambre...",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Las huellas estás recientes. Ese diablo debe de estar cerca.",
	ANNOUNCE_HUNT_LOST_TRAIL = "He perdido el rastro.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "El rastro se ha borrado.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "¿Necesitas más estiércol, planta?",
	ANNOUNCE_INV_FULL = "¡No puedo llevar más cosas!",
	ANNOUNCE_KNOCKEDOUT = "Arrr, mi cabeza...",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "¡No podéis alcanzar a Patapalo, rayos del cielo!",
	ANNOUNCE_LOWRESEARCH = "Este viejo trasto ya no aprenderá más trucos, arrr.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Hacia las sombras y las tinieblas...",
	ANNOUNCE_MAPWRAP_RETURN = "¡Hasta el fin del mundo y regresar!",
	ANNOUNCE_MAPWRAP_WARN = "Se aproxima un velo de niebla...",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"El mensaje se ha borrado...",
	},
	ANNOUNCE_MORETREASURE = "¡Tesoros! ¡¡¡Más y más tesoros!!!",
	ANNOUNCE_MOSQUITOS = "¡Atrás, diablos chupasangre!",
	ANNOUNCE_NODANGERSIESTA = "Esta no es hora de echarse la siesta.",
	ANNOUNCE_NODANGERSLEEP = "Esta no es la hora de dormir.",
	ANNOUNCE_NODAYSLEEP = "Hay demasiada claridad para cerrar los ojos.",
	ANNOUNCE_NODAYSLEEP_CAVE = "No estoy cansado.",
	ANNOUNCE_NOHUNGERSIESTA = "Tengo mucha hambre para una siesta.",
	ANNOUNCE_NOHUNGERSLEEP = "Mi barriga está haciendo mucho ruido para dormir.",
	ANNOUNCE_NONIGHTSIESTA = "La noche es para dormir, no para echarse siestas.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Este no es el sitio para una siesta.",
	ANNOUNCE_NOSLEEPONFIRE = "No me gusta la idea de una cama ardiendo.",
	ANNOUNCE_NO_TRAP = "¡No hay problema!",
	ANNOUNCE_OTHER_WORLD_PLANT = "No creo que esta planta sea de aquí.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "El mapa no coincide con esta tierra.",
	ANNOUNCE_PECKED = "¡Guárdate el pico para ti!",
	ANNOUNCE_QUAKE = "La tierra está eruptando.",
	ANNOUNCE_RESEARCH = "El timón está girando.",
	ANNOUNCE_SHARX = "¡Arrr, mis viejos enemigos quieren darme un mordisco!",
	ANNOUNCE_SHELTER = "Quédate a mi lado, árbol.",
	ANNOUNCE_SOAKED = "¡Estoy calado hasta los huesos!",
	ANNOUNCE_THORNS = "¡Diablo con cuernos!",
	ANNOUNCE_TOOL_SLIP = "¡Se me ha escurrido de las manos!",
	ANNOUNCE_TORCH_OUT = "¡Se ha apagado la luz!",
	ANNOUNCE_TRAP_WENT_OFF = "¡Maldición!",
	ANNOUNCE_TRAWL_FULL = "¡Mi red está llena!",
	ANNOUNCE_TREASURE = "¡El mapa señala el lugar del tesoro!",
	ANNOUNCE_UNIMPLEMENTED = "Esto no está listo.",
	ANNOUNCE_VOLCANO_ERUPT = "¡Los diablos de fuego están eruptando!",
	ANNOUNCE_WAVE_BOOST = "¡Hay una veta de plata en el azul ahora!",
	ANNOUNCE_WET = "Mi blusa pirata se ha mojado.",
	ANNOUNCE_WETTER = "Me gusta que el agua esté debajo del barco.",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Un gran diablo anda cerca.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "He perdido el rastro de ese diablo de mar...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Como encontrar una aguja húmeda en un pajar húmedo.",
	ANNOUNCE_WORMHOLE = "Debo de estar volviéndome loco.",
	ANNOUNCE_TREASURE_DISCOVER = "Mi sentido pirata me está haciendo cosquillas.",
	BATTLECRY =
	{
		GENERIC = "¡Te has metido con el pirata equivocado!",
		PIG = "¡Habrá jamón en el menú de esta noche!",
		PREY = "¡Te presento a tu muerte!",
		SPIDER = "¡Voy a pisotearte con mis patas de palo hasta la muerte!",
		SPIDER_WARRIOR = "¡Voy a pisotearte con mis patas de palo hasta la muerte!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "¿Has probado ya lo que es un pirata?",
		PIG = "Ya me ensuciarás otro día.",
		PREY = "Es demasiado rápida para mi pata de palo.",
		SPIDER = "Inténtalo otra vez, diablo con mil patas.",
		SPIDER_WARRIOR = "Inténtalo otra vez, diablo con mil patas.",
	},
	DESCRIBE =
	{
		--ABIGAIL = "A lady spectre!",
		ACCOMPLISHMENT_SHRINE = "¡Conoce la gloria del pirata Patapalo, mundo!",
		ACORN =
		{
			GENERIC = "Suena cuando la agito.",
			PLANTED = "Esto será un árbol en el futuro.",
		},
		ACORN_COOKED = "No está mal para una nuez de tierra.",
		ADVENTURE_PORTAL = "¿Qué nueva trampa es esta?",
		AERODYNAMICHAT = "¡Tardo la mitad del tiempo!",
		AMULET = "Un poco de seguridad alrededor del cuello.",
		ANCIENT_ALTAR = "Una estatua de los tiempos pasados.",
		ANCIENT_ALTAR_BROKEN = "Está roto.",
		ANCIENT_STATUE = "No me da buenas vibraciones.",
		ANIMAL_TRACK = "La bestia ha dejado un rastro hasta su piel.",
		ANTIVENOM = "Será el mar quien me reclame, no cualquier insecto.",
		ARMORDRAGONFLY = "¡Quemará a mis enemigos al tocarla!",
		ARMORGRASS = "Solo un marinero de agua dulce pensaría en hacer una armadura con hierba.",
		ARMORLIMESTONE = "Se hundiría como una piedra en el mar.",
		ARMORMARBLE = "Se hundiría como una piedra en el mar.",
		ARMOROBSIDIAN = "Es pesada y caliente.",
		ARMORRUINS = "Es como si llevara un tesoro.",
		ARMORSEASHELL = "Mis camaradas de a bordo se reirían de mí...",
		ARMORSLURPER = "¿Cuánto más necesito protegerme?",
		ARMORSNURTLESHELL = "No me parece bien pelear con una tortuga.",
		ARMORWOOD = "Al menos la madera flota.",
		ARMOR_LIFEJACKET = "¡Para! ¡Esto es solo para blandengues!",
		ARMOR_SANITY = "Uno se siente bien al llevarla.",
		ARMOR_SNAKESKIN = "Cuero para protegerse de la lluvia.",
		ARMOR_WINDBREAKER = "¡El viejo Patapalo es un experto cazador!",
		ARMOUREDBOAT = "Es muy resistente.",
		ASH =
		{
			GENERIC = "El fuego ha reclamado su premio.",
			REMAINS_EYE_BONE = "Por suerte he conservado los ojos en mis viajes.",
			REMAINS_GLOMMERFLOWER = "Las flores no se han hecho para viajar.",
			REMAINS_THINGIE = "Supongo que no eran cenizas, para empezar.",
		},
		AXE = "¡Soy un hacha con el hacha!",
		BABYBEEFALO = "Eres mono para ser una carne tan peluda.",
		BABYOX = "No eres un marinero de agua dulce, ¿verdad? ¡Qué va!",
		BACKPACK = "Haré la mochila ahora.",
		BACONEGGS = "¡La comida más importante del día!",
		BALLPHIN = "Esos diablos de mar tienen una bola.",
		BAMBOO = "Eres demasiado grande para ser un mondadientes. Si tuviera dientes...",
		BAMBOOTREE =
		{
			BURNT = "Es el fin de eso.",
			CHOPPED = "Ya no hay más bambú de momento.",
			GENERIC = "Madera que brota.",
		},
		BANDAGE = "Para malandrines blandengues.",
		BASALT = "Es fuerte.",
		BAT = "¡Atrás, diablo volador con cara de rata!",
		BATBAT = "Echaría a volar esto contra mis enemigos.",
		BATWING = "Con un poco de mayonesa...",
		BATWING_COOKED = "Sabe a pajarraco.",
		BEARDHAIR = "Bigotes de la barbilla.",
		BEARGER = "¡Atrás, molesto diablo!",
		BEARGERVEST = "Qué calentito.",
		BEARGER_FUR = "Este olor me está molestando.",
		BEDROLL_FURRY = "Dulces y peludos sueños.",
		BEDROLL_STRAW = "No parece que sirva para dormir seco.",
		BEE =
		{
			GENERIC = "Un diablo que hace miel.",
			HELD = "¡Suelta tu dulce tesoro!",
		},
		BEEBOX =
		{
			BURNT = "Huelo a miel quemada...",
			FULLHONEY = "¡Hay oro en esta caja!",
			GENERIC = "Son abejas.",
			NOHONEY = "No queda ningún tesoro de oro.",
			SOMEHONEY = "Queda un poco de oro.",
		},
		BEEFALO =
		{
			FOLLOWER = "Sabes quién es tu maestro.",
			GENERIC = "¡Ahí está el beefalo!",
			NAKED = "Deberías avergonzarte de ti mismo.",
			SLEEPING = "Sus ronquidos podrían despertar a los muertos.",
		},
		BEEFALOHAT = "Me mantiene las orejas calientes.",
		BEEFALOWOOL = "Lleva almizcle.",
		BEEHAT = "¡Patapalo no es ningún granjero de miel!",
		BEEHIVE = "Una guarida de fabricantes de miel.",
		BEEMINE = "Como la pises te dolerá.",
		BEEMINE_MAXWELL = "Como la pises te dolerá.",
		BELL = "Dobla y redobla.",
		BELL_BLUEPRINT = "No puedo hacer cara o cruz con esto.",
		BERMUDATRIANGLE = "Adónde va uno es un misterio.",
		BERRIES = "Me manchan la blusa.",
		BERRIES_COOKED = "Me vendría bien una migaja de pan para untarlo.",
		BERRYBUSH =
		{
			BARREN = "Necesita un montón de estiércol.",
			GENERIC = "Maduro para la recogida.",
			PICKED = "¿Crecerán bayas de nuevo?",
			WITHERED = "El arbusto no soporta este calor.",
		},
		BIGFOOT = "¡Cuidado, diablo de pies grandes!",
		BIOLUMINESCENCE = "Me iluminan la vida.",
		BIRCHNUTDRAKE = "Eres duro de pelar, ¿eh?",
		BIRDCAGE =
		{
			GENERIC = "Ningún loro mío podría soportar estar enjaulado.",
			OCCUPIED = "¿Te gusta tu celda, compañero?",
			SLEEPING = "Ahhh, fíjate. El pajarraco está durmiendo.",
			HUNGRY = "¿Tienes ganas de picar un poco?",
			STARVING = "¡Patapalo también tiene hambre, sabes!",
			DEAD = "Tu alma se ha ido a las profundidades.",
			SKELETON = "Los huesos de Davy Jones.",
		},
		BIRDTRAP = "Una vez que entras volando dentro, no sales.",
		BIRD_EGG = "El huevo de un pajarraco.",
		BIRD_EGG_COOKED = "Ojalá tuviera una migaja de pan.",
		BISHOP = "Necesitas un chorro de aceite, tus extremidades están chirriando.",
		BISHOP_NIGHTMARE = "¡Atrás, pequeño diablo!",
		BLOWDART_FIRE = "Escupiré fuego.",
		BLOWDART_FLUP = "Te veo bien.",
		BLOWDART_PIPE = "Un arma envenenada.",
		BLOWDART_POISON = "Un arma envenenada.",
		BLOWDART_SLEEP = "Susúrrales para que se duerman.",
		BLUBBER = "A Patapalo nunca le pillarás lloriqueando.",
		BLUBBERSUIT = "Tienes que estar de broma.",
		BLUEAMULET = "Qué fresquito.",
		BLUEGEM = "¡Su brillo es azul verdadero!",
		BLUEPRINT = "No soy un hombre instruido.",
		BLUE_CAP = "Sé lo suficiente como para no meterme esto en la boca.",
		BLUE_CAP_COOKED = "Huele comestible...",
		BLUE_MUSHROOM =
		{
			GENERIC = "Tengo espacio para champiñones en mi tripa.",
			INGROUND = "¿Solo sales de noche?",
			PICKED = "¿Volverá este champiñón a crecer?",
		},
		BOARDS = "Buenos y rectos.",
		BOAT = "Es resistente, si fuese un poco más pequeño lo usaría.",
		BOATCANNON = "¡Listo para disparar bolas de 6 libras!",
		BOATREPAIRKIT = "Nunca zarpes sin él.",
		BOAT_LANTERN = "Para navegar por la noche.",
		BOAT_TORCH = "Para que haya una antorcha en mi barco, no para quemarlo.",
		BONESHARD = "Trozos de hueso.",
		BONESTEW = "Bueno para el escorbuto.",
		BOOMERANG = "Prefiero algo que no me golpee la nuca.",
		BOTTLELANTERN = "Es un uso posible para una botella.",
		BUGNET = "Impide que los bichos me entren en los dientes que no tengo.",
		BUNNYMAN = "Salta, malandrín con orejas peludas.",
		BUOY = "Boya navegar un poco.",
		BURIEDTREASURE = "¡Mi cosa favorita enterrada!",
		BUSHHAT = "Para mezclarme con los marineros de agua dulce.",
		BUSH_VINE =
		{
			BURNT = "Solo una forma de desatar un nudo.",
			CHOPPED = "Ahora ya estás recta.",
			GENERIC = "Pareces como un montón de aparejos enredados.",
		},
		BUTTER = "¡Mira lo que ha salido!",
		BUTTERFLY =
		{
			GENERIC = "Tan bonita como un atardecer en el agua.",
			HELD = "Tan bonita en mi bolsillo.",
		},
		BUTTERFLYMUFFIN = "La fibra te da alas.",
		BUTTERFLYWINGS = "Me he quedado con la parte más bonita.",
		BUZZARD = "¡Diablo carroñero!",
		CACTUS =
		{
			GENERIC = "Tienes un gusto afilado, ¿eh?",
			PICKED = "Estás recién pinchada. Digo cortada.",
		},
		CACTUS_FLOWER = "Igual me saca un ojo si la huelo.",
		CACTUS_MEAT = "Seca y con pinchos, pero sigue siendo carne.",
		CACTUS_MEAT_COOKED = "No está mal cuando no se te queda pegada.",
		CAMPFIRE =
		{
			EMBERS = "Hay que alimentar ese fuego.",
			GENERIC = "¿Alguno conoce una buena canción de marineros?",
			HIGH = "Está en llamas.",
			LOW = "El fuego se está apagando.",
			NORMAL = "Agradable y calentito.",
			OUT = "Se acabó.",
		},
		CANE = "Yo llevo un bastón incorporado.",
		CAPTAINHAT = "¡Ponte elegante, grumete! ¡El capitán está en cubierta!",
		CARGOBOAT = "Para el acaparador marino.",
		CARROT = "Para mi visión nocturna en el ojo.",
		CARROT_COOKED = "Buena y suave para mis pocos dientes.",
		CARROT_PLANTED = "Una especie de tesoro enterrado.",
		CARROT_SEEDS = "Marineros de agua dulce.",
		CATCOON = "Parece que te gusta mucho la basura.",
		CATCOONDEN =
		{
			EMPTY = "¿Meto la mano dentro y me aseguro?",
			GENERIC = "¿Quién vive aquí? Estoy perplejo.",
		},
		CATCOONHAT = "Espero que ninguno de mis compañeros me pille de esta guisa.",
		CAVE_BANANA = "Hace un frío que pela aquí abajo.",
		CAVE_BANANA_COOKED = "No está mal.",
		CAVE_BANANA_TREE = "Ahora el viejo Patapalo lo ha visto todo.",
		CAVE_ENTRANCE =
		{
			GENERIC = "Lo mío no es trepar hasta agujeros como un pajarraco.",
			OPEN = "Apuesto a que no hay mar allá abajo.",
		},
		CAVE_EXIT = "De vuelta al cielo abierto.",
		CAVE_FERN = "¿Cómo has crecido aquí sin luz?",
		CHARCOAL = "Quemado hasta convertirse en carbón.",
		CHESSJUNK1 = "Alguien es un perdedor resentido.",
		CHESSJUNK2 = "Alguien es un perdedor resentido.",
		CHESSJUNK3 = "Alguien es un perdedor resentido.",
		CHESTER = "¿Pero qué demonios eres?",
		CHESTER_EYEBONE =
		{
			GENERIC = "Tienes un ojo bonito.",
			WAITING = "Está echando una cabezada.",
		},
		CHIMINEA = "Mantiene el viento alejado de un buen fuego.",
		CLOTHSAIL = "Una vela bonita.",
		COCONADE =
		{
			BURNING = "¡Sorpresa! ¡Una fruta que explota!",
			GENERIC = "¡Esta fruta pega fuerte!",
		},
		COCONUT = 
		{
		    GENERIC = "Sí, mi fruta de árbol preferida.",
		    PLANTED = "¡Ya no es un fruto!",
		},
		COCONUT_COOKED = "Esto estará aún mejor cocinado al fuego.",
		COFFEE = "Arrr, ahí hay un tesoro de verdad.",
		COFFEEBEANS = "Solo añade agua.",
		COFFEEBEANS_COOKED = "¿No hay agua caliente?",
		COFFEEBUSH =
		{
			BARREN = "Necesita un montón de estiércol.",
			GENERIC = "¡Una planta como mi amargo y negro corazón!",
			PICKED = "Espero que vuelvan a crecer pronto.",
			WITHERED = "Necesita una taza de café para crecer.",
		},
		COLDFIRE =
		{
			EMBERS = "El fuego casi se ha apagado.",
			GENERIC = "Las llamas devorarán la oscuridad.",
			HIGH = "Me alegro de que este fuego esté en una hoguera y no en mi barco.",
			LOW = "El fuego se está apagando.",
			NORMAL = "Me sirve para enfriarme.",
			OUT = "El fuego se ha apagado.",
		},
		COLDFIREPIT =
		{
			EMBERS = "El fuego casi se ha apagado.",
			GENERIC = "Las llamas devorarán la oscuridad.",
			HIGH = "Me alegro de que este fuego esté en una hoguera y no en mi barco.",
			LOW = "El fuego se está apagando.",
			NORMAL = "Me sirve para enfriarme.",
			OUT = "El fuego se ha apagado.",
		},

		COMPASS =
		{
			E = "¡Al este!",
			GENERIC = "Esto es una brújula.",
			N = "¡Al norte!",
			NE = "¡Al noreste!",
			NW = "¡Al noroeste!",
			S = "¡Al sur!",
			SE = "¡Al sureste!",
			SW = "¡Al suroeste!",
			W = "¡Al oeste!",
		},
		COOKEDMANDRAKE = "Patapalo lo ha cocinado bien.",
		COOKEDMEAT = "Una buena comida.",
		COOKEDMONSTERMEAT = "Estará malo.",
		COOKEDSMALLMEAT = "Es solo un bocado.",
		COOKPOT =
		{
			BURNT = "La olla se ha quemado.",
			COOKING_LONG = "Es una receta lenta.",
			COOKING_SHORT = "Pronto estará listo.",
			DONE = "Está listo para comerlo.",
			EMPTY = "La olla está vacía.",
		},
		COONTAIL = "¡Al gato se le ha caído la cola!",
		CORAL = "¡Esto desgarraría un barco en un momento!",
		CORALREEF = "Será mejor que navegues bien, Patapalo.",
		CORAL_BRAIN = "Uno no pensaría que eso es inteligente.",
		CORAL_BRAIN_ROCK = "Los cerebros del océano.",
		CORN = "¡Maíz fresco! Es mi día de la suerte.",
		CORN_COOKED = "Maíz asado, mi preferido.",
		CORN_SEEDS = "Pronto serás maíz.",
		CRAB =
		{
			GENERIC = "¡Qué comida más sabrosa!",
			HIDDEN = "Sé que ese congrejo anda cerca.",
		},
		CRABHOLE = "Tienes una casa bonita, congrejo.",
		CROW =
		{
			GENERIC = "¡Ese es un loro aceitoso!",
			HELD = "Eres difícil de limpiar, loro.",
		},
		CUTGRASS = "Ya ayudarás más tarde a Patapalo.",
		CUTLASS = "Sí, un verdadero cuchillo de pirata.",
		CUTLICHEN = "¡Hierba marina!",
		CUTREEDS = "Pero Patapalo no puede leer.",
		CUTSTONE = "Es una piedra bien tallada.",
		DEADLYFEAST = "Es una comida asquerosa.",
		DEAD_SWORDFISH = "Seguro que luchas muy bien.",
		DECIDUOUSTREE =
		{
			BURNING = "No estarás mucho tiempo en pie.",
			BURNT = "Ese árbol ya no sirve de nada.",
			CHOPPED = "Serás un buen navío.",
			GENERIC = "Tu pelo es bonito.",
			POISON = "No pareces nada bueno.",
		},
		DEERCLOPS = "¿Es una broma, arrr?",
		DEERCLOPS_EYEBALL = "Es un globo ocular gigante.",
		DEPLETED_GRASS =
		{
			GENERIC = "No servirás de mucho a Patapalo.",
		},
		DEVTOOL = "Sí, es un objeto verdaderamente maravilloso.",
		DEVTOOL_NODEV = "Sí, es un objeto verdaderamente maravilloso.",
		DIRTPILE = "Eso parece un montón de tesoros.",
		DIVININGROD =
		{
			COLD = "No hay ni una pizca de tesoro cerca.",
			GENERIC = "Ayudará al viejo Patapalo a olfatear tesoros.",
			HOT = "¿¡Habrá tesoros!?",
			WARM = "¡Lleva a Patapalo a tus tesoros!",
			WARMER = "¡Patapalo tiene que estar cerca!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Arrr, esto es un misterio.",
			READY = "Un ojo de cerradura.",
			UNLOCKED = "¡Allá va!",
		},
		DIVININGRODSTART = "Esta vara es un tesoro.",
		DOUBLE_UMBRELLAHAT = "Esto es obra de un chiflado.",
		DOYDOY = "Qué pájaro tan estúpido.",
		DOYDOYBABY = "Es un diminuto pájaro tonto.",
		DOYDOYEGG = "¡Comida gratis!",
		DOYDOYEGG_CRACKED = "Esto es inútil.",
		DOYDOYFEATHER = "Es una vela de ave.",
		DOYDOYNEST = "Es la casa de un pájaro.",
		DRAGONFLY = "¡Lleva a Patapalo a tus tesoros!",
		DRAGONFLYCHEST = "Eso mantiene mis tesoros sanos y salvos.",
		DRAGONFRUIT = "¡Está llena de poder!",
		DRAGONFRUIT_COOKED = "Serás una deliciosa comida.",
		DRAGONFRUIT_SEEDS = "Necesitas un hogar en la tierra.",
		DRAGONPIE = "Este tesoro es un pastel.",
		DRAGON_SCALES = "Es un tesoro maravilloso.",
		DRAGOON = "¡Mantén tus llamas lejos de Patapalo, marinero de agua dulce!",
		DRAGOONDEN = "¿Crees que estará lleno de tesoros?",
		DRAGOONEGG = "Noto que se acerca una tormenta.",
		DRUMSTICK = "¡Un festín de carne para Patapalo!",
		DRUMSTICK_COOKED = "Carne caliente para la cena.",
		DUBLOON = "¡Mis tesoros!",
		DUG_BAMBOOTREE = "Le hará falta algo de tierra para ser útil.",
		DUG_BERRYBUSH = "Le hará falta algo de tierra para ser útil.",
		DUG_COFFEEBUSH = "Le hará falta algo de tierra para ser útil.",
		DUG_ELEPHANTCACTUS = "Le hará falta algo de tierra para ser útil.",
		DUG_GRASS = "Le hará falta algo de tierra para ser útil.",
		DUG_MARSH_BUSH = "Le hará falta algo de tierra para ser útil.",
		DUG_SAPLING = "Le hará falta algo de tierra para ser útil.",
		DURIAN = "¡Esto no huele a comida!",
		DURIAN_COOKED = "Cocinada no es mejor.",
		DURIAN_SEEDS = "¿Veis, semillas?",
		EARMUFFSHAT = "Ese sombrero hace sonidos chirriantes.",
		EARRING = "¡Sí! ¡Mi viejo pendiente!",
		EEL = "¡Malandrín!",
		EEL_COOKED = "¡Malandrín a la parrilla!",
		EGGPLANT = "Es de un color morado muy bonito.",
		EGGPLANT_COOKED = "Fíjate lo que ha cocinado Patapalo.",
		EGGPLANT_SEEDS = "¿Veis, semillas?",
		ELEPHANTCACTUS = "Patapalo debe tener cuidado.",
		ELEPHANTCACTUS_ACTIVE = "¡Es una planta peligrosa!",
		ELEPHANTCACTUS_STUMP = "¡Esa planta diabólica está acumulando energía para atacar de nuevo!",		
		EVERGREEN =
		{
			BURNING = "Tu utilidad se está acabando.",
			BURNT = "Ahora no podrás propagar tus semillas.",
			CHOPPED = "Tus raíces terrenales son profundas.",
			GENERIC = "Este es un material bueno para construir barcos.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Ese árbol está ardiendo.",
			BURNT = "No construiré un barco contigo.",
			CHOPPED = "Pareces un poco pequeño.",
			GENERIC = "Ese árbol parece desigual.",
		},
		EYEBRELLAHAT = "Vigila bien al viejo Patapalo.",
		EYEPLANT = "Te veo.",
		EYETURRET = "Un cañón mágico.",
		EYETURRET_ITEM = "Necesitará una base para que sea útil.",
		FABRIC = "¡Tela para una vela!",
		FARMPLOT =
		{
			BURNT = "Está ennegrecido.",
			GENERIC = "Supongo que la tierra dará algo útil.",
			GROWING = "Sí, se está liberando de sus lazos terrenales.",
			NEEDSFERTILIZER = "El suelo parece hambriento.",
		},
		FEATHERFAN = "Es una vela para mi cara.",
		FEATHERHAT = "Un sombrero de tesoros con plumas.",
		FEATHERSAIL = "Es ligera como una pluma.",
		FEATHER_CROW = "Esa pluma es grasientamente poderosa.",
		FEATHER_ROBIN = "Mis pies son a pruebas de cosquillas.",
		FEATHER_ROBIN_WINTER = "¿Dónde están todos los colores?",
		FEM_PUPPET = "Parece que estás en un buen aprieto.",
		FERTILIZER = "Esto puede abonar algunas plantas.",
		FIREFLIES =
		{
			GENERIC = "Pequeñas constelaciones. No sirven para la navegación.",
			HELD = "Estrellas diminutas en mis bolsillos.",
		},
		FIREHOUND = "¡Apártate de mis patas!",
		FIREPIT =
		{
			EMBERS = "Esto está casi quemado.",
			GENERIC = "Tengo que tener cuidado de no quemarme las patas.",
			HIGH = "Es una bendición que mi barco esté cerca.",
			LOW = "Va a necesitar pronto algo de combustible.",
			NORMAL = "Mejor mantendré la distancia.",
			OUT = "El fuego se ha ido.",
		},
		FIRESTAFF = "Patapalo ha aprendido a no jugar con fuego.",
		FIRESUPPRESSOR =
		{
			LOWFUEL = "Está casi vacío.",
			OFF = "Espero que no haya incendios por aquí.",
			ON = "Este área está protegida de los incendios.",
		},
		FISH = "¡Pescado! Uno de mis favoritos.",
		FISHINGROD = "Esto es una herramienta útil.",
		FISHINHOLE = "¡Un banco de arena! ¡Haré una nota en el mapa!",
		FISHSTICKS = "Patapalo ha convertido el pescado en palitos.",
		FISHTACOS = "La concha crujiente está deliciosa.",
		FISH_COOKED = "Este pez asado está bueno.",
		FISH_MED = "Ya no es un lobo de mar.",
		FISH_MED_COOKED = "Esto está un poco mejor.",
		FISH_RAW = "Hace falta calentarlo un poco.",
		FISH_RAW_SMALL = "Apenas hay un bocado de pescado.",
		FISH_RAW_SMALL_COOKED = "Esto está un poco mejor.",
		FLAMEGEYSER = "Patapalo debe de estar sobre un mar de fuego.",
		FLINT = "Esa roca es muy afilada.",
		FLOTSAM = "Los restos de un barco.",
		FLOWER = "Una flor bonita.",
		FLOWERHAT = "Una bonita guirnalda.",
		FLOWERSALAD = "Es una comida con flores bonita.",
		FLOWER_CAVE = "Qué flor más bonita.",
		FLOWER_CAVE_DOUBLE = "Qué flor más bonita.",
		FLOWER_CAVE_TRIPLE = "Qué flor más bonita.",
		FLOWER_EVIL = "Una flor maligna. ¡Apártate!",
		FLUP = "¡Regresa a la tierra!",
		FOLIAGE = "Esto es de tierra firme.",
		FOOTBALLHAT = "Mantiene segura mi chaveta.",
		FROG =
		{
			DEAD = "¡Al cofre de Davy Jones!",
			GENERIC = "¡Salta cerca de Patapalo!",
			SLEEPING = "Ese diablo está dormido.",
		},
		FROGGLEBUNWICH = "¡Sándwich de patas!",
		FROGLEGS = "¡En algún lugar hay una rana andando con dos patas de palo!",
		FROGLEGS_COOKED = "Pollo de goma, me gusta.",
		FROG_POISON = "¡Aparta tu veneno lejos de mí, bestia!",
		GASHAT = "Huele a frescor cuando lo llevo.",
		GEMSOCKET =
		{
			GEMS = "Esta lleno de tesoro.",
			VALID = "Esto está lleno de tesoros.",
		},
		GHOST = "¡No me harás nada, espíritu!",
		GLOMMER = "Tú serás mi primer oficial.",
		GLOMMERFLOWER =
		{
			DEAD = "Se ha secado.",
			GENERIC = "Algo mágico está relacionado con esto.",
		},
		GLOMMERFUEL = "Deja la cubierta hecha un desastre, pero a Patapalo le encanta.",
		GLOMMERWINGS = "Me ha dejado un pequeño tesoro pegajoso.",
		GOATMILK = "¡Sí, la leche fresca es rara en el mar!",
		GOLDENAXE = "Es una forma de usar el tesoro.",
		GOLDENMACHETE = "Es una espada pesada y poderosa.",
		GOLDENPICKAXE = "Esta hacha está fabricada con un metal suave poderoso.",
		GOLDENPITCHFORK = "El suelo tiene suerte de tocar mi tesoro.",
		GOLDENSHOVEL = "Perfecta para enterrar tesoros.",
		GOLDNUGGET = "Tener oro alrededor me calma el alma.",
		GOOSE_FEATHER = "¡El pájaro debe de ser enorme!",
		GRASS =
		{
			BARREN = "No servirás de mucho a Patapalo.",
			BURNING = "Apártate de mis patas de palo.",
			GENERIC = "Parece como un puñado de hierba.",
			PICKED = "Date prisa y vuelve a crecer.",
			WITHERED = "Ni servirás de mucho a Patapalo así.",
		},
		GRASS_UMBRELLA = "Un poco de agua no hace daño a nadie.",
		GRASS_WATER = "¡Debes de tener muchísima sed!",
		GREENAMULET = "¡Llevar este viejo amuleto me hace parecer tan inteligente!",
		GREENGEM = "Tesoros de esmeralda.",
		GREENSTAFF = "No me opongo a algo de magia útil.",
		GREEN_CAP = "No es mi clase de comida favorita.",
		GREEN_CAP_COOKED = "La hechicera dijo a Patapalo que me curaría la locura.",
		GREEN_MUSHROOM =
		{
			GENERIC = "No se ven muchos de estos en el mar.",
			INGROUND = "Está por debajo del nivel del mar.",
			PICKED = "Ahora navega.",
		},
		GUACAMOLE = "¡Patapalo encontrará más patatas fritas para mojar!",
		GUNPOWDER = "Explota mucho.",
		HAIL_ICE = "¡Mi barco está temblando!",
		HAMBAT = "Hecho con metal de las más finas minas de carne.",
		HAMMER = "Puedes hacer un buen agujero en un barco con esto.",
		HAWAIIANSHIRT = "Ligera y elegante.",
		HEALINGSALVE = "Me calmará las heridas.",
		HEATROCK =
		{
			COLD = "Mi amiga la roca está fría.",
			FROZEN = "¡Mi amiga la roca está congelada!",
			GENERIC = "Mi amiga la roca.",
			HOT = "Mi amiga la roca está ardiendo.",
			WARM = "Mi amiga la roca está calentita.",
		},
		HOME = "Los camarotes del capitán.",
		HOMESIGN =
		{
			BURNT = "Solía indicar algo.",
			GENERIC = "Debe de haber algo importante por aquí.",
		},
		HONEY = "Pegajosa y dulce.",
		HONEYCOMB = "Hay larvas retorciéndose en el interior.",
		HONEYHAM = "¡Un festín digno de un pirata!",
		HONEYNUGGETS = "¡Pepitas de miel!",
		HORN = "Toca la canción del beefalo.",
		HOTCHILI = "Me alegro de tener una lengua de madera.",
		HOUND = "Eh, bestia.",
		HOUNDBONE = "Los restos de algo.",
		HOUNDMOUND = "Los sabuesos viven ahí.",
		HOUNDSTOOTH = "¡Unos cuantos más y Patapalo tendrá un juego completo!",
		ICE = "No vale para navegar.",
		ICEBOX = "Bueno para guardar la comida.",
		ICECREAM = "Refrescante en un día caluroso.",
		ICEHAT = "Me mantiene la cabeza fría.",
		ICEHOUND = "¡Da bastante fresquito!",
		ICEMAKER =
		{
			HIGH = "Funciona como una locomotora.",
			LOW = "Está escupiendo.",
			NORMAL = "Funciona bien.",
			OUT = "Se ha quedado sin combustible.",
			VERYLOW = "¡Se está atragantando!",
		},
		ICEPACK = "Un frío escalofrío recorre esta bolsa.",
		ICESTAFF = "Este báculo está helado.",
		INSANITYROCK =
		{
			ACTIVE = "Esta roca está dando dolor de cabeza a Patapalo.",
			INACTIVE = "Esa roca tiene una mala aura.",
		},
		IRONWIND = "Patapalo prefiere su vela.",
		JAMMYPRESERVES = "Conservadas a la perfección.",
		JELLYFISH = "Impactantemente blandengue.",
		JELLYFISH_COOKED = "Impactantemente sabroso.",
		JELLYFISH_DEAD = "Impactantemente muerto.",
		JELLYFISH_PLANTED = "Impactantemente peligroso.",
		JELLYJERKY = "¿Quién hubiera sabido que una cosa así sería posible?",
		JUNGLETREE =
		{
			BURNING = "Arde con brillo.",
			BURNT = "Huele como saco de carbón.",
			CHOPPED = "Aquí no queda ningún tesoro.",
			GENERIC = "Ese árbol oculta toda clase de tesoros.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Tal vez crezcas hasta ser mi nueva pata de palo.",
            PLANTED = "¡Igual le crecen varias patas!",
        },
		KABOBS = "¡Toda la comida es comida de piratas!",
		KILLERBEE =
		{
			GENERIC = "No pareces muy amigable.",
			HELD = "Ahora eres mía.",
		},
		KNIGHT = "¡El caballero está aquí!",
		KNIGHTBOAT = "¡El barco está aquí!",
		KNIGHT_NIGHTMARE = "No me gustas un pelo.",
		KOALEFANT_SUMMER = "Patapalo te conoce por tu gran calor.",
		KOALEFANT_WINTER = "Patapalo te conoce por tu calor poderoso. Y por ser tan grueso.",
		KRAMPUS = "¿Qué ha hecho el viejo Patapalo?",
		KRAMPUS_SACK = "¡Patapalo nunca volverá a dejar atrás ningún tesoro!",
		LANTERN = "Qué luz tan bonita.",
		LAVAPOOL = "Espero que no me quede atrapado.",
		LAVASPIT =
		{
			COOL = "Ahora parece más seguro.",
			HOT = "Parece bastante ardiente.",
		},
		LEIF = "¡Me alegro de que mis patas de palo no hagan eso!",
		LEIF_SPARSE = "¡Me alegro de que mis patas de palo no hagan eso!",
		LICHEN = "¡Puedo masticar eso!",
		LIGHTBULB = "Luz de noche brillante.",
		LIGHTNINGGOAT =
		{
			CHARGED = "Mejor mantendré la distancia.",
			GENERIC = "Esos cuernos dan miedo.",
		},
		LIGHTNINGGOATHORN = "Parece útil para golpear cosas.",
		LIGHTNING_ROD =
		{
			CHARGED = "¡He esquivado eso!",
			GENERIC = "Me protege de los cielos.",
		},
		LIMESTONE = "No vale para construir barcos.",
		LIMPETROCK =
		{
			GENERIC = "La roca está cubierta de buen alimento.",
			PICKED = "Ahora solo es una roca.",
		},
		LIMPETS = "Pronto estarás en mi estómago.",
		LIMPETS_COOKED = "¡Ñammmm!",
		LITTLE_WALRUS = "Crecerá hasta convertirse en un gran pirata.",
		TREEGUARD = "¡Arrr, con esas patas de árbol somos prácticamente iguales!",
		LIVINGJUNGLETREE = "Ese árbol está echando un mal de ojo a Patapalo.",
		LIVINGLOG = "Es madera maldita.",
		LIVINGTREE = "No le voy a despertar.",
		LOBSTER = "¡No te escaparás de mí!",
		LOBSTERHOLE = "Este es el camarote de esa bestia con caparazón.",
		LOBSTER_DEAD = "¡Sí! Ahora Patapalo puede comérsela.",
		LOBSTER_DEAD_COOKED = "¡Carne caliente del mar!",
		LOCKEDWES = "¡Está bien encerrado!",
		LOG =
		{
			BURNING = "¡Mantente atrás!",
			GENERIC = "Estas son las patas de mi hermano.",
		},
		LOGRAFT = "No parece muy resistente.",
		LUGGAGECHEST = "Podría haber oro dentro.",
		LUREPLANT = "Planta de botín, mejor conservarla.",
		LUREPLANTBULB = "El corazón de la planta saqueada.",
		MACHETE = "¡Corta, corta!",
		MAGIC_SEAL = "¿Qué diablos es esto?",
		MAGMAROCK = "Podría haber algo enterrado ahí.",
		MAGMAROCK_GOLD = "¡Rocas de oro!",
		MALE_PUPPET = "¡Estás atrapado!",
		MANDRAKE =
		{
			DEAD = "Era una bestia muy ruidosa.",
			GENERIC = "Una planta legendaria.",
			PICKED = "¡Deja de graznar!",
		},
		MANDRAKESOUP = "Un brebaje mágico.",
		MANDRAKE_COOKED = "¡Patapalo la ha cocinado!",
		MANGROVETREE = "Las aguas son poco profundas aquí.",
		MANGROVETREE_BURNT = "Está cocinado.",
		MANRABBIT_TAIL = "¡Un poco de suerte!",
		MARBLE = "Liso y fuerte.",
		MARBLEPILLAR = "Una pata de palo de mármol. Para un gigante.",
		MARBLETREE = "Árboles extraños...",
		MARSH_BUSH =
		{
			BURNING = "Ardiendo.",
			GENERIC = "Tiene espadas pequeñas.",
			PICKED = "¡Me has pinchado!",
		},
		MARSH_PLANT = "Verde como los ojos de una sirena.",
		MARSH_PLANT_TROPICAL = "Verde como los ojos de una sirena.",
		MARSH_TREE =
		{
			BURNING = "Ardiendo.",
			BURNT = "¡Mejor él que yo!",
			CHOPPED = "Esto es todo lo que queda.",
			GENERIC = "Un árbol con dagas.",
		},
		MAXWELL = "Me gustaría lanzarlo por la borda.",
		MAXWELLHEAD = "Tiene ojos malvados.",
		MAXWELLLIGHT = "Es una llama oscura.",
		MAXWELLLOCK = "No creo que esto abra ningún tesoro...",
		MAXWELLPHONOGRAPH = "Toca una melodía embrujada.",
		MAXWELLTHRONE = "No es un asiento que quiera tomar.",
		MEAT = "Carne de la bestia.",
		MEATBALLS = "¡Mi comida!",
		MEATRACK =
		{
			BURNT = "Una pena.",
			DONE = "¡Está lista!",
			DRYING = "¡Vuela, vuela, hasta la boca!",
			DRYINGINRAIN = "La lluvia no ayuda.",
			GENERIC = "Un lugar para colgar la carne.",
		},
		MEAT_DRIED = "¡La cecina me dura meses en el mar!",
		MERM = "Malandrín.",
		MERMFISHER = "¡Al menos puede pescar peces!",
		MERMHEAD =
		{
			BURNT = "Está crujiente.",
			GENERIC = "Cuidado...",
		},
		MERMHOUSE =
		{
			BURNT = "Hasta nunca.",
			GENERIC = "No me fío de ellos.",
		},
		MERMHOUSE_FISHER = "¡Huelen peor que Patapalo!",
		MESSAGEBOTTLE = "¡Jo, jo! ¿Será un mapa?",
		MESSAGEBOTTLEEMPTY = "Está vacía.",
		MINERHAT = "Una luz en el mar me mantiene tranquilo.",
		MINOTAUR = "Las historias que he oído de este diablo...",
		MINOTAURCHEST = "¿¡Cómo lo lleva Patapalo hasta el barco!?",
		MINOTAURHORN = "¡Sí, un tesoro de verdad!",
		MOLE =
		{
			ABOVEGROUND = "¿Qué está olisqueando?",
			HELD = "Tranquila, mascota.",
			UNDERGROUND = "¡Está nadando bajo tierra!",
		},
		MOLEHAT = "¡Son como los ojos de un fantasma de noche!",
		MOLEHILL = "Está durmiendo bajo tierra.",
		MONKEY = "Una vez vi un mono con un garfio.",
		MONKEYBARREL = "Seguro que ahí esconden tesoros.",
		MONSTERLASAGNA = "No es mi comida favorita.",
		MONSTERMEAT = "Un poco amarga.",
		MONSTERMEAT_DRIED = "He secado a esa bestia.",
		MOOSE = "¡Apártate de mi barco!",
		MOOSEEGG = "¡Qué bestia acecha dentro!",
		MOSQUITO =
		{
			GENERIC = "Su zumbido me está poniendo nervioso.",
			HELD = "¡Será mejor que no me piques a través del bolsillo!",
		},
		MOSQUITOSACK = "Parece una medusa.",
		MOSQUITOSACK_YELLOW = "¡Era una bestia con la tripa amarilla!",
		MOSQUITO_POISON = "¡Atrás, bicho asqueroso!",
		MOSSLING = "¡Ah del barco, pato grande!",
		MOUND =
		{
			DUG = "¡Tengo que buscar el tesoro!",
			GENERIC = "No es mal lugar para esconder tu plata.",
		},
		MULTITOOL_AXE_PICKAXE = "Es multiusos.",
		MUSHTREE_MEDIUM = "Un árbol de champiñones, ahora ya lo he visto todo.",
		MUSHTREE_SMALL = "¡Brilla!",
		MUSHTREE_TALL = "¿Qué hace ese champiñón tan arriba?",
		MUSSEL = "¡A Patapalo le encantan los mejillones!",
		MUSSEL_COOKED = "Arrr, esto está bueno.",
		MUSSEL_FARM =
		{
			GENERIC = "¡Hay que recogerlo!",
			STICKPLANTED = "Esperar a que crezca la comida no es lo mío...",
		},
		MUSSEL_STICK = "Para atraer a los mejillones a mi barriga.",
		NEEDLESPEAR = "Una especie de puñal.",
		NIGHTLIGHT = "No ofreces mucha comodidad, ¿eh?",
		NIGHTMAREFUEL = "He visto la magia oscura del mar...",
		NIGHTMARELIGHT = "Patapalo no se fía de esta luz.",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Todo está en calma.",
			DAWN = "Se está esfumando...",
			NOMAGIC = "Ni una pizca de magia.",
			STEADY = "¡La pesadilla está en su apogeo!",
			WANING = "Siento como si mis patas de palo estuvieran muriéndose.",
			WARN = "Hay algo que no me gusta...",
			WAXING = "¡Está construyéndose!",
		},
		NIGHTSTICK = "¡Una espada brillante!",
		NIGHTSWORD = "Mi alfanje maldito.",
		NITRE = "Es carne de cañón.",
		OBSIDIAN = "Una piedra poderosa.",
		OBSIDIANAXE = "¡Aparta eso de mis patas!",
		OBSIDIANCOCONADE = "¡Boom!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Esto está casi quemado.",
			GENERIC = "Tengo que tener cuidado de no quemarme las patas.",
			HIGH = "Es una bendición que mi barco esté cerca.",
			LOW = "Va a necesitar pronto algo de combustible.",
			NORMAL = "Fuego caliente.",
			OUT = "El fuego se ha ido.",
		},
		OBSIDIANMACHETE = "¡Se está poniendo caliente!",
		OBSIDIANSPEARGUN = "¡Dispara fuego!",
		OBSIDIAN_WORKBENCH = "La leyenda es cierta...",
		OCTOPUSCHEST = "¿Qué hay dentro para el viejo Patapalo?",
		OCTOPUSKING = "¡Ah del barco, perro salado!",
		ONEMANBAND = "¿Para qué sirve esto?",
		ORANGEAMULET = "Mi cadena mágica.",
		ORANGEGEM = "¡A Patapalo le encantan todas las gemas!",
		ORANGESTAFF = "¡Patas de palo mágicas!",
		OX = "Le vendría bien un abrazo pirata.",
		PACKIM = "¡Ese es mi compañero!",
		PACKIM_FISHBONE = "El corazón de un ave. Por así decirlo.",
		PALMLEAF = "¿Quñe puedo hacer con esto aquí?",
		PALMLEAF_HUT = "¡Necesita una hamaca!",
		PALMLEAF_UMBRELLA = "Es un pirata con paraguas.",
		PALMTREE =
		{
			BURNING = "Arde con brillo.",
			BURNT = "Huele como saco de carbón.",
			CHOPPED = "Aquí no queda ningún tesoro.",
			GENERIC = "Da una buena sombra.",
		},
		PANDORASCHEST = "¡Yuju! ¡Un tesoro para mí!",
		PANFLUTE = "Te hipnotiza hasta quedarte dormido.",
		PAPYRUS = "¡Sí! ¡Un mapa nuevo!",
		PARROT = "Es un pajarito muy bonito.",
		PENGUIN = "Una señal segura de hielo en el mar.",
		PERD = "¡Qué maníaco!",
		PEROGIES = "¡Patapalo podría comer un cofre entero de estos!",
		PETALS = "Esas flores no volverán a la vida.",
		PETALS_EVIL = "Flores embrujadas.",
		PICKAXE = "¡Excavemos tesoros!",
		PIGGUARD = "¡No resoples delante de mí!",
		PIGGYBACK = "De la carne del jabalí.",
		PIGHEAD =
		{
			BURNT = "Crujiente.",
			GENERIC = "A veces le brillan los ojos...",
		},
		PIGHOUSE =
		{
			BURNT = "El fuego ha hecho su trabajo aquí.",
			FULL = "Ven, cerdito, ven.",
			GENERIC = "Parece como un edificio anexo, ¿verdad?",
			LIGHTSOUT = "Está echando una cabezada.",
		},
		PIGKING = "Este es rico.",
		PIGMAN =
		{
			DEAD = "Buenas noches, cerdo.",
			FOLLOWER = "¡Sígueme, cerdito!",
			GENERIC = "¿Crees que habla latín?",
			GUARD = "¡No resoples delante de mí!",
			WEREPIG = "¿¡Que te ha pasado!?",
		},
		PIGSKIN = "Ha perdido el trasero.",
		PIGTENT = "¿Qué hay dentro?",
		PIGTORCH = "Apuesto a que vale mucho...",
		PIKE_SKULL = "Sigue andando.",
		PINECONE =
		{
			GENERIC = "La semilla del árbol.",
			PLANTED = "Crece hasta convertirte en un barco.",
		},
		PIRATEHAT = "¡Jo, jo, jo!",
		PIRATEPACK = "¡Creí que lo había perdido!",
		PIRATIHATITATOR =
		{
			BURNT = "Qué pena.",
			GENERIC = "Tiene un aspecto genial con ese sombrero.",
		},
		PITCHFORK = "¿Podré excavar tesoros con esto?",
		PLANTMEAT = "Una carne sospechosa.",
		PLANTMEAT_COOKED = "Lo he cocinado yo.",
		PLANT_NORMAL =
		{
			GENERIC = "¿Puede comerla Patapalo?",
			GROWING = "Esperando y esperando.",
			READY = "¡Arrr, está lista!",
			WITHERED = "Demasiado calor para sus pequeñas raíces.",
		},
		POISONHOLE = "El peor tipo de agujero.",
		POMEGRANATE = "Mis compañeros dicen que esto es bueno para el corazón.",
		POMEGRANATE_COOKED = "Semillas.",
		POMEGRANATE_SEEDS = "Semillas con las que crecen más semillas.",
		POND = "Un barco de verdad no cabría aquí.",
		POND_ALGAE = "Un barco de verdad no cabría aquí.",
		POOP = "¿¡Qué malandrín habrá dejado sus excrementos por aquí!?",
		PORTAL_SHIPWRECKED = "¡Parece un paseo encantador!",
		POTTEDFERN = "¿Para qué me va a servir una planta doméstica?",
		POWCAKE = "¿Es esto de verdad comida?",
		PRIMEAPE = "Como mirarse en un espejo roto y grasiento.",
		PRIMEAPEBARREL = "No les gusta mucho la organización.",
		PUMPKIN = "Haría una buena bola de cañón.",
		PUMPKINCOOKIE = "No soy muy goloso.",
		PUMPKIN_COOKED = "El cocinero del barco solía añadir una pizca de canela.",
		PUMPKIN_LANTERN = "Un poco pesada para una linterna.",
		PUMPKIN_SEEDS = "Lo mío no es la granja, pero me encantan las calabazas...",
		PURPLEAMULET = "¡Queda bien en Patapalo!",
		PURPLEGEM = "¡Reluciente y valiosa!",
		RABBIT =
		{
			GENERIC = "Criatura saltarina.",
			HELD = "Ahora estate quieto en mi bolsillo.",
		},
		RABBITHOLE =
		{
			GENERIC = "¿Tendrán tesoros ahí abajo?",
			SPRING = "Esos conejitos no salen.",
		},
		RABBITHOUSE =
		{
			BURNT = "¡Quemada hasta convertirse en cenizas!",
			GENERIC = "Esa es una zanahoria muy grande.",
		},
		RAFT = "¡Ese navío es una vergüenza!",
		RAINCOAT = "Me mantiene la blusa seca.",
		RAINHAT = "Mantiene tu cabeza seca.",
		RAINOMETER =
		{
			BURNT = "¡No se puede predecir el fuego, eh!",
			GENERIC = "¡Los marineros son imanes para la lluvia, arrr!",
		},
		RATATOUILLE = "¡Superalimento contra el escorbuto!",
		RAWLING = "Me recuerda a mi viejo loro.",
		RAZOR = "Afeitarse es para príncipes y abogados.",
		REDBARREL = "Calaveras y tibias solo significan una cosa de donde vengo.",
		REDGEM = "¡Brilla como el sol!",
		RED_CAP = "Espero que el color no sea un aviso...",
		RED_CAP_COOKED = "Mi color favorito de champiñón.",
		RED_MUSHROOM =
		{
			GENERIC = "Es un champiñón de color alarmante.",
			INGROUND = "No quiero cogerlo todavía.",
			PICKED = "Champiñón arrancado.",
		},
		REEDS =
		{
			BURNING = "Arden rápido.",
			GENERIC = "¡Seguro que puedo silbar una melodía con esto!",
			PICKED = "Es la caña.",
		},
		REFLECTIVEVEST = "Reflejado otra vez hacia ti.",
		RELIC =
		{
			BROKEN = "Ahora ya no vale ni medio doblón.",
			GENERIC = "Me pregunto si podría venderlo en el mercado negro.",
		},
		RESEARCHLAB =
		{
			BURNT = "Supongo que la ciencia no es tan lista al final y al cabo.",
			GENERIC = "He oído hablar de esto de la ciencia. Avanza mucho.",
		},
		RESEARCHLAB2 =
		{
			BURNT = "Ya no hará lo que fuese que hiciera antes.",
			GENERIC = "¿Esto qué hace?",
		},
		RESEARCHLAB3 =
		{
			BURNT = "Las artes oscuras no te han salvado.",
			GENERIC = "La brujeria no ha tenido piedad con esto.",
		},
		RESEARCHLAB4 =
		{
			BURNT = "¡Bien! No me gustaba decir tu nombre de todas formas.",
			GENERIC = "No tengo bastante con aprender a decir una palabra como esa.",
		},
		RESURRECTIONSTATUE =
		{
			BURNT = "No resucitará nada más.",
			GENERIC = "¡No me captures a mí!",
		},
		RESURRECTIONSTONE = "Mi nariz huele a brujería...",
		ROBIN =
		{
			GENERIC = "Tú no hablas, ¿verdad?",
			HELD = "Patapalo cuidará de ti.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Es una belleza.",
			HELD = "Es un pájaro frío.",
		},
		ROBOT_PUPPET = "¡Está encerrado!",
		ROCK = "Esto rompería un casco.",
		ROCKS = "Se hunden.",
		ROCKY = "¡Atrás, diablo con garras!",
		ROCK_CHARCOAL = "Podría empezar una buena barbacoa con esto.",
		ROCK_ICE =
		{
			GENERIC = "Mejor aquí que debajo de mi barco destrozando el casco.",
			MELTED = "Necesita enfriarse.",
		},
		ROCK_ICE_MELTED = "Necesita un poco de frío para que pueda volver a congelarse.",
		ROCK_LIGHT =
		{
			GENERIC = "Un charco de fuego.",
			LOW = "Se está apagando.",
			NORMAL = "No está mal para ver.",
			OUT = "Se apagó.",
		},
		ROCK_OBSIDIAN = "Roca de fuego de una montaña de fuego.",
		ROOK = "¡Va a toda velocidad!",
		ROOK_NIGHTMARE = "Esta bestia ha sido maldecida.",
		ROPE = "Para atar cosas.",
		ROTTENEGG = "Huele como los camarotes después de una noche de guindillas.",
		ROWBOAT = "No he remado desde que era un pequeño malandrín.",
		RUBBLE = "Solo un montón de escombros.",
		RUINSHAT = "Una corona de joyas.",
		RUINS_BAT = "¡Qué belleza!",
		RUINS_RUBBLE = "Patapalo puede volver a construir esto.",
		SAIL = "Para aprovecharse del viento.",
		SAIL_STICK = "Mantiene el viento a mi espalda.",
		SAND = "Un puñado de tierra.",
		SANDBAG = "Para mantener las inundaciones a raya.",
		SANDBAGSMALL = "Para mantener las inundaciones a raya.",
		SANDBAG_ITEM = "Para mantener las inundaciones a raya.",
		SANDHILL = "Nada como sentir la arena debajo de mis patas de palo.",
		SAND_CASTLE =
		{
			GENERIC = "¡Soy un maestro constructor de castillos de arena!",
			SAND = "¡Ningún pirate puede construir un castillo de arena mejor que el viejo Patapalo!",
		},
		SANITYROCK =
		{
			ACTIVE = "Esa roca es muy extraña.",
			INACTIVE = "A esa extraña roca le faltan piezas.",
		},

		SAPLING =
		{
			BURNING = "La madera arde.",
			GENERIC = "Pequeña madera.",
			PICKED = "No se podrán recolectar más por un tiempo.",
			WITHERED = "Necesita un chorro de ron.",
		},
		SEAGULL = "Una rata con alas.",
		SEAGULL_WATER = "¡Ah del barco, marinero!",
		SEASACK = "Aquí guardo todas mis pertenencias.",
		SEASHELL = "Oigo el azul.",
		SEASHELL_BEACHED = "Baratija del mar.",
		SEATRAP = "¡Un almuerzo de pirata para mí!",
		SEAWEED = "Se enredan en mis aparejos.",
		SEAWEED_COOKED = "Por mucho que la cocines no será comida.",
		SEAWEED_DRIED = "¿Esto se supone que se hace pasar por cecina?",
		SEAWEED_PLANTED = "Se enredan en mis aparejos.",
		SEEDS = "¡Patapalo no es un granjero de agua dulce!",
		SEEDS_COOKED = "Plántalas en mi barriga.",
		SEWING_KIT = "Necesito tela para poder coser.",
		SHARKITTEN = "No me mires con esos ojos tan adorables...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Los gatiburones afilan sus garras aquí.",
			INACTIVE = "¿Hola, gatito?",
		},
		SHARK_FIN = "¡Te has dejado el timón, diablo de mar!",
		SHARK_GILLS = "¡Ya no volverás a respirar con esto!",
		SHARK_TEETHHAT = "Qué locura poner las cuchillas del diablo sobre mi cabeza.",
		SHARX = "¡Diablos de mar!",
		SHOVEL = "¡Soy un buscador de oro!",
		SIESTAHUT =
		{
			BURNT = "Ahora no vale para echarse la siesta.",
			GENERIC = "Odio dormir en tierra.",
		},
		SILK = "¡Se usa en las camisas piratas de la mejor calidad!",
		SKELETON = "Se te ha acabado la suerte, amigo.",
		SKELETON_PLAYER = "Tan familiar...",
		SKULLCHEST = "Qué tesoros debe de haber devorado.",
		SLOTMACHINE = "Siempre me consideré un jugador.",
		SLURPER = "Eres feo, malandrín.",
		SLURPERPELT = "¡Qué olor!",
		SLURPER_PELT = "¡Qué olor!",
		SLURTLE = "Mírala, arrastrándose feliz.",
		SLURTLEHAT = "¿En mi cabeza?",
		SLURTLEHOLE = "Se arrastran hasta entrar ahí, ¿verdad?",
		SLURTLESLIME = "Parece que como un escupitinajo mío.",
		SLURTLE_SHELLPIECES = "No se me dan bien los rompecabezas.",
		SMALLBIRD =
		{
			GENERIC = "Arrr, ¿qué clase de pajarraco eres tú?",
			HUNGRY = "¿Te están sonando las plumas?",
			STARVING = "Te vas a morir de hambre.",
		},
		SMALLMEAT = "Es pequeña, pero es carne.",
		SMALLMEAT_DRIED = "¡Toma, cecina!",
		SNAKE = "¡Diablo de lengua partida!",
		SNAKEDEN =
		{
			BURNT = "Solo una forma de desatar un nudo.",
			CHOPPED = "Ahora ya estás recta.",
			GENERIC = "Pareces como un montón de aparejos enredados.",
		},
		SNAKEOIL = "Sé distinguir una buena oferta cuando la veo.",
		SNAKESKIN = "Necesito un chaleco nuevo.",
		SNAKESKINHAT = "¿Llevar eso? ¿En mi cabeza?",
		SNAKE_POISON = "¡Apártate, diablo con lengua partida!",
		SNURTLE = "Te atraparía si tuviera mi bote a mano.",
		SOLOFISH = "¡Perro salado!",
		SPEAR = "Podría estar pinchando con esto todo el día.",
		SPEARGUN = "Eres una buena arma.",
		SPEARGUN_POISON = "¿Qué malandrín usaría una cosa así?",
		SPEAR_OBSIDIAN = "¡Te pincho con fuego!",
		SPEAR_POISON = "El arma de un cobarde.",
		SPIDER =
		{
			DEAD = "¡Bien!",
			GENERIC = "Te tiene que gustar mucho la tierra con tantas patas.",
			SLEEPING = "Está soñando con la punta de mi bota.",
		},
		SPIDERDEN = "Prefiero una cueva de ladrones.",
		SPIDEREGGSACK = "¿Quieres que Patapalo haga ahora de niñera de bichejos?",
		SPIDERGLAND = "He comido cosas peores.",
		SPIDERHAT = "¿Llevar una araña en la cabeza? ¡Bah!",
		SPIDERHOLE = "Lo que viva ahí dentro no me preocupa.",
		SPIDERQUEEN = "¡Patapalo no se inclina ante ninguna reina ni ninguna araña!",
		SPIDER_DROPPER = "¡Bichos amarillos!",
		SPIDER_HIDER = "¡Arañas infernales!",
		SPIDER_SPITTER = "Creo que puedo escupir más lejos que tú.",
		SPIDER_WARRIOR =
		{
			DEAD = "¡Guerrera, no me hagas reír!",
			GENERIC = "Ocho patas con las que andar por la tierra.",
			SLEEPING = "¿Sueñas con moscas?",
		},
		SPOILED_FISH = "Huele como si el mismo diablo se hubiera tirado un pedo.",
		SPOILED_FOOD = "He comido cosas peores.",
		STAFFLIGHT = "Las estrellas no están al alcance del hombre.",
		STAFF_TORNADO = "¿Eso qué es, por mil demonios?",
		STALAGMITE = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_FULL = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_LOW = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_MED = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_TALL = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_TALL_FULL = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_TALL_LOW = "Me gustan las rocas donde pueda verlas.",
		STALAGMITE_TALL_MED = "Me gustan las rocas donde pueda verlas.",
		STATUEGLOMMER =
		{
			EMPTY = "Se ha roto.",
			GENERIC = "Estatua fea.",
		},
		STATUEHARP = "¡Te falta la cabeza!",
		STATUEMAXWELL = "¡He visto la cara de ese malandrín en todas partes!",
		STINGER = "A la avispa se la caído la cola.",
		STRAWHAT = "No apto para un capitán. Pero queda bonito en la cabeza.",
		STUFFEDEGGPLANT = "¿De qué está esto relleno?",
		STUNGRAY = "¡Atrás, apestoso bicho!",
		SUNKBOAT = "Algunos compañeros se han quedado sin suerte...",
		SUNKEN_BOAT =
		{
			ABANDONED = "Hombre al agua.",
			GENERIC = "Te lanzaría una cuerda si tuviera una.",
		},
		SUNKEN_BOAT_BURNT = "Hundido y quemado. Eso sí que es mala suerte.",
		SUNKEN_BOAT_TRINKET_1 = "Un capitán que se precie no necesita esto.",
		SUNKEN_BOAT_TRINKET_2 = "Para un niño pirata.",
		SUNKEN_BOAT_TRINKET_3 = "Las velas y el agua no combinan.",
		SUNKEN_BOAT_TRINKET_4 = "¡Bah! ¡Paparruchas!",
		SUNKEN_BOAT_TRINKET_5 = "Ya tengo una buena bota.",
		SUPERTELESCOPE = "¡El ojo ve claramente el horizonte!",
		BANANAPOP = "He oído que hay oro dentro del plátano.",
		BISQUE = "¡Un delicioso plato para mojar el gaznate!",
		CEVICHE = "¡Qué criaturas más sabrosas hay en el mar!",
		SEAFOODGUMBO = "¡Abajo por el pescuezo!",
		SURFNTURF = "Preferiría sin tanta carne.",
		SHARKFINSOUP = "¡Ahora Patapalo puede devorarte a ti!",
		LOBSTERDINNER = "¡Me encanta comerlas!",
		LOBSTERBISQUE = "¡Combate el escorbuto!",
		JELLYOPOP = "¡La especialidad de Patapalo!",
		SWEATERVEST = "Perfecto para una fiesta.",
		SWEET_POTATO = "¡Me gustan las batatas!",
		SWEET_POTATO_COOKED = "¡Comida caliente!",
		SWEET_POTATO_PLANTED = "Un tipo diferente de tesoro enterrado.",
		SWEET_POTATO_SEEDS = "Las semillas son para plantar, y Patapalo no es ningún granjero.",
		SWORDFISH = "Arrr, quieres clavar esa nariz en el viejo Patapalo, ¿eh?",
		TAFFY = "Se me queda pegado en los dientes que no tengo.",
		TALLBIRD = "¡No tendrías esa cola tan grande si tuviera mi sable conmigo!",
		TALLBIRDEGG = "¿Cuándo saldrá el pajarraco?",
		TALLBIRDEGG_COOKED = "¡Me gusta el ron de yema de pájaro alto!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Necesita que algún pajarraco se siente encima.",
			GENERIC = "¿Vas a salir ya?",
			HOT = "No te calientes conmigo.",
			LONG = "Tardaré en ver salir a este pájaro del cascarón.",
			SHORT = "¡El pajarraco va a salir en cualquier momento!",
		},
		TALLBIRDNEST =
		{
			GENERIC = "¡Eso es un huevo grande!",
			PICKED = "La cesta de huevos está vacía.",
		},
		TEENBIRD =
		{
			GENERIC = "Tú no eres tan alto, ¿eh?",
			HUNGRY = "Será mejor que encuentre algo de comida para tu tripa.",
			STARVING = "¡No estarás pensado en comerte al viejo Patapalo!",
		},
		TELEBASE =
		{
			GEMS = "Necesita más gemitas moradas.",
			VALID = "¡Ahora está enfocada!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "No sé a dónde lleva, pero está listo para transportarme.",
			GENERIC = "¡Podría llevar al viejo Patapalo hasta el fin de los mares!",
			LOCKED = "La falta una pieza.",
			PARTIAL = "Está casi listo.",
		},
		TELEPORTATO_BOX = "Un simple pirata como yo no sabe para qué sirve esto.",
		TELEPORTATO_CRANK = "Por lo que veo es una manivela.",
		TELEPORTATO_POTATO = "Qué armadura tan extraña.",
		TELEPORTATO_RING = "Un anillo sin joyas, ¡bah!",
		TELEPORTATO_SW_BASE = "Qué pieza más curiosa.",
		TELEPORTATO_SW_BOX = "Hay secretos escondidos en esta caja.",
		TELEPORTATO_SW_CRANK = "Sí, Patapalo probará esto.",
		TELEPORTATO_SW_POTATO = "Nunca sabré para que necesita una patata un casco.",
		TELEPORTATO_SW_RING = "Lo morderé, pero sé que no es oro.",
		TELESCOPE = "¡Ojo por ojo!",
		TELESTAFF = "Prefiero un barco rápido y el viento a mi espalda.",
		TENT =
		{
			BURNT = "Esto es lo que pasa por fiarte de dormir en tierra.",
			GENERIC = "Prefiero una cama de agua.",
		},
		TENTACLE = "¡Como en mis sueños!",
		TENTACLESPIKE = "¡Ajá! ¡Ahora tengo a este diablo en mis propias manos!",
		TENTACLESPOTS = "Me falla la memoria. ¿Para qué sirve esto de nuevo?",
		TENTACLE_GARDEN = "¡Es asqueroso!",
		TENTACLE_PILLAR = "Serviría para un mástil resbaladizo.",
		TENTACLE_PILLAR_ARM = "¡Es asqueroso!",
		THATCHPACK = "¡Cuánta paja!",
		THULECITE = "¿Me pregunto para qué valdrá esto?",
		THULECITE_PIECES = "Sabe a poderoso oro.",
		TIDALPOOL = "Veo el futuro...",
		TIDAL_PLANT = "Vegetales de hojas verde de la marea alta.",
		TIGERSHARK = "¡Ven hacia mí, diablo con rayas!",
		TOPHAT = "Hasta un sucio pirata podría acicalarse algún día.",
		TORCH = "¡Ahora puedo ver tesoros en la oscuridad!",
		TOUCAN = "No te llamarás Sam, ¿verdad?",
		TRAILMIX = "Prefiero los aperitivos marinos.",
		TRANSISTOR = "¿Esto qué es?",
		TRAP = "Prefiero enfrentarme a mis enemigos cara a cara.",
		TRAP_TEETH = "Yo puede que no tenga dientes, pero esta trampa sí los tiene.",
		TRAP_TEETH_MAXWELL = "No voy a caer en esa trampa.",
		TRAWLNET = "Para hacer pesca de arrastre.",
		TRAWLNETDROPPED =
		{
			GENERIC = "¡Suelta tu redada!",
			SOON = "Tu redada pronto sera mía.",
			SOONISH = "Dame tu redada.",
		},
		TREASURECHEST =
		{
			BURNT = "¡Nooooooooooo!",
			GENERIC = "Sí, el significado de la vida en una caja.",
		},
		TREASURECHEST_TRAP = "¡Tesoro de oro!",
		TREECLUMP = "¡Apártate de mi camino!",
		TRIDENT = "¡Yo creía que esto solo salía en los cuentos!",
		TRINKET_1 = "Para las noches aburridas en alta mar.",
		TRINKET_10 = "¡Mis plegarias han sido escuchadas, arrr!",
		TRINKET_11 = "¡Caja de tuercas con la lengua larga!",
		TRINKET_12 = "¿Pero esto qué es?",
		TRINKET_13 = "¡Un refresco!",
		TRINKET_14 = "No me entrometo con la brujería.",
		TRINKET_15 = "No puedo tocar una nota.",
		TRINKET_16 = "Una placa extraña.",
		TRINKET_17 = "¡Una bota!",
		TRINKET_18 = "No sé apreciar las antigüedades delicadas.",
		TRINKET_19 = "Para devanarse los sesos.",
		TRINKET_2 = "Ojalá fuera de verdad.",
		TRINKET_23 = "Incluso aunque no estuviera roto, no sabría que hacer con él.",
		TRINKET_3 = "Gordiano sabe cómo deshacer un nudo.",
		TRINKET_4 = "¡Diablo con gorro rojo!",
		TRINKET_5 = "No conozco esta clase de barco.",
		TRINKET_6 = "¿Quién demonios ha atado este nudo?",
		TRINKET_7 = "¡Sí, el nuevo juego de moda!",
		TRINKET_8 = "Un tapón duro.",
		TRINKET_9 = "Me da igual que sean de otro color.",
		TROPICALFAN = "Sofoca el calor.",
		TROPICAL_FISH = "¡Sí, mi comida preferida!",
		TRUNKVEST_SUMMER = "¡Ropa de una nariz!",
		TRUNKVEST_WINTER = "¡Ropa de una nariz!",
		TRUNK_COOKED = "He comido narices más desagradables que esta.",
		TRUNK_SUMMER = "¿Habrá joyas y riquezas aquí dentro?",
		TRUNK_WINTER = "¿Habrá joyas y riquezas aquí dentro?",
		TUMBLEWEED = "Me gusta que los hierbajos estén quietos.",
		TUNACAN = "¡Pez enlatado!",
		TURBINE_BLADES = "Creo que habrá un uso para esto.",
		TURF_SANDY = "Yo no soy un marinero de agua dulce.",
		TURF_ASH = "Yo no soy un marinero de agua dulce.",
		TURF_BADLANDS = "Yo no soy un marinero de agua dulce.",
		TURF_BEACH = "Yo no soy un marinero de agua dulce.",
		TURF_CARPETFLOOR = "Yo no soy un marinero de agua dulce.",
		TURF_CAVE = "Yo no soy un marinero de agua dulce.",
		TURF_CHECKERFLOOR = "Yo no soy un marinero de agua dulce.",
		TURF_DECIDUOUS = "Yo no soy un marinero de agua dulce.",
		TURF_DESERTDIRT = "Yo no soy un marinero de agua dulce.",
		TURF_DIRT = "Yo no soy un marinero de agua dulce.",
		TURF_FOREST = "Yo no soy un marinero de agua dulce.",
		TURF_FUNGUS = "Yo no soy un marinero de agua dulce.",
		TURF_FUNGUS_GREEN = "Yo no soy un marinero de agua dulce.",
		TURF_GRASS = "Yo no soy un marinero de agua dulce.",
		TURF_JUNGLE = "Yo no soy un marinero de agua dulce.",
		TURF_MARSH = "Yo no soy un marinero de agua dulce.",
		TURF_MEADOW = "Yo no soy un marinero de agua dulce.",
		TURF_MUD = "Yo no soy un marinero de agua dulce.",
		TURF_ROAD = "Yo no soy un marinero de agua dulce.",
		TURF_ROCKY = "Yo no soy un marinero de agua dulce.",
		TURF_SAVANNA = "Yo no soy un marinero de agua dulce.",
		TURF_SINKHOLE = "Yo no soy un marinero de agua dulce.",
		TURF_SNAKESKINFLOOR = "Yo no soy un marinero de agua dulce.",
		TURF_SWAMP = "Yo no soy un marinero de agua dulce.",
		TURF_UNDERROCK = "Yo no soy un marinero de agua dulce.",
		TURF_VOLCANO = "El suelo del diablo.",
		TURF_WOODFLOOR = "Cruje debajo de mi pata de palo.",
		TURKEYDINNER = "¡Este pajarraco está bueno!",
		TWIGS = "Demasiado flacas para reemplazar mi pata de palo.",
		TWISTER = "¡Ese viento está soplando como el aliento del diablo!",
		TWISTER_SEAL = "No me mires con esos ojos tristes.",
		UMBRELLA = "Me gusta mantener la pólvora seca.",
		UNAGI = "¿Comer una anguila? ¿Es ya el desayuno?",
		UNIMPLEMENTED = "No está listo.",
		VENOMGLAND = "Sí, esta es la fuente del veneno.",
		VINE = "Pueden estrangular a alguien.",
		VOLCANO = "Mi prisión.",
		VOLCANOSTAFF = "¡Ahora estarás a mi merced, volcán!",
		VOLCANO_ALTAR =
		{
			GENERIC = "Aquí es donde se soborna al volcán.",
			OPEN = "Listo para el soborno.",
		},
		VOLCANO_ALTAR_BROKEN = "¡Ahora el volcán no estará contento!",
		VOLCANO_EXIT = "Ya era hora que saliera de este lugar terrible.",
		VOLCANO_SHRUB = "Pareces quemado.",
		WAFFLES = "Justo como mamá solía abrir del paquete.",
		WALLYINTRO_DEBRIS = "El mar se ha tragado mi barco, pero ha escupido al viejo Patapalo.",
		WALL_HAY =
		{
			BURNT = "El muro de heno se ha quemado, vete a saber.",
			GENERIC = "Las únicas paredes que tolero son la de mi camarote.",
		},
		WALL_HAY_ITEM = "Espero que no haya caballos salvajes por aquí.",
		WALL_LIMESTONE = "¡Bah! ¡Muros!",
		WALL_LIMESTONE_ITEM = "Los muros me hacen sentir atrapado.",
		WALL_RUINS = "¡Estos muros son más viejos que yo!",
		WALL_RUINS_ITEM = "Muros antiguos para proteger un preciado tesoro.",
		WALL_STONE = "Se hundiría en el mar.",
		WALL_STONE_ITEM = "Muro de piedra para todas las preocupaciones de tierra.",
		WALL_WOOD =
		{
			BURNT = "Ya no será nunca más un muro.",
			GENERIC = "Protege tu territorio si eso es lo que quieres.",
		},
		WALL_WOOD_ITEM = "Los muros son para la tierra y la tierra para los marineros de agua dulce.",
		WALRUS = "¿Cuál es tu historia, compañero?",
		WALRUSHAT = "No es mi estilo.",
		WALRUS_CAMP =
		{
			EMPTY = "Aquí no hay marineros de agua dulce.",
			GENERIC = "Campamento para marineros de agua dulce.",
		},
		WALRUS_TUSK = "Servirías para una bonita pata de palo.",
		WARG = "Eres un bicho grande en tierra, pero en el mar serías alimento para los peces.",
		WASPHIVE = "Dejarlo en paz será lo mejor.",
		WATERMELON = "Sí, está fruta conquista el corazón acuático de Patapalo.",
		WATERMELONHAT = "Me encantan las frutas de agua, pero esto es ridículo.",
		WATERMELONICLE = "¡Un dulce frío de mi fruta favorita!",
		WATERMELON_COOKED = "Mejor de lo que pensaba.",
		WATERMELON_SEEDS = "Ojalá pudiera plantarlas en el agua.",
		WEBBERSKULL = "¿Qué clase de cuello le sirve a esto?",
		WETGOOP = "Por eso nunca dejaron subir al viejo Patapalo a esa galera.",
		WHALE_BLUE = "¿Eres tú el diablo que llevará a Patapalo a las profundidades?",
		WHALE_BUBBLES = "¡Hay un diablo en las profundidades!",
		WHALE_CARCASS_BLUE = "¡Por qué no te hundes y despejas el aire!",
		WHALE_CARCASS_WHITE = "¡Esa ballena huele que apesta!",
		WHALE_WHITE = "¡Ahora eres un diablo digno de luchar con Patapalo!",
		WILBUR_CROWN = "¿En qué clase de cabeza vale esta corona?",
		WILBUR_UNLOCK = "¡Mira qué mono tan gracioso!",
		WILDBORE = "No me pareces muy salvaje.",
		WILDBOREHOUSE = "Seguro que los cerdos saben cómo hacer fiestas, arrr.",
		WIND_CONCH = "Acaba con la tormenta.",
		WINTERHAT = "Impide que mi cabeza se congele.",
		WINTEROMETER =
		{
			BURNT = "Ahora no me sirve.",
			GENERIC = "¡Arrr, brrrrr!",
		},
		WORM =
		{
			DIRT = "Tierra sucia.",
			PLANT = "Maduro para la recogida.",
			WORM = "¡Es una lombriz!",
		},
		WORMHOLE =
		{
			GENERIC = "¿Qué me podría poseer para pisar ahí?",
			OPEN = "¿A dónde conduce, por todas mis barbas?",
		},
		WORMHOLE_LIMITED = "Ese pozo parece que está en sus últimas.",
		WORMLIGHT = "Prende un incendio en tu estómago.",
		YELLOWAMULET = "¡Soy un faro andante!",
		YELLOWGEM = "¡Una gema del color de mis dientes!",
		YELLOWSTAFF = "Las estrellas no están al alcance del hombre.",
		WOODLEGSBOAT = "Mi barco. Es mi \"Pata marina\".",
		WOODLEGSHAT = "¡Es mi sombrero de la suerte!",

		ARMORCACTUS = "¡Me gustaría verlo tratar de golpear a Patapalo ahora!",
		BIGFISHINGROD = "Patapalo las ha visto más grandes.",
		--BOOK_METEOR = "Devil magic thet summons demons from th'sky!",
		BRAINJELLYHAT = "Una medusa para ponérmela en mi delicada cabeza.",
		COCONUT_HALVED = "Su pulpa está ya madura.",
		COFFEEBOT = "¡Hace el café de Patapalo!",
		CRATE = "Es una caja.",
		DEPLETED_BAMBOOTREE = "Se acabó.",
		DEPLETED_BUSH_VINE = "El arbusto necesita echarse un sueñecito.",
		DEPLETED_GRASS_WATER = "No volverá a crecer por un tiempo.",
		DOYDOYEGG_COOKED = "¡El aprendiz de ganso está cocinado!",
		DRAGOONHEART = "El corazón de la temible criatura.",
		DRAGOONSPIT = "¡Qué ordinario! ¡Tiene la aprobación de Patapalo!",
		DUG_BUSH_VINE = "Esto me lo llevo yo.",
		FRESHFRUITCREPES = "Sí, esto es comida.",
		FRUITMEDLEY = "Un bocado para chuparse los dedos.",
		GEARS = "Mis tuercas están girando.",
		GUANO = "¡Esto ha salido de la parte trasera de una bestia!",
		HOUNDFIRE = "¡Arde violentamente!",
		INVENTORYGRAVE = "¿Quién ha estado hurgando en mis islas?",
		INVENTORYMOUND = "¿Quién ha estado hurgando en mis islas?",
		KRAKEN = "¡Es la bestia más poderosa del mar!",
		KRAKENCHEST = "¡Sí, para esto vive Patapalo!",
		KRAKEN_TENTACLE = "¡No me toques!",
		MAGMAROCK_FULL = "¡Mi sentido del tesoro está a toda mecha!",
		MAGMAROCK_GOLD_FULL = "¡Mi sentido del tesoro está a toda mecha!",
		MONKEYBALL = "Inquietante.",
		MONSTERTARTARE = "Qué cosa más vil.",
		MUSSELBOUILLABAISE = "Esto es un manjar.",
		MYSTERYMEAT = "¡Sí, voy a comer bien esta noche!",
		OXHAT = "Es el sombrero del buey.",
		OX_FLUTE = "Una flauta para tocar una pequeña melodía.",
		OX_HORN = "Un cuerno de bestia temible.",
		PARROT_PIRATE = "¡Arrr! ¡Este es mi Polly!",
		PEACOCK = "¡Qué criatura tan bonita!",
		PEG_LEG = "Patapalo será mejor que la guarde para el futuro.",
		PIRATEGHOST = "Así es la vida de pirata, incluso en la muerte.",
		SANDBAGSMALL_ITEM = "¡Patapalo nunca arrastraría eso por tierra!",
		SHADOWSKITTISH_WATER = "¡Atrás, bestia!",
		SHIPWRECKED_ENTRANCE = "¡Ah del barco, grumetes!",
		SHIPWRECKED_EXIT = "¡Adiós, marineros de agua dulce!",
		SNAKESKINSAIL = "Es una vela.",
		SNAKE_FIRE = "Ah, qué criatura tan horrenda.",
		SPEAR_LAUNCHER = "¡Carga una lanza y a volar!",
		SWEETPOTATOSOUFFLE = "Un delicioso panecillo.",
		SWIMMINGHORROR = "¡A las profundidades!",
		TIGEREYE = "Me recuerda a mi viejo primer oficial, Ojosalvaje Weston.",
		TRINKET_20 = "¡Con esto atravesaré los mares!",
		TRINKET_21 = "¡Esto es un chiste comparado con los poderosos barcos!",
		TRINKET_22 = "¿Dónde está el vino?",
		TURF_FUNGUS_RED = "Yo no soy un marinero de agua dulce.",
		TURF_MAGMAFIELD = "Yo no soy un marinero de agua dulce.",
		TURF_TIDALMARSH = "Yo no soy un marinero de agua dulce.",
		VOLCANO_ALTAR_TOWER = "Esto es obra del diablo.",
		WATERYGRAVE = "El único fin adecuado para un hombre de mar.",
		WHALE_TRACK = "¡Ah del barco, ballena!",
		WILDBOREHEAD = "Deja de mirarme.",
		WOODLEGSSAIL = "¡Mi vela!",
		WOODLEGS_CAGE = "Qué cosa más horrible.",
		WOODLEGS_KEY1 = "Una cosa inútil donde las haya.",
		WOODLEGS_KEY2 = "Una cosa inútil donde las haya.",
		WOODLEGS_KEY3 = "Una cosa inútil donde las haya.",
		WRECK = "Descansa, navegante cansado.",
		CALIFORNIAROLL = "Unos deliciosos manjares de pescado.",

	},
	DESCRIBE_GENERIC = "Esto es... una cosa u otra.",
	DESCRIBE_SMOLDERING = "Es como prender un fuego.",
	DESCRIBE_TOODARK = "¡Esto está muy oscuro para espiar con el ojo!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "¡A mi barriga que vas!",
	},
}