return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "더 이상 작업이 필요 없거든.",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "아, 천천히. 깨었거든.",
			GENERIC = "아냐.",
			NOBITS = "내 일은 끝났거든.",
		},
		STORE =
		{
			GENERIC = "다 담고 있어.",
			NOTALLOWED = "쑤셔 넣을까. 망가질지도 모르는데.",
		},
		RUMMAGE =
		{	
			GENERIC = "하하, 아니야.",	
		},
        COOK =
        {
            GENERIC = "어, 아니야.",
            TOOFAR = "저기 가서 쓰면 돼... 아, 굶겠거든!",
        },
        GIVE =
        {
            DEAD = "불쌍한 놈이 죽었거든.",
            SLEEPING = "아. 자게 놔주자.",
            BUSY = "지금 다른 것을 하고 있거든.",
        },
        WRITE =
        {
            GENERIC = "아니. 하기 싫어.",
        },
        CHANGEIN =
        {
            GENERIC = "내 옷에 문제가 있어?",
            BURNING = "관둬야지.",
        },
		TEACH =
        {
            KNOWN = "이미 알거든?",
            CANTLEARN = "지루하거든.",
        },
	},
	ACTIONFAIL_GENERIC = "작동하지 않았거든.",
	ANNOUNCE_MAGIC_FAIL = "일 못 해. 나도 못 해! 하하.",
	ANNOUNCE_ACCOMPLISHMENT = "바빴거든.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "아, 완료했거든.",
	ANNOUNCE_ADVENTUREFAIL = "모든 것이 물거품이 되었거든.",
	ANNOUNCE_BEES = "좀 쉬어!",
	ANNOUNCE_BOAT_DAMAGED = "배가 손상을 받았거든!",
	ANNOUNCE_BOAT_SINKING = "물을 받아들이고 있거든.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "더 오래는 떠 있지 못할 거거든...",
	ANNOUNCE_BOOMERANG = "아! 자신을 그만 때리자!",
	ANNOUNCE_BURNT = "앗! 손가락을 태우거든!",
	ANNOUNCE_CANFIX = "\n수리해야겠거든. 아마 나중에.", 
	ANNOUNCE_CHARLIE = "누굴까?! 날 내버려 둬!",
	ANNOUNCE_CHARLIE_ATTACK = "윽! 가라니까!",
	ANNOUNCE_COLD = "너무 차갑거든!",
	ANNOUNCE_CRAB_ESCAPE = "여기였던 것 같거든...",
	ANNOUNCE_CRAFTING_FAIL = "하하. 정말 망쳤거든.",
	ANNOUNCE_DEERCLOPS = "큰 것이 오고 있거든!",
	ANNOUNCE_DUSK = "어둠이 곧 찾아오거든!",
	ANNOUNCE_EAT =
	{
		GENERIC = "나쁘지 않거든. 헤헤.",
		INVALID = "사양하겠거든.",
		PAINFUL = "혀가 이렇게 부어도 될까?",
		SPOILED = "우욱! 토하겠거든...",
		STALE = "음식이었거든, 전에는.",
		YUCKY = "하하, 아니.",
	},
	ANNOUNCE_ENTER_DARK = "정말 어두워! 도와 줘! 도와 줘!",
	ANNOUNCE_ENTER_LIGHT = "빛이거든! 너가 그리웠거든!",
	ANNOUNCE_FREEDOM = "만세, 자유거든! 낮잠 시간인가?",
	ANNOUNCE_HIGHRESEARCH = "우와, 내 정신이 확장된 느낌이거든!",
	ANNOUNCE_HOT = "열을 견딜 수 없거든.",
	ANNOUNCE_HOUNDS = "구린 개들이 오거든.",
	ANNOUNCE_HUNGRY = "약한 파도처럼 쓰러지고 있거든! 음식을 줘!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "근처에서 떨리는 것이 들리거든.",
	ANNOUNCE_HUNT_LOST_TRAIL = "윽, 도망갔거든.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "물이 자취를 없앴거든. 어쩔 수 없지.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "뭔가를 원하는 것 같거든. 야! 너 뭘 원하는 거야?",
	ANNOUNCE_INV_FULL = "내가 짐 드는 동물일까?",
	ANNOUNCE_KNOCKEDOUT = "우와. 무슨 일일까?",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "오늘은 아니거든, 자연아!",
	ANNOUNCE_LOWRESEARCH = "끝내줘! 지식이거든!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "음. 어디에 있지?",
	ANNOUNCE_MAPWRAP_RETURN = "안개가 걷히고 있거든!",
	ANNOUNCE_MAPWRAP_WARN = "안개가 낀 느낌이거든.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"어차피 독서는 지루하거든.",
	},
	ANNOUNCE_MORETREASURE = "내가 운이 좋거든!",
	ANNOUNCE_MOSQUITOS = "무례하거든! 자기 피는 자기가 만들어!",
	ANNOUNCE_NODANGERSIESTA = "지금 자는 것은 위험하거든.",
	ANNOUNCE_NODANGERSLEEP = "지금 자는 것은 위험하거든.",
	ANNOUNCE_NODAYSLEEP = "낮잠은 좋지만... 지금은 안 되거든.",
	ANNOUNCE_NODAYSLEEP_CAVE = "미쳤어? 난 동굴에 안 잘 거거든!",
	ANNOUNCE_NOHUNGERSIESTA = "먹을 것...",
	ANNOUNCE_NOHUNGERSLEEP = "먹을 것...",
	ANNOUNCE_NONIGHTSIESTA = "올바른 수면법이 아니거든.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "동굴에서는 시에스타를 즐길 수 없거든.",
	ANNOUNCE_NOSLEEPONFIRE = "윽... 지금 불타고 있거든.",
	ANNOUNCE_NO_TRAP = "최악의 함정이거든.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "이 근처가 아닌 것 같거든.",
	ANNOUNCE_OTHER_WORLD_PLANT = "할 수 없어. 여기서 자라지 않을 것이니까.",
	ANNOUNCE_PECKED = "야! 멈추라니까!",
	ANNOUNCE_QUAKE = "땅이 흔들거리거든.",
	ANNOUNCE_RESEARCH = "더 영리해진 느낌이거든.",
	ANNOUNCE_SHARX = "상어의 냄새가 나거든.",
	ANNOUNCE_SHELTER = "아. 악천후를 피해야 정신 차리거든.",
	ANNOUNCE_THORNS = "아! 날 물었거든!",
	ANNOUNCE_TOOL_SLIP = "너 때문에 더 재미있어지지는 않거든!",
	ANNOUNCE_TORCH_OUT = "빛이 어디로 갔을까?!",
	ANNOUNCE_TRAP_WENT_OFF = "내 잘못이거든.",
	ANNOUNCE_TRAWL_FULL = "일이 끝났거든!",
	ANNOUNCE_TREASURE = "이야! 보물이거든!",
	ANNOUNCE_UNIMPLEMENTED = "반쯤 된 것 같아.",
	ANNOUNCE_VOLCANO_ERUPT = "화산이 말하거든!",
	ANNOUNCE_WAVE_BOOST = "서프스 업!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "고래, 고래, 고래!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "더 깊게 파고 들어야 하거든.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "물이 너무 거칠거든.",
	ANNOUNCE_WORMHOLE = "...여긴 어디일까?",
	ANNOUNCE_DAMP = "좀 젖었다고 다치진 않거든.",
	ANNOUNCE_WET = "곧 몸을 말려야겠거든.",
	ANNOUNCE_WETTER = "옷이 다 졌었거든... 하하.",
	ANNOUNCE_SOAKED = "충분히 젖었거든.",
	BATTLECRY =
	{
		GENERIC = "난 세거든!",
		PIG = "파괴거든!",
		PREY = "넌 이길 수 없거든!",
		SPIDER = "넌 오늘을 후회할 거거든!",
		SPIDER_WARRIOR = "널 끝장낼 것이거든!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "네 표정을 봤어야 하는 건데.",
		PIG = "하하, 속였거든.",
		PREY = "아냐, 장난이거든.",
		SPIDER = "헤, 아냐, 안 싸워도 되거든.",
		SPIDER_WARRIOR = "하하, 아냐. 우린 괜찮아.",
	},
	DESCRIBE =
	{
		BERRYBUSH =
		{
			GENERIC = "How lush!",
			PICKED = "Thanks for the snack, dude.",
			WITHERED = "I can nurse it back to health.",
		},
		INVENTORYGRAVE = "짜식, 하늘의 큰 파도를 타거든.",
		INVENTORYMOUND = "큰 파도를 타고 하늘로 갈 거거든.",
		ACCOMPLISHMENT_SHRINE = "아주 바빠 보이거든.",
		ACORN =
		{
			GENERIC = "나와라, 자연!",
			PLANTED = "강하게 성장해, 작은 친구.",
		},
		ACORN_COOKED = "미안해, 나무 아기거든.",
		ADVENTURE_PORTAL = "내가 왜 거기에 가야 될까?",
		AERODYNAMICHAT = "공기역학. 좋거든.",
		AMULET = "보기 좋고, 느낌도 좋거든.", --Red
		ANCIENT_ALTAR = "오싹하게 만드는 것이거든.",
		ANCIENT_ALTAR_BROKEN = "아직도 작동할까?",
		ANCIENT_STATUE = "우울하게 만들거든.",
		ANIMAL_TRACK = "친구가 근처에 있거든.",
		ANTIVENOM = "이걸 쓰면 아픈 게 사라지거든.",
		ARMORDRAGONFLY = "이 갑옷이 지금 너무 인기거든.",
		ARMORGRASS = "그리 세지 않아 보이거든.",
		ARMORLIMESTONE = "*너무* 튼튼해 보이거든.",
		ARMORMARBLE = "이건 심하거든.",
		ARMOROBSIDIAN = "내 엉덩이를 찌르거든.",
		ARMORRUINS = "고급이거든!",
		ARMORSEASHELL = "대양이 나를 보호해줄 거거든!",
		ARMORSLURPER = "효율적이거든!",
		ARMORSNURTLESHELL = "자연으로 자연을 막는 것이거든.",
		ARMORWOOD = "공격자가 도끼가 없었으면 좋겠네.",
		ARMOR_LIFEJACKET = "파도가 거칠어지는 것을 대비하는 것이거든.",
		ARMOR_SANITY = "윽! 오싹하게 만드는 것이거든.",
		ARMOR_SNAKESKIN = "뱀이 나쁘지 않는 면도 있거든.",
		ARMOR_WINDBREAKER = "바람이 나를 피해 가거든!",
		ARMOUREDBOAT = "거추장스러워 보이는 보드거든.",
		ASH =
		{
			GENERIC = "파티를 놓친 것으로 보이거든.",
			REMAINS_EYE_BONE = "흠, 여행을 싫어한 것일까?",
			REMAINS_GLOMMERFLOWER = "흠, 여행을 싫어한 것일까?",
			REMAINS_THINGIE = "흠, 여행을 싫어한 것일까?",
		},
		AXE = "이것으로 나무를 자를 수 있겠지만... 사양이거든.",
		BABYBEEFALO = "성장하는 것은 덫이거든... 하지 마!",
		BABYOX = "윽, 넌 쓰레기 냄새가 나거든!",
		BACKPACK = "내 물건을 가지고 다니는 것이거든.",
		BACONEGGS = "미소를 지어봐!",
		BALLPHIN = "서핑 친구거든!",
		BAMBOO = "잘 뜰 것으로 보이거든.",
		BAMBOOTREE =
		{
			BURNT = "죽은 것 같거든.",
			CHOPPED = "빨리 자라라!",
			GENERIC = "자를 수 있겠거든.",
		},
		BANDAGE = "나 자신을 치료할 수 있거든!",
		BAT = "다른 데에서 퍼덕거리자!",
		BATBAT = "이 배트로 박쥐들을 칠 수 있을 것이거든.",
		BATWING = "이거 몇 개 더 있으며 날 수 있거든!",
		BATWING_COOKED = "가죽 같거든.",
		BEARDHAIR = "아마 누군가가 이것을 잃었거든.",
		BEARGER = "복잡하게 생각하지 않아도 돼.",
		BEARGERVEST = "진짜 곰오소리 가슴으로 만들었거든!",
		BEARGER_FUR = "이제 편하게 동면할 수 있거든.",
		BANANAPOP = "시원하게 만들어주는 가장 좋은 방법. 준비도 별로 필요 없거든!",
		BISQUE = "노력의 대가거든!",
		CEVICHE = "햇빛과 좋은 음식만 있으면 되거든.",
		SEAFOODGUMBO = "내가 좋아하는 거거든!",
		SURFNTURF = "서프보드에서 먹을 수 있을 거거든?",
		SHARKFINSOUP = "내 얼굴을 쳐박아도 될 것 같거든.",
		LOBSTERDINNER = "까재, 뭐가 널 먹는 것이지? 아, 나!",
		LOBSTERBISQUE = "고급스럽거든. 맛있거든.",
		JELLYOPOP = "정크푸드인가, 건강식품인가? 모르겠거든.",
		BEDROLL_FURRY = "더 편안한 낮잠 시간을 위한 것이거든!",
		BEDROLL_STRAW = "낮잠 시간용이거든!",
		BEE =
		{
			GENERIC = "너나 \"윙웅\"이거든!",
			HELD = "여기에 있는 것이 밖에 있는 것보다 안전하거든, 정말.",
		},
		BEEBOX =
		{
			BURNT = "벌들이 인테리어 디자인을 하는 것일까?",
			FULLHONEY = "달콤한 꿀을 만들었거든!",
			GENERIC = "벌들이 상자 안과 주변에 있거든.",
			NOHONEY = "벌 보고 일 열심히 하라고 하면 위선적일까?",
			SOMEHONEY = "벌들이 나를 위해 꿀을 만들었거든! 고마워!",
		},
		BEEFALO =
		{
			FOLLOWER = "날 사랑하는 것이거든!",
			GENERIC = "이것이 정말 좋거든!",
			NAKED = "아름다운 해변의 몸매거든.",
			SLEEPING = "밤의 공포를 모르고 자는 것이거든.",
		},
		BEEFALOHAT = "고기물소 냄새가 나거든.",
		BEEFALOWOOL = "머리카락 같아보이거든.",
		BEEHAT = "벌한테 쏘이는 걸 막거든.",
		BEEHIVE = "벌이 그 안에서 자거든.",
		BEEMINE = "콘페티 폭탄. 하지만 벌이 들어있거든.",
		BELL = "큰 괴물을 부르거든.",
		BELL_BLUEPRINT = "재앙의 레시피거든.",
		BERMUDATRIANGLE = "새로운 서핑 위치로 이동하자!",
		BERRIES = "먹을 수 있는 거지, 그렇지?",
		BERRIES_COOKED = "이제 끈적하거든. 헤헤, 징그럽거든.",
		BERRYBUSH =
		{
			BARREN = "약간의 사랑이 필요하거든.",
			GENERIC = "좋아! 베리가 달린 덤불이거든!",
			PICKED = "이제는 보통 덤불이거든.",
			WITHERED = "안 좋아보이는 덤불이거든.",
		},
		BIOLUMINESCENCE = "예쁘게 빛나는 덩어리거든!",
		BIRDCAGE =
		{
			GENERIC = "새 친구를 구해야겠거든.",
			OCCUPIED = "새 친구가 조용하길 바라거든.",
			SLEEPING = "새 친구가 아주 졸린 것 같거든.",
			HUNGRY = "새 친구의 배가 비었거든!",
			STARVING = "새 친구가 뼈만 남았거든!",
			DEAD = "새 친구가 마지막 숨을 거뒀거든...",
			SKELETON = "난 후회되는 게 많거든.",
		},
		BIRDTRAP = "이것으로 새를 잡을 수 있거든.",
		BIRD_EGG = "안에 작은 새가 있거든!",
		BIRD_EGG_COOKED = "...미안해, 새 친구.",
		BISHOP = "엉뚱한 생각하지 말자.",
		BLUBBER = "더 많이 있으며 어떤 조건에서도 서핑할 수 있을 텐데!",
		BLUBBERSUIT = "불쾌하지만 효과적이거든.",
		BOARDS = "이 보드로 서핑할 수는 없거든.",
		BOATCANNON = "Can't we find a peaceful solution?",
		BOATREPAIRKIT = "서프보드는 보수가 중요하거든!",
		BOAT_LANTERN = "밤의 서핑. 좋아하거든!",
		BOAT_TORCH = "밤의 서핑. 좋아하거든!",
		BOOMERANG = "무언가를 좋아한다면 그걸 놔야 한다고 하거든.",
		BOTTLELANTERN = "어둠을 물리치거든.",
		BURIEDTREASURE = "일한 보람이 있기를 바라거든.",
		BUSHHAT = "이것은 나를 자연과 하나로 만들어주거든.",
		BUSH_VINE =
		{
			BURNT = "이제 누구도 쓸 수 없거든.",
			CHOPPED = "그 덩굴은 내 것이거든.",
			GENERIC = "약간 엉킨 것 같거든.",
		},
		BUTTER = "하하. 미끄럽거든!",
		BUTTERFLY =
		{
			GENERIC = "아름다운 무늬거든.",
			HELD = "나의 예쁜 포켓 친구거든.",
		},
		BUTTERFLYMUFFIN = "예쁜 머핀이거든!",
		BUTTERFLYWINGS = "기분이 안 좋거든.",
		CAMPFIRE =
		{
			EMBERS = "불을 위한 연료가 필요하거든!",
			GENERIC = "아늑한 모닥불이거든!",
			HIGH = "어... 퍼지지 않길 바라거든.",
			LOW = "에너지가 필요한 것 같거든!",
			NORMAL = "아늑한 모닥불이거든!",
			OUT = "끝났거든.",
		},
		CANE = "지팡이거든.",
		CAPTAINHAT = "보스가 지금 날 볼 수 있다면.",
		CARGOBOAT = "주머니가 많은 서프보드거든.",
		CARROT = "오렌지에서 이름을 가져왔을 것이거든.",
		CARROT_COOKED = "냄새가 좋거든!",
		CARROT_PLANTED = "잘 발견했거든!",
		CARROT_SEEDS = "이것으로 당근을 키울 수 있거든.",
		CAVE_BANANA = "칼륨이거든!",
		CAVE_BANANA_COOKED = "요리한 포타슘이거든!",
		CHARCOAL = "타고 남은 것이거든.",
		CHESSJUNK1 = "잠재력이 많아 담겨 있거든!",
		CHESSJUNK2 = "이것으로 누군가가 무엇을 만들었으면 하거든.",
		CHESSJUNK3 = "조각들이 많거든.",
		CHESTER = "가장 좋은 친구는... 공짜로 일하는 친구거든.",
		CHESTER_EYEBONE =
		{
			GENERIC = "감시당하는 느낌이거든.",
			WAITING = "낮잠 시간이거든!",
		},
		CHIMINEA = "아름다운 불, 바람으로부터 지켜줄 거거든!",
		CLOTHSAIL = "바람과 함께 흘러가자.",
		COCONADE =
		{
			BURNING = "크게 터질 것이거든!",
			GENERIC = "가지고 있는 것만으로도 강력해진 느낌이거든.",
		},
		COCONUT = 
		{
		    GENERIC = "머리에 이것이 떨어지만 아프겠거든!",
		    PLANTED = "조그맣거든.",
		},
		COCONUT_COOKED = "흠. 그래. 요리가 됐거든.",
		COFFEE = "냄새가 좋거든!",
		COFFEEBEANS = "좋거든!",
		COFFEEBEANS_COOKED = "에너지거든!",
		COFFEEBUSH =
		 {
		 	BARREN = "안 돼, 커피가 필요하거든!",
		 	GENERIC = "커피거든!",
		 	PICKED = "빨리 다시 자라야 하거든!",
		 	WITHERED = "화산에서 자란다면...",
		 },
		COLDFIRE =
		{
			EMBERS = "나를 두고 가지마, 빛!",
			GENERIC = "이것을 어떻게 사용하는지 모르거든.",
			HIGH = "차갑거든.",
			LOW = "불이 게으름 피우고 있거든.",
			NORMAL = "불이 할 일을 하고 있거든.",
			OUT = "불이 휴식을 취하고 있거든.",
		},
		COLDFIREPIT =
		{
			EMBERS = "나를 두고 가지마, 빛!",
			GENERIC = "이것을 어떻게 사용하는지 모르거든.",
			HIGH = "차갑거든.",
			LOW = "불이 게으름 피우고 있거든.",
			NORMAL = "불이 할 일을 하고 있거든.",
			OUT = "불이 휴식을 취하고 있거든.",
		},
		COMPASS =
		{
			GENERIC = "이것을 어떻게 사용하는 것이었거든?",
			N = "북?",
			S = "남?",
			E = "동?",
			W = "서?",
			NE = "북동?",
			SE = "남동?",
			NW = "북서?",
			SW = "남서?",
		},
		COOKEDMEAT = "서핑 연료거든!",
		COOKEDMONSTERMEAT = "그래도 끔찍해 보이거든.",
		COOKEDSMALLMEAT = "맛있는 고기 조각이거든.",
		COOKPOT =
		{
			BURNT = "음식이 탄 맛이 날지도 모르거든.",
			COOKING_LONG = "보고 있으면 끓지 않을 거거든.",
			COOKING_SHORT = "음식이 오고 있거든!",
			DONE = "요리했거든. 냠!",
			EMPTY = "내 스타일 요리거든... 다 넣고 기다리는 거야!",
		},
		CORAL = "이것을 넣을 어항이 필요하거든!",
		CORALREEF = "예쁜 산호초거든.",
		CORAL_BRAIN = "근처에서 절망의 느낌이 들거든.",
		CORAL_BRAIN_ROCK = "멋진 산호 조각이거든.",
		CORN = "쓰윽.",
		CORN_COOKED = "곧 이쑤시개가 필요할 것이거든.",
		CORN_SEEDS = "이것으로 내 옥수수를 키울 수 있거든.",
		CRAB =
		{
			GENERIC = "서프보드에 타고 있었으면 널 잡을 수 있을 거거든.",
			HIDDEN = "달리다가 휴식을 취하고 있거든.",
		},
		CRABHOLE = "근사한 해변의 집이거든.",
		CUTGRASS = "걸으면 부스럭 소리가 나거든.",
		DEAD_SWORDFISH = "엇, 큰 물고기거든!",
		DEPLETED_GRASS =
		{
			GENERIC = "풀이 죽은 것 같거든.",
		},
		DEVTOOL = "유용하거든!",
		DIRTPILE = "어디 보자. 흙 무더기거든.",
		DIVININGROD =
		{
			COLD = "막대기가 반응이 없거든.",
			GENERIC = "웃기게 생긴 장치거든.",
			HOT = "막대기 막 흥분하고 있거든!",
			WARM = "막대기가 반응이 있거든!",
			WARMER = "엇, 막대기가 더 반응하고 있거든.",
		},
		DOUBLE_UMBRELLAHAT = "최소한 두 배는 건조하게 하거든.",
		DRAGONFRUIT_SEEDS = "이것으로 용과를 재배할 수 있거든.",
		DRAGONPIE = "맛있는 파이이거든!",
		DUBLOON = "운수 좋은 날이거든!",
		DUG_BAMBOOTREE = "이것을 심는 것은 어려운 일이거든.",
		DUG_BERRYBUSH = "이것을 심는 것은 어려운 일이거든.",
		DUG_COFFEEBUSH = "이것을 심는 것은 어려운 일이거든.",
		DUG_ELEPHANTCACTUS = "이것을 심는 것은 어려운 일이거든.",
		DUG_GRASS = "이것을 심는 것은 어려운 일이거든.",
		DUG_MARSH_BUSH = "이것을 심는 것은 어려운 일이거든.",
		DUG_SAPLING = "이것을 심는 것은 어려운 일이거든.",
		DURIAN = "먹기 꽤 어렵다고 하거든.",
		DURIAN_COOKED = "와! 나쁜 냄새거든!",
		DURIAN_SEEDS = "이것으로 냄새 나는 과일을 재배할 수 있거든.",
		EARMUFFSHAT = "부드럽게 내 귀를 따뜻하게 만들어주거든.",
		EARRING = "누군가 이것을 잃지 않았으면 좋겠거든...",
		EGGPLANT_SEEDS = "이것으로 가지를 키울 수 있거든.",
		ELEPHANTCACTUS = "멋있거든!",
		ELEPHANTCACTUS_ACTIVE = "앗!",
		ELEPHANTCACTUS_STUMP = "낮잠을 자고 있거든.",

		-----------------------------------------------------

		EVERGREEN =
		{
			BURNING = "쿨하지 않거든.",
			BURNT = "그 느낌 알거든.",
			CHOPPED = "썰고 잘랐거든.",
			GENERIC = "겨울을 생각나게 하거든. 우웩.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "쿨하지 않거든.",
			BURNT = "탔거든.",
			CHOPPED = "전성기 때 잘랐거든.",
			GENERIC = "다이어트 버전 같아.",
		},
		EYEBRELLAHAT = "나의 셋째 눈이 날 지켜 줄 것이거든.",
		EYEPLANT = "널 보게 만들었거든!",
		EYETURRET = "나를 주시하고 있거든.",
		EYETURRET_ITEM = "뒤에서 나를 보거든.",
		FABRIC = "막대가 어디에 있을까? 속았거든!",
		FARMPLOT =
		{
			BURNT = "토스트거든!",
			GENERIC = "내가 보기엔 육체노동 같거든.",
			GROWING = "유기농이길 바라거든.", --Earth is having a ground-child
			NEEDSFERTILIZER = "영양을 더해주면 좋거든.",
		},
		FEATHERFAN = "인위적인 대양의 산들바람이거든.",
		FEATHERHAT = "깃털 달린 친구와 하나가 되는 것이거든.",
		FEATHERSAIL = "매끄럽고 빠른 항해를 위한 것이거든!",
		FEATHER_CROW = "정말 부드럽거든.",
		FEATHER_ROBIN = "깃털의 색이 날 간지럽히거든.",
		FEATHER_ROBIN_WINTER = "A portable reminder of the beauty of nature.",
		FEM_PUPPET = "실망이거든.",
		FERTILIZER = "땅의 음식이거든.",
		FIREFLIES =
		{
			GENERIC = "마음에 드는 곤충이거든.",
			HELD = "나의 작게 빛나는 포켓 친구거든.",
		},
		FIREHOUND = "이건 더 화난 것 같거든.",
		FIREPIT =
		{
			EMBERS = "불이 지쳤거든.",
			GENERIC = "아, 어둠의 적이거든.",
			HIGH = "어엇! 뜨겁거든!",
			LOW = "일을 하고 있거든.",
			NORMAL = "더 좋거나... 더 나쁠 수 있거든.",
			OUT = "쉬고 있거든.",
		},
		FIRESTAFF = "뜨거운 물건이거든.",
		FIRESUPPRESSOR =
		{
			LOWFUEL = "연료가 필요하거든.",
			OFF = "꺼졌거든.",
			ON = "쓰자!",
		},
		FISHINGROD = "막대가 있으면 어디로든 갈 수 있거든.",
		FISHINHOLE = "점심 식사를 구하기 좋은 곳이거든.",
		FISHSTICKS = "물고기 막대거든.",
		FISHTACOS = "타코는 언제나 좋거든.",
		FISH_COOKED = "나의 개인 레시피거든.",
		FISH_MED = "미안하거든.",
		FISH_MED_COOKED = "간식 시간일까?",
		FISH_RAW = "불이 더 필요하거든.",
		FISH_RAW_SMALL = "큰 연못의 작은 물고기거든.",
		FISH_RAW_SMALL_COOKED = "간식 시간일까?",
		FLAMEGEYSER = "열기가 넘치거든.",
		FLINT = "이 돌은 구르지 않거든.",
		FLOTSAM = "아마도 내가 꺼낼 수 있거든.",
		FLOWER = "이걸 고를 때는 내가 까다롭거든. 헤헤헤.",
		FLOWERHAT = "행복해 보이는 모자거든!",
		FLOWERSALAD = "진짜 건강 식품이거든.",
		FLOWER_EVIL = "꽃이 이렇게 무서워서는 안 되거든.",
		FLUP = "짜식, 뚫어지게 쳐다보는 건 무례하거든!",
		FOLIAGE = "대자연이거든.",
		FOOTBALLHAT = "무엇이든 태클할 수 있을 것 같은 느낌이거든.",
		FRUITMEDLEY = "달콤한 간식이거든!",
		GASHAT = "악취로부터 보호해주거든.",
		GEARS = "로봇 내장 같거든.",
		GOLDENAXE = "보물 도구이거든.",
		GOLDENMACHETE = "근사한 스타일로 자르거든.",
		GOLDENPICKAXE = "좋은 것을 선택했거든.",
		GOLDENPITCHFORK = "반짝반짝 빛나면서 일할 수 있거든!",
		GOLDENSHOVEL = "고급 삽이 좋거든.",
		GOLDNUGGET = "빛나고 유용하거든!",
		GRASS =
		{
			BARREN = "도움이 있어야 자랄 수 있거든.",
			BURNING = "오래 가지 않거든.",
			GENERIC = "풀이 필요할 때가 있거든.",
			PICKED = "돌아올 것이거든.",
			WITHERED = "피곤해 보이는군.",
		},
		GRASS_UMBRELLA = "날 거의 젖지 않게 만들거든.",
		GREEN_CAP = "조금 맛있어 보이거든.",
		GREEN_CAP_COOKED = "구운 버섯이거든.",
		GREEN_MUSHROOM =
		{
			GENERIC = "멋진 버섯이거든.",
			INGROUND = "낮잠을 자고 있거든.",
			PICKED = "아마 배고픈 모양이거든.",
		},
		GUACAMOLE = "완벽한 간식이거든.",
		GUNPOWDER = "펑 터지거든.",
		HAIL_ICE = "하늘의 냉동고거든.",
		HAMBAT = "음식을 음식으로 싸울 수 있거든.",
		HAMMER = "부수는 것은 *일*같지만 재미있거든.",
		HAWAIIANSHIRT = "내 스타일의 셔츠거든.",
		HEALINGSALVE = "약간 살아날 수 있게 해주거든.",
		HEATROCK =
		{
			COLD = "얼음 같거든!",
			FROZEN = "신선하거든.",
			GENERIC = "돌의 온도거든.",
			HOT = "따뜻하고 빛나거든.",
			WARM = "약간 따뜻하거든.",
		},
		HOMESIGN =
		{
			BURNT = "그 느낌 알거든.",
			GENERIC = "행 텐!",
		},
		HONEY = "끈적하고, 달콤하고 맛있거든!",
		HOUND = "진짜 귀찮은 개거든!",
		ICEMAKER =
		{
			HIGH = "아주 잘 되거든.",
			LOW = "잘 안 되거든.",
			NORMAL = "되고 있거든.",
			OUT = "그만이거든.",
			VERYLOW = "거의 안 되거든.",
		},
		ICEPACK = "스낵을 쿨하게 유지하거든, 나만큼.",
		ICESTAFF = "잡기에는 너무 차갑거든.",
		INSANITYROCK =
		{
			ACTIVE = "앗. 머리가 아파지고 있거든.",
			INACTIVE = "어둠의 탑이거든.",
		},
		JAMMYPRESERVES = "잼을 잘 보관하자.",
		JELLYFISH = "맨발로 밟으면 안 되거든!!",
		JELLYFISH_COOKED = "속 안에서 안 쏘길 바라거든.",
		JELLYFISH_DEAD = "아직도 날 쏠지도 모르거든.",
		JELLYFISH_PLANTED = "너무 싫거든.",
		JELLYJERKY = "더 질겨 보이거든.",
		JUNGLETREE =
		{
			BURNING = "쿨하지 않거든.",
			BURNT = "그 느낌 알거든.",
			CHOPPED = "썰고 잘랐거든.",
			GENERIC = "자연의 캐노피 같은 것이거든.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "커서 나무가 되자.",
            PLANTED = "윽, 심느라 땀 나서 싫거든.",
        },
		KABOBS = "꼬챙이 고기거든!",
		KILLERBEE =
		{
			GENERIC = "성질이 나쁘거든.",
			HELD = "벌이 쉬어야 하거든.",
		},
		KNIGHTBOAT = "저주 받은 기사거든.",
		KRAMPUS = "훔치는 것은 좋지 않거든!",
		KRAMPUS_SACK = "훔친 물건이 든 가방이거든.",
		LANTERN = "무드를 밝게 하거든.",
		LAVAPOOL = "끈적한 모닥불 같거든!",
		LAVASPIT =
		{
			COOL = "모두 말랐거든.",
			HOT = "좀 매워 보이거든.",
		},
		LIGHTNING_ROD =
		{
			CHARGED = "에너지가 가득 찼거든!",
			GENERIC = "전력을 사용하거든.",
		},
		LIMESTONE = "단단한거든.",
		LIMPETROCK =
		{
			GENERIC = "따개비가 많거든.",
			PICKED = "먹을 것이 없거든.",
		},
		LIMPETS = "분주한 일상으로부터 자유롭거든.",
		LIMPETS_COOKED = "아직도 미끌거리거든.",
		LIVINGJUNGLETREE = "나무가 대단한 보드거든.",
		TREEGUARD = "보드가 되고 싶은 거거든?!",
		LIVINGLOG = "맹해 보이거든.",
		LOBSTER = "맛있는 바다 벌레거든.",
		LOBSTERHOLE = "언제까지나 기다릴 수 있거든.",
		LOBSTER_DEAD = "곧 훌륭한 음식이 될 것이거든.",
		LOBSTER_DEAD_COOKED = "좋은 요리거든!",
		LOG =
		{
			BURNING = "좋은 보드의 낭비거든.",
			GENERIC = "안에 보드가 있거든.",
		},
		LOGRAFT = "정말일까?",
		LUGGAGECHEST = "이 트렁크는 증기선이 생각 나거든.",
		LUREPLANT = "아주 매력적이거든.",
		LUREPLANTBULB = "쉽게 고기를 잡을 수 있거든.",
		MACHETE = "자르는 용도거든.",
		MAGMAROCK = "만지면 따뜻하거든.",
		MAGMAROCK_GOLD = "만지면 따뜻하거든.",
		MALE_PUPPET = "미안하거든.",
		MANDRAKE =
		{
			DEAD = "응원하고 있었거든.",
			GENERIC = "신비로운 식물이거든.",
			PICKED = "짜식, 시끄럽거든.",
		},
		MANDRAKESOUP = "신비한 수프거든.",
		MANDRAKE_COOKED = "생각보다 신비롭지 않거든.",
		MANGROVETREE = "이 나무가 정말 물을 좋아하거든.",
		MANGROVETREE_BURNT = "어떻게 된 걸까?",
		MARSH_BUSH =
		{
			BURNING = "스파이크가 타고 있거든. 좋거든.",
			GENERIC = "스파이크는 필요 없거든.",
			PICKED = "앗!",
		},
		MARSH_PLANT = "풀 같거든.",
		MARSH_PLANT_TROPICAL = "열대 식물이거든.",
		MARSH_TREE =
		{
			BURNING = "그렇게 뾰족한 불을 본 적이 없거든.",
			BURNT = "여전히 뾰족하거든.",
			CHOPPED = "이제 뾰족하지 않거든.",
			GENERIC = "나랑 스파이크는 친하지 않거든.",
		},
		MEAT = "5초 규칙이라는 것이 있거든!",
		MEATBALLS = "맛있거든.",
		MEATRACK =
		{
			BURNT = "육포 만드는 시절이 끝났거든.",
			DONE = "좋아 보이는 육포거든.",
			DRYING = "나중에 보자, 물.",
			DRYINGINRAIN = "물은 말리는 데 소용 없거든.",
			GENERIC = "이 걸이에 고기를 걸어야 하거든.",
		},
		MEAT_DRIED = "육포스러운 고기거든.",
		MERM = "머리를 물에 넣으면 좋겠거든.",
		MERMFISHER = "살기 위해 일하는 것을 게의치 않거든.",
		MERMHEAD =
		{
			BURNT = "탄 것이 더 좋거든.",
			GENERIC = "돼지 악취로도 모자라서.",
		},
		MERMHOUSE =
		{
			BURNT = "탄 집이거든.",
			GENERIC = "이것이 분명히 화장실인 줄 알았는데.",
		},
		MERMHOUSE_FISHER = "일꾼들이 쉬는 곳이거든.",
		MESSAGEBOTTLE = "메시지를 보내는 더 좋은 방법이 있을 것이거든...",
		MESSAGEBOTTLEEMPTY = "너와 함께 휘파람을 불 수 있거든.",
		MINERHAT = "절대로 하고 싶지 않은 일이거든.",
		MONSTERLASAGNA = "아직도 괴물 냄새가 나...",
		MONSTERMEAT = "이걸 먹을 정도로 배가 고플까?",
		MONSTERMEAT_DRIED = "씹기 어렵고 만들기도 어렵거든!",
		MOSQUITOSACK_YELLOW = "윽.",
		MOSQUITO_POISON = "꺼져!",
		MULTITOOL_AXE_PICKAXE = "도구를 고를 때는 까다롭거든.",
		MUSHTREE_MEDIUM = "중간 수준의 버섯이거든.",
		MUSHTREE_SMALL = "나무야, 성장하자! 버섯! 버섯!",
		MUSHTREE_TALL = "버섯나무가 크거든!",
		MUSSEL = "이런 거는 100개를 먹을 수 있거든.",
		MUSSEL_COOKED = "양파가 필요하거든.",
		MUSSEL_FARM =
		{
			GENERIC = "거기에 음식이 달려 있거든.",
			STICKPLANTED = "홍합아, 나오자.",
		},
		MUSSEL_STICK = "홍합이 질척하거든.",
		NIGHTLIGHT = "밤을 악몽으로 밝혀주거든.",
		NIGHTMAREFUEL = "악몽의 재료거든.",
		NIGHTSWORD = "어둠을 휘두르는 것이거든.",
		NITRE = "이상한 멍청한 돌이 아니거든.",
		OBSIDIAN = "아, 뜨겁거든!",
		OBSIDIANAXE = "내가 일해야 너가 일하는 것이거든...",
		OBSIDIANCOCONADE = "폭발을 조심하자!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "불이 지쳤거든.",
			GENERIC = "아, 어둠의 적이거든.",
			HIGH = "너무 밝거든!",
			LOW = "일을 하고 있거든.",
			NORMAL = "불이 계속 날뛰고 있거든.",
			OUT = "쉬고 있거든.",
		},
		OBSIDIANMACHETE = "이 칼은 뜨거우면서 쿨하거든.",
		OBSIDIANSPEARGUN = "너가 마음에 들거든.",
		OBSIDIAN_WORKBENCH = "불과 노는 용이지.",
		OCTOPUSCHEST = "보물이거든!",
		OCTOPUSKING = "넌 약해 보이거든.",
		ONEMANBAND = "신나게 연주해보자!",
		OX = "젖은 머리카락 냄새가 나거든.",
		PACKIM = "넌 입이 크거든.",
		PACKIM_FISHBONE = "가지고 있자.",
		PALMLEAF = "귀여운 스커트를 만들 수 있거든.",
		PALMLEAF_HUT = "실내지만 야외 같거든.",
		PALMLEAF_UMBRELLA = "나의 작은 야자나무거든.",
		PALMTREE =
		{
			BURNING = "쿨하지 않거든.",
			BURNT = "그 느낌 알거든.",
			CHOPPED = "썰고 잘랐거든.",
			GENERIC = "멋진 헤어 스타일이거든.",
		},
		PANFLUTE = "최면의 노래를 연주하거든.",
		PAPYRUS = "잘 타겠거든.",
		PARROT = "그만 꽥꽥 거리면 좋겠거든?",
		PEACOCK = "열대의 터키거든!",
		PEROGIES = "위안을 주는 음식이거든!",
		PETALS = "꽃은 나를 완전히 이해하거든.",
		PETALS_EVIL = "사악해 보이거든.",
		PICKAXE = "보는 것만으로도 허리가 아프거든.",
		PIGSKIN = "엉덩이 털은 싫거든.",
		PIRATEHAT = "망망대해를 위한 패션이거든.",
		PIRATEPACK = "등에 달린 약탈품이거든.",
		PIRATIHATITATOR =
		{
			BURNT = "불이 언제나 이기거든.",
			GENERIC = "바다의 비밀이 가득 들어있거든.",
		},
		PITCHFORK = "삼지창 같은 것이거든.",
		PLANTMEAT = "동시에 두 가지 식품군이거든.",
		PLANTMEAT_COOKED = "진짜 스테이크가 아니거든!",
		PLANT_NORMAL =
		{
			GENERIC = "농사는 어렵거든!",
			GROWING = "아직도 어리거든.",
			READY = "이제 먹을 수 있을까?",
			WITHERED = "무언가가... 끔찍하게 만들었거든.",
		},
		POISONHOLE = "웩!",
		POMEGRANATE = "씨 많거든.",
		POMEGRANATE_COOKED = "뜨겁고 즙이 많거든.",
		POMEGRANATE_SEEDS = "윽, 땅에 심어야 되는 것이거든...",
		POOP = "서프 하수도!",
		PORTAL_SHIPWRECKED = "이것이 어떤 작용이 있을까...",
		POWCAKE = "뭐든 먹을 거거든.",
		PRIMEAPE = "해변의 말썽꾸러기거든.",
		PRIMEAPEBARREL = "근사한 집이거든...",
		PURPLEAMULET = "나를 미치게 만들거든!",
		PURPLEGEM = "반짝이거든!",
		---------------------------------------------------------

		RAFT = "최악의 서핑보드거든.",
		RAINOMETER =
		{
			BURNT = "이것은 예상 못했거든.",
			GENERIC = "언제 패들을 써야 할지 알려주거든.",
		},
		RATATOUILLE = "괴혈병이 걸리기 싫으면 먹어야겠거든.",
		RAZOR = "내 다리 근처에 오지 말라고 했거든!",
		REDBARREL = "이것을 배에 실어야 하는 것일까?",
		REDGEM = "아름다운 보물!",
		RED_CAP_COOKED = "그 정도로 배고프지 않거든.",
		REEDS =
		{
			BURNING = "와. 심각하거든.",
			GENERIC = "더 많은 풀이거든.",
			PICKED = "나중에 보자.",
		},
		REFLECTIVEVEST = "태양 숭배자도 휴식이 필요하거든.",
		RESEARCHLAB =
		{
			BURNT = "윽, 널 다시 만들어야 할까?",
			GENERIC = "대신 모든 일을 하는 기계면 좋겠거든.",
		},
		RESEARCHLAB2 =
		{
			BURNT = "윽, 널 다시 만들어야 하나?",
			GENERIC = "내가 일 다하는 것 같거든.",
		},
		RESEARCHLAB3 =
		{
			BURNT = "스스로 타지 않게 방지할 수 있지 않았을까?",
			GENERIC = "그림자를 조종하는 것은 어려운 것 같거든. 내가 안 해도 되니까 다행이거든.",
		},
		RESURRECTIONSTATUE =
		{
			BURNT = "탔거든...",
			GENERIC = "작동되길 바라거든.",
		},
		RESURRECTIONSTONE = "이상한 나무 짜식, 너가 필요 없길 바라거든...",
		ROCK = "땅에 있을 때가 더 좋거든.",
		ROCKS = "평평하지 않으니까 물에 튕기지 않거든.",
		ROCK_LIGHT =
		{
			GENERIC = "근사하거든!",
			LOW = "용암이 차가워지고 있는걸.",
			NORMAL = "근사하거든!",
			OUT = "불이 꺼졌거든.",
		},
		ROPE = "지루한 것이 좋거든.",
		ROTTENEGG = "선실 냄새가 나거든.",
		ROWBOAT = "엇, 노젓기? 싫거든.",
		RUINSHAT = "여왕에게 어울리는 것이든!",
		RUINS_BAT = "소개해주고 싶은 것들이 있거든.",
		SAIL = "바람으로 가는 배의 가장 친한 친구거든.",
		SAND = "발가락 사이의 느낌이 좋거든.",
		SANDBAG = "들기 무겁거든...",
		SANDBAGSMALL = "들기 무겁거든...",
		SANDBAG_ITEM = "들기 무겁거든...",
		SANDHILL = "이것이 더 컸으면 샌드보드를 탈 수 있었을 것이거든.",
		SAND_CASTLE =
		{
			GENERIC = "다시 아이가 된 것 같거든!",
			SAND = "발가락 사이의 느낌이 좋거든.",
		},
		SAPLING =
		{
			BURNING = "태울 것이 없거든.",
			GENERIC = "보드 재료?",
			PICKED = "누들 같거든.",
			WITHERED = "나의 느낌을 그대로 재현하거든.",
		},
		SEAGULL = "똥새거든!",
		SEAGULL_WATER = "윽, 새 엉덩이가 내 파도에 닿고 있거든...",
		SEASACK = "물컹하군.",
		SEASHELL = "똑같은 것이 없어. 저 둘 빼고. 아... 그리고 저것.",
		SEASHELL_BEACHED = "바다의 선물이거든.",
		SEATRAP = "까재가 들어가서 식사가 나오거든.",
		SEAWEED = "이름이 모든 걸 말해주거든.",
		SEAWEED_COOKED = "조금 더 낫거든...",
		SEAWEED_DRIED = "바삭하면 좀 더 맛있거든.",
		SEAWEED_PLANTED = "보드에 걸리는 것이거든.",
		SEEDS = "윽, 내가 이걸 심어야 할까?",
		SEEDS_COOKED = "이 사이에 끼거든.",
		SEWING_KIT = "나는 \"바느질\"하는 타입이 아니거든.",
		SHARKITTEN = "넌 최악의 악몽치고는 귀엽거든.",
		SHARK_FIN = "내가 원하는 유일한 지느러미거든.",
		SHARK_GILLS = "필요 없겠지.",
		SHARK_TEETHHAT = "머리에 쓰는 것이 이상하거든...",
		SHARX = "가! 가! 가!",
		SHOVEL = "아, 파는 느낌이거든...",
		SIESTAHUT =
		{
			BURNT = "명복을 빌거든.",
			GENERIC = "낮잠을 자면 좋겠거든.",
		},
		SILK = "거미 오물이거든...",
		SKELETON = "초월의 영역에서 서핑하는 거거든...",
		SKELETON_PLAYER = "초월의 영역에서 서핑하는 거거든...",
		SKULLCHEST = "나랑 어울리는 것이거든.",
		SLOTMACHINE = "운을 시험해볼까?",
		SMALLBIRD =
		{
			GENERIC = "너가 보이거든.",
			HUNGRY = "네 배가 네 눈처럼 크길 바라거든.",
			STARVING = "배고프면 눈을 두 번 깜박거려.",
		},
		SMALLMEAT = "고기야!",
		SMALLMEAT_DRIED = "여행할 때 좋은 간식이거든.",
		SNAKE = "수영할 줄 모르길 바라거든.",
		SNAKEOIL = "난 어제 태어나지 않았거든.",
		SNAKESKIN = "이것으로 비늘 달린 비키니를 만들 수 있거든!",
		SNAKESKINHAT = "모자에 계속 비가 내리거든.",
		SNAKE_POISON = "이 친구가 물면 아프거든!",
		SOLOFISH = "내 슬리퍼를 가져오면 좋겠거든.",
		SPEAR = "찌를 때 필요하거든.",
		SPEARGUN = "조준. 발사.",
		SPEARGUN_POISON = "아주 전염성이 강하거든.",
		SPEAR_OBSIDIAN = "준비, 조준, 발사거든.",
		SPEAR_POISON = "아프게 만들어줄것이거든?",
		SPIDER =
		{
			DEAD = "지금 비가 내릴까?",
			GENERIC = "기어다니는 징그러운 것이거든.",
			SLEEPING = "아, 평온하고 징그럽거든.",
		},
		SPIDERDEN = "불법침입자 같지 않거든.",
		SPIDEREGGSACK = "거미 농장을 시작하는 것이거든.",
		SPIDERGLAND = "왜 건강식품은 맛이 역할까?",
		SPIDERHAT = "하하! 내가 네 보스거든, 이제!",
		SPIDERQUEEN = "나는 왕족에게 절하지 않거든.",
		SPIDER_WARRIOR =
		{
			DEAD = "이제 평화롭게 쉴 수 있겠거든.",
			GENERIC = "저리 가, 벌레야!",
			SLEEPING = "악몽을 꾸길 바라거든.",
		},
		SPOILED_FISH = "구역질 나게 만들거든!",
		SPOILED_FOOD = "낭비거든.",
		STINGER = "내 피부에서 이걸 뜯어내지 않아서 다행이거든.",
		STRAWHAT = "얼굴에 주근깨가 생기는 것을 방지하거든.",
		STUFFEDEGGPLANT = "건강식이거든.",
		STUNGRAY = "상어 방귀보다 악취가 심하거든...",
		SUNKBOAT = "서프보드는 가라앉지 않거든!",
		SUNKEN_BOAT =
		{
			ABANDONED = "서프보드는 가라앉지 않거든!",
			GENERIC = "서프보드는 가라앉지 않거든!",
		},
		SUPERTELESCOPE = "정말 멀리 볼 수 있거든!!",
		SURFBOARD = "너에 대한 사랑은 바다보다 깊으니까.",
		SURFBOARD_ITEM = "나의 긍지이자 기쁨이거든!",
		SWEET_POTATO = "디저트거든!",
		SWEET_POTATO_COOKED = "그리 달지 않거든...",
		SWEET_POTATO_PLANTED = "땅에서 디저트가 자라거든!",
		SWEET_POTATO_SEEDS = "음, 이것을 심어야 할까?",
		SWORDFISH = "싸움보다는 사랑이 더 좋거든.",
		TAFFY = "이것으로 보드에 왁스 칠을 할 수 있을까.",
		TALLBIRD = "날 수 없다는 것이 다행이거든.",
		TALLBIRDEGG = "안에서 작은 것이 쉬고 있거든.",
		TALLBIRDEGG_COOKED = "거대한 토스트가 있으면 좋겠거든.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "젤라틴 같거든...",
			GENERIC = "생생하거든...",
			HOT = "완숙이 아니길 바라거든.",
			LONG = "커지고 있거든...",
			SHORT = "빨리 나오자.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "미래의 성가신 존재거든.",
			PICKED = "알이 우리를 떠났거든.",
		},
		TEENBIRD =
		{
			GENERIC = "깃털 아래에 여드름이 더 많거든. 하하, 징그럽거든.",
			HUNGRY = "언제나 배고파 해!",
			STARVING = "나를 완전히 굶길려는 거거든!",
		},
		TELEPORTATO_SW_BASE = "힘이 느껴져...",
		TELEPORTATO_SW_BOX = "이것은 다른 것에 연결되거든?",
		TELEPORTATO_SW_CRANK = "빗자루가 아니길 바래, 쓰는 것이 싫어하거든.",
		TELEPORTATO_SW_POTATO = "대단하거든...",
		TELEPORTATO_SW_RING = "훌라후프 하는 데 어울리는 것 같지 않거든...",
		TELESCOPE = "이제 섬이 숨을 수 없거든!",
		TENT =
		{
			BURNT = "뭐야! 안 좋거든...",
			GENERIC = "잘 수 있는 서늘하고 건조한 곳이거든.",
		},
		THATCHPACK = "내 주머니가 찼을 때 필요하거든.",
		TIDALPOOL = "얼마나 깊이 들어갈까...",
		TIDAL_PLANT = "어디에서든 자랄 수 있는 것이거든...",
		TIGERSHARK = "절대로 보통 상어 때문에 불평하지 않을 것이거든!",
		TOPHAT = "내 스타일이 아니거든...",
		TORCH = "밤을 위한 것이거든!",
		TOUCAN = "그런 코로는 파도도 잡을 수 있거든!",
		TRAILMIX = "단백질이거든!",
		TRANSISTOR = "과학적인 것을 하는 것이거든!",
		TRAP = "해변의 아침 식사를 잡자!",
		TRAP_TEETH = "아, 끔찍해 보이거든!",
		TRAP_TEETH_MAXWELL = "피해야 되거든...",
		TRAWLNET = "약탈과 크루징이거든.",
		TRAWLNETDROPPED =
		{
			GENERIC = "바다의 전리품이거든!",
			SOON = "약간 더 어망을 치고...",
			SOONISH = "무엇을 잡아올릴까...",
		},
		TREASURECHEST =
		{
			BURNT = "안 되거든! 반짝이는 보물, 잘 가...",
			GENERIC = "보물이거든!",
		},
		TREASURECHEST_TRAP = "요상한 보물이거든!",
		TRIDENT = "무슨 신이 된 것 같거든!",
		TRINKET_1 = "추하거든.",
		TRINKET_10 = "와아프아웃을 제대로 하면 이것이 필요할지도 모르거든.",
		TRINKET_11 = "작은 아이야. 나와 함께 갈까?",
		TRINKET_12 = "이게 뭘까?",
		TRINKET_13 = "쾅 내려칠 수 있는 소다거든!",
		TRINKET_14 = "핀이 있으면 하거든...",
		TRINKET_15 = "근사한 우쿨렐레거든!",
		TRINKET_16 = "이상하게 생긴 접시거든...",
		TRINKET_17 = "너무 크거든...",
		TRINKET_18 = "옛날 장인의 실력이거든.",
		TRINKET_19 = "나는 허브만 쓰거든...",
		TRINKET_2 = "오, 하지만 난 진짜 카주가 좋거든...",
		TRINKET_23 = "이것이 무엇인지 알아내기엔 너무 복잡하거든...",
		TRINKET_3 = "고르드만 이것의 용도를 알거든.",
		TRINKET_4 = "으스스하게 고마운 지령이거든.",
		TRINKET_5 = "쓩!",
		TRINKET_6 = "젖은 손으로 만지고 싶지 않거든...",
		TRINKET_7 = "아, 내가 잘 하는 것이거든!",
		TRINKET_8 = "무엇이 경화되었을까?",
		TRINKET_9 = "짝이 안 맞아도 상관 없거든.",
		TROPICALFAN = "달콤한 휴식이거든.",
		TROPICAL_FISH = "색이 맛있어 보이거든!",
		TRUNKVEST_SUMMER = "피부를 숨쉬게 하거든.",
		TUNACAN = "와! 안 상하거든!",
		TURBINE_BLADES = "꼬여 있거든!",
		TURF_ASH = "재거든...",
		TURF_BEACH = "해변을 옮길 수 있거든.",
		TURF_CARPETFLOOR = "발가락으로 주먹 모양을 만들거든.",
		TURF_JUNGLE = "옹이졌거든.",
		TURF_MARSH = "점액성이거든...",
		TURF_MEADOW = "발 밑의 느낌이 좋거든.",
		TURF_MUD = "철벅거리거든.",
		TURF_SINKHOLE = "가라앉는 느낌이 들거든.",
		TURF_UNDERROCK = "우두둑이거든.",
		TURKEYDINNER = "고마운 것이거든.",
		TWIGS = "아주 유용하거든.",
		UMBRELLA = "날씨를 물리치거든!",
		UNAGI = "10마리 더!",
		VENOMGLAND = "끔찍한 분비 기관이거든.",
		VINE = "채찍질하기에 좋거든.",
		VOLCANO = "근사한 산이거든!",
		VOLCANOSTAFF = "이제 내가 화산의 보스거든!",
		VOLCANO_ALTAR =
		{
			GENERIC = "화산이 가격을 묻거든...",
			OPEN = "받을 준비가 되었거든...",
		},
		VOLCANO_ALTAR_BROKEN = "더 이상 아이템을 받지 않을 것이거든.",
		VOLCANO_EXIT = "퇴장할 시간이거든.",
		WAFFLES = "브런치거든!",
		WALLYINTRO_DEBRIS = "배의 파편...",
		WALL_HAY =
		{
			BURNT = "놀랍지 않거든... 건초로 만들었거든...",
			GENERIC = "벽이 없는 것보단 낫거든...",
		},
		WALL_HAY_ITEM = "벽이 없는 것보단 낫거든...",
		WALL_LIMESTONE = "이게 진짜 벽이거든!",
		WALL_LIMESTONE_ITEM = "이게 진짜 벽이거든!",
		WALL_RUINS = "왜 벽으로 세계를 막은 거야?",
		WALL_RUINS_ITEM = "이것으로 벽을 만들 수 있지 귀찮잖아?",
		WALL_STONE = "강해 보이거든...",
		WALL_STONE_ITEM = "강해 보이거든...",
		WALL_WOOD =
		{
			BURNT = "어차피 나무였거든...",
			GENERIC = "나무 벽이 지켜주거든.",
		},
		WALL_WOOD_ITEM = "나무 벽이 지켜주거든.",
		WASPHIVE = "최악의 벌통이거든!",
		WATERMELON = "뜨거운 날보다 더 좋은 것은 없거든!",
		WATERMELONHAT = "수박 비키니 다음으로 좋은 것이거든.",
		WATERMELONICLE = "녹기 전에 먹어야 하거든!",
		WATERMELON_COOKED = "뜨거운 수박이거든....",
		WATERMELON_SEEDS = "수박은 좋지만... 농장 일은 싫거든...",
		WEBBERSKULL = "평범한 해골이 아니거든.",
		WETGOOP = "마른 점액도 있을까?",
		WHALE_BLUE = "왜 우울할까?",
		WHALE_BUBBLES = "뭔가 아래에 있거든...",
		WHALE_CARCASS_BLUE = "더 이상 슬플 필요 없거든...",
		WHALE_CARCASS_WHITE = "복수는 나의 것이거든.",
		WHALE_WHITE = "검은 피를 뿌리고 지느러미를 밖으로 드러낼까?",
		WILDBORE = "기분 좋지 않거든.",
		WILDBOREHOUSE = "돼지가 집에 살거든? 대단하거든!",
		VOLCANO_SHRUB = "손에서 묻어나거든.",
		ROCK_OBSIDIAN = "널 여는 것이 너무 어렵거든...",
		ROCK_CHARCOAL = "탔지만, 좋거든!",
		DRAGOONDEN = "일? 뭐 하러 해.",

		ABIGAIL = "잘 지내자, 유령 친구.",
		ARMORCACTUS = "이걸 입으면 어떻게 나무를 포옹할까?",
		BASALT = "강하고 조용한 타입이거든.",
		BEEMINE_MAXWELL = "어쩔 때는 윙윙 소리에 맞추어 춤을 추거든.",
		BIGFISHINGROD = "낚시 하기 좋은 곳을 찾고 싶거든.",
		BIGFOOT = "웃긴 발을 가진 괴물이거든!",
		BIRCHNUTDRAKE = "흥분하지 말자.",
		BISHOP_NIGHTMARE = "그래서 보드 게임을 안 하는 것이거든!",
		BLOWDART_FIRE = "아무도 보고 있지 않을 때 빠르게 불을 피우는 방법이거든.",
		BLOWDART_FLUP = "맞으면 젖은 소리를 내거든.",
		BLOWDART_PIPE = "이걸로 누군가를 쏴야 할까?",
		BLOWDART_POISON = "파티 트릭으로서 좋지 않거든. 내가 어렵게 배웠거든.",
		BLOWDART_SLEEP = "(어쩔 때는 낮잠 자기 위해서 쓰거든.)",
		BLUEAMULET = "몸이 너무 뜨거워질 때 착용하면 좋거든.",
		BLUEGEM = "대양의 색이거든!",
		BLUEPRINT = "보는 것만으로도 머리를 아프게 하거든.",
		BLUE_CAP = "버섯이 파란색도 있는 줄은 몰랐거든.",
		BLUE_CAP_COOKED = "잘 한 것일까, 못 한 것일까?",
		BLUE_MUSHROOM =
		{
			GENERIC = "요리하든 생이든, 이걸 잔뜩 먹을 수 있거든.",
			INGROUND = "낮에 자는 걸 원하거든. 나처럼!",
			PICKED = "쉴 시간이 필요하거든.",
		},
		BOAT = "두 번째로 좋은 여행 방법이거든.",
		BOATCANNON = "물에 쏘면 멋진 파도가 생기거든.",
		BONESHARD = "이제는 캐스트하는 것이 도움될 것 같진 않거든.",
		BONESTEW = "푸짐한 식사로 보이거든.",
		BRAINJELLYHAT = "정신을 빼놓거든!",
		BUGNET = "나비를 잡으며 오후를 보낼 수 있거든.",
		BUNNYMAN = "껴안기 잘 할까?",
		BUOY = "그냥 잘 있거든.",
		BUZZARD = "아직 안 죽었거든, 친구!",
		CACTUS =
		{
			GENERIC = "그냥 두면 괜찮거든.",
			PICKED = "앗! 찔렸거든.",
		},
		CACTUS_FLOWER = "정말 아름답거든?",
		CACTUS_MEAT = "선인장 살코기... 채식주의자일까?",
		CACTUS_MEAT_COOKED = "이제 꽤 맛있어 보이거든.",
		CATCOON = "아주 독립적이고 쓰레기를 좋아하거든. 나처럼!",
		CATCOONDEN =
		{
			EMPTY = "누가 있을까?",
			GENERIC = "지내기 좋은 곳이거든.",
		},
		CATCOONHAT = "이 너괭이의 영혼이 느껴지거든.",
		CAVE_BANANA_TREE = "진짜 바나나가 아니거든!",
		CAVE_ENTRANCE =
		{
			GENERIC = "얼마나 노력해야 안으로 들어갈 수 있을까?",
			OPEN = "언제나 동굴 탐험을 하고 싶었거든.",
		},
		CAVE_EXIT = "나가자!",
		CAVE_FERN = "여기서도 자연이 살아남고 있거든.",
		COCONUT_HALVED = "하나의 가격으로 두 개를 갖고 싶은 것이거든. 훗.",
		COFFEEBOT = "커피 마시면 좋겠거든.",
		COOKEDMANDRAKE = "이제 먹으면 되겠거든.",
		COONTAIL = "멋진 모자가 될 수 있거든.",
		CRATE = "안에 뭐가 있을까.",
		CROW =
		{
			GENERIC = "캇!",
			HELD = "이제 가장 친한 친구가 된 것일까?",
		},
		CUTLASS = "이것을 잡은지 꽤 됐거든.",
		CUTLICHEN = "이제 먹을 것을 구할 수 있을까?",
		CUTREEDS = "자르는 것이 어려웠거든. 그럼 낮잠 잘 시간!",
		CUTSTONE = "지금 뭔가 만들 필요는 없지?",
		DEADLYFEAST = "내 배가 견딜 수 없거든!",
		DECIDUOUSTREE =
		{
			BURNING = "무의미하거든.",
			BURNT = "미안하다고 해도 돌아오지 않거든.",
			CHOPPED = "통나무 고맙거든. 네 몸에 대해선 미안하거든.",
			GENERIC = "다양한 색이 있거든!",
			POISON = "미안하다고 했거든!",
		},
		DEERCLOPS = "앗! 이제 임팩트 존에 왔거든!",
		DEERCLOPS_EYEBALL = "아. 보스가 생각나게 하거든.",
		DEPLETED_BAMBOOTREE = "지금은 없거든.",
		DEPLETED_BUSH_VINE = "더 이상 없거든.",
		DEPLETED_GRASS_WATER = "그뿐이었거든.",
		DEVTOOL_NODEV = "이걸 사용할 수 없거든.",
		DIVININGRODBASE =
		{
			GENERIC = "저것이 무엇일까?",
			READY = "열쇠를 원하는 것일까?",
			UNLOCKED = "돌아갈까?",
		},
		DIVININGRODSTART = "멋진 걸 찾고 싶거든!",
		DOYDOY = "안녕, 작은 친구야.",
		DOYDOYBABY = "귀여워! 안아줄까!",
		DOYDOYEGG = "도이도이일 수 있거든. 아니면 저녁 식사이거나.",
		DOYDOYEGG_COOKED = "위험을 맛볼 수 있거든.",
		DOYDOYEGG_CRACKED = "내가 안 만졌거든, 정말이야.",
		DOYDOYFEATHER = "감촉이 부드럽거든.",
		DOYDOYNEST = "낮잠 자는 데 최고거든. 도이도이한테는.",
		DRAGONFLY = "대양에서는 이런 것과 상대할 필요가 없거든!",
		DRAGONFLYCHEST = "뭐지?!",
		DRAGONFRUIT = "데카당스하고 장식적이거든!",
		DRAGONFRUIT_COOKED = "꽤 맛있거든.",
		DRAGON_SCALES = "이것이 즉시 잔뜩 필요하거든.",
		DRAGOON = "어, 그만 하자.",
		DRAGOONEGG = "핥은 적이 있거든. 그래서 혀를 대었거든.",
		DRAGOONHEART = "사랑하고 있었나 봐. 아직도 무척 뜨겁거든.",
		DRAGOONSPIT = "내 동생도 같은 짓을 했거든.",
		DRUMSTICK = "나를 위해 요리해줄 사람 있을까?",
		DRUMSTICK_COOKED = "전사 같거든.",
		DUG_BUSH_VINE = "정말 다시 심어야 할까?",
		EEL = "눈을 가늘게 뜨면 약간 귀엽거든.",
		EEL_COOKED = "장어는 먹기 싫거든!",
		EGGPLANT = "자주색 알은 본 적이 없거든.",
		EGGPLANT_COOKED = "오믈렛인가?",
		FEATHER_ROBIN_WINTER = "이것으로 만든 목걸이가 있으면 좋겠거든.",
		FISH = "요리조리 움직이거든.",
		FLOWER_CAVE = "화환을 만들 수 있을 정도로 필요하거든!",
		FLOWER_CAVE_DOUBLE = "화환을 만들 수 있을 정도로 필요하거든!",
		FLOWER_CAVE_TRIPLE = "화환을 만들 수 있을 정도로 필요하거든!",
		FRESHFRUITCREPES = "최고거든!",
		FROG =
		{
			DEAD = "이 나쁜 세상에 어울리지 않았거든.",
			GENERIC = "혀 내밀지 마.",
			SLEEPING = "좋은 꿈을 꿀까.",
		},
		FROGGLEBUNWICH = "나쁘지 않는 오후의 간식이거든.",
		FROGLEGS = "만지는 것이 정말 싫거든.",
		FROGLEGS_COOKED = "도이도이 같은 맛이거든.",
		FROG_POISON = "그냥 두는 것이 좋거든.",
		GEMSOCKET =
		{
			GEMS = "여기에 돌을 넣으라고 하는 것이거든.",
			VALID = "좋거든!",
		},
		GHOST = "이제 넌 쉴 자격이 있거든.",
		GLOMMER = "친구로 보이거든.",
		GLOMMERFLOWER =
		{
			DEAD = "불쌍하거든.",
			GENERIC = "머리카락에 넣으면 멋있지 않을까?",
		},
		GLOMMERFUEL = "유용하게 쓰자.",
		GLOMMERWINGS = "한숨. 더 이상 날지 말자.",
		GOATMILK = "목을 타고 내려갈 때 간지럽거든.",
		GOOSE_FEATHER = "부드럽지만... 지저분하거든.",
		GRASS_WATER = "풀이 수분 공급이 잘 되었거든!",
		GREENAMULET = "이 목걸이가 창조력이 가득하거든. 느껴지거든.",
		GREENGEM = "자연의 색이거든!",
		GREENSTAFF = "이 지팡이는 파괴만 하거든.",
		GUANO = "배틸리스크 똥이거든.",
		HOME = "낮잠 시간일까?",
		HONEYCOMB = "달고 벌 아기가 많이 들어있거든.",
		HONEYHAM = "특별한 경우일까?",
		HONEYNUGGETS = "누워서 이것을 먹을 것이거든.",
		HORN = "큰 동물 뿔이거든.",
		HOTCHILI = "앗! 혀를 태우는 것 같거든.",
		HOUNDBONE = "뼈가 잔뜩 있거든. 마음 편하게 해주는 것일까.",
		HOUNDFIRE = "뜨겁거든! 아주 뜨겁거든!",
		HOUNDMOUND = "위험한 강아지들이 근처에 있는 것 같거든.",
		HOUNDSTOOTH = "정기적인 치아 검사의 중요성을 부각하거든.",
		ICE = "쿨하게 지낼 줄 알거든.",
		ICEBOX = "차갑게 유지하면 더 좋거든.",
		ICECREAM = "뜨거운 날 해먹에 누워서 먹으면 좋거든.",
		ICEHAT = "머리를 차갑고 젖게 만들어주거든.",
		ICEHOUND = "차가운 개거든.",
		IRONWIND = "어... 난 보드에 집중하겠거든.",
		KNIGHT = "낮잠을 자면 될 것 같거든.",
		KNIGHT_NIGHTMARE = "자야지... 그리고 깨어나지 말아야지.",
		KOALEFANT_SUMMER = "잘 달라 붙어있거든.",
		KOALEFANT_WINTER = "겨울 동물이 잘 달라 붙어있거든.",
		KRAKEN = "서프스 업!",
		KRAKENCHEST = "보물이 기다리고 있거든!",
		KRAKEN_TENTACLE = "너무 물렁하거든!",
		LEIF = "꺼져, 회색 배!",
		LEIF_SPARSE = "꺼져, 회색 배!",
		LICHEN = "이 이끼는 나를 슬프게 하거든.",
		LIGHTBULB = "원래 밝거든. 나처럼!",
		LIGHTNINGGOAT =
		{
			CHARGED = "위엄이 있거든!",
			GENERIC = "내가 껴안게 해줄까?",
		},
		LIGHTNINGGOATHORN = "죽은 염소가 약간 불쌍하거든.",
		LITTLE_WALRUS = "잘 지내, 꼬마야?",
		LIVINGTREE = "해방되고 싶은 보드가 그 안에 갇혔거든.",
		LOCKEDWES = "너를 풀어주길 원하는 것이거든.",
		MAGIC_SEAL = "왜 누가 이것을 필요로 할까?",
		MAGMAROCK_FULL = "큰 돌이거든.",
		MAGMAROCK_GOLD_FULL = "반짝이는 것일까?",
		MANRABBIT_TAIL = "복슬복슬하거든!",
		MARBLE = "꽤 고급 재료거든.",
		MARBLEPILLAR = "무엇을 지탱했을까?",
		MARBLETREE = "아주 이상하거든.",
		MAXWELL = "못된 사람 같거든.",
		MAXWELLHEAD = "엇, 내가 환각의 씨를 먹은걸까?",
		MAXWELLLIGHT = "이상하거든.",
		MAXWELLLOCK = "소름 돋게 만들거든.",
		MAXWELLPHONOGRAPH = "유쾌하지만 거슬리거든.",
		MAXWELLTHRONE = "엇. 힘들겠거든.",
		MINOTAUR = "대단한 뿔이거든.",
		MINOTAURCHEST = "마법 상자야, 나를 위해 무엇을 할 수 있을까?",
		MINOTAURHORN = "이걸 구하기가 어려웠거든.",
		MOLE =
		{
			ABOVEGROUND = "표면으로 온 것을 환영하거든!",
			HELD = "그 안에 있으면 편할까?",
			UNDERGROUND = "누가 아래 있을까?",
		},
		MOLEHAT = "다 볼 수 있거든!",
		MOLEHILL = "좋은 두더지 구멍이거든.",
		MONKEY = "그가 서핑할 수 있을까?",
		MONKEYBALL = "저 작은 녀석은 누구일까? 나를 던지고 싶어?",
		MONKEYBARREL = "괜찮은 집이거든.",
		MONSTERTARTARE = "입 안에 넣고 싶지 않거든.",
		MOOSE = "큰 것이거든!",
		MOOSEEGG = "언젠가... 소... 거위... 동물이 될 것이거든.",
		MOSQUITO =
		{
			GENERIC = "더러운 흡혈귀거든!",
			HELD = "우리가 친구라고 생각하지 말자.",
		},
		MOSQUITOSACK = "코를 막으면 쓸만한 베개가 되거든.",
		MOSSLING = "들어서 꼭 쥐고 싶거든?",
		MOUND =
		{
			DUG = "전리품 고마워.",
			GENERIC = "간섭하면 무례해 보이거든.",
		},
		MUSSELBOUILLABAISE = "해물은 내가 가장 좋아하는 것이거든.",
		MYSTERYMEAT = "괴물 버거거든.",
		NEEDLESPEAR = "어. 무슨 소용일까.",
		NIGHTMARELIGHT = "어둠을 물리칠 수 있다면 이상해도 좋거든.",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "쉽게 숨쉴 수 있거든.",
			DAWN = "거의 끝났거든...!",
			NOMAGIC = "어디로든 가고 있지 않거든.",
			STEADY = "꾸준히 유지하고 있거든.",
			WANING = "사라지고 있거든...",
			WARN = "엇! 정말 열기가 강해지고 있거든!",
			WAXING = "힘이 세지고 있거든!",
		},
		NIGHTSTICK = "근사하게 생긴 지팡이거든.",
		ORANGEAMULET = "나를 이해하는 보석을 드디어 만났거든.",
		ORANGEGEM = "들여다보니 세계가 갈라진 것으로 보이거든!",
		ORANGESTAFF = "나를 위해 만든 지팡이거든!",
		OXHAT = "내 포니테일을 망치지 않았으면 좋겠거든.",
		OX_FLUTE = "이것으로 멋지게 연주하자.",
		OX_HORN = "동물에 붙어있지 않아서 좋거든.",
		PANDORASCHEST = "뭔가 좋은 걸 갖게 될까?",
		PARROT_PIRATE = "해적새거든.",
		PEG_LEG = "하나만 있으면 이상할까?",
		PENGUIN = "안녕, 꼬마.",
		PERD = "귀여운 작은 아이구나.",
		PIGGUARD = "가만히 있어도 되거든.",
		PIGGYBACK = "이럴 가치가 있었을까?",
		PIGHEAD =
		{
			BURNT = "타기 전에도 나빴거든?",
			GENERIC = "어렵겠거든.",
		},
		PIGHOUSE =
		{
			BURNT = "보험에 들었기를 바라거든.",
			FULL = "다 어떻게 들어갔을까?",
			GENERIC = "돼지가 휴식을 취하는 곳이거든.",
			LIGHTSOUT = "다시 켜야 되거든! 제발!",
		},
		PIGKING = "하하. 예절을 지켜야 하는 거야, 뭐야?",
		PIGMAN =
		{
			DEAD = "운이 안 좋거든.",
			FOLLOWER = "파도 타자!",
			GENERIC = "좋아 보이거든, 돼지.",
			GUARD = "아, 충성심이 높네. 훌륭한 면모거든.",
			WEREPIG = "하하! 그게 뭐냐?",
		},
		PIGTENT = "냄새가 그리 좋지 않거든.",
		PIGTORCH = "조금 귀엽거든.",
		PIKE_SKULL = "그리 좋지 않거든.",
		PINECONE =
		{
			GENERIC = "나무 아기거든.",
			PLANTED = "자라라, 작은 송이.",
		},
		PIRATEGHOST = "아. 영원한 잠을 잘 수 있었지만, 돌아왔거든.",
		POND = "요즘은 나 자신을 보는 것이 어렵거든.",
		POND_ALGAE = "대양을 그립게 하거든.",
		POTTEDFERN = "더 이상 마음대로 자라지 않거든.",
		PUMPKIN = "오늘 기분 좋아 보이네, 호박.",
		PUMPKINCOOKIE = "최고거든!",
		PUMPKIN_COOKED = "가을 냄새가 나거든.",
		PUMPKIN_LANTERN = "으스스해!",
		PUMPKIN_SEEDS = "이대로 좋거든. 더 키울 필요 없거든.",
		RABBIT =
		{
			GENERIC = "작은 귀를 봐 봐!",
			HELD = "무서워 할 필요 없거든.",
		},
		RABBITHOLE =
		{
			GENERIC = "토끼 모양이거든.",
			SPRING = "자기만의 시간이 필요했거든.",
		},
		RABBITHOUSE =
		{
			BURNT = "아유. 토끼가 집을 잃었거든.",
			GENERIC = "살기에 좋은 공간이거든.",
		},
		RAINCOAT = "파도가 날 적실 수는 없거든!",
		RAINHAT = "젖지 않게 하거든.",
		RAWLING = "웃기는 놈이거든!",
		RED_CAP = "땅에 떨어진 것을 먹는 것은 좋은 생각이 아니거든.",
		RED_MUSHROOM =
		{
			GENERIC = "이것이야말로 버섯이거든!",
			INGROUND = "숨고 있어, 작은 친구?",
			PICKED = "스스로 자라지 않을까.",
		},
		RELIC =
		{
			BROKEN = "내가 치우지 않을 것이거든.",
			GENERIC = "고대의 침대가 어디에 있을까?",
		},
		RESEARCHLAB4 =
		{
			BURNT = "더 이상 레버를 당길 수 없거든.",
			GENERIC = "레버가 나를 부르거든.",
		},
		ROBIN =
		{
			GENERIC = "날개 달린 노래거든.",
			HELD = "잘 있을까, 작은 친구?",
		},
		ROBIN_WINTER =
		{
			GENERIC = "사랑스러운 목소리를 가졌거든!",
			HELD = "너무 세게 쥔 것은 아닐까?",
		},
		ROBOT_PUPPET = "네 존재가 가엾거든.",
		ROCKY = "싸울 필요는 없거든!",
		ROCK_ICE =
		{
			GENERIC = "여기서 최소한 한 명은 놀 줄 알거든!",
			MELTED = "웅덩이에서 뛰어노는 부츠를 안 가져왔거든!",
		},
		ROCK_ICE_MELTED = "웅덩이에서 뛰어노는 부츠를 안 가져왔거든!",
		ROOK = "체크, 메이트!",
		ROOK_NIGHTMARE = "진짜일까?!",
		RUBBLE = "큰 돌 무더기거든.",
		RUINS_RUBBLE = "오래된 돌 무더기거든.",
		SAIL_STICK = "보통 막대보다 더 유용하거든.",
		SANDBAGSMALL_ITEM = "이것을 가지고 수영하지 말자!",
		SANITYROCK =
		{
			ACTIVE = "꺼져라!",
			INACTIVE = "나중에 보자.",
		},
		SHADOWSKITTISH_WATER = "야!",
		SHARKITTENSPAWNER =
		{
			GENERIC = "안에 고양이들이 놀고 있을 것이거든.",
			INACTIVE = "그냥 모래일까?",
		},
		SHIPWRECKED_ENTRANCE = "알로하, 세계!",
		SHIPWRECKED_EXIT = "알로하, 세계!",
		SLURPER = "약간 징그럽지만, 어쩔 수 없는 것이거든?",
		SLURPERPELT = "아마 담요로 사용할 수 있을 것이거든.",
		SLURPER_PELT = "아마 담요로 사용할 수 있을 것이거든.",
		SLURTLE = "발로 맛을 본다. 끔찍하거든.",
		SLURTLEHAT = "공개적으로 쓰기에는 약간 부끄러워.",
		SLURTLEHOLE = "달팽이 같은 것이 나오거든.",
		SLURTLESLIME = "쥐고 있기 어렵거든.",
		SLURTLE_SHELLPIECES = "가지고 있어도 쓸모 없어 보이거든.",
		SNAKEDEN =
		{
			BURNT = "이제 누구도 쓸 수 없거든.",
			CHOPPED = "그 덩굴은 내 것이거든.",
			GENERIC = "약간 엉킨 것 같거든.",
		},
		SNAKESKINSAIL = "보드가 있으니까 이건 필요 없거든?",
		SNAKE_FIRE = "다루기가 너무 뜨겁거든!",
		SNURTLE = "발로 맛을 본다. 끔찍하거든.",
		SPEAR_LAUNCHER = "좀 사납거든.",
		SPIDERHOLE = "구멍이거든. 거미가 가득 든.",
		SPIDER_DROPPER = "무례하게 내려오거든!",
		SPIDER_HIDER = "너가 보이거든!",
		SPIDER_SPITTER = "원하지 않거든!",
		STAFFLIGHT = "별빛은 피부에 나쁘지 않을까?",
		STAFF_TORNADO = "내가 당하는 것이 아니라서 다행이거든.",
		STALAGMITE = "꽤 쿨한 돌이거든.",
		STALAGMITE_FULL = "꽤 쿨한 돌이거든.",
		STALAGMITE_LOW = "꽤 쿨한 돌이거든.",
		STALAGMITE_MED = "꽤 쿨한 돌이거든.",
		STALAGMITE_TALL = "꽤 쿨한 돌이거든.",
		STALAGMITE_TALL_FULL = "꽤 쿨한 돌이거든.",
		STALAGMITE_TALL_LOW = "이 돌은 쿨해 보이지 않거든.",
		STALAGMITE_TALL_MED = "꽤 쿨한 돌이거든.",
		STATUEGLOMMER =
		{
			EMPTY = "오, 신기하거든.",
			GENERIC = "다 망쳤거든.",
		},
		STATUEHARP = "신발이 없음.. 머리 없음... 서비스 없음!",
		STATUEMAXWELL = "자만심 문제가 있거든.",
		SUNKEN_BOAT_BURNT = "바다의 추종자, 재가 되었거든. 불의거든!",
		SUNKEN_BOAT_TRINKET_1 = "어떻게 쓰는지 모르겠거든.",
		SUNKEN_BOAT_TRINKET_2 = "장난감 서프보드는 어디에 있을까?",
		SUNKEN_BOAT_TRINKET_3 = "병 안의 젖은 양초거든. 메가 천재니까!",
		SUNKEN_BOAT_TRINKET_4 = "바다의 가치는 얼마일까?",
		SUNKEN_BOAT_TRINKET_5 = "이미 부츠가 있거든.",
		SWEATERVEST = "내가 이것을 입고 있는 것을 서퍼 친구들에 들키지 말아야 하거든.",
		SWEETPOTATOSOUFFLE = "먹기 좋거든!",
		SWIMMINGHORROR = "아! 미치겠거든!",
		TELEBASE =
		{
			GEMS = "자주색 보석을 좋아하는 것 같거든.",
			VALID = "됐거든!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "정말 할까?",
			GENERIC = "짜식, 이상한 얼굴을 내밀어봐!",
			LOCKED = "그래도 통과하지 못 하거든.",
			PARTIAL = "이것을 조립하려면 까다로울 것이거든.",
		},
		TELEPORTATO_BOX = "중요해 보이거든.",
		TELEPORTATO_CRANK = "나와 함께 오고 싶은 것일까?",
		TELEPORTATO_POTATO = "헤헤.",
		TELEPORTATO_RING = "가지고 있어야 할 것 같거든.",
		TELESTAFF = "내가 보지 못한 것을 보여주거든.",
		TENTACLE = "손 떼라고 했거든!",
		TENTACLESPIKE = "물렁거려. 큰 피해를 줄 수 있지 않거든.",
		TENTACLESPOTS = "까다로운 상황에서 도움이 될 수 있거든.",
		TENTACLE_GARDEN = "존재할 이유가 없거든.",
		TENTACLE_PILLAR = "다 끈적거리거든.",
		TENTACLE_PILLAR_ARM = "너무 끈적거리거든!",
		THULECITE = "다른 세상의 것이거든.",
		THULECITE_PIECES = "이상하거든.",
		TIGEREYE = "최악이거든.",
		TREECLUMP = "애초에 여기를 통과하고 싶지 않았거든.",
		TRINKET_20 = "어떻게 쓰는지 모르겠거든.",
		TRINKET_21 = "장난감 서프 보드가 있을까?",
		TRINKET_22 = "병 안의 양초. 천재니까.",
		TRUNKVEST_WINTER = "이것 입고 잠들 수 있겠거든.",
		TRUNK_COOKED = "코를 먹을 수 있을 것 같거든.",
		TRUNK_SUMMER = "고기 같아 보이는 트렁크거든.",
		TRUNK_WINTER = "차가운 살코기 같아 보이는 트렁크거든.",
		TUMBLEWEED = "\"삶\"이라는 여행을 하는 중이거든.",
		TURF_SANDY = "신발에 들어가거든!",
		TURF_BADLANDS = "땅에 착 달라붙게 하거든.",
		TURF_CAVE = "지면이거든.",
		TURF_CHECKERFLOOR = "지면이거든.",
		TURF_DECIDUOUS = "땅에 착 달라붙게 하거든.",
		TURF_DESERTDIRT = "땅에 착 달라붙게 하거든.",
		TURF_DIRT = "흙.",
		TURF_FOREST = "땅에 착 달라붙게 하거든.",
		TURF_FUNGUS = "땅에 착 달라붙게 하거든.",
		TURF_FUNGUS_GREEN = "땅에 착 달라붙게 하거든.",
		TURF_FUNGUS_RED = "땅에 착 달라붙게 하거든.",
		TURF_GRASS = "풀이거든.",
		TURF_MAGMAFIELD = "땅에 착 달라붙게 하거든.",
		TURF_ROAD = "땅에 착 달라붙게 하거든.",
		TURF_ROCKY = "돌이 많거든.",
		TURF_SAVANNA = "땅에 착 달라붙게 하거든.",
		TURF_SNAKESKINFLOOR = "땅에 착 달라붙게 하거든.",
		TURF_SWAMP = "늪이거든.",
		TURF_TIDALMARSH = "늪 같거든.",
		TURF_VOLCANO = "땅에 착 달라붙게 하거든.",
		TURF_WOODFLOOR = "경목. 고급이거든.",
		TWISTER = "이것은 쉬어야 되거든!",
		TWISTER_SEAL = "그 얼굴을 내 얼굴에 대고 싶거든.",
		UNIMPLEMENTED = "내 일이라면 절대로 완료되지 않을 거야.",
		VOLCANO_ALTAR_TOWER = "아주 자연스럽지 않은 구조거든.",
		WALRUS = "회색 배! 잘 살고 있을까?",
		WALRUSHAT = "이 플래드가 나쁘지 않거든.",
		WALRUS_CAMP =
		{
			EMPTY = "아무도 집에 없거든.",
			GENERIC = "좋은 곳이거든.",
		},
		WALRUS_TUSK = "꽤 대단한 이빨이거든.",
		WARG = "넌 뭐가 문젤까?",
		WATERYGRAVE = "상처가 오래 되지 않았거든.",
		WHALE_TRACK = "추적하기에는 많은 노력이 들거든.",
		WILBUR_CROWN = "스타일이 마음에 들거든.",
		WILBUR_UNLOCK = "놀자, 친구야!",
		WILDBOREHEAD = "머리를 잃으면 그렇게 되거든.",
		WIND_CONCH = "파도를 멋지게 만들어 보자!",
		WINTERHAT = "머리를 포옹하는 느낌이거든.",
		WINTEROMETER =
		{
			BURNT = "더는 쓸모가 없거든.",
			GENERIC = "느낄 수 있는 것에 왜 수를 붙일까?",
		},
		WOODLEGSBOAT = "그래도 보드 타는 것이 더 마음에 들거든.",
		WOODLEGSHAT = "해양의 느낌이거든.",
		WOODLEGSSAIL = "서핑을 대체할 수 있거든... 일까.",
		WOODLEGS_CAGE = "우리를 발명한 사람은 못된 마음을 가졌거든.",
		WOODLEGS_KEY1 = "뼈 열쇠거든.",
		WOODLEGS_KEY2 = "비싸 보이거든.",
		WOODLEGS_KEY3 = "쇠 열쇠거든. 뭘 열까?",
		WORM =
		{
			DIRT = "무언가가 쓰러져 있거든.",
			PLANT = "볼 것이 없거든.",
			WORM = "그 녀석은 멋진 공중 기술을 쓸 수 있거든.",
		},
		WORMHOLE =
		{
			GENERIC = "앞구멍일까, 뒷구멍일까?",
			OPEN = "뭐, 안 들어갈 이유가 없거든.",
		},
		WORMHOLE_LIMITED = "기분이 좋아보이지 않는 것 같거든.",
		WORMLIGHT = "이상하게 매력적이거든.",
		WRECK = "아마도 금방 항해하지는 않을 것이거든.",
		YELLOWAMULET = "입으면 내 몸에서 빛이 나거든!",
		YELLOWGEM = "좋은 에너지가 나오거든.",
		YELLOWSTAFF = "별빛은 피부에 나쁘지 않을까?",
		CALIFORNIAROLL = "이걸 배 터지게 먹을 수 있거든.",
},
	DESCRIBE_GENERIC = "그래, 분명히 무엇인가겠거든.",
	DESCRIBE_SMOLDERING = "너무 뜨거워지고 있거든.",
	DESCRIBE_TOODARK = "도와 줘! 여기 무섭거든!",
		EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "미안해, 작은 아이야.",
	},
}