return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "Ech, i niby po co to?",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "Muszę poczekać, aż się czymś zajmie...",
			GENERIC = "Nie-e.",
			NOBITS = "Jest już ogolony!",
		},
		WRITE =
        {
            GENERIC = "Na tym nic nie napiszę.",
        },
		RUMMAGE =
        {   
            GENERIC = "Nic z tego.", 
        },
		COOK =
        {
            GENERIC = "Gotowanie to nie moja specjalność.",
            TOOFAR = "Za daleeeeko!",
        },
		STORE =
		{
			GENERIC = "Więcej nie wejdzie.",
			NOTALLOWED = "Nie da się.",
		},
		CHANGEIN =
        {
            GENERIC = "Ech, za dużo roboty.",
            BURNING = "Lepsze to niż jakieś durne sukienki!",
        },
        GIVE =
        {
            DEAD = "Chyba nie docenią mojego prezentu.",
            SLEEPING = "Nie teraz. Śpi",
            BUSY = "Zajęte.",
        },
        TEACH =
        {
            KNOWN = "Raaaju, przecież już to wiem!",
            CANTLEARN = "Mniejsza z tym, i tak nie chciałam tego wiedzieć.",
        },
	},
	ACTIONFAIL_GENERIC = "Nie dam rady!",
	ANNOUNCE_MAGIC_FAIL = "Dlaczego nie działa?!",
	ANNOUNCE_ADVENTUREFAIL = "Tym razem wygrałeś, Maxwellu!",
	ANNOUNCE_BOOMERANG = "Głupi bumerang!",
	ANNOUNCE_CHARLIE = "Nie boję się ciebie!",
	ANNOUNCE_CHARLIE_ATTACK = "AUĆ! Ty małpo!",
	ANNOUNCE_COLD = "Co za mróz! Aż pali!",
	ANNOUNCE_HOT = "Za ciepło!",
	ANNOUNCE_DUSK = "Nadchodzi noc. Potrzebuję ognia!",
	ANNOUNCE_WORMS = "Chyba nie chcę wiedzieć, co wydało ten dźwięk!",
	ANNOUNCE_EAT =
	{
		GENERIC = "Mniam!",
		PAINFUL = "Uch! Okropieństwo!",
		SPOILED = "To było ohydne!",
		STALE = "Trochę obrzydliwe.",
		INVALID = "Jak niby miałabym to zjeść?!",
		YUCKY = "Fuuj, nie ma mowy!",
	},
	ANNOUNCE_NOSLEEPONFIRE = "Martwię się tylko, że mogłabym zemdleć.",
	ANNOUNCE_NODANGERSIESTA = "Nie czas na odpoczynek! Czas stanąć do walki!",
	ANNOUNCE_NONIGHTSIESTA = "Nie dam rady tutaj odpocząć.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Wolałabym jednak wejść do środka.",
	ANNOUNCE_NOHUNGERSIESTA = "Nie mogę odpoczywać, jak mi w brzuchu gra!",
	ANNOUNCE_SHELTER = "Jednak nadajesz się nie tylko na podpałkę.",
	ANNOUNCE_BURNT = "Ogień strawi wszystko...",
	ANNOUNCE_TOOL_SLIP = "Wciąż mam zapalniczkę!",
	ANNOUNCE_DAMP = "Ups!",
	ANNOUNCE_WET = "To może się źle skończyć!",
	ANNOUNCE_WETTER = "Nienawidzę tego!",
	ANNOUNCE_SOAKED = "Ech, to jest NAJGORSZE!",
	ANNOUNCE_HOUNDS = "Pokażcie się!",
	ANNOUNCE_HUNGRY = "Jestem głodna!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Znajdę cię!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Ach... uciekł.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Buu! Zgubiłam trop w tym błocie.",
	ANNOUNCE_ACCOMPLISHMENT= "Rusz się, strzałko! NO DALEJ!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "UDAŁO SIĘ!",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "Hi, hi!",
		[2] = "Piękny!",
		[3] = "Ups!",
		[4] = "Rozpaliłam ogień!",
		[5] = "Płoń!",
		[6] = "Nie mogę się powstrzymać!",
	},
	ANNOUNCE_PECKED = "Nie! Niegrzeczny ptaszek!",
	ANNOUNCE_TORCH_OUT = "Mój skarb zgasł!",
	ANNOUNCE_FAN_OUT = "Zepsuło się, badziewie.",
    ANNOUNCE_COMPASS_OUT = "Arrgh! Igła się zacięła!",
	ANNOUNCE_WORMHOLE = "Będę musiała spalić te ciuchy!",
	ANNOUNCE_TRAP_WENT_OFF = "Aaa!",
    ANNOUNCE_CRAFTING_FAIL = "Czegoś brakuje.",
    ANNOUNCE_QUAKE = "Ten dźwięk na pewno nie wróży nic dobrego.",
    ANNOUNCE_NODANGERSLEEP = "Nie czas na odpoczynek! Trzeba się zająć walką!",
    ANNOUNCE_NOHUNGERSLEEP = "Burczy mi w brzuchu. Nie zasnę w takim stanie!",
    ANNOUNCE_FREEDOM = "Jestem wolna! Nadszedł czas ognia!",
    ANNOUNCE_RESEARCH = "Przydało się, chociaż nie ma nic wspólnego z ogniem.",
    ANNOUNCE_NO_TRAP = "To jak podpalić beczkę ryb.",
    ANNOUNCE_HIGHRESEARCH = "Tyle informacji!",
    ANNOUNCE_THORNS = "Auć!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Zbyt tu straszno, żeby spać.",
    ANNOUNCE_BEES = "Aaaaa! Kłujące robale!",
    ANNOUNCE_KNOCKEDOUT = "Argh! Moja głowa!",
    ANNOUNCE_LOWRESEARCH = "Buu, co za nuda.",
    ANNOUNCE_DEERCLOPS = "Brzmiało jak ogromny, wredny monstroludź!",
    ANNOUNCE_MOSQUITOS = "Uciekajcie, krwiopijcze bestie!",
    ANNOUNCE_NODAYSLEEP = "Nie zasnę, gdy na niebie świeci wielka kula ognia.",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "Wygląda odrobinę weselej.",
	ANNOUNCE_CANFIX = "\nChyba umiałabym to naprawić!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Ogień z nieba mi nie straszny.",
	ANNOUNCE_VOLCANO_ERUPT = "Ognista góra przemówiła!",
	ANNOUNCE_TREASURE = "X wskazuje miejsce!",
	ANNOUNCE_CRAB_ESCAPE = "A niech to! Uciekł.",
	ANNOUNCE_SHARX = "Hej! Przestań mi tam pluskać!",
	ANNOUNCE_MORETREASURE = "Doskonały poprawiacz humoru.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "To mi nie wygląda na mapę tej krainy.",
	ANNOUNCE_OTHER_WORLD_PLANT = "Nie urośnie. Może lepiej go spalić.",
	ANNOUNCE_MAPWRAP_WARN = "Ta mgła wygląda na dość gęstą.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Ups! Gdzie to ja miałam...",
	ANNOUNCE_MAPWRAP_RETURN = "Nic tam nie było widać!",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Wiadomość wyblakła. Nie dam rady przeczytać.",
	},
	ANNOUNCE_BOAT_DAMAGED = "Moja łódź jest ranna!",
	ANNOUNCE_BOAT_SINKING = "Tonę!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Żegnaj, okrutny świecie!",
	ANNOUNCE_ENTER_DARK = "Gdzie odłożyłam zapalniczkę?!",
	ANNOUNCE_ENTER_LIGHT = "Ja widzę! Już myślałam, że straciłam wzrok.",
	ANNOUNCE_INV_FULL = "Więcej już nie uniosę!",
	ANNOUNCE_TRAWL_FULL = "Sieć jest gotowa do wciągnięcia.",
	ANNOUNCE_UNIMPLEMENTED = "Wygląda niebezpiecznie! Trzeba to spalić!",
	ANNOUNCE_WAVE_BOOST = "Juuuhuuu!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Ooo, w pobliżu kręci się jakaś duża ryba.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Grr! Uciekł!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Woda jest zbyt wzburzona. Nic nie widać!",

	BATTLECRY =
	{
		GENERIC = "Albo ty, albo ja!",
		PIG = "Głupi prosiak!",
		PREY = "Chodź tutaj!",
		SPIDER = "Grrrrar!",
		SPIDER_WARRIOR = "Fuuuj, zaaabiiić!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Tak właśnie myślałam!",
		PIG = "Wracaj tu, szyneczko!",
		PREY = "Dopadnę cię następnym razem!",
		SPIDER = "Ech, zabiję go później.",
		SPIDER_WARRIOR = "Jednak nie taki z ciebie twardziel!",
	},
	
	DESCRIBE =
	{
		BIGFISHINGROD = "Duża rzecz!",
		DEVTOOL = "Aż się prosi, żeby to spalić.",
		DEVTOOL_NODEV = "Aż się prosi, żeby to spalić.",
		HOUNDFIRE = "Ale ekstra!",
		INVENTORYGRAVE = "Nie każdy się nadaje do tego miejsca.",
		INVENTORYMOUND = "Nie każdy się nadaje do tego miejsca.",
		MANDRAKE_COOKED = "W ogniu w końcu wszyscy milkną.",
		ROCK = "Taki jakby... kamień.",
		SLURPERPELT = "Gdybym ją podpaliła, śmierdziałaby jeszcze gorzej. Znacznie gorzej.",
		TREECLUMP = "Ruuuuuuuuuuuuusz się.",
		TURF_DESERTDIRT = "Gleba jest taka nudna.",
		TURF_FUNGUS_GREEN = "Gleba jest taka nudna.",
		TURF_FUNGUS_RED = "Gleba jest taka nudna.",
		TURF_SWAMP = "Bagnista.",
		WATERMELON_SEEDS = "Można by je zasiać, ale to chyba straszna nuda.",
		WORMHOLE_LIMITED = "Prawie się wypaliła.",
		GLOMMER = "Ale włochaty! I oślizgły...",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Dlaczego wszędzie napotykam jakieś kwiaty?!",
        	DEAD = "Ciekawe, czy się pali...",
        },
        GLOMMERWINGS = "Ale są malutkie!",
        GLOMMERFUEL = "Dziwny i obleśny.",
        BELL = "Mamy Nowy Rok? Czy to FAJERWERKI?",
        MOOSE_NESTING_GROUND = "Śmierdzi ptasim zadkiem!",
        STATUEGLOMMER = 
        {	
        	GENERIC = "To ma coś przedstawiać?",
        	EMPTY = "Wygląda identycznie.",
    	},
		WEBBERSKULL = "Wolę inne rozwiązania, ale bez pogrzebu się nie obędzie.",
		MOLE =
		{
			HELD = "Spod ziemi prosto do ognia.",
			UNDERGROUND = "Chowamy się przed słoneczkiem?",
			ABOVEGROUND = "Podglądacz!",
		},
		MOLEHILL = "Chowa się przed ogniem słońca. Dziwne.",
		MOLEHAT = "Jakoś nie jestem przekonana...",
		NIGHTSTICK = "Byłaby znacznie fajniejsza, gdyby płonęła.",
		RABBITHOUSE=
		{
			GENERIC = "Ugh. Głupie króliki.",
			BURNT = "Ha! Znakomicie.",
		},
		TURF_DECIDUOUS = "Gleba jest taka nudna.",
		TURF_SANDY = "Gleba jest taka nudna.",
		TURF_BADLANDS = "Gleba jest taka nudna.",
		BEARGER = "Oj! Grzeczny misiek...",
		BEARGERVEST = "Jakbym pływała w futrze.",
		ICEPACK = "Futrzasty plecak!",
		MOONROCKNUGGET = "Wygląda mi to na kamień....",
		ROCK_MOON = "Wygląda mi to na kamień....",
		BEARGER_FUR = "Futro, futro i jeszcze raz futro.",
		FURTUFT = "Czarno-białe futerko!",
		BIGFOOT = "Co do diaska?!",
		BONESHARD = "Chyba nie nadadzą się na podpałkę.",
		BUZZARD = "Masz paskudną szyję.",
		CACTUS = 
		{
			GENERIC = "Kolce! Moja słabość! Skąd wiedziałeś?",
			PICKED = "Niech będzie remis.",
		},
		CACTUS_MEAT_COOKED = "Teraz wydaje się w porządku.",
		CACTUS_MEAT = "Wciąż wygląda niebezpiecznie.",
		CACTUS_FLOWER = "Kolejny kwiatek.",
		COLDFIRE =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Lubię ogień pod każdą postacią.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ I NIEBIEŚCIEJ!",
			LOW = "Ogień jest mały i nudny.",
			NORMAL = "Płoń!",
			OUT = "Ach. Skończyło się.",
		},
		CATCOON = "Kici, kici, koteczku!",
		CATCOONDEN = 
		{
			GENERIC = "Nie mogłabym go podpalić, dopóki ktoś w nim mieszka.",
			EMPTY = "Puściutki i gotowy do palenia.",
		},
		CATCOONHAT = "Przytulaśna czapa.",
		COONTAIL = "Trzymałam już dziwniejsze rzeczy.",
		COOKPOT =
		{
			COOKING_LONG = "Ogień ma jeszcze trochę do zrobienia.",
			COOKING_SHORT = "Ogień ciężko pracuje!",
			DONE = "Najlepiej się gotuje na żywym ogniu.",
			EMPTY = "Do środka jedzenie, a pod spodem ogień.",
			BURNT = "Przynajmniej odszedł w płomieniach chwały.",
		},
		EYEBRELLAHAT =	"Jak ją założę, nie będę musiała na nią potrzeć...",
		ARMORDRAGONFLY = "Hurra! Więcej OGNIA!",
		DRAGON_SCALES = "Oooooch! PODOBAJĄ MI SIĘ.",
		DRAGONFLYCHEST = "Nie wiem, po co komuś coś, czego NIE DA się podpalić...",
		DECIDUOUSTREE = 
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Lepiej byłoby je spalić.",
			GENERIC = "Na pewno znakomicie się pali.",
			POISON = "Ogień postawiłby go do pionu.",
		},
		ACORN_COOKED = "Jednak nie zostaniesz drzewkiem.",
		BIRCHNUTDRAKE = "Aaach! Podpalmy go!",
		FARMPLOT =
		{
			GENERIC = "Ech. Kupa ziemi.",
			GROWING = "No dalej, kupo ziemi. Nakarm mnie!",
			NEEDSFERTILIZER = "Głupie pole potrzebuje nawozu.",
			BURNT = "Nienajgorsze widowisko.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Mogłabym go oglądać godzinami, mimo że jest zimny.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ I NIEBIEŚCIEJ!",
			LOW = "Ogień jest mały i nudny. I niebieski.",
			NORMAL = "Płoń!",
			OUT = "Powinnam przywrócić ogień do życia.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Mógłbyś się już zamknąć i przestać gasić ogień?",
			OFF = "I więcej się nie włączaj!",
			LOWFUEL = "Bliski końca.",
		},
		ICEHAT = "W sam raz na mój nastrój...",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Skoczna koza.",
			CHARGED = "Wariat!",
		},
		LIGHTNINGGOATHORN = "Jak przyłożę go do ucha, słyszę grzmoty.",
		GOATMILK = "Buczą w nim elektrony. Fuj.",
		MEATRACK =
		{
			DONE = "Gotowe!",
			DRYING = "No dalej, mięsko. Schnij!",
			DRYINGINRAIN = "Olej deszcz! Schnij!",
			GENERIC = "Mam ochotę coś tu zawiesić!",
			BURNT = "Może ogień nie jest jednak najlepszym przyjacielem suszenia...",
		},
		MERMHEAD = 
		{
			GENERIC = "I widzisz, co cię spotkało przez ten smród?!",
			BURNT = "Tutaj nawet ogień nie pomoże.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Nikomu nie byłoby żal, gdyby stanął w ogniu.",
			BURNT = "Rzeczywiście, nikomu nie żal.",
		},
		FLOWERSALAD = "Wolałabym miskę płomieni.",
        ICECREAM = "No cóż, niektóre zimne rzeczy też są fajne.",
        WATERMELONICLE = "Po co mrozić owoc, jak można go spalić?",
        TRAILMIX = "Chrup, chrup.",
        HOTCHILI = "Takie ciepło lubię!",
        GUACAMOLE = "O rajuśku! Ale paskudztwo!",
		MOOSE = "Co do diabła...",
		MOOSEEGG = "Ale ogroooomne!",
		MOSSLING = "Ma przypalone piórka.",
		FEATHERFAN = "Hmm... Nie wiem... Może dałoby się tym ugasić jakiś ogień...",
		TROPICALFAN = "Hmm... Nie wiem... Może dałoby się tym ugasić jakiś ogień...",
		GOOSE_FEATHER = "Ale przyjemne w dotyku!",
		STAFF_TORNADO = "Wciąż się obraca! Wiruje ku zniszczeniu!",
		PIGHEAD = 
		{	
			GENERIC = "Ładnie się załatwił.",
			BURNT = "Zawsze może być gorzej...",
		},
		PIGHOUSE =
		{
			FULL = "Robi tam jakieś świństwa.",
			GENERIC = "Achitektoniczny gust prosiaków jest dość dyskusyjny.",
			LIGHTSOUT = "Ty draniu! Wpuść mnie!",
			BURNT = "Willow cię urządzi!",
		},
		FERTILIZER = "Wiaderko obrzydliwości.",
		RAINOMETER = 
		{	
			GENERIC = "Deszcz jest zaprzeczeniem ognia. Buu!",
			BURNT = "A masz, deszczu!",
		},
		RAINCOAT = "To powinno załatwić sprawę.",
		RAINHAT = "Zrobię wszystko, byle woda trzymała się ode mnie z daleka.",
		RESEARCHLAB = 
		{	
			GENERIC = "Nawet ja jeszcze nie wszystko wiem.",
			BURNT = "Już nic się z tego nie nauczę.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Nawet ja jeszcze nie wszystko wiem.",
			BURNT = "Już nic się z tego nie nauczę.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Emanuje mroczną, potężną energią.",
			BURNT = "Potęga uleciała, został tylko mrok.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Mogłabym go użyć jako kociołka.",
			BURNT = "To z tym kociołkiem to może jednak nie najlepszy pomysł.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Moja polisa ubezpieczeniowa.",
			BURNT = "Moja polisa wygasła.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Chyba nie ma szans, żeby to podpalić.",
			MELTED = "Bezużyteczny. Jak to woda.",
		},
		ROCK_ICE_MELTED = "Bezużyteczny. Jak to woda.",
		ICE = "Zimnawy.",
        REFLECTIVEVEST = "Kamizelki to ostatni krzyk mody.",
		HAWAIIANSHIRT = "Ciekawe, czy pali się tak dobrze, jak prawdziwe kwiaty.",
		TENT = 
		{
			GENERIC = "W skautach zdobyłam wszystkie sprawności.",
			BURNT = "Cóż, wciąż mam swoje sprawności.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Uczyli nas budować takie na obozie harcerskim.",
			BURNT = "Jakimś cudem zawsze je podpalam.",
		},
		TRANSISTOR = "Z przyczłapami.",
		TREASURECHEST = 
		{
			GENERIC = "Skrzynia na szpargały.",
			BURNT = "Muszę przyznać, że płonęła wprost przepięknie.",
		},
		TUMBLEWEED = "Wygląda łatwopalnie.",
		GRASS_UMBRELLA = "Piękna na miarę swych możliwości!",
		PALMLEAF_UMBRELLA = "Całkiem ładna rzecz!",
		UNIMPLEMENTED = "Jeszcze nie jest gotowe. Ale na pewno da się podpalić.",
		WALL_HAY = 
		{	
			GENERIC = "Wygląda na bardzo łatwopalny.",
			BURNT = "I był łatwopalny!",
		},
		WALL_WOOD = 
		{
			GENERIC = "Może się łatwo zapalić...",
			BURNT = "No i się zapaliło!",
		},
		WARG = "You're a big mean jerk!",
		WATERMELON = "Znałam kiedyś takiego jednego. Miał na imię Arek i był kierowcą busa.",
		WATERMELON_COOKED = "Ciepły, słodki, soczysty.",
		WATERMELONHAT = "Cóż. Można i tak.",
		WINTEROMETER = 
		{
			GENERIC = "Bardziej by się przydał, gdyby mierzył ogień.",
			BURNT = "Gdybyś mierzył ogień, to byłbyś na to gotowy!",
		},
		HOME = "I'm gonna burn it.",
		HOMESIGN = 
		{
			GENERIC = "Dość czytania, czas na ogień!",
			UNWRITTEN = "Można by tu coś wypalić.",
			BURNT = "Ha, ha, ha! Taaaak!",
		},
		BEEBOX =
		{
			READY = "Ha! Mogę podkraść trochę miodu!",
			FULLHONEY = "Ha! Mogę podkraść trochę miodu!",
			GENERIC = "No dalej, leniwe pszczoły. Róbcie miód!",
			NOHONEY = "Nie ma tu nic ciekawego.",
			SOMEHONEY = "Cierpliwości.",
			BURNT = "Wędzony miód?",
		},
		LIVINGTREE = "Może i jest żywe, ale na pewno pali się jak każde inne.",
		ICESTAFF = "Nuuuuuda.",
		WORMLIGHT = "Światło bez ognia. To sprzeczne z naturą.",
		WORMLIGHT_LESSER = "W dotyku podobne do babcinych dłoni.",
		WORM =
		{
		    PLANT = "Światło bez ognia. To sprzeczne z naturą.",
		    DIRT = "Czy ziemia normalnie sama się przemieszcza?",
		    WORM = "Ale włochaty!",
		},
		WORMLIGHT_PLANT = "Światło bez ognia. To sprzeczne z naturą.",
		EEL = "Nie podoba mi się jego spojrzenie!",
		EEL_COOKED = "Ogień uszlachetnia wszystko.",
		UNAGI = "Można go trochę udziwnić, ale to jednak węgorz.",
		EYETURRET = "Szkoda, że nie miota ogniem.",
		EYETURRET_ITEM = "Na nic się nie przyda, dopóki jej gdzieś nie ustawię.",
		MINOTAURHORN = "Ciekawe, czy te pierścienie wskazują wiek.",
		MINOTAURCHEST = "Też chcę takie rogi!",
		THULECITE_PIECES = "Tulecyt rozpadł się na kawałki.",
		POND = "Nie ma szans, żeby go podpalić. Co za nuda.",
		POND_ALGAE = "Pewnie potrzebuje sporo wody.",
		GREENSTAFF = "Ognia tym nie rozpalę, ale i tak może się przydać.",
		POTTEDFERN = "Najchętniej spaliłabym je wszystkie.",

		THULECITE = "Chyba się nie zapali.",
		ARMORRUINS = "Nie jestem pewna, czy chcę to włożyć.",
		RUINS_BAT = "Będą się dranie trzymać z daleka.",
		RUINSHAT = "Coś chyba przez nią przepływa.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Wygląda całkiem normalnie.",	--Calm phase
			WARN = "Ostrzega mnie.",	--Before nightmare
			WAXING = "Paliwo powstaje do życia!", --Nightmare Phase first 33%
			STEADY = "Sytuacja jest stabilna.", --Nightmare 33% - 66%
			WANING = "Chyba się wyłącza.", --Nightmare 66% +
			DAWN = "Chyba już mija.", --After nightmare
			NOMAGIC = "Chyba nie działa.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "Aaach!",
		ROOK_NIGHTMARE = "Ma parszywy uśmiech.",
		KNIGHT_NIGHTMARE = "Trochę się zużył.",
		MINOTAUR = "Biedaczek. Utknął w labiryncie.",	--Monster in labyrinth
		SPIDER_DROPPER = "Przybywają z góry.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Światło bez ognia. To sprzeczne z naturą.",	--Lights that activate during nightmare.
		GREENGEM = "Wydaje się niezwykle lekki.",
		RELIC = "I guess someone lived here before.",	--Fixed relic
		RUINS_RUBBLE = "Pewnie dałabym radę to naprawić.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "Przydatna rzecz!",	--Works as axe and pickaxe
		ORANGESTAFF = "Głowa mnie od niego boli.",	--Teleports player.
		YELLOWAMULET = "Zdaje się pochłaniać otaczający go mrok.",	--Emits light, player walks faster.
		GREENAMULET = "Czuję, jak mój umysł się otwiera.",	--Reduce cost of crafting

		SLURPER = "Chyba maja w brzuszkach małe ogniki....",
		SLURPER_PELT = "Fuuuuj! Jeszcze żyje!",
		ARMORSLURPER = "Och, aj! Aj! Aj! Aj! Aj! Fuuuuuuuuuuuj!",
		ORANGEAMULET = "Zbiera dla mnie materiały do palenia!",
		YELLOWSTAFF = "To magia!",
		YELLOWGEM = "Aż się skrzy!",
		ORANGEGEM = "Czuję mrowienie w palcach.",
		PALMTREE =
        {
			BURNING = "Wooow! To się nazywa ogień!",
			BURNT = "Tak jest znacznie lepiej.",
			CHOPPED = "Trzeba się było trochę namachać.",
			GENERIC = "Jakoś ma dziwnie mało gałęzi.",
		},
		TELEBASE = 
		{
			VALID = "Wyczuwam magię!",
			GEMS = "Potrzeba czegoś więcej.",
		},
		GEMSOCKET = 
		{
			VALID = "Ciekawe, jakim sposobem utrzymują się w powietrzu...",
			GEMS = "Pustka!",
		},
		STAFFLIGHT = "Ale piękny!",

        LIGHTER = "Moja ukochana zapalniczka!",


        ANCIENT_ALTAR =
        {
        	WORKING = "Oooo! Centrala zaświatów.",
        	BROKEN = "Śmierć nie ma tutaj dostępu.",
        },  
        ANCIENT_ALTAR_BROKEN = "Śmierć nie ma tutaj dostępu.",

        ANCIENT_STATUE = "A niech to, nie chce się palić.",

        LICHEN = "Obrzydliwa, łamliwa roślina.",
		CUTLICHEN = "Ble. Smakuje jak trociny.",

        CAVE_BANANA = "Banany!",
        CAVE_BANANA_COOKED = "Mniam!",
        CAVE_BANANA_BURNT = "To mi się podoba!",
        CAVE_BANANA_TREE = "Chyba dałoby się go podpalić!",
        ROCKY = "Nie mamy zbyt wiele wspólnego.",

        BLUEAMULET = "Bezużyteczny śmieć.",
		PURPLEAMULET = "Czyżby nauka posunęła się za daleko?",
		TELESTAFF = "Puf! Niespodzianka!",
		MINERHAT = "Ogień to to nie jest, ale i tak mi się podoba.",
		MONKEY = "I kto się śmieje ostatni?! Mogę podpalić tę kupę.",
		MONKEYBARREL = "Ale cudownie łatwopalny domek.",

		HOUNDSTOOTH="Ostry! Podoba mi się!",
		ARMORSNURTLESHELL="Mniej obrony, więcej ataku!",
		BAT="Ale słodziak!",
		BATBAT = "Mogę tym przywalić swym rywalom.",
		BATWING="Fuj!",
		BATWING_COOKED="Fuj!",
		BEDROLL_FURRY="Jak dla mnie trochę zbyt puchaty.",
		BUNNYMAN="Ugh. Wyglądają strasznie głupio.",
		FLOWER_CAVE="Płonie od wewnątrz.",
		FLOWER_CAVE_DOUBLE="Płonie od wewnątrz.",
		FLOWER_CAVE_TRIPLE="Płonie od wewnątrz.",
		GUANO="Pali się jak normalne łajno.",
		LANTERN="Ognia nie można tak ograniczać!",
		LIGHTBULB="Wkładanie żarówek do buzi podobno może skończyć się tragicznie.",
		MANRABBIT_TAIL="Wygrałam ten spór.",
		MUSHTREE_TALL=
		{
            GENERIC = "Gross. This tree is sick all over.",
            BLOOM = "Ack! It stinks!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Gross. It smells like leprechaun butt.",
            BLOOM = "It's spreading junk everywhere.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Gross. It's all mushroomy.",
            BLOOM = "Ew, I don't want to get too close.",
        },
        MUSHTREE_TALL_WEBBED = "Dostał, na co zasłużył.",
        SPORE_TALL = "Jak kolorowe iskry!",
        SPORE_MEDIUM = "Jak kolorowe iskry!",
        SPORE_SMALL = "Jak kolorowe iskry!",
        SPORE_TALL_INV = "Na pewno łatwo się pali.",
        SPORE_MEDIUM_INV = "Na pewno łatwo się pali.",
        SPORE_SMALL_INV = "Na pewno łatwo się pali.",
		MUSHTREE_TALL="Okropieństwo. To drzewo jest chore.",
		MUSHTREE_MEDIUM="Wstrętne. Śmierdzi jak tyłek kobolda.",
		MUSHTREE_SMALL="Okropieństwo. Jakieś takie całe grzybowe.",

		SLURTLE="Mam ochotę wysadzić go w powietrze!",
		SLURTLE_SHELLPIECES="Zepsuła się.",
		SLURTLEHAT="Pasuje na moją głowę.",
		SLURTLEHOLE="Powinnam wywabić je ogniem.",
		SLURTLESLIME="Uwielbiam to!",
		SNURTLE="Kabum!",
		SPIDER_HIDER="Co za wnerwiający kretyn!",
		SPIDER_SPITTER="Chodź tutaj!",
		SPIDERHOLE="Pełen pająków.",
		STALAGMITE="Kamienie są takie nudne.",
		STALAGMITE_FULL="Kamienie są takie nudne.",
		STALAGMITE_LOW="Kamienie są takie nudne.",
		STALAGMITE_MED="Kamienie są takie nudne.",
		STALAGMITE_TALL="Więcej nudnych kamieni.",
		STALAGMITE_TALL_FULL="Więcej nudnych kamieni.",
		STALAGMITE_TALL_LOW="Więcej nudnych kamieni.",
		STALAGMITE_TALL_MED="Więcej nudnych kamieni.",

		TURF_CARPETFLOOR = "Gleba jest taka nudna.",
		TURF_CHECKERFLOOR = "Gleba jest taka nudna.",
		TURF_DIRT = "Gleba jest taka nudna.",
		TURF_FOREST = "Gleba jest taka nudna.",
		TURF_GRASS = "Gleba jest taka nudna.",
		TURF_MARSH = "Gleba jest taka nudna.",
		TURF_ROAD = "Gleba jest taka nudna.",
		TURF_ROCKY = "Gleba jest taka nudna.",
		TURF_SAVANNA = "Gleba jest taka nudna.",
		TURF_WOODFLOOR = "Gleba jest taka nudna.",
		TURF_DRAGONFLY = "Moja zapalniczka nic tu nie da.",

		TURF_CAVE="Gleba jest taka nudna.",
		TURF_FUNGUS="Gleba jest taka nudna.",
		TURF_SINKHOLE="Gleba jest taka nudna.",
		TURF_UNDERROCK="Gleba jest taka nudna.",
		TURF_MUD="Gleba jest taka nudna.",
		
		TURKEYDINNER = "Uczta ze spalonego ptaka.",
		TWIGS = "Kupka małych gałązek. Dobra na przykład na podpałkę.",
		POWCAKE = "Ciekawe, czy łatwo się pali.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Who plugged that hole?",
            OPEN = "I hope there's lava down there somewhere.",
        },
        CAVE_EXIT = "It's too dark and stuffy down here.",
        CAVE_ENTRANCE = "Kto zatkał tę dziurę?",
        CAVE_ENTRANCE_RUINS = "Kto zatkał tę dziurę?",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "Nie zamierzam włazić do tej dziury obrzydliwości!",
            OPEN = "Mam nadzieję, że gdzieś tam w dole jest lawa.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Przynajmniej jest chłodniej.",
            OPEN = "Ciemno tu i duszno.",
        },

		MAXWELLPHONOGRAPH = "Wolę trochę żywszą muzykę.",
		PIGGUARD = "Lubię jego podejście do życia!",
		BOOMERANG = "Niezbyt ekscytująca broń.",
		ADVENTURE_PORTAL = "Może prowadzi do domu.",
		AMULET = "Jestem niezwyciężona! No, może nie. Ale uczucie jest fajnie.",
		ANIMAL_TRACK = "Prowadzi do mojego nowego przyjaciela.",
		ARMORGRASS = "Szkoda łatwopalnych materiałów.",
		ARMORMARBLE = "Skoro mam walczyć, to należy mi się ochrona.",
		ARMORWOOD = "Teraz mogę zmierzyć się ze światem!",
		ARMOR_SANITY = "Jakbym się ubrała w dym.",
		ASH =
		{
			GENERIC = "Resztki po ogniu. Szkoda, że już go nie ma.",
			REMAINS_GLOMMERFLOWER = "Szkoda, że nie widziałam, jak ten dziwny kwiat się pali.",
			REMAINS_EYE_BONE = "Założę się, że to coś z okiem świetnie wyglądałoby w ogniu.",
			REMAINS_THINGIE = "Cokolwiek to było, szkoda, że już nie płonie.",
		},
		AXE = "Ostra rzecz.",
		BABYBEEFALO =
		{
			GENERIC = "Nawet młode są paskudne.",
			SLEEPING = "POBUDKA!",
		},
		BACKPACK = "Zmieściłabym tu chyba z milion zapalniczek.",
		BACONEGGS = "To żółte oślizgłe coś jest obrzydliwe, ale boczek – pierwsza klasa.",
		BANDAGE = "Ech, naprawdę muszę?",
		BASALT = "Za twardy! Nie dam rady go zniszczyć!",
		BEARDHAIR = "Eee, skąd to się wzięło?",
		BEDROLL_STRAW = "Trochę stęchły.",
		BEE =
		{
			GENERIC = "Jest raczej gruba, ale to żądło wygląda niebezpiecznie.",
			HELD = "Już nie pofruwa. Ani tu, ani tam.",
		},
		BEEFALO =
		{
			FOLLOWER = "Eee, chodzisz za mną?",
			GENERIC = "Co za obrzydliwa, włochata bestia!",
			NAKED = "Ha! Teraz jest goły!",
			SLEEPING = "Jak śpią, wyglądają jeszcze głupiej.",
		},
		BEEFALOHAT = "Zabrałam mu włosy i nałożyłam na własne!",
		BEEFALOWOOL = "Ha! Ukradłam mu kłaki!",
		BEEHIVE = "Pełen pszczół!",
		BEEMINE = "Pełna pszczół. Powinnam jeszcze dołożyć trochę ognia.",
		BEEMINE_MAXWELL = "Pełna komarów. Nie wydają się szczęśliwe.",
		BEEHAT = "To mnie ochroni przed tymi kłujkami.",
		BERRIES = "Czerwone są najlepsze.",
		BERRIES_COOKED = "Porzeczki opieczone w ogniu jakoś lepiej smakują.",
		BERRYBUSH =
		{
			BARREN = "Jedz to, głupia roślino!",
			WITHERED = "Wyschnięty. Gotowy do spalenia!",
			GENERIC = "Mmmmm. Porzeczki.",
			PICKED = "Chcę więcej porzeczek!",
		},
		BIRDCAGE =
		{
			GENERIC = "Ptasie więzienie!",
			OCCUPIED = "Ha! Mam cię!",
			SLEEPING = "Głupi ptak. Obudź się!",
			HUNGRY = "O co tyle krzyku?",
			STARVING = "Nie chce się zamknąć!",
			DEAD = "Przynajmniej jest cicho.",
			SKELETON = "Chyba trzeba to posprzątać.",
		},
		BIRDTRAP = "Złapię was, przeklęte ptaki.",
		BIRD_EGG = "Śmierdzi jak ptasi tyłek.",
		BIRD_EGG_COOKED = "Fuj! Żółtko jest surowe.",
		BISHOP = "Goniec!",
		BISHOP_CHARGE_HIT = "Auuuu!",
		BLOWDART_FIRE = "Najlepsza rzecz na całym świecie.",
		BLOWDART_SLEEP = "Środek usypiający ułatwia podpalanie.",
		BLOWDART_PIPE = "Dobry trening przed rozniecaniem ognia.",
		BLUEGEM = "Ugh. Ten jest okropny.",
		BLUEPRINT = "Oszczędzę trochę czasu na eksperymentach.",
		BELL_BLUEPRINT = "Oszczędzę trochę czasu na eksperymentach.",
		BLUE_CAP = "Śmierdzi jak skarpeta maratończyka!",
		BLUE_CAP_COOKED = "Ogień go odmienił!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Głupi grzyb.",
			INGROUND = "Hej, ty! Wyłaź!",
			PICKED = "Może kiedyś odrośnie.",
		},
		BOARDS = "Deski. Palą się tak samo jak drewno w każdej innej postaci.",
		BONESTEW = "Wystarczy dodać ognia do jedzenia i voila!",
		BUGNET = "Mogę łapać owady!",
		BUSHHAT = "Nuda!",
		BUTTER = "Masełko idzie w sadełko.",
		BUTTERFLY =
		{
			GENERIC = "Motylku, leć...",
			HELD = "Mam ochotę go zgnieść.",
		},
		BUTTERFLYMUFFIN = "Ha, ha! Motyl utknął w babeczce.",
		BUTTERFLYWINGS = "Skończyło się motylowanie!",
		CAMPFIRE =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Lubię ogień.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ!",
			LOW = "Ogień jest mały i nudny.",
			NORMAL = "Płoń!",
			OUT = "Ach. Skończyło się.",
		},
		CANE = "Teraz łatwiej mi będzie iść!",
		CARROT = "Fuj. Żarcie dla królików.",
		CARROT_COOKED = "Wciąż bardzo warzywna, ale ogień trochę poprawił smak.",
		CARROT_PLANTED = "Może znajdzie w ziemi swojego marchewkowego przyjaciela.",
		CARROT_SEEDS = "Nasiona pomarańczowego obrzydlistwa.",
		CAVE_FERN = "Wygląda na łatwopalną.",
		CHARCOAL = "Mmm. Pachnie ogniem.",
        CHESSJUNK1 = "Martwy nakręcany konik.",
        CHESSJUNK2 = "Martwy nakręcany posłaniec.",
        CHESSJUNK3 = "Martwy nakręcany zamek.",
		CHESTER = "Ale włochata!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Niegrzecznie jest się gapić.",
			WAITING = "Przynajmniej już się na mnie nie gapi.",
		},
		COOKEDMEAT = "Niedoprawione mięso... super.",
		COOKEDMONSTERMEAT = "Wciąż jest ohydne.",
		COOKEDSMALLMEAT = "Jeśli mam przetrwać, będę potrzebowała czegoś więcej.",
		CORN = "Słodkie warzywo, mniam!",
		CORN_COOKED = "Och! W ogniu eksploduje!",
		CORN_SEEDS = "Nasionka mojego ulubionego wybuchowego warzywa.",
		CROW =
		{
			GENERIC = "Chyba czeka, aż umrę.",
			HELD = "Wcale nie taki sprytny z ciebie ptaszek, co?",
		},
		CUTGRASS = "Ścięta trawa, gotowa do spalenia. Ewentualnie do jakiegoś rzemiosła.",
		CUTREEDS = "Cięty tatarak, gotowy do spalenia. Ewentualnie do jakiegoś rzemiosła.",
		CUTSTONE = "Idealnie ociosane dla maksimum przyjemności.",
		DEADLYFEAST = "Ogień nie pomógł. I tak jest obrzydliwa.",
		DEERCLOPS = "O rety!",
		DEERCLOPS_EYEBALL = "Przestań się na mnie gapić!",
		DIRTPILE = "Kto w ogóle zostawia w lesie jakąś ziemię?",
		DIVININGROD =
		{
			COLD = "Wydaje jakieś ciche dźwięki.",
			GENERIC = "Elektryczne ustrojstwo.",
			HOT = "Wystarczy tego pikania!",
			WARM = "Robi się coraz głośniejsza.",
			WARMER = "Chyba jestem blisko!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Nie wiem, co to robi. Chyba nie ma nic wspólnego z ogniem.",
			READY = "Trzeba to otworzyć. Niestety kluczem, a nie ogniem.",
			UNLOCKED = "Zaczęło się kręcić!",
		},
		DIVININGRODSTART = "Coś się z tego wymyśli.",
		DRAGONFLY = "Jest przepełniona ogniem!",
		LAVASPIT = 
		{
			HOT = "Gorąca pluja.",
			COOL = "Zimna pluja.",
		},
		LAVA_POND = "Tak! Takkkk!",
		LAVAE = "Może zostaniemy przyjaciółmi?",
		LAVAE_PET = 
		{
			STARVING = "Widać mu żeberka!",
			HUNGRY = "Chyba potrzebuje ognia.",
			CONTENT = "Mój własny ognioinator.",
			GENERIC = "Jest... idealny.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "Ogień chyba próbuje się wydostać.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Zimny drań.",
			COMFY = "Wygląda na szczęśliwe.",
		},
		LAVAE_TOOTH = "Mam nadzieję, że nie gryzie.",
		DRAGONFRUIT = "Wygląda trochę jak ogień!",
		DRAGONFRUIT_COOKED = "Teraz bardziej wygląda na owoc, który ma coś do czynienia z ogniem.",
		DRAGONFRUIT_SEEDS = "Nasiona tego ognistego owocu.",
		DRAGONPIE = "Ciasto z ognistymi owocami? O raju!",
		DRUMSTICK = "Kurczę pieczone!",
		DRUMSTICK_COOKED = "Zabić głód, czy kogoś?",
		DURIAN = "Ale śmierdziel!",
		DURIAN_COOKED = "Fuj! Ugotowany śmierdzi równie paskudnie!",
		DURIAN_SEEDS = "Śmierdzące nasiona śmierdzącego owocu.",
		EARMUFFSHAT = "Śmierdzi jak tyłek królika.",
		EGGPLANT = "Na pewno nie jest psem.",
		EGGPLANT_COOKED = "Ogień znacznie pomógł.",
		EGGPLANT_SEEDS = "Ciekawe, co z nich wyrośnie. Warzywa, czy małe pieski?",
		STUFFEDEGGPLANT = "Wciąż nie jest psem, ale jest wypchany jak martwy pies.",
		DUG_BERRYBUSH = "Co jest? Brakuje ci ziemi?",
		DUG_GRASS = "Co jest? Brakuje ci ziemi?",
		DUG_MARSH_BUSH = "Co jest? Brakuje ci ziemi?",
		DUG_SAPLING = "Co jest? Brakuje ci ziemi?",
		EARMUFFS = "Śmierdzi jak tyłek królika.",
		ACORN = 
		{
		    GENERIC = "Witaj, drzewne nasionko.",
		    PLANTED = "Wkrótce będziesz prawdziwym drzewem.",
		},
		EVERGREEN =
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Jedno drzewo mniej na świecie.",
			GENERIC = "Na pewno znakomicie się pali.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Jedno drzewo mniej na świecie.",
			GENERIC = "Giń w ogniu!",
		},
		EYEPLANT = "Rozprzestrzeniają się jak ogień.",
		FEATHERHAT = "Jestem feniksem!",
		FEATHER_CROW = "Pióro kruka. Pewnie strasznie śmierdzi w ogniu.",
		FEATHER_ROBIN = "Pióro kardynała. Pewnie strasznie śmierdzi w ogniu.",
		FEATHER_ROBIN_WINTER = "Pióro śnieżyka. Pewnie strasznie śmierdzi w ogniu.",
		FEM_PUPPET = "Chyba się boi.",
		FIREFLIES =
		{
			GENERIC = "Szkoda, że tak uciekają!",
			HELD = "Są jak małe ogniki w kieszeni!",
		},
		FIREHOUND = "W sumie to te nawet mi się podobają...",
		FIREPIT =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Mogłabym się w nie wpatrywać godzinami.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ!",
			LOW = "Ogień jest mały i nudny.",
			NORMAL = "Płoń!",
			OUT = "Powinnam przywrócić ogień do życia.",
		},
		FIRESTAFF = "Moja najulubieńsza zabawka.",
		FISH = "Ryba wpływa na wszystko!",
		FISHINGROD = "Wędkowanie wcale nie jest takie proste.",
		FISHSTICKS = "Jesteś tym, co jesz. Teraz będę rybnym paluchem.",
		FISHTACOS = "Wygodny taco-chwyt!",
		FISH_MED = "Czas wrzucić ją do ognia!",
		FISH_MED_COOKED = "Wygląda na całkiem jadalną.",
		FISH_COOKED = "Po spotkaniu z ogniem nie jest już taka śliska.",
		FLINT = "Zapalniczka dla ubogich.",
		FLOWER = "Nie mam czasu na jakieś kwiatki.",
		FLOWERHAT = "Aureola z kwiatków. Szkoda, że nie jest to płonąca aureola z kwiatków.",
		FLOWER_EVIL = "Śmierdzi paskudnie.",
		FOLIAGE = "Paliwo dla ognia.",
		FOOTBALLHAT = "Sport nie jest łatwy.",
		FROG =
		{
			DEAD = "Ale jej pokazałam!",
			GENERIC = "Zbyt wilgotna, żeby się zapalić.",
			SLEEPING = "Są takie urocze, jak śpią.",
		},
		FROGGLEBUNWICH = "Może wcale nie zauważę, że to żabie nogi w bułce...",
		FROGLEGS = "Jeszcze się ruszają. Straszne.",
		FROGLEGS_COOKED = "W ogniu przestały wreszcie wierzgać. Ogień jest fantastyczny.",
		FRUITMEDLEY = "Mmm, owocki!",
		GEARS = "To pewnie dzięki nim się ruszają.",
		GHOST = "Nie mogę zabić kogoś, kto już nie żyje.",
		GOLDENAXE = "Może nie podpali drzewa, ale przynajmniej się błyszczy.",
		GOLDENPICKAXE = "Może nie podpali kamienia, ale przynajmniej się błyszczy.",
		GOLDENPITCHFORK = "Ziemi nie podpali, ale przynajmniej ładnie się błyszczy.",
		GOLDENSHOVEL = "Nie dokopię się nią do ognia, ale przynajmniej ładnie błyszczy.",
		GOLDNUGGET = "I gdzie ja to wydam?",
		GRASS =
		{
			BARREN = "Potrzebuje nawozu.",
			WITHERED = "Zupełnie sucha i gotowa do spalenia!",
			BURNING = "Ogień! Hurra!",
			GENERIC = "Łatwopalna kępka trawy.",
			PICKED = "Małe ściernisko. Raczej bezużyteczne.",
		},
		GREEN_CAP = "Nuda!",
		GREEN_CAP_COOKED = "Ogień go odmienił!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Głupi grzyb.",
			INGROUND = "Hej, ty! Wyłaź!",
			PICKED = "Może kiedyś odrośnie.",
		},
		GUNPOWDER = "Oooooooch! Będzie ogień!",
		HAMBAT = "Spuszczę komuś mięsisty łomot!",
		HAMMER = "Wolę ostre narzędzia.",
		HEALINGSALVE = "Pali! Gdzie jest ogień?",
		HEATROCK =
		{
			FROZEN = "Zamarznięty na kamień.",
			COLD = "Zimny jak głaz.",
			GENERIC = "Ogień mógłby go ożywić!",
			WARM = "Nie ma płomienia, nie ma prawdziwego ciepła... Gdzie tu przyjemność?",
			HOT = "Ale się świeci!",
		},
		HONEY = "Słodki i pyszny!",
		HONEYCOMB = "Bardzo woskowaty.",
		HONEYHAM = "Ogień, szynka i miód – doskonałe połączenie.",
		HONEYNUGGETS = "Pokryte miodem kąski po spotkaniu z moim najlepszym przyjacielem.",
		HORN = "Słyszę wewnątrz te włochate bestie.",
		HOUND = "Co za wredne zwierzę!",
		HOUNDMOUND = "Uj... Nie podoba mi się to.",
		HOUNDBONE = "Obrzydliwe.",
		ICEBOX = "Odwrotność ognia.",
		ICEHOUND = "Obrzydliwy! I zimny!",
		INSANITYROCK =
		{
			ACTIVE = "Zaczynam mieć zwidy?",
			INACTIVE = "Wygląda na zupełnie niepalny. Ale nuda.",
		},
		JAMMYPRESERVES = "Marmelada!",
		KABOBS = "Mięso i ogień. I patyczek!",
		KILLERBEE =
		{
			GENERIC = "Fajny ma kolec.",
			HELD = "Bzzz!",
		},
		KNIGHT = "Kucyk!",
		KOALEFANT_SUMMER = "Będziemy dobrymi przyjaciółmi!",
		KOALEFANT_WINTER = "Wygląda cieplutko...",
		KRAMPUS = "Trzymaj się z dala, wredny paskudzie!",
		KRAMPUS_SACK = "Święta przyszły wcześniej w tym roku!",
		LEIF = "Na pewno jest łatwopalny!",
		LEIF_SPARSE = "Na pewno jest łatwopalny!",
		LIGHTNING_ROD =
		{
			CHARGED = "Ooo, świeci, a nie ma ognia.",
			GENERIC = "Zapraszamy wszystkie błyskawice tutaj!",
		},
		LITTLE_WALRUS = "Wygląda smacznie.",
		LIVINGLOG = "Wygląda na zdenerwowaną.",
		LOCKEDWES = "Uwięziły go te podłe posągi!",
		LOG =
		{
			BURNING = "Płoń, drewienko, płooooń!",
			GENERIC = "Drewno! Tak łatwopalne! Tak śmiesznie marne!",
		},
		LUREPLANT = "Odrobina ognia załatwiłaby sprawę.",
		LUREPLANTBULB = "Teraz jest moja.",
		MALE_PUPPET = "Chyba się boi.",
		MANDRAKE =
		{
			DEAD = "Dlaczego ta roślina ma twarz?",
			GENERIC = "To nie jest zwykła roślina.",
			PICKED = "Co za paskudztwo!",
		},
		COOKEDMANDRAKE = "Ogień nie pozbył się tej twarzy. Trochę to straszne.",
		MANDRAKESOUP = "Twarz się nie wygotowała!!",
		MARBLE = "Ale ciężkie!",
		MARBLEPILLAR = "Ciekawe... reszta się spaliła?",
		MARBLETREE = "Najgorszy rodzaj drzewa. Niepalny.",
		MARSH_BUSH =
		{
			BURNING = "Płońcie, wredne ciernie!",
			GENERIC = "Wyglądają na ostre.",
			PICKED = "Ale kłuje!",
		},
		MARSH_PLANT = "Zwykła roślina.",
		MARSH_TREE =
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Ha! I gdzie są teraz twoje kolce?!",
			GENERIC = "Wygląda groźnie!",
		},
		MAXWELL = "Jest taki protekcjonalny.",
		MAXWELLHEAD = "Zdecydowanie lubi dużo gadać.",
		MAXWELLLIGHT = "Wcale nie są fajne. Same się zapalają.",
		MAXWELLLOCK = "Potrzeba jeszcze tylko klucza.",
		MAXWELLTHRONE = "Wygląda na klejący.",
		MEAT = "OGIEŃ mógłby to jeszcze udoskonalić.",
		MEATBALLS = "Mięso uformowane w kulki i udoskonalone ogniem.",
		MEAT_DRIED = "Trochę gumowe, ale może być.",
		MERM = "Fuj, co za oślizgłe paskudztwo.",
		MONSTERLASAGNA = "Makaron, mięso i kępki włosów. Obrzydliwe.",
		MONSTERMEAT = "Pełno tu włosów. Ohyda.",
		MONSTERMEAT_DRIED = "Jest suche i dziwnie pachnie.",
		MOSQUITO =
		{
			GENERIC = "Ale są denerwujące!",
			HELD = "Trzymaj tę gębę z dala ode mnie!",
		},
		MOSQUITOSACK = "Mam krew na rękach.",
		MOUND =
		{
			DUG = "Lepiej on niż ja.",
			GENERIC = "Pewnie jest pełny martwych rzeczy.",
		},
		NIGHTLIGHT = "Trochę jak ogień, tylko fioletowy!",
		NIGHTMAREFUEL = "Fuj! Jeszcze ciepłe!",
		NIGHTSWORD = "Czuję, że moje sny mogą zadać ból w realnym świecie.",
		NITRE = "Wewnątrz kryją się małe eksplozje.",
		ONEMANBAND = "Znam się też na fajerwerkach!",
		PANDORASCHEST = "Trochę tandetna.",
		PANFLUTE = "Muzyka jest taka nudna...",
		PAPYRUS = "Na pewno dobrze się pali!",
		PENGUIN = "Uciekajcie, mali tancerze.",
		PERD = "Podłe ptaszysko! Trzymaj się z dala od moich porzeczek!",
		PEROGIES = "Smaczne jedzonko zapieczętowane ogniem.",
		PETALS = "Głupie kwiaty. Są prawie bezużyteczne.",
		PETALS_EVIL = "Fuj. Kleją się.",
		PICKAXE = "Ma dużo ostrych krawędzi.",
		PIGGYBACK = "Plecak ze świńskich zadków!",
		PIGKING = "Blee. Co za flejtuch.",
		PIGMAN =
		{
			DEAD = "Ciekawe, jak smakują.",
			FOLLOWER = "Ech. Łazi za mną.",
			GENERIC = "Ugh. Nie pachną zbyt pięknie.",
			GUARD = "Nie będzie mi się rządził!",
			WEREPIG = "Stawaj, prosiaku!",
		},
		PIGSKIN = "Ha, ha! Świński zadek.",
		PIGTORCH = "Te prosiaki umieją się bawić!",
		PINECONE = 
		{
		    GENERIC = "Witaj, drzewne nasionko.",
		    PLANTED = "Wkrótce będziesz prawdziwym drzewem.",
		},
		PITCHFORK = "Potrójna ostrość.",
		PLANTMEAT = "Fuj, ale oślizgłe.",
		PLANTMEAT_COOKED = "Ogień ulepsza wszystko.",
		PLANT_NORMAL =
		{
			GENERIC = "Zjem to, jeśli będę musiała.",
			GROWING = "Szybciej, głupia roślino!",
			READY = "O rany. Warzywa.",
			WITHERED = "Suche i łamliwe. Dobre na rozpałkę!",
		},
		POMEGRANATE = "To normalne, że ma w środku tyle części?",
		POMEGRANATE_COOKED = "Dobrze, że nie wybuchł w ogniu.",
		POMEGRANATE_SEEDS = "Mam nadzieję, że nie wybuchną.",
		POOP = "Fuj. Ohydne. Ale użyteczne.",
		PUMPKIN = "Ciekawe, co się stanie, jak potraktuje ją ogniem.",
		SCORCHED_SKELETON = "Bleeeeeeeeee!",
		PUMPKINCOOKIE = "Ciasteczka!!!",
		PUMPKIN_COOKED = "Ogień spisał się całkiem nieźle.",
		PUMPKIN_LANTERN = "Ten ogień w środku jest obłędny.",
		PUMPKIN_SEEDS = "Nasiona najlepszego warzywnego przyjaciela ognia: dyni.",
		PURPLEGEM = "Ale dziwny!",
		RABBIT =
		{
			GENERIC = "Wygląda smacznie.",
			HELD = "Jest tam, gdzie powinien.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Głupie króliki. Wyłaźcie, żebym mogła was zjeść.",
			SPRING = "Głupie króliki pewnie utknęły w środku.",
		},
		RATATOUILLE = "Warzywa. Dużo warzyw.",
		RAZOR = "Po co to w ogóle stworzyłam?",
		REDGEM = "Ale piękny!",
		RED_CAP = "Fajny kolor.",
		RED_CAP_COOKED = "Ogień go odmienił!",
		RED_MUSHROOM =
		{
			GENERIC = "Piękny!",
			INGROUND = "Hej, ty! Wyłaź!",
			PICKED = "Może kiedyś odrośnie.",
		},
		REEDS =
		{
			BURNING = "Płoń! O tak!",
			GENERIC = "Kępka tataraku. Łatwopalnego tataraku.",
			PICKED = "Na nic mi się nie przydadzą resztki tataraku.",
		},
        RELIC = 
        {
            GENERIC = "Stary mebel.",
            BROKEN = "Różne takie śmieci.",
        },
        RUBBLE = "Popsute meble.",
		RESURRECTIONSTONE = "Pewnie powinnam go dotknąć?",
		ROBIN =
		{
			GENERIC = "Rudzik. W kolorze ognia. Niestety nie feniks.",
			HELD = "W kieszeni będzie mu ciepło.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Wydaje się zmarznięty. Na pewno szuka ognia.",
			HELD = "Ale puchaty.",
		},
		ROBOT_PUPPET = "Wyglądają na kompletnie przerażonych.",
		ROCK_LIGHT =
		{
			GENERIC = "Widać wewnątrz ciepło, które tylko czeka, by się uwolnić!",
			OUT = "Wystygło.",
			LOW = "Lawa stygnie.",
			NORMAL = "Jezioro ognia!",
		},
		ROCKS = "Po co miałabym to zbierać?",
        ROOK = "To zamek!",
        ROPE = "Co mogłabym związać?",
		ROTTENEGG = "Fuj! Czemuż, ach czemuż?",
		SANITYROCK =
		{
			ACTIVE = "Ciekawe, co to za znaki.",
			INACTIVE = "Gdzie on się podział?",
		},
		SAPLING =
		{
			BURNING = "Płoń! O tak!",
			WITHERED = "Jest taka sucha. Jakby sama chciała zająć się ogniem.",
			GENERIC = "Powinnam ją zabrać.",
			PICKED = "Biedne małe drzewko.",
		},
		SEEDS = "Rolnictwo jest takie nudne.",
		SEEDS_COOKED = "Już się ich nie zasieje.",
		SEWING_KIT = "Destrukcja jest o tyle fajniejsza!",
		SHOVEL = "Do walki się nie nada.",
		SILK = "Mmmmmm. Mięciutka.",
		SKELETON = "O rany. Mam nadzieję, że odszedł w ognistej chwale.",
		SKELETON_PLAYER = "Aż mi ciarki przeszły.",
		SKULLCHEST = "Ooooch, okropieństwo!",
		SMALLBIRD =
		{
			GENERIC = "Może to nie feniks, ale też jest uroczy.",
			HUNGRY = "Głodny?",
			STARVING = "Dobra, dobra! Rozumiem. Jesteś głodny.",
		},
		SMALLMEAT = "OGIEŃ mógłby to jeszcze udoskonalić.",
		SMALLMEAT_DRIED = "Trochę gumowe, ale może być.",
		SPAT = "Nie podoba mi się twoja morda!",
		SPEAR = "Poczuj mój kłujący gniew.",
		SPIDER =
		{
			DEAD = "Ha! To się doigrałeś!",
			GENERIC = "Jest okropny. Muszę go zabić.",
			SLEEPING = "Mogłabym zabrać go ze sobą.",
		},
		SPIDERDEN = "Okropieństwo.",
		SPIDEREGGSACK = "Mnóstwo małych odrażających pajączków.",
		SPIDERGLAND = "Bleee! Oślizgły i śmierdzący!",
		SPIDERHAT = "Mam nadzieję, że naprawdę nie żyje.",
		SPIDERQUEEN = "Ogień ją unicestwi!",
		SPIDER_WARRIOR =
		{
			DEAD = "Zasłużył sobie.",
			GENERIC = "Mogłabym go zabić... OGNIEM!",
			SLEEPING = "Może lepiej zostawić go w spokoju...",
		},
		SPOILED_FOOD = "Zawsze można je spalić.",
		STATUEHARP = "Ładny posążek. Szkoda by było, gdyby coś mu się stało.",
		STATUEMAXWELL = "Przestaje mi się podobać ten gość.",
		STEELWOOL = "Nawet ona zapłonie od iskry.",
		STINGER = "Kłuje!",
		STRAWHAT = "Kapelusz ze słomy. Można by go użyć na podpałkę.",
		SUNKBOAT = "Jest za daleko. Nie mogę jej nawet podpalić!",
		SWEATERVEST = "Ognista kamizelka byłaby fajniejsza, ale ta też da radę.",
		TAFFY = "Cukier dobrze się pali, ale powinnam to jednak zjeść.",
		TALLBIRD = "Chyba nie chce się przyjaźnić.",
		TALLBIRDEGG = "Ciekawe, czy lubi ogień...",
		TALLBIRDEGG_COOKED = "Ogień działa cuda!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Potrzeba więcej ognia!",
			GENERIC = "Powstań, mój feniksie!",
			HOT = "Czy istnieje w ogóle coś takiego jak nadmiar ognia?",
			LONG = "Ile to jeszcze potrwa?",
			SHORT = "Mam już dość tego czekania.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Temu jajku przydałaby się odrobina ognia!",
			PICKED = "Gniazdo jest puste.",
		},
		TEENBIRD =
		{
			GENERIC = "Chyba mnie rozumie.",
			HUNGRY = "Lubi zjeść.",
			STARVING = "Nie patrz tak na mnie! Zorganizuj sobie coś do jedzenia.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Chcę zobaczyć, jak świat płonie.",
			GENERIC = "Fajnie się świecą te symbole.",
			LOCKED = "Trzeba to jakoś odblokować.",
			PARTIAL = "Tworzę potwora!",
		},
		TELEPORTATO_BOX = "Wydaje się ciepłe.",
		TELEPORTATO_CRANK = "I do czego to to służy?",
		TELEPORTATO_POTATO = "Może dałoby się to przetopić w coś przyjemniejszego dla oka.",
		TELEPORTATO_RING = "Jest zbyt cenne, żeby to spalić!",
		TENTACLE = "Zupełnie nie do przytulania.",
		TENTACLESPOTS = "Fuuuuuj,",
		TENTACLESPIKE = "Kłujący i oślizgły.",
		TENTACLE_PILLAR = "Cała drży.",
		TENTACLE_PILLAR_HOLE = "Co za smród! Następnym razem zapalę zapałkę!",
		TENTACLE_PILLAR_ARM = "Oooch, chcą się przytulać!",
		TENTACLE_GARDEN = "Słyszę cichutkie odgłosy kopania.",
		
		LAVA_POND_ROCK = "Świetnie. Kolejny śmierdzący kamlot!",
		LAVA_POND_ROCK2 = "Świetnie. Kolejny śmierdzący kamlot!",
		LAVA_POND_ROCK3 = "Świetnie. Kolejny śmierdzący kamlot!",
		LAVA_POND_ROCK4 = "Świetnie. Kolejny śmierdzący kamlot!",
		LAVA_POND_ROCK5 = "Świetnie. Kolejny śmierdzący kamlot!",
		LAVA_POND_ROCK6 = "Świetnie. Kolejny śmierdzący kamlot!",
		LAVA_POND_ROCK7 = "Świetnie. Kolejny śmierdzący kamlot!",

		TOPHAT = "Cylinder i zapalniczka. Idealne połączenie.",
		TORCH = "Ogień jest taki piękny.",
		TRAP = "Trochę pasywno-agresywna, ale powinna dać radę.",
		TRAP_TEETH = "Z ogniem byłaby skuteczniejsza.",
		TRAP_TEETH_MAXWELL = "Co za kretyn zostawia na ziemi takie rzeczy?",
		TRINKET_1 = "Ogień, który je stopił, musiał być niesamowicie gorący.",
		TRINKET_10 = "Zęby chyba się zbyt dobrze nie palą.",
		TRINKET_11 = "Oooch, ciekawe, czy ma miotacz ognia.",
		TRINKET_12 = "Wyschła do cna. Chyba leżała za blisko ognia.",
		TRINKET_2 = "Tania podróbka. Pewnie się nawet porządnie nie pali.",
		TRINKET_3 = "Węzeł się zacisnął. Po co komu nóż, jak można użyć ognia?",
		TRINKET_4 = "Wygląda, jakby wykuto go w płomieniach.",
		TRINKET_5 = "Popatrz tylko na te miniaturowe silniki. Tyle mocy!",
		TRINKET_6 = "Nawet nie ma iskier.",
		TRINKET_7 = "Ogień jest fajniejszy.",
		TRINKET_8 = "Nigdy nie lubiłam się kąpać.",
		TRINKET_9 = "Na zamku odpalisz zapałkę, na guzikach już gorzej.",
		TRUNKVEST_SUMMER = "Teraz będę ze swoim przyjacielem już na zawsze.",
		TRUNKVEST_WINTER = "Nie tak ciepła, jak porządny ogień, ale i tak daje radę!",
		TRUNK_COOKED = "Wciąż nie jestem pewna, czy chcę to zjeść.",
		TRUNK_SUMMER = "Cóż... kawałek wciąż nadaje się do przytulania.",
		TRUNK_WINTER = "Jest taka miękka i przytulaśna!",
		UMBRELLA = "Świetny kolor!",
		WAFFLES = "Cześć, goferki!",
		WALL_HAY_ITEM = "Hmmmm. Ciekawe, czy się zapali.",
		WALL_STONE = "Ech. Chyba może być.",
		WALL_STONE_ITEM = "Zaskakująco ciężkie.",
		WALL_RUINS = "I mogą sobie chuchać i dmuchać!",
		WALL_RUINS_ITEM = "Zmieszczą mi się do kieszeni?",
		WALL_WOOD_ITEM = "Nienawidzę się chować.",
		WALL_MOONROCK = "Teraz wygląda bezpiecznie.",
		WALL_MOONROCK_ITEM = "Chyba dałaby radę to podnieść.",
		WALRUS = "Przestań za mną łazić!",
		WALRUSHAT = "Nawet nie najgorszy.",
		WALRUS_CAMP =
		{
			EMPTY = "Nie zamierzam tam wchodzić. Ohyda!",
			GENERIC = "Dlaczego wszyscy mają ładniejsze domy niż ja?",
		},
		WALRUS_TUSK = "Nom, nom, nom.",
		WARDROBE = 
		{
			GENERIC = "Mam ochotę ją podpalić.",
            BURNING = "Tak! Płoń!",
			BURNT = "Ech, ogień się już wypalił.",
		},
		WARG = "Jesteś wielkim, wrednym draniem!",
		WASPHIVE = "Lepiej trzymać się z daleka.",
		WETGOOP = "Dlaczego nie wyszło?! Włożyłam wszystko do ognia i w ogóle.",
		WINTERHAT = "Jak dla mnie trochę za chłodna.",
		WORMHOLE =
		{
			GENERIC = "Trzeba ją dźgnąć patykiem!",
			OPEN = "Ciekawe, czy lubi ostre jedzenie?",
		},
		ACCOMPLISHMENT_SHRINE = "Nienawidzę tej strzałki!", 

		------------------------------------------------------capy--------------------------------
		AERODYNAMICHAT = "Jego delikatne ruchy rozwiewają płomienie.",
		ARMOR_LIFEJACKET = "Czy ochroni moją zapalniczkę przed wodą?",
		ARMOR_SNAKESKIN = "Płaszcz do walki z mugolami.",
		ARMOR_WINDBREAKER = "Wiatr jest wrogiem ognia.",
		ARMORLIMESTONE = "Ale... ciężki.",
		ARMOROBSIDIAN = "Traf mnie i płoń!",
		ARMORSEASHELL = "Kto się teraz odważy ze mną zadrzeć?",
		ARMOUREDBOAT = "Nic nie przegryzie tej łodzi.",
		BABYOX = "Śmierdzisz.",
		BALLPHIN = "Nie wyglądasz na łatwopalnego.",
		BALLPHINPOD = "Rodzina skocznych zwierzów.",
		BAMBOOTREE = "A stick-y shrub.",
		BERRYBUSH2_SNAKE = "Mmmmm. Porzeczki.",--I don't think these should have diff name or examine text
		BERRYBUSH_SNAKE = "Mmmmm. Porzeczki.",--I don't think these should have diff name or examine text
		BIOLUMINESCENCE = "Zimne światło. Zupełnie niepodobne do ognia...",
		BLOWDART_POISON = "Chorobliwy pocałunek.",
		BOAT_LANTERN = "Światło bez płomienia? Nie podoba mi się to.",
		BOTTLELANTERN = "Zimne, obce światło.",
		BURIEDTREASURE = "Jak nie spodoba mi się skarb, po prostu podpalę skrzynię.",
		BUSH_VINE = "I bet these crackle and pop when they burn.",
		SNAKEDEN = "I bet these crackle and pop when they burn.",--I don't think these should have diff name or examine text
		CANNONSHOT = "Ognia!",
		CAPTAINHAT = "Już nie czuję, że spadam na dno.",
		CARGOBOAT = "Ale mi się tu zmieści różnych łatwopalnych rzeczy.",
		CHIMINEA = "Podoba ci się twój domek, ogniku? Nie ma za co.",
		CIRCLINGSEAGULL = "Lećcie do słońca, łajdaki.",
		CLOTHSAIL = "Niezły szew.",
		COCONUT = 
		{
		    GENERIC = "Jadalny drzewny odrost.",
		    PLANTED = "Pospiesz się z tym rośnięciem. Potrzebuję cienia.",
		},
		COCONUT_COOKED = "Mmmm, pychota.",
		COFFEE = "Czuję nagły przypływ motywacji.",
		COFFEEBEANS = "Przydałoby im się trochę ognia.",
		COFFEEBEANS_COOKED = "Ach, ten zapach!",
		COFFEEBUSH = "This bush flourishes near the volcano's fire!",
		CORAL = "Ładne kolory.",
		CORALREEF = "Szkoda, że nie mam maski do nurkowania.",
		CUTLASS = "Trochę śmierdzi ten miecz.",
		DEAD_SWORDFISH = "Blee. Ogień rozprawiłby się z tym smrodem.",
		DEPLETED_BAMBOOTREE = "Jeszcze jakiś bambus? Haalooooo?",
		DEPLETED_BUSH_VINE = "Wróć jeszcze!",
		DOYDOY = "Nie widzę ognia w jego oczach.",
		DOYDOYBABY = "To mały biedaku.",
		DOYDOYEGG = "Głupie jajo.",
		DOYDOYEGG_COOKED = "Usmażenie tego głupiego jajka było całkiem niezłym pomysłem.",
		DOYDOYEGG_CRACKED = "Ta planeta jest coraz głupsza.",
		DOYDOYFEATHER = "Na pewno łatwo się pali.",
		DOYDOYNEST = "Co sekundę gdzieś a świecie wykluwa się taki paskud.",
		DUBLOON = "Piracka mamona!",
		DUG_BAMBOOTREE = "Potrzebujesz ziemi, i to szybko.",
		DUG_BERRYBUSH2 = "Chciałbyś otrzymać nowe życie?",
		DUG_BUSH_VINE = "Chcesz wrócić do ziemi?",
		DUG_COFFEEBUSH = "Już ja wiem, co z wami zrobić.",
		EARRING = "Ale błysk!",
		FABRIC = "Niesamowite, co można zrobić z bambusa.",
		FEATHERSAIL = "Muszę przyznać tym pierzastym bałwanom, że żagle z nich są znakomite.",
		FIRERAIN = "Niech pada!",
		FIRERAINSHADOW = "Już niedługo!",
		FISHINHOLE = "Witajcie, rybeńki!",
		GASHAT = "Chroni przed smrodkiem.",
		GOLDENMACHETE = "Nie chciałabym jej zadrapać.",
		ICEMAKER = "It turns fire into ice. Boo.",
		IRONWIND = "No teraz to można pływać.",
		JELLYFISH = "Trzęsie się jak galareta.",
		JELLYFISH_DEAD = "Już nikogo nie poparzy.",
		JELLYFISH_COOKED = "Wygląda nawet na jadalną.",
		JELLYFISH_PLANTED = "Nazwę cię Mariusz.",
		JELLYJERKY = "Na pewno przyjemnie się żuje.",
		JUNGLETREESEED =
        {
            GENERIC = "Kiedyś będzie pożarem lasu.",
            PLANTED = "Podwaliny pod pożar lasu.",
        },
		LAVAPOOL = "Ach, ta temperatura, ta furia!",
		LIMESTONE = "Stworzony z kruszonych martwych rybek.",
		LIMPETS = "Odrobina ognia i będziecie całkiem smaczne.",
		LIMPETS_COOKED = "Całkiem niezłe!",
		LOBSTERHOLE = "Domek szczęśliwego homara.",
		LOGRAFT = "Drewno do ogniska ma najwyraźniej jeszcze inne zastosowania!",
		MOSQUITO_POISON = "Sio! Uciekać!",
		MUSSEL = "Otwieraj, kolego.",
		MUSSEL_COOKED = "W ogniu od razu są bardziej otwarte.",
		MUSSEL_STICK = "Z jakiegoś powodu małże lubią ten patyk.",
		OBSIDIAN = "Ognisty kamień!",
		OBSIDIAN_WORKBENCH = "Można w nim tworzyć ogniste przedmioty!",
		OBSIDIANAXE = "To dopiero siekiera! Tnie i podpala?!",
		OBSIDIANCOCONADE = "Obsydianowa eksplozja smaku.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Mogłabym się w nie wpatrywać godzinami.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ!",
			LOW = "Ogień jest mały i nudny.",
			NORMAL = "Ale sobie dogadzam!",
			OUT = "Powinnam przywrócić ogień do życia.",
		},
		OBSIDIANMACHETE = "Ognista maczeta to najlepsza przyjaciółka każdej dziewczynki.",
		SPEAR_OBSIDIAN = "Ja kuję, oni płoną!",
		OBSIDIANSPEARGUN = "Ogień to mój żywioł!",
		PACKIM = "Przyjaciel czy wróg?",
		PACKIM_FISHBONE = "Wygląda dość znacząco.",
		PALMLEAF = "Spłoniesz!",
		PALMTREE_BURNT = "Ależ cudowny zapach.",
		PALMTREE_STUMP = "Kolejna poległa.",
		PARROT = "Ależ cudowny, ognistoczerwony kolor.",
		PIRATEHAT = "Czuję się jak prawdziwy pirat.",
		PIRATIHATITATOR = "Cursed pirate magic?",
		POISONHOLE = "Natura jest obrzydliwa.",
		RAFT = "Podpalenie jej na pełnym morzu chyba nie będzie dobrym pomysłem.",
		ROWBOAT = "Mam wiosłować? Naprawdę?",
		SAIL = "Wykorzystuje siłę wiatru.",
		SAND = "Piasek. Wielkie mi rzeczy.",
		SANDBAG = "Worek pełen piasku.",
		SANDBAG_ITEM = "Więc mam to położyć na ziemi?",
		SANDHILL = "O! Piasek!",
		SEAGULL = "Ciekawe, czy boi się ognia... Bo powinna.",
		SEASACK = "Mam założyć to mokre coś na plecy?",
		SEASHELL = "Jakaś głupia muszelka.",
		SEASHELL_BEACHED = "Jakaś głupia muszelka.",
		SEATRAP = "No dalej! Wpływajcie! Patrzcie, jak tam przytulnie!",
		SEAWEED = "Przemoczona morska trawa.",
		SEAWEED_COOKED = "Po zastosowaniu ognia całkiem niezłe.",
		SEAWEED_DRIED = "Zdrowa suszonka.",
		SEAWEED_PLANTED = "Przemoczona morska trawa.",
		SHARX = "Pływające łajdaki.",
		SLOTMACHINE = "Straszna strata czasu...",
		SNAKE = "Jadowity ślizgacz.",
		SNAKE_FIRE = "Mamy podobne zainteresowania, śliski przyjacielu.",
		SNAKESKIN = "Zdarta z prawdziwego węża.",
		SNAKESKINHAT = "Woda się go nie ima.",
		SPEAR_POISON = "Mam nadzieję, że się nie nadzieję.",
		SPEARGUN = "Doskonały na morskie wyprawy.",
		SPEARGUN_POISON = "Nie wiem, czy tak w ogóle można.",
		STUNGRAY = "Nic mnie już nie zaskoczy w kwestii zapachów.",
		SUPERTELESCOPE = "Widzę kraniec Ziemi.",
		SWORDFISH = "Do boju!",
		TELESCOPE = "Teraz się nie ukryjecie, wysepki!",
		TIGERSHARK = "Moje koszmary się ziściły!",
		TIGERSHARKSHADOW = "Niedobrze! Niedobrze!",
		TOUCAN = "Fajny masz kinol.",
		TRAWLNET = "Złapię nim trochę przemoczonych szpargałów.",
		TRAWLNETDROPPED = "Everything is going to be wet in there.",
		TREEGUARD = "Nie lubię cię. A ty nie lubisz mnie.",
		TRIDENT = "Mokry na wskroś.",
		TRINKET_13 = "Ogień w płynie? Jest pomarańczowy...",
		TRINKET_14 = "Nie mam szpilek...",
		TRINKET_15 = "O, na pewno świetnie się pali.",
		TRINKET_16 = "Śmieci to zło.",
		TRINKET_17 = "Nie moje klimaty.",
		TRINKET_18 = "Ciekawe, czy jest coś warta...",
		TRINKET_19 = "Zaćmienia umysłowego? Brzmi dość drastycznie.",
		TURBINE_BLADES = "Co one robią?",
		TURF_BEACH = "Gleba jest taka nudna.",
		TURF_JUNGLE = "Gleba jest taka nudna.",
		VENOMGLAND = "Obrzydlistwo! Szkoda, że nie mam rękawiczek.",
		VINE = "Chyba mogłabym to do czegoś wykorzystać. Albo po prostu spalić.",
		VOLCANO = "Największy, najogniowszy ogień na całym świecie!",
		VOLCANO_ALTAR = "Why would I wanna appease the volcano? Then it wouldn't shoot fire!",
		VOLCANO_ALTAR_BROKEN = "Nie sposób już teraz zaspokoić głodu wulkanu.",
		VOLCANO_EXIT = "Smutno będzie odchodzić...",
		VOLCANOSTAFF = "Jestem boginią ognistego zniszczenia!",
		WALL_LIMESTONE = "Strasznie nierówny.",
		WALL_LIMESTONE_ITEM = "Chyba nie pali się zbyt ławo.",
		WHALE_BLUE = "Nawet nie wiedziałam, że robią takie duże ryby.",
		WHALE_CARCASS_BLUE = "Zaczyna się psuć... Ohyda.",
		WHALE_CARCASS_WHITE = "Zwycięstwo wcale nie pachnie najlepiej...",
		WHALE_WHITE = "Widzę ogień w jego oczach!",
		CRABHOLE = "Wyjdź się pobawić!",
		CRAB =
		{
			GENERIC = "Przestań uciekać!",
			HIDDEN = "Założę się, że siedzi tam jakiś krablik.",
		},
		BERMUDATRIANGLE = "Trochę mi się w głowie kręci od samego patrzenia.",
		BOATCANNON = "Ciekawe, czy da się tym rozpalić ogień...",
		BOATREPAIRKIT = "Załatwmy wszystkie dziury.",
		MACHETE = "Łatwiej byłoby wypalić sobie drogę ogniem.",
		LUGGAGECHEST = "Ooo! Mam nadzieję, że znajdę w środku coś przydatnego.",
		DRAGOON = "Gdybym tylko znalazła sposób, żeby jakiegoś wytresować....",
		ANTIVENOM = "Przyda się, gdyby mnie coś kiedyś otruło.",
		BAMBOO = "Wygląda na łatwopalną.",
		FROG_POISON = "Fuj! Nie zbliżaj się do mnie.",
		OX = "Kawał z ciebie zwierza.",
		PEACOCK = "Piękny!",
		SEAGULL_WATER = "Zamknij dziób.",
		SNAKE_POISON = "Nie podobają mi się te kły...",
		SOLOFISH = "Nie wygląda na specjalnie rozgarniętą.",
		SPOILED_FISH = "Obrzydliwe.",
		TWISTER = "Trzymaj się z dala od moich bezcennych płomieni!",
		SAND_CASTLE =
		{
			GENERIC = "Całkiem uroczy.",
			SAND = "To zamek zrobiony z piasku! Piaskowy zamek!",
		},
		SNAKEOIL = "Jakoś nie jestem przekonana.",
		LOBSTER = "No chodź, paskudzie!",
		MESSAGEBOTTLE = "Zabutelkowany papier.",
		MESSAGEBOTTLEEMPTY = "Butelka.",
		SHARK_FIN = "Komuś odpadła płetwa.",
		VOLCANO_ALTAR =
		{
		 	GENERIC = "Ołtarz bogów ognia!",
		 	OPEN = "Gotowy do przyjęcia ognia!",
		},
		ELEPHANTCACTUS = "Nie ocieraj się o mnie!",
		ELEPHANTCACTUS_ACTIVE = "Aaauć!",
		ELEPHANTCACTUS_STUMP = "I tak masz leżeć!",
		DOUBLE_UMBRELLAHAT = "Dzieło chorego umysłu.",
		MUSSEL_FARM =
		{
			GENERIC = "No nie sięgnę.",
			STICKPLANTED = "Wkrótce będziecie moi.",
		},
		WOODLEGS_CAGE = "Wydaje się trochę sztywny.",

		 PIRATIHATITATOR =
		 {
		 	GENERIC = "To już przegięcie.",
		 	BURNT = "Teraz jest trochę bardziej w moim stylu.",
		 },
		 COFFEEBUSH =
		 {
		 	BARREN = "Nie będzie już z niego ani kropli.",
		 	PICKED = "Ach, a chciałam jeszcze łyka...",
		 	WITHERED = "Potrzebuje popiołu i miłości. Głównie popiołu.",
		 	GENERIC = "Gorąca lawa, gorąca kawa!",
		 },
		 DUG_ELEPHANTCACTUS = "Nie trzeba cię podlewać, prawda?",
		 WHALE_BUBBLES = "Skąd te bąbelki?",

		ARMORCACTUS = "Mogę wtopić się w tłum kaktusów.",
		BAMBOOTREE =
		{
			BURNT = "Ech. Mogę go spalić jeszcze raz?",
			CHOPPED = "Jeszcze odrośnie.",
			GENERIC = "Podpałka!",
		},
		BLOWDART_FLUP = "Trochę dmucha.",
		BLUBBER = "Na pewno płonie na niebiesko!",
		BLUBBERSUIT = "Trochę skrzypi, jak chodzę...",
		BOAT = "Nie wiem, czy zdołam się powstrzymać, żeby jej nie podpalić.",
		BOAT_TORCH = "Woda i ogień w jednym spali domku.",
		BRAINJELLYHAT = "Czuję się mądrzejsza, ale jakim kosztem...",
		BUOY = "Boja. Cieszę się, że ją mam.",
		BUSH_VINE =
		{
			BURNT = "Fajnie się palą!",
			CHOPPED = "Tak się je rozplątuje.",
			GENERIC = "Na pewno strzelają w ogniu.",
		},
		COCONADE =
		{
			BURNING = "No i proszę...",
			GENERIC = "Najpierw bum, potem auć.",
		},
		COCONUT_HALVED = "Aha! Teraz można cię zjeść!",
		COFFEEBOT = "Robi kawę!",
		COMPASS =
		{
			E = "Wschód!",
			GENERIC = "Coś nie chce działać.",
			N = "Północ!",
			NE = "Północny wschód!",
			NW = "Północny zachód!",
			S = "Południe!",
			SE = "Południowy wschód!",
			SW = "Południowy zachód!",
			W = "Zachód!",
		},
		CORAL_BRAIN = "Mogłabym nawet polubić ten smak...",
		CORAL_BRAIN_ROCK = "Genialny pomysł, chować się w tych głupich, zwykłych koralowcach.",
		CRATE = "Spaliłabym ją. I wszystko wewnątrz...",
		DEPLETED_GRASS =
		{
			GENERIC = "Cóż za żałosna... kępka trawy?",
		},
		DEPLETED_GRASS_WATER = "Odpoczywa sobie.",
		DRAGOONDEN = "Mieszkają tu gorące chłopaki.",
		DRAGOONEGG = "Ten gorący kamień tak naprawdę jest chyba gorącym jajem.",
		DRAGOONHEART = "Nie ma to jak ciepły posiłek.",
		DRAGOONSPIT = "Płonąca kałuża obrzydliwości.",
		FISH_RAW = "Potrzeba... ognia!",
		FISH_RAW_SMALL = "Lubię sushi... ale wolę opiekane w ogniu.",
		FISH_RAW_SMALL_COOKED = "Ryby i ogień to doskonałe połączenie.",
		FLAMEGEYSER = "Rozkosz dla oczu...",
		FLOTSAM = "One są tam, a ja tutaj...",
		FLUP = "Odflupuj się ode mnie!",
		FRESHFRUITCREPES = "O, la, la.",
		GRASS_WATER = "Nie trzeba jej podlewać.",
		HAIL_ICE = "Ech, to weź już stopniej.",
		HOME = "Ciekawe, kto tu mieszka.",
		ICEMAKER =
		{
			HIGH = "Ma pełno paliwa!",
			LOW = "Potrzebuje więcej paliwa.",
			NORMAL = "Więcej lodu!",
			OUT = "Skończyło się paliwo.",
			VERYLOW = "Prawie skończyło się paliwo.",
		},
		JUNGLETREE =
		{
			BURNING = "Wooow! To się nazywa ogień!",
			BURNT = "Tak jest znacznie lepiej.",
			CHOPPED = "Trzeba się było trochę namachać.",
			GENERIC = "Pokaźne drzewo. Będzie się długo palić!",
		},
		KNIGHTBOAT = "Sprawdź sobie łódź, kolego.",
		KRAKEN = "Ogień ją unicestwi!",
		KRAKENCHEST = "Pełna skarbów z głębin?",
		KRAKEN_TENTACLE = "Ble, trzymaj się z daleka!",
		LIMPETROCK =
		{
			GENERIC = "Obrzydliwe żarcie próbuje zjeść ten głaz.",
			PICKED = "Głaz będzie miał spokój na jakiś czas.",
		},
		LIVINGJUNGLETREE = "Jakieś dziwne to drzewo.",
		LOBSTER_DEAD = "Szczypie w język.",
		LOBSTER_DEAD_COOKED = "Homar na obiad! Niech mnie ktoś uszczypnie!",
		MAGIC_SEAL = "Ale się świeci.",
		MAGMAROCK = "Magmastyczny!",
		MAGMAROCK_FULL = "Magmastyczny!",
		MAGMAROCK_GOLD = "Magmastyczny!",
		MAGMAROCK_GOLD_FULL = "Magmastyczny!",
		MANGROVETREE = "Przynajmniej nie trzeba go podlewać.",
		MANGROVETREE_BURNT = "Spalone do... eee... wody.",
		MARSH_PLANT_TROPICAL = "Roślinka.",
		MERMFISHER = "Ugh! Zapachu ryb chyba nie da się pozbyć.",
		MERMHOUSE_FISHER = "Wszystko kręci się tu wokół ryb.",
		MONKEYBALL = "Małpie wygłupy.",
		MONSTERTARTARE = "Ohyda!",
		MOSQUITOSACK_YELLOW = "Coś odrażającego to zostawiło.",
		MUSSELBOUILLABAISE = "Mmmm. Pachnie świetnie!",
		MYSTERYMEAT = "Rodzicielstwo jest obrzydliwe.",
		NEEDLESPEAR = "Mogłabym o niej gadać cały dzień.",
		OCTOPUSCHEST = "Pełno w niej morskich przekąsek!",
		OCTOPUSKING = "Chyba trochę przysypia.",
		OXHAT = "Nie dla jeleni.",
		OX_FLUTE = "Słyszę nadciągający sztorm.",
		OX_HORN = "Ciekawe, gdzie się podział drugi.",
		PALMLEAF_HUT = "Chroni przed działaniem żywiołów. Ale chyba nie wszystkich...",
		PARROT_PIRATE = "Ty skrzeczący łobuzie.",
		PEG_LEG = "Nie mogę dojść, co to takiego.",
		PIGTENT = "Śmierdzi niemiłosiernie!",
		PIKE_SKULL = "Paskudne.",
		PIRATEGHOST = "Niech cię kule biją!",
		PIRATEPACK = "Wyrobię sobie mięsnie.",
		PORTAL_SHIPWRECKED = "Czas się ewakuować.",
		PRIMEAPE = "Hej, kolego! Też lubisz bawić się ogniem?",
		PRIMEAPEBARREL = "Małpi raj.",
		RAWLING = "Dotrzymuje mi towarzystwa.",
		REDBARREL = "Takie beczki to ja lubię!",
		ROCK_CHARCOAL = "It drops burned things!",
		ROCK_OBSIDIAN = "This rock makes me so excited, I just want to explode!",
		SAIL_STICK = "Jestem królową tej łooooodzi!",
		SANDBAGSMALL = "Na swój sposób chroni przed wodą.",
		SANDBAGSMALL_ITEM = "Na swój sposób chroni przed wodą.",
		SHADOWSKITTISH_WATER = "A to co??",
		SHARKITTEN = "Hej, słodziaku, gdzie masz mamusię?",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Mój wykrywacz rekinów zaczyna szaleć.",
			INACTIVE = "Co to za wydma?",
		},
		SHARK_GILLS = "Chyba już mu się nie przydadzą...",
		SHARK_TEETHHAT = "Ale mam teraz szeroki uśmiech.",
		SHIPWRECKED_ENTRANCE = "Nadchodzę!",
		SHIPWRECKED_EXIT = "Spadam stąd.",
		SNAKEDEN =
		{
			BURNT = "Fajnie się palą!",
			CHOPPED = "Tak się je rozplątuje.",
			GENERIC = "Na pewno strzelają w ogniu.",
		},
		SNAKESKINSAIL = "Makabra.",
		SPEAR_LAUNCHER = "Jedyna rzecz lepsza od włóczni to wyrzutnia włóczni.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Gdzie się wszyscy podziali?",
			GENERIC = "Ktoś gdzieś jest kompletnie mokry.",
		},
		SUNKEN_BOAT_BURNT = "Podwójne ups.",
		SUNKEN_BOAT_TRINKET_1 = "Nie umiem tego wymówić!",
		SUNKEN_BOAT_TRINKET_2 = "Wyrosłam już z zabawek...",
		SUNKEN_BOAT_TRINKET_3 = "Na pewno chętnie pozna moją zapalniczkę.",
		SUNKEN_BOAT_TRINKET_4 = "Nie mam pojęcia, co to jest.",
		SUNKEN_BOAT_TRINKET_5 = "Nie mój rozmiar.",
		SWEETPOTATOSOUFFLE = "Przyrządzony wręcz idealnie!",
		SWEET_POTATO = "Doskonała odmiana od porzeczek.",
		SWEET_POTATO_COOKED = "Ogień ma na nie zbawienny wpływ.",
		SWEET_POTATO_PLANTED = "W ogniu wyglądałby korzystniej!",
		SWEET_POTATO_SEEDS = "Nasiona. Słodkie nasiona.",
		SWIMMINGHORROR = "Potrafisz pływać? To straszne!",
		TELEPORTATO_SW_BASE = "Chyba brakuje jakiegoś elementu.",
		TELEPORTATO_SW_BOX = "Element jakiego czegoś.",
		TELEPORTATO_SW_CRANK = "Do kręcenia?",
		TELEPORTATO_SW_POTATO = "Ciekawe, do czego to służy.",
		TELEPORTATO_SW_RING = "To chyba do czegoś pasuje...",
		THATCHPACK = "Ciekawe, czy te liście dobrze się palą.",
		TIDALPOOL = "Ciekawe, w którą stronę by się obracał, gdyby wyjąć korek.",
		TIDAL_PLANT = "Zwykła roślina.",
		TIGEREYE = "Nie patrz tak na mnie!",
		TRAWLNETDROPPED =
		{
			GENERIC = "Cóż się tam kryje...",
			SOON = "Zaraz zatonie!",
			SOONISH = "Siatka chyba tonie.",
		},
		TREASURECHEST_TRAP = "Podła sztuczka!",
		TRINKET_20 = "Nie umiem tego wymówić!",
		TRINKET_21 = "Wyrosłam już z zabawek...",
		TRINKET_22 = "Na pewno chętnie pozna moją zapalniczkę.",
		TRINKET_23 = "Zepsute co?",
		TROPICAL_FISH = "Pięknie ubarwiona.",
		TUNACAN = "A ja akurat lubię z piłkofinem...",
		TURF_ASH = "Produkt uboczny spalania.",
		TURF_MAGMAFIELD = "Wybuchowa!",
		TURF_MEADOW = "Całkiem przyjemna.",
		TURF_SNAKESKINFLOOR = "Obrzydliwe.",
		TURF_TIDALMARSH = "Grząska.",
		TURF_VOLCANO = "Ogrzewanie podłogowe.",
		TWISTER_SEAL = "Zachodni wiatr spienione fale goni.",
		VOLCANO_ALTAR_TOWER = "Zbudowany na chwałę ognia!",
		VOLCANO_SHRUB = "You come pre-burnt!",
		WALLYINTRO_DEBRIS = "Ja to zrobiłam?",
		WATERYGRAVE = "Ktoś się zalał w trupa.",
		WHALE_TRACK = "Nie ma bąbelków bez ognia. A nie, to chyba nie tak szło...",
		WILBUR_CROWN = "Trzeba mieć naprawdę małą głowę...",
		WILBUR_UNLOCK = "Śmieszna małpka.",
		WILDBORE = "Jakoś mnie nie kręci przebywanie koło niego.",
		WILDBOREHEAD = "Ble!",
		WILDBOREHOUSE = "Wystarczy odrobina ognia i mamy grilla.",
		WIND_CONCH = "Mam nadzieję, że nie zgasi żadnego ognia.",
		WOODLEGSBOAT = "Porządna łajba.",
		WOODLEGSHAT = "Chyba nie został zrobiony dla mnie.",
		WOODLEGSSAIL = "Ten żagiel chyba był komuś bardzo drogi.",
		WOODLEGS_KEY1 = "Klucz do czego?",
		WOODLEGS_KEY2 = "Coś gdzieś pewnie czeka w zamknięciu.",
		WOODLEGS_KEY3 = "Kolejny klucz.",
		WRECK = "Ktoś ma teraz srogie wyrzuty sumienia...",
		CALIFORNIAROLL = "O raju! Ryba zawinięta w wodorosty.",
		BANANAPOP = "Odwrotność ognia.",
		BISQUE = "Chyba mogłabym to zjeść.",
		CEVICHE = "Ale oślizgłe...",
		SEAFOODGUMBO = "Fuj, co to w ogóle jest?",
		SURFNTURF = "Ugh. To jest jedzenie dla staruszków!",
		SHARKFINSOUP = "Nawet nie przypaliłam.",
		LOBSTERDINNER = "Mniammmmmm!",
		LOBSTERBISQUE = "Zjem wszystko i wyliżę miseczkę!",
		JELLYOPOP = "Poproszę dwadzieścia!",
		VOLCANO_SHRUB = "To niesprawiedliwe! Ja chciałam cię spalić!",
		ROCK_OBSIDIAN = "Najpiękniejszy... kamień... jaki... w życiu... widziałam...",
		ROCK_CHARCOAL = "Czarno to widzę.",
	},
	DESCRIBE_TOODARK = "Więcej światła!",
	DESCRIBE_GENERIC = "Aż się prosi, żeby to spalić.",
	DESCRIBE_SMOLDERING = "Hurra! Zaraz zajmie się ogniem!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Ughhhh!",
	},
}