return{
	ACTIONFAIL = 
	{
		REPAIRBOAT =
		{
			GENERIC = "修理するとこ、ないネ",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "起きてるあいだは、ムリでしょうネ",
			GENERIC = "毛が生えてないネ",
			NOBITS = "もう、毛が生えてないネ",
		},
		STORE =
		{
			GENERIC = "これ以上は、入らないネ",
			NOTALLOWED = "そこには、入れられないネ",
		},
		RUMMAGE =
		{	
			GENERIC = "今はダメだヨ",	
		},
        COOK =
        {
            GENERIC = "まだ準備ができてないヨ",
            TOOFAR = "もっと近くへ寄らなきゃダメだヨ",
        },
        GIVE =
        {
            DEAD = "アワワ…",
            SLEEPING = "寝ている。",
            BUSY = "忙しそうネ",
        },
        WRITE =
        {
            GENERIC = "今は手が汚れてるから、あとにするヨ",
        },
        CHANGEIN =
        {
            GENERIC = "服を着替えるなんて発想、なかったヨ",
            BURNING = "アララ～…燃えちゃってるネ",
        },
		TEACH =
        {
            KNOWN = "もう知ってるヨ",
            CANTLEARN = "ボクには理解不能だヨ",
        },
	},
	ACTIONFAIL_GENERIC = "それは、できないヨ",
	ANNOUNCE_MAGIC_FAIL = "残念…ダメみたいだヨ",
	ANNOUNCE_ACCOMPLISHMENT = "やったヨ～！！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "このうれしいキモチ…ずっと続くとイイネ…",
	ANNOUNCE_ADVENTUREFAIL = "また挑戦するしかないネ",
	ANNOUNCE_BEES = "ハチミツの虫に追っかけられるヨ！",
	ANNOUNCE_BOAT_DAMAGED = "船、少し壊れたネ…",
	ANNOUNCE_BOAT_SINKING = "そんな…空腹のまま死ぬのはイヤだヨ！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "スープにドボン！",
	ANNOUNCE_BOOMERANG = "イタッ！もうッ！",
	ANNOUNCE_BURNT = "黒焦げネ…",
	ANNOUNCE_CANFIX = "あれは…修理できそうネ",
	ANNOUNCE_CHARLIE = "ハッ！ナニ、今の…！？",
	ANNOUNCE_CHARLIE_ATTACK = "ヒャァッ！かみつかれたヨッ！",
	ANNOUNCE_COLD = "ウウ…冷凍焼けしちゃいそうネ…",
	ANNOUNCE_CRAB_ESCAPE = "ディナーの食材…！逃げちゃったヨ…",
	ANNOUNCE_CRAFTING_FAIL = "材料、足りないネ",
	ANNOUNCE_DAMP = "ちょっと、しっとりしちゃったネ…",
	ANNOUNCE_WET = "すっかり、びしょぬれだヨ",
	ANNOUNCE_WETTER = "ボクの体、水に溶けたらドウシヨウ！？",
	ANNOUNCE_DEERCLOPS = "ナニ！？なんの音！？",
	ANNOUNCE_DUSK = "もうすぐディナーの時間ネ",
	ANNOUNCE_EAT =
	{
		GENERIC = "トレビアン！",
		INVALID = "どう見ても、食べ物じゃないネ",
		PAINFUL = "ウッ…おなかが痛いヨ…",
		SPOILED = "ウグッ…食べるんじゃなかったヨ…",
		STALE = "賞味期限、切れてたネ…",
		PREPARED = "おいしゅうございマス！",
		SAME_OLD_1 = "そろそろ、あきてきたネ…",
		SAME_OLD_2 = "味気ないネ…",
		SAME_OLD_3 = "そろそろ別のものが食べたいネ…",
		SAME_OLD_4 = "もうあきたネ…",
		SAME_OLD_5 = "同じものばかり…もうウンザリだヨ！",
		TASTY = "ン～！トレビア～ン！！",
		COOKED = "洗練された味…とは言えないネ…",
		DRIED = "ちょっとパサついてるネ…",
		RAW = "やっぱり、料理しないとおいしくないネ…",
		YUCKY = "食べろと言われただけで不快だヨ",
	},
	ANNOUNCE_OTHER_WORLD_PLANT = "この世界じゃ、育たなそうネ",
	ANNOUNCE_ENTER_DARK = "真っ暗ネ…",
	ANNOUNCE_ENTER_LIGHT = "夜明けとともに、新しい1日が始まるヨ…",
	ANNOUNCE_FREEDOM = "自由になったヨ～～～！！",
	ANNOUNCE_HIGHRESEARCH = "脳ミソがジンジンするネ！",
	ANNOUNCE_HOT = "暑くて、脳ミソがスフレになりそうだヨ…",
	ANNOUNCE_HOUNDS = "あれは…空腹の音ネ…",
	ANNOUNCE_HUNGRY = "食べ物…恋しいネ…",
	ANNOUNCE_HUNT_BEAST_NEARBY = "獲物が近いネ…",
	ANNOUNCE_HUNT_LOST_TRAIL = "足跡、見失ったヨ…",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "雨で足跡、消えちゃってるヨ…",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "肥料、足りてないみたいネ…",
	ANNOUNCE_INV_FULL = "もう、これ以上は持てないヨ",
	ANNOUNCE_KNOCKEDOUT = "ウウ…目がまわるヨ…",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "フゥ！危なかったネ！",
	ANNOUNCE_LOWRESEARCH = "特に新しいことは、学べなかったネ",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "この先ヘ進んだら、もう戻れないネ…",
	ANNOUNCE_MAPWRAP_RETURN = "世界の果てから、再登場だヨ！",
	ANNOUNCE_MAPWRAP_WARN = "うーん…ゴリムチューだヨ…",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"インクが、にじんでしまっているヨ…",
	},
	ANNOUNCE_MORETREASURE = "またお宝だネ！",
	ANNOUNCE_MOSQUITOS = "病気を運ぶ虫だヨ！",
	ANNOUNCE_NODANGERSIESTA = "いま目をつぶると、危険だヨ！",
	ANNOUNCE_NODANGERSLEEP = "寝てる間に死ぬは、ゴメンだヨ！",
	ANNOUNCE_NODAYSLEEP = "明るすぎて眠れないヨ",
	ANNOUNCE_NODAYSLEEP_CAVE = "疲れてはいない。",
	ANNOUNCE_NOHUNGERSIESTA = "まずは、おなかを満たしてからネ",
	ANNOUNCE_NOHUNGERSLEEP = "おなかがカラッポで、眠れないヨ…",
	ANNOUNCE_NONIGHTSIESTA = "昼寝は昼にするものネ",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "こんなとこでは、昼寝したくないヨ…",
	ANNOUNCE_NOSLEEPONFIRE = "あったかいベッドはいいけど…熱すぎネ！",
	ANNOUNCE_NO_TRAP = "簡単に開いたネ",
	ANNOUNCE_OTHER_WORLD_TREASURE = "この世界にはない場所の地図カナ…？",
	ANNOUNCE_PECKED = "イタイッ！ヤメテ！",
	ANNOUNCE_QUAKE = "不穏な音ネ…",
	ANNOUNCE_RESEARCH = "人間、一生勉強ネ",
	ANNOUNCE_SHARX = "あいつら…ボクを襲う気まんまんネ…",
	ANNOUNCE_SHELTER = "木が守ってくれるヨ…ありがとネ…",
	ANNOUNCE_SOAKED = "キッチンの布巾より、びしょぬれだヨ！",
	ANNOUNCE_THORNS = "イタイッ！",
	ANNOUNCE_FAN_OUT = "粉々になっちゃったヨ！",
    ANNOUNCE_COMPASS_OUT = "んー、壊れたみたいネ",
	ANNOUNCE_TOOL_SLIP = "ツルツルすべるヨ…",
	ANNOUNCE_TORCH_OUT = "明かり、消えちゃったヨ！？",
	ANNOUNCE_TRAP_WENT_OFF = "もうッ！",
	ANNOUNCE_TRAWL_FULL = "たくさん、かかったヨ！",
	ANNOUNCE_TREASURE = "宝の地図かもネ！",
	ANNOUNCE_UNIMPLEMENTED = "まだ、使えないヨ",
	ANNOUNCE_VOLCANO_ERUPT = "アブナイヨ～！",
	ANNOUNCE_WAVE_BOOST = "ヒュー！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "大物が近いヨ！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "大物に逃げられたヨ！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "波が荒くて、泡が見えないヨ！",
	ANNOUNCE_WORMHOLE = "ムショーに飛び込んでみたくなるヨ…",
	BATTLECRY =
	{
		GENERIC = "肉のカットなら、得意だヨ！",
		PIG = "耳からシッポまで、おいしく食べてやるッ！",
		PREY = "キミ、おいしそうネ！",
		SPIDER = "スパイダーロールにしてやるゾ！",
		SPIDER_WARRIOR = "害虫は駆除してやるゾ！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "逃げるが勝ちだヨ！",
		PIG = "ボクのブタ肉～！待ってヨ～！",
		PREY = "フゥ、息が切れちゃったヨ",
		SPIDER = "かみつかれてないカナ…",
		SPIDER_WARRIOR = "フゥ…あぶなかったネ…",
	},
	DESCRIBE =
	{
		INVENTORYGRAVE = "来世はもっといい人生になるといいネ",
		INVENTORYMOUND = "来世はもっといい人生になるといいネ",
		ACCOMPLISHMENT_SHRINE = "やっと、偉業を達成できたヨ！",
		ACORN =
		{
			GENERIC = "カラカラ音がするネ",
			PLANTED = "新しい命の始まりネ",
		},
		ACORN_COOKED = "これは…ひどい味ネ…",
		ADVENTURE_PORTAL = "なんともアヤシイ装置ネ…",
		AERODYNAMICHAT = "これをかぶると、すばやく歩けるネ",
		AMULET = "着用型の安全装置だヨ",
		ANCIENT_ALTAR = "古代の装置ネ…",
		ANCIENT_ALTAR_BROKEN = "壊れてるヨ…",
		ANCIENT_STATUE = "ビリビリ震えてる…？ブキミだヨ",
		ANIMAL_TRACK = "たどっていけば、獲物がいるはずだヨ…",
		ANTIVENOM = "これ持ってれば、安心ネ",
		ARMORDRAGONFLY = "重いし、熱いヨ",
		ARMORGRASS = "干し草で、身を守れるノ…？",
		ARMORLIMESTONE = "着れば、石みたいに強くなれるネ！",
		ARMORMARBLE = "すごく重いヨ",
		ARMOROBSIDIAN = "重いし、熱いヨ",
		ARMORRUINS = "むか～しむかしのよろいネ",
		ARMORSEASHELL = "貝殻でできたよろいネ",
		ARMORSLURPER = "これを着ると、空腹がまぎれるヨ",
		ARMORSNURTLESHELL = "カメの甲羅みたいネ",
		ARMORWOOD = "丈夫だけど、燃えやすいネ",
		ARMOR_LIFEJACKET = "万が一のときのためにネ",
		ARMOR_SANITY = "こんなの着るなんて、どうかしてるカナ？",
		ARMOR_SNAKESKIN = "機能的でオシャレ！害獣駆除もできたしネ",
		ARMOR_WINDBREAKER = "風をブレイクする？どういうことカナ？",
		ARMOUREDBOAT = "これなら、外海に出ても安心ネ",
		ASH =
		{
			GENERIC = "灰をまぶしたチーズ…恋しいネ…",
			REMAINS_EYE_BONE = "移動中に、灰になってしまったヨ",
			REMAINS_GLOMMERFLOWER = "フシギな花、灰になっちゃったヨ…",
			REMAINS_THINGIE = "これじゃ、もう使えないネ",
		},
		AXE = "とっても頼りになる道具ネ",
		BABYBEEFALO = "まるまる太った成獣になるといいネ",
		BABYOX = "今日は子牛肉食べたい気分じゃないヨ",
		BACKPACK = "背中を任せられる相棒ネ",
		BACONEGGS = "黄身は半熟…ベーコンはカリカリ…至福ネ…",
		BALLPHIN = "イルカくん、元気ネ",
		BAMBOO = "タケノコご飯、食べたいネ…",
		BAMBOOTREE =
		{
			BURNT = "はぁ…もったいないネ…",
			CHOPPED = "そのうちまた、生えてくるヨ",
			GENERIC = "ライスを竹の皮に包んで蒸すと美味だヨ",
		},
		BANDAGE = "応急処置グッズネ",
		BASALT = "とっても硬いネ！",
		BAT = "“バット”で殴ってやりたいネ…",
		BATBAT = "なんとも恐ろしい道具ネ…",
		BATWING = "いいダシ、出るカナ…？",
		BATWING_COOKED = "ニンニクがあれば、おいしくなるカモ…？",
		BEARDHAIR = "キモチ悪いネ…",
		BEARGER = "ウワッ…！こっち来ないでッ！",
		BEARGERVEST = "モフモフ…寒い日も安心ネ",
		BEARGER_FUR = "あったかいネ",
		BEDROLL_FURRY = "ホッとする。",
		BEDROLL_STRAW = "チクチクするけど、地面に寝るよりマシだヨ",
		BEE =
		{
			GENERIC = "ハチミツくん、発見！",
			HELD = "ハチミツくん！",
		},
		BEEBOX =
		{
			BURNT = "カラメル作り、失敗ネ",
			FULLHONEY = "ハチミツ、ゲットだヨ！",
			GENERIC = "ハチミツくんたちの、おうちだヨ！",
			NOHONEY = "ハチミツ、からっぽだヨ…",
			SOMEHONEY = "ハチミツ、ちょっとしか入ってないネ",
		},
		BEEFALO =
		{
			FOLLOWER = "そうそう！ボクについといでヨ！",
			GENERIC = "これでビーフが食べられるネ",
			NAKED = "ダイジョウブ、毛はすぐ生えてくるヨ",
			SLEEPING = "サーロインステーキは睡眠中ネ…",
		},
		BEEFALOHAT = "ボクの頭にぴったりネ",
		BEEFALOWOOL = "ウシには、悪いことしたネ…",
		BEEHAT = "ハチミツ採るときの必需品ネ",
		BEEHIVE = "中でブンブン音がするネ",
		BEEMINE = "ハチ兵器ネ",
		BEEMINE_MAXWELL = "このワナにかかったら、すごく痛そうネ…",
		BELL = "鳴らしてみようカナ…？",
		BELL_BLUEPRINT = "見事な設計図ネ！",
		BERMUDATRIANGLE = "近づかないほうが、いいカモ？",
		BERRIES = "フレッシュなフルーツだヨ！",
		BERRIES_COOKED = "ちょっと甘みが足りないネ…",
		BERRYBUSH =
		{
			BARREN = "肥料あげて、お世話しないとネ…",
			GENERIC = "ベリーだヨ！",
			PICKED = "そのうちまた、実がなるヨ",
			WITHERED = "暑さにやられてしまったネ",
		},
		BIGFOOT = "踏みつぶさないでヨ！",
		BIOLUMINESCENCE = "トレビアン…",
		BIRCHNUTDRAKE = "こいつら、ナンナノ…？",
		BIRDCAGE =
		{
			GENERIC = "翼のあるドーブツさんのおうちネ",
			OCCUPIED = "卵農場、完成だヨ！",
			SLEEPING = "タマゴ産むエネルギー、たくわえないとネ！",
			HUNGRY = "おいしいもの、作ってあげようネ",
			STARVING = "鳥は、なに食べる？ステーキでいいのカナ？",
			DEAD = "そのうち、目を覚ますカナ？",
			SKELETON = "いつまでたっても目を覚まさないネ…",
		},
		BIRDTRAP = "鳥の…ロースト…＊ジュルリ＊",
		BIRD_EGG = "天然の完全食ネ",
		BIRD_EGG_COOKED = "ハーブを添えれば、おいしくなるハズ…",
		BISHOP = "キミ、あんまり信心深そうじゃないヨ？",
		BISHOP_NIGHTMARE = "ボロボロですヨ…？ムリは、よくないですヨ？",
		BLOWDART_FIRE = "これでボクも、火を吹けるネ！",
		BLOWDART_FLUP = "死んだ生き物の再利用！ちょっとフクザツ…",
		BLOWDART_PIPE = "敵に気づかれずに攻撃できるネ",
		BLOWDART_POISON = "臆病者の武器…ボクにぴったりネ！",
		BLOWDART_SLEEP = "ぐっすり眠れるネ！",
		BLUBBER = "ラード！よく燃えそうネ！",
		BLUBBERSUIT = "非常のときは、ぜいたくは言えないネ",
		BLUEAMULET = "つつつつめたいヨ…！",
		BLUEGEM = "きれいな青色ネ…",
		BLUEPRINT = "テクノロジーのレシピだヨ！",
		BLUE_CAP = "どんなステキな味がするのカナ…！？",
		BLUE_CAP_COOKED = "スモークソルトとバルサミコ酢が欲しいネ…",
		BLUE_MUSHROOM =
		{
			GENERIC = "おお…！青トリュフだヨ！",
			INGROUND = "キノコは光を嫌うヨ",
			PICKED = "トリュフ、また入荷するといいネ",
		},
		BOARDS = "これでサーモンのグリル作りたいけどネ…",
		BOAT = "これで海を渡れるネ",
		BOATCANNON = "早くブッぱなしたいネ！",
		BOATREPAIRKIT = "航海の必需品ネ",
		BOAT_LANTERN = "暗い海を照らすヨ！",
		BOAT_TORCH = "海でも使える明かりネ",
		BONESHARD = "いいスープがとれそうネ",
		BONESTEW = "ココロまで、あったかくなるネ！",
		BOOMERANG = "コイツを手放すなんて…ボクには無理ネ…",
		BOTTLELANTERN = "明るいネ！",
		BUGNET = "代替タンパク源を捕まえる道具ネ",
		BUNNYMAN = "ウサギ肉のレシピなら、いろいろ知ってるヨ",
		BURIEDTREASURE = "なにが出るカナ？なにが出るカナ？",
		BUSHHAT = "携帯用のおやつカナ？",
		BUSH_VINE =
		{
			BURNT = "スモークの香り…おかなすいてきたヨ…",
			CHOPPED = "ツルは、ツルッと採ってしまったヨ",
			GENERIC = "ブドウのツルだったら、いいのにネ…",
		},
		BUTTER = "バター！キミに会えて、ボクはうれしいヨ！",
		BUTTERFLY =
		{
			GENERIC = "ヒラヒラ…見てるとココロが落ち着くネ…",
			HELD = "“チョウ”しに乗ってると、逃げられるヨ！",
		},
		BUTTERFLYMUFFIN = "おいしゅうございマス！",
		BUTTERFLYWINGS = "この食材で、どんな料理ができるカナ…？",
		BUZZARD = "ターキーなら大歓迎だけどネ…",
		CACTUS =
		{
			GENERIC = "シャープな味がしそうネ",
			PICKED = "きっとまた、トゲトゲくんが生えてくるヨ",
		},
		CACTUS_FLOWER = "花は意外とかわいらしいネ",
		CACTUS_MEAT = "ノドにトゲが刺さらないカナ…",
		CACTUS_MEAT_COOKED = "トルティーヤとチーズが欲しいネ…",
		CAMPFIRE =
		{
			EMBERS = "燃料を足したほうがいいかもネ…",
			GENERIC = "これで暗闇も怖くないネ",
			HIGH = "まるで油を注いだみたいだヨ！",
			LOW = "火が弱くなってきたヨ",
			NORMAL = "しばらく、そばに座ってていいカナ…？",
			OUT = "また火をおこさなきゃネ",
		},
		CANE = "歩くのが楽チンになるヨ！",
		CAPTAINHAT = "船長に昇格したヨ！",
		CARGOBOAT = "これで長距離輸送もばっちりネ！",
		CARROT = "摘みたて野菜だヨ！",
		CARROT_COOKED = "オリーブオイルとコリアンダーが欲しいネ…",
		CARROT_PLANTED = "新鮮なニンジンだヨ！",
		CARROT_SEEDS = "いつの日か、ニンジンになるヨ！",
		CATCOON = "ピンと立ったお耳がカワイイネ！",
		CATCOONDEN =
		{
			EMPTY = "何も住んでないヨ",
			GENERIC = "このおうち、何匹、入れるのカナ？",
		},
		CATCOONHAT = "ボクのシュミじゃないネ…",
		CAVE_BANANA = "これこそ、ボクが求めていた味ネ！",
		CAVE_BANANA_COOKED = "オート麦とチョコチップが欲しいネ…",
		CAVE_BANANA_TREE = "近くにサルがいそうネ",
		CAVE_ENTRANCE =
		{
			GENERIC = "I wonder what is underneath that?",
			OPEN = "Dare I?",
		},
		CAVE_EXIT = "Thank goodness.",
		CAVE_ENTRANCE = "下には何があるのカナ…？",
        CAVE_ENTRANCE_RUINS = "中はどうなってるのカナ…？",
       
       	CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "下には何があるのカナ…？",
            OPEN = "ンー…入ってみる…？",
        },
        CAVE_EXIT = 
        {
            GENERIC = "フゥ…助かった",
            OPEN = "地上の世界に戻りたいヨ…",
        },

		CAVE_FERN = "こんなとこでも、植物が育つのカナ…？",
		CHARCOAL = "あとは、グリルと肉があればネ…",
		CHESSJUNK1 = "壊れたチェスの駒カナ…？",
		CHESSJUNK2 = "これも、壊れたチェスの駒カナ…？",
		CHESSJUNK3 = "これもやっぱり、壊れたチェスの駒カナ…？",
		CHESTER = "カワイイ！でも、食べ物じゃなさそうネ！",
		CHESTER_EYEBONE =
		{
			GENERIC = "こっち見てるネ…",
			WAITING = "寝ている。",
		},
		CHIMINEA = "ピザ窯に改造できるカナ？",
		CLOTHSAIL = "海の旅は、こうじゃなきゃネ！",
		COCONADE =
		{
			BURNING = "たぶん、もうすぐ爆発するヨ…",
			GENERIC = "食材兵器ネ",
		},
		COCONUT = 
		{
		    GENERIC = "パッケージが固くて開かないヨー",
		    PLANTED = "ココナッツ…食べたかったネ…",
		},
		COCONUT_COOKED = "ライスとカレー粉、欲しいネ…",
		COFFEE = "トレビアン！",
		COFFEEBEANS = "セボン！",
		COFFEEBEANS_COOKED = "コーヒーにして飲みたいヨ…！",
		--COFFEEBOT = "What a delight!",
		COFFEEBUSH =
		{
			BARREN = "アアッ！コーヒーがッ！",
			GENERIC = "あれに…コーヒー豆がなるノ！？",
			PICKED = "明日の朝までに、実がなるといいナ…",
			WITHERED = "アアッ！コーヒーがッ！",
		},
		COLDFIRE =
		{
			EMBERS = "燃料を足したほうがいいかもネ…",
			GENERIC = "ヒンヤリする火…？",
			HIGH = "炎が空へ昇っていくネ！",
			LOW = "収まって来た。",
			NORMAL = "しばらく、そばに座ってていいカナ…？",
			OUT = "また火をおこさなきゃネ",
		},
		COLDFIREPIT =
		{
			EMBERS = "燃料を足したほうがいいかもネ…",
			GENERIC = "ヒンヤリする火…？",
			HIGH = "炎が空へ昇っていくネ！",
			LOW = "収まって来た。",
			NORMAL = "しばらく、そばに座ってていいカナ…？",
			OUT = "また火をおこさなきゃネ",
		},

		COMPASS =
		{
			E = "東だ",
			GENERIC = "んー…方角、わからないネ",
			N = "北",
			NE = "北東だ",
			NW = "北西だ",
			S = "南だ",
			SE = "南東だ",
			SW = "南西だ",
			W = "西だ",
		},
		COOKEDMANDRAKE = "ホースラディッシュが欲しいネ…",
		COOKEDMEAT = "チミチュリソースが欲しいネ…",
		COOKEDMONSTERMEAT = "これは…何をつけ合せてもダメネ…",
		COOKEDSMALLMEAT = "海塩かけたら、おいしくなりそうネ…",
		COOKPOT = 
		{
			BURNT = "オー！ノー！",
			COOKING_LONG = "料理のコツは、時間と愛情かけることネ！",
			COOKING_SHORT = "もうすぐできるヨ…",
			DONE = "おお！完成したヨ！",
			EMPTY = "鍋がカラだと、ココロもからっぽネ…",
		},
		COONTAIL = "焼きそば用の麺みたいネ",
		CORAL = "これで、何作ろうカナ…？",
		CORALREEF = "海にしかない、虹色の岩ネ",
		CORAL_BRAIN = "これって、ホントに脳ミソ…？",
		CORAL_BRAIN_ROCK = "ブヨブヨしてて、ちょっと賢そうな岩ネ",
		CORN = "甘くておいしい、コーンだヨ！",
		CORN_COOKED = "味噌とベーコンが欲しいネ…",
		CORN_SEEDS = "コーンを、おなかいっぱい食べられるヨ！",
		CRAB =
		{
			GENERIC = "クラブケーキの材料ネ",
			HIDDEN = "んー、カニの香り！",
		},
		CRABHOLE = "さー、出てオイデー！",
		CROW =
		{
			GENERIC = "カラス肉のシチュー…悪くないカモ？",
			HELD = "静かにしてヨ！",
		},
		CUTGRASS = "さーて、何つくろうカナ？",
		CUTLASS = "アンギャルド！",
		CUTLICHEN = "これは…何カナ？",
		CUTREEDS = "新緑の香りだヨ",
		CUTSTONE = "平らに整えた石だヨ…きれいネ",
		DEADLYFEAST = "これは…食べないほうがいいネ",
		DEAD_SWORDFISH = "大物ネ！",
		DECIDUOUSTREE =
		{
			BURNING = "アデュー！",
			BURNT = "クリスピー？",
			CHOPPED = "スライス！",
			GENERIC = "まるで木の葉のブーケね！",
			POISON = "結構です！",
		},
		DEERCLOPS = "昔、厨房で一緒だったヤツに似てるネ",
		DEERCLOPS_EYEBALL = "巨大な目玉の…スープ？",
		DEPLETED_GRASS =
		{
			GENERIC = "賞味期限切れネ",
		},
		DEVTOOL = "便利ネ",
		DEVTOOL_NODEV = "ズルはしない主義だヨ",
		DIRTPILE = "土を掘り起こしてるヤツがいるネ…？",
		DIVININGROD =
		{
			COLD = "…このへんじゃないみたいネ",
			GENERIC = "かなり高度なレーダー装置ネ",
			HOT = "この近くのはずネ！",
			WARM = "反応あったヨ！",
			WARMER = "近づいてるネ…！",
		},
		DIVININGRODBASE =
		{
			GENERIC = "これは…まな板、カナ？",
			READY = "どうやって起動するのカナ？",
			UNLOCKED = "準備完了ネ！",
		},
		DIVININGRODSTART = "これはたぶん、大事なものネ",
		DOUBLE_UMBRELLAHAT = "ハハハ！かっこ悪いネ！サイコー！",
		DOYDOY = "この鳥、見込みありそうネ",
		DOYDOYBABY = "育てれば食材になるネ",
		DOYDOYEGG = "朝ごはんに、ぴったりネ",
		DOYDOYFEATHER = "ボクの友だちの羽根ネ",
		DOYDOYNEST = "待てば待つほど、おいしくなるネ",
		DOYDOYEGG_CRACKED = "腐ったタマゴ…？",
		DRAGONFLY = "ボク、あんなのと戦えナイヨ！",
		DRAGONFLYCHEST = "燃えない倉庫！イイネ！",
		DRAGONFRUIT = "エキゾチック！",
		DRAGONFRUIT_COOKED = "プディングとチアシードを添えたいネ…",
		DRAGONFRUIT_SEEDS = "ふ化すると、ドラゴンフルーツになるネ",
		DRAGONPIE = "ほどよい酸味のフィリング…サクサクの生地…！",
		DRAGON_SCALES = "触ると熱いネ！",
		DRAGOON = "ボクも、自力で火をおこせたらいいのにネ！",
		DRUMSTICK = "赤身の肉ネ！",
		DRUMSTICK_COOKED = "ハニーガーリックソース、かけたいネ…",
		DUBLOON = "黄金色の食べ物は、だいたい全部おいしいヨ！",
		DUG_BAMBOOTREE = "どこかに植えたほうがいいカナ？",
		DUG_BERRYBUSH = "どこかに植えたほうがいいカナ？",
		DUG_COFFEEBUSH = "コーヒー、お持ち帰りで！",
		DUG_ELEPHANTCACTUS = "どこかに植えたほうがいいカナ？",
		DUG_GRASS = "どこかに植えたほうがいいカナ？",
		DUG_MARSH_BUSH = "どこかに植えたほうがいいカナ？",
		DUG_SAPLING = "どこかに植えたほうがいいカナ？",
		DURIAN = "なんとも言えないにおいネ…",
		DURIAN_COOKED = "オニオンとトウガラシを添えたいネ…",
		DURIAN_SEEDS = "種までクサいネ…",
		EARMUFFSHAT = "もふもふネ！",
		EARRING = "お洒落。",
		EEL = "高級食材ネ",
		EEL_COOKED = "ケイジャン風スパイス、かけたいネ…",
		EGGPLANT = "秋の味覚ネ！",
		EGGPLANT_COOKED = "トマトソースと粉チーズ、かけたいネ…",
		EGGPLANT_SEEDS = "ナスを育てられるネ！",
		ELEPHANTCACTUS = "でっかいトゲトゲ植物ネ",
		ELEPHANTCACTUS_ACTIVE = "植物なのに、武装してるネ！",
		ELEPHANTCACTUS_STUMP = "そのうちまた、生えてくるネ",
		EVERGREEN =
		{
			BURNING = "アデュー！",
			BURNT = "クリスピー？",
			CHOPPED = "スライス！",
			GENERIC = "まるで、異国の森の兵士ネ",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "アデュー！",
			BURNT = "クリスピー？",
			CHOPPED = "スライス！",
			GENERIC = "種をつけない…？変わった木ネ",
		},
		EYEBRELLAHAT = "本日の“目玉”商品ネ！",
		EYEPLANT = "ついつい目を奪われちゃうネ…",
		EYETURRET = "レーザー式の目玉デバイスだヨ！",
		EYETURRET_ITEM = "起キナサーイ！",
		FABRIC = "やわらかくて、でもパリッとしてるネ",
		FARMPLOT =
		{
			BURNT = "ちょっと焼き時間が長すぎたみたいネ",
			GENERIC = "食材を自給自足できるネ！",
			GROWING = "新鮮な摘みたて野菜、食べるの楽しみネ！",
			NEEDSFERTILIZER = "肥料、やらないとだめネ",
		},
		FEATHERFAN = "どうしてこんなに大きいのカナ？",
		FEATHERHAT = "これで何をしろって言うの？",
		FEATHERSAIL = "ナデナデしたくなるネ",
		FEATHER_CROW = "トリュフみたいに黒い鳥の羽根ネ",
		FEATHER_ROBIN = "チェリーみたいに赤い鳥の羽根ネ",
		FEATHER_ROBIN_WINTER = "マグロみたいに青い鳥の羽根ネ",
		FEM_PUPPET = "あいつが罠にかかった！",
		FERTILIZER = "畑にかけるソース、ってとこネ！",
		FIREFLIES =
		{
			GENERIC = "キラキラ光る、小さな虫ネ",
			HELD = "ボクのペット…豆電球みたいでカワイイネ",
		},
		FIREHOUND = "あのイヌ、燃えてるヨ！",
		FIREPIT =
		{
			EMBERS = "火が消えそうダヨ！",
			GENERIC = "あったかいし、ソーセージも焼けるネ！",
			HIGH = "最大火力ネ！",
			LOW = "収まって来た。",
			NORMAL = "パーフェクト！",
			OUT = "火が燃えてないと、寒いし、寂しいネ…",
		},
		FIRESTAFF = "棒つきオーブンだヨ！",
		FIRESUPPRESSOR =
		{
			LOWFUEL = "そろそろ、燃料、入れたほうがいいカナ…？",
			OFF = "寝てるみたいネ…",
			ON = "雪よ、降れ！",
		},
		FISH = "お魚だヨ！",
		FISHINGROD = "魚は市場で買いたいネ…",
		FISHINHOLE = "キラキラ輝く食材が泳いでるネ",
		FISHSTICKS = "外はカリッと、中はしっとり！",
		FISHTACOS = "ん～、メキシコの味ネ！",
		FISH_MED = "大丈夫、おいしく料理してあげるヨ",
		FISH_MED_COOKED = "摘みたてハーブとバターを添えたいネ…",
		FISH_COOKED = "レモン汁、かけたいネ…",
		FISH_RAW = "新鮮だから、全然生臭くないネ！",
		FISH_RAW_SMALL = "じつにすばらしい食材ネ！",
		FISH_RAW_SMALL_COOKED = "摘みたてハーブとバター、添えたいネ…",
		FLAMEGEYSER = "ヤケドに注意ネ！",
		FLINT = "鋭くトガってるヨ！",
		FLOTSAM = "船の残骸かもネ…",
		FLOWER = "ビューティフル！",
		FLOWERHAT = "これをかぶれば、みんなハンサムね！",
		FLOWERSALAD = "まさに、食べるアートね！",
		FLOWER_CAVE = "アア…暗闇にさす、一筋の光！",
		FLOWER_CAVE_DOUBLE = "アア…暗闇にさす、一筋の光！",
		FLOWER_CAVE_TRIPLE = "アア…暗闇にさす、一筋の光！",
		FLOWER_EVIL = "不吉な前兆…間違いないネ…",
		FLUP = "イタイッ！あっち行けッ！",
		FOLIAGE = "葉っぱだヨ",
		FOOTBALLHAT = "ブタは、防具にもなるんだネ！",
		FROG =
		{
			DEAD = "オマエの脚を、晩メシにしてやるゾ！",
			GENERIC = "カエルは珍味だヨ",
			SLEEPING = "食材が眠ってるネ…",
		},
		FROGGLEBUNWICH = "フランス料理のできあがりネ！",
		FROGLEGS = "飛びはねたいほど、うれしいネ！",
		FROGLEGS_COOKED = "ニンニクと澄ましバターをつけたいネ…",
		FROG_POISON = "毒をもってるから、注意ネ",
		FRUITMEDLEY = "ビタミンたっぷりネ！",
		GASHAT = "食べ物に毒が入ったら、大変だからネ！",
		GEARS = "怖～い機械の内臓ネ",
		GEMSOCKET =
		{
			GEMS = "宝石をはめ込まないとだめネ！",
			VALID = "準備完了ネ～♪",
		},
		GHOST = "「ゴーストペッパー」ってトウガラシがあってネ…",
		GLOMMER = "なかなか、カワイイと思うネ",
		GLOMMERFLOWER =
		{
			DEAD = "なんて無駄。",
			GENERIC = "トレビアン！",
		},
		GLOMMERFUEL = "見た目はガムに似てるケド、味は…",
		GLOMMERWINGS = "ちっこいけど、珍味ネ",
		GOATMILK = "チーズにしたいネ！",
		GOLDENAXE = "キラキラのオノだヨ！",
		GOLDENMACHETE = "豪華なナタだヨ！",
		GOLDENPICKAXE = "キラキラでカッコイイネ！",
		GOLDENPITCHFORK = "黄金でできた、巨人用のフォーク…カナ？",
		GOLDENSHOVEL = "キラキラだヨ！",
		GOLDNUGGET = "卵の黄身のような色ネ！",
		GOOSE_FEATHER = "グースから抜いた羽根ネ…",
		GRASS =
		{
			BARREN = "肥料をあげないとネ",
			BURNING = "ボクは、食材焦がしたことがないネ",
			GENERIC = "サバイバル生活の“主食”みたいなものネ",
			PICKED = "もう摘めるところはないネ！",
			WITHERED = "暑すぎて枯れちゃったネ",
		},
		GRASS_UMBRELLA = "ささないよりはマシ、ってとこネ…",
		GRASS_WATER = "海のハーブだヨ",
		GREENAMULET = "効率よく物づくりできるネ！",
		GREENGEM = "これは珍しいネ！",
		GREENSTAFF = "これでスープ混ぜるのは、やめとくネ…",
		GREEN_CAP = "キノコは、ほとんど水分だヨ",
		GREEN_CAP_COOKED = "バターとアサツキ、たっぷり添えたいネ…",
		GREEN_MUSHROOM =
		{
			GENERIC = "シャンピニオン！",
			INGROUND = "自分で自分を食べちゃったのカナ…？",
			PICKED = "また生えてくるのを待つしかないネ！",
		},
		GUACAMOLE = "アモーレ！",
		GUANO = "コウモリのフン、ダネ…",
		GUNPOWDER = "爆発するヨ！",
		HAIL_ICE = "普通の氷と変わらないネ",
		HAMBAT = "アイスキャンディ型の肉ネ！",
		HAMMER = "肉をたたいて、やわらかくする道具ネ！",
		HAWAIIANSHIRT = "「郷に入れば郷に従え」ってネ…",
		HEALINGSALVE = "やわらぐ。",
		HEATROCK =
		{
			COLD = "まだ冷たいネ",
			FROZEN = "アイスクリームみたいに冷たいネ",
			GENERIC = "熱くなったり冷たくなったりする石ネ",
			HOT = "アッチッチ！",
			WARM = "ちょうどいい温かさネ",
		},
		HOME = "誰の家カナ？",
		HOMESIGN =
		{
			BURNT = "焼きすぎだヨ…",
			GENERIC = "看板立てても、意味なくナイ？",
		},
		HONEY = "神々のお飲み物ネ！",
		HONEYCOMB = "ミルクかければ、デザートになるヨ！",
		HONEYHAM = "ごちそうネ！",
		HONEYNUGGETS = "実はジャンクフードも好き…ナイショだヨ？",
		HORN = "中に毛が残ってるネ…",
		HOTCHILI = "ちょっぴりスパイシーな人生もイイネ！",
		HOUND = "あのイヌ、凶暴だヨ！",
		HOUNDBONE = "いいスープがとれそうネ…",
		HOUNDFIRE = "火の元、注意ネ！",
		HOUNDMOUND = "湿ったニオイがするネ",
		HOUNDSTOOTH = "舌を抜かれるよりマシだヨ",
		ICE = "氷だヨ",
		ICEBOX = "料理人の強い味方だヨ",
		ICECREAM = "甘～いスイーツで、暑さを撃退ネ！",
		ICEHAT = "…どうしても、かぶらないとダメ？",
		ICEHOUND = "氷の悪魔め！ウセロ！",
		ICEMAKER =
		{
			HIGH = "絶好調ネ！",
			LOW = "まだ、なんとか動いてるネ",
			NORMAL = "小さなぜいたくネ",
			OUT = "止まっちゃったヨ",
			VERYLOW = "止まりそうだヨ！",
		},
		ICEPACK = "とっても便利ネ！",
		ICESTAFF = "鶏肉を瞬間冷凍するヨ！",
		INSANITYROCK =
		{
			ACTIVE = "ボク、ついにおかしくなっちゃったネ！",
			INACTIVE = "なめると、舌がくっついちゃうヨ",
		},
		IRONWIND = "ブルルン！ブルルン！",
		JAMMYPRESERVES = "そぼくな甘み…ん～ゼツミョウ！",
		JELLYFISH = "電気クラゲ…食材にできるカナ…？",
		JELLYFISH_COOKED = "ゴマ油と唐辛子が欲しいネ…",
		JELLYFISH_DEAD = "ちっちゃな顔があるネ…",
		JELLYFISH_PLANTED = "クラゲ、ダヨ",
		JELLYJERKY = "ニンニク、欲しいネ…",
		JUNGLETREE =
		{
			BURNING = "アデュー！",
			BURNT = "クリスピー？",
			CHOPPED = "スライス！",
			GENERIC = "なんて大きな木！",
		},
		JUNGLETREESEED =
        {
            GENERIC = "かわいらしいネ",
            PLANTED = "種よりかわいくなったヨ！",
        },
		KABOBS = "ボクのグランパの得意料理ネ！",
		KILLERBEE =
		{
			GENERIC = "ハチミツ欲しいけど、死ぬのはイヤネ！",
			HELD = "このハチ、態度が気に入らないネ！",
		},
		KNIGHT = "このナイトは、クワセモノだヨ！",
		KNIGHTBOAT = "大砲、用意！海賊ごっこの時間ネ！",
		KNIGHT_NIGHTMARE = "ひぃ～、コワイヨ～！",
		KOALEFANT_SUMMER = "ん～、まるまる太って、オイシソウ！",
		KOALEFANT_WINTER = "食用のケモノに感情移入しちゃダメネ",
		KRAMPUS = "オマエ！何者ダ！",
		KRAMPUS_SACK = "いっぱい入るヨ！",
		LANTERN = "常夜灯にぴったりネ",
		LAVAPOOL = "ピリッと、からそうな色ネ！",
		LAVASPIT =
		{
			COOL = "表面カリカリ…クレームブリュレみたいネ！",
			HOT = "シェフは、熱いの触ってもヤケドしないヨ",
		},
		LEIF = "自然のお怒りに触れちゃったヨ！",
		LEIF_SPARSE = "自然のお怒りに触れちゃったヨ！",
		LICHEN = "こんな食材しか手に入らないナンテ…",
		LIGHTBULB = "キャンディみたいネ",
		LIGHTNINGGOAT =
		{
			CHARGED = "ヤギのミルクシェイク！",
			GENERIC = "ボク、昔、ヤギを飼っていたヨ",
		},
		LIGHTNINGGOATHORN = "これでシシケバブ作れるカナ？",
		LIGHTNING_ROD =
		{
			CHARGED = "ビリビリだヨ！",
			GENERIC = "これで、ちょっと安心ネ",
		},
		LIMESTONE = "ちっちゃいお魚のホネでできてるネ",
		LIMPETROCK =
		{
			GENERIC = "ちっちゃい貝が獲れるネ！",
			PICKED = "ボク、二枚貝には目がないヨ～！",
		},
		LIMPETS = "潮の香りがするネ",
		LIMPETS_COOKED = "ほどよい塩気…絶妙な舌触り…絶品ネ",
		LITTLE_WALRUS = "おチビちゃん！",
		LIVINGJUNGLETREE = "もしもし？寝てるんデスカ？",
		TREEGUARD = "アナタとは戦いたくないデスヨ…",
		LIVINGLOG = "魔法の建築材ダヨ！",
		LIVINGTREE = "なんだかとっても、アヤシイヨ…",
		LOBSTER = "ごちそうちゃん、パパのところへオイデ！",
		LOBSTERHOLE = "出てくるまで、待ってるヨ！",
		LOBSTER_DEAD = "すぐに、ごちそうにしてあげるヨ…",
		LOBSTER_DEAD_COOKED = "ガーリックバター、つけて食べたいネ…",
		LOCKEDWES = "ボクが助けてあげるからネ！",
		
		LOG =
		{
			BURNING = "燃えガラになっちゃうヨ…",
			GENERIC = "料理という芸術に、欠かせない素材ネ",
		},
		LOGRAFT = "丸太は、燃料にしたほうがいいと思うヨ…",
		LUGGAGECHEST = "新しい下着、入ってるとイイナ！",
		LUREPLANT = "なぜか、近くへ行きたくなるヨ…",
		LUREPLANTBULB = "植物から肉…？フシギなこともあるネ…",
		MACHETE = "これなら、玉ねぎみじん切りも簡単ネ！",
		MAGMAROCK = "岩は、いいワネ！…な～んてネ",
		MAGMAROCK_GOLD = "金箔、採れるカナ？",
		MANDRAKE =
		{
			DEAD = "この謎の根は深いネ…根っこなダケニ？",
			GENERIC = "これは…新種の根菜！？",
			PICKED = "抜いちゃダメだヨ！",
		},
		MANDRAKESOUP = "摩訶不思議な味だヨ！",
		MANDRAKE_COOKED = "これに合う調味料？知るわけないヨ！",
		MANGROVETREE = "水分含有量は、どのくらいカナ？",
		MANGROVETREE_BURNT = "現在の水分含有量は…0ネ",
		MARBLE = "いい調理台になりそうネ",
		MARBLEPILLAR = "調理台、何台造れるカナ…",
		MARSH_BUSH =
		{
			BURNING = "燃えちゃえば、ただの木と同じネ",
			GENERIC = "ちょっと“トゲのある”お客様ネ",
			PICKED = "トゲが刺さって痛かったネ…",
		},
		MARSH_PLANT = "これも食材になるカナ？",
		MARSH_PLANT_TROPICAL = "これも食材になるカナ？",
		MARSH_TREE =
		{
			BURNING = "これで、ケガする心配なくなったネ",
			BURNT = "この木、炭になると、独特の香り放つネ",
			CHOPPED = "これでもう、トゲが刺さる心配ないネ",
			GENERIC = "木なのに、攻撃してくるヨ！",
		},
		MAXWELL = "オマエ！悪いヤツ！",
	    MAXWELLHEAD = "巨大サンドイッチ、食べるのカナ？",
		MAXWELLLIGHT = "明かりなら、なんでも歓迎だヨ",
		MAXWELLLOCK = "カギは、どこカナ…？",
		MAXWELLPHONOGRAPH = "アイツ、どんなレコード持ってるのカナ？",
		MAXWELLTHRONE = "「玉座に座る者に、苦悩はつきもの」ネ…",
		MEAT = "筋を断ち切るようにカットするといいヨ！",
		MEATBALLS = "肉汁たっぷりネ！",
		MEATRACK =
		{
			BURNT = "乾燥させすぎダヨ！",
			DONE = "どんなかみ応えに仕上がったカナ？",
			DRYING = "まだ水分が残ってるヨ",
			DRYINGINRAIN = "水分、補給されちゃってるヨ…",
			GENERIC = "石器時代のシェフが使った設備ネ！",
		},
		MEAT_DRIED = "チポトレをかけて食べたいネ…",
		MERM = "魚人さんの家だヨ",
		MERMFISHER = "魚屋さんネ！",
		MERMHEAD =
		{
			BURNT = "まだ生焼けみたいネ！",
			GENERIC = "時間がたつほど、クサくなるネ…",
		},
		MERMHOUSE =
		{
			BURNT = "焼けたら、ニオイがマシになったネ",
			GENERIC = "魚人の家ネ…ニオイでわかるヨ",
		},
		MERMHOUSE_FISHER = "魚人の家ネ…ニオイでわかるヨ",
		MESSAGEBOTTLE = "これは…裏メニュー、カナ？",
		MESSAGEBOTTLEEMPTY = "ヴィンテージワインが入ってたのカナ…？",
		MINERHAT = "「頭を使う」って、こういうことネ！",
		MINOTAUR = "こっちクルナ！",
		MINOTAURCHEST = "細工がとても美しいネ…",
		MINOTAURHORN = "粉末にしたら、食材になるカナ…？",
		MOLE =
		 {
		 	ABOVEGROUND = "ボクのこと、かぎ回ってるノ…？",
		 	HELD = "土の中より、快適カナ？",
		 	UNDERGROUND = "地下に何か住んでるみたいネ…",
		 },
		MOLEHAT = "暗闇でも、よく見えるネ！",
		MOLEHILL = "さすが、穴掘りのプロが掘った穴ネ",
		MONKEY = "ウザイ系動物の新種カナ？",
		MONKEYBARREL = "異様なおうちネ…",
		MONSTERLASAGNA = "ボク、なんでこんなもの作ったのカナ…",
		MONSTERMEAT = "見事な霜降りネ…",
		MONSTERMEAT_DRIED = "わざわざ干した理由が、わからないヨ…",
		MOOSE = "グースなら食材になるんだけどネ…",
		MOOSEEGG = "この卵には、触らないほうがよさそうネ！",
		MOSQUITO =
		{
			GENERIC = "ボクの血は、ボクのものネ！",
			HELD = "こんな虫、触るのもイヤだヨ！",
		},
		MOSQUITOSACK = "血が入ってた袋…？キモチワルイ！",
		MOSQUITOSACK_YELLOW = "血が入ってた袋…？キモチワルイ！",
		MOSQUITO_POISON = "血を吸う代わりに毒をくれる？イラナイヨ！",
	    MOSSLING = "お願いだから、ママは探さないでヨッ！",
		MOUND =
		{
			DUG = "ボク、ひどいことしたネ…",
			GENERIC = "何が埋まってるのカナ…？",
		},
		MULTITOOL_AXE_PICKAXE = "ナルホド！先割れスプーンみたいなものネ！",
		MUSHTREE_MEDIUM = "木になるキノコ！？新発見ッ！",
		MUSHTREE_SMALL = "木になるキノコなんて…あるノ…？",
		MUSHTREE_TALL = "アア、驚くべき、聖なるキノコの木ヨ…！",
		MUSSEL = "ムラサキ色の、海の宝石ネ…！",
		MUSSEL_COOKED = "エシャロットとレモングラスが欲しいネ…",
		MUSSEL_FARM =
		{
			GENERIC = "おいしいシーフードが集まってるヨ",
			STICKPLANTED = "ムール貝ちゃん、この棒につかまってヨ！",
		},
		MUSSEL_STICK = "ムール貝は、くっつかずにいられないヨ！",
		NEEDLESPEAR = "誰をつっつこうカナ…？",
		NIGHTLIGHT = "蛍光灯よりひどいネ！",
		NIGHTMAREFUEL = "これ以上、悪夢のモトなんて、いらないヨ…",
		NIGHTMARELIGHT = "この明かり…「照らしてくれてる感」ないネ…",
		NIGHTMARE_TIMEPIECE =
		 {
		 	CALM = "異常ナシだヨ",
		 	DAWN = "悪夢、もうすぐ終わるヨ！",
		 	NOMAGIC = "魔力、0だヨ",
		 	STEADY = "安定してるネ",
		 	WANING = "収まってきたネ",
		 	WARN = "魔力に反応し始めたヨ！",
		 	WAXING = "マジックアワーだヨ！",
		 },
		NIGHTSTICK = "電気仕掛けカナ？",
		NIGHTSWORD = "夢のように、スパスパ振れるヨ！",
		NITRE = "フムフム…興味深いネ",
		OBSIDIAN = "この石、熱いネ！",
		OBSIDIANAXE = "山火事みたいな勢いで、木を切れるヨ！",
		OBSIDIANCOCONADE = "爆発力アップだヨ！",
		OBSIDIANFIREPIT =
		{
			EMBERS = "火が消えそうダヨ！",
			GENERIC = "あったかいし、ソーセージも焼けるネ！",
			HIGH = "最大火力ネ！",
			LOW = "収まって来た。",
			NORMAL = "いつもより長めに燃えておりマス！",
			OUT = "火が燃えてないと、寒いし、寂しいネ…",
		},
		OBSIDIANMACHETE = "振りすぎて、オーバーヒートしないようにネ！",
		OBSIDIANSPEARGUN = "いま一番ホットなスピアガンだヨ！",
		OBSIDIAN_WORKBENCH = "火山グッズを作る装置ネ！",
		OCTOPUSCHEST = "冷たい飲み物、入ってるといいナ…",
		OCTOPUSKING = "あの足…おいしそ…オホンッ！",
		ONEMANBAND = "さあ、ドンチャン騒ぎシマショウ！",
		ORANGEAMULET = "一瞬で遠くへ行けちゃうヨ！",
		ORANGEGEM = "オレンジ、食べたいネ…",
		ORANGESTAFF = "これ持ってると、世界が“速く”見えるヨ",
		OX = "オオ！ビーフが食べられるヨ！",
		PACKIM = "大きな口！",
		PACKIM_FISHBONE = "きれいに食べたネ…",
		PALMLEAF = "タマーレ作るのに、ちょうどいいネ",
		PALMLEAF_HUT = "日陰、最高ネ！",
		PALMLEAF_UMBRELLA = "ボクは、雨には歌わないヨ！",
		PALMTREE =
		{
			BURNING = "アデュー！",
			BURNT = "クリスピー？",
			CHOPPED = "スライス！",
			GENERIC = "この木、よくしなるネ",
		},
		PANDORASCHEST = "It's quite magnificent.",
		PANFLUTE = "こういう音が好きな生き物もいるノ？",
		PAPYRUS = "レシピをメモできるネ！",
		PARROT = "オウム料理は…レパートリーにないヨ",
		PEACOCK = "目立ちたがり屋の鳥ネ！",
		PENGUIN = "このお客様、正装してるネ",
		PEROGIES = "一口食べれば、舌ツヅミ！",
		PETALS = "サラダに入れると、グッドだヨ！",
		PETALS_EVIL = "サラダに入れるのは、やめたほうがいいネ…",
		PICKAXE = "硬いナッツもラクラク割れるネ",
		PIGGUARD = "自分の肉を守ってるのカナ…？",
		PIGGYBACK = "ブタ皮のバッグだヨ！",
		PIGHEAD =
		{
			BURNT = "頬肉すら残ってないヨ…",
			GENERIC = "こんなところに、スバラシイ食材が！",
		},
		PIGHOUSE =
		{
			BURNT = "バーベキューだヨ！",
			FULL = "子ブタが3匹以上、入ってそうネ",
			GENERIC = "息を吹きかけたら、フッ飛ぶカナ？",
			LIGHTSOUT = "オーイ！誰かいるカ～イ？",
		},
		PIGKING = "う～ん、おいしそ…オホンッ！",
		PIGMAN =
		{
			DEAD = "おいしくいただかないと、もったいないヨ？",
			FOLLOWER = "ボク、カリスマ性があるからネ",
			GENERIC = "ブタなのに二足歩行…アヤシイネ…",
			GUARD = "わかったわかった、あっち行くヨ…",
			WEREPIG = "ストレスは肉の質を落とすヨ",
		},
		PIGSKIN = "カリッとクリスピー！",
		PIGTENT = "いい夢、見られそうネ",
		PIGTORCH = "何か、意味があるのカナ…？",
		PIKE_SKULL = "ヒィィィ…！",
		PINECONE =
		{
			GENERIC = "松の香りがするネ！",
			PLANTED = "いつか、大きな木になるんだネ",
		},
		PIRATEHAT = "海賊はキライだけど、帽子はカッコイイネ",
		PIRATEPACK = "背負ってると、背筋が伸びるネ",
		PIRATIHATITATOR =
		{
			BURNT = "炎の演出で、フィナーレだヨ…",
			GENERIC = "これ、なんだか、見覚えがあるヨ…",
		},
		PITCHFORK = "農具だヨ",
		PLANTMEAT = "植物の肉…？どういうコト？",
		PLANTMEAT_COOKED = "なんだか…矛盾した味がしそうだヨ…",
		PLANT_NORMAL =
		{
			GENERIC = "生命の神秘ネ！",
			GROWING = "その調子！ガンバレ！",
			READY = "摘みたてが食べられるネ！",
			WITHERED = "枯らしちゃったヨ…",
		},
		POISONHOLE = "キケンなニオイがするヨ…",
		POMEGRANATE = "トレビアン！",
		POMEGRANATE_COOKED = "タヒニとミントを添えて食べたいネ…",
		POMEGRANATE_SEEDS = "つぶつぶダヨ！",
		POND = "底が見えないヨ…",
		POND_ALGAE = "底が見えないヨ…",
		POOP = "高級食材も、最後はみんな、こうなるヨ",
		PORTAL_SHIPWRECKED = "別の世界へ旅する装置…カナ？",
		PORTABLECOOKPOT = 
		{
            BURNT = "ノオオオオオォォォォォォ！！",
            COOKING_LONG = "芸術的な料理は、時間がかかるものだヨ",
            COOKING_SHORT = "もう少しの、しんぼうネ！",
            DONE = "上がったヨ～！…っと、昔のクセが…",
            EMPTY = "デカケルトキハ、忘レズニ！",
        },
		PORTABLECOOKPOT_ITEM = "グルメの旅に欠かせない相棒ネ！",
		POTTEDFERN = "「とらわれの自然」、だネ",
		POWCAKE = "体にいいのか悪いのか…謎の食べ物ネ…",
		PRIMEAPE = "イタズラ者だし、おまけにクサいヨ！",
		PRIMEAPEBARREL = "ゴミ屋敷だヨ",
		PUMPKIN = "ヒトの頭ぐらい大きいネ！",
		PUMPKINCOOKIE = "最高傑作ができたヨ",
		PUMPKIN_COOKED = "パイ生地とナツメグが欲しいネ…",
		PUMPKIN_LANTERN = "誰か、お菓子くれないカナ…",
		PUMPKIN_SEEDS = "このまま食べてもオイシイヨ！",
		PURPLEAMULET = "われながら、とても正気とは思えないネ…",
		PURPLEGEM = "深～い秘密を秘めてるヨ…",
		RABBIT =
		{
			GENERIC = "ウサギ肉、しばらく食べてないネ…",
			HELD = "心臓が、すごい速さでドクドクしてるヨ",
		},
		RABBITHOLE =
		{
			GENERIC = "丸々太ったウサギさん、いたら返事シテ！",
			SPRING = "残念…ウサギのシーズンは、終わったヨ",
		},
		RABBITHOUSE =
		{
			BURNT = "ニンジンじゃなかったヨッ！",
			GENERIC = "幻覚…カナ？",
		},
		RAFT = "泳ぐよりは、マシ…カナ",
		RAINCOAT = "霧深いパリの夜にも、ぴったりネ",
		RAINHAT = "新聞紙よりは、マシ…カナ",
		RAINOMETER =
		{
			BURNT = "これじゃ、何も測れないネ…",
			GENERIC = "雲の水分含有量を測る装置ネ",
		},
		RATATOUILLE = "「野菜のごった煮オシャレ風」だヨ！",
		RAZOR = "アフターシェーブローション、欲しいネ",
		REDBARREL = "ドクロは、「キケン」の印…ダヨネ？",
		REDGEM = "中で炎がアカアカと燃えてるヨ",
		RED_CAP = "生クリームと塩、欲しいネ…毒はいらないヨ",
		RED_CAP_COOKED = "これでおいしいスープ、作れるかもネ…",
		RED_MUSHROOM =
		{
			GENERIC = "新鮮なキノコだヨ！",
			INGROUND = "土の中に潜っちゃってるヨ…",
			PICKED = "もう、何も残ってないヨ",
		},
		REEDS =
		{
			BURNING = "よく燃えてるネ",
			GENERIC = "アシの茂みだヨ",
			PICKED = "全部摘んでしまったヨ",
		},
		REFLECTIVEVEST = "これなら、なくしてもすぐ見つかるネ",
		RESEARCHLAB = --Science Machine
		{
			BURNT = "焼き加減、間違えたカナ…？",
			GENERIC = "即席研修センターだヨ",
		},
		RESEARCHLAB2 = --Alchemy Machine
		{
			BURNT = "炎に、ペロリと食べられちゃったヨ",
			GENERIC = "これで、研究し放題ネ！",
		},
		RESEARCHLAB3 = --Shadow Manipulator
		{
			BURNT = "闇も燃え尽きてしまったヨ…",
			GENERIC = "ジョーシキを超えた装置ネ…",
		},
		RESURRECTIONSTATUE =
		{
			BURNT = "これじゃもう、役に立たないヨ…",
			GENERIC = "中に、ボクの魂のかけらが入ってるヨ",
		},
		RESURRECTIONSTONE = "何かの儀式に使うものカナ？",
		ROBIN =
		{
			GENERIC = "ごきげんよう、マダム！…あー、サーかな？",
			HELD = "ホワホワだヨ…おとなしいネ…",
		},
		ROBIN_WINTER =
		{
			GENERIC = "ちょっと冷たい印象の鳥ネ",
			HELD = "鳥サン、ボクが温めてあげるヨ",
		},
		ROBOT_PUPPET = "いくらロボットだからって、ヒドイヨ！",
		ROCK = "石ころ、コロコロ！",
		ROCKS = "ひとくちサイズの岩ネ",
		ROCKY = "あれは、食べたら歯が欠けるかもネ…",
		ROCK_ICE =
		{
			GENERIC = "冷たいヨッ！",
			MELTED = "すっかり溶けちゃってるネ",
		},
		ROCK_ICE_MELTED = "すっかり溶けちゃってるネ",
		ROCK_LIGHT =
		{
			GENERIC = "表面が固まってるネ",
			LOW = "もうすぐ冷えて固まるヨ",
			NORMAL = "天然のフォンデュ鍋ネ！",
			OUT = "すっかり冷めてしまっているネ",
		},
		ROOK = "なんてシツレイな装置ナノ！",
		ROOK_NIGHTMARE = "An utter monstrosity!",
		ROPE = "ローストチキンをしばるには、太すぎるネ",
		ROTTENEGG = "オエッ！",
		ROWBOAT = "この島からボクを解放シテ！",
		RUBBLE = "Delicious destruction.",
		RUINSHAT = "ずいぶんゼイタクなかぶり物ネ",
		RUINS_BAT = "これで肉をたたけば、やわらかくなるネ",
		RUINS_RUBBLE = "Delicious destruction.",
		SAIL = "スイスイ進めるヨ",
		SAND = "ちっこい、ちっこい、石がたくさんッ！",
		SANDBAG = "中身はジャガイモかと思ったのにナ…",
		SANDBAGSMALL = "これを置けば、水が入ってこないヨ",
		SANDBAG_ITEM = "ジャガイモは、入ってないネ…残念",
		SANDBAGSMALL_ITEM = "早いうちに、設置しておかないとネ",
		SANDHILL = "砂が積み上がって、小さな山になってるヨ",
		SAND_CASTLE =
		{
			GENERIC = "ココロが安らぐネ",
			SAND = "ここにいると、くつろげるネ",
		},
		SANITYROCK =
		{
			ACTIVE = "見てると、頭がグチャグチャになりそうネ…",
			INACTIVE = "中に闇が潜んでるヨ…",
		},
		SAPLING =
		{
			BURNING = "なかなか、よく燃えるネ",
			GENERIC = "サバイバルの必需品ネ",
			PICKED = "もう摘んでしまったヨ！",
			WITHERED = "愛情が足りていないのカナ？",
		},
		SEAGULL = "ボクの料理、狙っているナ！",
		SEAGULL_WATER = "ボクの料理、狙っているナ！",
		SEASACK = "潮の香りのバッグだヨ",
		SEASHELL = "食べられる部分は、残っていないネ…",
		SEASHELL_BEACHED = "きれいな貝殻ネ",
		SEATRAP = "おいしい甲殻類、捕まえるヨ！",

		SEAWEED = "ボク、この食材は、料理し慣れていないヨ…",
		SEAWEED_COOKED = "いりゴマが欲しいネ…",
		SEAWEED_DRIED = "たまり醤油が欲しいネ…",
		SEAWEED_PLANTED = "海の幸だヨ！",
		SEEDS = "いつか、おいしい食材になるかもネ！",
		SEEDS_COOKED = "スモーク・パプリカパウダーが欲しいネ…",
		SEWING_KIT = "ボク、縫い物は専門外だヨ…",
		SHARKITTEN = "海の子牛ネ！",
		SHARK_FIN = "味は、しなそうネ…",
		SHARK_GILLS = "死んでしまったら、もう必要ないネ",
		SHARK_TEETHHAT = "ボクが王様だヨ！",
		SHARX = "食べないで！ボク、味ついてないヨ！",
		SHOVEL = "庭仕事は好きじゃないヨ…",
		SIESTAHUT =
		{
			BURNT = "ちょっと焼きすぎだヨ…",
			GENERIC = "ランチのあとは、昼寝にかぎるネ",
		},
		SILK = "殺菌は、してあるのカナ…？",
		SKELETON = "誰かを骨まで愛する自信は…ないネ",
		SKELETON_PLAYER = "誰かを骨まで愛する自信は…ないネ",
		SKULLCHEST = "ブキミな箱ネ",
		SLOTMACHINE = "おいしい食材、手に入るカナ？",
		SLURPER = "大口開けて食べるのは、お行儀悪いネ",
		SLURPERPELT = "これを身につける…？ナンデ？",
		SLURPER_PELT = "これを身につける…？ナンデ？",
		SLURTLE = "煮込めば、いいダシ出そうネ",
		SLURTLEHAT = "かぶればスラツムリになれるヨ",
		SLURTLEHOLE = "ゲーッ！",
		SLURTLESLIME = "自然の恵みは、ときどきグロいネ",
		SLURTLE_SHELLPIECES = "瞬間接着剤があれば、直せるけどネ…",
		SMALLBIRD =
		{
			GENERIC = "こんなところに食…じゃなくて、お友だちが！",
			HUNGRY = "あり合わせで、何か作るヨ",
			STARVING = "おなかペコペコなのネ！",
		},
		SMALLMEAT = "新鮮なタンパク源ネ！",
		SMALLMEAT_DRIED = "てり焼きソース、かけたいネ…",
		SNAKE = "あっち行け！串焼きにするゾ！",
		SNAKEDEN =
		{
			BURNT = "スモークの香り…おかなすいてきたヨ…",
			CHOPPED = "ツルは、ツルッと採ってしまったヨ",
			GENERIC = "ブドウのツルだったら、いいのにネ…",
		},
		SNAKEOIL = "オリーブオイルだったら、いいのにネ…",
		SNAKESKIN = "高級エプロン、作れるネ",
		SNAKESKINHAT = "トレビアン！",
		SNAKE_FIRE = "ヘビと火のダブルパンチ…！",
		SNAKE_POISON = "毒があるから、ていねいにさばかないとネ…",
		SNURTLE = "エスカルゴ…じゃないネ！",
		SOLOFISH = "切り身にして、バター焼きがいいカナ…",
		SPEAR = "シシケバブが作れるかもネ…",
		SPEARGUN = "遠距離用ケバブ製作装置ネ",
		SPEARGUN_POISON = "これで獲物しとめたら、肉が台なしになるネ…",
		SPEAR_OBSIDIAN = "狩りと料理、同時にできるネ！",
		SPEAR_POISON = "これで獲物しとめたら、肉が台なしになるネ…",
		SPICEPACK = "料理人の七つ道具が入ってるヨ！",
		SPIDER =
		{
			DEAD = "ボク、地獄に落ちちゃう…！？",
			GENERIC = "これは…食材にはならないネ",
			SLEEPING = "ああしてると、真綿の詰まった枕みたいネ",
		},
		SPIDERDEN = "クモにも住む場所は必要ネ",
		SPIDEREGGSACK = "どこかの国では、珍味かもネ",
		SPIDERGLAND = "薬にもなるヨ",
		SPIDERHAT = "手に入れたからには、活用しなきゃネ",
		SPIDERHOLE = "中をのぞいてみる気はないヨ…",
		SPIDERQUEEN = "オマエなんかの言いなりには、ならないゾ！",
		SPIDER_DROPPER = "天井から降りてくる悪者？ありがちネ～",
		SPIDER_HIDER = "カメみたいな習性のクモだヨ！",
		SPIDER_SPITTER = "スパイダーだらけだヨ！",
		SPIDER_WARRIOR =
		{
			DEAD = "自業自得ネ",
			GENERIC = "他のクモより凶暴？",
			SLEEPING = "きっと、戦場の悪夢にうなされてるヨ…",
		},
		SPOILED_FISH = "アア…もったいナイ…",
		SPOILED_FOOD = "食べ物粗末にするのは、重罪だヨ…",
		STAFFLIGHT = "片手じゃ扱えないほど、すごいパワーだヨ！",
		STAFF_TORNADO = "自然は、人に操られること、望むのカナ…？",
		STALAGMITE = "上向きの鍾乳石ネ",
		STALAGMITE_FULL = "ツルハシで掘れそうネ",
		STALAGMITE_LOW = "ツルハシで掘れそうネ",
		STALAGMITE_MED = "ツルハシで掘れそうネ",
		STALAGMITE_TALL = "ツルハシで掘れそうネ",
		STALAGMITE_TALL_FULL = "ツルハシで掘れそうネ",
		STALAGMITE_TALL_LOW = "ツルハシで掘れそうネ",
		STALAGMITE_TALL_MED = "ツルハシで掘れそうネ",
		STATUEGLOMMER =
		{
			EMPTY = "おっとっと！",
			GENERIC = "何かわからないケド…重要なものだった…？",
		},
		STATUEHARP = "ハープ持ってるけど…頭がないネ…",
		STATUEMAXWELL = "石のように冷たい男だヨ…",
		STINGER = "見てると、胸がチクチク痛むネ…",
		STRAWHAT = "のんびりリラックス～♪",
		STUFFEDEGGPLANT = "ジューシーなフィリング…スモークの香り…",
		STUNGRAY = "クサい…！体の中が腐ってるのカ…？",
		SUNKBOAT = "海は、すべてを容赦なくのみ込むヨ…",
		SUNKEN_BOAT =
		{
			ABANDONED = "あいつどこいった？",
			GENERIC = "アララ～、沈んじゃってるヨ",
		},
		SUNKEN_BOAT_BURNT = "あの船、きっと呪われてたんだネ",
		SUNKEN_BOAT_TRINKET_1 = "ん～？",
		SUNKEN_BOAT_TRINKET_2 = "これには、乗れないネ",
		SUNKEN_BOAT_TRINKET_3 = "ロウソクとしては使えなそうネ",
		SUNKEN_BOAT_TRINKET_4 = "これは…なにカナ？",
		SUNKEN_BOAT_TRINKET_5 = "ボクには、サイズが合わないヨ",
		SUPERTELESCOPE = "サメは鼻だけじゃなく、目もいいんだネ！",
		SWEATERVEST = "これ着ると、気持ちが落ち着くヨ",
		SWEET_POTATO = "甘～い、甘～い、おイモだヨ",
		SWEET_POTATO_COOKED = "カレー粉とサワークリームを添えたいネ…",
		SWEET_POTATO_PLANTED = "甘～い、甘～い、おイモだヨ",
		SWEET_POTATO_SEEDS = "ヤムイモとサツマイモは、別モノだヨ！",
		SWORDFISH = "高級食材だけど…近づくとキケンだヨ！",
		TAFFY = "歯が抜けないといいケド…",
		TALLBIRD = "足が長いネ",
		TALLBIRDEGG = "ふ化するまで、どのくらいかかるカナ？",
		TALLBIRDEGG_COOKED = "フライドトマトと豆を添えたいネ…",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "こんなに冷たくなって…カワイソウに！",
			GENERIC = "中でヒナが育ってるヨ！",
			HOT = "カタユデになってないと、いいケドネ…",
			LONG = "時間をかけて、愛情注がないとネ…",
			SHORT = "もうすぐふ化しそうだヨ！",
		},
		TALLBIRDNEST =
		{
			GENERIC = "満室ネ",
			PICKED = "親鳥が、「巣立ち症候群」にならないといいネ…",
		},
		TEENBIRD =
		{
			GENERIC = "キミは、そこそこ、背が高いネ…",
			HUNGRY = "育ち盛りのコの食欲は、底なしネ！",
			STARVING = "チョットは遠慮したら…？",
		},
		TELEBASE =
		{
			GEMS = "ムラサキの石が、もっと要るヨ",
			VALID = "準備オーケーだヨ",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "どこへ連れてってくれるのカナ？",
			GENERIC = "どっかにつながってる…怖イヨウ…！",
			LOCKED = "アクセスできないヨ",
			PARTIAL = "部品が足りないみたいだヨ",
		},
		TELEPORTATO_BOX = "んー、アレの部品カナ…？",
		TELEPORTATO_CRANK = "ナニかをクルクル回す道具ネ",
		TELEPORTATO_POTATO = "これは…ナンダ？",
		TELEPORTATO_RING = "「一つの輪は、すべてをテレポートする」！",
		TELEPORTATO_SW_BASE = "どっかにつながってる…怖イヨウ…！",
		TELEPORTATO_SW_BOX = "んー、アレの部品カナ…？",
		TELEPORTATO_SW_CRANK = "ナニかをクルクル回す道具ネ",
		TELEPORTATO_SW_POTATO = "これは…ナンダ？",
		TELEPORTATO_SW_RING = "「一つの輪は、すべてをテレポートする」！",
		TELESCOPE = "“遠く”がどれぐらい近づいたか、わかるヨ！",
		TELESTAFF = "ドコでもいいから、連れてって！",
		TENT =
		{
			BURNT = "安眠の夢は、煙のように消えたヨ…",
			GENERIC = "底辺生活の必需品ネ",
		},
		TENTACLE = "フライにしたら、おいしそう…？",
		TENTACLESPIKE = "食べたらノドに刺さりそうネ",
		TENTACLESPOTS = "キッチンマットに、よさそうネ",
		TENTACLE_GARDEN = "イカだったら、食材にできたのにネ…",
		TENTACLE_PILLAR = "イカだったら、食材にできたのにネ…",
		TENTACLE_PILLAR_ARM = "イカだったら、食材にできたのにネ…",
		THATCHPACK = "ヤシの葉、便利ネ！",
		THULECITE = "チュ…チューレ…舌かみそうネ",
		THULECITE_PIECES = "チューレなんちゃらのかけらだヨ",
		TIDALPOOL = "潮といっしょに、食材もたまってるヨ",
		TIDAL_PLANT = "これは、食べられないネ",
		TIGERSHARK = "タイガーシュリンプだったらいいのにッ！",
		TOPHAT = "夜のおでかけ用…？",
		TORCH = "カラメリゼはできないけど、明かりになるネ",
		TOUCAN = "でっかい鼻ネ…",
		TRAILMIX = "元気が出るおやつネ！",
		TRANSISTOR = "プラスの電気を帯びてるヨ",
		TRAP = "ズルい手は使いたくないけど、しかたないネ…",
		TRAP_TEETH = "ヒトにも、動物にも、優しくないワナだネ…",
		TRAP_TEETH_MAXWELL = "しかけてある場所、覚えとかなきゃネ…",
		TRAWLNET = "漁師生活、最高ネ！",
		TRAWLNETDROPPED =
		{
			GENERIC = "海の恵み、たくさんかかってるとイイネ",
			SOON = "もうすぐ沈んじゃうヨ！",
			SOONISH = "沈んじゃいそうネ",
		},
		TREASURECHEST =
		{
			BURNT = "これじゃもう、宝箱とは呼べないネ",
			GENERIC = "お宝だヨ！",
		},
		TREASURECHEST_TRAP = "なんだか、イヤな予感がするヨ…",
		TREECLUMP = "「入るな！」ってコト？",
		TRIDENT = "ナンテでっかいフォークなの！",
		TRINKET_1 = "アメ細工みたいネ",
		TRINKET_10 = "人工ソシャク装置？",
		TRINKET_11 = "コイツ、信用できなそうネ…",
		TRINKET_12 = "こんな食材使うレシピは、知らないヨ…",
		TRINKET_13 = "ボクはライムソーダのほうが好きネ",
		TRINKET_14 = "果物ナイフとセット…？",
		TRINKET_15 = "ボクは、リュートのほうが好きヨ",
		TRINKET_16 = "「プレート」？料理には見えないヨ…？",
		TRINKET_17 = "サイズが合っても、履きたくないネ…",
		TRINKET_18 = "取り扱い注意ネ",
		TRINKET_19 = "アヤシイおくすりネ",
		TRINKET_2 = "自分でハミングするから、いらないヨ",
		TRINKET_23 = "キョウミ深い装置ネ！",
		TRINKET_3 = "解けない結び目…解けないナゾ…",
		TRINKET_4 = "誰かの庭に、飾ってあったやつカナ…？",
		TRINKET_5 = "アリんこ用のロケット…カナ？",
		TRINKET_6 = "銅線むきだし…キケンかも…？",
		TRINKET_7 = "息抜きにはいいケド…時間のむだネ",
		TRINKET_8 = "アア…なつかしい、入浴の思ひ出…",
		TRINKET_9 = "ボタン？押しても、何も起きないヨ？",
		TROPICALFAN = "潮風みたいに涼しいネ",
		MINIFAN = "潮風みたいに涼しいネ",
		TROPICAL_FISH = "活きのいいのが釣れたヨ！",
		TRUNKVEST_SUMMER = "夏を涼しく、オシャレに乗り切るヨ！",
		TRUNKVEST_WINTER = "トレンディな、あったかウェアだヨ！",
		TRUNK_COOKED = "これは…何を添えてもマズそうネ…",
		TRUNK_SUMMER = "ケモノくさいネ…",
		TRUNK_WINTER = "良質…とはいえない肉ネ",
		TUMBLEWEED = "どんな秘密を抱えてるノ？",
		TUNACAN = "マグロの油漬けだヨ！",
		TURBINE_BLADES = "フードプロセッサーの刃カナ？",
		TURF_SANDY = "地面の材料…カナ？",
		TURF_ASH = "地面の材料…カナ？",
		TURF_BADLANDS = "地面の材料…カナ？",
		TURF_BEACH = "地面の材料…カナ？",
		TURF_CARPETFLOOR = "はだしで歩くと気持ちいいネ…",
		TURF_CAVE = "It's like an ingredient for the ground.",
		TURF_CHECKERFLOOR = "地面の材料…カナ？",
		TURF_DECIDUOUS = "It's like an ingredient for the ground.",
		TURF_DESERTDIRT = "地面の材料…カナ？",
		TURF_DIRT = "地面の材料…カナ？",
		TURF_FOREST = "地面の材料…カナ？",
		TURF_FUNGUS = "地面の材料…カナ？",
		TURF_FUNGUS_GREEN = "地面の材料…カナ？",
		TURF_GRASS = "芝刈りしないとダメ？めんどくさいネ…",
		TURF_JUNGLE = "地面の材料…カナ？",
		TURF_MARSH = "地面の材料…カナ？",
		TURF_MEADOW = "地面の材料…カナ？",
		TURF_MUD = "地面の材料…カナ？",
		TURF_ROCKY = "地面の材料…カナ？",
		TURF_SAVANNA = "地面の材料…カナ？",
		TURF_SINKHOLE = "地面の材料…カナ？",
		TURF_SWAMP = "地面の材料…カナ？",
		TURF_UNDERROCK = "地面の材料…カナ？",
		TURF_VOLCANO = "地面の材料…カナ？",
		TURF_WOODFLOOR = "地面の材料…カナ？",
		TURKEYDINNER = "おなかいっぱいに食べたら、眠くなるネ！",
		TWIGS = "かまどに火をおこすとき、重宝するネ",
		UMBRELLA = "屋内では、開いちゃダメだヨ",
		UNAGI = "ウナギのウマミ！絶品ネ！",
		UNIMPLEMENTED = "未完成ネ",
		VENOMGLAND = "食べたら、おなか痛くなりそうネ！",
		VINE = "ブドウは、なってないネ…",
		VOLCANO = "はあ…カンベンしてヨ…",
		VOLCANOSTAFF = "取り扱い注意ネ",
		VOLCANO_ALTAR =
		{
			GENERIC = "何かの祭壇…カナ？",
			OPEN = "プレゼントあげればいいのカナ…？",
		},
		VOLCANO_ALTAR_BROKEN = "これじゃ、プレゼントあげられないヨ！",
		VOLCANO_EXIT = "とっととズラかるヨ！",
		BANANAPOP = "調理手順は簡単だけど、とてもおいしいヨ",
		BISQUE = "トレビア～ン！",
		CEVICHE = "ん～、言うことなしネ！",
		SEAFOODGUMBO = "おばあちゃんの味、思い出すネ！",
		SURFNTURF = "ん～！絶品ネ！",
		SHARKFINSOUP = "おばあちゃんの秘伝のレシピだヨ！",
		LOBSTERDINNER = "無人島でも、美食はあきらめないヨ！",
		LOBSTERBISQUE = "特別おいしく仕上がったヨ！",
		JELLYOPOP = "ウーム…フシギな味がするネ…",
		WAFFLES = "ブランチにぴったりネ！",
		WALLYINTRO_DEBRIS = "なんだか、後味悪いネ…",
		WALL_HAY =
		{
			BURNT = "やっぱりネ…",
			GENERIC = "これ…壁って呼べるのカナ…？",
		},
		WALL_HAY_ITEM = "干し草の束を、壁の形にまとめたヨ",
		WALL_LIMESTONE = "セッカイ岩の、デッカイ壁！",
		WALL_LIMESTONE_ITEM = "セッカイ岩の壁…なんて、おセッカイな！",
		WALL_RUINS = "彫刻がウツクシイネ…",
		WALL_RUINS_ITEM = "古代の歴史が刻まれてる…スバラシイネ…",
		WALL_STONE = "石を加工した壁ネ",
		WALL_STONE_ITEM = "これなら安全そうネ",
		WALL_WOOD =
		{
			BURNT = "木は火に弱い…当たり前ネ",
			GENERIC = "地面に打ち込めば、壁になるネ",
		},
		WALL_WOOD_ITEM = "“き”のきいた壁になりそうネ！",
		WALRUS = "思ったより、すばやいネ…",
		WALRUSHAT = "チョット、カビくさいネ…",
		WALRUS_CAMP =
		{
			EMPTY = "空き家だヨ",
			GENERIC = "アウトドア派のひとが作ったのカナ？",
		},
		WALRUS_TUSK = "死んでしまったら、もう必要ないネ",
		WARG = "群れのボス、カナ？",
		WASPHIVE = "普通のハチじゃないヨ！",
		WATERMELON = "みんな大好きなフルーツだヨ！",
		WATERMELONHAT = "ん～、ひんやりスウィ～ト！",
		WATERMELONICLE = "子どもの頃を思い出すネ！",
		WATERMELON_COOKED = "ミントとフェタチーズを添えたいネ…",
		WATERMELON_SEEDS = "スイカをたらふく食べられるヨ！",
		WEBBERSKULL = "こっち見んナ！土に埋めるゾ！",
		WETGOOP = "スーシェフに見つからなくてよかったヨ…",
		WHALE_BLUE = "どうして泣いてるのカナ…？",
		WHALE_BUBBLES = "これは…ナンダ？",
		WHALE_CARCASS_BLUE = "クジラの死骸…ずいぶんでかいネ…",
		WHALE_CARCASS_WHITE = "クジラの死骸…ずいぶんでかいネ…",
		WHALE_WHITE = "コイツは…悪魔ダ！",
		WILDBORE = "このブタはチョット凶暴そうネ…",
		WILDBOREHOUSE = "意外とフツーの家に住んでるネ",
		WINTERHAT = "寒くなったら、すぐにこれをかぶるヨ！",
		WINTEROMETER =
		{
			BURNT = "お先“まっクロ”、ネ",
			GENERIC = "これで、いつ春が来るか、わかるネ",
		},
		WOODLEGS_CAGE = "アノ～、すみませ…いえ、なんでもないデス…",
		WOODLEGS_KEY1 = "なんだかチョット、恐ろしいカギだネ",
		WOODLEGS_KEY2 = "なんだかチョット、恐ろしいカギだネ",
		WOODLEGS_KEY3 = "なんだかチョット、恐ろしいカギだネ",
		VOLCANO_SHRUB = "これは…どんな木だったのカナ？",
		ROCK_OBSIDIAN = "ツルハシじゃダメだヨ！爆弾じゃないと！",
		ROCK_CHARCOAL = "バーベキューになった岩ネ",
		DRAGOONDEN = "ボク…コイツら、苦手ダヨ…",
		WORM =
		{
			DIRT = "汚ない。",
			PLANT = "とくにアヤシイところはないヨ",
			WORM = "でっかいミミズね！",
		},
		WORMHOLE =
		{
			GENERIC = "地面に、歯が生えた穴があるヨ！？",
			OPEN = "ここに…入るノ…？ホンキ…？",
		},
		WORMHOLE_LIMITED = "これはまた…一段と、キモチワルイネ…",
		WORMLIGHT = "光輝くおいしさだヨ！",
		YELLOWAMULET = "身につけると、足取りが軽くなるヨ！",
		YELLOWGEM = "レモンが恋しいヨ…",
		YELLOWSTAFF = "大鍋かき混ぜるのにチョウドイイネ！",

		ARMORCACTUS = "作るとき、トゲが刺さって痛かったヨ…",
		BIGFISHINGROD = "原始的な食材捕獲装置ネ",
		--BOOK_METEOR = "There's not a single recipe to be found within.",
		BRAINJELLYHAT = "謎の液体が染み出てるネ…アイデアの素？",
		BUOY = "オオ…わが道を照らす光ヨ！",
		COCONUT_HALVED = "おいしゅうございマス",
		COFFEEBOT = "これはすばらしいネ！",
		CRATE = "食料が入ってるといいネ…",
		DEPLETED_BAMBOOTREE = "そのうちまた、生えてくるカモ？",
		DEPLETED_BUSH_VINE = "しばらく待たないと、生えてこないネ",
		DEPLETED_GRASS_WATER = "また生えてくるカナ…",
		DOYDOYEGG_COOKED = "ボナペティ！",
		DRAGOONEGG = "食べられないタマゴには、興味ないネ…",
		DRAGOONHEART = "死んでるのに、触るとすごく熱いネ",
		DRAGOONSPIT = "汚いし、近づくと危ないヨ！",
		DUG_BUSH_VINE = "好きなところに植えられるネ",
		FRESHFRUITCREPES = "なんて美しいデザート！",

		KRAKEN = "こんな怪物、ボクにも料理できないネ！",
		KRAKENCHEST = "どんなお宝、入ってるカナ？",
		KRAKEN_TENTACLE = "料理酒かけて、躍り食いしたいネ！",
		MAGIC_SEAL = "魔力が、したたり落ちてるヨ！",
		MAGMAROCK_FULL = "岩は、いいワネ！…な～んてネ",
		MAGMAROCK_GOLD_FULL = "金箔、採れるカナ？",
		MALE_PUPPET = "タイヘン！助けてあげなきゃ！",
		MANRABBIT_TAIL = "モフモフして、心地よい触感ネ",
		MARBLETREE = "とっても、とっても、怪しい木だヨ！",
		MONKEYBALL = "カワイイけど…バナナがもったいないヨ",
		MONSTERTARTARE = "料理という芸術に対する冒涜だヨ！",
		MUSSELBOUILLABAISE = "芸術的なひと皿！ココロが踊り出すヨ！",
		MYSTERYMEAT = "これは、食べ物じゃないネ…",
		OXHAT = "コック帽より、耐水性に優れてるネ",
		OX_FLUTE = "愉快な音楽を奏でるヨ",
		OX_HORN = "猛々しいケモノの置き土産ネ",
		PANDORASCHEST = "ずいぶん立派な箱ネ",
		PARROT_PIRATE = "人なつっこい鳥ネ…仲良くなれるカナ…？",
		PEG_LEG = "なんでこんなの、拾ったカナ…",
		PERD = "とってもグルメな鳥さんネ",
		PIRATEGHOST = "いいオバケかもしれないけど…怖いネ",
		RAWLING = "髪、とかしたほうがいいヨ…？",
		RELIC =
		{
			BROKEN = "アアァ…料理の歴史を伝える、貴重な資料が…",
			GENERIC = "古代の台所用品ネ",
		},
		RESEARCHLAB4 =
		{
			BURNT = "灰になってしまったヨ",
			GENERIC = "この名前…なんて読むのかワカラナイヨ～…",
		},

		ROOK_NIGHTMARE = "なんてオソロシイ！",
		RUBBLE = "破壊の跡ネ",
		RUINS_RUBBLE = "破壊の跡ネ",
		SAIL_STICK = "鍋をかき混ぜるのに、ちょうどいいかもネ",
		SHADOWSKITTISH_WATER = "まったく…",
		SHARKITTENSPAWNER =
		{
			GENERIC = "近づかないほうがいいかもネ",
			INACTIVE = "ごく普通の砂山だヨ",
		},
		SHIPWRECKED_ENTRANCE = "ボンジュール！",
		SHIPWRECKED_EXIT = "アデュー！",
		SNAKESKINSAIL = "香辛料の国へ、行けるカナ？",
		SPEAR_LAUNCHER = "これで簡単に食材が獲れるヨ！",
		SWEETPOTATOSOUFFLE = "ココロも満たす、栄養満点の一皿ネ",
		SWIMMINGHORROR = "あまりお近づきにはなりたくないヨ…",
		TIGEREYE = "食材になりそうネ",
		TRINKET_20 = "フクザツな装置ネ…",
		TRINKET_21 = "ボクが乗るには小さすぎるヨ…",
		TRINKET_22 = "ディナーのテーブルにぴったりネ！",
		TURF_CAVE = "地面の材料…カナ？",
		TURF_DECIDUOUS = "地面の材料…カナ？",
		TURF_FUNGUS_RED = "地面の材料…カナ？",
		TURF_MAGMAFIELD = "地面の材料…カナ？",
		TURF_ROAD = "地面の材料…カナ？",
		TURF_SNAKESKINFLOOR = "地面の材料…カナ？",
		TURF_TIDALMARSH = "地面の材料…カナ？",
		TWISTER = "天然のミキサーだヨ！",
		TWISTER_SEAL = "食べたらきっと、おいしい…ケド…",
		VOLCANO_ALTAR_TOWER = "アア、神様ッ！",
		WATERYGRAVE = "開けてみようカナ…",
		WHALE_TRACK = "近くに獲物がいるヨ！",
		WILBUR_CROWN = "ついに、シェフキングと認められたヨ！",
		WILBUR_UNLOCK = "サルくん！ゴキゲンヨウ！",
		WILDBOREHEAD = "誰か、高級ジャーキー作ってる…？",
		WIND_CONCH = "ふるさとのコンクサラダが懐かしいヨ…",
		WOODLEGSBOAT = "あの船…チョット遅いネ…",
		WOODLEGSHAT = "チョット…キケンな気分になるネ",
		WOODLEGSSAIL = "いつでも海に出られるヨ！",
		WRECK = "これじゃもう、航海は無理ネ",
		CALIFORNIAROLL = "和食と西洋料理のマリアージュ！",
	},
	DESCRIBE_GENERIC = "これは…ナニカ、だネ",
	DESCRIBE_SMOLDERING = "こんがり焼けちゃいそうだヨ",
	DESCRIBE_TOODARK = "なんにも見えないヨ！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "この卵は…ちょっと新鮮すぎかもネ…",
	},
}
