return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "그것을 좋아할 것 같진 않군.",
			GENERIC = "왜?",
			NOBITS = "하지만 이미 아기 엉덩이처럼 매끈하군.",
		},
		STORE =
		{
			GENERIC = "들어가지 않지.",
			NOTALLOWED = "그 안에 들어가지 않는다.",
		},
		WRITE =
        {
            GENERIC = "지금은 할 수 없지.",
        },
		RUMMAGE =
		{	
			GENERIC = "저주스럽군.",	
		},
		COOK =
        {
            GENERIC = "계획대로 되는 것이 없군.",
            TOOFAR = "가까이 다가가야 하겠구나.",
        },
        CHANGEIN =
        {
            GENERIC = "어떻게 완벽함을 개선할 수 있지?",
            BURNING = "아. 마음에 드는 손수건이 다 사라졌군.",
        },
        GIVE =
        {
            DEAD = "죽은 자에게는 필요 없는 것이군.",
            SLEEPING = "충분히 무의식 상태군.",
            BUSY = "바쁘군.",
        },
        TEACH =
        {
            KNOWN = "나는 이것보다 이미 상당히 우월하지.",
            CANTLEARN = "비밀의 지식을 건드리면 보복이 돌아오지.",
        },
		REPAIRBOAT =
		{
			GENERIC = "지금은 안 되는군.",
		},

	},
	ACTIONFAIL_GENERIC = "안 됐군.",
	ANNOUNCE_MAGIC_FAIL = "그런 마법은 여기의 것이 아니지.",
    ANNOUNCE_NOSLEEPONFIRE = "최고의 아이디어는 아니군.",
	ANNOUNCE_NODANGERSIESTA = "추적하고 있군!",
	ANNOUNCE_NONIGHTSIESTA = "시에스타 시간이 아니라 수면 시간이지.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "그것을 하기엔 밖이 좀 오싹하지.",
	ANNOUNCE_NOHUNGERSIESTA = "전통적으로 시에스타는 먹은 다음에 오지, 그 전이 아니라.",
	ANNOUNCE_SHELTER = "나를 보호하라, 초라한 나무!",
	ANNOUNCE_BURNT = "타는군!",
	ANNOUNCE_TOOL_SLIP = "빌어먹을.",
	ANNOUNCE_DAMP = "축축한 것은 말쑥하지 않지.",
	ANNOUNCE_WORMS = "끔찍한 것이 오는군.",
	ANNOUNCE_WET = "물은 좋은 슈트를 망친다는 사실을 알고 있나?",
	ANNOUNCE_WETTER = "두 번 다시 마를 것 같지 않군.",
	ANNOUNCE_SOAKED = "물보다 더 축축하군.",
	ANNOUNCE_ADVENTUREFAIL = "내가 아니면 누가 이것을 하겠나.",
	ANNOUNCE_BEES = "날 죽인다고 네 꿀이 돌아오진 않지!",
	ANNOUNCE_BOOMERANG = "이런! 제기랄... 서투르군!",
	ANNOUNCE_CHARLIE = "찰리인가? 나다! 맥스웰!",
	ANNOUNCE_CHARLIE_ATTACK = "이런! 찰리, 그건 아프군!",
	ANNOUNCE_COLD = "심장이 차가워지고 있군.",
	ANNOUNCE_HOT = "내 심장이 열을 견딜 수 없군!",
	ANNOUNCE_CRAFTING_FAIL = "음... 그것은 할 수 없지.",
	ANNOUNCE_DEERCLOPS = "하나가 돌아오는 것이 들리는군.",
	ANNOUNCE_DUSK = "곧 어두워지겠군. 찰리가 깨어나겠지.",
	ANNOUNCE_EAT =
	{
		GENERIC = "(꿀꺽!)",
		PAINFUL = "이런! 내 입을 아프게 하는군!",
		SPOILED = "부패했군.",
		STALE = "유효 기간이 지났군.",
		INVALID = "저것을 내 입 근처에 가져가지도 않겠어.",
		YUCKY = "문명인은 이런 것을 먹지 않지.",  
	},
	ANNOUNCE_ENTER_DARK = "어둡군! 보이지 않는군!",
	ANNOUNCE_ENTER_LIGHT = "빛이 다시 생겼군.",
	ANNOUNCE_FREEDOM = "자유군, 드디어!",
	ANNOUNCE_HIGHRESEARCH = "두뇌에 능력이 가득 차고 있지!",
	ANNOUNCE_HOUNDS = "개가 불안해 하는군.",
	ANNOUNCE_HUNGRY = "속이 비었군.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "배설물과 짐승의 땀 냄새가 나는군.",
	ANNOUNCE_HUNT_LOST_TRAIL = "빌어먹을! 도망갔군.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "이 상태에서는 추적할 수 없군!",
	ANNOUNCE_INV_FULL = "주머니가 가득 찼군.",
	ANNOUNCE_KNOCKEDOUT = "윽. 머리가 아프군.",
	ANNOUNCE_LOWRESEARCH = "그리 유익하지 않았군.",
	ANNOUNCE_MOSQUITOS = "성가신 작은 벌레군.",
	ANNOUNCE_NODANGERSLEEP = "위험할 때는 할 수 없지!",
	ANNOUNCE_NODAYSLEEP = "낮에는 잘 수 없지.",
	ANNOUNCE_NODAYSLEEP_CAVE = "지금 자면 내 수면 스케줄에 문제가 생기겠지!",
	ANNOUNCE_NOHUNGERSLEEP = "너무 배고프군. 잠잘 수 없군.",
	ANNOUNCE_NO_TRAP = "이상하군. 설치하는 것을 잊었군.",
	ANNOUNCE_PECKED = "인내심을 가지시지!",
	ANNOUNCE_QUAKE = "떨리는 것이 좋은 징조가 아니군.",
	ANNOUNCE_RESEARCH = "지식이 힘이지. 그리고 힘은... 힘이지.",
	ANNOUNCE_THORNS = "이것을 하느라 팔을 긁혔군.",
	ANNOUNCE_TORCH_OUT = "젠장, 불이 또 꺼졌군.",
	ANNOUNCE_FAN_OUT = "휴식이 끝났군.",
	ANNOUNCE_COMPASS_OUT = "나침반이 조각 났군.",
	ANNOUNCE_TRAP_WENT_OFF = "악!",
	ANNOUNCE_UNIMPLEMENTED = "흠, 아직 안 됐군.",
	ANNOUNCE_WORMHOLE = "으윽. 안이 끔찍하군.",
	ANNOUNCE_CANFIX = "\n고칠 수 있을 것 같아!",
	ANNOUNCE_NOSANITY = "심한 두통이 느껴지는군!",
	ANNOUNCE_NOFUEL = "악몽 연료가 필요하군.",
	ANNOUNCE_NOWARDROBEONFIRE = "농담인가?",
	ANNOUNCE_ACCOMPLISHMENT= "어떻게든 시간을 보내야 하겠지.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "어쨌든 잘 됐군.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "약간 도움되었군.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "누구를 건드리는 것이지!",
	ANNOUNCE_OTHER_WORLD_PLANT = "이것을 여기에 심을 수는 없지.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"악필이라 못 읽겠군.",
	},
	ANNOUNCE_BOAT_DAMAGED = "배가 손상을 받았군.",
	ANNOUNCE_BOAT_SINKING = "새게 만들었군.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "고생 끝에 이렇게 끝나는 건가?!",
	ANNOUNCE_CRAB_ESCAPE = "교활한 갑각류...",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "심연이 나를 빨아들이는군!",
	ANNOUNCE_MAPWRAP_RETURN = "다행이라는.",
	ANNOUNCE_MAPWRAP_WARN = "안개 근처에는 가기 싫지.",
	ANNOUNCE_MORETREASURE = "아. 잃어버린 보물로 가는 또 다른 지침이군.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "이 보물이 근처에 있을 것이라고 생각되지 않는군.",
	ANNOUNCE_SHARX = "나를 추적하는 것 같지.",
	ANNOUNCE_TRAWL_FULL = "어망이 터질듯이 가득 찼군!",
	ANNOUNCE_TREASURE = "이것을 따라가면 보물이... 나오겠지.",
	ANNOUNCE_VOLCANO_ERUPT = "그렇게 폭발할 필요가 없지.",
	ANNOUNCE_WAVE_BOOST = "정말이지!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "짐승을 추격해야지!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "물고기가 날 속였군!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "고래의 흔적을 잃었군!",

	BATTLECRY =
	{
		GENERIC = "공격하지!",
		PIG = "힘보다 지능이지!",
		PREY = "넌 맛있어 보이는군!",
		SPIDER = "날 다시 놀리지 못하게 하지!",
		SPIDER_WARRIOR = "어쩔 수 없이 싸우게 만들었거든!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "그리고 꺼져!",
		PIG = "다음에 보지, 돼지!",
		PREY = "너는 내 시간을 할애할 가치가 없군!",
		SPIDER = "다음에는... 바보 취급당하지 않겠어!",
		SPIDER_WARRIOR = "다음엔 장갑을 벗고 싸우겠어!",
	},
	
	DESCRIBE =
	{
		LICHEN = "A slow growing cave plant.",
		ICEHOUND = "빨리 타는군...",
		INVENTORYGRAVE = "누가 이것을 소유했었을까. 흠?",
		INVENTORYMOUND = "그녀가 다른 희생자를 만들었군.",
		GLOMMER = "날아다니는 점액 공장이군.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "꽃의 힘이군.",
        	DEAD = "영원한 꽃의 힘이군.",
        },
        GLOMMERWINGS = "들러붙는군.",
        GLOMMERFUEL = "흠, 고약하군.",
        BELL = "종이 더 있군.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "뭐, 저것은 나의 조각상이 아니군!",
        	EMPTY = "내가 아니라는 것이 문제지.",
    	},
		WEBBERSKULL = "그리 쉽게 탈출할 수 있을 것이라고 생각하지 마시지.",
		MOLE =
		{
			HELD = "종착역이군.",
			UNDERGROUND = "너는 내가 놓는 것을 집는가? 이해하지?",
			ABOVEGROUND = "\"예\"라고 받아들이지.",
		},
		MOLEHILL = "깊게 파고 들어가시지, 내가 쫓아갈 테니.",
		MOLEHAT = "그래서 몇 시간 동안이나 팔 수 있군.",
		NIGHTSTICK = "안녕한가.",
		RABBITHOUSE=
		{
			GENERIC = "오, 영리하군.",
			BURNT = "영리해서 당근을 죽였군.",
		},
		TURF_DECIDUOUS = "표층이지.",
		TURF_SANDY = "표층이지.",
		TURF_BADLANDS = "표층이지.",
		BEARGER = "원하는 것은 무엇이든 가져.",
		BEARGERVEST = "내 조끼를 구경하시지.",
		ICEPACK = "내용물이 동면하고 있군.",
		BEARGER_FUR = "괜찮은 양탄자를 만들 수 있겠군.",
		BIGFOOT = "저것이야말로 악몽의 연료군.",
		BONESHARD = "가는 뼈군.",
		BUZZARD = "부패의 미식가군.",
		CACTUS = 
		{
			GENERIC = "부푼 식물이지.",
			PICKED = "선인장? 이젠 납작하군!",
		},
		CACTUS_MEAT_COOKED = "선인장 식품이군.",
		CACTUS_MEAT = "입 안에 넣는 것은 현명한 행위가 아니겠지.",
		CACTUS_FLOWER = "선인장의 이 부분은 언제나 좋지.",
		COLDFIRE =
		{
			EMBERS = "없어지겠군.",
			GENERIC = "위안이군.",
			HIGH = "지금은 저것이 찰리를 접근하지 못하게 하겠군.",
			LOW = "연료가 필요하군.",
			NORMAL = "차갑고 뜨겁군.",
			OUT = "돌아오지 않겠군.",
		},
		CATCOON = "고양이 같은 해수군.",
		CATCOONDEN = 
		{
			GENERIC = "해수의 집이군.",
			EMPTY = "그런 것이군.",
		},
		CATCOONHAT = "죽은 머리지.",
		COONTAIL = "꼬리의 이야기군.",
		COOKPOT =
		{
			COOKING_LONG = "기다리지...",
			COOKING_SHORT = "되고 있군!",
			DONE = "이제 제대로 된 음식을 먹겠군.",
			EMPTY = "생각만으로도 입에 침이 고이는군.",
			BURNT = "내 입맛에 비해 심하게 요리했군.",
		},
		EYEBRELLAHAT =	"하늘의 눈이군.",
		ARMORDRAGONFLY = "날개 달린 갑옷이군.",
		DRAGON_SCALES = "불 같군.",
		DRAGONFLYCHEST = "비늘이 멋지군.",
		DECIDUOUSTREE = 
		{
			BURNING = "아차.",
			BURNT = "불로 목욕했군.",
			POISON = "입을 닥치지 못할까!",
			CHOPPED = "다시 자라지 않겠군.",
			GENERIC = "\"무성하다\"고 표현한 것을 들은 적이 있지.",
		},
		ACORN_COOKED = "열린 불 위에서.",
		BIRCHNUTDRAKE = "다리가 있는 너트라! 공포스럽군!",
		FARMPLOT =
		{
			GENERIC = "내가 농부로 보이나?",
			GROWING = "식물의 성장을 것보다는 중요한 일이 많지.",
			NEEDSFERTILIZER = "영양을... 줘야겠군.",
			BURNT = "재를 수확하는군.",
		},
		COLDFIREPIT =
		{
			EMBERS = "신경 써야겠군.",
			GENERIC = "불 구덩이입니다.",
			HIGH = "타오르는 차가운 불이군.",
			LOW = "약해지고 있군.",
			NORMAL = "차갑군.",
			OUT = "미지근해졌군.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "꺼져라, 불!",
			OFF = "폭풍 전의 고요군.",
			LOWFUEL = "연료가 얼마 남지 않았군.",
		},
		ICEHAT = "머리에 얼음을 싸매는 것이지.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "뭘 언제나 씹고 있는 것이지?",
			CHARGED = "충전하라!",
		},
		LIGHTNINGGOATHORN = "괜찮은 뿔을 만들 수 있겠군.",
		GOATMILK = "영양이 가득 들었군.",
		MEATRACK =
		{
			DONE = "사막처럼.",
			DRYING = "아직 습하군.",
			DRYINGINRAIN = "계속 습한 상태겠군.",
			GENERIC = "더 오래 먹을 수 있도록 고기를 건조할 수 있지.",
			BURNT = "고기를 걸기에는 아직 약하군.",
		},
		MERMHEAD = 
		{
			GENERIC = "눈이 목표를 쫓지.",
			BURNT = "구운 어인 머리군. 맛있군.",
		},
		MERMHOUSE = 
		{
			GENERIC = "돼지를 따라 했지만 지능이 더욱 낮군.",
			BURNT = "돼지의 것처럼 잘 타는군.",
		},
		FLOWERSALAD = "잎이 무성하군.",
        ICECREAM = "선디, 선디, 선디군!",
        BANANAPOP = "흠... 내가 뭘 기대한 것일까.",
        BISQUE = "음식은 좋지만 분위기가 떨어지는군.",
        CEVICHE = "훌륭하고 교양이 넘치는 요리군.",
        SEAFOODGUMBO = "괜찮겠군.",
        SURFNTURF = "영양을 골고루 갖춘 식사군.",
        SHARKFINSOUP = "나의 고급스러운 입맛은 위험을 즐기지.",
        LOBSTERDINNER = "턱받이를 안 가져왔군.",
        LOBSTERBISQUE = "아, 나에겐 고급스러운 것이 어울리지.",
        JELLYOPOP = "흠... 나의 세련된 모습과 어울리지 않는군.",
        WATERMELONICLE = "차가운 수박 덩어리군.",
        TRAILMIX = "너트와 베리군. 볼트는 없지.",
        HOTCHILI = "아주 뜨겁다!",
        GUACAMOLE = "몰이 섞여 있군.",
		MOOSE = "뭐든 간에 분명히 북부에서 온 것이군.",
		MOOSEEGG = "번개를 타고 달려라, 큰 알.",
		MOSSLING = "복슬복슬한... 것이군.",
		FEATHERFAN = "바람이 부는가 아니면 내 부채 때문인가?",
		TROPICALFAN = "바람이 부는가 아니면 내 부채 때문인가?",
		GOOSE_FEATHER = "이것으로 가득 채운 베개를 쓰고 싶군.",
		STAFF_TORNADO = "풍력이군.",
		PIGHEAD = 
		{	
			GENERIC = "어... 매력적이군.",
			BURNT = "돼지 구이!",
		},
		PIGHOUSE =
		{
			FULL = "내가 그라면 들어가겠지.",
			GENERIC = "안전한 구조가 아니지.",
			LIGHTSOUT = "바람을 불어라!",
			BURNT = "그 안에 숨는 것을 보지.",
		},
		FERTILIZER = "손으로 비료를 만지는 것은 신사가 할 일이 아니지.",
		RAINOMETER = 
		{	
			GENERIC = "조사 좀 하면 같은 것을 배울 수 있겠군.",
			BURNT = "비가 제 시간에 오지 않았군.",
		},
		RAINCOAT = "가라, 비!",
		RAINHAT = "가장 말쑥한 모자는 아니지만 유용하지.",
		RESEARCHLAB = 
		{	
			GENERIC = "이것을 만드는 방법을 잊었다는 사실을 믿을 수 없군.",
			BURNT = "불이 태우는 방법을 익혔군.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "보통 수준의 방법을 잠금 해제하지.",
			BURNT = "화염이 전체를 삼켰군.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "여기에서 내 연구를 하지.",
			BURNT = "연구 완료군.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "꽤 말쑥한 기계군.",
			BURNT = "뜨거워서 관리하기 어려웠군.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "나라도 이것을 사용해야겠지.",
			BURNT = "더 이상 사용할 수 없겠군.",
		},
		ROCK_ICE = 
		{
			GENERIC = "바위에서 얼음을 쪼아낼 수 있겠군.",
			MELTED = "단순한 웅덩이일 뿐이지.",
		},
		ROCK_ICE_MELTED = "단순한 웅덩이일 뿐이지.",
		ICE = "아기 빙하군.",
        REFLECTIVEVEST = "말쑥한 것보다는 안전이 우선이군.",
		HAWAIIANSHIRT = "가장 말쑥한 차림이군.",
		TENT = 
		{
			GENERIC = "내 취향에 비해서는 조금 조야하군.",
			BURNT = "내 취향에 비해서는 조금 탔군.",
		},
		SIESTAHUT = 
		{
			GENERIC = "예스럽지만 훌륭한 그늘이군.",
			BURNT = "\"그늘\"이 없어졌군.",
		},
		TRANSISTOR = "어떻게 작동하는지 모르겠지만 작동하는군.",
		TREASURECHEST = 
		{
			GENERIC = "약탈품을 보관할 수 있는 공간이지.",
			BURNT = "지금은 아무 것도 보관할 수 없지.",
		},
		TUMBLEWEED = "굴러가라, 잡초.",
		GRASS_UMBRELLA = "\"말쑥\"하다기 보다는 \"예쁘군\".",
		PALMLEAF_UMBRELLA = "목적을 수행하지.",
		UNIMPLEMENTED = "신비롭군! 만지지 말아야겠군.",
		WALL_HAY = 
		{	
			GENERIC = "불이 잘 붙겠군.",
			BURNT = "내가 말했었지.",
		},
		WALL_WOOD = 
		{
			GENERIC = "적당히 강하지만 가연성이지.",
			BURNT = "강하지도 않고 가연성도 아니군.",
		},
		WARG = "알파군!",
		WATERMELON = "대부분이 물이지. 섬유질의 단 물이지.",
		WATERMELON_COOKED = "그릴한 수박이군.",
		WATERMELONHAT = "서늘하게 지내는 한 가지 방법이군. 끈적하기도 하지.",
		WINTEROMETER = 
		{
			GENERIC = "그리 유용한 발명품은 아니지.",
			BURNT = "전혀 관심 없지.",
		},
		LIVINGTREE = "얼굴을 가지고 있군.",
		ICESTAFF = "차가운 지팡이지.",
		WAXWELLJOURNAL = "미안하군, 찰리.",
		WORMLIGHT = "산뜻한 묘수군.",
		WORM =
		{
		    PLANT = "날 속일 수는 없지, 식물.",
		    DIRT = "무언가 움직이는군.",
		    WORM = "새로운 것이군!",
		},
		EEL = "깊은 곳에만 있지.",
		EEL_COOKED = "전체가 미끌거리는군.",
		UNAGI = "이것으로 만족할 수밖에 없군.",
		EYETURRET = "내 작품 중에서 좋은 것 중 하나지.",
		EYETURRET_ITEM = "이제 설치하기만 하면 되는군.",
		MINOTAURHORN = "이럴 수 밖에 없어서 미안하군, 오랜 친구.",
		MINOTAURCHEST = "거의 살아있는 것 같군.",
		THULECITE_PIECES = "여러 조각을 합쳐서 더 큰 조각을 만들 수 있지.",
		POND_ALGAE = "조류일 뿐이지.",
		GREENSTAFF = "이러한 형태의 집중형 도구에 의존해야겠군.",
		POTTEDFERN = "구식이군.",

		THULECITE = "무척 희귀하지만 유용한 재료지.",
		ARMORRUINS = "툴레사이트가 악몽 연료와 잘 섞이는군.",
		RUINS_BAT = "이 안에서 연료가 깊이 흐르고 있지.",
		RUINSHAT = "연료가 흘러야 하지.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "도시의 심장이 멈추었군.",	--calm phase
			WARN = "또 박동하는군.",	--Before nightmare
			WAXING = "박동이 빨라지고 있군.", --Nightmare Phase first 33%
			STEADY = "박동이 안정적이군.", --Nightmare 33% - 66%
			WANING = "박동이 약해지고 있군.", --Nightmare 66% +
			DAWN = "다시 진정하는군.", --After nightmare
			NOMAGIC = "박동이 여기에서는 영향이 없군.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "제대로 보존하지 않으면 저하하지.",
		ROOK_NIGHTMARE = "건설업자들이 버려두고 갔군.",
		KNIGHT_NIGHTMARE = "더 이상 수리할 수 없을 정도군.",
		MINOTAUR = "아니, 연료가 날 바꿔 놓았군.",	--Monster in labyrinth
		SPIDER_DROPPER = "이 세계의 생물들은 급속하게 진화하지.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "연료를 과도하게 사용한 것이 실패의 원인이었지.",	--Lights that activate during nightmare.
		RELIC = "They were all dead when I got here.",	--Fixed relic
		RUINS_RUBBLE = "The earthquakes have taken their toll.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "내가 왜 이것을 생각하지 못했는지 모르겠군.",	--Works as axe and pickaxe
		GREENGEM = "악몽 연료가 진정한 잠재력을 해방시킬 수 있지.",
		ORANGESTAFF = "이러한 형태의 집중형 도구에 의존해야겠군.",	--Teleports player.
		YELLOWAMULET = "나를 돋보이게 하겠군.",	--Emits light, player walks faster.
		GREENAMULET = "평소에는 정말 필요 없는 것이지.",	--Reduce cost of crafting

		SLURPER = "단순한 동물이지. 자고 먹기 위해서만 존재하지.",
		SLURPER_PELT = "죽음을 통해 이 동물이 나를 섬기는군!",
		ARMORSLURPER = "젖었고, 축축하고, 이상하게 속이 찬 느낌이군.",
		ORANGEAMULET = "간단한 마법이 가장 효과적일 때가 많지.",
		YELLOWSTAFF = "보석이 더 크면 훨씬 더 강하겠군.",
		YELLOWGEM = "이 안에 든 마법을 느낄 수 있군.",
		ORANGEGEM = "어떤 연료와 사용하면 꽤 강력하겠군.",
		TELEBASE = 
		{
			VALID = "이제 됐군.",
			GEMS = "연료에 포커스 포인트가 필요하군.",
		},
		GEMSOCKET = 
		{
			VALID = "준비되었군.",
			GEMS = "연료에 포커스가 필요하군.",
		},
		STAFFLIGHT = "그림자들이 물러가겠군.",
       	ANCIENT_ALTAR =
        {
        	WORKING = "Where are their gods now?",
        	BROKEN = "This can be partially restored.",
        },
        ANCIENT_ALTAR = "그들의 신은 지금 어디에 있나?",
        ANCIENT_ALTAR_BROKEN = "이것은 부분적으로 복원할 수 있지.",

        ANCIENT_STATUE = "한 때 긍지 높았던 종족이었지.",

		CAVE_BANANA = "입 안에 재가 있는 느낌이군.",
		CAVE_BANANA_COOKED = "날것보다 나쁘군.",
		CAVE_BANANA_TREE = "바나나처럼 보이지만 믿을 수 없군.",
		ROCKY = "이유가 있어서 이 놈들을 추방했었지.",
		
		HOUNDSTOOTH="패션을 위해 사용할 수 있겠군.",
		ARMORSNURTLESHELL="전혀 말쑥하지 않군.",
		BAT="윽. 못생긴 짐승이군.",
		BATBAT = "기분 좋은 폭력이지.",
		BATWING="그것을 먹을 수는 없지.",
		BATWING_COOKED="그래도 먹지는 않지.",
		BEDROLL_FURRY="그래도 쓸 데는 있지.",
		BUNNYMAN="나의 옛날 쇼를 떠올리게 하는군.",
		FLOWER_CAVE="이 아래는 너무 어둡군.",
		FLOWER_CAVE_DOUBLE="이 아래는 너무 어둡군.",
		FLOWER_CAVE_TRIPLE="이 아래는 너무 어둡군.",
		GUANO="메스껍군!",
		LANTERN="이것으로 그들을 멀리할 수 있으면 좋겠군.",
		LIGHTBULB="결국 꺼지겠지.",
		MANRABBIT_TAIL="어리석은 토끼군.",
		MUSHTREE_TALL="부패와 실패의 냄새가 나는군.",
		MUSHTREE_MEDIUM="월리를 찾아라?",
		MUSHTREE_SMALL="윽, 냄새가 나쁘군.",
		SLURTLE="저것은 기억나지 않는군...",
		SLURTLE_SHELLPIECES="서로 맞지 않는군.",
		SLURTLEHAT="싸워야 한다면 이것이 힘을 주겠지.",
		SLURTLEHOLE="혐오스럽군.",
		SLURTLESLIME="더 나은 방법이 있겠지.",
		SNURTLE="이상하군. 새로 생겼나 보군.",
		SPIDER_HIDER="까다로운 것이지.",
		SPIDER_SPITTER="작은 것이 사납군, 그렇지 않나?",
		SPIDERHOLE="저것이 어떻게 여기까지 내려왔지?",
		STALAGMITE="바위지. 엄청 따분한걸.",
		STALAGMITE_FULL="바위지. 엄청 따분한걸.",
		STALAGMITE_LOW="바위지. 엄청 따분한걸.",
		STALAGMITE_MED="바위지. 엄청 따분한걸.",
		STALAGMITE_TALL="석순이지. 엄청 따분한걸.",
		STALAGMITE_TALL_FULL="석순이지. 엄청 따분한걸.",
		STALAGMITE_TALL_LOW="석순이지. 엄청 따분한걸.",
		STALAGMITE_TALL_MED="석순이지. 엄청 따분한걸.",

		POWCAKE = "악의 끔찍한 발현인가?",
		CAVE_ENTRANCE = 
		{
			GENERIC= "내가 오래 전에 막았지.",
			OPEN = "좋은 아이디어가 아니군!",
		},
        CAVE_EXIT = "날 내보내주시지!",

		MAXWELLPHONOGRAPH = "저주스러운 것!",
		BOOMERANG = "자기 손을 더럽히는 것보다는 낫지.",
		PIGGUARD = "우왁. 역겨운 짐승이군.",
		ABIGAIL = "왜 이것들이 죽은 채로 있지 않나?",
		ADVENTURE_PORTAL = "내가 그것을 저기에 뒀었군!",
		AMULET = "우주의 가장 어두운 에너지가 흐르고 있지.",
		ANIMAL_TRACK = "어떤 멍청한 짐승이 여기를 통과했군.",
		ARMORGRASS = "대면해서 싸우는 것은 서투른 방법이지.",
		ARMORMARBLE = "정말 내 스타일이 아니군.",
		ARMORWOOD = "윽. 상스러운 주먹 싸움은 나에게 어울리지 않지.",
		ARMOR_SANITY = "악몽에 내 자신을 감쌀 시간이군.",
		ASH =
		{
			GENERIC = "파괴적인 향이 나는 미세한 분말이지.",
			REMAINS_GLOMMERFLOWER = "글로머는 언제나 하나 더 있지.",
			REMAINS_EYE_BONE = "안심해. 체스터는 언제나 더 있으니까.",
			REMAINS_THINGIE = "포털로 들어가서 알 수 없는 형체가 되었군.",
		},
		AXE = "어쩔 때는 직접적인 방법이 최고지.",
		BABYBEEFALO = "어리니까 더 추하군.",
		BACKPACK = "주위에 문지기가 있으면 좋겠군.",
		BACONEGGS = "좋은 아침 식사잖아.",
		BANDAGE = "끈적하고 상처를 감싸는 데 유용하지.",
		BASALT = "너무 무거운 돌을 만들어서 들 수도 없군.",
		BEARDHAIR = "털이 수북하군.",
		BEDROLL_STRAW = "거친 곳에서 자는 것은 즐기지 않지.",
		BEE =
		{
			GENERIC = "정말 부지런히 일하는군, 바보들.",
			HELD = "이제 이것으로 무엇을 하냐?",
		},
		BEEBOX =
		{
			FULLHONEY = "유혹적이지만 벌이 가득 들어있군.",
			GENERIC = "내 벌을 보관하지.",
			NOHONEY = "벌들이 충분히 열심히 일하지 않는군.",
			SOMEHONEY = "더 기다려야겠군.",
			BURNT = "허니 로스트군.",
		},
		BEEFALO =
		{
			FOLLOWER = "제기랄, 날 따라 오는군.",
			GENERIC = "저 멍청한 짐승을 보시지.",
			NAKED = "이제는 멍청하고 딱해 보이는군.",
			SLEEPING = "잠잘 때 약간 덜 멍청하군.",
		},
		BEEFALOHAT = "패션 센스 떨어지는군.",
		BEEFALOWOOL = "헛간 냄새가 나는군.",
		BEEHAT = "필요하다면 입어야겠지.",
		BEEHIVE = "벌은 안돼!",
		BEEMINE = "그들은 인내심을 가지고 기다리지.",
		BEEMINE_MAXWELL = "어쩌면 저기에 그것을 놓지 말았어야 되는군.",
		BERRIES = "흐음. 꼭 필요하다면 어쩔 수 없지.",
		BERRIES_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		BERRYBUSH =
		{
			BARREN = "비료가 필요하군.",
			WITHERED = "작은 덤불에게는 너무 뜨겁군.",
			GENERIC = "베리를 먹는 신세가 되었군. 흐음.",
			PICKED = "이제 기다리지.",
		},
		BIRDCAGE =
		{
			GENERIC = "날 두 번 다시 철창 뒤에 가둘 수는 없지.",
			OCCUPIED = "내 기분을 잘 알고 있지, 새.",
			SLEEPING = "일어난 다음에도 그 안에 있을 테지.",
			HUNGRY = "뭐가 문제지, 깃털아?",
			STARVING = "뭐지. 지난 주에 먹였는데.",
			DEAD = "깊이 잠들었군.",
			SKELETON = "자는 것이 아니었군.",
		},
		BIRDTRAP = "계속 속는군!",
		BIRD_EGG = "아기 새 감옥이라고 생각하고 싶군.",
		BIRD_EGG_COOKED = "노른자위를 위로.",
		BISHOP = "특히 저 말이 자랑스럽지.",
		BLOWDART_FIRE = "내쉬는 것을 잊지 말아야겠군.",
		BLOWDART_SLEEP = "나를 \"미스터 샌드맨\"이라고 불러다오.",
		BLOWDART_PIPE = "고통을 선사하는 영광의 통이군!",
		BLUEAMULET = "얼어붙었군.",
		BLUEGEM = "파란색이 얼음을 불러오지.",
		BLUEPRINT = "다 아는 것인데. 단지 잊었을 뿐.",
		BELL_BLUEPRINT = "다 아는 것인데. 단지 잊었을 뿐.",
		BLUE_CAP = "문제 없겠지?",
		BLUE_CAP_COOKED = "감칠맛 나는군!",
		BLUE_MUSHROOM =
		{
			GENERIC = "파란색은 무언가에 유용한 것이지.",
			INGROUND = "아직 준비되지 않았군.",
			PICKED = "아마 다른 시기에?",
		},
		BOARDS = "거칠게 잘라 만들었군.",
		BOAT = "아무 데도 가지 않겠군.",
		BONESTEW = "모든 재료를 쓰는 것이지.",
		BUGNET = "방어 능력이 없는 곤충을 잡을 때 좋겠군.",
		BUSHHAT = "나를 위한 공간이 있군.",
		BUTTER = "어떤 말장난은 참기 어렵지.",
		BUTTERFLY =
		{
			GENERIC = "비행하는 꽃이군.",
			HELD = "날개를 뜯으면 안타깝겠군.",
		},
		BUTTERFLYMUFFIN = "끝없는 날개짓을 멈추겠군.",
		BUTTERFLYWINGS = "하하하. 잡았군!",
		CAMPFIRE =
		{
			EMBERS = "없어지겠군.",
			GENERIC = "위안이군.",
			HIGH = "지금은 저것이 찰리를 접근하지 못하게 하겠군.",
			LOW = "연료가 필요하군.",
			NORMAL = "불 같군.",
			OUT = "돌아오지 않겠군.",
		},
		CANE = "빠른 것들의 그림이 새겨져 있지.",
		CARROT = "나는 채소를 좋아하지 않지.",
		CARROT_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		CARROT_PLANTED = "정말 평범하군.",
		CARROT_SEEDS = "나에게는 천한 노동이군.",
		CAVE_FERN = "밟고 싶게 만드는군.",
		CHARCOAL = "어떤 것도 내 탄소를 훔칠 수는 없지!",
        CHESSJUNK1 = "저걸 완성하지 않은 이유가 있었지.",
        CHESSJUNK2 = "못된 것이군.",
        CHESSJUNK3 = "저 얼굴이 마음에 들지 않는군.",
		CHESTER = "성가신 작은 괴물이군. 하지만 나름대로 역할이 있지.",
		CHESTER_EYEBONE =
		{
			GENERIC = "나를 그만 쳐다보지!",
			WAITING = "무엇을 기다리고 있나?",
		},
		COOKEDMANDRAKE = "힘을 많이 잃었군.",
		COOKEDMEAT = "이제 헛간 냄새가 덜 나는군.",
		COOKEDMONSTERMEAT = "필요하다면 먹어야겠는걸.",
		COOKEDSMALLMEAT = "적어도 더 이상 움직이지는 않는군.",
		CORN = "과당 함량이 높지.",
		CORN_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		CORN_SEEDS = "나에게는 천한 노동이군.",
		CROW =
		{
			GENERIC = "그들이 어떻게 여기에 왔는지 모르겠군.",
			HELD = "조용... 얘들아.",
		},
		LICHEN = "전락에서 살아남은 진균류지.",
		CUTLICHEN = "건조하고, 푸석푸석하고, 영양을 주지.",
		CUTGRASS = "땅에 흔히 있는 것이지.",
		CUTREEDS = "이것으로 유용한 것을 만들 수 있겠군.",
		CUTSTONE = "문명을 만드는 블록이군.",
		DEADLYFEAST = "냄새가... 유독하군.",
		DEERCLOPS = "저자는 나조차도 두렵군.",
		DEERCLOPS_EYEBALL = "외눈사슴은 근시지.",
		DEPLETED_GRASS =
		{
			GENERIC = "아무 짝에도 쓸모없군.",
		},
		DIRTPILE = "뭔가 이상해 보이는군.",
		DIVININGROD =
		{
			COLD = "대체로 배경 소음 뿐이군.",
			GENERIC = "이것을 사용하여 분실한 부품을 찾을 수 있지.",
			HOT = "등잔 밑이 어둡군!",
			WARM = "올바른 방향이군.",
			WARMER = "잘 보고 있어야겠군.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "시작 메커니즘이군.",
			READY = "탐지봉을 삽입해야 하는군.",
			UNLOCKED = "진전이군!",
		},
		DIVININGRODSTART = "이 포털은 다음 막대로 이어지지.",
		DRAGONFLY = "불 같은 파리군.",
		LAVASPIT = 
		{
			HOT = "불 뿜는 것이지.",
			COOL = "이제 차갑고 건조하군.",
		},
		DRAGONFRUIT = "이국적이고 맛있군.",
		DRAGONFRUIT_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		DRAGONFRUIT_SEEDS = "내가 하기에는 천한 노동이군.",
		DRAGONPIE = "절묘하군.",
		DRUMSTICK = "여전히 이상하게 베리 맛이 나는군.",
		DRUMSTICK_COOKED = "여전히 베리 맛이 나는군.",
		DUG_BERRYBUSH = "내가 정원사로 보이나?",
		DUG_GRASS = "내가 정원사로 보이나?",
		DUG_MARSH_BUSH = "내가 정원사로 보이나?",
		DUG_SAPLING = "내가 이렇게 초라해지다니.",
		DURIAN = "배워야 알 수 있는 맛이지.",
		DURIAN_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		DURIAN_SEEDS = "나에게는 천한 노동이군.",
		EARMUFFSHAT = "적어도 따뜻하긴 하군.",
		EGGPLANT = "또 하나의 따분한 식물이지.",
		EGGPLANT_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		EGGPLANT_SEEDS = "나에게는 천한 노동이군.",
		ACORN = 
		{
		    GENERIC = "야외가 좋은 자라면 이것으로 뭘 할 수 있겠군.",
		    PLANTED = "흠, 땅에 두어야 하는 것이군.",
		},
		EVERGREEN =
		{
			BURNING = "아차.",
			BURNT = "불로 목욕했군.",
			CHOPPED = "다시 자라지 않겠군.",
			GENERIC = "이를 \"소나무\"라고 표현한 것을 들은 적이 있지.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "아차.",
			BURNT = "먼지에서 먼지로 되는군요.",
			CHOPPED = "괴로움을 끝내줬지.",
			GENERIC = "병약해 보이는군.",
		},
		EYEPLANT = "고기 알뿌리의 끄나풀이군.",
		FEATHERHAT = "내 깃털로 유인해야겠군.",
		FEATHER_CROW = "검은색은 양의 색이지.",
		FEATHER_ROBIN = "빨간색을 불의 색이지.",
		FEATHER_ROBIN_WINTER = "회색은 고통의 색이지.",
		FEM_PUPPET = "나보단 남이 당하는 것이 낫지.",
		FIREFLIES =
		{
			GENERIC = "무척 예쁘군.",
			HELD = "원한다면 찌그러뜨릴 수 있겠지.",
		},
		FIREHOUND = "농담으로 불 보석을 박은 것이었지.",
		FIREPIT =
		{
			EMBERS = "신경 써야겠군.",
			GENERIC = "불 구덩이입니다.",
			HIGH = "타오르는 불이군.",
			LOW = "약해지고 있군.",
			NORMAL = "뜨겁지.",
			OUT = "차가워졌군.",
		},
		FIRESTAFF = "기본 마법이지만 효과적이지.",
		FISH = "어두운 심해에서 바로 나왔군.",
		FISHINGROD = "평생을 먹겠군.",
		FISHSTICKS = "배를 채우겠군.",
		FISHTACOS = "껍질이 바삭한 생선 요리군.",
		FISH_MED = "가만히 있어야지.",
		FISH_MED_COOKED = "여전히 악취가 나는군.",
		FISH_COOKED = "여전히 악취가 나는군.",
		FLINT = "이런! 손가락을 베었군!",
		FLOWER = "밟고 싶은 불합리한 충동이 생기는군.",
		FLOWERHAT = "전혀 내 스타일이 아니군.",
		FLOWER_EVIL = "저 꽃이 마음에 드는군.",
		FOLIAGE = "농부에게 어울리는 식사군.",
		FOOTBALLHAT = "드잡이를 할 준비가 되었군.",
		FROG =
		{
			DEAD = "죽었군.",
			GENERIC = "뛰어서 핥는 것이지.",
			SLEEPING = "피곤해 보이는군.",
		},
		FROGGLEBUNWICH = "약간 강렬한 맛이 나지.",
		FROGLEGS = "근육질이군.",
		FROGLEGS_COOKED = "힘줄이 느껴지는군.",
		FRUITMEDLEY = "간단한 치즈 플레이트와 어울리겠군.",
		GEARS = "나의 애완동물이군! 무슨 일이 있었지?",
		GHOST = "나를 기억하는군!",
		GOLDENAXE = "자를 때마다 날카로워지지.",
		GOLDENPICKAXE = "게임의 논리라는 것이군.",
		GOLDENPITCHFORK = "이것이 좋은 투자였는지 모르겠군.",
		GOLDENSHOVEL = "이 삽은 가격이 무척 높겠군.",
		GOLDNUGGET = "한 때는 나에게 중요했었지.",
		GRASS =
		{
			BARREN = "거름이 필요하군.",
			WITHERED = "풀이 이 열기를 견딜 줄 알았는데...",
			BURNING = "아차.",
			GENERIC = "군생하는군.",
			PICKED = "수확할 것이 없군.",
		},
		GREEN_CAP = "먹어야겠지.",
		GREEN_CAP_COOKED = "짜군!",
		GREEN_MUSHROOM =
		{
			GENERIC = "녹색 버섯이군.",
			INGROUND = "언제 이것이 올라오지?",
			PICKED = "다 보고. 다 해봤지.",
		},
		GUNPOWDER = "이것은 마음에 드는군.",
		HAMBAT = "덜 세련된 시대의 품위 없는 무기이지.",
		HAMMER = "다른 자의 작업을 망치는 것은 기분이 좋지.",
		HEALINGSALVE = "약간의 독액과 더럽고 오래된 재군.",
		HEATROCK =
		{	
			FROZEN = "쥐기 어려울 정도로 차갑군.",
			COLD = "기분 좋게 서늘하군.",
			GENERIC = "주머니에 들어가는 돌과 온기지.",
			WARM = "편안하게 따뜻하군.",
			HOT = "쥐기 어려울 정도로 뜨겁군.",
		},
		HOME = "가장 편한 곳이지.",
		HOMESIGN = 
		{
			GENERIC = "아무 의미... 없군.",
			BURNT = "어찌 된 게 전보다 의미 더 없군.",
		},
		HONEY = "끈적하고 달다.",
		HONEYCOMB = "벌 애벌레가 가득 들어있군.",
		HONEYHAM = "연하군.",
		HONEYNUGGETS = "애들이 먹는 것이지만 맛있군.",
		HORN = "짐승을 호출하라!",
		HOUND = "나를 못 알아보는군!",
		HOUNDBONE = "배고픈 마귀들이지?",
		HOUNDMOUND = "개 소굴로 내려가는 터널이군.",
		ICEBOX = "상자 안에 작은 겨울이 있군.",
		INSANITYROCK =
		{
			ACTIVE = "이제 진짜 모습을 볼 수 있군!",
			INACTIVE = "이 세계에 절반만 존재하고 있군.",
		},
		JAMMYPRESERVES = "나의 좋은 장갑을 망쳤군.",
		KABOBS = "완벽하게 요리했군.",
		KILLERBEE =
		{
			GENERIC = "벌이 왜 저리도 화난 상태이지?",
			HELD = "호랑이의 꼬리를 잡고 있는 격이군.",
		},
		KNIGHT = "훌륭한 장인의 솜씨군!",
		KOALEFANT_SUMMER = "고기물소의 먼 사촌이군.",
		KOALEFANT_WINTER = "겨울 코트를 입고 있군.",
		KRAMPUS = "날 잡을 순 없지!",
		KRAMPUS_SACK = "정말 가볍지.",
		LEIF = "역겨운 짐승이군!",
		LEIF_SPARSE = "역겨운 짐승이군!",
		LIGHTNING_ROD =
		{
			CHARGED = "에너지가 이를 통해 흐르지.",
			GENERIC = "약간의 보호를 제공하지.",
		},
		LITTLE_WALRUS = "부전자전이군.",
		LIVINGLOG = "태울 때 나는 소리가 마음에 들지.",
		LOCKEDWES = "화나게 만드는군.",
		LOG =
		{
			BURNING = "흐음. 그 동안은 재미있었지.",
			GENERIC = "나무 조각이군. 더 할 말이 있지 않겠지?",
		},
		LUREPLANT = "사나운 식물이군.",
		LUREPLANTBULB = "이것을 유리하게 써먹을 수 있을지도 모르겠군.",
		MALE_PUPPET = "나보단 남이 당하는 것이 낫지.",
		MANDRAKE =
		{
			DEAD = "귀가 아직도 울리는군.",
			GENERIC = "좀 닥치시지?",
			PICKED = "불쾌한 뿌리군.",
		},
		MANDRAKESOUP = "넌 더 이상 비명을 지를 수 없지.",
		MANDRAKE_COOKED = "내가 최후의 승자군.",
		MARBLE = "강한 것이군.",
		MARBLEPILLAR = "누가 이것을 만들었는지 언제나 궁금했었지.",
		MARBLETREE = "묘하군.",
		MARSH_BUSH =
		{
			BURNING = "질문을 해야겠군.",
			GENERIC = "나처럼 꼬여 있고 가시가 돋혔군!",
			PICKED = "고통스럽군.",
		},
		MARSH_PLANT = "무척이나 평범한 작은 식물이군.",
		MARSH_TREE =
		{
			BURNING = "끝나는군.",
			BURNT = "이제 누구에게도 쓸모없군.",
			CHOPPED = "나무 0점, 맥스웰 1점.",
			GENERIC = "품행이 단정치 못한 나무군.",
		},
		MAXWELL = "좋아 보이는군!",
		MAXWELLHEAD = "안녕한가, 미남.",
		MAXWELLLIGHT = "호오, 날 기억하는군.",
		MAXWELLLOCK = "지배자를 의자에 묶어 두지.",
		MAXWELLTHRONE = "보이는 것보다 덜 고통스럽군. 약간만.",
		MEAT = "나는 이것보다는 고급 요리에 익숙하지.",
		MEATBALLS = "요리사에게 찬사를 보내지!",
		MEAT_DRIED = "이것을 먹기에는 내 치아가 너무 약해진 것 같군.",
		MERM = "내가 여기에 왔을 때 그들이 이미 여기에 있었지.",
		MINERHAT = "반딧불이 결국 굶어 죽겠지.",
		MONKEY = "너를 위한 시간은 없지!",
		MONKEYBARREL = "끔찍히 더러운 집이군.",
		MONSTERLASAGNA = "섭취하는 것은 좋지 않지.",
		MONSTERMEAT = "무척 혐오스럽군.",
		MONSTERMEAT_DRIED = "이것을 먹기에는 내 치아가 너무 약해진 것 같군.",
		MOSQUITO =
		{
			GENERIC = "못된 흡혈 벌레.",
			HELD = "잡았지.",
		},
		MOSQUITOSACK = "피 주머니군. 피가 들었지.",
		MOUND =
		{
			DUG = "이미 획득한 것이군.",
			GENERIC = "아래에 무엇이 있는 것이지?",
		},
		NIGHTLIGHT = "아름다운 빛을 내며 타는군.",
		NIGHTMAREFUEL = "아. 시원하군.",
		NIGHTSWORD = "역시 재밌군!",
		NITRE = "삼 분의 일 되었군...",
		ONEMANBAND = "뛰어난 박자에 따라 춤출 수 있지.",
		PANDORASCHEST = "함정이지.",
		PANFLUTE = "내가 광기의 노래를 부르겠군.",
		PAPYRUS = "빈 캔버스군.",
		PENGUIN = "괜찮은 턱시도군.",
		PERD = "발효한 베리에 중독되었지.",
		PEROGIES = "훌륭하지, 내가 만들었으니까.",
		PETALS = "아름다운 것을 파괴하는 것이 나의 버릇이지 않은가?",
		PETALS_EVIL = "악몽의 정수가 뚝뚝 떨어질 정도군.",
		PICKAXE = "누구나 캐는 것을 좋아하지.",
		PIGGYBACK = "흠, 품위를 떨어뜨리는군.",
		PIGKING = "중요한 것이 뭔지 아는군!",
		PIGMAN =
		{
			DEAD = "너를 \"베이컨\"이라고 칭하지.",
			FOLLOWER = "단순하지만 내 소유물이지.",
			GENERIC = "침 흘리는 바보군.",
			GUARD = "조직적으로 되고 있군.",
			WEREPIG = "저것은 야생화했군.",
		},
		PIGSKIN = "그놈 아니면 나였겠지.",
		PIGTENT = "끔찍하군.",
		PIGTORCH = "훌륭하군. 이제 불을 가지게 됐군.",
		PINECONE = 
		{
		    GENERIC = "야외가 좋은 자라면 이것으로 뭘 할 수 있겠군.",
		    PLANTED = "흠, 땅에 두어야 하는 것이군.",
		},
		PITCHFORK = "완벽주의자가 선택할 도구이군.",
		PLANTMEAT = "미약한 정신을 속이기 위한 얕은 속임수지.",
		PLANTMEAT_COOKED = "열이 적당한 식사로 만들어주었군.",
		PLANT_NORMAL =
		{
			GENERIC = "일반 식물이지.",
			GROWING = "성장 중이지.",
			READY = "준비되었군.",
			WITHERED = "열에 견딜 정도로 튼튼하지 않았군.",
		},
		POMEGRANATE = "평소라면 다른 사람에게 씨를 빼라고 할 테지.",
		POMEGRANATE_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		POMEGRANATE_SEEDS = "나에게는 천한 노동이군.",
		POND = "표면에 반사된 내 얼굴을 볼 수 있군.",
		POOP = "모든 생명체가 내놓는 것이지.",
		PUMPKIN = "나는 언제나 할로윈을 좋아했지.",
		PUMPKINCOOKIE = "좋은 비스킷 먹어본지 참 오래 되었군.",
		PUMPKIN_COOKED = "조금 더 세련되었군, 적어도 말이지.",
		PUMPKIN_LANTERN = "안녕하군, 크레인 씨.",
		PUMPKIN_SEEDS = "나에게는 천한 노동이군.",
		PURPLEAMULET = "그림자와 대화를 나누는군.",
		PURPLEGEM = "자주색이 큰 힘을 불러오지.",
		RABBIT =
		{
			GENERIC = "내가 여기에 너무 오래 있었던 모양이군... 실제로 맛있군 이것이.",
			HELD = "안심해, 토끼. 다 잘 될 테니까.",
		},
		RABBITHOLE = 
		{
			GENERIC = "아래에 또 다른 세상이 있군.",
			SPRING = "입구가 내려 앉았군.",
		},
		RATATOUILLE = "조악한 음식물이군.",
		RAZOR = "세계의 목이 하나만 있다면 좋겠지만.",
		REDGEM = "적색이 불을 불러오지.",
		RED_CAP = "이것이 무엇이었는지 잊었군.",
		RED_CAP_COOKED = "좀 쓰군.",
		RED_MUSHROOM =
		{
			GENERIC = "빨간 버섯이잖아.",
			INGROUND = "나중에 돌아와야겠군.",
			PICKED = "다 소비했군.",
		},
		REEDS =
		{
			BURNING = "아차.",
			GENERIC = "바람 부는 버드나무가 생각나는군.",
			PICKED = "더 이상 통이 없군.",
		},
        RELIC = 
        {
            GENERIC = "멸망한 문명의 잔재물이지.",
            BROKEN = "돌 조각일 뿐이다.",
        },
        RUINS_RUBBLE = "망가진 유물이군.",
        RUBBLE = "돌 조각일 뿐이다.",
		RESURRECTIONSTONE = "이야기가 담겨 있는 것이지...",
		ROBIN =
		{
			GENERIC = "피리새는 불의 땅에서 왔지.",
			HELD = "침묵을 지켜라, 새!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "내가 모르는 것이군.",
			HELD = "조용히 해.",
		},
		ROBOT_PUPPET = "나보단 남이 당하는 것이 나은걸.",
		ROCK_LIGHT =
		{
			GENERIC = "용암의 겉이 차가워졌군.",
			OUT = "무해해 보여.",
			LOW = "불이 차가워지고 있군.",
			NORMAL = "뜨겁지.",
		},
		ROCK = "바위다.",
		ROCKS = "흠. 이제 그것으로 무엇을 하나?",
        ROOK = "내 집을 위한 성이군.",
		ROPE = "쓸 데가 더 많이 있을 것이라고 생각했었지.",
		ROTTENEGG = "메스껍군. 내가 왜 이것을 휴대하고 있지?",
		SANITYROCK =
		{
			ACTIVE = "이제 진짜 모습을 볼 수 있군!",
			INACTIVE = "저 장애물을 볼 수 있는 방법은 두 가지가 있지.",
		},
		SAPLING =
		{
			BURNING = "아차.",
			WITHERED = "이 열에서 생존하는 것은 없지.",
			GENERIC = "유연한 나무 줄기군.",
			PICKED = "다시 자라겠지.",
		},
		SEEDS = "스스로 심어지지는 않겠군.",
		SEEDS_COOKED = "구워서 생기를 다 없앴군.",
		SEWING_KIT = "훌륭하고 고급스러운 일이지.",
		SHOVEL = "최첨단 테크놀로지군.",
		SILK = "출처는 고급이 아니지만, 결과물인 옷은 고급이겠군.",
		SKELETON = "훗! 기억나는군.",
		SKELETON_PLAYER = "지배자가 학생이 되었군.",
		SKULLCHEST = "멋진 궤짝이군.",
		SMALLBIRD =
		{
			GENERIC = "뭐지!? 무엇을 원하지?",
			HUNGRY = "음식을 원하나?",
			STARVING = "아주 배고픈 모양이군!",
		},
		SMALLMEAT = "겨우 한 입 되는군.",
		SMALLMEAT_DRIED = "이것을 먹기에는 내 치아가 너무 약해진 것 같군.",
		SPEAR = "창이지. 그래.",
		SPIDER =
		{
			DEAD = "철퍽.",
			GENERIC = "대부분이 소화기관이지.",
			SLEEPING = "조용! 배고픈 상태에서 깨겠지.",
		},
		SPIDERDEN = "여기에서 크게 자라는군.",
		SPIDEREGGSACK = "물컹하군.",
		SPIDERGLAND = "불쾌하군.",
		SPIDERHAT = "거미는 융통성 있는 재료군.",
		SPIDERQUEEN = "내가 길을 비켜야겠군.",
		SPIDER_WARRIOR =
		{
			DEAD = "철퍽.",
			GENERIC = "특수 형태이군.",
			SLEEPING = "저것은 깨우고 싶지 않군.",
		},
		SPOILED_FOOD = "내가 허비하기 전까지는 음식이었지.",
		STATUEHARP = "내 최고의 작품은 아니지.",
		STATUEMAXWELL = "저것이야말로 훌륭한 조각상이군.",
		STINGER = "독액이 뚝뚝 떨어지는군.",
		STEELWOOL = "누군가가 이 곳을 정말 정리해야겠군.",
		STRAWHAT = "농부에게 어울리는 모자군.",
		STUFFEDEGGPLANT = "왕의 식사... 또는 왕좌에 앉은 자를 위한 식사.",
		SUNKBOAT = "배는 그렇게 사용하는 것이 아니지!",
		SWEATERVEST = "쓰리 피스는 아니지만 어느 정도는 말쑥하군.",
		TAFFY = "거의 설탕으로 이루어졌군.",
		TALLBIRD = "실패한 실험이었지.",
		TALLBIRDEGG = "이것 때문에 큰새가 영역 싸움을 하지.",
		TALLBIRDEGG_COOKED = "부서진 꿈 같은 맛이군.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "미지근해지고 있군.",
			GENERIC = "살아있군.",
			HOT = "충분히 뜨겁나?",
			LONG = "시간이 꽤 걸리겠군.",
			SHORT = "이제 조금 있으면...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "흐음. 날 유혹하는군.",
			PICKED = "더러운 고기물소 털로 만들었지.",
		},
		TEENBIRD =
		{
			GENERIC = "성장하니 이제 덜 귀엽군.",
			HUNGRY = "정말 많이 먹는군.",
			STARVING = "배고픈 짐승은 위험한 짐승이지.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "살아 있군!",
			GENERIC = "나의 아름다운 기계가 조각났군!",
			LOCKED = "이제 켜야지.",
			PARTIAL = "아직 미완성이군.",
		},
		TELEPORTATO_BOX = "슬픔과 비애가 가득한 상자이지.",
		TELEPORTATO_CRANK = "유머 감각을 살리게 위해 사용하지.",
		TELEPORTATO_POTATO = "이 안에 든 기어는 너무 작아서 현실조차 뒤틀어 버리지.",
		TELEPORTATO_RING = "이것은 양자장 방어 밴드이군.",
		TELESTAFF = "적절한 채널을 이용할 수 있다면 마법은 큰 효과를 발휘할 수 있지.",
		TENTACLE = "나머지가 여전히 여기에 있어서 다행이군.",
		TENTACLESPIKE = "윽. 무척 혐오스럽군.",
		TENTACLESPOTS = "이렇게 번식하는군.",
		TENTACLE_PILLAR = "얼마나 깊이 들어가지?",
		TENTACLE_GARDEN = "이상한 것이군.",
        TENTACLE_PILLAR_ARM = "새끼?",
		TOPHAT = "고급 의류군.",
		TORCH = "찰리가 접근하지 못하게 하지.",
		TRAP = "가장 멍청한 동물만 이것에 속겠군.",
		TRAP_TEETH = "강력하겠군.",
		TRAP_TEETH_MAXWELL = "내가 여기에 두었을 때 이유가 있었는데.",
		TREASURECHEST_TRAP = "흠. 수상해 보이는군.",
		TREECLUMP = "통과할 수 없군.",
		TRINKET_1 = "초고온으로 가열한 모양이군.",
		TRINKET_10 = "추잡하군, 이빨이라니.",
		TRINKET_11 = "듣지 않는다.",
		TRINKET_12 = "장갑을 여러 겹 끼지 않으면 건드리지 않겠어.",
		TRINKET_2 = "누군가에게 중요한 것이었었지.",
		TRINKET_3 = "삶처럼 엉망진창이군.",
		TRINKET_4 = "날 그렇게 보지 마시지!",
		TRINKET_5 = "아이의 장난감이군.",
		TRINKET_6 = "쓸모 없는 철사.",
		TRINKET_7 = "어른이 놀아야 하는 것이 아니군.",
		TRINKET_8 = "사슬 달린 주머니시계를 선호하지.",
		TRINKET_9 = "이 끔찍한 것으로 내 옷을 망칠 수는 없지.",
		TRUNKVEST_SUMMER = "가을 조끼로 더 적합하지.",
		TRUNKVEST_WINTER = "겨울에는 패션을 챙기기 무척 어렵지.",
		TRUNK_COOKED = "적어도 점액은 타서 없어졌군.",
		TRUNK_SUMMER = "여름의 점액이 가득하군.",
		TRUNK_WINTER = "점액을 더 보관하기 위해 겨울에는 줄기가 두꺼워지지.",

		TURF_CARPETFLOOR = "고품질의 하이 파일 카펫 샘플이군!",
		TURF_CHECKERFLOOR = "내가 원래 있어야 할 공간이지.",
		TURF_DIRT = "먼지투성이군.",
		TURF_FOREST = "진흙 냄새가 나는군.",
		TURF_GRASS = "긁히는군.",
		TURF_MARSH = "뚝뚝 떨어지는군.",
		TURF_ROAD = "적어도 이것은 유용하군.",
		TURF_ROCKY = "좀 거칠군.",
		TURF_SAVANNA = "더럽군.",
		TURF_WOODFLOOR = "나는 경재를 선호하지.",

		TURF_CAVE="표층이지.",
		TURF_FUNGUS="표층이지.",
		TURF_SINKHOLE="표층이지.",
		TURF_UNDERROCK="표층이지.",
		TURF_MUD="표층이지.",

		TURKEYDINNER = "명랑하군.",
		TWIGS = "평범하지만 유용하지.",
		UMBRELLA = "구부러졌군!",
		WAFFLES = "탁월한 아침 식사. 또는 저녁 식사군.",
		WALL_HAY_ITEM = "포켓 크기의 벽 조각이군. 그래.",
		WALL_STONE = "하층민이 들어오지 못하게 하겠군.",
		WALL_STONE_ITEM = "포켓 크기의 벽 조각이군. 그래.",
		WALL_WOOD_ITEM = "포켓 크기의 벽 조각이군. 그래.",
		WALL_RUINS = "고대의 벽이지.",
		WALL_RUINS_ITEM = "포켓 크기의 벽 조각이군. 그래.",
		WALRUS = "나를 못 알아보겠나?",
		WALRUSHAT = "스코틀랜드에서 제조했군.",
		WALRUS_CAMP =
		{
			EMPTY = "겨울에 올 때 남아있지 말아야겠군.",
			GENERIC = "바다 코끼리가 멀리 있지 않겠군.",
		},
		WALRUS_TUSK = "내가 이를 더 잘 활용하겠군.",
		WASPHIVE = "위험해 보인다.",
		WETGOOP = "야만적이군.",
		WINTERHAT = "실망스러울 정도로 예스럽군.",
		WORMHOLE =
		{
			GENERIC = "다른 부분이 어떻게 생겼는지 아는 것이 더 나쁘지.",
			OPEN = "보기보다 냄새가 분명히 더 나쁘지.",
		},
		WORMHOLE_LIMITED = "아파 보이는군.",
		ACCOMPLISHMENT_SHRINE = "그들조차도 이렇게 사악한 것을 만들 수 없었겠지.",

		AERODYNAMICHAT = "우아하진 않아도 매끈하군.",
		ANTIVENOM = "독을 치료해주지.",
		ARMORCACTUS = "남을 \"멀리 하기\"에 최적이군.",
		ARMORLIMESTONE = "나를... 느리게 만드는군.",
		ARMOROBSIDIAN = "화염을 내 의지대로 쓰고 있지.",
		ARMORSEASHELL = "가장 튼튼하지는 않지만, 나의 취약성을 숨겨줄 수 있겠군.",
		ARMOR_LIFEJACKET = "아쉽게도 교양은 접어두고 실용성을 중시해야겠군.",
		ARMOR_SNAKESKIN = "꽤 말쑥하군!",
		ARMOR_WINDBREAKER = "한숨.",
		ARMOUREDBOAT = "이 배는 챔피언처럼 공격을 견뎌낼 수 있겠지.",
		BABYOX = "나에게서 특별한 대우를 받지는 못하지, 짐승.",
		BALLPHIN = "겉보이는 것보다 훨씬 간교하지.",
		BAMBOO = "이것을 위한 아이디어가 몇 가지 있지.",
		BAMBOOTREE =
		{
			BURNT = "돌아오지 않겠군.",
			CHOPPED = "보충할 시간이 돌아왔군.",
			GENERIC = "어떠한 것으로든 자랄 수 있겠지.",
		},
		BERMUDATRIANGLE = "나보고 들어오라는 것인가.",
		BIGFISHINGROD = "이제 헤엄치는 고기를 더 잘 잡을 수 있겠군.",
		BIOLUMINESCENCE = "초자연적이지?",
		BLOWDART_FLUP = "멋지게 기절시킬 수 있겠군.",
		BLOWDART_POISON = "이 세상의 독으로 세상을 공격하는 것이지.",
		BLUBBER = "식용... 인 것 같군...",
		BLUBBERSUIT = "품위 없군.",
		BOATCANNON = "이것을 쓸 때가 되었군.",
		BOATREPAIRKIT = "허물어지는 배를 잠시 고쳐주는 것이지.",
		BOAT_LANTERN = "주위에 오싹한 기운이 퍼트리지.",
		BOAT_TORCH = "밤에 항해하는 것은 안전하지 않지만, 이러면 더 낫겠지.",
		BOTTLELANTERN = "노예 상태가 되어 삶의 목적을 찾았군.",
		BRAINJELLYHAT = "영감이 떠오른다.",
		BUOY = "쉽게 뜨는군.",
		BURIEDTREASURE = "아, 이것이 뭐지?",
		BUSH_VINE =
		{
			BURNT = "종말을 맞이했군.",
			CHOPPED = "지금은 다 썼군.",
			GENERIC = "이것들이 섬 전체에 퍼졌군.",
		},
		CAPTAINHAT = "명령권이 생긴 것 같군.",
		CARGOBOAT = "아, 숨쉴 공간이 많군.",
		CHIMINEA = "어렵게 구한 불을 안전하게 보관하지.",
		CLOTHSAIL = "여행에 도움이 되겠군.",
		COCONADE =
		{
			BURNING = "엄폐 뒤에서 숨어야겠군.",
			GENERIC = "미래에 죽음이 보이는군.",
		},
		COCONUT = 
		{
		    GENERIC = "머리를 상당히 다치게 할 수 있지.",
		    PLANTED = "더 이상 아무도 해칠 수 없지.",
		},
		COCONUT_COOKED = "지금은 꽤 쓸 수 있겠군.",
		COCONUT_HALVED = "코코넛 하나를 두 개로 만들었군... 마법이지!",
		COFFEE = "이것을 기대하겠지.",
		COFFEEBEANS = "이 색으로 보니 이상하군.",
		COFFEEBEANS_COOKED = "날 것보다는 낫지만, 다르게 준비하는 방법이 있나?",
		COFFEEBOT = "내 커피 잔시부름을 하겠지.",
		COFFEEBUSH =
		{
			BARREN = "메말랐군.",
			GENERIC = "기쁨을 주는 커피콩이지.",
			PICKED = "다 땄지.",
			WITHERED = "부패의 승리군.",
		},
		COMPASS =
		{
			GENERIC="흠. 판독할 수 없군.",
			N = "북.",
			S = "남.",
			E = "동.",
			W = "서.",
			NE = "북동.",
			SE = "남동.",
			NW = "북서.",
			SW = "남서.",
		},
		CORAL = "꽤 사랑스럽군.",
		CORALREEF = "광범위한 생물체들을 보조할 수 있겠군.",
		CORAL_BRAIN = "이제 그 생각의 힘을 내가 쓸 수 있겠군.",
		CORAL_BRAIN_ROCK = "무엇을 생각하는 것일지?",
		CRAB =
		{
			GENERIC = "먹을 수 있는 갑각류군.",
			HIDDEN = "게토끼가 숨어있군.",
		},
		CRABHOLE = "영원히 숨을 수는 없지.",
		CRATE = "비틀어 열 수 있을지도 모르겠군.",
		CUTLASS = "신사의 무기지.",
		DEAD_SWORDFISH = "펜싱 레슨을 더 받는 것이 좋았겠군.",
		DEPLETED_BAMBOOTREE = "사라졌군.",
		DEPLETED_BUSH_VINE = "더 이상 없어.",
		DEPLETED_GRASS_WATER = "그뿐이었군.",
		DEVTOOL = "정말 이상하군.",
		DEVTOOL_NODEV = "내가 이해할 수 있는 것이 아니군.",
		DOUBLE_UMBRELLAHAT = "한심해보이는군.",
		DOYDOY = "이 슬픈 짐승은 생존의 희망이 없군.",
		DOYDOYBABY = "더 많이 생길 것이지.",
		DOYDOYEGG = "흠, 멸종해가는 종을 키울까 아니면 가벼운 식사를 즐길까?",
		DOYDOYEGG_COOKED = "가벼운 스낵이 가장 뛰어난 선택이지.",
		DOYDOYEGG_CRACKED = "흣.",
		DOYDOYFEATHER = "선데이 해트에 꽂으면 멋있겠군.",
		DOYDOYNEST = "과연 살아남을 수 있을지?",
		DRAGOON = "내가 누군지 모르는지?",
		DRAGOONDEN = "그들을 방해할 이유가 없군.",
		DRAGOONEGG = "고압적인 열이 방사되는군.",
		DRAGOONHEART = "어차피 심장은 고통만 가져주지.",
		DRAGOONSPIT = "꽤 지저분하군.",
		DUBLOON = "서로 부딪힐 때의 소리가 극도로 만족스럽지.",
		DUG_BAMBOOTREE = "이것을 위한 공간을 찾아야겠군.",
		DUG_BUSH_VINE = "이를 위한 올바른 것을 찾아야겠군.",
		DUG_COFFEEBUSH = "다시 심을 가치가 있군.",
		DUG_ELEPHANTCACTUS = "이것을 가지고 달릴 순 없지.",
		EARRING = "귀를 뚫었다면 멋있게 걸 수 있겠지.",
		ELEPHANTCACTUS = "이래서는 아무 것도 쏘지 못 하지.",
		ELEPHANTCACTUS_ACTIVE = "엄폐물 뒤에 숨어라!",
		ELEPHANTCACTUS_STUMP = "잘 없어졌잖아.",
		FABRIC = "대나무를 유용한 것으로 만들었지.",
		FEATHERSAIL = "패딩보다 낫군.",
		FISHINHOLE = "내 배 안에 들어오면 더 만족스럽겠지.",
		FISH_RAW = "불에 살짝 구우면 좋겠군.",
		FISH_RAW_SMALL = "내가 이렇게 초라해진 것인지?",
		FISH_RAW_SMALL_COOKED = "...다 먹지.",
		FLAMEGEYSER = "멋진 광경을 만들어내는군.",
		FLOTSAM = "어쩌면 잡아당길 수 있을지도 모르겠군.",
		FLUP = "비천한 것이군.",
		FRESHFRUITCREPES = "은식기로 먹어야 어울리겠지만, 안타깝게도 손 밖에 없군.",
		FROG_POISON = "매너를 가르쳐야겠군.",
		GASHAT = "냄새를 없애주지.",
		GOLDENMACHETE = "언제나 럭셔리한 도구로 절단하고 싶었지.",
		GRASS_WATER = "부분적으로 잠겼군.",
		HAIL_ICE = "약간 춥군.",
		HOUNDFIRE = "물어뜯는 화염이군!",
		ICEMAKER =
		{
			HIGH = "얼음을 만들기 위해 열심히 작동하는군.",
			LOW = "보충해야겠군.",
			NORMAL = "작동하는 것 같군.",
			OUT = "작동하지 않는군.",
			VERYLOW = "거의 다 떨어졌군.",
		},
		IRONWIND = "좋아, 갈 곳이 있으니까!",
		JELLYFISH = "이상한 작은 생물체군.",
		JELLYFISH_COOKED = "이것으로 되겠지, 아마.",
		JELLYFISH_DEAD = "죽은 것이 더 마음에 드는군.",
		JELLYFISH_PLANTED = "꽤 충격적이군.",
		JELLYJERKY = "그리 나쁘지 않군?",
		JUNGLETREE =
		{
			BURNING = "곧 이 세계를 떠나겠군.",
			BURNT = "어쩌면 다른 시대라면 괜찮겠지.",
			CHOPPED = "내 목적을 위해 사용했지.",
			GENERIC = "자르길 원하는 것 같군.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "이론적으로 따지면 이것을 다시 심을 수 있겠지.",
            PLANTED = "그래. 내가 옳았지.",
        },
		KNIGHTBOAT = "나를 따르시지, 우둔한 것!",
		KRAKEN = "내 앞에서는 고개를 숙이시지.",
		KRAKENCHEST = "이제 내 보상을 차지해야겠군.",
		KRAKEN_TENTACLE = "감히 나를 만지다니?",
		LAVAPOOL = "월등하게 뜨겁군.",
		LIMESTONE = "어쩌면 이 바다 생물의 죽음이 유용하게 쓰이겠지.",
		LIMPETROCK =
		{
			GENERIC = "급박할 때 식량이 될 수 있겠군.",
			PICKED = "이제는 돌일 뿐이지.",
		},
		LIMPETS = "점액성이고, 어쨌든 소화는 되겠군.",
		LIMPETS_COOKED = "별미? 정말로?",
		LIVINGJUNGLETREE = "평범한 곳이다.",
		TREEGUARD = "넌센스를 멈추시지.",
		LOBSTER = "이제서야 제대로 된 식사군.",
		LOBSTERHOLE = "맛있는 동물, 나타나시지.",
		LOBSTER_DEAD = "훌륭하군.",
		LOBSTER_DEAD_COOKED = "턱받이를 안 가져왔군.",
		LOGRAFT = "이것을 금지하는 규정이 있어야 할 것 같군.",
		LUGGAGECHEST = "꽤나 멋있는 가방이군.",
		MACHETE = "그래, 난 언제나 열심히 살았었지.",
		MAGIC_SEAL = "담겨 있는 강력한 힘이 느껴지는군.",
		MAGMAROCK = "어쨌든 돌이군.",
		MAGMAROCK_FULL = "어쨌든 돌이군.",
		MAGMAROCK_GOLD = "더욱 고급인 돌이군.",
		MAGMAROCK_GOLD_FULL = "더욱 고급인 돌이군.",
		MANGROVETREE = "나무지만... 젖었군.",
		MANGROVETREE_BURNT = "파괴되었군.",
		MARSH_PLANT_TROPICAL = "나에게 도움이 안 되는군.",
		MERMFISHER = "그와 싸울 이유가 없지.",
		MERMHOUSE_FISHER = "모두 살 곳이 필요하겠지...",
		MESSAGEBOTTLE = "이 미개한 통신 수단은 뭐지?",
		MESSAGEBOTTLEEMPTY = "시간이 충분히 있으면 안에서 배를 만들 수 있겠군.",
		MONKEYBALL = "이것으로 무엇을 할 수 있는 거지요?",
		MONSTERTARTARE = "식욕을 전혀 돋우지 않는군.",
		MOSQUITOSACK_YELLOW = "그 피를 되찾아야겠지.",
		MOSQUITO_POISON = "이것에 물리고 싶지 않군.",
		MUSSEL = "어느 지역에서는... 별미겠지.",
		MUSSELBOUILLABAISE = "정찬이 기대되는군.",
		MUSSEL_COOKED = "이제 더 이상 건강에 위험하지 않군.",
		MUSSEL_FARM =
		{
			GENERIC = "음식물이 편리하게 모였군.",
			STICKPLANTED = "다가오는 죽음을 깨닫지 못하는군.",
		},
		MUSSEL_STICK = "홍합이 견디지 못하겠군.",
		MYSTERYMEAT = "꽤 혐오스럽군.",
		NEEDLESPEAR = "아주 날카롭군.",
		OBSIDIAN = "즐거운 색이군.",
		OBSIDIANAXE = "불붙었을 때 가장 효과적인 것 같군.",
		OBSIDIANCOCONADE = "분명히 확인사살용이군.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "신경 써야겠군.",
			GENERIC = "이 돌의 탄생의 목적이지.",
			HIGH = "타오르는 불이군.",
			LOW = "약해지고 있군.",
			NORMAL = "뜨거운 스타일이군.",
			OUT = "차가워졌군.",
		},
		OBSIDIANMACHETE = "농사일에 쓰기에는 위험해 보이는군.",
		OBSIDIANSPEARGUN = "발사하는 화염. 마음에 드는군.",
		OBSIDIAN_WORKBENCH = "이 작업대는 내 마음의 창의성을 불피워주는군...",
		OCTOPUSCHEST = "썩은 것으로... 보이는군.",
		OCTOPUSKING = "그의 관용을 내 장점으로 사용할 수 있겠지.",
		OX = "냄새가 나고 매우 멍청하지.",
		OXHAT = "어쩔 때는 기능을 위해 형상을 포기해야지.",
		OX_FLUTE = "좋아. 이것을 연주한지 꽤 됐지.",
		OX_HORN = "짐승한테는 승산이 없었지.",
		PACKIM = "성가시게 생겼지만 유용성과 복종성으로 균형을 이루는군.",
		PACKIM_FISHBONE = "가지고 있어야 할 것 같군.",
		PALMLEAF = "나를 부채질해줄 하인만 있으면 되겠군!",
		PALMLEAF_HUT = "휴.",
		PALMTREE =
		{
			BURNING = "곧 이 세계를 떠나겠군.",
			BURNT = "어쩌면 다른 시대라면 괜찮겠지.",
			CHOPPED = "내 목적을 위해 사용했지.",
			GENERIC = "정말 호화롭군.",
		},
		PARROT = "흠. 다채롭군.",
		PARROT_PIRATE = "어쩌면 그를 조용하게 만들 수 있겠지.",
		PEACOCK = "이 생물은 쇼맨십이 뭔지 아는군.",
		PEG_LEG = "구타하는 데 좋지.",
		PIKE_SKULL = "칙칙하군.",
		PIRATEGHOST = "너와 같은 운명이 되지는 않아야겠지!",
		PIRATEHAT = "이것이 즐거운가?",
		PIRATEPACK = "이거면 되겠군.",
		PIRATIHATITATOR =
		{
			BURNT = "재는 재가 되는군요.",
			GENERIC = "정말 신기한 장치군.",
		},
		POISONHOLE = "여기에서 잘 보이는군... 더 가까이 갈 필요가 없지.",
		PORTAL_SHIPWRECKED = "쓸모없군!",
		PRIMEAPE = "이 비루한 동물의 지능은 참 뒤떨어지지.",
		PRIMEAPEBARREL = "멀리 떨어져 있게 하시지.",
		RAFT = "내가 원하는 것보다 훨씬 위험해보이는군.",
		RAWLING = "그렇군. 속을 채운 말하는 주머니군.",
		REDBARREL = "잠재력이 가득하군.",
		ROCK_CHARCOAL = "자연의 형성에 감탄할 수 밖에 없군.",
		ROCK_OBSIDIAN = "나는 도구에 굽히지 않을 테지.",
		ROWBOAT = "수동이군. 아쉽게도.",
		SAIL = "이것을 달면 잘 항해할 수 있겠군.",
		SAIL_STICK = "돛을 위한 막대군.",
		SAND = "바위들을 잘게 분쇄해서 더 이상 형체를 알아볼 수 없군.",
		SANDBAG = "물이 들어오지 않게 하는 흙 주머니군.",
		SANDBAGSMALL = "물이 들어오지 않게 하는 흙 주머니군.",
		SANDBAGSMALL_ITEM = "휴대할 수 있는 흙 주머니군.",
		SANDBAG_ITEM = "휴대할 수 있는 흙 주머니군.",
		SANDHILL = "작은 노란색 모래 무더기군.",
		SAND_CASTLE =
		{
			GENERIC = "전혀 즐겁지 않았군. 맹세하지.",
			SAND = "장식 모래군.",
		},
		SEAGULL = "시끄럽고 거슬리는군.",
		SEAGULL_WATER = "미개하군.",
		SEASACK = "나를 강하게 만들지는 않지만, 주머니를 더 주는군.",
		SEASHELL = "잡고 있으니 관광객이 된 것 같군.",
		SEASHELL_BEACHED = "내 취향이라기엔 너무 키치적이군.",
		SEATRAP = "결국 호기심 때문에 망하겠지.",
		SEAWEED = "바다 쓰레기군.",
		SEAWEED_COOKED = "이것을 먹기가 싫군.",
		SEAWEED_DRIED = "윽.",
		SEAWEED_PLANTED = "여기에서 잘 자라는군.",
		SHADOWSKITTISH_WATER = "저런.",
		SHARKITTEN = "매력적인 괴물이군.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "먹는 것을 언급하면 뒤트는군.",
			INACTIVE = "평범한 모래 더미군.",
		},
		SHARK_FIN = "훌륭한 사냥 트로피군.",
		SHARK_GILLS = "가지고 있으면 쓰겠지.",
		SHARK_TEETHHAT = "이 패션 감각을 존중하지.",
		SHARX = "정복\"할 수 있느냐\"가 문제가 아니라, 언제 정복하느냐가 문제지.",
		SHIPWRECKED_ENTRANCE = "준비되었길 바라는군.",
		SHIPWRECKED_EXIT = "잘 가시오.",
		SLOTMACHINE = "운명의 장난을 즐기는 것이 나의 취미지.",
		SLURPERPELT = "고급 날가죽이지.",
		SNAKE = "잔인하지만 우아한 짐승이지.",
		SNAKEDEN =
		{
			BURNT = "종말을 맞이했군.",
			CHOPPED = "지금은 다 썼군.",
			GENERIC = "이것들이 섬 전체에 퍼졌군.",
		},
		SNAKEOIL = "이것으로 이익을 챙길 수 있을지도 모르겠군.",
		SNAKESKIN = "맛있는 질감이군.",
		SNAKESKINHAT = "실제로 꽤 멋있군.",
		SNAKESKINSAIL = "쉽게 항해할 수 있지.",
		SNAKE_FIRE = "뱀이 가열됐군.",
		SNAKE_POISON = "이것은 잘 피해 가야겠군.",
		SOLOFISH = "젖은 개 같은 냄새군.",
		SPEARGUN = "발사 도구가 유용하게 쓰이겠군.",
		SPEARGUN_POISON = "내가 더 강력하게 만들었지.",
		SPEAR_LAUNCHER = "발사 도구가 유용하게 쓰이겠군.",
		SPEAR_OBSIDIAN = "불의 힘을 강력하게 만들었지.",
		SPEAR_POISON = "내가 더 강력하게 만들었지.",
		SPOILED_FISH = "버려야겠군.",
		STUNGRAY = "흉악한 냄새가 나는군.",
		SUNKEN_BOAT =
		{
			ABANDONED = "수비가 삼엄하지.",
			GENERIC = "더 이상 항해하지 못 하겠지.",
		},
		SUNKEN_BOAT_BURNT = "시간의 흐름은 모든 것을 파멸시키지.",
		SUNKEN_BOAT_TRINKET_1 = "보이는 그대로지. 음... 그런데 그것이 무엇일지?",
		SUNKEN_BOAT_TRINKET_2 = "나의 상황을 놀리는 것 같군.",
		SUNKEN_BOAT_TRINKET_3 = "특별한 기능이 없지.",
		SUNKEN_BOAT_TRINKET_4 = "작은 첨단 장치이지.",
		SUNKEN_BOAT_TRINKET_5 = "더러운 물에 들어가기 전에도 끔찍했겠지.",
		SUPERTELESCOPE = "이것으로 땅의 형세를 알아볼 수 있겠군.",
		SWEETPOTATOSOUFFLE = "꽤 맛있어 보이는군!",
		SWEET_POTATO = "요리할 준비가 되었군.",
		SWEET_POTATO_COOKED = "가게에서 산 것은 같은 맛이 안 나지.",
		SWEET_POTATO_PLANTED = "이것보다 더 나쁜 것들을 먹었지. 훨씬 더 나쁜 것들을.",
		SWEET_POTATO_SEEDS = "이것을 땅에 쳐박으면 무언가 나올지도 모르겠군.",
		SWIMMINGHORROR = "지긋지긋하군, 마귀.",
		SWORDFISH = "아, 스파링 파트너군!",
		TELEPORTATO_SW_BASE = "무언가 멋진 것이 만들어지겠군.",
		TELEPORTATO_SW_BOX = "또 하나의 퍼즐 조각이군.",
		TELEPORTATO_SW_CRANK = "좋군. 이제 얼마 안 남았군.",
		TELEPORTATO_SW_POTATO = "좀 우습긴 하지.",
		TELEPORTATO_SW_RING = "아, 다른 조각이군.",
		TELESCOPE = "이것으로 땅의 형세를 알아볼 수 있겠군.",
		THATCHPACK = "대단하진 않지만 공간이 더 있으니 좋군.",
		TIDALPOOL = "보기보다 훨씬 깊지.",
		TIDAL_PLANT = "약간 작군.",
		TIGEREYE = "신사가 장갑을 안 끼고 다룰 수 있는 것은 아니지.",
		TIGERSHARK = "적절한 이름이군.",
		TOUCAN = "알록달록한 해충이군.",
		TRAWLNET = "전혀 나쁜 점이 없군.",
		TRAWLNETDROPPED =
		{
			GENERIC = "내가 만들 식사를 상상해보지.",
			SOON = "깊이 들어가는군...",
			SOONISH = "내려오고 있군.",
		},
		TRIDENT = "대양의 왕족에게 어울리는 포크군.",
		TRINKET_13 = "바닷물과 달라서 좋군.",
		TRINKET_14 = "나쁜 부두 마술 같군.",
		TRINKET_15 = "스트링이 네 개뿐이군.",
		TRINKET_16 = "문자와 숫자... 비밀코드인가?",
		TRINKET_17 = "더러운 물에 들어가기 전에도 끔찍했겠지.",
		TRINKET_18 = "순간접착제가 약간 있으면 근사한 장식품이 되겠군.",
		TRINKET_19 = "빨갛지도 파랗지도 않군.",
		TRINKET_20 = "보이는 그대로지. 음... 그런데 그것이 무엇일지?",
		TRINKET_21 = "뜨거운 욕조에서 좋겠지...",
		TRINKET_22 = "시골 벼룩시장에서 볼 수 있는 것이군.",
		TRINKET_23 = "무엇과도 통신을 하고 있지 않지.",
		TROPICAL_FISH = "꼬챙이를 꽂으면 좋겠군.",
		TUNACAN = "안에 물고기가 든 모양이군.",
		TURBINE_BLADES = "전문성 있게 설계한 것 같군.",
		TURF_ASH = "표층으로 보이는군.",
		TURF_BEACH = "표층으로 보이는군.",
		TURF_DESERTDIRT = "표층으로 보이는군.",
		TURF_FUNGUS_GREEN = "표층으로 보이는군.",
		TURF_FUNGUS_RED = "표층으로 보이는군.",
		TURF_JUNGLE = "표층으로 보이는군.",
		TURF_MAGMAFIELD = "표층으로 보이는군.",
		TURF_MEADOW = "표층으로 보이는군.",
		TURF_SNAKESKINFLOOR = "표층으로 보이는군.",
		TURF_SWAMP = "표층으로 보이는군.",
		TURF_TIDALMARSH = "표층으로 보이는군.",
		TURF_VOLCANO = "표층으로 보이는군.",
		TWISTER = "안으로 빨려 들어가기 싫군.",
		TWISTER_SEAL = "음... 귀여운 것인가?",
		VENOMGLAND = "이것이 치료제?",
		VINE = "비틀어지고 옹이졌군.",
		VOLCANO = "그 힘을 존중하지.",
		VOLCANOSTAFF = "잡히는 느낌이 익숙하군.",
		VOLCANO_ALTAR =
		{
			GENERIC = "제물을 받치는 곳이군.",
			OPEN = "내가 통제할 수 없는 것의 힘을 써도 될지?",
		},
		VOLCANO_ALTAR_BROKEN = "진정으로 불쌍하군.",
		VOLCANO_ALTAR_TOWER = "매력적인 구조물이군.",
		VOLCANO_EXIT = "떠나야겠군.",
		VOLCANO_SHRUB = "내가 연민이 있다면 이 나무에게 주겠지.",
		WALLYINTRO_DEBRIS = "이것이 무슨 허튼 짓이지?",
		WALL_LIMESTONE = "튼튼하게 서있겠군.",
		WALL_LIMESTONE_ITEM = "나의 성을 어디부터 만들어야 할까?",
		WATERMELON_SEEDS = "이것을 심을 수 있겠지.",
		WATERYGRAVE = "모든 자가 최후의 안식처를 찾지는 못하지.",
		WHALE_BLUE = "항복하시지.",
		WHALE_BUBBLES = "자신의 위치를 드러냈군, 형씨.",
		WHALE_CARCASS_BLUE = "크기는 정말로 중요하지 않지!",
		WHALE_CARCASS_WHITE = "내가 이겼군!",
		WHALE_TRACK = "대추격이지!",
		WHALE_WHITE = "다시 만났군.",
		WILBUR_CROWN = "안쪽이 더럽군.",
		WILBUR_UNLOCK = "이제 너를 되돌려 보낼 수는 없겠군.",
		WILDBORE = "쉽게 이 무식한 돼지를 제거할 수 있지.",
		WILDBOREHEAD = "사랑스러운 분위기군.",
		WILDBOREHOUSE = "여기에서는 이것을 건축물이라고 하는가?",
		WIND_CONCH = "밖은 아름답고, 안은 파괴적이군.",
		WOODLEGSBOAT = "신뢰성이 있어 보이는군.",
		WOODLEGSHAT = "해적의 모험...",
		WOODLEGSSAIL = "좋은 돛이군요.",
		WOODLEGS_CAGE = "어쨌든 우리는 모두 갇혀 있는지 존재지.",
		WOODLEGS_KEY1 = "약하군.",
		WOODLEGS_KEY2 = "고급 금 열쇠군.",
		WOODLEGS_KEY3 = "평범한 철이군.",
		WRECK = "승산이 없었구나.",
		CALIFORNIAROLL = "또 만났군, 게토끼.",
	},
	DESCRIBE_GENERIC = "말해 봐.",
	DESCRIBE_TOODARK = "어두워서 안 보이는군!",
	DESCRIBE_SMOLDERING = "곧 불붙겠군.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "현명하지 못했군.",
	},
}
