return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Lo esquilaré cuando duerma.",
			GENERIC = "No merece la pena afeitar.",
			NOBITS = "¡Pero no hay nada que recortar!",
		},
		STORE =
		{
			GENERIC = "Ya está lleno de bienes.",
			NOTALLOWED = "Me temo que eso no va ahí.",
		},
		RUMMAGE =
        {   
            GENERIC = "¡Si yo no puedo hacerlo, no se puede hacer!",   
        },
		COOK =
        {
            GENERIC = "¡Ay! ¡Derrotado por utensilios de cocina!",
            TOOFAR = "¡Debo cerrar la brecha entre nosotros!",
        },
        WRITE =
        {
            GENERIC = "¡No tengo miedo!",
        },
        GIVE =
        {
            DEAD = "Habrá cosas mejores en Valhalla.",
            SLEEPING = "Un sueño tan dulce...Igual más tarde.",
            BUSY = "Lo intentaré una vez más cuando acabe.",
        },
        CHANGEIN =
        {
            GENERIC = "Ahí es donde guardo mis pieles favoritas.",
            BURNING = "¡Glub! ¡Mis pieles!",
        },
        TEACH =
        {
            KNOWN = "Ya poseo ese conocimiento.",
            CANTLEARN = "Ese conocimiento está prohibido por los dioses.",
        },
		REPAIRBOAT =
		{
			GENERIC = "¡Mi nave está como nueva!",
		},
	},
	ACTIONFAIL_GENERIC = "¡Si yo no puedo hacerlo, no se puede hacer!",
	ANNOUNCE_MAGIC_FAIL = "¡Su magia se ha debilitado!",
	ANNOUNCE_ADVENTUREFAIL = "De vuelta al otro mundo. ¡La victoria será mía!",
	ANNOUNCE_BEES = "¡Atrás, pequeñas criaturas con lanza!",
	ANNOUNCE_BOOMERANG = "¡Agh! Tengo que dominar el arma curva.",
	ANNOUNCE_CHARLIE = "¡Muéstrate!",
	ANNOUNCE_CHARLIE_ATTACK = "¡Cobarde!",
	ANNOUNCE_COLD = "¡Brrr! ¿¡Dónde están mis pieles!?",
	ANNOUNCE_HOT = "El sol me cansa.",
	ANNOUNCE_CRAFTING_FAIL = "Me faltan las provisiones necesarias.",
	ANNOUNCE_DEERCLOPS = "¡Se acerca un enemigo digno!",
	ANNOUNCE_DUSK = "Se está poniendo el sol. La oscuridad espera cerca.",
	ANNOUNCE_EAT =
	{
		GENERIC = "¡La carne hace que mi corazón cante!",
		PAINFUL = "Ah, no me siento bien.",
		SPOILED = "Agh. Fresca estaría mejor.",
		STALE = "Era una bestia rancia.",
		INVALID = "¡No es comida apropiada para una guerrera!",
		YUCKY = "¡Esta comida no es apropiada para una guerrera!",
	},
	ANNOUNCE_ENTER_DARK = "Y cae el telón.",
	ANNOUNCE_ENTER_LIGHT = "¡Entro en la luz!",
	ANNOUNCE_FREEDOM = "¡Libertad! ¡La saga continúa!",
	ANNOUNCE_HIGHRESEARCH = "Soy una artesana excelente.",
	ANNOUNCE_HOUNDS = "Las bestias se acercan...",
	ANNOUNCE_HUNGRY = "¡Qué ganas tengo de un banquete!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Shhh... La criatura está cerca.",
	ANNOUNCE_HUNT_LOST_TRAIL = "He perdido la pista.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Está demasiado embarrado para caminar.",
	ANNOUNCE_INV_FULL = "¡Estoy llevando todo lo que puedo!",
	ANNOUNCE_KNOCKEDOUT = "Ay, mi cabeza.",
	ANNOUNCE_LOWRESEARCH = "No ha sido muy emocionante.",
	ANNOUNCE_MOSQUITOS = "¡Largo, demonios diminutos!",
	ANNOUNCE_NODANGERSLEEP = "No es seguro para dormir. ¡Usa la lanza!",
	ANNOUNCE_NODAYSLEEP = "¡El sol está alto, la marcha continúa!",
	ANNOUNCE_NODAYSLEEP_CAVE = "Todavía no descansaré.",
	ANNOUNCE_NOHUNGERSLEEP = "¡Tendré hambre durante la noche! El banquete primero.",
	ANNOUNCE_NOSLEEPONFIRE = "No dormiré en las llamas.",
	ANNOUNCE_NODANGERSIESTA = "¡La batalla va a comenzar, no habrá descanso!",
	ANNOUNCE_NONIGHTSIESTA = "No se puede dormir la siesta bajo la luna.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Creo que este no es el momento para una siesta.",
	ANNOUNCE_NOHUNGERSIESTA = "Preferiría comer primero un aperitivo de carne.",
	ANNOUNCE_NO_TRAP = "Afortunadamente, soy ligera de pies.",
	ANNOUNCE_PECKED = "¡Largo, bestia con pico!",
	ANNOUNCE_QUAKE = "¡El mundo se estremece!",
	ANNOUNCE_RESEARCH = "El poder del conocimiento es magnífico.",
	ANNOUNCE_SHELTER = "¡Ajá! ¡Un refugio!",
	ANNOUNCE_THORNS = "¡Agh, me he pinchado!",
	ANNOUNCE_TORCH_OUT = "¡Mi luz se apaga!",
	ANNOUNCE_TRAP_WENT_OFF = "Eso no era parte del plan.",
	ANNOUNCE_UNIMPLEMENTED = "No es de este mundo.",
	ANNOUNCE_WORMHOLE = "Ha sido una aventura descuidada.",
	ANNOUNCE_CANFIX = "\nPuedo reparar esto.",
	ANNOUNCE_FAN_OUT = "¡Se acabó el aire!",
	ANNOUNCE_ACCOMPLISHMENT = "¿Puedo volver a la batalla ahora?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "¡Victoria! Bien, vamos.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "¿Quieres más excrementos?",
	ANNOUNCE_TOOL_SLIP = "¡Diablo resbaladizo!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "He montado sobre un rayo.",

	ANNOUNCE_DAMP = "Mancha para la batalla.",
	ANNOUNCE_WET = "Soy una guerrera mojada.",
	ANNOUNCE_WETTER = "¿Esto cuenta como un baño?",
	ANNOUNCE_SOAKED = "¡Casi estoy ahogada!",
	
	ANNOUNCE_OTHER_WORLD_PLANT = "¡Esta planta nunca florecerá en este reino!",

	ANNOUNCE_BOAT_DAMAGED = "¡Mi navío está herido!",
	ANNOUNCE_BOAT_SINKING = "¡El mar me lleva al infierno!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "¡Estas negras profundidades me reclamarán pronto!",
	ANNOUNCE_BURNT = "¡Ayyyy!",
	ANNOUNCE_CRAB_ESCAPE = "¡Ha desaparecido!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "¡Las corrientes son mi amo!",
	ANNOUNCE_MAPWRAP_RETURN = "¡He emergido de entre la niebla!",
	ANNOUNCE_MAPWRAP_WARN = "¡He llegado a los confines del mundo!",
	ANNOUNCE_MORETREASURE = "¡Este día me sonríe!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Este mapa describe otra tierra.",
	ANNOUNCE_SHARX = "¡Enemigos salidos de la espuma!",
	ANNOUNCE_TRAWL_FULL = "Mi red se ha llenado de maravillosos botines.",
	ANNOUNCE_TREASURE = "¡El mapa habla de un tesoro!",
	ANNOUNCE_VOLCANO_ERUPT = "¿¡Me está atacando Ragnarok!?",
	ANNOUNCE_WAVE_BOOST = "¡Llévame hacia delante!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Hay una bestia bajo las olas...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "He perdido el rastro de la bestia...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "No puedo leer estas aguas agitadas...",

	BATTLECRY =
	{
		GENERIC = "¡Valhalla te espera!",
		PIG = "¡Voy a tener cerdo esta noche!",
		PREY = "¡Muere con valor, enemigo endeble!",
		SPIDER = "¡Araña, te presento a mi lanza!",
		SPIDER_WARRIOR = "¡Prepárate para ser asesinada!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "¡Odin te vencerá!",
		PIG = "¡Volveré, piel de cerdo!",
		PREY = "¡Te dejaré marchar esta vez!",
		SPIDER = "Cobarde, no huyas.",
		SPIDER_WARRIOR = "¡Huye, monstruo! Volveré.",
	},

	DESCRIBE =
	{		
		BIGFISHINGROD = "Atraparé deliciosa carne de pescado.",
		BIGFOOT = "¡Esto es algo completamente diferente!",
		COFFEEBOT = "La mejor máquina bajo el sol.",
		DEPLETED_GRASS_WATER = "Está totalmente condenado.",
		HOUNDFIRE = "¡Arde con pasión eterna!",
		INVENTORYGRAVE = "¡Te veré en Valhalla!",
		INVENTORYMOUND = "¡Te veré en Valhalla!",
		LIMPETS_COOKED = "¡Démonos un festín!",
		WOODLEGSBOAT = "Preferiría un drakar.",
		WOODLEGSHAT = "Palidece en comparación con mi casco.",
		WOODLEGSSAIL = "Una tela temible.",
		GLOMMER = "Un bicho majestuoso.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Una maravilla de los bosques.",
        	DEAD = "Una vez fue una maravilla de los bosques.",
        },
        GLOMMERWINGS = "Oh, mira qué porquería me ha dejado.",
        GLOMMERFUEL = "Esta porquería podría ser útil.",
        BELL = "Prefiero el sonido de las espadas chocando.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Un curioso homenaje a los dioses.",
        	EMPTY = "Eso no ha sido muy respetuoso de mi parte.",
        },

		WEBBERSKULL = "Luchó con valentía, pero su entierro no será el de un vikingo.",
		WORMLIGHT = "¡Tesoro brillante, no puedo resistir!",
		WORMLIGHT_LESSER = "¡Brilla! ¡Brilla con toda tu fuerza!",
		WORM =
		{
		    PLANT = "Huelo una trampa.",
		    DIRT = "¿Qué hay debajo de la tierra?",
		    WORM = "¡Una bestia serpiente de las profundidades!",
		},
		WORMLIGHT_PLANT = "Huelo una trampa.",
		MOLE =
		{
			HELD = "Un amigo para mi bolsillo.",
			UNDERGROUND = "¿Quién está ahí debajo?",
			ABOVEGROUND = "Excava con un abandono imprudente.",
		},
		MOLEHILL = "Algo diabólico vive ahí abajo.",
		MOLEHAT = "Es mejor utilizar cada parte del animal.",

		EEL = "Delicioso pescado serpiente viscoso.",
		EEL_COOKED = "¡Anguila caliente!",
		UNAGI = "No hace falta que la comida sea tan bonita.",
		EYETURRET = "El ojo del dios del láser me está mirando el alma.",
		EYETURRET_ITEM = "¡Un antiguo globo ocular protector!",
		MINOTAURHORN = "¿Puedo añadir esto a mi casco?",
		MINOTAURCHEST = "¡El cofre de la conquista!",
		THULECITE_PIECES = "Parece brillante maíz estallado.",
		POND_ALGAE = "Flora antigua.",
		GREENSTAFF = "Energía verde que gira.",
		POTTEDFERN = "¿Qué se supone que tengo que hacer con esto?",

		THULECITE = "¡Este material posee una fuerza gigantesca!",
		ARMORRUINS = "¡Una armadura apta para el mismo Odín!",
		RUINS_BAT = "¡La varita de un guerrero!",
		RUINSHAT = "¡Una corona que lucha!",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Nothing stirs.",
			WARN = "It's starting...",
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			NOMAGIC = "The magic slumbers far from here.",
		},
		BISHOP_NIGHTMARE = "¡Cuidado con sus ráfagas!",
		ROOK_NIGHTMARE = "¡No me asustas!",
		KNIGHT_NIGHTMARE = "No creo que pudiera montar en ese caballo.",
		MINOTAUR = "Qué maravilla. ¡Retémonos a un duelo!",
		SPIDER_DROPPER = "¡Eres tan astuto!",
		NIGHTMARELIGHT = "Aprovecha los poderes oscuros de abajo.",
		NIGHTSTICK = "Un arma digna de Thor.",
		GREENGEM = "Una piedra de esmeralda.",
		RELIC = "Old bits of a dwelling.",
		RUINS_RUBBLE = "I'm quite crafty. I could repair that.",
		MULTITOOL_AXE_PICKAXE = "¡Una herramienta de guerrero!",
		ORANGESTAFF = "Un báculo de movimiento mágico.",
		YELLOWAMULET = "Una estrella capturada en un amuleto.",
		GREENAMULET = "¡Habilidades de fabricación de esmeraldas mejoradas!",
		SLURPERPELT = "I do love furs.",	

		SLURPER = "¡El enemigo peludo cree que es un sombrero!",
		SLURPER_PELT = "Me encantan las pieles.",
		SLURPERPELT = "Me encantan las pieles.",
		ARMORSLURPER = "Me sacia el apetito. Buena piel.",
		ORANGEAMULET = "Reunir esto nunca ha sido tan fácil.",
		YELLOWSTAFF = "¡Invoca estrellas!",
		YELLOWGEM = "Una belleza amarilla.",
		ORANGEGEM = "Una piedra de color naranja.",
		TELEBASE = 
		{
			VALID = "Prepare yourselves for the power of purple!",
			GEMS = "There's still gems missing.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "It's empty.",
		},
		STAFFLIGHT = "¡He aquí un regalo de Wotan!",
	
        ANCIENT_ALTAR = "Será mejor que esta artesanía sea buena.",

        ANCIENT_ALTAR_BROKEN = "Este no funciona.",

        ANCIENT_STATUE = "Tesoro con un aura misteriosa.",

        LICHEN = "Planta tonta del cielo azul.",
		CUTLICHEN = "Lo he cogido. Pero no me lo comeré.",

		CAVE_BANANA = "Comida de mono.",
		CAVE_BANANA_COOKED = "Carne de mono caliente.",
		CAVE_BANANA_TREE = "Un árbol endeble para monos.",
		ROCKY = "Puede ser un digno compañero de combate.",
		
		COMPASS =
		{
			GENERIC= "No consigo hacer que funcione.",
			N = "Norte.",
			S = "Sur.",
			E = "Este.",
			W = "Oeste.",
			NE = "Nordeste.",
			SE = "Sureste.",
			NW = "Noroeste.",
			SW = "Sudoeste.",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "¡La magia se está acentuando!",
			STEADY = "La magia guarda energía constante.",
			WANING = "¡Está empezando a retirarse!",
			DAWN = "Apenas queda nada de magia.",
			WARN = "Está empezando...",
			CALM = "Nada se mueve.",
			NOMAGIC = "La magia duerme desde aquí.",
		},

		HOUNDSTOOTH="Un símbolo de mi conquista.",
		ARMORSNURTLESHELL="Una especie de escudo.",
		BAT="Carne oscura con alas.",
		BATBAT = "Winged spear!",
		BATWING="Como las alas de mi casco, solo que con carne.",
		BATWING_COOKED="Ala oscura cocinada.",
		BEDROLL_FURRY="¡Una cama de piel de lujo!",
		BUNNYMAN="Te comeré.",
		FLOWER_CAVE="E iluminó la noche, en la hora más oscura.",
		FLOWER_CAVE_DOUBLE="E iluminó la noche, en la hora más oscura.",
		FLOWER_CAVE_TRIPLE="E iluminó la noche, en la hora más oscura.",
		GUANO="Hmm, porquería de alas oscuras.",
		LANTERN="Una linterna para la oscuridad.",
		LIGHTBULB="¡Brilla!",
		MANRABBIT_TAIL="El trofeo peludo de una batalla exitosa.",
		MUSHTREE_TALL  ="¿Qué es esta magia?",
		MUSHTREE_MEDIUM="Me gusta su brillo.",
		MUSHTREE_SMALL ="Me dan igual los champiñones.",
		RABBITHOUSE=
		{
			GENERIC = "¿Qué voy a hacer con una zanahoria tan grande?",
			BURNT = "Hasta nunca, zanahoria gigante.",
		},
		SLURTLE="Eres un ángel. Desagradable.",
		SLURTLE_SHELLPIECES="Han quedado bien destrozadas.",
		SLURTLEHAT="¡Un nuevo casco de batalla para mi colección!",
		SLURTLEHOLE="No es donde elegiría colgar mi casco.",
		SLURTLESLIME="Sí. Baba.",
		SNURTLE="Me gusta su casco.",
		SPIDER_HIDER="¡Te aplastaré!",
		SPIDER_SPITTER="Esta es luchadora.",
		SPIDERHOLE="Telarañas. Nunca una buena señal.",
		STALAGMITE="Una roca de cueva.",
		STALAGMITE_FULL="Una roca de cueva.",
		STALAGMITE_LOW="Una roca de cueva.",
		STALAGMITE_MED="Una roca de cueva.",
		STALAGMITE_TALL="Una especie de roca puntiaguda.",
		STALAGMITE_TALL_FULL="Una especie de roca puntiaguda.",
		STALAGMITE_TALL_LOW="Una especie de roca puntiaguda.",
		STALAGMITE_TALL_MED="Una especie de roca puntiaguda.",

		TURF_CARPETFLOOR = "Absorbe la sangre de la batalla.",
		TURF_CHECKERFLOOR = "Suelo elegante.",
		TURF_DIRT = "Una pieza del campo de batalla.",
		TURF_FOREST = "Una pieza del campo de batalla.",
		TURF_GRASS = "Una pieza del campo de batalla.",
		TURF_MARSH = "Una pieza del campo de batalla.",
		TURF_ROAD = "El camino a la batalla conduce donde yo elija.",
		TURF_ROCKY = "Una pieza del campo de batalla.",
		TURF_SAVANNA = "Una pieza del campo de batalla.",
		TURF_WOODFLOOR = "Suelo de madera, una superficie elegante para el combate mortal.",

		TURF_CAVE="Una pieza del campo de batalla.",
		TURF_FUNGUS="Una pieza del campo de batalla.",
		TURF_SINKHOLE="Una pieza del campo de batalla.",
		TURF_UNDERROCK="Una pieza del campo de batalla.",
		TURF_MUD="Una pieza del campo de batalla.",

		POWCAKE = "¿Qué es esto, en el nombre del unicornio?",
        CAVE_ENTRANCE = 
        {
            GENERIC="¿Qué tesoros yacen debajo?",
            OPEN = "¡A los infiernos!",
        },
        CAVE_EXIT = "¡Vuelta al cielo abierto!",
		MAXWELLPHONOGRAPH = "Una cantante mecánica.",
		BOOMERANG = "¡Para arrojárselo a los enemigos!",
		PIGGUARD = "Está listo para batalla. Lo noto.",
		ADVENTURE_PORTAL = "La aventura me está llamando.",
		AMULET = "Es rojo y es un luchador. ¡Igual que yo!",
		ANIMAL_TRACK = "¡Ah! Me encanta una buena caza.",
		ARMORGRASS = "Protección de hierba. No va a durar mucho.",
		ARMORMARBLE = "¡Casi impenetrable!",
		ARMORWOOD = "Un chaleco de árbol prestado.",
		ARMOR_SANITY = "Es fuerte, pero creo que mi mente divaga...",
		ASH =
		{
			GENERIC = "Restos de las llamas.",
			REMAINS_GLOMMERFLOWER = "La flor debe quedarse en su mundo natal.",
			REMAINS_EYE_BONE = "El hueso con ojo no podría entrar en este mundo.",
			REMAINS_THINGIE = "Se ha quemado. Adiós.",
		},
		AXE = "¡Talar y destruir!",
		BABYBEEFALO = "Minibestia.",
		BACKPACK = "Una armería portátil.",
		BANDAGE = "Para curar mis heridas de batalla.",
		BASALT = "Mil mortales no han podido romper esta piedra.",
		BATBAT = "¡Lanza de ala!",
		BEARDHAIR = "Piel de la locura.",
		BEDROLL_STRAW = "Una herramienta para mis siestas.",
		BEARGER = "¿Oso muy osado?",
		BEARGERVEST = "¡Soy una berserker!",
		ICEPACK = "La mochila de la bestia.",
		BEARGER_FUR = "Ha luchado valientemente, pero yo he reclamado su piel.",
		BEE =
		{
			GENERIC = "¡Pequeñas guerreras! No sé si me gustan.",
			HELD = "¡Fácil ahora!",
		},
		BEEBOX =
		{
			FULLHONEY = "¡Es un tesoro de miel!",
			GENERIC = "Una dulce caja de pequeños guerreros.",
			NOHONEY = "¿Dónde está la miel?",
			SOMEHONEY = "Algo de miel. Se necesita paciencia.",
			BURNT = "Mi colmena está en silencio.",
		},
		BEEFALO =
		{
			FOLLOWER = "Sígueme, bestia.",
			GENERIC = "¡Antiguas bestias de lana!",
			NAKED = "¿No tienes frío sin la lana?",
			SLEEPING = "Suena como la tía Hilda.",
		},
		BEEFALOHAT = "Me va a quedar bien, lo sé.",
		BEEFALOWOOL = "Me encantan las cosas de lana.",
		BEEHAT = "Mi casco de abeja, por supuesto.",
		BEEHIVE = "Siempre zumbando, siempre tramando.",
		BEEMINE = "Suena sospechoso.",
		BEEMINE_MAXWELL = "¡Cuidado dónde pisas!",
		BERRIES = "Frutas. No me gustan.",
		BERRIES_COOKED = "Puré rojo caliente.",
		BERRYBUSH =
		{
			BARREN = "¿Y si echo algo de estiércol?",
			WITHERED = "Hace demasiado calor para crecer.",
			GENERIC = "Un arbusto de frutos.",
			PICKED = "Le han quitado los frutos.",
		},
		BIRDCAGE =
		{
			GENERIC = "¡Un hogar para mis cuervos!",
			OCCUPIED = "¿Te lo estás pasando bien?",
			SLEEPING = "Dulces sueños, amigo cuervo.",
		},
		BIRDTRAP = "¡Soy una cazadora de cuervos astuta!",
		BIRD_EGG = "Huevecito.",
		BIRD_EGG_COOKED = "Huevo caliente.",
		BISHOP = "Este necesita un buen tortazo.",
		BLOWDART_FIRE = "Como el aliento de un dragón.",
		BLOWDART_SLEEP = "Buenas noches a mis enemigos.",
		BLOWDART_PIPE = "¡Armas de proyectil!",
		BLUEAMULET = "Joyas frías.",
		BLUEGEM = "Un zafiro azul hielo.",
		BLUEPRINT = "¡Oh, un mapa! No, espera. Eso está mal.",
		BELL_BLUEPRINT = "¡Oh, un mapa! No, espera. Eso está mal.",
		BLUE_CAP = "Hmm, uno azul.",
		BLUE_CAP_COOKED = "Aún no quiero comérmelo.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Es moho, realmente.",
			INGROUND = "Bien, se está escondiendo.",
			PICKED = "Espero que no vuelva a crecer.",
		},
		BOARDS = "Troncos de abuelo.",
		BOAT = "¿Así es como he llegado aquí?",
		BONESHARD = "Pedacitos de mis enemigos.",
		BONESTEW = "¡Delicioso!",
		BUGNET = "Para atrapar insectos desde el aire.",
		BUSHHAT = "Para la caza.",
		BUTTER = "Mantequilla. ¿Podría ser buena en la carne?",
		BUTTERFLY =
		{
			GENERIC = "Es más o menos bonita.",
			HELD = "¡Atrapada!",
		},
		BUTTERFLYMUFFIN = "Magdalena, dalena, dalena.",
		BUTTERFLYWINGS = "Un bonito recuerdo.",
		BUZZARD = "Tú y yo, juntos formamos un festín.",
		CACTUS = 
		{
			GENERIC = "Tiene una armadura admirable.",
			PICKED = "Regresará.",
		},
		CACTUS_MEAT_COOKED = "Carne de planta-espada asada.",
		CACTUS_MEAT = "Carne de planta-espada.",
		CACTUS_FLOWER = "Maña con belleza.",
		COLDFIRE =
		{
			EMBERS = "Este fuego está casi muerto.",
			GENERIC = "Un confort frío.",
			HIGH = "¡El fuego ruge!",
			LOW = "El fuego está muriendo lentamente.",
			NORMAL = "Un confort frío.",
			OUT = "Y la luz se apaga.",
		},
		CAMPFIRE =
		{
			EMBERS = "Este fuego está casi muerto.",
			GENERIC = "Fuego caliente, Wigfrid caliente.",
			HIGH = "¡El fuego ruge!",
			LOW = "El fuego está muriendo lentamente.",
			NORMAL = "Fuego caliente, Wigfrid caliente.",
			OUT = "Y la luz se apaga.",
		},
		CANE = "El \"andar\" se vuelve \"trotar\".",
		CATCOON = "¡Ah! Bonita carne con piel.", 
		CATCOONDEN = 
		{
			GENERIC = "Aquí vive carne bonita.",
			EMPTY = "Luchó con valentía. Pero ay, se fue.",
		},
		CATCOONHAT = "¡Un gorro peludo! Te bendigo, carne bonita.",
		COONTAIL = "Es la cola de una bonita carne.",
		CARROT = "¿Dónde está la proteína?",
		CARROT_COOKED = "Pobres zanahorias cocidas.",
		CARROT_PLANTED = "Una pequeña raíz vegetal.",
		CARROT_SEEDS = "Pedacitos pequeños de la naturaleza.",
		CAVE_FERN = "Follaje de la Edad Media.",
		CHARCOAL = "Botín de Loge, el semidiós.",
        CHESSJUNK1 = "No es más que un montón de guerreros caídos.",
        CHESSJUNK2 = "Más mecánicos guerreros caídos.",
        CHESSJUNK3 = "Alguien debería realmente limpiar este lugar.",
		CHESTER = "No te preocupes, no me lo comeré.",
		CHESTER_EYEBONE =
		{
			GENERIC = "¿Quién eres?",
			WAITING = "El globo ocular está cansado.",
		},
		COOKEDMANDRAKE = "Está definitivamente muerta.",
		COOKEDMEAT = "¡Carneee!",
		COOKEDMONSTERMEAT = "Filete de monstruo.",
		COOKEDSMALLMEAT = "Ñam, ñam, aperitivos de carne.",
		COOKPOT =
		{
			COOKING_LONG = "Podría también hacer algo mientras espero.",
			COOKING_SHORT = "¡No debería tardar mucho!",
			DONE = "¿Qué tenemos aquí?",
			EMPTY = "No hay nada ahí.",
			BURNT = "El fuego ha reinado.",
		},
		CORN = "¡Una espada vegetal!",
		CORN_COOKED = "Las palomitas de maíz huelen bien.",
		CORN_SEEDS = "Pedacitos pequeños de la naturaleza.",
		CROW =
		{
			GENERIC = "¡Amigo cuervo!",
			HELD = "Juntos de nuevo.",
		},
		CUTGRASS = "El recurso más elemental de una artesana.",
		CUTREEDS = "¡He quitado todos los bichos! Y luego me los he comido.",
		CUTSTONE = "¡Roca sólida!",
		DEADLYFEAST = "Un plato muy potente.",
		DEERCLOPS = "¡Los rayos brillarán a través de mi lanza y te arrancarán el ojo!",
		DEERCLOPS_EYEBALL = "¿Hmm, debo comérmelo?",
		EYEBRELLAHAT = "¡Que no te llueva en el ojo!",
		DEPLETED_GRASS =
		{
			GENERIC = "Es probablemente un manojo de hierba.",
		},
		DEVTOOL = "¡Huele a tocino!",
		DEVTOOL_NODEV = "No soy lo bastante fuerte como para hacerla funcionar.",
		DIRTPILE = "Un pequeño montículo de tierra.",
		DIVININGROD =
		{
			COLD = "Todo está tranquilo.",
			GENERIC = "Un sabueso de caza mecánica. Para la cacería.",
			HOT = "¡Que suenen los cuernos! ¡Hemos llegado!",
			WARM = "¡Tenemos el perfume!",
			WARMER = "El perro está ansioso. Nos estamos acercando.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Qué ruinas más crípticas.",
			READY = "Parece que me falta una pieza...",
			UNLOCKED = "¡Listo! ¡La saga continúa!",
		},
		DIVININGRODSTART = "Esta espada misteriosa se siente importante.",
		DRAGONFLY = "¡Ah, dragón! ¡Al fin nos encontramos!",
		ARMORDRAGONFLY = "Una armadura excelente para el calor de la batalla.",
		DRAGON_SCALES = "Escamas místicas.",
		DRAGONFLYCHEST = "Este cofre es digno de mis armas.",
		LAVASPIT = 
		{
			HOT = "¡Tus pozos de lava no son rival para mí!",
			COOL = "Ahora no da mucho miedo, ¿verdad?",
		},
		DRAGONFRUIT = "Mola mucho.",
		DRAGONFRUIT_COOKED = "Una fruta bonita a la plancha.",
		DRAGONFRUIT_SEEDS = "Pedacitos pequeños de la naturaleza.",
		DRAGONPIE = "¿Por qué no es esto un pastel de carne? ¡Carne, carneeeee!",
		DRUMSTICK = "Pierna de bestia, en mi vientre.",
		DRUMSTICK_COOKED = "¡Carne calienteeeee!",
		DUG_BERRYBUSH = "Creo que devolveré esto a la diosa de la tierra.",
		DUG_GRASS = "Creo que devolveré esto a la diosa de la tierra.",
		DUG_MARSH_BUSH = "Creo que devolveré esto a la diosa de la tierra.",
		DUG_SAPLING = "Creo que devolveré esto a la diosa de la tierra.",
		DURIAN = "Huele como mis botas de batalla.",
		DURIAN_COOKED = "¿Por qué he vuelto a cocinar esto?",
		DURIAN_SEEDS = "Pedacitos pequeños de la naturaleza.",
		EARMUFFSHAT = "¡Sí, qué práctico!",
		EGGPLANT = "Morada y bulbosa.",
		EGGPLANT_COOKED = "Alimentos para los más débiles.",
		EGGPLANT_SEEDS = "Pedacitos pequeños de la naturaleza.",
		DECIDUOUSTREE = 
		{
			BURNING = "¡La madera está ardiendo!",
			BURNT = "Se lo ha llevado Loge.",
			CHOPPED = "¡Talado por el guerrero de los bosques!",
			POISON = "Tengo que trabajar un poco más con esta leña.",
			GENERIC = "¡Futura leña!",
		},
		ACORN = 
		{
		    GENERIC = "Hay un árbol escondido dentro.",
		    PLANTED = "¡Creced fuertes, ramitas jóvenes!",
		},
		ACORN_COOKED = "He cocinado el árbol joven.",
		BIRCHNUTDRAKE = "¡Un árbol joven guerrero!",
		EVERGREEN =
		{
			BURNING = "¡La madera está ardiendo!",
			BURNT = "Se lo ha llevado Loge.",
			CHOPPED = "¡Talado por el guerrero de los bosques!",
			GENERIC = "Me siento en casa en el bosque.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "¡La madera está ardiendo!",
			BURNT = "Se lo ha llevado Loge.",
			CHOPPED = "¡Talado por el guerrero de los bosques!",
			GENERIC = "Un árbol bien robusto.",
		},
		EYEPLANT = "¡No me mires con tu ojo, follaje!",
		FARMPLOT =
		{
			GENERIC = "No puedo producir carne, ¿de qué sirve?",
			GROWING = "Están creciendo más fuertes.",
			NEEDSFERTILIZER = "Quiere una fiesta de estiércol.",
			BURNT = "¡Esto por no producir carne!",
		},
		FEATHERHAT = "Parece un poco llamativo para la batalla.",
		FEATHER_CROW = "¡Un símbolo de los cuervos!",
		FEATHER_ROBIN = "Rojo como mi cabello.",
		FEATHER_ROBIN_WINTER = "Pluma de invierno.",
		FEM_PUPPET = "Parece infeliz sobre su trono.",
		FIREFLIES =
		{
			GENERIC = "¡Las hadas diminutas brillan!",
			HELD = "¡Tengo la luz!",
		},
		FIREHOUND = "El que ha ardido no tiene piedad.",
		FIREPIT =
		{
			EMBERS = "Este fuego está casi apagado.",
			GENERIC = "Fuego caliente, Wigfrid caliente.",
			HIGH = "¡El fuego ruge!",
			LOW = "El fuego está muriendo lentamente.",
			NORMAL = "Fuego caliente, Wigfrid caliente.",
			OUT = "Y la luz se apaga.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Este fuego está casi muerto.",
			GENERIC = "Un confort frío.",
			HIGH = "¡El fuego ruge!",
			LOW = "El fuego está muriendo lentamente.",
			NORMAL = "Un confort frío.",
			OUT = "Y la luz se apaga.",
		},
		FIRESTAFF = "¡Wigfrid! ¡Maestra del fuego!",
		FIRESUPPRESSOR = 
		{	
			ON = "¡Catapulta preparada para la batalla!",
			OFF = "Hora de descansar, aguerrido guerrero.",
			LOWFUEL = "La catapulta se debilita y se cansa.",
		},

		FISH = "¡Carne del mar!",
		FISHINGROD = "Soy una pescadora sin escrúpulos.",
		FISHSTICKS = "Lanzas de carne marina.",
		FISHTACOS = "¡Pez envuelto!",
		FISH_MED = "Descansa en paz en Valhalla.",
		FISH_MED_COOKED = "¡Alegría!",
		FISH_COOKED = "¡Alegría!",
		FLINT = "Vital para la construcción de la lanza.",
		FLOWER = "Una flor de Freya.",
		FLOWERHAT = "Débil para la lucha, bonito para mi cabeza.",
		FLOWER_EVIL = "Un terrible mal asola esta flora.",
		FOLIAGE = "Una colección de helechos.",
		FOOTBALLHAT = "Mi casco ha sido fabricado con el trasero de un cerdo.",
		FROG =
		{
			DEAD = "Eres un poco babosa para Valhalla.",
			GENERIC = "Me gustaría tener unas botas de rana algún día.",
			SLEEPING = "Está dormida.",
		},
		FROGGLEBUNWICH = "¡Qué banquete!",
		FROGLEGS = "¡Llenas de proteína carnosa!",
		FROGLEGS_COOKED = "Me gusta cuando veo sobresalir los huesos.",
		FRUITMEDLEY = "¡Agh! Que esté en una copa no me engaña.",
		GEARS = "Esto podría quedar bonito pegado en mi casco.",
		GHOST = "Un espíritu atrapado entre dos mundos.",
		GOLDENAXE = "¡Una herramienta de oro!",
		GOLDENPICKAXE = "Oro para el oro.",
		GOLDENPITCHFORK = "¿Por qué he hecho una horca tan lujosa?",
		GOLDENSHOVEL = "¡Excavando como un rey!",
		GOLDNUGGET = "Estoy contenta con esta pepita de oro.",

		GRASS =
		{
			BARREN = "Se ha quedado sin vida.",
			WITHERED = "El calor ha derrotado a esta planta.",
			BURNING = "¡Loge te mira!",
			GENERIC = "Esto podría ser útil.",
			PICKED = "Ha caído ante mi poder.",
		},
		GREEN_CAP = "¡Terrible!",
		GREEN_CAP_COOKED = "¡Carbonizado por el fuego o no, no tocará mis labios!",
		GREEN_MUSHROOM =
		{
			GENERIC = "¡Ha crecido!",
			INGROUND = "Escóndete, cobarde.",
			PICKED = "Veo las esporas del hongo.",
		},
		GUNPOWDER = "¡Cuánta energía!",
		HAMBAT = "¡Un arma para los grandes comedores!",
		HAMMER = "Más apto para el trabajo que la batalla.",
		HEALINGSALVE = "¡Lléname de vida!",
		HEATROCK =
		{
			FROZEN = "¡Los dientes fríos me muerden!",
			COLD = "¡La piedra se ha puesto fría!",
			GENERIC = "¡Una piedra de gran utilidad!",
			WARM = "¡La piedra se ha puesto caliente!",
			HOT = "Loge estaría orgulloso.",
		},
		HOMESIGN = 
		{
			GENERIC = "Una señal bien colocada.",
			UNWRITTEN = "¡Escribiré un relato de triunfo!",
			BURNT = "Signos de una batalla pasada.",
		},
		HONEY = "Pegajoso y asqueroso.",
		HONEYCOMB = "Cuánta dulzura.",
		HONEYHAM = "¡Un festín abundante!",
		HONEYNUGGETS = "¡Un festín en pepitas!",
		HORN = "Qué ganas tengo de una batalla.",
		HOUND = "¡Engendro de Fenrir!",
		HOUNDBONE = "Un enemigo caído.",
		HOUNDMOUND = "Estos perros son realmente guerreros.",
		ICEBOX = "¡El invierno habita dentro!",
		ICEHAT = "Un trozo de frío.",
		ICEHOUND = "¡Dientes de las heladas!",
		INSANITYROCK =
		{
			ACTIVE = "¡Ahhh!",
			INACTIVE = "No sospecho nada de esta roca.",
		},
		JAMMYPRESERVES = "Pegajoso y asqueroso.",
		KABOBS = "¡Carne metida en un palo! ¡Sí!",
		KILLERBEE =
		{
			GENERIC = "¡Una contendiente!",
			HELD = "Un enemigo conquistado.",
		},
		KNIGHT = "¡Huelo la batalla!",

		KOALEFANT_SUMMER = "Querida criatura... Voy a comerte.",
		KOALEFANT_WINTER = "Pobre bestia de carne incauta.",
		KRAMPUS = "¡No me asustas, cabra!",
		KRAMPUS_SACK = "¡Puedo caber aquí!",
		LEIF = "Es un antiguo ser del bosque.",
		LEIF_SPARSE = "Es un antiguo ser del bosque.",
		LIGHTNING_ROD =
		{
			CHARGED = "¡Oh, gran relámpago!",
			GENERIC = "¡Trae contigo el relámpago, Donner!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "¿Puedo llamarte unicornio?",
			CHARGED = "¡El rayo te ha convertido en un guerrero unicornio!",
		},
		LIGHTNINGGOATHORN = "Esto podría dar un golpe duradero.",
		GOATMILK = "Esto es leche poderosa.",
		LITTLE_WALRUS = "Un engendro de la malvada foca con dientes.",
		LIVINGLOG = "Quemar esta magia parece un desperdicio.",
		LOCKEDWES = "¡Te salvaré, silencioso mortal!",
		LOG =
		{
			BURNING = "¡Tronco en llamas!",
			GENERIC = "La madera siempre es de valor.",
		},
		LUREPLANT = "¡Por fin! Un vegetal útil.",
		LUREPLANTBULB = "¡Tal vez seré una granjera de carne después de todo!",
		MALE_PUPPET = "Parece infeliz en su trono.",
		MANDRAKE =
		{
			DEAD = "El cadáver del colinabo conserva su magia.",
			GENERIC = "¡Un colinabo!",
			PICKED = "Quiere reunir una saga de colinabos.",
		},
		MANDRAKESOUP = "¡Un guiso de magia!",
		MANDRAKE_COOKED = "Colinabo a la plancha.",
		MARBLE = "¡La piedra del guerrero!",
		MARBLEPILLAR = "¡Perfecta para un palacio!",
		MARBLETREE = "Ni siquiera los vientos derribarán a este árbol.",
		MARSH_BUSH =
		{
			BURNING = "¡Tronco caliente!",
			GENERIC = "Un arbusto en guardia.",
			PICKED = "Qué fastidio.",
		},
		MARSH_PLANT = "Follaje de estanque.",
		MARSH_TREE =
		{
			BURNING = "¡Está ardiendo!",
			BURNT = "Quemado.",
			CHOPPED = "Mi hacha de batalla siempre gana.",
			GENERIC = "Un árbol guerrero.",
		},
		MAXWELL = "¡Arrg! ¿¡Es el antagonista de mi saga!?",
		MAXWELLHEAD = "Puedo ver a través de sus poros.",
		MAXWELLLIGHT = "La magia oscura vive aquí.",
		MAXWELLLOCK = "¿Lo abro?",
		MAXWELLTHRONE = "Prefiero vagar libre, mi unicornio y yo.",
		MEAT = "¡La verdadera fruta de la tierra!",
		MEATBALLS = "Bolas de banquete diminutas.",
		MEATRACK =
		{
			DONE = "¡A comer!",
			DRYING = "Está quedando como me gusta.",
			DRYINGINRAIN = "Esta lluvia no ayuda.",
			GENERIC = "¡Ah! ¡Un estante colgante para mi carne!",
			BURNT = "Una pena.",
		},
		MEAT_DRIED = "Provisiones para la batalla excelentes.",
		MERM = "¡Muere, pez bestia empapado!",
		MERMHEAD = 
		{
			GENERIC = "¡Podría olerla desde allí!",
			BURNT = "Decapitada. Quemada. Apestosa.",
		},
		MERMHOUSE = 
		{
			GENERIC = "¿Es esta vivienda hecha de pescado?",
			BURNT = "No me lo perderé.",
		},
		MINERHAT = "¡Un casco con luz! Para la oscuridad.",
		MONKEY = "No me fío de él.",
		MONKEYBARREL = "¿Qué maravillas habrá dentro?",
		MONSTERLASAGNA = "Guiso de monstruo.",
		FLOWERSALAD = "Las hojas son para los animales. Los animales son para comérselos.",
        ICECREAM = "Me duelen los dientes.",
        WATERMELONICLE = "No puedes engañarme escondiéndote en fruta congelada, palo.",
        TRAILMIX = "La carne de un fruto seco no es carne verdadera.",
        HOTCHILI = "Una prueba de mi fuerza de voluntad.",
        GUACAMOLE = "¡Ñam, cremoso!",
		MONSTERMEAT = "Carne de las bestias oscuras.",
		MONSTERMEAT_DRIED = "Se ha secado del todo.",
		MOOSE = "Ojalá pudiera montar en él para luchar.",
		MOOSEEGG = "Algo está rebotando dentro.",
		MOSSLING = "No eres lo bastante grande como para ser mi corcel.",
		FEATHERFAN = "Los lujos del campamento, sobre la marcha.",
		TROPICALFAN = "Los lujos del campamento, sobre la marcha.",
		GOOSE_FEATHER = "Una escudera merece una suave cama de plumas.",
		STAFF_TORNADO = "Una tormenta de dolor.",
		MOSQUITO =
		{
			GENERIC = "¡Aghh! ¡Estas cosas son inútiles!",
			HELD = "¡Detente, furia del demonio!",
		},
		MOSQUITOSACK = "La sangre me hará más fuerte.",
		MOUND =
		{
			DUG = "¡Quería el botín!",
			GENERIC = "¿Hay tesoros debajo de las lápidas?",
		},
		NIGHTLIGHT = "Estoy más cómoda cerca de mi propio fuego.",
		NIGHTMAREFUEL = "¡El combustible de la oscuridad!",
		NIGHTSWORD = "Hace falta un valiente guerrero para empuñar esta espada.",
		NITRE = "Contiene componentes explosivos.",
		ONEMANBAND = "¡Canta conmigo! ¡Somos los guardianes de Asgard!",
		PANDORASCHEST = "Contiene un misterio.",
		PANFLUTE = "Prefiero enfrentarme a mis enemigos despiertos.",
		PAPYRUS = "Esto continuará el registro de mi saga.",
		PENGUIN = "Aves del mar, procedentes de lejos.",
		PERD = "¡No puedes correr para siempre!",
		PEROGIES = "Bolsillos de carne.",
		PETALS = "¡Gracias por este regalo, Froh!",
		PETALS_EVIL = "Estos no los hizo Froh.",
		PICKAXE = "Puedo usarla para obtener preciosos materiales para lanzas y yelmos.",
		PIGGYBACK = "El cerdo murió con honor y me dio esta mochila.",
		PIGHEAD = 
		{	
			GENERIC = "Esto es salvajismo.",
			BURNT = "Normalmente me gusta un buen asado, pero esto no es correcto.",
		},
		PIGHOUSE =
		{
			FULL = "¡Salid y venid a la guerra conmigo!",
			GENERIC = "No sabía que los cerdos pudieran hacer casas.",
			LIGHTSOUT = "¿No tienes hambre de batalla, cerdo?",
			BURNT = "Loge no te ha sonreído hoy.",
		},
		PIGKING = "¿Es el cerdo-Odín?",
		PIGMAN =
		{
			DEAD = "Murió con honor.",
			FOLLOWER = "¡Nos dirigimos a la batalla!",
			GENERIC = "¿Lucharás conmigo, cerdo?",
			GUARD = "Ese cerdo parece valiente.",
			WEREPIG = "Ha sido mancillado por Fenrir.",
		},
		PIGSKIN = "La piel de un cerdo.",
		PIGTORCH = "¿Adoran estos cerdos a Loge?",
		PINECONE = 
		{
		    GENERIC = "Este árbol bebé está bien protegido por una armadura de pinchos.",
		    PLANTED = "Se ha despojado de su armadura. ¡Crece, árbol bebé!",
		},
		PITCHFORK = "Un arma para los agricultores.",
		PLANTMEAT = "Supongo que está lo suficientemente cerca.",
		PLANTMEAT_COOKED = "Todavía está verde, pero servirá.",
		PLANT_NORMAL =
		{
			GENERIC = "Una planta.",
			GROWING = "¡Soy una escudera, no una granjera!",
			READY = "Agh, verduras. No sé bien lo que esperaba...",
			WITHERED = "Derrotada por el sol.",
		},
		POMEGRANATE = "Carne con sabor a fruta.",
		POMEGRANATE_COOKED = "Carne de fruta a la plancha.",
		POMEGRANATE_SEEDS = "Pedacitos pequeños de la naturaleza.",
		POND = "Algo acecha en las profundidades.",
		POOP = "Ojalá pudiera usarlo como camuflaje contra los depredadores.",
		FERTILIZER = "Su hedor podría levantar a los caídos.",
		PUMPKIN = "Podría ser un buen garrote, por lo menos.",
		PUMPKINCOOKIE = "Se le ha quitado toda la vida cocinándola.",
		PUMPKIN_COOKED = "Papilla naranja ardiendo.",
		PUMPKIN_LANTERN = "¿Quieres luchar, vegetal?",
		PUMPKIN_SEEDS = "Pedacitos pequeños de la naturaleza.",
		PURPLEAMULET = "Un amuleto de poderes oscuros.",
		PURPLEGEM = "Está nublado con una energía misteriosa.",
		RABBIT =
		{
			GENERIC = "¡Salta en mi boca!",
			HELD = "¡No hay escapatoria!",
		},
		RABBITHOLE = 
		{
			GENERIC = "¡Hora del espectáculo, conejos!",
			SPRING = "Debe ser el intermedio para los conejos.",
		},
		RAINOMETER = 
		{	
			GENERIC = "Predice la llegada de lluvia.",
			BURNT = "Sus días de profecías han terminado.",
		},
		RAINCOAT = "Armadura para la lluvia.",
		RAINHAT = "Lucharemos en la lluvia.",
		RATATOUILLE = "Un montón de verduras. No, gracias.",
		RAZOR = "Un filo pequeño, pero un filo al fin y al cabo.",
		REDGEM = "Es caliente al tacto.",
		RED_CAP = "Umami o no, no lo quiero.",
		RED_CAP_COOKED = "No me lo comeré, pero ha sido divertido meterlo en el fuego.",
		RED_MUSHROOM =
		{
			GENERIC = "Al menos tiene un color bonito.",
			INGROUND = "¡Y no salgas!",
			PICKED = "Hasta nunca.",
		},
		REEDS =
		{
			BURNING = "¡Nos vemos en Asgard, cañas!",
			GENERIC = "Estas cañas son fuertes.",
			PICKED = "Cortadas cuando estaban en la flor de la vida.",
		},
        RELIC = 
        {
            GENERIC = "Sirve para Asgard.",
            BROKEN = "Se ha reducido a añicos.",
        },
        RUINS_RUBBLE = "Sus días aún no han terminado.",
        RUBBLE = "Un montón de rocas antiguas.",
		RESEARCHLAB = 
		{	
			GENERIC = "Prefiero la batalla a la ciencia.",
			BURNT = "Cenizas a las cenizas.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Tal vez la ciencia pueda mejorar mis habilidades de combate.",
			BURNT = "Polvo al polvo.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Una cosa mística.",
			BURNT = "Su extraño poder no me protegió del fuego.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Una máquina absurda que hace carne.",
			BURNT = "¡De aquí no saldrá más carne!",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "No sé por qué hice esto.",
			BURNT = "¡Ahí voy, Valhalla!",
		},
		RESURRECTIONSTONE = "Me protege de Valhalla.",
		ROBIN =
		{
			GENERIC = "Rojo como la sangre.",
			HELD = "Prefiero a tus hermanos negros.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Este pájaro conoce el frío.",
			HELD = "Qué plumas tan suaves.",
		},
		ROBOT_PUPPET = "¡Un preso!",
		ROCK_LIGHT =
		{
			GENERIC = "La corteza de lava está dura.",
			OUT = "Parece delicada.",
			LOW = "La corteza de lava se está rompiendo.",
			NORMAL = "¡Hermosa luz!",
		},
		ROCK = "¡Aplastar!",
		ROCK_ICE = 
		{
			GENERIC = "Una montaña congelada de miniatura.",
			MELTED = "¡Pobre glaciar!",
		},
		ROCK_ICE_MELTED = "¡Pobre glaciar!",
		ICE = "Me recuerda a mi hogar.",
		ROCKS = "Algunas rocas bastante normales.",
        ROOK = "¡A la cargaaaaa!",
		ROPE = "Bastante fuerte para atar las velas de mi drakar.",
		ROTTENEGG = "Arruinado por comer, pero preparado para la batalla.",
		SANITYROCK =
		{
			ACTIVE = "No creo que pueda vencer a esta roca en combate.",
			INACTIVE = "¡Roca lista, no puedes sorprender a una guerrero!",
		},
		SAPLING =
		{
			BURNING = "¡Nooo! ¡Mis lanzas!",
			WITHERED = "Se ha encogido por el calor.",
			GENERIC = "Lo convertiré en una lanza.",
			PICKED = "¡He matado al pequeño árbol!",
		},
		SEEDS = "Pedacitos pequeños de la naturaleza.",
		SEEDS_COOKED = "Pequeños trozos de naturaleza, cocinados hasta la muerte.",
		SEWING_KIT = "No soy costurera, pero las reparaciones a veces son necesarias.",
		SHOVEL = "Preferiría un entierro del barco, aunque esto puede tener sus usos.",
		SILK = "Útil para tejer, y para recordar victorias pasadas.",
		SKELETON = "Descansa bien en Valhalla.",
		SKELETON_PLAYER = "Esta lucha aún no ha terminado.",
		SKULLCHEST = "Ah, ha sido una buena batalla.",
		SMALLBIRD =
		{
			GENERIC = "Tú aún no eres feroz, pájaro.",
			HUNGRY = "Debes comer para crecer fuerte.",
			STARVING = "El pequeño pájaro parece estar muerto de hambre.",
		},
		SMALLMEAT = "Un delicioso bocado carnoso.",
		SMALLMEAT_DRIED = "Una pequeña provisión para una larga campaña.",
		SPEAR = "No es mi lanza preferida, pero servirá.",
		SPIDER =
		{
			DEAD = "Derribada por mi lanza, como tantas otras.",
			GENERIC = "¡Ocho patas y todavía no son rival para mí!",
			SLEEPING = "Permitiré que la batalla sea justa y esperaré hasta que despierte.",
		},
		SPIDERDEN = "¡Aplástalas todas de donde salen!",
		SPIDEREGGSACK = "Podría espachurrar estos, pero me faltarían más para más batallas.",
		SPIDERGLAND = "Arrancada del abdomen de una araña muerta.",
		SPIDERHAT = "Una manera perfecta de infiltrarse en el campamento enemigo.",
		SPIDERQUEEN = "Por fin, una verdadera prueba de mis habilidades.",
		SPIDER_WARRIOR =
		{
			DEAD = "¡Victoria para Wigfrid una vez más!",
			GENERIC = "El campeón de las arañas. ¡A la batalla!",
			SLEEPING = "Es cobarde atacar a un enemigo dormido.",
		},
		SPOILED_FOOD = "El tiempo solo ha convertido esta comida en más asquerosa, no más sabia.",
		STATUEHARP = "Debe ser Gunnar. Las serpientes se llevaron su cabeza.",
		STATUEMAXWELL = "¡Qué vergüenza, demonio!",
		STINGER = "La espada en la parte trasera de una abeja.",
		STRAWHAT = "Un sombrero para refrescarse después de una batalla feroz.",
		STUFFEDEGGPLANT = "Rellenar la verdura no la convierte en carne.",
		SUNKBOAT = "No me extraña que se haya hundido. Ya no es un drakar.",
		SWEATERVEST = "Es un hermoso chaleco, pero no ofrece ninguna protección.",
		REFLECTIVEVEST = "¡Ja! El sol no es ningún guerrero si no puede penetrar esto.",
		HAWAIIANSHIRT = "Las flores no detendrán una lanza.",
		TAFFY = "Se contará durante mucho tiempo la historia de este caramelo.",
		TALLBIRD = "¡Un pájaro temible! Pero no tengo miedo.",
		TALLBIRDEGG = "Crecerá hasta convertirse en un enemigo formidable.",
		TALLBIRDEGG_COOKED = "Era o tú o yo, pájaro.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Este huevo no sobreviviría a un invierno nórdico.",
			GENERIC = "¡Lucha para salir, pájaro!",
			HOT = "¡Soporta el fuego! Al menos hasta que se cocina.",
			LONG = "Queda un poco antes de que nazca este pájaro.",
			SHORT = "Pronto despertará en este mundo.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Un guerrero emplumado se esconde dentro.",
			PICKED = "Una joven ave de guerra pronto nacerá.",
		},
		TEENBIRD =
		{
			GENERIC = "Todavía no estás listo para la batalla, ave.",
			HUNGRY = "Espero que te gusten las verduras... la carne es para mí.",
			STARVING = "Entablar batalla conmigo es cosa tuya, ave.",
		},
		TELEBASE =
		{
			VALID = "Aprovechará mi velocidad impresionante.",
			GEMS = "Requiere gemas moradas.",
		},
		GEMSOCKET = 
		{
			VALID = "¡Hora del espectáculo!",
			GEMS = "Le falta su gema.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "¡A Asgard!",
			GENERIC = "Un puente a otro mundo.",
			LOCKED = "El puente aún es inestable.",
			PARTIAL = "El puente está incompleto.",
		},
		TELEPORTATO_BOX = "Tal vez esto guarde el secreto del Bifröst de esta tierra.",
		TELEPORTATO_CRANK = "Una manivela resistente.",
		TELEPORTATO_POTATO = "No hay decencia. No es ni siquiera carne de metal.",
		TELEPORTATO_RING = "Parece similar al Bifröst.",
		TELESTAFF = "¡Paseo por el aire y el mar!",
		TENT = 
		{
			GENERIC = "Duerme esta noche y prepárate para la batalla a la mañana siguiente.",
			BURNT = "Ha sido destruida.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Un lugar para descansar mi cabeza cansada de la batalla.",
			BURNT = "Ha sido destruida.",
		},
		TENTACLE = "Parece feroz. ¡A la refriega!",
		TENTACLESPIKE = "Viscoso, pero peligroso. Me gusta.",
		TENTACLESPOTS = "Una piel resistente.",
		TENTACLE_PILLAR = "Un enemigo con un tentáculo imponente.",
		TENTACLE_PILLAR_ARM = "Un apéndice para agarrar asqueroso.",
		TENTACLE_GARDEN = "¡Embestiré con mi lanza contra esa masa de tentáculos!",
		TOPHAT = "No hace juego con mi traje.",
		TORCH = "Perfecta para un asalto nocturno.",
		TRANSISTOR = "Una maravilla de la ciencia.",
		TRAP = "Una trampa bien construida. Tendré mi comida.",
		TRAP_TEETH = "Una trampa traicionera.",
		TRAP_TEETH_MAXWELL = "Una maza excelente desperdiciada, enterrada en el suelo.",
		TREASURECHEST = 
		{
			GENERIC = "Un lugar para guardar mi yelmo y la lanza mientras descanso.",
			BURNT = "Sus paredes fueron derribadas por el fuego.",
		},
		TREASURECHEST_TRAP = "Siempre estoy lista.",
		TREECLUMP = "¡Un callejón sin salida! Debo ser valiente y luchar.",
		TRINKET_1 = "Los juguetes no le interesan a una gran guerrera como yo.",
		TRINKET_10 = "Un símbolo de la victoria.",
		TRINKET_11 = "Un guerrero dentro de una armadura fina.",
		TRINKET_12 = "Despojado de un monstruo horrible.",
		TRINKET_2 = "Acompañamiento de la canción de mis triunfos.",
		TRINKET_3 = "Ni siquiera mi lanza puede deshacer este nudo.",
		TRINKET_4 = "Un hombrecillo peculiar.",
		TRINKET_5 = "¿Me llevará a Asgard?",
		TRINKET_6 = "Tecnología inútil.",
		TRINKET_7 = "¡No hay tiempo para juegos! ¡Tenemos una batalla entre manos!",
		TRINKET_8 = "Sería una buena arma si fuera necesario.",
		TRINKET_9 = "Con esto no se puede hacer ninguna armadura decente.",
		TRUNKVEST_SUMMER = "No será suficiente en los páramos congelados.",
		TRUNKVEST_WINTER = "La piel caliente de una criatura vencida. Una prenda fina.",
		TRUNK_COOKED = "Una jugosa recompensa después de una dura batalla.",
		TRUNK_SUMMER = "Una poderosa trompa de un una bestia caída no muy peluda.",
		TRUNK_WINTER = "La poderosa trompa de un una bestia caída peluda.",
		TUMBLEWEED = "¡Huye, cobarde planta andante!",
		TURKEYDINNER = "Un verdadero banquete.",
		TWIGS = "Buenas para fabricar lanzas.",
		UMBRELLA = "Protección contra la lluvia hecho con el trofeo de una caza.",
		GRASS_UMBRELLA = "No me gustan las flores, pero menos me gustan las armaduras mojadas.",
		PALMLEAF_UMBRELLA = "No me gustan las plantas, pero menos aún me gustan las armaduras mojadas.",
		UNIMPLEMENTED = "Una misteriosa reliquia, seguro que contiene un gran poder.",
		WAFFLES = "¡Los gofres no sirven para prepararse para la batalla!",
		WALL_HAY = 
		{	
			GENERIC = "Un pequeño elemento disuasivo para los atacantes.",
			BURNT = "Esto no bastará.",
		},
		WALL_HAY_ITEM = "Tal vez mis enemigos se perderán en este heno.",
		WALL_STONE = "Mis enemigos se aplastarán contra estas rocas.",
		WALL_STONE_ITEM = "Una pared sólida hecha con el suelo.",
		WALL_RUINS = "Casi impenetrable.",
		WALL_RUINS_ITEM = "Solo las mejores barreras para mi fuerte.",
		WALL_WOOD = 
		{
			GENERIC = "Puede empalar un enemigo.",
			BURNT = "¡Fuego, la madera se debilita!",
		},
		WALL_WOOD_ITEM = "Una fortificación mediocre.",
		WALRUS = "Esos colmillos podrían perforar incluso la mejor armadura.",
		WALRUSHAT = "¡Alta suciedad!",
		WALRUS_CAMP =
		{
			EMPTY = "Han partido para un gran viaje.",
			GENERIC = "Un campamento de invierno como es debido.",
		},
		WALRUS_TUSK = "Arrancado de la boca de la bestia marina.",
		WARG = "¿Eres tú, Fenrir?",
		WASPHIVE = "¡Abejas de la guerra!",
		WATERMELON = "Hace un buen sonido cuando la golpeas.",
		WATERMELON_COOKED = "Cálida y roja, pero no fluye.",
		WATERMELONHAT = "Es casi como llevar un pellejo.",
		WETGOOP = "Porquería.",
		WINTERHAT = "Caliente, pero no apto para el combate.",
		WINTEROMETER = 
		{
			GENERIC = "Ojalá midiera el calor de la batalla.",
			BURNT = "El dispositivo de medición ha sido asesinado por Loge.",
		},
		WORMHOLE =
		{
			GENERIC = "¿Se traga a aquellos caídos en batalla?",
			OPEN = "Sus fauces me dan la bienvenida.",
		},
		WORMHOLE_LIMITED = "Es enfermizo y débil.",
		ACCOMPLISHMENT_SHRINE = "¡Mis victorias se recordarán!",        
		LIVINGTREE = "Un árbol de la vida, pero no es Yggdrasil.",
		ICESTAFF = "¡Un regalo de Ullr!",
		WATHGRITHRHAT = "El poder del unicornio es grande.",
		SPEAR_WATHGRITHR = "¡Mi compañero de armas!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		BACONEGGS = "¡Cerdo y huevos!",
		BANANAPOP = "¡He encontrado una manera de que sea AÚN menos atractivo!",
		BISQUE = "No está mal el plato.",
		CEVICHE = "Demasiado elaborado para mi gusto, pero valdrá.",
		SEAFOODGUMBO = "Una comida digna de una reina.",
		SURFNTURF = "¡Puaj! ¡Suelo!",
		SHARKFINSOUP = "¡Delicioso!",
		LOBSTERDINNER = "He triunfado sobre mi enemigo langüosta.",
		LOBSTERBISQUE = "Esto ya me gusta más.",
		JELLYOPOP = "¡Podría volverme loco con estos!",
		CALIFORNIAROLL = "Es solo un bocado de pescado cocido.",

		AERODYNAMICHAT = "¡Mi cabeza cortará el aire!",
		ANTIVENOM = "¡Ningún veneno correrá por mis venas!",
		ARMOR_LIFEJACKET = "¡La aventura no ofrece ninguna verdadera seguridad!",
		ARMOR_SNAKESKIN = "¡La lluvia es derrotada!",
		ARMOR_WINDBREAKER = "¡Romperé el viento con cada paso!",
		ARMORLIMESTONE = "Su influencia es reconfortante en mis huesos.",
		ARMOROBSIDIAN = "¡Venid a mí ahora, demonios!",
		ARMORSEASHELL = "¡Si llevo esto, no apareceré en las costas de Valhalla!",
		ARMOUREDBOAT = "¡Esto sí que es un barco apropiado para un vikingo!",
		BABYOX = "Qué carne tan bonita.",
		BALLPHIN = "Un golpe simplemente podría rebotar.",
		BALLPHINPOD = "¡Un grupo de asalto!",
		BAMBOO = "Palos de gran versatilidad.",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "¿Es esto un juguete de Loki?",
		BIOLUMINESCENCE = "¿Qué clase de magia es esta?",
		BLOWDART_POISON = "Demasiado débil desde la distancia. Odín, perdóname...",
		BOAT_INDICATOR = "I shall launch my craft.",
		BOAT_LANTERN = "¡Contempladme, bestias inmundas de los sombríos mares!",
		BOATCANNON = "¿¡Golpea a los enemigos por mí!?",
		BOATREPAIRKIT = "El cargamento más sensato.",
		BOTTLELANTERN = "Una antorcha muy curiosa.",
		BURIEDTREASURE = "Que la suerte me sonría este día.",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "¡El sonido y la furia!",
		CAPTAINHAT = "Sería mejor con cuernos.",
		CARGOBOAT = "Un barco apropiado para un largo viaje.",
		CHIMINEA = "¿Qué tipo de fuego se esconde en un agujero?",
		CIRCLINGSEAGULL = "¡Las ratas del aire!",
		CLOTHSAIL = "Una buena vela.",
		COCONADE = "Fire that can be thrown.",
		COCONUT = 
		{
		    GENERIC = "El más duro de los frutos.",
		    PLANTED = "El fruto duro ha dado paso a un árbol enclenque.",
		},
		COFFEE = "Amargo y energizante.",
		COFFEEBEANS = "A mí me gusta el café solo.",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "El mar da ofrendas extrañas como estas.",
		CORALREEF = "Un lugar duro y quebradizo. Me gusta.",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "¿Le has conducido la vergüenza a este agujero?",
		CUTLASS = "Oh, gran espada de muerte marina. Te blandiré con honor.",
		DEAD_SWORDFISH = "Hacia Valhalla, pez valiente.",
		DEPLETED_BAMBOOTREE = "Ten algo de respeto por ti mismo.",
		DEPLETED_BUSH_VINE = "Ahora yo no tienes tantas viñas, ¿no?",
		DOYDOY = "¡No muestra rastro de temor para mí!",
		DOYDOYBABY = "Te honro, joven guerrero de los DoyDoys.",
		DOYDOYEGG = "Dentro de este huevo crece un vikingo de otro plumaje.",
		
		DOYDOYFEATHER = "La preciada pluma de un pájaro guerrero caído.",
		DOYDOYNEST = "¡El nido donde se incubarán más valientes!",
		DUBLOON = "¡Los botines de los caídos!",
		DUG_BAMBOOTREE = "Si te planto, ¿me lo pagarás?",
		DUG_BERRYBUSH2 = "¡Mi propia fuente personal de bayas!",
		DUG_BUSH_VINE = "¿Beber o no beber?",
		DUG_COFFEEBUSH = "Café para llevar.",
		EARRING = "No es de mi oreja.",
		FABRIC = "Coser no es trabajo para guerreros...",
		FEATHERSAIL = "¡Los pájaros valientes me regalan sus ágiles plumas!",
		FIRERAIN = "¡El verdadero tiempo de los guerreros!",
		FIRERAINSHADOW = "¡Por Odín!",
		FISHINHOLE = "¿Queréis rendiros, pececitos?",
		FROG_POISON = "¡Atrás, inmundo demonio reptiliano!",
		GASHAT = "¡Una especie de armadura para mi nariz y garganta!",
		GOLDENMACHETE = "Te blandiré con orgullo.",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "¡Este artilugio funciona en corceles de Odín!",
		JELLYFISH = "Eres demasiado pequeño para ser un monstruo marino.",
		JELLYFISH_COOKED = "¡El monstruo del mar está bueno!",
		JELLYFISH_DEAD = "¡El monstruo marino lleva a Valhalla!",
		JELLYFISH_PLANTED = "Esperaba que los monstruos marinos fuesen más grandes.",
		JELLYJERKY = "Mis dientes lucharán contigo.",
		JUNGLETREE = "A mighty tree!",
		JUNGLETREE_BURNT = "Adiós, gigante.",
		JUNGLETREE_STUMP = "Te veo en Valhalla, árbol.",
		JUNGLETREESEED =
        {
            GENERIC = "La fuerza del árbol en una semilla.",
            PLANTED = "Crecerá poderoso.",
        },
		LAVAPOOL = "¡Un charco de fuego!",
		LIMESTONE = "Dura como una fruta inmadura.",
		LIMPETS = "¡Carne de roca!",
		
		LOBSTER = "Estás vestido para la batalla, habitante del mar.",
		LOBSTERHOLE = "Las criaturas blindadas viven aquí...",
		LOGRAFT = "No me llevarás lejos, pero me llevarás.",
		MACHETE = "Una espada de buena longitud.",
		MESSAGEBOTTLE = "¿Un mensaje de Valhalla?",
		MESSAGEBOTTLEEMPTY = "Sin un mensaje y sin bebida. Una lástima.",
		MOSQUITO_POISON = "¡Veneno! ¡La obra de un cobarde!",
		MUSSEL = "No pareces fuerte.",
		MUSSEL_STICK = "Los bobos mejillones subirán por este palo.",
		OBSIDIAN = "¡Guijarros de la montaña de fuego!",
		OBSIDIAN_WORKBENCH = "¡Fragua de fuego!",
		OBSIDIANAXE = "¡ESTO es un hacha!",
		OBSIDIANCOCONADE = "Lanzar fuego es de cobardes. ¡Pero es divertido!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Este fuego está casi muerto.",
			GENERIC = "¡Un fuego digno de un vikingo!",
			HIGH = "¡El fuego ruge!",
			LOW = "El fuego está muriendo lentamente.",
			NORMAL = "Fuego caliente, Wigfrid caliente.",
			OUT = "Y la luz se apaga.",
		},
		OBSIDIANMACHETE = "Una herramienta para cortar. Una herramienta para quemar.",
		SPEAR_OBSIDIAN = "Siente la quemadura.",
		OBSIDIANSPEARGUN = "Normalmente prefiero incendiar de cerca.",
		OX = "¡Alaba al mismo Odín por este abundante festín con pezuñas!",
		PACKIM = "¿Me seguirás a Valhalla?",
		PACKIM_FISHBONE = "Un curioso adorno.",
		PALMLEAF = "¡Una hoja del tamaño de un vikingo!",
		PALMTREE =
		{
			BURNING = "¡La madera está ardiendo!",
			BURNT = "Se lo ha llevado Loge.",
			CHOPPED = "¡Talado por el guerrero de los bosques!",
			GENERIC = "¿Abandonas las ramas, árbol?",
		},
		PALMTREE_BURNT = "Huelo a coco quemado.",
		PALMTREE_STUMP = "Alimentarás mi corazón en Valhalla.",
		PARROT = "¡Cuidado con lo que dices, pájaro!",
		PEACOCK = "Sería una lástima arruinar esas plumas, carne.",
		PIRATEHAT = "Este sombrero confunde mi personaje... quiero decir, mi alma.",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "¡La tierra eructa enferma!",
		RAFT = "¡Un vikingo no teme mojarse!",
		ROWBOAT = "Llevo remar en la sangre.",
		SAIL = "Una vela curiosa, pero valdrá.",
		SAND = "Eres una tierra muy limpia.",
		SAND_CASTLE = "A scale model of my future keep.",
		SANDBAG = "Arena en saco.",
		SANDBAG_ITEM = "Mantiene las mareas a raya.",
		SANDHILL = "No haré una montaña con un montículo.",
		SEAGULL = "¡Vil ave!",
		SEAGULL_WATER = "¡Ensucias el agua sobre la que flotas!",
		SEASACK = "Asqueroso, pero útil a su manera.",
		SEASHELL = "La moneda del mar.",
		SEASHELL_BEACHED = "¿Un pequeño escudo elfo?",
		SEATRAP = "¡Me trae el botín del mar!",
		SEAWEED = "¡Asquerosa hierba acuosa!",
		
		SEAWEED_PLANTED = "Una maleza que no puedo aplastar con mi bota.",
		SHARK_FIN = "Un recuerdo de un guerrero caído.",
		SHARX = "¡Ah, un digno oponente marino!",
		SLOTMACHINE = "Una máquina de destino y miseria.",
		SNAKE = "Nunca confíes en quien se arrastre.",
		SNAKE_FIRE = "¡Hablan con la boca del volcán!",
		SNAKE_POISON = "¡Aparta tus asquerosos colmillos de mi piel!",
		SNAKESKIN = "Una serpiente ha mudado su piel. Con un poco de ayuda...",
		SNAKESKINHAT = "¿Debería llevar puesta una serpiente?",
		SOLOFISH = "Parece que el mar me está ofreciendo un festín.",
		SPEAR_POISON = "Esta lanza concede una victoria de cobardes.",
		SPEARGUN = "El arma de un cobarde.",
		SPEARGUN_POISON = "¡No soy ninguna ratera escondiéndose entre las sombras! ¿O sí?",
		SPOILED_FISH = "Hueles a tu fracaso.",
		STUNGRAY = "¿Es que no tenéis honor, apestosos?",
		SUPERTELESCOPE = "¡Odín me ha prestado su ojo!",
		SWORDFISH = "¡Ahora eres un pez que va tras mi corazón!",
		TELESCOPE = "¿Qué engaño es este?",
		TIGERSHARK = "¡Llévame a Valhalla, diablo del mar!",
		TIGERSHARKSHADOW = "¡La sombra de la bestia!",
		TORNADO = "¡El viento ha adoptado una forma furiosa!",
		TOUCAN = "¡Lucha conmigo, pájaro de nariz larga! ¡Y cenaremos juntos en Valhalla!",
		TRAWLNET = "¡Saquearé el mar!",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "¡Un arma digna para un dios!",
		TRINKET_13 = "¿Qué clase de aguamiel asquerosa es esta?",
		TRINKET_14 = "El juguete de un bebé. ¿O no?",
		TRINKET_15 = "Un arma para incordiar.",
		TRINKET_16 = "¿Una pieza de armadura?",
		TRINKET_17 = "Un guerrero camina hacia Valhalla descalzo...",
		TRINKET_18 = "No reconozco esta artesanía.",
		TRINKET_19 = "Siempre hay cielos despejados para un guerrero justo.",
		TURBINE_BLADES = "¿Qué tipo de espada extraña es esta?",
		TURF_BEACH = "Me gusta esta sensación bajo mis pies.",
		TURF_JUNGLE = "Aquí es muy fácil perderse...",
		TWISTER = "¡Te escondes debajo del viento, villano!",
		VENOMGLAND = "La fuente de la fiebre.",
		VINE = "¿Qué puedes hacer por mí?",
		VOLCANO = "¡Una montaña de fuego!",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "Destrucción sin sentido de una fragua de armas...",
		VOLCANO_EXIT = "Me he cansado de este reino infernal.",
		VOLCANOSTAFF = "¡Invoca la ira de la montaña de fuego!",
		WALL_LIMESTONE = "Una buena pieza.",
		WALL_LIMESTONE_ITEM = "¿Aguantarás por mí?",
		WHALE_BLUE = "¡Acabaré con tu tristeza, gigante!",
		WHALE_CARCASS_BLUE = "Brindaré por ti en Valhalla.",
		WHALE_CARCASS_WHITE = "Oh, cómo apestan los poderosos.",
		WHALE_WHITE = "Sería un honor matarte.",
		NEEDLESPEAR = "¡Es sin duda una maravillosa lanza de guerra!",
		ARMORCACTUS = "Así me haré amiga del cactus.",
		BAMBOOTREE =
		{
			BURNT = "Tu brujería simple no podría salvarme del fuego.",
			CHOPPED = "¡Qué corte!",
			GENERIC = "¿Qué brujería es esta? ¿Madera hueca?",
		},
		BLOWDART_FLUP = "El arma de un cobarde, soltada por una criatura despreciable y furtiva.",
		BLUBBER = "¡Esto es muy preciado para mi gente!",
		BLUBBERSUIT = "¡Lamenta mi traje de grasa!",
		BOAT_TORCH = "¡El mar nocturno está encendido!",
		BRAINJELLYHAT = "¡Mi cerebro tiene el poder de mi espada!",
		BUOY = "Me levanta el ánimo verla a flote.",
		BUSH_VINE =
		{
			BURNT = "Está quemado. No hace falta darle más vueltas.",
			CHOPPED = "Necesitaba un corte de pelo.",
			GENERIC = "Este arbusto está despeinado.",
		},
		COCONADE =
		{
			BURNING = "¡El fruto arrojará pronto su fuego!",
			GENERIC = "¡Este fruto no es ordinario!",
		},
		COCONUT_COOKED = "Me daré un festín con este fruto grande.",
		COCONUT_HALVED = "¡He partido el fruto en dos y me ha enseñado su interior!",
		COFFEEBEANS_COOKED = "Huele vigorizante.",
		COFFEEBUSH =
		{
			BARREN = "¿Fuiste capaz al menos de luchar?",
			GENERIC = "Tiene extrañas frutas de volcán.",
			PICKED = "Sus frutos deben renacer.",
			WITHERED = "¡Arbusto debilucho!",
		},
		CORAL_BRAIN = "Si me lo como, ¿adquiriré su sabiduría?",
		CORAL_BRAIN_ROCK = "¡Una roca mística de agua omnisciente!",
		CRAB =
		{
			GENERIC = "¡Lucha conmigo, criatura blindada!",
			HIDDEN = "¡Desentiérrate, cobarde!",
		},
		CRATE = "¡Enseña tus secretos, caja!",
		DOUBLE_UMBRELLAHAT = "¿Qué tipo de casco extraño es este?",
		DOYDOYEGG_COOKED = "Comeré del botín de este pájaro intrépido.",
		DOYDOYEGG_CRACKED = "Su audacia sale.",
		DRAGOON = "¡Un compañero bersérker cuyo vientre está lleno de fuego!",
		DRAGOONDEN = "Un berserker tiene que vivir en algún lugar.",
		DRAGOONEGG = "¡Puedo oír el corazón de un guerrero latiendo dentro!",
		DRAGOONHEART = "¡Mi enemigo caído me ha dado un regalo!",
		DRAGOONSPIT = "Ojalá pudiera escupir fuego...",
		DUG_ELEPHANTCACTUS = "Iré al grano: ahora me perteneces.",
		ELEPHANTCACTUS = "Percibo el espíritu de un berserker dentro de ti, planta.",
		ELEPHANTCACTUS_ACTIVE = "¡Finalmente brota de la tierra un digno adversario!",
		ELEPHANTCACTUS_STUMP = "¡Cobarde!",
		FISH_RAW = "Esta carne de mar me saciará.",
		FISH_RAW_SMALL = "Esta carne de mar me saciará.",
		FISH_RAW_SMALL_COOKED = "¡Esta carne nadará en mi barriga!",
		FLAMEGEYSER = "¡La tierra eructa fuego!",
		FLOTSAM = "Debo pescarlo del mar si quiero aprender sus secretos.",
		FLUP = "¡Cobarde criatura que acecha en el barro!",
		FRESHFRUITCREPES = "¡Tan ligeros y etéreos!",
		GRASS_WATER = "¡Hierba que puedo coger desde mi drakar!",
		HAIL_ICE = "¡El cielo está lanzando hielo!",
		HOME = "Alguien debe de vivir aquí.",
		ICEMAKER =
		{
			HIGH = "¡La máquina echa humo!",
			LOW = "Está escupiendo considerablemente menos hielo.",
			NORMAL = "¡Hielo del fuego!",
			OUT = "¡Necesita más fuego!",
			VERYLOW = "Se le va a acabar el fuego.",
		},
		JUNGLETREE =
		{
			BURNING = "El árbol se quema.",
			BURNT = "El árbol ya no existe.",
			CHOPPED = "Un árbol fuerte, pero no tan fuerte como mi hacha.",
			GENERIC = "No hay árboles como este de donde vengo.",
		},
		KNIGHTBOAT = "¡Mi drakar me conduce a la guerra!",
		KRAKEN = "¡Yo misma te devolveré al infierno!",
		KRAKENCHEST = "¡Botines de guerra!",
		KRAKEN_TENTACLE = "¡El brazo de la bestia!",
		LIMPETROCK =
		{
			GENERIC = "¡La piedra de carne!",
			PICKED = "La piedra ahora no tiene carne...",
		},
		TREEGUARD = "¡A las armas!",
		LIVINGJUNGLETREE = "¡No me gusta tu cara, árbol!",
		LOBSTER_DEAD = "Duerme en Valhalla, criatura blindada.",
		LOBSTER_DEAD_COOKED = "Tu armadura esconde una comida sabrosa.",
		LUGGAGECHEST = "¡Espero recoger los botines del mar!",
		MAGIC_SEAL = "Blandiré esto con el debido respeto para el poderoso guerrero que lo llevaba.",
		MAGMAROCK = "¿Qué puedo usar para hacer rodar estas rocas?",
		MAGMAROCK_FULL = "¿Qué puedo usar para hacer rodar estas rocas?",
		MAGMAROCK_GOLD = "Brilla...",
		MAGMAROCK_GOLD_FULL = "Brilla...",
		MANGROVETREE = "¡Nunca antes había talado un árbol desde mi drakar!",
		MANGROVETREE_BURNT = "Todo sobre el agua está chamuscado.",
		MARSH_PLANT_TROPICAL = "Una pobre planta.",
		MERMFISHER = "No discuto con los pescadores, siempre y cuando no cojan las armas.",
		MERMHOUSE_FISHER = "Los pescadores habitan aquí.",
		MONKEYBALL = "Un árbol de diversión para monos.",
		MONSTERTARTARE = "Todavía está temblando.",
		MOSQUITOSACK_YELLOW = "El bicho ha soltado su saco de peste.",
		MUSSELBOUILLABAISE = "No muy espesa, pero calienta.",
		MUSSEL_COOKED = "Un sabor fuerte.",
		MUSSEL_FARM =
		{
			GENERIC = "Fabrica mejillones.",
			STICKPLANTED = "Únete al palo...",
		},
		MYSTERYMEAT = "La comida de los niños de mi enemigo es... ¿qué para mí?",
		OCTOPUSCHEST = "El cofre contiene ofrendas.",
		OCTOPUSKING = "Parece abierto a negociar.",
		OXHAT = "Este casco mantendrá seco mi cuero cabelludo.",
		OX_FLUTE = "No tengo ritmo...",
		OX_HORN = "¡Ah, qué jarra más buena sería!",
		PALMLEAF_HUT = "Impide que la lluvia me moje el casco.",
		PARROT_PIRATE = "¡Hablas demasiado!",
		PEG_LEG = "¡Esta pata será un buen mortero!",
		PIGTENT = "¡Huele a desayuno!",
		PIKE_SKULL = "Me recuerda a mi hogar.",
		PIRATEGHOST = "¡Al infierno, espíritu!",
		PIRATEPACK = "Desarrolla los pectorales.",
		PIRATIHATITATOR =
		{
			BURNT = "Su magia ha flotado como brasas.",
			GENERIC = "¿Qué brujería extraña es esta?",
		},
		PORTAL_SHIPWRECKED = "Este drakar parece impropio para un guerrero.",
		PRIMEAPE = "Eres tan divertido como peludo.",
		PRIMEAPEBARREL = "Por como está esto de sucio diría que aquí vive un vikingo.",
		RAWLING = "¡Por fin! Alguien con quien entrenar.",
		REDBARREL = "¡Esta barrica pega fuerte!",
		ROCK_CHARCOAL = "¿Las rocas arden?",
		ROCK_OBSIDIAN = "¡Una piedra de lava!",
		SAIL_STICK = "¡Ordeno al viento!",
		SANDBAGSMALL = "¡Esa bolsa de arena lucha contra el agua!",
		SANDBAGSMALL_ITEM = "¡El agua se choca contra él débilmente!",
		SAND_CASTLE =
		{
			GENERIC = "¡Quiero fingir que soy una giganta y aplastarlo!",
			SAND = "El tiempo lo ha aplastado.",
		},
		SEAWEED_COOKED = "Aperitivo marino.",
		SEAWEED_DRIED = "Es masticable...",
		SHADOWSKITTISH_WATER = "¡Un enemigo acecha!",
		SHARKITTEN = "A quien quiero es a tu mamá...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "¡Algo acecha a la espera!",
			INACTIVE = "Sólo arena... por ahora...",
		},
		SHARK_GILLS = "¡Agallas de tiburón!",
		SHARK_TEETHHAT = "¡Un casco para mi corazón guerrero!",
		SHIPWRECKED_ENTRANCE = "¡Una nueva tierra para saquear y desvalijar!",
		SHIPWRECKED_EXIT = "Hacia una nueva tierra...",
		SNAKEDEN =
		{
			BURNT = "Está quemado. No hace falta darle más vueltas.",
			CHOPPED = "Necesitaba un corte de pelo.",
			GENERIC = "Este arbusto está despeinado.",
		},
		SNAKEOIL = "¿Qué poderosas propiedades otorga esto?",
		SNAKESKINSAIL = "¡Una vela hecha con un asesinato!",
		SPEAR_LAUNCHER = "¡Un regalo de Odín!",
		SUNKEN_BOAT =
		{
			ABANDONED = "¡El mar reclama otro!",
			GENERIC = "¡Tiene algo que decir!",
		},
		SUNKEN_BOAT_BURNT = "Un funeral vikingo ha tenido lugar...",
		SUNKEN_BOAT_TRINKET_1 = "¿Algún tipo de arma tosca?", 
		SUNKEN_BOAT_TRINKET_2 = "El drakar de un niño.", 
		SUNKEN_BOAT_TRINKET_3 = "Vela empapada.", 
		SUNKEN_BOAT_TRINKET_4 = "Brujería marina.", 
		SUNKEN_BOAT_TRINKET_5 = "No es de mi tamaño.",
		SWEETPOTATOSOUFFLE = "¡Está lleno de aire delicioso!",
		SWEET_POTATO = "¡Nunca he oído hablar de una patata tan dulce...! ¡Qué asco!",
		SWEET_POTATO_COOKED = "No me lo comeré, pero aprecio su color.",
		SWEET_POTATO_PLANTED = "¡Hay plantas no comestibles en la tierra!",
		SWEET_POTATO_SEEDS = "Crecerán dulcemente.",
		SWIMMINGHORROR = "¿Estás aquí para darme un funeral vikingo?",
		TELEPORTATO_SW_BASE = "Le faltan cosas.",
		TELEPORTATO_SW_BOX = "Es parte de algo.",
		TELEPORTATO_SW_CRANK = "Una manivela. ¿Pero de qué?",
		TELEPORTATO_SW_POTATO = "¿Qué artilugio extraño es este?",
		TELEPORTATO_SW_RING = "¿Es valioso?",
		THATCHPACK = "Espero que mi lanza no le haga un agujero.",
		TIDALPOOL = "¡Un lago diminuto!",
		TIDAL_PLANT = "Planta empapada.",
		TIGEREYE = "¡Tengo la vista del tiburón tigre!",
		TRAWLNETDROPPED =
		{
			GENERIC = "¡Qué gran redada!",
			SOON = "El botín se hundirá pronto.",
			SOONISH = "Creo que mi botín se hundirá pronto.",
		},
		TRINKET_20 = "¿Algún tipo de arma tosca?", 
		TRINKET_21 = "El drakar de un niño.",
		TRINKET_22 = "Vela empapada.", 
		TRINKET_23 = "Una cosa rota.", 
		TROPICAL_FISH = "¡En su interior es del color de la carne!",
		TUNACAN = "¡Comida que puede durar en un viaje!",
		TURF_SANDY = "Una pieza del campo de batalla.",
		TURF_ASH = "Una pieza del campo de batalla.",
		TURF_BADLANDS = "Una pieza del campo de batalla.",
		TURF_DECIDUOUS = "Una pieza del campo de batalla.",
		TURF_DESERTDIRT = "Una pieza del campo de batalla.",
		TURF_FUNGUS_GREEN = "Una pieza del campo de batalla.",
		TURF_FUNGUS_RED = "Una pieza del campo de batalla.",
		TURF_MAGMAFIELD = "Una pieza del campo de batalla.",
		TURF_MEADOW = "Una pieza del campo de batalla.",
		TURF_SNAKESKINFLOOR = "¡La piel de mi enemigo sienta bien debajo de mis pies!",
		TURF_SWAMP = "Una pieza del campo de batalla.",
		TURF_TIDALMARSH = "Una pieza del campo de batalla.",
		TURF_VOLCANO = "Una pieza del campo de batalla.",
		TWISTER_SEAL = "¿¡Tú eras el pequeño que estaba haciendo todos esos soplidos!?",
		VOLCANO_ALTAR =
		{
			GENERIC = "El altar de los dioses de fuego duerme.",
			OPEN = "¡Está listo para recibir el sacrificio!",
		},
		VOLCANO_ALTAR_TOWER = "¡Un altar a los dioses del fuego!",
		VOLCANO_SHRUB = "Pareces quemado.",
		WALLYINTRO_DEBRIS = "¿Son estos los restos de mi drakar?",
		WATERMELON_SEEDS = "Semillas.",
		WATERYGRAVE = "¡Botín en las profundidades!",
		WHALE_BUBBLES = "Algo acecha debajo.",
		WHALE_TRACK = "¡Te encontraré, ballena!",
		WILBUR_CROWN = "¿Qué será este botín?",
		WILBUR_UNLOCK = "¡No me arrodillo ante ningún rey, ni siquiera los adorables!",
		WILDBORE = "¡Noto un alma gemela!",
		WILDBOREHEAD = "Guarda una jarra en Valhalla para mí.",
		WILDBOREHOUSE = "¡Un terrible lugar para vivir!",
		WIND_CONCH = "Noto una brisa...",
		WOODLEGS_CAGE = "¡Una jaula cerrada!",
		WOODLEGS_KEY1 = "¿Qué podría abrir esto?",
		WOODLEGS_KEY2 = "¡Otra llave!",
		WOODLEGS_KEY3 = "¡Una llave extraña!",
		WRECK = "Los drakars pueblan el camino a Valhalla.",
	},
	DESCRIBE_GENERIC = "Es un artefacto de este reino.",
	DESCRIBE_TOODARK = "Demasiado oscuro incluso para la batalla.",
	DESCRIBE_SMOLDERING = "Las llamas lo consumirán pronto.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "¡La carne más fresca de todas!",
	},
}
