return {

	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "Já tem uma forma melhor que a minha.",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "Prefiro ser coberta pela noite a isso.",
			GENERIC = "Não vou chegar perto disso com uma navalha.",
			NOBITS = "Ela já perdeu tudo.",
		},
		WRITE =
        {
            GENERIC = "N-Não posso.",
        },
		STORE =
		{
			GENERIC = "Não caberia.",
			NOTALLOWED = "Preciso me lembrar das boas maneiras.",
		},
		RUMMAGE =
        {   
            GENERIC = "Tudo na vida precisa ser difícil?", 
        },
        CHANGEIN =
        {
            GENERIC = "Pra quê?",
            BURNING = "Acho que não vou mudar de novo tão logo.",
        },
		COOK =
        {
            GENERIC = "Oh. Ninguém nunca me ensinou a cozinhar.",
            TOOFAR = "Tão perto... tão longe...",
        },
        GIVE =
        {
            DEAD = "Eles não têm necessidade de posses materiais para onde foram.",
            SLEEPING = "Vou voltar mais tarde...",
            BUSY = "Está muito ocupado para prestar atenção em mim...",
        },
        TEACH =
        {
            KNOWN = "Já possuo esse conhecimento...",
            CANTLEARN = "Esse conhecimento está além das minhas capacidades...",
        },
	},
	ACTIONFAIL_GENERIC = "Não consigo fazer nada certo.",
	ANNOUNCE_MAGIC_FAIL = "Não está fazendo nada. Tsc.",
	ANNOUNCE_ADVENTUREFAIL = "Nem todas as mortes são semelhantes.",
	ANNOUNCE_BOOMERANG = "Oh! Isso foi carma.",
	ANNOUNCE_CHARLIE = "Demônio! Apareça!",
	ANNOUNCE_CHARLIE_ATTACK = "Fui atacada!",
	ANNOUNCE_COLD = "Estou tremendo até os ossos.",
	ANNOUNCE_HOT = "Estou com um calor lastimável.",
	ANNOUNCE_WORMS = "Uh-oh. Acho que devo ir embora.",
	ANNOUNCE_CRAFTING_FAIL = "Não disponho dos materiais necessários.",
	ANNOUNCE_DUSK = "A escuridão logo chegará. Devo me preparar.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Hmm!",
		PAINFUL = "Isso não era comestível.",
		SPOILED = "Essa comida está chegando ao fim de sua vida útil.",
		STALE = "Isso estava velho?",
		INVALID = "Eu nunca...",
		YUCKY = "Tenho medo de consumir isso.",
	},
	ANNOUNCE_ENTER_DARK = "A escuridão me engoliu.",
	ANNOUNCE_ENTER_LIGHT = "E fez-se a luz!",
	ANNOUNCE_HOUNDS = "Os cães estão uivando.",
	ANNOUNCE_HUNGRY = "Estou cheia de vazio.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Sinto a presença da fera por perto.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Essa trilha não leva a lugar algum.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Sem rastros, só um monte de estrume.",
	ANNOUNCE_INV_FULL = "Não posso carregar mais.",
	ANNOUNCE_KNOCKEDOUT = "Ainda assim, novamente acordo para a vida. Humpf.",
	ANNOUNCE_NOHUNGERSLEEP = "Meu estômago está tão vazio quanto meu coração. Não posso dormir agora.",
	ANNOUNCE_PECKED = "Você está testando minha paciência.",
	ANNOUNCE_QUAKE = "O solo treme. Será que ele vai me engolir inteiro?",
	ANNOUNCE_THORNS = "Ai! Cutuca, como eu.",
	ANNOUNCE_TORCH_OUT = "A escuridão voltou!",
	ANNOUNCE_FAN_OUT = "O leque deu seu último suspiro.",
    ANNOUNCE_COMPASS_OUT = "Não mais sente a força da Terra.",
	ANNOUNCE_TRAP_WENT_OFF = "Oh, céus!",
	ANNOUNCE_WORMHOLE = "Chego a este mundo mais uma vez.",
	ANNOUNCE_CANFIX = "\nDiferente do meu coração, isso poderia ser consertado.",
	ANNOUNCE_ACCOMPLISHMENT = "Tudo isso é passageiro.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Isso também será esquecido, algum dia.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Poderia colocar um pouco mais.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Tão perto da morte, mas ao mesmo tempo, tão longe.",
	ANNOUNCE_BEES = "Abelhas! Talvez eu seja alérgica!",
	ANNOUNCE_DEERCLOPS = "Talvez seja ruim.",
	ANNOUNCE_FREEDOM = "Liberdade. Ótimo.",
	ANNOUNCE_HIGHRESEARCH = "Eu vi o vazio e é profundo e sombrio.",
	ANNOUNCE_LOWRESEARCH = "Conhecimento patético...",
	ANNOUNCE_MOSQUITOS = "Mosquitos! Se banqueteiem em minhas veias!",
	ANNOUNCE_NODANGERSLEEP = "Não consigo dormir, preciso de mortes.",
	ANNOUNCE_NODAYSLEEP = "O sol me incomoda. Eu não conseguiria dormir.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Ainda não estou cansada.",
	ANNOUNCE_NOSLEEPONFIRE = "Essa seria uma ótima forma de morrer.",
	ANNOUNCE_NODANGERSIESTA = "Eu não poderia cochilar. A morte se aproxima.",
	ANNOUNCE_NONIGHTSIESTA = "Prefiro mesmo ficar em uma barraca.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Prefiro mesmo ficar em uma barraca.",
	ANNOUNCE_NOHUNGERSIESTA = "Meu estômago está tão vazio quanto meu coração. Não posso cochilar agora.",
	ANNOUNCE_SHELTER = "A natureza serve para alguma coisa, afinal de contas.",
	ANNOUNCE_BURNT = "Ai! Fogos do inferno!",
	ANNOUNCE_TOOL_SLIP = "Tudo bem, eu não precisava mesmo.",
	ANNOUNCE_DAMP = "Mole e triste.",
	ANNOUNCE_WET = "Ainda mais úmido quando choro até dormir.",
	ANNOUNCE_WETTER = "Uma eternidade de umidade e mágoa.",
	ANNOUNCE_SOAKED = "Um real apocalipse de água.",

	ANNOUNCE_OTHER_WORLD_PLANT = "Aqui não é seu lugar. Como eu.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Todas as coisas desaparecem, com o tempo...",
	},
	ANNOUNCE_BOAT_DAMAGED = "Essa embarcação está avariada. Me identifico.",
	ANNOUNCE_BOAT_SINKING = "Em breve enfrentarei uma sepultura aquosa.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Me rendo às profundezas!",
	ANNOUNCE_CRAB_ESCAPE = "Iludiu a morte mais um dia.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Observe enquanto navego direto para a boca da morte!",
	ANNOUNCE_MAPWRAP_RETURN = "Retorno mais uma vez para este mundo.",
	ANNOUNCE_MAPWRAP_WARN = "Talvez navegarei da extremidade da Terra.",
	ANNOUNCE_TREASURE = "Um mapa do tesouro... Que empolgante!",
	ANNOUNCE_MORETREASURE = "Outro mapa... Menos empolgante!",
	ANNOUNCE_NO_TRAP = "Alguma coisa finalmente deu certo.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Esse é um guia de uma terra distante.",
	ANNOUNCE_RESEARCH = "Agora possuo grande conhecimento deste mundo terrível.",
	ANNOUNCE_SHARX = "Estou sendo perseguido por patifes!",
	ANNOUNCE_TRAWL_FULL = "O mar oferece sua recompensa.",
	ANNOUNCE_UNIMPLEMENTED = "Oh! Acho que precisa de mais tempo.",
	ANNOUNCE_VOLCANO_ERUPT = "Não é com um bangue, mas com uma ERUPÇÃO!",
	ANNOUNCE_WAVE_BOOST = "Felicidade...",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "A monstruosidade se revela!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Como Ismael, minha caça está fadada.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Encontrarei você, monstro!",

	BATTLECRY =
	{
		GENERIC = "A morte te encontrará!",
		PIG = "Deixe a morte te abraçar!",
		PREY = "Sofra, verme!",
		SPIDER = "Te enviarei para o outro lado!",
		SPIDER_WARRIOR = "Serei o seu fim!",
	},
	COMBAT_QUIT =
	{
		PIG = "Você enganou a morte hoje, fera.",
		PREY = "Você vai gostar mais do presente que é vida agora.",
		SPIDER = "Você deve agradecer por eu poupar você.",
		SPIDER_WARRIOR = "Não esquecerei disso.",
		GENERIC = "Você viverá. Por enquanto.",
	},
	DESCRIBE =
	{
		INVENTORYGRAVE = "Será que se importariam se eu entrasse lá com eles?",
		INVENTORYMOUND = "Será que se importariam se eu entrasse lá com eles?",
		LIMPETS_COOKED = "Deprimente.",
		GLOMMER = "Oun, que bolinha de pelo mais feliz! Morra!",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Flor da noite.",
        	DEAD = "Até mesmo flores da noite morrem.",
        },
        GLOMMERWINGS = "Até mesmo suas asas são pequenas e alegres.",
        GLOMMERFUEL = "Excremento de bolinha de pelo.",
        BELL = "Podem chamar os mortos.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "O que que é isso?!",
        	EMPTY = "Eu matei.",
    	},
		WEBBERSKULL = "Ele fica melhor assim.",

		LAVA_POND_ROCK = "É tão frio e duro quanto o meu coração...",
		LAVA_POND_ROCK2 = "É tão frio e duro quanto o meu coração...",
		LAVA_POND_ROCK3 = "É tão frio e duro quanto o meu coração...",
		LAVA_POND_ROCK4 = "É tão frio e duro quanto o meu coração...",
		LAVA_POND_ROCK5 = "É tão frio e duro quanto o meu coração...",
		LAVA_POND_ROCK6 = "É tão frio e duro quanto o meu coração...",
		LAVA_POND_ROCK7 = "É tão frio e duro quanto o meu coração...",

		MOLE =
		{
			HELD = "O que você acha de ser arrancado de sua família?",
			UNDERGROUND = "Fique aí embaixo, longe deste lugar horrível.",
			ABOVEGROUND = "Você deveria voltar para onde é escuro.",
		},
		MOLEHILL = "Descendo, descendo, até as profundezas.",
		MOLEHAT = "Então é isso que aquelas coisas veem.",
		NIGHTSTICK = "Perigo no escuro.",
		RABBITHOUSE=
		{
			GENERIC = "Não é tão comestível quanto parece.",
			BURNT = "Não ficou boa cozida.",
		},
		TURF_DECIDUOUS = "Um pouco de solo.",
		TURF_SANDY = "Um pouco de solo.",
		TURF_BADLANDS = "Um pouco de solo.",
		BEARGER = "Poderia me destruir com um só golpe. Queria que assim fosse.",
		BEARGERVEST = "A morte me cerca. Bem, meu tronco, na verdade.",
		ICEPACK = "Não vai me isolar dos horrores deste mundo.",
		BEARGER_FUR = "Tem cheiro de morte.",
		FURTUFT = "Isso saiu de uma criatura viva.",
		BIGFOOT = "O arauto da destruição.",
		BONESHARD = "Perigo de sufocamento.",
		BUZZARD = "Ouvi dizer que se alimentam dos mortos.",
		FIREPIT =
		{
			EMBERS = "Don't give up, little flame!",
			GENERIC = "A flame to keep the horrors at bay.",
			HIGH = "This fire burns with passion!",
			LOW = "It's losing the will to go on.",
			NORMAL = "It's a comfort.",
			OUT = "This can be rekindled, unlike my heart.",
		},
		CACTUS = 
		{
			GENERIC = "Apresentar facas.",
			PICKED = "Achatado",
		},
		CACTUS_MEAT_COOKED = "Arranquei todos os seus espinhos.",
		CACTUS_MEAT = "Ainda é perigoso.",
		CACTUS_FLOWER = "Até mesmo a planta-lâmina tem uma flor. Ugh.",
		COLDFIRE =
		{
			EMBERS = "A escuridão se aproxima.",
			GENERIC = "Talvez eu sobreviva essa noite!",
			HIGH = "Uma visão de um inferno completamente congelado!",
			LOW = "O negrume se avizinha.",
			NORMAL = "É um fogo estranho.",
			OUT = "Esse não é bom sinal.",
		},
		CATCOON = "Me pergunto se também tinha irmã gêmea.",
		CATCOONDEN = 
		{
			GENERIC = "Eu poderia ficar em posição fetal e morrer aqui.",
			EMPTY = "Todos os gatos devem morrer.",
		},
		CATCOONHAT = "Nada como o fedor da morte na minha cabeça.",
		COONTAIL = "Está emaranhado, desigual e podre.",
		COOKPOT =
		{
			COOKING_LONG = "Seja lá o que está lá dentro ainda não está morto.",
			COOKING_SHORT = "Precisa ferver.",
			DONE = "Comida, finalmente.",
			EMPTY = "Tão vazia como a minha alma.",
			BURNT = "Queimado até o talo.",
		},
		EYEBRELLAHAT =	"Esse é um olho bem flexível.",
		ARMORDRAGONFLY = "Eu gostaria de usar do avesso.",
		DRAGON_SCALES = "Escamas de dor.",
		DRAGONFLYCHEST = "Caixa estonteante.",
		DECIDUOUSTREE = 
		{
			BURNING = "Está queimando forte.",
			BURNT = "Usado e terminado.",
			CHOPPED = "Tudo morre.",
			GENERIC = "Essa árvore é assustadora. Aposto que ela gosta do Halloween.",
			POISON = "Extra assustador!",
		},
		ACORN_COOKED = "Assado até a morte.",
		BIRCHNUTDRAKE = "Bolas de batalha!",
		FARMPLOT =
		{
			GENERIC = "Que sementes devo plantar?",
			GROWING = "Gavinhas folhosas se lançam para fora do estrume.",
			NEEDSFERTILIZER = "Essa terra está fria e morta.",
			BURNT = "Essa terra está queimada e morta.",
		},
		COLDFIREPIT =
		{
			EMBERS = "A escuridão se aproxima.",
			GENERIC = "Talvez eu sobreviva essa noite!",
			HIGH = "Uma visão de um inferno completamente congelado!",
			LOW = "O negrume se avizinha.",
			NORMAL = "É um fogo estranho.",
			OUT = "Esse não é bom sinal.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Não sei porque você se incomoda. Todos vamos queimar.",
			OFF = "Em silêncio, como um cadáver.",
			LOWFUEL = "Está quase sem combustível.",
		},
		ICEHAT = "Mantenha a cabeça fria.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Olhe aqueles cascos.",
			CHARGED = "Atacaaar!",
		},
		LIGHTNINGGOATHORN = "Um chifre curvado estranho.",
		GOATMILK = "Acho que coalhou.",
		MEATRACK =
		{
			DONE = "A secagem terminou.",
			DRYING = "Tremula a secar ao vento.",
			DRYINGINRAIN = "A chuva não deixa secar.",
			GENERIC = "Posso pendurar carne aqui.",
			BURNT = "Nunca mais secará nada.",
		},
		MERMHEAD = 
		{
			GENERIC = "Zero dignidade.",
			BURNT = "De alguma forma, encontrou uma forma de se rebaixar ainda mais.",
		},
		MERMHOUSE = 
		{
			GENERIC = "O tempo a destruiu.",
			BURNT = "O fogo a destruiu ainda mais.",
		},
		FLOWERSALAD = "Ugh, mais flores.",
        ICECREAM = "Um sorvete nunca poderia substituir a Abigail.",
        WATERMELONICLE = "A melancia está em estado catatônico.",
        TRAILMIX = "Uma porção de nutrição.",
        HOTCHILI = "Queima minhas entranhas.",
        GUACAMOLE = "Isso é macabro. Eu gosto.",
		MOOSE = "É uma abominação.",
		MOOSEEGG = "Não tenho certeza como uma coisa assim acontece.",
		MOSSLING = "Uma nova vida. A última coisa de que alguém precisa.",
		FEATHERFAN = "Isso vai fazer muito vento.",
		TROPICALFAN = "Quando fica parada, fica sem vida como a Abigail.",
		MINIFAN = "Quando fica parada, fica sem vida como a Abigail.",
		GOOSE_FEATHER = "Arrancada, como fizeram com a Abigail de mim.",
		STAFF_TORNADO = "Que clima esse, hein?",
		PIGHEAD = 
		{	
			GENERIC = "Mate o porco. Derrame seu sangue.",
			BURNT = "Ele foi carbonizado.",
		},
		PIGHOUSE =
		{
			FULL = "Espero que estejam se divertindo.",
			GENERIC = "Pelo menos estão confortáveis.",
			LIGHTSOUT = "Sempre do lado de fora, olhando para dentro.",
			BURNT = "Nada dura para sempre.",
		},
		FERTILIZER = "Um balde de sujeira.",
		RAINOMETER = 
		{	
			GENERIC = "Mede a nebulosidade. Gosto quando está melancólico.",
			BURNT = "Isso significa que a luz do sol morreu também?",
		},
		RAINCOAT = "Eu gostava de pular em poças com a Abigail.",
		RAINHAT = "Que graça tem a chuva se você não se molha?",
		RESEARCHLAB = 
		{	
			GENERIC = "Vou aprender coisas indescritíveis.",
			BURNT = "Está indescritivelmente carbonizado.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Vou aprender coisas indescritíveis.",
			BURNT = "Está indescritivelmente carbonizado.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Vou aprender coisas indescritíveis.",
			BURNT = "Está indescritivelmente carbonizado.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Está só a um passo da loucura.",
			BURNT = "A loucura traz o fogo.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Estou apenas adiando o inevitável.",
			BURNT = "Ainda bem que o sistema de emergência já era.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Um pedação de gelo frio e insensível.",
			MELTED = "Uma grande poça de gelo frio e derretido.",
		},
		ROCK_ICE_MELTED = "Uma grande poça de gelo frio e derretido.",
		ICE = "Partes quebradas do meu coração.",
        REFLECTIVEVEST = "Tudo é um colete.",
		HAWAIIANSHIRT = "Colocam flores em qualquer coisa hoje em dia.",
		TENT = 
		{
			GENERIC = "O sono nada mais é que uma prévia da morte.",
			BURNT = "Uma prévia dos fogos do inferno.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Um cochilo nada mais é que uma prévia da morte.",
			BURNT = "Uma prévia dos fogos do inferno.",
		},
		TRANSISTOR = "O do que elétrico?",
		TREASURECHEST = 
		{
			GENERIC = "O qual conterá meus ganhos.",
			BURNT = "Não pode nem guardar cinzas.",
		},
		TUMBLEWEED = "Sozinha e rolando pela vida.",
		GRASS_UMBRELLA = "O sol castiga.",
		PALMLEAF_UMBRELLA = "O sol castiga.",
		UNIMPLEMENTED = "Ainda não está pronto, como a vida.",
		WALL_HAY = 
		{	
			GENERIC = "Essa é a mera sugestão de defesa.",
			BURNT = "Defesas abertas.",
		},
		WALL_WOOD = 
		{
			GENERIC = "Agora posso evitar o inevitável.",
			BURNT = "O inevitável está chegando.",
		},
		WARG = "A true bastion of evil.",
		WATERMELON = "É principalmente água. O que tem de mais?",
		WATERMELON_COOKED = "Virou água morna.",
		WATERMELONHAT = "Está grudando na minha cabeça. Eca!",
		WINTEROMETER = 
		{
			GENERIC = "Por que tenho a sensação de que está medindo minha mortalidade?",
			BURNT = "Quer dizer que o dia da minha morte é esse?",
		},
		HOME = "A pathetic simulcra...",
		HOMESIGN = 
		{
			GENERIC = "Uma marca é feita, mesmo que passageira.",
			BURNT = "Passageira, sem dúvida.",
		},
		BEEBOX =
		{
			GENERIC = "Elas trabalharão para que eu possa roubar.",
			READY = "Seus esforços foram produtivos!",
			FULLHONEY = "Seus esforços foram produtivos!",
			NOHONEY = "Trabalhem, abelhas!",
			SOMEHONEY = "Continuem se esforçando.",
			BURNT = "Mel queimado.",
		},
		LIVINGTREE = "Não morre nunca?",
		ICESTAFF = "Um cajado para congelar.",
		WORMLIGHT = "Há um leve sussurro vindo dela.",
		WORMLIGHT_LESSER = "É melhor a luz do verme que sua língua.",
		WORM =
		{
		    PLANT = "Parece deslocada.",
		    DIRT = "Há algo aí?",
		    WORM = "Vem das profundezas.",
		},
		WORMLIGHT_PLANT = "Parece deslocada.",
		EEL = "Uma enguia.",
		EEL_COOKED = "Uma enguia cozida.",
		UNAGI = "Parece mais apetitoso assim.",
		EYETURRET = "Não sei por que me ajuda.",
		EYETURRET_ITEM = "Acho que preciso instalá-lo.",
		MINOTAURHORN = "Tudo que estou de uma fera que uma vez foi grande.",
		MINOTAURCHEST = "Nossa, que chifres magníficos você tem!",
		THULECITE_PIECES = "Fragmentos de um material poderoso.",
		POND_ALGAE = "Algas.",
		GREENSTAFF = "Posso ver o poder brilhando lá dentro.",
		POTTEDFERN = "Seu crescimento é interrompido pelos limites da panela.",

		THULECITE = "Sua presença marca o limite do desconhecido.",
		ARMORRUINS = "Um adiamento da morte.",
		RUINS_BAT = "Tenho o poder dos antigos em minhas mãos.",
		RUINSHAT = "Abigail teria adorado essa coroa.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Não sei o que espreita nas sombras.",	--calm phase
			WARN = "Posso sentir os olhos a espreitar.",	--Before nightmare
			WAXING = "Eles se aproximam.", --Nightmare Phase first 33%
			STEADY = "Estou completamente cercada!", --Nightmare 33% - 66%
			WANING = "Acho que estão indo embora.", --Nightmare 66% +
			DAWN = "Está quase terminando.", --After nightmare
			NOMAGIC = "Estou sozinha.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "O tempo vence todas as batalhas.",
		ROOK_NIGHTMARE = "O tempo desgasta tudo.",
		KNIGHT_NIGHTMARE = "Outra batalha perdida para o tempo.",
		MINOTAUR = "Ele deve estar solitário, preso em uma gaiola tão pequena.",	--Monster in labyrinth
		SPIDER_DROPPER = "A escuridão drenou a cor de sua pele.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Retira a energia das profundezas.",	--Lights that activate during nightmare.
		RELIC = "A vision of the past.",	--Fixed relic
		RUINS_RUBBLE = "A vision of the past. Broken.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "Um item com várias funções.",	--Works as axe and pickaxe
		GREENGEM = "Suas falhas são suas características mais belas.",
		ORANGESTAFF = "A cada vez que uso morro e renasço.",	--Teleports player.
		YELLOWAMULET = "Um breve momento de luz em minha vida sombria.",	--Emits light, player walks faster.
		GREENAMULET = "Um clarão de brilho!",	--Reduce cost of crafting

		SLURPER = "Ah, como é bom ser simples.",
		SLURPER_PELT = "Um saco vazio de fome.",
		SLURPERPELT = "An empty bag of hunger.",
		ARMORSLURPER = "Um traje vivo, grudento e melancólico.",
		ORANGEAMULET = "Libertação temporária da escravidão.",
		YELLOWSTAFF = "A vara está tão distorcida quanto minha alma.",
		YELLOWGEM = "Me faz lembrar da minha mãe.",
		ORANGEGEM = "Essas coisas costumavam me deixar feliz.",
		TELEBASE = 
		{
			VALID = "A energia flui por ele.",
			GEMS = "O foco é tão sem vida.",
		},
		GEMSOCKET = 
		{
			VALID = "A pedra preciosa concentrou a força.",
			GEMS = "Parece vazio.",
		},
		STAFFLIGHT = "Quase posso divisar um pequeno sistema solar.",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="É bonita.",
			LONG = "Era a flor da minha irmã. Ela partiu para longe.",
			MEDIUM = "Posso sentir a presença da Abigail ficando mais forte.",
			SOON = "A Abigail está quase chegando!",
			HAUNTED_POCKET = "A Abigail está pronta para brincar, mas ela precisa de um pouco de espaço.",
			HAUNTED_GROUND = "Preciso mostrar à Abigail como brincar.",

		},

        ANCIENT_ALTAR = "Está repleto de ecos dos mortos.",
        ANCIENT_ALTAR_BROKEN = "Ouço os ecos de dor da minha morte.",
        ANCIENT_STATUE = "Não é muito atraente.",

        LICHEN = "Como é que consegue crescer assim?",
		CUTLICHEN = "Fugaz, como a vida.",
		CAVE_BANANA = "As cascas parecem perigosas.",
		CAVE_BANANA_COOKED = "Amassadinho de banana quente é muito melhor.",
		CAVE_BANANA_TREE = "Pobre planta, presa longe do sol.",
		CAVE_BANANA_BURNT = "A morte e o sofrimento nunca terminam.",
		ROCKY = "Que imagens terríveis eles viram.",


		BLUEAMULET = "Um abraço frio familiar.",
		PURPLEAMULET = "Está secretando.",
		TELESTAFF = "Eu poderia fugir se fosse mais poderoso.",
		MONKEY = "Viver sem o fardo da inteligência deve ser bacana.",
		MONKEYBARREL = "Está sujo.",
		MONSTERLASAGNA = "Maldade cozida continua sendo maldade, mesmo na lasanha.",
		HOUNDSTOOTH="Retirado com raiz e tudo.",
		ARMORSNURTLESHELL="Agora posso me esconder dos meus problemas.",
		BAT="Uma criatura notívaga.",
		BATBAT = "Uma arma encantada. Empolgante!",
		BATWING="Se pelo menos eu pudesse voar para longe.",
		BATWING_COOKED="Uma vez eles tinham grande potencial.",
		BATCAVE= "Eles estão espreitando lá...",
		BEDROLL_FURRY="Vou me enrolar nas peles peludas dos derrotados.",
		BUNNYMAN="Que vidas interiores atormentadas eles devem ter.",
		FLOWER_CAVE="Parece frágil.",
		FLOWER_CAVE_DOUBLE="Parece frágil.",
		FLOWER_CAVE_TRIPLE="Parece frágil.",
		GUANO="O subproduto inevitável da vida.",
		LANTERN="Ilumine o caminho sombriamente.",
		LIGHTBULB="Está sendo lentamente destruída pelo fogo.",
		MANRABBIT_TAIL="Contém essência borbulhante.",
		MUSHTREE_TALL  ="These are some strange trees.",
		MUSHTREE_MEDIUM="It looks like a rotting hat.",
		MUSHTREE_SMALL ="Do little gnomes live in these?",
		MUSHTREE_TALL=
		{
            GENERIC = "Que árvores estranhas.",
            BLOOM = "Está tentando com tanto afinco. Por quê?",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Parece um chapéu podre.",
            BLOOM = "Todos seus esforços caem em solo rochoso.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Será que gnominhos vivem aqui?",
            BLOOM = "Tem uma presença brilhante.",
        },
        MUSHTREE_TALL_WEBBED = "Esse é frágil e desprezado.",
        SPORE_TALL = "Seja livre, pequeno!",
        SPORE_MEDIUM = "Seja livre, pequeno!",
        SPORE_SMALL = "Seja livre, pequeno!",
        SPORE_TALL_INV = "Tantos pereceram. Mas este está a salvo.",
        SPORE_MEDIUM_INV = "Tantos pereceram. Mas este está a salvo.",
        SPORE_SMALL_INV = "Tantos pereceram. Mas este está a salvo.",

		SLURTLE="Está distraído perseguindo pedras.",
		SLURTLE_SHELLPIECES="Pedaços de sonhos desfeitos de tartareca.",
		SLURTLEHAT="Certamente não ajudou seu dono original.",
		SLURTLEHOLE="As tartarecas saem quando crescem demais.",
		SLURTLESLIME="Tremula com ansiedade viscosa.",
		SNURTLE="Esse tem uma concha maior.",
		SPIDER_HIDER="Uma aranha covarde.",
		SPIDER_SPITTER="Está mastigando algo.",
		BEEMINE_MAXWELL = "The furious creatures appreciate their freedom in retrospect.",
		SPIDERHOLE="Está infestado.",
		SPIDERHOLE_ROCK ="Está infestado.",
		STALAGMITE="A terra rende seus espólios.",
		STALAGMITE_FULL="A terra rende seus espólios.",
		STALAGMITE_LOW="A terra rende seus espólios.",
		STALAGMITE_MED="A terra rende seus espólios.",
		STALAGMITE_TALL="A terra se eleva.",
		STALAGMITE_TALL_FULL="A terra se eleva.",
		STALAGMITE_TALL_LOW="A terra se eleva.",
		STALAGMITE_TALL_MED="A terra se eleva.",

		TURF_CARPETFLOOR = "Um pouco de solo.",
		TURF_CHECKERFLOOR = "Um pouco de solo.",
		TURF_DIRT = "Um pouco de solo.",
		TURF_FOREST = "Um pouco de solo.",
		TURF_GRASS = "Um pouco de solo.",
		TURF_MARSH = "Um pouco de solo.",
		TURF_ROAD = "Um pouco de solo.",
		TURF_ROCKY = "Um pouco de solo.",
		TURF_SAVANNA = "Um pouco de solo.",
		TURF_WOODFLOOR = "Um pouco de solo.",

		TURF_CAVE="Um pouco de solo.",
		TURF_FUNGUS="Um pouco de solo.",
		TURF_SINKHOLE="Um pouco de solo.",
		TURF_UNDERROCK="Um pouco de solo.",
		TURF_MUD="Um pouco de solo.",

		POWCAKE = "Eu teria que estar desesperada.",		
		CAVE_ENTRANCE = "Alguém está tentando manter o submundo sob controle.",
		CAVE_ENTRANCE_RUINS = "Alguém está tentando manter o submundo sob controle.",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "Estou muito ocupada descendo à loucura para descer essa caverna.",
            OPEN = "Um grande mal espreita sob a superfície.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Por ir embora? A luz aqui fica bem com minha pele.",
            OPEN = "A superfície chama.",
        },

		BOOMERANG = "A morte volta para o remetente.",
		MAXWELLPHONOGRAPH = "Deveríamos fazer uma dança macabra?",
		ABIGAIL = "Essa é a minha irmã gêmea, Abigail.",
		PIGGUARD = "Esse porquinho parece mau.",
		ADVENTURE_PORTAL = "Que horror tecnológico é esse?",
		AMULET = "Fico pensando quem costumava ser o dono disso.",
		ANIMAL_TRACK = "Sinais da fera.",
		ARMORGRASS = "Só estou prolongando o inevitável.",
		ARMORMARBLE = "Poderia deter as adagas que apunhalam meu coração.",
		ARMORWOOD = "Posso adiar o inevitável um pouco mais com isso.",
		ARMOR_SANITY = "Uma maneira perfeitamente segura de ficar louco.",
		ASH =
		{
			GENERIC = "Tudo o que restou depois de outro lindo incêndio.",
			REMAINS_GLOMMERFLOWER = "A flor foi incinerada no teletransporte!",
			REMAINS_EYE_BONE = "O osso ocular foi incinerado no teletransporte!",
			REMAINS_THINGIE = "Isso era alguma coisa antes de ser carbonizada...",
		},
		AXE = "Um instrumento para a indústria e para assassinatos.",
		BABYBEEFALO = "Aproveite sua juventude. Logo você aprenderá os horrores do mundo real.",
		BACKPACK = "Uma mochila. Agora posso carregar fardos ainda mais pesados.",
		BACONEGGS = "Um café da manhã balanceado para começar outro dia deprimente.",
		BANDAGE = "Não há salvação para a dor da existência.",
		BASALT = "Tentar quebrar não teria sentido.",
		BEARDHAIR = "Isso é simplesmente sórdido.",
		BEDROLL_STRAW = "O sono nada mais é que uma morte temporária.",
		BEE =
		{
			GENERIC = "Eu ficaria longe dessa ferroadora.",
			HELD = "Fique calma, pequenina.",
		},
		BEEFALO =
		{
			FOLLOWER = "Ele me segue até sua desgraça.",
			GENERIC = "Que pensamentos doentes devem se esconder atrás daqueles olhos.",
			NAKED = "Sua nudez agora está à mostra.",
			SLEEPING = "Dormir, talvez sonhar.",
		},
		BEEFALOHAT = "Devo cobrir minha cabeça.",
		BEEFALOWOOL = "Em algum lugar, um bífalo está nu e com frio.",
		BEEHAT = "Isso vai me proteger daqueles zumbidos felizes. Ah, e das ferroadas.",
		BEEHIVE = "Uma colmeia desgraçada de escória e pólen.",
		BEEMINE = "Eles ainda estão vivos lá dentro. Pobrezinhos!",
		BERRIES = "Essas bagas são ácidas.",
		BERRIES_COOKED = "Tem sabor mais balanceado, mas não vai durar muito.",
		BERRYBUSH =
		{
			BARREN = "Seco.",
			WITHERED = "Sucumbiu ao calor.",
			GENERIC = "Um lanchinho, quem sabe?",
			PICKED = "Vou precisar esperar.",
		},
		BIRDCAGE =
		{
			GENERIC = "Poucos de nós podem ver nossas jaulas.",
			OCCUPIED = "Ele está mais feliz agora.",
			SLEEPING = "Morto? Não. Só dormindo.",
			HUNGRY = "Deve estar com fome.",
			STARVING = "O vazio o está corroendo de dentro para fora.",
			DEAD = "Sem vida, ele descansa em pedaços.",
			SKELETON = "Esse... é um ex-pássaro.",
		},
		BIRDTRAP = "Gravetos e seda letais.",
		BIRD_EGG = "Tanta esperança, destruída.",
		BIRD_EGG_COOKED = "Nenhum pássaro sairá daí.",
		BISHOP = "Para o que ele reza?",
		BISHOP_CHARGE_HIT = "Autch...",

		BLOWDART_SLEEP = "Não é o sono longo, só um temporário.",
		BLOWDART_PIPE = "Assopro nesta ponta e a dor sai na outra.",
		BLOWDART_FIRE = "Devo incendiar o mundo?",
		BLUEGEM = "Azul como... ahm... um pássaro triste?",
		BLUEPRINT = "Seja lá quem desenhou isso, provavelmente já morreu.",
		BELL_BLUEPRINT = "Seja lá quem desenhou isso, provavelmente já morreu.",
		BLUE_CAP = "Um fungo para conservar a monotonia.",
		BLUE_CAP_COOKED = "Tudo é maleável.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Mofado.",
			INGROUND = "Eu também me esconderia, se pudesse.",
			PICKED = "Colhido.",
		},
		BOARDS = "Ainda mais assustador para as árvores.",
		BONESTEW = "Eles morreram, daí coloquei todos num ensopado.",
		BUGNET = "Uma prisão para insetinhos.",
		BUSHHAT = "Já sou praticamente invisível...",
		BUTTER = "Não estava esperando isso.",
		BUTTERFLY =
		{
			GENERIC = "Bonita, mas de vida curta.",
			HELD = "Tenho seu fogo nas minhas mãos.",
		},
		BUTTERFLYWINGS = "A borboleta não pode mais voar.",
		BUTTERFLYMUFFIN = "Quero ver você sair dessa armadilha açucarada!",
		CAMPFIRE =
		{
			EMBERS = "A escuridão se aproxima.",
			GENERIC = "Talvez eu sobreviva essa noite!",
			HIGH = "Uma visão do inferno!",
			LOW = "O negrume se avizinha.",
			NORMAL = "É um fogo.",
			OUT = "Esse não é bom sinal.",
		},
		CANE = "Não conseguiria chegar a lugar nenhum mais rápido.",
		CARROT = "É uma cenoura.",
		CARROT_COOKED = "É uma cenoura que passou pela manopla de fogo.",
		CARROT_PLANTED = "É uma cenoura que está na terra.",
		CARROT_SEEDS = "É uma cenoura que esperando ser.",
		CAVE_FERN = "Um toque de cor na escuridão.",
		CHARCOAL = "Gelado, morto e sombrio, exatamente como meu coração.",
        CHESSJUNK1 = "Vida artificial fria e morta.",
        CHESSJUNK2 = "Vida artificial fria e morta.",
        CHESSJUNK3 = "Vida artificial fria e morta.",
		CHESTER = "Uma bola peluda de vazio.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Está olhando dentro da minha alma.",
			WAITING = "Está menos dormindo do que esperando...",
		},
		COOKEDMANDRAKE = "Foi uma boa morte. Você será delicioso.",
		COOKEDMEAT = "O sangue restante foi todo cozido.",
		COOKEDMONSTERMEAT = "Maldade cozida continua sendo maldade.",
		COOKEDSMALLMEAT = "O fogo a purificou.",
		CORN = "O que é um pontinho amarelo... deixa pra lá!",
		CORN_COOKED = "Esse milho não suportou o calor.",
		CORN_SEEDS = "A semente da vida, tão pequena na minha mão.",
		CROW =
		{
			GENERIC = "Tira teu bico do meu coração!",
			HELD = "Ele é meu.",
		},
		CUTGRASS = "Gosto de matar coisas pequenas.",
		CUTREEDS = "Gosto de cortar coisas.",
		CUTSTONE = "O melhor para marcar sepulturas.",
		DEADLYFEAST = "Aqui, minha última refeição.",
		DEERCLOPS = "A morte encarnada!",
		DEERCLOPS_EYEBALL =  "Que horrores ele deve ver.",
		DEPLETED_GRASS =
		{
			GENERIC = "Os restos de um tufo de grama.",
		},
		DIRTPILE = "Olha só, mais terra!",
		DIVININGROD =
		{
			COLD = "A fonte está distante.",
			GENERIC = "Está procurando para sempre sua metade perdida.",
			HOT = "Há algo maligno por aqui!",
			WARM = "A maldade está chegando mais perto.",
			WARMER = "Está muito perto agora.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "O que essa coisa ultramoderna faz?",
			READY = "Ainda precisa de uma chave grande.",
			UNLOCKED = "Vamos ver o que eu encontro!",
		},
		DRAGONFLY = "Está queimando por dentro.",
		LAVASPIT = 
		{
			HOT = "Ele cuspiu.",
			COOL = "Esfriou e tem um cheiro esquisito.",
		},
		LAVA_POND = "Eu poderia pular lá e acabar com isso.",
		LAVAE = "Queima com os fogos do inferno.",
		LAVAE_PET = 
		{
			STARVING = "Ele está se aproximando de sua morte.",
			HUNGRY = "Ele está sofrendo as dores da fome.",
			CONTENT = "Aproveite sua felicidade enquanto dura, pequena lava.",
			GENERIC = "Uma centelha de vida iluminando a escuridão.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "Vale a pena apostar no seu futuro?",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Esse ovo está quase tão frio quanto meu coração.",
			COMFY = "O ovo está quente, mas meu coração ainda está frio.",
		},
		LAVAE_TOOTH = "Sente, é só um dente.",

		DRAGONFRUIT = "Isso nem tem forma de dragão.",
		DRAGONFRUIT_COOKED = "Ainda não é um dragão. Pelo menos está morta.",
		DRAGONFRUIT_SEEDS = "É uma semente. Não vai virar dragão.",
		DRAGONPIE = "Bem, pelo menos agora é uma torta.",
		DRUMSTICK = "Dá um som interessante e tem nutrientes!",
		DRUMSTICK_COOKED = "Menos cru, mais saborosa.",
		DUG_BERRYBUSH = "Gosto dela morta, mas devo plantar isso.",
		DUG_GRASS = "Gosto dela morta, mas devo plantar isso.",
		DUG_MARSH_BUSH = "Gosto dela morta, mas devo plantar isso.",
		DUG_SAPLING = "Gosto dela morta, mas devo plantar isso.",
		DURIAN = "Espinhoso e fedorento!",
		DURIAN_COOKED = "Menos espinhoso, mas mais fedido!",
		DURIAN_SEEDS = "Milagrosamente, as sementes não têm cheiro.",
		EARMUFFSHAT = "Suas pontas amargas me protegem do amargo frio.",
		EGGPLANT = "Praticamente uma erva-moura. Praticamente.",
		EGGPLANT_COOKED = "Cozinhar essa erva-moura tornou-a ainda menos mortífera.",
		EGGPLANT_SEEDS = "É uma semente de erva-moura.",
		ACORN = 
		{
		    GENERIC = "Uma vidinha, abrigada na frágil morte.",
		    PLANTED = "Uma árvore crescerá em breve.",
		},
		EVERGREEN =
		{
			BURNING = "Está queimando forte.",
			BURNT = "Usado e terminado.",
			CHOPPED = "Tudo morre.",
			GENERIC = "A natureza é tão entediante.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Está queimando forte.",
			BURNT = "Usado e terminado.",
			CHOPPED = "Tudo morre.",
			GENERIC = "Seu ciclo de vida está terminando.",
		},
		EYEPLANT = "Eles seguem todos os desejos de seu mestre.",
		FEATHERHAT = "Piu piu!",
		FEATHER_CROW = "Uma pensa de corvo, preta como a escuridão eterna.",
		FEATHER_ROBIN = "Uma pena de cardeal, vermelha como o sangue.",
		FEATHER_ROBIN_WINTER = "Uma pena de cardeal invernal, branca como a luz no fim do túnel.",
		FEM_PUPPET = "Me pergunto o que ela fez.",
		FIREFLIES =
		{
			GENERIC = "Um pequeno brilho no escuro.",
			HELD = "Luzes pequenas, afastadas do mundo fora do meu bolso.",
		},
		FIREHOUND = "Tem uma disposição ardente.",
		FIRESTAFF = "Eu poderia colocar fogo no mundo.",
		FISH = "Eu estava lutando desesperadamente pela vida. Coitado!",
		FISHINGROD = "Com isso, posso arrancar os peixes de seu precioso lago.",
		FISHSTICKS = "Blocos perfeitamente moldados de peixe.",
		FISHTACOS = "Espero ter tirado todos os ossos.",
		FISH_MED_COOKED = "Uma boa grelhada deixa firminho.",
		FISH_MED = "Largou sua corrente terrena.",
		FISH_COOKED = "Uma boa grelhada deixa firminho.",
		FLINT = "Uma pedra com aparência de lâmina.",
		FLOWER = "Elas são brilhantes e felizes. Eca.",
		FLOWER_WITHERED = "Esse é o destino de todas as coisas.",
		FLOWERHAT = "Mas estou de luto...",
		FLOWER_EVIL = "Pelo menos elas são melhores que as outras flores.",
		FOLIAGE = "Me leva a Aarnivalkea.",
		FOOTBALLHAT = "Uma coisa morta para eu usar. Beleza.",
		FROG =
		{
			DEAD = "A vida é pequena e curta.",
			GENERIC = "Ele é pequeno e cheio de verrugas.",
			SLEEPING = "Ele está dormindo.",
		},
		FROGGLEBUNWICH = "Eu nunca pensei que pernas de sapo poderiam ter uma aparência tão boa.",
		FROGLEGS = "Arrancado direto de um sapo.",
		FROGLEGS_COOKED = "Definitivamente não se contorce mais.",
		FRUITMEDLEY = "Doce, azedinho e numa taça.",
		GEARS = "As entranhas de um demônio mecânico.",
		GHOST = "Ele ascendeu do túmulo!",
		GOLDENAXE = "Pelo menos posso matar árvores com estilo.",
		GOLDENPICKAXE = "Pelo menos posso destruir pedras com estilo.",
		GOLDENPITCHFORK = "Pelo menos posso preparar a terra com estilo.",
		GOLDENSHOVEL = "Pelo menos posso cavar com estilo.",
		GOLDNUGGET = "Mesmo no purgatório continua sendo o mais precioso dos metais.",
		GRASS =
		{
			BARREN = "Precisa de cocô.",
			WITHERED = "Não conseguiu suportar o calor.",
			BURNING = "Tem um cheiro esquisito.",
			GENERIC = "É só um tufo de grama.",
			PICKED = "Acabou de ser morta.",
		},
		GREEN_CAP = "Esse cogumelo é decepcionantemente normal.",
		GREEN_CAP_COOKED = "Tudo é maleável.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Frio e úmido.",
			INGROUND = "Eu também me esconderia, se pudesse.",
			PICKED = "Colhido.",
		},
		GUNPOWDER = "O caminho que trilho é sombrio.",
		HAMBAT = "Morte gera morte.",
		HAMMER = "Com isso poderei destruir o mundo.",
		HEALINGSALVE = "A vida traz dor, dor traz vida.",
		HEATROCK =
		{
			FROZEN = "Congelada como meu coração.",
			COLD = "Apenas uma pedra moderadamente fria.",
			GENERIC = "Lá está ela, só ocupando espaço.",
			WARM = "Tão morna e sem vida quanto todas as outras pedras.",
			HOT = "As que queimam mais claro, queima mais rápido.",
		},
		HONEY = "Uma gostosura doce, mas fugaz.",
		HONEYCOMB = "Pedaços de colmeia, espalhados.",
		HONEYHAM = "Um molho doce para o abraço doce dessa criatura.",
		HONEYNUGGETS = "Carne cortada em pedacinhos. Igual ao meu coração.",
		HORN = "Parece que tem um bífalo preso lá dentro.",
		HOUND = "Afaste-se, lacaio do mal!",
		HOUNDBONE = "Os restos de uma fera maligna.",
		HOUNDMOUND = "Lar das criaturas mais malignas.",
		ICEBOX = "É tão fria quanto o meu coração.",
		ICEHOUND = "Ele tem um coração morto e gelado.",
		INSANITYROCK =
		{
			ACTIVE = "Está chamando meu nome.",
			INACTIVE = "É fria e sombria.",
		},
		JAMMYPRESERVES = "A quantidade perfeita de geleia.",
		KABOBS = "Carne, espetadas bem no centro.",
		KILLERBEE =
		{
			GENERIC = "Uma abelha sem consciência.",
			HELD = "Fique calma, pequenina.",
		},
		KNIGHT = "Um cavalo frio e sem alma.",
		KOALEFANT_SUMMER = "Uma fera da solidão.",
		KOALEFANT_WINTER = "Suporta os elementos cruéis.",
		KRAMPUS = "Oi, criatura imunda do submundo.",
		KRAMPUS_SACK = "Tem cheiro de bode.",
		LEIF = "Uma fera vagarosa.",
		LEIF_SPARSE = "Uma fera vagarosa.",
		LIGHTNING_ROD =
		{
			CHARGED = "Até mesmo essa energia terminará.",
			GENERIC = "Concentra a destruição.",
		},
		LITTLE_WALRUS = "O ciclo de violência continua.",
		LIVINGLOG = "Está gritando para sempre silenciosamente.",
		LOCKEDWES = "Aprisionado pelas estátuas de Maxwell, sempre vivo.",
		LOG = "If trees could talk, they would scream at the sight of this.",
		LOG =
		{
			BURNING = "Just a burning log.",
			GENERIC = "If trees could talk, they would scream at the sight of this.",
		},
		LUREPLANT = "Consome tudo.",
		LUREPLANTBULB = "A vida continua.",
		MALE_PUPPET = "Me pergunto o que ele fez.",
		MANDRAKE =
		{
			DEAD = "Pobre mandrágora!",
			GENERIC = "A poderosa mandrágora. Eu deveria colhê-la à noite.",
			PICKED = "Avante, meu lacaio vegetal!",
		},
		MANDRAKESOUP = "Fervida até a morte",
		MARBLE = "Lisa e sem vida.",
		MARBLEPILLAR = "Nem mesmo pedras podem suportar a pressão constante da decadência.",
		MARBLETREE = "Não há mais sinais vitais nessa árvore gelada.",
		MARSH_BUSH =
		{
			BURNING = "Até mesmo espinhos queimam.",
			GENERIC = "Um arbusto que sempre dói.",
			PICKED = "Me doeu fazer isso.",
		},
		MARSH_PLANT = "É uma planta.",
		MARSH_TREE =
		{
			BURNING = "Está queimando.",
			BURNT = "Sombrio como meu coração.",
			CHOPPED = "Seus espinhos não a protegeram.",
			GENERIC = "Uma árvore que só conhece a morte.",
		},
		MAXWELL = "Sinto um estranho parentesco com ele.",
		MAXWELLHEAD = "Ele, sem dúvidas, tem um gostinho pelo drama.",
		MAXWELLLIGHT = "Que luz curiosa.",
		MAXWELLLOCK = "Parece mágico.",
		MAXWELLTHRONE = "Não é bem o que eu esperava.",
		MEAT = "Ainda está sangrenta.",
		MEATBALLS = "Carne em forma de bolas. Que demais!",
		MEAT_DRIED = "Carne seca e deliciosa.",
		MERM = "Coisa do pântano horrenda!",
		MINERHAT = "Luz sem necessidade de usar as mãos.",
		MONSTERMEAT = "A maldade a permeia.",
		MONSTERMEAT_DRIED = "Carne seca e com gosto estranho.",
		MOSQUITO =
		{
			GENERIC = "Rouba a vida dos outros para manter a sua.",
			HELD = "Posso sentir seu calor roubado.",
		},
		MOSQUITOSACK = "Um saco de sangue tirado de um mosquito. Adoro.",
		MOUND =
		{
			DUG = "A terra vomitou seus segredos.",
			GENERIC = "Algum dia vou me reunir com você.",
		},
		NIGHTLIGHT = "Misteriosa, mas mesmo assim, linda.",
		NIGHTMAREFUEL = "Com o sono dos sonhos isso aparece.",
		NIGHTSWORD = "Os sonhos têm um fim. Um fim violento.",
		NITRE = "Aqui jaz a insensatez da humanidade.",
		ONEMANBAND = "Eu tinha muito prazer em instrumentos como esse.",
		PANDORASCHEST = "A vida é um jogo de azar.",
		PANFLUTE = "A música é a janela para a minha alma vazia!",
		PAPYRUS = "Para documentar minha dor.",
		PENGUIN = "Todo arrumado, mas onde ir?",
		PERD = "Pássaro estúpido! Fique longe das minhas bagas!",
		PEROGIES = "Uma adorável dose de nutrientes.",
		PETALS = "Destruí algo lindo.",
		PETALS_EVIL = "Elas estão pintadas com as cores da minha alma.",
		PICKAXE = "Para que eu possa penetrar a própria terra.",
		PIGGYBACK = "Eles são mais úteis quando mortos.",
		PHLEGM = "A fera maldita devia estar doente.",
		PIGKING = "Viva bem enquanto pode, vossa majestade.",
		PIGMAN =
		{
			DEAD = "Ele está melhor agora.",
			FOLLOWER = "Ainda me sinto sozinha.",
			GENERIC = "Eles são tão reservados.",
			GUARD = "Bem Orwelliano.",
			WEREPIG = "Uma criatura notívaga.",
		},
		PIGSKIN = "A pele de um porco que uma vez viveu.",
		PIGTORCH = "Desbravando a escuridão.",
		PINECONE = 
		{
		    GENERIC = "Uma vidinha, envolta em frágil morte.",
		    PLANTED = "Uma árvore crescerá em breve.",
		},
		PITCHFORK = "Que ferramenta demoníaca!",
		PLANTMEAT = "Tem um cheiro podre.",
		PLANTMEAT_COOKED = "É só um pouquinho mais atraente.",
		PLANT_NORMAL =
		{
			GENERIC = "Uma planta comestível.",
			GROWING = "Continue crescendo. Eu espero.",
			READY = "Está pronta para a colheita.",
			WITHERED = "Teve a sua vida sugada por completo.",
		},
		POMEGRANATE = "Tantas partes vermelhas suculentas para devorar e esmagar!",
		POMEGRANATE_COOKED = "Quente, mas não menos melequenta.",
		POMEGRANATE_SEEDS = "Estava esperando mais sementes do que isso dessa coisa.",
		POND = "Ofélia? Você está aí embaixo?",
		POOP = "A vida é sangue e isso.",
		SCORCHED_SKELETON = "A chama limpou essa pobre maldita alma.",
		PUMPKIN = "É tão grande quanto o buraco do meu coração.",
		PUMPKINCOOKIE = "Um... cookie...",
		PUMPKIN_COOKED = "Encolheu um pouco com o calor. Gosto disso.",
		PUMPKIN_LANTERN = "Você não é tão assustador.",
		PUMPKIN_SEEDS = "É uma semente. Uhu.",
		PURPLEGEM = "Roxo como uma... coisa roxa.",
		RABBIT =
		{
			GENERIC = "Ele está vagando sem rumo, sem consciência de seu destino.",
			HELD = "Ele está seguro em meus braços.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Sou muito grande para passar por aqui.",
			SPRING = "Está fechado. Ninguém vai cair aqui agora.",
		},
		RATATOUILLE = "Um monte de vegetais cozidos. Impressionante.",
		RAZOR = "Isso serve apenas para raspar.",
		REDGEM = "Vermelho como o sangue do meu coração.",
		RED_CAP = "Um cogumelo atrás do meu próprio coração.",
		RED_CAP_COOKED = "Tudo é maleável.",
		RED_MUSHROOM =
		{
			GENERIC = "Úmido.",
			INGROUND = "Eu também me esconderia, se pudesse.",
			PICKED = "Colhido.",
		},
		REEDS =
		{
			BURNING = "Logos virarão cinzas.",
			GENERIC = "É só um monte de juncos.",
			PICKED = "Recolhidos.",
		},
        RELIC = 
        {
            GENERIC = "Um resto de um mundo ancestral.",
            BROKEN = "Pedaços quebrados de pedra.",
        },
        RUBBLE = "Broken bits of stone.",
        RUINS_RUBBLE = "Uma pilha de sonhos desfeitos.",
		RESURRECTIONSTONE = "Uma área desnecessária.",
		ROBIN =
		{
			GENERIC = "Isso significa que a primavera está chegando? Espero que não.",
			HELD = "Ele gosta de ficar preso no meu bolso.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "A vida no deserto gelado.",
			HELD = "É tão macio. É meu inimigo.",
		},
		ROBOT_PUPPET = "O que será que eles fizeram?",
		MOOSE_NESTING_GROUND = "O início da vida. Odeio.",
		ROCK_LIGHT =
		{
			GENERIC = "Tem uma fogueira no estômago da cova.",
			OUT = "A lava perdeu sua vontade de queimar...",
			LOW = "As sombras se avizinham.",
			NORMAL = "A lava está pegando fogo.",
		},
		ROCK = "Nem mesmo isso é permanente.",
		ROCKS = "Algumas pedrinhas.",
        ROOK = "Uma torre? Ou é um castelo?",
		ROPE = "Essa seria a saída fácil desse lugar.",
		ROTTENEGG = "O destino de todas as coisas.",
		SANITYROCK =
		{
			ACTIVE = "Está me chamando.",
			INACTIVE = "Até mesmo esse obelisco me deixou.",
		},
		SAPLING =
		{
			BURNING = "Entregue às chamas.",
			WITHERED = "O calor opressivo venceu.",
			GENERIC = "Está tentando crescer.",
			PICKED = "Quem sabe na próxima, muda.",
		},
		SEEDS = "Vida, ou pelo menos a promessa de uma.",
		SEEDS_COOKED = "Tostei-as até a morte.",
		SEWING_KIT = "Outro implemento para adiar o inevitável declínio.",
		SHOVEL = "Que segredos terríveis descobrirei?",
		SILK = "Tão escorregadio e refinado.",
		SKELETON = "Invejo sua fuga.",
		SKELETON_PLAYER = "Eu estava tão, mas tão perto.",
		SKULLCHEST = "Conterá meus lembretes sobre a morte.",
		SMALLBIRD =
		{
			GENERIC = "Olá, pequenino.",
			HUNGRY = "Você está vazio por dentro?",
			STARVING = "Um buraco negro do qual as sementes nunca voltam.",
		},
		SMALLMEAT = "Tem cheiro de medinho.",
		SMALLMEAT_DRIED = "Carne seca e deliciosa.",
		SPAT = "Vou acabar com seu sofrimento.",
		SPEAR = "Me tornei a destruidora de mundos.",
		SPIDER =
		{
			DEAD = "Nos encontraremos de novo algum dia.",
			GENERIC = "Uma criatura notívaga.",
			SLEEPING = "O mal está dormido.",
		},
		SPIDERDEN = "Um ninho de sujeira e vilania.",
		SPIDEREGGSACK = "Um pacotinho cheio de morte e destruição.",
		SPIDERGLAND = "Mesmo na morte, essa fera causa dor.",
		SPIDERHAT = "Hora de fitar o abismo.",
		SPIDERQUEEN = "Ela é magnificente em sua horribilidade.",
		SPIDER_WARRIOR =
		{
			DEAD = "Oh, brava guerreira.",
			GENERIC = "Uma guerreira da noite!",
			SLEEPING = "Devo ter cuidado.",
		},
		SPOILED_FOOD = "Tudo vira lixo, no fim das contas.",
		STATUEHARP = "Talvez essas estátuas me façam companhia.",
		STATUEMAXWELL = "Ele me trouxe até aqui.",
		STEELWOOL = "Isso não oferece esperança de calor.",
		STINGER = "Afiado e mortal.",
		STRAWHAT = "Devo cobrir minha cabeça.",
		STUFFEDEGGPLANT = "Uma erva-moura. Provavelmente não está cheia de veneno.",
		SUNKBOAT = "Um truque cruel.",
		SWEATERVEST = "Posso vestir peças de coisas mortas em forma de colete!",
		TAFFY = "Nunca imaginei que pudesse fazer algo tão doce.",
		TALLBIRD = "Livre dos grilhões do céu.",
		TALLBIRDEGG = "Com tanto potencial.",
		TALLBIRDEGG_COOKED = "Todas as possibilidades se foram. Com bacon fica gostosinho.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Resfriado pela escuridão.",
			GENERIC = "Um ser pequeno e frágil, lutando pela luz.",
			HOT = "Não pode suportar o calor.",
			LONG = "Uma vida que começa mais cedo é uma vida que termina mais cedo.",
			SHORT = "Em breve, agora.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Esse ovo representa uma nova vida. Ugh.",
			PICKED = "O ninho está vazio. Desocupado. Deserto. Um vácuo.",
		},
		TEENBIRD =
		{
			GENERIC = "Você também vai me deixar?",
			HUNGRY = "Todos tentamos preencher o vazio.",
			STARVING = "Sua verdadeira natureza se revela!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Tenho certeza que o próximo mundo será ainda mais horrível!",
			GENERIC = "Nada de bom pode vir disso.",
			LOCKED = "Ainda está trancada.",
			PARTIAL = "Está semi-pronto, ou semi-destruído?",
		},
		TELEPORTATO_BOX = "Contém uma centelha vital.",
		TELEPORTATO_CRANK = "Parece complicado.",
		TELEPORTATO_POTATO = "Que criação horrenda!",
		TELEPORTATO_RING = "Não tem pontas afiadas.",
		TENTACLE = "Longo, fino e perigoso!",
		TENTACLESPOTS = "É melhor não falar desses.",
		TENTACLESPIKE = "Afiado, viscoso e perigoso.",
        TENTACLE_PILLAR = "Então é isso que rola lá embaixo.",
        TENTACLE_PILLAR_HOLE = "Voltará, algum dia.",
        TENTACLE_PILLAR_ARM = "Bebês!",
        TENTACLE_GARDEN = "Este é diferente.",
		TOPHAT = "Uma peça de refinamento para ajudar a esquecer a selva inescapável.",
		TORCH = "Um pequeno baluarte contra a noite.",
		TRAP = "Uma simples grama se tornou mortífera.",
		TRAP_TEETH = "Uma surpresa maligna do submundo.",
		TRAP_TEETH_MAXWELL = "A morte quando eu menos esperava.",
		TRINKET_1 = "Perfeitamente disforme.",
		TRINKET_10 = "Outra boca para alimentar.",
		TRINKET_11 = "Robô sortudo, nunca teve uma alma.",
		TRINKET_12 = "Não é mais tão viscoso, né?",
		TRINKET_2 = "É falsa. Apenas uma tentação, como a morte.",
		TRINKET_3 = "Se pelo menos facas resolvessem mais dos meus problemas...",
		TRINKET_4 = "Eu carregaria isso até o fim do mundo.",
		TRINKET_5 = "Eu voaria reto assim até o sol, se pelo menos ele fosse maior.",
		TRINKET_6 = "Uma vez viveram com eletricidade, mas chegaram ao fim.",
		TRINKET_7 = "Apenas um simples jogo.",
		TRINKET_8 = "Eu queria poder tomar um banho.",
		TRINKET_9 = "Botões errados para uma vida errada.",
		TRUNKVEST_SUMMER = "Pele para vestir sobre a minha pele.",
		TRUNKVEST_WINTER = "Pode aquecer meu corpo, mas e o meu espírito?",
		TRUNK_COOKED = "Está ainda pior agora.",
		TRUNK_SUMMER = "Eu teria preferido orelhas.",
		TRUNK_WINTER = "Separado de seu único amigo.",
		TURKEYDINNER = "Que está gorgolejando agora?",
		BANANAPOP = "Eu costumava comer isso com a Abigail...",
		BISQUE = "Alimenta o corpo, mata a alma de fome...",
		CEVICHE = "Tudo que saboreio é minha tristeza...",
		SEAFOODGUMBO = "Um mar que um dia abundava vida. Não mais.",
		SURFNTURF = "Poderia ser pior.",
		SHARKFINSOUP = "Provou de uma fuja mortal. Vou provar também.",
		LOBSTERDINNER = "Sua morte me dará vida.",
		LOBSTERBISQUE = "Eu gostaria de uma colher.",
		JELLYOPOP = "A morte vem para todos nós. Algumas vezes em uma vara.",
		CALIFORNIAROLL = "Sirelho, vestido com um casaco de alga marinha.",
		TWIGS = "Retirados do solo antes de seu auge.",
		UMBRELLA = "As nuvens choram.",
		WAFFLES = "Definitivamente são waffles.",
		WALL_HAY_ITEM = "Seu valor defensivo é questionável.",
		WALL_STONE = "O que me protegerá do que há lá dentro?",
		WALL_STONE_ITEM = "Elas não vão proteger dos demônios internos.",
		WALL_RUINS = "Elas não protegeram os antigos, protegeram?",
		WALL_RUINS_ITEM = "As próprias pedras são assombradas?",
		WALL_WOOD_ITEM = "Conjunto de toras.",
		WALL_MOONROCK = "A Lua... ela sussurra promessas de proteção para mim.",
		WALL_MOONROCK_ITEM = "Este presente dos céus não deve ser desperdiçado.",
		WALRUS = "Um velho do mar.",
		WALRUSHAT = "Que pensamentos febris ocorreram embaixo dele?",
		WALRUS_CAMP =
		{
			EMPTY = "Se eles não estiverem lá, onde estarão?",
			GENERIC = "Temo que essa casa não seja feliz.",
		},
		WALRUS_TUSK = "Tritura-lo-ei.",
		WARDROBE = 
		{
			GENERIC = "Me faz lembrar de uma história que eu costumava ouvir com a Abigail.",
            BURNING = "Logo não passará de cinzas.",
			BURNT = "Agora não me faz lembrar de nada.",
		},
		WARG = "Um verdadeiro bastião do mal.",
		WASPHIVE = "Eles se escondem em sua fortaleza de ódio.",
		WETGOOP = "Uma grande cagada, como a vida.",
		WHIP = "Ele só dá uma ilusão de controle.",
		WINTERHAT = "Ajuda a protelar o frio que se aproxima.",
		WORMHOLE =
		{
			GENERIC = "A vida nem sempre faz sentido.",
			OPEN = "Não importa o que consuma, nunca está satisfeito.",
		},
		ACCOMPLISHMENT_SHRINE = "Nunca dei muita bola para metáforas.",
		MOONROCKNUGGET = "Viajou tão longe...",
		ROCK_MOON = "Viajou tão longe...",



		------------------------------capy---------------------------------

		AERODYNAMICHAT = "Corto os ares!",
		ANTIVENOM = "Uma poção para evitar o enjoo.",
		ARMOR_LIFEJACKET = "Eu preferiria uma sepultura seca, obrigada.",
		ARMOR_SNAKESKIN = "Um casaco de carne morta. Chique.",
		ARMOR_WINDBREAKER = "As gavinhas do vento não podem me segurar!",
		ARMORLIMESTONE = "Pesada...",
		ARMOROBSIDIAN = "É sábio fazer uma veste com pedra de fogo?",
		ARMORSEASHELL = "Armadura feita de casas de meleca morta.",
		ARMOUREDBOAT = "Um barco que pode levar uma mordida ou duas.",
		BABYOX = "Olhos frios e distantes...",
		BALLPHIN = "Que carinha animado. Ele sabe que a vida não tem sentido?",
		BALLPHINPOD = "Nadar em casulos evita a solidão da existência?",
		BAMBOO = "Gravetos verdes... quem se importa...",
		BAMBOOTREE = "A long blade could part you from your life.",
		BERMUDATRIANGLE = "Uma energia sombria percorre esses portais misteriosos.",
		BERRYBUSH2_SNAKE = "Um lanchinho, quem sabe?",
		BERRYBUSH_SNAKE = "Um lanchinho, quem sabe?",
		BIOLUMINESCENCE = "A vida toma formas tão curiosas! Ainda assim a morte reivindica todas elas.",
		BLOWDART_POISON = "Enviando um desejo ruim com um sussurro.",
		BOAT_INDICATOR = "Where shall I launch my hopeless craft?",
		BOAT_LANTERN = "Para ver todo o vasto nada na escuridão da noite.",
		BOATCANNON = "Leva a morte ao alto mar!",
		BOATREPAIRKIT = "Isso poderia salvar um barco da destruição. E eu com ele.",
		BOTTLELANTERN = "A luz da vida. Aprisionada.",
		BURIEDTREASURE = "Coisas de pessoas mortas.",
		BUSH_VINE = "They look as if they want to choke something.",
		SNAKEDEN = "They look as if they want to choke something.",
		CAPTAINHAT = "Nenhuma alma viva comanda o mar...",
		CARGOBOAT = "Isso transporta mais porcarias para lugar nenhum.",
		CHIMINEA = "Isso deve proteger um fogo dos dedos aniquilantes do vento.",
		CIRCLINGSEAGULL = "Continue no ar, carne voadora. Não há nada digno de aterrissar.",
		CLOTHSAIL = "Com a vela nas mãos realizarei uma fuga rápida. Mas para onde?",
		COCONADE = "A coconut filled with hot, fiery death.",
		COCONUT = 
		{
		    GENERIC = "Que segredos essa fruta esconde sob sua proteção?",
		    PLANTED = "Eu esperava um segredo mais obscuro.",
		},
		COFFEE = "Escuro. Amargo...",
		COFFEEBEANS = "Esses parecem estimulantes.",
		
		COFFEEBUSH = "This plant takes nourishment from fiery death.",
		CORAL = "O mar dá vida a eles e ainda assim eles tentam fugir.",
		CORALREEF = "O coral cresce para fugir do mar.",
		CRAB = "There is soft meat beneath that hard shell.",
		CRABHOLE = "Um buraco é apenas uma sepultura que precisa ser coberta.",
		CUTLASS = "Não sentirá culpa com a morte. Não passa de uma ferramenta.",
		DEAD_SWORDFISH = "Sua cara de espada não pôde salvá-lo...",
		DEPLETED_BAMBOOTREE = "Se agarra à vida. Mal.",
		DEPLETED_BUSH_VINE = "As videiras estranguladoras foram elas mesmas estranguladas.",
		DOYDOY = "Esse pássaro parece muito idiota para estar vivo.",
		DOYDOYBABY = "Que fofo. E idiota.",
		DOYDOYEGG = "Que ovo idiota.",
		
		DOYDOYNEST = "Com cada um desses a ilha fica mais idiota. E carnuda.",
		DUBLOON = "A moeda dos marujos.",
		DUG_BAMBOOTREE = "Você secará ou viverá?",
		DUG_BUSH_VINE = "Plantar você de novo seria uma verdadeira crueldade.",
		DUG_COFFEEBUSH = "Querem voltar para a terra firme?",
		EARRING = "Mas sem orelha...",
		FABRIC = "Será que o bambu acha que essa nova forma é agradável?",
		FEATHERSAIL = "Esses pássaros idiotas realmente são ótimos para a navegação.",
		FIRERAIN = "Morte dos céus.",
		FIRERAINSHADOW = "Isso não deve ser bom.",
		FISHINHOLE = "A carne nada em círculos. Ignorante.",
		FROG_POISON = "Uma lambida venenosa disso e esse pesadelo terminará.",
		GASHAT = "Esse chapéu evita que eu respire na morte.",
		GOLDENMACHETE = "Que lâmina chique para arruinar bambu!",
		ICEMAKER = "My heart makes ice too.",
		IRONWIND = "Se eu tiver sorte, navegarei além dos confins da Terra.",
		JELLYFISH = "Como uma coisa tão curiosa pode viver?",
		JELLYFISH_COOKED = "É parecido com gelatina.",
		JELLYFISH_DEAD = "Foi uma morte sem dor. A fera não tinha sistema nervoso.",
		JELLYFISH_PLANTED = "O ferrão não é fatal. Apenas doloroso.",
		JELLYJERKY = "Tão... duro.",
		JUNGLETREESEED =
        {
            GENERIC = "É um pacote de potencial.",
            PLANTED = "Não há mais volta agora.",
        },
		LAVAPOOL = "Essa poça espuma com a fúria do vulcão!",
		LIMESTONE = "Quando o coral morre ele endurece, virando pedra.",
		LIMPETS = "Eles se alimentam da rocha. Eu me alimento deles.",
		
		LOBSTER = "Teria um gosto excelente morto e besuntado com manteiga.",
		LOBSTERHOLE = "Um jantar de lagosta vive aí.",
		LOGRAFT = "Isso parece pesado, lento e perigoso.",
		MACHETE = "Quanta lâmina!",
		MESSAGEBOTTLE = "O último ato desesperado de uma alma condenada. Em uma garrafa.",
		MESSAGEBOTTLEEMPTY = "Vazia. Como a minha alma.",
		MOSQUITO_POISON = "Como se um chupador de sangue não fosse baixo o suficiente, esse te deixa doente.",
		MUSSEL = "Você não pode se esconder sob as ondas, carne!",
		MUSSEL_STICK = "Os mexilhões grudam na vara. Idiotas.",
		OBSIDIAN = "Uma pedra forjada com fogo.",
		OBSIDIAN_WORKBENCH = "Ah, é aqui onde os itens de fogo são forjados.",
		OBSIDIANAXE = "Corta e queima.",
		OBSIDIANCOCONADE = "Os filhos da árvore destruirão o mundo.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Não desista, chaminha!",
			GENERIC = "Uma chama para controlar os horrores.",
			HIGH = "Esse fogo queima com paixão!",
			LOW = "Está perdendo a vontade de continuar!",
			NORMAL = "Queima com a raiva de seu criador.",
			OUT = "É melhor eu reacender isso.",
		},
		OBSIDIANMACHETE = "A lâmina morde e queima.",
		SPEAR_OBSIDIAN = "Golpeando com fogo.",
		OBSIDIANSPEARGUN = "Envio fogo com o puxar de um gatilho.",
		OX = "Você está pesado com carne. Deixe eu aliviar sua carga.",
		PACKIM = "Eu não confiaria um peixe a ele, mas talvez minhas porcarias...",
		PACKIM_FISHBONE = "Uma coisinha peixe morta. Parece importante.",
		PALMLEAF = "Aposto que essa folha está de luto por sua árvore derrubada.",
		PALMTREE =
		{
			BURNING = "Provavelmente devo recuar.",
			BURNT = "Ficou com um incrível tom de preto.",
			CHOPPED = "Que destruição maravilhosa.",
			GENERIC = "Suas frutas concedem vida, mas apenas seu eu matá-la.",
		},
		PALMTREE_BURNT = "Teve um fim flamejante.",
		PALMTREE_STUMP = "Seu tormento de árvore acabou-se.",
		PARROT = "São meus ouvidos ou a criatura emite um monólogo solitário?",
		PEACOCK = "Que penas lindas escondem uma carne saborosa!",
		PIRATEHAT = "Um chapéu de um corsário assassino. Admiro isso.",
		PIRATIHATITATOR = "This is but a step from madness.",
		POISONHOLE = "O solo arrota morte.",
		RAFT = "Quem sabe se eu usar isso sobre as ondas, me unirei a minha irmã?",
		ROWBOAT = "Quantas ligas isso pode me transmitir?",
		SAIL = "Domine o vento e voe para... lugar nenhum.",
		SAND = "Será que a areia sabe de sua própria insignificância?",
		SAND_CASTLE = "I suppose this diversion brings some comfort.",
		SANDBAG = "Eles controlam a ruina. Por um tempo...",
		SANDHILL = "Isso parece impermanente.",
		SEAGULL = "Os exploradores da terra e dos mares.",
		SEAGULL_WATER = "Como se não fosse ruim o suficiente que eles empesteiam o ar.",
		SEASACK = "Diminui a velocidade da podridão e decadência.",
		SEASHELL = "Seja lá o que vivia aqui provavelmente está morto agora.",
		SEATRAP = "Venham, criaturas do mar! Desfrutem de um lanche lindo!",
		SEAWEED = "Até mesmo o mar está infestado de capim.",
		
		SEAWEED_PLANTED = "Uma mato substancial.",
		SHARK_FIN = "Não vai mais precisar disso.",
		SHARX = "Terror dos mares!",
		SLOTMACHINE = "Ah, isso parece um teste sensato do destino.",
		SNAKE = "Desprovida de braços e pernas. Eu também estaria zangada.",
		SNAKE_FIRE = "As crianças do vulcão. Elas respiram seu fogo.",
		SNAKE_POISON = "A única coisa pior que uma cobra é uma cobra venenosa.",
		SNAKESKIN = "Perdeu a pele, com minha ajuda.",
		SNAKESKINHAT = "Um chapéu de troféus, arrancados dos mortos!",
		SOLOFISH = "Que nado gracioso. Que carne saborosa.",
		SPEAR_POISON = "Um golpe e vão golfar.",
		SPEARGUN = "Administra a morte à distância!",
		SPEARGUN_POISON = "Cada disparo inflige uma doença sufocante.",
		STUNGRAY = "Eles voam para fugir de sua própria horripilância.",
		SUPERTELESCOPE = "Eu consigo ver muito mais inutilidades.",
		SWORDFISH = "Esse peixe corta a morde com sua cara!",
		TELESCOPE = "Para ver até o horizonte com uma saudade pouco duradoura.",
		TIGERSHARK = "Morte com faixas laranja na água!",
		TIGERSHARKSHADOW = "Perigo!",
		TORNADO = "A fúria faminta da natureza!",
		TOUCAN = "Conta uma canção de tortura.",
		TRAWLNET = "Uma forma de retirar itens dos punhos do mar.",
		TRAWLNETDROPPED = "I wonder what this net pulled from the sea?",
		TRIDENT = "Os povos que forjaram isso estão mortos há muito tempo.",
		TRINKET_13 = "Talvez se eu bebesse isso eu retornaria para a minha irmã.",
		TRINKET_14 = "Se eu enfiasse uma agulha nesse boneco, quem sentiria?",
		TRINKET_15 = "Seja lá a quem isso pertenceu não anda mais.",
		TRINKET_16 = "Seja lá a quem isso pertenceu teve um fim horrível.",
		TRINKET_17 = "Seja lá quem usou isso certamente está morto.",
		TRINKET_18 = "Um remanescente de uma civilização perdida no mar.",
		TRINKET_19 = "O cérebro do dono certamente de anuviou para sempre agora.",
		TURBINE_BLADES = "Não giram mais.",
		TURF_BEACH = "Areia não serve bem para encher sepulturas.",
		TURF_JUNGLE = "Uma superfície nodosa e contorcida.",
		TWISTER = "A natureza está muito zangada!",
		VENOMGLAND = "Seus mortos liberam a cura de sua doença.",
		VINE = "Vida rebelde.",
		VOLCANO = "A montanha que cospe morte para os céus!",
		VOLCANO_ALTAR = "The will of the volcano flows through this shrine!",
		VOLCANO_ALTAR_BROKEN = "Que pena. Não há mais armas de fogo a forjar.",
		VOLCANO_EXIT = "Devo deixar este lugar de morte quente?",
		VOLCANOSTAFF = "O bafo chamejante do vulcão está sob meu comando!",
		WALL_LIMESTONE = "Uma parede dos mortos para repelir os vivos.",
		WALL_LIMESTONE_ITEM = "Uma parede feita de corais vivos... Não mais.",
		WHALE_BLUE = "Parece triste.",
		WHALE_CARCASS_BLUE = "Algo tão grande e morto certamente vai feder.",
		WHALE_CARCASS_WHITE = "É muito grande e está muito morta.",
		WHALE_WHITE = "Há o ódio pela vida em seus olhos chamejantes!",
		WOODLEGS_CAGE = "Pelo menos sua alma fugiu.",
		VOLCANO_SHRUB = "Apenas uma sombra miserável de sua forma passada.",
		ROCK_OBSIDIAN = "Você queima quando tocada?",
		ROCK_CHARCOAL = "Não sei dizer o que você costumava ser.",
		DRAGOONDEN = "Corações cruéis habitam o interior.",

		ARMORCACTUS = "Me torna tão espinhosa por fora quanto sou por dentro!",
		BAMBOOTREE =
		{
			BURNT = "Assim vai.",
			CHOPPED = "Venci esse round.",
			GENERIC = "Posso curvá-lo à minha vontade.",
		},
		BEEMINE_MAXWELL = "As criaturas furiosas lá dentro apreciam sua liberdade em retrospecto.",
		BIGFISHINGROD = "Estejam avisadas, criaturas do mar. A morte está vindo.",
		BLOWDART_FLUP = "Agora quando eu der um olhar para alguém terá efeito!",
		BLUBBER = "A refeição perfeita para um tolo gordurento.",
		BLUBBERSUIT = "Perturbador, mas aconchegante.",
		BOAT = "É um barco.",
		BOAT_TORCH = "Que esclarecedor.",
		BRAINJELLYHAT = "Assim meu cérebro parece grande?",
		BUOY = "Continue a flutuar, amiguinho.",
		BUSH_VINE =
		{
			BURNT = "Acho que fica melhor assim.",
			CHOPPED = "Seu sacrifício não será em vão.",
			GENERIC = "É bem bonita.",
		},
		COCONADE =
		{
			BURNING = "Abaixem-se!",
			GENERIC = "Seguro a morte explosiva de alguém nas minhas mãos.",
		},
		COCONUT_COOKED = "É um docinho.",
		COCONUT_HALVED = "Duas metades que eram um inteiro. Onde você está agora, Abigail?",
		COFFEEBEANS_COOKED = "Quem pensaria que a vontade de viver vinha em forma de grão?",
		COFFEEBOT = "Gosto do meu preto.",
		COFFEEBUSH =
		{
			BARREN = "Um estimulante seria útil.",
			GENERIC = "Um presente granulento dos céus.",
			PICKED = "Todas as feridas saram com o tempo, pequeno arbusto.",
			WITHERED = "Sinto o mesmo.",
		},
		COMPASS =
		{
			E = "Leste.",
			GENERIC = "Estou sem direção.",
			N = "Norte.",
			NE = "Nordeste.",
			NW = "Noroeste.",
			S = "Norte. Não, espere, sul.",
			SE = "Sudeste.",
			SW = "Sudoeste.",
			W = "Oeste.",
		},
		CORAL_BRAIN = "É assim que sou por dentro?",
		CORAL_BRAIN_ROCK = "Essa planta parece inteligente.",
		CRAB =
		{
			GENERIC = "Essa ilha tem uma infestação de crustáceos.",
			HIDDEN = "Você não pode ser esconder de seus problemas para sempre. Eu tentei.",
		},
		CRATE = "É só uma caixa.",
		DEPLETED_GRASS_WATER = "Já era.",
		DEVTOOL = "Tem um cheiro forte.",
		DEVTOOL_NODEV = "Não posso usar isso.",
		DIVININGRODSTART = "Eu poderia usar isso.",
		DOUBLE_UMBRELLAHAT = "Isso parece exagerado.",
		DOYDOYEGG_COOKED = "Ainda não está extinto, não por falta de tentativa.",
		DOYDOYEGG_CRACKED = "Talvez isso seja piedade.",
		DOYDOYFEATHER = "Uma mancha de cor em um mundo melancólico.",
		DRAGOON = "Daria um ótimo bichinho de estimação, se não fosse por toda a coisa de \"assassinatos\".",
		DRAGOONEGG = "Difícil imaginar que isso daria à luz a um monstro tão horrível.",
		DRAGOONHEART = "Esse coração está tão morto quando o meu, embora esteja mais quente.",
		DRAGOONSPIT = "Eca!",
		DUG_ELEPHANTCACTUS = "Preciso carregar isso?",
		ELEPHANTCACTUS = "É triste e doloroso.",
		ELEPHANTCACTUS_ACTIVE = "Essa planta não quer que ninguém toque nela.",
		ELEPHANTCACTUS_STUMP = "Está se escondendo no subsolo.",
		FIREPIT =
		{
			EMBERS = "Não desista, chaminha!",
			GENERIC = "Uma chama para controlar os horrores.",
			HIGH = "Esse fogo queima com paixão!",
			LOW = "Está perdendo a vontade de continuar!",
			NORMAL = "É um conforto.",
			OUT = "É melhor eu reacender isso.",
		},
		FISH_RAW = "Foi decapitado.",
		FISH_RAW_SMALL = "Há outros peixes no mar. Maiores, espero.",
		FISH_RAW_SMALL_COOKED = "Vai me satisfazer... por enquanto.",
		FLAMEGEYSER = "Quente!",
		FLOTSAM = "Não consigo alcançar direito.",
		FLUP = "São muitos olhos!",
		FRESHFRUITCREPES = "Pode trazer um desses com chantili?",
		GRASS_WATER = "Úmido.",
		HAIL_ICE = "Congelada como meu coração.",
		HOME = "Não é exatamente material para uma cerca de madeira.",
		HOUNDFIRE = "Queima!",
		ICEMAKER =
		{
			HIGH = "Está em ótima forma.",
			LOW = "Parece meio deprimido.",
			NORMAL = "Está se sentindo bem.",
			OUT = "Desistiu.",
			VERYLOW = "Está quase sem combustível.",
		},
		JUNGLETREE =
		{
			BURNING = "Provavelmente devo recuar.",
			BURNT = "Ficou com um incrível tom de preto.",
			CHOPPED = "Que destruição maravilhosa.",
			GENERIC = "Uma árvore florestal.",
		},
		KNIGHTBOAT = "Essa coisa tem problemas com raiva!",
		KRAKEN = "Ajoelhe-se aos meus pés, fera medonha!",
		KRAKENCHEST = "Que maravilhas existem lá dentro?",
		KRAKEN_TENTACLE = "Oh, céus, Quacken diria que eu me surpreenderia?",
		LIMPETROCK =
		{
			GENERIC = "Parece comestível... mais ou menos.",
			PICKED = "Colhi tudo.",
		},
		LIVINGJUNGLETREE = "Essa árvore modesta tem a exata aparência de como me sinto.",
		LOBSTER_DEAD = "Foi encontrar seu criador. Encontrei meu almoço.",
		LOBSTER_DEAD_COOKED = "É um banquete!",
		LOG =
		{
			BURNING = "É só um tronco queimando.",
			GENERIC = "É só um tronco.",
		},
		LUGGAGECHEST = "Um sistema de armazenamento de itens muito elegante.",
		MAGIC_SEAL = "Pulsa com uma força desconhecida.",
		MAGMAROCK = "Os intestinos da Terra, frios e prontos para mineração.",
		MAGMAROCK_FULL = "Os intestinos da Terra, frios e prontos para mineração.",
		MAGMAROCK_GOLD = "Os intestinos da Terra, frios e prontos para mineração.",
		MAGMAROCK_GOLD_FULL = "Os intestinos da Terra, frios e prontos para mineração.",
		MANDRAKE_COOKED = "Agora é só comida.",
		MANGROVETREE = "É bem elegante.",
		MANGROVETREE_BURNT = "Uma grande pena.",
		MARSH_PLANT_TROPICAL = "Que broto patético.",
		MERMFISHER = "Admiro o comprometimento dessa criatura ao canibalismo.",
		MERMHOUSE_FISHER = "Que singular.",
		MONKEYBALL = "Assim me sinto menos sozinha. E posso arremessá-la também.",
		MONSTERTARTARE = "A aparência é bonita, o gosto, horrível.",
		MOSQUITOSACK_YELLOW = "Que lindo tom de amarelo vômito.",
		MUSSELBOUILLABAISE = "Estou com água na boca só de olhar.",
		MUSSEL_COOKED = "Com certeza superei esse mexilhão.",
		MUSSEL_FARM =
		{
			GENERIC = "Não parecem tão duros para mim.",
			STICKPLANTED = "Ha!",
		},
		MYSTERYMEAT = "Isso é grotesco.",
		NEEDLESPEAR = "É possível terminar tudo com isso.",
		OCTOPUSCHEST = "Esse não parece um lugar confiável para guardar coisas.",
		OCTOPUSKING = "Invejo seu contentamento.",
		OXHAT = "Encantador.",
		OX_FLUTE = "Que eu possa tocar uma canção para acalmar meu coração perturbado.",
		OX_HORN = "Foi decepado de seu dono.",
		PALMLEAF_HUT = "Um descanso bem-vindo.",
		PARROT_PIRATE = "Se eu sussurrasse meus segredos a ele, contaria a alguém?",
		PEG_LEG = "Mas onde está o resto da pessoa de pau?",
		PIGTENT = "O lugar onde eles enrolam porcos em lençóis.",
		PIKE_SKULL = "Acho que escolheu \"não ser\".",
		PIRATEGHOST = "Um futuro amigo da Abigail?",
		PIRATEPACK = "Isso deve me ajudar a carregar mais porcarias.",
		PIRATIHATITATOR =
		{
			BURNT = "Seja o que for, agora está queimado.",
			GENERIC = "Não sei o que é isso.",
		},
		PORTAL_SHIPWRECKED = "Como minha amada irmã, nunca posso voltar.",
		PRIMEAPE = "Sua jovialidade é quase cativante. Quase.",
		PRIMEAPEBARREL = "Parece sujo.",
		RAWLING = "Está falando comigo.",
		REDBARREL = "Essa é uma ameaça à segurança. Ótimo!",
		RUBBLE = "Essa pedra destroçada é inútil.",
		SAIL_STICK = "É... uma vara.",
		SANDBAGSMALL = "Densa e pesada.",
		SANDBAGSMALL_ITEM = "Um saco de terra que posso carregar.",
		SANDBAG_ITEM = "Parece uma lesão nas costas prestes a acontecer.",
		SAND_CASTLE =
		{
			GENERIC = "Sua beleza sem dúvidas sucumbirá à maré.",
			SAND = "Se pelo menos moldar as areias do tempo fosse tão fácil.",
		},
		SEASHELL_BEACHED = "Conchas, com chás... no original também não faz sentido.",
		SEAWEED_COOKED = "Melhor, mas ainda é mato.",
		SEAWEED_DRIED = "Conserva mais tempo assim. Também é mais saborosa.",
		SHADOWSKITTISH_WATER = "Nossa!",
		SHARKITTEN = "Eu poderia ficar velha em uma casa cheia desses.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Estou sentindo cheiro... de fezes de gato?",
			INACTIVE = "Um montinho de areia considerável.",
		},
		SHARK_GILLS = "Ninguém vai respirar por isso agora.",
		SHARK_TEETHHAT = "Chique, mas aterrorizante.",
		SHIPWRECKED_ENTRANCE = "Curioso, muito curioso.",
		SHIPWRECKED_EXIT = "Avante para a próxima aventura.",
		SLURPERPELT = "Um saco vazio de fome.",
		SNAKEDEN =
		{
			BURNT = "Acho que fica melhor assim.",
			CHOPPED = "Seu sacrifício não será em vão.",
			GENERIC = "É bem bonita.",
		},
		SNAKEOIL = "Isso me enche com uma sensação de desconfiança.",
		SNAKESKINSAIL = "Nojento, mas eficiente.",
		SPEAR_LAUNCHER = "Por que arremessar uma lança quando pode lançá-la?",
		SPOILED_FISH = "Adeus, companheiro.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Você está completamente só?",
			GENERIC = "Oh, as histórias que esse navio poderia contar.",
		},
		SUNKEN_BOAT_BURNT = "Um fim poético.",
		SUNKEN_BOAT_TRINKET_1 = "Vou usar como peso de papel.",
		SUNKEN_BOAT_TRINKET_2 = "Que tipo de mente simplória se entreteria com isso?",
		SUNKEN_BOAT_TRINKET_3 = "Está completamente ensopado.",
		SUNKEN_BOAT_TRINKET_4 = "Não faço ideia do que é isso.",
		SUNKEN_BOAT_TRINKET_5 = "Que clichê.",
		SWEETPOTATOSOUFFLE = "Delicado, mas delicioso.",
		SWEET_POTATO = "Doce. Como eu.",
		SWEET_POTATO_COOKED = "Se pelo menos meu desespero tivesse um gosto tão bom.",
		SWEET_POTATO_PLANTED = "Isso parece almoço.",
		SWEET_POTATO_SEEDS = "Talvez estas possam dar nova vida.",
		SWIMMINGHORROR = "Quero ficar distante disso!",
		TELEPORTATO_SW_BASE = "Está faltando alguma coisa.",
		TELEPORTATO_SW_BOX = "Parece meio borrachento.",
		TELEPORTATO_SW_CRANK = "Parece incompleto.",
		TREEGUARD = "Oh... não...",
		TELEPORTATO_SW_POTATO = "Que possível uso isso poderia ter?",
		TELEPORTATO_SW_RING = "Esse anel provavelmente não serve para usar.",
		THATCHPACK = "Meu destino sempre foi carregar um fardo pesado.",
		TIDALPOOL = "Quando observo essa poça límpida, sonho que posso ver Abigail.",
		TIDAL_PLANT = "É afiada.",
		TIGEREYE = "Tigre, tigre, brilhando intensamente...",
		TRAWLNETDROPPED =
		{
			GENERIC = "Que criaturas isso vai retirar do oceano?",
			SOON = "Sua jornada está quase no fim.",
			SOONISH = "Iniciou sua jornada nas profundezas.",
		},
		TREASURECHEST_TRAP = "Às vezes, as coisas me favorecem.",
		TREECLUMP = "Isso foi colocado intencionalmente.",
		TRINKET_20 = "Vou usar como peso de papel.",
		TRINKET_21 = "Que tipo de mente simplória se entreteria com isso?",
		TRINKET_22 = "Muito DIY.",
		TRINKET_23 = "Que pena.",
		TROPICAL_FISH = "É ofensivamente brilhante.",
		TUNACAN = "Isso é simplesmente propaganda falsa.",
		TURF_ASH = "É só terra.",
		TURF_DESERTDIRT = "É só terra.",
		TURF_FUNGUS_GREEN = "É só terra.",
		TURF_FUNGUS_RED = "É só terra.",
		TURF_MAGMAFIELD = "É só terra.",
		TURF_MEADOW = "É só terra.",
		TURF_SNAKESKINFLOOR = "É só terra.",
		TURF_SWAMP = "É só terra.",
		TURF_TIDALMARSH = "É só terra.",
		TURF_VOLCANO = "É só terra.",
		TWISTER_SEAL = "Não tem qualquer consciência dos males do mundo.",
		VOLCANO_ALTAR =
		{
			GENERIC = "Não está aberto.",
			OPEN = "Que o sacrifício comece!",
		},
		VOLCANO_ALTAR_TOWER = "Um lindo altar da morte.",
		WALLYINTRO_DEBRIS = "O navio foi obliterado.",
		WATERMELON_SEEDS = "Com a forma perfeita para cuspir.",
		WATERYGRAVE = "Poderia roubar uma sepultura.",
		WHALE_BUBBLES = "Parece um peixe com problemas de gases.",
		WHALE_TRACK = "Baleia, oh!",
		WILBUR_CROWN = "Os monarcas devem ter cabeças pequenas.",
		WILBUR_UNLOCK = "Sua fineza não adianta nada para disfarçar o cheiro.",
		WILDBORE = "Por que está zangado?",
		WILDBOREHEAD = "Que decoração linda.",
		WILDBOREHOUSE = "Espero que não me convidem para entrar.",
		WIND_CONCH = "Uma força aterrorizante da natureza contida em uma concha delicada.",
		WOODLEGSBOAT = "Uma embarcação preparada para o mar, se um dia houve uma!",
		WOODLEGSHAT = "Alta costura pirática.",
		WOODLEGSSAIL = "Adoro o design.",
		WOODLEGS_KEY1 = "Que alma desafortunada doou seus ossos para isso?",
		WOODLEGS_KEY2 = "Provavelmente destranca algo extravagante.",
		WOODLEGS_KEY3 = "O que você abre?",
		WORMHOLE_LIMITED = "Está parecendo oprimido.",
		WRECK = "Sua tripulação provavelmente está morta...",
	},
	DESCRIBE_GENERIC = "É imencionável.",
	DESCRIBE_TOODARK = "A escuridão! É escura demais!",
	DESCRIBE_SMOLDERING = "Está prestes a ser engolido pelas chamas.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Nem mesmo conseguiu ver o mundo.",
	},
}
