return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Vou tosquiá-lo quando dormir.",
			GENERIC = "Indigno de raspagem.",
			NOBITS = "Mas não há nada para cortar!",
		},
		STORE =
		{
			GENERIC = "Já está repleto de objetos.",
			NOTALLOWED = "Temo que isso não vá aí.",
		},
		RUMMAGE =
        {   
            GENERIC = "Se eu não posso fazer, é impossível!",   
        },
		COOK =
        {
            GENERIC = "Como?! Superada por equipamentos de cozinha!",
            TOOFAR = "Preciso acabar com a diferença entre nós!",
        },
        WRITE =
        {
            GENERIC = "Temo que não possa!",
        },
        GIVE =
        {
            DEAD = "Eles terão coisas melhores em Valhalla.",
            SLEEPING = "Que sono lindo... Talvez mais tarde.",
            BUSY = "Vou tentar mais uma vez quando estiver pronto.",
        },
        CHANGEIN =
        {
            GENERIC = "É aí que guardo todas minhas peles e couros favoritos.",
            BURNING = "Ufa! Minhas peles!",
        },
        TEACH =
        {
            KNOWN = "Já detenho tanto conhecimento.",
            CANTLEARN = "Esse conhecimento é proibido pelos deuses.",
        },
		REPAIRBOAT =
		{
			GENERIC = "Minha embarcação foi renovada!",
		},
	},
	ACTIONFAIL_GENERIC = "Se eu não posso fazer, é impossível!",
	ANNOUNCE_MAGIC_FAIL = "Suas magias se enfraqueceram!",
	ANNOUNCE_ADVENTUREFAIL = "De volta ao Além. A vitória será minha!",
	ANNOUNCE_BEES = "Para trás, criaturinhas pontiagudas!",
	ANNOUNCE_BOOMERANG = "Ugh! Preciso dominar a arma curvada.",
	ANNOUNCE_CHARLIE = "Revele-se!",
	ANNOUNCE_CHARLIE_ATTACK = "Covarde!",
	ANNOUNCE_COLD = "Brrr! Onde estão minhas peles?",
	ANNOUNCE_HOT = "O sol quente me cansa.",
	ANNOUNCE_CRAFTING_FAIL = "Não disponho das provisões necessárias.",
	ANNOUNCE_DEERCLOPS = "Um adversário digno se aproxima!",
	ANNOUNCE_DUSK = "O sol está se pondo. A escuridão aguarda por perto.",
	ANNOUNCE_EAT =
	{
		GENERIC = "A carne faz meu coração cantar!",
		PAINFUL = "Oh, não me sinto bem.",
		SPOILED = "Ugh. Fresco ficaria melhor.",
		STALE = "Essa fera estava podre.",
		INVALID = "Esse não é um alimento digno de uma guerreira.",
		YUCKY = "Esse alimento não é digno de uma guerreira.",
	},
	ANNOUNCE_ENTER_DARK = "E a cortina desce.",
	ANNOUNCE_ENTER_LIGHT = "Adentrei a luz!",
	ANNOUNCE_FREEDOM = "Liberdade! A saga continua!",
	ANNOUNCE_HIGHRESEARCH = "Sou uma ótima artesã.",
	ANNOUNCE_HOUNDS = "As feras estão se aproximando...",
	ANNOUNCE_HUNGRY = "Como desejo um banquete!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Shh... A criatura está perto.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Perdi o rastro.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Está muito enlameado para seguir rastros.",
	ANNOUNCE_INV_FULL = "Estou carregando tudo o que posso.",
	ANNOUNCE_KNOCKEDOUT = "Ugh, minha cabeça.",
	ANNOUNCE_LOWRESEARCH = "Isso não foi muito empolgante.",
	ANNOUNCE_MOSQUITOS = "Afastem-se, demoninhos!",
	ANNOUNCE_NODANGERSLEEP = "Não é seguro dormir. Use a lança!",
	ANNOUNCE_NODAYSLEEP = "O sol está alto, continuar jornada!",
	ANNOUNCE_NODAYSLEEP_CAVE = "Ainda não descansarei.",
	ANNOUNCE_NOHUNGERSLEEP = "Morrerei de fome durante a noite! Primeiro o banquete!",
	ANNOUNCE_NOSLEEPONFIRE = "Não dormirei nas chamas.",
	ANNOUNCE_NODANGERSIESTA = "A batalha está próxima, não haverá descanso!",
	ANNOUNCE_NONIGHTSIESTA = "Sem cochilo na luz da lua.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Esse não parece um bom momento para um cochilo.",
	ANNOUNCE_NOHUNGERSIESTA = "Gostaria de um lanche com carne primeiro.",
	ANNOUNCE_NO_TRAP = "Felizmente, meus passos são leves.",
	ANNOUNCE_PECKED = "Afaste-se, bicudo ousado!",
	ANNOUNCE_QUAKE = "O mundo treme!",
	ANNOUNCE_RESEARCH = "O poder do conhecimento é lindo.",
	ANNOUNCE_SHELTER = "Arrá! Abrigo!",
	ANNOUNCE_THORNS = "Argh, fui espetada!",
	ANNOUNCE_TORCH_OUT = "Minha luz se extinguiu!",
	ANNOUNCE_TRAP_WENT_OFF = "Isso não fazia parte do plano.",
	ANNOUNCE_UNIMPLEMENTED = "Não é deste mundo.",
	ANNOUNCE_WORMHOLE = "Essa foi uma aventura desleixada.",
	ANNOUNCE_CANFIX = "\nPosso consertar isso.",
	ANNOUNCE_FAN_OUT = "Perdi outro leque!",
	ANNOUNCE_ACCOMPLISHMENT = "Posso retornar para a batalha agora?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Vitória! Tudo bem, vamos.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Mais dejetos para você?",
	ANNOUNCE_TOOL_SLIP = "Diabinho escorregadio!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Viajei em um relâmpago.",

	ANNOUNCE_DAMP = "Escorregadio para a batalha.",
	ANNOUNCE_WET = "Sou uma guerreira molhada.",
	ANNOUNCE_WETTER = "Isso conta como banho?",
	ANNOUNCE_SOAKED = "Estou quase encharcada.",
	
	ANNOUNCE_OTHER_WORLD_PLANT = "Uma planta dessas nunca sobreviveria neste reino!",

	ANNOUNCE_BOAT_DAMAGED = "Minha embarcação foi ferida!",
	ANNOUNCE_BOAT_SINKING = "O mar me puxa em direção a Hel!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Essas profundezas negras logo me chamarão!",
	ANNOUNCE_BURNT = "Uhuu!",
	ANNOUNCE_CRAB_ESCAPE = "Sumiu!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "As correntes são meu mestre!",
	ANNOUNCE_MAPWRAP_RETURN = "Emergi da neblina!",
	ANNOUNCE_MAPWRAP_WARN = "Eu havia chegado aos confins do mundo!",
	ANNOUNCE_MORETREASURE = "Este dia sorri para mim!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Este mapa descreve outra terra.",
	ANNOUNCE_SHARX = "Inimigos da escuma!",
	ANNOUNCE_TRAWL_FULL = "Minha rede encheu-se de espólios maravilhosos.",
	ANNOUNCE_TREASURE = "O mapa fala de um tesouro!",
	ANNOUNCE_VOLCANO_ERUPT = "Ragnarok chegou?",
	ANNOUNCE_WAVE_BOOST = "Me leve adiante!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Uma fera espreita sob as ondas...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Perdi o rastro da fera.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Não posso ler essas águas agitadas.",

	BATTLECRY =
	{
		GENERIC = "Valhalla me espera!",
		PIG = "Vou comer porco esta noite!",
		PREY = "Morra com bravura, fraco adversário!",
		SPIDER = "Aranha, sinta minha lança!",
		SPIDER_WARRIOR = "Prepare-se para ser destroçado!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Odin te derrotará em breve!",
		PIG = "Voltarei, pele de porco!",
		PREY = "Vou te deixar ir desta vez!",
		SPIDER = "Covarde pernuda.",
		SPIDER_WARRIOR = "Fuja, monstro! Voltarei.",
	},

	DESCRIBE =
	{		
		BIGFISHINGROD = "Vou prender essa carne de peixe deliciosa.",
		BIGFOOT = "Isso é algo completamente diferente!",
		COFFEEBOT = "A melhor máquina sob o sol.",
		DEPLETED_GRASS_WATER = "Foi totalmente subjugada.",
		HOUNDFIRE = "Queima com um paixão eterna!",
		INVENTORYGRAVE = "Vejo você em Valhalla!",
		INVENTORYMOUND = "Vejo você em Valhalla!",
		LIMPETS_COOKED = "Vamos ao banquete!",
		WOODLEGSBOAT = "Eu preferiria um drácar.",
		WOODLEGSHAT = "Nem se compara a meu elmo.",
		WOODLEGSSAIL = "Uma folha temível.",
		GLOMMER = "Um bacana majestoso.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Uma maravilha da floresta.",
        	DEAD = "Um dia foi uma maravilha da floresta.",
        },
        GLOMMERWINGS = "Oh, olhe o que o bacana me deixou.",
        GLOMMERFUEL = "Essa meleca poderia ser útil.",
        BELL = "Prefiro a ressonância do tilintar das espadas.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Uma homenagem curiosa aos deuses.",
        	EMPTY = "Isso não foi muito respeitoso para mim.",
        },

		WEBBERSKULL = "Ele lutou corajosamente, mas seu enterro não será o de um viquingue.",
		WORMLIGHT = "Tesouro incandescente, não consigo resistir!",
		WORMLIGHT_LESSER = "Brilhe! Brilhe com toda a sua força!",
		WORM =
		{
		    PLANT = "Sinto cheiro de armadilha.",
		    DIRT = "O que está sob a terra?",
		    WORM = "Uma fera cobra das profundezas!",
		},
		WORMLIGHT_PLANT = "Sinto cheiro de armadilha.",
		MOLE =
		{
			HELD = "Um amigo para o meu bolso.",
			UNDERGROUND = "Quem está aí embaixo?",
			ABOVEGROUND = "Ele se enterra com uma despreocupação imprudente.",
		},
		MOLEHILL = "Algo maligno vive lá embaixo.",
		MOLEHAT = "É melhor usar todas as partes do animal.",

		EEL = "Peixe-cobra gosmento delicioso.",
		EEL_COOKED = "Enguia quente!",
		UNAGI = "Não há necessidade de a comida ser atraente.",
		EYETURRET = "O olho do deus do laser observa minha alma.",
		EYETURRET_ITEM = "Um olho de proteção ancestral!",
		MINOTAURHORN = "Posso colocar isso no meu elmo?",
		MINOTAURCHEST = "O baú da conquista!",
		THULECITE_PIECES = "Parece milho estourado brilhante.",
		POND_ALGAE = "Uma flora ancestral.",
		GREENSTAFF = "Energia verde rodopiante.",
		POTTEDFERN = "O que devo fazer com tal coisa?",

		THULECITE = "Esse material tem uma força imensa!",
		ARMORRUINS = "Armadura digna do próprio Odin!",
		RUINS_BAT = "Uma varinha de guerreiro!",
		RUINSHAT = "Uma coroa, que luta!",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Nothing stirs.",
			WARN = "It's starting...",
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			NOMAGIC = "The magic slumbers far from here.",
		},
		BISHOP_NIGHTMARE = "Cuidado com seus raios!",
		ROOK_NIGHTMARE = "Você não me assusta!",
		KNIGHT_NIGHTMARE = "Não acho que eu montaria esse cavalo.",
		MINOTAUR = "Que maravilhas. Vamos duelar!",
		SPIDER_DROPPER = "Você é tão traiçoeira!",
		NIGHTMARELIGHT = "Controla os poderes sombrios do subterrâneo.",
		NIGHTSTICK = "Uma arma digna de Thor.",
		GREENGEM = "Uma pedra de esmeralda.",
		RELIC = "Old bits of a dwelling.",
		RUINS_RUBBLE = "I'm quite crafty. I could repair that.",
		MULTITOOL_AXE_PICKAXE = "Uma ferramenta de guerreiro!",
		ORANGESTAFF = "Um cajado de movimento mágico.",
		YELLOWAMULET = "Uma estrela capturada em um amuleto.",
		GREENAMULET = "Habilidades de criação de esmeraldas aprimoradas!",
		SLURPERPELT = "I do love furs.",	

		SLURPER = "O adversário peludo acha que é um chapéu!",
		SLURPER_PELT = "Realmente amo peles.",
		SLURPERPELT = "Realmente amo peles.",
		ARMORSLURPER = "Ela reduz a dor ada fome. Boa pele.",
		ORANGEAMULET = "A coleta nunca foi tão fácil.",
		YELLOWSTAFF = "Invoca as estrelas!",
		YELLOWGEM = "Uma beleza amarela.",
		ORANGEGEM = "Uma pedra alaranjada.",
		TELEBASE = 
		{
			VALID = "Prepare yourselves for the power of purple!",
			GEMS = "There's still gems missing.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "It's empty.",
		},
		STAFFLIGHT = "Vejam! Um presente de Wotan!",
	
        ANCIENT_ALTAR = "É melhor que seja bons.",

        ANCIENT_ALTAR_BROKEN = "Esse não está funcionando direito.",

        ANCIENT_STATUE = "Um tesouro com uma aura misteriosa.",

        LICHEN = "Planta sem sentido azul-céu.",
		CUTLICHEN = "Colhi. Mas não vou comer.",

		CAVE_BANANA = "Comida de macaco.",
		CAVE_BANANA_COOKED = "Comida de macaco aquecida.",
		CAVE_BANANA_TREE = "Uma árvore de macaco fraca.",
		ROCKY = "Ele pode ser um companheiro de combate digno.",
		
		COMPASS =
		{
			GENERIC= "Uma leitura não pode ser visualizada.",
			N = "Norte.",
			S = "Sul.",
			E = "Leste.",
			W = "Oeste.",
			NE = "Nordeste.",
			SE = "Sudeste.",
			NW = "Noroeste.",
			SW = "Sudoeste.",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "A magia está ganhando força!",
			STEADY = "A magia possui poder controlado.",
			WANING = "Está começando a recuar!",
			DAWN = "Quase nenhuma magia resta.",
			WARN = "Está começando...",
			CALM = "Nada se agita.",
			NOMAGIC = "A magia descansa longe daqui.",
		},

		HOUNDSTOOTH="Um símbolo de minha conquista.",
		ARMORSNURTLESHELL="Um tipo de escudo.",
		BAT="Carne alada escura.",
		BATBAT = "Winged spear!",
		BATWING="Como as asas de meu elmo, mas um pouco mais carnudas.",
		BATWING_COOKED="Asa negra cozida.",
		BEDROLL_FURRY="Uma cama de pele luxuosa!",
		BUNNYMAN="Vou comer você.",
		FLOWER_CAVE="E iluminou a noite, na hora mais escura.",
		FLOWER_CAVE_DOUBLE="E iluminou a noite, na hora mais escura.",
		FLOWER_CAVE_TRIPLE="E iluminou a noite, na hora mais escura.",
		GUANO="Hmm, excrementos alados escuros.",
		LANTERN="Um lampião para a escuridão.",
		LIGHTBULB="Brilhe!",
		MANRABBIT_TAIL="O troféu peludo de uma batalha bem-sucedida.",
		MUSHTREE_TALL  ="Que magia é essa?",
		MUSHTREE_MEDIUM="Realmente gosto de seu brilho.",
		MUSHTREE_SMALL ="Não me importo com cogumelos.",
		RABBITHOUSE=
		{
			GENERIC = "O que farei com uma cenoura tão grande?",
			BURNT = "Adeus, cenoura gigante.",
		},
		SLURTLE="Você é um anjo. Do mau.",
		SLURTLE_SHELLPIECES="Eles foram bem destruidinhos.",
		SLURTLEHAT="Um novo elmo de batalha para a minha coleção!",
		SLURTLEHOLE="Eu não escolheria pendurar meu elmo aí.",
		SLURTLESLIME="Sim. Meleca.",
		SNURTLE="Gosto de seu elmo!",
		SPIDER_HIDER="Te esmagarei!",
		SPIDER_SPITTER="Essa é ousada.",
		SPIDERHOLE="Teias. Nunca é um bom sinal.",
		STALAGMITE="Uma rocha de caverna.",
		STALAGMITE_FULL="Uma rocha de caverna.",
		STALAGMITE_LOW="Uma rocha de caverna.",
		STALAGMITE_MED="Uma rocha de caverna.",
		STALAGMITE_TALL="Um tipo de pedra pontiaguda.",
		STALAGMITE_TALL_FULL="Um tipo de pedra pontiaguda.",
		STALAGMITE_TALL_LOW="Um tipo de pedra pontiaguda.",
		STALAGMITE_TALL_MED="Um tipo de pedra pontiaguda.",

		TURF_CARPETFLOOR = "Suga o sangue da batalha.",
		TURF_CHECKERFLOOR = "Chão chique.",
		TURF_DIRT = "Uma parte do campo de batalha.",
		TURF_FOREST = "Uma parte do campo de batalha.",
		TURF_GRASS = "Uma parte do campo de batalha.",
		TURF_MARSH = "Uma parte do campo de batalha.",
		TURF_ROAD = "A estrada para a batalha leva aonde eu escolher.",
		TURF_ROCKY = "Uma parte do campo de batalha.",
		TURF_SAVANNA = "Uma parte do campo de batalha.",
		TURF_WOODFLOOR = "Piso de madeira, uma ótima superfície para combates mortais.",

		TURF_CAVE="Uma parte do campo de batalha.",
		TURF_FUNGUS="Uma parte do campo de batalha.",
		TURF_SINKHOLE="Uma parte do campo de batalha.",
		TURF_UNDERROCK="Uma parte do campo de batalha.",
		TURF_MUD="Uma parte do campo de batalha.",

		POWCAKE = "Pelo amor do unicórnio, o que é isso?",
        CAVE_ENTRANCE = 
        {
            GENERIC="Que tesouros me esperam?",
            OPEN = "Ao subterrâneo!",
        },
        CAVE_EXIT = "De volta ao céu aberto!",
		MAXWELLPHONOGRAPH = "Uma cantora mecânica.",
		BOOMERANG = "Para atirar nos adversários!",
		PIGGUARD = "Ele está pronto para a batalha, posso ver.",
		ADVENTURE_PORTAL = "A aventura chama.",
		AMULET = "É vermelho, e um lutador. Como eu!",
		ANIMAL_TRACK = "Nossa! Adoro uma boa caçada.",
		ARMORGRASS = "Proteção de grama. Não vai durar muito.",
		ARMORMARBLE = "Praticamente impenetrável!",
		ARMORWOOD = "Um colete de árvore emprestado.",
		ARMOR_SANITY = "Forte, mas sinto que minha mente vaga...",
		ASH =
		{
			GENERIC = "As chamas permanecem.",
			REMAINS_GLOMMERFLOWER = "A flor deve permanecer em seu mundo natal.",
			REMAINS_EYE_BONE = "O osso ocular não pode passar para este mundo.",
			REMAINS_THINGIE = "Queimado. Já era.",
		},
		AXE = "Cortar e destruir!",
		BABYBEEFALO = "Mini-fera.",
		BACKPACK = "Um arsenal portátil.",
		BANDAGE = "Para curar as feridas de batalha.",
		BASALT = "Mil mortais não poderiam quebrar essa pedra.",
		BATBAT = "Lança alada!",
		BEARDHAIR = "Pelo dos loucos.",
		BEDROLL_STRAW = "Uma ferramenta para meus cochilos.",
		BEARGER = "Fera ou besta-fera?",
		BEARGERVEST = "Sou uma besta-fera!",
		ICEPACK = "A mochila da fera.",
		BEARGER_FUR = "Ele lutou bravamente, mas eu conquistei sua pele.",
		BEE =
		{
			GENERIC = "Pequenos guerreiros! Não sei se gosto deles.",
			HELD = "Calma!",
		},
		BEEBOX =
		{
			FULLHONEY = "Um tesouro de mel!",
			GENERIC = "Uma caixinha de soldados pequeninos.",
			NOHONEY = "Onde está o mel?",
			SOMEHONEY = "Um pouco de mel. É necessário ter paciência.",
			BURNT = "Minha colmeia está em silêncio.",
		},
		BEEFALO =
		{
			FOLLOWER = "Venha comigo fera.",
			GENERIC = "Feras lanudas ancestrais!",
			NAKED = "Você fica com frio sem suas lãs?",
			SLEEPING = "Parece a tia Hilda.",
		},
		BEEFALOHAT = "Isso vai ficar bem em mim, estou sentindo.",
		BEEFALOWOOL = "Realmente adoro coisas lanosas.",
		BEEHAT = "Meu elmo de abelhas, é claro.",
		BEEHIVE = "Sempre zumbindo, sempre tramando.",
		BEEMINE = "Soa suspeito.",
		BEEMINE_MAXWELL = "Cuidado onde pisa!",
		BERRIES = "Frutas. Não gosto delas.",
		BERRIES_COOKED = "Polpinha vermelha e quente.",
		BERRYBUSH =
		{
			BARREN = "Será que coloco uns excrementos nisso?",
			WITHERED = "Está muito quente para crescer.",
			GENERIC = "Um arbusto de frutas.",
			PICKED = "As frutas foram roubadas.",
		},
		BIRDCAGE =
		{
			GENERIC = "Um lar para os meus corvos!",
			OCCUPIED = "Está se divertindo?",
			SLEEPING = "Bons sonhos, amigo corvo.",
		},
		BIRDTRAP = "Sou uma capturadora de corvos sagaz.",
		BIRD_EGG = "Oval.",
		BIRD_EGG_COOKED = "Ovo quente.",
		BISHOP = "Esse precisa de uma boa lição.",
		BLOWDART_FIRE = "Como o bafo de um dragão!",
		BLOWDART_SLEEP = "Boa noite aos meus adversários.",
		BLOWDART_PIPE = "Arma de projéteis!",
		BLUEAMULET = "Joias frias.",
		BLUEGEM = "Uma safira azul.",
		BLUEPRINT = "Oh, um mapa! Não, espere. Isso está errado.",
		BELL_BLUEPRINT = "Oh, um mapa! Não, espere. Isso está errado.",
		BLUE_CAP = "Hmm, um azul.",
		BLUE_CAP_COOKED = "Ainda não quero comer isso.",
		BLUE_MUSHROOM =
		{
			GENERIC = "É mofo, na verdade.",
			INGROUND = "Bom, está se escondendo.",
			PICKED = "Espero que não cresça de novo.",
		},
		BOARDS = "Toras de avô.",
		BOAT = "Foi assim que cheguei aqui?",
		BONESHARD = "Pedaços dos meus inimigos.",
		BONESTEW = "Delicioso!",
		BUGNET = "Para capturar insetos no ar.",
		BUSHHAT = "À caçada!",
		BUTTER = "Manteiga. Será que fica bom no filé?",
		BUTTERFLY =
		{
			GENERIC = "É meio bacana.",
			HELD = "Peguei!",
		},
		BUTTERFLYMUFFIN = "Bolinho, balela.",
		BUTTERFLYWINGS = "Uma lembrancinha bonita.",
		BUZZARD = "Você e eu, comemos carne juntos.",
		CACTUS = 
		{
			GENERIC = "De fato, tem uma armadura admirável.",
			PICKED = "Voltará.",
		},
		CACTUS_MEAT_COOKED = "Carne de planta espada assada.",
		CACTUS_MEAT = "Carne de planta espada.",
		CACTUS_FLOWER = "A beleza dos músculos.",
		COLDFIRE =
		{
			EMBERS = "Esse fogo está quase no fim.",
			GENERIC = "Um conforto frio.",
			HIGH = "O fogo ruge!",
			LOW = "O fogo está lentamente acabando.",
			NORMAL = "Um conforto frio.",
			OUT = "E a luz se apaga.",
		},
		CAMPFIRE =
		{
			EMBERS = "Esse fogo está quase no fim.",
			GENERIC = "Fogo quente, Wigfrid quente.",
			HIGH = "O fogo ruge!",
			LOW = "O fogo está lentamente acabando.",
			NORMAL = "Fogo quente, Wigfrid quente.",
			OUT = "E a luz se apaga.",
		},
		CANE = "Transforma caminhada em marcha.",
		CATCOON = "Oh! Carne fofa com pelo.", 
		CATCOONDEN = 
		{
			GENERIC = "Uma carne fofa mora aqui.",
			EMPTY = "Ela lutou bravamente. Mas, infelizmente, se foi.",
		},
		CATCOONHAT = "Um chapéu peludo! Bênçãos a você, linda carne.",
		COONTAIL = "É a cauda de uma carne fofa.",
		CARROT = "Onde está a proteína?",
		CARROT_COOKED = "Tristes cenouras cozidas.",
		CARROT_PLANTED = "Uma raiz vegetal pequena.",
		CARROT_SEEDS = "Pedacinhos de natureza.",
		CAVE_FERN = "Folhagem da era das trevas.",
		CHARCOAL = "Espólios de Loge, o semideus.",
        CHESSJUNK1 = "É apenas uma pilha de guerreiros derrotados.",
        CHESSJUNK2 = "Mais guerreiros mecânicos derrotados.",
        CHESSJUNK3 = "Alguém deveria limpar esse lugar.",
		CHESTER = "Não se preocupe, não vou comê-lo.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Quem é você?",
			WAITING = "O globo ocular está cansado.",
		},
		COOKEDMANDRAKE = "Ela está definitivamente morta.",
		COOKEDMEAT = "Caarnee!",
		COOKEDMONSTERMEAT = "Filé de fera monstruosa.",
		COOKEDSMALLMEAT = "Hm, lanche de carne.",
		COOKPOT =
		{
			COOKING_LONG = "Eu poderia fazer alguma coisa enquanto espero.",
			COOKING_SHORT = "Não deve demorar agora!",
			DONE = "O que temos aqui?",
			EMPTY = "Não há nada aqui.",
			BURNT = "O fogo reinou supremo.",
		},
		CORN = "Uma espada vegetal!",
		CORN_COOKED = "O milho estourado cheira bem.",
		CORN_SEEDS = "Pedacinhos de natureza.",
		CROW =
		{
			GENERIC = "Amigo corvo!",
			HELD = "Unidos novamente.",
		},
		CUTGRASS = "O recurso mais elementar de uma artesã.",
		CUTREEDS = "Acabei com todos os insetos! Depois, comi.",
		CUTSTONE = "Pedra sólida!",
		DEADLYFEAST = "Um prato deveras potente.",
		DEERCLOPS = "Os raios brilharão através de minha lança e espetarei seu olho!",
		DEERCLOPS_EYEBALL = "Hmm, será que eu como?",
		EYEBRELLAHAT = "Não deixe a chuva cair em seus olhos!",
		DEPLETED_GRASS =
		{
			GENERIC = "Provavelmente é um tufo de grama.",
		},
		DEVTOOL = "Tem cheiro de bacon!",
		DEVTOOL_NODEV = "Não sou forte o suficiente para carregar isso.",
		DIRTPILE = "Uma pequena colina de terra.",
		DIVININGROD =
		{
			COLD = "Está tudo em silêncio.",
			GENERIC = "Um cão de caça mecânico. Para a caçada.",
			HOT = "Soem as trombetas! Chegamos!",
			WARM = "Capturamos o cheiro!",
			WARMER = "O cão está animado. Estamos nos aproximando.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Que ruínas mais crípticas.",
			READY = "Parece que falta uma peça...",
			UNLOCKED = "Pronto! A saga continua!",
		},
		DIVININGRODSTART = "Essa espada misteriosa se sente importante.",
		DRAGONFLY = "Ah, monstro alado! Finalmente, nos encontramos!",
		ARMORDRAGONFLY = "Armadura excelente para o calor da batalha.",
		DRAGON_SCALES = "Escamas místicas.",
		DRAGONFLYCHEST = "Esse baú é digno das minhas armas.",
		LAVASPIT = 
		{
			HOT = "Suas piscinas de fogo não são páreo para mim!",
			COOL = "Não é tão assustador agora, não é?",
		},
		DRAGONFRUIT = "É muito elegante.",
		DRAGONFRUIT_COOKED = "Fruta chique grelhada.",
		DRAGONFRUIT_SEEDS = "Pedacinhos de natureza.",
		DRAGONPIE = "Por que isso não é uma torta de carne? Carne, carneee!",
		DRUMSTICK = "A perna de uma fera, na minha barriga.",
		DRUMSTICK_COOKED = "Carne queeente!",
		DUG_BERRYBUSH = "Acho que retornarei à deusa terra.",
		DUG_GRASS = "Acho que retornarei à deusa terra.",
		DUG_MARSH_BUSH = "Acho que retornarei à deusa terra.",
		DUG_SAPLING = "Acho que retornarei à deusa terra.",
		DURIAN = "Tem o cheiro das minhas botas de batalha.",
		DURIAN_COOKED = "Por que cozinhei isso, mesmo?",
		DURIAN_SEEDS = "Pedacinhos de natureza.",
		EARMUFFSHAT = "Sim, muito prático!",
		EGGPLANT = "Roxo e bulboso.",
		EGGPLANT_COOKED = "Alimento para os fracos.",
		EGGPLANT_SEEDS = "Pedacinhos de natureza.",
		DECIDUOUSTREE = 
		{
			BURNING = "A madeira está em chamas!",
			BURNT = "Essa ficou com Loge.",
			CHOPPED = "Derrubada pela guerreira da floresta!",
			POISON = "Preciso me empenhar mais para essa lenha.",
			GENERIC = "Futura lenha!",
		},
		ACORN = 
		{
		    GENERIC = "Tem uma árvore se escondendo lá dentro.",
		    PLANTED = "Cresçam fortes, jovens gravetos!",
		},
		ACORN_COOKED = "Cozinhei a jovem árvore.",
		BIRCHNUTDRAKE = "Uma árvore guerreira jovem!",
		EVERGREEN =
		{
			BURNING = "A madeira está em chamas!",
			BURNT = "Essa ficou com Loge.",
			CHOPPED = "Derrubada pela guerreira da floresta!",
			GENERIC = "Me sinto em casa na floresta.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "A madeira está em chamas!",
			BURNT = "Essa ficou com Loge.",
			CHOPPED = "Derrubada pela guerreira da floresta!",
			GENERIC = "Uma árvore boa e resistente.",
		},
		EYEPLANT = "Não aponte sua bola ocular para mim, folhagem!",
		FARMPLOT =
		{
			GENERIC = "Não posso cultivar carne, qual é o sentido?",
			GROWING = "Eles estão ficando mais fortes.",
			NEEDSFERTILIZER = "Necessita de um banquete de excremento.",
			BURNT = "Bem feito por não cultivar carne!",
		},
		FEATHERHAT = "Parece um pouco cheguei para a batalha.",
		FEATHER_CROW = "Um símbolo dos corvos!",
		FEATHER_ROBIN = "Vermelho como meu cabelo.",
		FEATHER_ROBIN_WINTER = "Pena do inverno.",
		FEM_PUPPET = "Ela parece infeliz sobre seu trono.",
		FIREFLIES =
		{
			GENERIC = "Luzinhas de fada brilham!",
			HELD = "Detenho a luz!",
		},
		FIREHOUND = "O flamejante não tem misericórdia.",
		FIREPIT =
		{
			EMBERS = "Esse fogo está quase no fim.",
			GENERIC = "Fogo quente, Wigfrid quente.",
			HIGH = "O fogo ruge!",
			LOW = "O fogo está lentamente acabando.",
			NORMAL = "Fogo quente, Wigfrid quente.",
			OUT = "E a luz se apaga.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Esse fogo está quase no fim.",
			GENERIC = "Um conforto frio.",
			HIGH = "O fogo ruge!",
			LOW = "Esse fogo está lentamente acabando.",
			NORMAL = "Um conforto frio.",
			OUT = "E a luz se apaga.",
		},
		FIRESTAFF = "Wigfrid! Mestra do fogo!",
		FIRESUPPRESSOR = 
		{	
			ON = "Catapulta pronta para a batalha!",
			OFF = "Hora de descansar, guerreiro arremessador.",
			LOWFUEL = "A catapulta está ficando fraca e cansada.",
		},

		FISH = "Carne dos mares!",
		FISHINGROD = "Sou uma pescadora impiedosa.",
		FISHSTICKS = "Lanças de carne marinha.",
		FISHTACOS = "Peixe num cobertor!",
		FISH_MED = "Descanse em paz em Valhalla.",
		FISH_MED_COOKED = "Felicidade!",
		FISH_COOKED = "Felicidade!",
		FLINT = "Vital para a montagem de lanças.",
		FLOWER = "Uma flor de Freia.",
		FLOWERHAT = "Fraco para a luta, adorável na minha cabeça.",
		FLOWER_EVIL = "Um mal terrível aflige esta flora.",
		FOLIAGE = "Uma coleção de samambaias.",
		FOOTBALLHAT = "Meu elmo foi feito com o traseiro de um porco.",
		FROG =
		{
			DEAD = "Você é um pouco melequento para Valhalla.",
			GENERIC = "Eu adoraria botas de sapo um dia.",
			SLEEPING = "Está dormindo.",
		},
		FROGGLEBUNWICH = "Que delícia!",
		FROGLEGS = "Cheio de proteína de borracha!",
		FROGLEGS_COOKED = "Gosto quando vejo ossos protuberantes.",
		FRUITMEDLEY = "Eca! Colocar isso em uma taça não me engana.",
		GEARS = "Isso pode ficar legal colado no meu elmo.",
		GHOST = "Um espírito aprisionado entre mundos.",
		GOLDENAXE = "Uma ferramenta de ouro!",
		GOLDENPICKAXE = "Ouro por ouro.",
		GOLDENPITCHFORK = "Por que cargas d'água fiz um forcado tão extravagante?",
		GOLDENSHOVEL = "Cavando como um rei!",
		GOLDNUGGET = "Estou contente com essa peça de ouro.",

		GRASS =
		{
			BARREN = "A vida já se esvaiu dessa criatura.",
			WITHERED = "O calor derrotou essa planta.",
			BURNING = "Loge te observa!",
			GENERIC = "Isso poderia ser útil.",
			PICKED = "Caiu diante da minha força.",
		},
		GREEN_CAP = "Terrível!",
		GREEN_CAP_COOKED = "Carbonizado por chamas ou não, não tocará meus lábios!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Levantou-se!",
			INGROUND = "Esconda-se, covarde.",
			PICKED = "Vejo esporos fúngicos.",
		},
		GUNPOWDER = "Que energia!",
		HAMBAT = "Uma arma digna de grandes salões de jantares!",
		HAMMER = "Mais adequada para o trabalho que para a batalha.",
		HEALINGSALVE = "Encha-me de vida!",
		HEATROCK =
		{
			FROZEN = "Dentes frios me mordem!",
			COLD = "A pedra recebeu frio!",
			GENERIC = "Uma pedra de grande utilidade!",
			WARM = "A pedra recebeu calor!",
			HOT = "Loge ficaria orgulhoso.",
		},
		HOMESIGN = 
		{
			GENERIC = "Uma placa muito bem colocada.",
			UNWRITTEN = "Escreverei uma história de triunfo!",
			BURNT = "Placas de uma batalha passada.",
		},
		HONEY = "Grudento e nojento.",
		HONEYCOMB = "Não daria um bom pente.",
		HONEYHAM = "Um banquete substancial!",
		HONEYNUGGETS = "Um banquete carnívoro e suculento!",
		HORN = "Como desejo uma batalha.",
		HOUND = "A cria de Fenrir!",
		HOUNDBONE = "Um adversário derrotado.",
		HOUNDMOUND = "Esses cães são verdadeiramente guerreiros.",
		ICEBOX = "O inverno habita seu interior.",
		ICEHAT = "Um pedaço de frio.",
		ICEHOUND = "Dentes de gelo!",
		INSANITYROCK =
		{
			ACTIVE = "Uau!",
			INACTIVE = "Não tenho qualquer suspeita dessa rocha.",
		},
		JAMMYPRESERVES = "Grudento e nojento.",
		KABOBS = "Carne enfiada em um palito! Sim!",
		KILLERBEE =
		{
			GENERIC = "Um desafiante!",
			HELD = "Um adversário conquistado.",
		},
		KNIGHT = "Sinto a batalha!",

		KOALEFANT_SUMMER = "Cara criatura, comer-te-ei.",
		KOALEFANT_WINTER = "Pobre fera de carne inocente.",
		KRAMPUS = "Você não me assusta, bode!",
		KRAMPUS_SACK = "Consigo enfiar tudo aqui!",
		LEIF = "Esse é um ser florestal ancestral.",
		LEIF_SPARSE = "Esse é um ser florestal ancestral.",
		LIGHTNING_ROD =
		{
			CHARGED = "Oh, grande relâmpago!",
			GENERIC = "Traga consigo relâmpagos, Donner!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "Posso te chamar de Unicórnio?",
			CHARGED = "O relâmpago o tornou um guerreiro unicórnio!",
		},
		LIGHTNINGGOATHORN = "Isso poderia causar um dano duradouro.",
		GOATMILK = "Esse é um leite poderoso.",
		LITTLE_WALRUS = "Uma cria da foca maligna dentada.",
		LIVINGLOG = "Queimar tal magia pareceria um desperdício.",
		LOCKEDWES = "Te salvarei, mortal silencioso!",
		LOG =
		{
			BURNING = "Tora em chamas!",
			GENERIC = "A madeira sempre tem o seu valor.",
		},
		LUREPLANT = "Finalmente! Um vegetal útil.",
		LUREPLANTBULB = "Talvez eu seja uma pecuarista afinal!",
		MALE_PUPPET = "Ele parece infeliz em seu trono.",
		MANDRAKE =
		{
			DEAD = "O cadáver do nabo ainda retém sua magia.",
			GENERIC = "Um nabo!",
			PICKED = "Ela só quer sair em uma nabosaga!",
		},
		MANDRAKESOUP = "Um ensopado de magia!",
		MANDRAKE_COOKED = "Nabo grelhado.",
		MARBLE = "A pedra do guerreiro!",
		MARBLEPILLAR = "Perfeito para um palácio!",
		MARBLETREE = "Nem mesmo os ventos podem derrubar esta árvore.",
		MARSH_BUSH =
		{
			BURNING = "Tora quente!",
			GENERIC = "Um arbusto de guarda.",
			PICKED = "Que chateação!",
		},
		MARSH_PLANT = "Folhagem de lago.",
		MARSH_TREE =
		{
			BURNING = "Está em chamas!",
			BURNT = "Queimado.",
			CHOPPED = "Meu machado sempre vence.",
			GENERIC = "Uma árvore guerreira.",
		},
		MAXWELL = "Argh! Esse é o antagonista da minha saga?",
		MAXWELLHEAD = "Consigo ver em seus poros.",
		MAXWELLLIGHT = "Existe uma magia sombria aqui.",
		MAXWELLLOCK = "Devo destrancá-lo?",
		MAXWELLTHRONE = "Prefiro vagar livremente, meu unicórnio e eu.",
		MEAT = "A verdadeira fruta da terra!",
		MEATBALLS = "Bolinhas delícia.",
		MEATRACK =
		{
			DONE = "Vamos comer!",
			DRYING = "Está sendo preparado exatamente do jeito que eu gosto.",
			DRYINGINRAIN = "Toda essa chuva não está ajudando.",
			GENERIC = "Ah! Um cavalete frouxo para minhas carnes!",
			BURNT = "Que vergonha.",
		},
		MEAT_DRIED = "Excelentes provisões de batalha.",
		MERM = "Morra, fera peixe pegajosa!",
		MERMHEAD = 
		{
			GENERIC = "Consegui sentir o cheiro lá de trás!",
			BURNT = "Decapitado. Queimado. Fedido.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Essa habitação é feita de peixes?",
			BURNT = "Não sentirei falta disso.",
		},
		MINERHAT = "Um elmo iluminado! Para o escuro.",
		MONKEY = "Não confio nele.",
		MONKEYBARREL = "Que horrores habitam aí?",
		MONSTERLASAGNA = "Caçarola monstro.",
		FLOWERSALAD = "Folhas são para animais. Animais são para comer.",
        ICECREAM = "Machuca meus dentes.",
        WATERMELONICLE = "Você não me engana se escondendo em fruta congelada.",
        TRAILMIX = "A carne de noz não é carne de verdade.",
        HOTCHILI = "Um teste de minha força de vontade.",
        GUACAMOLE = "Hm, cremosa!",
		MONSTERMEAT = "Carne das feras sombrias.",
		MONSTERMEAT_DRIED = "Bem seca.",
		MOOSE = "Gostaria de poder montá-lo para a batalha.",
		MOOSEEGG = "Algo está saltando lá dentro.",
		MOSSLING = "Você não é grande o suficiente para ser um corcel.",
		FEATHERFAN = "Os luxos do acampamento, para a viagem.",
		TROPICALFAN = "Os luxos do acampamento, para a viagem.",
		GOOSE_FEATHER = "Uma escudeira merece uma cama macia de penas.",
		STAFF_TORNADO = "Uma tempestade de dor.",
		MOSQUITO =
		{
			GENERIC = "Eca! Essas coisas são inúteis!",
			HELD = "Acalme-se, fúria demoníaca!",
		},
		MOSQUITOSACK = "O sangue me deixará forte.",
		MOUND =
		{
			DUG = "Eu queria os espólios!",
			GENERIC = "Existem tesouros sob as tumbas?",
		},
		NIGHTLIGHT = "Fico mais confortável perto do meu próprio fogo.",
		NIGHTMAREFUEL = "O combustível da escuridão!",
		NIGHTSWORD = "É necessário um grande guerreiro para carregar essa espada.",
		NITRE = "Contém componentes explosivos.",
		ONEMANBAND = "Cante comigo! Somos guardiães de Asgard!",
		PANDORASCHEST = "Contém um mistério.",
		PANFLUTE = "Prefiro enfrentar meus inimigos acordados.",
		PAPYRUS = "Isso carregará adiante o registro da minha saga.",
		PENGUIN = "Pássaros do mar, vindos de longe.",
		PERD = "Você não pode correr para sempre!",
		PEROGIES = "Bolsinhas de carne.",
		PETALS = "Obrigado Froh por este presente!",
		PETALS_EVIL = "Elas não foram feitas por Froh.",
		PICKAXE = "Posso usá-lo para obter materiais preciosos para lanças e elmos.",
		PIGGYBACK = "O porco morreu com honra, depois me deu esta bolsa.",
		PIGHEAD = 
		{	
			GENERIC = "Isso é selvageria.",
			BURNT = "Normalmente, gosto de um bom assado, mas isso não está certo.",
		},
		PIGHOUSE =
		{
			FULL = "Saia daí e venha para a guerra comigo!",
			GENERIC = "Eu não achava que porcos podiam construir casas.",
			LIGHTSOUT = "Você não tem fome de batalha, porco?",
			BURNT = "Loge não sorriu para você hoje!",
		},
		PIGKING = "É o porcOdin?",
		PIGMAN =
		{
			DEAD = "Ele morreu com honra.",
			FOLLOWER = "Cavalgamos para a batalha!",
			GENERIC = "Você lutará comigo, porco?",
			GUARD = "Esse porco parece valente.",
			WEREPIG = "Foi contaminado por Fenrir.",
		},
		PIGSKIN = "A pele de uma criatura porca.",
		PIGTORCH = "Esses porcos veneram Loge?",
		PINECONE = 
		{
		    GENERIC = "Essa Essa árvore bebê está bem protegida pela armadura de espinhos.",
		    PLANTED = "Perdeu sua armadura. Cresça, árvore bebê!",
		},
		PITCHFORK = "Uma arma para fazendeiros.",
		PLANTMEAT = "Imagino que seja quase a mesma coisa.",
		PLANTMEAT_COOKED = "Ainda verde, mas vai servir.",
		PLANT_NORMAL =
		{
			GENERIC = "Uma planta.",
			GROWING = "Sou uma escudeira, não uma fazendeira!",
			READY = "Eca, vegetais. Não sei bem o que esperar...",
			WITHERED = "Vencida pelo sol.",
		},
		POMEGRANATE = "Carne frutosa.",
		POMEGRANATE_COOKED = "Carne de fruta tostada.",
		POMEGRANATE_SEEDS = "Pedacinhos de natureza.",
		POND = "Algo espreita na profundeza.",
		POOP = "Se eu pelo menos pudesse usar como camuflagem contra predadores.",
		FERTILIZER = "Seu fedor poderia levantar os mortos.",
		PUMPKIN = "Poderia ser um bela clava, no mínimo.",
		PUMPKINCOOKIE = "Tirei toda a sua vida ao assá-lo.",
		PUMPKIN_COOKED = "Polpa laranja fumegante.",
		PUMPKIN_LANTERN = "Quer lutar, vegetal?",
		PUMPKIN_SEEDS = "Pedacinhos de natureza.",
		PURPLEAMULET = "Um amuleto com poderes sombrios.",
		PURPLEGEM = "É nebulosa com uma energia misteriosa.",
		RABBIT =
		{
			GENERIC = "Pule em minha boca!",
			HELD = "Não há escapatória!",
		},
		RABBITHOLE = 
		{
			GENERIC = "Hora do show, coelhos!",
			SPRING = "Deve ser hora do intervalo para os coelhos.",
		},
		RAINOMETER = 
		{	
			GENERIC = "Prediz a chegada de chuva.",
			BURNT = "Seus dias de profecias terminaram.",
		},
		RAINCOAT = "Proteção contra a chuva.",
		RAINHAT = "Lutaremos na chuva.",
		RATATOUILLE = "Uma pilha de vegetais. Não, obrigado!",
		RAZOR = "Uma lâmina pequena, mas uma lâmina, não obstante.",
		REDGEM = "É quente ao toque.",
		RED_CAP = "Umami ou não, não quero.",
		RED_CAP_COOKED = "Não vou comer isso, mas foi divertido atear fogo.",
		RED_MUSHROOM =
		{
			GENERIC = "Pelo menos tem uma cor bonita.",
			INGROUND = "E fique aí embaixo!",
			PICKED = "Já vai tarde!",
		},
		REEDS =
		{
			BURNING = "Vejo vocês em Asgard, juncos!",
			GENERIC = "Que juncos mais duros!",
			PICKED = "Cortados em seu auge.",
		},
        RELIC = 
        {
            GENERIC = "Adequado para Asgard.",
            BROKEN = "Foi reduzido a pedacinhos.",
        },
        RUINS_RUBBLE = "Seus dias ainda não acabaram.",
        RUBBLE = "Uma pilha de pedras ancestral.",
		RESEARCHLAB = 
		{	
			GENERIC = "Prefiro a batalha à ciência.",
			BURNT = "Das cinzas às cinzas.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Talvez a ciência possa aprimorar minhas habilidades de combate.",
			BURNT = "Do pó ao pó.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Uma coisa mística.",
			BURNT = "Seu estranho poder não o protegeu do fogo.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "É uma máquina absurda que faz carne.",
			BURNT = "Não sairá mais carne daqui!",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Não sei porque fiz isso.",
			BURNT = "Valhalla, aí vou eu!",
		},
		RESURRECTIONSTONE = "Me impede de chegar a Valhalla.",
		ROBIN =
		{
			GENERIC = "Vermelho como o sangue.",
			HELD = "Prefiro seu irmão negro.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Esse pássaro conhece o frio.",
			HELD = "Que penas mais fofinhas!",
		},
		ROBOT_PUPPET = "Um prisioneiro!",
		ROCK_LIGHT =
		{
			GENERIC = "A crosta de lava é firme.",
			OUT = "Parece delicada.",
			LOW = "A crosta de lava está se formando novamente.",
			NORMAL = "Linda luz!",
		},
		ROCK = "Bam!",
		ROCK_ICE = 
		{
			GENERIC = "Uma montanha congelada em miniatura.",
			MELTED = "Pobre geleira!",
		},
		ROCK_ICE_MELTED = "Pobre geleira!",
		ICE = "Me faz lembrar de casa.",
		ROCKS = "Algumas rochas bem normais.",
        ROOK = "Atacaaar!",
		ROPE = "Forte o suficiente para colar as velas do meu drácar.",
		ROTTENEGG = "Arruinado para comer, mas perfeito para a batalha.",
		SANITYROCK =
		{
			ACTIVE = "Não acredito que eu posso superar essa pedra em combate.",
			INACTIVE = "Pedra esperta, você não surpreende uma guerreira!",
		},
		SAPLING =
		{
			BURNING = "Nãããoo! Minhas lanças!",
			WITHERED = "Enrugou-se com o calor.",
			GENERIC = "Farei uma lança com ela.",
			PICKED = "Assassinei a arvorezinha!",
		},
		SEEDS = "Pedacinhos de natureza.",
		SEEDS_COOKED = "Pedacinhos de natureza, cozidos até a morte.",
		SEWING_KIT = "Não sou costureira, mas reparos às vezes são necessários.",
		SHOVEL = "Eu preferiria um funeral em um barco, embora este possa ter sua utilidade.",
		SILK = "Útil para amarração e para lembrar das vitórias passadas.",
		SKELETON = "Descanse em paz em Valhalla.",
		SKELETON_PLAYER = "Essa luta ainda não terminou.",
		SKULLCHEST = "Ah, essa foi uma batalha boa.",
		SMALLBIRD =
		{
			GENERIC = "Você não é feroz ainda, pássaro.",
			HUNGRY = "Você precisa comer para crescer forte.",
			STARVING = "O passarinho parece faminto.",
		},
		SMALLMEAT = "Um lanchinho carnudo.",
		SMALLMEAT_DRIED = "Uma pequena provisão para uma longa campanha.",
		SPEAR = "Não é minha lança favorita, mas vai servir.",
		SPIDER =
		{
			DEAD = "Derrubada pela minha lança, como muitas antes.",
			GENERIC = "Oito pernas e mesmo assim não está à minha altura!",
			SLEEPING = "Vou oferecer uma luta justa e esperar até que acorde.",
		},
		SPIDERDEN = "Destrua-os na fonte!",
		SPIDEREGGSACK = "Eu poderia esmagá-los, mas deixaria de lutar novas batalhas.",
		SPIDERGLAND = "Arrancado do abdômen de uma aranha abatida.",
		SPIDERHAT = "Uma maneira perfeita de se infiltrar no acampamento inimigo.",
		SPIDERQUEEN = "Finalmente, um verdadeiro teste para minhas habilidades.",
		SPIDER_WARRIOR =
		{
			DEAD = "Vitória para Wigfrid novamente!",
			GENERIC = "O campeão das aranhas. À batalha!",
			SLEEPING = "É covarde atacar um inimigo dormindo.",
		},
		SPOILED_FOOD = "O tempo só deixou essa comida mais nojenta, não mais inteligente.",
		STATUEHARP = "Deve ser Gunnar. As cobras levaram sua cabeça.",
		STATUEMAXWELL = "Ugh, demônio!",
		STINGER = "A espada nas costas de uma abelha.",
		STRAWHAT = "Um chapéu para refrescar depois de uma batalha feroz.",
		STUFFEDEGGPLANT = "Rechear o legume não o torna carne.",
		SUNKBOAT = "Não é de se admirar que afundou. Não é um drácar.",
		SWEATERVEST = "É um belo colete, mas não oferece proteção.",
		REFLECTIVEVEST = "Rá! O sol não é um guerreiro se ele não puder penetrar isso.",
		HAWAIIANSHIRT = "Flores não podem deter uma lança.",
		TAFFY = "A saga desta balinha será contada por gerações.",
		TALLBIRD = "Um pássaro assustador! Mas não tenho medo.",
		TALLBIRDEGG = "Crescerá e se tornará um adversário formidável.",
		TALLBIRDEGG_COOKED = "Era você ou eu, pássaro.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Esse ovo não sobreviveria no inverno nórdico.",
			GENERIC = "Lute para sair, pássaro!",
			HOT = "Nascido das chamas! A menos que frite até a morte.",
			LONG = "Ainda resta um tempo para esse pássaro nascer.",
			SHORT = "Logo acordará para este mundo.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Um guerreiro de penas espreita lá dentro.",
			PICKED = "Um pássaro de guerra jovem logo nascerá.",
		},
		TEENBIRD =
		{
			GENERIC = "Você ainda não está pronto para a batalha, pássaro.",
			HUNGRY = "Espero que goste de vegetais... a carne é para mim.",
			STARVING = "Entrar em batalha comigo é sua escolha, pássaro.",
		},
		TELEBASE =
		{
			VALID = "Controlará minha incrível velocidade.",
			GEMS = "Necessita de pedras preciosas roxas.",
		},
		GEMSOCKET = 
		{
			VALID = "Hora do show!",
			GEMS = "Está faltando sua pedra preciosa.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Para Asgard!",
			GENERIC = "Uma ponte para outro mundo.",
			LOCKED = "A ponte ainda está instável.",
			PARTIAL = "A ponte está incompleta.",
		},
		TELEPORTATO_BOX = "Talvez oculte o segredo da Bifrost desta terra.",
		TELEPORTATO_CRANK = "Uma manivela resistente.",
		TELEPORTATO_POTATO = "Nenhuma decência. Não é nem carne de metal.",
		TELEPORTATO_RING = "Parece semelhante à Bifrost.",
		TELESTAFF = "Cruzo pelos ares e mares!",
		TENT = 
		{
			GENERIC = "Durma esta noite e se prepare para a batalha amanhã.",
			BURNT = "Foi arrasada.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Um lugar para descansar minha cabeça cansada da batalha.",
			BURNT = "Foi arrasada.",
		},
		TENTACLE = "Parece bravo. Ao embate.",
		TENTACLESPIKE = "Gosmento, mas perigoso. Gosto disso.",
		TENTACLESPOTS = "Pele dura.",
		TENTACLE_PILLAR = "Um adversário de tentáculos gigante.",
		TENTACLE_PILLAR_ARM = "Um apêndice de manipulação nojento.",
		TENTACLE_GARDEN = "Enfiarei minha lança nessa massa de tentáculos!",
		TOPHAT = "Não combina com minha fantasia.",
		TORCH = "Perfeita para um ataque noturno.",
		TRANSISTOR = "Uma maravilha da ciência.",
		TRAP = "Uma armadilha bem construída. Conseguirei meu alimento.",
		TRAP_TEETH = "Uma armadilha traiçoeira.",
		TRAP_TEETH_MAXWELL = "Uma excelente clava desperdiçada, enterrada no solo.",
		TREASURECHEST = 
		{
			GENERIC = "Um local para armazenar meu elmo e minha lança enquanto descanso.",
			BURNT = "Suas paredes foram destruídas pelo fogo.",
		},
		TREASURECHEST_TRAP = "Estou sempre pronta.",
		TREECLUMP = "Fim da estrada! Devo ficar e lutar.",
		TRINKET_1 = "Brinquedos não são de interesse de uma grande guerreira como eu.",
		TRINKET_10 = "Um símbolo de vitória.",
		TRINKET_11 = "Um guerreiro preso em uma armadura requintada.",
		TRINKET_12 = "Lã de um monstro horrível.",
		TRINKET_2 = "Acompanhamento para a música de meus triunfos.",
		TRINKET_3 = "Nem mesmo minha lança pode desfazer esse nó.",
		TRINKET_4 = "Um homem pequeno e estranho.",
		TRINKET_5 = "Vai me levar à Asgard?",
		TRINKET_6 = "Tecnologia inútil.",
		TRINKET_7 = "Não é hora de brincadeira! Há uma batalha iminente!",
		TRINKET_8 = "Daria uma arma mais ou menos na hora da necessidade.",
		TRINKET_9 = "Nenhuma armadura decente pode ser feita com isso.",
		TRUNKVEST_SUMMER = "Não será suficiente em desertos gelados.",
		TRUNKVEST_WINTER = "A pele quente de uma criatura derrotada. Um traje elegante.",
		TRUNK_COOKED = "Uma recompensa suculenta depois de uma batalha dura.",
		TRUNK_SUMMER = "O baú poderoso de uma fera derrotada não-tão-peluda.",
		TRUNK_WINTER = "O baú poderoso de uma fera peluda caída.",
		TUMBLEWEED = "Fuja, covarde saltitante!",
		TURKEYDINNER = "Um verdadeiro banquete!",
		TWIGS = "Ótima para fazer lanças.",
		UMBRELLA = "Proteção contra a chuva feita com o troféu de uma caçada.",
		GRASS_UMBRELLA = "Odeio flores, mas odeio mais uma armadura molhada.",
		PALMLEAF_UMBRELLA = "Odeio plantas, mas odeio mais uma armadura molhada.",
		UNIMPLEMENTED = "Uma relíquia misteriosa, certamente contém grande poder.",
		WAFFLES = "Não é com waffles que você se prepara para a batalha!",
		WALL_HAY = 
		{	
			GENERIC = "Um impeditivo secundário aos agressores.",
			BURNT = "Isso não vai adiantar nada.",
		},
		WALL_HAY_ITEM = "Talvez meus adversários se perderão nesse feno.",
		WALL_STONE = "Meus inimigos vão se atirar contra essas pedras.",
		WALL_STONE_ITEM = "Uma parede resistente feita com a terra.",
		WALL_RUINS = "Quase impenetrável.",
		WALL_RUINS_ITEM = "Somente as barreiras mais elegantes para o meu forte.",
		WALL_WOOD = 
		{
			GENERIC = "Poderia empalar um adversário.",
			BURNT = "Fogo, a única fraqueza da madeira!",
		},
		WALL_WOOD_ITEM = "Uma fortificação medíocre.",
		WALRUS = "Essas presas poderiam penetrar até a melhor armadura.",
		WALRUSHAT = "Corja das terras altas!",
		WALRUS_CAMP =
		{
			EMPTY = "Eles partiram para uma grande jornada.",
			GENERIC = "Um acampamento de inverno adequado.",
		},
		WALRUS_TUSK = "Retirado da boca da fera marinha.",
		WARG = "És tu, Fenrir?",
		WASPHIVE = "Abelhas de guerra!",
		WATERMELON = "Faz um som agradável quando você a acerta.",
		WATERMELON_COOKED = "Vermelha e quente, mas não flui.",
		WATERMELONHAT = "É quase como usar pele.",
		WETGOOP = "Poça.",
		WINTERHAT = "Quente, mas não é adequado para o combate.",
		WINTEROMETER = 
		{
			GENERIC = "Se pelo menos medisse o calor da batalha.",
			BURNT = "O dispositivo medidor foi derrotado por Loge.",
		},
		WORMHOLE =
		{
			GENERIC = "Ele engole aqueles que caíram em batalha?",
			OPEN = "Sua mãe que me convidou.",
		},
		WORMHOLE_LIMITED = "Está fraco e doente.",
		ACCOMPLISHMENT_SHRINE = "Minhas vitórias serão lembradas!",        
		LIVINGTREE = "Uma árvore da vida, mas não é a Yggdrasil.",
		ICESTAFF = "Um presente de Ullr!",
		WATHGRITHRHAT = "O poder do unicórnio é imenso.",
		SPEAR_WATHGRITHR = "Meu camarada de batalha!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		BACONEGGS = "Porco e ovos!",
		BANANAPOP = "De alguma forma encontrei um jeito de a tornar MENOS atraente!",
		BISQUE = "Não é um prato mal.",
		CEVICHE = "Extravagante para o meu gosto, mas vai servir.",
		SEAFOODGUMBO = "Uma refeição adequada para uma rainha.",
		SURFNTURF = "Eca! Terra!",
		SHARKFINSOUP = "Delicioso!",
		LOBSTERDINNER = "Triunfei sobre meu inimigo lagosta.",
		LOBSTERBISQUE = "Assim, sim.",
		JELLYOPOP = "Eu poderia ficar louca com isso!",
		CALIFORNIAROLL = "É só um naco de comida de peixe.",

		AERODYNAMICHAT = "Minha cabeça cortará o ar!",
		ANTIVENOM = "Nenhum veneno fluirá pelas minhas veias!",
		ARMOR_LIFEJACKET = "A aventura não oferece uma segurança verdadeira!",
		ARMOR_SNAKESKIN = "A chuva foi superada!",
		ARMOR_WINDBREAKER = "Quebrarei o vento a cada passo!",
		ARMORLIMESTONE = "Seu peso é reconfortante sobre meus ossos.",
		ARMOROBSIDIAN = "Podem vir, vilões!",
		ARMORSEASHELL = "Usando isso não serei arrastada para as praias de Valhalla ainda!",
		ARMOUREDBOAT = "Agora sim, essa é uma embarcação digna de um viquingue!",
		BABYOX = "Que carne fofa.",
		BALLPHIN = "Um golpe dado pode simplesmente ricochetear.",
		BALLPHINPOD = "Um grupo de saqueadores!",
		BAMBOO = "Gravetos de grande versatilidade.",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "Seria esse um brinquedinho de Loki?",
		BIOLUMINESCENCE = "Que tipo de magia é essa?",
		BLOWDART_POISON = "Enfraquecer à distância. Odin, me perdoe...",
		BOAT_INDICATOR = "I shall launch my craft.",
		BOAT_LANTERN = "Olhem para mim feras vis dos mares sombrios!",
		BOATCANNON = "Castiga meus inimigos por mim?!",
		BOATREPAIRKIT = "Uma carga muito preciosa.",
		BOTTLELANTERN = "Uma tocha muito curiosa.",
		BURIEDTREASURE = "Que o dia sorria para mim neste dia.",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "Som e fúria!",
		CAPTAINHAT = "Ficaria melhor com chifres.",
		CARGOBOAT = "Um barco adequado para uma longa jornada.",
		CHIMINEA = "Que tipo de fogo se esconde em um buraco?",
		CIRCLINGSEAGULL = "Sujeira dos céus!",
		CLOTHSAIL = "Uma bela vela.",
		COCONADE = "Fire that can be thrown.",
		COCONUT = 
		{
		    GENERIC = "A mais dura das frutas.",
		    PLANTED = "Uma fruta dura deu lugar a uma árvore frágil.",
		},
		COFFEE = "Amargo e energizante.",
		COFFEEBEANS = "Gosto do meu preto.",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "Os mares dão presentes muito estranhos.",
		CORALREEF = "Um local duro e frágil. Eu gosto.",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "A vergonha os leva até esse buraco?",
		CUTLASS = "Oh, grande espada de morte pisceana, usarei você com honra.",
		DEAD_SWORDFISH = "Avante para Valhalla, valente peixe.",
		DEPLETED_BAMBOOTREE = "Demonstre um pouco de respeito por si mesma.",
		DEPLETED_BUSH_VINE = "Não está tão videirosa agora, não é?",
		DOYDOY = "Não mostra traços de medo em relação a mim!",
		DOYDOYBABY = "Te homenageio, jovem guerreiro dos DoyDoys.",
		DOYDOYEGG = "Dentro desse ovo cresce um viquingue de outro saco.",
		
		DOYDOYFEATHER = "A valiosa pena de um pássaro guerreiro caído.",
		DOYDOYNEST = "O ninho onde mais valentes nascerão!",
		DUBLOON = "Os espólios dos derrotados!",
		DUG_BAMBOOTREE = "Se eu plantar você, você me recompensará?",
		DUG_BERRYBUSH2 = "Minha própria fonte de bagas!",
		DUG_BUSH_VINE = "Videiras ou não vi?",
		DUG_COFFEEBUSH = "Café para a viagem.",
		EARRING = "Esse não é da minha orelha.",
		FABRIC = "Costurar não é trabalho de guerreiro...",
		FEATHERSAIL = "Os pássaros valentes me presenteiam com suas penas vivazes!",
		FIRERAIN = "Um clima para um verdadeiro guerreiro!",
		FIRERAINSHADOW = "Por Odin!",
		FISHINHOLE = "Querem se render, peixes?",
		FROG_POISON = "Para trás praga reptiliana!",
		GASHAT = "Um tipo de armadura para meu nariz e minha garganta!",
		GOLDENMACHETE = "Usarei você com orgulho.",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "Esse instrumento é movido pelos alazões de Odin!",
		JELLYFISH = "Você é muito pequeno para ser um monstro marinho.",
		JELLYFISH_COOKED = "O monstro marinho dá uma boa refeição!",
		JELLYFISH_DEAD = "O monstro marinho se move para Valhalla!",
		JELLYFISH_PLANTED = "Eu esperava que os monstros marinhos fossem maiores.",
		JELLYJERKY = "Meus dentes batalharão com você.",
		JUNGLETREE = "A mighty tree!",
		JUNGLETREE_BURNT = "Adeus, gigante.",
		JUNGLETREE_STUMP = "Vejo você em Valhalla, árvore.",
		JUNGLETREESEED =
        {
            GENERIC = "A força da árvore em uma semente.",
            PLANTED = "Vai crescer poderosamente.",
        },
		LAVAPOOL = "Uma poça de fogo!",
		LIMESTONE = "Dura como uma fruta verde.",
		LIMPETS = "Carne rochosa!",
		
		LOBSTER = "Você está vestido para a batalha habitante dos mares.",
		LOBSTERHOLE = "Os de armadura habitam este local...",
		LOGRAFT = "Você não me carregará para longe, mas me carregará.",
		MACHETE = "Um bom tamanho de lâmina.",
		MESSAGEBOTTLE = "Uma mensagem de Valhalla?",
		MESSAGEBOTTLEEMPTY = "Sem nenhuma mensagem nem bebida. Uma pena!",
		MOSQUITO_POISON = "Veneno! A obra de um covarde!",
		MUSSEL = "Você não parece forte.",
		MUSSEL_STICK = "Os mexilhões idiotas subirão nesta vara.",
		OBSIDIAN = "Seixos da montanha de fogo!",
		OBSIDIAN_WORKBENCH = "Forjadura de fogo!",
		OBSIDIANAXE = "ISSO é um machado!",
		OBSIDIANCOCONADE = "Arremessar fogo é o caminho dos covardes. Mas é divertido!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Esse fogo está quase no fim.",
			GENERIC = "Um fogo digno de um viquingue!",
			HIGH = "O fogo ruge!",
			LOW = "O fogo está lentamente acabando.",
			NORMAL = "Fogo quente, Wigfrid quente.",
			OUT = "E a luz se apaga.",
		},
		OBSIDIANMACHETE = "Uma ferramenta para cortar. Uma ferramenta para queimar.",
		SPEAR_OBSIDIAN = "Sinta a queimação.",
		OBSIDIANSPEARGUN = "Normalmente prefiro acender fogos mais perto.",
		OX = "Louvemos a Odin por esse banquete abundante de cascos!",
		PACKIM = "Você me seguirá até Valhalla?",
		PACKIM_FISHBONE = "Uma bugiganga interessante.",
		PALMLEAF = "Uma folha do tamanho de um viquingue!",
		PALMTREE =
		{
			BURNING = "A madeira está em chamas!",
			BURNT = "Essa ficou com Loge.",
			CHOPPED = "Derrubada pela guerreira da floresta!",
			GENERIC = "Você abandona os galhos, árvore?",
		},
		PALMTREE_BURNT = "Sinto cheiro de coco queimado.",
		PALMTREE_STUMP = "Você virará lenha para minha lareira em Valhalla.",
		PARROT = "Feche a matraca, pássaro!",
		PEACOCK = "Seria uma lástima arruinar essas penas, carne.",
		PIRATEHAT = "Esse chapéu confunde minha personagem... quero dizer, alma.",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "O solo arrota com doença!",
		RAFT = "Um viquingue não teme a umidade!",
		ROWBOAT = "Remar está em meu sangue.",
		SAIL = "Uma vela curiosa, mas deve servir.",
		SAND = "Você é uma terra muito limpa.",
		SAND_CASTLE = "A scale model of my future keep.",
		SANDBAG = "Areia ensacada.",
		SANDBAG_ITEM = "Controla as inundações.",
		SANDHILL = "Não vou fazer uma montanha a partir de um monte de areia.",
		SEAGULL = "Pássaro vil!",
		SEAGULL_WATER = "Você estraga a água sobre a qual flutua!",
		SEASACK = "Nojento, mas útil de seu jeito.",
		SEASHELL = "A moeda do mar.",
		SEASHELL_BEACHED = "Um escudinho élfico?",
		SEATRAP = "Traga-me os espólios dos mares!",
		SEAWEED = "Sujeira de planta aquática!",
		
		SEAWEED_PLANTED = "Uma folha que não posso esmagar com minha bota.",
		SHARK_FIN = "Um presente de um guerreiro caído.",
		SHARX = "Ah, um oponente dos mares digno!",
		SLOTMACHINE = "Uma máquina de destino e tormento.",
		SNAKE = "Nunca confie naqueles que rastejam.",
		SNAKE_FIRE = "Eles falam com a boca do vulcão!",
		SNAKE_POISON = "Mantenha suas presas vis longe de mim!",
		SNAKESKIN = "Uma cobra soltou sua pele. Com uma ajudinha...",
		SNAKESKINHAT = "Devo usar a serpente?",
		SOLOFISH = "Parece que o mar está me oferecendo um banquete.",
		SPEAR_POISON = "Essa lança recompensa a vitória do covarde.",
		SPEARGUN = "A arma de um covarde.",
		SPEARGUN_POISON = "Não sou uma dissimulada se escondendo nas sombras, sou?",
		SPOILED_FISH = "Você tem cheiro de derrota.",
		STUNGRAY = "Vocês não têm honra, seu fedidos?",
		SUPERTELESCOPE = "Odin me emprestou seu olho!",
		SWORDFISH = "Agora você é um peixe atrás de meu coração!",
		TELESCOPE = "Que tipo de truque é esse?",
		TIGERSHARK = "Me leve a Valhalla, monstro dos mares!",
		TIGERSHARKSHADOW = "A sombra da fera!",
		TORNADO = "O vento tomou uma forma furiosa!",
		TOUCAN = "Lute comigo, pássaro de bico longo! E juntos jantaremos em Valhalla!",
		TRAWLNET = "Vou saquear os mares!",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "Uma arma digna de um deus!",
		TRINKET_13 = "De onde vem esse cheiro?",
		TRINKET_14 = "O brinquedo de um bebê. Será mesmo?",
		TRINKET_15 = "Uma arma de chateação.",
		TRINKET_16 = "Um pedaço de armadura?",
		TRINKET_17 = "Uma guerreira adentra Valhalla de pés descalços...",
		TRINKET_18 = "Não reconheço esse trabalho.",
		TRINKET_19 = "Os céus estão sempre limpos para o guerreiro justo.",
		TURBINE_BLADES = "Que tipo de espada estranha é essa?",
		TURF_BEACH = "Dá uma sensação boa entre meus dedos do pé.",
		TURF_JUNGLE = "É possível se perder nisso...",
		TWISTER = "Você se esconde sob o vento, vilão!",
		VENOMGLAND = "A fonte das febres.",
		VINE = "O que você pode fazer por mim?",
		VOLCANO = "Uma montanha de fogo!",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "Destruição sem sentido de uma forjadura de arma...",
		VOLCANO_EXIT = "Estou exausta desse reino infernal.",
		VOLCANOSTAFF = "Invoque a fúria da montanha de fogo!",
		WALL_LIMESTONE = "Um trabalho bem feito.",
		WALL_LIMESTONE_ITEM = "Você resistirá comigo?",
		WHALE_BLUE = "Abaterei seu abatimento, gigante!",
		WHALE_CARCASS_BLUE = "Torrarei você em Valhalla.",
		WHALE_CARCASS_WHITE = "Oh, como os poderosos fedem.",
		WHALE_WHITE = "Seria uma honra matá-la.",
		NEEDLESPEAR = "Essa é realmente uma lança de guerra maravilhosa!",
		ARMORCACTUS = "Fará de mim uma amiga para o cacto.",
		BAMBOOTREE =
		{
			BURNT = "Sua feitiçaria vazia não poderia salvá-la do fogo.",
			CHOPPED = "Você não pode cortar isso!",
			GENERIC = "Que feitiçaria é essa? Madeira oca?",
		},
		BLOWDART_FLUP = "A arma de um covarde, largada por uma criatura desprezível e vil.",
		BLUBBER = "Isso é muito valorizado pelo meu povo!",
		BLUBBERSUIT = "Lamente minha roupa de gordura, hidratação!",
		BOAT_TORCH = "O mar noturno está ardendo!",
		BRAINJELLYHAT = "Meu cérebro tem a força da minha espada!",
		BUOY = "Faz meu espírito flutuar acima das ondas.",
		BUSH_VINE =
		{
			BURNT = "Queimou. Agora é tocar a vida-eira para frente.",
			CHOPPED = "Precisava cortar o cabelo.",
			GENERIC = "Esse arbusto tem uma cabeça de elmo.",
		},
		COCONADE =
		{
			BURNING = "O coco cuspirá seu fogo em breve!",
			GENERIC = "Esse não é um coco comum!",
		},
		COCONUT_COOKED = "Banquetearei com essa castanha gigante.",
		COCONUT_HALVED = "Parti o coco e ele me mostrou suas partes internas!",
		COFFEEBEANS_COOKED = "Pelo cheiro parece energizante.",
		COFFEEBUSH =
		{
			BARREN = "Você pelo menos tentou lutar?",
			GENERIC = "Ele produz frutas vulcânicas estranhas.",
			PICKED = "Suas frutas devem renascer.",
			WITHERED = "Arbusto fracote!",
		},
		CORAL_BRAIN = "Seu eu comer, adquirirei seu conhecimento?",
		CORAL_BRAIN_ROCK = "Uma pedra marinha mística sabichona!",
		CRAB =
		{
			GENERIC = "Me enfrente, aquele de armadura.",
			HIDDEN = "Desenterre-se, covarde!",
		},
		CRATE = "Renda seus segredos, caixa!",
		DOUBLE_UMBRELLAHAT = "Que tipo de elmo estranho é esse?",
		DOYDOYEGG_COOKED = "Devo me alimentar do saque desse pássaro destemido.",
		DOYDOYEGG_CRACKED = "Sua valentia está se esvaindo.",
		DRAGOON = "Um besta-fera amiga cuja barriga está cheia de fogo!",
		DRAGOONDEN = "Uma besta-fera precisa viver em algum lugar.",
		DRAGOONEGG = "Consigo ouvir as batidas do coração de um guerreiro lá dentro!",
		DRAGOONHEART = "Meu inimigo caído me deu um presente!",
		DRAGOONSPIT = "Eu gostaria de poder cuspir fogo.",
		DUG_ELEPHANTCACTUS = "Vou ir direto ao ponto: agora você pertence a mim.",
		ELEPHANTCACTUS = "Sinto o espírito de uma besta-fera dentro de você, planta.",
		ELEPHANTCACTUS_ACTIVE = "Finalmente a terra faz um adversário digno brotar!",
		ELEPHANTCACTUS_STUMP = "Covarde!",
		FISH_RAW = "Essa carne marinha vai me servir bem.",
		FISH_RAW_SMALL = "Essa carne marinha vai me servir bem.",
		FISH_RAW_SMALL_COOKED = "Essa carne vai nadar na minha barriga!",
		FLAMEGEYSER = "O solo arrota fogo!",
		FLOTSAM = "Devo pescá-lo do mar se quero descobrir seus segredos.",
		FLUP = "Seu barrento covarde!",
		FRESHFRUITCREPES = "Tão leve e areado!",
		GRASS_WATER = "Grama que posso pegar do meu drácar!",
		HAIL_ICE = "Os céus estão arremessando gelo!",
		HOME = "Alguém deve viver aqui.",
		ICEMAKER =
		{
			HIGH = "A máquina está no máximo!",
			LOW = "Está cuspindo consideravelmente menos gelo.",
			NORMAL = "Gelo a partir de fogo!",
			OUT = "Precisa de mais fogo!",
			VERYLOW = "Seu fogo está prestes a acabar.",
		},
		JUNGLETREE =
		{
			BURNING = "A árvore queima.",
			BURNT = "A árvore já era.",
			CHOPPED = "Uma árvore forte, mas não tão forte quanto meu machado.",
			GENERIC = "Não há árvores como essa de onde eu navego.",
		},
		KNIGHTBOAT = "Meu drácar me lança para a guerra!",
		KRAKEN = "Devolverei você a própria Hel!",
		KRAKENCHEST = "Espólios de guerra!",
		KRAKEN_TENTACLE = "O braço da fera!",
		LIMPETROCK =
		{
			GENERIC = "A pedra de carne!",
			PICKED = "A pedra não tem carne por enquanto...",
		},
		TREEGUARD = "Às armas!",
		LIVINGJUNGLETREE = "Não gosto da sua cara, árvore!",
		LOBSTER_DEAD = "Durma em Valhalla, ser de armadura.",
		LOBSTER_DEAD_COOKED = "Sua armadura esconde uma carne deliciosa.",
		LUGGAGECHEST = "Espero ficar bem com os bens do mar!",
		MAGIC_SEAL = "Levarei isso com o respeito adequado pelo poderoso mago guerreiro que o deixou.",
		MAGMAROCK = "O que posso usar para rolar essas pedras?",
		MAGMAROCK_FULL = "O que posso usar para rolar essas pedras?",
		MAGMAROCK_GOLD = "Está tremulando...",
		MAGMAROCK_GOLD_FULL = "Está tremulando...",
		MANGROVETREE = "Nunca havia derrubado uma árvore do meu drácar antes!",
		MANGROVETREE_BURNT = "Tudo acima da água foi carbonizado.",
		MARSH_PLANT_TROPICAL = "Uma planta magrela.",
		MERMFISHER = "Não disputo com pescadores, desde que eles não se lancem às armas.",
		MERMHOUSE_FISHER = "Os pescadores vivem por aqui.",
		MONKEYBALL = "Um pouco de alegria primata.",
		MONSTERTARTARE = "Ainda está tremulando.",
		MOSQUITOSACK_YELLOW = "A peste deixou seu saco de doença cair.",
		MUSSELBOUILLABAISE = "Ralo, mas quentinho.",
		MUSSEL_COOKED = "Gosto forte.",
		MUSSEL_FARM =
		{
			GENERIC = "É um criadouro de mexilhões.",
			STICKPLANTED = "Seja um com o graveto...",
		},
		MYSTERYMEAT = "A comida dos filhos de meu inimigo é... o que para mim?",
		OCTOPUSCHEST = "O baú guarda oferendas.",
		OCTOPUSKING = "Ele parece aberto ao escambo.",
		OXHAT = "Esse elmo vai manter minha peruca seca.",
		OX_FLUTE = "Não tenho ritmo...",
		OX_HORN = "Ah, daria uma ótima caneca!",
		PALMLEAF_HUT = "Deixa a chuva longe elmo.",
		PARROT_PIRATE = "Você fala de mais!",
		PEG_LEG = "Essa perna vai servir bem como taco!",
		PIGTENT = "Tem cheiro de café da manhã!",
		PIKE_SKULL = "Me faz lembrar de casa.",
		PIRATEGHOST = "Para Hel, espírito!",
		PIRATEPACK = "Faz os músculos peitorais se desenvolverem.",
		PIRATIHATITATOR =
		{
			BURNT = "Sua magia foi soprada como brasa ao vento.",
			GENERIC = "Que tipo de feitiçaria estranha é essa?",
		},
		PORTAL_SHIPWRECKED = "Esse drácar não parece adequado para uma guerreira.",
		PRIMEAPE = "Você é tão intrigante quanto peludo.",
		PRIMEAPEBARREL = "A julgar por essa bagunça, eu diria que um viquingue mora aqui.",
		RAWLING = "Finalmente! Alguém para ensaiar comigo.",
		REDBARREL = "Esse barril tem muita força!",
		ROCK_CHARCOAL = "Pedras queimam?",
		ROCK_OBSIDIAN = "Pedra de lava!",
		SAIL_STICK = "Eu comando o vento!",
		SANDBAGSMALL = "Esse saco de areia está enfrentando a água!",
		SANDBAGSMALL_ITEM = "A água se choca debilmente contra ele.",
		SAND_CASTLE =
		{
			GENERIC = "Quero fingir que sou uma gigante e esmagá-lo!",
			SAND = "O tempo o esmagou.",
		},
		SEAWEED_COOKED = "Tira-gosto marinho.",
		SEAWEED_DRIED = "É borrachudo...",
		SHADOWSKITTISH_WATER = "Um inimigo espreita!",
		SHARKITTEN = "É a sua mãe que eu quero...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Algo está esperando!",
			INACTIVE = "Apenas areia... por enquanto...",
		},
		SHARK_GILLS = "Guelras de tubarão!",
		SHARK_TEETHHAT = "Um elmo pelo meu coração de guerreiro!",
		SHIPWRECKED_ENTRANCE = "Terras novas para pilhar e saquear!",
		SHIPWRECKED_EXIT = "Partindo para novas terras...",
		SNAKEDEN =
		{
			BURNT = "Queimou. Agora é tocar a vida-eira para frente.",
			CHOPPED = "Precisava cortar o cabelo.",
			GENERIC = "Esse arbusto tem uma cabeça de elmo.",
		},
		SNAKEOIL = "Que propriedades poderosas ele concede?",
		SNAKESKINSAIL = "Uma vela feita de morte!",
		SPEAR_LAUNCHER = "Um presente de Odin!",
		SUNKEN_BOAT =
		{
			ABANDONED = "O mar leva mais um!",
			GENERIC = "Ele tem algo a dizer!",
		},
		SUNKEN_BOAT_BURNT = "Um funeral viquingue ocorreu aqui...",
		SUNKEN_BOAT_TRINKET_1 = "Algum tipo de armamento rústico?", 
		SUNKEN_BOAT_TRINKET_2 = "Um drácar infantil.", 
		SUNKEN_BOAT_TRINKET_3 = "Vela encharcada.", 
		SUNKEN_BOAT_TRINKET_4 = "Feitiçaria do mar.", 
		SUNKEN_BOAT_TRINKET_5 = "Não é do meu tamanho.",
		SWEETPOTATOSOUFFLE = "Tem um delicioso recheio de vento!",
		SWEET_POTATO = "Nunca ouvi falar de uma batata que é doce! ... Nojento!",
		SWEET_POTATO_COOKED = "Não vou comer, mas gostei da cor.",
		SWEET_POTATO_PLANTED = "O solo está repleto de doces-plantas não comestíveis.",
		SWEET_POTATO_SEEDS = "Essas vão crescer docemente.",
		SWIMMINGHORROR = "Você está aqui para me fazer um funeral viquingue?",
		TELEPORTATO_SW_BASE = "Estão faltando coisas.",
		TELEPORTATO_SW_BOX = "Será parte de algo?",
		TELEPORTATO_SW_CRANK = "Gira. Mas para quê?",
		TELEPORTATO_SW_POTATO = "Que instrumento estranho é esse?",
		TELEPORTATO_SW_RING = "É valioso?",
		THATCHPACK = "Espero que minha lança não faça um furo nele!",
		TIDALPOOL = "Um laguinho!",
		TIDAL_PLANT = "Planta encharcada.",
		TIGEREYE = "Tenho o olho do tubarão-tigre.",
		TRAWLNETDROPPED =
		{
			GENERIC = "Espoliafatoso!",
			SOON = "Os espólios logo afundarão.",
			SOONISH = "Acho que meus espólios logo afundarão.",
		},
		TRINKET_20 = "Algum tipo de armamento rústico?", 
		TRINKET_21 = "Um drácar infantil.",
		TRINKET_22 = "Vela encharcada.", 
		TRINKET_23 = "Algo quebrado.", 
		TROPICAL_FISH = "Dentro tem a cor de carne!",
		TUNACAN = "Comida que sobrevive à viagem!",
		TURF_SANDY = "Uma parte do campo de batalha.",
		TURF_ASH = "Uma parte do campo de batalha.",
		TURF_BADLANDS = "Uma parte do campo de batalha.",
		TURF_DECIDUOUS = "Uma parte do campo de batalha.",
		TURF_DESERTDIRT = "Uma parte do campo de batalha.",
		TURF_FUNGUS_GREEN = "Uma parte do campo de batalha.",
		TURF_FUNGUS_RED = "Uma parte do campo de batalha.",
		TURF_MAGMAFIELD = "Uma parte do campo de batalha.",
		TURF_MEADOW = "Uma parte do campo de batalha.",
		TURF_SNAKESKINFLOOR = "A pele de meu inimigo me dá uma sensação boa sob meus pés!",
		TURF_SWAMP = "Uma parte do campo de batalha.",
		TURF_TIDALMARSH = "Uma parte do campo de batalha.",
		TURF_VOLCANO = "Uma parte do campo de batalha.",
		TWISTER_SEAL = "Era você o carinha que estava bufando e soprando?!",
		VOLCANO_ALTAR =
		{
			GENERIC = "O altar dos deuses do fogo dorme.",
			OPEN = "Está pronto para receber sacrifícios!",
		},
		VOLCANO_ALTAR_TOWER = "Um altar para os deuses do fogo!",
		VOLCANO_SHRUB = "Você parece esgotado.",
		WALLYINTRO_DEBRIS = "Esses são os restos do meu drácar?",
		WATERMELON_SEEDS = "Sementoso.",
		WATERYGRAVE = "Saque aqui!",
		WHALE_BUBBLES = "Algo espreita lá embaixo.",
		WHALE_TRACK = "Vou te capturar!",
		WILBUR_CROWN = "Espólio aí, o que é isso?",
		WILBUR_UNLOCK = "Não me ajoelho para rei nenhum, mesmo que sejam encantadores!",
		WILDBORE = "Sinto um espírito semelhante!",
		WILDBOREHEAD = "Guarde uma caneca em Valhalla para mim.",
		WILDBOREHOUSE = "Um lugar terrível para morar!",
		WIND_CONCH = "Estou sentindo uma brisa.",
		WOODLEGS_CAGE = "Uma gaiola trancada!",
		WOODLEGS_KEY1 = "O que isso abrirá?",
		WOODLEGS_KEY2 = "Outra chave!",
		WOODLEGS_KEY3 = "Uma chave estranha!",
		WRECK = "Drácares se espalham pelo caminho até Valhalla.",
	},
	DESCRIBE_GENERIC = "É um artefato deste mundo.",
	DESCRIBE_TOODARK = "Muito escuro até para batalhar.",
	DESCRIBE_SMOLDERING = "As chamas logo consumirão tudo.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "A mais fresca das carnes!",
	},
}
