return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "자면 털을 깎겠어요.",
			GENERIC = "면도할 수 없군요.",
			NOBITS = "하지만 깎을 것이 없군요!",
		},
		STORE =
		{
			GENERIC = "이미 좋은 것들이 가득 들어있어요.",
			NOTALLOWED = "거기에 들어가지 않아요.",
		},
		RUMMAGE =
        {   
            GENERIC = "제가 할 수 없으면, 불가능한 거죠!",   
        },
		COOK =
        {
            GENERIC = "윽! 조리도구한테 졌군요!",
            TOOFAR = "틈을 줄여야겠군요!",
        },
        WRITE =
        {
            GENERIC = "할 수 없어요!",
        },
        GIVE =
        {
            DEAD = "발할라에는 더 좋은 것이 기다리겠지요.",
            SLEEPING = "달콤한 잠... 나중에 하죠.",
            BUSY = "다 되면 또 시도하죠.",
        },
        CHANGEIN =
        {
            GENERIC = "마음에 드는 털과 가죽을 보관하는 곳이죠.",
            BURNING = "흑! 내 모피!",
        },
        TEACH =
        {
            KNOWN = "이미 아는 지식이지요.",
            CANTLEARN = "그 지식은 신이 차단한 것이에요.",
        },
		REPAIRBOAT =
		{
			GENERIC = "배가 새로워졌군요!",
		},
	},
	ACTIONFAIL_GENERIC = "제가 할 수 없으면, 불가능한 거죠.",
	ANNOUNCE_MAGIC_FAIL = "마법이 약해졌군요!",
	ANNOUNCE_ADVENTUREFAIL = "저승으로 돌아가죠. 승리는 곧 저의 것!",
	ANNOUNCE_BEES = "창을 든 작은 동물 씨, 물러가시지요!",
	ANNOUNCE_BOOMERANG = "앗! 구부러진 무기를 숙달해야겠군요.",
	ANNOUNCE_CHARLIE = "모습을 드러내세요!",
	ANNOUNCE_CHARLIE_ATTACK = "겁쟁이군요!",
	ANNOUNCE_COLD = "덜덜덜이군요! 모피가 어디 있지요!",
	ANNOUNCE_HOT = "뜨거운 태양이 저를 피곤하게 하는군요.",
	ANNOUNCE_CRAFTING_FAIL = "준비물이 모자라요.",
	ANNOUNCE_DEERCLOPS = "강한 적수가 오는군요!",
	ANNOUNCE_DUSK = "태양이 지고 있어요. 어둠이 근처에서 기다리고 있지요.",
	ANNOUNCE_EAT =
	{
		GENERIC = "고기가 제 심금을 울리는군요!",
		PAINFUL = "윽, 좋은 느낌이 안 드는군요.",
		SPOILED = "욱. 신선한 것이 더 낫군요.",
		STALE = "싱싱하지 못한 짐승이군요.",
		INVALID = "전사에게 어울리는 음식이 아니지요!",
		YUCKY = "전사에게 어울리는 음식이 아니지요!",
	},
	ANNOUNCE_ENTER_DARK = "그리고 막이 내리지요.",
	ANNOUNCE_ENTER_LIGHT = "제가 빛으로 들어가지요!",
	ANNOUNCE_FREEDOM = "자유이지요! 사가는 계속 흐르지요!",
	ANNOUNCE_HIGHRESEARCH = "저는 뛰어난 장인이지요.",
	ANNOUNCE_HOUNDS = "짐승이 다가오고 있군요...",
	ANNOUNCE_HUNGRY = "잔치가 그립군요!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "쉿... 동물이 근처에 있어요.",
	ANNOUNCE_HUNT_LOST_TRAIL = "흔적을 잃었군요.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "흔적을 쫓기에는 너무 질퍽하군요.",
	ANNOUNCE_INV_FULL = "가능한 한 많이 휴대하고 있군요!",
	ANNOUNCE_KNOCKEDOUT = "윽, 머리가 아프군요.",
	ANNOUNCE_LOWRESEARCH = "흥미롭지 않았군요.",
	ANNOUNCE_MOSQUITOS = "가세요, 작은 마귀 씨!",
	ANNOUNCE_NODANGERSLEEP = "자는 것은 안전하지 않군요. 창을 사용해야겠군요!",
	ANNOUNCE_NODAYSLEEP = "태양이 높이 떴군요, 가지요!",
	ANNOUNCE_NODAYSLEEP_CAVE = "아직 쉬지 않겠지요.",
	ANNOUNCE_NOHUNGERSLEEP = "밤새 굶겠군요! 식사부터 하지요.",
	ANNOUNCE_NOSLEEPONFIRE = "제가 화염 안에 잠들지는 않겠지요.",
	ANNOUNCE_NODANGERSIESTA = "싸워야 하니까 쉴 수 없지요!",
	ANNOUNCE_NONIGHTSIESTA = "달빛 아래에서는 낮잠 잘 수 없지요.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "낮잠 시간으로 느껴지지 않는군요.",
	ANNOUNCE_NOHUNGERSIESTA = "우선 고기 간식부터 먹겠어요.",
	ANNOUNCE_NO_TRAP = "다행히, 저는 발이 재빠르지요.",
	ANNOUNCE_PECKED = "사나운 부리 씨, 가세요!",
	ANNOUNCE_QUAKE = "세계가 떨고 있군요!",
	ANNOUNCE_RESEARCH = "지식이 힘은 대단해요!",
	ANNOUNCE_SHELTER = "아하! 쉴 곳이군요!",
	ANNOUNCE_THORNS = "앗, 찔렸군요!",
	ANNOUNCE_TORCH_OUT = "제 빛이 소멸했군요!",
	ANNOUNCE_TRAP_WENT_OFF = "저것은 계획의 일부가 아니었어요.",
	ANNOUNCE_UNIMPLEMENTED = "이 세계의 것이 아니군요.",
	ANNOUNCE_WORMHOLE = "질퍽한 경험이었군요.",
	ANNOUNCE_CANFIX = "\n이건 수리할 수 있지요.",
	ANNOUNCE_FAN_OUT = "팬을 또 잃었군요!",
	ANNOUNCE_ACCOMPLISHMENT = "이제 전투로 돌아가도 되겠지요?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "승리군요! 그럼, 가지요.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "똥이 더 필요한지요?",
	ANNOUNCE_TOOL_SLIP = "미끄러운 마귀군요!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "번갯불을 타고 왔지요.",

	ANNOUNCE_DAMP = "전투하기에 축축하군요.",
	ANNOUNCE_WET = "저는 젖은 전사이지요.",
	ANNOUNCE_WETTER = "이를 목욕으로 칠 수 있을까요?",
	ANNOUNCE_SOAKED = "거의 물에 빠진 것이군요!",
	
	ANNOUNCE_OTHER_WORLD_PLANT = "그러한 식물은 이 세계에서 제대로 자라지 않겠지요!",

	ANNOUNCE_BOAT_DAMAGED = "배가 다쳤군요!",
	ANNOUNCE_BOAT_SINKING = "바다가 나를 지옥으로 빠트리려고 하는군요!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "심해가 저를 삼키려고 하는군요!",
	ANNOUNCE_BURNT = "으앗!",
	ANNOUNCE_CRAB_ESCAPE = "사라졌어요!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "파도가 저의 주인이지요!",
	ANNOUNCE_MAPWRAP_RETURN = "안개 속에서 나왔지요!",
	ANNOUNCE_MAPWRAP_WARN = "세계의 끝에 도달했군요!",
	ANNOUNCE_MORETREASURE = "행운의 날이 저에게 미소를 짓는군요!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "이 지도는 다른 땅을 묘사하지요.",
	ANNOUNCE_SHARX = "거품에서 나온 적이지요!",
	ANNOUNCE_TRAWL_FULL = "망이 가득 찼군요.",
	ANNOUNCE_TREASURE = "지도가 보물의 장소를 알려주는군요!",
	ANNOUNCE_VOLCANO_ERUPT = "라그나로크가 찾아온 것일까요?!",
	ANNOUNCE_WAVE_BOOST = "전진하지요!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "파도 아래에 짐승이 있군요...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "짐승의 흔적을 잃었어요...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "거친 바다를 더 이상 읽을 수 없군요...",

	BATTLECRY =
	{
		GENERIC = "발할라가 기다리고 있어요!",
		PIG = "오늘밤에는 돼지를 먹겠지요!",
		PREY = "용감하게 죽으세요, 약한 적!",
		SPIDER = "거미 씨, 제 창을 만나시지요!",
		SPIDER_WARRIOR = "살해당할 준비를 하시지요!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "언젠가는 오딘이 데려가겠지요!",
		PIG = "돼지껍질 씨, 돌아오겠요!",
		PREY = "이번에는 봐 주지요!",
		SPIDER = "다리 많은 겁쟁이군요.",
		SPIDER_WARRIOR = "도망가세요, 괴물 씨! 돌아올 거예요.",
	},

	DESCRIBE =
	{		
		BIGFISHINGROD = "맛있는 생선 고기를 잡겠어요.",
		BIGFOOT = "전혀 다른 것이군요!",
		COFFEEBOT = "지상 최고의 기계군요.",
		DEPLETED_GRASS_WATER = "완전히 사라졌군요.",
		HOUNDFIRE = "영원한 열정으로 타는군요!",
		INVENTORYGRAVE = "발할라에서 보지요!",
		INVENTORYMOUND = "발할라에서 만나지요!",
		LIMPETS_COOKED = "잔치상이군요!",
		WOODLEGSBOAT = "저는 롱십을 더 좋아해요.",
		WOODLEGSHAT = "제 투구에 비하면 아무 것도 아니지요.",
		WOODLEGSSAIL = "사나운 헝겊이군요.",
		GLOMMER = "제왕 같은 구버군요.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "숲의 경이로군요.",
        	DEAD = "한 때 숲의 경이로움이었지요.",
        },
        GLOMMERWINGS = "오, 구버가 남긴 것을 볼까요.",
        GLOMMERFUEL = "이 진창물이 유용할 수 있겠군요.",
        BELL = "저는 칼날이 부딪히는 소리를 선호하지요.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "신들에 대한 이상한 존경의 표시군요.",
        	EMPTY = "제가 무례했군요.",
        },

		WEBBERSKULL = "그는 용감하게 싸웠지만 바이킹의 장례를 치르지는 않겠군요.",
		WORMLIGHT = "빛나는 보물에 저항할 수 없지요!",
		WORMLIGHT_LESSER = "빛나는군요! 힘껏 발광하세요!",
		WORM =
		{
		    PLANT = "함정의 냄새가 나는군요.",
		    DIRT = "흙 아래 무엇이 있는 것이지요?",
		    WORM = "깊은 곳의 뱀 짐승이군요!",
		},
		WORMLIGHT_PLANT = "함정의 냄새가 나는군요.",
		MOLE =
		{
			HELD = "제 주머니를 위한 친구지요.",
			UNDERGROUND = "누가 저 아래에 있겠지요?",
			ABOVEGROUND = "걱정 없이 파는군요.",
		},
		MOLEHILL = "아래에 끔찍한 무언가가 살고 있군요.",
		MOLEHAT = "동물의 모든 부위를 사용하는 것이 좋아요.",

		EEL = "미끌거리는 맛있는 뱀 물고기군요.",
		EEL_COOKED = "뜨거운 뱀장어군요!",
		UNAGI = "음식이 그리 고급스러울 필요는 없지요.",
		EYETURRET = "레이저 신의 눈이 저를 보고 있군요.",
		EYETURRET_ITEM = "고대 보호 눈알이군요!",
		MINOTAURHORN = "투구에 이를 추가할 수 있겠지요?",
		MINOTAURCHEST = "정복의 궤짝이군요!",
		THULECITE_PIECES = "빛나는 튀긴 옥수수 같군요.",
		POND_ALGAE = "고대의 식물이군요.",
		GREENSTAFF = "베베 꼬인 녹색 힘이군요.",
		POTTEDFERN = "이것으로 무엇을 할 수 있는 거지요?",

		THULECITE = "이 재료의 강함은 원대하지요!",
		ARMORRUINS = "오딘이 입어도 좋을 갑옷이군요!",
		RUINS_BAT = "전사 지팡이군요!",
		RUINSHAT = "싸우는 관이군요!",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Nothing stirs.",
			WARN = "It's starting...",
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			NOMAGIC = "The magic slumbers far from here.",
		},
		BISHOP_NIGHTMARE = "그의 충격파를 조심해야지요!",
		ROOK_NIGHTMARE = "그대는 두렵지 않군요!",
		KNIGHT_NIGHTMARE = "저 말을 타서는 안 될 것 같군요.",
		MINOTAUR = "경이롭군요. 결투를 하지요!",
		SPIDER_DROPPER = "그대는 아주 은밀하군요!",
		NIGHTMARELIGHT = "지하의 어두운 힘을 부르지요.",
		NIGHTSTICK = "토르에게 어울리는 무기군요.",
		GREENGEM = "에메랄드 돌이군요.",
		RELIC = "Old bits of a dwelling.",
		RUINS_RUBBLE = "I'm quite crafty. I could repair that.",
		MULTITOOL_AXE_PICKAXE = "전사 도구군요!",
		ORANGESTAFF = "마법 이동의 지팡이군요.",
		YELLOWAMULET = "호부에 갇힌 별이군요.",
		GREENAMULET = "향상된 에메랄드 제조 기술!",
		SLURPERPELT = "I do love furs.",	

		SLURPER = "털 짐승은 자신이 모자라고 생각하고 있군요!",
		SLURPER_PELT = "저는 모피를 좋아하지요.",
		SLURPERPELT = "저는 모피를 좋아하지요.",
		ARMORSLURPER = "식욕을 감퇴하게 만드는군요. 좋은 털이군요.",
		ORANGEAMULET = "수집이 이렇게 쉬운 적이 없었지요.",
		YELLOWSTAFF = "별을 부르는군요!",
		YELLOWGEM = "노란색이 아름답군요.",
		ORANGEGEM = "주황색 돌이군요.",
		TELEBASE = 
		{
			VALID = "Prepare yourselves for the power of purple!",
			GEMS = "There's still gems missing.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "It's empty.",
		},
		STAFFLIGHT = "보세요! 보탄의 선물이군요!",
	
        ANCIENT_ALTAR = "공작의 결과가 좋길 바래요.",

        ANCIENT_ALTAR_BROKEN = "이는 작동하지 않는군요.",

        ANCIENT_STATUE = "신비로운 기운이 있는 보물이군요.",

        LICHEN = "엄청나게 무의미한 식물이군요.",
		CUTLICHEN = "제가 집었어요. 하지만 먹진 않겠지요.",

		CAVE_BANANA = "원숭이 음식이군요.",
		CAVE_BANANA_COOKED = "따뜻하게 만든 원숭이 음식이군요.",
		CAVE_BANANA_TREE = "약한 원숭이 나무군요.",
		ROCKY = "그는 훌륭한 전투 동지가 될 수 있지요.",
		
		COMPASS =
		{
			GENERIC= "판독할 수 없군요.",
			N = "북.",
			S = "남.",
			E = "동.",
			W = "서.",
			NE = "북동.",
			SE = "남동.",
			NW = "북서.",
			SW = "남서.",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "마법이 상승하고 있군요!",
			STEADY = "마법이 안정적이군요.",
			WANING = "후퇴하기 시작하는군요!",
			DAWN = "마법이 거의 남지 않았군요.",
			WARN = "시작하는 중이군요...",
			CALM = "아무 것도 움직이지 않는군요.",
			NOMAGIC = "마법이 먼 곳에서 자고 있군요.",
		},

		HOUNDSTOOTH="제 정복의 징표군요.",
		ARMORSNURTLESHELL="방패군요.",
		BAT="어두운 날개가 달린 고기군요.",
		BATBAT = "Winged spear!",
		BATWING="제 투구의 날개 같지만 더 고기 같군요.",
		BATWING_COOKED="요리한 어두운 날개군요.",
		BEDROLL_FURRY="고급스러운 털 침대군요!",
		BUNNYMAN="제가 당신을 먹을게요.",
		FLOWER_CAVE="그리고 가장 어두운 시간에 밤을 밝혔지요.",
		FLOWER_CAVE_DOUBLE="그리고 가장 어두운 시간에 밤을 밝혔지요.",
		FLOWER_CAVE_TRIPLE="그리고 가장 어두운 시간에 밤을 밝혔지요.",
		GUANO="흠, 어두운 날개의 똥이군요.",
		LANTERN="어둠을 위한 등불이지요.",
		LIGHTBULB="빛나는군요!",
		MANRABBIT_TAIL="성공적인 전투를 기리는 털 달린 트로피군요.",
		MUSHTREE_TALL  ="이 마법은 무엇인가요?",
		MUSHTREE_MEDIUM="빛이 마음에 드는군요.",
		MUSHTREE_SMALL ="버섯은 좋아하지 않지요.",
		RABBITHOUSE=
		{
			GENERIC = "이 큰 당근으로 무엇을 하지요?",
			BURNT = "잘 사라졌군요, 큰 당근.",
		},
		SLURTLE="그대는 천사군요. 불쾌한.",
		SLURTLE_SHELLPIECES="많이 부서졌군요.",
		SLURTLEHAT="제 소장품에 더할 새로운 전투 투구군요!",
		SLURTLEHOLE="제가 투구를 걸고 싶은 곳이 아니군요.",
		SLURTLESLIME="예. 찐득하군요.",
		SNURTLE="저는 그의 투구를 좋아하지요.",
		SPIDER_HIDER="그대를 때려 부수겠어요!",
		SPIDER_SPITTER="성났군요.",
		SPIDERHOLE="거미줄. 좋은 징조가 아니지요.",
		STALAGMITE="동굴 돌덩이군요.",
		STALAGMITE_FULL="동굴 돌덩이군요.",
		STALAGMITE_LOW="동굴 돌덩이군요.",
		STALAGMITE_MED="동굴 돌덩이군요.",
		STALAGMITE_TALL="뾰족한 돌이군요.",
		STALAGMITE_TALL_FULL="뾰족한 돌이군요.",
		STALAGMITE_TALL_LOW="뾰족한 돌이군요.",
		STALAGMITE_TALL_MED="뾰족한 돌이군요.",

		TURF_CARPETFLOOR = "전투의 피를 빨아들였군요.",
		TURF_CHECKERFLOOR = "고급스러운 바닥이군요.",
		TURF_DIRT = "전장의 조각이군요.",
		TURF_FOREST = "전장의 조각이군요.",
		TURF_GRASS = "전장의 조각이군요.",
		TURF_MARSH = "전장의 조각이군요.",
		TURF_ROAD = "전투의 길에 제가 갈 곳을 정해 주지요.",
		TURF_ROCKY = "전장의 조각이군요.",
		TURF_SAVANNA = "전장의 조각이군요.",
		TURF_WOODFLOOR = "나무 바닥은 필사의 투쟁을 하기에 좋은 표면이지요.",

		TURF_CAVE="전장의 조각이군요.",
		TURF_FUNGUS="전장의 조각이군요.",
		TURF_SINKHOLE="전장의 조각이군요.",
		TURF_UNDERROCK="전장의 조각이군요.",
		TURF_MUD="전장의 조각이군요.",

		POWCAKE = "일각수여, 이것이 도대체 무엇이지요?",
        CAVE_ENTRANCE = 
        {
            GENERIC="아래에 어떤 보물이 있을까요?",
            OPEN = "지하 세계로 가지요!",
        },
        CAVE_EXIT = "열린 하늘을 다시 보는군요!",
		MAXWELLPHONOGRAPH = "기계 여가수군요.",
		BOOMERANG = "적에게 던지기 위한 것이군요!",
		PIGGUARD = "전투할 준비가 되었군요, 제가 알 수 있지요.",
		ADVENTURE_PORTAL = "모험이 부르고 있지요.",
		AMULET = "빨간색이고 전사이군요. 저처럼 말이지요!",
		ANIMAL_TRACK = "아! 저는 훌륭한 사냥을 좋아하지요.",
		ARMORGRASS = "풀의 보호군요. 오래 지속되지 않겠지요.",
		ARMORMARBLE = "거의 꿰뚫을 수 없군요!",
		ARMORWOOD = "빌린 나무 조끼군요.",
		ARMOR_SANITY = "강하지만, 제 정신이 오락가락하는군요...",
		ASH =
		{
			GENERIC = "화염의 잔존물이군요.",
			REMAINS_GLOMMERFLOWER = "꽃은 원래 세계에 남아있어야 하지요.",
			REMAINS_EYE_BONE = "눈뼈는 이 세계로 올 수 없었군요.",
			REMAINS_THINGIE = "탔군요. 떠났군요.",
		},
		AXE = "자르고 파괴하지요!",
		BABYBEEFALO = "소형 짐승이군요.",
		BACKPACK = "휴대용 무기고군요.",
		BANDAGE = "전투로 입은 상처를 치료하기 위한 것이군요.",
		BASALT = "수 천 명의 인간이라도 이 돌을 부술 수는 없겠지요.",
		BATBAT = "날개 창이군요!",
		BEARDHAIR = "광인의 털이지요.",
		BEDROLL_STRAW = "제 낮잠을 위한 도구군요.",
		BEARGER = "짐승 혹은 베어서커?",
		BEARGERVEST = "저는 광란의 전사이지요!",
		ICEPACK = "짐승의 배낭이군요.",
		BEARGER_FUR = "용맹하게 싸웠지만 제가 그 가죽을 차지했지요.",
		BEE =
		{
			GENERIC = "조막만한 전사군요! 그들이 마음에 드는지는 모르겠군요.",
			HELD = "가만히 있어요!",
		},
		BEEBOX =
		{
			FULLHONEY = "꿀이 든 보물상자군요!",
			GENERIC = "작은 전사들이 들어있는 달콤한 상자군요.",
			NOHONEY = "꿀이 어디에 있지요?",
			SOMEHONEY = "약간의 꿀이군요. 인내심이 필요하군요.",
			BURNT = "제 벌통이 침묵을 지키고 있군요.",
		},
		BEEFALO =
		{
			FOLLOWER = "오세요, 짐승 씨.",
			GENERIC = "고대의 털복숭이 짐승이군요!",
			NAKED = "모피가 없으면 추운가요?",
			SLEEPING = "힐다 고모와 같은 소리를 내는군요.",
		},
		BEEFALOHAT = "저에게 분명히 어울리겠군요.",
		BEEFALOWOOL = "저는 털 많은 것을 좋아하지요.",
		BEEHAT = "물론 제 벌 투구이지요.",
		BEEHIVE = "언제나 소리를 내며 음모를 꾸미는군요.",
		BEEMINE = "수상쩍은 소리군요.",
		BEEMINE_MAXWELL = "발걸음을 주의하세요!",
		BERRIES = "과일이군요. 제가 싫어하는 거군요.",
		BERRIES_COOKED = "따뜻한 빨간 죽.",
		BERRYBUSH =
		{
			BARREN = "여기에 똥을 놓아야 할까요?",
			WITHERED = "자라기에는 너무 뜨겁군요.",
			GENERIC = "과일 떨기군요.",
			PICKED = "과일을 잡아챘군요.",
		},
		BIRDCAGE =
		{
			GENERIC = "제 갈가마귀를 위한 집이군요!",
			OCCUPIED = "좋은 시간을 보내고 있나요?",
			SLEEPING = "좋은 꿈 꾸세요, 갈가마귀 친구.",
		},
		BIRDTRAP = "저는 영리하게 갈가마귀를 잡지요!",
		BIRD_EGG = "알 같군요.",
		BIRD_EGG_COOKED = "뜨거운 알이군요.",
		BISHOP = "이는 잘 때려야겠군요.",
		BLOWDART_FIRE = "용의 숨 같군요.",
		BLOWDART_SLEEP = "저의 적들, 안녕히 주무세요.",
		BLOWDART_PIPE = "발사하는 무기류군요!",
		BLUEAMULET = "차가운 보석이군요.",
		BLUEGEM = "얼음 같은 파란 사파이어군요.",
		BLUEPRINT = "오, 지도군요! 아니, 잠깐만요! 잘못됐군요.",
		BELL_BLUEPRINT = "오, 지도군요! 아니, 잠깐만요! 잘못됐군요.",
		BLUE_CAP = "흠, 파란색이군요.",
		BLUE_CAP_COOKED = "그래도 먹기 싫잖아.",
		BLUE_MUSHROOM =
		{
			GENERIC = "곰팡이군요, 진짜.",
			INGROUND = "좋아요, 숨고 있군요.",
			PICKED = "다시 자라질 않길 바래요.",
		},
		BOARDS = "할아버지 통나무군요.",
		BOAT = "저 것으로 제가 온 건가요?",
		BONESHARD = "제 적의 조각이군요.",
		BONESTEW = "맛있군요!",
		BUGNET = "공중에서 곤충을 잡기 위해서군요.",
		BUSHHAT = "사냥을 위해서지요.",
		BUTTER = "버터군요. 스테이크에 좋은가요?",
		BUTTERFLY =
		{
			GENERIC = "좀 좋군요.",
			HELD = "잡았군요!",
		},
		BUTTERFLYMUFFIN = "머핀, 머핀이군요.",
		BUTTERFLYWINGS = "예쁜 기념품이군요.",
		BUZZARD = "그대와 제가 함께 고기 축제를 하는군요.",
		CACTUS = 
		{
			GENERIC = "우수한 갑옷을 가지고 있군요.",
			PICKED = "돌아오겠지요.",
		},
		CACTUS_MEAT_COOKED = "구운 검 식물 고기군요.",
		CACTUS_MEAT = "검 식물 고기군요.",
		CACTUS_FLOWER = "강자의 아름다움이군요.",
		COLDFIRE =
		{
			EMBERS = "불이 거의 죽었군요.",
			GENERIC = "차가운 편안함이군요.",
			HIGH = "불이 타오르고 있군요!",
			LOW = "불이 서서히 죽고 있군요.",
			NORMAL = "차가운 편안함이군요.",
			OUT = "그리고 빛이 가물거리며 꺼지지요.",
		},
		CAMPFIRE =
		{
			EMBERS = "불이 거의 죽었군요.",
			GENERIC = "따뜻한 불에 따뜻한 위그프리드지요.",
			HIGH = "불이 타오르고 있군요!",
			LOW = "불이 서서히 죽고 있군요.",
			NORMAL = "따뜻한 불에 따뜻한 위그프리드지요.",
			OUT = "그리고 빛이 가물거리며 꺼지지요.",
		},
		CANE = "\"걸음\"을 \"빠른 걸음\"으로 만들지요.",
		CATCOON = "아! 털 달린 귀여운 고기군요.", 
		CATCOONDEN = 
		{
			GENERIC = "귀여운 고기가 그곳에 살지요.",
			EMPTY = "그녀는 용감하게 싸웠지요. 아아, 그녀는 이미 갔군요.",
		},
		CATCOONHAT = "털난 모자군요! 고마워요, 귀여운 고기.",
		COONTAIL = "귀여운 고기의 꼬리군요.",
		CARROT = "단백질이 어디에 있지요?",
		CARROT_COOKED = "슬픈 요리된 당근이군요.",
		CARROT_PLANTED = "작은 뿌리 채소군요.",
		CARROT_SEEDS = "자연의 작은 조각이군요.",
		CAVE_FERN = "암흑시대의 식물이군요.",
		CHARCOAL = "반신반인 로기의 전리품이군요.",
        CHESSJUNK1 = "쓰러진 전사 더미일 뿐이군요.",
        CHESSJUNK2 = "쓰러진 더 많은 기계 전사들이군요.",
        CHESSJUNK3 = "누군가가 이 곳을 정말 정리해야겠군요.",
		CHESTER = "걱정 마세요, 그를 먹지 않겠어요.",
		CHESTER_EYEBONE =
		{
			GENERIC = "누구시지요?",
			WAITING = "눈알이 피곤하군요.",
		},
		COOKEDMANDRAKE = "그녀는 분명히 죽었지요.",
		COOKEDMEAT = "고오기이군요!",
		COOKEDMONSTERMEAT = "괴물 짐승 스테이크.",
		COOKEDSMALLMEAT = "냠냠, 고기 간식이군요.",
		COOKPOT =
		{
			COOKING_LONG = "기다리면서 뭔가 하는 것이 좋겠지요.",
			COOKING_SHORT = "오래 걸리지 않겠지요!",
			DONE = "이것이 무엇인가요?",
			EMPTY = "저 안에 아무 것도 없어요.",
			BURNT = "불이 지배하였군요.",
		},
		CORN = "채소 검이군요!",
		CORN_COOKED = "튀긴 옥수수는 냄새가 좋군요.",
		CORN_SEEDS = "자연의 작은 조각이군요.",
		CROW =
		{
			GENERIC = "갈가마귀 친구군요!",
			HELD = "다시 함께군요.",
		},
		CUTGRASS = "공예 여인의 가장 기본적인 재료군요.",
		CUTREEDS = "벌레를 다 치웠지요! 그리고 제가 먹었지요.",
		CUTSTONE = "단단한 돌이군요!",
		DEADLYFEAST = "가장 강력한 요리다.",
		DEERCLOPS = "제 창에 광선이 반사되고, 그대의 눈알을 뽑아낼 것이에요!",
		DEERCLOPS_EYEBALL = "흠, 제가 먹을까요?",
		EYEBRELLAHAT = "눈에 비가 들어가지 않게 하세요!",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불인 것 같잖아.",
		},
		DEVTOOL = "베이컨 냄새가 난다!",
		DEVTOOL_NODEV = "이것을 사용할 정도로 강하지 않다.",
		DIRTPILE = "흙의 작은 고개군요.",
		DIVININGROD =
		{
			COLD = "모든 것이 조용하군요.",
			GENERIC = "기계 사냥개군요. 사냥을 위해서지요.",
			HOT = "뿔나팔을 부세요! 저희가 도착했습니다!",
			WARM = "냄새를 맡았군요!",
			WARMER = "개가 흥분했군요. 가까워지고 있군요.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "비밀스러운 폐허군요.",
			READY = "조각이 없군요...",
			UNLOCKED = "준비하지요! 사가는 계속 흐르지요!",
		},
		DIVININGRODSTART = "이 신비한 검은 중요하게 느껴지는군요.",
		DRAGONFLY = "아, 용이군요! 결국 만났군요!",
		ARMORDRAGONFLY = "전투 열기를 견딜 수 있는 훌륭한 갑옷이군요.",
		DRAGON_SCALES = "신비한 비늘이군요.",
		DRAGONFLYCHEST = "궤짝이 제 무기에 어울리는군요.",
		LAVASPIT = 
		{
			HOT = "그대의 불 웅덩이는 저를 이길 수 없어요!",
			COOL = "이제 별로 두렵지 않지요?",
		},
		DRAGONFRUIT = "아주 고급스럽군요.",
		DRAGONFRUIT_COOKED = "구운 고급 과일이군요.",
		DRAGONFRUIT_SEEDS = "자연의 작은 조각이군요.",
		DRAGONPIE = "왜 이것이 고기 파이가 아니지요? 고기, 고기군요!",
		DRUMSTICK = "짐승의 다리가 제 배 안에 있지요.",
		DRUMSTICK_COOKED = "뜨거운 고기군요!",
		DUG_BERRYBUSH = "이를 대지의 여신에게로 돌려주겠어요.",
		DUG_GRASS = "이를 대지의 여신에게로 돌려주겠어요.",
		DUG_MARSH_BUSH = "이를 대지의 여신에게로 돌려주겠어요.",
		DUG_SAPLING = "이를 대지의 여신에게로 돌려주겠어요.",
		DURIAN = "제 전투화 냄새가 나는군요.",
		DURIAN_COOKED = "왜 이것을 요리했었나요?",
		DURIAN_SEEDS = "자연의 작은 조각이군요.",
		EARMUFFSHAT = "네, 아주 유용하군요!",
		EGGPLANT = "자주색이고 구근 모양이군요.",
		EGGPLANT_COOKED = "약자의 음식이군요.",
		EGGPLANT_SEEDS = "자연의 작은 조각이군요.",
		DECIDUOUSTREE = 
		{
			BURNING = "나무가 불타고 있군요!",
			BURNT = "로기께서 가져갔군요.",
			CHOPPED = "숲의 전사가 베었군요!",
			POISON = "이 땔나무를 위해 더 노력해야겠군요.",
			GENERIC = "미래의 땔나무군요!",
		},
		ACORN = 
		{
		    GENERIC = "안에 나무가 숨어있군요.",
		    PLANTED = "어린 잔가지 씨, 강하게 자라세요!",
		},
		ACORN_COOKED = "제가 작은 나무를 요리했군요.",
		BIRCHNUTDRAKE = "젊은 나무 전사군요!",
		EVERGREEN =
		{
			BURNING = "나무가 불타고 있군요!",
			BURNT = "로기께서 가져갔군요.",
			CHOPPED = "숲의 전사가 베었군요!",
			GENERIC = "숲에 오면 집에 온 느낌이 들지요.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "나무가 불타고 있군요!",
			BURNT = "로기께서 가져갔군요.",
			CHOPPED = "숲의 전사가 베었군요!",
			GENERIC = "훌륭한 튼튼한 나무군요.",
		},
		EYEPLANT = "눈알을 제게 향하지 말아요, 식물 씨!",
		FARMPLOT =
		{
			GENERIC = "고기를 재배할 수 없는데 무슨 의미가 있지요?",
			GROWING = "강해지고 있군요.",
			NEEDSFERTILIZER = "똥 잔치를 원하는군요.",
			BURNT = "고기를 재배하지 못하는 자에게 합당한 결과이지요!",
		},
		FEATHERHAT = "전투에 쓰기에는 좀 화려하군요.",
		FEATHER_CROW = "갈가마귀의 징표군요!",
		FEATHER_ROBIN = "제 머리카락처럼 붉은 색이군요.",
		FEATHER_ROBIN_WINTER = "겨울의 깃털이군요.",
		FEM_PUPPET = "그녀는 왕좌에 앉아있지만 불행해 보이는군요.",
		FIREFLIES =
		{
			GENERIC = "작은 요정 불이 빛나고 있군요!",
			HELD = "제가 빛을 가지고 있어요!",
		},
		FIREHOUND = "화염의 존재가 자비심이 없군요.",
		FIREPIT =
		{
			EMBERS = "불이 거의 죽었군요.",
			GENERIC = "따뜻한 불에 따뜻한 위그프리드지요.",
			HIGH = "불이 타오르고 있군요!",
			LOW = "불이 서서히 죽고 있군요.",
			NORMAL = "따뜻한 불에 따뜻한 위그프리드지요.",
			OUT = "그리고 빛이 가물거리며 꺼지지요.",
		},
		COLDFIREPIT =
		{
			EMBERS = "불이 거의 죽었군요.",
			GENERIC = "차가운 편안함이군요.",
			HIGH = "불이 타오르고 있군요!",
			LOW = "불이 서서히 죽고 있군요.",
			NORMAL = "차가운 편안함이군요.",
			OUT = "그리고 빛이 가물거리며 꺼지지요.",
		},
		FIRESTAFF = "위그프리드는요! 불의 명수이지요!",
		FIRESUPPRESSOR = 
		{	
			ON = "쇠뇌가 전투에 돌입했군요!",
			OFF = "쉴 시간이에요, 날개 치는 전사씨.",
			LOWFUEL = "쇠뇌가 약해지고 지쳐가고 있군요.",
		},

		FISH = "바다의 고기군요!",
		FISHINGROD = "저는 무자비한 고기잡이 여인이지요.",
		FISHSTICKS = "바다 고기의 창이군요.",
		FISHTACOS = "담요 안의 물고기군요!",
		FISH_MED = "발할라에서 평온을 찾기를.",
		FISH_MED_COOKED = "기쁨이군요!",
		FISH_COOKED = "기쁨이군요!",
		FLINT = "창 제작에 필수적이지요.",
		FLOWER = "프레이아께서 보낸 꽃이군요.",
		FLOWERHAT = "전투에는 약하지만 제 머리를 예쁘게 해주는군요.",
		FLOWER_EVIL = "이 식물은 끔찍한 악령에 씌웠군요.",
		FOLIAGE = "양치류의 모음이군요.",
		FOOTBALLHAT = "돼지 엉덩이가 제 투구를 만들었군요.",
		FROG =
		{
			DEAD = "발할라에 들어가기엔 너무 점액이 많군요.",
			GENERIC = "언젠가는 개구리 장화를 신고 싶군요.",
			SLEEPING = "자고 있군요.",
		},
		FROGGLEBUNWICH = "굉장한 특식이군요!",
		FROGLEGS = "고무 같은 단백질이 차 있군요!",
		FROGLEGS_COOKED = "뼈가 튀어나오는 것을 보면 기분 좋지요.",
		FRUITMEDLEY = "윽! 잔에 넣는다고 저를 속일 수는 없지요.",
		GEARS = "제 투구에 붙이면 좋아 보이겠군요.",
		GHOST = "세계 사이에 갇힌 영혼이군요.",
		GOLDENAXE = "금으로 만든 도구군요!",
		GOLDENPICKAXE = "금으로 금을 캐는군요.",
		GOLDENPITCHFORK = "내가 왜 이렇게 고급스러운 쇠스랑을 만들었을까?",
		GOLDENSHOVEL = "왕처럼 파는군요!",
		GOLDNUGGET = "이 황금 조각에 만족하지요.",

		GRASS =
		{
			BARREN = "목숨이 사라졌군요.",
			WITHERED = "열이 이 식물을 이겼군요.",
			BURNING = "로기가 그대를 바라보는군요!",
			GENERIC = "이것이 유용할 수 있겠군요.",
			PICKED = "제 강력함 때문에 쓰러졌군요.",
		},
		GREEN_CAP = "끔찍하군요!",
		GREEN_CAP_COOKED = "불에 굽든 굽지 않든 이는 제 입술을 건드리지 않을 거예요!",
		GREEN_MUSHROOM =
		{
			GENERIC = "나왔군요!",
			INGROUND = "숨으세요, 겁쟁이.",
			PICKED = "버섯 포자가 보이는군요.",
		},
		GUNPOWDER = "굉장한 화력이군요!",
		HAMBAT = "위대한 식사 홀에 어울리는 무기군요!",
		HAMMER = "전투보다는 노동에 어울리는군요.",
		HEALINGSALVE = "저에게 생기를 채워주는군요!",
		HEATROCK =
		{
			FROZEN = "차가운 이가 저를 무는군요!",
			COLD = "돌에 냉기가 생겼군요!",
			GENERIC = "무척 유용한 돌이군요!",
			WARM = "돌에 온기가 생겼군요!",
			HOT = "로기께서 자랑스러워 하시겠군요.",
		},
		HOMESIGN = 
		{
			GENERIC = "가장 잘 배치된 표지판이군요.",
			UNWRITTEN = "승리의 이야기를 쓰겠어요!",
			BURNT = "과거의 전투의 징표이군요.",
		},
		HONEY = "끈적하고 징그럽군요.",
		HONEYCOMB = "빗으로는 좋지 않군요.",
		HONEYHAM = "푸짐한 잔치군요!",
		HONEYNUGGETS = "먹음직한 잔치군요!",
		HORN = "전투가 그립군요.",
		HOUND = "펜리르의 새끼!",
		HOUNDBONE = "쓰러진 적이군요.",
		HOUNDMOUND = "개는 진정한 전사군요.",
		ICEBOX = "겨울이 안에 살고 있군요!",
		ICEHAT = "냉기 덩어리군요.",
		ICEHOUND = "서릿발의 이빨이군요!",
		INSANITYROCK =
		{
			ACTIVE = "뭐지요!",
			INACTIVE = "이 바위는 전혀 의심스럽지 않군요.",
		},
		JAMMYPRESERVES = "끈적하고 징그럽군요.",
		KABOBS = "막대기에 꽂은 고기! 좋지요!",
		KILLERBEE =
		{
			GENERIC = "도전자군요!",
			HELD = "무찌른 적이군요.",
		},
		KNIGHT = "전투가 느껴지는군요!",

		KOALEFANT_SUMMER = "동물 씨... 제가 그대를 먹겠어요.",
		KOALEFANT_WINTER = "아무 것도 의심하지 못하는 고기 짐승이군요.",
		KRAMPUS = "그대는 두렵지 않군요, 염소 씨!",
		KRAMPUS_SACK = "모든 것을 여기에 넣을 수 있겠군요!",
		LEIF = "저것은 고대의 삼림지 생물이군요.",
		LEIF_SPARSE = "저것은 고대의 삼림지 생물이군요.",
		LIGHTNING_ROD =
		{
			CHARGED = "오, 위대한 번개군요!",
			GENERIC = "천둥 번개를 부르지요!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "그대를 일각수라고 불러도 되겠지요?",
			CHARGED = "벼락이 그대를 유니콘으로 만들었군요!",
		},
		LIGHTNINGGOATHORN = "이는 오래 지속되는 타격을 입힐 수 있지요.",
		GOATMILK = "강력한 유액이군요.",
		LITTLE_WALRUS = "사악한 이빨이 달린 물개의 새끼군요.",
		LIVINGLOG = "이 마법을 태우는 것은 낭비겠지요.",
		LOCKEDWES = "침묵의 인간 씨, 제가 구출하지요!",
		LOG =
		{
			BURNING = "불 뿜는 통나무군요!",
			GENERIC = "나무는 언제나 값어치가 있지요.",
		},
		LUREPLANT = "마침내! 유용한 채소군요.",
		LUREPLANTBULB = "제가 언젠가는 고기 농부가 될지도 모르겠군요!",
		MALE_PUPPET = "왕좌에 앉아있지만 불행해 보이는군요.",
		MANDRAKE =
		{
			DEAD = "루타바가 시체가 아직도 마법을 간직하고 있군요.",
			GENERIC = "루타바가군요!",
			PICKED = "그녀는 단지 루타바가 사가를 떠나고 싶은 것이지요.",
		},
		MANDRAKESOUP = "마법의 스튜군요!",
		MANDRAKE_COOKED = "구운 루타바가군요.",
		MARBLE = "전사의 돌이군요!",
		MARBLEPILLAR = "궁전에 어울리겠군요!",
		MARBLETREE = "바람도 이 나무를 쓰러뜨릴 수는 없어요.",
		MARSH_BUSH =
		{
			BURNING = "뜨거운 통나무군요!",
			GENERIC = "수비하는 떨기나무군요.",
			PICKED = "성가시군요.",
		},
		MARSH_PLANT = "연못의 잎이군요.",
		MARSH_TREE =
		{
			BURNING = "불타고 있군요!",
			BURNT = "탔군요.",
			CHOPPED = "제 전투도끼가 언제나 이기지요.",
			GENERIC = "전사 나무군요.",
		},
		MAXWELL = "앗! 저것이 제 사가의 적수인가요?!",
		MAXWELLHEAD = "털구멍이 보인다.",
		MAXWELLLIGHT = "어둠 마법이 여기에 살고 있군요.",
		MAXWELLLOCK = "제가 열까요?",
		MAXWELLTHRONE = "제 일각수와 저는 자유롭게 다니는 것을 선호하지요.",
		MEAT = "땅의 진정한 열매군요!",
		MEATBALLS = "작은 잔치 공이지요.",
		MEATRACK =
		{
			DONE = "먹지요!",
			DRYING = "제가 원하는 대로 준비하고 있군요.",
			DRYINGINRAIN = "비가 도움이 안 되는군요.",
			GENERIC = "아! 제 고기를 거는 걸이군요!",
			BURNT = "안타깝군요.",
		},
		MEAT_DRIED = "훌륭한 전투 준비물이군요.",
		MERM = "죽으세요, 축축한 짐승 물고기!",
		MERMHEAD = 
		{
			GENERIC = "저 멀리서도 냄새를 맡을 수 있는 것이군요!",
			BURNT = "머리를 잘렸군요. 탔군요. 악취가 나는군요.",
		},
		MERMHOUSE = 
		{
			GENERIC = "이 집은 물고기로 만들어졌나요?",
			BURNT = "놓치지 않을 거예요.",
		},
		MINERHAT = "빛이 있는 투구군요! 어둠을 위해서지요.",
		MONKEY = "그를 믿을 수 없군요.",
		MONKEYBARREL = "어떠한 공포가 기다리고 있을까요?",
		MONSTERLASAGNA = "괴물 캐서롤이군요.",
		FLOWERSALAD = "잎은 동물을 위한 것이지요. 동물은 먹기 위한 것이지요.",
        ICECREAM = "제 이를 아프게 하지요.",
        WATERMELONICLE = "얼린 과일에 안에 숨어도 보이지요, 막대 씨.",
        TRAILMIX = "콩의 고기는 진짜 고기가 아니지요.",
        HOTCHILI = "제 의지력을 시험하는군요.",
        GUACAMOLE = "냠냠, 부드럽군요!",
		MONSTERMEAT = "어두운 짐승의 고기지요.",
		MONSTERMEAT_DRIED = "모두 말랐거든.",
		MOOSE = "그것을 타고 전투를 하고 싶군요.",
		MOOSEEGG = "안에서 무언가가 튀고 있군요.",
		MOSSLING = "제 군마가 될 정도로 크지 않군요.",
		FEATHERFAN = "야영지의 안락함을 휴대할 수 있군요.",
		TROPICALFAN = "야영지의 안락함을 휴대할 수 있군요.",
		GOOSE_FEATHER = "방패 처녀는 던의 부드러운 침대에서 자야 하지요.",
		STAFF_TORNADO = "고통의 폭풍이군요.",
		MOSQUITO =
		{
			GENERIC = "윽! 쓸모없는 것이군요!",
			HELD = "마귀의 분노는 진정하세요!",
		},
		MOSQUITOSACK = "피가 저를 강하게 만들겠지요.",
		MOUND =
		{
			DUG = "제가 전리품을 원했어요!",
			GENERIC = "묘비 아래에 보석이 있나 보군요?",
		},
		NIGHTLIGHT = "저는 제 불 주위에서 더 편하지요.",
		NIGHTMAREFUEL = "어둠의 연료군요!",
		NIGHTSWORD = "이 검을 휘두르려면 용감한 전사가 필요하지요.",
		NITRE = "폭발물 구성 요소를 포함하고 있군요.",
		ONEMANBAND = "저와 함께 노래부르세요! 우리는 아스가르드의 수호자예요!",
		PANDORASCHEST = "신비를 담고 있군요.",
		PANFLUTE = "저는 깬 상태에서 적을 상대하는 것을 선호하지요.",
		PAPYRUS = "이는 제 사가의 기록을 전하겠지요.",
		PENGUIN = "멀리서 온 바다의 새군요.",
		PERD = "영원히 도망갈 수는 없지요!",
		PEROGIES = "고기 주머니군요.",
		PETALS = "이 선물을 주신 프레이르에게 감사드리지요!",
		PETALS_EVIL = "이는 프레이르가 만들지 않았군요.",
		PICKAXE = "귀중한 창과 투구 재료를 구하는 데 사용할 수 있지요.",
		PIGGYBACK = "돼지가 명예롭게 죽고 저에게 이 팩을 주었군요.",
		PIGHEAD = 
		{	
			GENERIC = "야만스럽군요.",
			BURNT = "평소에는 뛰어난 구이를 좋아하지만 이것은 아니군요.",
		},
		PIGHOUSE =
		{
			FULL = "나와서 저와 함께 전쟁에 참가하세요!",
			GENERIC = "돼지가 집을 지을 수 있는지 몰랐군요.",
			LIGHTSOUT = "전투에 굶주리지 않나요, 돼지 씨?",
			BURNT = "로기께서 오늘 그대에게 미소를 짓지 않았군요.",
		},
		PIGKING = "돼지 오딘인지요?",
		PIGMAN =
		{
			DEAD = "명예롭게 죽었군요.",
			FOLLOWER = "전투에 뛰어드세요!",
			GENERIC = "저와 함께 싸우겠어요, 돼지 씨?",
			GUARD = "저 돼지는 용감해 보이는군요.",
			WEREPIG = "펜리르가 오점을 남겼군요.",
		},
		PIGSKIN = "돼지 동물의 가죽이군요.",
		PIGTORCH = "이 돼지들은 로기를 숭배하나요?",
		PINECONE = 
		{
		    GENERIC = "아기 나무가 뾰족한 갑옷으로 보호 받고 있군요.",
		    PLANTED = "갑옷을 벗었군요. 나무 아기, 자라세요!",
		},
		PITCHFORK = "농부의 무기군요.",
		PLANTMEAT = "이 정도면 가까운 것 같군요.",
		PLANTMEAT_COOKED = "녹색이지만 이것으로 만족해야겠군요.",
		PLANT_NORMAL =
		{
			GENERIC = "식물이군요.",
			GROWING = "저는 방패 처녀지 농부가 아니지요!",
			READY = "윽, 채소군요. 무엇을 기대했었는지 모르겠군요...",
			WITHERED = "태양이 이겼군요.",
		},
		POMEGRANATE = "과육이군요.",
		POMEGRANATE_COOKED = "그슬린 과육이군요.",
		POMEGRANATE_SEEDS = "자연의 작은 조각이군요.",
		POND = "깊은 곳에 무언가가 잠복하고 있군요.",
		POOP = "포식자를 피할 수 있는 위장으로 사용할 수 있으면 좋을 텐데요.",
		FERTILIZER = "악취 때문에 망자도 다시 일으키겠군요.",
		PUMPKIN = "최소한 무겁게 내려칠 때는 유용하겠군요.",
		PUMPKINCOOKIE = "생기를 다 구워 버렸군요.",
		PUMPKIN_COOKED = "아주 뜨거운 주황색 죽이군요.",
		PUMPKIN_LANTERN = "싸우고 싶나요, 채소 씨?",
		PUMPKIN_SEEDS = "자연의 작은 조각이군요.",
		PURPLEAMULET = "어두운 힘의 호부군요.",
		PURPLEGEM = "신비로운 기운이 감돌고 있군요.",
		RABBIT =
		{
			GENERIC = "제 입으로 뛰어드세요!",
			HELD = "도망갈 곳은 없어요!",
		},
		RABBITHOLE = 
		{
			GENERIC = "개시 시간이군요, 토끼 씨!",
			SPRING = "토끼를 위한 막간인가 보군요.",
		},
		RAINOMETER = 
		{	
			GENERIC = "비내리는 것을 예언하지요.",
			BURNT = "예언의 시절이 지났군요.",
		},
		RAINCOAT = "비 차단 방어구.",
		RAINHAT = "저희는 빗속에서 싸우겠지요.",
		RATATOUILLE = "채소 더미군요! 사양하겠어요.",
		RAZOR = "작지만 칼날이긴 하군요.",
		REDGEM = "촉감이 뜨겁군요.",
		RED_CAP = "감칠맛인지는 모르겠지만 전 원하지 않지요.",
		RED_CAP_COOKED = "먹지는 않겠지만 불에 넣는 것은 재미있군요.",
		RED_MUSHROOM =
		{
			GENERIC = "최소한 색은 좋군요.",
			INGROUND = "그대로 쓰러져 있으세요!",
			PICKED = "잘 없어졌잖아.",
		},
		REEDS =
		{
			BURNING = "아스가르드에서 보지요, 갈대 씨!",
			GENERIC = "튼튼한 갈대군요.",
			PICKED = "혈기왕성할 때 잘렸군요.",
		},
        RELIC = 
        {
            GENERIC = "아스가르드에 어울리겠군요.",
            BROKEN = "산산조각 났군요.",
        },
        RUINS_RUBBLE = "전성기가 아직 끝나지 않았지요.",
        RUBBLE = "고대 바위 더미군요.",
		RESEARCHLAB = 
		{	
			GENERIC = "저는 과학보다는 전투를 선호하지요.",
			BURNT = "재는 재가 되는군요.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "어쩌면 과학이 제 전투 기술을 향상시킬 수 있겠군요.",
			BURNT = "먼지에서 먼지로 되는군요.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "불가사의한 것이군요.",
			BURNT = "이상한 능력이 불로부터 그것을 지켜주지 못했군요.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "고기를 만드는 부조리한 기계군요.",
			BURNT = "여기에서 고기가 더 나오지는 않을 거예요!",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "왜 이것을 만들었는지 모르겠군요.",
			BURNT = "발할라, 제가 가지요!",
		},
		RESURRECTIONSTONE = "제가 발할라로 가는 것을 막는군요.",
		ROBIN =
		{
			GENERIC = "피처럼 붉은 색이군요.",
			HELD = "전 그대의 검은 형제를 선호하지요.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "이 새는 냉기를 알고 있군요.",
			HELD = "보드라운 깃털이군요.",
		},
		ROBOT_PUPPET = "죄수군요!",
		ROCK_LIGHT =
		{
			GENERIC = "용암 껍질이 딱딱하지요.",
			OUT = "섬세해 보이는군요.",
			LOW = "용암 껍질이 딱딱하지요.",
			NORMAL = "아름다운 빛이군요!",
		},
		ROCK = "쾅이군요!",
		ROCK_ICE = 
		{
			GENERIC = "소형 냉동 산이군요.",
			MELTED = "불쌍한 빙하군요!",
		},
		ROCK_ICE_MELTED = "불쌍한 빙하군요!",
		ICE = "고향을 상기시키는군요.",
		ROCKS = "평범한 바위군요.",
        ROOK = "충전!",
		ROPE = "제 롱십의 돛을 묶을 수 있을 정도로 강하군요.",
		ROTTENEGG = "먹지는 못하게 되었지만 전투를 위해 준비가 되었군요.",
		SANITYROCK =
		{
			ACTIVE = "전투로 이 바위를 이길 수는 없을 것 같군요.",
			INACTIVE = "똑똑한 바위 씨, 그대는 전사를 놀라게 할 수 없어요!",
		},
		SAPLING =
		{
			BURNING = "안되지요! 제 창이요!",
			WITHERED = "열 때문에 오그라들었군요.",
			GENERIC = "창으로 만들어야겠군요.",
			PICKED = "제가 작은 나무를 죽였군요!",
		},
		SEEDS = "자연의 작은 조각이군요.",
		SEEDS_COOKED = "자연의 작은 조각을 죽도록 요리했군요.",
		SEWING_KIT = "저는 재봉사가 아니지만 가끔은 수리할 필요가 있지요.",
		SHOVEL = "배에 장례를 치는 것을 선호하지요. 이것도 쓸데가 있겠지만.",
		SILK = "묶거나 과거의 승리를 기억하는 데 유용하지요.",
		SKELETON = "발할라에서 편히 쉬세요.",
		SKELETON_PLAYER = "전투는 아직 끝나지 않았지요.",
		SKULLCHEST = "아, 훌륭한 전투였지요.",
		SMALLBIRD =
		{
			GENERIC = "아직 사납지 않군요, 새 씨.",
			HUNGRY = "먹어야 강하게 자라지요.",
			STARVING = "작은 새가 굶주린 것으로 보이는군요.",
		},
		SMALLMEAT = "좋은 고기 간식이군요.",
		SMALLMEAT_DRIED = "긴 전투를 위한 작은 준비지요.",
		SPEAR = "좋아하는 창은 아니지만 어쨌든 쓰지요.",
		SPIDER =
		{
			DEAD = "과거의 수많은 자처럼 제 창에 쓰러졌군요.",
			GENERIC = "다리가 여덟 개라도 저의 상대는 되지 않지요!",
			SLEEPING = "정정당당히 싸우기 위해 그것이 깨길 기다리지요.",
		},
		SPIDERDEN = "근원에서 격파해야지요!",
		SPIDEREGGSACK = "이것을 밟으면 더 전투를 못하겠지요.",
		SPIDERGLAND = "살해한 거미의 복부에서 뜯어냈군요.",
		SPIDERHAT = "적 야영지에 침입하는 완벽한 방법이군요.",
		SPIDERQUEEN = "드디어 저의 능력에 대한 진정한 시험이군요.",
		SPIDER_WARRIOR =
		{
			DEAD = "또 한 번 위그프리드의 승리군요!",
			GENERIC = "거미의 챔피언이군요. 전투하지요!",
			SLEEPING = "자는 적을 공격하는 것은 비겁하군요.",
		},
		SPOILED_FOOD = "나이는 이 음식을 더 징그럽게만 만들고, 현명하게 만들지는 않았군요.",
		STATUEHARP = "군나르이겠군요. 뱀이 그의 머리를 가져갔군요.",
		STATUEMAXWELL = "에잇, 악마군요!",
		STINGER = "벌의 등에 있는 검이군요.",
		STRAWHAT = "요란한 전투 후에 머리를 식히기 위한 모자군요.",
		STUFFEDEGGPLANT = "채소를 채운다고 고기가 되진 않겠지요.",
		SUNKBOAT = "침몰한 것이 당연하겠지요. 롱십이 아니군요.",
		SWEATERVEST = "멋진 조끼지만 보호해 주지 않는군요.",
		REFLECTIVEVEST = "훗! 이것을 통과할 수 없다면 태양은 전사라고 할 수 없겠지요.",
		HAWAIIANSHIRT = "꽃은 창을 막을 수 없지요.",
		TAFFY = "이 태피의 사가가 오랫동안 전해지겠지요.",
		TALLBIRD = "무서운 새군요! 하지만 저는 두렵지 않아요.",
		TALLBIRDEGG = "강력한 적으로 성장하겠지요.",
		TALLBIRDEGG_COOKED = "그대 아니면 저였겠지요, 새 씨.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "이 알은 스칸디나비아의 겨울을 살아남을 수 없겠지요.",
			GENERIC = "싸워서 나가세요, 새 씨!",
			HOT = "불에서 나왔군요! 불에 구운 요리가 아니라면.",
			LONG = "이 새가 태어나려면 어느 정도 기다려야겠군요.",
			SHORT = "곧 이 세계에서 깨어나겠지요.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "안에 깃털 달린 전사가 들어있군요.",
			PICKED = "어린 전쟁 새가 태어나겠군요.",
		},
		TEENBIRD =
		{
			GENERIC = "아직 전투 준비가 되지 않았군요, 새 씨.",
			HUNGRY = "채소를 좋아하길 바래요... 고기는 제 것이지요.",
			STARVING = "저와 전투하는 것은 그대의 선택이에요, 새 씨.",
		},
		TELEBASE =
		{
			VALID = "저의 굉장한 속도를 이용하겠지요.",
			GEMS = "자주색 보석이 필요하군요.",
		},
		GEMSOCKET = 
		{
			VALID = "개시 시간이군요!",
			GEMS = "보석이 없군요.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "아스가르드로 가지요!",
			GENERIC = "다른 세계로 이어지는 다리군요.",
			LOCKED = "다리가 아직 불안정하군요.",
			PARTIAL = "다리가 불완전하군요.",
		},
		TELEPORTATO_BOX = "이 땅의 비프로스트의 비밀을 가지고 있을지도 모르겠군요.",
		TELEPORTATO_CRANK = "튼튼한 크랭크군요.",
		TELEPORTATO_POTATO = "단정하지 않군요. 금속 고기도 아니군요.",
		TELEPORTATO_RING = "비프로스트와 비슷해 보이는군요.",
		TELESTAFF = "저는 하늘과 바다를 가로질러 가지요!",
		TENT = 
		{
			GENERIC = "이 밤에는 자고 내일의 전투를 준비하지요.",
			BURNT = "파괴되었군요.",
		},
		SIESTAHUT = 
		{
			GENERIC = "전투에 지친 제 머리를 쉴 곳이군요.",
			BURNT = "파괴되었군요.",
		},
		TENTACLE = "사나워 보이는군요. 싸움에 뛰어들지요!",
		TENTACLESPIKE = "끈적하지만 위험하군요. 좋군요.",
		TENTACLESPOTS = "튼튼한 껍질이군요.",
		TENTACLE_PILLAR = "거대한 촉수로 만들어진 적이군요.",
		TENTACLE_PILLAR_ARM = "징그럽게 쥐락하는 부속지군요.",
		TENTACLE_GARDEN = "제 창을 그 촉수 덩어리에 찌르겠어요!",
		TOPHAT = "제 의상에 맞지 않는군요.",
		TORCH = "야간 습격에 완벽하군요.",
		TRANSISTOR = "과학의 경이로군요.",
		TRAP = "잘 만든 덫이군요. 식사를 해야겠지요.",
		TRAP_TEETH = "위험한 덫이군요.",
		TRAP_TEETH_MAXWELL = "뛰어난 철퇴를 아깝게 땅에 묻었군요.",
		TREASURECHEST = 
		{
			GENERIC = "제가 쉬는 동안 투구와 창을 보관할 수 있는 곳이군요.",
			BURNT = "벽이 불타 쓰러졌군요.",
		},
		TREASURECHEST_TRAP = "저는 언제나 준비되었지요.",
		TREECLUMP = "막바지군요! 당당히 서서 싸워야겠군요.",
		TRINKET_1 = "장난감은 저처럼 위대한 전사에게 의미가 없어요.",
		TRINKET_10 = "승리의 징표군요.",
		TRINKET_11 = "훌륭한 갑옷을 두른 전사군요.",
		TRINKET_12 = "끔찍한 괴물을 깎아 만들었군요.",
		TRINKET_2 = "제 승전가를 위한 부속물이군요.",
		TRINKET_3 = "제 창도 이 매듭을 풀 수는 없군요.",
		TRINKET_4 = "이상한 작은 사람이군요.",
		TRINKET_5 = "저를 아스가르드로 데려가 줄까요?",
		TRINKET_6 = "쓸모없는 기술이군요.",
		TRINKET_7 = "놀 시간은 없지요! 전투를 해야 하니까요!",
		TRINKET_8 = "어쩔 수 없는 상황이라면 무기로 쓸 수 있겠군요.",
		TRINKET_9 = "이것으로는 좋은 갑옷을 만들 수가 없지요.",
		TRUNKVEST_SUMMER = "동토에서는 충분하지 않겠지요.",
		TRUNKVEST_WINTER = "무찌른 동물의 따뜻한 가죽이군요. 뛰어난 의류군요.",
		TRUNK_COOKED = "힘겨운 전투 후의 즙이 많은 보상이군요.",
		TRUNK_SUMMER = "쓰러진 털이 덜 있는 짐승의 강력한 바지군요.",
		TRUNK_WINTER = "쓰러진 털이 많은 짐승의 강력한 바지군요.",
		TUMBLEWEED = "튀는 겁쟁이 씨, 도망가세요!",
		TURKEYDINNER = "진정한 향연이군요.",
		TWIGS = "창을 만드는 데 좋지요.",
		UMBRELLA = "사냥의 기념품으로 만든 비 보호구군요.",
		GRASS_UMBRELLA = "꽃은 싫어하지만, 젖은 갑옷을 더 싫군요.",
		PALMLEAF_UMBRELLA = "식물은 싫지만, 젖은 갑옷을 더 싫군요.",
		UNIMPLEMENTED = "위대한 힘을 간직한 신비로운 유물이군요.",
		WAFFLES = "와플은 전투 준비로 충분하지 않군요!",
		WALL_HAY = 
		{	
			GENERIC = "공격자에 대한 작은 억지력이군요.",
			BURNT = "그것으로는 안되겠다.",
		},
		WALL_HAY_ITEM = "어쩌면 적들이 건초 안에서 길을 잃을지도 모르겠군요.",
		WALL_STONE = "적들이 이 바위로 직접 뛰어들겠지요.",
		WALL_STONE_ITEM = "땅으로 만든 튼튼한 벽이군요.",
		WALL_RUINS = "거의 꿰뚫을 수 없어요.",
		WALL_RUINS_ITEM = "제 요새는 가장 훌륭한 방벽만 쓰지요.",
		WALL_WOOD = 
		{
			GENERIC = "적을 꿰뚫을 수 있겠군요.",
			BURNT = "불은 나무의 유일한 약점이지요!",
		},
		WALL_WOOD_ITEM = "범상한 축성이군요.",
		WALRUS = "저 엄니는 최고의 갑옷도 뚫을 수 있지요.",
		WALRUSHAT = "하이랜드의 쓰레기군요!",
		WALRUS_CAMP =
		{
			EMPTY = "위대한 여행을 위해 떠났군요.",
			GENERIC = "제대로 된 겨울 야영지군요.",
		},
		WALRUS_TUSK = "바다 짐승의 입에서 뽑았군요.",
		WARG = "그대인가요, 펜리르?",
		WASPHIVE = "전쟁의 벌들!",
		WATERMELON = "치면 좋은 소리를 내는군요.",
		WATERMELON_COOKED = "따뜻하고 빨간색이지만 흐르지 않는군요.",
		WATERMELONHAT = "거의 가죽을 착용한 느낌이 드는군요.",
		WETGOOP = "진창이군요.",
		WINTERHAT = "따뜻하지만 전투에 적합하지 않군요.",
		WINTEROMETER = 
		{
			GENERIC = "전투의 열기를 측정할 수 있다면 좋겠지요.",
			BURNT = "로게께서 측정 도구를 죽이셨군요.",
		},
		WORMHOLE =
		{
			GENERIC = "전투에서 쓰러진 자를 삼키나요?",
			OPEN = "벌린 입이 저를 초대하는군요.",
		},
		WORMHOLE_LIMITED = "병약하군요.",
		ACCOMPLISHMENT_SHRINE = "제 승리는 기억에 남겠군요!",        
		LIVINGTREE = "생명의 나무이지만 위그드라실은 아니군요.",
		ICESTAFF = "울르의 선물이군요!",
		WATHGRITHRHAT = "일각수의 힘은 위대하지요.",
		SPEAR_WATHGRITHR = "전우군요!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		BACONEGGS = "돼지와 알이군요!",
		BANANAPOP = "더 끔찍해졌군요!",
		BISQUE = "나쁜 요리가 아니군요.",
		CEVICHE = "맛이 고급이지만 괜찮군요.",
		SEAFOODGUMBO = "여왕에게 어울리는 식사군요.",
		SURFNTURF = "우웩! 질겨요!",
		SHARKFINSOUP = "맛있군요!",
		LOBSTERDINNER = "까재를 이겼어요.",
		LOBSTERBISQUE = "마음에 드는군요.",
		JELLYOPOP = "이걸 먹으면 광전사가 되겠어요!",
		CALIFORNIAROLL = "물고기 조각일 뿐이지요.",

		AERODYNAMICHAT = "머리가 공기를 가르지요!",
		ANTIVENOM = "어떤 독소도 내 혈관을 통해 흐를 수 없어요!",
		ARMOR_LIFEJACKET = "진정으로 안전한 모험은 없지요!",
		ARMOR_SNAKESKIN = "비를 물리치지요!",
		ARMOR_WINDBREAKER = "매 걸음마다 바람을 부수겠어요!",
		ARMORLIMESTONE = "무게감이 뼈에 느껴지는 것이 안심이 되는군요.",
		ARMOROBSIDIAN = "어떤 자라도 덤벼보세요!",
		ARMORSEASHELL = "이것을 착용하면 아직은 발할라에 가지 않아도 되겠지요!",
		ARMOUREDBOAT = "이것이야말로 바이킹에게 어울리는 배지요!",
		BABYOX = "귀여운 고기군요.",
		BALLPHIN = "공격이 튕겨져 나갈 것 같군요.",
		BALLPHINPOD = "습격단이군요!",
		BAMBOO = "뛰어난 다용도 막대이군요.",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "로키의 노리개인가요?",
		BIOLUMINESCENCE = "이것은 어떤 마법입니까?",
		BLOWDART_POISON = "멀리서 적을 약하게 만들다니. 오딘, 저를 용서해주세요...",
		BOAT_INDICATOR = "I shall launch my craft.",
		BOAT_LANTERN = "그림자 바다의 악한 짐승들이여, 나를 보세요!",
		BOATCANNON = "저의 적을 공격하는 것인가요!?",
		BOATREPAIRKIT = "아주 유용한 화물이지요.",
		BOTTLELANTERN = "정말 신기한 횃불이군요.",
		BURIEDTREASURE = "운의 여신이여, 행운을 내려주시지요.",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "소리와 분노!",
		CAPTAINHAT = "뿔이 있으면 더 좋겠지요.",
		CARGOBOAT = "긴 여행에 어울리는 배군요.",
		CHIMINEA = "어떠한 불이 여기에 숨어있을까요?",
		CIRCLINGSEAGULL = "하늘의 쓰레기군요!",
		CLOTHSAIL = "좋은 돛이군요.",
		COCONADE = "Fire that can be thrown.",
		COCONUT = 
		{
		    GENERIC = "가장 단단한 과일이지요.",
		    PLANTED = "딱딱한 과일이 허약한 나무를 만드는군요.",
		},
		COFFEE = "쓰고, 심장을 뛰게 만들지요.",
		COFFEEBEANS = "난 블랙.",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "바다는 이상한 선물을 주지요.",
		CORALREEF = "단단하고 깨지고 쉬운 곳. 마음에 들어요.",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "수치 때문에 이 구멍으로 들어가는 것일까요?",
		CUTLASS = "물고기의 죽음을 불러오는 위대한 검, 제가 명예롭게 휘두르지요.",
		DEAD_SWORDFISH = "발할라로 가세요, 용감한 물고기.",
		DEPLETED_BAMBOOTREE = "자존심을 가져보세요.",
		DEPLETED_BUSH_VINE = "이제 덩굴 같지 않군요?",
		DOYDOY = "저를 두려워 하는 모습이 보이지 않는군요!",
		DOYDOYBABY = "어린 도이도이 전사, 당신을 기리겠어요.",
		DOYDOYEGG = "이 달걀 안에는 다른 깃털의 바이킹이 자라고 있지요.",
		
		DOYDOYFEATHER = "쓰러진 새 전사의 귀중한 깃털이군요.",
		DOYDOYNEST = "더 용감한 새가 부화할 둥지군요!",
		DUBLOON = "쓰러진 자의 전리품이군요!",
		DUG_BAMBOOTREE = "당신을 심으면 저에게 갚을 것인가요?",
		DUG_BERRYBUSH2 = "저만의 베리 샘이군요!",
		DUG_BUSH_VINE = "덤불이거나 아니거나?",
		DUG_COFFEEBUSH = "커피 한 잔이요.",
		EARRING = "제 귀가 아니군요.",
		FABRIC = "바느질은 전사의 일이 아니지요...",
		FEATHERSAIL = "용감한 새가 아름다운 깃털을 선물했어요!",
		FIRERAIN = "전사의 날씨군요!",
		FIRERAINSHADOW = "오디이시여!",
		FISHINHOLE = "항복할 생각인가요, 물고기?",
		FROG_POISON = "끔찍한 파충류 악당, 돌아가요!",
		GASHAT = "코와 목을 위한 갑옷이군요!",
		GOLDENMACHETE = "자긍심을 가지고 당신을 휘두르겠어요.",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "오딘의 말로 움직일 수 있는 장치군요!",
		JELLYFISH = "당신은 바다 괴물이기에는 너무 작군요.",
		JELLYFISH_COOKED = "바다 괴물이 잘 익었군요!",
		JELLYFISH_DEAD = "바다 괴물이 발할라로 가고 있지요!",
		JELLYFISH_PLANTED = "바다 괴물이 더 크길 바랬지요.",
		JELLYJERKY = "저의 이빨이 당신과 싸우겠어요.",
		JUNGLETREE = "A mighty tree!",
		JUNGLETREE_BURNT = "잘가요, 거인.",
		JUNGLETREE_STUMP = "발할라에서 보지요, 나무 씨.",
		JUNGLETREESEED =
        {
            GENERIC = "씨앗에 들어있는 나무의 힘이지요.",
            PLANTED = "강하게 자라겠군요.",
        },
		LAVAPOOL = "불 웅덩이군요!",
		LIMESTONE = "익지 않은 과일처럼 딱딱하군요.",
		LIMPETS = "돌 고기군요!",
		
		LOBSTER = "전투를 위해 무장했군요, 바다의 거주자여.",
		LOBSTERHOLE = "갑옷을 입은 자가 여기에 사는군요...",
		LOGRAFT = "저를 멀리 옮기지 못해도 일단은 옮기세요.",
		MACHETE = "적당한 길이의 검이군요.",
		MESSAGEBOTTLE = "발할라의 전갈일까요?",
		MESSAGEBOTTLEEMPTY = "전갈도 술도 없군요. 한심하게시리.",
		MOSQUITO_POISON = "독! 겁쟁이의 짓이군요!",
		MUSSEL = "강해 보이지 않는군요.",
		MUSSEL_STICK = "바보 홍합이 이 막대 위를 오르겠군요.",
		OBSIDIAN = "불산의 자갈이군요!",
		OBSIDIAN_WORKBENCH = "불의 공작소군요!",
		OBSIDIANAXE = "이것이야말로 도끼군요!",
		OBSIDIANCOCONADE = "던지는 불은 겁쟁이의 방식이지만, 재미있군요!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "불이 거의 죽었군요.",
			GENERIC = "바이킹에게 어울리는 불이지요!",
			HIGH = "불이 타오르고 있군요!",
			LOW = "불이 서서히 죽고 있군요.",
			NORMAL = "따뜻한 불에 따뜻한 위그프리드지요.",
			OUT = "그리고 빛이 가물거리며 꺼지지요.",
		},
		OBSIDIANMACHETE = "자르는 도구이자 태우는 도구이지요.",
		SPEAR_OBSIDIAN = "타는 느낌이지요.",
		OBSIDIANSPEARGUN = "저는 보통은 근처에서 불을 놓지요.",
		OX = "이 발 달린 잔칫상을 하사하신 오딘께 감사드리지요!",
		PACKIM = "발할라까지 저를 따라오시겠어요?",
		PACKIM_FISHBONE = "신기한 물건이군요.",
		PALMLEAF = "바이킹 사이즈의 잎이지요!",
		PALMTREE =
		{
			BURNING = "나무가 불타고 있군요!",
			BURNT = "로기께서 가져갔군요.",
			CHOPPED = "숲의 전사가 베었군요!",
			GENERIC = "가지를 버렸나요, 나무 씨?",
		},
		PALMTREE_BURNT = "탄 코코넛 냄새가 나는군요.",
		PALMTREE_STUMP = "발할라에서 저의 난로를 불때겠군요.",
		PARROT = "혀를 놀리지 마세요, 새!",
		PEACOCK = "이 깃털을 망치는 안타깝겠군요.",
		PIRATEHAT = "모자가 제 역할... 아니 영혼을 혼란스럽게 만드는군요.",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "땅이 질병을 뿜어내는군요!",
		RAFT = "바이킹은 젖는 것을 두려워하지 않지요!",
		ROWBOAT = "노젓기는 저의 특기지요.",
		SAIL = "묘한 돛이지만 쓸 수 있겠군요.",
		SAND = "무척 깨끗한 흙이군요.",
		SAND_CASTLE = "A scale model of my future keep.",
		SANDBAG = "백에 넣은 모래군요.",
		SANDBAG_ITEM = "홍수를 막아주지요.",
		SANDHILL = "모래고개로 산을 만들지는 않겠어요.",
		SEAGULL = "미천한 새군요!",
		SEAGULL_WATER = "떠있는 물을 더럽히는군요!",
		SEASACK = "역겹지만 나름대로 유용하지요.",
		SEASHELL = "바다의 통화지요.",
		SEASHELL_BEACHED = "작은 요정 방패인가요?",
		SEATRAP = "바다의 전리품을 저에게 가져오세요!",
		SEAWEED = "물기 많은 더러운 풀이군요!",
		
		SEAWEED_PLANTED = "발로 밟을 수 없는 잡초이지요.",
		SHARK_FIN = "쓰러진 전사의 징표군요.",
		SHARX = "손색이 없는 바다의 적이군요!",
		SLOTMACHINE = "운명과 궁상의 기계군요.",
		SNAKE = "미끄러지는 자를 믿지 말아야지요.",
		SNAKE_FIRE = "화산의 입으로 말하는군요!",
		SNAKE_POISON = "악한 송곳니를 저에게 대지 마세요!",
		SNAKESKIN = "뱀이 껍질을 벗었군요. 약간의 도움이 있다면...",
		SNAKESKINHAT = "뱀을 입을까요?",
		SOLOFISH = "바다가 잔치상을 차려주는군요.",
		SPEAR_POISON = "이 창은 겁쟁이에게 승리를 안겨주는군요.",
		SPEARGUN = "겁쟁이 무기댜.",
		SPEARGUN_POISON = "제가 그림자 밑에 숨는 자인가요! 그런가요?",
		SPOILED_FISH = "낭패의 냄새가 나는군요.",
		STUNGRAY = "명예도 신경 쓰지 않고 악취를 풍기나요?",
		SUPERTELESCOPE = "오딘께서 저에게 눈을 빌려주셨지요!",
		SWORDFISH = "내 심장을 원하는 물고기군요!",
		TELESCOPE = "이것이 무슨 묘술인가요?",
		TIGERSHARK = "저를 발할라로 데려가세요, 바다의 악마!",
		TIGERSHARKSHADOW = "짐승의 그림자군요!",
		TORNADO = "바람이 사나워졌군요!",
		TOUCAN = "저와 싸우세요, 긴 코의 새! 그러면 발할라에서 같이 만찬을 즐길 수 있겠지요!",
		TRAWLNET = "바다를 휩쓸겠어요!",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "신에게 어울리는 무기군요!",
		TRINKET_13 = "이것이 무슨 끔찍한 술인가요?",
		TRINKET_14 = "아기 장난감. 아니면 다른 것인가요?",
		TRINKET_15 = "귀찮은 무기군요.",
		TRINKET_16 = "갑옷 조각인가요?",
		TRINKET_17 = "전사가 맨발로 발할라에 가는 것...",
		TRINKET_18 = "이 장인의 실력의 유래를 모르겠군요.",
		TRINKET_19 = "정의의 전사에게는 언제나 맑은 하늘이지요.",
		TURBINE_BLADES = "이것이 무슨 이상한 검인가요?",
		TURF_BEACH = "발가락 사이에서 기분 좋게 느껴지는군요.",
		TURF_JUNGLE = "여기라면 자신을 잃을 수 있겠지요...",
		TWISTER = "바람 아래에서 숨는 악당이군요!",
		VENOMGLAND = "신열을 일으키는 근원이군요.",
		VINE = "저를 위해 무엇을 할 수 있나요?",
		VOLCANO = "불의 산!",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "무기 제작소를 무의미하게 파괴했군요...",
		VOLCANO_EXIT = "명계는 지쳤군요.",
		VOLCANOSTAFF = "불 산의 분노를 부르지요!",
		WALL_LIMESTONE = "훌륭한 솜씨군요.",
		WALL_LIMESTONE_ITEM = "저와 함께 똑바로 설까요?",
		WHALE_BLUE = "당신을 끝내주겠어요, 거물!",
		WHALE_CARCASS_BLUE = "발할라에서 굽겠어요.",
		WHALE_CARCASS_WHITE = "오, 거대한 악취군요.",
		WHALE_WHITE = "당신을 죽이는 것이 영광이겠군요.",
		NEEDLESPEAR = "정말 대단한 전쟁용 창이군요!",
		ARMORCACTUS = "선인장과 친구가 되겠어요.",
		BAMBOOTREE =
		{
			BURNT = "허영의 마법이 불로부터 당신을 구해주지 못했군요.",
			CHOPPED = "자를 수 없군요!",
			GENERIC = "이게 무슨 마법이지요? 텅 빈 나무라니요?",
		},
		BLOWDART_FLUP = "불쌍하게 몰래 다니는 괴물이 떨어뜨린 겁쟁이 무기군요.",
		BLUBBER = "전우들이 좋아하는 것이지요!",
		BLUBBERSUIT = "뉘우치세요, 지방으로 만들어진 옷, 수분으로!",
		BOAT_TORCH = "밤바다를 밝게 만들지요!",
		BRAINJELLYHAT = "제 뇌는 제 검만큼 뛰어나지요!",
		BUOY = "파도 위에 있는 것을 보니 원기가 솟는군요.",
		BUSH_VINE =
		{
			BURNT = "탔군요. 후회는 없지요.",
			CHOPPED = "이발이 필요했지요.",
			GENERIC = "이 덤불은 투구형 머리를 가지고 있군요.",
		},
		COCONADE =
		{
			BURNING = "이 넛은 곳 불을 뿜겠지요!",
			GENERIC = "보통 넛이 아니군요!",
		},
		COCONUT_COOKED = "이 큰 넛을 먹겠어요.",
		COCONUT_HALVED = "넛을 자르니 저에게 안을 보여주는군요!",
		COFFEEBEANS_COOKED = "에너지 넘치는 냄새지요.",
		COFFEEBUSH =
		{
			BARREN = "대항하긴 했나요?",
			GENERIC = "이상한 화산 과일이 맺히는군요.",
			PICKED = "과실이 다시 태어나야겠지요.",
			WITHERED = "약한 덤불이군요!",
		},
		CORAL_BRAIN = "먹으면 그의 지식을 습득하게 될까요?",
		CORAL_BRAIN_ROCK = "신비로운 전지의 물 돌이군요!",
		CRAB =
		{
			GENERIC = "전투를 하지요, 갑옷을 두른 자!",
			HIDDEN = "땅에서 나오세요, 겁쟁이!",
		},
		CRATE = "비밀을 실토하세요, 상자!",
		DOUBLE_UMBRELLAHAT = "이 이상한 투구란 무엇인가요?",
		DOYDOYEGG_COOKED = "이 두려움을 모르는 새의 하사품을 먹겠지요.",
		DOYDOYEGG_CRACKED = "두려움을 모르는 것이 흘러나오는군요.",
		DRAGOON = "배에 불이 들어있는 버서커 전우지요!",
		DRAGOONDEN = "버서커도 어디엔가 살아야겠지요.",
		DRAGOONEGG = "안에 있는 전사의 박동하는 심장 소리를 들을 수 있지요!",
		DRAGOONHEART = "쓰러진 적이 선물을 주었지요!",
		DRAGOONSPIT = "불을 토할 수 있다면 좋겠지요...",
		DUG_ELEPHANTCACTUS = "간단히 말하지요. 당신은 이제 제 것이에요.",
		ELEPHANTCACTUS = "식물 씨, 버서커의 유령이 당신 안에 있군요.",
		ELEPHANTCACTUS_ACTIVE = "이제 땅이 쓸만한 적을 싹틔웠군요!",
		ELEPHANTCACTUS_STUMP = "겁쟁이군요!",
		FISH_RAW = "이 바다 고기가 저에게 도움이 되겠지요.",
		FISH_RAW_SMALL = "이 바다 고기가 저에게 도움이 되겠지요.",
		FISH_RAW_SMALL_COOKED = "이 고기는 제 배 안에서 헤엄치겠지요!",
		FLAMEGEYSER = "땅이 불을 뿜는군요!",
		FLOTSAM = "비밀을 알려면 바다에서 꺼내야지요.",
		FLUP = "비겁한 진흙의 존재군요!",
		FRESHFRUITCREPES = "가볍고 푹신하네요!",
		GRASS_WATER = "롱십에서 뜯을 수 있는 풀이군요!",
		HAIL_ICE = "하늘이 얼음을 던지고 있군요!",
		HOME = "누가 여기에 살겠지요.",
		ICEMAKER =
		{
			HIGH = "기계가 열이 올랐군요!",
			LOW = "얼음을 상당히 덜 뱉는군요.",
			NORMAL = "불에서 얼음으로!",
			OUT = "불이 더 필요하지요!",
			VERYLOW = "불이 꺼지려고 하는군요.",
		},
		JUNGLETREE =
		{
			BURNING = "나무가 타는군요.",
			BURNT = "더 이상 나무가 없지요.",
			CHOPPED = "강한 나무지만 제 도끼만큼 강하진 않지요.",
			GENERIC = "제 고향에는 이러한 나무가 없지요.",
		},
		KNIGHTBOAT = "롱십으로 전장에 빠르게 갈 수 있지요!",
		KRAKEN = "지옥으로 돌아가겠어요!",
		KRAKENCHEST = "전리품이지요!",
		KRAKEN_TENTACLE = "짐승의 팔이군요!",
		LIMPETROCK =
		{
			GENERIC = "고기 돌이군요!",
			PICKED = "지금은 돌에 고기가 없군요...",
		},
		TREEGUARD = "공격하지!",
		LIVINGJUNGLETREE = "당신의 얼굴이 마음에 들지 않는군요!",
		LOBSTER_DEAD = "발할라에서 잠드세요, 갑옷을 두른 자여.",
		LOBSTER_DEAD_COOKED = "갑옷 안에 맛있는 고기가 숨어있군요.",
		LUGGAGECHEST = "바다의 보물을 향유하고 싶군요!",
		MAGIC_SEAL = "이것을 남긴 강력한 전사 마법사를 위해 경의를 가지고 이를 쓰겠어요.",
		MAGMAROCK = "이 돌을 무엇으로 굴릴 수 있지요?",
		MAGMAROCK_FULL = "이 돌을 무엇으로 굴릴 수 있지요?",
		MAGMAROCK_GOLD = "빛나는군요...",
		MAGMAROCK_GOLD_FULL = "빛나는군요...",
		MANGROVETREE = "제 롱십에서 나무를 자른 적은 없었지요!",
		MANGROVETREE_BURNT = "물 위의 모든 것이 탔군요.",
		MARSH_PLANT_TROPICAL = "메마른 식물이지요.",
		MERMFISHER = "대항하지 않는다면 저는 어주민과 싸울 이유가 없지요.",
		MERMHOUSE_FISHER = "어주민들이 여기에 살지요.",
		MONKEYBALL = "원숭이를 즐겁게 해주지요.",
		MONSTERTARTARE = "아직 떠는군요.",
		MOSQUITOSACK_YELLOW = "해충이 질병 주머니를 떨어뜨렸군요.",
		MUSSELBOUILLABAISE = "묽지만 몸을 따뜻하게 만드는군요.",
		MUSSEL_COOKED = "강한 맛이지요.",
		MUSSEL_FARM =
		{
			GENERIC = "홍합을 키우지요.",
			STICKPLANTED = "막대기와 하나가 되는군요...",
		},
		MYSTERYMEAT = "적의 아이의 요리는... 저에게 무엇이지요?",
		OCTOPUSCHEST = "상자가 제물을 담고 있군요.",
		OCTOPUSKING = "거래가 가능한 것 같군요.",
		OXHAT = "이 투구가 제 두피를 마르게 해주겠지요.",
		OX_FLUTE = "저는 리듬감이 없지요...",
		OX_HORN = "멋진 잔을 만들 수 있겠군요!",
		PALMLEAF_HUT = "투구가 비에 젖지 않게 하지요.",
		PARROT_PIRATE = "너무 많이 말하는군요!",
		PEG_LEG = "이 다리가 훌륭한 무기가 되겠군요!",
		PIGTENT = "아침식사의 향기지요!",
		PIKE_SKULL = "고향을 상기시키는군요.",
		PIRATEGHOST = "지옥으로 가세요, 망령!",
		PIRATEPACK = "가슴 근육을 만들어주지요.",
		PIRATIHATITATOR =
		{
			BURNT = "마법이 깜부기불이 되어 떠났군요.",
			GENERIC = "이 어색한 마술은 무엇인가요?",
		},
		PORTAL_SHIPWRECKED = "이 롱십은 전사에게 적합하지 않은 것 같군요.",
		PRIMEAPE = "털도 많고 재미도 있군요.",
		PRIMEAPEBARREL = "뒤죽박죽한 것을 보니 바이킹이 사는 것 같군요.",
		RAWLING = "드디어! 함께 리허설을 할 수 있는 짝이 생겼군요.",
		REDBARREL = "폭발적인 통이군요!",
		ROCK_CHARCOAL = "타는 돌인가요?",
		ROCK_OBSIDIAN = "용암의 돌이군요!",
		SAIL_STICK = "바람에게 명령을 내리지요!",
		SANDBAGSMALL = "이 모래 가방은 물과 싸우지요!",
		SANDBAGSMALL_ITEM = "물이 약하게 부딪히는군요!",
		SAND_CASTLE =
		{
			GENERIC = "거인이 된 것처럼 밟고 싶군요!",
			SAND = "시간이 망가뜨렸군요.",
		},
		SEAWEED_COOKED = "바다 스낵이군요.",
		SEAWEED_DRIED = "쫄깃하군요...",
		SHADOWSKITTISH_WATER = "적이 어렴풋이 보이는군요!",
		SHARKITTEN = "당신의 어머니가 필요한 것이지요...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "무엇이 숨어서 기다리고 있군요!",
			INACTIVE = "지금은 모래일 뿐... 이군요...",
		},
		SHARK_GILLS = "상어 아가미!",
		SHARK_TEETHHAT = "전사의 심장을 원하는 투구지요!",
		SHIPWRECKED_ENTRANCE = "약탈할 수 있는 새로운 땅이군요!",
		SHIPWRECKED_EXIT = "새로운 땅으로...",
		SNAKEDEN =
		{
			BURNT = "탔군요. 후회는 없지요.",
			CHOPPED = "이발이 필요했지요.",
			GENERIC = "이 덤불은 투구형 머리를 가지고 있군요.",
		},
		SNAKEOIL = "이것이 어떠한 강력한 특성을 주는 것인지요?",
		SNAKESKINSAIL = "살해의 결과로 만들어진 돛이지요!",
		SPEAR_LAUNCHER = "오딘의 선물이지요!",
		SUNKEN_BOAT =
		{
			ABANDONED = "바다가 또 하나 집어삼켰군요!",
			GENERIC = "할 말이 있군요!",
		},
		SUNKEN_BOAT_BURNT = "바이킹 장례식이 있었군요...",
		SUNKEN_BOAT_TRINKET_1 = "조잡한 무기인가요?", 
		SUNKEN_BOAT_TRINKET_2 = "어린이의 롱십이군요.", 
		SUNKEN_BOAT_TRINKET_3 = "축축한 초군요.", 
		SUNKEN_BOAT_TRINKET_4 = "바다의 마법이군요.", 
		SUNKEN_BOAT_TRINKET_5 = "제 사이즈가 아니군요.",
		SWEETPOTATOSOUFFLE = "맛있는 공기가 들어있군요!",
		SWEET_POTATO = "단 감자는 들어본 적이 없어요! ...끔찍하군요!",
		SWEET_POTATO_COOKED = "먹진 않겠지만 색이 마음에 드는군요.",
		SWEET_POTATO_PLANTED = "땅에 먹을 수 없는 식물이 들어있군요!",
		SWEET_POTATO_SEEDS = "달콤하게 자라겠군요.",
		SWIMMINGHORROR = "저의 바이킹 장례식을 치르려고 하는지요?",
		TELEPORTATO_SW_BASE = "무언가 없군요.",
		TELEPORTATO_SW_BOX = "무언가의 부분이군요.",
		TELEPORTATO_SW_CRANK = "크랭크지만 어디에 쓰지요?",
		TELEPORTATO_SW_POTATO = "이것이 무슨 장치인지요?",
		TELEPORTATO_SW_RING = "가치가 있는지요?",
		THATCHPACK = "제 창이 구멍을 내지 않길 바라지요.",
		TIDALPOOL = "작은 호수군요!",
		TIDAL_PLANT = "젖은 식물이지요.",
		TIGEREYE = "호랑이상어의 눈을 가졌지요!",
		TRAWLNETDROPPED =
		{
			GENERIC = "풍성한 전리품!",
			SOON = "전리품이 금방 가라앉겠군요.",
			SOONISH = "제 전리품이 곧 가라앉을 것 같군요.",
		},
		TRINKET_20 = "조잡한 무기인가요?", 
		TRINKET_21 = "어린이의 롱십이군요.",
		TRINKET_22 = "축축한 초군요.", 
		TRINKET_23 = "부서진 것이군요.", 
		TROPICAL_FISH = "안에 알록달록한 고기가 있지요!",
		TUNACAN = "항해할 때 오래 가는 음식이군요!",
		TURF_SANDY = "전장의 조각이군요.",
		TURF_ASH = "전장의 조각이군요.",
		TURF_BADLANDS = "전장의 조각이군요.",
		TURF_DECIDUOUS = "전장의 조각이군요.",
		TURF_DESERTDIRT = "전장의 조각이군요.",
		TURF_FUNGUS_GREEN = "전장의 조각이군요.",
		TURF_FUNGUS_RED = "전장의 조각이군요.",
		TURF_MAGMAFIELD = "전장의 조각이군요.",
		TURF_MEADOW = "전장의 조각이군요.",
		TURF_SNAKESKINFLOOR = "적의 껍질을 밟으니 기분 좋군요!",
		TURF_SWAMP = "전장의 조각이군요.",
		TURF_TIDALMARSH = "전장의 조각이군요.",
		TURF_VOLCANO = "전장의 조각이군요.",
		TWISTER_SEAL = "조그만 당신이 그 큰 바람을 만들었단 말인가요!?",
		VOLCANO_ALTAR =
		{
			GENERIC = "불신 제단이 잠들어있군요.",
			OPEN = "제물을 받을 준비가 되었군요!",
		},
		VOLCANO_ALTAR_TOWER = "불신을 위한 제단이군요!",
		VOLCANO_SHRUB = "타버린 것 같군요.",
		WALLYINTRO_DEBRIS = "이것이 제 롱십의 잔해인가요?",
		WATERMELON_SEEDS = "씨 많거든.",
		WATERYGRAVE = "전리품이 아래에 있겠군요!",
		WHALE_BUBBLES = "무언가 아래 있군요.",
		WHALE_TRACK = "고래를 찾겠군요!",
		WILBUR_CROWN = "이것이 도대체 무엇이지요?",
		WILBUR_UNLOCK = "저는 어떠한 왕 앞에서도 무릎 꿇지 않지요, 아무리 귀여워도!",
		WILDBORE = "전우의 느낌이군요!",
		WILDBOREHEAD = "발할라에 저를 위한 잔을 준비해주시지요.",
		WILDBOREHOUSE = "살기 끔찍한 곳이군요!",
		WIND_CONCH = "바람이 느껴지는군요...",
		WOODLEGS_CAGE = "잠긴 우리군요!",
		WOODLEGS_KEY1 = "무엇을 열까?",
		WOODLEGS_KEY2 = "다른 열쇠군요!",
		WOODLEGS_KEY3 = "이상한 열쇠군요!",
		WRECK = "많은 롱십이 발할라의 길에 있군요.",
	},
	DESCRIBE_GENERIC = "이 영역의 유물이군요.",
	DESCRIBE_TOODARK = "전투하기에는 너무 어둡군요.",
	DESCRIBE_SMOLDERING = "화염이 곧 잠식하겠군요.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "가장 신선한 고기!",
	},
}
