return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Ich glaube nicht, dass es das zulassen wird.",
			GENERIC = "Das ist nicht rasierbar.",
			NOBITS = "Aber es ist schon so glatt wie ein Baby-Popo.",
		},
		STORE =
		{
			GENERIC = "Das würde nicht passen. ",
			NOTALLOWED = "Das kann da nicht rein.",
		},
	},
	ACTIONFAIL_GENERIC = "Das funktionierte nicht.",
    LICHEN = "Eine langsam wachsende Höhlenpflanze.",
	ANNOUNCE_ADVENTUREFAIL = "Von allen Leuten, sollte ich in der Lage sein, das zu tun.",
	ANNOUNCE_BEES = "Wenn du mich tötest, bringt dir das deinen Honig auch nicht zurück.",
	ANNOUNCE_BOOMERANG = "Oh! Ungeschickt!",
	ANNOUNCE_CHARLIE = "Charlie? Ich bin's! Maxwell!",
	ANNOUNCE_CHARLIE_ATTACK = "Au! Charlie, das tut weh!",
	ANNOUNCE_COLD = "Mein Herz wird kalt.",
	ANNOUNCE_CRAFTING_FAIL = "Äh... Ich kann das nicht.",
	ANNOUNCE_DEERCLOPS = "Ich höre einen von ihnen kommen.",
	ANNOUNCE_DUSK = "Es wird bald dunkel. Charlie wird aufwachen.",
	ANNOUNCE_EAT =
	{
		GENERIC = "(Schluck!)",
		PAINFUL = "Au! Das hat in meinem Mund wehgetan!",
		SPOILED = "Das war verwest.",
		STALE = "Das Mindesthaltbarkeitsdatum war überschritten.",
	},
	ANNOUNCE_ENTER_DARK = "Es ist dunkel! Ich kann nichts sehen!",
	ANNOUNCE_ENTER_LIGHT = "Das Licht ist zurück.",
	ANNOUNCE_FREEDOM = "Freiheit, immerhin!",
	ANNOUNCE_HIGHRESEARCH = "Mein Hirn schwillt durch die Macht an.",
	ANNOUNCE_HOUNDS = "Die Hunde wachsen unablässig.",
	ANNOUNCE_HUNGRY = "Ich bin innen leer.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Ich rieche Dung und Bestienschweiß.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Verflixt! Es ist entwischt.",
	ANNOUNCE_INV_FULL = "Meine Taschen sind voll.",
	ANNOUNCE_KNOCKEDOUT = "Uhh. Mein Kopf tut weh.",
	ANNOUNCE_LOWRESEARCH = "Das war nicht sehr informativ.",
	ANNOUNCE_MOSQUITOS = "Was für kleine nervige Käfer.",
	ANNOUNCE_NODANGERSLEEP = "Nicht, solange Gefahr besteht!",
	ANNOUNCE_NODAYSLEEP = "Ich kann am Tag nicht schlafen.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Es würde meinen Zeitplan durcheinander bringen, wenn ich jetzt schlafe.",
	ANNOUNCE_NOHUNGERSLEEP = "Ich bin zu hungrig. Ich kann nicht schlafen.",
	ANNOUNCE_NO_TRAP = "Seltsam. Sie haben vergessen sie zu aktivieren.",
	ANNOUNCE_PECKED = "Hab Geduld!",
	ANNOUNCE_QUAKE = "Dieses Rumpeln kann nicht gut sein.",
	ANNOUNCE_RESEARCH = "Wissen ist Macht. Und Macht ist... nun, Macht.",
	ANNOUNCE_THORNS = "Ich habe mir meine Arme zerkratzt, als ich das getan habe.",
	ANNOUNCE_TORCH_OUT = "Verdammt. Ein weiteres Licht ist aus.",
	ANNOUNCE_TRAP_WENT_OFF = "Positiv!",
	ANNOUNCE_UNIMPLEMENTED = "Hmmm, nicht ganz fertig.",
	ANNOUNCE_WORMHOLE = "Igitt! Dort drinnen ist es entsetzlich.",
	ANNOUNCE_CANFIX = "\nIch glaub, ich kann das reparieren!",
	ANNOUNCE_NOSANITY = "Ich habe Kopfschmerzen.",
	ANNOUNCE_NOFUEL = "Ich brauche etwas Albtraum-Kraftstoff.",
	ANNOUNCE_ACCOMPLISHMENT= "Ich muss die irgendwie Zeit überdauern. ",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Das macht es alles irgendwie lohnenswert.",	
	BATTLECRY =
	{
		GENERIC = "Zu den Waffen!",
		PIG = "Verstand über Muskeln!",
		PREY = "Du siehst lecker aus!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Und bleib weg!",
		PIG = "Nächstes Mal, Schwein!",
		PREY = "Du bist meine Zeit nicht wert!",
	},
	DESCRIBE =
	{
		WAXWELLJOURNAL = "Es tut mir so Leid, Charlie.",
		WORMLIGHT = "Netter Trick.",
		WORM =
		{
		    PLANT = "Du legst mich nicht herein, Pflanze.",
		    DIRT = "Da rührt sich etwas.",
		    WORM = "Hm, das ist neu!",
		},
		EEL = "Die existieren nur in den Tiefen.",
		EEL_COOKED = "Das muss reichen.",
		UNAGI = "Kompliment an die Küche!",
		EYETURRET = "Eine meiner besseren Arbeiten.",
		EYETURRET_ITEM = "Jetzt muss ich ihn nur noch aufstellen.",
		MINOTAURHORN = "Tut mir leid, dass ich das tun musste, alter Freund.",
		MINOTAURCHEST = "Es ist fast so, als wäre er noch am Leben.",
		THULECITE_PIECES = "Ich könnte mehrere Haufen kombinieren, um ein größeres Stück zu bekommen.",
		POND_ALGAE = "Das ist eine Alge.",
		GREENSTAFF = "Ich muss den Stab auf die richtige Art und Weise benutzen, damit er funktioniert.",
		POTTEDFERN = "Wie idyllisch.",

		THULECITE = "Ein überaus seltenes aber nützliches Material.",
		ARMORRUINS = "Thulecite passt so gut zu Albtraum-Kraftstoff.",
		RUINS_BAT = "Sie ist von Kraftstoff durchdrungen.",
		RUINSHAT = "Kraftstoff muss fließen.",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "Das Stadtzentrum bleibt.",	
			WARN = "Er pulsiert noch.",	
			WAXING = "Die Impuls wird schneller.", 
			STEADY = "Der Impuls ist anhaltend.", 
			WANING = "Die Impuls schwindet.", 
			DAWN = "Er beruhigt sich wieder.", 
			NOMAGIC = "Der Impuls zeigt hier keine Einflüsse. ", 
		},
		BISHOP_NIGHTMARE = "Sie zerfallen ohne eine angemessene Wartung.",
		ROOK_NIGHTMARE = "Die Erbauer haben es dem Zustand der Herrenlosigkeit überlassen.",
		KNIGHT_NIGHTMARE = "Scheint nicht reparierbar zu sein.",
		MINOTAUR = "Sieh an, sieh an. Der Stoff hat dich verändert.",	
		SPIDER_DROPPER = "Die Kreaturen in dieser Welt entwickeln sich in einem erschreckenden Tempo.",	
		NIGHTMARELIGHT = "Die Überbeanspruchung des Kraftstoffs war ihr Untergang.",	
		RELIC = "Sie waren alle schon tot, als ich hier ankam.",	
		RUINS_RUBBLE = "Ein zerbrochenes Relikt.",	
		MULTITOOL_AXE_PICKAXE = "Ich weiß nicht, wieso ich nicht daran gedacht habe.",	
		GREENGEM = "Der Albtraum-Kraftstoff wird sein wahres Potential freisetzen.",
		ORANGESTAFF = "Ich muss den Stab auf die richtige Art und Weise benutzen, damit er funktioniert.",	
		YELLOWAMULET = "Das wird mich auffallen lassen.",	
		GREENAMULET = "Normalerweise brauch ich das ehrlich nicht.",	

		SLURPER = "Einfache Kreaturen. Sie existieren nur zum Schlafen und Fressen.",
		SLURPER_PELT = "Diese Kreatur wird mir im Tode dienen.",
		ARMORSLURPER = "Nass, durchweicht und komischerweise sättigend.",
		ORANGEAMULET = "Einfache Magie ist oft die beste.",
		YELLOWSTAFF = "Mit einem größeren Edelstein würde er noch mächtiger sein.",
		YELLOWGEM = "Ich kann seine Magie spüren.",
		ORANGEGEM = "Mit ein wenig Kraftstoff wird er noch mächtiger.",
		TELEBASE = 
		{
			VALID = "Das sollte seinen Zweck erfüllen.",
			GEMS = "Die Kraft benötigt mehr Fokuspunkte.",
		},
		GEMSOCKET = 
		{
			VALID = "Er ist bereit.",
			GEMS = "Der Stoff braucht ein Nutzen.",
		},
		STAFFLIGHT = "Das sollte die Schatten verjagen.",
		RESEARCHLAB4 = "Ziemlich schmucke Maschine.",
       	ANCIENT_ALTAR =
        {
        	WORKING = "Wo sind ihre Götter jetzt?",
        	BROKEN = "Das lässt sich teilweise wiederherstellen.",
        },

        ANCIENT_STATUE = "Eine ehemals stolze Rasse.",

		CAVE_BANANA = "Als hätte man Asche im Mund.",
		CAVE_BANANA_COOKED = "Sogar noch schlechter als eine rohe Banane.",
		CAVE_BANANA_TREE = "Sieht zwar aus wie eine Banane, aber das kaufe ich ihm nicht ab.",
		ROCKY = "Ich habe diese Typen aus gutem Grund hier runter verbannt.",
		
		HOUNDSTOOTH="Er könnte für die Mode genutzt werden.",
		ARMORSNURTLESHELL="Die ist überhaupt nicht elegant.",
		BAT="Igitt. Hässliches Biest.",
		BATBAT = "Gewalt hat sich noch nie besser angefühlt.",
		BATWING="Das esse ich nicht.",
		BATWING_COOKED="Das esse ich immer noch nicht.",
		BEDROLL_FURRY="Wenigstens ist es für etwas gut.",
		BUNNYMAN="Er erinnert mich an einen alten",
		FLOWER_CAVE="Es ist so dunkel hier unten.",
		FLOWER_CAVE_DOUBLE="Es ist so dunkel hier unten.",
		FLOWER_CAVE_TRIPLE="Es ist so dunkel hier unten.",
		GUANO="Widerlich!",
		LANTERN="Ich hoffe, das wird sie fernhalten.",
		LIGHTBULB="Es wird irgendwann ausgehen.",
		MANRABBIT_TAIL="Dummes Kaninchen.",
		MUSHTREE_TALL="Er riecht nach Fäule und Versagen.",
		MUSHTREE_MEDIUM="Wo ist Waldo?",
		MUSHTREE_SMALL="Uh, der riecht schlecht.",
		RABBITHOUSE="Oh, ist das nicht clever?",
		SLURTLE="An die kann ich mich nicht erinnern...",
		SLURTLE_SHELLPIECES="Sie passen nicht wieder zusammen.",
		SLURTLEHAT="Der lässt mich standhaft bleiben, wenn ich kämpfen muss.",
		SLURTLEHOLE="Das ist ekelhaft.",
		SLURTLESLIME="Es muss einen besseren Weg geben.",
		SNURTLE="Das ist seltsam. Die müssen neu sein.",
		SPIDER_HIDER="Die ist trickreich.",
		SPIDER_SPITTER="Aggressives kleines Ding, nicht wahr?",
		SPIDERHOLE="Wie ist das hier runter gekommen?",
		STALAGMITE="Steine. Wie dumm. ",
		STALAGMITE_FULL="Steine. Wie dumm. ",
		STALAGMITE_LOW="Steine. Wie dumm. ",
		STALAGMITE_MED="Steine. Wie dumm. ",
		STALAGMITE_TALL="Stalagmit. Wie dumm.",
		STALAGMITE_TALL_FULL="Stalagmit. Wie dumm.",
		STALAGMITE_TALL_LOW="Stalagmit. Wie dumm.",
		STALAGMITE_TALL_MED="Stalagmit. Wie dumm.",

		POWCAKE = "Was für ein verdorbenes Produkt der Wissenschaft ist das?",
		CAVE_ENTRANCE = 
		{
			GENERIC="Ich habe sie vor langer Zeit zugestopft.",
			OPEN = "Das war keine gute Idee!",
		},
        CAVE_EXIT = "Holt mich hier raus!",

		MAXWELLPHONOGRAPH = "Dieses verfluchte Ding!",
		BOOMERANG = "Der macht die Hände schmutzig.",
		PIGGUARD = "Igitt. Widerliches Vieh.",
		ABIGAIL = "Warum bleiben die Sterblichen nicht einfach tot?",
		ADVENTURE_PORTAL = "Hier habe ich das Ding also gelassen!",
		AMULET = "Es leitet die dunkelsten Energien des Universums.",
		ANIMAL_TRACK = "Irgendein dummes Vieh ist hier lang gegangen.",
		ARMORGRASS = "Eine direkte Konfrontation ist ziemlich tölpelhaft.",
		ARMORMARBLE = "Das ist wirklich nicht mein Stil.",
		ARMORWOOD = "Uh. Ich bin kein Freund von solchen geschmacklosen Handgreiflichkeiten.",
		ARMOR_SANITY = "Zeit, um mich mit Alpträumen zu umhüllen.",
		ASH =
		{
			GENERIC = "Ein schönes Pulver, das nach Zerstörung riecht.",
			REMAINS_EYE_BONE = "Keine Sorge. Es gibt noch mehr Chesters.",
			REMAINS_THINGIE = "Dafür gibt es eine völlig wissenschaftliche Erklärung.",
		},
		AXE = "Manchmal ist die direkte Vorgehensweise am besten.",
		BABYBEEFALO = "Sie sind sogar als Kinder hässlich.",
		BACKPACK = "Ich wünschte, es würde hier Träger geben.",
		BACONEGGS = "Kompliment an die Küche!",
		BANDAGE = "Klebrig und pampig. Gut, um es auf Wehwehchen zu legen.",
		BASALT = "Ich habe den Stein so schwer gemacht, dass ich ihn nicht mehr anheben kann.",
		BEARDHAIR = "Haarig.",
		BEDROLL_STRAW = "Ich mag es nicht, hart zu schlafen.",
		BEE =
		{
			GENERIC = "Sie arbeiten so hart, die Narren.",
			HELD = "Was mache ich jetzt damit?",
		},
		BEEBOX =
		{
			FULLHONEY = "So verlockend, aber so voll mit Bienen.",
			GENERIC = "Sie beherbergt meine Bienen.",
			NOHONEY = "Meine Bienen arbeiten nicht hart genug.",
			SOMEHONEY = "Ein sollte ein wenig länger warten.",
		},
		BEEFALO =
		{
			FOLLOWER = "Verdammt, er folgt mir.",
			GENERIC = "Schau dir nur dieses dumme Biest an.",
			NAKED = "Jetzt sieht er dumm UND mitleiderregend aus.",
			SLEEPING = "Er ist nur geringfügig schlauer, wenn er schläft.",
		},
		BEEFALOHAT = "Wie unmodisch.",
		BEEFALOWOOL = "Die riecht wie eine Scheune.",
		BEEHAT = "Ich werde ihn tragen, wenn ich muss.",
		BEEHIVE = "Nicht die Bienen!",
		BEEMINE = "Sie warten geduldig.",
		BEEMINE_MAXWELL = "Vielleicht hätte ich die nicht dort hinlegen sollen.",
		BERRIES = "Seufz. Ich muss.",
		BERRIES_COOKED = "Immerhin ein bisschen verfeinert.",
		BERRYBUSH =
		{
			BARREN = "Er braucht Dünger.",
			GENERIC = "Aufs Beerenessen reduziert. Seufz.",
			PICKED = "Und nun warten wir.",
		},
		BIRDCAGE =
		{
			GENERIC = "Man wird mich nie wieder hinter Gitter bringen.",
			OCCUPIED = "Ich fühle mit dir.",
			SLEEPING = "Du wirst immer noch da drin sein, wenn du wieder aufwachst.",
		},
		BIRDTRAP = "Sie werden weiter darauf reinfallen.",
		BIRD_EGG = "Ich betrachte es gern als ein Gefängnis für Babyvögel.",
		BIRD_EGG_COOKED = "Spiegelei.",
		BISHOP = "Auf diese Stück bin ich besonders stolz.",
		BLOWDART_FIRE = "Sei einfach nur sicher, dass du auch ausatmest.",
		BLOWDART_SLEEP = "Nenn mich Sandmann.",
		BLOWDART_PIPE = "Ein wunderbares Rohr, um Schmerzen auszuteilen.",
		BLUEAMULET = "Es ist überfroren.",
		BLUEGEM = "Blau bewirkt Eis.",
		BLUEPRINT = "Ich weiß alles darüber. Ich habe es nur vergessen.",
		BLUE_CAP = "Was kann schon schiefgehen?",
		BLUE_CAP_COOKED = "Umami!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Die blauen sind für irgendwas gut.",
			INGROUND = "Er ist nicht bereit.",
			PICKED = "Vielleicht ein anderes Mal?",
		},
		BOARDS = "Ungehobelt.",
		BOAT = "Das fährt nirgendwo mehr hin.",
		BONESTEW = "Kompliment an die Küche!",
		BUGNET = "Perfekt, um wehrlose Insekten zu fangen.",
		BUSHHAT = "Für mich gibt es hier Verbesserungspotential.",
		BUTTER = "Einige Wortspiele sind unwiderstehlich.",
		BUTTERFLY =
		{
			GENERIC = "Eine fliegende Blüte.",
			HELD = "Es wäre eine Schande, wenn jemand seine Flügel abreißen würde.",
		},
		BUTTERFLYMUFFIN = "Kompliment an die Küche!",
		BUTTERFLYWINGS = "Hahaha. Ich hab ihn!",
		CAMPFIRE =
		{
			EMBERS = "Ich werde es verlieren.",
			GENERIC = "Wie beruhigend.",
			HIGH = "Das wird Charlie von mir fernhalten.",
			LOW = "Es braucht Brennstoff.",
			NORMAL = "Feurig.",
			OUT = "Es wird nicht zurück kommen.",
		},
		CANE = "In ihm sind Bilder von schnellen Dingen eingeritzt.",
		CARROT = "Ich bin kein Fan von Gemüse.",
		CARROT_COOKED = "Immerhin ein bisschen verfeinert.",
		CARROT_PLANTED = "Wie banal.",
		CARROT_SEEDS = "Diese Arbeit ist unter meine Würde.",
		CAVE_FERN = "Ich würde gern drauftreten.",
		CHARCOAL = "Niemand wird meinen Kohlenstoff stehlen!",
        CHESSJUNK1 = "Mechanischer Abfall.",
        CHESSJUNK2 = "Mechanischer Abfall.",
        CHESSJUNK3 = "Mechanischer Abfall.",
		CHESTER = "Lästiges kleines Monster. Hat jedoch seinen Nutzen.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Hör auf mich anzugucken!",
			WAITING = "Worauf wartet er?",
		},
		COOKEDMANDRAKE = "Er hat die Mehrheit seiner Macht verloren.",
		COOKEDMEAT = "Es riecht jetzt nicht mehr so stark nach Bauernhof.",
		COOKEDMONSTERMEAT = "Ich werde es essen, wenn ich muss.",
		COOKEDSMALLMEAT = "Nun, immerhin bewegt es sich nicht mehr.",
		COOKPOT =
		{
			COOKING_LONG = "Warte drauf...",
			COOKING_SHORT = "Hier kommt es!",
			DONE = "Endlich, ein qualitativ hochwertiges Essen.",
			EMPTY = "Allein der Gedanke daran, macht mir den Mund wässrig.",
		},
		CORN = "Reich an Fruchtzucker.",
		CORN_COOKED = "Immerhin ein bisschen verfeinert.",
		CORN_SEEDS = "Diese Arbeit ist unter meine Würde.",
		CROW =
		{
			GENERIC = "Ich weiß nicht, wie sie hierher gekommen sind.",
			HELD = "Shhhh... meine Hübsche.",
		},
		LICHEN = "Dieser Pilz hat den Untergang überlebt.",
		CUTLICHEN = "Trocken, bröselig, nahrhaft.",
		CUTGRASS = "Das gewöhnlichste Zeug der Erde.",
		CUTREEDS = "Ich denke, ich könnte etwas nützliches daraus bauen.",
		CUTSTONE = "Die Bausteine der Zivilisation.",
		DEADLYFEAST = "Es riecht... giftig.",
		DEERCLOPS = "Vor dem hab selbst ich Angst.",
		DEERCLOPS_EYEBALL = "Deerclops sind kurzsichtig.",
		DEPLETED_GRASS =
		{
			GENERIC = "Es tut niemandem etwas Gutes.",
		},
		DIRTPILE = "Das sieht deplatziert aus.",
		DIVININGROD =
		{
			COLD = "Hauptsächlich nur Nebengeräusche.",
			GENERIC = "Die kann ich verwenden, um meine fehlenden Teile zu finden.",
			HOT = "Es muss genau unter meine Nase sein!",
			WARM = "Das ist die richtige Richtung.",
			WARMER = "Ich sollte meine Augen offen halten.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Das ist der Startmechanismus.",
			READY = "Ich muss die Wünschelrute einsetzen.",
			UNLOCKED = "Fortschritt!",
		},
		DIVININGRODSTART = "Die Portale führen zur nächsten Rute.",
		DRAGONFRUIT = "Exotisch und köstlich.",
		DRAGONFRUIT_COOKED = "Immerhin ein bisschen verfeinert.",
		DRAGONFRUIT_SEEDS = "Diese Arbeit ist unter meine Würde.",
		DRAGONPIE = "Kompliment an die Küche!",
		DRUMSTICK = "Schmeckt seltsamerweise nach Beeren.",
		DRUMSTICK_COOKED = "Schmeckt immer noch nach Beeren.",
		DUG_BERRYBUSH = "Sehe ich wie ein Gärtner aus?",
		DUG_GRASS = "Sehe ich wie ein Gärtner aus?",
		DUG_MARSH_BUSH = "Sehe ich wie ein Gärtner aus?",
		DUG_SAPLING = "Sehe ich wie ein Gärtner aus?",
		DURIAN = "Das ist etwas für Kenner.",
		DURIAN_COOKED = "Immerhin ein bisschen verfeinert.",
		DURIAN_SEEDS = "Diese Arbeit ist unter meine Würde.",
		EARMUFFSHAT = "Wenigstens hält er warm.",
		EGGPLANT = "Nur eine weitere langweilige Pflanze.",
		EGGPLANT_COOKED = "Immerhin ein bisschen verfeinert.",
		EGGPLANT_SEEDS = "Diese Arbeit ist unter meine Würde.",
		EVERGREEN =
		{
			BURNING = "Hoppla!",
			BURNT = "In Feuer gebadet.",
			CHOPPED = "Er scheint nicht wieder nachzuwachsen.",
			GENERIC = "Ich hörte, wie sie ihn als 'harzig' beschreiben.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Ups.",
			BURNT = "Staub zu Staub.",
			CHOPPED = "Ich habe ihn von seinem Elend befreit.",
			GENERIC = "Er sieht kränklich aus.",
		},
		EYEPLANT = "Die Schachfiguren der Fleischzwiebel.",
		FARMPLOT =
		{
			GENERIC = "Sehe ich wie ein Bauer aus?",
			GROWING = "Ich habe bessere Dinge zu tun, als den Pflanzen beim Wachsen zuzuschauen.",
			NEEDSFERTILIZER = "Sie muss... aufgefrischt werden.",
		},
		FEATHERHAT = "Ich werde sie mit meinem Gefieder anlocken.",
		FEATHER_CROW = "Schwarz ist die Farbe des Schlafes.",
		FEATHER_ROBIN = "Rot ist die Farbe des Feuers.",
		FEATHER_ROBIN_WINTER = "Grau ist die Farbe des Schmerzes.",
		FEM_PUPPET = "Lieber sie als ich.",
		FIREFLIES =
		{
			GENERIC = "Wie schön!",
			HELD = "Ich könnte es zerquetschen, wenn ich wollte.",
		},
		FIREHOUND = "Als Scherz habe ich Feueredelsteine in sie eingebaut.",
		FIREPIT =
		{
			EMBERS = "Ich sollte mich darum kümmern.",
			GENERIC = "Eine Feuerstelle.",
			HIGH = "Ein tosendes Feuer.",
			LOW = "Es wird kleiner.",
			NORMAL = "Es ist heiß.",
			OUT = "Es ist abgekühlt.",
		},
		FIRESTAFF = "Ein einfacher, aber wirksamer Zauber.",
		FISH = "Frisch aus den finsteren Tiefen.",
		FISHINGROD = "Ich werde mein Leben lang etwas zu essen haben.",
		FISHSTICKS = "Kompliment an die Küche!",
		FISHTACOS = "Kompliment an die Küche!",
		FISH_COOKED = "Er stinkt noch.",
		FLINT = "Au! Ich habe mir in den Finger geschnitten!",
		FLOWER = "Mich erfüllt das irrationale Verlangen, auf sie draufzutreten.",
		FLOWERHAT = "Definitiv nicht mein Stil.",
		FLOWER_EVIL = "Ich mag diese Blume.",
		FOLIAGE = "Eine geeignete Mahlzeit für einen Bauern.",
		FOOTBALLHAT = "Jetzt bin ich bereit für ein Trainingsspiel.",
		FROG =
		{
			DEAD = "Er quakte.",
			GENERIC = "Er springt und leckt an Dingen.",
			SLEEPING = "Er sieht müde aus.",
		},
		FROGGLEBUNWICH = "Kompliment an die Küche!",
		FROGLEGS = "Muskulös.",
		FROGLEGS_COOKED = "Zäh.",
		FRUITMEDLEY = "Kompliment an die Küche!",
		GEARS = "Meine Haustiere! Was ist aus ihnen geworden?",
		GHOST = "Er erinnert sich an mich!",
		GOLDENAXE = "Sie wird mit jedem Schwung schärfer.",
		GOLDENPICKAXE = "Das muss Spielelogik sein.",
		GOLDENPITCHFORK = "Ich bin mir nicht sicher, ob das eine gute Investition war.",
		GOLDENSHOVEL = "Diese Schaufel ist eine fürstliche Summe wert.",
		GOLDNUGGET = "Damals war mir das noch wichtig.",
		GRASS =
		{
			BARREN = "Braucht Dünger.",
			BURNING = "Ups.",
			GENERIC = "Buschig.",
			PICKED = "Nichts zum Ernten.",
		},
		GREEN_CAP = "Ich sollte es essen.",
		GREEN_CAP_COOKED = "Salzig!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Grüner Pilz.",
			INGROUND = "Wann kommen die wieder raus?",
			PICKED = "Kenn ich schon!",
		},
		GUNPOWDER = "Das mag ich.",
		HAMBAT = "Eine würdelose Waffe für eine weniger gebildete Zeit.",
		HAMMER = "Es fühlt sich gut an, die Arbeit von anderen zunichte zu machen.",
		HEALINGSALVE = "Nur ein wenig Gift und ein bisschen dreckige alte Asche.",
		HEATROCK =
		{
			COLD = "Angenehm kühl.",
			GENERIC = "Eine Tasche voll Stein und Temperatur.",
			HOT = "Er ist fast zu heiß, um ihn festzuhalten.",
			WARM = "Angenehm lauwarm.",
		},
		HOME = "Es gibt keinen Ort wie diesen.",
		HOMESIGN = "Dort steht... nichts.",
		HONEY = "Sticky und süß.",
		HONEYCOMB = "Sie ist voll von Bienensamen.",
		HONEYHAM = "Kompliment an die Küche!",
		HONEYNUGGETS = "Kompliment an die Küche!",
		HORN = "Rufe die Bestien herbei!",
		HOUND = "Sie erkennen mich nicht!",
		HOUNDBONE = "Hungrige Teufel, nicht wahr?",
		HOUNDMOUND = "Ein Tunnel, der hinunter ins Hundenest führt.",
		ICEBOX = "Ein kleines Stück Winter in einem Kasten.",
		ICEHOUND = "Ich hatte viele überschüssige Edelsteine!",
		INSANITYROCK =
		{
			ACTIVE = "Jetzt kann ich seine wahre Natur sehen!",
			INACTIVE = "Auf dieser Ebene existiert er nur zur Hälfte.",
		},
		JAMMYPRESERVES = "Kompliment an die Küche!",
		KABOBS = "Kompliment an die Küche!",
		KILLERBEE =
		{
			GENERIC = "Weswegen ist diese Biene so verärgert?",
			HELD = "Ich habe einem Tiger am Schwanz gepackt.",
		},
		KNIGHT = "Das nenn ich Qualität!",
		KOALEFANT_SUMMER = "Ein entfernter Verwandter des Beefalos.",
		KOALEFANT_WINTER = "Er hat seinen Wintermantel an.",
		KRAMPUS = "Du kriegst mich nicht!",
		KRAMPUS_SACK = "Er ist wirklich leicht.",
		LEIF = "Widerliche Kreatur!",
		LEIF_SPARSE = "Widerliche Kreatur!",
		LIGHTNING_ROD =
		{
			CHARGED = "Sie wird von Energie durchströmt.",
			GENERIC = "Ein klein wenig Schutz.",
		},
		LITTLE_WALRUS = "Ein Splitter vom alten Block.",
		LIVINGLOG = "Ich mag das Geräusch, das sie machen, wenn Sie sie verbrennen.",
		LOCKEDWES = "Er hat mich verärgert.",
		LOG =
		{
			BURNING = "Nun. Es hat Spaß gemacht, solange er brannte.",
			GENERIC = "Ein Stück Holz. Was gibt es da noch zu sagen?",
		},
		LUREPLANT = "Eine bösartige Pflanze.",
		LUREPLANTBULB = "Vielleicht kann ich das zu meinem Vorteil verwenden.",
		MALE_PUPPET = "Lieber er als ich.",
		MANDRAKE =
		{
			DEAD = "Meine Ohren klingeln immer noch.",
			GENERIC = "Wirst du endlich SCHWEIGEN?",
			PICKED = "Was für eine verstörende Wurzel.",
		},
		MANDRAKESOUP = "Kompliment an die Küche!",
		MANDRAKE_COOKED = "Sieht so aus, als hätte sie den letzten Laut von sich gegeben.",
		MARBLE = "Das ist starkes Zeug.",
		MARBLEPILLAR = "Ich habe mich immer gefragt, wer die gebaut hat.",
		MARBLETREE = "Wie skurril.",
		MARSH_BUSH =
		{
			BURNING = "Ich sollte ihm Fragen stellen.",
			GENERIC = "Er ist verdorben und dornig. Genau wie ich!",
			PICKED = "Das war schmerzhaft.",
		},
		MARSH_PLANT = "Was für eine typische, kleine Pflanze.",
		MARSH_TREE =
		{
			BURNING = "Das war's dann wohl.",
			BURNT = "Jetzt nützt es niemandem mehr etwas.",
			CHOPPED = "Baum: 0, Maxwell: 1.",
			GENERIC = "Ein Baum mit einem verdorbenen Verhalten.",
		},
		MAXWELL = "Sieht gut aus!",
		MAXWELLHEAD = "Hey, gutaussehend.",
		MAXWELLLIGHT = "Ohh, es erinnert sich an mich.",
		MAXWELLLOCK = "Dadurch behält der Meister den Vorsitz.",
		MAXWELLTHRONE = "Es ist weniger schmerzhaft als es aussieht.",
		MEAT = "Ich bin wesentlich bessere Kost gewohnt.",
		MEATBALLS = "Kompliment an die Küche!",
		MEATRACK =
		{
			DONE = "Wie die Wüste.",
			DRYING = "Immer noch feucht.",
			GENERIC = "Es wird zum Trocknen von Fleisch genutzt, damit es länger hält.",
		},
		MEAT_DRIED = "Meine Zähne werden zu alt dafür.",
		MERM = "Sie waren schon hier, als ich herkam.",
		MERMHEAD = "Die Augen folgen einem noch.",
		MERMHOUSE = "Sie imitieren die Schweine, sind aber weit weniger intelligent.",
		MINERHAT = "Irgendwann wird das Glühwürmchen verhungern.",
		MONKEY = "Ich habe keine Zeit für dich!",
		MONKEYBARREL = "Was für ein widerliches Zuhause.",
		MONSTERLASAGNA = "Kompliment an die Küche!",
		MONSTERMEAT = "Wie ekelhaft.",
		MONSTERMEAT_DRIED = "Meine Zähne werden zu alt dafür.",
		MOSQUITO =
		{
			GENERIC = "Verdammte blutsaugende Blutsauger.",
			HELD = "Ich hab ihn.",
		},
		MOSQUITOSACK = "Ein blutiger Sack. Mit Blut darin.",
		MOUND =
		{
			DUG = "Das habe ich bereits.",
			GENERIC = "Was liegt wohl darunter?",
		},
		NIGHTLIGHT = "Es brennt in einem wunderschönen Schein.",
		NIGHTMAREFUEL = "Ahhh. Erfrischend.",
		NIGHTSWORD = "Kicher-Snack!",
		NITRE = "Ein Drittel des Weges...",
		ONEMANBAND = "Sie hat einen guten Rhythmus und man kann dazu tanzen.",
		PANDORASCHEST = "Das ist eine Falle.",
		PANFLUTE = "Ich bin dabei, ein Lied des Wahnsinn zu singen.",
		PAPYRUS = "Eine leere Leinwand.",
		PENGUIN = "Netter Smoking.",
		PERD = "Er ist süchtig nach gegorenen Beeren.",
		PEROGIES = "Kompliment an die Küche!",
		PETALS = "Wie Konfetti.",
		PETALS_EVIL = "Die triefen vor lauter Albtraumgehalt.",
		PICKAXE = "Jeder liebt ein wenig Bergbau.",
		PIGGYBACK = "Oh, das ist einfach nur erniedrigend.",
		PIGHEAD = "Äh... wie charmant.",
		PIGHOUSE =
		{
			FULL = "Ich würde auch hineingehen, wenn ich ein Schwein wäre.",
			GENERIC = "Das ist scheinbar ihr einziges Kunststück.",
			LIGHTSOUT = "Ich werde das Schweinehaus wegpusten.",
		},
		PIGKING = "Das ist ein Mann, dessen Prioritäten in Ordnung sind!",
		PIGMAN =
		{
			DEAD = "Ich nenne dich 'Speck'.",
			FOLLOWER = "Er ist zwar dumm, aber er gehört mir.",
			GENERIC = "Was für ein sabbernder Narr.",
			GUARD = "Sie beginnen, sich zu organisieren.",
			WEREPIG = "Dieser ist wild geworden.",
		},
		PIGSKIN = "Es galt 'Er oder ich'.",
		PIGTENT = "Das ist einfach nur widerlich.",
		PIGTORCH = "Super. Jetzt haben sie Feuer.",
		PINECONE = 
		{
		    GENERIC = "Jemand der gerne an der frischen Luft ist, könnte damit vielleicht was anfangen.",
		    PLANTED = "Hm, er scheint in den Boden zu gehören.",
		},
		PITCHFORK = "Das richtige Werkzeug für Perfektionisten.",
		PLANTMEAT = "Ein schwacher Versuch, die mit dem begrenzten Verstand hereinzulegen.",
		PLANTMEAT_COOKED = "Durch die Hitze wurde es erst zu einer ordentlichen Mahlzeit.",
		PLANT_NORMAL =
		{
			GENERIC = "Das ist eine typische Pflanze.",
			GROWING = "Sie wächst.",
			READY = "Sie ist bereit.",
		},
		POMEGRANATE = "Normalerweise würde ich jemanden dazu bringen, das für mich auszusäen.",
		POMEGRANATE_COOKED = "Immerhin ein bisschen verfeinert.",
		POMEGRANATE_SEEDS = "Diese Arbeit ist unter meine Würde.",
		POND = "Ich kann die Reflektion meines Gesichts auf der Oberfläche sehen.",
		POOP = "Das ist der Lauf des sterblichen Lebens.",
		PUMPKIN = "Halloween hat mir schon immer gefallen.",
		PUMPKINCOOKIE = "Kompliment an die Küche!",
		PUMPKIN_COOKED = "Immerhin ein bisschen verfeinert.",
		PUMPKIN_LANTERN = "Hallo, Mr. Kürbis.",
		PUMPKIN_SEEDS = "Diese Arbeit ist unter meine Würde.",
		PURPLEAMULET = "Er spricht mit den Schatten.",
		PURPLEGEM = "Violett bringt große Kraft mit sich. ",
		RABBIT =
		{
			GENERIC = "Ich bin einfach schon zu lange hier - es sieht wirklich köstlich aus.",
			HELD = "Keine Sorge, Kaninchen. Alles unter Kontrolle.",
		},
		RABBITHOLE = "Dort unten existiert eine weitere Welt.",
		RAINOMETER = "Ich kann auch einfach nach oben schauen, um dasselbe hervorzusagen.",
		RATATOUILLE = "Kompliment an die Küche!",
		RAZOR = "Wenn nur die Welt einen eigenen Hals hätte.",
		REDGEM = "Rot bringt Feuer.",
		RED_CAP = "Ich habe vergessen, was der bewirkt.",
		RED_CAP_COOKED = "Irgendwie bitter.",
		RED_MUSHROOM =
		{
			GENERIC = "Das ist ein roter Pilz.",
			INGROUND = "Ich werde später nochmals wiederkommen müssen.",
			PICKED = "Er ist ganz verbraucht. ",
		},
		REEDS =
		{
			BURNING = "Ups.",
			GENERIC = "Das ist Wassergras.",
			PICKED = "Keine weiteren Röhren.",
		},
        RELIC = 
        {
            GENERIC = "Reste von einer ausgestorbenen Zivilisation.",
            BROKEN = "Kleine Steinstückchen.",
        },
        RUINS_RUBBLE = "Ein zerbrochenes Relikt.",
        RUBBLE = "Kleine Steinstückchen.",
		RESEARCHLAB = "Ich kann nicht glauben, dass ich vergessen habe, wie man diese Dinge baut.",
		RESEARCHLAB2 = "Es schaltet Rezepte für durchschnittliche Versorgungseinrichtungen frei.",
		RESEARCHLAB3 = "Hier betreibe ich meine persönliche Forschung.",
		RESURRECTIONSTATUE = "Ich bin mir nicht zu schade, die zu verwenden.",
		RESURRECTIONSTONE = "Dahinter verbirgt sich eine Geschichte...",
		ROBIN =
		{
			GENERIC = "Der rote Vogel kommt aus den Feuerländern.",
			HELD = "Ruhe, Vogel!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Den erkenne ich nicht wieder.",
			HELD = "Sei still.",
		},
		ROBOT_PUPPET = "Besser er als ich.",
		ROCK_LIGHT =
		{
			GENERIC = "Eine verkrustete Lavagrube.",
			OUT = "Er sieht harmlos aus.",
			LOW = "Die Feuer kühlen ab.",
			NORMAL = "Es ist heiß.",
		},
		ROCK = "Das ist ein Stein.",
		ROCKS = "Hmmm. Was mache ich jetzt damit?",
        ROOK = "Eine Festung als Zuhause.",
		ROPE = "Man sollte meinen, dass man damit mehr tun könnte.",
		ROTTENEGG = "Widerlich. Wieso trage ich das mit mir rum?",
		SANITYROCK =
		{
			ACTIVE = "Jetzt kann ich seine wahre Natur sehen!",
			INACTIVE = "Dieses Hindernis kann in zwei verschiedenen Zuständen gefunden werden.",
		},
		SAPLING =
		{
			BURNING = "Ups.",
			GENERIC = "Ein biegsamer, holziger Stängel.",
			PICKED = "Er wird wieder wachsen.",
		},
		SEEDS = "Ich nehme an, dass sie sich nicht selbst anpflanzen.",
		SEEDS_COOKED = "Ich habe das gesamte Leben aus ihnen rausgekocht.",
		SEWING_KIT = "Ein gutes und stattliches Bestreben.",
		SHOVEL = "Dies ist eine wirklich fortschrittliche Technologie.",
		SILK = "Ungeachtet seines Ursprungs, könnte man daraus gute Kleidung herstellen.",
		SKELETON = "Ha! An den erinnere ich mich.",
		SKULLCHEST = "Das ist eine schicke Truhe.",
		SMALLBIRD =
		{
			GENERIC = "Was!? Was willst du?",
			HUNGRY = "Willst du was zu essen?",
			STARVING = "Er ist so hungrig!",
		},
		SMALLMEAT = "Das ist nicht mal ein Mundvoll.",
		SMALLMEAT_DRIED = "Meine Zähne werden zu alt dafür.",
		SPEAR = "Das ist ein Speer. Ja.",
		SPIDER =
		{
			DEAD = "Platsch.",
			GENERIC = "Sie ist überwiegend ein Verdauungssystem.",
			SLEEPING = "Shhhh! Sie wird hungrig aufwachen.",
		},
		SPIDERDEN = "Hier werden sie erwachsen.",
		SPIDEREGGSACK = "Matschig.",
		SPIDERGLAND = "Unangenehm.",
		SPIDERHAT = "Spinnen haben einen solch formbaren Willen.",
		SPIDERQUEEN = "Vielleicht kann ich ihr noch aus dem Weg gehen.",
		SPIDER_WARRIOR =
		{
			DEAD = "Platsch.",
			GENERIC = "Das ist eine spezialisierte Form.",
			SLEEPING = "Ich will ihn nicht aufwecken.",
		},
		SPOILED_FOOD = "Das war mal Nahrung, bis ich sie verschwendet habe.",
		STATUEHARP = "Nicht meine beste Arbeit.",
		STATUEMAXWELL = "Jetzt ist es eine schön Statue.",
		STINGER = "Er trieft vor Gift.",
		STRAWHAT = "Ein geeigneter Hut für einen Bauern.",
		STUFFEDEGGPLANT = "Kompliment an die Küche!",
		SUNKBOAT = "So sollte man ein Boot nicht benutzen.",
		SWEATERVEST = "Zwar kein Dreiteiler, aber trotzdem elegant.",
		TAFFY = "Kompliment an die Küche!",
		TALLBIRD = "Das war ein erfolgloses Experiment.",
		TALLBIRDEGG = "Wegen dieser Dinge haben langbeinige Vögel so ein Territorialverhalten.",
		TALLBIRDEGG_COOKED = "Es schmeckt, wie zerstörte Träume.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Es wird lauwarm.",
			GENERIC = "Hier ist ein lebendes Exemplar.",
			HOT = "Heiß genug für dich?",
			LONG = "Das wird eine Weile dauern.",
			SHORT = "Es ist jeden Moment soweit...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Nun, das ist verlockend.",
			PICKED = "Aus dreckigem Beefalo-Haar gemacht.",
		},
		TEENBIRD =
		{
			GENERIC = "Jetzt, wo er gewachsen ist, ist er nicht mehr so süß.",
			HUNGRY = "Sie essen sicher viel.",
			STARVING = "Eine hungriges Biest ist eine gefährliche Bestie.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Es lebt!",
			GENERIC = "Meine schöne Maschine ist zerbrochen!",
			LOCKED = "Jetzt könnte ich es einschalten.",
			PARTIAL = "Es ist immer noch unvollständig.",
		},
		TELEPORTATO_BOX = "Das ist ein Kasten voller Traurigkeit und Kummer.",
		TELEPORTATO_CRANK = "Das wird benutzt, um die Gemüter zu erregen.",
		TELEPORTATO_POTATO = "Die Zahnräder sind so klein, dass sie die Realität auf den Kopf stellen.",
		TELEPORTATO_RING = "Das ist das Schutzband des Quantenfelds.",
		TELESTAFF = "Macht kann erstaunliche Dinge bewirken, wenn sie durch die richtigen Kanäle kanalisiert wird.",
		TENT = "Das ist für meinen Geschmack ein bisschen zu rustikal.",
		TENTACLE = "Ich bin froh, dass der Rest noch dort unten ist.",
		TENTACLESPIKE = "Igitt. Das ist so ekelhaft.",
		TENTACLESPOTS = "Damit vermehren sie sich.",
		TENTACLE_PILLAR = "Wie tief geht die runter?",
		TENTACLE_GARDEN = "Komisch.",
        TENTACLE_PILLAR_ARM = "Babys?",
		TOPHAT = "Eine edle Herrenbekleidung.",
		TORCH = "Sie hält Charlie in Schach.",
		TRAP = "Nur die dümmsten Tiere werden darauf reinfallen.",
		TRAP_TEETH = "Das Ding kann ganz schön zuschlagen.",
		TRAP_TEETH_MAXWELL = "Ich bin mir sicher, dass ich meine Gründe hatte, als ich sie ausgelegt habe.",
		TREASURECHEST = "Ein Platz, um Beute zu lagern.",
		TREASURECHEST_TRAP = "Hmmm. Sieht verdächtig aus.",
		TREECLUMP = "Ich komme da nicht durch.",
		TRINKET_1 = "Das war mal wichtig für jemanden.",
		TRINKET_10 = "Das war mal wichtig für jemanden.",
		TRINKET_11 = "Das war mal wichtig für jemanden.",
		TRINKET_12 = "Das war mal wichtig für jemanden.",
		TRINKET_2 = "Das war mal wichtig für jemanden.",
		TRINKET_3 = "Das war mal wichtig für jemanden.",
		TRINKET_4 = "Das war mal wichtig für jemanden.",
		TRINKET_5 = "Das war mal wichtig für jemanden.",
		TRINKET_6 = "Das war mal wichtig für jemanden.",
		TRINKET_7 = "Das war mal wichtig für jemanden.",
		TRINKET_8 = "Das war mal wichtig für jemanden.",
		TRINKET_9 = "Das war mal wichtig für jemanden.",
		TRUNKVEST_SUMMER = "Es ist mehr eine Herbstweste.",
		TRUNKVEST_WINTER = "Es ist wirklich schwer, sich im Winter elegant zu kleiden.",
		TRUNK_COOKED = "Wenigstens ist der Schleim verbrannt.",
		TRUNK_SUMMER = "Voll von Sommerschleim.",
		TRUNK_WINTER = "Der Rüssel wird im Winter dicker, damit er mehr Schleim aufnehmen kann.",

		TURF_CARPETFLOOR = "Das ist eine qualitative, vielschichtige Teppichprobe.",
		TURF_CHECKERFLOOR = "Das ist mein natürlicher Lebensraum.",
		TURF_DIRT = "Staubig.",
		TURF_FOREST = "Riecht wie Matsch.",
		TURF_GRASS = "Kratzig.",
		TURF_MARSH = "Der trieft gänzlich.",
		TURF_ROAD = "Dieser ist wenigstens nützlich.",
		TURF_ROCKY = "Irgendwie rau.",
		TURF_SAVANNA = "Dreckig.",
		TURF_WOODFLOOR = "Ich bevorzuge Hartholz.",

		TURF_CAVE="Erdboden.",
		TURF_FUNGUS="Erdboden.",
		TURF_SINKHOLE="Erdboden.",
		TURF_UNDERROCK="Erdboden.",
		TURF_MUD="Erdboden.",

		TURKEYDINNER = "Wie festlich.",
		TWIGS = "Gewöhnlich, aber nützlich.",
		UMBRELLA = "Er ist krumm!",
		WAFFLES = "Kompliment an die Küche!",
		WALL_HAY = "Das ist ein Pulverfass.",
		WALL_HAY_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALL_STONE = "Die sollten das Gesindel draußen halten.",
		WALL_STONE_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALL_WOOD = "Halbwegs widerstandsfähig, aber leicht entzündlich.",
		WALL_WOOD_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALL_RUINS = "Eine antike Mauer.",
		WALL_RUINS_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALRUS = "Erkennen Sie mich nicht?",
		WALRUSHAT = "Hergestellt in Schottland.",
		WALRUS_CAMP =
		{
			EMPTY = "Ich sollte am besten nicht hier sein, wenn der Winter kommt.",
			GENERIC = "Das Walross kann nicht weit sein.",
		},
		WALRUS_TUSK = "Ich werde dafür eine besseren Nutzen finden.",
		WASPHIVE = "Das sieht gefährlich aus.",
		WETGOOP = "Kompliment an die Küche!",
		WINTERHAT = "Enttäuschend bodenständig.",
		WINTEROMETER = "Nicht die hilfreichste Erfindung, oder?",
		WORMHOLE =
		{
			GENERIC = "Es ist schlechter zu wissen, wie die andere Seite aussieht.",
			OPEN = "Ich kann dir versichern, dass es schlechter riecht als es aussieht.",
		},
		WORMHOLE_LIMITED = "Es sieht krank aus.",
		ACCOMPLISHMENT_SHRINE = "Selbst SIE hätten etwas so hinterhältiges nicht bauen können.",		
		LIVINGTREE = "Er hat ein Gesicht.",
		ICESTAFF = "Cooler Stab.",
	},
	DESCRIBE_GENERIC = "Sag du es mir.",
	DESCRIBE_TOODARK = "Ich kann in der Dunkelheit nichts sehen.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Das schmeckt so gut, das würde man nicht glauben.",
	},
}
