return {
	ANNOUNCE_ADVENTUREFAIL = "Tym razem wygrałeś, Maxwellu!",
	ANNOUNCE_BOOMERANG = "Głupi bumerang!",
	ANNOUNCE_CHARLIE = "Nie boję się ciebie!",
	ANNOUNCE_CHARLIE_ATTACK = "AUĆ! Ty małpo!",
	ANNOUNCE_COLD = "Co za mróz! Aż pali!",
	ANNOUNCE_DUSK = "Nadchodzi noc. Potrzebuję ognia!",
	ANNOUNCE_EAT =
	{
		GENERIC = "Mniam!",
		PAINFUL = "Uch! Okropieństwo!",
		SPOILED = "To było ohydne!",
		STALE = "Trochę obrzydliwe.",
	},
	ANNOUNCE_HOUNDS = "Pokażcie się!",
	ANNOUNCE_HUNGRY = "Jestem głodna!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Znajdę cię!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Ach... uciekł.",
	ANNOUNCE_ACCOMPLISHMENT= "Rusz się, strzałko! NO DALEJ!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "UDAŁO SIĘ!",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "Hi, hi!",
		[2] = "Piękny!",
		[3] = "Ups!",
		[4] = "Rozpaliłam ogień!",
		[5] = "Płoń!",
		[6] = "Nie mogę się powstrzymać!",
	},
	ANNOUNCE_PECKED = "Nie! Niegrzeczny ptaszek!",
	ANNOUNCE_TORCH_OUT = "Mój skarb zgasł!",
	ANNOUNCE_WORMHOLE = "Będę musiała spalić te ciuchy!",
	ANNOUNCE_TRAP_WENT_OFF = "Aaa!",
    ANNOUNCE_CRAFTING_FAIL = "Czegoś brakuje.",
    ANNOUNCE_QUAKE = "Ten dźwięk na pewno nie wróży nic dobrego.",
    ANNOUNCE_NODANGERSLEEP = "Nie czas na odpoczynek! Trzeba się zająć walką!",
    ANNOUNCE_NOHUNGERSLEEP = "Burczy mi w brzuchu. Nie zasnę w takim stanie!",
    ANNOUNCE_FREEDOM = "Jestem wolna! Nadszedł czas ognia!",
    ANNOUNCE_RESEARCH = "Przydało się, chociaż nie ma nic wspólnego z ogniem.",
    ANNOUNCE_NO_TRAP = "To jak podpalić beczkę ryb.",
    ANNOUNCE_HIGHRESEARCH = "Tyle informacji!",
    ANNOUNCE_THORNS = "Auć!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Zbyt tu straszno, żeby spać.",
    ANNOUNCE_BEES = "Aaaaa! Kłujące robale!",
    ANNOUNCE_KNOCKEDOUT = "Argh! Moja głowa!",
    ANNOUNCE_LOWRESEARCH = "Buu, co za nuda.",
    ANNOUNCE_DEERCLOPS = "Brzmiało jak ogromny, wredny monstroludź!",
    ANNOUNCE_MOSQUITOS = "Uciekajcie, krwiopijcze bestie!",
    ANNOUNCE_NODAYSLEEP = "Nie zasnę, gdy na niebie świeci wielka kula ognia.",
	ANNOUNCE_CANFIX = "\nChyba umiałabym to naprawić!",
	BATTLECRY =
	{
		GENERIC = "Albo ty, albo ja!",
		PIG = "Głupi prosiak!",
		PREY = "Chodź tutaj!",
		SPIDER = "Grrrrar!",
		SPIDER_WARRIOR = "Fuuuj, zaaabiiić!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Tak właśnie myślałam!",
		PIG = "Wracaj tu, szyneczko!",
		PREY = "Dopadnę cię następnym razem!",
		SPIDER = "Ech, zabiję go później.",
		SPIDER_WARRIOR = "Jednak nie taki z ciebie twardziel!",
	},
	DESCRIBE =
	{
		WORMLIGHT = "Światło bez ognia. To sprzeczne z naturą.",
		WORM =
		{
		    PLANT = "Światło bez ognia. To sprzeczne z naturą.",
		    DIRT = "Czy ziemia normalnie sama się przemieszcza?",
		    WORM = "Ale włochaty!",
		},
		EEL = "Nie podoba mi się jego spojrzenie!",
		EEL_COOKED = "Ogień uszlachetnia wszystko.",
		UNAGI = "Sama to przyrządziłam.",
		EYETURRET = "Szkoda, że nie miota ogniem.",
		EYETURRET_ITEM = "Na nic się nie przyda, dopóki jej gdzieś nie ustawię.",
		MINOTAURHORN = "Ciekawe, czy te pierścienie wskazują wiek.",
		MINOTAURCHEST = "Też chcę takie rogi!",
		THULECITE_PIECES = "Tulecyt rozpadł się na kawałki.",
		POND = "Nie ma szans, żeby go podpalić. Co za nuda.",
		POND_ALGAE = "Pewnie potrzebuje sporo wody.",
		GREENSTAFF = "Ognia tym nie rozpalę, ale i tak może się przydać.",
		POTTEDFERN = "Najchętniej spaliłabym je wszystkie.",

		THULECITE = "Chyba się nie zapali.",
		ARMORRUINS = "Nie jestem pewna, czy chcę to włożyć.",
		RUINS_BAT = "Będą się dranie trzymać z daleka.",
		RUINSHAT = "Coś chyba przez nią przepływa.",
		NIGHTMARE_TIMEPIECE = 
		{
		CALM = "Wygląda całkiem normalnie.",	
		WARN = "Ostrzega mnie.",	
		WAXING = "Paliwo powstaje do życia!", 
		STEADY = "Sytuacja jest stabilna.", 
		WANING = "Chyba się wyłącza.", 
		DAWN = "Chyba już mija.", 
		NOMAGIC = "Chyba nie działa.", 
		},
		BISHOP_NIGHTMARE = "Aaach!",
		ROOK_NIGHTMARE = "Ma parszywy uśmiech.",
		KNIGHT_NIGHTMARE = "Trochę się zużył.",
		MINOTAUR = "Biedaczek. Utknął w labiryncie.",	
		SPIDER_DROPPER = "Przybywają z góry.",	
		NIGHTMARELIGHT = "Światło bez ognia. To sprzeczne z naturą.",	
		GREENGEM = "Wydaje się niezwykle lekki.",
		RELIC = "Ktoś tu chyba kiedyś mieszkał.",	
		RUINS_RUBBLE = "Pewnie dałabym radę to naprawić.",	
		MULTITOOL_AXE_PICKAXE = "Przydatna rzecz!",	
		ORANGESTAFF = "Głowa mnie od niego boli.",	
		YELLOWAMULET = "Zdaje się pochłaniać otaczający go mrok.",	
		GREENAMULET = "Czuję, jak mój umysł się otwiera.",	

		SLURPER = "Chyba maja w brzuszkach małe ogniki....",
		SLURPER_PELT = "Fuuuuj! Jeszcze żyje!",
		ARMORSLURPER = "Och, aj! Aj! Aj! Aj! Aj! Fuuuuuuuuuuuj!",
		ORANGEAMULET = "Zbiera dla mnie materiały do palenia!",
		YELLOWSTAFF = "To magia!",
		YELLOWGEM = "Aż się skrzy!",
		ORANGEGEM = "Czuję mrowienie w palcach.",
		TELEBASE = 
		{
			VALID = "Wyczuwam magię!",
			GEMS = "Potrzeba czegoś więcej.",
		},
		GEMSOCKET = 
		{
			VALID = "Ciekawe, jakim sposobem utrzymują się w powietrzu...",
			GEMS = "Pustka!",
		},
		STAFFLIGHT = "Ale piękny!",
		RESEARCHLAB4 = "Mogłabym go użyć jako kociołka.",

        LIGHTER = "Moja ukochana zapalniczka!",


        ANCIENT_ALTAR =
        {
        	WORKING = "Oooo! Centrala zaświatów.",
        	BROKEN = "Umarli tędy się nie przedostaną.",
        },  
        ANCIENT_ALTAR_BROKEN = "Śmierć nie ma tutaj dostępu.",

        ANCIENT_STATUE = "A niech to, nie chce się palić.",

        LICHEN = "Chrupiący kwiatek.",
		CUTLICHEN = "Ble. Smakuje jak trociny.",

        CAVE_BANANA = "Banany!",
        CAVE_BANANA_COOKED = "Mniam!",
        CAVE_BANANA_TREE = "Chyba dałoby się go podpalić!",
        ROCKY = "Nie mamy zbyt wiele wspólnego.",

        BLUEAMULET = "Bezużyteczny śmieć.",
		PURPLEAMULET = "Czyżby nauka posunęła się za daleko?",
		TELESTAFF = "Puf! Niespodzianka!",
		MINERHAT = "Ogień to to nie jest, ale i tak mi się podoba.",
		MONKEY = "I kto się śmieje ostatni?! Mogę podpalić tę kupę.",
		MONKEYBARREL = "Ale cudownie łatwopalny domek.",

		HOUNDSTOOTH="Ostry! Podoba mi się!",
		ARMORSNURTLESHELL="Mniej obrony, więcej ataku!",
		BAT="Ale słodziak!",
		BATBAT = "Mogę tym przywalić swym rywalom.",
		BATWING="Fuj!",
		BATWING_COOKED="Fuj!",
		BEDROLL_FURRY="Jak dla mnie trochę zbyt puchaty.",
		BUNNYMAN="Ugh. Wyglądają strasznie głupio.",
		FLOWER_CAVE="Płonie od wewnątrz.",
		FLOWER_CAVE_DOUBLE="Wciąż płonie od wewnątrz.",
		FLOWER_CAVE_TRIPLE="Płonie od wewnątrz.",
		GUANO="Pali się jak normalne łajno.",
		LANTERN="Ognia nie można tak ograniczać!",
		LIGHTBULB="Niech nastanie jasność!",
		MANRABBIT_TAIL="Wygrałam ten spór.",
		MUSHTREE_TALL="Okropieństwo. To drzewo jest chore.",
		MUSHTREE_MEDIUM="Ohyda. Śmierdzi jak tyłek leprekauna.",
		MUSHTREE_SMALL="Okropieństwo. Jakieś takie całe grzybowe.",
		RABBITHOUSE="Ugh. Głupie króliki.",
		SLURTLE="Mam ochotę wysadzić go w powietrze!",
		SLURTLE_SHELLPIECES="Zepsuła się.",
		SLURTLEHAT="Pasuje na moją głowę.",
		SLURTLEHOLE="Powinnam wywabić je ogniem.",
		SLURTLESLIME="Uwielbiam to!",
		SNURTLE="Kabum!",
		SPIDER_HIDER="Co za wnerwiający kretyn!",
		SPIDER_SPITTER="Chodź tutaj!",
		SPIDERHOLE="Pełen pająków.",
		STALAGMITE="Kamienie są takie nudne.",
		STALAGMITE_FULL="Kamienie są takie nudne.",
		STALAGMITE_LOW="Kamienie są takie nudne.",
		STALAGMITE_MED="Kamienie są takie nudne.",
		STALAGMITE_TALL="Więcej nudnych kamieni.",
		STALAGMITE_TALL_FULL="Więcej nudnych kamieni.",
		STALAGMITE_TALL_LOW="Więcej nudnych kamieni.",
		STALAGMITE_TALL_MED="Więcej nudnych kamieni.",

		TURF_CARPETFLOOR = "Ziemia jest taka nudna.",
		TURF_CHECKERFLOOR = "Gleba jest taka nudna.",
		TURF_DIRT = "Gleba jest taka nudna.",
		TURF_FOREST = "Gleba jest taka nudna.",
		TURF_GRASS = "Ziemia jest taka nudna.",
		TURF_MARSH = "Ziemia jest taka nudna.",
		TURF_ROAD = "Ziemia jest taka nudna.",
		TURF_ROCKY = "Gleba jest taka nudna.",
		TURF_SAVANNA = "Gleba jest taka nudna.",
		TURF_WOODFLOOR = "Gleba jest taka nudna.",

		TURF_CAVE="Gleba jest taka nudna.",
		TURF_FUNGUS="Gleba jest taka nudna.",
		TURF_SINKHOLE="Gleba jest taka nudna.",
		TURF_UNDERROCK="Gleba jest taka nudna.",
		TURF_MUD="Gleba jest taka nudna.",
		
		TURKEYDINNER = "Uczta ze spalonego ptaka.",
		TWIGS = "Kupka małych gałązek. Dobra na przykład na podpałkę.",
		POWCAKE = "Ciekawe, czy łatwo się pali.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Kto zatkał tę dziurę?",
            OPEN = "Mam nadzieję, że gdzieś tam w dole jest lawa.",
        },
        CAVE_EXIT = "Ciemno tu i duszno.",

		MAXWELLPHONOGRAPH = "Wolę trochę żywszą muzykę.",
		PIGGUARD = "Lubię jego podejście do życia!",
		BOOMERANG = "Niezbyt ekscytująca broń.",
		ADVENTURE_PORTAL = "Może prowadzi do domu.",
		AMULET = "Jestem niezwyciężona! No, może nie. Ale uczucie jest fajnie.",
		ANIMAL_TRACK = "Prowadzi do mojego nowego przyjaciela.",
		ARMORGRASS = "Szkoda łatwopalnych materiałów.",
		ARMORMARBLE = "Skoro mam walczyć, to należy mi się ochrona.",
		ARMORWOOD = "Teraz mogę zmierzyć się ze światem!",
		ARMOR_SANITY = "Jakbym się ubrała w dym.",
		ASH =
		{
			GENERIC = "Resztki po ogniu. Szkoda, że już go nie ma.",
			REMAINS_EYE_BONE = "Założę się, że to coś z okiem świetnie wygląda w ogniu.",
			REMAINS_THINGIE = "Cokolwiek to było, szkoda, że już nie płonie.",
		},
		AXE = "Ostra rzecz.",
		BABYBEEFALO =
		{
			GENERIC = "Nawet młode są paskudne.",
			SLEEPING = "POBUDKA!",
		},
		BACKPACK = "Zmieściłabym tu chyba z milion zapalniczek.",
		BACONEGGS = "To żółte oślizgłe coś jest obrzydliwe, ale boczek – pierwsza klasa.",
		BANDAGE = "Ech, naprawdę muszę?",
		BASALT = "Za twardy! Nie dam rady go zniszczyć!",
		BEARDHAIR = "Eee, skąd to się wzięło?",
		BEDROLL_STRAW = "Trochę stęchły.",
		BEE =
		{
			GENERIC = "Jest raczej gruba, ale to żądło wygląda niebezpiecznie.",
			HELD = "Już nie pofruwa. Ani tu, ani tam.",
		},
		BEEBOX =
		{
			GENERIC = "No dalej, leniwe pszczoły. Róbcie miód!",
			READY = "Ha! Mogę podkraść trochę miodu!",
		},
		BEEFALO =
		{
			FOLLOWER = "Eee, chodzisz za mną?",
			GENERIC = "Co za obrzydliwa, włochata bestia!",
			NAKED = "Ha! Teraz jest goły!",
			SLEEPING = "Jak śpią, wyglądają jeszcze głupiej.",
		},
		BEEFALOHAT = "Zabrałam mu włosy i nałożyłam na własne!",
		BEEFALOWOOL = "Ha! Ukradłam mu kłaki!",
		BEEHIVE = "Pełen pszczół!",
		BEEMINE = "Pełna pszczół. Powinnam jeszcze dołożyć trochę ognia.",
		BEEMINE_MAXWELL = "Pełna komarów. Nie wydają się szczęśliwe.",
		BEEHAT = "To mnie ochroni przed tymi kłujkami.",
		BERRIES = "Czerwone są najlepsze.",
		BERRIES_COOKED = "Porzeczki opieczone w ogniu jakoś lepiej smakują.",
		BERRYBUSH =
		{
			BARREN = "Jedz to, głupia roślino!",
			GENERIC = "Mmmmm. Porzeczki.",
			PICKED = "Chcę więcej porzeczek!",
		},
		BIRDCAGE =
		{
			GENERIC = "Ptasie więzienie!",
			OCCUPIED = "Ha! Jesteś mój!",
			SLEEPING = "Głupi ptak. Obudź się!",
		},
		BIRDTRAP = "Złapię was, przeklęte ptaki.",
		BIRD_EGG = "Śmierdzi jak ptasi tyłek.",
		BIRD_EGG_COOKED = "Fuj! Żółtko jest surowe.",
		BISHOP = "Goniec!",
		BLOWDART_FIRE = "Najlepsza rzecz na świecie.",
		BLOWDART_SLEEP = "Środek usypiający ułatwi podpalenie ofiary.",
		BLOWDART_PIPE = "Dobry trening przed rozniecaniem ognia.",
		BLUEGEM = "Ugh. Ten jest okropny.",
		BLUEPRINT = "Oszczędzę trochę czasu na eksperymentach.",
		BLUE_CAP = "Śmierdzi jak skarpeta maratończyka!",
		BLUE_CAP_COOKED = "Ogień go odmienił!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Głupi grzyb.",
			INGROUND = "Hej, ty! Wyłaź!",
			PICKED = "Może kiedyś odrośnie.",
		},
		BOARDS = "Deski. Palą się tak samo jak drewno w każdej innej postaci.",
		BONESTEW = "Wystarczy dodać ognia do jedzenia i voila!",
		BUGNET = "Mogę łapać owady!",
		BUSHHAT = "Nuda!",
		BUTTER = "Masełko idzie w sadełko.",
		BUTTERFLY =
		{
			GENERIC = "Motylku, leć...",
			HELD = "Mam ochotę go zgnieść.",
		},
		BUTTERFLYMUFFIN = "Ha, ha! Motyl utknął w babeczce.",
		BUTTERFLYWINGS = "Skończyło się motylowanie!",
		CAMPFIRE =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Lubię ogień.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ!",
			LOW = "Ogień jest mały i nudny.",
			NORMAL = "Płoń!",
			OUT = "Ach. Skończyło się.",
		},
		CANE = "Teraz łatwiej mi będzie iść!",
		CARROT = "Fuj. Żarcie dla królików.",
		CARROT_COOKED = "Wciąż bardzo warzywna, ale ogień trochę poprawił smak.",
		CARROT_PLANTED = "Może znajdzie w ziemi swojego marchewkowego przyjaciela.",
		CARROT_SEEDS = "Nasiona pomarańczowego obrzydlistwa.",
		CAVE_FERN = "Wygląda na łatwopalną.",
		CHARCOAL = "Mmm. Pachnie ogniem.",
        CHESSJUNK1 = "Martwy nakręcany konik.",
        CHESSJUNK2 = "Martwy nakręcany posłaniec.",
        CHESSJUNK3 = "Martwy nakręcany zamek.",
		CHESTER = "Ale włochata!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Niegrzecznie jest się gapić.",
			WAITING = "Przynajmniej już się na mnie nie gapi.",
		},
		COOKEDMEAT = "Jadłam już lepsze rzeczy.",
		COOKEDMONSTERMEAT = "Wciąż jest ohydne.",
		COOKEDSMALLMEAT = "Jeśli mam przetrwać, będę potrzebowała czegoś więcej.",
		CORN = "Słodkie warzywo, mniam!",
		CORN_COOKED = "Och! W ogniu eksploduje!",
		CORN_SEEDS = "Nasionka mojego ulubionego wybuchowego warzywa.",
		CROW =
		{
			GENERIC = "Chyba czeka, aż umrę.",
			HELD = "Wcale nie taki sprytny z ciebie ptaszek, co?",
		},
		CUTGRASS = "Ścięta trawa, gotowa do spalenia. Ewentualnie do jakiegoś rzemiosła.",
		CUTREEDS = "Cięty tatarak, gotowy do spalenia. Ewentualnie do jakiegoś rzemiosła.",
		CUTSTONE = "Idealnie ociosane dla maksimum przyjemności.",
		DEADLYFEAST = "Ogień nie pomógł. I tak jest obrzydliwa.",
		DEERCLOPS = "O rety!",
		DEERCLOPS_EYEBALL = "Przestań się na mnie gapić!",
		DIRTPILE = "Kto w ogóle zostawia w lesie jakąś ziemię?",
		DIVININGROD =
		{
			COLD = "Wydaje jakieś ciche dźwięki.",
			GENERIC = "Elektryczne ustrojstwo.",
			HOT = "Wystarczy tego pikania!",
			WARM = "Robi się coraz głośniejsza.",
			WARMER = "Chyba jestem blisko!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Nie wiem, co to robi. Chyba nie ma nic wspólnego z ogniem.",
			READY = "Trzeba to otworzyć. Niestety kluczem, a nie ogniem.",
			UNLOCKED = "Zaczęło się kręcić!",
		},
		DIVININGRODSTART = "Coś się z tego wymyśli.",
		DRAGONFRUIT = "Wygląda trochę jak ogień!",
		DRAGONFRUIT_COOKED = "Teraz bardziej wygląda na owoc, który ma coś do czynienia z ogniem.",
		DRAGONFRUIT_SEEDS = "Nasiona tego ognistego owocu.",
		DRAGONPIE = "Ciasto z ognistymi owocami? O raju!",
		DRUMSTICK = "Kurczę pieczone!",
		DRUMSTICK_COOKED = "Zabić głód, czy kogoś?",
		DURIAN = "Ale śmierdziel!",
		DURIAN_COOKED = "Fuj! Ugotowany śmierdzi równie paskudnie!",
		DURIAN_SEEDS = "Śmierdzące nasiona śmierdzącego owocu.",
		EARMUFFSHAT = "Śmierdzi jak tyłek królika.",
		EGGPLANT = "Na pewno nie jest psem.",
		EGGPLANT_COOKED = "Ogień znacznie pomógł.",
		EGGPLANT_SEEDS = "Ciekawe, co z nich wyrośnie. Warzywa, czy małe pieski?",
		STUFFEDEGGPLANT = "Wciąż nie jest psem, ale jest wypchany jak martwy pies.",
		DUG_BERRYBUSH = "Co się stało? Nie masz ziemi?",
		DUG_GRASS = "Co się stało? Nie masz ziemi?",
		DUG_MARSH_BUSH = "Co się stało? Nie masz ziemi?",
		DUG_SAPLING = "Co jest? Brakuje ci ziemi?",
		EARMUFFS = "Śmierdzi jak tyłek królika.",
		EVERGREEN =
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Jedno drzewo mniej na świecie.",
			GENERIC = "Na pewno znakomicie się pali.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Jedno drzewo mniej na świecie.",
			GENERIC = "Giń w ogniu!",
		},
		EYEPLANT = "Rozprzestrzeniają się jak ogień.",
		FARMPLOT =
		{
			GENERIC = "Ech. Kupa ziemi.",
			GROWING = "No dalej, kupo ziemi. Nakarm mnie!",
			NEEDSFERTILIZER = "Głupie pole potrzebuje nawozu.",
		},
		FEATHERHAT = "Jestem feniksem!",
		FEATHER_CROW = "Pióro kruka. Pewnie strasznie śmierdzi w ogniu.",
		FEATHER_ROBIN = "Pióro kardynała. Pewnie strasznie śmierdzi w ogniu.",
		FEATHER_ROBIN_WINTER = "Pióro śnieżyka. Pewnie strasznie śmierdzi w ogniu.",
		FEM_PUPPET = "Chyba się boi.",
		FIREFLIES =
		{
			GENERIC = "Szkoda, że tak uciekają!",
			HELD = "Są jak małe ogniki w kieszeni!",
		},
		FIREHOUND = "W sumie to te nawet mi się podobają.",
		FIREPIT =
		{
			EMBERS = "Oj... Zaraz zgaśnie!",
			GENERIC = "Mogłabym się w nie wpatrywać godzinami.",
			HIGH = "PŁOŃ! PŁOŃ MOCNIEJ!",
			LOW = "Ogień jest mały i nudny.",
			NORMAL = "Płoń!",
			OUT = "Powinnam przywrócić ogień do życia.",
		},
		FIRESTAFF = "Moja najulubieńsza zabawka.",
		FISH = "Ryba wpływa na wszystko!",
		FISHINGROD = "Ciekawe, czy dzisiaj biorą.",
		FISHSTICKS = "Jesteś tym, co jesz. Teraz będę rybnym paluchem.",
		FISHTACOS = "Wygodny taco-chwyt!",
		FISH_COOKED = "Po spotkaniu z ogniem nie jest już taka śliska.",
		FLINT = "Zapalniczka dla ubogich.",
		FLOWER = "Nie mam czasu na jakieś kwiatki.",
		FLOWERHAT = "Aureola z kwiatków. Szkoda, że nie jest to płonąca aureola z kwiatków.",
		FLOWER_EVIL = "Śmierdzi paskudnie.",
		FOLIAGE = "Paliwo dla ognia.",
		FOOTBALLHAT = "Sport nie jest łatwy.",
		FROG =
		{
			DEAD = "Ale jej pokazałam!",
			GENERIC = "Zbyt wilgotna, żeby się zapalić.",
			SLEEPING = "Są takie urocze, jak śpią.",
		},
		FROGGLEBUNWICH = "Może wcale nie zauważę, że to żabie nogi w bułce...",
		FROGLEGS = "Jeszcze się ruszają. Straszne.",
		FROGLEGS_COOKED = "W ogniu przestały wreszcie wierzgać. Ogień jest fantastyczny.",
		FRUITMEDLEY = "Mmm, owocki!",
		GEARS = "To pewnie dzięki nim się ruszają.",
		GHOST = "Nie mogę zabić kogoś, kto już nie żyje.",
		GOLDENAXE = "Może nie podpali drzewa, ale przynajmniej się błyszczy.",
		GOLDENPICKAXE = "Może nie podpali kamienia, ale przynajmniej się błyszczy.",
		GOLDENPITCHFORK = "Ziemi nie podpali, ale przynajmniej ładnie się błyszczy.",
		GOLDENSHOVEL = "Nie dokopię się nią do ognia, ale przynajmniej ładnie błyszczy.",
		GOLDNUGGET = "I gdzie ja to wydam?",
		GRASS =
		{
			BARREN = "Potrzebuje łajna.",
			BURNING = "Ogień! Hurra!",
			GENERIC = "Łatwopalna kępka trawy.",
			PICKED = "Małe ściernisko. Raczej bezużyteczne.",
		},
		GREEN_CAP = "Nuda!",
		GREEN_CAP_COOKED = "Ogień go odmienił!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Głupi grzyb.",
			INGROUND = "Hej, ty! Wyłaź!",
			PICKED = "Może kiedyś odrośnie.",
		},
		GUNPOWDER = "Oooooooch! Będzie ogień!",
		HAMBAT = "Spuszczę komuś mięsisty łomot!",
		HAMMER = "Wolę ostre narzędzia.",
		HEALINGSALVE = "Pali! Gdzie jest ogień?",
		HEATROCK =
		{
			COLD = "Zimny jak głaz.",
			GENERIC = "Ogień mógłby go ożywić!",
			HOT = "Ale się świeci!",
			WARM = "Nie ma płomienia, nie ma prawdziwego ciepła... Gdzie tu przyjemność?",
		},
		HOMESIGN = "Dość czytania, czas na ogień!",
		HONEY = "Słodki i pyszny!",
		HONEYCOMB = "Bardzo woskowaty.",
		HONEYHAM = "Ogień, szynka i miód – doskonałe połączenie.",
		HONEYNUGGETS = "Pokryte miodem kąski po spotkaniu z moim najlepszym przyjacielem.",
		HORN = "Słyszę wewnątrz te włochate bestie.",
		HOUND = "Co za wredne zwierzę!",
		HOUNDMOUND = "Uj... Nie podoba mi się to.",
		HOUNDBONE = "Obrzydlistwo.",
		ICEBOX = "Odwrotność ognia.",
		ICEHOUND = "Obrzydliwy! I zimny!",
		INSANITYROCK =
		{
			ACTIVE = "Zaczynam mieć zwidy?",
			INACTIVE = "Wygląda na zupełnie niepalny. Ale nuda.",
		},
		JAMMYPRESERVES = "Marmelada!",
		KABOBS = "Mięso i ogień. I patyczek!",
		KILLERBEE =
		{
			GENERIC = "Fajny ma kolec.",
			HELD = "Bzzz!",
		},
		KNIGHT = "Kucyk!",
		KOALEFANT_SUMMER = "Będziemy dobrymi przyjaciółmi!",
		KOALEFANT_WINTER = "Wygląda cieplutko...",
		KRAMPUS = "Trzymaj się z dala, wredny paskudzie!",
		KRAMPUS_SACK = "Mam nową torebkę!",
		LEIF = "Na pewno jest łatwopalny!",
		LEIF_SPARSE = "Na pewno jest łatwopalny!",
		LIGHTNING_ROD =
		{
			CHARGED = "Ooo, świeci, a nie ma ognia.",
			GENERIC = "Zapraszamy wszystkie błyskawice tutaj!",
		},
		LITTLE_WALRUS = "Wygląda smakowicie.",
		LIVINGLOG = "Wygląda na zdenerwowaną.",
		LOCKEDWES = "Uwięziły go te podłe posągi!",
		LOG =
		{
			BURNING = "Płoń, drewienko, płooooń!",
			GENERIC = "Drewno! Tak łatwopalne! Tak śmiesznie marne!",
		},
		LUREPLANT = "Odrobina ognia załatwiłaby sprawę.",
		LUREPLANTBULB = "Teraz jest moja.",
		MALE_PUPPET = "Chyba się boi.",
		MANDRAKE =
		{
			DEAD = "Dlaczego ta roślina ma twarz?",
			GENERIC = "To nie jest zwykła roślina.",
			PICKED = "Co za paskudztwo!",
		},
		COOKEDMANDRAKE = "Ogień nie pozbył się tej twarzy. Trochę to straszne.",
		MANDRAKESOUP = "W zupie przynajmniej nie widać jej twarzy.",
		MARBLE = "Ale ciężkie!",
		MARBLEPILLAR = "Ciekawe... reszta się spaliła?",
		MARBLETREE = "Najgorszy rodzaj drzewa. Niepalny.",
		MARSH_BUSH =
		{
			BURNING = "Płońcie, wredne ciernie!",
			GENERIC = "Wyglądają na ostre.",
			PICKED = "Ale kłuje!",
		},
		MARSH_PLANT = "Bardzo roślinna.",
		MARSH_TREE =
		{
			BURNING = "TAK! PŁOŃ!",
			BURNT = "Szkoda, że już nie płonie.",
			CHOPPED = "Ha! I gdzie są teraz twoje kolce?!",
			GENERIC = "Wygląda groźnie!",
		},
		MAXWELL = "Jest taki protekcjonalny.",
		MAXWELLHEAD = "Zdecydowanie lubi dużo gadać.",
		MAXWELLLIGHT = "Wcale nie są fajne. Same się zapalają.",
		MAXWELLLOCK = "Brakuje tylko klucza.",
		MAXWELLTHRONE = "Wygląda na klejący.",
		MEAT = "OGIEŃ mógłby je uszlachetnić!",
		MEATBALLS = "Mięso uformowane w kulki i udoskonalone ogniem.",
		MEATRACK =
		{
			DONE = "Gotowe!",
			DRYING = "No dalej, mięsko. Schnij!",
			GENERIC = "Mam ochotę coś tu zawiesić!",
		},
		MEAT_DRIED = "Trochę gumowe, ale całkiem przyzwoite.",
		MERM = "Fuj, co za oślizgłe paskudztwo.",
		MERMHEAD = "I widzisz, co cię spotkało przez ten smród?!",
		MERMHOUSE = "Nikomu nie byłoby żal, gdyby stanął w ogniu.",
		MONSTERLASAGNA = "Makaron, mięso i kępki włosów. Obrzydliwe.",
		MONSTERMEAT = "Pełno tu włosów. Ohyda.",
		MONSTERMEAT_DRIED = "Jest suche i dziwnie pachnie.",
		MOSQUITO =
		{
			GENERIC = "Ale są denerwujące!",
			HELD = "Trzymaj tę gębę z dala ode mnie!",
		},
		MOSQUITOSACK = "Mam krew na rękach.",
		MOUND =
		{
			DUG = "Lepiej on niż ja.",
			GENERIC = "Pewnie jest pełny martwych rzeczy.",
		},
		NIGHTLIGHT = "Trochę jak ogień, tylko fioletowy!",
		NIGHTMAREFUEL = "Fuj! Jeszcze ciepłe!",
		NIGHTSWORD = "Czuję, że moje sny mogą zadać ból w realnym świecie.",
		NITRE = "Wewnątrz kryją się małe eksplozje.",
		ONEMANBAND = "Znam się też na fajerwerkach!",
		PANDORASCHEST = "Trochę tandetna.",
		PANFLUTE = "Muzyka jest taka nudna...",
		PAPYRUS = "Na pewno dobrze się pali!",
		PENGUIN = "Uciekajcie, mali tancerze.",
		PERD = "Podłe ptaszysko! Trzymaj się z dala od moich porzeczek!",
		PEROGIES = "Smaczne jedzonko zapieczętowane ogniem.",
		PETALS = "Głupie kwiaty. Są prawie bezużyteczne.",
		PETALS_EVIL = "Fuj. Kleją się.",
		PICKAXE = "Ma dużo ostrych krawędzi.",
		PIGGYBACK = "Plecak ze świńskich zadków!",
		PIGHEAD = "Ładnie się załatwił.",
		PIGHOUSE =
		{
			FULL = "Robi tam jakieś świństwa.",
			GENERIC = "Te prosiaki mają dość osobliwy gust architektoniczny.",
			LIGHTSOUT = "Ty draniu! Wpuść mnie!",
		},
		PIGKING = "Blee. Co za flejtuch.",
		PIGMAN =
		{
			DEAD = "Ciekawe, jak smakują.",
			FOLLOWER = "Ech. Łazi za mną.",
			GENERIC = "Ugh. Nie pachną zbyt pięknie.",
			GUARD = "Nie będzie mi się rządził!",
			WEREPIG = "Stawaj, prosiaku!",
		},
		PIGSKIN = "Ha, ha! Świński zadek.",
		PIGTORCH = "Te prosiaki umieją się bawić!",
		PINECONE = 
		{
		    GENERIC = "Witaj, drzewne nasionko.",
		    PLANTED = "Wkrótce będziesz prawdziwym drzewem.",
		},
		PITCHFORK = "Potrójna ostrość.",
		PLANTMEAT = "Fuj, ale oślizgłe.",
		PLANTMEAT_COOKED = "Ogień ulepsza wszystko.",
		PLANT_NORMAL =
		{
			GENERIC = "Zjem to, jeśli będę musiała.",
			GROWING = "Szybciej, głupia roślino!",
			READY = "O rany. Warzywa.",
		},
		POMEGRANATE = "To normalne, że ma w środku tyle części?",
		POMEGRANATE_COOKED = "Dobrze, że nie wybuchł w ogniu.",
		POMEGRANATE_SEEDS = "Mogą wybuchnąć?",
		POOP = "Fuj. Ohydne. Ale użyteczne.",
		PUMPKIN = "Ciekawe, co się stanie, jak potraktuje ją ogniem.",
		PUMPKINCOOKIE = "Ciasteczka!!!",
		PUMPKIN_COOKED = "Ogień spisał się całkiem nieźle.",
		PUMPKIN_LANTERN = "Ten ogień w środku jest obłędny.",
		PUMPKIN_SEEDS = "Nasiona królowej warzyw, przyjaciółki ognia, jedynej w swoim rodzaju dyni.",
		PURPLEGEM = "Ale dziwny!",
		RABBIT =
		{
			GENERIC = "Wygląda smacznie.",
			HELD = "Jest tam, gdzie powinien.",
		},
		RABBITHOLE = "Głupie króliki. Wyłaźcie, żebym mogła was zjeść.",
		RAINOMETER = "Deszcz jest zaprzeczeniem ognia. Buu!",
		RATATOUILLE = "Warzywa. Dużo warzyw.",
		RAZOR = "Po co to w ogóle stworzyłam?",
		REDGEM = "Ale piękny!",
		RED_CAP = "Fajny kolor.",
		RED_CAP_COOKED = "Ogień go odmienił!",
		RED_MUSHROOM =
		{
			GENERIC = "Piękny!",
			INGROUND = "Hej, ty! Wyłaź!",
			PICKED = "Może kiedyś odrośnie.",
		},
		REEDS =
		{
			BURNING = "Płoń! O tak!",
			GENERIC = "Kępka tataraku. Łatwopalnego tataraku.",
			PICKED = "Na nic mi się nie przydadzą resztki tataraku.",
		},
        RELIC = 
        {
            GENERIC = "Stary mebel.",
            BROKEN = "Różne takie śmieci.",
        },
        RUBBLE = "Popsute meble.",
		RESEARCHLAB = "Nawet ja jeszcze nie wszystko wiem.",
		RESEARCHLAB2 = "Nawet ja jeszcze nie wszystko wiem.",
		RESEARCHLAB3 = "Emanuje mroczną, potężną energią.",
		RESURRECTIONSTATUE = "Moja polisa ubezpieczeniowa.",
		RESURRECTIONSTONE = "Pewnie powinnam go dotknąć?",
		ROBIN =
		{
			GENERIC = "Rudzik. W kolorze ognia. Niestety nie feniks.",
			HELD = "W kieszeni będzie mu ciepło.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Wydaje się zmarznięty. Na pewno szuka ognia.",
			HELD = "Ale puchaty.",
		},
		ROBOT_PUPPET = "Chyba się boi.",
		ROCK_LIGHT =
		{
			GENERIC = "Zastygnięte źródło ognia.",
			OUT = "Wystygło.",
			LOW = "Lawa stygnie.",
			NORMAL = "Jezioro ognia!",
		},
		ROCKS = "Może ułożę z nich inuksuk?",
        ROOK = "To zamek!",
        ROPE = "Co mogłabym związać?",
		ROTTENEGG = "Fuj! Czemuż, ach czemuż?",
		SANITYROCK =
		{
			ACTIVE = "Ciekawe, co to za znaki.",
			INACTIVE = "Gdzie on się podział?",
		},
		SAPLING =
		{
			BURNING = "Płoń! O tak!",
			GENERIC = "Powinnam ją zabrać.",
			PICKED = "Biedne małe drzewko.",
		},
		SEEDS = "Rolnictwo jest takie nudne.",
		SEEDS_COOKED = "Już się ich nie zasieje.",
		SEWING_KIT = "Destrukcja jest o tyle fajniejsza!",
		SHOVEL = "Do walki się nie nada.",
		SILK = "Mmmmmm. Mięciutka.",
		SKELETON = "O rany. Mam nadzieję, że odszedł w ognistej chwale.",
		SKULLCHEST = "Ooooch, okropieństwo!",
		SMALLBIRD =
		{
			GENERIC = "Może to nie feniks, ale też jest uroczy.",
			HUNGRY = "Głodny?",
			STARVING = "Dobra, dobra! Rozumiem. Jesteś głodny.",
		},
		SMALLMEAT = "OGIEŃ mógłby to jeszcze udoskonalić.",
		SMALLMEAT_DRIED = "Trochę gumowe, ale może być.",
		SPEAR = "Poczuj mój gniew!",
		SPIDER =
		{
			DEAD = "Ha! To się doigrałeś!",
			GENERIC = "Jest okropny. Muszę go zabić.",
			SLEEPING = "Mogłabym zabrać go ze sobą.",
		},
		SPIDERDEN = "Obrzydlistwo.",
		SPIDEREGGSACK = "Mnóstwo małych odrażających pajączków.",
		SPIDERGLAND = "Bleee! Oślizgły i śmierdzący!",
		SPIDERHAT = "Mam nadzieję, że naprawdę nie żyje.",
		SPIDERQUEEN = "Ogień ją unicestwi!",
		SPIDER_WARRIOR =
		{
			DEAD = "Zasłużył sobie.",
			GENERIC = "Mogłabym go zabić... OGNIEM!",
			SLEEPING = "Może lepiej zostawić go w spokoju...",
		},
		SPOILED_FOOD = "Zawsze można je spalić.",
		STATUEHARP = "Ładny posążek. Szkoda by było, gdyby coś mu się stało.",
		STATUEMAXWELL = "Przestaje mi się podobać ten gość.",
		STINGER = "Kłuje!",
		STRAWHAT = "Kapelusz ze słomy. Można by go użyć na podpałkę.",
		SUNKBOAT = "Jest za daleko. Nie mogę jej nawet podpalić!",
		SWEATERVEST = "Ognista kamizelka byłaby fajniejsza, ale ta też da radę.",
		TAFFY = "Cukier dobrze się pali, ale powinnam to jednak zjeść.",
		TALLBIRD = "Chyba nie chce się przyjaźnić.",
		TALLBIRDEGG = "Ciekawe, czy lubi ogień...",
		TALLBIRDEGG_COOKED = "Ogień działa cuda!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Potrzeba więcej ognia!",
			GENERIC = "Powstań, mój feniksie!",
			HOT = "Czy istnieje w ogóle coś takiego jak nadmiar ognia?",
			LONG = "Ile to jeszcze potrwa?",
			SHORT = "Mam już dość tego czekania.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Temu jajku przydałaby się odrobina ognia!",
			PICKED = "Gniazdo jest puste.",
		},
		TEENBIRD =
		{
			GENERIC = "Chyba mnie rozumie.",
			HUNGRY = "Lubi zjeść.",
			STARVING = "Nie patrz tak na mnie! Zorganizuj sobie coś do jedzenia.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Chcę zobaczyć, jak świat płonie.",
			GENERIC = "Fajnie się świecą te symbole.",
			LOCKED = "Trzeba to jakoś odblokować.",
			PARTIAL = "Tworzę potwora!",
		},
		TELEPORTATO_BOX = "Wydaje się ciepłe.",
		TELEPORTATO_CRANK = "I do czego to to służy?",
		TELEPORTATO_POTATO = "Może dałoby się to przetopić w coś przyjemniejszego dla oka.",
		TELEPORTATO_RING = "Jest zbyt cenne, żeby to spalić!",
		TENT = "W skautach zdobyłam wszystkie sprawności.",
		TENTACLE = "Zupełnie nie do przytulania.",
		TENTACLESPOTS = "Fuuuuuj,",
		TENTACLESPIKE = "Kłujący i oślizgły.",
		TENTACLE_PILLAR = "Cała drży.",
		TENTACLE_PILLAR_ARM = "Oooch, chcą się przytulać!",
		TENTACLE_GARDEN = "Słyszę cichutkie odgłosy kopania.",
		TOPHAT = "Cylinder i zapalniczka. Idealne połączenie.",
		TORCH = "Ogień jest taki piękny.",
		TRAP = "Trochę pasywno-agresywna, ale powinna dać radę.",
		TRAP_TEETH = "Z ogniem byłaby skuteczniejsza.",
		TRAP_TEETH_MAXWELL = "Co za kretyn zostawia na ziemi takie rzeczy?",
		TREASURECHEST = "Skrzynia na szpargały.",
		TRINKET_1 = "Ogień, który je stopił, musiał być niesamowicie gorący.",
		TRINKET_10 = "Sztuczne szczęki chyba nie palą się najlepiej.",
		TRINKET_11 = "Oooch, ciekawe, czy ma miotacz ognia.",
		TRINKET_12 = "Wyschła do cna. Chyba leżała za blisko ognia.",
		TRINKET_2 = "Tania podróbka. Pewnie się nawet porządnie nie pali.",
		TRINKET_3 = "Węzeł się zacisnął. Po co komu nóż, jak można użyć ognia?",
		TRINKET_4 = "Wygląda, jakby wykuto go w płomieniach.",
		TRINKET_5 = "Popatrz tylko na te miniaturowe silniki. Tyle mocy!",
		TRINKET_6 = "Nawet nie ma iskier.",
		TRINKET_7 = "Ogień jest fajniejszy.",
		TRINKET_8 = "Nigdy nie lubiłam się kąpać.",
		TRINKET_9 = "Na zamku odpalisz zapałkę, na guzikach już gorzej.",
		TRUNKVEST_SUMMER = "Teraz będę ze swoim przyjacielem już na zawsze.",
		TRUNKVEST_WINTER = "Nie tak ciepła, jak porządny ogień, ale i tak daje radę!",
		TRUNK_COOKED = "Wciąż nie jestem pewna, czy chcę to zjeść.",
		TRUNK_SUMMER = "Cóż... kawałek wciąż nadaje się do przytulania.",
		TRUNK_WINTER = "Jest taka miękka i przytulaśna!",
		UMBRELLA = "Lubię ten kolor!",
		WAFFLES = "Cześć, goferki!",
		WALL_HAY = "Wygląda na bardzo łatwopalny.",
		WALL_HAY_ITEM = "Hmmmm. Ciekawe, czy się zapali.",
		WALL_STONE = "Ech. Chyba może być.",
		WALL_STONE_ITEM = "Zaskakująco ciężkie.",
		WALL_RUINS = "I mogą sobie chuchać i dmuchać!",
		WALL_RUINS_ITEM = "Zmieszczą mi się do kieszeni?",
		WALL_WOOD = "Może się łatwo zapalić...",
		WALL_WOOD_ITEM = "Nienawidzę się chować.",
		WALRUS = "Przestań za mną łazić!",
		WALRUSHAT = "Nawet nie najgorszy.",
		WALRUS_CAMP =
		{
			EMPTY = "Nie zamierzam tam wchodzić. Ohyda!",
			GENERIC = "Dlaczego wszyscy mają ładniejsze domy niż ja?",
		},
		WALRUS_TUSK = "Nom, nom, nom.",
		WASPHIVE = "Lepiej trzymać się na dystans.",
		WETGOOP = "Dlaczego nie wyszło?! Włożyłam wszystko do ognia i w ogóle.",
		WINTERHAT = "Jak dla mnie trochę za chłodna.",
		WINTEROMETER = "Bardziej by się przydał, gdyby mierzył ogień.",
		WORMHOLE =
		{
			GENERIC = "Trzeba ją dźgnąć patykiem!",
			OPEN = "Ciekawe, czy lubi ostre jedzenie?",
		},
		ACCOMPLISHMENT_SHRINE = "Nienawidzę tej strzałki!",        		
		LIVINGTREE = "Może i jest żywe, ale na pewno pali się jak każde inne.",
		ICESTAFF = "Nuuuuuda.",
	},
	DESCRIBE_TOODARK = "Więcej światła!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Oj. Kruchutkie.",
	},
}
