return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我不認為她願意剃毛。",
			GENERIC = "這東西無法剃毛。",
			NOBITS = "但是它已經像嬰兒屁股一樣光溜溜了。",
		},
		STORE =
		{
			GENERIC = "裝不下了。",
			NOTALLOWED = "這東西不能裝進那裡。",
		},
	},
	ACTIONFAIL_GENERIC = "這麼做沒用。",
    LICHEN = "生長緩慢的洞穴植物",
	ANNOUNCE_ADVENTUREFAIL = "除了我，沒人能成功。",
	ANNOUNCE_BEES = "就算殺了我，你的蜂蜜也不會回來的！",
	ANNOUNCE_BOOMERANG = "噢！我笨死了！",
	ANNOUNCE_CHARLIE = "查理？是我！麥斯威爾！",
	ANNOUNCE_CHARLIE_ATTACK = "噢！查理，這一下好疼！",
	ANNOUNCE_COLD = "我的心都變冷了。",
	ANNOUNCE_CRAFTING_FAIL = "呃... 我做不到。",
	ANNOUNCE_DEERCLOPS = "我聽到它們中有一隻來了。",
	ANNOUNCE_DUSK = "天馬上就黑了。查理會醒過來。",
	ANNOUNCE_EAT =
	{
		GENERIC = "（狼吞虎嚥！）",
		PAINFUL = "噢！它傷了我的嘴！",
		SPOILED = "這東西都爛掉了。",
		STALE = "這東西過了保鮮期。",
	},
	ANNOUNCE_ENTER_DARK = "好黑！我看不見了！",
	ANNOUNCE_ENTER_LIGHT = "又亮起來了。",
	ANNOUNCE_FREEDOM = "終於自由了！",
	ANNOUNCE_HIGHRESEARCH = "我的大腦中充滿了能量！",
	ANNOUNCE_HOUNDS = "獵犬蠢蠢欲動了。",
	ANNOUNCE_HUNGRY = "我的肚子空了。",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我聞到了糞便和野獸汗液的味道。",
	ANNOUNCE_HUNT_LOST_TRAIL = "該死！它消失了。",
	ANNOUNCE_INV_FULL = "我的口袋都裝滿了。",
	ANNOUNCE_KNOCKEDOUT = "呃。腦袋好疼。",
	ANNOUNCE_LOWRESEARCH = "它增進不了多少見識。",
	ANNOUNCE_MOSQUITOS = "多麼討厭的小蟲子。",
	ANNOUNCE_NODANGERSLEEP = "附近有危險，不能睡覺！",
	ANNOUNCE_NODAYSLEEP = "我在白天睡不著。",
	ANNOUNCE_NODAYSLEEP_CAVE = "現在睡覺會打亂我的作息規律！",
	ANNOUNCE_NOHUNGERSLEEP = "我太餓了， 睡不著。",
	ANNOUNCE_NO_TRAP = "好奇怪。他們忘記設陷阱了。",
	ANNOUNCE_PECKED = "耐心點！",
	ANNOUNCE_QUAKE = "那個轟隆隆的聲音一定不是好事。",
	ANNOUNCE_RESEARCH = "知識就是力量。而力量就是...好吧，還是力量。",
	ANNOUNCE_THORNS = "為了摘下它，我的手臂被劃傷了。",
	ANNOUNCE_TORCH_OUT = "見鬼，火又熄了。",
	ANNOUNCE_TRAP_WENT_OFF = "啊！",
	ANNOUNCE_UNIMPLEMENTED = "嗯，還沒有全部完成。",
	ANNOUNCE_WORMHOLE = "哎， 那裡面真是太嚇人了。",
	ANNOUNCE_CANFIX = "\n我覺得我能修好這個！",
	ANNOUNCE_NOSANITY = "我感到頭痛！",
	ANNOUNCE_NOFUEL = "我需要一些噩夢燃料。",
	ANNOUNCE_ACCOMPLISHMENT= "我得想點辦法打發時間。",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我感覺自己的努力沒有白費。",	
	BATTLECRY =
	{
		GENERIC = "拿起武器！",
		PIG = "智慧強於力量！",
		PREY = "你看起來很美味！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "給我離遠點！",
		PIG = "下次再教訓你，蠢豬！",
		PREY = "你不值得我浪費時間！",
	},
	DESCRIBE =
	{
		WAXWELLJOURNAL = "查理，我很抱歉。",
		WORMLIGHT = "多麼漂亮的騙局。",
		WORM =
		{
		    PLANT = "植物，你騙不了我。",
		    DIRT = "有東西在遁地行走。",
		    WORM = "噢，又來了新的！",
		},
		EEL = "它們只生活在深淵中。",
		EEL_COOKED = "它注定要成為盤中餐。",
		UNAGI = "我要大讚廚師！",
		EYETURRET = "我較好的作品。",
		EYETURRET_ITEM = "現在我只需要把它安放好。",
		MINOTAURHORN = "很抱歉我不得不那麼做，老友。",
		MINOTAURCHEST = "幾乎就像他還活著。",
		THULECITE_PIECES = "我可以將好幾塊碎片合成更大的一塊。",
		POND_ALGAE = "這是一些水藻。",
		GREENSTAFF = "我必須依賴這種形式的聚能工具。",
		POTTEDFERN = "好別緻。",

		THULECITE = "極其稀少卻很有用的材料。",
		ARMORRUINS = "銩礦與噩夢燃料結合得如此完美。",
		RUINS_BAT = "燃料深藏其中。",
		RUINSHAT = "裡面肯定有燃料在流動。",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "城市中心平靜無波。",	
			WARN = "它又開始跳動了。",	
			WAXING = "脈衝在加快。", 
			STEADY = "脈衝保持平穩。", 
			WANING = "脈衝在減弱。", 
			DAWN = "它又平靜下來了。", 
			NOMAGIC = "脈衝在這裡沒有影響。", 
		},
		BISHOP_NIGHTMARE = "因為保養不當，它們壞掉了。",
		ROOK_NIGHTMARE = "製造者遺棄了它。",
		KNIGHT_NIGHTMARE = "它看起來無法修了。",
		MINOTAUR = "天哪，噩夢燃料改變了你。",	
		SPIDER_DROPPER = "這個世界的生物進化的速度越來越恐怖了。",	
		NIGHTMARELIGHT = "過度使用燃料讓它們墮落了。",	
		RELIC = "我到这里的时候他们全都死了。",	
		RUINS_RUBBLE = "損毀的廢墟。",	
		MULTITOOL_AXE_PICKAXE = "不知道為什麼我過去沒想到用這個。",	
		GREENGEM = "噩夢燃料將釋放它的真正潛力。",
		ORANGESTAFF = "我必須依賴這種形式的聚能工具。",	
		YELLOWAMULET = "這將讓我引人注目。",	
		GREENAMULET = "我發誓，我平常不需要這個。",	

		SLURPER = "單蠢的生物。它們活著只是為了吃吃睡睡。",
		SLURPER_PELT = "這傢伙死後將為我所用！",
		ARMORSLURPER = "又濕又悶，填充材料也很怪。",
		ORANGEAMULET = "簡單的魔法往往是最好的。",
		YELLOWSTAFF = "有一個大點的寶石，它會強大得多。",
		YELLOWGEM = "我可以感覺到其中的魔力。",
		ORANGEGEM = "只要有一些燃料，它會相當強大。",
		TELEBASE = 
		{
			VALID = "應該可以啟動了。",
			GEMS = "燃料需要更多的聚能寶石。",
		},
		GEMSOCKET = 
		{
			VALID = "這個準備好了。",
			GEMS = "燃料需要聚能寶石。",
		},
		STAFFLIGHT = "這東西應該能趕走暗影。",
		RESEARCHLAB4 = "一台造型相當簡潔的機器。",
       	ANCIENT_ALTAR =
        {
        	WORKING = "他们的神现在在哪里？",
        	BROKEN = "这个可以在一定程度上修复。",
        },

        ANCIENT_STATUE = "曾經的高傲種族。",

		CAVE_BANANA = "就像我嘴裡進了灰。",
		CAVE_BANANA_COOKED = "比生的還難吃。",
		CAVE_BANANA_TREE = "它看起來像香蕉，但我可不相信。",
		ROCKY = "我把這些傢伙放逐到這下面是有原因的。",
		
		HOUNDSTOOTH="這可以用在時尚方面。",
		ARMORSNURTLESHELL="這一點也不體面。",
		BAT="呃。醜陋的怪物。",
		BATBAT = "暴力從未讓人感覺如此之爽。",
		BATWING="我不要吃這個。",
		BATWING_COOKED="我還是不要吃這個。",
		BEDROLL_FURRY="至少它們有些用處。",
		BUNNYMAN="這讓我想起了我的老本行。",
		FLOWER_CAVE="這下面太黑了。",
		FLOWER_CAVE_DOUBLE="這下面太黑了。",
		FLOWER_CAVE_TRIPLE="這下面太黑了。",
		GUANO="真噁心！",
		LANTERN="我希望這能趕跑它們。",
		LIGHTBULB="它最終會耗盡的。",
		MANRABBIT_TAIL="愚蠢的兔子。",
		MUSHTREE_TALL="它聞起來充滿了腐爛壞掉的味道。",
		MUSHTREE_MEDIUM="瓦爾多在哪裡？",
		MUSHTREE_SMALL="呃，它很難聞。",
		RABBITHOUSE="哦，真是太聰明了。",
		SLURTLE="我不記得那些東西了...",
		SLURTLE_SHELLPIECES="它們拼不回去。",
		SLURTLEHAT="在需要戰鬥時，它可以防止我倒下。",
		SLURTLEHOLE="真噁心。",
		SLURTLESLIME="肯定有更好的辦法。",
		SNURTLE="好奇怪。它們肯定是新來的。",
		SPIDER_HIDER="這傢伙有點難對付。",
		SPIDER_SPITTER="兇猛的小東西，不是嗎？",
		SPIDERHOLE="那東西是怎樣下來這裡的？",
		STALAGMITE="岩石。太無趣了。",
		STALAGMITE_FULL="岩石。太無趣了。",
		STALAGMITE_LOW="岩石。太無趣了。",
		STALAGMITE_MED="岩石。太無趣了。",
		STALAGMITE_TALL="石筍。太無趣了。",
		STALAGMITE_TALL_FULL="石筍。太無趣了。",
		STALAGMITE_TALL_LOW="石筍。太無趣了。",
		STALAGMITE_TALL_MED="石筍。太無趣了。",

		POWCAKE = "這是什麼邪惡的科學產物？",
		CAVE_ENTRANCE = 
		{
			GENERIC="很久以前我就把它堵上了。",
			OPEN = "這可不是個好主意！",
		},
        CAVE_EXIT = "我可以出去了！",

		MAXWELLPHONOGRAPH = "那個該死的東西！",
		BOOMERANG = "每次擊中目標都會髒了你的手。",
		PIGGUARD = "呸， 噁心的畜生。",
		ABIGAIL = "這些肉體凡胎為什麼不一直保持死亡的狀態呢？",
		ADVENTURE_PORTAL = "這就是我留下那件東西的地方了！",
		AMULET = "它輸送著宇宙中最黑暗的能量。",
		ANIMAL_TRACK = "某隻蠢笨的動物經過了這裡。",
		ARMORGRASS = "直接對抗是很粗魯的。",
		ARMORMARBLE = "這真的不是我的風格。",
		ARMORWOOD = "呃， 這種粗俗的鬥毆和我一點都不搭。",
		ARMOR_SANITY = "是時候把自己包裹在噩夢裡了。",
		ASH =
		{
			GENERIC = "細細的粉末，聞起來有毀滅的味道。",
			REMAINS_EYE_BONE = "別擔心。會有更多切斯特的。",
			REMAINS_THINGIE = "這肯定有個完美的科學解釋。",
		},
		AXE = "有時候，直截了當的方法是最好的。",
		BABYBEEFALO = "它們小時候就這麼醜。",
		BACKPACK = "我希望這附近有搬運工。",
		BACONEGGS = "我要大讚廚師！",
		BANDAGE = "又黏又甜，療傷效果不錯。",
		BASALT = "我造了塊石頭，重得我都抬不起來。",
		BEARDHAIR = "好多毛。",
		BEDROLL_STRAW = "我不喜歡露宿。",
		BEE =
		{
			GENERIC = "它們如此辛勤地工作，這些傻瓜。",
			HELD = "現在我拿它怎麼辦？",
		},
		BEEBOX =
		{
			FULLHONEY = "真誘人，但是蜜蜂太多了。",
			GENERIC = "我的蜜蜂就住在裡面。",
			NOHONEY = "我的蜜蜂不夠勤勞。",
			SOMEHONEY = "我應該等久一點。",
		},
		BEEFALO =
		{
			FOLLOWER = "該死，它在跟著我。",
			GENERIC = "看看那頭愚蠢的動物吧。",
			NAKED = "現在它看起來傻不拉幾又慘兮兮的。",
			SLEEPING = "它睡著後也還是一副蠢樣。",
		},
		BEEFALOHAT = "一點也不時尚。",
		BEEFALOWOOL = "聞起來像牲口棚的味道。",
		BEEHAT = "如果有必要，我會戴著它的。",
		BEEHIVE = "不要是蜜蜂啊！",
		BEEMINE = "它們等得很有耐心。",
		BEEMINE_MAXWELL = "也許我不該把它放在那裡。",
		BERRIES = "唉， 如果實在沒別的吃。",
		BERRIES_COOKED = "至少比原來好了點。",
		BERRYBUSH =
		{
			BARREN = "它需要施肥。",
			GENERIC = "淪落到吃漿果了。唉。",
			PICKED = "現在我們得等等。",
		},
		BIRDCAGE =
		{
			GENERIC = "你們再也不能將我重新關進牢籠。",
			OCCUPIED = "我瞭解你的心情，長羽毛的小傢伙。",
			SLEEPING = "當你醒來的時候，你還是在那裡面。",
		},
		BIRDTRAP = "它們前仆後繼地上當！",
		BIRD_EGG = "我喜歡把它想像成幼鳥的牢籠。",
		BIRD_EGG_COOKED = "有蛋黃的那一面朝上。",
		BISHOP = "我對那件作品感到特別自豪。",
		BLOWDART_FIRE = "一定要吹出去。",
		BLOWDART_SLEEP = "請稱呼我為睡魔先生。",
		BLOWDART_PIPE = "一根能造成痛苦的好管子！",
		BLUEAMULET = "凍過頭了。",
		BLUEGEM = "藍色會帶來冰。",
		BLUEPRINT = "這些我都知道。我只是忘記了。",
		BLUE_CAP = "會出什麼問題？",
		BLUE_CAP_COOKED = "真鮮啊！",
		BLUE_MUSHROOM =
		{
			GENERIC = "這些藍色的會有一些好處。",
			INGROUND = "它還沒長好呢。",
			PICKED = "下次再來採吧？",
		},
		BOARDS = "刨得很粗糙。",
		BOAT = "它哪兒也去不了。",
		BONESTEW = "我要大讚廚師！",
		BUGNET = "很適合用來抓毫無防備的昆蟲。",
		BUSHHAT = "那裡有我的藏身之處。",
		BUTTER = "一些冷笑話是免不了的，比如蝴蝶飛不動了就變成牛油了。",
		BUTTERFLY =
		{
			GENERIC = "會飛的花朵。",
			HELD = "如果有人把它的翅膀扯掉就太可恥了。",
		},
		BUTTERFLYMUFFIN = "我要大讚廚師！",
		BUTTERFLYWINGS = "哈哈哈， 我抓到他了！",
		CAMPFIRE =
		{
			EMBERS = "火要滅了。",
			GENERIC = "真舒服。",
			HIGH = "這會讓查理暫時遠離我。",
			LOW = "它需要燃料。",
			NORMAL = "正在燃燒。",
			OUT = "火不會重新燃起了。",
		},
		CANE = "它身上雕刻著神行物的圖案。",
		CARROT = "我不喜歡吃蔬菜。",
		CARROT_COOKED = "至少比原來好了點。",
		CARROT_PLANTED = "真平凡。",
		CARROT_SEEDS = "這種低賤的工作不適合我。",
		CAVE_FERN = "我想踩上去。",
		CHARCOAL = "沒什麼能偷走我的木炭！",
        CHESSJUNK1 = "機械垃圾。",
        CHESSJUNK2 = "機械垃圾。",
        CHESSJUNK3 = "機械垃圾。",
		CHESTER = "煩人的小怪物， 儘管有它的用途。",
		CHESTER_EYEBONE =
		{
			GENERIC = "不准再看我！",
			WAITING = "它在等什麼？",
		},
		COOKEDMANDRAKE = "它失去了不少力量。",
		COOKEDMEAT = "它現在沒有那麼難聞了。",
		COOKEDMONSTERMEAT = "如果沒得選的話，我會吃它的。",
		COOKEDSMALLMEAT = "嗯，至少它現在不動了。",
		COOKPOT =
		{
			COOKING_LONG = "等著...",
			COOKING_SHORT = "馬上就好了！",
			DONE = "終於有一些美食出爐了。",
			EMPTY = "想一想都讓我流口水。",
		},
		CORN = "富含果糖。",
		CORN_COOKED = "至少比原來好了點。",
		CORN_SEEDS = "這種低賤的工作不適合我。",
		CROW =
		{
			GENERIC = "我不知道它們怎麼到這裡來的。",
			HELD = "噓... 我的寶貝。",
		},
		LICHEN = "這些菌類植物在陷落中逃過一劫。",
		CUTLICHEN = "乾燥、鬆脆、有營養。",
		CUTGRASS = "大地上的凡物。",
		CUTREEDS = "我想我可以用這個來造點有用的東西。",
		CUTSTONE = "文明的基石。",
		DEADLYFEAST = "它聞起來...有毒。",
		DEERCLOPS = "連我都害怕那傢伙。",
		DEERCLOPS_EYEBALL = "巨鹿都是近視。",
		DEPLETED_GRASS =
		{
			GENERIC = "這對任何人都沒有好處。",
		},
		DIRTPILE = "那個看起來格格不入。",
		DIVININGROD =
		{
			COLD = "多半只是背景的雜音。",
			GENERIC = "我可以用這個找到我遺失的零件。",
			HOT = "它一定就在我的眼皮底下！",
			WARM = "這是正確的方向。",
			WARMER = "我應該睜大眼睛。",
		},
		DIVININGRODBASE =
		{
			GENERIC = "這是啟動裝置。",
			READY = "我需要插入探測杖。",
			UNLOCKED = "行了！",
		},
		DIVININGRODSTART = "這些門通往下一根探測杖。",
		DRAGONFRUIT = "美味又充滿異域風情。",
		DRAGONFRUIT_COOKED = "至少比原來好了點。",
		DRAGONFRUIT_SEEDS = "這種低賤的工作不適合我。",
		DRAGONPIE = "我要大讚廚師！",
		DRUMSTICK = "吃起來味道跟漿果一樣奇怪。",
		DRUMSTICK_COOKED = "嚐起來還是像漿果。",
		DUG_BERRYBUSH = "我看起來像個園丁嗎？",
		DUG_GRASS = "我看起來像個園丁嗎？",
		DUG_MARSH_BUSH = "我看起來像個園丁嗎？",
		DUG_SAPLING = "我看起來像個園丁嗎？",
		DURIAN = "這是後天養成的嗜好。",
		DURIAN_COOKED = "至少比原來好了點。",
		DURIAN_SEEDS = "這種低賤的工作不適合我。",
		EARMUFFSHAT = "至少它們是暖和的。",
		EGGPLANT = "又一株無聊的植物。",
		EGGPLANT_COOKED = "至少比原來好了點。",
		EGGPLANT_SEEDS = "這種低賤的工作不適合我。",
		EVERGREEN =
		{
			BURNING = "哎呀。",
			BURNT = "火的洗禮。",
			CHOPPED = "不會重新長出來了。",
			GENERIC = "我聽到它們被描述成「針葉樹」。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "哎呀。",
			BURNT = "塵歸塵，土歸土。",
			CHOPPED = "我讓它從痛苦中解脫了。",
			GENERIC = "它看上去生病了。",
		},
		EYEPLANT = "食人花的小兵。",
		FARMPLOT =
		{
			GENERIC = "我看起來像個農民嗎？",
			GROWING = "比起看植物是怎麼長大的，我有更重要的事情要做。",
			NEEDSFERTILIZER = "它需要...補充點營養。",
		},
		FEATHERHAT = "我會用我的羽毛引誘它們。",
		FEATHER_CROW = "黑色是睡眠的顏色。",
		FEATHER_ROBIN = "紅色是火的顏色。",
		FEATHER_ROBIN_WINTER = "灰色是疼痛的顏色。",
		FEM_PUPPET = "幸好是她不是我。",
		FIREFLIES =
		{
			GENERIC = "真美。",
			HELD = "要是我想的話，我可以捏扁它們。",
		},
		FIREHOUND = "我把火寶石放在了那裡，只是想開個玩笑。",
		FIREPIT =
		{
			EMBERS = "我應該注意的。",
			GENERIC = "一處石頭營火。",
			HIGH = "熊熊燃燒的火。",
			LOW = "火勢小了。",
			NORMAL = "有點熱。",
			OUT = "變冷了。",
		},
		FIRESTAFF = "一個基礎魔法，但是很有效。",
		FISH = "從混濁的深水中新鮮捕撈的。",
		FISHINGROD = "我要吃一輩子。",
		FISHSTICKS = "我要大讚廚師！",
		FISHTACOS = "我要大讚廚師！",
		FISH_COOKED = "還是很腥。",
		FLINT = "噢！我割到了手指！",
		FLOWER = "我現在充滿了想踩它幾腳的衝動。",
		FLOWERHAT = "絕對不是我的風格。",
		FLOWER_EVIL = "我喜歡那朵花。",
		FOLIAGE = "鄉下人最適合吃這個。",
		FOOTBALLHAT = "現在我已經準備好爭球了。",
		FROG =
		{
			DEAD = "它掛了。",
			GENERIC = "它喜歡跳躍和舔東西。",
			SLEEPING = "它看起來累了。",
		},
		FROGGLEBUNWICH = "我要大讚廚師！",
		FROGLEGS = "肌肉發達。",
		FROGLEGS_COOKED = "好勁道。",
		FRUITMEDLEY = "我要大讚廚師！",
		GEARS = "我的寶貝！你怎麼樣了？",
		GHOST = "它記得我！",
		GOLDENAXE = "每砍一次東西，它都會變得更鋒利。",
		GOLDENPICKAXE = "這肯定是遊戲邏輯。",
		GOLDENPITCHFORK = "我不確定這筆投資是否划算。",
		GOLDENSHOVEL = "這把鏟子價值不菲。",
		GOLDNUGGET = "這東西曾經對我很重要。",
		GRASS =
		{
			BARREN = "需要施肥。",
			BURNING = "哎呀。",
			GENERIC = "好多草。",
			PICKED = "沒什麼可以收穫的。",
		},
		GREEN_CAP = "我應該吃掉它。",
		GREEN_CAP_COOKED = "好鹹！",
		GREEN_MUSHROOM =
		{
			GENERIC = "綠色菌類。",
			INGROUND = "這些東西什麼時候會冒出來？",
			PICKED = "曾經在那裡， 已經採過了。",
		},
		GUNPOWDER = "這個東西我喜歡。",
		HAMBAT = "一件不太莊重的武器，適合不太講究的時候。",
		HAMMER = "破壞別人的勞動成果感覺真好。",
		HEALINGSALVE = "只有一些毒液和陳舊骯髒的灰燼。",
		HEATROCK =
		{
			COLD = "很清涼。",
			GENERIC = "裝在口袋裡的石頭，可以提供熱量。",
			HOT = "燙到拿不住。",
			WARM = "暖暖的，真舒服。",
		},
		HOME = "沒有什麼地方比家裡更好。",
		HOMESIGN = "上面寫著...什麼都沒寫。",
		HONEY = "又黏又甜。",
		HONEYCOMB = "裡面全是蜜蜂卵。",
		HONEYHAM = "我要大讚廚師！",
		HONEYNUGGETS = "我要大讚廚師！",
		HORN = "召喚犛牛！",
		HOUND = "它們不認識我！",
		HOUNDBONE = "它們是飢餓的惡魔，不是嗎？",
		HOUNDMOUND = "這是一個通往獵犬巢穴的通道。",
		ICEBOX = "這個箱子裡有點冬天的氣息。",
		ICEHOUND = "我有很多剩餘的寶石了！",
		INSANITYROCK =
		{
			ACTIVE = "我現在可以看到它真正的樣子了！",
			INACTIVE = "在這個平面上只能看到它的一半。",
		},
		JAMMYPRESERVES = "我要大讚廚師！",
		KABOBS = "我要大讚廚師！",
		KILLERBEE =
		{
			GENERIC = "那隻蜜蜂為什麼如此生氣？",
			HELD = "我抓住了老虎尾巴。",
		},
		KNIGHT = "如此巧奪天工的手藝！",
		KOALEFANT_SUMMER = "犛牛的遠親。",
		KOALEFANT_WINTER = "它穿上了自己的冬衣。",
		KRAMPUS = "你抓不到我的！",
		KRAMPUS_SACK = "它真的很輕。",
		LEIF = "討厭的生物！",
		LEIF_SPARSE = "討厭的生物！",
		LIGHTNING_ROD =
		{
			CHARGED = "能量從中流過。",
			GENERIC = "一點點保護。",
		},
		LITTLE_WALRUS = "一個模子裡印出來的傢伙。",
		LIVINGLOG = "我喜歡它們被點燃時的聲音。",
		LOCKEDWES = "他讓我不高興。",
		LOG =
		{
			BURNING = "好吧， 它燒起來很有意思。",
			GENERIC = "這是一塊木材。還有什麼要說的？",
		},
		LUREPLANT = "一株惡毒的植物。",
		LUREPLANTBULB = "或許我能讓它好好發揮作用。",
		MALE_PUPPET = "幸好是他不是我。",
		MANDRAKE =
		{
			DEAD = "我的耳朵還在嗡嗡作響。",
			GENERIC = "噢，閉嘴好嗎？",
			PICKED = "曼德拉草真是太煩人了。",
		},
		MANDRAKESOUP = "我要大讚廚師！",
		MANDRAKE_COOKED = "看來我叫到了最後。",
		MARBLE = "這東西很堅硬。",
		MARBLEPILLAR = "我總想知道誰建造了那些東西。",
		MARBLETREE = "真怪異。",
		MARSH_BUSH =
		{
			BURNING = "我應該問它一些問題。",
			GENERIC = "扭曲而多刺，就像我一樣！",
			PICKED = "刺得我好痛。",
		},
		MARSH_PLANT = "好普通的小植物。",
		MARSH_TREE =
		{
			BURNING = "就這樣吧。",
			BURNT = "它現在對任何人都沒有用處了。",
			CHOPPED = "樹木0，麥斯威爾1。",
			GENERIC = "一棵姿勢怪異的樹。",
		},
		MAXWELL = "看上去不錯！",
		MAXWELLHEAD = "嗨，帥哥。",
		MAXWELLLIGHT = "哦，它記得我。",
		MAXWELLLOCK = "它能將主人鎖在王座上。",
		MAXWELLTHRONE = "它沒有看上去那麼讓人痛苦， 但也只是好一點點。",
		MEAT = "我過去吃得比這好多了。",
		MEATBALLS = "我要大讚廚師！",
		MEATRACK =
		{
			DONE = "就像沙漠一樣幹。",
			DRYING = "還是很濕。",
			GENERIC = "它可以把肉曬乾，讓肉不容易腐爛。",
		},
		MEAT_DRIED = "我的牙根本咬不動這個。",
		MERM = "我到這裡的時候他們已經在這了。",
		MERMHEAD = "它的眼睛注視著你。",
		MERMHOUSE = "他們照搬了豬屋的設計，但他們甚至還沒有豬聰明。",
		MINERHAT = "這些螢火蟲最終會餓死的。",
		MONKEY = "我可沒時間浪費在你身上！",
		MONKEYBARREL = "多令人厭惡的家。",
		MONSTERLASAGNA = "我要大讚廚師！",
		MONSTERMEAT = "真噁心。",
		MONSTERMEAT_DRIED = "我的牙根本咬不動這個。",
		MOSQUITO =
		{
			GENERIC = "貪婪的吸血蟲，真該下地獄。",
			HELD = "我抓到他了。",
		},
		MOSQUITOSACK = "一個血腥的袋子。裡面裝滿了血。",
		MOUND =
		{
			DUG = "已經挖過了。",
			GENERIC = "下面有什麼？",
		},
		NIGHTLIGHT = "它點燃時發出美麗的光芒。",
		NIGHTMAREFUEL = "啊~ 真提神。",
		NIGHTSWORD = "嚓嚓！",
		NITRE = "火藥的三種成分之一...",
		ONEMANBAND = "這個拍子不錯，你可以隨它起舞。",
		PANDORASCHEST = "這是一個陷阱。",
		PANFLUTE = "我要唱一首瘋狂之歌。",
		PAPYRUS = "一塊空白畫布。",
		PENGUIN = "不錯的晚禮服。",
		PERD = "它對發酵的漿果上癮。",
		PEROGIES = "我要大讚廚師！",
		PETALS = "就像很多五彩紙屑。",
		PETALS_EVIL = "它充滿噩夢的精華。",
		PICKAXE = "人人都愛挖點礦。",
		PIGGYBACK = "哦，背這個有損身份。",
		PIGHEAD = "呃...好迷人。",
		PIGHOUSE =
		{
			FULL = "如果我是他，我也會進去的。",
			GENERIC = "那是他們唯一的技巧。",
			LIGHTSOUT = "我吹，我吹，我吹吹吹！",
		},
		PIGKING = "這是一個將生活安排得井井有條的男人！",
		PIGMAN =
		{
			DEAD = "我給你取名叫「培根」。",
			FOLLOWER = "他很單純，但他是我的。",
			GENERIC = "真是個口水直流的傻瓜。",
			GUARD = "他們開始變得有組織性了。",
			WEREPIG = "那隻豬瘋了。",
		},
		PIGSKIN = "當時不是他死就是我亡。",
		PIGTENT = "真髒。",
		PIGTORCH = "太好了。現在他們有火了。",
		PINECONE = 
		{
		    GENERIC = "一個更熱愛戶外的人或許能用這個來做點什麼。",
		    PLANTED = "哈，它看起來屬於大地。",
		},
		PITCHFORK = "完美主義者的理想工具。",
		PLANTMEAT = "愚蠢的騙局，只有傻子才會上當。",
		PLANTMEAT_COOKED = "它烤熟後就可以吃了。",
		PLANT_NORMAL =
		{
			GENERIC = "這是一株普通的植物。",
			GROWING = "它正在生長。",
			READY = "可以收穫了。",
		},
		POMEGRANATE = "通常我會找人來幫我播種。",
		POMEGRANATE_COOKED = "至少比原來好了點。",
		POMEGRANATE_SEEDS = "這種低賤的工作不適合我。",
		POND = "我可以從池面倒影中看到我的臉。",
		POOP = "凡間所有生命都免不了吃喝拉撒。",
		PUMPKIN = "萬聖節始終是我的最愛。",
		PUMPKINCOOKIE = "我要大讚廚師！",
		PUMPKIN_COOKED = "至少比原來好了點。",
		PUMPKIN_LANTERN = "哎呀，你好，無頭騎士先生。",
		PUMPKIN_SEEDS = "這種低賤的工作不適合我。",
		PURPLEAMULET = "它與暗影交談。",
		PURPLEGEM = "紫色能帶來強大的力量。",
		RABBIT =
		{
			GENERIC = "我已經在這裡太久了 — 它看上去確實很美味。",
			HELD = "別擔心，小兔子。一切都在掌握之中。",
		},
		RABBITHOLE = "在那下面還有一個世界。",
		RAINOMETER = "我只要抬頭看看天，就可以瞭解到同樣的資訊。",
		RATATOUILLE = "我要大讚廚師！",
		RAZOR = "要是整個世界只有一個脖子該多好。",
		REDGEM = "紅色帶來火焰。",
		RED_CAP = "我忘記這東西有什麼用了。",
		RED_CAP_COOKED = "有點苦。",
		RED_MUSHROOM =
		{
			GENERIC = "是紅蘑菇。",
			INGROUND = "我得過會再來採收它。",
			PICKED = "已經採光了。",
		},
		REEDS =
		{
			BURNING = "哎呀。",
			GENERIC = "起風時，就好像聽到柳林中的風聲。",
			PICKED = "沒有蘆葦管了。",
		},
        RELIC = 
        {
            GENERIC = "已經湮滅的文明的遺跡。",
            BROKEN = "只是岩石的碎塊",
        },
        RUINS_RUBBLE = "損毀的廢墟。",
        RUBBLE = "只是岩石的碎塊",
		RESEARCHLAB = "難以置信，我忘記了怎樣造那些東西。",
		RESEARCHLAB2 = "它解鎖了中級工具的製造配方。",
		RESEARCHLAB3 = "這是我做個人研究的地方。",
		RESURRECTIONSTATUE = "我可不會為使用這個而感到羞愧。",
		RESURRECTIONSTONE = "在那背後有一段故事...",
		ROBIN =
		{
			GENERIC = "紅雀來自炎火之地。",
			HELD = "安靜點，小鳥！",
		},
		ROBIN_WINTER =
		{
			GENERIC = "我不認識那隻鳥。",
			HELD = "你給我安靜點。",
		},
		ROBOT_PUPPET = "幸好是它不是我。",
		ROCK_LIGHT =
		{
			GENERIC = "裹了石皮的熔岩坑。",
			OUT = "它看起來無害。",
			LOW = "火焰正在冷卻",
			NORMAL = "有點熱。",
		},
		ROCK = "這是一塊石頭。",
		ROCKS = "嗯， 現在我該對它們做什麼？",
        ROOK = "可以安家的城堡。",
		ROPE = "你會認為這東西有更多用途。",
		ROTTENEGG = "真噁心。我為什麼要把這個帶在身上？",
		SANITYROCK =
		{
			ACTIVE = "我現在可以看到它真正的樣子了！",
			INACTIVE = "有兩種方法可以看到那個障礙物。",
		},
		SAPLING =
		{
			BURNING = "哎呀。",
			GENERIC = "柔軟的木莖。",
			PICKED = "它會再長出來的。",
		},
		SEEDS = "我想這些東西不會把自己種下去。",
		SEEDS_COOKED = "我把它們烤死了。",
		SEWING_KIT = "一項精細高尚的事業。",
		SHOVEL = "這可是真正的先進技術。",
		SILK = "不論它來自哪裡，至少可以做成不錯的衣服。",
		SKELETON = "哈！我記得這個。",
		SKULLCHEST = "那是個時髦的箱子。",
		SMALLBIRD =
		{
			GENERIC = "什麼！？你想要什麼？",
			HUNGRY = "你想要些吃的？",
			STARVING = "他很餓！",
		},
		SMALLMEAT = "這連一口都沒有。",
		SMALLMEAT_DRIED = "我的牙根本咬不動這個。",
		SPEAR = "這是一根長矛。是的。",
		SPIDER =
		{
			DEAD = "啪嘰。",
			GENERIC = "這東西基本上是個消化系統。",
			SLEEPING = "噓！它醒來會餓的。",
		},
		SPIDERDEN = "它們在這裡長大。",
		SPIDEREGGSACK = "黏糊糊的。",
		SPIDERGLAND = "真倒胃口。",
		SPIDERHAT = "蜘蛛的意志力真是太不堅定了。",
		SPIDERQUEEN = "或許我不該擋她的路。",
		SPIDER_WARRIOR =
		{
			DEAD = "啪嘰。",
			GENERIC = "它是一個特殊品種。",
			SLEEPING = "我可不想弄醒它。",
		},
		SPOILED_FOOD = "曾經是食物，直到我浪費了它。",
		STATUEHARP = "並非我的最佳作品。",
		STATUEMAXWELL = "真是座不錯的雕像。",
		STINGER = "它充滿了毒液。",
		STRAWHAT = "這帽子看起來很土。",
		STUFFEDEGGPLANT = "我要大讚廚師！",
		SUNKBOAT = "船不該這麼用！",
		SWEATERVEST = "雖然不是三件式的，但足夠體面。",
		TAFFY = "我要大讚廚師！",
		TALLBIRD = "它們是失敗的實驗產物。",
		TALLBIRDEGG = "因為這些東西的存在，高腳鳥很有領地意識。",
		TALLBIRDEGG_COOKED = "它的味道就像破碎的夢想。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "火不太熱了。",
			GENERIC = "這裡有一個活物。",
			HOT = "對你來說夠熱了？",
			LONG = "還要等好大一會。",
			SHORT = "時間就要到了...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "哦， 真誘人。",
			PICKED = "它是用骯髒的牛毛做成的。",
		},
		TEENBIRD =
		{
			GENERIC = "長大後沒那麼可愛了。",
			HUNGRY = "它們肯定吃得很多。",
			STARVING = "飢餓的野獸是危險的。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "它還活著！",
			GENERIC = "我美麗的機器已經被拆成了很多塊！",
			LOCKED = "現在開啟它。",
			PARTIAL = "它仍然不完整。",
		},
		TELEPORTATO_BOX = "這是一個充滿悲傷和痛苦的盒子。",
		TELEPORTATO_CRANK = "這是用來啟動幽默成分的。",
		TELEPORTATO_POTATO = "這裡面的齒輪非常小，但它們改變了真實世界的脈絡。",
		TELEPORTATO_RING = "這是量子場的防護頻帶。",
		TELESTAFF = "當能量沿正確的通道流動時，就能做出令人驚歎的事情。",
		TENT = "就我的品味而言，它太土氣了。",
		TENTACLE = "我很高興，它的其餘部分還在下面。",
		TENTACLESPIKE = "呃。這東西真噁心。",
		TENTACLESPOTS = "這就是它們繁殖的方式。",
		TENTACLE_PILLAR = "這個到底能去到多深的地方？",
		TENTACLE_GARDEN = "這東西真古怪。",
        TENTACLE_PILLAR_ARM = "小觸手？",
		TOPHAT = "一件精美的服飾用品。",
		TORCH = "它讓查理無法接近。",
		TRAP = "只有最蠢的動物才會掉進這個陷阱。",
		TRAP_TEETH = "掉進去就會被猛揍一頓。",
		TRAP_TEETH_MAXWELL = "我確信我放置這東西是有原因的。",
		TREASURECHEST = "一個裝戰利品的地方。",
		TREASURECHEST_TRAP = "這個嘛， 看上去很可疑。",
		TREECLUMP = "我沒辦法通過那裡。",
		TRINKET_1 = "這曾經對某個人很重要。",
		TRINKET_10 = "這曾經對某個人很重要。",
		TRINKET_11 = "這曾經對某個人很重要。",
		TRINKET_12 = "這曾經對某個人很重要。",
		TRINKET_2 = "這曾經對某個人很重要。",
		TRINKET_3 = "這曾經對某個人很重要。",
		TRINKET_4 = "這曾經對某個人很重要。",
		TRINKET_5 = "這曾經對某個人很重要。",
		TRINKET_6 = "這曾經對某個人很重要。",
		TRINKET_7 = "這曾經對某個人很重要。",
		TRINKET_8 = "這曾經對某個人很重要。",
		TRINKET_9 = "這曾經對某個人很重要。",
		TRUNKVEST_SUMMER = "這不僅僅是件秋天穿的背心。",
		TRUNKVEST_WINTER = "在冬天要時尚點真是太不容易了。",
		TRUNK_COOKED = "至少這些鼻涕被燒光了。",
		TRUNK_SUMMER = "全是夏天的鼻涕。",
		TRUNK_WINTER = "為了裝更多鼻涕，象鼻在冬天變厚了。",

		TURF_CARPETFLOOR = "這是一塊高品質長毛絨地毯的樣品！",
		TURF_CHECKERFLOOR = "這是我的自然棲息地。",
		TURF_DIRT = "好多塵土。",
		TURF_FOREST = "聞起來像泥土。",
		TURF_GRASS = "好多草。",
		TURF_MARSH = "到處都在滴水。",
		TURF_ROAD = "至少這個是有用的。",
		TURF_ROCKY = "有點粗糙。",
		TURF_SAVANNA = "好髒。",
		TURF_WOODFLOOR = "我更喜歡硬木。",

		TURF_CAVE="地面。",
		TURF_FUNGUS="地面。",
		TURF_SINKHOLE="地面。",
		TURF_UNDERROCK="地面。",
		TURF_MUD="地面。",

		TURKEYDINNER = "真有節日氣氛。",
		TWIGS = "雖然普通，但是很有用。",
		UMBRELLA = "傘柄是彎的！",
		WAFFLES = "我要大讚廚師！",
		WALL_HAY = "它是一個易燃物。",
		WALL_HAY_ITEM = "口袋大小的牆體。是的。",
		WALL_STONE = "那些烏合之眾再也進不來了。",
		WALL_STONE_ITEM = "口袋大小的牆體。是的。",
		WALL_WOOD = "有點堅硬，但還是可以燃燒的。",
		WALL_WOOD_ITEM = "口袋大小的牆體。是的。",
		WALL_RUINS = "古老的牆。",
		WALL_RUINS_ITEM = "口袋大小的牆體。是的。",
		WALRUS = "你不認識我了？",
		WALRUSHAT = "蘇格蘭製造。",
		WALRUS_CAMP =
		{
			EMPTY = "冬天來的時候，我最好別在這裡晃悠。",
			GENERIC = "海象肯定在不遠的地方。",
		},
		WALRUS_TUSK = "我會讓它有更好的用途。",
		WASPHIVE = "那個看起來很危險。",
		WETGOOP = "我要大讚廚師！",
		WINTERHAT = "令人失望的土氣帽子。",
		WINTEROMETER = "不是最有用的發明，對嗎？",
		WORMHOLE =
		{
			GENERIC = "知道其他部分長什麼樣子後感覺更糟糕。",
			OPEN = "我保證，它聞起來比看上去更糟糕。",
		},
		WORMHOLE_LIMITED = "它看上去生病了。",
		ACCOMPLISHMENT_SHRINE = "即使是他們，也造不出如此陰險的東西。",		
		LIVINGTREE = "它有一張臉。",
		ICESTAFF = "又冷又酷的東西。",
	},
	DESCRIBE_GENERIC = "誰來介紹一下這個？",
	DESCRIBE_TOODARK = "我在黑暗中什麼都看不見！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "味道和期待的一樣好。",
	},
}
