return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "깨어 있을 때 시도하지 않을 거야.",
			GENERIC = "그것은 깎을 수 없어!",
			NOBITS = "짧은 수염도 남지 않았다!",
		},
		STORE =
		{
			GENERIC = "가득 찼다.",
			NOTALLOWED = "그 안에 들어가지 않는다.",
		},
	},
	ACTIONFAIL_GENERIC = "그것은 할 수 없다.",
	ANNOUNCE_ADVENTUREFAIL = "잘 안 됐어. 다시 시도해야겠어.",
	ANNOUNCE_BEES = "벌이다!!!!",
	ANNOUNCE_BOOMERANG = "이런!저걸 잡아야 되겠다!",
	ANNOUNCE_CHARLIE = "뭐였지?!",
	ANNOUNCE_CHARLIE_ATTACK = "이런!무언가가 날 물었다!",
	ANNOUNCE_COLD = "너무 춥다!",
	ANNOUNCE_CRAFTING_FAIL = "재료를 다 갖고 있지 않아.",
	ANNOUNCE_DEERCLOPS = "큰 소리였다!",
	ANNOUNCE_DUSK = "늦어지고 있다. 곧 캄캄해질 거다.",
	ANNOUNCE_EAT =
	{
		GENERIC = "냠!",
		PAINFUL = "속이 안 좋다.",
		SPOILED = "우엑!끔찍했다!",
		STALE = "변하기 시작했던 것 같다.",
	},
	ANNOUNCE_ENTER_DARK = "너무 어두워!",
	ANNOUNCE_ENTER_LIGHT = "다시 보인다!",
	ANNOUNCE_FREEDOM = "자유다!드디어 자유다!",
	ANNOUNCE_HIGHRESEARCH = "지금 아주 영리해진 느낌이 든다!",
	ANNOUNCE_HOUNDS = "소리가 들렸나?",
	ANNOUNCE_HUNGRY = "너무 배고파!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "이 자국은 새 거다. 근처에 짐승이 있는 모양이군.",
	ANNOUNCE_HUNT_LOST_TRAIL = "흔적이 여기에서 끝났다.",
	ANNOUNCE_INV_FULL = "물건을 더 휴대할 수 없다!",
	ANNOUNCE_KNOCKEDOUT = "윽, 머리야!",
	ANNOUNCE_LOWRESEARCH = "많은 것을 배우지 못했다.",
	ANNOUNCE_MOSQUITOS = "아!가 버려!",
	ANNOUNCE_NODANGERSLEEP = "지금은 너무 위험해!",
	ANNOUNCE_NODAYSLEEP = "밖이 너무 밝다.",
	ANNOUNCE_NODAYSLEEP_CAVE = "피곤하지 않다.",
	ANNOUNCE_NOHUNGERSLEEP = "자기에는 너무 배고프다. 꼬르륵거려서 잠 못 자겠지!",
	ANNOUNCE_NO_TRAP = "쉬웠다.",
	ANNOUNCE_PECKED = "이런!그만 해!",
	ANNOUNCE_QUAKE = "예감이 안 좋은 소리다.",
	ANNOUNCE_RESEARCH = "절대로 배움을 멈추지 말라!",
	ANNOUNCE_THORNS = "이런!",
	ANNOUNCE_TORCH_OUT = "불이 방금 꺼졌다!",
	ANNOUNCE_TRAP_WENT_OFF = "아차.",
	ANNOUNCE_UNIMPLEMENTED = "이런!아직 준비되지 않은 것 같다.",
	ANNOUNCE_WORMHOLE = "멀쩡한 정신으로 할 짓이 아니었다.",
	ANNOUNCE_CANFIX = "\n고칠 수 있을 것 같다!",
	ANNOUNCE_ACCOMPLISHMENT = "많은 것을 성취한 느낌!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "친구들이 지금 나를 볼 수 있다면...",	
	BATTLECRY =
	{
		GENERIC = "눈을 공격해!",
		PIG = "이리 와, 돼지야!",
		PREY = "널 파괴하겠어!",
		SPIDER = "널 밟아 죽이겠어!",
		SPIDER_WARRIOR = "나보단 네가 당하는 것이 낫지!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "본때를 보였다!",
		PIG = "놓아주지. 이번엔.",
		PREY = "너무 빠르다!",
		SPIDER = "어차피 너무 징그러워.",
		SPIDER_WARRIOR = "꺼져, 못된 것!",
	},
	DESCRIBE =
	{
		WORMLIGHT = "맛있어 보인다.",
		WORM =
		{
		    PLANT = "안전해 보인다.",
		    DIRT = "흙 더미로 보일 뿐이다.",
		    WORM = "벌레다!",
		},

		EEL = "맛있는 식사가 되겠지.",
		EEL_COOKED = "냄새 좋다!",
		UNAGI = "내가 직접 요리했다!",
		EYETURRET = "날 배신하지 않길 바란다.",
		EYETURRET_ITEM = "자고 있는 것 같다.",
		MINOTAURHORN = "휴우!나를 꿰뚫지 않아서 다행이다!",
		MINOTAURCHEST = "더 크고 굉장한 것이 들어있을 것 같다!아니면 끔찍한 것일까.",
		THULECITE_PIECES = "작은 툴레사이트 덩어리다.",
		POND_ALGAE = "연못가에 조류가 있다.",
		GREENSTAFF = "도움이 되겠지.",
		POTTEDFERN = "단지 안에 든 양치류.",

		THULECITE = "어디에서 온 것일까?",
		ARMORRUINS = "이상하게 가볍다.",
		RUINS_BAT = "꽤 묵직하다.",
		RUINSHAT = "왕에게 어울린다. 나에게도 어울린다.",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "좋은 상태다.",
		WARN = "마법이 점점 느껴진다.",
		WAXING = "더 집중되고 있는 것 같다!",
		STEADY = "안정성을 유지하는 것 같다.",
		WANING = "감퇴하는 느낌이다.",
		DAWN = "악몽이 거의 떠났다!",
		NOMAGIC = "여기엔 마법이 없다.",
		},
		BISHOP_NIGHTMARE = "산산조각나고 있다!",
		ROOK_NIGHTMARE = "겁난다!",
		KNIGHT_NIGHTMARE = "나이트메어다!",
		MINOTAUR = "행복해 보이지 않는다.",
		SPIDER_DROPPER = "위를 보지 말자.",
		NIGHTMARELIGHT = "무슨 기능을 할까.",
		GREENGEM = "녹색이고 보석인 듯.",
		RELIC = "고대 가재 도구.",
		RUINS_RUBBLE = "수리할 수 있겠다.",
		MULTITOOL_AXE_PICKAXE = "찬란하다!",
		ORANGESTAFF = "걷는 것보다 낫다.",
		YELLOWAMULET = "촉감이 따뜻하다.",
		GREENAMULET = "더 좋아질 수 없을 것이라고 생각했는데.",
		SLURPERPELT = "죽어도 별로 달라 보이지 않는다.",	

		SLURPER = "털이 너무 많다!",
		SLURPER_PELT = "죽어도 별로 달라 보이지 않는다.",
		ARMORSLURPER = "축축하고, 기운을 주고, 즙이 많은 슈트.",
		ORANGEAMULET = "원격이동은 정말 유용하다.",
		YELLOWSTAFF = "막대에 보석 박았다.",
		YELLOWGEM = "이 보석은 노란색.",
		ORANGEGEM = "주황색 보석이다.",
		TELEBASE = 
		{
			VALID = "준비 됐다.",
			GEMS = "자주색 보석이 더 필요하다.",
		},
		GEMSOCKET = 
		{
			VALID = "준비된 것 같다.",
			GEMS = "보석이 필요해.",
		},
		STAFFLIGHT = "정말 위험해 보인다.",
		RESEARCHLAB4 = "누가 저것에 이름을 붙일까?",
	
        ANCIENT_ALTAR = "오래된 신비로운 구조물.",

        ANCIENT_ALTAR_BROKEN = "부서진 것 같다.",

        ANCIENT_STATUE = "세계와는 다른 리듬이 느껴진다.",

        LICHEN = "이 빛으로는 남세균만 자랄 수 있다.",
		CUTLICHEN = "영양가 있지만 오래 가진 않겠지.",

		CAVE_BANANA = "물컹하다.",
		CAVE_BANANA_COOKED = "냠!",
		CAVE_BANANA_TREE = "수상쩍게 광합성이다.",
		ROCKY = "갈고리 발톱이 끔찍하다.",
		
		COMPASS =
		{
			GENERIC="판독할 수 없다.",
			N = "북",
			S = "남",
			E = "동",
			W = "서",
			NE = "북동",
			SE = "남동",
			NW = "북서",
			SW = "남서",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "더 집중되고 있는 것 같다!",
			STEADY = "안정성을 유지하는 것 같다.",
			WANING = "감퇴하는 느낌이다.",
			DAWN = "악몽이 거의 떠났다!",
			WARN = "마법이 점점 느껴진다.",
			CALM = "좋은 상태다.",
			NOMAGIC = "여기엔 마법이 없다.",
		},

		HOUNDSTOOTH="날카롭다!",
		ARMORSNURTLESHELL="등에 달라붙는다.",
		BAT="악!무서운 거다!",
		BATBAT = "이걸 두 개 들면 날 수 있겠지.",
		BATWING="이것들은 죽었어도 싫다.",
		BATWING_COOKED="적어도 돌아오진 않으니까.",
		BEDROLL_FURRY="아주 따뜻하고 포근하다.",
		BUNNYMAN="과학적인 것을 하고 싶은 욕망이 불끈 솟는다.",
		FLOWER_CAVE="과학이 빛나게 한다.",
		FLOWER_CAVE_DOUBLE="과학이 빛나게 한다.",
		FLOWER_CAVE_TRIPLE="과학이 빛나게 한다.",
		GUANO="다른 맛의 똥.",
		LANTERN="더 품위 있는 빛.",
		LIGHTBULB="이상하게 맛있어 보인다.",
		MANRABBIT_TAIL="쥐고 있는 것이 기분 좋다.",
		MUSHTREE_TALL  ="버섯이 너무 커져 버렸다.",
		MUSHTREE_MEDIUM="내 화장실에서 이런 것이 자랐었는데.",
		MUSHTREE_SMALL ="마법 버섯?",
		RABBITHOUSE="진짜 당근이 아니다.",
		SLURTLE="우웩. 우웩이다.",
		SLURTLE_SHELLPIECES="해결책이 없는 퍼즐.",
		SLURTLEHAT="내 헤어스타일을 망치지 않았으면 좋겠는데.",
		SLURTLEHOLE="'우웩'이 많다.",
		SLURTLESLIME="유용하지 않으면 건드리지도 않을 텐데.",
		SNURTLE="덜 징그럽지만 그래도 징그럽다.",
		SPIDER_HIDER="으앗!거미가 더 있다!",
		SPIDER_SPITTER="거미가 싫다!",
		SPIDERHOLE="오래된 거미줄이 얽혀 있다.",
		STALAGMITE="돌로 보이는데.",
		STALAGMITE_FULL="돌로 보이는데.",
		STALAGMITE_LOW="돌로 보이는데.",
		STALAGMITE_MED="돌로 보이는데.",
		STALAGMITE_TALL="바위, 바위, 바위, 바위...",
		STALAGMITE_TALL_FULL="바위, 바위, 바위, 바위...",
		STALAGMITE_TALL_LOW="바위, 바위, 바위, 바위...",
		STALAGMITE_TALL_MED="바위, 바위, 바위, 바위...",

		TURF_CARPETFLOOR = "은근히 긁힌다.",
		TURF_CHECKERFLOOR = "꽤 근사하다.",
		TURF_DIRT = "땅덩이.",
		TURF_FOREST = "땅덩이.",
		TURF_GRASS = "땅덩이.",
		TURF_MARSH = "땅덩이.",
		TURF_ROAD = "급하게 깐 자갈.",
		TURF_ROCKY = "땅덩이.",
		TURF_SAVANNA = "땅덩이.",
		TURF_WOODFLOOR = "바닥 널이다.",

		TURF_CAVE="또 다른 지형이다.",
		TURF_FUNGUS="또 다른 지형이다.",
		TURF_SINKHOLE="또 다른 지형이다.",
		TURF_UNDERROCK="또 다른 지형이다.",
		TURF_MUD="또 다른 지형이다.",

		POWCAKE = "그 정도로 배고프진 않은 것 같다.",
        CAVE_ENTRANCE = 
        {
            GENERIC="저 바위를 움직일 수 있을까.",
            OPEN = "저 아래에서 발견할 것이 많겠지.",
        },
        CAVE_EXIT = "이제 발견하는 것이 지쳤다.",
		MAXWELLPHONOGRAPH = "저기에서 음악이 들려 온 것이었군.",
		BOOMERANG = "공기역학의 승리!",
		PIGGUARD = "다른 것들처럼 친근해 보이지 않는다.",
		ABIGAIL = "오호, 예쁜 리본을 달고 있다.",
		ADVENTURE_PORTAL = "두 번 들어가고 싶지는 않은데.",
		AMULET = "착용하고 있으면 무척 안전하게 느껴진다.",
		ANIMAL_TRACK = "음식이 남긴 자국. 아니... 동물이 남긴.",
		ARMORGRASS = "안에 벌레가 없길 바란다.",
		ARMORMARBLE = "정말 무거워 보인다.",
		ARMORWOOD = "완벽하게 합리적인 의류다.",
		ARMOR_SANITY = "이걸 쓰면 안전하고 불안하게 느끼겠지.",
		ASH =
		{
			GENERIC = "불타고 남은 것뿐이다.",
			REMAINS_EYE_BONE = "내가 원격이동했을 때 눈뼈가 타버렸다!",
			REMAINS_THINGIE = "타기 전엔 무언가였을 텐데...",
		},
		AXE = "믿음직한 도끼.",
		BABYBEEFALO = "오호. 너무 귀엽다!",
		BACKPACK = "물건을 집어넣는 것.",
		BACONEGGS = "내가 직접 요리했다!",
		BANDAGE = "적당히 무균인 것 같다.",
		BASALT = "너무 강해서 부술 수 없다!",
		BATBAT = "이걸 두 개 들면 날 수 있겠지.",
		BEARDHAIR = "내 얼굴로 만들었다.",
		BEDROLL_STRAW = "축축한 냄새가 난다.",
		BEE =
		{
			GENERIC = "벌이거나 벌이 아니거나.",
			HELD = "조심!",
		},
		BEEBOX =
		{
			FULLHONEY = "꿀이 가득 있다.",
			GENERIC = "벌!",
			NOHONEY = "비어있다.",
			SOMEHONEY = "좀 기다려야겠다.",
		},
		BEEFALO =
		{
			FOLLOWER = "평온하게 따라오고 있다.",
			GENERIC = "고기물소다!",
			NAKED = "어, 무척 슬퍼하고 있구나.",
			SLEEPING = "정말 깊게 잠을 자고 있다.",
		},
		BEEFALOHAT = "아주 좋은 모자다.",
		BEEFALOWOOL = "고기물소 눈물 냄새가 난다.",
		BEEHAT = "보호 받을 수 있겠다.",
		BEEHIVE = "활동이 많다.",
		BEEMINE = "흔들면 윙윙거리는 소리가 난다.",
		BEEMINE_MAXWELL = "병에 든 모기의 분노!",
		BERRIES = "빨간 베리가 가장 맛있다.",
		BERRIES_COOKED = "가열해서 더 좋아진 것 같진 않다.",
		BERRYBUSH =
		{
			BARREN = "비료가 필요한 것 같다.",
			GENERIC = "빨간 베리가 가장 맛있다.",
			PICKED = "다시 자라지 않을까?",
		},
		BIRDCAGE =
		{
			GENERIC = "안에 새를 넣어야겠다.",
			OCCUPIED = "내가 새 주인이다!",
			SLEEPING = "오호, 자고 있네.",
		},
		BIRDTRAP = "탁월한 우위!",
		BIRD_EGG = "작은 평범한 알.",
		BIRD_EGG_COOKED = "노른자가 맛있다!",
		BISHOP = "물러서라, 설교자!",
		BLOWDART_FIRE = "근본적으로 안전해 보이지 않는다.",
		BLOWDART_SLEEP = "들이쉬지 않도록 한다.",
		BLOWDART_PIPE = "생일 케이크를 불기 위한 좋은 연습!",
		BLUEAMULET = "얼음처럼 차갑다!",
		BLUEGEM = "냉기가 깜박거리며 빛난다.",
		BLUEPRINT = "과학적이다!",
		BLUE_CAP = "이상하고 끈적거린다.",
		BLUE_CAP_COOKED = "지금은 다른데...",
		BLUE_MUSHROOM =
		{
			GENERIC = "버섯이다.",
			INGROUND = "자고 있다.",
			PICKED = "다시 돌아올까?",
		},
		BOARDS = "판자.",
		BOAT = "저 것으로 제가 온 건가요?",
		BONESTEW = "내가 직접 요리했다!",
		BUGNET = "벌레 잡는 용이다.",
		BUSHHAT = "좀 가렵다.",
		BUTTER = "버터인 것을 믿을 수 없어!",
		BUTTERFLY =
		{
			GENERIC = "나비야, 날아라.",
			HELD = "이제 널 잡았다!",
		},
		BUTTERFLYMUFFIN = "내가 직접 요리했다!",
		BUTTERFLYWINGS = "이게 없다면 버터만 있는 거다.",
		CAMPFIRE =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "캄캄한 것보단 훨씬 좋다.",
			HIGH = "불이 너무 크다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "따뜻해서 좋다.",
			OUT = "결국 끝나 버렸다.",
		},
		CANE = "걷는 것을 훨씬 쉽게 만든다!",
		CARROT = "우엑. 다 야채인걸.",
		CARROT_COOKED = "물컹하다.",
		CARROT_PLANTED = "땅이 식물아기를 만들고 있다.",
		CARROT_SEEDS = "씨앗이다.",
		CAVE_FERN = "양치류다.",
		CHARCOAL = "작고, 어둡고, 탄 나무 냄새가 난다.",
        CHESSJUNK1 = "부서진 체스 말 더미.",
        CHESSJUNK2 = "또 다른 부서진 체스 말 더미.",
        CHESSJUNK3 = "더 많은 부서진 체스 말 더미.",
		CHESTER = "오토 폰 체스터필드 님",
		CHESTER_EYEBONE =
		{
			GENERIC = "나를 보고 있다.",
			WAITING = "잠들었다.",
		},
		COOKEDMANDRAKE = "불쌍한 놈.",
		COOKEDMEAT = "완벽하게 그을리고 구웠다.",
		COOKEDMONSTERMEAT = "날것이었을 때보다 조금만 더 맛있다.",
		COOKEDSMALLMEAT = "이제 기생충에 걸릴 걱정은 없다!",
		COOKPOT =
		{
			COOKING_LONG = "시간이 꽤 걸릴 것이다.",
			COOKING_SHORT = "거의 다 됐습니다!",
			DONE = "냠냠!먹을 준비가 되었다!",
			EMPTY = "보는 것만으로도 배고프다.",
		},
		CORN = "과당 함량이 높다!",
		CORN_COOKED = "과당 함량이 높다!",
		CORN_SEEDS = "씨앗이다.",
		CROW =
		{
			GENERIC = "소름 끼쳐!",
			HELD = "안에 있는 것이 행복해 보이지 않는다.",
		},
		CUTGRASS = "자른 풀은 공예 준비물.",
		CUTREEDS = "자른 갈대는 공작과 취미 생활에 쓸 수 있다.",
		CUTSTONE = "아주 반들반들하게 만들었다.",
		DEADLYFEAST = "가장 강력한 요리다.",
		DEERCLOPS = "거대해!!",
		DEERCLOPS_EYEBALL = "정말 징그럽다.",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불인 것 같다.",
		},
		DEVTOOL = "베이컨 냄새가 난다!",
		DEVTOOL_NODEV = "이것을 사용할 정도로 강하지 않다.",
		DIRTPILE = "흙더미이다... 인가?",
		DIVININGROD =
		{
			COLD = "신호가 미약하다.",
			GENERIC = "자동 유도 장치인 것 같다.",
			HOT = "광폭 상태다!",
			WARM = "올바른 방향으로 가고 있다.",
			WARMER = "가까워지는 것 같다.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "어떤 기능이 있을까.",
			READY = "큰 열쇠가 필요한 것 같다.",
			UNLOCKED = "이제 내 기계를 작동할 수 있다!",
		},
		DIVININGRODSTART = "저 막대가 유용해 보인다!",
		DRAGONFRUIT = "이상한 과일이다.",
		DRAGONFRUIT_COOKED = "그래도 이상하다.",
		DRAGONFRUIT_SEEDS = "씨앗이다.",
		DRAGONPIE = "내가 직접 요리했다!",
		DRUMSTICK = "게걸스럽게 먹어야겠다.",
		DRUMSTICK_COOKED = "이제 더 맛있다.",
		DUG_BERRYBUSH = "이를 심어야겠다.",
		DUG_GRASS = "이를 심어야겠다.",
		DUG_MARSH_BUSH = "이를 심어야겠다.",
		DUG_SAPLING = "이를 심어야겠다.",
		DURIAN = "냄새난다!",
		DURIAN_COOKED = "냄새가 더 고약해졌다!",
		DURIAN_SEEDS = "씨앗이다.",
		EARMUFFSHAT = "적어도 귀는 춥지 않겠지...",
		EGGPLANT = "알 같아 보이지 않는다.",
		EGGPLANT_COOKED = "더욱 더 알 같지 않다.",
		EGGPLANT_SEEDS = "씨앗이다.",
		EVERGREEN =
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "소나무스럽다.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "이 슬픈 나무는 방울이 없다.",
		},
		EYEPLANT = "누가 보고 있는 것 같다.",
		FARMPLOT =
		{
			GENERIC = "농작물을 심어야겠다.",
			GROWING = "열심히 자라라, 식물아!",
			NEEDSFERTILIZER = "비료가 필요한 것 같다.",
		},
		FEATHERHAT = "새가 됐다!",
		FEATHER_CROW = "까마귀 깃털.",
		FEATHER_ROBIN = "피리새 깃털.",
		FEATHER_ROBIN_WINTER = "흰머리멧새 깃털.",
		FEM_PUPPET = "잡혔다!",
		FIREFLIES =
		{
			GENERIC = "저걸 잡을 수만 있다면!",
			HELD = "내 주머니를 빛나게 한다!",
		},
		FIREHOUND = "저건 빛나고 있다.",
		FIREPIT =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "캄캄한 것보단 훨씬 좋다.",
			HIGH = "번지지 않을 테니 다행이다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "따뜻해서 좋다.",
			OUT = "적어도 다시 켤 수 있다.",
		},
		FIRESTAFF = "세상을 불지르고 싶진 않다.",

		FISH = "이제 하루 먹을 수 있다.",
		FISHINGROD = "바늘, 줄, 막대기!",
		FISHSTICKS = "내가 직접 요리했다!",
		FISHTACOS = "내가 직접 요리했다!",
		FISH_COOKED = "완벽하게 구웠다.",
		FLINT = "무척 날카로운 바위다.",
		FLOWER = "예쁘지만 흔한 일꾼 냄새가 난다.",
		FLOWERHAT = "예쁜 향이 난다.",
		FLOWER_EVIL = "으악!아주 사악하다!",
		FOLIAGE = "무성한 잎.",
		FOOTBALLHAT = "난 스포츠를 안 좋아해.",
		FROG =
		{
			DEAD = "꼴까닥 했구나.",
			GENERIC = "정말 귀엽다!",
			SLEEPING = "오호, 자는 것 봐!",
		},
		FROGGLEBUNWICH = "내가 직접 요리했다!",
		FROGLEGS = "진미라고 들었다.",
		FROGLEGS_COOKED = "닭고기 맛이다.",
		FRUITMEDLEY = "내가 직접 요리했다!",
		GEARS = "기계 부품 더미.",
		GHOST = "과학자에 대한 모욕이다.",
		GOLDENAXE = "고급스러운 도끼다.",
		GOLDENPICKAXE = "금은 연한 금속 아니었나?",
		GOLDENPITCHFORK = "내가 왜 이렇게 고급스러운 쇠스랑을 만들었을까?",
		GOLDENSHOVEL = "땅 파고 싶게 만든다.",
		GOLDNUGGET = "먹을 수는 없지만 광택이 대단하다.",
		GRASS =
		{
			BARREN = "똥이 필요해.",
			BURNING = "빨리 타고 있다!",
			GENERIC = "풀 덤불이다.",
			PICKED = "삶이 가장 창창할 때 잘렸다.",
		},
		GREEN_CAP = "꽤 평범해 보인다.",
		GREEN_CAP_COOKED = "지금은 다른데...",
		GREEN_MUSHROOM =
		{
			GENERIC = "버섯이다.",
			INGROUND = "자고 있다.",
			PICKED = "다시 돌아올까?",
		},
		GUNPOWDER = "후추처럼 보인다.",
		HAMBAT = "비위생적으로 보인다.",
		HAMMER = "멈춰!때가 왔다!망치 시간!",
		HEALINGSALVE = "따끔한 느낌은 효과가 있다는 표시다.",
		HEATROCK =
		{
			COLD = "참 차가운 돌이다.",
			GENERIC = "온도를 조절할 수 있을 것 같다.",
			HOT = "따끈따끈해서 좋다!",
			WARM = "따뜻해서 안고 싶다... 돌 치고는!",
		},
		HOME = "누군가 여기에 사는 것 같다.",
		HOMESIGN = "'너는 여기에 있다'고 써 있다.",
		HONEY = "맛있어 보인다!",
		HONEYCOMB = "여기에 벌들이 살았었다.",
		HONEYHAM = "내가 직접 요리했다!",
		HONEYNUGGETS = "내가 직접 요리했다!",
		HORN = "고기물소 들판인 것으로 들린다.",
		HOUND = "넌 아무 것도 아냐, 하운드 독!",
		HOUNDBONE = "소름 끼친다.",
		HOUNDMOUND = "뼈 가지고 주인과 싸우고 싶진 않다.",
		ICEBOX = "냉기의 힘을 끌어모았다!",
		ICEHOUND = "모든 계절에 어울리는 개가 있는 건가?",
		INSANITYROCK =
		{
			ACTIVE = "받아라, 멀쩡한 이성!",
			INACTIVE = "방첨탑이라기보다는 피라미드다.",
		},
		JAMMYPRESERVES = "내가 직접 요리했다!",
		KABOBS = "내가 직접 요리했다!",
		KILLERBEE =
		{
			GENERIC = "아니!살인벌이다!",
			HELD = "위험해 보인다.",
		},
		KNIGHT = "멋지다!",
		KOALEFANT_SUMMER = "귀여운 것이 맛도 좋다.",
		KOALEFANT_WINTER = "따뜻하고 고기가 가득 든 것 같다.",
		KRAMPUS = "내 것을 가져가려고 한다!",
		KRAMPUS_SACK = "우웩. 크램퍼스 점액이 뒤덮여있다.",
		LEIF = "거대하다!",
		LEIF_SPARSE = "거대하다!",
		LIGHTNING_ROD =
		{
			CHARGED = "힘은 나의 것!",
			GENERIC = "하늘의 힘을 쓸 수 있다!",
		},
		LITTLE_WALRUS = "영영 귀엽고 안아주고 싶은 상태로 남지 않겠지.",
		LIVINGLOG = "걱정스러워 보인다.",
		LOCKEDWES = "맥스웰의 조각상이 그를 가둬 두고 있다.",
		LOG =
		{
			BURNING = "뜨거운 나무다!",
			GENERIC = "크고, 무겁고, 나무다.",
		},
		LUREPLANT = "너무 유혹적이다.",
		LUREPLANTBULB = "이제 나만의 고기 농장을 시작할 수 있다.",
		MALE_PUPPET = "잡혔다!",
		MANDRAKE =
		{
			DEAD = "맨드레이크 뿌리는 이상한 힘을 가지고 있다.",
			GENERIC = "이 식물에 대한 이상한 이야기를 들었다.",
			PICKED = "날 따라오지 마!",
		},
		MANDRAKESOUP = "내가 직접 요리했다!",
		MANDRAKE_COOKED = "더는 이상해 보이지 않는다.",
		MARBLE = "멋지다!",
		MARBLEPILLAR = "쓸모 있을 것 같다.",
		MARBLETREE = "도끼로 자를 수 없을 것 같다.",
		MARSH_BUSH =
		{
			BURNING = "빨리 타고 있다!",
			GENERIC = "가시가 많아 보인다.",
			PICKED = "아파.",
		},
		MARSH_PLANT = "잡풀이다.",
		MARSH_TREE =
		{
			BURNING = "가시와 불!",
			BURNT = "이제 타고 뾰족한 것만 남았다.",
			CHOPPED = "더 이상 안 뾰족하다!",
			GENERIC = "가시가 뾰족해 보인다!",
		},
		MAXWELL = "저 놈이 싫다.",
		MAXWELLHEAD = "털구멍이 보인다.",
		MAXWELLLIGHT = "어떻게 작동하는 걸까.",
		MAXWELLLOCK = "열쇠 구멍으로 보인다.",
		MAXWELLTHRONE = "그리 편해 보이지 않는다.",
		MEAT = "질기지만 이게 어디냐.",
		MEATBALLS = "내가 직접 요리했다!",
		MEATRACK =
		{
			DONE = "육포 만들 시간!",
			DRYING = "고기는 건조하는 데 시간이 꽤 걸린다.",
			GENERIC = "고기를 말려야겠다.",
		},
		MEAT_DRIED = "딱 육포다.",
		MERM = "비린내 난다!",
		MERMHEAD = "오늘의 최악의 냄새.",
		MERMHOUSE = "누가 이런 끔찍한 곳에 살까?",
		MINERHAT = "손을 쓸 수 있게 해준다.",
		MONKEY = "호기심 많은 작은 놈.",
		MONKEYBARREL = "방금 움직였나?",
		MONSTERLASAGNA = "내가 직접 요리했다!",
		MONSTERMEAT = "윽. 저걸 먹어선 안 될 것 같다.",
		MONSTERMEAT_DRIED = "이상한 냄새가 나는 육포.",
		MOSQUITO =
		{
			GENERIC = "역겨운 조그만 흡혈 동물.",
			HELD = "야, 내 피냐?",
		},
		MOSQUITOSACK = "다른 사람의 피가 아니겠지...",
		MOUND =
		{
			DUG = "아마 죄책감을 느껴야 할 것 같지만.",
			GENERIC = "저 아래에 좋은 것이 많겠지!",
		},
		NIGHTLIGHT = "으스스한 빛을 발한다.",
		NIGHTMAREFUEL = "정말 괴상한 것이다!",
		NIGHTSWORD = "내 꿈에서 나온 것이다!",
		NITRE = "나는 지질학자가 아니다.",
		ONEMANBAND = "고기물소 벨을 달 걸 그랬다.",
		PANDORASCHEST = "굉장한 것이 들어있을 것 같다!아니면 끔찍한 것일까.",
		PANFLUTE = "동물을 위한 소야곡을 연주할 수 있다.",
		PAPYRUS = "종이 몇 장.",
		PENGUIN = "번식기인 것 같다.",
		PERD = "멍텅구리 새야!내 베리에서 멀찍이 떨어져!",
		PEROGIES = "내가 직접 요리했다!",
		PETALS = "꽃에게 본때를 보여줬다!",
		PETALS_EVIL = "이것을 들고 싶은 생각이 안 든다.",
		PICKAXE = "상징적이지 않나?",
		PIGGYBACK = "죄책감이 좀 느껴진다.",
		PIGHEAD = "짐승을 위한 제물이다.",
		PIGHOUSE =
		{
			FULL = "창문에 주둥이가 붙어 있는 것이 보인다.",
			GENERIC = "돼지들이 꽤 좋은 집을 가지고 있다.",
			LIGHTSOUT = "야!집에 있는 것 알고 있어!",
		},
		PIGKING = "으윽, 냄새 난다!",
		PIGMAN =
		{
			DEAD = "누군가 가족에게 소식을 전해야 할 텐데.",
			FOLLOWER = "내 측근이다.",
			GENERIC = "뭔가 소름 끼친다.",
			GUARD = "심각해 보인다.",
			WEREPIG = "우호적이지 않다!",
		},
		PIGSKIN = "아직도 꼬리가 달려있다.",
		PIGTENT = "베이컨 냄새가 난다.",
		PIGTORCH = "아주 포근해 보인다.",
		PINECONE = 
		{
		    GENERIC = "밖으로 나오고 싶어하는 작은 나무가 안에 있는 것이 들린다.",
		    PLANTED = "금방 나무가 되겠지!",
		},
		PITCHFORK = "맥스웰이 이것을 찾고 있을지도 모른다.",
		PLANTMEAT = "그리 맛있어 보이지 않는다.",
		PLANTMEAT_COOKED = "적어도 따뜻하긴 하다.",
		PLANT_NORMAL =
		{
			GENERIC = "무성하다!",
			GROWING = "윽!너무 느리게 성장한다!",
			READY = "흠. 수확 준비가 되었다.",
		},
		POMEGRANATE = "외계인의 뇌 안을 보는 것 같다.",
		POMEGRANATE_COOKED = "고급 요리!",
		POMEGRANATE_SEEDS = "씨앗이다.",
		POND = "밑바닥이 안 보인다!",
		POOP = "주머니를 채워야겠다!",
		PUMPKIN = "내 머리만큼 크다!",
		PUMPKINCOOKIE = "내가 직접 요리했다!",
		PUMPKIN_COOKED = "왜 파이가 되지 않았지?",
		PUMPKIN_LANTERN = "으스스해!",
		PUMPKIN_SEEDS = "씨앗이다.",
		PURPLEAMULET = "나에게 속삭이고 있다.",
		PURPLEGEM = "우주의 신비를 담고 있다.",
		RABBIT =
		{
			GENERIC = "당근을 찾고 있다.",
			HELD = "과학을 좋아하나요?",
		},
		RABBITHOLE = "버니맨 왕국으로 이어지는 것 같다.",
		RAINOMETER = "구름 낀 정도를 측정한다.",
		RATATOUILLE = "내가 직접 요리했다!",
		RAZOR = "막대기에 달린 날카롭게 만든 돌. 위생적이다!",
		REDGEM = "내적인 따뜻함으로 반짝인다.",
		RED_CAP = "냄새가 요상하다.",
		RED_CAP_COOKED = "지금은 다른데...",
		RED_MUSHROOM =
		{
			GENERIC = "버섯이다.",
			INGROUND = "자고 있다.",
			PICKED = "다시 돌아올까?",
		},
		REEDS =
		{
			BURNING = "제대로 타고 있다!",
			GENERIC = "갈대 덤불이다.",
			PICKED = "쓸모 있는 갈대는 다 뽑았다.",
		},
        RELIC = 
        {
            GENERIC = "고대 가재 도구.",
            BROKEN = "여기에는 쓸모 있는 것이 없다.",
        },
        RUINS_RUBBLE = "수리할 수 있겠다.",
        RUBBLE = "돌 조각일 뿐이다.",
		RESEARCHLAB = "물체를 과학 구성품으로 해체한다.",
		RESEARCHLAB2 = "저번 것보다 더 과학적이다!",
		RESEARCHLAB3 = "내가 무엇을 창조했는가?",
		RESURRECTIONSTATUE = "미남 악마구나!",
		RESURRECTIONSTONE = "참 이상하게 생긴 돌이다.",
		ROBIN =
		{
			GENERIC = "겨울이 끝났다는 의미인가?",
			HELD = "내 주머니를 좋아한다.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "언 황무지의 삶.",
			HELD = "무척 부드럽다.",
		},
		ROBOT_PUPPET = "잡혔다!",
		ROCK_LIGHT =
		{
			GENERIC = "위가 딱딱해진 용암 구덩이.",
			OUT = "부서지기 쉬워 보인다.",
			LOW = "용암 위쪽이 딱딱해지고 있다.",
			NORMAL = "따뜻해서 좋다.",
		},
		ROCK = "주머니 안에 들어가지 않는다.",
		ROCKS = "이것으로 물건을 만들 수 있다.",
        ROOK = "성을 공격하라!",
		ROPE = "짧은 밧줄.",
		ROTTENEGG = "우욱!악취가 난다!",
		SANITYROCK =
		{
			ACTIVE = "미치광이 바위다!",
			INACTIVE = "나머지는 어디로 갔지?",
		},
		SAPLING =
		{
			BURNING = "빨리 타고 있다!",
			GENERIC = "아기 나무는 너무 귀여워!",
			PICKED = "따끔한 맛을 봐라.",
		},
		SEEDS = "하나하나가 작은 수수께끼다.",
		SEEDS_COOKED = "요리해서 생명을 다 없앴다!",
		SEWING_KIT = "꿰매자!다 꿰매 버리자!",
		SHOVEL = "지하에 뭔가 많이 이루어지고 있다.",
		SILK = "거미 엉덩이에서 나오는 것.",
		SKELETON = "나보단 남이 당하는 것이 낫지.",
		SKULLCHEST = "열고 싶은 생각이 안 든다.",
		SMALLBIRD =
		{
			GENERIC = "꽤 작은 새다.",
			HUNGRY = "배고파 보인다.",
			STARVING = "굶주린 모양이다.",
		},
		SMALLMEAT = "죽은 동물의 작은 조각.",
		SMALLMEAT_DRIED = "작은 육포.",
		SPEAR = "아주 뾰족한 막대기.",
		SPIDER =
		{
			DEAD = "으윽!",
			GENERIC = "거미가 싫다.",
			SLEEPING = "깨어날 때 여기에 있으면 안 되겠다.",
		},
		SPIDERDEN = "들러붙는다!",
		SPIDEREGGSACK = "주머니 안에서 부화하지 않길 바란다.",
		SPIDERGLAND = "톡 쏘는 소독제 냄새가 난다.",
		SPIDERHAT = "거미 점액을 다 닦아냈어야 할 텐데.",
		SPIDERQUEEN = "으악!정말 큰 거미다!",
		SPIDER_WARRIOR =
		{
			DEAD = "시원하게 없앴다!",
			GENERIC = "평소보다 더 못되어 보인다.",
			SLEEPING = "거리를 두어야겠다.",
		},
		SPOILED_FOOD = "복슬복슬하고 둥근 썩은 음식.",
		STATUEHARP = "머리는 어떻게 되었지?",
		STATUEMAXWELL = "특성을 잘 포착했다.",
		STINGER = "날카로워 보인다!",
		STRAWHAT = "아주 좋은 모자다.",
		STUFFEDEGGPLANT = "내가 직접 요리했다!",
		SUNKBOAT = "거기에 있으면 나에게 쓸모없지!",
		SWEATERVEST = "이 조끼는 말쑥한 외투다.",
		TAFFY = "내가 직접 요리했다!",
		TALLBIRD = "큰 새다!",
		TALLBIRDEGG = "부화할까?",
		TALLBIRDEGG_COOKED = "맛있고 영양가 있다.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "부르르!",
			GENERIC = "부화하는 것 같다.",
			HOT = "알이 땀 흘려도 되는 건가?",
			LONG = "시간이 좀 걸릴 것 같은데...",
			SHORT = "금방 부화하겠지.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "대단한 알이다!",
			PICKED = "둥지가 비어있다.",
		},
		TEENBIRD =
		{
			GENERIC = "아주 큰 새가 아니다.",
			HUNGRY = "식량을 찾아야겠다.",
			STARVING = "위험한 눈초리다.",
		},
		TELEBASE =
		{
			VALID = "준비 됐다.",
			GEMS = "자주색 보석이 더 필요하다.",
		},
		GEMSOCKET = 
		{
			VALID = "준비된 것 같다.",
			GEMS = "보석이 필요해.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "이것으로 시간과 공간을 통과할 수 있을 거야!",
			GENERIC = "다른 세계로 가는 연결 고리인 것 같다!",
			LOCKED = "아직도 빠진 것이 있다.",
			PARTIAL = "내 발명이 곧 완성될 것이다!",
		},
		TELEPORTATO_BOX = "우주 전체의 극성을 제어할 수 있을 것 같다.",
		TELEPORTATO_CRANK = "극심한 실험도 견딜 정도로 단단하다.",
		TELEPORTATO_POTATO = "이 금속 감자는 위대하고 무시무시한 능력을 가지고 있다...",
		TELEPORTATO_RING = "차원 에너지를 집중할 수 있는 고리.",
		TELESTAFF = "나에게 세계를 보여줄 수 있다.",
		TENT = "잠 안 자면 미칠 것 같다.",
		TENTACLE = "위험해 보인다.",
		TENTACLESPIKE = "뾰족하고 점액투성이인걸.",
		TENTACLESPOTS = "이게 생식기였던 것 같다.",
		TENTACLE_PILLAR = "미끈덩한 기둥.",
		TENTACLE_PILLAR_ARM = "미끌거리는 작은 팔.",
		TENTACLE_GARDEN = "또 다른 미끈덩한 기둥.",
		TOPHAT = "아주 좋은 모자다.",
		TORCH = "밤의 엄습을 막아내는 것.",
		TRAP = "정말 촘촘하게 짰다.",
		TRAP_TEETH = "더러운 깜짝선물이다.",
		TRAP_TEETH_MAXWELL = "이 것을 밟지 말아야지!",
		TREASURECHEST = "나의 기분 좋은 상자!",
		TREASURECHEST_TRAP = "대단히 편리하다!",
		TREECLUMP = "다른 곳에 가는 걸 누가 막고 있는 것만 같다.",
		TRINKET_1 = "다 함께 녹여져 있다.",
		TRINKET_10 = "이것이 필요해지기 전까지 여기에서 나가고 싶다.",
		TRINKET_11 = "나에게 아름다운 거짓말을 속삭인다.",
		TRINKET_12 = "마른 촉수로 뭘 해야 할지 모르겠다.",
		TRINKET_2 = "싸구려 복제품일 뿐이다.",
		TRINKET_3 = "매듭이 박혀있다. 영원히.",
		TRINKET_4 = "종교적 유물인 것 같다.",
		TRINKET_5 = "안타깝지만 내가 타고 탈출하기엔 너무 작다.",
		TRINKET_6 = "더 이상 전력을 가지고 있지는 않다.",
		TRINKET_7 = "장난치고 놀 시간 없다!",
		TRINKET_8 = "훌륭해. 이제 욕조를 막을 수 있겠어.",
		TRINKET_9 = "나는 지퍼를 선호한다.",
		TRUNKVEST_SUMMER = "야생의 캐주얼 패션.",
		TRUNKVEST_WINTER = "겨울 생존 장비.",
		TRUNK_COOKED = "전보다 더 코 같다.",
		TRUNK_SUMMER = "가볍고 시원한 트렁크.",
		TRUNK_WINTER = "두껍고 털 많은 트렁크.",
		TURF_CARPETFLOOR = "은근히 긁힌다.",
		TURF_CHECKERFLOOR = "꽤 근사하다.",
		TURF_DIRT = "땅덩이.",
		TURF_FOREST = "땅덩이.",
		TURF_GRASS = "땅덩이.",
		TURF_MARSH = "땅덩이.",
		TURF_ROAD = "급하게 깐 자갈.",
		TURF_ROCKY = "땅덩이.",
		TURF_SAVANNA = "땅덩이.",
		TURF_WOODFLOOR = "바닥 널이다.",
		TURKEYDINNER = "흠.",
		TWIGS = "잔가지 다발이다.",
		UMBRELLA = "적어도 머리카락은 젖지 않게 해주겠지.",
		UNIMPLEMENTED = "완성된 것 같지 않다!위험할지도 모르겠다.",
		WAFFLES = "내가 직접 요리했다!",
		WALL_HAY = "흐음. 이것으로 만족할 수 밖에.",
		WALL_HAY_ITEM = "안 좋은 아이디어 같다.",
		WALL_STONE = "좋은 벽이다.",
		WALL_STONE_ITEM = "아주 안전한 느낌을 준다.",
		WALL_RUINS = "고대의 벽 조각.",
		WALL_RUINS_ITEM = "역사의 단단한 조각.",
		WALL_WOOD = "뾰족하다!",
		WALL_WOOD_ITEM = "울타리!",
		WALRUS = "바다코끼리는 자연의 포식자다.",
		WALRUSHAT = "바다코끼리 털로 덮여있다.",
		WALRUS_CAMP =
		{
			EMPTY = "누군가 여기에서 야영했던 것 같다.",
			GENERIC = "안은 따뜻하고 편안한 것으로 보인다.",
		},
		WALRUS_TUSK = "용도를 찾을 수 있겠지.",
		WASPHIVE = "벌이 화난 것 같다.",
		WETGOOP = "내가 직접 요리했다!",
		WINTERHAT = "겨울에 유용하겠다.",
		WINTEROMETER = "난 정말 대단한 과학자다.",
		WORMHOLE =
		{
			GENERIC = "보드랍고 굽이친다.",
			OPEN = "과학 때문에 뛰어들고 싶다.",
		},
		WORMHOLE_LIMITED = "평소보다 안 좋아 보인다.",
		ACCOMPLISHMENT_SHRINE = "내가 쓰고 싶고, 세계에 내가 한 일을 알리고 싶다.",        
		LIVINGTREE = "날 보고 있는 것일까?",
		ICESTAFF = "촉감이 차갑다.",
	},
	DESCRIBE_GENERIC = "흠... 물건.",
	DESCRIBE_TOODARK = "너무 어두워서 안 보인다!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "으음. 부리.",
	},
}
