return {
	ANNOUNCE_ADVENTUREFAIL = "這次你贏了，麥斯威爾。",
	ANNOUNCE_BOOMERANG = "愚蠢的迴旋鏢！",
	ANNOUNCE_CHARLIE = "我不怕你！",
	ANNOUNCE_CHARLIE_ATTACK = "哎喲！你混蛋！",
	ANNOUNCE_COLD = "好冷！像冰火在燃燒！",
	ANNOUNCE_DUSK = "夜晚就要來了。我需要火！",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "呃！太難受了！",
		SPOILED = "太難吃了！",
		STALE = "吃起來有點噁心。",
	},
	ANNOUNCE_HOUNDS = "現身吧！",
	ANNOUNCE_HUNGRY = "我需要食物！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我會找到你的！",
	ANNOUNCE_HUNT_LOST_TRAIL = "噢...他消失了。",
	ANNOUNCE_ACCOMPLISHMENT= "轉動吧，箭頭！轉動吧！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "搞定！",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "嘻嘻！",
		[2] = "漂亮！",
		[3] = "哎呀！",
		[4] = "我放了一把火！",
		[5] = "燒吧！",
		[6] = "我忍不住！",
	},
	ANNOUNCE_PECKED = "不要！你這只壞鳥！",
	ANNOUNCE_TORCH_OUT = "我寶貴的光消失了！",
	ANNOUNCE_WORMHOLE = "我要把這些衣服全燒掉！",
	ANNOUNCE_TRAP_WENT_OFF = "啊！",
    ANNOUNCE_CRAFTING_FAIL = "我肯定是漏掉了什麼東西。",
    ANNOUNCE_QUAKE = "那個聲音聽起來不像是好事。",
    ANNOUNCE_NODANGERSLEEP = "沒時間睡覺，我必須得戰鬥！",
    ANNOUNCE_NOHUNGERSLEEP = "肚子餓得咕咕叫，睡不著！",
    ANNOUNCE_FREEDOM = "我自由了！該放火慶祝一下！",
    ANNOUNCE_RESEARCH = "這很有用，即使它跟火扯不上一點關係。",
    ANNOUNCE_NO_TRAP = "就像放火燒水桶裡的魚一樣白費力氣。",
    ANNOUNCE_HIGHRESEARCH = "好多資訊！",
    ANNOUNCE_THORNS = "哎喲！",
    ANNOUNCE_NODAYSLEEP_CAVE = "在這下面睡覺太恐怖了。",
    ANNOUNCE_BEES = "啊啊啊啊！螫人的蟲子！",
    ANNOUNCE_KNOCKEDOUT = "啊啊，我的小腦袋！",
    ANNOUNCE_LOWRESEARCH = "切，太無聊了。",
    ANNOUNCE_DEERCLOPS = "聽起來有一個怪物一樣的兇惡巨人走過來了！",
    ANNOUNCE_MOSQUITOS = "滾開，你這個吸血的混蛋！",
    ANNOUNCE_NODAYSLEEP = "當天空掛著一個大火球時，我是不會進裡面睡覺的。",
	ANNOUNCE_CANFIX = "\n我覺得我能修好這個！",
	BATTLECRY =
	{
		GENERIC = "不是你死，就是我活！",
		PIG = "蠢豬！",
		PREY = "放馬過來！",
		SPIDER = "咿咿咿咿呀！",
		SPIDER_WARRIOR = "呃，殺殺殺了它！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "不出我所料！",
		PIG = "給我回來，豬排！",
		PREY = "下次我再來收拾你！",
		SPIDER = "切， 下次我再幹掉他。",
		SPIDER_WARRIOR = "現在沒那麼強硬了！",
	},
	DESCRIBE =
	{
		WORMLIGHT = "沒有火卻能發光。太不正常了。",
		WORM =
		{
		    PLANT = "沒有火卻能發光。太不正常了。",
		    DIRT = "泥土通常會動嗎？",
		    WORM = "它身上長了好多毛！",
		},
		EEL = "我不喜歡它的表情！",
		EEL_COOKED = "有了火，一切都變好了。",
		UNAGI = "我做的。",
		EYETURRET = "我希望它能讓東西點燃。",
		EYETURRET_ITEM = "等我把它放好，它才能發揮作用。",
		MINOTAURHORN = "不知道這些圈圈是否代表年齡。",
		MINOTAURCHEST = "我想要那樣的大角！",
		THULECITE_PIECES = "這塊銩礦已經成了碎片。",
		POND = "這片池塘肯定燒不起來。太無趣了。",
		POND_ALGAE = "它肯定需要大量的水。",
		GREENSTAFF = "雖然它無法用來生火，但我猜它還是很有用。",
		POTTEDFERN = "我寧願燒掉它們。",

		THULECITE = "我覺得它應該不會燃燒。",
		ARMORRUINS = "我不確定要不要穿這個。",
		RUINS_BAT = "這可以讓那些壞蛋不敢靠近我。",
		RUINSHAT = "似乎有什麼東西在其中流動。",
		NIGHTMARE_TIMEPIECE = 
		{
		CALM = "感覺沒什麼異常。",	
		WARN = "它在警告我。",	
		WAXING = "魔法能量甦醒了！", 
		STEADY = "它幾乎在嗡嗡作響。", 
		WANING = "魔法能量正在平靜下來。", 
		DAWN = "我猜一切快結束了。", 
		NOMAGIC = "它好像停止工作了。", 
		},
		BISHOP_NIGHTMARE = "啊——！",
		ROOK_NIGHTMARE = "它的笑容很猥瑣。",
		KNIGHT_NIGHTMARE = "它看上去很破舊。",
		MINOTAUR = "可憐的傢伙。被困在了這個迷宮裡。",	
		SPIDER_DROPPER = "它們是從上面下來的。",	
		NIGHTMARELIGHT = "不用火就可以照明實在是不正常。",	
		GREENGEM = "這個寶石感覺真的好亮。",
		RELIC = "我猜先前有人住在这里。",	
		RUINS_RUBBLE = "也許我可以把它修好。",	
		MULTITOOL_AXE_PICKAXE = "這東西太有用了！",	
		ORANGESTAFF = "它讓我頭疼。",	
		YELLOWAMULET = "它似乎能夠把周圍的黑暗都吸進去。",	
		GREENAMULET = "戴著它我感覺自己的思維都開闊了。",	

		SLURPER = "它們肚子裡有火嗎？",
		SLURPER_PELT = "咦，它還是活的！",
		ARMORSLURPER = "呃，呸！呸！呸！呸！真噁心！",
		ORANGEAMULET = "它在幫我撿燃料！",
		YELLOWSTAFF = "太神奇了。",
		YELLOWGEM = "它在閃閃發光。",
		ORANGEGEM = "這東西刺痛我的手指了。",
		TELEBASE = 
		{
			VALID = "我可以感覺到魔力的存在！",
			GEMS = "它還需要一些東西。",
		},
		GEMSOCKET = 
		{
			VALID = "它們究竟是如何浮在空中的？",
			GEMS = "上面是空的！",
		},
		STAFFLIGHT = "太漂亮了！",
		RESEARCHLAB4 = "我可以把那個帽子當作巫師施符咒的大鍋！",

        LIGHTER = "它是我的幸運打火機！",


        ANCIENT_ALTAR =
        {
        	WORKING = "哇！與來世相通。",
        	BROKEN = "死靈無法從這裡出去。",
        },  
        ANCIENT_ALTAR_BROKEN = "死靈無法從這裡出去。",

        ANCIENT_STATUE = "該死，又不會燃燒。",

        LICHEN = "一種有脆皮的植物",
		CUTLICHEN = "呸，一股鋸屑的味道。",

        CAVE_BANANA = "香蕉！",
        CAVE_BANANA_COOKED = "好吃！",
        CAVE_BANANA_TREE = "看起來可以燃燒！",
        ROCKY = "我們可沒有多少共同點。",

        BLUEAMULET = "切。",
		PURPLEAMULET = "這科技是不是有點走偏了？",
		TELESTAFF = "它用起來就像一陣風。",
		MINERHAT = "雖然不是真正的火光，但還是很有趣。",
		MONKEY = "開個玩笑！我可以點燃這坨便便。",
		MONKEYBARREL = "多麼棒的家，一下子就能燒起來。",

		HOUNDSTOOTH="好鋒利。我喜歡！",
		ARMORSNURTLESHELL="更少防守！更多進攻！",
		BAT="可愛的小傢伙！",
		BATBAT = "我可以用它來對付敵人。",
		BATWING="呸！",
		BATWING_COOKED="呸！",
		BEDROLL_FURRY="褶邊太多了。",
		BUNNYMAN="呃。它們看起來好蠢。",
		FLOWER_CAVE="它裡面在燃燒。",
		FLOWER_CAVE_DOUBLE="它裡面在燃燒。",
		FLOWER_CAVE_TRIPLE="它裡面在燃燒。",
		GUANO="它燒起來和普通糞便沒什麼區別。",
		LANTERN="烈火不應該受到這樣的束縛！",
		LIGHTBULB="真亮！",
		MANRABBIT_TAIL="我吵贏了。",
		MUSHTREE_TALL="噁心。這棵樹已經病入膏肓了。",
		MUSHTREE_MEDIUM="噁心。聞起來像小妖精的屁股",
		MUSHTREE_SMALL="噁心。它從頭到尾都像蘑菇。",
		RABBITHOUSE="呃。愚蠢的兔子。",
		SLURTLE="我想要把它炸飛！",
		SLURTLE_SHELLPIECES="呵呵。它碎了。",
		SLURTLEHAT="很適合我的腦袋。",
		SLURTLEHOLE="我應該把它們都燒掉。",
		SLURTLESLIME="我愛死這玩意兒了！",
		SNURTLE="砰！",
		SPIDER_HIDER="真是個難搞的傢伙！",
		SPIDER_SPITTER="放馬過來！",
		SPIDERHOLE="裡面全是蜘蛛。",
		STALAGMITE="石頭真無趣。",
		STALAGMITE_FULL="石頭真無趣。",
		STALAGMITE_LOW="石頭真無趣。",
		STALAGMITE_MED="石頭真無趣。",
		STALAGMITE_TALL="又是無趣的岩石。",
		STALAGMITE_TALL_FULL="又是無趣的岩石。",
		STALAGMITE_TALL_LOW="又是無趣的岩石。",
		STALAGMITE_TALL_MED="又是無趣的岩石。",

		TURF_CARPETFLOOR = "地面太沒意思了。",
		TURF_CHECKERFLOOR = "地面太沒意思了。",
		TURF_DIRT = "地面太沒意思了。",
		TURF_FOREST = "地面太沒意思了。",
		TURF_GRASS = "地面太沒意思了。",
		TURF_MARSH = "地面太沒意思了。",
		TURF_ROAD = "地面太沒意思了。",
		TURF_ROCKY = "地面太沒意思了。",
		TURF_SAVANNA = "地面太沒意思了。",
		TURF_WOODFLOOR = "地面太沒意思了。",

		TURF_CAVE="地面太沒意思了。",
		TURF_FUNGUS="地面太沒意思了。",
		TURF_SINKHOLE="地面太沒意思了。",
		TURF_UNDERROCK="地面太沒意思了。",
		TURF_MUD="地面太沒意思了。",
		
		TURKEYDINNER = "一場烤鳥盛宴！",
		TWIGS = "一堆小樹枝。和其他東西一樣，也是很好的燃料。",
		POWCAKE = "我想知道它能不能燃燒。",
        CAVE_ENTRANCE = 
        {
            GENERIC="誰把那個洞給堵上的？",
            OPEN = "我希望下面某個地方會有熔岩。",
        },
        CAVE_EXIT = "這下面又黑又悶。",

		MAXWELLPHONOGRAPH = "我喜歡更刺激的音樂。",
		PIGGUARD = "我喜歡他的態度！",
		BOOMERANG = "它不是最讓人興奮的武器。",
		ADVENTURE_PORTAL = "也許那是回家的路。",
		AMULET = "我是無敵的！好吧，或許不是。但這樣感覺不錯。",
		ANIMAL_TRACK = "它會引導我找到新朋友。",
		ARMORGRASS = "浪費這麼多易燃材料。",
		ARMORMARBLE = "如果我要去戰鬥，最好先做好保護工作。",
		ARMORWOOD = "現在，我可以挑戰整個世界了！",
		ARMOR_SANITY = "像被包裹在煙霧裡一樣。",
		ASH =
		{
			GENERIC = "燒完後剩下的東西。真希望火還沒滅。",
			REMAINS_EYE_BONE = "我猜這個長著眼睛的東西燃燒起來肯定相當壯觀！",
			REMAINS_THINGIE = "不管這東西是什麼，我都希望它能繼續燃燒。",
		},
		AXE = "它非常鋒利。",
		BABYBEEFALO =
		{
			GENERIC = "即使是犛牛寶寶，看上去也很醜。",
			SLEEPING = "醒醒！",
		},
		BACKPACK = "我可以往裡面裝比如說一百萬個打火機。",
		BACONEGGS = "溏心蛋黃部分有點噁心，但是培根非常美味！",
		BANDAGE = "呃，一定要這麼做嗎？",
		BASALT = "太難鑿碎了！",
		BEARDHAIR = "呃，這東西從哪兒來的？",
		BEDROLL_STRAW = "一股霉臭味。",
		BEE =
		{
			GENERIC = "很肥的蜜蜂，不過它的刺看起來很危險。",
			HELD = "滿袋子的蜜蜂！",
		},
		BEEBOX =
		{
			GENERIC = "趕緊的，肥蜜蜂，趕緊給我產蜂蜜！",
			READY = "耶！我可以偷蜂蜜囉！",
		},
		BEEFALO =
		{
			FOLLOWER = "呃，你在跟著我嗎？",
			GENERIC = "多麼噁心的長毛野獸！",
			NAKED = "哈！他身上一根毛也沒有了！",
			SLEEPING = "它們睡著的時候樣子更傻。",
		},
		BEEFALOHAT = "我剃了他的毛，做成帽子戴在自己的頭髮上！",
		BEEFALOWOOL = "哈！我偷了他的毛！",
		BEEHIVE = "裡面全是蜜蜂！",
		BEEMINE = "裡面有蜜蜂。應該再往那裡放點火。",
		BEEMINE_MAXWELL = "裡面有蚊子。它們聽起來可不太高興。",
		BEEHAT = "這可以防止那些螫人的蜜蜂接近我。",
		BERRIES = "紅色漿果最好吃。",
		BERRIES_COOKED = "烤過之後的紅色漿果味道更好。",
		BERRYBUSH =
		{
			BARREN = "吃屎吧，愚蠢的植物！",
			GENERIC = "嗯。漿果。",
			PICKED = "我想要更多的漿果！",
		},
		BIRDCAGE =
		{
			GENERIC = "鳥的牢籠！",
			OCCUPIED = "哈！你是我的了！",
			SLEEPING = "蠢鳥。醒醒！",
		},
		BIRDTRAP = "我會抓住那些臭鳥的。",
		BIRD_EGG = "聞起來像鳥屁股一樣。",
		BIRD_EGG_COOKED = "呸。黃色的部分還沒凝固。",
		BISHOP = "是主教！",
		BLOWDART_FIRE = "這是全世界我最喜歡的東西。",
		BLOWDART_SLEEP = "催眠吹箭可以更方便我點火。",
		BLOWDART_PIPE = "練好這個，給火吹風就不費勁了。",
		BLUEGEM = "呃。這玩意兒好醜。",
		BLUEPRINT = "這可以省去一些實驗。",
		BLUE_CAP = "一股運動後的臭襪子的味道！",
		BLUE_CAP_COOKED = "我用火改變了它！",
		BLUE_MUSHROOM =
		{
			GENERIC = "愚蠢的蘑菇。",
			INGROUND = "嘿！你！給我起來！",
			PICKED = "也許有一天它會再長回來。",
		},
		BOARDS = "木板。它們也會燃燒，就和其他木材一樣。",
		BONESTEW = "只需要給食物加把火，瞧！",
		BUGNET = "我能抓到蟲子！",
		BUSHHAT = "太被動了！",
		BUTTER = "很美味，只是有點昆蟲的味道",
		BUTTERFLY =
		{
			GENERIC = "飛走吧，蝴蝶！",
			HELD = "我想捏它。",
		},
		BUTTERFLYMUFFIN = "嘻嘻，看起來像蝴蝶被困在瑪芬裡面一樣。",
		BUTTERFLYWINGS = "那隻蝴蝶不會再飛了！",
		CAMPFIRE =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "我喜歡火。",
			HIGH = "燒吧！燒得再旺點！",
			LOW = "火太小了，真無聊。",
			NORMAL = "燒吧！",
			OUT = "嗚嗚嗚。一切都結束了。",
		},
		CANE = "有了這個，走起路來容易多了！",
		CARROT = "呸。全是蔬菜。",
		CARROT_COOKED = "雖然還是一股蔬菜味，但經火烤過的味道要好些。",
		CARROT_PLANTED = "也許地下有它特別的胡蘿蔔朋友。",
		CARROT_SEEDS = "難吃的橙色蔬菜的種子。",
		CAVE_FERN = "看上去可以燃燒。",
		CHARCOAL = "嗯。火的味道。",
        CHESSJUNK1 = "上發條的馬，已經死了",
        CHESSJUNK2 = "死去的發條主教",
        CHESSJUNK3 = "上發條的城堡，已經死了",
		CHESTER = "他毛茸茸的！",
		CHESTER_EYEBONE =
		{
			GENERIC = "盯著人看是很沒禮貌的。",
			WAITING = "至少它不再盯著我了。",
		},
		COOKEDMEAT = "我吃過更好吃的。",
		COOKEDMONSTERMEAT = "還是很噁心。",
		COOKEDSMALLMEAT = "如果我想活下來的話，光開胃菜可是不夠的。",
		CORN = "甜甜的蔬菜，好吃！",
		CORN_COOKED = "哦，這東西丟進火裡會爆！",
		CORN_SEEDS = "玉米種子，會爆炸的玉米可是我最愛的蔬菜了。",
		CROW =
		{
			GENERIC = "我猜它是在等我死掉。",
			HELD = "聰明不起來了，對嗎？",
		},
		CUTGRASS = "乾草是很好的燃料， 也可以用來合成其他東西。",
		CUTREEDS = "採下的蘆葦是很好的燃料。也可以用來合成其他東西。",
		CUTSTONE = "完全是四四方方的，看著真舒服。",
		DEADLYFEAST = "連火也治不了這盤菜的卑鄙本性。",
		DEERCLOPS = "哇靠！",
		DEERCLOPS_EYEBALL = "不准再盯著我！",
		DIRTPILE = "是誰走的時候在森林裡留下了這一堆泥土？",
		DIVININGROD =
		{
			COLD = "它在發出某種噪聲。",
			GENERIC = "它全身上下都是電子垃圾。",
			HOT = "討厭！別再嗶嗶嗶地叫了！",
			WARM = "這東西越來越吵了。",
			WARMER = "一定很近了！",
		},
		DIVININGRODBASE =
		{
			GENERIC = "不知道這是用來幹嘛的。看起來不像是能夠燃燒的東西。",
			READY = "只需要用鑰匙解鎖就可以了。很遺憾，不是用火來解鎖。",
			UNLOCKED = "它在發出呼呼的聲音！",
		},
		DIVININGRODSTART = "我要用它搞點名堂出來。",
		DRAGONFRUIT = "它看上去有幾分像火！",
		DRAGONFRUIT_COOKED = "現在看起來更像是把水果放在烈火中一樣。",
		DRAGONFRUIT_SEEDS = "那個看起來像火一樣的水果的種子。",
		DRAGONPIE = "做成派的火龍果？我的乖乖！",
		DRUMSTICK = "整天都在砰砰砰擊鼓！",
		DRUMSTICK_COOKED = "我是用它來填飽肚子呢還是用它來敲鼓？",
		DURIAN = "呃，好臭！",
		DURIAN_COOKED = "呸，聞起來就像是東西煮壞了一樣！",
		DURIAN_SEEDS = "臭水果的臭種子。",
		EARMUFFSHAT = "聞上去像是兔子的屁股。",
		EGGPLANT = "絕對不是鳥。",
		EGGPLANT_COOKED = "火讓茄子變得更美味了。",
		EGGPLANT_SEEDS = "這些種子會長成一株植物還是一隻小鳥？",
		STUFFEDEGGPLANT = "它仍然不是鳥，不過我在它裡面塞了東西，現在看起來就像一隻鳥！",
		DUG_BERRYBUSH = "怎麼了，沒有土了嗎？",
		DUG_GRASS = "怎麼了，沒有土了嗎？",
		DUG_MARSH_BUSH = "怎麼了，沒有土了嗎？",
		DUG_SAPLING = "怎麼了，沒有土了嗎？",
		EARMUFFS = "聞上去像是兔子的屁股。",
		EVERGREEN =
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "世上又少了一棵樹。",
			GENERIC = "看起來它會燒得很旺。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "世上又少了一棵樹。",
			GENERIC = "在火中結束吧！",
		},
		EYEPLANT = "它們像火一樣迅速擴散。",
		FARMPLOT =
		{
			GENERIC = "唉， 這是一堆土。",
			GROWING = "加把勁，土堆。給我提供食物！",
			NEEDSFERTILIZER = "蠢東西又需要施肥了。",
		},
		FEATHERHAT = "我就是涅槃的鳳凰！",
		FEATHER_CROW = "烏鴉羽毛。它燃燒起來也許很難聞。",
		FEATHER_ROBIN = "紅雀羽毛。它燃燒起來也許很難聞。",
		FEATHER_ROBIN_WINTER = "雪雀羽毛。它燃燒起來也許很難聞。",
		FEM_PUPPET = "她看起來已經被嚇得半死。",
		FIREFLIES =
		{
			GENERIC = "真希望它們沒有跑掉！",
			HELD = "它們就像是裝在我口袋裡的小火苗！",
		},
		FIREHOUND = "實際上我還挺喜歡這傢伙的。",
		FIREPIT =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "我可以幾個小時一直盯著它看。",
			HIGH = "燒吧！燒得再旺點！",
			LOW = "火太小了，真無聊。",
			NORMAL = "燒吧！",
			OUT = "我應該重新把火點燃。",
		},
		FIRESTAFF = "這絕對是我最喜愛的玩具。",
		FISH = "滑不溜秋的魚！",
		FISHINGROD = "用釣魚線和墜子來釣魚。",
		FISHSTICKS = "所見即所得。瞧，炸魚排。",
		FISHTACOS = "真是方便好拿的魚肉玉米卷。",
		FISH_COOKED = "烤過之後的魚沒之前那麼滑溜溜了。",
		FLINT = "可憐人的打火石。",
		FLOWER = "我可沒有時間浪費在花朵上。",
		FLOWERHAT = "花環。可惜不是正在燃燒的花環。",
		FLOWER_EVIL = "呃，太難聞了。",
		FOLIAGE = "不錯的燃料。",
		FOOTBALLHAT = "運動可不是那麼容易。",
		FROG =
		{
			DEAD = "我讓他嚐到我的厲害了！",
			GENERIC = "他太潮濕了，燒不起來。",
			SLEEPING = "他們睡著的時候好可愛。",
		},
		FROGGLEBUNWICH = "也許我不會注意到三明治裡面夾的是青蛙腿。",
		FROGLEGS = "它時不時的還在抽搐。太奇怪了。",
		FROGLEGS_COOKED = "是火讓它停止抽搐的。火最好了。",
		FRUITMEDLEY = "好吃的水果！",
		GEARS = "這些會讓它們動起來的。",
		GHOST = "我無法殺死一個本來就已經死了的人。",
		GOLDENAXE = "雖然它無法讓樹著火，但至少它會閃閃發光。",
		GOLDENPICKAXE = "雖然它無法讓石頭著火，但至少它會閃閃發光。",
		GOLDENPITCHFORK = "雖然它無法讓地面著火，但至少它會閃閃發光。",
		GOLDENSHOVEL = "雖然它無法用來挖火坑，但至少它會閃閃發光。",
		GOLDNUGGET = "我該在哪裡花掉這個。",
		GRASS =
		{
			BARREN = "它需要施肥。",
			BURNING = "燒吧！哇！",
			GENERIC = "是一叢易燃的草。",
			PICKED = "草茬沒什麼用。",
		},
		GREEN_CAP = "真乏味！",
		GREEN_CAP_COOKED = "我用火改變了它！",
		GREEN_MUSHROOM =
		{
			GENERIC = "愚蠢的蘑菇。",
			INGROUND = "嘿！你！給我起來！",
			PICKED = "也許有一天它會再長回來。",
		},
		GUNPOWDER = "哇哦！好閃亮！",
		HAMBAT = "很高興認識你，我的肉友！",
		HAMMER = "我喜歡鋒利的工具",
		HEALINGSALVE = "它燒著了！但是火在哪裡？",
		HEATROCK =
		{
			COLD = "已經冷冰冰的了。",
			GENERIC = "火會讓這東西變暖！",
			HOT = "看看它是怎麼發光的！",
			WARM = "既沒有火焰，也沒有真正的熱量...有什麼好玩的？",
		},
		HOMESIGN = "少讀！多燒！",
		HONEY = "甜蜜而美味！",
		HONEYCOMB = "像蠟一樣。",
		HONEYHAM = "烈火、火腿和蜂蜜是絕配。",
		HONEYNUGGETS = "蜂蜜和肉塊遇到最可愛的火，就成了蜂蜜包肉。",
		HORN = "我可以聽到裡面有那些多毛動物的聲音。",
		HOUND = "真是個混蛋！",
		HOUNDMOUND = "啊哦，我不喜歡那東西的樣子。",
		HOUNDBONE = "噁心。",
		ICEBOX = "這是火的對立面。",
		ICEHOUND = "可惡！好冷！",
		INSANITYROCK =
		{
			ACTIVE = "是我看花眼了嗎？",
			INACTIVE = "看上去不像是能燃燒的。太無趣了。",
		},
		JAMMYPRESERVES = "舔，舔，舔！五秒搞定。",
		KABOBS = "火烤的肉，用簽子串起！",
		KILLERBEE =
		{
			GENERIC = "我喜歡那隻蜜蜂的樣子。",
			HELD = "嗡嗡！",
		},
		KNIGHT = "是馬兒耶！",
		KOALEFANT_SUMMER = "我們會成為很好的朋友的！",
		KOALEFANT_WINTER = "毫無疑問，他看上去很暖和...",
		KRAMPUS = "退後，你這個大混蛋！",
		KRAMPUS_SACK = "我有新的包包了！",
		LEIF = "他看上去一點就著！",
		LEIF_SPARSE = "他看上去一點就著！",
		LIGHTNING_ROD =
		{
			CHARGED = "哇，通體發光但沒有火。",
			GENERIC = "所有閃電都將彙集到這裡！",
		},
		LITTLE_WALRUS = "他看上去很美味。",
		LIVINGLOG = "它看起來很煩躁。",
		LOCKEDWES = "他被那些卑鄙的雕像給困住了！",
		LOG =
		{
			BURNING = "燒吧，木頭，燒燒燒燒吧！",
			GENERIC = "木頭！容易燃燒的木頭！太好了！",
		},
		LUREPLANT = "我打賭一把火就可以解決它。",
		LUREPLANTBULB = "它現在歸我了。",
		MALE_PUPPET = "他看起來已經被嚇得半死。",
		MANDRAKE =
		{
			DEAD = "為什麼這植物長著一張臉？",
			GENERIC = "那株植物不太正常",
			PICKED = "現在它太嚇人了！",
		},
		COOKEDMANDRAKE = "火都沒能把它的臉燒掉。這讓我有點不安。",
		MANDRAKESOUP = "將它熬成湯後，終於看不到它的臉了。",
		MARBLE = "它很重！",
		MARBLEPILLAR = "不知道其餘的燒燬了沒。",
		MARBLETREE = "世上最糟糕的樹， 居然不能燃燒。",
		MARSH_BUSH =
		{
			BURNING = "燃燒吧，刺木！",
			GENERIC = "它看上去很尖銳。",
			PICKED = "這些刺木刺得人很痛！",
		},
		MARSH_PLANT = "徹頭徹尾的植物。",
		MARSH_TREE =
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "現在沒那麼刺手了，對吧？",
			GENERIC = "它看起來很危險！",
		},
		MAXWELL = "他太傲慢了。",
		MAXWELLHEAD = "他顯然很愛講話。",
		MAXWELLLIGHT = "一點都不好玩。它們可以自己把自己點燃。",
		MAXWELLLOCK = "現在我只需要一把鑰匙。",
		MAXWELLTHRONE = "看上去很黏。",
		MEAT = "有火的話，味道更好！",
		MEATBALLS = "將肉做成丸子，用火烹飪一下就成了美味。",
		MEATRACK =
		{
			DONE = "已經乾了！",
			DRYING = "拜託，肉塊，快點乾吧！",
			GENERIC = "我想要曬些肉乾！",
		},
		MEAT_DRIED = "雖然有點難嚼，但還不錯。",
		MERM = "又軟又濕，真噁心。",
		MERMHEAD = "讓你這麼臭，這就是你的下場！",
		MERMHOUSE = "沒人會在意它是否被燒燬。",
		MONSTERLASAGNA = "麵條、肉和一團一團的毛髮。真噁心。",
		MONSTERMEAT = "噁心。到處都是毛。",
		MONSTERMEAT_DRIED = "乾的，聞起來怪怪的。",
		MOSQUITO =
		{
			GENERIC = "真煩人！",
			HELD = "讓你那張嘴離我遠點！",
		},
		MOSQUITOSACK = "在沉悶厚重的氣流中，血液必須沸騰起來。",
		MOUND =
		{
			DUG = "幸好是它不是我。",
			GENERIC = "我打賭裡面全是死去的東西。",
		},
		NIGHTLIGHT = "像火焰一樣，不過是紫色的！",
		NIGHTMAREFUEL = "噁心，還是溫熱的！",
		NIGHTSWORD = "好像我的夢境會對現實事物造成傷害！",
		NITRE = "裡面有一些小爆炸。",
		ONEMANBAND = "我還可以製作煙火！",
		PANDORASCHEST = "有點俗氣。",
		PANFLUTE = "音樂很無聊。",
		PAPYRUS = "我肯定它能夠燃燒！",
		PENGUIN = "跑掉的小小舞蹈家。",
		PERD = "臭鳥！別靠近我美味的漿果！",
		PEROGIES = "用火來封口的美味餃子。",
		PETALS = "愚蠢的花。幾乎是毫無用處。",
		PETALS_EVIL = "好噁心，太黏了。",
		PICKAXE = "它很尖銳。",
		PIGGYBACK = "我用豬屁股做了個背包！",
		PIGHEAD = "比起那傢伙，我的處境還不算太糟。",
		PIGHOUSE =
		{
			FULL = "他在裡面幹一些豬的事情。",
			GENERIC = "這些豬在建築方面的品味真的很有問題",
			LIGHTSOUT = "你個蠢貨！讓我進去！",
		},
		PIGKING = "呸。懶人一個。",
		PIGMAN =
		{
			DEAD = "真想嚐嚐它們的味道如何。",
			FOLLOWER = "討厭。它在跟著我。",
			GENERIC = "呃。真是臭死了。",
			GUARD = "他可不是我的Boss！",
			WEREPIG = "出招吧，小豬！",
		},
		PIGSKIN = "哈哈。豬屁股。",
		PIGTORCH = "這些豬可真知道享受。",
		PINECONE = 
		{
		    GENERIC = "嘿，你好啊，大樹種子。",
		    PLANTED = "你很快就會長成一棵真正的樹的。",
		},
		PITCHFORK = "三倍那麼尖。",
		PLANTMEAT = "真噁心，又黏又滑。",
		PLANTMEAT_COOKED = "火可以讓一切東西變得更好。",
		PLANT_NORMAL =
		{
			GENERIC = "如果沒得選的話，我會吃它的。",
			GROWING = "快點長，你個愚蠢的植物！",
			READY = "我的乖乖。新鮮的蔬菜。",
		},
		POMEGRANATE = "為什麼它有這麼多部分？",
		POMEGRANATE_COOKED = "火總是讓東西變得更好。",
		POMEGRANATE_SEEDS = "一顆小小的種子。看上去和果實裡面的東西很像。",
		POOP = "嘔... 真噁心。不過很有用。",
		PUMPKIN = "我很好奇它用火烤後會變成什麼樣子。",
		PUMPKINCOOKIE = "小甜餅！！！",
		PUMPKIN_COOKED = "在外面用火烤出來的東西真的挺不錯的。",
		PUMPKIN_LANTERN = "裡面的火真是太神奇了！",
		PUMPKIN_SEEDS = "在蔬菜裡，南瓜是火最好的朋友，而這就是南瓜種子。",
		PURPLEGEM = "好奇異！",
		RABBIT =
		{
			GENERIC = "他看上去很美味。",
			HELD = "想抓住他的時候就得手了！",
		},
		RABBITHOLE = "蠢兔子， 快出來，我要吃了你。",
		RAINOMETER = "雨火不兩立。切！",
		RATATOUILLE = "蔬菜。好多的蔬菜。",
		RAZOR = "我為什麼做了這玩意？",
		REDGEM = "真漂亮！",
		RED_CAP = "我喜歡這顏色。",
		RED_CAP_COOKED = "我用火改變了它！",
		RED_MUSHROOM =
		{
			GENERIC = "好漂亮！",
			INGROUND = "嘿！你！給我起來！",
			PICKED = "也許有一天它會再長回來。",
		},
		REEDS =
		{
			BURNING = "燒吧！耶！",
			GENERIC = "這是一叢可以燒著的蘆葦",
			PICKED = "我拿蘆葦茬毫無辦法。",
		},
        RELIC = 
        {
            GENERIC = "老古董。",
            BROKEN = "零七八碎，七零八碎。",
        },
        RUBBLE = "殘破的傢俱。",
		RESEARCHLAB = "即使有些東西我不知道，這也只是暫時的。",
		RESEARCHLAB2 = "即使有些東西我不知道，這也只是暫時的。",
		RESEARCHLAB3 = "它散發著黑暗而強大的能量。",
		RESURRECTIONSTATUE = "那是我的保險單。",
		RESURRECTIONSTONE = "我是不是應該去摸一下它？",
		ROBIN =
		{
			GENERIC = "一隻紅雀。火一樣的顏色，但不是鳳凰。",
			HELD = "它在我口袋裡很舒服。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "它看起來好冷。我猜它肯定想烤火。",
			HELD = "它的羽毛好軟。",
		},
		ROBOT_PUPPET = "它看起來已經被嚇得半死。",
		ROCK_LIGHT =
		{
			GENERIC = "裹了石皮的熔岩坑。",
			OUT = "噢，它涼下來了。",
			LOW = "熔岩在冷卻。",
			NORMAL = "一個火塘！",
		},
		ROCKS = "可以用這些東西來修建因努伊特石堆嗎？",
        ROOK = "這是一個城堡！",
        ROPE = "我可以用這個來綁什麼？",
		ROTTENEGG = "好噁心！為什麼？為什麼會這樣？！",
		SANITYROCK =
		{
			ACTIVE = "我想知道這些標記有什麼含義。",
			INACTIVE = "它去了哪裡？",
		},
		SAPLING =
		{
			BURNING = "燒吧！耶！",
			GENERIC = "我應該採摘它。",
			PICKED = "可憐的小樹苗。",
		},
		SEEDS = "耕種最無聊了。",
		SEEDS_COOKED = "現在不能用來耕種了。",
		SEWING_KIT = "但是搞破壞要有趣得多！",
		SHOVEL = "不太適合用來戰鬥。",
		SILK = "嗯。好光滑。",
		SKELETON = "天啊。真希望它是在榮耀的火焰中死去的。",
		SKULLCHEST = "哦哦哦，太可怕了！",
		SMALLBIRD =
		{
			GENERIC = "我覺得吧，雖然不太像鳳凰，但還是很可愛。",
			HUNGRY = "你餓了嗎？",
			STARVING = "好好好！我知道了，你餓了。",
		},
		SMALLMEAT = "有火的話，味道更好！",
		SMALLMEAT_DRIED = "雖然有點難嚼，但還不錯。",
		SPEAR = "感受我的憤怒吧！",
		SPIDER =
		{
			DEAD = "哈！嚐到我的厲害了吧！",
			GENERIC = "他很討厭。我應該殺了他。",
			SLEEPING = "我可以幹掉他。",
		},
		SPIDERDEN = "太讓人厭惡了。",
		SPIDEREGGSACK = "一大堆讓人噁心的小蜘蛛。",
		SPIDERGLAND = "好噁心，又黏又臭！",
		SPIDERHAT = "誰是你媽媽！",
		SPIDERQUEEN = "用火燒死它！",
		SPIDER_WARRIOR =
		{
			DEAD = "他活該。",
			GENERIC = "也許我可以...用火燒死它。",
			SLEEPING = "也許我不應該去打擾那傢伙。",
		},
		SPOILED_FOOD = "至少它仍然是可以燃燒的。",
		STATUEHARP = "好漂亮的雕像。弄壞了就可惜了。",
		STATUEMAXWELL = "我開始討厭那傢伙了。",
		STINGER = "好刺手！",
		STRAWHAT = "一頂稻草做的帽子。但是我覺得，它本來可以成為火種的。",
		SUNKBOAT = "它太遠了，我都燒不到它！",
		SWEATERVEST = "雖然沒有火焰背心那麼好，但還湊合。",
		TAFFY = "甜食燒起來感覺很棒，不過我應該把它吃下去，而不是燒掉。",
		TALLBIRD = "我覺得它不想和我交朋友。",
		TALLBIRDEGG = "它喜歡火嗎？",
		TALLBIRDEGG_COOKED = "經火烤之後好多了。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "火需要再旺點！",
			GENERIC = "現身吧，我的鳳凰！",
			HOT = "火是不是太旺了？",
			LONG = "這需要多長時間？",
			SHORT = "我都等得不耐煩了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "可以用火來烤那個蛋！",
			PICKED = "巢是空的。",
		},
		TEENBIRD =
		{
			GENERIC = "我感覺他能理解我。",
			HUNGRY = "他的確吃得多。",
			STARVING = "不要看我！自己去找吃的。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我只想看著這個世界燒起來。",
			GENERIC = "我喜歡這些符號發亮的樣子。",
			LOCKED = "需要以某種方式解鎖。",
			PARTIAL = "我在創造怪物！",
		},
		TELEPORTATO_BOX = "感覺暖暖的。",
		TELEPORTATO_CRANK = "這部分有什麼用？",
		TELEPORTATO_POTATO = "也許我可以把它融化成更漂亮的形狀。",
		TELEPORTATO_RING = "這麼珍貴的東西燒了太可惜了！",
		TENT = "我可是獲得過所有勳章的女童子軍。",
		TENTACLE = "一點都不討人喜歡。",
		TENTACLESPOTS = "呃，好噁心。",
		TENTACLESPIKE = "它又尖又黏。",
		TENTACLE_PILLAR = "它在顫抖。",
		TENTACLE_PILLAR_ARM = "啊，它們想要擁抱！",
		TENTACLE_GARDEN = "我聽到有輕微的挖土的聲音。",
		TOPHAT = "高禮帽和打火機，真是絕配。",
		TORCH = "火焰太漂亮了。",
		TRAP = "雖然有點被動攻擊的意思，但有用就行。",
		TRAP_TEETH = "有火就更好了。",
		TRAP_TEETH_MAXWELL = "什麼樣的混蛋會在地上放這東西？",
		TREASURECHEST = "可以幫我裝東西的箱子。",
		TRINKET_1 = "我猜，能夠把這些東西熔掉的火肯定溫度很高。",
		TRINKET_10 = "我覺得假牙也可以燒得很旺。",
		TRINKET_11 = "哦，不知道他有沒有火焰噴射器！",
		TRINKET_12 = "全部萎縮了，就好像它過於靠近火一樣。",
		TRINKET_2 = "廉價的假玩意兒。它甚至也許都不能當柴火燒。",
		TRINKET_3 = "那是個死結。有火的話，誰還需要刀啊？",
		TRINKET_4 = "他看起來像是經過烈火鍛造的。",
		TRINKET_5 = "看看那些迷你推進器。真是驚人的爆發力！",
		TRINKET_6 = "連一點火花都沒有。",
		TRINKET_7 = "還是縱火比較有趣。",
		TRINKET_8 = "我從來不喜歡用水洗澡。",
		TRINKET_9 = "你可以在拉鍊上擦火柴，但無法在鈕釦上擦。",
		TRUNKVEST_SUMMER = "現在我要永遠和我的朋友待在一起了。",
		TRUNKVEST_WINTER = "雖然不像火焰那樣溫暖，但還不錯！",
		TRUNK_COOKED = "我還是不確定到底要不要吃它。",
		TRUNK_SUMMER = "其實，他有一部分還是挺惹人喜愛的。",
		TRUNK_WINTER = "又軟又黏！",
		UMBRELLA = "我喜歡這顏色！",
		WAFFLES = "你好，鬆餅！",
		WALL_HAY = "看起來是一點就燃！",
		WALL_HAY_ITEM = "嗯。不知道這些東西會不會燒起來。",
		WALL_STONE = "嗯。我覺得還不錯。",
		WALL_STONE_ITEM = "沒想到這些東西這麼重。",
		WALL_RUINS = "壞蛋會來把它吹倒的！",
		WALL_RUINS_ITEM = "我的口袋裝得下它們嗎？",
		WALL_WOOD = "那東西很容易著火的。",
		WALL_WOOD_ITEM = "我討厭躲起來。",
		WALRUS = "別跟著我！",
		WALRUSHAT = "我蠻喜歡這帽子的樣式。",
		WALRUS_CAMP =
		{
			EMPTY = "我才不會進去那裡。討厭！",
			GENERIC = "為什麼其他人的房子都比我的漂亮？",
		},
		WALRUS_TUSK = "吧唧吧唧吧唧。",
		WASPHIVE = "我最好保持點距離。",
		WETGOOP = "怎麼會出錯呢？！我把它放進了火裡，而且做了一切該做的事。",
		WINTERHAT = "這對我來說還不夠暖和。",
		WINTEROMETER = "如果它能測量火的話會更好。",
		WORMHOLE =
		{
			GENERIC = "用棍子戳一下！",
			OPEN = "不知道他喜不喜歡辛辣的食物？",
		},
		ACCOMPLISHMENT_SHRINE = "我討厭那個箭頭！",        		
		LIVINGTREE = "它也許是活的，不過它還是會燃燒。",
		ICESTAFF = "太太太太無趣了。",
	},
	DESCRIBE_TOODARK = "我需要更多的光！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "呃。嘎吱。",
	},
}
