return {


	ACTIONFAIL_GENERIC = "我什麼都做不好。",
	ANNOUNCE_ADVENTUREFAIL = "並不是所有死亡都是相似的。",
	ANNOUNCE_BOOMERANG = "噢！這就是報應。",
	ANNOUNCE_CHARLIE = "惡魔！現身吧！",
	ANNOUNCE_CHARLIE_ATTACK = "我被攻擊了！",
	ANNOUNCE_COLD = "我感到徹骨的寒冷。",
	ANNOUNCE_CRAFTING_FAIL = "我缺少必要的材料。",
	ANNOUNCE_DUSK = "黑暗很快就要降臨了。我必須做好準備。",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "那個不能吃。",
		SPOILED = "這個食物已經接近生命的尾聲了。",
		STALE = "不新鮮了嗎？",
	},
	ANNOUNCE_ENTER_DARK = "黑暗吞沒了我。",
	ANNOUNCE_ENTER_LIGHT = "那兒有光！",
	ANNOUNCE_HOUNDS = "獵犬在狂吠。",
	ANNOUNCE_HUNGRY = "我感到無盡的空虛。",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我感覺附近有野獸。",
	ANNOUNCE_HUNT_LOST_TRAIL = "這個痕跡沒有指向任何地方。",
	ANNOUNCE_INV_FULL = "我帶不了更多東西了。",
	ANNOUNCE_KNOCKEDOUT = "天啊，好疼！我又一次醒過來了。",
	ANNOUNCE_NOHUNGERSLEEP = "我的胃就像我的心一樣空虛，我現在不能睡覺。",
	ANNOUNCE_PECKED = "你在試探我的耐心。",
	ANNOUNCE_QUAKE = "大地在晃動。它會將我整個吞沒嗎？",
	ANNOUNCE_THORNS = "噢！像我一樣刺手。",
	ANNOUNCE_TORCH_OUT = "黑暗再次降臨！",
	ANNOUNCE_TRAP_WENT_OFF = "噢，天哪。",
	ANNOUNCE_WORMHOLE = "我又一次出現在這個世界。",
	ANNOUNCE_CANFIX = "\n我覺得我能修好這個！",
	ANNOUNCE_ACCOMPLISHMENT = "這一切都是短暫的。",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "有一天，這個也會被忘記的。",
	BATTLECRY =
	{
		GENERIC = "死亡會找上你的！",
		PIG = "讓死亡擁抱你！",
		PREY = "受死吧，蟲子！",
		SPIDER = "我會把你送到另一個世界！",
		SPIDER_WARRIOR = "我會幹掉你！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "你應該活著， 至少目前不能死。",
	},
	DESCRIBE =
	{
		WORMLIGHT = "它發出了輕微的嗡嗡聲。",
		WORM =
		{
		    PLANT = "它看起來格格不入。",
		    DIRT = "那裡有什麼東西嗎？",
		    WORM = "它來自洞穴深處。",
		},
		EEL = "一條鰻魚。",
		EEL_COOKED = "一條熟鰻魚。",
		UNAGI = "這樣看起來更美味。",
		EYETURRET = "我不知道它為什麼幫我。",
		EYETURRET_ITEM = "我想我需要放置它。",
		MINOTAURHORN = "一位曾經的偉大野獸留下的全部遺物。",
		MINOTAURCHEST = "天啊，你有一對多麼華麗的角！",
		THULECITE_PIECES = "強大材料的碎片。",
		POND_ALGAE = "一些水藻。",
		GREENSTAFF = "我能看見其中深藏的能量火花。",
		POTTEDFERN = "它住在一個籠子裡。",

		THULECITE = "它的存在標誌著未知的邊界。",
		ARMORRUINS = "可以暫緩死亡。",
		RUINS_BAT = "我將遠古的力量握在了手中。",
		RUINSHAT = "阿比蓋爾會喜歡這個王冠的。",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "我不知道陰影中潛伏著什麼。",	
			WARN = "我可以感覺到虎視眈眈的眼睛。",	
			WAXING = "它們接近了。", 
			STEADY = "它們就在我身邊！", 
			WANING = "我想它們應該正在離去。", 
			DAWN = "快要結束了。", 
			NOMAGIC = "我孤單一人。", 
		},
		BISHOP_NIGHTMARE = "時間贏得了這場戰鬥。",
		ROOK_NIGHTMARE = "時間會侵蝕一切。",
		KNIGHT_NIGHTMARE = "另一場輸給時間的戰鬥。",
		MINOTAUR = "被困在這樣一個小小的牢籠中， 他肯定很孤獨。",	
		SPIDER_DROPPER = "黑暗褪去了它們身上的顏色。",	
		NIGHTMARELIGHT = "它從地下汲取能量。",	
		RELIC = "令人想起过去的景象。",	
		RUINS_RUBBLE = "一堆破碎的夢。",	
		MULTITOOL_AXE_PICKAXE = "一個用途多多的工具。",	
		GREENGEM = "瑕疵是它最美麗的特質。",
		ORANGESTAFF = "每次使用它時，我都會死亡並重生。",	
		YELLOWAMULET = "我黑暗生活中的一道短暫光芒。",	
		GREENAMULET = "才華的閃光！",	

		SLURPER = "啊，這麼簡單。",
		SLURPER_PELT = "一個空的飢餓口袋。",
		ARMORSLURPER = "貼身、沉悶、有生命的裝束。",
		ORANGEAMULET = "臨時從苦差中解脫。",
		YELLOWSTAFF = "這根魔杖和我的靈魂一樣扭曲。",
		YELLOWGEM = "這讓我想起了我媽媽。",
		ORANGEGEM = "這些東西過去曾給我帶來快樂。",
		TELEBASE = 
		{
			VALID = "能量從中流過。",
			GEMS = "傳送焦點是如此死氣沉沉。",
		},
		GEMSOCKET = 
		{
			VALID = "寶石讓能量聚集了。",
			GEMS = "它看上去如此空虛。",
		},
		STAFFLIGHT = "我幾乎能做出一個小小的太陽能系統。",
		RESEARCHLAB4 = "距離瘋狂只有一步之遙。",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="它很漂亮。",
			LONG = "這是我姐姐的花。她去了很遠的地方。",
			MEDIUM = "我能感覺到阿比蓋爾的氣息越來越強了。",
			SOON = "阿比蓋爾就快到了！",
			HAUNTED_POCKET = "阿比蓋爾準備好了，但她需要一點空間。",
			HAUNTED_GROUND = "我需要教阿比蓋爾怎麼玩。",

		},

        ANCIENT_ALTAR = "它充滿了死亡的回音。",
        ANCIENT_ALTAR_BROKEN = "我聽到了死者的痛苦回聲。",
        ANCIENT_STATUE = "不太有吸引力。",

        LICHEN = "它是怎麼長成那樣的？",
		CUTLICHEN = "就像生命一樣轉瞬即逝。",
		CAVE_BANANA = "它們的皮看起來很危險。",
		CAVE_BANANA_COOKED = "熱香蕉泥要美味多了。",
		CAVE_BANANA_TREE = "可憐的植物，永遠不見天日。",
		ROCKY = "他們看到了多麼可怕的景象。",


		BLUEAMULET = "熟悉的寒冷擁抱。",
		PURPLEAMULET = "正在滲出怪影。",
		TELESTAFF = "如果它更強大一些，我就可以解脫了。",
		MONKEY = "不用動腦地活著肯定很爽。",
		MONKEYBARREL = "真髒。",
		MONSTERLASAGNA = "弄熟的惡魔還是惡魔，在千層餅中也不會改變。",
		HOUNDSTOOTH="連根拔起。",
		ARMORSNURTLESHELL="現在我可以躲開麻煩了。",
		BAT="夜行生物。",
		BATBAT = "一件被施了魔法的武器。多麼令人興奮！",
		BATWING="要是我也能飛走就好了。",
		BATWING_COOKED="它們曾經擁有如此大的潛力。",
		BEDROLL_FURRY="我要用死去動物的毛皮把自己包裹起來。",
		BUNNYMAN="它們的內心世界一定備受折磨。",
		FLOWER_CAVE="它看起來很脆弱。",
		FLOWER_CAVE_DOUBLE="它看起來很脆弱。",
		FLOWER_CAVE_TRIPLE="它看起來很脆弱。",
		GUANO="這是生命不可避免的副產品。",
		LANTERN="昏暗地照出前方的路。",
		LIGHTBULB="它在慢慢燃盡光亮。",
		MANRABBIT_TAIL="毛茸茸、軟綿綿的，盡顯其本質。",
		MUSHTREE_TALL  ="這是一些奇怪的樹。",
		MUSHTREE_MEDIUM="它看起來像一頂腐爛的帽子。",
		MUSHTREE_SMALL ="有小地精生活在這裡嗎？",
		RABBITHOUSE="它並不像看上去那樣是可以吃的。",
		SLURTLE="它盲目地追逐著石頭。",
		SLURTLE_SHELLPIECES="尖殼蝸牛夢想的碎片。",
		SLURTLEHAT="我覺得它對我的幫助不會比對前主人的幫助多。",
		SLURTLEHOLE="尖殼蝸牛長得太大的時候就會從裡面出來。",
		SLURTLESLIME="它閃爍著微光，看上去就很黏。",
		SNURTLE="那個蝸牛的殼更大。",
		SPIDER_HIDER="一隻膽小的蜘蛛。",
		SPIDER_SPITTER="它在嚼著什麼東西。",
		SPIDERHOLE="這裡到處都是蜘蛛。",
		STALAGMITE="大地慷慨地奉獻了這些岩石。",
		STALAGMITE_FULL="大地慷慨地奉獻了這些岩石。",
		STALAGMITE_LOW="大地慷慨地奉獻了這些岩石。",
		STALAGMITE_MED="大地慷慨地奉獻了這些岩石。",
		STALAGMITE_TALL="大地的奇觀。",
		STALAGMITE_TALL_FULL="大地的奇觀。",
		STALAGMITE_TALL_LOW="大地的奇觀。",
		STALAGMITE_TALL_MED="大地的奇觀。",

		TURF_CARPETFLOOR = "一些地面。",
		TURF_CHECKERFLOOR = "一些地面。",
		TURF_DIRT = "一些地面。",
		TURF_FOREST = "一些地面。",
		TURF_GRASS = "一些地面。",
		TURF_MARSH = "一些地面。",
		TURF_ROAD = "一些地面。",
		TURF_ROCKY = "一些地面。",
		TURF_SAVANNA = "一些地面。",
		TURF_WOODFLOOR = "一些地面。",

		TURF_CAVE="一些地面。",
		TURF_FUNGUS="一些地面。",
		TURF_SINKHOLE="一些地面。",
		TURF_UNDERROCK="一些地面。",
		TURF_MUD="一些地面。",

		POWCAKE = "我要不是餓瘋了絕不會吃它。",		
		CAVE_ENTRANCE = 
		{
			GENERIC="有人不想讓別人進入地下。",
			OPEN = "地表之下潛伏著巨大的邪惡。",
		},
        CAVE_EXIT = "地面在召喚我。",
		BOOMERANG = "死亡會回到發鏢者身上。",
		MAXWELLPHONOGRAPH = "我們要跳一場死亡之舞嗎？",
		ABIGAIL = "那是我的孿生姐姐，阿比蓋爾。",
		PIGGUARD = "這頭小豬看上去脾氣不好。",
		ADVENTURE_PORTAL = "這是哪門子的技術恐怖行動？",
		AMULET = "我想知道過去它屬於誰。",
		ANIMAL_TRACK = "野獸的痕跡。",
		ARMORGRASS = "我延遲了不可避免的死亡。",
		ARMORMARBLE = "停下那把刺向我心臟的利刃。",
		ARMORWOOD = "穿著這個，我或許能拖延一下不可避免的死亡。",
		ARMOR_SANITY = "最安全的發瘋方法。",
		ASH =
		{
			GENERIC = "另一場熊熊大火過後只剩下這些。",
			REMAINS_EYE_BONE = "當我傳送時，這個眼骨被燒成了灰燼！",
			REMAINS_THINGIE = "在被燒燬前，它曾經是某樣東西…",
		},
		AXE = "用於工業和謀殺的工具。",
		BABYBEEFALO = "享受你的童年。很快你就會知道真實世界的殘酷。",
		BACKPACK = "一個背包。現在我可以背起更多重負了。",
		BACONEGGS = "吃了這份營養均衡的早餐，新的悲慘一天又開始了。",
		BANDAGE = "我還會再次受傷的。",
		BASALT = "嘗試破壞它是毫無意義的。",
		BEARDHAIR = "真髒。",
		BEDROLL_STRAW = "睡眠只是短暫的死亡。",
		BEE =
		{
			GENERIC = "我要避開毒刺。",
			HELD = "別亂動，小傢伙。",
		},
		BEEBOX =
		{
			GENERIC = "它們得去勞動，這樣我才有東西偷。",
			READY = "它們的辛勤工作收穫頗豐!",
		},
		BEEFALO =
		{
			FOLLOWER = "他跟著我走向他的末日。",
			GENERIC = "那些眼睛背後一定藏有什麼瘋狂的想法。",
			NAKED = "他現在赤身裸體了。",
			SLEEPING = "他肯定在做噩夢。",
		},
		BEEFALOHAT = "我應該蓋住我的腦袋。",
		BEEFALOWOOL = "在某個地方，一頭犛牛正光著身子受凍。",
		BEEHAT = "有了這個，我再也不用害怕那些快樂的嗡嗡聲， 也不用害怕那些毒刺了。",
		BEEHIVE = "充滿渣滓和花粉的可悲蜂窩。",
		BEEMINE = "它們在那裡面還是活的。可憐的小東西。",
		BERRIES = "這些漿果很酸。",
		BERRIES_COOKED = "味道更協調，但過不了多久它們就會腐爛。",
		BERRYBUSH =
		{
			BARREN = "它荒蕪了。",
			GENERIC = "一份點心，也許吧？",
			PICKED = "我必須等著。",
		},
		BIRDCAGE =
		{
			GENERIC = "我們中的一些人可以看到我們的籠子。",
			OCCUPIED = "他現在更開心了。",
			SLEEPING = "他死了嗎？不，只是睡著了而已。",
		},
		BIRDTRAP = "樹枝和蜘蛛絲也能變得致命。",
		BIRD_EGG = "這麼多的希望都化為烏有了。",
		BIRD_EGG_COOKED = "它再也孵不出小鳥了。",
		BISHOP = "他在祈禱什麼？",
		BLOWDART_SLEEP = "甚至都不會讓目標沉睡，只會造成短暫的休眠。",
		BLOWDART_PIPE = "我從這一端吹氣，另一端出來的是痛苦。",
		BLOWDART_FIRE = "我該燒掉整個世界嗎？",
		BLUEGEM = "憂鬱的藍色，就像...呃...一隻悲傷的鳥？",
		BLUEPRINT = "繪製這個的人可能已經死了。",
		BLUE_CAP = "單調乏味的菌類。",
		BLUE_CAP_COOKED = "全都是有韌性的。",
		BLUE_MUSHROOM =
		{
			GENERIC = "發霉的。",
			INGROUND = "如果可以的話，我也想藏起來。",
			PICKED = "採收了。",
		},
		BOARDS = "對樹木來說更可怕。",
		BONESTEW = "它們死了， 然後我將它們燉成了一鍋湯。",
		BUGNET = "小蟲子的監獄。",
		BUSHHAT = "噢，我可以隱身了。",
		BUTTER = "我可沒想到會有這個。",
		BUTTERFLY =
		{
			GENERIC = "美麗的生命，如曇花一現。",
			HELD = "它的生命掌握在我的手中。",
		},
		BUTTERFLYWINGS = "那隻蝴蝶再也不能飛了。",
		BUTTERFLYMUFFIN = "看你如何逃出這個甜蜜陷阱！",
		CAMPFIRE =
		{
			EMBERS = "黑暗快要降臨了。",
			GENERIC = "我也許能熬過今晚！",
			HIGH = "地獄般的景象！",
			LOW = "黑暗來襲。",
			NORMAL = "這是一堆營火。",
			OUT = "這不是個好兆頭。",
		},
		CANE = "我的速度快到不能更快了。",
		CARROT = "這是一根胡蘿蔔。",
		CARROT_COOKED = "這是一根經過烈火考驗的胡蘿蔔。",
		CARROT_PLANTED = "這是一根種在地裡的胡蘿蔔。",
		CARROT_SEEDS = "有一天，這顆種子將變成一根胡蘿蔔。",
		CAVE_FERN = "黑暗中的一抹顏色。",
		CHARCOAL = "冰冷死寂，如同我的內心。",
        CHESSJUNK1 = "冰冷、沒有生機的人造生命。",
        CHESSJUNK2 = "冰冷、沒有生機的人造生命。",
        CHESSJUNK3 = "冰冷、沒有生機的人造生命。",
		CHESTER = "一隻空虛的毛球。",
		CHESTER_EYEBONE =
		{
			GENERIC = "它看向了我靈魂的深處。",
			WAITING = "與其說是睡眠...不如說是等待。",
		},
		COOKEDMANDRAKE = "死得很有價值。他會很美味的。",
		COOKEDMEAT = "血被烤乾了。",
		COOKEDMONSTERMEAT = "弄熟的惡魔還是惡魔。",
		COOKEDSMALLMEAT = "火淨化了它。",
		CORN = "我可以說個關於玉米的老掉牙笑話，但我會克制的。",
		CORN_COOKED = "這個玉米熱得爆開了花。",
		CORN_SEEDS = "是的，這是一顆種子。",
		CROW =
		{
			GENERIC = "把你的嘴從我的心上拔出來！",
			HELD = "他是我的。",
		},
		CUTGRASS = "我喜歡殺死一些小東西。",
		CUTREEDS = "我喜歡割東西。",
		CUTSTONE = "方便用來做墓碑。",
		DEADLYFEAST = "這是我最後的晚餐。",
		DEERCLOPS = "死亡的化身！",
		DEERCLOPS_EYEBALL = "它肯定看到了什麼可怕的東西。",
		DEPLETED_GRASS =
		{
			GENERIC = "一叢草的遺跡。",
		},
		DIRTPILE = "噢，看看， 更多的泥土。",
		DIVININGROD =
		{
			COLD = "源頭在很遠的地方。",
			GENERIC = "它永遠在尋找失去的另一半。",
			HOT = "這裡有邪惡的東西！",
			WARM = "邪惡逼近了。",
			WARMER = "現在已經非常接近了。",
		},
		DIVININGRODBASE =
		{
			GENERIC = "這個新奇玩意有什麼用處？",
			READY = "它還需要一把大鑰匙。",
			UNLOCKED = "看看我能找到什麼！",
		},

		DRAGONFRUIT = "它的形狀一點也不像龍。",
		DRAGONFRUIT_COOKED = "還是沒有變成龍。至少它是死的。",
		DRAGONFRUIT_SEEDS = "這是一顆種子。它不會長成一條龍。",
		DRAGONPIE = "好吧，至少它現在做成派了。",
		DRUMSTICK = "可以用來打鼓，而且很有營養！",
		DRUMSTICK_COOKED = "烤熟點，更美味。",
		DUG_BERRYBUSH = "我喜歡它死去，但我應該把這個種下。",
		DUG_GRASS = "我喜歡它死去，但我應該把這個種下。",
		DUG_MARSH_BUSH = "我喜歡它死去，但我應該把這個種下。",
		DUG_SAPLING = "我喜歡它死去，但我應該把這個種下。",
		DURIAN = "多刺而難聞！",
		DURIAN_COOKED = "刺少了，但氣味甚至更重了！",
		DURIAN_SEEDS = "真是奇蹟，這些種子不臭。",
		EARMUFFSHAT = "它們最終保護我抵禦嚴寒。",
		EGGPLANT = "差一點就是致命的顛茄了。就差一點點。",
		EGGPLANT_COOKED = "煮熟這個茄子可以使它不那麼致命。",
		EGGPLANT_SEEDS = "這是一顆茄子種子。",
		EVERGREEN =
		{
			BURNING = "它在熊熊燃燒。",
			BURNT = "油盡燈枯。",
			CHOPPED = "萬物皆有一死。",
			GENERIC = "大自然真是無聊。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "它在熊熊燃燒。",
			BURNT = "油盡燈枯。",
			CHOPPED = "萬物皆有一死。",
			GENERIC = "它的生命循環結束了。",
		},
		EYEPLANT = "它們對主人言聽必從。",
		FARMPLOT =
		{
			GENERIC = "我該種什麼種子？",
			GROWING = "枝繁葉茂的捲鬚盤繞在泥土上。",
			NEEDSFERTILIZER = "這塊土地冰涼而沒有生機。",
		},
		FEATHERHAT = "嚓嚓！",
		FEATHER_CROW = "烏鴉羽毛，像永夜一樣漆黑。",
		FEATHER_ROBIN = "紅雀羽毛，鮮紅似血。",
		FEATHER_ROBIN_WINTER = "雪雀的羽毛，就像隧道盡頭的光一樣白。",
		FEM_PUPPET = "我想知道她幹了什麼。",
		FIREFLIES =
		{
			GENERIC = "黑暗中的微光。",
			HELD = "從我的口袋灑向外界的微光。",
		},
		FIREHOUND = "他的性情暴躁如火。",
		FIREPIT =
		{
			EMBERS = "黑暗快要降臨了。",
			GENERIC = "我也許能熬過今晚！",
			HIGH = "地獄般的景象！",
			LOW = "黑暗來襲。",
			NORMAL = "這是一堆營火。",
			OUT = "這不是個好兆頭。",
		},
		FIRESTAFF = "我可以點燃這個世界！",
		FISH = "它為了活命絕望地掙扎。可憐的傻瓜。",
		FISHINGROD = "用這個我能把魚從它們珍貴安全的小池塘裡拽出來。",
		FISHSTICKS = "精心打造的魚肉塊。",
		FISHTACOS = "希望我把魚刺都剔出來了。",
		FISH_COOKED = "烤上一會兒，它們就不會撲騰了。",
		FLINT = "一個刀刃狀的小石頭。",
		FLOWER = "它們明亮又活潑。真討厭。",
		FLOWERHAT = "但我正在哀悼...",
		FLOWER_EVIL = "至少比別的花要好。",
		FOLIAGE = "它在迷惑我。",
		FOOTBALLHAT = "我可以把這個死去的東西戴在頭上。太好了。",
		FROG =
		{
			DEAD = "生命渺小而短暫。",
			GENERIC = "他個子很小而且全身是包。",
			SLEEPING = "他睡著了。",
		},
		FROGGLEBUNWICH = "我從沒想過蛙腿可以看上去這麼棒。",
		FROGLEGS = "它是從青蛙身上扯下來的。",
		FROGLEGS_COOKED = "肯定不會再抽筋了。",
		FRUITMEDLEY = "裝在杯子裡，酸酸甜甜的。",
		GEARS = "機械惡魔的內心。",
		GHOST = "他從墳墓裡跑出來！",
		GOLDENAXE = "至少我可以更有格調地殺死樹了。",
		GOLDENPICKAXE = "至少我可以更有格調地挖礦了。",
		GOLDENPITCHFORK = "至少我可以更有格調地鏟地面了。",
		GOLDENSHOVEL = "至少我可以更有格調地挖東西了。",
		GOLDNUGGET = "我會把它帶在身上。",
		GRASS =
		{
			BARREN = "它需要施肥。",
			BURNING = "聞起來怪怪的。",
			GENERIC = "這只是一叢草。",
			PICKED = "它被殺死了。",
		},
		GREEN_CAP = "這個蘑菇太普通了，真讓人失望。",
		GREEN_CAP_COOKED = "全都是有韌性的。",
		GREEN_MUSHROOM =
		{
			GENERIC = "它又濕又冷。",
			INGROUND = "如果可以的話，我也想藏起來。",
			PICKED = "採收了。",
		},
		GUNPOWDER = "這是一條我踏上的黑暗之路。",
		HAMBAT = "用死亡製造死亡。",
		HAMMER = "噢，我可能會摧毀這個世界。",
		HEALINGSALVE = "生命帶來痛苦，痛苦帶來生命。",
		HEATROCK =
		{
			COLD = "只是一塊有些冰涼的石頭。",
			GENERIC = "它待在那裡，佔據著空間。",
			HOT = "燒得最亮的也會最快燒盡。",
			WARM = "像其他石頭一樣微溫而沒有生機。",
		},
		HOMESIGN = "我做了個標記，不過是暫時的。",
		HONEY = "甜蜜而短暫的一餐。",
		HONEYCOMB = "散亂的蜂窩碎片。",
		HONEYHAM = "死去的肉塊，蘸滿甜蜜的醬汁。",
		HONEYNUGGETS = "死去的肉塊，蘸滿甜蜜的醬汁。",
		HORN = "聽起來裡面似乎困著一頭犛牛。",
		HOUND = "退後，惡魔的骯髒手下！",
		HOUNDBONE = "邪惡野獸的遺骨。",
		HOUNDMOUND = "最邪惡的生物的巢穴。",
		ICEBOX = "像我的心一樣冰冷。",
		ICEHOUND = "他有一顆冰冷、死寂的心。",
		INSANITYROCK =
		{
			ACTIVE = "它在呼喚我的名字。",
			INACTIVE = "它烏黑冰冷。",
		},
		JAMMYPRESERVES = "份量很完美的果醬。",
		KABOBS = "從肉塊中間刺穿的肉串。",
		KILLERBEE =
		{
			GENERIC = "一隻凶狠無情的蜜蜂。",
			HELD = "別亂動，小傢伙。",
		},
		KNIGHT = "一匹冰冷的、沒有靈魂的馬。",
		KOALEFANT_SUMMER = "一隻孤獨的野獸。",
		KOALEFANT_WINTER = "它抵抗著殘酷的天氣。",
		KRAMPUS = "你好啊，地下的邪惡生物。",
		KRAMPUS_SACK = "聞起來一股羊膻味。",
		LEIF = "一隻動作遲緩的野獸。",
		LEIF_SPARSE = "一隻動作遲緩的野獸。",
		LIGHTNING_ROD =
		{
			CHARGED = "即使是這樣的力量也會耗盡。",
			GENERIC = "將毀滅的力量聚集於一處。",
		},
		LITTLE_WALRUS = "暴力週而復始，仍在繼續。",
		LIVINGLOG = "它永遠在無聲地尖叫。",
		LOCKEDWES = "被麥斯威爾的雕像困住，獲得永生。",
		LOG = "如果樹木可以說話，它們看到這個會尖叫的。",
		LUREPLANT = "它吞食萬物。",
		LUREPLANTBULB = "生命在繼續。",
		MALE_PUPPET = "我想知道他幹了什麼。",
		MANDRAKE =
		{
			DEAD = "唉，可憐的曼德拉草！",
			GENERIC = "強大的曼德拉草。我應該在晚上來採摘它。",
			PICKED = "前進，我的蔬菜部下！",
		},
		MANDRAKESOUP = "他被煮死了。",
		MARBLE = "光滑而沒有生機。",
		MARBLEPILLAR = "即使是石頭，也經不起天長地久的腐蝕。",
		MARBLETREE = "這棵冰冷的樹裡沒有生命的脈動。",
		MARSH_BUSH =
		{
			BURNING = "就連刺木也會燃燒。",
			GENERIC = "總是能造成傷痛的灌木叢。",
			PICKED = "為了採收它我受了傷。",
		},
		MARSH_PLANT = "這是一株植物。",
		MARSH_TREE =
		{
			BURNING = "它在燃燒",
			BURNT = "像我的心一樣黑",
			CHOPPED = "它的針葉沒能保護它。",
			GENERIC = "一棵只能感受到痛苦的樹。",
		},
		MAXWELL = "他讓我覺得有一種奇怪的親切感。",
		MAXWELLHEAD = "他確實對戲劇有品味。",
		MAXWELLLIGHT = "多麼奇妙的光芒。",
		MAXWELLLOCK = "看起來充滿魔力。",
		MAXWELLTHRONE = "跟我期望的不太一樣。",
		MEAT = "依舊血腥。",
		MEATBALLS = "肉丸。太讓人興奮了。",
		MEATRACK =
		{
			DONE = "肉曬好了。",
			DRYING = "它在乾燥的風中晃來晃去。",
			GENERIC = "我可以把肉掛在這裡。",
		},
		MEAT_DRIED = "肉曬乾了，很美味。",
		MERM = "可怕的沼澤怪物！",
		MERMHEAD = "一點尊嚴都沒有。",
		MERMHOUSE = "時間的洗禮讓它破舊不堪。",
		MINERHAT = "解放雙手的照明工具！",
		MONSTERMEAT = "邪惡在裡面蔓延。",
		MONSTERMEAT_DRIED = "肉曬乾了，味道有點怪。",
		MOSQUITO =
		{
			GENERIC = "它以吸血為生。",
			HELD = "我能感覺到它偷來的鮮血的溫熱。",
		},
		MOSQUITOSACK = "從蚊子身上掉落下來的血囊。我愛這玩意。",
		MOUND =
		{
			DUG = "大地吐露了它的秘密。",
			GENERIC = "總有一天，我會加入你們的。",
		},
		NIGHTLIGHT = "怪異但美麗。",
		NIGHTMAREFUEL = "這東西隨著睡夢而來。",
		NIGHTSWORD = "噩夢漸漸變得尖銳， 鑄成了這把利劍。",
		NITRE = "這是人類的愚蠢帶來的產物。",
		ONEMANBAND = "我曾經在類似的樂器中享受這樣的快樂。",
		PANDORASCHEST = "生活是一場賭博。",
		PANFLUTE = "音樂是通向我空虛靈魂的窗戶。",
		PAPYRUS = "用於記錄我的痛苦。",
		PENGUIN = "全都衣冠楚楚，但是去哪呢？",
		PERD = "笨鳥！離我的漿果遠點！",
		PEROGIES = "小巧可愛的營養餃子。",
		PETALS = "我摧毀了美麗的東西。",
		PETALS_EVIL = "它們用我的靈魂著色。",
		PICKAXE = "有了這個，我或許可以挖穿地球。",
		PIGGYBACK = "它們在死後更有用。",
		PIGHEAD = "殺了這隻豬， 瀝乾他的血。",
		PIGHOUSE =
		{
			FULL = "我希望他過得愉快。",
			GENERIC = "至少這些屋子很舒適。",
			LIGHTSOUT = "現在我完全孤單了。",
		},
		PIGKING = "陛下，盡您所能逍遙快活吧。",
		PIGMAN =
		{
			DEAD = "他現在日子更好了。",
			FOLLOWER = "我還是覺得孤單。",
			GENERIC = "他們真不友好。",
			GUARD = "真是奧威爾式的做派。",
			WEREPIG = "夜行生物！",
		},
		PIGSKIN = "曾經是一隻豬身上的皮。",
		PIGTORCH = "它驅散了黑暗。",
		PINECONE = 
		{
		    GENERIC = "藏身於脆弱死亡中的渺小生命。",
		    PLANTED = "一棵樹很快就會長出來。",
		},
		PITCHFORK = "多麼邪惡的工具！",
		PLANTMEAT = "它的氣味很難聞。",
		PLANTMEAT_COOKED = "烹飪過後味道只好了一點點。",
		PLANT_NORMAL =
		{
			GENERIC = "一株可食用的植物。",
			GROWING = "繼續生長吧。我會等著的。",
			READY = "可以收穫了。",
		},
		POMEGRANATE = "這麼多可以咬碎擠扁的多汁紅色果肉！",
		POMEGRANATE_COOKED = "變熱了，但還是那麼麻煩。",
		POMEGRANATE_SEEDS = "我原本期望那東西能多產點種子。",
		POND = "奧菲莉雅， 你在下面嗎？",
		POOP = "生命的特徵就是血和這個。",
		PUMPKIN = "它和我心裡的洞一樣大。",
		PUMPKINCOOKIE = "我自己做的！",
		PUMPKIN_COOKED = "熱量讓它萎縮了一點點。我喜歡這樣。",
		PUMPKIN_LANTERN = "你並沒有那麼嚇人。",
		PUMPKIN_SEEDS = "這是一顆種子。真令人興奮。",
		PURPLEGEM = "紫得就像一個...紫色的東西。",
		RABBIT =
		{
			GENERIC = "他盲目地四處遊蕩，對自己的命運一無所知。",
			HELD = "他在我的懷裡很安全。",
		},
		RABBITHOLE = "我個子太大了，沒辦法掉到洞下面去。",
		RAINOMETER = "它能測出是否有雨。我喜歡沉悶的天氣。",
		RATATOUILLE = "一大鍋燴蔬菜， 非常吸引人。",
		RAZOR = "僅用於剃毛。",
		REDGEM = "像我的鮮血一樣紅。",
		RED_CAP = "知心的蘑菇。",
		RED_CAP_COOKED = "全都是有韌性的。",
		RED_MUSHROOM =
		{
			GENERIC = "它濕濕的。",
			INGROUND = "如果可以的話，我也想藏起來。",
			PICKED = "採收了。",
		},
		REEDS =
		{
			BURNING = "很快就化為灰燼了。",
			GENERIC = "這只是一簇蘆葦。",
			PICKED = "我已經採摘了它們。",
		},
        RELIC = 
        {
            GENERIC = "遠古世界的遺物。",
            BROKEN = "破碎的石塊",
        },
        RUINS_RUBBLE = "一堆破碎的夢。",
		RESEARCHLAB = "我會學到無法形容的事情。",
		RESEARCHLAB2 = "我會學到無法形容的事情。",
		RESEARCHLAB3 = "我學到了無法形容的事情。",
		RESURRECTIONSTATUE = "我只是將不可避免的死亡延遲了。",
		RESURRECTIONSTONE = "一個無足輕重的守衛。",
		ROBIN =
		{
			GENERIC = "這意味著春天來了嗎？希望不是。",
			HELD = "他喜歡被困在我的口袋裡。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "寒荒之地的生命。",
			HELD = "它如此柔軟。它是我的敵人。",
		},
		ROBOT_PUPPET = "我想知道它幹了什麼。",
		ROCK_LIGHT =
		{
			GENERIC = "裹了石皮的熔岩坑。",
			OUT = "它看起來無害。",
			LOW = "陰影來襲。",
			NORMAL = "熔岩著火了。",
		},
		ROCK = "連這個都不是永恆的。",
		ROCKS = "一些小石頭。",
        ROOK = "戰車？還是城堡？",
		ROPE = "這會是一種輕鬆的解脫方式。",
		ROTTENEGG = "萬物皆如此。",
		SANITYROCK =
		{
			ACTIVE = "它在召喚我。",
			INACTIVE = "就連這個方尖碑也離我而去了。",
		},
		SAPLING =
		{
			BURNING = "交給火焰了。",
			GENERIC = "它在努力生長。",
			PICKED = "也許下次吧，小樹苗。",
		},
		SEEDS = "生命，或者至少是孕育生命的希望。",
		SEEDS_COOKED = "我烤死了它們。",
		SEWING_KIT = "另一種推遲不可避免的耐久下降的方法。",
		SHOVEL = "我可能會挖掘出什麼可怕的秘密？",
		SILK = "如此光滑而精美。",
		SKELETON = "他解脫了，我很嫉妒。",
		SKULLCHEST = "那裡面應該有我的死亡警告。",
		SMALLBIRD =
		{
			GENERIC = "小傢伙，你好。",
			HUNGRY = "你身體裡面空虛嗎？",
			STARVING = "一個黑洞，種子有去無回。",
		},
		SMALLMEAT = "聞起來像小小的恐懼。",
		SMALLMEAT_DRIED = "肉曬乾了，很美味。",
		SPEAR = "我成了世界的毀滅者。",
		SPIDER =
		{
			DEAD = "總有一天我們會重逢。",
			GENERIC = "夜行生物！",
			SLEEPING = "惡魔睡著了。",
		},
		SPIDERDEN = "一窩烏合之眾。",
		SPIDEREGGSACK = "滿是死亡和毀滅的小包裹。",
		SPIDERGLAND = "即使死去，這隻野獸仍能製造傷痛。",
		SPIDERHAT = "是時候凝視深淵了。",
		SPIDERQUEEN = "她像帝王般殘酷。",
		SPIDER_WARRIOR =
		{
			DEAD = "唉，勇敢的戰士。",
			GENERIC = "夜行勇士！",
			SLEEPING = "我必須小心。",
		},
		SPOILED_FOOD = "最終一切都會變成垃圾。",
		STATUEHARP = "也許這些雕像將一直伴我左右。",
		STATUEMAXWELL = "他把我帶來這裡。",
		STINGER = "鋒利而致命。",
		STRAWHAT = "我應該蓋住我的腦袋。",
		STUFFEDEGGPLANT = "一隻茄子， 裡面大概沒有塞滿毒藥。",
		SUNKBOAT = "殘忍的騙局！",
		SWEATERVEST = "我可以穿上這件背心，它是用一塊塊死去的東西做成的！",
		TAFFY = "從沒想過我可以做出這麼甜蜜的東西。",
		TALLBIRD = "擺脫天空的桎梏。",
		TALLBIRDEGG = "充滿了潛力。",
		TALLBIRDEGG_COOKED = "所有希望都被奪走了。和培根搭配起來不賴。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "因黑暗而感到寒冷。",
			GENERIC = "小小的脆弱生命，正在掙扎著迎向光明。",
			HOT = "它承受不了這樣的高溫。",
			LONG = "越早誕生，越早消亡。",
			SHORT = "就快出來了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "這個蛋代表了一個新生命。呃。",
			PICKED = "巢是空的。空虛、 貧瘠 而虛無。",
		},
		TEENBIRD =
		{
			GENERIC = "你也要離開我嗎？",
			HUNGRY = "我們都想填補空虛。",
			STARVING = "你露出了本性！",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我確信下一個地方會更可怕！",
			GENERIC = "它不會帶來什麼好事。",
			LOCKED = "它仍然是上鎖關閉的狀態。",
			PARTIAL = "它是建成了一半，還是有一半被摧毀了？",
		},
		TELEPORTATO_BOX = "它包含著至關重要的火花。",
		TELEPORTATO_CRANK = "它看起來很複雜。",
		TELEPORTATO_POTATO = "多麼醜陋的產物！",
		TELEPORTATO_RING = "它沒有鋒利的邊緣。",
		TENT = "睡眠只是死亡的預演。",
		TENTACLE = "又瘦又長又危險！",
		TENTACLESPOTS = "這些事最好略過不提。",
		TENTACLESPIKE = "鋒利、黏滑而危險。",
        TENTACLE_PILLAR = "所以這就是下面的情況了。",
        TENTACLE_PILLAR_ARM = "小觸手！",
        TENTACLE_GARDEN = "這東西是不同的。",
		TOPHAT = "我應該蓋住我的腦袋。",
		TORCH = "對抗黑夜的小小武器。",
		TRAP = "小小的草也變得致命了。",
		TRAP_TEETH = "來自地下的卑劣意外。",
		TRAP_TEETH_MAXWELL = "猝不及防的死亡。",
		TREASURECHEST = "它裝著我的財富。",
		TRINKET_1 = "非常奇異。",
		TRINKET_10 = "另一張要餵飽的嘴。",
		TRINKET_11 = "幸運的機器人，它永遠都不會有靈魂。",
		TRINKET_12 = "不再那麼黏滑了，不是嗎？",
		TRINKET_2 = "這是假的。只是一種誘惑，就像死亡一樣。",
		TRINKET_3 = "要是小刀能解決我的更多問題該有多好...",
		TRINKET_4 = "我會帶著這個，直到世界末日。",
		TRINKET_5 = "如果它再大點的話，我會乘著它筆直飛向太陽。",
		TRINKET_6 = "曾經因通電而有了生命，現在已經走到了盡頭。",
		TRINKET_7 = "只是一個簡單的遊戲。",
		TRINKET_8 = "我希望可以洗個澡。",
		TRINKET_9 = "不搭的鈕釦，亂搭的人生。",
		TRUNKVEST_SUMMER = "穿在我皮膚上的另一層皮。",
		TRUNKVEST_WINTER = "它也許能溫暖我的身體，但對我的靈魂有什麼用呢？",
		TRUNK_COOKED = "現在看上去更糟了。",
		TRUNK_SUMMER = "我更喜歡耳朵。",
		TRUNK_WINTER = "和它唯一的朋友分開了。",
		TURKEYDINNER = "誰在咯咯叫？",
		TWIGS = "還沒長大就被拔出了土地。",
		UMBRELLA = "雲在流淚。",
		WAFFLES = "它們肯定是鬆餅。",
		WALL_HAY = "只能做做防禦的樣子。",
		WALL_HAY_ITEM = "它們的防禦效果值得懷疑。",
		WALL_STONE = "在裡面又有什麼來保護我呢？",
		WALL_STONE_ITEM = "這不能抵禦內心的惡魔。",
		WALL_RUINS = "這些牆並沒能保護古人，不是嗎！",
		WALL_RUINS_ITEM = "這些石頭會鬧鬼嗎？",
		WALL_WOOD = "現在我可以延遲不可避免的死亡。",
		WALL_WOOD_ITEM = "捆起來的木頭。",
		WALRUS = "一個屬於海洋的老人家。",
		WALRUSHAT = "這下面洩露了怎樣的狂熱想法？",
		WALRUS_CAMP =
		{
			EMPTY = "如果它們不在這，那它們會在哪裡？",
			GENERIC = "我擔心這個家並不溫馨。",
		},
		WALRUS_TUSK = "我要把你咬碎。",
		WASPHIVE = "它們躲在仇恨的堡壘裡。",
		WETGOOP = "一團糟糕的東西，就像生活一樣。",
		WINTERHAT = "這有助於延緩寒冷的侵襲。",
		WINTEROMETER = "我怎麼覺得像在計算我的死期？",
		WORMHOLE =
		{
			GENERIC = "生命並非總是有意義。",
			OPEN = "不論多少東西都填不飽它的胃口。",
		},
		ACCOMPLISHMENT_SHRINE = "我向來不太關心隱喻。",
		LIVINGTREE = "它會長生不死嗎？",
		ICESTAFF = "有冰凍效果的魔杖。",
	},
	DESCRIBE_GENERIC = "無法說。",
	DESCRIBE_TOODARK = "黑暗！太黑了！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "我讓它免於經歷生活的痛苦。",
	},
}
