return {
	ANNOUNCE_ADVENTUREFAIL = "这次你赢了，麦斯威尔。",
	ANNOUNCE_BOOMERANG = "愚蠢的回旋镖！",
	ANNOUNCE_CHARLIE = "我不怕你！",
	ANNOUNCE_CHARLIE_ATTACK = "哎哟！你混蛋！",
	ANNOUNCE_COLD = "好冷！像冰火在燃烧！",
	ANNOUNCE_DUSK = "夜晚就要来了。我需要火！",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "呃！太难受了！",
		SPOILED = "太难吃了！",
		STALE = "吃起来有点恶心。",
	},
	ANNOUNCE_HOUNDS = "现身吧！",
	ANNOUNCE_HUNGRY = "我需要食物！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我会找到你的！",
	ANNOUNCE_HUNT_LOST_TRAIL = "噢...他消失了。",
	ANNOUNCE_ACCOMPLISHMENT= "转动吧，箭头！转动吧！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "搞定！",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "嘻嘻！",
		[2] = "漂亮！",
		[3] = "哎呀！",
		[4] = "我放了一把火！",
		[5] = "烧吧！",
		[6] = "我忍不住！",
	},
	ANNOUNCE_PECKED = "不要！你这只坏鸟！",
	ANNOUNCE_TORCH_OUT = "我宝贵的光消失了！",
	ANNOUNCE_WORMHOLE = "我要把这些衣服全烧掉！",
	ANNOUNCE_TRAP_WENT_OFF = "啊！",
    ANNOUNCE_CRAFTING_FAIL = "我肯定是漏掉了什么东西。",
    ANNOUNCE_QUAKE = "那个声音听起来不像是好事。",
    ANNOUNCE_NODANGERSLEEP = "没时间睡觉，我必须得战斗！",
    ANNOUNCE_NOHUNGERSLEEP = "肚子饿得咕咕叫，睡不着！",
    ANNOUNCE_FREEDOM = "我自由了！该放火庆祝一下！",
    ANNOUNCE_RESEARCH = "这很有用，即使它跟火扯不上一点关系。",
    ANNOUNCE_NO_TRAP = "就像放火烧水桶里的鱼一样白费力气。",
    ANNOUNCE_HIGHRESEARCH = "好多信息！",
    ANNOUNCE_THORNS = "哎哟！",
    ANNOUNCE_NODAYSLEEP_CAVE = "在这下面睡觉太恐怖了。",
    ANNOUNCE_BEES = "啊啊啊啊！蜇人的虫子！",
    ANNOUNCE_KNOCKEDOUT = "啊啊，我的小脑袋！",
    ANNOUNCE_LOWRESEARCH = "切，太无聊了。",
    ANNOUNCE_DEERCLOPS = "听起来有一个怪物一样的凶恶巨人走过来了！",
    ANNOUNCE_MOSQUITOS = "滚开，你这个吸血的混蛋！",
    ANNOUNCE_NODAYSLEEP = "当天空挂着一个大火球时，我是不会进里面睡觉的。",
	ANNOUNCE_CANFIX = "\n我觉得我能修好这个！",
	BATTLECRY =
	{
		GENERIC = "不是你死，就是我活！",
		PIG = "蠢猪！",
		PREY = "放马过来！",
		SPIDER = "咿咿咿咿呀！",
		SPIDER_WARRIOR = "呃，杀杀杀了它！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "不出我所料！",
		PIG = "给我回来，猪扒！",
		PREY = "下次我再来收拾你！",
		SPIDER = "切，下次我再干掉他。",
		SPIDER_WARRIOR = "现在没那么强硬了！",
	},
	DESCRIBE =
	{
		WORMLIGHT = "没有火却能发光。太不正常了。",
		WORM =
		{
		    PLANT = "没有火却能发光。太不正常了。",
		    DIRT = "泥土通常会动吗？",
		    WORM = "它身上长了好多毛！",
		},
		EEL = "我不喜欢它的表情！",
		EEL_COOKED = "有了火，一切都变好了。",
		UNAGI = "我做的。",
		EYETURRET = "我希望它能让东西点燃。",
		EYETURRET_ITEM = "等我把它放好，它才能发挥作用。",
		MINOTAURHORN = "不知道这些圈圈是否代表年龄。",
		MINOTAURCHEST = "我想要那样的大角！",
		THULECITE_PIECES = "这块铥矿已经成了碎片。",
		POND = "这片池塘肯定烧不起来。太无趣了。",
		POND_ALGAE = "它肯定需要大量的水。",
		GREENSTAFF = "虽然它没法用来生火，但我猜它还是很有用。",
		POTTEDFERN = "我宁愿烧掉它们。",

		THULECITE = "我觉得它应该不会燃烧。",
		ARMORRUINS = "我不确定要不要穿这个。",
		RUINS_BAT = "这可以让那些坏蛋不敢靠近我。",
		RUINSHAT = "似乎有什么东西在其中流动。",
		NIGHTMARE_TIMEPIECE = 
		{
		CALM = "感觉没什么异常。",	
		WARN = "它在警告我。",	
		WAXING = "魔法能量苏醒了！", 
		STEADY = "它几乎在嗡嗡作响。", 
		WANING = "魔法能量正在平静下来。", 
		DAWN = "我猜一切快结束了。", 
		NOMAGIC = "它好像停止工作了。", 
		},
		BISHOP_NIGHTMARE = "啊——！",
		ROOK_NIGHTMARE = "它的笑容很猥琐。",
		KNIGHT_NIGHTMARE = "它看上去很破旧。",
		MINOTAUR = "可怜的家伙。被困在了这个迷宫里。",	
		SPIDER_DROPPER = "它们是从上面下来的。",	
		NIGHTMARELIGHT = "不用火就可以照明实在是不正常。",	
		GREENGEM = "这个宝石感觉真的好亮。",
		RELIC = "我猜先前有人住在這裡。",	
		RUINS_RUBBLE = "也许我可以把它修好。",	
		MULTITOOL_AXE_PICKAXE = "这东西太有用了！",	
		ORANGESTAFF = "它让我头疼。",	
		YELLOWAMULET = "它似乎能够把周围的黑暗都吸进去。",	
		GREENAMULET = "戴着它我感觉自己的思维都开阔了。",	

		SLURPER = "它们肚子里有火吗？",
		SLURPER_PELT = "咦，它还是活的！",
		ARMORSLURPER = "呃，呸！呸！呸！呸！真恶心！",
		ORANGEAMULET = "它在帮我捡燃料！",
		YELLOWSTAFF = "太神奇了。",
		YELLOWGEM = "它在闪闪发光。",
		ORANGEGEM = "这东西刺痛我的手指了。",
		TELEBASE = 
		{
			VALID = "我可以感觉到魔力的存在！",
			GEMS = "它还需要一些东西。",
		},
		GEMSOCKET = 
		{
			VALID = "它们究竟是如何浮在空中的？",
			GEMS = "上面是空的！",
		},
		STAFFLIGHT = "太漂亮了！",
		RESEARCHLAB4 = "我可以把那个帽子当作巫师施符咒的大锅！",

        LIGHTER = "它是我的幸运打火机！",


        ANCIENT_ALTAR =
        {
        	WORKING = "哇！与来世相通。",
        	BROKEN = "死灵没法从这里出去。",
        },  
        ANCIENT_ALTAR_BROKEN = "死灵没法从这里出去。",

        ANCIENT_STATUE = "该死，又不会燃烧。",

        LICHEN = "一种有脆皮的植物",
		CUTLICHEN = "呸，一股锯屑的味道。",

        CAVE_BANANA = "香蕉！",
        CAVE_BANANA_COOKED = "好吃！",
        CAVE_BANANA_TREE = "看起来可以燃烧！",
        ROCKY = "我们可没有多少共同点。",

        BLUEAMULET = "切。",
		PURPLEAMULET = "这科技是不是有点走偏了？",
		TELESTAFF = "它用起来就像一阵风。",
		MINERHAT = "虽然不是真正的火光，但还是很有趣。",
		MONKEY = "开个玩笑！我可以点燃这坨便便。",
		MONKEYBARREL = "多么棒的家，一下子就能烧起来。",

		HOUNDSTOOTH="好锋利。我喜欢！",
		ARMORSNURTLESHELL="更少防守！更多进攻！",
		BAT="可爱的小家伙！",
		BATBAT = "我可以用它来对付敌人。",
		BATWING="呸！",
		BATWING_COOKED="呸！",
		BEDROLL_FURRY="褶边太多了。",
		BUNNYMAN="呃。它们看起来好蠢。",
		FLOWER_CAVE="它里面在燃烧。",
		FLOWER_CAVE_DOUBLE="它里面在燃烧。",
		FLOWER_CAVE_TRIPLE="它里面在燃烧。",
		GUANO="它烧起来和普通粪便没什么区别。",
		LANTERN="烈火不应该受到这样的束缚！",
		LIGHTBULB="真亮！",
		MANRABBIT_TAIL="我吵赢了。",
		MUSHTREE_TALL="恶心。这棵树已经病入膏肓了。",
		MUSHTREE_MEDIUM="恶心。闻起来像小妖精的屁股",
		MUSHTREE_SMALL="恶心。它从头到尾都像蘑菇。",
		RABBITHOUSE="呃。愚蠢的兔子。",
		SLURTLE="我想要把它炸飞！",
		SLURTLE_SHELLPIECES="嗬嗬。它碎了。",
		SLURTLEHAT="很适合我的脑袋。",
		SLURTLEHOLE="我应该把它们都烧掉。",
		SLURTLESLIME="我爱死这玩意儿了！",
		SNURTLE="砰！",
		SPIDER_HIDER="真是个难搞的家伙！",
		SPIDER_SPITTER="放马过来！",
		SPIDERHOLE="里面全是蜘蛛。",
		STALAGMITE="石头真无趣。",
		STALAGMITE_FULL="石头真无趣。",
		STALAGMITE_LOW="石头真无趣。",
		STALAGMITE_MED="石头真无趣。",
		STALAGMITE_TALL="又是无趣的岩石。",
		STALAGMITE_TALL_FULL="又是无趣的岩石。",
		STALAGMITE_TALL_LOW="又是无趣的岩石。",
		STALAGMITE_TALL_MED="又是无趣的岩石。",

		TURF_CARPETFLOOR = "地皮太没意思了。",
		TURF_CHECKERFLOOR = "地皮太没意思了。",
		TURF_DIRT = "地皮太没意思了。",
		TURF_FOREST = "地皮太没意思了。",
		TURF_GRASS = "地皮太没意思了。",
		TURF_MARSH = "地皮太没意思了。",
		TURF_ROAD = "地皮太没意思了。",
		TURF_ROCKY = "地皮太没意思了。",
		TURF_SAVANNA = "地皮太没意思了。",
		TURF_WOODFLOOR = "地皮太没意思了。",

		TURF_CAVE="地皮太没意思了。",
		TURF_FUNGUS="地皮太没意思了。",
		TURF_SINKHOLE="地皮太没意思了。",
		TURF_UNDERROCK="地皮太没意思了。",
		TURF_MUD="地皮太没意思了。",
		
		TURKEYDINNER = "一场烤鸟盛宴！",
		TWIGS = "一堆小树枝。和其他东西一样，也是很好的燃料。",
		POWCAKE = "我想知道它能不能燃烧。",
        CAVE_ENTRANCE = 
        {
            GENERIC="谁把那个洞给堵上的？",
            OPEN = "我希望下面某个地方会有熔岩。",
        },
        CAVE_EXIT = "这下面又黑又闷。",

		MAXWELLPHONOGRAPH = "我喜欢更刺激的音乐。",
		PIGGUARD = "我喜欢他的态度！",
		BOOMERANG = "它不是最让人兴奋的武器。",
		ADVENTURE_PORTAL = "也许那是回家的路。",
		AMULET = "我是无敌的！好吧，或许不是。但这样感觉不错。",
		ANIMAL_TRACK = "它会引导我找到新朋友。",
		ARMORGRASS = "浪费这么多易燃材料。",
		ARMORMARBLE = "如果我要去战斗，最好先做好保护工作。",
		ARMORWOOD = "现在，我可以挑战整个世界了！",
		ARMOR_SANITY = "像被包裹在烟雾里一样。",
		ASH =
		{
			GENERIC = "烧完后剩下的东西。真希望火还没灭。",
			REMAINS_EYE_BONE = "我猜这个长着眼睛的东西燃烧起来肯定相当壮观！",
			REMAINS_THINGIE = "不管这东西是什么，我都希望它能继续燃烧。",
		},
		AXE = "它非常锋利。",
		BABYBEEFALO =
		{
			GENERIC = "即使是牦牛宝宝，看上去也很丑。",
			SLEEPING = "醒醒！",
		},
		BACKPACK = "我可以往里面装比如说一百万个打火机。",
		BACONEGGS = "溏心蛋黄部分有点恶心，但是培根非常美味！",
		BANDAGE = "呃，一定要这么做吗？",
		BASALT = "太难凿碎了！",
		BEARDHAIR = "呃，这东西从哪儿来的？",
		BEDROLL_STRAW = "一股霉臭味。",
		BEE =
		{
			GENERIC = "很肥的蜜蜂，不过它的刺看起来很危险。",
			HELD = "满袋子的蜜蜂！",
		},
		BEEBOX =
		{
			GENERIC = "赶紧的，肥蜜蜂，赶紧给我产蜂蜜！",
			READY = "耶！我可以偷蜂蜜咯！",
		},
		BEEFALO =
		{
			FOLLOWER = "呃，你在跟着我吗？",
			GENERIC = "多么恶心的长毛野兽！",
			NAKED = "哈！他身上一根毛也没有了！",
			SLEEPING = "它们睡着的时候样子更傻。",
		},
		BEEFALOHAT = "我剃了他的毛，做成帽子戴在自己的头发上！",
		BEEFALOWOOL = "哈！我偷了他的毛！",
		BEEHIVE = "里面全是蜜蜂！",
		BEEMINE = "里面有蜜蜂。应该再往那里放点火。",
		BEEMINE_MAXWELL = "里面有蚊子。它们听起来可不太高兴。",
		BEEHAT = "这可以防止那些蜇人的蜜蜂接近我。",
		BERRIES = "红色浆果最好吃。",
		BERRIES_COOKED = "烤过之后的红色浆果味道更好。",
		BERRYBUSH =
		{
			BARREN = "吃屎吧，愚蠢的植物！",
			GENERIC = "嗯。浆果。",
			PICKED = "我想要更多的浆果！",
		},
		BIRDCAGE =
		{
			GENERIC = "鸟的牢笼！",
			OCCUPIED = "哈！你是我的了！",
			SLEEPING = "蠢鸟。醒醒！",
		},
		BIRDTRAP = "我会抓住那些臭鸟的。",
		BIRD_EGG = "闻起来像鸟屁股一样。",
		BIRD_EGG_COOKED = "呸。黄色的部分还没凝固。",
		BISHOP = "是主教！",
		BLOWDART_FIRE = "这是全世界我最喜欢的东西。",
		BLOWDART_SLEEP = "催眠吹箭可以更方便我点火。",
		BLOWDART_PIPE = "练好这个，给火吹风就不费劲了。",
		BLUEGEM = "呃。这玩意儿好丑。",
		BLUEPRINT = "这可以省去一些实验。",
		BLUE_CAP = "一股运动后的臭袜子的味道！",
		BLUE_CAP_COOKED = "我用火改变了它！",
		BLUE_MUSHROOM =
		{
			GENERIC = "愚蠢的蘑菇。",
			INGROUND = "嘿！你！给我起来！",
			PICKED = "也许有一天它会再长回来。",
		},
		BOARDS = "木板。它们也会燃烧，就和其他木材一样。",
		BONESTEW = "只需要给食物加把火，瞧！",
		BUGNET = "我能抓到虫子！",
		BUSHHAT = "太被动了！",
		BUTTER = "很美味，只是有点昆虫的味道",
		BUTTERFLY =
		{
			GENERIC = "飞走吧，蝴蝶！",
			HELD = "我想捏它。",
		},
		BUTTERFLYMUFFIN = "嘻嘻，看起来像蝴蝶被困在玛芬里面一样。",
		BUTTERFLYWINGS = "那只蝴蝶不会再飞了！",
		CAMPFIRE =
		{
			EMBERS = "啊哦。就快要熄灭了！",
			GENERIC = "我喜欢火。",
			HIGH = "烧吧！烧得再旺点！",
			LOW = "火太小了，真无聊。",
			NORMAL = "烧吧！",
			OUT = "呜呜呜。一切都结束了。",
		},
		CANE = "有了这个，走起路来容易多了！",
		CARROT = "呸。全是蔬菜。",
		CARROT_COOKED = "虽然还是一股蔬菜味，但经火烤过的味道要好些。",
		CARROT_PLANTED = "也许地下有它特别的胡萝卜朋友。",
		CARROT_SEEDS = "难吃的橙色蔬菜的种子。",
		CAVE_FERN = "看上去可以燃烧。",
		CHARCOAL = "嗯。火的味道。",
        CHESSJUNK1 = "上发条的马，已经死了",
        CHESSJUNK2 = "死去的发条主教",
        CHESSJUNK3 = "上发条的城堡，已经死了",
		CHESTER = "他毛茸茸的！",
		CHESTER_EYEBONE =
		{
			GENERIC = "盯着人看是很没礼貌的。",
			WAITING = "至少它不再盯着我了。",
		},
		COOKEDMEAT = "我吃过更好吃的。",
		COOKEDMONSTERMEAT = "还是很恶心。",
		COOKEDSMALLMEAT = "如果我想活下来的话，光开胃菜可是不够的。",
		CORN = "甜甜的蔬菜，好吃！",
		CORN_COOKED = "哦，这东西丢进火里会爆！",
		CORN_SEEDS = "玉米种子，会爆炸的玉米可是我最爱的蔬菜了。",
		CROW =
		{
			GENERIC = "我猜它是在等我死掉。",
			HELD = "聪明不起来了，对吗？",
		},
		CUTGRASS = "干草是很好的燃料，也可以用来合成其他东西。",
		CUTREEDS = "采下的芦苇是很好的燃料。也可以用来合成其他东西。",
		CUTSTONE = "完全是四四方方的，看着真舒服。",
		DEADLYFEAST = "连火也治不了这盘菜的卑鄙本性。",
		DEERCLOPS = "哇靠！",
		DEERCLOPS_EYEBALL = "不准再盯着我！",
		DIRTPILE = "是谁走的时候在森林里留下了这一堆泥土？",
		DIVININGROD =
		{
			COLD = "它在发出某种噪声。",
			GENERIC = "它全身上下都是电子垃圾。",
			HOT = "讨厌！别再哔哔哔地叫了！",
			WARM = "这东西越来越吵了。",
			WARMER = "一定很近了！",
		},
		DIVININGRODBASE =
		{
			GENERIC = "不知道这是用来干嘛的。看起来不像是能够燃烧的东西。",
			READY = "只需要用钥匙解锁就可以了。很遗憾，不是用火来解锁。",
			UNLOCKED = "它在发出呼呼的声音！",
		},
		DIVININGRODSTART = "我要用它搞点名堂出来。",
		DRAGONFRUIT = "它看上去有几分像火！",
		DRAGONFRUIT_COOKED = "现在看起来更像是把水果放在烈火中一样。",
		DRAGONFRUIT_SEEDS = "那个看起来像火一样的水果的种子。",
		DRAGONPIE = "做成派的火龙果？我的乖乖！",
		DRUMSTICK = "整天都在砰砰砰击鼓！",
		DRUMSTICK_COOKED = "我是用它来填饱肚子呢还是用它来敲鼓？",
		DURIAN = "呃，好臭！",
		DURIAN_COOKED = "呸，闻起来就像是东西煮坏了一样！",
		DURIAN_SEEDS = "臭水果的臭种子。",
		EARMUFFSHAT = "闻上去像是兔子的屁股。",
		EGGPLANT = "绝对不是鸟。",
		EGGPLANT_COOKED = "火让茄子变得更美味了。",
		EGGPLANT_SEEDS = "这些种子会长成一株植物还是一只小鸟？",
		STUFFEDEGGPLANT = "它仍然不是鸟，不过我在它里面塞了东西，现在看起来就像一只鸟！",
		DUG_BERRYBUSH = "怎么了，没有土了吗？",
		DUG_GRASS = "怎么了，没有土了吗？",
		DUG_MARSH_BUSH = "怎么了，没有土了吗？",
		DUG_SAPLING = "怎么了，没有土了吗？",
		EARMUFFS = "闻上去像是兔子的屁股。",
		EVERGREEN =
		{
			BURNING = "就是这样！烧吧！",
			BURNT = "真希望火还没灭。",
			CHOPPED = "世上又少了一棵树。",
			GENERIC = "看起来它会烧得很旺。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "就是这样！烧吧！",
			BURNT = "真希望火还没灭。",
			CHOPPED = "世上又少了一棵树。",
			GENERIC = "在火中结束吧！",
		},
		EYEPLANT = "它们像火一样迅速扩散。",
		FARMPLOT =
		{
			GENERIC = "唉，这是一堆土。",
			GROWING = "加把劲，土堆。给我提供食物！",
			NEEDSFERTILIZER = "蠢东西又需要施肥了。",
		},
		FEATHERHAT = "我就是涅槃的凤凰！",
		FEATHER_CROW = "乌鸦羽毛。它燃烧起来也许很难闻。",
		FEATHER_ROBIN = "红雀羽毛。它燃烧起来也许很难闻。",
		FEATHER_ROBIN_WINTER = "雪雀羽毛。它燃烧起来也许很难闻。",
		FEM_PUPPET = "她看起来已经被吓得半死。",
		FIREFLIES =
		{
			GENERIC = "真希望它们没有跑掉！",
			HELD = "它们就像是装在我口袋里的小火苗！",
		},
		FIREHOUND = "实际上我还挺喜欢这家伙的。",
		FIREPIT =
		{
			EMBERS = "啊哦。就快要熄灭了！",
			GENERIC = "我可以几个小时一直盯着它看。",
			HIGH = "烧吧！烧得再旺点！",
			LOW = "火太小了，真无聊。",
			NORMAL = "烧吧！",
			OUT = "我应该重新把火点燃。",
		},
		FIRESTAFF = "这绝对是我最喜爱的玩具。",
		FISH = "滑不溜秋的鱼！",
		FISHINGROD = "用钓鱼线和坠子来钓鱼。",
		FISHSTICKS = "所见即所得。瞧，炸鱼排。",
		FISHTACOS = "真是方便好拿的鱼肉玉米卷。",
		FISH_COOKED = "烤过之后的鱼没之前那么滑溜溜了。",
		FLINT = "可怜人的打火石。",
		FLOWER = "我可没有时间浪费在花朵上。",
		FLOWERHAT = "花环。可惜不是正在燃烧的花环。",
		FLOWER_EVIL = "呃，太难闻了。",
		FOLIAGE = "不错的燃料。",
		FOOTBALLHAT = "运动可不是那么容易。",
		FROG =
		{
			DEAD = "我让他尝到我的厉害了！",
			GENERIC = "他太潮湿了，烧不起来。",
			SLEEPING = "他们睡着的时候好可爱。",
		},
		FROGGLEBUNWICH = "也许我不会注意到三明治里面夹的是青蛙腿。",
		FROGLEGS = "它时不时的还在抽搐。太奇怪了。",
		FROGLEGS_COOKED = "是火让它停止抽搐的。火最好了。",
		FRUITMEDLEY = "好吃的水果！",
		GEARS = "这些会让它们动起来的。",
		GHOST = "我没法杀死一个本来就已经死了的人。",
		GOLDENAXE = "虽然它没法让树着火，但至少它会闪闪发光。",
		GOLDENPICKAXE = "虽然它没法让石头着火，但至少它会闪闪发光。",
		GOLDENPITCHFORK = "虽然它没法让地面着火，但至少它会闪闪发光。",
		GOLDENSHOVEL = "虽然它没法用来挖火坑，但至少它会闪闪发光。",
		GOLDNUGGET = "我该在哪里花掉这个。",
		GRASS =
		{
			BARREN = "它需要施肥。",
			BURNING = "烧吧！哇！",
			GENERIC = "是一丛易燃的草。",
			PICKED = "草茬没什么用。",
		},
		GREEN_CAP = "真乏味！",
		GREEN_CAP_COOKED = "我用火改变了它！",
		GREEN_MUSHROOM =
		{
			GENERIC = "愚蠢的蘑菇。",
			INGROUND = "嘿！你！给我起来！",
			PICKED = "也许有一天它会再长回来。",
		},
		GUNPOWDER = "哇哦！好闪亮！",
		HAMBAT = "很高兴认识你，我的肉友！",
		HAMMER = "我喜欢锋利的工具",
		HEALINGSALVE = "它烧着了！但是火在哪里？",
		HEATROCK =
		{
			COLD = "已经冷冰冰的了。",
			GENERIC = "火会让这东西变暖！",
			HOT = "看看它是怎么发光的！",
			WARM = "既没有火焰，也没有真正的热量...有什么好玩的？",
		},
		HOMESIGN = "少读！多烧！",
		HONEY = "甜蜜而美味！",
		HONEYCOMB = "像蜡一样。",
		HONEYHAM = "烈火、火腿和蜂蜜是绝配。",
		HONEYNUGGETS = "蜂蜜和肉块遇到最可爱的火，就成了蜂蜜包肉。",
		HORN = "我可以听到里面有那些多毛动物的声音。",
		HOUND = "真是个混蛋！",
		HOUNDMOUND = "啊哦，我不喜欢那东西的样子。",
		HOUNDBONE = "恶心。",
		ICEBOX = "这是火的对立面。",
		ICEHOUND = "可恶！好冷！",
		INSANITYROCK =
		{
			ACTIVE = "是我看花眼了吗？",
			INACTIVE = "看上去不像是能燃烧的。太无趣了。",
		},
		JAMMYPRESERVES = "舔，舔，舔！五秒搞定。",
		KABOBS = "火烤的肉，用签子串起！",
		KILLERBEE =
		{
			GENERIC = "我喜欢那只蜜蜂的样子。",
			HELD = "嗡嗡！",
		},
		KNIGHT = "是马儿耶！",
		KOALEFANT_SUMMER = "我们会成为很好的朋友的！",
		KOALEFANT_WINTER = "毫无疑问，他看上去很暖和...",
		KRAMPUS = "退后，你这个大混蛋！",
		KRAMPUS_SACK = "我有新的包包了！",
		LEIF = "他看上去一点就着！",
		LEIF_SPARSE = "他看上去一点就着！",
		LIGHTNING_ROD =
		{
			CHARGED = "哇，通体发光但没有火。",
			GENERIC = "所有闪电都将汇集到这里！",
		},
		LITTLE_WALRUS = "他看上去很美味。",
		LIVINGLOG = "它看起来很烦躁。",
		LOCKEDWES = "他被那些卑鄙的雕像给困住了！",
		LOG =
		{
			BURNING = "烧吧，木头，烧烧烧烧吧！",
			GENERIC = "木头！容易燃烧的木头！太好了！",
		},
		LUREPLANT = "我打赌一把火就可以解决它。",
		LUREPLANTBULB = "它现在归我了。",
		MALE_PUPPET = "他看起来已经被吓得半死。",
		MANDRAKE =
		{
			DEAD = "为什么这植物长着一张脸？",
			GENERIC = "那株植物不太正常",
			PICKED = "现在它太吓人了！",
		},
		COOKEDMANDRAKE = "火都没能把它的脸烧掉。这让我有点不安。",
		MANDRAKESOUP = "将它熬成汤后，终于看不到它的脸了。",
		MARBLE = "它很重！",
		MARBLEPILLAR = "不知道其余的烧毁了没。",
		MARBLETREE = "世上最糟糕的树，居然不能燃烧。",
		MARSH_BUSH =
		{
			BURNING = "燃烧吧，刺木！",
			GENERIC = "它看上去很尖锐。",
			PICKED = "这些刺木扎得人很痛！",
		},
		MARSH_PLANT = "彻头彻尾的植物。",
		MARSH_TREE =
		{
			BURNING = "就是这样！烧吧！",
			BURNT = "真希望火还没灭。",
			CHOPPED = "现在没那么扎手了，对吧？",
			GENERIC = "它看起来很危险！",
		},
		MAXWELL = "他太傲慢了。",
		MAXWELLHEAD = "他显然很爱讲话。",
		MAXWELLLIGHT = "一点都不好玩。它们可以自己把自己点燃。",
		MAXWELLLOCK = "现在我只需要一把钥匙。",
		MAXWELLTHRONE = "看上去很黏。",
		MEAT = "有火的话，味道更好！",
		MEATBALLS = "将肉做成丸子，用火烹饪一下就成了美味。",
		MEATRACK =
		{
			DONE = "已经干了！",
			DRYING = "拜托，肉块，快点干吧！",
			GENERIC = "我想要晾些肉干！",
		},
		MEAT_DRIED = "虽然有点难嚼，但还不错。",
		MERM = "又软又湿，真恶心。",
		MERMHEAD = "让你这么臭，这就是你的下场！",
		MERMHOUSE = "没人会在意它是否被烧毁。",
		MONSTERLASAGNA = "面条、肉和一团一团的毛发。真恶心。",
		MONSTERMEAT = "恶心。到处都是毛。",
		MONSTERMEAT_DRIED = "干的，闻起来怪怪的。",
		MOSQUITO =
		{
			GENERIC = "真烦人！",
			HELD = "让你那张嘴离我远点！",
		},
		MOSQUITOSACK = "在沉闷厚重的气流中，血液必须沸腾起来。",
		MOUND =
		{
			DUG = "幸好是它不是我。",
			GENERIC = "我打赌里面全是死去的东西。",
		},
		NIGHTLIGHT = "像火焰一样，不过是紫色的！",
		NIGHTMAREFUEL = "恶心，还是温热的！",
		NIGHTSWORD = "好像我的梦境会对现实事物造成伤害！",
		NITRE = "里面有一些小爆炸。",
		ONEMANBAND = "我还可以制作烟火！",
		PANDORASCHEST = "有点俗气。",
		PANFLUTE = "音乐很无聊。",
		PAPYRUS = "我肯定它能够燃烧！",
		PENGUIN = "跑掉的小小舞蹈家。",
		PERD = "臭鸟！别靠近我美味的浆果！",
		PEROGIES = "用火来封口的美味饺子。",
		PETALS = "愚蠢的花。几乎是毫无用处。",
		PETALS_EVIL = "好恶心，太黏了。",
		PICKAXE = "它很尖锐。",
		PIGGYBACK = "我用猪屁股做了个背包！",
		PIGHEAD = "比起那家伙，我的处境还不算太糟。",
		PIGHOUSE =
		{
			FULL = "他在里面干一些猪的事情。",
			GENERIC = "这些猪在建筑方面的品味真的很有问题",
			LIGHTSOUT = "你个蠢货！让我进去！",
		},
		PIGKING = "呸。懒汉一个。",
		PIGMAN =
		{
			DEAD = "真想尝尝它们的味道如何。",
			FOLLOWER = "讨厌。它在跟着我。",
			GENERIC = "呃。真是臭死了。",
			GUARD = "他可不是我的Boss！",
			WEREPIG = "出招吧，小猪！",
		},
		PIGSKIN = "哈哈。猪屁股。",
		PIGTORCH = "这些猪可真知道享受。",
		PINECONE = 
		{
		    GENERIC = "嘿，你好啊，大树种子。",
		    PLANTED = "你很快就会长成一棵真正的树的。",
		},
		PITCHFORK = "三倍那么尖。",
		PLANTMEAT = "真恶心，又黏又滑。",
		PLANTMEAT_COOKED = "火可以让一切东西变得更好。",
		PLANT_NORMAL =
		{
			GENERIC = "如果没得选的话，我会吃它的。",
			GROWING = "快点长，你个愚蠢的植物！",
			READY = "我的乖乖。新鲜的蔬菜。",
		},
		POMEGRANATE = "为什么它有这么多部分？",
		POMEGRANATE_COOKED = "火总是让东西变得更好。",
		POMEGRANATE_SEEDS = "一颗小小的种子。看上去和果实里面的东西很像。",
		POOP = "呕... 真恶心。不过很有用。",
		PUMPKIN = "我很好奇它用火烤后会变成什么样子。",
		PUMPKINCOOKIE = "小甜饼！！！",
		PUMPKIN_COOKED = "在外面用火烤出来的东西真的挺不错的。",
		PUMPKIN_LANTERN = "里面的火真是太神奇了！",
		PUMPKIN_SEEDS = "在蔬菜里，南瓜是火最好的朋友，而这就是南瓜种子。",
		PURPLEGEM = "好奇异！",
		RABBIT =
		{
			GENERIC = "他看上去很美味。",
			HELD = "想抓住他的时候就得手了！",
		},
		RABBITHOLE = "蠢兔子，快出来，我要吃了你。",
		RAINOMETER = "雨火不两立。切！",
		RATATOUILLE = "蔬菜。好多的蔬菜。",
		RAZOR = "我为什么做了这玩意？",
		REDGEM = "真漂亮！",
		RED_CAP = "我喜欢这颜色。",
		RED_CAP_COOKED = "我用火改变了它！",
		RED_MUSHROOM =
		{
			GENERIC = "好漂亮！",
			INGROUND = "嘿！你！给我起来！",
			PICKED = "也许有一天它会再长回来。",
		},
		REEDS =
		{
			BURNING = "烧吧！耶！",
			GENERIC = "这是一丛可以烧着的芦苇",
			PICKED = "我拿芦苇茬毫无办法。",
		},
        RELIC = 
        {
            GENERIC = "老古董。",
            BROKEN = "零七八碎，七零八碎。",
        },
        RUBBLE = "残破的家具。",
		RESEARCHLAB = "即使有些东西我不知道，这也只是暂时的。",
		RESEARCHLAB2 = "即使有些东西我不知道，这也只是暂时的。",
		RESEARCHLAB3 = "它散发着黑暗而强大的能量。",
		RESURRECTIONSTATUE = "那是我的保险单。",
		RESURRECTIONSTONE = "我是不是应该去摸一下它？",
		ROBIN =
		{
			GENERIC = "一只红雀。火一样的颜色，但不是凤凰。",
			HELD = "它在我口袋里很舒服。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "它看起来好冷。我猜它肯定想烤火。",
			HELD = "它的羽毛好软。",
		},
		ROBOT_PUPPET = "它看起来已经被吓得半死。",
		ROCK_LIGHT =
		{
			GENERIC = "裹了石皮的熔岩坑。",
			OUT = "噢，它凉下来了。",
			LOW = "熔岩在冷却。",
			NORMAL = "一个火塘！",
		},
		ROCKS = "可以用这些东西来修建因努伊特石堆吗？",
        ROOK = "这是一个城堡！",
        ROPE = "我可以用这个来绑什么？",
		ROTTENEGG = "好恶心！为什么？为什么会这样？！",
		SANITYROCK =
		{
			ACTIVE = "我想知道这些标记有什么含义。",
			INACTIVE = "它去了哪里？",
		},
		SAPLING =
		{
			BURNING = "烧吧！耶！",
			GENERIC = "我应该采摘它。",
			PICKED = "可怜的小树苗。",
		},
		SEEDS = "耕种最无聊了。",
		SEEDS_COOKED = "现在不能用来耕种了。",
		SEWING_KIT = "但是搞破坏要有趣得多！",
		SHOVEL = "不太适合用来战斗。",
		SILK = "嗯。好光滑。",
		SKELETON = "天啊。真希望它是在荣耀的火焰中死去的。",
		SKULLCHEST = "哦哦哦，太可怕了！",
		SMALLBIRD =
		{
			GENERIC = "我觉得吧，虽然不太像凤凰，但还是很可爱。",
			HUNGRY = "你饿了吗？",
			STARVING = "好好好！我知道了，你饿了。",
		},
		SMALLMEAT = "有火的话，味道更好！",
		SMALLMEAT_DRIED = "虽然有点难嚼，但还不错。",
		SPEAR = "感受我的愤怒吧！",
		SPIDER =
		{
			DEAD = "哈！尝到我的厉害了吧！",
			GENERIC = "他很讨厌。我应该杀了他。",
			SLEEPING = "我可以干掉他。",
		},
		SPIDERDEN = "太让人厌恶了。",
		SPIDEREGGSACK = "一大堆让人恶心的小蜘蛛。",
		SPIDERGLAND = "好恶心，又黏又臭！",
		SPIDERHAT = "谁是你妈妈！",
		SPIDERQUEEN = "用火烧死它！",
		SPIDER_WARRIOR =
		{
			DEAD = "他活该。",
			GENERIC = "也许我可以...用火烧死它。",
			SLEEPING = "也许我不应该去打扰那家伙。",
		},
		SPOILED_FOOD = "至少它仍然是可以燃烧的。",
		STATUEHARP = "好漂亮的雕像。弄坏了就可惜了。",
		STATUEMAXWELL = "我开始讨厌那家伙了。",
		STINGER = "好扎手！",
		STRAWHAT = "一顶稻草做的帽子。但是我觉得，它本来可以成为引火物的。",
		SUNKBOAT = "它太远了，我都烧不到它！",
		SWEATERVEST = "虽然没有火焰背心那么好，但还凑合。",
		TAFFY = "甜食烧起来感觉很棒，不过我应该把它吃下去，而不是烧掉。",
		TALLBIRD = "我觉得它不想和我交朋友。",
		TALLBIRDEGG = "它喜欢火吗？",
		TALLBIRDEGG_COOKED = "经火烤之后好多了。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "火需要再旺点！",
			GENERIC = "现身吧，我的凤凰！",
			HOT = "火是不是太旺了？",
			LONG = "这需要多长时间？",
			SHORT = "我都等得不耐烦了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "可以用火来烤那个蛋！",
			PICKED = "巢是空的。",
		},
		TEENBIRD =
		{
			GENERIC = "我感觉他能理解我。",
			HUNGRY = "他的确吃得多。",
			STARVING = "不要看我！自己去找吃的。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我只想看着这个世界烧起来。",
			GENERIC = "我喜欢这些符号发亮的样子。",
			LOCKED = "需要以某种方式解锁。",
			PARTIAL = "我在创造怪物！",
		},
		TELEPORTATO_BOX = "感觉暖暖的。",
		TELEPORTATO_CRANK = "这部分有什么用？",
		TELEPORTATO_POTATO = "也许我可以把它熔化成更漂亮的形状。",
		TELEPORTATO_RING = "这么珍贵的东西烧了太可惜了！",
		TENT = "我可是获得过所有勋章的女童子军。",
		TENTACLE = "一点都不讨人喜欢。",
		TENTACLESPOTS = "呃，好恶心。",
		TENTACLESPIKE = "它又尖又黏。",
		TENTACLE_PILLAR = "它在颤抖。",
		TENTACLE_PILLAR_ARM = "啊，它们想要拥抱！",
		TENTACLE_GARDEN = "我听到有轻微的挖土的声音。",
		TOPHAT = "高礼帽和打火机，真是绝配。",
		TORCH = "火焰太漂亮了。",
		TRAP = "虽然有点被动攻击的意思，但有用就行。",
		TRAP_TEETH = "有火就更好了。",
		TRAP_TEETH_MAXWELL = "什么样的混蛋会在地上放这东西？",
		TREASURECHEST = "可以帮我装东西的箱子。",
		TRINKET_1 = "我猜，能够把这些东西熔掉的火肯定温度很高。",
		TRINKET_10 = "我觉得假牙也可以烧得很旺。",
		TRINKET_11 = "哦，不知道他有没有火焰喷射器！",
		TRINKET_12 = "全部萎缩了，就好像它过于靠近火一样。",
		TRINKET_2 = "廉价的假玩意儿。它甚至也许都不能当柴火烧。",
		TRINKET_3 = "那是个死结。有火的话，谁还需要刀啊？",
		TRINKET_4 = "他看起来像是经过烈火锻造的。",
		TRINKET_5 = "看看那些迷你推进器。真是惊人的爆发力！",
		TRINKET_6 = "连一点火花都没有。",
		TRINKET_7 = "还是纵火比较有趣。",
		TRINKET_8 = "我从来不喜欢用水洗澡。",
		TRINKET_9 = "你可以在拉链上擦火柴，但没法在纽扣上擦。",
		TRUNKVEST_SUMMER = "现在我要永远和我的朋友待在一起了。",
		TRUNKVEST_WINTER = "虽然不像火焰那样温暖，但还不错！",
		TRUNK_COOKED = "我还是不确定到底要不要吃它。",
		TRUNK_SUMMER = "其实，他有一部分还是挺惹人喜爱的。",
		TRUNK_WINTER = "又软又黏！",
		UMBRELLA = "我喜欢这颜色！",
		WAFFLES = "你好，华夫饼！",
		WALL_HAY = "看起来是一点就燃！",
		WALL_HAY_ITEM = "嗯。不知道这些东西会不会烧起来。",
		WALL_STONE = "嗯。我觉得还不错。",
		WALL_STONE_ITEM = "没想到这些东西这么重。",
		WALL_RUINS = "坏蛋会来把它吹倒的！",
		WALL_RUINS_ITEM = "我的口袋装得下它们吗？",
		WALL_WOOD = "那东西很容易着火的。",
		WALL_WOOD_ITEM = "我讨厌躲起来。",
		WALRUS = "别跟着我！",
		WALRUSHAT = "我蛮喜欢这帽子的样式。",
		WALRUS_CAMP =
		{
			EMPTY = "我才不会进去那里。讨厌！",
			GENERIC = "为什么其他人的房子都比我的漂亮？",
		},
		WALRUS_TUSK = "吧唧吧唧吧唧。",
		WASPHIVE = "我最好保持点距离。",
		WETGOOP = "怎么会出错呢？！我把它放进了火里，而且做了一切该做的事。",
		WINTERHAT = "这对我来说还不够暖和。",
		WINTEROMETER = "如果它能测量火的话会更好。",
		WORMHOLE =
		{
			GENERIC = "用棍子戳一下！",
			OPEN = "不知道他喜不喜欢辛辣的食物？",
		},
		ACCOMPLISHMENT_SHRINE = "我讨厌那个箭头！",        		
		LIVINGTREE = "它也许是活的，不过它还是会燃烧。",
		ICESTAFF = "太太太太无趣了。",
	},
	DESCRIBE_TOODARK = "我需要更多的光！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "呃。嘎嘣脆。",
	},
}
