return {


	ACTIONFAIL_GENERIC = "Io non posso fare niente di buono.",
	ANNOUNCE_ADVENTUREFAIL = "Non tutte le morti sono uguali.",
	ANNOUNCE_BOOMERANG = "Ahi! Quello era il karma.",
	ANNOUNCE_CHARLIE = "Demone! Mostrati!",
	ANNOUNCE_CHARLIE_ATTACK = "Mi hanno attaccato!",
	ANNOUNCE_COLD = "Sono raffreddato fino all'osso.",
	ANNOUNCE_CRAFTING_FAIL = "Mi mancano i materiali necessari.",
	ANNOUNCE_DUSK = "L'oscurità giungerà presto. Mi devo preparare.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Gnam!",
		PAINFUL = "Quello non era commestibile.",
		SPOILED = "Quel cibo era quasi alla fine del suo ciclo di vita.",
		STALE = "Era stantio?",
	},
	ANNOUNCE_ENTER_DARK = "L'oscurità mi ha inghiottito.",
	ANNOUNCE_ENTER_LIGHT = "E la luce fu.",
	ANNOUNCE_HOUNDS = "I segugi stanno abbaiando.",
	ANNOUNCE_HUNGRY = "Sono piena di vacuità.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Sento la presenza della bestia nelle vicinanze.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Questo sentiero non porta da nessuna parte.",
	ANNOUNCE_INV_FULL = "Non posso trasportare più!",
	ANNOUNCE_KNOCKEDOUT = "Perbacco, che male! Eppure, ancora una volta mi sveglio alla vita.",
	ANNOUNCE_NOHUNGERSLEEP = "Il mio stomaco è vuoto come il mio cuore, non riesco a dormire adesso.",
	ANNOUNCE_PECKED = "Stai mettendo a prova la mia pazienza.",
	ANNOUNCE_QUAKE = "La terra trema. Mi ingoierà tutto?",
	ANNOUNCE_THORNS = "Ahi! Pungente, come me.",
	ANNOUNCE_TORCH_OUT = "L'oscurità è tornata!",
	ANNOUNCE_TRAP_WENT_OFF = "Oh, bene.",
	ANNOUNCE_WORMHOLE = "Emergo in questo mondo una volta ancora.",
	ANNOUNCE_CANFIX = "\nPenso di poterlo aggiustare!",
	ANNOUNCE_ACCOMPLISHMENT = "Tutto questo è temporaneo.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Anche questo sarà dimenticato, un giorno.",
	BATTLECRY =
	{
		GENERIC = "La morte ti troverà!",
		PIG = "Lascia che la morte ti accolga!",
		PREY = "Soffri, verme!",
		SPIDER = "Ti manderò all'altro mondo!",
		SPIDER_WARRIOR = "Sarò la tua fine!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Vivrai. Per adesso.",
	},
	DESCRIBE =
	{
		WORMLIGHT = "Un lieve ronzio proviene da esso.",
		WORM =
		{
		    PLANT = "Sembra fuori luogo.",
		    DIRT = "C'è qualcosa là?",
		    WORM = "Viene dalla profondità.",
		},
		EEL = "Un'anguilla.",
		EEL_COOKED = "Un'anguilla che è stata cucinata.",
		UNAGI = "Sembra più appetitoso in questo modo.",
		EYETURRET = "Non so perché mi aiuta.",
		EYETURRET_ITEM = "Credo che lo devo piazzare.",
		MINOTAURHORN = "Tutto ciò che rimane di una bestia una volta grandiosa.",
		MINOTAURCHEST = "Ma che corna magnifiche hai!",
		THULECITE_PIECES = "Frammenti di un materiale potente.",
		POND_ALGAE = "Alcune alghe.",
		GREENSTAFF = "Riesco a vedere la scintilla del potere racchiuso nel profondo.",
		POTTEDFERN = "Vive in una gabbia.",

		THULECITE = "La sua presenza segna il confine dell'ignoto.",
		ARMORRUINS = "Un rinvio della morte.",
		RUINS_BAT = "Ho il potere degli antichi nelle mie mani.",
		RUINSHAT = "Abigail avrebbe amato questa corona.",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "Non so cosa si celi nell'ombra.",	
			WARN = "Riesco a sentire gli occhi indiscreti.",	
			WAXING = "Si avvicinano.", 
			STEADY = "Sono tutti intorno a me!", 
			WANING = "Credo che se ne stiano andando.", 
			DAWN = "È quasi finita.", 
			NOMAGIC = "Sono sola.", 
		},
		BISHOP_NIGHTMARE = "Il tempo ha vinto questa battaglia.",
		ROOK_NIGHTMARE = "Il tempo erode tutto.",
		KNIGHT_NIGHTMARE = "Un'altra battaglia persa da tempo.",
		MINOTAUR = "Deve sentirsi solo. Intrappolato in una tale gabbietta.",	
		SPIDER_DROPPER = "L'oscurità ha cancellato il colore della loro pelliccia.",	
		NIGHTMARELIGHT = "Tira il potere da sotto.",	
		RELIC = "Una visione del passato.",	
		RUINS_RUBBLE = "Un mucchio di sogni infranti.",	
		MULTITOOL_AXE_PICKAXE = "Un attrezzo dai molteplici usi.",	
		GREENGEM = "I difetti sono le sue caratteristiche più belle.",
		ORANGESTAFF = "Ogni volta che lo uso, muoio ed poi rinasco.",	
		YELLOWAMULET = "Una breve luce nella mia oscura vita.",	
		GREENAMULET = "Un lampo di genio!",	

		SLURPER = "Ah, per essere così semplice.",
		SLURPER_PELT = "Un sacchetto della fame vuoto.",
		ARMORSLURPER = "Un vestito vivente, aderente e tetro.",
		ORANGEAMULET = "Un sollievo temporaneo dal lavoro ingrato.",
		YELLOWSTAFF = "Il bastone è più contorto della mia anima.",
		YELLOWGEM = "Mi ricorda mia madre.",
		ORANGEGEM = "Queste cose mi portavano felicità.",
		TELEBASE = 
		{
			VALID = "L'energia lo attraversa.",
			GEMS = "La concentrazione è così inanimata.",
		},
		GEMSOCKET = 
		{
			VALID = "La gemma lo ha focalizzato.",
			GEMS = "Sembra così vuoto.",
		},
		STAFFLIGHT = "Posso quasi creare un minuscolo sistema solare.",
		RESEARCHLAB4 = "Questo è solo un passo dalla follia.",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="È grazioso.",
			LONG = "Era il fiore di mia sorella. Se ne è andata lontano.",
			MEDIUM = "Posso percepire la presenza di Abigail sempre più forte.",
			SOON = "Abigail è quasi qui!",
			HAUNTED_POCKET = "Abigail è pronta a giocare, ma ha bisogno di un po' di spazio.",
			HAUNTED_GROUND = "Ho bisogno di mostrare ad Abigail come giocare.",

		},

        ANCIENT_ALTAR = "È pieno di echi della morte.",
        ANCIENT_ALTAR_BROKEN = "Sento gli echi dolorosi della morte.",
        ANCIENT_STATUE = "Non molto attraente.",

        LICHEN = "Come riesce a crescere così?",
		CUTLICHEN = "Fugace, proprio come la vita.",
		CAVE_BANANA = "Le bucce sembrano pericolose.",
		CAVE_BANANA_COOKED = "La poltiglia di banana riscaldata è molto meglio.",
		CAVE_BANANA_TREE = "Povera pianta rinchiusa lontana dal sole.",
		ROCKY = "Quali terribili scene hanno visto.",


		BLUEAMULET = "Un abbraccio agghiacciante e familiare.",
		PURPLEAMULET = "È trasudante.",
		TELESTAFF = "Potrei scappare se fosse più potente.",
		MONKEY = "Vivere senza l'onere dell'intelligenza deve essere piacevole.",
		MONKEYBARREL = "È sudicio.",
		MONSTERLASAGNA = "Il maligno cotto rimane maligno, anche nella lasagna.",
		HOUNDSTOOTH="Tirato fuori dalla radice.",
		ARMORSNURTLESHELL="Ora posso nascondermi dai miei problemi.",
		BAT="Una creatura della notte.",
		BATBAT = "Un'arma incantata. Che emozione!",
		BATWING="Se solo potessi volare via.",
		BATWING_COOKED="Una volta avevano detenuto un grandioso potenziale.",
		BEDROLL_FURRY="Mi avvolgerò nella pelle pelosa dei caduti.",
		BUNNYMAN="Che vite interiori tormentate devono avere.",
		FLOWER_CAVE="Sembra fragile.",
		FLOWER_CAVE_DOUBLE="Sembra fragile.",
		FLOWER_CAVE_TRIPLE="Sembra fragile.",
		GUANO="Il sottoprodotto inevitabile della vita.",
		LANTERN="Illumina la via nell'oscurità.",
		LIGHTBULB="Sta bruciando lentamente.",
		MANRABBIT_TAIL="Contiene la propria essenza di pelo morbidoso.",
		MUSHTREE_TALL  ="Questi sono degli strani alberi.",
		MUSHTREE_MEDIUM="Sembra un cappello marcio.",
		MUSHTREE_SMALL ="Gli gnometti vivono in questi?",
		RABBITHOUSE="Non è così commestibile come sembra.",
		SLURTLE="Insegue le rocce senza pensieri.",
		SLURTLE_SHELLPIECES="Pezzi di sogni di bavuga infranti.",
		SLURTLEHAT="Dubito che mi aiuterà più di quello che ha fatto per il suo proprietario originario.",
		SLURTLEHOLE="Le bavughe escono quando diventano troppo grandi per stare là.",
		SLURTLESLIME="Brilla con viscida anticipazione.",
		SNURTLE="Quella ha un guscio più grande.",
		SPIDER_HIDER="Un ragno vile.",
		SPIDER_SPITTER="Sta masticando qualcosa.",
		SPIDERHOLE="È infestato.",
		STALAGMITE="La terra rinuncia alla sua taglia.",
		STALAGMITE_FULL="La terra rinuncia alla sua taglia.",
		STALAGMITE_LOW="La terra rinuncia alla sua taglia.",
		STALAGMITE_MED="La terra rinuncia alla sua taglia.",
		STALAGMITE_TALL="La terra raggiunge le altezze.",
		STALAGMITE_TALL_FULL="La terra raggiunge le altezze.",
		STALAGMITE_TALL_LOW="La terra raggiunge le altezze.",
		STALAGMITE_TALL_MED="La terra raggiunge le altezze.",

		TURF_CARPETFLOOR = "Un po' di terreno.",
		TURF_CHECKERFLOOR = "Un po' di terreno.",
		TURF_DIRT = "Un po' di terreno.",
		TURF_FOREST = "Un po' di terreno.",
		TURF_GRASS = "Un po' di terreno.",
		TURF_MARSH = "Un po' di terreno.",
		TURF_ROAD = "Un po' di terreno.",
		TURF_ROCKY = "Un po' di terreno.",
		TURF_SAVANNA = "Un po' di terreno.",
		TURF_WOODFLOOR = "Un po' di terreno.",

		TURF_CAVE="Un po' di terreno.",
		TURF_FUNGUS="Un po' di terreno.",
		TURF_SINKHOLE="Un po' di terreno.",
		TURF_UNDERROCK="Un po' di terreno.",
		TURF_MUD="Un po' di terreno.",

		POWCAKE = "Avrei dovuto essere disperata.",		
		CAVE_ENTRANCE = 
		{
			GENERIC="Qualcuno sta cercando di tenere a bada il sottosuolo.",
			OPEN = "Un grande male si nasconde sotto la superficie.",
		},
        CAVE_EXIT = "La superficie chiama.",
		BOOMERANG = "La morte ritorna al mittente.",
		MAXWELLPHONOGRAPH = "Vogliamo fare una danza macabra?",
		ABIGAIL = "È mia sorella gemella, Abigail.",
		PIGGUARD = "Questo maialetto sembra cattivo.",
		ADVENTURE_PORTAL = "Che terrore tecnologico è questo?",
		AMULET = "Mi chiedo a chi appartenesse.",
		ANIMAL_TRACK = "Tracce della bestia.",
		ARMORGRASS = "Prolungamento dell'inevitabile.",
		ARMORMARBLE = "Ferma i pugnali che pugnalano il mio cuore.",
		ARMORWOOD = "Potrei tenere a bada l'inevitabile un po' più a lungo con questo.",
		ARMOR_SANITY = "Un modo perfettamente sicuro per impazzire.",
		ASH =
		{
			GENERIC = "Tutto quello che resta dopo un altro bel fuoco.",
			REMAINS_EYE_BONE = "L'ossocchio si è incenerito quando mi sono teletrasportata!",
			REMAINS_THINGIE = "Questo è stato un qualcosa prima di essere carbonizzato.",
		},
		AXE = "Uno strumento per l'industria e per l'omicidio.",
		BABYBEEFALO = "Goditi la gioventù. Presto imparerai gli orrori del mondo reale.",
		BACKPACK = "Un sacco. Ora posso portare ancora più peso.",
		BACONEGGS = "Una colazione bilanciata per iniziare un altro miserabile giorno.",
		BANDAGE = "Finirà solo per farsi male di nuovo.",
		BASALT = "Cercare di romperlo sarebbe inutile.",
		BEARDHAIR = "È semplicemente odioso.",
		BEDROLL_STRAW = "Il sonno non è altro che una morte temporanea.",
		BEE =
		{
			GENERIC = "Starei alla larga da quel pungiglione.",
			HELD = "Non ti muovere, piccolina.",
		},
		BEEBOX =
		{
			GENERIC = "Devono faticare in modo che io possa rubare.",
			READY = "Le loro fatiche sono state fruttuose!",
		},
		BEEFALO =
		{
			FOLLOWER = "Mi segue nel suo destino.",
			GENERIC = "Quali pensieri folli si celano dietro quegli occhi.",
			NAKED = "La sua nudità è ora in mostra.",
			SLEEPING = "Che incubi deve avere.",
		},
		BEEFALOHAT = "Mi coprirò la testa.",
		BEEFALOWOOL = "Da qualche parte, un mufalo è nudo e freddo.",
		BEEHAT = "Questo mi proteggerà da quei ronzii felici. E dalle punture.",
		BEEHIVE = "Un misero alveare di feccia e polline.",
		BEEMINE = "Sono ancora vivi lì dentro. Poverini.",
		BERRIES = "Queste bacche sono acide.",
		BERRIES_COOKED = "Un sapore più equilibrato, ma non dureranno a lungo.",
		BERRYBUSH =
		{
			BARREN = "È sterile.",
			GENERIC = "Una merenda, magari?",
			PICKED = "Dovrò aspettare.",
		},
		BIRDCAGE =
		{
			GENERIC = "Alcuni di noi possono vedere le nostre gabbie.",
			OCCUPIED = "Ora è più felice.",
			SLEEPING = "È morto? No. Sta solo dormendo.",
		},
		BIRDTRAP = "Bastoni e seta diventati letali.",
		BIRD_EGG = "Tanta speranza, infranta.",
		BIRD_EGG_COOKED = "Nessun pennuto verrà mai fuori da questo.",
		BISHOP = "Per che cosa prega?",
		BLOWDART_SLEEP = "Non è una dormita eterna, solo una temporanea.",
		BLOWDART_PIPE = "Soffio da questa estremità, e il dolore viene fuori dall'altra.",
		BLOWDART_FIRE = "Devo incendiare il mondo?",
		BLUEGEM = "Blu come... ehm... un pennuto triste?",
		BLUEPRINT = "Chiunque lo ha disegnato è probabilmente morto.",
		BLUE_CAP = "Un fungo per preservare la monotonia.",
		BLUE_CAP_COOKED = "Tutto è malleabile.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Ammuffito.",
			INGROUND = "Mi nasconderei anch'io, se potessi.",
			PICKED = "Raccolto.",
		},
		BOARDS = "Ancora più spaventoso per gli alberi.",
		BONESTEW = "Morirono. E così li misi in uno stufato.",
		BUGNET = "Una prigione per minuscoli insetti.",
		BUSHHAT = "Oh, per scomparire.",
		BUTTER = "Non me lo aspettavo.",
		BUTTERFLY =
		{
			GENERIC = "Graziosa, ma di vita breve.",
			HELD = "Ho la sua vita nelle mie mani.",
		},
		BUTTERFLYWINGS = "La farfalla non può sollevarsi più di così.",
		BUTTERFLYMUFFIN = "Vediamo come esci da questa trappola zuccherina!",
		CAMPFIRE =
		{
			EMBERS = "L'oscurità si profila.",
			GENERIC = "Potrei sopravvivere a questa notte!",
			HIGH = "Una visione dell'inferno!",
			LOW = "L'oscurità invade.",
			NORMAL = "È un incendio.",
			OUT = "Quello non è un buon segno.",
		},
		CANE = "Posso arrivare ovunque più velocemente.",
		CARROT = "È una carota.",
		CARROT_COOKED = "È una carota che è passata attraverso il guanto di sfida del fuoco.",
		CARROT_PLANTED = "È una carota nel terreno.",
		CARROT_SEEDS = "Un giorno, questo seme sarà una carota.",
		CAVE_FERN = "Un tocco di colore nel buio.",
		CHARCOAL = "È freddo e morto, come il mio cuore.",
        CHESSJUNK1 = "Fredda e morta vita artificiale.",
        CHESSJUNK2 = "Vita artificiale morta e gelida.",
        CHESSJUNK3 = "Fredda e morta vita artificiale.",
		CHESTER = "Un batuffolo di vacuità.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Sta guardando nella mia anima.",
			WAITING = "Non c'è niente di così dormiente come... l'attesa.",
		},
		COOKEDMANDRAKE = "È stata una buona morte. Sarà delizioso.",
		COOKEDMEAT = "Il sangue è stato cucinato.",
		COOKEDMONSTERMEAT = "Il maligno cotto rimane pur sempre maligno.",
		COOKEDSMALLMEAT = "Il fuoco lo ha purificato.",
		CORN = "Potrei raccontare una storiella sulle corna, ma mi asterrò.",
		CORN_COOKED = "Questo mais non ha potuto sopportare il calore.",
		CORN_SEEDS = "Già, è un seme.",
		CROW =
		{
			GENERIC = "Togli il becco dal mio cuore!",
			HELD = "Lui è mio.",
		},
		CUTGRASS = "Mi piace uccidere le cose piccole.",
		CUTREEDS = "Mi piace tagliuzzare le cose.",
		CUTSTONE = "È il meglio per contrassegnare le lapidi.",
		DEADLYFEAST = "Questo, il mio banchetto finale.",
		DEERCLOPS = "La morte incarnata!",
		DEERCLOPS_EYEBALL = "Che orrori deve vedere.",
		DEPLETED_GRASS =
		{
			GENERIC = "I resti di un ciuffo d'erba.",
		},
		DIRTPILE = "Oh guarda. Altro terriccio.",
		DIVININGROD =
		{
			COLD = "La fonte è distante.",
			GENERIC = "È sempre alla ricerca della sua metà perduta.",
			HOT = "Qualcosa di maligno è qui!",
			WARM = "La malvagità si avvicina.",
			WARMER = "È molto vicina adesso.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Casa fa questa diavoleria?",
			READY = "Ha bisogno ancora di una grossa chiave.",
			UNLOCKED = "Vediamo cosa riesco a trovare!",
		},

		DRAGONFRUIT = "Questo non ha affatto la forma di un drago.",
		DRAGONFRUIT_COOKED = "Ancora non è un drago. Almeno è morto.",
		DRAGONFRUIT_SEEDS = "È un seme. Non farà crescere un drago.",
		DRAGONPIE = "Beh, almeno è un tortino adesso.",
		DRUMSTICK = "Fa un buon botto ed è nutriente!",
		DRUMSTICK_COOKED = "Meno crudo, più gustoso.",
		DUG_BERRYBUSH = "Mi piace morto, ma dovrei piantarlo.",
		DUG_GRASS = "Mi piace morto, ma dovrei piantarlo.",
		DUG_MARSH_BUSH = "Mi piace morto, ma dovrei piantarlo.",
		DUG_SAPLING = "Mi piace morto, ma dovrei piantarlo.",
		DURIAN = "Appuntito e puzzolente!",
		DURIAN_COOKED = "Meno spigolosa, ma più puzzolente!",
		DURIAN_SEEDS = "Miracolosamente, i semi non puzzano.",
		EARMUFFSHAT = "Le loro estremità amare mi proteggono dal freddo rigido.",
		EGGPLANT = "Una belladonna quasi letale. Quasi.",
		EGGPLANT_COOKED = "La belladonna cotta è meno letale.",
		EGGPLANT_SEEDS = "È un seme di belladonna.",
		EVERGREEN =
		{
			BURNING = "Sta bruciando vivacemente.",
			BURNT = "Usato ed esaurito.",
			CHOPPED = "Tutto muore.",
			GENERIC = "La natura è così noiosa.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Sta bruciando vivacemente.",
			BURNT = "Usato ed esaurito.",
			CHOPPED = "Tutto muore.",
			GENERIC = "Il suo ciclo di vita sta finendo.",
		},
		EYEPLANT = "Seguono ogni desiderio del loro padrone.",
		FARMPLOT =
		{
			GENERIC = "Quale seme seminerò?",
			GROWING = "Viticci arricciati e fogliosi che escono dal letame.",
			NEEDSFERTILIZER = "Questa terra è fredda e morta.",
		},
		FEATHERHAT = "Cra-cra!",
		FEATHER_CROW = "Una piuma di corvo, nera come l'oscurità eterna.",
		FEATHER_ROBIN = "Una piuma di cardinale, rossa come il sangue.",
		FEATHER_ROBIN_WINTER = "Una piuma dello zigolo, bianca come la luce alla fine del tunnel.",
		FEM_PUPPET = "Mi chiedo cosa abbia fatto.",
		FIREFLIES =
		{
			GENERIC = "Una fioca luminosità nel buio.",
			HELD = "Piccole luci, estraniate dal mondo esterno della mia tasca.",
		},
		FIREHOUND = "La sua disposizione è impetuosa.",
		FIREPIT =
		{
			EMBERS = "L'oscurità si profila.",
			GENERIC = "Potrei sopravvivere a questa notte!",
			HIGH = "Una visione dell'inferno!",
			LOW = "L'oscurità invade.",
			NORMAL = "È un incendio.",
			OUT = "Quello non è un buon segno.",
		},
		FIRESTAFF = "Potrei incendiare il mondo!",
		FISH = "Si sbatteva disperato per sopravvivere. Il povero sciocco.",
		FISHINGROD = "Con questo, posso tirare i pesci fuori dal loro stagno prezioso e sicuro.",
		FISHSTICKS = "Blocchi di pesce perfettamente modellati.",
		FISHTACOS = "Spero che tu abbia tolto tutte le spine.",
		FISH_COOKED = "Una buona grigliata fa fermare il dimenarsi.",
		FLINT = "Una roccia simile a una lama.",
		FLOWER = "Sono luminosi e allegri. Blach.",
		FLOWERHAT = "Ma sono in lutto...",
		FLOWER_EVIL = "Almeno sono meglio di altri fiori.",
		FOLIAGE = "Mi portano ad Aarnivalkea.",
		FOOTBALLHAT = "Una cosa morta da indossare. Benissimo.",
		FROG =
		{
			DEAD = "La vita è piccola e breve.",
			GENERIC = "È piccolo e verrucoso.",
			SLEEPING = "Sta dormendo.",
		},
		FROGGLEBUNWICH = "Non ho mai pensato che le cosce di rana potessero essere così buone.",
		FROGLEGS = "Strappato proprio dalla rana.",
		FROGLEGS_COOKED = "Sicuramente non si contraggono più.",
		FRUITMEDLEY = "Dolce, acida e in una tazza.",
		GEARS = "Gli interni di un demone meccanico.",
		GHOST = "È risorto dalla tomba!",
		GOLDENAXE = "Almeno posso uccidere gli alberi con stile.",
		GOLDENPICKAXE = "Almeno posso fracassare le rocce con stile.",
		GOLDENPITCHFORK = "Almeno posso arare la terra con stile.",
		GOLDENSHOVEL = "Almeno posso scavare con stile.",
		GOLDNUGGET = "Lo porterò con me.",
		GRASS =
		{
			BARREN = "Ha bisogno di cacca.",
			BURNING = "Ha uno strano odore.",
			GENERIC = "È solo un ciuffo d'erba.",
			PICKED = "È stato ucciso.",
		},
		GREEN_CAP = "Questo fungo è deludentemente normale.",
		GREEN_CAP_COOKED = "Tutto è malleabile.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Umido.",
			INGROUND = "Mi nasconderei anche io, se potessi.",
			PICKED = "Raccolto.",
		},
		GUNPOWDER = "È un sentiero oscuro che calpesto.",
		HAMBAT = "La morte genera morte.",
		HAMMER = "Oh, così che possa schiacciare il mondo.",
		HEALINGSALVE = "La vita porta il dolore, il dolore porta la vita.",
		HEATROCK =
		{
			COLD = "Solo un blocco moderatamente freddo di roccia.",
			GENERIC = "Ecco dove giace, occupando solo spazio.",
			HOT = "Quelli che bruciano più brillanti bruciano più veloci.",
			WARM = "Tiepida e senza vita come ogni altra roccia.",
		},
		HOMESIGN = "Un marchio è creato, per quanto transitorio.",
		HONEY = "Una delizia dolce, ma fugace.",
		HONEYCOMB = "Pezzi di alveare, sparsi.",
		HONEYHAM = "Una salsa dolce per il dolce abbraccio di questa creatura.",
		HONEYNUGGETS = "Una salsa dolce per il dolce abbraccio di questa creatura.",
		HORN = "Si sente come un mufalo intrappolato all'interno.",
		HOUND = "Stai indietro, seguace del male!",
		HOUNDBONE = "I resti di una bestia malvagia.",
		HOUNDMOUND = "Casa delle creature più atroci.",
		ICEBOX = "È freddo come il mio cuore.",
		ICEHOUND = "Ha un cuore freddo e morto.",
		INSANITYROCK =
		{
			ACTIVE = "Sta chiamando il mio nome.",
			INACTIVE = "È freddo e nero.",
		},
		JAMMYPRESERVES = "La perfetta quantità di marmellata.",
		KABOBS = "Carne, infilzata proprio nel centro.",
		KILLERBEE =
		{
			GENERIC = "Un'ape con un cuore freddo, morto.",
			HELD = "Non ti muovere, piccolina.",
		},
		KNIGHT = "Un cavallo freddo, senz'anima.",
		KOALEFANT_SUMMER = "Una bestia di solitudine.",
		KOALEFANT_WINTER = "Si erge contro gli elementi crudeli.",
		KRAMPUS = "Ciao, creature malvage degli inferi.",
		KRAMPUS_SACK = "Puzza di capra.",
		LEIF = "Una bestia sgraziata.",
		LEIF_SPARSE = "Una bestia sgraziata.",
		LIGHTNING_ROD =
		{
			CHARGED = "Perfino questo potere si esaurirà.",
			GENERIC = "Si concentra sulla distruzione.",
		},
		LITTLE_WALRUS = "Il ciclo di violenza continua.",
		LIVINGLOG = "Grida per sempre in silenzio.",
		LOCKEDWES = "Intrappolato dalle statue di Maxwell, vive per sempre.",
		LOG = "Se gli alberi potessero parlare, urlerebbero a questa visione.",
		LUREPLANT = "Si consuma tutto.",
		LUREPLANTBULB = "La vita continua.",
		MALE_PUPPET = "Mi chiedo cosa abbia fatto.",
		MANDRAKE =
		{
			DEAD = "Ahimè, povera mandragola!",
			GENERIC = "La possente mandragola. Dovrei prenderla durante la notte.",
			PICKED = "Avanti, miei seguaci vegetali!",
		},
		MANDRAKESOUP = "Bollito all'estremo.",
		MARBLE = "Liscio e senza vita.",
		MARBLEPILLAR = "Nemmeno la pietra è in grado di sopportare la forza costante del decadimento.",
		MARBLETREE = "Non c'è nessun battito di vita all'interno di questo albero freddo.",
		MARSH_BUSH =
		{
			BURNING = "Anche le spine bruciano.",
			GENERIC = "Un cespuglio che fa sempre male.",
			PICKED = "Mi ha fatto male farlo.",
		},
		MARSH_PLANT = "È una pianta.",
		MARSH_TREE =
		{
			BURNING = "Sta bruciando.",
			BURNT = "Nero come il mio cuore.",
			CHOPPED = "Le sue punte non gli hanno dato alcuna protezione.",
			GENERIC = "Un albero che conosce solo il dolore.",
		},
		MAXWELL = "Sento una strana parentela con lui.",
		MAXWELLHEAD = "Ha sicuramente un gusto per il drammatico.",
		MAXWELLLIGHT = "Che luce curiosa.",
		MAXWELLLOCK = "Sembra magico.",
		MAXWELLTHRONE = "Non è proprio quello che mi aspettavo.",
		MEAT = "È ancora sanguinante.",
		MEATBALLS = "Carne appallottata. Che emozione.",
		MEATRACK =
		{
			DONE = "L'asciugatura è finita.",
			DRYING = "Ondeggia nel vento secco.",
			GENERIC = "Posso appenderci la carne.",
		},
		MEAT_DRIED = "Carne diventata secca e deliziosa.",
		MERM = "Orrida cosa delle paludi.",
		MERMHEAD = "Assolutamente nessuna dignità.",
		MERMHOUSE = "Il tempo l'ha rovinata.",
		MINERHAT = "Illuminazione mani-libere!",
		MONSTERMEAT = "La cattiveria lo pervade.",
		MONSTERMEAT_DRIED = "La carne è diventata secca e di sapore strano.",
		MOSQUITO =
		{
			GENERIC = "Prende la vita per poter vivere.",
			HELD = "Posso sentire il suo calore rubato.",
		},
		MOSQUITOSACK = "Una sacca di sangue distrutta da una zanzara. Mi piace.",
		MOUND =
		{
			DUG = "La terra ha vomitato i suoi segreti.",
			GENERIC = "Un giorno, mi unirò a te.",
		},
		NIGHTLIGHT = "Inquietante ma pur sempre bella.",
		NIGHTMAREFUEL = "Il sonno dei sogni genera queste cose.",
		NIGHTSWORD = "I sogni arrivano ad un punto. Netto.",
		NITRE = "Qui giace la follia dell'uomo.",
		ONEMANBAND = "Ero abituata a trarre gioia da strumenti come questi.",
		PANDORASCHEST = "La vita è un gioco d'azzardo.",
		PANFLUTE = "La musica è la finestra sulla mia anima vuota.",
		PAPYRUS = "Per documentare il mio dolore.",
		PENGUIN = "Tutti in smoking, per andare dove?",
		PERD = "Stupido pennuto! Stai lontano dalle mie bacche!",
		PEROGIES = "Un incantevole piccolo sacchetto di sostanze nutrienti.",
		PETALS = "Ho distrutto qualcosa di bello.",
		PETALS_EVIL = "Sono dipinti con i colori della mia anima.",
		PICKAXE = "Così che io possa penetrare la terra stessa.",
		PIGGYBACK = "Sono più utili da morti.",
		PIGHEAD = "Uccidi il maiale. Versa il suo sangue.",
		PIGHOUSE =
		{
			FULL = "Spero che si stia divertendo.",
			GENERIC = "Almeno sono comodi.",
			LIGHTSOUT = "Ora sono tutta sola.",
		},
		PIGKING = "Se la goda finché è possibile, Sua Maestà.",
		PIGMAN =
		{
			DEAD = "Sta meglio, ora.",
			FOLLOWER = "Mi sento ancora da sola.",
			GENERIC = "Sono così scostanti.",
			GUARD = "Com'è orwelliano.",
			WEREPIG = "Una creatura della notte!",
		},
		PIGSKIN = "La pelle di un maiale che fu.",
		PIGTORCH = "Taglia al buio.",
		PINECONE = 
		{
		    GENERIC = "Una piccola vita, rifugiata nella fragile morte.",
		    PLANTED = "Un albero crescerà presto.",
		},
		PITCHFORK = "Che strumento diabolico!",
		PLANTMEAT = "Ha un odore fetido.",
		PLANTMEAT_COOKED = "È solo leggermente più attraente.",
		PLANT_NORMAL =
		{
			GENERIC = "Una pianta commestibile.",
			GROWING = "Continuare a crescere. Ti aspetterò.",
			READY = "È pronta per il raccolto.",
		},
		POMEGRANATE = "Tanti pezzetti rossi e succosi da tagliare e spremere.",
		POMEGRANATE_COOKED = "Caldo, ma non per questo meno caotico.",
		POMEGRANATE_SEEDS = "Mi aspettavo più semi da quella cosa.",
		POND = "Ofelia? Sei laggiù?",
		POOP = "La vita è fatta di sangue e di questo.",
		PUMPKIN = "È grande come il buco dove era il mio cuore.",
		PUMPKINCOOKIE = "L'ho cucinato io!",
		PUMPKIN_COOKED = "Un pochino raggrinzito dal calore. Mi piace.",
		PUMPKIN_LANTERN = "Non sei così spaventoso.",
		PUMPKIN_SEEDS = "Si tratta di un seme. Emozionante.",
		PURPLEGEM = "Viola come una... cosa viola.",
		RABBIT =
		{
			GENERIC = "Vaga senza pensare, ignaro della sua sorte.",
			HELD = "È sicuro tra le mie braccia.",
		},
		RABBITHOLE = "Sono troppo grande per cadere lì dentro.",
		RAINOMETER = "Misura la nuvolosità. Mi piace quando è triste.",
		RATATOUILLE = "Un sacco di verdure cotte. Affascinante.",
		RAZOR = "Questo serve solo alla rasatura.",
		REDGEM = "Rosso come il sangue del mio cuore.",
		RED_CAP = "Un fungo che segue il mio cuore.",
		RED_CAP_COOKED = "Tutto è malleabile.",
		RED_MUSHROOM =
		{
			GENERIC = "Umido.",
			INGROUND = "Mi nasconderei anche io, se potessi.",
			PICKED = "Raccolto.",
		},
		REEDS =
		{
			BURNING = "Presto sarà cenere.",
			GENERIC = "È solo un mucchio di canne.",
			PICKED = "Li ho raccolti.",
		},
        RELIC = 
        {
            GENERIC = "Un avanzo di un mondo antico.",
            BROKEN = "Pezzi rotti di pietra.",
        },
        RUINS_RUBBLE = "Un mucchio di sogni infranti.",
		RESEARCHLAB = "Imparerò cose indicibili.",
		RESEARCHLAB2 = "Imparerò cose indicibili.",
		RESEARCHLAB3 = "Ho imparato cose indicibili.",
		RESURRECTIONSTATUE = "Sto solo rimandando l'inevitabile.",
		RESURRECTIONSTONE = "Un verso futile.",
		ROBIN =
		{
			GENERIC = "Ciò significa che sta arrivando la primavera? Spero di no.",
			HELD = "Gli piace essere intrappolato nella mia tasca.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "La vita nelle aride lande ghiacciate.",
			HELD = "È così morbido. È il mio nemico.",
		},
		ROBOT_PUPPET = "Mi chiedo cosa abbia fatto.",
		ROCK_LIGHT =
		{
			GENERIC = "Una crosta sopra il pozzo di lava.",
			OUT = "Sembra innocuo.",
			LOW = "Le ombre invadono.",
			NORMAL = "La lava è incandescente.",
		},
		ROCK = "Anche questo non è permanente.",
		ROCKS = "Alcune piccole rocce.",
        ROOK = "Una torre? O è un castello?",
		ROPE = "Quella sarebbe l'uscita più facile da questo luogo.",
		ROTTENEGG = "La conclusione di tutte le cose.",
		SANITYROCK =
		{
			ACTIVE = "Mi sta chiamando.",
			INACTIVE = "Anche questo obelisco mi ha lasciato.",
		},
		SAPLING =
		{
			BURNING = "Consegnato alle fiamme.",
			GENERIC = "Sta cercando di crescere.",
			PICKED = "Forse la prossima volta, alberello.",
		},
		SEEDS = "La vita, o almeno la sua promessa.",
		SEEDS_COOKED = "Li ho tostati all'estremo.",
		SEWING_KIT = "Un altro attrezzo per ritardare l'inevitabile decadimento.",
		SHOVEL = "Quali segreti terribili potrei scoprire?",
		SILK = "Così scivoloso e raffinato.",
		SKELETON = "Invidio la sua fuga.",
		SKULLCHEST = "Dovrà contenere il mio memento mori.",
		SMALLBIRD =
		{
			GENERIC = "Ciao, piccolino.",
			HUNGRY = "Sei vuoto dentro?",
			STARVING = "Un buco nero da cui i semi non fanno più ritorno.",
		},
		SMALLMEAT = "Odora di piccola paura.",
		SMALLMEAT_DRIED = "Carne diventata secca e deliziosa.",
		SPEAR = "Sono diventata la distruttrice dei mondi.",
		SPIDER =
		{
			DEAD = "Ci incontreremo di nuovo un giorno.",
			GENERIC = "Una creatura della notte!",
			SLEEPING = "Il male sta dormendo.",
		},
		SPIDERDEN = "Un nido di sporcizia e scelleratezza.",
		SPIDEREGGSACK = "Un piccolo pacchetto completo di morte e distruzione.",
		SPIDERGLAND = "Anche nella morte, questa bestia provoca dolore.",
		SPIDERHAT = "È ora di fissare nel baratro.",
		SPIDERQUEEN = "È regale nella sua spaventosità.",
		SPIDER_WARRIOR =
		{
			DEAD = "Ahimè, coraggioso guerriero.",
			GENERIC = "Un guerriero della notte!",
			SLEEPING = "Devo stare attenta.",
		},
		SPOILED_FOOD = "Tutto si trasforma in rifiuti, alla fine.",
		STATUEHARP = "Forse queste statue mi terranno compagnia.",
		STATUEMAXWELL = "Mi ha portato qui.",
		STINGER = "Affilato e mortale.",
		STRAWHAT = "Mi coprirò la testa.",
		STUFFEDEGGPLANT = "Una belladonna. Probabilmente non è piena di veleno.",
		SUNKBOAT = "Uno scherzo crudele!",
		SWEATERVEST = "Posso indossare un giubbotto fatto di pezzi di cose morte!",
		TAFFY = "Non avrei mai immaginato di poter fare una cosa così dolce.",
		TALLBIRD = "Libero dalle catene del cielo.",
		TALLBIRDEGG = "Così pieno di potenzialità.",
		TALLBIRDEGG_COOKED = "Una promessa strappata via. Non male con la pancetta.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Raffreddato dal buio.",
			GENERIC = "Un esserino fragile, che lotta verso la luce.",
			HOT = "Non posso sopportare il calore.",
			LONG = "Una vita iniziata presto è una vita presto conclusa.",
			SHORT = "Manca poco.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Quell'uovo rappresenta una nuova vita. Che schifo.",
			PICKED = "Il nido è vuoto. Vacante. Sterile. Un vuoto.",
		},
		TEENBIRD =
		{
			GENERIC = "Mi lascerai anche tu?",
			HUNGRY = "Cerchiamo tutti di riempire il vuoto.",
			STARVING = "La tua vera natura è rivelata!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Sono sicura che il prossimo regno sarà ancora più orribile!",
			GENERIC = "Nulla di buono può venire da questo.",
			LOCKED = "È ancora chiuso a chiave.",
			PARTIAL = "È metà costruito, o mezzo distrutto?",
		},
		TELEPORTATO_BOX = "Contiene una scintilla vitale.",
		TELEPORTATO_CRANK = "Sembra complicato.",
		TELEPORTATO_POTATO = "Che orribile creazione!",
		TELEPORTATO_RING = "Non ha spigoli affilati.",
		TENT = "Il sonno non è altro che un'anteprima della morte.",
		TENTACLE = "Lungo, sottile e pericoloso!",
		TENTACLESPOTS = "Meglio lasciarli non menzionati.",
		TENTACLESPIKE = "Affilato, viscido e pericoloso.",
        TENTACLE_PILLAR = "Quindi questo è quello che succede là sotto.",
        TENTACLE_PILLAR_ARM = "Bambini!",
        TENTACLE_GARDEN = "Questo è diverso.",
		TOPHAT = "Mi coprirò la testa.",
		TORCH = "Un piccolo baluardo contro la notte.",
		TRAP = "Una semplice erba è diventata letale.",
		TRAP_TEETH = "Una subdola sorpresa dal sottosuolo.",
		TRAP_TEETH_MAXWELL = "La morte quando meno me l'aspettavo.",
		TREASURECHEST = "Con il quale contenere il mio lucro.",
		TRINKET_1 = "Perfettamente deforme.",
		TRINKET_10 = "Un'altra bocca da sfamare.",
		TRINKET_11 = "Fortunato robot, non ha mai avuto un'anima.",
		TRINKET_12 = "Non siamo più così viscidi, vero?",
		TRINKET_2 = "È un falso. Solo una tentazione, come la morte.",
		TRINKET_3 = "Se solo i coltelli potessero risolvere altri miei problemi...",
		TRINKET_4 = "Lo trasporterei fino alla fine del mondo.",
		TRINKET_5 = "Lo farei volare diritto verso il sole, se solo fosse più grande.",
		TRINKET_6 = "Una volta ravvivati con l'elettricità, incontrano la loro fine.",
		TRINKET_7 = "Solo un semplice gioco.",
		TRINKET_8 = "Avrei voluto farmi un bagno.",
		TRINKET_9 = "Bottoni non abbinati per una vita non corrisposta.",
		TRUNKVEST_SUMMER = "Pelle da indossare sulla mia pelle.",
		TRUNKVEST_WINTER = "Può scaldare il mio corpo, ma il mio spirito?",
		TRUNK_COOKED = "Ora sembra anche peggio.",
		TRUNK_SUMMER = "Avrei preferito le orecchie.",
		TRUNK_WINTER = "Separato dal suo unico amico.",
		TURKEYDINNER = "Chi sta divorando ora?",
		TWIGS = "Strappato dal terreno prima di uscire.",
		UMBRELLA = "Le nuvole piangono.",
		WAFFLES = "Sono decisamente delle cialde.",
		WALL_HAY = "Quello è solo un suggerimento di difesa.",
		WALL_HAY_ITEM = "Il loro valore difensivo è discutibile.",
		WALL_STONE = "Cosa mi proteggerà da quello che c'è dentro?",
		WALL_STONE_ITEM = "Questi non proteggono dai demoni interiori.",
		WALL_RUINS = "Questi non hanno protetto gli antichi, sbaglio?",
		WALL_RUINS_ITEM = "Sono delle pietre infestate?",
		WALL_WOOD = "Ora posso ritardare l'inevitabile.",
		WALL_WOOD_ITEM = "Tronchi raggruppati.",
		WALRUS = "Un uomo anziano, di mare.",
		WALRUSHAT = "Quali pensieri febbrili sono emersi da qua sotto?",
		WALRUS_CAMP =
		{
			EMPTY = "Se non sono là, allora dove sono?",
			GENERIC = "Questa casa non è felice, temo.",
		},
		WALRUS_TUSK = "Ti devo azzannare.",
		WASPHIVE = "Si nascondono nella loro fortezza di odio.",
		WETGOOP = "Un pasticcio miserabile, proprio come la vita.",
		WINTERHAT = "Aiuta ad allontanare il freddo invadente.",
		WINTEROMETER = "Perché mi sembra che stia misurando la mia mortalità?",
		WORMHOLE =
		{
			GENERIC = "La vita non sempre ha senso.",
			OPEN = "Non importa ciò che consuma, non è mai soddisfatto.",
		},
		ACCOMPLISHMENT_SHRINE = "Non mi è mai importato delle metafore.",
		LIVINGTREE = "Non può mai morire?",
		ICESTAFF = "Un materiale da congelare.",
	},
	DESCRIBE_GENERIC = "È innominabile.",
	DESCRIBE_TOODARK = "L'oscurità! È troppo buia!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Gli ho risparmiato il tormento del vivere.",
	},
}
