return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我覺得她不喜歡剃毛。",
			GENERIC = "你不能剃掉不是毛髮的東西。",
			NOBITS = "已經剃過了，嗯？",
		},
		STORE =
		{
			GENERIC = "已經比大城市的公交還擠了。",
			NOTALLOWED = "不能裝在這，是吧？",
		},
	},
	ACTIONFAIL_GENERIC = "對不起，我做不到。",
	ANNOUNCE_ADVENTUREFAIL = "唉，好吧。至少我嘗試過了。",
	ANNOUNCE_BEES = "蜜蜂！蜜蜂！",
	ANNOUNCE_BOOMERANG = "抱歉！我真是笨死了！",
	ANNOUNCE_CHARLIE = "誰在那兒，嗯？",
	ANNOUNCE_CHARLIE_ATTACK = "哎喲！太粗暴了！",
	ANNOUNCE_COLD = "這裡太冷了！",
	ANNOUNCE_CRAFTING_FAIL = "我現在無法做那個。",
	ANNOUNCE_DEERCLOPS = "那是什麼？",
	ANNOUNCE_DUSK = "快到我的睡覺時間了。",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "已經過了保鮮期了。",
		SPOILED = "有一點點壞了。",
		STALE = "我要趕緊把它吃掉。",
	},
	ANNOUNCE_ENTER_DARK = "誰關的燈？",
	ANNOUNCE_ENTER_LIGHT = "世界亮了！",
	ANNOUNCE_FREEDOM = "我出來了！",
	ANNOUNCE_HOUNDS = "那邊有什麼東西。",
	ANNOUNCE_HUNGRY = "越來越餓了。",
	ANNOUNCE_HUNT_BEAST_NEARBY = "動物就在附近。",
	ANNOUNCE_HUNT_LOST_TRAIL = "動物已經走遠了。",
	ANNOUNCE_INV_FULL = "我拿不了更多的東西了。",
	ANNOUNCE_KNOCKEDOUT = "噢。這是怎麼回事？",
	ANNOUNCE_MOSQUITOS = "蚊子！",
	ANNOUNCE_NODANGERSLEEP = "野外睡覺太可怕了。",
	ANNOUNCE_NODAYSLEEP = "只有失敗者才在白天睡覺。",
	ANNOUNCE_NOHUNGERSLEEP = "我的肚子太餓了，睡不著。",
	ANNOUNCE_NO_TRAP = "好險！",
	ANNOUNCE_PECKED = "對不起！我會更努力的！",
	ANNOUNCE_QUAKE = "大地在晃！",
	ANNOUNCE_THORNS = "哎喲！",
	ANNOUNCE_TORCH_OUT = "火把滅了！",
	ANNOUNCE_TRAP_WENT_OFF = "糟糕！",
	ANNOUNCE_WORMHOLE = "裡面太可怕了！",
	ANNOUNCE_CANFIX = "\n我覺得我能修好這個！",
	ANNOUNCE_ACCOMPLISHMENT= "露西肯定會為我感到驕傲的！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我太厲害了，是吧！",
	BATTLECRY =
	{
		GENERIC = "放馬過來吧，哈！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "差不多夠了。",
	},
	DESCRIBE =
	{
		WORMLIGHT = "這東西應該會有用。",
		WORM =
		{
		    PLANT = "是不是植物，我一看就知道。這絕對是個騙子！",
		    DIRT = "小心移動的地面。",
		    WORM = "哇哦，蠕蟲！",
		},
		EEL = "這烹飪出來應該挺不錯的。",
		EEL_COOKED = "烤得真不錯。",
		UNAGI = "它會填飽你的肚子。",
		EYETURRET = "它會把其他傢伙擊退的。",
		EYETURRET_ITEM = "這需要正確安裝。",
		MINOTAURHORN = "很漂亮的犀牛角，是吧。",
		MINOTAURCHEST = "很不錯的帶角箱子，是吧。",
		THULECITE_PIECES = "雖然不是木製的，但還湊合。",
		POND_ALGAE = "好像不能吃。",
		GREENSTAFF = "這可以幫我把現有的東西拆解和還原！",
		POTTEDFERN = "這足以證明我對植物的熱愛。",

		THULECITE = "它可以說是洞穴裡的木頭！",
		ARMORRUINS = "這可以防止傷害。",
		RUINS_BAT = "金屬串在棍子上。",
		RUINSHAT = "雖然不是無邊帽，但還湊合。",
		NIGHTMARE_TIMEPIECE = 
		{
		CALM = "我想它已經關了吧。",	
		WARN = "這東西又開啟了！",	
		WAXING = "它在振動！", 
		STEADY = "太瘋狂了！", 
		WANING = "它穩定下來了。", 
		DAWN = "它幾乎沒動。", 
		NOMAGIC = "我想它已經關了吧。", 
		},
		BISHOP_NIGHTMARE = "我可以看到它內部的零件！",
		ROOK_NIGHTMARE = "齒輪都散落出來了。",
		KNIGHT_NIGHTMARE = "好像並不是它最好的狀態。",
		MINOTAUR = "又一個被詛咒的可憐生物。",	
		SPIDER_DROPPER = "它們很聰明，知道要遠離腐爛物。",	
		NIGHTMARELIGHT = "這盞燈應該使用木材的。",	
		RELIC = "破碎的傢俱。",	
		RUINS_RUBBLE = "一切都毀了。",	
		MULTITOOL_AXE_PICKAXE = "它...它真漂亮。",	
		GREENGEM = "好閃亮。",
		ORANGESTAFF = "它可以幫我快速移動。",	
		YELLOWAMULET = "有了這個東西，晚上我也可以砍樹了。",	
		GREENAMULET = "不管怎麼說，我還是更擅長砍東西。",	

		SLURPER = "我覺得這團毛球是活的。",
		SLURPER_PELT = "看上去像一隻死去的海狸。",
		ARMORSLURPER = "好癢，我覺得它還是活的。",
		ORANGEAMULET = "這可以讓家事更快完成！",
		YELLOWSTAFF = "在緊要關頭很有用！",
		YELLOWGEM = "我可以看到它裡面有星星在閃。",
		ORANGEGEM = "它在閃閃發光。",
		TELEBASE = 
		{
			VALID = "它是準備好了，但我呢？",
			GEMS = "需要裝上寶石，是嗎？",
		},
		GEMSOCKET = 
		{
			VALID = "看起來準備就緒了。",
			GEMS = "它需要一個寶石。",
		},
		STAFFLIGHT = "太厲害了。",
		RESEARCHLAB4 = "我喜歡叫它「帽子機器」！",

	
		LUCY = "我愛露西！",

        ANCIENT_ALTAR =
        {
        	WORKING = "祭壇的石頭上有斧頭標記。",
        	BROKEN = "好像有點壞了。",
        },     
        
        ANCIENT_ALTAR_BROKEN = "好像有點壞了。",
        ANCIENT_STATUE = "又一個失敗者。",

        LICHEN = "看起來幾乎不能吃。",
		CUTLICHEN = "好吃！味道像木頭一樣！",

		CAVE_BANANA = "熱帶水果的味道。",
		CAVE_BANANA_COOKED = "我把它烤了。",
		CAVE_BANANA_TREE = "在家鄉看不到這種樹。",
		ROCKY = "龍蝦餐時間！",
		
		COMPASS =
		{
			GENERIC="我不知道怎麼讀。",
			N = "正北。",
			S = "南",
			E = "東",
			W = "西",
			NE = "東北",
			SE = "東南",
			NW = "西北",
			SW = "西南",
		},


		BLUEAMULET = "現在只需要來杯飲料冰凍一下，不是嗎？",
		PURPLEAMULET = "寶石上的光芒消失了。",
		TELESTAFF = "我很好奇這東西幹什麼用的。",
		MONKEY = "很好。又來一隻。",
		MONKEYBARREL = "很不錯的建築材料。",

		HOUNDSTOOTH="很漂亮，對嗎？",
		ARMORSNURTLESHELL="永遠要小心為上。",
		BAT="是誰教會那隻老鼠飛的？",
		BATBAT = "長著翅膀的老鼠？",
		BATWING="好噁心！",
		BATWING_COOKED="好噁心！但又很好吃！好為難啊！",
		
		BEDROLL_FURRY="我喜歡露營。",
		BUNNYMAN="他看起來很友善。",
		FLOWER_CAVE="好閃亮！",
		FLOWER_CAVE_DOUBLE="好閃亮！",
		FLOWER_CAVE_TRIPLE="好閃亮！",
		GUANO="它不像其他的那麼臭。",
		LANTERN="高科技啊！",
		LIGHTBULB="它看起來很耐嚼。",
		MANRABBIT_TAIL="我覺得對不起他。",
		MUSHTREE_TALL  ="我不能放任它不管。",
		MUSHTREE_MEDIUM="也許我應該砍了它。",
		MUSHTREE_SMALL ="它是木頭做的。",
		RABBITHOUSE="這是胡蘿蔔的味道嗎？",
		SLURTLE="他只是被誤解了。",
		SLURTLE_SHELLPIECES="我弄壞了他的家。真是過意不去。",
		SLURTLEHAT="它可以確保我的腦袋安全。",
		SLURTLEHOLE="你們在那地方沒問題嗎？",
		SLURTLESLIME="看來有人需要一張紙巾。",
		SNURTLE="螺旋形的東西！",
		SPIDER_HIDER="狡猾的魔鬼！",
		SPIDER_SPITTER="亂吐東西太沒禮貌了！",
		SPIDERHOLE="我應該在它們出來之前趕緊離開這地方。",
		STALAGMITE="我對岩石沒多大興趣。",
		STALAGMITE_FULL="我對岩石沒多大興趣。",
		STALAGMITE_LOW="我對岩石沒多大興趣。",
		STALAGMITE_MED="我對岩石沒多大興趣。",
		STALAGMITE_TALL="我對岩石沒多大興趣。",
		STALAGMITE_TALL_FULL="我對岩石沒多大興趣。",
		STALAGMITE_TALL_LOW="我對岩石沒多大興趣。",
		STALAGMITE_TALL_MED="我對岩石沒多大興趣。",


		TURF_CARPETFLOOR = "太對我的口味了",
		TURF_CHECKERFLOOR = "看起來像城市裡戶外廁所的地板。",
		TURF_DIRT = "只是一些地面，不是嗎？",
		TURF_FOREST = "只是一些地面，不是嗎？",
		TURF_GRASS = "只是一些地面，不是嗎？",
		TURF_MARSH = "只是一些地面，不是嗎？",
		TURF_ROAD = "只是一些地面，不是嗎？",
		TURF_ROCKY = "只是一些地面，不是嗎？",
		TURF_SAVANNA = "只是一些地面，不是嗎？",
		TURF_WOODFLOOR = "適合國王的地板！",

		TURF_CAVE="一些地面。",
		TURF_FUNGUS="黏糊糊的，像豌豆泥一樣。",
		TURF_SINKHOLE="我是在地下發現這個的。",
		TURF_UNDERROCK="是岩石。廢話。",	
		TURF_MUD="至少不需要你打掃。",

		
		POWCAKE = "我更喜歡用真正的糖做成的蛋糕。",
        CAVE_ENTRANCE = 
        {
            GENERIC="它被堵住了。",
            OPEN = "下面看起來好像加拿大的薩德伯里。",
        },
        CAVE_EXIT = "那上面也許有樹。",
		
		MAXWELLPHONOGRAPH = "比收音機上聽到的大多數東西都要好。",
		BOOMERANG = "看起來很難扔。",
		PIGGUARD = "我可不想讓他發瘋。",
		ADVENTURE_PORTAL = "我懷疑那是不是離開這裡的路。",
		AMULET = "應該總是準備一個備用計劃。",
		ANIMAL_TRACK = "有一隻大型林地生物從這走過！",
		ARMORGRASS = "總比什麼都沒有好。",
		ARMORMARBLE = "穿著這個很難揮動斧頭。",
		ARMORWOOD = "它太適合我了！",
		ARMOR_SANITY = "看見它我就想吐。",
		ASH =
		{
			GENERIC = "全都付之一炬了。",
			REMAINS_EYE_BONE = "這曾經是個眼骨。",
			REMAINS_THINGIE = "我猜它沒能和我一起傳送過來。",
		},
		AXE = "沒有我的露西斧好。",
		BABYBEEFALO = "長得這麼醜，估計只有親媽才不會嫌棄。",
		BACKPACK = "那是我的背包。",
		BACONEGGS = "嗚嗚嗚。只有五花培根。",
		BANDAGE = "至少我不必付錢買它。",
		BASALT = "那塊岩石是不會移動的。",
		BEARDHAIR = "不是我的鬍子。",
		BEDROLL_STRAW = "想當初在伐木場的時候，我還睡過更糟糕的地方呢。",
		BEE =
		{
			GENERIC = "她在給花授粉，讓花開得更艷。",
			HELD = "現在我拿它怎麼辦？",
		},
		BEEBOX =
		{
			FULLHONEY = "好多蜂蜜！",
			GENERIC = "蜜蜂！",
			NOHONEY = "只是看著它我就已經餓了。",
			SOMEHONEY = "如果再等等，我可以收穫更多的。",
		},
		BEEFALO =
		{
			FOLLOWER = "我覺得他喜歡我。",
			GENERIC = "他聞起來像草房一樣。",
			NAKED = "瞬間有精神了，是吧？",
			SLEEPING = "他在睡覺。",
		},
		BEEFALOHAT = "現在我是犛牛王！",
		BEEFALOWOOL = "感覺像我的鬍子。",
		BEEHAT = "這個可以防止蜜蜂螫我的眼睛。",
		
		BEEHIVE = "它們在裡面又舒適又愜意。",
		
		BEEMINE = "不知道蜜蜂喜不喜歡這個。",
		BEEMINE_MAXWELL = "喂！這太卑鄙了！",
		BERRIES = "它們填不飽我的胃口。",
		BERRIES_COOKED = "像熱漿果的味道。",
		BERRYBUSH =
		{
			BARREN = "它需要有充足養分的糞便肥料",
			GENERIC = "薩斯卡通漿果？",
			PICKED = "沒有漿果了！",
		},
		BIRDCAGE =
		{
			GENERIC = "這就是我用來讓臭鳥們反省自己惡行的地方。",
			OCCUPIED = "想想你都做過些什麼吧，臭鳥！",
			SLEEPING = "它們睡著了之後倒是看起來很無辜。",
		},
		BIRDTRAP = "臭鳥們，等著吧！",
		BIRD_EGG = "那裡面有只滿腦子邪惡思想的鳥。",
		BIRD_EGG_COOKED = "很好，至少它永遠不會變成討厭的鳥。",
		BISHOP = "離我上一次懺悔已經有一陣子了。",
		BLOWDART_FIRE = "這好像有點攻擊性。",
		BLOWDART_SLEEP = "用這個的話，我就可以逃跑了！",
		BLOWDART_PIPE = "是檢驗我強大肺活量的時候了！",
		BLUEGEM = "它好冷。",
		BLUEPRINT = "我可不是愛讀書的人。",
		BLUE_CAP = "那可不是肉。",
		BLUE_CAP_COOKED = "那可不是肉。",
		BLUE_MUSHROOM =
		{
			GENERIC = "我不記得哪些蘑菇是可以吃的。",
			INGROUND = "我會再回來的。",
			PICKED = "噢，已經採完了。",
		},
		BOARDS = "好光滑。你真的可以看到它上面的紋理。",
		BOAT = "一定是碰到東北風暴了。",
		BONESTEW = "這可以填飽肚子。",
		BUGNET = "可以用它來捕蚊子。",
		BUSHHAT = "這是與大自然融為一體的好辦法。",
		BUTTER = "我更喜歡人造牛油。",
		BUTTERFLY =
		{
			GENERIC = "我從來不相信那些東西，你說呢？",
			HELD = "你還想往哪兒飛啊？",
		},
		BUTTERFLYMUFFIN = "嘎吱！",
		BUTTERFLYWINGS = "很抱歉！是我不好！",
		CAMPFIRE =
		{
			EMBERS = "快要熄滅了。",
			GENERIC = "我的吉他哪兒去了？",
			HIGH = "哇哦！燒得好旺！",
			LOW = "我是不是應該做點什麼，嗯？",
			NORMAL = "我喜歡在晚上點一堆營火。",
			OUT = "它還是燃著的時候比較好。",
		},
		CANE = "這可以幫助我重返故土。",
		CARROT = "那是兔子吃的東西。",
		CARROT_COOKED = "那是兔子吃的東西。",
		CARROT_PLANTED = "我可不是素食主義者，你說呢？",
		CARROT_SEEDS = "迷你胡蘿蔔。",
		CAVE_FERN = "喂！是蕨類植物！",

		CHARCOAL = "這讓我有點兒難過。",

        CHESSJUNK1 = "廢金屬",
        CHESSJUNK2 = "廢金屬",
        CHESSJUNK3 = "廢金屬",

		CHESTER = "它已經盡力了！",
		CHESTER_EYEBONE =
		{
			GENERIC = "從來沒有人告訴過他，盯著別人看是不禮貌的。",
			WAITING = "不知道它還會不會再醒過來。",
		},
		COOKEDMANDRAKE = "我是不是不應該那樣做？",
		COOKEDMEAT = "跟老媽以前做的一模一樣。",
		COOKEDMONSTERMEAT = "我還是不想吃它。",
		COOKEDSMALLMEAT = "那只會讓我覺得更餓！",
		COOKPOT =
		{
			COOKING_LONG = "還要好一會兒，是嗎？",
			COOKING_SHORT = "我的乖乖！馬上就好了！",
			DONE = "晚餐時間到！",
			EMPTY = "就這樣把它放在這兒，也不煮東西，好像挺浪費的。",
		},
		CORN = "我喜歡玉米，但它不是我最愛的食物。",
		CORN_COOKED = "充分保留了玉米的精華。",
		CORN_SEEDS = "我更多的是一名伐木工而不是農民。",
		CROW =
		{
			GENERIC = "他正在謀劃些什麼。我看得出來。",
			HELD = "烏鴉，你遭到了報應！",
		},
		CUTGRASS = "我想我可能對這東西過敏。",
		CUTREEDS = "想聽聽我學潛鳥叫嗎？",
		CUTSTONE = "加拿大地盾的一部分。",
		DEADLYFEAST = "聞起來有點不對勁，是吧。",
		DEERCLOPS = "好大一隻駝鹿！",
		DEERCLOPS_EYEBALL = "這可以用來幹什麼？",
		DEPLETED_GRASS =
		{
			GENERIC = "它可能是一叢草。",
		},
		DEVTOOL = "我選擇不發表意見。",
		DIRTPILE = "嘿！一條線索！",
		DIVININGROD =
		{
			COLD = "這裡太不明顯了。",
			GENERIC = "不知道可不可以用它來玩曲棍球比賽。",
			HOT = "肯定沒錯！這附近有東西！",
			WARM = "我覺得越來越近了。",
			WARMER = "哇哦，仔細點兒，老兄。",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "看來它上面本來插有東西的。",
			READY = "解鎖準備就緒。",
			UNLOCKED = "現在只需要啟動它就可以了。",
		},
		DIVININGRODSTART = "那根棒子看起來好奇怪。",
		DRAGONFRUIT = "我以前從來沒見過這東西。",
		DRAGONFRUIT_COOKED = "味道有點像楓糖漿。",
		DRAGONFRUIT_SEEDS = "也許我可以再多種些。",
		DRAGONPIE = "幾乎和奶油蛋塔一樣好吃！",
		DRUMSTICK = "十月份的食物。",
		DRUMSTICK_COOKED = "謝謝你，火雞。",
		DUG_BERRYBUSH = "是時候進行點園林綠化了。",
		DUG_GRASS = "它把我的眼淚都弄出來了。",
		DUG_MARSH_BUSH = "我應該種下這個。",
		DUG_SAPLING = "嗯。都是小樹枝。",
		DURIAN = "好臭。",
		DURIAN_COOKED = "沒有最臭，只有更臭。",
		DURIAN_SEEDS = "我才不想多種那東西。",
		EARMUFFSHAT = "在我的家鄉，這種東西只在秋天管用。",
		EGGPLANT = "我打賭這肯定和鳥有關係。",
		EGGPLANT_COOKED = "像鳥一樣，太可疑了。",
		EGGPLANT_SEEDS = "嗯。我不是很確定。",
		EVERGREEN =
		{
			BURNING = "不！我本來可以把它砍掉的！",
			BURNT = "真是浪費。",
			CHOPPED = "啊——！",
			GENERIC = "它在召喚我！",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "很抱歉！",
			BURNT = "簡直太可怕了！",
			CHOPPED = "又砍倒一棵！",
			GENERIC = "露西會希望我把它砍倒的。",
		},
		EYEPLANT = "它應該管好自己的事情。",
		FARMPLOT =
		{
			GENERIC = "我更喜歡大型植物。",
			GROWING = "它們永遠長不到適合砍伐的大小。",
			NEEDSFERTILIZER = "我想應該給它加點肥料。",
		},
		FEATHERHAT = "我不想戴那個...東西。",
		FEATHER_CROW = "令人厭惡的羽毛。",
		FEATHER_ROBIN = "讓人噁心的羽毛。",
		FEATHER_ROBIN_WINTER = "愚蠢的羽毛。",
		FEM_PUPPET = "她被困住了！",
		FIREFLIES =
		{
			GENERIC = "讓我想起了阿岡昆公園。",
			HELD = "我口袋裡面裝滿了陽光！",
		},
		FIREHOUND = "火獵犬！",
		FIREPIT =
		{
			EMBERS = "我應該去砍點木頭來，是吧？",
			GENERIC = "它要用木頭當燃料。",
			HIGH = "我消耗木頭的速度太快了！",
			LOW = "這附近應該有木頭。",
			NORMAL = "嗯。木頭的味道。",
			OUT = "要是我有木頭就好了。",
		},
		FIRESTAFF = "我不相信這種魔法的東西。",
		FISH = "看起來像鱈魚。",
		FISHINGROD = "我應該去湖邊待一會兒。",
		FISHSTICKS = "優雅又有型的食物。",
		FISHTACOS = "海的味道，對嗎？",
		FISH_COOKED = "真希望能配點薯條。",
		FLINT = "這可以做成斧頭。",
		FLOWER = "很好看。",
		FLOWERHAT = "我覺得它和我的紅頭髮很配。",
		FLOWER_EVIL = "那朵花有問題。",
		FOLIAGE = "看起來像沙拉。",
		FOOTBALLHAT = "這玩意兒會弄亂我的髮型嗎？",
		FROG =
		{
			DEAD = "曾經的青蛙。",
			GENERIC = "我不相信任何不能決定在水裡還是在陸地上生活的生物。",
			SLEEPING = "它累了。",
		},
		FROGGLEBUNWICH = "你可以嚐到沼澤的味道。",
		FROGLEGS = "它們還在跳！",
		FROGLEGS_COOKED = "至少它們不動了。",
		FRUITMEDLEY = "浸了楓糖漿的！",
		GEARS = "我永遠都不可能把這些東西弄清楚的。",
		GHOST = "崩！哈哈！",
		GOLDENAXE = "幾乎趕得上露西了。",
		GOLDENPICKAXE = "它確實很漂亮，但不能用來砍樹。",
		GOLDENPITCHFORK = "我不知道自己為啥要做這個。",
		GOLDENSHOVEL = "是時候去挖點金礦了。",
		GOLDNUGGET = "你無法用黃金做成咖啡桌。\n好吧，也許你可以。但是你不應該那樣做。",
		GRASS =
		{
			BARREN = "我需要在上面施肥。",
			BURNING = "希望這火不會蔓延到樹上。",
			GENERIC = "看起來可以用來點火。",
			PICKED = "表面好粗糙。",
		},
		GREEN_CAP = "我曾經在森林裡吃過更奇怪的東西。",
		GREEN_CAP_COOKED = "我不相信它。",
		GREEN_MUSHROOM =
		{
			GENERIC = "是綠蘑菇。",
			INGROUND = "它們有自己的作息規律。",
			PICKED = "我想我把它弄斷了。",
		},
		GUNPOWDER = "從來沒有做過這種東西。",
		HAMBAT = "真是浪費了美味的火腿。",
		HAMMER = "是人都會犯錯，不是嗎？",
		HEALINGSALVE = "黏黏的藥膏。",
		HEATROCK =
		{
			COLD = "它變冷了，感覺到了嗎？",
			GENERIC = "在家鄉，我們管這種東西叫「夜石」。",
			HOT = "有這東西在我口袋裡，我可以砍一整個冬天的樹！",
			WARM = "它正變得越來越...暖和。",
		},
		HOME = "誰在那兒？",
		HOMESIGN = "有什麼東西是木頭不能做成的嗎？",
		HONEY = "嗯——嗯。蜂王漿。",
		HONEYCOMB = "我差一點就覺得不應該拿這個的。",
		HONEYHAM = "但現在並不是什麼節假日...",
		HONEYNUGGETS = "我最喜歡的食物之一！",
		HORN = "我不確定是不是應該用嘴去吹它。",
		HOUND = "它們應該很擅長拉雪橇。",
		HOUNDBONE = "上面都是狗狗唾液，對嗎？",
		HOUNDMOUND = "我才沒有蠢到去惹那東西。",
		ICEBOX = "啊—— 讓我想起了家鄉。",
		ICEHOUND = "北極獵犬？",
		INSANITYROCK =
		{
			ACTIVE = "它去哪兒了？！",
			INACTIVE = "我不知道該怎麼把那玩意兒移開。",
		},
		JAMMYPRESERVES = "現在就差花生醬了。",
		KABOBS = "樹枝確實讓肉變得更香了。",
		KILLERBEE =
		{
			GENERIC = "那隻蜜蜂好像不太友好。",
			HELD = "他對自己的處境很不滿意。",
		},
		KNIGHT = "麥斯威爾自己的騎警隊。",
		KOALEFANT_SUMMER = "他看上去很美味。",
		KOALEFANT_WINTER = "冬天裡的它們更美味。",
		KRAMPUS = "退後，蠢材！",
		KRAMPUS_SACK = "拿走別人的袋子讓我覺得很不安。",
		LEIF = "我很抱歉我對那些樹做的事！",
		LEIF_SPARSE = "我很抱歉我對那些樹做的事！",
		LIGHTNING_ROD =
		{
			CHARGED = "好像北極光。",
			GENERIC = "現在我不會被閃電劈了。",
		},
		LITTLE_WALRUS = "它們為什麼要住在這麼偏南的地方？",
		LIVINGLOG = "我要留著你，以後你就叫法蘭克吧。",
		LOCKEDWES = "那個傻瓜是誰啊？",
		LOG =
		{
			BURNING = "哦，不！我的勞動成果！",
			GENERIC = "一切都值得了。",
		},
		LUREPLANT = "那是肉嗎？",
		LUREPLANTBULB = "它真暖和，而且是塊狀的。",
		MALE_PUPPET = "你需要幫助嗎？",
		MANDRAKE =
		{
			DEAD = "對不起，小傢伙。",
			GENERIC = "它在看著我。",
			PICKED = "我都幹了什麼？",
		},
		MANDRAKESOUP = "是喝了讓人睏倦的湯。",
		MANDRAKE_COOKED = "抱歉！",
		MARBLE = "感覺像是政府大樓。",
		MARBLEPILLAR = "一定是有人建造的。",
		MARBLETREE = "即使是露西也砍不倒那個。",
		MARSH_BUSH =
		{
			BURNING = "該死！",
			GENERIC = "是荊棘。",
			PICKED = "這麼做值得嗎？",
		},
		MARSH_PLANT = "是植物。",
		MARSH_TREE =
		{
			BURNING = "讓你到處刺人，這就是你的下場！",
			BURNT = "活該。",
			CHOPPED = "雖然是一場很艱苦的戰鬥，但最終我贏了。",
			GENERIC = "是樹就不應該反擊！",
		},
		MAXWELL = "他為什麼要恨我呢？",
		MAXWELLHEAD = "只是一個頭，是嗎？",
		MAXWELLLIGHT = "這有點違反自然規律。",
		MAXWELLLOCK = "鑰匙在哪兒？",
		MAXWELLTHRONE = "我見過比它好的椅子。",
		MEAT = "味道像駝鹿鵝。",
		MEATBALLS = "全都是肉！",
		MEATRACK =
		{
			DONE = "看起來已經曬好了。",
			DRYING = "這就像看著肉慢慢變乾。",
			GENERIC = "它是用來...管它呢，只要加肉就好了。",
		},
		MEAT_DRIED = "感覺像野外求生一樣。",
		MERM = "那東西是從多骯髒的大海裡面爬出來的啊？",
		MERMHEAD = "聞起來像拖網漁船。",
		MERMHOUSE = "它們不是最好使的。",
		MINERHAT = "下煤礦幹活兒了。",
		MONSTERLASAGNA = "這是貓食！",
		MONSTERMEAT = "我還沒有餓到吃怪物肉的地步。",
		MONSTERMEAT_DRIED = "我還是不想吃它。",
		MOSQUITO =
		{
			GENERIC = "那東西吸了我一品脫的血！",
			HELD = "你說我該怎麼處置這小東西呢？",
		},
		MOSQUITOSACK = "很血腥野蠻，對嗎？",
		MOUND =
		{
			DUG = "對不起了！不要纏著我啊！",
			GENERIC = "也許我應該離它遠點。",
		},
		NIGHTLIGHT = "那是什麼樣的黑暗啊？",
		NIGHTMAREFUEL = "我的所有恐懼都匯成了液體，是嗎？",
		
		NIGHTSWORD = "噩夢無法傷害你！",
		NITRE = "我們就是用這個建造鐵路的。",
		ONEMANBAND = "啊，我為你站崗！",
		PANDORASCHEST = "箱子裡裝的是什麼？！",
		PANFLUTE = "我只給露西唱歌。",
		PAPYRUS = "我寧願砍樹也不要寫字。",
		PENGUIN = "走吧！去加拿大！美人兒。",
		PERD = "又是鳥！為什麼總是鳥呢？",
		PEROGIES = "我稱它們為「好吃的餃子」。",
		PETALS = "不知道露西喜不喜歡這些。",
		PETALS_EVIL = "它們正用邪惡的小臉朝我皺眉頭。",
		PICKAXE = "和斧頭差不多，但不完全是斧頭。",
		PIGGYBACK = "豬身上的任何部分我都沒有浪費。",
		PIGHEAD = "真是浪費了這麼好的豬肉。",
		PIGHOUSE =
		{
			FULL = "裡面塞滿了培根。",
			GENERIC = "只需要一點管道膠帶就可以把它修好。",
			LIGHTSOUT = "抱歉！我沒有往裡面看！",
		},
		PIGKING = "他不是我的國王。",
		PIGMAN =
		{
			FOLLOWER = "我們是一個團隊！耶！",
			GENERIC = "給我回來，我的培根！",
			GUARD = "那一隻看起來像是管事的。",
			WEREPIG = "他怎麼了？！",
		},
		PIGSKIN = "帶尾巴的培根。",
		PIGTORCH = "它們是怎麼不用拇指就做到的？",
		PINECONE = 
		{
		    GENERIC = "我應該把它種出來，然後再砍倒它！",
		    PLANTED = "又來了一棵樹！",
		},
		
		PITCHFORK = "這真心不是我的菜。",
		PLANTMEAT = "太噁心了！",
		PLANTMEAT_COOKED = "烤熟了之後也沒有多好吃",
		PLANT_NORMAL =
		{
			GENERIC = "我很好奇它會長成什麼樣。",
			GROWING = "你看著它的話就會感覺它一點都沒長。",
			READY = "可以收穫了。",
		},
		POMEGRANATE = "這東西對我來說太複雜了。",
		POMEGRANATE_COOKED = "把這個放在煎餅上應該會很好。",
		POMEGRANATE_SEEDS = "好多種子。",
		POND = "我不會游泳！",
		POOP = "不要在營地裡拉大便！",
		PUMPKIN = "我討厭吃長在地上的東西。",
		PUMPKINCOOKIE = "吃了這個，就有力氣一直砍樹了。",
		PUMPKIN_COOKED = "我喜歡南瓜派。",
		PUMPKIN_LANTERN = "最好不要把它打翻。",
		PUMPKIN_SEEDS = "這是一顆種子。",
		PURPLEGEM = "沒什麼是優秀伐木工解決不了的。",
		RABBIT =
		{
			GENERIC = "討厭的地松鼠...",
			HELD = "吃掉他會讓我感覺很糟糕。",
		},
		RABBITHOLE = "我很懷疑那下面到底有沒有樹。",
		RAINOMETER = "下雨會讓樹長得快。",
		RATATOUILLE = "我自己做的！",
		RAZOR = "真正的伐木工永遠不會剃鬍子。",
		REDGEM = "我在它裡面看到了成千棵樹在熊熊烈火中死去。",
		RED_CAP = "我不知道...",
		RED_CAP_COOKED = "不是真的餓了我才不會吃這個。",
		RED_MUSHROOM =
		{
			GENERIC = "是紅蘑菇。",
			INGROUND = "它們有自己的作息規律。",
			PICKED = "我想我把它弄斷了。",
		},
		REEDS =
		{
			BURNING = "火讓我緊張。",
			GENERIC = "蘆葦。",
			PICKED = "它們會再長出來的。",
		},
        RUBBLE = "殘破的傢俱。",
		RESEARCHLAB = "我不相信所有這些科學的東西。",
		RESEARCHLAB2 = "這越來越奇怪了。",
		RESEARCHLAB3 = "好吧，我好像明白了。",
		RESURRECTIONSTATUE = "木頭版的我看起來還不錯。",
		RESURRECTIONSTONE = "我不確定是不是應該去碰它。",
		ROBIN =
		{
			GENERIC = "真是下賤的小混蛋。",
			HELD = "不要覺得太舒適了，臭鳥。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "飛到南方去不就行了！",
			HELD = "它在偷取我身體的熱量。",
		},
		ROBOT_PUPPET = "它被困住了！",
		ROCK_LIGHT =
		{
			GENERIC = "不需要木材的營火？太違反自然規律了！",
			OUT = "看起來像是會碎掉一樣。",
			LOW = "需要加點...木材？",
			NORMAL = "不需要木材的營火？太違反自然規律了！",
		},
		ROCK = "如果足夠用勁的話，我應該可以把它鑿碎。",
		ROCKS = "在木頭行不通的時候可以用。",
        ROOK = "嗯...這戰車是直線移動嗎？我忘了。",
		ROPE = "可以用來把不同的東西捆在一起。",
		ROTTENEGG = "這世上將少一隻鳥。很好。",
		SANITYROCK =
		{
			ACTIVE = "那塊石頭有點奇怪，你說呢？",
			INACTIVE = "可以理解。",
		},
		SAPLING =
		{
			BURNING = "唉！他都沒機會長大！",
			GENERIC = "我想要看它長大，那樣我就可以砍掉它了。",
			PICKED = "採摘與砍樹相比真是太沒意思了。",
		},
		SEEDS = "不是樹。",
		SEEDS_COOKED = "我們把它叫做「伐木工的驚喜」。",
		SEWING_KIT = "縫縫補補是我的長項。",
		SHOVEL = "挖洞。種樹！",
		SILK = "看到蜘蛛我就心驚膽戰。",
		SKELETON = "抱歉，朋友。",
		SKULLCHEST = "太嚇人了！",
		SMALLBIRD =
		{
			GENERIC = "你想要什麼？",
			HUNGRY = "它想要什麼東西。",
			STARVING = "我想它應該是很餓了。",
		},
		SMALLMEAT = "真希望它再大點兒。",
		SMALLMEAT_DRIED = "一口就沒了。",
		SPEAR = "比起一把堅實的好斧頭，它的重量還輕了點。",
		SPIDER =
		{
			GENERIC = "那是我見過的最大的蜘蛛！",
			SLEEPING = "現在應該小心點兒，是吧？",
		},
		SPIDERDEN = "好傢伙！看那個東西！",
		SPIDEREGGSACK = "我為什麼要帶著那個東西到處走？",
		SPIDERGLAND = "我覺得它有毒。",
		SPIDERHAT = "這帽子真漂亮，是吧？",
		SPIDERQUEEN = "你可不是我的女王！",
		SPIDER_WARRIOR =
		{
			GENERIC = "他們現在變成黃色了，是吧？",
			SLEEPING = "我可不想吵醒它。",
		},
		SPOILED_FOOD = "呀，就像約翰·迪芬貝克一樣。",
		STATUEHARP = "你的頭不見了，是嗎？",
		STATUEMAXWELL = "他就是個混蛋，不是嗎？",
		STINGER = "哎喲！刺到我了。",
		STRAWHAT = "這樣我的頭就不會被太陽曬到。",
		STUFFEDEGGPLANT = "我的廚藝越來越好了。",
		SUNKBOAT = "那些木頭以前是有過好日子的。",
		SWEATERVEST = "雖然不是格子圖案的，但還湊合。",
		TAFFY = "甜食很好。",
		TALLBIRD = "即使是不會飛的鳥，我也不相信。",
		TALLBIRDEGG = "這裡面是什麼？",
		TALLBIRDEGG_COOKED = "正義得以彰顯的味道。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "你覺得太冷了嗎？",
			GENERIC = "它在孵化。",
			HOT = "它在哭嗎？",
			LONG = "鳥類從來都是不慌不忙的。",
			SHORT = "現在它隨時都可能出來。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "我應該去偷它的蛋，給它點兒教訓。",
			PICKED = "什麼也沒有。",
		},
		TEENBIRD =
		{
			GENERIC = "它將來也會長成一個混球，就像它的父母一樣。",
			HUNGRY = "你一天到晚都很餓嗎？",
			STARVING = "飢餓會讓它變得野蠻。",
		},
		TELEBASE =
		{
			VALID = "它是準備好了，但我呢？",
			GEMS = "需要裝上寶石，是嗎？",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "準備好了，是吧？",
			GENERIC = "我想這應該是個...有魔法的東西。",
			LOCKED = "好像少了點什麼，是吧？",
			PARTIAL = "就快準備好了，是吧？",
		},
		TELEPORTATO_BOX = "四四方方的，是吧？",
		TELEPORTATO_CRANK = "彎彎扭扭的，是吧？",
		TELEPORTATO_POTATO = "看起來像土豆，是吧？",
		TELEPORTATO_RING = "環狀的，是吧？",
		TELESTAFF = "我很好奇這東西幹什麼用的。",
		TENT = "我已經習慣在糟糕的環境中睡覺。",
		TENTACLE = "有魷魚在那下面嗎？",
		TENTACLESPIKE = "這玩意揮舞起來還在左搖右擺呢。",
		TENTACLESPOTS = "我臉紅了！",
		TENTACLE_PILLAR = "好大啊！",
		TENTACLE_PILLAR_ARM = "那些是小魷魚嗎？",
		TENTACLE_GARDEN = "我厭倦了這些魷魚！",
		TOPHAT = "太花俏了。",
		TORCH = "火把讓我又能看到樹了。",
		TRAP = "變聰明了，對嗎？",
		TRAP_TEETH = "做工似乎有點粗糙。",
		TRAP_TEETH_MAXWELL = "這不公平，他耍詐，不是嗎？",
		TREASURECHEST = "木頭太有用處了！看看所有這些用木頭做的東西就知道了！",
		TREASURECHEST_TRAP = "那個箱子有點不太對勁。",

		TRINKET_1 = "我以前玩過那個遊戲。",
		TRINKET_10 = "老年人的牙齒。",
		TRINKET_11 = "你，給我安靜點！",
		TRINKET_12 = "它完全萎縮了。",
		TRINKET_2 = "這不是真的，對不對？",
		TRINKET_3 = "讓我想起了我曾經聽到的一個故事。",
		TRINKET_4 = "不要問我。",
		TRINKET_5 = "它需要一個機器臂，對嗎？",
		TRINKET_6 = "它們再也變不回原來的樣子了，是嗎？",
		TRINKET_7 = "我可以幾個小時不停地玩這個！",
		TRINKET_8 = "如果能找到浴缸，那我會立刻去洗澡。",
		TRINKET_9 = "我剛才在穿衣服的時候已經把衣服鈕釦縫死了。",
		TRUNKVEST_SUMMER = "好看又透氣",
		TRUNKVEST_WINTER = "這應該可以抵禦家鄉的寒冬，對嗎？",
		TRUNK_COOKED = "我想所有鼻涕應該都煮掉了吧。",
		TRUNK_SUMMER = "真的好薄。",
		TRUNK_WINTER = "又厚實又毛茸茸的。",
		TURF_CARPETFLOOR = "太對我的口味了",
		TURF_CHECKERFLOOR = "看起來像城市裡戶外廁所的地板。",
		TURF_DIRT = "只是一些地面，不是嗎？",
		TURF_FOREST = "只是一些地面，不是嗎？",
		TURF_GRASS = "只是一些地面，不是嗎？",
		TURF_MARSH = "只是一些地面，不是嗎？",
		TURF_ROAD = "只是一些地面，不是嗎？",
		TURF_ROCKY = "只是一些地面，不是嗎？",
		TURF_SAVANNA = "只是一些地面，不是嗎？",
		TURF_WOODFLOOR = "適合國王的地板！",
		TURKEYDINNER = "又到火雞節了！",
		TWIGS = "我應該做個小斧頭來砍這些。",
		UMBRELLA = "這可以讓我的鬍子保持乾燥，是吧？",
		UNIMPLEMENTED = "看起來不太安全。",
		WAFFLES = "我更喜歡煎餅。",
		WALL_HAY = "它會使我打噴嚏。",
		WALL_HAY_ITEM = "它會使我打噴嚏。",
		WALL_STONE = "相當安全，不是嗎？",
		WALL_STONE_ITEM = "相當安全，不是嗎？",
		WALL_RUINS = "雖然破碎了，但還是安全的，對嗎？",
		WALL_RUINS_ITEM = "呵，又是石頭做成的，是嗎？",
		WALL_WOOD = "我喜歡它的樣子！",
		WALL_WOOD_ITEM = "我喜歡它的樣子！",
		WALRUS = "不是吧，又是海象！",
		WALRUSHAT = "我爺爺也有一頂這樣的帽子。",
		WALRUS_CAMP =
		{
			EMPTY = "這在冬天會變得不安全。",
			GENERIC = "海象就在附近，是嗎？",
		},
		WALRUS_TUSK = "他有蛀牙，是嗎？",
		WASPHIVE = "那些蜜蜂為什麼這麼生氣？",
		WETGOOP = "比我吃過的一些東西要好！",
		WINTERHAT = "很不錯的無邊帽，是吧？",
		WINTEROMETER = "在家鄉，我們只需要一半的刻度就夠了。",
		WORMHOLE =
		{
			GENERIC = "看起來像屁股！",
			OPEN = "我不確定自己是否真的想進去看看，你說呢？",
		},
		WORMHOLE_LIMITED = "聞起來有點不是味兒，對嗎？",
		ACCOMPLISHMENT_SHRINE = "對我來說似乎有點炫耀的意味。",        		
		LIVINGTREE = "我覺得很矛盾，不是嗎？",
		ICESTAFF = "讓我想起了家鄉。",
	},
	DESCRIBE_GENERIC = "那是什麼，嗯？",
	DESCRIBE_TOODARK = "好黑啊！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "你可以嚐出鳥嘴的味道，對嗎？",
	},
}
