return {


	ACTIONFAIL_GENERIC = "我什么都做不好。",
	ANNOUNCE_ADVENTUREFAIL = "并不是所有死亡都是相似的。",
	ANNOUNCE_BOOMERANG = "噢！这就是报应。",
	ANNOUNCE_CHARLIE = "恶魔！现身吧！",
	ANNOUNCE_CHARLIE_ATTACK = "我被攻击了！",
	ANNOUNCE_COLD = "我感到彻骨的寒冷。",
	ANNOUNCE_CRAFTING_FAIL = "我缺少必要的材料。",
	ANNOUNCE_DUSK = "黑暗很快就要降临了。我必须做好准备。",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "那个不能吃。",
		SPOILED = "这个食物已经接近生命的尾声了。",
		STALE = "不新鲜了吗？",
	},
	ANNOUNCE_ENTER_DARK = "黑暗吞没了我。",
	ANNOUNCE_ENTER_LIGHT = "那儿有光！",
	ANNOUNCE_HOUNDS = "猎犬在狂吠。",
	ANNOUNCE_HUNGRY = "我感到无尽的空虚。",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我感觉附近有野兽。",
	ANNOUNCE_HUNT_LOST_TRAIL = "这个痕迹没有指向任何地方。",
	ANNOUNCE_INV_FULL = "我带不了更多东西了。",
	ANNOUNCE_KNOCKEDOUT = "天啊，好疼！我又一次醒过来了。",
	ANNOUNCE_NOHUNGERSLEEP = "我的胃就像我的心一样空虚，我现在不能睡觉。",
	ANNOUNCE_PECKED = "你在试探我的耐心。",
	ANNOUNCE_QUAKE = "大地在晃动。它会将我整个吞没吗？",
	ANNOUNCE_THORNS = "噢！像我一样扎手。",
	ANNOUNCE_TORCH_OUT = "黑暗再次降临！",
	ANNOUNCE_TRAP_WENT_OFF = "噢，天哪。",
	ANNOUNCE_WORMHOLE = "我又一次出现在这个世界。",
	ANNOUNCE_CANFIX = "\n我觉得我能修好这个！",
	ANNOUNCE_ACCOMPLISHMENT = "这一切都是短暂的。",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "有一天，这个也会被忘记的。",
	BATTLECRY =
	{
		GENERIC = "死亡会找上你的！",
		PIG = "让死亡拥抱你！",
		PREY = "受死吧，虫子！",
		SPIDER = "我会把你送到另一个世界！",
		SPIDER_WARRIOR = "我会干掉你！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "你应该活着，至少目前不能死。",
	},
	DESCRIBE =
	{
		WORMLIGHT = "它发出了轻微的嗡嗡声。",
		WORM =
		{
		    PLANT = "它看起来格格不入。",
		    DIRT = "那里有什么东西吗？",
		    WORM = "它来自洞穴深处。",
		},
		EEL = "一条鳗鱼。",
		EEL_COOKED = "一条熟鳗鱼。",
		UNAGI = "这样看起来更美味。",
		EYETURRET = "我不知道它为什么帮我。",
		EYETURRET_ITEM = "我想我需要放置它。",
		MINOTAURHORN = "一位曾经的伟大野兽留下的全部遗物。",
		MINOTAURCHEST = "天啊，你有一对多么华丽的角！",
		THULECITE_PIECES = "强大材料的碎片。",
		POND_ALGAE = "一些水藻。",
		GREENSTAFF = "我能看见其中深藏的能量火花。",
		POTTEDFERN = "它住在一个笼子里。",

		THULECITE = "它的存在标志着未知的边界。",
		ARMORRUINS = "可以暂缓死亡。",
		RUINS_BAT = "我将远古的力量握在了手中。",
		RUINSHAT = "阿比盖尔会喜欢这个王冠的。",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "我不知道阴影中潜伏着什么。",	
			WARN = "我可以感觉到虎视眈眈的眼睛。",	
			WAXING = "它们接近了。", 
			STEADY = "它们就在我身边！", 
			WANING = "我想它们应该正在离去。", 
			DAWN = "快要结束了。", 
			NOMAGIC = "我孤单一人。", 
		},
		BISHOP_NIGHTMARE = "时间赢得了这场战斗。",
		ROOK_NIGHTMARE = "时间会侵蚀一切。",
		KNIGHT_NIGHTMARE = "另一场输给时间的战斗。",
		MINOTAUR = "被困在这样一个小小的牢笼中，他肯定很孤独。",	
		SPIDER_DROPPER = "黑暗褪去了它们身上的颜色。",	
		NIGHTMARELIGHT = "它从地下汲取能量。",	
		RELIC = "令人想起過去的景象。",	
		RUINS_RUBBLE = "一堆破碎的梦。",	
		MULTITOOL_AXE_PICKAXE = "一个用途多多的工具。",	
		GREENGEM = "瑕疵是它最美丽的特质。",
		ORANGESTAFF = "每次使用它时，我都会死亡并重生。",	
		YELLOWAMULET = "我黑暗生活中的一道短暂光芒。",	
		GREENAMULET = "才华的闪光！",	

		SLURPER = "啊，这么简单。",
		SLURPER_PELT = "一个空的饥饿口袋。",
		ARMORSLURPER = "贴身、沉闷、有生命的装束。",
		ORANGEAMULET = "临时从苦差中解脱。",
		YELLOWSTAFF = "这根魔杖和我的灵魂一样扭曲。",
		YELLOWGEM = "这让我想起了我妈妈。",
		ORANGEGEM = "这些东西过去曾给我带来快乐。",
		TELEBASE = 
		{
			VALID = "能量从中流过。",
			GEMS = "传送焦点是如此死气沉沉。",
		},
		GEMSOCKET = 
		{
			VALID = "宝石让能量聚集了。",
			GEMS = "它看上去如此空虚。",
		},
		STAFFLIGHT = "我几乎能做出一个小小的太阳能系统。",
		RESEARCHLAB4 = "距离疯狂只有一步之遥。",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="它很漂亮。",
			LONG = "这是我姐姐的花。她去了很远的地方。",
			MEDIUM = "我能感觉到阿比盖尔的气息越来越强了。",
			SOON = "阿比盖尔就快到了！",
			HAUNTED_POCKET = "阿比盖尔准备好了，但她需要一点空间。",
			HAUNTED_GROUND = "我需要教阿比盖尔怎么玩。",

		},

        ANCIENT_ALTAR = "它充满了死亡的回音。",
        ANCIENT_ALTAR_BROKEN = "我听到了死者的痛苦回声。",
        ANCIENT_STATUE = "不太有吸引力。",

        LICHEN = "它是怎么长成那样的？",
		CUTLICHEN = "就像生命一样转瞬即逝。",
		CAVE_BANANA = "它们的皮看起来很危险。",
		CAVE_BANANA_COOKED = "热香蕉泥要美味多了。",
		CAVE_BANANA_TREE = "可怜的植物，永远不见天日。",
		ROCKY = "他们看到了多么可怕的景象。",


		BLUEAMULET = "熟悉的寒冷拥抱。",
		PURPLEAMULET = "正在渗出怪影。",
		TELESTAFF = "如果它更强大一些，我就可以解脱了。",
		MONKEY = "不用动脑地活着肯定很爽。",
		MONKEYBARREL = "真脏。",
		MONSTERLASAGNA = "弄熟的恶魔还是恶魔，在千层饼中也不会改变。",
		HOUNDSTOOTH="连根拔起。",
		ARMORSNURTLESHELL="现在我可以躲开麻烦了。",
		BAT="夜行生物。",
		BATBAT = "一件被施了魔法的武器。多么令人兴奋！",
		BATWING="要是我也能飞走就好了。",
		BATWING_COOKED="它们曾经拥有如此大的潜力。",
		BEDROLL_FURRY="我要用死去动物的毛皮把自己包裹起来。",
		BUNNYMAN="它们的内心世界一定备受折磨。",
		FLOWER_CAVE="它看起来很脆弱。",
		FLOWER_CAVE_DOUBLE="它看起来很脆弱。",
		FLOWER_CAVE_TRIPLE="它看起来很脆弱。",
		GUANO="这是生命不可避免的副产品。",
		LANTERN="昏暗地照出前方的路。",
		LIGHTBULB="它在慢慢燃尽光亮。",
		MANRABBIT_TAIL="毛茸茸、软绵绵的，尽显其本质。",
		MUSHTREE_TALL  ="这是一些奇怪的树。",
		MUSHTREE_MEDIUM="它看起来像一顶腐烂的帽子。",
		MUSHTREE_SMALL ="有小地精生活在这里吗？",
		RABBITHOUSE="它并不像看上去那样是可以吃的。",
		SLURTLE="它盲目地追逐着石头。",
		SLURTLE_SHELLPIECES="尖壳蜗牛梦想的碎片。",
		SLURTLEHAT="我觉得它对我的帮助不会比对前主人的帮助多。",
		SLURTLEHOLE="尖壳蜗牛长得太大的时候就会从里面出来。",
		SLURTLESLIME="它闪烁着微光，看上去就很黏。",
		SNURTLE="那个蜗牛的壳更大。",
		SPIDER_HIDER="一只胆小的蜘蛛。",
		SPIDER_SPITTER="它在嚼着什么东西。",
		SPIDERHOLE="这里到处都是蜘蛛。",
		STALAGMITE="大地慷慨地奉献了这些岩石。",
		STALAGMITE_FULL="大地慷慨地奉献了这些岩石。",
		STALAGMITE_LOW="大地慷慨地奉献了这些岩石。",
		STALAGMITE_MED="大地慷慨地奉献了这些岩石。",
		STALAGMITE_TALL="大地的奇观。",
		STALAGMITE_TALL_FULL="大地的奇观。",
		STALAGMITE_TALL_LOW="大地的奇观。",
		STALAGMITE_TALL_MED="大地的奇观。",

		TURF_CARPETFLOOR = "一些地皮。",
		TURF_CHECKERFLOOR = "一些地皮。",
		TURF_DIRT = "一些地皮。",
		TURF_FOREST = "一些地皮。",
		TURF_GRASS = "一些地皮。",
		TURF_MARSH = "一些地皮。",
		TURF_ROAD = "一些地皮。",
		TURF_ROCKY = "一些地皮。",
		TURF_SAVANNA = "一些地皮。",
		TURF_WOODFLOOR = "一些地皮。",

		TURF_CAVE="一些地皮。",
		TURF_FUNGUS="一些地皮。",
		TURF_SINKHOLE="一些地皮。",
		TURF_UNDERROCK="一些地皮。",
		TURF_MUD="一些地皮。",

		POWCAKE = "我要不是饿疯了绝不会吃它。",		
		CAVE_ENTRANCE = 
		{
			GENERIC="有人不想让别人进入地下。",
			OPEN = "地表之下潜伏着巨大的邪恶。",
		},
        CAVE_EXIT = "地面在召唤我。",
		BOOMERANG = "死亡会回到发镖者身上。",
		MAXWELLPHONOGRAPH = "我们要跳一场死亡之舞吗？",
		ABIGAIL = "那是我的孪生姐姐，阿比盖尔。",
		PIGGUARD = "这头小猪看上去脾气不好。",
		ADVENTURE_PORTAL = "这是哪门子的技术恐怖行动？",
		AMULET = "我想知道过去它属于谁。",
		ANIMAL_TRACK = "野兽的痕迹。",
		ARMORGRASS = "我延迟了不可避免的死亡。",
		ARMORMARBLE = "停下那把刺向我心脏的利刃。",
		ARMORWOOD = "穿着这个，我或许能拖延一下不可避免的死亡。",
		ARMOR_SANITY = "最安全的发疯方法。",
		ASH =
		{
			GENERIC = "另一场熊熊大火过后只剩下这些。",
			REMAINS_EYE_BONE = "当我传送时，这个眼骨被烧成了灰烬！",
			REMAINS_THINGIE = "在被烧毁前，它曾经是某样东西…",
		},
		AXE = "用于工业和谋杀的工具。",
		BABYBEEFALO = "享受你的童年。很快你就会知道真实世界的残酷。",
		BACKPACK = "一个背包。现在我可以背起更多重负了。",
		BACONEGGS = "吃了这份营养均衡的早餐，新的悲惨一天又开始了。",
		BANDAGE = "我还会再次受伤的。",
		BASALT = "尝试破坏它是毫无意义的。",
		BEARDHAIR = "真脏。",
		BEDROLL_STRAW = "睡眠只是短暂的死亡。",
		BEE =
		{
			GENERIC = "我要避开毒刺。",
			HELD = "别乱动，小家伙。",
		},
		BEEBOX =
		{
			GENERIC = "它们得去劳动，这样我才有东西偷。",
			READY = "它们的辛勤工作收获颇丰!",
		},
		BEEFALO =
		{
			FOLLOWER = "他跟着我走向他的末日。",
			GENERIC = "那些眼睛背后一定藏有什么疯狂的想法。",
			NAKED = "他现在赤身裸体了。",
			SLEEPING = "他肯定在做噩梦。",
		},
		BEEFALOHAT = "我应该盖住我的脑袋。",
		BEEFALOWOOL = "在某个地方，一头牦牛正光着身子受冻。",
		BEEHAT = "有了这个，我再也不用害怕那些快乐的嗡嗡声，也不用害怕那些毒刺了。",
		BEEHIVE = "充满渣滓和花粉的可悲蜂窝。",
		BEEMINE = "它们在那里面还是活的。可怜的小东西。",
		BERRIES = "这些浆果很酸。",
		BERRIES_COOKED = "味道更协调，但过不了多久它们就会腐烂。",
		BERRYBUSH =
		{
			BARREN = "它荒芜了。",
			GENERIC = "一份点心，也许吧？",
			PICKED = "我必须等着。",
		},
		BIRDCAGE =
		{
			GENERIC = "我们中的一些人可以看到我们的笼子。",
			OCCUPIED = "他现在更开心了。",
			SLEEPING = "他死了吗？不，只是睡着了而已。",
		},
		BIRDTRAP = "树枝和蜘蛛丝也能变得致命。",
		BIRD_EGG = "这么多的希望都化为乌有了。",
		BIRD_EGG_COOKED = "它再也孵不出小鸟了。",
		BISHOP = "他在祈祷什么？",
		BLOWDART_SLEEP = "甚至都不会让目标沉睡，只会造成短暂的休眠。",
		BLOWDART_PIPE = "我从这一端吹气，另一端出来的是痛苦。",
		BLOWDART_FIRE = "我该烧掉整个世界吗？",
		BLUEGEM = "忧郁的蓝色，就像...呃...一只悲伤的鸟？",
		BLUEPRINT = "绘制这个的人可能已经死了。",
		BLUE_CAP = "单调乏味的菌类。",
		BLUE_CAP_COOKED = "全都是有韧性的。",
		BLUE_MUSHROOM =
		{
			GENERIC = "发霉的。",
			INGROUND = "如果可以的话，我也想藏起来。",
			PICKED = "采掉了。",
		},
		BOARDS = "对树木来说更可怕。",
		BONESTEW = "它们死了，然后我将它们炖成了一锅汤。",
		BUGNET = "小虫子的监狱。",
		BUSHHAT = "噢，我可以隐身了。",
		BUTTER = "我可没想到会有这个。",
		BUTTERFLY =
		{
			GENERIC = "美丽的生命，如昙花一现。",
			HELD = "它的生命掌握在我的手中。",
		},
		BUTTERFLYWINGS = "那只蝴蝶再也不能飞了。",
		BUTTERFLYMUFFIN = "看你如何逃出这个甜蜜陷阱！",
		CAMPFIRE =
		{
			EMBERS = "黑暗快要降临了。",
			GENERIC = "我也许能熬过今晚！",
			HIGH = "地狱般的景象！",
			LOW = "黑暗来袭。",
			NORMAL = "这是一堆营火。",
			OUT = "这不是个好兆头。",
		},
		CANE = "我的速度快到不能更快了。",
		CARROT = "这是一根胡萝卜。",
		CARROT_COOKED = "这是一根经过烈火考验的胡萝卜。",
		CARROT_PLANTED = "这是一根种在地里的胡萝卜。",
		CARROT_SEEDS = "有一天，这颗种子将变成一根胡萝卜。",
		CAVE_FERN = "黑暗中的一抹颜色。",
		CHARCOAL = "冰冷死寂，如同我的内心。",
        CHESSJUNK1 = "冰冷、没有生机的人造生命。",
        CHESSJUNK2 = "冰冷、没有生机的人造生命。",
        CHESSJUNK3 = "冰冷、没有生机的人造生命。",
		CHESTER = "一只空虚的毛球。",
		CHESTER_EYEBONE =
		{
			GENERIC = "它看向了我灵魂的深处。",
			WAITING = "与其说是睡眠...不如说是等待。",
		},
		COOKEDMANDRAKE = "死得很有价值。他会很美味的。",
		COOKEDMEAT = "血被烤干了。",
		COOKEDMONSTERMEAT = "弄熟的恶魔还是恶魔。",
		COOKEDSMALLMEAT = "火净化了它。",
		CORN = "我可以说个关于玉米的老掉牙笑话，但我会克制的。",
		CORN_COOKED = "这个玉米热得爆开了花。",
		CORN_SEEDS = "是的，这是一颗种子。",
		CROW =
		{
			GENERIC = "把你的嘴从我的心上拔出来！",
			HELD = "他是我的。",
		},
		CUTGRASS = "我喜欢杀死一些小东西。",
		CUTREEDS = "我喜欢割东西。",
		CUTSTONE = "方便用来做墓碑。",
		DEADLYFEAST = "这是我最后的晚餐。",
		DEERCLOPS = "死亡的化身！",
		DEERCLOPS_EYEBALL = "它肯定看到了什么可怕的东西。",
		DEPLETED_GRASS =
		{
			GENERIC = "一丛草的遗迹。",
		},
		DIRTPILE = "噢看看，更多的泥土。",
		DIVININGROD =
		{
			COLD = "源头在很远的地方。",
			GENERIC = "它永远在寻找失去的另一半。",
			HOT = "这里有邪恶的东西！",
			WARM = "邪恶逼近了。",
			WARMER = "现在已经非常接近了。",
		},
		DIVININGRODBASE =
		{
			GENERIC = "这个新奇玩意有什么用处？",
			READY = "它还需要一把大钥匙。",
			UNLOCKED = "看看我能找到什么！",
		},

		DRAGONFRUIT = "它的形状一点也不像龙。",
		DRAGONFRUIT_COOKED = "还是没有变成龙。至少它是死的。",
		DRAGONFRUIT_SEEDS = "这是一颗种子。它不会长成一条龙。",
		DRAGONPIE = "好吧，至少它现在做成派了。",
		DRUMSTICK = "可以用来打鼓，而且很有营养！",
		DRUMSTICK_COOKED = "烤熟点，更美味。",
		DUG_BERRYBUSH = "我喜欢它死去，但我应该把这个种下。",
		DUG_GRASS = "我喜欢它死去，但我应该把这个种下。",
		DUG_MARSH_BUSH = "我喜欢它死去，但我应该把这个种下。",
		DUG_SAPLING = "我喜欢它死去，但我应该把这个种下。",
		DURIAN = "多刺而难闻！",
		DURIAN_COOKED = "刺少了，但气味甚至更重了！",
		DURIAN_SEEDS = "真是奇迹，这些种子不臭。",
		EARMUFFSHAT = "它们最终保护我抵御严寒。",
		EGGPLANT = "差一点就是致命的颠茄了。就差一点点。",
		EGGPLANT_COOKED = "煮熟这个茄子可以使它不那么致命。",
		EGGPLANT_SEEDS = "这是一颗茄子种子。",
		EVERGREEN =
		{
			BURNING = "它在熊熊燃烧。",
			BURNT = "油尽灯枯。",
			CHOPPED = "万物皆有一死。",
			GENERIC = "大自然真是无聊。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "它在熊熊燃烧。",
			BURNT = "油尽灯枯。",
			CHOPPED = "万物皆有一死。",
			GENERIC = "它的生命循环结束了。",
		},
		EYEPLANT = "它们对主人言听必从。",
		FARMPLOT =
		{
			GENERIC = "我该种什么种子？",
			GROWING = "枝繁叶茂的卷须盘绕在泥土上。",
			NEEDSFERTILIZER = "这块土地冰凉而没有生机。",
		},
		FEATHERHAT = "嚓嚓！",
		FEATHER_CROW = "乌鸦羽毛，像永夜一样漆黑。",
		FEATHER_ROBIN = "红雀羽毛，鲜红似血。",
		FEATHER_ROBIN_WINTER = "雪雀的羽毛，就像隧道尽头的光一样白。",
		FEM_PUPPET = "我想知道她干了什么。",
		FIREFLIES =
		{
			GENERIC = "黑暗中的微光。",
			HELD = "从我的口袋洒向外界的微光。",
		},
		FIREHOUND = "他的性情暴躁如火。",
		FIREPIT =
		{
			EMBERS = "黑暗快要降临了。",
			GENERIC = "我也许能熬过今晚！",
			HIGH = "地狱般的景象！",
			LOW = "黑暗来袭。",
			NORMAL = "这是一堆营火。",
			OUT = "这不是个好兆头。",
		},
		FIRESTAFF = "我可以点燃这个世界！",
		FISH = "它为了活命绝望地挣扎。可怜的傻瓜。",
		FISHINGROD = "用这个我能把鱼从它们珍贵安全的小池塘里拽出来。",
		FISHSTICKS = "精心打造的鱼肉块。",
		FISHTACOS = "希望我把鱼刺都剔出来了。",
		FISH_COOKED = "烤上一会儿，它们就不会扑腾了。",
		FLINT = "一个刀刃状的小石头。",
		FLOWER = "它们明亮又活泼。真讨厌。",
		FLOWERHAT = "但我正在哀悼...",
		FLOWER_EVIL = "至少比别的花要好。",
		FOLIAGE = "它在迷惑我。",
		FOOTBALLHAT = "我可以把这个死去的东西戴在头上。太好了。",
		FROG =
		{
			DEAD = "生命渺小而短暂。",
			GENERIC = "他个子很小而且全身是包。",
			SLEEPING = "他睡着了。",
		},
		FROGGLEBUNWICH = "我从没想过蛙腿可以看上去这么棒。",
		FROGLEGS = "它是从青蛙身上扯下来的。",
		FROGLEGS_COOKED = "肯定不会再抽筋了。",
		FRUITMEDLEY = "装在杯子里，酸酸甜甜的。",
		GEARS = "机械恶魔的内心。",
		GHOST = "他从坟墓里跑出来！",
		GOLDENAXE = "至少我可以更有格调地杀死树了。",
		GOLDENPICKAXE = "至少我可以更有格调地挖矿了。",
		GOLDENPITCHFORK = "至少我可以更有格调地铲地皮了。",
		GOLDENSHOVEL = "至少我可以更有格调地挖东西了。",
		GOLDNUGGET = "我会把它带在身上。",
		GRASS =
		{
			BARREN = "它需要施肥。",
			BURNING = "闻起来怪怪的。",
			GENERIC = "这只是一丛草。",
			PICKED = "它被杀死了。",
		},
		GREEN_CAP = "这个蘑菇太普通了，真让人失望。",
		GREEN_CAP_COOKED = "全都是有韧性的。",
		GREEN_MUSHROOM =
		{
			GENERIC = "它又湿又冷。",
			INGROUND = "如果可以的话，我也想藏起来。",
			PICKED = "采掉了。",
		},
		GUNPOWDER = "这是一条我踏上的黑暗之路。",
		HAMBAT = "用死亡制造死亡。",
		HAMMER = "噢，我可能会摧毁这个世界。",
		HEALINGSALVE = "生命带来痛苦，痛苦带来生命。",
		HEATROCK =
		{
			COLD = "只是一块有些冰凉的石头。",
			GENERIC = "它待在那里，占据着空间。",
			HOT = "烧得最亮的也会最快烧尽。",
			WARM = "像其他石头一样微温而没有生机。",
		},
		HOMESIGN = "我做了个标记，不过是暂时的。",
		HONEY = "甜蜜而短暂的一餐。",
		HONEYCOMB = "散乱的蜂窝碎片。",
		HONEYHAM = "死去的肉块，蘸满甜蜜的酱汁。",
		HONEYNUGGETS = "死去的肉块，蘸满甜蜜的酱汁。",
		HORN = "听起来里面似乎困着一头牦牛。",
		HOUND = "退后，恶魔的肮脏手下！",
		HOUNDBONE = "邪恶野兽的遗骨。",
		HOUNDMOUND = "最邪恶的生物的巢穴。",
		ICEBOX = "像我的心一样冰冷。",
		ICEHOUND = "他有一颗冰冷、死寂的心。",
		INSANITYROCK =
		{
			ACTIVE = "它在呼唤我的名字。",
			INACTIVE = "它乌黑冰冷。",
		},
		JAMMYPRESERVES = "份量很完美的果酱。",
		KABOBS = "从肉块中间刺穿的肉串。",
		KILLERBEE =
		{
			GENERIC = "一只凶狠无情的蜜蜂。",
			HELD = "别乱动，小家伙。",
		},
		KNIGHT = "一匹冰冷的、没有灵魂的马。",
		KOALEFANT_SUMMER = "一只孤独的野兽。",
		KOALEFANT_WINTER = "它抵抗着残酷的天气。",
		KRAMPUS = "你好啊，地下的邪恶生物。",
		KRAMPUS_SACK = "闻起来一股羊膻味。",
		LEIF = "一只动作迟缓的野兽。",
		LEIF_SPARSE = "一只动作迟缓的野兽。",
		LIGHTNING_ROD =
		{
			CHARGED = "即使是这样的力量也会耗尽。",
			GENERIC = "将毁灭的力量聚集于一处。",
		},
		LITTLE_WALRUS = "暴力周而复始，仍在继续。",
		LIVINGLOG = "它永远在无声地尖叫。",
		LOCKEDWES = "被麦斯威尔的雕像困住，获得永生。",
		LOG = "如果树木可以说话，它们看到这个会尖叫的。",
		LUREPLANT = "它吞食万物。",
		LUREPLANTBULB = "生命在继续。",
		MALE_PUPPET = "我想知道他干了什么。",
		MANDRAKE =
		{
			DEAD = "唉，可怜的曼德拉草！",
			GENERIC = "强大的曼德拉草。我应该在晚上来采摘它。",
			PICKED = "前进，我的蔬菜部下！",
		},
		MANDRAKESOUP = "他被煮死了。",
		MARBLE = "光滑而没有生机。",
		MARBLEPILLAR = "即使是石头，也经不起天长地久的腐蚀。",
		MARBLETREE = "这棵冰冷的树里没有生命的脉动。",
		MARSH_BUSH =
		{
			BURNING = "就连刺木也会燃烧。",
			GENERIC = "总是能造成伤痛的灌木丛。",
			PICKED = "为了采它我受了伤。",
		},
		MARSH_PLANT = "这是一株植物。",
		MARSH_TREE =
		{
			BURNING = "它在燃烧。",
			BURNT = "像我的心一样黑。",
			CHOPPED = "它的针叶没能保护它。",
			GENERIC = "一棵只能感受到痛苦的树。",
		},
		MAXWELL = "他让我觉得有一种奇怪的亲切感。",
		MAXWELLHEAD = "他确实对戏剧有品味。",
		MAXWELLLIGHT = "多么奇妙的光芒。",
		MAXWELLLOCK = "看起来充满魔力。",
		MAXWELLTHRONE = "跟我期望的不太一样。",
		MEAT = "依旧血腥。",
		MEATBALLS = "肉丸。太让人兴奋了。",
		MEATRACK =
		{
			DONE = "肉晾好了。",
			DRYING = "它在干燥的风中晃来晃去。",
			GENERIC = "我可以把肉挂在这里。",
		},
		MEAT_DRIED = "肉晾干了，很美味。",
		MERM = "可怕的沼泽怪物！",
		MERMHEAD = "一点尊严都没有。",
		MERMHOUSE = "时间的洗礼让它破旧不堪。",
		MINERHAT = "解放双手的照明工具！",
		MONSTERMEAT = "邪恶在里面蔓延。",
		MONSTERMEAT_DRIED = "肉晾干了，味道有点怪。",
		MOSQUITO =
		{
			GENERIC = "它以吸血为生。",
			HELD = "我能感觉到它偷来的鲜血的温热。",
		},
		MOSQUITOSACK = "从蚊子身上掉落下来的血囊。我爱这玩意。",
		MOUND =
		{
			DUG = "大地吐露了它的秘密。",
			GENERIC = "总有一天，我会加入你们的。",
		},
		NIGHTLIGHT = "怪异但美丽。",
		NIGHTMAREFUEL = "这东西随着睡梦而来。",
		NIGHTSWORD = "噩梦渐渐变得尖锐，铸成了这把利剑。",
		NITRE = "这是人类的愚蠢带来的产物。",
		ONEMANBAND = "我曾经在类似的乐器中享受这样的快乐。",
		PANDORASCHEST = "生活是一场赌博。",
		PANFLUTE = "音乐是通向我空虚灵魂的窗户。",
		PAPYRUS = "用于记录我的痛苦。",
		PENGUIN = "全都衣冠楚楚，但是去哪呢？",
		PERD = "笨鸟！离我的浆果远点！",
		PEROGIES = "小巧可爱的营养饺子。",
		PETALS = "我摧毁了美丽的东西。",
		PETALS_EVIL = "它们用我的灵魂着色。",
		PICKAXE = "有了这个，我或许可以挖穿地球。",
		PIGGYBACK = "它们在死后更有用。",
		PIGHEAD = "杀了这只猪，沥干他的血。",
		PIGHOUSE =
		{
			FULL = "我希望他过得愉快。",
			GENERIC = "至少这些屋子很舒适。",
			LIGHTSOUT = "现在我完全孤单了。",
		},
		PIGKING = "陛下，尽您所能逍遥快活吧。",
		PIGMAN =
		{
			DEAD = "他现在日子更好了。",
			FOLLOWER = "我还是觉得孤单。",
			GENERIC = "他们真不友好。",
			GUARD = "真是奥威尔式的做派。",
			WEREPIG = "夜行生物！",
		},
		PIGSKIN = "曾经是一只猪身上的皮。",
		PIGTORCH = "它驱散了黑暗。",
		PINECONE = 
		{
		    GENERIC = "藏身于脆弱死亡中的渺小生命。",
		    PLANTED = "一棵树很快就会长出来。",
		},
		PITCHFORK = "多么邪恶的工具！",
		PLANTMEAT = "它的气味很难闻。",
		PLANTMEAT_COOKED = "烹饪过后味道只好了一点点。",
		PLANT_NORMAL =
		{
			GENERIC = "一株可食用的植物。",
			GROWING = "继续生长吧。我会等着的。",
			READY = "可以收获了。",
		},
		POMEGRANATE = "这么多可以咬碎挤扁的多汁红色果肉！",
		POMEGRANATE_COOKED = "变热了，但还是那么麻烦。",
		POMEGRANATE_SEEDS = "我原本期望那东西能多产点种子。",
		POND = "奥菲莉娅，你在下面吗？",
		POOP = "生命的特征就是血和这个。",
		PUMPKIN = "它和我心里的洞一样大。",
		PUMPKINCOOKIE = "我自己做的！",
		PUMPKIN_COOKED = "热量让它萎缩了一点点。我喜欢这样。",
		PUMPKIN_LANTERN = "你并没有那么吓人。",
		PUMPKIN_SEEDS = "这是一颗种子。真令人兴奋。",
		PURPLEGEM = "紫得就像一个...紫色的东西。",
		RABBIT =
		{
			GENERIC = "他盲目地四处游荡，对自己的命运一无所知。",
			HELD = "他在我的怀里很安全。",
		},
		RABBITHOLE = "我个子太大了，没办法掉到洞下面去。",
		RAINOMETER = "它能测出是否有雨。我喜欢沉闷的天气。",
		RATATOUILLE = "一大锅烩蔬菜，非常吸引人。",
		RAZOR = "仅用于剃毛。",
		REDGEM = "像我的鲜血一样红。",
		RED_CAP = "知心的蘑菇。",
		RED_CAP_COOKED = "全都是有韧性的。",
		RED_MUSHROOM =
		{
			GENERIC = "它湿湿的。",
			INGROUND = "如果可以的话，我也想藏起来。",
			PICKED = "采掉了。",
		},
		REEDS =
		{
			BURNING = "很快就化为灰烬了。",
			GENERIC = "这只是一簇芦苇。",
			PICKED = "我已经采摘了它们。",
		},
        RELIC = 
        {
            GENERIC = "远古世界的遗物。",
            BROKEN = "破碎的石块",
        },
        RUINS_RUBBLE = "一堆破碎的梦。",
		RESEARCHLAB = "我会学到无法形容的事情。",
		RESEARCHLAB2 = "我会学到无法形容的事情。",
		RESEARCHLAB3 = "我学到了无法形容的事情。",
		RESURRECTIONSTATUE = "我只是将不可避免的死亡延迟了。",
		RESURRECTIONSTONE = "一个无足轻重的守卫。",
		ROBIN =
		{
			GENERIC = "这意味着春天来了吗？希望不是。",
			HELD = "他喜欢被困在我的口袋里。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "寒荒之地的生命。",
			HELD = "它如此柔软。它是我的敌人。",
		},
		ROBOT_PUPPET = "我想知道它干了什么。",
		ROCK_LIGHT =
		{
			GENERIC = "裹了石皮的熔岩坑。",
			OUT = "它看起来无害。",
			LOW = "阴影来袭。",
			NORMAL = "熔岩着火了。",
		},
		ROCK = "连这个都不是永恒的。",
		ROCKS = "一些小石头。",
        ROOK = "战车？还是城堡？",
		ROPE = "这会是一种轻松的解脱方式。",
		ROTTENEGG = "万物皆如此。",
		SANITYROCK =
		{
			ACTIVE = "它在召唤我。",
			INACTIVE = "就连这个方尖碑也离我而去了。",
		},
		SAPLING =
		{
			BURNING = "交给火焰了。",
			GENERIC = "它在努力生长。",
			PICKED = "也许下次吧，小树苗。",
		},
		SEEDS = "生命，或者至少是孕育生命的希望。",
		SEEDS_COOKED = "我烤死了它们。",
		SEWING_KIT = "另一种推迟不可避免的耐久下降的方法。",
		SHOVEL = "我可能会挖掘出什么可怕的秘密？",
		SILK = "如此光滑而精美。",
		SKELETON = "他解脱了，我很嫉妒。",
		SKULLCHEST = "那里面应该有我的死亡警告。",
		SMALLBIRD =
		{
			GENERIC = "小家伙，你好。",
			HUNGRY = "你身体里面空虚吗？",
			STARVING = "一个黑洞，种子有去无回。",
		},
		SMALLMEAT = "闻起来像小小的恐惧。",
		SMALLMEAT_DRIED = "肉晾干了，很美味。",
		SPEAR = "我成了世界的毁灭者。",
		SPIDER =
		{
			DEAD = "总有一天我们会重逢。",
			GENERIC = "夜行生物！",
			SLEEPING = "恶魔睡着了。",
		},
		SPIDERDEN = "一窝乌合之众。",
		SPIDEREGGSACK = "满是死亡和毁灭的小包裹。",
		SPIDERGLAND = "即使死去，这只野兽仍能制造伤痛。",
		SPIDERHAT = "是时候凝视深渊了。",
		SPIDERQUEEN = "她像帝王般残酷。",
		SPIDER_WARRIOR =
		{
			DEAD = "唉，勇敢的战士。",
			GENERIC = "夜行勇士！",
			SLEEPING = "我必须小心。",
		},
		SPOILED_FOOD = "最终一切都会变成垃圾。",
		STATUEHARP = "也许这些雕像将一直伴我左右。",
		STATUEMAXWELL = "他把我带来这里。",
		STINGER = "锋利而致命。",
		STRAWHAT = "我应该盖住我的脑袋。",
		STUFFEDEGGPLANT = "一只茄子，里面大概没有塞满毒药。",
		SUNKBOAT = "残忍的骗局！",
		SWEATERVEST = "我可以穿上这件背心，它是用一块块死去的东西做成的！",
		TAFFY = "从没想过我可以做出这么甜蜜的东西。",
		TALLBIRD = "摆脱天空的桎梏。",
		TALLBIRDEGG = "充满了潜力。",
		TALLBIRDEGG_COOKED = "所有希望都被夺走了。和培根搭配起来不赖。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "因黑暗而感到寒冷。",
			GENERIC = "小小的脆弱生命，正在挣扎着迎向光明。",
			HOT = "它承受不了这样的高温。",
			LONG = "越早诞生，越早消亡。",
			SHORT = "就快出来了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "这个蛋代表了一个新生命。呃。",
			PICKED = "巢是空的。空虚、 贫瘠 而虚无。",
		},
		TEENBIRD =
		{
			GENERIC = "你也要离开我吗？",
			HUNGRY = "我们都想填补空虚。",
			STARVING = "你露出了本性！",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我确信下一个地方会更可怕！",
			GENERIC = "它不会带来什么好事。",
			LOCKED = "它仍然是上锁关闭的状态。",
			PARTIAL = "它是建成了一半，还是有一半被摧毁了？",
		},
		TELEPORTATO_BOX = "它包含着至关重要的火花。",
		TELEPORTATO_CRANK = "它看起来很复杂。",
		TELEPORTATO_POTATO = "多么丑陋的产物！",
		TELEPORTATO_RING = "它没有锋利的边缘。",
		TENT = "睡眠只是死亡的预演。",
		TENTACLE = "又瘦又长又危险！",
		TENTACLESPOTS = "这些事最好略过不提。",
		TENTACLESPIKE = "锋利、黏滑而危险。",
        TENTACLE_PILLAR = "所以这就是下面的情况了。",
        TENTACLE_PILLAR_ARM = "小触手！",
        TENTACLE_GARDEN = "这东西是不同的。",
		TOPHAT = "我应该盖住我的脑袋。",
		TORCH = "对抗黑夜的小小武器。",
		TRAP = "小小的草也变得致命了。",
		TRAP_TEETH = "来自地下的卑劣意外。",
		TRAP_TEETH_MAXWELL = "猝不及防的死亡。",
		TREASURECHEST = "它装着我的财富。",
		TRINKET_1 = "非常奇异。",
		TRINKET_10 = "另一张要喂饱的嘴。",
		TRINKET_11 = "幸运的机器人，它永远都不会有灵魂。",
		TRINKET_12 = "不再那么黏滑了，不是吗？",
		TRINKET_2 = "这是假的。只是一种诱惑，就像死亡一样。",
		TRINKET_3 = "要是小刀能解决我的更多问题该有多好...",
		TRINKET_4 = "我会带着这个，直到世界末日。",
		TRINKET_5 = "如果它再大点的话，我会乘着它笔直飞向太阳。",
		TRINKET_6 = "曾经因通电而有了生命，现在已经走到了尽头。",
		TRINKET_7 = "只是一个简单的游戏。",
		TRINKET_8 = "我希望可以洗个澡。",
		TRINKET_9 = "不搭的纽扣，乱搭的人生。",
		TRUNKVEST_SUMMER = "穿在我皮肤上的一层皮肤。",
		TRUNKVEST_WINTER = "它也许能温暖我的身体，但对我的灵魂有什么用呢？",
		TRUNK_COOKED = "现在看上去更糟了。",
		TRUNK_SUMMER = "我更喜欢耳朵。",
		TRUNK_WINTER = "和它唯一的朋友分开了。",
		TURKEYDINNER = "谁在咯咯叫？",
		TWIGS = "还没长大就被拔出了土地。",
		UMBRELLA = "云在流泪。",
		WAFFLES = "它们肯定是华夫饼。",
		WALL_HAY = "只能做做防御的样子。",
		WALL_HAY_ITEM = "它们的防御效果值得怀疑。",
		WALL_STONE = "在里面又有什么来保护我呢？",
		WALL_STONE_ITEM = "这不能抵御内心的恶魔。",
		WALL_RUINS = "这些墙并没能保护古人，不是吗！",
		WALL_RUINS_ITEM = "这些石头会闹鬼吗？",
		WALL_WOOD = "现在我可以延迟不可避免的死亡。",
		WALL_WOOD_ITEM = "捆起来的木头。",
		WALRUS = "一个属于海洋的老人家。",
		WALRUSHAT = "这下面泄露了怎样的狂热想法？",
		WALRUS_CAMP =
		{
			EMPTY = "如果它们不在这，那它们会在哪里？",
			GENERIC = "我担心这个家并不温馨。",
		},
		WALRUS_TUSK = "我要把你咬碎。",
		WASPHIVE = "它们躲在仇恨的堡垒里。",
		WETGOOP = "一团糟糕的东西，就像生活一样。",
		WINTERHAT = "这有助于延缓寒冷的侵袭。",
		WINTEROMETER = "我怎么觉得像在计算我的死期？",
		WORMHOLE =
		{
			GENERIC = "生命并非总是有意义。",
			OPEN = "不论多少东西都填不饱它的胃口。",
		},
		ACCOMPLISHMENT_SHRINE = "我向来不太关心隐喻。",
		LIVINGTREE = "它会长生不死吗？",
		ICESTAFF = "有冰冻效果的魔杖。",
	},
	DESCRIBE_GENERIC = "没法说。",
	DESCRIBE_TOODARK = "黑暗！太黑了！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "我让它免于经历生活的痛苦。",
	},
}
