return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Je ne vais pas essayer ça tant qu'il est éveillé.",
			GENERIC = "Impossible de raser ça !",
			NOBITS = "Il ne reste pas le moindre poil !",
		},
		STORE =
		{
			GENERIC = "C'est plein.",
			NOTALLOWED = "Ça rentre pas là-dedans.",
		},
	},
	ACTIONFAIL_GENERIC = "Je ne peux pas faire ça !",
	ANNOUNCE_ADVENTUREFAIL = "Ça n'a pas marché. Je dois recommencer.",
	ANNOUNCE_BEES = "DES ABEILLES !!!!!",
	ANNOUNCE_BOOMERANG = "Oh ! Je devrais essayer d'attraper ça !",
	ANNOUNCE_CHARLIE = "C'était quoi ça ?",
	ANNOUNCE_CHARLIE_ATTACK = "Ouille ! Je me suis fait mordre !",
	ANNOUNCE_COLD = "Il fait si froid !",
	ANNOUNCE_CRAFTING_FAIL = "Il me manque des ingrédients.",
	ANNOUNCE_DEERCLOPS = "Ça doit être une grosse bête !",
	ANNOUNCE_DUSK = "Il se fait tard. La nuit va tomber.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Miam !",
		PAINFUL = "Je ne me sens pas très bien.",
		SPOILED = "Beurk ! C'était atroce !",
		STALE = "Ça commençait à se périmer.",
	},
	ANNOUNCE_ENTER_DARK = "Il fait si sombre !",
	ANNOUNCE_ENTER_LIGHT = "Je peux voir à nouveau !",
	ANNOUNCE_FREEDOM = "Je suis libre ! Enfin libre !",
	ANNOUNCE_HIGHRESEARCH = "Je suis trop intelligent maintenant !",
	ANNOUNCE_HOUNDS = "Vous avez entendu ça ?",
	ANNOUNCE_HUNGRY = "J'ai tellement faim !",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Cette piste est fraîche, la bestiole ne doit pas être bien loin.",
	ANNOUNCE_HUNT_LOST_TRAIL = "La piste s'arrête ici.",
	ANNOUNCE_INV_FULL = "Je ne peux plus rien porter !",
	ANNOUNCE_KNOCKEDOUT = "Aïe, ma tête !",
	ANNOUNCE_LOWRESEARCH = "Ça ne m'a pas appris grand-chose.",
	ANNOUNCE_MOSQUITOS = "Ah ! Punaise !",
	ANNOUNCE_NODANGERSLEEP = "Trop dangereux pour l'instant !",
	ANNOUNCE_NODAYSLEEP = "Il y a trop de lumière.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Je ne suis pas fatigué.",
	ANNOUNCE_NOHUNGERSLEEP = "J'ai trop faim pour dormir, les gargouillements me réveilleraient !",
	ANNOUNCE_NO_TRAP = "Ha, c'était facile.",
	ANNOUNCE_PECKED = "Ouille ! Arrête !",
	ANNOUNCE_QUAKE = "J'aime pas ce genre de bruit.",
	ANNOUNCE_RESEARCH = "Il ne faut jamais cesser d'apprendre !",
	ANNOUNCE_THORNS = "Ho !",
	ANNOUNCE_TORCH_OUT = "Ma lumière vient de s'éteindre !",
	ANNOUNCE_TRAP_WENT_OFF = "Mince...",
	ANNOUNCE_UNIMPLEMENTED = "Oh ! C'est pas encore prêt.",
	ANNOUNCE_WORMHOLE = "C'était pas le truc le plus sensé à faire.",
	ANNOUNCE_CANFIX = "\nJe dois pouvoir réparer ça !",
	ANNOUNCE_ACCOMPLISHMENT = "Quel accomplissement !",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Si mes amis pouvaient me voir en ce moment...",	
	BATTLECRY =
	{
		GENERIC = "Vise les yeux !",
		PIG = "Hé ! Cochon, cochon !",
		PREY = "Je vais te détruire !",
		SPIDER = "Je vais te piétiner à mort !",
		SPIDER_WARRIOR = "Plutôt toi que moi !",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Qui c'est le plus fort ?",
		PIG = "Je le laisse partir. Pour cette fois.",
		PREY = "Trop rapide !",
		SPIDER = "Trop moche de toute façon.",
		SPIDER_WARRIOR = "Bouh ! Sale bestiole !",
	},
	DESCRIBE =
	{
		WORMLIGHT = "Ça a l'air délicieux.",
		WORM =
		{
		    PLANT = "Ça me parait sûr.",
		    DIRT = "On dirait juste un tas de terre.",
		    WORM = "C'est un ver !",
		},

		EEL = "Ça va faire un délicieux repas.",
		EEL_COOKED = "Ça sent super bon !",
		UNAGI = "C'est moi qui l'ai fait !",
		EYETURRET = "J'espère qu'elle ne va pas s'en prendre à moi.",
		EYETURRET_ITEM = "Je crois qu'elle dort.",
		MINOTAURHORN = "Waouh ! Heureusement qu'il ne m'a pas encorné !",
		MINOTAURCHEST = "Ça pourrait contenir un truc fantastique plus gros ! Ou atroce !",
		THULECITE_PIECES = "Des morceaux de thulécite plus petits.",
		POND_ALGAE = "Des algues près d'une mare.",
		GREENSTAFF = "Ça va servir.",
		POTTEDFERN = "Une fougère dans un pot.",

		THULECITE = "Je me demande d'où ça vient.",
		ARMORRUINS = "C'est curieusement léger.",
		RUINS_BAT = "C'est plutôt lourd.",
		RUINSHAT = "Pour un roi. Ou pour moi.",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "Tout va bien.",
		WARN = "Ça devient magique par ici.",
		WAXING = "Je crois que ça se concentre de plus en plus !",
		STEADY = "On dirait que ça reste régulier.",
		WANING = "On dirait que ça s'évanouit.",
		DAWN = "Le cauchemar est presque parti !",
		NOMAGIC = "Aucune magie par ici.",
		},
		BISHOP_NIGHTMARE = "Tout s'écroule !",
		ROOK_NIGHTMARE = "Terrifiant !",
		KNIGHT_NIGHTMARE = "C'est un cauchemar !",
		MINOTAUR = "Il n'a pas l'air heureux.",
		SPIDER_DROPPER = "Note personnelle : ne pas lever la tête.",
		NIGHTMARELIGHT = "Je me demande à quoi ça servait.",
		GREENGEM = "Une gemme toute verte.",
		RELIC = "Du vieux matériel ménager.",
		RUINS_RUBBLE = "Ça peut se réparer.",
		MULTITOOL_AXE_PICKAXE = "C'est brillant !",
		ORANGESTAFF = "C'est mieux que la marche.",
		YELLOWAMULET = "Chaud au toucher.",
		GREENAMULET = "Et dire que je croyais que tout allait déjà pour le mieux.",
		SLURPERPELT = "C'est quasiment pareil mort.",	

		SLURPER = "Trop poilu !",
		SLURPER_PELT = "C'est quasiment pareil mort.",
		ARMORSLURPER = "Une tenue mouillée, consistante et délicieuse.",
		ORANGEAMULET = "La téléportation ça peut être super pratique.",
		YELLOWSTAFF = "Je place une gemme sur un bâton.",
		YELLOWGEM = "Cette gemme est jaune",
		ORANGEGEM = "C'est une gemme orange",
		TELEBASE = 
		{
			VALID = "Elle est prête !",
			GEMS = "Il me faut plus de gemmes pourpres.",
		},
		GEMSOCKET = 
		{
			VALID = "On dirait que c'est prêt.",
			GEMS = "Il me faut une gemme.",
		},
		STAFFLIGHT = "Ça semble vraiment dangereux.",
		RESEARCHLAB4 = "Qui a trouvé un nom pareil ?",
	
        ANCIENT_ALTAR = "Une structure ancienne et mystérieuse.",

        ANCIENT_ALTAR_BROKEN = "On dirait que c'est cassé.",

        ANCIENT_STATUE = "Elle semble en décalage avec le monde.",

        LICHEN = "Seule une cyanobactérie pourrait pousser avec cette lumière.",
		CUTLICHEN = "Nutritif, mais périssable.",

		CAVE_BANANA = "C'est tout mou.",
		CAVE_BANANA_COOKED = "Miam !",
		CAVE_BANANA_TREE = "La photosynthèse n'a sans doute rien à voir ici.",
		ROCKY = "Il a des griffes terrifiantes.",
		
		COMPASS =
		{
			GENERIC="J'arrive pas à la faire marcher.",
			N = "Nord",
			S = "Sud",
			E = "Est",
			W = "Ouest",
			NE = "Nord-est",
			SE = "Sud-est",
			NW = "Nord-ouest",
			SW = "Sud-ouest",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "Je crois que ça se concentre de plus en plus !",
			STEADY = "On dirait que ça reste régulier.",
			WANING = "On dirait que ça s'évanouit.",
			DAWN = "Le cauchemar est presque parti !",
			WARN = "Ça devient magique par ici.",
			CALM = "Tout va bien.",
			NOMAGIC = "Aucune magie par ici.",
		},

		HOUNDSTOOTH="C'est pointu !",
		ARMORSNURTLESHELL="Ça me colle au dos.",
		BAT="Argh ! C'est terrifiant !",
		BATBAT = "Je parie que je pourrais voler si j'en attrapais deux.",
		BATWING="Je déteste ces choses, même mortes.",
		BATWING_COOKED="Au moins il ne reviendra pas.",
		BEDROLL_FURRY="Si chaud et si confortable.",
		BUNNYMAN="Je ressens un urgent besoin de faire de la science.",
		FLOWER_CAVE="Elle brille grâce à la science.",
		FLOWER_CAVE_DOUBLE="Il brille grâce à la science.",
		FLOWER_CAVE_TRIPLE="Il brille grâce à la science.",
		GUANO="De la crotte d'une odeur différente.",
		LANTERN="Une lumière plus civilisée.",
		LIGHTBULB="Curieusement, ça a l'air super bon.",
		MANRABBIT_TAIL="Rien qu'à toucher, c'est bon.",
		MUSHTREE_TALL  ="Ce champignon est devenu trop grand, c'est mauvais pour lui.",
		MUSHTREE_MEDIUM="Il en poussait dans ma salle de bain.",
		MUSHTREE_SMALL ="Hallucinogène ?",
		RABBITHOUSE="Ce n'est pas une vraie carotte.",
		SLURTLE="Beurk... C'est... beurk.",
		SLURTLE_SHELLPIECES="Une énigme sans solution.",
		SLURTLEHAT="J'espère que ça ne va pas me décoiffer.",
		SLURTLEHOLE="Un repaire de « beurk ».",
		SLURTLESLIME="Si ce n'était pas utile, je n'y toucherais pas.",
		SNURTLE="Il est moins moche, mais toujours moche.",
		SPIDER_HIDER="Bah ! Encore des araignées !",
		SPIDER_SPITTER="Je déteste les araignées.",
		SPIDERHOLE="C'est recouvert de vieilles toiles.",
		STALAGMITE="On dirait bien un caillou.",
		STALAGMITE_FULL="On dirait bien un caillou.",
		STALAGMITE_LOW="On dirait bien un caillou.",
		STALAGMITE_MED="On dirait bien un caillou.",
		STALAGMITE_TALL="Des cailloux, des cailloux, des cailloux...",
		STALAGMITE_TALL_FULL="Des cailloux, des cailloux, des cailloux...",
		STALAGMITE_TALL_LOW="Des cailloux, des cailloux, des cailloux...",
		STALAGMITE_TALL_MED="Des cailloux, des cailloux, des cailloux...",

		TURF_CARPETFLOOR = "Étonnant comme ça gratte.",
		TURF_CHECKERFLOOR = "C'est plutôt chouette.",
		TURF_DIRT = "Un morceau de sol.",
		TURF_FOREST = "Un morceau de sol.",
		TURF_GRASS = "Un morceau de sol.",
		TURF_MARSH = "Un morceau de sol.",
		TURF_ROAD = "Des pavés taillés à la hâte.",
		TURF_ROCKY = "Un morceau de sol.",
		TURF_SAVANNA = "Un morceau de sol.",
		TURF_WOODFLOOR = "Des lattes de plancher.",

		TURF_CAVE="Encore un autre type de sol.",
		TURF_FUNGUS="Encore un autre type de sol.",
		TURF_SINKHOLE="Encore un autre type de sol.",
		TURF_UNDERROCK="Encore un autre type de sol.",
		TURF_MUD="Encore un autre type de sol.",

		POWCAKE = "Je suis pas sûr d'avoir si faim que ça.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Je me demande si je peux déplacer ce rocher.",
            OPEN = "Je parie qu'il y a plein de trucs à découvrir par ici !",
        },
        CAVE_EXIT = "J'ai fait assez de découvertes pour l'instant.",
		MAXWELLPHONOGRAPH = "C'est donc de là que venait la musique.",
		BOOMERANG = "Aérodynamique !",
		PIGGUARD = "Il n'a pas l'air aussi sympa que les autres.",
		ABIGAIL = "Ahhh, elle a un joli petit nœud.",
		ADVENTURE_PORTAL = "Je suis pas certain de vouloir refaire ça une deuxième fois.",
		AMULET = "Je me sens tellement sécurisé quand je porte ça.",
		ANIMAL_TRACK = "Des traces de nourriture. Enfin... des traces d'animal.",
		ARMORGRASS = "J'espère qu'il n'y a pas d'insectes là-dedans.",
		ARMORMARBLE = "Ça a l'air vraiment lourd.",
		ARMORWOOD = "C'est un vêtement tout à fait sensé.",
		ARMOR_SANITY = "En portant ça je me sens en sécurité et en danger.",
		ASH =
		{
			GENERIC = "C'est tout ce qu'il reste quand le feu a fait son œuvre.",
			REMAINS_EYE_BONE = "L'os-œil a brûlé quand je me suis téléporté !",
			REMAINS_THINGIE = "Ça devait être quelque chose avant de brûler...",
		},
		AXE = "C'est ma fidèle hache.",
		BABYBEEFALO = "Oh ! Tellement mignon !",
		BACKPACK = "C'est pour ranger mes trucs.",
		BACONEGGS = "C'est moi qui l'ai fait !",
		BANDAGE = "Ça m'a l'air bien stérile.",
		BASALT = "Trop solide pour être cassé !",
		BATBAT = "Je parie que je pourrais voler si j'en attrapais deux.",
		BEARDHAIR = "Je les ai faits avec mon visage.",
		BEDROLL_STRAW = "Ça sent l'humidité.",
		BEE =
		{
			GENERIC = "Happy apiculteur.",
			HELD = "Attention !",
		},
		BEEBOX =
		{
			FULLHONEY = "C'est plein de miel.",
			GENERIC = "Des abeilles !",
			NOHONEY = "C'est vide.",
			SOMEHONEY = "Je devrais attendre un peu.",
		},
		BEEFALO =
		{
			FOLLOWER = "Il suit paisiblement.",
			GENERIC = "C'est un bœufalo !",
			NAKED = "Ho, il est si triste.",
			SLEEPING = "C'est vraiment des gros dormeurs.",
		},
		BEEFALOHAT = "Un bien joli chapeau.",
		BEEFALOWOOL = "Ça sent comme les larmes de bœufalo.",
		BEEHAT = "Ça devrait me protéger.",
		BEEHIVE = "Quelle activité bourdonnante.",
		BEEMINE = "Ça bourdonne quand je la secoue.",
		BEEMINE_MAXWELL = "De la rage de moustique en conserve !",
		BERRIES = "Les baies rouges sont les meilleures.",
		BERRIES_COOKED = "Je ne crois pas que chaleur leur ait fait du bien.",
		BERRYBUSH =
		{
			BARREN = "Je crois qu'il faudrait fertiliser ça.",
			GENERIC = "Les baies rouges sont les meilleures.",
			PICKED = "Est-ce que ça repoussera ?",
		},
		BIRDCAGE =
		{
			GENERIC = "Je devrais y mettre un oiseau.",
			OCCUPIED = "C'est mon oiseau !",
			SLEEPING = "Ha... il dort.",
		},
		BIRDTRAP = "Ça me donne un net avantage !",
		BIRD_EGG = "Un œuf normal et petit.",
		BIRD_EGG_COOKED = "Ça a l'air drôlement bon !",
		BISHOP = "Arrière, prédicateur !",
		BLOWDART_FIRE = "Ça semble fondamentalement risqué.",
		BLOWDART_SLEEP = "Ne surtout pas inspirer...",
		BLOWDART_PIPE = "Un bon entraînement pour souffler mes bougies !",
		BLUEAMULET = "Froid comme la glace !",
		BLUEGEM = "Ça étincelle d'énergie froide.",
		BLUEPRINT = "C'est scientifique !",
		BLUE_CAP = "C'est bizarre et gluant.",
		BLUE_CAP_COOKED = "C'est plus pareil maintenant...",
		BLUE_MUSHROOM =
		{
			GENERIC = "C'est un champignon.",
			INGROUND = "Il dort.",
			PICKED = "Je me demande s'il va repousser.",
		},
		BOARDS = "Des planches.",
		BOAT = "C'est avec ça que je suis arrivé ici ?",
		BONESTEW = "C'est moi qui l'ai fait !",
		BUGNET = "Pour choper des insectes.",
		BUSHHAT = "Ça gratte un peu.",
		BUTTER = "Du beurre ? C'est pas possible !",
		BUTTERFLY =
		{
			GENERIC = "Le papillon papillonne.",
			HELD = "Je te tiens !",
		},
		BUTTERFLYMUFFIN = "C'est moi qui l'ai fait !",
		BUTTERFLYWINGS = "Sans elles, c'est juste une chenille.",
		CAMPFIRE =
		{
			EMBERS = "Je devrais mettre quelque chose dans le feu avant qu'il ne s'éteigne.",
			GENERIC = "Plus fort que les ténèbres.",
			HIGH = "Ce feu devient incontrôlable !",
			LOW = "Le feu faiblit.",
			NORMAL = "Chaud et confortable.",
			OUT = "Bon, c'est terminé.",
		},
		CANE = "Marcher devient si facile !",
		CARROT = "Beurk. C'est un légume.",
		CARROT_COOKED = "De la bouillie.",
		CARROT_PLANTED = "La terre fait pousser des bébés légumes.",
		CARROT_SEEDS = "C'est des graines.",
		CAVE_FERN = "C'est une fougère.",
		CHARCOAL = "C'est petit, noir et ça sent le bois brûlé.",
        CHESSJUNK1 = "Un tas de pièces d'échec brisées.",
        CHESSJUNK2 = "Un autre tas de pièces d'échec brisées.",
        CHESSJUNK3 = "Un autre tas de pièces d'échec brisées.",
		CHESTER = "M. Otto von Chesterfield",
		CHESTER_EYEBONE =
		{
			GENERIC = "Il m'observe.",
			WAITING = "Il s'est endormi.",
		},
		COOKEDMANDRAKE = "Pauvre petit bonhomme",
		COOKEDMEAT = "Grillée à la perfection.",
		COOKEDMONSTERMEAT = "C'est juste un peu plus appétissant comme ça que cru.",
		COOKEDSMALLMEAT = "Je ne risque plus d'avoir des vers !",
		COOKPOT =
		{
			COOKING_LONG = "Ça va prendre un moment.",
			COOKING_SHORT = "Presque fini !",
			DONE = "Miammm ! À table !",
			EMPTY = "Rien qu'à le regarder, ça me donne faim.",
		},
		CORN = "Haute teneur en fructose !",
		CORN_COOKED = "Haute teneur en fructose !",
		CORN_SEEDS = "C'est des graines.",
		CROW =
		{
			GENERIC = "Ça fout les jetons !",
			HELD = "C'est pas la fête là-dedans.",
		},
		CUTGRASS = "De l'herbe coupée pour créer et fabriquer.",
		CUTREEDS = "Des roseaux coupés, je vais pouvoir créer et m'amuser.",
		CUTSTONE = "Je les ai adoucies à merveille.",
		DEADLYFEAST = "Un plat très puissant.",
		DEERCLOPS = "C'est énorme !",
		DEERCLOPS_EYEBALL = "C'est vraiment dégueu.",
		DEPLETED_GRASS =
		{
			GENERIC = "Sans doute une touffe d'herbe.",
		},
		DEVTOOL = "Ça sent le bacon !",
		DEVTOOL_NODEV = "Je ne suis pas assez fort pour soulever ça.",
		DIRTPILE = "C'est un tas de terre... ou est-ce... ?",
		DIVININGROD =
		{
			COLD = "Le signal est très faible.",
			GENERIC = "Un genre d'appareil à tête chercheuse.",
			HOT = "Ce truc devient fou !",
			WARM = "Je vais dans la bonne direction.",
			WARMER = "Je ne dois plus être très loin.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Je me demande à quoi ça sert.",
			READY = "On dirait qu'il faut une grosse clé.",
			UNLOCKED = "Ma machine va pouvoir marcher !",
		},
		DIVININGRODSTART = "Ce bâton a l'air utile !",
		DRAGONFRUIT = "Quel étrange fruit.",
		DRAGONFRUIT_COOKED = "Toujours bizarre.",
		DRAGONFRUIT_SEEDS = "C'est des graines.",
		DRAGONPIE = "C'est moi qui l'ai faite !",
		DRUMSTICK = "Je devrais l'engloutir.",
		DRUMSTICK_COOKED = "C'est meilleur comme ça.",
		DUG_BERRYBUSH = "Je devrais planter ça.",
		DUG_GRASS = "Je devrais planter ça.",
		DUG_MARSH_BUSH = "Je devrais planter ça.",
		DUG_SAPLING = "Je devrais planter ça.",
		DURIAN = "Aïe ! Quelle odeur !",
		DURIAN_COOKED = "Maintenant il sent encore plus mauvais !",
		DURIAN_SEEDS = "C'est des graines.",
		EARMUFFSHAT = "Au moins, j'aurai chaud aux oreilles...",
		EGGPLANT = "Ça ne ressemble pas à un œuf.",
		EGGPLANT_COOKED = "Cuit c'est plus de la bas-bergine.",
		EGGPLANT_SEEDS = "C'est des graines.",
		EVERGREEN =
		{
			BURNING = "Que de bouffe gaspillée.",
			BURNT = "Je trouve que j'aurais pu éviter ça.",
			CHOPPED = "Prends ça, nature !",
			GENERIC = "Juste un sapin.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Que de bouffe gaspillée.",
			BURNT = "Je trouve que j'aurais pu éviter ça.",
			CHOPPED = "Prends ça, nature !",
			GENERIC = "Un arbre sans pommes de pin. C'est triste.",
		},
		EYEPLANT = "Je crois qu'on m'observe.",
		FARMPLOT =
		{
			GENERIC = "Je devrais semer des graines.",
			GROWING = "Allez les plantes, allez !",
			NEEDSFERTILIZER = "Je crois qu'il faudrait fertiliser ça.",
		},
		FEATHERHAT = "JE SUIS UN OISEAU !",
		FEATHER_CROW = "Une plume de corbeau.",
		FEATHER_ROBIN = "Une plume d'oiseau rouge",
		FEATHER_ROBIN_WINTER = "Une plume d'oiseau des neiges.",
		FEM_PUPPET = "Elle est piégée !",
		FIREFLIES =
		{
			GENERIC = "Si seulement je pouvais les attraper !",
			HELD = "Elles font briller ma poche !",
		},
		FIREHOUND = "Celui-ci est brillant.",
		FIREPIT =
		{
			EMBERS = "Je devrais mettre quelque chose dans le feu avant qu'il ne s'éteigne.",
			GENERIC = "Plus fort que les ténèbres.",
			HIGH = "Heureusement qu'il y a les pierres !",
			LOW = "Le feu faiblit.",
			NORMAL = "Chaud et confortable.",
			OUT = "Au moins je pourrai m'en resservir.",
		},
		FIRESTAFF = "Je n'ai pas envie de mettre le monde en feu.",

		FISH = "J'ai à manger pour la journée.",
		FISHINGROD = "Un hameçon, une ligne et un bâton !",
		FISHSTICKS = "C'est moi qui les ai faits !",
		FISHTACOS = "C'est moi qui les ai faits !",
		FISH_COOKED = "Parfaitement grillé.",
		FLINT = "Une pierre très coupante.",
		FLOWER = "C'est joli mais ça sent juste la ferme.",
		FLOWERHAT = "Une odeur charmante.",
		FLOWER_EVIL = "Beurk ! Tellement mauvais !",
		FOLIAGE = "Un feuillage bien touffu.",
		FOOTBALLHAT = "J'aime pas le sport.",
		FROG =
		{
			DEAD = "Elle en a eu cro... assez.",
			GENERIC = "Elle est trop mignonne !",
			SLEEPING = "Ha... regardez-la dormir !",
		},
		FROGGLEBUNWICH = "C'est moi qui l'ai fait !",
		FROGLEGS = "On dit que c'est un mets délicat.",
		FROGLEGS_COOKED = "On dirait du poulet.",
		FRUITMEDLEY = "C'est moi qui l'ai faite !",
		GEARS = "Un tas de pièces mécaniques",
		GHOST = "En tant que scientifique, je trouve ça vexant.",
		GOLDENAXE = "Ça c'est une hache qu'elle est chouette.",
		GOLDENPICKAXE = "Hé ? L'or c'est mou , non ?",
		GOLDENPITCHFORK = "Pourquoi j'ai fait une fourche aussi chouette ?",
		GOLDENSHOVEL = "Je suis pressé de creuser des trous.",
		GOLDNUGGET = "Ça ne se mange pas, mais ça brille.",
		GRASS =
		{
			BARREN = "Faudrait de l'engrais.",
			BURNING = "Ça brûle vite !",
			GENERIC = "Une touffe d'herbe.",
			PICKED = "Elle a été coupée dans sa prime jeunesse.",
		},
		GREEN_CAP = "Il a l'air plutôt normal.",
		GREEN_CAP_COOKED = "C'est plus pareil maintenant...",
		GREEN_MUSHROOM =
		{
			GENERIC = "C'est un champignon.",
			INGROUND = "Il dort.",
			PICKED = "Je me demande s'il va repousser.",
		},
		GUNPOWDER = "On dirait du poivre.",
		HAMBAT = "Ça a l'air insalubre.",
		HAMMER = "Stop ! C'est l'heure ! Ça va détruire !",
		HEALINGSALVE = "Si ça pique c'est que ça marche.",
		HEATROCK =
		{
			COLD = "C'est une pierre froide.",
			GENERIC = "Je pourrais changer sa température.",
			HOT = "Joli et bien chaud !",
			WARM = "C'est assez chaud et doux... pour un caillou !",
		},
		HOME = "Quelqu'un doit vivre ici.",
		HOMESIGN = "C'est marqué : « Vous êtes ici ».",
		HONEY = "Ça a l'air délicieux !",
		HONEYCOMB = "Il y avait des abeilles là-dedans.",
		HONEYHAM = "C'est moi qui l'ai faite !",
		HONEYNUGGETS = "C'est moi qui les ai faits !",
		HORN = "On dirait que c'est un champ de bœufalos par là.",
		HOUND = "T'es pas beau gosse, molosse !",
		HOUNDBONE = "Sinistre.",
		HOUNDMOUND = "Un tas d'os de molosse.",
		ICEBOX = "J'ai exploité les pouvoirs du froid !",
		ICEHOUND = "Il y a des molosses à chaque saison ? ",
		INSANITYROCK =
		{
			ACTIVE = "PRENDS ÇA, ÇA TE SOIGNERA !",
			INACTIVE = "C'est plus une pyramide qu'un obélisque.",
		},
		JAMMYPRESERVES = "C'est moi qui l'ai faite !",
		KABOBS = "C'est moi qui les ai faites !",
		KILLERBEE =
		{
			GENERIC = "Oh non ! Une abeille tueuse !",
			HELD = "Ça a l'air dangereux.",
		},
		KNIGHT = "Regardez-moi ça !",
		KOALEFANT_SUMMER = "Délicieusement adorable.",
		KOALEFANT_WINTER = "Il a l'air chaud et riche en viande.",
		KRAMPUS = "Il en veut à mes biens !",
		KRAMPUS_SACK = "Beurk... il y a de la bave de krampus partout.",
		LEIF = "C'est énorme !",
		LEIF_SPARSE = "C'est énorme !",
		LIGHTNING_ROD =
		{
			CHARGED = "Le pouvoir est à moi !",
			GENERIC = "Je peux exploiter les cieux !",
		},
		LITTLE_WALRUS = "Il ne restera pas si mignon éternellement.",
		LIVINGLOG = "Il a l'air inquiet.",
		LOCKEDWES = "Maxwell se fait piéger par ses propres statues.",
		LOG =
		{
			BURNING = "C'est du bois chaud !",
			GENERIC = "C'est gros, c'est lourd, c'est du bois.",
		},
		LUREPLANT = "Tellement charmant.",
		LUREPLANTBULB = "Je vais pouvoir lancer ma propre ferme à viande.",
		MALE_PUPPET = "Il est piégé !",
		MANDRAKE =
		{
			DEAD = "La racine de mandragore a d'étranges pouvoirs.",
			GENERIC = "On raconte des choses bizarres sur cette plante.",
			PICKED = "Arrête de me suivre !",
		},
		MANDRAKESOUP = "C'est moi qui l'ai faite !",
		MANDRAKE_COOKED = "Elle n'a plus l'air si bizarre.",
		MARBLE = "Beau !",
		MARBLEPILLAR = "Je crois que ça pourrait me servir.",
		MARBLETREE = "Une hache ne le coupera pas.",
		MARSH_BUSH =
		{
			BURNING = "Ça brûle vite !",
			GENERIC = "Il y a plein d'épines.",
			PICKED = "Ça fait mal.",
		},
		MARSH_PLANT = "C'est une plante.",
		MARSH_TREE =
		{
			BURNING = "Des épines et du feu !",
			BURNT = "Maintenant il est brûlé et piquant.",
			CHOPPED = "Bien moins piquant maintenant !",
			GENERIC = "Ces épines ont vraiment l'air pointu !",
		},
		MAXWELL = "Je déteste ce mec.",
		MAXWELLHEAD = "Je peux voir jusque dans ses pores.",
		MAXWELLLIGHT = "Je me demande comment ça marche.",
		MAXWELLLOCK = "On dirait presque une serrure.",
		MAXWELLTHRONE = "Ça n'a pas l'air très confortable.",
		MEAT = "Ça sent le gibier, mais ça ira.",
		MEATBALLS = "C'est moi qui les ai faites !",
		MEATRACK =
		{
			DONE = "À la viande !",
			DRYING = "La viande est longue à sécher.",
			GENERIC = "Je devrais sécher de la viande.",
		},
		MEAT_DRIED = "Juste séchée comme il faut",
		MERM = "Ça sent le poisson !",
		MERMHEAD = "Le truc le plus puant que j'aie senti aujourd'hui.",
		MERMHOUSE = "Qui peut vivre là-dedans ?",
		MINERHAT = "Avec ça, j'aurai les mains libres.",
		MONKEY = "Étrange petit bonhomme.",
		MONKEYBARREL = "Ça vient de bouger ?",
		MONSTERLASAGNA = "C'est moi qui les ai faites !",
		MONSTERMEAT = "Pouah... Je ne devrais pas manger ça.",
		MONSTERMEAT_DRIED = "Viande séchée à l'odeur étrange",
		MOSQUITO =
		{
			GENERIC = "Dégoûtant petit suceur de sang.",
			HELD = "Hé ? C'est mon sang ?",
		},
		MOSQUITOSACK = "Ce n'est sans doute pas le sang de quelqu'un d'autre...",
		MOUND =
		{
			DUG = "Je devrais avoir honte de ce que je viens de faire.",
			GENERIC = "Je parie qu'il y a plein de trucs bien par ici !",
		},
		NIGHTLIGHT = "Ça produit une lumière inquiétante.",
		NIGHTMAREFUEL = "Ce truc est dingue !",
		NIGHTSWORD = "C'est moi qui l'ai rêvée !",
		NITRE = "Je ne suis pas géologue.",
		ONEMANBAND = "J'aurais dû ajouter une cloche de bœufalo.",
		PANDORASCHEST = "Ça pourrait contenir un truc fantastique ! Ou atroce !",
		PANFLUTE = "Je peux donner une sérénade aux animaux.",
		PAPYRUS = "Des feuilles de papier.",
		PENGUIN = "Ça doit être la saison des amours.",
		PERD = "Crétin d'oiseau ! Laisse mes baies tranquilles !",
		PEROGIES = "C'est moi qui les ai faits !",
		PETALS = "Ces fleurs ont vu qui était le patron !",
		PETALS_EVIL = "Je suis pas sûr qu'il faille prendre ça.",
		PICKAXE = "Emblématique, pas vrai ?",
		PIGGYBACK = "Je suis pas super fier de moi pour ça.",
		PIGHEAD = "On dirait une offrande à la bête.",
		PIGHOUSE =
		{
			FULL = "On dirait qu'un groin colle à la vitre.",
			GENERIC = "Ces cochons ont de bien jolies cabanes.",
			LIGHTSOUT = "Allez ! Je sais que t'es chez toi !",
		},
		PIGKING = "Beurk, il pue !",
		PIGMAN =
		{
			DEAD = "Quelqu'un devrait prévenir sa famille.",
			FOLLOWER = "Il fait partie de mes amis.",
			GENERIC = "Le genre de truc qui me fait froid dans le dos.",
			GUARD = "Il a l'air sérieux.",
			WEREPIG = "Il n'est pas amical !",
		},
		PIGSKIN = "Il y a encore la queue dessus.",
		PIGTENT = "Ça sent le bacon !",
		PIGTORCH = "Ça a l'air tout chaud.",
		PINECONE = 
		{
		    GENERIC = "Je peux entendre un petit arbre à l'intérieur, qui essaie de sortir.",
		    PLANTED = "Ça sera un arbre bientôt !",
		},
		PITCHFORK = "Il se pourrait que Maxwell cherche ce truc-là.",
		PLANTMEAT = "Ça n'a pas l'air très appétissant.",
		PLANTMEAT_COOKED = "Au moins elle est chaude maintenant.",
		PLANT_NORMAL =
		{
			GENERIC = "Touffu !",
			GROWING = "Bouh ! Ça pousse si lentement !",
			READY = "Hmmm. Prête pour la récolte.",
		},
		POMEGRANATE = "On dirait l'intérieur d'un cerveau d'extra-terrestre.",
		POMEGRANATE_COOKED = "Grande cuisine !",
		POMEGRANATE_SEEDS = "C'est des graines.",
		POND = "Impossible d'en voir le fond !",
		POOP = "Ça devrait me remplir les poches !",
		PUMPKIN = "Elle est grosse comme ma tête !",
		PUMPKINCOOKIE = "C'est moi qui l'ai fait !",
		PUMPKIN_COOKED = "Pourquoi c'est pas devenu une tarte ?",
		PUMPKIN_LANTERN = "Sinistre !",
		PUMPKIN_SEEDS = "C'est des graines.",
		PURPLEAMULET = "Elle me murmure quelque chose.",
		PURPLEGEM = "Elle contient les mystères de l'univers.",
		RABBIT =
		{
			GENERIC = "Il cherche des carottes.",
			HELD = "Vous aimez la science ?",
		},
		RABBITHOLE = "Ça doit mener au monde des hommes-lapins.",
		RAINOMETER = "Ça mesure l'état des nuages.",
		RATATOUILLE = "C'est moi qui l'ai faite !",
		RAZOR = "Une lame aiguisée ficelée sur un bout de bois. Hygiénique !",
		REDGEM = "Ça étincelle d'une chaleur intérieure.",
		RED_CAP = "Drôle d'odeur.",
		RED_CAP_COOKED = "C'est plus pareil maintenant...",
		RED_MUSHROOM =
		{
			GENERIC = "C'est un champignon.",
			INGROUND = "Il dort.",
			PICKED = "Je me demande s'il va repousser.",
		},
		REEDS =
		{
			BURNING = "Ça brûle vraiment !",
			GENERIC = "C'est une touffe de roseaux.",
			PICKED = "J'ai cueilli tous les roseaux utiles.",
		},
        RELIC = 
        {
            GENERIC = "Du vieux matériel ménager.",
            BROKEN = "Y a rien à faire ici.",
        },
        RUINS_RUBBLE = "Ça peut se réparer.",
        RUBBLE = "Juste des morceaux de caillou.",
		RESEARCHLAB = "Ça brise les objets pour découvrir leurs composants élémentaires.",
		RESEARCHLAB2 = "Encore plus scientifique que le dernier !",
		RESEARCHLAB3 = "Qu'ai-je créé ?",
		RESURRECTIONSTATUE = "Quel joli petit diable !",
		RESURRECTIONSTONE = "Quelle étrange pierre.",
		ROBIN =
		{
			GENERIC = "Est-ce le signe que l'hiver se termine ?",
			HELD = "Il aime bien ma poche.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Il vit dans les contrées glacés.",
			HELD = "C'est si doux.",
		},
		ROBOT_PUPPET = "Il est piégé !",
		ROCK_LIGHT =
		{
			GENERIC = "Une fosse de lave recouverte d'une croûte.",
			OUT = "Elle a l'air faible.",
			LOW = "La croûte se reforme sur la lave.",
			NORMAL = "Chaud et confortable.",
		},
		ROCK = "Ça rentre pas dans ma poche.",
		ROCKS = "Je peux faire des trucs avec ça.",
        ROOK = "À bas la tour !",
		ROPE = "De petits bouts de corde.",
		ROTTENEGG = "Beurk ! Ça pue !",
		SANITYROCK =
		{
			ACTIVE = "Cette pierre a l'air complètement dingue !",
			INACTIVE = "Où est le reste ?",
		},
		SAPLING =
		{
			BURNING = "Ça brûle vite !",
			GENERIC = "Les petits arbres sont si mignons.",
			PICKED = "Ça lui apprendra.",
		},
		SEEDS = "Chacune cache un petit mystère.",
		SEEDS_COOKED = "J'en ai tiré tout ce que je pouvais tirer !",
		SEWING_KIT = "Un vrai atelier de coup dur !",
		SHOVEL = "Il se passe plein de choses là-dessous.",
		SILK = "Ça sort des fesses d'une araignée.",
		SKELETON = "Plutôt lui que moi.",
		SKULLCHEST = "Je suis pas sûr qu'il faille ouvrir ça.",
		SMALLBIRD =
		{
			GENERIC = "Plutôt petit comme oiseau.",
			HUNGRY = "Il a l'air affamé.",
			STARVING = "Il doit mourir de faim.",
		},
		SMALLMEAT = "Un petit morceau d'animal mort.",
		SMALLMEAT_DRIED = "Un peu de viande séchée",
		SPEAR = "Un bâton bien pointu.",
		SPIDER =
		{
			DEAD = "Beurk !",
			GENERIC = "Je déteste les araignées.",
			SLEEPING = "J'ai intérêt à être parti quand elle se réveillera.",
		},
		SPIDERDEN = "Ça colle !",
		SPIDEREGGSACK = "J'espère qu'ils ne vont pas éclore dans ma poche.",
		SPIDERGLAND = "Leur odeur est piquante et antiseptique.",
		SPIDERHAT = "Pourvu qu'il n'y ait plus de jus d'araignée dans ce truc-là.",
		SPIDERQUEEN = "AAAAAH ! Cette araignée est énorme !",
		SPIDER_WARRIOR =
		{
			DEAD = "Bon débarras !",
			GENERIC = "Il a l'air encore plus méchant que d'habitude.",
			SLEEPING = "Je devrais garder mes distances.",
		},
		SPOILED_FOOD = "Une boule poilue de bouffe pourrie.",
		STATUEHARP = "Où est passée sa tête ?",
		STATUEMAXWELL = "Elle traduit vraiment sa personnalité.",
		STINGER = "Ça a l'air pointu !",
		STRAWHAT = "Un bien joli chapeau.",
		STUFFEDEGGPLANT = "C'est moi qui l'ai faite !",
		SUNKBOAT = "Il sert à rien planté là !",
		SWEATERVEST = "Ce gilet est élégant comme tout.",
		TAFFY = "C'est moi qui les ai faits !",
		TALLBIRD = "C'est un échassier !",
		TALLBIRDEGG = "Va-t-il éclore ?",
		TALLBIRDEGG_COOKED = "Délicieux et nutritif.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Brrrr !",
			GENERIC = "On dirait qu'il est en train d'éclore.",
			HOT = "Ça sue un œuf ?",
			LONG = "J'ai l'impression que ça va prendre du temps...",
			SHORT = "Il devrait bientôt éclore.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Ça c'est un œuf !",
			PICKED = "Le nid est vide.",
		},
		TEENBIRD =
		{
			GENERIC = "Un oiseau pas très grand.",
			HUNGRY = "Je ferais mieux de lui trouver à manger.",
			STARVING = "Il a un regard inquiétant.",
		},
		TELEBASE =
		{
			VALID = "Elle est prête !",
			GEMS = "Il me faut plus de gemmes pourpres.",
		},
		GEMSOCKET = 
		{
			VALID = "On dirait que c'est prêt.",
			GEMS = "Il me faut une gemme.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Avec ça, je peux sûrement voyager dans le temps et l'espace !",
			GENERIC = "On dirait une liaison vers un autre monde !",
			LOCKED = "Il manque encore quelque chose.",
			PARTIAL = "Mon invention sera bientôt achevée !",
		},
		TELEPORTATO_BOX = "Ça pourrait contrôler la polarité de tout l'univers.",
		TELEPORTATO_CRANK = "Assez résistant pour supporter les expériences les plus intenses.",
		TELEPORTATO_POTATO = "Cette patate en métal recèle un pouvoir énorme et terrifiant...",
		TELEPORTATO_RING = "Un anneau capable de concentrer les énergies dimensionnelles.",
		TELESTAFF = "Il peut me montrer le monde.",
		TENT = "Je deviens fou quand je ne dors pas.",
		TENTACLE = "Ça a l'air dangereux.",
		TENTACLESPIKE = "C'est pointu et visqueux.",
		TENTACLESPOTS = "Ç'était sûrement ses organes génitaux.",
		TENTACLE_PILLAR = "Une colonne visqueuse.",
		TENTACLE_PILLAR_ARM = "Des petits bras glissants.",
		TENTACLE_GARDEN = "Encore un de ces trucs gluants.",
		TOPHAT = "Quel joli chapeau.",
		TORCH = "Un truc pour faire reculer la nuit.",
		TRAP = "Je l'ai tressé bien serré.",
		TRAP_TEETH = "Mauvaise surprise.",
		TRAP_TEETH_MAXWELL = "Autant éviter de marcher là-dessus !",
		TREASURECHEST = "C'est mon coffre à surprises !",
		TREASURECHEST_TRAP = "Trop pratique !",
		TREECLUMP = "On dirait presque qu'on cherche à m'empêcher d'aller quelque part.",
		TRINKET_1 = "C'est tout mélangé.",
		TRINKET_10 = "J'espère que je serai parti d'ici avant d'avoir besoin de ça.",
		TRINKET_11 = "Il me murmure de jolis mensonges.",
		TRINKET_12 = "Je ne sais trop quoi faire d'un tentacule séché.",
		TRINKET_2 = "Une simple copie à pas cher.",
		TRINKET_3 = "Le nœud est noué. Pour toujours.",
		TRINKET_4 = "Sans doute un genre d'artéfact religieux.",
		TRINKET_5 = "Malheureusement, trop petite pour que je m'échappe avec.",
		TRINKET_6 = "L'électricité c'est terminé pour eux.",
		TRINKET_7 = "Je n'ai pas le temps de m'amuser !",
		TRINKET_8 = "Super. C'est la fin de mes problèmes de fuite.",
		TRINKET_9 = "Perso, je préfère les fermetures éclairs.",
		TRUNKVEST_SUMMER = "Nature et décontracté.",
		TRUNKVEST_WINTER = "Tenue de survie pour l'hiver.",
		TRUNK_COOKED = "Encore plus nasillard qu'avant, en fait.",
		TRUNK_SUMMER = "Une trompe légère pour mieux respirer.",
		TRUNK_WINTER = "Un coffre épais et poilu.",
		TURF_CARPETFLOOR = "Étonnant comme ça gratte.",
		TURF_CHECKERFLOOR = "C'est plutôt chouette.",
		TURF_DIRT = "Un morceau de sol.",
		TURF_FOREST = "Un morceau de sol.",
		TURF_GRASS = "Un morceau de sol.",
		TURF_MARSH = "Un morceau de sol.",
		TURF_ROAD = "Des pavés taillés à la hâte.",
		TURF_ROCKY = "Un morceau de sol.",
		TURF_SAVANNA = "Un morceau de sol.",
		TURF_WOODFLOOR = "Des lattes de plancher.",
		TURKEYDINNER = "Mmmm.",
		TWIGS = "Une poignée de petites branches.",
		UMBRELLA = "Avec ça j'aurai enfin les cheveux au sec.",
		UNIMPLEMENTED = "On dirait que ce n'est pas fini ! Ça pourrait être dangereux.",
		WAFFLES = "C'est moi qui les ai faites !",
		WALL_HAY = "Hmmm... Je crois que je vais devoir faire avec.",
		WALL_HAY_ITEM = "Sans doute une mauvaise idée.",
		WALL_STONE = "C'est un joli mur.",
		WALL_STONE_ITEM = "C'est une garantie de sécurité.",
		WALL_RUINS = "Une ancienne portion de mur.",
		WALL_RUINS_ITEM = "Un solide morceau d'histoire.",
		WALL_WOOD = "Piquant !",
		WALL_WOOD_ITEM = "Clôture !",
		WALRUS = "Les morses sont des prédateurs-nés.",
		WALRUSHAT = "C'est couvert de poils de morse.",
		WALRUS_CAMP =
		{
			EMPTY = "On dirait qu'on a campé ici.",
			GENERIC = "Ça a l'air chaud et confortable là-dedans.",
		},
		WALRUS_TUSK = "Je suis sûr que je lui trouverai une utilité.",
		WASPHIVE = "Ces abeilles sont dingues.",
		WETGOOP = "C'est moi qui l'ai fait !",
		WINTERHAT = "Ça servira quand l'hiver sera là.",
		WINTEROMETER = "Je suis un sacré scientifique.",
		WORMHOLE =
		{
			GENERIC = "Doux et sinueux.",
			OPEN = "La science m'oblige à y sauter.",
		},
		WORMHOLE_LIMITED = "Beuh... ce truc a l'air encore pire que d'habitude.",
		ACCOMPLISHMENT_SHRINE = "Je veux l'utiliser et je veux que le monde le sache.",        
		LIVINGTREE = "Est-ce qu'il me regarde ?",
		ICESTAFF = "C'est si froid au toucher.",
	},
	DESCRIBE_GENERIC = "C'est un... truc.",
	DESCRIBE_TOODARK = "Il fait trop sombre !",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Hmmm... ça croustille.",
	},
}
