return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "좋아할 것 같지 않은데.",
			GENERIC = "털이 아닌 걸 깎을 수는 없지.",
			NOBITS = "이미 깎았잖아, 엉?",
		},
		STORE =
		{
			GENERIC = "토론토 시내 전차보다 더 붐비잖아.",
			NOTALLOWED = "허용 안 하잖아, 엉?",
		},
	},
	ACTIONFAIL_GENERIC = "미안, 못하겠다.",
	ANNOUNCE_ADVENTUREFAIL = "어쩔 수 없다. 최대한 시도는 했다.",
	ANNOUNCE_BEES = "벌!벌!",
	ANNOUNCE_BOOMERANG = "미안해!내 잘못이다!",
	ANNOUNCE_CHARLIE = "누군가, 엉?",
	ANNOUNCE_CHARLIE_ATTACK = "윽!거칠잖아!",
	ANNOUNCE_COLD = "여기 춥잖아!",
	ANNOUNCE_CRAFTING_FAIL = "지금은 할 수 없다.",
	ANNOUNCE_DEERCLOPS = "저게 뭐냐?",
	ANNOUNCE_DUSK = "거의 잘 시간이잖아.",
	ANNOUNCE_EAT =
	{
		GENERIC = "맛있잖아!",
		PAINFUL = "유효 기간이 지났잖아.",
		SPOILED = "좀 형편없잖아.",
		STALE = "완전히 썩기 전에 먹었다.",
	},
	ANNOUNCE_ENTER_DARK = "누가 불껐잖아?",
	ANNOUNCE_ENTER_LIGHT = "광명이다!",
	ANNOUNCE_FREEDOM = "나왔잖아!",
	ANNOUNCE_HOUNDS = "밖에 뭔가 있다.",
	ANNOUNCE_HUNGRY = "배고파지고 있잖아.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "짐승이 근처에 있다.",
	ANNOUNCE_HUNT_LOST_TRAIL = "짐승이 탈출했다.",
	ANNOUNCE_INV_FULL = "키트를 더 휴대할 수 없다.",
	ANNOUNCE_KNOCKEDOUT = "아. 저게 뭐냐?",
	ANNOUNCE_MOSQUITOS = "모기잖아!",
	ANNOUNCE_NODANGERSLEEP = "밖에서 자기엔 너무 무섭잖아.",
	ANNOUNCE_NODAYSLEEP = "못난 짜식만 낮에 자잖아.",
	ANNOUNCE_NOHUNGERSLEEP = "자기에는 배가 너무 비었잖아.",
	ANNOUNCE_NO_TRAP = "아슬아슬했잖아!",
	ANNOUNCE_PECKED = "미안해!더 열심히 하겠어!",
	ANNOUNCE_QUAKE = "땅이 움직인다!",
	ANNOUNCE_THORNS = "앗!",
	ANNOUNCE_TORCH_OUT = "불이 꺼졌잖아!",
	ANNOUNCE_TRAP_WENT_OFF = "아차!",
	ANNOUNCE_WORMHOLE = "안이 더러웠잖아!",
	ANNOUNCE_CANFIX = "\n고칠 수 있을 것 같다!",
	ANNOUNCE_ACCOMPLISHMENT= "루시가 날 자랑스워하겠네!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "됐잖아, 엉?",
	BATTLECRY =
	{
		GENERIC = "여기 와라, 엉?",
	},
	COMBAT_QUIT =
	{
		GENERIC = "그만하면 됐잖아.",
	},
	DESCRIBE =
	{
		WORMLIGHT = "이거 유용하겠다.",
		WORM =
		{
		    PLANT = "식물인지 보면 안다. 이건 가짜잖아!",
		    DIRT = "움직이는 땅을 조심해.",
		    WORM = "벌레!",
		},
		EEL = "요리 잘 되겠다.",
		EEL_COOKED = "요리 잘 됐잖아.",
		UNAGI = "날 채워준다.",
		EYETURRET = "짜식들을 내쫓겠지.",
		EYETURRET_ITEM = "올바르게 설치하자.",
		MINOTAURHORN = "좋은 뿔이네, 엉.",
		MINOTAURCHEST = "뿔 달린 좋은 궤짝이잖아, 엉.",
		THULECITE_PIECES = "나무는 아니지만 쓰자.",
		POND_ALGAE = "식용으로 보이지 않잖아.",
		GREENSTAFF = "분해하는 것을 보조하지!",
		POTTEDFERN = "식물의 삶을 사랑하는 나의 마음을 표현한다.",

		THULECITE = "동굴의 나무잖아!",
		ARMORRUINS = "안 아프게 하겠지.",
		RUINS_BAT = "막대기에 달린 금속이잖아.",
		RUINSHAT = "토크는 아니지만 쓰자.",
		NIGHTMARE_TIMEPIECE = 
		{
		CALM = "꺼졌잖아.",	
		WARN = "켜졌잖아!",	
		WAXING = "떨리잖아!", 
		STEADY = "미쳤잖아!", 
		WANING = "꺼지는 중이잖아.", 
		DAWN = "거의 멈췄잖아.", 
		NOMAGIC = "꺼졌잖아.", 
		},
		BISHOP_NIGHTMARE = "내부 작동이 보이잖아!",
		ROOK_NIGHTMARE = "기어가 튀어나고 있잖아.",
		KNIGHT_NIGHTMARE = "최고 상태가 아닌 것 같다.",
		MINOTAUR = "저주당한 불쌍한 놈이 또 있잖아.",	
		SPIDER_DROPPER = "부패한 곳을 피해 사는 것이 현명하네.",	
		NIGHTMARELIGHT = "나무를 썼어야지.",	
		RELIC = "가구 조각이잖아.",	
		RUINS_RUBBLE = "다 망가졌잖아.",	
		MULTITOOL_AXE_PICKAXE = "아... 아름답잖아.",	
		GREENGEM = "번뜩이잖아.",
		ORANGESTAFF = "빨리 돌아다니는 데 도움되겠어.",	
		YELLOWAMULET = "이걸로 밤에 도끼질해야지.",	
		GREENAMULET = "어차피 나는 자르는 것이 특기잖아.",	

		SLURPER = "살아있는 털 같잖아.",
		SLURPER_PELT = "죽은 비버 같잖아.",
		ARMORSLURPER = "간지러워, 아직 살아있잖아.",
		ORANGEAMULET = "허드렛일이 금방 되겠네!",
		YELLOWSTAFF = "어쩔 수 없다면 쓸모 있잖아!",
		YELLOWGEM = "안에 별이 보이잖아.",
		ORANGEGEM = "반짝이잖아.",
		TELEBASE = 
		{
			VALID = "그건 준비됐는데, 나도 준비됐나?",
			GEMS = "보석이 필요하잖아, 엉?",
		},
		GEMSOCKET = 
		{
			VALID = "준비된 것으로 보인다.",
			GEMS = "보석이 필요하잖아.",
		},
		STAFFLIGHT = "신기하네.",
		RESEARCHLAB4 = "'모자 기계'라고 부르겠다!",

	
		LUCY = "루시가 좋아!",

        ANCIENT_ALTAR =
        {
        	WORKING = "제단 돌에 도끼 자국이 있잖아.",
        	BROKEN = "좀 헐어 보이잖아.",
        },     
        
        ANCIENT_ALTAR_BROKEN = "좀 헐어 보이잖아.",
        ANCIENT_STATUE = "짜식.",

        LICHEN = "겨우 먹을 수 있겠네.",
		CUTLICHEN = "냠!나무 맛이잖아!",

		CAVE_BANANA = "열대의 맛이다.",
		CAVE_BANANA_COOKED = "내가 요리했다.",
		CAVE_BANANA_TREE = "고향에는 저런 게 없지.",
		ROCKY = "바닷가재 저녁 시간!",
		
		COMPASS =
		{
			GENERIC="읽을 수 없잖아.",
			N = "진북.",
			S = "남",
			E = "동",
			W = "서",
			NE = "북동",
			SE = "남동",
			NW = "북서",
			SW = "남서",
		},


		BLUEAMULET = "이제 시원한 음료수만 있으면 되지, 엉?",
		PURPLEAMULET = "보석의 광채가 사라졌잖아.",
		TELESTAFF = "이게 뭘 하는 것일까.",
		MONKEY = "뭐냐. 새로운 거잖아.",
		MONKEYBARREL = "훌륭한 건설 재료잖아.",

		HOUNDSTOOTH="아름답나, 엉?",
		ARMORSNURTLESHELL="과도하게 안전할 수는 없잖아.",
		BAT="누가 쥐한테 나는 법 가르쳤냐?",
		BATBAT = "날개 달린 쥐?",
		BATWING="징그럽잖아!",
		BATWING_COOKED="징그럽잖아!맛있잖아!헷갈리잖아!",
		
		BEDROLL_FURRY="내가 캠핑을 좋아하잖아.",
		BUNNYMAN="우호적으로 보이네.",
		FLOWER_CAVE="반짝이잖아!",
		FLOWER_CAVE_DOUBLE="반짝인다!",
		FLOWER_CAVE_TRIPLE="반짝인다!",
		GUANO="다른 것보다 악취가 덜 나.",
		LANTERN="첨단 기술이잖아!",
		LIGHTBULB="질겨 보이잖아.",
		MANRABBIT_TAIL="불쌍한 놈이잖아.",
		MUSHTREE_TALL  ="저걸 그냥 둘 순 없잖아.",
		MUSHTREE_MEDIUM="잘라야겠잖아.",
		MUSHTREE_SMALL ="나무로 만들어졌다.",
		RABBITHOUSE="당근 맛인가?",
		SLURTLE="오해 받는구나.",
		SLURTLE_SHELLPIECES="내가 집을 망가뜨렸잖아. 미안하다.",
		SLURTLEHAT="내 머리를 안전하게 지켜줄 거야.",
		SLURTLEHOLE="여기서 잘 지내냐?",
		SLURTLESLIME="화장지가 필요하잖아.",
		SNURTLE="나선!",
		SPIDER_HIDER="간사한 악마!",
		SPIDER_SPITTER="침 뱉는 것은 무례하잖아!",
		SPIDERHOLE="다시 나오기 전 내빼야겠다.",
		STALAGMITE="바위에는 별로 관심 없잖아.",
		STALAGMITE_FULL="바위에는 별로 관심 없잖아.",
		STALAGMITE_LOW="바위에는 별로 관심 없잖아.",
		STALAGMITE_MED="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL_FULL="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL_LOW="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL_MED="바위에는 별로 관심 없잖아.",


		TURF_CARPETFLOOR = "나한텐 너무 고급이잖아.",
		TURF_CHECKERFLOOR = "도시 사람 화장실 바닥 같잖아.",
		TURF_DIRT = "지면이잖아, 엉?",
		TURF_FOREST = "지면이잖아, 엉?",
		TURF_GRASS = "지면이잖아, 엉?",
		TURF_MARSH = "지면이잖아, 엉?",
		TURF_ROAD = "지면이잖아, 엉?",
		TURF_ROCKY = "지면이잖아, 엉?",
		TURF_SAVANNA = "지면이잖아, 엉?",
		TURF_WOODFLOOR = "왕에게 어울리는 바닥재잖아!",

		TURF_CAVE="지면이잖아.",
		TURF_FUNGUS="완두콩처럼 걸쭉하잖아.",
		TURF_SINKHOLE="지하에서 찾았다.",
		TURF_UNDERROCK="바위잖아. 별로.",	
		TURF_MUD="적어도 치울 필요는 없잖아.",

		
		POWCAKE = "진짜 설탕하고 버터로 만든 게 좋지.",
        CAVE_ENTRANCE = 
        {
            GENERIC="막혔잖아.",
            OPEN = "서드버리 같잖아.",
        },
        CAVE_EXIT = "올라가면 나무가 있겠지.",
		
		MAXWELLPHONOGRAPH = "라디오에 나오는 것보다 낫잖아.",
		BOOMERANG = "던지기 어렵잖아.",
		PIGGUARD = "저놈 화나게 만들지 말자.",
		ADVENTURE_PORTAL = "저기가 출구일까.",
		AMULET = "언제나 예비 계획이 필요하잖아.",
		ANIMAL_TRACK = "거대한 숲 동물이 여길 지나갔다!",
		ARMORGRASS = "없는 것보다 낫잖아.",
		ARMORMARBLE = "이걸 착용하고 도끼 휘두르기 어렵잖아.",
		ARMORWOOD = "나에게 잘 맞는다!",
		ARMOR_SANITY = "욕지기나게 하잖아.",
		ASH =
		{
			GENERIC = "다 탔잖아.",
			REMAINS_EYE_BONE = "눈뼈였잖아.",
			REMAINS_THINGIE = "저것을 통과하지 않잖아.",
		},
		AXE = "루시만큼 좋지 않지.",
		BABYBEEFALO = "어미만 사랑할 수 있는 얼굴이잖아.",
		BACKPACK = "내 륙색이잖아.",
		BACONEGGS = "오호. 앞쪽 베이컨이잖아.",
		BANDAGE = "그래도 돈은 안 냈잖아.",
		BASALT = "저 바위는 안 움직일 거잖아.",
		BEARDHAIR = "내것이 아니잖아.",
		BEDROLL_STRAW = "목재 캠프에서 저것보다 더 후진 것에서 잤었지.",
		BEE =
		{
			GENERIC = "꽃을 자라게 하고 있잖아.",
			HELD = "이제 이것으로 무엇을 하냐?",
		},
		BEEBOX =
		{
			FULLHONEY = "꿀!",
			GENERIC = "벌!",
			NOHONEY = "보기만 해도 배고프잖아.",
			SOMEHONEY = "기다리면 더 가질 수 있잖아.",
		},
		BEEFALO =
		{
			FOLLOWER = "날 좋아하잖아.",
			GENERIC = "헛간 냄새나잖아.",
			NAKED = "힘내라, 엉?",
			SLEEPING = "잠에 취했잖아.",
		},
		BEEFALOHAT = "이제 내가 고기물소 왕이다!",
		BEEFALOWOOL = "내 수염 같은 느낌이다.",
		BEEHAT = "벌이 눈에 들어가는 걸 막아준다.",
		
		BEEHIVE = "편하게 있잖아.",
		
		BEEMINE = "벌의 마음에 들지 모르겠다.",
		BEEMINE_MAXWELL = "어이!못된 것!",
		BERRIES = "이것으로 내 식욕을 채울 순 없다.",
		BERRIES_COOKED = "따뜻한 베리 맛이 나잖아.",
		BERRYBUSH =
		{
			BARREN = "거름이 필요하잖아.",
			GENERIC = "사스카툰 베리?",
			PICKED = "베리가 안 남았잖아!",
		},
		BIRDCAGE =
		{
			GENERIC = "못된 새들을 교화하는 공간이다.",
			OCCUPIED = "반성해라, 새!",
			SLEEPING = "꿈꿀 때는 정말 순해 보이잖아.",
		},
		BIRDTRAP = "새들한테 본때를 보여주겠다!",
		BIRD_EGG = "저 새가 못된 새 생각하잖아.",
		BIRD_EGG_COOKED = "적어도 새가 되지는 않았잖아.",
		BISHOP = "마지막으로 고백 성사했는지 오래 됐잖아.",
		BLOWDART_FIRE = "좀 저돌적이다.",
		BLOWDART_SLEEP = "이것을 쓰면 탈출할 수 있겠다!",
		BLOWDART_PIPE = "나의 거대한 폐활량으로 뭘 할 수 있는지 볼까!",
		BLUEGEM = "아주 차갑잖아.",
		BLUEPRINT = "내가 책 보고 배우는 스타일이 아니잖아.",
		BLUE_CAP = "고기가 아니잖아.",
		BLUE_CAP_COOKED = "고기가 아니잖아.",
		BLUE_MUSHROOM =
		{
			GENERIC = "먹을 수 있는 게 뭔지 도대체 기억할 수 없다.",
			INGROUND = "나중에 돌아오지.",
			PICKED = "끝났잖아.",
		},
		BOARDS = "아주 매끄럽다. 나뭇결이 제대로 보이네.",
		BOAT = "강한 동풍에 맞았잖아.",
		BONESTEW = "먹으면 든든하잖아.",
		BUGNET = "모기 수집용이다.",
		BUSHHAT = "자연에서 숨는 데 좋잖아.",
		BUTTER = "난 마가린이 더 좋아.",
		BUTTERFLY =
		{
			GENERIC = "내가 그걸 믿은 적이 없잖아, 엉?",
			HELD = "어디로 도망가냐?",
		},
		BUTTERFLYMUFFIN = "바삭하잖아!",
		BUTTERFLYWINGS = "미안해!내가 나쁜 놈이다!",
		CAMPFIRE =
		{
			EMBERS = "거의 다 사라졌다.",
			GENERIC = "내 기타 어딨냐?",
			HIGH = "엉!좀 높다!",
			LOW = "뭔가 해야겠지, 엉?",
			NORMAL = "저녁에 켠 불이 좋지.",
			OUT = "있는 동안은 좋았잖아.",
		},
		CANE = "벽촌에서 유용하지.",
		CARROT = "토끼 음식이잖아.",
		CARROT_COOKED = "토끼 음식이잖아.",
		CARROT_PLANTED = "난 야채 싫다고, 엉?",
		CARROT_SEEDS = "작은 당근.",
		CAVE_FERN = "어이!양치류다!",

		CHARCOAL = "좀 슬퍼지네.",

        CHESSJUNK1 = "죽은 금속",
        CHESSJUNK2 = "죽은 금속",
        CHESSJUNK3 = "죽은 금속",

		CHESTER = "최선을 다하고 있잖아!",
		CHESTER_EYEBONE =
		{
			GENERIC = "노려보는 게 무례하다고 가르쳐 준 사람이 없는 모양이다.",
			WAITING = "다시 일어날까.",
		},
		COOKEDMANDRAKE = "나쁜 짓이었나?",
		COOKEDMEAT = "어머니가 만들어준 그 맛이잖아.",
		COOKEDMONSTERMEAT = "그래도 먹기 싫잖아.",
		COOKEDSMALLMEAT = "더 배고프게 만들잖아!",
		COOKPOT =
		{
			COOKING_LONG = "좀 더 길겠네, 엉?",
			COOKING_SHORT = "저런!오잖아!",
			DONE = "저녁 식사 시간!",
			EMPTY = "저기에 빈 채로 두는 것은 낭비잖아.",
		},
		CORN = "좋지만, 먹는 것에 다 넣을 필요는 없다.",
		CORN_COOKED = "옥수수를 잘 요리했다.",
		CORN_SEEDS = "나는 흙 가는 사람이 아니라 나무 자르는 사람이잖아.",
		CROW =
		{
			GENERIC = "뭔가 계획하고 있어. 분명해.",
			HELD = "너 벌 받을 거다, 까마귀!",
		},
		CUTGRASS = "이것에 알러지 반응이 있는 것 같다.",
		CUTREEDS = "물새 부르는 소리 들려줄까?",
		CUTSTONE = "캐나다 순상지의 일부잖아.",
		DEADLYFEAST = "냄새가 영 아니지, 엉.",
		DEERCLOPS = "큰 말코손바닥사슴이잖아!",
		DEERCLOPS_EYEBALL = "어디에 쓰는 물건이냐?",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불인 것 같다.",
		},
		DEVTOOL = "할 말 없다.",
		DIRTPILE = "엇!실마리잖아!",
		DIVININGROD =
		{
			COLD = "여기선 흐릿하잖아.",
			GENERIC = "하키 경기를 이해할까.",
			HOT = "크고 뚜렷하잖아!근처에 뭐가 있다!",
			WARM = "가까워지는 것 같다.",
			WARMER = "조심하자.",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "뭔가 삽입할 수 있잖아.",
			READY = "잠금 해제할 준비가 됐다.",
			UNLOCKED = "이제 켜기만 하면 된다.",
		},
		DIVININGRODSTART = "이상하게 생긴 막대잖아.",
		DRAGONFRUIT = "이런 것은 본 적 없어.",
		DRAGONFRUIT_COOKED = "단풍당밀 맛이잖아.",
		DRAGONFRUIT_SEEDS = "더 키울 수 있잖아.",
		DRAGONPIE = "거의 버터 타트만큼 좋다!",
		DRUMSTICK = "10월 음식이잖아.",
		DRUMSTICK_COOKED = "고맙다, 칠면조.",
		DUG_BERRYBUSH = "조경에 손대볼까.",
		DUG_GRASS = "눈물 나잖아.",
		DUG_MARSH_BUSH = "심어야지.",
		DUG_SAPLING = "음. 약하잖아.",
		DURIAN = "나쁜 냄새잖아.",
		DURIAN_COOKED = "냄새가 더 나쁘잖아.",
		DURIAN_SEEDS = "왜 이걸 더 재배하냐.",
		EARMUFFSHAT = "고향에서는 가을에만 이걸 쓰잖아.",
		EGGPLANT = "새들의 짓이겠지.",
		EGGPLANT_COOKED = "수상하게 새랑 연관이 있잖아.",
		EGGPLANT_SEEDS = "흠. 모르겠잖아.",
		EVERGREEN =
		{
			BURNING = "안되잖아!내가 자를 수 있었는데!",
			BURNT = "낭비잖아.",
			CHOPPED = "아!",
			GENERIC = "나를 부르잖아!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "미안해!",
			BURNT = "안타깝다!",
			CHOPPED = "하나 더!",
			GENERIC = "루시가 자르라고 하네.",
		},
		EYEPLANT = "자기 일이나 신경 쓰라 그래.",
		FARMPLOT =
		{
			GENERIC = "난 더 큰 식물이 좋다.",
			GROWING = "자를 정도로 절대 커지지 않을 거야.",
			NEEDSFERTILIZER = "거름이 필요하잖아.",
		},
		FEATHERHAT = "저것은... 쓰고 싶지 않잖아.",
		FEATHER_CROW = "더러운 깃털이잖아.",
		FEATHER_ROBIN = "넌더리 나는 깃털이다.",
		FEATHER_ROBIN_WINTER = "바보 같은 깃털.",
		FEM_PUPPET = "잡혔잖아!",
		FIREFLIES =
		{
			GENERIC = "앨곤퀸 공원이 생각난다.",
			HELD = "햇빛이 한 주머니 가득!",
		},
		FIREHOUND = "뜨거운 개!",
		FIREPIT =
		{
			EMBERS = "저걸 위해 나무를 베어야겠지, 엉?",
			GENERIC = "나무를 쓰잖아.",
			HIGH = "나무를 너무 빨리 너무 많이 쓰고 있잖아!",
			LOW = "여기 어딘가에 나무가 있겠지.",
			NORMAL = "흠. 나무 냄새 난다.",
			OUT = "나무가 있으면 좋겠다.",
		},
		FIRESTAFF = "마법 짓거리는 몸 믿겠으니까.",
		FISH = "대구 같잖아.",
		FISHINGROD = "호수에서 시간을 보내야겠다.",
		FISHSTICKS = "상자 안의 고급 식사다.",
		FISHTACOS = "바다 맛이잖아, 엉?",
		FISH_COOKED = "감자칩이 있으면 좋겠다.",
		FLINT = "도끼날로 써도 되겠다.",
		FLOWER = "좋잖아.",
		FLOWERHAT = "내 빨간 머리와 어울리잖아.",
		FLOWER_EVIL = "꽃이 뭔가 문제 있잖아.",
		FOLIAGE = "샐러드 같잖아.",
		FOOTBALLHAT = "이거 쓰면 머리카락이 엉망이 될려나?",
		FROG =
		{
			DEAD = "개구리였잖아.",
			GENERIC = "공기와 물 중에서 택일 못하는 건 못 믿겠다.",
			SLEEPING = "피곤하잖아.",
		},
		FROGGLEBUNWICH = "늪의 맛을 제대로 느낄 수 있잖아.",
		FROGLEGS = "아직도 뛰잖아!",
		FROGLEGS_COOKED = "적어도 움직이는 것은 멈췄어.",
		FRUITMEDLEY = "시럽 추가!",
		GEARS = "난 이런 거 이해 못하잖아.",
		GHOST = "으악!하하!",
		GOLDENAXE = "거의 루시만큼 좋다.",
		GOLDENPICKAXE = "예쁘지만 나무를 찍어 내릴 수는 없잖아.",
		GOLDENPITCHFORK = "왜 이걸 만들었는지 모르겠잖아.",
		GOLDENSHOVEL = "황금 구멍을 팔 시간이다.",
		GOLDNUGGET = "금으로 커피 테이블을 만들 수 없잖아.\n어쩌면 될지도 모르겠다. 그래도 하지 말아야지.",
		GRASS =
		{
			BARREN = "여기에 똥 싸야 되잖아.",
			BURNING = "나무에 번지지 않았으면 한다.",
			GENERIC = "불쏘시개 같아.",
			PICKED = "맨 땅이 됐네.",
		},
		GREEN_CAP = "숲에서 이것보다 더 이상한 것 먹었잖아.",
		GREEN_CAP_COOKED = "안 믿어.",
		GREEN_MUSHROOM =
		{
			GENERIC = "녹색 버섯이잖아.",
			INGROUND = "자기 스케줄이 있는 놈이다.",
			PICKED = "내가 망가뜨린 것 같다.",
		},
		GUNPOWDER = "이걸 좋아한 적이 없지.",
		HAMBAT = "좋은 햄 낭비잖아.",
		HAMMER = "누구나 실수하잖아, 엉?",
		HEALINGSALVE = "건강에 좋은 죽이다.",
		HEATROCK =
		{
			COLD = "차가워졌잖아, 엉?",
			GENERIC = "고향에서는 이걸 '밤의 바위'라고 한다.",
			HOT = "주머니 안에 저게 있으면 겨울 내내 나무를 벨 수 있잖아!",
			WARM = "좀... 뜨뜻해진다.",
		},
		HOME = "누구냐?",
		HOMESIGN = "나무가 할 수 없는 것도 있냐?",
		HONEY = "으흐음. 벌 시럽이잖아.",
		HONEYCOMB = "이걸 가져가서 거의 죄책감 느껴지잖아.",
		HONEYHAM = "하지만 휴일이 아냐...",
		HONEYNUGGETS = "내가 좋아하는 식사잖아!",
		HORN = "내가 왜 이것에 입을 대야 하냐.",
		HOUND = "썰매 당길 때 좋겠지.",
		HOUNDBONE = "개 침으로 덮였잖아, 엉?",
		HOUNDMOUND = "저거랑 상대 안 하는 게 낫지.",
		ICEBOX = "아!고향 생각나네.",
		ICEHOUND = "북극 개냐?",
		INSANITYROCK =
		{
			ACTIVE = "어디 갔지?!",
			INACTIVE = "어떻게 움직일 수 있는 모르잖아.",
		},
		JAMMYPRESERVES = "이제 땅콩버터만 찾으면 된다.",
		KABOBS = "막대가 맛에 정말 영향을 주잖아.",
		KILLERBEE =
		{
			GENERIC = "저 벌은 우호적으로 보이지 않잖아.",
			HELD = "상황이 그리 기쁘지 않은 모양이잖아.",
		},
		KNIGHT = "맥스웰의 말 탄 경찰이잖아.",
		KOALEFANT_SUMMER = "맛있어 보인다.",
		KOALEFANT_WINTER = "겨울에 더 맛있어지잖아.",
		KRAMPUS = "물러서라, 짜식아!",
		KRAMPUS_SACK = "남의 자루를 가져가면 미안한데.",
		LEIF = "나무 때문에 미안하다!",
		LEIF_SPARSE = "나무 때문에 미안하다!",
		LIGHTNING_ROD =
		{
			CHARGED = "오로라처럼 예쁘잖아.",
			GENERIC = "이제 벼락 맞을 일 없다.",
		},
		LITTLE_WALRUS = "왜 이렇게 남쪽으로 왔나?",
		LIVINGLOG = "널 가질 거야. 그리고 프랭크라고 부르겠어.",
		LOCKEDWES = "저 자식 누구야?",
		LOG =
		{
			BURNING = "아니!노력의 결실이잖아!",
			GENERIC = "보람있잖아.",
		},
		LUREPLANT = "고기잖아?",
		LUREPLANTBULB = "따뜻하고 튀어나왔다.",
		MALE_PUPPET = "도와줄까?",
		MANDRAKE =
		{
			DEAD = "미안해, 작은 놈.",
			GENERIC = "나를 보고 있잖아.",
			PICKED = "내가 뭘 한 거지?",
		},
		MANDRAKESOUP = "피곤한 수프잖아.",
		MANDRAKE_COOKED = "미안해!",
		MARBLE = "정부 건물 같잖아.",
		MARBLEPILLAR = "누군가가 만들었겠지.",
		MARBLETREE = "루시도 그건 못 자른다.",
		MARSH_BUSH =
		{
			BURNING = "흠!",
			GENERIC = "나무딸기잖아.",
			PICKED = "그럴 가치가 있었나?",
		},
		MARSH_PLANT = "잡풀이잖아.",
		MARSH_TREE =
		{
			BURNING = "뾰족하면 그렇게 된다!",
			BURNT = "인과응보잖아.",
			CHOPPED = "어려운 싸움에서 내가 이겼다.",
			GENERIC = "나무가 왜 반격하냐!",
		},
		MAXWELL = "왜 나를 싫어하냐?",
		MAXWELLHEAD = "그냥 머리잖아, 엉?",
		MAXWELLLIGHT = "부자연스럽잖아.",
		MAXWELLLOCK = "열쇠 어딨어?",
		MAXWELLTHRONE = "이거보다 나은 의자 봤잖아.",
		MEAT = "말코손바닥사슴 맛이 난다.",
		MEATBALLS = "다 고기다!",
		MEATRACK =
		{
			DONE = "된 것으로 보인다.",
			DRYING = "고기 마르는 걸 보는 것 같잖아.",
			GENERIC = "설치했다... 고기만 추가하면 돼.",
		},
		MEAT_DRIED = "생존의 맛이다.",
		MERM = "어떤 끔찍한 바다에서 튀어나왔지?",
		MERMHEAD = "대형 트롤선 냄새가 난다.",
		MERMHOUSE = "편리한 것은 아니다.",
		MINERHAT = "석탄 광산 깊숙이.",
		MONSTERLASAGNA = "고양이 음식이잖아!",
		MONSTERMEAT = "그걸 먹을 정도로 배고프지 않잖아.",
		MONSTERMEAT_DRIED = "그래도 먹고 싶지 않잖아.",
		MOSQUITO =
		{
			GENERIC = "내 피 한 바가지!",
			HELD = "이걸로 뭘 하나, 엉?",
		},
		MOSQUITOSACK = "피와 내장, 엉?",
		MOUND =
		{
			DUG = "미안!날 쫓지 마!",
			GENERIC = "저걸 내버려 두는 게 낫겠지.",
		},
		NIGHTLIGHT = "저건 무슨 어둠이냐?",
		NIGHTMAREFUEL = "나의 모든 두려움을 액체로 만들었냐, 엉?",
		
		NIGHTSWORD = "악몽은 해치지 않잖아!",
		NITRE = "이것으로 철도 선로를 만들지.",
		ONEMANBAND = "너를 보호해 주겠다!",
		PANDORASCHEST = "상자 안에 뭐가 있는 거냐?!",
		PANFLUTE = "나는 루시만을 위해 노래 부르잖아.",
		PAPYRUS = "글쓰기보다는 자르겠어.",
		PENGUIN = "가라!위대하고 하얀 북방으로!아름다운 놈아.",
		PERD = "새가 더 있잖아!왜 새가 많냐?",
		PEROGIES = "'맛 주머니'라고 부르지.",
		PETALS = "루시가 이걸 좋아할까.",
		PETALS_EVIL = "작고 못된 얼굴로 나한테 찡그리잖아.",
		PICKAXE = "도끼 같지만, 아니다.",
		PIGGYBACK = "돼지의 모든 부위를 썼잖아.",
		PIGHEAD = "좋은 돈육 낭비잖아.",
		PIGHOUSE =
		{
			FULL = "베이컨이 들어찼다.",
			GENERIC = "청테이프 있으면 고칠 수 있을 텐데.",
			LIGHTSOUT = "미안!안을 보지 않겠어!",
		},
		PIGKING = "나의 왕이 아니잖아.",
		PIGMAN =
		{
			FOLLOWER = "우린 팀이잖아!야아!",
			GENERIC = "걷는 백 베이컨이잖아!",
			GUARD = "저놈은 사나워 보이잖아.",
			WEREPIG = "어떻게 된 거야?!",
		},
		PIGSKIN = "꼬리 달린 베이컨이잖아.",
		PIGTORCH = "엄지 없이 어떻게 저걸 할 수 있지?",
		PINECONE = 
		{
		    GENERIC = "키운 다음에 잘라야겠다!",
		    PLANTED = "나무가 나올 거다!",
		},
		
		PITCHFORK = "이건 진짜 내 스타일이 아니다.",
		PLANTMEAT = "추잡하잖아!",
		PLANTMEAT_COOKED = "요리했는 데 도움이 안 된다.",
		PLANT_NORMAL =
		{
			GENERIC = "뭐가 될까.",
			GROWING = "바라보고 있으면 식물이 안 자란다.",
			READY = "캘 때가 됐잖아.",
		},
		POMEGRANATE = "나한테는 너무 고급이잖아.",
		POMEGRANATE_COOKED = "플랩잭에 잘 어울리겠네.",
		POMEGRANATE_SEEDS = "씨 많잖아.",
		POND = "난 수영 못하잖아!",
		POOP = "캠프에서 똥 싸지 마!",
		PUMPKIN = "땅에서 자라는 건 먹기 싫은데.",
		PUMPKINCOOKIE = "계속 자를 수 있게 해준다.",
		PUMPKIN_COOKED = "파이가 좋잖아.",
		PUMPKIN_LANTERN = "쓰러뜨리지 말자.",
		PUMPKIN_SEEDS = "씨잖아.",
		PURPLEGEM = "자르면 다 해결되잖아.",
		RABBIT =
		{
			GENERIC = "제기랄 땅 다람쥐...",
			HELD = "먹으면 미안하겠지.",
		},
		RABBITHOLE = "아래에 나무가 없겠지.",
		RAINOMETER = "비오면 나무가 자라지.",
		RATATOUILLE = "내가 요리했다!",
		RAZOR = "진짜 벌목꾼은 면도하지 않잖아.",
		REDGEM = "수천 그루의 나무가 불타는 죽음이 보인다.",
		RED_CAP = "모르겠다...",
		RED_CAP_COOKED = "너무 배고파지면.",
		RED_MUSHROOM =
		{
			GENERIC = "빨간 버섯이잖아.",
			INGROUND = "자기 스케줄이 있는 놈이다.",
			PICKED = "내가 망가뜨린 것 같다.",
		},
		REEDS =
		{
			BURNING = "불 보면 불안해.",
			GENERIC = "갈대.",
			PICKED = "돌아오겠지.",
		},
        RUBBLE = "부서진 가구잖아.",
		RESEARCHLAB = "과학 못 믿겠어.",
		RESEARCHLAB2 = "이상해지고 있잖아.",
		RESEARCHLAB3 = "아, 이제 알겠잖아.",
		RESURRECTIONSTATUE = "나무로 만들어진 내 모습이 좋다.",
		RESURRECTIONSTONE = "만져야 할지 모르겠잖아.",
		ROBIN =
		{
			GENERIC = "추잡한 못된 놈.",
			HELD = "편하게 있지 마.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "남쪽으로 날아가던가 해라!",
			HELD = "내 온기를 빼앗고 있다.",
		},
		ROBOT_PUPPET = "잡혔잖아!",
		ROCK_LIGHT =
		{
			GENERIC = "나무가 필요 없는 불인가?부자연스럽잖아!",
			OUT = "부서질 것 같잖아.",
			LOW = "나무가 더... 필요한가?",
			NORMAL = "나무가 필요 없는 불인가?부자연스럽잖아!",
		},
		ROCK = "노력하면 부술 수 있어.",
		ROCKS = "나무로 안될 때.",
        ROOK = "흠... 루크가 직선으로 이동하던가?까먹었다.",
		ROPE = "물건 묶을 때 쓴다.",
		ROTTENEGG = "새 한 마리 줄었다. 좋지.",
		SANITYROCK =
		{
			ACTIVE = "바위가 이상하지, 엉?",
			INACTIVE = "말 되잖아.",
		},
		SAPLING =
		{
			BURNING = "오!기회를 박탈당했잖아!",
			GENERIC = "크는 걸 본 다음에 잘라야겠다.",
			PICKED = "따는 건 자르는 것만큼 재밌지 않잖아.",
		},
		SEEDS = "나무가 아냐.",
		SEEDS_COOKED = "'벌목꾼의 깜짝선물'이라고 부르지.",
		SEWING_KIT = "내가 바느질 잘 하지.",
		SHOVEL = "구멍을 판다. 나무를 심는다!",
		SILK = "거미는 오싹해.",
		SKELETON = "미안해, 친구.",
		SKULLCHEST = "무시무시하잖아!",
		SMALLBIRD =
		{
			GENERIC = "뭘 원하냐?",
			HUNGRY = "뭔가 원하잖아.",
			STARVING = "굶고 있잖아.",
		},
		SMALLMEAT = "더 컸으면 좋겠다.",
		SMALLMEAT_DRIED = "한 입만.",
		SPEAR = "묵직한 게 좋은 도끼 같지 않잖아.",
		SPIDER =
		{
			GENERIC = "본 중에 가장 큰 거미잖아!",
			SLEEPING = "조심해, 엉?",
		},
		SPIDERDEN = "으앗!저걸 봐라!",
		SPIDEREGGSACK = "저걸 왜 들고 다녀?",
		SPIDERGLAND = "독이잖아.",
		SPIDERHAT = "진짜 예쁘지, 엉?",
		SPIDERQUEEN = "너가 내 여왕이 아니잖아!",
		SPIDER_WARRIOR =
		{
			GENERIC = "노란색도 있나, 엉?",
			SLEEPING = "깨우고 싶지 않아.",
		},
		SPOILED_FOOD = "디펜베이커 꼴이잖아.",
		STATUEHARP = "머리를 잃었나, 엉?",
		STATUEMAXWELL = "못된 놈이지, 엉?",
		STINGER = "앗!뾰족하잖아.",
		STRAWHAT = "머리를 위해 해를 막는다.",
		STUFFEDEGGPLANT = "요리 실력이 늘고 있잖아.",
		SUNKBOAT = "저 나무에게도 좋은 시절이 있었지.",
		SWEATERVEST = "플래드는 아니지만 쓰자.",
		TAFFY = "설탕이 잔뜩 들어서 좋네.",
		TALLBIRD = "나도 나는 새는 믿지 못한다.",
		TALLBIRDEGG = "안에 뭐가 들었지?",
		TALLBIRDEGG_COOKED = "정의의 맛이다.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "너에겐 너무 춥나?",
			GENERIC = "부화한다.",
			HOT = "울고 있나?",
			LONG = "새는 시간을 안 지키잖아.",
			SHORT = "금방 나오겠어.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "알을 훔쳐서 혼내 주지.",
			PICKED = "아무 것도 없잖아.",
		},
		TEENBIRD =
		{
			GENERIC = "그 부모처럼 커서 못된 놈이 되려고 하잖아.",
			HUNGRY = "넌 언제나 배고프냐?",
			STARVING = "배고파서 사나워지잖아.",
		},
		TELEBASE =
		{
			VALID = "그건 준비됐는데, 나도 준비됐나?",
			GEMS = "보석이 필요하잖아, 엉?",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "준비됐나, 엉?",
			GENERIC = "마법... 물건이잖아.",
			LOCKED = "부품이 없잖아, 엉?",
			PARTIAL = "거의 됐잖아, 엉?",
		},
		TELEPORTATO_BOX = "상자, 엉?",
		TELEPORTATO_CRANK = "크랭크, 엉?",
		TELEPORTATO_POTATO = "감자, 엉?",
		TELEPORTATO_RING = "링, 엉?",
		TELESTAFF = "이게 뭘 하는 것일까.",
		TENT = "더 허름한 곳에서 많이 잤지.",
		TENTACLE = "아래에 오징어 있나?",
		TENTACLESPIKE = "흔들면 휘어지잖아.",
		TENTACLESPOTS = "얼굴 빨개진다!",
		TENTACLE_PILLAR = "엄청 크잖아!",
		TENTACLE_PILLAR_ARM = "오징어 아기인가?",
		TENTACLE_GARDEN = "오징어, 짜증나네!",
		TOPHAT = "너무 고급이잖아.",
		TORCH = "횃불 나무.",
		TRAP = "똑똑하게 살라고, 엉?",
		TRAP_TEETH = "이건 좀 거칠잖아.",
		TRAP_TEETH_MAXWELL = "정정당당하게 싸우는 게 아니잖아, 엉?",
		TREASURECHEST = "나무는 유용해!수많은 걸 만들 수 있잖아!",
		TREASURECHEST_TRAP = "궤짝이 뭔가 수상해.",

		TRINKET_1 = "그 게임을 한 적이 있었지.",
		TRINKET_10 = "노인을 위한 까뀌.",
		TRINKET_11 = "조용히 해!",
		TRINKET_12 = "다 시들었잖아.",
		TRINKET_2 = "진짜가 아니잖아, 엉?",
		TRINKET_3 = "전에 들었던 이야기가 생각나네.",
		TRINKET_4 = "나한테 묻지 마.",
		TRINKET_5 = "로봇 팔이 필요한 거야, 엉?",
		TRINKET_6 = "더 이상 안 좋잖아, 엉?",
		TRINKET_7 = "이건 몇 시간이고 가지고 놀 수 있잖아!",
		TRINKET_8 = "욕조만 있으면 되잖아.",
		TRINKET_9 = "착용하고 옷을 기워버렸다.",
		TRUNKVEST_SUMMER = "시원해서 좋다.",
		TRUNKVEST_WINTER = "고향 겨울도 견디겠어, 엉?",
		TRUNK_COOKED = "끓여서 콧물이 증발한 것 같다.",
		TRUNK_SUMMER = "꽤 얇잖아.",
		TRUNK_WINTER = "두껍고 털 많잖아.",
		TURF_CARPETFLOOR = "나한텐 너무 고급이잖아.",
		TURF_CHECKERFLOOR = "도시 사람 화장실 바닥 같잖아.",
		TURF_DIRT = "지면이잖아, 엉?",
		TURF_FOREST = "지면이잖아, 엉?",
		TURF_GRASS = "지면이잖아, 엉?",
		TURF_MARSH = "지면이잖아, 엉?",
		TURF_ROAD = "지면이잖아, 엉?",
		TURF_ROCKY = "지면이잖아, 엉?",
		TURF_SAVANNA = "지면이잖아, 엉?",
		TURF_WOODFLOOR = "왕에게 어울리는 바닥재잖아!",
		TURKEYDINNER = "칠면조 먹는 날이 돌아왔다!",
		TWIGS = "이걸 자르려면 작은 도끼를 만들어야겠다.",
		UMBRELLA = "수염을 젖지 않게 해주겠지, 엉?",
		UNIMPLEMENTED = "안전해 보이지 않잖아.",
		WAFFLES = "난 플랩잭이 더 좋아.",
		WALL_HAY = "재채기하면 쓰러지겠어.",
		WALL_HAY_ITEM = "재채기하면 쓰러지겠어.",
		WALL_STONE = "안전한가, 엉?",
		WALL_STONE_ITEM = "안전한가, 엉?",
		WALL_RUINS = "무너지고 있지만 안전해, 엉?",
		WALL_RUINS_ITEM = "또 돌 맞았나, 엉?",
		WALL_WOOD = "좋잖아!",
		WALL_WOOD_ITEM = "좋잖아!",
		WALRUS = "안돼. 또 바다코끼리잖아!",
		WALRUSHAT = "할아버지께서 저런 모자를 썼지.",
		WALRUS_CAMP =
		{
			EMPTY = "겨울이 되면 안전하지 않을 거다.",
			GENERIC = "근처에 바다코끼리가 있잖아, 엉?",
		},
		WALRUS_TUSK = "충치 구멍 있었잖아, 엉?",
		WASPHIVE = "벌이 왜 화났냐?",
		WETGOOP = "먹었던 것 중 최악은 아니잖아!",
		WINTERHAT = "좋은 모자네, 엉?",
		WINTEROMETER = "고향에서 절반 높이로 만들 수 있잖아.",
		WORMHOLE =
		{
			GENERIC = "거지 같잖아!",
			OPEN = "들여다보고 싶지 않은데, 엉?",
		},
		WORMHOLE_LIMITED = "좀 상한 냄새 나잖아, 엉?",
		ACCOMPLISHMENT_SHRINE = "너무 젠체하는 것 같다.",        		
		LIVINGTREE = "모순된 느낌이잖아, 엉?",
		ICESTAFF = "고향 생각나잖아.",
	},
	DESCRIBE_GENERIC = "저게 뭐야, 엉?",
	DESCRIBE_TOODARK = "캄캄하잖아, 엉!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "부리를 맛볼 수 있잖아, 엉?",
	},
}
