return {


	ACTIONFAIL_GENERIC = "아무 것도 제대로 할 수 없네.",
	ANNOUNCE_ADVENTUREFAIL = "모든 죽음이 같은 것은 아니야.",
	ANNOUNCE_BOOMERANG = "이런!카르마였네.",
	ANNOUNCE_CHARLIE = "마귀!나와라!",
	ANNOUNCE_CHARLIE_ATTACK = "공격당했어!",
	ANNOUNCE_COLD = "뼛속까지 춥네.",
	ANNOUNCE_CRAFTING_FAIL = "필요한 재료가 없네.",
	ANNOUNCE_DUSK = "곧 어둠이 깔릴 거야. 준비해야 해.",
	ANNOUNCE_EAT =
	{
		GENERIC = "냠!",
		PAINFUL = "먹을 수 있는 것이 아니었어.",
		SPOILED = "수명이 끝나가는 음식이었어.",
		STALE = "안 싱싱했나?",
	},
	ANNOUNCE_ENTER_DARK = "어둠이 날 삼켰어.",
	ANNOUNCE_ENTER_LIGHT = "그리고 빛이 있으라!",
	ANNOUNCE_HOUNDS = "개가 짖고 있어.",
	ANNOUNCE_HUNGRY = "텅 비어 있어.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "근처에서 짐승의 존재감이 느껴져.",
	ANNOUNCE_HUNT_LOST_TRAIL = "흔적이 이어지는 곳이 없어.",
	ANNOUNCE_INV_FULL = "더 들 수 없어.",
	ANNOUNCE_KNOCKEDOUT = "아, 아퍼!하지만 또 살아나네.",
	ANNOUNCE_NOHUNGERSLEEP = "배가 내 마음처럼 비어서 잘 수가 없네.",
	ANNOUNCE_PECKED = "내 인내심을 시험하는 거야.",
	ANNOUNCE_QUAKE = "땅이 떨리네. 나를 완전히 삼킬까?",
	ANNOUNCE_THORNS = "이런!나처럼 가시투성이야.",
	ANNOUNCE_TORCH_OUT = "어둠이 돌아왔어!",
	ANNOUNCE_TRAP_WENT_OFF = "뭐야.",
	ANNOUNCE_WORMHOLE = "다시 한 번 세계에 등장하네.",
	ANNOUNCE_CANFIX = "\n고칠 수 있을 것 같아!",
	ANNOUNCE_ACCOMPLISHMENT = "다 덧없어.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "이것도 언젠가는 잊혀지겠네.",
	BATTLECRY =
	{
		GENERIC = "죽음이 널 찾아올 거야!",
		PIG = "죽음의 포옹을 맛봐라!",
		PREY = "당해라, 벌레!",
		SPIDER = "너를 저승으로 보내겠어!",
		SPIDER_WARRIOR = "너에게 종말을 전해 주겠어!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "넌 살 거야. 지금은.",
	},
	DESCRIBE =
	{
		WORMLIGHT = "약간의 소리가 들리고 있어.",
		WORM =
		{
		    PLANT = "엉뚱한 곳에 있는 것 같아.",
		    DIRT = "뭐가 있는 걸까?",
		    WORM = "깊은 곳에서 왔네.",
		},
		EEL = "장어네.",
		EEL_COOKED = "요리한 장어야.",
		UNAGI = "더 맛있어 보여.",
		EYETURRET = "왜 도움이 되는지 모르겠어.",
		EYETURRET_ITEM = "배치해야 할 것 같네.",
		MINOTAURHORN = "위대한 짐승의 잔재야.",
		MINOTAURCHEST = "굉장한 뿔을 가지고 있구나!",
		THULECITE_PIECES = "강력한 재료의 조각이야.",
		POND_ALGAE = "조류네.",
		GREENSTAFF = "깊숙이 안에서 힘이 반짝이고 있는 것이 보여.",
		POTTEDFERN = "우리 안에서 살아.",

		THULECITE = "그 존재가 무명의 가장자리에 자국을 낸다.",
		ARMORRUINS = "죽음을 일시적으로 물리쳐.",
		RUINS_BAT = "내 손 안에 고대인의 힘이 들어있어.",
		RUINSHAT = "애비게일이라면 이 관을 좋아할 텐데.",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "그림자에 무엇이 숨어있는지 알아.",	
			WARN = "응시하는 눈이 느껴져.",	
			WAXING = "접근하네.", 
			STEADY = "네 주위를 둘러쌌어!", 
			WANING = "그들이 떠나는 것 같아.", 
			DAWN = "거의 끝났어.", 
			NOMAGIC = "나는 홀로 있네.", 
		},
		BISHOP_NIGHTMARE = "시간이 싸움에서 이겼네.",
		ROOK_NIGHTMARE = "시간이 모든 것을 부식시켜.",
		KNIGHT_NIGHTMARE = "시간이 굴복한 또 한 번의 전투야.",
		MINOTAUR = "외로운가 봐. 아주 작은 우리 안에 갇혔어.",	
		SPIDER_DROPPER = "어둠이 털을 탈색시켰어.",	
		NIGHTMARELIGHT = "지하에서 힘을 가져오네.",	
		RELIC = "과거가 보이네.",	
		RUINS_RUBBLE = "망가진 꿈의 더미야.",	
		MULTITOOL_AXE_PICKAXE = "다용도 아이템이네.",	
		GREENGEM = "오점이 이것의 가장 아름다운 특징이야.",
		ORANGESTAFF = "사용할 때마다 내가 죽고 다시 살아나.",	
		YELLOWAMULET = "내 어둠의 삶에 잠깐의 빛이야.",	
		GREENAMULET = "잠깐의 반짝임!",	

		SLURPER = "단순해서 좋겠네.",
		SLURPER_PELT = "비어있는 배고픔의 가방.",
		ARMORSLURPER = "달라붙는 음울한 살아있는 슈트네.",
		ORANGEAMULET = "고역에 대한 일시적인 방출구.",
		YELLOWSTAFF = "막대가 나의 혼처럼 비꼬였어.",
		YELLOWGEM = "엄마를 기억나게 해.",
		ORANGEGEM = "이런 게 행복하게 해줬는데.",
		TELEBASE = 
		{
			VALID = "에너지가 이를 통해 흐르지.",
			GEMS = "포커스에 생기가 없어.",
		},
		GEMSOCKET = 
		{
			VALID = "보석이 집중시켰어.",
			GEMS = "무척 비어 보이네.",
		},
		STAFFLIGHT = "작은 태양계가 보일락말락.",
		RESEARCHLAB4 = "거의 미친 것이나 마찬가지야.",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="예뻐.",
			LONG = "언니의 꽃이야. 멀리 갔어.",
			MEDIUM = "애비게일의 존재감이 더 강하게 느껴져.",
			SOON = "애비게일이 거의 다 왔어!",
			HAUNTED_POCKET = "애비게일이 놀이를 할 준비가 되었지만 공간이 좀 필요해.",
			HAUNTED_GROUND = "애비게일에게 놀이를 하는 방법을 알려 줘야 해.",

		},

        ANCIENT_ALTAR = "죽은 자의 메아리가 들려.",
        ANCIENT_ALTAR_BROKEN = "죽은 자의 고통스러운 메아리가 들려.",
        ANCIENT_STATUE = "별로 매력적이지 않아.",

        LICHEN = "어떻게 저렇게 잘 자라지?",
		CUTLICHEN = "목숨처럼 덧없이 지나가.",
		CAVE_BANANA = "껍질이 위험해 보여.",
		CAVE_BANANA_COOKED = "뜨끈한 바나나 덩이가 훨씬 더 좋네.",
		CAVE_BANANA_TREE = "불쌍한 식물, 해를 못 보고 있구나.",
		ROCKY = "끔찍한 광경을 봤을 거야.",


		BLUEAMULET = "익숙한 냉기의 포옹이야.",
		PURPLEAMULET = "스며 나와.",
		TELESTAFF = "더 강력하면 탈출할 수 있을 텐데.",
		MONKEY = "지성이라는 부담 없이 사니까 행복하겠네.",
		MONKEYBARREL = "더러워.",
		MONSTERLASAGNA = "요리한 악은 여전히 악이야, 라자냐에 넣어도.",
		HOUNDSTOOTH="뿌리채 뽑혔어.",
		ARMORSNURTLESHELL="이제 나의 문제로부터 숨을 수 있겠어.",
		BAT="밤의 동물이야.",
		BATBAT = "마법에 걸린 무기네. 아유, 신나라!",
		BATWING="날아갈 수 있으면 좋을 텐데.",
		BATWING_COOKED="위대한 잠재력을 가지고 있었어.",
		BEDROLL_FURRY="망자의 복슬복슬한 가죽으로 감싸겠어.",
		BUNNYMAN="고통스러운 정신 세계를 가지고 있겠네.",
		FLOWER_CAVE="약해 보여.",
		FLOWER_CAVE_DOUBLE="약해 보여.",
		FLOWER_CAVE_TRIPLE="약해 보여.",
		GUANO="삶의 어쩔 수 없는 부산물이야.",
		LANTERN="어둠을 비추어라.",
		LIGHTBULB="서서히 타서 없어지고 있어.",
		MANRABBIT_TAIL="복슬복슬한 정수를 담고 있네.",
		MUSHTREE_TALL  ="이상한 나무들이야.",
		MUSHTREE_MEDIUM="썩은 모자 같아.",
		MUSHTREE_SMALL ="작은 난쟁이들이 안에 사는 거야?",
		RABBITHOUSE="보기보다 먹을만하지 않네.",
		SLURTLE="생각 없이 바위를 쫓고 있어.",
		SLURTLE_SHELLPIECES="망가진 민달팽거북 꿈의 조각이야.",
		SLURTLEHAT="원래 소유주보다 나를 더 도와줄 것이라고 생각하지 않아.",
		SLURTLEHOLE="민달팽거북이 더 커지면 튀어 나와.",
		SLURTLESLIME="미끌거리는 기대감이 빛나네.",
		SNURTLE="저건 껍질이 더 크네.",
		SPIDER_HIDER="비겁한 거미네.",
		SPIDER_SPITTER="뭔가 씹고 있어.",
		SPIDERHOLE="잔뜩 있어.",
		STALAGMITE="땅이 선물을 주네.",
		STALAGMITE_FULL="땅이 선물을 주네.",
		STALAGMITE_LOW="땅이 선물을 주네.",
		STALAGMITE_MED="땅이 선물을 주네.",
		STALAGMITE_TALL="땅이 솟았어.",
		STALAGMITE_TALL_FULL="땅이 솟았어.",
		STALAGMITE_TALL_LOW="땅이 솟았어.",
		STALAGMITE_TALL_MED="땅이 솟았어.",

		TURF_CARPETFLOOR = "지면이야.",
		TURF_CHECKERFLOOR = "지면이야.",
		TURF_DIRT = "지면이야.",
		TURF_FOREST = "지면이야.",
		TURF_GRASS = "지면이야.",
		TURF_MARSH = "지면이야.",
		TURF_ROAD = "지면이야.",
		TURF_ROCKY = "지면이야.",
		TURF_SAVANNA = "지면이야.",
		TURF_WOODFLOOR = "지면이야.",

		TURF_CAVE="지면이야.",
		TURF_FUNGUS="지면이야.",
		TURF_SINKHOLE="지면이야.",
		TURF_UNDERROCK="지면이야.",
		TURF_MUD="지면이야.",

		POWCAKE = "절박해야 쓰겠네.",		
		CAVE_ENTRANCE = 
		{
			GENERIC="누군가가 지하로 가지 못하게 하려고 하네.",
			OPEN = "지하에 거대한 악의 존재가 거닐고 있어.",
		},
        CAVE_EXIT = "표면이 부르네.",
		BOOMERANG = "발신인에게 돌아오는 죽음이야.",
		MAXWELLPHONOGRAPH = "죽음의 춤을 출까?",
		ABIGAIL = "내 쌍둥이 언니, 애비게일이야.",
		PIGGUARD = "작은 돼지가 험악해 보이네.",
		ADVENTURE_PORTAL = "이것은 무슨 무시무시한 기술이지?",
		AMULET = "누가 이것을 소유했었을까.",
		ANIMAL_TRACK = "짐승의 표식이야.",
		ARMORGRASS = "운명을 연장할 뿐이야.",
		ARMORMARBLE = "내 심장을 찌를 단도를 막아줄 거야.",
		ARMORWOOD = "이것으로 운명을 약간 더 저지할 수 있어.",
		ARMOR_SANITY = "미치기 위한 완벽하게 안전한 방법이야.",
		ASH =
		{
			GENERIC = "아름다운 불이 꺼진 다음에 남은 것이야.",
			REMAINS_EYE_BONE = "내가 원격이동했을 때 눈뼈가 연소되었어!",
			REMAINS_THINGIE = "타기 전엔 무언가였을 텐데...",
		},
		AXE = "노동과 살해의 도구네.",
		BABYBEEFALO = "어린 시절을 잘 보내. 곧 현실이라는 공포를 배우게 될 테니까.",
		BACKPACK = "팩이네. 이제 더 많은 짐을 들 수 있어.",
		BACONEGGS = "또 다른 하루를 시작할 균형 있는 아침 식사야.",
		BANDAGE = "또 다치고 말 걸.",
		BASALT = "부수는 것은 무의미해.",
		BEARDHAIR = "추잡해.",
		BEDROLL_STRAW = "잠은 잠깐의 죽음이야.",
		BEE =
		{
			GENERIC = "침은 피해야지.",
			HELD = "가만히 있어, 작은 아이야.",
		},
		BEEBOX =
		{
			GENERIC = "그들이 일하면 내가 훔쳐야지.",
			READY = "그들의 고생이 결실을 맺었어!",
		},
		BEEFALO =
		{
			FOLLOWER = "나를 쫓으면 파멸로 치달을 거야.",
			GENERIC = "그 눈 뒤에서 어떤 생각을 하고 있을까.",
			NAKED = "이제 벌거숭이야.",
			SLEEPING = "어떤 악몽을 꾸고 있을까.",
		},
		BEEFALOHAT = "머리를 덮어야겠네.",
		BEEFALOWOOL = "어딘가에 헐벗고 추운 고기물소가 있겠네.",
		BEEHAT = "즐거운 소리를 막아줄 거야. 물론 침도.",
		BEEHIVE = "더껑이와 꽃가루가 든 몹쓸 벌통.",
		BEEMINE = "안에서 아직 살아있어. 불쌍해.",
		BERRIES = "베리가 시큼하네.",
		BERRIES_COOKED = "더 균형이 있는 맛이지만 오래 가지 않아.",
		BERRYBUSH =
		{
			BARREN = "황폐해.",
			GENERIC = "스낵인가, 아마?",
			PICKED = "기다려야겠어.",
		},
		BIRDCAGE =
		{
			GENERIC = "어떤 이는 자신의 우리를 볼 수 있어.",
			OCCUPIED = "그는 이제 더 행복해.",
			SLEEPING = "죽은 걸까?아니야. 자고 있는 거네.",
		},
		BIRDTRAP = "막대와 줄이 치명적으로 바뀌었네.",
		BIRD_EGG = "그 많은 희망이 사라졌어.",
		BIRD_EGG_COOKED = "더 이상 새가 생길 수 없어.",
		BISHOP = "그는 무엇을 위해 기도할까?",
		BLOWDART_SLEEP = "많이 자는 것이 아니라 조금만.",
		BLOWDART_PIPE = "내가 여기를 불면 반대쪽에서 고통이 나오네.",
		BLOWDART_FIRE = "세계를 불태울까?",
		BLUEGEM = "파란색은... 슬픈 새인가?",
		BLUEPRINT = "이걸 그린 자는 아마 죽었겠지.",
		BLUE_CAP = "따분함을 보존하는 버섯이네.",
		BLUE_CAP_COOKED = "모든 것은 변해.",
		BLUE_MUSHROOM =
		{
			GENERIC = "곰팡내가 나네.",
			INGROUND = "나라도 숨을 거야.",
			PICKED = "수확했어.",
		},
		BOARDS = "나무에게는 더 무섭겠네.",
		BONESTEW = "그들이 죽었어. 그리고 스튜에 집어넣었어.",
		BUGNET = "작은 곤충의 감옥이야.",
		BUSHHAT = "사라지고 싶어.",
		BUTTER = "기대하지 않았어.",
		BUTTERFLY =
		{
			GENERIC = "예쁘지만 짧은 삶이야.",
			HELD = "내 손 안에 들고 있어.",
		},
		BUTTERFLYWINGS = "나비가 더 이상 떠오를 수 없어.",
		BUTTERFLYMUFFIN = "이 달콤한 함정에서 빠져나올 수 있나 보자!",
		CAMPFIRE =
		{
			EMBERS = "어둠이 찾아 오고 있어.",
			GENERIC = "오늘밤은 살아남을 수 있겠어!",
			HIGH = "지옥 풍경!",
			LOW = "암흑이 접근하고 있어.",
			NORMAL = "불이야.",
			OUT = "좋은 징조가 아니야.",
		},
		CANE = "아무 데나 빨리 갈 수 있어.",
		CARROT = "당근이야.",
		CARROT_COOKED = "불의 공격을 받은 당근이야.",
		CARROT_PLANTED = "땅에 있는 당근이야.",
		CARROT_SEEDS = "언젠가는 이 씨가 당근이 될 거야.",
		CAVE_FERN = "어둠에 접촉하는 색.",
		CHARCOAL = "차갑고 죽었다, 내 마음처럼.",
        CHESSJUNK1 = "차갑고, 죽은 인공 생명이야.",
        CHESSJUNK2 = "차갑고, 죽은 인공 생명이야.",
        CHESSJUNK3 = "차갑고, 죽은 인공 생명이야.",
		CHESTER = "털 달린 공허한 공.",
		CHESTER_EYEBONE =
		{
			GENERIC = "내 혼을 보고 있어.",
			WAITING = "자는 것이 아니라... 기다리는 거야.",
		},
		COOKEDMANDRAKE = "좋은 죽음이었어. 맛있겠네.",
		COOKEDMEAT = "요리해서 피가 증발했어.",
		COOKEDMONSTERMEAT = "요리한 악은 여전히 악이야.",
		COOKEDSMALLMEAT = "불이 정화했어.",
		CORN = "유치한 농담을 할 수 있지만, 안 하겠어.",
		CORN_COOKED = "이 옥수수는 열을 견딜 수 없었어.",
		CORN_SEEDS = "음, 씨야.",
		CROW =
		{
			GENERIC = "내 심장에서 부리를 빼!",
			HELD = "내 거야.",
		},
		CUTGRASS = "작은 것들을 죽이는 것을 좋아해.",
		CUTREEDS = "나는 자르는 것을 좋아해.",
		CUTSTONE = "무덤을 표시할 때 좋아.",
		DEADLYFEAST = "이것이 나의 마지막 성찬이야.",
		DEERCLOPS = "죽음의 화신이네!",
		DEERCLOPS_EYEBALL = "어떤 공포를 목격할까.",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불의 잔재네.",
		},
		DIRTPILE = "어라. 흙이 더 있네.",
		DIVININGROD =
		{
			COLD = "근원은 멀리에 있어.",
			GENERIC = "없어진 짝을 영원히 찾고 있어.",
			HOT = "사악한 것이 여기에 있어!",
			WARM = "악이 다가오고 있어.",
			WARMER = "이제 아주 가까워.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "이 새로운 것이 무엇을 할 수 있을까?",
			READY = "그래도 큰 열쇠가 필요하네.",
			UNLOCKED = "뭘 찾을 수 있는지 보자!",
		},

		DRAGONFRUIT = "전혀 용처럼 생기지 않았어.",
		DRAGONFRUIT_COOKED = "그래도 용이 아니야. 적어도 죽긴 했어.",
		DRAGONFRUIT_SEEDS = "씨앗이야. 그래도 용이 자라지는 않아.",
		DRAGONPIE = "뭐, 적어도 이제는 파이네.",
		DRUMSTICK = "내려치면 소리를 잘 내고 영양이 있어!",
		DRUMSTICK_COOKED = "날것이 아니면 더 맛있어.",
		DUG_BERRYBUSH = "죽은 것이 마음에 들지만 이것을 심어야겠네.",
		DUG_GRASS = "죽은 것이 마음에 들지만 이것을 심어야겠네.",
		DUG_MARSH_BUSH = "죽은 것이 마음에 들지만 이것을 심어야겠네.",
		DUG_SAPLING = "왜 이것을 만들었는지 모르겠어.",
		DURIAN = "뾰족하고 냄새나!",
		DURIAN_COOKED = "덜 뾰족하지만 냄새는 더 나네!",
		DURIAN_SEEDS = "신기하게 씨는 냄새나지 않아.",
		EARMUFFSHAT = "그들의 끔찍한 종말이 나를 심한 추위로부터 막아주네.",
		EGGPLANT = "거의 치명적인 나이트셰이드. 거의.",
		EGGPLANT_COOKED = "나이트셰이드를 요리하니까 죽음의 느낌이 더 없어졌어.",
		EGGPLANT_SEEDS = "나이트셰이드 씨야.",
		EVERGREEN =
		{
			BURNING = "밝게 타고 있어.",
			BURNT = "사그라졌어.",
			CHOPPED = "다 죽으니까.",
			GENERIC = "자연은 너무 따분해.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "밝게 타고 있어.",
			BURNT = "사그라졌어.",
			CHOPPED = "다 죽으니까.",
			GENERIC = "생명의 순환이 끊어졌어.",
		},
		EYEPLANT = "주인의 모든 요구를 들어주지.",
		FARMPLOT =
		{
			GENERIC = "어떤 씨를 심을까?",
			GROWING = "꾸불꾸불한 이파리가 흙에서 삐져나와.",
			NEEDSFERTILIZER = "땅이 얼어서 죽었어.",
		},
		FEATHERHAT = "까아악!",
		FEATHER_CROW = "까마귀 깃털은 영원한 어둠처럼 흑색이야.",
		FEATHER_ROBIN = "피리새 깃털, 피처럼 붉은 색이야.",
		FEATHER_ROBIN_WINTER = "흰머리멧새 깃털이 터널 끝의 빛처럼 희네.",
		FEM_PUPPET = "그녀가 무엇을 했을까.",
		FIREFLIES =
		{
			GENERIC = "어둠 속의 작은 빛.",
			HELD = "작은 빛, 내 주머니 밖의 세상에서 표류하네.",
		},
		FIREHOUND = "성질이 불 같아.",
		FIREPIT =
		{
			EMBERS = "어둠이 찾아오고 있네.",
			GENERIC = "오늘밤을 살아남을 수 있겠어!",
			HIGH = "지옥 풍경!",
			LOW = "암흑이 접근하네.",
			NORMAL = "불이야.",
			OUT = "좋은 징조가 아니네.",
		},
		FIRESTAFF = "세상을 불지르겠어!",
		FISH = "살려고 발버둥쳤어. 불쌍한 것.",
		FISHINGROD = "이것으로 안전한 연못에서 물고기를 꺼낼 수 있어.",
		FISHSTICKS = "완벽하게 네모나게 만든 물고기야.",
		FISHTACOS = "뼈를 다 뺐기를 바래.",
		FISH_COOKED = "제대로 구우면 더 이상 팔딱거리지 않아.",
		FLINT = "작은 칼날 같은 바위야.",
		FLOWER = "밝고 명랑해. 우엑.",
		FLOWERHAT = "하지만 나는 애도하고 있어...",
		FLOWER_EVIL = "그래도 다른 꽃보다는 낫지.",
		FOLIAGE = "나를 아아르니발케아로 인도해 줘.",
		FOOTBALLHAT = "내가 입을 죽은 것이네. 좋아라.",
		FROG =
		{
			DEAD = "삶은 작고 짧은 것이야.",
			GENERIC = "작고 사마귀투성이야.",
			SLEEPING = "자고 있어.",
		},
		FROGGLEBUNWICH = "개구리 다리가 이렇게 좋아 보일 줄 몰랐어.",
		FROGLEGS = "개구리에서 뜯어냈어.",
		FROGLEGS_COOKED = "더 이상 안 꿈틀거려.",
		FRUITMEDLEY = "달고, 신 것이 컵 안에 들어있어.",
		GEARS = "기계 악마의 내부야.",
		GHOST = "무덤에서 일어났네!",
		GOLDENAXE = "적어도 멋지게 나무를 죽일 수 있겠네.",
		GOLDENPICKAXE = "적어도 멋지게 돌을 깰 수 있겠네.",
		GOLDENPITCHFORK = "적어도 멋지게 땅을 갈 수 있겠네.",
		GOLDENSHOVEL = "적어도 멋지게 땅 팔 수 있겠네.",
		GOLDNUGGET = "내가 가지겠어.",
		GRASS =
		{
			BARREN = "똥이 필요해.",
			BURNING = "냄새가 요상하다.",
			GENERIC = "풀 덤불일 뿐.",
			PICKED = "살해당했네.",
		},
		GREEN_CAP = "이 버섯은 실망스럽게 평범해.",
		GREEN_CAP_COOKED = "모든 것은 변해.",
		GREEN_MUSHROOM =
		{
			GENERIC = "습기 차.",
			INGROUND = "나라도 숨을 거야.",
			PICKED = "수확했어.",
		},
		GUNPOWDER = "어둠의 길을 걷는 나.",
		HAMBAT = "죽음이 죽음을 부르네.",
		HAMMER = "세상을 부수기 위하여.",
		HEALINGSALVE = "삶이 고통을 가져오고, 고통이 삶을 가져오네.",
		HEATROCK =
		{
			COLD = "그냥 약간 차가운 바위야.",
			GENERIC = "그냥 공간을 차지하고 있어.",
			HOT = "가장 밝게 타는 것이 가장 빠르게 타니까.",
			WARM = "다른 바위처럼 미지근하고 생명이 없어.",
		},
		HOMESIGN = "일시적이지만 표시를 남겼어.",
		HONEY = "달지만 일시적인 특식이야.",
		HONEYCOMB = "벌집 조각이 흩어졌어.",
		HONEYHAM = "이 생물체의 달콤한 포옹에 어울리는 달콤한 소스야.",
		HONEYNUGGETS = "이 생물체의 달콤한 포옹에 어울리는 달콤한 소스야.",
		HORN = "고기물소가 안에 갇힌 소리가 들려.",
		HOUND = "물러서, 사악한 악의 수하!",
		HOUNDBONE = "악한 짐승의 시체야.",
		HOUNDMOUND = "가장 끔찍한 생물체의 집이야.",
		ICEBOX = "내 마음처럼 차가워.",
		ICEHOUND = "차갑고 죽은 마음을 가졌어.",
		INSANITYROCK =
		{
			ACTIVE = "내 이름을 불러.",
			INACTIVE = "차갑고 검은색이야.",
		},
		JAMMYPRESERVES = "딱 적당한 양의 잼이야.",
		KABOBS = "중앙을 관통당한 고기네.",
		KILLERBEE =
		{
			GENERIC = "차갑고 죽은 마음을 가진 벌아.",
			HELD = "가만히 있어, 작은 아이야.",
		},
		KNIGHT = "차갑고 혼이 없는 말이네.",
		KOALEFANT_SUMMER = "외로움의 짐승.",
		KOALEFANT_WINTER = "악천후를 견디네.",
		KRAMPUS = "지하세계의 끔찍한 생물체야, 안녕.",
		KRAMPUS_SACK = "염소 냄새가 나.",
		LEIF = "육중한 짐승이네.",
		LEIF_SPARSE = "육중한 짐승이네.",
		LIGHTNING_ROD =
		{
			CHARGED = "결국 이 능력도 소진될 거야.",
			GENERIC = "파괴를 집중시켜.",
		},
		LITTLE_WALRUS = "폭력의 고리가 계속 이어져.",
		LIVINGLOG = "영원히 침묵 속에서 비명을 지르고 있어.",
		LOCKEDWES = "맥스웰의 조각상 때문에 갇혀서 영원히 사네.",
		LOG = "나무가 말할 수 있다면, 이것을 보고 비명을 지르겠네요.",
		LUREPLANT = "다 삼켜 버리네.",
		LUREPLANTBULB = "삶은 흐르네.",
		MALE_PUPPET = "그가 무엇을 했을까.",
		MANDRAKE =
		{
			DEAD = "아아, 불쌍한 맨드레이크야!",
			GENERIC = "강력한 맨드레이크야. 밤에 따야겠어.",
			PICKED = "전진, 나의 채소 부하들아!",
		},
		MANDRAKESOUP = "끓여서 생기가 사라졌어.",
		MARBLE = "매끄럽고 생명이 없어.",
		MARBLEPILLAR = "돌도 끊임없는 부식의 유혹 견딜 수 없지.",
		MARBLETREE = "이 차가운 나무에는 생명의 박동이 없어.",
		MARSH_BUSH =
		{
			BURNING = "가시도 불타네.",
			GENERIC = "언제나 아픈 관목이야.",
			PICKED = "그걸 하는 게 아팠어.",
		},
		MARSH_PLANT = "잡풀이야.",
		MARSH_TREE =
		{
			BURNING = "타고 있어.",
			BURNT = "내 마음처럼 검은색이야.",
			CHOPPED = "가시가 보호해 주지 못해.",
			GENERIC = "고통만 아는 나무야.",
		},
		MAXWELL = "그와 이상한 친밀함이 느껴져.",
		MAXWELLHEAD = "극적인 것을 좋아하는구나.",
		MAXWELLLIGHT = "궁금한 빛이야.",
		MAXWELLLOCK = "마법으로 보이네.",
		MAXWELLTHRONE = "내가 예상한 것이 아니야.",
		MEAT = "아직도 피가 흘러.",
		MEATBALLS = "공 고기네. 아유, 신나라.",
		MEATRACK =
		{
			DONE = "건조가 끝났어.",
			DRYING = "건조한 바람 속에서 흔들려.",
			GENERIC = "여기에 고기를 말릴 수 있어.",
		},
		MEAT_DRIED = "고기가 마르고 맛있어졌어.",
		MERM = "끔찍한 늪 괴물!",
		MERMHEAD = "전혀 품위 없어.",
		MERMHOUSE = "시간의 흐름으로 망가졌네.",
		MINERHAT = "핸즈프리 조명이네!",
		MONSTERMEAT = "악의 기운이 흐르고 있어.",
		MONSTERMEAT_DRIED = "고기가 건조해지고 맛이 이상해졌어.",
		MOSQUITO =
		{
			GENERIC = "살기 위해 삶을 빼앗네.",
			HELD = "훔친 온기가 느껴져.",
		},
		MOSQUITOSACK = "모기에서 뜯어낸 피 주머니. 마음에 들어.",
		MOUND =
		{
			DUG = "땅이 비밀을 토해냈어.",
			GENERIC = "언젠가 너를 쫓아갈게.",
		},
		NIGHTLIGHT = "무시무시하면서도 아름다워.",
		NIGHTMAREFUEL = "꿈이 잠들 때 이것이 찾아 와.",
		NIGHTSWORD = "꿈이 한 곳에 모였어. 날카로워.",
		NITRE = "인간의 어리석음이 담겨 있어.",
		ONEMANBAND = "전에는 이런 악기가 재미있었어.",
		PANDORASCHEST = "인생은 도박이야.",
		PANFLUTE = "음악은 내 텅 빈 혼의 창이야.",
		PAPYRUS = "나의 고통을 기록하기 위하여.",
		PENGUIN = "옷을 차려 입었지만 어디로 가?",
		PERD = "바보 새야!내 베리에서 멀찍이 떨어져!",
		PEROGIES = "사랑스러운 영양 주머니.",
		PETALS = "내가 아름다운 것을 파괴했어.",
		PETALS_EVIL = "내 혼의 색으로 칠해졌어.",
		PICKAXE = "땅을 관통하기 위하여.",
		PIGGYBACK = "죽으면 더 유용하지.",
		PIGHEAD = "돼지를 죽여라. 그의 피를 흘려라.",
		PIGHOUSE =
		{
			FULL = "그가 즐기고 있다면 좋겠어.",
			GENERIC = "적어도 그들은 편안하겠지.",
			LIGHTSOUT = "이제 난 혼자야.",
		},
		PIGKING = "살 수 있을 때 살아라, 폐하.",
		PIGMAN =
		{
			DEAD = "더 좋은 곳으로 갔어.",
			FOLLOWER = "너무 외로워.",
			GENERIC = "너무 무뚝뚝해.",
			GUARD = "오웰의 소설 같아.",
			WEREPIG = "밤의 동물이네!",
		},
		PIGSKIN = "죽은 돼지 가죽이네.",
		PIGTORCH = "어둠을 가르네.",
		PINECONE = 
		{
		    GENERIC = "작은 생명, 깨지기 쉬운 죽음이 감싸고 있네.",
		    PLANTED = "나무가 금방 자라겠네.",
		},
		PITCHFORK = "마귀의 도구네!",
		PLANTMEAT = "냄새가 구역질 나.",
		PLANTMEAT_COOKED = "약간만 더 나아.",
		PLANT_NORMAL =
		{
			GENERIC = "먹는 풀이야.",
			GROWING = "계속 자라라. 기다릴게.",
			READY = "수확 준비가 되었어.",
		},
		POMEGRANATE = "씹고 으깰 빨간 과즙 알갱이네!",
		POMEGRANATE_COOKED = "따뜻하지만 더 깔끔하진 않아.",
		POMEGRANATE_SEEDS = "씨가 더 나올 줄 알았어.",
		POND = "오펠리아?아래에 있는 거야?",
		POOP = "인생은 피 그리고 이것이야.",
		PUMPKIN = "내 마음이 있던 곳의 구멍만큼 커.",
		PUMPKINCOOKIE = "내가 직접 요리했어!",
		PUMPKIN_COOKED = "열 때문에 약간 오그라들었어. 마음에 들어.",
		PUMPKIN_LANTERN = "넌 별로 안 무서워.",
		PUMPKIN_SEEDS = "씨앗이야. 신나라.",
		PURPLEGEM = "자주색은... 자주색이야.",
		RABBIT =
		{
			GENERIC = "운명을 모른 채 생각 없이 헤매고 있어.",
			HELD = "안전하게 나의 포옹을 받아들이네.",
		},
		RABBITHOLE = "안에 빠져들기에는 내가 너무 커.",
		RAINOMETER = "구름 낀 정도를 측정하네. 적적한 것이 마음에 들어.",
		RATATOUILLE = "요리한 채소가 잔뜩 있어. 황홀해.",
		RAZOR = "면도용이야.",
		REDGEM = "내 심장의 피처럼 빨개.",
		RED_CAP = "내 마음을 빼앗으려는 버섯이네.",
		RED_CAP_COOKED = "모든 것은 변해.",
		RED_MUSHROOM =
		{
			GENERIC = "축축해.",
			INGROUND = "나라도 숨을 거야.",
			PICKED = "수확했어.",
		},
		REEDS =
		{
			BURNING = "곧 재가 되겠네.",
			GENERIC = "갈대 덤불일 뿐이야.",
			PICKED = "집었어.",
		},
        RELIC = 
        {
            GENERIC = "고대 세계의 잔재야.",
            BROKEN = "부서진 돌 조각이야.",
        },
        RUINS_RUBBLE = "망가진 꿈의 더미야.",
		RESEARCHLAB = "끔찍한 것을 배우겠네.",
		RESEARCHLAB2 = "끔찍한 것을 배우겠네.",
		RESEARCHLAB3 = "말하지 못할 것들을 배웠어.",
		RESURRECTIONSTATUE = "운명을 약간 늦추는 것 뿐이야.",
		RESURRECTIONSTONE = "부질없는 짓이야.",
		ROBIN =
		{
			GENERIC = "봄이 왔다는 걸까?아니었으면 좋겠네.",
			HELD = "주머니 안에 갇혀 있는 것을 좋아해.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "쓸쓸한 동토의 삶이야.",
			HELD = "무척 부드럽네. 나의 적이야.",
		},
		ROBOT_PUPPET = "이것이 무엇을 했을까.",
		ROCK_LIGHT =
		{
			GENERIC = "위가 딱딱해진 용암 구덩이야.",
			OUT = "무해해 보여.",
			LOW = "그림자가 접근하고 있어.",
			NORMAL = "용암이 불붙었어.",
		},
		ROCK = "그것도 영원하진 않아.",
		ROCKS = "작은 바위야.",
        ROOK = "루크인가?아니면 성인가?",
		ROPE = "저것으로 쉽게 여기를 빠져나갈 수 있겠지.",
		ROTTENEGG = "만물의 도야.",
		SANITYROCK =
		{
			ACTIVE = "나를 부르네.",
			INACTIVE = "방첨탑도 날 떠났어.",
		},
		SAPLING =
		{
			BURNING = "화염의 봉인이네.",
			GENERIC = "성장하려고 하네.",
			PICKED = "다음 기회를 노려라, 어린나무.",
		},
		SEEDS = "삶 또는 삶에 대한 약속.",
		SEEDS_COOKED = "생기를 구워서 없앴어.",
		SEWING_KIT = "피할 수 없는 부패를 지연하기 위한 또 다른 방법이야.",
		SHOVEL = "어떤 끔찍한 비밀을 내가 드러낼까?",
		SILK = "미끌거리고 가느다라네.",
		SKELETON = "탈출한 그가 부러워.",
		SKULLCHEST = "나의 메멘토 모리를 보관할 거야.",
		SMALLBIRD =
		{
			GENERIC = "안녕, 작은 아이야.",
			HUNGRY = "속이 비었어?",
			STARVING = "씨가 돌아오지 않는 블랙홀이야.",
		},
		SMALLMEAT = "작은 두려움의 냄새가 나.",
		SMALLMEAT_DRIED = "고기가 마르고 맛있어졌어.",
		SPEAR = "내가 세계의 파괴자가 되었네.",
		SPIDER =
		{
			DEAD = "언젠가 다시 만날 거야.",
			GENERIC = "밤의 동물이네!",
			SLEEPING = "악이 잠들어 있어.",
		},
		SPIDERDEN = "더러움과 악함의 둥지야.",
		SPIDEREGGSACK = "죽음과 파괴를 가득 담은 작은 꾸러미.",
		SPIDERGLAND = "이 짐승은 죽어서도 고통을 주네.",
		SPIDERHAT = "심연을 바라볼 때야.",
		SPIDERQUEEN = "제왕적인 끔찍함을 갖추었네.",
		SPIDER_WARRIOR =
		{
			DEAD = "아아, 용감한 전사.",
			GENERIC = "밤의 전사야!",
			SLEEPING = "조심해야 해.",
		},
		SPOILED_FOOD = "결국 모든 것은 쓰레기가 되지.",
		STATUEHARP = "어쩌면 이 조각상들이 나의 친구가 되어주겠네.",
		STATUEMAXWELL = "그가 날 데려왔어.",
		STINGER = "날카롭고 치명적이야.",
		STRAWHAT = "머리를 덮어야겠네.",
		STUFFEDEGGPLANT = "나이트셰이드야. 아마 독이 들어있지는 않아.",
		SUNKBOAT = "잔인한 꾀야!",
		SWEATERVEST = "죽은 조각들을 조끼로 만들어서 입을 수 있어!",
		TAFFY = "이렇게 달콤한 것을 내가 만들 줄이야.",
		TALLBIRD = "하늘의 굴레에서 해방되었네.",
		TALLBIRDEGG = "잠재성이 가득해.",
		TALLBIRDEGG_COOKED = "약속을 다 앗아갔어. 베이컨과 같이 먹으면 나쁘지 않아.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "어둠으로 냉각되었어.",
			GENERIC = "작고 허약한 존재가 빛을 향해 힘겹게 가.",
			HOT = "열을 견딜 수 없어.",
			LONG = "먼저 시작한 삶은 먼저 끝나.",
			SHORT = "이제 곧.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "저 알은 새 삶은 상징해. 윽.",
			PICKED = "둥지가 비어있네. 비어있어. 불모지야. 공허야.",
		},
		TEENBIRD =
		{
			GENERIC = "너도 날 떠날 거야?",
			HUNGRY = "우리 모두 공허함을 채우려고 하네.",
			STARVING = "너의 진정한 모습이 드러났어!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "다음 영역은 더욱 끔찍할 거야!",
			GENERIC = "좋을 것이 없어.",
			LOCKED = "아직 잠겨 있어.",
			PARTIAL = "반을 세운 걸까, 반을 파괴한 걸까?",
		},
		TELEPORTATO_BOX = "생명의 불꽃이 들어있어.",
		TELEPORTATO_CRANK = "복잡해 보여.",
		TELEPORTATO_POTATO = "끔찍한 것!",
		TELEPORTATO_RING = "날카로운 모서리가 없어.",
		TENT = "잠은 죽음의 시사회야.",
		TENTACLE = "길고 가느다랗고 위험해!",
		TENTACLESPOTS = "이것은 말하지 않는 것이 나아.",
		TENTACLESPIKE = "날카롭고, 미끌거리고, 위험해.",
        TENTACLE_PILLAR = "이런 일이 아래에서 일어나네.",
        TENTACLE_PILLAR_ARM = "아기들아!",
        TENTACLE_GARDEN = "이 건 다르네.",
		TOPHAT = "머리를 덮어야겠네.",
		TORCH = "밤에 저항하는 조그마한 성채야.",
		TRAP = "단순한 풀이 치명적으로 변했어.",
		TRAP_TEETH = "땅 밑의 못된 깜짝선물이네.",
		TRAP_TEETH_MAXWELL = "전혀 기대치 못했을 때의 죽음.",
		TREASURECHEST = "나의 부를 간직하는 것이야.",
		TRINKET_1 = "완벽하게 기형적이야.",
		TRINKET_10 = "먹일 입이 늘었네.",
		TRINKET_11 = "행운의 로봇이구나, 혼을 가졌던 적이 없으니.",
		TRINKET_12 = "더 이상 미끌거리지 않지?",
		TRINKET_2 = "가짜야. 죽음처럼 유혹하네.",
		TRINKET_3 = "칼이 내 문제를 다 해결할 수 있다면...",
		TRINKET_4 = "이를 세계 끝까지 가져가겠어.",
		TRINKET_5 = "더 컸더라면 이것을 태양으로 바로 날렸을 거야.",
		TRINKET_6 = "한 때 전기가 흘렀지만, 지금은 끝났네.",
		TRINKET_7 = "단순한 놀이일 뿐이야.",
		TRINKET_8 = "목욕하고 싶어.",
		TRINKET_9 = "짝이 안 맞는 삶을 위한 짝이 안 맞는 단추네.",
		TRUNKVEST_SUMMER = "내 피부에 착용하는 피부.",
		TRUNKVEST_WINTER = "내 몸은 따뜻하게 해주지만, 내 정신은?",
		TRUNK_COOKED = "지금은 더 안 좋아 보여.",
		TRUNK_SUMMER = "귀가 더 마음에 들어.",
		TRUNK_WINTER = "유일한 친구와 헤어졌네.",
		TURKEYDINNER = "이제는 누가 먹이가 되었나?",
		TWIGS = "다 자라기 전에 땅에서 뽑혔네.",
		UMBRELLA = "구름이 울어.",
		WAFFLES = "정말 와플이네.",
		WALL_HAY = "최소한의 방어네.",
		WALL_HAY_ITEM = "방어 효과는 의심스러워.",
		WALL_STONE = "내부에 있는 것으로부터 무엇이 날 지켜줄까?",
		WALL_STONE_ITEM = "안에 있는 악귀를 막아주진 않아.",
		WALL_RUINS = "이것이 고대인들을 지켜 주지 못했어!",
		WALL_RUINS_ITEM = "돌에 귀신이 든 걸까?",
		WALL_WOOD = "이제 운명을 지연시킬 수 있네.",
		WALL_WOOD_ITEM = "묶어 놓은 통나무들.",
		WALRUS = "바다의 노인이네.",
		WALRUSHAT = "이 아래에서 무슨 열띤 생각을 했을까?",
		WALRUS_CAMP =
		{
			EMPTY = "거기에 없다면 어디에 있을까?",
			GENERIC = "이 집은 행복하지 않네, 안타깝게도.",
		},
		WALRUS_TUSK = "너를 갉겠어.",
		WASPHIVE = "증오의 요새 안에 숨어있어.",
		WETGOOP = "삶처럼 비참한 진창이야.",
		WINTERHAT = "다가오는 냉기를 물리쳐 주네.",
		WINTEROMETER = "나의 죽을 운명을 측정하고 있다는 느낌이 드네?",
		WORMHOLE =
		{
			GENERIC = "삶은 부조리해.",
			OPEN = "무엇을 삼키든 만족하지 않아.",
		},
		ACCOMPLISHMENT_SHRINE = "메타포를 좋아한 적은 없어.",
		LIVINGTREE = "절대로 죽을 수 없나?",
		ICESTAFF = "냉동 지팡이야.",
	},
	DESCRIBE_GENERIC = "입에 담을 수 없어.",
	DESCRIBE_TOODARK = "어둠이야!이건 너무 어두워!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "삶의 번뇌를 없애주었어.",
	},
}
