return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Je crois qu'il n'a pas aimé ça.",
			GENERIC = "Seul le poil se rase.",
			NOBITS = "Déjà rasé, hein ?",
		},
		STORE =
		{
			GENERIC = "C'est déjà plein comme un œuf.",
			NOTALLOWED = "On n'a pas le droit, hein ?",
		},
	},
	ACTIONFAIL_GENERIC = "Désolé, je peux pas faire ça.",
	ANNOUNCE_ADVENTUREFAIL = "Ah tant pis, au moins j'aurai essayé.",
	ANNOUNCE_BEES = "Des abeilles ! Des abeilles !",
	ANNOUNCE_BOOMERANG = "Désolé ! Je suis pas adroit !",
	ANNOUNCE_CHARLIE = "Qui est là ? Hein ?",
	ANNOUNCE_CHARLIE_ATTACK = "Aïe ! C'était brutal !",
	ANNOUNCE_COLD = "Il fait froid par là !",
	ANNOUNCE_CRAFTING_FAIL = "Je ne peux pas faire ça pour le moment.",
	ANNOUNCE_DEERCLOPS = "C'était quoi ça ?",
	ANNOUNCE_DUSK = "C'est presque l'heure du coucher.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Bon !",
		PAINFUL = "La date de péremption était dépassée.",
		SPOILED = "C'était un peu cradingue.",
		STALE = "Fallait pas attendre plus longtemps.",
	},
	ANNOUNCE_ENTER_DARK = "Qui a éteint la lumière ?",
	ANNOUNCE_ENTER_LIGHT = "Lumière !",
	ANNOUNCE_FREEDOM = "Je suis sorti !",
	ANNOUNCE_HOUNDS = "Il y a quelque chose par là.",
	ANNOUNCE_HUNGRY = "Je commence à avoir la dalle.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "La bestiole est pas loin.",
	ANNOUNCE_HUNT_LOST_TRAIL = "La bestiole est partie.",
	ANNOUNCE_INV_FULL = "Je peux plus rien transporter.",
	ANNOUNCE_KNOCKEDOUT = "Ho ! C'était quoi ?",
	ANNOUNCE_MOSQUITOS = "Des moustiques !",
	ANNOUNCE_NODANGERSLEEP = "J'ai bien trop peur pour dormir.",
	ANNOUNCE_NODAYSLEEP = "Y a que les minables qui dorment la journée.",
	ANNOUNCE_NOHUNGERSLEEP = "J'ai l'estomac trop creux pour m'endormir.",
	ANNOUNCE_NO_TRAP = "Pas passé loin !",
	ANNOUNCE_PECKED = "Désolé ! C'est de ma faute !",
	ANNOUNCE_QUAKE = "Le sol se soulève !",
	ANNOUNCE_THORNS = "Ouille !",
	ANNOUNCE_TORCH_OUT = "Ma lumière s'est éteinte !",
	ANNOUNCE_TRAP_WENT_OFF = "Mince...",
	ANNOUNCE_WORMHOLE = "C'était dégueu là-dedans !",
	ANNOUNCE_CANFIX = "\nJe dois pouvoir réparer ça !",
	ANNOUNCE_ACCOMPLISHMENT= "Lucy va être fière de moi !",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Ça sera tout, hein ?",
	BATTLECRY =
	{
		GENERIC = "Viens par ici, hein ?",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Je crois que c'est terminé.",
	},
	DESCRIBE =
	{
		WORMLIGHT = "Ça pourrait servir.",
		WORM =
		{
		    PLANT = "Je reconnais une plante immédiatement. Ça c'est un imposteur !",
		    DIRT = "Attention au sol mouvant.",
		    WORM = "UN VER !",
		},
		EEL = "Ça devrait être bon cuit.",
		EEL_COOKED = "Très bon cuit ça.",
		UNAGI = "Pour se gaver.",
		EYETURRET = "Ça éloignera les minables.",
		EYETURRET_ITEM = "Il faut installer ça comme il faut.",
		MINOTAURHORN = "Une jolie corne, hein ?",
		MINOTAURCHEST = "Un joli coffre avec des cornes, hein ?",
		THULECITE_PIECES = "C'est pas du bois, mais ça ira.",
		POND_ALGAE = "Ça a pas l'air mangeable.",
		GREENSTAFF = "Ça va m'aider à démantibuler des trucs !",
		POTTEDFERN = "C'est bien la preuve que j'aime les végétaux.",

		THULECITE = "C'est le bois des grottes !",
		ARMORRUINS = "Ça bloquera la douleur.",
		RUINS_BAT = "Du métal sur un bout de bois.",
		RUINSHAT = "C'est pas une toque, mais ça ira.",
		NIGHTMARE_TIMEPIECE = 
		{
		CALM = "Je crois que c'est éteint.",	
		WARN = "Ce truc vient de s'allumer !",	
		WAXING = "Ça vibre !", 
		STEADY = "Ça devient fou !", 
		WANING = "Ça se calme.", 
		DAWN = "C'est presque arrêté.", 
		NOMAGIC = "Je crois que c'est éteint.", 
		},
		BISHOP_NIGHTMARE = "On voit même ses organes fonctionner !",
		ROOK_NIGHTMARE = "Ses mécanismes sont de sortie.",
		KNIGHT_NIGHTMARE = "Pas en grande forme apparemment.",
		MINOTAUR = "Encore une de ces pauvres âmes maudites.",	
		SPIDER_DROPPER = "Elles ont raison d'avoir fui ce monde corrompu.",	
		NIGHTMARELIGHT = "Ils auraient dû utiliser du bois.",	
		RELIC = "Du mobilier.",	
		RUINS_RUBBLE = "C'est complètement bousillé.",	
		MULTITOOL_AXE_PICKAXE = "Comment dire... c'est beau quoi !",	
		GREENGEM = "Ça brille fort.",
		ORANGESTAFF = "Ça m'aidera à me déplacer plus vite.",	
		YELLOWAMULET = "Je pourrais couper du bois la nuit avec ça.",	
		GREENAMULET = "Je suis plus fort pour couper du bois.",	

		SLURPER = "On dirait du poil vivant.",
		SLURPER_PELT = "On dirait un castor mort.",
		ARMORSLURPER = "Ça chatouille, je crois qu'il est encore vivant.",
		ORANGEAMULET = "Les corvées passeront plus vite !",
		YELLOWSTAFF = "Utile, à la rigueur !",
		YELLOWGEM = "Je vois les étoiles là-dedans.",
		ORANGEGEM = "C'est chatoyant.",
		TELEBASE = 
		{
			VALID = "Ça c'est prêt. Mais moi ?",
			GEMS = "Il faut des gemmes, hein ?",
		},
		GEMSOCKET = 
		{
			VALID = "On dirait que c'est prêt.",
			GEMS = "Il faudra une gemme.",
		},
		STAFFLIGHT = "C'est pas quelque chose ça ?",
		RESEARCHLAB4 = "J'appelle ça la « Machine au chapeau » !",

	
		LUCY = "J'aime Lucy !",

        ANCIENT_ALTAR =
        {
        	WORKING = "Il y a des marques de hache sur les pierres de cet autel.",
        	BROKEN = "Ça a l'air un peu usé.",
        },     
        
        ANCIENT_ALTAR_BROKEN = "Ça a l'air un peu usé.",
        ANCIENT_STATUE = "Encore un minable.",

        LICHEN = "Ça n'a pas l'air très mangeable.",
		CUTLICHEN = "Miam ! On dirait du bois !",

		CAVE_BANANA = "Un goût des tropiques.",
		CAVE_BANANA_COOKED = "Je l'ai cuite.",
		CAVE_BANANA_TREE = "On n'a pas de ça par chez nous.",
		ROCKY = "Le homard est servi !",
		
		COMPASS =
		{
			GENERIC="Je sais pas m'en servir.",
			N = "Vrai Nord.",
			S = "Sud",
			E = "Est",
			W = "Ouest",
			NE = "Nord-est",
			SE = "Sud-est",
			NW = "Nord-ouest",
			SW = "Sud-ouest",
		},


		BLUEAMULET = "Je boirais bien un truc frais moi, hein ?",
		PURPLEAMULET = "La gemme a perdu son étincelle.",
		TELESTAFF = "Je me demande à quoi ça sert.",
		MONKEY = "Ça c'est nouveau !",
		MONKEYBARREL = "Excellent choix de matériaux.",

		HOUNDSTOOTH="Une beauté, hein ?",
		ARMORSNURTLESHELL="On n'est jamais trop prudent.",
		BAT="Qui a appris à voler à ce rat ?",
		BATBAT = "Une souris avec des ailes ?",
		BATWING="Écœurant !",
		BATWING_COOKED="Dégoûtant ! Et vachement bon ! J'y comprends rien !",
		
		BEDROLL_FURRY="J'adore le camping !",
		BUNNYMAN="Il a l'air assez sympa.",
		FLOWER_CAVE="Ça brille !",
		FLOWER_CAVE_DOUBLE="Ça brille !",
		FLOWER_CAVE_TRIPLE="Ça brille !",
		GUANO="Ça pue moins que l'autre crotte.",
		LANTERN="Haute technologie !",
		LIGHTBULB="Ça a l'air dur à mâcher.",
		MANRABBIT_TAIL="Je suis désolé pour lui.",
		MUSHTREE_TALL  ="Va falloir que je coupe ça.",
		MUSHTREE_MEDIUM="Je devrais peut-être le couper.",
		MUSHTREE_SMALL ="C'est en bois.",
		RABBITHOUSE="Ça a goût de carotte ?",
		SLURTLE="Il a juste pas compris.",
		SLURTLE_SHELLPIECES="J'ai cassé sa maison. J'ai honte.",
		SLURTLEHAT="Ça ma protégera la caboche.",
		SLURTLEHOLE="Hé les gars ? Ça va là-dedans ?",
		SLURTLESLIME="J'en connais qui ont oublié leur mouchoir.",
		SNURTLE="En spirale !",
		SPIDER_HIDER="Diablesse !",
		SPIDER_SPITTER="Cracher c'est pas poli !",
		SPIDERHOLE="Je devrais déguerpir avant qu'elles sortent de là.",
		STALAGMITE="Les cailloux ça me passionne pas.",
		STALAGMITE_FULL="Les cailloux ça me passionne pas.",
		STALAGMITE_LOW="Les cailloux ça me passionne pas.",
		STALAGMITE_MED="Les cailloux ça me passionne pas.",
		STALAGMITE_TALL="Les cailloux ça me passionne pas.",
		STALAGMITE_TALL_FULL="Les cailloux ça me passionne pas.",
		STALAGMITE_TALL_LOW="Les cailloux ça me passionne pas.",
		STALAGMITE_TALL_MED="Les cailloux ça me passionne pas.",


		TURF_CARPETFLOOR = "Trop classe pour moi.",
		TURF_CHECKERFLOOR = "Les citadins mettent ça dans les toilettes du jardin.",
		TURF_DIRT = "Juste de la terre, hein ?",
		TURF_FOREST = "Juste de la terre, hein ?",
		TURF_GRASS = "Juste de la terre, hein ?",
		TURF_MARSH = "Juste de la terre, hein ?",
		TURF_ROAD = "Juste de la terre, hein ?",
		TURF_ROCKY = "Juste de la terre, hein ?",
		TURF_SAVANNA = "Juste de la terre, hein ?",
		TURF_WOODFLOOR = "Un parquet de roi !",

		TURF_CAVE="De la terre.",
		TURF_FUNGUS="Comme de la bouillie de pois.",
		TURF_SINKHOLE="J'ai trouvé ça sous la terre.",
		TURF_UNDERROCK="Du caillou. Pouah !",	
		TURF_MUD="L'avantage c'est qu'on passe plus la serpillère.",

		
		POWCAKE = "Je préfère ceux avec du vrai sucre.",
        CAVE_ENTRANCE = 
        {
            GENERIC="C'est bouché.",
            OPEN = "On dirait qu'une météorite est tombée ici.",
        },
        CAVE_EXIT = "Il doit y avoir des arbres là-haut.",
		
		MAXWELLPHONOGRAPH = "Mieux que ce qu'ils passent à la radio.",
		BOOMERANG = "Ça doit être dur à lancer.",
		PIGGUARD = "J'ai pas envie de l'énerver.",
		ADVENTURE_PORTAL = "Je me demande si c'est la sortie.",
		AMULET = "Il faut toujours un plan B.",
		ANIMAL_TRACK = "Une grosse créature des forêts est passée par ici !",
		ARMORGRASS = "C'est mieux que rien.",
		ARMORMARBLE = "Dur de manier la hache habillé avec ça.",
		ARMORWOOD = "Ça me va comme un gant !",
		ARMOR_SANITY = "Regarder ça me met mal à l'aise.",
		ASH =
		{
			GENERIC = "C'est tout brûlé.",
			REMAINS_EYE_BONE = "C'était un os-œil.",
			REMAINS_THINGIE = "J'imagine que ça passe pas là-dedans.",
		},
		AXE = "Pas aussi belle que Lucy.",
		BABYBEEFALO = "Avec une tête pareille, sa mère a dû porter plainte.",
		BACKPACK = "C'est mon sac à dos.",
		BACONEGGS = "Ah ! Y a du monde au bacon.",
		BANDAGE = "Au moins c'était gratuit.",
		BASALT = "Ce rocher ne bougera pas.",
		BEARDHAIR = "C'est pas les miens.",
		BEDROLL_STRAW = "J'ai dormi sur pire au camp de bûcherons.",
		BEE =
		{
			GENERIC = "Elle fait pousser les fleurs.",
			HELD = "Et maintenant, j'en fais quoi ?",
		},
		BEEBOX =
		{
			FULLHONEY = "Du miel !",
			GENERIC = "Des abeilles !",
			NOHONEY = "Rien qu'à voir ça, j'ai faim.",
			SOMEHONEY = "Je pourrais en avoir plus en étant patient.",
		},
		BEEFALO =
		{
			FOLLOWER = "Je crois qu'il m'aime bien.",
			GENERIC = "Il sent l'étable.",
			NAKED = "Courage, hein ?",
			SLEEPING = "Il en écrase.",
		},
		BEEFALOHAT = "Maintenant je suis le roi des bœufalos !",
		BEEFALOWOOL = "On dirait ma barbe.",
		BEEHAT = "Les abeilles ne pourront pas me piquer les yeux.",
		
		BEEHIVE = "Elles sont bien au chaud là-dedans.",
		
		BEEMINE = "Je sais pas si les abeilles aiment ça.",
		BEEMINE_MAXWELL = "Hé ! C'est méchant ça !",
		BERRIES = "Il me faudra plus pour me rassasier.",
		BERRIES_COOKED = "Ça a le goût de baies cuites.",
		BERRYBUSH =
		{
			BARREN = "Il lui faudrait un bon coup de crottin.",
			GENERIC = "Des baies de Saskatoon ?",
			PICKED = "Il n'y a plus de baies !",
		},
		BIRDCAGE =
		{
			GENERIC = "C'est là que j'essaie de rééduquer les oiseaux.",
			OCCUPIED = "Réfléchis à ce que tu as fait, l'oiseau !",
			SLEEPING = "Ça a l'air si innocent quand ça dort...",
		},
		BIRDTRAP = "Je vais leur montrer à ces piafs !",
		BIRD_EGG = "Là-dedans y a un oiseau avec des sales pensées d'oiseau.",
		BIRD_EGG_COOKED = "Au moins, il n'a pas eu le temps de devenir un oiseau.",
		BISHOP = "Ça fait longtemps que je suis pas allé à confesse.",
		BLOWDART_FIRE = "Ça m'a l'air un peu agressif.",
		BLOWDART_SLEEP = "Je pourrai m'échapper si je me sers de ça !",
		BLOWDART_PIPE = "Voyons ce que je fais de ça avec mes gros poumons !",
		BLUEGEM = "C'est très froid.",
		BLUEPRINT = "Les bouquins c'est pas mon truc.",
		BLUE_CAP = "C'est pas de la viande.",
		BLUE_CAP_COOKED = "C'est pas de la viande.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Je me rappelle jamais lesquels on peut manger.",
			INGROUND = "Je reviendrai plus tard.",
			PICKED = "Bon, c'est terminé.",
		},
		BOARDS = "Elles sont si lisses qu'on peut voir le grain.",
		BOAT = "Il a dû rencontrer le Nordet.",
		BONESTEW = "Ça tient au ventre.",
		BUGNET = "Je peux attraper des moustiques.",
		BUSHHAT = "C'est pas mal pour se camoufler.",
		BUTTER = "Je préfère la margarine.",
		BUTTERFLY =
		{
			GENERIC = "Je me suis toujours méfié de ces trucs, hein ?",
			HELD = "Tu crois t'échapper où ?",
		},
		BUTTERFLYMUFFIN = "Croustillant !",
		BUTTERFLYWINGS = "Désolé ! Je suis un être immonde !",
		CAMPFIRE =
		{
			EMBERS = "C'est presque éteint.",
			GENERIC = "Où est ma guitare ?",
			HIGH = "Hou là ! C'est un peu haut !",
			LOW = "Je devrais peut-être faire quelque chose, hein ?",
			NORMAL = "J'adore un bon feu en soirée.",
			OUT = "C'était bien quand ça flambait.",
		},
		CANE = "C'est bon pour la campagne ça.",
		CARROT = "C'est de la bouffe de lapin.",
		CARROT_COOKED = "C'est de la bouffe de lapin.",
		CARROT_PLANTED = "Les légumes, c'est pas mon truc, hein ?",
		CARROT_SEEDS = "Des bébés carottes.",
		CAVE_FERN = "Hé ! C'est une fougère !",

		CHARCOAL = "Ça me rend un peu triste.",

        CHESSJUNK1 = "Du métal mort.",
        CHESSJUNK2 = "Du métal mort.",
        CHESSJUNK3 = "Du métal mort.",

		CHESTER = "Il fait de son mieux !",
		CHESTER_EYEBONE =
		{
			GENERIC = "Il a pas appris qu'on fixe pas les gens comme ça ?",
			WAITING = "Je me demande s'il va se réveiller.",
		},
		COOKEDMANDRAKE = "C'était pas une chose à faire ?",
		COOKEDMEAT = "Exactement comme faisait la grand-mère.",
		COOKEDMONSTERMEAT = "Toujours pas envie de manger ça.",
		COOKEDSMALLMEAT = "Je vais avoir encore plus faim avec ça !",
		COOKPOT =
		{
			COOKING_LONG = "Ça va prendre un peu de temps, hein ?",
			COOKING_SHORT = "Oh mon gars ! Voilà que c'est prêt !",
			DONE = "Le dîner est servi !",
			EMPTY = "C'est un gâchis de la laisser vide comme ça.",
		},
		CORN = "J'aime bien ça, mais pas dans tous les plats.",
		CORN_COOKED = "Tous les bienfaits du maïs bien cuit.",
		CORN_SEEDS = "Je suis plus équarrisseur que laboureur.",
		CROW =
		{
			GENERIC = "Il prépare un sale coup. J'en suis sûr.",
			HELD = "Tu paieras pour tes crimes, corbeau !",
		},
		CUTGRASS = "Je dois être allergique à ça.",
		CUTREEDS = "Je vous fais le cri du canard des marais ?",
		CUTSTONE = "Une partie du bouclier canadien.",
		DEADLYFEAST = "L'odeur est pas terrible, hein ?",
		DEERCLOPS = "Ça c'est un gros élan à plumes !",
		DEERCLOPS_EYEBALL = "Et ça sert à quoi ?",
		DEPLETED_GRASS =
		{
			GENERIC = "Sûrement juste une touffe d'herbe.",
		},
		DEVTOOL = "Je ne fais pas de commentaire là-dessus.",
		DIRTPILE = "Hé ! Un indice !",
		DIVININGROD =
		{
			COLD = "C'est vraiment pas net vu d'ici.",
			GENERIC = "Je me demande si ça capte les matchs de hockey.",
			HOT = "C'est évident ! Y a un truc pas loin !",
			WARM = "Je crois que j'approche.",
			WARMER = "Waouh ! Attention là, mon pote.",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "On dirait qu'il faut y brancher quelque chose.",
			READY = "C'est prêt à être débloqué.",
			UNLOCKED = "Maintenant y a plus qu'à l'allumer.",
		},
		DIVININGRODSTART = "C'est un bâton bien curieux.",
		DRAGONFRUIT = "C'est la première fois que j'en vois.",
		DRAGONFRUIT_COOKED = "On dirait du sirop d'érable.",
		DRAGONFRUIT_SEEDS = "Je pourrais peut-être en faire pousser plus.",
		DRAGONPIE = "Presque aussi bon qu'une tarte au beurre !",
		DRUMSTICK = "Nourriture d'automne.",
		DRUMSTICK_COOKED = "Merci le dindon.",
		DUG_BERRYBUSH = "Faudrait tailler tout ça un peu.",
		DUG_GRASS = "J'en pleurerais.",
		DUG_MARSH_BUSH = "Je devrais planter ça.",
		DUG_SAPLING = "Mmmm... c'est tout fragile.",
		DURIAN = "Ça sent mauvais.",
		DURIAN_COOKED = "Ça pue encore plus.",
		DURIAN_SEEDS = "Pourquoi j'en ferais pousser d'autres ?",
		EARMUFFSHAT = "Par chez nous, ce truc-là sert plus à rien après l'automne.",
		EGGPLANT = "Je parie que les oiseaux ont un truc à voir là-dedans.",
		EGGPLANT_COOKED = "Aussi suspect qu'un oiseau.",
		EGGPLANT_SEEDS = "Hmmm... Je suis pas sûr.",
		EVERGREEN =
		{
			BURNING = "Non ! J'aurais pu le couper !",
			BURNT = "Quel gâchis.",
			CHOPPED = "Ahhhh !",
			GENERIC = "Il m'appelle !",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Désolation !",
			BURNT = "Je suis catastrophé !",
			CHOPPED = "Et un de plus !",
			GENERIC = "Lucy me pousserait à couper celui-ci.",
		},
		EYEPLANT = "Il devrait se mêler de ses affaires.",
		FARMPLOT =
		{
			GENERIC = "Je préfère les grosses plantes.",
			GROWING = "Ça va jamais pousser assez.",
			NEEDSFERTILIZER = "Je crois qu'il faudrait du crottin.",
		},
		FEATHERHAT = "Pas question que je porte cette... chose.",
		FEATHER_CROW = "Une grossière plume.",
		FEATHER_ROBIN = "Une plume dégoûtante.",
		FEATHER_ROBIN_WINTER = "Une plume idiote.",
		FEM_PUPPET = "Elle est piégée !",
		FIREFLIES =
		{
			GENERIC = "Ça me rappelle le parc provincial Algonquin.",
			HELD = "J'ai le soleil qui brille dans ma poche !",
		},
		FIREHOUND = "Molosse en feu !",
		FIREPIT =
		{
			EMBERS = "Je devrais aller lui couper du bois, hein ?",
			GENERIC = "Ça consomme du bois.",
			HIGH = "Je consomme le bois trop vite !",
			LOW = "On devrait trouver du bois dans les environs.",
			NORMAL = "Mmmm... ça sent le bois.",
			OUT = "Si seulement j'avais du bois.",
		},
		FIRESTAFF = "Je fais pas confiance à ces trucs magiques.",
		FISH = "On dirait de la morue.",
		FISHINGROD = "Je devrais aller faire un tour au lac.",
		FISHSTICKS = "Un repas parfaitement géométrique.",
		FISHTACOS = "Un petit goût de marée, hein ?",
		FISH_COOKED = "Si seulement j'avais des frites...",
		FLINT = "Ça pourrait faire la lame d'une hache.",
		FLOWER = "C'est beau.",
		FLOWERHAT = "Je trouve que ça va bien avec mes cheveux roux.",
		FLOWER_EVIL = "Il y a un truc pas normal avec cette fleur.",
		FOLIAGE = "On dirait de la salade.",
		FOOTBALLHAT = "J'aurai l'air d'un joueur de hockey ?",
		FROG =
		{
			DEAD = "Ex-grenouille.",
			GENERIC = "Aucune confiance pour les trucs qui hésitent entre l'air et l'eau.",
			SLEEPING = "Elle est fatiguée.",
		},
		FROGGLEBUNWICH = "On sent bien le goût de vase.",
		FROGLEGS = "Elles sautent encore !",
		FROGLEGS_COOKED = "Au moins elles ont arrêté de gigoter.",
		FRUITMEDLEY = "Avec du sirop !",
		GEARS = "J'ai jamais compris à quoi ça servait.",
		GHOST = "Hou ! Ha ha !",
		GOLDENAXE = "Presque aussi belle que Lucy.",
		GOLDENPICKAXE = "C'est joli mais ça coupe pas les arbres.",
		GOLDENPITCHFORK = "Je ne sais pas pourquoi j'ai fait ça.",
		GOLDENSHOVEL = "Il est temps d'aller trouver des trésors.",
		GOLDNUGGET = "On ne fait pas une table sans or.\nEnfin, peut-être que si, mais faudrait pas.",
		GRASS =
		{
			BARREN = "Faut que je lui balance de la crotte.",
			BURNING = "J'espère que ça va pas s'étendre aux arbres.",
			GENERIC = "On dirait du petit bois.",
			PICKED = "C'est tout riquiqui.",
		},
		GREEN_CAP = "J'ai mangé des trucs plus bizarres dans les bois.",
		GREEN_CAP_COOKED = "Je ne lui fais pas confiance.",
		GREEN_MUSHROOM =
		{
			GENERIC = "C'est un champignon vert",
			INGROUND = "Ils ont leur propre emploi du temps.",
			PICKED = "Je crois que je l'ai cassé.",
		},
		GUNPOWDER = "J'ai jamais aimé ça.",
		HAMBAT = "C'est gâcher de la bonne viande.",
		HAMMER = "On fait tous des erreurs, hein ?",
		HEALINGSALVE = "Médicament gluant.",
		HEATROCK =
		{
			COLD = "C'est froid, hein ?",
			GENERIC = "Par chez nous, on appelle ça des pierres de nuit.",
			HOT = "Je pourrais couper du bois tout l'hiver avec ça dans ma poche !",
			WARM = "Ça se réchauffe un peu.",
		},
		HOME = "Qui est là ?",
		HOMESIGN = "Rien d'impossible pour le bois !",
		HONEY = "Mmmmmm-mmmm. Du sirop d'abeille.",
		HONEYCOMB = "J'ai presque honte de prendre ça.",
		HONEYHAM = "Vraiment par gourmandise...",
		HONEYNUGGETS = "Un de mes plats préférés !",
		HORN = "Je ne sais pas si je dois mettre ça dans ma bouche.",
		HOUND = "Ils seraient bons pour tirer un traîneau.",
		HOUNDBONE = "C'est couvert de bave de chien, hein ?",
		HOUNDMOUND = "J'ai mieux à faire que m'occuper de ça.",
		ICEBOX = "Ahhh, ça me rappelle la maison.",
		ICEHOUND = "Des chiens de l'Arctique ?",
		INSANITYROCK =
		{
			ACTIVE = "Où est-ce qu'il est parti ?",
			INACTIVE = "Je ne sais pas comment bouger ça.",
		},
		JAMMYPRESERVES = "Je devrais trouver du beurre de cacahouète.",
		KABOBS = "Le bout de bois ajoute vraiment du goût.",
		KILLERBEE =
		{
			GENERIC = "Cette abeille n'a pas l'air très amical.",
			HELD = "Elle est pas ravie de sa situation.",
		},
		KNIGHT = "La police montée de Maxwell.",
		KOALEFANT_SUMMER = "Il a l'air bon.",
		KOALEFANT_WINTER = "C'est meilleur en hiver.",
		KRAMPUS = "Dégage, minable !",
		KRAMPUS_SACK = "J'ai honte de voler le sac de quelqu'un.",
		LEIF = "Je suis désolé pour tous ces arbres !",
		LEIF_SPARSE = "Je suis désolé pour tous ces arbres !",
		LIGHTNING_ROD =
		{
			CHARGED = "C'est beau comme une aurore boréale.",
			GENERIC = "Le ciel ne me tombera plus sur la tête.",
		},
		LITTLE_WALRUS = "Pourquoi ils sont si au sud ?",
		LIVINGLOG = "Je vais te garder, et je vais t'appeler Franck.",
		LOCKEDWES = "Qui est ce minable ?",
		LOG =
		{
			BURNING = "Oh non ! Le fruit de mon travail !",
			GENERIC = "Ça récompense le travail.",
		},
		LUREPLANT = "C'est de la viande ?",
		LUREPLANTBULB = "C'est chaud et bosselé.",
		MALE_PUPPET = "T'as besoin d'aide ?",
		MANDRAKE =
		{
			DEAD = "Désolé, ma petit dame.",
			GENERIC = "Elle m'observe.",
			PICKED = "Qu'est-ce que j'ai fait ?",
		},
		MANDRAKESOUP = "C'est une soupe qui fait dormir.",
		MANDRAKE_COOKED = "Désolé !",
		MARBLE = "On dirait l'assemblée nationale.",
		MARBLEPILLAR = "Sans doute construit par quelqu'un.",
		MARBLETREE = "Même Lucy peut pas couper ça.",
		MARSH_BUSH =
		{
			BURNING = "Pchiiit !",
			GENERIC = "C'est des ronces.",
			PICKED = "Ça valait le coup ?",
		},
		MARSH_PLANT = "Une plante.",
		MARSH_TREE =
		{
			BURNING = "Voilà ce qui arrive quand on a des épines !",
			BURNT = "Il l'a bien cherché.",
			CHOPPED = "Ce fut un rude combat, mais j'ai gagné.",
			GENERIC = "Les arbres sont pas censés se défendre !",
		},
		MAXWELL = "Pourquoi me déteste-t-il ?",
		MAXWELLHEAD = "Juste la tête, hein ?",
		MAXWELLLIGHT = "C'est surnaturel.",
		MAXWELLLOCK = "Où est la clé ?",
		MAXWELLTHRONE = "J'ai vu de plus belles chaises.",
		MEAT = "On dirait du caribou.",
		MEATBALLS = "Avec toutes les viandes !",
		MEATRACK =
		{
			DONE = "Ça a l'air prêt.",
			DRYING = "C'est comme regarder la viande sécher.",
			GENERIC = "C'est prêt... manque plus que la viande.",
		},
		MEAT_DRIED = "De la bouffe de survie.",
		MERM = "De quelle mer ignoble ce truc sort-il ?",
		MERMHEAD = "Ça sent le vieux chalutier.",
		MERMHOUSE = "Pas du plus pratique.",
		MINERHAT = "Comme pour aller à la mine.",
		MONSTERLASAGNA = "C'est de la bouffe de chat !",
		MONSTERMEAT = "J'ai pas assez faim pour ça.",
		MONSTERMEAT_DRIED = "Toujours pas envie de manger ça.",
		MOSQUITO =
		{
			GENERIC = "Il peut m'en sucer un litre !",
			HELD = "Et j'en fais quoi maintenant, hein ?",
		},
		MOSQUITOSACK = "Du sang dans un boyau, hein ?",
		MOUND =
		{
			DUG = "Désolé ! Ne viens pas me hanter !",
			GENERIC = "Je devrais sans doute pas toucher à ça.",
		},
		NIGHTLIGHT = "Qu'est-ce que c'est que cette obscurité ?",
		NIGHTMAREFUEL = "Tout ce qui m'effraie sous forme liquide, hein ?",
		
		NIGHTSWORD = "Les cauchemars peuvent blesser !",
		NITRE = "C'est avec ça qu'on fait la poudre.",
		ONEMANBAND = "Je te lâche pas de l'œil !",
		PANDORASCHEST = "Il y a quoi dans la boîte ?",
		PANFLUTE = "Je ne chante que pour Lucy.",
		PAPYRUS = "Je préfère couper qu'écrire.",
		PENGUIN = "Décolle ! Va rejoindre ton Grand Nord ! Beauté.",
		PERD = "Encore des oiseaux ! Pourquoi y a des oiseaux partout ?",
		PEROGIES = "J'appelle ça des « sacs à miam ».",
		PETALS = "Je me demande si Lucy aimerait ça.",
		PETALS_EVIL = "Leurs sales petites têtes lancent des regards noirs.",
		PICKAXE = "Presque une hache, mais pas tout à fait.",
		PIGGYBACK = "J'ai utilisé toutes les parties du cochon.",
		PIGHEAD = "Quelle bonne viande gâchée.",
		PIGHOUSE =
		{
			FULL = "C'est plein de bacon.",
			GENERIC = "Il suffirait d'un peu de ruban adhésif...",
			LIGHTSOUT = "Désolé ! Je voulais pas être indiscret !",
		},
		PIGKING = "Ce n'est pas mon roi.",
		PIGMAN =
		{
			FOLLOWER = "On est une équipe ! Ouais !",
			GENERIC = "Recule, bacon !",
			GUARD = "Celui-là il a l'air sérieux.",
			WEREPIG = "Qu'est-ce qui lui prend ?",
		},
		PIGSKIN = "Du bacon avec une queue.",
		PIGTORCH = "Comment ont-ils fait ça sans pouce ?",
		PINECONE = 
		{
		    GENERIC = "Je devrais planter ça pour couper l'arbre plus tard ! ",
		    PLANTED = "Et voilà un arbre !",
		},
		
		PITCHFORK = "Vraiment pas pour moi.",
		PLANTMEAT = "C'est dégoûtant !",
		PLANTMEAT_COOKED = "C'est pas bien meilleur cuit.",
		PLANT_NORMAL =
		{
			GENERIC = "Je me demande ce que ça sera.",
			GROWING = "Une plante dont on s'occupe ne pousse jamais.",
			READY = "C'est l'heure de la bouffe !",
		},
		POMEGRANATE = "C'est trop chic pour moi.",
		POMEGRANATE_COOKED = "Ça irait bien sur des crêpes.",
		POMEGRANATE_SEEDS = "Des graines, hein ?",
		POND = "Je sais nager !",
		POOP = "Pas de crotte dans le camp !",
		PUMPKIN = "J'aime pas manger les trucs qui poussent par terre.",
		PUMPKINCOOKIE = "Je vais pouvoir continuer à couper.",
		PUMPKIN_COOKED = "J'aime bien les tartes.",
		PUMPKIN_LANTERN = "On va éviter de trébucher.",
		PUMPKIN_SEEDS = "C'est des graines.",
		PURPLEGEM = "Tout peut se régler par un bon coup de hache.",
		RABBIT =
		{
			GENERIC = "Maudits écureuils terrestres...",
			HELD = "J'ai honte de le manger.",
		},
		RABBITHOLE = "Il doit pas y avoir d'arbres là-dedans.",
		RAINOMETER = "La pluie fait pousser les arbres.",
		RATATOUILLE = "C'est moi qui l'ai faite !",
		RAZOR = "Un vrai bûcheron ne se rase jamais.",
		REDGEM = "J'y vois briller la mort d'un millier d'arbres par les flammes.",
		RED_CAP = "Je ne sais pas trop...",
		RED_CAP_COOKED = "Seulement si j'ai vraiment faim.",
		RED_MUSHROOM =
		{
			GENERIC = "C'est un champignon rouge",
			INGROUND = "Ils ont leur propre emploi du temps.",
			PICKED = "Je crois que je l'ai cassé.",
		},
		REEDS =
		{
			BURNING = "Le feu me rend nerveux.",
			GENERIC = "Des roseaux",
			PICKED = "Ils repousseront.",
		},
        RUBBLE = "Du mobilier cassé.",
		RESEARCHLAB = "Je me méfie de tous ces trucs scientifiques.",
		RESEARCHLAB2 = "Ça devient bizarre.",
		RESEARCHLAB3 = "Ok, je crois que je commence à piger.",
		RESURRECTIONSTATUE = "Je suis pas mal en bois.",
		RESURRECTIONSTONE = "Je ne sais pas si je dois toucher ça.",
		ROBIN =
		{
			GENERIC = "Quel sale petit morveux.",
			HELD = "Te crois pas tiré d'affaire, le piaf.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Il doit être en migration !",
			HELD = "Il profite de ma chaleur.",
		},
		ROBOT_PUPPET = "Il est enfermé !",
		ROCK_LIGHT =
		{
			GENERIC = "Un feu sans bois ? Pas normal ça !",
			OUT = "On dirait que ça va casser.",
			LOW = "Il faut ajouter... du bois ?",
			NORMAL = "Un feu sans bois ? Pas normal ça !",
		},
		ROCK = "Je pourrais la casser si j'y mettais du mien.",
		ROCKS = "Pour les fois où le bois ne marche pas.",
        ROOK = "Hmm... la tour avance en ligne droite ? J'ai oublié.",
		ROPE = "Pratique pour attacher des trucs à d'autres trucs.",
		ROTTENEGG = "Un oiseau de moins. Bien.",
		SANITYROCK =
		{
			ACTIVE = "Il y a un truc qui déconne avec cette pierre, hein ?",
			INACTIVE = "C'est normal.",
		},
		SAPLING =
		{
			BURNING = "Ah ! Il n'avait aucune chance !",
			GENERIC = "Je veux le voir grandir pour pouvoir le couper.",
			PICKED = "Cueillir c'est moins rigolo que couper.",
		},
		SEEDS = "C'est pas des arbres.",
		SEEDS_COOKED = "On appelle ça la « surprise du bûcheron ».",
		SEWING_KIT = "Je m'en tire pas mal en couture.",
		SHOVEL = "Qui creuse un trou plante un arbre !",
		SILK = "Les araignées me foutent les chocottes.",
		SKELETON = "Désolé, l'ami.",
		SKULLCHEST = "C'est effrayant !",
		SMALLBIRD =
		{
			GENERIC = "Qu'est-ce que tu veux ?",
			HUNGRY = "Il veut quelque chose.",
			STARVING = "Je crois qu'il est affamé.",
		},
		SMALLMEAT = "C'était pas bien gros.",
		SMALLMEAT_DRIED = "Une petite bouchée.",
		SPEAR = "Il lui manque le poids d'une bonne vieille hache.",
		SPIDER =
		{
			GENERIC = "C'est la plus grosse araignée que j'aie jamais vue !",
			SLEEPING = "On fait doucement maintenant, hein ?",
		},
		SPIDERDEN = "Bon Dieu de cent mille ! Regardez-moi ça !",
		SPIDEREGGSACK = "Pourquoi j'irais transporter des trucs pareils ?",
		SPIDERGLAND = "À mon avis, c'est toxique.",
		SPIDERHAT = "Une vraie beauté, vous trouvez pas ?",
		SPIDERQUEEN = "T'es pas ma reine !",
		SPIDER_WARRIOR =
		{
			GENERIC = "Ils les font en jaune maintenant ?",
			SLEEPING = "J'ai pas envie de la réveiller.",
		},
		SPOILED_FOOD = "Ah... ça va plus être bon ça.",
		STATUEHARP = "T'as perdu la tête, hein ?",
		STATUEMAXWELL = "C'est un pauvre type, hein ?",
		STINGER = "Ouille ! C'est pointu.",
		STRAWHAT = "Ça me protégera du soleil.",
		STUFFEDEGGPLANT = "Je m'améliore en cuisine.",
		SUNKBOAT = "Du bois qui a connu des jours meilleurs.",
		SWEATERVEST = "C'est pas du tissu écossais, mais ça ira.",
		TAFFY = "Sucrement bon !",
		TALLBIRD = "Je ne fais pas plus confiance aux oiseaux qui ne volent pas.",
		TALLBIRDEGG = "Qu'est-ce qu'il y a là-dedans ?",
		TALLBIRDEGG_COOKED = "Ce n'est que justice.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Trop froid pour toi ?",
			GENERIC = "Il va éclore.",
			HOT = "Est-ce qu'il pleure ?",
			LONG = "Les oiseaux sont jamais à l'heure.",
			SHORT = "Ça va plus tarder.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Je devrais voler cet œuf pour lui donner une bonne leçon.",
			PICKED = "Il n'y a rien ici.",
		},
		TEENBIRD =
		{
			GENERIC = "En grandissant il deviendra aussi stupide que ses parents.",
			HUNGRY = "Ça t'arrive de pas avoir faim ?",
			STARVING = "Il est affamé à en devenir dingo.",
		},
		TELEBASE =
		{
			VALID = "Ça c'est prêt. Mais moi ?",
			GEMS = "Il faut des gemmes, hein ?",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Prêt à y aller, hein ?",
			GENERIC = "C'est... un truc magique, je crois.",
			LOCKED = "Il manque des trucs, hein ?",
			PARTIAL = "C'est presque prêt, hein ?",
		},
		TELEPORTATO_BOX = "Une boîte, hein ?",
		TELEPORTATO_CRANK = "Une manivelle, hein ?",
		TELEPORTATO_POTATO = "Une patate, hein ?",
		TELEPORTATO_RING = "Un anneau, hein ?",
		TELESTAFF = "Je me demande à quoi ça sert.",
		TENT = "Je suis habitué à dormir dans pire que ça.",
		TENTACLE = "Y a un calmar là-dessous ?",
		TENTACLESPIKE = "Elle tremble quand on l'agite.",
		TENTACLESPOTS = "C'est presque obscène !",
		TENTACLE_PILLAR = "C'est super gros !",
		TENTACLE_PILLAR_ARM = "C'est des bébés calmars ?",
		TENTACLE_GARDEN = "Ils me fatiguent ces calmars !",
		TOPHAT = "C'est trop chic.",
		TORCH = "Comme pour un dîner aux chandelles.",
		TRAP = "Alors c'est qui le plus malin ?",
		TRAP_TEETH = "Ça a l'air assez rudimentaire.",
		TRAP_TEETH_MAXWELL = "Il fait des coups bas, hein ?",
		TREASURECHEST = "Le bois c'est pratique. Regardez tout ce qu'on peut faire avec !",
		TREASURECHEST_TRAP = "Il y a un truc pas normal avec ce coffre.",

		TRINKET_1 = "Je jouais à ça quand j'étais petit.",
		TRINKET_10 = "Des ratiches pour les vieux.",
		TRINKET_11 = "La ferme, toi !",
		TRINKET_12 = "C'est tout flétri.",
		TRINKET_2 = "C'est pas un vrai, hein ?",
		TRINKET_3 = "Ça me rappelle une vieille histoire.",
		TRINKET_4 = "Me demandez pas...",
		TRINKET_5 = "Il lui manque un Canadarm, hein ?",
		TRINKET_6 = "Ils sont foutus, hein ?",
		TRINKET_7 = "Je pourrais jouer à ça pendant des heures !",
		TRINKET_8 = "Si je trouve une baignoire, je suis paré.",
		TRINKET_9 = "Je me suis cousu les vêtements, pas besoin de boutons.",
		TRUNKVEST_SUMMER = "Joli et aéré.",
		TRUNKVEST_WINTER = "Ça pourrait supporter les hivers de par chez nous, hein ?",
		TRUNK_COOKED = "Il ne doit plus rester de morve là-dedans.",
		TRUNK_SUMMER = "Pas très épais.",
		TRUNK_WINTER = "C'est épais et poilu.",
		TURF_CARPETFLOOR = "Trop classe pour moi.",
		TURF_CHECKERFLOOR = "Les citadins mettent ça dans les toilettes du jardin.",
		TURF_DIRT = "Juste de la terre, hein ?",
		TURF_FOREST = "Juste de la terre, hein ?",
		TURF_GRASS = "Juste de la terre, hein ?",
		TURF_MARSH = "Juste de la terre, hein ?",
		TURF_ROAD = "Juste de la terre, hein ?",
		TURF_ROCKY = "Juste de la terre, hein ?",
		TURF_SAVANNA = "Juste de la terre, hein ?",
		TURF_WOODFLOOR = "Un parquet de roi !",
		TURKEYDINNER = "C'est le retour de la dinde !",
		TWIGS = "Je devrais me faire une hachette pour ça.",
		UMBRELLA = "Avec ça j'aurai la barbe au sec, hein ?",
		UNIMPLEMENTED = "Ça n'a pas l'air sûr.",
		WAFFLES = "Je préfère les crêpes.",
		WALL_HAY = "Si j'éternue tout s'envole.",
		WALL_HAY_ITEM = "Si j'éternue tout s'envole.",
		WALL_STONE = "Bien à l'abri, hein ?",
		WALL_STONE_ITEM = "Bien à l'abri, hein ?",
		WALL_RUINS = "En ruines mais toujours sécurisant, hein ?",
		WALL_RUINS_ITEM = "C'est la ruine, hein ?",
		WALL_WOOD = "Ça, ça a de la gueule !",
		WALL_WOOD_ITEM = "Je trouve ça très beau !",
		WALRUS = "Oh non ! Encore les morses !",
		WALRUSHAT = "Mon grand-père avait le même.",
		WALRUS_CAMP =
		{
			EMPTY = "Un lieu à éviter cet hiver.",
			GENERIC = "Il y a des morses dans le coin, hein ?",
		},
		WALRUS_TUSK = "Il avait une carie, hein ?",
		WASPHIVE = "Pourquoi ces abeilles sont-elles en colère ?",
		WETGOOP = "J'ai déjà mangé pire !",
		WINTERHAT = "Une jolie toque, hein ?",
		WINTEROMETER = "Par chez nous, on les fait deux fois plus petits.",
		WORMHOLE =
		{
			GENERIC = "On dirait une paire de fesses !",
			OPEN = "Je suis pas sûr d'avoir envie de voir ça, hein ?",
		},
		WORMHOLE_LIMITED = "Ça pue un peu, hein ?",
		ACCOMPLISHMENT_SHRINE = "Un peu trop de frime à mon goût.",        		
		LIVINGTREE = "J'éprouve un sentiment partagé, hein ?",
		ICESTAFF = "Ça me rappelle la maison.",
	},
	DESCRIBE_GENERIC = "C'est quoi, hein ?",
	DESCRIBE_TOODARK = "Il fait noir, hein ?",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Il reste des bouts de bec, hein ?",
	},
}
