return {


	ACTIONFAIL_GENERIC = "Não consigo fazer nada certo.",
	ANNOUNCE_ADVENTUREFAIL = "Nem todas as mortes são semelhantes.",
	ANNOUNCE_BOOMERANG = "Oh! Isso foi carma.",
	ANNOUNCE_CHARLIE = "Demônio! Apareça!",
	ANNOUNCE_CHARLIE_ATTACK = "Fui atacada!",
	ANNOUNCE_COLD = "Estou tremendo até os ossos.",
	ANNOUNCE_CRAFTING_FAIL = "Não disponho dos materiais necessários.",
	ANNOUNCE_DUSK = "A escuridão logo chegará. Devo me preparar.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Hmm!",
		PAINFUL = "Isso não era comestível.",
		SPOILED = "Essa comida está chegando ao fim de sua vida útil.",
		STALE = "Isso estava velho?",
	},
	ANNOUNCE_ENTER_DARK = "A escuridão me engoliu.",
	ANNOUNCE_ENTER_LIGHT = "E fez-se a luz!",
	ANNOUNCE_HOUNDS = "Os cães estão uivando.",
	ANNOUNCE_HUNGRY = "Estou cheia de vazio.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Sinto a presença da fera por perto.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Essa trilha não leva a lugar algum.",
	ANNOUNCE_INV_FULL = "Não posso carregar mais.",
	ANNOUNCE_KNOCKEDOUT = "Nossa, essa doeu! Ainda assim, novamente acordo para a vida.",
	ANNOUNCE_NOHUNGERSLEEP = "Meu estômago está tão vazio quanto meu coração, não posso dormir agora.",
	ANNOUNCE_PECKED = "Você está testando minha paciência.",
	ANNOUNCE_QUAKE = "O solo treme. Será que ele vai me engolir inteiro?",
	ANNOUNCE_THORNS = "Ai! Cutuca, como eu.",
	ANNOUNCE_TORCH_OUT = "A escuridão voltou!",
	ANNOUNCE_TRAP_WENT_OFF = "Oh, céus!",
	ANNOUNCE_WORMHOLE = "Chego a este mundo mais uma vez.",
	ANNOUNCE_CANFIX = "\nAcho que posso arrumar isso!",
	ANNOUNCE_ACCOMPLISHMENT = "Tudo isso é passageiro.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Isso também será esquecido, algum dia.",
	BATTLECRY =
	{
		GENERIC = "A morte te encontrará!",
		PIG = "Deixe a morte te abraçar!",
		PREY = "Sofra, verme!",
		SPIDER = "Te enviarei para o outro lado!",
		SPIDER_WARRIOR = "Serei o seu fim!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Você viverá. Por enquanto.",
	},
	DESCRIBE =
	{
		WORMLIGHT = "Há um leve sussurro vindo dela.",
		WORM =
		{
		    PLANT = "Parece deslocada.",
		    DIRT = "Há algo aí?",
		    WORM = "Vem das profundezas.",
		},
		EEL = "Uma enguia.",
		EEL_COOKED = "Uma enguia cozida.",
		UNAGI = "Parece mais apetitoso assim.",
		EYETURRET = "Não sei por que me ajuda.",
		EYETURRET_ITEM = "Acho que preciso instalá-lo.",
		MINOTAURHORN = "Tudo que estou de uma fera que uma vez foi grande.",
		MINOTAURCHEST = "Nossa, que chifres magníficos você tem!",
		THULECITE_PIECES = "Fragmentos de um material poderoso.",
		POND_ALGAE = "Algas.",
		GREENSTAFF = "Posso ver o poder brilhar lá dentro.",
		POTTEDFERN = "Vive em uma gaiola.",

		THULECITE = "Sua presença marca o limite do desconhecido.",
		ARMORRUINS = "Um adiamento da morte.",
		RUINS_BAT = "Tenho o poder dos antigos em minhas mãos.",
		RUINSHAT = "Abigail teria adorado essa coroa.",
		NIGHTMARE_TIMEPIECE = 
		{
			CALM = "Não sei o que espreita nas sombras.",	
			WARN = "Posso sentir os olhos a espreitar.",	
			WAXING = "Eles se aproximam.", 
			STEADY = "Estou completamente cercada!", 
			WANING = "Acho que estão indo embora.", 
			DAWN = "Está quase terminando.", 
			NOMAGIC = "Estou sozinha.", 
		},
		BISHOP_NIGHTMARE = "O tempo venceu esta batalha.",
		ROOK_NIGHTMARE = "O tempo desgasta tudo.",
		KNIGHT_NIGHTMARE = "Outra batalha perdida para o tempo.",
		MINOTAUR = "Ele deve estar solitário, preso em uma gaiola tão pequena.",	
		SPIDER_DROPPER = "A escuridão drenou a cor de sua pele.",	
		NIGHTMARELIGHT = "Retira a energia das profundezas.",	
		RELIC = "Uma visão do passado.",	
		RUINS_RUBBLE = "Uma pilha de sonhos desfeitos.",	
		MULTITOOL_AXE_PICKAXE = "Um item com várias funções.",	
		GREENGEM = "Suas falhas são suas características mais belas.",
		ORANGESTAFF = "A cada vez que uso morro e renasço.",	
		YELLOWAMULET = "Um breve momento de luz em minha vida sombria.",	
		GREENAMULET = "Um clarão de brilho!",	

		SLURPER = "Ah, como é bom ser simples.",
		SLURPER_PELT = "Um saco vazio de fome.",
		ARMORSLURPER = "Um traje vivo, grudento e melancólico.",
		ORANGEAMULET = "Libertação temporária da escravidão.",
		YELLOWSTAFF = "A vara está tão distorcida quanto minha alma.",
		YELLOWGEM = "Me faz lembrar da minha mãe.",
		ORANGEGEM = "Essas coisas costumavam me deixar feliz.",
		TELEBASE = 
		{
			VALID = "A energia flui por ele.",
			GEMS = "O foco é tão sem vida.",
		},
		GEMSOCKET = 
		{
			VALID = "A pedra preciosa concentrou a força.",
			GEMS = "Parece vazio.",
		},
		STAFFLIGHT = "Quase posso divisar um pequeno sistema solar.",
		RESEARCHLAB4 = "Está só a um passo da loucura.",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="É bonita.",
			LONG = "Era a flor da minha irmã. Ela partiu para longe.",
			MEDIUM = "Posso sentir a presença da Abigail ficando mais forte.",
			SOON = "A Abigail está quase chegando!",
			HAUNTED_POCKET = "A Abigail está pronta para brincar, mas ela precisa de um pouco de espaço.",
			HAUNTED_GROUND = "Preciso mostrar à Abigail como brincar.",

		},

        ANCIENT_ALTAR = "Está repleto dos ecos dos mortos.",
        ANCIENT_ALTAR_BROKEN = "Ouço os ecos de dor da minha morte.",
        ANCIENT_STATUE = "Não é muito atraente.",

        LICHEN = "Como é que consegue crescer assim?",
		CUTLICHEN = "Fugaz, como a vida.",
		CAVE_BANANA = "As cascas parecem perigosas.",
		CAVE_BANANA_COOKED = "Amassadinho de banana quente é muito melhor.",
		CAVE_BANANA_TREE = "Pobre planta, presa longe do sol.",
		ROCKY = "Que imagens terríveis eles viram.",


		BLUEAMULET = "Um abraço frio familiar.",
		PURPLEAMULET = "Está secretando.",
		TELESTAFF = "Eu poderia fugir se fosse mais poderoso.",
		MONKEY = "Viver sem o fardo da inteligência deve ser bacana.",
		MONKEYBARREL = "Está sujo.",
		MONSTERLASAGNA = "Maldade cozida continua sendo maldade, mesmo na lasanha.",
		HOUNDSTOOTH="Retirado com raiz e tudo.",
		ARMORSNURTLESHELL="Agora posso me esconder dos meus problemas.",
		BAT="Uma criatura notívaga.",
		BATBAT = "Uma arma encantada. Empolgante!",
		BATWING="Se pelo menos eu pudesse voar para longe.",
		BATWING_COOKED="Uma vez eles tinham grande potencial.",
		BEDROLL_FURRY="Vou me enrolar nas peles peludas dos derrotados.",
		BUNNYMAN="Que vidas interiores atormentadas eles devem ter.",
		FLOWER_CAVE="Parece frágil.",
		FLOWER_CAVE_DOUBLE="Parece frágil.",
		FLOWER_CAVE_TRIPLE="Parece frágil.",
		GUANO="O subproduto inevitável da vida.",
		LANTERN="Ilumine o caminho sombriamente.",
		LIGHTBULB="Está sendo lentamente destruída pelo fogo.",
		MANRABBIT_TAIL="Contém essência borbulhante.",
		MUSHTREE_TALL  ="Que árvores estranhas.",
		MUSHTREE_MEDIUM="Parece um chapéu podre.",
		MUSHTREE_SMALL ="Será que gnominhos vivem aqui?",
		RABBITHOUSE="Não é tão comestível quanto parece.",
		SLURTLE="Está distraído perseguindo pedras.",
		SLURTLE_SHELLPIECES="Pedaços de sonhos desfeitos de tartareca.",
		SLURTLEHAT="Duvido que me ajude mais que ajudou o dono original.",
		SLURTLEHOLE="As tartarecas saem quando crescem demais.",
		SLURTLESLIME="Tremula com ansiedade viscosa.",
		SNURTLE="Esse tem uma concha maior.",
		SPIDER_HIDER="Uma aranha covarde.",
		SPIDER_SPITTER="Está mastigando algo.",
		SPIDERHOLE="Está infestado.",
		STALAGMITE="A terra rende seus espólios.",
		STALAGMITE_FULL="A terra rende seus espólios.",
		STALAGMITE_LOW="A terra rende seus espólios.",
		STALAGMITE_MED="A terra rende seus espólios.",
		STALAGMITE_TALL="A terra se eleva.",
		STALAGMITE_TALL_FULL="A terra se eleva.",
		STALAGMITE_TALL_LOW="A terra se eleva.",
		STALAGMITE_TALL_MED="A terra se eleva.",

		TURF_CARPETFLOOR = "Um pouco de solo.",
		TURF_CHECKERFLOOR = "Um pouco de solo.",
		TURF_DIRT = "Um pouco de solo.",
		TURF_FOREST = "Um pouco de solo.",
		TURF_GRASS = "Um pouco de solo.",
		TURF_MARSH = "Um pouco de solo.",
		TURF_ROAD = "Um pouco de solo.",
		TURF_ROCKY = "Um pouco de solo.",
		TURF_SAVANNA = "Um pouco de solo.",
		TURF_WOODFLOOR = "Um pouco de solo.",

		TURF_CAVE="Um pouco de solo.",
		TURF_FUNGUS="Um pouco de solo.",
		TURF_SINKHOLE="Um pouco de solo.",
		TURF_UNDERROCK="Um pouco de solo.",
		TURF_MUD="Um pouco de solo.",

		POWCAKE = "Eu teria que estar desesperada.",		
		CAVE_ENTRANCE = 
		{
			GENERIC="Alguém está tentando manter o submundo sob controle.",
			OPEN = "Um grande mal espreita sob a superfície.",
		},
        CAVE_EXIT = "A superfície chama.",
		BOOMERANG = "A morte volta para o remetente.",
		MAXWELLPHONOGRAPH = "Deveríamos fazer uma dança macabra?",
		ABIGAIL = "Essa é a minha irmã gêmea, Abigail.",
		PIGGUARD = "Esse porquinho parece mau.",
		ADVENTURE_PORTAL = "Que horror tecnológico é esse?",
		AMULET = "Fico pensando quem costumava ser o dono disso.",
		ANIMAL_TRACK = "Sinais da fera.",
		ARMORGRASS = "Só estou prolongando o inevitável.",
		ARMORMARBLE = "Detém as adagas que apunhalam meu coração.",
		ARMORWOOD = "Posso adiar o inevitável um pouco mais com isso.",
		ARMOR_SANITY = "Uma maneira perfeitamente segura de ficar louco.",
		ASH =
		{
			GENERIC = "Tudo o que restou depois de outro lindo incêndio.",
			REMAINS_EYE_BONE = "O osso ocular foi incinerado no teletransporte!",
			REMAINS_THINGIE = "Isso era alguma coisa antes de ser incendiada...",
		},
		AXE = "Um instrumento para a indústria e para assassinatos.",
		BABYBEEFALO = "Aproveite sua juventude. Logo você aprenderá os horrores do mundo real.",
		BACKPACK = "Uma mochila. Agora posso carregar ainda mais fardos.",
		BACONEGGS = "Um café da manhã balanceado para começar outro dia deprimente.",
		BANDAGE = "Vou acabar ferida novamente.",
		BASALT = "Tentar quebrar não teria sentido.",
		BEARDHAIR = "Isso é simplesmente sórdido.",
		BEDROLL_STRAW = "O sono nada mais é que uma morte temporária.",
		BEE =
		{
			GENERIC = "Eu ficaria longe dessa ferroadora.",
			HELD = "Fique calma, pequenina.",
		},
		BEEBOX =
		{
			GENERIC = "Elas trabalharão para que eu possa roubar.",
			READY = "Seus esforços foram produtivos!",
		},
		BEEFALO =
		{
			FOLLOWER = "Ele me segue até sua desgraça.",
			GENERIC = "Que pensamentos doentes devem se esconder atrás daqueles olhos.",
			NAKED = "Sua nudez agora está à mostra.",
			SLEEPING = "Que pesadelos ele deve estar tendo.",
		},
		BEEFALOHAT = "Devo cobrir minha cabeça.",
		BEEFALOWOOL = "Em algum lugar, um bífalo está nu e com frio.",
		BEEHAT = "Isso vai me proteger daqueles zumbidos felizes. Ah, e das ferroadas.",
		BEEHIVE = "Uma colmeia desgraçada de escória e pólen.",
		BEEMINE = "Eles ainda estão vivos lá dentro. Pobrezinhos!",
		BERRIES = "Essas bagas são ácidas.",
		BERRIES_COOKED = "Tem sabor mais balanceado, mas não vai durar muito.",
		BERRYBUSH =
		{
			BARREN = "Seco.",
			GENERIC = "Um lanchinho, quem sabe?",
			PICKED = "Vou precisar esperar.",
		},
		BIRDCAGE =
		{
			GENERIC = "Alguns de nós podem ver nossas jaulas.",
			OCCUPIED = "Ele está mais feliz agora.",
			SLEEPING = "Ele está morto? Não. Só dormindo.",
		},
		BIRDTRAP = "Gravetos e seda letais.",
		BIRD_EGG = "Tanta esperança, destruída.",
		BIRD_EGG_COOKED = "Nenhum pássaro sairá daí.",
		BISHOP = "Para o que ele reza?",
		BLOWDART_SLEEP = "Nem mesmo o sono longo, só um temporário.",
		BLOWDART_PIPE = "Assopro nesta ponta e a dor sai na outra.",
		BLOWDART_FIRE = "Devo incendiar o mundo?",
		BLUEGEM = "Azul como... ahm... um pássaro triste?",
		BLUEPRINT = "Seja lá quem desenhou isso, provavelmente já morreu.",
		BLUE_CAP = "Um fungo para conservar a monotonia.",
		BLUE_CAP_COOKED = "Tudo é maleável.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Mofado.",
			INGROUND = "Eu também me esconderia, se pudesse.",
			PICKED = "Colhido.",
		},
		BOARDS = "Ainda mais assustador para as árvores.",
		BONESTEW = "Eles morreram, daí coloquei todos num ensopado.",
		BUGNET = "Uma prisão para insetinhos.",
		BUSHHAT = "Oh, desaparecer.",
		BUTTER = "Não estava esperando isso.",
		BUTTERFLY =
		{
			GENERIC = "Bonita, mas de vida curta.",
			HELD = "Tenho seu fogo nas minhas mãos.",
		},
		BUTTERFLYWINGS = "A borboleta não pode mais voar.",
		BUTTERFLYMUFFIN = "Quero ver você sair dessa armadilha açucarada!",
		CAMPFIRE =
		{
			EMBERS = "A escuridão se aproxima.",
			GENERIC = "Talvez eu sobreviva essa noite!",
			HIGH = "Uma visão do inferno!",
			LOW = "O negrume se avizinha.",
			NORMAL = "É um fogo.",
			OUT = "Esse não é bom sinal.",
		},
		CANE = "Não conseguiria chegar a lugar nenhum mais rápido.",
		CARROT = "É uma cenoura.",
		CARROT_COOKED = "É uma cenoura que passou pela manopla de fogo.",
		CARROT_PLANTED = "É uma cenoura que está na terra.",
		CARROT_SEEDS = "Um dia, essa semente será uma cenoura.",
		CAVE_FERN = "Um toque de cor na escuridão.",
		CHARCOAL = "Está frio e morto, como meu coração.",
        CHESSJUNK1 = "Vida artificial fria e morta.",
        CHESSJUNK2 = "Vida artificial fria e morta.",
        CHESSJUNK3 = "Vida artificial fria e morta.",
		CHESTER = "Uma bola peluda de vazio.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Está olhando dentro da minha alma.",
			WAITING = "Está menos dormindo do que esperando...",
		},
		COOKEDMANDRAKE = "Foi uma boa morte. Ele será delicioso.",
		COOKEDMEAT = "O sangue foi todo cozido.",
		COOKEDMONSTERMEAT = "Maldade cozida continua sendo maldade.",
		COOKEDSMALLMEAT = "O fogo a purificou.",
		CORN = "O que é um pontinho amarelo... deixa pra lá!",
		CORN_COOKED = "Esse milho não suportou o calor.",
		CORN_SEEDS = "É, é uma semente.",
		CROW =
		{
			GENERIC = "Tira teu bico do meu coração!",
			HELD = "Ele é meu.",
		},
		CUTGRASS = "Gosto de matar coisas pequenas.",
		CUTREEDS = "Gosto de cortar coisas.",
		CUTSTONE = "O melhor para marcar sepulturas.",
		DEADLYFEAST = "Aqui, minha última refeição.",
		DEERCLOPS = "A morte encarnada!",
		DEERCLOPS_EYEBALL = "Que terrores ele deve ver.",
		DEPLETED_GRASS =
		{
			GENERIC = "Os restos de um tufo de grama.",
		},
		DIRTPILE = "Olha só, mais terra!",
		DIVININGROD =
		{
			COLD = "A fonte está distante.",
			GENERIC = "Está procurando para sempre sua metade perdida.",
			HOT = "Há algo maligno por aqui!",
			WARM = "A maldade está chegando mais perto.",
			WARMER = "Está muito perto agora.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "O que essa coisa ultramoderna faz?",
			READY = "Ainda precisa de uma chave grande.",
			UNLOCKED = "Vamos ver o que eu encontro!",
		},

		DRAGONFRUIT = "Isso nem tem forma de dragão.",
		DRAGONFRUIT_COOKED = "Ainda não é um dragão. Pelo menos está morta.",
		DRAGONFRUIT_SEEDS = "É uma semente. Não vai virar dragão.",
		DRAGONPIE = "Bem, pelo menos agora é uma torta.",
		DRUMSTICK = "Dá um som interessante e tem nutrientes!",
		DRUMSTICK_COOKED = "Menos cru, mais saborosa.",
		DUG_BERRYBUSH = "Gosto dela morta, mas devo plantar isso.",
		DUG_GRASS = "Gosto dela morta, mas devo plantar isso.",
		DUG_MARSH_BUSH = "Gosto dela morta, mas devo plantar isso.",
		DUG_SAPLING = "Gosto dela morta, mas devo plantar isso.",
		DURIAN = "Espinhoso e fedorento!",
		DURIAN_COOKED = "Menos espinhoso, mas mais fedido!",
		DURIAN_SEEDS = "Milagrosamente, as sementes não têm cheiro.",
		EARMUFFSHAT = "Suas pontas amargas me protegem do amargo frio.",
		EGGPLANT = "Praticamente uma erva-moura. Praticamente.",
		EGGPLANT_COOKED = "Cozinhar essa erva-moura tornou-a ainda menos mortífera.",
		EGGPLANT_SEEDS = "É uma semente de erva-moura.",
		EVERGREEN =
		{
			BURNING = "Está queimando forte.",
			BURNT = "Usado e terminado.",
			CHOPPED = "Tudo morre.",
			GENERIC = "A natureza é tão entediante.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Está queimando forte.",
			BURNT = "Usado e terminado.",
			CHOPPED = "Tudo morre.",
			GENERIC = "Seu ciclo de vida está terminando.",
		},
		EYEPLANT = "Eles seguem todos os desejos de seu mestre.",
		FARMPLOT =
		{
			GENERIC = "Que sementes devo plantar?",
			GROWING = "Gavinhas folhosas se lançam para fora do estrume.",
			NEEDSFERTILIZER = "Essa terra está fria e morta.",
		},
		FEATHERHAT = "Piu piu!",
		FEATHER_CROW = "Uma pensa de corvo, preta como a escuridão eterna.",
		FEATHER_ROBIN = "Uma pena de cardeal, vermelha como o sangue.",
		FEATHER_ROBIN_WINTER = "Uma pena de cardeal invernal, branca como a luz no fim do túnel.",
		FEM_PUPPET = "Me pergunto o que ela fez.",
		FIREFLIES =
		{
			GENERIC = "Um pequeno brilho no escuro.",
			HELD = "Luzes pequenas, afastadas do mundo fora do meu bolso.",
		},
		FIREHOUND = "Sua disposição é ardente.",
		FIREPIT =
		{
			EMBERS = "A escuridão se aproxima.",
			GENERIC = "Talvez eu sobreviva esta noite!",
			HIGH = "É a visão do inferno!",
			LOW = "O negrume se avizinha.",
			NORMAL = "É fogo.",
			OUT = "Não é bom sinal.",
		},
		FIRESTAFF = "Eu poderia colocar fogo no mundo.",
		FISH = "Eu estava lutando desesperadamente pela vida. Coitado!",
		FISHINGROD = "Com isso, posso arrancar os peixes de seu precioso lago.",
		FISHSTICKS = "Blocos perfeitamente moldados de peixe.",
		FISHTACOS = "Espero ter tirado todos os ossos.",
		FISH_COOKED = "Uma boa grelhada deixa firminho.",
		FLINT = "Uma pedra com aparência de lâmina.",
		FLOWER = "Elas são brilhantes e felizes. Eca.",
		FLOWERHAT = "Mas estou de luto...",
		FLOWER_EVIL = "Pelo menos elas são melhores que as outras flores.",
		FOLIAGE = "Me leva a Aarnivalkea.",
		FOOTBALLHAT = "Uma coisa morta para eu usar. Beleza.",
		FROG =
		{
			DEAD = "A vida é pequena e curta.",
			GENERIC = "Ele é pequeno e cheio de verrugas.",
			SLEEPING = "Ele está dormindo.",
		},
		FROGGLEBUNWICH = "Eu nunca pensei que pernas de sapo poderiam ter uma aparência tão boa.",
		FROGLEGS = "Arrancado direto de um sapo.",
		FROGLEGS_COOKED = "Definitivamente não se contorce mais.",
		FRUITMEDLEY = "Doce, azedinho e numa taça.",
		GEARS = "As entranhas de um demônio mecânico.",
		GHOST = "Ele ascendeu do túmulo!",
		GOLDENAXE = "Pelo menos posso matar árvores com estilo.",
		GOLDENPICKAXE = "Pelo menos posso destruir pedras com estilo.",
		GOLDENPITCHFORK = "Pelo menos posso preparar a terra com estilo.",
		GOLDENSHOVEL = "Pelo menos posso cavar com estilo.",
		GOLDNUGGET = "Vou levar comigo.",
		GRASS =
		{
			BARREN = "Precisa de cocô.",
			BURNING = "Tem um cheiro esquisito.",
			GENERIC = "É só um tufo de grama.",
			PICKED = "Acabou de ser morta.",
		},
		GREEN_CAP = "Esse cogumelo é decepcionantemente normal.",
		GREEN_CAP_COOKED = "Tudo é maleável.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Frio e úmido.",
			INGROUND = "Eu também me esconderia, se pudesse.",
			PICKED = "Colhido.",
		},
		GUNPOWDER = "O caminho que trilho é sombrio.",
		HAMBAT = "Morte gera morte.",
		HAMMER = "Com isso poderei destruir o mundo.",
		HEALINGSALVE = "A vida traz dor, dor traz vida.",
		HEATROCK =
		{
			COLD = "Apenas uma pedra moderadamente fria.",
			GENERIC = "Lá está ela, só ocupando espaço.",
			HOT = "As que queimam mais claro, queima mais rápido.",
			WARM = "Tão morna e sem vida quanto todas as outras pedras.",
		},
		HOMESIGN = "Uma marca é feita, mesmo que passageira.",
		HONEY = "Uma gostosura doce, mas fugaz.",
		HONEYCOMB = "Pedaços de colmeia, espalhados.",
		HONEYHAM = "Um molho doce para o abraço doce dessa criatura.",
		HONEYNUGGETS = "Um molho doce para o abraço doce dessa criatura.",
		HORN = "Parece que tem um bífalo preso lá dentro.",
		HOUND = "Afaste-se, lacaio do mal!",
		HOUNDBONE = "Os restos de uma fera maligna.",
		HOUNDMOUND = "Lar das criaturas mais malignas.",
		ICEBOX = "É tão fria quanto o meu coração.",
		ICEHOUND = "Ele tem um coração morto e gelado.",
		INSANITYROCK =
		{
			ACTIVE = "Está chamando meu nome.",
			INACTIVE = "É fria e sombria.",
		},
		JAMMYPRESERVES = "A quantidade perfeita de geleia.",
		KABOBS = "Carne, espetadas bem no centro.",
		KILLERBEE =
		{
			GENERIC = "Uma abelha com um coração frio e morto.",
			HELD = "Fique calma, pequenina.",
		},
		KNIGHT = "Um cavalo frio e sem alma.",
		KOALEFANT_SUMMER = "Uma fera da solidão.",
		KOALEFANT_WINTER = "Suporta os elementos cruéis.",
		KRAMPUS = "Oi, criatura imunda do submundo.",
		KRAMPUS_SACK = "Tem cheiro de bode.",
		LEIF = "Uma fera vagarosa.",
		LEIF_SPARSE = "Uma fera vagarosa.",
		LIGHTNING_ROD =
		{
			CHARGED = "Até mesmo essa energia terminará.",
			GENERIC = "Concentra a destruição.",
		},
		LITTLE_WALRUS = "O ciclo de violência continua.",
		LIVINGLOG = "Está gritando silenciosamente para sempre.",
		LOCKEDWES = "Aprisionado pelas estátuas de Maxwell, sempre vivo.",
		LOG = "Se as árvores pudessem falar, elas gritariam ao ver isso.",
		LUREPLANT = "Consome tudo.",
		LUREPLANTBULB = "A vida continua.",
		MALE_PUPPET = "Me pergunto o que ele fez.",
		MANDRAKE =
		{
			DEAD = "Pobre mandrágora!",
			GENERIC = "A poderosa mandrágora. Eu deveria colhê-la à noite.",
			PICKED = "Em frente, meus lacaios vegetais!",
		},
		MANDRAKESOUP = "Fervida até a morte",
		MARBLE = "Lisa e sem vida.",
		MARBLEPILLAR = "Nem mesmo pedras podem suportar a pressão constante da decadência.",
		MARBLETREE = "Não há mais sinais vitais nessa árvore gelada.",
		MARSH_BUSH =
		{
			BURNING = "Até mesmo espinhos queimam.",
			GENERIC = "Um arbusto que sempre dói.",
			PICKED = "Me doeu fazer isso.",
		},
		MARSH_PLANT = "É uma planta.",
		MARSH_TREE =
		{
			BURNING = "Está queimando.",
			BURNT = "Negro como meu coração.",
			CHOPPED = "Seus espinhos não a protegeram.",
			GENERIC = "Uma árvore que só conhece a morte.",
		},
		MAXWELL = "Sinto um estranho parentesco com ele.",
		MAXWELLHEAD = "Ele, sem dúvidas, tem um gostinho pelo drama.",
		MAXWELLLIGHT = "Que luz curiosa.",
		MAXWELLLOCK = "Parece mágico.",
		MAXWELLTHRONE = "Não é bem o que eu esperava.",
		MEAT = "Ainda está sangrenta.",
		MEATBALLS = "Carne em forma de bolas. Que demais!",
		MEATRACK =
		{
			DONE = "A secagem terminou.",
			DRYING = "Tremula a secar ao vento.",
			GENERIC = "Posso pendurar carne aqui.",
		},
		MEAT_DRIED = "Carne seca e deliciosa.",
		MERM = "Coisa do pântano horrenda!",
		MERMHEAD = "Zero dignidade.",
		MERMHOUSE = "O tempo a destruiu.",
		MINERHAT = "Luz sem necessidade de usar as mãos.",
		MONSTERMEAT = "A maldade a permeia.",
		MONSTERMEAT_DRIED = "Carne seca e com gosto estranho.",
		MOSQUITO =
		{
			GENERIC = "Tira a vida para poder viver.",
			HELD = "Posso sentir seu calor roubado.",
		},
		MOSQUITOSACK = "Um saco de sangue tirado de um mosquito. Adoro.",
		MOUND =
		{
			DUG = "A terra vomitou seus segredos.",
			GENERIC = "Algum dia vou me reunir com você.",
		},
		NIGHTLIGHT = "Misteriosa, mas mesmo assim, linda.",
		NIGHTMAREFUEL = "Com o sono dos sonhos isso aparece.",
		NIGHTSWORD = "Os sonhos têm um fim. Um fim violento.",
		NITRE = "Aqui jaz a insensatez da humanidade.",
		ONEMANBAND = "Eu tinha muito prazer em instrumentos como esse.",
		PANDORASCHEST = "A vida é um jogo de azar.",
		PANFLUTE = "A música é a janela para a minha alma vazia!",
		PAPYRUS = "Para documentar minha dor.",
		PENGUIN = "Todo arrumado, mas onde ir?",
		PERD = "Pássaro estúpido! Fique longe das minhas bagas!",
		PEROGIES = "Uma adorável dose de nutrientes.",
		PETALS = "Destruí algo lindo.",
		PETALS_EVIL = "Elas estão pintadas com as cores da minha alma.",
		PICKAXE = "Para que eu possa penetrar a própria terra.",
		PIGGYBACK = "Eles são mais úteis quando mortos.",
		PIGHEAD = "Mate o porco. Derrame seu sangue.",
		PIGHOUSE =
		{
			FULL = "Espero que esteja se divertindo.",
			GENERIC = "Pelo menos estão confortáveis.",
			LIGHTSOUT = "Agora estou completamente sozinha.",
		},
		PIGKING = "Viva bem enquanto pode, vossa majestade.",
		PIGMAN =
		{
			DEAD = "Ele está melhor agora.",
			FOLLOWER = "Ainda me sinto sozinha.",
			GENERIC = "Eles são tão reservados.",
			GUARD = "Bem Orwelliano.",
			WEREPIG = "Uma criatura notívaga.",
		},
		PIGSKIN = "A pele de um porco que uma vez viveu.",
		PIGTORCH = "Desbravando a escuridão.",
		PINECONE = 
		{
		    GENERIC = "Uma vidinha, envolta em frágil morte.",
		    PLANTED = "Uma árvore crescerá em breve.",
		},
		PITCHFORK = "Que ferramenta demoníaca!",
		PLANTMEAT = "Tem um cheiro podre.",
		PLANTMEAT_COOKED = "É só um pouquinho mais atraente.",
		PLANT_NORMAL =
		{
			GENERIC = "Uma planta comestível.",
			GROWING = "Continue crescendo. Eu espero.",
			READY = "Está pronta para a colheita.",
		},
		POMEGRANATE = "Tantas partes vermelhas suculentas para devorar e esmagar!",
		POMEGRANATE_COOKED = "Quente, mas não menos melequenta.",
		POMEGRANATE_SEEDS = "Estava esperando mais sementes do que isso dessa coisa.",
		POND = "Ofélia? Você está aí embaixo?",
		POOP = "A vida é sangue e isso.",
		PUMPKIN = "É tão grande quanto o buraco do meu coração.",
		PUMPKINCOOKIE = "Eu mesmo fiz!",
		PUMPKIN_COOKED = "Encolheu um pouco com o calor. Gosto disso.",
		PUMPKIN_LANTERN = "Você não é tão assustador.",
		PUMPKIN_SEEDS = "É uma semente. Uhu.",
		PURPLEGEM = "Roxo como uma... coisa roxa.",
		RABBIT =
		{
			GENERIC = "Ele está vagando sem rumo, sem consciência de seu destino.",
			HELD = "Ele está seguro em meus braços.",
		},
		RABBITHOLE = "Sou muito grande para passar por aqui.",
		RAINOMETER = "Mede a nebulosidade. Gosto quando está lúgubre.",
		RATATOUILLE = "Um monte de vegetais cozidos. Impressionante.",
		RAZOR = "Isso serve apenas para raspar.",
		REDGEM = "Vermelho como o sangue do meu coração.",
		RED_CAP = "Um cogumelo atrás do meu próprio coração.",
		RED_CAP_COOKED = "Tudo é maleável.",
		RED_MUSHROOM =
		{
			GENERIC = "Úmido.",
			INGROUND = "Eu também me esconderia, se pudesse.",
			PICKED = "Colhido.",
		},
		REEDS =
		{
			BURNING = "Logos virarão cinzas.",
			GENERIC = "É só um monte de juncos.",
			PICKED = "Recolhidos.",
		},
        RELIC = 
        {
            GENERIC = "Um resto de um mundo ancestral.",
            BROKEN = "Pedaços quebrados de pedra.",
        },
        RUINS_RUBBLE = "Uma pilha de sonhos desfeitos.",
		RESEARCHLAB = "Vou aprender coisas indescritíveis.",
		RESEARCHLAB2 = "Vou aprender coisas indescritíveis.",
		RESEARCHLAB3 = "Aprendi coisas indescritíveis.",
		RESURRECTIONSTATUE = "Estou apenas adiando o inevitável.",
		RESURRECTIONSTONE = "Uma área desnecessária.",
		ROBIN =
		{
			GENERIC = "Isso significa que a primavera está chegando? Espero que não.",
			HELD = "Ele gosta de ficar preso no meu bolso.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "A vida no deserto gelado.",
			HELD = "É tão macio. É meu inimigo.",
		},
		ROBOT_PUPPET = "Fico pensando o que ele fez.",
		ROCK_LIGHT =
		{
			GENERIC = "Uma incrustação sobre o poço de lava.",
			OUT = "Parece inofensivo.",
			LOW = "As sombras se avizinham.",
			NORMAL = "A lava está pegando fogo.",
		},
		ROCK = "Nem mesmo isso é permanente.",
		ROCKS = "Algumas pedrinhas.",
        ROOK = "Uma torre? Ou é um castelo?",
		ROPE = "Essa seria a saída fácil desse lugar.",
		ROTTENEGG = "O destino de todas as coisas.",
		SANITYROCK =
		{
			ACTIVE = "Está me chamando.",
			INACTIVE = "Até mesmo esse obelisco me deixou.",
		},
		SAPLING =
		{
			BURNING = "Entregue às chamas.",
			GENERIC = "Está tentando crescer.",
			PICKED = "Quem sabe na próxima, muda.",
		},
		SEEDS = "Vida, ou pelo menos a promessa de uma.",
		SEEDS_COOKED = "Tostei-as até a morte.",
		SEWING_KIT = "Outro implemento para adiar o inevitável declínio.",
		SHOVEL = "Que segredos terríveis descobrirei?",
		SILK = "Tão escorregadio e refinado.",
		SKELETON = "Invejo sua fuga.",
		SKULLCHEST = "Conterá meus lembretes sobre a morte.",
		SMALLBIRD =
		{
			GENERIC = "Olá, pequenino.",
			HUNGRY = "Você está vazio por dentro?",
			STARVING = "Um buraco negro do qual as sementes nunca voltam.",
		},
		SMALLMEAT = "Tem cheiro de medinho.",
		SMALLMEAT_DRIED = "Carne seca e deliciosa.",
		SPEAR = "Me tornei a destruidora de mundos.",
		SPIDER =
		{
			DEAD = "Nos encontraremos de novo algum dia.",
			GENERIC = "Uma criatura notívaga.",
			SLEEPING = "O mal está dormido.",
		},
		SPIDERDEN = "Um ninho de sujeira e vilania.",
		SPIDEREGGSACK = "Um pacotinho cheio de morte e destruição.",
		SPIDERGLAND = "Mesmo na morte, essa fera causa dor.",
		SPIDERHAT = "Hora de fitar o abismo.",
		SPIDERQUEEN = "Ela é magnificente em sua horribilidade.",
		SPIDER_WARRIOR =
		{
			DEAD = "Oh, brava guerreira.",
			GENERIC = "Uma guerreira da noite!",
			SLEEPING = "Devo ter cuidado.",
		},
		SPOILED_FOOD = "Tudo vira lixo, no fim das contas.",
		STATUEHARP = "Talvez essas estátuas me façam companhia.",
		STATUEMAXWELL = "Ele me trouxe até aqui.",
		STINGER = "Afiado e mortal.",
		STRAWHAT = "Devo cobrir minha cabeça.",
		STUFFEDEGGPLANT = "Uma erva-moura. Provavelmente não está cheia de veneno.",
		SUNKBOAT = "Um truque cruel.",
		SWEATERVEST = "Posso vestir peças de coisas mortas em forma de colete!",
		TAFFY = "Nunca imaginei que pudesse fazer algo tão doce.",
		TALLBIRD = "Livre dos grilhões do céu.",
		TALLBIRDEGG = "Com tanto potencial.",
		TALLBIRDEGG_COOKED = "Todas as possibilidades se foram. Com bacon fica gostosinho.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Resfriado pela escuridão.",
			GENERIC = "Um ser pequeno e frágil, lutando em direção à luz.",
			HOT = "Não pode suportar o calor.",
			LONG = "Uma vida que começa mais cedo é uma vida que termina mais cedo.",
			SHORT = "Em breve, agora.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Esse ovo representa uma nova vida. Ugh.",
			PICKED = "O ninho está vazio. Desocupado. Deserto. Um vácuo.",
		},
		TEENBIRD =
		{
			GENERIC = "Você também vai me deixar?",
			HUNGRY = "Todos tentamos preencher o vazio.",
			STARVING = "Sua verdadeira natureza se revela!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Tenho certeza que o próximo mundo será ainda mais horrível!",
			GENERIC = "Nada de bom pode vir disso.",
			LOCKED = "Ainda está trancada.",
			PARTIAL = "Está semi-pronto, ou semi-destruído?",
		},
		TELEPORTATO_BOX = "Contém uma centelha vital.",
		TELEPORTATO_CRANK = "Parece complicado.",
		TELEPORTATO_POTATO = "Que criação horrenda!",
		TELEPORTATO_RING = "Não tem pontas afiadas.",
		TENT = "O sono nada mais é que uma prévia da morte.",
		TENTACLE = "Longo, fino e perigoso!",
		TENTACLESPOTS = "É melhor não falar desses.",
		TENTACLESPIKE = "Afiado, viscoso e perigoso.",
        TENTACLE_PILLAR = "Então é isso que rola lá embaixo.",
        TENTACLE_PILLAR_ARM = "Bebês!",
        TENTACLE_GARDEN = "Este é diferente.",
		TOPHAT = "Devo cobrir minha cabeça.",
		TORCH = "Um pequeno baluarte contra a noite.",
		TRAP = "Uma simples grama se tornou mortífera.",
		TRAP_TEETH = "Uma surpresa maligna do submundo.",
		TRAP_TEETH_MAXWELL = "A morte quando eu menos esperava.",
		TREASURECHEST = "O qual conterá meus ganhos.",
		TRINKET_1 = "Perfeitamente disforme.",
		TRINKET_10 = "Outra boca para alimentar.",
		TRINKET_11 = "Robô sortudo, nunca teve uma alma.",
		TRINKET_12 = "Não é mais tão viscoso, né?",
		TRINKET_2 = "É falsa. Apenas uma tentação, como a morte.",
		TRINKET_3 = "Se pelo menos facas resolvessem mais dos meus problemas...",
		TRINKET_4 = "Eu carregaria isso até o fim do mundo.",
		TRINKET_5 = "Eu voaria reto assim até o sol, se pelo menos ele fosse maior.",
		TRINKET_6 = "Uma vez viveram com eletricidade, mas chegaram ao fim.",
		TRINKET_7 = "Apenas um simples jogo.",
		TRINKET_8 = "Eu queria poder tomar um banho.",
		TRINKET_9 = "Botões errados para uma vida errada.",
		TRUNKVEST_SUMMER = "Pele para vestir sobre a minha pele.",
		TRUNKVEST_WINTER = "Pode aquecer meu corpo, mas e o meu espírito?",
		TRUNK_COOKED = "Está ainda pior agora.",
		TRUNK_SUMMER = "Eu teria preferido orelhas.",
		TRUNK_WINTER = "Separado de seu único amigo.",
		TURKEYDINNER = "Que está gorgolejando agora?",
		TWIGS = "Retirados do solo antes de seu auge.",
		UMBRELLA = "As nuvens choram.",
		WAFFLES = "Definitivamente são waffles.",
		WALL_HAY = "Essa é uma mera sugestão de defesa.",
		WALL_HAY_ITEM = "Seu valor defensivo é questionável.",
		WALL_STONE = "O que me protegerá do que há lá dentro?",
		WALL_STONE_ITEM = "Elas não vão proteger dos demônios internos.",
		WALL_RUINS = "Elas não protegeram os antigos, protegeram?",
		WALL_RUINS_ITEM = "As próprias pedras são assombradas?",
		WALL_WOOD = "Agora posso evitar o inevitável.",
		WALL_WOOD_ITEM = "Conjunto de toras.",
		WALRUS = "Um velho dos mares.",
		WALRUSHAT = "Que pensamentos febris ocorreram embaixo dele?",
		WALRUS_CAMP =
		{
			EMPTY = "Se eles não estiverem lá, onde estarão?",
			GENERIC = "Temo que essa casa não seja feliz.",
		},
		WALRUS_TUSK = "Tritura-lo-ei.",
		WASPHIVE = "Eles se escondem em sua fortaleza de ódio.",
		WETGOOP = "Uma grande cagada, como a vida.",
		WINTERHAT = "Ajuda a protelar o frio que se aproxima.",
		WINTEROMETER = "Por que tenho a sensação de que está medindo minha mortalidade?",
		WORMHOLE =
		{
			GENERIC = "A vida nem sempre faz sentido.",
			OPEN = "Não importa o que consuma, nunca está satisfeito.",
		},
		ACCOMPLISHMENT_SHRINE = "Nunca dei muita bola para metáforas.",
		LIVINGTREE = "Não morre nunca?",
		ICESTAFF = "Um cajado para congelar.",
	},
	DESCRIBE_GENERIC = "É imencionável.",
	DESCRIBE_TOODARK = "A escuridão! É escura demais!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Poupei-lhe o tormento de viver.",
	},
}
