return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Ich warte, bis er nicht hinguckt.",
			GENERIC = "Das kann nicht rasiert werden.",
			NOBITS = "Ich kann nicht rasieren, wenn da keine Haare sind.",
		},
	},
	ACTIONFAIL_GENERIC = "Ich bin nicht mächtig genug, um das zu tun.",
	
	ANNOUNCE_NORMALTOMIGHTY="ICH BIN MÄCHTIG!",
	ANNOUNCE_NORMALTOWIMPY="Ich fühle mich nicht so gut.",
	ANNOUNCE_WIMPYTONORMAL="Wolfgang geht es besser.",
	ANNOUNCE_MIGHTYTONORMAL="Ich muss meinen mächtigen Bauch mal wieder füllen.",


	ANNOUNCE_ADVENTUREFAIL = "Nächstes Mal werde ich stärker sein!",
	ANNOUNCE_BOOMERANG = "Au! Wieso tust du mir weh, Wurfstock?",
	ANNOUNCE_CHARLIE = "Zeig dich!",
	ANNOUNCE_CHARLIE_ATTACK = "Oh! Es hat mich!",
	ANNOUNCE_COLD = "Brrrrrrr! Das ist kalt!",
	ANNOUNCE_CRAFTING_FAIL = "Ich muss noch weitere Dinge sammeln, um das zu tun.",
	ANNOUNCE_DUSK = "Die unheimliche Zeit naht.",
	ANNOUNCE_EAT =
	{
		GENERIC = "MJAM!",
		PAINFUL = "Ooooh. Ich habe Bauchschmerzen.",
		SPOILED = "Ihhh! Schmeckt nach Abfall.",
		STALE = "Schmeckt lustig.",
	},
	ANNOUNCE_ENTER_DARK = "Ich kann nichts sehen! Ich habe Angst!",
	ANNOUNCE_ENTER_LIGHT = "Ich kann wieder etwas sehen.",
	ANNOUNCE_HOUNDS = "Ich kann Hundewelpen hören.",
	ANNOUNCE_HUNGRY = "Mein mächtiger Bauch ist leer!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Tier in der Nähe!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Keine Tiere da.",
	ANNOUNCE_INV_FULL = "Meine mächtigen Arme können nichts mehr tragen.",
	ANNOUNCE_PECKED = "Womit habe ich das verdient?",
	ANNOUNCE_TORCH_OUT = "Oh nein! Das Licht ist aus.",
	ANNOUNCE_WORMHOLE = "Es sorgt dafür, dass ich mich lebendig fühle!",
	ANNOUNCE_TRAP_WENT_OFF = "Das überrascht Wolfgang nicht.",
    ANNOUNCE_QUAKE = "Der Boden bebt. Wolfgang hasst bebenden Boden.",
    ANNOUNCE_NODANGERSLEEP = "Wolfgang bevorzugt lieber den Kampf als zu schlafen.",
    ANNOUNCE_UNIMPLEMENTED = "Es ist nicht fertig.",
    ANNOUNCE_NOHUNGERSLEEP = "Wolfgang schläft nie mit leerem Magen.",
    ANNOUNCE_FREEDOM = "Ich bin frei! Starke Freiheit!",
    ANNOUNCE_RESEARCH = "Das sind viele Informationen.",
    ANNOUNCE_NO_TRAP = "Leicht wie Gewichte.",
    ANNOUNCE_HIGHRESEARCH = "Vielleicht zu viele Informationen.",
    ANNOUNCE_THORNS = "Stachlig ist nicht fair!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Es ist gruselig in der Höhle.",
    ANNOUNCE_BEES = "Bienen! Böse, stechende Insektenmänner! ",
    ANNOUNCE_KNOCKEDOUT = "Uh, Wolfgang muss am Kopf getroffen worden sein.",
    ANNOUNCE_LOWRESEARCH = "Zu wenig Informationen.",
    ANNOUNCE_DEERCLOPS = "Hört sich an, als ob ein schwerer, starker Mann kommt.",
    ANNOUNCE_MOSQUITOS = "Wolfgang braucht sein Blut. Verschwindet, ihr saugenden Käfer!",
    ANNOUNCE_NODAYSLEEP = "Es ist zu hell, um zu schlafen.",
	ANNOUNCE_CANFIX = "\nMächtiges Gehirn könnte dies besser machen!",
	ANNOUNCE_ACCOMPLISHMENT= "Ich mache große Dinge mit winzigem Pfeil!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Ich habe den winzigen Pfeil besiegt!",	
	BATTLECRY =
	{
		GENERIC = "Ich werde dich schlagen!",
		PIG = "Es tut mir leid, mein Freund!",
		PREY = "Stampf! Stampf! Stampf!",
		SPIDER = "Stirb', böser Käfer!",
		SPIDER_WARRIOR = "Ich bin stärker als du, gruselig Käfer!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Ha! Ich gewinne!",
		PIG = "Ich vergebe dir, Schweinemann.",
		PREY = "Lauf nur weiter!",
		SPIDER = "Sie ist vor mir weggerannt.",
		SPIDER_WARRIOR = "Sie weiß wohl, dass ich stärker bin.",
	},
	DESCRIBE =
	{
		WORMLIGHT = "Schönes Licht.",
		WORM =
		{
		    PLANT = "Schönes Licht.",
		    DIRT = "Bewegt sich der Dreck?",
		    WORM = "Das habe ich nicht erwartet!",
		},
		EEL = "Ich muss das Kochen!",
		EEL_COOKED = "Das habe ich gekocht.",
		UNAGI = "Essen macht mich stark!",
		EYETURRET = "Dieser mächtige Aufbau wird mir beim kämpfen helfen!",
		EYETURRET_ITEM = "Ich muss es hinstellen.",
		MINOTAURHORN = "Trophäe eines mächtigen Feindes.",
		MINOTAURCHEST = "Kiste mit starken Hörnern.",
		THULECITE_PIECES = "Ich kann sie gegeneinander schmettern, um größere Stücke zu machen!",
		POND_ALGAE = "Die Pflanze ist so klein. Das ist lustig.",
		GREENSTAFF = "Dieser Stock hat einen grünen Edelstein. ",
		POTTEDFERN = "Das macht mich glücklich.",

		SLURPER = "Nein! Nein! Halte dich von mir fern!",
		SLURPER_PELT = "Es bewegt sich noch!",
		ARMORSLURPER = "Es bewegt sich mit meinen vielen Muskeln!",
		ORANGEAMULET = "Ich kann es um den Hals tragen.",
		YELLOWSTAFF = "Schöner Edelstein",
		YELLOWGEM = "Hübscher Stein.",
		ORANGEGEM = "Hübscher Stein.",
		TELEBASE = 
		{
			VALID = "Ein gutes Zeichen, wenn es leuchtet.",
			GEMS = "Glaube nicht, dass das funktioniert.",
		},
		GEMSOCKET = 
		{
			VALID = "Der hübsche Stein schwebt jetzt.",
			GEMS = "ist leer",
		},
		STAFFLIGHT = "Es schmerzt, wenn man ihn anfasst.",
		RESEARCHLAB4 = "Ein Hut, nicht nur für den Kopf.",

        ANCIENT_ALTAR =
        {
        	WORKING = "Ein fieser, gruseliger Altar.",
        	BROKEN = "Ein zerstörter Altar.",
        },  
        ANCIENT_ALTAR_BROKEN = "Ein zerstörter Altar.",

        ANCIENT_STATUE = "Hässlich, hässlich, hässlich.",

        LICHEN = "Eine Flechte.",
		CUTLICHEN = "Schmeckt schrecklich.",

        CAVE_BANANA = "Lecker!",
        CAVE_BANANA_COOKED = "Ist warm und lecker!",
        CAVE_BANANA_TREE = "Hallo, Affenbrotbaum.",
        ROCKY = "Er ist mächtig. Genau wie ich!",

        BLUEAMULET = "Würde gute Eiswürfel machen!",
		PURPLEAMULET = "Dieses Amulett... macht Wolfgang Angst.",
		TELESTAFF = "Das macht mir Kopfschmerzen.",
		MINERHAT = "Lampe für den Kopf.",
		MONKEY = "Hässlicher Affenmann!",
		MONKEYBARREL = "Dieses... Ding. Es riecht nicht so gut.",

		HOUNDSTOOTH="Welpenzahn!",
		ARMORSNURTLESHELL="Klebrig im Inneren.",
		BAT="Fliegendes Mäuschen!",
		BATBAT = "Diese Keule belustigt mich.",
		BATWING="Haarig und widerlich.",
		BATWING_COOKED="Crespo",
		BEDROLL_FURRY="So bequem!",
		BUNNYMAN="Hallo Kaninchen!",
		FLOWER_CAVE="Eine Lichtpflanze.",
		FLOWER_CAVE_DOUBLE="Eine Lichtpflanze.",
		FLOWER_CAVE_TRIPLE="Eine Lichtpflanze.",
		GUANO="Noch mehr Mist.",
		LANTERN="Schützt mich vor dem Dunkeln.",
		LIGHTBULB="Ist das was zu essen?",
		MANRABBIT_TAIL="Bauschig!",
		MUSHTREE_TALL  ="Der Pilzbau ist groß.",
		MUSHTREE_MEDIUM="Pilziger Busch.",
		MUSHTREE_SMALL ="Pilziger Busch.",
		RABBITHOUSE="Ich höre ein Mampfen im Inneren.",
		SLURTLE="Ha! Du bist so langsam!",
		SLURTLE_SHELLPIECES="Das ist kaputt!",
		SLURTLEHAT="Schützt meinen Kopf.",
		SLURTLEHOLE="Ein Loch voll mit Schnecken.",
		SLURTLESLIME="Schnodder!",
		SNURTLE="Spiralförmig!",
		SPIDER_HIDER="Eine ängstliche Spinne.",
		SPIDER_SPITTER="Bam! Bam!",
		SPIDERHOLE="Überall Spinnen.",
		STALAGMITE="Spitz.",
		STALAGMITE_FULL="Spitz.",
		STALAGMITE_LOW="Spitz.",
		STALAGMITE_MED="Spitz.",
		STALAGMITE_TALL="Stein, auf dem Weg zur Decke.",
		STALAGMITE_TALL_FULL="Stein, auf dem Weg zur Decke.",
		STALAGMITE_TALL_LOW="Stein, auf dem Weg zur Decke.",
		STALAGMITE_TALL_MED="Stein, auf dem Weg zur Decke.",

		TURF_CARPETFLOOR = "Fußweg.",
		TURF_CHECKERFLOOR = "Fußweg.",
		TURF_DIRT = "Fußweg.",
		TURF_FOREST = "Fußweg.",
		TURF_GRASS = "Fußweg.",
		TURF_MARSH = "Fußweg.",
		TURF_ROAD = "Fußweg.",
		TURF_ROCKY = "Fußweg.",
		TURF_SAVANNA = "Fußweg.",
		TURF_WOODFLOOR = "Fußweg.",

		TURF_CAVE="Fußweg.",
		TURF_FUNGUS="Fußweg.",
		TURF_SINKHOLE="Fußweg.",
		TURF_UNDERROCK="Fußweg.",
		TURF_MUD="Fußweg.",

		POWCAKE = "Ist aus Nichts gemacht.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Selbst ich bin nicht so mächtig.",
            OPEN = "Die Welt hat einen Bauchnabel!",
        },
        CAVE_EXIT = "Es ist dunkel und gruselig hier unten.",

		MAXWELLPHONOGRAPH = "Ein Kasten, der singt.",
		BOOMERANG = "BOOM-erang! Ha!",
		PIGGUARD = "Ein böses Schweinchen.",
		ADVENTURE_PORTAL = "Ein Eingang wie ein Mund! Sag 'Ahhhh'!",
		AMULET = "Das ist sehr hübsch.",
		ANIMAL_TRACK = "Das Tier ging in diese Richtung.",
		ARMORGRASS = "Kratzig.",
		ARMORMARBLE = "Aus Steinen werden Muskeln.",
		ARMORWOOD = "Fast so hart wie mein Bauch!",
		ARMOR_SANITY = "Das ist, wie das Tragen von kleinen gruseligen Fetzen.",
		ASH =
		{
			GENERIC = "Das Skelett eines Feuers.",
			REMAINS_EYE_BONE = "Die verbrannten Überreste von einem Augenknochen.",
			REMAINS_THINGIE = "Die verbrannten Überreste von etwas, was nun tot ist...",
		},
		AXE = "Hack!",
		BABYBEEFALO = "Eine kleine Fellkuh!",
		BACKPACK = "Um mehr Sachen zu tragen.",
		BACONEGGS = "Die Nahrung hat Eigelb. Und Fleisch! Macht stärker!",
		BANDAGE = "Ich kann mich wieder gut machen!",
		BASALT = "Das ist sogar stärker als ich!",
		BEARDHAIR = "Widerlich. Die sind nicht aus meinem Gesicht.",
		BEDROLL_STRAW = "Schlafenszeit!",
		BEE =
		{
			GENERIC = "Ist fett und sieht wütend aus.",
			HELD = "Ist sicher in meiner Tasche.",
		},
		BEEBOX =
		{
			GENERIC = "Bienen!",
			READY = "Bereit zum Ernten!",
		},
		BEEFALO =
		{
			FOLLOWER = "Die haarige Kuh folgt mir!",
			GENERIC = "Eine haarige Kuh!",
			NAKED = "Die haarige Kuh hat keine Haare mehr.",
			SLEEPING = "Die haarige Kuh schläft.",
		},
		BEEFALOHAT = "Guter Hut!",
		BEEFALOWOOL = "Ich mache Sachen aus Kuh mit Haaren.",
		BEEHAT = "Ein Hut, der mich vor Bienen schützt.",
		BEEHIVE = "Oh, Bienenstock!",
		BEEMINE = "Ein Ball, voll mit zornigen Bienen.",
		BEEMINE_MAXWELL = "Ein Ball voll mit zornigen Moskitos.",
		BERRIES = "Lecker!",
		BERRIES_COOKED = "Schmeckt noch besser!",
		BERRYBUSH =
		{
			BARREN = "Ich muss es düngen.",
			GENERIC = "Voll von essbaren Bällchen.",
			PICKED = "Der essbare Teil ist weg.",
		},
		BIRDCAGE =
		{
			GENERIC = "Ein Zuhause für meine Vögelchen.",
			OCCUPIED = "Hallo Vögelchen.",
			SLEEPING = "Ich sollte leise sein.",
		},
		BIRDTRAP = "Ich werde einen Vogel fangen!",
		BIRD_EGG = "Armes Vögelchen.",
		BIRD_EGG_COOKED = "MJAM!",
		BISHOP = "Pater!",
		BLOWDART_FIRE = "Vorsicht, Wolfgang.",
		BLOWDART_SLEEP = "Pfeil, um Gegner einzuschläfern.",
		BLOWDART_PIPE = "Pfeil, der Gegnern Schmerzen zufügt.",
		BLUEGEM = "Hübscher Stein.",
		BLUEPRINT = "Schöne Bilder.",
		BLUE_CAP = "Gut für mich... glaube ich.",
		BLUE_CAP_COOKED = "Ist nicht dasselbe.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Pilzig.",
			INGROUND = "Der Pilz versteckt sich.",
			PICKED = "Ich habe den Pilz mitgenommen.",
		},
		BOARDS = "Ich zerbreche den Holzklotz, um daraus Bretter zu machen!",
		BONESTEW = "Ein Topf, voll mit starkem Fleisch.",
		BUGNET = "Zum Fangen von Krabbeltieren.",
		BUSHHAT = "Ich bin so hinterhältig!",
		BUTTER = "Das ist butterartig und schmeckt nach Insekten.",
		BUTTERFLY =
		{
			GENERIC = "Ein hübscher Letterschming.",
			HELD = "Mein Haustier!",
		},
		BUTTERFLYMUFFIN = "Wolfgang weiß nichts über Käfer-Muffins. Ich werde einfach probieren.",
		BUTTERFLYWINGS = "Kein Flug ohne Flügel!",
		CAMPFIRE =
		{
			EMBERS = "Die Dunkelheit kommt!",
			GENERIC = "Lebt wohl, dunkle Zeiten!",
			HIGH = "Zu viel Feuer.",
			LOW = "Das Feuer ist nicht heiß genug.",
			NORMAL = "Ein gutes Feuer!",
			OUT = "Oh. Es ist ausgegangen.",
		},
		CANE = "Ich kann nicht gleichzeitig gehen UND Dinge schlagen.",
		CARROT = "Nahrung... glaube ich.",
		CARROT_COOKED = "Immer noch kein Fleisch, auch nach dem Kochen nicht.",
		CARROT_PLANTED = "Versteckt sie sich?",
		CARROT_SEEDS = "Samen sind zu klein.",
		CAVE_FERN = "Hübsche Pflanze.",
		CHARCOAL = "Ein kleiner toter Baum.",
        CHESSJUNK1 = "Metallschrott.",
        CHESSJUNK2 = "Metallschrott.",
        CHESSJUNK3 = "Metallschrott.",
		CHESTER = "Seltsame Box mit Beinen.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Das ist ein Augenknochen. Verbunden mit Chester.",
			WAITING = "Jetzt schläft grade.",
		},
		COOKEDMEAT = "Mit Feuer hab ich das Fleisch gut gemacht!",
		COOKEDMONSTERMEAT = "Ich will das immer noch nicht essen.",
		COOKEDSMALLMEAT = "Ist gekocht noch kleiner.",
		COOKPOT =
		{
			COOKING_LONG = "Das braucht eine lange Zeit.",
			COOKING_SHORT = "Ist fast gekocht.",
			DONE = "Zeit zu Essen!",
			EMPTY = "Ein leerer Topf bringt Wolfgang dazu, an Hunger zu denken.",
		},
		CORN = "Mais. Was soll man da erwarten?",
		CORN_COOKED = "Pop pop pop! Haha, lustiger Mais!",
		CORN_SEEDS = "Samen, um Mais anzubauen.",
		CROW =
		{
			GENERIC = "Ich mag keine Vögel.",
			HELD = "Sie ist krächzend.",
		},
		CUTGRASS = "Ein Stapel Gras.",
		CUTREEDS = "Ich habe einen Büschel Schilf hergestellt.",
		CUTSTONE = "Ich zerquetsche Stein, um Ziegel zu machen.",
		DEADLYFEAST = "Sieht aus wie böse Nahrung.",
		DEERCLOPS = "Er sieht mächtiger aus, als ich.",
		DEERCLOPS_EYEBALL = "Pfui! Pfui! Pfui!",
		DEPLETED_GRASS =
		{
			GENERIC = "Ein Büschel Gras.",
		},
		DIRTPILE = "Dreckiger Dreck.",
		DIVININGROD =
		{
			COLD = "Der Automat spricht.",
			GENERIC = "Das ist irgendein Automat.",
			HOT = "Der Automat macht mir Angst!",
			WARM = "Ha! So ist es gut, Automat!",
			WARMER = "Der Automat wird zornig...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Was hat das für einen Nutzen?",
			READY = "Das Stab-Ding braucht einen Schlüssel, um zu starten.",
			UNLOCKED = "Das Stab-Ding ist an!",
		},
		DIVININGRODSTART = "Ein lustiges Stab-Ding.",
		DRAGONFRUIT = "Das ist eine lustig aussehende Frucht.",
		DRAGONFRUIT_COOKED = "Sieht selbst gekocht noch lustig aus.",
		DRAGONFRUIT_SEEDS = "Das muss ich benutzen, um eine lustig aussehende Frucht zu pflanzen.",
		DRAGONPIE = "Kuchen aus lustiger, roten Frucht.",
		DRUMSTICK = "Beinfleisch, um meine Beine stärker zu machen.",
		DRUMSTICK_COOKED = "Vom Knochen zu essen ist gut.",
		DUG_BERRYBUSH = "Es ist einsam und allein.",
		DUG_GRASS = "Es ist einsam und allein.",
		DUG_MARSH_BUSH = "Es ist einsam und allein.",
		DUG_SAPLING = "Es ist einsam und allein.",
		DURIAN = "Eine dornige, riechende Frucht.",
		DURIAN_COOKED = "Jetzt ist es eine warme, stinkende Frucht.",
		DURIAN_SEEDS = "Winzige, dornige Baby-Pflanze.",
		EARMUFFSHAT = "Jetzt sehe ich wie ein kleines Häschen aus.",
		EARMUFFHAT = "Jetzt sehe ich wie ein kleines Häschen aus.",
		EGGPLANT = "Das ist kein Ei!",
		EGGPLANT_COOKED = "Kein Eigelb! Das Eigelb ist das Beste!",
		EGGPLANT_SEEDS = "Winzig kleine Eierpflanze.",
		STUFFEDEGGPLANT = "Ich habe Eigelb aus anderer Nahrung erschaffen.",
		EVERGREEN =
		{
			BURNING = "Ich hab ihn kaputt gemacht.",
			BURNT = "Ist jetzt klein und zerbrochen.",
			CHOPPED = "Ha! Es gibt mich noch!",
			GENERIC = "Hallo, Baum!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Ich hab ihn kaputt gemacht.",
			BURNT = "Ist jetzt klein und zerbrochen.",
			CHOPPED = "Ha! Es gibt mich noch!",
			GENERIC = "Kopf hoch, Baum!",
		},
		EYEPLANT = "Sie sind nicht, was sie zu sein scheinen.",
		FARMPLOT =
		{
			GENERIC = "Ich werde mächtige Früchte anbauen.",
			GROWING = "Wachst, meine kleinen Freunde! Wachst!",
			NEEDSFERTILIZER = "Der Dreck ist nicht dreckig genug, um die Pflanzen wachsen zu lassen.",
		},
		FEATHERHAT = "Ein dämlicher Hut aus Federn. Ist Wolfgang jetzt ein Vogel?",
		FEATHER_CROW = "Eine Feder von einem schwarzen Vogel.",
		FEATHER_ROBIN = "Eine Feder von einem roten Vogel.",
		FEATHER_ROBIN_WINTER = "Feder vom weißen Vogel.",
		FEM_PUPPET = "Der gruselige Stuhl hat sie erschreckt!",
		FIREFLIES =
		{
			GENERIC = "Leuchtend!",
			HELD = "Meine Tasche leuchtet!",
		},
		FIREHOUND = "Wau!",
		FIREPIT =
		{
			EMBERS = "Die Dunkelheit kommt!",
			GENERIC = "Lebt wohl, dunkle Zeiten!",
			HIGH = "Zu viel Feuer.",
			LOW = "Das Feuer ist nicht heiß genug.",
			NORMAL = "Ein gutes Feuer!",
			OUT = "Oh. Es ist ausgegangen.",
		},
		FIRESTAFF = "Ein Stab, um Feuer zu machen. Vorsichtig, Wolfgang.",
		FISH = "Fischartig.",
		FISHINGROD = "Um Fische aus dem Teich zu bekommen.",
		FISHSTICKS = "Haha, lustiger Name.",
		FISHTACOS = "Wolfgang hofft, dass es nicht zu scharf für Wolfgang ist.",
		FISH_COOKED = "Fleisch aus dem Wasser macht Wolfgang trotzdem stark.",
		FLINT = "Ein Stein, nur spitzer.",
		FLOWER = "Sie ist wirklich schön.",
		FLOWERHAT = "Das ist so hübsch.",
		FLOWER_EVIL = "Das ist keine Kartoffel.",
		FOLIAGE = "Ich habe die schöne Pflanze getötet.",
		FOOTBALLHELMET = "Ein Helm für den Zweikampf.",
		FROG =
		{
			DEAD = "Ist eine Delikatesse in meinem Land.",
			GENERIC = "Hey, kleiner Frosch!",
			SLEEPING = "Schläft.",
		},
		FROGLEGS = "In meinem Land ist das eine Delikatesse!",
		FROGGLEBUNWICH = "Ein Sandwich mit leckerem Fleisch vom Bein.",
		FROGLEGS_COOKED = "Schmeckt weitestgehend nach Hühnchen.",
		FRUITMEDLEY = "Ein Becher mit klitzekleinen Früchten.",
		GEARS = "Haha! Wer hat hier nun mehr Muskeln?",
		GHOST = "Aaaaaaaaaaah!",
		GOLDENAXE = "Die schicke Axt ist viel besser zum Hacken.",
		GOLDENPICKAXE = "Schicke Spitzhacke zerschmettert besser.",
		GOLDENPITCHFORK = "Schicke Forke. Gut um Boden auszustechen.",
		GOLDENSHOVEL = "Die schicke Schaufel macht gute Löcher.",
		GOLDNUGGET = "Geld ist für winzige Leute!",
		GRASS =
		{
			BARREN = "Es braucht Dünger.",
			BURNING = "Nicht gut!",
			GENERIC = "Das ist Gras.",
			PICKED = "Das Gras wurde besiegt.",
		},
		GREEN_CAP = "Für den Salat. Igitt.",
		GREEN_CAP_COOKED = "Ist nicht dasselbe.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Pilzig.",
			INGROUND = "Der Pilz versteckt sich.",
			PICKED = "Ich habe den Pilz mitgenommen.",
		},
		GUNPOWDER = "Knallpfeffer!",
		HAMBAT = "Immer noch gut.",
		HAMMER = "Die Sichel fehlt.",
		HEALINGSALVE = "Es sorgt dafür, dass ich mich lebendig fühle!",
		HEATROCK =
		{
			COLD = "Der Stein ist ein bisschen kalt.",
			GENERIC = "Dieser runde Stein ist wie mein Kopf!",
			HOT = "Warm genug für Wolfgang!",
			WARM = "Ein ganz normaler Stein.",
		},
		HOMESIGN = "Keine Zeit, um Schilder zu lesen!",
		HONEY = "Lecker!",
		HONEYCOMB = "Da hat die Biene gelebt.",
		HONEYHAM = "Großes Fleisch mit Süßem ist gutes Fleisch.",
		HONEYNUGGETS = "Süßes Fleisch ist gutes Fleisch.",
		HORN = "Das Horn einer haarigen Kuh. Wolfgang hört die haarige Kuh.",
		HOUND = "Wuff!",
		HOUNDMOUND = "Ein Haus aus Knochen.",
		HOUNDBONE = "Der schwächliche Wauwau war nicht stark genug.",
		ICEBOX = "Kiste, die kalt macht!",
		ICEHOUND = "Wauwau!",
		INSANITYROCK =
		{
			ACTIVE = "Das ist nach meinem Geschmack.",
			INACTIVE = "Ha. Ich habe das winzige Hindernis überwunden.",
		},
		JAMMYPRESERVES = "Das quillt aus meiner Hand wie ein zerquetschter Feind.",
		KABOBS = "Vom Stock zu essen ist gut.",
		KILLERBEE =
		{
			GENERIC = "Zornige Biene!",
			HELD = "Meine zornige Biene!",
		},
		KNIGHT = "Pferdchen!",
		KOALEFANT_SUMMER = "Fleisch mit Nase.",
		KOALEFANT_WINTER = "So weich, ich will ihn zerquetschen.",
		KRAMPUS = "Gruseliger Ziegenmann! Lauf!",
		KRAMPUS_SACK = "Ich habe den Sack vom Ziegenmann.",
		LEIF = "Holzmann!",
		LEIF_SPARSE = "Holzmann!",
		LIGHTNING_ROD =
		{
			CHARGED = "Ooooh, Funken!",
			GENERIC = "Ein Draht zum Himmel.",
		},
		LITTLE_WALRUS = "Du meinst, du bist stärker wie alter Mann?",
		LIVINGLOG = "Gruseliger Gesichtsklotz.",
		LOCKEDWES = "Mickrig Mann ist von Statuen-Männern gefangen.",
		LOG = "So dick wie mein Arm.",
		LUREPLANT = "Du kannst Wolfgang nicht täuschen!",
		LUREPLANTBULB = "Haha! Wer ist jetzt verflixt?",
		MALE_PUPPET = "Der gruselige Stuhl hat ihn erschreckt!",
		MANDRAKE =
		{
			DEAD = "Der kleine Pflanzenmann ist gestorben.",
			GENERIC = "Eine seltsame Pflanze.",
			PICKED = "Der kleine Pflanzenmann ist mein Freund!",
		},
		COOKEDMANDRAKE = "Ist der kleine Pflanzenmann essbar?",
		MANDRAKESOUP = "Kleiner Pflanzenmann, um Suppe zu machen.",
		MARBLE = "Ich kann es hochheben!",
		MARBLEPILLAR = "Ist zu schwer zum Heben.",
		MARBLETREE = "Versuche nicht, den Baum zu schlagen.",
		MARSH_BUSH =
		{
			BURNING = "Uh. Stachliges Feuer.",
			GENERIC = "Ist dornig.",
			PICKED = "Dornen tun weh.",
		},
		MARSH_PLANT = "Ist 'ne Pflanze.",
		MARSH_TREE =
		{
			BURNING = "Ich verbrenne die Stacheln!",
			BURNT = "Jetzt ist es stachlig und schwarz.",
			CHOPPED = "Ich hacke die Stacheln ab!",
			GENERIC = "Stachlig.",
		},
		MAXWELL = "Ein eleganter Anzug passt nicht zu meinen Muskeln!",
		MAXWELLHEAD = "Ein drei Meter großer Kopf.",
		MAXWELLLIGHT = "Gruseliges Licht!",
		MAXWELLLOCK = "Gruselig!",
		MAXWELLTHRONE = "Gruseliger Stuhl.",
		MEAT = "Fleisch macht mich stark!",
		MEATBALLS = "Fleischbällchen machen mich stark!",
		MEATRACK =
		{
			DONE = "Lecker, lederartiges Fleisch!",
			DRYING = "Trockne, Fleisch-Ding! Trockne!",
			GENERIC = "Ich kann Fleisch trocknen.",
		},
		MEAT_DRIED = "Sieht aus wie Leder, schmeckt wie Fleisch.",
		MERM = "Fischartiger Mann!",
		MERMHEAD = "Was für ein hübscher Teufel!",
		MERMHOUSE = "Das Haus war nicht stark genug.",
		MONSTERLASAGNA = "Schmeckt wie Nudeln mit Haaren und Fleisch.",
		MONSTERMEAT = "Sieht nicht wie etwas zum Essen aus.",
		MONSTERMEAT_DRIED = "Seht aus wie Leder, schmeckt wie Leder.",
		MOSQUITO =
		{
			GENERIC = "Ein Blutsauger!",
			HELD = "Kein Blut mehr für dich!",
		},
		MOSQUITOSACK = "Ziemlich vollgesaugt.",
		MOUND =
		{
			DUG = "Es tut mir leid, ihr toten Leute.",
			GENERIC = "Gruselig! Ist vermutlich voll mit Knochen!",
		},
		NIGHTLIGHT = "Ein seltsames Leuchten.",
		NIGHTMAREFUEL = "Gruseliges Zeug.",
		NIGHTSWORD = "Echt? Nicht echt? Auf jeden Fall scharf!",
		NITRE = "Stein, nur schwerer.",
		ONEMANBAND = "Groß und laut. Das mag ich!",
		PANDORASCHEST = "Schicker Kasten!",
		PANFLUTE = "Ich kann ein Volkslied spielen.",
		PAPYRUS = "Ist wie Papier",
		PENGUIN = "Vogel mit einem echt lustigen Gang!",
		PERD = "Der dumme Vogel nimmt die ganzen Beeren.",
		PEROGIES = "Wolfgang liebt Piroggen.",
		PETALS = "Das riecht angenehm.",
		PETALS_EVIL = "Die sorgen dafür, dass mein Hirn schmerzt.",
		PICKAXE = "Hack!",
		PIGGYBACK = "Packehuck!",
		PIGHEAD = "Wieso so ein langes Gesicht?",
		PIGHOUSE =
		{
			FULL = "He, komm schon raus, Schweinemann!",
			GENERIC = "Die Tür ist zu klein für mich.",
			LIGHTSOUT = "Wo ist er hin?",
		},
		PIGKING = "Ha! Gute Leute!",
		PIGMAN =
		{
			DEAD = "Nein! Das Schwein ist tot!",
			FOLLOWER = "Ist jetzt mein Freund!",
			GENERIC = "Hallo Schwein. Wie geht es dir?",
			GUARD = "Ob er auch trainiert?",
			WEREPIG = "Zorniges Schweinchen.",
		},
		PIGSKIN = "Ein langer Hintern! Ha ha, Wolfgang ist so lustig.",
		PIGTORCH = "Wie macht man Feuer?",
		PINECONE = 
		{
		    GENERIC = "Ich könnte diesen Baumsamen mit meinen Händen zerquetschen!",
		    PLANTED = "Ich werde bald ein Baum sein.",
		},
		PITCHFORK = "Erinnert mich an meine Kindheit.",
		PLANTMEAT = "Was ist das? Fleisch für Babys?",
		PLANTMEAT_COOKED = "Jetzt ist es etwas besser.",
		PLANT_NORMAL =
		{
			GENERIC = "Blättrig!",
			GROWING = "Sie wächst noch.",
			READY = "Mmmm. Jetzt ist es lecker.",
		},
		POMEGRANATE = "Sieht aus wie das Hirn eines Besserwissers.",
		POMEGRANATE_COOKED = "Hahaha! Ein gekochtes Gehirn. Jetzt ist es nicht mehr so schlau.",
		POMEGRANATE_SEEDS = "Ein Stück Gehirn?",
		POND = "Alles nass.",
		POOP = "Stinkend!",
		PUMPKIN = "So groß wie der Kopf eines schwachen Mannes! Nicht wie der von Wolfgang.",
		PUMPKINCOOKIE = "Leckerer Keks.",
		PUMPKIN_COOKED = "Ich kann deinen Kopf kochen, mickriger Mann! Ich bin der stärkste Wolfgang.",
		PUMPKIN_LANTERN = "Jetzt ist es wirklich ein Kopf! Wolfgang hat Angst!",
		PUMPKIN_SEEDS = "Daraus wächst was zu essen. So groß wie ein kümmerlicher Kopf.",
		PURPLEGEM = "Ein noch hübscherer Stein.",
		RABBIT =
		{
			GENERIC = "Winziges Kaninchen! Versteck dich vor mir!",
			HELD = "Er ist mein Freund.",
		},
		RABBITHOLE = "Du kannst dich nicht ewig verstecken, hoppelndes Fleisch.",
		RAINOMETER = "Plitsch! Platsch!",
		RATATOUILLE = "Was zum essen. Irgendwie.",
		RAZOR = "Meine Haut ist zu stark für Haare!",
		REDGEM = "Hübscher Stein.",
		RED_CAP = "Oh! Das ist schön und funkelnd.",
		RED_CAP_COOKED = "Ist nicht dasselbe.",
		RED_MUSHROOM =
		{
			GENERIC = "Pilzig.",
			INGROUND = "Der Pilz versteckt sich.",
			PICKED = "Ich habe den Pilz mitgenommen.",
		},
		REEDS =
		{
			BURNING = "Nicht gut!",
			GENERIC = "Wassergras.",
			PICKED = "Ich habe das Schilf besiegt.",
		},
        RELIC = 
        {
            GENERIC = "Zeug fürs Haus.",
            BROKEN = "Völlig zerstört!",
        },
        RUBBLE = "Überreste von einem kaputten Haus.",
		RESEARCHLAB = "Ich weiß nicht, was ich von Wissenschaft halten soll.",
		RESEARCHLAB2 = "Ich weiß nicht, was ich von Wissenschaft halten soll.",
		RESEARCHLAB3 = "Was hat Wolfgang getan?",
		RESURRECTIONSTATUE = "Ich werde nicht sterben.",
		RESURRECTIONSTONE = "Einstiegsstein.",
		ROBIN =
		{
			GENERIC = "Hübsches rotes Vögelein.",
			HELD = "Glückliches Vogel in Tasche.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Ein ganz weißer Vogel.",
			HELD = "Ein flauschiger Vogel.",
		},
		ROBOT_PUPPET = "Der gruselige Stuhl hat sie erschreckt!",
		ROCK_LIGHT =
		{
			GENERIC = "Ein Haufen verkrusteter Steine.",
			OUT = "Ha! Ein weiteres Ding zum Zerschmettern.",
			LOW = "Die Lava ist die Kühlung.",
			NORMAL = "Flüssiges Feuer!",
        },
		ROCK = "Hart! So wie ich!",
		ROCKS = "Das ist ein Stein. Weiß doch jeder.",
        ROOK = "Turm schlägt Königin.",
		ROPE = "Stark! So wie ich!",
		ROTTENEGG = "Stinkt!",
		SANITYROCK =
		{
			ACTIVE = "Ist schön!",
			INACTIVE = "Versteckt sich unter der Erde.",
		},
		SAPLING =
		{
			BURNING = "Ups.",
			GENERIC = "Winziger Baum! Ich bin stärker als du!",
			PICKED = "Ha! Ha! Ha! Baum ist schlapp!",
		},
		SEEDS = "Zu klein zum essen.",
		SEEDS_COOKED = "Das Feuer hat sie größer gemacht. Jetzt kann ich sie essen.",
		SEWING_KIT = "Das ist spitz!",
		SHOVEL = "Dreckiger Löffel!",
		SILK = "Das ist schick!",
		SKELETON = "Nicht genug Muskeln.",
		SKULLCHEST = "Dieser Mann hatte großen Kopf!",
		SMALLBIRD =
		{
			GENERIC = "Ist sehr kleiner Vogel.",
			HUNGRY = "Kleiner Vogel ist hungrig.",
			STARVING = "Kleiner Vogel wird verhungern.",
		},
		SMALLMEAT = "Ich brauch mehr Fleisch!",
		SMALLMEAT_DRIED = "Sieht aus wie Leder, schmeckt wie Fleisch.",
		SPEAR = "Davon habe ich einen Splitter.",
		SPIDER =
		{
			DEAD = "Aus klebrigem Spinnenzeug gemacht.",
			GENERIC = "Sie hat ein gruseliges Gesicht.",
			SLEEPING = "Ganz ruhig weitergehen. Vielleicht sieht er mich nicht.",
		},
		SPIDERDEN = "Die Käfer verstecken sich darin.",
		SPIDEREGGSACK = "Böse Spinneneier.",
		SPIDERGLAND = "Schwabbelig und wabbelig!",
		SPIDERHAT = "Wie ein Schmatzer von einem Riesenkäfer.",
		SPIDERQUEEN = "Oh nein! Ein wandelndes Käfer-Haus.",
		SPIDER_WARRIOR =
		{
			DEAD = "Jetzt nicht beängstigend!",
			GENERIC = "Diese ist extra gruselig.",
			SLEEPING = "Besser nicht aufwecken.",
		},
		SPOILED_FOOD = "Pfui! Ekelball!",
		STATUEHARP = "Wo ist die schöne Musik?",
		STATUEMAXWELL = "Der Mann ist jetzt Stein! Sehr verzwickt...",
		STINGER = "Ist scharf wie Spieß!",
		STRAWHAT = "Guter Hut!",
		SUNKBOAT = "Ist gebrochen!",
		SWEATERVEST = "Eine Weste für elegante Menschen.",
		TAFFY = "Toffee zum Zerdrücken!",
		TALLBIRD = "Der größte Vogel.",
		TALLBIRDEGG = "Da ist ein Vogel drin.",
		TALLBIRDEGG_COOKED = "Gebratener Vogel. Gut zum Frühstück.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Vogel mag Eiswürfel!",
			GENERIC = "Kleiner Vogel will raus.",
			HOT = "Ist zu heiß für kleinen Vogel!",
			LONG = "Ich warte auf Vogel.",
			SHORT = "Vogel kommt bald.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Ein großes Ei.",
			PICKED = "Ein Nest der Leere.",
		},
		TEENBIRD =
		{
			GENERIC = "Ha! Er ist gar nicht so groß.",
			HUNGRY = "Ist hungrig, und laut.",
			STARVING = "Er ist hungrig, laut und zornig!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Ich fürchte nicht, was mich erwartet.",
			GENERIC = "Seltsamer Stein. Soll ich mich draufsetzen?",
			LOCKED = "Irgendwas fehlt noch.",
			PARTIAL = "Kommt jetzt zusammen.",
		},
		TELEPORTATO_BOX = "Hat einen kleinen Hebel.",
		TELEPORTATO_CRANK = "Gebogenes Ding ist aus Metall!",
		TELEPORTATO_POTATO = "Hahaha! So eine hässliche Kartoffel!",
		TELEPORTATO_RING = "Ich werde es zu einem perfekten Kreis biegen!",
		TENT = "Es ist Zeit für ein mächtiges Schläfchen.",
		TENTACLE = "Nacktes Monster.",
		TENTACLESPOTS = "Igitt! Schleimig!",
        TENTACLESPIKE = "Ideal zum Kleben!",
		TENTACLE_PILLAR = "Viele kleine Freunde!",
		TENTACLE_PILLAR = "Viele kleine Freunde!",
		TENTACLE_PILLAR_ARM = "Kleine Baby-Tentakel-Ding! Ha!",
		TENTACLE_GARDEN = "Hmmmm, seltsam!",
		TOPHAT = "Guter Hut!",
		TORCH = "Ich greife die Nacht mit meinem Feuerstab an.",
		TRAP = "Keine Falle kann mich aufhalten!",
		TRAP_TEETH = "Es beißt, von unten.",
		TRAP_TEETH_MAXWELL = "Wer auch immer sie dahin gelegt hat, ist ein schlechter Kerl.",
		TREASURECHEST = "Dort tue ich Dinge hinein.",
		TRINKET_1 = "Nix besonderes, glaub ich.",
		TRINKET_10 = "Nix besonderes, glaub ich.",
		TRINKET_11 = "Nix besonderes, glaub ich.",
		TRINKET_12 = "Nix besonderes, glaub ich.",
		TRINKET_2 = "Nix besonderes, glaub ich.",
		TRINKET_3 = "Nix besonderes, glaub ich.",
		TRINKET_4 = "Nix besonderes, glaub ich.",
		TRINKET_5 = "Nix besonderes, glaub ich.",
		TRINKET_6 = "Nix besonderes, glaub ich.",
		TRINKET_7 = "Nix besonderes, glaub ich.",
		TRINKET_8 = "Nix besonderes, glaub ich.",
		TRINKET_9 = "Nix besonderes, glaub ich.",
		TRUNKVEST_SUMMER = "Eine warme, flauschige Nasen-Weste.",
		TRUNKVEST_WINTER = "Ich fühle mich in dieser Nasen-Weste wohl.",
		TRUNK_COOKED = "Eine gekochte Nase.",
		TRUNK_SUMMER = "Eine schlappe Nase.",
		TRUNK_WINTER = "Eine schlappe, haarige Nase.",
		TURKEYDINNER = "Ein Festmahl von einem Vogel.",
		TWIGS = "Mickrige Zweige! Ich kann sie zerbrechen!",
		UMBRELLA = "Der Regen schmerzt auf meiner mächtigen Haut.",
		WAFFLES = "Warum hat das Brot Löcher?",
		WALL_HAY = "Die Mauer ist aus Gras!",
		WALL_HAY_ITEM = "Kratzendes Stroh!",
		WALL_STONE = "Mauer ist stark wie ich!",
		WALL_STONE_ITEM = "Ein Stapel von Steinen.",
		WALL_RUINS = "Alte, starke Mauer.",
		WALL_RUINS_ITEM = "Ein Stapel alter Steine!",
		WALL_WOOD = "Hallo, spitze Stöcke!",
		WALL_WOOD_ITEM = "Spitze Stöcke.",
		WALRUS = "Seekuhmann!",
		WALRUSHAT = "Ich habe den Hut vom Seekuhmann.",
		WALRUS_CAMP =
		{
			EMPTY = "Verschlossen.",
			GENERIC = "Wie passen die da alle rein?",
		},
		WALRUS_TUSK = "Der Zahn von einem Seekuhmann.",
		WASPHIVE = "Verstand sagt Nein. Muskeln sagen Ja!",
		WETGOOP = "Wolfgang hat das Essen ruiniert.",
		WINTERHAT = "Macht Ohren im Winter glücklich.",
		WINTEROMETER = "Kalt geht hoch, warm geht runter.",
		WORMHOLE =
		{
			GENERIC = "Wie weiches Kissen, das auf Boden wächst.",
			OPEN = "Kann diesem Mann nichts anhaben!",
		},
 
        ARMORRUINS = "Mich beschützen? So etwas brauche ich nicht!",
        BISHOP_NIGHTMARE = "Zorniger Mann. Sollte sich entspannen.",
        GREENAMULET = "Was ist dieses Ding?", 
        GREENGEM = "Er ist hübsch und unerschütterlich! So wie ich!",
        KNIGHT_NIGHTMARE = "Komischer Metallmann.",
        MINOTAUR = "Stark! Wie ich! Ich mag ihn!",    
        MULTITOOL_AXE_PICKAXE = "Hacken und Graben! Das kann ich den ganzen Tag tun.",
        NIGHTMARELIGHT = "Licht, aber kein gutes.",
        NIGHTMARE_TIMEPIECE =
        {
            WARN = "Das böse Licht kommt bald.",  
            WAXING = "Böses Licht kommt und wir immer stärker.", 
            STEADY = "Ich glaube, böses Licht wird nicht stärker.", 
            WANING = "Zeit von bösem Licht geht zu Ende.", 
            DAWN = "Gute Zeit ist bald.", 
            CALM = "Kein böses Licht.", 
            NOMAGIC = "In Sicherheit vor bösem Licht.", 
        },
        ORANGESTAFF = "Besser zu gehen, denke ich.",  
        ROOK_NIGHTMARE = "Ist nichts gegen meine mächtige Brust!",
        RELIC = "Ist das Schrott?",
        RUINS_RUBBLE = "Ich werde es zerschmettern.",  
        RUINS_BAT = "Ist gruselig.",
        RUINSHAT = "Ist Hut für König.",
        SPIDER_DROPPER = "Unheimliche Spinne von oben.", 
        THULECITE = "Ein schöner Stein.",
        YELLOWAMULET = "Es leuchtet gelb.",    
		ACCOMPLISHMENT_SHRINE = "Ich werde dich vernichten, kleiner Pfeil.",  
		LIVINGTREE = "Ich mag den Baum mit den Augen nicht.",
		ICESTAFF = "Gefrorene Spitze.",              
	},
	DESCRIBE_GENERIC = "Was ist dieses Ding?",
	DESCRIBE_TOODARK = "Hilf mir! Es ist dunkel!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Dieses Ei ist knusprig. ",
	},
}
