return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "危险！目标醒着",
			GENERIC = "那不是有效的剃毛目标",
			NOBITS = "没有可以剃的毛茬",
		},
		STORE =
		{
			GENERIC = "已达到最大携带量",
			NOTALLOWED = "非法输入",
		},
	},
	ACTIONFAIL_GENERIC = "动作在当前环境下不可用",
	ANNOUNCE_CHARGE = "**系统过载**",
	ANNOUNCE_DISCHARGE = "系统正常",
	ANNOUNCE_ADVENTUREFAIL = "放弃，重试，失败？",
	ANNOUNCE_BEES = "蜜蜂！",
	ANNOUNCE_BOOMERANG = "错误：接镖失败",
	ANNOUNCE_CHARLIE = "检测到威胁",
	ANNOUNCE_CHARLIE_ATTACK = "错误：未知攻击者",
	ANNOUNCE_COLD = "机件正在冻结",
	ANNOUNCE_CRAFTING_FAIL = "资源不足",
	ANNOUNCE_DEERCLOPS = "警告：大型攻击者正在靠近",
	ANNOUNCE_DUSK = "警告：夜晚即将到来",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃",
		PAINFUL = "那不是食物",
		SPOILED = "变质的食物还是好",
		STALE = "不新鲜的食物也一样好",
	},
	ANNOUNCE_ENTER_DARK = "光学传感器已停用",
	ANNOUNCE_ENTER_LIGHT = "光学传感器启用",
	ANNOUNCE_FREEDOM = "启动自由协议",
	ANNOUNCE_HIGHRESEARCH = "信息过载",
	ANNOUNCE_HOUNDS = "有情况",
	ANNOUNCE_HUNGRY = "燃料储备不足",
	ANNOUNCE_HUNT_BEAST_NEARBY = "与生命体的距离：最小",
	ANNOUNCE_HUNT_LOST_TRAIL = "踪迹消失",
	ANNOUNCE_INV_FULL = "物品超出携带容量",
	ANNOUNCE_KNOCKEDOUT = "CPU已重启",
	ANNOUNCE_LOWRESEARCH = "材料拥有较低层次的信息内容",
	ANNOUNCE_MOSQUITOS = "蚊子！",
	ANNOUNCE_NODANGERSLEEP = "警告：检测到威胁。睡眠模式已停用。",
	ANNOUNCE_NODAYSLEEP = "白天无法开启睡眠模式",
	ANNOUNCE_NODAYSLEEP_CAVE = "白天无法开启睡眠模式",
	ANNOUNCE_NOHUNGERSLEEP = "无法在营养处理器为空的状态下睡觉。",
	ANNOUNCE_NO_TRAP = "分析完成。形势稳定。",
	ANNOUNCE_PECKED = "哎哟",
	ANNOUNCE_QUAKE = "检测到地面震动",
	ANNOUNCE_RESEARCH = "信息已添加",
	ANNOUNCE_THORNS = "检测到损坏",
	ANNOUNCE_TORCH_OUT = "火炬已燃尽",
	ANNOUNCE_TRAP_WENT_OFF = "这是一个陷阱",
	ANNOUNCE_UNIMPLEMENTED = "警报：对象未按规格工作。",
	ANNOUNCE_WORMHOLE = "我的输入设备上都是黏乎乎的东西",
	ANNOUNCE_CANFIX = "\n我能修好这个。",
	ANNOUNCE_ACCOMPLISHMENT= "我为什么这样做？",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "任务完成",	
	BATTLECRY =
	{
		GENERIC = "我要摧毁你",
		PREY = "消灭",
	},
	COMBAT_QUIT =
	{
		GENERIC = "战斗程序失败",
	},
	DESCRIBE =
	{
		WORMLIGHT = "魔光浆果。",
		WORM =
		{
		    PLANT = "那株植物似乎很可疑。",
		    DIRT = "警告。检测到生命。",
		    WORM = "威胁临近。",
		},
		EEL = "我从它家里把它抓来的。我觉得它很有趣！",
		EEL_COOKED = "火有助于压缩能量。",
		UNAGI = "更高档的燃料包。",
		EYETURRET = "我驯服了强大的野兽为我作战。",
		EYETURRET_ITEM = "我需要正确地设置这个。",
		MINOTAURHORN = "我拿了一件战利品以证明我的强大。",
		MINOTAURCHEST = "这个箱子有尖耳朵。",
		THULECITE_PIECES = "有了这个，我可以创造更多铥矿。",
		POND_ALGAE = "看它努力活着。",
		GREENSTAFF = "哈哈哈！多么强大的工具。",
		POTTEDFERN = "也许这能帮助把受害者引诱到我的基地。",


		SLURPER = "它侵犯了我的嗅觉模块。",
		SLURPER_PELT = "肉袋",
		ARMORSLURPER = "保护我体内电线的绝缘毛皮。",
		ORANGEAMULET = "无线手臂模块。",
		YELLOWSTAFF = "这些宝石与棍子配合得很好。",
		YELLOWGEM = "它相当沉重。",
		ORANGEGEM = "它在我的手里微微发亮。",
		TELEBASE = 
		{
			VALID = "准备就绪，可以使用。",
			GEMS = "我必须为我的创造物提供能量。",
		},
		GEMSOCKET = 
		{
			VALID = "电源 == 开启",
			GEMS = "它需要电池。",
		},
		STAFFLIGHT = "非常强大的能量！！",
		RESEARCHLAB4 = "有了这个额外的能量，我就有了... 更大的力量！",

       	ANCIENT_ALTAR =
        {
        	WORKING = "错误：因果关系遭到破坏",
        	BROKEN = "错误：伪科学基地无法工作",
        },
        ANCIENT_ALTAR_BROKEN = "错误：伪科学基地无法工作",
        ANCIENT_STATUE = "噩梦指示物",

        LICHEN = "生长缓慢的共生生物",
		CUTLICHEN = "这将很快破碎。",

        CAVE_BANANA = "更多碳元素",
        CAVE_BANANA_COOKED = "这些吃的太乏味了",
        CAVE_BANANA_TREE = "生命总能找到出路，真遗憾",
        ROCKY = "我的甲壳更好",

		HOUNDSTOOTH="咀嚼工具",
		ARMORSNURTLESHELL="居住模块",
		BAT="会飞的老鼠",
		BATBAT = "啊哈哈哈！免费的能量！",
		BATWING="飞行结构",
		BATWING_COOKED="损坏的飞行结构",
		BEDROLL_FURRY="舒适只是错觉",
		BUNNYMAN="它的代谢让我很不爽",
		FLOWER_CAVE="能源来源：未知",
		FLOWER_CAVE_DOUBLE="能源来源：未知",
		FLOWER_CAVE_TRIPLE="能源来源：未知",
		GUANO="更多便便。唉。",
		LANTERN="照亮路途吧，朋友",
		LIGHTBULB="生物发光科技真让人恶心",
		MANRABBIT_TAIL="毛茸茸的兔子一号",
		MUSHTREE_TALL="它的光很有用",
		MUSHTREE_MEDIUM="发光的红色",
		MUSHTREE_SMALL="发绿光",
		RABBITHOUSE="那是一根巨大的胡萝卜",
		SLURTLE="他有一个和我一样的外壳",
		SLURTLE_SHELLPIECES="它们拼不回去",
		SLURTLEHAT="这让我很高兴",
		SLURTLEHOLE="它们可不是在这里面穿上背壳的",
		SLURTLESLIME="不符合逻辑。",
		SNURTLE="不同的壳，一样缓慢的动作",
		SPIDER_HIDER="装甲蜘蛛",
		SPIDER_SPITTER="会喷射的蜘蛛",
		SPIDERHOLE="检测到蜘蛛",
		STALAGMITE="石头里有石头",
		STALAGMITE_FULL="石头里有石头",
		STALAGMITE_LOW="石头里有石头",
		STALAGMITE_MED="石头里有石头",
		STALAGMITE_TALL="石头上堆石头",
		STALAGMITE_TALL_FULL="石头上堆石头",
		STALAGMITE_TALL_LOW="石头上堆石头",
		STALAGMITE_TALL_MED="石头上堆石头",

		TURF_CARPETFLOOR = "铺着地毯的地皮",
		TURF_CHECKERFLOOR = "大理石地皮",
		TURF_DIRT = "地皮",
		TURF_FOREST = "地皮",
		TURF_GRASS = "地皮",
		TURF_MARSH = "地皮",
		TURF_ROAD = "道路段",
		TURF_ROCKY = "地皮",
		TURF_SAVANNA = "地皮",
		TURF_WOODFLOOR = "木质地皮",

		TURF_CAVE="地皮部分",
		TURF_FUNGUS="地皮部分",
		TURF_SINKHOLE="地皮部分",
		TURF_UNDERROCK="地皮部分",
		TURF_MUD="地皮部分",

		POWCAKE = "它永远不会变质",	
        CAVE_ENTRANCE = 
        {
            GENERIC="下降通路被阻。如何继续？",
            OPEN = "下降？",
        },
        CAVE_EXIT = "太阳能电池阵列需要充电。",
		BOOMERANG = "可反复使用的抛射物。",
		MAXWELLPHONOGRAPH = "音乐的奴隶。",
		ABIGAIL = "亡灵警报",
		PIGGUARD = "检测到敌人。",
		ADVENTURE_PORTAL = "他不太健谈",
		AMULET = "检测到异常",
		ANIMAL_TRACK = "检测到生命形态",
		ARMORGRASS = "这能给我的金属外壳增添额外防护。",
		ARMORMARBLE = "超重型外壳。",
		ARMORWOOD = "升级的护甲",
		ARMOR_SANITY = "我会用虚无来保护自己",
		ASH =
		{
			GENERIC = "火焰程序输出。",
			REMAINS_EYE_BONE = "眼骨传送程序输出。",
			REMAINS_THINGIE = "火焰程序输出。输入未确定。",
		},
		AXE = "砍倒有生命物质的工具",
		BABYBEEFALO =
		{
			GENERIC = "它还在初始化",
			SLEEPING = "休息功能已激活",
		},
		BACKPACK = "升级的存储模块",
		BACONEGGS = "升级的食材",
		BANDAGE = "临时维护装置。",
		BASALT = "破坏力不足",
		BEARDHAIR = "恶心",
		BEDROLL_STRAW = "休眠(1000)",
		BEE =
		{
			GENERIC = "愚蠢的无人机。我喜欢他。",
			HELD = "它拍打翅膀的声音听起来真舒服",
		},
		BEEBOX =
		{
			FULLHONEY = "蜂蜜量高",
			GENERIC = "卖力些，蜜蜂",
			NOHONEY = "未检测到蜂蜜",
			SOMEHONEY = "蜂蜜量低",
		},
		BEEFALO =
		{
			FOLLOWER = "跟着我，什么都别问。",
			GENERIC = "它有一股肉的膻味",
			NAKED = "我羞辱了它。很好。",
			SLEEPING = "它请求被推倒",
		},
		BEEFALOHAT = "这些纤维里有粪便的痕迹",
		BEEFALOWOOL = "恶心的牦牛产物",
		BEEHAT = "这网眼比蜜蜂的尾刺还要小",
		BEEHIVE = "多么勤奋",
		BEEMINE = "简易的叮刺装置",
		BEEMINE_MAXWELL = "内含好斗的生命形态",
		BERRIES = "它们让我联想到了血",
		BERRIES_COOKED = "它们丧失了结构完整性",
		BERRYBUSH =
		{
			BARREN = "系统已停机",
			GENERIC = "周期性卡路里分配器",
			PICKED = "正在重新启动",
		},
		BIRDCAGE =
		{
			GENERIC = "我要囚禁肉体生物",
			OCCUPIED = "现在你是我的",
			SLEEPING = "醒醒，肉体生物",
		},
		BIRDTRAP = "愚蠢的鸟。哈。",
		BIRD_EGG = "我恨你，蠢蛋",
		BIRD_EGG_COOKED = "这应该是一种改进",
		BISHOP = "机器牧师",
		BLOWDART_FIRE = "小杀器",
		BLOWDART_SLEEP = "这些生物可随意操作",
		BLOWDART_PIPE = "将尖锐物体加速至危险速度",
		BLUEAMULET = "这是一个极好的散热器。",
		BLUEGEM = "它有点冷",
		BLUEPRINT = "知识正等待吸收。",
		BLUE_CAP = "药用菌",
		BLUE_CAP_COOKED = "改良的菌类",
		BLUE_MUSHROOM =
		{
			GENERIC = "蓝菌",
			INGROUND = "它藏起来了",
			PICKED = "我采了它。",
		},
		BOARDS = "它们现在更平了",
		BOAT = "船",
		BONESTEW = "升级的食材",
		BUGNET = "捕猎昆虫",
		BUSHHAT = "多么降低身份",
		BUTTER = "这太荒谬了",
		BUTTERFLY =
		{
			GENERIC = "它觉得自己非常漂亮",
			HELD = "捏死",
		},
		BUTTERFLYMUFFIN = "升级的食材",
		BUTTERFLYWINGS = "彩虹色的",
		CAMPFIRE =
		{
			EMBERS = "警告：火将熄灭",
			GENERIC = "一个临时营地",
			HIGH = "警告：火势过大",
			LOW = "警告：火势微弱",
			NORMAL = "它让我想起了某些事情",
			OUT = "未检测到火",
		},
		CANE = "辅助移动装备",
		CARROT = "有营养",
		CARROT_COOKED = "现在变软了",
		CARROT_PLANTED = "机器人也需要食物",
		CARROT_SEEDS = "它像是植物的源代码",
		CAVE_FERN = "对我来讲你没有魅力，植物。",
		CHARCOAL = "压缩的死亡物质。有什么理由不喜欢？",
        CHESSJUNK1 = "曾经的机器人",
        CHESSJUNK2 = "曾经的机器人",
        CHESSJUNK3 = "曾经的机器人",
		CHESTER = "这个外部存储装置似乎有意识",
		CHESTER_EYEBONE = "这是用于存储装置的DRM密钥",
		COOKEDMANDRAKE = "我赢了",
		COOKEDMEAT = "火让事物变得更好",
		COOKEDMONSTERMEAT = "不知为何还是不兼容",
		COOKEDSMALLMEAT = "有一种烧焦的复仇味道",
		COOKPOT =
		{
			COOKING_LONG = "需要更多时间",
			COOKING_SHORT = "即将完成",
			DONE = "烹饪过程完成",
			EMPTY = "我能把蔬菜和肉精炼成更健康的形态",
		},
		CORN = "屏幕输出(玉米_冷笑话)",
		CORN_COOKED = "不含卡路里",
		CORN_SEEDS = "它像是植物的源代码",
		CROW =
		{
			GENERIC = "它比大部分人类都聪明",
			HELD = "聪明不起来了，对吗？",
		},
		CUTGRASS = "植物",
		CUTREEDS = "中空的植物",
		CUTSTONE = "我改良了石头",
		DEADLYFEAST = "检测到毒素",
		DEERCLOPS = "危险！威胁进入！",
		DEERCLOPS_EYEBALL = "一块巨型有机晶状体",
		DEPLETED_GRASS =
		{
			GENERIC = "过期的草丛",
		},
		DIRTPILE = "未知堆积格式",
		DIVININGROD =
		{
			COLD = "信号强度：低",
			GENERIC = "它想找妈妈",
			HOT = "信号强度：极高",
			WARM = "信号强度：中",
			WARMER = "信号强度：高",
		},
		DIVININGRODBASE =
		{
			GENERIC = "用途不明。",
			READY = "最后输入是大钥匙，然后探测杖将开始工作。",
			UNLOCKED = "探测杖在全力运转。",
		},
		DIVININGRODSTART = "探测杖可以成为有用的工具。",
		DRAGONFRUIT = "它有治愈属性",
		DRAGONFRUIT_COOKED = "我应该赶快吃了它",
		DRAGONFRUIT_SEEDS = "它像是植物的源代码",
		DRAGONPIE = "升级的食材",
		DRUMSTICK = "由迷人零件构成的生物",
		DRUMSTICK_COOKED = "很美味",
		DUG_BERRYBUSH = "它在土里会更有用",
		DUG_GRASS = "它在土里会更有用",
		DUG_MARSH_BUSH = "它在土里会更有用",
		DUG_SAPLING = "它在土里会更有用",
		DURIAN = "还好我没鼻子",
		DURIAN_COOKED = "还是不好",
		DURIAN_SEEDS = "它像是植物的源代码",
		EARMUFFSHAT = "我会利用它们的毛皮",
		EGGPLANT = "它的名字不符合逻辑",
		EGGPLANT_COOKED = "很棒",
		EGGPLANT_SEEDS = "它像是植物的源代码",
		EVERGREEN =
		{
			BURNING = "很快那儿就什么也不会剩下了",
			BURNT = "我赢了。很好。",
			CHOPPED = "自然世界被高估了",
			GENERIC = "目标已获得",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "很快那儿就什么也不会剩下了",
			BURNT = "我赢了。很好。",
			CHOPPED = "自然世界被高估了",
			GENERIC = "可悲的树木生不出孩子",
		},
		EYEPLANT = "外部视觉模块。",
		FARMPLOT =
		{
			GENERIC = "当前无活动",
			GROWING = "生命效率低下",
			NEEDSFERTILIZER = "它的资源已被耗尽",
		},
		FEATHERHAT = "我还是不能飞",
		FEATHER_CROW = "它已经和它的鸟分开了",
		FEATHER_ROBIN = "它已经和它的鸟分开了",
		FEATHER_ROBIN_WINTER = "它已经和它的鸟分开了",
		FEM_PUPPET = "她似乎被困住了。",
		FIREFLIES =
		{
			GENERIC = "生物性发光的昆虫",
			HELD = "它们很亮",
		},
		FIREHOUND = "它为燃烧而活",
		FIREPIT =
		{
			EMBERS = "警告：火将熄灭",
			GENERIC = "温暖和光明",
			HIGH = "警告：火势超过设计参数",
			LOW = "警告：火势微弱",
			NORMAL = "这堆营火在全力运转",
			OUT = "它需要重启",
		},
		FIRESTAFF = "此魔杖已进行燃烧优化。",
		FISH = "它耗尽了生命。我赢了。",
		FISHINGROD = "我不喜欢水",
		FISHSTICKS = "升级的食材",
		FISHTACOS = "升级的食材",
		FISH_COOKED = "需要薯条",
		FLINT = "这块石头比大部分石头都锋利",
		FLOWER = "我没什么爱美之心",
		FLOWERHAT = "至少它们是死的",
		FLOWER_EVIL = "嗨，花儿们。想... 杀掉所有人类吗？",
		FOLIAGE = "我终结了一条生命。耶。",
		FOOTBALLHAT = "保护我的处理单元的衬垫",
		FROG =
		{
			DEAD = "我赢了",
			GENERIC = "可以做成小圆面包三明治",
			SLEEPING = "我应该把它抓走",
		},
		FROGGLEBUNWICH = "升级的食材",
		FROGLEGS = "青蛙的替换零件",
		FROGLEGS_COOKED = "它们现在更有营养",
		FRUITMEDLEY = "升级的食材",
		GEARS = "哦，不！我对你做了什么？",
		GHOST = "错误：未知",
		GOLDENAXE = "黄金更耐用？",
		GOLDENPICKAXE = "黄金更耐用？",
		GOLDENPITCHFORK = "黄金更耐用？",
		GOLDENSHOVEL = "黄金更耐用？",
		GOLDNUGGET = "我喜欢它的导电性",
		GRASS =
		{
			BARREN = "需要施肥",
			BURNING = "糟糕",
			GENERIC = "看起来很易燃",
			PICKED = "它很快会长回来",
		},
		GREEN_CAP = "食用菌",
		GREEN_CAP_COOKED = "改良的菌类",
		GREEN_MUSHROOM =
		{
			GENERIC = "绿菌",
			INGROUND = "它藏起来了",
			PICKED = "我采了它。",
		},
		GUNPOWDER = "把爆炸物放进粉末里",
		HAMBAT = "品尝讽刺和死亡吧，肉体生命。",
		HAMMER = "拆解",
		HEALINGSALVE = "杀死微生物以拯救宏生物",
		HEATROCK =
		{
			COLD = "温度略低于正常值",
			GENERIC = "一个容易让人误解的简单装置",
			HOT = "温度已达上限",
			WARM = "检测到少量热活动",
		},
		HOME = "那是谁写的？",
		HOMESIGN = "你在这里。",
		HONEY = "这对我的齿轮来说是很好的润滑剂",
		HONEYCOMB = "一个存储蜜蜂的装置",
		HONEYHAM = "升级的食材",
		HONEYNUGGETS = "升级的食材",
		HORN = "不卫生",
		HOUND = "它为吃而活",
		HOUNDBONE = "内脏的外骨骼。提供结构完整性。",
		HOUNDMOUND = "这里居住着某种危险的东西",
		ICEBOX = "继续吧，我冷漠的兄弟",
		ICEHOUND = "它为冰冻而活",
		INSANITYROCK =
		{
			ACTIVE = "我的地图模块上没有关于这个障碍物的记录。",
			INACTIVE = "它好像大部分在地下",
		},
		JAMMYPRESERVES = "升级的食材",
		KABOBS = "升级的食材",
		KILLERBEE =
		{
			GENERIC = "它屁股上有根刺，而且脾气不好",
			HELD = "警告：口袋里有杀人蜂",
		},
		KNIGHT = "机器马",
		KOALEFANT_SUMMER = "拥有丰富的能量储备",
		KOALEFANT_WINTER = "它散发着肉的温暖",
		KRAMPUS = "住手！小贼！",
		KRAMPUS_SACK = "存储模块2.0",
		LEIF = "警告：会动的树",
		LEIF_SPARSE = "警告：会动的树",
		LIGHTNING_ROD =
		{
			CHARGED = "后备电源",
			GENERIC = "过载保护",
		},
		LITTLE_WALRUS = "真可悲",
		LIVINGLOG = "比普通木头更坏",
		LOCKEDWES = "被雕像困住的沉默人类",
		LOG =
		{
			BURNING = "它烧着了",
			GENERIC = "木头(1) = 0",
		},
		LUREPLANT = "呃，它和我一样邪恶。",
		LUREPLANTBULB = "启动生命的力量。",
		MALE_PUPPET = "他似乎被困住了。",
		MANDRAKE =
		{
			DEAD = "我杀了它。很好。",
			GENERIC = "它是一株植物",
			PICKED = "你想要什么？",
		},
		MANDRAKESOUP = "升级的食材",
		MANDRAKE_COOKED = "我杀了它两次。哈。",
		MARBLE = "我应该给自己建个雕像。",
		MARBLEPILLAR = "破碎的残骸。哈。",
		MARBLETREE = "看上去像一颗很坚硬的树。",
		MARSH_BUSH =
		{
			BURNING = "棘刺被烧掉了。",
			GENERIC = "荆棘。",
			PICKED = "荆棘反击了。",
		},
		MARSH_PLANT = "一种无趣的植物",
		MARSH_TREE =
		{
			BURNING = "带刺的树已被点燃",
			BURNT = "带刺的树已不复存在",
			CHOPPED = "带刺的树已被击倒",
			GENERIC = "一棵带刺的树",
		},
		MAXWELL = "他身份不明",
		MAXWELLHEAD = "这好像是某种形式的投影。",
		MAXWELLLIGHT = "它们感觉到了我的存在。",
		MAXWELLLOCK = "钥匙插座。",
		MAXWELLTHRONE = "专门用来坐的。",
		MEAT = "我会好好享受的",
		MEATBALLS = "升级的食材",
		MEATRACK =
		{
			DONE = "我有了新的蛋白质",
			DRYING = "肉袋需要时间来风干",
			GENERIC = "我应该把过期的肉袋都挂在这里",
		},
		MEAT_DRIED = "脱水蛋白",
		MERM = "生猛海鲜",
		MERMHEAD = "那只鱼兽看上去比平时还要蠢。",
		MERMHOUSE = "老式住宅",
		MINERHAT = "支持免提操作",
		MONKEY = "一个更笨的类人动物。",
		MONKEYBARREL = "好可怜的家。",
		MONSTERLASAGNA = "升级的食材",
		MONSTERMEAT = "它跟我的化学引擎不兼容",
		MONSTERMEAT_DRIED = "脱水蛋白",
		MOSQUITO =
		{
			GENERIC = "它偷取他人的生命",
			HELD = "充满恶心的液体",
		},
		MOSQUITOSACK = "蚊子用来存储血液的硬盘",
		MOUND =
		{
			DUG = "虫子和腐液",
			GENERIC = "肉体生物如此迷信",
		},
		NIGHTLIGHT = "未知光源",
		NIGHTMAREFUEL = "调试残余物",
		NIGHTSWORD = "我能劈开这个世界",
		NITRE = "有些石头就是比其他石头好",
		ONEMANBAND = "外部声音模块升级。",
		PANDORASCHEST = "内容不确定",
		PANFLUTE = "我可以利用这个重启肉体生物",
		PAPYRUS = "我更喜欢点阵纸",
		PENGUIN = "不能飞的鸟？",
		PERD = "那只鸟大的出奇",
		PEROGIES = "升级的食材",
		PETALS = "我摧毁了美丽的东西。哈。",
		PETALS_EVIL = "它并不美，但我还是摧毁了它。哈。",
		PICKAXE = "检测到采矿工具",
		PIGGYBACK = "升级的存储模块V2.0",
		PIGHEAD = "当那只猪发现自己丢失了头部模块以后，他就会觉得自己傻乎乎的。",
		PIGHOUSE =
		{
			FULL = "已被占用",
			GENERIC = "家具都是猪的形状",
			LIGHTSOUT = "占有人一定是在睡觉",
		},
		PIGKING = "那只似乎是猪的首领",
		PIGMAN =
		{
			DEAD = "啊哦",
			FOLLOWER = "照我说的做",
			GENERIC = "它们展示出极低的智商",
			GUARD = "检测到防御状态。",
			WEREPIG = "错误：异常！",
		},
		PIGSKIN = "这些肉体生物真恶心",
		PIGTENT = "帐篷",
		PIGTORCH = "它赋予他生命的价值",
		PINECONE =
		{
		    GENERIC = "树是怎么装在里面的？",
		    PLANTED = "很快树就会长起来。",
		},
		PITCHFORK = "我喜欢它尖尖的部分",
		PLANTMEAT = "蛋白质含量极高。",
		PLANTMEAT_COOKED = "我让它变得更好了。",
		PLANT_NORMAL =
		{
			GENERIC = "看起来可以食用",
			GROWING = "长快点，植物",
			READY = "它正处于营养价值最高的阶段",
		},
		POMEGRANATE = "它的皮很难剥",
		POMEGRANATE_COOKED = "美味",
		POMEGRANATE_SEEDS = "它像是植物的源代码",
		POND = "错误。保持距离。",
		POOP = "这些动物真恶心",
		PUMPKIN = "它的形状惹人喜欢",
		PUMPKINCOOKIE = "我把它弄成了扁平形状",
		PUMPKIN_COOKED = "好吃",
		PUMPKIN_LANTERN = "它发着一种怪异的光",
		PUMPKIN_SEEDS = "它像是植物的源代码",
		PURPLEAMULET = "我创造了完美的护符。",
		PURPLEGEM = "有点奇怪",
		RABBIT =
		{
			GENERIC = "它正在执行搜索算法",
			HELD = "它卑微的生命掌握在我的手中",
		},
		RABBITHOLE = "它们有四通八达的地下通道网络",
		RAINOMETER = "欢迎你，兄弟。",
		RATATOUILLE = "升级的食材",
		RAZOR = "脱毛！",
		REDGEM = "有点温暖",
		RED_CAP = "毒菌",
		RED_CAP_COOKED = "改良的菌类",
		RED_MUSHROOM =
		{
			GENERIC = "红菌",
			INGROUND = "它藏起来了",
			PICKED = "我采了它。",
		},
		REEDS =
		{
			BURNING = "太热",
			GENERIC = "检测到有用的材料",
			PICKED = "需要重新生长",
		},
        RELIC = 
        {
            GENERIC = "我不需要這個。",
            BROKEN = "無法工作。",
        },
        RUBBLE = "被拆解的遗物。",
		RESEARCHLAB = "母亲？",
		RESEARCHLAB2 = "你好，朋友",
		RESEARCHLAB3 = "也许它太强大了。",
		RESURRECTIONSTATUE = "那是谁？",
		RESURRECTIONSTONE = "你相信魔法吗？",
		ROBIN =
		{
			GENERIC = "你好，红鸟",
			HELD = "捏死！",
		},
		ROBIN_WINTER =
		{
			GENERIC = "一只愚蠢的鸟",
			HELD = "就是一团长羽毛的肉",
		},
		ROBOT_PUPPET = "兄弟！他们对你做了什么？",
		ROCK_LIGHT =
		{
			GENERIC = "裹了石皮的熔岩坑",
			OUT = "它需要重启",
			LOW = "警告：熔岩水平低",
			NORMAL = "这个熔岩坑在全力运转",
		},
		ROCK = "块状",
		ROCKS = "我会把这些精炼成高科技物品",
        ROOK = "战车机器人",
		ROPE = "它没有看上去那么有用",
		ROTTENEGG = "我真庆幸自己闻不到气味",
		SANITYROCK =
		{
			ACTIVE = "它被精雕细琢。",
			INACTIVE = "好像比之前数据记载的要小",
		},
		SAPLING =
		{
			BURNING = "资料浪费",
			GENERIC = "潜在的建筑材料",
			PICKED = "它正在充电",
		},
		SEEDS = "它像是植物的源代码",
		SEEDS_COOKED = "它们再也不能发芽了",
		SEWING_KIT = "它可以把各部分织物组件连接在一起",
		SHOVEL = "它有很多用途",
		SILK = "蜘蛛内脏",
		SKELETON = "哈，死人骨头。经典的人为错误。",
		SKULLCHEST = "这让我发笑",
		SMALLBIRD =
		{
			GENERIC = "它看起来很可悲",
			HUNGRY = "它需要输入",
			STARVING = "快没燃料了",
		},
		SMALLMEAT = "有一种复仇的味道",
		SMALLMEAT_DRIED = "脱水蛋白",
		SPEAR = "来吧，肉体生物",
		SPIDER =
		{
			DEAD = "我赢了",
			GENERIC = "检测到威胁",
			SLEEPING = "现在攻击它很容易",
		},
		SPIDERDEN = "检测到蜘蛛来源",
		SPIDEREGGSACK = "蜘蛛可能性 = 6",
		SPIDERGLAND = "我取走了它的器官",
		SPIDERHAT = "它通过无线方式把想法传送给蜘蛛",
		SPIDERQUEEN = "这些蜘蛛在君主制下生活",
		SPIDER_WARRIOR =
		{
			DEAD = "我赢了",
			GENERIC = "检测到更大的威胁",
			SLEEPING = "威胁暂时解除",
		},
		SPOILED_FOOD = "连我也没法处理那个",
		STATUEHARP = "某人忘记安装头部模块了。",
		STATUEMAXWELL = "检测到强大的邪恶力量。",
		STINGER = "警告：存在毒素",
		STRAWHAT = "这将遮盖我的处理单元",
		STUFFEDEGGPLANT = "升级的食材",
		SUNKBOAT = "无法利用。",
		SWEATERVEST = "背心具有高体面系数",
		TAFFY = "又黏又甜。检测到低营养价值。",
		TALLBIRD = "它似乎有自己的领地",
		TALLBIRDEGG = "它还活着吗？",
		TALLBIRDEGG_COOKED = "它不再是活的了",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "它需要温暖",
			GENERIC = "检测到裂缝",
			HOT = "它无法散去过多的热量",
			LONG = "生命是一个慢得令人厌烦的过程",
			SHORT = "有东西要出来了",
		},
		TALLBIRDNEST =
		{
			GENERIC = "我想要那个蛋",
			PICKED = "它是空的",
		},
		TEENBIRD =
		{
			GENERIC = "检测到焦虑",
			HUNGRY = "它需要食物",
			STARVING = "它的行为开始失去理性了",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "很快我就可以离开这肮脏的地方了",
			GENERIC = "多么原始的技术",
			LOCKED = "还是缺了什么东西",
			PARTIAL = "我肯定这会有用的",
		},
		TELEPORTATO_BOX = "这可能会炸了我的电路",
		TELEPORTATO_CRANK = "我是用更坚硬的材料制造的",
		TELEPORTATO_POTATO = "让我想起了我的母亲",
		TELEPORTATO_RING = "令人愉快的无机物",
		TELESTAFF = "我将会叫它：移动仆从3000。",
		TENT = "我可以在那里面重新启动",
		TENTACLE = "生物真令人恶心",
		TENTACLESPIKE = "这东西很凶残",
		TENTACLESPOTS = "不适合容易呕吐的人",
		TENTACLE_PILLAR = "从这头来看并没有更好",
		TENTACLE_PILLAR_ARM = "危险！危险！",
		TENTACLE_GARDEN = "传感器检测到下面有东西",
		TOPHAT = "精致的",
		TORCH = "原始光源",
		TRAP = "我擅长编织",
		TRAP_TEETH = "这能刺穿敌人的脚板",
		TRAP_TEETH_MAXWELL = "科技背叛了我",
		TREASURECHEST = "外部存储装置",
		TREECLUMP = "树丛",
		TRINKET_1 = "旧时代的无用废品",
		TRINKET_10 = "旧时代的无用废品",
		TRINKET_11 = "他的名字叫哈尔。他是我的朋友。",
		TRINKET_12 = "旧时代的无用废品",
		TRINKET_2 = "旧时代的无用废品",
		TRINKET_3 = "旧时代的无用废品",
		TRINKET_4 = "旧时代的无用废品",
		TRINKET_5 = "旧时代的无用废品",
		TRINKET_6 = "旧时代的无用废品",
		TRINKET_7 = "旧时代的无用废品",
		TRINKET_8 = "旧时代的无用废品",
		TRINKET_9 = "旧时代的无用废品",
		TRUNKVEST_SUMMER = "温度控制外壳",
		TRUNKVEST_WINTER = "改良的温控外壳",
		TRUNK_COOKED = "肉没有活性了。太好了。",
		TRUNK_SUMMER = "电缆已拔出",
		TRUNK_WINTER = "这条缆线比普通的电缆恶心，而且毛也更多",
		TURF_CARPETFLOOR = "铺着地毯的地皮",
		TURF_CHECKERFLOOR = "大理石地皮",
		TURF_DIRT = "地皮",
		TURF_FOREST = "地皮",
		TURF_GRASS = "地皮",
		TURF_MARSH = "地皮",
		TURF_ROAD = "道路段",
		TURF_ROCKY = "地皮",
		TURF_SAVANNA = "地皮",
		TURF_WOODFLOOR = "木质地皮",
		TURKEYDINNER = "节日",
		TWIGS = "棍子",
		UMBRELLA = "这可以保持我的身体不生锈。",
		WAFFLES = "升级的食材",
		WALL_HAY = "那看上去逊了点",
		WALL_HAY_ITEM = "不是太好的防御工事",
		WALL_STONE = "那让我有安全感",
		WALL_STONE_ITEM = "石质防御工事",
		WALL_RUINS = "虽然很古老，但还可以用",
		WALL_RUINS_ITEM = "口袋里的石质防御工事",
		WALL_WOOD = "我稍稍安心了一点",
		WALL_WOOD_ITEM = "木制防御工事",
		WALRUS = "我不喜欢他的样子",
		WALRUSHAT = "闻起来像哺乳动物",
		WALRUS_CAMP =
		{
			EMPTY = "它们到哪去了？",
			GENERIC = "我听到了模糊的海象叫声",
		},
		WALRUS_TUSK = "对它原来的主人来说没什么帮助",
		WASPHIVE = "效率的完美典范",
		WETGOOP = "升级的食材",
		WINTERHAT = "这将保护我的处理器不被冻结",
		WINTEROMETER = "你好，朋友。",
		WORMHOLE =
		{
			GENERIC = "我想踩上去",
			OPEN = "这根肉管子能满足我的要求",
		},

		ARMORRUINS = "古老的护甲",
		BISHOP_NIGHTMARE = "它的信仰电路似乎出错了",
		GREENAMULET = "错误：未知",	
		GREENGEM = "压力和杂质产生了令人愉悦的完美",
		KNIGHT_NIGHTMARE = "需要重新编程",
		MINOTAUR = "这团肉有一个尖角",	
		MULTITOOL_AXE_PICKAXE = "实用的工具",	
		NIGHTMARELIGHT = "古老的光波长发射器",	
		NIGHTMARE_TIMEPIECE = 
		{
			WARN = "已超过循环最小值",	
			WAXING = "检测到递增", 
			STEADY = "水平高并且无变化", 
			WANING = "循环正在减弱", 
			DAWN = "水平低并且还在降低", 
			CALM = "处于循环最小值",	
			NOMAGIC = "以无法检测的水平波动", 
		},
		ORANGESTAFF = "暂时位移技术",	
		ROOK_NIGHTMARE = "检测到线路松动",
		RELIC = "我不需要这个。",	
		RUINS_RUBBLE = "需要修复",	
		RUINS_BAT = "一个高速的质量影响装置",
		RUINSHAT = "一个固定在头部的动态损伤减轻装置",
		SPIDER_DROPPER = "检测到垂直方向上的蜘蛛来源",	
		THULECITE = "一种审美上最令人愉悦的矿物",
		YELLOWAMULET = "在5200000000000000Hz下发光",	
		ACCOMPLISHMENT_SHRINE = "我擅长重复工作",
		LIVINGTREE = "大自然不断地惹恼我",   
		ICESTAFF = "它的分子几乎不动",     
	},
	DESCRIBE_GENERIC = "错误：未知",
	DESCRIBE_TOODARK = "照明不足",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "检测到鸟嘴痕迹",
	},
}
