return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我會一直等到他閉眼為止。",
			GENERIC = "那個剃不了。",
			NOBITS = "已經沒毛了，我剃不了。",
		},
	},
	ACTIONFAIL_GENERIC = "我不夠強大，做不到。",
	
	ANNOUNCE_NORMALTOMIGHTY="我是最強壯的！",
	ANNOUNCE_NORMALTOWIMPY="我感覺不太好。",
	ANNOUNCE_WIMPYTONORMAL="沃夫岡感覺好些了。",
	ANNOUNCE_MIGHTYTONORMAL="我需要再次填滿我碩大的肚子！",


	ANNOUNCE_ADVENTUREFAIL = "下次我會聰明點的！",
	ANNOUNCE_BOOMERANG = "噢！你為什麼傷害我，會飛的臭棍子？",
	ANNOUNCE_CHARLIE = "出來！",
	ANNOUNCE_CHARLIE_ATTACK = "噢！它擊中我了！",
	ANNOUNCE_COLD = "嘶~~~~~~~！好冷！",
	ANNOUNCE_CRAFTING_FAIL = "我需要收集更多東西才能製造那個。",
	ANNOUNCE_DUSK = "令人恐慌的時刻即將到來。",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "噢~ 我肚子疼。",
		SPOILED = "嘔！味道像垃圾！",
		STALE = "味道怪怪的。",
	},
	ANNOUNCE_ENTER_DARK = "我看不見了！我害怕！",
	ANNOUNCE_ENTER_LIGHT = "我又可以看到東西了！",
	ANNOUNCE_HOUNDS = "我聽到了小狗的聲音！",
	ANNOUNCE_HUNGRY = "我碩大的肚子空了！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "動物在附近！",
	ANNOUNCE_HUNT_LOST_TRAIL = "這裡沒有動物。",
	ANNOUNCE_INV_FULL = "我再強壯也帶不了更多東西了。",
	ANNOUNCE_PECKED = "為什麼要這樣對我？",
	ANNOUNCE_TORCH_OUT = "哦，不！火滅了！",
	ANNOUNCE_WORMHOLE = "它讓我感到自己還活著！",
	ANNOUNCE_TRAP_WENT_OFF = "啊！別驚嚇沃夫岡！",
    ANNOUNCE_QUAKE = "大地在震顫。沃夫岡討厭搖晃的地面。",
    ANNOUNCE_NODANGERSLEEP = "沃夫岡喜歡戰鬥多過睡覺。",
    ANNOUNCE_UNIMPLEMENTED = "還沒好。",
    ANNOUNCE_NOHUNGERSLEEP = "沃夫岡說，絕不空腹睡覺。",
    ANNOUNCE_FREEDOM = "我自由了！大大的自由！",
    ANNOUNCE_RESEARCH = "好多資訊。",
    ANNOUNCE_NO_TRAP = "像舉重一樣簡單。",
    ANNOUNCE_HIGHRESEARCH = "也許資訊太多了。",
    ANNOUNCE_THORNS = "尖刺是不公平的！",
    ANNOUNCE_NODAYSLEEP_CAVE = "洞穴裡太嚇人了。",
    ANNOUNCE_BEES = "蜜蜂！討厭的螫人蟲子！",
    ANNOUNCE_KNOCKEDOUT = "呃，我一定是被砸到了腦袋。",
    ANNOUNCE_LOWRESEARCH = "一點點資訊。",
    ANNOUNCE_DEERCLOPS = "聽起來像是有一個強壯的巨人來了。",
    ANNOUNCE_MOSQUITOS = "沃夫岡需要血，該死的蟲子快滾開！",
    ANNOUNCE_NODAYSLEEP = "天太亮了，睡不著。",
	ANNOUNCE_CANFIX = "\n聰明的頭腦可以使這個變得更好！",
	ANNOUNCE_ACCOMPLISHMENT= "我用小小的箭頭做偉大的事情！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我打敗了小箭頭！",	
	BATTLECRY =
	{
		GENERIC = "我要揍扁你！",
		PIG = "對不起，我的朋友！",
		PREY = "我踩！我踩！我踩！",
		SPIDER = "去死吧，邪惡可怕的蟲子！",
		SPIDER_WARRIOR = "還是我更強壯，可怕的蟲子！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "哈！我贏了！",
		PIG = "我原諒你，豬人。",
		PREY = "繼續逃吧你！",
		SPIDER = "他逃走了。",
		SPIDER_WARRIOR = "他知道我更強壯。",
	},
	DESCRIBE =
	{
		WORMLIGHT = "漂亮的燈。",
		WORM =
		{
		    PLANT = "漂亮的燈。",
		    DIRT = "土在動？",
		    WORM = "完全沒料到！",
		},
		EEL = "我必須弄熟了這個！",
		EEL_COOKED = "我把它弄熟了。",
		UNAGI = "食物讓我強大！",
		EYETURRET = "強大的建築將幫助我戰鬥！",
		EYETURRET_ITEM = "我必須放置這個。",
		MINOTAURHORN = "強大對手掉落的戰利品。",
		MINOTAURCHEST = "這箱子長著大尖角。",
		THULECITE_PIECES = "我能混到一起做成更大的一塊！",
		POND_ALGAE = "這麼小的植物！我覺得很有趣。",
		GREENSTAFF = "這根棍子上面有一顆綠寶石。",
		POTTEDFERN = "它讓我很高興。",

		SLURPER = "不！不！離我的頭遠點！",
		SLURPER_PELT = "它還在動！",
		ARMORSLURPER = "它隨我的許多肌肉一起運動！",
		ORANGEAMULET = "我能把它戴在脖子上。",
		YELLOWSTAFF = "漂亮的寶石裝在棍子上。",
		YELLOWGEM = "漂亮的石頭。",
		ORANGEGEM = "漂亮的石頭。",
		TELEBASE = 
		{
			VALID = "發光是好跡象。",
			GEMS = "不覺得它起作用了。",
		},
		GEMSOCKET = 
		{
			VALID = "漂亮的石頭現在裝好了。",
			GEMS = "它是空的。",
		},
		STAFFLIGHT = "摸了會手疼。",
		RESEARCHLAB4 = "帽子不光可以用來戴在頭上。",

        ANCIENT_ALTAR =
        {
        	WORKING = "骯髒詭異的祭壇。",
        	BROKEN = "破損的祭壇。",
        },  
        ANCIENT_ALTAR_BROKEN = "破損的祭壇。",

        ANCIENT_STATUE = "醜、醜、醜。",

        LICHEN = "我喜歡這個！",
		CUTLICHEN = "真難吃。",

        CAVE_BANANA = "真好吃！",
        CAVE_BANANA_COOKED = "溫暖的食物，真好吃！",
        CAVE_BANANA_TREE = "你好，倒立的樹。",
        ROCKY = "他真強壯！就像我一樣！",

        BLUEAMULET = "可以做出很好的冰塊！",
		PURPLEAMULET = "這個護符...讓沃夫岡感到害怕。",
		TELESTAFF = "它讓我頭疼。",
		MINERHAT = "放在腦袋上的燈。",
		MONKEY = "醜陋的猴人！",
		MONKEYBARREL = "這個...東西。氣味不怎麼好聞。",

		HOUNDSTOOTH="狗牙！",
		ARMORSNURTLESHELL="裡面黏黏的。",
		BAT="會飛的老鼠！",
		BATBAT = "這根棒子讓我感覺好好笑。",
		BATWING="長滿了毛，很噁心",
		BATWING_COOKED="外酥內嫩！",
		BEDROLL_FURRY="真舒服！",
		BUNNYMAN="你好，兔子！",
		FLOWER_CAVE="發光的植物。",
		FLOWER_CAVE_DOUBLE="發光的植物。",
		FLOWER_CAVE_TRIPLE="發光的植物。",
		GUANO="更多便便。",
		LANTERN="讓我在黑暗中很安全。",
		LIGHTBULB="能吃嗎？",
		MANRABBIT_TAIL="毛茸茸的！",
		MUSHTREE_TALL  ="大蘑菇樹確實很大。",
		MUSHTREE_MEDIUM="蘑菇灌木。",
		MUSHTREE_SMALL ="矮蘑菇樹。",
		RABBITHOUSE="我聽見裡面有吃東西的聲音。",
		SLURTLE="哈！你真慢！",
		SLURTLE_SHELLPIECES="碎掉了。",
		SLURTLEHAT="保護我腦袋的安全。",
		SLURTLEHOLE="洞裡全是鼻涕蟲。",
		SLURTLESLIME="一坨鼻涕！",
		SNURTLE="螺旋狀的！",
		SPIDER_HIDER="是受驚的蜘蛛！",
		SPIDER_SPITTER="噗突！噗突！",
		SPIDERHOLE="到處都是蜘蛛。",
		STALAGMITE="尖尖的。",
		STALAGMITE_FULL="尖尖的。",
		STALAGMITE_LOW="尖尖的。",
		STALAGMITE_MED="尖尖的。",
		STALAGMITE_TALL="岩石從大地上冒出來。",
		STALAGMITE_TALL_FULL="岩石從大地上冒出來。",
		STALAGMITE_TALL_LOW="岩石從大地上冒出來。",
		STALAGMITE_TALL_MED="岩石從大地上冒出來。",

		TURF_CARPETFLOOR = "踏腳石。",
		TURF_CHECKERFLOOR = "踏腳石。",
		TURF_DIRT = "踏腳石。",
		TURF_FOREST = "踏腳石。",
		TURF_GRASS = "踏腳石。",
		TURF_MARSH = "踏腳石。",
		TURF_ROAD = "踏腳石。",
		TURF_ROCKY = "踏腳石。",
		TURF_SAVANNA = "踏腳石。",
		TURF_WOODFLOOR = "踏腳石。",

		TURF_CAVE="踏腳石。",
		TURF_FUNGUS="踏腳石。",
		TURF_SINKHOLE="踏腳石。",
		TURF_UNDERROCK="踏腳石。",
		TURF_MUD="踏腳石。",

		POWCAKE = "都不知道是什麼做的！",
        CAVE_ENTRANCE = 
        {
            GENERIC="連我也沒那麼大的力氣。",
            OPEN = "地球的肚臍眼！",
        },
        CAVE_EXIT = "這下面又黑又恐怖。",

		MAXWELLPHONOGRAPH = "會唱歌的盒子！",
		BOOMERANG = "迴旋！鏢！哈！",
		PIGGUARD = "壞小豬！",
		ADVENTURE_PORTAL = "口形門！說「啊~」！",
		AMULET = "很漂亮。",
		ANIMAL_TRACK = "動物向這邊走了。",
		ARMORGRASS = "刺人。",
		ARMORMARBLE = "我把石頭綁在肌肉上。",
		ARMORWOOD = "幾乎和肚子一樣結實！",
		ARMOR_SANITY = "就像是穿著一塊嚇人的破布！",
		ASH =
		{
			GENERIC = "火焰的殘骸。",
			REMAINS_EYE_BONE = "當我傳送時被燒成灰燼的眼骨！",
			REMAINS_THINGIE = "某種被燒燬的東西。現在死了...",
		},
		AXE = "砍！",
		BABYBEEFALO = "小犛牛！",
		BACKPACK = "為了帶更多的東西。",
		BACONEGGS = "食物裡有蛋黃！還有肉！更強壯！",
		BANDAGE = "我能修好自己！",
		BASALT = "比我還強硬！",
		BEARDHAIR = "噁心。這些不是從我臉上剃下來的。",
		BEDROLL_STRAW = "休息時間到了！",
		BEE =
		{
			GENERIC = "又胖又生氣的樣子。",
			HELD = "在我的口袋裡很安全。",
		},
		BEEBOX =
		{
			GENERIC = "蜜蜂！",
			READY = "可以採集了！",
		},
		BEEFALO =
		{
			FOLLOWER = "犛牛跟著我！",
			GENERIC = "犛牛！",
			NAKED = "犛牛沒毛了。",
			SLEEPING = "犛牛在睡覺。",
		},
		BEEFALOHAT = "這帽子不錯！",
		BEEFALOWOOL = "我用牛毛做衣服。",
		BEEHAT = "防止蜜蜂螫人的帽子。",
		BEEHIVE = "啊，蜂巢！",
		BEEMINE = "裝滿憤怒蜜蜂的球。",
		BEEMINE_MAXWELL = "裝滿憤怒蚊蟲的球。",
		BERRIES = "真好吃！",
		BERRIES_COOKED = "更好吃了！",
		BERRYBUSH =
		{
			BARREN = "我需要在上面施肥。",
			GENERIC = "長滿了吃的！",
			PICKED = "能吃的部分沒了。",
		},
		BIRDCAGE =
		{
			GENERIC = "我家小鳥的窩。",
			OCCUPIED = "你好，小鳥！",
			SLEEPING = "我應該保持安靜！",
		},
		BIRDTRAP = "我要去抓鳥！",
		BIRD_EGG = "可憐的小鳥。",
		BIRD_EGG_COOKED = "好吃！",
		BISHOP = "神父！",
		BLOWDART_FIRE = "當心，沃夫岡。",
		BLOWDART_SLEEP = "吹箭讓敵人睡覺。",
		BLOWDART_PIPE = "讓敵人痛苦的吹箭。",
		BLUEGEM = "漂亮的石頭。",
		BLUEPRINT = "漂亮的圖畫！",
		BLUE_CAP = "我想這對我有好處。",
		BLUE_CAP_COOKED = "變得不一樣了。",
		BLUE_MUSHROOM =
		{
			GENERIC = "蘑菇。",
			INGROUND = "蘑菇藏起來了！",
			PICKED = "我已經採了那蘑菇。",
		},
		BOARDS = "我會劈開原木做木板！",
		BONESTEW = "全是好肉的燉菜。",
		BUGNET = "抓蟲子用的。",
		BUSHHAT = "我真是太狡猾了！",
		BUTTER = "是牛油，嚐起來像昆蟲。",
		BUTTERFLY =
		{
			GENERIC = "蝴蝶飛舞！",
			HELD = "我的愛寵！",
		},
		BUTTERFLYMUFFIN = "沃夫岡沒吃過蟲子瑪芬。我嚐嚐。",
		BUTTERFLYWINGS = "沒有翅膀飛不起來！",
		CAMPFIRE =
		{
			EMBERS = "黑暗來臨了！",
			GENERIC = "再見了，黑暗時代！",
			HIGH = "火太大了！",
			LOW = "火不夠熱。",
			NORMAL = "好火！",
			OUT = "啊哦。火滅了。",
		},
		CANE = "我可以一邊走路一邊戰鬥！",
		CARROT = "這是食物。我猜。",
		CARROT_COOKED = "烤過以後也沒有更像肉。",
		CARROT_PLANTED = "藏著呢？",
		CARROT_SEEDS = "種子太小了。",
		CAVE_FERN = "漂亮的植物！",
		CHARCOAL = "像拿著小小的死樹。",
        CHESSJUNK1 = "金屬垃圾。",
        CHESSJUNK2 = "金屬垃圾。",
        CHESSJUNK3 = "金屬垃圾。",
		CHESTER = "有腳的奇怪箱子。",
		CHESTER_EYEBONE =
		{
			GENERIC = "這是眼骨。眼骨連著臉骨。",
			WAITING = "它現在睡著了。",
		},
		COOKEDMEAT = "我很會烤肉！",
		COOKEDMONSTERMEAT = "我還是不想吃這個。",
		COOKEDSMALLMEAT = "烤熟之後更小了！",
		COOKPOT =
		{
			COOKING_LONG = "這需要很長時間。",
			COOKING_SHORT = "快熟了！",
			DONE = "吃飯時間到了！",
			EMPTY = "空鍋子讓沃夫岡產生了飢餓感。",
		},
		CORN = "是玉米，你還想指望什麼？",
		CORN_COOKED = "啵啵啵！哈哈，有趣的玉米。",
		CORN_SEEDS = "長玉米的種子。",
		CROW =
		{
			GENERIC = "我不喜歡鳥。",
			HELD = "他叫得真難聽。",
		},
		CUTGRASS = "我弄了一堆草。",
		CUTREEDS = "我弄了一堆蘆葦。",
		CUTSTONE = "看我劈石作磚！",
		DEADLYFEAST = "看起來像邪惡的食物。",
		DEERCLOPS = "他看起來比我強壯！",
		DEERCLOPS_EYEBALL = "真噁心！",
		DEPLETED_GRASS =
		{
			GENERIC = "是一叢草。",
		},
		DIRTPILE = "骯髒的泥土。",
		DIVININGROD =
		{
			COLD = "機器人盒子在說話。",
			GENERIC = "機器人盒子。",
			HOT = "機器人盒子嚇死我了！",
			WARM = "哈！那真不錯，機器人盒子！",
			WARMER = "機器人盒子要發怒了...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "有什麼用？",
			READY = "魔杖需要鑰匙啟動。",
			UNLOCKED = "魔杖開啟了！",
		},
		DIVININGRODSTART = "古怪的魔杖。",
		DRAGONFRUIT = "樣子古怪的水果。",
		DRAGONFRUIT_COOKED = "熟了，但看起來還是怪怪的。",
		DRAGONFRUIT_SEEDS = "我用這個種古怪的水果。",
		DRAGONPIE = "用奇怪的紅色果實做的餡餅。",
		DRUMSTICK = "腿肉讓腿更強壯。",
		DRUMSTICK_COOKED = "連骨頭都吃掉就好。",
		DUG_BERRYBUSH = "他又冷又孤單。",
		DUG_GRASS = "他又冷又孤單。",
		DUG_MARSH_BUSH = "他又冷又孤單。",
		DUG_SAPLING = "他又冷又孤單。",
		DURIAN = "臭臭的帶刺果實。",
		DURIAN_COOKED = "現在是熱的、臭臭的帶刺果實。",
		DURIAN_SEEDS = "尖刺水果植物的小寶寶。",
		EARMUFFSHAT = "現在我看起來像只小兔子！",
		EARMUFFHAT = "現在我看起來像只小兔子！",
		EGGPLANT = "這不是蛋！",
		EGGPLANT_COOKED = "沒有蛋黃！蛋黃才是最精華的部分！",
		EGGPLANT_SEEDS = "小小的茄子種子。",
		STUFFEDEGGPLANT = "好吃到令其他食物羞愧。",
		EVERGREEN =
		{
			BURNING = "我弄死了它。",
			BURNT = "現在又小又破了。",
			CHOPPED = "哈！我獲勝了！",
			GENERIC = "你好，樹！",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "我弄死了它。",
			BURNT = "現在又小又破了。",
			CHOPPED = "哈！我獲勝了！",
			GENERIC = "開心點，大樹！",
		},
		EYEPLANT = "它們可不像看起來那麼可愛。",
		FARMPLOT =
		{
			GENERIC = "我會在這裡種植強大的農作物！",
			GROWING = "長吧，我的小朋友！快快長大！",
			NEEDSFERTILIZER = "土對農作物來說不夠肥。",
		},
		FEATHERHAT = "傻乎乎的羽毛帽子。沃夫岡現在成了鳥嗎？",
		FEATHER_CROW = "黑鳥的羽毛。",
		FEATHER_ROBIN = "紅鳥的羽毛。",
		FEATHER_ROBIN_WINTER = "白鳥的羽毛。",
		FEM_PUPPET = "恐怖的椅子嚇壞了她！",
		FIREFLIES =
		{
			GENERIC = "閃閃發光！",
			HELD = "我的口袋閃閃發光！",
		},
		FIREHOUND = "汪汪！",
		FIREPIT =
		{
			EMBERS = "黑暗來臨了！",
			GENERIC = "再見了，黑暗時代！",
			HIGH = "火太大了！",
			LOW = "火不夠熱。",
			NORMAL = "好火！",
			OUT = "啊哦。火滅了。",
		},
		FIRESTAFF = "生火的魔杖。當心，沃夫岡。",
		FISH = "真腥。",
		FISHINGROD = "用來從池塘獲得魚肉。",
		FISHSTICKS = "哈哈，有趣的名字。",
		FISHTACOS = "希望對於沃爾夫岡來說不會太辣。",
		FISH_COOKED = "來自水裡的肉也可以讓沃夫岡強壯。",
		FLINT = "是石頭，但是很尖。",
		FLOWER = "它們很美。",
		FLOWERHAT = "太美了！",
		FLOWER_EVIL = "不是土豆。",
		FOLIAGE = "我殺死了美麗的植物。",
		FOOTBALLHELMET = "抱摔專用帽子。",
		FROG =
		{
			DEAD = "在我的國家這就是美味佳餚。",
			GENERIC = "嘿，是小青蛙，青蛙。",
			SLEEPING = "睡著了。",
		},
		FROGLEGS = "在我的國家這就是美味佳餚！",
		FROGGLEBUNWICH = "夾了美味腿肉的三明治。",
		FROGLEGS_COOKED = "味道很像雞肉。",
		FRUITMEDLEY = "一杯水果丁。",
		GEARS = "啊哈！現在誰的肌肉更大？",
		GHOST = "啊！啊！啊！",
		GOLDENAXE = "漂亮的斧頭砍東西更好用。",
		GOLDENPICKAXE = "花俏的鶴嘴鋤鑿東西更好用。",
		GOLDENPITCHFORK = "漂亮的乾草叉扒土更好用。",
		GOLDENSHOVEL = "花俏的鏟子很適合挖洞。",
		GOLDNUGGET = "錢是給小孩的！",
		GRASS =
		{
			BARREN = "它需要施肥。",
			BURNING = "不妙！",
			GENERIC = "是草。",
			PICKED = "草被打敗了！",
		},
		GREEN_CAP = "用來做沙拉的。呸。",
		GREEN_CAP_COOKED = "變得不一樣了。",
		GREEN_MUSHROOM =
		{
			GENERIC = "蘑菇。",
			INGROUND = "蘑菇藏起來了！",
			PICKED = "我已經採了那蘑菇。",
		},
		GUNPOWDER = "烈性胡椒粉！",
		HAMBAT = "還不錯。",
		HAMMER = "再來把鐮刀！",
		HEALINGSALVE = "它讓我感到自己還活著！",
		HEATROCK =
		{
			COLD = "石頭有點冷。",
			GENERIC = "這塊圓石像我的腦袋！",
			HOT = "對沃夫岡來說夠熱了！",
			WARM = "相當普通的石頭。",
		},
		HOMESIGN = "沒空看標誌！",
		HONEY = "好甜！",
		HONEYCOMB = "蜜蜂曾生活在裡面。",
		HONEYHAM = "帶甜味的大肉是好肉。",
		HONEYNUGGETS = "帶甜味的小肉仍是好肉。",
		HORN = "犛牛角。沃夫岡聽到了犛牛的聲音。",
		HOUND = "汪汪！",
		HOUNDMOUND = "骨頭房子。",
		HOUNDBONE = "汪汪叫的弱狗不夠強壯。",
		ICEBOX = "製冷的箱子！",
		ICEHOUND = "汪汪！",
		INSANITYROCK =
		{
			ACTIVE = "擋住我的路了。",
			INACTIVE = "哈。我踩到了小障礙物。",
		},
		JAMMYPRESERVES = "軟泥般的質感，像我在手心捏扁的敵人。",
		KABOBS = "連棍子都吃掉就好。",
		KILLERBEE =
		{
			GENERIC = "憤怒的蜜蜂！",
			HELD = "我的憤怒的蜜蜂！",
		},
		KNIGHT = "像馬的鐵馬！",
		KOALEFANT_SUMMER = "鼻子肉！",
		KOALEFANT_WINTER = "好軟，我要擠扁他！",
		KRAMPUS = "可怕的山羊男！快跑！",
		KRAMPUS_SACK = "我拿到了山羊男的包。",
		LEIF = "木頭人！",
		LEIF_SPARSE = "木頭人！",
		LIGHTNING_ROD =
		{
			CHARGED = "噢，火花！",
			GENERIC = "天上的電線！",
		},
		LITTLE_WALRUS = "你覺得你比成年人更強大？",
		LIVINGLOG = "這木頭長著一張恐怖的臉！",
		LOCKEDWES = "小個子給雕像人困住了。",
		LOG = "跟我的手臂一樣粗。",
		LUREPLANT = "你騙不了沃夫岡！",
		LUREPLANTBULB = "啊哈！現在誰狡猾？",
		MALE_PUPPET = "恐怖的椅子嚇住了他！",
		MANDRAKE =
		{
			DEAD = "植物小人死了！",
			GENERIC = "奇怪的植物。",
			PICKED = "植物小人朋友！",
		},
		COOKEDMANDRAKE = "植物小人是食物？",
		MANDRAKESOUP = "植物小人是用來做湯的！",
		MARBLE = "我能舉起來！",
		MARBLEPILLAR = "太重了，舉不起來。",
		MARBLETREE = "別想用手擊倒這棵樹。",
		MARSH_BUSH =
		{
			BURNING = "啊哦。尖尖的火焰。",
			GENERIC = "好多刺。",
			PICKED = "棘刺刺手。",
		},
		MARSH_PLANT = "是植物。",
		MARSH_TREE =
		{
			BURNING = "我燒掉了尖刺！",
			BURNT = "現在又黑又刺人",
			CHOPPED = "我砍掉了尖刺！",
			GENERIC = "好尖。",
		},
		MAXWELL = "花俏的衣服比不上我的肌肉！",
		MAXWELLHEAD = "可怕的頭有12英尺高！",
		MAXWELLLIGHT = "恐怖的燈！",
		MAXWELLLOCK = "恐怖的鎖！",
		MAXWELLTHRONE = "恐怖的椅子！",
		MEAT = "肉使我強壯！",
		MEATBALLS = "肉丸子讓我更強壯！",
		MEATRACK =
		{
			DONE = "美味，像皮革一樣有嚼勁的肉！",
			DRYING = "曬乾肉！曬乾！",
			GENERIC = "我能曬乾肉！",
		},
		MEAT_DRIED = "看起來像皮革，吃起來像肉。",
		MERM = "魚人！",
		MERMHEAD = "多麼帥氣的惡魔啊！",
		MERMHOUSE = "這屋子不夠結實。",
		MONSTERLASAGNA = "味道像夾雜著毛和肉的麵條。",
		MONSTERMEAT = "看起來不像是食物。",
		MONSTERMEAT_DRIED = "看起來像皮革，吃起來也像皮革。",
		MOSQUITO =
		{
			GENERIC = "讓我想起了叔叔！",
			HELD = "不能再給你吸更多血了！",
		},
		MOSQUITOSACK = "叔叔可沒這樣的膽。",
		MOUND =
		{
			DUG = "對不起了，死去的人們。",
			GENERIC = "怕怕！可能裡邊全是骨頭！",
		},
		NIGHTLIGHT = "發出奇怪的光。",
		NIGHTMAREFUEL = "恐怖的東西。",
		NIGHTSWORD = "真的？不是真的？至少是鋒利的！",
		NITRE = "是石頭，但是不一樣。",
		ONEMANBAND = "又大又響。我喜歡！",
		PANDORASCHEST = "漂亮的箱子！",
		PANFLUTE = "我能演奏民歌。",
		PAPYRUS = "像紙",
		PENGUIN = "滑稽的陸行鳥！",
		PERD = "蠢鳥吃光了所有漿果！",
		PEROGIES = "沃夫岡愛吃餃子！",
		PETALS = "真香。",
		PETALS_EVIL = "它們讓我腦子疼。",
		PICKAXE = "鑿！",
		PIGGYBACK = "臭烘烘的袋子！",
		PIGHEAD = "為什麼一張苦臉？",
		PIGHOUSE =
		{
			FULL = "嘿！出來吧，豬人！",
			GENERIC = "對我來說門太小了。",
			LIGHTSOUT = "他去哪兒了？",
		},
		PIGKING = "哈！他是好人！",
		PIGMAN =
		{
			DEAD = "不！豬死了！",
			FOLLOWER = "現在是朋友了！",
			GENERIC = "你好，豬兄。最近怎麼樣？",
			GUARD = "他練舉重嗎？",
			WEREPIG = "憤怒的小豬！",
		},
		PIGSKIN = "為什麼屁股那麼長？哈哈，沃夫岡真幽默。",
		PIGTORCH = "怎麼點火？",
		PINECONE = 
		{
		    GENERIC = "我能徒手捏碎這些樹的種子！",
		    PLANTED = "它很快就會長成一棵樹。",
		},
		PITCHFORK = "讓我想起了小時候。",
		PLANTMEAT = "這是啥玩意兒？給小孩子吃的肉？",
		PLANTMEAT_COOKED = "現在好一點了。",
		PLANT_NORMAL =
		{
			GENERIC = "枝繁葉茂！",
			GROWING = "還在生長。",
			READY = "嘖~ 現在好吃了。",
		},
		POMEGRANATE = "看起來像是機靈鬼的大腦。",
		POMEGRANATE_COOKED = "哈哈哈！我把它的腦子烤了！現在聰明不起來了。",
		POMEGRANATE_SEEDS = "大腦的組成部分？",
		POND = "全是水。",
		POOP = "真臭！",
		PUMPKIN = "像弱者的腦袋一樣大！不是沃夫岡的腦袋。",
		PUMPKINCOOKIE = "好吃的餅乾。",
		PUMPKIN_COOKED = "我把你的頭烤了，弱小的人！我是最強壯的沃夫岡。",
		PUMPKIN_LANTERN = "現在真的是一個頭了！沃夫岡害怕！",
		PUMPKIN_SEEDS = "這能長出腦袋大小的食物。",
		PURPLEGEM = "更漂亮的石頭。",
		RABBIT =
		{
			GENERIC = "小兔子！躲遠點吧！",
			HELD = "他是我的朋友。",
		},
		RABBITHOLE = "躲得了一時，躲不了一世，你這會跳的肥肉！",
		RAINOMETER = "嘀嘀！嗒嗒！",
		RATATOUILLE = "這是食物。算是吧。",
		RAZOR = "我的皮膚硬的連毛都長不出來！",
		REDGEM = "漂亮的石頭。",
		RED_CAP = "哦！美麗又閃亮！",
		RED_CAP_COOKED = "變得不一樣了。",
		RED_MUSHROOM =
		{
			GENERIC = "蘑菇。",
			INGROUND = "蘑菇藏起來了！",
			PICKED = "我已經採了那蘑菇。",
		},
		REEDS =
		{
			BURNING = "不妙！",
			GENERIC = "水草。",
			PICKED = "我打敗了蘆葦！",
		},
        RELIC = 
        {
            GENERIC = "家居用品。",
            BROKEN = "完全打碎了！",
        },
        RUBBLE = "殘破的房屋瓦礫。",
		RESEARCHLAB = "我不確定我對…科學的感覺。",
		RESEARCHLAB2 = "我不確定我對…科學的感覺。",
		RESEARCHLAB3 = "沃夫岡做了什麼？",
		RESURRECTIONSTATUE = "我不會死的。",
		RESURRECTIONSTONE = "在石頭上跳起舞吧！",
		ROBIN =
		{
			GENERIC = "漂亮的紅鳥。",
			HELD = "裝在口袋裡的快樂小鳥。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "漂亮的白鳥。",
			HELD = "毛茸茸的鳥。好鳥。",
		},
		ROBOT_PUPPET = "恐怖的椅子嚇壞了它！",
		ROCK_LIGHT =
		{
			GENERIC = "一堆帶殼的岩石！",
			OUT = "哈！又有東西可以砸了！",
			LOW = "熔岩在冷卻。",
			NORMAL = "液態的火！",
        },
		ROCK = "真硬！就像我一樣！",
		ROCKS = "是石頭。你還缺什麼？",
        ROOK = "這傢伙可以越過皇后！",
		ROPE = "結實！就像我一樣！",
		ROTTENEGG = "真臭！",
		SANITYROCK =
		{
			ACTIVE = "真美！",
			INACTIVE = "藏在地下。",
		},
		SAPLING =
		{
			BURNING = "哎呀。",
			GENERIC = "弱小的樹！我比你強壯！",
			PICKED = "哈！哈！哈！樹鬆鬆垂垂的！",
		},
		SEEDS = "小得不夠塞牙縫。",
		SEEDS_COOKED = "火讓它們變得更大，現在可以吃了。",
		SEWING_KIT = "會刺到手！",
		SHOVEL = "挖土的勺子！",
		SILK = "太奇特了。",
		SKELETON = "肌肉太少了。",
		SKULLCHEST = "這個人有個大腦袋！",
		SMALLBIRD =
		{
			GENERIC = "非常小的鳥。",
			HUNGRY = "小鳥餓了。",
			STARVING = "小鳥會餓死的。",
		},
		SMALLMEAT = "我要吃更多的肉！",
		SMALLMEAT_DRIED = "看起來像皮革，吃起來像肉。",
		SPEAR = "它給了我一根長木條。",
		SPIDER =
		{
			DEAD = "一肚子黏糊糊的東西！",
			GENERIC = "他有張可怕的臉！",
			SLEEPING = "靜悄悄地走，這樣他可能不會發現我。",
		},
		SPIDERDEN = "蟲子藏在那裡面。",
		SPIDEREGGSACK = "噁心的蜘蛛卵。",
		SPIDERGLAND = "黏黏軟軟的，而且晃來晃去！",
		SPIDERHAT = "像是巨蟲留下的污物。",
		SPIDERQUEEN = "哦，不！會走路的蟲屋！",
		SPIDER_WARRIOR =
		{
			DEAD = "現在不可怕了！",
			GENERIC = "這隻特別可怕。",
			SLEEPING = "去捅它可不太好。",
		},
		SPOILED_FOOD = "真噁心！",
		STATUEHARP = "優美的音樂在哪裡？",
		STATUEMAXWELL = "他現在變成石頭了！非常狡猾...",
		STINGER = "像烤肉叉一樣尖！",
		STRAWHAT = "這帽子不錯！",
		SUNKBOAT = "破船！",
		SWEATERVEST = "帶圖案的背心，適合花花公子。",
		TAFFY = "補充能量的太妃糖！",
		TALLBIRD = "世上最高的鳥！",
		TALLBIRDEGG = "裡面有小鳥。",
		TALLBIRDEGG_COOKED = "烤熟的鳥。當早餐好極了！",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "小鳥冰冰涼！",
			GENERIC = "小鳥想要出來。",
			HOT = "對小鳥來說太熱了！",
			LONG = "我等小鳥出來。",
			SHORT = "小鳥快出來了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "大鳥蛋！",
			PICKED = "空空如也的鳥巢。",
		},
		TEENBIRD =
		{
			GENERIC = "哈！沒那麼高。",
			HUNGRY = "它餓了，不停吵吵。",
			STARVING = "它餓了，不停吵吵還很憤怒！",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我無懼前方的挑戰！",
			GENERIC = "奇怪的石頭。我要坐上去嗎？",
			LOCKED = "還是缺了什麼東西。",
			PARTIAL = "現在都集齊了。",
		},
		TELEPORTATO_BOX = "有小手把。",
		TELEPORTATO_CRANK = "這彎東西是金屬做的！",
		TELEPORTATO_POTATO = "哈哈！哈哈！好醜的土豆！",
		TELEPORTATO_RING = "我會把它彎成完美的圓圈！",
		TENT = "是時候好好睡一覺了。",
		TENTACLE = "瘦長的怪物！",
		TENTACLESPOTS = "真噁心！黏黏的！",
        TENTACLESPIKE = "一釘一個準！",
		TENTACLE_PILLAR = "好多小朋友！",
		TENTACLE_PILLAR = "好多小朋友！",
		TENTACLE_PILLAR_ARM = "小觸手崽子！哈！",
		TENTACLE_GARDEN = "嗯，看著可疑！",
		TOPHAT = "這帽子不錯！",
		TORCH = "我用火把對抗黑夜。",
		TRAP = "沒有陷阱能困住我！",
		TRAP_TEETH = "它會從下面咬屁股！",
		TRAP_TEETH_MAXWELL = "放這個的是個壞蛋！",
		TREASURECHEST = "我把東西放在那裡面！",
		TRINKET_1 = "要我說就是垃圾。",
		TRINKET_10 = "要我說就是垃圾。",
		TRINKET_11 = "要我說就是垃圾。",
		TRINKET_12 = "要我說就是垃圾。",
		TRINKET_2 = "要我說就是垃圾。",
		TRINKET_3 = "要我說就是垃圾。",
		TRINKET_4 = "要我說就是垃圾。",
		TRINKET_5 = "要我說就是垃圾。",
		TRINKET_6 = "要我說就是垃圾。",
		TRINKET_7 = "要我說就是垃圾。",
		TRINKET_8 = "要我說就是垃圾。",
		TRINKET_9 = "要我說就是垃圾。",
		TRUNKVEST_SUMMER = "暖和的毛茸茸的鼻子。",
		TRUNKVEST_WINTER = "裹著這個鼻子真舒服！",
		TRUNK_COOKED = "煮熟的鼻子。",
		TRUNK_SUMMER = "鬆垂的鼻子。",
		TRUNK_WINTER = "鬆垂的毛鼻子。",
		TURKEYDINNER = "鳥肉大餐。",
		TWIGS = "弱小的樹枝！我可以輕鬆地折斷它們！",
		UMBRELLA = "雨水對我健美的皮膚不好。",
		WAFFLES = "為什麼麵包上有孔？",
		WALL_HAY = "牆是用草建成的！",
		WALL_HAY_ITEM = "雜亂的稻草！",
		WALL_STONE = "牆和我一樣壯！",
		WALL_STONE_ITEM = "一堆石頭！",
		WALL_RUINS = "古牆真結實！",
		WALL_RUINS_ITEM = "一堆古老的石頭！",
		WALL_WOOD = "你好，尖木頭！",
		WALL_WOOD_ITEM = "刺人的棍子！",
		WALRUS = "海牛男！",
		WALRUSHAT = "我有海牛男的帽子！",
		WALRUS_CAMP =
		{
			EMPTY = "鎖上了。",
			GENERIC = "他們怎麼鑽進去的？",
		},
		WALRUS_TUSK = "海牛男的牙齒！",
		WASPHIVE = "腦袋說走。身體說上！",
		WETGOOP = "沃夫岡糟蹋了食物！",
		WINTERHAT = "它讓耳朵在冷天很開心！",
		WINTEROMETER = "氣溫降低！紅色下降！",
		WORMHOLE =
		{
			GENERIC = "像個長在地上的軟枕頭。",
			OPEN = "它傷不到我這個漢子！",
		},
 
        ARMORRUINS = "保護我？我不需要！",
        BISHOP_NIGHTMARE = "憤怒的人。應該放鬆放鬆。",
        GREENAMULET = "這是啥玩意兒？", 
        GREENGEM = "漂亮而且壓不碎。就像我一樣！",
        KNIGHT_NIGHTMARE = "滑稽的金屬人。",
        MINOTAUR = "強壯！就像我一樣！我喜歡他！",    
        MULTITOOL_AXE_PICKAXE = "砍砍挖挖！我能持續一整天。",
        NIGHTMARELIGHT = "是燈，但不是什麼好燈。",
        NIGHTMARE_TIMEPIECE =
        {
            WARN = "凶光快來了。",  
            WAXING = "凶光來了並且正在變強。", 
            STEADY = "我覺得凶光沒有變強。", 
            WANING = "凶光時間正在結束。", 
            DAWN = "好時光快來了。", 
            CALM = "沒有凶光。", 
            NOMAGIC = "沒有凶光，安全了。", 
        },
        ORANGESTAFF = "我覺得還是走路好。",  
        ROOK_NIGHTMARE = "比不上我強壯的胸膛！",
        RELIC = "垃圾？",
        RUINS_RUBBLE = "打碎了更好。",  
        RUINS_BAT = "嚇人。",
        RUINSHAT = "給國王戴的帽子。",
        SPIDER_DROPPER = "從天而降的可怕蜘蛛。", 
        THULECITE = "漂亮的石頭。",
        YELLOWAMULET = "發黃光。",    
		ACCOMPLISHMENT_SHRINE = "我會打敗你的，小箭頭！",  
		LIVINGTREE = "我不喜歡有眼睛的樹。",
		ICESTAFF = "尖端結霜了。",              
	},
	DESCRIBE_GENERIC = "這是啥玩意兒？",
	DESCRIBE_TOODARK = "救救我！太黑了！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "這蛋太容易碎了。",
	},
}
