return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Ich glaube nicht, dass es das zulassen wird.",
			GENERIC = "Ende.",
			NOBITS = "Aber es ist schon so glatt wie ein Baby-Popo.",
		},
		STORE =
		{
			GENERIC = "Das würde nicht passen.",
			NOTALLOWED = "Das kann da nicht rein.",
		},
		WRITE =
        {
            GENERIC = "Das kann ich im Moment nicht tun.",
        },
		RUMMAGE =
		{	
			GENERIC = "Verflucht.",	
		},
		COOK =
        {
            GENERIC = "Es läuft nie nach Plan.",
            TOOFAR = "Ich muss näher dran, nicht wahr?",
        },
        CHANGEIN =
        {
            GENERIC = "Wie lässt sich etwas perfektes noch verbessern?",
            BURNING = "Oh nein. Meine schönen Einstecktücher...",
        },
        GIVE =
        {
            DEAD = "DAS BRAUCH ICH NICHT.",
            SLEEPING = "Bekommt nichts mit.",
            BUSY = "Gerade beschäftigt.",
        },
        TEACH =
        {
            KNOWN = "Es ist zu weit draußen. Ich kann es nicht mal anzünden!",
            CANTLEARN = "Daraus müssen wir unsere Lehren ziehen.",
        },
		REPAIRBOAT =
		{
			GENERIC = "Da ist gerade beschäftigt.",
		},

	},
	ACTIONFAIL_GENERIC = "Das funktionierte nicht.",
	ANNOUNCE_MAGIC_FAIL = "Solche Magie gehört nicht hierher.",
    ANNOUNCE_NOSLEEPONFIRE = "Das ist vermutlich nicht die beste Idee.",
	ANNOUNCE_NODANGERSIESTA = "Sie sind mir auf den Fersen!",
	ANNOUNCE_NONIGHTSIESTA = "Es ist Schlafenszeit, nicht Siestazeit.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Es ist ein bisschen zu unheimlich dafür.",
	ANNOUNCE_NOHUNGERSIESTA = "Traditionell findet eine Siesta nach dem Essen statt, nicht davor.",
	ANNOUNCE_SHELTER = "Beschütze mich, Baum!",
	ANNOUNCE_BURNT = "Es brennt!",
	ANNOUNCE_TOOL_SLIP = "Zum Teufel! Das wird nicht brennen.",
	ANNOUNCE_DAMP = "Feuchtigkeit ist nicht modisch.",
	ANNOUNCE_WORMS = "Schrecklich!",
	ANNOUNCE_WET = "Wasser ruiniert einen guten Anzug, verstehst du?",
	ANNOUNCE_WETTER = "Ich glaube nicht, dass ich jemals wieder trocken werde.",
	ANNOUNCE_SOAKED = "Nasser als Wasser selbst.",
	ANNOUNCE_ADVENTUREFAIL = "Von allen Leuten, sollte ich in der Lage sein, das zu tun.",
	ANNOUNCE_BEES = "Wenn du mich tötest, bringt dir das deinen Honig auch nicht zurück.",
	ANNOUNCE_BOOMERANG = "Oh! Ungeschickt!",
	ANNOUNCE_CHARLIE = "Charlie? Ich bin's! Maxwell!",
	ANNOUNCE_CHARLIE_ATTACK = "Au! Charlie, das tut weh!",
	ANNOUNCE_COLD = "Mein Herz wird kalt.",
	ANNOUNCE_HOT = "Mein Herz kann der Hitze nicht standhalten!",
	ANNOUNCE_CRAFTING_FAIL = "Äh... Ich kann das nicht.",
	ANNOUNCE_DEERCLOPS = "Ich höre einen von ihnen kommen.",
	ANNOUNCE_DUSK = "Es wird bald dunkel. Charlie wird aufwachen.",
	ANNOUNCE_EAT =
	{
		GENERIC = "(Schluck!)",
		PAINFUL = "Au! Das hat in meinem Mund wehgetan!",
		SPOILED = "Das war verwest.",
		STALE = "Das Mindesthaltbarkeitsdatum war überschritten.",
		INVALID = "Das werde ich nicht in die Nähe meines Mundes lassen.",
		YUCKY = "Ein zivilisierter Mensch isst nicht solche Dinge.",  
	},
	ANNOUNCE_ENTER_DARK = "Es ist dunkel! Ich kann nichts sehen!",
	ANNOUNCE_ENTER_LIGHT = "Das Licht ist zurück.",
	ANNOUNCE_FREEDOM = "Freiheit, immerhin!",
	ANNOUNCE_HIGHRESEARCH = "Mein Hirn schwillt durch die Macht an.",
	ANNOUNCE_HOUNDS = "Die Hunde wachsen unablässig.",
	ANNOUNCE_HUNGRY = "Ich bin innen leer.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Ich rieche Dung und Bestienschweiß.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Verflixt! Es ist entwischt.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Unter diesen Umständen kann ich der Spur nicht folgen!",
	ANNOUNCE_INV_FULL = "Meine Taschen sind voll.",
	ANNOUNCE_KNOCKEDOUT = "Uhh. Mein Kopf tut weh.",
	ANNOUNCE_LOWRESEARCH = "Das war nicht sehr informativ.",
	ANNOUNCE_MOSQUITOS = "Was für kleine nervige Käfer.",
	ANNOUNCE_NODANGERSLEEP = "Nicht, solange Gefahr besteht!",
	ANNOUNCE_NODAYSLEEP = "Tagsüber kann ich nicht schlafen.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Es würde meinen Zeitplan durcheinander bringen, wenn ich jetzt schlafe.",
	ANNOUNCE_NOHUNGERSLEEP = "Ich bin zu hungrig. Ich kann nicht schlafen.",
	ANNOUNCE_NO_TRAP = "Seltsam. Sie haben vergessen sie zu aktivieren.",
	ANNOUNCE_PECKED = "Hab Geduld!",
	ANNOUNCE_QUAKE = "Dieses Rumpeln kann nicht gut sein.",
	ANNOUNCE_RESEARCH = "Wissen ist Macht. Und Macht ist... nun, Macht.",
	ANNOUNCE_THORNS = "Ich habe mir meine Arme zerkratzt, als ich das getan habe.",
	ANNOUNCE_TORCH_OUT = "Verdammt. Ein weiteres Licht ist aus.",
	ANNOUNCE_FAN_OUT = "Das war's dann wohl.",
	ANNOUNCE_COMPASS_OUT = "Der Kompass ist in Stücke gefallen.",
	ANNOUNCE_TRAP_WENT_OFF = "Positiv!",
	ANNOUNCE_UNIMPLEMENTED = "Hmmm, nicht ganz fertig.",
	ANNOUNCE_WORMHOLE = "Igitt! Dort drinnen ist es entsetzlich.",
	ANNOUNCE_CANFIX = "\nIch glaub, ich kann das reparieren!",
	ANNOUNCE_NOSANITY = "Ich habe Kopfschmerzen.",
	ANNOUNCE_NOFUEL = "Ich brauche etwas Albtraum-Kraftstoff.",
	ANNOUNCE_NOWARDROBEONFIRE = "Du bist verrückt!",
	ANNOUNCE_ACCOMPLISHMENT= "Ich muss die irgendwie Zeit überdauern.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Das macht es alles irgendwie lohnenswert.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Das hat es nur ein klein wenig aufgewertet.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Kann ich nicht anfassen!",
	ANNOUNCE_OTHER_WORLD_PLANT = "Ich kann das hier nicht anpflanzen.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Die Handschrift ist fürchterlich. Ich kann das nicht entziffern.",
	},
	ANNOUNCE_BOAT_DAMAGED = "Mein Schiff für Meeresforschung.",
	ANNOUNCE_BOAT_SINKING = "Ich glaube, ich hab ein Leck.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Soll das so enden?",
	ANNOUNCE_CRAB_ESCAPE = "Gewieftes Krustentier...",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Wieder einmal verschlingt mich der Abgrund!",
	ANNOUNCE_MAPWRAP_RETURN = "Gott sei Dank!",
	ANNOUNCE_MAPWRAP_WARN = "Ich will nichts mit Dunst und Nebel zu tun haben.",
	ANNOUNCE_MORETREASURE = "Ach, noch so eine Karte zu einem versteckten Schatz.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Ich glaube nicht, dass dieser Schatz hier in der Nähe ist.",
	ANNOUNCE_SHARX = "Hilfe! Ich werde entführt.",
	ANNOUNCE_TRAWL_FULL = "Mein Netz ist voll!",
	ANNOUNCE_TREASURE = "Das führt scheinbar zu irgendeinem... Schatz.",
	ANNOUNCE_VOLCANO_ERUPT = "Brauche... Eis... oder... Schatten!",
	ANNOUNCE_WAVE_BOOST = "Wirklich!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "DAS RUDER DER BESTIE.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Fischen",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Ich habe die Spur in diesen turbulenten Gewässern verloren!",

	BATTLECRY =
	{
		GENERIC = "Zu den Waffen!",
		PIG = "Verstand über Muskeln!",
		PREY = "Du siehst lecker aus!",
		SPIDER = "Nächstes Mal lass ich mich nicht mehr zum Narren machen!",
		SPIDER_WARRIOR = "Du hast meine Hand geführt.",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Und bleib weg!",
		PIG = "Nächstes Mal, Schwein!",
		PREY = "Du bist meine Zeit nicht wert!",
		SPIDER = "Nächstes Mal lass ich mich nicht mehr zum Narren machen!",
		SPIDER_WARRIOR = "Nächstes Mal ohne Handschuhe.",
	},
	
	DESCRIBE =
	{
		LICHEN = "A slow growing cave plant.",
		ICEHOUND = "Die brennen schnell!",
		INVENTORYGRAVE = "Ich frage mich, wem das mal gehört hat.",
		INVENTORYMOUND = "Sie hat schon wieder ein Opfer gefordert.",
		GLOMMER = "Eine fliegende Kleberfabrik.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Blumenkraft.",
        	DEAD = "Blumenkraft für immer.",
        },
        GLOMMERWINGS = "Die sind klebrig.",
        GLOMMERFUEL = "Also, das ist widerlich.",
        BELL = "Eine weitere Glocke.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Hey, das ist keine Statue von mir!",
        	EMPTY = "Das wird sie lehren, nicht ich zu sein.",
    	},
		WEBBERSKULL = "Glaube nicht, dass es einfach für dich sein wird von hier zu entkommen.",
		MOLE =
		{
			HELD = "Endstation.",
			UNDERGROUND = "Sag mal, hebst du aus, was ich fallen lasse?",
			ABOVEGROUND = "Das deute ich als ein 'Ja'.",
		},
		MOLEHILL = "Grab dich tief ein, ich werde dich holen.",
		MOLEHAT = "Kein Wunder, dass sie stundenlang graben können.",
		NIGHTSTICK = "Guten Morgen.",
		RABBITHOUSE=
		{
			GENERIC = "Oh, ist das nicht clever?",
			BURNT = "Klugheit tötete die Karotte.",
		},
		TURF_DECIDUOUS = "Erdboden.",
		TURF_SANDY = "Erdboden.",
		TURF_BADLANDS = "Erdboden.",
		BEARGER = "Nimm alles, was du willst.",
		BEARGERVEST = "Schaut euch meine Weste an.",
		ICEPACK = "Die Dinge im Inneren überwintern.",
		BEARGER_FUR = "Das würden einen netten Teppich abgeben.",
		BIGFOOT = "Nun, das ist wirklich Stoff für Albträume.",
		BONESHARD = "Ihre Knochen wurde zermahlt.",
		BUZZARD = "Liebhaber von Aas.",
		CACTUS = 
		{
			GENERIC = "Windbeutel-Pflanze.",
			PICKED = "Kaktus? Sieht mehr wie ein Flach-tus aus!",
		},
		CACTUS_MEAT_COOKED = "Essbarer Kaktus.",
		CACTUS_MEAT = "Es wäre nicht weise, wenn man das in den Mund nehmen würde.",
		CACTUS_FLOWER = "Dieser Teil eines Kaktus ist immer hübsch.",
		COLDFIRE =
		{
			EMBERS = "Ich werde es verlieren.",
			GENERIC = "Wie beruhigend.",
			HIGH = "Das wird Charlie von mir fernhalten.",
			LOW = "Es braucht Brennstoff.",
			NORMAL = "Kalte und feurig.",
			OUT = "Es wird nicht zurück kommen.",
		},
		CATCOON = "Heimtückisches Ungeziefer.",
		CATCOONDEN = 
		{
			GENERIC = "Ungezieferunterkunft.",
			EMPTY = "Nun, ich nehme an, so ist es.",
		},
		CATCOONHAT = "Totenkopf.",
		COONTAIL = "Geschichten von Schwänzen.",
		COOKPOT =
		{
			COOKING_LONG = "Warte drauf...",
			COOKING_SHORT = "Hier kommt es!",
			DONE = "Endlich, ein qualitativ hochwertiges Essen.",
			EMPTY = "Allein der Gedanke daran, macht mir den Mund wässrig.",
			BURNT = "Für meine Geschmack ein bisschen übertrieben.",
		},
		EYEBRELLAHAT =	"Auge zum Himmel.",
		ARMORDRAGONFLY = "Das ist eine Fliegenrüstung.",
		DRAGON_SCALES = "Feurig.",
		DRAGONFLYCHEST = "Diese Schuppen sind wirklich hübsch.",
		DECIDUOUSTREE = 
		{
			BURNING = "Hoppla.",
			BURNT = "In Feuer gebadet.",
			POISON = "Halt den Rand!",
			CHOPPED = "Er scheint nicht wieder nachzuwachsen.",
			GENERIC = "Ich hörte, wie sie ihn als 'belaubt' beschreiben.",
		},
		ACORN_COOKED = "Über einem offenen Feuer.",
		BIRCHNUTDRAKE = "Eine Nuss mit Beinen! Wie entsetzlich!",
		FARMPLOT =
		{
			GENERIC = "Sehe ich wie ein Bauer aus?",
			GROWING = "Ich habe bessere Dinge zu tun, als den Pflanzen beim Wachsen zuzuschauen.",
			NEEDSFERTILIZER = "Sie muss... aufgefrischt werden.",
			BURNT = "Die Ernte von Asche.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Ich sollte mich darum kümmern.",
			GENERIC = "Eine Feuerstelle.",
			HIGH = "Ein tosendes, kaltes Feuer.",
			LOW = "Es wird kleiner.",
			NORMAL = "Es ist kalt.",
			OUT = "Es ist warm geworden.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Hinfort, Feuer!",
			OFF = "Ruhe vor dem Sturm.",
			LOWFUEL = "Nicht mehr viel Kraftstoff übrig.",
		},
		ICEHAT = "Schnall dir etwas Eis auf deinen Kopf.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Worauf kaut es immer rum?",
			CHARGED = "Attacke!",
		},
		LIGHTNINGGOATHORN = "Das ist ein nettes Horn.",
		GOATMILK = "Er ist mit Nährstoffen geladen.",
		MEATRACK =
		{
			DONE = "Wie die Wüste.",
			DRYING = "Immer noch feucht.",
			DRYINGINRAIN = "Feucht und das bleibt es auch.",
			GENERIC = "Es wird zum Trocknen von Fleisch genutzt, damit es länger hält.",
			BURNT = "Es ist zu brüchig, um jetzt noch Fleisch darauf aufzuhängen.",
		},
		MERMHEAD = 
		{
			GENERIC = "Die Augen folgen einem noch.",
			BURNT = "Gebratener Mermkopf. Köstlich.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Sie imitieren die Schweine, sind aber weit weniger intelligent.",
			BURNT = "Er brennt genauso gut, wie die Version von den Schweinen.",
		},
		FLOWERSALAD = "Laubige Güte.",
        ICECREAM = "Eisbecher, Eisbecher, Eisbecher!",
        BANANAPOP = "Ich weiß nicht genau, was das für ein Ding ist.",
        BISQUE = "Ausgezeichnetes Essen, aber das Ambiente könnte verbessert werden.",
        CEVICHE = "Ein wunderbares Gericht.",
        SEAFOODGUMBO = "Sieht unterernährt aus.",
        SURFNTURF = "Eine sehr ausgewogene Mahlzeit.",
        SHARKFINSOUP = "Mein verwöhnter Gaumen liebt den Geschmack der Gefahr.",
        LOBSTERDINNER = "Ich hab mein Lätzchen vergessen.",
        LOBSTERBISQUE = "Ach, ich genieße die schönen Dinge.",
        JELLYOPOP = "Hm, ich glaub, das passt nicht so ganz zum kultivierten Look.",
        WATERMELONICLE = "Die Hülle um die Melone ist kalt.",
        TRAILMIX = "Nüsse und Beeren. Keine Schrauben.",
        HOTCHILI = "Heiß wie die Hölle!",
        GUACAMOLE = "Da ist ein Maulwurf drin.",
		MOOSE = "Was auch immer es ist, es stammt definitiv aus dem Norden.",
		MOOSEEGG = "Reite den Blitz, du riesiges Ei.",
		MOSSLING = "Das ist ein flauschiges... Ding.",
		FEATHERFAN = "Ist es windig draußen oder ist das nur mein Ventilator?",
		TROPICALFAN = "Ist es windig draußen oder ist das nur mein Ventilator?",
		GOOSE_FEATHER = "Ich könnte ein Kissen gebrauchen, das damit gefüllt ist.",
		STAFF_TORNADO = "Windkraft.",
		PIGHEAD = 
		{	
			GENERIC = "Äh... wie charmant.",
			BURNT = "Schweinebraten!",
		},
		PIGHOUSE =
		{
			FULL = "Ich würde auch hineingehen, wenn ich ein Schwein wäre.",
			GENERIC = "Geräusche und Wut!",
			LIGHTSOUT = "Ich werde das Schweinehaus wegpusten.",
			BURNT = "Ich bin gespannt, wie sich jetzt darin verstecken wollen.",
		},
		FERTILIZER = "Es gehört sich wirklich nicht, Mist in den Händen zu tragen.",
		RAINOMETER = 
		{	
			GENERIC = "Ich kann auch einfach nach oben schauen, um dasselbe hervorzusagen.",
			BURNT = "Der Regen kam nicht rechtzeitig.",
		},
		RAINCOAT = "Das war's, Regen!",
		RAINHAT = "Nicht der eleganteste Hut, aber dennoch unerlässlich.",
		RESEARCHLAB = 
		{	
			GENERIC = "Ich kann nicht glauben, dass ich vergessen habe, wie man diese Dinge baut.",
			BURNT = "Das Feuer hat gelernt, wie es die Maschine verbrennen kann.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Es schaltet Rezepte für durchschnittliche Versorgungseinrichtungen frei.",
			BURNT = "Die Flammen haben sie komplett verzehrt.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Hier betreibe ich meine persönliche Forschung.",
			BURNT = "Forschung abgeschlossen.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Ziemlich schmucke Maschine.",
			BURNT = "Das war wohl zu heiß, um es auszuhalten.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Ich bin mir nicht zu schade, die zu verwenden.",
			BURNT = "Ich will die nicht länger benutzen.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Ich könnte davon einen Eissplitter abschlagen.",
			MELTED = "Er ist nur noch eine Pfütze.",
		},
		ROCK_ICE_MELTED = "Er ist nur noch eine Pfütze.",
		ICE = "Babygletscher.",
        REFLECTIVEVEST = "Sicherheit vor Eleganz.",
		HAWAIIANSHIRT = "Das eleganteste von ihnen allen.",
		TENT = 
		{
			GENERIC = "Das ist für meinen Geschmack ein bisschen zu rustikal.",
			BURNT = "Das ist für meinen Geschmack ein bisschen zu verbrannt.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Rustikal, aber ein exzellenter Sonnenschutz.",
			BURNT = "Zu viel für das Schattending.",
		},
		TRANSISTOR = "Ich verstehe zwar nicht, wie das funktioniert, aber das tut es.",
		TREASURECHEST = 
		{
			GENERIC = "Ein Platz, um Beute zu lagern.",
			BURNT = "Jetzt lagert sie nichts mehr.",
		},
		TUMBLEWEED = "Roll weiter, Unkraut.",
		GRASS_UMBRELLA = "Er ist hübscher als hübsch.",
		PALMLEAF_UMBRELLA = "ES DIENT MIR.",
		UNIMPLEMENTED = "Mysteriös! Das fasse ich lieber nicht an.",
		WALL_HAY = 
		{	
			GENERIC = "Das ist ein Pulverfass.",
			BURNT = "Ich hab's dir gesagt.",
		},
		WALL_WOOD = 
		{
			GENERIC = "Halbwegs widerstandsfähig, aber leicht entzündlich.",
			BURNT = "Weder widerstandsfähig noch entzündlich.",
		},
		WARG = "Das Alphatier!",
		WATERMELON = "Es ist hauptsächlich Wasser. Faseriges, süßes Wasser.",
		WATERMELON_COOKED = "Grillmelone.",
		WATERMELONHAT = "Das ist eine Möglichkeit, um einen kühlen Kopf zu bewahren. Und klebrig zu sein.",
		WINTEROMETER = 
		{
			GENERIC = "Nicht die hilfreichste Erfindung, oder?",
			BURNT = "Wen kümmert's?",
		},
		LIVINGTREE = "Er hat ein Gesicht.",
		ICESTAFF = "Cooler Stab.",
		WAXWELLJOURNAL = "Es tut mir so Leid, Charlie.",
		WORMLIGHT = "Netter Trick.",
		WORM =
		{
		    PLANT = "Du legst mich nicht herein, Pflanze.",
		    DIRT = "Da rührt sich etwas.",
		    WORM = "Hm, das ist neu!",
		},
		EEL = "Die existieren nur in den Tiefen.",
		EEL_COOKED = "Wie das herumschlittert.",
		UNAGI = "Das muss reichen.",
		EYETURRET = "Eine meiner besseren Arbeiten.",
		EYETURRET_ITEM = "Jetzt muss ich ihn nur noch aufstellen.",
		MINOTAURHORN = "Tut mir leid, dass ich das tun musste, alter Freund.",
		MINOTAURCHEST = "Es ist fast so, als wäre er noch am Leben.",
		THULECITE_PIECES = "Ich könnte mehrere Haufen kombinieren, um ein größeres Stück zu bekommen.",
		POND_ALGAE = "Das ist eine Alge.",
		GREENSTAFF = "Ich muss den Stab auf die richtige Art und Weise benutzen, damit er funktioniert.",
		POTTEDFERN = "Wie idyllisch.",

		THULECITE = "Ein überaus seltenes aber nützliches Material.",
		ARMORRUINS = "Thulecite passt so gut zu Albtraum-Kraftstoff.",
		RUINS_BAT = "Sie ist von Kraftstoff durchdrungen.",
		RUINSHAT = "Kraftstoff muss fließen.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Das Stadtzentrum bleibt.",	--calm phase
			WARN = "Er pulsiert noch.",	--Before nightmare
			WAXING = "Die Impuls wird schneller.", --Nightmare Phase first 33%
			STEADY = "Der Impuls ist anhaltend.", --Nightmare 33% - 66%
			WANING = "Die Impuls schwindet.", --Nightmare 66% +
			DAWN = "Er beruhigt sich wieder.", --After nightmare
			NOMAGIC = "Der Impuls zeigt hier keine Einflüsse.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "Sie zerfallen ohne eine angemessene Wartung.",
		ROOK_NIGHTMARE = "Die Erbauer haben es dem Zustand der Herrenlosigkeit überlassen.",
		KNIGHT_NIGHTMARE = "Scheint nicht reparierbar zu sein.",
		MINOTAUR = "Sieh an, sieh an. Der Stoff hat dich verändert.",	--Monster in labyrinth
		SPIDER_DROPPER = "Die Kreaturen in dieser Welt entwickeln sich in einem erschreckenden Tempo.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Die Überbeanspruchung des Kraftstoffs war ihr Untergang.",	--Lights that activate during nightmare.
		RELIC = "They were all dead when I got here.",	--Fixed relic
		RUINS_RUBBLE = "The earthquakes have taken their toll.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "Ich weiß nicht, wieso ich nicht daran gedacht habe.",	--Works as axe and pickaxe
		GREENGEM = "Der Albtraum-Kraftstoff wird sein wahres Potential freisetzen.",
		ORANGESTAFF = "Ich muss den Stab auf die richtige Art und Weise benutzen, damit er funktioniert.",	--Teleports player.
		YELLOWAMULET = "Das wird mich auffallen lassen.",	--Emits light, player walks faster.
		GREENAMULET = "Normalerweise brauch ich das ehrlich nicht.",	--Reduce cost of crafting

		SLURPER = "Einfache Kreaturen. Sie existieren nur zum Schlafen und Fressen.",
		SLURPER_PELT = "Diese Kreatur wird mir im Tode dienen.",
		ARMORSLURPER = "Nass, durchweicht und komischerweise sättigend.",
		ORANGEAMULET = "Einfache Magie ist oft die beste.",
		YELLOWSTAFF = "Mit einem größeren Edelstein würde er noch mächtiger sein.",
		YELLOWGEM = "Ich kann seine Magie spüren.",
		ORANGEGEM = "Mit ein wenig Kraftstoff wird er noch mächtiger.",
		TELEBASE = 
		{
			VALID = "Das sollte seinen Zweck erfüllen.",
			GEMS = "Die Kraft benötigt mehr Fokuspunkte.",
		},
		GEMSOCKET = 
		{
			VALID = "Er ist bereit.",
			GEMS = "Der Stoff braucht ein Nutzen.",
		},
		STAFFLIGHT = "Das sollte die Schatten verjagen.",
       	ANCIENT_ALTAR =
        {
        	WORKING = "Where are their gods now?",
        	BROKEN = "This can be partially restored.",
        },
        ANCIENT_ALTAR = "Wo sind ihre Götter jetzt?",
        ANCIENT_ALTAR_BROKEN = "Der kann teilweise wiederaufgebaut werden.",

        ANCIENT_STATUE = "Eine ehemals stolze Rasse.",

		CAVE_BANANA = "Als hätte man Asche im Mund.",
		CAVE_BANANA_COOKED = "Sogar noch schlechter als eine rohe Banane.",
		CAVE_BANANA_TREE = "Sieht zwar aus wie eine Banane, aber das kaufe ich ihm nicht ab.",
		ROCKY = "Ich habe diese Typen aus gutem Grund hier runter verbannt.",
		
		HOUNDSTOOTH="Er könnte für die Mode genutzt werden.",
		ARMORSNURTLESHELL="Die ist überhaupt nicht elegant.",
		BAT="Igitt. Hässliches Biest.",
		BATBAT = "Gewalt hat sich noch nie besser angefühlt.",
		BATWING="Das esse ich nicht.",
		BATWING_COOKED="Das esse ich immer noch nicht.",
		BEDROLL_FURRY="Wenigstens ist es für etwas gut.",
		BUNNYMAN="Er erinnert mich an einen alten",
		FLOWER_CAVE="Es ist so dunkel hier unten.",
		FLOWER_CAVE_DOUBLE="Es ist so dunkel hier unten.",
		FLOWER_CAVE_TRIPLE="Es ist so dunkel hier unten.",
		GUANO="Widerlich!",
		LANTERN="Ich hoffe, das wird sie fernhalten.",
		LIGHTBULB="Es wird irgendwann ausgehen.",
		MANRABBIT_TAIL="Dummes Kaninchen.",
		MUSHTREE_TALL="Er riecht nach Fäule und Versagen.",
		MUSHTREE_MEDIUM="Wo ist Waldo?",
		MUSHTREE_SMALL="Uh, der riecht schlecht.",
		SLURTLE="An die kann ich mich nicht erinnern...",
		SLURTLE_SHELLPIECES="Sie passen nicht wieder zusammen.",
		SLURTLEHAT="Der lässt mich standhaft bleiben, wenn ich kämpfen muss.",
		SLURTLEHOLE="Das ist ekelhaft.",
		SLURTLESLIME="Es muss einen besseren Weg geben.",
		SNURTLE="Das ist seltsam. Die müssen neu sein.",
		SPIDER_HIDER="Die ist trickreich.",
		SPIDER_SPITTER="Aggressives kleines Ding, nicht wahr?",
		SPIDERHOLE="Wie ist das hier runter gekommen?",
		STALAGMITE="Steine. Wie dumm.",
		STALAGMITE_FULL="Steine. Wie dumm.",
		STALAGMITE_LOW="Steine. Wie dumm.",
		STALAGMITE_MED="Steine. Wie dumm.",
		STALAGMITE_TALL="Stalagmit. Wie dumm.",
		STALAGMITE_TALL_FULL="Stalagmit. Wie dumm.",
		STALAGMITE_TALL_LOW="Stalagmit. Wie dumm.",
		STALAGMITE_TALL_MED="Stalagmit. Wie dumm.",

		POWCAKE = "Bleib zurück, verdorbener Diener des Bösen!",
		CAVE_ENTRANCE = 
		{
			GENERIC= "Ich habe sie vor langer Zeit zugestopft.",
			OPEN = "Das war keine gute Idee!",
		},
        CAVE_EXIT = "Holt mich hier raus!",

		MAXWELLPHONOGRAPH = "Dieses verfluchte Ding!",
		BOOMERANG = "Der macht die Hände schmutzig.",
		PIGGUARD = "Igitt. Widerliches Vieh.",
		ABIGAIL = "Warum bleiben die Sterblichen nicht einfach tot?",
		ADVENTURE_PORTAL = "Hier habe ich das Ding also gelassen!",
		AMULET = "Es leitet die dunkelsten Energien des Universums.",
		ANIMAL_TRACK = "Irgendein dummes Vieh ist hier lang gegangen.",
		ARMORGRASS = "Eine direkte Konfrontation ist ziemlich tölpelhaft.",
		ARMORMARBLE = "Das ist wirklich nicht mein Stil.",
		ARMORWOOD = "Uh. Ich bin kein Freund von solchen geschmacklosen Handgreiflichkeiten.",
		ARMOR_SANITY = "Zeit, um mich mit Alpträumen zu umhüllen.",
		ASH =
		{
			GENERIC = "Ein schönes Pulver, das nach Zerstörung riecht.",
			REMAINS_GLOMMERFLOWER = "Es gibt immer einen weiteren Glommer.",
			REMAINS_EYE_BONE = "Keine Sorge. Es gibt noch mehr Chesters.",
			REMAINS_THINGIE = "Nach meiner Reise durch das Portal ist es nicht mehr zu erkennen.",
		},
		AXE = "Manchmal ist die direkte Vorgehensweise am besten.",
		BABYBEEFALO = "Sie sind sogar als Kinder hässlich.",
		BACKPACK = "Ich wünschte, es würde hier Träger geben.",
		BACONEGGS = "Das ist ein angemessene Winterkleidung.",
		BANDAGE = "Klebrig und pampig. Gut, um es auf Wehwehchen zu legen.",
		BASALT = "Ich habe den Stein so schwer gemacht, dass ich ihn nicht mehr anheben kann.",
		BEARDHAIR = "Haarig.",
		BEDROLL_STRAW = "Ich mag es nicht, hart zu schlafen.",
		BEE =
		{
			GENERIC = "Sie arbeiten so hart, die Narren.",
			HELD = "Was mache ich jetzt damit?",
		},
		BEEBOX =
		{
			FULLHONEY = "So verlockend, aber so voll mit Bienen.",
			GENERIC = "Sie beherbergt meine Bienen.",
			NOHONEY = "Meine Bienen arbeiten nicht hart genug.",
			SOMEHONEY = "Ein sollte ein wenig länger warten.",
			BURNT = "Gerösteter Honig.",
		},
		BEEFALO =
		{
			FOLLOWER = "Verdammt, er folgt mir.",
			GENERIC = "Schau dir nur dieses dumme Biest an.",
			NAKED = "Jetzt sieht er dumm UND mitleiderregend aus.",
			SLEEPING = "Er ist nur geringfügig schlauer, wenn er schläft.",
		},
		BEEFALOHAT = "Wie unmodisch.",
		BEEFALOWOOL = "Die riecht wie eine Scheune.",
		BEEHAT = "Ich werde ihn tragen, wenn ich muss.",
		BEEHIVE = "Nicht die Bienen!",
		BEEMINE = "Sie warten geduldig.",
		BEEMINE_MAXWELL = "Vielleicht hätte ich die nicht dort hinlegen sollen.",
		BERRIES = "Seufz. Ich muss.",
		BERRIES_COOKED = "Immerhin ein bisschen verfeinert.",
		BERRYBUSH =
		{
			BARREN = "Er braucht Dünger.",
			WITHERED = "Zu heiß für diesen kleinen Busch.",
			GENERIC = "Aufs Beerenessen reduziert. Seufz.",
			PICKED = "Und nun warten wir.",
		},
		BIRDCAGE =
		{
			GENERIC = "Man wird mich nie wieder hinter Gitter bringen.",
			OCCUPIED = "Ich fühle mit dir.",
			SLEEPING = "Du wirst immer noch da drin sein, wenn du wieder aufwachst.",
			HUNGRY = "Was soll das Gegackere?",
			STARVING = "Ich hab dich doch erst letzte Woche gefüttert!",
			DEAD = "In der Tiefe lauert etwas.",
			SKELETON = "Ist er tot? Nein. Schläft nur.",
		},
		BIRDTRAP = "Sie werden weiter darauf reinfallen.",
		BIRD_EGG = "Ich betrachte es gern als ein Gefängnis für Babyvögel.",
		BIRD_EGG_COOKED = "Spiegelei.",
		BISHOP = "Auf diese Stück bin ich besonders stolz.",
		BLOWDART_FIRE = "Sei einfach nur sicher, dass du auch ausatmest.",
		BLOWDART_SLEEP = "Nenn mich Sandmann.",
		BLOWDART_PIPE = "Ein wunderbares Rohr, um Schmerzen auszuteilen.",
		BLUEAMULET = "Es ist überfroren.",
		BLUEGEM = "Blau bewirkt Eis.",
		BLUEPRINT = "Ich weiß alles darüber. Ich habe es nur vergessen.",
		BELL_BLUEPRINT = "Ich weiß alles darüber. Ich habe es nur vergessen.",
		BLUE_CAP = "Was kann schon schiefgehen?",
		BLUE_CAP_COOKED = "Umami!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Die blauen sind für irgendwas gut.",
			INGROUND = "Er ist nicht bereit.",
			PICKED = "Vielleicht ein anderes Mal?",
		},
		BOARDS = "Ungehobelt.",
		BOAT = "Das fährt nirgendwo mehr hin.",
		BONESTEW = "Der wird seine Spuren hinterlassen.",
		BUGNET = "Perfekt, um wehrlose Insekten zu fangen.",
		BUSHHAT = "Für mich gibt es hier Verbesserungspotential.",
		BUTTER = "Einige Wortspiele sind unwiderstehlich.",
		BUTTERFLY =
		{
			GENERIC = "Eine fliegende Blüte.",
			HELD = "Es wäre eine Schande, wenn jemand seine Flügel abreißen würde.",
		},
		BUTTERFLYMUFFIN = "Damit sollte das nervige Flattern aufhören.",
		BUTTERFLYWINGS = "Hahaha. Ich hab ihn!",
		CAMPFIRE =
		{
			EMBERS = "Ich werde es verlieren.",
			GENERIC = "Wie beruhigend.",
			HIGH = "Das wird Charlie von mir fernhalten.",
			LOW = "Es braucht Brennstoff.",
			NORMAL = "Feurig.",
			OUT = "Es wird nicht zurück kommen.",
		},
		CANE = "In ihm sind Bilder von schnellen Dingen eingeritzt.",
		CARROT = "Ich bin kein Fan von Gemüse.",
		CARROT_COOKED = "Immerhin ein bisschen verfeinert.",
		CARROT_PLANTED = "Wie banal.",
		CARROT_SEEDS = "Solche Arbeit ist nichts für mich.",
		CAVE_FERN = "Ich würde gern drauftreten.",
		CHARCOAL = "Niemand wird meinen Kohlenstoff stehlen!",
        CHESSJUNK1 = "Wenn es meine Aufgabe war, würde es nie fertig bekommen.",
        CHESSJUNK2 = "Wäre dumm, wenn ich das nicht essen würde.",
        CHESSJUNK3 = "Sein Gesicht hat mir nicht gefallen.",
		CHESTER = "Lästiges kleines Monster. Hat jedoch seinen Nutzen.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Hör auf mich anzugucken!",
			WAITING = "Worauf wartet er?",
		},
		COOKEDMANDRAKE = "Er hat die Mehrheit seiner Macht verloren.",
		COOKEDMEAT = "Es riecht jetzt nicht mehr so stark nach Bauernhof.",
		COOKEDMONSTERMEAT = "Ich werde es essen, wenn ich muss.",
		COOKEDSMALLMEAT = "Nun, immerhin bewegt es sich nicht mehr.",
		CORN = "Reich an Fruchtzucker.",
		CORN_COOKED = "Immerhin ein bisschen verfeinert.",
		CORN_SEEDS = "Solche Arbeit ist nichts für mich.",
		CROW =
		{
			GENERIC = "Ich weiß nicht, wie sie hierher gekommen sind.",
			HELD = "Shhhh... meine Hübsche.",
		},
		LICHEN = "Dieser Pilz hat den Untergang überlebt.",
		CUTLICHEN = "Trocken, bröselig, nahrhaft.",
		CUTGRASS = "Das gewöhnlichste Zeug der Erde.",
		CUTREEDS = "Ich denke, ich könnte etwas nützliches daraus bauen.",
		CUTSTONE = "Die Bausteine der Zivilisation.",
		DEADLYFEAST = "Es riecht... giftig.",
		DEERCLOPS = "Vor dem hab selbst ich Angst.",
		DEERCLOPS_EYEBALL = "Deerclops sind kurzsichtig.",
		DEPLETED_GRASS =
		{
			GENERIC = "Es tut niemandem etwas Gutes.",
		},
		DIRTPILE = "Das sieht deplatziert aus.",
		DIVININGROD =
		{
			COLD = "Hauptsächlich nur Nebengeräusche.",
			GENERIC = "Die kann ich verwenden, um meine fehlenden Teile zu finden.",
			HOT = "Es muss genau unter meine Nase sein!",
			WARM = "Das ist die richtige Richtung.",
			WARMER = "Ich sollte meine Augen offen halten.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Das ist der Startmechanismus.",
			READY = "Ich muss die Wünschelrute einsetzen.",
			UNLOCKED = "Fortschritt!",
		},
		DIVININGRODSTART = "Die Portale führen zur nächsten Rute.",
		DRAGONFLY = "Eine feurige Fliege.",
		LAVASPIT = 
		{
			HOT = "Hitzkopf.",
			COOL = "Jetzt ist sie kalt und trocken.",
		},
		DRAGONFRUIT = "Exotisch und köstlich.",
		DRAGONFRUIT_COOKED = "Immerhin ein bisschen verfeinert.",
		DRAGONFRUIT_SEEDS = "Solche Arbeit ist nichts für mich.",
		DRAGONPIE = "Einfach hervorragend.",
		DRUMSTICK = "Schmeckt seltsamerweise nach Beeren.",
		DRUMSTICK_COOKED = "Schmeckt immer noch nach Beeren.",
		DUG_BERRYBUSH = "Sehe ich wie ein Gärtner aus?",
		DUG_GRASS = "Sehe ich wie ein Gärtner aus?",
		DUG_MARSH_BUSH = "Sehe ich wie ein Gärtner aus?",
		DUG_SAPLING = "Ich kann nicht glauben, was ich hier tue.",
		DURIAN = "Das ist etwas für Kenner.",
		DURIAN_COOKED = "Immerhin ein bisschen verfeinert.",
		DURIAN_SEEDS = "Solche Arbeit ist nichts für mich.",
		EARMUFFSHAT = "Wenigstens sind sie warm.",
		EGGPLANT = "Nur eine weitere langweilige Pflanze.",
		EGGPLANT_COOKED = "Immerhin ein bisschen verfeinert.",
		EGGPLANT_SEEDS = "Solche Arbeit ist nichts für mich.",
		ACORN = 
		{
		    GENERIC = "Jemand der gerne an der frischen Luft ist, könnte damit vielleicht was anfangen.",
		    PLANTED = "Hm, er scheint in den Boden zu gehören.",
		},
		EVERGREEN =
		{
			BURNING = "Hoppla.",
			BURNT = "In Feuer gebadet.",
			CHOPPED = "Er scheint nicht wieder nachzuwachsen.",
			GENERIC = "Manche nennen sowas Tannenbaum.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Hoppla.",
			BURNT = "Staub zu Staub.",
			CHOPPED = "Ich hab ihn von seinem Elend befreit.",
			GENERIC = "Er sieht kränklich aus.",
		},
		EYEPLANT = "Die Schachfiguren der Fleischzwiebel.",
		FEATHERHAT = "Ich werde sie mit meinem Gefieder anlocken.",
		FEATHER_CROW = "Schwarz ist die Farbe des Schlafs.",
		FEATHER_ROBIN = "Rot ist die Farbe des Feuers.",
		FEATHER_ROBIN_WINTER = "Grau ist die Farbe des Schmerzes.",
		FEM_PUPPET = "Lieber sie als ich.",
		FIREFLIES =
		{
			GENERIC = "Wie schön!",
			HELD = "Ich könnte es zerquetschen, wenn ich wollte.",
		},
		FIREHOUND = "Als Scherz habe ich Feueredelsteine in sie eingebaut.",
		FIREPIT =
		{
			EMBERS = "Ich sollte mich darum kümmern.",
			GENERIC = "Eine Feuerstelle.",
			HIGH = "Ein tosendes Feuer.",
			LOW = "Es wird kleiner.",
			NORMAL = "Es ist heiß.",
			OUT = "Es ist abgekühlt.",
		},
		FIRESTAFF = "Ein einfacher, aber wirksamer Zauber.",
		FISH = "Frisch aus den finsteren Tiefen.",
		FISHINGROD = "Ich werde mein Leben lang etwas zu essen haben.",
		FISHSTICKS = "Er wird über mir wachen.",
		FISHTACOS = "Gekochter Fisch in knuspriger Hülle.",
		FISH_MED = "Bleib.",
		FISH_MED_COOKED = "Er stinkt noch.",
		FISH_COOKED = "Er stinkt noch.",
		FLINT = "Au! Ich habe mir in den Finger geschnitten!",
		FLOWER = "Mich erfüllt das irrationale Verlangen, auf sie draufzutreten.",
		FLOWERHAT = "Definitiv nicht mein Stil.",
		FLOWER_EVIL = "Ich mag diese Blume.",
		FOLIAGE = "Eine geeignete Mahlzeit für einen Bauern.",
		FOOTBALLHAT = "Jetzt bin ich bereit für ein Trainingsspiel.",
		FROG =
		{
			DEAD = "Er quakte.",
			GENERIC = "Er springt und leckt an Dingen.",
			SLEEPING = "Er sieht müde aus.",
		},
		FROGGLEBUNWICH = "Wo sich die Schweine entspannen.",
		FROGLEGS = "Muskulös.",
		FROGLEGS_COOKED = "Zäh.",
		FRUITMEDLEY = "Auf einer Käseplatte würde sich das gut machen.",
		GEARS = "Meine Haustiere! Was ist aus ihnen geworden?",
		GHOST = "Er erinnert sich an mich!",
		GOLDENAXE = "Sie wird mit jedem Schwung schärfer.",
		GOLDENPICKAXE = "Das muss Spielelogik sein.",
		GOLDENPITCHFORK = "Ich bin mir nicht sicher, ob das eine gute Investition war.",
		GOLDENSHOVEL = "Diese Schaufel ist eine fürstliche Summe wert.",
		GOLDNUGGET = "Damals war mir das noch wichtig.",
		GRASS =
		{
			BARREN = "Braucht Dünger.",
			WITHERED = "Man würde annehmen, dass Gras einer solchen Hitze widerstehen kann...",
			BURNING = "Hoppla.",
			GENERIC = "Buschig.",
			PICKED = "Nichts zum Ernten.",
		},
		GREEN_CAP = "Ich sollte es essen.",
		GREEN_CAP_COOKED = "Salzig!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Grüner Pilz.",
			INGROUND = "Wann kommen die wieder raus?",
			PICKED = "Kenn ich schon!",
		},
		GUNPOWDER = "Das mag ich.",
		HAMBAT = "Eine würdelose Waffe für eine weniger gebildete Zeit.",
		HAMMER = "Es fühlt sich gut an, die Arbeit von anderen zunichte zu machen.",
		HEALINGSALVE = "Nur ein wenig Gift und ein bisschen dreckige alte Asche.",
		HEATROCK =
		{	
			FROZEN = "Er ist fast zu kalt, um ihn festzuhalten.",
			COLD = "Angenehm kühl.",
			GENERIC = "Eine Tasche voll Stein und Temperatur.",
			WARM = "Angenehm lauwarm.",
			HOT = "Er ist fast zu heiß, um ihn festzuhalten.",
		},
		HOME = "Es gibt keinen Ort wie diesen.",
		HOMESIGN = 
		{
			GENERIC = "Dort steht... nichts.",
			BURNT = "Irgendwie sagt es jetzt noch weniger aus.",
		},
		HONEY = "Sticky und süß.",
		HONEYCOMB = "Sie ist voll von Bienensamen.",
		HONEYHAM = "Es ist ziemlich empfindlich.",
		HONEYNUGGETS = "Sie sehen noch dümmer aus, wenn sie schlafen.",
		HORN = "Rufe die Bestien herbei!",
		HOUND = "Erkennst du mich nicht?",
		HOUNDBONE = "Hungrige Teufel, nicht wahr?",
		HOUNDMOUND = "Ein Tunnel, der hinunter ins Hundenest führt.",
		ICEBOX = "Ein kleines Stück Winter in einem Kasten.",
		INSANITYROCK =
		{
			ACTIVE = "Jetzt kann ich seine wahre Natur sehen!",
			INACTIVE = "Auf dieser Ebene existiert er nur zur Hälfte.",
		},
		JAMMYPRESERVES = "Fühlt sich gut zwischen meinen Zehen an.",
		KABOBS = "Perfekt gekocht!",
		KILLERBEE =
		{
			GENERIC = "Weswegen ist diese Biene so verärgert?",
			HELD = "Ich habe einem Tiger am Schwanz gepackt.",
		},
		KNIGHT = "Das nenn ich Qualität!",
		KOALEFANT_SUMMER = "Ein entfernter Verwandter des Beefalos.",
		KOALEFANT_WINTER = "Er hat seinen Wintermantel an.",
		KRAMPUS = "Du kriegst mich nicht!",
		KRAMPUS_SACK = "Er ist wirklich leicht.",
		LEIF = "Widerliche Kreatur!",
		LEIF_SPARSE = "Widerliche Kreatur!",
		LIGHTNING_ROD =
		{
			CHARGED = "Sie wird von Energie durchströmt.",
			GENERIC = "Ein klein wenig Schutz.",
		},
		LITTLE_WALRUS = "Ein Splitter vom alten Block.",
		LIVINGLOG = "Ich mag das Geräusch, das sie machen, wenn Sie sie verbrennen.",
		LOCKEDWES = "Er hat mich verärgert.",
		LOG =
		{
			BURNING = "Nun. Es hat Spaß gemacht, solange er brannte.",
			GENERIC = "Ein Stück Holz. Was gibt es da noch zu sagen?",
		},
		LUREPLANT = "Eine bösartige Pflanze.",
		LUREPLANTBULB = "Vielleicht kann ich das zu meinem Vorteil nutzen.",
		MALE_PUPPET = "Lieber er als ich.",
		MANDRAKE =
		{
			DEAD = "Meine Ohren klingeln immer noch.",
			GENERIC = "Wirst du endlich SCHWEIGEN?",
			PICKED = "Was für eine verstörende Wurzel.",
		},
		MANDRAKESOUP = "Dir weint keiner mehr nach.",
		MANDRAKE_COOKED = "Sieht so aus, als hätte sie den letzten Laut von sich gegeben.",
		MARBLE = "Das ist starkes Zeug.",
		MARBLEPILLAR = "Ich habe mich immer gefragt, wer die gebaut hat.",
		MARBLETREE = "Wie skurril.",
		MARSH_BUSH =
		{
			BURNING = "Ich sollte ihm Fragen stellen.",
			GENERIC = "Er ist verdorben und dornig. Genau wie ich!",
			PICKED = "Das war schmerzhaft.",
		},
		MARSH_PLANT = "Was für eine typische, kleine Pflanze.",
		MARSH_TREE =
		{
			BURNING = "Das war's dann wohl.",
			BURNT = "Jetzt nützt es niemandem mehr etwas.",
			CHOPPED = "Baum: 0, Maxwell: 1.",
			GENERIC = "Ein Baum mit einem verdorbenen Verhalten.",
		},
		MAXWELL = "Sieht gut aus!",
		MAXWELLHEAD = "Hey, gutaussehend.",
		MAXWELLLIGHT = "Ohh, es erinnert sich an mich.",
		MAXWELLLOCK = "Dadurch behält der Meister den Vorsitz.",
		MAXWELLTHRONE = "Es ist weniger schmerzhaft als es aussieht.",
		MEAT = "Ich bin wesentlich bessere Kost gewohnt.",
		MEATBALLS = "Kompliment an die Küche!",
		MEAT_DRIED = "Meine Zähne werden zu alt dafür.",
		MERM = "Sie waren alle schon tot, als ich hier ankam.",
		MINERHAT = "Irgendwann wird das Glühwürmchen verhungern.",
		MONKEY = "Ich habe keine Zeit für dich!",
		MONKEYBARREL = "Was für ein widerliches Zuhause.",
		MONSTERLASAGNA = "Es wäre nicht weise, wenn man das in den Mund nehmen würde.",
		MONSTERMEAT = "Wie ekelhaft.",
		MONSTERMEAT_DRIED = "Meine Zähne werden zu alt dafür.",
		MOSQUITO =
		{
			GENERIC = "Es ist immer noch blutig.",
			HELD = "Ich hab ihn.",
		},
		MOSQUITOSACK = "Ein blutiger Sack. Mit Blut darin.",
		MOUND =
		{
			DUG = "Das habe ich bereits.",
			GENERIC = "Was liegt wohl darunter?",
		},
		NIGHTLIGHT = "Es brennt in einem wunderschönen Schein.",
		NIGHTMAREFUEL = "Ahhh. Erfrischend.",
		NIGHTSWORD = "Kicher-Snack!",
		NITRE = "Ein Drittel des Weges...",
		ONEMANBAND = "Sie hat einen guten Rhythmus und man kann dazu tanzen.",
		PANDORASCHEST = "Das ist eine Falle.",
		PANFLUTE = "Ich bin dabei, ein Lied des Wahnsinn zu singen.",
		PAPYRUS = "Eine leere Leinwand.",
		PENGUIN = "Netter Smoking.",
		PERD = "Er ist süchtig nach gegorenen Beeren.",
		PEROGIES = "Hab ich gemacht. Es sollte also gut sein.",
		PETALS = "Dass ich die schönen Dinge immer kaputt machen muss.",
		PETALS_EVIL = "Die triefen vor lauter Albtraumgehalt.",
		PICKAXE = "Jeder liebt ein wenig Bergbau.",
		PIGGYBACK = "Oh, das ist einfach nur erniedrigend.",
		PIGKING = "Das ist ein Mann, dessen Prioritäten in Ordnung sind!",
		PIGMAN =
		{
			DEAD = "Ich nenne dich 'Speck'.",
			FOLLOWER = "Er ist zwar dumm, aber er gehört mir.",
			GENERIC = "Was für ein sabbernder Narr.",
			GUARD = "Sie beginnen, sich zu organisieren.",
			WEREPIG = "Dieser ist wild geworden.",
		},
		PIGSKIN = "Es galt 'Er oder ich'.",
		PIGTENT = "Das ist einfach nur widerlich.",
		PIGTORCH = "Super. Jetzt haben sie Feuer.",
		PINECONE = 
		{
		    GENERIC = "Jemand der gerne an der frischen Luft ist, könnte damit vielleicht was anfangen.",
		    PLANTED = "Hm, er scheint in den Boden zu gehören.",
		},
		PITCHFORK = "Das richtige Werkzeug für Perfektionisten.",
		PLANTMEAT = "Ein schwacher Versuch, die mit begrenztem Verstand hereinzulegen.",
		PLANTMEAT_COOKED = "Durch die Hitze wurde es erst zu einer ordentlichen Mahlzeit.",
		PLANT_NORMAL =
		{
			GENERIC = "Das ist eine typische Pflanze.",
			GROWING = "Sie wächst.",
			READY = "Sie ist bereit.",
			WITHERED = "Sie hat die Hitze nicht ausgehalten.",
		},
		POMEGRANATE = "Normalerweise würde ich jemanden dazu bringen, das für mich auszusäen.",
		POMEGRANATE_COOKED = "Immerhin ein bisschen verfeinert.",
		POMEGRANATE_SEEDS = "Solche Arbeit ist nichts für mich.",
		POND = "Ich kann die Reflektion meines Gesichts auf der Oberfläche sehen.",
		POOP = "Das ist der Lauf des sterblichen Lebens.",
		PUMPKIN = "Halloween hat mir schon immer gefallen.",
		PUMPKINCOOKIE = "Ich hatte schon ewig keinen guten Keks mehr.",
		PUMPKIN_COOKED = "Immerhin ein bisschen verfeinert.",
		PUMPKIN_LANTERN = "Hallo, Mr. Kürbis.",
		PUMPKIN_SEEDS = "Solche Arbeit ist nichts für mich.",
		PURPLEAMULET = "Er spricht mit den Schatten.",
		PURPLEGEM = "Violett bringt große Kraft mit sich.",
		RABBIT =
		{
			GENERIC = "Ich bin einfach schon zu lange hier - es sieht wirklich köstlich aus.",
			HELD = "Keine Sorge, Kaninchen. Alles unter Kontrolle.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Dort unten existiert eine weitere Welt.",
			SPRING = "Der Eingang ist in sich selbst zusammengebrochen.",
		},
		RATATOUILLE = "Ballaststoffe!",
		RAZOR = "Wenn nur die Welt einen eigenen Hals hätte.",
		REDGEM = "Rot bringt Feuer.",
		RED_CAP = "Ich habe vergessen, was der bewirkt.",
		RED_CAP_COOKED = "Irgendwie bitter.",
		RED_MUSHROOM =
		{
			GENERIC = "Das ist ein roter Pilz.",
			INGROUND = "Ich werde später nochmals wiederkommen müssen.",
			PICKED = "Er ist ganz verbraucht.",
		},
		REEDS =
		{
			BURNING = "Hoppla.",
			GENERIC = "Das ist Wassergras.",
			PICKED = "Keine weiteren Röhren.",
		},
        RELIC = 
        {
            GENERIC = "Reste von einer ausgestorbenen Zivilisation.",
            BROKEN = "Nur ein paar Teile eines Steins.",
        },
        RUINS_RUBBLE = "Ein zerbrochenes Relikt.",
        RUBBLE = "Nur ein paar Teile eines Steins.",
		RESURRECTIONSTONE = "Dahinter verbirgt sich eine Geschichte...",
		ROBIN =
		{
			GENERIC = "Der rote Vogel kommt aus den Feuerländern.",
			HELD = "Ruhe, Vogel!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Ich erkenne diese Kunstfertigkeit nicht.",
			HELD = "Sei still.",
		},
		ROBOT_PUPPET = "Besser er als ich.",
		ROCK_LIGHT =
		{
			GENERIC = "Die Oberfläche dieser Lavapfütze hat beim Abkühlen eine feine Kruste gebildet.",
			OUT = "Er sieht harmlos aus.",
			LOW = "Die Feuer kühlen ab.",
			NORMAL = "Es ist heiß.",
		},
		ROCK = "Das ist ein Stein.",
		ROCKS = "Hmmm. Was mache ich jetzt damit?",
        ROOK = "Eine Festung als Zuhause.",
		ROPE = "Man sollte meinen, dass man damit mehr tun könnte.",
		ROTTENEGG = "Widerlich. Wieso trage ich das mit mir rum?",
		SANITYROCK =
		{
			ACTIVE = "Jetzt kann ich seine wahre Natur sehen!",
			INACTIVE = "Dieses Hindernis kann in zwei verschiedenen Zuständen gefunden werden.",
		},
		SAPLING =
		{
			BURNING = "Hoppla.",
			WITHERED = "Bei dieser Hitze überlebt nichts.",
			GENERIC = "Ein biegsamer, holziger Stängel.",
			PICKED = "Er wird wieder wachsen.",
		},
		SEEDS = "Ich nehme an, dass sie sich nicht selbst anpflanzen.",
		SEEDS_COOKED = "Ich habe das gesamte Leben aus ihnen rausgekocht.",
		SEWING_KIT = "Ein gutes und vornehmes Unterfangen.",
		SHOVEL = "Dies ist eine wirklich fortschrittliche Technologie.",
		SILK = "Trotz seiner Herkunft könnte es einige schöne Kleider machen.",
		SKELETON = "Ha! An den erinnere ich mich.",
		SKELETON_PLAYER = "Der Meister wird zum Schüler.",
		SKULLCHEST = "Das ist eine schicke Truhe.",
		SMALLBIRD =
		{
			GENERIC = "Was!? Was willst du?",
			HUNGRY = "Willst du was zu essen?",
			STARVING = "Er ist so hungrig!",
		},
		SMALLMEAT = "Das ist nicht mal ein Mundvoll.",
		SMALLMEAT_DRIED = "Meine Zähne werden zu alt dafür.",
		SPEAR = "Das ist ein Speer. Ja.",
		SPIDER =
		{
			DEAD = "Platsch.",
			GENERIC = "Sie ist überwiegend ein Verdauungssystem.",
			SLEEPING = "Shhhh! Sie wird hungrig aufwachen.",
		},
		SPIDERDEN = "Hier werden sie erwachsen.",
		SPIDEREGGSACK = "Matschig.",
		SPIDERGLAND = "Unangenehm.",
		SPIDERHAT = "Spinnen haben einen solch formbaren Willen.",
		SPIDERQUEEN = "Vielleicht kann ich ihr noch aus dem Weg gehen.",
		SPIDER_WARRIOR =
		{
			DEAD = "Platsch.",
			GENERIC = "Das ist eine spezialisierte Form.",
			SLEEPING = "Ich will ihn nicht aufwecken.",
		},
		SPOILED_FOOD = "Das war mal Nahrung, bis ich sie verschwendet habe.",
		STATUEHARP = "Nicht meine beste Arbeit.",
		STATUEMAXWELL = "Jetzt ist es eine schön Statue.",
		STINGER = "Er trieft vor Gift.",
		STEELWOOL = "Jemand sollte diesen Ort wirklich mal aufräumen.",
		STRAWHAT = "Ein geeigneter Hut für einen Bauern.",
		STUFFEDEGGPLANT = "Eine Mahlzeit für einen König... oder zumindest jemanden mit einem Thron.",
		SUNKBOAT = "So sollte man ein Boot nicht benutzen.",
		SWEATERVEST = "Zwar kein Dreiteiler, aber trotzdem elegant.",
		TAFFY = "Könnte eine Prise Zucker vertragen.",
		TALLBIRD = "Das war ein erfolgloses Experiment.",
		TALLBIRDEGG = "Wegen dieser Dinge haben langbeinige Vögel so ein Territorialverhalten.",
		TALLBIRDEGG_COOKED = "Es schmeckt, wie zerstörte Träume.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Es wird lauwarm.",
			GENERIC = "Hier ist ein lebendes Exemplar.",
			HOT = "Heiß genug für dich?",
			LONG = "Das wird eine Weile dauern.",
			SHORT = "Es ist jeden Moment soweit...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Nun, das ist verlockend.",
			PICKED = "Aus dreckigem Beefalo-Haar gemacht.",
		},
		TEENBIRD =
		{
			GENERIC = "Jetzt, wo er gewachsen ist, ist er nicht mehr so süß.",
			HUNGRY = "Sie essen sicher viel.",
			STARVING = "Eine hungriges Biest ist eine gefährliche Bestie.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Es lebt!",
			GENERIC = "Meine schöne Maschine ist zerbrochen!",
			LOCKED = "Jetzt könnte ich es einschalten.",
			PARTIAL = "Es ist immer noch unvollständig.",
		},
		TELEPORTATO_BOX = "Das ist ein Kasten voller Traurigkeit und Kummer.",
		TELEPORTATO_CRANK = "Dies wird verwendet, um den Geist anzuregen.",
		TELEPORTATO_POTATO = "Die Zahnräder sind so klein, dass sie die Realität auf den Kopf stellen.",
		TELEPORTATO_RING = "Das ist das Schutzband des Quantenfelds.",
		TELESTAFF = "Macht kann erstaunliche Dinge bewirken, wenn sie durch die richtigen Kanäle kanalisiert wird.",
		TENTACLE = "Ich bin froh, dass der Rest noch dort unten ist.",
		TENTACLESPIKE = "Igitt. Das ist so ekelhaft.",
		TENTACLESPOTS = "Damit vermehren sie sich.",
		TENTACLE_PILLAR = "Wie tief geht die runter?",
		TENTACLE_GARDEN = "Komisch.",
        TENTACLE_PILLAR_ARM = "Babys?",
		TOPHAT = "Eine edle Herrenbekleidung.",
		TORCH = "Sie hält Charlie in Schach.",
		TRAP = "Nur die dümmsten Tiere werden darauf reinfallen.",
		TRAP_TEETH = "Das Ding kann ganz schön zuschlagen.",
		TRAP_TEETH_MAXWELL = "Ich bin mir sicher, dass ich meine Gründe hatte, als ich sie ausgelegt habe.",
		TREASURECHEST_TRAP = "Hmmm. Sieht verdächtig aus.",
		TREECLUMP = "Ich komme da nicht durch.",
		TRINKET_1 = "Die Hitze muss unvorstellbar heiß gewesen sein.",
		TRINKET_10 = "Welpenzahn!",
		TRINKET_11 = "Schiff hört nicht auf mächtigen Wolfgang!",
		TRINKET_12 = "Das fass ich nur mit ganz dicken Handschuhen an.",
		TRINKET_2 = "Das war mal wichtig für jemanden.",
		TRINKET_3 = "Ein erbärmliches Durcheinander, genau wie das Leben.",
		TRINKET_4 = "Ich mag nicht, wie er mich anschaut!",
		TRINKET_5 = "EIN UNPRAKTISCHES KINDERSPIELZEUG",
		TRINKET_6 = "Nicht nur irgendein alter Stein.",
		TRINKET_7 = "Nichts, womit ein erwachsener Mann gesehen werden sollte.",
		TRINKET_8 = "Ich würde etwas Abwechslung bevorzugen.",
		TRINKET_9 = "Meine Anzüge sind für sowas viel zu gut.",
		TRUNKVEST_SUMMER = "Es ist mehr eine Herbstweste.",
		TRUNKVEST_WINTER = "Es ist wirklich schwer, sich im Winter elegant zu kleiden.",
		TRUNK_COOKED = "Wenigstens ist der Schleim verbrannt.",
		TRUNK_SUMMER = "Voll von Sommerschleim.",
		TRUNK_WINTER = "Der Rüssel wird im Winter dicker, damit er mehr Schleim aufnehmen kann.",

		TURF_CARPETFLOOR = "Das ist eine qualitative, vielschichtige Teppichprobe.",
		TURF_CHECKERFLOOR = "Das ist mein natürlicher Lebensraum.",
		TURF_DIRT = "Staubig.",
		TURF_FOREST = "Riecht wie Matsch.",
		TURF_GRASS = "Kratzig.",
		TURF_MARSH = "Der trieft gänzlich.",
		TURF_ROAD = "Dieser ist wenigstens nützlich.",
		TURF_ROCKY = "Irgendwie rau.",
		TURF_SAVANNA = "Dreckig.",
		TURF_WOODFLOOR = "Ich bevorzuge Hartholz.",

		TURF_CAVE="Erdboden.",
		TURF_FUNGUS="Erdboden.",
		TURF_SINKHOLE="Erdboden.",
		TURF_UNDERROCK="Erdboden.",
		TURF_MUD="Erdboden.",

		TURKEYDINNER = "Wie festlich.",
		TWIGS = "Gewöhnlich, aber nützlich.",
		UMBRELLA = "Er ist krumm!",
		WAFFLES = "Ganz lecker zum Frühstück. Oder am Abend.",
		WALL_HAY_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALL_STONE = "Die sollten das Gesindel draußen halten.",
		WALL_STONE_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALL_WOOD_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALL_RUINS = "Eine antike Mauer.",
		WALL_RUINS_ITEM = "Mauerstücke im Taschenformat. Jep.",
		WALRUS = "Erkennst du mich nicht?",
		WALRUSHAT = "Hergestellt in Schottland.",
		WALRUS_CAMP =
		{
			EMPTY = "Ich sollte am besten nicht hier sein, wenn der Winter kommt.",
			GENERIC = "Das Walross kann nicht weit sein.",
		},
		WALRUS_TUSK = "Ich werde dafür eine besseren Nutzen finden.",
		WASPHIVE = "Das sieht gefährlich aus.",
		WETGOOP = "Wie?",
		WINTERHAT = "Enttäuschend bodenständig.",
		WORMHOLE =
		{
			GENERIC = "Es ist schlechter zu wissen, wie die andere Seite aussieht.",
			OPEN = "Ich kann dir versichern, dass es schlechter riecht als es aussieht.",
		},
		WORMHOLE_LIMITED = "Es sieht krank aus.",
		ACCOMPLISHMENT_SHRINE = "Selbst SIE hätten etwas so hinterhältiges nicht bauen können.",

		AERODYNAMICHAT = "Eine grausame, aber elegante Bestie.",
		ANTIVENOM = "Eine Heilung für deine Probleme.",
		ARMORCACTUS = "So abwehrend wie sonst nichts.",
		ARMORLIMESTONE = "ES DIENT MIR.",
		ARMOROBSIDIAN = "Durch Flammen verkohlt oder nicht. Das wird meine Lippen nicht berühren!",
		ARMORSEASHELL = "Nicht besonders robust, bietet aber durchaus Schutz.",
		ARMOR_LIFEJACKET = "Manchmal geht Vorsicht eben vor Stilsicherheit.",
		ARMOR_SNAKESKIN = "Sie draußen auf dem Meer sehr elegant aus.",
		ARMOR_WINDBREAKER = "SEUFZ. NATUR IST SCHRECKLICH.",
		ARMOUREDBOAT = "Dieses Schiff lässt sich nicht so schnell unterkriegen.",
		BABYOX = "Von mir bekommst du keine Sonderbehandlung, Bestie.",
		BALLPHIN = "Die sind viel geschickter als man meint.",
		BAMBOO = "Dafür hab ich einige Ideen im Kopf.",
		BAMBOOTREE =
		{
			BURNT = "ENDLICH WIEDER IN BEKANNTEM GEBIET",
			CHOPPED = "Braucht Zeit zum Entspannen.",
			GENERIC = "Das wächst durch fast alles.",
		},
		BERMUDATRIANGLE = "Er ruft nach mir!",
		BIGFISHINGROD = "Vielleicht hab ich jetzt mehr Glück mit dem schwimmenden Fleisch.",
		BIOLUMINESCENCE = "Es ist aus einer anderen Welt.",
		BLOWDART_FLUP = "Seltsame Vorrichtung.",
		BLOWDART_POISON = "Ich habe das Gift der Welt gegen sich selbst gerichtet.",
		BLUBBER = "Ich vermute, dass ich es reparieren kann.",
		BLUBBERSUIT = "Eine würdelose Waffe für eine weniger gebildete Zeit.",
		BOATCANNON = "Endlich hab ich mal eines dieser Prachtstücke.",
		BOATREPAIRKIT = "Damit lässt sich der Verfall meines Schiffs ein bisschen aufhalten.",
		BOAT_LANTERN = "Das taucht die Umgebung in ein fahles Licht.",
		BOAT_TORCH = "Macht die Schifffahrt in der Nacht ein bisschen weniger gefährlich.",
		BOTTLELANTERN = "Ihr Zweck ist es, uns zu dienen.",
		BRAINJELLYHAT = "Ich fühle mich inspiriert.",
		BUOY = "Holz schwimmt wenigstens.",
		BURIEDTREASURE = "Und was ist das?",
		BUSH_VINE =
		{
			BURNT = "Er hat ein feuriges Ende gefunden.",
			CHOPPED = "Das ist erstmal alles aufgebraucht.",
			GENERIC = "Die haben die Insel übernommen.",
		},
		CAPTAINHAT = "Der macht mich glücklich.",
		CARGOBOAT = "Ah, viel Platz zum Atmen.",
		CHIMINEA = "Darin sind meine Feuer gut aufgehoben.",
		CLOTHSAIL = "Wurde auf meinen Reisen geopfert.",
		COCONADE =
		{
			BURNING = "Ich sollte vielleicht besser in Deckung gehen.",
			GENERIC = "Ich seh meine Zukunft...",
		},
		COCONUT = 
		{
		    GENERIC = "Das könnte erheblichen Schaden an jemandes Schädel anrichten.",
		    PLANTED = "Es kann niemandem mehr wehtun.",
		},
		COCONUT_COOKED = "Kommt ruhig her, ihr Unmenschen!",
		COCONUT_HALVED = "Ich hab aus einer Kokosnuss zwei gemacht.",
		COFFEE = "Ich freue mich schon auf eine ordentliche Mahlzeit.",
		COFFEEBEANS = "Sieht komisch aus in dieser Farbe.",
		COFFEEBEANS_COOKED = "Besser als roh, aber vielleicht gibt es eine noch bessere Zubereitungsart?",
		COFFEEBOT = "LEISTE MEINEN ANORDNUNGEN FOLGE.",
		COFFEEBUSH =
		{
			BARREN = "Er ist karg.",
			GENERIC = "Herrliche Kaffeebohnen.",
			PICKED = "Ich habe es gepflückt.",
			WITHERED = "Das verfällt langsam.",
		},
		COMPASS =
		{
			GENERIC="Hm, ich kann da nichts ablesen.",
			N = "Norden.",
			S = "Süden.",
			E = "Osten.",
			W = "Westen.",
			NE = "Nordosten.",
			SE = "Südosten.",
			NW = "Nordwesten.",
			SW = "Südwesten.",
		},
		CORAL = "Nette Umgebung.",
		CORALREEF = "Hier könnte so einiges leben.",
		CORAL_BRAIN = "Jetzt kann ich seine Denkleistung für mich selbst nutzen.",
		CORAL_BRAIN_ROCK = "Ich frage mich, was es im Schilde führt...",
		CRAB =
		{
			GENERIC = "Ein essbares Krustentier.",
			HIDDEN = "Die Hasenkrabbe versteckt sich.",
		},
		CRABHOLE = "Du kannst dich nicht ewig verstecken, Kumpel.",
		CRATE = "Vielleicht bekomm ich das auf.",
		CUTLASS = "Die Waffe eines echten Gentlemans.",
		DEAD_SWORDFISH = "Vielleicht hätte ich mehr Fechtunterricht nehmen sollen.",
		DEPLETED_BAMBOOTREE = "Alle weg.",
		DEPLETED_BUSH_VINE = "Das war einmal.",
		DEPLETED_GRASS_WATER = "Es ist alles zappelig.",
		DEVTOOL = "Wie seltsam.",
		DEVTOOL_NODEV = "Ein Stück Wissen, das ich nicht verstehe... Faszinierend!",
		DOUBLE_UMBRELLAHAT = "Dummes Kaninchen.",
		DOYDOY = "Diese traurige Kreatur hat keine Hoffnung auf ein Überleben.",
		DOYDOYBABY = "SIE SIND NUN NAHRHAFTER.",
		DOYDOYEGG = "Soll ich lieber eine vom Aussterben bedrohte Tierart ausbrüten lassen oder doch lieber eine leichte Mahlzeit daraus machen?",
		DOYDOYEGG_COOKED = "Ein leichter Snack ist immer die beste Option.",
		DOYDOYEGG_CRACKED = "Hoppla.",
		DOYDOYFEATHER = "Auf einem Hut sieht das bestimmt gut aus.",
		DOYDOYNEST = "Teile uns mit, was du denkst.",
		DRAGOON = "Ich kenn dich nicht.",
		DRAGOONDEN = "Nun, es gibt einen Grund, reinzuspringen.",
		DRAGOONEGG = "Die erdrückende Hitze hat ihn erwischt.",
		DRAGOONHEART = "Herz bringt sowieso nur Schmerz.",
		DRAGOONSPIT = "Wie ungehobelt! Woodlegs gefällt das!",
		DUBLOON = "Das Klirren zweier Münzen ist so befriedigend.",
		DUG_BAMBOOTREE = "Dafür muss ich ein gutes Plätzchen finden.",
		DUG_BUSH_VINE = "Dafür muss ich ein gutes Plätzchen finden.",
		DUG_COFFEEBUSH = "Das ist es wert, umgepflanzt zu werden.",
		DUG_ELEPHANTCACTUS = "Damit renne ich lieber nicht.",
		EARRING = "Hätte ich Ohrlöcher, sähe ich damit bestimmt gut aus.",
		ELEPHANTCACTUS = "So erschießt das niemanden.",
		ELEPHANTCACTUS_ACTIVE = "In Deckung!",
		ELEPHANTCACTUS_STUMP = "Auf Nimmerwiedersehen!",
		FABRIC = "Ich hab aus dem Bambus etwas Nützliches gemacht.",
		FEATHERSAIL = "Immerhin besser als Paddeln.",
		FISHINHOLE = "Denen gefällt es in meinem Magen bestimmt genauso gut.",
		FISH_RAW = "Da fehlt ein bisschen Feuer.",
		FISH_RAW_SMALL = "Das ist alles?",
		FISH_RAW_SMALL_COOKED = "Na Mahlzeit.",
		FLAMEGEYSER = "Weiter geht's mit federndem Schritt.",
		FLOTSAM = "Vielleicht könnte ich das irgendwie reinholen.",
		FLUP = "Diese Arbeit ist unter meine Würde.",
		FRESHFRUITCREPES = "Das sollte mit Silberbesteck gegessen werden. Leider habe ich nur meine Hände.",
		FROG_POISON = "Dem muss ich wohl Manieren beibringen.",
		GASHAT = "Damit riecht man nichts mehr.",
		GOLDENMACHETE = "Ich wollte schon immer mit Stil Dinge zerhacken.",
		GRASS_WATER = "Das war schon teilweise verfault.",
		HAIL_ICE = "Etwas kühl.",
		HOUNDFIRE = "Eine beißende Flamme.",
		ICEMAKER =
		{
			HIGH = "Die Eisproduktion läuft auf Hochtouren.",
			LOW = "Das gibt einem wieder Kraft.",
			NORMAL = "Es brennt kaum.",
			OUT = "Es brennt kaum.",
			VERYLOW = "Das Ding läuft fast nicht mehr. Vielleicht können wir mit ein paar Beinen aushelfen!?",
		},
		IRONWIND = "Gott sei Dank. Ich muss weiter.",
		JELLYFISH = "Was für eine seltsame kleine Kreatur.",
		JELLYFISH_COOKED = "Ich nehme an, dass sie sich nicht selbst anpflanzen.",
		JELLYFISH_DEAD = "Verbrannt mag ich ihn lieber.",
		JELLYFISH_PLANTED = "Unterirdische Steine?! Schockierend.",
		JELLYJERKY = "Das ist irgendwie gar nicht so übel.",
		JUNGLETREE =
		{
			BURNING = "Nicht von dieser Welt.",
			BURNT = "Ich werde mein Leben lang etwas zu essen haben.",
			CHOPPED = "Hab ich für eigene Zwecke verwendet.",
			GENERIC = "Er will, dass ich ihn fälle.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Die könnte ich wahrscheinlich wieder pflanzen.",
            PLANTED = "Gut. Ich hatte recht.",
        },
		KNIGHTBOAT = "Hör auf mich, Dummkopf!",
		KRAKEN = "Du machst gefälligst, was ich sage.",
		KRAKENCHEST = "Jetzt meine Belohnung.",
		KRAKEN_TENTACLE = "Wie kannst du es wagen mich berühren?",
		LAVAPOOL = "Er ist ein ziemlich warm.",
		LIMESTONE = "Vielleicht ist sein Tod noch für etwas gut.",
		LIMPETROCK =
		{
			GENERIC = "Könnte notfalls auch als Nahrungsquelle taugen.",
			PICKED = "Das ist jetzt nur ein Stück Fels.",
		},
		LIMPETS = "Schleimig und schwer verdaulich.",
		LIMPETS_COOKED = "Ne Delikatesse? Echt?",
		LIVINGJUNGLETREE = "Nichts Außergewöhnliches hier.",
		TREEGUARD = "So ein Unsinn.",
		LOBSTER = "Scheint ein ziemlich hartes Metall zu sein.",
		LOBSTERHOLE = "Zeigt euch, ihr zarten Kreaturen.",
		LOBSTER_DEAD = "Ausgezeichnet.",
		LOBSTER_DEAD_COOKED = "Ich hab mein Lätzchen vergessen.",
		LOGRAFT = "Dagegen sollte es Vorschriften geben.",
		LUGGAGECHEST = "Eine elegante Aktentasche.",
		MACHETE = "Ehrlich gesagt war ich immer ein Hacker.",
		MAGIC_SEAL = "In dir steckt ein wilder Krieger, du Pflanze.",
		MAGMAROCK = "Nun, das war's.",
		MAGMAROCK_FULL = "Nun, das war's.",
		MAGMAROCK_GOLD = "Ein viel luxuriöser Fels.",
		MAGMAROCK_GOLD_FULL = "Ein viel luxuriöser Fels.",
		MANGROVETREE = "Ganz normaler Baum, nur nass.",
		MANGROVETREE_BURNT = "Wurde getötet.",
		MARSH_PLANT_TROPICAL = "Bringt mir jetzt nicht viel.",
		MERMFISHER = "Mit dem hab ich kein Problem.",
		MERMHOUSE_FISHER = "Eine Spinne muss eben auch irgendwo leben.",
		MESSAGEBOTTLE = "WAS FÜR EINE PRIMITIVE TECHNOLOGIE.",
		MESSAGEBOTTLEEMPTY = "Mit etwas Zeit könnte ich da drin ein Schiffchen bauen.",
		MONKEYBALL = "Was soll ich damit anfangen?",
		MONSTERTARTARE = "Nicht sehr appetitlich.",
		MOSQUITOSACK_YELLOW = "Das Blut hätte ich gerne wieder!",
		MOSQUITO_POISON = "Von dem möchte ich nicht gebissen werden.",
		MUSSEL = "Irgendwo ist das vermutlich eine Delikatesse.",
		MUSSELBOUILLABAISE = "Ich freue mich schon auf eine ordentliche Mahlzeit.",
		MUSSEL_COOKED = "Scheint jetzt nicht mehr so gesundheitsschädlich zu sein.",
		MUSSEL_FARM =
		{
			GENERIC = "So kann man sich sein Essen recht einfach zusammensammeln.",
			STICKPLANTED = "Die wissen noch nicht, dass sie gleich tot sind.",
		},
		MUSSEL_STICK = "Diesem Stecken können Muscheln einfach nicht widerstehen.",
		MYSTERYMEAT = "Widerlich!",
		NEEDLESPEAR = "Ein überaus seltenes aber nützliches Material.",
		OBSIDIAN = "Was für eine intensiv rote Farbe du besitzt.",
		OBSIDIANAXE = "Es scheint zu funktionieren am besten, wenn es brennt.",
		OBSIDIANCOCONADE = "Das ist einfach nur übertrieben.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Ich sollte mich darum kümmern.",
			GENERIC = "Jede Sekunde wird ein Dummkopf geboren.",
			HIGH = "Ein tosendes Feuer.",
			LOW = "Es wird kleiner.",
			NORMAL = "Das brennt mit Stil.",
			OUT = "Es ist abgekühlt.",
		},
		OBSIDIANMACHETE = "Scheint, als ob ein oder zwei Teile fehlen.",
		OBSIDIANSPEARGUN = "Projektilflamme. Das gefällt mir.",
		OBSIDIAN_WORKBENCH = "Ich werd schon ganz kreativ...",
		OCTOPUSCHEST = "Das ist ein pelziger Ball von verrotteter Nahrung.",
		OCTOPUSKING = "Ich konnte seine Großzügigkeit zu meinem Vorteil nutzen.",
		OX = "Stinkende Samen for eine stinkende Frucht.",
		OXHAT = "Manchmal ist Funktion eben wichtiger als Aussehen.",
		OX_FLUTE = "Meine Güte! Ich hab schon lang nicht mehr gespielt.",
		OX_HORN = "Die hatten keine Chance.",
		PACKIM = "Er geht fürchterlich auf die Nerven, ist aber durchaus nützlich und willig.",
		PACKIM_FISHBONE = "Ich glaube, das sollte ich behalten.",
		PALMLEAF = "Jetzt brauch ich nur noch einen Lakaien, der mir Luft zufächert.",
		PALMLEAF_HUT = "Puh!",
		PALMTREE =
		{
			BURNING = "Nicht von dieser Welt.",
			BURNT = "Ich werde mein Leben lang etwas zu essen haben.",
			CHOPPED = "Hab ich für eigene Zwecke verwendet.",
			GENERIC = "Welch Luxus!",
		},
		PARROT = "So bunt.",
		PARROT_PIRATE = "Vielleicht kann ich ihn zum Schweigen bringen.",
		PEACOCK = "Widerliche Kreatur!",
		PEG_LEG = "Nicht gut! Nicht gut!",
		PIKE_SKULL = "Trostlos.",
		PIRATEGHOST = "Ich werde nicht das gleiche Schicksal treffen!",
		PIRATEHAT = "Du bist so lustig, wie du haarig bist.",
		PIRATEPACK = "Ich nehme an, dass sie sich nicht selbst anpflanzen.",
		PIRATIHATITATOR =
		{
			BURNT = "Asche zu Asche.",
			GENERIC = "Faszinierend.",
		},
		POISONHOLE = "Ich seh es ganz gut von hier... Muss nicht näher ran.",
		PORTAL_SHIPWRECKED = "NUTZLOS",
		PRIMEAPE = "Diese erbärmliche Kreatur besitzt nur ein gewisses Maß an Intelligenz.",
		PRIMEAPEBARREL = "Halt deinen Mund von mir fern!",
		RAFT = "Das ist ein bisschen zu vornehm für mich.",
		RAWLING = "Prima. Ein sprechender Sack.",
		REDBARREL = "Es platzt vor Leben.",
		ROCK_CHARCOAL = "Die natürlichen Formationen sind echt toll.",
		ROCK_OBSIDIAN = "Da lässt sich mit meinen Werkzeugen einfach nicht bearbeiten.",
		ROWBOAT = "Echt schade.",
		SAIL = "Für eine ruhige und schnelle Segelei.",
		SAIL_STICK = "Ein Stecken, vermutlich für ein Segel.",
		SAND = "Felsen und Steine, die so fein zerschlagen wurden, dass man sie nicht mehr als solche erkennt.",
		SANDBAG = "Ein Sack voller Dreck, der das Wasser abhält.",
		SANDBAGSMALL = "Ein Sack voller Dreck, der das Wasser abhält.",
		SANDBAGSMALL_ITEM = "Ein Sack voller Dreck.",
		SANDBAG_ITEM = "Ein Sack voller Dreck.",
		SANDHILL = "Ein kleiner Haufen gelber Sand.",
		SAND_CASTLE =
		{
			GENERIC = "Ich fand das völlig ungenießbar. Ich schwöre.",
			SAND = "Dekorativer Sand.",
		},
		SEAGULL = "Groß und laut. Das mag ich!",
		SEAGULL_WATER = "ER IST ZIEMLICH SCHWER.",
		SEASACK = "Macht mich nicht stärker, aber gibt mir mehr Stauraum.",
		SEASHELL = "Ich fühle mich schon mächtig, wenn ich sie nur halte.",
		SEASHELL_BEACHED = "Das ist für meinen Geschmack ein bisschen zu kitschig.",
		SEATRAP = "Irgendwann wird dir deine Neugier zum Verhängnis.",
		SEAWEED = "Ihhh! Schmeckt nach Abfall.",
		SEAWEED_COOKED = "Ich bin mir nicht sicher, ob es eine gute Idee ist, das zu essen.",
		SEAWEED_DRIED = "Bäh.",
		SEAWEED_PLANTED = "hier",
		SHADOWSKITTISH_WATER = "Au weh.",
		SHARKITTEN = "Eine wunderbare Monstrosität!",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Der Haufen zittert, wenn ich was sage.",
			INACTIVE = "Ein ganz normaler Sandhaufen.",
		},
		SHARK_FIN = "Trophäe eines mächtigen Feindes.",
		SHARK_GILLS = "Die sollte man vielleicht behalten.",
		SHARK_TEETHHAT = "Ich respektiere die kräftigen Scheren vom Krustentier.",
		SHARX = "Die Frage ist nicht, ob ich siegen werden, sondern wann.",
		SHIPWRECKED_ENTRANCE = "Ich hoffe, du hast Durst, Gras.",
		SHIPWRECKED_EXIT = "Lebt wohl, ihr Landeier!",
		SLOTMACHINE = "Ich fordere das Schicksal ja ganz gerne heraus.",
		SLURPERPELT = "Ein feines Ding.",
		SNAKE = "Eine grausame, aber elegante Bestie.",
		SNAKEDEN =
		{
			BURNT = "Er hat ein feuriges Ende gefunden.",
			CHOPPED = "Das ist erstmal alles aufgebraucht.",
			GENERIC = "Die haben die Insel übernommen.",
		},
		SNAKEOIL = "Vielleicht ließe sich daran etwas verdienen.",
		SNAKESKIN = "Köstlich!",
		SNAKESKINHAT = "Schneidig.",
		SNAKESKINSAIL = "Reise",
		SNAKE_FIRE = "Es muss hier doch auch etwas anderes zu essen geben.",
		SNAKE_POISON = "Da mach ich besser einen großen Bogen herum.",
		SOLOFISH = "Es riecht, es wäre es Nässe.",
		SPEARGUN = "Diese Projektilschleuder könnte noch praktisch werden.",
		SPEARGUN_POISON = "Ich habe dafür gesorgt, dass sie ordentlich schießt.",
		SPEAR_LAUNCHER = "Diese Projektilschleuder könnte noch praktisch werden.",
		SPEAR_OBSIDIAN = "Ich habe dafür gesorgt, dass sie feurig schießt.",
		SPEAR_POISON = "Ich habe dafür gesorgt, dass sie ordentlich schießt.",
		SPOILED_FISH = "Das sollte ich lieber entsorgen.",
		STUNGRAY = "Es riecht ziemlich scheußlich.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Es ist grimmig bewacht.",
			GENERIC = "Das wird nicht mehr zur See fahren.",
		},
		SUNKEN_BOAT_BURNT = "Die Zeit verurteilt alles.",
		SUNKEN_BOAT_TRINKET_1 = "Das sieht aus... Äh, wie sieht das denn aus?",
		SUNKEN_BOAT_TRINKET_2 = "Ich hab das Gefühl, ich werde verspottet.",
		SUNKEN_BOAT_TRINKET_3 = "Nicht sehr modisch, aber funktionell.",
		SUNKEN_BOAT_TRINKET_4 = "Dies ist eine ziemlich fortschrittliche Technologie.",
		SUNKEN_BOAT_TRINKET_5 = "Das war wahrscheinlich vorher schon potthässlich.",
		SUPERTELESCOPE = "Damit könnte ich mir einen Überblick verschaffen.",
		SWEETPOTATOSOUFFLE = "Hm, das sieht halbwegs genießbar aus.",
		SWEET_POTATO = "Das kann gekocht werden.",
		SWEET_POTATO_COOKED = "Selbstgemacht ist immer am besten.",
		SWEET_POTATO_PLANTED = "Ich habe Schlimmeres gegessen. Viel schlimmer.",
		SWEET_POTATO_SEEDS = "Vielleicht wächst etwas, wenn ich die Dinger vergrabe.",
		SWIMMINGHORROR = "Ich hab genug von euch!",
		SWORDFISH = "Ah, ein Trainigspartner!",
		TELEPORTATO_SW_BASE = "Da entsteht etwas ziemlich Schönes.",
		TELEPORTATO_SW_BOX = "Noch ein Teil des Puzzles.",
		TELEPORTATO_SW_CRANK = "Ausgezeichnet. Nicht mehr lange.",
		TELEPORTATO_SW_POTATO = "Ich gebe zu, es ist ein wenig lächerlich.",
		TELEPORTATO_SW_RING = "Ah, noch ein Teil.",
		TELESCOPE = "Damit könnte ich mir einen Überblick verschaffen.",
		THATCHPACK = "Nicht viel, aber der zusätzliche Platz ist besser als nichts.",
		TIDALPOOL = "Meine Liebe zu dir ist tiefer als der Ozean.",
		TIDAL_PLANT = "Ein klein wenig Schutz.",
		TIGEREYE = "Ein Gentleman fasst sowas nur mit Handschuhen an.",
		TIGERSHARK = "Passender Name.",
		TOUCAN = "Buntes Ungeziefer.",
		TRAWLNET = "Ich will die nicht länger benutzen.",
		TRAWLNETDROPPED =
		{
			GENERIC = "Stell dir vor, was ich daraus alles kochen kann.",
			SOON = "Truhe der Tiefe",
			SOONISH = "Widerlich, aber auch nützlich auf seine eigene Weise.",
		},
		TRIDENT = "Eine Gabel für den König der Meere.",
		TRINKET_13 = "Mal was anderes als immer nur Meerwasser.",
		TRINKET_14 = "Das scheint mir keine gute Idee zu sein.",
		TRINKET_15 = "Die hat nur vier Saiten.",
		TRINKET_16 = "Buchstaben und Zahlen. Vielleicht ein Geheimcode?",
		TRINKET_17 = "Das war wahrscheinlich vorher schon potthässlich.",
		TRINKET_18 = "Ein bisschen Alleskleber und das ist das reinste Meisterwerk.",
		TRINKET_19 = "Weder rot noch blau.",
		TRINKET_20 = "Das sieht aus... Äh, wie sieht das denn aus?",
		TRINKET_21 = "Nett und angenehm warm.",
		TRINKET_22 = "Sieht aus, wie etwas was man auf einem Flohmarkt findet.",
		TRINKET_23 = "So, jetzt gibt es nichts mehr zum Pflücken.",
		TROPICAL_FISH = "Das gehört auf einen Spieß.",
		TUNACAN = "Vermutlich ist das Thunfisch drin.",
		TURBINE_BLADES = "Ein Schlüsselloch.",
		TURF_ASH = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_BEACH = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_DESERTDIRT = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_FUNGUS_GREEN = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_FUNGUS_RED = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_JUNGLE = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_MAGMAFIELD = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_MEADOW = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_SNAKESKINFLOOR = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_SWAMP = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_TIDALMARSH = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TURF_VOLCANO = "DAS SCHEINT EINE ART PROJEKTION ZU SEIN.",
		TWISTER = "Das würde ich lieber nicht.",
		TWISTER_SEAL = "Süß, oder?",
		VENOMGLAND = "Eine Heilung für deine Probleme.",
		VINE = "Eine knorrige und verworrene Oberfläche.",
		VOLCANO = "Ich spüre seine Macht...",
		VOLCANOSTAFF = "Wie für meine Hand gemacht.",
		VOLCANO_ALTAR =
		{
			GENERIC = "Hier scheint etwas seziert worden zu sein.",
			OPEN = "Soll ich es wagen, mit Kräften außerhalb meiner Kontrolle zu spielen?",
		},
		VOLCANO_ALTAR_BROKEN = "Echt schade.",
		VOLCANO_ALTAR_TOWER = "Was für eine interessante Struktur.",
		VOLCANO_EXIT = "Ich muss dann mal los.",
		VOLCANO_SHRUB = "Hätte ich Mitleid, gäbe ich es diesem Baum.",
		WALLYINTRO_DEBRIS = "Was ist das für Unsinn?",
		WALL_LIMESTONE = "Die wird halten.",
		WALL_LIMESTONE_ITEM = "Wo soll ich mit dem Bau meiner Festung beginnen?",
		WATERMELON_SEEDS = "Die könnte ich wahrscheinlich pflanzen.",
		WATERYGRAVE = "Nicht jeder findet eine letzte Ruhestätte.",
		WHALE_BLUE = "Ergib dich.",
		WHALE_BUBBLES = "Jetzt hast du dich verraten, Kumpel.",
		WHALE_CARCASS_BLUE = "Es kommt nicht auf die Größe an!",
		WHALE_CARCASS_WHITE = "Ich habe triumphiert.",
		WHALE_TRACK = "Ich verfolge ihn.",
		WHALE_WHITE = "Wir treffen uns irgendwann wieder.",
		WILBUR_CROWN = "Innen ist sie dreckig.",
		WILBUR_UNLOCK = "Tja, jetzt brauch ich dich auch nicht mehr zurückschicken.",
		WILDBORE = "Ich werde dieses schweinische Brut entsorgen.",
		WILDBOREHEAD = "Nette Umgebung.",
		WILDBOREHOUSE = "Gilt das hier schon als Architektur?",
		WIND_CONCH = "Außen schön, innen zerstörerisch.",
		WOODLEGSBOAT = "Sieht sicher aus.",
		WOODLEGSHAT = "Verwegen...",
		WOODLEGSSAIL = "Ein gutes Segel.",
		WOODLEGS_CAGE = "Auf irgendeine Weise sind wir alle gefangen.",
		WOODLEGS_KEY1 = "Marode.",
		WOODLEGS_KEY2 = "Ein Schlüssel aus reinem Gold.",
		WOODLEGS_KEY3 = "Ganz normales Eisen.",
		WRECK = "Die hatten keine Chance.",
		CALIFORNIAROLL = "Eines Tagen werden wir uns wiedertreffen.",
	},
	DESCRIBE_GENERIC = "Sag du es mir.",
	DESCRIBE_TOODARK = "Ich kann in der Dunkelheit nichts sehen.",
	DESCRIBE_SMOLDERING = "Es wird nicht mehr lange dauern, bis es in Flammen steht.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Das war unklug.",
	},
}
