return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Vou esperar até que ele não esteja olhando.",
			GENERIC = "Isso não pode ser raspado.",
			NOBITS = "Não posso raspar quando não tem cabelo.",
		},
		WRITE =
        {
            GENERIC = "Wolfgang não é bom com letras pequenas.",
        },
		RUMMAGE =
        {   
            GENERIC = "Talvez Wolfgang faça mais tarde.",
        },
		COOK =
        {
            GENERIC = "Wolfgang não está com humor para cozinhar.",
            TOOFAR = "Panela é pequena ou só está longe?",
        },
		REPAIRBOAT =
		{
			GENERIC = "O barquinho não tem danos para consertar! Wolfgang poderia dar um soco nele?",
		},
		STORE =
		{
			GENERIC = "Vou fazer caber!",
			NOTALLOWED = "Pf! Inútil.",
		},
		GIVE =
        {
            DEAD = "Você sabe que está morto, sim?",
            SLEEPING = "Está dormindo agora!",
            BUSY = "O Poderoso Wolfgang tenta de novo logo!",
        },
        CHANGEIN =
        {
            GENERIC = "Roupas só para rasgar com músculos fortes!",
            BURNING = "Roupas íntimas da semana de Wolfgang queimando? Wolfgang está triste.",
        },
        TEACH =
        {
            KNOWN = "Wolfgang já sabe disso!",
            CANTLEARN = "Não entendo.",
        },
	},
	ACTIONFAIL_GENERIC = "Não sou forte o suficiente para fazer isso.",
	
	ANNOUNCE_NORMALTOMIGHTY="SOU PODEROSO!",
	ANNOUNCE_NORMALTOWIMPY="Não estou me sentindo muito bem.",
	ANNOUNCE_WIMPYTONORMAL="Wolfgang é melhor.",
	ANNOUNCE_MIGHTYTONORMAL="Preciso encher minha poderosa barriga de novo!",

	ANNOUNCE_MAGIC_FAIL = "Não está fazendo as mágicas agora. Por quê?",
	ANNOUNCE_NOSLEEPONFIRE = "Está muito quente para dormir.",
	ANNOUNCE_NODANGERSIESTA = "Wolfgang prefere lutar a cochilar.",
	ANNOUNCE_NONIGHTSIESTA = "Wolfgang tem princípios contra cochilo à noite.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Wolfgang está tenso. Muito tenso para relaxar.",
	ANNOUNCE_NOHUNGERSIESTA = "Wolfgang tira cochilo depois da hora de comer.",
	ANNOUNCE_SHELTER = "Wolfgang se esconde embaixo da árvore.",
	ANNOUNCE_BURNT = "Foguinho, não é justo!",
	ANNOUNCE_TOOL_SLIP = "É muito escorregadio para segurar!",
	ANNOUNCE_DAMP = "Hora da água.",
	ANNOUNCE_WET = "Wolfgang não gosta da hora do banho.",
	ANNOUNCE_WETTER = "É como sentar em um lago.",
	ANNOUNCE_SOAKED = "Wolfgang talvez seja agora feito de água.",
	ANNOUNCE_ADVENTUREFAIL = "Da próxima vez serei mais bravo!",
	ANNOUNCE_BOOMERANG = "Ah! Por que você me machucou, pauzinho de jogar?",
	ANNOUNCE_CHARLIE = "Mostre-se!",
	ANNOUNCE_CHARLIE_ATTACK = "Ow! Me pegou!",
	ANNOUNCE_COLD = "Brrrrrrr! Está gelado!",
	ANNOUNCE_HOT = "Rá, é grudento e quente!",
	ANNOUNCE_CRAFTING_FAIL = "Preciso juntar mais coisas para fazer isso.",
	ANNOUNCE_DUSK = "A hora assustadora está chegando.",

	ANNOUNCE_ENTER_DARK = "Não posso ver! Estou com medo!",
	ANNOUNCE_ENTER_LIGHT = "Consigo ver de novo!",
	ANNOUNCE_HOUNDS = "Ouço filhotes!",
	ANNOUNCE_HUNGRY = "Minha poderosa barriga está vazia!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Animal está perto!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Nenhum animal aqui.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Rastros de animais virou lama.",
	ANNOUNCE_INV_FULL = "Meus braços fortes não podem carregar mais.",
	ANNOUNCE_FAN_OUT = "O ventiladorzinho está quebrado!",
    ANNOUNCE_COMPASS_OUT = "A agulhinha quebrou!",
	ANNOUNCE_PECKED = "O que eu fiz para merecer isso?",
	ANNOUNCE_TORCH_OUT = "Ah não! A luz se foi!",
	ANNOUNCE_WORMHOLE = "Me faz me sentir vivo.",
	ANNOUNCE_TRAP_WENT_OFF = "Ack! Não faça surpresa para Wolfgang!",
    ANNOUNCE_QUAKE = "Solo treme. Wolfgang odeia solo trêmulo.",
    ANNOUNCE_NODANGERSLEEP = "Wolfgang prefere luta a dormir.",
    ANNOUNCE_UNIMPLEMENTED = "Não está pronto.",
    ANNOUNCE_NOHUNGERSLEEP = "Wolfgang diz, nunca dormir com estômago vazio.",
    ANNOUNCE_FREEDOM = "Estou livre! Forte liberdade!",
    ANNOUNCE_RESEARCH = "Muita informação.",
    ANNOUNCE_NO_TRAP = "Fácil como levantar pesos.",
    ANNOUNCE_HIGHRESEARCH = "Talvez seja muita informação.",
    ANNOUNCE_THORNS = "Pontudo não é justo!",
    ANNOUNCE_NODAYSLEEP_CAVE = "É caverna assustadora.",
    ANNOUNCE_BEES = "Abelhas! Homens insetos picadores nojentos!",
    ANNOUNCE_KNOCKEDOUT = "Ugh, devo ter acertado a cabeça.",
    ANNOUNCE_LOWRESEARCH = "É pequena informação.",
    ANNOUNCE_DEERCLOPS = "Parece que o homem grande e forte está vindo.",
    ANNOUNCE_MOSQUITOS = "Wolfgang precisa do sangue, saiam, insetos chupadores!",
    ANNOUNCE_NODAYSLEEP = "Está muito claro para dormir.",
	ANNOUNCE_CANFIX = "\nO poderoso cérebro poderia melhorar as coisas!",
	ANNOUNCE_ACCOMPLISHMENT= "Fiz grandes coisas com a flechinha!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Derrotei a flecha pequena!",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Não é cocô suficiente.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Relâmpago é fraco comparado com as roupas de Wolfgang.",
	ANNOUNCE_WORMS = "Terra tremendo sob os pés do poderoso Wolfgang!",

	ANNOUNCE_OTHER_WORLD_PLANT = "Não é poderosa o suficiente para crescer aqui! Não como Wolfgang!",

	ANNOUNCE_BOAT_DAMAGED = "Navio é fraco! Precisa de momento de conserto.",
	ANNOUNCE_BOAT_SINKING = "Vou lutar contra o mar!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Wolfgang vai golpear a morte!",
	ANNOUNCE_CRAB_ESCAPE = "Sirelho fugiu. Não culpo ele.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Boa comida deixa Wolfgang forte!",
		PAINFUL = "Ooooh. Estou com dor de barriga.",
		SPOILED = "Eca! Tem gosto de lixo!",
		STALE = "Tem gosto esquisito.",
		INVALID = "Hahah! Isso não é comida!",
		YUCKY = "Estômago não é forte o suficiente para isso.",
	},
	ANNOUNCE_MAPWRAP_LOSECONTROL = "O barco não está ouvindo o poderoso Wolfgang!",
	ANNOUNCE_MAPWRAP_RETURN = "Wolfgang não pode ser detido!",
	ANNOUNCE_MAPWRAP_WARN = "Está ficando assustador!",
	ANNOUNCE_MORETREASURE = "Wolfgang encontrou mais reluzentes!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Tesouro não parece estar perto.",
	ANNOUNCE_SHARX = "O Wolfgang fez novos amigos!",
	ANNOUNCE_TRAWL_FULL = "Rede está gordinha com tesouros!",
	ANNOUNCE_TREASURE = "Wolfgang vê presentes!",
	ANNOUNCE_VOLCANO_ERUPT = "Rá rá! Hora de lutar com MONTANHA!",
	ANNOUNCE_WAVE_BOOST = "Sou poderoso!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "A morte te encontrará, grande peixe!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Argh! O grande peixe superou o Wolfgang!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "O Wolfgang não pode seguir o grande peixe!",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Eh... Wolfgang não sabe ler.",
	},

	BATTLECRY =
	{
		GENERIC = "Vou te dar um soco!",
		PIG = "Desculpe, meu amigo!",
		PREY = "Bam! Bam! Bam!",
		SPIDER = "Morre, inseto assustador do mau!",
		SPIDER_WARRIOR = "Ainda sou mais forte, inseto assustador!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Rá! Eu venci!",
		PIG = "Eu te perdoo, homem porco.",
		PREY = "Continua correndo!",
		SPIDER = "Ele fugiu de mim.",
		SPIDER_WARRIOR = "Ele sabe que eu sou mais forte.",
	},
	DESCRIBE =
	{
		BABYOX = "Ele vai crescer muito forte! Ou é ela?",
		BIGFISHINGROD = "Está fisgando peixe grande?",
		BLOWDART_POISON = "É como vários pequenos socos!",
		COFFEEBOT = "É trabalhador esforçado.",
		COMPASS =
		{
			E = "É leste.",
			GENERIC = "É todas direções, mas nenhuma direção.",
			N = "É norte.",
			NE = "É nordeste.",
			NW = "É noroeste.",
			S = "É sul.",
			SE = "É sudeste.",
			SW = "É sudoeste.",
			W = "É oeste.",
		},
		DEPLETED_BAMBOOTREE = "O arbusto já era.",
		DEPLETED_BUSH_VINE = "Videira tem aparência patética!",
		DEPLETED_GRASS_WATER = "Talvez grama só precise comer.",
		DEVTOOL = "Wolfgang vai esmagar!",
		DEVTOOL_NODEV = "Bam!",
		MUSSELBOUILLABAISE = "Isso pertence à boca do Wolfgang.",
		OBSIDIANSPEARGUN = "Não é tão divertido quanto socos, mas ainda é bem bom!",
		RELIC =
		{
			BROKEN = "Tiny bits.",
			GENERIC = "Is dumb thing.",
		},
		SPEARGUN_POISON = "Meu disparador de doenças!",
		SUPERTELESCOPE = "Deixa os olhos fortes!",
		SWEETPOTATOSOUFFLE = "Wolfgang vai comer!",
		TREASURECHEST_TRAP = "Raagh!",
		WOODLEGSBOAT = "É barco muito ruim.",
		WOODLEGSHAT = "É roupa de cabeça.",
		WOODLEGSSAIL = "É vela assustadora!",
		WORMHOLE_LIMITED = "It is weak and feeble.",
		GLOMMER = "Por que você me segue, inseto estranho?",
        GLOMMERFLOWER = 
        {
        	GENERIC = "É flor brilhante.",
        	DEAD = "É flor triste e brilhante.",
        },
        GLOMMERWINGS = "Tem cheiro de asas de fada.",
        GLOMMERFUEL = "Inseto esquisito fez cocô esquisito.",
        BELL = "O sino faz um som gracioso.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Por que a estátua não está voando?",
        	EMPTY = "Bam!",
    	},
		WEBBERSKULL = "Esmago crânio.",
		MOLE =
		{
			HELD = "Wolfgang tem misericórdia de animalzinho macio.",
			UNDERGROUND = "Fique no subterrâneo onde você está a salvo de Wolfgang.",
			ABOVEGROUND = "Agora você conhecerá a força de Wolfgang.",
		},
		MOLEHILL = "Buraco de toupeira.",
		MOLEHAT = "Pele de toupeira é flexível.",
		NIGHTSTICK = "O Wolfgang gosta mais dos punhos.",
		RABBITHOUSE=
		{
			GENERIC = "Estou ouvindo alguém mastigando lá dentro.",
			BURNT = "Não tem mais ninguém mastigando.",
		},
		TURF_DECIDUOUS = "Pedras de pisar.",
		TURF_SANDY = "Step stones.",
		TURF_BADLANDS = "Pedras de pisar.",
		BEARGER = "Wolfgang não quer lutar com urso grande.",
		BEARGERVEST = "Camisa de urso grande.",
		ICEPACK = "Saco peludo.",
		BEARGER_FUR = "É como o cabelo no peito de Wolfgang.",
		BIGFOOT = "O pé é muito grande!",
		BONESHARD = "Wolfgang destrói e faz ossos menores!",
		BUZZARD = "Continue.",
		CACTUS = 
		{
			GENERIC = "Wolfgang não é como planta afiada.",
			PICKED = "Rá! É planta lisa.",
		},
		CACTUS_MEAT_COOKED = "É seguro agora.",
		CACTUS_MEAT = "Carne planta espinhosa.",
		CACTUS_FLOWER = "Não vale a pena.",
		COLDFIRE =
		{
			EMBERS = "A escuridão está vindo!",
			GENERIC = "Adeus, tempos escuros!",
			HIGH = "É muito fogo!",
			LOW = "O fogo não está frio o suficiente.",
			NORMAL = "É fogo bom!",
			OUT = "Ohoh. Desligou.",
		},
		CATCOON = "Wolfgang não confia nele.",
		CATCOONDEN = 
		{
			GENERIC = "Toco é suspeito.",
			EMPTY = "Wolfgang mais confortável agora que o toco está vazio.",
		},
		CATCOONHAT = "Agora Wolfgang não confia em si mesmo.",
		COONTAIL = "Parte de gato sacolejante.",
		COOKPOT =
		{
			COOKING_LONG = "Isso leva muito tempo.",
			COOKING_SHORT = "Está quase pronto!",
			DONE = "É hora de comer!",
			EMPTY = "Panela vazia faz Wolfgang pensar pensamentos famintos.",
			BURNT = "A panela está morta.",
		},
		EYEBRELLAHAT =	"Está sempre olhando para cima.",
		ARMORDRAGONFLY = "Wolfgang não precisa de proteção.",
		DRAGON_SCALES = "Escamas brilhantes.",
		DRAGONFLYCHEST = "O baú não tem medo de fogo.",
		DECIDUOUSTREE = 
		{
			BURNING = "Quebrei.",
			BURNT = "É pequeno e está quebrado agora.",
			CHOPPED = "Rá! Eu venci!",
			GENERIC = "Oi, árvore!",
			POISON = "É árvore grande e irritada.",
		},
		ACORN_COOKED = "Wolfgang cozinha árvore da noz.",
		BIRCHNUTDRAKE = "É noz pequena e braba.",
		FARMPLOT =
		{
			GENERIC = "Vou cultivar plantas poderosas aqui!",
			GROWING = "Cresçam, amiguinhos! Cresçam!",
			NEEDSFERTILIZER = "A terra não é terrosa o suficiente para fazer plantas.",
			BURNT = "Sem mais cultivo.",
		},
		COLDFIREPIT =
		{
			EMBERS = "A escuridão está vindo!",
			GENERIC = "Adeus, tempos escuros!",
			HIGH = "É muito fogo!",
			LOW = "O fogo não está frio o suficiente.",
			NORMAL = "É fogo bom!",
			OUT = "Ohoh. Desligou.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Posso jogar melhor.",
			OFF = "A máquina sabe que o Wolfgang é mais forte.",
			LOWFUEL = "Está com fome, máquina?",
		},
		ICEHAT = "Por que colocar gelo grande na cabeça?",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Oi, bode.",
			CHARGED = "É clarão nos olhos.",
		},
		LIGHTNINGGOATHORN = "Ossinho de relâmpago.",
		GOATMILK = "Leite para músculos!",
		MEATRACK =
		{
			DONE = "Hmm, couro carnudo!",
			DRYING = "Sequem, coisas carnudas, sequem!",
			DRYINGINRAIN = "Vai embora, chuva! A carne está secando!",
			GENERIC = "Posso secar carne!",
			BURNT = "Não pode secar carne agora.",
		},
		MERMHEAD = 
		{
			GENERIC = "Que coisa mais linda!",
			BURNT = "Não é tão atraente agora.",
		},
		MERMHOUSE = 
		{
			GENERIC = "A casa não era forte o suficiente.",
			BURNT = "A casa realmente não era forte o suficiente.",
		},
		FLOWERSALAD = "Não é espinafre, mas ainda pode funcionar!",
        ICECREAM = "Bem, é domingo afinal de contas.",
        WATERMELONICLE = "Rá! Melancia no pauzinho.",
        TRAILMIX = "Bagas e nozes, bagas e nozes!",
        HOTCHILI = "Rá, rá, nada é picante de mais para Wolfgang!",
        GUACAMOLE = "Wolfgang não confia na polpa verde.",
		MOOSE = "Criatura muito estranha.",
		MOOSEEGG = "Café da manhã para toda a família!",
		MOSSLING = "Mmmm. Ainda é café da manhã, eu acho.",
		FEATHERFAN = "Rá! É tão grande quanto cabeça!",
		MINIFAN = "É tão enrolado quando eu corro! Haha!",
		TROPICALFAN = "Rá! É tão grande quanto cabeça!",
		GOOSE_FEATHER = "Cosquinha, cosquinha!",
		STAFF_TORNADO = "Gira, gira!",
		PIGHEAD = 
		{	
			GENERIC = "Por que a cara triste?",
			BURNT = "Por que não tem cara?",
		},
		PIGHOUSE =
		{
			FULL = "Ei! Vem aqui, homem porco!",
			GENERIC = "A porta é muito pequena para mim.",
			LIGHTSOUT = "Para onde ele foi?",
			BURNT = "A casa do porco se foi.",
		},
		FERTILIZER = "Balde cheio de fedor.",
		RAINOMETER = 
		{	
			GENERIC = "Splish! Splash!",
			BURNT = "Estalando!",
		},
		RAINCOAT = "Seco é bom.",
		RAINHAT = "Como água das costas da toupeira.",
		RESEARCHLAB = 
		{	
			GENERIC = "Não tenho certeza de como me sinto sobre... ciência.",
			BURNT = "A ciência não é tão forte afinal de contas.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Não tenho certeza de como me sinto sobre... ciência.",
			BURNT = "A ciência não é tão forte afinal de contas.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "O que Wolfgang fez?",
			BURNT = "Bem, agora acabou.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Chapéu não só para a cabeça.",
			BURNT = "Chapéu também para queimar.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Não vou morrer.",
			BURNT = "Melhor ele que o Wolfgang da vida real.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Pedras feitas de água.",
			MELTED = "Não consigo pegar água.",
		},
		ROCK_ICE_MELTED = "Não consigo pegar água.",
		ICE = "Bom para tira-gosto refrescante.",
        REFLECTIVEVEST = "Um colete é um colete.",
		HAWAIIANSHIRT = "É camisa de férias.",
		TENT = 
		{
			GENERIC = "É hora de um cochilo poderoso.",
			BURNT = "Não resta nada onde cochilar.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Lugar de cochilo.",
			BURNT = "O lugar de cochilo se foi.",
		},
		TRANSISTOR = "Fecho de ciência.",
		TREASURECHEST = 
		{
			GENERIC = "Eu coloco coisas aí!",
			BURNT = "Nada vai continuar aí dentro.",
		},
		TUMBLEWEED = "Volte, bolinha rolante!",
		GRASS_UMBRELLA = "Não gosto desse guarda-chuvinha.",
		PALMLEAF_UMBRELLA = "Não gosto desse guarda-chuvinha.",
		UNIMPLEMENTED = "Não confio em negócios inacabados.",
		WALL_HAY = 
		{	
			GENERIC = "A parede é de grama!",
			BURNT = "A grama queimou!",
		},
		WALL_WOOD = 
		{
			GENERIC = "Olá, gravetos pontudos!",
			BURNT = "Adeus, gravetos pontudos!",
		},
		WARG = "Big puppy!",
		WATERMELON = "Tantas sementes.",
		WATERMELON_COOKED = "Eu cozinho sementes de melancia.",
		WATERMELONHAT = "Por que não usar melancia na cabeça? Rá rá!",
		WINTEROMETER = 
		{
			GENERIC = "Frio sobe! Vermelho desce!",
			BURNT = "Chamas sobem! Máquina de medir desce!",
		},
		HOMESIGN = 
		{
			GENERIC = "Não é hora para ler placas!",
			BURNT = "Não dá para ler placa.",
		},
		BEEBOX =
		{
			GENERIC = "Muitas abelhas!",
			READY = "Está pronto para coleta!",
			FULLHONEY = "Está pronto para coleta!",
			NOHONEY = "Não tem mel.",
			SOMEHONEY = "Abelhas ocupadas.",
			BURNT = "As abelhas queimaram.",
		},
		LIVINGTREE = "Não gosto de árvores com olhos.",
		ICESTAFF = "Ponta congelada.",
		WORMLIGHT = "Luz bonita.",
		WORMLIGHT_LESSER = "Luzinha bacana.",
		WORM =
		{
		    PLANT = "Bem leve.",
		    DIRT = "A terra está se movendo?",
		    WORM = "Não esperava isso!",
		},
		WORMLIGHT_PLANT = "Bem leve.",
		EEL = "Preciso cozinhar isso!",
		EEL_COOKED = "Essa enguia foi assada.",
		UNAGI = "Comida me deixa poderoso!",
		EYETURRET = "A estrutura poderosa vai ajudar a lutar!",
		EYETURRET_ITEM = "Preciso colocar isso.",
		MINOTAURHORN = "É troféu de adversário poderoso.",
		MINOTAURCHEST = "O baú tem chifres fortes e grandes.",
		THULECITE_PIECES = "Posso unir esmagando para fazer uma peça maior!",
		POND_ALGAE = "A planta é tão pequena! É engraçado para mim.",
		GREENSTAFF = "Esse pauzinho tem uma pedra preciosa verde nele.",
		POTTEDFERN = "Me deixa feliz.",

		SLURPER = "Não! Não! Fica fora, cabeça!",
		SLURPER_PELT = "Ainda está se movendo!",
		SLURPERPELT = "Chumaço estranho de pelos.",
		ARMORSLURPER = "Se move com meus vários músculos.",
		ORANGEAMULET = "Posso usar no pescoço.",
		YELLOWSTAFF = "Pedra preciosa bonita em cima da vara.",
		TREECLUMP = "Não bloqueie o caminho do Wolfgang!",
		YELLOWGEM = "Pedra bonita.",
		ORANGEGEM = "Pedra bonita.",
		TELEBASE = 
		{
			VALID = "O brilho é um bom sinal.",
			GEMS = "Acho que não está funcionando.",
		},
		GEMSOCKET = 
		{
			VALID = "A pedra bonita agora paira.",
			GEMS = "Vazio.",
		},
		STAFFLIGHT = "Dói quando eu toco.",

        ANCIENT_ALTAR =
        {
        	WORKING = "É altar assustador e nojento.",
        	BROKEN = "É altar quebrado.",
        },  
        ANCIENT_ALTAR_BROKEN = "É altar quebrado.",

        ANCIENT_STATUE = "Feio, feio, feio.",

        LICHEN = "É um líquen!",
		CUTLICHEN = "Tem gosto horrível.",

        CAVE_BANANA = "Gostoso!",
        CAVE_BANANA_COOKED = "É quente e gostoso!",
        CAVE_BANANA_TREE = "Oi, árvore de cabeça para baixo.",
        CAVE_BANANA_BURNT = "É brasa.",
        ROCKY = "Ele é poderoso! Como eu!",

        BLUEAMULET = "Daria um bom cubo de gelo!",
		PURPLEAMULET = "Esse amuleto... assusta Wolfgang.",
		TELESTAFF = "Me dá dor de cabeça.",
		MINERHAT = "Lampião para colocar na cabeça.",
		MONKEY = "Homem macaco feioso!",
		MONKEYBARREL = "Essa... coisa. Não tem cheiro muito bom.",

		HOUNDSTOOTH="Dente de filhote.",
		ARMORSNURTLESHELL="É grudento por dentro.",
		BAT="Ratinho voador!",
		BATBAT = "Esse bastão me dá uma sensação estranha.",
		BATWING="É toda peluda e nojenta.",
		BATWING_COOKED="Crocante!",
		BEDROLL_FURRY="Como é confortável!",
		BUNNYMAN="Oi, coelho!",
		FLOWER_CAVE="É planta de luz.",
		FLOWER_CAVE_DOUBLE="É planta de luz.",
		FLOWER_CAVE_TRIPLE="É planta de luz.",
		GUANO="Mais cocô.",
		LANTERN="Me protege da escuridão.",
		LIGHTBULB="É comida?",
		MANRABBIT_TAIL="Fofinha!",
		MUSHTREE_TALL  ="Big mushtree is big.",
		MUSHTREE_MEDIUM="Mushy bush.",
		MUSHTREE_SMALL ="Mushy shrub.",
		MUSHTREE_TALL=
		{
            GENERIC = "Árvore de cogumelo grande é grande.",
            BLOOM = "Opa! Está ainda maior!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Arbusto molenga.",
            BLOOM = "Está se divertindo!",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Arbusto de coco melo.",
            BLOOM = "Até o cheiro é forte!",
        },
        MUSHTREE_TALL_WEBBED = "Oun, ânimo!",
        SPORE_TALL = "É pequeno inseto?",
        SPORE_MEDIUM = "É pequeno inseto?",
        SPORE_SMALL = "É pequeno inseto?",
        SPORE_TALL_INV = "Vou fazer isso meu bichinho.",
        SPORE_MEDIUM_INV = "Vou fazer isso meu bichinho.",
        SPORE_SMALL_INV = "Vou fazer isso meu bichinho.",

		SLURTLE="Rá! Você é lento!",
		SLURTLE_SHELLPIECES="Está quebrado.",
		SLURTLEHAT="Deixa minha cabeça segura.",
		SLURTLEHOLE="Buraco cheio de lesmas.",
		SLURTLESLIME="Meleca gigante!",
		SNURTLE="Espiral!",
		SPIDER_HIDER="É aranha assustada!",
		SPIDER_SPITTER="Pft! Pft!",
		SPIDERHOLE="Aranhas por tudo.",
		STALAGMITE="É pontudo.",
		STALAGMITE_FULL="É pontudo.",
		STALAGMITE_LOW="É pontudo.",
		STALAGMITE_MED="É pontudo.",
		STALAGMITE_TALL="Rocha tentando alcançar o teto.",
		STALAGMITE_TALL_FULL="Rocha tentando alcançar o teto.",
		STALAGMITE_TALL_LOW="Rocha tentando alcançar o teto.",
		STALAGMITE_TALL_MED="Rocha tentando alcançar o teto.",

		TURF_CARPETFLOOR = "Pedras de pisar.",
		TURF_CHECKERFLOOR = "Pedras de pisar.",
		TURF_DIRT = "Pedras de pisar.",
		TURF_FOREST = "Pedras de pisar.",
		TURF_GRASS = "Pedras de pisar.",
		TURF_MARSH = "Pedras de pisar.",
		TURF_ROAD = "Pedras de pisar.",
		TURF_ROCKY = "Pedras de pisar.",
		TURF_SAVANNA = "Pedras de pisar.",
		TURF_WOODFLOOR = "Pedras de pisar.",

		TURF_CAVE="Pedras de pisar.",
		TURF_FUNGUS="Pedras de pisar.",
		TURF_SINKHOLE="Pedras de pisar.",
		TURF_UNDERROCK="Pedras de pisar.",
		TURF_MUD="Pedras de pisar.",

		POWCAKE = "É feita de nadas!",
        CAVE_ENTRANCE = 
        {
            GENERIC="Quem quer entrar no buraco de caverna assustador, mesmo!",
            OPEN = "O mundo tem umbigo!",
        },
        CAVE_EXIT = "Is dark and scary down here.",
        CAVE_EXIT = 
        {
            GENERIC = "Por favor, deixa o Wolfgang sair!",
            OPEN = "É escuro e assustador lá embaixo.",
        },
        CAVE_ENTRANCE_RUINS = "Nem mesmo eu sou tão poderoso.",

		MAXWELLPHONOGRAPH = "É caixa que canta!",
		BOOMERANG = "Bum! E rangue! Rá!",
		PIGGUARD = "É porquinho mau!",
		ADVENTURE_PORTAL = "É porta da boca! Diga: \"Ahhhh!\"",
		AMULET = "É muito bonito.",
		ANIMAL_TRACK = "O animal foi por aqui.",
		ARMORGRASS = "É pontudo.",
		ARMORMARBLE = "Amarro as pedras nos músculos.",
		ARMORWOOD = "É quase tão forte quanto a barriga!",
		ARMOR_SANITY = "É como usar um trapinho assustador!",
		ASH =
		{
			GENERIC = "É esqueleto de fogo.",
			REMAINS_GLOMMERFLOWER = "São pedaços queimados de flor do meu teletransporte!",
			REMAINS_EYE_BONE = "São pedaços queimados de osso ocular do meu teletransporte!",
			REMAINS_THINGIE = "São pedaços queimados de alguma coisa. Está morto agora...",
		},
		AXE = "Corta!",
		BABYBEEFALO = "Vaca cabeluda bebê!",
		BACKPACK = "É para carregar mais coisas.",
		BACONEGGS = "A comida tem gema! E carne! Mais forte!",
		BANDAGE = "Posso me consertar!",
		BASALT = "É mais forte até que eu!",
		BEARDHAIR = "Nojento. Eles não são do meu rosto.",
		BEDROLL_STRAW = "Hora do cochilo!",
		BEE =
		{
			GENERIC = "É gorda e tem cara de braba.",
			HELD = "Está segura no meu bolso.",
		},
		BEEFALO =
		{
			FOLLOWER = "A vaca cabeluda está me seguindo!",
			GENERIC = "É vaca cabeluda!",
			NAKED = "A vaca cabeluda não tem mais cabelo.",
			SLEEPING = "A vaca cabeluda está dormindo.",
		},
		BEEFALOHAT = "É chapéu bom!",
		BEEFALOWOOL = "Faço roupa de vaca cabeluda.",
		BEEHAT = "É chapéu para proteger das abelhas picantes.",
		BEEHIVE = "É uma colmeia!",
		BEEMINE = "É bola cheia de abelhas raivosas.",
		BEEMINE_MAXWELL = "É bola cheia de insetos picadores raivosos.",
		BERRIES = "Gostoso!",
		BERRIES_COOKED = "É mais gostoso!",
		BERRYBUSH =
		{
			BARREN = "Preciso fazer cocô em cima dela.",
			WITHERED = "É muito quente para o arbusto.",
			GENERIC = "Está cheio de bolas de comida!",
			PICKED = "A parte de comer se foi.",
		},
		BIRDCAGE =
		{
			GENERIC = "É casa para passarinhos.",
			OCCUPIED = "Oi, passarinho!",
			SLEEPING = "Eu deveria ficar quieto!",
			HUNGRY = "Ouço pequenos roncos!",
			STARVING = "Seu pequeno estômago está vazio!",
			DEAD = "Passarinho? Você está bem?",
			SKELETON = "Ele está bem.",
		},
		BIRDTRAP = "Vou pegar pássaro!",
		BIRD_EGG = "Pobre passarinho.",
		BIRD_EGG_COOKED = "Hmm!",
		BISHOP = "Padre!",
		BISHOP_CHARGE_HIT = "Rrrraa!",
		BLOWDART_FIRE = "Cuidado, Wolfgang.",
		BLOWDART_SLEEP = "Dardo faz sono nos inimigos.",
		BLOWDART_PIPE = "Dardo faz dor nos inimigos.",
		BLUEGEM = "Pedra bonita.",
		BLUEPRINT = "Desenhos bonitos!",
		BELL_BLUEPRINT = "Desenhos bonitos!",
		BLUE_CAP = "É bom para mim, eu acho.",
		BLUE_CAP_COOKED = "Não é o mesmo.",
		BLUE_MUSHROOM =
		{
			GENERIC = "É coco melo.",
			INGROUND = "O coco melo está se escondendo.",
			PICKED = "Já peguei o coco melo.",
		},
		BOARDS = "Eu quebro tora para fazer tábua!",
		BONESTEW = "É ensopado cheio de carne forte.",
		BUGNET = "Capture insetos.",
		BUSHHAT = "Sou tão sorrateiro!",
		BUTTER = "É amanteigada e tem gosto de inseto.",
		BUTTERFLY =
		{
			GENERIC = "É braboleta bonita?",
			HELD = "Meu bichinho de estimação!",
		},
		BUTTERFLYMUFFIN = "Wolfgang não conhecia o bolinho de inseto. Vou provar.",
		BUTTERFLYWINGS = "Não voa sem as asas!",
		CAMPFIRE =
		{
			EMBERS = "A escuridão está vindo!",
			GENERIC = "Adeus, tempos escuros!",
			HIGH = "É muito fogo!",
			LOW = "O fogo não é quente o suficiente.",
			NORMAL = "É fogo bom!",
			OUT = "Ohoh. Desligou.",
		},
		CANE = "Posso caminhar E acertar coisas!",
		CARROT = "É comida. Eu acho.",
		CARROT_COOKED = "Não é mais como carne depois de fazer cozinhamento.",
		CARROT_PLANTED = "Está se escondendo!",
		CARROT_SEEDS = "As sementes são muito pequenas.",
		CAVE_FERN = "Planta bonita!",
		CHARCOAL = "É como segurar arvorezinha morta.",
        CHESSJUNK1 = "Lixo de metal.",
        CHESSJUNK2 = "Lixo de metal.",
        CHESSJUNK3 = "Lixo de metal.",
		CHESTER = "Caixa estranha com pernas.",
		CHESTER_EYEBONE =
		{
			GENERIC = "É osso ocular. Osso ocular se conecta ao osso facial.",
			WAITING = "Agora dorme.",
		},
		COOKEDMEAT = "Deixei a carne boa com fogo!",
		COOKEDMONSTERMEAT = "Ainda não quero comer isso.",
		COOKEDSMALLMEAT = "É ainda menor cozido!",
		CORN = "É milho. O que esperar?",
		CORN_COOKED = "Pop pop pop! Rá rá, milho engraçado.",
		CORN_SEEDS = "É sementes para cultivar milho.",
		CROW =
		{
			GENERIC = "Não gosto de pássaros. Muito frágeis.",
			HELD = "Ele é barulhento.",
		},
		CUTGRASS = "Fiz uma pilha de grama.",
		CUTREEDS = "Fiz um amontoado de junco.",
		CUTSTONE = "Destruo pedra para fazer tijolo!",
		DEADLYFEAST = "Parece comida do mau.",
		DEERCLOPS = "Ele parece mais poderoso que eu!",
		DEERCLOPS_EYEBALL = "Eca, eca, eca!",
		DEPLETED_GRASS =
		{
			GENERIC = "É tufo de grama.",
		},
		DIRTPILE = "Terra terrosa.",
		DIVININGROD =
		{
			COLD = "A caixa robô está falando.",
			GENERIC = "É caixa robô.",
			HOT = "A caixa robô está me assustando.",
			WARM = "Rá! Essa é boa, caixa robô!",
			WARMER = "Caixa robô está ficando irritada...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Qual a finalidade?",
			READY = "Essa vara precisa de chave para ativar.",
			UNLOCKED = "A vara está ligada!",
		},
		DIVININGRODSTART = "É vara engraçada.",
		DRAGONFLY = "Estou confuso... é libélula ou libe-lula?",
		LAVASPIT = 
		{
			HOT = "São germes de boa quentes.",
			COOL = "São germes de boca dura frios.",
		},
		LAVA_POND = "Não é hora para nadar!",
		LAVAE = "Preciso correr!",
		LAVAE_PET = 
		{
			STARVING = "Bebezinho faminto!",
			HUNGRY = "Bebezinho com fome.",
			CONTENT = "Bebezinho parece contente.",
			GENERIC = "Bebezinho parece feliz.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "É feita de pedras?",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Ovinho está tremendo.",
			COMFY = "Ovinho... parece confortável.",
		},
		LAVAE_TOOTH = "Que dente poderoso!",

		DRAGONFRUIT = "É fruta engraçada.",
		DRAGONFRUIT_COOKED = "Está cozida, mas ainda parece estranha.",
		DRAGONFRUIT_SEEDS = "Poderia usar isso para cultivar fruta engraçada, talvez.",
		DRAGONPIE = "Torta feita com fruta vermelha engraçada.",
		DRUMSTICK = "Carne de perna para deixar pernas mais fortes.",
		DRUMSTICK_COOKED = "Roer o osso é bom.",
		DUG_BERRYBUSH = "Ele está frio e solitário.",
		DUG_GRASS = "Ele está frio e solitário.",
		DUG_MARSH_BUSH = "Ele está frio e solitário.",
		DUG_SAPLING = "Ele está frio e solitário.",
		DURIAN = "É fruta fedida e espinhosa.",
		DURIAN_COOKED = "Agora é fruta fedorenta, espinhosa, quente!",
		DURIAN_SEEDS = "Planta fruta espinhosa bebezinha.",
		EARMUFFSHAT = "Agora eu pareço um coelhinho!",
		EARMUFFHAT = "Agora eu pareço um coelhinho!",
		EGGPLANT = "Não é ovo!",
		EGGPLANT_COOKED = "Não tem gema! A gema é a parte mais forte!",
		EGGPLANT_SEEDS = "Berinjelinha falsa.",
		STUFFEDEGGPLANT = "Faço gema de outras comidas.",
		ACORN = 
		{
		    GENERIC = "Eu poderia esmagar essa semente árvore com minhas mãos!",
		    PLANTED = "Logo será árvore.",
		},
		EVERGREEN =
		{
			BURNING = "Quebrei.",
			BURNT = "É pequeno e está quebrado agora.",
			CHOPPED = "Rá! Eu venci!",
			GENERIC = "Oi, árvore!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Eu quebrei.",
			BURNT = "É pequeno e está quebrado agora.",
			CHOPPED = "Rá! Eu venci!",
			GENERIC = "Alegre-se, árvore!",
		},
		EYEPLANT = "Elas não são o que parecem.",
		FEATHERHAT = "É chapéu bobo de penas. Wolfgang pássaro agora?",
		FEATHER_CROW = "É pena de pássaro preto.",
		FEATHER_ROBIN = "É pena de pássaro vermelho.",
		FEATHER_ROBIN_WINTER = "É pena de pássaro branco.",
		FEM_PUPPET = "Cadeira assustadora assusta ela!",
		FIREFLIES =
		{
			GENERIC = "Brilhante!",
			HELD = "Meu bolso é brilhos!",
		},
		FIREHOUND = "Late!",
		FIREPIT =
		{
			EMBERS = "A escuridão está vindo!",
			GENERIC = "Adeus, tempos escuros!",
			HIGH = "É muito fogo!",
			LOW = "O fogo não é suficiente.",
			NORMAL = "É fogo bom!",
			OUT = "Ohoh. Desligou.",
		},
		FIRESTAFF = "É cajado para fazer fogo. Cuidado, Wolfgang.",
		FISH = "É peixento.",
		FISHINGROD = "É para pegar peixe no negócio lago.",
		FISHSTICKS = "Rá rá, nome engraçado.",
		FISHTACOS = "Wolfgang espera que não seja muito apimentado.",
		FISH_MED = "Está morto.",
		FISH_MED_COOKED = "Carne da água ainda deixa o Wolfgang forte.",
		FISH_COOKED = "Carne da água ainda deixa o Wolfgang forte.",
		FLINT = "É pedra, mas ahm, pontuda.",
		FLOWER = "Elas são muito bonitas.",
		FLOWER_WITHERED = "Oun, esse está triste.",
		FLOWERHAT = "É tão bonito!",
		FLOWER_EVIL = "Não é batata.",
		FOLIAGE = "Matei a planta bonita.",
		FOOTBALLHELMET = "É chapéu para fazer ataque corporal.",
		FROG =
		{
			DEAD = "É iguaria no meu país.",
			GENERIC = "Ei, sapinho.",
			SLEEPING = "Está dormindo.",
		},
		FROGLEGS = "É iguaria no meu país!",
		FROGGLEBUNWICH = "É sanduíche com carne de perna saborosa.",
		FROGLEGS_COOKED = "É principalmente gosto de galinha.",
		FRUITMEDLEY = "É taça de frutinhas.",
		GEARS = "Arrá! Quem tem músculos maiores agora?",
		GHOST = "Aaaaaaaaaaah!",
		GOLDENAXE = "Machado chique mais bom para cortar.",
		GOLDENPICKAXE = "Picareta chique faz esmagamento melhor.",
		GOLDENPITCHFORK = "Forcado chique é bom para bater no solo.",
		GOLDENSHOVEL = "Pá chique é boa fazedora de buracos.",
		GOLDNUGGET = "Dinheiro é para homens pequenos!",
		GRASS =
		{
			BARREN = "Precisa de cocô.",
			WITHERED = "A grama foi derrotada pelo calor.",
			BURNING = "Não é bom!",
			GENERIC = "É grama.",
			PICKED = "A grama foi derrotada!",
		},
		GREEN_CAP = "É para saladas. Eca!",
		GREEN_CAP_COOKED = "Não é o mesmo.",
		GREEN_MUSHROOM =
		{
			GENERIC = "É coco melo.",
			INGROUND = "O coco melo está se escondendo.",
			PICKED = "Já peguei o coco melo.",
		},
		GUNPOWDER = "Super pimenta!",
		HAMBAT = "Ainda é bom.",
		HAMMER = "Precisa de foice!",
		HEALINGSALVE = "Me faz me sentir vivo.",
		HEATROCK =
		{
			FROZEN = "Brrr! É pedra fria!",
			COLD = "Pedra está um pouco fria.",
			GENERIC = "Essa pedra arredondada é como a minha cabeça!",
			WARM = "É uma pedra bem normal.",
			HOT = "Não é o bastante para Wolfgang!",
		},
		HONEY = "É gostoso!",
		HONEYCOMB = "A abelha costumava viver lá dentro.",
		HONEYHAM = "Carne grande com doce é carne boa.",
		HONEYNUGGETS = "Carninhas com doce ainda são boas.",
		HORN = "É chifre de vaca cabeluda. Wolfgang ouve vaca cabeluda.",
		HOUND = "Au, au!",
		HOUNDMOUND = "É casa de ossos.",
		HOUNDBONE = "Cachorrinho chorão não foi forte o suficiente.",
		ICEBOX = "Caixa que faz frio!",
		ICEHOUND = "Nossa!",
		INSANITYROCK =
		{
			ACTIVE = "Está no meu caminho.",
			INACTIVE = "Rá. Pisei em obstaculozinho.",
		},
		JAMMYPRESERVES = "Se esvai como inimigozinho que esmago na mão.",
		KABOBS = "Comer no palitinho é bom.",
		KILLERBEE =
		{
			GENERIC = "Abelha braba!",
			HELD = "Minha abelha braba!",
		},
		KNIGHT = "Cavalinho!",
		KOALEFANT_SUMMER = "Carne de nariz!",
		KOALEFANT_WINTER = "Tão macio, que quero esmagar!",
		KRAMPUS = "Homem bode assustador! Corre!",
		KRAMPUS_SACK = "Tenho saco de homem bode.",
		LEIF = "Homem de madeira!",
		LEIF_SPARSE = "Homem de madeira!",
		LIGHTNING_ROD =
		{
			CHARGED = "Uuhhh, faíscas!",
			GENERIC = "É fio no céu!",
		},
		LITTLE_WALRUS = "Você acha que é mais forte que o velho?",
		LIVINGLOG = "Tora de cara estranha!",
		LOCKEDWES = "Um homenzinho fraco preso pelos homens estátua.",
		LOG = "Is thick like my arm.",
		LOG =
		{
			BURNING = "When I stick my hand over it, it tickles.",
			GENERIC = "Remains of tree-fights!",
		},
		LUREPLANT = "Você não engana Wolfgang!",
		LUREPLANTBULB = "Arrá! Quem é astuto agora?",
		MALE_PUPPET = "Cadeira assustadora assusta ele!",
		MANDRAKE =
		{
			DEAD = "Homenzinho planta morreu!",
			GENERIC = "É planta estranha.",
			PICKED = "Amiguinho homem planta!",
		},
		COOKEDMANDRAKE = "O homenzinho planta é comida?",
		MANDRAKESOUP = "Homenzinho planta é para fazer sopa!",
		MARBLE = "Posso levantar!",
		MARBLEPILLAR = "É muito pesado para levantar.",
		MARBLETREE = "Não tente bater na árvore.",
		MARSH_BUSH =
		{
			BURNING = "Oh, oh. Fogo espinhento.",
			GENERIC = "É espinhento!",
			PICKED = "Os espinhos machucam.",
		},
		BURNT_MARSH_BUSH = "Está queimado agora.",
		MARSH_PLANT = "É planta.",
		MARSH_TREE =
		{
			BURNING = "Queimo os espinhos!",
			BURNT = "Está espinhoso e preto agora.",
			CHOPPED = "Corto os espinhos fora!",
			GENERIC = "É espinhoso.",
		},
		MAXWELL = "Um traje elegante não é páreo para meus músculos!",
		MAXWELLHEAD = "Cabeça assustadora tem três metros de altura!",
		MAXWELLLIGHT = "Luz assustadora!",
		MAXWELLLOCK = "Cadeado assustador!",
		MAXWELLTHRONE = "Cadeira assustadora!",
		MEAT = "A carne me deixa forte!",
		MEATBALLS = "Bola de carnes me deixa forte!",
		MEAT_DRIED = "Parece couro, tem gosto de carne.",
		MERM = "É um homem peixo!",
		MONSTERLASAGNA = "Tem gosto de cabelos e carnes com massinha.",
		MONSTERMEAT = "Não está parecendo ser comida.",
		MONSTERMEAT_DRIED = "Parece couro, tem gosto de couro.",
		MOSQUITO =
		{
			GENERIC = "Me faz lembrar do tio!",
			HELD = "Chega de sangue para você!",
		},
		MOSQUITOSACK = "O tio não tinha o estômago assim.",
		MOUND =
		{
			DUG = "Desculpe, pessoas mortas.",
			GENERIC = "Assustador! Provavelmente está cheio de ossos!",
		},
		NIGHTLIGHT = "É brilho estranho.",
		NIGHTMAREFUEL = "Coisa assustadora.",
		NIGHTSWORD = "É real? Não é real? É afiado!",
		NITRE = "É pedra, mas diferente.",
		ONEMANBAND = "É grande e alto. Eu gosto!",
		PANDORASCHEST = "Caixa chique!",
		PANFLUTE = "Posso tocar música tradicional.",
		PAPYRUS = "É como papel.",
		PENGUIN = "Esses pássaros caminham estranho!",
		PERD = "Pássaro idiota pegou todas as bagas!",
		PEROGIES = "Wolfgang adora pierogi!",
		PETALS = "Isso tem cheiro bom.",
		PETALS_EVIL = "Eles fazem meu cérebro doer.",
		PHLEGM = "A rá rá rá! Melecas! Oh ho ho!",
		PICKAXE = "Careta!",
		PIGGYBACK = "Bolsa fedida!",
		PIGKING = "Rá! É pessoa boa!",
		PIGMAN =
		{
			DEAD = "Não! O porco está morto!",
			FOLLOWER = "É amigo agora!",
			GENERIC = "Oi, porco. Como você está?",
			GUARD = "Será que ele treina?",
			WEREPIG = "Porquinho brabo!",
		},
		PIGSKIN = "Por que bunda longa? Rá rá, Wolfgang é engraçado.",
		PIGTORCH = "Como o fogo é feito?",
		PINECONE = 
		{
		    GENERIC = "Eu poderia esmagar essa sementárvore com minhas mãos!",
		    PLANTED = "Logo será árvore.",
		},
		PINECONE_SAPLING = "Logo será árvore.",
        LUMPY_SAPLING = "Surgiu de dentro da terra!",
		PITCHFORK = "Me faz lembrar dos tempos de criança.",
		PLANTMEAT = "O que é isso? Carne para homem bebê?",
		PLANTMEAT_COOKED = "Está um pouco melhor agora.",
		PLANT_NORMAL =
		{
			GENERIC = "Folhosa!",
			GROWING = "Ainda está crescendo.",
			READY = "Mmmm. Agora está gostoso.",
			WITHERED = "É planta triste e seca.",
		},
		POMEGRANATE = "Parece cérebro de espertinho.",
		POMEGRANATE_COOKED = "Rá rá rá! Cozinho cérebro! Não é tão esperto agora.",
		POMEGRANATE_SEEDS = "É pedaço de cérebro?",
		POND = "Está cheio de água.",
		POOP = "Fedido!",
		SCORCHED_SKELETON = "Wolfgang não gosta disso!",
		PUMPKIN = "É tão grande quanto a cabeça de homem fraco! Não a cabeça de Wolfgang.",
		PUMPKINCOOKIE = "É biscoitinho gostoso.",
		PUMPKIN_COOKED = "Cozinho sua cabeça, homenzinho! Sou o mais forte Wolfgang.",
		PUMPKIN_LANTERN = "Agora é cabeça de verdade! Wolfgang com medo!",
		PUMPKIN_SEEDS = "Isso cresce do tamanho de comida de cabeça maluca.",
		PURPLEGEM = "Pedra mais bonita.",
		RABBIT =
		{
			GENERIC = "Coelhinho! Se escondeu de mim!",
			HELD = "Ele é meu amigo.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Você não pode ser esconder para sempre, carne saltitante!",
			SPRING = "Tem movimento da casa do coelho.",
		},
		RATATOUILLE = "É comida. Mais ou menos.",
		RAZOR = "Minha pele é forte demais para pelos!",
		REDGEM = "Pedra bonita.",
		RED_CAP = "Oh! É bonito e brilhante!",
		RED_CAP_COOKED = "Não é o mesmo.",
		RED_MUSHROOM =
		{
			GENERIC = "É coco melo.",
			INGROUND = "O coco melo está se escondendo.",
			PICKED = "Já peguei o coco melo.",
		},
		REEDS =
		{
			BURNING = "Não é bom!",
			GENERIC = "É grama aguada.",
			PICKED = "Superei os juncos!",
		},
        RELIC = 
        {
            GENERIC = "House stuff.",
            BROKEN = "Smashed all the way!",
        },
        RUBBLE = "Coisas de casa quebradas.",
		RESURRECTIONSTONE = "Pular na pedra!",
		ROBIN =
		{
			GENERIC = "É pássaro de cor vermelha bonito.",
			HELD = "É pássaro feliz no bolso.",
		},
		MOOSE_NESTING_GROUND = "É cama de bebê pássaro grande!",
		ROBIN_WINTER =
		{
			GENERIC = "É pássaro branco bonito.",
			HELD = "É pássaro fofo. Pássaro legal.",
		},
		ROBOT_PUPPET = "A cadeira assustadora assustou!",
		ROCK_LIGHT =
		{
			GENERIC = "Uma pilha de pedras com crosta.",
			OUT = "Rá! Mais para esmagar!",
			LOW = "Está ficando fria.",
			NORMAL = "Fogo líquido!",
        },
		ROCK = "É dura! Como eu!",
		ROCKS = "É pedra. O que você não entende?",
        ROOK = "Esse salta sobre a rainha!",
		ROPE = "Forte! Como eu!",
		ROTTENEGG = "Fedido!",
		SANITYROCK =
		{
			ACTIVE = "É bonita!",
			INACTIVE = "Está se escondendo no subterrâneo.",
		},
		SAPLING =
		{
			BURNING = "Ops.",
			WITHERED = "Árvore fracote não aguentou o calor.",
			GENERIC = "Árvore fracote! Sou mais forte que você!",
			PICKED = "Rá! Rá! Rá! A árvore é molenga!",
		},
		SEEDS = "Muito pequenas para comer.",
		SEEDS_COOKED = "O fogo deixou maior, posso comer agora.",
		SEWING_KIT = "É pontudo!",
		SHOVEL = "Colher de terra!",
		SILK = "É muito chique.",
		SKELETON = "Não tem músculo suficiente.",
		SKELETON_PLAYER = "Onde foram parar todos os músculos?!",
		SKULLCHEST = "Esse homem tinha cabeça grande!",
		SMALLBIRD =
		{
			GENERIC = "É passarinho bem pequeno.",
			HUNGRY = "Passarinho está com fome.",
			STARVING = "Passarinho vai morrer de fome.",
		},
		SMALLMEAT = "Preciso de mais carne!",
		SMALLMEAT_DRIED = "Parece couro, tem gosto de carne.",
		SPAT = "Parece tão amistoso e fofinho.",
		SPEAR = "Me deu uma felpa.",
		SPIDER =
		{
			DEAD = "É feita de gosma grudenta!",
			GENERIC = "Ele tem uma cara assustadora!",
			SLEEPING = "Caminhe em silêncio, ele talvez não me veja.",
		},
		SPIDERDEN = "Os insetos estão se escondendo lá dentro.",
		SPIDEREGGSACK = "Ovos de aranha nojenta.",
		SPIDERGLAND = "Tenro e bambo!",
		SPIDERHAT = "Gosto do beijinho do inseto gigante.",
		SPIDERQUEEN = "Ah não! Casa de inseto ambulante!",
		SPIDER_WARRIOR =
		{
			DEAD = "Agora não é assustador!",
			GENERIC = "Esse é ainda mais assustador.",
			SLEEPING = "Acho que não é inteligente cutucar.",
		},
		SPOILED_FOOD = "É bola de nojeira!",
		STATUEHARP = "Onde está a música bonita?",
		STATUEMAXWELL = "O homem é pedra agora! Muito complexo!",
		STEELWOOL = "É como os pelos do meu braço.",
		STINGER = "É afiado como espeto!",
		STRAWHAT = "É chapéu bom!",
		SUNKBOAT = "Está quebrado!",
		SWEATERVEST = "É colete com estampa para homem elegante.",
		TAFFY = "É bala para destruir!",
		TALLBIRD = "É o maior pássaro!",
		TALLBIRDEGG = "Tem um pássaro lá dentro.",
		TALLBIRDEGG_COOKED = "Pássaro cozido. Bom para o café da manhã!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Pássaro como cubo de gelo!",
			GENERIC = "O passarinho está tentando sair.",
			HOT = "É muito quente para o passarinho!",
			LONG = "Espero pelo pássaro.",
			SHORT = "O pássaro vem logo.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "É ovo grande!",
			PICKED = "É ninho de nada.",
		},
		TEENBIRD =
		{
			GENERIC = "Rá! Não é tão alto.",
			HUNGRY = "Está com fome e é barulhento.",
			STARVING = "Está com fome, é barulhento e brabo!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Não temo o que está além!",
			GENERIC = "Pedra estranha. Sento em cima?",
			LOCKED = "Ainda tem algo faltando.",
			PARTIAL = "Agora está ficando certo.",
		},
		TELEPORTATO_BOX = "Tem uma alavanquinha.",
		TELEPORTATO_CRANK = "Coisa flexível é feita de metal!",
		TELEPORTATO_POTATO = "Rá rá! Rá rá! Que batata feia!",
		TELEPORTATO_RING = "Vou dobrar e fazer um círculo perfeito!",
		TENTACLE = "Monstro magrelo!",
		TENTACLESPOTS = "Eca! Melequento!",
        TENTACLESPIKE = "Perfeito para colar!",
		TENTACLE_PILLAR_HOLE = "Estão fugindo do poderoso Wolfgang?",
		TENTACLE_PILLAR = "Uma porção de amiguinhos!",
		TENTACLE_PILLAR_ARM = "Bebezinho tentáculo! Rá!",
		TENTACLE_GARDEN = "Hmmmm, suspeito!",
		TOPHAT = "É chapéu bom!",
		TORCH = "Ataco a noite com pauzinho de fogo.",
		TRAP = "Nenhuma armadilha pode me segurar!",
		TRAP_TEETH = "Morde os traseiros de baixo!",
		TRAP_TEETH_MAXWELL = "Quem colocou isso é uma pessoa ruim!",
		TRINKET_1 = "Bolha de vidro!",
		TRINKET_10 = "São mastigadores de pérolas!",
		TRINKET_11 = "É muito estranho!",
		TRINKET_12 = "Eca.",
		TRINKET_2 = "Falsa saúde!",
		TRINKET_3 = "Nó é o que o Wolfgang esperava.",
		TRINKET_5 = "O que é faz?",
		TRINKET_6 = "Pedaços de robô.",
		TRINKET_7 = "Bola vai no buraco de madeira.",
		TRINKET_8 = "Endurecido, como o Wolfgang.",
		TRINKET_9 = "Pequenos botõezinhos.",
		TRUNKVEST_SUMMER = "É nariz peludo quente.",
		TRUNKVEST_WINTER = "Aconchegante e barulhento!",
		TRUNK_COOKED = "É nariz assado.",
		TRUNK_SUMMER = "É nariz caído.",
		TRUNK_WINTER = "É nariz cabeludo molenga.",
		TURKEYDINNER = "É bom banquete de carne de pássaro.",
		TWIGS = "Gravetos fracotes! Posso quebrá-los!",
		UMBRELLA = "A chuva machuca minha pele poderosa.",
		WAFFLES = "Por que o pão tem furos?",
		WALL_HAY_ITEM = "Palhas ásperas.",
		WALL_STONE = "A parede é forte como eu!",
		WALL_STONE_ITEM = "Pilhas de pedras!",
		WALL_RUINS = "O muro antigo é forte!",
		WALL_RUINS_ITEM = "Pilha de pedras velhas!",
		WALL_WOOD_ITEM = "Gravetos espetantes!",
		WALL_MOONROCK = "Pedra da Lua protege Wolfgang.",
		WALL_MOONROCK_ITEM = "Pode construir com o poder da Lua!",
		WALRUS = "Rá rá! É homem geleca bolhoso.",
		WALRUSHAT = "Chapéu de homem vaca marinha!",
		WALRUS_CAMP =
		{
			EMPTY = "Está trancado.",
			GENERIC = "Como é que eles cabem?",
		},
		WALRUS_TUSK = "Dente de homem vaca marinha!",
		WARDROBE = 
		{
			GENERIC = "Caixa de roupas!",
            BURNING = "Caixa de fogo!",
			BURNT = "Caixa acabou tudo.",
		},
		WARG = "Filhote grande!",
		WASPHIVE = "Mente diz não. Músculos dizem sim!",
		WETGOOP = "Wolfgang estragou comida!",
		WINTERHAT = "Deixa as orelhas felizes no frio!",
		WORMHOLE =
		{
			GENERIC = "Como travesseiro grande crescendo no solo.",
			OPEN = "Não pode ferir esse homem!",
		},
 		WORMHOLE_LIMITED = "Não está com cara boa.",
        ARMORRUINS = "Me proteger? Não preciso!",
        BISHOP_NIGHTMARE = "É homem brabo. Precisa relaxar.",
        GREENAMULET = "O que é isso?", 
        GREENGEM = "É bonita e não é esmagada. Como eu!",
        KNIGHT_NIGHTMARE = "Homem de metal engraçado.",
        MINOTAUR = "Forte! Como eu! Gosto dele!",    
        MULTITOOL_AXE_PICKAXE = "Cortar e cavar! Posso fazer isso o dia todo.",
        NIGHTMARELIGHT = "É luz, mas não é luz boa.",
        NIGHTMARE_TIMEPIECE =
        {
            WARN = "A luz má está chegando.",  
            WAXING = "A luz má está aqui e ficando mais forte.", 
            STEADY = "Acho que a luz má não fica mais forte.", 
            WANING = "A hora da luz má está acabando.", 
            DAWN = "A hora boa está chegando.", 
            CALM = "Sem luz má.", 
            NOMAGIC = "Protegido da luz má.", 
        },
        ORANGESTAFF = "É melhor caminhar, eu acho.",  
        ROOK_NIGHTMARE = "Não é páreo para meu peito poderoso.",
        RELIC = "É lixo?",
        RUINS_RUBBLE = "Vou deixar melhor com esmigalhar.",  
        RUINS_BAT = "É assustador.",
        RUINSHAT = "É chapéu para rei.",
        SPIDER_DROPPER = "Aranha assustadora de cima.", 
        THULECITE = "É rocha bonita.",
        YELLOWAMULET = "Está brilhando amarelo.",    
		ACCOMPLISHMENT_SHRINE = "Vou te derrotar, flechinha!",   

		WOODLEGS_CAGE = "Está trancado.",
		AERODYNAMICHAT = "Deixa pernas fortes livres para correr!",
		ANTIVENOM = "Wolfgang vai tirar o veneno flexionando as veias!",
		ARMORCACTUS = "Rá! Tente acertar o Wolfgang agora.",
		ARMORLIMESTONE = "Essa armadura poderosa vai me proteger!",
		ARMOROBSIDIAN = "É truque barato, mas Wolfgang gosta!",
		ARMORSEASHELL = "Tente seus truques sujos agora, criaturas de veneno.",
		ARMOR_LIFEJACKET = "Grande água do oceano não vai levar o Wolfgang agora!",
		ARMOR_SNAKESKIN = "Foi feita para exibir meus músculos poderosos.",
		ARMOR_WINDBREAKER = "Wolfgang mestre de quebrar vento!",
		ARMOUREDBOAT = "Você é forte, como eu.",
		BALLPHIN = "Venham e lutem comigo, amigos marinhos!", 
		BAMBOO = "Um material de construção muito forte!",
		BAMBOOTREE =
		{
			BURNT = "Não é tão poderoso agora.",
			CHOPPED = "Espero que cresça rápido.",
			GENERIC = "Logo colherei você, poderosa planta!",
		},
		BERMUDATRIANGLE = "Está dando sentimentos apreensivos.",
		BIOLUMINESCENCE = "Lindas luzes marinhas!",
		BLOWDART_FLUP = "É treino para meus poderosos pulmões!",
		BLUBBER = "Não é músculo.",
		BLUBBERSUIT = "Preferiria usar um traje de músculos!",
		BOAT = "A embarcação poderosa luta contra as águas.",
		BOATCANNON = "A arma mais poderosa!",
		BOATREPAIRKIT = "Restaure minha poderosa embarcação!",
		BOAT_LANTERN = "É luz mais segura.",
		BOAT_TORCH = "Chama no barco é boa ideia!",
		BOTTLELANTERN = "É uma boa maneira de manter a escuridão afastada.",
		BRAINJELLYHAT = "Agh! Está fazendo Wolfgang pensar!",
		BUOY = "Ahhh, está marcando algo.",
		BURIEDTREASURE = "É meu!",
		BUSH_VINE =
		{
			BURNT = "Cinza.",
			CHOPPED = "Ganhei. Você perdeu.",
			GENERIC = "É um arbusto. De videiras.",
		},
		CAPTAINHAT = "Olhe para o Wolfgang! Ele é capitão agora!",
		CARGOBOAT = "Que porão de armazenagem poderoso!",
		CHIMINEA = "Fique protegido do vento, foguinho.",
		CLOTHSAIL = "Vou capturar você, vento!",
		COCONADE =
		{
			BURNING = "Está queimando rápido.",
			GENERIC = "Quanto poder!",
		},
		COCONUT = 
		{
		    GENERIC = "Vou esmagar apenas com minhas mãos.",
		    PLANTED = "É arvorezinha! Muito pequena!",
		},
		COCONUT_COOKED = "Coco assado.",
		COCONUT_HALVED = "Wolfgang não teve problema para golpear e separar a concha dura em dois.",
		COFFEE = "Forte, como Wolfgang!",
		COFFEEBEANS = "Os grãozinhos dão força ao Wolfgang!",
		COFFEEBEANS_COOKED = "É grãos amargos!",
		COFFEEBUSH =
		{
			BARREN = "Para onde foram todos os grãos saborosos?",
			GENERIC = "Pé de café é altivo e forte.",
			PICKED = "Descanse agora, amigo.",
			WITHERED = "Está à porta da morte.",
		},
		CORAL = "É muito bonito! Vai triturar?",
		CORALREEF = "É muito frágil!",
		CORAL_BRAIN = "He he. Esguicha com o toque do Wolfgang.",
		CORAL_BRAIN_ROCK = "Cérebro de Wolfgang vai golpear esse cérebro.",
		CRAB =
		{
			GENERIC = "Se eu acertar ele, vai ser comida.",
			HIDDEN = "Dizem que há mariscos que vêm para o bem.",
		},
		CRABHOLE = "Sirelho é covarde.",
		CRATE = "Eu poderia esmagar.",
		CUTLASS = "Wolfgang está pronto para a batalha!",
		DEAD_SWORDFISH = "Foi uma boa luta.",
		DOUBLE_UMBRELLAHAT = "Dois guarda-chuvas são melhores que um.",
		DOYDOY = "Passarinho idiota!",
		DOYDOYBABY = "Proteger amigo bobo, amar amigo bobo.",
		DOYDOYEGG = "Comer cru, bom para músculos poderosos!",
		DOYDOYEGG_COOKED = "Proteína estupidamente gostosa.",
		DOYDOYEGG_CRACKED = "Preciso comer rápido antes que o pássaro estúpido saia.",
		DOYDOYFEATHER = "Para me lembrar do passarinho.",
		DOYDOYNEST = "Onde os amigos idiotas dormem.",
		DRAGOON = "É hora da competição de flexão?",
		DRAGOONDEN = "Wolfgang aprova.",
		DRAGOONEGG = "Choque para podermos lutar!",
		DRAGOONHEART = "É macio na mão.",
		DRAGOONSPIT = "Rá! Wolfgang cospe muito mais longe.",
		DUBLOON = "Amassa quando esmagado entre as poderosas mandíbulas do Wolfgang!",
		DUG_BAMBOOTREE = "Vou levar comigo.",
		DUG_BUSH_VINE = "Vou levar comigo.",
		DUG_COFFEEBUSH = "Não vai dar grãos fortes como esse.",
		DUG_ELEPHANTCACTUS = "Vou colher apenas com minhas mãos!",
		EARRING = "Alguém deixou isso cair, talvez?",
		ELEPHANTCACTUS = "Autch! Ainda é afiado.",
		ELEPHANTCACTUS_ACTIVE = "Cacto insignificante quer lutar comigo!",
		ELEPHANTCACTUS_STUMP = "Não está morto, só dormindo.",
		FABRIC = "Recheio de roupa frágeis.",
		FEATHERSAIL = "Wolfgang é mestre dos mares!",
		FISHINHOLE = "É bom lugar para pescar... peixes.",
		FISH_RAW = "Bolinha de proteína fedida.",
		FISH_RAW_SMALL = "Bola de peixe para comer.",
		FISH_RAW_SMALL_COOKED = "Parece melhor agora.",
		FLAMEGEYSER = "Olhe eu caminhar sobre isso!",
		FLOTSAM = "Não é um navio poderoso.",
		FLUP = "Sai pra lá!",
		FOOTBALLHAT = "Protege minha cabeça!",
		FRESHFRUITCREPES = "Brunch másculo de manhã.",
		FROG_POISON = "Sapo covarde!",
		GASHAT = "O chapeuzinho é colorido.",
		GOLDENMACHETE = "Faca bacanuda!",
		GRASS_WATER = "A grama está com sede.",
		HAIL_ICE = "É frio.",
		HOME = "É um bom lugar para ficar.",
		HOUNDFIRE = "Filhote de fogo!",
		ICEMAKER =
		{
			HIGH = "A máquina está fazendo um serviço muito bom!",
			LOW = "A maquininha parece cansada.",
			NORMAL = "Obrigado por bom gelo, máquina.",
			OUT = "Acabou o combustível da maquininha.",
			VERYLOW = "A máquina não vai durar muito mais.",
		},
		INVENTORYGRAVE = "Um homenzinho passou por aqui.",
		INVENTORYMOUND = "Um homenzinho passou por aqui.",
		IRONWIND = "Vela rodopiante!",
		JELLYFISH = "Se eu acertar a gelatina, vai se tornar geleia.",
		JELLYFISH_COOKED = "A gelatina parece saborosa agora.",
		JELLYFISH_DEAD = "Não teve a mínima chance contra o Wolfgang.",
		JELLYFISH_PLANTED = "Posso fazer queda de braço?",
		JELLYJERKY = "Charque é durão, como o Wolfgang!",
		JUNGLETREE =
		{
			BURNING = "Eu quebrei.",
			BURNT = "É pequeno e está quebrado agora.",
			CHOPPED = "Rá! Eu venci!",
			GENERIC = "Árvore é forte e magnífica.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Pode se tornar uma árvore.",
            PLANTED = "Tem melhores chantes de ser árvore agora.",
        },
		KNIGHTBOAT = "Vamos lutar!",
		KRAKEN = "Comedor de pão sujo!",
		KRAKENCHEST = "Deixou alguma coisa cair.",
		KRAKEN_TENTACLE = "Você tem muitos braços!",
		LAVAPOOL = "Que triste. Esqueci do calção de banho.",
		LIMESTONE = "Os corais foram esmagados para fazer rocha pequena.",
		LIMPETROCK =
		{
			GENERIC = "Parecem lesminhas para comer!",
			PICKED = "As lesminhas se foram.",
		},
		LIMPETS = "É lesma? Talvez.",
		LIMPETS_COOKED = "É gosmento na descida.",
		TREEGUARD = "Homem árvore! Lute comigo!",
		LIVINGJUNGLETREE = "Parece árvore comum.",
		LOBSTER = "Wolfgang respeita as garras poderosas das fera de concha.",
		LOBSTERHOLE = "É casa para feras das conchas.",
		LOBSTER_DEAD = "Wolfgang queria ter mãos de garra aterrorizantes!",
		LOBSTER_DEAD_COOKED = "Está pronto para comer.",
		LOG =
		{
			BURNING = "Faz cócegas quando Wolfgang coloca mão forte em cima.",
			GENERIC = "Os restos de lutas com árvore!",
		},
		LOGRAFT = "Esse bote não... é tão poderoso.",
		LUGGAGECHEST = "Wolfgang vai esmagar e conseguir tesouros!",
		MACHETE = "Ah! Muito bom!",
		MAGIC_SEAL = "Por que é grudenta?",
		MAGMAROCK = "É pedra deixada pelo vulcão zangado.",
		MAGMAROCK_FULL = "É pedra deixada pelo vulcão zangado.",
		MAGMAROCK_GOLD = "É uma rocha vulcânica brilhante.",
		MAGMAROCK_GOLD_FULL = "É uma rocha vulcânica brilhante.",
		MANDRAKE_COOKED = "O homenzinho planta está pronto para comer!",
		MANGROVETREE = "Está com muita sede.",
		MANGROVETREE_BURNT = "Não pode resistir nem pouco calor!",
		MARSH_PLANT_TROPICAL = "Arbusto insignificante.",
		MERMFISHER = "Vamos lutar!",
		MERMHOUSE_FISHER = "Casa feia!",
		MESSAGEBOTTLE = "Wolfgang não consegue colocar mãos carnudas dentro.",
		MESSAGEBOTTLEEMPTY = "É só uma garrafa.",
		MONKEYBALL = "Rá rá! Homem-macaco estúpido.",
		MOSQUITOSACK_YELLOW = "É saco de pancada amarelo.",
		MOSQUITO_POISON = "Lute como um homem de verdade!",
		MUSSEL = "Meus músculos são muito maiores!",
		MUSSEL_COOKED = "Mexilhões viram proteína para os músculos!",
		MUSSEL_FARM =
		{
			GENERIC = "Que nome estranho. Eles não se mexem muito.",
			STICKPLANTED = "Criaturas patéticas, conquistadas por uma vara!",
		},
		MUSSEL_STICK = "Mexilhões amam a varinha.",
		MYSTERYMEAT = "Meu estômago poderoso pode suportar isso!",
		NEEDLESPEAR = "A arma de uma planta poderosa!",
		OBSIDIAN = "Tem um fogo forte dentro dessa pedra.",
		OBSIDIANAXE = "O mais forte dos machados!",
		OBSIDIANCOCONADE = "Ainda mais força!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "A escuridão está vindo!",
			GENERIC = "Wolfgang fez bom trabalho!",
			HIGH = "É muito fogo!",
			LOW = "O fogo não é quente o suficiente.",
			NORMAL = "O fogo caloroso aquece os ossos do Wolfgang.",
			OUT = "Ohoh. Desligou.",
		},
		OBSIDIANMACHETE = "É muito afiado!",
		OBSIDIAN_WORKBENCH = "É mesa de fogo.",
		OCTOPUSCHEST = "Dê para o Wolfgang seus tesouros!",
		OCTOPUSKING = "Criatura forte! Dê para o Wolfgang muitas coisas boas!",
		OX = "Que fera poderosa!",
		OXHAT = "Fiquei mais poderoso!",
		OX_FLUTE = "Wolfgang vai tocar cançãozinha.",
		OX_HORN = "Chifre de touro forte!",
		PACKIM = "Alô, amigo robusto!",
		PACKIM_FISHBONE = "É osso. Eu gosto.",
		PALMLEAF = "Folha grande e verde.",
		PALMLEAF_HUT = "O grande Wolfgang merece conforto.",
		PALMTREE =
		{
			BURNING = "Eu quebrei.",
			BURNT = "É pequeno e está quebrado agora.",
			CHOPPED = "Rá! Eu venci!",
			GENERIC = "Que árvore jovial.",
		},
		PARROT = "Passarinho falador!",
		PARROT_PIRATE = "Talvez pudesse ser amigo?",
		PEACOCK = "O passarinho está se exibindo.",
		PEG_LEG = "É o melhor troféu de batalha!",
		PIGTENT = "É barraca de porcos.",
		PIKE_SKULL = "Wolfgang não tem medo!",
		PIRATEGHOST = "Aaaaaaaaaaahrrrr!!",
		PIRATEHAT = "Ha ha! Eu gosto!",
		PIRATEPACK = "Soa como sinos.",
		PIRATIHATITATOR =
		{
			BURNT = "Não faz nada.",
			GENERIC = "Instrumento estranho.",
		},
		POISONHOLE = "Buraco covarde!",
		PORTAL_SHIPWRECKED = "Para onde você vai?",
		PRIMEAPE = "Não parece ser páreo para mim.",
		PRIMEAPEBARREL = "Casa dos homenzinhos macacos.",
		RAFT = "Como essa pranchinha vai sustentar Wolfgang?",
		RAWLING = "Wolfgang aceita!",
		REDBARREL = "Não cutuque o barril.",
		ROCK_CHARCOAL = "Wolfgang esfrega embaixo dos olhos para assustar os inimigos!",
		ROCK_OBSIDIAN = "Uma rocha muito forte. Wolfgang gostaria de tê-la.",
		ROWBOAT = "Vou remar com braços poderosos!",
		SAIL = "Wolfgang irá para os mares.",
		SAIL_STICK = "A vara ajuda na navegação!",
		SAND = "Quando o Wolfgang tenta segurar, ele escorrega das mãos grandes e fortes.",
		SANDBAG = "O saco chupa as águas.",
		SANDBAGSMALL = "O saquinho chupa as águas.",
		SANDBAGSMALL_ITEM = "É grande saco de terra.",
		SANDBAG_ITEM = "O saco está cheio de terra.",
		SANDHILL = "Monte pequeno e destruível.",
		SAND_CASTLE =
		{
			GENERIC = "Bom para pisar!",
			SAND = "É mais areia que castelo.",
		},
		SEAGULL = "Tem boca grande. Como eu!",
		SEAGULL_WATER = "Descansando depois das lutas, amigo?",
		SEASACK = "Wolfgang pode carregar ainda mais coisas!",
		SEASHELL = "Concha pequena seria destroçada facilmente.",
		SEASHELL_BEACHED = "Wolfgang tem uma tigela deles na mesa em casa.",
		SEATRAP = "Pequeno beliscador não tem a menor chance.",
		SEAWEED = "Uma planta, do mar.",
		SEAWEED_COOKED = "O estomago forte de Wolfgang vai destruir isso!",
		SEAWEED_DRIED = "É comestível.",
		SEAWEED_PLANTED = "Folhas estranhas do mar.",
		SHADOWSKITTISH_WATER = "Não gosto disso!",
		SHARKITTEN = "Wolfgang prefere cachorros.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "É hora do cochilo do gato?",
			INACTIVE = "É só areia.",
		},
		SHARK_FIN = "Perdi o resto do tubarão.",
		SHARK_GILLS = "Talvez agora Wolfgang respire debaixo d'água? Talvez não.",
		SHARK_TEETHHAT = "O chapéu favorito do Wolfgang!",
		SHARX = "Não confio nesses cães do mar.",
		SHIPWRECKED_ENTRANCE = "É portal mágico. Muito arenoso...",
		SHIPWRECKED_EXIT = "É portal mágico. Muito gramado...",
		SLOTMACHINE = "Wolfgang é um apostador!",
		SNAKE = "Estou pronto para lutar!",
		SNAKEDEN =
		{
			BURNT = "Cinza.",
			CHOPPED = "Ganhei. Você perdeu.",
			GENERIC = "É um arbusto. De videiras.",
		},
		SNAKEOIL = "Bom para os músculos reluzentes de Wolfgang!",
		SNAKESKIN = "Vou usar como bandana.",
		SNAKESKINHAT = "Muito bom.",
		SNAKESKINSAIL = "Pele da cobra morta vai me ajudar a navegar.",
		SNAKE_FIRE = "Você é escorregadia, cobra!",
		SNAKE_POISON = "Veneno é arma de covardes!",
		SOLOFISH = "Me enfrente, peixe!",
		SPEARGUN = "Lançar lanças agora!",
		SPEAR_LAUNCHER = "Um soco de uma grande distância!",
		SPEAR_OBSIDIAN = "Lança muito forte e quente.",
		SPEAR_POISON = "Não é covardia se eu usar.",
		SPOILED_FISH = "Não está mais bom.",
		STUNGRAY = "Parece liso. Vou acariciar!",
		SUNKEN_BOAT =
		{
			ABANDONED = "Ninguém em casa.",
			GENERIC = "Onde está o capitão?",
		},
		SUNKEN_BOAT_BURNT = "Pilha de madeira queimada.",
		SUNKEN_BOAT_TRINKET_1 = "Wolfgang ama essas coisas!",
		SUNKEN_BOAT_TRINKET_2 = "Wolfgang não vai caber.",
		SUNKEN_BOAT_TRINKET_3 = "É a quantidade perfeita de umidade.",
		SUNKEN_BOAT_TRINKET_4 = "É divertido brincar com esse coiso de metal.",
		SUNKEN_BOAT_TRINKET_5 = "Couro duro é difícil de mastigar.",
		BANANAPOP = "O Wolfgang pode comer com uma mordida!",
		BISQUE = "Vai abastecer socos poderosos!",
		CEVICHE = "Vai ficar melhor na barriga do Wolfgang!",
		SEAFOODGUMBO = "Isso vai deixar Wolfgang muito forte!",
		SURFNTURF = "Muito bom.",
		SHARKFINSOUP = "Tubarão pequeno está dentro?",
		MONSTERTARTARE = "Blerg!",
		LOBSTERDINNER = "Uma refeição digna de Wolfgang!",
		LOBSTERBISQUE = "Parece chique.",
		JELLYOPOP = "Parece bala, mas tem gosto de carne!",
		SWEET_POTATO = "Muito doce!",
		SWEET_POTATO_COOKED = "Está pronta para comer.",
		SWEET_POTATO_PLANTED = "Batata é cor estranha dentro.",
		SWEET_POTATO_SEEDS = "Sementes teriam um gosto melhor se fossem uma batata.",
		SWIMMINGHORROR = "Se é uma luta que você quer, Wolfgang vai fazer esse favor!",
		SWORDFISH = "Wolfgang desafia você para um duelo!",
		TELEPORTATO_SW_BASE = "Wolfgang precisa consertar.",
		TELEPORTATO_SW_BOX = "Para que serve essa caixinha? Wolfgang gostaria de saber.",
		TELEPORTATO_SW_CRANK = "Wolfgang vai ficar com isso.",
		TELEPORTATO_SW_POTATO = "Alô, batatoso.",
		TELEPORTATO_SW_RING = "Vou carregar você.",
		TELESCOPE = "Vejo longe!",
		THATCHPACK = "Wolfgang pode carregar mais nos ombros poderosos!",
		TIDALPOOL = "Peixes mordiscam os dedos quando eu mergulho eles.",
		TIDAL_PLANT = "É planta.",
		TIGEREYE = "Está me olhando torto.",
		TIGERSHARK = "Vou levar você para o ABRIGO!",
		TOUCAN = "O pássaro foge quando vê o Wolfgang.",
		TRAWLNET = "Wolfgang vai prender você em sua rede!",
		TRAWLNETDROPPED =
		{
			GENERIC = "Que peixes vou encontrar?",
			SOON = "Está afundando mesmo.",
			SOONISH = "Está afundando.",
		},
		TRIDENT = "Me sinto como o rei do mar.",
		TRINKET_13 = "Wolfgang não gostaria de beber.",
		TRINKET_14 = "Wolfgang não gosta disso.",
		TRINKET_15 = "Não cabe nas mãos grandes do Wolfgang.",
		TRINKET_16 = "Não sei o que é isso.",
		TRINKET_17 = "Couro duro é difícil de mastigar.",
		TRINKET_18 = "Está quebrado.",
		TRINKET_19 = "Wolfgang não toma pílulas perdidas.",
		TRINKET_20 = "Wolfgang ama essas coisas!",
		TRINKET_21 = "Wolfgang não vai caber.",
		TRINKET_22 = "Parece seco de mais.",
		TRINKET_23 = "Está bem quebrado.",
		TROPICAL_FISH = "Tem aparência gostosa.",
		TUNACAN = "Vou abrir apenas com minhas mãos!",
		TURBINE_BLADES = "Lâmina que não corta.",
		TURF_SANDY = "Pedras de pisar.",
		TURF_ASH = "Pedras de pisar.",
		TURF_BEACH = "Pedras de pisar.",
		TURF_DESERTDIRT = "Pedras de pisar.",
		TURF_FUNGUS_GREEN = "Pedras de pisar.",
		TURF_FUNGUS_RED = "Pedras de pisar.",
		TURF_JUNGLE = "Pedras de pisar.",
		TURF_MAGMAFIELD = "Pedras de pisar.",
		TURF_MEADOW = "Pedras de pisar.",
		TURF_SNAKESKINFLOOR = "Pedras de pisar.",
		TURF_SWAMP = "Pedras de pisar.",
		TURF_TIDALMARSH = "Pedras de pisar.",
		TURF_VOLCANO = "Pedras de pisar.",
		TWISTER = "Que força!",
		TWISTER_SEAL = "Rá rá! É bom amigo.",
		VENOMGLAND = "É arma de covardes.",
		VINE = "Para amarrar os inimigos.",
		VOLCANO = "Está me chamando para lutar!",
		VOLCANOSTAFF = "Poder da montanha de fogo está nas mãos do Wolfgang!",
		VOLCANO_ALTAR =
		{
			GENERIC = "Não está querendo nada de mim agora.",
			OPEN = "Wolfgang tem medo de usar.",
		},
		VOLCANO_ALTAR_BROKEN = "Isso já era.",
		VOLCANO_ALTAR_TOWER = "Tem aparência assustadora.",
		VOLCANO_EXIT = "Tchau!",
		VOLCANO_SHRUB = "Árvore era muito fraca. Morta agora.",
		WALLYINTRO_DEBRIS = "Perdeu sua batalha.",
		WALL_LIMESTONE = "Parede boa e resistente.",
		WALL_LIMESTONE_ITEM = "Vou fazer muro forte.",
		WATERMELON_SEEDS = "Talvez cresça para virar tira-gosto saboroso?",
		WATERYGRAVE = "Não gosto disso. É bizarro.",
		WHALE_BLUE = "Vou comer você!",
		WHALE_BUBBLES = "Peixe grande está lá embaixo.",
		WHALE_CARCASS_BLUE = "Bem lutado, peixe grande!",
		WHALE_CARCASS_WHITE = "Tubarão-vermelho agora.",
		WHALE_TRACK = "O peixe enorme não pode fugir de mim!",
		WHALE_WHITE = "Tubarão-branco! Lute com Wolfgang!",
		WILBUR_CROWN = "A coroa está se despedaçando!",
		WILBUR_UNLOCK = "Bem-vindo, amigo! Rá rá!",
		WILDBORE = "Vou lutar com você.",
		WILDBOREHEAD = "Muito nojento!",
		WILDBOREHOUSE = "Casa insignificante não poderia me deter.",
		WIND_CONCH = "Concha faz sons assustadores!",
		WOODLEGS_KEY1 = "Chave assustadora!",
		WOODLEGS_KEY2 = "Chave bonita!",
		WOODLEGS_KEY3 = "Chave chata!",
		WRECK = "Não é poderoso o suficiente para flutuar.",
		CALIFORNIAROLL = "Entra no estômago do Wolfgang!",
		
	},
	DESCRIBE_GENERIC = "O que é isso?",
	DESCRIBE_TOODARK = "Socorro! Está escuro!",
	DESCRIBE_SMOLDERING = "Está quase pegando fogo.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Não tão poderoso agora!",
	},
}