return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "あー…まだ修理しなくてもよくない？",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "今そったら、気づかれるんじゃない…？",
			GENERIC = "ムリでしょ",
			NOBITS = "てか、毛がないんだけど？",
		},
		WRITE =
        {
            GENERIC = "それには書けないよ",
        },
		RUMMAGE =
        {   
            GENERIC = "ムーリー！", 
        },
		COOK =
        {
            GENERIC = "料理とか、ニガテなんだよねー",
            TOOFAR = "遠すぎでしょ！",
        },
		STORE =
		{
			GENERIC = "もう入らないよ",
			NOTALLOWED = "あたしはダメだってさ",
		},
		CHANGEIN =
        {
            GENERIC = "えー、めんどくさい",
            BURNING = "うわ！燃えてる！最高じゃん！",
        },
        GIVE =
        {
            DEAD = "んー…いらないみたい",
            SLEEPING = "寝てるから、あとにしよう",
            BUSY = "終わるまで待とっか",
        },
        TEACH =
        {
            KNOWN = "そんなの、もう知ってるってば！はぁ…",
            CANTLEARN = "ダメっぽい…ま、別に、興味なかったし",
        },
	},
	ACTIONFAIL_GENERIC = "ムーリー！",
	ANNOUNCE_MAGIC_FAIL = "ダメじゃん！なんで！？",
	ANNOUNCE_ADVENTUREFAIL = "今回は君の勝ちだ、Maxwell。",
	ANNOUNCE_BOOMERANG = "変なブーメラン！",
	ANNOUNCE_CHARLIE = "君のことなど怖くない！",
	ANNOUNCE_CHARLIE_ATTACK = "イタタ！バカ野郎！",
	ANNOUNCE_COLD = "冷たい！しみる！",
	ANNOUNCE_HOT = "熱さが激しすぎる！",
	ANNOUNCE_DUSK = "夜がやって来る。わたしには火が必要なの！",
	ANNOUNCE_WORMS = "なんの音…？てか、知りたくないけど…！",
	ANNOUNCE_EAT =
	{
		GENERIC = "美味しい！",
		PAINFUL = "ウーッ！不快だ。",
		SPOILED = "ひどい味だった！",
		STALE = "あれは少し気色悪かった。",
		INVALID = "は！？こんなの、食べるわけないでしょ！",
		YUCKY = "はぁー？ムリムリ！",
	},
	ANNOUNCE_NOSLEEPONFIRE = "心配なのは、崩れることだけど。",
	ANNOUNCE_NODANGERSIESTA = "敵が来るのに昼寝とか、ムリ！",
	ANNOUNCE_NONIGHTSIESTA = "あそこで、リラックスできなかったんだ。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "どちらかと言うと中にいたい。",
	ANNOUNCE_NOHUNGERSIESTA = "お腹がグルグルうなってる最中に、シエスタなんて出来ないわ！",
	ANNOUNCE_SHELTER = "ものを燃やす以外に、できることあったんだね。",
	ANNOUNCE_BURNT = "それを炎上させたい…。",
	ANNOUNCE_TOOL_SLIP = "まだ持ってるわ、わたしのライター！",
	ANNOUNCE_DAMP = "おっと、まずい！",
	ANNOUNCE_WET = "これは悪い状況かも！",
	ANNOUNCE_WETTER = "嫌いよ！",
	ANNOUNCE_SOAKED = "うっ！これは最悪！",
	ANNOUNCE_HOUNDS = "姿を見せろ！",
	ANNOUNCE_HUNGRY = "食べ物が必要！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "見つけ出してやる！",
	ANNOUNCE_HUNT_LOST_TRAIL = "オーー…奴は逃げた。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "土がドロドロで、足跡消えちゃってる…",
	ANNOUNCE_ACCOMPLISHMENT= "動け、この矢め！今すぐ動け！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "わたしがやった！",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "てへへ！",
		[2] = "かわいい！",
		[3] = "おっとっと！",
		[4] = "火をつけちゃった！",
		[5] = "燃えろ！",
		[6] = "我慢できない！",
	},
	ANNOUNCE_PECKED = "いいえ！いけない鳥さんだな！",
	ANNOUNCE_TORCH_OUT = "貴重な明かりが消えた！",
	ANNOUNCE_FAN_OUT = "チッ…壊れたし",
    ANNOUNCE_COMPASS_OUT = "針が動かないんですけど！",
	ANNOUNCE_WORMHOLE = "この服を燃やさなくっちゃ！",
	ANNOUNCE_TRAP_WENT_OFF = "アー！",
    ANNOUNCE_CRAFTING_FAIL = "何かが足りない。",
    ANNOUNCE_QUAKE = "あの音は多分良い事が起きたわけじゃない。",
    ANNOUNCE_NODANGERSLEEP = "眠る時間はない、戦わなければ！",
    ANNOUNCE_NOHUNGERSLEEP = "お腹がゴロゴロ鳴っている。眠れない！",
    ANNOUNCE_FREEDOM = "わたしは自由よ！火をつけて！",
    ANNOUNCE_RESEARCH = "火に何の関係もなかったが、あれは便利だった。",
    ANNOUNCE_NO_TRAP = "大量の魚に火をつけるみたいに。",
    ANNOUNCE_HIGHRESEARCH = "情報が多すぎ！",
    ANNOUNCE_THORNS = "痛い！",
    ANNOUNCE_NODAYSLEEP_CAVE = "不気味すぎてここじゃ眠れない。",
    ANNOUNCE_BEES = "ああああ！つっつき虫！",
    ANNOUNCE_KNOCKEDOUT = "あぁ、わたしの頭が！",
    ANNOUNCE_LOWRESEARCH = "ちぇっ。つまらなかった。",
    ANNOUNCE_DEERCLOPS = "まるで大きくて意地悪な怪人みたいな声がした。",
    ANNOUNCE_MOSQUITOS = "あっちへ行け、この吸血鬼どもめ！",
    ANNOUNCE_NODAYSLEEP = "空に大きな火の玉がある時に、中には行けないわ。",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "これでちょっと良くなった。",
	ANNOUNCE_CANFIX = "\nこれを修理できると思う！",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "わたしは空の火からは安全。",
	ANNOUNCE_VOLCANO_ERUPT = "火の山が火を吹いた！ヤバい！かっこいい！",
	ANNOUNCE_TREASURE = "いかにも「お宝の隠し場所」って感じ！",
	ANNOUNCE_CRAB_ESCAPE = "チッ…逃げられたし…",
	ANNOUNCE_SHARX = "ちょっと！バシャバシャしないでよ！",
	ANNOUNCE_MORETREASURE = "今日はツイてるねー",
	ANNOUNCE_OTHER_WORLD_TREASURE = "この世界の地図じゃないっぽい",
	ANNOUNCE_OTHER_WORLD_PLANT = "ここじゃ育たないから、燃やしちゃおうよ～",
	ANNOUNCE_MAPWRAP_WARN = "すっごい霧…",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "あれ…どっちへ向かってたっけ？",
	ANNOUNCE_MAPWRAP_RETURN = "霧の中、視界ゼロだったねー！",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"文字がかすれて、読めないな",
	},
	ANNOUNCE_BOAT_DAMAGED = "船がケガしちゃった！",
	ANNOUNCE_BOAT_SINKING = "沈みそう～！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "あ～…終わったわ～…",
	ANNOUNCE_ENTER_DARK = "ちょっと！あたしのライター、どこ！？",
	ANNOUNCE_ENTER_LIGHT = "フゥ…目、見えなくなったかと思った！",
	ANNOUNCE_INV_FULL = "これ以上、持てないってば！",
	ANNOUNCE_TRAWL_FULL = "そろそろ引き揚げてみますかー！",
	ANNOUNCE_UNIMPLEMENTED = "どう見ても怪しいから、燃やしちゃおう！",
	ANNOUNCE_WAVE_BOOST = "ヤッフゥー！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "近くに、でっかいサカナがいるっぽい！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "がー！逃げられた！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "海が荒れてて、よく見えないなー",

	BATTLECRY =
	{
		GENERIC = "わたしかおまえか、生き残るのは一人！",
		PIG = "バカなブタめ！",
		PREY = "ここに来い！",
		SPIDER = "グアー！",
		SPIDER_WARRIOR = "うぇー、殺してやれー！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "わたしもそう思ってた！",
		PIG = "こっちへ戻ってこい、骨付きブタめ！",
		PREY = "今度は許さないぞ！",
		SPIDER = "ヘンッ。あとで殺してやる。",
		SPIDER_WARRIOR = "もう強がっていられないでしょ！",
	},
	
	DESCRIBE =
	{
		BIGFISHINGROD = "でかっ！",
		DEVTOOL = "これは燃やすしかないっしょ？",
		DEVTOOL_NODEV = "これは燃やすしかないっしょ？",
		HOUNDFIRE = "あのワンコ、飼いたい！",
		INVENTORYGRAVE = "まー、誰でも生き残れるわけじゃないよね",
		INVENTORYMOUND = "まー、誰でも生き残れるわけじゃないよね",
		MANDRAKE_COOKED = "火で焼いたら、静かになったね",
		ROCK = "フツーの岩だね",
		SLURPERPELT = "燃やしたら、もっとヘンなニオイしそう",
		TREECLUMP = "ちょっとー！これ、じゃまー！",
		TURF_DESERTDIRT = "地面？興味ないな",
		TURF_FUNGUS_GREEN = "地面？興味ないな",
		TURF_FUNGUS_RED = "地面？興味ないな",
		TURF_SWAMP = "沼地っぽい地面だね～",
		WATERMELON_SEEDS = "植えてみる？つまんなそうだけど",
		WORMHOLE_LIMITED = "燃え尽きちゃいそうな感じ？",
		GLOMMER = "フサフサしてる！それでネバネバ…。",
        GLOMMERFLOWER = 
        {
        	GENERIC = "なんで、何もかも花に関することじゃなきゃいけないの？！",
        	DEAD = "これは燃えるかな…。",
        },
        GLOMMERWINGS = "すごい小さい！",
        GLOMMERFUEL = "奇妙でねとねとしている。",
        BELL = "今日は大晦日？花火があるってこと？！",
        MOOSE_NESTING_GROUND = "くっさ！鳥のお尻みたいなニオイする！",
        STATUEGLOMMER = 
        {	
        	GENERIC = "それっていったい何なのかよくわからん。",
        	EMPTY = "だいたい同じに見える。",
    	},
		WEBBERSKULL = "わたしの流儀じゃないけど、埋葬でもしておくか。",
		MOLE =
		{
			HELD = "地面から出ておいで、炎の中へ。",
			UNDERGROUND = "光から隠れているんだ、そう？",
			ABOVEGROUND = "ちょっと覗いてごらんよ！",
		},
		MOLEHILL = "燃える太陽が嫌いとか、ありえなくない？",
		MOLEHAT = "これはちょっと微妙…。",
		NIGHTSTICK = "燃えていたら、もっとずっとクールなのに。",
		RABBITHOUSE=
		{
			GENERIC = "うぇ。愚かなウサギたち。",
			BURNT = "ハ！ナイスな結果。",
		},
		TURF_DECIDUOUS = "地面は退屈。",
		TURF_SANDY = "地面は退屈。",
		TURF_BADLANDS = "地面は退屈。",
		BEARGER = "うわぁ！いいぃクマさん…。",
		BEARGERVEST = "まるで毛皮の中で泳いでいるみたい。",
		ICEPACK = "フワフワしたバックパック！",
		MOONROCKNUGGET = "ただの石じゃん",
		ROCK_MOON = "ただの岩でしょ？",
		BEARGER_FUR = "ずーっと奥まで毛皮だわ。",
		FURTUFT = "モノトーンのモフモフ素材！",
		BIGFOOT = "何じゃあれは！",
		BONESHARD = "いい火口にはならないと思う。",
		BUZZARD = "お前の首って気持ち悪い。",
		CACTUS = 
		{
			GENERIC = "脊柱！私の弱味！どうして分かったの？",
			PICKED = "引き分けとしておきましょう。",
		},
		CACTUS_MEAT_COOKED = "今は大丈夫みたい。",
		CACTUS_MEAT = "まだ危険そう。",
		CACTUS_FLOWER = "また別の花。",
		COLDFIRE =
		{
			EMBERS = "まずい。ほぼなくなってしまった！",
			GENERIC = "わたしはいろんな種類の炎が好き。",
			HIGH = "燃えろ！速く燃えろ！そしてもっと青く！",
			LOW = "この火は小さくてつまらない。",
			NORMAL = "燃えろ！",
			OUT = "オウーー。すべて終わり。",
		},
		CATCOON = "おいで、ネコちゃん！",
		CATCOONDEN = 
		{
			GENERIC = "誰かが住んでいる限り、燃やさないけど。",
			EMPTY = "全部乾いていて、燃える準備はできている。",
		},
		CATCOONHAT = "撫でたくなる帽子。",
		COONTAIL = "これよりも変なものを持ってたことあるけど。",
		COOKPOT =
		{
			COOKING_LONG = "火にはまだまだ、するべき仕事がかなりある。",
			COOKING_SHORT = "火は、お仕事してるんだから！",
			DONE = "炎で料理して、良かった。",
			EMPTY = "中に食べ物を入れて、下に火をつけることもできる。",
			BURNT = "少なくとも、景気のいい炎で尽きたわ。",
		},
		EYEBRELLAHAT =	"身に付ければ、目を合わせなくてすむ…",
		ARMORDRAGONFLY = "やった！もっと炎！！！",
		DRAGON_SCALES = "おぉぉ！気に入った。",
		DRAGONFLYCHEST = "どうして、何か燃えないものが欲しい訳があるのかわからないけど…",
		DECIDUOUSTREE = 
		{
			BURNING = "イエス！燃えろ！",
			BURNT = "まだそれが燃えていればなぁ。",
			CHOPPED = "燃やしたほうが楽しかったと思うなー",
			GENERIC = "んー、よく燃えそう",
			POISON = "火をつけちゃえば、さすがに思い知るでしょ。",
		},
		ACORN_COOKED = "やっぱり、お前は木にはなれないかもね。",
		BIRCHNUTDRAKE = "\\bアァー！火をつけた！",
		FARMPLOT =
		{
			GENERIC = "ハァ。山積みの泥。",
			GROWING = "急げ、泥山だ。食料をくれ！",
			NEEDSFERTILIZER = "間抜けな者には糞が必要だ。",
			BURNT = "いいフィナーレだった。",
		},
		COLDFIREPIT =
		{
			EMBERS = "まずい。ほぼなくなってしまった！",
			GENERIC = "冷たいけど、何時間でも見ていられそう。",
			HIGH = "青い炎！いいね！燃えろ燃えろー！",
			LOW = "この火は小さくてつまらない。そして青い。",
			NORMAL = "燃えろ！",
			OUT = "火をまた起こすべきだな。",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "蓋を閉めて、火を消して回るのはやめて欲しいな。",
			OFF = "で、永遠にオフ状態でいて！",
			LOWFUEL = "もうすぐ燃料切れ。",
		},
		ICEHAT = "わたしのムード、台無しにしてくれた。",
		LIGHTNINGGOAT = 
		{
			GENERIC = "飛び跳ねるヤギ。",
			CHARGED = "あなたはクレイジーね！",
		},
		LIGHTNINGGOATHORN = "耳にあてがうと、稲妻の音が聞こえる。",
		GOATMILK = "フサフサしてて電気が通ってる。ゲロ。",
		MEATRACK =
		{
			DONE = "準備はできている！",
			DRYING = "さーさー肉よ、さっさと乾け！",
			DRYINGINRAIN = "雨なんてあっち行け！乾け！",
			GENERIC = "何枚か肉を干したい！",
			BURNT = "火で乾かすのは、一番いい方法ではなかったかもね…。",
		},
		MERMHEAD = 
		{
			GENERIC = "そんなに臭いからこういう罰になるのよ！",
			BURNT = "二重の刑！",
		},
		MERMHOUSE = 
		{
			GENERIC = "誰も気にしないよね、これが燃えても。",
			BURNT = "燃えちゃったけど、誰も文句言わないね",
		},
		FLOWERSALAD = "花食べるぐらいなら、火食べるって！",
        ICECREAM = "フン、時には冷たいものもオッケーってことか。",
        WATERMELONICLE = "燃やせる可能性があるのに、なんで果物を凍らせるの？",
        TRAILMIX = "カリ カリ カリ。",
        HOTCHILI = "こういうホットさは好きよ！",
        GUACAMOLE = "こりゃ参った、おいしい！",
		MOOSE = "いったいこれはどこの世界の…",
		MOOSEEGG = "でかーーい！",
		MOSSLING = "羽がチリチリと縮んでいる。",
		FEATHERFAN = "わからない… いくつか火を消されちゃうかも…。",
		TROPICALFAN = "わからない… いくつか火を消されちゃうかも…。",
		GOOSE_FEATHER = "フワフワ心地いい！",
		STAFF_TORNADO = "いつも旋回中！破壊に向けてうね回る！",
		PIGHEAD = 
		{	
			GENERIC = "まあ、わたしの今は悪くないか。",
			BURNT = "もっと悪いってことだってあり得るものね、きっと。",
		},
		PIGHOUSE =
		{
			FULL = "彼は中でブタに関係あることをしている。",
			GENERIC = "このブタたちの建築の趣味は疑問だけど。",
			LIGHTSOUT = "バカ野郎！わたしを中に入れろ！",
			BURNT = "ナイスリモデル！",
		},
		FERTILIZER = "バケツ一杯の臭いプンプン。",
		RAINOMETER = 
		{	
			GENERIC = "雨はアンチ火。ヤダ！",
			BURNT = "見たか、バカ雨！",
		},
		RAINCOAT = "これでうまくいくはず。",
		RAINHAT = "水を遠ざけておくものは何でも。",
		RESEARCHLAB = 
		{	
			GENERIC = "わたしだって全て分かってる訳じゃない、まだ。",
			BURNT = "もうここから学ぶことはない。",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "わたしだって全て分かってる訳じゃない、まだ。",
			BURNT = "もうここから学ぶことはない。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "暗くパワフルなエネルギーがそこから放射されている。",
			BURNT = "今は暗いがあまりパワフルではない。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "帽子を魔女の釜みたいにして使えるわ！",
			BURNT = "二倍、二倍の努力と…　あ。燃えちゃった。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "それがわたしの保険。",
			BURNT = "保険、解約されちゃったね",
		},
		ROCK_ICE = 
		{
			GENERIC = "あれはどうやっても燃えそうにない。",
			MELTED = "水が史上最高役に立たない状態。",
		},
		ROCK_ICE_MELTED = "水が史上最高役に立たない状態。",
		ICE = "寒い。",
        REFLECTIVEVEST = "ベストは今アツい。",
		HAWAIIANSHIRT = "これって、本当の花みたいにきれいに燃えるかなあ。",
		TENT = 
		{
			GENERIC = "ガールスカウトのバッジ、全部もらったっけ。",
			BURNT = "それで、まだ全部持ってる。",
		},
		SIESTAHUT = 
		{
			GENERIC = "ガールスカウトで、どうやって作るか習ったっけ。",
			BURNT = "いつも私は火をつけちゃったけど。",
		},
		TRANSISTOR = "電気エネルギーのドゥー… ワット？",
		TREASURECHEST = 
		{
			GENERIC = "わたしのごっこ衣装トランク。",
			BURNT = "トランクは良く燃えたわ。",
		},
		TUMBLEWEED = "すごく燃えやすそう！",
		GRASS_UMBRELLA = "なんて綺麗。",
		PALMLEAF_UMBRELLA = "かなりいい感じ！",
		UNIMPLEMENTED = "これは未完成。でもきっとそれでも、燃えると思う。",
		WALL_HAY = 
		{	
			GENERIC = "すごく燃えやすそう！",
			BURNT = "やっぱり燃えたわ！",
		},
		WALL_WOOD = 
		{
			GENERIC = "これは絶対火がつくでしょう。",
			BURNT = "やっぱりついた！",
		},
		WARG = "You're a big mean jerk!",
		WATERMELON = "中は赤くてきれいだけど、水気が多いなー…",
		WATERMELON_COOKED = "焼いたけど、やっぱり水気が多いなあ",
		WATERMELONHAT = "まあ、それもこの果物の一種の使い方ではあるわね。",
		WINTEROMETER = 
		{
			GENERIC = "炎を測ればもっといいのに。",
			BURNT = "炎を測ってれば、もっと準備できてたかもね。",
		},
		HOME = "I'm gonna burn it.",
		HOMESIGN = 
		{
			GENERIC = "読書は減らし！燃やすのは増やそう！",
			UNWRITTEN = "書くより、焼き印押したほうがよくない？",
			BURNT = "ハハハ、イェス！",
		},
		BEEBOX =
		{
			READY = "イェイ！蜂蜜を盗めるぞ！",
			FULLHONEY = "イェイ！蜂蜜を盗めるぞ！",
			GENERIC = "太った蜂め、蜂蜜を作れ！",
			NOHONEY = "ここに見るものは何もないから。",
			SOMEHONEY = "辛抱強く！",
			BURNT = "煙で誘い出した！",
		},
		LIVINGTREE = "生きてるかも知れないけど、燃えるのは燃える。",
		ICESTAFF = "たあーーいくつ。",
		WORMLIGHT = "火のない明かり。不自然だ。",
		WORMLIGHT_LESSER = "なんか…おばあちゃんの手みたい…",
		WORM =
		{
		    PLANT = "火のない明かり。不自然だ。",
		    DIRT = "普通、泥って動き回るもの？",
		    WORM = "かなりふわふわしている！",
		},
		WORMLIGHT_PLANT = "炎が出ない光…？怪しいな",
		EEL = "わたしを見ている様子が好きじゃない。",
		EEL_COOKED = "火がすべてを改善する。",
		UNAGI = "高級料理っぽくしても、やっぱキショいよ",
		EYETURRET = "それは物に火をつけてくれれば良いのに。",
		EYETURRET_ITEM = "それを置くまでは役に立たない。",
		MINOTAURHORN = "これらの年輪は年齢の現われなのか。",
		MINOTAURCHEST = "あんな大きな角が欲しい！",
		THULECITE_PIECES = "このスーラサイトが崩れて粉々になる。",
		POND = "この池は絶対に発火しない。なんて味気ない。",
		POND_ALGAE = "大量の水が必要に違いない。",
		GREENSTAFF = "これで火は起こせないけど、役には立つと思う。",
		POTTEDFERN = "どっちかというと奴らを燃やしたい。",

		THULECITE = "それが燃えるとは思えない。",
		ARMORRUINS = "それを着たいかどうか、確かじゃない。",
		RUINS_BAT = "これは不快なものを寄せ付けない。",
		RUINSHAT = "何かが底を流れているように見える。",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "わたしには普通に見える。",	--Calm phase
			WARN = "わたしに警告している。",	--Before nightmare
			WAXING = "燃料が生命を宿してきている！", --Nightmare Phase first 33%
			STEADY = "ほとんど鼻歌交じり。", --Nightmare 33% - 66%
			WANING = "消えそうになっていると思う。", --Nightmare 66% +
			DAWN = "ほぼ終わりに差しかかってきている。", --After nightmare
			NOMAGIC = "上手くいっているとは思えない。", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "アァー！",
		ROOK_NIGHTMARE = "意地の悪い笑いを浮かべている。",
		KNIGHT_NIGHTMARE = "かなりすり減って見える。",
		MINOTAUR = "可哀想な奴。この迷路にはまってしまった。",	--Monster in labyrinth
		SPIDER_DROPPER = "上から落ちてきた。",	--White spider that comes from the roof
		NIGHTMARELIGHT = "火の無い明かりは不自然だ。",	--Lights that activate during nightmare.
		GREENGEM = "これは本当に軽く感じる。",
		RELIC = "I guess someone lived here before.",	--Fixed relic
		RUINS_RUBBLE = "多分それを直すことができた。",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "それはかなり便利！",	--Works as axe and pickaxe
		ORANGESTAFF = "そのせいで頭痛がしてきた。",	--Teleports player.
		YELLOWAMULET = "その辺りの暗闇を吸い上げているようだ。",	--Emits light, player walks faster.
		GREENAMULET = "それを着るとオープンな気分になる。",	--Reduce cost of crafting

		SLURPER = "彼らは腹の中でかすかな炎を持っているのか？",
		SLURPER_PELT = "うーーわーーーー、まだ勢いがある！",
		ARMORSLURPER = "オー、オエッ！オエッ！オエッ！オエッ！気色悪いーーーーーーー！",
		ORANGEAMULET = "そいつがわたしのために燃えている物を取ってきてくれる！",
		YELLOWSTAFF = "魔法じみている。",
		YELLOWGEM = "火花を発している。",
		ORANGEGEM = "これのせいでわたしの指はズキズキする。",
		PALMTREE =
        {
			BURNING = "ヤバ！めっちゃ燃えてる！アハハ！",
			BURNT = "このほうが、ぜんぜんカッコイイよ",
			CHOPPED = "オノで何度か殴ったら、倒れたよ",
			GENERIC = "枝がない…ヘンなの",
		},
		TELEBASE = 
		{
			VALID = "わたしはその魔法を感じとれる！",
			GEMS = "それがもっと何かを必要としている。",
		},
		GEMSOCKET = 
		{
			VALID = "どうやって奴らは浮かんでいるのだろう？",
			GEMS = "まったく空っぽ！",
		},
		STAFFLIGHT = "とても美しい！",

        LIGHTER = "わたしのラッキーライター！",


        ANCIENT_ALTAR =
        {
        	WORKING = "ウー！あの世のインターフォン。",
        	BROKEN = "死人はここを通り抜けることはできない。",
        },  
        ANCIENT_ALTAR_BROKEN = "死人はここを通り抜けることはできない。",

        ANCIENT_STATUE = "チェッ、燃えない。",

        LICHEN = "野菜系？固そうだし、マズそうだけど",
		CUTLICHEN = "チェッ、安っぽい味がする。",

        CAVE_BANANA = "バナナだ！",
        CAVE_BANANA_COOKED = "美味しい！",
        CAVE_BANANA_BURNT = "んー、いい感じ！",
        CAVE_BANANA_TREE = "燃えそうだ！",
        ROCKY = "わたしたち、あまり共通点はないね。",

        BLUEAMULET = "これに対するブーイング。",
		PURPLEAMULET = "科学は行き過ぎたの？",
		TELESTAFF = "使うってことはかなり切迫している。",
		MINERHAT = "それは本物の火ではないけど、かなり楽しめる。",
		MONKEY = "自業自得！このうんちは燃やせる。",
		MONKEYBARREL = "いい感じに燃えやすそうな家。",

		HOUNDSTOOTH="シャープな柄。気に入った！",
		ARMORSNURTLESHELL="防御低下！攻撃強化！",
		BAT="キュートで小さい奴！",
		BATBAT = "それで敵を打てる。",
		BATWING="ゲーッ！",
		BATWING_COOKED="ゲーッ！",
		BEDROLL_FURRY="フリフリすぎるよ。",
		BUNNYMAN="うっ！彼らはかなり愚かに見える。",
		FLOWER_CAVE="内側が燃えている。",
		FLOWER_CAVE_DOUBLE="内側が燃えている。",
		FLOWER_CAVE_TRIPLE="内側が燃えている。",
		GUANO="普通の糞みたいに燃える。",
		LANTERN="火はこのように自制を意味するものではない！",
		LIGHTBULB="電球なの？球根なの？",
		MANRABBIT_TAIL="その議論に勝った。",
		MUSHTREE_TALL=
		{
            GENERIC = "Gross. This tree is sick all over.",
            BLOOM = "Ack! It stinks!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Gross. It smells like leprechaun butt.",
            BLOOM = "It's spreading junk everywhere.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Gross. It's all mushroomy.",
            BLOOM = "Ew, I don't want to get too close.",
        },
        MUSHTREE_TALL_WEBBED = "クモの巣まみれ…いい気味だね",
        SPORE_TALL = "きれーな色！火花みたい！",
        SPORE_MEDIUM = "きれーな色！火花みたい！",
        SPORE_SMALL = "きれーな色！火花みたい！",
        SPORE_TALL_INV = "よく燃えそう！",
        SPORE_MEDIUM_INV = "よく燃えそう！",
        SPORE_SMALL_INV = "よく燃えそう！",
		MUSHTREE_TALL="気味悪い。この木はずっと病気。",
		MUSHTREE_MEDIUM="くっさ！何これ？妖精のトイレ？",
		MUSHTREE_SMALL="気味悪い。全部キノコ尽くし。",

		SLURTLE="それを爆発させたい！",
		SLURTLE_SHELLPIECES="へー。壊れた。",
		SLURTLEHAT="わたしの頭にピッタリ。",
		SLURTLEHOLE="そいつらを燃やし尽くすべきだ。",
		SLURTLESLIME="これは大好き！",
		SNURTLE="ドッカーン！",
		SPIDER_HIDER="なんてイライラするやな奴！",
		SPIDER_SPITTER="ここに来い！",
		SPIDERHOLE="クモでいっぱい。",
		STALAGMITE="石は退屈だ。",
		STALAGMITE_FULL="岩は退屈だ。",
		STALAGMITE_LOW="岩は退屈だ。",
		STALAGMITE_MED="石は退屈だ。",
		STALAGMITE_TALL="もっと別のつまらない岩。",
		STALAGMITE_TALL_FULL="もっと沢山のつまらない岩。",
		STALAGMITE_TALL_LOW="もっと沢山のつまらない岩。",
		STALAGMITE_TALL_MED="もっと沢山のつまらない岩。",

		TURF_CARPETFLOOR = "地面は退屈だ。",
		TURF_CHECKERFLOOR = "地面は退屈だ。",
		TURF_DIRT = "地面は退屈。",
		TURF_FOREST = "地面は退屈。",
		TURF_GRASS = "地面は退屈。",
		TURF_MARSH = "地面は退屈。",
		TURF_ROAD = "地面は退屈。",
		TURF_ROCKY = "地面は退屈だ。",
		TURF_SAVANNA = "地面は退屈。",
		TURF_WOODFLOOR = "地面は退屈だ。",
		TURF_DRAGONFLY = "あたしのライターでも火がつかないよ",

		TURF_CAVE="地面は退屈。",
		TURF_FUNGUS="地面は退屈。",
		TURF_SINKHOLE="地面は退屈。",
		TURF_UNDERROCK="地面は退屈。",
		TURF_MUD="地面は退屈。",
		
		TURKEYDINNER = "焼けこげた鳥のごちそう！",
		TWIGS = "小ぶりの小枝の山。他の何よりも、たき火に適している。",
		POWCAKE = "それは燃やせるのだろうか。",
        CAVE_ENTRANCE = 
        {
            GENERIC="Who plugged that hole?",
            OPEN = "I hope there's lava down there somewhere.",
        },
        CAVE_EXIT = "It's too dark and stuffy down here.",
        CAVE_ENTRANCE = "誰？あそこにフタしたの",
        CAVE_ENTRANCE_RUINS = "誰？あそこにフタしたの",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "あん中、入るの！？ヤダよ！",
            OPEN = "あの下には、溶岩流れてるかなー…",
        },
        CAVE_EXIT = 
        {
            GENERIC = "ここのほうが涼しくていいよね",
            OPEN = "ここ、暗いし、空気悪くない？",
        },

		MAXWELLPHONOGRAPH = "もっと刺激的な音楽が好きだ。",
		PIGGUARD = "彼の態度が気に入っている！",
		BOOMERANG = "それは最もエキサイティングな武器ではない。",
		ADVENTURE_PORTAL = "たぶんそこから家に帰れる。",
		AMULET = "わたしは無敵だ！うーん、多分違う。でも気分はいいけど。",
		ANIMAL_TRACK = "それが新しい友達に引き合わせてくれる。",
		ARMORGRASS = "燃えやすい材質のゴミ。",
		ARMORMARBLE = "もし戦う必要があるのなら、同じように守られるだろう。",
		ARMORWOOD = "さあこれでわたしは、世界をわが手に！",
		ARMOR_SANITY = "まるで煙に包まれているみたい。",
		ASH =
		{
			GENERIC = "1つの火からの残り物。それがまだここにあればなぁ。",
			REMAINS_GLOMMERFLOWER = "あの変な花がどんな風に燃えたのか、見たかったな。",
			REMAINS_EYE_BONE = "目玉の骨が燃えるとこ、見たかったなー",
			REMAINS_THINGIE = "それが何であろうと、まだ燃えていたらなぁ。",
		},
		AXE = "とても鋭い。",
		BABYBEEFALO =
		{
			GENERIC = "赤ちゃんですら醜い。",
			SLEEPING = "起きろ！",
		},
		BACKPACK = "この中では百万ものライターのようにフィットできる。",
		BACONEGGS = "黄色のネバネバな部分は気持ち悪いがベーコンは素晴らしい！",
		BANDAGE = "気色悪い、やらなきゃダメ？",
		BASALT = "固すぎで壊れない！",
		BEARDHAIR = "あれ、これはどこから来たの？",
		BEDROLL_STRAW = "カビ臭い。",
		BEE =
		{
			GENERIC = "デブだけど、その刺す奴は危険そうに見える。",
			HELD = "蜂でいっぱいのポケット！",
		},
		BEEFALO =
		{
			FOLLOWER = "えーっと、わたしに付いて来ているの？",
			GENERIC = "なんて気色の悪い、毛深いけだもの！",
			NAKED = "ハハ！あいつは今全裸だ！",
			SLEEPING = "彼らは寝ている時、さらにあほに見える。",
		},
		BEEFALOHAT = "彼の髪を取って、俺自身の頭につけてみた！",
		BEEFALOWOOL = "ハハ！彼の髪を盗んだ！",
		BEEHIVE = "蜂でいっぱい！",
		BEEMINE = "蜂が中に。おまけでその中に火を付けてくるべきだったな。",
		BEEMINE_MAXWELL = "蚊が中に。あまりハッピーそうではない。",
		BEEHAT = "これでわたしは古くささとは縁遠くなるつもり。",
		BERRIES = "レッドベリーが一番おいしい。",
		BERRIES_COOKED = "火と一緒のレッドベリーはさらに美味しい。",
		BERRYBUSH =
		{
			BARREN = "糞を食らえ、ばかな植物！",
			WITHERED = "カラカラに乾いてる。燃やす準備OK！",
			GENERIC = "ウーーーン。ベリー。",
			PICKED = "もっとベリーが欲しい！",
		},
		BIRDCAGE =
		{
			GENERIC = "鳥の牢獄！",
			OCCUPIED = "ハハハ！もう逃げらんないよ！",
			SLEEPING = "鈍い鳥。起きろ！",
			HUNGRY = "うるさいなー…なにピーピー言ってんの？",
			STARVING = "マジうるさいんですけど！",
			DEAD = "ま、これで静かになったよね",
			SKELETON = "そろそろ掃除したほうがいいよね…",
		},
		BIRDTRAP = "気味悪い鳥たちを捕まえるつもり。",
		BIRD_EGG = "鳥のお尻のような臭いがする。",
		BIRD_EGG_COOKED = "ゲーッ！黄色の部分は全部流れやすい。",
		BISHOP = "司教だ！",
		BISHOP_CHARGE_HIT = "いったぁぁぁ！",
		BLOWDART_FIRE = "これがわたしの世界で一番好きなもの。",
		BLOWDART_SLEEP = "眠らせれば、火つけるの楽だよね",
		BLOWDART_PIPE = "火を吹き起こすための良い練習。",
		BLUEGEM = "うっ！これは醜い。",
		BLUEPRINT = "これでいくつかの実験を確保できる。",
		BELL_BLUEPRINT = "これでいくつかの実験を確保できる。",
		BLUE_CAP = "ジム用の靴下みたいな臭いがする！",
		BLUE_CAP_COOKED = "火でそれを変えたのよ！",
		BLUE_MUSHROOM =
		{
			GENERIC = "間抜けなキノコ。",
			INGROUND = "ねえ！おまえ！ここに登って来い！",
			PICKED = "多分いつかは帰ってくるだろう。",
		},
		BOARDS = "ボードだ。他の木材同様、こいつらも燃える。",
		BONESTEW = "食べ物に火を加えるだけ、出来上がり！",
		BUGNET = "わたしは虫を捕まえられる！",
		BUSHHAT = "従順すぎ！",
		BUTTER = "美味いが、ちょっと虫っぽい。",
		BUTTERFLY =
		{
			GENERIC = "ヒラヒラと飛んで行け、蝶よ！",
			HELD = "それをグシャっとつぶしたい。",
		},
		BUTTERFLYMUFFIN = "イヒヒ、マフィンの中で身動きが取れない蝶を見てよ。",
		BUTTERFLYWINGS = "その蝶がもう飛ぶことはない！",
		CAMPFIRE =
		{
			EMBERS = "まずい。ほぼなくなってしまった！",
			GENERIC = "わたしは炎が好き。",
			HIGH = "燃えろ！速攻で燃やせ！",
			LOW = "この火は小さくてつまらない。",
			NORMAL = "燃えろ！",
			OUT = "オウーー。すべて終わり。",
		},
		CANE = "これでもっと簡単に歩ける！",
		CARROT = "ゲーッ！全部野菜みたいだ。",
		CARROT_COOKED = "まだ野菜たっぷり、でも火にくべてたほうがよかった。",
		CARROT_PLANTED = "多分そいつの特別なニンジンの友は地中にいる。",
		CARROT_SEEDS = "すごくまずいオレンジ野菜の種。",
		CAVE_FERN = "燃えやすく見える。",
		CHARCOAL = "むむむむ。炎のような匂い。",
        CHESSJUNK1 = "死がお馬ちゃんの息の根を止める",
        CHESSJUNK2 = "死が神父を挑発する。",
        CHESSJUNK3 = "死が城を挑発する。",
		CHESTER = "彼はかなりファジーだ！",
		CHESTER_EYEBONE =
		{
			GENERIC = "じっと見るのは無礼。",
			WAITING = "少なくともわたしの事をもう凝視していない。",
		},
		COOKEDMEAT = "味ついてないんですけど…",
		COOKEDMONSTERMEAT = "まだゾッとする。",
		COOKEDSMALLMEAT = "生き延びたければ、前菜以上の物が必要になる。",
		CORN = "甘い野菜、おいしい！",
		CORN_COOKED = "オーッ！これは火の中に入れると爆発する！",
		CORN_SEEDS = "わたしの好きな爆発しやすい野菜の種。",
		CROW =
		{
			GENERIC = "それはわたしが死ぬのを待っていると思う。",
			HELD = "今じゃ君もあまり賢くないね？",
		},
		CUTGRASS = "燃やしたり、クラフトに使ったりすることが可能な草。",
		CUTREEDS = "アシを刈って、燃やす準備はできている。それか多分工作する。",
		CUTSTONE = "最大限楽しめるように完全に一致している。",
		DEADLYFEAST = "この料理のひどさは火でも直せなかった。",
		DEERCLOPS = "神聖な糞！",
		DEERCLOPS_EYEBALL = "わたしをジロジロ見るのは止めてよ！",
		DIRTPILE = "この森の回りに誰が泥を残して行ったのか。",
		DIVININGROD =
		{
			COLD = "ある種のノイズを出している。",
			GENERIC = "電気のガラクタでいっぱい。",
			HOT = "ガー！ビープ音はもうたくさん！",
			WARM = "これはどんどんうるさくなってきている。",
			WARMER = "近づいてるに違いない！",
		},
		DIVININGRODBASE =
		{
			GENERIC = "これが何に使えるのかわからない。燃えそうではない。",
			READY = "ただ鍵で開錠する必要があるだけ。火じゃないんだ、残念ながら。",
			UNLOCKED = "今ブンブン音を立てている。",
		},
		DIVININGRODSTART = "それから何かを作るつもりだ。",
		DRAGONFLY = "炎が中に詰まってる！",
		LAVASPIT = 
		{
			HOT = "さらに一番クールなよだれ！",
			COOL = "クールなよだれ、ほんとに。",
		},
		LAVA_POND = "ヤバいッ！これはヤバい！あはははは！",
		LAVAE = "ねー、仲よくしようってばー！",
		LAVAE_PET = 
		{
			STARVING = "ガリガリじゃん！",
			HUNGRY = "んー…燃やし足りないのかなぁ…",
			CONTENT = "この子とあたしで、世界を焼きつくしたい！",
			GENERIC = "この子、あたしにぴったりじゃん…",
		},
		LAVAE_EGG = 
		{
			GENERIC = "中から火が噴き出してきそう…",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "寒そうだよ",
			COMFY = "タマゴはゴキゲンみたい",
		},
		LAVAE_TOOTH = "あの子、かみグセないよね？",
		DRAGONFRUIT = "火のようなものに見える！",
		DRAGONFRUIT_COOKED = "火の中にあるフルーツに似ているように見えてきた。",
		DRAGONFRUIT_SEEDS = "見かけが火みたいなフルーツの種。",
		DRAGONPIE = "パイの中のファイアーフルーツ？それいいね！",
		DRUMSTICK = "一日中そのドラムが鳴っている！",
		DRUMSTICK_COOKED = "わたしは自分の飢えを満足させるのか、それともドラムを叩く？",
		DURIAN = "ゲッ、臭い！",
		DURIAN_COOKED = "ゲーッ、調理しても同じくらいひどい臭い！",
		DURIAN_SEEDS = "悪臭を放つフルーツに悪臭を放つ種。",
		EARMUFFSHAT = "ウサギのお尻のような臭い。",
		EGGPLANT = "間違いなく鳥じゃない。",
		EGGPLANT_COOKED = "それに火を使ったらナスが美味しくなった。",
		EGGPLANT_SEEDS = "これらの種から植物かそれとも鳥の赤ちゃんができるのか？",
		STUFFEDEGGPLANT = "まだそれは鳥じゃないけど、それらしく詰めておいた！",
		DUG_BERRYBUSH = "どうしたんだ、なんの泥もなしか？",
		DUG_GRASS = "どうしたんだ、なんの汚れもなしか？",
		DUG_MARSH_BUSH = "どうしたんだ、なんの泥もなしか？",
		DUG_SAPLING = "どうしたの、泥がないの？",
		EARMUFFS = "ウサギのお尻のような臭い。",
		ACORN = 
		{
		    GENERIC = "こんにちは、そこの木の種さん。",
		    PLANTED = "おまえはじきに、本物の木になる。",
		},
		EVERGREEN =
		{
			BURNING = "イエス！燃えろ！",
			BURNT = "まだそれが燃えていればなぁ。",
			CHOPPED = "世界で木が一本減ります。",
			GENERIC = "それは良く燃えるように見える。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "イエス！燃えろ！",
			BURNT = "まだそれが燃えていればなぁ。",
			CHOPPED = "世界で木が一本減ります。",
			GENERIC = "火の中で死ね！",
		},
		EYEPLANT = "火のように広がる。",
		FEATHERHAT = "わたしは不死鳥よ！",
		FEATHER_CROW = "カラスの羽。それは燃えるときっと恐ろしい臭いがする。",
		FEATHER_ROBIN = "赤い鳥の羽。それは燃えるときっと恐ろしい臭いがする。",
		FEATHER_ROBIN_WINTER = "スノーバードの羽。それは燃えるときっと恐ろしい臭いがする。",
		FEM_PUPPET = "彼女は恐怖で死にかかっているように見える。",
		FIREFLIES =
		{
			GENERIC = "あいつらが逃げていかなければ！",
			HELD = "わたしのポケットの中の小さな火事のようだ。",
		},
		FIREHOUND = "実際わたしはこれが好き。",
		FIREPIT =
		{
			EMBERS = "まずい。ほぼなくなってしまった！",
			GENERIC = "何時間でもそれを見ていられる。",
			HIGH = "燃えろ！速攻で燃やせ！",
			LOW = "この火は小さくてつまらない。",
			NORMAL = "燃えろ！",
			OUT = "その火をまた起こすべきだな。",
		},
		FIRESTAFF = "これは俺がすごく好きなおもちゃだ。",
		FISH = "ツルツルしてて魚臭い！",
		FISHINGROD = "マヌケな魚を釣り上げる道具だよ",
		FISHSTICKS = "目にしたものが手に入る。魚のスティック。",
		FISHTACOS = "便利なタコスグリップ。",
		FISH_MED = "っしゃ！あとは火で焼くだけ～",
		FISH_MED_COOKED = "食べられないこともなさそうじゃん？",
		FISH_COOKED = "火を見つけた今はあまり滑らなくなった。",
		FLINT = "その可哀想な男の発火具。",
		FLOWER = "花に費やす無駄な時間はない。",
		FLOWERHAT = "花の後光。花の後光を燃やせなかったのはかなりまずい。",
		FLOWER_EVIL = "ウッ、あの臭いはひどすぎる。",
		FOLIAGE = "燃やすための燃料。",
		FOOTBALLHAT = "スポーツはハードだ。",
		FROG =
		{
			DEAD = "彼に見せつけた！",
			GENERIC = "彼は湿気があって燃えない。",
			SLEEPING = "あいつらが眠っているときは可愛い。",
		},
		FROGGLEBUNWICH = "サンドイッチにカエルの足入り、とは多分気づかずにいよう。",
		FROGLEGS = "時々またピクピク動いている。怖い。",
		FROGLEGS_COOKED = "その火でピクピク動いているのが止まった。火こそ最高。",
		FRUITMEDLEY = "美味しいフルーツ！",
		GEARS = "これらが奴らを動かすに違いない。",
		GHOST = "すでに死んでいるものを殺せやしない。",
		GOLDENAXE = "木を燃やさないが、少なくとも輝いている。",
		GOLDENPICKAXE = "岩に火はつけられないが、少なくとも輝いている。",
		GOLDENPITCHFORK = "地面を燃やさないが、少なくとも輝いている。",
		GOLDENSHOVEL = "燃え立つピットはできないが、少なくとも輝いている。",
		GOLDNUGGET = "これをどこで使うのだろう。",
		GRASS =
		{
			BARREN = "船尾が必要。",
			WITHERED = "ちょうど良く乾いてて、燃える準備バッチリ！",
			BURNING = "火だ！ウーーー！",
			GENERIC = "草むらだね…よく燃えそう！",
			PICKED = "草の刈り株はある種使い道がない。",
		},
		GREEN_CAP = "退屈だ！",
		GREEN_CAP_COOKED = "火でそれを変えたのよ！",
		GREEN_MUSHROOM =
		{
			GENERIC = "愚かなキノコ。",
			INGROUND = "ねえ！おまえ！ここに登って来い！",
			PICKED = "多分いつかは帰ってくるだろう。",
		},
		GUNPOWDER = "ワーッ！輝いている！",
		HAMBAT = "お目にかかれて光栄です！",
		HAMMER = "鋭い道具のほうがいい。",
		HEALINGSALVE = "燃えている！でもその火はどこにある？",
		HEATROCK =
		{
			FROZEN = "凍った固体。",
			COLD = "石みたいに冷え冷え。",
			GENERIC = "炎があればこれにいい味を加えられる。",
			WARM = "炎がなく、熱もない… どこが楽しいの？",
			HOT = "どんな風に光るのか見て！",
		},
		HONEY = "甘くて美味しい！",
		HONEYCOMB = "それはろう状だ。",
		HONEYHAM = "火にハムと蜂蜜は良く合う。",
		HONEYNUGGETS = "わたしの友達の火に遭ったことがある、蜂蜜で覆われた欠片。",
		HORN = "中では毛深い獣の気配が聞こえる。",
		HOUND = "なんて間抜けな！",
		HOUNDMOUND = "やばい、その外見は好きじゃない。",
		HOUNDBONE = "気味悪い。",
		ICEBOX = "あれは火と真逆のもの。",
		ICEHOUND = "気味悪い！寒い！",
		INSANITYROCK =
		{
			ACTIVE = "わたし、幻覚を見てる？",
			INACTIVE = "良く燃えていないようだ。なんて退屈なの。",
		},
		JAMMYPRESERVES = "ドカン、ドスン、ピンチ！ありがとうございます、マダム。",
		KABOBS = "肉と火、今なら小枝付き！",
		KILLERBEE =
		{
			GENERIC = "あの蜂のジブの切れ具合が好きだ。",
			HELD = "ブンブン！",
		},
		KNIGHT = "ポニーだ！",
		KOALEFANT_SUMMER = "わたしたちは素晴らしい友達になれるだろう！",
		KOALEFANT_WINTER = "彼はとても暖かそうだ…",
		KRAMPUS = "下がっててよ、バカ野郎！",
		KRAMPUS_SACK = "もうクリスマス？やった！",
		LEIF = "あいつは燃えやすそうだ！",
		LEIF_SPARSE = "あいつは燃えやすそうだ！",
		LIGHTNING_ROD =
		{
			CHARGED = "あああ、光は全て発しているが火はない。",
			GENERIC = "稲妻はみんな、ここに落ちてくるはずだよ！",
		},
		LITTLE_WALRUS = "彼は美味しそうだな。",
		LIVINGLOG = "動揺しているようだ。",
		LOCKEDWES = "彼はこれらのみすぼらしい彫像にだまされた！",
		LOG =
		{
			BURNING = "燃えろ、丸太、燃えろおーー！",
			GENERIC = "木だ！かなり良く燃える！やったー！",
		},
		LUREPLANT = "素早く火をつければこれを始末できるに違いない。",
		LUREPLANTBULB = "今はわたしの物。",
		MALE_PUPPET = "彼は半分死にかかっておびえているようだ。",
		MANDRAKE =
		{
			DEAD = "なぜこの植物には顔があるの？",
			GENERIC = "普通の草…じゃないよね？",
			PICKED = "今は単にゾッとする！",
		},
		COOKEDMANDRAKE = "その火では顔を燃やし尽くせなかった。ドキドキさせやがる。",
		MANDRAKESOUP = "スープにしたのに、まだ顔がついてるし！",
		MARBLE = "重たい！",
		MARBLEPILLAR = "残りの燃え落ちたものはどうなっているの。",
		MARBLETREE = "最悪の種類の木。燃えないタイプ。",
		MARSH_BUSH =
		{
			BURNING = "燃えろ、とげよ！",
			GENERIC = "尖っていそうだ。",
			PICKED = "このとげは傷つけるぞ！",
		},
		MARSH_PLANT = "全部植物っぽい。",
		MARSH_TREE =
		{
			BURNING = "イエス！燃えろ！",
			BURNT = "まだそれが燃えていればなぁ。",
			CHOPPED = "今はあまり先が尖ってないよな？",
			GENERIC = "危なそうだ！",
		},
		MAXWELL = "あいつは相当恩着せがましい。",
		MAXWELLHEAD = "彼はとてもおしゃべり好きだ。",
		MAXWELLLIGHT = "こいつらは楽しくない。自分で自分を照らす。",
		MAXWELLLOCK = "あとは鍵が必要なだけ。",
		MAXWELLTHRONE = "粘着性があるようだ。",
		MEAT = "火をもってすればこれをマシにできるかもしれない。",
		MEATBALLS = "球体を肉で作り、火で改善された。",
		MEAT_DRIED = "硬くてかまなきゃならないけど、満足。",
		MERM = "気色悪い、全部沼地だ。",
		MONSTERLASAGNA = "麺、肉、髪の塊。ゾッとする。",
		MONSTERMEAT = "気味悪い。髪の毛でいっぱいだ。",
		MONSTERMEAT_DRIED = "乾いていて変な臭いがする。",
		MOSQUITO =
		{
			GENERIC = "かなりうっとうしい！",
			HELD = "その口をわたしから遠ざけて！",
		},
		MOSQUITOSACK = "血液は血管を蒸し暑い中ドロッと流れなければならない。",
		MOUND =
		{
			DUG = "自分よりそのほうが適任。",
			GENERIC = "屍でいっぱいに違いない、と思う。",
		},
		NIGHTLIGHT = "火のようだけど、紫だ！",
		NIGHTMAREFUEL = "うわぁ、まだ温かい！",
		NIGHTSWORD = "現実を損なうわたしの夢みたい！",
		NITRE = "内部に小さな爆発物が仕掛けられている。",
		ONEMANBAND = "火工品も作れる！",
		PANDORASCHEST = "ちょっと悪趣味。",
		PANFLUTE = "音楽は退屈だ。",
		PAPYRUS = "それは燃えるに違いない！",
		PENGUIN = "チビダンサー達、逃げて。",
		PERD = "邪悪な鳥！わたしの美味しいベリーから離れろ！",
		PEROGIES = "火で密封された美味いもの。",
		PETALS = "愚かな花たち。ほとんど役に立たない。",
		PETALS_EVIL = "ゲッ、奴らはネバネバしている。",
		PICKAXE = "かなり尖っている。",
		PIGGYBACK = "切れ端からバックパックを作った！",
		PIGKING = "うぇー。なんて薄汚い奴だ。",
		PIGMAN =
		{
			DEAD = "あいつらはどんな味がするのだろう。",
			FOLLOWER = "おえっ！わたしに付いてきている。",
			GENERIC = "うっ！良い香りがする。",
			GUARD = "あいつはわたしのボスじゃない！",
			WEREPIG = "かかってこい、子豚！",
		},
		PIGSKIN = "ハハ。ブタの尻。",
		PIGTORCH = "このブタたちは確かに楽しい時間の過ごし方を知っている。",
		PINECONE = 
		{
		    GENERIC = "おい、木の種。",
		    PLANTED = "おまえはじきに、本物の木になる。",
		},
		PITCHFORK = "3倍のとんがり方。",
		PLANTMEAT = "気色悪い、全部ネバネバしている。",
		PLANTMEAT_COOKED = "火ですべてがより良くなる。",
		PLANT_NORMAL =
		{
			GENERIC = "どうしてもっていうのなら、食べてやる。",
			GROWING = "急げ、このうすのろ植物！",
			READY = "ああ。野菜。",
			WITHERED = "パチパチ言って、乾いてる。いい焚き付け！",
		},
		POMEGRANATE = "そいつが沢山のパーツを持っているってこと？",
		POMEGRANATE_COOKED = "火はいつも快適にする。",
		POMEGRANATE_SEEDS = "実の中にビッシリ詰まってたやつだね",
		POOP = "うわ。ゾッとする。でも便利。",
		PUMPKIN = "これ、火であぶったらどうなるかな…",
		SCORCHED_SKELETON = "げ！グロ注意ッ！",
		PUMPKINCOOKIE = "クッキー！！！",
		PUMPKIN_COOKED = "外の炎は上手い具合に燃えていた。",
		PUMPKIN_LANTERN = "内側が燃えているなんて素晴らしい！",
		PUMPKIN_SEEDS = "火と相性バッチリの野菜の種だよ",
		PURPLEGEM = "変だ！",
		RABBIT =
		{
			GENERIC = "彼は美味しそうだな。",
			HELD = "つっかまーえたっ！",
		},
		RABBITHOLE = 
		{
			GENERIC = "愚かなウサギ達。出ておいで、食べてあげるから。",
			SPRING = "愚かなウサギ達は足止めされてるのかな。",
		},
		RATATOUILLE = "野菜。すごく沢山の野菜。",
		RAZOR = "なぜわたしはこれを建てたのだ？",
		REDGEM = "なんて可愛い！",
		RED_CAP = "その色が好きだ。",
		RED_CAP_COOKED = "火でそれを変えたのよ！",
		RED_MUSHROOM =
		{
			GENERIC = "かわいい！",
			INGROUND = "ねえ！おまえ！ここに登って来い！",
			PICKED = "多分いつかは帰ってくるだろう。",
		},
		REEDS =
		{
			BURNING = "燃えろ！イェイ！",
			GENERIC = "燃えるアシの一群。",
			PICKED = "アシの刈り株では何もできない。",
		},
        RELIC = 
        {
            GENERIC = "古い家具。",
            BROKEN = "こまごまとした物、雑用。",
        },
        RUBBLE = "壊れた家具。",
		RESURRECTIONSTONE = "それに触るべきってこと？",
		ROBIN =
		{
			GENERIC = "赤い鳥。火の色、でも不死鳥ではない。",
			HELD = "わたしのポケットの中は居心地が良い。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "ここは冷め切っているようだ。火を欲しがっているに違いない。",
			HELD = "とてもフワフワしている。",
		},
		ROBOT_PUPPET = "あのロボット、すっごく怖がってる…",
		ROCK_LIGHT =
		{
			GENERIC = "中に熱がこもってる…今にも噴き出しそう！",
			OUT = "おや、冷めた。",
			LOW = "溶岩が冷めてきている。",
			NORMAL = "火のプール！",
		},
		ROCKS = "こんなん集めて、なんに使うの？",
        ROOK = "城だ！",
        ROPE = "これと組み合わせて何ができる？",
		ROTTENEGG = "うわ！なぜだ？おーなぜだ？！",
		SANITYROCK =
		{
			ACTIVE = "これらのマーキングの意味はなんだろう。",
			INACTIVE = "それはどこに行ったのだ？",
		},
		SAPLING =
		{
			BURNING = "燃えろ！イェイ！",
			WITHERED = "カッサカサ…すっごい火つけたい…",
			GENERIC = "わたしがそれを拾うべき。",
			PICKED = "哀れな小さなしなびた木。",
		},
		SEEDS = "耕作は退屈だ。",
		SEEDS_COOKED = "今耕作するには適さない。",
		SEWING_KIT = "でも破壊するほうが、本当にずっと楽しい！",
		SHOVEL = "戦うことは素晴らしいわけじゃない。",
		SILK = "おいしいーーー。滑らか。",
		SKELETON = "かわいそうに…名誉の焼死だったのかな…",
		SKELETON_PLAYER = "それを見るとゾクゾクする。",
		SKULLCHEST = "ワーッ、不気味だ！",
		SMALLBIRD =
		{
			GENERIC = "完全に不死鳥ではないが、十分可愛いと思う。",
			HUNGRY = "お腹はすいているのか？",
			STARVING = "わかったわかった！おなか減ったんだね！",
		},
		SMALLMEAT = "火をもってすればこれをマシにできるかもしれない。",
		SMALLMEAT_DRIED = "硬くてかまなきゃならないけど、満足。",
		SPAT = "その顔、なんかムカつく！",
		SPEAR = "ブッ刺してやるー！",
		SPIDER =
		{
			DEAD = "ハハ！君に見せたぜ！",
			GENERIC = "彼は扱いにくい。殺すべきだ。",
			SLEEPING = "わたしが彼を捕まえるべきだ。",
		},
		SPIDERDEN = "単に君が悪い。",
		SPIDEREGGSACK = "大量の小さな気色悪いクモたち。",
		SPIDERGLAND = "気色悪い、ネバネバして臭い！",
		SPIDERHAT = "君の母親は誰！",
		SPIDERQUEEN = "それを火で殺せ！",
		SPIDER_WARRIOR =
		{
			DEAD = "彼は自業自得だ。",
			GENERIC = "多分それを殺せる…火をもってすれば。",
			SLEEPING = "多分ただそれだけを残していくべきだ。",
		},
		SPOILED_FOOD = "少なくともそれはまだ燃やせる。",
		STATUEHARP = "あの像、いいね。壊れたらやだなー",
		STATUEMAXWELL = "あの男を嫌いになり始めている。",
		STEELWOOL = "火つければ、赤くなって燃えるよ",
		STINGER = "ぐず！",
		STRAWHAT = "藁で作った帽子。考えてみれば、それは燃えやすいのかもしれなかった。",
		SUNKBOAT = "かなり消えかかっている、わたしですらそれを燃やせない！",
		SWEATERVEST = "燃え立つベストみたいにステキじゃないが、事足りる。",
		TAFFY = "甘いものはかなりよく燃えるが、そうではなくて食べるべきだ。",
		TALLBIRD = "そいつは友達になりたがるとは思わない。",
		TALLBIRDEGG = "それは火のようなもの？",
		TALLBIRDEGG_COOKED = "炎でこれらはずっと良くなった。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "もっと火が必要だ！",
			GENERIC = "わたしの不死鳥よ、蘇れ！",
			HOT = "火が強過ぎるなんてことがある？",
			LONG = "これはあとどの位かかるのか？",
			SHORT = "わたしは待ちくたびれてきた。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "その卵は火を利用できる！",
			PICKED = "巣はからっぽ。",
		},
		TEENBIRD =
		{
			GENERIC = "彼はわたしを理解しているように感じる。",
			HUNGRY = "彼はすごく沢山食べる。",
			STARVING = "わたしを見るな！自分の食事を食べてよ。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "ただこの世界が燃えるのを見たい。",
			GENERIC = "そのシンボルの光り方が好きだ。",
			LOCKED = "どうにかして鍵を開けなくては。",
			PARTIAL = "怪物を作っているところ！",
		},
		TELEPORTATO_BOX = "温かい感じがする。",
		TELEPORTATO_CRANK = "この部分は何に役立つのか？",
		TELEPORTATO_POTATO = "多分それをもっと喜ばれる形に溶かすこともできた。",
		TELEPORTATO_RING = "これは高価すぎて燃やせない！",
		TENTACLE = "全然柔らかくない。",
		TENTACLESPOTS = "ウワッー。",
		TENTACLESPIKE = "先がとがってて、ネバネバ。",
		TENTACLE_PILLAR = "ブルブル震えている。",
		TENTACLE_PILLAR_HOLE = "くっさー！焼いちゃったほうがよくない！？",
		TENTACLE_PILLAR_ARM = "アーーー、彼らはハグをしたがっている！",
		TENTACLE_GARDEN = "少し掘り返している音が聞こえる。",
		
		LAVA_POND_ROCK = "まぁた、岩？はぁー…",
		LAVA_POND_ROCK2 = "まぁた、岩？はぁー…",
		LAVA_POND_ROCK3 = "まぁた、岩？はぁー…",
		LAVA_POND_ROCK4 = "まぁた、岩？はぁー…",
		LAVA_POND_ROCK5 = "まぁた、岩？はぁー…",
		LAVA_POND_ROCK6 = "まぁた、岩？はぁー…",
		LAVA_POND_ROCK7 = "まぁた、岩？はぁー…",

		TOPHAT = "シルクハットとライター、完璧な組み合わせ。",
		TORCH = "火は本当に美しい。",
		TRAP = "少し受動攻撃的だが、まだ動く。",
		TRAP_TEETH = "火があればマシなのに。",
		TRAP_TEETH_MAXWELL = "どんな嫌な奴が、こういう物を置いていくわけ？",
		TRINKET_1 = "これを溶かした火は猛烈に熱かったに違いないと思う。",
		TRINKET_10 = "あんま燃えなそう",
		TRINKET_11 = "オー、奴は火炎放射器を持っているのか！",
		TRINKET_12 = "干からびてる…火であぶったみたい！",
		TRINKET_2 = "安物の偽物。多分適当に燃えることもない。",
		TRINKET_3 = "その結び目がひっかかっている。君が火を手に入れたら、ナイフが必要なのは誰？",
		TRINKET_4 = "彼は炎の中でプレスされたようだ。",
		TRINKET_5 = "これらのちっぽけなスラスタを調べろ。すごい爆発性のパワー！",
		TRINKET_6 = "火の粉さえもない。",
		TRINKET_7 = "火はもっと楽しい。",
		TRINKET_8 = "水風呂を好きになったことなど一度もない。",
		TRINKET_9 = "チャックの上でマッチは擦れるが、ボタンでは無理。",
		TRUNKVEST_SUMMER = "これからは友達と永遠に一緒にいるつもり。",
		TRUNKVEST_WINTER = "理想的な炎のように温かくはないけど、まあ悪くない！",
		TRUNK_COOKED = "それを食べたいかどうか、まだ確信がない。",
		TRUNK_SUMMER = "えっと、奴は部分的にまだ柔らかい。",
		TRUNK_WINTER = "とてもソフトでグニャグニャする！",
		UMBRELLA = "その色はすごくいい！",
		WAFFLES = "やぁ、ワッフル！",
		WALL_HAY_ITEM = "うーん。こいつらは燃えるかどうか。",
		WALL_STONE = "まあ…安全なのは間違いないかな…",
		WALL_STONE_ITEM = "こいつらはびっくりするほど重たい。",
		WALL_RUINS = "そして彼らは息を弾ませるだろう！",
		WALL_RUINS_ITEM = "これってわたしのポケットに入る大きさだと思う？",
		WALL_WOOD_ITEM = "わたしは隠れるのが嫌いだ。",
		WALL_MOONROCK = "これで、とりあえずは安全かな",
		WALL_MOONROCK_ITEM = "持ち運べないこともない感じ？",
		WALRUS = "わたしに付いてくるな！",
		WALRUSHAT = "その見かけは好きな感じ。",
		WALRUS_CAMP =
		{
			EMPTY = "その中に入るつもりはない。ゲーッ！",
			GENERIC = "なんでみんなわたしより良い家を持っているの？",
		},
		WALRUS_TUSK = "むしゃむしゃむしゃ。",
		WARDROBE = 
		{
			GENERIC = "火、つけたい…",
            BURNING = "うはは！燃えろ燃えろー！",
			BURNT = "あーあ、火、消えちゃった",
		},
		WARG = "あんたは意地悪でやな奴！",
		WASPHIVE = "距離を置いておいた方がよさそう。",
		WETGOOP = "ちゃんと強火にかけたのに！なんで！？",
		WINTERHAT = "わたしの趣味にピッタリくるほど温かくはない。",
		WORMHOLE =
		{
			GENERIC = "小枝でそれを突き刺せ！",
			OPEN = "あいつは辛い食べ物を好きなのか？",
		},
		ACCOMPLISHMENT_SHRINE = "あの矢を憎んでいる！", 

		------------------------------------------------------capy--------------------------------
		AERODYNAMICHAT = "速く歩くと、火が消えちゃうじゃんー…",
		ARMOR_LIFEJACKET = "これ着てても、ライターは、ぬれちゃうよね…？",
		ARMOR_SNAKESKIN = "着ると、キケンな気分になるよね",
		ARMOR_WINDBREAKER = "風は火の天敵だからねー",
		ARMORLIMESTONE = "うー…重い～…",
		ARMOROBSIDIAN = "襲ってくるやつは、燃やしてやる～！",
		ARMORSEASHELL = "これ着れば、最強じゃん？",
		ARMOUREDBOAT = "これなら、怪物にかみつかれても平気だね",
		BABYOX = "…クサッ！",
		BALLPHIN = "こいつは、あんま燃えなそうだなー",
		BALLPHINPOD = "今日は、家族そろってるんだねー",
		BAMBOOTREE = "A stick-y shrub.",
		BERRYBUSH2_SNAKE = "ウーーーン。ベリー。",--I don't think these should have diff name or examine text
		BERRYBUSH_SNAKE = "ウーーーン。ベリー。",--I don't think these should have diff name or examine text
		BIOLUMINESCENCE = "光ってるけど、熱くない…つまんないの",
		BLOWDART_POISON = "ポイズンキーッス！",
		BOAT_LANTERN = "光ってるけど、燃えてないじゃん…",
		BOTTLELANTERN = "この光…冷たい感じ…ヘンなの",
		BURIEDTREASURE = "つまんない物だったら、箱ごと燃やそ！",
		BUSH_VINE = "I bet these crackle and pop when they burn.",
		SNAKEDEN = "I bet these crackle and pop when they burn.",--I don't think these should have diff name or examine text
		CANNONSHOT = "発射ー！",
		CAPTAINHAT = "これかぶると、船も気分も沈まない感じ！",
		CARGOBOAT = "燃やす物、たくさん運べるね",
		CHIMINEA = "炎に、おうちを造ってあげたよ！",
		CIRCLINGSEAGULL = "そのまま太陽につっこんで燃えちゃえ！",
		CLOTHSAIL = "うまく縫えてるじゃん",
		COCONUT = 
		{
		    GENERIC = "木から落ちてきたけど、食べられるっぽい",
		    PLANTED = "さっさと育って、日陰作ってよー",
		},
		COCONUT_COOKED = "こんがり焼けた～！",
		COFFEE = "急にやる気出てきた！",
		COFFEEBEANS = "火であぶらないと！",
		COFFEEBEANS_COOKED = "んー、いい香り～♪",
		COFFEEBUSH = "This bush flourishes near the volcano's fire!",
		CORAL = "きれいな色だねー",
		CORALREEF = "シュノーケルがあったら、楽しいのになー",
		CUTLASS = "生ぐさいー…",
		DEAD_SWORDFISH = "火であぶれば、生ぐさくなくなるよ",
		DEPLETED_BAMBOOTREE = "竹さーん？もしもーし？",
		DEPLETED_BUSH_VINE = "戻ってこーい！",
		DOYDOY = "この鳥…目が死んでるよ",
		DOYDOYBABY = "かわいそうなぐらいアホな鳥のヒナだよ",
		DOYDOYEGG = "卵もアホそうだね",
		DOYDOYEGG_COOKED = "アホそうな鳥の卵を焼いたよ！",
		DOYDOYEGG_CRACKED = "この星の平均知性レベルが下がったよね",
		DOYDOYFEATHER = "よく燃えそう",
		DOYDOYNEST = "アホな鳥がどんどん生まれてくるよ",
		DUBLOON = "海賊のおカネだ！",
		DUG_BAMBOOTREE = "地面に植えないとダメかー",
		DUG_BERRYBUSH2 = "あんた、このまま死ぬのはイヤ？",
		DUG_BUSH_VINE = "地面に植えてほしい？",
		DUG_COFFEEBUSH = "地面に植えればいんだよね？",
		EARRING = "金ピカ！",
		FABRIC = "竹で、こんなのも作れちゃうんだねー",
		FEATHERSAIL = "あの鳥、アホだけど、羽根はいい帆になるね",
		FIRERAIN = "火の玉が降ってくるー！ヒャッハー！",
		FIRERAINSHADOW = "さあ来た！",
		FISHINHOLE = "魚って、なんでこんなとこに住んでんの？",
		GASHAT = "クサいニオイを嗅がずに済むね",
		GOLDENMACHETE = "もったいなくて使えないよー",
		ICEMAKER = "It turns fire into ice. Boo.",
		IRONWIND = "これならスイスイ進めるね",
		JELLYFISH = "シワシワに縮んでる…",
		JELLYFISH_DEAD = "これでもう、刺される心配ないね",
		JELLYFISH_COOKED = "フツーに食べられそうだよ",
		JELLYFISH_PLANTED = "あんたの名前、「クラゲン」でいい？",
		JELLYJERKY = "かみ切れなそうなんだけど…",
		JUNGLETREESEED =
        {
            GENERIC = "植えて、木にして、燃やそう！",
            PLANTED = "近い将来、山火事に貢献してくれるはず…！",
        },
		LAVAPOOL = "アッツアツ！ヤバい、最高！",
		LIMESTONE = "これ、死んでつぶれた魚の死骸でしょ？",
		LIMPETS = "ちょっと火であぶれば、おいしくなるはず",
		LIMPETS_COOKED = "けっこうイケるよ！",
		LOBSTERHOLE = "ロブスターくんのおうちだね",
		LOGRAFT = "たき火用の薪って、船にもなるんだね！",
		MOSQUITO_POISON = "シッ！シッ！",
		MUSSEL = "黙ってないで、なんか言いなよ",
		MUSSEL_COOKED = "火であぶると、口あけるんだね",
		MUSSEL_STICK = "貝って、なぜか棒にくっつくんだよね",
		OBSIDIAN = "この岩、アッツアツだよ！",
		OBSIDIAN_WORKBENCH = "ここで、炎系アイテムつくれるよ！",
		OBSIDIANAXE = "切れるし、焼けるし、最高じゃん！",
		OBSIDIANCOCONADE = "黒曜石使うと、火力大幅アップだね！",
		OBSIDIANFIREPIT =
		{
			EMBERS = "まずい。ほぼなくなってしまった！",
			GENERIC = "何時間でもそれを見ていられる。",
			HIGH = "燃えろ！速く燃えろ！",
			LOW = "この火は小さくてつまらない。",
			NORMAL = "こんなぜいたくして、いいのかな！",
			OUT = "その火をまた起こすべきだな。",
		},
		OBSIDIANMACHETE = "アツい女子のマストアイテムだよね！",
		SPEAR_OBSIDIAN = "突っつけるし、燃やせるし、最高！",
		OBSIDIANSPEARGUN = "あたしの本領発揮ー！",
		PACKIM = "こいつは…仲間？",
		PACKIM_FISHBONE = "なんか意味ありげだよね…",
		PALMLEAF = "よく燃えそうだな",
		PALMTREE_BURNT = "んー、かぐわしい香りー！",
		PALMTREE_STUMP = "はい、いっちょあがりー",
		PARROT = "真っ赤だね…炎の色だ！",
		PIRATEHAT = "海賊み、ハンパない！",
		PIRATIHATITATOR = "Cursed pirate magic?",
		POISONHOLE = "自然って、ときどきグロいよね",
		RAFT = "海でこれに火をつけるのは、やめとこっと",
		ROWBOAT = "手でこげって？は？何言ってんの？",
		SAIL = "風をうまく利用できるね",
		SAND = "ただの砂でしょ？",
		SANDBAG = "砂の詰まった袋だよ",
		SANDBAG_ITEM = "これを地面に置けばいいわけ？",
		SANDHILL = "あれはー…ただの砂の山だね",
		SEAGULL = "あの鳥、たぶん火が嫌いだよね？",
		SEASACK = "ビショビショだよ？これ、背負うの？",
		SEASHELL = "貝殻とか、ホント興味ないから",
		SEASHELL_BEACHED = "貝殻とか、ホント興味ないから",
		SEATRAP = "さっさと入れってばー！中は快適だよー！",
		SEAWEED = "草だけど、びしょぬれだよ",
		SEAWEED_COOKED = "火であぶったら、わりとマシになったね",
		SEAWEED_DRIED = "低カロリーのジャーキーだよ",
		SEAWEED_PLANTED = "草だけど、びしょぬれだね",
		SHARX = "めんどくさい連中が来たなー…",
		SLOTMACHINE = "時間のムダだよー",
		SNAKE = "うわ～、ヘビとかマジ勘弁",
		SNAKE_FIRE = "あいつとは、ちょっと気が合うかも",
		SNAKESKIN = "ヘビ皮、ゲット！",
		SNAKESKINHAT = "水をめっちゃはじくよ",
		SPEAR_POISON = "自分を刺さないように気をつけよっと",
		SPEARGUN = "海では、かなり重宝するよね",
		SPEARGUN_POISON = "これヤバいわー、ヤバすぎだわー",
		STUNGRAY = "うーわ、くっさー！",
		SUPERTELESCOPE = "地球の果てまで見えるよ",
		SWORDFISH = "アンギャルド！",
		TELESCOPE = "隠れてる島を見つけてやるー！",
		TIGERSHARK = "うわー、マジでかんべんしてよー！",
		TIGERSHARKSHADOW = "ヤバいヤバいヤバいヤバいッ…！",
		TOUCAN = "その鼻、かっこいいじゃん",
		TRAWLNET = "水浸しのアイテムがザクザクとれるよ",
		TRAWLNETDROPPED = "Everything is going to be wet in there.",
		TREEGUARD = "あたしも、あんたのこと気に入らないなー",
		TRIDENT = "ずぶぬれじゃん",
		TRINKET_13 = "オレンジ色だ…火の水かな？",
		TRINKET_14 = "針は持ってないなー…",
		TRINKET_15 = "うん、これは燃えるね",
		TRINKET_16 = "誰？こんなとこにゴミ捨てた人…",
		TRINKET_17 = "あたしの趣味じゃないなー",
		TRINKET_18 = "お宝だったりする…？",
		TRINKET_19 = "「ボンヤリ」って、病気なの？",
		TURBINE_BLADES = "これ、なんに使うの？",
		TURF_BEACH = "地面？興味ないな",
		TURF_JUNGLE = "地面？興味ないな",
		VENOMGLAND = "素手では触りたくないなー…",
		VINE = "何かに使う？それとも、燃やす？",
		VOLCANO = "地上最大の火力を誇る炎だよ！",
		VOLCANO_ALTAR = "Why would I wanna appease the volcano? Then it wouldn't shoot fire!",
		VOLCANO_ALTAR_BROKEN = "これじゃ、火山をなだめられないよー！",
		VOLCANO_EXIT = "帰りたくないなー…",
		VOLCANOSTAFF = "我は炎の破壊神なりー！ムワーッハッハ！",
		WALL_LIMESTONE = "デコボコしてるー",
		WALL_LIMESTONE_ITEM = "簡単には燃えなそうだなー",
		WHALE_BLUE = "こんなにでっかい魚、いるんだー",
		WHALE_CARCASS_BLUE = "オェー…腐り始めてるー",
		WHALE_CARCASS_WHITE = "これが「勝利のニオイ」…？オエッ…",
		WHALE_WHITE = "おー！目が燃えてる！",
		CRABHOLE = "出ておいでー！いっしょに遊ぼうよー！",
		CRAB =
		{
			GENERIC = "こら！逃げんな！",
			HIDDEN = "中に絶対、クラビットがいると思う",
		},
		BERMUDATRIANGLE = "見てると目が回ってくる～",
		BOATCANNON = "これで火つけられるのかなぁ？",
		BOATREPAIRKIT = "水もれしてるとこは、修理しないとね",
		MACHETE = "じゃまなものは、燃やせばよくない？",
		LUGGAGECHEST = "中に、いいもん入ってるかも！",
		DRAGOON = "あいつ、ペットにできないかなー",
		ANTIVENOM = "これで、毒とかくらっても安心だね",
		BAMBOO = "よく燃えそう…",
		FROG_POISON = "キモッ！こっち来んな！",
		OX = "体、丈夫そうだよね",
		PEACOCK = "かわいい！",
		SEAGULL_WATER = "キーキーうるさいなー",
		SNAKE_POISON = "キバが、めっちゃとがってる",
		SOLOFISH = "アホっぽい魚だなー",
		SPOILED_FISH = "触んないで！",
		TWISTER = "あたしの火、消したら怒るからね！",
		SAND_CASTLE =
		{
			GENERIC = "けっこう、かわいくできたんじゃん？",
			SAND = "お城だけど、砂でできてるよ",
		},
		SNAKEOIL = "これって…ホントに薬？",
		LOBSTER = "こら！逃げんな！",
		MESSAGEBOTTLE = "紙がビン詰めになってる！",
		MESSAGEBOTTLEEMPTY = "空きビンだね",
		SHARK_FIN = "ヒレが取れたんですけど…",
		VOLCANO_ALTAR =
		{
		 	GENERIC = "火の神様に、ささげ物をするところだよ",
		 	OPEN = "火の神様に、お供えができるよ！",
		},
		ELEPHANTCACTUS = "あいつには近寄ってほしくないなー",
		ELEPHANTCACTUS_ACTIVE = "いぃったい！",
		ELEPHANTCACTUS_STUMP = "もう生えてくんな！",
		DOUBLE_UMBRELLAHAT = "これ、お店で買うの、相当恥ずかしいよね",
		MUSSEL_FARM =
		{
			GENERIC = "んー、届かないなー",
			STICKPLANTED = "もうすぐ、あたしのものだね…フフフ",
		},
		WOODLEGS_CAGE = "オリに入って“おり”ます！なーんてね",

		 PIRATIHATITATOR =
		 {
		 	GENERIC = "なにこれ、アホくさ…",
		 	BURNT = "このほうがカッコよくない？",
		 },
		 COFFEEBUSH =
		 {
		 	BARREN = "ドリップし尽くしたっぽい",
		 	PICKED = "おかわり欲しかったのにー…",
		 	WITHERED = "愛情と灰が足んなかったかなー…",
		 	GENERIC = "ホットな大地で生まれた、ホットドリンク！",
		 },
		 DUG_ELEPHANTCACTUS = "水とか、やらなくていんだよね？",
		 WHALE_BUBBLES = "この泡、どっから出てるの…？",

		ARMORCACTUS = "これ着てれば、サボテンにやられないよ",
		BAMBOOTREE =
		{
			BURNT = "消えちゃったー…もっかい燃やしていい？",
			CHOPPED = "また生えてくるよね",
			GENERIC = "たきつけに使えそうじゃん！",
		},
		BLOWDART_FLUP = "攻撃力はイマイチだね",
		BLUBBER = "すっごいよく燃えそう！",
		BLUBBERSUIT = "動くたびにタプタプする～",
		BOAT = "燃やしたい…燃やしたい～…！",
		BOAT_TORCH = "船に火つける道具…じゃないっぽい",
		BRAINJELLYHAT = "頭よくなりそうだけど…見た目がグロいな…",
		BUOY = "フワフワしてるけど、けっこう頼りになるよ",
		BUSH_VINE =
		{
			BURNT = "燃やすと楽しいよ！",
			CHOPPED = "こんがらがったら、ぶった切ればいいよ！",
			GENERIC = "燃やしたらバチバチ言いそう！",
		},
		COCONADE =
		{
			BURNING = "ワクワク…",
			GENERIC = "ドーン！からの～、メラメラ～ってなるヤツ！",
		},
		COCONUT_HALVED = "これで食べられる♪",
		COFFEEBOT = "これでコーヒー作れるね！",
		COMPASS =
		{
			E = "東！",
			GENERIC = "んー、どっち？わかんないな…",
			N = "北！",
			NE = "北東！",
			NW = "北西！",
			S = "南！",
			SE = "南東！",
			SW = "南西！",
			W = "西！",
		},
		CORAL_BRAIN = "だんだんクセになる味かも…",
		CORAL_BRAIN_ROCK = "サンゴのフリして隠れてんだね、頭い～い！",
		CRATE = "火をつければ、中身ごと燃えるよね…",
		DEPLETED_GRASS =
		{
			GENERIC = "なにあれ？草？",
		},
		DEPLETED_GRASS_WATER = "休憩中かな",
		DRAGOONDEN = "短気なヤツらが住んでるよ",
		DRAGOONEGG = "触ると熱い…これ、岩じゃなくて、卵かも？",
		DRAGOONHEART = "あったかい食べ物は、ありがたいねー",
		DRAGOONSPIT = "ゲロが燃えてる…",
		FISH_RAW = "火であぶろう！",
		FISH_RAW_SMALL = "お刺身もいいけど、直火焼きが一番！",
		FISH_RAW_SMALL_COOKED = "魚と火って、相性バツグンだよね",
		FLAMEGEYSER = "見とれちゃうわー…",
		FLOTSAM = "うーん、遠いなぁー",
		FLUP = "こっち来んな！",
		FRESHFRUITCREPES = "おっしゃれー！",
		GRASS_WATER = "これなら、水やりしなくていいね",
		HAIL_ICE = "溶けてなくなれー！",
		HOME = "誰の家？",
		ICEMAKER =
		{
			HIGH = "燃料満タン！",
			LOW = "燃料、減ってきたっぽい",
			NORMAL = "どんどん氷作れー！",
			OUT = "燃料切れー",
			VERYLOW = "燃料、切れそう",
		},
		JUNGLETREE =
		{
			BURNING = "ヤバ！めっちゃ燃えてる！アハハ！",
			BURNT = "このほうが、ぜんぜんカッコイイよ",
			CHOPPED = "オノで何度か殴ったら、倒れたよ",
			GENERIC = "燃やしがいありそう！",
		},
		KNIGHTBOAT = "海の上でチェスすんの？",
		KRAKEN = "それを火で殺せ！",
		KRAKENCHEST = "遠慮なく、いただきまーす",
		KRAKEN_TENTACLE = "うわぁぁ！触んな！",
		LIMPETROCK =
		{
			GENERIC = "あの貝、岩を食べようとしてる…",
			PICKED = "くっついてた貝は、全部獲っちゃったよ",
		},
		LIVINGJUNGLETREE = "この木、なんかヘンじゃない？",
		LOBSTER_DEAD = "まあ…いざとなったら、食べるけど…",
		LOBSTER_DEAD_COOKED = "わりと豪華な感じになったかも！",
		MAGIC_SEAL = "光ってるー！",
		MAGMAROCK = "マグマが固まってできた岩だよ！",
		MAGMAROCK_FULL = "マグマが固まってできた岩だよ！",
		MAGMAROCK_GOLD = "マグマが固まってできた岩だよ！",
		MAGMAROCK_GOLD_FULL = "マグマが固まってできた岩だよ！",
		MANGROVETREE = "水やりは、しなくてよさそうだね",
		MANGROVETREE_BURNT = "水の中なのに、燃えたの…？",
		MARSH_PLANT_TROPICAL = "普通の草っぽいねー",
		MERMFISHER = "あいつ、ずーっと生ぐさそう…",
		MERMHOUSE_FISHER = "釣り師の家だよ",
		MONKEYBALL = "サルがキーキー言って喜びそう",
		MONSTERTARTARE = "気味悪い。",
		MOSQUITOSACK_YELLOW = "キショい虫が落としたよ",
		MUSSELBOUILLABAISE = "んー、いいにおい！",
		MYSTERYMEAT = "子育てって、ときどきキショいよね…",
		NEEDLESPEAR = "注射の針みたいじゃない？",
		OCTOPUSCHEST = "海のお宝が詰まってるよ！",
		OCTOPUSKING = "ダルそー",
		OXHAT = "この帽子、いい感じ！“ウッシ！”…なんつって",
		OX_FLUTE = "嵐になりそうな予感…",
		OX_HORN = "ウシくんのツノだー、ウッシッシ…",
		PALMLEAF_HUT = "雨よけにはなるけど…すぐ燃えそう",
		PARROT_PIRATE = "海賊のくせに、キーキーうるさいなぁ！",
		PEG_LEG = "これって…何？",
		PIGTENT = "くっさーい！",
		PIKE_SKULL = "キモチ悪いね…",
		PIRATEGHOST = "海賊？幽霊？どっちなの？",
		PIRATEPACK = "かついでると、筋肉つきそう",
		PORTAL_SHIPWRECKED = "そろそろ帰るかー",
		PRIMEAPE = "あんたも、火遊び好き？",
		PRIMEAPEBARREL = "サルの家だね。汚ったなーい！",
		RAWLING = "話し相手になってくれるよ",
		REDBARREL = "このタルは超お気に入り！",
		ROCK_CHARCOAL = "It drops burned things!",
		ROCK_OBSIDIAN = "This rock makes me so excited, I just want to explode!",
		SAIL_STICK = "船の舳先に立って、腕広げて叫びたくなるー！",
		SANDBAGSMALL = "これで、いろりの火を守れるね",
		SANDBAGSMALL_ITEM = "これで、いろりの火を守れるね",
		SHADOWSKITTISH_WATER = "え、何あれ！？",
		SHARKITTEN = "ママとはぐれちゃったのかな？",
		SHARKITTENSPAWNER =
		{
			GENERIC = "サメの気配がする…くぅ～燃えてきたぁー！",
			INACTIVE = "砂山だ…なんでこんなとこに？",
		},
		SHARK_GILLS = "死んだ魚にはもう、必要ないよね…？",
		SHARK_TEETHHAT = "これで、いつでも歯を見せて笑えるね！",
		SHIPWRECKED_ENTRANCE = "行ってみますかー！",
		SHIPWRECKED_EXIT = "帰ろ、帰ろー",
		SNAKEDEN =
		{
			BURNT = "燃やすの楽しかったー！",
			CHOPPED = "こんがらがったら、ぶった切ればいいよ！",
			GENERIC = "燃やしたらバチバチ言いそう！",
		},
		SNAKESKINSAIL = "この帆、キショくない？",
		SPEAR_LAUNCHER = "ヤリを発射できる銃って、最高じゃん",
		SUNKEN_BOAT =
		{
			ABANDONED = "乗ってた人たち、どこ行ったのかな？",
			GENERIC = "乗ってたヤツ、びしょぬれだろうねー",
		},
		SUNKEN_BOAT_BURNT = "踏んだり蹴ったりだねー",
		SUNKEN_BOAT_TRINKET_1 = "これって、何する道具？",
		SUNKEN_BOAT_TRINKET_2 = "おもちゃは片づけたはずなのに",
		SUNKEN_BOAT_TRINKET_3 = "あたしのライターと相性ぴったり！",
		SUNKEN_BOAT_TRINKET_4 = "…なにこれ？",
		SUNKEN_BOAT_TRINKET_5 = "サイズが合わないなー",
		SWEETPOTATOSOUFFLE = "んー、絶品！",
		SWEET_POTATO = "木イチゴばっかじゃ飽きるしね",
		SWEET_POTATO_COOKED = "火であぶったら、おいしくなったね",
		SWEET_POTATO_PLANTED = "燃やしたら、かわいくなると思う！",
		SWEET_POTATO_SEEDS = "植えたら、おイモが育つよ",
		SWIMMINGHORROR = "あいつ、泳げるの？サイアク！",
		TELEPORTATO_SW_BASE = "部品が足りないみたい",
		TELEPORTATO_SW_BOX = "なんかの部品かな",
		TELEPORTATO_SW_CRANK = "なんかを回すレバーとか？",
		TELEPORTATO_SW_POTATO = "なんかの装置？",
		TELEPORTATO_SW_RING = "なんかの部品だと思うけど…",
		THATCHPACK = "ヤシの葉って、便利だね",
		TIDALPOOL = "水を抜いたら、渦巻きはどっち回りかな？",
		TIDAL_PLANT = "植物だ！",
		TIGEREYE = "そんな目で見ないでもらえるかなー…",
		TRAWLNETDROPPED =
		{
			GENERIC = "さーて、何がとれたかなー！",
			SOON = "沈んじゃいそう！",
			SOONISH = "だんだん沈んでるっぽい",
		},
		TREASURECHEST_TRAP = "うわ！サイテー！",
		TRINKET_20 = "これって、何する道具？",
		TRINKET_21 = "おもちゃは片づけたはずなのに",
		TRINKET_22 = "あたしのライターと相性ぴったり！",
		TRINKET_23 = "何する道具か、さっぱりわかんない",
		TROPICAL_FISH = "すっごくきれいな色！",
		TUNACAN = "「イルカにやさしい」って、どゆこと…？",
		TURF_ASH = "灰っぽい地面だよ",
		TURF_MAGMAFIELD = "バクハツテキな地面！",
		TURF_MEADOW = "なんか、この地面、落ち着くね",
		TURF_SNAKESKINFLOOR = "触んないで！",
		TURF_TIDALMARSH = "グショグショ…",
		TURF_VOLCANO = "足元あったか！",
		TWISTER_SEAL = "かわいいコほど、油断ならないよねー",
		VOLCANO_ALTAR_TOWER = "火の記念碑だ！",
		VOLCANO_SHRUB = "You come pre-burnt!",
		WALLYINTRO_DEBRIS = "これって、あたしのせい…？",
		WATERYGRAVE = "んー、怪しい…ニオうなぁ…生臭いなぁ…",
		WHALE_TRACK = "火のないところに泡は出ない！ってね",
		WILBUR_CROWN = "これの持ち主、相当頭ちっちゃいね",
		WILBUR_UNLOCK = "このサル、派手派手だねー",
		WILDBORE = "ちょーっと、近づきたくない感じだよね",
		WILDBOREHEAD = "うぇっ！",
		WILDBOREHOUSE = "火をつけたら、バーベキューになるよね！",
		WIND_CONCH = "風で火が消えないといいけどなぁ",
		WOODLEGSBOAT = "この船、かっこいいじゃん",
		WOODLEGSHAT = "あたし用じゃないと思うな",
		WOODLEGSSAIL = "誰かが大事にしてる物っぽいよね",
		WOODLEGS_KEY1 = "どこのカギ？",
		WOODLEGS_KEY2 = "どっかに何かがしまわれてるってこと？",
		WOODLEGS_KEY3 = "カギ、みっけ！",
		WRECK = "誰かが後悔してそう",
		CALIFORNIAROLL = "魚と海藻？おいしいのかな…？",
		BANANAPOP = "火とは正反対だよねー…",
		BISQUE = "マズくはなさそう？",
		CEVICHE = "やっぱヌルヌルしててキショいな…",
		SEAFOODGUMBO = "はぁ？何これ…",
		SURFNTURF = "こんなの、じいさんばあさん用だよ…",
		SHARKFINSOUP = "火にかけてじっくり煮込んだよ！",
		LOBSTERDINNER = "これは絶対おいしいって！",
		LOBSTERBISQUE = "鍋ごとぜーんぶ食べちゃう！",
		JELLYOPOP = "あと20個はいけるな！",
		VOLCANO_SHRUB = "ちょっと！なんで燃やす前に焦げてんの！？",
		ROCK_OBSIDIAN = "すごい…きれいな…岩…ヤバ…",
		ROCK_CHARCOAL = "真っ黒！",
	},
	DESCRIBE_TOODARK = "もっと明かりが必要だ！",
	DESCRIBE_GENERIC = "うーん、燃やしたいー…！",
	DESCRIBE_SMOLDERING = "やったー、燃えて火がつこうとしている！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "オエエェェ！",
	},
}