return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Nie sądzę, żeby mu się to spodobało.",
			GENERIC = "Po cóż mam to czynić?",
			NOBITS = "Jest już gładki jak pupa niemowlaka.",
		},
		STORE =
		{
			GENERIC = "Nie zmieści się.",
			NOTALLOWED = "To tu nie pasuje.",
		},
		WRITE =
        {
            GENERIC = "Nie mogę tego teraz zrobić.",
        },
		RUMMAGE =
		{	
			GENERIC = "Motyla noga!",	
		},
		COOK =
        {
            GENERIC = "Nic nie może pójść według planu.",
            TOOFAR = "Muszę podejść bliżej.",
        },
        CHANGEIN =
        {
            GENERIC = "Jak ulepszyć ideał?",
            BURNING = "Och. No i tyle mam ze swoich poszetek.",
        },
        GIVE =
        {
            DEAD = "Martwi nie potrzebują takich rzeczy.",
            SLEEPING = "Jest kompletnie nieświadomy.",
            BUSY = "Akurat jest zajęty.",
        },
        TEACH =
        {
            KNOWN = "Jestem na to za mądry.",
            CANTLEARN = "Lepiej nie kombinować z tajemną wiedzą.",
        },
		REPAIRBOAT =
		{
			GENERIC = "Nie teraz.",
		},

	},
	ACTIONFAIL_GENERIC = "Nie udało się.",
	ANNOUNCE_MAGIC_FAIL = "Ta magia nie jest z tego świata.",
    ANNOUNCE_NOSLEEPONFIRE = "To chyba nie jest najlepszy pomysł.",
	ANNOUNCE_NODANGERSIESTA = "Depczą mi po piętach!",
	ANNOUNCE_NONIGHTSIESTA = "Czas na sen, nie na drzemkę.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Trochę tu zbyt straszno na takie rzeczy.",
	ANNOUNCE_NOHUNGERSIESTA = "Z reguły sjestę się robi po jedzeniu, nie przed.",
	ANNOUNCE_SHELTER = "Chroń mnie, przeklęte drzewo!",
	ANNOUNCE_BURNT = "Pali!",
	ANNOUNCE_TOOL_SLIP = "Szlag.",
	ANNOUNCE_DAMP = "Wilgoć nie jest elegancka.",
	ANNOUNCE_WORMS = "Zbliża się coś strasznego.",
	ANNOUNCE_WET = "Woda może zniszczyć najlepszy garnitur.",
	ANNOUNCE_WETTER = "Już chyba nigdy nie wyschnę.",
	ANNOUNCE_SOAKED = "Jestem bardziej mokry niż woda.",
	ANNOUNCE_ADVENTUREFAIL = "Jeśli ktokolwiek powinien sobie z tym poradzić, to właśnie ja.",
	ANNOUNCE_BEES = "Zabicie mnie nie zwróci wam miodu!",
	ANNOUNCE_BOOMERANG = "Auć! Niech to.... dwie lewe ręce!",
	ANNOUNCE_CHARLIE = "Charlie? To ja! Maxwell!",
	ANNOUNCE_CHARLIE_ATTACK = "Auć! To bolało, Charlie!",
	ANNOUNCE_COLD = "Zimno przeszywa me serce.",
	ANNOUNCE_HOT = "Moje serce nie zniesie tego gorąca!",
	ANNOUNCE_CRAFTING_FAIL = "Eee... Nie mogę tego zrobić.",
	ANNOUNCE_DEERCLOPS = "Nadchodzi jeden z nich.",
	ANNOUNCE_DUSK = "Zaraz się ściemni i Charlie się obudzi.",
	ANNOUNCE_EAT =
	{
		GENERIC = "**przełyka**",
		PAINFUL = "Auć! To bolało!",
		SPOILED = "To było paskudne.",
		STALE = "Data przydatności chyba już minęła.",
		INVALID = "Nie zbliżę tego do ust.",
		YUCKY = "Cywilizowani ludzie nie jedzą takich rzeczy.",  
	},
	ANNOUNCE_ENTER_DARK = "Ciemno! Nic nie widzę!",
	ANNOUNCE_ENTER_LIGHT = "Powrót światłości.",
	ANNOUNCE_FREEDOM = "Wolność! Nareszcie!",
	ANNOUNCE_HIGHRESEARCH = "Mój mózg aż puchnie od mocy!",
	ANNOUNCE_HOUNDS = "Ogary robią się niespokojne.",
	ANNOUNCE_HUNGRY = "W brzuchu mi gra.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Czuję łajno i pot bestii.",
	ANNOUNCE_HUNT_LOST_TRAIL = "A niech to! Uciekł.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Nie mogę tropić w tych warunkach!",
	ANNOUNCE_INV_FULL = "Mam już pełne kieszenie.",
	ANNOUNCE_KNOCKEDOUT = "Ugh. Głowa mi wysiada.",
	ANNOUNCE_LOWRESEARCH = "Niewiele się z tego dowiedziałem.",
	ANNOUNCE_MOSQUITOS = "Co za małe wredne robale.",
	ANNOUNCE_NODANGERSLEEP = "Nie teraz! Niebezpieczeństwo czyha!",
	ANNOUNCE_NODAYSLEEP = "Nie mogę spać w dzień.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Jak się teraz prześpię, rozreguluje mi się cały zegar biologiczny.",
	ANNOUNCE_NOHUNGERSLEEP = "Nie mogę spać. Jestem zbyt głodny.",
	ANNOUNCE_NO_TRAP = "Dziwne. Zapomnieli ją zastawić.",
	ANNOUNCE_PECKED = "Uspokój się!",
	ANNOUNCE_QUAKE = "Ten hałas nie wróży niczego dobrego.",
	ANNOUNCE_RESEARCH = "Wiedza to potęga. A potęga to... cóż, potęga.",
	ANNOUNCE_THORNS = "Podrapałem się.",
	ANNOUNCE_TORCH_OUT = "A niech to! Kolejna zgasła.",
	ANNOUNCE_FAN_OUT = "Nie będzie mi dane odetchnąć.",
	ANNOUNCE_COMPASS_OUT = "Kompas rozpadł się na kawałki.",
	ANNOUNCE_TRAP_WENT_OFF = "Ajć!",
	ANNOUNCE_UNIMPLEMENTED = "Hmm, jeszcze nie skończone.",
	ANNOUNCE_WORMHOLE = "Ech, ale tam paskudnie.",
	ANNOUNCE_CANFIX = "\nChyba umiałabym to naprawić!",
	ANNOUNCE_NOSANITY = "Głowa mi pęka!",
	ANNOUNCE_NOFUEL = "Potrzebuję koszmarnego paliwa.",
	ANNOUNCE_NOWARDROBEONFIRE = "To jest żart, tak?",
	ANNOUNCE_ACCOMPLISHMENT= "Muszę jakoś zabić czas.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Dla takich chwil warto się starać.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Odrobinkę się ruszyło.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Nic z tego!",
	ANNOUNCE_OTHER_WORLD_PLANT = "Tutaj nie mogę go zasadzić.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Jak kura pazurem. Nie dam rady tego przeczytać.",
	},
	ANNOUNCE_BOAT_DAMAGED = "Moja łódź jest uszkodzona.",
	ANNOUNCE_BOAT_SINKING = "Chyba mamy przeciek.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Po tym wszystkim czeka mnie taki koniec?!",
	ANNOUNCE_CRAB_ESCAPE = "Zręczny skorupiak...",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Otchłań mnie ogarnia!",
	ANNOUNCE_MAPWRAP_RETURN = "Co za szczęście!",
	ANNOUNCE_MAPWRAP_WARN = "Nie chcę mieć nic do czynienia z tą mgłą.",
	ANNOUNCE_MORETREASURE = "Ach, kolejna mapa prowadząca do zaginionego skarbu.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Nie wierzę, że gdzieś tu jest skarb.",
	ANNOUNCE_SHARX = "Wygląda na to, że ktoś mnie ściga.",
	ANNOUNCE_TRAWL_FULL = "Sieć zaraz pęknie!",
	ANNOUNCE_TREASURE = "Wygląda na to, że zaprowadzi mnie do jakiegoś... skarbu.",
	ANNOUNCE_VOLCANO_ERUPT = "Nie ma się co denerwować...",
	ANNOUNCE_WAVE_BOOST = "O to, to!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Gonić bestię!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Wykiwany przez rybę!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Wieloryb zniknął mi z oczu.",

	BATTLECRY =
	{
		GENERIC = "Do broni!",
		PIG = "Umysł ponad krzepę!",
		PREY = "Wyglądasz smacznie!",
		SPIDER = "Nie pozwolę robić z siebie durnia!",
		SPIDER_WARRIOR = "Zmuszasz mnie do tego!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "I trzymaj się z daleka!",
		PIG = "Do następnego razu, prosiaku!",
		PREY = "Szkoda na ciebie mojego czasu!",
		SPIDER = "Nie pozwolę robić z siebie durnia... następnym razem!",
		SPIDER_WARRIOR = "Następnym razem ci nie daruję!",
	},
	
	DESCRIBE =
	{
		LICHEN = "A slow growing cave plant.",
		ICEHOUND = "Jak szybko potrafią zapomnieć...",
		INVENTORYGRAVE = "Kto umieścił ten nagrobek?",
		INVENTORYMOUND = "Kolejna ofiara losu.",
		GLOMMER = "Latająca fabryka śluzu.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Flower power.",
        	DEAD = "Flower power na wieki wieków.",
        },
        GLOMMERWINGS = "Trochę się kleją.",
        GLOMMERFUEL = "Ale śmierdzi.",
        BELL = "Będzie hałas.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Hej! To nie mój posąg!",
        	EMPTY = "To go nauczy, żeby nie próbować być mną.",
    	},
		WEBBERSKULL = "Nie myśl, że tak łatwo uciekniesz.",
		MOLE =
		{
			HELD = "Koniec tego grzebania.",
			UNDERGROUND = "Wykopujesz to, co ja zakopię?",
			ABOVEGROUND = "Rozumiem, że odpowiedź brzmi „tak”.",
		},
		MOLEHILL = "Skryj się głęboko. Idę po ciebie!",
		MOLEHAT = "Nic dziwnego, że potrafią kopać godzinami.",
		NIGHTSTICK = "Dzień dobry.",
		RABBITHOUSE=
		{
			GENERIC = "Och, bardzo sprytne.",
			BURNT = "Spryt zgładził marchewkę.",
		},
		TURF_DECIDUOUS = "Gleba.",
		TURF_SANDY = "Gleba.",
		TURF_BADLANDS = "Gleba.",
		BEARGER = "Bierz, co chcesz.",
		BEARGERVEST = "Popatrz na tę kamizelę.",
		ICEPACK = "Komora hibernacyjna.",
		BEARGER_FUR = "Byłby z niego niezły dywanik.",
		BIGFOOT = "To jest dopiero paliwo dla koszmarów.",
		BONESHARD = "Wielokrotne złamanie otwarte.",
		BUZZARD = "Koneser mięsa.",
		CACTUS = 
		{
			GENERIC = "Jeżoroślina.",
			PICKED = "Kaktus platfus!",
		},
		CACTUS_MEAT_COOKED = "Kaktus w wersji jadalnej.",
		CACTUS_MEAT = "Włożenie tego do ust nie byłoby rozsądne.",
		CACTUS_FLOWER = "Ta część kaktusa jest fantastyczna.",
		COLDFIRE =
		{
			EMBERS = "Zaraz będzie po ptokach.",
			GENERIC = "Bardzo przyjemne.",
			HIGH = "Charlie przez jakiś czas się nie pokaże.",
			LOW = "Potrzeba paliwa.",
			NORMAL = "Płomienny, ale zimny.",
			OUT = "Skończyło się.",
		},
		CATCOON = "Przebiegły szkodnik.",
		CATCOONDEN = 
		{
			GENERIC = "Dom szkodnika.",
			EMPTY = "Cóż, to by chyba było na tyle.",
		},
		CATCOONHAT = "W sumie to jest trupia głowa.",
		COONTAIL = "Ogon straszliwego zwierza.",
		COOKPOT =
		{
			COOKING_LONG = "Trzeba zaczekać...",
			COOKING_SHORT = "Już niedługo!",
			DONE = "Nareszcie, jakieś porządne jadło.",
			EMPTY = "Na samą myśl cieknie mi ślinka.",
			BURNT = "Trochę za długo stał na ogniu, jak na mój gust.",
		},
		EYEBRELLAHAT =	"Zwróć oko ku niebu.",
		ARMORDRAGONFLY = "Pancerz smoka.",
		DRAGON_SCALES = "Ognista sprawa.",
		DRAGONFLYCHEST = "Te łuski są naprawdę szykowne.",
		DECIDUOUSTREE = 
		{
			BURNING = "Ups.",
			BURNT = "Skąpane w ogniu.",
			POISON = "Zamknij paszczę!",
			CHOPPED = "Raczej nie odrośnie.",
			GENERIC = "Niektórzy nazywają je „liściakami”.",
		},
		ACORN_COOKED = "Na otwartym ogniu.",
		BIRCHNUTDRAKE = "Orzech z nogami! Straszna rzecz!",
		FARMPLOT =
		{
			GENERIC = "Wyglądam na rolnika?",
			GROWING = "Mam lepsze rzeczy do roboty niż patrzenie, jak rosną rośliny.",
			NEEDSFERTILIZER = "Trzeba je trochę... odświeżyć.",
			BURNT = "Ognisty plon.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Powinienem się nim zająć.",
			GENERIC = "Palenisko.",
			HIGH = "Zimny, szalejący ogień.",
			LOW = "Zaczyna przygasać.",
			NORMAL = "Zimne.",
			OUT = "Zrobiło się ciepłe.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Przepadnij, ogniu!",
			OFF = "Cisza przed burzą.",
			LOWFUEL = "Zostało mało paliwa.",
		},
		ICEHAT = "Przytwierdź sobie lód do głowy...",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Co on tak ciągle przeżuwa?",
			CHARGED = "Ataaaak!",
		},
		LIGHTNINGGOATHORN = "Można by na nim zagrać.",
		GOATMILK = "Pełne składników odżywczych.",
		MEATRACK =
		{
			DONE = "Lepsze niż deser.",
			DRYING = "Jeszcze wilgotne.",
			DRYINGINRAIN = "Jest wilgotne i na razie takie zostanie.",
			GENERIC = "Mogę wysuszyć mięso, żeby dłużej było dobre.",
			BURNT = "Trochę za krucha, żeby powiesić na niej mięso.",
		},
		MERMHEAD = 
		{
			GENERIC = "Ciężko się uwolnić od ich wzroku.",
			BURNT = "Pieczona głowa merma. Pychota.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Starają się naśladować świnie, ale są jeszcze głupsi.",
			BURNT = "Palą się tak samo, jak te świńskie.",
		},
		FLOWERSALAD = "Liściaste błogosławieństwo.",
        ICECREAM = "Na poprawę humoru.",
        BANANAPOP = "Hmm... Nie wiem, na co liczyłem.",
        BISQUE = "Doskonałe danie. Tylko atmosfera do poprawki.",
        CEVICHE = "Wyborny, kulturalny posiłek.",
        SEAFOODGUMBO = "Wygląda całkiem przyzwoicie.",
        SURFNTURF = "Zbilansowany posiłek.",
        SHARKFINSOUP = "Moje wyrafinowane podniebienie uwielbia smak niebezpieczeństwa.",
        LOBSTERDINNER = "Zapomniałem chustki pod brodę.",
        LOBSTERBISQUE = "Ach, jednak prawdziwą przyjemność dają mi rzeczy wyrafinowane.",
        JELLYOPOP = "Hmm... Chyba nie pasuje do mojego wizerunku.",
        WATERMELONICLE = "Lodowy lizak.",
        TRAILMIX = "Owoce i orzechy.",
        HOTCHILI = "Gorąco jak w garnku!",
        GUACAMOLE = "Co za kretyn to wymyślił.",
		MOOSE = "Cokolwiek to jest, na pewno pochodzi z północy.",
		MOOSEEGG = "Elektryzujące.",
		MOSSLING = "Puchate... coś.",
		FEATHERFAN = "Wieje, czy to tylko mój wachlarz?",
		TROPICALFAN = "Wieje, czy to tylko mój wachlarz?",
		GOOSE_FEATHER = "Przydałaby mi się poduszka z takimi piórami.",
		STAFF_TORNADO = "Potęga wiatru.",
		PIGHEAD = 
		{	
			GENERIC = "Eee... urocze.",
			BURNT = "Pieczona wieprzowina!",
		},
		PIGHOUSE =
		{
			FULL = "Też bym się schował, gdybym był na jego miejscu.",
			GENERIC = "Nie imponuje odpornością.",
			LIGHTSOUT = "Będę chuchał i dmuchał!",
			BURNT = "Zobaczmy, czy teraz się schowasz.",
		},
		FERTILIZER = "Noszenie w rękach łajna nie przystoi dżentelmenom.",
		RAINOMETER = 
		{	
			GENERIC = "Wystarczy spojrzeć w górę, żeby stwierdzić to samo.",
			BURNT = "Deszcz nie nadszedł na czas.",
		},
		RAINCOAT = "Uciekaj, deszczu!",
		RAINHAT = "Może nie najwytworniejszy, ale nie można się bez niego obyć.",
		RESEARCHLAB = 
		{	
			GENERIC = "Nie mogę wręcz uwierzyć, że zapomniałem, jak to wszystko zbudować.",
			BURNT = "Ogień nauczył się, jak puścić ją z dymem.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Odblokowuje receptury o średniej przydatności.",
			BURNT = "Ogień go pochłonął.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Tutaj prowadzę swoje badania.",
			BURNT = "Badanie zakończone.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Całkiem elegancka maszyna.",
			BURNT = "Dla mnie trochę za gorący.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Mógłbym tego użyć.",
			BURNT = "Nie będzie już potrzebny.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Ofiara efektu cieplarnianego.",
			MELTED = "Zwykła kałuża.",
		},
		ROCK_ICE_MELTED = "Zwykła kałuża.",
		ICE = "Małe lodowce.",
        REFLECTIVEVEST = "Bezpieczeństwo ponad elegancję.",
		HAWAIIANSHIRT = "Najwytworniejsza ze wszystkich.",
		TENT = 
		{
			GENERIC = "Trochę zbyt rustykalny, jak na mój gust.",
			BURNT = "Trochę zbyt przypieczony, jak na mój gust.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Trochę prymitywne wykonanie, ale działa.",
			BURNT = "To by było na tyle w kwestii cienia.",
		},
		TRANSISTOR = "Nie wiem, jak to działa, ale działa.",
		TREASURECHEST = 
		{
			GENERIC = "Miejsce na łupy.",
			BURNT = "Teraz niczego już nie przechowa.",
		},
		TUMBLEWEED = "Kręć się z nami, kręć w kółeczko.",
		GRASS_UMBRELLA = "Raczej ładna niż wytworna.",
		PALMLEAF_UMBRELLA = "Użyteczna rzecz.",
		UNIMPLEMENTED = "Tajemnicza rzecz. Lepiej nie dotykać.",
		WALL_HAY = 
		{	
			GENERIC = "Cała góra podpałki.",
			BURNT = "Mówiłem.",
		},
		WALL_WOOD = 
		{
			GENERIC = "Całkiem wytrzymały, ale łatwopalny.",
			BURNT = "Ani wytrzymały, ani łatwopalny.",
		},
		WARG = "Samiec alfa!",
		WATERMELON = "To głównie woda. Trochę włóknista, słodka woda.",
		WATERMELON_COOKED = "Grillbuz.",
		WATERMELONHAT = "Klejący sposób na upały.",
		WINTEROMETER = 
		{
			GENERIC = "Niezbyt sensowny wynalazek.",
			BURNT = "Wielkie rzeczy...",
		},
		LIVINGTREE = "To drzewo ma twarz.",
		ICESTAFF = "Wieje chłodem.",
		WAXWELLJOURNAL = "Przykro mi, Charlie.",
		WORMLIGHT = "Świetna sztuczka.",
		WORM =
		{
		    PLANT = "Nie oszukasz mnie, roślinko.",
		    DIRT = "Coś się rusza.",
		    WORM = "A to ci nowość!",
		},
		EEL = "Żyją tylko w głębokich wodach.",
		EEL_COOKED = "Wolfgang pozwoli mu wślizgnąć się do brzucha.",
		UNAGI = "Będzie musiał wystarczyć.",
		EYETURRET = "Jedno z moich lepszych dzieł.",
		EYETURRET_ITEM = "Teraz muszę ją tylko ustawić.",
		MINOTAURHORN = "Przykro mi, że musiałem to zrobić, przyjacielu.",
		MINOTAURCHEST = "Czuję się, jakby wciąż żył.",
		THULECITE_PIECES = "Mógłbym połączyć kilka fragmentów, żeby stworzyć większy kawałek.",
		POND_ALGAE = "Jakieś algi.",
		GREENSTAFF = "W tej formie muszę polegać na narzędziach.",
		POTTEDFERN = "Po prostu urocza.",

		THULECITE = "Niezwykle rzadki, ale użyteczny materiał.",
		ARMORRUINS = "Tulecyt doskonale komponuje się z koszmarnym paliwem.",
		RUINS_BAT = "Paliwo jest w nim silne.",
		RUINSHAT = "Coś w sam raz dla mnie.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Serce miasta jest spokojne.",	--calm phase
			WARN = "Znów zaczyna bić.",	--Before nightmare
			WAXING = "Puls zaczyna rosnąć.", --Nightmare Phase first 33%
			STEADY = "Puls jest wyrównany.", --Nightmare 33% - 66%
			WANING = "Puls słabnie.", --Nightmare 66% +
			DAWN = "Znów się uspokaja.", --After nightmare
			NOMAGIC = "Puls nie ma wpływu na to miejsce.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "Bez odpowiedniej opieki zaczynają wariować.",
		ROOK_NIGHTMARE = "Budowniczy zostawili ją tu na pastwę koszmarów.",
		KNIGHT_NIGHTMARE = "Tego nie da się już naprawić.",
		MINOTAUR = "Proszę, proszę, paliwo zupełnie cię odmieniło.",	--Monster in labyrinth
		SPIDER_DROPPER = "Stworzenia w tym świecie ewoluują w zastraszającym tempie.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Ich największą wadą było duże zapotrzebowanie na paliwo.",	--Lights that activate during nightmare.
		RELIC = "They were all dead when I got here.",	--Fixed relic
		RUINS_RUBBLE = "The earthquakes have taken their toll.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "Nie wiem, dlaczego wcześniej o tym nie pomyślałem.",	--Works as axe and pickaxe
		GREENGEM = "Koszmarne paliwo ujawni swój prawdziwy potencjał.",
		ORANGESTAFF = "W tej formie muszę polegać na narzędziach.",	--Teleports player.
		YELLOWAMULET = "Będę się wyróżniać.",	--Emits light, player walks faster.
		GREENAMULET = "Przysięgam, że normalnie tego nie potrzebuję.",	--Reduce cost of crafting

		SLURPER = "Prymitywne istoty. Żyją tylko po to, by jeść i spać.",
		SLURPER_PELT = "Nawet po śmierci to stworzenie gotowe jest mi służyć!",
		ARMORSLURPER = "Wilgotny i dziwnie sycący.",
		ORANGEAMULET = "Prosta magia często najlepiej zdaje egzamin.",
		YELLOWSTAFF = "Z większym klejnotem byłby jeszcze potężniejszy.",
		YELLOWGEM = "Czuję drzemiącą w nim magię.",
		ORANGEGEM = "Odrobina paliwa i będzie naprawdę potężny.",
		TELEBASE = 
		{
			VALID = "To powinno wystarczyć.",
			GEMS = "Paliwo potrzebuje więcej punktów skupienia.",
		},
		GEMSOCKET = 
		{
			VALID = "Gotowe.",
			GEMS = "Paliwo potrzebuje skupienia.",
		},
		STAFFLIGHT = "Teraz cienie powinny się stąd wynieść.",
       	ANCIENT_ALTAR =
        {
        	WORKING = "Where are their gods now?",
        	BROKEN = "This can be partially restored.",
        },
        ANCIENT_ALTAR = "Gdzie są teraz ich bogowie?",
        ANCIENT_ALTAR_BROKEN = "Można go częściowo odbudować.",

        ANCIENT_STATUE = "Niegdyś była to dumna rasa.",

		CAVE_BANANA = "Jakbym jadł popiół.",
		CAVE_BANANA_COOKED = "Pieczony jest jeszcze gorszy..",
		CAVE_BANANA_TREE = "Wygląda na banana, ale jakoś mnie nie przekonuje.",
		ROCKY = "Nie bez powodu je wygnałem.",
		
		HOUNDSTOOTH="Można by go wykorzystać z modzie.",
		ARMORSNURTLESHELL="Ani krztyny klasy.",
		BAT="Paskudne. Paskudne bestie.",
		BATBAT = "Przemoc jeszcze nigdy nie dawała tyle frajdy.",
		BATWING="Nie zamierzam tego jeść.",
		BATWING_COOKED="I tak nie zamierzam go zjeść.",
		BEDROLL_FURRY="Przynajmniej do czegoś się nadają.",
		BUNNYMAN="Przypomina mi się, jak grałem w teatrzyku szkolnym.",
		FLOWER_CAVE="Ależ tu ciemno.",
		FLOWER_CAVE_DOUBLE="Ależ tu ciemno.",
		FLOWER_CAVE_TRIPLE="Ależ tu ciemno.",
		GUANO="Obrzydliwe!",
		LANTERN="Mam nadzieję, że ICH odstraszy.",
		LIGHTBULB="W końcu się wypali.",
		MANRABBIT_TAIL="Głupi królik.",
		MUSHTREE_TALL="Śmierdzi zgnilizną i porażką.",
		MUSHTREE_MEDIUM="Gdzie jest Wally?",
		MUSHTREE_SMALL="Ugh. Nie pachnie zbyt dobrze.",
		SLURTLE="Nie pamiętam ich...",
		SLURTLE_SHELLPIECES="Nie pasują do siebie.",
		SLURTLEHAT="Postawi mnie na nogi. Muszę walczyć!",
		SLURTLEHOLE="Odrażające.",
		SLURTLESLIME="Musi być jakiś lepszy sposób.",
		SNURTLE="Dziwne. Są chyba jakieś nowe.",
		SPIDER_HIDER="Sprytny jest.",
		SPIDER_SPITTER="Agresywny typ, co nie?",
		SPIDERHOLE="Skąd to się tu wzięło?",
		STALAGMITE="Kamienie. Co za nuda.",
		STALAGMITE_FULL="Kamienie. Co za nuda.",
		STALAGMITE_LOW="Kamienie. Co za nuda.",
		STALAGMITE_MED="Kamienie. Co za nuda.",
		STALAGMITE_TALL="Stalagmit. Co za nuda.",
		STALAGMITE_TALL_FULL="Stalagmit. Co za nuda.",
		STALAGMITE_TALL_LOW="Stalagmit. Co za nuda.",
		STALAGMITE_TALL_MED="Stalagmit. Co za nuda.",

		POWCAKE = "Zło przybiera najróżniejsze formy.",
		CAVE_ENTRANCE = 
		{
			GENERIC= "Zatkałem je wieki temu.",
			OPEN = "To nie był dobry pomysł!",
		},
        CAVE_EXIT = "Zabierzcie mnie stąd!",

		MAXWELLPHONOGRAPH = "Przeklęte pudło!",
		BOOMERANG = "Nie brudzi rąk.",
		PIGGUARD = "Bleee. Odrażający typ.",
		ABIGAIL = "Dlaczego ci śmiertelnicy po prostu nie mogą zostać martwi?",
		ADVENTURE_PORTAL = "A więc tu go zostawiłem!",
		AMULET = "Pozwala przetworzyć mroczną energię wszechświata.",
		ANIMAL_TRACK = "Jakiś głupi zwierz tędy przechodził.",
		ARMORGRASS = "Trochę surowy w dotyku.",
		ARMORMARBLE = "To naprawdę nie mój styl.",
		ARMORWOOD = "Ugh. Nie w moim stylu takie barbarzyńskie rozwiązania.",
		ARMOR_SANITY = "Czas otulić się koszmarem.",
		ASH =
		{
			GENERIC = "Proszek pachnący zniszczeniem.",
			REMAINS_GLOMMERFLOWER = "Zawsze znajdzie się inny glomer.",
			REMAINS_EYE_BONE = "Nie martw się. Skrzynek na świecie nie zabraknie.",
			REMAINS_THINGIE = "Podróż przez portal zmieniła jego strukturę.",
		},
		AXE = "Czasem proste rozwiązania są najlepsze.",
		BABYBEEFALO = "Nawet jako dzieci są paskudne.",
		BACKPACK = "Szkoda, że nie ma w tym świecie bagażowych.",
		BACONEGGS = "Właśnie tak powinno wyglądać śniadanie.",
		BANDAGE = "Klejący i rozciągliwy. Na gagę.",
		BASALT = "Stworzyłem kamień tak ciężki, że nie mogę go unieść.",
		BEARDHAIR = "Włochata sprawa.",
		BEDROLL_STRAW = "Nie przepadam za spaniem w takich warunkach.",
		BEE =
		{
			GENERIC = "Tak ciężko pracują. Głupie owady.",
			HELD = "I co mam z nią zrobić?",
		},
		BEEBOX =
		{
			FULLHONEY = "Oj kusi, ale niestety jest pełny pszczół.",
			GENERIC = "Mieszkanko dla moich pszczół.",
			NOHONEY = "Moje pszczoły za mało się starają.",
			SOMEHONEY = "Trzeba jeszcze trochę poczekać.",
			BURNT = "Pieczony miód.",
		},
		BEEFALO =
		{
			FOLLOWER = "A niech to. Idzie za mną.",
			GENERIC = "Popatrz tylko na to głupie zwierzę.",
			NAKED = "Teraz wygląda nie tylko głupio, ale do tego żałośnie.",
			SLEEPING = "Jak śpi, jest tylko marginalnie mniej głupi.",
		},
		BEEFALOHAT = "Wyczuciem smaku bym tego nie nazwał.",
		BEEFALOWOOL = "Śmierdzi oborą.",
		BEEHAT = "Jak będzie trzeba, to założę.",
		BEEHIVE = "Tylko nie pszczoły!",
		BEEMINE = "Ależ są cierpliwe.",
		BEEMINE_MAXWELL = "Może nie powinienem był jej tu umieszczać.",
		BERRIES = "Ech. Jakoś się zmuszę.",
		BERRIES_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		BERRYBUSH =
		{
			BARREN = "Potrzeba obornika.",
			WITHERED = "Za ciepło dla tego krzaczka.",
			GENERIC = "Że też przyszło mi jeść jakieś dzikie owoce...",
			PICKED = "No to teraz czekamy...",
		},
		BIRDCAGE =
		{
			GENERIC = "Nie dam się już więcej zamknąć.",
			OCCUPIED = "Rozumiem twój ból, pierzasty przyjacielu.",
			SLEEPING = "I tak tu będziesz, jak się obudzisz.",
			HUNGRY = "O co tyle krzyku?",
			STARVING = "Nie wygłupiaj się, karmiłem cię w zeszłym tygodniu.",
			DEAD = "Śpi bardzo, bardzo głęboko.",
			SKELETON = "Może wcale nie spał.",
		},
		BIRDTRAP = "Wciąż się nabierają na te same sztuczki!",
		BIRD_EGG = "Zawsze sobie tłumaczę, że to więzienie dla małego ptaszka.",
		BIRD_EGG_COOKED = "Sadzone najlepsze.",
		BISHOP = "Jestem z niego szczególnie dumny.",
		BLOWDART_FIRE = "Tylko pamiętaj, żeby zrobić wydech.",
		BLOWDART_SLEEP = "Aaa, kotki dwa.",
		BLOWDART_PIPE = "Wspaniała tuba bólu.",
		BLUEAMULET = "Jest cały pokryty szronem.",
		BLUEGEM = "Niebieski symbolizuje lód.",
		BLUEPRINT = "Wiem wszystko na ten temat. Po prostu wyleciało mi z głowy.",
		BELL_BLUEPRINT = "Wiem wszystko na ten temat. Po prostu wyleciało mi z głowy.",
		BLUE_CAP = "Czy coś mogłoby pójść nie tak?",
		BLUE_CAP_COOKED = "Umami!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Te niebieskie do czegoś się nadawały.",
			INGROUND = "Jeszcze nie jest gotowy.",
			PICKED = "Może innym razem?",
		},
		BOARDS = "Grubo ciosane.",
		BOAT = "Nigdzie się nie wybiera.",
		BONESTEW = "Nic nie może się zmarnować.",
		BUGNET = "Do łapania bezbronnych owadów.",
		BUSHHAT = "Znajdzie się tam dla mnie miejsce.",
		BUTTER = "Osełka masełka.",
		BUTTERFLY =
		{
			GENERIC = "Latający kwiatek.",
			HELD = "Szkoda by było, jakby mu ktoś urwał skrzydła.",
		},
		BUTTERFLYMUFFIN = "Dość tego trzepotania.",
		BUTTERFLYWINGS = "Ha, ha, ha! Dorwałem go!",
		CAMPFIRE =
		{
			EMBERS = "Zaraz będzie po ptokach.",
			GENERIC = "Bardzo przyjemne.",
			HIGH = "Charlie przez jakiś czas się nie pokaże.",
			LOW = "Potrzeba paliwa.",
			NORMAL = "Ognista sprawa.",
			OUT = "Skończyło się.",
		},
		CANE = "Jest cała pokryta wyobrażeniami szybkich rzeczy.",
		CARROT = "Nie przepadam za warzywami.",
		CARROT_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		CARROT_PLANTED = "Nie dla mnie takie przyziemne sprawy.",
		CARROT_SEEDS = "Nie dla mnie taka robota.",
		CAVE_FERN = "Chciałbym ją rozdeptać.",
		CHARCOAL = "Nie pozwolę ukraść mojego węgla!",
        CHESSJUNK1 = "Nie bez powodu nigdy ich nie dokończyłem.",
        CHESSJUNK2 = "Wredny drań.",
        CHESSJUNK3 = "Ale paskudna morda.",
		CHESTER = "Mały, denerwujący przybłęda. Jest jednak całkiem użyteczny.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Nie gap się tak.",
			WAITING = "Na co ona czeka?",
		},
		COOKEDMANDRAKE = "Straciła wiele ze swej mocy.",
		COOKEDMEAT = "Trochę mniej śmierdzi oborą.",
		COOKEDMONSTERMEAT = "Zjem to, jeśli będę musiała.",
		COOKEDSMALLMEAT = "Cóż, przynajmniej już się nie rusza.",
		CORN = "Bogata w fruktozę.",
		CORN_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		CORN_SEEDS = "Nie dla mnie taka robota.",
		CROW =
		{
			GENERIC = "Nie wiem, jak się tu dostały.",
			HELD = "Cichaj... Mój śliczny.",
		},
		LICHEN = "Ten grzyb przetrwałby nawet kataklizm.",
		CUTLICHEN = "Suchy, łamliwy, ale krzepiący.",
		CUTGRASS = "Przyziemne sprawy przyrody.",
		CUTREEDS = "Chyba mógłbym zrobić z tego coś przydatnego.",
		CUTSTONE = "To na nich zbudowano cywilizację.",
		DEADLYFEAST = "Pachnie... niebezpiecznie.",
		DEERCLOPS = "Nawet ja boję się tego typa.",
		DEERCLOPS_EYEBALL = "Jeleklopy są strasznie krótkowzroczne.",
		DEPLETED_GRASS =
		{
			GENERIC = "Nic dobrego już z tego nie będzie.",
		},
		DIRTPILE = "Wygląda podejrzanie.",
		DIVININGROD =
		{
			COLD = "Same zakłócenia.",
			GENERIC = "Mogę z jej pomocą znaleźć brakujące części.",
			HOT = "Musi być gdzieś blisko!",
			WARM = "Dobry kierunek.",
			WARMER = "Muszę mieć oczy szeroko otwarte.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Mechanizm startowy.",
			READY = "Muszę włożyć tu różdżkę.",
			UNLOCKED = "Mamy postęp!",
		},
		DIVININGRODSTART = "Portale prowadzą do kolejnej różdżki.",
		DRAGONFLY = "Ognista mucha.",
		LAVASPIT = 
		{
			HOT = "Ogień z pyska.",
			COOL = "Zimna i sucha.",
		},
		DRAGONFRUIT = "Egzotyczny i przepyszny.",
		DRAGONFRUIT_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		DRAGONFRUIT_SEEDS = "Nie dla mnie taka robota.",
		DRAGONPIE = "Po prostu wyborne.",
		DRUMSTICK = "Smakuje trochę porzeczkami.",
		DRUMSTICK_COOKED = "Wciąż smakuje porzeczkami.",
		DUG_BERRYBUSH = "Wyglądam na ogrodnika?",
		DUG_GRASS = "Wyglądam na ogrodnika?",
		DUG_MARSH_BUSH = "Wyglądam na ogrodnika?",
		DUG_SAPLING = "Nie wierzę, że to robię.",
		DURIAN = "Do takich rzeczy trzeba przywyknąć.",
		DURIAN_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		DURIAN_SEEDS = "Nie dla mnie taka robota.",
		EARMUFFSHAT = "Przynajmniej są ciepłe.",
		EGGPLANT = "Kolejna nudna roślina.",
		EGGPLANT_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		EGGPLANT_SEEDS = "Nie dla mnie taka robota.",
		ACORN = 
		{
		    GENERIC = "Ktoś bardziej miłujący przyrodę może byłby w stanie do czegoś ją wykorzystać.",
		    PLANTED = "Hmm, wygląda na to, że powinna być w ziemi.",
		},
		EVERGREEN =
		{
			BURNING = "Ups.",
			BURNT = "Skąpane w ogniu.",
			CHOPPED = "Raczej nie odrośnie.",
			GENERIC = "Niektórzy nazywają je „iglakami”.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Ups.",
			BURNT = "Z prochu powstałeś i w proch się obrócisz.",
			CHOPPED = "Skróciłem jego męki na tym świecie.",
			GENERIC = "Nie wygląda zdrowo.",
		},
		EYEPLANT = "Sługa mięśniaka.",
		FEATHERHAT = "Zwabię je swoim upierzeniem.",
		FEATHER_CROW = "Czerń to kolor snu.",
		FEATHER_ROBIN = "Czerwony to kolor ognia.",
		FEATHER_ROBIN_WINTER = "Szary to kolor cierpienia.",
		FEM_PUPPET = "Lepiej ona niż ja.",
		FIREFLIES =
		{
			GENERIC = "Przepiękne.",
			HELD = "Mógłbym je rozgnieść, gdybym tylko chciał.",
		},
		FIREHOUND = "Dodałem do nich ogniste klejnoty, tak dla żartu.",
		FIREPIT =
		{
			EMBERS = "Powinienem się nim zająć.",
			GENERIC = "Palenisko.",
			HIGH = "Szalejący ogień.",
			LOW = "Zaczyna przygasać.",
			NORMAL = "Gorące.",
			OUT = "Zgasło.",
		},
		FIRESTAFF = "Podstawowe zaklęcie, ale bardzo skuteczne.",
		FISH = "Prosto z mokrych otchłani.",
		FISHINGROD = "Najem się po wsze czasy.",
		FISHSTICKS = "Niewyrafinowane, ale bardzo przyzwoite.",
		FISHTACOS = "Smaczna rybka w chrupiącym kocyku!",
		FISH_MED = "Leżeć.",
		FISH_MED_COOKED = "Wciąż śmierdzi.",
		FISH_COOKED = "Wciąż śmierdzi.",
		FLINT = "Auć! Zaciąłem się w palec!",
		FLOWER = "Czuję niewytłumaczalną potrzebę zadeptania go na śmierć.",
		FLOWERHAT = "Zdecydowanie nie moje klimaty.",
		FLOWER_EVIL = "Podoba mi się ten kwiat.",
		FOLIAGE = "Posiłek dla prostaków.",
		FOOTBALLHAT = "Teraz jestem gotów do starcia.",
		FROG =
		{
			DEAD = "Już jej nie do śmiechu.",
			GENERIC = "Skacze i liże wszystko dokoła.",
			SLEEPING = "Wygląda na zmęczoną.",
		},
		FROGGLEBUNWICH = "Potrafi dać niezłego kopa.",
		FROGLEGS = "Nieźle umięśnione.",
		FROGLEGS_COOKED = "Trochę żylaste.",
		FRUITMEDLEY = "Znakomity dodatek do deski serów.",
		GEARS = "Moi drodzy! Cóż się z wami stało?",
		GHOST = "Pamięta mnie!",
		GOLDENAXE = "Z każdym ciosem robi się ostrzejsza.",
		GOLDENPICKAXE = "To jakaś logika z gier.",
		GOLDENPITCHFORK = "Nie jestem pewien, czy to dobra inwestycja.",
		GOLDENSHOVEL = "Ta łopata warta jest ładną sumkę.",
		GOLDNUGGET = "Kiedyś było to dla kogoś bardzo cenne.",
		GRASS =
		{
			BARREN = "Potrzeba obornika.",
			WITHERED = "Spodziewałbym się, że trawa przetrwa takie temperatury...",
			BURNING = "Ups.",
			GENERIC = "Trawka.",
			PICKED = "Nie ma czego zbierać.",
		},
		GREEN_CAP = "Powinienem go zjeść.",
		GREEN_CAP_COOKED = "Słony!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Zielony grzyb.",
			INGROUND = "Kiedy one wyłażą?",
			PICKED = "Załatwiony.",
		},
		GUNPOWDER = "To mi się podoba.",
		HAMBAT = "Nieelegancka broń na mniej cywilizowane czasy.",
		HAMMER = "Niweczenie pracy innych daje całkiem sporo satysfakcji.",
		HEALINGSALVE = "Trochę jadu i starego popiołu.",
		HEATROCK =
		{	
			FROZEN = "Jest tak zimny, że ledwo mogę go utrzymać.",
			COLD = "Przyjemnie chłodny.",
			GENERIC = "Kieszonkowa grzałka.",
			WARM = "Przyjemnie ciepły.",
			HOT = "Jest tak gorący, że ledwo mogę go utrzymać.",
		},
		HOME = "Wszędzie dobrze, ale tam najlepiej.",
		HOMESIGN = 
		{
			GENERIC = "W tym miejscu w roku 1675... nie wydarzyło się absolutnie nic interesującego.",
			BURNT = "Teraz się nie dowiem, co tu się wydarzyło.",
		},
		HONEY = "Słodki i klejący.",
		HONEYCOMB = "Pełny pszczelich larw.",
		HONEYHAM = "Kruchutka.",
		HONEYNUGGETS = "Wyglądają dziecinnie, ale są przepyszne.",
		HORN = "Wezwijcie bestie!",
		HOUND = "Nie rozpoznają mnie!",
		HOUNDBONE = "Głodne z nich bestie, co?",
		HOUNDMOUND = "Tunel prowadzący do nory ogarów.",
		ICEBOX = "Kawałek zimy w pudełku.",
		INSANITYROCK =
		{
			ACTIVE = "Teraz dostrzegam jego prawdziwą naturę.",
			INACTIVE = "Tak naprawdę w tej płaszczyźnie istnieje tylko w połowie.",
		},
		JAMMYPRESERVES = "Pobrudziłem najlepsze rękawiczki.",
		KABOBS = "Przyrządzony wręcz idealnie!",
		KILLERBEE =
		{
			GENERIC = "O co ten szerszeń się tak wścieka?",
			HELD = "Złapałem tygrysa za ogon.",
		},
		KNIGHT = "Fachowa robota!",
		KOALEFANT_SUMMER = "Daleki kuzyn wołka.",
		KOALEFANT_WINTER = "Ma na sobie zimowe wdzianko.",
		KRAMPUS = "Nie złapiesz mnie!",
		KRAMPUS_SACK = "Jest naprawdę lekki.",
		LEIF = "Odrażające stworzenie!",
		LEIF_SPARSE = "Odrażające stworzenie!",
		LIGHTNING_ROD =
		{
			CHARGED = "Przepływa przez nią strumień energii.",
			GENERIC = "Odrobina ochrony.",
		},
		LITTLE_WALRUS = "Pomiot szatańskiego stworzenia.",
		LIVINGLOG = "Lubię dźwięki, które wydają, jak się palą.",
		LOCKEDWES = "Nie spodobał mi się.",
		LOG =
		{
			BURNING = "Cóż. Było fajnie, ale się skończyło.",
			GENERIC = "Kawałek drewna. Co tu więcej gadać?",
		},
		LUREPLANT = "Złośliwa roślina.",
		LUREPLANTBULB = "Chyba mógłbym ją jakoś wykorzystać.",
		MALE_PUPPET = "Lepiej on niż ja.",
		MANDRAKE =
		{
			DEAD = "W uszach wciąż mi dzwoni.",
			GENERIC = "Może się już zamkniesz?",
			PICKED = "Co za wnerwiający korzeń.",
		},
		MANDRAKESOUP = "Koniec tego darcia papy.",
		MANDRAKE_COOKED = "Już się więcej nie odezwie.",
		MARBLE = "Wytrzymałe to.",
		MARBLEPILLAR = "Zawsze się zastanawiałem, kto to zbudował.",
		MARBLETREE = "Ale dziwne.",
		MARSH_BUSH =
		{
			BURNING = "Powinienem zadawać mu pytania.",
			GENERIC = "Jest nietuzinkowe i wbija szpile. Jak ja!",
			PICKED = "To bolało.",
		},
		MARSH_PLANT = "Zupełnie zwyczajna roślinka.",
		MARSH_TREE =
		{
			BURNING = "I po drzewie.",
			BURNT = "Teraz już się nikomu nie przyda.",
			CHOPPED = "Drzewo 0, Maxwell 1.",
			GENERIC = "Niegrzeczne drzewo.",
		},
		MAXWELL = "Przystojniak!",
		MAXWELLHEAD = "Hej, przystojniaku.",
		MAXWELLLIGHT = "Ach, pamięta mnie.",
		MAXWELLLOCK = "Trzyma mistrza na jego miejscu.",
		MAXWELLTHRONE = "Jest mniej bolesny, niż wygląda. Ale tylko odrobinę.",
		MEAT = "Przywykłem do trochę większych porcji.",
		MEATBALLS = "Wyrazy uznania dla kucharza!",
		MEAT_DRIED = "Moje zęby są już na to za stare.",
		MERM = "Byli tu, gdy się tu znalazłem.",
		MINERHAT = "Świetliki kiedyś umrą z głodu.",
		MONKEY = "Nie mam czasu na wygłupy!",
		MONKEYBARREL = "Ale paskudne mieszkanie.",
		MONSTERLASAGNA = "Włożenie tego do ust nie byłoby rozsądne.",
		MONSTERMEAT = "Odrażające.",
		MONSTERMEAT_DRIED = "Moje zęby są już na to za stare.",
		MOSQUITO =
		{
			GENERIC = "Przeklęci krwiopijcy.",
			HELD = "Mam go!",
		},
		MOSQUITOSACK = "Krwawy pęcherz. Pełen krwi.",
		MOUND =
		{
			DUG = "Tu już byłem.",
			GENERIC = "Cóż się tam kryje?",
		},
		NIGHTLIGHT = "Tworzy piękną poświatę.",
		NIGHTMAREFUEL = "Aaach. Odświeżające.",
		NIGHTSWORD = "Na pohybel draniom!",
		NITRE = "Brakuje jeszcze dwóch składników...",
		ONEMANBAND = "Dobry bit! Zapraszam do tańca.",
		PANDORASCHEST = "To pułapka.",
		PANFLUTE = "Zaniosę pieśń szaleństwa.",
		PAPYRUS = "Czyste płótno.",
		PENGUIN = "Niezgorszy smoking.",
		PERD = "Jest uzależniony od sfermentowanych porzeczek.",
		PEROGIES = "Ja je zrobiłem, więc muszą być dobre.",
		PETALS = "Mam chyba nawyk niszczenia ładnych rzeczy.",
		PETALS_EVIL = "Aż spływa z nich esencja koszmaru.",
		PICKAXE = "Każdy lubi czasem trochę pokopać.",
		PIGGYBACK = "Poniżające.",
		PIGKING = "Ten to się umie ustawić.",
		PIGMAN =
		{
			DEAD = "Nazwę cię Bekon.",
			FOLLOWER = "Jest prymitywny, ale jest mój.",
			GENERIC = "Co za uśliniony głupiec.",
			GUARD = "Zaczynają się organizować.",
			WEREPIG = "Ten trochę zdziczał.",
		},
		PIGSKIN = "Albo on, albo ja.",
		PIGTENT = "Okropieństwo.",
		PIGTORCH = "Świetnie. Teraz maja ogień.",
		PINECONE = 
		{
		    GENERIC = "Ktoś bardziej miłujący przyrodę może byłby w stanie do czegoś ją wykorzystać.",
		    PLANTED = "Hmm, wygląda na to, że powinna być w ziemi.",
		},
		PITCHFORK = "Narzędzie perfekcjonisty.",
		PLANTMEAT = "Marna próba oszukania mniej wprawnego umysłu.",
		PLANTMEAT_COOKED = "Ciepło sprawiło, że nada się do spożycia.",
		PLANT_NORMAL =
		{
			GENERIC = "Zupełnie zwyczajna roślina.",
			GROWING = "Jeszcze rośnie.",
			READY = "Gotowe.",
			WITHERED = "Upał zwyciężył.",
		},
		POMEGRANATE = "Normalnie dałbym go komuś, żeby mi wydłubał nasiona.",
		POMEGRANATE_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		POMEGRANATE_SEEDS = "Nie dla mnie taka robota.",
		POND = "Widzę swoje odbicie.",
		POOP = "Takie są uroki życia śmiertelników.",
		PUMPKIN = "Zawsze uwielbiałem Halloween.",
		PUMPKINCOOKIE = "Wieki minęły, od kiedy jadłem dobre ciastko.",
		PUMPKIN_COOKED = "Przynajmniej odrobinę bardziej wyszukana.",
		PUMPKIN_LANTERN = "Witam pana, panie dynio.",
		PUMPKIN_SEEDS = "Nie dla mnie taka robota.",
		PURPLEAMULET = "Pozwala rozmawiać z krainą cienia.",
		PURPLEGEM = "Fiolet jest źródłem potężnej mocy.",
		RABBIT =
		{
			GENERIC = "Za długo tu jestem.... Wyglądają nawet smacznie.",
			HELD = "Nie martw się, króliczku. Wszystko pod kontrolą.",
		},
		RABBITHOLE = 
		{
			GENERIC = "To jak wejście do nowego świata.",
			SPRING = "Wejście samo się zapadło.",
		},
		RATATOUILLE = "Kto wymyśla te nazwy?",
		RAZOR = "Gdybyż tylko świat miał szyję.",
		REDGEM = "Czerwień zwiastuje ogień.",
		RED_CAP = "Zawsze zapominam, który jak działa.",
		RED_CAP_COOKED = "Trochę gorzki.",
		RED_MUSHROOM =
		{
			GENERIC = "Czerwony grzyb.",
			INGROUND = "Będę musiał po niego wrócić.",
			PICKED = "Zupełnie zużyty.",
		},
		REEDS =
		{
			BURNING = "Ups.",
			GENERIC = "Pamiętasz miła, tę noc w tataraku?",
			PICKED = "Użyteczne rurki.",
		},
        RELIC = 
        {
            GENERIC = "Pozostałości po starożytnej cywilizacji.",
            BROKEN = "Kamienie i skalne odłamki.",
        },
        RUINS_RUBBLE = "Zepsuty relikt.",
        RUBBLE = "Kamienie i skalne odłamki.",
		RESURRECTIONSTONE = "Do dłuższa historia...",
		ROBIN =
		{
			GENERIC = "Kardynały pochodzą z ognistych krain.",
			HELD = "Cisza, ptaku!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Nie poznaję go.",
			HELD = "Cicho bądź.",
		},
		ROBOT_PUPPET = "Lepiej on niż ja.",
		ROCK_LIGHT =
		{
			GENERIC = "Powierzchnia wystygła, tworząc równą skorupę.",
			OUT = "Wygląda niegroźnie.",
			LOW = "Te płomienie zdają się być chłodne.",
			NORMAL = "Gorące.",
		},
		ROCK = "Kamień.",
		ROCKS = "Hmm. I co mam z nimi zrobić?",
        ROOK = "Kawałek zamku. Mógłbym w nim zamieszkać.",
		ROPE = "Spodziewałbym się, że będzie miała więcej zastosowań.",
		ROTTENEGG = "Obrzydliwe. Po co ja to noszę?",
		SANITYROCK =
		{
			ACTIVE = "Teraz dostrzegam jego prawdziwą naturę.",
			INACTIVE = "Są dwa sposoby patrzenia na tą przeszkodę.",
		},
		SAPLING =
		{
			BURNING = "Ups.",
			WITHERED = "Nic nie przetrwa w tym upale.",
			GENERIC = "Miękka, drewniana łodyżka.",
			PICKED = "Odrośnie",
		},
		SEEDS = "Same się pewnie nie zasieją.",
		SEEDS_COOKED = "Wyprażyłem z nich ostatnie resztki życia.",
		SEWING_KIT = "Zaprawdę szlachetna czynność.",
		SHOVEL = "To jakaś zaawansowana technologia.",
		SILK = "Pomimo parszywego pochodzenia może posłużyć do stworzenia naprawdę przyzwoitych ubrań.",
		SKELETON = "Ha! Pamiętam go.",
		SKELETON_PLAYER = "Mistrz zostaje uczniem.",
		SKULLCHEST = "Rewelacyjna skrzynia.",
		SMALLBIRD =
		{
			GENERIC = "Co? Czego chcesz?",
			HUNGRY = "Chcesz jeść?",
			STARVING = "Jest strasznie głodny!",
		},
		SMALLMEAT = "Ledwo wystarczy na jednego gryza.",
		SMALLMEAT_DRIED = "Moje zęby są już na to za stare.",
		SPEAR = "Dzida składa się z przeddzidzia dzidy, śróddzidzia dzidy i zadzidzia dzidy. Przeddzidzie dzidy składa się z przeddzidzia przeddzidzia dzidy, śróddzidzia przeddzidzia dzidy i zadzidzia przeddzidzia dzidy. I tak dalej.",
		SPIDER =
		{
			DEAD = "Pac.",
			GENERIC = "W większości składa się z układu trawiennego.",
			SLEEPING = "Ciii! Obudzi się głodny.",
		},
		SPIDERDEN = "Dobrze im tutaj.",
		SPIDEREGGSACK = "Ale mięciutkie.",
		SPIDERGLAND = "Paskudztwo.",
		SPIDERHAT = "Pająki mają tak łatwo formowalną wolę.",
		SPIDERQUEEN = "Może po prostu zejdę jej z drogi.",
		SPIDER_WARRIOR =
		{
			DEAD = "Pac.",
			GENERIC = "Wyspecjalizowany podgatunek.",
			SLEEPING = "Nie chcę go obudzić.",
		},
		SPOILED_FOOD = "Kiedyś było jedzeniem, ale się sfilcowało.",
		STATUEHARP = "Jedno z moich mniej udanych dzieł.",
		STATUEMAXWELL = "Doskonały posąg.",
		STINGER = "Aż ocieka toksynami.",
		STEELWOOL = "Można by nią coś wyczyścić.",
		STRAWHAT = "Kapelusz godny wieśniaka.",
		STUFFEDEGGPLANT = "Posiłek godny króla... A przynajmniej kogoś, kto ma tron.",
		SUNKBOAT = "Jak nie korzystać z łodzi.",
		SWEATERVEST = "Garnitur to to nie jest, ale daje radę.",
		TAFFY = "Sto procentu cukru.",
		TALLBIRD = "Nie udał mi się ten eksperyment.",
		TALLBIRDEGG = "Przez nie duptaki są bardzo terytorialne.",
		TALLBIRDEGG_COOKED = "Smakuje zrujnowanymi marzeniami.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Zaczyna się wychładzać.",
			GENERIC = "Coś się tu rusza.",
			HOT = "Dość ciepło?",
			LONG = "Trochę to potrwa.",
			SHORT = "Już za chwileczkę...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Cóż... kuszące.",
			PICKED = "Uplecione z brudnych kłaków wołka.",
		},
		TEENBIRD =
		{
			GENERIC = "Wyrośnięty już nie jest taki uroczy.",
			HUNGRY = "Potrafią nieźle zjeść.",
			STARVING = "Głodna bestia to niebezpieczna bestia.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Działa!",
			GENERIC = "Moja piękna maszyna w kawałkach!",
			LOCKED = "Teraz trzeba go włączyć.",
			PARTIAL = "Wciąż czegoś brakuje.",
		},
		TELEPORTATO_BOX = "Pudełko pełne smutku i rozpaczy.",
		TELEPORTATO_CRANK = "Można by tym coś nakręcić.",
		TELEPORTATO_POTATO = "Zębatki są tu tak małe, że zakrzywiają powłokę rzeczywistości.",
		TELEPORTATO_RING = "Pas ochronny pola kwantowego.",
		TELESTAFF = "Magia potrafi dokonać wielkich rzeczy, jeśli się ją odpowiednio ukierunkuje.",
		TENTACLE = "Dobrze, że reszta jest wciąż pod ziemią.",
		TENTACLESPIKE = "Ugh. Odrażające.",
		TENTACLESPOTS = "Tak się rozmnażają.",
		TENTACLE_PILLAR = "Ciekawe, jak głęboko sięga.",
		TENTACLE_GARDEN = "Dziwny twór.",
        TENTACLE_PILLAR_ARM = "Młode?",
		TOPHAT = "Fachowa robota.",
		TORCH = "Charlie będzie trzymać się z dala.",
		TRAP = "Tylko najgłupsze zwierzaki dadzą się na to nabrać.",
		TRAP_TEETH = "Potrafi zaboleć.",
		TRAP_TEETH_MAXWELL = "Musiałem mieć jakiś powód, żeby to tu ustawić.",
		TREASURECHEST_TRAP = "Hmm. Wygląda podejrzanie.",
		TREECLUMP = "Tędy nie przejdę.",
		TRINKET_1 = "Musiały się rozgrzać do niewyobrażalnej temperatury.",
		TRINKET_10 = "Lepiej pamiętać o myciu zębów.",
		TRINKET_11 = "Nie słucham cię.",
		TRINKET_12 = "Nie dotknę tego bez kilku par rękawiczek.",
		TRINKET_2 = "Kiedyś było to dla kogoś bardzo cenne.",
		TRINKET_3 = "Pomieszanie z poplątaniem. Metafora ludzkiego życia.",
		TRINKET_4 = "Nie patrz tak na mnie!",
		TRINKET_5 = "Zabawka dla małego geniusza.",
		TRINKET_6 = "Bezużyteczne stare kable.",
		TRINKET_7 = "Wolałbym, żeby mnie z tym nie widziano.",
		TRINKET_8 = "Wolałbym zegarek kieszonkowy na łańcuszku.",
		TRINKET_9 = "Mój garnitur nie zasługuje na takie okropieństwo.",
		TRUNKVEST_SUMMER = "Bardziej nadaje się na jesień.",
		TRUNKVEST_WINTER = "Ciężko ubrać się modnie zimą.",
		TRUNK_COOKED = "Przynajmniej śluz się wypalił.",
		TRUNK_SUMMER = "Pełna letniego śluzu.",
		TRUNK_WINTER = "Trąba rozszerza się zimą, żeby pomieścić więcej śluzu.",

		TURF_CARPETFLOOR = "Wysokiej jakości długowłosy dywan!",
		TURF_CHECKERFLOOR = "Oto moje naturalne środowisko.",
		TURF_DIRT = "Dużo kurzu.",
		TURF_FOREST = "Śmierdzi błotem.",
		TURF_GRASS = "Drapie.",
		TURF_MARSH = "Cała aż ocieka wodą.",
		TURF_ROAD = "Ta przynajmniej się do czegoś przyda.",
		TURF_ROCKY = "Trochę twarda.",
		TURF_SAVANNA = "Syf i brud.",
		TURF_WOODFLOOR = "Wolę lite drewno.",

		TURF_CAVE="Gleba.",
		TURF_FUNGUS="Gleba.",
		TURF_SINKHOLE="Gleba.",
		TURF_UNDERROCK="Gleba.",
		TURF_MUD="Gleba.",

		TURKEYDINNER = "Jak świątecznie.",
		TWIGS = "Pospolite, ale przydatne.",
		UMBRELLA = "Trochę pokrzywiona!",
		WAFFLES = "Doskonałe na rano. Albo wieczór.",
		WALL_HAY_ITEM = "Kieszonkowe kawałki ściany. Mhm.",
		WALL_STONE = "Powinno powstrzymać hołotę.",
		WALL_STONE_ITEM = "Kieszonkowe kawałki ściany. Mhm.",
		WALL_WOOD_ITEM = "Kieszonkowe kawałki ściany. Mhm.",
		WALL_RUINS = "Pradawny mur.",
		WALL_RUINS_ITEM = "Kieszonkowe kawałki ściany. Mhm.",
		WALRUS = "Nie poznajesz mnie?",
		WALRUSHAT = "Wyprodukowano w Szkocji.",
		WALRUS_CAMP =
		{
			EMPTY = "Lepiej nie zostawać tu na zimę.",
			GENERIC = "Morski stwór na pewno jest gdzieś niedaleko.",
		},
		WALRUS_TUSK = "Znajdę dla niego lepsze zastosowanie.",
		WASPHIVE = "Wygląda niebezpiecznie.",
		WETGOOP = "Nie moje klimaty...",
		WINTERHAT = "Rozczarowująco rustykalna.",
		WORMHOLE =
		{
			GENERIC = "Druga strona jest jeszcze gorsza.",
			OPEN = "Śmierdzi jeszcze gorzej, niż wygląda.",
		},
		WORMHOLE_LIMITED = "Wygląda na chorą.",
		ACCOMPLISHMENT_SHRINE = "Nawet ONI nie zdołaliby zbudować czegoś tak diabelskiego.",

		AERODYNAMICHAT = "Całkiem szykowny, można by nawet powiedzieć, że elegancki.",
		ANTIVENOM = "Lekarstwo na to, co ci dolega.",
		ARMORCACTUS = "Nic tak nie mówi „trzymaj się z daleka”, jak to.",
		ARMORLIMESTONE = "Sprawia, że poruszam się trochę... ospale.",
		ARMOROBSIDIAN = "Uformowałem płomień według swej własnej woli.",
		ARMORSEASHELL = "Może nie najmocniejszy, ale zakrywa moje najczulsze punkty.",
		ARMOR_LIFEJACKET = "Niestety moje wysublimowane poczucie estetyki musi ustąpić zdrowemu rozsądkowi.",
		ARMOR_SNAKESKIN = "Jest klasa!",
		ARMOR_WINDBREAKER = "Ech.",
		ARMOUREDBOAT = "Ta łódź nie będzie się mazać przy byle uderzeniu.",
		BABYOX = "Nie licz na specjalne traktowanie, bestio.",
		BALLPHIN = "Są dużo zręczniejsze, niż się wydaje.",
		BAMBOO = "Mam dla niego kilka pomysłów.",
		BAMBOOTREE =
		{
			BURNT = "Już nie wróci.",
			CHOPPED = "Potrzebuje trochę czasu, by odrosnąć.",
			GENERIC = "Przebije wszystko, co stanie mu na drodze.",
		},
		BERMUDATRIANGLE = "Wzywa mnie do kąpieli.",
		BIGFISHINGROD = "Może teraz bardziej mi się poszczęści z pływającym mięskiem.",
		BIOLUMINESCENCE = "Zjawisko wręcz nie z tego świata.",
		BLOWDART_FLUP = "Całkiem imponujące ustrojstwo.",
		BLOWDART_POISON = "Obróciłem jad tego świata przeciwko niemu samemu.",
		BLUBBER = "Chyba mógłbym to... zjeść...",
		BLUBBERSUIT = "Cóż za poniżenie.",
		BOATCANNON = "Już najwyższy czas, żeby sprawić sobie coś takiego.",
		BOATREPAIRKIT = "Odwlecze nieunikniony rozpad mojego okrętu.",
		BOAT_LANTERN = "Oświetla okolicę niezwykłym blaskiem.",
		BOAT_TORCH = "Żeglowanie nocą wydaje się dość niebezpieczne, ale z nią powinno być trochę lepiej.",
		BOTTLELANTERN = "W służbie odnajdują sens swego życia.",
		BRAINJELLYHAT = "Czuję inspirację.",
		BUOY = "Unosi się bez problemu.",
		BURIEDTREASURE = "Ach, cóż to takiego?",
		BUSH_VINE =
		{
			BURNT = "Spotkał go smutny koniec.",
			CHOPPED = "Całkowicie rozgrabiony... przynajmniej na razie.",
			GENERIC = "Przejęły już chyba całą wyspę.",
		},
		CAPTAINHAT = "Budzi we mnie duszę dowódcy!",
		CARGOBOAT = "Ach, ileż miejsca!",
		CHIMINEA = "Bezpieczne schronienie dla mojego uczciwie zdobytego ognia.",
		CLOTHSAIL = "Wspomoże mnie w podróży.",
		COCONADE =
		{
			BURNING = "Może lepiej się schować.",
			GENERIC = "Widzę śmierć na horyzoncie.",
		},
		COCONUT = 
		{
		    GENERIC = "Mógłby poważnie uszkodzić komuś czerep.",
		    PLANTED = "Już nikogo nie skrzywdzi.",
		},
		COCONUT_COOKED = "Na razie wystarczy.",
		COCONUT_HALVED = "Zamieniłem jeden kokos w dwa! Magia!",
		COFFEE = "Nie mogę się już doczekać.",
		COFFEEBEANS = "Dziwnie wyglądają w takim kolorze.",
		COFFEEBEANS_COOKED = "Lepsze takie niż surowe, ale czy jest jeszcze jakiś inny sposób, żeby je przyrządzić?",
		COFFEEBOT = "Od teraz będzie odpowiadał za kawę.",
		COFFEEBUSH =
		{
			BARREN = "Pusto.",
			GENERIC = "Ziarna pyszności.",
			PICKED = "Wszystkie już zebrałem.",
			WITHERED = "Dopadła go straszliwa moc zepsucia.",
		},
		COMPASS =
		{
			GENERIC="Hmm. Nie mogę nic odczytać.",
			N = "Północ",
			S = "Południe",
			E = "Wschód",
			W = "Zachód",
			NE = "Północny wschód",
			SE = "Południowy wschód",
			NW = "Północny zachód",
			SW = "Południowy zachód",
		},
		CORAL = "Całkiem uroczy.",
		CORALREEF = "Pewnie mogłaby być domem dla wielu żywych organizmów.",
		CORAL_BRAIN = "Teraz będę mógł posiąść moc jego umysłu.",
		CORAL_BRAIN_ROCK = "Ciekawe, o czym rozmyśla.",
		CRAB =
		{
			GENERIC = "Jadalny skorupiak.",
			HIDDEN = "Krablik się chowa.",
		},
		CRABHOLE = "Nie może ukrywać się wiecznie.",
		CRATE = "Może dałbym radę jakoś ją otworzyć.",
		CUTLASS = "Broń dżentelmenów.",
		DEAD_SWORDFISH = "Powinien się chyba zapisać na lekcje szermierki.",
		DEPLETED_BAMBOOTREE = "Nie ma.",
		DEPLETED_BUSH_VINE = "Skończyło się.",
		DEPLETED_GRASS_WATER = "To wszystko, więcej nie było.",
		DEVTOOL = "Ciekawe...",
		DEVTOOL_NODEV = "Obawiam się, że go nie pojmę.",
		DOUBLE_UMBRELLAHAT = "Wygląda cokolwiek debilnie.",
		DOYDOY = "To marne stworzenie nie ma szans na przetrwanie.",
		DOYDOYBABY = "Będzie ich więcej.",
		DOYDOYEGG = "Hmm, zachować zagrożony gatunek, czy zrobić sobie przekąskę?",
		DOYDOYEGG_COOKED = "Nie ma to jak lekka przekąska.",
		DOYDOYEGG_CRACKED = "Ups!",
		DOYDOYFEATHER = "Wyglądałoby świetnie przy niedzielnym kapeluszu.",
		DOYDOYNEST = "Ciekawe, jakie mają szanse...",
		DRAGOON = "Wiesz, kim jestem?",
		DRAGOONDEN = "Nie widzę powodu, żeby im przeszkadzać.",
		DRAGOONEGG = "Promieniuje przytłaczającym ciepłem.",
		DRAGOONHEART = "Serce i tak jest jedynie źródłem cierpienia.",
		DRAGOONSPIT = "Co za brak wychowania.",
		DUBLOON = "Dźwięk, który wydają, obijając się o siebie, jest niezwykle satysfakcjonujący.",
		DUG_BAMBOOTREE = "Muszę znaleźć dla niego jakieś miejsce.",
		DUG_BUSH_VINE = "Muszę znaleźć dla niego odpowiednie miejsce.",
		DUG_COFFEEBUSH = "Warto go ponownie zasadzić.",
		DUG_ELEPHANTCACTUS = "Lepiej z nim nie biegać.",
		EARRING = "Świetnie bym w nim wyglądał. Gdybym miał przekłute ucho.",
		ELEPHANTCACTUS = "Nie będzie mi tu strzelać, kaktus jeden.",
		ELEPHANTCACTUS_ACTIVE = "Kryć się!",
		ELEPHANTCACTUS_STUMP = "Do widzenia.",
		FABRIC = "Zamieniłem bambus w coś przydatnego.",
		FEATHERSAIL = "Pewnie lepsze to niż wiosłowanie.",
		FISHINHOLE = "Dużo lepiej czułyby się w moim brzuchu",
		FISH_RAW = "Przydałoby się trochę ognia.",
		FISH_RAW_SMALL = "Naprawdę tak nisko upadłem?",
		FISH_RAW_SMALL_COOKED = "No to siups.",
		FLAMEGEYSER = "Całkiem imponujące widowisko.",
		FLOTSAM = "Może dałoby się to jakoś przyciągnąć.",
		FLUP = "Kto wymyślił coś takiego...",
		FRESHFRUITCREPES = "Zasługują na to, żeby zjeść je sztućcami. Niestety mam tylko ręce.",
		FROG_POISON = "Trzeba nauczyć ją manier.",
		GASHAT = "Powstrzymuje przykre zapachy.",
		GOLDENMACHETE = "Zawsze pragnąłem siec wszystko jak szlachcic.",
		GRASS_WATER = "Częściowo zanurzona.",
		HAIL_ICE = "Trochę zimno.",
		HOUNDFIRE = "Kąsający płomień!",
		ICEMAKER =
		{
			HIGH = "Ciężko pracuje, by przygotować mi lód.",
			LOW = "Trzeba ją chyba zasilić.",
			NORMAL = "Chyba robi robotę.",
			OUT = "Nie robi roboty.",
			VERYLOW = "Ledwie stoi na nogach.",
		},
		IRONWIND = "Całe szczęście! Jestem umówiony!",
		JELLYFISH = "Cóż za osobliwe stworzenie.",
		JELLYFISH_COOKED = "Chyba da radę...",
		JELLYFISH_DEAD = "Wolę, jak jest martwa.",
		JELLYFISH_PLANTED = "Wstrząsające stworzenie.",
		JELLYJERKY = "W sumie nie mam nic przeciwko.",
		JUNGLETREE =
		{
			BURNING = "Koniec jego przygody na tym świecie.",
			BURNT = "W innym życiu. Być może.",
			CHOPPED = "Wykorzystałem je do swoich celów.",
			GENERIC = "Chyba chce, żeby je ściąć.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Teoretycznie mógłbym je gdzieś rozsiać.",
            PLANTED = "Świetnie. Miałem rację.",
        },
		KNIGHTBOAT = "Ukorz się, głupcze!",
		KRAKEN = "Padniesz przede mną na macki.",
		KRAKENCHEST = "Czas na nagrodę.",
		KRAKEN_TENTACLE = "Jak śmiesz mnie dotykać?",
		LAVAPOOL = "Wyjątkowo przypieczone.",
		LIMESTONE = "Może śmierć tej morskiej istoty nie pójdzie na marne.",
		LIMPETROCK =
		{
			GENERIC = "W razie kryzysu można je zjeść.",
			PICKED = "Został już tylko zwykły kamień.",
		},
		LIMPETS = "Oślizgłe, ale w ostateczności jadalne.",
		LIMPETS_COOKED = "Przysmak? Naprawdę?",
		LIVINGJUNGLETREE = "Wszystko w jak najlepszym porządku.",
		TREEGUARD = "Trzeba powstrzymać ten nonsens.",
		LOBSTER = "Z tego będzie porządny posiłek.",
		LOBSTERHOLE = "Pokażcie się, pyszności.",
		LOBSTER_DEAD = "Znakomicie.",
		LOBSTER_DEAD_COOKED = "Zapomniałem chustki pod brodę.",
		LOGRAFT = "Powinni ustalić jakieś prawo, które tego zabroni.",
		LUGGAGECHEST = "Całkiem szykowna waliza, musze powiedzieć.",
		MACHETE = "Zawsze chciałem mieć coś takiego.",
		MAGIC_SEAL = "Wyczuwam wewnątrz potężną moc.",
		MAGMAROCK = "Cóż. Kamień...",
		MAGMAROCK_FULL = "Cóż. Kamień...",
		MAGMAROCK_GOLD = "Prawdziwie luksusowa skała.",
		MAGMAROCK_GOLD_FULL = "Prawdziwie luksusowa skała.",
		MANGROVETREE = "Drzewo jak każde inne. Tyle że mokre.",
		MANGROVETREE_BURNT = "Nie wytrzymał temperatury.",
		MARSH_PLANT_TROPICAL = "Na niewiele mi się przyda.",
		MERMFISHER = "Nie mam nic do niego.",
		MERMHOUSE_FISHER = "Każdy musi gdzieś mieszkać...",
		MESSAGEBOTTLE = "Co to za prymitywne sposób komunikacji?",
		MESSAGEBOTTLEEMPTY = "Gdybym miał trochę czasu, mógłbym zbudować w środku okręt.",
		MONKEYBALL = "I co mam z tym niby zrobić?",
		MONSTERTARTARE = "Niezbyt zachęcające.",
		MOSQUITOSACK_YELLOW = "Zabieram tę krew z powrotem. Dziękuję bardzo.",
		MOSQUITO_POISON = "Wolałbym jednak uniknąć ugryzienia.",
		MUSSEL = "W niektórych miejscach uchodzą za przysmak.",
		MUSSELBOUILLABAISE = "Nie mogę się doczekać dania głównego.",
		MUSSEL_COOKED = "Teraz już nie wygląda, jakby miał mi zaszkodzić.",
		MUSSEL_FARM =
		{
			GENERIC = "Całkiem wygodne skupisko jedzenia.",
			STICKPLANTED = "Są zupełnie nieświadome nadciągającej śmierci.",
		},
		MUSSEL_STICK = "Małże nie będą w stanie się oprzeć.",
		MYSTERYMEAT = "Raczej obrzydliwe.",
		NEEDLESPEAR = "Niespotykanie ostra.",
		OBSIDIAN = "Fantastyczny kolor.",
		OBSIDIANAXE = "Wydaje się, że najlepiej działa zapalona.",
		OBSIDIANCOCONADE = "To już chyba lekka przesada.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Powinienem się nim zająć.",
			GENERIC = "Po to powstał ten kamień.",
			HIGH = "Szalejący ogień.",
			LOW = "Zaczyna przygasać.",
			NORMAL = "Płonie jak należy.",
			OUT = "Zgasło.",
		},
		OBSIDIANMACHETE = "Wygląda dość niebezpiecznie, jak na narzędzie rolnicze.",
		OBSIDIANSPEARGUN = "Wyrzutnia płomieni. Podoba mi się.",
		OBSIDIAN_WORKBENCH = "Ten warsztat budzi we mnie twórcze odruchy...",
		OCTOPUSCHEST = "Wygląda... na przegniłą.",
		OCTOPUSKING = "Może mógłbym jakoś wykorzystać jego hojność.",
		OX = "Śmierdzący i bezbrzeżnie głupi.",
		OXHAT = "Czasami zastosowanie praktyczne musi przeważyć nad formą.",
		OX_FLUTE = "O rany. Trochę czasu minęło, od kiedy ostatnio grałem.",
		OX_HORN = "Bestia nie miała szans.",
		PACKIM = "Nadrabia za swą denerwująca aparycję przydatnością i ochotą do służby.",
		PACKIM_FISHBONE = "Raczej to sobie zostawię.",
		PALMLEAF = "Teraz potrzebuje już tylko sług, którzy wachlowaliby moją wspaniałą osobę.",
		PALMLEAF_HUT = "Uff.",
		PALMTREE =
		{
			BURNING = "Koniec jego przygody na tym świecie.",
			BURNT = "W innym życiu. Być może.",
			CHOPPED = "Wykorzystałem je do swoich celów.",
			GENERIC = "Cóż za luksus.",
		},
		PARROT = "Hmm. Ładne kolory.",
		PARROT_PIRATE = "Musi dać się ją jakoś zamknąć.",
		PEACOCK = "Wie, jak się pokazać.",
		PEG_LEG = "Można kogoś nią zdzielić.",
		PIKE_SKULL = "Auć.",
		PIRATEGHOST = "Nie zamierzam podzielić twego losu!",
		PIRATEHAT = "To ma być fajne?",
		PIRATEPACK = "Chyba powinna być w sam raz.",
		PIRATIHATITATOR =
		{
			BURNT = "Wiedza poszła z dymem.",
			GENERIC = "Fascynujące urządzenie.",
		},
		POISONHOLE = "Stąd widzę ją doskonale... nie ma sensu podchodzić bliżej.",
		PORTAL_SHIPWRECKED = "Bezużyteczny śmieć!",
		PRIMEAPE = "To żałosne stworzenie posiada zaledwie szczątkową inteligencję.",
		PRIMEAPEBARREL = "Nie zamierzam się do tego zbliżać.",
		RAFT = "Za słaba jak na mój gust.",
		RAWLING = "Świetnie. Gadająca wypchana piłka.",
		REDBARREL = "Aż kipi od potencjału...",
		ROCK_CHARCOAL = "Nie sposób nie zachwycić się tą naturalną formacją.",
		ROCK_OBSIDIAN = "Nie zamierzam kłaniać się mym narzędziom.",
		ROWBOAT = "Napędzana ręcznie. Pech.",
		SAIL = "Teraz pływanie będzie jak bajka.",
		SAIL_STICK = "Kijek. Chyba do żeglowania.",
		SAND = "Kamienie w proszku.",
		SANDBAG = "Worek kamyków, który trzyma wodę na dystans.",
		SANDBAGSMALL = "Worek kamyków, który trzyma wodę na dystans.",
		SANDBAGSMALL_ITEM = "Worek kamyków. Tak łatwiej je przenieść.",
		SANDBAG_ITEM = "Worek kamyków. Tak łatwiej je przenieść.",
		SANDHILL = "Mała kupka żółtego piasku.",
		SAND_CASTLE =
		{
			GENERIC = "Zupełnie mnie to nie bawi. Serio. No co?",
			SAND = "Piasek dekoracyjny.",
		},
		SEAGULL = "Jest głośna i wnerwiająca.",
		SEAGULL_WATER = "Latający morski szczur.",
		SEASACK = "Nie wzmocni mnie, ale przynajmniej będę miał więcej kieszeni.",
		SEASHELL = "Jak ją trzymam, czuję się jak turysta.",
		SEASHELL_BEACHED = "Trochę zbyt kiczowate, jak na mój gust.",
		SEATRAP = "Ciekawość kiedyś cię zabije.",
		SEAWEED = "Morskie śmieci.",
		SEAWEED_COOKED = "Jak to zjem, to chyba zwymiotuję.",
		SEAWEED_DRIED = "Ugh.",
		SEAWEED_PLANTED = "Podoba im się tutaj.",
		SHADOWSKITTISH_WATER = "O rany.",
		SHARKITTEN = "Urocze monstrum.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Porusza się, jak wspominam o smakołykach.",
			INACTIVE = "Zwykła kupa piachu.",
		},
		SHARK_FIN = "Trofeum z udanych łowów.",
		SHARK_GILLS = "Chyba warto je sobie zostawić.",
		SHARK_TEETHHAT = "Szanuję taki dobór garderoby.",
		SHARX = "Pytanie nie brzmi, czy go pokonam. Pytanie brzmi – kiedy?",
		SHIPWRECKED_ENTRANCE = "Mam nadzieję, że jesteś gotów.",
		SHIPWRECKED_EXIT = "Żegnajcie!",
		SLOTMACHINE = "Mam tendencję do kuszenia losu.",
		SLURPERPELT = "Znakomita skóra.",
		SNAKE = "Okrutny, lecz elegancki.",
		SNAKEDEN =
		{
			BURNT = "Spotkał go smutny koniec.",
			CHOPPED = "Całkowicie rozgrabiony... przynajmniej na razie.",
			GENERIC = "Przejęły już chyba całą wyspę.",
		},
		SNAKEOIL = "Pewnie można by na tym zarobić.",
		SNAKESKIN = "Znakomita faktura.",
		SNAKESKINHAT = "W sumie całkiem wytworna rzecz.",
		SNAKESKINSAIL = "Ułatwia podróż.",
		SNAKE_FIRE = "Aż się gotuje ze złości.",
		SNAKE_POISON = "Lepiej omijajmy się z daleka.",
		SOLOFISH = "Pachnie mokrym psem.",
		SPEARGUN = "Miotacz pocisków. Może się przydać.",
		SPEARGUN_POISON = "Zadbałem o dodatkowe przyłożenie.",
		SPEAR_LAUNCHER = "Miotacz pocisków. Może się przydać.",
		SPEAR_OBSIDIAN = "Zadbałem o dodatkowe ogniste przyłożenie.",
		SPEAR_POISON = "Zadbałem o dodatkowe przyłożenie.",
		SPOILED_FISH = "Chyba lepiej się tego pozbyć.",
		STUNGRAY = "Śmierdzi niemożliwie.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Jest pilnie strzeżona.",
			GENERIC = "Więcej nie popłynie.",
		},
		SUNKEN_BOAT_BURNT = "Wszystko kiedyś przemija.",
		SUNKEN_BOAT_TRINKET_1 = "Jest dokładnie tym, na co wygląda... A na co wygląda?",
		SUNKEN_BOAT_TRINKET_2 = "Jakby drwiła sobie z mojej sytuacji.",
		SUNKEN_BOAT_TRINKET_3 = "Chyba nie ma żadnej konkretnej funkcji.",
		SUNKEN_BOAT_TRINKET_4 = "Mały, zaawansowany gadżet.",
		SUNKEN_BOAT_TRINKET_5 = "Był paskudny jeszcze zanim nabrał wody.",
		SUPERTELESCOPE = "Może teraz dowiem się, co mnie otacza.",
		SWEETPOTATOSOUFFLE = "Wygląda nawet na zjadliwy.",
		SWEET_POTATO = "Gotowe do pieczenia.",
		SWEET_POTATO_COOKED = "Sklepowe nie smakują tak samo.",
		SWEET_POTATO_PLANTED = "Jadłem gorsze rzeczy. Znacznie gorsze.",
		SWEET_POTATO_SEEDS = "Może coś wyrośnie, jak je wrzucę do ziemi.",
		SWIMMINGHORROR = "Mam was już dość, demonie.",
		SWORDFISH = "Ach, partner do ćwiczeń!",
		TELEPORTATO_SW_BASE = "Szykuje się coś naprawdę ciekawego.",
		TELEPORTATO_SW_BOX = "Kolejny element układanki.",
		TELEPORTATO_SW_CRANK = "Znakomicie. Już niewiele zostało.",
		TELEPORTATO_SW_POTATO = "Przyznaję, że to trochę głupkowate.",
		TELEPORTATO_SW_RING = "Ach, kolejny element.",
		TELESCOPE = "Może teraz dowiem się, co mnie otacza.",
		THATCHPACK = "Niewiele, ale każdy kawałek wolnego miejsca jest lepszy niż nic.",
		TIDALPOOL = "Dużo głębszy, niż się wydaje.",
		TIDAL_PLANT = "Trochę licha.",
		TIGEREYE = "Dżentelmen nie dotyka takich rzeczy bez rękawiczek.",
		TIGERSHARK = "Nazwa mówi wszytko.",
		TOUCAN = "Kolorowy szkodnik.",
		TRAWLNET = "Nie widzę przeciwwskazań dla tego rozwiązania.",
		TRAWLNETDROPPED =
		{
			GENERIC = "Widzę już oczami wyobraźni te wszystkie pyszne dania.",
			SOON = "W głębiny...",
			SOONISH = "Powoli opada na dno.",
		},
		TRIDENT = "Widelec dla oceanicznych królów.",
		TRINKET_13 = "Miła odskocznia od wody morskiej.",
		TRINKET_14 = "To chyba nie najlepszy omen.",
		TRINKET_15 = "Ma tylko cztery struny.",
		TRINKET_16 = "Literki i cyferki. Jakieś kod?",
		TRINKET_17 = "Był paskudny jeszcze zanim nabrał wody.",
		TRINKET_18 = "Trochę kleju i będzie w sam raz na stół.",
		TRINKET_19 = "Ani czerwona, ani niebieska.",
		TRINKET_20 = "Jest dokładnie tym, na co wygląda... A na co wygląda?",
		TRINKET_21 = "Może być fajna w gorącej kąpieli...",
		TRINKET_22 = "Jakby żywcem wyjęta z pchlego targu w jakiejś nadmorskiej miejscowości.",
		TRINKET_23 = "Z nikim się już nie komunikuje.",
		TROPICAL_FISH = "Powinna trafić na rożen.",
		TUNACAN = "Zapewne w środku znajdę tuńczyka.",
		TURBINE_BLADES = "Mistrzowski projekt i wykonanie.",
		TURF_ASH = "To chyba jakaś ziemia.",
		TURF_BEACH = "To chyba jakaś ziemia.",
		TURF_DESERTDIRT = "To chyba jakaś ziemia.",
		TURF_FUNGUS_GREEN = "To chyba jakaś ziemia.",
		TURF_FUNGUS_RED = "To chyba jakaś ziemia.",
		TURF_JUNGLE = "To chyba jakaś ziemia.",
		TURF_MAGMAFIELD = "To chyba jakaś ziemia.",
		TURF_MEADOW = "To chyba jakaś ziemia.",
		TURF_SNAKESKINFLOOR = "To chyba jakaś ziemia.",
		TURF_SWAMP = "To chyba jakaś ziemia.",
		TURF_TIDALMARSH = "To chyba jakaś ziemia.",
		TURF_VOLCANO = "To chyba jakaś ziemia.",
		TWISTER = "Wolałbym, żeby mnie nie wciągnęło.",
		TWISTER_SEAL = "Jest całkiem... eee... urocze?",
		VENOMGLAND = "Czyżby lekarstwo?",
		VINE = "Poskręcane i powykrzywiane.",
		VOLCANO = "Szanuję jego potęgę.",
		VOLCANOSTAFF = "Czuje się w moich rękach jak w domu.",
		VOLCANO_ALTAR =
		{
			GENERIC = "To chyba jakieś miejsce do składania ofiar.",
			OPEN = "Czy odważę się zadzierać z kolejnymi siłami poza moją kontrolą?",
		},
		VOLCANO_ALTAR_BROKEN = "Wielka szkoda.",
		VOLCANO_ALTAR_TOWER = "Fascynująca budowla.",
		VOLCANO_EXIT = "To ja już pójdę.",
		VOLCANO_SHRUB = "Gdybym znał pojęcie współczucia, obdarzyłbym nim to drzewko.",
		WALLYINTRO_DEBRIS = "Co to za nonsens?",
		WALL_LIMESTONE = "Sporo wytrzyma.",
		WALL_LIMESTONE_ITEM = "Od czego powinno się zacząć budowę fortecy?",
		WATERMELON_SEEDS = "Chyba powinienem je gdzieś zasiać.",
		WATERYGRAVE = "Nie wszystkim dane jest odnaleźć spokojne miejsce spoczynku.",
		WHALE_BLUE = "Poddaj się.",
		WHALE_BUBBLES = "Zdradziłeś się, kolego!",
		WHALE_CARCASS_BLUE = "Rozmiar naprawdę nie ma znaczenia!",
		WHALE_CARCASS_WHITE = "Zwyciężyłem!",
		WHALE_TRACK = "Nie uciekniesz!",
		WHALE_WHITE = "Znowu się spotykamy.",
		WILBUR_CROWN = "W środku jest wręcz obleśna.",
		WILBUR_UNLOCK = "Obawiam się, że nie ma już szans cię odesłać.",
		WILDBORE = "Pozbędę się tego prosiaka bez problemu.",
		WILDBOREHEAD = "Tworzy naprawdę cudowny nastrój.",
		WILDBOREHOUSE = "Osiągnięcia tutejszej architektury?",
		WIND_CONCH = "Piękna na zewnątrz, niszczycielska wewnątrz.",
		WOODLEGSBOAT = "Wygląda dość solidnie.",
		WOODLEGSHAT = "Zawadiacki...",
		WOODLEGSSAIL = "Przyzwoity żagiel.",
		WOODLEGS_CAGE = "Wszyscy jesteśmy uwięzieni. W ten czy inny sposób.",
		WOODLEGS_KEY1 = "Trochę łamliwy.",
		WOODLEGS_KEY2 = "Klucz ze szczerego złota.",
		WOODLEGS_KEY3 = "Zwykłe żelazo.",
		WRECK = "Nie miał szans.",
		CALIFORNIAROLL = "Znowu się spotykamy, krabliku.",
	},
	DESCRIBE_GENERIC = "Takie coś, z takim czymś, bez takiego czegoś.",
	DESCRIBE_TOODARK = "Nic nie widzę w tej ciemności!",
	DESCRIBE_SMOLDERING = "Niedługo wybuchnie ogniem.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "To nie było rozsądne!",
	},
}
