return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Non credo che le piacerebbe.",
			GENERIC = "Non si può rasare se non ci sono peli.",
			NOBITS = "È già tosato, eh?",
            REFUSE = "Mi piace la mia barba.",
		},
		STORE =
		{
			GENERIC = "È già più pieno di un tram di Toronto.",
			NOTALLOWED = "Non è proprio l'idea migliore, eh?",
		},
		WRITE =
        {
            GENERIC = "Oh no, grazie. Ho una scrittura terribile.",
        },
		RUMMAGE =
        {   
            GENERIC = "Spiacente, non posso in questo momento.", 
        },
		COOK =
        {
            GENERIC = "Spiacente, non posso cucinare adesso.",
            TOOFAR = "Devo avvicinarmi, eh?",
        },
        CHANGEIN =
        {
            GENERIC = "Eh. Non sembro già abbastanza impressionante?",
            BURNING = "Meglio quello che un albero.",
        },
        GIVE =
        {
            DEAD = "Non credo che... ehm...",
            SLEEPING = "Sta dormendo.",
            BUSY = "Ci proverò di nuovo in un momento.",
        },
		REPAIRBOAT =
		{
			GENERIC = "Temo di non poterlo fare.",
		},
		TEACH =
        {
            KNOWN = "Lo so già, eh?",
            CANTLEARN = "Emm... hai capito questo, Lucy?",
        },
	},
	ACTIONFAIL_GENERIC = "Mi dispiace, ma non posso farlo.",
	ANNOUNCE_MAGIC_FAIL = "Quella cosa non può funzionare qua, eh.",
	ANNOUNCE_ADVENTUREFAIL = "Oh beh. C'ho provato.",
	ANNOUNCE_BEES = "Api! Api!",
	ANNOUNCE_BOOMERANG = "Scusa! Sono un maldestro!",
	ANNOUNCE_CHARLIE = "Chi c'è là, eh?",
	ANNOUNCE_CHARLIE_ATTACK = "Ahio! Che botta!",
	ANNOUNCE_COLD = "È un po' freddo qui fuori!",
	ANNOUNCE_HOT = "È così caldo qui fuori!",
	ANNOUNCE_CRAFTING_FAIL = "Non posso farlo in questo momento.",
	ANNOUNCE_DEERCLOPS = "Che cos'è stato?",
	ANNOUNCE_DUSK = "È quasi il momento di andare a dormire.",
	ANNOUNCE_NOSLEEPONFIRE = "Non sono sicuro sia completamente sicuro.",
	ANNOUNCE_NODANGERSIESTA = "Non posso riposare, qualcosa mi insegue.",
	ANNOUNCE_NONIGHTSIESTA = "Preferisco fare la siesta tra un taglio e l'altro, non di notte.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Preferisco fare la siesta tra un taglio e l'altro, non di notte.",
	ANNOUNCE_NOHUNGERSIESTA = "Mi brontola lo stomaco. Non riuscirò mai a rilassarmi.",
	ANNOUNCE_SHELTER = "Grazie per il riparo, amico. Ti dovrò tagliare comunque.",
	ANNOUNCE_BURNT = "Ahi, scotta!",
	ANNOUNCE_TOOL_SLIP = "La materia degli incubi!",
	ANNOUNCE_DAMP = "Un po' umido, eh?",
	ANNOUNCE_WET = "Il plaid è caldo, anche quando è umido.",
	ANNOUNCE_WETTER = "Mi sto bagnando abbastanza, eh?",
	ANNOUNCE_SOAKED = "Meglio tenersi stretti, Lucy.",

	ANNOUNCE_OTHER_WORLD_PLANT = "Il tipo di terreno sbagliato, eh?",

	ANNOUNCE_EAT =
	{
		GENERIC = "Saporito!",
		PAINFUL = "Quello era oltre la data di scadenza.",
		SPOILED = "È stato un tantino disgustoso.",
		STALE = "Sono arrivato appena in tempo.",
		INVALID = "Non credo che i miei denti riescano a masticarlo.",
		YUCKY = "Preferirei masticare il blubbolo.",
	},
	ANNOUNCE_ENTER_DARK = "Chi ha spento la luce?",
	ANNOUNCE_ENTER_LIGHT = "Splendore!",
	ANNOUNCE_FREEDOM = "Sono uscito!",
	ANNOUNCE_HOUNDS = "C'è qualcosa là fuori.",
	ANNOUNCE_HUNGRY = "Comincio ad avere un certo appetito.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "La bestia è nei paraggi.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Sono più un boscaiolo che un cacciatore in ogni caso.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Le tracce della bestia sono state cancellate dall'acqua.",
	ANNOUNCE_INV_FULL = "Non posso trasportare nient'altro!",
	ANNOUNCE_KNOCKEDOUT = "Oh. Che cos'è stato?",
	ANNOUNCE_MOSQUITOS = "Moscerini!",
	ANNOUNCE_NODANGERSLEEP = "È una situazione troppo preoccupante per dormire.",
	ANNOUNCE_NODAYSLEEP = "Solo un idiota dorme durante il giorno.",
	ANNOUNCE_NOHUNGERSLEEP = "La mia pancia è troppo vuota per addormentarsi.",
	ANNOUNCE_NO_TRAP = "C'è mancato un pelo!",
	ANNOUNCE_PECKED = "Spiacente! Ci metterò più impegno!",
	ANNOUNCE_QUAKE = "La terra è ansante!",
	ANNOUNCE_THORNS = "Ahia!",
	ANNOUNCE_TORCH_OUT = "La mia luce si è spenta!",
	ANNOUNCE_FAN_OUT = "Immagino che potrò solo soffrire adesso.",
    ANNOUNCE_COMPASS_OUT = "Il Nord sarà sempre nel mio cuore.",
	ANNOUNCE_TRAP_WENT_OFF = "Ops!",
	ANNOUNCE_WORMHOLE = "È stato nauseante là dentro!",
	ANNOUNCE_CANFIX = "\nCredo di poter sistemare questo!",
	ANNOUNCE_ACCOMPLISHMENT= "Lucy sarà così orgogliosa di me!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Questo è un involucro!",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Serve più cacca, eh?",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Ha fatto il solletico, eh?",

	ANNOUNCE_BOAT_DAMAGED = "La mia barca è molto sbattuta, eh?",
	ANNOUNCE_BOAT_SINKING = "Sto per affondare!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Stiamo affondando!",
	ANNOUNCE_CRAB_ESCAPE = "È fuggito.",
	ANNOUNCE_HIGHRESEARCH = "Informativo.",
	ANNOUNCE_LOWRESEARCH = "Ne è valsa quasi la pena, eh?",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "In acque sconosciute!",
	ANNOUNCE_MAPWRAP_RETURN = "È stato imprudente!",
	ANNOUNCE_MAPWRAP_WARN = "Sto abbandonando le acque conosciute...",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Il mare ha cancellato il messaggio.",
	},
	ANNOUNCE_MORETREASURE = "C'è altro oro da trovare!",
	ANNOUNCE_NODAYSLEEP_CAVE = "Non mi sento troppo riposato in questo momento.",
	ANNOUNCE_NOWARDROBEONFIRE = "Va bene. Ho solo bisogno di una buona flanella, in ogni modo.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Non credo di poterlo trovare qui.",
	ANNOUNCE_RESEARCH = "Lo studio mantiene la mente affilata. Come un'ascia.",
	ANNOUNCE_SHARX = "C'è un pesce nelle vicinanze... ed è affamato!",
	ANNOUNCE_TRAWL_FULL = "È tempo di tirar su!",
	ANNOUNCE_TREASURE = "Ecco arrivare la corsa all'oro!",
	ANNOUNCE_UNIMPLEMENTED = "Eh! Non credo che sia pronto.",
	ANNOUNCE_VOLCANO_ERUPT = "Ooh, quello sembra davvero un tempaccio, eh?",
	ANNOUNCE_WAVE_BOOST = "Verso il nord!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Sono nato per trovare le bestie!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Ho perso le tracce. Mi dispiace!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Dove è andata la balena?!",

	BATTLECRY =
	{
		GENERIC = "Vieni qui, eh!",
		PIG = "Ti farò diventare pancetta!",
		PREY = "Questa è la tua fine!",
		SPIDER = "Verso il nord!",
		SPIDER_WARRIOR = "Preparati ad essere tagliato!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Credo sia abbastanza.",
		PIG = "Credevo sarebbe andata meglio.",
		PREY = "Spiacente, spiacente!",
		SPIDER = "Spiacente!",
		SPIDER_WARRIOR = "Alla stessa ora domani di nuovo, eh?",
	},
	DESCRIBE =
	{
		PIGMAN =
		{
			FOLLOWER = "Facciamo una bella squadra!",
			GENERIC = "Pancetta che ritorna all'ovile!",
			GUARD = "Quello sembra uno importante.",
			WEREPIG = "Succede ai migliori.",
			DEAD = "Non è più un maiale.",
		},
		GLOMMER = "Continua a sbattere, piccoletto!",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Perfino il fiore è viscido.",
        	DEAD = "Morto e ancora viscido.",
        },
        GLOMMERWINGS = "Non mi sorprende che le ali siano viscide.",
        GLOMMERFUEL = "Sì, la sua melma è melmosa.",
        BELL = "Sono stupefatto che emetta un suono così pulito.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "È una statua curiosa, eh?",
        	EMPTY = "Aveva alcune cose belle all'interno, eh?",
    	},
		WEBBERSKULL = "Anche il cranio mi dà i brividi.",
		MOLE =
		{
			HELD = "Vuoi qualche pietra?",
			UNDERGROUND = "Scava, scava, scava.",
			ABOVEGROUND = "I suoi sentimenti per le rocce sono gli stessi che ho io per gli alberi.",
		},
		MOLEHILL = "Scommetto che c'è solo un mucchio di sassi dentro.",
		MOLEHAT = "E ora si taglia con la funzione notturna.",
		NIGHTSTICK = "Quello è elegantissimo.",
		RABBITHOUSE=
		{
			GENERIC = "È al gusto di carota?",
			BURNT = "È al gusto di carota arrostita?",
		},
		TURF_DECIDUOUS = "Solo un po' di terra, eh?",
		TURF_SANDY = "Just some ground, eh?",
		TURF_BADLANDS = "Solo un po' di terra, eh?",

		LAVA_POND_ROCK = "Masso",
		LAVA_POND_ROCK2 = "Masso",
		LAVA_POND_ROCK3 = "Masso.",
		LAVA_POND_ROCK4 = "Masso.",
		LAVA_POND_ROCK5 = "Masso",
		LAVA_POND_ROCK6 = "Masso.",
		LAVA_POND_ROCK7 = "Masso",

		BEARGER = "Quello è un grande orso!",
		BEARGERVEST = "Questo è un equipaggiamento invernale adeguato.",
		CAVE_BANANA_BURNT = "Un tale spreco.",
		SCORCHED_SKELETON = "Accidenti.",
		ICEPACK = "Ottimo per lunghe escursioni.",
		BEARGER_FUR = "È denso come la mia testa!",
		BIGFOOT = "Guarda dove metti i piedi!",
		BONESHARD = "Vorrei sapere come fare il pane.",
		BUZZARD = "Stai lontano dai miei spuntini di carne!",
		CACTUS = 
		{
			GENERIC = "Farà male.",
			PICKED = "Sicuramente l'ha fatto.",
		},
		CACTUS_MEAT_COOKED = "Molto meglio.",
		CACTUS_MEAT = "Ti metteresti dei chiodi in bocca?",
		CACTUS_FLOWER = "È uno stupore che in questo clima possa crescere qualsiasi cosa.",
		COLDFIRE =
		{
			EMBERS = "È quasi finito.",
			GENERIC = "Questo lo farà sentire più a casa.",
			HIGH = "Uh oh! È un po' alto!",
			LOW = "Probabilmente dovrei fare qualcosa, eh?",
			NORMAL = "Mi piace un fuoco freddo la sera.",
			OUT = "È stato bello finché è durato.",
		},
		CATCOON = "Parassiti.",
		CATCOONDEN = 
		{
			GENERIC = "Ugh, ma quante altre vite hai?",
			EMPTY = "Che liberazione.",
		},
		CATCOONHAT = "Abito tradizionale del boscaiolo.",
		COONTAIL = "La fine del racconto di quel gatto.",
		COOKPOT =
		{
			COOKING_LONG = "Ci vorrà un po' di più, eh?",
			COOKING_SHORT = "Oh! Eccolo che arriva!",
			DONE = "È ora di cena!",
			EMPTY = "Mi sembra uno spreco lasciarla vuota.",
			BURNT = "Bruciato fino a croccare.",
		},
		EYEBRELLAHAT =	"È sempre una bella cosa avere qualcosa che vegli su di te.",
		ARMORDRAGONFLY = "Il plaid è tutta l'armatura di cui ho bisogno.",
		DRAGON_SCALES = "Continuo a non credere ai draghi.",
		DRAGONFLYCHEST = "Sgargiante, se chiedi a me.",
		DECIDUOUSTREE = 
		{
			BURNING = "Nooo! Avrei potuto abbatterlo!",
			BURNT = "Che spreco.",
			CHOPPED = "Ahhhh!",
			GENERIC = "Mi sta chiamando!",
			POISON = "Sei pronto per una tagliata.",
		},
		ACORN_COOKED = "Che spreco di albero assolutamente buono.",
		BIRCHNUTDRAKE = "Abbatterò anche te!",
		FARMPLOT =
		{
			GENERIC = "Preferisco piante più grandi.",
			GROWING = "Non raggiungeranno mai la dimensione giusta per essere tagliati.",
			NEEDSFERTILIZER = "Credo abbia bisogno di un po' di cacca.",
			BURNT = "Se fosse stata una fattoria di legno, sarei triste.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Dovrei andare a tagliare della legna per quello, eh?",
			GENERIC = "Utilizza il legno.",
			HIGH = "Sto usando troppa legna troppo velocemente!",
			LOW = "Ci dovrebbe essere della legna qui intorno da qualche parte.",
			NORMAL = "Mmmm. Odore legnoso.",
			OUT = "Se solo avessi un po' di legna.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Salva gli alberi!",
			OFF = "Cosa pigra.",
			LOWFUEL = "Brama il legno.",
		},
		ICEHAT = "Lo avrei tagliato se avessi dovuto.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Hai proprio un bel paio di corna, sai?",
			CHARGED = "Bella capra, bella capra!",
		},
		LIGHTNINGGOATHORN = "Il tuo corno è mio.",
		GOATMILK = "Credo che l'elettricità lo abbia cagliato.",
		MEATRACK =
		{
			DONE = "Quello sembra pronto.",
			DRYING = "È come guardare la carne seccarsi.",
			DRYINGINRAIN = "È come guardare la carne secca... sotto la pioggia.",
			GENERIC = "È tutto impostato. Basta aggiungere la carne.",
			BURNT = "La sua utilità si è seccata.",
		},
		MERMHEAD = 
		{
			GENERIC = "Puzza come un peschereccio.",
			BURNT = "Straordinario, puzza anche peggio adesso.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Non sono i più pratici.",
			BURNT = "Non sono riusciti nemmeno a costruire una casa a prova di fuoco.",
		},
		FLOWERSALAD = "Sano, ma non molto resistente.",
        ICECREAM = "Solo dopo che ho tagliato abbastanza!",
        WATERMELONICLE = "Legno e cibo?!",
        TRAILMIX = "Lo spuntino perfetto per una giornata di tagliate.",
        HOTCHILI = "È buono dopo una lunga giornata di tagliate al freddo.",
        GUACAMOLE = "Non sono sicuro di fidarmi di lui.",
		MOOSE = "Qualunque cosa sia, è sicuramente canadese.",
		MOOSEEGG = "Beh, depone uova, in apparenza.",
		MOSSLING = "Cucciolo di alce piumata!",
		FEATHERFAN = "Un ventaglio canadese tradizionale.",
		TROPICALFAN = "Non sono abituato al caldo in questo luogo!",
		MINIFAN = "Non sono abituato al caldo in questo luogo!",
		GOOSE_FEATHER = "Piumaggio cuscinoso.",
		STAFF_TORNADO = "Preferisco tagliare gli alberi da solo.",
		PIGHEAD = 
		{	
			GENERIC = "Che spreco di buon maiale.",
			BURNT = "Vorrei lamentarmi con lo chef. In modo cortese.",
		},
		PIGHOUSE =
		{
			FULL = "È ripieno di pancetta.",
			GENERIC = "Un piccolo nastro adesivo potrebbe sistemare le cose.",
			LIGHTSOUT = "Scusa! Non sto spiando, giuro!",
			BURNT = "Soltanto un emblema della sua gloria passata.",
		},
		FERTILIZER = "La cacca deve stare nei secchi, non per terra.",
		RAINOMETER = 
		{	
			GENERIC = "La pioggia fa crescere gli alberi.",
			BURNT = "La sua conoscenza della pioggia non ha evitato che si bruciasse.",
		},
		RAINCOAT = "Per tagliare sotto la pioggia.",
		RAINHAT = "Mantieni sempre la testa asciutta mentre tagli.",
		RESEARCHLAB = 
		{	
			GENERIC = "Non mi fido di tutta questa scienza.",
			BURNT = "Come si è bruciato?!",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Questo sta diventando strano.",
			BURNT = "Beh, ubbidisce a qualche legge basilare della fisica.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "OK, credo di capire adesso.",
			BURNT = "No, è perso.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Mi piace chiamarlo \"macchina cappello\"!",
			BURNT = "Ecco perché io non uso gli scaldini.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Ci sto bene con il legno.",
			BURNT = "Non sto molto bene da bruciato.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Casa dolce casa!",
			MELTED = "Da dove vengo, non si sciolgono mai.",
		},
		ROCK_ICE_MELTED = "Da dove vengo, non si sciolgono mai.",
		ICE = "Un souvenir di casa da tenere in tasca.",
        REFLECTIVEVEST = "Sono ancora convinto che il plaid non sia un tessuto per tutte le stagioni.",
		HAWAIIANSHIRT = "Io davvero preferisco il plaid.",
		TENT = 
		{
			GENERIC = "Sono abituato a dormire in posti peggiori.",
			BURNT = "Non credo che la si possa considerare ancora una tenda.",
		},
		SIESTAHUT = 
		{
			GENERIC = "I sonnellini sono importanti durante le lunghe giornate passate a tagliare.",
			BURNT = "È un guscio.",
		},
		TRANSISTOR = "Non farò neanche finta di sapere come funziona quello.",
		TREASURECHEST = 
		{
			GENERIC = "Il legno è così pratico! Guarda tutte le cose che si possono fare!",
			BURNT = "Immagino che il legno abbia un aspetto negativo...",
		},
		TUMBLEWEED = "Vorrei che fosse più duro per poterlo tagliare.",
		GRASS_UMBRELLA = "Questo dovrebbe tenermi la barba relativamente asciutta, eh?",
		PALMLEAF_UMBRELLA = "Credo di aver fatto un buon lavoro su questo ombrello.",
		WALL_HAY = 
		{	
			GENERIC = "Potrei starnutire.",
			BURNT = "Beh, la cosa si è intensificata rapidamente.",
		},
		WALL_WOOD = 
		{
			GENERIC = "Mi piace il suo aspetto!",
			BURNT = "Mi manca il vecchio te.",
		},
		WARDROBE = 
        {
        	GENERIC = "È difficile rimanere pulito e ordinato nel bosco.",
            BURNING = "Il legno è imbattibile nel bruciare.",
        	BURNT = "È così utile!",
    	},
		WARG = "Quel coso potrebbe tirare una slitta in solitudine.",
		WATERMELON = "Come può essere sia acqua che anguria?",
		WATERMELON_COOKED = "Non sono sicuro della frutta alla griglia...",
		WATERMELONHAT = "Puoi chiamarmi signor Anguria.",
		WINTEROMETER = 
		{
			GENERIC = "Li possiamo costruire di metà altezza da dove vengo io.",
			BURNT = "Quelli da dove vengo io non bruciano.",
		},
		WORMLIGHT = "Questa cosa sarà utile.",
		WORM =
		{
		    PLANT = "Riconosco una pianta quando ne vedo una. Questo è un impostore!",
		    DIRT = "Diffida della terra che si muove.",
		    WORM = "VEEERME!",
		},
		EEL = "Questa dovrebbe cuocere benissimo.",
		EEL_COOKED = "Questa è cotta benissimo.",
		UNAGI = "Ti riempirà.",
		EYETURRET = "Quella dovrebbe tenere a bada gli idioti.",
		EYETURRET_ITEM = "Questo deve essere installato correttamente.",
		MINOTAURHORN = "È un bel corno, eh.",
		MINOTAURCHEST = "Quello è un ottimo scrigno con le corna, eh.",
		THULECITE_PIECES = "Non si tratta di legno, ma lo farò.",
		POND_ALGAE = "Non sembra commestibile.",
		GREENSTAFF = "Questo mi aiuterà a smantellare le cose!",
		POTTEDFERN = "Mostra il mio amore per la vita vegetale.",

		THULECITE = "È il legno delle grotte!",
		ARMORRUINS = "Così smetterà di fare male.",
		RUINS_BAT = "Metallo su uno spiedo.",
		RUINSHAT = "Non è un tocco, ma farà al caso.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Penso che sia spento.",	--calm phase
			WARN = "Questa cosa si è appena accesa!",	--Before nightmare
			WAXING = "Sta vibrando!", --Nightmare Phase first 33%
			STEADY = "Sta impazzendo!", --Nightmare 33% - 66%
			WANING = "Si sta calmando.", --Nightmare 66% +
			DAWN = "È quasi immobile.", --After nightmare
			NOMAGIC = "Penso che sia spento.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "Posso vedere i meccanismi interni!",
		ROOK_NIGHTMARE = "Gli ingranaggi vengono allo scoperto.",
		KNIGHT_NIGHTMARE = "Non sembra essere al meglio della forma.",
		MINOTAUR = "Un'altra povera anima con una maledizione.",	--Monster in labyrinth
		SPIDER_DROPPER = "Fanno bene a stare alla larga dalla corruzione.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Avrebbero dovuto usare il legno.",	--Lights that activate during nightmare.
		RELIC = "Piece of furniture.",	--Fixed relic
		RUINS_RUBBLE = "Tutto ridotto male.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "È... è bellissima.",	--Works as axe and pickaxe
		GREENGEM = "Molto appariscente.",
		ORANGESTAFF = "Questo mi aiuterà a spostarmi rapidamente.",	--Teleports player.
		YELLOWAMULET = "Potrei tagliare il legno di notte con questo.",	--Emits light, player walks faster.
		GREENAMULET = "Sono sempre stato bravo a tagliare, in ogni caso.",	--Reduce cost of crafting

		SLURPER = "Penso che siano dei capelli viventi.",
		SLURPER_PELT = "Sembra un castoro morto.",
		SLURPERPELT = "Where's the nearest fur trader?",
		ARMORSLURPER = "Sente il solletico, credo sia ancora vivo.",
		SPIDERHOLE_ROCK ="Dovrei darmela a gambe prima che escano da là.",
		ORANGEAMULET = "Questo farà passare più velocemente le faccende!",
		YELLOWSTAFF = "Utile in un pizzico!",
		YELLOWGEM = "Riesco a vederci le stelle.",
		ORANGEGEM = "È scintillante.",
		RELIC =
		{
			BROKEN = "I don't plan on fixin' that.",
			GENERIC = "What's this all aboot?",
		},
		TELEBASE = 
		{
			VALID = "It's humming with energy.",
			GEMS = "I don't think it has power.",
		},
		GEMSOCKET = 
		{
			VALID = "Sembra pronto.",
			GEMS = "Avrà bisogno di una gemma.",
		},
		STAFFLIGHT = "Beh, mica male.",	
		LUCY = "Amo Lucy!",
        ANCIENT_ALTAR =
        {
        	WORKING = "Ci sono dei segni di ascia su queste pietre dell'altare.",
        	BROKEN = "Sembra un po' usurato.",
        },             
        ANCIENT_ALTAR_BROKEN = "Sembra un po' usurato.",
        ANCIENT_STATUE = "Un altro idiota.",
        LICHEN = "Sembra appena commestibile.",
		CUTLICHEN = "Gnam! Ha un sapore legnoso!",
		CAVE_BANANA = "Ha un sapore tropicale.",
		CAVE_BANANA_COOKED = "L'ho cucinata per qualche motivo.",
		CAVE_BANANA_TREE = "Non ce ne sono da dove vengo.",
		ROCKY = "Ora di cena di aragosta!",
		
		COMPASS =
		{
			GENERIC="Punta verso il vero nord.",
			N = "Vero nord",
			S = "Sud.",
			E = "Est.",
			W = "Ovest.",
			NE = "Nord-est.",
			SE = "Sud-est.",
			NW = "Nord-ovest.",
			SW = "Sud-ovest.",
		},

		BLUEAMULET = "Ora posso mantenere le mie bevande gelide.",
		PURPLEAMULET = "La scintilla della gemma è finita.",
		TELESTAFF = "Just another use for wood.",
		MONKEY = "Ben fatto. Questa è una novità.",
		MONKEYBARREL = "Che bella scelta di materiali di costruzione.",

		HOUNDSTOOTH="Che meraviglia!",
		ARMORSNURTLESHELL="Non si può mai essere troppo sicuri.",
		BAT="Chi ha insegnato quel ratto a volare?",
		BATBAT = "Un topo con le ali?",
		BATWING="Disgustoso!",
		BATWING_COOKED="Nauseante! E gustoso! Che confusione!",
		BATCAVE = "Pieno di piccole creature!",
		
		BEDROLL_FURRY="Mi piace il campeggio.",
		BUNNYMAN="Sembra abbastanza amichevole.",
		FLOWER_CAVE="Brillante!",
		FLOWER_CAVE_DOUBLE="Brillante!",
		FLOWER_CAVE_TRIPLE="Brillante!",
		GUANO="Puzza meno degli altri tipi.",
		LANTERN="Beh è illuminante, eh?",
		LIGHTBULB="Sembra gommoso.",
		MANRABBIT_TAIL="Mi dispiace per esso.",
		MUSHTREE_TALL  ="I can't let that stand.",
		MUSHTREE_MEDIUM="Maybe I should chop it.",
		MUSHTREE_SMALL ="It's made of wood.",
		MUSHTREE_TALL=
		{
            GENERIC = "Non posso permettere che rimanga in piedi.",
            BLOOM = "Recidilo prima che si diffonda!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Forse dovrei abbatterlo.",
            BLOOM = "Mi piace il colore di questo.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "È fatto di legno.",
            BLOOM = "Beh, non posso abbatterlo ora...",
        },
        MUSHTREE_TALL_WEBBED = "Questo ha bisogno come minimo di una potatura.",
        SPORE_TALL = "Una pigna volante!",
        SPORE_MEDIUM = "Pigne volanti!",
        SPORE_SMALL = "Pigne volanti!",
        SPORE_TALL_INV = "Un giorno questo potrebbe essere un albero.",
        SPORE_MEDIUM_INV = "Un giorno questo potrebbe essere un albero.",
        SPORE_SMALL_INV = "Un giorno questo potrebbe essere un albero.",
		SLURTLE="È solo un incompreso.",
		SLURTLE_SHELLPIECES="Ho rotto la sua casa. Mi sento male.",
		SLURTLEHAT="Questo terrà al riparo la mia capoccia.",
		SLURTLEHOLE="Tutto bene là dentro?",
		SLURTLESLIME="Qualcuno ha bisogno di un fazzoletto.",
		SNURTLE="Spirali!",
		SPIDER_HIDER="Furbo diavolo!",
		SPIDER_SPITTER="Sputare è da maleducati!",
		SPIDERHOLE="Dovrei darmela a gambe prima che escano da là.",
		STALAGMITE="Non sono troppo interessato alle rocce.",
		STALAGMITE_FULL="Non sono troppo interessato alle rocce.",
		STALAGMITE_LOW="Non sono troppo interessato alle rocce.",
		STALAGMITE_MED="Non sono troppo interessato alle rocce.",
		STALAGMITE_TALL="Non sono troppo interessato alle rocce.",
		STALAGMITE_TALL_FULL="Non sono troppo interessato alle rocce.",
		STALAGMITE_TALL_LOW="Non sono troppo interessato alle rocce.",
		STALAGMITE_TALL_MED="Non sono troppo interessato alle rocce.",


		TURF_CARPETFLOOR = "Some ground.",
		TURF_CHECKERFLOOR = "Some ground.",
		TURF_DIRT = "Some ground.",
		TURF_FOREST = "Some ground.",
		TURF_GRASS = "Some ground.",
		TURF_MARSH = "Some ground.",
		TURF_ROAD = "Some ground.",
		TURF_ROCKY = "Some ground.",
		TURF_SAVANNA = "Some ground.",
		TURF_WOODFLOOR = "Some ground.",

		TURF_CAVE="Un pezzo di terreno.",
		TURF_FUNGUS="È molle come i piselli.",
		TURF_SINKHOLE="L'ho trovato sottoterra.",
		TURF_UNDERROCK="Rocce. Bleah.",	
		TURF_MUD="Almeno non devi pulirlo.",

		
		POWCAKE = "Mi piacciono di più quelli fatti con vero zucchero.",
        CAVE_ENTRANCE = "È tutta ostruita.",
        CAVE_ENTRANCE_RUINS = "È otturato.",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "Probabilmente non ci sono alberi là sotto comunque.",
            OPEN = "Sembra Sudbury laggiù.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Magari più tardi. Sono molto comodo quaggiù.",
            OPEN = "Ci sono probabilmente degli alberi lassù.",
        },
		
		MAXWELLPHONOGRAPH = "Meglio della maggior parte della roba trasmessa alla radio.",
		BOOMERANG = "Sembra difficile da tirare.",
		PIGGUARD = "Non voglio farlo arrabbiare.",
		ADVENTURE_PORTAL = "Mi chiedo se questa sia l'uscita da qui.",
		AMULET = "Devi sempre avere un piano di riserva.",
		ANIMAL_TRACK = "Una grande creatura dei boschi è passata da questa parte!",
		ARMORGRASS = "Meglio che niente.",
		ARMORMARBLE = "È difficile maneggiare un'ascia quando si indossa questa cosa.",
		ARMORWOOD = "Mi calza così bene!",
		ARMOR_SANITY = "La sua vista mi dà la nausea.",
		ASH =
		{
			GENERIC = "È tutto bruciato.",
			REMAINS_GLOMMERFLOWER = "Questo è stato un fiore viscido.",
			REMAINS_EYE_BONE = "Questo era un ossocchio.",
			REMAINS_THINGIE = "Immagino che non passi di lì.",
		},
		AXE = "Non è simpatica quanto Lucy.",
		BABYBEEFALO = "Un volto che solo una madre potrebbe amare.",
		BACKPACK = "Quello è il mio zaino.",
		BACONEGGS = "Ohhh. È solo pancetta.",
		BANDAGE = "Almeno non ho dovuto sborsare il becco di un quattrino.",
		BASALT = "Quella roccia non si sposta.",
		BEARDHAIR = "I miei capelli non sono di quel colore. Soprattutto la mia barba.",
		BEDROLL_STRAW = "Ho dormito su cose peggiori nel campo di legname.",
		BEE =
		{
			GENERIC = "Fa crescere i fiori.",
			HELD = "E adesso che ci faccio con questo?",
		},
		BEEBOX =
		{
			FULLHONEY = "Surrogato dello sciroppo d'acero!",
			READY = "Surrogato dello sciroppo d'acero!",
			GENERIC = "Cicalini!",
			NOHONEY = "Mi sta venendo fame solo a guardarlo!",
			SOMEHONEY = "Avrei potuto ottenere di più se avessi aspettato.",
			BURNT = "No, non le api!",
		},
		BEEFALO =
		{
			FOLLOWER = "Credo di piacergli.",
			GENERIC = "Puzza come una casa ricoperta di zolle.",
			NAKED = "Su con la vita, eh?",
			SLEEPING = "Sta facendo un pisolino.",
		},
		BEEFALOHAT = "Adesso sono il re del mufalo!",
		BEEFALOWOOL = "Mi sembra la mia barba.",
		BEEHAT = "Quello terrà le api lontane dai miei occhi.",
		
		BEEHIVE = "Sono tutti comodi lì dentro.",
		
		BEEMINE = "Non so se piace alle api.",
		BEEMINE_MAXWELL = "Ehi! Questa è pura cattiveria!",
		BERRIES = "Ho un appetito più grande di quello.",
		BERRIES_COOKED = "Sa di bacche calde.",
		BERRYBUSH =
		{
			BARREN = "Ha bisogno di una buona cacca.",
			WITHERED = "È malmesso dal calore, eh?",
			GENERIC = "Bacche Saskatoon?",
			PICKED = "Nessuna bacca rimasta!",
		},
		BIRDCAGE =
		{
			GENERIC = "È dove cerco di far rinsavire i pennuti.",
			OCCUPIED = "Pensa a quello che hai fatto, pennuto!",
			SLEEPING = "Sembrano così innocenti quando sognano.",
			HUNGRY = "Ti prendo qualcosa da mangiare al più presto, amichetto.",
			STARVING = "Ha una voglia matta di poutine!",
			DEAD = "Sono davvero dispiaciuto! Non ho imparato molto.",
			SKELETON = "Sta iniziando a puzzare.",
		},
		BIRDTRAP = "Darò una bella lezione a quei pennuti!",
		BIRD_EGG = "C'è un pennuto là dentro che fa cattivi pensieri di pennuti.",
		BIRD_EGG_COOKED = "Beh, almeno non è mai diventato un pennuto.",
		BISHOP = "Ho sempre voluto conoscere un vero alfiere.",
		BLOWDART_FIRE = "Questo sembra un po' aggressivo.",
		BLOWDART_SLEEP = "Posso darmi alla fuga se uso questo!",
		BLOWDART_PIPE = "Vediamo cosa possono fare i miei enormi polmoni con questo!",
		BLUEGEM = "È molto fredda.",
		BLUEPRINT = "Non sono fatto per imparare dai libri.",
		BELL_BLUEPRINT = "Non sono fatto per imparare dai libri.",
		BLUE_CAP = "Non è carne.",
		BLUE_CAP_COOKED = "Non è carne.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Non riesco mai a ricordare quale si può mangiare.",
			INGROUND = "Tornerò più tardi.",
			PICKED = "Bene, è finita.",
		},
		BOARDS = "Così liscio. È davvero possibile vedere il grano.",
		BOAT = "Deve aver navigato a nord-est.",
		BONESTEW = "Si attacca alle costine.",
		BUGNET = "Può raccogliere moscerini.",
		BUSHHAT = "È ottimo per nascondersi dalla natura.",
		BUTTER = "Preferisco la margarina.",
		BUTTERFLY =
		{
			GENERIC = "Non mi sono mai fidato di queste cose, eh?",
			HELD = "Dove andrai a correre?",
		},
		BUTTERFLYMUFFIN = "Croccante!... Ma morbido?",
		BUTTERFLYWINGS = "Mi spiace! Sono una persona orribile!",
		CAMPFIRE =
		{
			EMBERS = "È quasi finito.",
			GENERIC = "Dove è la mia chitarra?",
			HIGH = "Uh oh! È un po' alto!",
			LOW = "Probabilmente dovrei fare qualcosa, eh?",
			NORMAL = "Mi piace il fuoco la sera.",
			OUT = "È stato bello finché è durato.",
		},
		CANE = "È utile nelle zone remote.",
		CARROT = "È cibo per conigli.",
		CARROT_COOKED = "È cibo per conigli.",
		CARROT_PLANTED = "Io non sono uno per le verdure, eh?",
		CARROT_SEEDS = "Carotine.",
		CAVE_FERN = "Ehi! È una felce!",

		CHARCOAL = "Questo mi rende un po' triste.",

        CHESSJUNK1 = "Metallo morto.",
        CHESSJUNK2 = "Metallo morto.",
        CHESSJUNK3 = "Metallo morto.",

		CHESTER = "Sta facendo del suo meglio!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Nessuno mi ha mai detto che fosse maleducato fissare qualcuno.",
			WAITING = "Mi chiedo se si sveglierà mai.",
		},
		COOKEDMANDRAKE = "È stata una cattiva cosa da fare?",
		COOKEDMEAT = "Proprio come la faceva la mia cara mammina.",
		COOKEDMONSTERMEAT = "Ancora non lo voglio mangiare.",
		COOKEDSMALLMEAT = "Mi farà venire ancora più fame!",
		CORN = "Mi piace, ma non in tutto quello che mangio.",
		CORN_COOKED = "Cotto con la bontà del mais.",
		CORN_SEEDS = "Sono più un taglialegna che non un coltivatore meccanico.",
		CROW =
		{
			GENERIC = "Sta architettando qualcosa. È evidente.",
			HELD = "Pagherai per i tuoi crimini, corvo!",
		},
		CUTGRASS = "Penso di essere allergico a questo.",
		CUTREEDS = "Vuoi sentire la mia chiamata folle?",
		CUTSTONE = "Parte dello scudo canadese.",
		DEADLYFEAST = "Ha un odore sospetto, eh.",
		DEERCLOPS = "Ma che grande alce!",
		DEERCLOPS_EYEBALL = "Adesso, a cosa è buono questo?",
		DEPLETED_GRASS =
		{
			GENERIC = "È probabilmente un ciuffo d'erba.",
		},
		DEVTOOL = "No comment.",
		DIRTPILE = "Ehi! Un indizio!",
		DIVININGROD =
		{
			COLD = "È davvero sfocato da qui.",
			GENERIC = "Mi chiedo se ottiene i risultati delle partite di hockey.",
			HOT = "Forte e chiaro! Qualcosa è vicino!",
			WARM = "Penso di essere più vicino.",
			WARMER = "Uoah, fai attenzione, amico.",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "Sembra che questo vada con qualcosa...",
			READY = "È pronto per essere sbloccato.",
			UNLOCKED = "Ora ha bisogno solo di essere acceso.",
		},
		DIVININGRODSTART = "È una bacchetta davvero strana.",
		DRAGONFLY = "Brucerà tutti gli alberi, prima che possa tagliarli!",
		LAVAE = "Morte dall'ascia!",
		LAVAE_PET = 
		{
			STARVING = "Più magro delle gambe di un airone blu.",
			HUNGRY = "Il poverino sta diventando affamato.",
			CONTENT = "Vedi come è felice!",
			GENERIC = "Ecco una creatura deliziosa.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "C'è un fuoco che brucia al suo interno.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Ha bisogno di una giacca a vento.",
			COMFY = "Più comodo di un alce avvolto in nastro adesivo!",
		},
		LAVAE_TOOTH = "Non è tagliente come Lucy!",

		LAVASPIT = 
		{
			HOT = "Aaaah! Assassino di alberi!",
			COOL = "I miei alberi sono al sicuro ora.",
		},
		LAVA_POND = "Non vorrei avvicinarmi troppo a quello, eh?",
		DRAGONFRUIT = "Non ne ho mai visti prima d'ora.",
		DRAGONFRUIT_COOKED = "Sa di sciroppo d'acero.",
		DRAGONFRUIT_SEEDS = "Forse posso farne crescere di più.",
		DRAGONPIE = "Buono quasi come le crostate al burro!",
		DRUMSTICK = "Cibo di ottobre.",
		DRUMSTICK_COOKED = "Grazie, tacchino.",
		DUG_BERRYBUSH = "È ora di un po' di giardinaggio.",
		DUG_GRASS = "Mi fa piangere.",
		DUG_MARSH_BUSH = "Dovrei piantarlo.",
		DUG_SAPLING = "Mmmmm. È tutto sterposo.",
		DURIAN = "Puzza.",
		DURIAN_COOKED = "Odora anche peggio!",
		DURIAN_SEEDS = "Perché dovrei voler farne crescere di più?",
		EARMUFFSHAT = "Da dove vengo io, queste cose funzionano solo in autunno.",
		EGGPLANT = "Scommetto che c'è lo zampino dei pennuti in questa faccenda.",
		EGGPLANT_COOKED = "Sospettosamente pennutoso.",
		EGGPLANT_SEEDS = "Uhmm. Non sono sicuro.",
		ACORN = 
		{
		    GENERIC = "Dovrei farlo crescere per poi abbatterlo!",
		    PLANTED = "Ecco che arriva un albero!",
		},
		EVERGREEN =
		{
			BURNING = "Nooo! Avrei potuto abbatterlo!",
			BURNT = "Che spreco.",
			CHOPPED = "Ahhhh!",
			GENERIC = "Mi sta chiamando.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Mi dispiace!",
			BURNT = "Mi sento malissimo.",
			CHOPPED = "Un altro!",
			GENERIC = "Lucy vorrebbe che lo abbattessi.",
		},
		EYEPLANT = "Deve farsi gli affari suoi.",
		FEATHERHAT = "Non voglio avere niente a che fare con quella... cosa.",
		FEATHER_CROW = "Una piuma nauseante.",
		FEATHER_ROBIN = "Una piuma disgustosa.",
		FEATHER_ROBIN_WINTER = "Una stupida piuma.",
		FEM_PUPPET = "È in trappola!",
		FIREFLIES =
		{
			GENERIC = "Mi ricorda il parco di Algonquin.",
			HELD = "Ho una tasca piena di sole!",
		},
		FIREHOUND = "Segugio focoso!",
		FIREPIT =
		{
			EMBERS = "Dovrei andare a tagliare della legna per quello, eh?",
			GENERIC = "Utilizza il legno.",
			HIGH = "Sto usando troppa legna troppo velocemente!",
			LOW = "Ci dovrebbe essere della legna qui intorno da qualche parte.",
			NORMAL = "Mmmm. Odore legnoso.",
			OUT = "Se solo avessi un po' di legna.",
		},
		FIRESTAFF = "Non mi fido di questa storia della magia.",
		FISH = "Sembra un merluzzo.",
		FISHINGROD = "Dovrei trascorrere un po' di tempo al lago.",
		FISHSTICKS = "Un'elegante cenetta in scatola.",
		FISHTACOS = "Sapore di mare, eh?",
		FISH_MED = "Vuole essere la cena.",
		FISH_MED_COOKED = "Vorrei delle patatine fritte.",
		FISH_COOKED = "Vorrei delle patatine fritte.",
		FLINT = "Questa potrebbe essere una testa di ascia.",
		FLOWER = "Che carino.",
		FLOWER_WITHERED = "Qualcuno ha un pollice marrone.",
		FLOWERHAT = "Penso che stia bene con i miei capelli rossi.",
		FLOWER_EVIL = "Qualcosa non va con quel fiore.",
		FOLIAGE = "Si presenta come un'insalata.",
		FOOTBALLHAT = "Questo renderà i miei capelli come quelli di un giocatore di hockey?",
		FROG =
		{
			DEAD = "Ex-rana.",
			GENERIC = "Non mi fido di ciò che non può decidere tra aria e acqua.",
			SLEEPING = "È stanco.",
		},
		FROGGLEBUNWICH = "Puoi davvero sentire il sapore paludoso.",
		FROGLEGS = "Stanno ancora saltando!",
		FROGLEGS_COOKED = "Almeno hanno smesso di muoversi.",
		FRUITMEDLEY = "Nello sciroppo!",
		GEARS = "Non ci ho mai capito niente di queste cose.",
		GHOST = "Bu! Ah ah!",
		GOLDENAXE = "È quasi bella come Lucy.",
		GOLDENPICKAXE = "È carina, ma non può abbattere gli alberi.",
		GOLDENPITCHFORK = "Gulp. Non posso disfarla, quindi...",
		GOLDENSHOVEL = "È ora di scavare buche d'oro.",
		GOLDNUGGET = "Non puoi fare un tavolino con l'oro.\nBeh, forse puoi. Ma non dovresti.",
		GRASS =
		{
			BARREN = "Ho bisogno di farci la cacca.",
			WITHERED = "Forse prospererebbe se fosse più fresco.",
			BURNING = "Spero che non si diffonda sugli alberi.",
			GENERIC = "Sembra un ramoscello.",
			PICKED = "È diventato tutto nodoso.",
		},
		GREEN_CAP = "Ho mangiato cose più strane nei boschi.",
		GREEN_CAP_COOKED = "Non mi fido.",
		GREEN_MUSHROOM =
		{
			GENERIC = "È un fungo verde.",
			INGROUND = "Hanno i propri tempi.",
			PICKED = "Credo di averlo rotto.",
		},
		GUNPOWDER = "Non mi è mai piaciuta questa roba.",
		HAMBAT = "Che spreco di buon prosciutto.",
		HAMMER = "Tutto commettono degli errori, eh?",
		HEALINGSALVE = "Salute sotto forma di vischio.",
		HEATROCK =
		{
			FROZEN = "Brrr! È congelato.",
			COLD = "Si è fatto freddo, eh?",
			GENERIC = "Da dove vengo io le chiamiamo \"rocce notturne\".",
			WARM = "Sta diventando un po'... medio.",
			HOT = "Potrei tagliare per tutto l'inverno con quello nella mia tasca!",
		},
		HOME = "Chi va là?",
		HOMESIGN = 
		{
			GENERIC = "C'è qualcosa che il legno non possa fare?",
			BURNT = "Il legno è imbattibile nel bruciare.",
		},
		HONEY = "Mmmmmm-mmmm. Sciroppo d'ape.",
		HONEYCOMB = "Mi sento quasi male nell'impossessarmene.",
		HONEYHAM = "Ma non è una vacanza...",
		HONEYNUGGETS = "Uno dei miei piatti preferiti!",
		HORN = "Non so se poterci poggiare la mia bocca.",
		HOUND = "Sarebbero bravi a tirare una slitta.",
		HOUNDBONE = "È ricoperto di saliva di cane, eh?",
		HOUNDMOUND = "Non sono così ingenuo da provocarlo.",
		ICEBOX = "Ahhhh. Mi ricorda casa.",
		ICEHOUND = "Segugi artici?",
		INSANITYROCK =
		{
			ACTIVE = "Dove è andato?!",
			INACTIVE = "Non so come spostarla.",
		},
		JAMMYPRESERVES = "Ora devo trovare il burro di arachidi.",
		KABOBS = "Lo spiedino aggiunge davvero sapore.",
		KILLERBEE =
		{
			GENERIC = "Quell'ape non sembra così amichevole.",
			HELD = "Non è troppo contenta della sua situazione.",
		},
		KNIGHT = "Polizia privata a cavallo di Maxwell.",
		KOALEFANT_SUMMER = "Sembra gustoso.",
		KOALEFANT_WINTER = "Diventano più saporiti in inverno.",
		KRAMPUS = "Fatti da parte, idiota!",
		KRAMPUS_SACK = "Mi sento male a prendere il sacco di qualcun altro.",
		LEIF = "Mi spiace per tutti quegli alberi!",
		LEIF_SPARSE = "Mi spiace per tutti quegli alberi!",
		LIGHTNING_ROD =
		{
			CHARGED = "È bello come l'aurora boreale.",
			GENERIC = "Adesso il tempo non potrà cadere su di me.",
		},
		LITTLE_WALRUS = "Perché sono così tanto a sud?",
		LIVINGLOG = "Ho intenzione di tenerti e chiamarti Frank.",
		LOCKEDWES = "Chi è quell'idiota?",
		LOG =
		{
			BURNING = "Oh no! Non mettere un'altra legna sul fuoco!",
			GENERIC = "Rende tutto proficuo.",
		},
		LUREPLANT = "È carne?",
		LUREPLANTBULB = "È caldo e grumoso.",
		MALE_PUPPET = "Hai bisogno d'aiuto?",
		MANDRAKE =
		{
			DEAD = "Mi dispiace, piccoletto.",
			GENERIC = "Mi sta guardando.",
			PICKED = "Cosa ho fatto?",
		},
		MANDRAKESOUP = "È una zuppa riscaldata.",
		MANDRAKE_COOKED = "Spiacente!",
		MARBLE = "Sembra un edificio governativo.",
		MARBLEPILLAR = "Qualcuno deve averlo costruito.",
		MARBLETREE = "Persino Lucy non potrebbe abbatterlo.",
		MARSH_BUSH =
		{
			BURNING = "Velocissimo!",
			GENERIC = "Quello è un rovo.",
			PICKED = "Ne valeva la pena?",
		},
		MARSH_PLANT = "Pianta.",
		MARSH_TREE =
		{
			BURNING = "È quello che meriti per essere così spinoso!",
			BURNT = "Se lo meritava.",
			CHOPPED = "È stata un'ardua battaglia, ma ho vinto.",
			GENERIC = "Gli alberi non dovrebbero contrattaccare!",
		},
		MAXWELL = "Perché mi odia?",
		MAXWELLHEAD = "Solo una testa, eh?",
		MAXWELLLIGHT = "È innaturale.",
		MAXWELLLOCK = "Dov'è la chiave?",
		MAXWELLTHRONE = "Ho visto sedie più carine.",
		MEAT = "Sa di alce.",
		MEATBALLS = "Quanta carne!",
		MEAT_DRIED = "Ha un sapore di sopravvivenza.",
		MERM = "Da dove diavolo è sbucato quello?",
		MINERHAT = "Giù in profondità nella miniera di carbone.",
		MONSTERLASAGNA = "Questo è cibo per gatti!",
		MONSTERMEAT = "Non ho abbastanza fame per quello.",
		MONSTERMEAT_DRIED = "Ancora non lo voglio mangiare.",
		MOSQUITO =
		{
			GENERIC = "Si succhierà una pinta da me!",
			HELD = "Cosa ci faccio con questo, eh?",
		},
		MOSQUITOSACK = "Sangue e budella, eh?",
		MOUND =
		{
			DUG = "Mi dispiace! Non tormentarmi!",
			GENERIC = "Probabilmente dovrei lasciarlo stare.",
		},
		NIGHTLIGHT = "Che tipo di oscurità è quella?",
		NIGHTMAREFUEL = "Tutte le mie paure nella forma liquida, eh?",
		
		NIGHTSWORD = "Gli incubi non possono farti del male!",
		NITRE = "È così che costruiamo la ferrovia.",
		ONEMANBAND = "Sto in guardia per te!",
		PANDORASCHEST = "Cosa c'è nella scatola?!",
		PANFLUTE = "Canto solo per Lucy.",
		PAPYRUS = "Preferisco tagliare che scrivere.",
		PENGUIN = "Non importa se vieni dal Grande Bianco Nord. Rimani un uccello.",
		PERD = "Altri pennuti! Perché si tratta sempre di pennuti?",
		PEROGIES = "Le chiamo \"tasche delle leccornie\".",
		PETALS = "Mi chiedo se a Lucy piacerebbero.",
		PETALS_EVIL = "Mi guardano corrucciati con le loro piccole facce maligne.",
		PHLEGM = "Non vorrei averlo sui miei baffi.",
		PICKAXE = "Quasi un'ascia, ma non esattamente.",
		PIGGYBACK = "Ho usato tutte le parti del maiale.",
		PIGKING = "Lui non è il MIO re.",
		PIGSKIN = "Pancetta con la coda.",
		PIGTORCH = "Come ci sono riusciti senza pollici?",
		PINECONE = 
		{
		    GENERIC = "Dovrei farlo crescere per poi abbatterlo!",
		    PLANTED = "Ecco che arriva un albero!",
		},
		LUMPY_SAPLING = "Cavoli, dovrò tagliarlo di nuovo.",
		PITCHFORK = "Questo davvero non è il mio stile.",
		PLANTMEAT = "È nauseante!",
		PLANTMEAT_COOKED = "Cucinarlo non ha aiutato molto.",
		PLANT_NORMAL =
		{
			GENERIC = "Mi chiedo che cosa sarà.",
			GROWING = "Una pianta osservata non cresce mai.",
			READY = "È ora di essere presa.",
			WITHERED = "Non ha più vita rimasta, eh?",
		},
		POMEGRANATE = "È troppo raffinato per me.",
		POMEGRANATE_COOKED = "Questo si accompagnerebbe bene alle frittelle.",
		POMEGRANATE_SEEDS = "Pieno di semi.",
		POND = "Non so nuotare!",
		POOP = "Non fare la cacca nel campo!",
		PUMPKIN = "Non mi piace mangiare le cose che crescono sul terreno.",
		PUMPKINCOOKIE = "Questo mi farà continuare a tagliare.",
		PUMPKIN_COOKED = "Le torte sono buone.",
		PUMPKIN_LANTERN = "È meglio non farla ribaltare.",
		PUMPKIN_SEEDS = "È un seme.",
		PURPLEGEM = "Non è niente che un bel taglio potrebbe sistemare.",
		RABBIT =
		{
			GENERIC = "Maledetti scoiattoli di terra...",
			HELD = "Mi sentirei male a mangiarlo.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Dubito che ci siano degli alberi laggiù.",
			SPRING = "Niente entra e niente esce.",
		},
		RATATOUILLE = "È come una foresta nella ciotola.",
		RAZOR = "Un vero boscaiolo non si fa mai la barba.",
		REDGEM = "Vedo al suo interno la morte impetuosa di migliaia di alberi.",
		RED_CAP = "Non lo so...",
		RED_CAP_COOKED = "Solo se ho davvero fame.",
		RED_MUSHROOM =
		{
			GENERIC = "È un fungo rosso.",
			INGROUND = "Hanno i propri tempi.",
			PICKED = "Credo di averlo rotto.",
		},
		REEDS =
		{
			BURNING = "Il fuoco mi rende nervoso.",
			GENERIC = "Canne.",
			PICKED = "Ricresceranno.",
		},
        RUBBLE = "Mobili rotti.",
		RESURRECTIONSTONE = "Non so se dovrei toccarlo.",
		ROBIN =
		{
			GENERIC = "Che borioso piccolo idiota.",
			HELD = "Non metterti comodo, pennuto.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Vola a sud o qualcosa del genere!",
			HELD = "Sta rubando il mio calore.",
		},
		ROBOT_PUPPET = "Sono intrappolati!",
		ROCK_LIGHT =
		{
			GENERIC = "Sembra un attimo crostoso.",
			OUT = "Sembra che possa rompersi.",
			LOW = "Serve altra... legna?",
			NORMAL = "Un fuoco che non ha bisogno di legna? Innaturale!",
		},
		ROCK = "Potrei romperla se provassi con tenacia.",
		ROCKS = "Sistemandole un po' si potrebbe fare un bell'inukshuk.",
        ROOK = "Uhm... la torre si muove in linea retta? Lo dimentico sempre.",
		ROPE = "Ottima per tenere insieme le cose.",
		ROTTENEGG = "Un pennuto in meno. Bene.",
		SANITYROCK =
		{
			ACTIVE = "C'è qualcosa di strano in quella roccia, eh?",
			INACTIVE = "Questo ha senso.",
		},
		SAPLING =
		{
			BURNING = "Oh! Aveva a malapena una possibilità!",
			WITHERED = "Con questo caldo, non diventerà mai grande abbastanza per essere tagliato!",
			GENERIC = "Voglio vederlo crescere in modo che possa abbatterlo.",
			PICKED = "Raccogliere non è divertente come tagliare.",
		},
		SEEDS = "Non sono alberi.",
		SEEDS_COOKED = "Questi li chiamiamo \"sorpresa del boscaiolo\".",
		SEWING_KIT = "Sono abbastanza bravo a cucire.",
		SHOVEL = "Scava una buca. Pianta un albero!",
		SILK = "I ragni mi fanno venire la pelle d'oca.",
		SKELETON = "Mi dispiace, amico.",
		SKELETON_PLAYER = "Questo è proprio snervante.",
		SKULLCHEST = "È spaventoso!",
		SMALLBIRD =
		{
			GENERIC = "Che cosa vuoi?",
			HUNGRY = "Vuole qualcosa.",
			STARVING = "Credo stia morendo di fame.",
		},
		SMALLMEAT = "Vorrei che fosse più grande.",
		SMALLMEAT_DRIED = "Solo un morso.",
		SPAT = "Mi ricorda di mamma!",
		SPEAR = "Gli manca la pesantezza di una buona e solida ascia.",
		SPIDER =
		{
			GENERIC = "Quello è il ragno più grosso che abbia mai visto!",
			SLEEPING = "Fai attenzione, adesso, eh?",
			DEAD = "Bene!",
		},
		SPIDERDEN = "Corpo di mille balene! Guarda quel coso!",
		SPIDEREGGSACK = "Perché vorresti portartelo appresso?",
		SPIDERGLAND = "Credo sia veleno.",
		SPIDERHAT = "È proprio una bellezza, non è così?",
		SPIDERQUEEN = "Non sei la mia regina!",
		SPIDER_WARRIOR =
		{
			GENERIC = "Li fanno gialli adesso?",
			SLEEPING = "Chi dorme non piglia lividi.",
			DEAD = "Ottimo!",
		},
		SPOILED_FOOD = "Oh, la sua parabola è stata discendente.",
		STATUEHARP = "Hai perso la testa, eh?",
		STATUEMAXWELL = "È piuttosto idiota, eh?",
		STEELWOOL = "Quello farà risplendere la tua ascia di nuovo.",
		STINGER = "Ahi! È a punta.",
		STRAWHAT = "Terrà il sole alla larga dalla mia capoccia.",
		STUFFEDEGGPLANT = "La mia cucina sta migliorando.",
		SUNKBOAT = "Quel legno ha visto giorni migliori.",
		SWEATERVEST = "Non è plaid ma andrà bene.",
		TAFFY = "Zuccheroso. Buono.",
		TALLBIRD = "Non mi fido nemmeno dei pennuti che non possono volare.",
		TALLBIRDEGG = "Cosa c'è qui?",
		TALLBIRDEGG_COOKED = "Ha il sapore della giustizia.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Troppo freddo per te?",
			GENERIC = "Si sta schiudendo.",
			HOT = "Piange?",
			LONG = "I pennuti non sono mai immediati.",
			SHORT = "Da un momento all'altro.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Gli dovrei rubare l'uovo per dargli una lezione.",
			PICKED = "Niente lì.",
		},
		TEENBIRD =
		{
			GENERIC = "Cresce per diventare un idiota, proprio come i suoi genitori.",
			HUNGRY = "Sei SEMPRE affamato?",
			STARVING = "Si sta dimenando dalla fame.",
		},
		TELEBASE =
		{
			VALID = "È pronto, ma io lo sono?",
			GEMS = "Ha bisogno di gemme, eh?",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Pronto a partire, eh?",
			GENERIC = "È... qualcosa di magico, credo.",
			LOCKED = "Ci sono delle parti mancanti, eh?",
			PARTIAL = "È quasi pronto, eh?",
		},
		TELEPORTATO_BOX = "Scatoloso, eh?",
		TELEPORTATO_CRANK = "Manovelloso, eh?",
		TELEPORTATO_POTATO = "Patatoso, eh?",
		TELEPORTATO_RING = "Anelloso, eh?",
		TELESTAFF = "Mi chiedo a cosa serva questo coso.",
		TENTACLE = "C'è un calamaro laggiù?",
		TENTACLESPIKE = "Ondeggia quando lo fai traballare.",
		TENTACLESPOTS = "Arrossisco!",
		TENTACLE_PILLAR = "È così grande!",
		TENTACLE_PILLAR_HOLE = "Non è rimasto neanche un ceppo!",
		TENTACLE_PILLAR_ARM = "Quelli sono dei calamari bambini?",
		TENTACLE_GARDEN = "Sono stufo di questi calamari!",
		TOPHAT = "È troppo raffinato.",
		TORCH = "Alberi delle fiaccole.",
		TRAP = "Lavorare meglio, eh?",
		TRAP_TEETH = "Questo sembra un po' grezzo.",
		TRAP_TEETH_MAXWELL = "Non sta giocando onestamente, eh?",
		TREASURECHEST_TRAP = "C'è qualcosa che non va con quello scrigno.",
		MOOSE_NESTING_GROUND = "Lo odio.",
		TRINKET_1 = "Ero abituato a giocare a quel gioco.",
		TRINKET_10 = "Mannaie per vecchietti.",
		TRINKET_11 = "Zitto, tu!",
		TRINKET_12 = "È tutto sfiorito.",
		TRINKET_2 = "Non è la cosa reale, eh?",
		TRINKET_3 = "Mi fa venire in mente una storiella che sentii una volta.",
		TRINKET_4 = "Non chiedermi.",
		TRINKET_5 = "Gli serve un braccio robotico, eh?",
		TRINKET_6 = "Non servono più a niente, eh?",
		TRINKET_7 = "Potrei suonarlo per ore!",
		TRINKET_8 = "Se trovo una tinozza, sono a posto.",
		TRINKET_9 = "Mi cucio i vestiti addosso quando li indosso.",
		TRUNKVEST_SUMMER = "Bello e ventilato.",
		TRUNKVEST_WINTER = "Questo potrebbe resistere agli inverni da dove vengo io, eh?",
		TRUNK_COOKED = "Penso che abbia bollito tutto il formaggio del naso.",
		TRUNK_SUMMER = "È abbastanza sottile.",
		TRUNK_WINTER = "È spessa e pelosa.",
		TURF_CARPETFLOOR = "Troppo di classe per i miei gusti.",
		TURF_CHECKERFLOOR = "Assomiglia a uno di quei gabinetti esterni nei quartieri residenziali.",
		TURF_DIRT = "Solo un po' di terra, eh?",
		TURF_FOREST = "Solo un po' di terra, eh?",
		TURF_GRASS = "Solo un po' di terra, eh?",
		TURF_MARSH = "Solo un po' di terra, eh?",
		TURF_ROAD = "Solo un po' di terra, eh?",
		TURF_ROCKY = "Solo un po' di terra, eh?",
		TURF_SAVANNA = "Solo un po' di terra, eh?",
		TURF_WOODFLOOR = "Una pavimentazione adatta a un re!",
		TURF_DRAGONFLY = "Il fuoco non appicca molto da queste parti, eh?",
		TURF_DESERTDIRT = "Just some ground, eh?",
		TURF_FUNGUS_GREEN = "Just some ground, eh?",
		TURF_FUNGUS_RED = "Just some ground, eh?",
		TURKEYDINNER = "Oggi è nuovamente il giorno del tacchino!",
		TWIGS = "Dovrei costruire una piccola ascia per tagliare questi.",
		BANANAPOP = "Preferisco le caramelle d'acero...",
		BISQUE = "Genuino.",
		CEVICHE = "Sarei un idiota a non mangiarlo.",
		SEAFOODGUMBO = "Non ce ne sono da dove vengo.",
		SURFNTURF = "Una buona mangiata, quello.",
		SHARKFINSOUP = "Nuoterà nel mio stomaco da ora in poi.",
		LOBSTERDINNER = "Preferirei il salmone.",
		LOBSTERBISQUE = "Sembra piuttosto buono per essere cibo di un'isola deserta.",
		JELLYOPOP = "Suppongo che questa sia l'isola dei dolci, eh?",
		UMBRELLA = "Questo mi terrà la barba asciutta, eh?",
		UNIMPLEMENTED = "Non sembra sicuro.",
		WAFFLES = "Preferisco le frittelle.",
		WALL_HAY_ITEM = "Potrei starnutire.",
		WALL_STONE = "Al salvo e al sicuro, eh?",
		WALL_STONE_ITEM = "Al salvo e al sicuro, eh?",
		WALL_RUINS = "Fatiscente ma ancora sicuro, eh?",
		WALL_RUINS_ITEM = "Eh, ancora pietre, non è così?",
		WALL_WOOD_ITEM = "Mi piace il suo aspetto!",
		WALL_MOONROCK = "Sembra bella e rubusta.",
		WALL_MOONROCK_ITEM = "Non è di grande utilità così.",
		WALRUS = "Oh no. Altri trichechi!",
		WALRUSHAT = "Mio nonno portava un cappello come questo.",
		WALRUS_CAMP =
		{
			EMPTY = "Questo non sarà sicuro con l'arrivo dell'inverno.",
			GENERIC = "I trichechi sono nelle vicinanze, eh?",
		},
		WALRUS_TUSK = "Aveva una carie, eh?",
		WASPHIVE = "Perché quelle api sono così arrabbiate?",
		WORMLIGHT_LESSER = "Più rugoso della parte inferiore del castoro.",
		WETGOOP = "Meglio di alcune delle cose che ho mangiato!",
        WHIP = "Mi auguro che quella non finisca a fare del male alle bestioline.",
		WINTERHAT = "Bel tocco, eh?",
		WORMHOLE =
		{
			GENERIC = "Quello ha l'aspetto di un deretano!",
			OPEN = "Non sono sicuro di volerlo osservare, eh?",
		},
		WORMHOLE_LIMITED = "Puzza come se fosse andato un po' a male, eh?",
		ACCOMPLISHMENT_SHRINE = "Mi sembra un po' esibizionista.",  
		BISHOP_CHARGE_HIT = "Ehi adesso!",        		
		LIVINGTREE = "Mi sento in conflitto, eh?",
		ICESTAFF = "Mi ricorda casa.",
		MOONROCKNUGGET = "È uh, una pietra lunare.",
        ROCK_MOON = "È uh, una pietra lunare.",

		------------------------------capy---------------------------------

		WOODLEGS_CAGE = "Va tutto bene lì dentro, amico?",

		TWISTER = "Madre natura fa i capricci!",
		WIND_CONCH = "Posso sentire i rintocchi di ventinove campane.",

		AERODYNAMICHAT = "È un cappello veloce, eh?",
		ANTIVENOM = "Un sapore terribile, ma funziona!",
		ARMORCACTUS = "Protezione piuttosto spinosa, eh?",
		ARMORLIMESTONE = "Mi fa sentire un duro.",
		ARMOROBSIDIAN = "Roba che scotta, eh?",
		ARMORSEASHELL = "Questo non sembra molto resistente.",
		ARMOR_LIFEJACKET = "Un po' di rassicurazione.",
		ARMOR_SNAKESKIN = "Mi sento così soave quando la indosso.",
		ARMOR_WINDBREAKER = "Mi sento a casa con questo, eh.",
		ARMOUREDBOAT = "Più sicuro di così nel mare non può andare!",
		BABYOX = "È tutto barba.",
		BALLPHIN = "Ehi amico, sai fare dei trucchetti?",
		BAMBOO = "Sembra un albero che fa la dieta, eh?",
		BAMBOOTREE =
		{
			BURNT = "Bruciato come la pancetta, eh?",
			CHOPPED = "È stato un buon taglio.",
			GENERIC = "Lucy si è lasciata prendere un po' troppo la mano.",
		},
		BERMUDATRIANGLE = "Un po' spettrale, eh?",
		BIGFISHINGROD = "Cammini a testa alta e porti una grande canna da pesca, eh?",
		BIOLUMINESCENCE = "È come l'aurora boreale.",
		BLOWDART_FLUP = "Ti acciufferò!",
		BLOWDART_POISON = "Mira alla vena principale, eh?",
		BLUBBER = "Smetti di fare bolle.",
		BLUBBERSUIT = "Non mi abbellisce molto.",
		BOATCANNON = "Questo li farà saltare in aria alla grande!",
		BOATREPAIRKIT = "Per rattoppare, eh?",
		BOAT_LANTERN = "È una luce per la barca.",
		BOAT_TORCH = "Posso andare a pesca di notte.",
		BOTTLELANTERN = "Tutto bene lì dentro, amici brillanti?",
		BRAINJELLYHAT = "Mi sento un po' arguto quando lo indosso.",
		BUOY = "Galleggiare attraverso la vita. Ha avuto l'idea giusta.",
		BURIEDTREASURE = "È arrivato il momento di scavare!",
		BUSH_VINE =
		{
			BURNT = "Non ci tornerà più.",
			CHOPPED = "Non è divertente come un albero, ma è stata una buona tagliata comunque.",
			GENERIC = "Sta chiedendo di essere tagliato.",
		},
		CAPTAINHAT = "Spero di non dover colare a picco con la nave.",
		CARGOBOAT = "Preferisco i pescherecci da diporto.",
		CHIMINEA = "È come un'armatura per il fuoco.",
		CLOTHSAIL = "Questo mi aiuterà a spostarmi.",
		COCONADE =
		{
			BURNING = "È ora di correre!",
			GENERIC = "Sto per fare dei danni seri con questa.",
		},
		COCONUT = 
		{
		    GENERIC = "È solo una noce di cocco.",
		    PLANTED = "Ora è una piccola palma.",
		},
		COCONUT_COOKED = "Pronta da mangiare.",
		COCONUT_HALVED = "Uno per me e uno per Lucy.",
		COFFEE = "Na tazzulella e cafè.",
		COFFEEBEANS = "Dovrei cuocerli.",
		COFFEEBEANS_COOKED = "I canadesi amano il caffè.",
		COFFEEBOT = "Fa il caffè, non è vero?",
		COFFEEBUSH =
		{
			BARREN = "Sembri un po' giù, amico.",
			GENERIC = "Chicchi di caffè!",
			PICKED = "Vorrei che avesse più chicchi.",
			WITHERED = "Gli farebbe bene un caffettuccio.",
		},
		CORAL = "Forse potrei frantumarlo per farne qualcos'altro.",
		CORALREEF = "Maturi per essere raccolti.",
		CORAL_BRAIN = "Un cervellone.",
		CORAL_BRAIN_ROCK = "Cosa saresti, una specie di arguto?",
		CRAB =
		{
			GENERIC = "Forse potremmo essere amici?",
			HIDDEN = "Non puoi nasconderti per sempre, amico!",
		},
		CRABHOLE = "Ecco dove vivono i miei amici granchi.",
		CRATE = "Ecco un contenitore.",
		CUTLASS = "È una piccola tagliatrice molto precisa, eh?",
		DEAD_SWORDFISH = "Mi dispiace.",
		DEPLETED_BAMBOOTREE = "Ricresci così che possa abbatterti nuovamente!",
		DEPLETED_BUSH_VINE = "Credo che ricrescerà.",
		DEPLETED_GRASS_WATER = "Non mi piace aspettare.",
		DEVTOOL_NODEV = "Che cosa curiosa.",
		DOUBLE_UMBRELLAHAT = "Doppia protezione!",
		DOYDOY = "Non troppo sicuro di come questa cosa sopravviva, eh.",
		DOYDOYBABY = "È sudicio.",
		DOYDOYEGG = "Mi sembra una buona mangiata.",
		DOYDOYEGG_COOKED = "Servirebbe un lato della pancetta canadese.",
		DOYDOYEGG_CRACKED = "Beh, non si può fare più niente ora.",
		DOYDOYFEATHER = "Non è come il piumaggio dell'orgogliosa oca canadese.",
		DOYDOYNEST = "Quei pennuti sporcaccioni si riproducono qui.",
		DRAGOON = "Sembra un po' caldo sotto il cappello!",
		DRAGOONDEN = "Non sembra una diga del castoro.",
		DRAGOONEGG = "Ummm. Sembra sospetto.",
		DRAGOONHEART = "Il cuore della bestia.",
		DRAGOONSPIT = "Cafone.",
		DUBLOON = "Ho colpito l'oro!",
		DUG_BAMBOOTREE = "Tu vieni con me!",
		DUG_BUSH_VINE = "Sei pronto per fare un viaggetto?",
		DUG_COFFEEBUSH = "Ti porterò ovunque con me.",
		DUG_ELEPHANTCACTUS = "Vai nella mia direzione?",
		EARRING = "Non dovrebbero essercene due?",
		ELEPHANTCACTUS = "È pungente, eh?",
		ELEPHANTCACTUS_ACTIVE = "Attento! Quella pianta sta per attaccare!",
		ELEPHANTCACTUS_STUMP = "Questo cactus ha dato il massimo. Adesso è stanco.",
		FABRIC = "Come posso tingerlo di plaid?",
		FEATHERSAIL = "Suppongo che ne sia valsa la pena di toccare tutte quelle grandi piume.",
		FISHINHOLE = "Se solo fosse un po' più freddo, sarebbe un posto perfetto per la pesca nel ghiaccio.",
		FISH_RAW = "Preferirei il salmone.",
		FISH_RAW_SMALL = "Spero di non attrarre gli orsi.",
		FISH_RAW_SMALL_COOKED = "Mi sembra buono.",
		FLAMEGEYSER = "Uao, raffreddalo!",
		FLOTSAM = "Solo un mucchio di spazzatura.",
		FLUP = "Disgustoso.",
		FRESHFRUITCREPES = "Posso averlo con lo sciroppo d'acero?",
		FROG_POISON = "Tieniti il tuo sputo velenoso per te stesso, eh!",
		GASHAT = "Niente puzza quando la indosso.",
		GOLDENMACHETE = "Taglia e scintilla!",
		GRASS_WATER = "Un po' umido, eh?",
		HAIL_ICE = "E credi che questo sia freddo? Che tenero.",
		HOUNDFIRE = "Brucia così intensamente!",
		ICEMAKER =
		{
			HIGH = "La furia del ghiaccio! Mi ricorda casa.",
			LOW = "Si affievolisce.",
			NORMAL = "Funziona senza intoppi.",
			OUT = "È finita.",
			VERYLOW = "Si sta per scassare.",
		},
		INVENTORYGRAVE = "Credo che qualcuno sia stato qua. Non più.",
		INVENTORYMOUND = "Credo che qualcuno sia stato qua. Non più.",
		IRONWIND = "Cosa veloce!",
		JELLYFISH = "È una medusa, non lo sapevi?",
		JELLYFISH_COOKED = "Credo che non possa essere più commestibile di così.",
		JELLYFISH_DEAD = "La vita è stata svuotata da quello, eh?",
		JELLYFISH_PLANTED = "Un piccolo amico medusa.",
		JELLYJERKY = "Carne essiccata! Il cibo della mia gente.",
		JUNGLETREE =
		{
			BURNING = "Che spreco di ceppo da tagliare.",
			BURNT = "Che spreco.",
			CHOPPED = "Quelli sì che erano bei tempi.",
			GENERIC = "Il richiamo dell'albero è musica per le mie orecchie!",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Questo potrebbe diventare un buon albero per essere tagliato.",
            PLANTED = "E adesso aspettiamo.",
        },
		KNIGHTBOAT = "Quel tipo ha un problema di comportamento!",
		KRAKEN = "Per Lucy!",
		KRAKENCHEST = "Mostrami il bottino!",
		KRAKEN_TENTACLE = "Si aggrappa un po' troppo, non credi?",
		LAVAPOOL = "Sono una goccia di sudore solo a guardarlo.",
		LIMESTONE = "Ho frantumato quel bel corallo per realizzare questo.",
		LIMPETROCK =
		{
			GENERIC = "Potrei farci uno spuntino.",
			PICKED = "Solo una grande roccia, eh?",
		},
		LIMPETS = "Una specie di lumaca da acqua.",
		LIMPETS_COOKED = "La cena è pronta.",
		TREEGUARD = "Ho fatto arrabbiare la foresta!",
		LIVINGJUNGLETREE = "Vuole che lo tagli, lo capisco.",
		LOBSTER = "Con un po' di burro sciolto sarebbe delizioso.",
		LOBSTERHOLE = "Vieni fuori, cosetto.",
		LOBSTER_DEAD = "È proprio finita.",
		LOBSTER_DEAD_COOKED = "Una buona mangiata!",
		LOGRAFT = "La mia specialità!",
		LUGGAGECHEST = "Qualcosa di buono dentro?",
		MACHETE = "Ooh, è una cosa per tagliare.",
		MAGIC_SEAL = "Pulsa di potere, eh.",
		MAGMAROCK = "Sistemandole un po' si potrebbe fare un bell'inukshuk.",
		MAGMAROCK_FULL = "Sistemandole un po' si potrebbe fare un bell'inukshuk.",
		MAGMAROCK_GOLD = "Sembra che ne valga la pena scavarci.",
		MAGMAROCK_GOLD_FULL = "Sembra che ne valga la pena scavarci.",
		MANGROVETREE = "Sembra gustoso!",
		MANGROVETREE_BURNT = "Mi duole il cuore orgoglioso al solo guardarlo.",
		MARSH_PLANT_TROPICAL = "È una piantina.",
		MERMFISHER = "Non conosco quel tipo.",
		MERMHOUSE_FISHER = "Preferirei una casetta di legno.",
		MESSAGEBOTTLE = "Qualcuno sta cercando di parlare con me?",
		MESSAGEBOTTLEEMPTY = "Cosa c'era?",
		MONKEYBALL = "Togliti quel ghigno dal muso!",
		MONSTERTARTARE = "Non c'è niente altro da mangiare?",
		MOSQUITOSACK_YELLOW = "Puzza un po' di acido.",
		MOSQUITO_POISON = "È impregnata di malattia.",
		MUSSEL = "Quelle sembrano buone da mangiare, eh?",
		MUSSELBOUILLABAISE = "Il pasto migliore che abbia visto da un po', eh?",
		MUSSEL_COOKED = "Sembrano gustose!",
		MUSSEL_FARM =
		{
			GENERIC = "Vogliono essere cibo.",
			STICKPLANTED = "Prevedo una cena a base di cozze nel mio futuro.",
		},
		MUSSEL_STICK = "Le cozze adorano questa cosa.",
		MYSTERYMEAT = "Cosa diavolo è quello!",
		NEEDLESPEAR = "Ahi. È tagliente.",
		OBSIDIAN = "È un po' tostata.",
		OBSIDIANAXE = "Attenta, Lucy, hai concorrenza! (Scherzo!)",
		OBSIDIANCOCONADE = "Provoca una bella botta.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Dovrei andare a tagliare della legna per quello, eh?",
			GENERIC = "Sembra il posto perfetto per accendere un fuoco.",
			HIGH = "Sto usando troppa legna troppo velocemente!",
			LOW = "Ci dovrebbe essere della legna qui intorno da qualche parte.",
			NORMAL = "Mmmm. Odore legnoso.",
			OUT = "Se solo avessi un po' di legna.",
		},
		OBSIDIANMACHETE = "Bruciacchia tutto ciò che tocca.",
		OBSIDIANSPEARGUN = "Accende la roba sul fuoco, eh.",
		OBSIDIAN_WORKBENCH = "Posso realizzare alcuni strumenti di fuoco qui, eh?",
		OCTOPUSCHEST = "Grazie per la roba, ragazzo!",
		OCTOPUSKING = "Come butta da quelle parti, amico?",
		OX = "Il poveraccio è il bersaglio di ogni giogo.",
		OXHAT = "Questo cappello si addice a un settentrionale.",
		OX_FLUTE = "Sono piuttosto un chitarrista.",
		OX_HORN = "Era attaccato ad un bue. Non più.",
		PACKIM = "Lo posso tollerare.",
		PACKIM_FISHBONE = "Farebbe meglio a non attirare i parassiti piumati.",
		PALMLEAF = "Lo uso per sventolarmi.",
		PALMLEAF_HUT = "Il miglior rifugio che un taglialegna possa desiderare.",
		PALMTREE =
		{
			BURNING = "Che spreco di ceppo da tagliare.",
			BURNT = "Che spreco.",
			CHOPPED = "Quelli sì che erano bei tempi.",
			GENERIC = "È legna per i miei depositi.",
		},
		PARROT = "Sciò, sporca sacca di penne!",
		PARROT_PIRATE = "Preferirei evitare i convenevoli con un cervello da gallina.",
		PEACOCK = "Che cosa ridicola. Bah!",
		PEG_LEG = "Posso tagliarlo?",
		PIGTENT = "Sembra essere una specie di tenda.",
		PIKE_SKULL = "È un po' pacchiano, eh.",
		PIRATEGHOST = "Forse è amichevole?",
		PIRATEHAT = "È la vita del pirata per me ora.",
		PIRATEPACK = "Una sacca per il mio bottino.",
		PIRATIHATITATOR =
		{
			BURNT = "Non è più così divertente.",
			GENERIC = "È un aggeggio curioso, eh?",
		},
		POISONHOLE = "Penso che gli starò alla larga.",
		PORTAL_SHIPWRECKED = "Sembra senza scampo.",
		PRIMEAPE = "Questo tipo è un po' arguto.",
		PRIMEAPEBARREL = "Dove dormono gli arguti.",
		RAFT = "Una barchetta pietosa.",
		RAWLING = "Che pazzo!",
		REDBARREL = "Sembra pericoloso.",
		RELIC =
		{
			BROKEN = "Non ho intenzione di aggiustarlo.",
			GENERIC = "Di cosa si tratta?",
		},
		ROCK_CHARCOAL = "Mi fa diventare le mani tutte fuligginose.",
		ROCK_OBSIDIAN = "C'è un fuoco che brucia al suo interno.",
		ROWBOAT = "Alimentato da olio di gomito.",
		SAIL = "Ho il vento in poppa.",
		SAIL_STICK = "I venti del Nord sono a mia disposizione.",
		SAND = "Sabbioso.",
		SANDBAG = "Costruire dighe è la mia specialità.",
		SANDBAGSMALL = "Costruire dighe è la mia specialità.",
		SANDBAGSMALL_ITEM = "Una piccola diga portatile.",
		SANDBAG_ITEM = "Una diga portatile.",
		SANDHILL = "È un gran mucchio di sabbia.",
		SAND_CASTLE =
		{
			GENERIC = "Chi lo sapeva che la sabbia potesse sembrare così bella.",
			SAND = "Sembra buono.",
		},
		SEAGULL = "Parassiti del cielo.",
		SEAGULL_WATER = "Parassiti del mare.",
		SEASACK = "È per conservare di miei tesori.",
		SEASHELL = "Mi fa venire voglia di tornare a fare l'artigiano.",
		SEASHELL_BEACHED = "Una bella conchiglia.",
		SEATRAP = "Non vedo l'ora di una cena a base di aragostra.",
		SEAWEED = "È viscido.",
		SEAWEED_COOKED = "Ha una consistenza strana.",
		SEAWEED_DRIED = "Si attacca alla mia lingua.",
		SEAWEED_PLANTED = "Ecco alcune alghe, eh?",
		SHADOWSKITTISH_WATER = "Accidenti!",
		SHARKITTEN = "Solo un grande dolce gattino.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Mi sembra di sentir miagolare...",
			INACTIVE = "Mi sembra solo un mucchio di sabbia, eh?",
		},
		SHARK_FIN = "Sono sicuro che lo squalo non ne sente la mancanza.",
		SHARK_GILLS = "I polmoni del pesce.",
		SHARK_TEETHHAT = "È un cappello fatto di denti.",
		SHARX = "Non ci farò amicizia, questo è sicuro.",
		SHIPWRECKED_ENTRANCE = "Sono pronto per l'avventura, eh!",
		SHIPWRECKED_EXIT = "Ci vediamo più tardi, amico.",
		SLOTMACHINE = "Lo spirito del Nord guida il mio destino.",
		SLURPERPELT = "Dov'è il commerciante di pellicce più vicino?",
		SNAKE = "Non è malaccio per essere un serpente.",
		SNAKEDEN =
		{
			BURNT = "Non ci tornerà più.",
			CHOPPED = "Non è divertente come un albero, ma è stata una buona tagliata comunque.",
			GENERIC = "Sta chiedendo di essere tagliato.",
		},
		SNAKEOIL = "Continuano a caderci!",
		SNAKESKIN = "Sono sicuro che il serpente non ne avesse bisogno.",
		SNAKESKINHAT = "Questo sarebbe un \"berretto\" o una \"berretta\"?",
		SNAKESKINSAIL = "Navigare con stile.",
		SNAKE_FIRE = "Sembra un po' surriscaldato.",
		SNAKE_POISON = "Preferirei non farmi mordere da quello.",
		SOLOFISH = "Bel cagnolino.",
		SPEARGUN = "Questa sì che è un'arma impressionante!",
		SPEARGUN_POISON = "Quest'arma impressionante avvelena i miei nemici!",
		SPEAR_LAUNCHER = "Questa sì che è un'arma impressionante!",
		SPEAR_OBSIDIAN = "Questa è una lancia focosa.",
		SPEAR_POISON = "Questa lancia ha una marcia in più.",
		SPOILED_FISH = "Penso che sia il momento di buttarlo.",
		STUNGRAY = "Puzza peggio di un'alce impregnata d'acqua!",
		SUNKEN_BOAT =
		{
			ABANDONED = "Che spreco di legna buona.",
			GENERIC = "Ehi amico.",
		},
		SUNKEN_BOAT_BURNT = "Quello non galleggerà più, eh.",
		SUNKEN_BOAT_TRINKET_1 = "È un po' troppo raffinato per i miei gusti.",
		SUNKEN_BOAT_TRINKET_2 = "Quella barca sembra un po' piccola.",
		SUNKEN_BOAT_TRINKET_3 = "Non riesco a immaginare che questo serva a qualcosa.",
		SUNKEN_BOAT_TRINKET_4 = "Un giocattolo per gli arguti.",
		SUNKEN_BOAT_TRINKET_5 = "Non è della mia taglia, quello.",
		SUPERTELESCOPE = "Facile come guardare lungo la pianura di Alberta.",
		SWEETPOTATOSOUFFLE = "Molto stravagante!",
		SWEET_POTATO = "Lo cucinerò per bene.",
		SWEET_POTATO_COOKED = "Ci vorrebbe qualche marshmallow.",
		SWEET_POTATO_PLANTED = "Sembra una patata raffinata, eh?",
		SWEET_POTATO_SEEDS = "Mi sarebbero più utili se piantati.",
		SWIMMINGHORROR = "Non voglio avere niente a che fare con quello, eh!",
		SWORDFISH = "È un pesce appuntito.",
		TELEPORTATO_SW_BASE = "Nulla che non possa essere risolto con del nastro adesivo.",
		TELEPORTATO_SW_BOX = "Questo servirà a qualcosa, eh?",
		TELEPORTATO_SW_CRANK = "Dovrei conservarlo.",
		TELEPORTATO_SW_POTATO = "Non sembra per niente una patata. E io conosco le patate.",
		TELEPORTATO_SW_RING = "Una specie di anello, eh?",
		TELESCOPE = "Aiuta la mia vista, eh?",
		THATCHPACK = "Ora posso portare altro legno delizioso.",
		TIDALPOOL = "Sembra un luogo di ritrovo popolare per i pesci.",
		TIDAL_PLANT = "Quella cosa non produce legna.",
		TIGEREYE = "Non lo sai che fissare è da maleducati?",
		TIGERSHARK = "Sarebbe carino se non provasse a mangiarmi.",
		TOUCAN = "Quella cosa sembra sfuggente.",
		TRAWLNET = "I pesci dovrebbero nuotarci dentro.",
		TRAWLNETDROPPED =
		{
			GENERIC = "Venite a me, pesci!",
			SOON = "Quasi arrivata!",
			SOONISH = "Sta calando.",
		},
		TREECLUMP = "Mi stai chiedendo di tagliarti per bene, amico.",
		TRIDENT = "Si fanno dei bocconi con questa forchetta gigante, eh?!",
		TRINKET_13 = "È sicuro da consumare?",
		TRINKET_14 = "È quella la mia faccia?",
		TRINKET_15 = "Questa chitarra è piccola!",
		TRINKET_16 = "È solo una piastrina di metallo, eh?",
		TRINKET_17 = "Non è la mia taglia.",
		TRINKET_18 = "È rotto.",
		TRINKET_19 = "Chissà a che cosa serve?",
		TRINKET_20 = "È un po' troppo raffinato per i miei gusti.",
		TRINKET_21 = "Quella barca sembra un po' piccola.",
		TRINKET_22 = "Non sembra per niente utile.",
		TRINKET_23 = "Non ho idea di cosa sia.",
		TROPICAL_FISH = "Sei pronto a diventare fish and chips?",
		TUNACAN = "Lucy la aprirà.",
		TURBINE_BLADES = "Mi fa girare la testa.",
		TURF_SANDY = "Solo un po' di terra, eh?",
		TURF_ASH = "Solo un po' di terra, eh?",
		TURF_BEACH = "Solo un po' di terra, eh?",
		TURF_DESERTDIRT = "Solo un po' di terra, eh?",
		TURF_FUNGUS_GREEN = "Solo un po' di terra, eh?",
		TURF_FUNGUS_RED = "Solo un po' di terra, eh?",
		TURF_JUNGLE = "Solo un po' di terra, eh?",
		TURF_MAGMAFIELD = "Solo un po' di terra, eh?",
		TURF_MEADOW = "Solo un po' di terra, eh?",
		TURF_SNAKESKINFLOOR = "Solo un po' di terra, eh?",
		TURF_SWAMP = "Solo un po' di terra, eh?",
		TURF_TIDALMARSH = "Solo un po' di terra, eh?",
		TURF_VOLCANO = "Solo un po' di terra, eh?",
		TWISTER_SEAL = "Tenero piccoletto.",
		VENOMGLAND = "Ha un odore curioso, eh?",
		VINE = "Ahimè. Non è un albero.",
		VOLCANO = "È straordinario!",
		VOLCANOSTAFF = "La potenza del vulcano è nella mia mano.",
		VOLCANO_ALTAR =
		{
			GENERIC = "Non c'è niente da fare.",
			OPEN = "Mi sento come se volesse qualcosa da me.",
		},
		VOLCANO_ALTAR_BROKEN = "Completamente rotto, quello.",
		VOLCANO_ALTAR_TOWER = "Quello è un raccapricciante pezzo di roccia, quello.",
		VOLCANO_EXIT = "È ora di filare via!",
		VOLCANO_SHRUB = "Beh, non è sicuramente un sempreverde.",
		WALLYINTRO_DEBRIS = "Dove sono?",
		WALL_LIMESTONE = "Quello è un muro.",
		WALL_LIMESTONE_ITEM = "Perché costruire muri quando si potrebbero costruire ponti?",
		WATERMELON_SEEDS = "Forse potrei piantarli.",
		WATERYGRAVE = "Spero di non finire mai in uno di quelli.",
		WHALE_BLUE = "Attacca!",
		WHALE_BUBBLES = "So che sei lì sotto, amico.",
		WHALE_CARCASS_BLUE = "È molto grande, eh.",
		WHALE_CARCASS_WHITE = "Beh, ora è morta.",
		WHALE_TRACK = "Sono sulla retta via.",
		WHALE_WHITE = "È forte, e molto libera.",
		WILBUR_CROWN = "Sfarzosa.",
		WILBUR_UNLOCK = "Mi sono fatto un nuovo amico.",
		WILDBORE = "Sembra proprio un idiota.",
		WILDBOREHEAD = "Che sfortuna, amico.",
		WILDBOREHOUSE = "Sembra una casa piena di idioti.",
		WOODLEGSBOAT = "Raffinato, ma sembra un po' lento.",
		WOODLEGSHAT = "Ci andrebbero un paio di orecchie a sventola.",
		WOODLEGSSAIL = "Una vela alla moda, quella.",
		WOODLEGS_KEY1 = "Che cosa potrebbe aprire?",
		WOODLEGS_KEY2 = "Una chiave per cosa?",
		WOODLEGS_KEY3 = "Dovrei conservarla, eh?",
		WRECK = "Uno spreco di buon legno.",
		CALIFORNIAROLL = "Mi sento come uno di Vancouver.",

	},
	DESCRIBE_GENERIC = "Che cos'è, eh?",
	DESCRIBE_TOODARK = "È buio!",
	DESCRIBE_SMOLDERING = "È in procinto di andare in fiamme, eh?",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Maturo. O non ancora maturo?",
	},
}
