return {

	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "벌써 나보다 좋은 상태네.",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "밤에 이것을 하지는 않겠어.",
			GENERIC = "면도칼을 대지 않겠어.",
			NOBITS = "이미 모든 것을 잃었지.",
		},
		WRITE =
        {
            GENERIC = "안... 돼.",
        },
		STORE =
		{
			GENERIC = "들어가지 않지.",
			NOTALLOWED = "매너를 지켜야겠네.",
		},
		RUMMAGE =
        {   
            GENERIC = "삶은 다 어렵기만 한 것인가?", 
        },
        CHANGEIN =
        {
            GENERIC = "무의미해.",
            BURNING = "금방 옷 갈아입기는 글렀네.",
        },
		COOK =
        {
            GENERIC = "아. 아무도 나에게 요리를 가르치지 않았어.",
            TOOFAR = "너무... 멀군...",
        },
        GIVE =
        {
            DEAD = "그들이 간 곳에는 물건이 필요 없어.",
            SLEEPING = "나중에 돌아오지...",
            BUSY = "나에게 집중하기에는 너무 바빠...",
        },
        TEACH =
        {
            KNOWN = "이미 아는 지식이야...",
            CANTLEARN = "내가 이해할 수 없는 지식이야...",
        },
	},
	ACTIONFAIL_GENERIC = "아무 것도 제대로 할 수 없네.",
	ANNOUNCE_MAGIC_FAIL = "아무 것도 못해. 쳇.",
	ANNOUNCE_ADVENTUREFAIL = "모든 죽음이 같은 것은 아니야.",
	ANNOUNCE_BOOMERANG = "이런! 카르마였네.",
	ANNOUNCE_CHARLIE = "마귀! 나와라!",
	ANNOUNCE_CHARLIE_ATTACK = "공격당했어!",
	ANNOUNCE_COLD = "뼛속까지 춥네.",
	ANNOUNCE_HOT = "비참하게 더워.",
	ANNOUNCE_WORMS = "엇, 떠나야겠군.",
	ANNOUNCE_CRAFTING_FAIL = "필요한 재료가 없네.",
	ANNOUNCE_DUSK = "곧 어둠이 깔릴 거야. 준비해야 해.",
	ANNOUNCE_EAT =
	{
		GENERIC = "냠!",
		PAINFUL = "먹을 수 있는 것이 아니었어.",
		SPOILED = "수명이 끝나가는 음식이었어.",
		STALE = "안 싱싱했나?",
		INVALID = "절대로 하지 않겠어.",
		YUCKY = "먹기가 두려워.",
	},
	ANNOUNCE_ENTER_DARK = "어둠이 날 삼켰어.",
	ANNOUNCE_ENTER_LIGHT = "그리고 빛이 있으라!",
	ANNOUNCE_HOUNDS = "개가 짖고 있어.",
	ANNOUNCE_HUNGRY = "텅 비어 있어.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "근처에서 짐승의 존재감이 느껴져.",
	ANNOUNCE_HUNT_LOST_TRAIL = "흔적이 이어지는 곳이 없어.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "흔적은 없고, 혼란스럽기만 해.",
	ANNOUNCE_INV_FULL = "더 들 수 없어.",
	ANNOUNCE_KNOCKEDOUT = "다시 깨어나네. 한숨.",
	ANNOUNCE_NOHUNGERSLEEP = "배가 내 마음처럼 비어서 잘 수가 없어.",
	ANNOUNCE_PECKED = "내 인내심을 시험하는 거야.",
	ANNOUNCE_QUAKE = "땅이 떨리네. 나를 완전히 삼킬까?",
	ANNOUNCE_THORNS = "이런! 나처럼 가시투성이야.",
	ANNOUNCE_TORCH_OUT = "어둠이 돌아왔어!",
	ANNOUNCE_FAN_OUT = "팬이 마지막 숨을 거두었어.",
    ANNOUNCE_COMPASS_OUT = "지구의 힘을 더 이상 느끼지 못해.",
	ANNOUNCE_TRAP_WENT_OFF = "뭐야.",
	ANNOUNCE_WORMHOLE = "다시 한 번 세계에 등장하네.",
	ANNOUNCE_CANFIX = "\n내 마음과는 달리 이것은 고칠 수 있어.",
	ANNOUNCE_ACCOMPLISHMENT = "다 덧없어.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "이것도 언젠가는 잊혀지겠네.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "더 필요해.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "죽음에 가깝지만 멀어.",
	ANNOUNCE_BEES = "벌이야! 내가 알러지가 있을지도 몰라!",
	ANNOUNCE_DEERCLOPS = "나쁠 것 같아.",
	ANNOUNCE_FREEDOM = "자유야. 좋을까.",
	ANNOUNCE_HIGHRESEARCH = "공허를 바라보았는데 깊고 어두웠지.",
	ANNOUNCE_LOWRESEARCH = "시시한 지식이야...",
	ANNOUNCE_MOSQUITOS = "모기! 나의 정맥이 너의 만찬!",
	ANNOUNCE_NODANGERSLEEP = "잘 수 없어, 죽여야 하니까.",
	ANNOUNCE_NODAYSLEEP = "해가 싫어. 잘 수 없어.",
	ANNOUNCE_NODAYSLEEP_CAVE = "아직 안 피곤해.",
	ANNOUNCE_NOSLEEPONFIRE = "사라지는 좋은 방법일지도 몰라.",
	ANNOUNCE_NODANGERSIESTA = "낮잠 잘 수는 없어. 죽음이 가까워.",
	ANNOUNCE_NONIGHTSIESTA = "이것보단 텐트 안에 있겠어.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "이것보단 텐트 안에 있겠어.",
	ANNOUNCE_NOHUNGERSIESTA = "배가 내 마음처럼 공허해. 낮잠을 잘 수 없어.",
	ANNOUNCE_SHELTER = "자연이 유용한 점이 있네.",
	ANNOUNCE_BURNT = "이런! 지옥 불이야!",
	ANNOUNCE_TOOL_SLIP = "어차피 필요 없었어.",
	ANNOUNCE_DAMP = "축축하고 처량해.",
	ANNOUNCE_WET = "울면서 잠들 때보다 더 젖었어.",
	ANNOUNCE_WETTER = "영원한 습기와 슬픔이야.",
	ANNOUNCE_SOAKED = "물의 묵시록이군.",

	ANNOUNCE_OTHER_WORLD_PLANT = "여기에 속하지 않아. 나처럼.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"시간의 흐름은 모든 것을 흐릿하게 만들어...",
	},
	ANNOUNCE_BOAT_DAMAGED = "이 배는 손상을 입었어. 이해해.",
	ANNOUNCE_BOAT_SINKING = "곧 물의 무덤을 보게 되겠네.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "심연에 항복하겠어!",
	ANNOUNCE_CRAB_ESCAPE = "죽음을 하루 미뤘네.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "죽음의 아가리로 들어가는 것을 봐봐!",
	ANNOUNCE_MAPWRAP_RETURN = "다시 세상으로 돌아왔어.",
	ANNOUNCE_MAPWRAP_WARN = "어쩌면 지구의 가장자리에서 항해해 갈 수 있을지도 모르겠어.",
	ANNOUNCE_TREASURE = "보물 지도... 신나라!",
	ANNOUNCE_MORETREASURE = "다른 지도... 덜 신나라!",
	ANNOUNCE_NO_TRAP = "이제 잘 된 것이 있네.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "먼 땅을 위한 가이드야.",
	ANNOUNCE_RESEARCH = "이 끔찍한 세계에 대한 지식이 늘어났어.",
	ANNOUNCE_SHARX = "이단자가 나를 쫓고 있어!",
	ANNOUNCE_TRAWL_FULL = "바다가 보물을 주네.",
	ANNOUNCE_UNIMPLEMENTED = "오호! 시간이 더 필요하네.",
	ANNOUNCE_VOLCANO_ERUPT = "폭발이 아니라 분화야!",
	ANNOUNCE_WAVE_BOOST = "기쁨...",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "거대한 짐승이 모습을 드러냈어.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "이스마엘처럼 나의 사냥은 저주 받았어.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "널 찾겠어, 짐승!",

	BATTLECRY =
	{
		GENERIC = "죽음이 널 찾아올 거야!",
		PIG = "죽음의 포옹을 맛봐라!",
		PREY = "당해라, 벌레!",
		SPIDER = "너를 저승으로 보내겠어!",
		SPIDER_WARRIOR = "너에게 종말을 전해 주겠어!",
	},
	COMBAT_QUIT =
	{
		PIG = "오늘은 죽음을 피했구나, 짐승.",
		PREY = "너는 이제 삶이라는 선물을 더 소중히 여기겠지.",
		SPIDER = "널 살려주는 것을 고맙게 여겨.",
		SPIDER_WARRIOR = "잊지 않겠어.",
		GENERIC = "넌 살 거야. 지금은.",
	},
	DESCRIBE =
	{
		INVENTORYGRAVE = "내가 함께 누워도 괜찮을까?",
		INVENTORYMOUND = "내가 같이 누워도 될까?",
		LIMPETS_COOKED = "우울해.",
		GLOMMER = "넌 행복한 털공이야. 죽어.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "밤의 꽃이야.",
        	DEAD = "밤의 꽃조차 죽어.",
        },
        GLOMMERWINGS = "날개도 작고 명랑해.",
        GLOMMERFUEL = "털공 배설물이네.",
        BELL = "죽은 자를 깨워라.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "저게 뭐야?!",
        	EMPTY = "내가 죽였어.",
    	},
		WEBBERSKULL = "이게 차라리 낫지.",

		LAVA_POND_ROCK = "내 마음처럼 차갑고 딱딱해...",
		LAVA_POND_ROCK2 = "내 마음처럼 차갑고 딱딱해...",
		LAVA_POND_ROCK3 = "내 마음처럼 차갑고 딱딱해...",
		LAVA_POND_ROCK4 = "내 마음처럼 차갑고 딱딱해...",
		LAVA_POND_ROCK5 = "내 마음처럼 차갑고 딱딱해...",
		LAVA_POND_ROCK6 = "내 마음처럼 차갑고 딱딱해...",
		LAVA_POND_ROCK7 = "내 마음처럼 차갑고 딱딱해...",

		MOLE =
		{
			HELD = "가족이랑 헤어지니 어떤 기분이야?",
			UNDERGROUND = "이 끔찍한 장소를 피하고 지하에 있어.",
			ABOVEGROUND = "어두운 곳으로 돌아가.",
		},
		MOLEHILL = "아래로 깊숙이.",
		MOLEHAT = "그것들이 이것을 보는 거야.",
		NIGHTSTICK = "어둠 속의 위험이네.",
		RABBITHOUSE=
		{
			GENERIC = "보기보다 먹을만하지 않네.",
			BURNT = "요리 망쳤네.",
		},
		TURF_DECIDUOUS = "지면이야.",
		TURF_SANDY = "지면이야.",
		TURF_BADLANDS = "지면이야.",
		BEARGER = "한 방으로 날 뭉개겠어. 그랬으면 좋겠네.",
		BEARGERVEST = "죽음이 날 둘러싸고 있어. 어, 내 상체를.",
		ICEPACK = "이 세상의 공포로부터 날 지켜 주지 않아.",
		BEARGER_FUR = "죽음의 냄새가 나네.",
		FURTUFT = "생명체에서 온 것이지.",
		BIGFOOT = "멸망의 전조자.",
		BONESHARD = "질식 위험이야.",
		BUZZARD = "죽은 자를 섭취한다고 들었어.",
		FIREPIT =
		{
			EMBERS = "Don't give up, little flame!",
			GENERIC = "A flame to keep the horrors at bay.",
			HIGH = "This fire burns with passion!",
			LOW = "It's losing the will to go on.",
			NORMAL = "It's a comfort.",
			OUT = "This can be rekindled, unlike my heart.",
		},
		CACTUS = 
		{
			GENERIC = "칼을 뽑아 들었어.",
			PICKED = "납작해졌어.",
		},
		CACTUS_MEAT_COOKED = "가시를 모두 뜯어냈어.",
		CACTUS_MEAT = "여전히 위험해.",
		CACTUS_FLOWER = "칼 같은 식물도 꽃펴. 윽.",
		COLDFIRE =
		{
			EMBERS = "어둠이 찾아 오고 있어.",
			GENERIC = "오늘밤은 살아남을 수 있겠어!",
			HIGH = "얼어붙은 지옥 풍경이야!",
			LOW = "암흑이 접근하고 있어.",
			NORMAL = "이상한 불이야.",
			OUT = "좋은 징조가 아니야.",
		},
		CATCOON = "쌍둥이 자매가 있었을까.",
		CATCOONDEN = 
		{
			GENERIC = "이 안에서 웅크리고 죽을 수 있을 거야.",
			EMPTY = "모든 고양이는 죽어야 해.",
		},
		CATCOONHAT = "머리에서 나는 죽음의 악취만한 것도 없어.",
		COONTAIL = "얼룩덜룩하고 부패했어.",
		COOKPOT =
		{
			COOKING_LONG = "안에 든 것이 아직 안 죽었어.",
			COOKING_SHORT = "끓여야 돼.",
			DONE = "이제서야 음식이네.",
			EMPTY = "내 영혼처럼 공허해.",
			BURNT = "바삭하게 탔어.",
		},
		EYEBRELLAHAT =	"유연성이 뛰어난 눈이네.",
		ARMORDRAGONFLY = "뒤집어서 입고 싶어.",
		DRAGON_SCALES = "고통의 비늘이야.",
		DRAGONFLYCHEST = "붐 박스네.",
		DECIDUOUSTREE = 
		{
			BURNING = "밝게 타고 있어.",
			BURNT = "사그라졌어.",
			CHOPPED = "다 죽으니까.",
			GENERIC = "오싹한 나무네. 할로윈을 좋아하겠네.",
			POISON = "더더욱 으스스해!",
		},
		ACORN_COOKED = "구워서 죽었네.",
		BIRCHNUTDRAKE = "전투하는 공!",
		FARMPLOT =
		{
			GENERIC = "어떤 씨를 심을까?",
			GROWING = "꾸불꾸불한 이파리가 흙에서 삐져나와.",
			NEEDSFERTILIZER = "땅이 얼어서 죽었어.",
			BURNT = "땅이 타 죽었어.",
		},
		COLDFIREPIT =
		{
			EMBERS = "어둠이 찾아 오고 있어.",
			GENERIC = "오늘밤은 살아남을 수 있겠어!",
			HIGH = "얼어붙은 지옥 풍경이야!",
			LOW = "암흑이 접근하고 있어.",
			NORMAL = "이상한 불이야.",
			OUT = "좋은 징조가 아니야.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "왜 막으려고 하는 거야. 어차피 다 탈 것을.",
			OFF = "시체처럼 조용하네.",
			LOWFUEL = "내용물이 없어지고 있어.",
		},
		ICEHAT = "머리를 시원하게 하네.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "발굽을 봐.",
			CHARGED = "충전!",
		},
		LIGHTNINGGOATHORN = "이상한 구부러진 뿔이야.",
		GOATMILK = "응유한 것 같아.",
		MEATRACK =
		{
			DONE = "건조가 끝났어.",
			DRYING = "건조한 바람 속에서 흔들려.",
			DRYINGINRAIN = "비가 마르지 않게 하고 있어.",
			GENERIC = "여기에 고기를 말릴 수 있어.",
			BURNT = "건조가 영원히 끝났어.",
		},
		MERMHEAD = 
		{
			GENERIC = "전혀 품위 없어.",
			BURNT = "더 악화될 수 있는 방법을 찾았네.",
		},
		MERMHOUSE = 
		{
			GENERIC = "시간의 흐름으로 망가졌네.",
			BURNT = "불 타서 더 망가졌네.",
		},
		FLOWERSALAD = "윽, 꽃이 더 있네.",
        ICECREAM = "아이스크림이 애비게일을 대체할 수는 없어.",
        WATERMELONICLE = "수박이 정체 상태네.",
        TRAILMIX = "식량 한 움큼.",
        HOTCHILI = "내 안을 태우네.",
        GUACAMOLE = "섬뜩하네. 좋아.",
		MOOSE = "혐오스러워.",
		MOOSEEGG = "저런 일이 어떻게 일어나는지 모르겠어.",
		MOSSLING = "새로운 삶이야. 전혀 불필요해.",
		FEATHERFAN = "바람을 불어 주겠네.",
		TROPICALFAN = "내가 가만히 있으면 애비게일처럼 생기가 없지.",
		MINIFAN = "내가 가만히 있으면 애비게일처럼 생기가 없지.",
		GOOSE_FEATHER = "나에게서 애비게일을 앗아간 것처럼.",
		STAFF_TORNADO = "날씨가 정말.",
		PIGHEAD = 
		{	
			GENERIC = "돼지를 죽여라. 그의 피를 흘려라.",
			BURNT = "타버렸어.",
		},
		PIGHOUSE =
		{
			FULL = "즐기고 있다면 좋겠어.",
			GENERIC = "적어도 그들은 편안하겠지.",
			LIGHTSOUT = "언제나 밖에서 안을 바라보는 거야.",
			BURNT = "아무 것도 영원하지 않아.",
		},
		FERTILIZER = "더러운 것 한 통.",
		RAINOMETER = 
		{	
			GENERIC = "구름 낀 정도를 측정해. 음울할 때가 마음에 들어.",
			BURNT = "그러면 햇빛도 죽은 것일까?",
		},
		RAINCOAT = "애비게일과 함께 웅덩이에서 뛰어 노는 걸 좋아했어.",
		RAINHAT = "젖지 않는다면 비가 무슨 소용일까?",
		RESEARCHLAB = 
		{	
			GENERIC = "끔찍한 것을 배우겠네.",
			BURNT = "끔찍하게 타 버렸어.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "끔찍한 것을 배우겠네.",
			BURNT = "끔찍하게 타 버렸어.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "끔찍한 것을 배우겠네.",
			BURNT = "끔찍하게 타 버렸어.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "거의 미친 것이나 마찬가지야.",
			BURNT = "광기가 화염을 불러와.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "운명을 약간 늦추는 것 뿐이야.",
			BURNT = "안전 장치가 사라져서 기뻐.",
		},
		ROCK_ICE = 
		{
			GENERIC = "차갑고 무정한 커다란 얼음.",
			MELTED = "차갑게 녹은 얼음 웅덩이야.",
		},
		ROCK_ICE_MELTED = "차갑게 녹은 얼음 웅덩이야.",
		ICE = "내 마음의 부서진 조각이야.",
        REFLECTIVEVEST = "모든 것이 조끼야.",
		HAWAIIANSHIRT = "이제는 아무 것에나 꽃을 놓네.",
		TENT = 
		{
			GENERIC = "잠은 죽음의 시사회야.",
			BURNT = "지옥불을 미리 보는 거야.",
		},
		SIESTAHUT = 
		{
			GENERIC = "낮잠은 죽음의 시사회야.",
			BURNT = "지옥불을 미리 보는 거야.",
		},
		TRANSISTOR = "전기 뭐?",
		TREASURECHEST = 
		{
			GENERIC = "나의 부를 간직하는 것이야.",
			BURNT = "재조차 보관할 수 없어.",
		},
		TUMBLEWEED = "혼자 굴러 다니며 사네.",
		GRASS_UMBRELLA = "해가 내리쬐고 있어.",
		PALMLEAF_UMBRELLA = "해가 내리쬐고 있어.",
		UNIMPLEMENTED = "삶처럼 아직 끝나지 않았어.",
		WALL_HAY = 
		{	
			GENERIC = "최소한의 방어일 뿐이야.",
			BURNT = "방어가 무너졌어.",
		},
		WALL_WOOD = 
		{
			GENERIC = "이제 운명을 지연시킬 수 있네.",
			BURNT = "피할 수 없는 것이 오네.",
		},
		WARG = "A true bastion of evil.",
		WATERMELON = "물이 가득해. 대단할 것 없는데?",
		WATERMELON_COOKED = "이제 따뜻한 물이야.",
		WATERMELONHAT = "머리가 끈적하네. 우욱.",
		WINTEROMETER = 
		{
			GENERIC = "나의 죽을 운명을 측정하고 있다는 느낌이 드네?",
			BURNT = "내가 여기에서 죽는 거야?",
		},
		HOME = "A pathetic simulcra...",
		HOMESIGN = 
		{
			GENERIC = "일시적이지만 표시를 남겼어.",
			BURNT = "정말 일시적이야.",
		},
		BEEBOX =
		{
			GENERIC = "얘들이 고생하면 내가 훔치겠어.",
			READY = "그들의 고생이 결실을 맺었어!",
			FULLHONEY = "그들의 고생이 결실을 맺었어!",
			NOHONEY = "일해, 벌들아!",
			SOMEHONEY = "수고해.",
			BURNT = "탄 꿀이네.",
		},
		LIVINGTREE = "절대로 죽을 수 없나?",
		ICESTAFF = "냉동 지팡이야.",
		WORMLIGHT = "약간의 소리가 들리고 있어.",
		WORMLIGHT_LESSER = "벌레의 혀보다는 빛이 낫겠지.",
		WORM =
		{
		    PLANT = "엉뚱한 곳에 있는 것 같아.",
		    DIRT = "뭐가 있는 걸까?",
		    WORM = "깊은 곳에서 왔네.",
		},
		WORMLIGHT_PLANT = "엉뚱한 곳에 있는 것 같아.",
		EEL = "장어네.",
		EEL_COOKED = "요리한 장어야.",
		UNAGI = "더 맛있어 보여.",
		EYETURRET = "왜 도움이 되는지 모르겠어.",
		EYETURRET_ITEM = "배치해야 할 것 같네.",
		MINOTAURHORN = "위대한 짐승의 잔재야.",
		MINOTAURCHEST = "굉장한 뿔을 가지고 있구나!",
		THULECITE_PIECES = "강력한 재료의 조각이야.",
		POND_ALGAE = "조류네.",
		GREENSTAFF = "깊숙이 안에서 힘이 반짝이고 있는 것이 보여.",
		POTTEDFERN = "화분이 작아서 잘 자라지 못하지.",

		THULECITE = "그 존재가 무명의 가장자리에 자국을 낸다.",
		ARMORRUINS = "죽음을 일시적으로 물리쳐.",
		RUINS_BAT = "내 손 안에 고대인의 힘이 들어있어.",
		RUINSHAT = "애비게일이라면 이 관을 좋아할 텐데.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "그림자에 무엇이 숨어있는지 알아.",	--calm phase
			WARN = "응시하는 눈이 느껴져.",	--Before nightmare
			WAXING = "접근하네.", --Nightmare Phase first 33%
			STEADY = "네 주위를 둘러쌌어!", --Nightmare 33% - 66%
			WANING = "그들이 떠나는 것 같아.", --Nightmare 66% +
			DAWN = "거의 끝났어.", --After nightmare
			NOMAGIC = "나는 홀로 있네.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "시간의 흐름이 모든 것을 이기지.",
		ROOK_NIGHTMARE = "시간이 모든 것을 부식시켜.",
		KNIGHT_NIGHTMARE = "시간이 굴복한 또 한 번의 전투야.",
		MINOTAUR = "외로운가 봐. 아주 작은 우리 안에 갇혔어.",	--Monster in labyrinth
		SPIDER_DROPPER = "어둠이 털을 탈색시켰어.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "지하에서 힘을 가져오네.",	--Lights that activate during nightmare.
		RELIC = "A vision of the past.",	--Fixed relic
		RUINS_RUBBLE = "A vision of the past. Broken.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "다용도 아이템이네.",	--Works as axe and pickaxe
		GREENGEM = "오점이 이것의 가장 아름다운 특징이야.",
		ORANGESTAFF = "사용할 때마다 내가 죽고 다시 살아나.",	--Teleports player.
		YELLOWAMULET = "내 어둠의 삶에 잠깐의 빛이야.",	--Emits light, player walks faster.
		GREENAMULET = "잠깐의 반짝임!",	--Reduce cost of crafting

		SLURPER = "단순해서 좋겠네.",
		SLURPER_PELT = "비어있는 배고픔의 가방.",
		SLURPERPELT = "An empty bag of hunger.",
		ARMORSLURPER = "달라붙는 음울한 살아있는 슈트네.",
		ORANGEAMULET = "고역으로부터 해방시켜 주는 일시적인 방출구.",
		YELLOWSTAFF = "막대가 나의 혼처럼 비꼬였어.",
		YELLOWGEM = "엄마를 기억나게 해.",
		ORANGEGEM = "이런 게 행복하게 해줬는데.",
		TELEBASE = 
		{
			VALID = "에너지가 이를 통해 흐르지.",
			GEMS = "포커스에 생기가 없어.",
		},
		GEMSOCKET = 
		{
			VALID = "보석이 집중시켰어.",
			GEMS = "무척 비어 보이네.",
		},
		STAFFLIGHT = "작은 태양계가 보일락말락.",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="예뻐.",
			LONG = "언니의 꽃이야. 멀리 갔어.",
			MEDIUM = "애비게일의 존재감이 더 강하게 느껴져.",
			SOON = "애비게일이 거의 다 왔어!",
			HAUNTED_POCKET = "애비게일이 놀이를 할 준비가 되었지만 공간이 좀 필요해.",
			HAUNTED_GROUND = "애비게일에게 놀이를 하는 방법을 알려 줘야 해.",

		},

        ANCIENT_ALTAR = "죽은 자의 메아리를 가득 담고 있어.",
        ANCIENT_ALTAR_BROKEN = "죽은 자의 고통스러운 메아리가 들려.",
        ANCIENT_STATUE = "별로 매력적이지 않아.",

        LICHEN = "어떻게 저렇게 잘 자라지?",
		CUTLICHEN = "목숨처럼 덧없이 지나가.",
		CAVE_BANANA = "껍질이 위험해 보여.",
		CAVE_BANANA_COOKED = "뜨끈한 바나나 덩이가 훨씬 더 좋네.",
		CAVE_BANANA_TREE = "불쌍한 식물, 해를 못 보고 있구나.",
		CAVE_BANANA_BURNT = "죽음과 고통이 끝나지 않아.",
		ROCKY = "끔찍한 광경을 봤을 거야.",


		BLUEAMULET = "익숙한 냉기의 포옹이야.",
		PURPLEAMULET = "스며 나와.",
		TELESTAFF = "더 강력하면 탈출할 수 있을 텐데.",
		MONKEY = "지성이라는 부담 없이 사니까 행복하겠네.",
		MONKEYBARREL = "더러워.",
		MONSTERLASAGNA = "요리한 악은 여전히 악이야, 라자냐에 넣어도.",
		HOUNDSTOOTH="뿌리채 뽑혔어.",
		ARMORSNURTLESHELL="이제 나의 문제로부터 숨을 수 있겠어.",
		BAT="밤의 동물이야.",
		BATBAT = "마법에 걸린 무기네. 아유, 신나라!",
		BATWING="날아갈 수 있으면 좋을 텐데.",
		BATWING_COOKED="위대한 잠재력을 가지고 있었어.",
		BATCAVE= "안에 숨어 있어...",
		BEDROLL_FURRY="망자의 복슬복슬한 가죽으로 감싸겠어.",
		BUNNYMAN="고통스러운 정신 세계를 가지고 있겠네.",
		FLOWER_CAVE="약해 보여.",
		FLOWER_CAVE_DOUBLE="약해 보여.",
		FLOWER_CAVE_TRIPLE="약해 보여.",
		GUANO="삶의 어쩔 수 없는 부산물이야.",
		LANTERN="어둠을 비추어라.",
		LIGHTBULB="서서히 타서 없어지고 있어.",
		MANRABBIT_TAIL="복슬복슬한 정수를 담고 있네.",
		MUSHTREE_TALL  ="These are some strange trees.",
		MUSHTREE_MEDIUM="It looks like a rotting hat.",
		MUSHTREE_SMALL ="Do little gnomes live in these?",
		MUSHTREE_TALL=
		{
            GENERIC = "이상한 나무들이야.",
            BLOOM = "열심히 노력하고 있어. 왜?",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "썩은 모자 같아.",
            BLOOM = "노력해도 돌 같은 흙에 떨어져.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "작은 난쟁이들이 안에 사는 거야?",
            BLOOM = "빛나는 존재야.",
        },
        MUSHTREE_TALL_WEBBED = "이것은 연약하고 경멸을 받고 있어.",
        SPORE_TALL = "자유를 찾아!",
        SPORE_MEDIUM = "자유를 찾아, 아이야!",
        SPORE_SMALL = "자유를 찾아 가, 작은 아이야!",
        SPORE_TALL_INV = "많이 죽었어. 하지만 이것은 살아남았어.",
        SPORE_MEDIUM_INV = "많은 수가 죽었지만, 이것은 살았어.",
        SPORE_SMALL_INV = "많이 쓰러졌지만, 이것은 안전해.",

		SLURTLE="생각 없이 바위를 쫓고 있어.",
		SLURTLE_SHELLPIECES="망가진 민달팽거북 꿈의 조각이야.",
		SLURTLEHAT="원래 소유주에게 도움되지 않았어.",
		SLURTLEHOLE="민달팽거북이 더 커지면 튀어 나와.",
		SLURTLESLIME="미끌거리는 기대감이 빛나네.",
		SNURTLE="저건 껍질이 더 크네.",
		SPIDER_HIDER="비겁한 거미네.",
		SPIDER_SPITTER="뭔가 씹고 있어.",
		BEEMINE_MAXWELL = "The furious creatures appreciate their freedom in retrospect.",
		SPIDERHOLE="잔뜩 있어.",
		SPIDERHOLE_ROCK ="잔뜩 있어.",
		STALAGMITE="땅이 선물을 주네.",
		STALAGMITE_FULL="땅이 선물을 주네.",
		STALAGMITE_LOW="땅이 선물을 주네.",
		STALAGMITE_MED="땅이 선물을 주네.",
		STALAGMITE_TALL="땅이 솟았어.",
		STALAGMITE_TALL_FULL="땅이 솟았어.",
		STALAGMITE_TALL_LOW="땅이 솟았어.",
		STALAGMITE_TALL_MED="땅이 솟았어.",

		TURF_CARPETFLOOR = "지면이야.",
		TURF_CHECKERFLOOR = "지면이야.",
		TURF_DIRT = "지면이야.",
		TURF_FOREST = "지면이야.",
		TURF_GRASS = "지면이야.",
		TURF_MARSH = "지면이야.",
		TURF_ROAD = "지면이야.",
		TURF_ROCKY = "지면이야.",
		TURF_SAVANNA = "지면이야.",
		TURF_WOODFLOOR = "지면이야.",

		TURF_CAVE="지면이야.",
		TURF_FUNGUS="지면이야.",
		TURF_SINKHOLE="지면이야.",
		TURF_UNDERROCK="지면이야.",
		TURF_MUD="지면이야.",

		POWCAKE = "절박해야 쓰겠네.",		
		CAVE_ENTRANCE = "누군가가 지하로 가지 못하게 하려고 하네.",
		CAVE_ENTRANCE_RUINS = "누군가가 지하로 가지 못하게 하려고 하네.",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "광기에 사로잡혀서 동굴에 들어갈 수는 없어.",
            OPEN = "지하에 거대한 악의 존재가 거닐고 있어.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "왜 떠나? 여기의 빛이 내 안색을 좋게 만들어 주는데.",
            OPEN = "표면이 부르네.",
        },

		BOOMERANG = "발신인에게 돌아오는 죽음이야.",
		MAXWELLPHONOGRAPH = "죽음의 춤을 출까?",
		ABIGAIL = "내 쌍둥이 언니, 애비게일이야.",
		PIGGUARD = "작은 돼지가 험악해 보이네.",
		ADVENTURE_PORTAL = "이것은 무슨 무시무시한 기술이지?",
		AMULET = "누가 이것을 소유했었을까.",
		ANIMAL_TRACK = "짐승의 표식이야.",
		ARMORGRASS = "운명을 연장할 뿐이야.",
		ARMORMARBLE = "내 심장을 찌를 단도를 막아줄 거야.",
		ARMORWOOD = "이것으로 운명을 약간 더 저지할 수 있어.",
		ARMOR_SANITY = "미치기 위한 완벽하게 안전한 방법이야.",
		ASH =
		{
			GENERIC = "아름다운 불이 꺼진 다음에 남은 것이야.",
			REMAINS_GLOMMERFLOWER = "내가 원격이동했을 때 꽃이 연소되었어!",
			REMAINS_EYE_BONE = "내가 원격이동했을 때 눈뼈가 연소되었어!",
			REMAINS_THINGIE = "무엇인가였겠지, 타기 전에는...",
		},
		AXE = "노동과 살해의 도구네.",
		BABYBEEFALO = "젊음을 누려. 곧 이 세상의 공포를 알게 될 거야.",
		BACKPACK = "팩이네. 이제 더 많은 짐을 들 수 있어.",
		BACONEGGS = "또 다른 하루를 시작할 균형 있는 아침 식사야.",
		BANDAGE = "존재의 고통을 치료할 수는 없어.",
		BASALT = "부수는 것은 무의미해.",
		BEARDHAIR = "끔찍하군.",
		BEDROLL_STRAW = "잠은 잠깐의 죽음이야.",
		BEE =
		{
			GENERIC = "침은 피해야지.",
			HELD = "가만히 있어, 작은 아이야.",
		},
		BEEFALO =
		{
			FOLLOWER = "나를 쫓으면 파멸로 치달을 거야.",
			GENERIC = "그 눈 뒤에서 어떤 생각을 하고 있을까.",
			NAKED = "이제 벌거숭이야.",
			SLEEPING = "자면 꿈꿀 기회가 올 거야.",
		},
		BEEFALOHAT = "머리를 덮어야겠네.",
		BEEFALOWOOL = "어딘가에 헐벗고 추운 고기물소가 있겠네.",
		BEEHAT = "즐거운 소리를 막아줄 거야. 물론 침도.",
		BEEHIVE = "더껑이와 꽃가루가 든 몹쓸 벌통.",
		BEEMINE = "안에서 아직 살아있어. 불쌍해.",
		BERRIES = "베리가 시큼하네.",
		BERRIES_COOKED = "더 균형이 있는 맛이지만 오래 가지 않아.",
		BERRYBUSH =
		{
			BARREN = "황폐해.",
			WITHERED = "열에게 졌어.",
			GENERIC = "스낵인가, 아마?",
			PICKED = "기다려야겠어.",
		},
		BIRDCAGE =
		{
			GENERIC = "어떤 이들은 자신의 우리를 볼 수 있어.",
			OCCUPIED = "그는 이제 더 행복해.",
			SLEEPING = "죽은 걸까? 아니야. 자고 있어.",
			HUNGRY = "배고픈가봐.",
			STARVING = "공허함이 그를 안으로부터 잠식하고 있어.",
			DEAD = "생명이 끊긴 채 평화롭게 쉬네.",
			SKELETON = "새... 였었지.",
		},
		BIRDTRAP = "막대와 줄이 치명적으로 바뀌었네.",
		BIRD_EGG = "그 많은 희망이 사라졌어.",
		BIRD_EGG_COOKED = "더 이상 새가 생길 수 없어.",
		BISHOP = "그는 무엇을 위해 기도할까?",
		BISHOP_CHARGE_HIT = "앗...",

		BLOWDART_SLEEP = "많이 자는 것이 아니라, 조금만.",
		BLOWDART_PIPE = "한쪽을 불면 반대쪽으로 고통이 나와.",
		BLOWDART_FIRE = "세계를 불태울까?",
		BLUEGEM = "파란색은... 슬픈 새인가?",
		BLUEPRINT = "이걸 그린 자는 아마 죽었겠지.",
		BELL_BLUEPRINT = "이걸 그린 자는 아마 죽었겠지.",
		BLUE_CAP = "따분함을 보존하는 버섯이네.",
		BLUE_CAP_COOKED = "모든 것은 변해.",
		BLUE_MUSHROOM =
		{
			GENERIC = "곰팡내가 나네.",
			INGROUND = "나라도 숨을 거야.",
			PICKED = "수확했어.",
		},
		BOARDS = "나무에게는 더 무섭겠네.",
		BONESTEW = "그들이 죽었어. 그리고 스튜에 집어넣었어.",
		BUGNET = "작은 곤충의 감옥이야.",
		BUSHHAT = "어차피 난 투명한 존재야...",
		BUTTER = "기대하지 않았어.",
		BUTTERFLY =
		{
			GENERIC = "예쁘지만 짧은 삶이야.",
			HELD = "내 손 안에 들고 있어.",
		},
		BUTTERFLYWINGS = "나비가 더 이상 떠오를 수 없어.",
		BUTTERFLYMUFFIN = "이 달콤한 함정에서 빠져나올 수 있나 보자!",
		CAMPFIRE =
		{
			EMBERS = "어둠이 찾아 오고 있어.",
			GENERIC = "오늘밤은 살아남을 수 있겠어!",
			HIGH = "지옥 풍경!",
			LOW = "암흑이 접근하고 있어.",
			NORMAL = "불이야.",
			OUT = "좋은 징조가 아니야.",
		},
		CANE = "아무 데나 빨리 갈 수 있어.",
		CARROT = "당근이야.",
		CARROT_COOKED = "불의 공격을 받은 당근이야.",
		CARROT_PLANTED = "땅에 있는 당근이야.",
		CARROT_SEEDS = "당근이 될 유망주.",
		CAVE_FERN = "어둠 속에서 보이는 약간의 색채.",
		CHARCOAL = "차갑고, 죽었고, 검은색이다. 내 마음처럼.",
        CHESSJUNK1 = "차가운, 죽은 인공생명.",
        CHESSJUNK2 = "차가운, 죽은 인공생명.",
        CHESSJUNK3 = "차가운, 죽은 인공생명.",
		CHESTER = "털 달린 공허한 공.",
		CHESTER_EYEBONE =
		{
			GENERIC = "내 혼을 보고 있어.",
			WAITING = "자는 것이 아니라... 기다리는 거야.",
		},
		COOKEDMANDRAKE = "좋은 죽음이었어. 넌 맛있겠네.",
		COOKEDMEAT = "요리해서 피가 증발했어.",
		COOKEDMONSTERMEAT = "요리한 악은 여전히 악이야.",
		COOKEDSMALLMEAT = "불이 정화했어.",
		CORN = "유치한 농담을 할 수 있지만, 안 하겠어.",
		CORN_COOKED = "이 옥수수는 열을 견딜 수 없었어.",
		CORN_SEEDS = "생명의 씨앗, 손 안에 작게 담겨 있어.",
		CROW =
		{
			GENERIC = "내 심장에서 부리를 빼!",
			HELD = "내 거야.",
		},
		CUTGRASS = "작은 것들을 죽이는 것을 좋아해.",
		CUTREEDS = "나는 자르는 것을 좋아해.",
		CUTSTONE = "무덤을 표시할 때 좋아.",
		DEADLYFEAST = "이것이 나의 마지막 성찬이야.",
		DEERCLOPS = "죽음의 화신이네!",
		DEERCLOPS_EYEBALL =  "이것은 어떤 공포를 목격할까.",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불의 잔재네.",
		},
		DIRTPILE = "어라. 흙이 더 있네.",
		DIVININGROD =
		{
			COLD = "근원은 멀리에 있어.",
			GENERIC = "없어진 짝을 영원히 찾고 있어.",
			HOT = "사악한 것이 여기에 있어!",
			WARM = "악이 다가오고 있어.",
			WARMER = "이제 아주 가까워.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "이 새로운 것이 무엇을 할 수 있을까?",
			READY = "그래도 큰 열쇠가 필요하네.",
			UNLOCKED = "뭘 찾을 수 있는지 보자!",
		},
		DRAGONFLY = "안에서 타고 있어.",
		LAVASPIT = 
		{
			HOT = "위로 뱉고 있어.",
			COOL = "식었는데 냄새가 이상해.",
		},
		LAVA_POND = "빠지면 끝낼 수 있어.",
		LAVAE = "지옥불로 타.",
		LAVAE_PET = 
		{
			STARVING = "죽음이 다가오고 있어.",
			HUNGRY = "배고픔의 고통을 즐기고 있어.",
			CONTENT = "있을 때 즐겨, 작은 애벌레야.",
			GENERIC = "어둠을 비추는 삶의 기운이네.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "미래를 기대해도 되는 것일까?",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "내 마음처럼 차가운 알이야.",
			COMFY = "알은 따뜻하지만, 내 마음은 차가워.",
		},
		LAVAE_TOOTH = "물론 이빨이야.",

		DRAGONFRUIT = "전혀 용처럼 생기지 않았어.",
		DRAGONFRUIT_COOKED = "그래도 용이 아니야. 적어도 죽긴 했어.",
		DRAGONFRUIT_SEEDS = "씨앗이야. 그래도 용이 자라지는 않아.",
		DRAGONPIE = "뭐, 적어도 이제는 파이네.",
		DRUMSTICK = "좋은 소리가 나, 그리고 영양도 있어!",
		DRUMSTICK_COOKED = "날것이 아니면 더 맛있어.",
		DUG_BERRYBUSH = "왜 이것을 만들었는지 모르겠어.",
		DUG_GRASS = "왜 이것을 만들었는지 모르겠어.",
		DUG_MARSH_BUSH = "왜 이것을 만들었는지 모르겠어.",
		DUG_SAPLING = "왜 이것을 만들었는지 모르겠어.",
		DURIAN = "뾰족하고 냄새나!",
		DURIAN_COOKED = "덜 뾰족하지만 냄새는 더 나네!",
		DURIAN_SEEDS = "신기하게 씨는 냄새나지 않아.",
		EARMUFFSHAT = "그들의 끔찍한 종말이 나를 심한 추위로부터 막아주네.",
		EGGPLANT = "거의 치명적인 나이트셰이드. 거의.",
		EGGPLANT_COOKED = "나이트셰이드를 요리하니까 죽음의 느낌이 더 없어졌어.",
		EGGPLANT_SEEDS = "나이트셰이드 씨야.",
		ACORN = 
		{
		    GENERIC = "작은 생명, 깨지기 쉬운 죽음이 감싸고 있네.",
		    PLANTED = "나무가 금방 자라겠네.",
		},
		EVERGREEN =
		{
			BURNING = "밝게 타고 있어.",
			BURNT = "사그라졌어.",
			CHOPPED = "다 죽으니까.",
			GENERIC = "자연은 너무 따분해.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "밝게 타고 있어.",
			BURNT = "사그라졌어.",
			CHOPPED = "다 죽으니까.",
			GENERIC = "생명의 순환이 끊어졌어.",
		},
		EYEPLANT = "주인의 모든 요구를 들어주지.",
		FEATHERHAT = "까아악!",
		FEATHER_CROW = "까마귀 깃털은 영원한 어둠처럼 흑색이야.",
		FEATHER_ROBIN = "피리새 깃털, 피처럼 붉은 색이야.",
		FEATHER_ROBIN_WINTER = "흰머리멧새 깃털이 터널 끝의 빛처럼 희네.",
		FEM_PUPPET = "그녀가 무엇을 했을까.",
		FIREFLIES =
		{
			GENERIC = "어둠 속의 작은 빛.",
			HELD = "작은 빛, 내 주머니 밖의 세상에서 표류하네.",
		},
		FIREHOUND = "성질이 불 같아.",
		FIRESTAFF = "세상을 불지르겠어!",
		FISH = "살려고 발버둥쳤어. 불쌍한 것.",
		FISHINGROD = "이것으로 안전한 연못에서 물고기를 꺼낼 수 있어.",
		FISHSTICKS = "완벽하게 네모나게 만든 물고기야.",
		FISHTACOS = "뼈를 다 뺐기를 바래.",
		FISH_MED_COOKED = "제대로 구우면 더 이상 팔딱거리지 않아.",
		FISH_MED = "이승과의 인연을 끊었네.",
		FISH_COOKED = "제대로 구우면 더 이상 팔딱거리지 않아.",
		FLINT = "작은 칼날 같은 바위야.",
		FLOWER = "밝고 명랑해. 우엑.",
		FLOWER_WITHERED = "시간의 흐름은 모든 것을 파멸시켜.",
		FLOWERHAT = "하지만 나는 애도하고 있어...",
		FLOWER_EVIL = "그래도 다른 꽃보다는 낫지.",
		FOLIAGE = "나를 아아르니발케아로 인도해 줘.",
		FOOTBALLHAT = "내가 입을 죽은 것이네. 좋아라.",
		FROG =
		{
			DEAD = "삶은 작고 짧은 것이야.",
			GENERIC = "작고 사마귀투성이야.",
			SLEEPING = "자고 있어.",
		},
		FROGGLEBUNWICH = "개구리 다리가 이렇게 좋아 보일 줄 몰랐어.",
		FROGLEGS = "개구리에서 뜯어냈어.",
		FROGLEGS_COOKED = "더 이상 안 꿈틀거려.",
		FRUITMEDLEY = "달고, 신 것이 컵 안에 들어있어.",
		GEARS = "기계 악마의 내부야.",
		GHOST = "무덤에서 일어났네!",
		GOLDENAXE = "적어도 멋지게 나무를 죽일 수 있겠네.",
		GOLDENPICKAXE = "적어도 멋지게 돌을 깰 수 있겠네.",
		GOLDENPITCHFORK = "적어도 멋지게 땅을 갈 수 있겠네.",
		GOLDENSHOVEL = "적어도 멋지게 땅 팔 수 있겠네.",
		GOLDNUGGET = "연옥에서도 가장 소중한 금속이지.",
		GRASS =
		{
			BARREN = "똥이 필요해.",
			WITHERED = "열을 견딜 수 없었네.",
			BURNING = "냄새가 요상하네.",
			GENERIC = "풀 덤불일 뿐.",
			PICKED = "살해당했네.",
		},
		GREEN_CAP = "이 버섯은 실망스럽게 평범해.",
		GREEN_CAP_COOKED = "모든 것은 변해.",
		GREEN_MUSHROOM =
		{
			GENERIC = "습기 차.",
			INGROUND = "나라도 숨을 거야.",
			PICKED = "수확했어.",
		},
		GUNPOWDER = "어둠의 길을 걷는 나.",
		HAMBAT = "죽음이 죽음을 부르네.",
		HAMMER = "세상을 부수기 위하여.",
		HEALINGSALVE = "삶이 고통을 가져오고, 고통이 삶을 가져오네.",
		HEATROCK =
		{
			FROZEN = "내 마음처럼 얼었어.",
			COLD = "그냥 약간 차가운 바위야.",
			GENERIC = "그냥 공간을 차지하고 있어.",
			WARM = "다른 바위처럼 미지근하고 생명이 없어.",
			HOT = "가장 밝게 타는 것이 가장 빠르게 타니까.",
		},
		HONEY = "달지만 일시적인 특식이야.",
		HONEYCOMB = "벌집 조각이 흩어졌어.",
		HONEYHAM = "이 생물체의 달콤한 포옹에 어울리는 달콤한 소스야.",
		HONEYNUGGETS = "작은 조각으로 잘린 고기. 내 마음처럼.",
		HORN = "고기물소가 안에 갇힌 소리가 들려.",
		HOUND = "물러서, 사악한 악의 수하!",
		HOUNDBONE = "악한 짐승의 시체야.",
		HOUNDMOUND = "가장 끔찍한 생물체의 집이야.",
		ICEBOX = "내 마음처럼 차가워.",
		ICEHOUND = "차갑고 죽은 마음을 가졌어.",
		INSANITYROCK =
		{
			ACTIVE = "내 이름을 불러.",
			INACTIVE = "차갑고 검은색이야.",
		},
		JAMMYPRESERVES = "딱 적당한 양의 잼이야.",
		KABOBS = "중앙을 관통당한 고기네.",
		KILLERBEE =
		{
			GENERIC = "양심 없는 벌이야.",
			HELD = "가만히 있어, 작은 아이야.",
		},
		KNIGHT = "차갑고 혼이 없는 말이네.",
		KOALEFANT_SUMMER = "외로움의 짐승.",
		KOALEFANT_WINTER = "악천후를 견디네.",
		KRAMPUS = "지하세계의 끔찍한 생물체야, 안녕.",
		KRAMPUS_SACK = "염소 냄새가 나.",
		LEIF = "육중한 짐승이네.",
		LEIF_SPARSE = "육중한 짐승이네.",
		LIGHTNING_ROD =
		{
			CHARGED = "결국 이 능력도 소진될 거야.",
			GENERIC = "파괴를 집중시켜.",
		},
		LITTLE_WALRUS = "폭력의 고리가 계속 이어져.",
		LIVINGLOG = "영원히 침묵 속에서 비명을 지르고 있어.",
		LOCKEDWES = "맥스웰의 조각상 때문에 갇혀서 영원히 사네.",
		LOG = "If trees could talk, they would scream at the sight of this.",
		LOG =
		{
			BURNING = "Just a burning log.",
			GENERIC = "If trees could talk, they would scream at the sight of this.",
		},
		LUREPLANT = "다 삼켜 버리네.",
		LUREPLANTBULB = "삶은 흐르네.",
		MALE_PUPPET = "그가 무엇을 했을까.",
		MANDRAKE =
		{
			DEAD = "아아, 불쌍한 맨드레이크야!",
			GENERIC = "강력한 맨드레이크야. 밤에 따야겠어.",
			PICKED = "전진, 나의 채소 부하들아!",
		},
		MANDRAKESOUP = "끓여서 생기가 사라졌어.",
		MARBLE = "매끄럽고 생명이 없어.",
		MARBLEPILLAR = "돌도 끊임없는 부식의 유혹 견딜 수 없지.",
		MARBLETREE = "이 차가운 나무 안에는 생명의 소리가 담겨 있지 않아.",
		MARSH_BUSH =
		{
			BURNING = "가시도 불타네.",
			GENERIC = "언제나 아픈 관목이야.",
			PICKED = "그걸 하는 게 아팠어.",
		},
		MARSH_PLANT = "잡풀이야.",
		MARSH_TREE =
		{
			BURNING = "타고 있어.",
			BURNT = "나의 심장처럼 컴컴해.",
			CHOPPED = "가시가 보호해 주지 못해.",
			GENERIC = "고통만 아는 나무야.",
		},
		MAXWELL = "그와 이상한 친밀함이 느껴져.",
		MAXWELLHEAD = "극적인 것을 좋아하는구나.",
		MAXWELLLIGHT = "궁금한 빛이야.",
		MAXWELLLOCK = "마법으로 보이네.",
		MAXWELLTHRONE = "내가 예상한 것이 아니야.",
		MEAT = "아직도 피가 흘러.",
		MEATBALLS = "공 고기네. 아유, 신나라.",
		MEAT_DRIED = "고기가 마르고 맛있어졌어.",
		MERM = "끔찍한 늪 괴물!",
		MINERHAT = "핸즈프리 조명이네!",
		MONSTERMEAT = "악의 기운이 흐르고 있어.",
		MONSTERMEAT_DRIED = "고기가 건조해지고 맛이 이상해졌어.",
		MOSQUITO =
		{
			GENERIC = "자신의 생명을 유지하기 위해 남의 생명을 훔쳐.",
			HELD = "훔친 온기가 느껴져.",
		},
		MOSQUITOSACK = "모기에서 뜯어낸 피 주머니. 마음에 들어.",
		MOUND =
		{
			DUG = "땅이 비밀을 토해냈어.",
			GENERIC = "언젠가 너를 쫓아갈게.",
		},
		NIGHTLIGHT = "무시무시하면서도 아름다워.",
		NIGHTMAREFUEL = "꿈이 잠들 때 이것이 찾아 와.",
		NIGHTSWORD = "꿈이 한 곳에 모였어. 날카로워.",
		NITRE = "인간의 어리석음이 담겨 있어.",
		ONEMANBAND = "전에는 이런 악기가 재미있었어.",
		PANDORASCHEST = "인생은 도박이야.",
		PANFLUTE = "음악은 내 텅 빈 혼의 창이야.",
		PAPYRUS = "나의 고통을 기록하기 위하여.",
		PENGUIN = "옷을 차려 입었지만 어디로 가?",
		PERD = "바보 새야! 내 베리에서 멀찍이 떨어져!",
		PEROGIES = "사랑스러운 영양 주머니.",
		PETALS = "내가 아름다운 것을 파괴했어.",
		PETALS_EVIL = "내 영혼의 색으로 칠해져 있어.",
		PICKAXE = "땅을 관통하기 위하여.",
		PIGGYBACK = "죽으면 더 유용하지.",
		PHLEGM = "처참한 짐승이 아팠나봐.",
		PIGKING = "살 수 있을 때 살으셔, 폐하.",
		PIGMAN =
		{
			DEAD = "더 좋은 곳으로 갔어.",
			FOLLOWER = "너무 외로워.",
			GENERIC = "너무 무뚝뚝해.",
			GUARD = "오웰의 소설 같아.",
			WEREPIG = "밤의 동물이네!",
		},
		PIGSKIN = "죽은 돼지 가죽이네.",
		PIGTORCH = "어둠을 가르네.",
		PINECONE = 
		{
		    GENERIC = "작은 생명, 깨지기 쉬운 죽음이 감싸고 있네.",
		    PLANTED = "나무가 금방 자라겠네.",
		},
		PITCHFORK = "마귀의 도구네!",
		PLANTMEAT = "냄새가 구역질 나.",
		PLANTMEAT_COOKED = "약간만 더 나아.",
		PLANT_NORMAL =
		{
			GENERIC = "먹는 풀이야.",
			GROWING = "계속 자라라. 기다릴게.",
			READY = "수확 준비가 되었어.",
			WITHERED = "생기가 빠져나왔어.",
		},
		POMEGRANATE = "씹고 으깰 빨간 과즙 알갱이네!",
		POMEGRANATE_COOKED = "따뜻하지만 더 깔끔하진 않아.",
		POMEGRANATE_SEEDS = "씨가 더 나올 줄 알았어.",
		POND = "오펠리아? 아래에 있는 거야?",
		POOP = "인생은 피 그리고 이것이야.",
		SCORCHED_SKELETON = "불이 이 불쌍한 영혼을 씻어주었어.",
		PUMPKIN = "내 마음이 있던 곳의 구멍만큼 커.",
		PUMPKINCOOKIE = "쿠키...",
		PUMPKIN_COOKED = "열 때문에 약간 오그라들었어. 마음에 들어.",
		PUMPKIN_LANTERN = "넌 별로 안 무서워.",
		PUMPKIN_SEEDS = "씨앗이야. 신나라.",
		PURPLEGEM = "자주색은... 자주색이야.",
		RABBIT =
		{
			GENERIC = "운명을 모른 채 생각 없이 헤매고 있어.",
			HELD = "안전하게 나의 포옹을 받아들이네.",
		},
		RABBITHOLE = 
		{
			GENERIC = "안에 빠져들기에는 내가 너무 커.",
			SPRING = "닫혔어. 이제 아무도 빠져들 수 없어.",
		},
		RATATOUILLE = "요리한 채소가 잔뜩 있어. 황홀해.",
		RAZOR = "면도용이야.",
		REDGEM = "내 심장의 피처럼 빨개.",
		RED_CAP = "내 마음을 빼앗으려는 버섯이네.",
		RED_CAP_COOKED = "모든 것은 변해.",
		RED_MUSHROOM =
		{
			GENERIC = "축축해.",
			INGROUND = "나라도 숨을 거야.",
			PICKED = "수확했어.",
		},
		REEDS =
		{
			BURNING = "곧 재가 되겠네.",
			GENERIC = "갈대 덤불일 뿐이야.",
			PICKED = "집었어.",
		},
        RELIC = 
        {
            GENERIC = "고대 세계의 잔재야.",
            BROKEN = "부서진 돌 조각이야.",
        },
        RUBBLE = "Broken bits of stone.",
        RUINS_RUBBLE = "망가진 꿈의 더미야.",
		RESURRECTIONSTONE = "부질없는 짓이야.",
		ROBIN =
		{
			GENERIC = "봄이 왔다는 걸까? 아니었으면 좋겠네.",
			HELD = "주머니 안에 갇혀 있는 것을 좋아해.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "쓸쓸한 동토의 삶이야.",
			HELD = "정말 부드럽네. 나의 적이야.",
		},
		ROBOT_PUPPET = "무엇을 했을까.",
		MOOSE_NESTING_GROUND = "삶의 요람. 싫어.",
		ROCK_LIGHT =
		{
			GENERIC = "불 구덩이의 배에 불이 있어.",
			OUT = "용암이 탈 의지를 잃었어...",
			LOW = "그림자가 접근하고 있어.",
			NORMAL = "용암이 불붙었어.",
		},
		ROCK = "그것도 영원하진 않아.",
		ROCKS = "작은 바위야.",
        ROOK = "루크인가? 아니면 성인가?",
		ROPE = "저것으로 쉽게 여기를 빠져나갈 수 있겠지.",
		ROTTENEGG = "만물의 도야.",
		SANITYROCK =
		{
			ACTIVE = "나를 부르네.",
			INACTIVE = "방첨탑도 날 떠났어.",
		},
		SAPLING =
		{
			BURNING = "화염의 봉인이네.",
			WITHERED = "뜨거운 열기가 이기고 말았네.",
			GENERIC = "성장하려고 하네.",
			PICKED = "다음 기회를 노려라, 어린나무.",
		},
		SEEDS = "삶 또는 삶에 대한 약속.",
		SEEDS_COOKED = "생기를 구워서 없앴어.",
		SEWING_KIT = "피할 수 없는 부패를 지연하기 위한 또 다른 방법이야.",
		SHOVEL = "어떤 끔찍한 비밀을 내가 드러낼까?",
		SILK = "미끌거리고 가느다라네.",
		SKELETON = "탈출한 네가 부러워.",
		SKELETON_PLAYER = "아주 아주 가까웠네.",
		SKULLCHEST = "나의 메멘토 모리를 보관할 거야.",
		SMALLBIRD =
		{
			GENERIC = "안녕, 작은 아이야.",
			HUNGRY = "속이 비었어?",
			STARVING = "씨가 돌아오지 않는 블랙홀이야.",
		},
		SMALLMEAT = "작은 두려움의 냄새가 나.",
		SMALLMEAT_DRIED = "고기가 마르고 맛있어졌어.",
		SPAT = "내가 고뇌를 끊어줬어.",
		SPEAR = "내가 세계의 파괴자가 되었네.",
		SPIDER =
		{
			DEAD = "언젠가 다시 만날 거야.",
			GENERIC = "밤의 동물이네!",
			SLEEPING = "악이 잠들어 있어.",
		},
		SPIDERDEN = "더러움과 악함의 둥지.",
		SPIDEREGGSACK = "죽음과 파괴를 가득 담은 작은 꾸러미.",
		SPIDERGLAND = "이 짐승은 죽어서도 고통을 주네.",
		SPIDERHAT = "심연을 바라볼 때야.",
		SPIDERQUEEN = "제왕적인 끔찍함을 갖추었네.",
		SPIDER_WARRIOR =
		{
			DEAD = "아아, 용감한 전사.",
			GENERIC = "밤의 전사야!",
			SLEEPING = "조심해야 해.",
		},
		SPOILED_FOOD = "결국 모든 것은 쓰레기가 되지.",
		STATUEHARP = "어쩌면 이 조각상들이 나의 친구가 되어주겠네.",
		STATUEMAXWELL = "그가 날 데려왔어.",
		STEELWOOL = "따뜻하게 해주지 않아.",
		STINGER = "날카롭고 치명적이야.",
		STRAWHAT = "머리를 덮어야겠네.",
		STUFFEDEGGPLANT = "나이트셰이드야. 아마 독이 들어있지는 않아.",
		SUNKBOAT = "잔인한 꾀야!",
		SWEATERVEST = "죽은 조각들을 조끼로 만들어서 입을 수 있어!",
		TAFFY = "이렇게 달콤한 것을 내가 만들 줄이야.",
		TALLBIRD = "하늘의 굴레에서 해방되었네.",
		TALLBIRDEGG = "잠재성이 가득해.",
		TALLBIRDEGG_COOKED = "약속을 다 앗아갔어. 베이컨과 같이 먹으면 나쁘지 않아.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "어둠으로 냉각되었어.",
			GENERIC = "작고 허약한 존재가 빛을 보려고 안간힘쓰고 있어.",
			HOT = "열을 견딜 수 없어.",
			LONG = "먼저 시작한 삶은 먼저 끝나.",
			SHORT = "이제 곧.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "저 알은 새 삶은 상징해. 윽.",
			PICKED = "둥지가 비어있네. 비어있어. 불모지야. 공허야.",
		},
		TEENBIRD =
		{
			GENERIC = "너도 날 떠날 거야?",
			HUNGRY = "우리 모두 공허함을 채우려고 하네.",
			STARVING = "너의 진정한 모습이 드러났어!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "다음 영역은 더욱 끔찍할 거야!",
			GENERIC = "좋을 것이 없어.",
			LOCKED = "아직 잠겨 있어.",
			PARTIAL = "반을 세운 걸까, 반을 파괴한 걸까?",
		},
		TELEPORTATO_BOX = "생명의 불꽃이 들어있어.",
		TELEPORTATO_CRANK = "복잡해 보여.",
		TELEPORTATO_POTATO = "끔찍한 것!",
		TELEPORTATO_RING = "날카로운 모서리가 없어.",
		TENTACLE = "길고 가느다랗고 위험해!",
		TENTACLESPOTS = "이것은 말하지 않는 것이 나아.",
		TENTACLESPIKE = "날카롭고, 미끌거리고, 위험해.",
        TENTACLE_PILLAR = "이런 일이 아래에서 일어나네.",
        TENTACLE_PILLAR_HOLE = "언젠가는 돌아오겠지.",
        TENTACLE_PILLAR_ARM = "아기들아!",
        TENTACLE_GARDEN = "이 건 다르네.",
		TOPHAT = "야성을 잊게 만들어주는 교양 있는 의류야.",
		TORCH = "밤에 저항하는 조그마한 성채야.",
		TRAP = "단순한 풀이 치명적으로 변했어.",
		TRAP_TEETH = "땅 밑의 못된 깜짝선물이네.",
		TRAP_TEETH_MAXWELL = "전혀 기대치 못했을 때의 죽음.",
		TRINKET_1 = "완벽하게 기형적이야.",
		TRINKET_10 = "먹일 입이 늘었네.",
		TRINKET_11 = "행운의 로봇이구나, 혼을 가졌던 적이 없으니.",
		TRINKET_12 = "더 이상 미끌거리지 않지?",
		TRINKET_2 = "가짜. 죽음처럼 유혹하네.",
		TRINKET_3 = "칼이 내 문제를 다 해결할 수 있다면...",
		TRINKET_4 = "이를 세계 끝까지 가져가겠어.",
		TRINKET_5 = "더 컸더라면 이것을 태양으로 바로 날렸을 거야.",
		TRINKET_6 = "한 때 전기가 흘렀지만, 지금은 끝났네.",
		TRINKET_7 = "단순한 놀이일 뿐이야.",
		TRINKET_8 = "목욕하고 싶어.",
		TRINKET_9 = "짝이 안 맞는 삶을 위한 짝이 안 맞는 단추네.",
		TRUNKVEST_SUMMER = "내 피부에 착용하는 피부.",
		TRUNKVEST_WINTER = "내 몸은 따뜻하게 해주지만, 내 정신은?",
		TRUNK_COOKED = "지금은 더 안 좋아 보여.",
		TRUNK_SUMMER = "귀가 더 마음에 들어.",
		TRUNK_WINTER = "유일한 친구와 헤어졌네.",
		TURKEYDINNER = "이제는 누가 먹이가 되었나?",
		BANANAPOP = "애비게일과 함께 이걸 먹었었어...",
		BISQUE = "몸에 영양을 주고, 혼을 굶겨...",
		CEVICHE = "슬픔의 맛만 느껴져...",
		SEAFOODGUMBO = "삶이 가득하던 바다. 더 이상은 아니야.",
		SURFNTURF = "더 나쁠 수도 있어.",
		SHARKFINSOUP = "죽음으로 탈출했어. 내가 맛볼 죽음.",
		LOBSTERDINNER = "그의 죽음이 나에게 생명을 줘.",
		LOBSTERBISQUE = "숟가락이 있으면 좋겠어.",
		JELLYOPOP = "죽음은 모두에게 찾아와. 어쩔 때는 막대기를 통해서.",
		CALIFORNIAROLL = "게토끼를 해초에 감쌌어.",
		TWIGS = "다 자라기 전에 땅에서 뽑혔네.",
		UMBRELLA = "구름이 울어.",
		WAFFLES = "정말 와플이네.",
		WALL_HAY_ITEM = "방어 효과는 의심스러워.",
		WALL_STONE = "내부에 있는 것으로부터 무엇이 날 지켜줄까?",
		WALL_STONE_ITEM = "안에 있는 악귀를 막아주진 않아.",
		WALL_RUINS = "이것이 고대인들을 지켜 주지 못했어!",
		WALL_RUINS_ITEM = "돌에 귀신이 든 걸까?",
		WALL_WOOD_ITEM = "묶어 놓은 통나무들.",
		WALL_MOONROCK = "달... 나를 보호해주겠다고 속삭이고 있어.",
		WALL_MOONROCK_ITEM = "상공에서 내려온 선물을 허비하지 않아야 해.",
		WALRUS = "바다의 노인이야.",
		WALRUSHAT = "이 아래에서 무슨 열띤 생각을 했을까?",
		WALRUS_CAMP =
		{
			EMPTY = "거기에 없다면 어디에 있을까?",
			GENERIC = "이 집은 행복하지 않네, 안타깝게도.",
		},
		WALRUS_TUSK = "너를 갉겠어.",
		WARDROBE = 
		{
			GENERIC = "애비게일에게 읽어주던 이야기가 생각나.",
            BURNING = "곧 재 밖에 남지 않을 거야.",
			BURNT = "아무 것도 떠올릴 수 없어.",
		},
		WARG = "진정한 악의 보루야.",
		WASPHIVE = "증오의 요새 안에 숨어있어.",
		WETGOOP = "삶처럼 비참한 진창이야.",
		WHIP = "통제할 수 있다는 환상만을 주지.",
		WINTERHAT = "다가오는 냉기를 물리쳐 주네.",
		WORMHOLE =
		{
			GENERIC = "삶은 부조리해.",
			OPEN = "무엇을 삼키든 만족하지 않아.",
		},
		ACCOMPLISHMENT_SHRINE = "메타포를 좋아한 적은 없어.",
		MOONROCKNUGGET = "멀리서 왔어...",
		ROCK_MOON = "너무 멀리서 왔어...",



		------------------------------capy---------------------------------

		AERODYNAMICHAT = "나는 공기를 가른다!",
		ANTIVENOM = "독을 물리칠 물약.",
		ARMOR_LIFEJACKET = "나는 마른 무덤을 선호해.",
		ARMOR_SNAKESKIN = "죽은 살로 만든 자켓. 패션이야.",
		ARMOR_WINDBREAKER = "바람의 덩굴손이 나를 잡을 수 없어!",
		ARMORLIMESTONE = "무거워...",
		ARMOROBSIDIAN = "불돌의 갑옷을 입는 것이 현명할까?",
		ARMORSEASHELL = "죽은 끈적한 덩어리의 집으로 만든 갑옷.",
		ARMOUREDBOAT = "공격을 받아도 끄떡없는 배.",
		BABYOX = "차가운, 텅 빈 눈...",
		BALLPHIN = "즐거운 꼬마네. 삶에 의미가 없다는 것을 알까?",
		BALLPHINPOD = "포드로서 헤엄치면 존재의 고독감을 없앨 수 있을까?",
		BAMBOO = "녹색 막대기... 관심 없어...",
		BAMBOOTREE = "A long blade could part you from your life.",
		BERMUDATRIANGLE = "어둠의 에너지가 신비 포털에 흐르고 있어...",
		BERRYBUSH2_SNAKE = "스낵인가, 아마?",
		BERRYBUSH_SNAKE = "스낵인가, 아마?",
		BIOLUMINESCENCE = "삶은 불가사의해! 하지만 죽음이 모든 것을 앗아가지.",
		BLOWDART_POISON = "속삭임으로 보내는 저주.",
		BOAT_INDICATOR = "Where shall I launch my hopeless craft?",
		BOAT_LANTERN = "캄캄한 밤의 광막한 공허를 보기 위한 것이야.",
		BOATCANNON = "망망대해에서 비참한 죽음을 불러와!",
		BOATREPAIRKIT = "이것으로 배가 파괴되는 것을 방지할 수 있겠어. 그럼 나도 안 죽겠네.",
		BOTTLELANTERN = "생명의 빛. 갇혔어.",
		BURIEDTREASURE = "죽은 자의 물건이야.",
		BUSH_VINE = "They look as if they want to choke something.",
		SNAKEDEN = "They look as if they want to choke something.",
		CAPTAINHAT = "살아있는 영혼이 바다에게 명령을 내릴 수는 없으니...",
		CARGOBOAT = "더 많은 쓰레기를 무(無)로 보내는 거야.",
		CHIMINEA = "바람의 거친 손가락으로부터 불을 보호할 거야.",
		CIRCLINGSEAGULL = "나는 고기야, 공중에 떠 있어. 착륙할 이유가 없으니까.",
		CLOTHSAIL = "돛을 달고 급히 달아날 수 있어. 하지만 어디로?",
		COCONADE = "A coconut filled with hot, fiery death.",
		COCONUT = 
		{
		    GENERIC = "갑옷 아래에 어떤 비밀을 담은 과일일까?",
		    PLANTED = "더 어두운 비밀을 기대하고 있었어.",
		},
		COFFEE = "어두워. 쓰네...",
		COFFEEBEANS = "흥분성으로 보여.",
		
		COFFEEBUSH = "This plant takes nourishment from fiery death.",
		CORAL = "바다가 생명을 주지만, 그들은 탈출하고 싶어서 팔을 뻗을 뿐.",
		CORALREEF = "바다에서 탈출하려고 산호가 성장하고 있어.",
		CRAB = "There is soft meat beneath that hard shell.",
		CRABHOLE = "구멍은 덮지 않은 무덤일 뿐이야.",
		CUTLASS = "죽일 때 양심의 가책을 느끼지 않을 거야. 도구일 뿐이니까.",
		DEAD_SWORDFISH = "검의 얼굴이 자신을 지켜주지 못했어...",
		DEPLETED_BAMBOOTREE = "가까스로 삶에 집착하고 있어.",
		DEPLETED_BUSH_VINE = "목조르는 덩굴 자체의 숨이 멎었어.",
		DOYDOY = "이 새는 살아있기에는 너무 멍청해.",
		DOYDOYBABY = "귀여워. 그리고 멍청해.",
		DOYDOYEGG = "바보 같은 알이야.",
		
		DOYDOYNEST = "하나 늘어날 때마다 섬의 평균 지성이 내려가. 동시에 고기 비축량은 늘어나지.",
		DUBLOON = "해적의 통화.",
		DUG_BAMBOOTREE = "시들까 아니면 살아날까?",
		DUG_BUSH_VINE = "너를 다시 심는 것이 진정으로 잔인한 거야.",
		DUG_COFFEEBUSH = "땅으로 돌아갈까?",
		EARRING = "하지만 귀가 없어...",
		FABRIC = "대나무가 이 새로운 형태를 마음에 들어할까?",
		FEATHERSAIL = "멍청한 새들의 재료로 빠른 돛을 만들었어.",
		FIRERAIN = "위에서 떨어지는 죽음!",
		FIRERAINSHADOW = "좋을 리가 없어.",
		FISHINHOLE = "고기가 빙글빙글 도네, 자기 운명도 모른 채.",
		FROG_POISON = "이것을 핥으면 악몽이 끝나겠지.",
		GASHAT = "이 모자는 죽음의 공기를 호흡하지 않게 막아주지.",
		GOLDENMACHETE = "대나무를 해칠 수 있는 고급 칼!",
		ICEMAKER = "My heart makes ice too.",
		IRONWIND = "운이 좋으면 지구의 가장자리에서 배가 떨어지겠지.",
		JELLYFISH = "이렇게 신기한 것이 생명체라니?",
		JELLYFISH_COOKED = "젤라틴 같아.",
		JELLYFISH_DEAD = "고통이 없는 죽음이었어. 짐승은 신경계가 없어.",
		JELLYFISH_PLANTED = "쏘여도 죽지 않아. 아플 뿐.",
		JELLYJERKY = "아주... 질겨.",
		JUNGLETREESEED =
        {
            GENERIC = "잠재성이 든 꾸러미야.",
            PLANTED = "더 이상 돌아갈 수 없네.",
        },
		LAVAPOOL = "화산의 분노로 타고 있는 웅덩이야!",
		LIMESTONE = "산호가 죽으면 돌로 경화해.",
		LIMPETS = "그들은 돌을 먹어, 나는 그들을 먹고.",
		
		LOBSTER = "죽은 다음에 버터를 발라 먹으면 아주 맛있겠어.",
		LOBSTERHOLE = "롭스터 만찬이 여기에 살아.",
		LOGRAFT = "무겁고, 느리고, 위험해 보여.",
		MACHETE = "날이 많아.",
		MESSAGEBOTTLE = "저주 받은 영혼의 마지막 절박한 행위. 병 안에 들어있어.",
		MESSAGEBOTTLEEMPTY = "비었어. 나의 영혼처럼.",
		MOSQUITO_POISON = "피 빠는 것으로도 모자라서 아프게 만드네.",
		MUSSEL = "파도 아래에서 숨을 수는 없어, 고기야!",
		MUSSEL_STICK = "홍합들이 막대기에 붙어있네. 바보들.",
		OBSIDIAN = "불로 만든 돌이야.",
		OBSIDIAN_WORKBENCH = "아, 불 아이템이 만들어지는 곳이야.",
		OBSIDIANAXE = "자르고 태우는 거야.",
		OBSIDIANCOCONADE = "나무의 아이들이 세계를 불태울 거야.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "포기하지마, 작은 불!",
			GENERIC = "공포를 물리치는 화염.",
			HIGH = "열정을 가지고 타는 불이야!",
			LOW = "살 의지를 잃고 있어.",
			NORMAL = "제작자의 분노가 불타네.",
			OUT = "다시 켜야겠어.",
		},
		OBSIDIANMACHETE = "물어뜯고 불태우는 날이야.",
		SPEAR_OBSIDIAN = "불로 찌르는 거야.",
		OBSIDIANSPEARGUN = "방아쇠를 당겨서 불을 던지는 거야.",
		OX = "고기가 무겁게 달려 있네. 내가 가볍게 만들어 줄게.",
		PACKIM = "물고기를 맡길 정도로 그를 믿지는 않지만, 잡동사니라면...",
		PACKIM_FISHBONE = "생선 시체. 중요해 보이네.",
		PALMLEAF = "잎이 쓰러진 나무를 애도할 것이라고 생각해.",
		PALMTREE =
		{
			BURNING = "물러서는 것이 좋아.",
			BURNT = "아름다운 검은색으로 변했어.",
			CHOPPED = "사랑스러운 파괴야.",
			GENERIC = "과일이 생기를 주지만, 내가 죽여야만 그럴 수 있어.",
		},
		PALMTREE_BURNT = "불로 맺은 종말이야.",
		PALMTREE_STUMP = "나무의 고통이 사라졌어.",
		PARROT = "내 귀가 이상한 것인가, 아니면 이 동물의 지저귐은 고독한 독백인 것일까?",
		PEACOCK = "예쁜 깃털이 맛있는 고기를 숨기고 있네!",
		PIRATEHAT = "살인자의 모자. 마음에 들어.",
		PIRATIHATITATOR = "This is but a step from madness.",
		POISONHOLE = "땅이 죽음의 공기를 통해.",
		RAFT = "파도에 몸을 맡기면 언니와 만날 수 있을지도 몰라.",
		ROWBOAT = "이것으로 몇 리나 갈 수 있을까?",
		SAIL = "바람을 받아서.. 무(無)를 향하여.",
		SAND = "모래가 자신의 무의미함을 알까?",
		SAND_CASTLE = "I suppose this diversion brings some comfort.",
		SANDBAG = "몰락을 멈추어주지. 잠시 동안...",
		SANDHILL = "영구해 보이지 않아.",
		SEAGULL = "땅과 바다의 청소 동물.",
		SEAGULL_WATER = "끔찍한 것들이 공기까지 탁하게 만드네.",
		SEASACK = "부패를 느리게 만들지.",
		SEASHELL = "안에 살던 것은 벌써 죽었을 거야.",
		SEATRAP = "오라, 바다의 동물들! 맛있는 간식을 즐겨라!",
		SEAWEED = "바다도 잡초가 가득해.",
		
		SEAWEED_PLANTED = "원기 왕성한 잡초.",
		SHARK_FIN = "더 이상 원하지 않을 거야.",
		SHARX = "바다의 공포!",
		SLOTMACHINE = "아, 합리적인 운명의 시험이네.",
		SNAKE = "팔이나 다리가 없으면 나도 화날 거야.",
		SNAKE_FIRE = "화산의 아이들. 불을 토하네.",
		SNAKE_POISON = "뱀보다 나쁜 것은 독뱀이야.",
		SNAKESKIN = "나의 도움으로 껍질을 벗는 거야.",
		SNAKESKINHAT = "죽은 자로부터 갈취한 트로피로 만든 모자!",
		SOLOFISH = "우아한 동작. 맛있는 살.",
		SPEAR_POISON = "한 번 찌르면 다 토하겠지.",
		SPEARGUN = "멀리서 죽음을 선사해!",
		SPEARGUN_POISON = "탄마다 숨막히는 독을 전달해.",
		STUNGRAY = "자신의 못생긴 모습으로부터 탈출하고 싶어해.",
		SUPERTELESCOPE = "쓸 데 없는 것들이 더 많이 보이네.",
		SWORDFISH = "이 물고기는 얼굴로 죽음을 절단해!",
		TELESCOPE = "그리움을 간직한 채 수평선 멀리 바라보네.",
		TIGERSHARK = "바다에서 만나는 주황색 줄무늬의 죽음!",
		TIGERSHARKSHADOW = "해난이야!",
		TORNADO = "자연의 굶주린 분노!",
		TOUCAN = "고통의 노래를 불러.",
		TRAWLNET = "바다의 손아귀로부터 아이템을 빼앗는 방법이야.",
		TRAWLNETDROPPED = "I wonder what this net pulled from the sea?",
		TRIDENT = "이것을 만든 사람들은 오래 전에 죽었어.",
		TRINKET_13 = "이것을 마시면 언니에게 돌아갈 수 있을지도 몰라.",
		TRINKET_14 = "이 인형에 핀을 꽂으면 누가 느낄까?",
		TRINKET_15 = "이것의 소유주는 더 이상 걷고 있지 않아.",
		TRINKET_16 = "이것의 주인의 종말은 나빴어.",
		TRINKET_17 = "이걸 착용했던 사람은 분명히 죽었어.",
		TRINKET_18 = "바다에서 사라진 문명의 잔재야.",
		TRINKET_19 = "소유자의 뇌가 이제 분명히 흐려졌을 거야.",
		TURBINE_BLADES = "더 이상 돌지 않아.",
		TURF_BEACH = "모래는 무덤을 채우는 적당한 재료가 아냐.",
		TURF_JUNGLE = "옹이지고 비틀어진 표면이야.",
		TWISTER = "아주 화난 자연!",
		VENOMGLAND = "죽어서 그 질병을 치료해주네.",
		VINE = "혼란스러운 삶.",
		VOLCANO = "하늘로 죽음을 분출하는 산!",
		VOLCANO_ALTAR = "The will of the volcano flows through this shrine!",
		VOLCANO_ALTAR_BROKEN = "안타까워. 더 이상 화염 무기를 만들 수 없어.",
		VOLCANO_EXIT = "이 뜨거운 죽음의 장소를 떠날까?",
		VOLCANOSTAFF = "화산의 불 같은 숨을 내가 조종하겠어!",
		WALL_LIMESTONE = "생명을 지킬 수 있는 죽은 재료의 벽.",
		WALL_LIMESTONE_ITEM = "살아있는 산호로 만든 벽이... 더 이상 아니지.",
		WHALE_BLUE = "슬퍼보여.",
		WHALE_CARCASS_BLUE = "이렇게 큰 것이 죽었으니 악취가 심하겠지.",
		WHALE_CARCASS_WHITE = "아주 크네. 그리고 아주 죽었어.",
		WHALE_WHITE = "불타는 눈에 삶에 대한 증오가 이글거려!",
		WOODLEGS_CAGE = "최소한 그의 영혼은 탈출했어.",
		VOLCANO_SHRUB = "이전과는 초라한 모습.",
		ROCK_OBSIDIAN = "만지면 화상을 입을까?",
		ROCK_CHARCOAL = "너가 원래 무엇이었는지 모르겠어.",
		DRAGOONDEN = "포악한 마음이 안에 들어있어.",

		ARMORCACTUS = "내 마음처럼 밖에도 가시가 있어!",
		BAMBOOTREE =
		{
			BURNT = "그렇게 끝나네.",
			CHOPPED = "이번에는 내가 이겼어.",
			GENERIC = "내 마음대로 구부릴 수 있어.",
		},
		BEEMINE_MAXWELL = "갇혀 있던 분노의 동물이 자유를 만끽하네.",
		BIGFISHINGROD = "경고했어, 바다의 동물들. 너희에게 죽음이 찾아올 거야.",
		BLOWDART_FLUP = "이제 누군가를 주시하면서 실제로 공격할 수 있어!",
		BLUBBER = "바보를 위한 완벽한 식사야.",
		BLUBBERSUIT = "불온하지만 아늑하네.",
		BOAT = "배야.",
		BOAT_TORCH = "빛나.",
		BRAINJELLYHAT = "나의 뇌를 크게 보이게 만드나?",
		BUOY = "떠라, 작은 친구야.",
		BUSH_VINE =
		{
			BURNT = "이것이 더 나아 보이는 것 같아.",
			CHOPPED = "희생을 헛되게 하지 않겠어.",
			GENERIC = "꽤 아름다워.",
		},
		COCONADE =
		{
			BURNING = "호 안에 수류탄!",
			GENERIC = "이걸로 누굴 폭사할 수 있을 거야.",
		},
		COCONUT_COOKED = "약간 달콤해.",
		COCONUT_HALVED = "하나였던 것이 둘이 되었어. 어디에 있니, 애비게일?",
		COFFEEBEANS_COOKED = "삶의 의지를 콩으로 얻을 수 있다는 것을 누가 알았을까?",
		COFFEEBOT = "난 블랙.",
		COFFEEBUSH =
		{
			BARREN = "에너지를 보충해야겠어.",
			GENERIC = "하늘이 준 콩 선물.",
			PICKED = "모든 상처는 시간이 지나면 치유가 돼, 작은 덤불아.",
			WITHERED = "나도 같은 느낌이야.",
		},
		COMPASS =
		{
			E = "동.",
			GENERIC = "방향이 없어.",
			N = "북.",
			NE = "북동.",
			NW = "북서.",
			S = "북. 아니, 남.",
			SE = "남동.",
			SW = "남서.",
			W = "서.",
		},
		CORAL_BRAIN = "나의 내부가 저렇게 생겼나?",
		CORAL_BRAIN_ROCK = "스마트해 보이는 식물이야.",
		CRAB =
		{
			GENERIC = "섬에 갑각류가 횡행하네.",
			HIDDEN = "언제까지나 문제를 회피할 수는 없어. 내가 해봤어.",
		},
		CRATE = "상자일 뿐이야.",
		DEPLETED_GRASS_WATER = "더 이상 없어.",
		DEVTOOL = "강한 냄새야.",
		DEVTOOL_NODEV = "그걸 사용할 수는 없어.",
		DIVININGRODSTART = "쓸 수 있겠어.",
		DOUBLE_UMBRELLAHAT = "과도해 보여.",
		DOYDOYEGG_COOKED = "아직 멸종하진 않았지만, 위태롭네.",
		DOYDOYEGG_CRACKED = "이것이 자비일 거야.",
		DOYDOYFEATHER = "칙칙한 세상을 위한 약간의 색.",
		DRAGOON = "사랑스러운 애완동물이 될 거야, \"살해\" 충동만 아니라면.",
		DRAGOONEGG = "끔찍한 괴물이 나온다는 것이 믿기 어려워.",
		DRAGOONHEART = "심장이 나의 것처럼 죽어있어, 내 것이 더 따뜻하지만.",
		DRAGOONSPIT = "우엑!",
		DUG_ELEPHANTCACTUS = "내가 옮겨야 하나?",
		ELEPHANTCACTUS = "슬프고 고통스러워.",
		ELEPHANTCACTUS_ACTIVE = "이 식물은 아무도 자기를 만지기 원하지 않아.",
		ELEPHANTCACTUS_STUMP = "아래에 숨어 있어.",
		FIREPIT =
		{
			EMBERS = "포기하지마, 작은 불!",
			GENERIC = "공포를 물리치는 화염.",
			HIGH = "열정을 가지고 타는 불이야!",
			LOW = "살 의지를 잃고 있어.",
			NORMAL = "위안이야.",
			OUT = "다시 켜야겠어.",
		},
		FISH_RAW = "머리가 잘렸어.",
		FISH_RAW_SMALL = "바다에는 다른 물고기도 있어. 더 큰 것들 말이야.",
		FISH_RAW_SMALL_COOKED = "지금은... 허기를... 달랠 수 있겠어.",
		FLAMEGEYSER = "뜨거워!",
		FLOTSAM = "어떻게 도달할 수 없어.",
		FLUP = "눈이 너무 많아!",
		FRESHFRUITCREPES = "여기에 아이스크림을 얹을 수 있을까?",
		GRASS_WATER = "축축해.",
		HAIL_ICE = "내 마음처럼 얼었어.",
		HOME = "펜스 재료는 아니네.",
		HOUNDFIRE = "타는군!",
		ICEMAKER =
		{
			HIGH = "뛰어난 상태야.",
			LOW = "약간 기운이 없어.",
			NORMAL = "괜찮은가 봐.",
			OUT = "포기했어.",
			VERYLOW = "내용물이 없어지고 있어.",
		},
		JUNGLETREE =
		{
			BURNING = "물러서는 것이 좋아.",
			BURNT = "아름다운 검은색으로 변했어.",
			CHOPPED = "사랑스러운 파괴야.",
			GENERIC = "정글 나무야.",
		},
		KNIGHTBOAT = "분노를 참지 못 하네!",
		KRAKEN = "무릎 꿇어, 지저분한 짐승아!",
		KRAKENCHEST = "어떠한 경이로움이 기다리고 있을까?",
		KRAKEN_TENTACLE = "오, 무서우셔라.",
		LIMPETROCK =
		{
			GENERIC = "좀 먹을만해... 보여.",
			PICKED = "깨끗하게 수확했어.",
		},
		LIVINGJUNGLETREE = "나의 느낌을 그대로 전달하는 겸손한 나무야.",
		LOBSTER_DEAD = "그는 조물주를 만났어. 나는 점심을 만났고.",
		LOBSTER_DEAD_COOKED = "잔치네!",
		LOG =
		{
			BURNING = "타는 통나무일 뿐.",
			GENERIC = "통나무일 뿐이야.",
		},
		LUGGAGECHEST = "아주 말쑥한 아이템 보관 시스템이야.",
		MAGIC_SEAL = "알 수 없는 힘이 박동하네.",
		MAGMAROCK = "지구의 위장이 냉각되어서 이제 파헤칠 수 있어.",
		MAGMAROCK_FULL = "지구의 위장이 냉각되어서 이제 파헤칠 수 있어.",
		MAGMAROCK_GOLD = "지구의 위장이 냉각되어서 이제 파헤칠 수 있어.",
		MAGMAROCK_GOLD_FULL = "지구의 위장이 냉각되어서 이제 파헤칠 수 있어.",
		MANDRAKE_COOKED = "이제 음식일 뿐이야.",
		MANGROVETREE = "꽤 우아해.",
		MANGROVETREE_BURNT = "안타깝네.",
		MARSH_PLANT_TROPICAL = "비참한 싹이네.",
		MERMFISHER = "이 동물의 동족 섭취 의지가 대단해.",
		MERMHOUSE_FISHER = "구식이군.",
		MONKEYBALL = "덜 고독하게 해주는 거야. 그리고 던질 수도 있어.",
		MONSTERTARTARE = "좋아 보이지만, 맛은 끔찍해.",
		MOSQUITOSACK_YELLOW = "사랑스런 토사물의 노란색.",
		MUSSELBOUILLABAISE = "보는 것만으로도 입에 군침이 돌아.",
		MUSSEL_COOKED = "내가 홍합을 압도했어.",
		MUSSEL_FARM =
		{
			GENERIC = "그리 강해 보이지 않아.",
			STICKPLANTED = "훗!",
		},
		MYSTERYMEAT = "그로테스크해.",
		NEEDLESPEAR = "이것으로 모든 것을 끝낼 수 있겠지.",
		OCTOPUSCHEST = "보관에 적절한 곳이 아닌 것 같아.",
		OCTOPUSKING = "그의 만족감이 부러워.",
		OXHAT = "말쑥해.",
		OX_FLUTE = "아픈 마음을 달래기 위해 연주해볼까.",
		OX_HORN = "소유자로부터 절단되었어.",
		PALMLEAF_HUT = "환영이다, 이 휴식.",
		PARROT_PIRATE = "내가 비밀을 말하면 안전하게 지킬까?",
		PEG_LEG = "하지만 다리 주인은 어디에 있을까?",
		PIGTENT = "돼지를 담요에 둘러싸는 곳이야.",
		PIKE_SKULL = "존재하지 않기를 선택했어.",
		PIRATEGHOST = "애비게일의 미래 친구?",
		PIRATEPACK = "더 많은 잡동사니를 소지할 수 있겠네.",
		PIRATIHATITATOR =
		{
			BURNT = "뭐였는지 모르지만 지금은 타버렸어.",
			GENERIC = "이것이 무엇일까.",
		},
		PORTAL_SHIPWRECKED = "나의 사랑하는 언니처럼, 절대로 돌아갈 수 없어.",
		PRIMEAPE = "거의 귀여울 정도로 즐거워 하네. 거의에 강조점.",
		PRIMEAPEBARREL = "더러워 보여.",
		RAWLING = "나에게 말을 해.",
		REDBARREL = "안전 위해 요소내. 마음에 들어.",
		RUBBLE = "부서진 돌은 쓸모 없어.",
		SAIL_STICK = "음... 막대기.",
		SANDBAGSMALL = "밀도가 높고 무겁네.",
		SANDBAGSMALL_ITEM = "휴대할 수 있는 흙 주머니군.",
		SANDBAG_ITEM = "이걸 들다간 허리를 다칠 거야.",
		SAND_CASTLE =
		{
			GENERIC = "그 아름다움이 조류에 휩쓸리겠지.",
			SAND = "시간의 모래를 주무르는 것이 이렇게 쉽다면 좋겠어.",
		},
		SEASHELL_BEACHED = "어여쁜 바다조개... 후, 무슨 소용이야.",
		SEAWEED_COOKED = "좋아, 하지만 여전히 잡초야.",
		SEAWEED_DRIED = "이러면 더 오래 가. 맛도 더 있고.",
		SHADOWSKITTISH_WATER = "앗.",
		SHARKITTEN = "이런 것들을 애완동물로 키우면서 늙어갈 수 있을 것 같아.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "냄새... 고양이 오줌인가?",
			INACTIVE = "큰 모래 더미다.",
		},
		SHARK_GILLS = "이제 아무도 이것을 통해 숨쉴 수는 없어.",
		SHARK_TEETHHAT = "세련되면서도 오싹해.",
		SHIPWRECKED_ENTRANCE = "두 배로 불가사의해.",
		SHIPWRECKED_EXIT = "다음 모험으로 전진.",
		SLURPERPELT = "비어있는 배고픔의 가방.",
		SNAKEDEN =
		{
			BURNT = "이것이 더 나아 보이는 것 같아.",
			CHOPPED = "희생을 헛되게 하지 않겠어.",
			GENERIC = "꽤 아름다워.",
		},
		SNAKEOIL = "불신이 생기는 물건이야.",
		SNAKESKINSAIL = "징그럽지만 효과적이야.",
		SPEAR_LAUNCHER = "창을 쏠 수 있다면 던질 필요가 없겠지?",
		SPOILED_FISH = "잘 가, 친구.",
		SUNKEN_BOAT =
		{
			ABANDONED = "혼자야?",
			GENERIC = "이 배가 들려줄 이야기가 궁금해.",
		},
		SUNKEN_BOAT_BURNT = "시적인 종말이야.",
		SUNKEN_BOAT_TRINKET_1 = "문진으로 쓸 뿐이야.",
		SUNKEN_BOAT_TRINKET_2 = "어떤 단순한 것이 이것으로 재미를 찾을까?",
		SUNKEN_BOAT_TRINKET_3 = "아주 젖었어.",
		SUNKEN_BOAT_TRINKET_4 = "그것이 무엇인지 모르겠어.",
		SUNKEN_BOAT_TRINKET_5 = "뻔하게 진부해.",
		SWEETPOTATOSOUFFLE = "섬세하면서 맛있어.",
		SWEET_POTATO = "달콤해. 나처럼.",
		SWEET_POTATO_COOKED = "나의 절망도 이것의 반만이라도 달콤했으면.",
		SWEET_POTATO_PLANTED = "점심 같아 보여.",
		SWEET_POTATO_SEEDS = "새로운 삶이 될 수 있지 않을까.",
		SWIMMINGHORROR = "그것과는 거리를 두고 싶어!",
		TELEPORTATO_SW_BASE = "뭔가 빠져있어.",
		TELEPORTATO_SW_BOX = "작은 나사 같아.",
		TELEPORTATO_SW_CRANK = "불완전해보여.",
		TREEGUARD = "아... 아니...",
		TELEPORTATO_SW_POTATO = "이것이 무슨 용도일까?",
		TELEPORTATO_SW_RING = "착용하는 용도가 아닐 거야.",
		THATCHPACK = "난 언제나 무거운 짐을 들기로 한 운명이었어.",
		TIDALPOOL = "이 맑은 풀을 보니 꿈 속에 애비게일이 나오는 것 같아.",
		TIDAL_PLANT = "날카로워.",
		TIGEREYE = "밝게 불타는 호랑이...",
		TRAWLNETDROPPED =
		{
			GENERIC = "바다로부터 건질 생물은 무엇일까?",
			SOON = "여행이 거의 끝났어.",
			SOONISH = "심해로의 여행이 시작됐어.",
		},
		TREASURECHEST_TRAP = "가끔은 내 마음대로 돼.",
		TREECLUMP = "이것을 고의적으로 둔 것일까?",
		TRINKET_20 = "문진으로 쓸 뿐이야.",
		TRINKET_21 = "어떤 단순한 것이 이것으로 재미를 찾을까?",
		TRINKET_22 = "아주 DIY네.",
		TRINKET_23 = "불운이야.",
		TROPICAL_FISH = "불쾌하게 밝아.",
		TUNACAN = "분명히 허위 광고일 거야.",
		TURF_ASH = "땅일 뿐이야.",
		TURF_DESERTDIRT = "땅일 뿐이야.",
		TURF_FUNGUS_GREEN = "땅일 뿐이야.",
		TURF_FUNGUS_RED = "땅일 뿐이야.",
		TURF_MAGMAFIELD = "땅일 뿐이야.",
		TURF_MEADOW = "땅일 뿐이야.",
		TURF_SNAKESKINFLOOR = "땅일 뿐이야.",
		TURF_SWAMP = "땅일 뿐이야.",
		TURF_TIDALMARSH = "땅일 뿐이야.",
		TURF_VOLCANO = "땅일 뿐이야.",
		TWISTER_SEAL = "이 세상의 추잡함을 모르고 있어.",
		VOLCANO_ALTAR =
		{
			GENERIC = "영업 중지야.",
			OPEN = "제물을 바쳐!",
		},
		VOLCANO_ALTAR_TOWER = "아름다운 죽음의 제단이야.",
		WALLYINTRO_DEBRIS = "배가 파괴되었어.",
		WATERMELON_SEEDS = "뱉기 위한 최적의 모양이야.",
		WATERYGRAVE = "무덤 약탈도 사양하지 않겠어.",
		WHALE_BUBBLES = "가스 문제가 있는 물고기 같아.",
		WHALE_TRACK = "고래, 호오!",
		WILBUR_CROWN = "왕들은 머리가 작은가봐.",
		WILBUR_UNLOCK = "화려함이 냄새를 가리지는 않아.",
		WILDBORE = "무엇이 그렇게 화가 나는 걸까?",
		WILDBOREHEAD = "아름다운 장식품이야.",
		WILDBOREHOUSE = "나를 초대하지 않겠지.",
		WIND_CONCH = "섬세한 조가비 안에 든 공포스러운 자연의 힘.",
		WOODLEGSBOAT = "항해에 적합한 배야!",
		WOODLEGSHAT = "해적 오뜨 꾸뛰르.",
		WOODLEGSSAIL = "디자인이 마음에 들어.",
		WOODLEGS_KEY1 = "어떤 불운한 자가 이것을 위해 뼈를 주었을까?",
		WOODLEGS_KEY2 = "뭔가 이상한 것을 잠금 해제했어.",
		WOODLEGS_KEY3 = "무엇을 여는 거지?",
		WORMHOLE_LIMITED = "짓밟힌 것으로 보여.",
		WRECK = "선원들은 아마 죽었을 거야...",
	},
	DESCRIBE_GENERIC = "입에 담을 수 없어.",
	DESCRIBE_TOODARK = "어둠이야! 이건 너무 어두워!",
	DESCRIBE_SMOLDERING = "화염이 곧 삼키겠네.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "세계를 보지도 못 했어.",
	},
}
