return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "좋아할 것 같지 않은데.",
			GENERIC = "털이 아닌 걸 깎을 수는 없잖아.",
			NOBITS = "이미 깎았잖아, 엉?",
            REFUSE = "내 수염 같잖아.",
		},
		STORE =
		{
			GENERIC = "토론토 시내 전차보다 더 붐비잖아.",
			NOTALLOWED = "가장 훌륭한 아이디어는 아니잖아, 엉?",
		},
		WRITE =
        {
            GENERIC = "아, 아니. 내 글씨체가 안 좋아서.",
        },
		RUMMAGE =
        {   
            GENERIC = "미안, 지금은 할 수 없잖아.", 
        },
		COOK =
        {
            GENERIC = "미안, 지금은 요리할 수 없잖아.",
            TOOFAR = "더 가까이 가야 하잖아, 엉?",
        },
        CHANGEIN =
        {
            GENERIC = "앗.",
            BURNING = "나무가 타는 것보다는 낫겠지.",
        },
        GIVE =
        {
            DEAD = "그들이... 음...",
            SLEEPING = "자고 있잖아.",
            BUSY = "나중에 다시 해보겠어.",
        },
		REPAIRBOAT =
		{
			GENERIC = "안 되잖아.",
		},
		TEACH =
        {
            KNOWN = "이미 아는 거잖아, 엉?",
            CANTLEARN = "어... 이 거 이해해, 루시?",
        },
	},
	ACTIONFAIL_GENERIC = "미안, 못하겠잖아.",
	ANNOUNCE_MAGIC_FAIL = "여기에서 쓸 수 없잖아, 엉.",
	ANNOUNCE_ADVENTUREFAIL = "어쩔 수 없지. 최대한 시도는 했잖아.",
	ANNOUNCE_BEES = "벌! 벌!",
	ANNOUNCE_BOOMERANG = "미안해! 내 잘못이잖아!",
	ANNOUNCE_CHARLIE = "누군가, 엉?",
	ANNOUNCE_CHARLIE_ATTACK = "윽! 거칠잖아!",
	ANNOUNCE_COLD = "좀 춥잖아!",
	ANNOUNCE_HOT = "여긴 너무 뜨겁잖아!",
	ANNOUNCE_CRAFTING_FAIL = "지금은 할 수 없잖아.",
	ANNOUNCE_DEERCLOPS = "저게 뭐냐?",
	ANNOUNCE_DUSK = "거의 잘 시간이잖아.",
	ANNOUNCE_NOSLEEPONFIRE = "그리 안전한지 모르겠잖아.",
	ANNOUNCE_NODANGERSIESTA = "뭐가 쫓아와서 낮잠을 못 자잖아.",
	ANNOUNCE_NONIGHTSIESTA = "낮잠은 밤이 아니라 나무 찍다가 휴식할 때 하는 게 좋지.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "낮잠은 밤이 아니라 나무 찍다가 휴식할 때 하는 게 좋지.",
	ANNOUNCE_NOHUNGERSIESTA = "배가 울잖아. 휴식을 취할 수 없잖아.",
	ANNOUNCE_SHELTER = "쉴 곳을 제공해 줘서 고맙다. 그래도 자를 것이지만.",
	ANNOUNCE_BURNT = "앗, 뜨겁잖아!",
	ANNOUNCE_TOOL_SLIP = "악몽에서 나오겠잖아!",
	ANNOUNCE_DAMP = "좀 젖었잖아, 엉?",
	ANNOUNCE_WET = "플래드는 젖어도 따뜻하잖아.",
	ANNOUNCE_WETTER = "젖고 있잖아, 엉?",
	ANNOUNCE_SOAKED = "루시를 꽉 잡아야겠잖아.",

	ANNOUNCE_OTHER_WORLD_PLANT = "틀린 흙이잖아, 엉?",

	ANNOUNCE_EAT =
	{
		GENERIC = "맛있잖아!",
		PAINFUL = "유효 기간이 지났잖아.",
		SPOILED = "좀 형편없잖아.",
		STALE = "완전히 썩기 전에 먹었잖아.",
		INVALID = "내 이빨로 자를 수 없잖아.",
		YUCKY = "차라리 블러버 공을 씹겠잖아.",
	},
	ANNOUNCE_ENTER_DARK = "누가 불껐잖아?",
	ANNOUNCE_ENTER_LIGHT = "광명이잖아!",
	ANNOUNCE_FREEDOM = "나왔잖아!",
	ANNOUNCE_HOUNDS = "밖에 뭔가 있잖아.",
	ANNOUNCE_HUNGRY = "배고파지고 있잖아.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "짐승이 근처에 있잖아.",
	ANNOUNCE_HUNT_LOST_TRAIL = "나는 사냥꾼이 나무꾼이니까.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "짐승의 흔적이 씻겨졌잖아.",
	ANNOUNCE_INV_FULL = "키트를 더 휴대할 수 없잖아.",
	ANNOUNCE_KNOCKEDOUT = "아. 저게 뭐냐?",
	ANNOUNCE_MOSQUITOS = "모기잖아!",
	ANNOUNCE_NODANGERSLEEP = "밖에서 자기엔 너무 무섭잖아.",
	ANNOUNCE_NODAYSLEEP = "못난 짜식만 낮에 자잖아.",
	ANNOUNCE_NOHUNGERSLEEP = "자기에는 배가 너무 비었잖아.",
	ANNOUNCE_NO_TRAP = "아슬아슬했잖아!",
	ANNOUNCE_PECKED = "미안해! 더 열심히 하겠어!",
	ANNOUNCE_QUAKE = "땅이 움직이잖아!",
	ANNOUNCE_THORNS = "앗!",
	ANNOUNCE_TORCH_OUT = "불이 꺼졌잖아!",
	ANNOUNCE_FAN_OUT = "이제 고생이잖아.",
    ANNOUNCE_COMPASS_OUT = "내 마음은 언제나 북쪽에 있잖아.",
	ANNOUNCE_TRAP_WENT_OFF = "아차!",
	ANNOUNCE_WORMHOLE = "안이 더러웠잖아!",
	ANNOUNCE_CANFIX = "\n고칠 수 있을 것 같아!",
	ANNOUNCE_ACCOMPLISHMENT= "루시가 날 자랑스워하겠네!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "됐잖아!",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "똥이 더 필요하잖아, 엉?",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "간지럽잖아, 엉?",

	ANNOUNCE_BOAT_DAMAGED = "배가 많이 손상을 입었잖아, 엉?",
	ANNOUNCE_BOAT_SINKING = "곧 가라앉잖아!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "잠기잖아!",
	ANNOUNCE_CRAB_ESCAPE = "도망갔잖아.",
	ANNOUNCE_HIGHRESEARCH = "유용한 정보잖아.",
	ANNOUNCE_LOWRESEARCH = "그럴 가치가 없잖아, 엉?",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "미지의 물로 들어가잖아!",
	ANNOUNCE_MAPWRAP_RETURN = "현명하지 못했잖아!",
	ANNOUNCE_MAPWRAP_WARN = "알려진 해역을 떠나는 거잖아...",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"바다가 서신을 지웠잖아.",
	},
	ANNOUNCE_MORETREASURE = "더 많은 금이잖아!",
	ANNOUNCE_NODAYSLEEP_CAVE = "지금은 잘 쉬지 못했잖아.",
	ANNOUNCE_NOWARDROBEONFIRE = "괜찮아. 좋은 플란넬만 있으면 되잖아.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "이것을 여기에서 찾을 수 있을 것 같지 않잖아.",
	ANNOUNCE_RESEARCH = "학습은 생각을 날카롭게 만들잖아. 도끼처럼.",
	ANNOUNCE_SHARX = "근처에 물고기가 있어... 그리고 배고픈 모양이잖아!",
	ANNOUNCE_TRAWL_FULL = "끌어당길 준비가 됐잖아!",
	ANNOUNCE_TREASURE = "황금광시대잖아!",
	ANNOUNCE_UNIMPLEMENTED = "앗! 아직 준비되지 않은 것 같잖아.",
	ANNOUNCE_VOLCANO_ERUPT = "윽, 날씨가 안 좋잖아, 엉?",
	ANNOUNCE_WAVE_BOOST = "북으로!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "내가 짐승을 잡기 위해 태어났잖아!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "흔적을 놓쳤잖아. 미안!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "고래가 어디로 갔나?!",

	BATTLECRY =
	{
		GENERIC = "여기 와라, 엉?",
		PIG = "널 베이컨으로 만들어겠잖아!",
		PREY = "여기서 끝이잖아!",
		SPIDER = "북으로!",
		SPIDER_WARRIOR = "잘려질 준비해라!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "그만하면 됐잖아.",
		PIG = "더 잘 될 줄 알았잖아.",
		PREY = "미안, 미안!",
		SPIDER = "미안해!",
		SPIDER_WARRIOR = "내일 같은 시간에 또 하자, 엉?",
	},
	DESCRIBE =
	{
		PIGMAN =
		{
			FOLLOWER = "우린 팀이잖아! 엉!",
			GENERIC = "보행하는 베이컨이잖아!",
			GUARD = "심각해 보이잖아.",
			WEREPIG = "일어날 수 있는 일이잖아.",
			DEAD = "더 이상 돼지가 아니잖아.",
		},
		GLOMMER = "계속 펄럭거려라, 작은 놈!",
        GLOMMERFLOWER = 
        {
        	GENERIC = "꽃도 점액투성이잖아.",
        	DEAD = "죽었는 데도 점액투성이잖아.",
        },
        GLOMMERWINGS = "당연히 날개가 점액투성이잖아.",
        GLOMMERFUEL = "음, 점액이 찐득하잖아.",
        BELL = "신기하게 시원한 소리 내잖아.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "이상한 조각상이잖아, 엉?",
        	EMPTY = "안에 멋진 게 있었잖아, 엉?",
    	},
		WEBBERSKULL = "두개골도 오싹해.",
		MOLE =
		{
			HELD = "바위 필요하냐?",
			UNDERGROUND = "파라, 파라, 파라.",
			ABOVEGROUND = "내가 나무에 느끼는 감정을 바위에 대해 느끼잖아.",
		},
		MOLEHILL = "안에 바위만 들었겠지.",
		MOLEHAT = "이제 밤에도 자를 수 있잖아!",
		NIGHTSTICK = "유용하잖아.",
		RABBITHOUSE=
		{
			GENERIC = "당근 맛인가?",
			BURNT = "구운 당근 맛인가?",
		},
		TURF_DECIDUOUS = "지면이잖아, 엉?",
		TURF_SANDY = "Just some ground, eh?",
		TURF_BADLANDS = "지면이잖아, 엉?",

		LAVA_POND_ROCK = "돌이잖아.",
		LAVA_POND_ROCK2 = "돌이잖아.",
		LAVA_POND_ROCK3 = "돌이잖아.",
		LAVA_POND_ROCK4 = "돌이잖아.",
		LAVA_POND_ROCK5 = "돌이잖아.",
		LAVA_POND_ROCK6 = "돌이잖아.",
		LAVA_POND_ROCK7 = "돌이잖아.",

		BEARGER = "큰 곰이잖아!",
		BEARGERVEST = "제대로 된 겨울 옷이잖아.",
		CAVE_BANANA_BURNT = "낭비잖아.",
		SCORCHED_SKELETON = "앗.",
		ICEPACK = "오래 하이킹할 때 좋잖아.",
		BEARGER_FUR = "내 머리만큼 두껍잖아!",
		BIGFOOT = "조심히 밟아라!",
		BONESHARD = "빵 만드는 법을 알았으면 좋겠네.",
		BUZZARD = "내 고기 간식에서 떨어져!",
		CACTUS = 
		{
			GENERIC = "아프겠잖아.",
			PICKED = "그렇지.",
		},
		CACTUS_MEAT_COOKED = "더 낫잖아.",
		CACTUS_MEAT = "누가 입에 못을 넣냐?",
		CACTUS_FLOWER = "이 기후에 뭐가 자란다는 게 신기하잖아.",
		COLDFIRE =
		{
			EMBERS = "거의 다 사라졌잖아.",
			GENERIC = "더 집 같아지겠잖아.",
			HIGH = "엉! 좀 높잖아!",
			LOW = "뭔가 해야겠지, 엉?",
			NORMAL = "저녁에 켠 차가운 불이 좋지.",
			OUT = "있는 동안은 좋았잖아.",
		},
		CATCOON = "염병할.",
		CATCOONDEN = 
		{
			GENERIC = "엉, 넌 목숨이 몇 개냐?",
			EMPTY = "잘 없어졌잖아.",
		},
		CATCOONHAT = "나무꾼의 전통 의상이잖아.",
		COONTAIL = "저 고양이의 이야기는 끝났잖아.",
		COOKPOT =
		{
			COOKING_LONG = "좀 더 길겠네, 엉?",
			COOKING_SHORT = "저런! 오잖아!",
			DONE = "저녁 식사 시간!",
			EMPTY = "저기에 빈 채로 두는 것은 낭비잖아.",
			BURNT = "바삭하게 탔잖아.",
		},
		EYEBRELLAHAT =	"위에서 내려다 보는 게 있으면 좋잖아.",
		ARMORDRAGONFLY = "갑옷은 플래드로 족하잖아.",
		DRAGON_SCALES = "그래도 난 용의 존재를 안 믿잖아.",
		DRAGONFLYCHEST = "촌스럽잖아.",
		DECIDUOUSTREE = 
		{
			BURNING = "아니! 내가 자를 수 있었는데!",
			BURNT = "낭비거든.",
			CHOPPED = "아!",
			GENERIC = "나를 부르잖아!",
			POISON = "너 자를 시기가 됐잖아.",
		},
		ACORN_COOKED = "완벽하게 좋은 나무의 낭비잖아.",
		BIRCHNUTDRAKE = "너도 자를 것이잖아!",
		FARMPLOT =
		{
			GENERIC = "난 더 큰 식물이 좋잖아.",
			GROWING = "자를 정도로 절대 커지지 않을 거야.",
			NEEDSFERTILIZER = "거름이 필요하잖아.",
			BURNT = "나무 농장이었으면 슬펐을 거잖아.",
		},
		COLDFIREPIT =
		{
			EMBERS = "저걸 위해 나무를 베어야겠지, 엉?",
			GENERIC = "나무를 쓰잖아.",
			HIGH = "나무를 너무 빨리 너무 많이 쓰고 있잖아!",
			LOW = "여기 어딘가에 나무가 있겠지.",
			NORMAL = "흠. 나무 냄새 나잖아.",
			OUT = "나무가 있으면 좋겠잖아.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "나무를 살려!",
			OFF = "게으르잖아.",
			LOWFUEL = "나무를 원하잖아.",
		},
		ICEHAT = "필요하면 자를 수 있잖아.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "좋은 뿔 가지고 있잖아, 너.",
			CHARGED = "착하지, 염소야!",
		},
		LIGHTNINGGOATHORN = "네 뿔이 내 뿔이잖아.",
		GOATMILK = "전기 때문에 굳었잖아.",
		MEATRACK =
		{
			DONE = "된 것으로 보이잖아.",
			DRYING = "고기 마르는 걸 보는 것 같잖아.",
			DRYINGINRAIN = "빗속에서 고기가 마르는 걸 보는 것 같잖아.",
			GENERIC = "설치했잖아. 고기만 추가하면 되잖아.",
			BURNT = "유용함이 사라졌잖아.",
		},
		MERMHEAD = 
		{
			GENERIC = "대형 트롤선 냄새가 나잖아.",
			BURNT = "신기하게 악취가 심해졌잖아.",
		},
		MERMHOUSE = 
		{
			GENERIC = "편리한 것은 아니잖아.",
			BURNT = "불에 안 타는 집을 지을 수도 없잖아.",
		},
		FLOWERSALAD = "건강에 좋지만 몸을 튼튼하게 만들진 않잖아.",
        ICECREAM = "많이 자른 다음에 먹자!",
        WATERMELONICLE = "나무와 식품?!",
        TRAILMIX = "도끼질한 다음에 먹기 좋은 간식이잖아.",
        HOTCHILI = "추운 날에 하루 종일 나무 자른 다음에 좋지.",
        GUACAMOLE = "신뢰가 안 가잖아.",
		MOOSE = "분명히 캐나다에서 온 거잖아.",
		MOOSEEGG = "알을 낳는다고 하잖아.",
		MOSSLING = "보송보송한 말코손바닥사슴 아기!",
		FEATHERFAN = "전통 캐나다 부채.",
		TROPICALFAN = "여기 오후의 열기는 싫잖아!",
		MINIFAN = "여기의 열기는 피할 수가 없잖아!",
		GOOSE_FEATHER = "베개에 쓰는 깃털이잖아.",
		STAFF_TORNADO = "나무는 내가 자르는 걸 선호하잖아.",
		PIGHEAD = 
		{	
			GENERIC = "좋은 돈육 낭비잖아.",
			BURNT = "요리사에게 불평해야겠잖아, 상냥하게.",
		},
		PIGHOUSE =
		{
			FULL = "베이컨이 들어찼잖아.",
			GENERIC = "청테이프 있으면 고칠 수 있잖아.",
			LIGHTSOUT = "미안해! 몰래 안 봐, 정말!",
			BURNT = "이전 영광은 사라지고 폐허만 남았잖아.",
		},
		FERTILIZER = "똥은 땅이 아니라 통에 들어있어야 하잖아.",
		RAINOMETER = 
		{	
			GENERIC = "비오면 나무가 자라지.",
			BURNT = "비에 대한 지식이 타는 걸 방지하지 않았잖아.",
		},
		RAINCOAT = "빗속에서 도끼질할 때 쓰잖아.",
		RAINHAT = "자를 때는 언제나 머리가 젖지 않게 해야 하잖아.",
		RESEARCHLAB = 
		{	
			GENERIC = "과학은 믿을 수 없잖아.",
			BURNT = "어떻게 탄 거지?!",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "이상해지고 있잖아.",
			BURNT = "기본 물리 법칙을 따르는 것 같긴 하잖아.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "아, 이제 알겠잖아.",
			BURNT = "음, 사라졌잖아.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "\"모자 기계\"라고 부를 수 있잖아!",
			BURNT = "이래서 내가 모자 보온기를 안 쓰잖아.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "나무로 만들어진 내 모습이 좋잖아.",
			BURNT = "타면 별로 안 좋아 보이잖아.",
		},
		ROCK_ICE = 
		{
			GENERIC = "집이 최고잖아!",
			MELTED = "고향에서는 안 녹잖아.",
		},
		ROCK_ICE_MELTED = "고향에서는 안 녹잖아.",
		ICE = "주머니에 고향을 담는 거잖아.",
        REFLECTIVEVEST = "플래드가 전천후 의류가 아니라고 하는 말은 믿을 수 없어.",
		HAWAIIANSHIRT = "실은 플래드를 선호하잖아.",
		TENT = 
		{
			GENERIC = "더 허름한 곳에서 많이 잤지.",
			BURNT = "이젠 천막이 아니잖아.",
		},
		SIESTAHUT = 
		{
			GENERIC = "도끼질 하루 종일 할 때는 낮잠이 중요하잖아.",
			BURNT = "깍지잖아.",
		},
		TRANSISTOR = "어떻게 작동하는지 추측도 하기 싫잖아.",
		TREASURECHEST = 
		{
			GENERIC = "나무는 유용해! 수많은 걸 만들 수 있잖아!",
			BURNT = "나무도 단점이 있긴 하잖아...",
		},
		TUMBLEWEED = "더 튼튼하면 내가 자를 수 있을 텐데.",
		GRASS_UMBRELLA = "수염을 적당히 젖지 않게 해주겠잖아, 엉?",
		PALMLEAF_UMBRELLA = "우산 잘 만든 것 같잖아.",
		WALL_HAY = 
		{	
			GENERIC = "재채기하면 쓰러지겠어.",
			BURNT = "금방 탔잖아.",
		},
		WALL_WOOD = 
		{
			GENERIC = "좋잖아!",
			BURNT = "이전의 네 모습이 그립구나.",
		},
		WARDROBE = 
        {
        	GENERIC = "숲에서는 옷을 더럽힐 수 밖에 없잖아.",
            BURNING = "나무는 타는 게 전문이잖아.",
        	BURNT = "이제 유용하지 않잖아, 엉?",
    	},
		WARG = "저건 혼자서도 썰매를 당길 수 있잖아.",
		WATERMELON = "어떻게 물이면서 멜론일 수 있지?",
		WATERMELON_COOKED = "구운 과일 맛은 믿음이 안 가...",
		WATERMELONHAT = "날 수박 아저씨라고 불러라.",
		WINTEROMETER = 
		{
			GENERIC = "고향에서 절반 높이로 만들 수 있잖아.",
			BURNT = "고향에 있는 건 안 타잖아.",
		},
		WORMLIGHT = "이거 유용하겠잖아.",
		WORM =
		{
		    PLANT = "식물이 어떻게 생겼는지는 알아. 이건 가짜잖아!",
		    DIRT = "움직이는 땅을 조심해.",
		    WORM = "벌레!",
		},
		EEL = "요리 잘 되겠잖아.",
		EEL_COOKED = "요리 잘 됐잖아.",
		UNAGI = "날 채워주잖아.",
		EYETURRET = "짜식들을 내쫓겠지.",
		EYETURRET_ITEM = "올바르게 설치하자.",
		MINOTAURHORN = "좋은 뿔이네, 엉.",
		MINOTAURCHEST = "뿔 달린 좋은 궤짝이잖아, 엉.",
		THULECITE_PIECES = "나무는 아니지만 쓸 수 있잖아.",
		POND_ALGAE = "식용으로 보이지 않잖아.",
		GREENSTAFF = "분해하는 것을 보조하지!",
		POTTEDFERN = "식물의 삶을 사랑하는 나의 마음을 표현하잖아.",

		THULECITE = "동굴의 나무잖아!",
		ARMORRUINS = "안 아프게 하겠지.",
		RUINS_BAT = "막대기에 달린 금속이잖아.",
		RUINSHAT = "토크는 아니지만 쓰자.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "꺼졌잖아.",	--calm phase
			WARN = "켜졌잖아!",	--Before nightmare
			WAXING = "떨리잖아!", --Nightmare Phase first 33%
			STEADY = "미쳤잖아!", --Nightmare 33% - 66%
			WANING = "꺼지는 중이잖아.", --Nightmare 66% +
			DAWN = "거의 멈췄잖아.", --After nightmare
			NOMAGIC = "꺼졌잖아.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "내부 작동이 보이잖아!",
		ROOK_NIGHTMARE = "기어가 튀어나고 있잖아.",
		KNIGHT_NIGHTMARE = "최고 상태가 아닌 것 같잖아.",
		MINOTAUR = "저주당한 불쌍한 놈이 또 있잖아.",	--Monster in labyrinth
		SPIDER_DROPPER = "부패한 곳을 피해 사는 것이 현명하잖아.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "나무를 썼어야 하잖아.",	--Lights that activate during nightmare.
		RELIC = "Piece of furniture.",	--Fixed relic
		RUINS_RUBBLE = "다 망가졌잖아.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "아... 아름답잖아.",	--Works as axe and pickaxe
		GREENGEM = "번뜩이잖아.",
		ORANGESTAFF = "빨리 돌아다니는 데 도움되겠어.",	--Teleports player.
		YELLOWAMULET = "이걸로 밤에 도끼질해야지.",	--Emits light, player walks faster.
		GREENAMULET = "어차피 나는 자르는 것이 특기잖아.",	--Reduce cost of crafting

		SLURPER = "살아있는 털 같잖아.",
		SLURPER_PELT = "죽은 비버 같잖아.",
		SLURPERPELT = "Where's the nearest fur trader?",
		ARMORSLURPER = "간지럽잖아. 아직 살아있잖아.",
		SPIDERHOLE_ROCK ="다시 나오기 전 내빼야겠잖아.",
		ORANGEAMULET = "허드렛일이 금방 되겠네!",
		YELLOWSTAFF = "어쩔 수 없다면 쓸모 있잖아!",
		YELLOWGEM = "안에 별이 보이잖아.",
		ORANGEGEM = "반짝이잖아.",
		RELIC =
		{
			BROKEN = "I don't plan on fixin' that.",
			GENERIC = "What's this all aboot?",
		},
		TELEBASE = 
		{
			VALID = "It's humming with energy.",
			GEMS = "I don't think it has power.",
		},
		GEMSOCKET = 
		{
			VALID = "준비된 것으로 보이잖아.",
			GEMS = "보석이 필요하잖아.",
		},
		STAFFLIGHT = "신기하잖아.",	
		LUCY = "루시가 좋아!",
        ANCIENT_ALTAR =
        {
        	WORKING = "제단 돌에 도끼 자국이 있잖아.",
        	BROKEN = "좀 헐어 보이잖아.",
        },             
        ANCIENT_ALTAR_BROKEN = "좀 헐어 보이잖아.",
        ANCIENT_STATUE = "짜식.",
        LICHEN = "겨우 먹을 수 있겠네.",
		CUTLICHEN = "냠! 나무 맛이잖아!",
		CAVE_BANANA = "열대의 맛이잖아.",
		CAVE_BANANA_COOKED = "왠지 몰라도 요리했잖아.",
		CAVE_BANANA_TREE = "고향에는 저런 게 없지.",
		ROCKY = "바닷가재 저녁 시간!",
		
		COMPASS =
		{
			GENERIC="진북을 향하잖아.",
			N = "진북.",
			S = "남.",
			E = "동.",
			W = "서.",
			NE = "북동.",
			SE = "남동.",
			NW = "북서.",
			SW = "남서.",
		},

		BLUEAMULET = "이제 음료를 시원하게 할 수 있잖아.",
		PURPLEAMULET = "보석의 광채가 사라졌잖아.",
		TELESTAFF = "Just another use for wood.",
		MONKEY = "뭐냐. 새로운 거잖아.",
		MONKEYBARREL = "훌륭한 건설 재료잖아.",

		HOUNDSTOOTH="아름답잖아.",
		ARMORSNURTLESHELL="과도하게 안전할 수는 없잖아.",
		BAT="누가 쥐한테 나는 법 가르쳤냐?",
		BATBAT = "날개 달린 쥐?",
		BATWING="징그럽잖아!",
		BATWING_COOKED="징그럽잖아! 맛있잖아! 헷갈리잖아!",
		BATCAVE = "작은 동물이 많이 들어있잖아!",
		
		BEDROLL_FURRY="내가 캠핑을 좋아하잖아.",
		BUNNYMAN="우호적으로 보이잖아.",
		FLOWER_CAVE="반짝이거든!",
		FLOWER_CAVE_DOUBLE="반짝이거든!",
		FLOWER_CAVE_TRIPLE="반짝이거든!",
		GUANO="다른 것보다 악취가 덜 나잖아.",
		LANTERN="빛이잖아, 엉?",
		LIGHTBULB="질겨 보이잖아.",
		MANRABBIT_TAIL="불쌍한 놈이잖아.",
		MUSHTREE_TALL  ="I can't let that stand.",
		MUSHTREE_MEDIUM="Maybe I should chop it.",
		MUSHTREE_SMALL ="It's made of wood.",
		MUSHTREE_TALL=
		{
            GENERIC = "저걸 그냥 둘 순 없잖아.",
            BLOOM = "퍼지기 전에 잘라야겠잖아!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "잘라야겠잖아.",
            BLOOM = "색이 마음에 들잖아.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "나무로 만들어졌잖아.",
            BLOOM = "지금은 자를 수 없잖아...",
        },
        MUSHTREE_TALL_WEBBED = "잔가지를 쳐야겠잖아.",
        SPORE_TALL = "비행하는 솔방울이잖아!",
        SPORE_MEDIUM = "비행하는 솔방울이잖아!",
        SPORE_SMALL = "비행하는 솔방울이잖아!",
        SPORE_TALL_INV = "언젠가는 나무가 되겠잖아.",
        SPORE_MEDIUM_INV = "언젠가는 나무가 되겠잖아.",
        SPORE_SMALL_INV = "언젠가는 나무가 되겠잖아.",
		SLURTLE="그냥 오해 받는 거잖아.",
		SLURTLE_SHELLPIECES="내가 집을 망가뜨렸잖아. 미안하다.",
		SLURTLEHAT="내 머리를 안전하게 지켜줄 거야.",
		SLURTLEHOLE="여기서 잘 지내냐?",
		SLURTLESLIME="화장지가 필요하잖아.",
		SNURTLE="나선!",
		SPIDER_HIDER="간사한 악마!",
		SPIDER_SPITTER="침 뱉는 것은 무례하잖아!",
		SPIDERHOLE="다시 나오기 전 내빼야겠잖아.",
		STALAGMITE="바위에는 별로 관심 없잖아.",
		STALAGMITE_FULL="바위에는 별로 관심 없잖아.",
		STALAGMITE_LOW="바위에는 별로 관심 없잖아.",
		STALAGMITE_MED="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL_FULL="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL_LOW="바위에는 별로 관심 없잖아.",
		STALAGMITE_TALL_MED="바위에는 별로 관심 없잖아.",


		TURF_CARPETFLOOR = "Some ground.",
		TURF_CHECKERFLOOR = "Some ground.",
		TURF_DIRT = "Some ground.",
		TURF_FOREST = "Some ground.",
		TURF_GRASS = "Some ground.",
		TURF_MARSH = "Some ground.",
		TURF_ROAD = "Some ground.",
		TURF_ROCKY = "Some ground.",
		TURF_SAVANNA = "Some ground.",
		TURF_WOODFLOOR = "Some ground.",

		TURF_CAVE="지면이야.",
		TURF_FUNGUS="완두콩처럼 걸쭉하잖아.",
		TURF_SINKHOLE="지하에서 찾았잖아.",
		TURF_UNDERROCK="바위잖아. 별로.",	
		TURF_MUD="적어도 치울 필요는 없잖아.",

		
		POWCAKE = "진짜 설탕하고 버터로 만든 게 좋지.",
        CAVE_ENTRANCE = "막혔잖아.",
        CAVE_ENTRANCE_RUINS = "막혔잖아.",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "어차피 아래에 나무가 없잖아.",
            OPEN = "서드버리 같잖아.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "나중에 하자. 여기가 편하잖아.",
            OPEN = "올라가면 나무가 있겠지.",
        },
		
		MAXWELLPHONOGRAPH = "라디오에 나오는 것보다 낫잖아.",
		BOOMERANG = "던지기 어렵잖아.",
		PIGGUARD = "저놈 화나게 만들지 말자.",
		ADVENTURE_PORTAL = "저기가 출구일까.",
		AMULET = "언제나 예비 계획이 필요하잖아.",
		ANIMAL_TRACK = "거대한 숲 동물이 여길 지나갔잖아!",
		ARMORGRASS = "없는 것보다 낫잖아.",
		ARMORMARBLE = "이걸 착용하고 도끼 휘두르기 어렵잖아.",
		ARMORWOOD = "나에게 잘 맞는잖아!",
		ARMOR_SANITY = "욕지기나게 하잖아.",
		ASH =
		{
			GENERIC = "다 탔잖아.",
			REMAINS_GLOMMERFLOWER = "점액성 꽃이었잖아.",
			REMAINS_EYE_BONE = "눈뼈였잖아.",
			REMAINS_THINGIE = "저것을 통과하지 않잖아.",
		},
		AXE = "루시만큼 좋지 않지.",
		BABYBEEFALO = "어미만 사랑할 수 있는 얼굴이잖아.",
		BACKPACK = "내 륙색이잖아.",
		BACONEGGS = "오호. 앞쪽 베이컨이잖아.",
		BANDAGE = "그래도 돈은 안 냈잖아.",
		BASALT = "저 바위는 안 움직일 거잖아.",
		BEARDHAIR = "내 머리카락 색이 아니잖아. 수염 색말이야.",
		BEDROLL_STRAW = "목재 캠프에서 저것보다 더 후진 것에 누워서 잔 적도 있잖아.",
		BEE =
		{
			GENERIC = "꽃을 자라게 하고 있잖아.",
			HELD = "이제 이것으로 무엇을 하냐?",
		},
		BEEBOX =
		{
			FULLHONEY = "단풍당밀 시럽 대용품이잖아!",
			READY = "단풍당밀 시럽 대용품이잖아!",
			GENERIC = "벌이잖아!",
			NOHONEY = "보는 것만으로도 배고프잖아.",
			SOMEHONEY = "기다리면 더 가질 수 있잖아.",
			BURNT = "아니, 벌은 안돼!",
		},
		BEEFALO =
		{
			FOLLOWER = "날 좋아하잖아.",
			GENERIC = "헛간 냄새나잖아.",
			NAKED = "힘내라, 엉?",
			SLEEPING = "잠에 취했잖아.",
		},
		BEEFALOHAT = "이제 내가 고기물소 왕이잖아!",
		BEEFALOWOOL = "내 수염 같은 느낌이잖아.",
		BEEHAT = "벌이 눈에 들어가는 걸 막아주잖아.",
		
		BEEHIVE = "편하게 들어있잖아.",
		
		BEEMINE = "벌의 마음에 들지 모르겠잖아.",
		BEEMINE_MAXWELL = "어이! 못된 것!",
		BERRIES = "이것으로 내 식욕을 채울 순 없잖아.",
		BERRIES_COOKED = "따뜻한 베리 맛이 나잖아.",
		BERRYBUSH =
		{
			BARREN = "거름이 필요하잖아.",
			WITHERED = "열 때문에 죽었잖아, 엉?",
			GENERIC = "사스카툰 베리?",
			PICKED = "베리가 안 남았잖아!",
		},
		BIRDCAGE =
		{
			GENERIC = "못된 새들을 교화하는 공간이잖아.",
			OCCUPIED = "반성해라, 새!",
			SLEEPING = "꿈꿀 때는 정말 순해 보이잖아.",
			HUNGRY = "곧 먹을 수 있게 해줄게.",
			STARVING = "감자 튀김을 원하잖아!",
			DEAD = "미안. 널 실망시켰잖아.",
			SKELETON = "냄새 나기 시작하잖아.",
		},
		BIRDTRAP = "새들한테 본때를 보여줘야겠잖아!",
		BIRD_EGG = "저 새가 못된 새 생각하잖아.",
		BIRD_EGG_COOKED = "적어도 새가 되지는 않았잖아.",
		BISHOP = "마지막으로 고백 성사했는지 오래 됐잖아.",
		BLOWDART_FIRE = "좀 저돌적이잖아.",
		BLOWDART_SLEEP = "이것을 쓰면 탈출할 수 있겠잖아!",
		BLOWDART_PIPE = "나의 거대한 폐활량으로 뭘 할 수 있는지 볼까!",
		BLUEGEM = "아주 차갑잖아.",
		BLUEPRINT = "내가 책 보고 배우는 스타일이 아니잖아.",
		BELL_BLUEPRINT = "내가 책 보고 배우는 스타일이 아니잖아.",
		BLUE_CAP = "고기가 아니잖아.",
		BLUE_CAP_COOKED = "고기가 아니잖아.",
		BLUE_MUSHROOM =
		{
			GENERIC = "먹을 수 있는 게 뭔지 도대체 기억할 수 없잖아.",
			INGROUND = "나중에 돌아오지.",
			PICKED = "끝났습니다.",
		},
		BOARDS = "아주 매끄럽잖아. 나뭇결이 제대로 보이네.",
		BOAT = "강한 북동풍에 맞았잖아.",
		BONESTEW = "먹으면 든든하잖아.",
		BUGNET = "모기 수집용이잖아.",
		BUSHHAT = "자연에서 숨는 데 좋잖아.",
		BUTTER = "난 마가린이 더 좋잖아.",
		BUTTERFLY =
		{
			GENERIC = "내가 그걸 믿은 적이 없잖아, 엉?",
			HELD = "어디로 도망가냐?",
		},
		BUTTERFLYMUFFIN = "우두둑! ...하지만 부드럽잖아?",
		BUTTERFLYWINGS = "미안해! 내가 나쁜 놈이!",
		CAMPFIRE =
		{
			EMBERS = "거의 다 사라졌잖아.",
			GENERIC = "내 기타가 어딨나?",
			HIGH = "엉! 좀 높잖아!",
			LOW = "뭔가 해야겠지, 엉?",
			NORMAL = "저녁에 켠 불이 좋지.",
			OUT = "있는 동안은 좋았잖아.",
		},
		CANE = "벽촌에서 유용하지.",
		CARROT = "토끼 음식이잖아.",
		CARROT_COOKED = "토끼 요리잖아.",
		CARROT_PLANTED = "난 야채 싫잖아, 엉?",
		CARROT_SEEDS = "작은 당근.",
		CAVE_FERN = "어이! 양치류다!",

		CHARCOAL = "좀 슬퍼지잖아.",

        CHESSJUNK1 = "죽은 금속이잖아.",
        CHESSJUNK2 = "죽은 금속이잖아.",
        CHESSJUNK3 = "죽은 금속이잖아.",

		CHESTER = "최선을 다하고 있잖아!",
		CHESTER_EYEBONE =
		{
			GENERIC = "노려보는 게 무례하다고 가르쳐 준 자가 없는 모양이잖아.",
			WAITING = "다시 일어날까.",
		},
		COOKEDMANDRAKE = "나쁜 짓이었나?",
		COOKEDMEAT = "어머니가 만들어준 그 맛이잖아.",
		COOKEDMONSTERMEAT = "그래도 먹기 싫잖아.",
		COOKEDSMALLMEAT = "더 배고프게 만들잖아!",
		CORN = "좋지만, 먹는 것에 다 넣을 필요는 없잖아.",
		CORN_COOKED = "옥수수를 잘 요리했잖아.",
		CORN_SEEDS = "나는 흙 가는 사람이 아니라 나무 자르는 사람이잖아.",
		CROW =
		{
			GENERIC = "뭔가 계획하고 있어. 분명해.",
			HELD = "너 벌 받을 거다, 까마귀!",
		},
		CUTGRASS = "이것에 알러지 반응이 있는 것 같잖아.",
		CUTREEDS = "물새 부르는 소리 들려줄까?",
		CUTSTONE = "캐나다 순상지의 일부잖아.",
		DEADLYFEAST = "냄새가 영 아니지, 엉.",
		DEERCLOPS = "큰 말코손바닥사슴이잖아!",
		DEERCLOPS_EYEBALL = "어디에 쓰는 물건이냐?",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불인 것 같잖아.",
		},
		DEVTOOL = "할 말 없다.",
		DIRTPILE = "엇! 실마리잖아!",
		DIVININGROD =
		{
			COLD = "여기선 흐릿하잖아.",
			GENERIC = "하키 경기를 이해할까.",
			HOT = "크고 뚜렷하잖아! 근처에 뭐가 있잖아!",
			WARM = "가까워지는 것 같잖아.",
			WARMER = "조심하자.",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "무언가 삽입해야 할 것 같잖아.",
			READY = "잠금 해제할 준비가 됐잖아.",
			UNLOCKED = "이제 켜기만 하면 되잖아.",
		},
		DIVININGRODSTART = "이상하게 생긴 막대잖아.",
		DRAGONFLY = "내가 자르기 전에 저것이 나무를 다 태우겠잖아!",
		LAVAE = "도끼로 죽이자!",
		LAVAE_PET = 
		{
			STARVING = "학다리보다 더 가늘잖아.",
			HUNGRY = "불쌍한 것이 배고파하잖아.",
			CONTENT = "정말 행복해 보이잖아!",
			GENERIC = "작은 생물이잖아.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "안에서 불이 타고 있잖아.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "파카가 필요하겠잖아.",
			COMFY = "청테이프로 감은 말코손바닥사슴보다 따뜻하잖아!",
		},
		LAVAE_TOOTH = "루시만큼 날카롭지는 않잖아!",

		LAVASPIT = 
		{
			HOT = "아악! 나무 살해자!",
			COOL = "내 나무가 이제 안전하잖아.",
		},
		LAVA_POND = "너무 가까이 가면 안 좋잖아, 엉?",
		DRAGONFRUIT = "이런 것은 본 적 없어.",
		DRAGONFRUIT_COOKED = "단풍당밀 맛이잖아.",
		DRAGONFRUIT_SEEDS = "더 키울 수 있잖아.",
		DRAGONPIE = "거의 버터 타트만큼 좋잖아!",
		DRUMSTICK = "10월 음식이잖아.",
		DRUMSTICK_COOKED = "고맙다, 칠면조.",
		DUG_BERRYBUSH = "조경에 손대볼까.",
		DUG_GRASS = "눈물 나잖아.",
		DUG_MARSH_BUSH = "심어야지.",
		DUG_SAPLING = "음. 약하잖아.",
		DURIAN = "나쁜 냄새잖아.",
		DURIAN_COOKED = "냄새가 더 나쁘잖아.",
		DURIAN_SEEDS = "왜 이걸 더 재배하냐?",
		EARMUFFSHAT = "고향에서는 가을에만 이걸 쓰잖아.",
		EGGPLANT = "새들의 짓이겠지.",
		EGGPLANT_COOKED = "수상하게 새랑 연관이 있잖아.",
		EGGPLANT_SEEDS = "흠. 모르겠잖아.",
		ACORN = 
		{
		    GENERIC = "키운 다음에 잘라야겠잖아!",
		    PLANTED = "나무가 나올 거잖아!",
		},
		EVERGREEN =
		{
			BURNING = "아니! 내가 자를 수 있었는데!",
			BURNT = "낭비거든.",
			CHOPPED = "아!",
			GENERIC = "나를 부르잖아!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "미안해!",
			BURNT = "안타깝잖아!",
			CHOPPED = "하나 더!",
			GENERIC = "루시가 자르라고 하네.",
		},
		EYEPLANT = "자기 일이나 신경 쓰라 그래.",
		FEATHERHAT = "저건 상대하기... 싫잖아.",
		FEATHER_CROW = "더러운 깃털이잖아.",
		FEATHER_ROBIN = "넌더리 나는 깃털이잖아.",
		FEATHER_ROBIN_WINTER = "바보 같은 깃털.",
		FEM_PUPPET = "잡혔잖아!",
		FIREFLIES =
		{
			GENERIC = "앨곤퀸 공원이 생각나잖아.",
			HELD = "햇빛이 한 주머니 가득!",
		},
		FIREHOUND = "뜨거운 개!",
		FIREPIT =
		{
			EMBERS = "저걸 위해 나무를 베어야겠지, 엉?",
			GENERIC = "나무를 쓰잖아.",
			HIGH = "나무를 너무 빨리 너무 많이 쓰고 있잖아!",
			LOW = "여기 어딘가에 나무가 있겠지.",
			NORMAL = "흠. 나무 냄새 나잖아.",
			OUT = "나무가 있으면 좋겠잖아.",
		},
		FIRESTAFF = "마법 짓거리는 몸 믿겠으니까.",
		FISH = "대구 같잖아.",
		FISHINGROD = "호수에서 시간을 보내야겠잖아.",
		FISHSTICKS = "상자 안의 고급 식사다.",
		FISHTACOS = "바다 맛이잖아.",
		FISH_MED = "식사가 되고 싶어 하잖아.",
		FISH_MED_COOKED = "감자칩이 있으면 좋겠잖아.",
		FISH_COOKED = "감자칩이 있으면 좋겠잖아.",
		FLINT = "도끼날로 써도 되겠잖아.",
		FLOWER = "좋잖아.",
		FLOWER_WITHERED = "누구 손가락이 갈색이 되었겠잖아.",
		FLOWERHAT = "들꽃이 내 빨간 머리와 어울리잖아.",
		FLOWER_EVIL = "꽃이 뭔가 문제 있잖아.",
		FOLIAGE = "샐러드 같잖아.",
		FOOTBALLHAT = "이거 쓰면 머리카락이 엉망이 될려나?",
		FROG =
		{
			DEAD = "개구리였잖아.",
			GENERIC = "공기와 물 중에서 선택하지 못하는 건 못 믿겠잖아.",
			SLEEPING = "피곤하잖아.",
		},
		FROGGLEBUNWICH = "늪의 맛을 제대로 느낄 수 있잖아.",
		FROGLEGS = "아직도 뛰잖아!",
		FROGLEGS_COOKED = "적어도 움직이는 것은 멈췄어.",
		FRUITMEDLEY = "시럽 추가!",
		GEARS = "난 이런 거 이해 못하잖아.",
		GHOST = "으악! 하하!",
		GOLDENAXE = "거의 루시만큼 좋잖아.",
		GOLDENPICKAXE = "예쁘지만 나무를 자를 수 없잖아.",
		GOLDENPITCHFORK = "쯧. 다시 분해할 수는 없으니까...",
		GOLDENSHOVEL = "황금 구멍을 팔 시간이잖아.",
		GOLDNUGGET = "금으로 커피 테이블을 만들 수 없잖아.\n어쩌면 될지도 모르지. 그래도 하지 말아야지.",
		GRASS =
		{
			BARREN = "여기에 똥 싸야 되잖아.",
			WITHERED = "좀 더 서늘하면 살았을까?",
			BURNING = "나무에 번지지 않았으면 하잖아.",
			GENERIC = "불쏘시개 같아.",
			PICKED = "맨 땅이 됐네.",
		},
		GREEN_CAP = "숲에서 이것보다 더 이상한 것 먹었잖아.",
		GREEN_CAP_COOKED = "안 믿어.",
		GREEN_MUSHROOM =
		{
			GENERIC = "녹색 버섯이잖아.",
			INGROUND = "자기 스케줄이 있는 놈이잖아.",
			PICKED = "내가 망가뜨린 것 같잖아.",
		},
		GUNPOWDER = "이걸 좋아한 적이 없지.",
		HAMBAT = "좋은 햄 낭비잖아.",
		HAMMER = "누구나 실수하잖아, 엉?",
		HEALINGSALVE = "건강에 좋은 죽이잖아.",
		HEATROCK =
		{
			FROZEN = "춥다! 얼었잖아.",
			COLD = "차가워졌잖아, 엉?",
			GENERIC = "고향에서는 이걸 \"밤의 바위\"라고 하잖아.",
			WARM = "좀... 뜨뜻해지잖아.",
			HOT = "주머니 안에 저게 있으면 겨울 내내 나무를 벨 수 있잖아!",
		},
		HOME = "누구냐?",
		HOMESIGN = 
		{
			GENERIC = "나무가 할 수 없는 것도 있냐?",
			BURNT = "나무는 타는 게 전문이잖아.",
		},
		HONEY = "으흐음. 벌 시럽이잖아.",
		HONEYCOMB = "이걸 가져가서 거의 죄책감 느껴지잖아.",
		HONEYHAM = "하지만 휴일이 아니잖아...",
		HONEYNUGGETS = "내가 좋아하는 식사잖아!",
		HORN = "내가 왜 이것에 입을 대야 하냐.",
		HOUND = "썰매 당길 때 좋잖아.",
		HOUNDBONE = "개 침으로 덮였잖아, 엉?",
		HOUNDMOUND = "저거랑 상대 안 하는 게 낫지.",
		ICEBOX = "아! 고향 생각나네.",
		ICEHOUND = "북극 개냐?",
		INSANITYROCK =
		{
			ACTIVE = "어디 갔지?!",
			INACTIVE = "어떻게 움직일 수 있는 모르잖아.",
		},
		JAMMYPRESERVES = "이제 땅콩버터만 찾으면 되잖아.",
		KABOBS = "막대가 맛에 정말 영향을 주잖아.",
		KILLERBEE =
		{
			GENERIC = "저 벌은 우호적으로 보이지 않잖아.",
			HELD = "그리 기쁘지 않은 모양이잖아.",
		},
		KNIGHT = "맥스웰의 말 탄 경찰이잖아.",
		KOALEFANT_SUMMER = "맛있어 보이잖아.",
		KOALEFANT_WINTER = "겨울에 더 맛있어지잖아.",
		KRAMPUS = "물러서라, 짜식아!",
		KRAMPUS_SACK = "남의 자루를 가져가면 미안한데.",
		LEIF = "나무 때문에 미안하다!",
		LEIF_SPARSE = "나무 때문에 미안하다!",
		LIGHTNING_ROD =
		{
			CHARGED = "오로라처럼 예쁘잖아.",
			GENERIC = "이제 벼락 맞을 일 없잖아.",
		},
		LITTLE_WALRUS = "왜 이렇게 많이 남쪽으로 왔나?",
		LIVINGLOG = "넌 내 거야 이제, 그리고 널 \"프랭크\"라고 부르겠어.",
		LOCKEDWES = "저 자식 누구야?",
		LOG =
		{
			BURNING = "안 돼! 불에 통나무를 더 넣지 마!",
			GENERIC = "보람있잖아.",
		},
		LUREPLANT = "고기잖아?",
		LUREPLANTBULB = "따뜻하고 튀어나왔잖아.",
		MALE_PUPPET = "도와줄까?",
		MANDRAKE =
		{
			DEAD = "미안해, 작은 놈.",
			GENERIC = "나를 보고 있잖아.",
			PICKED = "내가 뭘 한 거지?",
		},
		MANDRAKESOUP = "피곤한 수프잖아.",
		MANDRAKE_COOKED = "미안해!",
		MARBLE = "정부 건물 같잖아.",
		MARBLEPILLAR = "누군가가 만들었겠지.",
		MARBLETREE = "루시도 그건 못 자르잖아.",
		MARSH_BUSH =
		{
			BURNING = "흠!",
			GENERIC = "나무딸기잖아.",
			PICKED = "그럴 가치가 있었나?",
		},
		MARSH_PLANT = "잡풀이잖아.",
		MARSH_TREE =
		{
			BURNING = "뾰족하면 그렇게 되잖아!",
			BURNT = "인과응보잖아.",
			CHOPPED = "어려운 싸움, 하지만 내가 이겼잖아.",
			GENERIC = "나무가 왜 반격하냐!",
		},
		MAXWELL = "왜 나를 싫어하냐?",
		MAXWELLHEAD = "그냥 머리잖아, 엉?",
		MAXWELLLIGHT = "부자연스럽잖아.",
		MAXWELLLOCK = "열쇠 어딨어?",
		MAXWELLTHRONE = "이거보다 나은 의자 봤잖아.",
		MEAT = "말코손바닥사슴 맛이 나잖아.",
		MEATBALLS = "다 고기다!",
		MEAT_DRIED = "생존의 맛이잖아.",
		MERM = "어떤 끔찍한 바다에서 튀어나왔지?",
		MINERHAT = "석탄 광산 깊숙이.",
		MONSTERLASAGNA = "고양이 음식이잖아!",
		MONSTERMEAT = "그걸 먹을 정도로 배고프지 않잖아.",
		MONSTERMEAT_DRIED = "그래도 먹기 싫잖아.",
		MOSQUITO =
		{
			GENERIC = "내 피 한 바가지!",
			HELD = "이걸로 뭘 하나, 엉?",
		},
		MOSQUITOSACK = "피와 내장, 엉?",
		MOUND =
		{
			DUG = "미안! 날 쫓지 마!",
			GENERIC = "저걸 내버려 두는 게 낫겠지.",
		},
		NIGHTLIGHT = "저건 무슨 어둠이냐?",
		NIGHTMAREFUEL = "나의 모든 두려움을 액체로 만들었냐, 엉?",
		
		NIGHTSWORD = "악몽은 해치지 않잖아!",
		NITRE = "철도를 만든 방법이잖아.",
		ONEMANBAND = "너를 보호해 주겠잖아!",
		PANDORASCHEST = "상자 안에 뭐가 있는 거냐?!",
		PANFLUTE = "나는 루시만을 위해 노래 부르잖아.",
		PAPYRUS = "글을 쓰느니 자르겠잖아.",
		PENGUIN = "흰 대륙에서 와도 상관없지. 그래도 새잖아.",
		PERD = "새가 더 있잖아! 왜 새가 많냐?",
		PEROGIES = "난 \"맛 주머니\"라고 부르잖아.",
		PETALS = "루시가 이걸 좋아할까.",
		PETALS_EVIL = "작고 못된 얼굴로 나한테 찡그리잖아.",
		PHLEGM = "수염에 안 걸리면 좋겠잖아.",
		PICKAXE = "도끼 같지만, 아니잖아.",
		PIGGYBACK = "돼지의 모든 부위를 썼잖아.",
		PIGKING = "나의 왕이 아니잖아.",
		PIGSKIN = "꼬리 달린 베이컨이잖아.",
		PIGTORCH = "엄지 없이 어떻게 저걸 할 수 있지?",
		PINECONE = 
		{
		    GENERIC = "키운 다음에 잘라야겠잖아!",
		    PLANTED = "나무가 나올 거잖아!",
		},
		LUMPY_SAPLING = "흠, 다시 잘라야겠잖아.",
		PITCHFORK = "이건 진짜 내 스타일이 아니잖아.",
		PLANTMEAT = "추잡하잖아!",
		PLANTMEAT_COOKED = "요리했는 데 도움이 안 되잖아.",
		PLANT_NORMAL =
		{
			GENERIC = "무엇이 될까.",
			GROWING = "바라보고 있으면 식물이 안 자라잖아.",
			READY = "캘 때가 됐잖아.",
			WITHERED = "생명이 없잖아, 엉?",
		},
		POMEGRANATE = "나한테는 너무 고급이잖아.",
		POMEGRANATE_COOKED = "플랩잭에 잘 어울리겠네.",
		POMEGRANATE_SEEDS = "씨 많거든.",
		POND = "난 수영 못하잖아!",
		POOP = "캠프에서 똥 싸지 마!",
		PUMPKIN = "땅에서 자라는 건 먹기 싫은데.",
		PUMPKINCOOKIE = "계속 자를 수 있게 해주잖아.",
		PUMPKIN_COOKED = "파이가 좋잖아.",
		PUMPKIN_LANTERN = "쓰러뜨리지 말자.",
		PUMPKIN_SEEDS = "씨잖아.",
		PURPLEGEM = "자르면 다 해결되잖아.",
		RABBIT =
		{
			GENERIC = "제기랄 땅 다람쥐...",
			HELD = "먹으면 미안하겠지.",
		},
		RABBITHOLE = 
		{
			GENERIC = "아래에 나무가 없겠지.",
			SPRING = "들어가는 거나 나가는 게 없잖아.",
		},
		RATATOUILLE = "사발 안의 숲같잖아.",
		RAZOR = "진짜 벌목꾼은 면도하지 않잖아.",
		REDGEM = "수천 그루의 나무가 불타는 죽음이 보이잖아.",
		RED_CAP = "모르겠잖아...",
		RED_CAP_COOKED = "너무 배고파지면.",
		RED_MUSHROOM =
		{
			GENERIC = "빨간 버섯이잖아.",
			INGROUND = "자기 스케줄이 있는 놈이잖아.",
			PICKED = "내가 망가뜨린 것 같잖아.",
		},
		REEDS =
		{
			BURNING = "불 보면 불안해.",
			GENERIC = "갈대.",
			PICKED = "돌아오겠지.",
		},
        RUBBLE = "부서진 가구잖아.",
		RESURRECTIONSTONE = "만져야 할지 모르겠잖아.",
		ROBIN =
		{
			GENERIC = "추잡한 못된 놈.",
			HELD = "편하게 있지 마.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "남쪽으로 날아가던가 해라!",
			HELD = "내 온기를 빼앗고 있잖아.",
		},
		ROBOT_PUPPET = "갇혔잖아!",
		ROCK_LIGHT =
		{
			GENERIC = "껍질이 느껴지잖아.",
			OUT = "부서질 것 같잖아.",
			LOW = "나무가 더... 필요한가?",
			NORMAL = "나무가 필요 없는 불? 부자연스럽잖아!",
		},
		ROCK = "노력하면 부술 수 있어.",
		ROCKS = "괜찮은 이눅슈크가 되겠잖아.",
        ROOK = "흠... 루크가 직선으로 움직이던가? 까먹었잖아.",
		ROPE = "물건 묶을 때 쓰잖아.",
		ROTTENEGG = "새 한 마리 줄었잖아. 좋지.",
		SANITYROCK =
		{
			ACTIVE = "바위가 이상하지, 엉?",
			INACTIVE = "말 되잖아.",
		},
		SAPLING =
		{
			BURNING = "오! 기회를 박탈당했잖아!",
			WITHERED = "이 열로는 자를 수 있을 정도로 자라지 않잖아!",
			GENERIC = "크는 걸 본 다음에 잘라야겠잖아.",
			PICKED = "따는 건 자르는 것만큼 재밌지 않잖아.",
		},
		SEEDS = "나무가 아냐.",
		SEEDS_COOKED = "\"벌목꾼의 깜짝선물\"이라고 부르잖아.",
		SEWING_KIT = "내가 바느질 잘 하지.",
		SHOVEL = "구멍을 판다. 나무를 심는다!",
		SILK = "거미는 오싹해.",
		SKELETON = "미안해, 친구.",
		SKELETON_PLAYER = "끔찍하잖아.",
		SKULLCHEST = "무시무시하잖아!",
		SMALLBIRD =
		{
			GENERIC = "뭘 원하냐?",
			HUNGRY = "뭔가 원하잖아.",
			STARVING = "굶고 있잖아.",
		},
		SMALLMEAT = "더 컸으면 좋겠잖아.",
		SMALLMEAT_DRIED = "한 입만.",
		SPAT = "엄마가 생각나는구나!",
		SPEAR = "묵직한 게 좋은 도끼 같지 않잖아.",
		SPIDER =
		{
			GENERIC = "본 거미 중에서 가장 크잖아!",
			SLEEPING = "조심해야겠잖아, 엉?",
			DEAD = "좋잖아!",
		},
		SPIDERDEN = "으앗! 저걸 봐라!",
		SPIDEREGGSACK = "저걸 왜 들고 다녀?",
		SPIDERGLAND = "독이잖아.",
		SPIDERHAT = "진짜 예쁘지, 엉?",
		SPIDERQUEEN = "너가 내 여왕이 아니잖아!",
		SPIDER_WARRIOR =
		{
			GENERIC = "이제 노란색도 있잖아?",
			SLEEPING = "맞을려고 잠자잖아.",
			DEAD = "좋아!",
		},
		SPOILED_FOOD = "디펜베이커 꼴이잖아.",
		STATUEHARP = "머리를 잃었나, 엉?",
		STATUEMAXWELL = "못된 놈이지, 엉?",
		STEELWOOL = "도끼를 다시 빛나게 해주겠잖아.",
		STINGER = "앗! 뾰족하잖아.",
		STRAWHAT = "해를 가려 주잖아.",
		STUFFEDEGGPLANT = "요리 실력이 늘고 있잖아.",
		SUNKBOAT = "저 나무도 좋은 시절이 있었잖아.",
		SWEATERVEST = "플래드는 아니지만 입겠어.",
		TAFFY = "설탕. 좋잖아.",
		TALLBIRD = "나도 나는 새는 믿지 못하잖아.",
		TALLBIRDEGG = "안에 뭐가 들었지?",
		TALLBIRDEGG_COOKED = "정의의 맛이잖아.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "너에겐 너무 춥나?",
			GENERIC = "부화하고 있잖아.",
			HOT = "울고 있나?",
			LONG = "새는 시간을 안 지키잖아.",
			SHORT = "빨리.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "알을 훔쳐서 혼내 줘야겠잖아.",
			PICKED = "아무 것도 없잖아.",
		},
		TEENBIRD =
		{
			GENERIC = "그 부모처럼 커서 못된 놈이 되려고 하잖아.",
			HUNGRY = "넌 언제나 배고프냐?",
			STARVING = "배고파서 사나워지잖아.",
		},
		TELEBASE =
		{
			VALID = "그건 준비됐는데, 나도 준비됐나?",
			GEMS = "보석이 필요하잖아, 엉?",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "준비됐나, 엉?",
			GENERIC = "마법... 물건이잖아.",
			LOCKED = "부품이 없잖아, 엉?",
			PARTIAL = "거의 됐잖아, 엉?",
		},
		TELEPORTATO_BOX = "상자, 엉?",
		TELEPORTATO_CRANK = "크랭크, 엉?",
		TELEPORTATO_POTATO = "감자, 엉?",
		TELEPORTATO_RING = "고리, 엉?",
		TELESTAFF = "이게 뭘 하는 것일까.",
		TENTACLE = "아래에 오징어 있나?",
		TENTACLESPIKE = "흔들면 휘어지잖아.",
		TENTACLESPOTS = "얼굴 빨개진다!",
		TENTACLE_PILLAR = "엄청 크잖아!",
		TENTACLE_PILLAR_HOLE = "그루터기도 안 남았잖아!",
		TENTACLE_PILLAR_ARM = "오징어 아기인가?",
		TENTACLE_GARDEN = "오징어, 짜증나잖아!",
		TOPHAT = "너무 고급이잖아.",
		TORCH = "횃불 나무.",
		TRAP = "똑똑하게 살라고, 엉?",
		TRAP_TEETH = "이건 좀 거칠잖아.",
		TRAP_TEETH_MAXWELL = "정정당당하게 싸우는 게 아니잖아, 엉?",
		TREASURECHEST_TRAP = "궤짝이 뭔가 수상하잖아.",
		MOOSE_NESTING_GROUND = "싫잖아.",
		TRINKET_1 = "그 게임을 한 적이 있었지.",
		TRINKET_10 = "노인을 위한 까뀌.",
		TRINKET_11 = "조용히 해!",
		TRINKET_12 = "다 시들었잖아.",
		TRINKET_2 = "진짜가 아니잖아, 엉?",
		TRINKET_3 = "전에 들었던 이야기가 생각나네.",
		TRINKET_4 = "나한테 묻지 마.",
		TRINKET_5 = "로봇 팔이 필요한 거야, 엉?",
		TRINKET_6 = "더 이상 안 좋잖아, 엉?",
		TRINKET_7 = "이건 몇 시간이고 가지고 놀 수 있잖아!",
		TRINKET_8 = "욕조만 있으면 되잖아.",
		TRINKET_9 = "착용하고 옷을 기워버리잖아.",
		TRUNKVEST_SUMMER = "시원해서 좋잖아.",
		TRUNKVEST_WINTER = "고향 겨울도 견디겠잖아, 엉?",
		TRUNK_COOKED = "끓여서 콧물이 증발한 것 같잖아.",
		TRUNK_SUMMER = "꽤 얇잖아.",
		TRUNK_WINTER = "두껍고 털 많잖아.",
		TURF_CARPETFLOOR = "나한텐 너무 고급이잖아.",
		TURF_CHECKERFLOOR = "도시 사람 화장실 바닥 같잖아.",
		TURF_DIRT = "지면이잖아, 엉?",
		TURF_FOREST = "지면이잖아, 엉?",
		TURF_GRASS = "지면이잖아, 엉?",
		TURF_MARSH = "지면이잖아, 엉?",
		TURF_ROAD = "지면이잖아, 엉?",
		TURF_ROCKY = "지면이잖아, 엉?",
		TURF_SAVANNA = "지면이잖아, 엉?",
		TURF_WOODFLOOR = "제왕의 바닥재잖아!",
		TURF_DRAGONFLY = "여긴 불 있어도 괜찮나, 엉?",
		TURF_DESERTDIRT = "Just some ground, eh?",
		TURF_FUNGUS_GREEN = "Just some ground, eh?",
		TURF_FUNGUS_RED = "Just some ground, eh?",
		TURKEYDINNER = "칠면조 먹는 날이 돌아왔잖아!",
		TWIGS = "이걸 자르려면 작은 도끼를 만들어야겠잖아.",
		BANANAPOP = "난 메이플 태피가 더 좋은데...",
		BISQUE = "영양가가 많잖아.",
		CEVICHE = "안 먹으면 바보잖아.",
		SEAFOODGUMBO = "고향에는 이런 게 없잖아.",
		SURFNTURF = "좋은 음식이잖아.",
		SHARKFINSOUP = "이제부터 내 배 안에서 헤엄칠 거잖아.",
		LOBSTERDINNER = "연어가 낫잖아.",
		LOBSTERBISQUE = "섬의 요리치고 꽤 좋잖아.",
		JELLYOPOP = "섬의 디저트잖아, 엉?",
		UMBRELLA = "수염을 젖지 않게 해주겠지, 엉?",
		UNIMPLEMENTED = "안전해 보이지 않잖아.",
		WAFFLES = "난 플랩잭이 더 좋아.",
		WALL_HAY_ITEM = "재채기하면 쓰러지겠어.",
		WALL_STONE = "안전한가, 엉?",
		WALL_STONE_ITEM = "안전한가, 엉?",
		WALL_RUINS = "무너지고 있지만 안전해, 엉?",
		WALL_RUINS_ITEM = "또 돌 맞았나, 엉?",
		WALL_WOOD_ITEM = "좋잖아!",
		WALL_MOONROCK = "튼튼해 보이잖아.",
		WALL_MOONROCK_ITEM = "이래서는 쓸모 없잖아.",
		WALRUS = "안돼. 또 바다코끼리잖아!",
		WALRUSHAT = "할아버지께서 이런 모자를 썼잖아.",
		WALRUS_CAMP =
		{
			EMPTY = "겨울이 되면 안전하지 않을 거잖아.",
			GENERIC = "근처에 바다코끼리가 있잖아, 엉?",
		},
		WALRUS_TUSK = "충치 구멍 있었잖아, 엉?",
		WASPHIVE = "벌이 왜 화났냐?",
		WORMLIGHT_LESSER = "비버의 배보다 더 쭈글쭈글하잖아.",
		WETGOOP = "먹었던 것 중 최악은 아니잖아!",
        WHIP = "작은 동물을 해치지 않았으면 좋겠잖아.",
		WINTERHAT = "좋은 모자네, 엉?",
		WORMHOLE =
		{
			GENERIC = "거지 같잖아!",
			OPEN = "들여다보고 싶지 않은데, 엉?",
		},
		WORMHOLE_LIMITED = "좀 상한 냄새 나잖아, 엉?",
		ACCOMPLISHMENT_SHRINE = "너무 젠체하는 것 같잖아.",  
		BISHOP_CHARGE_HIT = "야!",        		
		LIVINGTREE = "모순된 느낌이잖아, 엉?",
		ICESTAFF = "고향 생각나잖아.",
		MOONROCKNUGGET = "달의 돌이잖아.",
        ROCK_MOON = "음, 달돌이잖아.",

		------------------------------capy---------------------------------

		WOODLEGS_CAGE = "안에 있어도 괜찮나?",

		TWISTER = "대자연이 화났잖아!",
		WIND_CONCH = "종 29개의 소리가 들리잖아.",

		AERODYNAMICHAT = "가속도 모자잖아.",
		ANTIVENOM = "맛이 나쁘지만 효과 있잖아!",
		ARMORCACTUS = "뾰족한 가시로 보호하잖아, 엉?",
		ARMORLIMESTONE = "힘 나게 만들어주잖아.",
		ARMOROBSIDIAN = "뜨겁잖아, 엉?",
		ARMORSEASHELL = "강해 보이지 않잖아.",
		ARMOR_LIFEJACKET = "약간의 보험이잖아.",
		ARMOR_SNAKESKIN = "멋있어 보이잖아.",
		ARMOR_WINDBREAKER = "아주 편하잖아, 엉.",
		ARMOUREDBOAT = "바다에서 가장 안전한 것이잖아.",
		BABYOX = "다 수염이잖아.",
		BALLPHIN = "친구, 기술 알아?",
		BAMBOO = "다이어트 나무 같잖아, 엉?",
		BAMBOOTREE =
		{
			BURNT = "베이컨처럼 타잖아, 엉?",
			CHOPPED = "잘 잘랐잖아!",
			GENERIC = "루시가 너무 즐겼잖아.",
		},
		BERMUDATRIANGLE = "좀 으스스하잖아, 엉?",
		BIGFISHINGROD = "큰 막대를 들고 성큼성큼 걷잖아.",
		BIOLUMINESCENCE = "오로라 같잖아.",
		BLOWDART_FLUP = "눈을 쏴라!",
		BLOWDART_POISON = "주 정맥을 맞추라고, 엉?",
		BLUBBER = "그만 바보처럼 굴어라.",
		BLUBBERSUIT = "그리 멋있지 않잖아.",
		BOATCANNON = "쾅, 터뜨리겠잖아!",
		BOATREPAIRKIT = "수리하는 거잖아, 엉?",
		BOAT_LANTERN = "보트 라이트잖아.",
		BOAT_TORCH = "밤낚시할 수 있잖아.",
		BOTTLELANTERN = "뭐야, 그 안에서 괜찮나?",
		BRAINJELLYHAT = "이걸 쓰면 좀 똑똑해지잖아.",
		BUOY = "떠다니는 인생. 맞는 말이잖아.",
		BURIEDTREASURE = "팔 시간이잖아!",
		BUSH_VINE =
		{
			BURNT = "음, 안 돌아오겠잖아.",
			CHOPPED = "나무만큼 재미있지는 않지만, 자르는 건 자르는 것이잖아.",
			GENERIC = "자르길 바라잖아.",
		},
		CAPTAINHAT = "배와 함께 익사하고 싶진 않잖아.",
		CARGOBOAT = "난 카고 쇼츠가 좋아.",
		CHIMINEA = "불의 갑옷이잖아.",
		CLOTHSAIL = "돌아가는 데 도움이 되겠잖아.",
		COCONADE =
		{
			BURNING = "피해야 되잖아!",
			GENERIC = "이것으로 상당한 타격을 줄 수 있잖아.",
		},
		COCONUT = 
		{
		    GENERIC = "그냥 코코넛이잖아.",
		    PLANTED = "아주 작은 야자 나무잖아.",
		},
		COCONUT_COOKED = "먹을 준비가 됐잖아.",
		COCONUT_HALVED = "나 하나, 루시 하나.",
		COFFEE = "커피잖아.",
		COFFEEBEANS = "이것을 요리해야겠잖아.",
		COFFEEBEANS_COOKED = "캐나다 사람은 커피를 좋아하잖아.",
		COFFEEBOT = "커피를 만들잖아.",
		COFFEEBUSH =
		{
			BARREN = "없어 보이네, 친구.",
			GENERIC = "커피콩!",
			PICKED = "콩이 더 많았으면.",
			WITHERED = "커피를 먹이면 좋을까.",
		},
		CORAL = "부숴서 새로운 걸 만들 수 있잖아.",
		CORALREEF = "따기 좋을 것 같잖아.",
		CORAL_BRAIN = "뇌잖아.",
		CORAL_BRAIN_ROCK = "뭐야, 너 똑똑한 거야?",
		CRAB =
		{
			GENERIC = "우리는 어쩌면 친구?",
			HIDDEN = "언제나 숨을 수는 없잖아, 친구.",
		},
		CRABHOLE = "내 게토끼 친구가 사는 곳이잖아.",
		CRATE = "상자잖아.",
		CUTLASS = "꽤 좋은 커터잖아, 엉?",
		DEAD_SWORDFISH = "미안하잖아.",
		DEPLETED_BAMBOOTREE = "다시 자르게 다시 자라라!",
		DEPLETED_BUSH_VINE = "다시 자라겠지.",
		DEPLETED_GRASS_WATER = "기다리는 것이 싫잖아.",
		DEVTOOL_NODEV = "이상한 물건이다.",
		DOUBLE_UMBRELLAHAT = "두 배로 보호하잖아!",
		DOYDOY = "이것이 어떻게 살아남을지 모르잖아.",
		DOYDOYBABY = "더러워.",
		DOYDOYEGG = "잘 먹을 수 있겠잖아.",
		DOYDOYEGG_COOKED = "캐나다 베이컨이 있으면 좋겠잖아.",
		DOYDOYEGG_CRACKED = "이제 어떻게 할 수 없잖아.",
		DOYDOYFEATHER = "긍지 높은 캐나다거위 깃털과는 전혀 다르잖아.",
		DOYDOYNEST = "더러운 새들이 여기서 번식하잖아.",
		DRAGOON = "좀 뜨겁잖아!",
		DRAGOONDEN = "비버 댐으로 보이지 않잖아.",
		DRAGOONEGG = "수상해 보이잖아.",
		DRAGOONHEART = "짐승의 심장이잖아.",
		DRAGOONSPIT = "무례하잖아.",
		DUBLOON = "노다지잖아!",
		DUG_BAMBOOTREE = "나와 함께 가는 거야!",
		DUG_BUSH_VINE = "여행을 떠날 수 있을까?",
		DUG_COFFEEBUSH = "어디든 휴대해야겠잖아.",
		DUG_ELEPHANTCACTUS = "내 쪽으로 오는 거냐?",
		EARRING = "둘이어야 하는 것 아닐까?",
		ELEPHANTCACTUS = "뾰족하잖아, 엉?",
		ELEPHANTCACTUS_ACTIVE = "조심해! 식물이 위험해!",
		ELEPHANTCACTUS_STUMP = "선인장이 지쳤잖아.",
		FABRIC = "어떻게 플래드로 염색할 수 있을까?",
		FEATHERSAIL = "이상한 깃털을 만져도 괜찮았잖아.",
		FISHINHOLE = "더 추웠다면, 얼음 낚시할 수 있었을 거잖아!",
		FISH_RAW = "연어가 낫잖아.",
		FISH_RAW_SMALL = "곰을 부르지 않기를.",
		FISH_RAW_SMALL_COOKED = "좋아 보이잖아.",
		FLAMEGEYSER = "식어라!",
		FLOTSAM = "쓰레기 뭉치잖아.",
		FLUP = "추하거든.",
		FRESHFRUITCREPES = "단풍당밀 시럽 뿌릴 수 있을까?",
		FROG_POISON = "독이 든 침은 혼자 가져라, 엉!",
		GASHAT = "이걸 쓰면 아무 것도 악취가 나지 않지.",
		GOLDENMACHETE = "자르고 빛이 나잖아!",
		GRASS_WATER = "좀 젖었잖아, 엉?",
		HAIL_ICE = "이것이 춥다고? 귀엽잖아.",
		HOUNDFIRE = "용감하게 타잖아!",
		ICEMAKER =
		{
			HIGH = "얼음 가득! 집 생각 나잖아.",
			LOW = "낮아지고 있잖아.",
			NORMAL = "잘 되고 있잖아.",
			OUT = "죽었잖아.",
			VERYLOW = "금방 꺼지겠다.",
		},
		INVENTORYGRAVE = "누가 여기 있었잖아. 더 이상은 아니지만.",
		INVENTORYMOUND = "누가 여기 있었잖아. 더 이상은 없지만.",
		IRONWIND = "재빠르잖아.",
		JELLYFISH = "해파리잖아.",
		JELLYFISH_COOKED = "그나마 먹을만해진 거잖아.",
		JELLYFISH_DEAD = "생기가 빠져나갔잖아, 엉?",
		JELLYFISH_PLANTED = "작은 해파리 친구.",
		JELLYJERKY = "육포! 나 같은 사람을 위한 음식이잖아.",
		JUNGLETREE =
		{
			BURNING = "좋은 패는 그루터기 낭비잖아.",
			BURNT = "낭비거든.",
			CHOPPED = "시간 잘 보냈어.",
			GENERIC = "나무의 부름이 내 귀를 채우잖아!",
		},
		JUNGLETREESEED =
        {
            GENERIC = "자를 수 있는 큰 나무가 되겠지.",
            PLANTED = "이제 기다려야잖아.",
        },
		KNIGHTBOAT = "성격 더럽잖아!",
		KRAKEN = "루시를 위하여!",
		KRAKENCHEST = "전리품을 내노라고 했잖아!",
		KRAKEN_TENTACLE = "달라붙잖아?",
		LAVAPOOL = "보는 것만으로도 땀이 나잖아.",
		LIMESTONE = "예쁜 산호를 분쇄하여 이것을 만들었잖아.",
		LIMPETROCK =
		{
			GENERIC = "이것으로 스낵을 만들 수 있겠어.",
			PICKED = "큰 돌이잖아, 엉?",
		},
		LIMPETS = "물에 사는 달팽이잖아.",
		LIMPETS_COOKED = "밥이잖아.",
		TREEGUARD = "숲을 화나게 만들었잖아!",
		LIVINGJUNGLETREE = "잘라달라고 애원하고 있잖아.",
		LOBSTER = "녹은 버터가 있으면 맛있을 텐데.",
		LOBSTERHOLE = "나와라, 작은 친구.",
		LOBSTER_DEAD = "아주 죽었잖아.",
		LOBSTER_DEAD_COOKED = "좋은 식사잖아!",
		LOGRAFT = "나의 특기잖아!",
		LUGGAGECHEST = "안에 좋은 게 있을까?",
		MACHETE = "하아, 자르는 용도잖아.",
		MAGIC_SEAL = "힘이 흐르잖아.",
		MAGMAROCK = "조금 재배열하면 좋은 이눅슈크가 되겠잖아.",
		MAGMAROCK_FULL = "조금 재배열하면 좋은 이눅슈크가 되겠잖아.",
		MAGMAROCK_GOLD = "팔 가치가 있어 보이잖아.",
		MAGMAROCK_GOLD_FULL = "팔 가치가 있어 보이잖아.",
		MANGROVETREE = "맛있어 보인다!",
		MANGROVETREE_BURNT = "보는 것만으로도 마음이 아프잖아.",
		MARSH_PLANT_TROPICAL = "작은 식물이잖아.",
		MERMFISHER = "잘 모르겠잖아.",
		MERMHOUSE_FISHER = "통나무집이 더 마음에 들잖아.",
		MESSAGEBOTTLE = "나에게 할 말이 있나?",
		MESSAGEBOTTLEEMPTY = "안에 무엇이 있었지?",
		MONKEYBALL = "뭘 보고 웃냐?",
		MONSTERTARTARE = "먹을 것, 다른 거 없나?",
		MOSQUITOSACK_YELLOW = "약간 신 냄새가 나잖아.",
		MOSQUITO_POISON = "질병이 가득 하잖아.",
		MUSSEL = "먹기 좋아 보이잖아.",
		MUSSELBOUILLABAISE = "최고의 식사잖아, 엉?",
		MUSSEL_COOKED = "맛있어 보이잖아.",
		MUSSEL_FARM =
		{
			GENERIC = "음식이 되고 싶어하잖아.",
			STICKPLANTED = "나의 미래에 홍합 식사가 보이잖아.",
		},
		MUSSEL_STICK = "홍합이 좋아하는 것이잖아.",
		MYSTERYMEAT = "그건 도대체 뭐야!",
		NEEDLESPEAR = "앗, 날카롭잖아.",
		OBSIDIAN = "약간 따뜻하거든.",
		OBSIDIANAXE = "조심해, 루시, 경쟁자가 나타났잖아! (농담이잖아!)",
		OBSIDIANCOCONADE = "강력한 위력을 가지고 있잖아.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "저걸 위해 나무를 베어야겠지, 엉?",
			GENERIC = "불 피우기 아주 좋은 곳이잖아.",
			HIGH = "나무를 너무 빨리 너무 많이 쓰고 있잖아!",
			LOW = "여기 어딘가에 나무가 있겠지.",
			NORMAL = "흠. 나무 냄새 나잖아.",
			OUT = "나무가 있으면 좋겠잖아.",
		},
		OBSIDIANMACHETE = "접촉하는 모든 것을 태우잖아.",
		OBSIDIANSPEARGUN = "불붙이는 용도잖아, 엉.",
		OBSIDIAN_WORKBENCH = "이것으로 불 도구를 만들 수 있잖아.",
		OCTOPUSCHEST = "고맙다, 친구!",
		OCTOPUSKING = "잘 지내고 있나, 친구?",
		OX = "농담의 대상이잖아.",
		OXHAT = "북부 사람에게 어울리는 모자잖아.",
		OX_FLUTE = "난 기타 연주를 선호해.",
		OX_HORN = "원래 소에 달려 있었잖아.",
		PACKIM = "참아줘야겠잖아.",
		PACKIM_FISHBONE = "털 달린 해로운 동물들을 끌어들이면 안 돼.",
		PALMLEAF = "부채질할 때 쓰잖아.",
		PALMLEAF_HUT = "나무꾼에게 가장 어울리는 집.",
		PALMTREE =
		{
			BURNING = "좋은 패는 그루터기 낭비잖아.",
			BURNT = "낭비거든.",
			CHOPPED = "시간 잘 보냈어.",
			GENERIC = "목재소로 가고 싶게 만들잖아.",
		},
		PARROT = "가라, 더러운 깃털생물!",
		PARROT_PIRATE = "멍청한 새하고 잡담할 시간은 없잖아.",
		PEACOCK = "이상한 것이잖아. 윽!",
		PEG_LEG = "잘라도 될까?",
		PIGTENT = "텐트 같잖아.",
		PIKE_SKULL = "구린 장식이잖아.",
		PIRATEGHOST = "우호적일까?",
		PIRATEHAT = "해적의 인생이잖아.",
		PIRATEPACK = "전리품을 위한 가방이잖아.",
		PIRATIHATITATOR =
		{
			BURNT = "더 이상 안 웃기잖아.",
			GENERIC = "웃겨 보이는 장치잖아.",
		},
		POISONHOLE = "피해 가야겠잖아.",
		PORTAL_SHIPWRECKED = "테를 두른 것으로 보이잖아.",
		PRIMEAPE = "웃기는 놈이잖아.",
		PRIMEAPEBARREL = "원숭이가 자는 곳이잖아.",
		RAFT = "불쌍한 작은 배잖아.",
		RAWLING = "미쳤잖아!",
		REDBARREL = "위험해 보인다.",
		RELIC =
		{
			BROKEN = "고칠 생각이 없잖아.",
			GENERIC = "이게 다 뭐냐?",
		},
		ROCK_CHARCOAL = "손을 거멓게 만들잖아.",
		ROCK_OBSIDIAN = "안에서 불이 타고 있잖아.",
		ROWBOAT = "수동의 힘이잖아.",
		SAIL = "돛에 바람이 달렸잖아.",
		SAIL_STICK = "북풍이 나를 도와줄 것이잖아.",
		SAND = "모래잖아.",
		SANDBAG = "댐 만들기가 내 특기잖아.",
		SANDBAGSMALL = "댐 만들기가 내 특기잖아.",
		SANDBAGSMALL_ITEM = "작은 휴대용 댐이잖아.",
		SANDBAG_ITEM = "휴대용 댐이잖아.",
		SANDHILL = "큰 모래 더미잖아.",
		SAND_CASTLE =
		{
			GENERIC = "모래가 이렇게 좋을 줄 누가 알았을까.",
			SAND = "보기 좋다.",
		},
		SEAGULL = "하늘의 해충이잖아.",
		SEAGULL_WATER = "바다의 해충이잖아.",
		SEASACK = "보물을 두는 곳이잖아.",
		SEASHELL = "다시 공예하고 싶게 만들잖아.",
		SEASHELL_BEACHED = "예쁜 조개잖아.",
		SEATRAP = "까재 만찬이 기대되잖아.",
		SEAWEED = "미끈덩하잖아.",
		SEAWEED_COOKED = "질감이 요상하잖아.",
		SEAWEED_DRIED = "혀에 달라붙잖아.",
		SEAWEED_PLANTED = "바닷말이잖아, 엉?",
		SHADOWSKITTISH_WATER = "저런!",
		SHARKITTEN = "큰 귀여운 고양이일 뿐이잖아.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "냐옹 소리가 나잖아...?",
			INACTIVE = "그냥 모래 같잖아, 엉?",
		},
		SHARK_FIN = "상어가 이걸 원하지 않겠지.",
		SHARK_GILLS = "물고기 폐잖아.",
		SHARK_TEETHHAT = "이빨로 만든 모자잖아.",
		SHARX = "이건 친구가 될 수 없잖아.",
		SHIPWRECKED_ENTRANCE = "모험 준비되었잖아, 엉!",
		SHIPWRECKED_EXIT = "나중에 보자, 친구.",
		SLOTMACHINE = "북의 정신이 나의 운명을 이끌잖아.",
		SLURPERPELT = "근처에 가죽 상인이 어디에 있지?",
		SNAKE = "보통 뱀이잖아.",
		SNAKEDEN =
		{
			BURNT = "음, 안 돌아오겠잖아.",
			CHOPPED = "나무만큼 재미있지는 않지만, 자르는 건 자르는 것이잖아.",
			GENERIC = "자르길 바라잖아.",
		},
		SNAKEOIL = "안 속잖아.",
		SNAKESKIN = "뱀한테 필요 없는 거잖아.",
		SNAKESKINHAT = "이것이 \"투쿠\"인가 \"투크\"인가?",
		SNAKESKINSAIL = "멋지게 항해할 수 있잖아.",
		SNAKE_FIRE = "약간 가열되었잖아.",
		SNAKE_POISON = "이것에 물리고 싶진 않잖아.",
		SOLOFISH = "착하지, 강아지.",
		SPEARGUN = "훌륭한 무기잖아!",
		SPEARGUN_POISON = "수크컴 무기가 적을 중독시키잖아!",
		SPEAR_LAUNCHER = "훌륭한 무기잖아!",
		SPEAR_OBSIDIAN = "불타는 창이잖아.",
		SPEAR_POISON = "이 창은 조금 더 아파.",
		SPOILED_FISH = "버릴 때가 된 것 같잖아.",
		STUNGRAY = "물에 빠진 말코손바닥사슴보다 악취가 심하잖아!",
		SUNKEN_BOAT =
		{
			ABANDONED = "좋은 나무가 아깝잖아.",
			GENERIC = "안녕, 친구.",
		},
		SUNKEN_BOAT_BURNT = "더 이상 뜨지 않잖아.",
		SUNKEN_BOAT_TRINKET_1 = "나한테는 너무 고급이잖아.",
		SUNKEN_BOAT_TRINKET_2 = "배가 작아 보이잖아.",
		SUNKEN_BOAT_TRINKET_3 = "용도를 상상하지 못 하겠잖아.",
		SUNKEN_BOAT_TRINKET_4 = "애들 장난감이잖아.",
		SUNKEN_BOAT_TRINKET_5 = "내 크기가 아니잖아.",
		SUPERTELESCOPE = "알버타의 평원을 보는 것처럼 쉽잖아.",
		SWEETPOTATOSOUFFLE = "아주 훌륭하잖아!",
		SWEET_POTATO = "요리 잘 해야겠잖아.",
		SWEET_POTATO_COOKED = "마시맬로 있으면 좋겠잖아.",
		SWEET_POTATO_PLANTED = "고급 감자잖아.",
		SWEET_POTATO_SEEDS = "심는 것이 더 소용이 있잖아.",
		SWIMMINGHORROR = "상종하기 싫잖아, 엉!",
		SWORDFISH = "아주 뾰족한 물고기잖아.",
		TELEPORTATO_SW_BASE = "청테이프로 못 고치는 것이 없잖아.",
		TELEPORTATO_SW_BOX = "쓸 데가 있겠지, 엉?",
		TELEPORTATO_SW_CRANK = "가지고 있어야겠잖아.",
		TELEPORTATO_SW_POTATO = "감자 같지 않잖아. 난 감자 전문가잖아.",
		TELEPORTATO_SW_RING = "반지잖아, 엉?",
		TELESCOPE = "내 시력을 보조하잖아, 엉?",
		THATCHPACK = "이제 나무를 더 들고 다닐 수 있잖아.",
		TIDALPOOL = "물고기한테 인기 있는 장소잖아.",
		TIDAL_PLANT = "이것으로 나무를 구할 수 없잖아.",
		TIGEREYE = "뚫어지게 쳐다보는 건 무례하잖아?",
		TIGERSHARK = "날 안 먹으려고 하면 귀엽겠잖아.",
		TOUCAN = "수상해 보이잖아.",
		TRAWLNET = "물고기가 안으로 수영해서 들어오겠지.",
		TRAWLNETDROPPED =
		{
			GENERIC = "나에게 와라, 물고기!",
			SOON = "거의 다 됐잖아!",
			SOONISH = "내려가고 있잖아.",
		},
		TREECLUMP = "자기를 잘라 달라는 것이지, 친구.",
		TRIDENT = "거대한 포크잖아, 엉?!",
		TRINKET_13 = "먹는 것이 안전한가?",
		TRINKET_14 = "얼굴인가?",
		TRINKET_15 = "기타가 작잖아!",
		TRINKET_16 = "작은 금속판이잖아, 엉?",
		TRINKET_17 = "제 사이즈가 아니군요.",
		TRINKET_18 = "부서졌잖아.",
		TRINKET_19 = "이것이 무엇일까?",
		TRINKET_20 = "나한테는 너무 고급이잖아.",
		TRINKET_21 = "배가 작아 보이잖아.",
		TRINKET_22 = "그리 유용해 보이지 않잖아.",
		TRINKET_23 = "저것이 뭔지 모르겠잖아.",
		TROPICAL_FISH = "피시 앤드 칩스가 되고 싶냐?",
		TUNACAN = "루시가 열어주겠지.",
		TURBINE_BLADES = "머리가 돌아가게 만들잖아.",
		TURF_SANDY = "지면이잖아, 엉?",
		TURF_ASH = "지면이잖아, 엉?",
		TURF_BEACH = "지면이잖아, 엉?",
		TURF_DESERTDIRT = "지면이잖아, 엉?",
		TURF_FUNGUS_GREEN = "지면이잖아, 엉?",
		TURF_FUNGUS_RED = "지면이잖아, 엉?",
		TURF_JUNGLE = "지면이잖아, 엉?",
		TURF_MAGMAFIELD = "지면이잖아, 엉?",
		TURF_MEADOW = "지면이잖아, 엉?",
		TURF_SNAKESKINFLOOR = "지면이잖아, 엉?",
		TURF_SWAMP = "지면이잖아, 엉?",
		TURF_TIDALMARSH = "지면이잖아, 엉?",
		TURF_VOLCANO = "지면이잖아, 엉?",
		TWISTER_SEAL = "귀여운 작은 것.",
		VENOMGLAND = "냄새가 좀 웃기잖아.",
		VINE = "한숨. 나무가 아니잖아.",
		VOLCANO = "근사하잖아!",
		VOLCANOSTAFF = "화산의 힘이 나의 손 안에 있잖아.",
		VOLCANO_ALTAR =
		{
			GENERIC = "내가 할 것이 없잖아.",
			OPEN = "뭘 원하는 것 같잖아.",
		},
		VOLCANO_ALTAR_BROKEN = "제대로 부서졌잖아.",
		VOLCANO_ALTAR_TOWER = "이상하게 생긴 돌이잖아, 엉.",
		VOLCANO_EXIT = "나갈 시간이잖아.",
		VOLCANO_SHRUB = "상록수가 아니잖아.",
		WALLYINTRO_DEBRIS = "여긴 어디지?",
		WALL_LIMESTONE = "벽이 잖아.",
		WALL_LIMESTONE_ITEM = "다리를 지을 수 있는데 왜 벽을 지어?",
		WATERMELON_SEEDS = "심을 수 있겠지?",
		WATERYGRAVE = "저렇게 죽지 않기를 바라잖아.",
		WHALE_BLUE = "크잖아!",
		WHALE_BUBBLES = "거기에 있는 것 알아, 친구.",
		WHALE_CARCASS_BLUE = "큰 놈이잖아, 엉.",
		WHALE_CARCASS_WHITE = "이제 죽었잖아.",
		WHALE_TRACK = "잘 추적하고 있잖아.",
		WHALE_WHITE = "강하고 자유롭잖아.",
		WILBUR_CROWN = "호화롭잖아.",
		WILBUR_UNLOCK = "새로운 친구잖아.",
		WILDBORE = "못된 짜식 같잖아.",
		WILDBOREHEAD = "운이 없잖아, 친구.",
		WILDBOREHOUSE = "짜식들이 많이 있는 집 같잖아.",
		WOODLEGSBOAT = "괜찮지만 약간 느리잖아.",
		WOODLEGSHAT = "털 달린 귀 플랩이 있으면 좋겠잖아.",
		WOODLEGSSAIL = "꽤 근사한 돛이잖아.",
		WOODLEGS_KEY1 = "무엇을 열까?",
		WOODLEGS_KEY2 = "무슨 열쇠?",
		WOODLEGS_KEY3 = "이걸 가지고 있어야 하는 거잖아, 엉?",
		WRECK = "좋은 나무의 낭비잖아.",
		CALIFORNIAROLL = "밴쿠버 도시인이 된 것 같잖아.",

	},
	DESCRIBE_GENERIC = "저게 뭐야, 엉?",
	DESCRIBE_TOODARK = "어둡잖아!",
	DESCRIBE_SMOLDERING = "곧 불탈 거잖아, 엉?",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "다 익었나. 아니면 안 익었나?",
	},
}
