return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "Äh, warum sollte ich das jetzt tun?",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "Vielleicht sollte ich warten, bis es abgelenkt ist.",
			GENERIC = "Naja.",
			NOBITS = "Das ist schon rasiert.",
		},
		WRITE =
        {
            GENERIC = "Ich kann nur ein X schreiben!",
        },
		RUMMAGE =
        {   
            GENERIC = "Ich sagte, es tut mir Leid!", 
        },
		COOK =
        {
            GENERIC = "Ich bin zu groß, um dort reinzufallen.",
            TOOFAR = "Überall Pelz.",
        },
		STORE =
		{
			GENERIC = "Ist schon voll.",
			NOTALLOWED = "Man wird mich nicht reinlassen.",
		},
		CHANGEIN =
        {
            GENERIC = "Wie schwierig wird es sein, da hinein zu kommen?",
            BURNING = "Viel besser als manches dämliche Kostüm!",
        },
        GIVE =
        {
            DEAD = "Die werden mein Geschenk nicht mehr zu schätzen wissen.",
            SLEEPING = "Nicht jetzt. Es schläft.",
            BUSY = "Beschäftigt.",
        },
        TEACH =
        {
            KNOWN = "Ich habe den Pilz mitgenommen.",
            CANTLEARN = "Bäh. Ich wollte das sowieso nicht wissen.",
        },
	},
	ACTIONFAIL_GENERIC = "Ich kann nicht!",
	ANNOUNCE_MAGIC_FAIL = "Warum funktioniert das nicht?",
	ANNOUNCE_ADVENTUREFAIL = "Diesmal hast du gewonnen, Maxwell.",
	ANNOUNCE_BOOMERANG = "Dummer Bumerang.",
	ANNOUNCE_CHARLIE = "Ich habe keine Angst vor dir!",
	ANNOUNCE_CHARLIE_ATTACK = "AUTSCH! Du Idiot!",
	ANNOUNCE_COLD = "Diese Kälte! Es brennt!",
	ANNOUNCE_HOT = "Die Hitze ist zu intensiv!",
	ANNOUNCE_DUSK = "Die Nacht kommt. Ich brauche Feuer!",
	ANNOUNCE_WORMS = "Ich möchte NICHT sehen, woher dieses Geräusch kam.",
	ANNOUNCE_EAT =
	{
		GENERIC = "MJAM!",
		PAINFUL = "Pfui! Ekelhaft!",
		SPOILED = "Das schmeckt schrecklich.",
		STALE = "Das war irgendwie widerlich.",
		INVALID = "Wie soll man das denn essen?",
		YUCKY = "Bäh, das gibt's doch nicht.",
	},
	ANNOUNCE_NOSLEEPONFIRE = "Es ist nur die Einsturzgefahr, die mir Sorgen bereitet.",
	ANNOUNCE_NODANGERSIESTA = "Keine Zeit für eine Siesta. Es ist Zeit zum Kämpfen!",
	ANNOUNCE_NONIGHTSIESTA = "Ich könnte mich so nicht entspannen.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Ich möchte wirklich lieber drin sein.",
	ANNOUNCE_NOHUNGERSIESTA = "Ich kann keine Siesta machen, während mein Bauch grummelt!",
	ANNOUNCE_SHELTER = "Abgesehen vom Brennen, bist du bestimmt für irgendetwas gut.",
	ANNOUNCE_BURNT = "Ich wünschte, ich hatte es nicht in Flammen aufgehen lassen...",
	ANNOUNCE_TOOL_SLIP = "Ich habe immer noch mein Feuerzeug.",
	ANNOUNCE_DAMP = "Uh oh!",
	ANNOUNCE_WET = "Dies könnte schlecht sein!",
	ANNOUNCE_WETTER = "Ich hasse es!",
	ANNOUNCE_SOAKED = "Ihh, das ist am SCHLECHTESTEN!",
	ANNOUNCE_HOUNDS = "Zeig dich!",
	ANNOUNCE_HUNGRY = "Ich brauche etwas zu Essen!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Ich werde dich finden!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Ohh... er ist davongekommen.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Argh! Ich habe seine Spur im Schlamm verloren.",
	ANNOUNCE_ACCOMPLISHMENT= "Beweg dich, Pfeil! BEWEG DICH!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Ich hab's geschafft!",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "Tadaa!",
		[2] = "Hübsch!",
		[3] = "Ups!",
		[4] = "Ich habe ein Feuer gemacht!",
		[5] = "Brenne!",
		[6] = "Ich kann einfach nicht anders!",
	},
	ANNOUNCE_PECKED = "Nein! Böses Vögelchen!",
	ANNOUNCE_TORCH_OUT = "Mein wertvolles Licht ist aus!",
	ANNOUNCE_FAN_OUT = "Das dumme Ding braucht Kacke.",
    ANNOUNCE_COMPASS_OUT = "Kleine Nadel abgebrochen!",
	ANNOUNCE_WORMHOLE = "Ich werde diese Kleidung verbrennen müssen!",
	ANNOUNCE_TRAP_WENT_OFF = "Aah!",
    ANNOUNCE_CRAFTING_FAIL = "Ich habe irgendwas vergessen.",
    ANNOUNCE_QUAKE = "Dieses Geräusch bedeutet vermutlich nichts Gutes.",
    ANNOUNCE_NODANGERSLEEP = "Keine Zeit zum Schlafen. Ich muss kämpfen!",
    ANNOUNCE_NOHUNGERSLEEP = "Mein Bäuchlein grummelt. Ich kann nicht schlafen!",
    ANNOUNCE_FREEDOM = "Ich bin frei! Zeit für Feuer!",
    ANNOUNCE_RESEARCH = "Das war hilfreich, auch wenn es nichts mit Feuer zutun hat.",
    ANNOUNCE_NO_TRAP = "Als würde man ein Fass voll Fisch in Brand setzen.",
    ANNOUNCE_HIGHRESEARCH = "So viel Informationen!",
    ANNOUNCE_THORNS = "Autsch!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Es ist hier unten zu gruselig, um zu schlafen.",
    ANNOUNCE_BEES = "Aaaah! Stechende Käfer!",
    ANNOUNCE_KNOCKEDOUT = "Argh, mein kleiner Kopf!",
    ANNOUNCE_LOWRESEARCH = "Buh, das war langweilig.",
    ANNOUNCE_DEERCLOPS = "Das hörte sich nach einem riesigen Monster an!",
    ANNOUNCE_MOSQUITOS = "Verschwindet, ihr blutsaugenden Idioten!",
    ANNOUNCE_NODAYSLEEP = "Ich werde da nicht reingehen, solang ich hier einen großen Feuerball am Himmel haben kann.",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "Es sieht etwas glücklicher aus.",
	ANNOUNCE_CANFIX = "\nIch glaub, ich kann das reparieren!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Ich bin vor dem Himmelfeuer sicher.",
	ANNOUNCE_VOLCANO_ERUPT = "Der Feuerberg spricht.",
	ANNOUNCE_TREASURE = "'X markiert die Stelle!",
	ANNOUNCE_CRAB_ESCAPE = "Schießen! Er ist davongekommen.",
	ANNOUNCE_SHARX = "Hey! Hör' auf herumzuspritzen!",
	ANNOUNCE_MORETREASURE = "Dieser Tag wird immer besser.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Das sieht nicht wie eine Karte dieses Ortes aus.",
	ANNOUNCE_OTHER_WORLD_PLANT = "Es wird nicht wachsen. Vielleicht sollte ich es lieber verbrennen.",
	ANNOUNCE_MAPWRAP_WARN = "Der Nebel sieht ziemlich dicht aus.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Ähm, wohin wollte ich noch gleich?",
	ANNOUNCE_MAPWRAP_RETURN = "Ich konnte dort nichts sehen!",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Die Nachricht ist verblasst. Ich kann sie nicht lesen.",
	},
	ANNOUNCE_BOAT_DAMAGED = "Mein Schiff ist angeschlagen!",
	ANNOUNCE_BOAT_SINKING = "Ich geh unter!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Lebewohl, du schlimme Welt!",
	ANNOUNCE_ENTER_DARK = "Wo hab ich nur mein Feuerzeug?",
	ANNOUNCE_ENTER_LIGHT = "Achso. Ich dachte schon, ich wäre blind geworden.",
	ANNOUNCE_INV_FULL = "Ich kann nichts mehr tragen.",
	ANNOUNCE_TRAWL_FULL = "Mein Netz kann jetzt eingefahren werden.",
	ANNOUNCE_UNIMPLEMENTED = "Das sieht gefährlich aus. Verbrenn es!",
	ANNOUNCE_WAVE_BOOST = "Huiiiii!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Oho, da ist ein großer Fisch in der Nähe.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Mist, verloren!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Das Wasser ist zu unruhig!",

	BATTLECRY =
	{
		GENERIC = "Jetzt heißt es 'Du oder ich'!",
		PIG = "Dummes Schwein!",
		PREY = "Komm hierher!",
		SPIDER = "Grrrrar!",
		SPIDER_WARRIOR = "Ihhhh, töte sie!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Das habe ich mir gedacht!",
		PIG = "Komm zurück, Schweinefleisch!",
		PREY = "Nächstes Mal kriege ich dich!",
		SPIDER = "Mäh. Ich werde ihn später töten.",
		SPIDER_WARRIOR = "Jetzt ist sie nicht mehr so hart!",
	},
	
	DESCRIBE =
	{
		BIGFISHINGROD = "Wie groß!",
		DEVTOOL = "Das will doch verbrannt werden.",
		DEVTOOL_NODEV = "Das will doch verbrannt werden.",
		HOUNDFIRE = "Ich brauche etwas zu Essen!",
		INVENTORYGRAVE = "Nicht jeder ist für das Leben hier draußen geeignet.",
		INVENTORYMOUND = "Nicht jeder ist für das Leben hier draußen geeignet.",
		MANDRAKE_COOKED = "Nach dem Feuer sieht der Pflanzenmann sehr viel ruhiger aus.",
		ROCK = "Sieht aus wie ein Stein.",
		SLURPERPELT = "Wenn man das verbrennt, stinkt es noch schlimmer.",
		TREECLUMP = "Weg daaaaaaaa!",
		TURF_DESERTDIRT = "Der Boden ist langweilig.",
		TURF_FUNGUS_GREEN = "Der Boden ist langweilig.",
		TURF_FUNGUS_RED = "Der Boden ist langweilig.",
		TURF_SWAMP = "Sumpfig.",
		WATERMELON_SEEDS = "Die könnte ich säen, aber das ist bestimmt langweilig.",
		WORMHOLE_LIMITED = "ER HAT FAST KEINEN TREIBSTOFF MEHR.",
		GLOMMER = "Er ist flauschig! Und schleimig...",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Warum muss immer alles eine Blume sein?!",
        	DEAD = "Ich frage mich, ob es brennt...",
        },
        GLOMMERWINGS = "Sie sind so klein!",
        GLOMMERFUEL = "Klebrig und unheimlich.",
        BELL = "Ist denn schon Silvester? Ist das FEUERWERK?",
        MOOSE_NESTING_GROUND = "Es riecht wie das Ende eines Vogels.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Soll das irgendwas sein?",
        	EMPTY = "Sieht irgendwie gleich aus.",
    	},
		WEBBERSKULL = "Das ist zwar nicht meine Sache, aber ein Begräbnis sollte es geben.",
		MOLE =
		{
			HELD = "Aus dem Boden, in das Feuer.",
			UNDERGROUND = "Versteckt sich vor dem Licht, was?",
			ABOVEGROUND = "Komm doch für einen kurzen Blick nach oben!",
		},
		MOLEHILL = "Weit unten, weg von der Sonne. Das ist unnatürlich.",
		MOLEHAT = "Ich bin mir dabei nicht sicher...",
		NIGHTSTICK = "Es wäre selbst dann kühler, wenn es in Flammen stehen würde...",
		RABBITHOUSE=
		{
			GENERIC = "Igitt! Blöde Karnickel.",
			BURNT = "Ha! Gutes Ergebnis.",
		},
		TURF_DECIDUOUS = "Der Boden ist langweilig.",
		TURF_SANDY = "Der Boden ist langweilig.",
		TURF_BADLANDS = "Der Boden ist langweilig.",
		BEARGER = "Whoa! Coooooler Bär...",
		BEARGERVEST = "Als würde man in Pelz schwimmen.",
		ICEPACK = "Flauschiger Rucksack!",
		MOONROCKNUGGET = "Nur eine weitere langweilige Pflanze.",
		ROCK_MOON = "Nur eine weitere langweilige Pflanze.",
		BEARGER_FUR = "Überall Pelz.",
		FURTUFT = "Schwarz, weiß und fusselig!",
		BIGFOOT = "Was zur Hölle?!",
		BONESHARD = "Ich glaube nicht, dass sie gut brennbar sind.",
		BUZZARD = "Dein Hals ist widerlich.",
		CACTUS = 
		{
			GENERIC = "Stacheln! Meine Schwäche! Wie können die das wissen?",
			PICKED = "Einigen wir uns auf unentschieden.",
		},
		CACTUS_MEAT_COOKED = "Jetzt sieht es gut aus.",
		CACTUS_MEAT = "Er sieht immer noch gefährlich aus.",
		CACTUS_FLOWER = "Und noch eine weitere Blume.",
		COLDFIRE =
		{
			EMBERS = "Oh. Es ist schon fast aus!",
			GENERIC = "Ich mag alle Arten von Feuer.",
			HIGH = "BRENNE! BRENNE SCHNELLER! AND BLAUER!",
			LOW = "Dieses Feuer ist klein und langweilig.",
			NORMAL = "Brenne!",
			OUT = "Ohhh. Es ist vorbei.",
		},
		CATCOON = "Hier, Kätzchen!",
		CATCOONDEN = 
		{
			GENERIC = "Ich würde es nicht verbrennen, während jemand hier lebt.",
			EMPTY = "Komplett ausgetrocknet und bereit zum Verbrennen.",
		},
		CATCOONHAT = "Knuddeliger Hut.",
		COONTAIL = "Ich habe schon seltsamere Dinge als das aufgehoben.",
		COOKPOT =
		{
			COOKING_LONG = "Das Feuer hat noch einiges Arbeit vor sich.",
			COOKING_SHORT = "Das Feuer tut, was es soll!",
			DONE = "Ich bin stolz, dass ich mit Feuer gekocht habe.",
			EMPTY = "Ich könnte Nahrung in ihn und Feuer unter ihm machen.",
			BURNT = "Wenigstens ging er in der Herrlichkeit der Flamme unter.",
		},
		EYEBRELLAHAT =	"Wenn ich ihn trage, dann muss ich es nicht mehr angucken...",
		ARMORDRAGONFLY = "Juhu! Mehr FEUER!!!",
		DRAGON_SCALES = "Oooooooh! ICH MAG das.",
		DRAGONFLYCHEST = "Ich bin mir nicht sicher, warum man etwas haben wollen würde, das NICHT brennt...",
		DECIDUOUSTREE = 
		{
			BURNING = "JA! BRENNE!",
			BURNT = "Ich wünschte, er würde immer noch brennen.",
			CHOPPED = "Nun, die wären früher schon nützlich gewesen.",
			GENERIC = "Sieht aus, als würde er gut brennen.",
			POISON = "Ein Feuer würde es ihnen zeigen.",
		},
		ACORN_COOKED = "Sieht nicht so aus, als würdest du ein Baum werden.",
		BIRCHNUTDRAKE = "Aaah! Setz es in Brand!",
		FARMPLOT =
		{
			GENERIC = "Seufz. Das ist ein Haufen Dreck.",
			GROWING = "Beeil dich, Dreckhaufen. Füttere mich!",
			NEEDSFERTILIZER = "Das dumme Ding braucht Kacke.",
			BURNT = "Das war ein nettes Finale.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Oh. Es ist schon fast aus!",
			GENERIC = "Ich konnte es mir Stunden anschauen. Selbst wenn es kalt ist.",
			HIGH = "BRENNE! BRENNE SCHNELLER! AND BLAUER!",
			LOW = "Dieses Feuer ist klein und langweilig. Und blau.",
			NORMAL = "Brenne!",
			OUT = "Ich sollte das Feuer wieder zurückholen.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Ich wünschte, du würdest deinen Deckel schließen und damit aufhören, die Feuer auszumachen.",
			OFF = "Und bleib aus!",
			LOWFUEL = "Fast aus.",
		},
		ICEHAT = "Das ist ein echter Dämpfer für meine Stimmung.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Hüpfende Ziege.",
			CHARGED = "Du bist verrückt!",
		},
		LIGHTNINGGOATHORN = "Ich kann den Blitz hören, wenn ich es an mein Ohr halte.",
		GOATMILK = "Versetzt mit Elektrizität. Pfui.",
		MEATRACK =
		{
			DONE = "Es ist fertig!",
			DRYING = "Los, Fleisch, trockne endlich.",
			DRYINGINRAIN = "Vergiss den Regen! Trockne!",
			GENERIC = "Ich will etwas Fleisch aufhängen!",
			BURNT = "Vielleicht war das Feuer nicht die beste Trocknungsmethode...",
		},
		MERMHEAD = 
		{
			GENERIC = "Das ist dafür, weil du so stinkst!",
			BURNT = "Doppelt gut!",
		},
		MERMHOUSE = 
		{
			GENERIC = "Es würde niemanden interessieren, wenn es abbrennen würde.",
			BURNT = "Es ist wahr, es interessiert niemanden.",
		},
		FLOWERSALAD = "Mir wäre eine Schüssel voll Flammen lieber.",
        ICECREAM = "Mache kalte Dinge sind gar nicht so schlecht.",
        WATERMELONICLE = "Wieso sollte man eine Frucht einfrieren, wenn man sie auch kochen kann?",
        TRAILMIX = "Knusper, knusper, knusper.",
        HOTCHILI = "Das ist genau meine Art von Schärfe!",
        GUACAMOLE = "Heiliger Strohsack, das ist lecker.",
		MOOSE = "Was zur...",
		MOOSEEGG = "Es ist riiiiiiiesig!",
		MOSSLING = "Seine Federn sind zerfetzt.",
		FEATHERFAN = "Hmm... Ich könnte ein paar Feuer löschen...",
		TROPICALFAN = "Hmm... Ich könnte ein paar Feuer löschen...",
		GOOSE_FEATHER = "Weich und mollig!",
		STAFF_TORNADO = "Dreht sich ständig und zerstört dabei alles!",
		PIGHEAD = 
		{	
			GENERIC = "Ich schätze, ich habe alles richtig gemacht.",
			BURNT = "Ich schätze, es kann immer schlechter werden.",
		},
		PIGHOUSE =
		{
			FULL = "Er macht da drin Schweinereien.",
			GENERIC = "Diese Schweine haben einen zweifelhaften Architekturgeschmack.",
			LIGHTSOUT = "Du Idiot! Lass mich rein!",
			BURNT = "Nette Renovierungsaufgabe.",
		},
		FERTILIZER = "Ein Eimer voll Ekelzeugs.",
		RAINOMETER = 
		{	
			GENERIC = "Regen ist das Anti-Feuer. Buh!",
			BURNT = "Nimm das, Regen!",
		},
		RAINCOAT = "Das wird den Unterschied ausmachen.",
		RAINHAT = "Alles, um Wasser abzuhalten.",
		RESEARCHLAB = 
		{	
			GENERIC = "Selbst ich weiß nicht alles... noch nicht.",
			BURNT = "Davon kann man nun nichts mehr lernen.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Selbst ich weiß nicht alles... noch nicht.",
			BURNT = "Davon kann man nun nichts mehr lernen.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Eine dunkle und mächtige Energie geht davon aus.",
			BURNT = "Jetzt ist sie zwar dunkel aber nicht mehr sehr mächtig.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Ich kann den Hut wie einen Kochkessel verwenden!",
			BURNT = "Doppelte, doppelte Arbeit und... oh. Es ist abgebrannt.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Das ist meine Versicherungspolice.",
			BURNT = "Meine Versicherung wurde hiermit gekündigt.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Ich denke nicht, dass es einen Weg gibt, es zum brennen zu bringen.",
			MELTED = "So nutzlos wie Wasser schon immer war.",
		},
		ROCK_ICE_MELTED = "So nutzlos wie Wasser schon immer war.",
		ICE = "Kalt.",
        REFLECTIVEVEST = "Westen sind wirklich in.",
		HAWAIIANSHIRT = "Ich frage mich, ob es genauso schön brennt wie normale Blumen.",
		TENT = 
		{
			GENERIC = "Ich habe alle Abzeichen bei den Pfadfinderinnen bekommen.",
			BURNT = "Nun, ich habe meine Abzeichen trotzdem noch.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Sie haben uns bei den Pfadfinderinnen beigebracht, wie man das macht.",
			BURNT = "Ich habe sie schon immer in Brand gesteckt.",
		},
		TRANSISTOR = "Ein elektrisches Dingsbums.",
		TREASURECHEST = 
		{
			GENERIC = "Ein Truhe für meinen Müll.",
			BURNT = "Die Truhe hat schön gebrannt.",
		},
		TUMBLEWEED = "Das sieht hochentzündlich aus.",
		GRASS_UMBRELLA = "So hübsch wie er nur sein kann.",
		PALMLEAF_UMBRELLA = "Das ist so schön.",
		UNIMPLEMENTED = "Es ist noch nicht fertig. Aber ich wette, dass es trotzdem brennt.",
		WALL_HAY = 
		{	
			GENERIC = "Das sieht wirklich brennbar aus!",
			BURNT = "Es ist brennbar!",
		},
		WALL_WOOD = 
		{
			GENERIC = "Das könnte Feuer fangen.",
			BURNT = "Sie hat Feuer gefangen!",
		},
		WARG = "You're a big mean jerk!",
		WATERMELON = "Ich kannte mal eine Melone mit dem Namen Walter.",
		WATERMELON_COOKED = "Warm, saftig und süß.",
		WATERMELONHAT = "Ah, das ist also ein Verwendungszweck dieser Frucht.",
		WINTEROMETER = 
		{
			GENERIC = "Es wäre besser, wenn es Feuer messen würde.",
			BURNT = "Hätte es Feuer gemessen, wäre es vielleicht vorbereitet gewesen!",
		},
		HOME = "I'm gonna burn it.",
		HOMESIGN = 
		{
			GENERIC = "Weniger Lesen! Mehr Brennen!",
			UNWRITTEN = "Ich könnte sie zu was gebrauchen. Oder einfach verbrennen.",
			BURNT = "Hahaha, jaaaa!",
		},
		BEEBOX =
		{
			READY = "Hurra, ich kann Honig stehlen!",
			FULLHONEY = "Hurra, ich kann Honig stehlen!",
			GENERIC = "Los, ihr fetten Bienen. Macht mir Honig!",
			NOHONEY = "Hier gibts nichts zu sehen.",
			SOMEHONEY = "Geduld.",
			BURNT = "Habe sie ausgeräuchert!",
		},
		LIVINGTREE = "Es könnte leben, aber es wird trotzen brennen.",
		ICESTAFF = "Laaaaaangweilig.",
		WORMLIGHT = "Licht ohne Feuer. Wie unnatürlich!",
		WORMLIGHT_LESSER = "Wie für meine Hand gemacht.",
		WORM =
		{
		    PLANT = "Licht ohne Feuer. Wie unnatürlich!",
		    DIRT = "Ist das normal, dass sich der Dreck bewegt?",
		    WORM = "Es ist wirklich pelzig!",
		},
		WORMLIGHT_PLANT = "Licht ohne Feuer. Wie unnatürlich!",
		EEL = "Ich mag nicht, wie er mich anschaut!",
		EEL_COOKED = "Feuer macht alles besser.",
		UNAGI = "Wie man es dreht und wendet. Ein Aal bleibt ein Aal.",
		EYETURRET = "Ich wünschte, es könnte Dinge in Brand setzen.",
		EYETURRET_ITEM = "Nutzlos, solange ich ihn nicht irgendwo platziert habe.",
		MINOTAURHORN = "Ich frage mich, ob die Ringe ein Anzeichen des Alters darstellen.",
		MINOTAURCHEST = "Ich will auch so große Hörner haben!",
		THULECITE_PIECES = "Dieses Thulecite ist zerbröckelt.",
		POND = "Dieser Teich lässt sich sicher nicht entzünden. Wie dumm.",
		POND_ALGAE = "Es braucht viel Wasser.",
		GREENSTAFF = "Er kann kein Feuer erschaffen, aber scheint dennoch hilfreich zu sein.",
		POTTEDFERN = "Ich würde sie lieber verbrennen.",

		THULECITE = "Ich glaube nicht, dass es brennen würde.",
		ARMORRUINS = "Ich bin mir nicht sicher, ob ich das tragen möchte.",
		RUINS_BAT = "Die wird die Fieslinge fernhalten.",
		RUINSHAT = "Sieht aus, als wäre dort etwas durchgeflogen.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Wirkt auf mich ganz normal.",	--Calm phase
			WARN = "Es warnt mich.",	--Before nightmare
			WAXING = "Der Treibstoff erwacht zum Leben!", --Nightmare Phase first 33%
			STEADY = "Sie summt fast schon.", --Nightmare 33% - 66%
			WANING = "Ich glaube, es ist ausgeschaltet.", --Nightmare 66% +
			DAWN = "Ich schätze, dass es fast vorbei ist.", --After nightmare
			NOMAGIC = "Ich glaube nicht, dass das funktioniert.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "Ahhh!",
		ROOK_NIGHTMARE = "Das hat ein ekelhaftes Lachen.",
		KNIGHT_NIGHTMARE = "Sieht ziemlich abgenutzt aus.",
		MINOTAUR = "Armes Ding. Gefangen in diesem Irrgarten.",	--Monster in labyrinth
		SPIDER_DROPPER = "Die kommen von oben.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Licht ohne Feuer. Wie unnatürlich!",	--Lights that activate during nightmare.
		GREENGEM = "Der fühlt sich wirklich leicht an.",
		RELIC = "I guess someone lived here before.",	--Fixed relic
		RUINS_RUBBLE = "Ich könnte das wahrscheinlich in Ordnung bringen.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "Die ist echt hilfreich!",	--Works as axe and pickaxe
		ORANGESTAFF = "Das macht mir Kopfschmerzen.",	--Teleports player.
		YELLOWAMULET = "Er scheint die Dunkelheit um ihn herum zu absorbieren.",	--Emits light, player walks faster.
		GREENAMULET = "Ich fühle, wie sich mein Geist öffnet, wenn ich es trage.",	--Reduce cost of crafting

		SLURPER = "Haben die kleine Feuerchen in ihren Bäuchen?",
		SLURPER_PELT = "Iiiiiihhhh, der ist ja immer noch am Leben!",
		ARMORSLURPER = "Iih! Iih! Iih! Iih! Igitt!",
		ORANGEAMULET = "Es hebt die brennenden Materialien für mich auf.",
		YELLOWSTAFF = "Magisch.",
		YELLOWGEM = "Er funkelt.",
		ORANGEGEM = "Der lässt meine Finger kribbeln.",
		PALMTREE =
        {
			BURNING = "Wow! So viel Feuer.",
			BURNT = "Eine echte Verbesserung.",
			CHOPPED = "Loki hat ihn zu sich geholt.",
			GENERIC = "Du hast einen merkwürdigen Mangel an Zweigen.",
		},
		TELEBASE = 
		{
			VALID = "Ich spüre den Zauber!",
			GEMS = "Da fehlt noch was.",
		},
		GEMSOCKET = 
		{
			VALID = "Ich frage mich, wie sie schweben.",
			GEMS = "Er ist leer!",
		},
		STAFFLIGHT = "Es ist so schön!",

        LIGHTER = "Das ist mein glückbringendes Feuerzeug.",


        ANCIENT_ALTAR =
        {
        	WORKING = "Oooo! Eine Wechselsprechanlage zum Jenseits.",
        	BROKEN = "Die Toten kommen hier nicht durch.",
        },  
        ANCIENT_ALTAR_BROKEN = "Die Toten kommen hier nicht durch.",

        ANCIENT_STATUE = "Zum Teufel! Das wird nicht brennen.",

        LICHEN = "Eine eklige, krustige Pflanze.",
		CUTLICHEN = "Bäh, schmeckt wie Sägemehl.",

        CAVE_BANANA = "Bananen!",
        CAVE_BANANA_COOKED = "MJAM!",
        CAVE_BANANA_BURNT = "Mehr wollt ich gar nicht!",
        CAVE_BANANA_TREE = "Sieht brennbar aus!",
        ROCKY = "Wir haben nicht viel gemeinsam.",

        BLUEAMULET = "'Buh' dazu.",
		PURPLEAMULET = "Ist die Wissenschaft zu weit gegangen?",
		TELESTAFF = "Es ist wirklich stürmisch ihn zu benutzen.",
		MINERHAT = "Das ist zwar kein echtes Feuer, aber es ist trotzdem ganz witzig.",
		MONKEY = "Der Witz ist auf deiner Seite! Ich kann deine Kacke verbrennen.",
		MONKEYBARREL = "Was für ein wunderbar entflammbares Haus.",

		HOUNDSTOOTH="Der ist scharf. Das mag ich!",
		ARMORSNURTLESHELL="Weniger Verteidigung! Mehr Angriff!",
		BAT="Niedlicher kleiner Kerl!",
		BATBAT = "Damit kann ich meine Gegner schlagen.",
		BATWING="Igitt!",
		BATWING_COOKED="Igitt!",
		BEDROLL_FURRY="Das ist mir zu aufgeputzt.",
		BUNNYMAN="Bäh! Die sehen so dumm aus.",
		FLOWER_CAVE="Es brennt im Inneren.",
		FLOWER_CAVE_DOUBLE="Es brennt im Inneren.",
		FLOWER_CAVE_TRIPLE="Es brennt im Inneren.",
		GUANO="Es brennt wie normale Kacke.",
		LANTERN="Feuer sollte nicht so eingesperrt werden!",
		LIGHTBULB="Es ist eine Glühbirne, aber eine schwere.",
		MANRABBIT_TAIL="Ich hab den Streit gewonnen.",
		MUSHTREE_TALL=
		{
            GENERIC = "Gross. This tree is sick all over.",
            BLOOM = "Ack! It stinks!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Gross. It smells like leprechaun butt.",
            BLOOM = "It's spreading junk everywhere.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Gross. It's all mushroomy.",
            BLOOM = "Ew, I don't want to get too close.",
        },
        MUSHTREE_TALL_WEBBED = "Was ist los? Fehlt Erde?",
        SPORE_TALL = "Wie farbige Funken!",
        SPORE_MEDIUM = "Wie farbige Funken!",
        SPORE_SMALL = "Wie farbige Funken!",
        SPORE_TALL_INV = "Es ist brennbar!",
        SPORE_MEDIUM_INV = "Es ist brennbar!",
        SPORE_SMALL_INV = "Es ist brennbar!",
		MUSHTREE_TALL="Widerlich! Dieser Baum ist vollkommen krank.",
		MUSHTREE_MEDIUM="Widerlich! Das riecht wie das Hinterteil eines Kobolds.",
		MUSHTREE_SMALL="Widerlich! Das ist vollkommen pilzig.",

		SLURTLE="Ich will's in die Luft jagen.",
		SLURTLE_SHELLPIECES="Hey! Das ist kaputt.",
		SLURTLEHAT="Er passt auf meinen Kopf.",
		SLURTLEHOLE="Ich sollte sie ausräuchern.",
		SLURTLESLIME="Ich liebe dieses Zeug!",
		SNURTLE="Kawumm!",
		SPIDER_HIDER="Was für ein frustrierender Idiot.",
		SPIDER_SPITTER="Komm hierher!",
		SPIDERHOLE="Es ist voll mit Spinnen.",
		STALAGMITE="Felsen sind langweilig.",
		STALAGMITE_FULL="Felsen sind langweilig.",
		STALAGMITE_LOW="Felsen sind langweilig.",
		STALAGMITE_MED="Felsen sind langweilig.",
		STALAGMITE_TALL="Noch mehr langweilige Steine.",
		STALAGMITE_TALL_FULL="Noch mehr langweilige Steine.",
		STALAGMITE_TALL_LOW="Noch mehr langweilige Steine.",
		STALAGMITE_TALL_MED="Noch mehr langweilige Steine.",

		TURF_CARPETFLOOR = "Der Boden ist langweilig.",
		TURF_CHECKERFLOOR = "Der Boden ist langweilig.",
		TURF_DIRT = "Der Boden ist langweilig.",
		TURF_FOREST = "Der Boden ist langweilig.",
		TURF_GRASS = "Der Boden ist langweilig.",
		TURF_MARSH = "Der Boden ist langweilig.",
		TURF_ROAD = "Der Boden ist langweilig.",
		TURF_ROCKY = "Der Boden ist langweilig.",
		TURF_SAVANNA = "Der Boden ist langweilig.",
		TURF_WOODFLOOR = "Der Boden ist langweilig.",
		TURF_DRAGONFLY = "Mein Feuerzeug funktioniert damit nicht.",

		TURF_CAVE="Der Boden ist langweilig.",
		TURF_FUNGUS="Der Boden ist langweilig.",
		TURF_SINKHOLE="Der Boden ist langweilig.",
		TURF_UNDERROCK="Der Boden ist langweilig.",
		TURF_MUD="Der Boden ist langweilig.",
		
		TURKEYDINNER = "Ein Festmahl. Verbrannter Vogel.",
		TWIGS = "Ein Bündel kleiner Zweige. Zum Beispiel zum Feuermachen.",
		POWCAKE = "Ich frage mich, ob das brennbar ist.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Who plugged that hole?",
            OPEN = "I hope there's lava down there somewhere.",
        },
        CAVE_EXIT = "It's too dark and stuffy down here.",
        CAVE_ENTRANCE = "Wer hat das Loch zugestopft?",
        CAVE_ENTRANCE_RUINS = "Wer hat das Loch zugestopft?",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "Ich möchte nicht in dieses eklige Loch.",
            OPEN = "Ich hoffe, dort unten gibt es irgendwo Lava.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Jedenfalls ist es hier unten kälter.",
            OPEN = "Es ist dunkel und stickig hier unten.",
        },

		MAXWELLPHONOGRAPH = "Ich mag nur spannendere Musik.",
		PIGGUARD = "Ich mag seine Einstellung.",
		BOOMERANG = "Das ist nicht die aufregendste Waffe.",
		ADVENTURE_PORTAL = "Das führt mich vielleicht nach Hause.",
		AMULET = "Ich bin unbesiegbar! Nun ja, das vielleicht nicht. Aber es fühlt sich gut an.",
		ANIMAL_TRACK = "Sie führt zu meinem neuen Freund.",
		ARMORGRASS = "Eine Verschwendung von brennbaren Materialien.",
		ARMORMARBLE = "Wenn ich kämpfen muss, könnte ich dadurch sogar geschützt sein.",
		ARMORWOOD = "Jetzt kann ich die Welt erobern!",
		ARMOR_SANITY = "Als wäre man von Rauch umhüllt.",
		ASH =
		{
			GENERIC = "Überreste eines Feuers. Ich wünsche, es wäre immer noch hier.",
			REMAINS_GLOMMERFLOWER = "Ich wünsche, ich hätte gesehen, wie die unheimliche Blume brannte.",
			REMAINS_EYE_BONE = "Ich wette, dass es ein schöner Anblick war, als sich das Augending im Feuer gewunden hat.",
			REMAINS_THINGIE = "Ich wünschte, dieses Ding würde immer noch brennen. Egal, was es mal war.",
		},
		AXE = "Die ist sehr scharf.",
		BABYBEEFALO =
		{
			GENERIC = "Selbst die Babys sind hässlich.",
			SLEEPING = "WACH AUF!",
		},
		BACKPACK = "Ich könnte hier mindestens eine Million Feuerzeuge reinpacken.",
		BACONEGGS = "Der gelbe, schleimige Teil ist widerlich, aber der Speck ist spitze!",
		BANDAGE = "Ihh, muss ich?",
		BASALT = "Er ist zu hart, um es durchzubrechen!",
		BEARDHAIR = "Äh, wo kommt das denn her?",
		BEDROLL_STRAW = "Muffig.",
		BEE =
		{
			GENERIC = "Sie ist zwar dick, sieht aber trotzdem gefährlich aus.",
			HELD = "Taschen voll mit Beeren!",
		},
		BEEFALO =
		{
			FOLLOWER = "Äh, folgst du mir etwa?",
			GENERIC = "Was für ein widerliches, haariges Biest!",
			NAKED = "Ha! Jetzt ist er nackt!",
			SLEEPING = "Sie sehen noch dümmer aus, wenn sie schlafen.",
		},
		BEEFALOHAT = "Ich habe mir seine Haare genommen, um sie selbst zu verwenden.",
		BEEFALOWOOL = "Ha! Ich habe sein Haar geklaut!",
		BEEHIVE = "Voll mit Bienen!",
		BEEMINE = "Dort sind Bienen drin. Man hätte dort Feuer reintun sollen.",
		BEEMINE_MAXWELL = "Da sind Moskitos drin. Die klingen aber nicht glücklich.",
		BEEHAT = "Das wird die Stacheldinger von mir fern halten.",
		BERRIES = "Rote Beeren schmecken am besten.",
		BERRIES_COOKED = "Geröstete Rote Beeren schmecken irgendwie noch besser.",
		BERRYBUSH =
		{
			BARREN = "Friss Dünger, dumme Pflanze!",
			WITHERED = "Total ausgetrocknet. Perfekt für Feuer!",
			GENERIC = "Mmmmm. Beeren.",
			PICKED = "Ich will mehr Beeren!",
		},
		BIRDCAGE =
		{
			GENERIC = "Vogelgefängnis!",
			OCCUPIED = "Ha! Jetzt ist er nackt!",
			SLEEPING = "Dummer Vogel. Wach auf!",
			HUNGRY = "Was soll das Gegackere?",
			STARVING = "Er wird nicht immer so süß und knuddelig sein.",
			DEAD = "Wenigstens ist es jetzt warm.",
			SKELETON = "Ich kann es wahrscheinlich reparieren.",
		},
		BIRDTRAP = "Ich werde diese unheimlichen Vögel fangen.",
		BIRD_EGG = "Es riecht wie das Ende eines Vogels.",
		BIRD_EGG_COOKED = "Igitt! Der gelbe Teil ist noch flüssig.",
		BISHOP = "Ein Bischof!",
		BISHOP_CHARGE_HIT = "Auuuu!",
		BLOWDART_FIRE = "Das ist mein Lieblingsgegenstand auf der ganzen Welt.",
		BLOWDART_SLEEP = "Das Beruhigungsmittel macht es leichter, etwas in Flammen zu setzen.",
		BLOWDART_PIPE = "Gute Übung, um in ein Feuer zu pusten.",
		BLUEGEM = "Igitt. Dieser ist hässlich.",
		BLUEPRINT = "Das wird einiges an Experimenten ersparen.",
		BELL_BLUEPRINT = "Das wird einiges an Experimenten ersparen.",
		BLUE_CAP = "Der riecht wie Sportsocken!",
		BLUE_CAP_COOKED = "Ich habe sie mit dem Feuer verändert!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Dämlicher Pilz.",
			INGROUND = "Hey! Du! Komm raus da!",
			PICKED = "Vielleicht kommt er eines Tages wieder.",
		},
		BOARDS = "Bretter. Die brennen genauso gut wie normales Holz.",
		BONESTEW = "Kombiniere Feuer mit Nahrung... und voila!",
		BUGNET = "Ich kann einen Käfer fangen!",
		BUSHHAT = "Zu passiv!",
		BUTTER = "Schmeckt lecker... und ein bisschen nach Insekten.",
		BUTTERFLY =
		{
			GENERIC = "Flattere weg, Schmetterling!",
			HELD = "Ich will ihn zerquetschen.",
		},
		BUTTERFLYMUFFIN = "Hihi, der Schmetterling steckt im Muffin fest.",
		BUTTERFLYWINGS = "Der Schmetterling fliegt nicht mehr!",
		CAMPFIRE =
		{
			EMBERS = "Oh. Es ist schon fast aus!",
			GENERIC = "Ich mag Feuer.",
			HIGH = "BRENNE! BRENNE SCHNELLER!",
			LOW = "Dieses Feuer ist klein und langweilig.",
			NORMAL = "Brenne!",
			OUT = "Ohhh. Es ist vorbei.",
		},
		CANE = "Damit kann ich besser spazieren gehen!",
		CARROT = "Pfui! Vollkommen vegetarisch.",
		CARROT_COOKED = "Zwar immer noch vegetarisch, aber gut, dass sie im Feuer waren.",
		CARROT_PLANTED = "Vielleicht ist sein besonderer Karottenfreund im Boden.",
		CARROT_SEEDS = "Samen für das ekelhafte, orange Gemüse.",
		CAVE_FERN = "Sieht brennbar aus.",
		CHARCOAL = "Mmmm. Schmeckt nach Feuer.",
        CHESSJUNK1 = "Totes Aufziehpferdchen.",
        CHESSJUNK2 = "Toter Aufziehpriester.",
        CHESSJUNK3 = "Tote Aufziehfestung.",
		CHESTER = "Er ist so flauschig!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Es ist unhöflich zu Starren.",
			WAITING = "Wenigstens schaut es mich nicht mehr an.",
		},
		COOKEDMEAT = "Ist das Fleisch?",
		COOKEDMONSTERMEAT = "Es ist immer noch widerlich.",
		COOKEDSMALLMEAT = "Ich werde mehr von diesen Häppchen brauchen, wenn ich überleben will.",
		CORN = "Süßes Gemüse, lecker!",
		CORN_COOKED = "Oh. Das explodiert, wenn man es ins Feuer hält!",
		CORN_SEEDS = "Samen für mein explosives Lieblingsgemüse.",
		CROW =
		{
			GENERIC = "Ich glaube, sie wartet darauf, dass ich sterbe.",
			HELD = "Jetzt bist du nicht mehr so clever, was?",
		},
		CUTGRASS = "Geschnittenes Gras, bereit zum verbrennen. Oder zur Weiterverarbeitung.",
		CUTREEDS = "Geschnittenes Schilf, bereit zum verbrennen. Oder zur Weiterverarbeitung.",
		CUTSTONE = "Perfekt geformt für das maximale Vergnügen.",
		DEADLYFEAST = "Das Feuer hat es nicht geschafft, die Speise von seinem Ekel zu befreien.",
		DEERCLOPS = "Heilige Scheiße!",
		DEERCLOPS_EYEBALL = "Hör auf, mich anzustarren!",
		DIRTPILE = "Wer lässt hier im Wald nur seinen Dreck rumliegen?",
		DIVININGROD =
		{
			COLD = "Es macht irgendwelche Geräusche.",
			GENERIC = "Voll mit elektrischem Schrott.",
			HOT = "Ah! Genug gepiept!",
			WARM = "Das Ding wird lauter.",
			WARMER = "Ich muss schon nah dran sein!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Ich bin mir nicht sicher, was es macht. Sieht nicht so aus, als würde es Dinge entflammen.",
			READY = "Muss einfach nur mit einem Schlüssel aufgeschlossen werden. Nicht mit Feuer, leider.",
			UNLOCKED = "Jetzt summt es.",
		},
		DIVININGRODSTART = "Ich werde irgendetwas daraus machen.",
		DRAGONFLY = "Sie ist gefüllt mit Feuer!",
		LAVASPIT = 
		{
			HOT = "Die coolste Sabber!",
			COOL = "Coole Sabber, wortwörtlich.",
		},
		LAVA_POND = "Ja!",
		LAVAE = "Warum können wir nicht miteinander auskommen?",
		LAVAE_PET = 
		{
			STARVING = "Ich kann wieder sehen.",
			HUNGRY = "Ìch glaub, sie will was Angebranntes.",
			CONTENT = "Meine eigenen Pflanzeneier.",
			GENERIC = "Ideal zum Kleben!",
		},
		LAVAE_EGG = 
		{
			GENERIC = "Ich glaube, die Rute will mir irgendwas sagen!",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Entspann dich!",
			COMFY = "Das Ei sieht glücklich aus.",
		},
		LAVAE_TOOTH = "Ich frage mich, was sie getan hat.",
		DRAGONFRUIT = "Sieht aus, als würde sie Feuer mögen!",
		DRAGONFRUIT_COOKED = "Jetzt sieht es mehr nach einer Frucht aus, die im Feuer gekocht wurde.",
		DRAGONFRUIT_SEEDS = "Samen der nach Feuer aussehenden Frucht.",
		DRAGONPIE = "Feuerfrucht in einem Kuchen? Au weia!",
		DRUMSTICK = "Hau auf die Trommel... den ganzen Tag!",
		DRUMSTICK_COOKED = "Stille ich damit meinen Hunger oder schlage ich auf die Trommel?",
		DURIAN = "Ihh, das stinkt!",
		DURIAN_COOKED = "Igitt, es riecht gekocht genauso schlecht.",
		DURIAN_SEEDS = "Stinkende Samen for eine stinkende Frucht.",
		EARMUFFSHAT = "Riecht wie ein Kaninchenhintern.",
		EGGPLANT = "Definitiv kein Vogel.",
		EGGPLANT_COOKED = "Das Feuer hat die Aubergine schmackhafter gemacht.",
		EGGPLANT_SEEDS = "Entsteht aus den Samen eine Pflanze oder ein Vogel?",
		STUFFEDEGGPLANT = "Sie ist immer noch kein Vogel, aber ich habe sie wie einen ausgestopft!",
		DUG_BERRYBUSH = "Was ist los? Fehlt Erde?",
		DUG_GRASS = "Was ist los? Fehlt Erde?",
		DUG_MARSH_BUSH = "Was ist los? Fehlt Erde?",
		DUG_SAPLING = "Was ist los? Fehlt Erde?",
		EARMUFFS = "Riecht wie ein Kaninchenhintern.",
		ACORN = 
		{
		    GENERIC = "Na du! Kleiner Baumsamen.",
		    PLANTED = "Bald wirst du ein richtiger Baum sein.",
		},
		EVERGREEN =
		{
			BURNING = "JA! BRENNE!",
			BURNT = "Ich wünschte, er würde immer noch brennen.",
			CHOPPED = "Ein Baum weniger auf der Welt.",
			GENERIC = "Sieht aus, als würde er gut brennen.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "JA! BRENNE!",
			BURNT = "Ich wünschte, er würde immer noch brennen.",
			CHOPPED = "Ein Baum weniger auf der Welt.",
			GENERIC = "Stirb' im Feuer!",
		},
		EYEPLANT = "Die breiten sich aus wie Flammen.",
		FEATHERHAT = "Ich bin ein Phönix!",
		FEATHER_CROW = "Krähenfeder. Riecht wahrscheinlich schrecklich, wenn sie brennt.",
		FEATHER_ROBIN = "Feder eines roten Vogels. Riecht wahrscheinlich schrecklich, wenn sie brennt.",
		FEATHER_ROBIN_WINTER = "Feder eines Schneevogels. Riecht wahrscheinlich schrecklich, wenn sie brennt.",
		FEM_PUPPET = "Sie sieht halb zu Tode erschreckt aus.",
		FIREFLIES =
		{
			GENERIC = "Ich wünschte, sie würden nicht davonlaufen.",
			HELD = "Sie sind wie kleine Feuer in meiner Tasche!",
		},
		FIREHOUND = "Ich mag diese Dinger irgendwie.",
		FIREPIT =
		{
			EMBERS = "Oh. Es ist schon fast aus!",
			GENERIC = "Da könnt ich stundenlang zusehen.",
			HIGH = "BRENNE! BRENNE SCHNELLER!",
			LOW = "Dieses Feuer ist klein und langweilig.",
			NORMAL = "Brenne!",
			OUT = "Ich sollte das Feuer wieder zurückholen.",
		},
		FIRESTAFF = "Das ist mein absolutes Lieblingsspielzeug.",
		FISH = "Rutschiger Fisch!",
		FISHINGROD = "Zum Angeln von Antworten. Mit Schnur und Bleigewicht.",
		FISHSTICKS = "Was du siehst, ist was du bekommst. Fisch am Stiel.",
		FISHTACOS = "Praktisches Taco-Gerippe.",
		FISH_MED = "Das kann jetzt ins Feuer.",
		FISH_MED_COOKED = "Es sieht tatsächlich essbar aus.",
		FISH_COOKED = "Jetzt ist er nicht mehr so glitschig.",
		FLINT = "Der Anzünder des armen Mannes.",
		FLOWER = "Ich habe nicht die Zeit, um sie mit Blumen zu verschwenden.",
		FLOWERHAT = "Ein Heiligenschein aus Blumen. Schade, dass es kein brennender Heiligenschein ist.",
		FLOWER_EVIL = "Pfui, das riecht schrecklich.",
		FOLIAGE = "Kraftstoff für das Feuer.",
		FOOTBALLHAT = "Sport ist hart.",
		FROG =
		{
			DEAD = "Dem hab ich's gezeigt.",
			GENERIC = "Er ist feucht, um zu brennen.",
			SLEEPING = "Sie sind süß, wenn sie schlafen.",
		},
		FROGGLEBUNWICH = "Vielleicht bemerke ich gar nicht, dass da Froschschenkel auf dem Sandwich sind.",
		FROGLEGS = "Er zuckt noch ab und zu. Irre.",
		FROGLEGS_COOKED = "Das Feuer hat dafür gesorgt, dass es nicht mehr zuckt. Feuer ist das Beste.",
		FRUITMEDLEY = "Lecker, Früchte.",
		GEARS = "Damit müssen sie sich bewegen lassen.",
		GHOST = "Ich kann nicht töten, was bereits tot ist.",
		GOLDENAXE = "Sie wird zwar keine Bäume in Brand setzen, aber wenigstens funkelt sie.",
		GOLDENPICKAXE = "Sie kann zwar keine Steine entflammen, funkelt aber trotzdem.",
		GOLDENPITCHFORK = "Sie wird die Erde zwar nicht in Brand setzen, aber wenigstens funkelt sie.",
		GOLDENSHOVEL = "Sie kann zwar keine lodernden Gruben erschaffen, aber wenigstens glänzt sie.",
		GOLDNUGGET = "Wo kann ich hingehen, um es auszugeben?",
		GRASS =
		{
			BARREN = "Es braucht Dünger.",
			WITHERED = "Hübsch und trocken. Bereit zu brennen!",
			BURNING = "Feuer! Juhuuu!",
			GENERIC = "Ein brennbarer Büschel Gras.",
			PICKED = "Grasstoppeln sind irgendwie nutzlos.",
		},
		GREEN_CAP = "Langweilig!",
		GREEN_CAP_COOKED = "Ich habe sie mit dem Feuer verändert!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Dummer Pilz.",
			INGROUND = "Hey! Du! Komm raus da!",
			PICKED = "Vielleicht kommt er eines Tages wieder.",
		},
		GUNPOWDER = "Oooooooooh! Glänzend!",
		HAMBAT = "Es ist mir eine fleischgewordene Ehre!",
		HAMMER = "Ich bevorzuge scharfe Werkzeuge.",
		HEALINGSALVE = "Es brennt! Doch wo ist das Feuer?",
		HEATROCK =
		{
			FROZEN = "Eingefroren.",
			COLD = "Kalt wie ein Stein.",
			GENERIC = "Ein Feuer würde diese Sache beleben!",
			WARM = "Keine Flamme, keine echte Hitze... wo bleibt der Spaß dabei?",
			HOT = "Schau mal, wie es glüht!",
		},
		HONEY = "Süß und köstlich!",
		HONEYCOMB = "Dass ist wachsartig.",
		HONEYHAM = "Feuer, Schinken und Honig passen gut zusammen.",
		HONEYNUGGETS = "Mit Honig ummantelte Leckereien, die mit dem Feuer Bekanntschaft gemacht haben.",
		HORN = "Ich kann die haarigen Bestien im Inneren hören.",
		HOUND = "Was für ein Idiot!",
		HOUNDMOUND = "Oh, ich mag seinen Blick nicht.",
		HOUNDBONE = "Widerlich.",
		ICEBOX = "Das ist das Gegenstück zum Feuer.",
		ICEHOUND = "Widerlich! Kalt!",
		INSANITYROCK =
		{
			ACTIVE = "Bilde ich mir das nur ein?",
			INACTIVE = "Sieht nicht entflammbar aus. Wie langweilig.",
		},
		JAMMYPRESERVES = "Danke, gnädige Fräulein!",
		KABOBS = "Fleisch und Feuer, jetzt mit einem Stock.",
		KILLERBEE =
		{
			GENERIC = "Ich mag die segelartigen Flügel der Bienen.",
			HELD = "Summen!",
		},
		KNIGHT = "Es ist ein Pony!",
		KOALEFANT_SUMMER = "Wir werden gute Freunde sein!",
		KOALEFANT_WINTER = "Er sieht wirklich warm aus...",
		KRAMPUS = "Bleib zurück, du Idiot!",
		KRAMPUS_SACK = "Ja ist denn heut schon Weihnachten",
		LEIF = "Er sieht brennbar aus!",
		LEIF_SPARSE = "Er sieht brennbar aus!",
		LIGHTNING_ROD =
		{
			CHARGED = "Ohh, so viel Glühen aber kein Feuer.",
			GENERIC = "Der Blitz kann kommen!",
		},
		LITTLE_WALRUS = "Er sieht lecker aus.",
		LIVINGLOG = "Er sieht verärgert aus.",
		LOCKEDWES = "Er wird durch die Statuen festgehalten!",
		LOG =
		{
			BURNING = "Brenne, Holzklotz, brenneeeeeeee!",
			GENERIC = "Holz! Damit lässt sich Feuer machen. Hurra!",
		},
		LUREPLANT = "Ich wette ein schnelles Feuer würde seine Aufmerksamkeit erregen.",
		LUREPLANTBULB = "Das gehört jetzt mir.",
		MALE_PUPPET = "Er sieht halb zu Tode erschreckt aus.",
		MANDRAKE =
		{
			DEAD = "Wieso hat diese Pflanze ein Gesicht?",
			GENERIC = "Das ist keine gewöhnliche Pflanze.",
			PICKED = "Das ist einfach nur unheimlich!",
		},
		COOKEDMANDRAKE = "Das Feuer konnte sein Gesicht nicht entfernen. Das macht mich nervös.",
		MANDRAKESOUP = "Das Gesicht lässt sich nicht abwaschen.",
		MARBLE = "Das ist schwer!",
		MARBLEPILLAR = "Ich frage mich, ob der Rest abgebrannt ist.",
		MARBLETREE = "Die schlechteste Art des Baums. Die nicht entzündbare Art.",
		MARSH_BUSH =
		{
			BURNING = "Brennt, ihr Dornen!",
			GENERIC = "Das sieht scharf aus.",
			PICKED = "Die Dornen tun weh!",
		},
		MARSH_PLANT = "Pflanze.",
		MARSH_TREE =
		{
			BURNING = "JA! BRENNE!",
			BURNT = "Ich wünschte, er würde immer noch brennen.",
			CHOPPED = "Jetzt bist du nicht mehr so stachlig, was?",
			GENERIC = "Sieht gefährlich aus!",
		},
		MAXWELL = "Er ist so herablassend.",
		MAXWELLHEAD = "Er mag es zu sprechen.",
		MAXWELLLIGHT = "Dies macht keinen Spaß. Die zünden sich selbst an.",
		MAXWELLLOCK = "Jetzt brauche ich nur noch einen Schlüssel.",
		MAXWELLTHRONE = "Sieht klebrig aus.",
		MEAT = "Mit FEUER könnte ich es aufwerten!",
		MEATBALLS = "Kugeln aus Fleisch, die im Feuer nochmals verbessert wurden.",
		MEAT_DRIED = "Schwer zu kauen, aber zufriedenstellend.",
		MERM = "Ihh, er ist total sumpfig.",
		MONSTERLASAGNA = "Nudeln, Fleisch und Haarklumpen. Ekelhaft.",
		MONSTERMEAT = "Widerlich. Voller Haare.",
		MONSTERMEAT_DRIED = "Es ist trocken und riecht seltsam.",
		MOSQUITO =
		{
			GENERIC = "So nervig!",
			HELD = "Halt deinen Mund von mir fern!",
		},
		MOSQUITOSACK = "Das Blut blubbert und strömt feuchtwarm und dickflüssig hindurch.",
		MOUND =
		{
			DUG = "Besser er als ich.",
			GENERIC = "Ich wette, er ist voll mit totem Zeug.",
		},
		NIGHTLIGHT = "Das ist wie Feuer, nur lila!",
		NIGHTMAREFUEL = "Ihh, es ist noch warm!",
		NIGHTSWORD = "Es ist so, als könnten meine Träume reale Dinge verletzen.",
		NITRE = "Darin sind winzige Explosionen gefangen.",
		ONEMANBAND = "Ich kann die Pyrotechnik auch machen!",
		PANDORASCHEST = "Irgendwie klebrig.",
		PANFLUTE = "Musik ist langweilig.",
		PAPYRUS = "Ich wette, dass es brennt!",
		PENGUIN = "Verschwindet, ihr kleinen Tänzer.",
		PERD = "Böser Vogel! Verschwinde von meinen leckeren Beeren!",
		PEROGIES = "Schmackhafte Dinger, im Feuer zubereitet.",
		PETALS = "Blöde Blumen. Zu fast nichts zu gebrauchen.",
		PETALS_EVIL = "Ihh, die kleben.",
		PICKAXE = "Die ist sehr spitz.",
		PIGGYBACK = "Ich habe einen Rucksack aus einem Hinterteil hergestellt.",
		PIGKING = "Igitt! Was für ein Chaot.",
		PIGMAN =
		{
			DEAD = "Ich frage mich, wie sie schmecken würden.",
			FOLLOWER = "Ihh. Es verfolgt mich.",
			GENERIC = "Igitt! Die riechen.",
			GUARD = "Er ist nicht mein Boss!",
			WEREPIG = "Versuch's doch, Schweinchen!",
		},
		PIGSKIN = "Haha. Das Hinterteil eines Schweins.",
		PIGTORCH = "Die Schweine scheinen zu wissen, wie man sich gut fühlt.",
		PINECONE = 
		{
		    GENERIC = "Na du! Kleiner Baumsamen.",
		    PLANTED = "Bald wirst du ein richtiger Baum sein.",
		},
		PITCHFORK = "Dreimal spitz.",
		PLANTMEAT = "Ihh, das ist total schleimig.",
		PLANTMEAT_COOKED = "Feuer macht alles besser.",
		PLANT_NORMAL =
		{
			GENERIC = "Ich werde es essen, wenn ich muss.",
			GROWING = "Beeil dich, du dumme Pflanze!",
			READY = "Oh, man. Gemüse.",
			WITHERED = "Sie ist knisternd und trocken. Gutes Anzündholz!",
		},
		POMEGRANATE = "Hat das immer so viele Teile?",
		POMEGRANATE_COOKED = "Mit Feuer wird alles besser.",
		POMEGRANATE_SEEDS = "Ein winziger Samen. Sieht aus wie die Teile im Inneren der Frucht.",
		POOP = "Ihh. Ekelhaft. Aber nützlich.",
		PUMPKIN = "Ich frage mich, was geschieht, wenn ich ihn mit Feuer kombiniere.",
		SCORCHED_SKELETON = "Bäääääh!",
		PUMPKINCOOKIE = "Kekse!!!",
		PUMPKIN_COOKED = "Die äußere Einwirkung von Feuer hat sich als ziemlich gut erwiesen.",
		PUMPKIN_LANTERN = "Das Feuer im Inneren ist beeindruckend.",
		PUMPKIN_SEEDS = "Samen für den besten Gemüsefreund des Feuers: Der Kürbis.",
		PURPLEGEM = "Unheimlich!",
		RABBIT =
		{
			GENERIC = "Er sieht lecker aus.",
			HELD = "Ich habe ihn, wo ich ihn haben will.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Dumme Kaninchen. Kommt raus, damit ich euch essen kann.",
			SPRING = "Die dummen Kaninchen sind da unten wohl stecken geblieben.",
		},
		RATATOUILLE = "Gemüse. So viel Gemüse.",
		RAZOR = "Warum habe ich das gebaut?",
		REDGEM = "So hübsch!",
		RED_CAP = "Ich liebe diese Farbe!",
		RED_CAP_COOKED = "Ich habe sie mit dem Feuer verändert!",
		RED_MUSHROOM =
		{
			GENERIC = "Hübsch!",
			INGROUND = "Hey! Du! Komm raus da!",
			PICKED = "Vielleicht kommt er eines Tages wieder.",
		},
		REEDS =
		{
			BURNING = "Brenne! Jaaa!",
			GENERIC = "Ein brennbarer Klumpen Schilf.",
			PICKED = "Mit den Schilfstoppeln kann ich nichts anfangen.",
		},
        RELIC = 
        {
            GENERIC = "Alte Möbel.",
            BROKEN = "Stückchen und Stücke, Stücke und Stückchen.",
        },
        RUBBLE = "Kaputte Möbel.",
		RESURRECTIONSTONE = "Ich schätze, ich soll es berühren?",
		ROBIN =
		{
			GENERIC = "Ein roter Vogel. Die Farbe des Feuers, auch wenn es kein Phönix ist.",
			HELD = "Es ist bequem in meiner Tasche.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Er sieht kalt aus. Ich wette er hätte gern ein warmes Feuer.",
			HELD = "Er ist wirklich flauschig.",
		},
		ROBOT_PUPPET = "Er sieht halb zu Tode erschreckt aus.",
		ROCK_LIGHT =
		{
			GENERIC = "Vielleicht kann ich ihr noch aus dem Weg gehen.",
			OUT = "Ohh, es ist kühler geworden.",
			LOW = "Die Lava ist die Kühlung.",
			NORMAL = "Eine Feuergrube.",
		},
		ROCKS = "Muscheln am See. Oder Kuscheln im Schnee?",
        ROOK = "Das ist eine Festung!",
        ROPE = "Was kann ich damit festmachen?",
		ROTTENEGG = "Ähm. Warum nur?",
		SANITYROCK =
		{
			ACTIVE = "Ich frage mich, was diese Markierungen bedeuten.",
			INACTIVE = "Wo führt das hin?",
		},
		SAPLING =
		{
			BURNING = "Brenne! Jaaa!",
			WITHERED = "Es ist so trocken. Es sieht fast so aus, als würde es gern brennen.",
			GENERIC = "Ich sollte ihn mitnehmen.",
			PICKED = "Armes, kleines Bäumchen.",
		},
		SEEDS = "Landwirtschaft ist langweilig.",
		SEEDS_COOKED = "Zum Anpflanzen nicht mehr zu gebrauchen.",
		SEWING_KIT = "Aber Zerstörung ist viel lustiger!",
		SHOVEL = "Nicht so gut, um damit zu kämpfen.",
		SILK = "Mmmmmm. Weich.",
		SKELETON = "Oh, man. Ich hoffe, dass er in der Herrlichkeit der Flamme untergegangen ist.",
		SKELETON_PLAYER = "Das macht mich nervös.",
		SKULLCHEST = "Ooooh unheimlich!",
		SMALLBIRD =
		{
			GENERIC = "Kein Phönix, aber trotzdem süß.",
			HUNGRY = "Bist du hungrig?",
			STARVING = "Ok, ok! Ich hab's verstanden. Du hast Hunger.",
		},
		SMALLMEAT = "Mit FEUER könnte ich es aufwerten!",
		SMALLMEAT_DRIED = "Schwer zu kauen, aber zufriedenstellend.",
		SPAT = "Dein Gesicht gefällt mir nicht, Baum!",
		SPEAR = "Spüre meinen Zorn!",
		SPIDER =
		{
			DEAD = "Ha! Dir hab ich's gezeigt.",
			GENERIC = "Sie ist widerlich. Ich sollte sie töten.",
			SLEEPING = "Ich könnte ihn mitnehmen.",
		},
		SPIDERDEN = "Das ist einfach nur widerlich.",
		SPIDEREGGSACK = "Tonnen von winzigen, widerlichen Spinnen.",
		SPIDERGLAND = "Iihhh, das ist schleimig und stinkend!",
		SPIDERHAT = "Wer ist deine Mama!",
		SPIDERQUEEN = "Töte es mit Feuer!",
		SPIDER_WARRIOR =
		{
			DEAD = "Er hat es drauf angelegt.",
			GENERIC = "Vielleicht könnte ich ihn... mit FEUER töten.",
			SLEEPING = "Vielleicht sollte ich ihn einfach allein lassen.",
		},
		SPOILED_FOOD = "Wenigstens ist es immer noch brennbar.",
		STATUEHARP = "Was für eine schöne Statue. Wäre schade, wenn der was passieren würde.",
		STATUEMAXWELL = "Ich fange an, diesen Mann nicht zu mögen.",
		STEELWOOL = "Es könnte leben, aber es wird trotzen brennen.",
		STINGER = "Spitz.",
		STRAWHAT = "Ein Hut aus Stroh. Es hätte auch Zunder sein können.",
		SUNKBOAT = "Es ist zu weit draußen. Ich kann es nicht mal anzünden!",
		SWEATERVEST = "Nicht so toll wie eine Flammenweste, aber dennoch in Ordnung.",
		TAFFY = "Die süßen Dinger brennen ausgezeichnet, aber ich sollte sie lieber essen.",
		TALLBIRD = "Ich glaube nicht, dass er mit mein Freund sein möchte.",
		TALLBIRDEGG = "Ob es Feuer mag?",
		TALLBIRDEGG_COOKED = "Feuer macht sie so viel besser.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Braucht mehr Feuer!",
			GENERIC = "Steig auf, mein Phönix.",
			HOT = "War das zu viel Feuer?",
			LONG = "Wie lange wird es dauern?",
			SHORT = "Ich werde vom Warten müde.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Das Ei könnte ein bisschen Feuer vertragen!",
			PICKED = "Das Nest ist leer.",
		},
		TEENBIRD =
		{
			GENERIC = "Ich fühle mich, als würde er mich verstehen.",
			HUNGRY = "Er isst sicher viel.",
			STARVING = "Sieh mich nicht so an! Hol dir dein eigenes Essen.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Ich will diese Welt einfach nur brennen sehen.",
			GENERIC = "Ich mag es, wie die Symbole leuchten.",
			LOCKED = "Muss irgendwie aufgeschlossen werden.",
			PARTIAL = "Ich erschaffe eine Monstrosität!",
		},
		TELEPORTATO_BOX = "Fühlt sich warm an.",
		TELEPORTATO_CRANK = "Wofür ist dieses Teil gut?",
		TELEPORTATO_POTATO = "Vielleicht könnte ich es in eine etwas angenehmere Form schmelzen.",
		TELEPORTATO_RING = "Der ist zu kostbar, um ihn zu verbrennen.",
		TENTACLE = "Überhaupt nicht knuddelig.",
		TENTACLESPOTS = "Iiiiihhhh.",
		TENTACLESPIKE = "Er ist spitz und schleimig.",
		TENTACLE_PILLAR = "Es zittert.",
		TENTACLE_PILLAR_HOLE = "Was für ein Gestank! Mach nächstes Mal ein Fenster auf!",
		TENTACLE_PILLAR_ARM = "Ohhhh, sie wollen eine Umarmung!",
		TENTACLE_GARDEN = "Ich kann Grabegeräusche hören.",
		
		LAVA_POND_ROCK = "Na toll, noch ein Fels!",
		LAVA_POND_ROCK2 = "Na toll, noch ein Fels!",
		LAVA_POND_ROCK3 = "Na toll, noch ein Fels!",
		LAVA_POND_ROCK4 = "Na toll, noch ein Fels!",
		LAVA_POND_ROCK5 = "Na toll, noch ein Fels!",
		LAVA_POND_ROCK6 = "Na toll, noch ein Fels!",
		LAVA_POND_ROCK7 = "Na toll, noch ein Fels!",

		TOPHAT = "Ein Zylinder und ein Feuerzeug, eine perfekte Kombination.",
		TORCH = "Feuer ist so hübsch.",
		TRAP = "Sie ist zwar irgendwie passiv aggressiv, aber sie funktioniert.",
		TRAP_TEETH = "Mit Feuer wäre sie besser.",
		TRAP_TEETH_MAXWELL = "Welcher Idiot lässt so etwas hier rumliegen.",
		TRINKET_1 = "Ich wette, dass das Feuer ziemlich heiß war, welches diese Ding geschmolzen hat.",
		TRINKET_10 = "Ich glaube nicht, dass Zahnprothese schlecht brennen.",
		TRINKET_11 = "Ooh, ich frage mich, ob er einen Flammenwerfer hat!",
		TRINKET_12 = "Total ausgetrocknet, als ob es zu nahe am Feuer war.",
		TRINKET_2 = "Eine billige Fälschung. Brennt bestimmt nicht mal richtig.",
		TRINKET_3 = "Der Knoten ist fest. Wer braucht ein Messer, wenn man Feuer haben kann?",
		TRINKET_4 = "Sieht aus, wie in Flammen geschmiedet.",
		TRINKET_5 = "Schau dir diese kleine Rakete an. Solch explosive Kraft!",
		TRINKET_6 = "Nicht mal ein Funken.",
		TRINKET_7 = "Feuer ist lustiger.",
		TRINKET_8 = "Ich habe nie gern mit Wasser gebadet.",
		TRINKET_9 = "An einem Reissverschluss kann man ein Streichholz anmachen. An einem Knopf nicht.",
		TRUNKVEST_SUMMER = "Jetzt werde immer mit meinem Freund zusammen sein.",
		TRUNKVEST_WINTER = "Nicht so warm wie ein gutes Feuer, aber trotzdem schon ganz gut.",
		TRUNK_COOKED = "Ich bin mir noch immer nicht sicher, ob ich das essen will.",
		TRUNK_SUMMER = "Ein Teil von ihm ist immer noch knuddelig.",
		TRUNK_WINTER = "Er ist so weich und matschig!",
		UMBRELLA = "Ich liebe diese Farbe!",
		WAFFLES = "Hi, Waffeln!",
		WALL_HAY_ITEM = "Hmmm. Ich frage mich, ob das brennen wird.",
		WALL_STONE = "Ähm. Ich schätze, das ist okay.",
		WALL_STONE_ITEM = "Die sind überraschenderweise schwer.",
		WALL_RUINS = "Die zerfallen schon fast, wenn man sie nur anschaut!",
		WALL_RUINS_ITEM = "Werden die in meine Taschen passen?",
		WALL_WOOD_ITEM = "Verstecken mag ich nicht.",
		WALL_MOONROCK = "Jetzt ist es sicher.",
		WALL_MOONROCK_ITEM = "Ich glaube, das könnte ich abholzen.",
		WALRUS = "Hör' auf mir zu folgen!",
		WALRUSHAT = "Irgendwie mag ich den Stil.",
		WALRUS_CAMP =
		{
			EMPTY = "Dort gehe ich nicht rein. Pfui!",
			GENERIC = "Wieso hat eigentlich jeder ein hübscheres Haus als ich?",
		},
		WALRUS_TUSK = "Mampf mampf!",
		WARDROBE = 
		{
			GENERIC = "Ich möchte nicht die Welt in Brand setzen.",
            BURNING = "JA! BRENNE!",
			BURNT = "Ohh, so viel Glühen aber kein Feuer.",
		},
		WARG = "Du bist ein großer, fieser Trottel!",
		WASPHIVE = "Ich sollte auf Abstand bleiben.",
		WETGOOP = "Wie konnte das passieren? Ich hab es ins Feuer getan und alles.",
		WINTERHAT = "Nach meinem Geschmack ist er nicht warm genug.",
		WORMHOLE =
		{
			GENERIC = "Ich sollte es mal mit einem Stock pieken.",
			OPEN = "Ich frage mich, ob es scharfes Essen mag.",
		},
		ACCOMPLISHMENT_SHRINE = "Ich hasse diesen Pfeil!", 

		------------------------------------------------------capy--------------------------------
		AERODYNAMICHAT = "Zügige Fortbewegung...",
		ARMOR_LIFEJACKET = "Aber wird sie mich auch trocken halten?",
		ARMOR_SNAKESKIN = "Dieser Mantel bringt mich dazu, mich gefährlich zu fühlen.",
		ARMOR_WINDBREAKER = "Wind ist der Feind des Feuers.",
		ARMORLIMESTONE = "Sie ist so... schwer.",
		ARMOROBSIDIAN = "Schlag mich und brenne!",
		ARMORSEASHELL = "Versucht's nur, ihr Schurken.",
		ARMOUREDBOAT = "Diesem Schiff kann keiner was.",
		BABYOX = "Du stinkst!",
		BALLPHIN = "Du siehst nicht besonders brennbar aus.",
		BALLPHINPOD = "Eine Gruppe von lebhaften Dingern.",
		BAMBOOTREE = "A stick-y shrub.",
		BERRYBUSH2_SNAKE = "Mmmmm. Beeren.",--I don't think these should have diff name or examine text
		BERRYBUSH_SNAKE = "Mmmmm. Beeren.",--I don't think these should have diff name or examine text
		BIOLUMINESCENCE = "Das ist ein kaltes Licht. Nicht wie das einer echten Flamme...",
		BLOWDART_POISON = "Ein kranker Kuss.",
		BOAT_LANTERN = "Licht ohne eine Flamme. Ich mag es kein bisschen.",
		BOTTLELANTERN = "Das Licht ist so kalt und fremdartig.",
		BURIEDTREASURE = "Wenn ich den Schatz nicht mag, dann verbrenne ich die ganze Truhe.",
		BUSH_VINE = "I bet these crackle and pop when they burn.",
		SNAKEDEN = "I bet these crackle and pop when they burn.",--I don't think these should have diff name or examine text
		CANNONSHOT = "Feuer!",
		CAPTAINHAT = "Damit habe ich nicht länger Angst.",
		CARGOBOAT = "Damit kann ich eine Menge brennbare Sachen transportieren.",
		CHIMINEA = "Magst du dein neues Zuhause, Feuer? Gern geschehen.",
		CIRCLINGSEAGULL = "Fliegt in die Sonne, ihr Idioten.",
		CLOTHSAIL = "Gute Nähte.",
		COCONUT = 
		{
		    GENERIC = "Eine essbare Baumfrucht.",
		    PLANTED = "Schnell, wachs schon! Ich brauch Schatten.",
		},
		COCONUT_COOKED = "Mmmm, nicht schlecht.",
		COFFEE = "Ich fühle mich plötzlich motiviert.",
		COFFEEBEANS = "Diese könnten Feuer vertragen.",
		COFFEEBEANS_COOKED = "Mmh, das Aroma.",
		COFFEEBUSH = "This bush flourishes near the volcano's fire!",
		CORAL = "Hübsche Farben.",
		CORALREEF = "Ich wünschte, ich hätte einen Schnorchel.",
		CUTLASS = "Dieses Schwert riecht.",
		DEAD_SWORDFISH = "Mit Feuer würde man diesen Geruch bestimmt loswerden.",
		DEPLETED_BAMBOOTREE = "Hallo? Gibt's noch mehr Bambus?",
		DEPLETED_BUSH_VINE = "Komm zurück!",
		DOYDOY = "Sieht nicht sonderlich intelligent aus.",
		DOYDOYBABY = "Du armer, kleiner Dummkopf.",
		DOYDOYEGG = "Dummes Ei.",
		DOYDOYEGG_COOKED = "Es war schlau von mir, dieses dumme Ei zu kochen.",
		DOYDOYEGG_CRACKED = "Der Planet ist gerade ein bisschen dümmer geworden.",
		DOYDOYFEATHER = "Die würde brennen.",
		DOYDOYNEST = "Jede Sekunde wird ein Dummkopf geboren.",
		DUBLOON = "Piratenmünzen!",
		DUG_BAMBOOTREE = "Du brauchst schnell etwas Erde.",
		DUG_BERRYBUSH2 = "Möchtest du wieder leben?",
		DUG_BUSH_VINE = "Würdest du gern wieder in der Erde stecken?",
		DUG_COFFEEBUSH = "Ich weiß schon, was ich mit dir mache.",
		EARRING = "Wie ein Ritter in etwas merkwürdiger Rüstung.",
		FABRIC = "Es ist erstaunlich, was man alles mit Bambus machen kann.",
		FEATHERSAIL = "Das gibt ein gutes Segel ab.",
		FIRERAIN = "Lass es regnen!",
		FIRERAINSHADOW = "Hier kommt es!",
		FISHINHOLE = "Warum hier, Fischlein?",
		GASHAT = "Ich rieche nicht gern stinkende Gerüche.",
		GOLDENMACHETE = "Ich will sie nicht abnutzen.",
		ICEMAKER = "It turns fire into ice. Boo.",
		IRONWIND = "Jetzt kommen wir überall hin.",
		JELLYFISH = "Sie ist schrumplig.",
		JELLYFISH_DEAD = "Jetzt nützt es niemandem mehr etwas.",
		JELLYFISH_COOKED = "Es sieht tatsächlich essbar aus.",
		JELLYFISH_PLANTED = "Ich werde dich \"Jerald\" nennen.",
		JELLYJERKY = "Sieht zäh aus.",
		JUNGLETREESEED =
        {
            GENERIC = "Ein zukünftiger Waldbrand.",
            PLANTED = "In nicht allzu ferner Zukunft kann das ein Waldbrand werden.",
        },
		LAVAPOOL = "Welch wunderbare Hitze und Wut!",
		LIMESTONE = "Rüstung aus der Muschelwohnung.",
		LIMPETS = "Ein bisschen Feuer und du wirst schmackhaft sein.",
		LIMPETS_COOKED = "Ziemlich gut!",
		LOBSTERHOLE = "Hier wohnt man als glücklicher Hummer.",
		LOGRAFT = "Lagerfeuer-Holz kann auch anders verwendet werden!",
		MOSQUITO_POISON = "Schsch! Weg da!",
		MUSSEL = "Öffne dich, Kumpel.",
		MUSSEL_COOKED = "Das Feuer öffnet ihre Schale.",
		MUSSEL_STICK = "Die Muscheln mögen den Stab aus irgendeinem Grund.",
		OBSIDIAN = "Ein Feuerstein!",
		OBSIDIAN_WORKBENCH = "Feuer-Gegenstände können hier geschmiedet werden!",
		OBSIDIANAXE = "Was für eine Axt! Hackt UND verbrennt?!",
		OBSIDIANCOCONADE = "Das Obsidian sorgt für mehr Bums.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Oh. Es ist schon fast aus!",
			GENERIC = "Da könnt ich stundenlang zusehen.",
			HIGH = "BRENNE! BRENNE SCHNELLER!",
			LOW = "Dieses Feuer ist klein und langweilig.",
			NORMAL = "Ich fühle mich so verwöhnt!",
			OUT = "Ich sollte das Feuer wieder zurückholen.",
		},
		OBSIDIANMACHETE = "Eine Feuermachete ist des Mädchens bester Freund!",
		SPEAR_OBSIDIAN = "Ich stoße zu. Sie brennen!",
		OBSIDIANSPEARGUN = "Ich versuch mein Bestes.",
		PACKIM = "Freund oder Feind?",
		PACKIM_FISHBONE = "Das sieht bedeutsam aus.",
		PALMLEAF = "Bald wirst du ein richtiger Baum sein.",
		PALMTREE_BURNT = "Was für ein lieblicher Geruch.",
		PALMTREE_STUMP = "Und wieder hat einer den Löffel abgegeben.",
		PARROT = "Was für eine intensiv rote Farbe du besitzt.",
		PIRATEHAT = "Ich fühle mich unartig, wie ein Pirat.",
		PIRATIHATITATOR = "Cursed pirate magic?",
		POISONHOLE = "Die Natur ist so widerlich.",
		RAFT = "Es anzuzünden, während man damit auf See ist, wäre unklug.",
		ROWBOAT = "Rudern? Wirklich?",
		SAIL = "Es macht sich den Wind zunutze.",
		SAND = "Wow, Sand. Großartig.",
		SANDBAG = "Ein Sack voll Sand.",
		SANDBAG_ITEM = "Soll ich ihn einfach auf den Boden legen?",
		SANDHILL = "Oh, schau mal! Das ist Sand.",
		SEAGULL = "Fürchtet sie Feuer? Sie sollte es.",
		SEASACK = "Muss ich dieses durchnässte Ding auf meinem Rücken tragen?",
		SEASHELL = "Dumme Muschel.",
		SEASHELL_BEACHED = "Dumme Muschel.",
		SEATRAP = "Kommt schon, schwimmt rein da. Ist es gemütlich.",
		SEAWEED = "Nasses Seegras.",
		SEAWEED_COOKED = "Nicht schlecht, wenn es im Feuer war.",
		SEAWEED_DRIED = "Gesundes Trockenfleisch.",
		SEAWEED_PLANTED = "Nasses Seegras.",
		SHARX = "Schwimmende Idioten.",
		SLOTMACHINE = "Sieht wie Zeitverschwendung aus.",
		SNAKE = "Schlängelnde Idioten.",
		SNAKE_FIRE = "Du hast dieselben Interessen wie ich.",
		SNAKESKIN = "Lederartig.",
		SNAKESKINHAT = "Wasser prallt einfach davon ab.",
		SPEAR_POISON = "Ich hoffe, ich steche mich nicht selbst.",
		SPEARGUN = "Ein praktisches Werkzeug auf hoher See.",
		SPEARGUN_POISON = "Das ist fast schon zu bösartig.",
		STUNGRAY = "Jetzt habe ich wirklich alles gesehen.",
		SUPERTELESCOPE = "Ich kann bis ans Ende der Welt gucken.",
		SWORDFISH = "En garde!",
		TELESCOPE = "Inseln können sich nicht mehr vor mir verstecken.",
		TIGERSHARK = "Meine Albträume sind wahr geworden!",
		TIGERSHARKSHADOW = "Nicht gut! Nicht gut!",
		TOUCAN = "Ich mag deine Nase.",
		TRAWLNET = "Damit werde ich ein Haufen nasses Zeug fangen.",
		TRAWLNETDROPPED = "Everything is going to be wet in there.",
		TREEGUARD = "Ich mag dich nicht. Du magst mich nicht.",
		TRIDENT = "Der ist vollkommen nass.",
		TRINKET_13 = "Ist das Löschwasser? Es ist orange.",
		TRINKET_14 = "Ich habe keine Nadeln...",
		TRINKET_15 = "Oh, die würde brennen.",
		TRINKET_16 = "Abfälle sind ein schreckliche Sache.",
		TRINKET_17 = "Nicht mein Geschmack.",
		TRINKET_18 = "Ich frage mich, ob die was wert ist?",
		TRINKET_19 = "Gehirnwolke? Hört sich tragisch an.",
		TURBINE_BLADES = "Wozu sind die da?",
		TURF_BEACH = "Der Boden ist langweilig.",
		TURF_JUNGLE = "Der Boden ist langweilig.",
		VENOMGLAND = "Widerlich! Ich wünschte, ich hätte Handschuhe.",
		VINE = "Ich könnte sie zu was gebrauchen. Oder einfach verbrennen.",
		VOLCANO = "Das größte und feurigste Feuer aller Länder!",
		VOLCANO_ALTAR = "Why would I wanna appease the volcano? Then it wouldn't shoot fire!",
		VOLCANO_ALTAR_BROKEN = "Jetzt gibt es keine Möglichkeit mehr, den Hunger des Vulkans zu stillen!",
		VOLCANO_EXIT = "Ich hasse es, diesen Ort zu verlassen...",
		VOLCANOSTAFF = "Ich bin eine Göttin der feurigen Zerstörung!",
		WALL_LIMESTONE = "Sie ist ganz rau.",
		WALL_LIMESTONE_ITEM = "Siehst nicht aus, als würdest du leicht brennen.",
		WHALE_BLUE = "Dass es so große Fische gibt, wusste ich gar nicht.",
		WHALE_CARCASS_BLUE = "Er fängt an zu gammeln... Iiih.",
		WHALE_CARCASS_WHITE = "Der Sieg riecht nicht sonderlich gut...",
		WHALE_WHITE = "Ich kann das Feuer in seinen Augen sehen!",
		CRABHOLE = "Komm raus und spiel mit mir!",
		CRAB =
		{
			GENERIC = "Lauf doch nicht immer weg!",
			HIDDEN = "Ich bin mir ziemlich sicher, dass sich dort eine Krabbe versteckt.",
		},
		BERMUDATRIANGLE = "Mir wird irgendwie schwindelig, wenn ich es anschaue.",
		BOATCANNON = "Ich frage mich, ob ich damit ein Feuer legen kann.",
		BOATREPAIRKIT = "Das sollte kleinere Lecks flicken.",
		MACHETE = "Oder ich könnte mir meinen Weg einfach mit Feuer freimachen.",
		LUGGAGECHEST = "Ohh! Ich hoffe da sind nützliche Sachen drin.",
		DRAGOON = "Wenn ich doch nur herausfinden könnte, wie man sie dressieren kann.",
		ANTIVENOM = "Das wird helfen, wenn ich mal vergiftet werde.",
		BAMBOO = "Sieht brennbar aus.",
		FROG_POISON = "Bäh. Bleib mir bloß vom Leib.",
		OX = "Du siehst ziemlich kräftig aus.",
		PEACOCK = "Hübsch!",
		SEAGULL_WATER = "Selber \"Krächz\".",
		SNAKE_POISON = "Das sind wirklich spitze Zähne.",
		SOLOFISH = "Sieht nicht sehr klug aus.",
		SPOILED_FISH = "Widerlich.",
		TWISTER = "Bleib von meinen kostbaren Flammen fern!",
		SAND_CASTLE =
		{
			GENERIC = "Ganz niedlich.",
			SAND = "Das ist eine Sandburg im Sand!",
		},
		SNAKEOIL = "Ich bin nicht überzeugt.",
		LOBSTER = "Komm her, du!",
		MESSAGEBOTTLE = "Papier in einer Flasche.",
		MESSAGEBOTTLEEMPTY = "Das ist eine Flasche.",
		SHARK_FIN = "Die Flosse ist abgefallen.",
		VOLCANO_ALTAR =
		{
		 	GENERIC = "Ein Altar, um den Hunger der Götter zu sättigen!",
		 	OPEN = "Bereit, um sich im Feuer zu verzehren!",
		},
		ELEPHANTCACTUS = "Nicht an mir reiben!",
		ELEPHANTCACTUS_ACTIVE = "Autsch!",
		ELEPHANTCACTUS_STUMP = "Und bleib dort unten!",
		DOUBLE_UMBRELLAHAT = "Wenn ich das in einem Laden gekauft hätte, würde ich mich veralbert fühlen.",
		MUSSEL_FARM =
		{
			GENERIC = "Knapp außer Reichweite.",
			STICKPLANTED = "Bald wirst du mein sein.",
		},
		WOODLEGS_CAGE = "Kleines Ei scheint sich nicht wohlzufühlen.",

		 PIRATIHATITATOR =
		 {
		 	GENERIC = "Das ist einfach nur lächerlich.",
		 	BURNT = "Das ist schon eher mein Stil.",
		 },
		 COFFEEBUSH =
		 {
		 	BARREN = "Da ist nichts mehr zu holen.",
		 	PICKED = "Ach, aber ich möchte noch eine Tasse...",
		 	WITHERED = "Es braucht Asche und Liebe. Vor allem Asche.",
		 	GENERIC = "Heißer Kaffee von heißer Lava!",
		 },
		 DUG_ELEPHANTCACTUS = "Ich muss dich nicht gießen, richtig?",
		 WHALE_BUBBLES = "Woher kommen diese Blasen?",

		ARMORCACTUS = "So stech ich mich nicht an den Kakteen.",
		BAMBOOTREE =
		{
			BURNT = "Ah, kann ich es nochmal verbrennen?",
			CHOPPED = "Ich werde später nochmals wiederkommen müssen.",
			GENERIC = "Sieht aus wie Feueranzünder.",
		},
		BLOWDART_FLUP = "SO EIN WIND",
		BLUBBER = "Es ist noch nicht fertig. Aber ich wette, dass es trotzdem brennt.",
		BLUBBERSUIT = "Ich frage mich, ob ich diesen Felsen bewegen könnte.",
		BOAT = "BRENNE! BRENNE SCHNELLER!",
		BOAT_TORCH = "Sie pulsiert seltsamerweise.",
		BRAINJELLYHAT = "Ich fühle mich klüger.",
		BUOY = "Mann, bin ich froh, dich zu sehen.",
		BUSH_VINE =
		{
			BURNT = "Die brennen wunderbar!",
			CHOPPED = "So entwirrt man das.",
			GENERIC = "Ich wette, er knistert und knallt, wenn er brennt.",
		},
		COCONADE =
		{
			BURNING = "Los geht's...",
			GENERIC = "Zuerst dröhnt es, dann brennt es.",
		},
		COCONUT_HALVED = "Aha! Jetzt kann man dich essen!",
		COFFEEBOT = "Es macht Kaffee!",
		COMPASS =
		{
			E = "Osten.",
			GENERIC = "Ich kann keinen Messwert ablesen.",
			N = "Norden.",
			NE = "Nordosten.",
			NW = "Nordwesten.",
			S = "Süden.",
			SE = "Südosten.",
			SW = "Südwesten.",
			W = "Westen...",
		},
		CORAL_BRAIN = "An den Geschmack könnte ich mich gewöhnen...",
		CORAL_BRAIN_ROCK = "Geniale Idee, sich bei diesen dummen Korallen zu verstecken.",
		CRATE = "Wenn ich sie anzünde, verbrennt auch das, was drinsteckt...",
		DEPLETED_GRASS =
		{
			GENERIC = "Was für ein erbärmliches bisschen Gras!?",
		},
		DEPLETED_GRASS_WATER = "Es macht nur eine Pause.",
		DRAGOONDEN = "Hier leben ein paar Hitzköpfe.",
		DRAGOONEGG = "Ich glaube, dieser heiße Stein ist eigentlich ein heißes Ei.",
		DRAGOONHEART = "Nichts geht über eine warme Mahlzeit!",
		DRAGOONSPIT = "Eine brennende Pfütze...",
		FISH_RAW = "Braucht mehr Feuer!",
		FISH_RAW_SMALL = "Ich mag Sushi, aber am liebsten flambiert.",
		FISH_RAW_SMALL_COOKED = "Feuer, Schinken und Honig passen gut zusammen.",
		FLAMEGEYSER = "Wunderbar!",
		FLOTSAM = "HILFE! Mir reicht es jetzt!",
		FLUP = "Verflupp dich!",
		FRESHFRUITCREPES = "Aber hallo!",
		GRASS_WATER = "Es braucht keine Arbeit.",
		HAIL_ICE = "Jetzt schmilz schon!",
		HOME = "Wer wohnt hier?",
		ICEMAKER =
		{
			HIGH = "Ich frage mich, wie sie befeuert wird.",
			LOW = "Es braucht mehr Kraftstoff.",
			NORMAL = "Würde gute Eiswürfel machen!",
			OUT = "ER HAT FAST KEINEN TREIBSTOFF MEHR.",
			VERYLOW = "Fast aus!",
		},
		JUNGLETREE =
		{
			BURNING = "Wow! So viel Feuer.",
			BURNT = "Eine echte Verbesserung.",
			CHOPPED = "Loki hat ihn zu sich geholt.",
			GENERIC = "Das ist jede Menge Feuerholz!",
		},
		KNIGHTBOAT = "Schau dir dein Schiff an, Kumpel.",
		KRAKEN = "Töte es mit Feuer!",
		KRAKENCHEST = "Das ist irgendwie gar nicht so übel.",
		KRAKEN_TENTACLE = "Und bleib weg!",
		LIMPETROCK =
		{
			GENERIC = "Dieses Essen will den Felsen verspeisen.",
			PICKED = "Dem Fels macht das gar nichts aus.",
		},
		LIVINGJUNGLETREE = "Das Schwert hat irgendetwas fischartiges an sich.",
		LOBSTER_DEAD = "Das war nicht mehr essbar.",
		LOBSTER_DEAD_COOKED = "Hier lebt ein Hummergericht.",
		MAGIC_SEAL = "Hübsch und leuchtend.",
		MAGMAROCK = "Das Magma oder man mag es nicht.",
		MAGMAROCK_FULL = "Das Magma oder man mag es nicht.",
		MAGMAROCK_GOLD = "Das Magma oder man mag es nicht.",
		MAGMAROCK_GOLD_FULL = "Das Magma oder man mag es nicht.",
		MANGROVETREE = "Der muss nicht gegossen werden.",
		MANGROVETREE_BURNT = "Bis auf's Wasser verbrannt.",
		MARSH_PLANT_TROPICAL = "Pflanze.",
		MERMFISHER = "Bäh, den Fischgestank bekommt man wohl nicht mehr los.",
		MERMHOUSE_FISHER = "Fischhändler.",
		MONKEYBALL = "Ich wette, Affen wären ganz wild drauf.",
		MONSTERTARTARE = "Widerlich!",
		MOSQUITOSACK_YELLOW = "Das wurde von etwas Ekligem fallen gelassen.",
		MUSSELBOUILLABAISE = "Mmh. Riecht gut!",
		MYSTERYMEAT = "Ist ja widerlich!",
		NEEDLESPEAR = "Darüber könnte ich den ganzen Tag reden.",
		OCTOPUSCHEST = "Köstliche Fisch-Häppchen.",
		OCTOPUSKING = "Sieht irgendwie durchnässt aus.",
		OXHAT = "Horn von starkem Ochsen.",
		OX_FLUTE = "Ich höre einen von ihnen kommen.",
		OX_HORN = "Davon könnte ich noch einen gebrauchen.",
		PALMLEAF_HUT = "Hält die Elemente im Zaum, brennt aber schnell ab.",
		PARROT_PIRATE = "Das richtige Schiff für einen Tunichtgut.",
		PEG_LEG = "Wozu das gut ist, hab ich noch nicht raus.",
		PIGTENT = "Pfui, das riecht schrecklich.",
		PIKE_SKULL = "Pfui! Ekelhaft!",
		PIRATEGHOST = "Wer bist du denn?",
		PIRATEPACK = "Wer das mit sich herumträgt, bekommt wenigstens ein paar Muckis.",
		PORTAL_SHIPWRECKED = "Jetzt aber nichts wie weg.",
		PRIMEAPE = "He Kleiner, spielst du auch gerne mit Feuer?",
		PRIMEAPEBARREL = "Was für ein Affentheater.",
		RAWLING = "Vielleicht leisten mir diese Statuen Gesellschaft.",
		REDBARREL = "Das ist mein absolutes Lieblingsspielzeug.",
		ROCK_CHARCOAL = "It drops burned things!",
		ROCK_OBSIDIAN = "This rock makes me so excited, I just want to explode!",
		SAIL_STICK = "Turm schlägt Königin.",
		SANDBAGSMALL = "Damit die Feuer daheim nicht ausgehen.",
		SANDBAGSMALL_ITEM = "Damit die Feuer daheim nicht ausgehen.",
		SHADOWSKITTISH_WATER = "Was IST das?!",
		SHARKITTEN = "Wo ist denn deine Mutti?",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Es hebt die brennenden Materialien für mich auf.",
			INACTIVE = "Darum hab ich dich hierher gebracht.",
		},
		SHARK_GILLS = "Die braucht es bestimmt nicht mehr zum Atmen.",
		SHARK_TEETHHAT = "Das gibt mir ein breites Grinsen.",
		SHIPWRECKED_ENTRANCE = "So geht's...",
		SHIPWRECKED_EXIT = "Jetzt aber nichts wie weg.",
		SNAKEDEN =
		{
			BURNT = "Die brennen wunderbar!",
			CHOPPED = "So entwirrt man das.",
			GENERIC = "Ich wette, er knistert und knallt, wenn er brennt.",
		},
		SNAKESKINSAIL = "Fahre zu",
		SPEAR_LAUNCHER = "Besser als ein Speer ist nur die Schleuder, um ihn abzuschießen.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Wo führt das hin?",
			GENERIC = "Zur Wasserabwehr.",
		},
		SUNKEN_BOAT_BURNT = "Doppelt gut!",
		SUNKEN_BOAT_TRINKET_1 = "Das kann ich nicht aussprechen.",
		SUNKEN_BOAT_TRINKET_2 = "Ich habe kindische Sachen weggeräumt.",
		SUNKEN_BOAT_TRINKET_3 = "Spinne, spüre meinen Speer!",
		SUNKEN_BOAT_TRINKET_4 = "Das war keine gute Idee!",
		SUNKEN_BOAT_TRINKET_5 = "Nicht meine Größe.",
		SWEETPOTATOSOUFFLE = "Perfekt gekocht!",
		SWEET_POTATO = "Mal was anderes als immer nur rote Beeren.",
		SWEET_POTATO_COOKED = "Die Hitze hat sie auf jeden Fall besser gemacht.",
		SWEET_POTATO_PLANTED = "Mit Feuer wäre sie besser.",
		SWEET_POTATO_SEEDS = "Süßkartoffelsamen",
		SWIMMINGHORROR = "Ich hoffe, du kannst nicht schwimmen.",
		TELEPORTATO_SW_BASE = "Scheint, als ob ein oder zwei Teile fehlen.",
		TELEPORTATO_SW_BOX = "Ein Teil für etwas.",
		TELEPORTATO_SW_CRANK = "Zum Kurbeln?",
		TELEPORTATO_SW_POTATO = "Ich frage mich, was das ist.",
		TELEPORTATO_SW_RING = "Das gehört zu etwas anderem, glaube ich.",
		THATCHPACK = "Reet kein Unsinn.",
		TIDALPOOL = "In welche Richtung sich das Wasser beim Spülen wohl dreht?",
		TIDAL_PLANT = "Es ist eine Pflanze.",
		TIGEREYE = "Ich mag nicht, wie er mich anschaut!",
		TRAWLNETDROPPED =
		{
			GENERIC = "Was war das?!",
			SOON = "Das Zeug sinkt bald.",
			SOONISH = "Ich glaube, das Boot sinkt.",
		},
		TREASURECHEST_TRAP = "Fauler Trick.",
		TRINKET_20 = "Das kann ich nicht aussprechen.",
		TRINKET_21 = "Ich habe kindische Sachen weggeräumt.",
		TRINKET_22 = "Spinne, spüre meinen Speer!",
		TRINKET_23 = "Was ist kaputt!",
		TROPICAL_FISH = "Hübsche Farben.",
		TUNACAN = "Oh, aber ich mag's lieber mit Ballphin!",
		TURF_ASH = "Aschig.",
		TURF_MAGMAFIELD = "Samen für mein explosives Lieblingsgemüse.",
		TURF_MEADOW = "Herrlich.",
		TURF_SNAKESKINFLOOR = "Widerlich.",
		TURF_TIDALMARSH = "Zertreten.",
		TURF_VOLCANO = "Eine heiße Sohle.",
		TWISTER_SEAL = "Ich hab mir schön öfter die Finger verbrannt.",
		VOLCANO_ALTAR_TOWER = "Ein Feuerdenkmal!",
		VOLCANO_SHRUB = "You come pre-burnt!",
		WALLYINTRO_DEBRIS = "Hab ich das gemacht?",
		WATERYGRAVE = "Das Schwert hat irgendetwas fischartiges an sich.",
		WHALE_TRACK = "Es brennt! Doch wo ist das Feuer?",
		WILBUR_CROWN = "Die passt nur auf einen winzigen Kopf.",
		WILBUR_UNLOCK = "Schick!",
		WILDBORE = "Zu dem hätte ich gerne ein bisschen mehr Abstand.",
		WILDBOREHEAD = "Igitt!",
		WILDBOREHOUSE = "Bisschen Feuer und es kann gegrillt werden...",
		WIND_CONCH = "Hoffe, dass kein Feuer ausgeblasen wird.",
		WOODLEGSBOAT = "Ein herrliches Schiff.",
		WOODLEGSHAT = "Ich glaube nicht, dass das so richtig ist.",
		WOODLEGSSAIL = "Das Segel liegt bestimmt jemand am Herzen.",
		WOODLEGS_KEY1 = "Ein Schlüssel für was?",
		WOODLEGS_KEY2 = "Irgendetwas muss irgendwo verschlossen sein.",
		WOODLEGS_KEY3 = "Noch ein Schlüssel.",
		WRECK = "Jemand hat sein Gepäck verloren.",
		CALIFORNIAROLL = "Prima. Fisch in Seetang.",
		BANANAPOP = "Das ist das Gegenstück zum Feuer.",
		BISQUE = "Ich glaube, das könnte ich abholzen.",
		CEVICHE = "Immernoch schleimig...",
		SEAFOODGUMBO = "Igitt. Einfach nur IGITT!",
		SURFNTURF = "Bäh. Das ist Essen für alte Leute!",
		SHARKFINSOUP = "Es ist nicht einmal wie eine echte Karotte verbrannt.",
		LOBSTERDINNER = "Lecker!!",
		LOBSTERBISQUE = "Ich ess doch nicht Aales...",
		JELLYOPOP = "Ich will zwanzig.",
		VOLCANO_SHRUB = "Das ist nicht richtig! Ich bin nicht gekommen, um dich zu verbrennen!",
		ROCK_OBSIDIAN = "Der... hübscheste... Stein... den ich jemals... gesehen habe.",
		ROCK_CHARCOAL = "Kohleartig!",
	},
	DESCRIBE_TOODARK = "Ich benötige mehr Licht!",
	DESCRIBE_GENERIC = "Das will doch verbrannt werden.",
	DESCRIBE_SMOLDERING = "Hurra, es fängt fast an zu brennen.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Ächz!",
	},
}