return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Non ho intenzione di provarci mentre è sveglio.",
			GENERIC = "Non lo posso radere!",
			NOBITS = "Non c'è nemmeno una stabbia rimasta!",
		},
		STORE =
		{
			GENERIC = "È piena.",
			NOTALLOWED = "Non ci può entrare.",
		},
		RUMMAGE =
		{	
			GENERIC = "Non posso.",	
		},
        COOK =
        {
            GENERIC = "Oh, non posso.",
            TOOFAR = "È troppo lontano!",
        },
        GIVE =
        {
            DEAD = "Forse lo conserverò.",
            SLEEPING = "Troppo incosciente per preoccuparsene.",
            BUSY = "Ci proverò di nuovo fra un secondo.",
        },
        WRITE =
        {
            GENERIC = "Mi sembra buono così com'è.",
        },
        CHANGEIN =
        {
            GENERIC = "Non voglio cambiare adesso.",
            BURNING = "È troppo pericoloso adesso!",
        },
		REPAIRBOAT = 
		{
			GENERIC = "Adesso galleggia perfettamente.",
		},
		TEACH =
        {
            KNOWN = "Già lo conosco.",
            CANTLEARN = "Non posso impararlo.",
        },
	},
	ACTIONFAIL_GENERIC = "Non posso farlo.",
	ANNOUNCE_MAGIC_FAIL = "Non funzionerà qua.",
	
	ANNOUNCE_ADVENTUREFAIL = "Non è andata bene. Dovrò riprovare.",
	ANNOUNCE_BEES = "AAAAAAAAAAPI!!!",
	ANNOUNCE_BOOMERANG = "Ahi! Dovrei provare a prenderlo!",
	ANNOUNCE_CHARLIE = "Cos’era quello?",
	ANNOUNCE_CHARLIE_ATTACK = "AHI! Qualcosa mi ha morso!",
	ANNOUNCE_COLD = "Così freddo!",
	ANNOUNCE_HOT = "Serve... ghiaccio... o... ombra!",
	ANNOUNCE_CRAFTING_FAIL = "Mi mancano un paio di elementi fondamentali.",
	ANNOUNCE_DEERCLOPS = "Sembrava una cosa grande!",
	ANNOUNCE_DUSK = "Si sta facendo tardi. Presto sarà buio.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Gnam!",
		PAINFUL = "Non mi sento molto bene.",
		SPOILED = "Puah! È stato terribile!",
		STALE = "Credo che stesse iniziando a girare.",
		INVALID = "Non lo posso mangiare!",
		YUCKY = "Metterlo in bocca sarebbe disgustoso!",
	},
	ANNOUNCE_ENTER_DARK = "È così buio!",
	ANNOUNCE_ENTER_LIGHT = "Posso vedere di nuovo!",
	ANNOUNCE_FREEDOM = "Sono libero! Sono finalmente libero!",
	ANNOUNCE_HIGHRESEARCH = "Mi sento così intelligente ora!",
	ANNOUNCE_HOUNDS = "L'hai sentito?",
	ANNOUNCE_WORMS = "L'hai sentito?",
	ANNOUNCE_SHARX = "Avrò bisogno di una barca più grande...",
	ANNOUNCE_HUNGRY = "Ho una fame!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Questa pista è fresca. La bestia deve essere nelle vicinanze.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Le tracce della bestia terminano qui.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Questo terreno bagnato non reggerà un'impronta.",
	ANNOUNCE_INV_FULL = "Non posso trasportare nient'altro!",
	ANNOUNCE_KNOCKEDOUT = "Ah, la mia testa!",
	ANNOUNCE_LOWRESEARCH = "Non ho imparato molto da quello.",
	ANNOUNCE_MOSQUITOS = "Aaah! Sparisci!",
	ANNOUNCE_NOWARDROBEONFIRE = "Non posso cambiarmi mentre è in fiamme!",
	ANNOUNCE_NODANGERSLEEP = "È troppo pericoloso adesso!",
	ANNOUNCE_NODAYSLEEP = "È troppo luminoso fuori.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Non sono stanco.",
	ANNOUNCE_NOHUNGERSLEEP = "Ho troppa fame per dormire, il gorgoglio mi terrà sveglio!",
	ANNOUNCE_NOSLEEPONFIRE = "Non ho un ardente desiderio di dormire in quello.",
	ANNOUNCE_NODANGERSIESTA = "È troppo pericoloso fare la siesta adesso!",
	ANNOUNCE_NONIGHTSIESTA = "La notte non è fatta per dormire o riposarsi.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Non credo che potrei veramente rilassarmi qua sotto.",
	ANNOUNCE_NOHUNGERSIESTA = "Ho troppa fame per una pausa!",
	ANNOUNCE_NO_TRAP = "Beh, è stato facile.",
	ANNOUNCE_PECKED = "Ahi! Smettila!",
	ANNOUNCE_QUAKE = "Non sembra una buona idea.",
	ANNOUNCE_RESEARCH = "Mai smettere di imparare!",
	ANNOUNCE_SHELTER = "Grazie per la protezione dalle intemperie, albero!",
	ANNOUNCE_THORNS = "Ahi!",
	ANNOUNCE_BURNT = "Ahia! Era bollente!",
	ANNOUNCE_TORCH_OUT = "La mia luce si è appena scaricata!",
	ANNOUNCE_FAN_OUT = "Il mio ventilatore è andato via con il vento.",
    ANNOUNCE_COMPASS_OUT = "Questa bussola non punta più.",
	ANNOUNCE_TRAP_WENT_OFF = "Ops.",
	ANNOUNCE_UNIMPLEMENTED = "AHI! Non credo sia ancora pronto.",
	ANNOUNCE_WORMHOLE = "Non è stata una cosa sensata da fare.",
	ANNOUNCE_CANFIX = "\nCredo di poter sistemare questa faccenda!",
	ANNOUNCE_ACCOMPLISHMENT = "Mi sento così realizzato!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Se solo i miei amici mi vedessero adesso...",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Sei ancora affamata, pianta?",
	ANNOUNCE_TOOL_SLIP = "Uau, quello strumento è scivoloso!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Al sicuro da quel fulmine spaventoso!",

	ANNOUNCE_DAMP = "Oh, H2O.",
	ANNOUNCE_WET = "I miei vestiti sembrano essere permeabili all'acqua.",
	ANNOUNCE_WETTER = "Passaggio acquatico!",
	ANNOUNCE_SOAKED = "Ho quasi raggiunto il mio punto di saturazione.",

	ANNOUNCE_TREASURE = "È una mappa! E segna una posizione!",
	ANNOUNCE_MORETREASURE = "Sul serio? Un altro!?",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Questa mappa non combacia con l'ambiente in cui mi trovo adesso.",
	ANNOUNCE_OTHER_WORLD_PLANT = "Non credo che questa terra abbia le sostanze nutrienti adeguate.",

	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Il messaggio è sbiadito. Non riesco a leggerlo.",
	},
	ANNOUNCE_VOLCANO_ERUPT = "Non può essere buono.",
	ANNOUNCE_MAPWRAP_WARN = "Ci saranno dei mostri.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Il mio futuro è annebbiato.",
	ANNOUNCE_MAPWRAP_RETURN = "Credo di aver sentito un qualcosa sfiorare la mia gamba...",
	ANNOUNCE_CRAB_ESCAPE = "Avrei giurato che fosse proprio lì...",
	ANNOUNCE_TRAWL_FULL = "La mia rete si è riempita!",
	ANNOUNCE_BOAT_DAMAGED = "Penso di aver provocato una falla.",
	ANNOUNCE_BOAT_SINKING = "Mi sembra di affondare.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Ho bisogno di terra ferma!",
	ANNOUNCE_WAVE_BOOST = "Ueeeeee!",

	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Segui quelle bolle!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Mi chiedo dove sia andato...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Il mare è troppo agitato!",


	BATTLECRY =
	{
		GENERIC = "Punta agli occhi!",
		PIG = "Vieni qua maialino!",
		PREY = "Ti distruggerò!",
		SPIDER = "Ti schiaccerò fino alla morte!",
		SPIDER_WARRIOR = "Meglio tu che io!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Gli ho fatto vedere!",
		PIG = "Lo lascerò andare. Per questa volta.",
		PREY = "È troppo veloce!",
		SPIDER = "È troppo schifoso, comunque.",
		SPIDER_WARRIOR = "Sciò, brutta cosa!",
	},

	DESCRIBE =
	{
        WILDBOREGUARD = "Cosa sta sorvegliando?",
        GLOMMER = "È tenero, in una maniera rozza.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "I petali riflettono alla luce.",
        	DEAD = "I petali dondolano e luccicano nella luce.",
        },
        GLOMMERWINGS = "Questi avrebbero un aspetto meraviglioso con un casco!",
        GLOMMERFUEL = "Questa sostanza viscida odora di marcio.",
        BELL = "Scampanellio.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Non sono sicuro di cosa dovrebbe essere.",
        	EMPTY = "L'ho rotto. Per la scienza.",
    	},

		LAVA_POND_ROCK = "Un posto roccioso come tanti.",
		LAVA_POND_ROCK2 = "Un posto roccioso come tanti.",
		LAVA_POND_ROCK3 = "Un posto roccioso come tanti.",
		LAVA_POND_ROCK4 = "Un posto roccioso come tanti.",
		LAVA_POND_ROCK5 = "Un posto roccioso come tanti.",
		LAVA_POND_ROCK6 = "Un posto roccioso come tanti.",
		LAVA_POND_ROCK7 = "Un posto roccioso come tanti.",

		WEBBERSKULL = "Poverino. Merita un funerale decoroso.",
		WORMLIGHT = "Sembra delizioso.",
		WORMLIGHT_LESSER = "Piuttosto rugoso.",
		WORM =
		{
		    PLANT = "Mi sembra sicuro.",
		    DIRT = "Sembra solo un mucchio di terriccio.",
		    WORM = "È un verme!",
		},
		WORMLIGHT_PLANT = "Mi sembra sicuro.",
		MOLE =
		{
			HELD = "Non c'è rimasto più niente da scavare, amico mio.",
			UNDERGROUND = "C'è qualcosa là sotto, alla ricerca di minerali.",
			ABOVEGROUND = "Mi piacerebbe senz'altro colpire quella cosa... talpa.",
		},
		MOLEHILL = "Che bella ed accogliente buca nel terreno!",
		MOLEHAT = "Un pessimo fetore, ma la visibilità è eccellente.",

		EEL = "Questo sarà un pasto delizioso.",
		EEL_COOKED = "Ha un ottimo odore!",
		UNAGI = "Spero che non mi faccia sentire male!",
		EYETURRET = "Spero non si giri verso di me.",
		EYETURRET_ITEM = "Credo che stia dormendo.",
		MINOTAURHORN = "Uau! Sono contento che non mi abbia incornato!",
		MINOTAURCHEST = "Potrebbe contenere qualcosa di fantastico! O orribile.",
		THULECITE_PIECES = "Sono piccoli pezzi di tulecite.",
		POND_ALGAE = "Alcune alghe intorno a uno stagno.",
		GREENSTAFF = "Questo tornerà utile.",
		POTTEDFERN = "Una felce in un vaso.",

		THULECITE = "Mi chiedo da dove provenga.",
		ARMORRUINS = "È stranamente leggero.",
		RUINS_BAT = "Ha un certo peso.",
		RUINSHAT = "Come stanno i miei capelli?",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Va tutto bene.",
			WARN = "Si sta facendo magico da queste parti.",
			WAXING = "Credo stia diventando sempre più concentrato.",
			STEADY = "Sembra stia immobile.",
			WANING = "Sembra come se stesse indietreggiando.",
			DAWN = "L'incubo è quasi finito!",
			NOMAGIC = "Non c'è nessuna magia qui intorno.",
		},
		BISHOP_NIGHTMARE = "Sta cadendo a pezzi!",
		ROOK_NIGHTMARE = "Terrificante!",
		KNIGHT_NIGHTMARE = "È un incubo-cavaliere!",
		MINOTAUR = "Quella cosa non sembra felice.",
		SPIDER_DROPPER = "Nota a sé: non guardare in alto.",
		NIGHTMARELIGHT = "Mi chiedo quale funzionalità abbia.",
		NIGHTSTICK = "È elettrico!",
		GREENGEM = "È verde e come una gemma.",
		RELIC = "Ancient household goods.",
		RUINS_RUBBLE = "This can be fixed.",
		MULTITOOL_AXE_PICKAXE = "È fantastico!",
		ORANGESTAFF = "Questo è meglio che camminare.",
		YELLOWAMULET = "Caldo al tatto.",
		GREENAMULET = "Proprio quando pensavo che non potesse andare meglio.",
		SLURPERPELT = "Non sembra molto diverso da morto.",		

		SLURPER = "È così peloso!",
		SLURPER_PELT = "Non sembra molto diverso da morto.",	
		ARMORSLURPER = "Un completo inzuppato, sostenuto e succulento.",
		ORANGEAMULET = "Il teletrasporto può essere davvero utile.",
		YELLOWSTAFF = "Ho messo una gemma su una bacchetta.",
		YELLOWGEM = "La gemma è gialla.",
		ORANGEGEM = "È una gemma arancione.",
		TELEBASE = 
		{
			VALID = "It's ready to go.",
			GEMS = "It needs more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks ready.",
			GEMS = "It needs a gem.",
		},
		STAFFLIGHT = "Sembra davvero pericoloso.",
	
        ANCIENT_ALTAR = "Una struttura antica e misteriosa.",

        ANCIENT_ALTAR_BROKEN = "Sembra essere rotto.",

        ANCIENT_STATUE = "Sembra stonare rispetto al mondo.",

        LICHEN = "Solo un cianobatterio potrebbe crescere con questa luce.",
		CUTLICHEN = "Nutriente, ma non durerà a lungo.",

		CAVE_BANANA = "È molle.",
		CAVE_BANANA_COOKED = "Gnam!",
		CAVE_BANANA_TREE = "È dubbiosamente fotosintetico.",
		ROCKY = "Ha degli artigli terrificanti.",
		
		COMPASS =
		{
			GENERIC="In che direzione sto guardando?",
			N = "Nord.",
			S = "Sud.",
			E = "Est.",
			W = "Ovest.",
			NE = "Nord-est.",
			SE = "Sud-est.",
			NW = "Nord-ovest.",
			SW = "Sud-ovest.",
		},

		HOUNDSTOOTH="È affilato!",
		ARMORSNURTLESHELL="Si attacca alla mia schiena.",
		BAT="Argh! È terrificante!",
		BATBAT = "I bet I could fly if I held two of them.",
		BATWING="Odio quelle cose, anche se sono morte.",
		BATWING_COOKED="Almeno non tornerà indietro.",
		BATCAVE = "Non voglio svegliarli.",
		BEDROLL_FURRY="È così caldo e confortevole.",
		BUNNYMAN="Ho tanta voglia irrefrenabile di fare scienza.",
		FLOWER_CAVE="La scienza lo fa risplendere.",
		FLOWER_CAVE_DOUBLE="La scienza lo fa risplendere.",
		FLOWER_CAVE_TRIPLE="La scienza lo fa risplendere.",
		GUANO= "Un altro sapore di cacca.",
		LANTERN= "Una luce più civile.",
		LIGHTBULB= "Sembra stranamente gustoso.",
		MANRABBIT_TAIL= "Mi piace tenerlo.",
		MUSHTREE_TALL  = "That mushroom got too big for its own good.",
		MUSHTREE_MEDIUM= "These used to grow in my bathroom.",
		MUSHTREE_SMALL = "A magic mushroom?",
		MUSHTREE_TALL =
		{
            GENERIC = "Quel fungo è diventato troppo grande.",
            BLOOM = "Non si sente in lontananza, ma è piuttosto puzzolente.",
        },
		MUSHTREE_MEDIUM = 
		{
            GENERIC = "Crescevano nel mio bagno.",
            BLOOM = "Sono leggermente offeso da questo.",
        },
		MUSHTREE_SMALL = 
		{
            GENERIC = "Un fungo allucinogeno?",
            BLOOM = "Sta tentando di riprodursi.",
        },
        MUSHTREE_TALL_WEBBED = "I ragni lo hanno ritenuto importante.",
        SPORE_TALL = "Sta solo andando alla deriva qua e là.",
        SPORE_MEDIUM = "Sta solo andando alla deriva qua e là.",
        SPORE_SMALL = "Sta solo andando alla deriva qua e là.",
        SPORE_TALL_INV = "Terrò un po' di luce in tasca.",
        SPORE_MEDIUM_INV = "Terrò un po' di luce in tasca.",
        SPORE_SMALL_INV = "Terrò un po' di luce in tasca.",
		RABBITHOUSE=
		{
			GENERIC = "Non è una vera carota.",
			BURNT = "Non è una vera carota arrostita.",
		},
		SLURTLE="Bleah. Solo bleah.",
		SLURTLE_SHELLPIECES="Un rompicapo senza soluzione.",
		SLURTLEHAT= "Spero che non mi scompigli i capelli.",
		SLURTLEHOLE= "Un covo di \"bleah\".",
		SLURTLESLIME= "Se non fosse utile, non lo toccherei.",
		SNURTLE= "È meno rozzo, ma pur sempre rozzo.",
		SPIDER_HIDER= "Ah! Altri ragni!",
		SPIDER_SPITTER= "Odio i ragni!",
		SPIDERHOLE= "È incrostato con la vecchia tessitura.",
		SPIDERHOLE_ROCK = "È incrostato con la vecchia tessitura.",
		STALAGMITE= "Mi sembra una roccia.",
		STALAGMITE_FULL= "Mi sembra una roccia.",
		STALAGMITE_LOW= "Mi sembra una roccia.",
		STALAGMITE_MED= "Mi sembra una roccia.",
		STALAGMITE_TALL= "Pietre, pietre, pietre, pietre...",
		STALAGMITE_TALL_FULL= "Pietre, pietre, pietre, pietre...",
		STALAGMITE_TALL_LOW= "Pietre, pietre, pietre, pietre...",
		STALAGMITE_TALL_MED= "Pietre, pietre, pietre, pietre...",

		TURF_CARPETFLOOR = "È sorprendentemente ruvido.",
        TURF_CHECKERFLOOR = "Questi sono piuttosto sgargianti.",
		TURF_DIRT = "A chunk of ground.",
		TURF_FOREST = "A chunk of ground.",
		TURF_GRASS = "A chunk of ground.",
		TURF_MARSH = "A chunk of ground.",
		TURF_ROAD = "Hastily cobbled stones.",
		TURF_ROCKY = "A chunk of ground.",
		TURF_SAVANNA = "A chunk of ground.",
		TURF_WOODFLOOR = "Queste sono tavole per pavimenti.",

		TURF_CAVE="Ancora un altro tipo di terreno.",
		TURF_FUNGUS="Ancora un altro tipo di terreno.",
		TURF_SINKHOLE="Ancora un altro tipo di terreno.",
		TURF_UNDERROCK="Ancora un altro tipo di terreno.",
		TURF_MUD="Ancora un altro tipo di terreno.",

		TURF_DECIDUOUS = "Ancora un altro tipo di terreno.",
		TURF_SANDY = "Ancora un altro tipo di terreno.",
		TURF_BADLANDS = "Ancora un altro tipo di terreno.",
		TURF_DESERTDIRT = "A chunk of ground.",
		TURF_FUNGUS_GREEN = "A chunk of ground.",
		TURF_FUNGUS_RED = "A chunk of ground.",
		TURF_DRAGONFLY = "Vuoi la prova che è a prova di fuoco?",

		POWCAKE = "Non so se ho abbastanza fame.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Mi chiedo se posso spostare quella roccia.",
            OPEN = "Scommetto che ci sono un sacco di cose da scoprire laggiù.",
        },
        CAVE_EXIT = "I've had enough discovery for now.",
        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "La terra stessa mi respinge!",
            OPEN = "Scommetto che ci sono un sacco di cose da scoprire laggiù.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Me ne starò qui sotto, suppongo.",
            OPEN = "Ho fatto abbastanza scoperte per ora.",
        },
		MAXWELLPHONOGRAPH = "Ecco da dove proveniva la musica.",
		BOOMERANG = "Aerodinamico!",
		PIGGUARD = "Non sembra così amichevole come gli altri.",
		ADVENTURE_PORTAL = "Non sono sicuro di volerci cadere per la seconda volta.",
		AMULET = "Mi sento così sicuro quando lo indosso.",
		ANIMAL_TRACK = "Tracce lasciate dal cibo. Voglio dire... da un animale.",
		ARMORGRASS = "Spero che non ci siano insetti in questo.",
		ARMORMARBLE = "Questo sembra davvero pesante.",
		ARMORWOOD = "Questo è un pezzo perfettamente ragionevole di abbigliamento.",
		ARMOR_SANITY = "Con questo addosso mi sento al sicuro ma insicuro.",
		ASH =
		{
			GENERIC = "Tutto quello che resta dopo che l'incendio ha fatto il suo dovere.",
			REMAINS_GLOMMERFLOWER = "Il fiore è stato consumato dal fuoco nel teletrasporto!",
			REMAINS_EYE_BONE = "L'ossocchio è stato consumato dal fuoco nel teletrasporto!",
			REMAINS_THINGIE = "C'è una spiegazione perfettamente scientifica per questo.",
		},
		AXE = "È la mia fidata ascia.",
		BABYBEEFALO = "Oh. Carinissimo!",
		BACKPACK = "Ci si potrebbe far entrare un sacco di scienza.",
		BACONEGGS = "La colazione perfetta per un uomo di scienza.",
		BANDAGE = "Sembra abbastanza sterile.",
		BASALT = "È troppo forte da sfondare!",
		BATBAT = "Scommetto che riuscirei a volare con due di questi.",
		BEARDHAIR = "Li ho fatti con la mia faccia.",
		BEARGER = "Che orso di un tasso.",
		BEARGERVEST = "Benvenuto nella stazione dell'ibernazione!",
		ICEPACK = "La pelliccia mantiene la temperatura interna stabile.",
		BEARGER_FUR = "Una stuoia di folta pelliccia.",
		BEDROLL_STRAW = "Sembra comodo, ma odora di muffa.",
		BEE =
		{
			GENERIC = "Ape o non ape.",
			HELD = "Attento!",
		},
		BEEBOX =
		{
			FULLHONEY = "È piena di miele.",
			GENERIC = "Api!",
			NOHONEY = "È vuota.",
			SOMEHONEY = "Dovrei aspettare un po'.",
			BURNT = "Come si è bruciata?!",
		},
		BEEFALO =
		{
			FOLLOWER = "Sta venendo in pace.",
			GENERIC = "È un mufalo!",
			NAKED = "Oh, è così triste.",
			SLEEPING = "Questi tipi dormono davvero pesantemente.",
		},
		BEEFALOHAT = "Ecco una situazione di cappello-capelli in attesa di accadere.",
		BEEFALOWOOL = "C'è odore di lacrime di mufalo.",
		BEEHAT = "Protegge la tua pelle, ma ti schiaccia la pettinatura.",
		BEEHIVE = "È brulicante di attività.",
		BEEMINE = "Suona quando lo scuoto.",
		BEEMINE_MAXWELL = "Rabbia di zanzara imbottigliata!",
		BERRIES = "Le bacche rosse sono le più buone.",
		BERRIES_COOKED = "Non credo che il calore li abbia migliorati.",
		BERRYBUSH =
		{
			BARREN = "Credo che debba essere fertilizzato.",
			WITHERED = "Niente ricrescerà con questo calore.",
			GENERIC = "Le bacche rosse sono le più buone.",
			PICKED = "Forse ricrescerà?",
		},
		BIGFOOT = "Questo è un biiigfoot.",
		BIRDCAGE =
		{
			GENERIC = "Dovrei metterci un pennuto.",
			OCCUPIED = "È il mio pennuto!",
			SLEEPING = "Oh, sta dormendo.",
			HUNGRY = "Sembra un po' affamato.",
			STARVING = "Non ti ho dato da mangiare da un po'?",
			DEAD = "Forse sta solo riposando?",
			SKELETON = "Quell'uccello è sicuramente morto.",
		},
		BIRDTRAP = "Mi dà un netto vantaggio!",
		CAVE_BANANA_BURNT = "Non è colpa mia!",
		BIRD_EGG = "Un piccolo uovo ordinario.",
		BIRD_EGG_COOKED = "Uovo fritto gnam!",
		BISHOP = "Indietro, predicatore!",
		BLOWDART_FIRE = "Questo sembra fondamentalmente non sicuro.",
		BLOWDART_SLEEP = "Basta non respirare.",
		BLOWDART_PIPE = "È un buon allenamento per la mia torta di compleanno!",
		BLUEAMULET = "Freddo come il ghiaccio!",
		BLUEGEM = "Luccica di energia fredda.",
		BLUEPRINT = "È scientifico!",
		BELL_BLUEPRINT = "È scientifico!",
		BLUE_CAP = "È strano e appiccicoso.",
		BLUE_CAP_COOKED = "Ora è diverso...",
		BLUE_MUSHROOM =
		{
			GENERIC = "È un fungo.",
			INGROUND = "Sta dormendo.",
			PICKED = "Mi chiedo se tornerà?",
		},
		BOARDS = "Tavole.",
		BOAT = "È così che sono arrivato qua?",
		BONESHARD = "Frammenti di osso.",
		BONESTEW = "Uno stufato di mettere carne sulle mie ossa.",
		BUGNET = "Per la cattura degli insetti.",
		BUSHHAT = "È piuttosto cespuglioso.",
		BUTTER = "Non posso credere che sia burro!",
		BUTTERFLY =
		{
			GENERIC = "Farfalla svolazzante.",
			HELD = "Ora ti ho presa!",
		},
		BUTTERFLYMUFFIN = "Ho buttato via la ricetta e ho improvvisato.",
		BUTTERFLYWINGS = "Senza questi, è solo un burro.",
		BUZZARD = "Che strana poiana!",
		CACTUS = 
		{
			GENERIC = "Tagliente ma delizioso.",
			PICKED = "Sgonfio, ma ancora coperto di spine.",
		},
		CACTUS_MEAT_COOKED = "Frutta del deserto alla griglia.",
		CACTUS_MEAT = "Ci sono ancora delle spine tra me e un pasto gustoso.",
		CACTUS_FLOWER = "Un fiore carino da una pianta spinosa.",

		COLDFIRE =
		{
			EMBERS = "Dovrei mettere qualcosa sul fuoco prima che sia troppo tardi.",
			GENERIC = "Sicuramente batte l'oscurità.",
			HIGH = "Quel fuoco sta sfuggendo di mano!",
			LOW = "Il fuoco si sta affievolendo.",
			NORMAL = "Bello e piacevole.",
			OUT = "Bene, è finita.",
		},
		CAMPFIRE =
		{
			EMBERS = "Dovrei mettere qualcosa sul fuoco prima che sia troppo tardi.",
			GENERIC = "Sicuramente batte l'oscurità.",
			HIGH = "Quel fuoco sta sfuggendo di mano!",
			LOW = "Il fuoco si sta affievolendo.",
			NORMAL = "Bello e piacevole.",
			OUT = "Beh, è spento.",
		},
		CANE = "Fa sembrare il camminare molto facile.",
		CATCOON = "Una cosetta giocherellona.",
		CATCOONDEN = 
		{
			GENERIC = "È una tana dentro un ceppo.",
			EMPTY = "Il suo proprietario ha esaurito le vite.",
		},
		CATCOONHAT = "Cappello con le orecchie!",
		COONTAIL = "Credo che stia ancora frusciando.",
		CARROT = "Che schifo. Ho tirato questo ortaggio dal terriccio.",
		CARROT_COOKED = "Pastoso.",
		CARROT_PLANTED = "La terra sta producendo pianticelle.",
		CARROT_SEEDS = "È un seme di carota.",
		WATERMELON_SEEDS = "È un seme di melone.",
		CAVE_FERN = "È una felce.",
		CHARCOAL = "È piccolo, scuro e profuma di legno bruciato.",
        CHESSJUNK1 = "Un mucchio di pezzi rotti degli scacchi.",
        CHESSJUNK2 = "Un altro mucchio di pezzi rotti degli scacchi.",
        CHESSJUNK3 = "Ancora altri pezzi rotti degli scacchi.",
		CHESTER = "Egregio sig. Otto von Chesterfield",
		CHESTER_EYEBONE =
		{
			GENERIC = "Mi sta guardando.",
			WAITING = "È andato a dormire.",
		},
		COOKEDMANDRAKE = "Povero piccoletto.",
		COOKEDMEAT = "Grigliato a puntino.",
		COOKEDMONSTERMEAT = "È solo un po' più appetitosa di quando era cruda.",
		COOKEDSMALLMEAT = "Adesso non devo preoccuparmi dei vermi!",
		COOKPOT =
		{
			COOKING_LONG = "Ci vorrà un po' di tempo.",
			COOKING_SHORT = "È quasi fatto!",
			DONE = "Mmmmm! È pronto da mangiare!",
			EMPTY = "Mi fa venir fame solo a guardarlo.",
			BURNT = "La pentola si è bruciata.",
		},
		CORN = "Ad alto contenuto di fruttosio!",
		CORN_COOKED = "Cucinato e ad alto contenuto di fruttosio!",
		CORN_SEEDS = "È un seme di mais.",
		CROW =
		{
			GENERIC = "Raccapricciante!",
			HELD = "Non è molto felice.",
		},
		CUTGRASS = "Taglia l'erba, pronto per arti e mestieri.",
		CUTREEDS = "Canne tagliate, pronte per l'artigianato e l'hobbistica.",
		CUTSTONE = "Li ho fatti seducenti e lisci.",
		DEADLYFEAST = "Il piatto più potente.",
		DEERCLOPS = "È enorme!!",
		DEERCLOPS_EYEBALL = "Questo è davvero una volgarità.",
		EYEBRELLAHAT =	"Veglierà su me.",
		DEPLETED_GRASS =
		{
			GENERIC = "È probabilmente un ciuffo d'erba.",
		},
		DEVTOOL = "Odora di pancetta!",
		DEVTOOL_NODEV = "Non sono abbastanza forte per impugnarla.",
		DIRTPILE = "È un mucchio di terriccio... VERO?",
		DIVININGROD =
		{
			COLD = "Il segnale è molto debole.",
			GENERIC = "È un qualche tipo di dispositivo a inseguimento.",
			HOT = "Questa cosa sta impazzendo!",
			WARM = "Sto andando nella direzione giusta.",
			WARMER = "Devo essere molto vicino.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Mi chiedo a cosa serva.",
			READY = "Sembra che abbia bisogno di una grossa chiave.",
			UNLOCKED = "Ora la mia macchina può funzionare!",
		},
		DIVININGRODSTART = "Quella bacchetta sembra utile!",
		DRAGONFLY = "Quella sì che è una libellula!",
		ARMORDRAGONFLY = "Maglio rovente!",
		DRAGON_SCALES = "Sono ancora calde.",
		DRAGONFLYCHEST = "La cosa migliore dopo una cassaforte!",
		LAVASPIT = 
		{
			HOT = "Sputo bollente!",
			COOL = "Mi piace chiamarlo \"basaliva\".",
		},
		LAVA_POND = "Magmagnifico!",
		LAVAE = "Troppo caldo da maneggiare!",
		LAVAE_PET = 
		{
			STARVING = "Il poveretto deve avere una fame da lupo.",
			HUNGRY = "Sento il brontolio di un piccolo stomaco.",
			CONTENT = "Sembra felice.",
			GENERIC = "Ah. Chi è un buon mostro?",
		},
		LAVAE_EGG = 
		{
			GENERIC = "C'è un debole calore proveniente dall'interno.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Non credo che quell'uovo sia abbastanza caldo.",
			COMFY = "Non ho mai pensato di vedere un uovo felice.",
		},
		LAVAE_TOOTH = "È un dente di uovo!",

		DRAGONFRUIT = "Che strano frutto.",
		DRAGONFRUIT_COOKED = "Il frutto è ancora strano.",
		DRAGONFRUIT_SEEDS = "È uno strano seme di frutta.",
		DRAGONPIE = "Il frutto del dragone è molto saziante.",
		DRUMSTICK = "Lo dovrei trangugitare.",
		DRUMSTICK_COOKED = "Ora è ancora più gustoso.",
		DUG_BERRYBUSH = "Ora può essere portato ovunque.",
		DUG_GRASS = "Ha bisogno di essere piantato.",
		DUG_MARSH_BUSH = "Dovrei piantarlo.",
		DUG_SAPLING = "Potrei ripiantarlo più vicino a casa.",
		DURIAN = "Oh, che odore!",
		DURIAN_COOKED = "Adesso odora anche peggio!",
		DURIAN_SEEDS = "È un seme di durian.",
		EARMUFFSHAT = "Almeno le mie orecchie non si raffredderanno.",
		EGGPLANT = "Non sembra un uovo.",
		EGGPLANT_COOKED = "È persino meno ovoso.",
		EGGPLANT_SEEDS = "È un seme di melanzana.",
		DECIDUOUSTREE = 
		{
			BURNING = "Che spreco di legna.",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			POISON = "Non sembra contento che stia rubando quelle nocetulle!",
			GENERIC = "È tutto un fogliame. La maggior parte del tempo.",
		},
		ACORN = 
		{
		    GENERIC = "C'è sicuramente qualcosa là dentro.",
		    PLANTED = "Sarà presto un albero!",
		},
		ACORN_COOKED = "Arrostito alla perfezione.",
		BIRCHNUTDRAKE = "Una piccola noce folle.",
		EVERGREEN =
		{
			BURNING = "Che spreco di legna.",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "È tutto pinoso.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Che spreco di legna.",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "Questo triste albero non ha pigne.",
		},
		EYEPLANT = "Credo di essere osservato.",
		FARMPLOT =
		{
			GENERIC = "Dovrei provare a piantare alcune colture.",
			GROWING = "Vai a piantare, vai!",
			NEEDSFERTILIZER = "Credo che debba essere fertilizzato.",
			BURNT = "Non credo che crescerà niente da un mucchio di cenere.",
		},
		FEATHERHAT = "SONO UN PENNUTO!",
		FEATHER_CROW = "Una piuma di corvo.",
		FEATHER_ROBIN = "Una piuma di cardinale rosso.",
		FEATHER_ROBIN_WINTER = "Una piuma dello zigolo delle nevi.",
		FEM_PUPPET = "È in trappola!",
		FIREFLIES =
		{
			GENERIC = "Se solo potessi prenderli!",
			HELD = "Fanno risplendere la mia tasca!",
		},
		FIREHOUND = "Quello è luminoso.",
		FIREPIT =
		{
			EMBERS = "Dovrei mettere qualcosa sul fuoco prima che sia troppo tardi.",
			GENERIC = "Sicuramente batte l'oscurità.",
			HIGH = "Buona cosa che è contenuto!",
			LOW = "Il fuoco si sta affievolendo.",
			NORMAL = "Bello e piacevole.",
			OUT = "Almeno lo posso riaccendere.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Dovrei mettere qualcosa sul fuoco prima che sia troppo tardi.",
			GENERIC = "Sicuramente batte l'oscurità.",
			HIGH = "Buona cosa che è contenuto!",
			LOW = "Il fuoco si sta affievolendo.",
			NORMAL = "Bello e piacevole.",
			OUT = "Almeno posso ricominciare.",
		},
		FIRESTAFF = "Non voglio incendiare il mondo.",
		FIRESUPPRESSOR = 
		{	
			ON = "Scaglia!",
			OFF = "Tutto è tranquillo sul fronte degli oggetti scagliati.",
			LOWFUEL = "Il serbatoio del carburante si sta svuotando.",
		},

		FISH = "Ora mangerò per un giorno.",
		FISHINGROD = "Amo, lenza e canna!",
		FISHSTICKS = "Si attacca alle costine.",
		FISH_MED = "Un buon pesce cane.",
		FISH_MED_COOKED = "Grigliato alla perfezione.",
		FISHTACOS = "Croccante e delizioso!",
		FISH_COOKED = "Grigliato alla perfezione.",
		FLINT = "È una roccia molto affilata.",
		FLOWER = "È carino, ma odora come un manovale.",
		FLOWERHAT = "Odora di beltà.",
		FLOWER_EVIL = "Augh! È così malvagio!",
		FOLIAGE = "Alcune verdure a foglia verde.",
		FOOTBALLHAT = "Non mi piace lo sport.",
		FROG =
		{
			DEAD = "Ha gracchiato.",
			GENERIC = "È così carino!",
			SLEEPING = "Oh, guardalo che dorme!",
		},
		FROGGLEBUNWICH = "Un panino in gamba.",
		FROGLEGS = "Ho sentito dire che siano una prelibatezza.",
		FROGLEGS_COOKED = "Sa di pollo.",
		FRUITMEDLEY = "Fruttoso.",
		FURTUFT = "Pelliccia bianca e nera.", 
		GEARS = "Un mucchio di parti meccaniche.",
		GHOST = "Questo mi offende come scienziato.",
		GOLDENAXE = "È un'ascia di lusso.",
		GOLDENPICKAXE = "Ehi, ma l'oro non è morbidissimo?",
		GOLDENPITCHFORK = "Perché mai ho fatto un forcone così piacevole?",
		GOLDENSHOVEL = "Non vedo l'ora di scavare buche.",
		GOLDNUGGET = "Non posso mangiarlo, ma è sicuramente splendente.",
		GRASS =
		{
			BARREN = "Ha bisogno di cacca.",
			WITHERED = "Non ricrescerà finché fa così caldo.",
			BURNING = "Sta bruciando in fretta!",
			GENERIC = "È un ciuffo d'erba.",
			PICKED = "È stato abbattuto nel fiore della sua vita.",
		},
		GREEN_CAP = "Sembra abbastanza normale.",
		GREEN_CAP_COOKED = "Ora è diverso...",
		GREEN_MUSHROOM =
		{
			GENERIC = "È un fungo.",
			INGROUND = "Sta dormendo.",
			PICKED = "Mi chiedo se tornerà?",
		},
		GUNPOWDER = "Sembra pepe.",
		HAMBAT = "Sembra antigienico.",
		HAMMER = "Stop! È ora! Di martellare cose!",
		HEALINGSALVE = "Questo pizzicore indica che sta funzionando.",
		HEATROCK =
		{
			FROZEN = "È più freddo del ghiaccio.",
			COLD = "È una pietra fredda.",
			GENERIC = "Potrei manipolare la sua temperatura.",
			WARM = "È abbastanza calda e coccolona... per essere una roccia!",
			HOT = "Bello e caldissimo!",
		},
		HOME = "Qualcuno deve vivere qui.",
		HOMESIGN = 
		{
			GENERIC = "Dice \"Sei qua\".",
			UNWRITTEN = "Il segnale è attualmente vuoto.",
			BURNT = "Non posso più leggerlo.",
		},
		HONEY = "Sembra delizioso!",
		HONEYCOMB = "Ci vivevano le api.",
		HONEYHAM = "Dolce e salato.",
		HONEYNUGGETS = "Sa di pollo, ma non credo che lo sia.",
		HORN = "Suona come un campo di mufalo lì dentro.",
		HOUND = "Non sei nessuno, cane segugio!",
		HOUNDBONE = "Raccapricciante.",
		HOUNDMOUND = "Non credo che il padrone sia un osso duro.",
		ICEBOX = "Ho sfruttato la potenza del freddo!",
		ICEHAT = "Stai fresco, ragazzo.",
		ICEHOUND = "Ci sono cani segugi per ogni stagione?",
		INSANITYROCK =
		{
			ACTIVE = "PRENDI QUESTO, EGO SENSATO!",
			INACTIVE = "È più una piramide che un obelisco.",
		},
		JAMMYPRESERVES = "Avrei dovuto fare un barattolo.",
		KABOBS = "Pranzo su un bastone.",
		KILLERBEE =
		{
			GENERIC = "Oh no! È un'ape assassina!",
			HELD = "Sembra pericoloso.",
		},
		KNIGHT = "Controlla!",
		KOALEFANT_SUMMER = "Adorabilmente delizioso.",
		KOALEFANT_WINTER = "Sembra caldo e pieno di carne.",
		KRAMPUS = "Sta inseguendo le mie cose!",
		KRAMPUS_SACK = "È ricoperto di melma di Krampus.",
		LEIF = "È enorme!",
		LEIF_SPARSE = "È enorme!",
		LIGHTNING_ROD =
		{
			CHARGED = "Il potere è mio!",
			GENERIC = "Posso sfruttare i cieli!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "\"Baaaah\" a te stesso!",
			CHARGED = "Non credo gli sia piaciuto essere stato colpito da un fulmine.",
		},
		LIGHTNINGGOATHORN = "È come un parafulmine in miniatura.",
		GOATMILK = "È brulicante di bontà!",
		LITTLE_WALRUS = "Non sarà tenero e coccolone per sempre.",
		LIVINGLOG = "Sembra preoccupato.",
		LOCKEDWES = "Le statue di Maxwell lo stanno intrappolando.",
		LOG =
		{
			BURNING = "È un legno caldo!",
			GENERIC = "È grande, è pesante ed è legno.",
		},
		LUREPLANT = "È così affascinante.",
		LUREPLANTBULB = "Adesso posso iniziare la mia fattoria di carne.",
		MALE_PUPPET = "È intrappolato!",
		MANDRAKE =
		{
			DEAD = "La radice di mandragola ha delle proprietà particolari.",
			GENERIC = "Ho sentito dire cose strane su queste piante.",
			PICKED = "Smettila di seguirmi!",
		},
		MANDRAKESOUP = "Beh, non si risveglierà di nuovo.",
		MANDRAKE_COOKED = "Non sembra più così strano.",
		MARBLE = "Carino!",
		MARBLEPILLAR = "Penso di poterla usare.",
		MARBLETREE = "Non credo che un'ascia potrà tagliarlo.",
		MARSH_BUSH =
		{
			BURNING = "Sta bruciando in fretta!",
			GENERIC = "Sembra spinoso.",
			PICKED = "Fa male.",
		},
		BURNT_MARSH_BUSH = "È tutto bruciato.",
		MARSH_PLANT = "È una pianta.",
		MARSH_TREE =
		{
			BURNING = "Punte e fuoco!",
			BURNT = "Ora è bruciato e appuntito.",
			CHOPPED = "Non è così appuntito ora!",
			GENERIC = "Quelle punte sembrano affilate!",
		},
		MAXWELL = "Odio quel tipo.",
		MAXWELLHEAD = "Posso vedere nei suoi pori.",
		MAXWELLLIGHT = "Mi chiedo come funzionano.",
		MAXWELLLOCK = "Sembra quasi un buco della serratura.",
		MAXWELLTHRONE = "Non sembra molto comodo.",
		MEAT = "È un po' selvatico, ma andrà bene.",
		MEATBALLS = "L'ho cucinato io!",
		MEATRACK =
		{
			DONE = "È l'ora della carne essiccata!",
			DRYING = "La carne impiega del tempo ad essiccarsi.",
			DRYINGINRAIN = "La carne impiega ancora più tempo a seccarsi con la pioggia.",
			GENERIC = "Dovrei essiccare della carne.",
			BURNT = "La griglia si è seccata.",
		},
		MEAT_DRIED = "Carne essiccata appena quanto basta.",
		MERM = "Puzza di pesce!",
		MERMHEAD = 
		{
			GENERIC = "La cosa più puzzolente che odorerò tutto il giorno.",
			BURNT = "La testa di mermo bruciata puzza ancora di più.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Chi vorrebbe vivere qui?",
			BURNT = "Niente in cui vivere, adesso.",
		},
		MINERHAT = "Per illuminare la mia giornata a mani libere.",
		MONKEY = "Tipetto curioso.",
		MONKEYBARREL = "Si è appena mosso?",
		MONSTERLASAGNA = "È un affronto alla scienza.",
		FLOWERSALAD = "Una ciotola di fogliame.",
        ICECREAM = "Voglio il gelato!",
        WATERMELONICLE = "Anguria criogenica.",
        TRAILMIX = "Uno spuntino sano e naturale.",
        HOTCHILI = "Allarme piccante!",
        GUACAMOLE = "Piatto preferito di Avogadro.",
		MONSTERMEAT = "Ugh. Non credo che dovrei mangiarlo.",
		MONSTERMEAT_DRIED = "Carne essiccata dall'odore strano.",
		MOOSE = "Non so cosa sia quella cosa esattamente.",
		MOOSE_NESTING_GROUND = "Ci mette i suoi cuccioli.",
		MOOSEEGG = "I suoi contenuti sono come elettroni eccitati che cercano di scappare.",
		MOSSLING = "Aaah! Tu non sei sicuramente un elettrone!",
		FEATHERFAN = "Giù, per abbassare la mia temperatura.",
		MINIFAN = "Stranamente la brezza esce da dietro al doppio della velocità.",
		TROPICALFAN = "Stranamente la brezza esce da dietro al doppio della velocità.",
		GOOSE_FEATHER = "Soffice!",
		STAFF_TORNADO = "Disgrazia rotante.",
		MOSQUITO =
		{
			GENERIC = "Disgustose piccole sanguisughe.",
			HELD = "Ehi, ma è il mio sangue?",
		},
		MOSQUITOSACK = "Probabilmente non è il sangue di qualcun altro...",
		MOUND =
		{
			DUG = "Probabilmente dovrei sentirmi male per questo.",
			GENERIC = "Scommetto che ci sia un sacco di roba buona laggiù!",
		},
		NIGHTLIGHT = "Emana una luce spettrale.",
		NIGHTMAREFUEL = "Questa roba è fuori di testa!",
		NIGHTSWORD = "L'ho sognato io!",
		NITRE = "Non sono un geologo.",
		ONEMANBAND = "Avrei dovuto aggiungere una campanella di mufalo.",
		PANDORASCHEST = "Potrebbe contenere qualcosa di fantastico! O orribile.",
		PANFLUTE = "Posso suonare la serenata agli animali.",
		PAPYRUS = "Alcuni fogli di carta.",
		PENGUIN = "Deve essere la stagione della riproduzione.",
		PERD = "Stupido pennuto! Stai lontano dalle mie bacche!",
		PEROGIES = "Questi si sono rivelati piuttosto buoni.",
		PETALS = "Ho mostrato a quei fiori chi è il capo!",
		PETALS_EVIL = "Non sono sicuro di volerli tenere.",
		PHLEGM = "È spesso e flessibile. E salato.",
		PICKAXE = "Emblematico, vero?",
		PIGGYBACK = "Questo porcellino se n'è andato... \"a casa\".",
		PIGHEAD = 
		{	
			GENERIC = "Sembra essere un'offerta alla bestia.",
			BURNT = "Croccante.",
		},
		PIGHOUSE =
		{
			FULL = "Vedo un muso schiacciato contro la finestra.",
			GENERIC = "Questi maiali hanno delle belle abitazioni.",
			LIGHTSOUT = "Dai! Lo so che sei casa!",
			BURNT = "Non è così speciale ora, maiale!",
		},
		PIGKING = "Diamine, puzza!",
		PIGMAN =
		{
			DEAD = "Qualcuno dovrebbe dirlo alla sua famiglia.",
			FOLLOWER = "Fai parte del mio entourage.",
			GENERIC = "Mi danno i brividi.",
			GUARD = "Sembra serio.",
			WEREPIG = "Non è un maiale amichevole!!",
		},
		PIGSKIN = "Ha ancora la coda.",
		PIGTENT = "Odora di pancetta.",
		PIGTORCH = "Di certo sembra accogliente.",
		PINECONE = 
		{
		    GENERIC = "Posso sentire un piccolo albero al suo interno, che cerca di uscire.",
		    PLANTED = "Sarà presto un albero!",
		},
		LUMPY_SAPLING = "Come ha fatto a riprodursi questo albero?",
		PITCHFORK = "Maxwell potrebbe essere alla ricerca di questo.",
		PLANTMEAT = "Non sembra molto invitante.",
		PLANTMEAT_COOKED = "Almeno ora è caldo.",
		PLANT_NORMAL =
		{
			GENERIC = "Frondoso!",
			GROWING = "Uh! Va così piano!",
			READY = "Mmmm. Pronto per la mietitura.",
			WITHERED = "Il calore lo ha ucciso.",
		},
		POMEGRANATE = "Sembra l'interno del cervello di un alieno.",
		POMEGRANATE_COOKED = "Alta cucina!",
		POMEGRANATE_SEEDS = "È un seme di melo-qualcosa.",
		POND = "Non riesco a vedere il fondo!",
		POOP = "Dovrei riempirmi le tasche!",
		FERTILIZER = "È sicuramente un secchio pieno di cacca.",
		PUMPKIN = "È grande come la mia testa!",
		PUMPKINCOOKIE = "Questo è un bel biscotto di cucurbitacee!",
		PUMPKIN_COOKED = "Come hai fatto a non trasformarti in una torta?",
		PUMPKIN_LANTERN = "Inquietante!",
		PUMPKIN_SEEDS = "È un seme di zucca.",
		PURPLEAMULET = "Mi sta sussurrando.",
		PURPLEGEM = "Contiene i misteri dell'universo.",
		RABBIT =
		{
			GENERIC = "È alla ricerca di carote.",
			HELD = "Ti piace la scienza?",
		},
		RABBITHOLE = 
		{
			GENERIC = "Quello deve condurre al Regno degli Uomini-coniglio.",
			SPRING = "Il Regno degli Uomini-coniglio è chiuso per la stagione.",
		},
		RAINOMETER = 
		{	
			GENERIC = "Misura la nuvolosità.",
			BURNT = "Le parti misuranti sono finite tra le nuvole.",
		},
		RAINCOAT = "Mantiene la pioggia dove dovrebbe essere. Fuori dal mio corpo.",
		RAINHAT = "Mi scompiglierà i capelli, ma starò bello e asciutto.",
		RATATOUILLE = "Una eccellente sorgente di fibre.",
		RAZOR = "Una roccia affilata legata ad una stecca. Igienica!",
		REDGEM = "Brilla di calore interno.",
		RED_CAP = "Ha uno strano odore.",
		RED_CAP_COOKED = "Ora è diverso...",
		RED_MUSHROOM =
		{
			GENERIC = "È un fungo.",
			INGROUND = "Sta dormendo.",
			PICKED = "Mi chiedo se tornerà?",
		},
		REEDS =
		{
			BURNING = "Sta bruciando davvero!",
			GENERIC = "È un cespuglio di canne.",
			PICKED = "Ho raccolto tutte le canne utili.",
		},
        RELIC = 
        {
            GENERIC = "Antichi articoli per la casa.",
            BROKEN = "Non c'è niente da fare qui.",
        },
        RUINS_RUBBLE = "Questo può essere aggiustato.",
        RUBBLE = "Solo pezzi e pezzetti di roccia.",
		RESEARCHLAB = 
		{	
			GENERIC = "Scompone gli oggetti nelle loro componenti scientifiche.",
			BURNT = "Non potrà fare molta scienza adesso.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "È ancora più scientifico dell'ultimo!",
			BURNT = "La scienza supplementare non lo ha tenuto in vita.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Che cosa ho creato?",
			BURNT = "Qualunque cosa fosse, è bruciata adesso.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Chi darebbe il nome a una cosa simile?",
			BURNT = "Il fuoco non risolve davvero i problemi dei nomi...",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Che bel diavolo!",
			BURNT = "Non serve più a niente.",
		},
		RESURRECTIONSTONE = "Farsi rivedere ogni tanto è sempre una buona idea.",
		ROBIN =
		{
			GENERIC = "Questo significa che l'inverno è passato?",
			HELD = "Gli piace la mia tasca.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "La vita nelle lande ghiacciate.",
			HELD = "È così morbido.",
		},
		ROBOT_PUPPET = "È intrappolato!",
		ROCK_LIGHT =
		{
			GENERIC = "Una crosta sopra il pozzo di lava.",
			OUT = "Sembra fragile.",
			LOW = "La lava sta facendo la crosta in superficie.",
			NORMAL = "Bello e piacevole.",
		},
		ROCK = "Non entrerebbe nella mia tasca.",
		ROCK_ICE = 
		{
			GENERIC = "Un ghiacciaio molto isolato.",
			MELTED = "Non ha utilità finché non si ghiaccia di nuovo.",
		},
		ROCK_ICE_MELTED = "Non ha utilità finché non si ghiaccia di nuovo.",
		ICE = "Piacere di conoscerti.",
		ROCKS = "Posso creare cose con queste.",
        ROOK = "Assalta il castello!",
		ROPE = "Alcune funi corte.",
		ROTTENEGG = "BLEAH! Che puzza!",
		SANITYROCK =
		{
			ACTIVE = "È una roccia dall'aspetto PAZZO!",
			INACTIVE = "Che fine ha fatto il resto?",
		},
		SAPLING =
		{
			BURNING = "Sta bruciando in fretta!",
			WITHERED = "Potrebbe andar bene se fosse più fresco.",
			GENERIC = "Gli alberelli sono così teneri!",
			PICKED = "Questo gli darà una lezione.",
		},
		SEEDS = "Ognuno di essi è un piccolo mistero.",
		SEEDS_COOKED = "Li ho cucinati all'estremo!",
		SEWING_KIT = "Accidenti! Tutti al diavolo!",
		SHOVEL = "Nel sottosuolo succedono un sacco di cose.",
		SILK = "Proviene dal deretano di un ragno.",
		SKELETON = "Meglio tu che io.",
		SCORCHED_SKELETON = "Inquietante.",
		SKELETON_PLAYER = "Meglio lui di... aspetta un attimo!",
		SKULLCHEST = "Non so se voglio aprirlo.",
		SMALLBIRD =
		{
			GENERIC = "È un pennuto piuttosto piccolo!",
			HUNGRY = "Sembra affamato.",
			STARVING = "Deve avere una fame da lupo.",
		},
		SMALLMEAT = "Un minuscolo pezzo di animale morto.",
		SMALLMEAT_DRIED = "Un po' di carne essiccata.",
		SPAT = "Che animale dall'aspetto croccante.",
		SPEAR = "È una stecca appuntita.",
		SPIDER =
		{
			DEAD = "Bleah!",
			GENERIC = "Odio i ragni.",
			SLEEPING = "Farei meglio a non trovarmi qua quando si sveglia.",
		},
		SPIDERDEN = "Appiccicoso!",
		SPIDEREGGSACK = "Spero che queste non si schiudano nella mia tasca.",
		SPIDERGLAND = "Ha un odore pungente, antisettico.",
		SPIDERHAT = "Spero di averci tolto tutta la materia viscida del ragno.",
		SPIDERQUEEN = "AAAAAAAAH! Quel ragno è enorme!",
		SPIDER_WARRIOR =
		{
			DEAD = "Buona liberazione!",
			GENERIC = "Sembra anche più maligno del solito.",
			SLEEPING = "Devo mantenermi distante.",
		},
		SPOILED_FOOD = "È una palla pelosa di cibo marcio.",
		STATUEHARP = "Cos'è successo alla testa?",
		STATUEMAXWELL = "Cattura davvero la sua personalità.",
		STEELWOOL = "Fibre metalliche ruvide.",
		STINGER = "Sembra forte!",
		STRAWHAT = "I cappelli mi rovinano sempre la pettinatura.",

		TALLBIRD = "È un pennuto alto!",
		TALLBIRDEGG = "Si schiuderà?",
		TALLBIRDEGG_COOKED = "Delizioso e nutriente.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Sta tremando oppure sono io?",
			GENERIC = "Sembra che si stia schiudendo!",
			HOT = "Ma le uova sudano?",
			LONG = "Ho la sensazione che ci vorrà un po'...",
			SHORT = "Dovrebbe schiudersi in qualsiasi momento da adesso.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Ma che uovo!",
			PICKED = "Il nido è vuoto.",
		},
		TEENBIRD =
		{
			GENERIC = "Non è un pennuto molto alto.",
			HUNGRY = "Farei bene a trovare del cibo.",
			STARVING = "Ha uno sguardo pericoloso.",
		},
		TELEBASE =
		{
			VALID = "È pronto all'utilizzo.",
			GEMS = "Ha bisogno di più gemme viola.",
		},
		GEMSOCKET = 
		{
			VALID = "Sembra pronto.",
			GEMS = "Ha bisogno di una gemma.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Con questo posso sicuramente passare attraverso lo spazio e il tempo!",
			GENERIC = "Sembra essere il legame con un altro mondo!",
			LOCKED = "Manca ancora qualcosa.",
			PARTIAL = "Presto, l'invenzione sarà completa!",
		},
		TELEPORTATO_BOX = "Questo può controllare la polarità dell'intero universo.",
		TELEPORTATO_CRANK = "Abbastanza duro da gestire gli esperimenti più intensi.",
		TELEPORTATO_POTATO = "Questa patata di metallo contiene un potere grande e spaventoso...",
		TELEPORTATO_RING = "Un anello che potrebbe concentrare le energie dimensionali.",
		TELESTAFF = "Mi può mostrare il mondo.",
		TENT = 
		{
			GENERIC = "Impazzisco quando non dormo.",
			BURNT = "Non è rimasto niente per dormirci.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Un bel posto per un riposo pomeridiano, lontano dal calore.",
			BURNT = "Non potrà fare molta ombra adesso.",
		},
		TENTACLE = "Sembra pericoloso.",
		TENTACLESPIKE = "È appuntito e viscido.",
		TENTACLESPOTS = "Credo che questi fossero i suoi genitali.",
		TENTACLE_PILLAR = "Un palo viscido.",
		TENTACLE_PILLAR_HOLE = "Sembra puzzolente, ma vale la pena esplorarlo.",
		TENTACLE_PILLAR_ARM = "Piccole braccia scivolose.",
		TENTACLE_GARDEN = "Ancora un altro palo viscido.",
		TOPHAT = "Che bel cappello.",
		TORCH = "Una cosa per ritardare la notte.",
		TRANSISTOR = "Emette un ronzio di elettricità.",
		TRAP = "L'ho tessuto davvero stretto.",
		TRAP_TEETH = "È una brutta sorpresa.",
		TRAP_TEETH_MAXWELL = "Eviterei di camminarci sopra!",
		TREASURECHEST = 
		{
			GENERIC = "È il mio baule dei vestiti!",
			BURNT = "Quella cassa è stata scassata.",
		},
		TREASURECHEST_TRAP = "Davvero conveniente!",
		TREECLUMP = "È quasi come se qualcuno stesse cercando di impedirmi di andare da qualche parte.",

		TRINKET_1 = "Sono tutti fusi insieme.",
		TRINKET_10 = "Spero di uscire da qui prima di aver bisogno di questi.",
		TRINKET_11 = "Mi sussurra delle belle bugie.",
		TRINKET_12 = "Non sono sicuro di cosa dovrei farci con un tentacolo essiccato.",
		TRINKET_2 = "Corpo di mille kazoo, che cos'hai?",
		TRINKET_23 = "Qualcuno ha perso la parola.",
		TRINKET_3 = "Il nodo è bloccato. Per sempre.",
		TRINKET_4 = "Deve trattarsi di qualche specie di artefatto religioso.",
		TRINKET_5 = "Purtroppo è troppo piccolo per poterci scappare in groppa.",
		TRINKET_6 = "I loro giorni del trasporto di elettricità sono finiti.",
		TRINKET_7 = "Non ho tempo per i giochetti!",
		TRINKET_8 = "Ottimo. Tutte le necessità di tappare le vasche da bagno sono soddisfatte.",
		TRINKET_9 = "Sono più una persona da cerniera.",

		BISHOP_CHARGE_HIT = "Ahi!",
		TRUNKVEST_SUMMER = "Landa selvaggia informale.",
		TRUNKVEST_WINTER = "Abbigliamento di sopravvivenza per l'inverno.",
		TRUNK_COOKED = "In qualche modo anche più nasale di prima.",
		TRUNK_SUMMER = "Una leggera proboscide ventilata.",
		TRUNK_WINTER = "Una proboscide spessa e pelosa.",
		TUMBLEWEED = "Chi lo sa cosa ha raccolto quel rotolacampo.",
		TURF_DIRT = "Un pezzo di terra.",
		TURF_FOREST = "Un pezzo di terra.",
		TURF_GRASS = "Un pezzo di terra.",
		TURF_MARSH = "Un pezzo di terra.",
		TURF_ROAD = "Ciottoli messi insieme in fretta.",
		TURF_ROCKY = "Un pezzo di terra.",
		TURF_SAVANNA = "Un pezzo di terra.",
		TURKEYDINNER = "Mmmm.",
		TWIGS = "È un mucchio di piccoli ramoscelli.",
		UMBRELLA = "Manterrà i miei capelli asciutti, almeno.",
		GRASS_UMBRELLA = "Manterrà i miei capelli moderatamente asciutti, almeno.",
		PALMLEAF_UMBRELLA = "I miei capelli stanno bene da bagnati... il problema sorge quando sono asciutti.",
		UNIMPLEMENTED = "Non sembra finito! Potrebbe essere pericoloso.",
		WAFFLES = "Sono indeciso se aggiungere altro sciroppo.",
		WALL_HAY = 
		{	
			GENERIC = "Mmmmm. Credo che dovrà bastare.",
			BURNT = "Non va affatto bene.",
		},
		WALL_HAY_ITEM = "Sembra una cattiva idea.",
		WALL_STONE = "Che bel muro.",
		WALL_STONE_ITEM = "Mi fanno sentire così sicuro.",
		WALL_RUINS = "Un antico pezzo di muro.",
		WALL_RUINS_ITEM = "Un solido pezzo di storia.",
		WALL_WOOD = 
		{
			GENERIC = "Appuntito!",
			BURNT = "Bruciato!",
		},
		WALL_WOOD_ITEM = "Picchetti!",
		WALL_MOONROCK = "Spaziosa e liscia!",
		WALL_MOONROCK_ITEM = "Molto leggera, ma sorprendentemente dura.",
		MOONROCKNUGGET = "Quella roccia proviene dalla luna.",
		ROCK_MOON = "Quella roccia proviene dalla luna.",
		WALRUS = "I trichechi sono predatori naturali.",
		WALRUSHAT = "È ricoperto da peli di tricheco.",
		WALRUS_CAMP =
		{
			EMPTY = "Sembra che qualcuno si sia accampato qui.",
			GENERIC = "Sembra caldo e accogliente all'interno.",
		},
		WALRUS_TUSK = "Sono sicuro che ne troverò un uso alla fine.",
		WARDROBE = 
		{
			GENERIC = "Racchiude segreti oscuri e profondi...",
            BURNING = "Sta bruciando in fretta!",
			BURNT = "Non va più di moda.",
		},
		WARG = "Potresti essere qualcosa con cui fare i conti, cagnolone.",
		WASPHIVE = "Credo che quelle api siano matte.",
		WATERMELON = "Dolce appiccicoso.",
		WATERMELON_COOKED = "Caldo e succoso.",
		WATERMELONHAT = "Lascia scorrere il succo sulla tua faccia.",
		WETGOOP = "Non sa di niente.",
		WHIP = "Niente aiuta a mantenere la pace come i rumori forti.",
		WINTERHAT = "Sarà buono per quando arriva l'inverno.",
		WINTEROMETER = 
		{
			GENERIC = "Sono uno scienziato eccezionale.",
			BURNT = "I giorni delle misurazioni sono finiti.",
		},
		WORMHOLE =
		{
			GENERIC = "Morbido e ondulato.",
			OPEN = "La scienza mi costringe ad essere coinvolto.",
		},
		WORMHOLE_LIMITED = "Guh, quella cosa sembra peggio del solito.",
		ACCOMPLISHMENT_SHRINE = "Voglio usarlo, e voglio che il mondo sappia quello che ho fatto.",        
		LIVINGTREE = "Mi sta guardando?",
		ICESTAFF = "È freddo al tatto.",
		
        FLOTSAM = "Se solo potessi trovare il modo di agganciarmici da qui.",

        SUNKEN_BOAT = 
        {
            GENERIC = "Quel tipo sembra che voglia parlare.",
            ABANDONED = "Questo è il motivo per il quale odio l'acqua.",
        },
        SUNKEN_BOAT_BURNT = "È ancora meno idonea alla navigazione di prima.",
   		SUNKEN_BOAT_TRINKET_1 = "Uno strumento di qualche tipo.", --sextant
		SUNKEN_BOAT_TRINKET_2 = "Adesso ho solo bisogno di una macchina miniaturizzatrice!", --toy boat
		SUNKEN_BOAT_TRINKET_3 = "Sembra un po' fradicia.", --candle
		SUNKEN_BOAT_TRINKET_4 = "Scientifico!", --sea worther
		SUNKEN_BOAT_TRINKET_5 = "Se solo ne avessi un'altra.", --boot

		HOUNDFIRE = "Fuoco! Fuoco!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------
		
		STUFFEDEGGPLANT = "Sarò ripieno dopo aver mangiato questo!",
		SUNKBOAT = "È inutile per me là fuori!",
		BANANAPOP = "No, non congelare il cervello! Mi serve per la scienza!",
		BISQUE = "Cucinarla mi ha tenuto di sicuro di zuppa-umore!",
		CEVICHE = "Posso avere una ciotola più grande? Questa sembra un po' striminzita.",
		SEAFOODGUMBO = "È un gigantesco gombo con frutti di mare.",
		SURFNTURF = "È perfettissimo!",
		SHARKFINSOUP = "Zuppa di pinne di squalo!",
		LOBSTERDINNER = "Se la mangio di mattina è ancora considerata cena?",
		LOBSTERBISQUE = "Manca un po' di sale, ma non sono zuppe che mi riguardano.",
		JELLYOPOP = "Ghiacciolo alla medusa da addentare subito!",
		SWEATERVEST = "Questo giubbotto è elegante per uscire tutto in ghingheri.",
		REFLECTIVEVEST = "Alla larga, sole malvagio!",
		HAWAIIANSHIRT = "Non è a prova di laboratorio!",
		TAFFY = "Il mio dentista si arrabbierebbe se lo mangiassi... meno male che non ne ho.",

		ANTIVENOM = "Ha un sapore orribile!",
		VENOMGLAND = "Solo il veleno può curare il veleno.",
		BLOWDART_POISON = "L'estremità a punta va in quella direzione.",
		OBSIDIANMACHETE = "È rovente al tatto.",
		SPEARGUN_POISON = "Punta avvelenata.",
		OBSIDIANSPEARGUN = "Punta di fuoco.",
		LUGGAGECHEST = "Sembra un baule a vapore di prima categoria.",
		PIRATIHATITATOR =
		{
			GENERIC = "Sta torcendo la mia lingua.",
			BURNT = "Il fuoco non risolve davvero i problemi dei nomi...",
		},
		COFFEEBEANS = "Potrebbero essere tostati.",
		COFFEE = "Ha un profumo delizioso ed energizzante!",
		COFFEEBEANS_COOKED = "Il calore li ha migliorati.",
		COFFEEBUSH =
		{
			BARREN = "Credo che debba essere fertilizzato.",
			WITHERED = "Sembra malnutrito.",
			GENERIC = "Potrei imparare ad amare questa pianta.",
			PICKED = "Forse ricrescerà?",
		},
		COFFEEBOT = "È una macchina per il caffè.",
		MUSSEL = "Servirebbero un po' di flessioni.",
		MUSSEL_FARM =
		{
			 GENERIC = "Mi chiedo se vengano da Bruxelles.",
			 STICKPLANTED = "L'ho davvero piantato su di loro."
		},

		MUSSEL_STICK = "Ho davvero intenzione di infilzare quelle cozze.",
		LOBSTER = "Ma che aragostra.",
		LOBSTERHOLE = "Wascal sta dormendo.",
		SEATRAP = "Per una cattura mortale.",
		SAND_CASTLE =
		{
			SAND = "È un castello di sabbia, nella sabbia!",
			GENERIC = "Guarda cosa ho fatto!"
		},
		BOATREPAIRKIT = "Questo farà galleggiare di più la mia barca.",

		BALLPHIN = "Che amico rotondo e gommoso.",
		BOATCANNON = "L'unica cosa migliore di una barca è una barca con un cannone.",
		BOTTLELANTERN = "Una bottiglia piena di sole.",
		BURIEDTREASURE = "Ti prego di essere un buon tesoro!",
		BUSH_VINE =
		{
			BURNING = "Ops!",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "È tutto rampicante.",
		},
		CAPTAINHAT = "L'abbigliamento nautico più adatto.",
		COCONADE =
		{
			BURNING = "Sembra pericoloso.",
			GENERIC = "Dovrò accenderla prima.",
		},
		CORAL = "Materiale da costruzione vivente!",
		CORALREEF = "Il corallo ha formato una barriera!",
		CRABHOLE = "Chiamano casa una buca scavata nella sabbia.",
		CUTLASS = "Spero che questa spada non inizi a puzzare...",
		DUBLOON = "Sono ricco!",
		FABRIC = "Un panno morbido fatto di radice dura!",
		FISHINHOLE = "Questa zona sembra piena di pesci.",
		GOLDENMACHETE = "Colpisce con stile!",
		JELLYFISH = "Questa creatura è scienza pura!",
		JELLYFISH_DEAD = "Ha vissuto una buona vita, forse.",
		JELLYFISH_COOKED = "Si contorce tutto.",
		JELLYFISH_PLANTED = "La scienza funziona in un modo misterioso e bolloso.",
		JELLYJERKY = "Sarei un idiota a non mangiarlo.",

		LIMPETROCK =
		{
			GENERIC = "Potrei riempire un secchio con tutte quelle lumache.",
			PICKED = "Non posso riempire il secchio senza le lumache.",
		},
		LOGRAFT = "Sembra... tipo una barca...",
		MACHETE = "Mi piace il taglio di questa lama.",
		MESSAGEBOTTLEEMPTY = "Solo una bottiglia vuota.",
		MOSQUITO_POISON = "Queste maledette zanzare portano malattie terribili.",
		OBSIDIANCOCONADE = "È una bomba ancora più forte!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Dovrei mettere qualcosa sul fuoco prima che sia troppo tardi.",
			GENERIC = "Questo pozzo per il fuoco è il conduttore di... altro fuoco.",
			HIGH = "Buona cosa che è contenuto!",
			LOW = "Il fuoco si sta affievolendo.",
			NORMAL = "Questa è la mia migliore invenzione.",
			OUT = "Almeno posso ricominciare.",
		},
		OX = "Queste creature sembrano ragionevoli.",
		PIRATEHAT = "Adatto ad un furfante tagliagola. O a me.",
		RAFT = "Sembra adeguata.",
		ROWBOAT = "Funziona con olio di gomito.",
		SAIL = "Questo potrebbe davvero trasformare la mia navigazione.",
		SANDBAG_ITEM = "Tecnologia della sabbia portatile.",
		SANDBAG = "Tiene l'acqua a bada.",
		SEASACK = "Odio quando il cibo ha un gusto non-così-fresco.",
		SEASHELL_BEACHED = "Rifiuti del mare.",
		SEAWEED = "Un'erba. Del mare.",

		SEAWEED_PLANTED = "È questo che passano da mangiare da queste parti?",
		SLOTMACHINE = "Suppongo che potrei indugiare per qualche secondo.",
		SNAKE_POISON = "Ancora peggio di un serpente comune!",
		SNAKESKIN = "Sono incuriosito e disgustato.",
		SNAKESKINHAT = "Dovrebbe respingere la pioggia dai miei capelli.",
		SOLOFISH = "Odora di cane bagnato.",
		SPEARGUN = "Oh, la scienza che potrei fare con questa!",
		SPOILED_FISH = "Non sono troppo curioso di odorarlo.",
		SWORDFISH = "Credo che questo pesce sia evoluto per trafiggermi.",
		TRIDENT = "Mi domando quanti anni abbia questo artefatto.",
		TRINKET_13 = "Che cosa è questa sostanza?",
		TRINKET_14 = "Questa cosa mi dà i brividi...",
		TRINKET_15 = "Incredibile! Questa chitarra è stata sottoposta al processo di 'restringi-ficazione'!",
		TRINKET_16 = "Come ha fatto ad arrivare fino a qui?",
		TRINKET_17 = "Dov'è l'altro?",
		TRINKET_18 = "Una reliquia di un'epoca passata!",
		TRINKET_19 = "Annebbiamento del cervello. Mai sentito...",
		TURBINE_BLADES = "Forse questo ha alimentato la tempesta bestiale.",
		TURF_BEACH = "Terreno sabbioso.",
		TURF_JUNGLE = "Un terreno molto irregolare.",
		VOLCANO_ALTAR =
		{
			GENERIC = "Sembra essere chiuso.",
			OPEN = "L'altare è aperto e pronto ad accettare le offerte!",
		},
		VOLCANO_ALTAR_BROKEN = "Ehm, non sarà un problema, vero?",
		WHALE_BLUE = "Quella balena ha problemi emotivi.",
		WHALE_CARCASS_BLUE = "Nauseante. Credo sia iniziata la decomposizione.",
		WHALE_CARCASS_WHITE = "Nauseante. Credo sia iniziata la decomposizione.",

		ARMOR_SNAKESKIN = "Alla moda!",
		CLOTHSAIL = "Quel vento non sta andando via adesso!",
		DUG_COFFEEBUSH = "Questo appartiene alla terra!",
		LAVAPOOL = "Un po' forte per i miei gusti.",
		BAMBOO = "Forse posso confondere i miei nemici con questo?",
		AERODYNAMICHAT = "Passa proprio attraverso l'aria!",
		POISONHOLE = "Credo che mi terrò alla larga da quello.",
		BOAT_LANTERN = "Farà miracoli per la mia vista notturna!",
		DEAD_SWORDFISH = "Meglio non correre con questo.",
		LIMPETS = "Forse il digiuno non è poi così male.",
		OBSIDIANAXE = "Accoppiata vincente!",
		COCONUT = 
		{
		    GENERIC = "Richiede un gran schiaccianoci.",
		    PLANTED = "Non ha più bisogno del mio aiuto per crescere.",
		},
		COCONUT_COOKED = "Ora ho solo bisogno di una torta.",
		BERMUDATRIANGLE = "Mi dà una sensazione di disagio.",
		SNAKE = "Mi domando se mi venderà dell'olio.",
		SNAKEOIL = "L'etichetta dice \"Miracoloso olio di serpente\"!",
		ARMORSEASHELL = "Arti e mestieri!",
		SNAKE_FIRE = "Quel serpente è fumante?",
		MUSSEL_COOKED = "Cucino una cozza crudele.",

		PACKIM_FISHBONE = "Sembra una cosa che porterei in giro.",
		PACKIM = "Scommetto che potrei impacchettarlo ben bene.",

		ARMORLIMESTONE = "Sono sicuro che resisterà ottimamente!",
		TIGERSHARK = "Beh, è terrificante.",
		WOODLEGS_KEY1 = "Qualcosa, da qualche parte, deve essere chiusa a chiave.",
		WOODLEGS_KEY2 = "Questa chiave probabilmente apre qualcosa.",
		WOODLEGS_KEY3 = "È una chiave.",
		WOODLEGS_CAGE = "Sembra una quantità eccessiva di serrature.",
		OBSIDIAN_WORKBENCH = "Mi sento ispirato.",

		NEEDLESPEAR = "Sono grato di non esserci passato sopra.",
		LIMESTONE = "Sembra un materiale da costruzione utile.",
		DRAGOON = "Sei uno rapido, non è vero?",

		ICEMAKER = 
		{
			OUT = "Ha bisogno di più carburante.",
			VERYLOW = "La sento tremolare.",
			LOW = "Sembra stia rallentando.",
			NORMAL = "Sta funzionando.",
			HIGH = "Funziona perfettamente!",
		},

		DUG_BAMBOOTREE = "Devo piantarlo.",
		BAMBOOTREE =
		{
			BURNING = "Ciao ciao, bambù.",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "Sembra piuttosto robusto.",
		},
		JUNGLETREE =
		{
			BURNING = "Che spreco di legna.",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "Quell'albero ha bisogno di un taglio.",
		},
		SHARK_GILLS = "Vorrei avere le branchie.",
		TREEGUARD = "Che qualcuno mi dia una mano con questa palma!",
		OBSIDIAN = "È una roccia di fuoco.",
		BABYOX = "Più piccolo, ma puzzolente.",
		STUNGRAY = "Credo che manterrò le distanze.",
		SHARK_FIN = "Una pinna elegante.",
		FROG_POISON = "Sembra più cattivo del solito.",
		ARMOUREDBOAT = "È una barca durevole.",
		ARMOROBSIDIAN = "Sono un genio.",
		BIOLUMINESCENCE = "Produce una luce lenitiva.",
		SPEAR_POISON = "Ora è molto più letale.",
		SPEAR_OBSIDIAN = "Questo lascerà il segno.",
		SNAKEDEN =
		{
			BURNING = "Ops!",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "È tutto rampicante.",
		},
		TOUCAN = "Puuure io non posso prenderlo.",
		MESSAGEBOTTLE = "Qualcuno mi ha scritto un messaggio!",
		SAND = "Un utile mucchio di sabbia da taschino.",
		SANDHILL = "Faresti meglio a non entrare nelle mie scarpe.",
		PEACOCK = "Niente altro che un ladro ben vestito.",
		VINE = "Forse posso legarci le cose.",
		SUPERTELESCOPE = "Posso vedere per sempre!",
		SEAGULL = "Sciò! Trova qualche altra terra!",
		SEAGULL_WATER = "Sciò! Trova qualche altra acqua!",
		PARROT = "Ho appena finito la scorta di cracker.",
		ARMOR_LIFEJACKET = "Mi tiene a galla, senza la mia barca!",
		WHALE_BUBBLES = "Something's underwater here.",
		EARRING = "Meno buchi ho nel corpo e meglio è.",
		ARMOR_WINDBREAKER = "Il vento non ha alcuna possibilità!",
		SEAWEED_COOKED = "Croccante.",
		CARGOBOAT = "C'è spazio per tutte le mie cose!",
		GASHAT = "Succhia fuori tutta la puzza.",
		ELEPHANTCACTUS = "Accidenti! Potrei infilzarmi l'occhio!",
		DUG_ELEPHANTCACTUS = "Una pianta spinosa portatile.",
		ELEPHANTCACTUS_ACTIVE = "Quel cactus sembra anormale.",
		ELEPHANTCACTUS_STUMP = "Farà germogliare più spine un giorno.",
		FEATHERSAIL = "È leggera come una piuma!",
		WALL_LIMESTONE_ITEM = "Questi sarebbero più utili se li piazzassi.",
		JUNGLETREESEED =
        {
            GENERIC = "Posso sentire il sibilo di piccoli serpenti.",
            PLANTED = "Crescerà e diventerà un bell'albero della giungla.",
        },
		VOLCANO = "La mia sapienza scientifica mi dice che si tratta di una montagna assolutamente sicura!",
		IRONWIND = "Così dovrebbe viaggiare uno scienziato.",
		SEAWEED_DRIED = "Salato!",
		TELESCOPE = "Con il mio occhietto spio...",
		
		DOYDOY = "Mi sento stranamente protettivo di questo sciocco uccello.",
		DOYDOYBABY = "Ma che tenera piccola, ehm, cosa.",
		DOYDOYEGG = "Forse avrei dovuto farlo schiudere.",
		DOYDOYEGG_CRACKED = "Oh bene. Sicuramente ce ne sono molte altre!",
		DOYDOYFEATHER = "Morbido e in via di estinzione!",

		PALMTREE =
		{
			BURNING = "Che spreco di legna.",
			BURNT = "Mi sento come se avessi potuto impedirlo.",
			CHOPPED = "Prendi questo, natura!",
			GENERIC = "Molto tropicale.",
		},
		PALMLEAF = "Sono affezionato a queste fronde.",
		CHIMINEA = "Prendi questo, vento!",
		DOUBLE_UMBRELLAHAT = "Il secondo ombrello mantiene il primo ombrello asciutto.",
		CRAB = 
		{
			GENERIC = "Non fare lo stizzoso con me, signore.",
			HIDDEN = "Mi chiedo dove sia andato quel granchiglio.",
		},
		TRAWLNET = "Niente altro che reti.",
		TRAWLNETDROPPED = 
		{
			SOON = "Sta sicuramente affondando.",
			SOONISH = "Credo che stia affondando.",
			GENERIC = "È pieno di potenzialità.",
		},
		VOLCANO_EXIT = "Sento una brezza fresca provenire da fuori.",
		SHARX = "Queste cose sono sicuramente persistenti.",
		SEASHELL = "Magari potrei venderle.",
		WHALE_BUBBLES = "Qualcosa laggiù ha l'alito pesante.",
		MAGMAROCK = "Posso scavarlo.",
		MAGMAROCK_GOLD = "Vedo un'occasione d'oro.",
		CORAL_BRAIN_ROCK = "Mi chiedo cosa stia tramando...",
		CORAL_BRAIN = "Spunto di riflessione.",
		SHARKITTEN = "Ma stai facendo le fusa?",
		SHARKITTENSPAWNER = 
		{
			GENERIC = "Quel mucchio di sabbia sta facendo le fusa?",
			INACTIVE = "È un mucchio di sabbia piuttosto grande.",
		},
		LIVINGJUNGLETREE = "Proprio come qualsiasi altro albero.",
		WALLYINTRO_DEBRIS = "Parte di una nave naufragata.",
		MERMFISHER = "Non provare niente che puzzi di pesce.",
        PRIMEAPE = "Queste cose saranno la mia fine.",
        PRIMEAPEBARREL = "Qui dimora il male.",
        REDBARREL = "Molto originale.",
        PORTAL_SHIPWRECKED = "È rotto.",
		MARSH_PLANT_TROPICAL = "Piantoso.",
		TELEPORTATO_SW_POTATO = "Sembra sia stato fatto con uno scopo.",
		PIKE_SKULL = "Ahi!",
		PALMLEAF_HUT = "Ombra, dolce ombra.",
		FISH_RAW_SMALL_COOKED = "Un pezzetto di pesce cotto.",
		LOBSTER_DEAD = "Si dovrebbe cucinare bene.",
		MERMHOUSE_FISHER = "Non ha un odore molto buono.",
		WILDBORE = "Sembra aggressivo.",
		PIRATEPACK = "Posso tenerci il mio bottino.",
		TUNACAN = "Da dove potrebbe provenire?",
		MOSQUITOSACK_YELLOW = "Parte di una zanzara gialla.",
		SANDBAGSMALL = "Questo dovrebbe tenere l'acqua fuori.",
		FLUP = "Lasciami stare!",
		OCTOPUSKING = "Sono una perdente per questo tizio.",
		OCTOPUSCHEST = "Spero che quella cosa sia impermeabile.",
		GRASS_WATER = "Spero tu sia assetata, erba.",
		WILDBOREHOUSE = "Che casa da cinghiale.",
		FISH_RAW_SMALL = "Un piccolo pezzo di pesce.",
		TURF_SWAMP = "Zolla di terreno della palude.",
		FLAMEGEYSER = "Forse dovrei rimanere indietro.",
		KNIGHTBOAT = "Esci dal canale, maniaco!",
		MANGROVETREE_BURNT = "Mi chiedo come sia successo.",
		TIDAL_PLANT = "Guarda. Una pianta.",
		WALL_LIMESTONE = "Robusto.",
		FISH_RAW = "Un pezzo di carne di pesce.",
		LOBSTER_DEAD_COOKED = "Non vedo l'ora di mangiarti.",
		BLUBBERSUIT = "Beh, è un qualcosa.",
		BLOWDART_FLUP = "Vedo, vedo.",
		TURF_MEADOW = "Zolla di prato.",
		TURF_VOLCANO = "Zolla di terreno vulcanoso.",
		SWEET_POTATO = "Sembra delizioso!",
		SWEET_POTATO_COOKED = "Sembra perfino più delizioso.",
		SWEET_POTATO_PLANTED = "È una strana carota.",
		SWEET_POTATO_SEEDS = "Le mie uova di pianta.",
		BLUBBER = "Molliccio!",
		TELEPORTATO_SW_RING = "Sembra che potrei utilizzarlo.",
		TELEPORTATO_SW_BOX = "Sembra una parte di qualcosa.",
		TELEPORTATO_SW_CRANK = "Mi chiedo a cosa sia servito.",
		TELEPORTATO_SW_BASE = "Credo che manchino delle parti.",
		VOLCANOSTAFF = "L'etichetta dice \"Tenere fuori dalla portata dei bambini\".",
		THATCHPACK = "Lo chiamo impagliato.",
		TURF_DESERTDIRT = "Zolla di terriccio del deserto.",
		SHARK_TEETHHAT = "Che cappello minaccioso.",
		TURF_ASH = "Zolla di cenere.",
		TURF_FUNGUS_GREEN = "Zolla con funghi verdi.",
		BOAT_TORCH = "Questo terrà le mie mani libere.",
		MANGROVETREE = "Mi chiedo se stia ricevendo abbastanza acqua?",
		HAIL_ICE = "Agghiacciante.",
		TROPICAL_FISH = "Un pesce dall'aspetto tropicale.",
		TIDALPOOL = "Una piscina lasciata dalle maree.",
		WHALE_WHITE = "Sembra un combattente.",
		VOLCANO_SHRUB = "Sembri cinereo.",
		ROCK_OBSIDIAN = "Falla saltare! Non sarà minata!",
		ROCK_CHARCOAL = "Servirà una calza gigantesca per quello.",
		DRAGOONDEN = "Anche i dragoni dormono.",
		WILBUR_UNLOCK = "Sembra un tipo regale.",
		WILBUR_CROWN = "Ha la strana forma delle scimmie.",
		TWISTER = "Mi sembrava che ci fosse dello strano vento qua intorno.",
		TWISTER_SEAL = "Che tenero.",
		MAGIC_SEAL = "È un artefatto potente.",
		SAIL_STICK = "Ci deve essere una spiegazione scientifica.",
		WIND_CONCH = "Riesco a sentire il vento intrappolato.",
		DRAGOONEGG = "Ho sentito un rumore di rottura?",
		BUOY = "Ahhhh iaaaa boa!", 
		TURF_SNAKESKINFLOOR = "Assssserzione di sssssstile.",
        DOYDOYNEST = "È per le uova di doidoi, cretino.",
		ARMORCACTUS = "La miglior difesa è l'attacco.",
		BIGFISHINGROD = "Per catturare un grande pesce, c'è bisogno di una grande canna.",
		BRAINJELLYHAT = "Due cervelli significano il doppio delle idee!",
		COCONUT_HALVED = "Quando le sbatto insieme, fanno il rumore dei cavalli.",
		CRATE = "Ci deve essere un modo per aprirlo.",
		DEPLETED_BAMBOOTREE = "Crescerà di nuovo?",
		DEPLETED_BUSH_VINE = "Un giorno farà ritorno.",
		DEPLETED_GRASS_WATER = "Addio, dolce pianta.",
		DOYDOYEGG_COOKED = "Una reazione chimica controllata ha reso questo uovo più nutriente.",
		DRAGOONHEART = "Dove il dragone un tempo conservava i suoi sentimenti.",
		DRAGOONSPIT = "È SPUTacolarmente disgustoso!",
		DUG_BUSH_VINE = "Suppongo che debba prenderlo.",
		FRESHFRUITCREPES = "Frutta zuccherata! Parte di una colazione equilibrata.",
		KRAKEN = "Non è il momento di fare il quaccolo saggio!",
		KRAKENCHEST = "Al vincitore, il bottino.",
		KRAKEN_TENTACLE = "Una bestia che non dorme mai.",
		MAGMAROCK_FULL = "Posso scavarlo.",
		MAGMAROCK_GOLD_FULL = "Vedo un'occasione d'oro.",
		MONKEYBALL = "Ho uno strano desiderio di dargli il mio nome.",
		MONSTERTARTARE = "Ci deve essere qualcos'altro da mangiare da queste parti.",
		MUSSELBOUILLABAISE = "Immagina tutti gli esperimenti che potrei farci!",
		MYSTERYMEAT = "Non lo voglio sezionare.",
		OXHAT = "Bello e asciutto. Questo elmetto mi proteggerà dalle intemperie.",
		OX_FLUTE = "Sta gocciolando...?",
		OX_HORN = "Ho afferrato il bue per le corna.",
		PARROT_PIRATE = "Cerco di non mangiare niente che abbia un nome.",
		PEG_LEG = "Posso eseguire l'amputazione se qualcuno la volesse indossare davvero.",
		PIRATEGHOST = "Ha fatto una fine terribile. E anche io se non esco di qui.",
		SANDBAGSMALL_ITEM = "Un sacchetto pieno di sabbia. La scienza non conosce limiti?",
		SHADOWSKITTISH_WATER = "Accidenti!",
		SHIPWRECKED_ENTRANCE = "Ohi!",
		SHIPWRECKED_EXIT = "E così salpo verso l'orizzonte!",
		SNAKESKINSAIL = "Squamalo e fanne una vela!",
		SPEAR_LAUNCHER = "La scienza si prende cura di me.",
		SWEETPOTATOSOUFFLE = "Il soufflé di patate dolci ha una popolarità lievitante.",
		SWIMMINGHORROR = "Ehiii! Fammi tornare sulla terra ferma!",
		TIGEREYE = "Più occhi vedono meglio... giusto?",
		TRINKET_20 = "Non sono sicuro di cosa sia, ma mi fa sentire più intelligente!",
		TRINKET_21 = "Dovrei misurarlo per assicurarmi che sia proporzionato.",
		TRINKET_22 = "Sono sicuro che a qualcuno piacerebbe.",
		TURF_FUNGUS_RED = "Pavimento rosso fungine.",
		TURF_MAGMAFIELD = "Pavimentazione lavica.",
		TURF_TIDALMARSH = "Pavimentazione acquitrinica.",
		VOLCANO_ALTAR_TOWER = "Che paura!",
		WATERYGRAVE = "Certo, potrei pescarlo fuori di lì. Ma dovrei?",
		WHALE_TRACK = "Balena, oh!",
		WILDBOREHEAD = "Ha un odore tanto brutto quanto il suo aspetto.",
		WOODLEGSBOAT = "Un'imbarcazione adatta ad un furfante.",
		WOODLEGSHAT = "Mi fa sembrare scorbuto... voglio dire spaventoso!?",
		WOODLEGSSAIL = "La vela pirata per eccellenza.",
		WRECK = "Povera barchetta.",
		INVENTORYGRAVE = "Credo che qualcuno sia stato qua prima di me.",
        INVENTORYMOUND = "Credo che qualcuno sia stato qua prima di me.",
		LIMPETS_COOKED = "Patellata!",
		RAWLING = "È il mio amico!",
		CALIFORNIAROLL = "Ma non ho le bacchette.",
	},
	DESCRIBE_GENERIC = "È una... cosa.",
	DESCRIBE_TOODARK = "È troppo buio per vedere!",
	DESCRIBE_SMOLDERING = "Quella cosa sta per incendiarsi.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Umm. Beccuto.",
	},
}
