return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "깨어 있을 때 시도하지 않을 거야.",
			GENERIC = "그것은 깎을 수 없어!",
			NOBITS = "짧은 수염도 남지 않았다!",
		},
		STORE =
		{
			GENERIC = "가득 찼네.",
			NOTALLOWED = "그 안에 들어가지 않는다.",
		},
		RUMMAGE =
		{	
			GENERIC = "할 수 없다.",	
		},
        COOK =
        {
            GENERIC = "아, 할 수 없다.",
            TOOFAR = "너무 멀다!",
        },
        GIVE =
        {
            DEAD = "가지고 있어야겠다.",
            SLEEPING = "무의식이라 할 수 있는 것이 없다.",
            BUSY = "나중에 다시 해야지.",
        },
        WRITE =
        {
            GENERIC = "그대로라도 좋다.",
        },
        CHANGEIN =
        {
            GENERIC = "지금은 바꾸기 싫다.",
            BURNING = "지금은 너무 위험해!",
        },
		REPAIRBOAT = 
		{
			GENERIC = "지금은 잘 뜨고 있다.",
		},
		TEACH =
        {
            KNOWN = "이미 가지고 있는 것이다.",
            CANTLEARN = "그것은 배울 수 없다.",
        },
	},
	ACTIONFAIL_GENERIC = "그것은 할 수 없습니다.",
	ANNOUNCE_MAGIC_FAIL = "여기에서는 쓸 수 없다.",
	
	ANNOUNCE_ADVENTUREFAIL = "잘 안 됐어. 다시 시도해야겠어.",
	ANNOUNCE_BEES = "벌이다!!!!",
	ANNOUNCE_BOOMERANG = "이런! 저걸 잡아야 되겠다!",
	ANNOUNCE_CHARLIE = "뭐였지?!",
	ANNOUNCE_CHARLIE_ATTACK = "이런! 무언가가 날 물었다!",
	ANNOUNCE_COLD = "너무 춥다!",
	ANNOUNCE_HOT = "얼음이나... 그늘이... 필요해!",
	ANNOUNCE_CRAFTING_FAIL = "주요 재료가 몇 개 없다.",
	ANNOUNCE_DEERCLOPS = "큰 소리였다!",
	ANNOUNCE_DUSK = "늦어지고 있다. 곧 캄캄해질 거다.",
	ANNOUNCE_EAT =
	{
		GENERIC = "냠!",
		PAINFUL = "속이 안 좋다.",
		SPOILED = "우엑! 끔찍했다!",
		STALE = "변하기 시작했던 것 같다.",
		INVALID = "먹을 수 없는 것이다!",
		YUCKY = "입 안에 넣으면 끔찍하겠다!",
	},
	ANNOUNCE_ENTER_DARK = "너무 어두워!",
	ANNOUNCE_ENTER_LIGHT = "다시 보인다!",
	ANNOUNCE_FREEDOM = "자유다! 드디어 자유다!",
	ANNOUNCE_HIGHRESEARCH = "지금 아주 영리해진 느낌이 든다!",
	ANNOUNCE_HOUNDS = "소리가 들리지 않았습니까?",
	ANNOUNCE_WORMS = "느끼지 않았나요?",
	ANNOUNCE_SHARX = "더 큰 배가 필요해...",
	ANNOUNCE_HUNGRY = "너무 배고파!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "이 자국은 새 거다. 근처에 짐승이 있는 모양이다.",
	ANNOUNCE_HUNT_LOST_TRAIL = "짐승 흔적이 여기에서 끝났다.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "땅이 축축해서 발자국이 남지 않는다.",
	ANNOUNCE_INV_FULL = "물건을 더 휴대할 수 없다!",
	ANNOUNCE_KNOCKEDOUT = "윽, 머리야!",
	ANNOUNCE_LOWRESEARCH = "많은 것을 배우지 못했다.",
	ANNOUNCE_MOSQUITOS = "아! 가 버려!",
	ANNOUNCE_NOWARDROBEONFIRE = "불타면 갈아입을 수 없다!",
	ANNOUNCE_NODANGERSLEEP = "지금은 너무 위험해!",
	ANNOUNCE_NODAYSLEEP = "밖이 너무 밝다.",
	ANNOUNCE_NODAYSLEEP_CAVE = "피곤하지 않다.",
	ANNOUNCE_NOHUNGERSLEEP = "자기에는 너무 배고프다. 꼬르륵거려서 잠을 잘 수 없다!",
	ANNOUNCE_NOSLEEPONFIRE = "그 안에서 자고픈 것은 아니다.",
	ANNOUNCE_NODANGERSIESTA = "지금은 낮잠 자기에 너무 위험하다!",
	ANNOUNCE_NONIGHTSIESTA = "밤은 낮잠이 아니라 잠자기 위한 시간.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "여기에서 제대로 쉴 수 없겠다.",
	ANNOUNCE_NOHUNGERSIESTA = "너무 배고파서 낮잠을 못 자겠다!",
	ANNOUNCE_NO_TRAP = "쉬웠다.",
	ANNOUNCE_PECKED = "이런! 그만 해!",
	ANNOUNCE_QUAKE = "예감이 안 좋은 소리다.",
	ANNOUNCE_RESEARCH = "절대로 배움을 멈추지 말라!",
	ANNOUNCE_SHELTER = "나쁜 날씨로부터 날 보호해 줘서 고맙다, 나무야!",
	ANNOUNCE_THORNS = "이런!",
	ANNOUNCE_BURNT = "앗! 뜨거워!",
	ANNOUNCE_TORCH_OUT = "불이 방금 꺼졌다!",
	ANNOUNCE_FAN_OUT = "바람이 부는 날의 부채.",
    ANNOUNCE_COMPASS_OUT = "나침반의 방향이 죽었다.",
	ANNOUNCE_TRAP_WENT_OFF = "아차.",
	ANNOUNCE_UNIMPLEMENTED = "이런! 아직 준비되지 않은 것 같다.",
	ANNOUNCE_WORMHOLE = "멀쩡한 정신으로 할 짓이 아니었다.",
	ANNOUNCE_CANFIX = "\n고칠 수 있을 것 같아!",
	ANNOUNCE_ACCOMPLISHMENT = "많은 것을 성취한 느낌!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "친구들이 지금 나를 볼 수 있다면...",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "식물아, 아직도 배고파?",
	ANNOUNCE_TOOL_SLIP = "앗, 미끄러운 도구다!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "겁나는 벼락을 피할 수 있다!",

	ANNOUNCE_DAMP = "아, H2O.",
	ANNOUNCE_WET = "옷이 삼투성이다.",
	ANNOUNCE_WETTER = "물의 순리!",
	ANNOUNCE_SOAKED = "거의 포화 상태에 도달했다.",

	ANNOUNCE_TREASURE = "지도다! 위치를 표시하고 있다!",
	ANNOUNCE_MORETREASURE = "정말? 또 있나!?",
	ANNOUNCE_OTHER_WORLD_TREASURE = "지도가 주변과 일치하지 않는다.",
	ANNOUNCE_OTHER_WORLD_PLANT = "흙에 적합한 영양분이 있는 것 같지 않다.",

	ANNOUNCE_MESSAGEBOTTLE =
	{
		"글이 흐려져서 읽을 수 없다.",
	},
	ANNOUNCE_VOLCANO_ERUPT = "좋을 리가 없어.",
	ANNOUNCE_MAPWRAP_WARN = "여기에 괴물이 있다.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "미래가 안개 낀 것처럼 흐릿하다.",
	ANNOUNCE_MAPWRAP_RETURN = "다리에 뭔가 스치고 지나간 것 같다...",
	ANNOUNCE_CRAB_ESCAPE = "여기에 있었던 것 같은데...",
	ANNOUNCE_TRAWL_FULL = "어망이 가득 찼다!",
	ANNOUNCE_BOAT_DAMAGED = "물이 새는 것 같다.",
	ANNOUNCE_BOAT_SINKING = "가라앉는 것 같다.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "육지에 가야 한다!",
	ANNOUNCE_WAVE_BOOST = "슈악!",

	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "거품을 쫓아가자!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "어디에 갔을까...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "물이 너무 거칠다!",


	BATTLECRY =
	{
		GENERIC = "눈을 공격해!",
		PIG = "이리 와, 돼지야!",
		PREY = "널 파괴하겠어!",
		SPIDER = "널 밟아 죽이겠어!",
		SPIDER_WARRIOR = "나보단 네가 당하는 것이 낫지!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "본때를 보였다!",
		PIG = "놓아주지. 이번엔.",
		PREY = "너무 빠르다!",
		SPIDER = "어차피 너무 징그러워.",
		SPIDER_WARRIOR = "꺼져, 못된 것!",
	},

	DESCRIBE =
	{
        WILDBOREGUARD = "무엇을 지키고 있나?",
        GLOMMER = "징그러우면서 귀엽다.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "꽃잎이 빛을 받으면 반짝인다.",
        	DEAD = "꽃잎이 빛을 받으면 처지고 반짝인다.",
        },
        GLOMMERWINGS = "투구에 달면 멋있다는 증거가 있다!",
        GLOMMERFUEL = "이 덩이는 악취가 난다.",
        BELL = "땡땡땡.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "저게 무엇인지 잘 모르겠다.",
        	EMPTY = "내가 망가뜨렸다. 과학을 위하여.",
    	},

		LAVA_POND_ROCK = "돌이 있는 곳이다.",
		LAVA_POND_ROCK2 = "돌이 있는 곳이다.",
		LAVA_POND_ROCK3 = "돌이 있는 곳이다.",
		LAVA_POND_ROCK4 = "돌이 있는 곳이다.",
		LAVA_POND_ROCK5 = "돌이 있는 곳이다.",
		LAVA_POND_ROCK6 = "돌 같은 곳이다.",
		LAVA_POND_ROCK7 = "돌이 있는 곳이다.",

		WEBBERSKULL = "불쌍한 놈. 제대로 장례를 받아야 할 텐데.",
		WORMLIGHT = "맛있어 보인다.",
		WORMLIGHT_LESSER = "좀 쭈글하다.",
		WORM =
		{
		    PLANT = "안전해 보인다.",
		    DIRT = "흙 더미로 보일 뿐이다.",
		    WORM = "벌레다!",
		},
		WORMLIGHT_PLANT = "안전해 보인다.",
		MOLE =
		{
			HELD = "더 이상 팔 곳이 없어, 친구.",
			UNDERGROUND = "저 아래에서 뭔가가 광물을 찾고 있다.",
			ABOVEGROUND = "저 두더지 같은 것을... 때리고 싶다.",
		},
		MOLEHILL = "집으로 만들기에 좋은 땅 구멍이다!",
		MOLEHAT = "냄새는 고약하지만 가시성은 훌륭하다.",

		EEL = "맛있는 식사가 되겠지.",
		EEL_COOKED = "냄새 좋다!",
		UNAGI = "장어스럽다!",
		EYETURRET = "날 배신하지 않길 바란다.",
		EYETURRET_ITEM = "자고 있는 것 같다.",
		MINOTAURHORN = "휴우! 나를 꿰뚫지 않아서 다행이다!",
		MINOTAURCHEST = "더 크고 굉장한 것이 들어있을 것 같다! 아니면 끔찍한 것일까.",
		THULECITE_PIECES = "작은 툴레사이트 덩어리다.",
		POND_ALGAE = "연못가에 조류가 있다.",
		GREENSTAFF = "도움이 되겠지.",
		POTTEDFERN = "단지 안에 든 양치류.",

		THULECITE = "어디에서 온 것일까?",
		ARMORRUINS = "이상하게 가볍다.",
		RUINS_BAT = "꽤 묵직하다.",
		RUINSHAT = "머리카락이 어떻지?",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "좋은 상태다.",
			WARN = "마법이 점점 느껴진다.",
			WAXING = "더 집중되고 있는 것 같다!",
			STEADY = "안정성을 유지하는 것 같다.",
			WANING = "감퇴하는 느낌이다.",
			DAWN = "악몽이 거의 떠났다!",
			NOMAGIC = "여기엔 마법이 없다.",
		},
		BISHOP_NIGHTMARE = "산산조각나고 있다!",
		ROOK_NIGHTMARE = "겁난다!",
		KNIGHT_NIGHTMARE = "나이트메어다!",
		MINOTAUR = "행복해 보이지 않는다.",
		SPIDER_DROPPER = "위를 보지 말자.",
		NIGHTMARELIGHT = "무슨 기능을 할까.",
		NIGHTSTICK = "전기다!",
		GREENGEM = "녹색이고 보석인 듯.",
		RELIC = "Ancient household goods.",
		RUINS_RUBBLE = "This can be fixed.",
		MULTITOOL_AXE_PICKAXE = "찬란하다!",
		ORANGESTAFF = "걷는 것보다 낫다.",
		YELLOWAMULET = "촉감이 따뜻하다.",
		GREENAMULET = "더 좋아질 수 없을 것이라고 생각했는데.",
		SLURPERPELT = "죽어도 별로 달라 보이지 않는다.",		

		SLURPER = "털이 너무 많다!",
		SLURPER_PELT = "죽어도 별로 달라 보이지 않는다.",	
		ARMORSLURPER = "축축하고, 기운을 주고, 즙이 많은 슈트.",
		ORANGEAMULET = "원격이동은 정말 유용하다.",
		YELLOWSTAFF = "막대에 보석 박았다.",
		YELLOWGEM = "이 보석은 노란색.",
		ORANGEGEM = "주황색 보석이다.",
		TELEBASE = 
		{
			VALID = "It's ready to go.",
			GEMS = "It needs more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks ready.",
			GEMS = "It needs a gem.",
		},
		STAFFLIGHT = "정말 위험해 보인다.",
	
        ANCIENT_ALTAR = "오래된 신비로운 구조물.",

        ANCIENT_ALTAR_BROKEN = "부서진 것 같다.",

        ANCIENT_STATUE = "세계와는 다른 리듬이 느껴진다.",

        LICHEN = "이 빛으로는 남세균만 자랄 수 있다.",
		CUTLICHEN = "영양가 있지만 오래 가진 않겠지.",

		CAVE_BANANA = "물컹하다.",
		CAVE_BANANA_COOKED = "냠!",
		CAVE_BANANA_TREE = "수상쩍게 광합성이다.",
		ROCKY = "갈고리 발톱이 끔찍하다.",
		
		COMPASS =
		{
			GENERIC="어떤 방향인가?",
			N = "북.",
			S = "남.",
			E = "동.",
			W = "서.",
			NE = "북동.",
			SE = "남동.",
			NW = "북서.",
			SW = "남서.",
		},

		HOUNDSTOOTH="날카롭다!",
		ARMORSNURTLESHELL="등에 달라붙는다.",
		BAT="악! 무서운 거다!",
		BATBAT = "I bet I could fly if I held two of them.",
		BATWING="이것들은 죽었어도 싫다.",
		BATWING_COOKED="적어도 돌아오진 않으니까.",
		BATCAVE = "깨우고 싶지 않다.",
		BEDROLL_FURRY="아주 따뜻하고 포근하다.",
		BUNNYMAN="과학을 하고 싶은 욕망이 불끈 일고 있다.",
		FLOWER_CAVE="과학이 빛나게 한다.",
		FLOWER_CAVE_DOUBLE="과학이 빛나게 한다.",
		FLOWER_CAVE_TRIPLE="과학이 빛나게 한다.",
		GUANO= "다른 맛의 똥이다.",
		LANTERN= "더 품위 있는 빛.",
		LIGHTBULB= "이상하게 맛있어 보인다.",
		MANRABBIT_TAIL= "쥐고 있는 것이 기분 좋다.",
		MUSHTREE_TALL  = "That mushroom got too big for its own good.",
		MUSHTREE_MEDIUM= "These used to grow in my bathroom.",
		MUSHTREE_SMALL = "A magic mushroom?",
		MUSHTREE_TALL =
		{
            GENERIC = "버섯이 너무 커져 버렸다.",
            BLOOM = "멀리선 모르겠지만 악취가 좀 난다.",
        },
		MUSHTREE_MEDIUM = 
		{
            GENERIC = "내 화장실에서 이런 것이 자랐었는데.",
            BLOOM = "좀 불쾌하다.",
        },
		MUSHTREE_SMALL = 
		{
            GENERIC = "마법 버섯?",
            BLOOM = "번식하려고 한다.",
        },
        MUSHTREE_TALL_WEBBED = "거미들이 중요하게 생각한 것이다.",
        SPORE_TALL = "부유한다.",
        SPORE_MEDIUM = "떠 다닐 뿐이다.",
        SPORE_SMALL = "떠 다니고 있다.",
        SPORE_TALL_INV = "주머니에 넣는 작은 불이다.",
        SPORE_MEDIUM_INV = "주머니에 두는 작은 빛.",
        SPORE_SMALL_INV = "주머니에 빛을 둔다.",
		RABBITHOUSE=
		{
			GENERIC = "진짜 당근이 아니다.",
			BURNT = "진짜 구운 당근이 아니다.",
		},
		SLURTLE="우웩. 우웩이다.",
		SLURTLE_SHELLPIECES="해결책이 없는 퍼즐.",
		SLURTLEHAT= "내 헤어스타일을 망치지 않았으면 좋겠는데.",
		SLURTLEHOLE= "'우웩' 소리 나오는 곳이다.",
		SLURTLESLIME= "유용하지 않으면 건드리지도 않을 텐데.",
		SNURTLE= "덜 징그럽지만, 그래도 징그럽다.",
		SPIDER_HIDER= "으앗! 거미가 더 있다!",
		SPIDER_SPITTER= "거미가 싫다!",
		SPIDERHOLE= "오래된 거미줄이 얽혀 있다.",
		SPIDERHOLE_ROCK = "오래된 거미줄이 얽혀 있다.",
		STALAGMITE= "돌로 보이는데.",
		STALAGMITE_FULL= "돌로 보이는데.",
		STALAGMITE_LOW= "돌로 보인다.",
		STALAGMITE_MED= "돌로 보이는데.",
		STALAGMITE_TALL= "바위, 바위, 바위, 바위...",
		STALAGMITE_TALL_FULL= "바위, 바위, 바위, 바위...",
		STALAGMITE_TALL_LOW= "바위, 바위, 바위, 바위...",
		STALAGMITE_TALL_MED= "바위, 바위, 바위, 바위...",

		TURF_CARPETFLOOR = "은근히 긁힌다.",
        TURF_CHECKERFLOOR = "꽤 근사하다.",
		TURF_DIRT = "A chunk of ground.",
		TURF_FOREST = "A chunk of ground.",
		TURF_GRASS = "A chunk of ground.",
		TURF_MARSH = "A chunk of ground.",
		TURF_ROAD = "Hastily cobbled stones.",
		TURF_ROCKY = "A chunk of ground.",
		TURF_SAVANNA = "A chunk of ground.",
		TURF_WOODFLOOR = "바닥 널이다.",

		TURF_CAVE="또 다른 지형이다.",
		TURF_FUNGUS="또 다른 지형이다.",
		TURF_SINKHOLE="또 다른 지형이다.",
		TURF_UNDERROCK="또 다른 지형이다.",
		TURF_MUD="또 다른 지형이다.",

		TURF_DECIDUOUS = "또 다른 지형이다.",
		TURF_SANDY = "또 다른 지형이다.",
		TURF_BADLANDS = "또 다른 지형이다.",
		TURF_DESERTDIRT = "A chunk of ground.",
		TURF_FUNGUS_GREEN = "A chunk of ground.",
		TURF_FUNGUS_RED = "A chunk of ground.",
		TURF_DRAGONFLY = "내화성을 확인할까요?",

		POWCAKE = "그 정도로 배고프진 않은 것 같다.",
        CAVE_ENTRANCE = 
        {
            GENERIC="저 바위를 움직일 수 있을까.",
            OPEN = "저 아래에서 발견할 것이 많겠지.",
        },
        CAVE_EXIT = "I've had enough discovery for now.",
        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "땅 자체가 날 거부한다!",
            OPEN = "저 아래에서 발견할 것이 많겠지.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "지금은 여기에 있어야겠다.",
            OPEN = "이제 발견하는 것이 지쳤다.",
        },
		MAXWELLPHONOGRAPH = "저기에서 음악이 들려 온 것이었군.",
		BOOMERANG = "공기역학의 승리!",
		PIGGUARD = "다른 것들처럼 친근해 보이지 않는다.",
		ADVENTURE_PORTAL = "두 번 들어가고 싶지는 않은데.",
		AMULET = "착용하고 있으면 무척 안전하게 느껴진다.",
		ANIMAL_TRACK = "음식이 남긴 자국. 아니... 동물이 남긴.",
		ARMORGRASS = "안에 벌레가 없길 바란다.",
		ARMORMARBLE = "정말 무거워 보인다.",
		ARMORWOOD = "완벽하게 합리적인 의류다.",
		ARMOR_SANITY = "이걸 쓰면 안전하고 불안하게 느끼겠지.",
		ASH =
		{
			GENERIC = "불타고 남은 것뿐이다.",
			REMAINS_GLOMMERFLOWER = "원격이동했을 때 꽃이 타버렸다!",
			REMAINS_EYE_BONE = "원격이동했을 때 눈뼈가 타버렸다!",
			REMAINS_THINGIE = "이에 대한 완벽하게 과학적인 설명이 있지.",
		},
		AXE = "믿음직한 도끼.",
		BABYBEEFALO = "오호. 너무 귀엽다!",
		BACKPACK = "과학적인 것이 잔뜩 들어간다.",
		BACONEGGS = "과학자의 완벽한 아침식사.",
		BANDAGE = "적당히 무균인 것 같다.",
		BASALT = "너무 강해서 부술 수 없다!",
		BATBAT = "이걸 두 개 들면 날 수 있겠지.",
		BEARDHAIR = "내 얼굴로 만들었다.",
		BEARGER = "곰 같은 오소리다.",
		BEARGERVEST = "동면 스테이션에 온 것을 환영합니다!",
		ICEPACK = "털이 내부 온도를 안정화한다.",
		BEARGER_FUR = "두꺼운 털 거적.",
		BEDROLL_STRAW = "편하지만 곰팡내난다.",
		BEE =
		{
			GENERIC = "벌이거나 벌이 아니거나.",
			HELD = "조심!",
		},
		BEEBOX =
		{
			FULLHONEY = "꿀이 가득 있다.",
			GENERIC = "벌이구나!",
			NOHONEY = "비어있다.",
			SOMEHONEY = "좀 기다려야겠다.",
			BURNT = "왜 탔지?!!",
		},
		BEEFALO =
		{
			FOLLOWER = "평온하게 따라오고 있다.",
			GENERIC = "고기물소다!",
			NAKED = "어, 무척 슬퍼하고 있구나.",
			SLEEPING = "정말 깊게 잠을 자고 있다.",
		},
		BEEFALOHAT = "머리카락이 모자에 눌리겠다.",
		BEEFALOWOOL = "고기물소 눈물 냄새가 난다.",
		BEEHAT = "피부를 보호하지만 머리카락을 누른다.",
		BEEHIVE = "활동이 많다.",
		BEEMINE = "흔들면 윙윙거리는 소리가 난다.",
		BEEMINE_MAXWELL = "병에 든 모기의 분노!",
		BERRIES = "빨간 베리가 가장 맛있는걸.",
		BERRIES_COOKED = "가열해서 더 좋아진 것 같진 않다.",
		BERRYBUSH =
		{
			BARREN = "비료가 필요한 것 같다.",
			WITHERED = "열 때문에 아무 것도 못 자란다.",
			GENERIC = "빨간 베리가 가장 맛있는걸.",
			PICKED = "다시 자라지 않을까?",
		},
		BIGFOOT = "굉장히 큰 발이다.",
		BIRDCAGE =
		{
			GENERIC = "안에 새를 넣어야겠다.",
			OCCUPIED = "내가 새 주인이다!",
			SLEEPING = "오호, 자고 있네.",
			HUNGRY = "배고파 보인다.",
			STARVING = "너를 최근에 안 먹였나?",
			DEAD = "쉬고 있는 것일까?",
			SKELETON = "새가 분명히 사망했다.",
		},
		BIRDTRAP = "탁월한 우위!",
		CAVE_BANANA_BURNT = "내 잘못이 아니다!",
		BIRD_EGG = "작은 평범한 알.",
		BIRD_EGG_COOKED = "노른자가 맛있다!",
		BISHOP = "물러서라, 설교자!",
		BLOWDART_FIRE = "근본적으로 안전해 보이지 않는다.",
		BLOWDART_SLEEP = "들이쉬지 않도록 한다.",
		BLOWDART_PIPE = "생일 케이크를 불기 위한 좋은 연습!",
		BLUEAMULET = "얼음처럼 차갑다!",
		BLUEGEM = "냉기가 깜박거리며 빛난다.",
		BLUEPRINT = "과학적이다!",
		BELL_BLUEPRINT = "과학적이다!",
		BLUE_CAP = "이상하고 끈적거린다.",
		BLUE_CAP_COOKED = "지금은 다른데...",
		BLUE_MUSHROOM =
		{
			GENERIC = "버섯이다.",
			INGROUND = "자고 있습니다.",
			PICKED = "다시 돌아올까?",
		},
		BOARDS = "판자.",
		BOAT = "저 것으로 제가 온 건가요?",
		BONESHARD = "뼈 조각.",
		BONESTEW = "내 뼈에 살을 붙여줄 스튜다.",
		BUGNET = "벌레 잡는 용이다.",
		BUSHHAT = "좀 가렵다.",
		BUTTER = "버터인 것을 믿을 수 없어!",
		BUTTERFLY =
		{
			GENERIC = "나비야, 날아라.",
			HELD = "이제 널 잡았다!",
		},
		BUTTERFLYMUFFIN = "레서피를 버리고 대충 만들었다.",
		BUTTERFLYWINGS = "이게 없다면 버터만 있는 거다.",
		BUZZARD = "기괴한 말똥가리다!",
		CACTUS = 
		{
			GENERIC = "뾰족하지만 맛있다.",
			PICKED = "부피는 줄었지만 그래도 가시는 많다.",
		},
		CACTUS_MEAT_COOKED = "사막의 구운 과일.",
		CACTUS_MEAT = "맛있지만 가시가 걸린다.",
		CACTUS_FLOWER = "가시 많은 식물의 예쁜 꽃.",

		COLDFIRE =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "캄캄한 것보단 훨씬 좋다.",
			HIGH = "불이 너무 크다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "따뜻해서 좋다.",
			OUT = "끝났습니다.",
		},
		CAMPFIRE =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "캄캄한 것보단 훨씬 좋다.",
			HIGH = "불이 너무 크다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "따뜻해서 좋다.",
			OUT = "끝났습니다.",
		},
		CANE = "걷는 것을 훨씬 쉽게 만든다!",
		CATCOON = "작은 게 잘 논다.",
		CATCOONDEN = 
		{
			GENERIC = "그루터기 안의 굴이다.",
			EMPTY = "주인의 생명력이 떨어졌다.",
		},
		CATCOONHAT = "귀 모자!",
		COONTAIL = "아직도 꼬리를 휘두르는 것 같다.",
		CARROT = "윽. 흙에서 채소를 꺼냈다.",
		CARROT_COOKED = "물컹하다.",
		CARROT_PLANTED = "땅이 식물아기를 만들고 있다.",
		CARROT_SEEDS = "당근 씨다.",
		WATERMELON_SEEDS = "멜론 씨다.",
		CAVE_FERN = "양치류다.",
		CHARCOAL = "작고, 어둡고, 탄 나무 냄새가 난다.",
        CHESSJUNK1 = "부서진 체스 말 더미.",
        CHESSJUNK2 = "또 다른 부서진 체스 말 더미.",
        CHESSJUNK3 = "더 많은 부서진 체스 말 더미.",
		CHESTER = "오토 폰 체스터필드 님",
		CHESTER_EYEBONE =
		{
			GENERIC = "나를 보고 있잖아.",
			WAITING = "잠들었다.",
		},
		COOKEDMANDRAKE = "불쌍한 놈.",
		COOKEDMEAT = "완벽하게 그을리고 구웠다.",
		COOKEDMONSTERMEAT = "날것이었을 때보다 조금만 더 맛있다.",
		COOKEDSMALLMEAT = "이제 기생충에 걸릴 걱정은 없다!",
		COOKPOT =
		{
			COOKING_LONG = "시간이 꽤 걸릴 것이다.",
			COOKING_SHORT = "거의 다 됐다!",
			DONE = "냠냠! 먹을 준비가 되었다!",
			EMPTY = "보는 것만으로도 배고프다.",
			BURNT = "냄비가 요리되어 버렸다.",
		},
		CORN = "과당 함량이 높다!",
		CORN_COOKED = "요리했는데 과당 함량이 높다!",
		CORN_SEEDS = "옥수수 씨다.",
		CROW =
		{
			GENERIC = "소름 끼쳐!",
			HELD = "안에 있는 것이 행복해 보이지 않는다.",
		},
		CUTGRASS = "자른 풀은 공예 준비물.",
		CUTREEDS = "자른 갈대는 공작과 취미 생활에 쓸 수 있다.",
		CUTSTONE = "아주 반들반들하게 만들었다.",
		DEADLYFEAST = "가장 강력한 요리다.",
		DEERCLOPS = "거대해!!",
		DEERCLOPS_EYEBALL = "정말 징그럽다.",
		EYEBRELLAHAT =	"날 넘보겠지.",
		DEPLETED_GRASS =
		{
			GENERIC = "풀 덤불인 것 같잖아.",
		},
		DEVTOOL = "베이컨 냄새가 난다!",
		DEVTOOL_NODEV = "이것을 사용할 정도로 강하지 않다.",
		DIRTPILE = "흙더미이다... 인가?",
		DIVININGROD =
		{
			COLD = "신호가 미약하다.",
			GENERIC = "자동 유도 장치인 것 같다.",
			HOT = "광폭 상태다!",
			WARM = "올바른 방향으로 가고 있다.",
			WARMER = "가까워지는 것 같다.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "어떤 기능이 있을까.",
			READY = "큰 열쇠가 필요한 것 같다.",
			UNLOCKED = "이제 내 기계를 작동할 수 있다!",
		},
		DIVININGRODSTART = "저 막대가 유용해 보인다!",
		DRAGONFLY = "용 파리다!",
		ARMORDRAGONFLY = "멋진 갑옷!",
		DRAGON_SCALES = "아직도 따뜻하다.",
		DRAGONFLYCHEST = "자물쇠 달린 상자가 없다면 이것이라도!",
		LAVASPIT = 
		{
			HOT = "뜨거운 침!",
			COOL = "이를 '바살리바'라고 부른다.",
		},
		LAVA_POND = "마그마다!",
		LAVAE = "다루기가 너무 뜨겁다.",
		LAVAE_PET = 
		{
			STARVING = "불쌍한 게 굶주린 모양이다.",
			HUNGRY = "희미하게 배고픈 소리가 들린다.",
			CONTENT = "행복해 보인다.",
			GENERIC = "이야. 귀여운 괴물이잖아?",
		},
		LAVAE_EGG = 
		{
			GENERIC = "안에서 희미한 따스함이 번져나온다.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "알이 충분이 따뜻하지 않다.",
			COMFY = "행복한 알을 만날 줄은 몰랐다.",
		},
		LAVAE_TOOTH = "알 이빨이다!",

		DRAGONFRUIT = "이상한 과일이다.",
		DRAGONFRUIT_COOKED = "그래도 이상한 과일이다.",
		DRAGONFRUIT_SEEDS = "이상한 과일 씨앗이다.",
		DRAGONPIE = "용과는 배부르게 한다.",
		DRUMSTICK = "게걸스럽게 먹어야겠다.",
		DRUMSTICK_COOKED = "이제 더 맛있다.",
		DUG_BERRYBUSH = "이제 어디로든 가져갈 수 있다.",
		DUG_GRASS = "심어야 한다.",
		DUG_MARSH_BUSH = "심어야지.",
		DUG_SAPLING = "집 근처에 다시 심을 수 있겠다.",
		DURIAN = "냄새난다!",
		DURIAN_COOKED = "냄새가 더 고약해졌다!",
		DURIAN_SEEDS = "두리안 씨다.",
		EARMUFFSHAT = "적어도 귀는 춥지 않겠지...",
		EGGPLANT = "알 같아 보이지 않는다.",
		EGGPLANT_COOKED = "더욱 더 알 같지 않다.",
		EGGPLANT_SEEDS = "가지 씨다.",
		DECIDUOUSTREE = 
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			POISON = "내가 버치넛을 훔쳐서 언짢아 보인다!",
			GENERIC = "잎이 무성하다. 대개는.",
		},
		ACORN = 
		{
		    GENERIC = "안에 분명히 뭔가 있다.",
		    PLANTED = "금방 나무가 되겠지!",
		},
		ACORN_COOKED = "완벽하게 구웠다.",
		BIRCHNUTDRAKE = "미친 작은 너트.",
		EVERGREEN =
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "소나무스럽다.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "이 슬픈 나무는 방울이 없다.",
		},
		EYEPLANT = "누가 보고 있는 것 같다.",
		FARMPLOT =
		{
			GENERIC = "농작물을 심어야겠다.",
			GROWING = "열심히 자라라, 식물아!",
			NEEDSFERTILIZER = "비료가 필요한 것 같다.",
			BURNT = "잿더미에서 재배할 수 있는 것은 없겠지.",
		},
		FEATHERHAT = "새가 됐다!",
		FEATHER_CROW = "까마귀 깃털.",
		FEATHER_ROBIN = "피리새 깃털.",
		FEATHER_ROBIN_WINTER = "흰머리멧새 깃털.",
		FEM_PUPPET = "잡혔잖아!",
		FIREFLIES =
		{
			GENERIC = "저걸 잡을 수만 있다면!",
			HELD = "내 주머니를 빛나게 한다!",
		},
		FIREHOUND = "저건 빛나고 있다.",
		FIREPIT =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "캄캄한 것보단 훨씬 좋다.",
			HIGH = "번지지 않을 테니 다행이다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "따뜻해서 좋다.",
			OUT = "적어도 다시 켤 수 있다.",
		},
		COLDFIREPIT =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "캄캄한 것보단 훨씬 좋다.",
			HIGH = "번지지 않을 테니 다행이다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "따뜻해서 좋다.",
			OUT = "적어도 다시 켤 수 있다.",
		},
		FIRESTAFF = "세상을 불지르고 싶진 않다.",
		FIRESUPPRESSOR = 
		{	
			ON = "던져라!",
			OFF = "그만 던진다.",
			LOWFUEL = "연료 탱크가 많이 줄어들고 있다.",
		},

		FISH = "이제 하루 먹을 수 있다.",
		FISHINGROD = "바늘, 줄, 막대기!",
		FISHSTICKS = "갈비뼈에 붙는다.",
		FISH_MED = "착하지.",
		FISH_MED_COOKED = "완벽하게 구웠다.",
		FISHTACOS = "바삭하고 맛있다!",
		FISH_COOKED = "완벽하게 구웠다.",
		FLINT = "무척 날카로운 바위다.",
		FLOWER = "예쁘지만 육체노동자의 냄새가 난다.",
		FLOWERHAT = "예쁜 향이 난다.",
		FLOWER_EVIL = "으악! 아주 사악하다!",
		FOLIAGE = "무성한 잎.",
		FOOTBALLHAT = "난 스포츠를 안 좋아해.",
		FROG =
		{
			DEAD = "꼴까닥이다.",
			GENERIC = "정말 귀엽다!",
			SLEEPING = "오호, 자는 것 봐!",
		},
		FROGGLEBUNWICH = "긴 다리 샌드위치다.",
		FROGLEGS = "진미라고 들었다.",
		FROGLEGS_COOKED = "닭고기 맛이다.",
		FRUITMEDLEY = "과육이다.",
		FURTUFT = "검고 흰 털.", 
		GEARS = "기계 부품 더미.",
		GHOST = "과학자에 대한 모욕이다.",
		GOLDENAXE = "고급스러운 도끼다.",
		GOLDENPICKAXE = "금은 연한 금속 아니었나?",
		GOLDENPITCHFORK = "내가 왜 이렇게 고급스러운 쇠스랑을 만들었을까?",
		GOLDENSHOVEL = "땅 파고 싶게 만든다.",
		GOLDNUGGET = "먹을 수는 없지만 광택이 대단하다.",
		GRASS =
		{
			BARREN = "똥이 필요해.",
			WITHERED = "너무 더울 때는 다시 자라지 않을 것이다.",
			BURNING = "빨리 타고 있다!",
			GENERIC = "풀 덤불이다.",
			PICKED = "삶이 가장 창창할 때 잘렸다.",
		},
		GREEN_CAP = "꽤 평범해 보인다.",
		GREEN_CAP_COOKED = "지금은 다른데...",
		GREEN_MUSHROOM =
		{
			GENERIC = "버섯이다.",
			INGROUND = "자고 있습니다.",
			PICKED = "다시 돌아올까?",
		},
		GUNPOWDER = "후추처럼 보인다.",
		HAMBAT = "비위생적으로 보인다.",
		HAMMER = "멈춰! 때가 왔다! 망치 시간!",
		HEALINGSALVE = "따끔한 느낌은 효과가 있다는 표시다.",
		HEATROCK =
		{
			FROZEN = "얼음보다 차갑다.",
			COLD = "참 차가운 돌이다.",
			GENERIC = "온도를 조절할 수 있을 것 같다.",
			WARM = "따뜻해서 안고 싶다... 돌 치고는!",
			HOT = "따끈따끈해서 좋다!",
		},
		HOME = "누군가 여기에 사는 것 같다.",
		HOMESIGN = 
		{
			GENERIC = "'너는 여기에 있다'라고 써있다.",
			UNWRITTEN = "현재는 비어있는 표지판이다.",
			BURNT = "더 읽을 수 없다.",
		},
		HONEY = "맛있어 보인다!",
		HONEYCOMB = "여기에 벌들이 살았었다.",
		HONEYHAM = "새콤달콤이다.",
		HONEYNUGGETS = "닭 같다, 하지만 아니다.",
		HORN = "고기물소 들판인 것으로 들린다.",
		HOUND = "넌 아무 것도 아냐, 하운드 독!",
		HOUNDBONE = "소름 끼친다.",
		HOUNDMOUND = "이들의 뼈를 가져갈 생각은 없다.",
		ICEBOX = "냉기의 힘을 끌어모았다!",
		ICEHAT = "쿨하게 지내자.",
		ICEHOUND = "모든 계절에 어울리는 개가 있는 건가?",
		INSANITYROCK =
		{
			ACTIVE = "받아라, 멀쩡한 이성!",
			INACTIVE = "방첨탑이라기보다는 피라미드다.",
		},
		JAMMYPRESERVES = "병을 만들었어야 한다.",
		KABOBS = "막대기에 달린 점심.",
		KILLERBEE =
		{
			GENERIC = "아니! 살인벌이다!",
			HELD = "위험해 보인다.",
		},
		KNIGHT = "멋지다!",
		KOALEFANT_SUMMER = "귀여운 것이 맛도 좋다.",
		KOALEFANT_WINTER = "따뜻하고 고기가 가득 든 것 같다.",
		KRAMPUS = "내 것을 가져가려고 한다!",
		KRAMPUS_SACK = "우웩. 크램퍼스 점액이 뒤덮여있다.",
		LEIF = "거대하다!",
		LEIF_SPARSE = "거대하다!",
		LIGHTNING_ROD =
		{
			CHARGED = "힘은 나의 것!",
			GENERIC = "하늘의 힘을 쓸 수 있다!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "너나 '메에'해라!",
			CHARGED = "벼락에 맞은 걸 좋아하는 것 같진 않다.",
		},
		LIGHTNINGGOATHORN = "소형 피뢰침 같다.",
		GOATMILK = "짜릿하게 맛있다!",
		LITTLE_WALRUS = "영영 귀엽고 안아주고 싶은 상태로 남지 않겠지.",
		LIVINGLOG = "걱정스러워 보인다.",
		LOCKEDWES = "맥스웰의 조각상이 그를 가둬 두고 있다.",
		LOG =
		{
			BURNING = "뜨거운 나무다!",
			GENERIC = "크고, 무겁고, 나무다.",
		},
		LUREPLANT = "너무 유혹적이다.",
		LUREPLANTBULB = "이제 나만의 고기 농장을 시작할 수 있다.",
		MALE_PUPPET = "잡혔다!",
		MANDRAKE =
		{
			DEAD = "맨드레이크 뿌리는 이상한 효과가 있다.",
			GENERIC = "이 식물에 대한 이상한 이야기를 들었다.",
			PICKED = "날 따라오지 마!",
		},
		MANDRAKESOUP = "다시 안 일어나겠다.",
		MANDRAKE_COOKED = "더는 이상해 보이지 않는다.",
		MARBLE = "멋지다!",
		MARBLEPILLAR = "쓸모 있을 것 같다.",
		MARBLETREE = "도끼로 자를 수 없을 것 같다.",
		MARSH_BUSH =
		{
			BURNING = "빨리 타고 있다!",
			GENERIC = "가시가 많아 보인다.",
			PICKED = "아파.",
		},
		BURNT_MARSH_BUSH = "다 탔잖아.",
		MARSH_PLANT = "잡풀이야.",
		MARSH_TREE =
		{
			BURNING = "가시와 불!",
			BURNT = "이제 타고 뾰족한 것만 남았다.",
			CHOPPED = "더 이상 안 뾰족하다!",
			GENERIC = "가시가 뾰족해 보인다!",
		},
		MAXWELL = "저 놈이 싫다.",
		MAXWELLHEAD = "털구멍이 보인다.",
		MAXWELLLIGHT = "어떻게 작동하는 걸까.",
		MAXWELLLOCK = "열쇠 구멍으로 보인다.",
		MAXWELLTHRONE = "그리 편해 보이지 않는다.",
		MEAT = "질기지만 이게 어디냐.",
		MEATBALLS = "내가 직접 요리했어!",
		MEATRACK =
		{
			DONE = "육포 만들 시간!",
			DRYING = "고기는 건조하는 데 시간이 꽤 걸린다.",
			DRYINGINRAIN = "비 오면 고기 말리는 시간이 더 오래 걸린다.",
			GENERIC = "고기를 말려야겠다.",
			BURNT = "걸이 자체가 말라 버렸다.",
		},
		MEAT_DRIED = "딱 육포다.",
		MERM = "비린내 난다!",
		MERMHEAD = 
		{
			GENERIC = "오늘의 최악의 냄새.",
			BURNT = "어쩐지 탄 어인 살의 냄새는 더 고약하다.",
		},
		MERMHOUSE = 
		{
			GENERIC = "누가 이런 끔찍한 곳에 살까?",
			BURNT = "더 이상 살 곳이 없다.",
		},
		MINERHAT = "핸즈프리 빛이다.",
		MONKEY = "호기심 많은 작은 놈.",
		MONKEYBARREL = "방금 움직였나?",
		MONSTERLASAGNA = "과학에 대한 모독이다.",
		FLOWERSALAD = "잎 한 사발.",
        ICECREAM = "아이스크림 먹자!",
        WATERMELONICLE = "극저온 수박이다.",
        TRAILMIX = "건강한 천연 스낵.",
        HOTCHILI = "경보기 다섯 개!",
        GUACAMOLE = "아보가드로가 좋아하는 요리.",
		MONSTERMEAT = "윽. 저걸 먹어선 안 될 것 같다.",
		MONSTERMEAT_DRIED = "이상한 냄새가 나는 육포.",
		MOOSE = "저게 무엇인지 잘 모르겠다.",
		MOOSE_NESTING_GROUND = "아기 놓는 곳이다.",
		MOOSEEGG = "자극 받은 전자가 탈출하려고 하는 것처럼 내용물이 보인다.",
		MOSSLING = "아! 너는 전자가 아니잖아!",
		FEATHERFAN = "체온을 내려줄 깃털.",
		MINIFAN = "뒤에서 바람이 두 배로 빨리 부는 것 같다.",
		TROPICALFAN = "뒤로 바람이 두 배로 세게 나온다.",
		GOOSE_FEATHER = "복슬복슬하거든!",
		STAFF_TORNADO = "파멸을 위한 회전.",
		MOSQUITO =
		{
			GENERIC = "역겨운 조그만 흡혈 동물.",
			HELD = "야, 내 피냐?",
		},
		MOSQUITOSACK = "다른 사람의 피가 아니겠지...",
		MOUND =
		{
			DUG = "아마 죄책감을 느껴야 할 것 같지만.",
			GENERIC = "저 아래에 좋은 것이 많겠지!",
		},
		NIGHTLIGHT = "으스스한 빛을 발한다.",
		NIGHTMAREFUEL = "정말 괴상한 것이다!",
		NIGHTSWORD = "내 꿈에서 나온 것이다!",
		NITRE = "나는 지질학자가 아니다.",
		ONEMANBAND = "고기물소 벨을 달 걸 그랬다.",
		PANDORASCHEST = "굉장한 것이 들어있을 것 같다! 아니면 끔찍한 것일까.",
		PANFLUTE = "동물을 위한 소야곡을 연주할 수 있다.",
		PAPYRUS = "종이 몇 장.",
		PENGUIN = "번식기인 것 같다.",
		PERD = "멍텅구리 새야! 내 베리에서 멀찍이 떨어져!",
		PEROGIES = "괜찮게 됐다.",
		PETALS = "꽃에게 본때를 보여줬다!",
		PETALS_EVIL = "이것을 들고 싶은 생각이 안 든다.",
		PHLEGM = "두껍고 유연하고 짜다.",
		PICKAXE = "상징적이지 않나?",
		PIGGYBACK = "아기 돼지가... \"집\"에 갔다.",
		PIGHEAD = 
		{	
			GENERIC = "짐승을 위한 제물이다.",
			BURNT = "파삭파삭하다.",
		},
		PIGHOUSE =
		{
			FULL = "창문에 주둥이가 붙어 있는 것이 보인다.",
			GENERIC = "돼지들이 꽤 좋은 집을 가지고 있다.",
			LIGHTSOUT = "야! 집에 있는 것 알고 있어!",
			BURNT = "이제 전혀 근사하지 않지, 돼지야!",
		},
		PIGKING = "으윽, 냄새 난다!",
		PIGMAN =
		{
			DEAD = "누군가 가족에게 소식을 전해야 하겠다.",
			FOLLOWER = "내 측근이다.",
			GENERIC = "뭔가 소름 끼친다.",
			GUARD = "심각해 보인다.",
			WEREPIG = "친한 돼지가 아니다!!",
		},
		PIGSKIN = "아직도 꼬리가 달려있다.",
		PIGTENT = "베이컨 냄새가 난다.",
		PIGTORCH = "아주 포근해 보인다.",
		PINECONE = 
		{
		    GENERIC = "밖으로 나오고 싶어하는 작은 나무가 안에 있는 것이 들린다.",
		    PLANTED = "금방 나무가 되겠지!",
		},
		LUMPY_SAPLING = "이 나무는 어떻게 재생산될까?",
		PITCHFORK = "맥스웰이 이것을 찾고 있을지도 모른다.",
		PLANTMEAT = "그리 맛있어 보이지 않는다.",
		PLANTMEAT_COOKED = "적어도 따뜻하긴 하다.",
		PLANT_NORMAL =
		{
			GENERIC = "무성하다!",
			GROWING = "윽! 너무 느리게 성장한다!",
			READY = "흠. 수확 준비가 되었다.",
			WITHERED = "열 때문에 죽었다.",
		},
		POMEGRANATE = "외계인의 뇌 안을 보는 것 같다.",
		POMEGRANATE_COOKED = "고급 요리!",
		POMEGRANATE_SEEDS = "석류 씨다.",
		POND = "밑바닥이 안 보인다!",
		POOP = "주머니를 채워야겠다!",
		FERTILIZER = "분명히 똥이 가득 찬 통이다.",
		PUMPKIN = "내 머리만큼 크다!",
		PUMPKINCOOKIE = "맛있는 호박 쿠키다!",
		PUMPKIN_COOKED = "왜 파이가 되지 않았지?",
		PUMPKIN_LANTERN = "으스스해!",
		PUMPKIN_SEEDS = "호박 씨다.",
		PURPLEAMULET = "나에게 속삭이고 있다.",
		PURPLEGEM = "우주의 신비를 담고 있다.",
		RABBIT =
		{
			GENERIC = "당근을 찾고 있다.",
			HELD = "과학을 좋아하나요?",
		},
		RABBITHOLE = 
		{
			GENERIC = "버니맨 왕국으로 이어지는 것 같다.",
			SPRING = "버니맨 왕국이 열리는 철이 아니다.",
		},
		RAINOMETER = 
		{	
			GENERIC = "구름 낀 정도를 측정한다.",
			BURNT = "측정 부품이 연기를 내며 타버렸다.",
		},
		RAINCOAT = "비를 제 자리에 둔다. 내 몸이 아닌 곳에.",
		RAINHAT = "헤어스타일이 망가지겠지만 젖진 않게 해준다.",
		RATATOUILLE = "훌륭한 섬유 공급원이다.",
		RAZOR = "막대기에 달린 날카롭게 만든 돌. 위생적이다!",
		REDGEM = "내적인 따뜻함으로 반짝인다.",
		RED_CAP = "냄새가 요상하네.",
		RED_CAP_COOKED = "지금은 다른데...",
		RED_MUSHROOM =
		{
			GENERIC = "버섯이다.",
			INGROUND = "자고 있습니다.",
			PICKED = "다시 돌아올까?",
		},
		REEDS =
		{
			BURNING = "제대로 타고 있다!",
			GENERIC = "갈대 덤불이다.",
			PICKED = "쓸모 있는 갈대는 다 뽑았다.",
		},
        RELIC = 
        {
            GENERIC = "고대 가재 도구.",
            BROKEN = "여기에는 쓸모 있는 것이 없다.",
        },
        RUINS_RUBBLE = "수리할 수 있겠다.",
        RUBBLE = "돌 조각일 뿐이다.",
		RESEARCHLAB = 
		{	
			GENERIC = "물체를 과학 구성품으로 해체한다.",
			BURNT = "더 이상 과학을 못 한다.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "저번 것보다 더 과학적이다!",
			BURNT = "과학이 더 추가되었는 데도 살지 못했다.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "내가 무엇을 창조했는가?",
			BURNT = "뭐였는지 모르지만 지금은 타버렸어.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "누가 저것에 이름을 붙일까?",
			BURNT = "불은 이름 문제를 해결하지 않는데...",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "미남 악마구나!",
			BURNT = "더 이상 쓸모없다.",
		},
		RESURRECTIONSTONE = "본부를 마련하는 것이 좋다.",
		ROBIN =
		{
			GENERIC = "겨울이 끝났다는 의미인가?",
			HELD = "내 주머니를 좋아한다.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "언 황무지의 삶.",
			HELD = "무척 부드럽다.",
		},
		ROBOT_PUPPET = "잡혔잖아!",
		ROCK_LIGHT =
		{
			GENERIC = "위가 딱딱해진 용암 구덩이야.",
			OUT = "부서지기 쉬워 보인다.",
			LOW = "용암 위쪽이 딱딱해지고 있다.",
			NORMAL = "따뜻해서 좋다.",
		},
		ROCK = "주머니 안에 들어가지 않는다.",
		ROCK_ICE = 
		{
			GENERIC = "외톨이 빙하다.",
			MELTED = "다시 얼지 않으면 쓸모없다.",
		},
		ROCK_ICE_MELTED = "다시 얼지 않으면 쓸모없다.",
		ICE = "반가운 얼음.",
		ROCKS = "이것으로 물건을 만들 수 있다.",
        ROOK = "성을 공격하라!",
		ROPE = "짧은 밧줄.",
		ROTTENEGG = "우욱! 악취가 난다!",
		SANITYROCK =
		{
			ACTIVE = "미치광이 바위다!",
			INACTIVE = "나머지는 어디로 갔지?",
		},
		SAPLING =
		{
			BURNING = "빨리 타고 있다!",
			WITHERED = "더 서늘하면 괜찮을지도 모르겠다.",
			GENERIC = "아기 나무는 너무 귀여워!",
			PICKED = "따끔한 맛을 봐라.",
		},
		SEEDS = "하나하나가 작은 수수께끼다.",
		SEEDS_COOKED = "요리해서 생명을 다 없앴다!",
		SEWING_KIT = "꿰매자! 다 꿰매 버리자!",
		SHOVEL = "지하에 뭔가 많이 이루어지고 있다.",
		SILK = "거미 엉덩이에서 나오는 것.",
		SKELETON = "나보단 네가 당하는 것이 낫다.",
		SCORCHED_SKELETON = "으스스하다.",
		SKELETON_PLAYER = "남이 당하는 것이... 잠깐만!",
		SKULLCHEST = "열고 싶은 생각이 안 든다.",
		SMALLBIRD =
		{
			GENERIC = "꽤 작은 새다.",
			HUNGRY = "배고파 보인다.",
			STARVING = "굶주린 모양이다.",
		},
		SMALLMEAT = "죽은 동물의 작은 조각.",
		SMALLMEAT_DRIED = "작은 육포.",
		SPAT = "껍질스러운 동물이다.",
		SPEAR = "아주 뾰족한 막대기.",
		SPIDER =
		{
			DEAD = "으윽!",
			GENERIC = "거미가 싫다.",
			SLEEPING = "깨어날 때 여기에 있으면 안 되겠다.",
		},
		SPIDERDEN = "들러붙는다!",
		SPIDEREGGSACK = "주머니 안에서 부화하지 않길 바란다.",
		SPIDERGLAND = "톡 쏘는 소독제 냄새가 난다.",
		SPIDERHAT = "거미 점액을 다 닦아냈어야 할 텐데.",
		SPIDERQUEEN = "으악! 정말 큰 거미다!",
		SPIDER_WARRIOR =
		{
			DEAD = "시원하게 없앴다!",
			GENERIC = "평소보다 더 못되어 보인다.",
			SLEEPING = "거리를 두어야겠다.",
		},
		SPOILED_FOOD = "복슬복슬하고 둥근 썩은 음식.",
		STATUEHARP = "머리는 어떻게 되었을까?",
		STATUEMAXWELL = "특성을 잘 포착했다.",
		STEELWOOL = "긁히기 좋은 금속 섬유다.",
		STINGER = "날카로워 보인다!",
		STRAWHAT = "모자는 언제나 내 머리카락을 망친다.",

		TALLBIRD = "아주 큰 새다!",
		TALLBIRDEGG = "부화할까?",
		TALLBIRDEGG_COOKED = "맛과 영양이 있다.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "그것이, 아니면 내가 떨고 있는 것인가!",
			GENERIC = "부화하는 것 같다!",
			HOT = "알이 땀 흘려도 되는 건가?",
			LONG = "시간이 좀 걸릴 것 같은데...",
			SHORT = "금방 부화하겠지.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "대단한 알이다!",
			PICKED = "둥지가 비어있는걸.",
		},
		TEENBIRD =
		{
			GENERIC = "아주 큰 새가 아니다.",
			HUNGRY = "식량을 찾아야겠다.",
			STARVING = "위험해 보이는 눈초리다.",
		},
		TELEBASE =
		{
			VALID = "준비 됐다.",
			GEMS = "자주색 보석이 더 필요하다.",
		},
		GEMSOCKET = 
		{
			VALID = "준비된 것으로 보이잖아.",
			GEMS = "보석이 필요해.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "이것으로 시간과 공간을 통과할 수 있을 거야!",
			GENERIC = "다른 세계로 가는 연결 고리인 것 같다!",
			LOCKED = "아직도 빠진 것이 있다.",
			PARTIAL = "내 발명이 곧 완성될 것이다!",
		},
		TELEPORTATO_BOX = "우주 전체의 극성을 제어할 수 있을 것 같다.",
		TELEPORTATO_CRANK = "극심한 실험도 견딜 정도로 단단하다.",
		TELEPORTATO_POTATO = "이 금속 감자는 위대하고 무시무시한 능력을 가지고 있다...",
		TELEPORTATO_RING = "차원 에너지를 집중할 수 있는 고리.",
		TELESTAFF = "나에게 세계를 보여줄 수 있다.",
		TENT = 
		{
			GENERIC = "잠 안 자면 미칠 것 같다.",
			BURNT = "잘 곳이 남지 않았다.",
		},
		SIESTAHUT = 
		{
			GENERIC = "오후에 열기를 피해 쉴 수 있는 괜찮은 곳이다.",
			BURNT = "이제 그늘이 없다.",
		},
		TENTACLE = "위험해 보인다.",
		TENTACLESPIKE = "뾰족하고 점액투성이인걸.",
		TENTACLESPOTS = "이게 생식기였던 것 같다.",
		TENTACLE_PILLAR = "미끈덩한 기둥.",
		TENTACLE_PILLAR_HOLE = "악취가 나지만 탐험할 가치가 있다.",
		TENTACLE_PILLAR_ARM = "미끌거리는 작은 팔.",
		TENTACLE_GARDEN = "또 다른 미끈덩한 기둥.",
		TOPHAT = "아주 좋은 모자다.",
		TORCH = "밤의 엄습을 막아내는 것.",
		TRANSISTOR = "전기가 웅웅거린다.",
		TRAP = "정말 촘촘하게 짰다.",
		TRAP_TEETH = "더러운 깜짝선물이다.",
		TRAP_TEETH_MAXWELL = "이 것을 밟지 말아야지!",
		TREASURECHEST = 
		{
			GENERIC = "나의 기분 좋은 상자!",
			BURNT = "망가져 버린 상자.",
		},
		TREASURECHEST_TRAP = "대단히 편리하다!",
		TREECLUMP = "다른 곳에 가는 걸 누가 막고 있는 것만 같다.",

		TRINKET_1 = "다 함께 녹여져 있다.",
		TRINKET_10 = "이것이 필요해지기 전까지 여기에서 나가고 싶다.",
		TRINKET_11 = "나에게 아름다운 거짓말을 속삭인다.",
		TRINKET_12 = "마른 촉수로 뭘 해야 할지 모르겠다.",
		TRINKET_2 = "커주일까?",
		TRINKET_23 = "누군가가 말을 잃었다.",
		TRINKET_3 = "매듭이 박혀있다. 영원히.",
		TRINKET_4 = "종교적 유물인 것 같다.",
		TRINKET_5 = "안타깝지만 내가 타고 탈출하기엔 너무 작다.",
		TRINKET_6 = "더 이상 전력을 가지고 있지는 않다.",
		TRINKET_7 = "장난치고 놀 시간 없다!",
		TRINKET_8 = "훌륭해. 이제 욕조를 막을 수 있겠어.",
		TRINKET_9 = "나는 지퍼를 선호한다.",

		BISHOP_CHARGE_HIT = "이런!",
		TRUNKVEST_SUMMER = "야생의 캐주얼 패션.",
		TRUNKVEST_WINTER = "겨울 생존 장비.",
		TRUNK_COOKED = "전보다 더 코 같다.",
		TRUNK_SUMMER = "가볍고 시원한 트렁크.",
		TRUNK_WINTER = "두껍고 털 많은 트렁크.",
		TUMBLEWEED = "회전초가 뭘 집어 들었는지 모르겠다.",
		TURF_DIRT = "땅덩이.",
		TURF_FOREST = "땅덩이.",
		TURF_GRASS = "땅덩이.",
		TURF_MARSH = "땅덩이.",
		TURF_ROAD = "급하게 깐 자갈.",
		TURF_ROCKY = "땅덩이.",
		TURF_SAVANNA = "땅덩이.",
		TURKEYDINNER = "흠.",
		TWIGS = "잔가지 다발이다.",
		UMBRELLA = "적어도 머리카락은 젖지 않게 해주겠지.",
		GRASS_UMBRELLA = "적어도 머리카락은 적당히 젖지 않게 해주겠지.",
		PALMLEAF_UMBRELLA = "머리카락이 젖었다... 마르면 이상해지겠다.",
		UNIMPLEMENTED = "완성된 것 같지 않다! 위험할지도 모르겠다.",
		WAFFLES = "시럽을 더 추가해야 할까.",
		WALL_HAY = 
		{	
			GENERIC = "흐음. 이것으로 만족할 수 밖에.",
			BURNT = "그것으로는 안되겠다.",
		},
		WALL_HAY_ITEM = "안 좋은 아이디어 같다.",
		WALL_STONE = "좋은 벽이다.",
		WALL_STONE_ITEM = "아주 안전한 느낌을 준다.",
		WALL_RUINS = "고대의 벽 조각.",
		WALL_RUINS_ITEM = "역사의 단단한 조각.",
		WALL_WOOD = 
		{
			GENERIC = "뾰족하다!",
			BURNT = "탔다!",
		},
		WALL_WOOD_ITEM = "울타리!",
		WALL_MOONROCK = "우주에서 온 매끄러운 것!",
		WALL_MOONROCK_ITEM = "가볍지만 단단하다.",
		MOONROCKNUGGET = "달의 돌이댜.",
		ROCK_MOON = "달의 돌이댜.",
		WALRUS = "바다코끼리는 자연의 포식자다.",
		WALRUSHAT = "바다코끼리 털로 덮여있다.",
		WALRUS_CAMP =
		{
			EMPTY = "누군가 여기에서 야영했던 것 같다.",
			GENERIC = "안은 따뜻하고 편안한 것으로 보인다.",
		},
		WALRUS_TUSK = "용도를 찾을 수 있겠지.",
		WARDROBE = 
		{
			GENERIC = "깊고 어두운 비밀을 간직하고 있다.",
            BURNING = "빨리 타고 있다!",
			BURNT = "유행이 지났다.",
		},
		WARG = "써먹을 수 있을 것 같은 큰 개다.",
		WASPHIVE = "벌이 화난 것 같다.",
		WATERMELON = "끈적하고 달콤하다.",
		WATERMELON_COOKED = "즙이 많고 따뜻하다.",
		WATERMELONHAT = "얼굴에 즙이 흘러내리게 놔 둔다.",
		WETGOOP = "아무 맛도 안 난다.",
		WHIP = "시끄러운 소리가 평화를 유지해준다.",
		WINTERHAT = "겨울에 유용하겠다.",
		WINTEROMETER = 
		{
			GENERIC = "난 정말 대단한 과학자다.",
			BURNT = "측정하던 시절은 다 지났다.",
		},
		WORMHOLE =
		{
			GENERIC = "보드랍고 굽이친다.",
			OPEN = "과학 때문에 뛰어들고 싶다.",
		},
		WORMHOLE_LIMITED = "평소보다 안 좋아 보인다.",
		ACCOMPLISHMENT_SHRINE = "내가 쓰고 싶다. 그리고 세계에 내가 한 일을 알리고 싶다.",        
		LIVINGTREE = "날 보고 있는 것일까?",
		ICESTAFF = "만지면 차갑다.",
		
        FLOTSAM = "여기에서 걸 방법이 있다면 좋겠다.",

        SUNKEN_BOAT = 
        {
            GENERIC = "말하고 싶어하는 것처럼 보인다.",
            ABANDONED = "그래서 난 물이 싫다.",
        },
        SUNKEN_BOAT_BURNT = "전보다 감항성이 감소했다.",
   		SUNKEN_BOAT_TRINKET_1 = "기기이다.", --sextant
		SUNKEN_BOAT_TRINKET_2 = "이제 소형화 장치만 있으면 된다!", --toy boat
		SUNKEN_BOAT_TRINKET_3 = "축축해 보인다.", --candle
		SUNKEN_BOAT_TRINKET_4 = "과학적이다!", --sea worther
		SUNKEN_BOAT_TRINKET_5 = "하나만 더 있었더라면!", --boot

		HOUNDFIRE = "불이야! 불이야!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------
		
		STUFFEDEGGPLANT = "이걸 먹으면 배부르겠다!",
		SUNKBOAT = "거기에 있으면 나에게 쓸모없지!",
		BANANAPOP = "뇌가 어느 건 안 된다! 과학에 필요하니까!",
		BISQUE = "비스크 요리다!",
		CEVICHE = "더 큰 사발이 없을까!? 작은 새우 같아 보인다.",
		SEAFOODGUMBO = "해물잡탕 대짜다.",
		SURFNTURF = "완벽해!",
		SHARKFINSOUP = "상어 지느러미 수프다!",
		LOBSTERDINNER = "아침에 먹어도 만찬일까?",
		LOBSTERBISQUE = "소금이 있으면 좋겠지만, 어쩔 수 없다.",
		JELLYOPOP = "내 입 안의 젤리오 팝!",
		SWEATERVEST = "이 조끼는 말쑥한 외투다.",
		REFLECTIVEVEST = "꺼져라, 흉악한 태양아!",
		HAWAIIANSHIRT = "실험실에 적합하지 않다!",
		TAFFY = "치과의사가 싫어할 음식이지만... 여기엔 치과의사가 없다.",

		ANTIVENOM = "맛이 끔찍하다!",
		VENOMGLAND = "독만이 독을 해독할 수 있다.",
		BLOWDART_POISON = "뾰족한 부분이 그쪽을 향한다.",
		OBSIDIANMACHETE = "만지면 뜨겁다.",
		SPEARGUN_POISON = "끝에 독을 발랐다.",
		OBSIDIANSPEARGUN = "끝에 불이 달려있다.",
		LUGGAGECHEST = "고급 기선 트렁크로 보인다.",
		PIRATIHATITATOR =
		{
			GENERIC = "이름이 복잡하다.",
			BURNT = "불은 이름 문제를 해결하지 않는데...",
		},
		COFFEEBEANS = "볶으면 되겠다.",
		COFFEE = "맛있는 향이 나고, 활력을 준다!",
		COFFEEBEANS_COOKED = "열로 분명히 개선시켰다.",
		COFFEEBUSH =
		{
			BARREN = "비료가 필요한 것 같다.",
			WITHERED = "영양이 부족해 보인다.",
			GENERIC = "마음에 들 것 같은 식물이다.",
			PICKED = "다시 자라지 않을까?",
		},
		COFFEEBOT = "커피메이커다.",
		MUSSEL = "구부러뜨리면 좋겠다.",
		MUSSEL_FARM =
		{
			 GENERIC = "브뤼셀에서 왔을까.",
			 STICKPLANTED = "제대로 꽂았다."
		},

		MUSSEL_STICK = "홍합꽂이다.",
		LOBSTER = "까칠한 까재다.",
		LOBSTERHOLE = "조그만게 자고 있다.",
		SEATRAP = "월척을 잡히길.",
		SAND_CASTLE =
		{
			SAND = "모래 안의 모래성이다!",
			GENERIC = "내가 만든 것이다!"
		},
		BOATREPAIRKIT = "배가 뜰 수 있게 해준다.",

		BALLPHIN = "둥근 고무 같은 동물이다.",
		BOATCANNON = "배보다 좋은 것은 대포가 있는 배다.",
		BOTTLELANTERN = "햇빛이 가득한 병이다.",
		BURIEDTREASURE = "좋은 보물이 있기를!",
		BUSH_VINE =
		{
			BURNING = "흣.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "덩굴이 많다!",
		},
		CAPTAINHAT = "제대로 된 바다의 복장!",
		COCONADE =
		{
			BURNING = "위험해 보인다.",
			GENERIC = "우선 점화해야 된다.",
		},
		CORAL = "살아있는 건축 자재다!",
		CORALREEF = "산호가 산호초가 되었다!",
		CRABHOLE = "모래에 판 구멍을 집이라고 부른다.",
		CUTLASS = "칼에서 냄새가 나지 않길 바란다...",
		DUBLOON = "난 부자다!",
		FABRIC = "단단한 뿌리로 만든 부드러운 천!",
		FISHINHOLE = "물고기가 있을 것 같다.",
		GOLDENMACHETE = "근사한 스타일로 팬다!",
		JELLYFISH = "순수한 과학 생물이다!",
		JELLYFISH_DEAD = "좋은 삶을 살았다. 아마도.",
		JELLYFISH_COOKED = "꿈틀거린다.",
		JELLYFISH_PLANTED = "과학은 신비하게 물컹거리는 덩어리다.",
		JELLYJERKY = "먹어야겠지.",

		LIMPETROCK =
		{
			GENERIC = "달팽이로 통을 채울 수 있을 것 같다.",
			PICKED = "달팽이가 없으면 통을 채울 수 없다.",
		},
		LOGRAFT = "이것도... 배인가...",
		MACHETE = "마음에 드는 칼이다.",
		MESSAGEBOTTLEEMPTY = "빈 병일 뿐이다.",
		MOSQUITO_POISON = "이 못된 모기들은 질병을 옮긴다.",
		OBSIDIANCOCONADE = "위력이 더 세졌다!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "꺼지기 전에 불에 뭘 놓아야겠다.",
			GENERIC = "불 구덩이는... 더 많은 불을 부른다.",
			HIGH = "번지지 않을 테니 다행이다!",
			LOW = "불이 줄어들고 있다.",
			NORMAL = "나의 최고 발명이다.",
			OUT = "적어도 다시 켤 수 있다.",
		},
		OX = "순한 동물 같다.",
		PIRATEHAT = "해적에게 어울리지만 내가 써도 어울린다.",
		RAFT = "적당해 보인다.",
		ROWBOAT = "체력이 동력이다.",
		SAIL = "행해 경험을 바꾸어줄 것이다.",
		SANDBAG_ITEM = "휴대용 모래 테크놀로지이다.",
		SANDBAG = "물이 들어오지 못하게 한다.",
		SEASACK = "신선하지 않은 음식은 싫다.",
		SEASHELL_BEACHED = "바다 찌꺼기.",
		SEAWEED = "바다 잡초다.",

		SEAWEED_PLANTED = "여기선 이것이 식량인가?",
		SLOTMACHINE = "여기에서 시간을 좀 보내도 되겠다.",
		SNAKE_POISON = "보통 뱀보다 나쁘다!",
		SNAKESKIN = "흥미로우면서도 징그럽다.",
		SNAKESKINHAT = "머리가 비 맞지 않게 한다.",
		SOLOFISH = "젖은 개 같은 냄새가 난다.",
		SPEARGUN = "이것으로 과학 수치를 높일 수 있겠다!",
		SPOILED_FISH = "맡고 싶은 냄새가 아니다.",
		SWORDFISH = "물고기가 날 관통하기 위해 진화한 것 같다.",
		TRIDENT = "이 유물은 얼마나 오래 되었을까?",
		TRINKET_13 = "이 물질이 무엇일까?",
		TRINKET_14 = "오싹하다...",
		TRINKET_15 = "대단하다! 기타가 작아졌다!",
		TRINKET_16 = "어떻게 여기까지 왔을까?",
		TRINKET_17 = "다른 것은 어디에 있지?",
		TRINKET_18 = "지나간 시대의 유물!",
		TRINKET_19 = "뇌에 구름이 낀다. 이런 말은 못들어봤다...",
		TURBINE_BLADES = "이것이 사나운 폭풍에 힘을 실어줬을까?",
		TURF_BEACH = "모래 가득한 땅이다.",
		TURF_JUNGLE = "아주 옹이진 지면이다.",
		VOLCANO_ALTAR =
		{
			GENERIC = "닫힌 것으로 보인다.",
			OPEN = "제단이 제물을 받을 준비가 되었다!",
		},
		VOLCANO_ALTAR_BROKEN = "흠, 문제 없을까?",
		WHALE_BLUE = "감정 문제가 있는 고래다.",
		WHALE_CARCASS_BLUE = "징그럽다. 부풀기 시작하는 것 같다.",
		WHALE_CARCASS_WHITE = "끔찍하다. 부풀기 시작하는 것 같다.",

		ARMOR_SNAKESKIN = "패션 감각이 넘친다!",
		CLOTHSAIL = "바람의 힘만 있으면 된다!",
		DUG_COFFEEBUSH = "땅에 둬야겠다!",
		LAVAPOOL = "좀 많이 뜨겁다.",
		BAMBOO = "이것으로 적들을 물리칠 수 있을까?",
		AERODYNAMICHAT = "공기를 탁 가른다!",
		POISONHOLE = "저만치 떨어져 있는 것이 좋겠다.",
		BOAT_LANTERN = "밤에 볼 때 도움이 된다!",
		DEAD_SWORDFISH = "이것을 가지고 달리면 위험하다.",
		LIMPETS = "굶는 것이 나을지도 모르겠다.",
		OBSIDIANAXE = "최고의 조합!",
		COCONUT = 
		{
		    GENERIC = "코코넛 칼이 필요하다.",
		    PLANTED = "성장하는 데 더 이상 내 도움이 필요 없다.",
		},
		COCONUT_COOKED = "이제 케이크만 필요하다.",
		BERMUDATRIANGLE = "이상한 느낌이 든다.",
		SNAKE = "기름을 팔까?",
		SNAKEOIL = "\"재이의 효능 좋은 뱀기름!\"이라고 써있다.",
		ARMORSEASHELL = "공예다!",
		SNAKE_FIRE = "뱀이 타고 있나?",
		MUSSEL_COOKED = "홍합 요리는 나의 전문이다.",

		PACKIM_FISHBONE = "휴대해야 할 것 같다.",
		PACKIM = "안에 잔뜩 집어넣을 수 있을 것 같다.",

		ARMORLIMESTONE = "내구성이 뛰어나 보인다!",
		TIGERSHARK = "정말 겁난다.",
		WOODLEGS_KEY1 = "어디엔가 무언가가 잠겨 있을 것이다.",
		WOODLEGS_KEY2 = "이 열쇠가 무언가를 열 것이다.",
		WOODLEGS_KEY3 = "열쇠가 있다.",
		WOODLEGS_CAGE = "자물쇠가 과도하게 많다.",
		OBSIDIAN_WORKBENCH = "영감이 떠오른다.",

		NEEDLESPEAR = "밟지 않길 잘 했다.",
		LIMESTONE = "유용한 건축 자재다.",
		DRAGOON = "빠르군!",

		ICEMAKER = 
		{
			OUT = "연료가 더 필요하다.",
			VERYLOW = "기운이 빠지고 있다.",
			LOW = "느려지고 있다.",
			NORMAL = "정상이다.",
			HIGH = "힘차다!",
		},

		DUG_BAMBOOTREE = "이것을 심어야겠다.",
		BAMBOOTREE =
		{
			BURNING = "안녕, 대나무.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "튼튼해 보인다.",
		},
		JUNGLETREE =
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "저 나무는 숱을 쳐야겠다.",
		},
		SHARK_GILLS = "나도 아가미가 있었으면 좋겠다.",
		TREEGUARD = "야자 열매 거두는 데 도와주세요!",
		OBSIDIAN = "불의 돌이다.",
		BABYOX = "작지만 냄새가 심하다.",
		STUNGRAY = "거리를 두는 것이 좋겠다.",
		SHARK_FIN = "유선형의 지느러미다.",
		FROG_POISON = "평소보다 더 사나워 보인다.",
		ARMOUREDBOAT = "튼튼한 배다.",
		ARMOROBSIDIAN = "난 천재다.",
		BIOLUMINESCENCE = "아늑한 빛을 발한다.",
		SPEAR_POISON = "이제 더 치명적이다.",
		SPEAR_OBSIDIAN = "자국 내기에 좋다.",
		SNAKEDEN =
		{
			BURNING = "흣.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "덩굴이 많다!",
		},
		TOUCAN = "잡을 수 없다.",
		MESSAGEBOTTLE = "누군가 나에게 전갈을 보냈다!",
		SAND = "주머니 모래 더미이다.",
		SANDHILL = "신발 안으로 들어가지 않으면 좋겠다.",
		PEACOCK = "화려한 도둑일 뿐이다.",
		VINE = "이것으로 물건을 묶을 수 있을 것 같다.",
		SUPERTELESCOPE = "영원히 바라볼 수 있다!",
		SEAGULL = "꺼져! 다른 땅을 찾아라!",
		SEAGULL_WATER = "꺼져! 다른 물을 찾아라!",
		PARROT = "크래커가 없다.",
		ARMOR_LIFEJACKET = "배 없이 뜰 수 있게 해준다!",
		WHALE_BUBBLES = "Something's underwater here.",
		EARRING = "몸에는 구멍이 덜 있는 것이 좋다.",
		ARMOR_WINDBREAKER = "바람은 나의 상대가 될 수 없다!",
		SEAWEED_COOKED = "파삭파삭하다.",
		CARGOBOAT = "내 물건이 다 들어갈 공간이 있다!",
		GASHAT = "악취를 다 빼준다.",
		ELEPHANTCACTUS = "앗! 눈을 찌를 것 같다!",
		DUG_ELEPHANTCACTUS = "휴대용 꼬챙이 식물이다.",
		ELEPHANTCACTUS_ACTIVE = "저 선인장은 유난히 뾰족하다.",
		ELEPHANTCACTUS_STUMP = "언젠가는 뾰족한 것을 더 많이 만들겠다.",
		FEATHERSAIL = "깃털처럼 가볍다!",
		WALL_LIMESTONE_ITEM = "배치하면 더 유용할 것이다.",
		JUNGLETREESEED =
        {
            GENERIC = "작은 뱀의 소리가 들린다.",
            PLANTED = "좋은 정글 나무로 자랄 것이다.",
        },
		VOLCANO = "아주 안전한 산이라는 과학적 증거가 있다!",
		IRONWIND = "과학자답게 이동하는 방법이다.",
		SEAWEED_DRIED = "짜군!",
		TELESCOPE = "작은 구멍으로 바라본다...",
		
		DOYDOY = "이 멍청한 새를 보호해야 될 것 같은 느낌이 든다.",
		DOYDOYBABY = "작고 귀여운... 것이다.",
		DOYDOYEGG = "부화하게 놔두는 것이 좋을지도 모르겠다.",
		DOYDOYEGG_CRACKED = "어쩔 수 없지. 더 많이 있겠지!",
		DOYDOYFEATHER = "부드럽고 멸종 위기에 있는 것이다!",

		PALMTREE =
		{
			BURNING = "나무 낭비다.",
			BURNT = "그것을 방지했을 수 있을 것 같다는 느낌이 든다.",
			CHOPPED = "자연아, 맛 좀 봐라!",
			GENERIC = "열대니까 있다.",
		},
		PALMLEAF = "마음에 드는 잎이다.",
		CHIMINEA = "바람아, 맛 좀 봐라!",
		DOUBLE_UMBRELLAHAT = "둘째 우산이 첫째 우산을 젖지 않게 해준다.",
		CRAB = 
		{
			GENERIC = "날 꼬집지 마!",
			HIDDEN = "게토끼가 어디에 갔을까?",
		},
		TRAWLNET = "어망이다.",
		TRAWLNETDROPPED = 
		{
			SOON = "정말 가라앉고 있다.",
			SOONISH = "가라앉고 있는 것 같다.",
			GENERIC = "잠재성이 크다!",
		},
		VOLCANO_EXIT = "밖에서 시원한 바람이 들어온다.",
		SHARX = "끈질긴 것들.",
		SEASHELL = "이것을 팔 수 있을 것 같다.",
		WHALE_BUBBLES = "심연의 구취다.",
		MAGMAROCK = "파헤칠 수 있다.",
		MAGMAROCK_GOLD = "황금 같은 기회다.",
		CORAL_BRAIN_ROCK = "어떤 꿍꿍이를 담고 있을까...",
		CORAL_BRAIN = "생각의 양식이다.",
		SHARKITTEN = "농담이냐!",
		SHARKITTENSPAWNER = 
		{
			GENERIC = "모래 더미가 고양이처럼 울고 있나?",
			INACTIVE = "꽤 큰 모래 더미이다.",
		},
		LIVINGJUNGLETREE = "다른 나무와 다를 바 없다.",
		WALLYINTRO_DEBRIS = "난파선의 일부이다.",
		MERMFISHER = "수상한 짓 하지 마.",
        PRIMEAPE = "날 죽일지도 모른다.",
        PRIMEAPEBARREL = "사악한 것이 들어있다.",
        REDBARREL = "뻔하다.",
        PORTAL_SHIPWRECKED = "부서졌잖아.",
		MARSH_PLANT_TROPICAL = "풀 같거든.",
		TELEPORTATO_SW_POTATO = "목적을 가지고 만든 것 같다.",
		PIKE_SKULL = "아얏.",
		PALMLEAF_HUT = "아주 시원한 그늘.",
		FISH_RAW_SMALL_COOKED = "요리된 작은 물고기 조각.",
		LOBSTER_DEAD = "이제 요리만 하면 된다.",
		MERMHOUSE_FISHER = "그리 좋은 냄새가 나지 않는다.",
		WILDBORE = "사나워 보인다.",
		PIRATEPACK = "여기에 부츠를 둘 수 있겠다.",
		TUNACAN = "이 캔이 어디에서 온 것일까?",
		MOSQUITOSACK_YELLOW = "노란색 모기의 부분이다.",
		SANDBAGSMALL = "물이 들어오지 않게 한다.",
		FLUP = "날 내버려 둬!",
		OCTOPUSKING = "마음에 드는 자군요.",
		OCTOPUSCHEST = "방수 기능이 있길 바란다.",
		GRASS_WATER = "목마르지, 풀아.",
		WILDBOREHOUSE = "멧도야지집이다.",
		FISH_RAW_SMALL = "작은 물고기 조각이다.",
		TURF_SWAMP = "습지스러운표층이다.",
		FLAMEGEYSER = "뒤로 물러서야겠다.",
		KNIGHTBOAT = "물에서 나와라, 미치광이!",
		MANGROVETREE_BURNT = "어떻게 이렇게 되었을까.",
		TIDAL_PLANT = "풀일 뿐이다.",
		WALL_LIMESTONE = "튼튼하다.",
		FISH_RAW = "물고기 덩어리다.",
		LOBSTER_DEAD_COOKED = "빨리 먹고 싶다.",
		BLUBBERSUIT = "이상하다.",
		BLOWDART_FLUP = "눈이 보인다.",
		TURF_MEADOW = "초원스러운 표층이다.",
		TURF_VOLCANO = "화산스러운 표층이다.",
		SWEET_POTATO = "맛있어 보인다!",
		SWEET_POTATO_COOKED = "더 맛있어졌다!",
		SWEET_POTATO_PLANTED = "이상해 보이는 당근이다.",
		SWEET_POTATO_SEEDS = "나만의 식물 알이다.",
		BLUBBER = "물컹하군.",
		TELEPORTATO_SW_RING = "유용해 보인다.",
		TELEPORTATO_SW_BOX = "무언가의 일부로 보인다.",
		TELEPORTATO_SW_CRANK = "원래 무엇이었을까.",
		TELEPORTATO_SW_BASE = "부품이 빠진 것 같다.",
		VOLCANOSTAFF = "\"어린이의 손이 닿지 않는 곳에 보관하십시오\"라고 써있다.",
		THATCHPACK = "나는 이것을 때첼이라고 부른다.",
		TURF_DESERTDIRT = "더러운 표층이다.",
		SHARK_TEETHHAT = "위험해 보이는 모자다.",
		TURF_ASH = "재 표층이다.",
		TURF_FUNGUS_GREEN = "녹색 균류 표층이다.",
		BOAT_TORCH = "손을 자유롭게 쓸 수 있게 해준다.",
		MANGROVETREE = "물을 충분히 흡수하고 있을까?",
		HAIL_ICE = "차갑다.",
		TROPICAL_FISH = "열대의 물고기다.",
		TIDALPOOL = "조수가 남긴 웅덩이다.",
		WHALE_WHITE = "싸움꾼 같다.",
		VOLCANO_SHRUB = "잿빛이다.",
		ROCK_OBSIDIAN = "쳇! 파헤칠 수가 없다!",
		ROCK_CHARCOAL = "정말 큰 스타킹이 필요하겠다.",
		DRAGOONDEN = "드래군도 잠을 잔다.",
		WILBUR_UNLOCK = "좀 당당해 보인다.",
		WILBUR_CROWN = "이상하게 원숭이에 맞는 크기다.",
		TWISTER = "이상하게 바람이 많이 분다했다.",
		TWISTER_SEAL = "귀엽다.",
		MAGIC_SEAL = "강력한 유물이다.",
		SAIL_STICK = "과학적인 설명이 있을 것이다.",
		WIND_CONCH = "안에 갇힌 바람이 들린다.",
		DRAGOONEGG = "깨지는 소리가 들렸나?",
		BUOY = "오예, 부표!", 
		TURF_SNAKESKINFLOOR = "이것이 패션이다.",
        DOYDOYNEST = "맛있는 도이도이 알의 집이다.",
		ARMORCACTUS = "뛰어난 공격이 최선의 방어다.",
		BIGFISHINGROD = "큰 물고기를 잡으려면 큰 낚싯대가 필요하다.",
		BRAINJELLYHAT = "뇌가 두 개면, 아이디어가 두 배다!",
		COCONUT_HALVED = "같이 부딪히면 말 소리가 난다.",
		CRATE = "열 방법이 분명히 있을 것이다.",
		DEPLETED_BAMBOOTREE = "다시 자랄까?",
		DEPLETED_BUSH_VINE = "언젠가는 돌아오겠지.",
		DEPLETED_GRASS_WATER = "안녕, 사랑스러운 풀.",
		DOYDOYEGG_COOKED = "제어된 화학 반응을 통해 이 알을 더 영양가 있게 만들었다.",
		DRAGOONHEART = "한 때 드래군이 감정을 담고 있던 곳이다.",
		DRAGOONSPIT = "더러운 침이다!",
		DUG_BUSH_VINE = "집어드는 것이 좋겠다.",
		FRESHFRUITCREPES = "달콤한 과일! 균형 잡힌 아침식사의 일부이다.",
		KRAKEN = "정말 정신 똑바로 차려야 한다!",
		KRAKENCHEST = "승자를 위한 보상이다.",
		KRAKEN_TENTACLE = "자지 않는 괴물이다.",
		MAGMAROCK_FULL = "파헤칠 수 있다.",
		MAGMAROCK_GOLD_FULL = "황금 같은 기회다.",
		MONKEYBALL = "내 이름을 붙이고 싶은 이상한 욕망이 생긴다.",
		MONSTERTARTARE = "이 근처에 다른 먹을 것이 분명히 있겠지.",
		MUSSELBOUILLABAISE = "수많은 실험을 할 수 있을 것 같다!",
		MYSTERYMEAT = "저것을 해부할 생각은 없다.",
		OXHAT = "축축하지 않다. 날씨를 막아줄 모자다.",
		OX_FLUTE = "뭐가 흐르고 있나...?",
		OX_HORN = "황소의 뿔을 잡았다.",
		PARROT_PIRATE = "이름이 있는 것은 안 먹으려고 노력한다.",
		PEG_LEG = "정말 사용하고 싶다면 내가 다리를 절단해줄 용의가 있다.",
		PIRATEGHOST = "끔찍한 종말을 맞이했다. 여기에서 나가지 않으면 나도 같은 운명이 기다린다.",
		SANDBAGSMALL_ITEM = "모래가 가득한 자루. 과학에는 끝이 없단 말인가?",
		SHADOWSKITTISH_WATER = "앗!",
		SHIPWRECKED_ENTRANCE = "어어이!",
		SHIPWRECKED_EXIT = "이제 수평선을 향하여 나간다!",
		SNAKESKINSAIL = "비늘 벗기고 항해하기!",
		SPEAR_LAUNCHER = "과학이 나를 살린다.",
		SWEETPOTATOSOUFFLE = "고구마 수플레가 요즘 유행이다.",
		SWIMMINGHORROR = "앗! 땅으로 돌아가고 싶다!",
		TIGEREYE = "눈이 더 많으면 시력이... 좋아지겠지?",
		TRINKET_20 = "무엇인지 모르겠지만, 더 영리해진 느낌이다!",
		TRINKET_21 = "정확하게 측정해야 한다.",
		TRINKET_22 = "누군가가 이것을 원하겠지.",
		TURF_FUNGUS_RED = "균류의 빨간 바닥.",
		TURF_MAGMAFIELD = "용암스러운 바닥이다.",
		TURF_TIDALMARSH = "늪스러운 바닥이다.",
		VOLCANO_ALTAR_TOWER = "무섭다!",
		WATERYGRAVE = "낚을 수 있지만, 정말 낚아도 될까?",
		WHALE_TRACK = "고래, 호오!",
		WILDBOREHEAD = "생긴 대로 악취가 심하다.",
		WOODLEGSBOAT = "싸나이를 위한 배.",
		WOODLEGSHAT = "나를 해적처럼 만들어줄까?",
		WOODLEGSSAIL = "원조 해적 돛이다.",
		WRECK = "작은 불쌍한 배.",
		INVENTORYGRAVE = "내가 오기 전에 누군가가 먼저 왔었다!",
        INVENTORYMOUND = "내가 오기 전에 누군가가 먼저 왔었다!",
		LIMPETS_COOKED = "다 됐다!",
		RAWLING = "내 친구다!",
		CALIFORNIAROLL = "하지만 젓가락이 없다.",
	},
	DESCRIBE_GENERIC = "흠... 물건.",
	DESCRIBE_TOODARK = "너무 어두워서 안 보인다!",
	DESCRIBE_SMOLDERING = "곧 불붙을 것이다.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "음, 부리다.",
	},
}
