return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我不认为她愿意剃毛。",
			GENERIC = "为了什么？",
			NOBITS = "但是它已经像婴儿屁股一样光溜溜了。",
		},
		STORE =
		{
			GENERIC = "装不下了。",
			NOTALLOWED = "这东西不能装进那里。",
		},
		WRITE =
        {
            GENERIC = "我现在没法做那个。",
        },
		RUMMAGE =
		{	
			GENERIC = "该死。",	
		},
		COOK =
        {
            GENERIC = "什么事都不称心。",
            TOOFAR = "我必须靠近。",
        },
        CHANGEIN =
        {
            GENERIC = "如何超越完美？",
            BURNING = "唉，我的口袋方巾全没了。",
        },
        GIVE =
        {
            DEAD = "死人不需要这种东西。",
            SLEEPING = "它彻底失去了知觉。",
            BUSY = "它现在很忙。",
        },
        TEACH =
        {
            KNOWN = "我早就超过这个水平了。",
            CANTLEARN = "涉足秘密知识的经验教训。",
        },
		REPAIRBOAT =
		{
			GENERIC = "现在不用。",
		},

	},
	ACTIONFAIL_GENERIC = "这么做没用。",
	ANNOUNCE_MAGIC_FAIL = "这样的魔力不属于这里。",
    ANNOUNCE_NOSLEEPONFIRE = "这可能不是最好的主意。",
	ANNOUNCE_NODANGERSIESTA = "它们在我身后紧追不舍！",
	ANNOUNCE_NONIGHTSIESTA = "现在是睡觉时间，不是午休时间。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "在这里午休有点太吓人了。",
	ANNOUNCE_NOHUNGERSIESTA = "传统上来讲，应该在吃饭后而不是吃饭前午休。",
	ANNOUNCE_SHELTER = "保护我，混账的树！",
	ANNOUNCE_BURNT = "它烧着了！",
	ANNOUNCE_TOOL_SLIP = "该死。",
	ANNOUNCE_DAMP = "身上打湿了可不够体面。",
	ANNOUNCE_WORMS = "有什么可怕的东西来了。",
	ANNOUNCE_WET = "水会毁掉一件好西装的，知道吗？",
	ANNOUNCE_WETTER = "我觉得身上的水永远也干不了。",
	ANNOUNCE_SOAKED = "比水本身还要湿。",
	ANNOUNCE_ADVENTUREFAIL = "除了我，没人能成功。",
	ANNOUNCE_BEES = "就算没有我，你的蜂蜜也不会回来的！",
	ANNOUNCE_BOOMERANG = "噢！被打了下狠的...笨手笨脚！",
	ANNOUNCE_CHARLIE = "查理？是我！麦斯威尔！",
	ANNOUNCE_CHARLIE_ATTACK = "噢！查理，这一下好疼！",
	ANNOUNCE_COLD = "我的心都变冷了。",
	ANNOUNCE_HOT = "我的心脏不能承受这样的高温！",
	ANNOUNCE_CRAFTING_FAIL = "呃...我做不到。",
	ANNOUNCE_DEERCLOPS = "我听到它们中有一只来了。",
	ANNOUNCE_DUSK = "天马上就黑了。查理会醒过来。",
	ANNOUNCE_EAT =
	{
		GENERIC = "（狼吞虎咽！）",
		PAINFUL = "噢！它伤了我的嘴！",
		SPOILED = "这东西都烂掉了。",
		STALE = "这东西过了保质期。",
		INVALID = "我不会让那东西靠近我的嘴。",
		YUCKY = "文明人不吃这种东西。",  
	},
	ANNOUNCE_ENTER_DARK = "好黑！我看不见了！",
	ANNOUNCE_ENTER_LIGHT = "又亮起来了。",
	ANNOUNCE_FREEDOM = "终于自由了！",
	ANNOUNCE_HIGHRESEARCH = "我的大脑中充满了能量！",
	ANNOUNCE_HOUNDS = "猎犬蠢蠢欲动了。",
	ANNOUNCE_HUNGRY = "我的肚子空了。",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我闻到了粪便和野兽汗液的味道。",
	ANNOUNCE_HUNT_LOST_TRAIL = "该死！它消失了。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "在这样的条件下，我无法追寻它的踪迹了！",
	ANNOUNCE_INV_FULL = "我的口袋都装满了。",
	ANNOUNCE_KNOCKEDOUT = "呃。脑袋好疼。",
	ANNOUNCE_LOWRESEARCH = "它增进不了多少见识。",
	ANNOUNCE_MOSQUITOS = "多么讨厌的小虫子。",
	ANNOUNCE_NODANGERSLEEP = "附近有危险，不能睡觉！",
	ANNOUNCE_NODAYSLEEP = "白天我睡不着。",
	ANNOUNCE_NODAYSLEEP_CAVE = "现在睡觉会打乱我的作息规律！",
	ANNOUNCE_NOHUNGERSLEEP = "我太饿了，睡不着。",
	ANNOUNCE_NO_TRAP = "好奇怪。他们忘记设陷阱了。",
	ANNOUNCE_PECKED = "耐心点！",
	ANNOUNCE_QUAKE = "那个轰隆隆的声音一定不是好事。",
	ANNOUNCE_RESEARCH = "知识就是力量。而力量就是...好吧，还是力量。",
	ANNOUNCE_THORNS = "为了摘下它，我的手臂被划伤了。",
	ANNOUNCE_TORCH_OUT = "该死，火又熄了。",
	ANNOUNCE_FAN_OUT = "休息时间结束了。",
	ANNOUNCE_COMPASS_OUT = "指南针坏了。",
	ANNOUNCE_TRAP_WENT_OFF = "啊！",
	ANNOUNCE_UNIMPLEMENTED = "嗯，还没有全部完成。",
	ANNOUNCE_WORMHOLE = "哎，那里面真是太吓人了。",
	ANNOUNCE_CANFIX = "\n我觉得我能修好这个！",
	ANNOUNCE_NOSANITY = "我头痛得要死！",
	ANNOUNCE_NOFUEL = "我需要一些噩梦燃料。",
	ANNOUNCE_NOWARDROBEONFIRE = "开玩笑是吧？",
	ANNOUNCE_ACCOMPLISHMENT= "我得想点办法打发时间。",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我感觉自己的努力没有白费。",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "它只精神了一点点。",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "这个不能摸！",
	ANNOUNCE_OTHER_WORLD_PLANT = "我没法把这个种在这里。",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"这字写得太糟糕了。我认不出来。",
	},
	ANNOUNCE_BOAT_DAMAGED = "我的船遭到了破坏。",
	ANNOUNCE_BOAT_SINKING = "我担心开始漏水了。",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "经过千辛万苦，这就是我的结局？！",
	ANNOUNCE_CRAB_ESCAPE = "狡猾的甲壳动物...",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "我被深渊吞噬了！",
	ANNOUNCE_MAPWRAP_RETURN = "谢天谢地。",
	ANNOUNCE_MAPWRAP_WARN = "我不想跟迷雾扯上任何关系。",
	ANNOUNCE_MORETREASURE = "啊，又一份遗失宝藏的指引。",
	ANNOUNCE_OTHER_WORLD_TREASURE = "我不认为这个宝藏位于附近。",
	ANNOUNCE_SHARX = "似乎我被盯上了。",
	ANNOUNCE_TRAWL_FULL = "网已经满到要爆了！",
	ANNOUNCE_TREASURE = "好像我能跟着这个找到某种...宝藏。",
	ANNOUNCE_VOLCANO_ERUPT = "不需要这样爆发。",
	ANNOUNCE_WAVE_BOOST = "真爽！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "追上那头水怪！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "居然对付不了一条鱼！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "我追丢了那条鲸鱼！",

	BATTLECRY =
	{
		GENERIC = "拿起武器！",
		PIG = "智慧强于力量！",
		PREY = "你看起来很美味！",
		SPIDER = "我不会被再次耍弄！",
		SPIDER_WARRIOR = "是你逼我出手的！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "给我离远点！",
		PIG = "下次再教训你，蠢猪！",
		PREY = "你不值得我浪费时间！",
		SPIDER = "我不会被耍弄了...下次！",
		SPIDER_WARRIOR = "下次脱了手套跟你玩！",
	},
	
	DESCRIBE =
	{
		LICHEN = "A slow growing cave plant.",
		ICEHOUND = "它们忘得可真快...",
		INVENTORYGRAVE = "但我想知道墓碑是谁立的？",
		INVENTORYMOUND = "看来它又夺取了一个受害者的性命。",
		GLOMMER = "飞来飞去的黏液工厂。",
        GLOMMERFLOWER = 
        {
        	GENERIC = "花的力量。",
        	DEAD = "花的永恒力量。",
        },
        GLOMMERWINGS = "它们很黏手。",
        GLOMMERFUEL = "唔，好臭。",
        BELL = "更多铃铛。",
        STATUEGLOMMER = 
        {	
        	GENERIC = "喂，那不是我的雕像！",
        	EMPTY = "现在该知道不是我的雕像有何下场了吧。",
    	},
		WEBBERSKULL = "别幻想你能轻易解脱。",
		MOLE =
		{
			HELD = "你走投无路了。",
			UNDERGROUND = "你捡起了我放下的东西吗？你挖出了它吗？",
			ABOVEGROUND = "我当你回答“是”了。",
		},
		MOLEHILL = "挖深点，我要来抓你了。",
		MOLEHAT = "难怪它们能挖几个小时的洞。",
		NIGHTSTICK = "早上好。",
		RABBITHOUSE=
		{
			GENERIC = "哦，真是太聪明了。",
			BURNT = "聪明反被聪明误，胡萝卜被烧死了。",
		},
		TURF_DECIDUOUS = "地皮。",
		TURF_SANDY = "地皮。",
		TURF_BADLANDS = "地皮。",
		BEARGER = "拿走你想要的任何东西。",
		BEARGERVEST = "看看我的背心。",
		ICEPACK = "里面的东西都在冬眠。",
		BEARGER_FUR = "这可以做成一块不错的小地毯。",
		BIGFOOT = "现在，它显然会助长梦魇的气焰。",
		BONESHARD = "碾成碎骨。",
		BUZZARD = "鉴赏腐肉的行家。",
		CACTUS = 
		{
			GENERIC = "长得像河豚的植物。",
			PICKED = "仙人掌？我看不如叫仙人扁！",
		},
		CACTUS_MEAT_COOKED = "可以吃的仙人掌。",
		CACTUS_MEAT = "把这东西放进嘴里真是太不明智了。",
		CACTUS_FLOWER = "仙人掌的这部分总是很不错。",
		COLDFIRE =
		{
			EMBERS = "火要灭了。",
			GENERIC = "真舒服。",
			HIGH = "这会让查理暂时远离我。",
			LOW = "它需要燃料。",
			NORMAL = "冰冷而激烈。",
			OUT = "火不会重新燃起了。",
		},
		CATCOON = "长得像猫的害兽。",
		CATCOONDEN = 
		{
			GENERIC = "害兽的家。",
			EMPTY = "嗯，我想就是那样了。",
		},
		CATCOONHAT = "死掉的脑袋。",
		COONTAIL = "尾巴的故事。",
		COOKPOT =
		{
			COOKING_LONG = "等着...",
			COOKING_SHORT = "马上就好了！",
			DONE = "终于有一些美食出炉了。",
			EMPTY = "想一想都让我流口水。",
			BURNT = "就我的口味而言，它烧过头了。",
		},
		EYEBRELLAHAT =	"注视天空的眼睛。",
		ARMORDRAGONFLY = "火蜻蜓鳞片做成的盔甲。",
		DRAGON_SCALES = "像在燃烧一般。",
		DRAGONFLYCHEST = "这些鳞片无疑很漂亮。",
		DECIDUOUSTREE = 
		{
			BURNING = "哎呀。",
			BURNT = "火的洗礼。",
			POISON = "闭上你的血盆大口！",
			CHOPPED = "不会重新长出来了。",
			GENERIC = "我听到它们被描述成“阔叶树”。",
		},
		ACORN_COOKED = "在营火上烤熟的。",
		BIRCHNUTDRAKE = "长着腿的坚果！好吓人！",
		FARMPLOT =
		{
			GENERIC = "我看起来像个农民吗？",
			GROWING = "比起看植物是怎么长大的，我有更重要的事情要做。",
			NEEDSFERTILIZER = "它需要...补充点营养。",
			BURNT = "收获了一大堆灰烬。",
		},
		COLDFIREPIT =
		{
			EMBERS = "我应该注意的。",
			GENERIC = "一处石头营火。",
			HIGH = "冷冷的、熊熊燃烧的火。",
			LOW = "火势小了。",
			NORMAL = "火很冷。",
			OUT = "变暖了。",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "熄灭吧，火焰！",
			OFF = "暴风雨前的平静。",
			LOWFUEL = "剩下的燃料不多了。",
		},
		ICEHAT = "将一些冰戴在你的脑袋上。",
		LIGHTNINGGOAT = 
		{
			GENERIC = "它总是在嚼什么？",
			CHARGED = "充电！！！",
		},
		LIGHTNINGGOATHORN = "这可以做成不错的角。",
		GOATMILK = "它富含营养。",
		MEATRACK =
		{
			DONE = "就像沙漠一样干。",
			DRYING = "还是很湿。",
			DRYINGINRAIN = "雨一直下，肉还是湿的。",
			GENERIC = "它可以把肉晾干，让肉不容易腐烂。",
			BURNT = "它现在太脆弱了，没办法挂肉。",
		},
		MERMHEAD = 
		{
			GENERIC = "它的眼睛注视着你。",
			BURNT = "烤熟的鱼人头。真是太美味了。",
		},
		MERMHOUSE = 
		{
			GENERIC = "他们照搬了猪屋的设计，但他们甚至还没有猪聪明。",
			BURNT = "这屋子像猪屋一样烧掉了。",
		},
		FLOWERSALAD = "蔬菜的精华。",
        ICECREAM = "圣代，圣代，圣代！",
        BANANAPOP = "嗯...我不知道我期待的是什么。",
        BISQUE = "上好的食物，但氛围可以改进。",
        CEVICHE = "令人愉悦的高档菜肴。",
        SEAFOODGUMBO = "看起来还行。",
        SURFNTURF = "营养非常均衡。",
        SHARKFINSOUP = "我出众的味觉尝到了濒危的味道。",
        LOBSTERDINNER = "我忘了带围兜。",
        LOBSTERBISQUE = "啊，我确实喜欢精细的东西。",
        JELLYOPOP = "嗯...我觉得我这么文雅的人吃这个有点违和。",
        WATERMELONICLE = "冰棺中的西瓜成了一桩悬案。",
        TRAILMIX = "坚果和浆果。没有放椒盐脆棒。",
        HOTCHILI = "像地狱一样热！",
        GUACAMOLE = "食材中有一只鼹鼠。",
		MOOSE = "不论它是什么，它一定是从北方来的。",
		MOOSEEGG = "驾着闪电而来？你这个大鸟蛋。",
		MOSSLING = "毛茸茸的...小家伙。",
		FEATHERFAN = "外面有风吗？或者只是我的扇子在扇风？",
		TROPICALFAN = "外面有风吗？或者只是我的扇子在扇风？",
		GOOSE_FEATHER = "我可以用它们来填满我用的枕头。",
		STAFF_TORNADO = "风的力量。",
		PIGHEAD = 
		{	
			GENERIC = "呃...好迷人。",
			BURNT = "烤猪！",
		},
		PIGHOUSE =
		{
			FULL = "如果我是他，我也会进去的。",
			GENERIC = "结构不合理。",
			LIGHTSOUT = "我吹，我吹，我吹吹吹！",
			BURNT = "现在看你还躲不躲在那里。",
		},
		FERTILIZER = "手里拿着粪便太不绅士了。",
		RAINOMETER = 
		{	
			GENERIC = "我只要抬头看看天，就可以了解到同样的信息。",
			BURNT = "那时候没有一场及时雨。",
		},
		RAINCOAT = "雨水快出去！",
		RAINHAT = "不是最体面的帽子，但相当有必要拥有一顶。",
		RESEARCHLAB = 
		{	
			GENERIC = "难以置信，我忘记了怎样造那些东西。",
			BURNT = "火焰学会了怎样烧毁它。",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "它解锁了中级工具的制造配方。",
			BURNT = "火焰将它完全吞噬了。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "这是我做个人研究的地方。",
			BURNT = "研究完成。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "一台造型相当简洁的机器。",
			BURNT = "太烫了，没办法处理。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "我可不会为使用这个而感到羞愧。",
			BURNT = "我不会再使用它了。",
		},
		ROCK_ICE = 
		{
			GENERIC = "我可以从这座旧冰矿上凿点冰块下来。",
			MELTED = "这只是一个水坑。",
		},
		ROCK_ICE_MELTED = "这只是一个水坑。",
		ICE = "冰矿的产物。",
        REFLECTIVEVEST = "安全比形象更重要。",
		HAWAIIANSHIRT = "最体面的衣服。",
		TENT = 
		{
			GENERIC = "就我的品味而言，它太土气了。",
			BURNT = "就我的品味而言，它烧过头了。",
		},
		SIESTAHUT = 
		{
			GENERIC = "很土气，但是遮荫效果很好。",
			BURNT = "这个凉棚也就到此为止了。",
		},
		TRANSISTOR = "我不了解它的工作原理，但它确实有用。",
		TREASURECHEST = 
		{
			GENERIC = "一个装战利品的地方。",
			BURNT = "它现在不能装任何东西了。",
		},
		TUMBLEWEED = "滚动吧，野草。",
		GRASS_UMBRELLA = "与其说它“整洁”，不如说它“漂亮”。",
		PALMLEAF_UMBRELLA = "物尽其用。",
		UNIMPLEMENTED = "有点神秘！别去摸它。",
		WALL_HAY = 
		{	
			GENERIC = "它是一个易燃物。",
			BURNT = "我告诉过你了。",
		},
		WALL_WOOD = 
		{
			GENERIC = "有点坚硬，但还是可以燃烧的。",
			BURNT = "不坚硬，也不易燃烧。",
		},
		WARG = "头狼！",
		WATERMELON = "它里面主要是水。纤维状的、甜蜜的水。",
		WATERMELON_COOKED = "烧烤西瓜。",
		WATERMELONHAT = "这是保持凉快的一种方法。你还会觉得黏黏的。",
		WINTEROMETER = 
		{
			GENERIC = "不是最有用的发明，对吗？",
			BURNT = "谁在乎这个？",
		},
		LIVINGTREE = "它有一张脸。",
		ICESTAFF = "又冷又酷的东西。",
		WAXWELLJOURNAL = "查理，我很抱歉。",
		WORMLIGHT = "多么漂亮的骗局。",
		WORM =
		{
		    PLANT = "植物，你骗不了我。",
		    DIRT = "有东西在遁地行走。",
		    WORM = "噢，又来了新的！",
		},
		EEL = "它们只生活在深海中。",
		EEL_COOKED = "它全身都滑溜溜的。",
		UNAGI = "它注定要成为盘中餐。",
		EYETURRET = "我较好的作品。",
		EYETURRET_ITEM = "现在我只需要把它安放好。",
		MINOTAURHORN = "很抱歉我不得不那么做，老友。",
		MINOTAURCHEST = "几乎就像他还活着。",
		THULECITE_PIECES = "我可以将好几块碎片合成更大的一块。",
		POND_ALGAE = "这是一些水藻。",
		GREENSTAFF = "我必须依赖这种形式的聚能工具。",
		POTTEDFERN = "好别致。",

		THULECITE = "极其稀少却很有用的材料。",
		ARMORRUINS = "铥矿与噩梦燃料结合得如此完美。",
		RUINS_BAT = "燃料深藏其中。",
		RUINSHAT = "里面肯定有燃料在流动。",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "城市中心平静无波。",	--calm phase
			WARN = "它又开始跳动了。",	--Before nightmare
			WAXING = "脉冲在加快。", --Nightmare Phase first 33%
			STEADY = "脉冲保持平稳。", --Nightmare 33% - 66%
			WANING = "脉冲在减弱。", --Nightmare 66% +
			DAWN = "它又平静下来了。", --After nightmare
			NOMAGIC = "脉冲在这里没有影响。", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "因为保养不当，它们坏掉了。",
		ROOK_NIGHTMARE = "制造者遗弃了它。",
		KNIGHT_NIGHTMARE = "它看起来没法修了。",
		MINOTAUR = "天哪，噩梦燃料改变了你。",	--Monster in labyrinth
		SPIDER_DROPPER = "这个世界的生物进化的速度越来越恐怖了。",	--White spider that comes from the roof
		NIGHTMARELIGHT = "过度使用燃料让它们堕落了。",	--Lights that activate during nightmare.
		RELIC = "They were all dead when I got here.",	--Fixed relic
		RUINS_RUBBLE = "The earthquakes have taken their toll.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "不知道为什么我过去没想到用这个。",	--Works as axe and pickaxe
		GREENGEM = "噩梦燃料将释放它的真正潜力。",
		ORANGESTAFF = "我必须依赖这种形式的聚能工具。",	--Teleports player.
		YELLOWAMULET = "这将让我引人注目。",	--Emits light, player walks faster.
		GREENAMULET = "我发誓，我平常不需要这个。",	--Reduce cost of crafting

		SLURPER = "单蠢的生物。它们活着只是为了吃吃睡睡。",
		SLURPER_PELT = "这家伙死后将为我所用！",
		ARMORSLURPER = "又湿又闷，填充材料也很怪。",
		ORANGEAMULET = "简单的魔法往往是最好的。",
		YELLOWSTAFF = "有一个大点的宝石，它会强大得多。",
		YELLOWGEM = "我可以感觉到其中的魔力。",
		ORANGEGEM = "只要有一些燃料，它会相当强大。",
		TELEBASE = 
		{
			VALID = "应该可以启动了。",
			GEMS = "燃料需要更多的聚能宝石。",
		},
		GEMSOCKET = 
		{
			VALID = "这个准备好了。",
			GEMS = "燃料需要聚能宝石。",
		},
		STAFFLIGHT = "这东西应该能赶走暗影。",
       	ANCIENT_ALTAR =
        {
        	WORKING = "Where are their gods now?",
        	BROKEN = "This can be partially restored.",
        },
        ANCIENT_ALTAR = "他们的神现在在哪里？",
        ANCIENT_ALTAR_BROKEN = "这个可以在一定程度上修复。",

        ANCIENT_STATUE = "曾经的高傲种族。",

		CAVE_BANANA = "就像我嘴里进了灰。",
		CAVE_BANANA_COOKED = "比生的还难吃。",
		CAVE_BANANA_TREE = "它看起来像香蕉，但我可不相信。",
		ROCKY = "我放逐这些家伙是有原因的。",
		
		HOUNDSTOOTH="这可以用在时尚方面。",
		ARMORSNURTLESHELL="这一点也不体面。",
		BAT="呃。丑陋的怪物。",
		BATBAT = "暴力从未让人感觉如此之爽。",
		BATWING="我不要吃这个。",
		BATWING_COOKED="我还是不要吃这个。",
		BEDROLL_FURRY="至少它们有些用处。",
		BUNNYMAN="这让我想起了我的旧行当。",
		FLOWER_CAVE="这下面太黑了。",
		FLOWER_CAVE_DOUBLE="这下面太黑了。",
		FLOWER_CAVE_TRIPLE="这下面太黑了。",
		GUANO="真恶心！",
		LANTERN="我希望这能赶跑它们。",
		LIGHTBULB="它最终会耗尽的。",
		MANRABBIT_TAIL="愚蠢的兔子。",
		MUSHTREE_TALL="它闻起来充满了腐烂坏掉的味道。",
		MUSHTREE_MEDIUM="瓦尔多在哪里？",
		MUSHTREE_SMALL="呃，它很难闻。",
		SLURTLE="我不记得那些东西了...",
		SLURTLE_SHELLPIECES="它们拼不回去。",
		SLURTLEHAT="在需要战斗时，它可以防止我倒下。",
		SLURTLEHOLE="真恶心。",
		SLURTLESLIME="肯定有更好的办法。",
		SNURTLE="好奇怪。它们肯定是新来的。",
		SPIDER_HIDER="这家伙有点难对付。",
		SPIDER_SPITTER="凶猛的小东西，不是吗？",
		SPIDERHOLE="那东西是怎样下来这里的？",
		STALAGMITE="岩石。太无趣了。",
		STALAGMITE_FULL="岩石。太无趣了。",
		STALAGMITE_LOW="岩石。太无趣了。",
		STALAGMITE_MED="岩石。太无趣了。",
		STALAGMITE_TALL="石笋。太无趣了。",
		STALAGMITE_TALL_FULL="石笋。太无趣了。",
		STALAGMITE_TALL_LOW="石笋。太无趣了。",
		STALAGMITE_TALL_MED="石笋。太无趣了。",

		POWCAKE = "这是什么邪恶的鬼东西？",
		CAVE_ENTRANCE = 
		{
			GENERIC= "很久以前我就把它堵上了。",
			OPEN = "这可不是个好主意！",
		},
        CAVE_EXIT = "我可以出去了！",

		MAXWELLPHONOGRAPH = "那个该死的东西！",
		BOOMERANG = "每次击中目标都会脏了你的手。",
		PIGGUARD = "呸，恶心的畜生。",
		ABIGAIL = "这些肉体凡胎为什么不一直保持死亡的状态呢？",
		ADVENTURE_PORTAL = "这就是我留下那件东西的地方了！",
		AMULET = "它输送着宇宙中最黑暗的能量。",
		ANIMAL_TRACK = "某只蠢笨的动物经过了这里。",
		ARMORGRASS = "直接对抗是很粗鲁的。",
		ARMORMARBLE = "这真的不是我的风格。",
		ARMORWOOD = "呃，这种粗俗的斗殴和我一点都不衬。",
		ARMOR_SANITY = "是时候把自己包裹在噩梦里了。",
		ASH =
		{
			GENERIC = "细细的粉末，闻起来有毁灭的味道。",
			REMAINS_GLOMMERFLOWER = "总是会有另一只格罗姆。",
			REMAINS_EYE_BONE = "别担心。会有更多切斯特的。",
			REMAINS_THINGIE = "传送门之旅使它变得无法辨别了。",
		},
		AXE = "有时候，直截了当的方法是最好的。",
		BABYBEEFALO = "它们小时候就这么丑。",
		BACKPACK = "我希望这附近有搬运工。",
		BACONEGGS = "这才是像样的早餐。",
		BANDAGE = "又黏又甜，疗伤效果不错。",
		BASALT = "我造了块石头，重得我都抬不起来。",
		BEARDHAIR = "好多毛。",
		BEDROLL_STRAW = "我不喜欢露宿。",
		BEE =
		{
			GENERIC = "它们如此辛勤地工作，这些傻瓜。",
			HELD = "现在我拿它怎么办？",
		},
		BEEBOX =
		{
			FULLHONEY = "真诱人，但是蜜蜂太多了。",
			GENERIC = "我的蜜蜂就住在里面。",
			NOHONEY = "我的蜜蜂不够勤劳。",
			SOMEHONEY = "我应该等久一点。",
			BURNT = "烤焦的蜂蜜。",
		},
		BEEFALO =
		{
			FOLLOWER = "该死，它在跟着我。",
			GENERIC = "看看那头愚蠢的动物吧。",
			NAKED = "现在它看起来傻不拉几又惨兮兮的。",
			SLEEPING = "它睡着后也还是一副蠢样。",
		},
		BEEFALOHAT = "一点也不时尚。",
		BEEFALOWOOL = "闻起来像牲口棚的味道。",
		BEEHAT = "如果有必要，我会戴着它的。",
		BEEHIVE = "不要是蜜蜂啊！",
		BEEMINE = "它们等得很有耐心。",
		BEEMINE_MAXWELL = "也许我不该把它放在那里。",
		BERRIES = "唉，如果实在没别的吃。",
		BERRIES_COOKED = "至少比原来好了点。",
		BERRYBUSH =
		{
			BARREN = "它需要施肥。",
			WITHERED = "对小小的浆果丛来说温度太高了。",
			GENERIC = "沦落到吃浆果了。唉。",
			PICKED = "现在我们得等等。",
		},
		BIRDCAGE =
		{
			GENERIC = "你们再也不能将我重新关进牢笼。",
			OCCUPIED = "我了解你的心情，长羽毛的小家伙。",
			SLEEPING = "当你醒来的时候，你还是在那里面。",
			HUNGRY = "闹腾什么呢，小毛团？",
			STARVING = "哦，别这样，我上周才喂过你。",
			DEAD = "睡得真沉。",
			SKELETON = "也许它不是在睡觉。",
		},
		BIRDTRAP = "它们前仆后继地上当！",
		BIRD_EGG = "我喜欢把它想象成幼鸟的牢笼。",
		BIRD_EGG_COOKED = "有蛋黄的那一面朝上。",
		BISHOP = "我对那件作品感到特别自豪。",
		BLOWDART_FIRE = "一定要吹出去。",
		BLOWDART_SLEEP = "请称呼我为“睡魔先生”。",
		BLOWDART_PIPE = "一根能造成痛苦的好管子！",
		BLUEAMULET = "冻过头了。",
		BLUEGEM = "蓝色会带来冰。",
		BLUEPRINT = "这些我都知道。我只是忘记了。",
		BELL_BLUEPRINT = "这些我都知道。我只是忘记了。",
		BLUE_CAP = "会出什么问题？",
		BLUE_CAP_COOKED = "真鲜啊！",
		BLUE_MUSHROOM =
		{
			GENERIC = "这些蓝色的会有一些好处。",
			INGROUND = "它还没长好呢。",
			PICKED = "下次再来采吧？",
		},
		BOARDS = "刨得很粗糙。",
		BOAT = "它哪儿也去不了。",
		BONESTEW = "一点渣都不剩。",
		BUGNET = "很适合用来抓毫无防备的昆虫。",
		BUSHHAT = "那里有我的藏身之处。",
		BUTTER = "一些冷笑话是免不了的，比如蝴蝶飞不动了就变成黄油了。",
		BUTTERFLY =
		{
			GENERIC = "会飞的花朵。",
			HELD = "如果有人把它的翅膀扯掉就太可耻了。",
		},
		BUTTERFLYMUFFIN = "它应该不会再无休止地扇动翅膀了。",
		BUTTERFLYWINGS = "哈哈哈，我抓到他了！",
		CAMPFIRE =
		{
			EMBERS = "火要灭了。",
			GENERIC = "真舒服。",
			HIGH = "这会让查理暂时远离我。",
			LOW = "它需要燃料。",
			NORMAL = "像在燃烧一般。",
			OUT = "火不会重新燃起了。",
		},
		CANE = "它身上雕刻着神行物的图案。",
		CARROT = "我不喜欢吃蔬菜。",
		CARROT_COOKED = "至少比原来好了点。",
		CARROT_PLANTED = "真平凡。",
		CARROT_SEEDS = "这种低贱的活不适合我。",
		CAVE_FERN = "我想踩上去。",
		CHARCOAL = "没什么能偷走我的木炭！",
        CHESSJUNK1 = "我没有下完那局棋是有原因的。",
        CHESSJUNK2 = "那是个笨蛋。",
        CHESSJUNK3 = "不喜欢那个家伙的脸。",
		CHESTER = "烦人的小怪物，尽管有它的用途。",
		CHESTER_EYEBONE =
		{
			GENERIC = "不准再看我！",
			WAITING = "它在等什么？",
		},
		COOKEDMANDRAKE = "它失去了不少力量。",
		COOKEDMEAT = "它现在没有那么难闻了。",
		COOKEDMONSTERMEAT = "如果没得选的话，我会吃它的。",
		COOKEDSMALLMEAT = "嗯，至少它现在不动了。",
		CORN = "富含果糖。",
		CORN_COOKED = "至少比原来好了点。",
		CORN_SEEDS = "这种低贱的活不适合我。",
		CROW =
		{
			GENERIC = "我不知道它们怎么到这里来的。",
			HELD = "嘘...我的宝贝。",
		},
		LICHEN = "这些菌类植物在陷落中逃过一劫。",
		CUTLICHEN = "干燥、松脆、有营养。",
		CUTGRASS = "大地上的凡物。",
		CUTREEDS = "我想我可以用这个来造点有用的东西。",
		CUTSTONE = "文明的基石。",
		DEADLYFEAST = "它闻起来...有毒。",
		DEERCLOPS = "连我都害怕那家伙。",
		DEERCLOPS_EYEBALL = "巨鹿十分近视。",
		DEPLETED_GRASS =
		{
			GENERIC = "这对任何人都没有好处。",
		},
		DIRTPILE = "那个看起来不协调。",
		DIVININGROD =
		{
			COLD = "多半只是背景的杂音。",
			GENERIC = "我可以用这个找到我丢失的零件。",
			HOT = "它一定就在我的眼皮底下！",
			WARM = "这是正确的方向。",
			WARMER = "我应该睁大眼睛。",
		},
		DIVININGRODBASE =
		{
			GENERIC = "这是启动装置。",
			READY = "我需要插入探测杖。",
			UNLOCKED = "行了！",
		},
		DIVININGRODSTART = "这些门通往下一根探测杖。",
		DRAGONFLY = "火红的蜻蜓。",
		LAVASPIT = 
		{
			HOT = "火焰喷射。",
			COOL = "现在又干又冷。",
		},
		DRAGONFRUIT = "美味又充满异域风情。",
		DRAGONFRUIT_COOKED = "至少比原来好了点。",
		DRAGONFRUIT_SEEDS = "这种低贱的活不适合我。",
		DRAGONPIE = "确实精致。",
		DRUMSTICK = "吃起来味道跟浆果一样奇怪。",
		DRUMSTICK_COOKED = "尝起来还是像浆果。",
		DUG_BERRYBUSH = "我看起来像个园丁吗？",
		DUG_GRASS = "我看起来像个园丁吗？",
		DUG_MARSH_BUSH = "我看起来像个园丁吗？",
		DUG_SAPLING = "我无法相信我竟然沦落到这般田地。",
		DURIAN = "这是后天养成的嗜好。",
		DURIAN_COOKED = "至少比原来好了点。",
		DURIAN_SEEDS = "这种低贱的活不适合我。",
		EARMUFFSHAT = "至少它们很暖和。",
		EGGPLANT = "又一株无聊的植物。",
		EGGPLANT_COOKED = "至少比原来好了点。",
		EGGPLANT_SEEDS = "这种低贱的活不适合我。",
		ACORN = 
		{
		    GENERIC = "一个更热爱户外的人或许能用这个来做点什么。",
		    PLANTED = "哈，它看起来属于大地。",
		},
		EVERGREEN =
		{
			BURNING = "哎呀。",
			BURNT = "火的洗礼。",
			CHOPPED = "不会重新长出来了。",
			GENERIC = "我听到它们被描述成“针叶树”。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "哎呀。",
			BURNT = "尘归尘，土归土。",
			CHOPPED = "我让它从痛苦中解脱了。",
			GENERIC = "它看上去生病了。",
		},
		EYEPLANT = "食人花的小兵。",
		FEATHERHAT = "我会用我的羽毛引诱它们。",
		FEATHER_CROW = "黑色是睡眠的颜色。",
		FEATHER_ROBIN = "红色是火的颜色。",
		FEATHER_ROBIN_WINTER = "灰色是疼痛的颜色。",
		FEM_PUPPET = "幸好是她不是我。",
		FIREFLIES =
		{
			GENERIC = "真美。",
			HELD = "要是我想的话，我可以捏扁它们。",
		},
		FIREHOUND = "我把火宝石放在了那里，只是想开个玩笑。",
		FIREPIT =
		{
			EMBERS = "我应该注意的。",
			GENERIC = "一处石头营火。",
			HIGH = "熊熊燃烧的火。",
			LOW = "火势小了。",
			NORMAL = "有点热。",
			OUT = "变冷了。",
		},
		FIRESTAFF = "一个基础魔法，但是很有效。",
		FISH = "从混浊的深水中新鲜捕捞的。",
		FISHINGROD = "我要吃一辈子。",
		FISHSTICKS = "这些应该可以让我渡过难关。",
		FISHTACOS = "裹在脆皮里的熟鱼肉。",
		FISH_MED = "站住。",
		FISH_MED_COOKED = "还是很腥。",
		FISH_COOKED = "还是很腥。",
		FLINT = "噢！我割到了手指！",
		FLOWER = "我现在充满了想踩它几脚的冲动。",
		FLOWERHAT = "绝对不是我的风格。",
		FLOWER_EVIL = "我喜欢那朵花。",
		FOLIAGE = "乡下人最适合吃这个。",
		FOOTBALLHAT = "现在我已经准备好争球了。",
		FROG =
		{
			DEAD = "它挂了。",
			GENERIC = "它喜欢跳跃和舔东西。",
			SLEEPING = "它看起来累了。",
		},
		FROGGLEBUNWICH = "有点辣。",
		FROGLEGS = "肌肉发达。",
		FROGLEGS_COOKED = "好筋道。",
		FRUITMEDLEY = "这个搭配干酪盘好极了。",
		GEARS = "我的宝贝！你怎么样了？",
		GHOST = "它记得我！",
		GOLDENAXE = "每砍一次东西，它都会变得更锋利。",
		GOLDENPICKAXE = "这肯定是游戏逻辑。",
		GOLDENPITCHFORK = "我不确定这笔投资是否划算。",
		GOLDENSHOVEL = "这把铲子价值不菲。",
		GOLDNUGGET = "这东西曾经对我很重要。",
		GRASS =
		{
			BARREN = "需要施肥。",
			WITHERED = "本以为草是受得住这种高温的...",
			BURNING = "哎呀。",
			GENERIC = "好多草。",
			PICKED = "没什么可以收获的。",
		},
		GREEN_CAP = "我应该吃掉它。",
		GREEN_CAP_COOKED = "好咸！",
		GREEN_MUSHROOM =
		{
			GENERIC = "绿色菌类。",
			INGROUND = "这些东西什么时候会冒出来？",
			PICKED = "曾经在那里，已经采过了。",
		},
		GUNPOWDER = "这个东西我喜欢。",
		HAMBAT = "一件不太庄重的武器，适合不太讲究的时候。",
		HAMMER = "破坏别人的劳动成果感觉真好。",
		HEALINGSALVE = "只有一些毒液和陈旧肮脏的灰烬。",
		HEATROCK =
		{	
			FROZEN = "冻得拿不住。",
			COLD = "很清凉。",
			GENERIC = "装在口袋里的石头，可以提供热量。",
			WARM = "暖暖的，真舒服。",
			HOT = "烫到拿不住。",
		},
		HOME = "没有什么地方比家里更好。",
		HOMESIGN = 
		{
			GENERIC = "上面写着...什么都没写。",
			BURNT = "就这样，它现在透露的信息更少了。",
		},
		HONEY = "又黏又甜。",
		HONEYCOMB = "里面全是蜂蛹。",
		HONEYHAM = "肉质细嫩。",
		HONEYNUGGETS = "这些看上去形状很幼稚，但非常美味。",
		HORN = "召唤牦牛！",
		HOUND = "它们不认识我了！",
		HOUNDBONE = "它们是饥饿的恶魔，不是吗？",
		HOUNDMOUND = "这是一个通往猎犬巢穴的通道。",
		ICEBOX = "这个箱子里有点冬天的气息。",
		INSANITYROCK =
		{
			ACTIVE = "我现在可以看到它真正的样子了！",
			INACTIVE = "在这个平面上只能看到它的一半。",
		},
		JAMMYPRESERVES = "它弄脏了我的好手套。",
		KABOBS = "完美的烹饪。",
		KILLERBEE =
		{
			GENERIC = "那只蜜蜂为什么如此生气？",
			HELD = "我抓住了老虎尾巴。",
		},
		KNIGHT = "如此巧夺天工的手艺！",
		KOALEFANT_SUMMER = "牦牛的远亲。",
		KOALEFANT_WINTER = "它穿上了自己的冬衣。",
		KRAMPUS = "你抓不到我的！",
		KRAMPUS_SACK = "它真的很轻。",
		LEIF = "讨厌的生物！",
		LEIF_SPARSE = "讨厌的生物！",
		LIGHTNING_ROD =
		{
			CHARGED = "能量从中流过。",
			GENERIC = "一点点保护。",
		},
		LITTLE_WALRUS = "一个模子里印出来的家伙。",
		LIVINGLOG = "我喜欢它们被点燃时的声音。",
		LOCKEDWES = "他让我不高兴。",
		LOG =
		{
			BURNING = "好吧，它烧起来很有意思。",
			GENERIC = "这是一块木材。还有什么要说的？",
		},
		LUREPLANT = "一株恶毒的植物。",
		LUREPLANTBULB = "或许我能让它好好发挥作用。",
		MALE_PUPPET = "幸好是他不是我。",
		MANDRAKE =
		{
			DEAD = "我的耳朵还在嗡嗡作响。",
			GENERIC = "噢，闭嘴好吗？",
			PICKED = "曼德拉草真是太烦人了。",
		},
		MANDRAKESOUP = "再也听不到你哭闹了。",
		MANDRAKE_COOKED = "看来我叫到了最后。",
		MARBLE = "这东西很坚硬。",
		MARBLEPILLAR = "我总想知道谁建造了那些东西。",
		MARBLETREE = "真怪异。",
		MARSH_BUSH =
		{
			BURNING = "我应该问它一些问题。",
			GENERIC = "扭曲而多刺，就像我一样！",
			PICKED = "扎得我好痛。",
		},
		MARSH_PLANT = "好普通的小植物。",
		MARSH_TREE =
		{
			BURNING = "就这样吧。",
			BURNT = "它现在对任何人都没有用处了。",
			CHOPPED = "树木0，麦斯威尔1。",
			GENERIC = "一棵姿势怪异的树。",
		},
		MAXWELL = "看上去不错！",
		MAXWELLHEAD = "嗨，帅哥。",
		MAXWELLLIGHT = "哦，它记得我。",
		MAXWELLLOCK = "它能将主人锁在王座上。",
		MAXWELLTHRONE = "它没有看上去那么让人痛苦，但也只是好一点点。",
		MEAT = "我过去吃得比这好多了。",
		MEATBALLS = "我要大赞厨师！",
		MEAT_DRIED = "我的牙根本咬不动这个。",
		MERM = "我到这里的时候他们已经在这了。",
		MINERHAT = "这些萤火虫最终会饿死的。",
		MONKEY = "我可没时间浪费在你身上！",
		MONKEYBARREL = "多令人厌恶的家。",
		MONSTERLASAGNA = "吃这个是不理智的。",
		MONSTERMEAT = "真恶心。",
		MONSTERMEAT_DRIED = "我的牙根本咬不动这个。",
		MOSQUITO =
		{
			GENERIC = "该死的吸血虫子。",
			HELD = "我抓到他了。",
		},
		MOSQUITOSACK = "一个血腥的袋子。里面装满了血。",
		MOUND =
		{
			DUG = "已经挖过了。",
			GENERIC = "下面有什么？",
		},
		NIGHTLIGHT = "它点燃时发出美丽的光芒。",
		NIGHTMAREFUEL = "啊~ 真提神。",
		NIGHTSWORD = "嚓嚓！",
		NITRE = "火药的三种成分之一...",
		ONEMANBAND = "这个拍子不错，你可以随它起舞。",
		PANDORASCHEST = "这是一个陷阱。",
		PANFLUTE = "我要唱一首疯狂之歌。",
		PAPYRUS = "一块空白画布。",
		PENGUIN = "不错的晚礼服。",
		PERD = "它对发酵的浆果上瘾。",
		PEROGIES = "这是我做的，必然很好。",
		PETALS = "我有摧毁美丽事物的习惯，不是吗？",
		PETALS_EVIL = "它充满噩梦的精华。",
		PICKAXE = "人人都爱挖点矿。",
		PIGGYBACK = "哦，背这个有损身份。",
		PIGKING = "这是一个将生活安排得井井有条的男人！",
		PIGMAN =
		{
			DEAD = "我给你取名叫“培根”。",
			FOLLOWER = "他很单纯，但他是我的。",
			GENERIC = "真是个口水直流的傻瓜。",
			GUARD = "他们开始变得有组织性了。",
			WEREPIG = "那只猪疯了。",
		},
		PIGSKIN = "当时不是他死就是我亡。",
		PIGTENT = "真脏。",
		PIGTORCH = "太好了。现在他们有火了。",
		PINECONE = 
		{
		    GENERIC = "一个更热爱户外的人或许能用这个来做点什么。",
		    PLANTED = "哈，它看起来属于大地。",
		},
		PITCHFORK = "完美主义者的理想工具。",
		PLANTMEAT = "愚蠢的骗局，只有傻子才会上当。",
		PLANTMEAT_COOKED = "它烤熟后就可以吃了。",
		PLANT_NORMAL =
		{
			GENERIC = "这是一株普通的植物。",
			GROWING = "它正在生长。",
			READY = "可以收获了。",
			WITHERED = "它受不了高温。",
		},
		POMEGRANATE = "通常我会找人来帮我播种。",
		POMEGRANATE_COOKED = "至少比原来好了点。",
		POMEGRANATE_SEEDS = "这种低贱的活不适合我。",
		POND = "我可以从池面倒影中看到我的脸。",
		POOP = "凡间所有生命都免不了吃喝拉撒。",
		PUMPKIN = "万圣节始终是我的最爱。",
		PUMPKINCOOKIE = "我有几个世纪没吃过好吃的饼干了。",
		PUMPKIN_COOKED = "至少比原来好了点。",
		PUMPKIN_LANTERN = "哎呀，你好，无头骑士先生。",
		PUMPKIN_SEEDS = "这种低贱的活不适合我。",
		PURPLEAMULET = "它与暗影交谈。",
		PURPLEGEM = "紫色能带来强大的力量。",
		RABBIT =
		{
			GENERIC = "我已经在这里太久了...它看上去确实很美味。",
			HELD = "别担心，小兔子。一切都在掌握之中。",
		},
		RABBITHOLE = 
		{
			GENERIC = "在那下面还有一个世界。",
			SPRING = "洞口自己垮掉了。",
		},
		RATATOUILLE = "粗粮。",
		RAZOR = "要是整个世界只有一个脖子该多好。",
		REDGEM = "红色带来火焰。",
		RED_CAP = "我忘记这东西有什么用了。",
		RED_CAP_COOKED = "有点苦。",
		RED_MUSHROOM =
		{
			GENERIC = "是红蘑菇。",
			INGROUND = "我得过会再来采它。",
			PICKED = "已经采光了。",
		},
		REEDS =
		{
			BURNING = "哎呀。",
			GENERIC = "起风时，就好像听到柳林中的风声。",
			PICKED = "没有芦苇管了。",
		},
        RELIC = 
        {
            GENERIC = "已经湮灭的文明的遗迹。",
            BROKEN = "只是岩石的碎块。",
        },
        RUINS_RUBBLE = "损毁的废墟。",
        RUBBLE = "只是岩石的碎块。",
		RESURRECTIONSTONE = "在那背后有一段故事...",
		ROBIN =
		{
			GENERIC = "红雀来自炎火之地。",
			HELD = "安静点，小鸟！",
		},
		ROBIN_WINTER =
		{
			GENERIC = "我不认识那只鸟。",
			HELD = "你给我安静点。",
		},
		ROBOT_PUPPET = "幸好是它不是我。",
		ROCK_LIGHT =
		{
			GENERIC = "这个熔岩坑的顶部已冷却成一层薄壳了。",
			OUT = "它看起来无害。",
			LOW = "火焰正在冷却。",
			NORMAL = "有点热。",
		},
		ROCK = "这是一块石头。",
		ROCKS = "嗯，现在我该对它们做什么？",
        ROOK = "可以安家的城堡。",
		ROPE = "你会认为这东西有更多用途。",
		ROTTENEGG = "真恶心。我为什么要把这个一直带在身上？",
		SANITYROCK =
		{
			ACTIVE = "我现在可以看到它真正的样子了！",
			INACTIVE = "有两种方法可以看到那个障碍物。",
		},
		SAPLING =
		{
			BURNING = "哎呀。",
			WITHERED = "没有东西能在热浪中幸免于难。",
			GENERIC = "柔软的木茎。",
			PICKED = "它会再长出来的。",
		},
		SEEDS = "我想这些东西不会把自己种下去。",
		SEEDS_COOKED = "我把它们烤死了。",
		SEWING_KIT = "一项精细高尚的事业。",
		SHOVEL = "这可是真正的先进技术。",
		SILK = "不论它来自哪里，至少可以做成不错的衣服。",
		SKELETON = "哈！我记得这个。",
		SKELETON_PLAYER = "大师一朝成枯骨。",
		SKULLCHEST = "那是个时髦的箱子。",
		SMALLBIRD =
		{
			GENERIC = "什么！？你想要什么？",
			HUNGRY = "你想要些吃的？",
			STARVING = "他很饿！",
		},
		SMALLMEAT = "这连一口都没有。",
		SMALLMEAT_DRIED = "我的牙根本咬不动这个。",
		SPEAR = "这是一根长矛。是的。",
		SPIDER =
		{
			DEAD = "啪叽。",
			GENERIC = "这东西基本上是个消化系统。",
			SLEEPING = "嘘！它醒来会饿的。",
		},
		SPIDERDEN = "它们在这里长大。",
		SPIDEREGGSACK = "黏乎乎的。",
		SPIDERGLAND = "真倒胃口。",
		SPIDERHAT = "蜘蛛的意志力真是太不坚定了。",
		SPIDERQUEEN = "或许我不该挡她的路。",
		SPIDER_WARRIOR =
		{
			DEAD = "啪叽。",
			GENERIC = "它是一个特殊品种。",
			SLEEPING = "我可不想弄醒它。",
		},
		SPOILED_FOOD = "曾经是食物，直到我浪费了它。",
		STATUEHARP = "并非我的最佳作品。",
		STATUEMAXWELL = "真是座不错的雕像。",
		STINGER = "它充满了毒液。",
		STEELWOOL = "这个应该用来清洁东西。",
		STRAWHAT = "这帽子看起来很土。",
		STUFFEDEGGPLANT = "适合国王...或至少是有王座的人的膳食。",
		SUNKBOAT = "船不该这么用！",
		SWEATERVEST = "虽然不是三件式的，但足够体面。",
		TAFFY = "几乎全是糖。",
		TALLBIRD = "它们是失败的实验产物。",
		TALLBIRDEGG = "因为这些东西的存在，高脚鸟很有领地意识。",
		TALLBIRDEGG_COOKED = "它的味道就像破碎的梦想。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "火不太热了。",
			GENERIC = "这里有一个活物。",
			HOT = "对你来说够热了？",
			LONG = "还要等好大一会。",
			SHORT = "时间就要到了...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "哦，真诱人。",
			PICKED = "它是用肮脏的牛毛做成的。",
		},
		TEENBIRD =
		{
			GENERIC = "长大后没那么可爱了。",
			HUNGRY = "它们肯定吃得很多。",
			STARVING = "饥饿的野兽是危险的。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "它还活着！",
			GENERIC = "我美丽的机器已经被拆成了很多块！",
			LOCKED = "现在打开它。",
			PARTIAL = "它仍然不完整。",
		},
		TELEPORTATO_BOX = "这是一个充满悲伤和痛苦的盒子。",
		TELEPORTATO_CRANK = "这是用来启动幽默成分的。",
		TELEPORTATO_POTATO = "这里面的齿轮非常小，但它们改变了真实世界的脉络。",
		TELEPORTATO_RING = "这是量子场的防护频带。",
		TELESTAFF = "当魔力沿正确的通道流动时，就能做出令人惊叹的事情。",
		TENTACLE = "我很高兴，它的其余部分还在下面。",
		TENTACLESPIKE = "呃。这东西真恶心。",
		TENTACLESPOTS = "这就是它们繁殖的方式。",
		TENTACLE_PILLAR = "这个到底能去到多深的地方？",
		TENTACLE_GARDEN = "这东西真古怪。",
        TENTACLE_PILLAR_ARM = "小触手？",
		TOPHAT = "一件精美的服饰用品。",
		TORCH = "它让查理无法接近。",
		TRAP = "只有最蠢的动物才会掉进这个陷阱。",
		TRAP_TEETH = "掉进去就会被猛揍一顿。",
		TRAP_TEETH_MAXWELL = "我确信我放置这东西是有原因的。",
		TREASURECHEST_TRAP = "这个嘛，看上去很可疑。",
		TREECLUMP = "我没办法通过那里。",
		TRINKET_1 = "这些东西肯定曾被加热到极高的温度。",
		TRINKET_10 = "这牙真令人恶心。",
		TRINKET_11 = "我没在听。",
		TRINKET_12 = "不戴几副手套我才不会碰那个。",
		TRINKET_2 = "这曾经对某个人很重要。",
		TRINKET_3 = "乱糟糟的一团。就像生活。",
		TRINKET_4 = "别用那种眼神看我。",
		TRINKET_5 = "小孩子的玩具。",
		TRINKET_6 = "只是没用的旧电线。",
		TRINKET_7 = "成年人玩这个可不太像话。",
		TRINKET_8 = "我更喜欢带链子的怀表。",
		TRINKET_9 = "我的西装不应该被粗糙的做工给毁了。",
		TRUNKVEST_SUMMER = "这不仅仅是件秋天穿的背心。",
		TRUNKVEST_WINTER = "在冬天要时尚点真是太不容易了。",
		TRUNK_COOKED = "至少这些鼻涕被烧光了。",
		TRUNK_SUMMER = "全是夏天的鼻涕。",
		TRUNK_WINTER = "为了装更多鼻涕，象鼻在冬天变厚了。",

		TURF_CARPETFLOOR = "这是一块高品质长毛绒地毯的样品！",
		TURF_CHECKERFLOOR = "这是我的自然栖息地。",
		TURF_DIRT = "好多尘土。",
		TURF_FOREST = "闻起来像泥土。",
		TURF_GRASS = "好多草。",
		TURF_MARSH = "到处都在滴水。",
		TURF_ROAD = "至少这个是有用的。",
		TURF_ROCKY = "有点粗糙。",
		TURF_SAVANNA = "好脏。",
		TURF_WOODFLOOR = "我更喜欢硬木。",

		TURF_CAVE="地皮。",
		TURF_FUNGUS="地皮。",
		TURF_SINKHOLE="地皮。",
		TURF_UNDERROCK="地皮。",
		TURF_MUD="地皮。",

		TURKEYDINNER = "真有节日气氛。",
		TWIGS = "虽然普通，但是很有用。",
		UMBRELLA = "伞柄是弯的！",
		WAFFLES = "早晨或晚上的美好开端。",
		WALL_HAY_ITEM = "口袋大小的墙体。是的。",
		WALL_STONE = "那些乌合之众再也进不来了。",
		WALL_STONE_ITEM = "口袋大小的墙体。是的。",
		WALL_WOOD_ITEM = "口袋大小的墙体。是的。",
		WALL_RUINS = "古老的墙。",
		WALL_RUINS_ITEM = "口袋大小的墙体。是的。",
		WALRUS = "你认不出我了？",
		WALRUSHAT = "苏格兰制造。",
		WALRUS_CAMP =
		{
			EMPTY = "冬天来的时候，我最好别在这里晃悠。",
			GENERIC = "海象肯定在不远的地方。",
		},
		WALRUS_TUSK = "我会让它有更好的用途。",
		WASPHIVE = "那个看起来很危险。",
		WETGOOP = "真没教养。",
		WINTERHAT = "令人失望的土气帽子。",
		WORMHOLE =
		{
			GENERIC = "知道其他部分长什么样子后感觉更糟糕。",
			OPEN = "我保证，它闻起来比看上去更糟糕。",
		},
		WORMHOLE_LIMITED = "它看上去生病了。",
		ACCOMPLISHMENT_SHRINE = "即使是他们，也造不出如此阴险的东西。",

		AERODYNAMICHAT = "相当时尚，哪怕算不上优雅。",
		ANTIVENOM = "中毒的解药。",
		ARMORCACTUS = "没什么能像这个一样清楚地表达“离我远点”的含义。",
		ARMORLIMESTONE = "它使我...行动迟缓。",
		ARMOROBSIDIAN = "我让火焰服从我的意志。",
		ARMORSEASHELL = "也许不是最坚固的，但它能遮住我的要害。",
		ARMOR_LIFEJACKET = "可悲的是，我高雅的风范不得不屈从于理性的需要。",
		ARMOR_SNAKESKIN = "相当帅气！",
		ARMOR_WINDBREAKER = "风在悲鸣。",
		ARMOUREDBOAT = "这艘船知道如何抵御重击。",
		BABYOX = "你这野兽不会得到我的什么优待。",
		BALLPHIN = "它们比一眼看上去的狡猾多了。",
		BAMBOO = "我想了好几种这个东西的用法。",
		BAMBOOTREE =
		{
			BURNT = "它长不回来了。",
			CHOPPED = "它需要时间恢复。",
			GENERIC = "它几乎可以穿过任何东西生长。",
		},
		BERMUDATRIANGLE = "它在召唤我驶进去。",
		BIGFISHINGROD = "也许现在我在捕猎游水肉类方面运气会好一点。",
		BIOLUMINESCENCE = "相当超自然，不是吗？",
		BLOWDART_FLUP = "很奇妙的新发明。",
		BLOWDART_POISON = "我将这个世界的恶意转过头来对付它自己了。",
		BLUBBER = "我相信我能...吃它...",
		BLUBBERSUIT = "这太没有尊严了。",
		BOATCANNON = "差不多是时候搞到这东西了。",
		BOATREPAIRKIT = "它将拖延我的船无法避免的腐朽。",
		BOAT_LANTERN = "它向四周发出怪异的光。",
		BOAT_TORCH = "晚上航海似乎不安全，但这个能提高一点安全性。",
		BOTTLELANTERN = "它们的生命在奴役中找到了意义。",
		BRAINJELLYHAT = "我觉得受到了启发。",
		BUOY = "它轻松地漂浮着。",
		BURIEDTREASURE = "哈，那么这是什么？",
		BUSH_VINE =
		{
			BURNT = "它的路走到了尽头。",
			CHOPPED = "油尽灯枯，暂时。",
			GENERIC = "这些东西占领了整个岛。",
		},
		CAPTAINHAT = "它让我想发出号令。",
		CARGOBOAT = "哈，有足够的呼吸空间。",
		CHIMINEA = "安全存放我辛苦得来的火焰。",
		CLOTHSAIL = "在我旅行时能用的上。",
		COCONADE =
		{
			BURNING = "我也许得寻找掩护。",
			GENERIC = "我预见了未来的死亡。",
		},
		COCONUT = 
		{
		    GENERIC = "可以对人的脑袋造成可观的伤害。",
		    PLANTED = "再也不能伤害任何人了。",
		},
		COCONUT_COOKED = "它可以让我暂时维持下去。",
		COCONUT_HALVED = "我把一个椰子变成了两个...太神奇了！",
		COFFEE = "非常期待。",
		COFFEEBEANS = "看到它们这个颜色真奇怪。",
		COFFEEBEANS_COOKED = "比生的好点，但可能有更好的方法处理它们？",
		COFFEEBOT = "它会执行与咖啡有关的命令。",
		COFFEEBUSH =
		{
			BARREN = "荒芜了。",
			GENERIC = "讨人喜欢的咖啡豆。",
			PICKED = "已经全部采摘了。",
			WITHERED = "已经枯萎了。",
		},
		COMPASS =
		{
			GENERIC="呃，没有读数。",
			N = "北。",
			S = "南。",
			E = "东。",
			W = "西。",
			NE = "东北。",
			SE = "东南。",
			NW = "西北。",
			SW = "西南。",
		},
		CORAL = "相当漂亮。",
		CORALREEF = "这里可能供养着许多的生命。",
		CORAL_BRAIN = "现在我可以利用它的思维力量了。",
		CORAL_BRAIN_ROCK = "我想知道它在思考什么？",
		CRAB =
		{
			GENERIC = "可以食用的甲壳动物。",
			HIDDEN = "螃蟹藏起来了。",
		},
		CRABHOLE = "它无法永远藏着。",
		CRATE = "也许我能把它撬开。",
		CUTLASS = "绅士的武器。",
		DEAD_SWORDFISH = "也许它应该多上上防御课。",
		DEPLETED_BAMBOOTREE = "不复存在了。",
		DEPLETED_BUSH_VINE = "不复存在。",
		DEPLETED_GRASS_WATER = "那就是曾经的一切了。",
		DEVTOOL = "真古怪。",
		DEVTOOL_NODEV = "我怕我掌握不了它。",
		DOUBLE_UMBRELLAHAT = "这个看起来太傻了。",
		DOYDOY = "这个悲惨的生物没有幸存的希望。",
		DOYDOYBABY = "现在它们的数量将更多。",
		DOYDOYEGG = "嗯，繁衍濒临灭绝的物种还是享用点心呢？",
		DOYDOYEGG_COOKED = "一份小点心总是最好的选择。",
		DOYDOYEGG_CRACKED = "哎呀。",
		DOYDOYFEATHER = "把它插在周日帽上会很漂亮。",
		DOYDOYNEST = "你认为它们有多大的机会？",
		DRAGOON = "你不知道我是谁吗？",
		DRAGOONDEN = "我没有理由打扰它们。",
		DRAGOONEGG = "它散发出压抑的热量。",
		DRAGOONHEART = "心只能带来疼痛。",
		DRAGOONSPIT = "真粗野。",
		DUBLOON = "它们互相碰撞发出的叮铃响声让人心满意足。",
		DUG_BAMBOOTREE = "我想我该为这个找个地方。",
		DUG_BUSH_VINE = "我该为这个找个合适的地方。",
		DUG_COFFEEBUSH = "这个值得再种下去。",
		DUG_ELEPHANTCACTUS = "我最好别带着这个奔跑。",
		EARRING = "如果我打了耳洞，戴上这个会很时尚。",
		ELEPHANTCACTUS = "它不会像这样射人了。",
		ELEPHANTCACTUS_ACTIVE = "寻找掩护！",
		ELEPHANTCACTUS_STUMP = "不在了就好。",
		FABRIC = "我把竹子做成了有用的东西。",
		FEATHERSAIL = "我想这比用手划好。",
		FISHINHOLE = "它们在我的肚子里会满足得多。",
		FISH_RAW = "需要在火上烤一下。",
		FISH_RAW_SMALL = "我落魄到只能吃这个了？",
		FISH_RAW_SMALL_COOKED = "...干杯。",
		FLAMEGEYSER = "那真是奇观。",
		FLOTSAM = "也许我能想办法把它钓过来。",
		FLUP = "那东西不配做我的对手。",
		FRESHFRUITCREPES = "值得用银器来享用。可悲的是，我只有双手。",
		FROG_POISON = "我最好教它一些礼貌。",
		GASHAT = "隔离臭气。",
		GOLDENMACHETE = "我一直想像个土豪一样的砍东西。",
		GRASS_WATER = "它一部分在水下。",
		HAIL_ICE = "有点冷。",
		HOUNDFIRE = "一团咬人的火焰！",
		ICEMAKER =
		{
			HIGH = "它正在努力为我制冰。",
			LOW = "我最好给它加点燃料。",
			NORMAL = "它看起来在干它的工作。",
			OUT = "它没在干它的工作。",
			VERYLOW = "它就快支撑不住了。",
		},
		IRONWIND = "谢天谢地，我有地方要去！",
		JELLYFISH = "好奇怪的小动物啊。",
		JELLYFISH_COOKED = "我想，这应该能吃。",
		JELLYFISH_DEAD = "我更喜欢死掉的它。",
		JELLYFISH_PLANTED = "相当令人震惊。",
		JELLYJERKY = "我实际上不介意这个？",
		JUNGLETREE =
		{
			BURNING = "它不再留恋这个世界。",
			BURNT = "下辈子吧，也许。",
			CHOPPED = "我把它用在了自己的用途。",
			GENERIC = "我相信它希望我把它砍倒。",
		},
		JUNGLETREESEED =
        {
            GENERIC = "理论上来说，我可以再种下这个。",
            PLANTED = "好。我是对的。",
        },
		KNIGHTBOAT = "服从我，笨蛋！",
		KRAKEN = "你将向我屈服。",
		KRAKENCHEST = "现在该看看我的奖励了。",
		KRAKEN_TENTACLE = "你竟敢碰我？",
		LAVAPOOL = "非常温暖。",
		LIMESTONE = "也许这个海洋生命的死亡终有用处。",
		LIMPETROCK =
		{
			GENERIC = "必要时可用作食物来源。",
			PICKED = "现在只是块石头了。",
		},
		LIMPETS = "黏滑而可消化。",
		LIMPETS_COOKED = "一种美味？真的吗？",
		LIVINGJUNGLETREE = "这里的一切都很平常。",
		TREEGUARD = "停止这种愚蠢的举动。",
		LOBSTER = "这顿饭看上去还像那么回事。",
		LOBSTERHOLE = "现身吧，美味的生物。",
		LOBSTER_DEAD = "太好了。",
		LOBSTER_DEAD_COOKED = "我忘了我的围兜。",
		LOGRAFT = "似乎有禁止使用这个的规定。",
		LUGGAGECHEST = "在我看来挺上档次的手提箱。",
		MACHETE = "说实话，我用刀的功夫一直不怎么样。",
		MAGIC_SEAL = "我感觉到它蕴含着强大的力量。",
		MAGMAROCK = "好吧，一块岩石。",
		MAGMAROCK_FULL = "好吧，一块岩石。",
		MAGMAROCK_GOLD = "这块石头豪华得多。",
		MAGMAROCK_GOLD_FULL = "这块石头豪华得多。",
		MANGROVETREE = "像其他树一样...不过是湿的。",
		MANGROVETREE_BURNT = "它已经被摧毁了。",
		MARSH_PLANT_TROPICAL = "对我没什么用。",
		MERMFISHER = "我对他没有意见。",
		MERMHOUSE_FISHER = "我想每个人都需要一个住的地方...",
		MESSAGEBOTTLE = "这个原始的通信系统是什么？",
		MESSAGEBOTTLEEMPTY = "只要有充足的时间，我能在里面建一艘船。",
		MONKEYBALL = "这个东西可以用来做什么？",
		MONSTERTARTARE = "它算不上色香俱佳。",
		MOSQUITOSACK_YELLOW = "我要拿回那些血，谢谢。",
		MOSQUITO_POISON = "我要避免被这个家伙叮咬。",
		MUSSEL = "在某个地方...它们被当作美味佳肴。",
		MUSSELBOUILLABAISE = "我很期待吃一顿大餐。",
		MUSSEL_COOKED = "现在看起来不太会危害健康了。",
		MUSSEL_FARM =
		{
			GENERIC = "这样采集食物似乎很方便。",
			STICKPLANTED = "它们没有察觉到即将来临的死亡。",
		},
		MUSSEL_STICK = "贻贝无法抗拒它。",
		MYSTERYMEAT = "相当恶心。",
		NEEDLESPEAR = "非常锋利。",
		OBSIDIAN = "多么令人愉悦的颜色。",
		OBSIDIANAXE = "它似乎燃烧的时候效果最好。",
		OBSIDIANCOCONADE = "这绝对是过度伤害。",
		OBSIDIANFIREPIT =
		{
			EMBERS = "我应该注意的。",
			GENERIC = "那石头就是这样用的。",
			HIGH = "熊熊燃烧的火。",
			LOW = "火势小了。",
			NORMAL = "它烧得别具风格。",
			OUT = "变冷了。",
		},
		OBSIDIANMACHETE = "用这个来耕种似乎很危险。",
		OBSIDIANSPEARGUN = "弹射型火焰。我挺喜欢它。",
		OBSIDIAN_WORKBENCH = "这个工作台点燃了我心中创意的火花...",
		OCTOPUSCHEST = "它看起来...烂掉了。",
		OCTOPUSKING = "我可以利用他的慷慨。",
		OX = "它臭哄哄的，而且非常蠢笨。",
		OXHAT = "有时必须为了功用牺牲外形。",
		OX_FLUTE = "天哪，我有一段时间没玩音乐了。",
		OX_HORN = "那只野兽没有机会。",
		PACKIM = "它能派得上用场并且心甘情愿地受奴役，这多少缓和了它那令人不快的外表。",
		PACKIM_FISHBONE = "我想我应该留住它。",
		PALMLEAF = "现在我只需要仆人来为我扇风！",
		PALMLEAF_HUT = "呼。",
		PALMTREE =
		{
			BURNING = "它不再留恋这个世界。",
			BURNT = "下辈子吧，也许。",
			CHOPPED = "我把它用在了自己的用途。",
			GENERIC = "多么豪华。",
		},
		PARROT = "嗯，色彩斑澜。",
		PARROT_PIRATE = "也许我能让他闭嘴。",
		PEACOCK = "这个生物的表演技巧不错。",
		PEG_LEG = "用来敲人不错。",
		PIKE_SKULL = "没劲。",
		PIRATEGHOST = "我不会重蹈覆辙！",
		PIRATEHAT = "这帽子是否引人发笑？",
		PIRATEPACK = "我想它能用。",
		PIRATIHATITATOR =
		{
			BURNT = "尘归尘，土归土。",
			GENERIC = "多么令人着迷的装置。",
		},
		POISONHOLE = "我从这里就看得很清楚了...不需要再靠近。",
		PORTAL_SHIPWRECKED = "一无所用！",
		PRIMEAPE = "这个可怜的生物只有一丁点智力。",
		PRIMEAPEBARREL = "我要远离那个东西。",
		RAFT = "太不安全了，我不喜欢。",
		RAWLING = "哦，不错。会说话的一袋填充物。",
		REDBARREL = "它可能突然爆炸。",
		ROCK_CHARCOAL = "我不禁深深钦佩大自然的创造。",
		ROCK_OBSIDIAN = "它拒绝屈服于我的工具。",
		ROWBOAT = "可惜是手动操作的。",
		SAIL = "有这个在我背后，航行会很顺利。",
		SAIL_STICK = "一根棍子，大概是航海用的。",
		SAND = "石头被粉碎得如此彻底，面目全非。",
		SANDBAG = "把水挡在外面的一袋沙土。",
		SANDBAGSMALL = "把水挡在外面的一袋沙土。",
		SANDBAGSMALL_ITEM = "一袋我可以携带的沙土。",
		SANDBAG_ITEM = "一袋我可以携带的沙土。",
		SANDHILL = "一小堆黄沙。",
		SAND_CASTLE =
		{
			GENERIC = "我发现那完全没有乐趣可言。我发誓。",
			SAND = "装潢用的沙。",
		},
		SEAGULL = "它很吵而且令人生气。",
		SEAGULL_WATER = "相当不文明。",
		SEASACK = "它不会让我更强壮，但会给我更多口袋。",
		SEASHELL = "拿着它让我感觉像个游客。",
		SEASHELL_BEACHED = "对我来说有点俗气。",
		SEATRAP = "好奇最终会打败你。",
		SEAWEED = "海里的垃圾。",
		SEAWEED_COOKED = "我讨厌吃这个。",
		SEAWEED_DRIED = "呃。",
		SEAWEED_PLANTED = "它在这里茁壮成长。",
		SHADOWSKITTISH_WATER = "噢，不好。",
		SHARKITTEN = "一只迷人的小怪兽。",
		SHARKITTENSPAWNER =
		{
			GENERIC = "在我提到吃的东西时，沙堆有了动静。",
			INACTIVE = "一堆普通的沙。",
		},
		SHARK_FIN = "辉煌杀戮的战利品。",
		SHARK_GILLS = "我想它们值得拥有。",
		SHARK_TEETHHAT = "我尊重这种时尚选择。",
		SHARX = "问题不是我“是否”会打败它，而是什么时候会打败它。",
		SHIPWRECKED_ENTRANCE = "我希望你准备好了。",
		SHIPWRECKED_EXIT = "再会。",
		SLOTMACHINE = "不可否认，我有玩弄命运的嗜好。",
		SLURPERPELT = "不错的皮子。",
		SNAKE = "一只凶残又优雅的动物。",
		SNAKEDEN =
		{
			BURNT = "它的路走到了尽头。",
			CHOPPED = "油尽灯枯，暂时。",
			GENERIC = "这些东西占领了整个岛。",
		},
		SNAKEOIL = "也许我能用这个赚钱。",
		SNAKESKIN = "这质感令人愉悦。",
		SNAKESKINHAT = "相当时尚，真的。",
		SNAKESKINSAIL = "用于轻松旅行。",
		SNAKE_FIRE = "什么东西给那条蛇加热了。",
		SNAKE_POISON = "也许我会跟那家伙保持更远的安全距离。",
		SOLOFISH = "它闻起来像落水狗。",
		SPEARGUN = "这个弹射装置可能很有用。",
		SPEARGUN_POISON = "我确信它能造成额外的打击。",
		SPEAR_LAUNCHER = "这个弹射装置可能很有用。",
		SPEAR_OBSIDIAN = "我确信它能造成火热的打击。",
		SPEAR_POISON = "我确信它能造成额外的打击。",
		SPOILED_FISH = "我认为应该扔掉这个。",
		STUNGRAY = "它闻起来糟透了。",
		SUNKEN_BOAT =
		{
			ABANDONED = "它有凶猛的守卫。",
			GENERIC = "它再也不能航行了。",
		},
		SUNKEN_BOAT_BURNT = "一切事物都将在时光中消亡。",
		SUNKEN_BOAT_TRINKET_1 = "就像它看上去那样。呃...它看起来像什么？",
		SUNKEN_BOAT_TRINKET_2 = "我感觉它仿佛在嘲笑我的处境。",
		SUNKEN_BOAT_TRINKET_3 = "它没有明显的功用。",
		SUNKEN_BOAT_TRINKET_4 = "先进的小玩意儿。",
		SUNKEN_BOAT_TRINKET_5 = "它浸在污水里之前可能就很难看。",
		SUPERTELESCOPE = "这能帮助我了解地形。",
		SWEETPOTATOSOUFFLE = "为什么，这个看上去味道还行！",
		SWEET_POTATO = "准备好烹饪了。",
		SWEET_POTATO_COOKED = "店里买的味道就是不一样。",
		SWEET_POTATO_PLANTED = "我吃过更糟糕的东西。远比这个糟糕。",
		SWEET_POTATO_SEEDS = "我把这些扔在土里，也许会长出什么东西。",
		SWIMMINGHORROR = "我已经受够了你的同类了，朋友。",
		SWORDFISH = "啊，一个搏击陪练！",
		TELEPORTATO_SW_BASE = "我看到它有条件成为某个相当酷炫的东西。",
		TELEPORTATO_SW_BOX = "另一块拼图。",
		TELEPORTATO_SW_CRANK = "好极了。现在不长了。",
		TELEPORTATO_SW_POTATO = "我承认它的确有点可笑。",
		TELEPORTATO_SW_RING = "啊，另一件。",
		TELESCOPE = "这能帮助我了解地形。",
		THATCHPACK = "虽然不多，但有额外的空间总比没有好。",
		TIDALPOOL = "它比看上去深多了。",
		TIDAL_PLANT = "长得有点矮。",
		TIGEREYE = "绅士不戴手套不会碰的东西。",
		TIGERSHARK = "名字起得真贴切。",
		TOUCAN = "色彩斑澜的害鸟。",
		TRAWLNET = "我觉得用这个没什么坏处。",
		TRAWLNETDROPPED =
		{
			GENERIC = "想想我要做的饭。",
			SOON = "直至深处...",
			SOONISH = "它正在慢慢下潜。",
		},
		TRIDENT = "适合海洋皇室的叉子。",
		TRINKET_13 = "受欢迎的海水加工产物。",
		TRINKET_14 = "这看起来像个坏巫毒人偶。",
		TRINKET_15 = "它只有四根弦。",
		TRINKET_16 = "字母和数字...某种密码？",
		TRINKET_17 = "它浸在污水里之前可能就很难看。",
		TRINKET_18 = "来一点强力胶，就能使它成为一件漂亮的中心装饰品。",
		TRINKET_19 = "不是红色也不是蓝色。",
		TRINKET_20 = "就像它看上去那样。呃...它看起来像什么？",
		TRINKET_21 = "泡热水澡的时候用用也许不错...",
		TRINKET_22 = "看起来像是在闭塞之地的跳蚤市场上找到的东西。",
		TRINKET_23 = "它现在不能与任何人通信了。",
		TROPICAL_FISH = "烤串是它的归属。",
		TUNACAN = "大概里面含有鱼。",
		TURBINE_BLADES = "它似乎经过巧妙的工程设计。",
		TURF_ASH = "它似乎是某种地皮。",
		TURF_BEACH = "它似乎是某种地皮。",
		TURF_DESERTDIRT = "它似乎是某种地皮。",
		TURF_FUNGUS_GREEN = "它似乎是某种地皮。",
		TURF_FUNGUS_RED = "它似乎是某种地皮。",
		TURF_JUNGLE = "它似乎是某种地皮。",
		TURF_MAGMAFIELD = "它似乎是某种地皮。",
		TURF_MEADOW = "它似乎是某种地皮。",
		TURF_SNAKESKINFLOOR = "它似乎是某种地皮。",
		TURF_SWAMP = "它似乎是某种地皮。",
		TURF_TIDALMARSH = "它似乎是某种地皮。",
		TURF_VOLCANO = "它似乎是某种地皮。",
		TWISTER = "我可不想被吸进去。",
		TWISTER_SEAL = "它，呃...挺可爱？",
		VENOMGLAND = "这会是解药吗？",
		VINE = "盘根错节。",
		VOLCANO = "我尊重它的力量。",
		VOLCANOSTAFF = "它在我的手里感觉像到家了一样。",
		VOLCANO_ALTAR =
		{
			GENERIC = "它好像是个献祭的地方。",
			OPEN = "我敢摆布超出我掌控的力量吗？",
		},
		VOLCANO_ALTAR_BROKEN = "真是遗憾。",
		VOLCANO_ALTAR_TOWER = "多么迷人的结构。",
		VOLCANO_EXIT = "我必须离开。",
		VOLCANO_SHRUB = "如果我有任何怜悯之心，我会献给这棵树。",
		WALLYINTRO_DEBRIS = "这是什么鬼东西？",
		WALL_LIMESTONE = "它撑得住。",
		WALL_LIMESTONE_ITEM = "我应该从哪里开始建造我的堡垒？",
		WATERMELON_SEEDS = "我也许能种植这些。",
		WATERYGRAVE = "并不是所有人都能找到最终的安息之所。",
		WHALE_BLUE = "向我投降吧。",
		WHALE_BUBBLES = "你泄露了自己的踪迹，伙计。",
		WHALE_CARCASS_BLUE = "大小真的不重要！",
		WHALE_CARCASS_WHITE = "我战胜了它！",
		WHALE_TRACK = "我正在紧追不舍！",
		WHALE_WHITE = "我们又见面了。",
		WILBUR_CROWN = "里面很脏。",
		WILBUR_UNLOCK = "好吧，我想现在没法把你送回去了。",
		WILDBORE = "我会轻松干掉那只畜生。",
		WILDBOREHEAD = "令人愉快的氛围。",
		WILDBOREHOUSE = "这就是这里所谓的建筑？",
		WIND_CONCH = "外表漂亮，内蕴毁灭。",
		WOODLEGSBOAT = "似乎很可靠。",
		WOODLEGSHAT = "神气活现...",
		WOODLEGSSAIL = "不错的帆。",
		WOODLEGS_CAGE = "从某种意义上来说，我们都是囚徒。",
		WOODLEGS_KEY1 = "脆弱易碎。",
		WOODLEGS_KEY2 = "上等黄金做的钥匙。",
		WOODLEGS_KEY3 = "只是一般的铁。",
		WRECK = "它没有机会。",
		CALIFORNIAROLL = "我们又见面了，螃蟹。",
	},
	DESCRIBE_GENERIC = "谁来介绍一下这个？",
	DESCRIBE_TOODARK = "我在黑暗中什么都看不见！",
	DESCRIBE_SMOLDERING = "不久后它就会着火的。",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "刚刚太不明智了。",
	},
}
