return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "它像我們一樣多毛，但我認為它不喜歡剃毛。",
			GENERIC = "現在不是剃毛的時間！",
			NOBITS = "這下剃乾淨了。",
		},
		STORE =
		{
			GENERIC = "全塞滿了！",
			NOTALLOWED = "這違規了。",
		},
		WRITE =
        {
            GENERIC = "我現在不能在那上面寫字。",
        },
		RUMMAGE =
        {   
            GENERIC = "沒辦法，超出了我們的能力範圍。",  
        },
		COOK =
        {
            GENERIC = "我不想做飯，媽媽總是說廚房很危險！",
            TOOFAR = "走近點！",
        },
        GIVE =
        {
            DEAD = "唔，我們也許該留著它。",
            SLEEPING = "呃...它現在睡得像頭豬！",
            BUSY = "我們可以在它完事後再試試。",
        },
        CHANGEIN =
        {
            GENERIC = "現在不要，我們很舒服。",
            BURNING = "哇哦！火熱的時裝！",
        },
        TEACH =
        {
            KNOWN = "我們倆肯定有一個知道那個。",
            CANTLEARN = "我們不明白...",
        },
		REPAIRBOAT =
		{
			GENERIC = "沒必要。我們的船已經好好地漂著了。",
		},
	},
	ACTIONFAIL_GENERIC = "媽媽告訴我絕對不可以那樣做。",
	ANNOUNCE_MAGIC_FAIL = "我覺得這東西不喜歡它。",
	ANNOUNCE_ADVENTUREFAIL = "遊戲時間結束。",
	ANNOUNCE_BEES = "滿世界飛的螫人的東西！",
	ANNOUNCE_BOOMERANG = "如果沒有接住它，它就會傷害到我們。",
	ANNOUNCE_CHARLIE = "誰在那裡?!",
	ANNOUNCE_CHARLIE_ATTACK = "啊！黑暗裡有怪物！",
	ANNOUNCE_COLD = "嘶~~~蜘蛛的毛髮不是很保暖。",
	ANNOUNCE_HOT = "像地獄一樣熱！",
	ANNOUNCE_CRAFTING_FAIL = "我們缺少一些東西。",
	ANNOUNCE_DEERCLOPS = "聽起來好像是個巨無霸。",
	ANNOUNCE_DUSK = "快到睡覺的時間了。",

	ANNOUNCE_EAT =
	{
		GENERIC = "美味盡在我們的肚子裡！",
		PAINFUL = "哎喲，肚子疼。",
		SPOILED = "已經過期了。",
		STALE = "一點都不新鮮，就像媽媽的剩飯剩菜一樣。",
		INVALID = "那不像是我們能吃的食物。",
		YUCKY = "我們打死也不要吃那玩意。",
	},
	ANNOUNCE_ENTER_DARK = "什麼都看不到！我想要我的夜燈。",
	ANNOUNCE_ENTER_LIGHT = "唷，重見光明！",
	ANNOUNCE_FREEDOM = "我們成功了！",
	ANNOUNCE_HIGHRESEARCH = "我學了好多東西！",
	ANNOUNCE_HOUNDS = "狗狗要來了！",
	ANNOUNCE_HUNGRY = "點心時間到！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "新鮮的足跡！",
	ANNOUNCE_HUNT_LOST_TRAIL = "動物已經消失無蹤了。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "太多泥了，不好追蹤。",
	ANNOUNCE_INV_FULL = "我們的口袋都裝滿了！",
	ANNOUNCE_KNOCKEDOUT = "嗷，我們的頭！",
	ANNOUNCE_LOWRESEARCH = "這只能教教不懂事的小孩。",
	ANNOUNCE_MOSQUITOS = "走開，去吸別人的血！",
	ANNOUNCE_NODANGERSLEEP = "附近有怪物出沒，無法睡覺！",
	ANNOUNCE_NODAYSLEEP = "現在是白天，不是睡覺時間。",
	ANNOUNCE_NODAYSLEEP_CAVE = "我們還不準備睡覺。",
	ANNOUNCE_NOHUNGERSLEEP = "肚子餓得咕咕叫，睡不著。",
	ANNOUNCE_NOSLEEPONFIRE = "媽媽總是說：「不要在正在燃燒的建築裡面睡覺。」",
	ANNOUNCE_NODANGERSIESTA = "附近有怪物出沒，無法午休！",
	ANNOUNCE_NONIGHTSIESTA = "我們不能睡午覺，現在是晚上！",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "不能在天亮之前午休！",
	ANNOUNCE_NOHUNGERSIESTA = "肚子餓得咕咕叫，無法午休。",
	ANNOUNCE_NO_TRAP = "小菜一碟。",
	ANNOUNCE_PECKED = "壞鳥！",
	ANNOUNCE_QUAKE = "我認為這不是我們的肚子在叫。",
	ANNOUNCE_RESEARCH = "感覺好像回到了學校裡。",
	ANNOUNCE_SHELTER = "大樹，保護我們！",
	ANNOUNCE_THORNS = "哎喲！",
	ANNOUNCE_BURNT = "哎呀，好熱呀！",
	ANNOUNCE_TORCH_OUT = "哎呀，火把熄滅了！",
	ANNOUNCE_FAN_OUT = "哦，扇風的東西已經壞了。",
    ANNOUNCE_COMPASS_OUT = "啊哦，我把它弄壞了。",
	ANNOUNCE_TRAP_WENT_OFF = "哎呀！",
	ANNOUNCE_UNIMPLEMENTED = "咳！還需要一些時間。",
	ANNOUNCE_WORMHOLE = "那個洞太可怕了！",
	ANNOUNCE_CANFIX = "\n我們可以修好它。",
	ANNOUNCE_ACCOMPLISHMENT = "我們簡直無所不能！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我們是超級英雄！",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "對你來說養分還不夠，是嗎？",
	ANNOUNCE_TOOL_SLIP = "喂！我們正在用那個呢！",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "我們是無敵的！",

	ANNOUNCE_DAMP = "水花四濺。",
	ANNOUNCE_WET = "我們身上濕答答的，真不舒服。",
	ANNOUNCE_WETTER = "濕得就像一個我們爬不出去的浴缸。",
	ANNOUNCE_SOAKED = "我們渾身濕透了！",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"八隻眼睛都看不懂。",
	},
	ANNOUNCE_OTHER_WORLD_PLANT = "我們不能在這裡種植它。",
	ANNOUNCE_BOAT_DAMAGED = "我們的船受損了！",
	ANNOUNCE_BOAT_SINKING = "下沉，下沉，我們正在下沉！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "救命！我們不會游泳！",
	ANNOUNCE_CRAB_ESCAPE = "你這個狡猾的蝸牛...呃不對，是螃蟹！",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "我們的腿在褲子裡發抖！",
	ANNOUNCE_MAPWRAP_RETURN = "好可怕！",
	ANNOUNCE_MAPWRAP_WARN = "我不喜歡這樣...",
	ANNOUNCE_MORETREASURE = "哇！可以繼續尋寶了！",
	ANNOUNCE_OTHER_WORLD_TREASURE = "我認為我在這裡找不到這個寶藏。",
	ANNOUNCE_SHARX = "海裡的卑鄙獵犬！離我們遠點！",
	ANNOUNCE_TRAWL_FULL = "讓我們把網拉上來！",
	ANNOUNCE_TREASURE = "一張地圖！我們應該按照它走！",
	ANNOUNCE_VOLCANO_ERUPT = "天上下著火雨！",
	ANNOUNCE_WAVE_BOOST = "噫！！！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "我們正在追蹤！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "它回家了...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "波濤太洶湧了！",


	BATTLECRY =
	{
		GENERIC = "準備戰鬥！",
		PIG = "我們討厭它！可怕的豬！",
		PREY = "我們要將你捉到我們的蜘蛛網裡！",
		SPIDER = "嘿，想玩玩嗎？",
		SPIDER_WARRIOR = "我們為什麼不能好好相處呢？！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "記住了，我們本來會贏的！",
		PIG = "蠢豬，我們改日再戰。",
		PREY = "好快的傢伙！",
		SPIDER = "實際上，我們並不想傷害你。",
		SPIDER_WARRIOR = "冷靜，我的朋友。",
	},
	
	DESCRIBE_GENERIC = "我們能玩這個嗎？",
	DESCRIBE_TOODARK = "我們的所有眼睛都停止了工作！",
	DESCRIBE_SMOLDERING = "啊哦。我聞到了燃燒的味道！",
	
	DESCRIBE =
	{
        INVENTORYGRAVE = "他們只是在長眠。",
		INVENTORYMOUND = "他們只是在長眠。",

		LAVA_POND_ROCK = "哇！一塊石頭！",
		LAVA_POND_ROCK2 = "哇！一塊石頭！",
		LAVA_POND_ROCK3 = "哇！一塊石頭！",
		LAVA_POND_ROCK4 = "哇！一塊石頭！",
		LAVA_POND_ROCK5 = "哇！一塊石頭！",
		LAVA_POND_ROCK6 = "哇！一塊石頭！",
		LAVA_POND_ROCK7 = "哇！一塊石頭！",

		SPIDER_WARRIOR =
		{
			GENERIC = "你能教我們戰鬥技巧嗎？",
			SLEEPING = "寧靜的夜晚。",
			DEAD = "原諒我們。",
		},
        GLOMMER = "眼睛很特別。",
        GLOMMERFLOWER = 
        {
        	GENERIC = "不是很好聞。",
        	DEAD = "我太早下結論了。現在它更難聞了。",
        },
        GLOMMERWINGS = "我希望自己最後至少也能長出一對翅膀。唉。",
        GLOMMERFUEL = "好噁心！",
        BELL = "這個鈴鐺剛剛好。",
        STATUEGLOMMER = 
        {	
        	GENERIC = "奇怪蟲子的雕像。",
        	EMPTY = "認命吧，石頭蟲子！",
    	},

		WEBBERSKULL = "這東西是怎麼到這裡來的？",
		WORMLIGHT = "它在發光。",
		WORMLIGHT_LESSER = "我打賭你不敢吃它！",
		WORM =
		{
		    PLANT = "總感覺有什麼不對勁呢？",
		    DIRT = "一堆泥土，沒什麼大不了。",
		    WORM = "可怕的爬行動物！",
		},
		WORMLIGHT_PLANT = "總感覺有什麼不對勁呢？",
		MOLE =
		{
			HELD = "你覺得舒服嗎？",
			UNDERGROUND = "出來一起玩吧！",
			ABOVEGROUND = "你好啊，小傢伙！",
		},
		MOLEHILL = "藏身之所。",
		MOLEHAT = "我可以看到很遠很遠的地方。",
		MOONROCKNUGGET = "漂亮！",
		ROCK_MOON = "漂亮！",

		EEL = "淡水蛇。",
		EEL_COOKED = "我們可以吃下它。",
		UNAGI = "我們有這麼多條手臂，這簡直是小菜一碟。",
		EYETURRET = "不准再看我！",
		EYETURRET_ITEM = "醒醒！",
		MINOTAURHORN = "摸起來很軟。",
		MINOTAURCHEST = "好大一個寶箱！",
		THULECITE_PIECES = "碎成小塊的奇特石頭。",
		POND_ALGAE = "只是一株很普通的池塘植物。",
		GREENSTAFF = "魔力拆解器。",
		POTTEDFERN = "這盆蕨類植物很漂亮，媽媽肯定喜歡。",

		THULECITE = "奇特的石頭！",
		ARMORRUINS = "輕便又好用的護甲。",
		RUINS_BAT = "我們將粉碎你！",
		RUINSHAT = "現在我們是國王了。",
		BISHOP_NIGHTMARE = "噩夢主教。",
		ROOK_NIGHTMARE = "你騙不了我們的。",
		KNIGHT_NIGHTMARE = "好騎士，晚安。",
		MINOTAUR = "別愁眉苦臉的。",
		SPIDER_DROPPER = "那兒住著我們的朋友。",
		NIGHTMARELIGHT = "這種夜燈不太適合我。",
		NIGHTSTICK = "夜間照明燈，照亮夜晚！",
		GREENGEM = "愛死這個綠東西了。",
		RELIC = "Reminds me of home, if I had lived in ancient times.",
		RUINS_RUBBLE = "We can repair it!",
		MULTITOOL_AXE_PICKAXE = "雙重功能。",
		ORANGESTAFF = "有了瞬移，我們的這麼多條腿就可以休息一下了。",
		YELLOWAMULET = "好東西，還會發光。",
		GREENAMULET = "開始建造吧！",
		SLURPERPELT = "像一小塊地毯。",	

		SLURPER = "長滿毛的長舌怪物！",
		SLURPER_PELT = "像一小塊地毯。",
		ARMORSLURPER = "把我們的肚子勒得好緊！",
		ORANGEAMULET = "腿越多越省事，這個東西也是一樣的效果。",
		YELLOWSTAFF = "我們召喚你，溫暖的光團！",
		YELLOWGEM = "黃色的寶石。",
		ORANGEGEM = "找到你了，橙寶石，你很開心吧？",
		TELEBASE = 
		{
			VALID = "Teleportation, away!",
			GEMS = "It needs s'more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks prepped.",
			GEMS = "Still needs a gem.",
		},
		STAFFLIGHT = "舒服。",
	
        ANCIENT_ALTAR = "古老而充滿神秘感。",

        ANCIENT_ALTAR_BROKEN = "已經被破壞了。",

        ANCIENT_STATUE = "它在奇怪地顫動。",

        LICHEN = "它喜歡長在這裡。",
		CUTLICHEN = "我喜歡苔蘚。",

		CAVE_BANANA = "一提香蕉。",
		CAVE_BANANA_COOKED = "熱呼呼的香蕉糊。",
		CAVE_BANANA_TREE = "當然，這是洞穴中生長的一種典型樹木。",
		ROCKY = "喀嚓喀嚓！",
		
		COMPASS =
		{
			GENERIC= "我們沒法讀取讀數！",
			N = "北！",
			S = "南！",
			E = "東！",
			W = "西！",
			NE = "東北！",
			SE = "東南！",
			NW = "西北！",
			SW = "西南！",
		},

		NIGHTMARE_TIMEPIECE =
		{
			CALM = "一切風平浪靜。",
			WARN = "有事情要發生了。",
			WAXING = "魔法能量越來越強烈了！",
			STEADY = "暫時穩定了。",
			WANING = "洞下面有魔法能量存在。",
			DAWN = "回來吧，白晝！",
			NOMAGIC = "這裡魔法能量不強。",
		},

		HOUNDSTOOTH="現在我們可以用這牙齒來撕咬東西了。",
		ARMORSNURTLESHELL="我們是一隻巨型蜘蛛！穿著蝸殼的巨型蜘蛛！",
		BAT="有著尖嗓門的討厭傢伙！",
		BATBAT = "揮舞那蝙蝠之翼吧，就像你天生就會做的那樣。",
		BATWING="這東西讓我變得很怪。",
		BATWING_COOKED="味道像雞肉。",
		BATCAVE= "噢，它們躲在那裡面！",
		BEDROLL_FURRY="真懷念能夠裹著睡袋睡覺的日子。",
		BUNNYMAN="跳吧，小兔子。",
		FLOWER_CAVE="哇哦，發光的花球！",
		FLOWER_CAVE_DOUBLE="哇哦，發光的花球！",
		FLOWER_CAVE_TRIPLE="哇哦，發光的花球！",
		GUANO="蝙蝠糞便。",
		LANTERN="太陽握在了我們手中。",
		LIGHTBULB="又明亮又好吃。",
		MANRABBIT_TAIL="我們覺得很幸運，實在是太幸運了。",
		MUSHTREE_TALL  ="How did it get so big?",
		MUSHTREE_MEDIUM="It's upsettingly large.",
		MUSHTREE_SMALL ="Bigger than a normal mushroom.",
		MUSHTREE_TALL=
		{
            GENERIC = "它是怎麼長到這麼大的？",
            BLOOM = "聽起來很有趣！",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "大得讓人心煩。",
            BLOOM = "哈哈哈！唔，它聞起來氣味好糟糕！",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "比普通蘑菇大。",
            BLOOM = "它現在圓滾滾、軟綿綿的！",
        },
        MUSHTREE_TALL_WEBBED = "這一棵看起來很友好！",
        SPORE_TALL = "捉住它！捉住它！",
        SPORE_MEDIUM = "捉住它！捉住它！",
        SPORE_SMALL = "捉住它！捉住它！",
        SPORE_TALL_INV = "盯著它我們會變成石頭的！",
        SPORE_MEDIUM_INV = "我們如果舔它，會變成木頭的！",
        SPORE_SMALL_INV = "我們如果吃掉它，會化成水的！",

		RABBITHOUSE=
		{
			GENERIC = "就像爺爺說過的：「你住在你吃的東西裡。」",
			BURNT = "這個胡蘿蔔太大了點，而且燒過頭了。",
		},
		SLURTLE="待我們去屠了那隻尖殼蝸牛。",
		SLURTLE_SHELLPIECES="我們太過用力了。",
		SLURTLEHAT="很堅實的頭盔。",
		SLURTLEHOLE="黏糊糊的，還有很多石頭。",
		SLURTLESLIME="黏液時間！",
		SNURTLE="待我們去滅了那隻圓殼蝸牛。",
		SPIDER_HIDER="朋友！",
		SPIDER_SPITTER="給我們吐點蜘蛛絲出來。",
		SPIDERHOLE="我們可以在那裡生存下來。",
		SPIDERHOLE_ROCK = "我們可以在那裡生存下來。",
		STALAGMITE="岩石長在地下？！長見識了。",
		STALAGMITE_FULL="岩石長在地下？！長見識了。",
		STALAGMITE_LOW="岩石長在地下？！長見識了。",
		STALAGMITE_MED="岩石長在地下？！長見識了。",
		STALAGMITE_TALL="地下居然有尖的岩石？！簡直難以置信。",
		STALAGMITE_TALL_FULL="地下居然有尖的岩石？！簡直難以置信。",
		STALAGMITE_TALL_LOW="地下居然有尖的岩石？！簡直難以置信。",
		STALAGMITE_TALL_MED="地下居然有尖的岩石？！簡直難以置信。",

		TURF_CARPETFLOOR = "Soft like our body.",
		TURF_CHECKERFLOOR = "Our feet go click-clack on this.",
		TURF_DIRT = "Some pretty average earth.",
		TURF_FOREST = "Some pretty average earth.",
		TURF_GRASS = "Some pretty average earth.",
		TURF_MARSH = "Some pretty average earth.",
		TURF_ROAD = "Some pretty average earth.",
		TURF_ROCKY = "Some pretty average earth.",
		TURF_SAVANNA = "Some pretty average earth.",
		TURF_WOODFLOOR = "Some pretty average earth.",

		TURF_CAVE="很一般的地面。",
		TURF_FUNGUS="很一般的地面。",
		TURF_SINKHOLE="很一般的地面。",
		TURF_UNDERROCK="很一般的地面。",
		TURF_MUD="很一般的地面。",

		POWCAKE = "媽媽從來不讓我吃這些的。",
        CAVE_ENTRANCE = "堵住了。",
        CAVE_ENTRANCE_RUINS = "堵住了。",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "我們寧願拜訪地面上的蜘蛛朋友。",
            OPEN = "我可以聽到下面有一些蜘蛛同胞。",
        },
        CAVE_EXIT = 
        {
            GENERIC = "我們喜歡待在這下面。",
            OPEN = "終於重見光明了。",
        },

		MAXWELLPHONOGRAPH = "我們永遠聽不厭！",
		BOOMERANG = "飛去又飛來！",
		PIGGUARD = "我們不想越過那個傢伙。",
		ABIGAIL = "那絕不是捉弄人的鬼！",
		ADVENTURE_PORTAL = "當邪惡來敲門。",
		AMULET = "我想這應該是條不錯的項鏈。",
		ANIMAL_TRACK = "不論是什麼動物，它的足跡都是一個接著一個的。",
		ARMORGRASS = "感覺就像多長了一些毛似的。",
		ARMORMARBLE = "來自大理石的非一般保護！",
		ARMORWOOD = "想跟我的木甲打一架嗎？",
		ARMOR_SANITY = "雖然穿著有點不舒服，但它確實挺有效的。",
		ASH =
		{
			GENERIC = "塵歸塵，土歸土。",
			REMAINS_GLOMMERFLOWER = "我可憐的花沒能撐過去。",
			REMAINS_EYE_BONE = "眼骨在傳送中變成了灰燼。",
			REMAINS_THINGIE = "無論什麼東西，最終都會回歸大地。",
		},
		AXE = "我砍啊砍。",
		BABYBEEFALO = "忙起來，小犛牛。",
		BACKPACK = "它就像我們的第二個肚子，裡面可以裝東西。",
		BACONEGGS = "我寧願吃含糖的穀物。噢好吧。",
		BANDAGE = "用來治癒小傷口的繃帶。",
		BASALT = "硬得刀槍不入。",
		BEARDHAIR = "換種活法的話，我本來可以長出鬍子的。",
		BEARGER = "快逃！",
		BEARGERVEST = "我們將是史上最多毛的蜘蛛。",
		ICEPACK = "我可以背起這個包！",
		BEARGER_FUR = "好厚啊！",
		FURTUFT = "毛茸茸的，而且並非來自蜘蛛。",	
		BEDROLL_STRAW = "雖然有股霉臭味兒，但還算舒服。",
		BEE =
		{
			GENERIC = "總是忙著授粉。",
			HELD = "現在是我們的了！",
		},
		BEEBOX =
		{
			FULLHONEY = "蜂蜜滿得要流出來了。",
			READY = "蜂蜜滿得要流出來了。",
			GENERIC = "一個裡面有蜜蜂的箱子。",
			NOHONEY = "裡面沒有蜂蜜。",
			SOMEHONEY = "蜜蜂們，加油產蜜啊！",
			BURNT = "我的蜂蜜就這樣燒沒了。",
		},
		BEEFALO =
		{
			FOLLOWER = "他看起來想跟著我們。",
			GENERIC = "巨大的犛牛！",
			NAKED = "看我幫你剃得乾乾淨淨的！",
			SLEEPING = "沉睡吧，犛牛。",
		},
		BEEFALOHAT = "我們可以天衣無縫地混入到它們之中。",
		BEEFALOWOOL = "厚厚的毛。",
		BEEHAT = "臉部防護裝備。",
		BEEHIVE = "蜜蜂的巢。",
		BEEMINE = "你是我的蜜蜂地雷嗎？",
		BEEMINE_MAXWELL = "只是我不能叮你。",
		BERRIES = "裝滿果汁的小圓球。",
		BERRIES_COOKED = "滿滿的熱漿果汁。",
		BERRYBUSH =
		{
			BARREN = "植物養分耗盡了。",
			WITHERED = "熱得快不行了嗎？",
			GENERIC = "已經成熟了，可以摘了。",
			PICKED = "一會兒再見，漿果！",
		},
		BIGFOOT = "啊啊啊！",
		BIRDCAGE =
		{
			GENERIC = "這是關鳥的牢籠。",
			OCCUPIED = "囚鳥。",
			SLEEPING = "你必須睡覺才能在牢籠裡生存下來。",
			HUNGRY = "他看起來餓了。",
			STARVING = "我們需要給他餵食。",
			DEAD = "我們不是很稱職的看守人。",
			SKELETON = "噁心。",
		},
		BIRDTRAP = "自投羅網吧，小鳥們！",
		BIRD_EGG = "一顆殼很硬的蛋。",
		PANDORASCHEST = "Stylish storage.",
		SCORCHED_SKELETON = "這樣可能很好。",
		CAVE_BANANA_BURNT = "香蕉受難記。",
		BIRD_EGG_COOKED = "煎蛋，就像我母親過去的手藝。",
		BISHOP = "你沒按爺爺教我的西洋棋規則來下棋。",
		BLOWDART_FIRE = "比吹熱氣更進一步。",
		BLOWDART_SLEEP = "透過空氣傳播的安眠藥。",
		BLOWDART_PIPE = "就和吹泡泡一樣一樣的。",
		BLUEAMULET = "應該還不錯。",
		BLUEGEM = "閃閃發光的冰寶石。",
		BLUEPRINT = "媽媽總是說：「按照指示來」。",
		BELL_BLUEPRINT = "媽媽總是說：「按照指示來」。",
		BLUE_CAP = "光是想想要吃這個就會瘋的...",
		BLUE_CAP_COOKED = "很好，感覺挺健康的。",
		BLUE_MUSHROOM =
		{
			GENERIC = "嗚嗚，蘑菇。",
			INGROUND = "在捉迷藏，是嗎？",
			PICKED = "也許它會再長出來。",
		},
		BOARDS = "木頭，不過形狀是平的。",
		BOAT = "腿是不少，但是我們不划船。",
		BONESHARD = "碎骨頭。",
		BONESTEW = "聞起來像星期天的晚餐。",
		BUGNET = "就像可攜帶的網！",
		BUSHHAT = "躲在灌木叢中的蜘蛛。",
		BUTTER = "牛油是個好東西。",
		BUTTERFLY =
		{
			GENERIC = "看它飛得多歡樂。",
			HELD = "高興不起來了吧，嗯？",
		},
		BUTTERFLYMUFFIN = "你認識會做鬆餅蛋糕的蜘蛛嗎？",
		BUTTERFLYWINGS = "用蝴蝶骨頭來剔牙。",
		BUZZARD = "你在這裡找不到任何腐肉。我們像這樣相依為命。",
		CACTUS = 
		{
			GENERIC = "從它裡面出來的東西比我們都多。",
			PICKED = "上面沒有肉了。",
		},
		CACTUS_MEAT_COOKED = "這下嚐到苦頭了吧，小刺球！",
		CACTUS_MEAT = "還不夠，哈？",
		CACTUS_FLOWER = "這朵花還不錯。",
		COLDFIRE =
		{
			EMBERS = "我們應該在熄火前加點東西進去。",
			GENERIC = "這樣就可以趕走炎熱，還有黑暗。",
			HIGH = "火燒的真旺！",
			LOW = "火勢越來越微弱了。",
			NORMAL = "舒爽又涼快。",
			OUT = "好吧，火熄了。",
		},
		CAMPFIRE =
		{
			EMBERS = "我們應該在熄火前加點東西進去。",
			GENERIC = "這樣就可以趕走寒冷，還有黑暗。",
			HIGH = "火燒的真旺！",
			LOW = "火勢越來越微弱了。",
			NORMAL = "舒適而暖和。",
			OUT = "好吧，火熄了。",
		},
		CANE = "再多一條腿也不會拖慢我們的速度。",
		CATCOON = "比爺爺的貓多了點野性。",
		CATCOONDEN = 
		{
			GENERIC = "樹幹小屋。",
			EMPTY = "它真的只有九條命！",
		},
		CATCOONHAT = "貓的帽子。",
		COONTAIL = "我總是喜歡去扯貓的尾巴。",
		CARROT = "我有點懷念被迫吃下這些東西的日子。",
		CARROT_COOKED = "對我們倆來說都更容易些。",
		CARROT_PLANTED = "我要把你的頭埋在土裡，胡蘿蔔。",
		CARROT_SEEDS = "我們可以用這些種子種點東西出來。",
		CAVE_FERN = "渦旋形植物。",
		CHARCOAL = "又黑又硬，就像我身體的另一半。",
        CHESSJUNK1 = "亂糟糟的一堆西洋棋。",
        CHESSJUNK2 = "亂糟糟的一堆西洋棋。",
        CHESSJUNK3 = "亂糟糟的一堆西洋棋。",
		CHESTER = "哈哈。你讓我們的所有東西都濕乎乎的。",
		CHESTER_EYEBONE =
		{
			GENERIC = "在玩躲貓貓嗎？",
			WAITING = "發現一隻相當疲憊的眼睛。",
		},
		COOKEDMANDRAKE = "被弄熟了，所以死了。",
		COOKEDMEAT = "如果不吃肉，就沒有布丁可以吃。",
		COOKEDMONSTERMEAT = "我會吃掉它，但是我一點都不開心。",
		COOKEDSMALLMEAT = "肉塊。",
		COOKPOT =
		{
			COOKING_LONG = "還要好一會兒才能做好。",
			COOKING_SHORT = "馬上就好了！",
			DONE = "晚餐準備好了。",
			EMPTY = "放一些食材進去，就會得到經過烹飪的食物。",
			BURNT = "一定是有人忘記了關火。",
		},
		CORN = "原汁原味的玉米。",
		CORN_COOKED = "爆開了的玉米。",
		CORN_SEEDS = "我們可以用這些種子種點東西出來。",
		CROW =
		{
			GENERIC = "噢，你飛來飛去，看起來日子過得不錯。",
			HELD = "我們都想要一點自由。",
		},
		CUTGRASS = "我們應該也能將它編成其他東西。",
		CUTREEDS = "蘆葦、蜘蛛網，有什麼區別。",
		CUTSTONE = "方形的石頭。",
		DEADLYFEAST = "死亡的氣息。",
		DEERCLOPS = "他也許能消化掉我！",
		DEERCLOPS_EYEBALL = "太噁心了，但確實又是好東西。",
		EYEBRELLAHAT =	"雖然有點令人不安，但它會保護我們不被雨淋濕。",
		DEPLETED_GRASS =
		{
			GENERIC = "它曾經是生長旺盛的草。",
		},
		DEVTOOL = "問我問題！",
		DEVTOOL_NODEV = "我揮不動它。",
		DIRTPILE = "一堆泥土。泥土下面肯定藏著什麼東西。",
		DIVININGROD =
		{
			COLD = "附近什麼也沒有。",
			GENERIC = "給我指引吧。",
			HOT = "已經很接近了！",
			WARM = "看來方向沒錯。",
			WARMER = "一定有東西就在附近。",
		},
		DIVININGRODBASE =
		{
			GENERIC = "這是一個神秘之物。",
			READY = "看起來那裡有一個用來插超大鑰匙的孔。",
			UNLOCKED = "它準備好了。",
		},
		DIVININGRODSTART = "魔力探測杖！",
		DRAGONFLY = "噢，你剛才難道不是在拖延時間嗎？",
		ARMORDRAGONFLY = "又一件生物護甲。",
		DRAGON_SCALES = "它們在磅秤上沒多重。",
		DRAGONFLYCHEST = "它看起來像我以前的玩具箱！",
		LAVASPIT = 
		{
			HOT = "熱到快融化了！",
			COOL = "目前看來是安全的。",
		},
		LAVA_POND = "哎喲！好燙！",
		LAVAE = "超級燙！",
		LAVAE_PET = 
		{
			STARVING = "它看上去餓壞了！",
			HUNGRY = "飢餓的岩漿蟲，真可憐。",
			CONTENT = "快樂的岩漿蟲！",
			GENERIC = "它是我的朋友。",
		},
		LAVAE_EGG = 
		{
			GENERIC = "也許我能讓它孵出來？",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "可憐的蛋。它看上去很冷。",
			COMFY = "那個蛋看上去很高興。",
		},
		LAVAE_TOOTH = "好奇怪的牙齒。",

		DRAGONFRUIT = "我有點懷疑它能不能吃。",
		DRAGONFRUIT_COOKED = "現在看起來美味多了。",
		DRAGONFRUIT_SEEDS = "我們可以用這些種子種點東西出來。",
		DRAGONPIE = "這是我們做的！",
		DRUMSTICK = "我只想擂鼓歡呼。",
		DRUMSTICK_COOKED = "愛死手抓食物了。",
		DUG_BERRYBUSH = "我要把你埋到土裡去！",
		DUG_GRASS = "我要把你埋到土裡去！",
		DUG_MARSH_BUSH = "我要把你埋到土裡去！",
		DUG_SAPLING = "我要把你埋到土裡去！",
		DURIAN = "好刺鼻。",
		DURIAN_COOKED = "算了吧，我不喜歡它。",
		DURIAN_SEEDS = "我們可以用這些種子種點東西出來。",
		EARMUFFSHAT = "綁幾隻兔子戴在頭上，好主意。",
		EGGPLANT = "呸，茄子。",
		EGGPLANT_COOKED = "媽媽知道我喜歡吃烤熟的茄子。",
		EGGPLANT_SEEDS = "我們可以用這些種子種點東西出來。",
		DECIDUOUSTREE = 
		{
			BURNING = "真是浪費木柴。",
			BURNT = "只有我們能防止森林火災。",
			CHOPPED = "你是我的了，大樹！",
			POISON = "什麼事情讓你這麼火大？",
			GENERIC = "天啊，你的葉子長得真茂盛。",
		},
		ACORN = 
		{
		    GENERIC = "是樹或是食物，總之它裡面有生命。",
		    PLANTED = "願你長久、自由地生活下去。",
		},
		ACORN_COOKED = "營火上烤熟的樺木果。",
		BIRCHNUTDRAKE = "原來裡面是這個東西！",
		EVERGREEN =
		{
			BURNING = "真是浪費木柴。",
			BURNT = "只有我們能防止森林火災。",
			CHOPPED = "你是我的了，大樹！",
			GENERIC = "圍牆另一邊的松樹總是看起來更綠一些。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "真是浪費木柴。",
			BURNT = "只有我們能防止森林火災。",
			CHOPPED = "你是我的了，大樹！",
			GENERIC = "一個瀕臨滅絕的品種。",
		},
		EYEPLANT = "時時醒著。",
		FARMPLOT =
		{
			GENERIC = "我要嘗試一下經營農田。",
			GROWING = "快快長大吧，我的農作物們！",
			NEEDSFERTILIZER = "土壤肥力已經枯竭了。",
			BURNT = "被燒燬的農田再也無法種東西了。",
		},
		FEATHERHAT = "羽毛足夠蓋住我們的蜘蛛頭。",
		FEATHER_CROW = "黑色羽毛。",
		FEATHER_ROBIN = "紅色的羽毛。",
		FEATHER_ROBIN_WINTER = "冬鳥的羽毛。",
		FEM_PUPPET = "她被關起來了！",
		FIREFLIES =
		{
			GENERIC = "真是不容易抓住的小飛蟲。",
			HELD = "繼續來一場冒險吧，我們已經抓住一些螢火蟲了！",
		},
		FIREHOUND = "他腳下有火焰，而且身體裡面都是火焰。",
		FIREPIT =
		{
			EMBERS = "我們應該在熄火前加點東西進去。",
			GENERIC = "這樣就可以趕走寒冷，還有黑暗。",
			HIGH = "火燒的真旺！",
			LOW = "火勢越來越微弱了。",
			NORMAL = "舒適而暖和。",
			OUT = "好吧，火熄了。但只是暫時的！",
		},
		COLDFIREPIT =
		{
			EMBERS = "我們應該在熄火前加點東西進去。",
			GENERIC = "這樣就可以趕走炎熱，還有黑暗。",
			HIGH = "火燒的真旺！",
			LOW = "火勢越來越微弱了。",
			NORMAL = "舒爽又涼快。",
			OUT = "好吧，火熄了。但只是暫時的！",
		},
		FIRESTAFF = "我們沒有生火。",
		FIRESUPPRESSOR = 
		{	
			ON = "這個在雪球大戰中派得上用場。",
			OFF = "關掉了。",
			LOWFUEL = "快沒燃料了。",
		},

		FISH = "它可以烤著吃。",
		FISHINGROD = "好懷念跟爺爺一起去釣魚的日子。",
		FISHSTICKS = "至少我們知道怎麼做魚條。",
		FISHTACOS = "週二是魚肉玉米捲日！",
		FISH_MED = "所有角鯊去天堂，對不對？",
		FISH_MED_COOKED = "片片分明、鮮嫩多汁。真是太美味了。",
		FISH_COOKED = "片片分明、鮮嫩多汁。真是太美味了。",
		FLINT = "我感覺它的邊緣好尖銳，劃到我的皮膚了。",
		FLOWER = "我們都認為這些花不錯。",
		FLOWER_WITHERED = "呃，太可悲了！",
		FLOWERHAT = "五顏六色的花冠。",
		FLOWER_EVIL = "這種花肯定不是什麼好東西！",
		FOLIAGE = "又軟又茂盛。",
		FOOTBALLHAT = "我們也可以很擅長橄欖球，至少比我以前擅長多了！",
		FROG =
		{
			DEAD = "這下跳過頭了吧。",
			GENERIC = "啊！好黏的舌頭！",
			SLEEPING = "真是粗心大意的兩棲動物。",
		},
		FROGGLEBUNWICH = "三明治給我，青蛙腿給他。",
		FROGLEGS = "青蛙身上的一小部分。",
		FROGLEGS_COOKED = "我得承認，我對這些東西有一種後天養成的嗜好。",
		FRUITMEDLEY = "一堆水果。",
		GEARS = "我希望我是一個機器人。",
		GHOST = "這個幽靈一點也不好玩！",
		GOLDENAXE = "當你有一把黃金斧頭，生活就容易了。",
		GOLDENPICKAXE = "所有鶴嘴鋤之中最好的。",
		GOLDENPITCHFORK = "有了這個，我們就可以做一些鏟地面的花招了。",
		GOLDENSHOVEL = "我們要挖數不清的洞。",
		GOLDNUGGET = "我們喜歡金光閃閃的東西。",
		GRASS =
		{
			BARREN = "需要天氣變好才能長出來。",
			WITHERED = "它被熱浪打敗了。",
			BURNING = "燃燒，盡情地燃燒吧！",
			GENERIC = "草是世上僅次於蜘蛛絲的好東西。",
			PICKED = "被採了，只剩下草梗。",
		},
		GREEN_CAP = "一股泥土味。",
		GREEN_CAP_COOKED = "蘑菇汁完全烤出來了。",
		GREEN_MUSHROOM =
		{
			GENERIC = "可以採摘了。",
			INGROUND = "還不能摘！",
			PICKED = "沒有了。",
		},
		GUNPOWDER = "我們越來越擅長製作東西了。",
		HAMBAT = "一種利用食物的有趣方式。",
		HAMMER = "混亂與毀滅！",
		HEALINGSALVE = "現在好多了。",
		HEATROCK =
		{
			FROZEN = "摸上去冷冰冰的。",
			COLD = "變冷了。",
			GENERIC = "這是一塊石頭。",
			WARM = "變暖了！",
			HOT = "熱得發燙了！",
		},
		HOMESIGN = 
		{
			GENERIC = "要是有支筆，我們就可以在上面寫點什麼了！",
			BURNT = "上面的字被燒掉了。",
		},
		HONEY = "又黏又甜。",
		HONEYCOMB = "蜂蜜產出地！",
		HORN = "如果這個發出求偶叫聲，那我們就有麻煩了。",
		HOUND = "那是一隻發怒的狗狗！",
		HOUNDBONE = "剩下的不多了。",
		HOUNDMOUND = "這地方太嚇人了。",
		ICEBOX = "不要腐爛了，我的食物們！",
		ICEHAT = "這應該能讓我們保持涼快。",
		ICEHOUND = "他的眼神好冰冷。",
		INSANITYROCK =
		{
			ACTIVE = "滾開，蠢石頭！",
			INACTIVE = "我很好奇那是幹什麼用的。",
		},
		HONEYHAM = "喔，真美味！",
		HONEYNUGGETS = "我們希望它們的形狀像恐龍。",
		JAMMYPRESERVES = "嘔...弄得手指黏黏的。",
		KABOBS = "用棍子串起來的食物！",
		KILLERBEE =
		{
			GENERIC = "不好，快跑！",
			HELD = "希望它不會逃出去。",
		},
		KNIGHT = "哇哦！好複雜的發條。",
		KOALEFANT_SUMMER = "也許它迷路了。",
		KOALEFANT_WINTER = "終於找到它了！",
		KRAMPUS = "把我們的東西還回來！",
		KRAMPUS_SACK = "我們可以放更多東西進去，但我們怕觸碰到他以前留在裡面的東西。",
		LEIF = "那東西是從哪兒冒出來的？！",
		LEIF_SPARSE = "那東西是從哪兒冒出來的？！",
		LIGHTNING_ROD =
		{
			CHARGED = "它通體都在發光！",
			GENERIC = "這也許能確保我們安全。",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "我父親養過羊。",
			CHARGED = "它全身都在發光。",
		},
		LIGHTNINGGOATHORN = "這沒準兒能做成一把好武器。",
		GOATMILK = "每頓晚飯喝一杯羊奶。",
		LITTLE_WALRUS = "他的眼神裡透著憤怒。",
		LIVINGLOG = "這塊木頭長著一張臉。",
		LOCKEDWES = "喂？你能聽到我說話嗎？",
		LOG =
		{
			BURNING = "它不能再用來製作和合成東西了！",
			GENERIC = "一段原木。",
		},
		LUREPLANT = "真是一株顏色美麗的植物。",
		LUREPLANTBULB = "真希望我們能夠學會如何生產肉。",
		MALE_PUPPET = "他看起來不怎麼開心。",
		MANDRAKE =
		{
			DEAD = "表皮全部燒焦了。",
			GENERIC = "這種植物的外形真有趣。",
			PICKED = "你是一個壞朋友！",
		},
		MANDRAKESOUP = "我們也會在浴缸裡睡著！",
		MANDRAKE_COOKED = "嚎叫終於停止了。",
		MARBLE = "也許我們應該開始雕刻了。",
		MARBLEPILLAR = "在這個世界上，沒有什麼東西是永恆的。",
		MARBLETREE = "希望不會砸到我們。",
		MARSH_BUSH =
		{
			BURNING = "很快它就會化為灰燼！",
			GENERIC = "希望我們別掉在上面。",
			PICKED = "刺到手了。",
		},
		MARSH_PLANT = "那是一株很口渴的植物。",
		MARSH_TREE =
		{
			BURNING = "現在尤其危險！",
			BURNT = "它生長的日子結束了。",
			CHOPPED = "斧頭可以解決掉所有與樹有關的問題！",
			GENERIC = "嚴酷環境下生長的渾身是刺的樹。",
		},
		MAXWELL = "那個混蛋欺騙了我們。",
		MAXWELLLIGHT = "呃，這些以前本來是很便利的。",
		MAXWELLLOCK = "好像少了點什麼。",
		MAXWELLTHRONE = "那個王座讓我們渾身起雞皮疙瘩。",
		MEAT = "火會讓它變得更美味。",
		MEATBALLS = "我曾經和爺爺一起做過這道菜！",
		MEATRACK =
		{
			DONE = "可以開動了！",
			DRYING = "還沒曬乾嗎？我好餓。",
			DRYINGINRAIN = "下雨天很難把肉曬乾。",
			GENERIC = "我們應該曬一些肉乾！",
			BURNT = "一切都化為了灰燼。",
		},

		MEAT_DRIED = "效果比我們預期的要好。",
		MERM = "我本以為它們更經常洗澡！",
		MERMHEAD = 
		{
			GENERIC = "浪費食物。",
			BURNT = "我很好奇那到底是誰。",
		},
		MERMHOUSE = 
		{
			GENERIC = "聞起來有魚腥味。",
			BURNT = "看起來比原先更糟了！",
		},
		MINERHAT = "戴在頭上的便利照明工具。",
		MONKEY = "他只是想學習！",

		MONKEYBARREL = "你聽見什麼聲音了嗎？",
		MONSTERLASAGNA = "唔！",
		FLOWERSALAD = "一天五份。",
        ICECREAM = "我們渴望冰淇淋。",
        WATERMELONICLE = "只屬於炎炎夏日的東西。",
        TRAILMIX = "脆脆的，營養又健康。",
        HOTCHILI = "簡直是辣椒炸彈！",
        GUACAMOLE = "好傢伙，太美味了。",
		MONSTERMEAT = "一股腐臭味。",
		MONSTERMEAT_DRIED = "太有嚼勁了。",
		MOOSE = "她好像並不樂意看到我們。",
		MOOSEEGG = "那可以做成一頓豐盛的早餐！",
		MOSSLING = "饞嘴小東西。",
		FEATHERFAN = "這玩意真大！",
		TROPICALFAN = "這玩意真大！",
		MINIFAN = "我們一跑它就扇涼風，太爽了。",
		GOOSE_FEATHER = "癢的難受。",
		STAFF_TORNADO = "我吹，我吹，我吹吹吹。",
		MOSQUITO =
		{
			GENERIC = "走開啦！",
			HELD = "我們網住了你。",
		},
		MOSQUITOSACK = "也許我們可以把蚊子吸的血再輸回來？",
		MOUND =
		{
			DUG = "對不起了。",
			GENERIC = "裡面肯定有好東西。",
		},
		NIGHTLIGHT = "它讓我們渾身起雞皮疙瘩。",
		NIGHTMAREFUEL = "又冰涼又不容易抓住。",
		NIGHTSWORD = "你也看到這個了，是吧？",
		NITRE = "這個東西可以用來做什麼？",
		ONEMANBAND = "我們需要多加練習。",
		PANFLUTE = "一支製作精良的樂器。",
		PAPYRUS = "我們可以用它來做家庭作業。",
		PHLEGM = "這是乾鼻屎！",
		PENGUIN = "一年中的其他時候它們住在哪兒呢？",
		PERD = "回來！我只想吃了你！",
		PEROGIES = "它看起來不像是餡餅...",
		PETALS = "顏色真鮮艷。",
		PETALS_EVIL = "它們會讓我們頭疼。",
		PICKAXE = "石頭將是我們的！",
		PIGGYBACK = "裡面可以裝這麼多東西！",
		PIGHEAD = 
		{	
			GENERIC = "我們只是想和你做朋友。",
			BURNT = "噁心。",
		},
		PIGHOUSE =
		{
			GENERIC = "專門為矮小肥豬建造的高高豬皮屋。",
			FULL = "我可以透過窗戶看到一頭豬！",
			LIGHTSOUT = "他們為什麼要恨我？",
			BURNT = "現在沒那麼舒適了吧，肥豬！",
		},
		PIGKING = "豬人之王！",
		PIGMAN =
		{
			DEAD = "他再也沒法欺負我們了。",
			GENERIC = "唉，你真是無趣。",
			GUARD = "他們看起來很生氣。",
			WEREPIG = "他現在全身都是毛！",
			FOLLOWER = "升起帆來，朋友！",
		},
		PIGSKIN = "這就是你的下場！",
		PIGTORCH = "要是我們能靠得再近點就好了。",
		PINECONE = 
		{
		    GENERIC = "它洋溢著生命氣息。",
		    PLANTED = "盡情生長吧！",
		},
		PITCHFORK = "玩泥巴的好工具。",
		PLANTMEAT = "它全身黏糊糊的。",
		PLANTMEAT_COOKED = "聞起來有些惡臭。",
		PLANT_NORMAL =
		{
			GENERIC = "哪些會開花呢？",
			GROWING = "還沒成熟嗎？",
			READY = "我們是模範農民。",
			WITHERED = "全都乾死了。",
		},
		POMEGRANATE = "我沒有想到這個會長出來。",
		POMEGRANATE_COOKED = "很好！",
		POMEGRANATE_SEEDS = "我們可以用這些種子種點東西出來。",
		POND = "池塘裡的水和我們身上的皮毛可不怎麼和諧。",
		POOP = "糞便。",
		FERTILIZER = "我曾經看到媽媽在她的花園裡用這個東西。",
		PUMPKIN = "好大一個南瓜！",
		PUMPKINCOOKIE = "好吃！",
		PUMPKIN_COOKED = "現在它全身上下都熱呼呼的。",
		PUMPKIN_LANTERN = "就像我們以前在家裡做的一樣！",
		PUMPKIN_SEEDS = "我們可以用這些種子種點東西出來。",
		PURPLEAMULET = "你聽見什麼聲音了嗎？",
		PURPLEGEM = "我可以看到知識在裡面徜徉。",
		RABBIT =
		{
			GENERIC = "我們只是想玩一下！",
			HELD = "現在他是我們的了。",
		},
		RABBITHOLE = 
		{
			GENERIC = "出來吧！我們只是想和你做朋友。",
			SPRING = "希望它們待在裡面沒事。",
		},
		RAINOMETER = 
		{	
			GENERIC = "它一定是用魔法驅動的。",
			BURNT = "我覺得它一點都不準確。",
		},
		RAINCOAT = "也許我們看起來像傻瓜一樣，但它會保護我們不被雨淋濕。",
		RAINHAT = "它將讓我們的皮毛不被水打濕。",
		RATATOUILLE = "我們必須吃這些素食嗎？",
		RAZOR = "我曾經看到過我父親用這個東西。",
		REDGEM = "即使在最冷的夜晚，它也令人感覺很溫暖。",
		RED_CAP = "聞起來怪怪的。",
		RED_CAP_COOKED = "現在好聞些了。",
		RED_MUSHROOM =
		{
			GENERIC = "已經成熟，可以摘了！",
			INGROUND = "它在睡覺，還不能摘。",
			PICKED = "我覺得應該還有一些孢子。",
		},
		REEDS =
		{
			BURNING = "那些東西燒得很快！",
			GENERIC = "也許我們可以用掉其中一些。",
			PICKED = "只剩下莖了。",
		},
        RELIC = 
        {
            GENERIC = "這些東西有一段時間沒用過了。",
            BROKEN = "已經被砸得稀巴爛，無法修了。",
        },
        RUINS_RUBBLE = "它好像損毀了。",
        RUBBLE = "來自古老城市的石堆。",
		RESEARCHLAB = 
		{	
			GENERIC = "就好像這裡有一個科學實驗室！",
			BURNT = "我覺得它已經壞了。",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "父親以前經常像這樣做東西。",
			BURNT = "我們所有的努力...這下全沒了。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "在它周圍的時候我們應該小心些。",
			BURNT = "火才不管你是不是魔法。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "我剛剛聽到的是吱吱聲嗎？",
			BURNT = "像是煮東西的味道。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "那是誰啊？",
			BURNT = "燒燬後的雕像對我們沒什麼用。",
		},
		RESURRECTIONSTONE = "也許是某種宗教紀念碑？",
		ROBIN =
		{
			GENERIC = "紅色是我最喜愛的顏色！",
			HELD = "待在我們的口袋裡你會很舒服。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "好漂亮的白色羽毛啊。",
			HELD = "我們就叫它「弗朗西斯」吧。",
		},
		ROBOT_PUPPET = "我覺得它一點都不開心。",
		ROCK = "在使用它之前，我們必須先開採它。",
		ROCK_CHARCOAL = "易碎的大岩石。",
		MOOSE_NESTING_GROUND = "給它的寶寶睡覺用的。",
		ROCK_LIGHT =
		{
			GENERIC = "這塊熔岩乾涸了。",
			LOW = "沒有那麼舒適了。",
			NORMAL = "好舒適！",
			OUT = "它看起來像要碎掉一樣。",
		},
		ROCK_ICE = 
		{
			GENERIC = "冰是一種很有用的東西。",
			MELTED = "已經融化成水坑了！",
		},
		ROCK_ICE_MELTED = "已經融化成水坑了！",
		ICE = "好冷。",
		ROCKS = "看起來這些石頭沒一個能用來打水漂。",
        ROOK = "這些東西是誰做的！？",
		ROPE = "我們可以用它來捆東西。",
		ROTTENEGG = "嘔！",
		SANITYROCK =
		{
			ACTIVE = "它擋住我們的路了。",
			INACTIVE = "感覺這根石柱的什麼東西消失了。",
		},
		SAPLING =
		{
			BURNING = "真明亮！",
			WITHERED = "我認為高溫傷害了它。",
			GENERIC = "它們確實長得很慢。",
			PICKED = "我們會好好利用你的樹枝！",
		},
		SEEDS = "一個小生命就這樣被困在裡面。真是可憐。",
		SEEDS_COOKED = "它們生長的日子結束了。",
		SEWING_KIT = "以前我們所有的針線活都是媽媽做的。",
		SHOVEL = "也許我們可以挖一條路出去？",
		SILK = "好光滑啊！",
		SKELETON = "喂？你還好嗎？",
		SKELETON_PLAYER = "呃，蜘蛛肉身哪兒去了？",
		SKULLCHEST = "天曉得那裡面藏著什麼東西！",
		SMALLBIRD =
		{
			GENERIC = "它能成為我們的朋友嗎？",
			HUNGRY = "我聽到它的肚子餓得咕咕叫了。",
			STARVING = "可憐的小傢伙。它看起來好餓！",
		},
		SMALLMEAT = "再多幾塊我們就可以開飯了！",
		SMALLMEAT_DRIED = "做成肉乾可以讓肉保存更長時間。",
		SPEAR = "我們應該用尖的那端去刺敵人。",
		SPIDER =
		{
			DEAD = "又失去一個朋友。",
			GENERIC = "還是蜘蛛瞭解我們。",
			SLEEPING = "啊！我認為它正在做夢。",
		},
		SPIDERDEN = "那裡面看起來好舒服。",
		SPIDEREGGSACK = "可以產生蜘蛛朋友的可攜卵囊！",
		SPIDERGLAND = "這東西也許可以減輕我們受到的傷害。",
		SPIDERHAT = "我都幹了什麼？",
		SPIDERQUEEN = "會生出小蜘蛛的長腿母蜘蛛？",
		SPOILED_FOOD = "太令人噁心了！",
		STATUEHARP = "有人把頭拿走了。",
		STATUEMAXWELL = "這就是那個說可以幫助我們的人。",
		STINGER = "當心點，不要戳到眼睛！",
		STRAWHAT = "這也許會擋住陽光。",
		STUFFEDEGGPLANT = "我們要用茄子塞滿我們的肚子！",
		SWEATERVEST = "這件背心穿上很好笑，而且弄得我發癢。",
		REFLECTIVEVEST = "安全第一！",
		HAWAIIANSHIRT = "絕對是爺爺的風格。",
		TAFFY = "糖果！",
		TALLBIRD = "快看它們的腿！",
		TALLBIRDEGG = "我剛才聽到的是唧唧聲嗎？",
		TALLBIRDEGG_COOKED = "聞起來真香！",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "它在發抖！",
			GENERIC = "它好像在孵化！",
			HOT = "如果不快點冷卻下來的話，它就會被烤熟了。",
			LONG = "看起來還是顆蛋。",
			SHORT = "那顆蛋剛才動了嗎？",
		},
		TALLBIRDNEST =
		{
			GENERIC = "這夠我們好幾天的伙食了！",
			PICKED = "蛋去哪兒了？",
		},
		TEENBIRD =
		{
			GENERIC = "它長得太快了！",
			HUNGRY = "它看起來餓了！",
			STARVING = "我想它應該是餓得快不行了！",
		},
		TELEBASE =
		{
			VALID = "看來可以使用了。",
			GEMS = "需要有東西來聚集能量。",
		},
		GEMSOCKET = 
		{
			VALID = "看上去一切就緒。",
			GEMS = "上面是空的。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我們可以用這個來探索新世界！",
			GENERIC = "我可以聽到另一個世界的聲音！",
			LOCKED = "還是無法用！",
			PARTIAL = "我覺得我們還沒有完成！",
		},
		TELEPORTATO_BOX = "這盒子裡的力量不可思議。",
		TELEPORTATO_CRANK = "經得起任何粗野對待的曲柄零件。",
		TELEPORTATO_POTATO = "似乎這個東西要和其他東西配合使用...",
		TELEPORTATO_RING = "我覺得不止這一個零件。",
		TELESTAFF = "它讓我的腦袋昏昏沉沉的。",
		TENT = 
		{
			GENERIC = "已經遠遠過了我們的睡覺時間！",
			BURNT = "大火摧毀了它。",
		},
		SIESTAHUT = 
		{
			GENERIC = "午休時間到了？",
			BURNT = "這東西無法用來睡午覺！",
		},
		TENTACLE = "如果有東西踩到我們，我們也會發狂的。",
		TENTACLESPIKE = "我們可以用尖銳部位擊打其他東西！",
		TENTACLESPOTS = "好多斑點！",
		TENTACLE_PILLAR = "好大！",
		TENTACLE_PILLAR_HOLE = "噢，我們跳進去吧！",
		TENTACLE_PILLAR_ARM = "啊，那只是個觸手寶寶！",
		TENTACLE_GARDEN = "好大！",
		TOPHAT = "像父親以前戴的。",
		TORCH = "這應該能確保我們安全。",
		TRANSISTOR = "我們越來越擅長合成東西了！",
		TRAP = "現在，我們可以抓些食物了！",
		TRAP_TEETH = "這可以讓我們的敵人受傷。",
		TRAP_TEETH_MAXWELL = "誰把它放在這裡的？我們可能會受傷！",
		TREASURECHEST = 
		{
			GENERIC = "我們可以把玩具裝在裡面！",
			BURNT = "現在它對我們已經沒那麼大用處了。",
		},
		TRINKET_1 = "如果它們沒有完全融化，我們可能還有得玩。",
		TRINKET_2 = "一支吹不響的笛子。",
		TRINKET_3 = "它不會自己解開的！",
		TRINKET_4 = "它在看著我們。",
		TRINKET_5 = "好耶，新玩具！",
		TRINKET_6 = "也許我們可以給這些東西找個用途。",
		TRINKET_7 = "又一個玩具！",
		TRINKET_8 = "我想念沐浴玩具。",
		TRINKET_9 = "沒一個扣對了！",
		TRINKET_10 = "簡直跟爺爺戴的假牙一模一樣！",
		TRINKET_11 = "嗶...咘！",
		TRINKET_12 = "感覺像皮革一樣。",
		TRUNKVEST_SUMMER = "太臃腫了！",
		TRUNKVEST_WINTER = "它會讓我們遠離感冒。",
		TRUNK_COOKED = "看起來料很足！",
		TRUNK_SUMMER = "我們拿到他的鼻子了！",
		TRUNK_WINTER = "他的鼻子變藍了。",
		TUMBLEWEED = "天知道那個風滾草裡裹著什麼。",
		TURF_CARPETFLOOR = "地毯！就跟我們的老房子一樣。",
		TURF_CHECKERFLOOR = "真漂亮。",
		TURF_DIRT = "我們挖出的一些地面。",
		TURF_FOREST = "我們挖出的一些地面。",
		TURF_GRASS = "我們挖出的一些地面。",
		TURF_MARSH = "我們挖出的一些地面。",
		TURF_ROAD = "我們挖出的一些地面。",
		TURF_ROCKY = "我們挖出的一些地面。",
		TURF_SAVANNA = "一些長滿草的地面。",
		TURF_DRAGONFLY = "溫暖舒適的地皮！",
		TURF_BADLANDS = "Some ground that we dug up.",
		TURF_DECIDUOUS = "Some ground that we dug up.",
		TURF_DESERTDIRT = "Some ground that we dug up.",
		TURF_FUNGUS_GREEN = "Some ground that we dug up.",
		TURF_FUNGUS_RED = "Some ground that we dug up.",
		TURF_SANDY = "Some ground that we dug up.",
		TURF_WOODFLOOR = "把這些放在地上之後，我們就有地板啦！",

		STEELWOOL = "有些刺癢，就像爸爸的鬍子！",
		SPAT = "也許它只需要一個擁抱！",
		BISHOP_CHARGE_HIT = "嗷！",
		TURKEYDINNER = "就像這一切發生之前母親經常做的那樣！",
		TWIGS = "希望能找到一個陪我們玩樹枝劍的朋友。",
		UMBRELLA = "這應該可以幫助我們少淋點雨。",
		GRASS_UMBRELLA = "有了它，我們還是可以在水坑裡玩耍！",
		PALMLEAF_UMBRELLA = "有了它，我們還是可以在水坑裡玩耍！",
		UNIMPLEMENTED = "這東西太糟糕了。",
		WAFFLES = "好吃！",
		WALL_HAY = 
		{	
			GENERIC = "這可以擋住任何東西！",
			BURNT = "但它擋不住火。",
		},
		WALL_HAY_ITEM = "綁在一起的草。",
		WALL_STONE = "我們是建造營地的大師！",
		WALL_STONE_ITEM = "這些遲早派得上用場。",
		WALL_RUINS = "看起來很堅固。",
		WALL_RUINS_ITEM = "噢！太重了。",
		WALL_WOOD = 
		{
			GENERIC = "像一座枕頭城堡，不過是木頭做的！",
			BURNT = "木頭果然是最容易燒著的東西。",
		},
		WALL_WOOD_ITEM = "如果我們就這樣拿著它們，那它們是無法保衛我們安全的。",
		WALL_MOONROCK = "這堵牆讓我們覺得很安全...它讓我們很想睡覺...",
		WALL_MOONROCK_ITEM = "我們曾以為「月亮」代表著另一種完全不同的東西！",
		WALRUS = "他應該不想和我們交朋友吧。",
		WALRUSHAT = "讓我想起了爺爺。",
		WALRUS_CAMP =
		{
			EMPTY = "我猜這裡以前有人住過。",
			GENERIC = "也許他們會邀請我們進去？",
		},
		WALRUS_TUSK = "也許我們可以用它來合成其他東西。",
		WARDROBE = 
		{
			GENERIC = "我們喜歡躲在裡面。",
            BURNING = "燃燒，盡情地燃燒吧！",
			BURNT = "我們再也不能躲在裡面了。",
		},
		WARG = "這隻狗狗看起來不太高興。",
		WASPHIVE = "它們好像發怒了！",
		WATERMELON = "看起來好好吃！",
		WATERMELON_COOKED = "沒有什麼是我們不能烹飪的！",
		BANANAPOP = "耶！冰棒，冰棒！",
		BISQUE = "我們吃它時翹起了我們的小指。",
		CEVICHE = "好噁心！",
		SEAFOODGUMBO = "我們可以一直吃這個！",
		SURFNTURF = "呃，這很健康！",
		SHARKFINSOUP = "真好喝的湯！",
		LOBSTERDINNER = "我們得閉著眼把它吃下去。太多條腿了！",
		LOBSTERBISQUE = "讓我們恨不得把舌頭都吞下去！",
		JELLYOPOP = "好吃！",
		WATERMELONHAT = "這是我們從過去到現在想出來的最好的點子。",
		WETGOOP = "至少是一次有趣的嘗試！",
		WINTERHAT = "媽媽總是說我應該戴一頂帽子。",
		WHIP = "噢，它製造了這麼多的噪音！",
		WINTEROMETER = 
		{
			GENERIC = "溫度計先生，現在多少度？",
			BURNT = "又一個朋友死去。",
		},
		WORMHOLE =
		{
			GENERIC = "我覺得那個東西是活的。",
			OPEN = "更糟糕的地方我都去過了。",
		},
		WORMHOLE_LIMITED = "呃，那個看起來好噁心！",
		ACCOMPLISHMENT_SHRINE = "它給了我一個為之奮鬥的人生目標。",        
		LIVINGTREE = "你好，樹先生！",
		ICESTAFF = "它讓我感覺好好笑。",



----------------------------capy---------------------------------------

		AERODYNAMICHAT = "我們感覺身輕如燕。",
		ANTIVENOM = "這是一種藥物？",
		ARMOR_LIFEJACKET = "注意安全總沒錯。",
		ARMOR_SNAKESKIN = "雨水會從這件蛇皮衣上滾落。",
		ARMOR_WINDBREAKER = "風阻礙不了我們！",
		ARMORLIMESTONE = "我們背疼...",
		ARMOROBSIDIAN = "我們的敵人會感覺到這股熱力！",
		ARMORSEASHELL = "我們感覺自己像一個騎士，儘管盔甲不太閃亮。",
		ARMOUREDBOAT = "它讓海上航行更加安全。",
		BABYOX = "Hey lil fella!",
		BALLPHIN = "愛嬉戲的傢伙，彈力十足。我們會遠遠觀賞的。",
		BALLPHINPOD = "它們為什麼不喜歡我們！",
		BAMBOO = "很有用的棍子狀東西。",
		BAMBOOTREE = "Such a small but helpful tree.",
		BERMUDATRIANGLE = "太讓人不安了！",
		BERRYBUSH2_SNAKE = "已經成熟了，可以摘了。",
		BERRYBUSH_SNAKE = "已經成熟了，可以摘了。",
		BIOLUMINESCENCE = "哇哦！美麗的水上光芒！",
		BLOWDART_POISON = "一件陰險的武器...",
		BOAT_LANTERN = "有了它，可以方便地看清我們所去的地方！",
		BOATCANNON = "有了這個，我們可以製造一艘戰船！",
		BOATREPAIRKIT = "出門的時候必須帶上它。",
		BOTTLELANTERN = "嘿，裡面的小夥伴，感謝你們帶來光芒！",
		BURIEDTREASURE = "寶藏，寶藏，寶藏！",
		BUSH_VINE = "What a crazy looking plant.",
		CAPTAINHAT = "看起來像一個真正的船員了！",
		CARGOBOAT = "哈，我們可以伸直所有的腿...",
		CHIMINEA = "我們的火不會被風吹熄了。",
		CIRCLINGSEAGULL = "別朝我們拉屎！",
		CLOTHSAIL = "現在我們可以利用風的力量了！",
		COCONADE = "We should throw this very much far away from ourselves.",
		COCONUT = 
		{
		    GENERIC = "食物！來自一棵樹！",
		    PLANTED = "噢。它是如此之小。",
		},
		COFFEE = "好苦。",
		COFFEEBEANS = "這些聞起來...像是大人喝的東西。",
		
		COFFEEBUSH = "These don't look tasty.",
		CORAL = "美麗的顏色。",
		CORALREEF = "一大片珊瑚！",
		CRABHOLE = "那個六條腿的傢伙住在地下。",
		CUTLASS = "這把劍和魚有些淵源。",
		DEAD_SWORDFISH = "我們應該吃掉它還是用掉它？",
		DEPLETED_BAMBOOTREE = "回來吧，竹子。",
		DEPLETED_BUSH_VINE = "籐蔓還會長回來嗎？",
		DOYDOY = "眼神空洞...",
		DOYDOYBABY = "噢，它是一隻小傻瓜。",
		DOYDOYEGG = "愚蠢的生命開始的地方。",
		
		DOYDOYFEATHER = "唔，它掉落了這個。",
		DOYDOYNEST = "那些小傻瓜就來自這裡。",
		DUBLOON = "閃亮的金幣！",
		DUG_BAMBOOTREE = "我們是園藝專家！",
		DUG_BUSH_VINE = "我們應該把它放在哪裡？",
		DUG_COFFEEBUSH = "只需要一點愛，它就可以再次生長了。",
		EARRING = "它的主人是一個海盜！",
		FABRIC = "我們可以做一條新毯子，或者不做。",
		FEATHERSAIL = "可以加快航海速度的羽毛帆。",
		FIRERAIN = "天上下著火雨！",
		FIRERAINSHADOW = "蹲下和掩護！",
		FISHINHOLE = "可以免費捕獲的魚！",
		FROG_POISON = "如果被它們舔了，我們會生病的。",
		GASHAT = "我們不會再聞到有毒的氣味了。",
		GOLDENMACHETE = "好漂亮的砍刀！",
		ICEMAKER = "Ice is useful in this heat.",
		IRONWIND = "誰需要槳！",
		TREEGUARD = "壞脾氣的樹！",
		JELLYFISH = "那一團東西是活的！",
		JELLYFISH_COOKED = "我們曾希望它的肉質更加...緊實的。",
		JELLYFISH_DEAD = "它既不是果凍也不是魚，而且它已經失去了生命。",
		JELLYJERKY = "什麼東西都要嘗試一下。",
		JELLYFISH_PLANTED = "大海充滿了這樣奇奇怪怪的生物。",
		JUNGLETREE =
	    {
			BURNING = "What a senseless waste of firewood.",
			BURNT = "That's one less place for snakes to slither from.",
			CHOPPED = "Bye-bye, big tree.",
			GENERIC = "Oh neat, a big tree.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "難以置信這個會長成那麼大一棵樹！",
            PLANTED = "生長，生長，盡情生長吧！",
        },
		LAVAPOOL = "好炎熱！",
		LIMESTONE = "崎嶇不平！",
		LIMPETROCK =
		{
			GENERIC = "This rock is covered in food things!",
			PICKED = "Come back, yumyums.",
		},
		LIMPETS = "我們必須吃這些東西嗎？",
		LIMPETS_COOKED = "味道像大海。",
		
		LOBSTER = "這個肉團穿著盔甲！",
		LOBSTERHOLE = "這就是全副武裝的龍蝦在白天藏身的地方。",
		LOGRAFT = "這個看起來速度不怎麼快。",
		MACHETE = "嘿！哈！",
		MESSAGEBOTTLE = "也許這裡面有一本漫畫書！",
		MESSAGEBOTTLEEMPTY = "我們希望裡面裝滿了汽水。",
		MOSQUITO_POISON = "這些蚊子在叮咬時會留下一個禮物。",
		
		MUSSEL = "也許有一天我也會有強壯的肌肉。",
		MUSSEL_STICK = "貽貝會爬上這根棒子並停下來。",
		OBSIDIAN = "來自火山岩的石頭！",
		OBSIDIAN_WORKBENCH = "我們在這裡鑄造跟火有關的物品。",
		OBSIDIANAXE = "我們將不可阻擋！",
		OBSIDIANCOCONADE = "天氣都會充滿爆炸的味道！",
		OBSIDIANFIREPIT =
		{
			EMBERS = "我們應該在熄火前加點東西進去。",
			GENERIC = "我們把火石做成了營火！",
			HIGH = "火燒的真旺！",
			LOW = "火勢越來越微弱了。",
			NORMAL = "最暖和的火。",
			OUT = "好吧，火熄了。但只是暫時的！",
		},
		OBSIDIANMACHETE = "它每砍一下都會生火！",
		SPEAR_OBSIDIAN = "一戳即燃！",
		OBSIDIANSPEARGUN = "就像放煙花一樣！",
		OX = "牛角很酷。",
		PACKIM = "你好，大嘴朋友！",
		PACKIM_FISHBONE = "我們想知道這是什麼？",
		PALMLEAF = "大葉子。",
		PALMTREE = 
		{
			BURNING = "真是浪費木柴。",
			BURNT = "它掉落了最後一個椰子。",
			CHOPPED = "再見了，椰樹。",
			GENERIC = "這棵樹上有禮物！",
		},
		PARROT = "你這個話多的傢伙！",
		PEACOCK = "好漂亮的羽毛！",
		PIRATEHAT = "啊啊啊，我們感覺自己屬於這片海洋！",
		PIRATIHATITATOR = "With this pirate hat we'll harness dark, cursed stuff.",
		POISONHOLE = "呀！大地在噴氣！",
		RAFT = "我們真的認為這個足夠結實嗎？",
		ROWBOAT = "那首老歌是怎麼唱的？",
		SAIL = "它可以給我們加把勁！",
		SAND = "很多條腿踩在上面的感覺很好。",
		SAND_CASTLE = "Look what we built!",
		SANDBAG = "Sand pillows!",
		SANDHILL = "希望我們有桶和鏟子。",
		SEAGULL = "我們想朝你扔東西。",
		SEAGULL_WATER = "飛來飛去吃垃圾的感覺...一定很不錯。",
		SEASACK = "好噁心，又濕軟又黏糊。",
		SEASHELL = "海洋垃圾。",
		SEATRAP = "游進來的是生物，出來的是晚餐。",
		SEAWEED = "來自海洋的沙拉。",
		
		SEAWEED_PLANTED = "也許我們應該把那個除乾淨。",
		SHARK_FIN = "要摸它嗎？",
		SHARX = "鯊...鯊...鯊魚！！！！！",
		SLOTMACHINE = "我想我還不到年齡玩這個。",
		SNAKE = "我們應該離它們遠點。",
		SNAKE_FIRE = "啊，來自火山的噴火生物！",
		SNAKE_POISON = "這些蛇有毒牙！",
		SNAKESKIN = "蛇的皮！",
		SNAKESKINHAT = "蛇皮會讓我們看上去很強硬嗎？",
		SOLOFISH = "聽說你身上有很多肉！",
		SPEAR_POISON = "戳一下就搞定了。",
		SPEARGUN = "我們開槍射擊了！",
		SPEARGUN_POISON = "我最好不要拿它指著自己。",
		STUNGRAY = "你好可愛！喂，那是什麼氣味...",
		SUPERTELESCOPE = "有了它，可以比我們所有眼睛加起來看得還清楚！",
		SWORDFISH = "魚兒，我們喜歡你那張寶劍一樣的臉！",
		TELESCOPE = "我可以看那麼遠！",
		TIGERSHARK = "出水怪物！",
		TIGERSHARKSHADOW = "好可怕...",
		TORNADO = "我們不喜歡這個...",
		TOUCAN = "你的嘴顏色真鮮艷！",
		TRAWLNET = "我想知道我們能捕撈到些什麼。",
		TRAWLNETDROPPED = "What goodies are inside!",
		TRIDENT = "握著它的感覺就像自己是天神下凡！",
		TRINKET_13 = "今天是我們的生日嗎？！",
		TRINKET_14 = "讓我想起了泰迪熊。",
		TRINKET_15 = "我想知道它在不在音調上。",
		TRINKET_16 = "汽車在哪裡？",
		TRINKET_17 = "對我們來說太大了。",
		TRINKET_18 = "這東西比我們古老得多。",
		TRINKET_19 = "什麼是腦殘？",
		TURBINE_BLADES = "好奇怪。",
		TURF_BEACH = "我們挖出的一些地皮。",
		TURF_JUNGLE = "我們挖出的一些地皮。",
		TWISTER = "大自然恨我們！",
		VENOMGLAND = "如果我們中毒了，這東西是解毒的關鍵。",
		VINE = "這東西是野生的。",
		VOLCANO = "那是...哦，天哪...",
		VOLCANO_ALTAR = "We can feed the hungry volcano! But what does it like to eat?",
		VOLCANO_ALTAR_BROKEN = "這真是奇恥大辱。",
		VOLCANO_EXIT = "我們可以逃離這裡的高溫了。",
		VOLCANOSTAFF = "火山聽從我們的差遣！",
		WALL_LIMESTONE = "這堵牆是石灰做成的嗎？",
		WALL_LIMESTONE_ITEM = "為什麼它被稱作石灰岩？它一點都不像灰。",
		WHALE_BLUE = "打起精神，大傢伙！",
		WHALE_CARCASS_BLUE = "現在它不用受折磨了。",
		WHALE_CARCASS_WHITE = "這個死去的傢伙是個龐然大物。",
		WHALE_WHITE = "它的眼睛裡燃燒著敵意！",
	
		ARMORCACTUS = "擁抱就是武器！",
		BAMBOOTREE =
		{
			BURNT = "它是燒焦的竹子。",
			CHOPPED = "它有竹子，竹子。",
			GENERIC = "可愛的小竹子。",
		},
		BIGFISHINGROD = "也許我們能釣到一些好東西。",
		BLOWDART_FLUP = "我不覺得這個會有很大殺傷力。",
		BLUBBER = "心寬體胖。",
		BLUBBERSUIT = "鯨魚脂肪裡裹著蜘蛛，蜘蛛體內住著小男孩。",
		BOAT_TORCH = "它將照亮我的路！",
		BRAINJELLYHAT = "我覺得我們的腦袋變聰明了，而且頭上黏糊糊的。",
		BUOY = "我是個喜歡燈塔的小男孩！",
		BUSH_VINE =
		{
			BURNT = "全燒光了。",
			CHOPPED = "我們全採走了。",
			GENERIC = "這是一叢不錯的籐蔓。",
		},
		COCONADE =
		{
			BURNING = "要爆炸了，小心！",
			GENERIC = "這個會很好玩！",
		},
		COCONUT_COOKED = "只需要在上面插一把小傘。",
		COCONUT_HALVED = "現在我們每個人都有一半了。",
		COFFEEBEANS_COOKED = "我覺得它們很有趣。",
		COFFEEBOT = "製作超好喝咖啡的機器！",
		COFFEEBUSH =
		{
			BARREN = "再沒有咖啡豆了。",
			GENERIC = "它上面長著很多開心的豆子。",
			PICKED = "我們全採走了。",
			WITHERED = "咖啡樹看起來很悲傷。",
		},
		CORAL_BRAIN = "美味的腦肉！",
		CORAL_BRAIN_ROCK = "我想戳它一下，但我怕我們的手會被黏住。",
		CRAB =
		{
			CRAB = "一條、兩條...六、六條腿。呃，我們曾以為你也許是我們的朋友。",
			HIDDEN = "出來，快出來，不管你在哪裡！",
		},
		CRATE = "哇，一個板條箱。",
		DEPLETED_GRASS_WATER = "全沒了。",
		DOUBLE_UMBRELLAHAT = "我們每人一層！",
		DOYDOYEGG_COOKED = "做一份歐姆蛋得犧牲好幾個物種。",
		DOYDOYEGG_CRACKED = "它在壓力下裂開了。",
		DRAGOON = "它是一個開拓者！",
		DRAGOONDEN = "也許我們該離它遠點。",
		DRAGOONEGG = "它會很快孵出來嗎？",
		DRAGOONHEART = "它燙得出奇。",
		DRAGOONSPIT = "把你的體液留給你自己！",
		DUG_ELEPHANTCACTUS = "現在我可以利用它了。",
		ELEPHANTCACTUS = "它枯萎了，但摸上去仍然刺手。",
		ELEPHANTCACTUS_ACTIVE = "它全身都是傷人的刺！",
		ELEPHANTCACTUS_STUMP = "你在那裡睡覺嗎？",
		FISH_RAW = "烤熟之後可能更好。",
		FISH_RAW_SMALL = "這是一條小魚。",
		FISH_RAW_SMALL_COOKED = "好多骨頭。",
		FLAMEGEYSER = "大地生氣了。",
		FLOTSAM = "一定有辦法可以打撈它。",
		FLUP = "它為什麼這麼有攻擊性！",
		FRESHFRUITCREPES = "天啊！我們等不及要吃這些可麗餅了！",
		GRASS_WATER = "它要去游泳。",
		HAIL_ICE = "嘶~好冷！",
		HOME = "有人嗎？我們在這裡！",
		HOUNDFIRE = "它會燒掉我們全身的蜘蛛毛！",
		ICEMAKER =
		{
			HIGH = "它運轉得非常順利！",
			LOW = "我想它需要我們的幫助。",
			NORMAL = "看起來一切正常。",
			OUT = "停產了。",
			VERYLOW = "這東西就快撐不住了。也許它可以向我們借幾條腿來多支撐一下？",
		},
		JUNGLETREE =
		{
			BURNING = "太熱了！",
			BURNT = "它不再是綠色的了。",
			CHOPPED = "我們砍掉了它！",
			GENERIC = "一棵不錯的樹。",
		},
		KNIGHTBOAT = "它很卑鄙！",
		KRAKEN = "快跑！",
		KRAKENCHEST = "我們來打開它！",
		KRAKEN_TENTACLE = "離我遠點！",
		LIMPETROCK =
		{
			GENERIC = "它上面長滿了帽貝。",
			PICKED = "全沒了。",
		},
		LIVINGJUNGLETREE = "這裡的一切都很平常。",
		LOBSTER_DEAD = "它不會再動了。",
		LOBSTER_DEAD_COOKED = "真好吃！",
		LUGGAGECHEST = "最好完成打包。",
		MAGIC_SEAL = "哇，有魔法！",
		MAGMAROCK = "一堆冷硬的石頭。",
		MAGMAROCK_FULL = "一堆冷硬的石頭。",
		MAGMAROCK_GOLD = "一堆閃耀的石頭。",
		MAGMAROCK_GOLD_FULL = "一堆閃耀的石頭。",
		MANGROVETREE = "這是個建樹屋的好地方。",
		MANGROVETREE_BURNT = "所以再沒有樹屋了。",
		MARSH_PLANT_TROPICAL = "它看起來像一棵野草。",
		MAXWELLHEAD = "想像一下他買帽子該有多麻煩！",
		MERMFISHER = "半人半動物，太奇怪了。",
		MERMHOUSE_FISHER = "我能進來嗎？",
		MONKEYBALL = "我們交了一個朋友！",
		MONSTERTARTARE = "看起來很不可思議！",
		MOSQUITOSACK_YELLOW = "蚊子的屁股。",
		MUSSELBOUILLABAISE = "超級開胃的美食。",
		MUSSEL_COOKED = "還是有點噁心。",
		MUSSEL_FARM =
		{
			GENERIC = "真討厭。",
			STICKPLANTED = "Is it done yet?",
		},
		MYSTERYMEAT = "一大坨黏糊糊的東西。",
		NEEDLESPEAR = "這個真的有可能傷到人。",
		OCTOPUSCHEST = "我們看看裡面有什麼！",
		OCTOPUSKING = "它看上去很友好。",
		OXHAT = "我們看上去怎麼樣？",
		OX_FLUTE = "它在祈求被吹奏！",
		OX_HORN = "我們可以用東西把它磨尖一點。",
		PALMLEAF_HUT = "幾乎和蜘蛛巢一樣棒。",
		PANDORASCHEST = "時髦的儲物箱。",
		PARROT_PIRATE = "就鳥而言，這一隻是很時髦的。",
		PEG_LEG = "這是我們用來戰鬥的腿。",
		PIGTENT = "小豬，小豬，讓我進來！",
		PIKE_SKULL = "我們不喜歡這樣！",
		PIRATEGHOST = "彷彿普通的海盜還不夠可怕似的！",
		PIRATEPACK = "打包戰利品的箱包。",
		PIRATIHATITATOR =
		{
			BURNT = "全燒光了！",
			GENERIC = "這肯定是某種東西。和海盜有關的神奇東西。",
		},
		PORTAL_SHIPWRECKED = "沒人打算穿過這裡。",
		PRIMEAPE = "我和這傢伙亦敵亦友。",
		PRIMEAPEBARREL = "太多猴子了。",
		RAWLING = "我們喜歡這個野生的籃球人。",
		REDBARREL = "炸藥！",
		ROCK_OBSIDIAN = "這塊岩石相當硬。",
		SAIL_STICK = "這是一根桿子！",
		SANDBAGSMALL = "用來防止水蔓延。",
		SANDBAGSMALL_ITEM = "記得用你的腿來抬...所有八條腿都用上！",
		SANDBAG = "記得用你的腿來抬...所有八條腿都用上！",
		SANDBAG_ITEM = "記得用你的腿來抬...所有八條腿都用上！",
		SAND_CASTLE =
		{
			GENERIC = "這很好玩！",
			SAND = "希望我們能住在裡面。",
		},
		SEASHELL_BEACHED = "有了這些，我們可以聽到海的聲音。沒有它們，我們同樣能聽到。",
		SEAWEED_COOKED = "非常鹹。",
		SEAWEED_DRIED = "它會黏在我們的上顎上！",
		SHADOWSKITTISH_WATER = "哎呀！",
		SHARKITTEN = "小貓，小貓，來這裡！",
		SHARKITTENSPAWNER =
		{
			GENERIC = "也許有一些小貓會出來玩耍？",
			INACTIVE = "平淡乏味的沙子。",
		},
		SHARK_GILLS = "大魚的呼吸部位。",
		SHARK_TEETHHAT = "戴上它，就像我們的額頭在微笑一樣！",
		SHIPWRECKED_ENTRANCE = "開始冒險吧！",
		SHIPWRECKED_EXIT = "再見了！",
		SNAKEDEN =
		{
			BURNT = "全燒光了。",
			CHOPPED = "我們全採走了。",
			GENERIC = "這是一叢不錯的籐蔓。",
		},
		SNAKEOIL = "它真的有效！",
		SNAKESKINSAIL = "有了這張用噁心的皮做成的船帆，我們可以開始冒險了。",
		SPEAR_LAUNCHER = "為什麼會有人發射長矛？可能會使別人受傷的。",
		SPOILED_FISH = "它現在對任何人都沒有用了。",
		SUNKBOAT = "這麼近，那麼遠。",
		SUNKEN_BOAT =
		{
			ABANDONED = "小鳥，也許到了該放棄這艘船的時候了。",
			GENERIC = "它的樣子沒什麼好看的。",
		},
		SUNKEN_BOAT_BURNT = "難以相信這東西曾經很適合航海。",
		SUNKEN_BOAT_TRINKET_1 = "它非常閃亮。",
		SUNKEN_BOAT_TRINKET_2 = "哇！！！！",
		SUNKEN_BOAT_TRINKET_3 = "我們可能點不燃這個。",
		SUNKEN_BOAT_TRINKET_4 = "這是一個玩具嗎？",
		SUNKEN_BOAT_TRINKET_5 = "如果我們陷入絕境，也許會把它給煮了的。",
		SWEETPOTATOSOUFFLE = "好美味。",
		SWEET_POTATO = "你說是「紅薯」，我說是「晚餐」！",
		SWEET_POTATO_COOKED = "橙色的食物泥。",
		SWEET_POTATO_PLANTED = "我們想吃這個！",
		SWEET_POTATO_SEEDS = "我們可以用這些種子種出更多蕃薯。",
		SWIMMINGHORROR = "啊啊！",
		TELEPORTATO_SW_BASE = "我們能吃掉這個嗎？",
		TELEPORTATO_SW_BOX = "有個東西螺絲鬆了。",
		TELEPORTATO_SW_CRANK = "奇怪的東西！",
		TELEPORTATO_SW_POTATO = "喔，它甚至都不能吃。",
		TELEPORTATO_SW_RING = "也許它是用來轉呼啦圈的？",
		THATCHPACK = "便於攜帶貨物！",
		TIDALPOOL = "它像個魚缸...但只有魚沒有缸！",
		TIDAL_PLANT = "一叢小小的灌木。",
		TIGEREYE = "你在看什麼？",
		TRAWLNETDROPPED =
		{
			GENERIC = "我們織的網簡直是錯綜複雜！",
			SOON = "它在下沉！",
			SOONISH = "它正在緩慢地下沉。",
		},
		TREASURECHEST_TRAP = "簡單又漂亮。",
		TREECLUMP = "它擋住了我們的路！",
		TRINKET_20 = "它非常閃亮。",
		TRINKET_21 = "哇！！！！",
		TRINKET_22 = "瓶子裡是什麼？",
		TRINKET_23 = "那些話語都傳到了哪裡？",
		TROPICAL_FISH = "它很漂亮！",
		TUNACAN = "我們把開罐器落在家裡了。",
		TURF_SANDY = "我們挖出的一些地面。",
		TURF_ASH = "我們挖出的一些地面。",
		TURF_BADLANDS = "我們挖出的一些地面。",
		TURF_DECIDUOUS = "我們挖出的一些地面。",
		TURF_DESERTDIRT = "我們挖出的一些地面。",
		TURF_FUNGUS_GREEN = "我們挖出的一些地面。",
		TURF_FUNGUS_RED = "我們挖出的一些地面。",
		TURF_MAGMAFIELD = "我們挖出的一些地面。",
		TURF_MEADOW = "我們挖出的一些地面。",
		TURF_SNAKESKINFLOOR = "我們挖出的一些地面。",
		TURF_SWAMP = "我們挖出的一些地面。",
		TURF_TIDALMARSH = "我們挖出的一些地面。",
		TURF_VOLCANO = "我們挖出的一些地面。",
		TWISTER_SEAL = "好想捏捏它的臉！",
		VOLCANO_ALTAR =
		{
			GENERIC = "我們現在不能使用它。",
			OPEN = "祭壇可以開始接受供品了！",
		},
		VOLCANO_ALTAR_TOWER = "好大！",
		VOLCANO_SHRUB = "我想它在和我說話。",
		WALLYINTRO_DEBRIS = "船的其餘部分在哪裡？",
		WATERMELON_SEEDS = "如果吃掉它們，它們會在我們體內生長嗎？",
		WATERYGRAVE = "咕嚕咕嚕。",
		WHALE_BUBBLES = "這些氣泡來自哪裡？",
		WHALE_TRACK = "跟著那頭鯨魚！",
		WILBUR_CROWN = "我們想戴著它。",
		WILBUR_UNLOCK = "他會是一個不錯的朋友。",
		WILDBORE = "我覺得它不友好。",
		WILDBOREHEAD = "它看起來不太高興。",
		WILDBOREHOUSE = "裡面傳出低沉的呼嚕聲。",
		WIND_CONCH = "和煦的海風待在這個海螺殼裡。好吧，可能沒有這麼和煦。",
		WOODLEGSBOAT = "準備駛向開闊的大海！",
		WOODLEGSHAT = "呀！哈哈。",
		WOODLEGSSAIL = "一塊花俏的布。",
		WOODLEGS_CAGE = "他需要我們的幫助！",
		WOODLEGS_KEY1 = "它會打開什麼？",
		WOODLEGS_KEY2 = "這把鑰匙可能比它打開的東西更值錢。",
		WOODLEGS_KEY3 = "這東西用於打開別的東西。",
		WRECK = "提醒我們要尊重大海。",
		CALIFORNIAROLL = "唔，這裡面有點不對勁的魚腥味！",
	},
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "要是它在我們的肚子裡孵出來怎麼辦？",
	},
}