return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "彼女は喜ばないと思う。",
			GENERIC = "毛じゃないものは剃れないよ。",
			NOBITS = "もうすでに刈り込まれてるんでしょ、ねえ？",
            REFUSE = "このヒゲは、そらねぇぞ",
		},
		STORE =
		{
			GENERIC = "もうすでにギュウギュウ詰めだよ。",
			NOTALLOWED = "やめといたほうがよさそうだぜ？",
		},
		WRITE =
        {
            GENERIC = "やめとくぜ…オレの字は汚ねぇからな",
        },
		RUMMAGE =
        {   
            GENERIC = "わりぃな、今はできねぇ", 
        },
		COOK =
        {
            GENERIC = "わりぃな、今は料理できねぇ",
            TOOFAR = "もうちっと近づかねぇとダメだな",
        },
        CHANGEIN =
        {
            GENERIC = "この格好の何が悪りぃんだ？",
            BURNING = "生きてる木が焼けちまうよりゃマシだ",
        },
        GIVE =
        {
            DEAD = "いや…そいつにやっても…なぁ",
            SLEEPING = "寝てるな",
            BUSY = "ちっと待ったほうがいいな",
        },
		REPAIRBOAT =
		{
			GENERIC = "修理するとこなんて、ないぜ？",
		},
		TEACH =
        {
            KNOWN = "そんなのは、もうとっくに知ってるぜ？",
            CANTLEARN = "あー…ルーシー、これ、わかるか？",
        },
	},
	ACTIONFAIL_GENERIC = "ごめん、ワシにはできないや。",
	ANNOUNCE_MAGIC_FAIL = "ここじゃムリみてぇだな",
	ANNOUNCE_ADVENTUREFAIL = "しょうがないか。頑張ったしね。",
	ANNOUNCE_BEES = "蜂だ！蜂だ！",
	ANNOUNCE_BOOMERANG = "すまん！″うっかりしてた！",
	ANNOUNCE_CHARLIE = "そこにいるのは誰なの、ねぇ？",
	ANNOUNCE_CHARLIE_ATTACK = "アイタタ！今のはきつかった！",
	ANNOUNCE_COLD = "ちと寒みぃな！",
	ANNOUNCE_HOT = "外はえらく暑いな！",
	ANNOUNCE_CRAFTING_FAIL = "いまはできないよ。",
	ANNOUNCE_DEERCLOPS = "あれは何だ？",
	ANNOUNCE_DUSK = "もうすぐおねんねの時間だ。",
	ANNOUNCE_NOSLEEPONFIRE = "完全に安全な場所とは言えない。",
	ANNOUNCE_NODANGERSIESTA = "シエスタしている暇はない、追われてる身だ。",
	ANNOUNCE_NONIGHTSIESTA = "木を倒す合間にシエスタで休む方が、夜よりも好きだ。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "木を倒す合間にシエスタで休む方が、夜よりも好きだ。",
	ANNOUNCE_NOHUNGERSIESTA = "腹がグルグル鳴ってる。もう永遠にリラックスできない。",
	ANNOUNCE_SHELTER = "この木のおかげで助かったぜ…",
	ANNOUNCE_BURNT = "イテ、熱い！",
	ANNOUNCE_TOOL_SLIP = "もう、悪夢に出てくるような！",
	ANNOUNCE_DAMP = "ちと湿ってきたな",
	ANNOUNCE_WET = "チェック柄は暖かい… たとえ濡れていても。",
	ANNOUNCE_WETTER = "けっこうひどく濡れてきたな、だろ？",
	ANNOUNCE_SOAKED = "Lucyにしっかり掴まっておかないとな。",

	ANNOUNCE_OTHER_WORLD_PLANT = "ここの土は、合わねぇってか？",

	ANNOUNCE_EAT =
	{
		GENERIC = "美味い！",
		PAINFUL = "有効期限を過ぎていた。",
		SPOILED = "ほんの少し臭った。",
		STALE = "時間内にちょうどそれを手に入れた。",
		INVALID = "歯だけじゃそれを噛みきれないと思う。",
		YUCKY = "脂のかたまり食ってたほうがマシだな…",
	},
	ANNOUNCE_ENTER_DARK = "誰が明かりを消したの？",
	ANNOUNCE_ENTER_LIGHT = "光り輝いている！",
	ANNOUNCE_FREEDOM = "脱出できた！",
	ANNOUNCE_HOUNDS = "そこに何かがある。",
	ANNOUNCE_HUNGRY = "腹がへってきた！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "野獣が近くにいる。",
	ANNOUNCE_HUNT_LOST_TRAIL = "ま、オレはきこりだ、狩人じゃねぇ",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "小動物の足跡が洗い流された。",
	ANNOUNCE_INV_FULL = "これ以上キットを持てないよ。",
	ANNOUNCE_KNOCKEDOUT = "オー。あれは何だ？",
	ANNOUNCE_MOSQUITOS = "蚊だ！",
	ANNOUNCE_NODANGERSLEEP = "外で寝るには怖すぎるよ。",
	ANNOUNCE_NODAYSLEEP = "ペテン師だけが昼間眠る。",
	ANNOUNCE_NOHUNGERSLEEP = "眠るにはお腹が減り過ぎてる。",
	ANNOUNCE_NO_TRAP = "惜しい！",
	ANNOUNCE_PECKED = "すまん！もっとマジにやってみるぜ！",
	ANNOUNCE_QUAKE = "地表が盛り上がってる！",
	ANNOUNCE_THORNS = "痛い！",
	ANNOUNCE_TORCH_OUT = "俺の明かりが消えてしまった！",
	ANNOUNCE_FAN_OUT = "せっかく涼しかったのによ…",
    ANNOUNCE_COMPASS_OUT = "針は動かねぇが、心はいつも北向いてるぜ",
	ANNOUNCE_TRAP_WENT_OFF = "おっとっと！",
	ANNOUNCE_WORMHOLE = "その中はゾッとするぜ！",
	ANNOUNCE_CANFIX = "\nこれを修理できると思う！",
	ANNOUNCE_ACCOMPLISHMENT= "Lucyは俺のことをとても誇りに思うだろう！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "うし、おつかれさん！",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "もっとフンが必要かい、え？",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "ありゃあ、ちょっとムズムズしたなぁ、な？",

	ANNOUNCE_BOAT_DAMAGED = "この船、だいぶガタが来てんな…",
	ANNOUNCE_BOAT_SINKING = "沈みそうだぜ！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "沈んじまうぜ！",
	ANNOUNCE_CRAB_ESCAPE = "逃げられちまったな",
	ANNOUNCE_HIGHRESEARCH = "ためになったぜ",
	ANNOUNCE_LOWRESEARCH = "たいして役に立たなかったな",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "未知の海域へ、突き進むぜ！",
	ANNOUNCE_MAPWRAP_RETURN = "ちと、無謀だったな！",
	ANNOUNCE_MAPWRAP_WARN = "こっから先は、未知の海域だぜ…",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"海水で字が消えちまってるぜ",
	},
	ANNOUNCE_MORETREASURE = "お宝、おかわりだぜ！",
	ANNOUNCE_NODAYSLEEP_CAVE = "のんびりする気分じゃねぇよ",
	ANNOUNCE_NOWARDROBEONFIRE = "ま、どうせネルシャツしか着ねぇしな",
	ANNOUNCE_OTHER_WORLD_TREASURE = "この世界でいくら探しても、ムダだな",
	ANNOUNCE_RESEARCH = "オレの頭もオノみてぇにキレッキレだぜ",
	ANNOUNCE_SHARX = "腹すかせた魚が寄ってきたぜ…！",
	ANNOUNCE_TRAWL_FULL = "そろそろ引き揚げてみるか！",
	ANNOUNCE_TREASURE = "ゴールドラッシュだぜ！",
	ANNOUNCE_UNIMPLEMENTED = "ッテ！まだ準備中みてぇだな…",
	ANNOUNCE_VOLCANO_ERUPT = "こりゃ、ずいぶん荒れた天気になりそうだ",
	ANNOUNCE_WAVE_BOOST = "北国の誇りにかけてッ！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "獣の追跡なら、オレに任しときな！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "悪りぃ！見失っちまった！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "あのクジラ、どこ行きやがった！？",

	BATTLECRY =
	{
		GENERIC = "これを超えて進めってことだろう！",
		PIG = "てめぇ、ベーコンにしてやる！",
		PREY = "ここで死んでもらうぜ！",
		SPIDER = "北国の誇りにかけてッ！",
		SPIDER_WARRIOR = "ブッたぎってやる！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "これでたぶん、十分だろう。",
		PIG = "ちと、しくじったな…",
		PREY = "悪りぃ！悪かった！悪かったよ！",
		SPIDER = "悪かったよ！",
		SPIDER_WARRIOR = "明日、また同じ時間に来てやるからな…",
	},
	DESCRIBE =
	{
		PIGMAN =
		{
			FOLLOWER = "ワシらはチームさ！イェーイ！",
			GENERIC = "歩きまわるベーコン！",
			GUARD = "あいつは真剣そうだね。",
			WEREPIG = "あいつも、選ばれしブタってわけだな",
			DEAD = "もう、ブタじゃなくなっちまったな",
		},
		GLOMMER = "パタパタ続けてくれよ、そこの小さい君！",
        GLOMMERFLOWER = 
        {
        	GENERIC = "その花でさえネバネバしてる。",
        	DEAD = "死んでなおかつネバネバ。",
        },
        GLOMMERWINGS = "あまり驚かないことに、羽がネバネバしている。",
        GLOMMERFUEL = "そだな、彼のスライムもネバネバだ。",
        BELL = "こんなにクリアな音をたてるなんて、感動だ。",
        STATUEGLOMMER = 
        {	
        	GENERIC = "こいつは興味深い像だね、え？",
        	EMPTY = "中にまた面白いものがあったな、なあ？",
    	},
		WEBBERSKULL = "実は、ガイコツも俺をギョッとビビらせる。",
		MOLE =
		{
			HELD = "石、欲しいか…？",
			UNDERGROUND = "掘れ、掘れ、掘れ。",
			ABOVEGROUND = "こいつは石について、俺が木に対して思うような気持ちを持っている。",
		},
		MOLEHILL = "たぶん中は、岩の山だと思うけど。",
		MOLEHAT = "新しく夜間木こりオープン！",
		NIGHTSTICK = "それはなんて、力強く素晴らしいんだ。",
		RABBITHOUSE=
		{
			GENERIC = "それってニンジン味？",
			BURNT = "それはあぶったニンジン味？",
		},
		TURF_DECIDUOUS = "ただの土だって、ねぇ？",
		TURF_SANDY = "Just some ground, eh?",
		TURF_BADLANDS = "ただの土だって、ねぇ？",

		LAVA_POND_ROCK = "岩だな",
		LAVA_POND_ROCK2 = "岩だな",
		LAVA_POND_ROCK3 = "岩だな",
		LAVA_POND_ROCK4 = "岩だな",
		LAVA_POND_ROCK5 = "岩だな",
		LAVA_POND_ROCK6 = "岩だな",
		LAVA_POND_ROCK7 = "岩だな",

		BEARGER = "こいつはでかいクマだ！",
		BEARGERVEST = "これはなかなか、寒い冬に適切な服だ！",
		CAVE_BANANA_BURNT = "もったいねぇなぁ…",
		SCORCHED_SKELETON = "気色悪りぃな…",
		ICEPACK = "長距離のハイキングに。",
		BEARGER_FUR = "俺の頭と同じくらい分厚い！",
		BIGFOOT = "足元に気をつけて！",
		BONESHARD = "パンの焼き方を知ってりゃ良かったな。",
		BUZZARD = "俺の肉スナックに近寄るなー！",
		CACTUS = 
		{
			GENERIC = "これはきっと痛いぞ。",
			PICKED = "確かに痛かった。",
		},
		CACTUS_MEAT_COOKED = "よっぽどいい。",
		CACTUS_MEAT = "釘を君の口に入れてくれる？",
		CACTUS_FLOWER = "この天気で、何か育つ方が不思議だよな。",
		COLDFIRE =
		{
			EMBERS = "もうすぐなくなるよ。",
			GENERIC = "故郷の冬みてぇに、ひんやりした火だな",
			HIGH = "まずいさ！ちょっと高すぎだ！",
			LOW = "なんとかしないといけないよ、なあ？",
			NORMAL = "夜の冷たい火はいいねえ。",
			OUT = "続いてた間はよかったんだけどね。",
		},
		CATCOON = "害獣。",
		CATCOONDEN = 
		{
			GENERIC = "ウェ、命をいったいあと幾つ持ってるんだ？",
			EMPTY = "ああせいせいした。",
		},
		CATCOONHAT = "きこりの伝統衣装だ",
		COONTAIL = "ネコも不死身じゃねぇってことだ",
		COOKPOT =
		{
			COOKING_LONG = "もうちょっとかかりそうだ、なあ？",
			COOKING_SHORT = "あぁ！やってきたぞ！",
			DONE = "夕飯の時間さ！",
			EMPTY = "空っぽのままにしておくなんて、なんだか無駄な気がするなぁ。",
			BURNT = "焦げ焦げに燃えた。",
		},
		EYEBRELLAHAT =	"いつも見守ってくれるものがいるというのはいいもんだ。",
		ARMORDRAGONFLY = "チェック柄さえあれば、それで俺には十分な鎧さ。",
		DRAGON_SCALES = "ドラゴンって、まだ信じてない。",
		DRAGONFLYCHEST = "ケバいな、俺に言わせれば。",
		DECIDUOUSTREE = 
		{
			BURNING = "やめろーー！俺が切り倒せた！",
			BURNT = "なんて無駄。",
			CHOPPED = "あーーーー！",
			GENERIC = "俺を呼んでいる！",
			POISON = "君が切られる番だね。",
		},
		ACORN_COOKED = "良質な木を無駄にして、勿体ない。",
		BIRCHNUTDRAKE = "お前も倒しちまうぞ！",
		FARMPLOT =
		{
			GENERIC = "大きな植物のほうが好みだ。",
			GROWING = "やつらは決して切るサイズにはならないだろう。",
			NEEDSFERTILIZER = "これにはいくらか糞が必要だと思う。",
			BURNT = "もしこれが木のファームだったら、俺は哀しい。",
		},
		COLDFIREPIT =
		{
			EMBERS = "それ用に少し木材を切り出しに行くべきだよな？",
			GENERIC = "それは木を使う。",
			HIGH = "沢山の木材を速く使い過ぎている！",
			LOW = "どこかこの近くに木材がいくらかあるはずだ。",
			NORMAL = "むむむむ。木の匂いがする。",
			OUT = "もしいくらか木材を持っていれば。",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "木を守れ！",
			OFF = "怠け者めが。",
			LOWFUEL = "それは木を欲するんだ。",
		},
		ICEHAT = "これだって、やろうと思えば切れるぞ。",
		LIGHTNINGGOAT = 
		{
			GENERIC = "なかなかイケてる角じゃないか。",
			CHARGED = "ナイスヤギ、ナイスヤギ！",
		},
		LIGHTNINGGOATHORN = "お前の角は俺のもの。",
		GOATMILK = "電気で凝固したみたい。",
		MEATRACK =
		{
			DONE = "もうできてるみたい。",
			DRYING = "肉が乾燥するのを見てるのに似てる。",
			DRYINGINRAIN = "これじゃ、雨ん中で肉を干すようなもんだ",
			GENERIC = "あとは肉を干すだけだな",
			BURNT = "その有用性も乾いてなくなった。",
		},
		MERMHEAD = 
		{
			GENERIC = "工場トロール船みたいな匂いだ。",
			BURNT = "信じがたいことだが、さらに強烈な臭いがしてきた。",
		},
		MERMHOUSE = 
		{
			GENERIC = "彼らは家まわりのことは得意じゃないらしい。",
			BURNT = "防火の備えがある家さえも作れなかった。",
		},
		FLOWERSALAD = "健康、だけど丈夫ではない。",
        ICECREAM = "木を十分切ってからのごほうび！",
        WATERMELONICLE = "木、で、食べ物？！",
        TRAILMIX = "一日木を切る時にぴったりのスナック。",
        HOTCHILI = "寒い中、木を切り倒した長い一日のあとにうってつけ。",
        GUACAMOLE = "信用していいものか、自信がない。",
		MOOSE = "何であるにしろ、間違いなくカナダ産だね。",
		MOOSEEGG = "それが、卵を産むらしいんだな、実は。",
		MOSSLING = "羽フワフワのムースの赤ちゃん！",
		FEATHERFAN = "伝統的なカナダの扇。",
		TROPICALFAN = "ここは暑すぎんだよ！",
		MINIFAN = "ここは暑すぎんだよ！",
		GOOSE_FEATHER = "フカフカの羽毛。",
		STAFF_TORNADO = "俺は一人で木を切るのが好きなんだ。",
		PIGHEAD = 
		{	
			GENERIC = "良質な豚肉を無駄にした。",
			BURNT = "どうも、料理がヘタなヤツがいるみてぇだ",
		},
		PIGHOUSE =
		{
			FULL = "ベーコンが詰まっている。",
			GENERIC = "少しのガムテープですぐに直せるだろう。",
			LIGHTSOUT = "悪りぃ！のぞく気はねぇんだよ！",
			BURNT = "かつての栄光の抜け殻。",
		},
		FERTILIZER = "フンはバケツの中に入るもんだ、地面じゃあない。",
		RAINOMETER = 
		{	
			GENERIC = "雨は木々を成長させる。",
			BURNT = "雨に関する知識は、それを火災からは守らなかった。",
		},
		RAINCOAT = "雨の中で木を切るときに。",
		RAINHAT = "木こりの後は、ドライな頭を保ちましょう、ってね。",
		RESEARCHLAB = 
		{	
			GENERIC = "俺は科学とか何だとか、あんまり信じてない。",
			BURNT = "どうやって燃えたんだ？！",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "なんか変なことになってきたぞ。",
			BURNT = "でも、基本的な物理の法則に従っているのは確かだが。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "よし、何となくわかってきたぞ。",
			BURNT = "だめだ、また分からん。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "俺はそれを「ハット・マシーン」と呼ぶ。",
			BURNT = "だから、ハット・ウォーマーとか信じないんだよ…。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "俺にはウッドがよく似合う。",
			BURNT = "燃えた場合はそれほど似合わない。",
		},
		ROCK_ICE = 
		{
			GENERIC = "ホーム、スイートホーム！",
			MELTED = "地元じゃ、絶対溶けないね。",
		},
		ROCK_ICE_MELTED = "地元じゃ、絶対溶けないね。",
		ICE = "ふるさとを思い出させてくれる、ポケットの中の家のかけら。",
        REFLECTIVEVEST = "チェック柄が全天候スタイルじゃないって、まだ納得できないんだけど。",
		HAWAIIANSHIRT = "チェックの方が好きだな。",
		TENT = 
		{
			GENERIC = "もっとひどいところに慣れてるよ。",
			BURNT = "思うに、これはテントとは呼べないかもな。",
		},
		SIESTAHUT = 
		{
			GENERIC = "一日中木を倒してる時、昼寝は大事だ。",
			BURNT = "残骸。",
		},
		TRANSISTOR = "どういう仕組みか、さっぱりわかんねぇな",
		TREASURECHEST = 
		{
			GENERIC = "木ってすげー便利！見て、こんないろいろ作れちゃうんだから！",
			BURNT = "ま、木にも弱点はあるってことだ…",
		},
		TUMBLEWEED = "もっと頑丈だったら… そしたら、俺が切ってやるのに。",
		GRASS_UMBRELLA = "ヒゲがそんなにぬれずに済むぜ",
		PALMLEAF_UMBRELLA = "なかなかいいカサに仕上がったよな？",
		WALL_HAY = 
		{	
			GENERIC = "クシャミで飛ばせるよ、なあ？",
			BURNT = "うーん、今のは展開が早過ぎたな。",
		},
		WALL_WOOD = 
		{
			GENERIC = "その見た目が好き！",
			BURNT = "前のルックスの方が好きだったな。",
		},
		WARDROBE = 
        {
        	GENERIC = "着るもんなんかに気ィ使ってられっかよ",
            BURNING = "やっぱり木は、燃やしてこそだな",
        	BURNT = "これじゃ、もう使えねぇな",
    	},
		WARG = "あいつだったら、一匹だけでそりを引けるだろう。",
		WATERMELON = "これは水とスイカ、両方だってどういうこと？",
		WATERMELON_COOKED = "焼いたフルーツって、納得いかないな…。",
		WATERMELONHAT = "俺のこと、「ミスター・スイカ」って呼んでいいよ。",
		WINTEROMETER = 
		{
			GENERIC = "これも、半分の高さで作れる。",
			BURNT = "地元のやつは燃えない。",
		},
		WORMLIGHT = "これは役に立つだろう。",
		WORM =
		{
		    PLANT = "その一つをみて植物だとわかった。これは替え玉だ！",
		    DIRT = "動いている地面に油断するな。",
		    WORM = "ミミズだーー！",
		},
		EEL = "これをうまく調理できるはず。",
		EEL_COOKED = "これは上手に料理されている。",
		UNAGI = "お腹いっぱいになるよ。",
		EYETURRET = "これで連中を追い払える。",
		EYETURRET_ITEM = "これはちゃんとインストールしなくちゃ。",
		MINOTAURHORN = "素敵な角だ、ねえ？",
		MINOTAURCHEST = "それは角の付いた素晴らしい収納箱だなぁ。",
		THULECITE_PIECES = "それは木製じゃないけれど、大丈夫。",
		POND_ALGAE = "食料品には見えない。",
		GREENSTAFF = "これで分解が楽になる！",
		POTTEDFERN = "俺の植物への愛を示しているんだ。",

		THULECITE = "洞窟の木だ！",
		ARMORRUINS = "それが苦痛を止めてくれるだろう。",
		RUINS_BAT = "棒に乗った金属。",
		RUINSHAT = "コックさんの帽子にはほど遠いけれど、まぁいいか。",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "オフのはずだ。",	--calm phase
			WARN = "今スイッチが入った！",	--Before nightmare
			WAXING = "振動している！", --Nightmare Phase first 33%
			STEADY = "発狂しているぞ！", --Nightmare 33% - 66%
			WANING = "落ち着いてきている。", --Nightmare 66% +
			DAWN = "ほぼ静止している。", --After nightmare
			NOMAGIC = "オフのはずだ。", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "内部の仕組みが見える！",
		ROOK_NIGHTMARE = "所持品が出てきちゃってる。",
		KNIGHT_NIGHTMARE = "最高の形には見えないけれど。",
		MINOTAUR = "また一つ、呪いをかけられた哀れな魂。",	--Monster in labyrinth
		SPIDER_DROPPER = "その邪悪から離れるとは奴らは賢い。",	--White spider that comes from the roof
		NIGHTMARELIGHT = "木材を使えばよかったのに。",	--Lights that activate during nightmare.
		RELIC = "Piece of furniture.",	--Fixed relic
		RUINS_RUBBLE = "めちゃくちゃになった。",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "これって…なんて美しいんだろう。",	--Works as axe and pickaxe
		GREENGEM = "なんて見かけ倒し。",
		ORANGESTAFF = "これは早く動き回る上で役に立つだろう。",	--Teleports player.
		YELLOWAMULET = "これで夜木を切ることができる。",	--Emits light, player walks faster.
		GREENAMULET = "いつもカットが得意だった。",	--Reduce cost of crafting

		SLURPER = "生きてる髪の毛かな。",
		SLURPER_PELT = "死んだビーバーみたいだ。",
		SLURPERPELT = "Where's the nearest fur trader?",
		ARMORSLURPER = "ムズムズする。それはまだ生きていると思う。",
		SPIDERHOLE_ROCK ="クモが出てくる前にズラかろうぜ",
		ORANGEAMULET = "これで雑用が素早く終わるようになるだろう。",
		YELLOWSTAFF = "ピンチでは役に立つ！",
		YELLOWGEM = "その中の星を見ることができる。",
		ORANGEGEM = "キラキラ光ってる。",
		RELIC =
		{
			BROKEN = "I don't plan on fixin' that.",
			GENERIC = "What's this all aboot?",
		},
		TELEBASE = 
		{
			VALID = "It's humming with energy.",
			GEMS = "I don't think it has power.",
		},
		GEMSOCKET = 
		{
			VALID = "準備万端みたい。",
			GEMS = "ジェムが必要。",
		},
		STAFFLIGHT = "えーっと、あれは何かじゃない。",	
		LUCY = "Lucyを愛している！",
        ANCIENT_ALTAR =
        {
        	WORKING = "これらの祭台には斧のマークがある。",
        	BROKEN = "少し消耗しているように見える。",
        },             
        ANCIENT_ALTAR_BROKEN = "少し消耗しているように見える。",
        ANCIENT_STATUE = "またペテン師さ。",
        LICHEN = "ぎりぎり食べられるかも。",
		CUTLICHEN = "美味しい！木の味がする！",
		CAVE_BANANA = "トロピカルな味がする。",
		CAVE_BANANA_COOKED = "とりあえず、焼いてみたぜ…",
		CAVE_BANANA_TREE = "あれは地元にはないよね。",
		ROCKY = "ロブスター晩餐の時間！",
		
		COMPASS =
		{
			GENERIC="これで、方角がわかるぜ",
			N = "真北。",
			S = "南",
			E = "東",
			W = "西",
			NE = "北東",
			SE = "南東",
			NW = "北西",
			SW = "南西",
		},

		BLUEAMULET = "ドリンクをキンキンに冷やせるぜ",
		PURPLEAMULET = "その宝石から輝きは失われた。",
		TELESTAFF = "Just another use for wood.",
		MONKEY = "よし、では。これが新しいやつだ。",
		MONKEYBARREL = "なんて厳選された建材なんだ。",

		HOUNDSTOOTH="こいつぁ、見事なキバだぜ！",
		ARMORSNURTLESHELL="安全すぎるということは決してない。",
		BAT="誰があのネズミに飛び方を教えたの？",
		BATBAT = "翼のついたネズミ？",
		BATWING="気味悪い。",
		BATWING_COOKED="気味悪い！そして美味い！かなり困惑している！",
		BATCAVE = "鳥みてぇな黒い獣の巣だ！",
		
		BEDROLL_FURRY="キャンプが大好き。",
		BUNNYMAN="親しみやすそうに見える。",
		FLOWER_CAVE="ピカピカ！",
		FLOWER_CAVE_DOUBLE="ピカピカ！",
		FLOWER_CAVE_TRIPLE="ピカピカ！",
		GUANO="他の種類よりは臭くはない。",
		LANTERN="これで明るくなるな",
		LIGHTBULB="噛み応えがありそうさ。",
		MANRABBIT_TAIL="彼がかわいそうさ。",
		MUSHTREE_TALL  ="I can't let that stand.",
		MUSHTREE_MEDIUM="Maybe I should chop it.",
		MUSHTREE_SMALL ="It's made of wood.",
		MUSHTREE_TALL=
		{
            GENERIC = "こいつぁ切ったほうがいいんじゃねぇか？",
            BLOOM = "胞子まき散らす前に、切っちまうか！",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "オノで切ってみるか…",
            BLOOM = "いい色してんじゃねぇか",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "こりゃ、木製だな",
            BLOOM = "今は切るのはやめとこうぜ…",
        },
        MUSHTREE_TALL_WEBBED = "誰も手入れしてねぇのかよ",
        SPORE_TALL = "空飛ぶ種だ！",
        SPORE_MEDIUM = "空飛ぶ種だ！",
        SPORE_SMALL = "空飛ぶ種だ！",
        SPORE_TALL_INV = "いつか木に育つかもしれねぇな",
        SPORE_MEDIUM_INV = "いつか木に育つかもしれねぇな",
        SPORE_SMALL_INV = "いつか木に育つかもしれねぇな",
		SLURTLE="彼は勘違いされてるだけさ。",
		SLURTLE_SHELLPIECES="彼の家を壊しちまった。気分が悪い。",
		SLURTLEHAT="これで俺の頭を安全に保てる。",
		SLURTLEHOLE="お前ら、元気でやってるか？",
		SLURTLESLIME="誰かがティッシュを必要としている。",
		SNURTLE="らせんだ！",
		SPIDER_HIDER="ずるい悪魔め！",
		SPIDER_SPITTER="唾を吐くのは無礼だ！",
		SPIDERHOLE="彼らが出てくる前に、さっさと逃げなくっちゃ。",
		STALAGMITE="石にはあまり興味がないんだ。",
		STALAGMITE_FULL="石にはあまり興味がないんだ。",
		STALAGMITE_LOW="石にはあまり興味がないんだ。",
		STALAGMITE_MED="石にはあまり興味がないんだ。",
		STALAGMITE_TALL="石にはあまり興味がないんだ。",
		STALAGMITE_TALL_FULL="石にはあまり興味がないんだ。",
		STALAGMITE_TALL_LOW="石にはあまり興味がないんだ。",
		STALAGMITE_TALL_MED="石にはあまり興味がないんだ。",


		TURF_CARPETFLOOR = "Some ground.",
		TURF_CHECKERFLOOR = "Some ground.",
		TURF_DIRT = "Some ground.",
		TURF_FOREST = "Some ground.",
		TURF_GRASS = "Some ground.",
		TURF_MARSH = "Some ground.",
		TURF_ROAD = "Some ground.",
		TURF_ROCKY = "Some ground.",
		TURF_SAVANNA = "Some ground.",
		TURF_WOODFLOOR = "Some ground.",

		TURF_CAVE="いくつかの土地。",
		TURF_FUNGUS="エンドウ豆みたいに煮くずれてる。",
		TURF_SINKHOLE="これを地下で見つけた。",
		TURF_UNDERROCK="岩だ。ヘンッ。",	
		TURF_MUD="少なくともそれをきれいにする必要はない。",

		
		POWCAKE = "本物のお砂糖でできた物の方が好きだ。",
        CAVE_ENTRANCE = "ふさがってるぜ",
        CAVE_ENTRANCE_RUINS = "ふさがってるぜ",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "洞窟ん中には、木なんてねぇだろうしな",
            OPEN = "下じゃ、鉱石が山ほど採れるかもな",
        },
        CAVE_EXIT = 
        {
            GENERIC = "もうちっと、ここでゆっくりしてこうぜ",
            OPEN = "地上に戻りゃ、木があるぜ",
        },
		
		MAXWELLPHONOGRAPH = "ラジオから流れるほとんどのものよりはマシ。",
		BOOMERANG = "それを投げるのは難しそうだ。",
		PIGGUARD = "彼を怒らせたくないのさ。",
		ADVENTURE_PORTAL = "あれがここから抜け出る道かな。",
		AMULET = "常にバックアッププランを用意。",
		ANIMAL_TRACK = "大きな森に住む動物がこの道を通り過ぎた！",
		ARMORGRASS = "何もないよりはマシだ。",
		ARMORMARBLE = "これを着ながら斧を振り下ろすのは大変だ。",
		ARMORWOOD = "俺にホントぴったり！",
		ARMOR_SANITY = "そいつを見ると吐き気がする。",
		ASH =
		{
			GENERIC = "すべて燃え尽きた。",
			REMAINS_GLOMMERFLOWER = "これはもっとネバネバした花だった。",
			REMAINS_EYE_BONE = "これは昔、目玉の骨だった。",
			REMAINS_THINGIE = "そいつはそこで上手くいかないと思う。",
		},
		AXE = "それはLucyほどステキではない。",
		BABYBEEFALO = "母親だけが愛せる顔。",
		BACKPACK = "それは俺のリュックサックだ。",
		BACONEGGS = "オウーー。まさに上質ベーコン。",
		BANDAGE = "少なくともその代金を支払う必要はなかった。",
		BASALT = "その岩は動こうとはしない。",
		BEARDHAIR = "オレのヒゲじゃねぇぞ…色が違ぇだろ？",
		BEDROLL_STRAW = "丸太小屋で、もっとひどい状態で眠りについてきた。",
		BEE =
		{
			GENERIC = "彼女がそれらの花を育てている。",
			HELD = "じゃあそれを使ってどうするか？",
		},
		BEEBOX =
		{
			FULLHONEY = "こりゃ、メープルシロップの代わりになるな！",
			READY = "こりゃ、メープルシロップの代わりになるな！",
			GENERIC = "ブンブンいう虫の巣箱だ！",
			NOHONEY = "見てるだけで腹が減ってくるぜ…",
			SOMEHONEY = "待っていればもっと手に入る。",
			BURNT = "その蜂たちはだめだ！",
		},
		BEEFALO =
		{
			FOLLOWER = "彼はワシを気に入ったみたい。",
			GENERIC = "芝土でできた家のような臭いがする。",
			NAKED = "元気出して、なあ？",
			SLEEPING = "睡眠補給中。",
		},
		BEEFALOHAT = "今や俺はそのビーファロの王だ！",
		BEEFALOWOOL = "ワシのヒゲみたい。",
		BEEHAT = "これで、ハチに目ん玉刺されずに済むな",
		
		BEEHIVE = "彼らはみんなその中で快適で心地良くしている。",
		
		BEEMINE = "蜂は怒るんじゃないかな。",
		BEEMINE_MAXWELL = "ねえ！そんなのって意地悪！",
		BERRIES = "ワシの食欲はもっと旺盛だぜい。",
		BERRIES_COOKED = "あったかいベリーのような味さ。",
		BERRYBUSH =
		{
			BARREN = "それは良質の糞を必要としている。",
			WITHERED = "熱にやられちまった、てか？",
			GENERIC = "サスカトゥーン・ベリー？",
			PICKED = "もうベリーがない！",
		},
		BIRDCAGE =
		{
			GENERIC = "悪りぃ鳥を入れて、反省させるオリだ",
			OCCUPIED = "自分がしたことを考えてみろ、鳥さんよう！",
			SLEEPING = "彼らが夢見ているときは、かなり無邪気に見える。",
			HUNGRY = "すぐに食いもん取ってきてやるからな",
			STARVING = "厚切りベーコンが食いてぇとよ！",
			DEAD = "すまねぇな…更正さしてやれなくてよ…",
			SKELETON = "ちょっとクサくなってきたな…",
		},
		BIRDTRAP = "これからこの鳥たちを見せるつもりだ！",
		BIRD_EGG = "邪悪の鳥の考えを持つ鳥が一羽その中にいる。",
		BIRD_EGG_COOKED = "とにかく、鳥にならなかっただけいいか。",
		BISHOP = "俺の最後の告白からしばらく時が流れた。",
		BLOWDART_FIRE = "ちょっと攻撃的かも。",
		BLOWDART_SLEEP = "これを使えば脱出に成功できる！",
		BLOWDART_PIPE = "俺の大きな肺でこれで何ができるか見てみよう。",
		BLUEGEM = "とても寒い。",
		BLUEPRINT = "俺は書物から学ぶタイプじゃない。",
		BELL_BLUEPRINT = "俺は書物から学ぶタイプじゃない。",
		BLUE_CAP = "あれは肉じゃないさ。",
		BLUE_CAP_COOKED = "あれは肉じゃないさ。",
		BLUE_MUSHROOM =
		{
			GENERIC = "どれが食用なのか、どうしても覚えられないわ。",
			INGROUND = "あとで戻ってくるよ。",
			PICKED = "もう、終わった。",
		},
		BOARDS = "かなり順調。実際にその穀物を見られる。",
		BOAT = "北東からの強風にぶつかったに違いない。",
		BONESTEW = "あばら骨にくっつく。",
		BUGNET = "蚊を集められる。",
		BUSHHAT = "自然から隠れるにはいいね。",
		BUTTER = "マーガリンのほうが好きだ。",
		BUTTERFLY =
		{
			GENERIC = "ああいうのは信じられないよ、なあ？",
			HELD = "どこへ逃げるのかい？",
		},
		BUTTERFLYMUFFIN = "ん…？固てぇもんが混じってるな…",
		BUTTERFLYWINGS = "悪いな！俺はどうしようもない人間なんだ！",
		CAMPFIRE =
		{
			EMBERS = "もうすぐなくなるよ。",
			GENERIC = "ギター鳴らして、歌でも歌うか？",
			HIGH = "まずいさ！ちょっと高すぎだ！",
			LOW = "なんとかしないといけないよ、なあ？",
			NORMAL = "夜の火はいいねえ。",
			OUT = "続いてた間はよかったんだけどね。",
		},
		CANE = "田舎ならいいけどね。",
		CARROT = "それってウサギの餌だよ。",
		CARROT_COOKED = "焼いたって、ウサギのエサには違ぇねぇ",
		CARROT_PLANTED = "ワシって野菜派じゃないんだよ、ねえ？",
		CARROT_SEEDS = "小さなニンジン。",
		CAVE_FERN = "ねえ！シダだ！",

		CHARCOAL = "ちょっと悲しい気分になるね。",

        CHESSJUNK1 = "死んでる金属",
        CHESSJUNK2 = "死んでる金属",
        CHESSJUNK3 = "死んでる金属",

		CHESTER = "奴はベストを尽くしている！",
		CHESTER_EYEBONE =
		{
			GENERIC = "凝視するのは不作法だと誰も彼に教えたことはなかった。",
			WAITING = "それはいつかまた目を覚ますのだろうか。",
		},
		COOKEDMANDRAKE = "それをしてはまずかったのか？",
		COOKEDMEAT = "愛しのばあちゃんが昔作ってくれた物のようだ。",
		COOKEDMONSTERMEAT = "まだ食べたくない。",
		COOKEDSMALLMEAT = "それじゃあお腹が減るばかりだよ！",
		CORN = "それは好きだが、食べた全部というわけじゃない。",
		CORN_COOKED = "トウモロコシの美味しさで調理した。",
		CORN_SEEDS = "俺は土壌の耕作者っていうより木こりだな。",
		CROW =
		{
			GENERIC = "彼は何か企んでる。ワシにはわかるよ。",
			HELD = "カラスめ、罰があたるぞ！",
		},
		CUTGRASS = "思うに俺はこれにアレルギーがあるみたい。",
		CUTREEDS = "水潜り鳥の鳴き声を真似してみようかい？",
		CUTSTONE = "カナダ盾状地の一部。",
		DEADLYFEAST = "あまり良い匂いはしないよな。",
		DEERCLOPS = "大きなムースだ！",
		DEERCLOPS_EYEBALL = "さてこれは何の役に立つ？",
		DEPLETED_GRASS =
		{
			GENERIC = "多分草やぶだ。",
		},
		DEVTOOL = "それについてコメントしていない。",
		DIRTPILE = "おお！ヒントだ！",
		DIVININGROD =
		{
			COLD = "ここからは実にファジー。",
			GENERIC = "ホッケーの試合に勝利したかは疑問だ。",
			HOT = "大きい声ではっきり！何かが近くにいる！",
			WARM = "俺は近づいていると思う。",
			WARMER = "ウォー、そこでは用心しろ、おまえ。",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "なんかを、つなげりゃいいみてぇだな",
			READY = "ロック解除の準備ができた。",
			UNLOCKED = "あとは電源を入れるだけさ。",
		},
		DIVININGRODSTART = "奇妙な見かけの棒だ。",
		DRAGONFLY = "あんなのに木ぃ燃やされてたまるかよ！",
		LAVAE = "オノでブッたぎってやる！",
		LAVAE_PET = 
		{
			STARVING = "アオサギの脚みてぇにガリガリだ…",
			HUNGRY = "腹減ってるみてぇだな…かわいそうに…",
			CONTENT = "ゴキゲンだな！",
			GENERIC = "オレのかわいいペットだ",
		},
		LAVAE_EGG = 
		{
			GENERIC = "中で火が燃えてるみてぇだな",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "厚手のジャケットでも着せてやるか…？",
			COMFY = "すっかりくつろいでるみてぇだな！",
		},
		LAVAE_TOOTH = "ルーシーほど鋭くねぇな！",

		LAVASPIT = 
		{
			HOT = "ああああ！ツリー・キラー！",
			COOL = "俺の木々はこれで安全だ。",
		},
		LAVA_POND = "近寄らねぇほうがよさそうだぜ…",
		DRAGONFRUIT = "今までこいつらを見たことがない。",
		DRAGONFRUIT_COOKED = "メープルシロップみたいな味がする。",
		DRAGONFRUIT_SEEDS = "多分俺はもっと成長できる。",
		DRAGONPIE = "バタータルトくらいに美味しい！",
		DRUMSTICK = "10月の食料。",
		DRUMSTICK_COOKED = "ありがとう、七面鳥。",
		DUG_BERRYBUSH = "ちょっとした造園の時間。",
		DUG_GRASS = "おかげで涙が出てくる。",
		DUG_MARSH_BUSH = "これを植えるべきだな。",
		DUG_SAPLING = "ウーーーン。全部小枝みたいだ。",
		DURIAN = "臭い。",
		DURIAN_COOKED = "もっとひどい匂いがする。",
		DURIAN_SEEDS = "なんでそんなのをもっと生やしたいと思うかな。",
		EARMUFFSHAT = "俺の出身地ではこいつらは滝でしか使えない。",
		EGGPLANT = "鳥たちがこれに何か関係しているに違いない。",
		EGGPLANT_COOKED = "疑わしい鳥さんだな。",
		EGGPLANT_SEEDS = "うーん。確信はない。",
		ACORN = 
		{
		    GENERIC = "そうだ、自分で育てて切り倒すべきだ！",
		    PLANTED = "よし、木だ！",
		},
		EVERGREEN =
		{
			BURNING = "やめろーー！そいつを切り刻めた！",
			BURNT = "なんて無駄。",
			CHOPPED = "あーーーー！",
			GENERIC = "そいつは俺を呼んでいる！",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "ごめんよ！",
			BURNT = "イヤな気分！",
			CHOPPED = "まただ！",
			GENERIC = "Lucyだったら切り倒してほしがるだろうな。",
		},
		EYEPLANT = "自分自身の仕事を気にかけることが必要だ。",
		FEATHERHAT = "んなもん、触んのもゴメンだぜ",
		FEATHER_CROW = "気持ち悪い羽。",
		FEATHER_ROBIN = "気色悪い羽。",
		FEATHER_ROBIN_WINTER = "バカな羽。",
		FEM_PUPPET = "あいつが罠にかかった！",
		FIREFLIES =
		{
			GENERIC = "カナダのアルゴンキン公園を思い出すなあ。",
			HELD = "ポケットにいっぱいの太陽を持っているのだ！",
		},
		FIREHOUND = "ホットハウンド！",
		FIREPIT =
		{
			EMBERS = "それ用に少し木材を切り出しに行くべきだよな？",
			GENERIC = "木材を使っている。",
			HIGH = "沢山の木材を速く使い過ぎている！",
			LOW = "どこかこの近くに木材がいくらかあるはずだ。",
			NORMAL = "むむむむ。木の匂いがする。",
			OUT = "もしいくらか木材を持っていれば。",
		},
		FIRESTAFF = "この魔法とやらは信用しない。",
		FISH = "タラみたい。",
		FISHINGROD = "湖で時間を過ごそうかな。",
		FISHSTICKS = "箱に入った洗練されたダイニング。",
		FISHTACOS = "海みてぇな味だ",
		FISH_MED = "今夜の晩メシだな",
		FISH_MED_COOKED = "ポテトチップスがあったらいいのに。",
		FISH_COOKED = "ポテトチップスがあったらいいのに。",
		FLINT = "これって斧頭になるかも。",
		FLOWER = "そりゃいい。",
		FLOWER_WITHERED = "いるよな、すぐ花を枯らしちまうヤツ…",
		FLOWERHAT = "オレの赤毛によく似合いそうだ",
		FLOWER_EVIL = "その花はどこかおかしい｡",
		FOLIAGE = "サラダみたいだ。",
		FOOTBALLHAT = "これ被ったらホッケー選手みたいな髪型になる？",
		FROG =
		{
			DEAD = "元カエル。",
			GENERIC = "空か海か選べないやつなんて信用できないよ。",
			SLEEPING = "疲れてるみたい。",
		},
		FROGGLEBUNWICH = "本当にその沼地の味がする。",
		FROGLEGS = "あいつらはまだジャンプしている！",
		FROGLEGS_COOKED = "とにかく彼らは移動するのをやめた。",
		FRUITMEDLEY = "シロップ漬け！",
		GEARS = "俺がこれらの物事を解明できることはないだろう。",
		GHOST = "ブー！ハハハ！",
		GOLDENAXE = "Lucyくらいに素敵だね。",
		GOLDENPICKAXE = "きれいな道具だが、これじゃ木は切れねぇ",
		GOLDENPITCHFORK = "作っちまったんだから、使うしかねぇな",
		GOLDENSHOVEL = "金の穴を掘る時間。",
		GOLDNUGGET = "金からコーヒーテーブルは作れない。\nいや、できるかもな。でも作るべきじゃない。",
		GRASS =
		{
			BARREN = "その上にうんちしなくちゃ。",
			WITHERED = "涼しくなりゃ、また生えんじゃねぇか？",
			BURNING = "木々に広がらないと良いけれど。",
			GENERIC = "発火みたいだ。",
			PICKED = "こぶだらけになっちゃった。",
		},
		GREEN_CAP = "林の中の見知らぬ物を食べた。",
		GREEN_CAP_COOKED = "俺はそれを信用しない。",
		GREEN_MUSHROOM =
		{
			GENERIC = "緑のキノコだ。",
			INGROUND = "各自の予定がある。",
			PICKED = "壊しちゃったかも。",
		},
		GUNPOWDER = "こんなことをしたのは一度もなかった。",
		HAMBAT = "良質なハムを無駄にした。",
		HAMMER = "誰でも過ちは犯すものだろう？",
		HEALINGSALVE = "ぐちゃぐちゃとしての健全さ。",
		HEATROCK =
		{
			FROZEN = "ブルル！凍ってる。",
			COLD = "寒くなったんだよな？",
			GENERIC = "こいつらを故郷では「夜の岩」と呼ぶ。",
			WARM = "だんだんと少し… 中くらいになってきた。",
			HOT = "あれがポケットにあれば、冬中ずっとたたき切れる！",
		},
		HOME = "そこにいるのは誰だ？",
		HOMESIGN = 
		{
			GENERIC = "木材で、できないことなんてあるんだろうか？",
			BURNT = "木が一番長けているのは、燃えることだが。",
		},
		HONEY = "うーーーーーん、うーーん。蜂のシロップ。",
		HONEYCOMB = "これを取るのはなんだか気が引ける。",
		HONEYHAM = "でも今は休日ではない…",
		HONEYNUGGETS = "ワシのお気に入り料理の一つ！",
		HORN = "俺の口をそこにつけるべきかわからない。",
		HOUND = "奴らはきっとそりを引くのが上手いだろう。",
		HOUNDBONE = "犬の唾液で覆われている、よな？",
		HOUNDMOUND = "あれにちょっかいを出すほどバカじゃないさ。",
		ICEBOX = "あぁ。故郷を思い出すなぁ。",
		ICEHOUND = "北極の猟犬？",
		INSANITYROCK =
		{
			ACTIVE = "それはどこに行ったのだ？！",
			INACTIVE = "それをどうやって動かすのかわからない。",
		},
		JAMMYPRESERVES = "さてと、ピーナッツバターを探さなきゃ。",
		KABOBS = "その小枝は絶妙にフレーバーを加味する。",
		KILLERBEE =
		{
			GENERIC = "その蜂はあまり気の良い風には見えない。",
			HELD = "逃げたくてしょうがねぇみてぇだな…",
		},
		KNIGHT = "Maxwellの自分自身の騎馬警官。",
		KOALEFANT_SUMMER = "彼は美味しそうだな。",
		KOALEFANT_WINTER = "冬には美味しくなる。",
		KRAMPUS = "後ろへ下がれ、この野郎！",
		KRAMPUS_SACK = "誰かのずだ袋を取ってしまっていやな気分。",
		LEIF = "これらの木、全て残念だったな。",
		LEIF_SPARSE = "これらの木、全て残念だったな。",
		LIGHTNING_ROD =
		{
			CHARGED = "きれいだな…オーロラみてぇだ",
			GENERIC = "天気が俺を出し抜くことはないだろう。",
		},
		LITTLE_WALRUS = "なぜ彼らはそんなに遠い南にいるのか？",
		LIVINGLOG = "君をキープしてFrankと呼ぶことにする。",
		LOCKEDWES = "あの野郎は誰だ？",
		LOG =
		{
			BURNING = "やめろ！丸太を燃やすんじゃねぇ！",
			GENERIC = "全部値打ちはある。",
		},
		LUREPLANT = "肉か？",
		LUREPLANTBULB = "温かくてゴツゴツしている。",
		MALE_PUPPET = "助けが必要か？",
		MANDRAKE =
		{
			DEAD = "すまない、平凡な君。",
			GENERIC = "こっちをじっと見つめている。",
			PICKED = "俺は何をやっちまった？",
		},
		MANDRAKESOUP = "うんざりするスープだ。",
		MANDRAKE_COOKED = "すまん！",
		MARBLE = "政府のビルみたいな感じ。",
		MARBLEPILLAR = "誰かがそれを建てたに違いない。",
		MARBLETREE = "Lucyでもあれは切り刻めない。",
		MARSH_BUSH =
		{
			BURNING = "フーームフ！",
			GENERIC = "キイチゴだ。",
			PICKED = "その価値があったのか？",
		},
		MARSH_PLANT = "植物。",
		MARSH_TREE =
		{
			BURNING = "トゲトゲの罰だ！",
			BURNT = "当然の報いだ。",
			CHOPPED = "激しい戦いだったけれど、ワシの勝ちだ。",
			GENERIC = "木は応戦すべきじゃないさ！",
		},
		MAXWELL = "なぜ奴は俺を嫌うのだ？",
		MAXWELLHEAD = "ただ頭ってことか？",
		MAXWELLLIGHT = "それは不自然だ。",
		MAXWELLLOCK = "そのカギはどこだ？",
		MAXWELLTHRONE = "もっと素晴らしい椅子を見た。",
		MEAT = "ムースのような味。",
		MEATBALLS = "全部肉だ！",
		MEAT_DRIED = "サバイバルの味がする。",
		MERM = "あれはいったいどんな汚い海から這い出してきたんだ？",
		MINERHAT = "炭鉱の奥深く。",
		MONSTERLASAGNA = "これはキャットフードだ！",
		MONSTERMEAT = "それを食べるほど腹ぺこじゃない。",
		MONSTERMEAT_DRIED = "まだ食べたくない。",
		MOSQUITO =
		{
			GENERIC = "それが俺からパイントを奪っていくつもりだ。",
			HELD = "これで何をするとしようか？",
		},
		MOSQUITOSACK = "血とはらわたじゃないか？",
		MOUND =
		{
			DUG = "すまん！俺に付きまとうな！",
			GENERIC = "多分そいつを一人で残しておくべきだな。",
		},
		NIGHTLIGHT = "それはどんな類の闇なのか？",
		NIGHTMAREFUEL = "ワシの恐怖が結集された液体ってとこだ、ねえ？",
		
		NIGHTSWORD = "悪夢が君に害を与えることはない！",
		NITRE = "俺たちがどのように鉄道を作ったかを示している。",
		ONEMANBAND = "君を守るために俺は立っている。",
		PANDORASCHEST = "その箱の中に何が入っている？！",
		PANFLUTE = "俺はLucyのためだけに歌う。",
		PAPYRUS = "書くよりも切り刻むほうがいい。",
		PENGUIN = "ふるさとの鳥だろうと、信用ならねぇよ",
		PERD = "もっと鳥が！なんでいつも鳥なんだ？",
		PEROGIES = "こいつらを「おいしいポケット」と呼ぶ。",
		PETALS = "Lucyもこれらが気に入るかは疑問だ。",
		PETALS_EVIL = "小さな悪魔の顔で奴らは俺に眉をひそめた。",
		PHLEGM = "ヒゲについてっと、みっともねぇんだよな",
		PICKAXE = "斧みたいだけど、ちょっと違う。",
		PIGGYBACK = "俺はそのブタの全部分を使った。",
		PIGKING = "奴は俺の王ではない。",
		PIGSKIN = "しっぽ付きベーコン。",
		PIGTORCH = "親指なしで、どうやってやつらはそれをできたのか？",
		PINECONE = 
		{
		    GENERIC = "それを育てて切り倒すべきだな！",
		    PLANTED = "よし、木だ！",
		},
		LUMPY_SAPLING = "チッ…また切らなきゃなんねぇのかよ…",
		PITCHFORK = "これって僕のスタイルじゃないな。",
		PLANTMEAT = "気持ち悪い！",
		PLANTMEAT_COOKED = "焼いても大して変わんねぇな…",
		PLANT_NORMAL =
		{
			GENERIC = "それが何になるのかな。",
			GROWING = "監視されている植物は決して成長しない。",
			READY = "食事の時間。",
			WITHERED = "もう生気は残ってない、か？",
		},
		POMEGRANATE = "俺には派手すぎる。",
		POMEGRANATE_COOKED = "これはホットケーキに乗せるとおいしいだろう。",
		POMEGRANATE_SEEDS = "種が多い。",
		POND = "俺は泳げないんだ！",
		POOP = "キャンプでウンコをするな！",
		PUMPKIN = "地面で成長しているものを食べるのは好きじゃない。",
		PUMPKINCOOKIE = "これで伐採を続けられる。",
		PUMPKIN_COOKED = "パイって美味しいのだ。",
		PUMPKIN_LANTERN = "ひっくり帰らなければいいけど。",
		PUMPKIN_SEEDS = "種だ。",
		PURPLEGEM = "上手く切り倒して解決できないものなど何もない。",
		RABBIT =
		{
			GENERIC = "いまいましいリスめ…",
			HELD = "彼を食べるのは気が進まない。",
		},
		RABBITHOLE = 
		{
			GENERIC = "おそらくそっちの方には、木はあまりないだろう。",
			SPRING = "出入りするものはない。",
		},
		RATATOUILLE = "「皿の上の森」、ってとこだな",
		RAZOR = "真の木こりは決して髭を剃らない。",
		REDGEM = "何千本もの木がその中で燃え死んでいるのが見える。",
		RED_CAP = "わからない…",
		RED_CAP_COOKED = "ものすごくお腹がすいたときにだけ。",
		RED_MUSHROOM =
		{
			GENERIC = "赤いキノコだ。",
			INGROUND = "各自の予定がある。",
			PICKED = "壊しちゃったかも。",
		},
		REEDS =
		{
			BURNING = "炎をみると落ち着かない。",
			GENERIC = "アシだ。",
			PICKED = "彼らは戻ってくるさ。",
		},
        RUBBLE = "壊れた家具。",
		RESURRECTIONSTONE = "触るべきかわからない。",
		ROBIN =
		{
			GENERIC = "なんて横柄でチビで間抜け。",
			HELD = "快適になるなよ、小鳥さん。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "南へ向かって飛ぶとか！",
			HELD = "俺の温かさを盗んでいる！",
		},
		ROBOT_PUPPET = "なんか捕まってるぞ！",
		ROCK_LIGHT =
		{
			GENERIC = "表面が、ちと固くなってるな",
			OUT = "こりゃ、崩れそうだな…",
			LOW = "もっと…木が必要？",
			NORMAL = "まきを必要としない火？自然じゃない！",
		},
		ROCK = "かなり頑張ればそれを壊せた。",
		ROCKS = "いいイヌクシュクが造れそうだぜ…",
        ROOK = "うーむ…そのヤマガラスは直線的に動くのか？忘れた。",
		ROPE = "他の物のために物を持っておくのは良いことだ。",
		ROTTENEGG = "一羽少ない鳥。やったね。",
		SANITYROCK =
		{
			ACTIVE = "その岩の何かが変、だろ？",
			INACTIVE = "つじつまが合う。",
		},
		SAPLING =
		{
			BURNING = "あぁ！彼にはほとんどチャンスがなかった！",
			WITHERED = "この熱波じゃ、木が切れる大きさに育たないよ！",
			GENERIC = "大きく育ったら、切り倒してぇな",
			PICKED = "採集ってのは、切るのよりつまらないね。",
		},
		SEEDS = "木じゃない。",
		SEEDS_COOKED = "俺たちはこれを「木こりのサプライズ」と呼ぶ。",
		SEWING_KIT = "裁縫はかなり得意だぜ。",
		SHOVEL = "穴を掘れ。木を植えろ！",
		SILK = "クモたちが俺をドキドキさせている。",
		SKELETON = "悪いな、友よ。",
		SKELETON_PLAYER = "ここまで来ると、究極のブルブルガタガタものだ。",
		SKULLCHEST = "こわいー！",
		SMALLBIRD =
		{
			GENERIC = "一体どうしたいんだ？",
			HUNGRY = "何かを必要としている。",
			STARVING = "餓死寸前だと思う。",
		},
		SMALLMEAT = "これが大きければ良かったのに。",
		SMALLMEAT_DRIED = "たった一口。",
		SPAT = "オレのかあちゃんソックリだ！",
		SPEAR = "良質の頑丈な斧の重さに欠けている。",
		SPIDER =
		{
			GENERIC = "今まで見たことないくらい大きなクモだ！",
			SLEEPING = "気をつけて、ね？",
			DEAD = "うし！",
		},
		SPIDERDEN = "神聖なマッキーノ！あれを見てみろよ！",
		SPIDEREGGSACK = "なぜ俺はあれをあちこち持ち運びたがるのだろう？",
		SPIDERGLAND = "それは毒だと思う。",
		SPIDERHAT = "彼女は本物の美じゃないか？",
		SPIDERQUEEN = "君はワシの女王様じゃないんだわ！",
		SPIDER_WARRIOR =
		{
			GENERIC = "色違いかよ",
			SLEEPING = "起こすとやっかいだぜ…",
			DEAD = "っしゃ！",
		},
		SPOILED_FOOD = "あぁ、ディーフェンベーカーになっちゃったわさ。",
		STATUEHARP = "頭をなくしちゃったみたいだ、ね？",
		STATUEMAXWELL = "彼ってイヤなやつだ、ねえ？",
		STEELWOOL = "これでオノ磨くと、ピカピカになるぜ",
		STINGER = "痛い！先がとがっている。",
		STRAWHAT = "それで俺の頭を日光から守り続けてくれる。",
		STUFFEDEGGPLANT = "料理していると気分が良くなる。",
		SUNKBOAT = "その木はかつてはもっと状態が良かった。",
		SWEATERVEST = "チェック柄じゃないけれど、まぁいいか。",
		TAFFY = "甘くていいな。",
		TALLBIRD = "飛べない鳥も、信用できないな。",
		TALLBIRDEGG = "中に何が入っている？",
		TALLBIRDEGG_COOKED = "正義の味がする。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "君には寒すぎる？",
			GENERIC = "孵化している。",
			HOT = "泣いているのか？",
			LONG = "鳥たちは決して機敏ではない。",
			SHORT = "もうすぐだ。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "卵を盗んで、思い知らせてやる。",
			PICKED = "そこには何もない。",
		},
		TEENBIRD =
		{
			GENERIC = "成長し嫌な奴になる、まるで両親みたいに。",
			HUNGRY = "君はいつも腹ペコなのか？",
			STARVING = "腹ペコだとど気が荒くなってくる。",
		},
		TELEBASE =
		{
			VALID = "準備はできているが、俺自身は？",
			GEMS = "宝石が必要だな？",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "準備はいいよな？",
			GENERIC = "それは…魔法がかってると思う。",
			LOCKED = "ちょっと足りなくないか？",
			PARTIAL = "ほぼ準備万端だよな？",
		},
		TELEPORTATO_BOX = "角張ってる、だろ？",
		TELEPORTATO_CRANK = "不機嫌そうだな？",
		TELEPORTATO_POTATO = "ポテトー、でしょう？",
		TELEPORTATO_RING = "怒った、でしょう？",
		TELESTAFF = "これは何をするものなんだろう。",
		TENTACLE = "土ん中にイカがいんのか？",
		TENTACLESPIKE = "振ると揺れるぞう。",
		TENTACLESPOTS = "ほっぺが赤くなってきたさ！",
		TENTACLE_PILLAR = "かなりデカイ。",
		TENTACLE_PILLAR_HOLE = "あのイカ…どこへ消えやがった！？",
		TENTACLE_PILLAR_ARM = "あれってばイカの赤ちゃん？",
		TENTACLE_GARDEN = "もうこのイカはたくさんだ！",
		TOPHAT = "お洒落すぎる。",
		TORCH = "焚き火の明かりで木こりごっこ。",
		TRAP = "もっと賢く働こう、ねえ？",
		TRAP_TEETH = "ちょっと手荒かもしれない。",
		TRAP_TEETH_MAXWELL = "彼はフェアなプレーをしてない、ねえ？",
		TREASURECHEST_TRAP = "あのチェストは何かがおかしい。",
		MOOSE_NESTING_GROUND = "見るのもイヤだぜ",
		TRINKET_1 = "このゲームは昔やっていた。",
		TRINKET_10 = "お年寄りには、ぶった切る道具を。",
		TRINKET_11 = "そこ、静かに！",
		TRINKET_12 = "全部干からびている。",
		TRINKET_2 = "本物じゃない、ねえ？",
		TRINKET_3 = "昔きいた話に似てる。",
		TRINKET_4 = "ワシにきかないで。",
		TRINKET_5 = "ロボットアームが必要だ、ね？",
		TRINKET_6 = "もう美味しくないよ、なあ？",
		TRINKET_7 = "何時間でもやっていられる！",
		TRINKET_8 = "これで風呂桶がみつかれば、完璧さ。",
		TRINKET_9 = "その洋服を着て、単に周りをぐるっと縫うだけ。",
		TRUNKVEST_SUMMER = "いーいそよ風",
		TRUNKVEST_WINTER = "地元の冬に勝るとも劣らない、ね？",
		TRUNK_COOKED = "鼻の角質が全部茹で落ちちゃったみたいだね。",
		TRUNK_SUMMER = "けっこう薄い。",
		TRUNK_WINTER = "分厚くて毛深そう。",
		TURF_CARPETFLOOR = "俺の趣味的には高級すぎだ。",
		TURF_CHECKERFLOOR = "これらの街の人たちの納屋の一つのようだ。",
		TURF_DIRT = "ただの土だって、ねぇ？",
		TURF_FOREST = "ただの土だって、ねぇ？",
		TURF_GRASS = "ただの土だって、ねぇ？",
		TURF_MARSH = "ただの土だって、ねぇ？",
		TURF_ROAD = "ただの土だって、ねぇ？",
		TURF_ROCKY = "ただの土だって、ねぇ？",
		TURF_SAVANNA = "ただの土だって、ねぇ？",
		TURF_WOODFLOOR = "王様にふさわしい床張り！",
		TURF_DRAGONFLY = "これは、燃えなそうだな",
		TURF_DESERTDIRT = "Just some ground, eh?",
		TURF_FUNGUS_GREEN = "Just some ground, eh?",
		TURF_FUNGUS_RED = "Just some ground, eh?",
		TURKEYDINNER = "七面鳥の日がまたやって来た！",
		TWIGS = "木を切る用の小さな斧を作ろうかな。",
		BANANAPOP = "メープルタフィのほうが、うまいぜ…",
		BISQUE = "こりゃうまそうだ",
		CEVICHE = "こりゃ、食わない手はねぇな",
		SEAFOODGUMBO = "オレの故郷にはねぇ料理だ",
		SURFNTURF = "こいつぁ、うまそうだ",
		SHARKFINSOUP = "オレの腹ん中で泳いでもらうぜ",
		LOBSTERDINNER = "サーモンはねぇのか？",
		LOBSTERBISQUE = "無人島で、こんないいもん食えるとはな",
		JELLYOPOP = "こりゃ、ゼリーか？アイスか？",
		UMBRELLA = "これで俺の髭を乾かしたままにできるっていうことか？",
		UNIMPLEMENTED = "安全には見えないよ。",
		WAFFLES = "ホットケーキの方がいいな。",
		WALL_HAY_ITEM = "クシャミで飛ばせるよ、なあ？",
		WALL_STONE = "安心安全だ、なあ？",
		WALL_STONE_ITEM = "安心安全だ、なあ？",
		WALL_RUINS = "崩れ落ちてるけれど、まだまだしっかりしてるよ、ね？",
		WALL_RUINS_ITEM = "酔っぱらって石で殴られたの、ねぇ？",
		WALL_WOOD_ITEM = "その見た目が好き！",
		WALL_MOONROCK = "わりと丈夫そうじゃねぇか",
		WALL_MOONROCK_ITEM = "持ってるだけじゃ意味ねぇぞ",
		WALRUS = "なんてことだ！またセイウチだ！",
		WALRUSHAT = "ワシのじいさんがそんな帽子を被ってた。",
		WALRUS_CAMP =
		{
			EMPTY = "冬になったら、これじゃあ危ない。",
			GENERIC = "セイウチが近くにいる、ねえ？",
		},
		WALRUS_TUSK = "彼には虫歯があったのだろう？",
		WASPHIVE = "なんであの蜂たちはそんなに怒っているのさ？",
		WORMLIGHT_LESSER = "ビーバーの腹みてぇにシワシワだ",
		WETGOOP = "もっとひでぇもん食ったことあるぜ",
        WHIP = "ちっこい動物をケガさせねぇようにな",
		WINTERHAT = "ステキなトークじゃないか？",
		WORMHOLE =
		{
			GENERIC = "ホームレスみたい！",
			OPEN = "あんまり見たくないかもしれない、ねえ？",
		},
		WORMHOLE_LIMITED = "ちょっと変な臭いがするよ、なあ？",
		ACCOMPLISHMENT_SHRINE = "ワシにはちょっと見栄っ張りな感じがするな。",  
		BISHOP_CHARGE_HIT = "おい！何しやがんだ！",        		
		LIVINGTREE = "葛藤を感じてる、ねえ？",
		ICESTAFF = "それは我が家を思い起こさせる。",
		MOONROCKNUGGET = "月から降ってきた石っころだ",
        ROCK_MOON = "月から降ってきた石っころだ",

		------------------------------capy---------------------------------

		WOODLEGS_CAGE = "おい、アンタ！大丈夫か？",

		TWISTER = "自然がカンシャク起こしてるぜ！",
		WIND_CONCH = "風の歌が聞こえてくるぜ…",

		AERODYNAMICHAT = "かぶると足が速くなるぜ",
		ANTIVENOM = "味はひでぇが、効果は抜群だぜ！",
		ARMORCACTUS = "なかなかトゲのあるよろいだな",
		ARMORLIMESTONE = "着ると強くなった気分になるぜ",
		ARMOROBSIDIAN = "アッツアツだな",
		ARMORSEASHELL = "あんまり強そうには見えねぇけどなぁ",
		ARMOR_LIFEJACKET = "ま、着てると安心感はあるな",
		ARMOR_SNAKESKIN = "着ると、男前の気分が味わえるぜ",
		ARMOR_WINDBREAKER = "着ると故郷を思い出すぜ",
		ARMOUREDBOAT = "海で安全対策っつったら、これが限界だろ",
		BABYOX = "全身、ヒゲだらけだな",
		BALLPHIN = "アンタ、曲芸、できるか？",
		BAMBOO = "軽いな…木もダイエットすんのか？",
		BAMBOOTREE =
		{
			BURNT = "ベーコンみてぇにカリカリだな",
			CHOPPED = "なかなかの切り心地だったぜ！",
			GENERIC = "ルーシーは、こいつに目がなくてな",
		},
		BERMUDATRIANGLE = "ちと、不気味だな…",
		BIGFISHINGROD = "ずいぶんと、でけぇ釣りざおだな",
		BIOLUMINESCENCE = "オーロラみてぇだ",
		BLOWDART_FLUP = "目玉で“大目玉”食らわしてやる！…ってな",
		BLOWDART_POISON = "大静脈に刺さりゃ、一発だな",
		BLUBBER = "ぶよぶよして、だらしねぇな",
		BLUBBERSUIT = "見栄えはイマイチだな",
		BOATCANNON = "これで敵をフッ飛ばせるぜ！",
		BOATREPAIRKIT = "船を修理する道具だな",
		BOAT_LANTERN = "船につるす明かりだな",
		BOAT_TORCH = "これで夜釣りができるな",
		BOTTLELANTERN = "中に、光る虫が入ってるぜ",
		BRAINJELLYHAT = "かぶると、キレ者になった気分になるぜ",
		BUOY = "オレも、のらりくらりと生きてぇもんだ",
		BURIEDTREASURE = "っしゃ、いっちょ掘ってみようぜ！",
		BUSH_VINE =
		{
			BURNT = "あれじゃ、もう生えてこねぇな",
			CHOPPED = "切るの、楽しかったぜ…木には劣るけどよ",
			GENERIC = "切らずには、いられねぇな…",
		},
		CAPTAINHAT = "オレは、船と運命を共にする気はねぇぜ",
		CARGOBOAT = "荷物持ち担当の船、ってとこだな",
		CHIMINEA = "火によろい着せるみてぇなもんだな",
		CLOTHSAIL = "これで、海の旅が楽になるぜ",
		COCONADE =
		{
			BURNING = "逃げろ！",
			GENERIC = "こいつは破壊力抜群だぜ",
		},
		COCONUT = 
		{
		    GENERIC = "ただのヤシの実だ",
		    PLANTED = "ちっこいヤシの木が生えてきたぜ",
		},
		COCONUT_COOKED = "これなら食えるぜ",
		COCONUT_HALVED = "ルーシーと半分ずつだ",
		COFFEE = "コーヒーか…ありがてぇ",
		COFFEEBEANS = "煎ってコーヒーにしねぇとな",
		COFFEEBEANS_COOKED = "カナダ人は、特にコーヒー好きなんだぜ",
		COFFEEBOT = "これでコーヒー作れるな？",
		COFFEEBUSH =
		{
			BARREN = "どうした、元気ねぇじゃねぇか",
			GENERIC = "コーヒー豆だ！",
			PICKED = "もうちっと、たくさん採れりゃなぁ…",
			WITHERED = "コーヒー飲ませりゃ、元気になるかもな",
		},
		CORAL = "こいつを砕いて、なんか作れそうだな",
		CORALREEF = "採り放題だな",
		CORAL_BRAIN = "脳っぽいな",
		CORAL_BRAIN_ROCK = "なんだ、こりゃ？脳ミソか？",
		CRAB =
		{
			GENERIC = "ダチになれるかもな？",
			HIDDEN = "そのうち出てくるはずだぜ",
		},
		CRABHOLE = "あん中にクラビットの野郎が住んでるぜ",
		CRATE = "ありゃ…箱だな",
		CUTLASS = "なかなか立派な剣じゃねぇか",
		DEAD_SWORDFISH = "すまねぇ…",
		DEPLETED_BAMBOOTREE = "早く生えてきな！また切ってやるからよ！",
		DEPLETED_BUSH_VINE = "ま、そのうちまた、生えてくんだろ",
		DEPLETED_GRASS_WATER = "待たされんのは嫌いだぜ",
		DEVTOOL_NODEV = "こいつぁ…なんだ？",
		DOUBLE_UMBRELLAHAT = "これで、防水性2倍だな！",
		DOYDOY = "こいつら、よく生きてこられたもんだぜ",
		DOYDOYBABY = "汚い。",
		DOYDOYEGG = "食ったらうまそうだぜ",
		DOYDOYEGG_COOKED = "カナディアンベーコンに合いそうだな",
		DOYDOYEGG_CRACKED = "割れちまったもんは、しょうがねぇな",
		DOYDOYFEATHER = "ガチョウの羽毛は、カナダ産が一番だぜ",
		DOYDOYNEST = "汚ねぇ鳥どもが、卵産んで育てる場所だ",
		DRAGOON = "あいつら、ちと頭冷やしたほうがいいな",
		DRAGOONDEN = "ありゃ、ビーバーの巣じゃねぇよな",
		DRAGOONEGG = "ありゃ、どうも怪しいぜ",
		DRAGOONHEART = "怪物の心臓だぜ",
		DRAGOONSPIT = "腹立つ！",
		DUBLOON = "金を掘り当てたぜ！",
		DUG_BAMBOOTREE = "オレと来やがれ！",
		DUG_BUSH_VINE = "散歩に連れてってやるぜ",
		DUG_COFFEEBUSH = "これで、どこでもいっしょだな",
		DUG_ELEPHANTCACTUS = "いっしょに行こうぜ？",
		EARRING = "もう片方はどこいったんだ？",
		ELEPHANTCACTUS = "トゲのある野郎だ",
		ELEPHANTCACTUS_ACTIVE = "草のくせに、攻撃してきやがるぜ！",
		ELEPHANTCACTUS_STUMP = "暴れて、くたびれたんだろ",
		FABRIC = "チェック柄にできねぇかな",
		FEATHERSAIL = "汚ねぇ羽根触って作ったかいがあったぜ",
		FISHINHOLE = "もうちと寒けりゃ、氷穴釣りできるけどな",
		FISH_RAW = "サーモンはねぇのか？",
		FISH_RAW_SMALL = "クマが寄ってこねぇといいがな",
		FISH_RAW_SMALL_COOKED = "うまそうじゃねぇか",
		FLAMEGEYSER = "ちとアツくなりすぎだ！",
		FLOTSAM = "ガラクタばっかだ",
		FLUP = "触んないで！",
		FRESHFRUITCREPES = "メープルシロップ、かけてぇな",
		FROG_POISON = "ツバがかかったら、危ねぇぞ！",
		GASHAT = "これで、どんな悪臭も怖くねぇな",
		GOLDENMACHETE = "見た目もいいし、切れ味も抜群だ",
		GRASS_WATER = "ちと湿ってきたな",
		HAIL_ICE = "こんなもん、氷のうちに入らねぇよ",
		HOUNDFIRE = "明々と燃えてやがるぜ！",
		ICEMAKER =
		{
			HIGH = "ふるさとの冬みてぇだな！",
			LOW = "勢いがなくなってきたな",
			NORMAL = "順調に氷を作ってるぜ",
			OUT = "くたばっちまったな",
			VERYLOW = "今にも止まりそうだぜ",
		},
		INVENTORYGRAVE = "誰かいたみてぇだが、もういねぇ…",
		INVENTORYMOUND = "誰かいたみてぇだが、もういねぇ…",
		IRONWIND = "スピード出そうだな",
		JELLYFISH = "見てのとおり、クラゲだぜ",
		JELLYFISH_COOKED = "ま、料理しても、うまそうには見えねえな",
		JELLYFISH_DEAD = "すっかりくたばっちまってるな",
		JELLYFISH_PLANTED = "クラゲの野郎だ",
		JELLYJERKY = "干し肉か…ふるさとの味だ",
		JUNGLETREE =
		{
			BURNING = "あれじゃ、もう、切れねぇな…",
			BURNT = "なんて無駄。",
			CHOPPED = "切るの、楽しかったぜ",
			GENERIC = "木の呼び声が聞こえるぜ…！",
		},
		JUNGLETREESEED =
        {
            GENERIC = "育ったら、切るのが楽しみだぜ",
            PLANTED = "あとは育つのを待つだけだぜ",
        },
		KNIGHTBOAT = "ありゃ、怒ると手がつけられねぇタイプだな",
		KRAKEN = "ルーシー、見てろよ！",
		KRAKENCHEST = "っしゃ！お宝ゲットだ",
		KRAKEN_TENTACLE = "なれなれしく触んじゃねぇ！",
		LAVAPOOL = "見てるだけで汗が噴き出るぜ",
		LIMESTONE = "きれいなサンゴを砕いて作ったぜ",
		LIMPETROCK =
		{
			GENERIC = "小腹すいたときに、ちょうどよさげだな",
			PICKED = "ただの、でけぇ岩だな",
		},
		LIMPETS = "水辺で獲れた貝だ",
		LIMPETS_COOKED = "晩メシができたぜ",
		TREEGUARD = "森を怒らせちまった！",
		LIVINGJUNGLETREE = "オレに切ってほしくてしかたねぇらしい",
		LOBSTER = "溶かしバターつけたら、うめぇだろうな",
		LOBSTERHOLE = "隠れてねぇで、出てこい！",
		LOBSTER_DEAD = "すっかり、くたばっちまってるぜ",
		LOBSTER_DEAD_COOKED = "こいつは、うまそうだ！",
		LOGRAFT = "オレにぴったりの船だな！",
		LUGGAGECHEST = "なんかいいもん、入ってるか？",
		MACHETE = "なかなかよく切れそうじゃねぇか",
		MAGIC_SEAL = "ナゾのエネルギーを感じるぜ…",
		MAGMAROCK = "イヌクシュク造りにぴったりだな",
		MAGMAROCK_FULL = "イヌクシュク造りにぴったりだな",
		MAGMAROCK_GOLD = "こりゃ、掘ってみる価値ありそうだぜ",
		MAGMAROCK_GOLD_FULL = "こりゃ、掘ってみる価値ありそうだぜ",
		MANGROVETREE = "おいしそうだね！",
		MANGROVETREE_BURNT = "気の毒で、見てらんねぇよ…",
		MARSH_PLANT_TROPICAL = "ちっぽけな草だぜ",
		MERMFISHER = "あいつの正体は…よくわからねぇな…",
		MERMHOUSE_FISHER = "オレは丸太小屋のほうが好みだぜ",
		MESSAGEBOTTLE = "オレ宛てか？",
		MESSAGEBOTTLEEMPTY = "何が入ってたんだろうな",
		MONKEYBALL = "何ニヤついてやがる？",
		MONSTERTARTARE = "他に食いもんねぇのかよ？",
		MOSQUITOSACK_YELLOW = "酸っぱいニオイがするぜ",
		MOSQUITO_POISON = "あいつは、病気のもとだぜ",
		MUSSEL = "結構、うまそうじゃねぇか",
		MUSSELBOUILLABAISE = "こんないいもん食えるの、久々だぜ",
		MUSSEL_COOKED = "うまそうだぜ",
		MUSSEL_FARM =
		{
			GENERIC = "こいつら、「食ってくれ」って言ってるぜ？",
			STICKPLANTED = "ムール貝料理にありつけそうだな",
		},
		MUSSEL_STICK = "ムール貝は、この棒に目がねぇんだ",
		MYSTERYMEAT = "なんだ、こりゃあ？",
		NEEDLESPEAR = "こいつぁまた、ずいぶん鋭いな",
		OBSIDIAN = "じんわり、あったけぇな",
		OBSIDIANAXE = "火を吹くオノ…ルーシーのライバルか？ヘヘ…",
		OBSIDIANCOCONADE = "こいつぁ、すげぇ爆発力だぜ",
		OBSIDIANFIREPIT =
		{
			EMBERS = "それ用に少し木材を切り出しに行くべきだよな？",
			GENERIC = "こりゃ、火ィ燃やすにゃ最高だ！",
			HIGH = "沢山の木材を速く使い過ぎている！",
			LOW = "どこかこの近くに木材がいくらかあるはずだ。",
			NORMAL = "むむむむ。木の匂いがする。",
			OUT = "もしいくらか木材を持っていれば。",
		},
		OBSIDIANMACHETE = "切るもの全部、炎上するぜ！",
		OBSIDIANSPEARGUN = "突くのと燃やすの、同時にできるぜ",
		OBSIDIAN_WORKBENCH = "炎系の道具が造れそうだな",
		OCTOPUSCHEST = "ありがたくちょうだいするぜ",
		OCTOPUSKING = "よう、調子はどうだい",
		OX = "物憂げな顔してやがるぜ",
		OXHAT = "北国の男にふさわしい帽子だぜ",
		OX_FLUTE = "オレはギターのほうが得意だぜ",
		OX_HORN = "ウシの頭にくっついてたもんだ",
		PACKIM = "この鳥は、まだマシだな",
		PACKIM_FISHBONE = "鳥が寄ってこねぇだろうな…？",
		PALMLEAF = "自分をあおぐのにちょうどいいぜ",
		PALMLEAF_HUT = "きこりにとっちゃ、最高の小屋だぜ",
		PALMTREE =
		{
			BURNING = "あれじゃ、もう、切れねぇな",
			BURNT = "なんて無駄。",
			CHOPPED = "切るの、楽しかったぜ",
			GENERIC = "木場が恋しいぜ…",
		},
		PARROT = "また鳥か！シッシッ！",
		PARROT_PIRATE = "鳥なんかと、しゃべることはねぇよ",
		PEACOCK = "間抜けな格好しやがって！フンッ！",
		PEG_LEG = "これも切っていいか？",
		PIGTENT = "テントかなんかか…？",
		PIKE_SKULL = "ずいぶんと悪趣味な飾りだな",
		PIRATEGHOST = "悪いオバケじゃねぇかもな？",
		PIRATEHAT = "海賊暮らしも、悪くねぇかもな",
		PIRATEPACK = "お宝入れるのに、ちょうどいいぜ",
		PIRATIHATITATOR =
		{
			BURNT = "すっかり黒焦げだぜ",
			GENERIC = "おもしれぇ格好の装置だな",
		},
		POISONHOLE = "近づかないほうがよさそうだぜ",
		PORTAL_SHIPWRECKED = "ブッ壊れてんじゃねぇか？",
		PRIMEAPE = "鼻持ちならねぇ野郎だ",
		PRIMEAPEBARREL = "サルどもの寝床だ",
		RAFT = "みすぼらしい船だぜ",
		RAWLING = "こいつ、怪しいぜ！",
		REDBARREL = "それは危険に見える。",
		RELIC =
		{
			BROKEN = "オレは修理する気はねぇぞ",
			GENERIC = "こりゃ、なんの道具だ？",
		},
		ROCK_CHARCOAL = "触ると手が真っ黒になっちまう",
		ROCK_OBSIDIAN = "中で火が燃えてるぜ",
		ROWBOAT = "手動船舶、ってヤツだな",
		SAIL = "まさに、順風満帆だぜ",
		SAIL_STICK = "北風を自由に操れるぜ",
		SAND = "ザラついてんな",
		SANDBAG = "ダム造りだったら、任してくれ",
		SANDBAGSMALL = "ダム造りだったら、任してくれ",
		SANDBAGSMALL_ITEM = "好きなところにダムを造れるぜ",
		SANDBAG_ITEM = "好きなところにダムを造れるぜ",
		SANDHILL = "砂の山だな",
		SAND_CASTLE =
		{
			GENERIC = "砂で、こんなきれいなもんが造れるとはな",
			SAND = "いい感じに見える。",
		},
		SEAGULL = "害鳥だぜ",
		SEAGULL_WATER = "海の害鳥だぜ",
		SEASACK = "お宝を入れる袋だ",
		SEASHELL = "オレの工芸魂がうずくぜ",
		SEASHELL_BEACHED = "きれいな貝殻だな",
		SEATRAP = "晩メシはウォブスターだな",
		SEAWEED = "ヌルヌルしてやがるぜ",
		SEAWEED_COOKED = "食べ慣れねぇ食感だな…",
		SEAWEED_DRIED = "舌にくっつきやがる",
		SEAWEED_PLANTED = "ありゃ、海藻だな",
		SHADOWSKITTISH_WATER = "やべぇぞ…！",
		SHARKITTEN = "ちとデカめだが、かわいいネコだな",
		SHARKITTENSPAWNER =
		{
			GENERIC = "ネコの鳴き声、しなかったか？",
			INACTIVE = "見たところ、ただの砂山みたいだな",
		},
		SHARK_FIN = "こいつは、オレがもらっていいよな？",
		SHARK_GILLS = "魚の肺だ",
		SHARK_TEETHHAT = "歯でできた帽子だ",
		SHARX = "あいつとは、仲よくなれそうにねぇな",
		SHIPWRECKED_ENTRANCE = "うし！冒険に出発しようぜ！",
		SHIPWRECKED_EXIT = "んじゃ、またな",
		SLOTMACHINE = "北の精霊が、きっと幸運を運んでくれるぜ",
		SLURPERPELT = "このへんに、毛皮商はいるか？",
		SNAKE = "ヘビん中じゃ、まだマシな種類だ",
		SNAKEDEN =
		{
			BURNT = "あれじゃ、もう生えてこねぇな",
			CHOPPED = "切るの、楽しかったぜ…木には劣るけどよ",
			GENERIC = "切らずには、いられねぇな…",
		},
		SNAKEOIL = "オレはだまされねぇぞ",
		SNAKESKIN = "これは、もらっといていいよな？",
		SNAKESKINHAT = "なかなか上等な帽子だ",
		SNAKESKINSAIL = "船もオシャレしねぇとな",
		SNAKE_FIRE = "ちと熱くなりすぎじゃねぇか？",
		SNAKE_POISON = "あいつにかまれると、ちとやっかいだぜ",
		SOLOFISH = "お利口なワン公だ",
		SPEARGUN = "こいつぁ、上等な武器だぜ！",
		SPEARGUN_POISON = "穂先の部分に、毒を仕込んであるぜ",
		SPEAR_LAUNCHER = "こいつぁ、上等な武器だぜ！",
		SPEAR_OBSIDIAN = "こいつぁ、なかなかアツい武器だぜ！",
		SPEAR_POISON = "敵をジワジワ苦しめるぜ",
		SPOILED_FISH = "いいかげん、捨てたほうがいいかもな",
		STUNGRAY = "ずぶぬれのヘラジカよりクセぇな！",
		SUNKEN_BOAT =
		{
			ABANDONED = "せっかくの木材が台なしだぜ",
			GENERIC = "よう、調子はどうだい",
		},
		SUNKEN_BOAT_BURNT = "ありゃ、修理のしようがねぇな",
		SUNKEN_BOAT_TRINKET_1 = "オレには、ちと高級すぎるぜ",
		SUNKEN_BOAT_TRINKET_2 = "ちと小さすぎるな",
		SUNKEN_BOAT_TRINKET_3 = "これは…ゴミじゃねぇのか？",
		SUNKEN_BOAT_TRINKET_4 = "インテリ連中のおもちゃだろ",
		SUNKEN_BOAT_TRINKET_5 = "サイズが合わねぇな",
		SUPERTELESCOPE = "アルバータの平原みてぇに、遠くまで見える",
		SWEETPOTATOSOUFFLE = "高級料理だな！",
		SWEET_POTATO = "料理に使えそうだな",
		SWEET_POTATO_COOKED = "焼きマシュマロ、乗せてぇな",
		SWEET_POTATO_PLANTED = "こじゃれたイモだな",
		SWEET_POTATO_SEEDS = "土に埋めねぇと意味ねぇな",
		SWIMMINGHORROR = "あいつとは関わりたくねぇな！",
		SWORDFISH = "ずいぶん、とんがった魚だな",
		TELEPORTATO_SW_BASE = "ガムテープで修理できんじゃねぇか？",
		TELEPORTATO_SW_BOX = "なんかに使えるはずだぜ",
		TELEPORTATO_SW_CRANK = "捨てずに持っとこうぜ",
		TELEPORTATO_SW_POTATO = "こいつはイモじゃねぇ、オレにはわかる",
		TELEPORTATO_SW_RING = "輪っか…みてぇだけどなぁ…",
		TELESCOPE = "遠くまでよく見えるぜ",
		THATCHPACK = "これで丸太を山ほど持てるぜ",
		TIDALPOOL = "魚どものたまり場みてぇだな",
		TIDAL_PLANT = "あれは丸太にはできねぇな…",
		TIGEREYE = "ジロジロ見やがって…失礼なヤツだぜ",
		TIGERSHARK = "オレを食おうとすんのが、玉にキズだな",
		TOUCAN = "あの鳥、どうも信用ならねぇな…",
		TRAWLNET = "魚が勝手に飛び込んでくるぜ",
		TRAWLNETDROPPED =
		{
			GENERIC = "どんな魚がかかったか、楽しみだぜ！",
			SOON = "沈みそうだぜ！",
			SOONISH = "だんだん沈んでるな…",
		},
		TREECLUMP = "オレにブッた切ってほしいのか？",
		TRIDENT = "すいぶんでっけぇフォークだな、おい！",
		TRINKET_13 = "飲んでも大丈夫か…？",
		TRINKET_14 = "こりゃ、オレの顔か？",
		TRINKET_15 = "このギター、ずいぶんちっこいな！",
		TRINKET_16 = "ただの金属の板じゃねぇか",
		TRINKET_17 = "サイズが合わねぇな",
		TRINKET_18 = "壊れてるな",
		TRINKET_19 = "飲んだら、どうなんだろな？",
		TRINKET_20 = "オレには、ちと高級すぎるぜ",
		TRINKET_21 = "ちと小さすぎるな",
		TRINKET_22 = "使いものにならなそうだぜ",
		TRINKET_23 = "なんだこりゃ？さっぱりわからねぇな",
		TROPICAL_FISH = "フィッシュ・アンド・チップスにするか",
		TUNACAN = "ルーシーでブッたたきゃ、開くだろ",
		TURBINE_BLADES = "見てると目が回るぜ",
		TURF_SANDY = "ただの土だって、ねぇ？",
		TURF_ASH = "ただの土だって、ねぇ？",
		TURF_BEACH = "ただの土だって、ねぇ？",
		TURF_DESERTDIRT = "どっかの地面だな",
		TURF_FUNGUS_GREEN = "どっかの地面だな",
		TURF_FUNGUS_RED = "どっかの地面だな",
		TURF_JUNGLE = "ただの土だって、ねぇ？",
		TURF_MAGMAFIELD = "ただの土だって、ねぇ？",
		TURF_MEADOW = "ただの土だって、ねぇ？",
		TURF_SNAKESKINFLOOR = "ただの土だって、ねぇ？",
		TURF_SWAMP = "ただの土だって、ねぇ？",
		TURF_TIDALMARSH = "ただの土だって、ねぇ？",
		TURF_VOLCANO = "ただの土だって、ねぇ？",
		TWISTER_SEAL = "ずいぶんかわいらしいのが出てきたな",
		VENOMGLAND = "ヘンなニオイがするぜ",
		VINE = "はぁ…こいつは木じゃねぇのか…",
		VOLCANO = "こいつぁ、たまげたぜ！",
		VOLCANOSTAFF = "火山の力を操れるぜ",
		VOLCANO_ALTAR =
		{
			GENERIC = "特に使い道はなさそうだな",
			OPEN = "ここに、何かささげりゃいいのか？",
		},
		VOLCANO_ALTAR_BROKEN = "完全にブッ壊れてるな",
		VOLCANO_ALTAR_TOWER = "不気味な岩の塊だな…",
		VOLCANO_EXIT = "ズラかろうぜ",
		VOLCANO_SHRUB = "枝も幹も、すっかり黒焦げだぜ",
		WALLYINTRO_DEBRIS = "ここは…どこだ？",
		WALL_LIMESTONE = "こいつぁ…壁だな",
		WALL_LIMESTONE_ITEM = "「壁を造るより、橋をかけよう」、ってな",
		WATERMELON_SEEDS = "植えてみるか…？",
		WATERYGRAVE = "こんな墓には、葬られたくねぇな",
		WHALE_BLUE = "メソメソ泣くんじゃねぇ！",
		WHALE_BUBBLES = "そこにいんのは、わかってるぜ",
		WHALE_CARCASS_BLUE = "しっかし、でけぇな",
		WHALE_CARCASS_WHITE = "やれやれ、だな",
		WHALE_TRACK = "獲物を追うぜ",
		WHALE_WHITE = "海を自由に駆け回る、凶暴な獣だぜ",
		WILBUR_CROWN = "ずいぶん豪華なかぶりもんだな",
		WILBUR_UNLOCK = "新しい仲間ができたぜ",
		WILDBORE = "こいつぁ信用ならねぇな",
		WILDBOREHEAD = "気の毒なこった",
		WILDBOREHOUSE = "怪しい連中の家だ",
		WOODLEGSBOAT = "豪勢な船だが、ちとトロそうだな",
		WOODLEGSHAT = "毛皮の耳当てつけたら、カンペキだな",
		WOODLEGSSAIL = "なかなかしゃれた帆だな",
		WOODLEGS_KEY1 = "どこのカギだ…？",
		WOODLEGS_KEY2 = "こいつは…どこのカギだ？",
		WOODLEGS_KEY3 = "持っといたほうが、よさそうだな",
		WRECK = "せっかくの木材が、台なしだぜ",
		CALIFORNIAROLL = "街の気取った連中が食ってるヤツだな",

	},
	DESCRIBE_GENERIC = "それは一体なんだろう？",
	DESCRIBE_TOODARK = "真っ暗だぜ！",
	DESCRIBE_SMOLDERING = "もうすぐ燃え上がるところ、か？",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "ちと、熟れすぎ…いや、若すぎか？",
	},
}
