return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Lo toserò mentre sta dormendo.",
			GENERIC = "Non vale la pena raderlo.",
			NOBITS = "Ma non c'è nulla da tagliare!",
		},
		STORE =
		{
			GENERIC = "È già ricco di merci.",
			NOTALLOWED = "Ho paura che non vada là.",
		},
		RUMMAGE =
        {   
            GENERIC = "Se non posso farlo, non si può fare!",   
        },
		COOK =
        {
            GENERIC = "Ahimè! Battuta dalle pentole!",
            TOOFAR = "Devo chiudere il divario tra noi!",
        },
        WRITE =
        {
            GENERIC = "Temo di non poter!",
        },
        GIVE =
        {
            DEAD = "Avranno cose migliori nel Valhalla.",
            SLEEPING = "Che dolce dormire... forse più tardi.",
            BUSY = "Ci proverò di nuovo quando ha finito.",
        },
        CHANGEIN =
        {
            GENERIC = "Ecco dove tengo tutte le mie pellicce e pelli preferiti.",
            BURNING = "Argh! Le mie pellicce!",
        },
        TEACH =
        {
            KNOWN = "Ho già brandito tale conoscenza.",
            CANTLEARN = "Quella conoscenza è vietata dagli dei.",
        },
		REPAIRBOAT =
		{
			GENERIC = "La mia imbarcazione è riparata!",
		},
	},
	ACTIONFAIL_GENERIC = "Se non posso farlo, non può essere fatto.",
	ANNOUNCE_MAGIC_FAIL = "I suoi poteri magici si sono indeboliti!",
	ANNOUNCE_ADVENTUREFAIL = "Torna nell'ultraterreno. La vittoria sarà mia!",
	ANNOUNCE_BEES = "Indietro, creaturine arpionate!",
	ANNOUNCE_BOOMERANG = "Argh! Devo padroneggiare l'arma ricurva.",
	ANNOUNCE_CHARLIE = "Rivelati!",
	ANNOUNCE_CHARLIE_ATTACK = "Codardo!",
	ANNOUNCE_COLD = "Brrr! Dove sono le mie pellicce?",
	ANNOUNCE_HOT = "Il sole caldo mi stanca.",
	ANNOUNCE_CRAFTING_FAIL = "Mi mancano le disposizioni necessarie.",
	ANNOUNCE_DEERCLOPS = "Un degno nemico si avvicina!",
	ANNOUNCE_DUSK = "Il sole sta tramontando, l'oscurità attende nelle vicinanze.",
	ANNOUNCE_EAT =
	{
		GENERIC = "La carne fa cantare il mio cuore!",
		PAINFUL = "Oh, non mi sento bene.",
		SPOILED = "Uh, fresco sarebbe meglio.",
		STALE = "Quella era una bestia stantia.",
		INVALID = "Non è cibo adatto ad un guerriero!",
		YUCKY = "Non è cibo adatto ad un guerriero!",
	},
	ANNOUNCE_ENTER_DARK = "E cala il sipario.",
	ANNOUNCE_ENTER_LIGHT = "Ho calpestato la luce!",
	ANNOUNCE_FREEDOM = "Libertà! La saga continua!",
	ANNOUNCE_HIGHRESEARCH = "Sono un'artigiana eccellente.",
	ANNOUNCE_HOUNDS = "Le bestie si avvicinano...",
	ANNOUNCE_HUNGRY = "Quanto manca al banchetto?",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Presto... la creatura è vicina.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Ho perso le tracce.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "È troppo fangoso per essere trascinato.",
	ANNOUNCE_INV_FULL = "Sto trasportando tutto quello che posso!",
	ANNOUNCE_KNOCKEDOUT = "Ah, la mia testa.",
	ANNOUNCE_LOWRESEARCH = "Non è stato molto eccitante.",
	ANNOUNCE_MOSQUITOS = "Via, piccoli demoni!",
	ANNOUNCE_NODANGERSLEEP = "Dormire non è sicuro. Usa la lancia!",
	ANNOUNCE_NODAYSLEEP = "Il sole è alto, inizia il viaggio!",
	ANNOUNCE_NODAYSLEEP_CAVE = "Non mi riposerò ancora.",
	ANNOUNCE_NOHUNGERSLEEP = "Digiunerò durante la notte! Banchetto prima.",
	ANNOUNCE_NOSLEEPONFIRE = "Non dormirò tra le fiamme.",
	ANNOUNCE_NODANGERSIESTA = "La battaglia è iniziata, non ci sarà nessun riposo!",
	ANNOUNCE_NONIGHTSIESTA = "Non sonnecchiare al chiaro di luna.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Non mi sembra il momento per un pisolino.",
	ANNOUNCE_NOHUNGERSIESTA = "Vorrei uno spuntino di carne prima di tutto.",
	ANNOUNCE_NO_TRAP = "Grazie al cielo, cammino con passo felpato.",
	ANNOUNCE_PECKED = "Via, beccuti esuberanti!",
	ANNOUNCE_QUAKE = "Il mondo trema!",
	ANNOUNCE_RESEARCH = "Il potere della conoscenza è immenso.",
	ANNOUNCE_SHELTER = "Ah! Riparo!",
	ANNOUNCE_THORNS = "Argh, sono stata infilzata!",
	ANNOUNCE_TORCH_OUT = "La mia luce è spenta!",
	ANNOUNCE_TRAP_WENT_OFF = "Questo non faceva parte del piano.",
	ANNOUNCE_UNIMPLEMENTED = "Non è di questo mondo.",
	ANNOUNCE_WORMHOLE = "È stata un'avventura sciatta.",
	ANNOUNCE_CANFIX = "\nPosso ripararlo.",
	ANNOUNCE_FAN_OUT = "Ho perso un altro ventaglio!",
	ANNOUNCE_ACCOMPLISHMENT = "Posso tornare alla battaglia adesso?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Vittoria! Va bene, andiamo.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Più escrementi per te?",
	ANNOUNCE_TOOL_SLIP = "Diavolo scivoloso!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "L'ho cavalcato su una saetta.",

	ANNOUNCE_DAMP = "Agile per la battaglia.",
	ANNOUNCE_WET = "Sono una guerriera bagnata.",
	ANNOUNCE_WETTER = "Questo conta come un bagno?",
	ANNOUNCE_SOAKED = "Sono quasi annegata!",
	
	ANNOUNCE_OTHER_WORLD_PLANT = "Una tale pianta non potrà mai prosperare in questo regno!",

	ANNOUNCE_BOAT_DAMAGED = "La mia imbarcazione è ferita!",
	ANNOUNCE_BOAT_SINKING = "Il mare mi spinge verso gli inferi!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Queste profondità oscure presto mi chiameranno a loro!",
	ANNOUNCE_BURNT = "Ahiaaaa!",
	ANNOUNCE_CRAB_ESCAPE = "È scomparso!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Le correnti sono il mio padrone!",
	ANNOUNCE_MAPWRAP_RETURN = "Sono riemersa dalla nebbia!",
	ANNOUNCE_MAPWRAP_WARN = "Ho raggiunto la fine del mondo!",
	ANNOUNCE_MORETREASURE = "Sorrido a questo giorno!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Questa mappa descrive un'altra terra.",
	ANNOUNCE_SHARX = "Nemici dalla schiuma!",
	ANNOUNCE_TRAWL_FULL = "La mia rete è piena di meravigliose delizie.",
	ANNOUNCE_TREASURE = "La mappa racconta di un tesoro!",
	ANNOUNCE_VOLCANO_ERUPT = "Il Ragnarok è giunto da me?!",
	ANNOUNCE_WAVE_BOOST = "Portami avanti!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Una bestia si nasconde sotto le onde...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Ho perso le tracce della bestia...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Non riesco a leggere queste acque agitate...",

	BATTLECRY =
	{
		GENERIC = "Il Valhalla aspetta!",
		PIG = "Avrò maiale per cena!",
		PREY = "Muori con coraggio, piccolo nemico!",
		SPIDER = "Ragno, assaggia la mia lancia!",
		SPIDER_WARRIOR = "Preparati ad essere ucciso!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Odino ti avrà prima o poi!",
		PIG = "Tornerò, pelle di maiale!",
		PREY = "Ti lascio andare per questa volta!",
		SPIDER = "Codardo gamboso.",
		SPIDER_WARRIOR = "Scappa mostro! Ritornerò.",
	},

	DESCRIBE =
	{		
		BIGFISHINGROD = "Ci intrappolerò la deliziosa carne di pesce.",
		BIGFOOT = "È una cosa completamente diversa!",
		COFFEEBOT = "La migliore macchina sotto il sole.",
		DEPLETED_GRASS_WATER = "È completamente disintegrato.",
		HOUNDFIRE = "Brucia di passione eterna!",
		INVENTORYGRAVE = "Ci vediamo nel Valhalla!",
		INVENTORYMOUND = "Ci vediamo nel Valhalla!",
		LIMPETS_COOKED = "Banchettiamo!",
		WOODLEGSBOAT = "Preferirei un drakkar.",
		WOODLEGSHAT = "Impallidisce paragonato al mio elmetto.",
		WOODLEGSSAIL = "Un lenzuolo spaventoso.",
		GLOMMER = "Un glommo maestoso.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Una meraviglia dei boschi.",
        	DEAD = "Una volta è stata una meraviglia dei boschi.",
        },
        GLOMMERWINGS = "Oh, guarda cosa ha lasciato il glommo per me.",
        GLOMMERFUEL = "Questa sbobba potrebbe essere utile.",
        BELL = "Preferiscono il suono di una lama contro l'altra.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Un curioso omaggio agli dèi.",
        	EMPTY = "Non è stato molto rispettoso da parte mia.",
        },

		WEBBERSKULL = "Ha combattuto con coraggio, ma la sua sepoltura non sarà quella di un vichingo.",
		WORMLIGHT = "Tesoro luminoso, non posso resistere!",
		WORMLIGHT_LESSER = "Brilla! Brilla con tutta la tua potenza!",
		WORM =
		{
		    PLANT = "Sento odore di trappola.",
		    DIRT = "Cosa c'è sotto quel terriccio?",
		    WORM = "Una bestia di serpente dal profondo!",
		},
		WORMLIGHT_PLANT = "Sento odore di trappola.",
		MOLE =
		{
			HELD = "Un amico per le mie tasche.",
			UNDERGROUND = "Chi è là sotto?",
			ABOVEGROUND = "Scava senza sosta.",
		},
		MOLEHILL = "Qualcosa di diabolico vive lì sotto.",
		MOLEHAT = "È meglio usare ogni parte dell'animale.",

		EEL = "Squisito, viscido pesce serpente.",
		EEL_COOKED = "Anguilla bollente!",
		UNAGI = "Non c'è bisogno che il cibo sia così sfarzoso.",
		EYETURRET = "L'occhio del dio laser mi fissa l'anima.",
		EYETURRET_ITEM = "Un antico bulbo oculare di protezione!",
		MINOTAURHORN = "Posso aggiungerlo al mio casco?",
		MINOTAURCHEST = "Lo scrigno delle conquiste!",
		THULECITE_PIECES = "Sembra un cereale soffiato splendente.",
		POND_ALGAE = "Una flora antica.",
		GREENSTAFF = "Potere verde arricciato.",
		POTTEDFERN = "Che cosa dovrei farci con una cosa simile?",

		THULECITE = "Questo materiale possiede una forza enorme!",
		ARMORRUINS = "Armatura adatta a Odin stesso!",
		RUINS_BAT = "La bacchetta del guerriero!",
		RUINSHAT = "Una corona, che combatte!",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Nothing stirs.",
			WARN = "It's starting...",
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			NOMAGIC = "The magic slumbers far from here.",
		},
		BISHOP_NIGHTMARE = "Attenzione alle sue esplosioni!",
		ROOK_NIGHTMARE = "Non mi spaventi!",
		KNIGHT_NIGHTMARE = "Non credo che cavalcherei quel cavallo.",
		MINOTAUR = "Che meraviglie. Combattiamo!",
		SPIDER_DROPPER = "Sei così subdolo!",
		NIGHTMARELIGHT = "Sfrutta i poteri oscuri da sotto.",
		NIGHTSTICK = "Un'arma degna di Thor.",
		GREENGEM = "Una pietra di smeraldo.",
		RELIC = "Old bits of a dwelling.",
		RUINS_RUBBLE = "I'm quite crafty. I could repair that.",
		MULTITOOL_AXE_PICKAXE = "Uno strumento del guerriero!",
		ORANGESTAFF = "Una materia dal movimento magico.",
		YELLOWAMULET = "Una stella, incastonata in un amuleto.",
		GREENAMULET = "Abilità artigiane di lavorazione dello smeraldo aumentate.",
		SLURPERPELT = "I do love furs.",	

		SLURPER = "Il nemico di pelliccia pensa che sia un cappello!",
		SLURPER_PELT = "Io amo le pellicce.",
		SLURPERPELT = "Io amo le pellicce.",
		ARMORSLURPER = "Soddisfa il morso della fame. Buona pelliccia.",
		ORANGEAMULET = "Riunirsi non è mai stato così facile.",
		YELLOWSTAFF = "Evoca le stelle!",
		YELLOWGEM = "Una bellezza gialla.",
		ORANGEGEM = "Una pietra arancione.",
		TELEBASE = 
		{
			VALID = "Prepare yourselves for the power of purple!",
			GEMS = "There's still gems missing.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "It's empty.",
		},
		STAFFLIGHT = "Ecco! Un regalo da Wotan!",
	
        ANCIENT_ALTAR = "Queste creazioni farebbero meglio ad essere buone.",

        ANCIENT_ALTAR_BROKEN = "Questo non funziona.",

        ANCIENT_STATUE = "Tesoro con un'aura misteriosa.",

        LICHEN = "Pianta insensata celeste.",
		CUTLICHEN = "L'ho preso. Ma non lo mangerò.",

		CAVE_BANANA = "Cibo delle scimmie.",
		CAVE_BANANA_COOKED = "Cibo per scimmie riscaldato.",
		CAVE_BANANA_TREE = "Un albero scimmia fragile.",
		ROCKY = "Potrebbe essere un compagno di combattimento valoroso.",
		
		COMPASS =
		{
			GENERIC= "La lettura non può essere verificata.",
			N = "Nord.",
			S = "Sud.",
			E = "Est.",
			W = "Ovest.",
			NE = "Nord-est.",
			SE = "Sud-est.",
			NW = "Nord-ovest.",
			SW = "Sud-ovest.",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "La magia si sta intensificando!",
			STEADY = "Il potere magico si mantiene costante.",
			WANING = "Sta iniziando a ritirarsi!",
			DAWN = "Non è rimasta quasi alcuna magia.",
			WARN = "Sta iniziando...",
			CALM = "Non si muove nulla.",
			NOMAGIC = "La magia sonnecchia lontano da qui.",
		},

		HOUNDSTOOTH="Un simbolo della mia conquista.",
		ARMORSNURTLESHELL="Una specie di scudo.",
		BAT="Carne scura alata.",
		BATBAT = "Winged spear!",
		BATWING="Come le ali del mio casco, solo più carnose.",
		BATWING_COOKED="Ala scura cotta.",
		BEDROLL_FURRY="Un letto di pelliccia lussuoso!",
		BUNNYMAN="Ti mangerò.",
		FLOWER_CAVE="E illuminò la notte, nell'ora più buia.",
		FLOWER_CAVE_DOUBLE="E illuminò la notte, nell'ora più buia.",
		FLOWER_CAVE_TRIPLE="E illuminò la notte, nell'ora più buia.",
		GUANO="Umm, sterco di ala scura.",
		LANTERN="Una lanterna per l'oscurità.",
		LIGHTBULB="Bagliore!",
		MANRABBIT_TAIL="Il trofeo peloso di una battaglia vinta.",
		MUSHTREE_TALL  ="Cos'è questa magia?",
		MUSHTREE_MEDIUM="Mi piace il suo splendore.",
		MUSHTREE_SMALL ="Non mi interessano i funghi.",
		RABBITHOUSE=
		{
			GENERIC = "Che cosa devo fare con una carota grande?",
			BURNT = "Che liberazione, una carota gigante.",
		},
		SLURTLE="Sei un angelo. Di cattiveria.",
		SLURTLE_SHELLPIECES="Sono distrutti per bene.",
		SLURTLEHAT="Un nuovo casco di battaglia per la mia collezione!",
		SLURTLEHOLE="Non dove sceglierei di appendere il mio casco.",
		SLURTLESLIME="Sì. Melma.",
		SNURTLE="Mi piace il suo casco.",
		SPIDER_HIDER="Ti fracasserò!",
		SPIDER_SPITTER="Questo è esuberante.",
		SPIDERHOLE="Ragnatele. Mai un buon segno.",
		STALAGMITE="Un masso della grotta.",
		STALAGMITE_FULL="Un masso della grotta.",
		STALAGMITE_LOW="Un masso della grotta.",
		STALAGMITE_MED="Un masso della grotta.",
		STALAGMITE_TALL="Una specie di roccia appuntita.",
		STALAGMITE_TALL_FULL="Una specie di roccia appuntita.",
		STALAGMITE_TALL_LOW="Una specie di roccia appuntita.",
		STALAGMITE_TALL_MED="Una specie di roccia appuntita.",

		TURF_CARPETFLOOR = "Assorbe il sangue della battaglia.",
		TURF_CHECKERFLOOR = "Pavimento di lusso.",
		TURF_DIRT = "Un pezzo del campo di battaglia.",
		TURF_FOREST = "Un pezzo del campo di battaglia.",
		TURF_GRASS = "Un pezzo del campo di battaglia.",
		TURF_MARSH = "Un pezzo del campo di battaglia.",
		TURF_ROAD = "La strada per la battaglia porta ovunque scelgo.",
		TURF_ROCKY = "Un pezzo del campo di battaglia.",
		TURF_SAVANNA = "Un pezzo del campo di battaglia.",
		TURF_WOODFLOOR = "Pavimenti di legno, un'ottima superficie per i combattimenti mortali.",

		TURF_CAVE="Un pezzo del campo di battaglia.",
		TURF_FUNGUS="Un pezzo del campo di battaglia.",
		TURF_SINKHOLE="Un pezzo del campo di battaglia.",
		TURF_UNDERROCK="Un pezzo del campo di battaglia.",
		TURF_MUD="Un pezzo del campo di battaglia.",

		POWCAKE = "Che cosa nel nome dell'unicorno è questo?",
        CAVE_ENTRANCE = 
        {
            GENERIC="Quali tesori si nascondono lì dietro?",
            OPEN = "Negli inferi!",
        },
        CAVE_EXIT = "Ritorno al cielo aperto!",
		MAXWELLPHONOGRAPH = "Una cantante meccanica.",
		BOOMERANG = "Per lanciare sui nemici!",
		PIGGUARD = "È pronto alla battaglia, lo posso confermare.",
		ADVENTURE_PORTAL = "L'avventura chiama.",
		AMULET = "È rosso e combattente. Proprio come me!",
		ANIMAL_TRACK = "Oh! Mi piace la buona caccia.",
		ARMORGRASS = "Protezione d'erba. Non durerà a lungo.",
		ARMORMARBLE = "Quasi impenetrabile!",
		ARMORWOOD = "Un giubbotto di albero prestato.",
		ARMOR_SANITY = "Forte, ma la mia mente vaga...",
		ASH =
		{
			GENERIC = "I resti delle fiamme.",
			REMAINS_GLOMMERFLOWER = "Il fiore deve rimanere nel suo mondo natale.",
			REMAINS_EYE_BONE = "L'ossocchio non poteva passare in questo mondo.",
			REMAINS_THINGIE = "È bruciato. Andato.",
		},
		AXE = "Tagliare e distruggere!",
		BABYBEEFALO = "Mini bestiola.",
		BACKPACK = "Un'armeria portatile.",
		BANDAGE = "Per guarire le mie ferite di battaglia.",
		BASALT = "Mille mortali non potrebbero sfondare questa pietra.",
		BATBAT = "Lancia alata!",
		BEARDHAIR = "Pelliccia dei pazzi.",
		BEDROLL_STRAW = "Uno strumento per i miei pisolini.",
		BEARGER = "Bestia o orso?",
		BEARGERVEST = "Sono impazzita!",
		ICEPACK = "Uno zaino della bestia.",
		BEARGER_FUR = "Ha combattuto con coraggio, ma ho reclamato la sua pelle.",
		BEE =
		{
			GENERIC = "Guerrieri piccini! Non so se mi piacciono.",
			HELD = "Facile ora!",
		},
		BEEBOX =
		{
			FULLHONEY = "È un tesoro di miele!",
			GENERIC = "Una dolce scatola di piccoli guerrieri.",
			NOHONEY = "Dov'è il miele?",
			SOMEHONEY = "Un po' di miele. È richiesta pazienza.",
			BURNT = "Il mio alveare è silente.",
		},
		BEEFALO =
		{
			FOLLOWER = "Vieni con me bestiola.",
			GENERIC = "Antiche bestie di lana!",
			NAKED = "Senti freddo senza la tua lana?",
			SLEEPING = "Sembra la zia Hilda.",
		},
		BEEFALOHAT = "Questo mi starà bene addosso, lo so.",
		BEEFALOWOOL = "Amo le cose di lana.",
		BEEHAT = "Il mio casco d'ape, naturalmente.",
		BEEHIVE = "Sempre ronzante, sempre tramante.",
		BEEMINE = "Sembra sospetto.",
		BEEMINE_MAXWELL = "Attento a dove metti i piedi!",
		BERRIES = "Frutta. Non mi piace.",
		BERRIES_COOKED = "Poltiglia rossa calda.",
		BERRYBUSH =
		{
			BARREN = "Dovrei metterci dello sterco sopra?",
			WITHERED = "Fa troppo caldo per crescere.",
			GENERIC = "Un cespuglio di frutta.",
			PICKED = "I frutti sono stati strappati.",
		},
		BIRDCAGE =
		{
			GENERIC = "Una casa per i miei corvi!",
			OCCUPIED = "Ti stai divertendo?",
			SLEEPING = "Sogni d'oro, amico corvo.",
		},
		BIRDTRAP = "Sono un'astuta acchiappa corvi!",
		BIRD_EGG = "Ovoso.",
		BIRD_EGG_COOKED = "Uovo caldo.",
		BISHOP = "Questo ha bisogno di uno schiaffone.",
		BLOWDART_FIRE = "Come il respiro di un drago.",
		BLOWDART_SLEEP = "Buonanotte ai miei nemici.",
		BLOWDART_PIPE = "Armi proiettile!",
		BLUEAMULET = "Gioiello freddo.",
		BLUEGEM = "Un gelido zaffiro blu.",
		BLUEPRINT = "Oh, una mappa! No, aspetta. È sbagliata.",
		BELL_BLUEPRINT = "Oh, una mappa! No, aspetta. È sbagliata.",
		BLUE_CAP = "Umm, uno blu.",
		BLUE_CAP_COOKED = "Ancora non lo voglio mangiare.",
		BLUE_MUSHROOM =
		{
			GENERIC = "È muffa, davvero.",
			INGROUND = "Bene, si nasconde.",
			PICKED = "Spero che non cresca di nuovo.",
		},
		BOARDS = "Tronchi del nonno.",
		BOAT = "È così che sono arrivato qua?",
		BONESHARD = "Pezzi dei miei nemici.",
		BONESTEW = "Delizioso!",
		BUGNET = "Per afferrare gli insetti in aria.",
		BUSHHAT = "Per la caccia.",
		BUTTER = "Burro. Potrebbe essere buono sulla bistecca?",
		BUTTERFLY =
		{
			GENERIC = "È piacevole.",
			HELD = "Preso!",
		},
		BUTTERFLYMUFFIN = "Muffin o non muffin.",
		BUTTERFLYWINGS = "Un bel souvenir.",
		BUZZARD = "Io e te, banchettiamo insieme con la carne.",
		CACTUS = 
		{
			GENERIC = "Ha un'armatura ammirevole.",
			PICKED = "Tornerà.",
		},
		CACTUS_MEAT_COOKED = "Carne di pianta spinosa tostata.",
		CACTUS_MEAT = "Carne di pianta che punge.",
		CACTUS_FLOWER = "Bellezza che nasce dalle asperità.",
		COLDFIRE =
		{
			EMBERS = "Il fuoco è quasi morto.",
			GENERIC = "Una magra consolazione.",
			HIGH = "Ruggiti di fuoco!",
			LOW = "Il fuoco sta morendo lentamente.",
			NORMAL = "Una magra consolazione.",
			OUT = "E la luce tremola.",
		},
		CAMPFIRE =
		{
			EMBERS = "Il fuoco è quasi morto.",
			GENERIC = "Fuoco caldo, Wigfrid calda.",
			HIGH = "Ruggiti di fuoco!",
			LOW = "Il fuoco sta morendo lentamente.",
			NORMAL = "Fuoco caldo, Wigfrid calda.",
			OUT = "E la luce tremola.",
		},
		CANE = "Cambia il \"cammino\" in \"trotto\".",
		CATCOON = "Oh! Carne tenera con pelliccia.", 
		CATCOONDEN = 
		{
			GENERIC = "La carne tenera vive lì.",
			EMPTY = "Ha combattuto coraggiosamente. Ahimè, se n'è andata.",
		},
		CATCOONHAT = "Un cappuccio peloso! Ti benedico, carne tenera.",
		COONTAIL = "È la coda della carne tenera.",
		CARROT = "Dove si trova la proteina?",
		CARROT_COOKED = "Carote tristi cotte.",
		CARROT_PLANTED = "Una piccola radice.",
		CARROT_SEEDS = "Piccoli pezzetti di natura.",
		CAVE_FERN = "Fogliame dall'età oscura.",
		CHARCOAL = "Bottino di Loge, il semidio.",
        CHESSJUNK1 = "È solo un mucchio di guerrieri caduti.",
        CHESSJUNK2 = "Altri guerrieri meccanici morti.",
        CHESSJUNK3 = "Qualcuno dovrebbe davvero ripulire questo posto.",
		CHESTER = "Non ti preoccupare, non lo mangerò.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Chi sei?",
			WAITING = "Il bulbo oculare è stanco.",
		},
		COOKEDMANDRAKE = "È sicuramente morta.",
		COOKEDMEAT = "Caaaarne!",
		COOKEDMONSTERMEAT = "Bistecca di bestia.",
		COOKEDSMALLMEAT = "Gnam, gnam, spuntini di carne.",
		COOKPOT =
		{
			COOKING_LONG = "Potrei fare qualcosa mentre aspetto.",
			COOKING_SHORT = "Non dovrebbe mancare molto adesso!",
			DONE = "Cosa abbiamo qui?",
			EMPTY = "Niente lì dentro.",
			BURNT = "Il fuoco ha regnato supremo.",
		},
		CORN = "Una spada di verdura!",
		CORN_COOKED = "I popcorn hanno un buon odore.",
		CORN_SEEDS = "Piccoli pezzetti di natura.",
		CROW =
		{
			GENERIC = "Amico corvo!",
			HELD = "Di nuovo insieme.",
		},
		CUTGRASS = "La risorsa più elementare di un'artigiana.",
		CUTREEDS = "Ho ripulito tutti gli insetti! Poi li ho mangiati.",
		CUTSTONE = "Pietra solida!",
		DEADLYFEAST = "Il piatto più potente.",
		DEERCLOPS = "I raggi traspariranno attraverso la mia lancia e ti caveranno l'occhio!",
		DEERCLOPS_EYEBALL = "Umm, devo mangiarla?",
		EYEBRELLAHAT = "Per non prendere pioggia negli occhi!",
		DEPLETED_GRASS =
		{
			GENERIC = "È probabilmente un ciuffo d'erba.",
		},
		DEVTOOL = "Odora di pancetta!",
		DEVTOOL_NODEV = "Non sono abbastanza forte per impugnarla.",
		DIRTPILE = "Una collinetta di terra.",
		DIVININGROD =
		{
			COLD = "Tutto tace.",
			GENERIC = "Un cane da caccia meccanico. Per la caccia.",
			HOT = "Suona le corna! Siamo arrivati!",
			WARM = "Abbiamo la traccia!",
			WARMER = "Il segugio è eccitato. Ci stiamo avvicinando.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Che rovine criptiche.",
			READY = "Sembra che mi manchi un pezzo...",
			UNLOCKED = "Pronta! La saga continua!",
		},
		DIVININGRODSTART = "Questa spada misteriosa si sente importante.",
		DRAGONFLY = "Ah drago! Finalmente ci incontriamo!",
		ARMORDRAGONFLY = "Eccellente armatura per il calore della battaglia.",
		DRAGON_SCALES = "Squame mistiche.",
		DRAGONFLYCHEST = "Questa cassa è degna delle mie armi.",
		LAVASPIT = 
		{
			HOT = "Le tue pozze di fuoco non mi fanno paura!",
			COOL = "Non fa più molto spavento adesso, vero?",
		},
		DRAGONFRUIT = "È molto lussuoso.",
		DRAGONFRUIT_COOKED = "Frutta alla griglia.",
		DRAGONFRUIT_SEEDS = "Piccoli pezzetti di natura.",
		DRAGONPIE = "Perché questo non è un pasticcio di carne? Carne, caaaarne!",
		DRUMSTICK = "Gamba di bestiola, nella mia pancia.",
		DRUMSTICK_COOKED = "Carne boooooollente!",
		DUG_BERRYBUSH = "Credo che lo restituirò alla dea della terra.",
		DUG_GRASS = "Credo che lo restituirò alla dea della terra.",
		DUG_MARSH_BUSH = "Credo che lo restituirò alla dea della terra.",
		DUG_SAPLING = "Credo che lo restituirò alla dea della terra.",
		DURIAN = "Odora come i miei stivali da battaglia.",
		DURIAN_COOKED = "Perché ho cucinato di nuovo questo?",
		DURIAN_SEEDS = "Piccoli pezzetti di natura.",
		EARMUFFSHAT = "Sì, più pratico!",
		EGGPLANT = "Viola e bulbosa.",
		EGGPLANT_COOKED = "Cibo per i deboli.",
		EGGPLANT_SEEDS = "Piccoli pezzetti di natura.",
		DECIDUOUSTREE = 
		{
			BURNING = "Il legno è in fiamme!",
			BURNT = "Loge lo ha preso.",
			CHOPPED = "Mozzato dal guerriero del bosco!",
			POISON = "Devo lavorare un po' di più per questa legna da ardere.",
			GENERIC = "Futura legna da ardere!",
		},
		ACORN = 
		{
		    GENERIC = "C'è un albero nascosto all'interno.",
		    PLANTED = "Crescete forti, giovani rametti!",
		},
		ACORN_COOKED = "Ho cucinato il giovane albero.",
		BIRCHNUTDRAKE = "Un giovane albero guerriero!",
		EVERGREEN =
		{
			BURNING = "Il legno è in fiamme!",
			BURNT = "Loge lo ha preso.",
			CHOPPED = "Mozzato dal guerriero del bosco!",
			GENERIC = "Nel bosco mi sento a casa.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Il legno è in fiamme!",
			BURNT = "Loge lo ha preso.",
			CHOPPED = "Mozzato dal guerriero del bosco!",
			GENERIC = "Un buon albero robusto.",
		},
		EYEPLANT = "Non puntare il tuo bulbo oculare verso di me, fogliame!",
		FARMPLOT =
		{
			GENERIC = "Se non posso far crescere la carne, qual è il punto?",
			GROWING = "Stanno crescendo più forti.",
			NEEDSFERTILIZER = "Vuole un banchetto di sterco.",
			BURNT = "Così imparate a non coltivare la carne!",
		},
		FEATHERHAT = "È un po' appariscente per la battaglia.",
		FEATHER_CROW = "Un simbolo dai corvi!",
		FEATHER_ROBIN = "Rosso come i miei capelli.",
		FEATHER_ROBIN_WINTER = "Piuma invernale.",
		FEM_PUPPET = "Sembra infelice sul suo trono.",
		FIREFLIES =
		{
			GENERIC = "Lumini da favola accesi!",
			HELD = "Mantengo la luce!",
		},
		FIREHOUND = "Quella fiammata non ha pietà.",
		FIREPIT =
		{
			EMBERS = "Il fuoco è quasi morto.",
			GENERIC = "Fuoco caldo, Wigfrid calda.",
			HIGH = "Ruggiti di fuoco!",
			LOW = "Il fuoco sta morendo lentamente.",
			NORMAL = "Fuoco caldo, Wigfrid calda.",
			OUT = "E la luce tremola.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Il fuoco è quasi morto.",
			GENERIC = "Una magra consolazione.",
			HIGH = "Ruggiti di fuoco!",
			LOW = "Il fuoco sta morendo lentamente.",
			NORMAL = "Una magra consolazione.",
			OUT = "E la luce tremola.",
		},
		FIRESTAFF = "Wigfrid! Maestra del fuoco!",
		FIRESUPPRESSOR = 
		{	
			ON = "Catapulta pronta alla battaglia!",
			OFF = "È ora di riposare, guerriero lanciatore.",
			LOWFUEL = "La catapulta cresce debole e stanca.",
		},

		FISH = "Carne del mare!",
		FISHINGROD = "Sono una pescatrice spietata.",
		FISHSTICKS = "Spiedini di carne di mare.",
		FISHTACOS = "Pesce in una coperta!",
		FISH_MED = "Riposa tranquillamente nel Valhalla.",
		FISH_MED_COOKED = "Gioia!",
		FISH_COOKED = "Gioia!",
		FLINT = "Vitale per la costruzione di lancia.",
		FLOWER = "Un fiore da Freya.",
		FLOWERHAT = "Inutile per la lotta, bello per la mia testa.",
		FLOWER_EVIL = "Un terribile male affligge questa flora.",
		FOLIAGE = "Una collezione di felci.",
		FOOTBALLHAT = "Il fondoschiena di un maiale ha creato il mio casco.",
		FROG =
		{
			DEAD = "Sei un po' viscido per il Valhalla.",
			GENERIC = "Mi piacerebbero degli stivali di rana qualche volta.",
			SLEEPING = "Dorme.",
		},
		FROGGLEBUNWICH = "Che sballo!",
		FROGLEGS = "Pieno di proteina gommosa!",
		FROGLEGS_COOKED = "Mi piace quando riesco a vedere le ossa sporgenti.",
		FRUITMEDLEY = "Ugh! Metterlo in una tazza non mi inganna.",
		GEARS = "Questi dovrebbero stare bene attaccati al mio casco.",
		GHOST = "Uno spirito intrappolato tra due mondi.",
		GOLDENAXE = "Uno strumento d'oro!",
		GOLDENPICKAXE = "Oro per oro.",
		GOLDENPITCHFORK = "Perché mai ho fatto un forcone così piacevole?",
		GOLDENSHOVEL = "Scavando come un re!",
		GOLDNUGGET = "Sono soddisfatta di questo pezzo d'oro.",

		GRASS =
		{
			BARREN = "La vita lo ha lasciato.",
			WITHERED = "Il calore ha sconfitto questa pianta.",
			BURNING = "Loge vi osserva!",
			GENERIC = "Potrebbe essere utile.",
			PICKED = "È caduto sotto la mia potenza.",
		},
		GREEN_CAP = "Terribile!",
		GREEN_CAP_COOKED = "Che sia carbonizzato dalle fiamme o no, non toccherà le mie labbra!",
		GREEN_MUSHROOM =
		{
			GENERIC = "È cresciuto!",
			INGROUND = "Nasconditi, codardo.",
			PICKED = "Vedo spore di funghi.",
		},
		GUNPOWDER = "Quanta energia!",
		HAMBAT = "Un'arma adatta per le grandi sale da pranzo!",
		HAMMER = "Più adatto al lavoro che alla battaglia.",
		HEALINGSALVE = "Riempimi di vita!",
		HEATROCK =
		{
			FROZEN = "Dente freddo mi ha morso!",
			COLD = "La pietra ha assunto freddo!",
			GENERIC = "Una pietra di grande utilità!",
			WARM = "La pietra ha assunto calore!",
			HOT = "Loge sarebbe orgoglioso.",
		},
		HOMESIGN = 
		{
			GENERIC = "Un segnale posizionato benissimo.",
			UNWRITTEN = "Scriverò un racconto di trionfo!",
			BURNT = "Segni di una battaglia del passato.",
		},
		HONEY = "Appiccicoso e rozzo.",
		HONEYCOMB = "Non sarebbe un granché come pettine.",
		HONEYHAM = "Un banchetto abbondante!",
		HONEYNUGGETS = "Un banchetto sostanzioso a base di torrone!",
		HORN = "Quanto mi mancava un combattimento.",
		HOUND = "Uova di Fenrir!",
		HOUNDBONE = "Un nemico caduto.",
		HOUNDMOUND = "Questi segugi sono dei veri guerrieri.",
		ICEBOX = "L'inverno si aggira all'interno!",
		ICEHAT = "Un pezzo di freddo.",
		ICEHOUND = "Denti di gelo!",
		INSANITYROCK =
		{
			ACTIVE = "Uau!",
			INACTIVE = "Non mi aspetto niente da quella roccia.",
		},
		JAMMYPRESERVES = "Appiccicoso e rozzo.",
		KABOBS = "Carne ammassata su un bastone! Sì!",
		KILLERBEE =
		{
			GENERIC = "Uno sfidante!",
			HELD = "Un nemico conquistato.",
		},
		KNIGHT = "Presagio di battaglia!",

		KOALEFANT_SUMMER = "Cara creatura... ti sto per mangiare.",
		KOALEFANT_WINTER = "Povera ignara bestia di carne.",
		KRAMPUS = "Non mi spaventi, capra!",
		KRAMPUS_SACK = "Posso farci entrare tutto!",
		LEIF = "Quello è un antico essere del bosco.",
		LEIF_SPARSE = "Quello è un antico essere del bosco.",
		LIGHTNING_ROD =
		{
			CHARGED = "Oh, grande fulmine!",
			GENERIC = "Donner, porta con te i fulmini!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "Posso chiamarti unicorno?",
			CHARGED = "Il fulmine ha fatto di te un guerriero unicorno!",
		},
		LIGHTNINGGOATHORN = "Questo potrebbe infliggere un colpo duraturo.",
		GOATMILK = "Questo è un latte potente.",
		LITTLE_WALRUS = "Un'apparizione della foca dentata malevola.",
		LIVINGLOG = "Bruciare tale magia sembrerebbe uno spreco.",
		LOCKEDWES = "Ti salverò silenzioso mortale!",
		LOG =
		{
			BURNING = "Tronco fiammeggiante!",
			GENERIC = "Il legno è sempre di valore.",
		},
		LUREPLANT = "Finalmente! Un ortaggio utile.",
		LUREPLANTBULB = "Potrò essere un'allevatrice di carne dopo tutto!",
		MALE_PUPPET = "Sembra infelice sul suo trono.",
		MANDRAKE =
		{
			DEAD = "Il cadavere della rapa gialla conserva ancora la sua magia.",
			GENERIC = "Una rapa gialla!",
			PICKED = "Vuole solo andare in una saga di rape.",
		},
		MANDRAKESOUP = "Uno stufato di magia!",
		MANDRAKE_COOKED = "Rutabaga alla griglia.",
		MARBLE = "La pietra del guerriero!",
		MARBLEPILLAR = "Adatto a un palazzo!",
		MARBLETREE = "Nemmeno i venti possono abbattere questo albero.",
		MARSH_BUSH =
		{
			BURNING = "Tronco rovente!",
			GENERIC = "Un arbusto di guardia.",
			PICKED = "Che seccatura.",
		},
		MARSH_PLANT = "Fogliame di stagno.",
		MARSH_TREE =
		{
			BURNING = "È in fiamme!",
			BURNT = "Bruciato.",
			CHOPPED = "La mia ascia di battaglia vince sempre.",
			GENERIC = "Un albero del guerriero.",
		},
		MAXWELL = "Argh! È quello l'antagonista della mia saga?!",
		MAXWELLHEAD = "Posso vedere nei suoi pori.",
		MAXWELLLIGHT = "La magia nera vive qui.",
		MAXWELLLOCK = "Devo sbloccarlo?",
		MAXWELLTHRONE = "Preferisco vagare in libertà, io e il mio unicorno.",
		MEAT = "Il vero frutto della terra!",
		MEATBALLS = "Palline da banchetto.",
		MEATRACK =
		{
			DONE = "Mangiamo!",
			DRYING = "È stata preparata proprio come piace a me.",
			DRYINGINRAIN = "Tutta questa pioggia non è di aiuto.",
			GENERIC = "Ah! Una griglia sospesa per le mie carni!",
			BURNT = "Davvero un peccato.",
		},
		MEAT_DRIED = "Eccellenti scorte di battaglia.",
		MERM = "Muori bestia pesce molliccia!",
		MERMHEAD = 
		{
			GENERIC = "Potevo odorarlo da laggiù!",
			BURNT = "Decapitato. Bruciato. Puzzolente.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Questa dimora è fatta di pesce?",
			BURNT = "Non mi mancherà.",
		},
		MINERHAT = "Un casco illuminato! Per l'oscurità.",
		MONKEY = "Non mi fido di lui.",
		MONKEYBARREL = "Che orrori dimorano lì dietro?",
		MONSTERLASAGNA = "Mostro in casseruola.",
		FLOWERSALAD = "Le foglie sono per gli animali. Gli animali sono fatti per essere mangiati.",
        ICECREAM = "Fa male ai miei denti.",
        WATERMELONICLE = "Non puoi ingannarmi nascondendoti nella frutta congelata, bastone.",
        TRAILMIX = "La carne di una noce non è una vera carne.",
        HOTCHILI = "Una prova della mia forza di volontà.",
        GUACAMOLE = "Gnam, cremoso!",
		MONSTERMEAT = "Carne delle bestie scure.",
		MONSTERMEAT_DRIED = "Tutto seccato.",
		MOOSE = "Mi sarebbe piaciuto cavalcarlo in battaglia.",
		MOOSEEGG = "C'è qualcosa all'interno che rimbalza.",
		MOSSLING = "Non sei abbastanza grande da essere il mio destriero.",
		FEATHERFAN = "I lussi dell'accampamento, in movimento.",
		TROPICALFAN = "I lussi dell'accampamento, in movimento.",
		GOOSE_FEATHER = "Una combattente merita un morbido letto di foglie.",
		STAFF_TORNADO = "Una tempesta di dolore.",
		MOSQUITO =
		{
			GENERIC = "Ugh! Queste cose sono inutili!",
			HELD = "Calmati, furia del demone!",
		},
		MOSQUITOSACK = "Il sangue mi renderà forte.",
		MOUND =
		{
			DUG = "Volevo il bottino!",
			GENERIC = "Ci sono tesori sotto le lapidi?",
		},
		NIGHTLIGHT = "Sono più a mio agio intorno al mio fuoco.",
		NIGHTMAREFUEL = "Il combustibile delle tenebre!",
		NIGHTSWORD = "Ci vuole un guerriero coraggioso per brandire questa spada.",
		NITRE = "Contiene componenti esplosive.",
		ONEMANBAND = "Canta con me! Siamo i custodi di Asgard!",
		PANDORASCHEST = "Contiene un mistero.",
		PANFLUTE = "Preferisco affrontare i miei nemici da svegli.",
		PAPYRUS = "Questo tramanderà la documentazione della mia saga.",
		PENGUIN = "Pennuti del mare, vengono da lontano.",
		PERD = "Non puoi correre per sempre!",
		PEROGIES = "Tasche di carne.",
		PETALS = "Grazie per questo dono, Froh!",
		PETALS_EVIL = "Questi non sono stati fatti da Froh.",
		PICKAXE = "Posso usarlo per ottenere una lancia preziosa e materiali per il casco.",
		PIGGYBACK = "Il maiale è morto con onore, poi mi ha dato questo pacco.",
		PIGHEAD = 
		{	
			GENERIC = "Questa è ferocia.",
			BURNT = "Di solito mi piace un buon arrosto, ma questo ha qualcosa che non va.",
		},
		PIGHOUSE =
		{
			FULL = "Vieni fuori e vai alla guerra con me!",
			GENERIC = "Non credevo che i maiali potessero costruire case.",
			LIGHTSOUT = "Non hai fame di battaglia, maiale?",
			BURNT = "Loge non ha riso di voi oggi.",
		},
		PIGKING = "È s-uino?",
		PIGMAN =
		{
			DEAD = "È morto con onore.",
			FOLLOWER = "Cavalchiamo verso la battaglia!",
			GENERIC = "Combatterai al mio fianco, maiale?",
			GUARD = "Quel maiale sembra coraggioso.",
			WEREPIG = "È stata contaminata da Fenrir.",
		},
		PIGSKIN = "La pelle di una creatura di maiale.",
		PIGTORCH = "Questi maiali venerano Loge?",
		PINECONE = 
		{
		    GENERIC = "Questo albero bambino è ben protetto da un'armatura spinosa.",
		    PLANTED = "Ha perso la sua armatura. Cresci, albero bambino!",
		},
		PITCHFORK = "Un'arma per gli agricoltori.",
		PLANTMEAT = "Suppongo che sia abbastanza vicino.",
		PLANTMEAT_COOKED = "Ancora verde, ma andrà bene.",
		PLANT_NORMAL =
		{
			GENERIC = "Una pianta.",
			GROWING = "Sono una donna combattente, non una contadina!",
			READY = "Ah, verdure. Non sono sicura di quello che mi aspettavo...",
			WITHERED = "Battuta dal sole.",
		},
		POMEGRANATE = "Carne fruttata.",
		POMEGRANATE_COOKED = "Polpa di frutta scottata.",
		POMEGRANATE_SEEDS = "Piccoli pezzetti di natura.",
		POND = "Qualcosa si nasconde nel profondo.",
		POOP = "Se solo potessi usarlo come camuffamento dai predatori.",
		FERTILIZER = "Il suo fetore potrebbe resuscitare i morti.",
		PUMPKIN = "Potrebbe essere un buon randello, almeno.",
		PUMPKINCOOKIE = "Cotto all'estremo.",
		PUMPKIN_COOKED = "Poltiglia arancione ultra bollente.",
		PUMPKIN_LANTERN = "Vuoi combattere, verdura?",
		PUMPKIN_SEEDS = "Piccoli pezzetti di natura.",
		PURPLEAMULET = "Un amuleto di poteri oscuri.",
		PURPLEGEM = "È nuvoloso con una misteriosa energia.",
		RABBIT =
		{
			GENERIC = "Saltami in bocca!",
			HELD = "Non c'è scappatoia!",
		},
		RABBITHOLE = 
		{
			GENERIC = "Lo spettacolo abbia inizio, conigli!",
			SPRING = "Deve essere l'intervallo per i conigli.",
		},
		RAINOMETER = 
		{	
			GENERIC = "Preannuncia l'arrivo della pioggia.",
			BURNT = "I suoi giorni di profezia sono finiti.",
		},
		RAINCOAT = "Armatura per la pioggia.",
		RAINHAT = "Combatteremo sotto la pioggia.",
		RATATOUILLE = "Un mucchio di verdure. No grazie.",
		RAZOR = "Una lama piccola, ma pur sempre una lama.",
		REDGEM = "È caldissimo al tatto.",
		RED_CAP = "Umami o no, non lo voglio.",
		RED_CAP_COOKED = "Non lo mangerò, ma è stato divertente metterlo nel fuoco.",
		RED_MUSHROOM =
		{
			GENERIC = "Almeno ha un bel colorito.",
			INGROUND = "E resta laggiù!",
			PICKED = "Che liberazione.",
		},
		REEDS =
		{
			BURNING = "Ci vediamo ad Asgard, canne!",
			GENERIC = "Quelle sono canne resistenti.",
			PICKED = "Tagliate nella loro perfezione.",
		},
        RELIC = 
        {
            GENERIC = "Adatta ad Asgard.",
            BROKEN = "È stato ridotto in mille pezzi.",
        },
        RUINS_RUBBLE = "I suoi giorni non sono ancora compiuti.",
        RUBBLE = "Un mucchio di rocce antiche.",
		RESEARCHLAB = 
		{	
			GENERIC = "Preferisco la battaglia alla scienza.",
			BURNT = "Cenere alla cenere.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Forse la scienza può migliorare la mia abilità di combattimento.",
			BURNT = "Polvere alla polvere.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Una cosa mistica.",
			BURNT = "Il suo strano potere non lo ha protetto dal fuoco.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "È una macchina assurda che produce carne.",
			BURNT = "Non ci sarà più carne da qua!",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Non so perché l'ho fatto.",
			BURNT = "Valhalla, sto arrivando!",
		},
		RESURRECTIONSTONE = "Mi trattiene dal Valhalla.",
		ROBIN =
		{
			GENERIC = "Rosso come il sangue.",
			HELD = "Preferisco i tuoi fratelli neri.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Questo pennuto conosce il freddo.",
			HELD = "Che piume morbide.",
		},
		ROBOT_PUPPET = "Un prigioniero!",
		ROCK_LIGHT =
		{
			GENERIC = "La crosta della lava è stabile.",
			OUT = "Sembra delicato.",
			LOW = "La crosta della lava si sta riformando.",
			NORMAL = "Bella luce!",
		},
		ROCK = "Fracassa!",
		ROCK_ICE = 
		{
			GENERIC = "Una montagna congelata in miniatura.",
			MELTED = "Povero ghiacciaio!",
		},
		ROCK_ICE_MELTED = "Povero ghiacciaio!",
		ICE = "Mi ricorda casa.",
		ROCKS = "Delle rocce piuttosto normali.",
        ROOK = "Attaaaaacco!",
		ROPE = "Abbastanza forte per legare le vele del mio drakkar.",
		ROTTENEGG = "Rovinato per mangiare, ma idoneo alla battaglia.",
		SANITYROCK =
		{
			ACTIVE = "Non credo di poter fare meglio di questa roccia in combattimento.",
			INACTIVE = "Roccia intelligente, non puoi sorprendere un guerriero!",
		},
		SAPLING =
		{
			BURNING = "No! Le mie lance!",
			WITHERED = "Si è seccato col calore.",
			GENERIC = "Ne farò una lancia.",
			PICKED = "Ho percosso il piccolo albero!",
		},
		SEEDS = "Piccoli pezzetti di natura.",
		SEEDS_COOKED = "Piccoli pezzetti di natura, cucinati fino alla morte.",
		SEWING_KIT = "Non sono una sarta, ma le riparazioni a volte sono necessarie.",
		SHOVEL = "Preferirei un funerale da barca, benché questa avrebbe la sua utilità.",
		SILK = "Utile per legare e per ricordare le vittorie del passato.",
		SKELETON = "Riposa tranquillamente nel Valhalla.",
		SKELETON_PLAYER = "Questa lotta non è ancora finita.",
		SKULLCHEST = "Ah, è stata una bella battaglia.",
		SMALLBIRD =
		{
			GENERIC = "Non sei ancora feroce, pennuto.",
			HUNGRY = "Devi mangiare per crescere forte.",
			STARVING = "Il piccolo pennuto sembra affamato.",
		},
		SMALLMEAT = "Un bello spuntino carnoso.",
		SMALLMEAT_DRIED = "Una piccola scorta per una lunga campagna.",
		SPEAR = "Non è la mia lancia preferita, ma andrà bene.",
		SPIDER =
		{
			DEAD = "Abbattuto dalla mia lancia, come tanti prima.",
			GENERIC = "Otto gambe e non c'è partita contro di me!",
			SLEEPING = "Gli permetterò una lotta leale aspettando che si svegli.",
		},
		SPIDERDEN = "Schiacciali alla fonte!",
		SPIDEREGGSACK = "Li potrei schiacciare, ma mi perderei altre battaglie.",
		SPIDERGLAND = "Strappato dal ventre di un ragno assassinato.",
		SPIDERHAT = "Un modo perfetto per infiltrarsi nel campo nemico.",
		SPIDERQUEEN = "Infine, una vera prova delle mie capacità.",
		SPIDER_WARRIOR =
		{
			DEAD = "Vittoria per Wigfrid ancora una volta!",
			GENERIC = "Il campione dei ragni. Alla battaglia!",
			SLEEPING = "È vile attaccare un nemico addormentato.",
		},
		SPOILED_FOOD = "L'età ha fatto diventare questo cibo volgare, non saggio.",
		STATUEHARP = "Deve essere Gunnar. I serpenti gli hanno preso la testa.",
		STATUEMAXWELL = "Vergognati, demone!",
		STINGER = "La spada sul retro di un'ape.",
		STRAWHAT = "Un cappello per rinfrescarsi dopo una battaglia turbolenta.",
		STUFFEDEGGPLANT = "Riempire la verdura non la fa diventare carne.",
		SUNKBOAT = "Non mi meraviglia che sia affondata. Non è un drakkar.",
		SWEATERVEST = "È un bel giubbotto, ma non offre alcuna protezione.",
		REFLECTIVEVEST = "Ah! Il sole non è guerriero se non può penetrare questo.",
		HAWAIIANSHIRT = "I fiori non possono fermare una lancia.",
		TAFFY = "La storia di questo toffee sarà raccontata per lungo tempo.",
		TALLBIRD = "Uno spaventoso pennuto! Ma io non ho paura.",
		TALLBIRDEGG = "Crescerà in un nemico formidabile.",
		TALLBIRDEGG_COOKED = "Era tra me e te, pennuto.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Questo uovo non sopravvivrebbe un inverno scandinavo.",
			GENERIC = "Combatti per una via d'uscita, pennuto!",
			HOT = "Dato alla luce dalla fiamma! A meno che non sia cotto a morte.",
			LONG = "Ci vorrà del tempo prima che nasca questo pennuto.",
			SHORT = "Presto si sveglierà in questo mondo.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Un guerriero piumato si annida all'interno.",
			PICKED = "Presto nascerà un giovane pennuto da guerra.",
		},
		TEENBIRD =
		{
			GENERIC = "Non sei ancora pronto alla battaglia, pennuto.",
			HUNGRY = "Spero che ti piacciano le verdure... la carne è per me.",
			STARVING = "Andare in battaglia con me è una tua scelta, pennuto.",
		},
		TELEBASE =
		{
			VALID = "Sfrutterà la mia impressionante velocità.",
			GEMS = "Richiede delle gemme viola.",
		},
		GEMSOCKET = 
		{
			VALID = "Lo spettacolo abbia inizio!",
			GEMS = "Gli manca la sua gemma.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Ad Asgard!",
			GENERIC = "Un ponte verso un altro mondo.",
			LOCKED = "Il ponte è ancora instabile.",
			PARTIAL = "Il ponte è incompleto.",
		},
		TELEPORTATO_BOX = "Forse detiene il segreto delle terre di Bifrost.",
		TELEPORTATO_CRANK = "Una manovella robusta.",
		TELEPORTATO_POTATO = "Nessuna decenza. Non si tratta nemmeno di carne di metallo.",
		TELEPORTATO_RING = "Sembra simile al Bifrost.",
		TELESTAFF = "Passo attraverso l'aria e il mare!",
		TENT = 
		{
			GENERIC = "Dormi questa notte, e preparati alla battaglia per il domani.",
			BURNT = "È stata rasa al suolo.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Un posto per poggiare la mia testa stanca dalla battaglia.",
			BURNT = "È stata rasa al suolo.",
		},
		TENTACLE = "Sembra feroce. Nella mischia!",
		TENTACLESPIKE = "Appiccicoso, ma pericoloso. Mi piace.",
		TENTACLESPOTS = "Una pellaccia.",
		TENTACLE_PILLAR = "Un nemico con tentacoli torreggianti.",
		TENTACLE_PILLAR_ARM = "Una rozza appendice afferrante.",
		TENTACLE_GARDEN = "Ficcherò la mia lancia in quella massa di tentacoli!",
		TOPHAT = "Non si abbina con il mio costume.",
		TORCH = "Perfetto per un assalto notturno.",
		TRANSISTOR = "Una meraviglia della scienza.",
		TRAP = "Una trappola ben costruita. Pranzerò sicuramente.",
		TRAP_TEETH = "Una trappola infida.",
		TRAP_TEETH_MAXWELL = "Un'eccellente mazza ferrata sprecata, sepolta nella terra.",
		TREASURECHEST = 
		{
			GENERIC = "Un luogo per conservare il mio casco e la mia lancia mentre riposo.",
			BURNT = "Le sue mura furono abbattute dal fuoco.",
		},
		TREASURECHEST_TRAP = "Sono sempre pronto.",
		TREECLUMP = "Un vicolo cieco! Devo rimanere a combattere.",
		TRINKET_1 = "I giocattoli non interessano a una grande guerriera come me.",
		TRINKET_10 = "Un simbolo di vittoria.",
		TRINKET_11 = "Un guerriero racchiuso in una bella armatura.",
		TRINKET_12 = "Rasato da un mostro tremendo.",
		TRINKET_2 = "Accompagnamento per la canzone dei miei trionfi.",
		TRINKET_3 = "Perfino la mia lancia non può sciogliere questo nodo.",
		TRINKET_4 = "Un ometto particolare.",
		TRINKET_5 = "Mi porterà a Asgard?",
		TRINKET_6 = "Tecnologia inutile.",
		TRINKET_7 = "Non c'è tempo per i giochi! La battaglia è a portata di mano!",
		TRINKET_8 = "Sarebbe un'arma accettabile in casi estremi.",
		TRINKET_9 = "Nessuna armatura decente può essere fatta con questi.",
		TRUNKVEST_SUMMER = "Non basterà nelle gelide lande.",
		TRUNKVEST_WINTER = "La calda pelle di una creatura sconfitta. Un capo raffinato.",
		TRUNK_COOKED = "Una succosa ricompensa dopo una dura battaglia.",
		TRUNK_SUMMER = "Una proboscide potente di una bestia senza pelo morta.",
		TRUNK_WINTER = "Una proboscide potente di una bestia pelosa morta.",
		TUMBLEWEED = "Scappa, codardo rimbalzante!",
		TURKEYDINNER = "Un vero banchetto.",
		TWIGS = "Buono per la fabbricazione di lance.",
		UMBRELLA = "Protezione dalla pioggia fatta dal trofeo di una battuta di caccia.",
		GRASS_UMBRELLA = "Non mi piacciono i fiori, ma ancora meno un'armatura bagnata.",
		PALMLEAF_UMBRELLA = "Non mi piacciono le piante, ma ancora meno un'armatura bagnata.",
		UNIMPLEMENTED = "Una misteriosa reliquia, contenente una grande potenza.",
		WAFFLES = "Le cialde non servono per prepararsi alla battaglia!",
		WALL_HAY = 
		{	
			GENERIC = "Un deterrente minore contro gli aggressori.",
			BURNT = "Non va affatto bene.",
		},
		WALL_HAY_ITEM = "I miei nemici potrebbero perdersi in questo fieno.",
		WALL_STONE = "I miei nemici si precipiteranno su queste rocce.",
		WALL_STONE_ITEM = "Una parete robusta, realizzata dalla terra.",
		WALL_RUINS = "Notte impenetrabile.",
		WALL_RUINS_ITEM = "Solo le migliori barriere per la mia fortezza.",
		WALL_WOOD = 
		{
			GENERIC = "Può impalare un nemico.",
			BURNT = "Il fuoco, unico punto debole del legno!",
		},
		WALL_WOOD_ITEM = "Una fortificazione mediocre.",
		WALRUS = "Quelle zanne potrebbero perforare anche l'armatura più pregiata.",
		WALRUSHAT = "Sporco di montagna!",
		WALRUS_CAMP =
		{
			EMPTY = "Sono partiti per un grande viaggio.",
			GENERIC = "Un accampamento invernale adeguato.",
		},
		WALRUS_TUSK = "Lacerato dalla bocca della bestia di mare.",
		WARG = "Sei tu, Fenrir?",
		WASPHIVE = "Api di guerra!",
		WATERMELON = "Produce un buon suono quando lo colpisci.",
		WATERMELON_COOKED = "Caldo e rosso, ma non scorre.",
		WATERMELONHAT = "È quasi come indossare una pelle di animale.",
		WETGOOP = "Brodaglia.",
		WINTERHAT = "Caldo, ma non adatto al combattimento.",
		WINTEROMETER = 
		{
			GENERIC = "Se solo misurasse la foga del combattimento.",
			BURNT = "Il dispositivo di misurazione è stato ucciso da Loge.",
		},
		WORMHOLE =
		{
			GENERIC = "Ingoia quelli caduti in battaglia?",
			OPEN = "Il suo ventre mi accoglie.",
		},
		WORMHOLE_LIMITED = "È debole e malaticcio.",
		ACCOMPLISHMENT_SHRINE = "Le mie vittorie verranno ricordate!",        
		LIVINGTREE = "Un albero della vita, ma non è Yggdrasil.",
		ICESTAFF = "Un regalo da Ullr!",
		WATHGRITHRHAT = "Il potere dell'unicorno è immenso.",
		SPEAR_WATHGRITHR = "Il mio compagno d'armi!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		BACONEGGS = "Maiale e uova!",
		BANANAPOP = "Ho trovato un modo per renderlo ancora MENO attraente!",
		BISQUE = "Non è niente male.",
		CEVICHE = "Un po' raffinato per i miei gusti, ma andrà bene.",
		SEAFOODGUMBO = "Un pasto adatto a una regina.",
		SURFNTURF = "Bleah! Zolla!",
		SHARKFINSOUP = "Delizioso!",
		LOBSTERDINNER = "Ho trionfato sul mio nemico aragostra.",
		LOBSTERBISQUE = "Ce ne sono ancora di simili.",
		JELLYOPOP = "Potrei uscire fuori di testa per questi!",
		CALIFORNIAROLL = "Quello è solo un boccone di pesce.",

		AERODYNAMICHAT = "La mia testa taglierà l'aria!",
		ANTIVENOM = "Nessun veleno scorrerà nelle mie vene!",
		ARMOR_LIFEJACKET = "L'avventura non offre una vera sicurezza!",
		ARMOR_SNAKESKIN = "La pioggia è sconfitta!",
		ARMOR_WINDBREAKER = "Romperò il vento ad ogni passo!",
		ARMORLIMESTONE = "La sua pesantezza è rassicurante sulle mie ossa.",
		ARMOROBSIDIAN = "Venite a me, ora, demoni!",
		ARMORSEASHELL = "Con questo addosso non dovrei arenarmi alla deriva del Valhalla!",
		ARMOUREDBOAT = "Questa è una nave a misura di vichingo!",
		BABYOX = "Che carne tenera.",
		BALLPHIN = "Un colpo potrebbe semplicemente rimbalzare.",
		BALLPHINPOD = "Una squadra d'assalto!",
		BAMBOO = "Bastoncini di grande versatilità.",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "Si tratta di un giocattolo di Loki?",
		BIOLUMINESCENCE = "Cos'è questa magia?",
		BLOWDART_POISON = "Per indebolire dalla distanza. Odino perdonami...",
		BOAT_INDICATOR = "I shall launch my craft.",
		BOAT_LANTERN = "Guardatemi, bestie immonde dei mari in ombra!",
		BOATCANNON = "Percuote i miei nemici per me!?",
		BOATREPAIRKIT = "Un carico sensato.",
		BOTTLELANTERN = "Una torcia davvero curiosa.",
		BURIEDTREASURE = "Possa la fortuna sorridermi oggi.",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "Suono e impeto!",
		CAPTAINHAT = "Sarebbe meglio con le corna.",
		CARGOBOAT = "Una barca fatta per un lungo viaggio.",
		CHIMINEA = "Che tipo di fiamma si nasconde in una buca?",
		CIRCLINGSEAGULL = "Sporcizia in cielo.",
		CLOTHSAIL = "Un vela raffinata.",
		COCONADE = "Fire that can be thrown.",
		COCONUT = 
		{
		    GENERIC = "Il frutto più duro.",
		    PLANTED = "Un frutto così duro ha dato vita ad un albero delicato.",
		},
		COFFEE = "È amaro e fa battere forte il cuore.",
		COFFEEBEANS = "Lo bevo senza latte.",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "Il mare tramanda regali talmente strani.",
		CORALREEF = "Un luogo duro e fragile. Mi piace.",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "È la vergogna che li conduce in questa buca?",
		CUTLASS = "Oh, grandiosa spada creata dalla morte dei pesci. Ti brandirò con onore.",
		DEAD_SWORDFISH = "Avanti verso il Valhalla, pesce coraggioso.",
		DEPLETED_BAMBOOTREE = "Abbi rispetto di te stesso.",
		DEPLETED_BUSH_VINE = "Non più così rampicante adesso?",
		DOYDOY = "Non mostra alcun segno di paura di me!",
		DOYDOYBABY = "Ti onoro, giovane guerriero dei doidoi.",
		DOYDOYEGG = "All'interno di questo uovo cresce un vichingo con le piume.",
		
		DOYDOYFEATHER = "La piuma preziosa di un volatile guerriero caduto.",
		DOYDOYNEST = "Il nido dove altri coraggiosi si schiuderanno!",
		DUBLOON = "Il bottino dei caduti!",
		DUG_BAMBOOTREE = "Se ti pianto, mi ripagherai?",
		DUG_BERRYBUSH2 = "La mia fonte personale di bacche!",
		DUG_BUSH_VINE = "Arrampicarsi o non arrampicarsi?",
		DUG_COFFEEBUSH = "Caffè da asporto.",
		EARRING = "Questo non appartiene al mio orecchio.",
		FABRIC = "Cucire non è un lavoro da guerrieri...",
		FEATHERSAIL = "I coraggiosi volatili mi hanno fatto dono delle loro rapide piume!",
		FIRERAIN = "Un vero tempo da guerrieri!",
		FIRERAINSHADOW = "Da Odino!",
		FISHINHOLE = "Desiderate arrendervi, pesci?",
		FROG_POISON = "Indietreggia, brutta peste rettiliana!",
		GASHAT = "Una specie di armatura per il mio naso e la mia gola!",
		GOLDENMACHETE = "Ti brandirò con orgoglio.",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "Questo aggeggio funziona sui destrieri di Odino!",
		JELLYFISH = "Sei troppo piccolo per essere un mostro marino.",
		JELLYFISH_COOKED = "Il mostro marino cuoce bene!",
		JELLYFISH_DEAD = "Il mostro marino cavalca verso il Valhalla!",
		JELLYFISH_PLANTED = "Mi aspettavo che i mostri marini fossero più grandi.",
		JELLYJERKY = "I miei denti ti daranno battaglia.",
		JUNGLETREE = "A mighty tree!",
		JUNGLETREE_BURNT = "Addio, gigante.",
		JUNGLETREE_STUMP = "Ci vediamo nel Valhalla, albero.",
		JUNGLETREESEED =
        {
            GENERIC = "La forza dell'albero, in un seme.",
            PLANTED = "Crescerà possente.",
        },
		LAVAPOOL = "Una pozzanghera di fuoco!",
		LIMESTONE = "Duro come un frutto acerbo.",
		LIMPETS = "Carne di roccia!",
		
		LOBSTER = "Sei vestito per la battaglia, abitante del mare.",
		LOBSTERHOLE = "Quelli con l'armatura dimorano qua...",
		LOGRAFT = "Non mi porterai lontano, ma mi porterai.",
		MACHETE = "Una lama dalla lunghezza giusta.",
		MESSAGEBOTTLE = "Un messaggio dal Valhalla.",
		MESSAGEBOTTLEEMPTY = "Priva sia di messaggio che di bevanda. Peccato.",
		MOSQUITO_POISON = "Veleno! L'opera del vigliacco!",
		MUSSEL = "Non sembri molto forte.",
		MUSSEL_STICK = "Le stupide cozze si arrampicheranno su questo bastone.",
		OBSIDIAN = "Ciottoli dalla montagna di fuoco!",
		OBSIDIAN_WORKBENCH = "Fucina del fuoco!",
		OBSIDIANAXE = "Questa sì che è un'ascia!",
		OBSIDIANCOCONADE = "Lanciare fuoco è da codardi. Ma è divertente!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Il fuoco è quasi morto.",
			GENERIC = "Un fuoco a misura di vichingo!",
			HIGH = "Ruggiti di fuoco!",
			LOW = "Il fuoco sta morendo lentamente.",
			NORMAL = "Fuoco caldo, Wigfrid calda.",
			OUT = "E la luce tremola.",
		},
		OBSIDIANMACHETE = "Uno strumento per tagliare. E per incendiare.",
		SPEAR_OBSIDIAN = "Senti il bruciore.",
		OBSIDIANSPEARGUN = "Di solito preferisco appiccare incendi da vicino.",
		OX = "Lode a Odino per questa generosa leccornia a quattro zampe!",
		PACKIM = "Mi seguirai fino al Valhalla?",
		PACKIM_FISHBONE = "Una curiosa bagattella.",
		PALMLEAF = "Una foglia dalle dimensioni di un vichingo!",
		PALMTREE =
		{
			BURNING = "Il legno è in fiamme!",
			BURNT = "Loge lo ha preso.",
			CHOPPED = "Mozzato dal guerriero del bosco!",
			GENERIC = "Abbandoni i rami, albero?",
		},
		PALMTREE_BURNT = "Sento odore di cocco bruciato.",
		PALMTREE_STUMP = "Alimenterai il mio cuore nel Valhalla.",
		PARROT = "Chiudi il becco, pennuto!",
		PEACOCK = "Sarà un peccato rovinare quelle piume, carne.",
		PIRATEHAT = "Questo cappello confonde il mio personaggio... voglio dire, la mia anima.",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "La terra erutta malattia!",
		RAFT = "Un vichingo non teme di bagnarsi!",
		ROWBOAT = "Il canottaggio è nel mio sangue.",
		SAIL = "Un vela curiosa, ma farà al caso.",
		SAND = "Sei uno sporco molto pulito.",
		SAND_CASTLE = "A scale model of my future keep.",
		SANDBAG = "Sabbia insaccata.",
		SANDBAG_ITEM = "Tiene a bada le inondazioni.",
		SANDHILL = "Non farò una montagna di una duna di sabbia.",
		SEAGULL = "Vile pennuto!",
		SEAGULL_WATER = "Fai marcire l'acqua su cui galleggi.",
		SEASACK = "Disgustoso, ma utile a modo suo.",
		SEASHELL = "La moneta del mare.",
		SEASHELL_BEACHED = "Un piccolo scudo elfo?",
		SEATRAP = "Portami i bottini del mare!",
		SEAWEED = "È erba acquosa sporca!",
		
		SEAWEED_PLANTED = "Un'erbaccia che non posso schiacciare sotto il mio stivale.",
		SHARK_FIN = "Un ricordo di un guerriero caduto.",
		SHARX = "Ah, un degno avversario di mare!",
		SLOTMACHINE = "Una macchina del destino e della miseria.",
		SNAKE = "Mai fidarsi di coloro che strisciano.",
		SNAKE_FIRE = "Parlano con la bocca del vulcano!",
		SNAKE_POISON = "Tieni le zanne marce lontano dalla mia pelle!",
		SNAKESKIN = "Un serpente è scivolato via dalla sua pelle. Con un piccolo aiuto...",
		SNAKESKINHAT = "Mi metto un serpente?",
		SOLOFISH = "Sembra che il mare mi offra un banchetto.",
		SPEAR_POISON = "Questa lancia premia la vittoria di un vigliacco.",
		SPEARGUN = "L’arma di un codardo.",
		SPEARGUN_POISON = "Non sono una sorpresa che si nasconde nell'ombra! Oppure lo sono?",
		SPOILED_FISH = "Hai l'odore del tuo fallimento.",
		STUNGRAY = "Non avete alcuna dignità, cose puzzolenti?",
		SUPERTELESCOPE = "Odino mi ha prestato il suo occhio!",
		SWORDFISH = "Ora sei un pesce che insegue il mio cuore!",
		TELESCOPE = "Che inganno è questo?",
		TIGERSHARK = "Portami nel Valhalla, diavolo marino!",
		TIGERSHARKSHADOW = "L'ombra della bestia!",
		TORNADO = "Il vento ha preso una forma furiosa!",
		TOUCAN = "Combatti al mio fianco, volatile dal naso lungo! E banchetteremo insieme nel Valhalla!",
		TRAWLNET = "Rovisterò il mare!",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "Un'arma a misura di divinità!",
		TRINKET_13 = "Che idromele scaduto è questo?",
		TRINKET_14 = "Il giocattolo di un bambino. O cosa?",
		TRINKET_15 = "Un'arma fastidiosa.",
		TRINKET_16 = "Un pezzo di armatura?",
		TRINKET_17 = "Un guerriero entra nel Valhalla a piedi nudi...",
		TRINKET_18 = "Non riconosco l'artigianato.",
		TRINKET_19 = "È sempre cielo sereno per il guerriero leale.",
		TURBINE_BLADES = "Che strano tipo di spada è questa?",
		TURF_BEACH = "Una bella sensazione tra le dita dei piedi.",
		TURF_JUNGLE = "Potresti davvero perderti in questo...",
		TWISTER = "Ti nascondi sotto il vento, cattivo!",
		VENOMGLAND = "La fonte delle febbri.",
		VINE = "Cosa puoi fare per me?",
		VOLCANO = "Una montagna di fuoco!",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "Distruzione insensata di una forgiatrice...",
		VOLCANO_EXIT = "Sono stufa di questo regno infernale.",
		VOLCANOSTAFF = "Fai scendere l'ira della montagna di fuoco!",
		WALL_LIMESTONE = "Una lavorazione raffinata.",
		WALL_LIMESTONE_ITEM = "Rimarrai al mio fianco?",
		WHALE_BLUE = "Terminerò i tuoi lamenti, gigante!",
		WHALE_CARCASS_BLUE = "Brinderò a te nel Valhalla.",
		WHALE_CARCASS_WHITE = "Oh, potenza della puzza.",
		WHALE_WHITE = "Sarebbe un onore ucciderti.",
		NEEDLESPEAR = "Questa è davvero una lancia da guerra meravigliosa!",
		ARMORCACTUS = "Farà di me un'amica del cactus.",
		BAMBOOTREE =
		{
			BURNT = "La tua stregoneria vuota non ti ha salvato dal fuoco.",
			CHOPPED = "Non l'hai potuto attaccare!",
			GENERIC = "Che stregoneria è questa? Un legno cavo?",
		},
		BLOWDART_FLUP = "Un'arma da codardo, rilasciata da una patetica creatura furtiva.",
		BLUBBER = "Questo è molto apprezzato dalla mia gente!",
		BLUBBERSUIT = "Rimpiangi la mia uniforme di grasso, umidità!",
		BOAT_TORCH = "Il mare di notte è acceso!",
		BRAINJELLYHAT = "Il mio cervello ha la forza della mia spada!",
		BUOY = "Mi rincuora vedere la boa sopra le onde.",
		BUSH_VINE =
		{
			BURNT = "È bruciato. Non ha senso lamentarsi.",
			CHOPPED = "Aveva bisogno di un taglio.",
			GENERIC = "Questo arbusto ha la testa a timone.",
		},
		COCONADE =
		{
			BURNING = "Presto la noce sputerà il suo fuoco!",
			GENERIC = "Questa non è una noce normale!",
		},
		COCONUT_COOKED = "Banchetterò con questa grande noce.",
		COCONUT_HALVED = "Ho spaccato la noce e mi ha mostrato il suo interno!",
		COFFEEBEANS_COOKED = "C'è un odore energizzante.",
		COFFEEBUSH =
		{
			BARREN = "Non hai opposto alcuna resistenza.",
			GENERIC = "Produce degli strani frutti del vulcano.",
			PICKED = "I suoi frutti devono essere rinati.",
			WITHERED = "Cespuglio debole!",
		},
		CORAL_BRAIN = "Se lo mangio, ne acquisisco la saggezza?",
		CORAL_BRAIN_ROCK = "Una mistica onnisciente roccia dell'acqua!",
		CRAB =
		{
			GENERIC = "Battiti con me, essere corazzato!",
			HIDDEN = "Disseppelisciti, vigliacco!",
		},
		CRATE = "Cedi i tuoi segreti, scatola!",
		DOUBLE_UMBRELLAHAT = "Che bizzarro tipo di copricapo è questo?",
		DOYDOYEGG_COOKED = "Mangerò la bontà di questo impavido volatile.",
		DOYDOYEGG_CRACKED = "Il suo coraggio trapela.",
		DRAGOON = "Un collega impazzito il cui ventre è pieno di fuoco!",
		DRAGOONDEN = "Un folle deve pur vivere da qualche parte.",
		DRAGOONEGG = "Posso sentire il cuore pulsante del guerriero che c'è in lui!",
		DRAGOONHEART = "Il mio nemico caduto mi ha dato un dono!",
		DRAGOONSPIT = "Vorrei poter sputare fuoco...",
		DUG_ELEPHANTCACTUS = "Arrivo al punto. Appartieni a me adesso.",
		ELEPHANTCACTUS = "Avverto lo spirito di un folle dentro di te, pianta.",
		ELEPHANTCACTUS_ACTIVE = "Finalmente la terra germoglia un degno avversario!",
		ELEPHANTCACTUS_STUMP = "Codardo!",
		FISH_RAW = "Questa carne di mare farà al caso mio.",
		FISH_RAW_SMALL = "Questa carne di mare farà al caso mio.",
		FISH_RAW_SMALL_COOKED = "Questa carne nuoterà nella mia pancia!",
		FLAMEGEYSER = "La terra erutta fuoco!",
		FLOTSAM = "Lo devo pescare dal mare se voglio imparare i suoi segreti.",
		FLUP = "Sei un codardo appostato nel fango!",
		FRESHFRUITCREPES = "Così luminoso e arioso!",
		GRASS_WATER = "Un'erba che posso raccogliere dal mio drakkar!",
		HAIL_ICE = "Il cielo sta gettando ghiaccio!",
		HOME = "Qualcuno deve abitare qui.",
		ICEMAKER =
		{
			HIGH = "La macchina è accesa!",
			LOW = "Sputa fuori molto meno ghiaccio.",
			NORMAL = "Ghiaccio dal fuoco!",
			OUT = "Gli serve più fuoco!",
			VERYLOW = "Il suo fuoco è in procinto di finire.",
		},
		JUNGLETREE =
		{
			BURNING = "L'albero brucia.",
			BURNT = "L'albero che non c'è più.",
			CHOPPED = "Un albero forte, ma non così forte come la mia ascia.",
			GENERIC = "Non ci sono alberi come questo da dove navigo.",
		},
		KNIGHTBOAT = "Il mio drakkar mi induce alla guerra!",
		KRAKEN = "Ti rimanderò all'inferno!",
		KRAKENCHEST = "Bottini di guerra!",
		KRAKEN_TENTACLE = "Il braccio della bestia!",
		LIMPETROCK =
		{
			GENERIC = "La pietra di carne!",
			PICKED = "La pietra è senza carne per ora...",
		},
		TREEGUARD = "Alle armi!",
		LIVINGJUNGLETREE = "Non mi piace la tua faccia, albero!",
		LOBSTER_DEAD = "Dormi nel Valhalla, creatura blindata.",
		LOBSTER_DEAD_COOKED = "La tua corazza cela carne saporita.",
		LUGGAGECHEST = "Spero di essere viziata da questi bottini del mare!",
		MAGIC_SEAL = "Lo maneggerò con il dovuto rispetto per il possente mago guerriero che lo ha lasciato.",
		MAGMAROCK = "Cosa posso usare per far rotolare queste rocce?",
		MAGMAROCK_FULL = "Cosa posso usare per far rotolare queste rocce?",
		MAGMAROCK_GOLD = "Brilla...",
		MAGMAROCK_GOLD_FULL = "Brilla...",
		MANGROVETREE = "Non ho mai abbattuto un albero dal mio drakkar prima!",
		MANGROVETREE_BURNT = "Tutto quello sopra l'acqua è carbonella.",
		MARSH_PLANT_TROPICAL = "Una pianta esigua.",
		MERMFISHER = "Non litigo con i pescatori, a meno che non impugnino le armi.",
		MERMHOUSE_FISHER = "I pescatori abitano qui.",
		MONKEYBALL = "Un po' di scimmiottaggio.",
		MONSTERTARTARE = "Freme ancora.",
		MOSQUITOSACK_YELLOW = "Il parassita ha rilasciato il suo sacco di malattia.",
		MUSSELBOUILLABAISE = "Sottile, ma tiene caldo.",
		MUSSEL_COOKED = "Gusto forte.",
		MUSSEL_FARM =
		{
			GENERIC = "Costruisce cozze.",
			STICKPLANTED = "Diventa un tutt'uno con il bastone...",
		},
		MYSTERYMEAT = "Il cibo dei figli del mio nemico è per me... cosa?",
		OCTOPUSCHEST = "Lo scrigno contiene offerte.",
		OCTOPUSKING = "Sembra aperto alla negoziazione.",
		OXHAT = "Questo cappello manterrà la mia cute secca.",
		OX_FLUTE = "Non ho il ritmo...",
		OX_HORN = "Ah, potrebbe essere una bella tazza!",
		PALMLEAF_HUT = "Mantiene la pioggia lontano dal mio elmetto.",
		PARROT_PIRATE = "Parli troppo!",
		PEG_LEG = "Questa gamba può fungere da battitoio.",
		PIGTENT = "Odora di colazione!",
		PIKE_SKULL = "Mi ricorda casa.",
		PIRATEGHOST = "All'inferno, spirito!",
		PIRATEPACK = "Rafforza i muscoli pettorali.",
		PIRATIHATITATOR =
		{
			BURNT = "La sua magia è volata via come fosse brace.",
			GENERIC = "Che ostrusa stregoneria è mia questa?",
		},
		PORTAL_SHIPWRECKED = "Questo drakkar non sembra adatto ad un guerriero.",
		PRIMEAPE = "Sei divertente tanto quanto peloso.",
		PRIMEAPEBARREL = "A giudicare dal casino, direi che ci vive un vichingo.",
		RAWLING = "Finalmente! Qualcuno con cui allenarsi.",
		REDBARREL = "Questa botte può dare bei pugni.",
		ROCK_CHARCOAL = "Le rocce bruciano?",
		ROCK_OBSIDIAN = "Pietra lavica!",
		SAIL_STICK = "Comando il vento!",
		SANDBAGSMALL = "Questo sacchetto di sabbia combatte l'acqua!",
		SANDBAGSMALL_ITEM = "L'acqua ci si scontra debolmente!",
		SAND_CASTLE =
		{
			GENERIC = "Voglio far finta di essere una gigante e schiacciarlo!",
			SAND = "Il tempo lo ha schiacciato.",
		},
		SEAWEED_COOKED = "Spuntino di mare.",
		SEAWEED_DRIED = "È gommoso...",
		SHADOWSKITTISH_WATER = "Un nemico si profila!",
		SHARKITTEN = "È la vostra mammina che voglio...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Qualcosa è in agguato!",
			INACTIVE = "Solo sabbia... per ora...",
		},
		SHARK_GILLS = "Branchie di squalo!",
		SHARK_TEETHHAT = "Un timone insegue il mio cuore guerriero!",
		SHIPWRECKED_ENTRANCE = "Una nuova terra da saccheggiare e depredare!",
		SHIPWRECKED_EXIT = "Via, verso una nuova terra...",
		SNAKEDEN =
		{
			BURNT = "È bruciato. Non ha senso lamentarsi.",
			CHOPPED = "Aveva bisogno di un taglio.",
			GENERIC = "Questo arbusto ha la testa a timone.",
		},
		SNAKEOIL = "Quali proprietà potenti elargisce?",
		SNAKESKINSAIL = "Una vela fatta di assassino!",
		SPEAR_LAUNCHER = "Un dono da Odino!",
		SUNKEN_BOAT =
		{
			ABANDONED = "Il mare ne richiede un'altra!",
			GENERIC = "Ha qualcosa da dire!",
		},
		SUNKEN_BOAT_BURNT = "Ha avuto luogo un funerale vichingo...",
		SUNKEN_BOAT_TRINKET_1 = "Una specie di arma greggia?", 
		SUNKEN_BOAT_TRINKET_2 = "Il drakkar di un bambino.", 
		SUNKEN_BOAT_TRINKET_3 = "Candela fradicia.", 
		SUNKEN_BOAT_TRINKET_4 = "Stregoneria del mare.", 
		SUNKEN_BOAT_TRINKET_5 = "Non è la mia taglia.",
		SWEETPOTATOSOUFFLE = "È riempito di aria deliziosa!",
		SWEET_POTATO = "Non ho mai sentito parlare di una patata che è dolce!... Disgustoso!",
		SWEET_POTATO_COOKED = "Non la mangerò, ma ne apprezzo il colore.",
		SWEET_POTATO_PLANTED = "Ci sono delle piante dolci non commestibili nel terreno!",
		SWEET_POTATO_SEEDS = "Questi cresceranno dolcemente.",
		SWIMMINGHORROR = "Sei qui per darmi un funerale da vichingo?",
		TELEPORTATO_SW_BASE = "Gli mancano delle cose.",
		TELEPORTATO_SW_BOX = "Fa parte di qualcosa.",
		TELEPORTATO_SW_CRANK = "Gira. Ma per cosa?",
		TELEPORTATO_SW_POTATO = "Che strano aggeggio è questo?",
		TELEPORTATO_SW_RING = "È prezioso?",
		THATCHPACK = "Spero che la mia lancia non lo perfori.",
		TIDALPOOL = "Un laghetto!",
		TIDAL_PLANT = "Pianta fradicia.",
		TIGEREYE = "Ho l'occhio dello squalo-tigre!",
		TRAWLNETDROPPED =
		{
			GENERIC = "Bottinastico!",
			SOON = "Il bottino affonderà presto.",
			SOONISH = "Credo che il mio bottino affonderà presto.",
		},
		TRINKET_20 = "Una specie di arma greggia?", 
		TRINKET_21 = "Il drakkar di un bambino.",
		TRINKET_22 = "Candela fradicia.", 
		TRINKET_23 = "Un qualcosa di rotto.", 
		TROPICAL_FISH = "All'interno è il colore della carne!",
		TUNACAN = "Il cibo che può sopravvivere a un viaggio!",
		TURF_SANDY = "Un pezzo del campo di battaglia.",
		TURF_ASH = "Un pezzo del campo di battaglia.",
		TURF_BADLANDS = "Un pezzo del campo di battaglia.",
		TURF_DECIDUOUS = "Un pezzo del campo di battaglia.",
		TURF_DESERTDIRT = "Un pezzo del campo di battaglia.",
		TURF_FUNGUS_GREEN = "Un pezzo del campo di battaglia.",
		TURF_FUNGUS_RED = "Un pezzo del campo di battaglia.",
		TURF_MAGMAFIELD = "Un pezzo del campo di battaglia.",
		TURF_MEADOW = "Un pezzo del campo di battaglia.",
		TURF_SNAKESKINFLOOR = "La pelle del nemico è gradevole sotto i miei piedi!",
		TURF_SWAMP = "Un pezzo del campo di battaglia.",
		TURF_TIDALMARSH = "Un pezzo del campo di battaglia.",
		TURF_VOLCANO = "Un pezzo del campo di battaglia.",
		TWISTER_SEAL = "Eri tu il piccoletto che sbuffava?!?",
		VOLCANO_ALTAR =
		{
			GENERIC = "L'altare degli dei del fuoco è inerme.",
			OPEN = "È pronto a ricevere il sacrificio!",
		},
		VOLCANO_ALTAR_TOWER = "Un altare agli dei del fuoco!",
		VOLCANO_SHRUB = "Sembri bruciato.",
		WALLYINTRO_DEBRIS = "È questo il relitto del mio drakkar?",
		WATERMELON_SEEDS = "Pieno di semi.",
		WATERYGRAVE = "Bottino sotterraneo!",
		WHALE_BUBBLES = "Qualcosa si nasconde nel profondo.",
		WHALE_TRACK = "Ti scoverò balena.",
		WILBUR_CROWN = "Lo saccheggio qualunque cosa sia?",
		WILBUR_UNLOCK = "Non mi inginocchio per nessun re, anche se adorabile!",
		WILDBORE = "Sento uno spirito affine!",
		WILDBOREHEAD = "Tienimi un posto nel Valhalla.",
		WILDBOREHOUSE = "Un posto terribile per vivere!",
		WIND_CONCH = "Sento una brezza...",
		WOODLEGS_CAGE = "Una gabbia bloccata!",
		WOODLEGS_KEY1 = "Che cosa potrebbe aprire?",
		WOODLEGS_KEY2 = "Un'altra chiave!",
		WOODLEGS_KEY3 = "Una strana chiave!",
		WRECK = "I drakkar disseminano rifiuti nel cammino verso il Valhalla.",
	},
	DESCRIBE_GENERIC = "È un artefatto di questo regno.",
	DESCRIBE_TOODARK = "Troppo scuro anche per la battaglia.",
	DESCRIBE_SMOLDERING = "Le fiamme presto lo consumeranno.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "La carne più fresca!",
	},
}
