return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我覺得她不喜歡剃毛。",
			GENERIC = "你不能剃掉不是毛髮的東西。",
			NOBITS = "已經剃過了，嗯？",
            REFUSE = "我喜歡我的鬍子。",
		},
		STORE =
		{
			GENERIC = "已經比大城市的公交還擠了。",
			NOTALLOWED = "呃，這個主意可能不是最好的？",
		},
		WRITE =
        {
            GENERIC = "噢，不用了，謝謝。我的字寫得很糟糕。",
        },
		RUMMAGE =
        {   
            GENERIC = "對不起，我現在做不到。", 
        },
		COOK =
        {
            GENERIC = "很抱歉，我現在不能烹飪。",
            TOOFAR = "嗯，我得靠近點？",
        },
        CHANGEIN =
        {
            GENERIC = "哎呀。難道我看上去還不夠強壯嗎？",
            BURNING = "幸好是它而不是樹。",
        },
        GIVE =
        {
            DEAD = "我覺得它們不會...嗯...",
            SLEEPING = "它在睡覺。",
            BUSY = "我過會兒再試一次。",
        },
		REPAIRBOAT =
		{
			GENERIC = "我恐怕做不到。",
		},
		TEACH =
        {
            KNOWN = "我已經知道這個了，不是嗎？",
            CANTLEARN = "呃...你懂這個嗎，露西？",
        },
	},
	ACTIONFAIL_GENERIC = "對不起，我做不到。",
	ANNOUNCE_MAGIC_FAIL = "呃，那在這沒用。",
	ANNOUNCE_ADVENTUREFAIL = "唉，好吧。至少我嘗試過了。",
	ANNOUNCE_BEES = "蜜蜂！蜜蜂！",
	ANNOUNCE_BOOMERANG = "抱歉！我真是笨死了！",
	ANNOUNCE_CHARLIE = "誰在那兒，嗯？",
	ANNOUNCE_CHARLIE_ATTACK = "哎喲！太粗暴了！",
	ANNOUNCE_COLD = "這裡有點冷！",
	ANNOUNCE_HOT = "這裡太熱了！",
	ANNOUNCE_CRAFTING_FAIL = "我現在無法做那個。",
	ANNOUNCE_DEERCLOPS = "那是什麼？",
	ANNOUNCE_DUSK = "快到我的睡覺時間了。",
	ANNOUNCE_NOSLEEPONFIRE = "不確定是不是一定安全。",
	ANNOUNCE_NODANGERSIESTA = "沒法午休，有東西在追我。",
	ANNOUNCE_NONIGHTSIESTA = "我寧願在砍樹的空檔午休，也不要在晚上睡覺。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "我寧願在砍樹的空檔午休，也不要在晚上睡覺。",
	ANNOUNCE_NOHUNGERSIESTA = "我的肚子已經咕咕叫了。餓得我無法放鬆睡覺。",
	ANNOUNCE_SHELTER = "感謝你為我遮蔭擋雨，夥計。我還是要砍掉你。",
	ANNOUNCE_BURNT = "哎喲，太熱了！",
	ANNOUNCE_TOOL_SLIP = "真是一場噩夢！",
	ANNOUNCE_DAMP = "有點潮濕，是嗎？",
	ANNOUNCE_WET = "格子衣服就算濕了，也還是暖和的。",
	ANNOUNCE_WETTER = "我身上很濕，是不是？",
	ANNOUNCE_SOAKED = "最好抓緊點，露西。",

	ANNOUNCE_OTHER_WORLD_PLANT = "土壤類型不適合它，是嗎？",

	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "已經過了保鮮期了。",
		SPOILED = "有一點點壞了。",
		STALE = "我要趕緊把它吃掉。",
		INVALID = "我的牙齒應該咬不動那個。",
		YUCKY = "我寧願嚼鯨脂丸子。",
	},
	ANNOUNCE_ENTER_DARK = "誰關的燈？",
	ANNOUNCE_ENTER_LIGHT = "世界亮了！",
	ANNOUNCE_FREEDOM = "我出來了！",
	ANNOUNCE_HOUNDS = "那邊有什麼東西。",
	ANNOUNCE_HUNGRY = "越來越餓了。",
	ANNOUNCE_HUNT_BEAST_NEARBY = "動物就在附近。",
	ANNOUNCE_HUNT_LOST_TRAIL = "不管怎樣，我更擅長伐木，而不是狩獵。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "動物的蹤跡已經被雨沖掉了。",
	ANNOUNCE_INV_FULL = "我拿不了更多的東西了。",
	ANNOUNCE_KNOCKEDOUT = "噢。這是怎麼回事？",
	ANNOUNCE_MOSQUITOS = "蚊子！",
	ANNOUNCE_NODANGERSLEEP = "野外睡覺太可怕了。",
	ANNOUNCE_NODAYSLEEP = "只有失敗者才在白天睡覺。",
	ANNOUNCE_NOHUNGERSLEEP = "我的肚子太餓了，睡不著。",
	ANNOUNCE_NO_TRAP = "好險！",
	ANNOUNCE_PECKED = "對不起！我會更努力的！",
	ANNOUNCE_QUAKE = "大地在晃！",
	ANNOUNCE_THORNS = "哎喲！",
	ANNOUNCE_TORCH_OUT = "火把滅了！",
	ANNOUNCE_FAN_OUT = "我猜現在我不得不忍受高溫的折磨了。",
    ANNOUNCE_COMPASS_OUT = "北方永遠在我心中。",
	ANNOUNCE_TRAP_WENT_OFF = "哎呀！",
	ANNOUNCE_WORMHOLE = "裡面太可怕了！",
	ANNOUNCE_CANFIX = "\n我覺得我能修好這個！",
	ANNOUNCE_ACCOMPLISHMENT= "露西肯定會為我感到驕傲的！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我太厲害了！",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "需要更多便便，是嗎？",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "有點麻，是嗎？",

	ANNOUNCE_BOAT_DAMAGED = "我的船損壞很嚴重，是嗎？",
	ANNOUNCE_BOAT_SINKING = "我快要沉了！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "我們在往下沉！",
	ANNOUNCE_CRAB_ESCAPE = "它逃走了。",
	ANNOUNCE_HIGHRESEARCH = "增長知識。",
	ANNOUNCE_LOWRESEARCH = "幾乎沒什麼價值，不是嗎？",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "進入未知水域！",
	ANNOUNCE_MAPWRAP_RETURN = "剛剛太不明智了！",
	ANNOUNCE_MAPWRAP_WARN = "我正在離開海圖上的水域...",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"大海沖洗掉了留言訊息。",
	},
	ANNOUNCE_MORETREASURE = "還有更多的黃金在等著我！",
	ANNOUNCE_NODAYSLEEP_CAVE = "我現在感覺不太平靜。",
	ANNOUNCE_NOWARDROBEONFIRE = "沒關係。反正我只要有一件不錯的法蘭絨襯衫就夠了。",
	ANNOUNCE_OTHER_WORLD_TREASURE = "真不敢相信，我居然在這裡發現了這個。",
	ANNOUNCE_RESEARCH = "學習會讓你的思想保持敏銳。就像斧頭一樣。",
	ANNOUNCE_SHARX = "附近有一條兇猛的魚類...而且它現在飢腸轆轆！",
	ANNOUNCE_TRAWL_FULL = "是時候拉起來了！",
	ANNOUNCE_TREASURE = "淘金熱拉開序幕！",
	ANNOUNCE_UNIMPLEMENTED = "哎呀！我覺得它還沒準備好。",
	ANNOUNCE_VOLCANO_ERUPT = "哦，天氣太惡劣了，是嗎？",
	ANNOUNCE_WAVE_BOOST = "向北方前進！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "我天生就是追蹤野獸的能手！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "我跟丟了。對不起！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "鯨魚去哪兒了？！",

	BATTLECRY =
	{
		GENERIC = "放馬過來吧，哈！",
		PIG = "我會把你做成培根！",
		PREY = "你就要完蛋了！",
		SPIDER = "向北方前進！",
		SPIDER_WARRIOR = "準備好砍砍砍！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "差不多夠了。",
		PIG = "我原以為情況會好轉的。",
		PREY = "對不起，對不起！",
		SPIDER = "抱歉！",
		SPIDER_WARRIOR = "明天同一時間再戰，是嗎？",
	},
	DESCRIBE =
	{
		PIGMAN =
		{
			FOLLOWER = "我們是一個團隊！耶！",
			GENERIC = "回來，培根！",
			GUARD = "那傢伙看上去不是鬧著玩玩的。",
			WEREPIG = "真不幸。",
			DEAD = "不再是豬了。",
		},
		GLOMMER = "繼續拍打翅膀不要停，小傢伙！",
        GLOMMERFLOWER = 
        {
        	GENERIC = "就連花都是黏黏的。",
        	DEAD = "死了之後還是黏黏的。",
        },
        GLOMMERWINGS = "不出所料，翅膀也是黏黏的。",
        GLOMMERFUEL = "沒錯，他的黏液也黏糊糊的。",
        BELL = "它居然能發出這麼清脆的聲音，太讓我驚訝了。",
        STATUEGLOMMER = 
        {	
        	GENERIC = "好奇怪的雕像，對嗎？",
        	EMPTY = "裡面肯定有過很酷的東西，是不是？",
    	},
		WEBBERSKULL = "這個頭骨也讓我心驚膽戰。",
		MOLE =
		{
			HELD = "想來些石頭嗎？",
			UNDERGROUND = "挖，挖，挖。",
			ABOVEGROUND = "石頭對於它就像是樹木對於我一樣。",
		},
		MOLEHILL = "我敢打賭裡面只是一堆石頭。",
		MOLEHAT = "現在就算是夜間我也能砍樹了！",
		NIGHTSTICK = "漂亮又強大。",
		RABBITHOUSE=
		{
			GENERIC = "這是胡蘿蔔的味道嗎？",
			BURNT = "這是烤胡蘿蔔的味道嗎？",
		},
		TURF_DECIDUOUS = "只是一些地面，不是嗎？",
		TURF_SANDY = "Just some ground, eh?",
		TURF_BADLANDS = "只是一些地面，不是嗎？",

		LAVA_POND_ROCK = "推石小子。",
		LAVA_POND_ROCK2 = "推石小子。",
		LAVA_POND_ROCK3 = "推石小子。",
		LAVA_POND_ROCK4 = "推石小子。",
		LAVA_POND_ROCK5 = "推石小子。",
		LAVA_POND_ROCK6 = "推石小子。",
		LAVA_POND_ROCK7 = "推石小子。",

		BEARGER = "好大一頭熊！",
		BEARGERVEST = "終於找到合適的冬裝了。",
		CAVE_BANANA_BURNT = "太浪費了。",
		SCORCHED_SKELETON = "呀。",
		ICEPACK = "很適合用來遠足旅行。",
		BEARGER_FUR = "就跟我的頭髮一樣厚！",
		BIGFOOT = "看著點兒踩！",
		BONESHARD = "真希望我知道如何做麵包。",
		BUZZARD = "離我的肉遠點！",
		CACTUS = 
		{
			GENERIC = "會被刺到的。",
			PICKED = "確實被刺了。",
		},
		CACTUS_MEAT_COOKED = "這下好多了。",
		CACTUS_MEAT = "你會把釘子往自己嘴巴裡塞嗎？",
		CACTUS_FLOWER = "這種鬼氣候下還能長出東西簡直就是個奇蹟。",
		COLDFIRE =
		{
			EMBERS = "快要熄滅了。",
			GENERIC = "有了這個，這裡就更像家鄉了。",
			HIGH = "哇哦！燒得好旺！",
			LOW = "我是不是應該做點什麼，嗯？",
			NORMAL = "我喜歡在晚上點一堆冰火。",
			OUT = "它還是燃著的時候比較好。",
		},
		CATCOON = "討厭的動物。",
		CATCOONDEN = 
		{
			GENERIC = "呃，你還有幾條命啊？",
			EMPTY = "不在了就好。",
		},
		CATCOONHAT = "樵夫的傳統打扮。",
		COONTAIL = "貓的尾巴。",
		COOKPOT =
		{
			COOKING_LONG = "還要好一會兒，是嗎？",
			COOKING_SHORT = "我的乖乖！馬上就好了！",
			DONE = "晚餐時間到！",
			EMPTY = "就這樣把它放在這裡，也不煮東西，好像挺浪費的。",
			BURNT = "都燒焦了。",
		},
		EYEBRELLAHAT =	"有東西看著你總歸是好事。",
		ARMORDRAGONFLY = "格子圖案是我唯一需要的護甲。",
		DRAGON_SCALES = "我還是不相信飛龍。",
		DRAGONFLYCHEST = "要我說這東西太華而不實了。",
		DECIDUOUSTREE = 
		{
			BURNING = "不！我本來可以把它砍掉的！",
			BURNT = "真是浪費。",
			CHOPPED = "啊——！",
			GENERIC = "它在召喚我！",
			POISON = "是時候把你給砍了。",
		},
		ACORN_COOKED = "真是浪費了這麼好的樹。",
		BIRCHNUTDRAKE = "我要把你也砍掉！",
		FARMPLOT =
		{
			GENERIC = "我更喜歡大型植物。",
			GROWING = "它們永遠長不到適合砍伐的大小。",
			NEEDSFERTILIZER = "我想應該給它加點肥料。",
			BURNT = "如果這是一片林場的話，那我肯定傷心死了。",
		},
		COLDFIREPIT =
		{
			EMBERS = "我應該去砍點木頭來，是吧？",
			GENERIC = "它要用木頭當燃料。",
			HIGH = "我消耗木頭的速度太快了！",
			LOW = "這附近應該有木頭。",
			NORMAL = "嗯。木頭的味道。",
			OUT = "要是我有木頭就好了。",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "拯救樹木！",
			OFF = "懶東西。",
			LOWFUEL = "它急需木頭。",
		},
		ICEHAT = "如果有必要的話，我可以把這個也剁碎。",
		LIGHTNINGGOAT = 
		{
			GENERIC = "你的羊角挺不錯的。",
			CHARGED = "好山羊，好山羊！",
		},
		LIGHTNINGGOATHORN = "你的羊角歸我了。",
		GOATMILK = "我覺得是電讓它凝結的。",
		MEATRACK =
		{
			DONE = "看起來已經曬好了。",
			DRYING = "這就像看著肉慢慢變乾。",
			DRYINGINRAIN = "這就像看著肉變乾...在雨天裡慢慢變乾。",
			GENERIC = "都安裝好了。只要加肉就好了。",
			BURNT = "它已經沒有利用價值了。",
		},
		MERMHEAD = 
		{
			GENERIC = "聞起來像拖網漁船。",
			BURNT = "太奇怪了，現在甚至更難聞了。",
		},
		MERMHOUSE = 
		{
			GENERIC = "它們不是最好使的。",
			BURNT = "連建造一間防火的房子都不會。",
		},
		FLOWERSALAD = "很健康，但不是很耐餓。",
        ICECREAM = "我砍了足夠的樹後才會吃！",
        WATERMELONICLE = "木頭和食物？！",
        TRAILMIX = "一天勞作之後的完美零食。",
        HOTCHILI = "在冷天裡砍了一天樹之後來點辣椒真不錯。",
        GUACAMOLE = "我不確定這玩意能不能吃。",
		MOOSE = "不管它是什麼，它肯定是加拿大的。",
		MOOSEEGG = "呃，很顯然，它會下蛋。",
		MOSSLING = "長著羽毛的駝鹿鵝寶寶！",
		FEATHERFAN = "傳統的加拿大羽扇。",
		TROPICALFAN = "我不習慣這地方的高溫！",
		MINIFAN = "我不習慣這地方的高溫！",
		GOOSE_FEATHER = "好軟的羽毛。",
		STAFF_TORNADO = "我更喜歡用自己的雙手去砍樹。",
		PIGHEAD = 
		{	
			GENERIC = "真是浪費了這麼好的豬肉。",
			BURNT = "我要向廚師投訴。我會注意禮貌的。",
		},
		PIGHOUSE =
		{
			FULL = "裡面塞滿了培根。",
			GENERIC = "只需要一點萬用膠帶就可以把它修好。",
			LIGHTSOUT = "對不起！我沒有偷窺，我發誓！",
			BURNT = "昔日的輝煌如今燒的只剩外殼了。",
		},
		FERTILIZER = "糞便應該放在便便桶裡，而不是讓它留在地上。",
		RAINOMETER = 
		{	
			GENERIC = "下雨會讓樹長得快。",
			BURNT = "氣候專家也躲不過被燒燬的命運。",
		},
		RAINCOAT = "為了能在雨中砍樹。",
		RAINHAT = "在砍樹的時候始終保持頭部乾燥。",
		RESEARCHLAB = 
		{	
			GENERIC = "我不相信所有這些科學的東西。",
			BURNT = "它怎麼會燒著呢？！",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "這越來越奇怪了。",
			BURNT = "沒錯，它也得遵守某些基本的物理定律。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "好吧，我好像明白了。",
			BURNT = "沒了，什麼都沒了。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "我喜歡叫它「帽子機器」！",
			BURNT = "這就是我不喜歡用帽子保暖的原因。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "木頭版的我看起來還不錯。",
			BURNT = "看起來好像還沒有燒焦。",
		},
		ROCK_ICE = 
		{
			GENERIC = "感覺像回到家鄉一樣！",
			MELTED = "在家鄉，它們絕不會融化的。",
		},
		ROCK_ICE_MELTED = "在家鄉，它們絕不會融化的。",
		ICE = "放在口袋裡讓我想起了家鄉。",
        REFLECTIVEVEST = "我還是不相信會有不適合穿格子圖案衣服的時候。",
		HAWAIIANSHIRT = "我更喜歡格子襯衫。",
		TENT = 
		{
			GENERIC = "我已經習慣在糟糕的環境中睡覺。",
			BURNT = "我覺得它現在已經稱不上是帳篷了。",
		},
		SIESTAHUT = 
		{
			GENERIC = "長時間砍樹之後，打個盹兒是很有必要的。",
			BURNT = "只剩下外殼了。",
		},
		TRANSISTOR = "我甚至都不會假裝明白它的工作原理。",
		TREASURECHEST = 
		{
			GENERIC = "木頭太有用處了！看看所有這些用木頭做的東西就知道了！",
			BURNT = "我猜木頭也有不好的一面...",
		},
		TUMBLEWEED = "真希望它再堅固些，這樣我就可以砍它了。",
		GRASS_UMBRELLA = "這可以讓我的鬍子保持適度乾燥，是吧？",
		PALMLEAF_UMBRELLA = "我覺得我這把傘做的不錯。",
		WALL_HAY = 
		{	
			GENERIC = "它會使我打噴嚏。",
			BURNT = "嗯，事情太突然了。",
		},
		WALL_WOOD = 
		{
			GENERIC = "我喜歡它的樣子！",
			BURNT = "我好想念以前的你。",
		},
		WARDROBE = 
        {
        	GENERIC = "在樹林裡要保持乾淨整潔並非易事。",
            BURNING = "木頭可是最好的燃料。",
        	BURNT = "現在沒那麼有用了，是嗎？",
    	},
		WARG = "那東西僅憑一己之力就可以拉動雪橇。",
		WATERMELON = "一個瓜怎麼能含那麼高的水分呢？",
		WATERMELON_COOKED = "不知道烤水果怎麼樣...",
		WATERMELONHAT = "你可以叫我西瓜先生。",
		WINTEROMETER = 
		{
			GENERIC = "在家鄉，我們只需要一半的刻度就夠了。",
			BURNT = "我家鄉的溫度計就不會被燒壞。",
		},
		WORMLIGHT = "這東西應該會有用。",
		WORM =
		{
		    PLANT = "是不是植物，我一看就知道。這很明顯是個冒充植物的傢伙！",
		    DIRT = "小心移動的地面。",
		    WORM = "哇哦，蠕蟲！",
		},
		EEL = "這烹飪出來應該挺不錯的。",
		EEL_COOKED = "烤得真不錯。",
		UNAGI = "它會填飽你的肚子。",
		EYETURRET = "它會把其他傢伙擊退的。",
		EYETURRET_ITEM = "這需要正確安裝。",
		MINOTAURHORN = "很漂亮的犀牛角，是吧。",
		MINOTAURCHEST = "很不錯的帶角箱子，是吧。",
		THULECITE_PIECES = "雖然不是木製的，但還湊合。",
		POND_ALGAE = "好像不能吃。",
		GREENSTAFF = "這可以幫我把現有的東西拆解和還原！",
		POTTEDFERN = "這足以證明我對植物的熱愛。",

		THULECITE = "它可以說是洞穴裡的木頭！",
		ARMORRUINS = "這可以防止傷害。",
		RUINS_BAT = "金屬串在棍子上。",
		RUINSHAT = "雖然不是無邊帽，但還湊合。",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "我想它已經關了吧。",	--calm phase
			WARN = "這東西又開啟了！",	--Before nightmare
			WAXING = "它在振動！", --Nightmare Phase first 33%
			STEADY = "太瘋狂了！", --Nightmare 33% - 66%
			WANING = "它穩定下來了。", --Nightmare 66% +
			DAWN = "它幾乎沒動。", --After nightmare
			NOMAGIC = "我想它已經關了吧。", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "我可以看到它內部的零件！",
		ROOK_NIGHTMARE = "齒輪都散落出來了。",
		KNIGHT_NIGHTMARE = "好像並不是它最好的狀態。",
		MINOTAUR = "又一個被詛咒的可憐生物。",	--Monster in labyrinth
		SPIDER_DROPPER = "它們很聰明，知道要遠離腐爛物。",	--White spider that comes from the roof
		NIGHTMARELIGHT = "這盞燈應該使用木材的。",	--Lights that activate during nightmare.
		RELIC = "Piece of furniture.",	--Fixed relic
		RUINS_RUBBLE = "一切都毀了。",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "它...它真漂亮。",	--Works as axe and pickaxe
		GREENGEM = "好閃亮。",
		ORANGESTAFF = "它可以幫我快速移動。",	--Teleports player.
		YELLOWAMULET = "有了這個東西，晚上我也可以砍樹了。",	--Emits light, player walks faster.
		GREENAMULET = "不管怎麼說，我還是更擅長砍東西。",	--Reduce cost of crafting

		SLURPER = "我覺得這團毛球是活的。",
		SLURPER_PELT = "看上去像一隻死去的海狸。",
		SLURPERPELT = "Where's the nearest fur trader?",
		ARMORSLURPER = "好癢，我覺得它還是活的。",
		SPIDERHOLE_ROCK ="我應該在它們出來之前趕緊離開這地方。",
		ORANGEAMULET = "這可以讓家事更快完成！",
		YELLOWSTAFF = "在緊要關頭很有用！",
		YELLOWGEM = "我可以看到它裡面有星星在閃。",
		ORANGEGEM = "它在閃閃發光。",
		RELIC =
		{
			BROKEN = "I don't plan on fixin' that.",
			GENERIC = "What's this all aboot?",
		},
		TELEBASE = 
		{
			VALID = "It's humming with energy.",
			GEMS = "I don't think it has power.",
		},
		GEMSOCKET = 
		{
			VALID = "看起來準備就緒了。",
			GEMS = "它需要一個寶石。",
		},
		STAFFLIGHT = "太厲害了。",	
		LUCY = "我愛露西！",
        ANCIENT_ALTAR =
        {
        	WORKING = "祭壇的石頭上有斧頭標記。",
        	BROKEN = "好像有點壞了。",
        },             
        ANCIENT_ALTAR_BROKEN = "好像有點壞了。",
        ANCIENT_STATUE = "又一個失敗者。",
        LICHEN = "看起來幾乎不能吃。",
		CUTLICHEN = "好吃！味道像木頭一樣！",
		CAVE_BANANA = "熱帶水果的味道。",
		CAVE_BANANA_COOKED = "我出於某種原因烤熟了它。",
		CAVE_BANANA_TREE = "在家鄉看不到這種樹。",
		ROCKY = "龍蝦餐時間！",
		
		COMPASS =
		{
			GENERIC="指向正北方。",
			N = "正北。",
			S = "南。",
			E = "東。",
			W = "西。",
			NE = "東北。",
			SE = "東南。",
			NW = "西北。",
			SW = "西南。",
		},

		BLUEAMULET = "現在我可以讓飲料保持冰凍了。",
		PURPLEAMULET = "寶石上的光芒消失了。",
		TELESTAFF = "Just another use for wood.",
		MONKEY = "很好。又來一隻。",
		MONKEYBARREL = "很不錯的建築材料。",

		HOUNDSTOOTH="漂亮的東西。",
		ARMORSNURTLESHELL="永遠要小心為上。",
		BAT="是誰教會那隻老鼠飛的？",
		BATBAT = "長著翅膀的老鼠？",
		BATWING="好噁心！",
		BATWING_COOKED="好噁心！但又很好吃！好為難啊！",
		BATCAVE = "裡面住滿了小生物！",
		
		BEDROLL_FURRY="我喜歡露營。",
		BUNNYMAN="他看起來很友善。",
		FLOWER_CAVE="好閃亮！",
		FLOWER_CAVE_DOUBLE="好閃亮！",
		FLOWER_CAVE_TRIPLE="好閃亮！",
		GUANO="它不像其他的那麼臭。",
		LANTERN="嗯，這很有啟發性，對吧？",
		LIGHTBULB="它看起來很耐嚼。",
		MANRABBIT_TAIL="我為此感到抱歉。",
		MUSHTREE_TALL  ="I can't let that stand.",
		MUSHTREE_MEDIUM="Maybe I should chop it.",
		MUSHTREE_SMALL ="It's made of wood.",
		MUSHTREE_TALL=
		{
            GENERIC = "我不能放任它不管。",
            BLOOM = "在它散播開之前砍倒它！",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "也許我應該砍了它。",
            BLOOM = "我喜歡它的顏色。",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "它是木頭做的。",
            BLOOM = "嗯，我現在不能砍倒它...",
        },
        MUSHTREE_TALL_WEBBED = "至少這一棵需要修剪。",
        SPORE_TALL = "飛翔的松果！",
        SPORE_MEDIUM = "飛翔的松果！",
        SPORE_SMALL = "飛翔的松果！",
        SPORE_TALL_INV = "有一天它可能會長成一棵樹的。",
        SPORE_MEDIUM_INV = "有一天它可能會長成一棵樹的。",
        SPORE_SMALL_INV = "有一天它可能會長成一棵樹的。",
		SLURTLE="他只是被誤解了。",
		SLURTLE_SHELLPIECES="我弄壞了他的家。真是過意不去。",
		SLURTLEHAT="它可以確保我的腦袋安全。",
		SLURTLEHOLE="你們在那地方沒問題嗎？",
		SLURTLESLIME="看來有人需要一張紙巾。",
		SNURTLE="螺旋形的東西！",
		SPIDER_HIDER="狡猾的魔鬼！",
		SPIDER_SPITTER="亂吐東西太沒禮貌了！",
		SPIDERHOLE="我應該在它們出來之前趕緊離開這地方。",
		STALAGMITE="我對岩石沒多大興趣。",
		STALAGMITE_FULL="我對岩石沒多大興趣。",
		STALAGMITE_LOW="我對岩石沒多大興趣。",
		STALAGMITE_MED="我對岩石沒多大興趣。",
		STALAGMITE_TALL="我對岩石沒多大興趣。",
		STALAGMITE_TALL_FULL="我對岩石沒多大興趣。",
		STALAGMITE_TALL_LOW="我對岩石沒多大興趣。",
		STALAGMITE_TALL_MED="我對岩石沒多大興趣。",


		TURF_CARPETFLOOR = "Some ground.",
		TURF_CHECKERFLOOR = "Some ground.",
		TURF_DIRT = "Some ground.",
		TURF_FOREST = "Some ground.",
		TURF_GRASS = "Some ground.",
		TURF_MARSH = "Some ground.",
		TURF_ROAD = "Some ground.",
		TURF_ROCKY = "Some ground.",
		TURF_SAVANNA = "Some ground.",
		TURF_WOODFLOOR = "Some ground.",

		TURF_CAVE="一些地面。",
		TURF_FUNGUS="黏糊糊的，像豌豆泥一樣。",
		TURF_SINKHOLE="我是在地下發現這個的。",
		TURF_UNDERROCK="是岩石。廢話。",	
		TURF_MUD="至少不需要你打掃。",

		
		POWCAKE = "我更喜歡用真正的糖做成的蛋糕。",
        CAVE_ENTRANCE = "堵得相當嚴實。",
        CAVE_ENTRANCE_RUINS = "堵得相當嚴實。",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "不管怎樣，那下面可能沒有任何樹。",
            OPEN = "下面看起來好像加拿大的薩德伯里。",
        },
        CAVE_EXIT = 
        {
            GENERIC = "可能過會兒。我在這下面待得很舒服。",
            OPEN = "那上面也許有樹。",
        },
		
		MAXWELLPHONOGRAPH = "比收音機上聽到的大多數東西都要好。",
		BOOMERANG = "看起來很難扔。",
		PIGGUARD = "我可不想讓他發瘋。",
		ADVENTURE_PORTAL = "我懷疑那是不是離開這裡的路。",
		AMULET = "應該總是準備一個備用計劃。",
		ANIMAL_TRACK = "有一隻大型林地生物從這走過！",
		ARMORGRASS = "總比什麼都沒有好。",
		ARMORMARBLE = "穿著這個很難揮動斧頭。",
		ARMORWOOD = "它太適合我了！",
		ARMOR_SANITY = "看見它我就想吐。",
		ASH =
		{
			GENERIC = "被燒得精光。",
			REMAINS_GLOMMERFLOWER = "這曾經是一朵黏滑的花。",
			REMAINS_EYE_BONE = "這曾經是個眼骨。",
			REMAINS_THINGIE = "我猜它沒能和我一起傳送過來。",
		},
		AXE = "沒有我的露西斧好。",
		BABYBEEFALO = "長得這麼醜，估計只有親媽才不會嫌棄。",
		BACKPACK = "那是我的背包。",
		BACONEGGS = "嗚嗚嗚。只有五花培根。",
		BANDAGE = "至少我不必付錢買它。",
		BASALT = "那塊岩石是不會移動的。",
		BEARDHAIR = "我的毛髮不是這個顏色。總之這不是我的鬍子。",
		BEDROLL_STRAW = "想當初在伐木場的時候，我還睡過更糟糕的地方呢。",
		BEE =
		{
			GENERIC = "她在給花授粉，讓花開得更艷。",
			HELD = "現在我拿它怎麼辦？",
		},
		BEEBOX =
		{
			FULLHONEY = "楓糖漿替代品！",
			READY = "楓糖漿替代品！",
			GENERIC = "蜂群！",
			NOHONEY = "只是看著它我就餓了！",
			SOMEHONEY = "如果再等等，我可以收穫更多的。",
			BURNT = "不，不要燒我的蜜蜂！",
		},
		BEEFALO =
		{
			FOLLOWER = "我覺得他喜歡我。",
			GENERIC = "他聞起來像草房一樣。",
			NAKED = "瞬間有精神了，是吧？",
			SLEEPING = "他在睡覺。",
		},
		BEEFALOHAT = "現在我是犛牛王！",
		BEEFALOWOOL = "感覺像我的鬍子。",
		BEEHAT = "這個可以防止蜜蜂蜇我的眼睛。",
		
		BEEHIVE = "它們在裡面又舒適又愜意。",
		
		BEEMINE = "不知道蜜蜂喜不喜歡這個。",
		BEEMINE_MAXWELL = "喂！這太卑鄙了！",
		BERRIES = "它們填不飽我的胃口。",
		BERRIES_COOKED = "像熱漿果的味道。",
		BERRYBUSH =
		{
			BARREN = "它需要有充足養分的糞便肥料。",
			WITHERED = "它快要被熱死了，對嗎？",
			GENERIC = "薩斯卡通漿果？",
			PICKED = "沒有漿果了！",
		},
		BIRDCAGE =
		{
			GENERIC = "我用來讓臭鳥們反省自己惡行的地方。",
			OCCUPIED = "想想你都做過些什麼吧，臭鳥！",
			SLEEPING = "它們睡著了之後倒是看起來很無辜。",
			HUNGRY = "我很快就會給你找點吃的，夥計。",
			STARVING = "他渴望來點肉汁奶酪薯條！",
			DEAD = "很抱歉。我辜負了你。",
			SKELETON = "這個開始散發臭味了。",
		},
		BIRDTRAP = "臭鳥們，等著吧！",
		BIRD_EGG = "那裡面有只滿腦子邪惡思想的鳥。",
		BIRD_EGG_COOKED = "很好，至少它永遠不會變成討厭的鳥。",
		BISHOP = "離我上一次懺悔已經有一陣子了。",
		BLOWDART_FIRE = "這好像有點攻擊性。",
		BLOWDART_SLEEP = "用這個的話，我就可以逃跑了！",
		BLOWDART_PIPE = "是檢驗我強大肺活量的時候了！",
		BLUEGEM = "它好冷。",
		BLUEPRINT = "我可不是愛讀書的人。",
		BELL_BLUEPRINT = "我可不是愛讀書的人。",
		BLUE_CAP = "那可不是肉。",
		BLUE_CAP_COOKED = "那可不是肉。",
		BLUE_MUSHROOM =
		{
			GENERIC = "我不記得哪些蘑菇是可以吃的。",
			INGROUND = "我會再回來的。",
			PICKED = "噢，已經採完了。",
		},
		BOARDS = "好光滑。你真的可以看到它上面的紋理。",
		BOAT = "一定是碰到東北風暴了。",
		BONESTEW = "這可以填飽肚子。",
		BUGNET = "可以用它來捕蚊子。",
		BUSHHAT = "這是與大自然融為一體的好辦法。",
		BUTTER = "我更喜歡人造牛油。",
		BUTTERFLY =
		{
			GENERIC = "我從來不相信那些東西，你說呢？",
			HELD = "你還想往哪兒飛啊？",
		},
		BUTTERFLYMUFFIN = "嘎崩脆！...但是又很鬆軟？",
		BUTTERFLYWINGS = "很抱歉！是我不好！",
		CAMPFIRE =
		{
			EMBERS = "快要熄滅了。",
			GENERIC = "我的吉他哪兒去了？",
			HIGH = "哇哦！燒得好旺！",
			LOW = "我是不是應該做點什麼，嗯？",
			NORMAL = "我喜歡在晚上點一堆營火。",
			OUT = "它還是燃著的時候比較好。",
		},
		CANE = "這可以幫助我重返故土。",
		CARROT = "那是兔子吃的東西。",
		CARROT_COOKED = "那是烤熟的兔子食物。",
		CARROT_PLANTED = "我可不是素食主義者，你說呢？",
		CARROT_SEEDS = "迷你胡蘿蔔。",
		CAVE_FERN = "嘿！是蕨類植物！",

		CHARCOAL = "這讓我有點兒難過。",

        CHESSJUNK1 = "廢金屬。",
        CHESSJUNK2 = "廢金屬。",
        CHESSJUNK3 = "廢金屬。",

		CHESTER = "它已經盡力了！",
		CHESTER_EYEBONE =
		{
			GENERIC = "從來沒有人告訴過他，盯著別人看是不禮貌的。",
			WAITING = "不知道它還會不會再醒過來。",
		},
		COOKEDMANDRAKE = "我是不是不應該那樣做？",
		COOKEDMEAT = "跟老媽以前做的一模一樣。",
		COOKEDMONSTERMEAT = "我還是不想吃它。",
		COOKEDSMALLMEAT = "那只會讓我覺得更餓！",
		CORN = "我喜歡玉米，但它不是我最愛的食物。",
		CORN_COOKED = "充分保留了玉米的精華。",
		CORN_SEEDS = "我更多的是一名伐木工而不是農民。",
		CROW =
		{
			GENERIC = "他正在謀劃些什麼。我看得出來。",
			HELD = "烏鴉，你遭到了報應！",
		},
		CUTGRASS = "我想我可能對這東西過敏。",
		CUTREEDS = "想聽聽我學潛鳥叫嗎？",
		CUTSTONE = "加拿大地盾的一部分。",
		DEADLYFEAST = "聞起來有點不對勁，是吧。",
		DEERCLOPS = "好大一隻駝鹿！",
		DEERCLOPS_EYEBALL = "這可以用來幹什麼？",
		DEPLETED_GRASS =
		{
			GENERIC = "它可能是一叢草。",
		},
		DEVTOOL = "我選擇不發表意見。",
		DIRTPILE = "嘿！一條線索！",
		DIVININGROD =
		{
			COLD = "這裡太不明顯了。",
			GENERIC = "不知道可不可以用它來玩曲棍球比賽。",
			HOT = "肯定沒錯！這附近有東西！",
			WARM = "我覺得越來越近了。",
			WARMER = "哇哦，仔細點兒，老兄。",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "看來它上面應該插有東西的。",
			READY = "解鎖準備就緒。",
			UNLOCKED = "現在只需要啟動它就可以了。",
		},
		DIVININGRODSTART = "那根棒子看起來好奇怪。",
		DRAGONFLY = "在我把這些樹砍倒之前，她會把它們全部燒掉的！",
		LAVAE = "一斧劈死！",
		LAVAE_PET = 
		{
			STARVING = "比青鷺的腿還瘦。",
			HUNGRY = "可憐的姑娘餓了。",
			CONTENT = "看她多高興！",
			GENERIC = "這是我的小蟲子。",
		},
		LAVAE_EGG = 
		{
			GENERIC = "它裡面在燃燒。",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "她需要一件派克大衣。",
			COMFY = "比用萬用膠帶裹起來的駝鹿鵝還舒服！",
		},
		LAVAE_TOOTH = "不像露西那麼鋒利！",

		LAVASPIT = 
		{
			HOT = "啊啊啊啊！樹木殺手！",
			COOL = "現在我的樹安全了。",
		},
		LAVA_POND = "我不會靠那個太近的，不是嗎？",
		DRAGONFRUIT = "我以前從來沒見過這東西。",
		DRAGONFRUIT_COOKED = "味道有點像楓糖漿。",
		DRAGONFRUIT_SEEDS = "也許我可以再多種些。",
		DRAGONPIE = "幾乎和奶油蛋塔一樣好吃！",
		DRUMSTICK = "十月份的食物。",
		DRUMSTICK_COOKED = "謝謝你，火雞。",
		DUG_BERRYBUSH = "是時候進行點園林綠化了。",
		DUG_GRASS = "它把我的眼淚都弄出來了。",
		DUG_MARSH_BUSH = "我應該種下這個。",
		DUG_SAPLING = "嗯。都是小樹枝。",
		DURIAN = "好臭。",
		DURIAN_COOKED = "沒有最臭，只有更臭。",
		DURIAN_SEEDS = "我才不想多種那東西。",
		EARMUFFSHAT = "在我的家鄉，這種東西只在秋天管用。",
		EGGPLANT = "我打賭這肯定和鳥有關係。",
		EGGPLANT_COOKED = "像鳥一樣，太可疑了。",
		EGGPLANT_SEEDS = "嗯。我不是很確定。",
		ACORN = 
		{
		    GENERIC = "我應該把它種出來，然後再砍倒它！",
		    PLANTED = "又來了一棵樹！",
		},
		EVERGREEN =
		{
			BURNING = "不！我本來可以把它砍掉的！",
			BURNT = "真是浪費。",
			CHOPPED = "啊——！",
			GENERIC = "它在召喚我！",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "很抱歉！",
			BURNT = "簡直太可怕了！",
			CHOPPED = "又砍倒一棵！",
			GENERIC = "露西會希望我把它砍倒的。",
		},
		EYEPLANT = "它應該管好自己的事情。",
		FEATHERHAT = "我不想跟那...東西扯上任何關係。",
		FEATHER_CROW = "令人厭惡的羽毛。",
		FEATHER_ROBIN = "讓人噁心的羽毛。",
		FEATHER_ROBIN_WINTER = "愚蠢的羽毛。",
		FEM_PUPPET = "她被困住了！",
		FIREFLIES =
		{
			GENERIC = "讓我想起了阿岡昆公園。",
			HELD = "我口袋裡面裝滿了陽光！",
		},
		FIREHOUND = "火獵犬！",
		FIREPIT =
		{
			EMBERS = "我應該去砍點木頭來，是吧？",
			GENERIC = "它要用木頭當燃料。",
			HIGH = "我消耗木頭的速度太快了！",
			LOW = "這附近應該有木頭。",
			NORMAL = "嗯。木頭的味道。",
			OUT = "要是我有木頭就好了。",
		},
		FIRESTAFF = "我不相信這種魔法的東西。",
		FISH = "看起來像鱈魚。",
		FISHINGROD = "我應該去湖邊待一會兒。",
		FISHSTICKS = "優雅又有型的食物。",
		FISHTACOS = "海的味道。",
		FISH_MED = "它想成為晚宴。",
		FISH_MED_COOKED = "真希望能配點薯條。",
		FISH_COOKED = "真希望能配點薯條。",
		FLINT = "這可以做成斧頭。",
		FLOWER = "很好看。",
		FLOWER_WITHERED = "有人不擅長園藝。",
		FLOWERHAT = "我覺得野花和我的紅頭髮很配。",
		FLOWER_EVIL = "那朵花有問題。",
		FOLIAGE = "看起來像沙拉。",
		FOOTBALLHAT = "這玩意兒會弄亂我的髮型嗎？",
		FROG =
		{
			DEAD = "曾經的青蛙。",
			GENERIC = "我不相信任何不能決定在水裡還是在陸地上生活的生物。",
			SLEEPING = "它累了。",
		},
		FROGGLEBUNWICH = "你可以嚐到沼澤的味道。",
		FROGLEGS = "它們還在跳！",
		FROGLEGS_COOKED = "至少它們不動了。",
		FRUITMEDLEY = "浸了楓糖漿的！",
		GEARS = "我永遠都不可能把這些東西弄清楚的。",
		GHOST = "崩！哈哈！",
		GOLDENAXE = "幾乎趕得上露西了。",
		GOLDENPICKAXE = "它確實很漂亮，但不能用來砍樹。",
		GOLDENPITCHFORK = "好吧。既然我沒法讓它消失，那麼...",
		GOLDENSHOVEL = "是時候去挖點金礦了。",
		GOLDNUGGET = "你無法用黃金做成咖啡桌。\n好吧，也許你可以。但是你不應該那樣做。",
		GRASS =
		{
			BARREN = "我需要在上面施肥。",
			WITHERED = "如果溫度再低些，它也許會長得很好？",
			BURNING = "希望這火不會蔓延到樹上。",
			GENERIC = "看起來可以用來點火。",
			PICKED = "表面好粗糙。",
		},
		GREEN_CAP = "我曾經在森林裡吃過更奇怪的東西。",
		GREEN_CAP_COOKED = "我不相信它。",
		GREEN_MUSHROOM =
		{
			GENERIC = "是綠蘑菇。",
			INGROUND = "它們有自己的作息規律。",
			PICKED = "我想我把它弄斷了。",
		},
		GUNPOWDER = "從來沒有做過這種東西。",
		HAMBAT = "真是浪費了美味的火腿。",
		HAMMER = "是人都會犯錯，不是嗎？",
		HEALINGSALVE = "黏黏的藥膏。",
		HEATROCK =
		{
			FROZEN = "嘶~~~！它結冰了。",
			COLD = "它變冷了，感覺到了嗎？",
			GENERIC = "在家鄉，我們把這種東西叫「夜石」。",
			WARM = "它正變得越來越...暖和。",
			HOT = "有這東西在我口袋裡，我可以砍一整個冬天的樹！",
		},
		HOME = "誰在那兒？",
		HOMESIGN = 
		{
			GENERIC = "有什麼東西是木頭不能做成的嗎？",
			BURNT = "木頭可是最好的燃料。",
		},
		HONEY = "嗯——嗯。蜂王漿。",
		HONEYCOMB = "我差一點就覺得不應該拿這個的。",
		HONEYHAM = "但現在並不是什麼節假日...",
		HONEYNUGGETS = "我最喜歡的食物之一！",
		HORN = "我不確定是不是應該用嘴去吹它。",
		HOUND = "它們應該很擅長拉雪橇。",
		HOUNDBONE = "上面都是狗狗唾液，對嗎？",
		HOUNDMOUND = "我才沒有蠢到去惹那東西。",
		ICEBOX = "啊—— 讓我想起了家鄉。",
		ICEHOUND = "北極獵犬？",
		INSANITYROCK =
		{
			ACTIVE = "它去哪兒了？！",
			INACTIVE = "我不知道該怎麼把那玩意兒移開。",
		},
		JAMMYPRESERVES = "現在就差花生醬了。",
		KABOBS = "樹枝確實讓肉變得更香了。",
		KILLERBEE =
		{
			GENERIC = "那隻蜜蜂好像不太友好。",
			HELD = "她對自己的處境很不滿意。",
		},
		KNIGHT = "麥斯威爾自己的騎警隊。",
		KOALEFANT_SUMMER = "他看上去很美味。",
		KOALEFANT_WINTER = "冬天裡的它們更美味。",
		KRAMPUS = "退後，蠢材！",
		KRAMPUS_SACK = "拿走別人的袋子讓我覺得很不安。",
		LEIF = "我很抱歉我對那些樹做的事！",
		LEIF_SPARSE = "我很抱歉我對那些樹做的事！",
		LIGHTNING_ROD =
		{
			CHARGED = "像北極光一樣漂亮。",
			GENERIC = "現在我不會被閃電劈了。",
		},
		LITTLE_WALRUS = "它們為什麼要住在這麼偏南的地方？",
		LIVINGLOG = "我要留著你，以後你就叫「弗蘭克」吧。",
		LOCKEDWES = "那個傻瓜是誰啊？",
		LOG =
		{
			BURNING = "噢，不要！別把另一根木頭放在火上！",
			GENERIC = "一切都值得了。",
		},
		LUREPLANT = "那是肉嗎？",
		LUREPLANTBULB = "它真暖和，而且是塊狀的。",
		MALE_PUPPET = "你需要幫助嗎？",
		MANDRAKE =
		{
			DEAD = "對不起，小傢伙。",
			GENERIC = "它在看著我。",
			PICKED = "我都幹了什麼？",
		},
		MANDRAKESOUP = "是喝了讓人睏倦的湯。",
		MANDRAKE_COOKED = "抱歉！",
		MARBLE = "感覺像是政府大樓。",
		MARBLEPILLAR = "一定是有人建造的。",
		MARBLETREE = "即使是露西也砍不倒那個。",
		MARSH_BUSH =
		{
			BURNING = "該死！",
			GENERIC = "是荊棘。",
			PICKED = "這樣做值得嗎？",
		},
		MARSH_PLANT = "是植物。",
		MARSH_TREE =
		{
			BURNING = "讓你到處刺人，這就是你的下場！",
			BURNT = "活該。",
			CHOPPED = "雖然是一場很艱苦的戰鬥，但最終我贏了。",
			GENERIC = "是樹就不應該反擊！",
		},
		MAXWELL = "他為什麼要恨我呢？",
		MAXWELLHEAD = "只是一個頭，是嗎？",
		MAXWELLLIGHT = "這有點違反自然規律。",
		MAXWELLLOCK = "鑰匙在哪兒？",
		MAXWELLTHRONE = "我見過比它好的椅子。",
		MEAT = "味道像駝鹿鵝。",
		MEATBALLS = "全都是肉！",
		MEAT_DRIED = "感覺像野外求生一樣。",
		MERM = "那東西是從多骯髒的大海裡面爬出來的啊？",
		MINERHAT = "下煤礦幹活兒了。",
		MONSTERLASAGNA = "這是貓食！",
		MONSTERMEAT = "我還沒有餓到吃怪物肉的地步。",
		MONSTERMEAT_DRIED = "我還是不想吃它。",
		MOSQUITO =
		{
			GENERIC = "那東西吸了我一品脫的血！",
			HELD = "你說我該怎麼處置這小東西呢？",
		},
		MOSQUITOSACK = "很血腥野蠻，對嗎？",
		MOUND =
		{
			DUG = "對不起了！不要纏著我啊！",
			GENERIC = "也許我應該離它遠點。",
		},
		NIGHTLIGHT = "那是什麼樣的黑暗啊？",
		NIGHTMAREFUEL = "我的所有恐懼都匯成了液體，是嗎？",
		
		NIGHTSWORD = "噩夢無法傷害你！",
		NITRE = "我們就是用這個建造鐵路的。",
		ONEMANBAND = "啊，我為你站崗！",
		PANDORASCHEST = "箱子裡裝的是什麼？！",
		PANFLUTE = "我只給露西唱歌。",
		PAPYRUS = "我寧願砍樹也不要寫字。",
		PENGUIN = "你是否來自加拿大並不重要。不論怎樣你都是隻鳥。",
		PERD = "又是鳥！為什麼總是鳥呢？",
		PEROGIES = "我稱它們為「好吃的餃子」。",
		PETALS = "不知道露西喜不喜歡這些。",
		PETALS_EVIL = "它們正用邪惡的小臉朝我皺眉頭。",
		PHLEGM = "我不想它黏在我的小鬍子上。",
		PICKAXE = "和斧頭差不多，但不完全是斧頭。",
		PIGGYBACK = "豬身上的任何部分我都沒有浪費。",
		PIGKING = "他不是我的國王。",
		PIGSKIN = "帶尾巴的培根。",
		PIGTORCH = "它們是怎麼不用拇指就做到的？",
		PINECONE = 
		{
		    GENERIC = "我應該把它種出來，然後再砍倒它！",
		    PLANTED = "又來了一棵樹！",
		},
		LUMPY_SAPLING = "哼，我又得再次把它砍掉了。",
		PITCHFORK = "這真心不是我的菜。",
		PLANTMEAT = "太噁心了！",
		PLANTMEAT_COOKED = "烤熟了之後也沒有多好吃。",
		PLANT_NORMAL =
		{
			GENERIC = "我想知道它會長成什麼。",
			GROWING = "你看著它的話就會感覺它一點都沒長。",
			READY = "可以收穫了。",
			WITHERED = "它已經活不了了，是嗎？",
		},
		POMEGRANATE = "這東西對我來說太複雜了。",
		POMEGRANATE_COOKED = "把這個放在煎餅上應該會很好。",
		POMEGRANATE_SEEDS = "好多種子。",
		POND = "我不會游泳！",
		POOP = "不要在營地裡拉大便！",
		PUMPKIN = "我討厭吃長在地上的東西。",
		PUMPKINCOOKIE = "吃了這個，就有力氣一直砍樹了。",
		PUMPKIN_COOKED = "我喜歡南瓜派。",
		PUMPKIN_LANTERN = "最好不要把它打翻。",
		PUMPKIN_SEEDS = "這是一顆種子。",
		PURPLEGEM = "沒什麼是優秀伐木工解決不了的。",
		RABBIT =
		{
			GENERIC = "討厭的地松鼠...",
			HELD = "吃掉他會讓我感覺很糟糕。",
		},
		RABBITHOLE = 
		{
			GENERIC = "我很懷疑那下面到底有沒有樹。",
			SPRING = "既沒有東西進去也沒有東西出來。",
		},
		RATATOUILLE = "它就像碗裡的一片森林。",
		RAZOR = "真正的伐木工永遠不會剃鬍子。",
		REDGEM = "我在它裡面看到了成千棵樹在熊熊烈火中死去。",
		RED_CAP = "我不知道...",
		RED_CAP_COOKED = "不是真的餓了我才不會吃這個。",
		RED_MUSHROOM =
		{
			GENERIC = "是紅蘑菇。",
			INGROUND = "它們有自己的作息規律。",
			PICKED = "我想我把它弄斷了。",
		},
		REEDS =
		{
			BURNING = "火讓我緊張。",
			GENERIC = "蘆葦。",
			PICKED = "它們會再長出來的。",
		},
        RUBBLE = "殘破的傢俱。",
		RESURRECTIONSTONE = "我不確定是不是應該去碰它。",
		ROBIN =
		{
			GENERIC = "真是下賤的小混蛋。",
			HELD = "不要覺得太舒適了，臭鳥。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "飛到南方去不就行了！",
			HELD = "它在偷取我身體的熱量。",
		},
		ROBOT_PUPPET = "它被困住了！",
		ROCK_LIGHT =
		{
			GENERIC = "它看上去帶著點殼。",
			OUT = "它看起來像要碎掉一樣。",
			LOW = "需要加點...木材？",
			NORMAL = "不需要木材的營火？太太太違反自然規律了！",
		},
		ROCK = "如果足夠用勁的話，我應該可以把它鑿碎。",
		ROCKS = "用這些東西可以做成一個不錯的小因努伊特石堆。",
        ROOK = "嗯...象棋裡的車是直線移動的嗎？我忘記了。",
		ROPE = "可以用來把不同的東西捆在一起。",
		ROTTENEGG = "這世上將少一隻鳥。很好。",
		SANITYROCK =
		{
			ACTIVE = "那塊石頭有點奇怪，你說呢？",
			INACTIVE = "可以理解。",
		},
		SAPLING =
		{
			BURNING = "唉！他都沒機會長大！",
			WITHERED = "在這麼炎熱的天氣下，它永遠也不會長到適合砍伐的大小！",
			GENERIC = "我想要看它長大，那樣我就可以砍掉它了。",
			PICKED = "採摘與砍樹相比真是太沒意思了。",
		},
		SEEDS = "不是樹。",
		SEEDS_COOKED = "我們把它叫做「伐木工的驚喜」。",
		SEWING_KIT = "縫縫補補是我的長項。",
		SHOVEL = "挖洞。種樹！",
		SILK = "看到蜘蛛我就心驚膽戰。",
		SKELETON = "抱歉，朋友。",
		SKELETON_PLAYER = "那太讓人不安了。",
		SKULLCHEST = "太嚇人了！",
		SMALLBIRD =
		{
			GENERIC = "你想要什麼？",
			HUNGRY = "它想要什麼東西。",
			STARVING = "我想它應該是很餓了。",
		},
		SMALLMEAT = "真希望它再大點兒。",
		SMALLMEAT_DRIED = "一口就沒了。",
		SPAT = "讓我想起了媽媽！",
		SPEAR = "比起一把堅實的好斧頭，它的重量還輕了點。",
		SPIDER =
		{
			GENERIC = "這是我見過的最大的蜘蛛！",
			SLEEPING = "現在應該小心點兒，是吧？",
			DEAD = "很好！",
		},
		SPIDERDEN = "好傢伙！看那個東西！",
		SPIDEREGGSACK = "我為什麼要帶著那個東西到處走？",
		SPIDERGLAND = "我覺得它有毒。",
		SPIDERHAT = "這帽子真漂亮，是吧？",
		SPIDERQUEEN = "你可不是我的女王！",
		SPIDER_WARRIOR =
		{
			GENERIC = "它們現在變成黃色了？",
			SLEEPING = "你睡著的時候會被揍得鼻青臉腫的。",
			DEAD = "太好了！",
		},
		SPOILED_FOOD = "呀，就像約翰·迪芬貝克一樣。",
		STATUEHARP = "你的頭不見了，是嗎？",
		STATUEMAXWELL = "他就是個混蛋，不是嗎？",
		STEELWOOL = "用這個可以讓你的斧頭重新變得閃亮。",
		STINGER = "哎喲！刺到我了。",
		STRAWHAT = "這樣我的頭就不會被太陽曬到。",
		STUFFEDEGGPLANT = "我的廚藝越來越好了。",
		SUNKBOAT = "那些木頭以前是有過好日子的。",
		SWEATERVEST = "雖然不是格子圖案的，但還湊合。",
		TAFFY = "甜甜的，不錯。",
		TALLBIRD = "即使是不會飛的鳥，我也不相信。",
		TALLBIRDEGG = "這裡面是什麼？",
		TALLBIRDEGG_COOKED = "正義得以彰顯的味道。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "你覺得太冷了嗎？",
			GENERIC = "它在孵化。",
			HOT = "它在哭嗎？",
			LONG = "鳥類從來都是不慌不忙的。",
			SHORT = "就快好了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "我應該去偷它的蛋，給它點兒教訓。",
			PICKED = "什麼也沒有。",
		},
		TEENBIRD =
		{
			GENERIC = "它將來也會長成一個混球，就像它的父母一樣。",
			HUNGRY = "你一天到晚都很餓嗎？",
			STARVING = "飢餓會讓它變得野蠻。",
		},
		TELEBASE =
		{
			VALID = "它是準備好了，但我呢？",
			GEMS = "需要裝上寶石，是嗎？",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "準備好了，是吧？",
			GENERIC = "我想這應該是個...有魔法的東西。",
			LOCKED = "好像少了點什麼，是吧？",
			PARTIAL = "就快準備好了，是吧？",
		},
		TELEPORTATO_BOX = "四四方方的，是吧？",
		TELEPORTATO_CRANK = "彎彎扭扭的，是吧？",
		TELEPORTATO_POTATO = "看起來像馬鈴薯，是吧？",
		TELEPORTATO_RING = "環狀的，是吧？",
		TELESTAFF = "我很好奇這東西幹什麼用的。",
		TENTACLE = "那下面有一條魷魚？",
		TENTACLESPIKE = "這玩意揮舞起來還在左搖右擺呢。",
		TENTACLESPOTS = "我臉紅了！",
		TENTACLE_PILLAR = "好大啊！",
		TENTACLE_PILLAR_HOLE = "就連樁子也沒留下！",
		TENTACLE_PILLAR_ARM = "那些是小魷魚嗎？",
		TENTACLE_GARDEN = "我厭倦了這些魷魚！",
		TOPHAT = "太花俏了。",
		TORCH = "火把讓我又能看到樹了。",
		TRAP = "變聰明了，對嗎？",
		TRAP_TEETH = "做工似乎有點粗糙。",
		TRAP_TEETH_MAXWELL = "這不公平，他耍詐，不是嗎？",
		TREASURECHEST_TRAP = "那個箱子有點不太對勁。",
		MOOSE_NESTING_GROUND = "我討厭它。",
		TRINKET_1 = "我以前玩過那個遊戲。",
		TRINKET_10 = "老年人的牙齒。",
		TRINKET_11 = "你，給我安靜點！",
		TRINKET_12 = "它完全萎縮了。",
		TRINKET_2 = "這不是真的，對不對？",
		TRINKET_3 = "讓我想起了我曾經聽到的一個故事。",
		TRINKET_4 = "不要問我。",
		TRINKET_5 = "它需要一個機器臂，對嗎？",
		TRINKET_6 = "它們再也變不回原來的樣子了，是嗎？",
		TRINKET_7 = "我可以幾個小時不停地玩這個！",
		TRINKET_8 = "如果能找到浴缸，那我會立刻去洗澡。",
		TRINKET_9 = "我剛才在穿衣服的時候已經把衣服鈕釦縫死了。",
		TRUNKVEST_SUMMER = "好看又透氣。",
		TRUNKVEST_WINTER = "這應該可以抵禦家鄉的寒冬，對嗎？",
		TRUNK_COOKED = "我想所有鼻涕應該都煮掉了吧。",
		TRUNK_SUMMER = "真的好薄。",
		TRUNK_WINTER = "又厚實又毛茸茸的。",
		TURF_CARPETFLOOR = "太對我的口味了。",
		TURF_CHECKERFLOOR = "看起來像城市裡戶外廁所的地板。",
		TURF_DIRT = "只是一些地面，不是嗎？",
		TURF_FOREST = "只是一些地面，不是嗎？",
		TURF_GRASS = "只是一些地面，不是嗎？",
		TURF_MARSH = "只是一些地面，不是嗎？",
		TURF_ROAD = "只是一些地面，不是嗎？",
		TURF_ROCKY = "只是一些地面，不是嗎？",
		TURF_SAVANNA = "只是一些地面，不是嗎？",
		TURF_WOODFLOOR = "適合國王的地板！",
		TURF_DRAGONFLY = "火在這地方不太容易燒起來，是嗎？",
		TURF_DESERTDIRT = "Just some ground, eh?",
		TURF_FUNGUS_GREEN = "Just some ground, eh?",
		TURF_FUNGUS_RED = "Just some ground, eh?",
		TURKEYDINNER = "又到火雞節了！",
		TWIGS = "我應該做個小斧頭來砍這些。",
		BANANAPOP = "我更喜歡吃冰鎮楓糖漿...",
		BISQUE = "好豐盛。",
		CEVICHE = "我瘋了才會不吃這個。",
		SEAFOODGUMBO = "我們家鄉沒有這個。",
		SURFNTURF = "好吃。",
		SHARKFINSOUP = "從現在起，他將在我的胃裡游泳了。",
		LOBSTERDINNER = "我更喜歡鮭魚肉。",
		LOBSTERBISQUE = "看起來是非常棒的荒島食物。",
		JELLYOPOP = "我猜這是個荒島，不是嗎？",
		UMBRELLA = "這可以讓我的鬍子保持乾燥，是吧？",
		UNIMPLEMENTED = "看起來不太安全。",
		WAFFLES = "我更喜歡煎餅。",
		WALL_HAY_ITEM = "它會使我打噴嚏。",
		WALL_STONE = "相當安全，不是嗎？",
		WALL_STONE_ITEM = "相當安全，不是嗎？",
		WALL_RUINS = "雖然破碎了，但還是安全的，對嗎？",
		WALL_RUINS_ITEM = "呵，又是石頭做成的，是嗎？",
		WALL_WOOD_ITEM = "我喜歡它的樣子！",
		WALL_MOONROCK = "看起來美觀又堅固。",
		WALL_MOONROCK_ITEM = "那樣用處不大。",
		WALRUS = "不是吧，又是海象！",
		WALRUSHAT = "我爺爺也有一頂這樣的帽子。",
		WALRUS_CAMP =
		{
			EMPTY = "這在冬天會變得不安全。",
			GENERIC = "海象就在附近，是嗎？",
		},
		WALRUS_TUSK = "他有蛀牙，是嗎？",
		WASPHIVE = "那些蜜蜂為什麼這麼生氣？",
		WORMLIGHT_LESSER = "比海狸的下面還要皺。",
		WETGOOP = "比我吃過的一些東西要好！",
        WHIP = "我希望這東西最後不會傷害任何小生物。",
		WINTERHAT = "很不錯的無邊帽，是吧？",
		WORMHOLE =
		{
			GENERIC = "看起來像屁股！",
			OPEN = "我不確定自己是否真的想進去看看，你說呢？",
		},
		WORMHOLE_LIMITED = "聞起來有點不是味兒，對嗎？",
		ACCOMPLISHMENT_SHRINE = "對我來說似乎有點炫耀的意味。",  
		BISHOP_CHARGE_HIT = "喂！",        		
		LIVINGTREE = "我覺得很矛盾，不是嗎？",
		ICESTAFF = "它讓我想起了家鄉。",
		MOONROCKNUGGET = "呃，它是一塊月亮石。",
        ROCK_MOON = "呃，它是一塊月亮石。",

		------------------------------capy---------------------------------

		WOODLEGS_CAGE = "你在裡面還好嗎，老兄？",

		TWISTER = "大自然母親發脾氣了！",
		WIND_CONCH = "我可以聽到29件整套編鐘的聲音。",

		AERODYNAMICHAT = "一頂可以加速的無邊帽。",
		ANTIVENOM = "味道很糟糕，但確實有效！",
		ARMORCACTUS = "來自多刺植物的保護，嗯？",
		ARMORLIMESTONE = "讓我覺得自己很強硬。",
		ARMOROBSIDIAN = "很酷炫，是吧？",
		ARMORSEASHELL = "它看起來不是很結實。",
		ARMOR_LIFEJACKET = "小小的心理安慰。",
		ARMOR_SNAKESKIN = "穿上它，我感覺自己變得很圓滑。",
		ARMOR_WINDBREAKER = "穿上這個讓我感覺像在家鄉一樣。",
		ARMOUREDBOAT = "這艘船在海上相當安全。",
		BABYOX = "Hey, little buddy!",
		BALLPHIN = "喂，老兄，你會玩把戲嗎？",
		BAMBOO = "它就像節食後的木頭，是吧？",
		BAMBOOTREE =
		{
			BURNT = "像煎培根一樣，是嗎？",
			CHOPPED = "砍得太痛快了！",
			GENERIC = "露西已經等不及要砍下它了。",
		},
		BERMUDATRIANGLE = "有點讓人毛骨悚然，是嗎？",
		BIGFISHINGROD = "挺直腰桿釣大魚去。",
		BIOLUMINESCENCE = "就像北極光。",
		BLOWDART_FLUP = "我會抓到你的！",
		BLOWDART_POISON = "要對準主脈吹，是嗎？",
		BLUBBER = "不要再哭鬧了。",
		BLUBBERSUIT = "不是很討人喜歡。",
		BOATCANNON = "這會把它們炸個稀巴爛！",
		BOATREPAIRKIT = "把它修好嗎？",
		BOAT_LANTERN = "一個船燈。",
		BOAT_TORCH = "我可以夜釣。",
		BOTTLELANTERN = "發光的小傢伙，你在裡面還好吧？",
		BRAINJELLYHAT = "戴上這個之後，我感覺自己像個智者。",
		BUOY = "終生都在漂泊。其實這樣也挺好的。",
		BURIEDTREASURE = "是時候開挖！",
		BUSH_VINE =
		{
			BURNT = "這下蛇不會再回來了。",
			CHOPPED = "雖然不如砍樹那麼有意思，不過也不賴。",
			GENERIC = "它剛剛是在找砍。",
		},
		CAPTAINHAT = "希望我不用和船一起沉沒。",
		CARGOBOAT = "我更喜歡有大口袋的工作短褲。",
		CHIMINEA = "就像為火焰訂製的護甲一樣。",
		CLOTHSAIL = "它應該可以幫助我前行。",
		COCONADE =
		{
			BURNING = "快跑！",
			GENERIC = "我要用這個搞點兒大破壞。",
		},
		COCONUT = 
		{
		    GENERIC = "只是個椰子。",
		    PLANTED = "現在它是一棵小小的棕櫚樹。",
		},
		COCONUT_COOKED = "可以開動了。",
		COCONUT_HALVED = "一半給我，一半給露西。",
		COFFEE = "不錯的咖啡。",
		COFFEEBEANS = "我應該把它們煮了。",
		COFFEEBEANS_COOKED = "加拿大人熱愛他們的咖啡。",
		COFFEEBOT = "用來製作咖啡的，不是嗎？",
		COFFEEBUSH =
		{
			BARREN = "你看起來有點低落，老兄。",
			GENERIC = "咖啡豆！",
			PICKED = "我希望它結的豆子比這多。",
			WITHERED = "需要給它來一大杯咖啡提提神。",
		},
		CORAL = "也許我可以把它碾碎了，做點新的東西出來。",
		CORALREEF = "已經成熟了，可以摘了。",
		CORAL_BRAIN = "好有腦子。",
		CORAL_BRAIN_ROCK = "你是什麼，智者之樹？",
		CRAB =
		{
			GENERIC = "或許我們能成為朋友？",
			HIDDEN = "老兄，你不可能永遠躲著不出來。",
		},
		CRABHOLE = "我的螃蟹老兄就住在那裡。",
		CRATE = "那裡有個箱子。",
		CUTLASS = "很秀氣的刀，不是嗎？",
		DEAD_SWORDFISH = "抱歉，朋友。",
		DEPLETED_BAMBOOTREE = "快點長出來，好讓我再砍你一次！",
		DEPLETED_BUSH_VINE = "我猜它會重新長出來。",
		DEPLETED_GRASS_WATER = "我不喜歡等待。",
		DEVTOOL_NODEV = "好奇怪的東西。",
		DOUBLE_UMBRELLAHAT = "雙重保護！",
		DOYDOY = "不太確定這個嚇人的傢伙是怎麼活下來的。",
		DOYDOYBABY = "真髒。",
		DOYDOYEGG = "我覺得應該挺好吃的。",
		DOYDOYEGG_COOKED = "可以配一塊加拿大培根。",
		DOYDOYEGG_CRACKED = "咳，我現在什麼也做不了。",
		DOYDOYFEATHER = "比不上加拿大鵝的羽毛。",
		DOYDOYNEST = "這些髒鳥在這裡繁衍生息。",
		DRAGOON = "戴著帽子似乎有點熱！",
		DRAGOONDEN = "那看起來可不像河狸壩。",
		DRAGOONEGG = "對我來說，那東西看起來有點可疑。",
		DRAGOONHEART = "怪物的心臟。",
		DRAGOONSPIT = "太沒禮貌了。",
		DUBLOON = "我發現了金礦！",
		DUG_BAMBOOTREE = "你跟我一起走吧！",
		DUG_BUSH_VINE = "準備好來一次旅行了嗎？",
		DUG_COFFEEBUSH = "無論去哪裡，我都會隨身帶著你。",
		DUG_ELEPHANTCACTUS = "你要跟我一起走嗎？",
		EARRING = "不是應該有一對嗎？",
		ELEPHANTCACTUS = "好刺人，是嗎？",
		ELEPHANTCACTUS_ACTIVE = "小心！那株植物隨時會發起攻擊！",
		ELEPHANTCACTUS_STUMP = "這棵仙人掌刺過人，不過現在它累了。",
		FABRIC = "我要怎麼把它染成格子圖案呢？",
		FEATHERSAIL = "我猜觸摸那些噁心的羽毛是值得的。",
		FISHINHOLE = "要是再冷一點兒就好了，這裡將會是一個完美的冰釣之處！",
		FISH_RAW = "我更喜歡鮭魚肉。",
		FISH_RAW_SMALL = "希望我不會引來熊。",
		FISH_RAW_SMALL_COOKED = "在我看來還不錯。",
		FLAMEGEYSER = "哇哦，冷靜一點！",
		FLOTSAM = "只是一堆垃圾。",
		FLUP = "噁心。",
		FRESHFRUITCREPES = "我可以在上面澆點楓糖漿？",
		FROG_POISON = "你的毒液還是留給你自己吧！",
		GASHAT = "戴上這個之後，我就百毒不侵了。",
		GOLDENMACHETE = "它不僅能砍樹，而且閃閃發光！",
		GRASS_WATER = "有點潮濕，是嗎？",
		HAIL_ICE = "你覺得這就很冷了？真逗。",
		HOUNDFIRE = "它燒得好猛！",
		ICEMAKER =
		{
			HIGH = "好冰！讓我想起了家鄉。",
			LOW = "燃料不足。",
			NORMAL = "一切運轉正常。",
			OUT = "它沒法運轉了。",
			VERYLOW = "它隨時可能停下來。",
		},
		INVENTORYGRAVE = "有人曾在這裡。現在不在了。",
		INVENTORYMOUND = "有人曾在這裡。現在不在了。",
		IRONWIND = "看上去速度很快。",
		JELLYFISH = "那是水母，不是嗎？",
		JELLYFISH_COOKED = "如果這個都不能吃的話，那其他還有什麼能吃。",
		JELLYFISH_DEAD = "它的生命幾乎全部流失了，是嗎？",
		JELLYFISH_PLANTED = "我的水母小夥伴。",
		JELLYJERKY = "肉乾！我們老家的食物。",
		JUNGLETREE =
		{
			BURNING = "浪費了這麼好的樹樁。",
			BURNT = "真是浪費。",
			CHOPPED = "以前那些美好的時光。",
			GENERIC = "我聽到樹在召喚我！",
		},
		JUNGLETREESEED =
        {
            GENERIC = "它可以長成一棵高大、適合砍的樹。",
            PLANTED = "現在我們得等等。",
        },
		KNIGHTBOAT = "那傢伙的態度有問題！",
		KRAKEN = "為露西而戰鬥！",
		KRAKENCHEST = "快讓我看看戰利品！",
		KRAKEN_TENTACLE = "有點太招搖了，不覺得嗎？",
		LAVAPOOL = "只是看著它就讓我滿身大汗。",
		LIMESTONE = "我把那個漂亮的珊瑚壓碎了才做成的這個。",
		LIMPETROCK =
		{
			GENERIC = "我可以用這些做一道點心。",
			PICKED = "只是一塊大石頭，是嗎？",
		},
		LIMPETS = "類似於某種水生蝸牛。",
		LIMPETS_COOKED = "開飯了。",
		TREEGUARD = "我惹怒了森林！",
		LIVINGJUNGLETREE = "看得出來，它是希望我把它砍倒的。",
		LOBSTER = "加一點融化的牛油，它會變得很美味。",
		LOBSTERHOLE = "出來吧，小傢伙。",
		LOBSTER_DEAD = "他徹底沒戲了。",
		LOBSTER_DEAD_COOKED = "好吃！",
		LOGRAFT = "我的專長！",
		LUGGAGECHEST = "裡面有什麼好東西嗎？",
		MACHETE = "哇哦，它可以用來砍東西。",
		MAGIC_SEAL = "它在有力地搏動。",
		MAGMAROCK = "把它稍微重新排列下，就可以做成一個不錯的因努伊特石堆。",
		MAGMAROCK_FULL = "把它稍微重新排列下，就可以做成一個不錯的因努伊特石堆。",
		MAGMAROCK_GOLD = "那塊石頭看起來值得一挖。",
		MAGMAROCK_GOLD_FULL = "那塊石頭看起來值得一挖。",
		MANGROVETREE = "看起來好好吃！",
		MANGROVETREE_BURNT = "看到它這樣讓我好傷心。",
		MARSH_PLANT_TROPICAL = "一株小植物。",
		MERMFISHER = "我不認識那個傢伙。",
		MERMHOUSE_FISHER = "我更喜歡小木屋。",
		MESSAGEBOTTLE = "有人要給我傳達什麼訊息嗎？",
		MESSAGEBOTTLEEMPTY = "之前裡面裝的是什麼？",
		MONKEYBALL = "你笑什麼？",
		MONSTERTARTARE = "還有其他東西可以吃嗎？",
		MOSQUITOSACK_YELLOW = "它聞起來有點酸臭。",
		MOSQUITO_POISON = "它肚子裡面裝的都是毒液。",
		MUSSEL = "它們看起來很好吃。",
		MUSSELBOUILLABAISE = "一會兒我就可以吃到最美味的一餐了，是吧？",
		MUSSEL_COOKED = "它們看起來很美味。",
		MUSSEL_FARM =
		{
			GENERIC = "它們想成為美食。",
			STICKPLANTED = "預計過段時間我會有一頓豐盛的貽貝晚餐。",
		},
		MUSSEL_STICK = "貽貝沒法從這東西身上獲得足夠的營養。",
		MYSTERYMEAT = "那究竟是什麼東西！",
		NEEDLESPEAR = "好傢伙，太鋒利了。",
		OBSIDIAN = "有點溫熱。",
		OBSIDIANAXE = "小心點露西，你有競爭對手了！（只是開個玩笑！）",
		OBSIDIANCOCONADE = "它裡面蓄積著很強大的能量。",
		OBSIDIANFIREPIT =
		{
			EMBERS = "我應該去砍點木頭來，是吧？",
			GENERIC = "看起來這是生火的完美地方。",
			HIGH = "我消耗木頭的速度太快了！",
			LOW = "這附近應該有木頭。",
			NORMAL = "嗯。木頭的味道。",
			OUT = "要是我有木頭就好了。",
		},
		OBSIDIANMACHETE = "任何東西一旦碰到它，都會被它燒焦。",
		OBSIDIANSPEARGUN = "它可以讓其他東西著火。",
		OBSIDIAN_WORKBENCH = "我可以在這裡造一些火屬性工具。",
		OCTOPUSCHEST = "謝謝你的東西，夥計！",
		OCTOPUSKING = "你還好嗎，夥計？",
		OX = "那可憐的傢伙就是賣苦力的命。",
		OXHAT = "這頂帽子適合北方人。",
		OX_FLUTE = "我更擅長彈吉他。",
		OX_HORN = "它曾經是牛身上的一部分。",
		PACKIM = "我可以容忍他。",
		PACKIM_FISHBONE = "這最好不要引來長羽毛的害蟲。",
		PALMLEAF = "我用它給自己扇風。",
		PALMLEAF_HUT = "伐木工所能奢求的最佳庇護所。",
		PALMTREE =
		{
			BURNING = "浪費了這麼好的樹樁。",
			BURNT = "真是浪費。",
			CHOPPED = "以前那些美好的時光。",
			GENERIC = "讓我想念貯木場。",
		},
		PARROT = "走開，你這個骯髒的帶毛東西！",
		PARROT_PIRATE = "我才不要和笨鳥聊天。",
		PEACOCK = "太可笑了，呸！",
		PEG_LEG = "這個東西可以砍嗎？",
		PIGTENT = "看起來是某種帳篷。",
		PIKE_SKULL = "呃，那裡有個俗氣的裝飾品。",
		PIRATEGHOST = "也許他並沒有惡意？",
		PIRATEHAT = "現在我就是一名海盜。",
		PIRATEPACK = "用來裝我戰利品的箱包。",
		PIRATIHATITATOR =
		{
			BURNT = "現在再也不滑稽了。",
			GENERIC = "這個裝置的外形好滑稽。",
		},
		POISONHOLE = "我想我應該避開它。",
		PORTAL_SHIPWRECKED = "感覺進去就會出不來。",
		PRIMEAPE = "這傢伙有點愛表現。",
		PRIMEAPEBARREL = "那些愛表現的傢伙睡覺的地方。",
		RAFT = "好可憐的小船。",
		RAWLING = "太瘋狂了！",
		REDBARREL = "那個看起來很危險。",
		RELIC =
		{
			BROKEN = "我沒打算把它修好。",
			GENERIC = "這是用來幹什麼的？",
		},
		ROCK_CHARCOAL = "它把我的手都弄髒了。",
		ROCK_OBSIDIAN = "它裡面在燃燒。",
		ROWBOAT = "靠臂力驅動。",
		SAIL = "我的船帆能夠捕捉到風。",
		SAIL_STICK = "北風任我掌控。",
		SAND = "沙子。",
		SANDBAG = "修築堤壩是我的專長。",
		SANDBAGSMALL = "修築堤壩是我的專長。",
		SANDBAGSMALL_ITEM = "迷你可攜式堤壩。",
		SANDBAG_ITEM = "可攜式堤壩。",
		SANDHILL = "一大堆沙子。",
		SAND_CASTLE =
		{
			GENERIC = "天曉得沙子也能造出這麼好看的東西。",
			SAND = "看上去不錯。",
		},
		SEAGULL = "天上的害蟲！",
		SEAGULL_WATER = "海裡的害蟲！",
		SEASACK = "用來裝我的寶物。",
		SEASHELL = "它讓我想要重新幹起藝術和手工這一行。",
		SEASHELL_BEACHED = "漂亮的貝殼。",
		SEATRAP = "我就等著吃龍蝦宴了。",
		SEAWEED = "它又黏又滑。",
		SEAWEED_COOKED = "它的紋理很奇怪。",
		SEAWEED_DRIED = "有點黏舌頭。",
		SEAWEED_PLANTED = "那會長出海帶來，是吧？",
		SHADOWSKITTISH_WATER = "好傢伙！",
		SHARKITTEN = "一隻體型稍大的可愛凱蒂貓而已。",
		SHARKITTENSPAWNER =
		{
			GENERIC = "我好像聽到了貓叫...？",
			INACTIVE = "我看它就是一堆沙子，對嗎？",
		},
		SHARK_FIN = "我相信鯊魚不會想念這個的。",
		SHARK_GILLS = "魚的肺。",
		SHARK_TEETHHAT = "一頂牙齒做的帽子。",
		SHARX = "可以肯定的是，它絕對不會成為朋友。",
		SHIPWRECKED_ENTRANCE = "我已經準備好去冒險了，嗯！",
		SHIPWRECKED_EXIT = "再見了，老兄。",
		SLOTMACHINE = "北方精神指引著我的命運。",
		SLURPERPELT = "離這最近的毛皮交易商在哪裡？",
		SNAKE = "在所有的蛇中，這一種算是比較無害的。",
		SNAKEDEN =
		{
			BURNT = "這下蛇不會再回來了。",
			CHOPPED = "雖然不如砍樹那麼有意思，不過也不賴。",
			GENERIC = "它剛剛是在找砍。",
		},
		SNAKEOIL = "我才不會上當。",
		SNAKESKIN = "我相信蛇不需要這個。",
		SNAKESKINHAT = "現在該稱它為「針織帽」還是「絨線帽」？",
		SNAKESKINSAIL = "一路酷炫地航行世界。",
		SNAKE_FIRE = "看起來有點過熱了。",
		SNAKE_POISON = "我最好不要被它咬到。",
		SOLOFISH = "好狗狗。",
		SPEARGUN = "這件武器太棒了！",
		SPEARGUN_POISON = "這件酷炫的武器可以讓我的敵人中毒！",
		SPEAR_LAUNCHER = "這件武器太棒了！",
		SPEAR_OBSIDIAN = "這是一根會噴火的長矛。",
		SPEAR_POISON = "這根長矛還有一點額外的功效。",
		SPOILED_FISH = "我覺得是時候把這個東西扔掉了。",
		STUNGRAY = "比浸飽水的駝鹿鵝還難聞！",
		SUNKEN_BOAT =
		{
			ABANDONED = "浪費了好木材。",
			GENERIC = "嘿，朋友。",
		},
		SUNKEN_BOAT_BURNT = "它再也沒法在海上航行了。",
		SUNKEN_BOAT_TRINKET_1 = "這東西對我來說有點太複雜了。",
		SUNKEN_BOAT_TRINKET_2 = "這艘船似乎有點太小了。",
		SUNKEN_BOAT_TRINKET_3 = "想像不出這個有什麼用。",
		SUNKEN_BOAT_TRINKET_4 = "智者的玩具。",
		SUNKEN_BOAT_TRINKET_5 = "那個不是我的尺碼。",
		SUPERTELESCOPE = "就像看阿爾伯塔省平原一樣一望無際。",
		SWEETPOTATOSOUFFLE = "太奢侈了！",
		SWEET_POTATO = "我會用它做成一道美味。",
		SWEET_POTATO_COOKED = "可以摻著棉花糖一起吃。",
		SWEET_POTATO_PLANTED = "看起來像某種特別的馬鈴薯。",
		SWEET_POTATO_SEEDS = "把這些種子種下去對我來說更有用。",
		SWIMMINGHORROR = "我不想跟它扯上任何關係，是吧！",
		SWORDFISH = "那裡有一隻鼻子尖尖的魚。",
		TELEPORTATO_SW_BASE = "沒什麼東西是萬用膠帶修不好的。",
		TELEPORTATO_SW_BOX = "它肯定會有用的，是吧？",
		TELEPORTATO_SW_CRANK = "我應該隨身帶著它。",
		TELEPORTATO_SW_POTATO = "看起來一點也不像馬鈴薯。我知道馬鈴薯長什麼樣子。",
		TELEPORTATO_SW_RING = "某種圓環？",
		TELESCOPE = "可以讓我看得更遠更清楚，是吧？",
		THATCHPACK = "現在我可以攜帶更多木頭了。",
		TIDALPOOL = "似乎是一個頗受歡迎的魚類聚集點。",
		TIDAL_PLANT = "那株植物上沒有木頭可以砍。",
		TIGEREYE = "你不知道盯著別人看是很不禮貌的嗎？",
		TIGERSHARK = "如果它沒有想吃掉我的話，那它還挺可愛的。",
		TOUCAN = "那傢伙看上去詭計多端。",
		TRAWLNET = "魚兒們應該直接游進去。",
		TRAWLNETDROPPED =
		{
			GENERIC = "到我這裡來吧，魚兒們！",
			SOON = "差不多了！",
			SOONISH = "它正在慢慢下沉。",
		},
		TREECLUMP = "老兄，這可是你自己找砍。",
		TRIDENT = "試一下這個笨重的叉子，怎麼樣？！",
		TRINKET_13 = "喝下它安全嗎？",
		TRINKET_14 = "那是我的臉嗎？",
		TRINKET_15 = "這把吉他好迷你！",
		TRINKET_16 = "只是一小塊金屬板而已，是吧？",
		TRINKET_17 = "不是我的尺碼。",
		TRINKET_18 = "它壞掉了。",
		TRINKET_19 = "誰知道這個是用來幹什麼的？",
		TRINKET_20 = "這東西對我來說有點太複雜了。",
		TRINKET_21 = "這艘船似乎有點太小了。",
		TRINKET_22 = "看起來沒什麼用。",
		TRINKET_23 = "我完全不知道那是什麼東西。",
		TROPICAL_FISH = "準備好被我做成炸魚薯條了嗎？",
		TUNACAN = "露西會幫我把它打開。",
		TURBINE_BLADES = "看到它我就暈頭轉向了。",
		TURF_SANDY = "只是一些地面，不是嗎？",
		TURF_ASH = "只是一些地面，不是嗎？",
		TURF_BEACH = "只是一些地面，不是嗎？",
		TURF_DESERTDIRT = "只是一些地面，不是嗎？",
		TURF_FUNGUS_GREEN = "只是一些地面，不是嗎？",
		TURF_FUNGUS_RED = "只是一些地面，不是嗎？",
		TURF_JUNGLE = "只是一些地面，不是嗎？",
		TURF_MAGMAFIELD = "只是一些地面，不是嗎？",
		TURF_MEADOW = "只是一些地面，不是嗎？",
		TURF_SNAKESKINFLOOR = "只是一些地面，不是嗎？",
		TURF_SWAMP = "只是一些地面，不是嗎？",
		TURF_TIDALMARSH = "只是一些地面，不是嗎？",
		TURF_VOLCANO = "只是一些地面，不是嗎？",
		TWISTER_SEAL = "好可愛的小傢伙。",
		VENOMGLAND = "聞起來有點怪。",
		VINE = "唉，可惜不是樹。",
		VOLCANO = "麻煩大了！",
		VOLCANOSTAFF = "火山的力量在我手中。",
		VOLCANO_ALTAR =
		{
			GENERIC = "沒什麼可做的。",
			OPEN = "感覺它想要從我這獲得什麼東西。",
		},
		VOLCANO_ALTAR_BROKEN = "已經徹底壞了。",
		VOLCANO_ALTAR_TOWER = "那塊大石頭看著讓人毛骨悚然。",
		VOLCANO_EXIT = "溜走的時候到了。",
		VOLCANO_SHRUB = "可以肯定它絕對不是常青樹。",
		WALLYINTRO_DEBRIS = "我這是在哪裡？",
		WALL_LIMESTONE = "那是一堵牆。",
		WALL_LIMESTONE_ITEM = "可以修橋的時候，我們為什麼要砌牆？",
		WATERMELON_SEEDS = "或許我可以把它們種起來？",
		WATERYGRAVE = "我希望自己最後不會落得這種下場。",
		WHALE_BLUE = "接招！",
		WHALE_BUBBLES = "老兄，我知道你在下面。",
		WHALE_CARCASS_BLUE = "真是個大傢伙。",
		WHALE_CARCASS_WHITE = "現在，他已經死了。",
		WHALE_TRACK = "我就快要追上它了。",
		WHALE_WHITE = "它很兇猛，而且每天很閒。",
		WILBUR_CROWN = "好奢華。",
		WILBUR_UNLOCK = "我交了個新朋友。",
		WILDBORE = "看起來像個十足的笨蛋。",
		WILDBOREHEAD = "老兄，你真不走運。",
		WILDBOREHOUSE = "看起來裡面住了一屋子笨蛋。",
		WOODLEGSBOAT = "好是好，但就是速度有點慢。",
		WOODLEGSHAT = "可以裝一對毛茸茸的耳罩。",
		WOODLEGSSAIL = "很有型的船帆。",
		WOODLEGS_KEY1 = "它可以打開什麼？",
		WOODLEGS_KEY2 = "什麼的鑰匙？",
		WOODLEGS_KEY3 = "我是不是應該拿著它？",
		WRECK = "浪費了這麼好的木頭。",
		CALIFORNIAROLL = "我覺得自己像一個普通的溫哥華人。",

	},
	DESCRIBE_GENERIC = "那是什麼，嗯？",
	DESCRIBE_TOODARK = "太黑了！",
	DESCRIBE_SMOLDERING = "它要燒起來了，是嗎？",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "成熟的小東西。或者還不夠成熟？",
	},
}
