return {

	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "Ya está en mejor forma que yo.",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "Prefiero que la noche me eche su manto.",
			GENERIC = "No pienso usar una cuchilla.",
			NOBITS = "Ya lo ha perdido todo.",
		},
		WRITE =
        {
            GENERIC = "No... no puedo.",
        },
		STORE =
		{
			GENERIC = "No cabe ahí.",
			NOTALLOWED = "Debo tener modales.",
		},
		RUMMAGE =
        {   
            GENERIC = "¿Tiene que ser difícil todo en la vida?", 
        },
        CHANGEIN =
        {
            GENERIC = "De qué sirve.",
            BURNING = "Supongo que no volveré a cambiar pronto.",
        },
		COOK =
        {
            GENERIC = "Oh. Nadie me ha enseñado a cocinar.",
            TOOFAR = "Está tan... lejos...",
        },
        GIVE =
        {
            DEAD = "No tienen necesidad de posesiones materiales cuando se han ido.",
            SLEEPING = "Volveré más tarde...",
            BUSY = "Es demasiado ocupado para prestarme atención...",
        },
        TEACH =
        {
            KNOWN = "Ya tengo ese conocimiento...",
            CANTLEARN = "Ese conocimiento no está a mi alcance...",
        },
	},
	ACTIONFAIL_GENERIC = "No hago nada bien.",
	ANNOUNCE_MAGIC_FAIL = "No hace nada. Ay.",
	ANNOUNCE_ADVENTUREFAIL = "No todas las muertes son iguales.",
	ANNOUNCE_BOOMERANG = "¡Ay! Eso ha sido el karma.",
	ANNOUNCE_CHARLIE = "¡Demonio! ¡Muéstrate!",
	ANNOUNCE_CHARLIE_ATTACK = "¡Me atacan!",
	ANNOUNCE_COLD = "Estoy muerta de frío.",
	ANNOUNCE_HOT = "Tengo calor miserablemente.",
	ANNOUNCE_WORMS = "Oh, oh. Creo que debería marcharme.",
	ANNOUNCE_CRAFTING_FAIL = "Me faltan los materiales necesarios.",
	ANNOUNCE_DUSK = "La oscuridad no tardará en llegar. Tengo que prepararme.",
	ANNOUNCE_EAT =
	{
		GENERIC = "¡Qué rico!",
		PAINFUL = "Eso no era comestible.",
		SPOILED = "Esa comida se acercaba al final de su vida.",
		STALE = "¿Estaba podrido?",
		INVALID = "Nunca lo haría.",
		YUCKY = "Me da miedo consumir eso.",
	},
	ANNOUNCE_ENTER_DARK = "La oscuridad me ha engullido.",
	ANNOUNCE_ENTER_LIGHT = "¡Y la luz se hizo!",
	ANNOUNCE_HOUNDS = "Los sabuesos están aullando.",
	ANNOUNCE_HUNGRY = "Estoy llena de vacío.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Siento la presencia de la bestia cerca.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Este camino no lleva a ninguna parte.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Sin rastro, solo un montón de estiércol.",
	ANNOUNCE_INV_FULL = "Ya no puedo cargar más.",
	ANNOUNCE_KNOCKEDOUT = "Una vez más despierto a la vida. Ay.",
	ANNOUNCE_NOHUNGERSLEEP = "Mi estómago está tan vacío como mi corazón. No puedo dormir ahora.",
	ANNOUNCE_PECKED = "Estás poniendo a prueba mi paciencia.",
	ANNOUNCE_QUAKE = "La tierra tiembla. ¿Me tragará entera?",
	ANNOUNCE_THORNS = "¡Ay! Con espinas, como yo.",
	ANNOUNCE_TORCH_OUT = "¡La oscuridad ha vuelto!",
	ANNOUNCE_FAN_OUT = "Ha exhalado su último suspiro.",
    ANNOUNCE_COMPASS_OUT = "Ya no siente la fuerza de la tierra.",
	ANNOUNCE_TRAP_WENT_OFF = "Oh, Dios mío.",
	ANNOUNCE_WORMHOLE = "Salgo a este mundo una vez más.",
	ANNOUNCE_CANFIX = "\nA diferencia de mi corazón, esto se puede arreglar.",
	ANNOUNCE_ACCOMPLISHMENT = "Todo esto es transitorio.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Esto se olvidará también, algún día.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Se podría utilizar un poco más.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Tan cerca de la muerte, pero tan lejos.",
	ANNOUNCE_BEES = "¡Abejas! ¡Tal vez sea alérgica!",
	ANNOUNCE_DEERCLOPS = "Eso podría ser malo.",
	ANNOUNCE_FREEDOM = "Libertad. Excelente.",
	ANNOUNCE_HIGHRESEARCH = "He visto el vacío y es profundo y oscuro.",
	ANNOUNCE_LOWRESEARCH = "Conocimiento sucinto...",
	ANNOUNCE_MOSQUITOS = "¡Mosquitos! ¡Que mis venas sean un festín!",
	ANNOUNCE_NODANGERSLEEP = "No puedo dormir, me rodea la muerte.",
	ANNOUNCE_NODAYSLEEP = "El sol me molesta. No podría dormir.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Aún no estoy cansada.",
	ANNOUNCE_NOSLEEPONFIRE = "Ese sería una buena forma de escapar.",
	ANNOUNCE_NODANGERSIESTA = "No podría echarme una siesta. La muerte está cerca.",
	ANNOUNCE_NONIGHTSIESTA = "Preferiría estar en una tienda de campaña.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Preferiría estar en una tienda de campaña.",
	ANNOUNCE_NOHUNGERSIESTA = "Mi estómago está tan vacío como mi corazón. No puedo dormir ahora.",
	ANNOUNCE_SHELTER = "La naturaleza es buena para algo después de todo.",
	ANNOUNCE_BURNT = "¡Ay! ¡Los fuegos del infierno!",
	ANNOUNCE_TOOL_SLIP = "Oh, en fin, no lo necesitaba de todos modos.",
	ANNOUNCE_DAMP = "Húmedo y triste.",
	ANNOUNCE_WET = "Incluso más húmedo que cuando lloro al dormir.",
	ANNOUNCE_WETTER = "Una eternidad de humedad y tristeza.",
	ANNOUNCE_SOAKED = "Un verdadero apocalipsis de agua.",

	ANNOUNCE_OTHER_WORLD_PLANT = "No pertenece a este sitio. Igual que yo.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Todo se desvanece con el tiempo...",
	},
	ANNOUNCE_BOAT_DAMAGED = "Este navío está dañado. Le entiendo perfectamente.",
	ANNOUNCE_BOAT_SINKING = "Pronto acabaré en una tumba de agua.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "¡Me entregaré a las profundidades!",
	ANNOUNCE_CRAB_ESCAPE = "Eludió la muerte otro día.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "¡Observad mientras navego directamente a las fauces de la muerte!",
	ANNOUNCE_MAPWRAP_RETURN = "Regreso una vez más a este mundo.",
	ANNOUNCE_MAPWRAP_WARN = "Tal vez navegaré desde los confines de la Tierra.",
	ANNOUNCE_TREASURE = "Un mapa del tesoro...¡Qué emoción!",
	ANNOUNCE_MORETREASURE = "Otro mapa... ¡Menos emocionante!",
	ANNOUNCE_NO_TRAP = "Por fin algo ha salido bien.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Una guía a una tierra lejana.",
	ANNOUNCE_RESEARCH = "Ahora poseo un mayor conocimiento de este mundo terrible.",
	ANNOUNCE_SHARX = "¡Me persiguen malhechores!",
	ANNOUNCE_TRAWL_FULL = "El mar ofrece su recompensa.",
	ANNOUNCE_UNIMPLEMENTED = "¡Oh! Creo que necesita un poco más de tiempo.",
	ANNOUNCE_VOLCANO_ERUPT = "¡Ha salido por TODO LO ALTO!",
	ANNOUNCE_WAVE_BOOST = "Alegría...",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "¡El mastodonte se muestra!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Al igual que Ismael, mi caza está condenada.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "¡Te encontraré, bestia!",

	BATTLECRY =
	{
		GENERIC = "¡La muerte te encontrará!",
		PIG = "¡Deja que la muerte te abrace!",
		PREY = "¡Sufre, gusano!",
		SPIDER = "¡Te enviaré al otro lado!",
		SPIDER_WARRIOR = "¡Voy a ser tu final!",
	},
	COMBAT_QUIT =
	{
		PIG = "Has eludido a la muerte hoy, bestia.",
		PREY = "Ahora apreciarás mejor el regalo de la vida.",
		SPIDER = "Deberías dar las gracias de que te esté perdonando la vida.",
		SPIDER_WARRIOR = "No olvidaré esto.",
		GENERIC = "Vivirás. Por ahora.",
	},
	DESCRIBE =
	{
		INVENTORYGRAVE = "¿Les importará si me arrastro con ellos?",
		INVENTORYMOUND = "¿Les importará si me arrastro con ellos?",
		LIMPETS_COOKED = "Qué deprimente.",
		GLOMMER = "Ay, qué bola peluda tan feliz. Muere.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "La flor de la noche.",
        	DEAD = "Incluso las flores de la noche mueren.",
        },
        GLOMMERWINGS = "Incluso sus alas son pequeñas y alegres.",
        GLOMMERFUEL = "Excremento de bola peluda.",
        BELL = "Para llamar a los muertos.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "¿¡Qué ES eso!?",
        	EMPTY = "Lo he matado.",
    	},
		WEBBERSKULL = "Está mejor así.",

		LAVA_POND_ROCK = "Tan frío y duro como mi corazón...",
		LAVA_POND_ROCK2 = "Tan frío y duro como mi corazón...",
		LAVA_POND_ROCK3 = "Tan frío y duro como mi corazón...",
		LAVA_POND_ROCK4 = "Tan frío y duro como mi corazón...",
		LAVA_POND_ROCK5 = "Tan frío y duro como mi corazón...",
		LAVA_POND_ROCK6 = "Tan frío y duro como mi corazón...",
		LAVA_POND_ROCK7 = "Tan frío y duro como mi corazón...",

		MOLE =
		{
			HELD = "¿Te gusta que te arrebaten de tu familia?",
			UNDERGROUND = "Quédate ahí abajo, lejos de este lugar horrible.",
			ABOVEGROUND = "Deberías volver a donde está oscuro.",
		},
		MOLEHILL = "Abajo, abajo, abajo a las profundidades.",
		MOLEHAT = "Así que esto es lo que ven estos bichos.",
		NIGHTSTICK = "Peligro en la oscuridad.",
		RABBITHOUSE=
		{
			GENERIC = "No es tan comestible como parece.",
			BURNT = "No se ha cocinado bien.",
		},
		TURF_DECIDUOUS = "Un poco de suelo.",
		TURF_SANDY = "Un poco de suelo.",
		TURF_BADLANDS = "Un poco de suelo.",
		BEARGER = "Podría aplastarme de un solo golpe. Me gustaría que lo hiciera.",
		BEARGERVEST = "La muerte me rodea. Bueno, al menos a mi torso.",
		ICEPACK = "No me aislará de los horrores de este mundo.",
		BEARGER_FUR = "Huele a muerte.",
		FURTUFT = "Procede de una criatura viviente.",
		BIGFOOT = "Mensajero de la muerte.",
		BONESHARD = "Riesgo de asfixia.",
		BUZZARD = "He oído que se alimentan de los muertos.",
		FIREPIT =
		{
			EMBERS = "Don't give up, little flame!",
			GENERIC = "A flame to keep the horrors at bay.",
			HIGH = "This fire burns with passion!",
			LOW = "It's losing the will to go on.",
			NORMAL = "It's a comfort.",
			OUT = "This can be rekindled, unlike my heart.",
		},
		CACTUS = 
		{
			GENERIC = "Cuchillos fuera.",
			PICKED = "Aplanado.",
		},
		CACTUS_MEAT_COOKED = "He arrancado todos sus pinchos.",
		CACTUS_MEAT = "Es aún peligroso.",
		CACTUS_FLOWER = "Incluso la planta-cuchillo tiene una flor. Agh.",
		COLDFIRE =
		{
			EMBERS = "La oscuridad se cierne.",
			GENERIC = "¡Tal vez sobreviva a esta noche!",
			HIGH = "¡Una visión de un infierno congelado!",
			LOW = "La oscuridad nos invade.",
			NORMAL = "Es un fuego extraño.",
			OUT = "Eso no es una buena señal.",
		},
		CATCOON = "Me pregunto si tendría un gemelo también.",
		CATCOONDEN = 
		{
			GENERIC = "Podría acurrucarme y morir allí.",
			EMPTY = "Todos los gatos deben morir.",
		},
		CATCOONHAT = "Nada como el hedor de la muerte en mi cabeza.",
		COONTAIL = "Es enmarañada, desigual y pútrida.",
		COOKPOT =
		{
			COOKING_LONG = "Sea lo que sea lo que haya aquí, aún no está muerto.",
			COOKING_SHORT = "Debe hervir.",
			DONE = "Por fin, comida.",
			EMPTY = "Tan vacía como mi alma.",
			BURNT = "Quemado hasta estar crujiente.",
		},
		EYEBRELLAHAT =	"Es un ojo elástico.",
		ARMORDRAGONFLY = "Me gustaría llevarla al revés.",
		DRAGON_SCALES = "Escamas de dolor.",
		DRAGONFLYCHEST = "Caja fogosa.",
		DECIDUOUSTREE = 
		{
			BURNING = "Está ardiendo brillantemente.",
			BURNT = "Agotado y muerto.",
			CHOPPED = "Todo muere.",
			GENERIC = "Este árbol es espeluznante. Apuesto a que le gusta Halloween.",
			POISON = "¡Muy espeluznante!",
		},
		ACORN_COOKED = "Asado muerto.",
		BIRCHNUTDRAKE = "¡Bolas de batalla!",
		FARMPLOT =
		{
			GENERIC = "¿Qué semillas debo sembrar?",
			GROWING = "El barro se alimenta de la suciedad para crecer.",
			NEEDSFERTILIZER = "Esta tierra está fría y muerta.",
			BURNT = "Esta tierra está quemada y muerta.",
		},
		COLDFIREPIT =
		{
			EMBERS = "La oscuridad se cierne.",
			GENERIC = "¡Tal vez sobreviva a esta noche!",
			HIGH = "¡Una visión de un infierno congelado!",
			LOW = "La oscuridad nos invade.",
			NORMAL = "Es un fuego extraño.",
			OUT = "Eso no es una buena señal.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "No sé para qué te molestas. Todos vamos a arder.",
			OFF = "Quieto como un cadáver.",
			LOWFUEL = "Sale humo.",
		},
		ICEHAT = "Mantiene la cabeza fría.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Mira esas pezuñas.",
			CHARGED = "¡A la cargaaaaa!",
		},
		LIGHTNINGGOATHORN = "Un cuerno retorcido de forma rara.",
		GOATMILK = "Creo que está cuajada.",
		MEATRACK =
		{
			DONE = "Se ha terminado de secar.",
			DRYING = "Se balancea secándose al viento.",
			DRYINGINRAIN = "La lluvia impide que se seque.",
			GENERIC = "Puedo colgar carne aquí.",
			BURNT = "Se ha terminado de secar para siempre.",
		},
		MERMHEAD = 
		{
			GENERIC = "Sin dignidad en absoluto.",
			BURNT = "De alguna manera, encontró una manera para hundirse aún más.",
		},
		MERMHOUSE = 
		{
			GENERIC = "El tiempo la ha roto.",
			BURNT = "El fuego la ha roto aún más.",
		},
		FLOWERSALAD = "Agh, más flores.",
        ICECREAM = "El helado nunca podría reemplazar a Abigail.",
        WATERMELONICLE = "El melón está en estasis.",
        TRAILMIX = "Un puñado de sustento.",
        HOTCHILI = "Quema mis entrañas.",
        GUACAMOLE = "Es simplemente espantoso. Me gusta.",
		MOOSE = "Es una abominación.",
		MOOSEEGG = "No sé cómo puede suceder una cosa así.",
		MOSSLING = "Una vida nueva. Lo último que alguien necesita.",
		FEATHERFAN = "Dará mucha corriente.",
		TROPICALFAN = "Cuando estoy quieta, es tan inerte como Abigail.",
		MINIFAN = "Cuando estoy quieta, es tan inerte como Abigail.",
		GOOSE_FEATHER = "Arrancada como me arrancaron a Abigail.",
		STAFF_TORNADO = "Qué mal tiempo hace ahí fuera.",
		PIGHEAD = 
		{	
			GENERIC = "Mata al cerdo. Derrama su sangre.",
			BURNT = "Ha ardido.",
		},
		PIGHOUSE =
		{
			FULL = "Espero que lo estén pasando bien.",
			GENERIC = "Al menos ellos están a gusto.",
			LIGHTSOUT = "Siempre fuera, mirando hacia dentro.",
			BURNT = "Nada dura para siempre.",
		},
		FERTILIZER = "Un cubo de suciedad.",
		RAINOMETER = 
		{	
			GENERIC = "Mide la nubosidad. Me gusta cuando hace un día gris.",
			BURNT = "¿Significa esto que el sol está muerto también?",
		},
		RAINCOAT = "Me gustaba saltar en los charcos con Abigail.",
		RAINHAT = "¿Qué diversión tiene la lluvia si no te mojas?",
		RESEARCHLAB = 
		{	
			GENERIC = "Aprenderé cosas innombrables.",
			BURNT = "Ha ardido inefablemente.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Aprenderé cosas innombrables.",
			BURNT = "Ha ardido inefablemente.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Aprenderé cosas innombrables.",
			BURNT = "Ha ardido inefablemente.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Esto es solo un paso hacia la locura.",
			BURNT = "La locura trae fuego.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Solo estoy posponiendo lo inevitable.",
			BURNT = "Me alegro de que la seguridad haya fallado.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Un pedazo grande de hielo frío y sin sentimientos.",
			MELTED = "Un gran charco de hielo fresco y fundido.",
		},
		ROCK_ICE_MELTED = "Un gran charco de hielo fresco y fundido.",
		ICE = "Trozos rotos de mi corazón.",
        REFLECTIVEVEST = "Todo es un chaleco.",
		HAWAIIANSHIRT = "A cualquier cosa le ponen flores hoy en día.",
		TENT = 
		{
			GENERIC = "El sueño no es más que un anticipo de la muerte.",
			BURNT = "Un anticipo de los fuegos del infierno.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Una siesta no es más que un anticipo de la muerte.",
			BURNT = "Un anticipo de los fuegos del infierno.",
		},
		TRANSISTOR = "¿No-sé-qué eléctrico?",
		TREASURECHEST = 
		{
			GENERIC = "Para almacenar mis lucros.",
			BURNT = "Ni siquiera puede guardar ya cenizas.",
		},
		TUMBLEWEED = "Sola y rodando por la vida.",
		GRASS_UMBRELLA = "El sol golpea.",
		PALMLEAF_UMBRELLA = "El sol golpea.",
		UNIMPLEMENTED = "No está terminado, como la vida.",
		WALL_HAY = 
		{	
			GENERIC = "Es la mera sugerencia de defensa.",
			BURNT = "Defensas fuera.",
		},
		WALL_WOOD = 
		{
			GENERIC = "Ahora puedo retrasar lo inevitable.",
			BURNT = "Lo inevitable se acerca.",
		},
		WARG = "A true bastion of evil.",
		WATERMELON = "Es sobre todo agua. ¿Qué tiene de especial?",
		WATERMELON_COOKED = "Ahora es agua tibia.",
		WATERMELONHAT = "Está pegajoso sobre mi cabeza. Puaj.",
		WINTEROMETER = 
		{
			GENERIC = "¿Por qué siento que está midiendo mi mortalidad?",
			BURNT = "¿Significa esto que mi día de morir es aquí?",
		},
		HOME = "A pathetic simulcra...",
		HOMESIGN = 
		{
			GENERIC = "La señal está hecha, aunque pasajera.",
			BURNT = "Pasajera, sí.",
		},
		BEEBOX =
		{
			GENERIC = "Trabajan para que yo pueda robar.",
			READY = "¡Su trabajo ha sido fructífero!",
			FULLHONEY = "¡Su trabajo ha sido fructífero!",
			NOHONEY = "¡Trabajas, abejas!",
			SOMEHONEY = "Producto del esfuerzo.",
			BURNT = "Miel quemada.",
		},
		LIVINGTREE = "¿Puede vivir para siempre?",
		ICESTAFF = "Un báculo para congelar.",
		WORMLIGHT = "Hay un ligero zumbido que viene de ahí.",
		WORMLIGHT_LESSER = "Mejor la luz del gusano que su lengua.",
		WORM =
		{
		    PLANT = "Parece fuera de lugar.",
		    DIRT = "¿Hay algo ahí?",
		    WORM = "Viene de las profundidades.",
		},
		WORMLIGHT_PLANT = "Parece fuera de lugar.",
		EEL = "Una anguila.",
		EEL_COOKED = "Una anguila que ha sido cocinada.",
		UNAGI = "Parece más apetecible así.",
		EYETURRET = "No sé por qué me ayuda.",
		EYETURRET_ITEM = "Creo que necesito colocarla.",
		MINOTAURHORN = "Todo lo que queda de una enorme bestia.",
		MINOTAURCHEST = "¡Vaya, qué magníficos cuernos tienes!",
		THULECITE_PIECES = "Fragmentos de un material poderoso.",
		POND_ALGAE = "Algunas algas.",
		GREENSTAFF = "Puedo ver el poder brillando en su interior.",
		POTTEDFERN = "Su crecimiento se atrofia por los límites de la olla.",

		THULECITE = "Su presencia marca el límite de lo desconocido.",
		ARMORRUINS = "Un respiro de la muerte.",
		RUINS_BAT = "Tengo el poder de los ancestros en mis manos.",
		RUINSHAT = "A Abigail le hubiera encantado esta corona.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "No sé lo que se esconde en la sombra.",	--calm phase
			WARN = "Puedo sentir las miradas indiscretas.",	--Before nightmare
			WAXING = "Se acercan.", --Nightmare Phase first 33%
			STEADY = "¡Me tienen rodeada!", --Nightmare 33% - 66%
			WANING = "Creo que se están yendo.", --Nightmare 66% +
			DAWN = "Ya casi ha terminado.", --After nightmare
			NOMAGIC = "Estoy sola.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "El tiempo gana todas las batallas.",
		ROOK_NIGHTMARE = "El tiempo lo erosiona todo.",
		KNIGHT_NIGHTMARE = "Otra batalla perdida contra el tiempo.",
		MINOTAUR = "Debe de estar muy solo. Atrapado en una jaula tan pequeña.",	--Monster in labyrinth
		SPIDER_DROPPER = "La oscuridad ha borrado el color de su piel.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Extrae poder desde abajo.",	--Lights that activate during nightmare.
		RELIC = "A vision of the past.",	--Fixed relic
		RUINS_RUBBLE = "A vision of the past. Broken.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "Un objeto con múltiples usos.",	--Works as axe and pickaxe
		GREENGEM = "Los defectos son sus características más hermosas.",
		ORANGESTAFF = "Cada vez que lo uso me muero y vuelvo a renacer.",	--Teleports player.
		YELLOWAMULET = "Una breve luz en mi vida oscura.",	--Emits light, player walks faster.
		GREENAMULET = "¡Un destello de brillantez!",	--Reduce cost of crafting

		SLURPER = "Ah, ser tan simple.",
		SLURPER_PELT = "Una bolsa vacía de hambre.",
		SLURPERPELT = "An empty bag of hunger.",
		ARMORSLURPER = "Un traje pegajoso, lúgubre y viviente.",
		ORANGEAMULET = "Liberación temporal de la monotonía.",
		YELLOWSTAFF = "El palo está tan retorcido como mi alma.",
		YELLOWGEM = "Me recuerda a mi madre.",
		ORANGEGEM = "Este tipo de cosas solían traerme felicidad.",
		TELEBASE = 
		{
			VALID = "La energía fluye a través de ella.",
			GEMS = "El foco está tan sin vida.",
		},
		GEMSOCKET = 
		{
			VALID = "La gema lo ha enfocado.",
			GEMS = "Parece muy vacío.",
		},
		STAFFLIGHT = "Casi puedo hacer un pequeño sistema solar.",
		
		ABIGAIL_FLOWER = 
		{ 
			GENERIC ="Es bonita.",
			LONG = "Era la flor de mi hermana. Se ha ido muy lejos.",
			MEDIUM = "Siento la presencia de Abigail cada vez más fuerte.",
			SOON = "¡Abigail casi está aquí!",
			HAUNTED_POCKET = "Abigail está lista para jugar, pero necesita un poco de espacio.",
			HAUNTED_GROUND = "Necesito enseñarle a Abigail a jugar.",

		},

        ANCIENT_ALTAR = "Está lleno de los ecos de los muertos.",
        ANCIENT_ALTAR_BROKEN = "Oigo los ecos dolorosos de los muertos.",
        ANCIENT_STATUE = "No es muy atractiva.",

        LICHEN = "¿Cómo se las arregló para crecer así?",
		CUTLICHEN = "Efímero, como la vida.",
		CAVE_BANANA = "Las cáscaras parecen peligrosas.",
		CAVE_BANANA_COOKED = "Es mucho mejor la papilla de plátano caliente.",
		CAVE_BANANA_TREE = "Pobre planta, encerrada lejos del sol.",
		CAVE_BANANA_BURNT = "La muerte y el sufrimiento nunca terminan.",
		ROCKY = "Qué cosas tan horribles han visto.",


		BLUEAMULET = "Un abrazo escalofriantemente familiar.",
		PURPLEAMULET = "Está radiante.",
		TELESTAFF = "Podría escapar si esto fuera más potente.",
		MONKEY = "Vivir sin la carga de la inteligencia debe ser agradable.",
		MONKEYBARREL = "Está sucio.",
		MONSTERLASAGNA = "La maldad cocida sigue siendo maldad, incluso en la lasaña.",
		HOUNDSTOOTH="Sacado desde la raíz.",
		ARMORSNURTLESHELL="Ahora puedo esconderme de mis problemas.",
		BAT="Una criatura de la noche.",
		BATBAT = "Un arma encantada. ¡Qué emocionante!",
		BATWING="Ojalá pudiera volar.",
		BATWING_COOKED="Alguna vez tuvo un gran potencial.",
		BATCAVE= "Están acechando ahí...",
		BEDROLL_FURRY="Voy a envolverme en las pieles de los caídos.",
		BUNNYMAN="Qué vida tan atormentada debe de tener.",
		FLOWER_CAVE="Parece frágil.",
		FLOWER_CAVE_DOUBLE="Parece frágil.",
		FLOWER_CAVE_TRIPLE="Parece frágil.",
		GUANO="El inevitable subproducto de la vida.",
		LANTERN="Ilumina el camino oscuro.",
		LIGHTBULB="Se quema lentamente.",
		MANRABBIT_TAIL="Contiene su esencia peluda.",
		MUSHTREE_TALL  ="These are some strange trees.",
		MUSHTREE_MEDIUM="It looks like a rotting hat.",
		MUSHTREE_SMALL ="Do little gnomes live in these?",
		MUSHTREE_TALL=
		{
            GENERIC = "Hay algunos árboles extraños.",
            BLOOM = "Se está esforzando mucho. ¿Por qué?",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Parece un sombrero en descomposición.",
            BLOOM = "Todos sus esfuerzos han caído a suelo rocoso.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "¿Viven los pequeños gnomos ahí?",
            BLOOM = "Tiene una presencia radiante.",
        },
        MUSHTREE_TALL_WEBBED = "Este es frágil y desdeñoso.",
        SPORE_TALL = "¡Sé libre, pequeño!",
        SPORE_MEDIUM = "¡Sé libre, pequeño!",
        SPORE_SMALL = "¡Sé libre, pequeño!",
        SPORE_TALL_INV = "Tantos han perecido. Pero este está a salvo.",
        SPORE_MEDIUM_INV = "Tantos han perecido. Pero este está a salvo.",
        SPORE_SMALL_INV = "Tantos han perecido. Pero este está a salvo.",

		SLURTLE="Está persiguiendo estúpidamente a las rocas.",
		SLURTLE_SHELLPIECES="Trozos de sueños rotos de una babortuga.",
		SLURTLEHAT="Ciertamente no ayudó a su dueño original.",
		SLURTLEHOLE="Las babortugas salen cuando son muchas.",
		SLURTLESLIME="Brilla con anticipación viscosa.",
		SNURTLE="Esa tiene un caparazón más grande.",
		SPIDER_HIDER="Una araña cobarde.",
		SPIDER_SPITTER="Está masticando algo.",
		BEEMINE_MAXWELL = "The furious creatures appreciate their freedom in retrospect.",
		SPIDERHOLE="Está infestado.",
		SPIDERHOLE_ROCK ="Está infestado.",
		STALAGMITE="La tierra entrega su generosidad.",
		STALAGMITE_FULL="La tierra entrega su generosidad.",
		STALAGMITE_LOW="La tierra entrega su generosidad.",
		STALAGMITE_MED="La tierra entrega su generosidad.",
		STALAGMITE_TALL="La tierra llega hasta arriba.",
		STALAGMITE_TALL_FULL="La tierra llega hasta arriba.",
		STALAGMITE_TALL_LOW="La tierra llega hasta arriba.",
		STALAGMITE_TALL_MED="La tierra llega hasta arriba.",

		TURF_CARPETFLOOR = "Un poco de suelo.",
		TURF_CHECKERFLOOR = "Un poco de suelo.",
		TURF_DIRT = "Un poco de suelo.",
		TURF_FOREST = "Un poco de suelo.",
		TURF_GRASS = "Un poco de suelo.",
		TURF_MARSH = "Un poco de suelo.",
		TURF_ROAD = "Un poco de suelo.",
		TURF_ROCKY = "Un poco de suelo.",
		TURF_SAVANNA = "Un poco de suelo.",
		TURF_WOODFLOOR = "Un poco de suelo.",

		TURF_CAVE="Un poco de suelo.",
		TURF_FUNGUS="Un poco de suelo.",
		TURF_SINKHOLE="Un poco de suelo.",
		TURF_UNDERROCK="Un poco de suelo.",
		TURF_MUD="Un poco de suelo.",

		POWCAKE = "Tendría que estar desesperada.",		
		CAVE_ENTRANCE = "Alguien está tratando de mantener el subsuelo lejos.",
		CAVE_ENTRANCE_RUINS = "Alguien está tratando de mantener el subsuelo lejos.",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "Estoy demasiado ocupada descendiendo en la locura para descender a esa cueva.",
            OPEN = "Un gran mal se esconde debajo de la superficie.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "¿Por qué salir? La luz de aquí complementa mi complexión.",
            OPEN = "La superficie me llama.",
        },

		BOOMERANG = "La muerte regresa al remitente.",
		MAXWELLPHONOGRAPH = "¿Bailaremos una danza macabra?",
		ABIGAIL = "Es mi hermana gemela, Abigail.",
		PIGGUARD = "Este pequeño cerdito parece malo.",
		ADVENTURE_PORTAL = "¿Qué clase de terror tecnológico es este?",
		AMULET = "Me pregunto quién era el dueño de esto.",
		ANIMAL_TRACK = "Señales de la bestia.",
		ARMORGRASS = "Prolongo lo inevitable.",
		ARMORMARBLE = "Podría detener las dagas que apuñalan mi corazón.",
		ARMORWOOD = "Podría demorar lo inevitable un poco más con esto.",
		ARMOR_SANITY = "Una manera perfectamente segura de volverse loco.",
		ASH =
		{
			GENERIC = "Esto es todo lo que queda después de otro hermoso fuego.",
			REMAINS_GLOMMERFLOWER = "¡La flor fue incinerada cuando me teletransporté!",
			REMAINS_EYE_BONE = "¡El hueso con ojo fue incinerado cuando me teletransporté!",
			REMAINS_THINGIE = "Esto era otra cosa, antes de que ardiera...",
		},
		AXE = "Un instrumento para la industria y el asesinato.",
		BABYBEEFALO = "Disfruta de tu juventud. Pronto conocerás los horrores de este mundo.",
		BACKPACK = "Una mochila. Ahora puedo llevar una carga más grande.",
		BACONEGGS = "Un desayuno equilibrado para empezar otro día miserable.",
		BANDAGE = "No hay bálsamo para el dolor de la existencia.",
		BASALT = "Sería inútil tratar de romperlo.",
		BEARDHAIR = "Esto es desagradable.",
		BEDROLL_STRAW = "El sueño es una muerte temporal.",
		BEE =
		{
			GENERIC = "Será mejor que me mantenga alejada de ese aguijón.",
			HELD = "Quédate quieta, pequeña.",
		},
		BEEFALO =
		{
			FOLLOWER = "Me sigue directo a su perdición.",
			GENERIC = "Qué pensamientos tan dementes deben estar detrás de esos ojos.",
			NAKED = "Exhibe ahora su desnudez.",
			SLEEPING = "Dormir, acaso soñar.",
		},
		BEEFALOHAT = "Cubriré mi cabeza.",
		BEEFALOWOOL = "En algún lugar, un beefalo está desnudo y frío.",
		BEEHAT = "Esto me protegerá de esos zumbidos felices. Ah, y de los aguijones.",
		BEEHIVE = "Una miserable colmena de escoria y polen.",
		BEEMINE = "Todavía siguen vivas ahí dentro. Pobrecitas.",
		BERRIES = "Esas bayas son de tarta.",
		BERRIES_COOKED = "Tienen un sabor más equilibrado, pero no durarán mucho tiempo.",
		BERRYBUSH =
		{
			BARREN = "Es estéril.",
			WITHERED = "Ha sucumbido al calor.",
			GENERIC = "¿Un aperitivo, tal vez?",
			PICKED = "Tendré que esperar.",
		},
		BIRDCAGE =
		{
			GENERIC = "Pocos de nosotros podemos ver nuestras jaulas.",
			OCCUPIED = "Está más feliz ahora.",
			SLEEPING = "¿Muerto? No. Solo durmiendo.",
			HUNGRY = "Debe de estar hambriento.",
			STARVING = "El vacío le está comiendo desde dentro.",
			DEAD = "Desprovisto de vida, descansa en pedazos.",
			SKELETON = "Es un... expájaro.",
		},
		BIRDTRAP = "Palos y seda resultaron letales.",
		BIRD_EGG = "Tantas esperanzas destruidas.",
		BIRD_EGG_COOKED = "Ningún pájaro volverá a salir de ahí.",
		BISHOP = "¿Por qué estará rezando?",
		BISHOP_CHARGE_HIT = "Ay...",

		BLOWDART_SLEEP = "Ni siquiera el sueño eterno, solo uno temporal.",
		BLOWDART_PIPE = "Soplo por este extremo y el dolor sale por el otro.",
		BLOWDART_FIRE = "¿Debería quemar el mundo?",
		BLUEGEM = "Azul como... eh... ¿un pájaro triste?",
		BLUEPRINT = "El que dibujó esto está probablemente muerto.",
		BELL_BLUEPRINT = "El que dibujó esto está probablemente muerto.",
		BLUE_CAP = "Un hongo para preservar la monotonía.",
		BLUE_CAP_COOKED = "Todo es maleable.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Huele a humedad.",
			INGROUND = "Yo también me escondería, si pudiera.",
			PICKED = "Cosechado.",
		},
		BOARDS = "Aún más aterradores para los árboles.",
		BONESTEW = "Se murieron. Y entonces los puse en un estofado.",
		BUGNET = "Una cárcel para pequeños insectos.",
		BUSHHAT = "Ya soy prácticamente invisible...",
		BUTTER = "No me esperaba eso.",
		BUTTERFLY =
		{
			GENERIC = "Bonita, pero efímera.",
			HELD = "Tengo su vida en mis manos.",
		},
		BUTTERFLYWINGS = "Ya no puede volar la mariposa.",
		BUTTERFLYMUFFIN = "¡Veamos cómo sales de esta trampa azucarada!",
		CAMPFIRE =
		{
			EMBERS = "La oscuridad se cierne.",
			GENERIC = "¡Tal vez sobreviva a esta noche!",
			HIGH = "¡Una visión del infierno!",
			LOW = "La oscuridad nos invade.",
			NORMAL = "Un fuego.",
			OUT = "Eso no es una buena señal.",
		},
		CANE = "Puedo llegar a ninguna parte más rápido.",
		CARROT = "Es una zanahoria.",
		CARROT_COOKED = "Es una zanahoria que ha pasado por las garras del fuego.",
		CARROT_PLANTED = "Es una zanahoria que está en el suelo.",
		CARROT_SEEDS = "Es una zanahoria que está esperando serlo.",
		CAVE_FERN = "Un toque de color en la oscuridad.",
		CHARCOAL = "Frío, muerto y negro, como mi corazón.",
        CHESSJUNK1 = "Vida artificial muerta y fría.",
        CHESSJUNK2 = "Vida artificial muerta y fría.",
        CHESSJUNK3 = "Vida artificial muerta y fría.",
		CHESTER = "Una bola peluda vacía.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Me está mirando el alma.",
			WAITING = "No está durmiendo sino... esperando.",
		},
		COOKEDMANDRAKE = "Fue una buena muerte. Estarás delicioso.",
		COOKEDMEAT = "La sangre que quedaba se ha cocinado.",
		COOKEDMONSTERMEAT = "La maldad cocida sigue siendo maldad.",
		COOKEDSMALLMEAT = "El fuego la ha purificado.",
		CORN = "Mazorca. Casi como mazurca.",
		CORN_COOKED = "Este maíz no pudo soportar el calor.",
		CORN_SEEDS = "La semilla de la vida, tan pequeña en mi mano.",
		CROW =
		{
			GENERIC = "¡Aparta tu pico de mi corazón!",
			HELD = "Es mío.",
		},
		CUTGRASS = "Me gusta matar cosas pequeñas.",
		CUTREEDS = "Me gusta cortar cosas.",
		CUTSTONE = "El mejor material para crear lápidas.",
		DEADLYFEAST = "Este es mi banquete final.",
		DEERCLOPS = "¡La encarnación de la muerte!",
		DEERCLOPS_EYEBALL =  "Qué horrores debe de haber visto.",
		DEPLETED_GRASS =
		{
			GENERIC = "Los restos de un manojo de hierba.",
		},
		DIRTPILE = "Oh, mira. Más suciedad.",
		DIVININGROD =
		{
			COLD = "La fuente está distante.",
			GENERIC = "Siempre está buscando su mitad perdida.",
			HOT = "¡Algo maligno está aquí!",
			WARM = "La maldad se acerca.",
			WARMER = "Ahora está muy cerca.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "¿Qué es lo que hace esta cosa novedosa?",
			READY = "Todavía necesita una llave grande.",
			UNLOCKED = "¡Vamos a ver lo que puedo encontrar!",
		},
		DRAGONFLY = "Están ardiendo por dentro.",
		LAVASPIT = 
		{
			HOT = "Escupe para arriba.",
			COOL = "Se ha enfriado y huele raro.",
		},
		LAVA_POND = "Puedo tirarme y acabar con todo.",
		LAVAE = "Arde con los fuegos del infierno.",
		LAVAE_PET = 
		{
			STARVING = "Está acercándose a la muerte.",
			HUNGRY = "Está sufriendo los dolores del hambre.",
			CONTENT = "Disfruta de tu felicidad mientras dure, pequeña lavae.",
			GENERIC = "Una chispa de vida iluminando la oscuridad.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "¿Merece la pena poner en juego tu futuro?",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Este huevo está casi tan frío como mi corazón.",
			COMFY = "El huevo está caliente, pero mi corazón sigue frío.",
		},
		LAVAE_TOOTH = "Ciertamente, es un diente.",

		DRAGONFRUIT = "Esto no tiene forma de dragón en absoluto.",
		DRAGONFRUIT_COOKED = "Todavía no es un dragón. Al menos está muerta.",
		DRAGONFRUIT_SEEDS = "Es una semilla. No crecerá ningún dragón.",
		DRAGONPIE = "Bueno, al menos es un pastel ahora.",
		DRUMSTICK = "Da buenos golpes, ¡y es nutritivo!",
		DRUMSTICK_COOKED = "Menos crudo, más sabroso.",
		DUG_BERRYBUSH = "Me gusta cuando están muertos, pero tengo que plantar este.",
		DUG_GRASS = "Me gusta cuando están muertos, pero tengo que plantar este.",
		DUG_MARSH_BUSH = "Me gusta cuando están muertos, pero tengo que plantar este.",
		DUG_SAPLING = "Me gusta cuando están muertos, pero tengo que plantar este.",
		DURIAN = "¡Espinosa y maloliente!",
		DURIAN_COOKED = "¡Menos pinchos, pero sigue siendo maloliente!",
		DURIAN_SEEDS = "Milagrosamente, las semillas no huelen.",
		EARMUFFSHAT = "Su amargo final me protege del amargo frío.",
		EGGPLANT = "Casi tan mortal como una belladona. Casi.",
		EGGPLANT_COOKED = "Cocinar esta belladona la hizo aún menos mortal.",
		EGGPLANT_SEEDS = "Es una semilla de belladona.",
		ACORN = 
		{
		    GENERIC = "Una pequeña vida, acomodada en una muerte frágil.",
		    PLANTED = "Un árbol crecerá pronto.",
		},
		EVERGREEN =
		{
			BURNING = "Está ardiendo brillantemente.",
			BURNT = "Agotado y muerto.",
			CHOPPED = "Todo muere.",
			GENERIC = "La naturaleza es tan aburrida.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Está ardiendo brillantemente.",
			BURNT = "Agotado y muerto.",
			CHOPPED = "Todo muere.",
			GENERIC = "Su ciclo de la vida está terminando.",
		},
		EYEPLANT = "Siguen todos los deseos de su amo.",
		FEATHERHAT = "¡Cuac, cuac!",
		FEATHER_CROW = "Una pluma de cuervo, negra como la oscuridad eterna.",
		FEATHER_ROBIN = "Una pluma de petirrojo, roja como la sangre.",
		FEATHER_ROBIN_WINTER = "Una pluma de pinzón de las nieves, blanca como la luz al final del túnel.",
		FEM_PUPPET = "Me pregunto lo que hizo.",
		FIREFLIES =
		{
			GENERIC = "Un pequeño brillo en la oscuridad.",
			HELD = "Luces diminutas, escondidas del mundo en mi bolsillo.",
		},
		FIREHOUND = "Su disposición es ardiente.",
		FIRESTAFF = "¡Podría hacer arder el mundo!",
		FISH = "Estaba sacudiéndose desesperadamente por su vida. Pobre tonto.",
		FISHINGROD = "Con esto, puedo sacar a los pececitos de la seguridad de su precioso estanque.",
		FISHSTICKS = "Bloques de pescado perfectamente moldeados.",
		FISHTACOS = "Espero que ya no tenga ninguna espina.",
		FISH_MED_COOKED = "Un buen asado pone fin a las sacudidas desesperadas.",
		FISH_MED = "Se ha despojado de su soga terrenal.",
		FISH_COOKED = "Un buen asado pone fin a las sacudidas desesperadas.",
		FLINT = "Una pequeña roca filosa.",
		FLOWER = "Son luminosas y alegres. Puaj.",
		FLOWER_WITHERED = "Este es el destino de todas las cosas.",
		FLOWERHAT = "Pero estoy de luto...",
		FLOWER_EVIL = "Al menos son mejores que las otras flores.",
		FOLIAGE = "Llévame al fuego fatuo.",
		FOOTBALLHAT = "Una cosa muerta para vestirme. Qué bien.",
		FROG =
		{
			DEAD = "La vida es pequeña y corta.",
			GENERIC = "Es pequeña y verrugosa.",
			SLEEPING = "Está dormida.",
		},
		FROGGLEBUNWICH = "Nunca pensé que las ancas de rana pudieran estar tan buenas.",
		FROGLEGS = "Arrancadas directamente de la rana.",
		FROGLEGS_COOKED = "Definitivamente no se doblarán más.",
		FRUITMEDLEY = "Dulce, ácido y en una taza.",
		GEARS = "El interior de un demonio mecánico.",
		GHOST = "¡Se ha levantado de su tumba!",
		GOLDENAXE = "Al menos puedo matar árboles con estilo.",
		GOLDENPICKAXE = "Al menos puedo romper rocas con estilo.",
		GOLDENPITCHFORK = "Al menos puedo labrar la tierra con estilo.",
		GOLDENSHOVEL = "Al menos puedo cavar con estilo.",
		GOLDNUGGET = "Incluso en el purgatorio sigue siendo el más precioso de los metales.",
		GRASS =
		{
			BARREN = "Necesita estiércol.",
			WITHERED = "No podía soportar el calor.",
			BURNING = "Huele raro.",
			GENERIC = "Es sólo un manojo de hierba.",
			PICKED = "Ha sido asesinada.",
		},
		GREEN_CAP = "Este champiñón es decepcionantemente normal.",
		GREEN_CAP_COOKED = "Todo es maleable.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Húmedo.",
			INGROUND = "Yo también me escondería, si pudiera.",
			PICKED = "Cosechado.",
		},
		GUNPOWDER = "Es un sendero oscuro el que recorro.",
		HAMBAT = "La muerte engendra muerte.",
		HAMMER = "Oh, ahora puedo aplastar el mundo.",
		HEALINGSALVE = "La vida trae dolor, el dolor trae vida.",
		HEATROCK =
		{
			FROZEN = "Congelada como mi corazón.",
			COLD = "Solo un trozo de roca moderadamente fría.",
			GENERIC = "Ahí está, solamente ocupando espacio.",
			WARM = "Tan fría y sin vida como las demás rocas.",
			HOT = "Las que arden más brillantes, arden más rápido.",
		},
		HONEY = "Una delicia dulce y fugaz.",
		HONEYCOMB = "Piezas de una colmena, dispersadas.",
		HONEYHAM = "Una dulce salsa para el dulce abrazo de esta criatura.",
		HONEYNUGGETS = "Carne cortada en trozos pequeños. Como mi corazón.",
		HORN = "Suena como si hubiera un beefalo atrapado dentro.",
		HOUND = "¡Atrás, peligroso esbirro del mal!",
		HOUNDBONE = "Los restos de una bestia malvada.",
		HOUNDMOUND = "Hogar de las criaturas más viles.",
		ICEBOX = "Es tan frío como mi corazón.",
		ICEHOUND = "Tiene un corazón frío y muerto.",
		INSANITYROCK =
		{
			ACTIVE = "Me está llamando por mi nombre.",
			INACTIVE = "Es fría y negra.",
		},
		JAMMYPRESERVES = "La cantidad perfecta de mermelada.",
		KABOBS = "Carne, ensartada justo por el centro.",
		KILLERBEE =
		{
			GENERIC = "Una abeja sin conciencia.",
			HELD = "Quédate quieta, pequeña.",
		},
		KNIGHT = "Un caballo frío y desalmado.",
		KOALEFANT_SUMMER = "Una bestia solitaria.",
		KOALEFANT_WINTER = "Se opone a la crueldad de los elementos.",
		KRAMPUS = "Hola, criatura horrenda del inframundo.",
		KRAMPUS_SACK = "Huele a cabra.",
		LEIF = "Una bestia torpe.",
		LEIF_SPARSE = "Una bestia torpe.",
		LIGHTNING_ROD =
		{
			CHARGED = "Incluso este poder se acabará.",
			GENERIC = "Concentra la destrucción.",
		},
		LITTLE_WALRUS = "El ciclo de violencia continúa.",
		LIVINGLOG = "Está gritando silenciosamente siempre.",
		LOCKEDWES = "Atrapado por las estatuas de Maxwell, siempre vivas.",
		LOG = "If trees could talk, they would scream at the sight of this.",
		LOG =
		{
			BURNING = "Just a burning log.",
			GENERIC = "If trees could talk, they would scream at the sight of this.",
		},
		LUREPLANT = "Lo consume todo.",
		LUREPLANTBULB = "La vida continúa.",
		MALE_PUPPET = "Me pregunto lo que hizo.",
		MANDRAKE =
		{
			DEAD = "¡Ay, pobre mandrágora!",
			GENERIC = "La poderosa mandrágora. Debería arrancarla por la noche.",
			PICKED = "¡Adelante, mi esbirro vegetal!",
		},
		MANDRAKESOUP = "Se ha hervido la vida que tenía.",
		MARBLE = "Liso y sin vida.",
		MARBLEPILLAR = "Incluso la piedra no puede soportar la fuerza constante de la decadencia.",
		MARBLETREE = "No hay latidos de vida dentro de este árbol frío.",
		MARSH_BUSH =
		{
			BURNING = "Incluso los pinchos se queman.",
			GENERIC = "Un arbusto que siempre duele.",
			PICKED = "Me ha dolido hacer eso.",
		},
		MARSH_PLANT = "Es una planta.",
		MARSH_TREE =
		{
			BURNING = "Está ardiendo.",
			BURNT = "Negro como mi corazón.",
			CHOPPED = "Sus pinchos no lo protegieron.",
			GENERIC = "Un árbol que solo conoce el dolor.",
		},
		MAXWELL = "Siento una extraña afinidad con él.",
		MAXWELLHEAD = "Seguramente tiene un gusto por lo dramático.",
		MAXWELLLIGHT = "Qué curiosa luz.",
		MAXWELLLOCK = "Parece mágico.",
		MAXWELLTHRONE = "No es exactamente lo que esperaba.",
		MEAT = "Todavía está sangrando.",
		MEATBALLS = "Bolas de carne. Qué emocionante.",
		MEAT_DRIED = "La carne se secó y se volvió deliciosa.",
		MERM = "¡Horrible cosa del pantano!",
		MINERHAT = "¡Iluminación con manos libres!",
		MONSTERMEAT = "Impregnada de maldad.",
		MONSTERMEAT_DRIED = "La carne se ha secado y ha adquirido un sabor extraño.",
		MOSQUITO =
		{
			GENERIC = "Roba la vida de los demás para mantener la suya.",
			HELD = "Puedo sentir su calidez robada.",
		},
		MOSQUITOSACK = "Un saco de sangre arrancado de un mosquito. Me encanta.",
		MOUND =
		{
			DUG = "La tierra ha vomitado sus secretos.",
			GENERIC = "Algún día, me uniré a ti.",
		},
		NIGHTLIGHT = "Misteriosa pero muy hermosa.",
		NIGHTMAREFUEL = "Del sueño de los sueños proviene esta cosa.",
		NIGHTSWORD = "Los sueños llegan a un punto. Uno muy afilado.",
		NITRE = "Aquí reside la insensatez del hombre.",
		ONEMANBAND = "Solía ser muy feliz con instrumentos como estos.",
		PANDORASCHEST = "La vida es un juego de azar.",
		PANFLUTE = "La música es la ventana hacia mi alma vacía.",
		PAPYRUS = "Para documentar mi dolor.",
		PENGUIN = "Todos vestidos con su esmoquin, pero ¿a dónde van?",
		PERD = "¡Estúpido pájaro! ¡Aléjate de mis bayas!",
		PEROGIES = "Una encantadora bolsita de nutrientes.",
		PETALS = "He destruido algo hermoso.",
		PETALS_EVIL = "Están pintados con los colores de mi alma.",
		PICKAXE = "Para que yo pueda penetrar la tierra misma.",
		PIGGYBACK = "Son más útiles muertos.",
		PHLEGM = "La horrible bestia debe de haber estado enferma.",
		PIGKING = "Viva mientras pueda, Su Majestad.",
		PIGMAN =
		{
			DEAD = "Está mejor ahora.",
			FOLLOWER = "Todavía me siento sola.",
			GENERIC = "Son tan distantes.",
			GUARD = "Qué Orwelliano.",
			WEREPIG = "¡Una criatura de la noche!",
		},
		PIGSKIN = "La piel de lo que una vez fue un cerdo.",
		PIGTORCH = "Se apaga en la oscuridad.",
		PINECONE = 
		{
		    GENERIC = "Una pequeña vida, acomodada en una muerte frágil.",
		    PLANTED = "Un árbol crecerá pronto.",
		},
		PITCHFORK = "¡Qué herramienta tan diabólica!",
		PLANTMEAT = "Tiene un olor nauseabundo.",
		PLANTMEAT_COOKED = "Ahora es solo un poco más apetecible.",
		PLANT_NORMAL =
		{
			GENERIC = "Una planta comestible.",
			GROWING = "Sigue creciendo. Yo esperaré.",
			READY = "Está lista para la cosecha.",
			WITHERED = "Le han chupado la vida.",
		},
		POMEGRANATE = "¡Tantos trocitos rojos y jugosos para masticar y aplastar!",
		POMEGRANATE_COOKED = "Caliente, pero no menos complicada.",
		POMEGRANATE_SEEDS = "Esperaba que me diera más semillas que estas.",
		POND = "¿Ofelia? ¿Estás ahí abajo?",
		POOP = "La vida es sangre y esto.",
		SCORCHED_SKELETON = "La llama ha purificado a esta pobre alma infeliz.",
		PUMPKIN = "Es tan grande como el agujero donde está en mi corazón.",
		PUMPKINCOOKIE = "Una... galleta...",
		PUMPKIN_COOKED = "Se ha marchitado un poco por el calor. Eso me gusta.",
		PUMPKIN_LANTERN = "Tú no das tanto miedo.",
		PUMPKIN_SEEDS = "Es una semilla. Emocionante.",
		PURPLEGEM = "Morada como una... cosa morada.",
		RABBIT =
		{
			GENERIC = "Está vagando sin rumbo, ajeno a su destino.",
			HELD = "Está a salvo en mis manos.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Soy demasiado grande para caer por ahí.",
			SPRING = "Está cerrado. Ahora nadie cae por aquí.",
		},
		RATATOUILLE = "Un montón de verduras cocidas. Fascinante.",
		RAZOR = "Es solo para afeitarse.",
		REDGEM = "Roja como la sangre de mi corazón.",
		RED_CAP = "Un champiñón detrás de mi propio corazón.",
		RED_CAP_COOKED = "Todo es maleable.",
		RED_MUSHROOM =
		{
			GENERIC = "Húmedo.",
			INGROUND = "Yo también me escondería, si pudiera.",
			PICKED = "Cosechado.",
		},
		REEDS =
		{
			BURNING = "Pronto serán cenizas.",
			GENERIC = "Es solo un montón de juncos.",
			PICKED = "Los he recogido.",
		},
        RELIC = 
        {
            GENERIC = "Los restos de un mundo ancestral.",
            BROKEN = "Trozos rotos de piedra.",
        },
        RUBBLE = "Broken bits of stone.",
        RUINS_RUBBLE = "Un montón de sueños rotos.",
		RESURRECTIONSTONE = "Una sala inútil.",
		ROBIN =
		{
			GENERIC = "¿Significa eso que la primavera está cerca? Espero que no.",
			HELD = "Le gusta estar atrapado en mi bolsillo.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Vida en las tierras áridas y heladas.",
			HELD = "Es tan suave. Es mi enemigo.",
		},
		ROBOT_PUPPET = "Me pregunto lo que hizo.",
		MOOSE_NESTING_GROUND = "Una cuna de vida. Lo odio.",
		ROCK_LIGHT =
		{
			GENERIC = "Hay un fuego en el vientre de la fosa.",
			OUT = "La lava ha perdido su voluntad de arder...",
			LOW = "Las sombras nos invaden.",
			NORMAL = "La lava está ardiendo.",
		},
		ROCK = "Incluso eso no es permanente.",
		ROCKS = "Algunas rocas pequeñas.",
        ROOK = "¿Una torre? ¿O es un castillo?",
		ROPE = "Este es el camino más fácil para salir de este lugar.",
		ROTTENEGG = "El final de todas las cosas.",
		SANITYROCK =
		{
			ACTIVE = "Está llamándome.",
			INACTIVE = "Incluso este obelisco me ha abandonado.",
		},
		SAPLING =
		{
			BURNING = "Destinado a las llamas.",
			WITHERED = "El calor opresivo acabó con este.",
			GENERIC = "Está intentando crecer.",
			PICKED = "Quizá la próxima vez, retoño.",
		},
		SEEDS = "Vida, o al menos la promesa de ella.",
		SEEDS_COOKED = "He echado su vida por la borda.",
		SEWING_KIT = "Otro instrumento para aplazar la inevitable decadencia.",
		SHOVEL = "¿Qué terribles secretos podría descubrir?",
		SILK = "Tan resbaladiza y elegante.",
		SKELETON = "Envidio tu huida.",
		SKELETON_PLAYER = "Estuvo tan, tan cerca.",
		SKULLCHEST = "Contendrá mi memento mori.",
		SMALLBIRD =
		{
			GENERIC = "Hola, pequeñito.",
			HUNGRY = "¿Estás vacío por dentro?",
			STARVING = "Un agujero negro del que las semillas nunca regresan.",
		},
		SMALLMEAT = "Huele a un poco de miedo.",
		SMALLMEAT_DRIED = "Carne, ahora seca y deliciosa.",
		SPAT = "Debería terminar con su miseria.",
		SPEAR = "Me he convertido en destructora de mundos.",
		SPIDER =
		{
			DEAD = "Nos volveremos a encontrar algún día.",
			GENERIC = "¡Una criatura de la noche!",
			SLEEPING = "El mal está durmiendo.",
		},
		SPIDERDEN = "Un nido de suciedad y vileza.",
		SPIDEREGGSACK = "Un pequeño paquete lleno de muerte y destrucción.",
		SPIDERGLAND = "Incluso muerta, esta bestia causa dolor.",
		SPIDERHAT = "Es hora de mirar hacia el abismo.",
		SPIDERQUEEN = "Es majestuosa aún siendo tan horrible.",
		SPIDER_WARRIOR =
		{
			DEAD = "Qué pena, valiente guerrera.",
			GENERIC = "¡Una guerrera de la noche!",
			SLEEPING = "Tengo que tener cuidado.",
		},
		SPOILED_FOOD = "Con el tiempo, todo se echa a perder.",
		STATUEHARP = "Tal vez estas estatuas me hagan compañía.",
		STATUEMAXWELL = "Me ha traído hasta aquí.",
		STEELWOOL = "No ofrece ninguna esperanza de calidez.",
		STINGER = "Puntiagudo y mortal.",
		STRAWHAT = "Cubriré mi cabeza.",
		STUFFEDEGGPLANT = "Una belladona. Probablemente no está llena de veneno.",
		SUNKBOAT = "¡Un truco cruel!",
		SWEATERVEST = "¡Puedo vestir trozos de cosas muertas en un chaleco!",
		TAFFY = "Nunca imaginé que podría hacer una cosa tan dulce.",
		TALLBIRD = "Libre de las ataduras del cielo.",
		TALLBIRDEGG = "Tan lleno de potencial.",
		TALLBIRDEGG_COOKED = "Todos sus sueños, arrebatados. No está mal con beicon.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Enfriado por la oscuridad.",
			GENERIC = "Un diminuto y frágil ser, luchando por salir a la luz.",
			HOT = "No puede soportar el calor.",
			LONG = "Una vida que pronto comienza es una vida que pronto termina.",
			SHORT = "Falta poco.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Ese huevo representa una nueva vida. Agh.",
			PICKED = "El nido está vacío. Vacante. Estéril. Un hueco.",
		},
		TEENBIRD =
		{
			GENERIC = "¿Me vas a dejar tú también?",
			HUNGRY = "Todos tratamos de llenar el vacío.",
			STARVING = "¡Tu verdadera naturaleza se revela!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "¡Estoy segura de que el próximo mundo será aún más horrible que este!",
			GENERIC = "Nada bueno puede salir de esto.",
			LOCKED = "Todavía está bloqueado.",
			PARTIAL = "¿Está medio construida, o medio destruida?",
		},
		TELEPORTATO_BOX = "Contiene una chispa vital.",
		TELEPORTATO_CRANK = "Parece complicado.",
		TELEPORTATO_POTATO = "¡Qué creación tan horrible!",
		TELEPORTATO_RING = "No tiene bordes afilados.",
		TENTACLE = "¡Largo, delgado y peligroso!",
		TENTACLESPOTS = "Es mejor que no se sepa lo que es esto.",
		TENTACLESPIKE = "Afilado, baboso y peligroso.",
        TENTACLE_PILLAR = "Así que esto es lo que pasa allá abajo.",
        TENTACLE_PILLAR_HOLE = "Regresará, algún día.",
        TENTACLE_PILLAR_ARM = "¡Bebés!",
        TENTACLE_GARDEN = "Este es diferente.",
		TOPHAT = "Un poco de elegancia para ayudar a olvidar la naturaleza ineludible.",
		TORCH = "Un pequeño baluarte contra la noche.",
		TRAP = "Las simples hierbas se han convertido en algo mortal.",
		TRAP_TEETH = "Una dolorosa sorpresa del subsuelo.",
		TRAP_TEETH_MAXWELL = "La muerte llega cuando menos lo esperas.",
		TRINKET_1 = "Perfectamente deformes.",
		TRINKET_10 = "Otra boca que alimentar.",
		TRINKET_11 = "Robot afortunado, nunca ha tenido alma.",
		TRINKET_12 = "Ya no eres tan viscoso, ¿verdad?",
		TRINKET_2 = "Es falso. Solo una tentación, como la muerte.",
		TRINKET_3 = "Si los cuchillos resolvieran la mayoría de mis problemas...",
		TRINKET_4 = "Me llevaría esto al fin del mundo.",
		TRINKET_5 = "Volaría con esto directamente hacia el sol, si fuera más grande.",
		TRINKET_6 = "Una vez llenos de electricidad, han conocido su fin.",
		TRINKET_7 = "Solo un simple juego.",
		TRINKET_8 = "Ojalá pudiera darme un baño.",
		TRINKET_9 = "Botones desconjuntados para una vida desconjuntada.",
		TRUNKVEST_SUMMER = "Piel para cubrir mi piel.",
		TRUNKVEST_WINTER = "Esto calentará mi cuerpo, pero ¿y mi espíritu?",
		TRUNK_COOKED = "Ahora parece aún peor.",
		TRUNK_SUMMER = "Habría preferido las orejas.",
		TRUNK_WINTER = "Separada de su único amigo.",
		TURKEYDINNER = "¿Quién se está pavoneando ahora?",
		BANANAPOP = "Solía comerlos con Abigail...",
		BISQUE = "Nutre el cuerpo, hace pasar hambre al alma...",
		CEVICHE = "Lo único que saboreo es mi tristeza...",
		SEAFOODGUMBO = "Un mar una vez lleno de vida. Ya no.",
		SURFNTURF = "Podría ser peor.",
		SHARKFINSOUP = "Ha probado una huida mortal. Yo la probaré.",
		LOBSTERDINNER = "Su muerte me dará la vida.",
		LOBSTERBISQUE = "Querría una cuchara.",
		JELLYOPOP = "La muerte nos llega a todos. A veces en un palo.",
		CALIFORNIAROLL = "Congrejo, envuelto en una funda de algas.",
		TWIGS = "Arrancadas de la tierra justo en la flor de la vida.",
		UMBRELLA = "Las nubes lloran.",
		WAFFLES = "Son definitivamente gofres.",
		WALL_HAY_ITEM = "Su capacidad defensiva es cuestionable.",
		WALL_STONE = "¿Qué me protegerá de lo que hay adentro?",
		WALL_STONE_ITEM = "Esto no me protegerá de mis demonios internos.",
		WALL_RUINS = "¡Estos no protegieron a los ancestros!",
		WALL_RUINS_ITEM = "¿Están también las piedras encantadas?",
		WALL_WOOD_ITEM = "Troncos agrupados.",
		WALL_MOONROCK = "La luna... me susurra promesas de protección.",
		WALL_MOONROCK_ITEM = "Este regalo del cielo no debe desperdiciarse.",
		WALRUS = "Un anciano del mar.",
		WALRUSHAT = "¿Qué pensamientos febriles sucedieron debajo?",
		WALRUS_CAMP =
		{
			EMPTY = "Si no están ahí, ¿dónde están?",
			GENERIC = "Me temo que este hogar no es feliz.",
		},
		WALRUS_TUSK = "Lo haré rechinar.",
		WARDROBE = 
		{
			GENERIC = "Me recuerda a una historia que solía leer con Abigail.",
            BURNING = "Pronto no será nada más que cenizas.",
			BURNT = "Ahora no me recuerda a nada.",
		},
		WARG = "Un verdadero bastión del mal.",
		WASPHIVE = "Se esconden en su fortaleza de odio.",
		WETGOOP = "Un miserable desorden, igual que la vida.",
		WHIP = "Solo proporciona la ilusión del control.",
		WINTERHAT = "Esto me ayuda a evitar que el frío me invada.",
		WORMHOLE =
		{
			GENERIC = "La vida no siempre tiene sentido.",
			OPEN = "No importa lo que consuma, nunca está satisfecho.",
		},
		ACCOMPLISHMENT_SHRINE = "Nunca me han importado mucho las metáforas.",
		MOONROCKNUGGET = "Ha viajado tan lejos...",
		ROCK_MOON = "Ha viajado tan lejos...",



		------------------------------capy---------------------------------

		AERODYNAMICHAT = "¡Atrevieso el aire!",
		ANTIVENOM = "Una pócima para evitar la enfermedad.",
		ARMOR_LIFEJACKET = "Prefiero una tumba seca, gracias.",
		ARMOR_SNAKESKIN = "Una chaqueta de carne muerta. Moderna.",
		ARMOR_WINDBREAKER = "¡Los zarcillos del viento no podrán cazarme!",
		ARMORLIMESTONE = "Pesada...",
		ARMOROBSIDIAN = "¿Es sensato ponerse un traje de piedra de fuego?",
		ARMORSEASHELL = "Armadura hecha con la casa de bichos muertos.",
		ARMOUREDBOAT = "Un barco al que le pueden dar un par de golpes.",
		BABYOX = "Unos ojos fríos y vacíos...",
		BALLPHIN = "Qué compañero tan alegre. ¿Sabrá que la vida no tiene sentido?",
		BALLPHINPOD = "¿Nadar en grupo evita la soledad de la existencia?",
		BAMBOO = "Palos verdes... a quién le importa...",
		BAMBOOTREE = "A long blade could part you from your life.",
		BERMUDATRIANGLE = "La energía oscura atraviesa estos portales misteriosos...",
		BERRYBUSH2_SNAKE = "¿Un aperitivo, tal vez?",
		BERRYBUSH_SNAKE = "¿Un aperitivo, tal vez?",
		BIOLUMINESCENCE = "¡La vida adopta formas tan curiosas! Y la muerte las reclama a todas.",
		BLOWDART_POISON = "Envía la enfermedad con un susurro.",
		BOAT_INDICATOR = "Where shall I launch my hopeless craft?",
		BOAT_LANTERN = "Para ver la gran nada en la oscuridad de la noche.",
		BOATCANNON = "¡Trae la muerte submarina a la alta mar!",
		BOATREPAIRKIT = "Esto podría salvar un barco de la destrucción. Y a mí con él.",
		BOTTLELANTERN = "La luz de la vida. Atrapada.",
		BURIEDTREASURE = "Cosas de gente muerta.",
		BUSH_VINE = "They look as if they want to choke something.",
		SNAKEDEN = "They look as if they want to choke something.",
		CAPTAINHAT = "No hay alma viviente que ordene al mar...",
		CARGOBOAT = "Esto transporta más basura a ninguna parte.",
		CHIMINEA = "Esto protegerá el fuego de los dedos curiosos del viento.",
		CIRCLINGSEAGULL = "Quédate en el aire, carne voladora. No merece la pena aterrirzar por nada.",
		CLOTHSAIL = "Con una vela en mano conseguiré huir a toda prisa. Pero ¿hacia dónde?",
		COCONADE = "A coconut filled with hot, fiery death.",
		COCONUT = 
		{
		    GENERIC = "¿Qué secretos debe ocultar esta fruta bajo su armadura?",
		    PLANTED = "Esperaba un secreto oscuro.",
		},
		COFFEE = "Oscuro. Amargo...",
		COFFEEBEANS = "Parecen estimulantes.",
		
		COFFEEBUSH = "This plant takes nourishment from fiery death.",
		CORAL = "El mar les da vida, y aun así se estiran para escapar de él.",
		CORALREEF = "El coral crece para escapar del mar.",
		CRAB = "There is soft meat beneath that hard shell.",
		CRABHOLE = "Un hoyo es simplemente una tumba aún por cubrir.",
		CUTLASS = "No sentirá ninguna culpa al matar. No es más que una herramienta.",
		DEAD_SWORDFISH = "Su cara de espada no pudo salvarlo...",
		DEPLETED_BAMBOOTREE = "Se aferra a la vida. Apenas.",
		DEPLETED_BUSH_VINE = "Las vides que estrangulan han sido estranguladas.",
		DOYDOY = "Este pájaro parece demasiado estúpido para estar vivo.",
		DOYDOYBABY = "Qué bonito. Y qué bobo.",
		DOYDOYEGG = "Qué huevo más tonto.",
		
		DOYDOYNEST = "Con cada uno de estos, la isla se vuelve más tonta. Y más carnosa.",
		DUBLOON = "La moneda de los malandrines.",
		DUG_BAMBOOTREE = "¿Te marchitarás o vivirás?",
		DUG_BUSH_VINE = "Plantarte de nuevo sería la verdadera crueldad.",
		DUG_COFFEEBUSH = "¿Quiere regresar a la tierra?",
		EARRING = "Pero dónde está la oreja...",
		FABRIC = "Me pregunto si el bambú encuentra esta nueva forma agradable.",
		FEATHERSAIL = "Esos pájaros bobos seguro que navegan rápido.",
		FIRERAIN = "¡La muerte desde arriba!",
		FIRERAINSHADOW = "Eso no puede ser bueno.",
		FISHINHOLE = "La carne nada y nada en círculos. Ajena a todo.",
		FROG_POISON = "Un lametazo venenoso y esta pesadilla terminará.",
		GASHAT = "Este sombrero me impide respirar la muerte.",
		GOLDENMACHETE = "¡Qué hoja más lujosa para destrozar el bambú!",
		ICEMAKER = "My heart makes ice too.",
		IRONWIND = "Si tengo suerte navegaré hasta el fin del mundo.",
		JELLYFISH = "¿Cómo puede una cosa tan curiosa vivir siquiera?",
		JELLYFISH_COOKED = "Es una especie de gelatina.",
		JELLYFISH_DEAD = "Fue una muerte sin dolor. La bestia no tenía sistema nervioso.",
		JELLYFISH_PLANTED = "La picadura no es mortal. Solo dolorosa.",
		JELLYJERKY = "Tan... dura.",
		JUNGLETREESEED =
        {
            GENERIC = "Rebosa potencial.",
            PLANTED = "Ahora no hay marcha atrás.",
        },
		LAVAPOOL = "¡Este pozo se agita con la ira del volcán!",
		LIMESTONE = "Cuando el coral muere se endurece hasta convertirse en piedra.",
		LIMPETS = "Ellas comen la roca. Yo me las como a ellas.",
		
		LOBSTER = "Esto estaría muy bueno muerto y cubierto de mantequilla.",
		LOBSTERHOLE = "Aquí vive una cena de langosta.",
		LOGRAFT = "Parece pesada, lenta y peligrosa.",
		MACHETE = "Es una espada muy grande.",
		MESSAGEBOTTLE = "El último acto desesperado de un alma condenada. En una botella.",
		MESSAGEBOTTLEEMPTY = "Vacía. Como mi alma.",
		MOSQUITO_POISON = "Como si un chupasangre no fuese ya malo, este te deja enfermo.",
		MUSSEL = "¡No se puedes ocultarte debajo de las olas, carne!",
		MUSSEL_STICK = "Los mejillones se aferran a este palo. Infelices.",
		OBSIDIAN = "Un piedra forjada del fuego.",
		OBSIDIAN_WORKBENCH = "Ah, aquí es donde se forjan los objetos ardientes.",
		OBSIDIANAXE = "Corta y quema.",
		OBSIDIANCOCONADE = "Los hijos del árbol arrasarán el mundo.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "¡No te rindas, llamita!",
			GENERIC = "Una llama para mantener los horres a raya.",
			HIGH = "¡Este fuego arde con pasión!",
			LOW = "Está perdiendo la voluntad de seguir.",
			NORMAL = "Arde con la ira de su creador.",
			OUT = "Será mejor que vuelva a encender esto.",
		},
		OBSIDIANMACHETE = "La hoja corta y quema.",
		SPEAR_OBSIDIAN = "Pinchando con fuego.",
		OBSIDIANSPEARGUN = "Envío fuego accionando un gatillo.",
		OX = "Te pesa mucho la carne. Déjame aligerar tu carga.",
		PACKIM = "No le confiaría un pez, pero tal vez mi basura...",
		PACKIM_FISHBONE = "Una cosa de pez muerta. Parece importante.",
		PALMLEAF = "Apuesto a que esta hoja llora por el árbol caído.",
		PALMTREE =
		{
			BURNING = "Probablemente debería alejarme.",
			BURNT = "Ha adquirido una hermosa tonalidad negra.",
			CHOPPED = "Qué encantadora destrucción.",
			GENERIC = "Su fruto ofrece la vida, pero solo si lo mato.",
		},
		PALMTREE_BURNT = "Ha tenido un final ardiente.",
		PALMTREE_STUMP = "Su tormento de árbol se terminó.",
		PARROT = "¿Son mis oídos, o la cháchara de esta criatura es un monólogo solitario?",
		PEACOCK = "¡Unas plumas tan bonitas que esconden una carne tan sabrosa!",
		PIRATEHAT = "El sombrero de un salvaje asesino. Me gusta.",
		PIRATIHATITATOR = "This is but a step from madness.",
		POISONHOLE = "La tierra eructa muerte.",
		RAFT = "Tal vez si monto sobre las olas me una a mi hermana.",
		ROWBOAT = "¿Me pregunto cuántas leguas me puede transportarr?",
		SAIL = "Aprovéchate del viento y vuela a... ninguna parte.",
		SAND = "Me pregunto si la arena es consciente de su propia insignificancia.",
		SAND_CASTLE = "I suppose this diversion brings some comfort.",
		SANDBAG = "Impiden la ruina. Por un tiempo...",
		SANDHILL = "Parece impermanente.",
		SEAGULL = "Los carroñeros de la tierra y el mar.",
		SEAGULL_WATER = "Por si todo no fuera malo ya, contaminan el aire.",
		SEASACK = "Frena la putrefacción y descomposición.",
		SEASHELL = "Lo que soliera vivir aquí seguramente ya esté muerto.",
		SEATRAP = "¡Venid, criaturas del mar! ¡Disfrutad de un aperitivo!",
		SEAWEED = "Hasta el mar está infestado de malas hierbas.",
		
		SEAWEED_PLANTED = "Una planta suculenta.",
		SHARK_FIN = "Ya no me hará más falta.",
		SHARX = "¡El terror del mar!",
		SLOTMACHINE = "Ah, esto parece una prueba razonable del destino.",
		SNAKE = "Desprovisto de brazos o piernas. Ya también estaría enfadada.",
		SNAKE_FIRE = "Los hijos del volcán. Respiran su fuego.",
		SNAKE_POISON = "Lo único peor que una serpiente es una venenosa.",
		SNAKESKIN = "Ha mudado su piel, con mi ayuda.",
		SNAKESKINHAT = "¡Un sombrero hecho de trofeos obtenidos de entre los muertos!",
		SOLOFISH = "Qué forma de nadar tan grácil. Qué carne tan sabrosa.",
		SPEAR_POISON = "Un pinchazo y darán arcadas.",
		SPEARGUN = "¡Causa muerte desde la distancia!",
		SPEARGUN_POISON = "Cada disparo asesta una sofocante enfermedad.",
		STUNGRAY = "Vuelan para escapar de su propio horror.",
		SUPERTELESCOPE = "Ahora puedo ver mejor la inutilidad de todo.",
		SWORDFISH = "¡Este pez corta la muerte con su cara!",
		TELESCOPE = "Para mirar hacia el horizonte con un anhelo imperdurable.",
		TIGERSHARK = "¡Muerte a rayas naranjas en el agua!",
		TIGERSHARKSHADOW = "¡Peligro!",
		TORNADO = "¡La ira feroz de la naturaleza!",
		TOUCAN = "Canta una canción torturada.",
		TRAWLNET = "Una forma de arrebatar objetos de las garras del mar.",
		TRAWLNETDROPPED = "I wonder what this net pulled from the sea?",
		TRIDENT = "El pueblo que forjó esto lleva mucho tiempo muerto.",
		TRINKET_13 = "Tal vez si bebo esto regresaré con mi hermana.",
		TRINKET_14 = "Si pincho a esta muñeca con una aguja, ¿lo sentiré yo?",
		TRINKET_15 = "Perteneciera a quien perteneciese esto, ya no anda más.",
		TRINKET_16 = "Perteneciera a quien perteneciese esto, ha tenido un mal final.",
		TRINKET_17 = "Quien llevara esto seguro que está muerto.",
		TRINKET_18 = "Un resto de civilización perdida en el mar.",
		TRINKET_19 = "El cerebro del propietario se ha nublado para siempre.",
		TURBINE_BLADES = "Ya no giran.",
		TURF_BEACH = "La arena no es un buen relleno para tumbas.",
		TURF_JUNGLE = "Una superficie con nudos y retorcida.",
		TWISTER = "¡La naturaleza está muy enfadada!",
		VENOMGLAND = "Su muerte ha soltado la cura de su enfermedad.",
		VINE = "Vida rebelde.",
		VOLCANO = "¡La montaña que arroja la muerte a los cielos!",
		VOLCANO_ALTAR = "The will of the volcano flows through this shrine!",
		VOLCANO_ALTAR_BROKEN = "Qué pena. No se pueden forjar más armas de fuego.",
		VOLCANO_EXIT = "¿Debo abandonar este lugar de muerte caliente?",
		VOLCANOSTAFF = "¡El soplo ardiente del volcán está ahora a mis órdenes!",
		WALL_LIMESTONE = "Un muro de cosas muertas para retener la vida.",
		WALL_LIMESTONE_ITEM = "Un muro hecho de coral vivo... Ya no.",
		WHALE_BLUE = "Parece triste.",
		WHALE_CARCASS_BLUE = "Algo así de grande y muerto seguro que apesta.",
		WHALE_CARCASS_WHITE = "Es muy grande. Y muy muerta.",
		WHALE_WHITE = "¡Tiene el odio de la vida ardiendo en sus ojos!",
		WOODLEGS_CAGE = "Por lo menos su alma escapó.",
		VOLCANO_SHRUB = "Una horrible sombra de su yo anterior.",
		ROCK_OBSIDIAN = "¿Quemas al tacto?",
		ROCK_CHARCOAL = "No puedo decir lo que solías ser.",
		DRAGOONDEN = "Corazones crueles habitan en su interior.",

		ARMORCACTUS = "¡Me hace tener tantas espinas por fuera como tengo por dentro!",
		BAMBOOTREE =
		{
			BURNT = "Así sucede.",
			CHOPPED = "He ganado esta ronda.",
			GENERIC = "Puedo doblegarlo a mi voluntad.",
		},
		BEEMINE_MAXWELL = "Las criaturas furiosas de su interior aprecian su libertad en retrospectiva.",
		BIGFISHINGROD = "Os he avisado, criaturas del mar. La muerte acecha sobre vosotras.",
		BLOWDART_FLUP = "¡Ahora cuando dispare a alguien, haré mucho daño!",
		BLUBBER = "La comida perfecta para un bobo grasiento.",
		BLUBBERSUIT = "Perturbador, pero cómodo.",
		BOAT = "Es un barco.",
		BOAT_TORCH = "Qué iluminador.",
		BRAINJELLYHAT = "¿Hace que mi cerebro parezca más grande?",
		BUOY = "Mantente a flote, pequeño amigo.",
		BUSH_VINE =
		{
			BURNT = "Creo que así está mejor.",
			CHOPPED = "Tu sacrificio no será en vano.",
			GENERIC = "Es bastante bonita.",
		},
		COCONADE =
		{
			BURNING = "¡Fuego en el hoyo!",
			GENERIC = "Tengo la muerte explosiva de alguien en mis manos.",
		},
		COCONUT_COOKED = "Un poco dulce.",
		COCONUT_HALVED = "Dos mitades que antes estaban juntas. ¿Dónde estás ahora, Abigail?",
		COFFEEBEANS_COOKED = "¿Quién iba a saber que el deseo de vivir venía en forma de grano?",
		COFFEEBOT = "A mí me gusta el café solo.",
		COFFEEBUSH =
		{
			BARREN = "Me vendría bien un estímulo.",
			GENERIC = "Un regalo en forma de grano de los cielos.",
			PICKED = "Todas las heridas curan a tiempo, pequeño arbusto.",
			WITHERED = "Yo me siento igual.",
		},
		COMPASS =
		{
			E = "Este.",
			GENERIC = "Estoy sin rumbo.",
			N = "Norte.",
			NE = "Nordeste.",
			NW = "Noroeste.",
			S = "Norte. No, espera, sur.",
			SE = "Sureste.",
			SW = "Sudoeste.",
			W = "Oeste.",
		},
		CORAL_BRAIN = "¿Así es como soy yo por dentro?",
		CORAL_BRAIN_ROCK = "Es una planta de aspecto inteligente.",
		CRAB =
		{
			GENERIC = "Esta isla está infestada de crustáceos.",
			HIDDEN = "No puedes esconderte de tus problemas para siempre. Ya lo he intentado.",
		},
		CRATE = "Es solo una caja.",
		DEPLETED_GRASS_WATER = "Se acabó.",
		DEVTOOL = "Tiene un olor fuerte.",
		DEVTOOL_NODEV = "No puedo usar eso.",
		DIVININGRODSTART = "Podría usar esto.",
		DOUBLE_UMBRELLAHAT = "Esto me parece excesivo.",
		DOYDOYEGG_COOKED = "Aún no está extinto, aunque no es por no intentarlo.",
		DOYDOYEGG_CRACKED = "Esto probablemente es una clemencia.",
		DOYDOYFEATHER = "Una mancha de color en un mundo triste.",
		DRAGOON = "Sería una bonita mascota, si no fuera por el tema de los \"asesinatos\".",
		DRAGOONEGG = "Difícil imaginar que esto pueda dar a luz a un monstruo tan horrible.",
		DRAGOONHEART = "Este corazón está tan muerto como el mío, aunque es mucho más caliente.",
		DRAGOONSPIT = "¡Qué asco!",
		DUG_ELEPHANTCACTUS = "¿Tengo que llevarlo?",
		ELEPHANTCACTUS = "Es triste y doloroso.",
		ELEPHANTCACTUS_ACTIVE = "Esta planta no quiere que nadie la toque.",
		ELEPHANTCACTUS_STUMP = "Está escondido debajo.",
		FIREPIT =
		{
			EMBERS = "¡No te rindas, llamita!",
			GENERIC = "Una llama para mantener los horres a raya.",
			HIGH = "¡Este fuego arde con pasión!",
			LOW = "Está perdiendo la voluntad de seguir.",
			NORMAL = "Es agradable.",
			OUT = "Será mejor que vuelva a encender esto.",
		},
		FISH_RAW = "Ha sido decapitado.",
		FISH_RAW_SMALL = "Hay otros peces en el mar. Más grandes, espero.",
		FISH_RAW_SMALL_COOKED = "Me... valdrá... de momento.",
		FLAMEGEYSER = "¡Está caliente!",
		FLOTSAM = "No puedo alcanzarlos.",
		FLUP = "¡Eso son demasiados ojos!",
		FRESHFRUITCREPES = "¿Los hay también a la moda?",
		GRASS_WATER = "Húmedo.",
		HAIL_ICE = "Congelada como mi corazón.",
		HOME = "No es exactamente un material de valla.",
		HOUNDFIRE = "¡Arde!",
		ICEMAKER =
		{
			HIGH = "Está en gran forma.",
			LOW = "Parece un poco deprimido.",
			NORMAL = "Se siente bien.",
			OUT = "Se rindió.",
			VERYLOW = "Sale humo.",
		},
		JUNGLETREE =
		{
			BURNING = "Probablemente debería alejarme.",
			BURNT = "Ha adquirido una hermosa tonalidad negra.",
			CHOPPED = "Qué encantadora destrucción.",
			GENERIC = "Un árbol de la jungla.",
		},
		KNIGHTBOAT = "¡Esa cosa tiene problemas de ira!",
		KRAKEN = "¡Arrodíllate ante mí, bestia asquerosa!",
		KRAKENCHEST = "¿Qué maravillas habrá dentro?",
		KRAKEN_TENTACLE = "Oh, no, un quacken en mis botas.",
		LIMPETROCK =
		{
			GENERIC = "Parecen comestibles... más o menos.",
			PICKED = "La he recogido limpia.",
		},
		LIVINGJUNGLETREE = "Este árbol sencillo es exactamente cómo me siento.",
		LOBSTER_DEAD = "Ha conocido a su creador. He conocido a mi almuerzo.",
		LOBSTER_DEAD_COOKED = "¡Un banquete!",
		LOG =
		{
			BURNING = "Es solo un tronco ardiendo.",
			GENERIC = "Es solo un tronco.",
		},
		LUGGAGECHEST = "Un sistema de almacenamiento muy apuesto.",
		MAGIC_SEAL = "Late con una fuerza desconocida.",
		MAGMAROCK = "Las entrañas de la tierra, enfriadas y listas para la minería.",
		MAGMAROCK_FULL = "Las entrañas de la tierra, enfriadas y listas para la minería.",
		MAGMAROCK_GOLD = "Las entrañas de la tierra, enfriadas y listas para la minería.",
		MAGMAROCK_GOLD_FULL = "Las entrañas de la tierra, enfriadas y listas para la minería.",
		MANDRAKE_COOKED = "Ahora es solo la comida.",
		MANGROVETREE = "Es bastante elegante.",
		MANGROVETREE_BURNT = "Qué pena.",
		MARSH_PLANT_TROPICAL = "Qué brote tan patético.",
		MERMFISHER = "Elogio la dedicación de esta criatura al canibalismo.",
		MERMHOUSE_FISHER = "Qué pintoresco.",
		MONKEYBALL = "Me hace sentir menos sola. Además puedo lanzarla.",
		MONSTERTARTARE = "Tiene buena pinta, sabe horrible.",
		MOSQUITOSACK_YELLOW = "Qué tonalidad más bonita de amarillo vómito.",
		MUSSELBOUILLABAISE = "Se me está haciendo la boca agua de solo mirarlo.",
		MUSSEL_COOKED = "He derrotado a este mejillón.",
		MUSSEL_FARM =
		{
			GENERIC = "A mí no me parecen tan duros.",
			STICKPLANTED = "¡Ja!",
		},
		MYSTERYMEAT = "Qué grotesca.",
		NEEDLESPEAR = "Uno podría acabar con todo con esto.",
		OCTOPUSCHEST = "No parece un lugar fiable para almacenar cosas.",
		OCTOPUSKING = "Envidio su felicidad.",
		OXHAT = "Apuesto.",
		OX_FLUTE = "Para que pueda tocar una melodía y calmar mi atormentado corazón.",
		OX_HORN = "Se ha separado de su dueño.",
		PALMLEAF_HUT = "Un respiro bienvenido.",
		PARROT_PIRATE = "Si le susurra mis secretos, ¿lo mantendría a salvo?",
		PEG_LEG = "Pero ¿dónde está el resto de la persona de palo?",
		PIGTENT = "El lugar donde envuelven a cerdos en mantas.",
		PIKE_SKULL = "Supongo que eligió \"no ser\".",
		PIRATEGHOST = "¿Un futuro amigo de Abigail?",
		PIRATEPACK = "Me debería ayudar a llevar más basura.",
		PIRATIHATITATOR =
		{
			BURNT = "Fuera lo que fuese, ahora está quemado.",
			GENERIC = "No sé lo que es esto.",
		},
		PORTAL_SHIPWRECKED = "Al igual que mi querida hermana, nunca puedo volver.",
		PRIMEAPE = "Su jovialidad es casi entrañable. Casi.",
		PRIMEAPEBARREL = "Parece sucio.",
		RAWLING = "Me habla.",
		REDBARREL = "Esto es un peligro para la seguridad. Bien.",
		RUBBLE = "Esta piedra triturada es inútil.",
		SAIL_STICK = "Es... un palo.",
		SANDBAGSMALL = "Densa y pesada.",
		SANDBAGSMALL_ITEM = "Una bolsa de tierra que puedo llevar.",
		SANDBAG_ITEM = "Parece que está a punto de ocurrir una lesión en la espalda.",
		SAND_CASTLE =
		{
			GENERIC = "Su belleza sucumbirá sin duda a la marea.",
			SAND = "Ojalá moldear las arenas del tiempo fuese tan fácil.",
		},
		SEASHELL_BEACHED = "Chucho le chuza la choza a Concha con ese chuzo... ah, qué más da.",
		SEAWEED_COOKED = "Mejor, pero sigue siendo un alga.",
		SEAWEED_DRIED = "Dura más así. Y sabe mejor también.",
		SHADOWSKITTISH_WATER = "Ostras.",
		SHARKITTEN = "Puedo verme a mí misma envejecer con una casa llena de estos animales.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Huele a... ¿arena para gatos?",
			INACTIVE = "Un montón de arena considerable.",
		},
		SHARK_GILLS = "Ahoa nadie respira a través de ellas.",
		SHARK_TEETHHAT = "Elegante, pero temible.",
		SHIPWRECKED_ENTRANCE = "Más y más curiosa.",
		SHIPWRECKED_EXIT = "Hacia la próxima aventura.",
		SLURPERPELT = "Una bolsa vacía de hambre.",
		SNAKEDEN =
		{
			BURNT = "Creo que así está mejor.",
			CHOPPED = "Tu sacrificio no será en vano.",
			GENERIC = "Es bastante bonita.",
		},
		SNAKEOIL = "Esto me llena de un sentimiento de desconfianza.",
		SNAKESKINSAIL = "Asquerosa, pero eficiente.",
		SPEAR_LAUNCHER = "¿Por qué lanzar una lanza cuando puedes dispararla?",
		SPOILED_FISH = "Adiós, amigo.",
		SUNKEN_BOAT =
		{
			ABANDONED = "¿Estáis todos solos?",
			GENERIC = "Ah, las historias que podría contar este barco.",
		},
		SUNKEN_BOAT_BURNT = "Un final poético.",
		SUNKEN_BOAT_TRINKET_1 = "Yo lo uso como pisapapeles.",
		SUNKEN_BOAT_TRINKET_2 = "¿Qué clase de mente simple se puede divertir con esto?",
		SUNKEN_BOAT_TRINKET_3 = "Está completamente empapado.",
		SUNKEN_BOAT_TRINKET_4 = "No tengo ni idea de lo que es esto.",
		SUNKEN_BOAT_TRINKET_5 = "Qué cliché.",
		SWEETPOTATOSOUFFLE = "Delicado, pero delicioso.",
		SWEET_POTATO = "Dulce. Como yo.",
		SWEET_POTATO_COOKED = "Ojalá mi desesperación supiese la mitad de dulce.",
		SWEET_POTATO_PLANTED = "Esto parece un almuerzo.",
		SWEET_POTATO_SEEDS = "Tal vez puedan dar nueva vida.",
		SWIMMINGHORROR = "¡Necesito poner algo de distancia entre él y yo!",
		TELEPORTATO_SW_BASE = "Le falta algo.",
		TELEPORTATO_SW_BOX = "Parece un poco descabellado.",
		TELEPORTATO_SW_CRANK = "Parece incompleta.",
		TREEGUARD = "Oh... no...",
		TELEPORTATO_SW_POTATO = "¿Qué posible uso podría tener esto?",
		TELEPORTATO_SW_RING = "Este anillo probablemente no es para llevarlo.",
		THATCHPACK = "Siempre he estado destinada a soportar una carga pesada.",
		TIDALPOOL = "Cuando miro en este pozo límpido, sueño que puedo ver a Abigail.",
		TIDAL_PLANT = "Es puntiaguda.",
		TIGEREYE = "Tigre, tigre, ardiendo brillante...",
		TRAWLNETDROPPED =
		{
			GENERIC = "¿Qué criaturas arrebatará al océano?",
			SOON = "Su viaje está a punto de terminar.",
			SOONISH = "Ha iniciado su viaje a las profundidades.",
		},
		TREASURECHEST_TRAP = "De vez en cuando, las cosas me salen bien.",
		TREECLUMP = "¿Lo han colocado de forma intencionada?",
		TRINKET_20 = "Yo lo uso como pisapapeles.",
		TRINKET_21 = "¿Qué clase de mente simple se puede divertir con esto?",
		TRINKET_22 = "Muy de bricolaje.",
		TRINKET_23 = "Qué desafortunado.",
		TROPICAL_FISH = "Es ofensivamente brillante.",
		TUNACAN = "Esto es claramente publicidad falsa.",
		TURF_ASH = "Es solo suelo.",
		TURF_DESERTDIRT = "Es solo suelo.",
		TURF_FUNGUS_GREEN = "Es solo suelo.",
		TURF_FUNGUS_RED = "Es solo suelo.",
		TURF_MAGMAFIELD = "Es solo suelo.",
		TURF_MEADOW = "Es solo suelo.",
		TURF_SNAKESKINFLOOR = "Es solo suelo.",
		TURF_SWAMP = "Es solo suelo.",
		TURF_TIDALMARSH = "Es solo suelo.",
		TURF_VOLCANO = "Es solo suelo.",
		TWISTER_SEAL = "No tiene conciencia de los males de este mundo.",
		VOLCANO_ALTAR =
		{
			GENERIC = "El negocio está cerrado.",
			OPEN = "¡Que comience el sacrificio!",
		},
		VOLCANO_ALTAR_TOWER = "Un bello altar de muerte.",
		WALLYINTRO_DEBRIS = "La nave ha sido arrasada.",
		WATERMELON_SEEDS = "Una forma perfecta para escupirlas.",
		WATERYGRAVE = "No está bien asaltar tumbas para buscar botines.",
		WHALE_BUBBLES = "Parece un pez con problemas de ventosidades.",
		WHALE_TRACK = "¡Jo, una ballena!",
		WILBUR_CROWN = "Los monarcas deben de tener cabezas diminutas.",
		WILBUR_UNLOCK = "Su elegancia no hace nada para enmascarar el olor.",
		WILDBORE = "¿Qué le pasa para estar enfadado?",
		WILDBOREHEAD = "Qué decoración tan preciosa.",
		WILDBOREHOUSE = "Espero que no me inviten a entrar.",
		WIND_CONCH = "Una fuerza de la naturaleza aterradora contenida en una concha delicada.",
		WOODLEGSBOAT = "¡Un navío en condiciones de navegar, si es que alguna vez hubo uno!",
		WOODLEGSHAT = "Alta costura de lobos de mar.",
		WOODLEGSSAIL = "Me encanta el diseño.",
		WOODLEGS_KEY1 = "¿Qué desafortunada alma ha donado sus huesos para esto?",
		WOODLEGS_KEY2 = "Probablemente abre algo bonito.",
		WOODLEGS_KEY3 = "¿Qué abres?",
		WORMHOLE_LIMITED = "Parecen oprimidos.",
		WRECK = "Su tripulación probablemente esté muerta...",
	},
	DESCRIBE_GENERIC = "Es innombrable.",
	DESCRIBE_TOODARK = "¡La oscuridad! ¡Es muy oscura!",
	DESCRIBE_SMOLDERING = "Está a punto de ser devorado por las llamas.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Ni siquiera llegó a ver el mundo.",
	},
}
