return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我會在它熟睡之後給它剃毛。",
			GENERIC = "不值得剃。",
			NOBITS = "但沒東西可剃！",
		},
		STORE =
		{
			GENERIC = "它已經裝滿了東西。",
			NOTALLOWED = "恐怕這個不能放進那裡。",
		},
		RUMMAGE =
        {   
            GENERIC = "如果我都做不到，那就沒人能做到！",   
        },
		COOK =
        {
            GENERIC = "哎！被廚具打敗了！",
            TOOFAR = "我必須縮短我們之間的距離！",
        },
        WRITE =
        {
            GENERIC = "我怕我做不到！",
        },
        GIVE =
        {
            DEAD = "英靈殿有更好的東西。",
            SLEEPING = "睡得真香...晚點再說吧。",
            BUSY = "等它完事了我再試試。",
        },
        CHANGEIN =
        {
            GENERIC = "那是我存放所有我最喜歡的皮草的地方。",
            BURNING = "啊！我的皮草！",
        },
        TEACH =
        {
            KNOWN = "我已經掌握了那些知識。",
            CANTLEARN = "那些知識是神禁止的。",
        },
		REPAIRBOAT =
		{
			GENERIC = "我的船已經翻新過了！",
		},
	},
	ACTIONFAIL_GENERIC = "如果我都做不到，那就沒人能做到。",
	ANNOUNCE_MAGIC_FAIL = "它的魔法變弱了！",
	ANNOUNCE_ADVENTUREFAIL = "返回另一個世界。勝利在望！",
	ANNOUNCE_BEES = "退後，身上有長矛的小生物！",
	ANNOUNCE_BOOMERANG = "趕緊！我必須掌握這種彎曲的武器。",
	ANNOUNCE_CHARLIE = "現身吧！",
	ANNOUNCE_CHARLIE_ATTACK = "懦夫！",
	ANNOUNCE_COLD = "嘶~~~！我的皮衣呢！",
	ANNOUNCE_HOT = "炎炎烈日曬得我疲憊不堪。",
	ANNOUNCE_CRAFTING_FAIL = "我缺少必需的材料。",
	ANNOUNCE_DEERCLOPS = "來了個值得尊敬的對手！",
	ANNOUNCE_DUSK = "太陽正在落下。黑夜快來了。",
	ANNOUNCE_EAT =
	{
		GENERIC = "有肉吃讓我心花怒放！",
		PAINFUL = "哦，我感覺不太好。",
		SPOILED = "啊，還是新鮮的好。",
		STALE = "那肉不新鮮。",
		INVALID = "那不是適合戰士的食物！",
		YUCKY = "那種食物不適合戰士！",
	},
	ANNOUNCE_ENTER_DARK = "夜幕降臨。",
	ANNOUNCE_ENTER_LIGHT = "我踏進了光明之中！",
	ANNOUNCE_FREEDOM = "自由！傳奇繼續！",
	ANNOUNCE_HIGHRESEARCH = "我是個出色的女匠人。",
	ANNOUNCE_HOUNDS = "野獸正在逼近...",
	ANNOUNCE_HUNGRY = "我多想大吃一頓啊！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "噓...那個生物就在附近。",
	ANNOUNCE_HUNT_LOST_TRAIL = "我找不到痕跡了。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "太多泥巴了，無法追蹤。",
	ANNOUNCE_INV_FULL = "我只能帶這麼多東西！",
	ANNOUNCE_KNOCKEDOUT = "嗷，我的頭。",
	ANNOUNCE_LOWRESEARCH = "那沒什麼意思。",
	ANNOUNCE_MOSQUITOS = "滾開，小魔鬼！",
	ANNOUNCE_NODANGERSLEEP = "現在睡覺不安全。使用長矛！",
	ANNOUNCE_NODAYSLEEP = "太陽高掛，繼續旅程！",
	ANNOUNCE_NODAYSLEEP_CAVE = "還沒到睡覺的時間。",
	ANNOUNCE_NOHUNGERSLEEP = "一晚上會餓死我的！要先吃東西。",
	ANNOUNCE_NOSLEEPONFIRE = "我才不會睡在火裡。",
	ANNOUNCE_NODANGERSIESTA = "戰鬥迫在眉睫，沒時間休息了！",
	ANNOUNCE_NONIGHTSIESTA = "不能在月光下打盹。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "感覺這不是該打盹的時候。",
	ANNOUNCE_NOHUNGERSIESTA = "我想先吃點肉。",
	ANNOUNCE_NO_TRAP = "幸好我身輕如燕。",
	ANNOUNCE_PECKED = "走開，好動的小尖嘴！",
	ANNOUNCE_QUAKE = "世界在顫抖！",
	ANNOUNCE_RESEARCH = "知識就是力量。",
	ANNOUNCE_SHELTER = "啊哈！涼棚！",
	ANNOUNCE_THORNS = "啊，我被刺到了！",
	ANNOUNCE_TORCH_OUT = "我的燈快滅了！",
	ANNOUNCE_TRAP_WENT_OFF = "原計劃不是那樣的。",
	ANNOUNCE_UNIMPLEMENTED = "它不屬於這個世界。",
	ANNOUNCE_WORMHOLE = "那是一次草率的的冒險。",
	ANNOUNCE_CANFIX = "\n我能把這個修好。",
	ANNOUNCE_FAN_OUT = "我又失去了一把扇子！",
	ANNOUNCE_ACCOMPLISHMENT = "我現在能回去戰鬥了嗎？",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "勝利！好了，我們走。",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "你需要更多糞便？",
	ANNOUNCE_TOOL_SLIP = "滑溜溜的，真麻煩！",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "我乘閃電而來。",

	ANNOUNCE_DAMP = "對戰鬥來說太滑了。",
	ANNOUNCE_WET = "我是個濕答答的戰士。",
	ANNOUNCE_WETTER = "這算洗澡嗎？",
	ANNOUNCE_SOAKED = "差點淹死我了！",
	
	ANNOUNCE_OTHER_WORLD_PLANT = "這樣的植物在這個地方是長不好的！",

	ANNOUNCE_BOAT_DAMAGED = "我的船受傷了！",
	ANNOUNCE_BOAT_SINKING = "大海將我拉向深淵！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "黑暗的深淵會將我吞沒！",
	ANNOUNCE_BURNT = "哎呀！",
	ANNOUNCE_CRAB_ESCAPE = "它不見了！",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "洋流成了我的主人！",
	ANNOUNCE_MAPWRAP_RETURN = "我終於從迷霧中出來了！",
	ANNOUNCE_MAPWRAP_WARN = "我到了世界的邊緣！",
	ANNOUNCE_MORETREASURE = "今天真是個好日子！",
	ANNOUNCE_OTHER_WORLD_TREASURE = "這是另一塊大陸的地圖。",
	ANNOUNCE_SHARX = "來自海裡的敵人！",
	ANNOUNCE_TRAWL_FULL = "我的網裡收穫驚人。",
	ANNOUNCE_TREASURE = "這張地圖標有寶藏地點！",
	ANNOUNCE_VOLCANO_ERUPT = "想毀滅我？！",
	ANNOUNCE_WAVE_BOOST = "海浪助我前進吧！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "海浪下潛藏著一隻怪物...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "我失去了怪物的蹤跡...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "蹤跡消失在湍急的波浪裡了...",

	BATTLECRY =
	{
		GENERIC = "英靈殿在等著你！",
		PIG = "今晚我要吃豬肉！",
		PREY = "勇敢地戰死吧，弱小的敵人！",
		SPIDER = "蜘蛛，讓你看看我長矛的厲害！",
		SPIDER_WARRIOR = "準備好受死吧！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "至高神會收了你！",
		PIG = "我會回來的，蠢豬！",
		PREY = "這次放過你！",
		SPIDER = "長腿的膽小鬼。",
		SPIDER_WARRIOR = "逃吧，怪物！我會回來的。",
	},

	DESCRIBE =
	{		
		BIGFISHINGROD = "我要誘捕美味的魚肉。",
		BIGFOOT = "不可思議！",
		COFFEEBOT = "太陽底下最好的機器。",
		DEPLETED_GRASS_WATER = "它被徹底打敗了。",
		HOUNDFIRE = "它懷著永恆的熱情在燃燒！",
		INVENTORYGRAVE = "我們英靈殿見吧！",
		INVENTORYMOUND = "我們英靈殿見吧！",
		LIMPETS_COOKED = "盡情享用吧！",
		WOODLEGSBOAT = "我更喜歡長船。",
		WOODLEGSHAT = "跟我的頭盔比起來遜色多了。",
		WOODLEGSSAIL = "一張有點嚇人的床單。",
		GLOMMER = "嚴肅的毛毛球。",
        GLOMMERFLOWER = 
        {
        	GENERIC = "森林裡的奇觀。",
        	DEAD = "它曾是森林裡的奇觀。",
        },
        GLOMMERWINGS = "哦，看看格羅姆給我留下了什麼。",
        GLOMMERFUEL = "這團液體可能有用。",
        BELL = "我更喜歡刀劍交鋒的聲音。",
        STATUEGLOMMER = 
        {	
        	GENERIC = "向眾神致敬的古怪方式。",
        	EMPTY = "我感覺有點被冒犯了。",
        },

		WEBBERSKULL = "他曾勇敢地戰鬥，但他的葬禮不是維京式的。",
		WORMLIGHT = "發光的財寶，我無法抗拒！",
		WORMLIGHT_LESSER = "發光吧！用你所有的力量綻放光芒吧！",
		WORM =
		{
		    PLANT = "我感覺有陷阱。",
		    DIRT = "那些土下面是什麼？",
		    WORM = "來自深淵的蛇形野獸！",
		},
		WORMLIGHT_PLANT = "我感覺有陷阱。",
		MOLE =
		{
			HELD = "可以裝在口袋裡的朋友。",
			UNDERGROUND = "誰在下面？",
			ABOVEGROUND = "它隨心所欲地到處挖洞。",
		},
		MOLEHILL = "有狡猾的東西住在那下面。",
		MOLEHAT = "最好是充分利用動物的每一部分。",

		EEL = "美味的黏滑蛇魚。",
		EEL_COOKED = "烤鰻魚！",
		UNAGI = "沒必要把食物弄得這麼花俏。",
		EYETURRET = "雷神之眼看向了我靈魂的深處。",
		EYETURRET_ITEM = "用於防禦的遠古眼球！",
		MINOTAURHORN = "我能把這個裝在我的頭盔上嗎？",
		MINOTAURCHEST = "戰利品寶箱！",
		THULECITE_PIECES = "看上去像發亮的爆米花。",
		POND_ALGAE = "古老的水藻。",
		GREENSTAFF = "旋轉的綠色能量。",
		POTTEDFERN = "這種東西可以用來做什麼？",

		THULECITE = "這種金屬蘊含著巨大的力量！",
		ARMORRUINS = "適合至高神的盔甲！",
		RUINS_BAT = "勇士之杖！",
		RUINSHAT = "一頂皇冠，對戰鬥很有幫助！",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Nothing stirs.",
			WARN = "It's starting...",
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			NOMAGIC = "The magic slumbers far from here.",
		},
		BISHOP_NIGHTMARE = "小心他爆炸！",
		ROOK_NIGHTMARE = "你嚇唬不了我！",
		KNIGHT_NIGHTMARE = "我不認為我能騎那匹馬。",
		MINOTAUR = "我可是見過大世面的。來決鬥吧！",
		SPIDER_DROPPER = "你真卑鄙！",
		NIGHTMARELIGHT = "它利用來自地下的黑暗能量。",
		NIGHTSTICK = "一把配得上雷神的武器。",
		GREENGEM = "一塊綠寶石。",
		RELIC = "Old bits of a dwelling.",
		RUINS_RUBBLE = "I'm quite crafty. I could repair that.",
		MULTITOOL_AXE_PICKAXE = "勇士的工具！",
		ORANGESTAFF = "魔法瞬移手杖。",
		YELLOWAMULET = "被裝在護符中的星星。",
		GREENAMULET = "改進的綠寶石合成工藝！",
		SLURPERPELT = "I do love furs.",	

		SLURPER = "這個全身是毛的傢伙以為自己是頂帽子！",
		SLURPER_PELT = "我確實喜愛毛皮。",
		SLURPERPELT = "我確實喜愛毛皮。",
		ARMORSLURPER = "它能減輕飢餓造成的痛苦。不錯的毛皮。",
		ORANGEAMULET = "拾取物品從未如此簡單。",
		YELLOWSTAFF = "它能召喚星星！",
		YELLOWGEM = "黃色的漂亮東西。",
		ORANGEGEM = "橙色的石頭。",
		TELEBASE = 
		{
			VALID = "Prepare yourselves for the power of purple!",
			GEMS = "There's still gems missing.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "It's empty.",
		},
		STAFFLIGHT = "看啊！來自至高神的禮物！",
	
        ANCIENT_ALTAR = "這些東西最好能用。",

        ANCIENT_ALTAR_BROKEN = "這東西壞掉了。",

        ANCIENT_STATUE = "帶有神秘氣氛的寶藏。",

        LICHEN = "天藍色的無用植物。",
		CUTLICHEN = "我摘了它。但我不會吃它。",

		CAVE_BANANA = "猴子的食物。",
		CAVE_BANANA_COOKED = "熱的猴子食物。",
		CAVE_BANANA_TREE = "一棵弱不經風的猴子樹。",
		ROCKY = "他也許是一位值得尊敬的戰友。",
		
		COMPASS =
		{
			GENERIC= "無法獲得讀數。",
			N = "北。",
			S = "南。",
			E = "東。",
			W = "西。",
			NE = "東北。",
			SE = "東南。",
			NW = "西北。",
			SW = "西南。",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "魔力正在變強！",
			STEADY = "魔力水平保持穩定。",
			WANING = "它開始撤退了！",
			DAWN = "幾乎沒剩下任何魔力。",
			WARN = "開始了...",
			CALM = "沒有動靜。",
			NOMAGIC = "魔力在遠方沉睡。",
		},

		HOUNDSTOOTH="這是我戰勝敵人的證據。",
		ARMORSNURTLESHELL="某種防護裝備。",
		BAT="暗黑之翼生物的肉。",
		BATBAT = "Winged spear!",
		BATWING="像我頭盔上的翼，只是更多肉。",
		BATWING_COOKED="烤暗黑之翼。",
		BEDROLL_FURRY="豪華毛皮床！",
		BUNNYMAN="我會吃了你。",
		FLOWER_CAVE="它在最黑暗的時刻點亮了夜晚。",
		FLOWER_CAVE_DOUBLE="它在最黑暗的時刻點亮了夜晚。",
		FLOWER_CAVE_TRIPLE="它在最黑暗的時刻點亮了夜晚。",
		GUANO="哼，暗黑之翼生物的糞。",
		LANTERN="在黑暗中使用的燈籠。",
		LIGHTBULB="發光！",
		MANRABBIT_TAIL="戰鬥勝利後得到的毛茸茸的戰利品。",
		MUSHTREE_TALL  ="這是什麼魔法？",
		MUSHTREE_MEDIUM="我喜歡它發出的光。",
		MUSHTREE_SMALL ="我不喜歡蘑菇。",
		RABBITHOUSE=
		{
			GENERIC = "我該拿那麼大的胡蘿蔔怎麼辦？",
			BURNT = "巨型胡蘿蔔，終於擺脫你了。",
		},
		SLURTLE="你的醜怪無可匹敵。",
		SLURTLE_SHELLPIECES="它們被砸得稀巴爛。",
		SLURTLEHAT="可加入我的收藏的新戰鬥頭盔！",
		SLURTLEHOLE="我不會選擇把頭盔掛在這裡。",
		SLURTLESLIME="是的。黏液。",
		SNURTLE="我喜歡這個頭盔。",
		SPIDER_HIDER="我要把你砸扁！",
		SPIDER_SPITTER="這一隻非常容易生氣。",
		SPIDERHOLE="結網，永遠不是個好兆頭。",
		STALAGMITE="洞穴岩石。",
		STALAGMITE_FULL="洞穴岩石。",
		STALAGMITE_LOW="洞穴岩石。",
		STALAGMITE_MED="洞穴岩石。",
		STALAGMITE_TALL="勉強算是塊尖石頭。",
		STALAGMITE_TALL_FULL="勉強算是塊尖石頭。",
		STALAGMITE_TALL_LOW="勉強算是塊尖石頭。",
		STALAGMITE_TALL_MED="勉強算是塊尖石頭。",

		TURF_CARPETFLOOR = "它浸透了戰鬥的鮮血。",
		TURF_CHECKERFLOOR = "高級地板。",
		TURF_DIRT = "一塊戰場。",
		TURF_FOREST = "一塊戰場。",
		TURF_GRASS = "一塊戰場。",
		TURF_MARSH = "一塊戰場。",
		TURF_ROAD = "無論我選擇哪裡，都將踏上戰鬥之路。",
		TURF_ROCKY = "一塊戰場。",
		TURF_SAVANNA = "一塊戰場。",
		TURF_WOODFLOOR = "木製地板，適合生死決鬥的極好地面。",

		TURF_CAVE="一塊戰場。",
		TURF_FUNGUS="一塊戰場。",
		TURF_SINKHOLE="一塊戰場。",
		TURF_UNDERROCK="一塊戰場。",
		TURF_MUD="一塊戰場。",

		POWCAKE = "這到底是什麼鬼東西？",
        CAVE_ENTRANCE = 
        {
            GENERIC="下面有什麼寶藏？",
            OPEN = "向地底世界進軍！",
        },
        CAVE_EXIT = "再次見到廣闊的天空！",
		MAXWELLPHONOGRAPH = "機械女歌手。",
		BOOMERANG = "朝敵人猛擲！",
		PIGGUARD = "看得出來，他已經做好了戰鬥準備。",
		ADVENTURE_PORTAL = "冒險在呼喚我。",
		AMULET = "它是紅色的，一個戰士。就像我一樣！",
		ANIMAL_TRACK = "哦！我喜歡打獵。",
		ARMORGRASS = "草做的護具。堅持不了多久。",
		ARMORMARBLE = "近乎無法穿透！",
		ARMORWOOD = "借來的木質背心。",
		ARMOR_SANITY = "強大，但我發現自己老是會走神...",
		ASH =
		{
			GENERIC = "火焰留下的產物。",
			REMAINS_GLOMMERFLOWER = "那朵花必須留在它原來的世界。",
			REMAINS_EYE_BONE = "眼骨無法傳送到這個世界。",
			REMAINS_THINGIE = "它被燒掉了。不復存在了。",
		},
		AXE = "砍剁和毀滅！",
		BABYBEEFALO = "迷你小野獸。",
		BACKPACK = "可攜式軍械庫。",
		BANDAGE = "治癒我在戰鬥中受的傷。",
		BASALT = "一千個人也打不碎這塊石頭。",
		BATBAT = "翅膀長矛！",
		BEARDHAIR = "瘋子的毛髮。",
		BEDROLL_STRAW = "用來打盹的工具。",
		BEARGER = "野獸還是狂戰士？",
		BEARGERVEST = "我是狂戰士！",
		ICEPACK = "野獸毛皮做成的背包。",
		BEARGER_FUR = "它勇敢地戰鬥了，但被我扒了皮。",
		BEE =
		{
			GENERIC = "蜜蜂勇士！我不知道我是否喜歡它們。",
			HELD = "放鬆點！",
		},
		BEEBOX =
		{
			FULLHONEY = "這就是個蜂蜜寶藏！",
			GENERIC = "蜜蜂戰士居住的甜蜜箱子。",
			NOHONEY = "蜂蜜在哪？",
			SOMEHONEY = "蜂蜜還沒滿。需要耐心。",
			BURNT = "我的蜂巢一片死寂。",
		},
		BEEFALO =
		{
			FOLLOWER = "快點，小寶寶。",
			GENERIC = "古老的長毛野獸！",
			NAKED = "你沒有了毛是不是覺得冷？",
			SLEEPING = "聽起來像是希爾達姨媽。",
		},
		BEEFALOHAT = "這個戴在我頭上肯定很好看，我看得出來。",
		BEEFALOWOOL = "我確實喜歡長毛製品。",
		BEEHAT = "這無疑是我的蜜蜂頭盔。",
		BEEHIVE = "總是嗡嗡叫，總是在密謀。",
		BEEMINE = "聽起來很可疑。",
		BEEMINE_MAXWELL = "小心腳下！",
		BERRIES = "水果。我不喜歡它們。",
		BERRIES_COOKED = "溫暖的紅色糊狀物。",
		BERRYBUSH =
		{
			BARREN = "我應該在它上面放些糞便嗎？",
			WITHERED = "太熱了，無法生長。",
			GENERIC = "水果灌木叢。",
			PICKED = "果子被摘走了。",
		},
		BIRDCAGE =
		{
			GENERIC = "為我的烏鴉做的家！",
			OCCUPIED = "你過得開心嗎？",
			SLEEPING = "做個好夢，烏鴉朋友。",
		},
		BIRDTRAP = "我就是聰明的烏鴉捕手！",
		BIRD_EGG = "蛋蛋。",
		BIRD_EGG_COOKED = "熱鳥蛋。",
		BISHOP = "這傢伙需要狠狠地收拾。",
		BLOWDART_FIRE = "像龍噴火一樣。",
		BLOWDART_SLEEP = "晚安，我的敵人。",
		BLOWDART_PIPE = "拋射武器！",
		BLUEAMULET = "冰冷的飾品。",
		BLUEGEM = "一塊冰藍的藍寶石。",
		BLUEPRINT = "哦，一張地圖！不，等等。不對。",
		BELL_BLUEPRINT = "哦，一張地圖！不，等等。不對。",
		BLUE_CAP = "哼，又一個藍色的。",
		BLUE_CAP_COOKED = "我還是不想吃它。",
		BLUE_MUSHROOM =
		{
			GENERIC = "那就是黴菌，真的。",
			INGROUND = "很好，它藏著呢。",
			PICKED = "我希望它不會再長出來。",
		},
		BOARDS = "爺爺輩的木頭。",
		BOAT = "我是乘那個來這裡的嗎？",
		BONESHARD = "我敵人的一丁點殘骸。",
		BONESTEW = "太好吃了！",
		BUGNET = "捕獲天上飛的昆蟲。",
		BUSHHAT = "適合打獵用。",
		BUTTER = "牛油。放在牛排上好嗎？",
		BUTTERFLY =
		{
			GENERIC = "看著還挺漂亮。",
			HELD = "抓到了！",
		},
		BUTTERFLYMUFFIN = "鬆餅蛋糕，鬆軟可口。",
		BUTTERFLYWINGS = "一個漂亮的紀念品。",
		BUZZARD = "你和我，我們一起大塊吃肉。",
		CACTUS = 
		{
			GENERIC = "它的盔甲當真絕妙。",
			PICKED = "它會長回來的。",
		},
		CACTUS_MEAT_COOKED = "烤尖刺植物肉。",
		CACTUS_MEAT = "尖刺植物的肉。",
		CACTUS_FLOWER = "多肉植物開出的漂亮花朵。",
		COLDFIRE =
		{
			EMBERS = "火快要滅了。",
			GENERIC = "清涼又舒適。",
			HIGH = "火焰在咆哮！",
			LOW = "火在慢慢熄滅。",
			NORMAL = "清涼又舒適。",
			OUT = "火光搖搖曳曳地熄滅了。",
		},
		CAMPFIRE =
		{
			EMBERS = "火快要滅了。",
			GENERIC = "溫暖的火焰，溫暖的薇格弗德。",
			HIGH = "火焰在咆哮！",
			LOW = "火在慢慢熄滅。",
			NORMAL = "溫暖的火焰，溫暖的薇格弗德。",
			OUT = "火光搖搖曳曳地熄滅了。",
		},
		CANE = "把「行走」變成「小跑」。",
		CATCOON = "哦！長毛的可愛肉肉。", 
		CATCOONDEN = 
		{
			GENERIC = "可愛的肉團住在那裡。",
			EMPTY = "她勇敢地戰鬥了。嗚呼，她已升天。",
		},
		CATCOONHAT = "一頂皮帽子！祝福你，可愛的肉。",
		COONTAIL = "可愛肉團的尾巴。",
		CARROT = "蛋白質在哪？",
		CARROT_COOKED = "憂傷的烤胡蘿蔔。",
		CARROT_PLANTED = "根小的蔬菜。",
		CARROT_SEEDS = "微小的自然產物。",
		CAVE_FERN = "來自黑暗時代的植物。",
		CHARCOAL = "火神的戰利品。",
        CHESSJUNK1 = "只是一堆倒下的戰士。",
        CHESSJUNK2 = "更多倒下的機械戰士。",
        CHESSJUNK3 = "這個地方真的應該清理一下。",
		CHESTER = "別擔心，我不會吃了他。",
		CHESTER_EYEBONE =
		{
			GENERIC = "你是誰？",
			WAITING = "眼球累了。",
		},
		COOKEDMANDRAKE = "她絕對死了。",
		COOKEDMEAT = "肉！",
		COOKEDMONSTERMEAT = "怪獸肉排。",
		COOKEDSMALLMEAT = "好吃，好吃，肉做的零食。",
		COOKPOT =
		{
			COOKING_LONG = "等待的時候也許可以做點什麼。",
			COOKING_SHORT = "就快好了！",
			DONE = "看看我們做出了什麼？",
			EMPTY = "裡面什麼也沒有。",
			BURNT = "火焚盡一切。",
		},
		CORN = "像一把劍的蔬菜！",
		CORN_COOKED = "爆米花真香。",
		CORN_SEEDS = "微小的自然產物。",
		CROW =
		{
			GENERIC = "烏鴉老兄！",
			HELD = "我們又在一起了。",
		},
		CUTGRASS = "女工匠最基本的資源。",
		CUTREEDS = "我清掉了所有的蟲子！然後我吃了它們。",
		CUTSTONE = "堅硬的石頭！",
		DEADLYFEAST = "功效最強的大餐。",
		DEERCLOPS = "我的長矛將閃耀萬丈光芒並挑出你的眼珠！",
		DEERCLOPS_EYEBALL = "嗯，我要吃了它嗎？",
		EYEBRELLAHAT = "別讓雨水進入你的眼睛！",
		DEPLETED_GRASS =
		{
			GENERIC = "它可能是一叢草。",
		},
		DEVTOOL = "聞起來像培根！",
		DEVTOOL_NODEV = "我還不夠強大，無法使用它。",
		DIRTPILE = "小土丘。",
		DIVININGROD =
		{
			COLD = "一切都靜悄悄的。",
			GENERIC = "機械獵犬。適合打獵用。",
			HOT = "吹響號角！我們到了！",
			WARM = "我們聞到了氣味！",
			WARMER = "獵犬很興奮。我們正在靠近。",
		},
		DIVININGRODBASE =
		{
			GENERIC = "多麼神秘的廢墟。",
			READY = "似乎少了一件...",
			UNLOCKED = "準備就緒！傳奇繼續！",
		},
		DIVININGRODSTART = "這把神秘的劍感覺很重要。",
		DRAGONFLY = "啊，龍蠅！我們終於見面了！",
		ARMORDRAGONFLY = "讓戰鬥更加火熱的絕佳盔甲。",
		DRAGON_SCALES = "神秘的鱗片。",
		DRAGONFLYCHEST = "這寶箱價值抵得上我的武器。",
		LAVASPIT = 
		{
			HOT = "你的火池不是我的對手！",
			COOL = "現在沒那麼可怕了，不是嗎？",
		},
		DRAGONFRUIT = "非常奇特的果實。",
		DRAGONFRUIT_COOKED = "烤熟的奇異水果。",
		DRAGONFRUIT_SEEDS = "微小的自然產物。",
		DRAGONPIE = "這為什麼不是肉餡餅？肉，我要吃肉！",
		DRUMSTICK = "動物的腿，進我肚子裡。",
		DRUMSTICK_COOKED = "熱的肉！",
		DUG_BERRYBUSH = "我想我會把這個還給大地女神。",
		DUG_GRASS = "我想我會把這個還給大地女神。",
		DUG_MARSH_BUSH = "我想我會把這個還給大地女神。",
		DUG_SAPLING = "我想我會把這個還給大地女神。",
		DURIAN = "聞起來像我的戰靴。",
		DURIAN_COOKED = "我為什麼又做了這個？",
		DURIAN_SEEDS = "微小的自然產物。",
		EARMUFFSHAT = "不錯，非常實用！",
		EGGPLANT = "紫色的，圓圓的。",
		EGGPLANT_COOKED = "弱者的食物。",
		EGGPLANT_SEEDS = "微小的自然產物。",
		DECIDUOUSTREE = 
		{
			BURNING = "那根木頭著火了！",
			BURNT = "火神帶走了它。",
			CHOPPED = "被森林中的勇士所砍倒！",
			POISON = "我得稍微再努點力才能弄到這根柴火。",
			GENERIC = "未來的柴火！",
		},
		ACORN = 
		{
		    GENERIC = "裡面藏著一棵樹。",
		    PLANTED = "茁壯成長吧，小樹苗！",
		},
		ACORN_COOKED = "我把樹寶寶烤了。",
		BIRCHNUTDRAKE = "年輕的樹木戰士！",
		EVERGREEN =
		{
			BURNING = "那根木頭著火了！",
			BURNT = "火神帶走了它。",
			CHOPPED = "被森林中的勇士所砍倒！",
			GENERIC = "在森林裡我感覺就像在家裡一樣。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "那根木頭著火了！",
			BURNT = "火神帶走了它。",
			CHOPPED = "被森林中的勇士所砍倒！",
			GENERIC = "一棵粗壯的樹。",
		},
		EYEPLANT = "別把你的眼珠子對著我，植物！",
		FARMPLOT =
		{
			GENERIC = "我不能種肉，這有什麼意義？",
			GROWING = "它們正在茁壯成長。",
			NEEDSFERTILIZER = "它想要糞便大餐。",
			BURNT = "叫你不長肉！",
		},
		FEATHERHAT = "對戰鬥來說似乎有點花俏。",
		FEATHER_CROW = "烏鴉的標誌！",
		FEATHER_ROBIN = "像我的頭髮一樣紅。",
		FEATHER_ROBIN_WINTER = "冬天的羽毛。",
		FEM_PUPPET = "她在王座上一副不開心的樣子。",
		FIREFLIES =
		{
			GENERIC = "發光的小精靈！",
			HELD = "我握住了光！",
		},
		FIREHOUND = "火犬冷酷無情。",
		FIREPIT =
		{
			EMBERS = "火快要滅了。",
			GENERIC = "溫暖的火焰，溫暖的薇格弗德。",
			HIGH = "火焰在咆哮！",
			LOW = "火在慢慢熄滅。",
			NORMAL = "溫暖的火焰，溫暖的薇格弗德。",
			OUT = "火光搖搖曳曳地熄滅了。",
		},
		COLDFIREPIT =
		{
			EMBERS = "火快要滅了。",
			GENERIC = "清涼又舒適。",
			HIGH = "火焰在咆哮！",
			LOW = "火在慢慢熄滅。",
			NORMAL = "清涼又舒適。",
			OUT = "火光搖搖曳曳地熄滅了。",
		},
		FIRESTAFF = "薇格弗德！火之掌控者！",
		FIRESUPPRESSOR = 
		{	
			ON = "發射器已準備好戰鬥！",
			OFF = "投擲戰士，你該休息了。",
			LOWFUEL = "發射器漸漸變得虛弱和疲勞。",
		},

		FISH = "海裡的肉！",
		FISHINGROD = "我是個無情的女漁夫。",
		FISHSTICKS = "海魚肉條。",
		FISHTACOS = "裹起來的魚肉！",
		FISH_MED = "在英靈殿中安息吧。",
		FISH_MED_COOKED = "開心！",
		FISH_COOKED = "開心！",
		FLINT = "對於長矛製作必不可少。",
		FLOWER = "來自美與愛之神的花朵。",
		FLOWERHAT = "沒有戰鬥價值，但戴在我頭上很漂亮。",
		FLOWER_EVIL = "可怕的邪惡力量污染了這朵花。",
		FOLIAGE = "蕨類植物的集合。",
		FOOTBALLHAT = "用豬皮做成的頭盔。",
		FROG =
		{
			DEAD = "英靈殿不收你這種黏滑的東西。",
			GENERIC = "我希望將來有機會穿上青蛙靴。",
			SLEEPING = "它睡著了。",
		},
		FROGGLEBUNWICH = "大飽口福！",
		FROGLEGS = "充滿了有彈性的蛋白質！",
		FROGLEGS_COOKED = "我喜歡看到骨頭從肉裡穿出來。",
		FRUITMEDLEY = "呃！把它裝進杯子裡也騙不到我。",
		GEARS = "這些東西黏在我的頭盔上也許挺好看。",
		GHOST = "困於兩個世界之間的靈魂。",
		GOLDENAXE = "金子做的工具！",
		GOLDENPICKAXE = "以金謀金。",
		GOLDENPITCHFORK = "我幹嘛把乾草叉弄得這麼花俏？",
		GOLDENSHOVEL = "給國王挖東西用的！",
		GOLDNUGGET = "這個金塊讓我開心。",

		GRASS =
		{
			BARREN = "生命已離它而去。",
			WITHERED = "高溫擊敗了這株植物。",
			BURNING = "火神凝視著你！",
			GENERIC = "那個能派上用場。",
			PICKED = "它倒在我的力量之下。",
		},
		GREEN_CAP = "糟糕！",
		GREEN_CAP_COOKED = "無論有沒有被火燒焦，我都不會讓它碰到我的嘴唇！",
		GREEN_MUSHROOM =
		{
			GENERIC = "它長出來了！",
			INGROUND = "躲起來吧，膽小鬼。",
			PICKED = "我看到了菌類孢子。",
		},
		GUNPOWDER = "巨大的能量！",
		HAMBAT = "適合晚宴大廳的武器！",
		HAMMER = "更適合勞動而不是戰鬥。",
		HEALINGSALVE = "為我補充生命！",
		HEATROCK =
		{
			FROZEN = "冰死我了！",
			COLD = "石頭是冷的！",
			GENERIC = "很有用的石頭！",
			WARM = "石頭是暖的！",
			HOT = "火神會為此感到自豪。",
		},
		HOMESIGN = 
		{
			GENERIC = "位置最恰當的標誌。",
			UNWRITTEN = "我將寫下一個勝利的故事！",
			BURNT = "戰鬥往事的標誌。",
		},
		HONEY = "黏糊糊的十分噁心。",
		HONEYCOMB = "看起來可不怎麼像蜂窩。",
		HONEYHAM = "豐盛的大餐！",
		HONEYNUGGETS = "多肉的塊狀美食！",
		HORN = "真想大戰一場啊。",
		HOUND = "芬里爾的後代！",
		HOUNDBONE = "一個倒下的敵人。",
		HOUNDMOUND = "這些獵犬是真正的戰士。",
		ICEBOX = "冬天住在裡面！",
		ICEHAT = "一大塊寒冰。",
		ICEHOUND = "寒冬之牙！",
		INSANITYROCK =
		{
			ACTIVE = "哇哦！",
			INACTIVE = "這塊石頭沒什麼可疑的。",
		},
		JAMMYPRESERVES = "黏糊糊的十分噁心。",
		KABOBS = "棍子上插滿了肉！太好了！",
		KILLERBEE =
		{
			GENERIC = "挑戰者！",
			HELD = "被征服的敵人。",
		},
		KNIGHT = "我聞到了戰鬥的氣息！",

		KOALEFANT_SUMMER = "親愛的生物...我要吃了你。",
		KOALEFANT_WINTER = "可憐的、沒有戒心的肉獸。",
		KRAMPUS = "你嚇不倒我，羊！",
		KRAMPUS_SACK = "我能把所有東西都裝進去！",
		LEIF = "那是一個古老的林地生物。",
		LEIF_SPARSE = "那是一個古老的林地生物。",
		LIGHTNING_ROD =
		{
			CHARGED = "哦，偉大的閃電！",
			GENERIC = "召喚雷神！",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "我能叫你獨角獸嗎？",
			CHARGED = "閃電把你變成了獨角獸戰士！",
		},
		LIGHTNINGGOATHORN = "這東西可造成持久的打擊。",
		GOATMILK = "這是蘊含強大力量的乳品。",
		LITTLE_WALRUS = "邪惡的長牙海豹的後代。",
		LIVINGLOG = "燒了這樣的魔法生物似乎是一種浪費。",
		LOCKEDWES = "我將拯救你，沉默的凡人！",
		LOG =
		{
			BURNING = "著火的木頭！",
			GENERIC = "木頭總是有用的。",
		},
		LUREPLANT = "終於！找到了一棵有用的蔬菜。",
		LUREPLANTBULB = "也許最終我將成為一個種肉的農夫！",
		MALE_PUPPET = "他在王座上一副不開心的樣子。",
		MANDRAKE =
		{
			DEAD = "蕪菁甘藍的屍體仍保留了它的魔力。",
			GENERIC = "蕪菁甘藍！",
			PICKED = "它只是想開始蕪菁甘藍的冒險。",
		},
		MANDRAKESOUP = "魔法菜餚！",
		MANDRAKE_COOKED = "烤蕪菁甘藍。",
		MARBLE = "勇士之石！",
		MARBLEPILLAR = "適合放在宮殿裡！",
		MARBLETREE = "再大的風也吹不倒這棵樹。",
		MARSH_BUSH =
		{
			BURNING = "好燙的木頭！",
			GENERIC = "一叢站崗的灌木。",
			PICKED = "麻煩的東西。",
		},
		MARSH_PLANT = "池塘邊的植物。",
		MARSH_TREE =
		{
			BURNING = "它著火了！",
			BURNT = "燒焦了。",
			CHOPPED = "我的戰斧總是勝利。",
			GENERIC = "一棵戰士樹。",
		},
		MAXWELL = "啊！那就是我傳奇故事裡的大反派嗎？！",
		MAXWELLHEAD = "我可以看穿他的毛孔。",
		MAXWELLLIGHT = "黑暗魔法於此處留存。",
		MAXWELLLOCK = "我該開啟它嗎？",
		MAXWELLTHRONE = "我更喜歡自由自在地漫遊，我的獨角獸和我。",
		MEAT = "大地的真實果實！",
		MEATBALLS = "好吃的小丸子。",
		MEATRACK =
		{
			DONE = "開吃吧！",
			DRYING = "正是我喜歡的製備方式。",
			DRYINGINRAIN = "下雨對這個沒什麼幫助。",
			GENERIC = "啊！一個可以曬肉的架子！",
			BURNT = "真可惜。",
		},
		MEAT_DRIED = "極好的戰鬥食物供應。",
		MERM = "去死吧，濕膩膩的魚獸！",
		MERMHEAD = 
		{
			GENERIC = "這麼遠我都能聞到它的臭味！",
			BURNT = "被斬首。被焚燒。惡臭。",
		},
		MERMHOUSE = 
		{
			GENERIC = "這屋子是用魚做的嗎？",
			BURNT = "我不會想念它的。",
		},
		MINERHAT = "會發光的頭盔！適合在黑暗中使用。",
		MONKEY = "我不相信他。",
		MONKEYBARREL = "裡面裝著什麼樣的怪物？",
		MONSTERLASAGNA = "怪獸燉菜。",
		FLOWERSALAD = "葉子是用來餵動物的。動物是用來吃的。",
        ICECREAM = "它冰壞了我的牙。",
        WATERMELONICLE = "你藏在冰凍的水果裡騙不到我，棍子。",
        TRAILMIX = "堅果肉不是真正的肉。",
        HOTCHILI = "考驗我的意志力。",
        GUACAMOLE = "好吃，又軟又滑！",
		MONSTERMEAT = "黑暗野獸的肉。",
		MONSTERMEAT_DRIED = "全部乾了。",
		MOOSE = "我希望我能騎著它去戰鬥。",
		MOOSEEGG = "有東西在裡面彈來彈去。",
		MOSSLING = "你還不夠大，當不了我的坐騎。",
		FEATHERFAN = "隨身攜帶的奢華享受。",
		TROPICALFAN = "隨身攜帶的奢華享受。",
		GOOSE_FEATHER = "女戰士值得擁有一張軟床。",
		STAFF_TORNADO = "會帶來痛苦的風暴。",
		MOSQUITO =
		{
			GENERIC = "嗷！這些東西一無所用！",
			HELD = "老實點，狂躁的傢伙！",
		},
		MOSQUITOSACK = "血將使我強大。",
		MOUND =
		{
			DUG = "我想要贓物！",
			GENERIC = "墓碑下面有寶藏嗎？",
		},
		NIGHTLIGHT = "還是在我自己的火旁更自在一些。",
		NIGHTMAREFUEL = "暗黑燃料！",
		NIGHTSWORD = "只有勇敢的戰士才能運用這件武器。",
		NITRE = "它包含易爆成分。",
		ONEMANBAND = "和我一起歌唱！我們是天堂的守護者！",
		PANDORASCHEST = "它包含著一個謎。",
		PANFLUTE = "我更喜歡面對清醒的敵人。",
		PAPYRUS = "用這個來記錄我的傳奇故事。",
		PENGUIN = "大海中的鳥，從遠方來。",
		PERD = "你不可能永遠逃得了！",
		PEROGIES = "肉餃子。",
		PETALS = "感謝福神賜予的禮物！",
		PETALS_EVIL = "這些不是福神創造的。",
		PICKAXE = "我可以用它獲取寶貴的長矛和頭盔材料。",
		PIGGYBACK = "那隻豬光榮戰死，然後把這個背包給了我。",
		PIGHEAD = 
		{	
			GENERIC = "這太殘暴了。",
			BURNT = "一般來說，我喜歡烤肉，但這是不對的。",
		},
		PIGHOUSE =
		{
			FULL = "出來和我一起去戰鬥吧！",
			GENERIC = "我原先不認為豬能建房子。",
			LIGHTSOUT = "你不渴望戰鬥嗎，豬兄？",
			BURNT = "火神今天沒有對你微笑。",
		},
		PIGKING = "那是豬的王？",
		PIGMAN =
		{
			DEAD = "他光榮地戰死了。",
			FOLLOWER = "我們奔向戰鬥！",
			GENERIC = "你會和我並肩作戰嗎，豬兄？",
			GUARD = "那隻豬看上去很勇敢。",
			WEREPIG = "它被芬里爾腐化了。",
		},
		PIGSKIN = "豬的皮。",
		PIGTORCH = "這些豬崇拜火神嗎？",
		PINECONE = 
		{
		    GENERIC = "這顆樹寶寶受到多刺盔甲的良好保護。",
		    PLANTED = "它已經脫掉了盔甲。好好生長吧，小樹苗！",
		},
		PITCHFORK = "農夫的武器。",
		PLANTMEAT = "我覺得它很接近了。",
		PLANTMEAT_COOKED = "還是綠色的，但行了。",
		PLANT_NORMAL =
		{
			GENERIC = "一株植物。",
			GROWING = "我是個女戰士，不是農夫！",
			READY = "呃，蔬菜。我不確定我期望什麼...",
			WITHERED = "被太陽打敗了。",
		},
		POMEGRANATE = "果肉。",
		POMEGRANATE_COOKED = "燒焦的果肉。",
		POMEGRANATE_SEEDS = "微小的自然產物。",
		POND = "有東西潛藏在深處。",
		POOP = "要是我能用它進行偽裝，躲避捕食者的侵襲就好了。",
		FERTILIZER = "它的臭味能讓植物起死回生。",
		PUMPKIN = "至少可以用它給敵人來一記重擊。",
		PUMPKINCOOKIE = "所有的生命精華都被烤出來了。",
		PUMPKIN_COOKED = "橙色的熱糊糊。",
		PUMPKIN_LANTERN = "你想戰鬥嗎，蔬菜？",
		PUMPKIN_SEEDS = "微小的自然產物。",
		PURPLEAMULET = "一塊黑暗力量護符。",
		PURPLEGEM = "霧朦朦的，蘊含神秘的能量。",
		RABBIT =
		{
			GENERIC = "跳進我的嘴裡來！",
			HELD = "你跑不了的！",
		},
		RABBITHOLE = 
		{
			GENERIC = "好戲上演，兔子！",
			SPRING = "對於兔子來說，一定是中場休息時間。",
		},
		RAINOMETER = 
		{	
			GENERIC = "預告雨的到來。",
			BURNT = "它預言的日子結束了。",
		},
		RAINCOAT = "針對雨水的護甲。",
		RAINHAT = "我們將在雨中戰鬥。",
		RATATOUILLE = "一堆蔬菜。不了，謝謝。",
		RAZOR = "小刀片，但也算是把刀。",
		REDGEM = "摸上去很熱。",
		RED_CAP = "不管鮮不鮮，我都不想要它。",
		RED_CAP_COOKED = "我不會吃它，但把它放到火裡很好玩。",
		RED_MUSHROOM =
		{
			GENERIC = "至少它的顏色很漂亮。",
			INGROUND = "永遠別出來！",
			PICKED = "不在了就好。",
		},
		REEDS =
		{
			BURNING = "天堂見，蘆葦！",
			GENERIC = "一些結實的蘆葦。",
			PICKED = "在它最茁壯的時候割下。",
		},
        RELIC = 
        {
            GENERIC = "適合天堂。",
            BROKEN = "它已被敲成碎塊。",
        },
        RUINS_RUBBLE = "它的日子還沒結束。",
        RUBBLE = "一堆古老的岩石。",
		RESEARCHLAB = 
		{	
			GENERIC = "我喜歡戰鬥多過科學。",
			BURNT = "塵歸塵，土歸土。",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "也許科學能提高我的戰鬥技巧。",
			BURNT = "塵歸塵，土歸土。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "一個神秘的東西。",
			BURNT = "它的魔力無法抵抗火焰。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "製造肉的荒誕機器。",
			BURNT = "這裡再也產不出肉了！",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "我不知道為什麼做了這個東西。",
			BURNT = "英靈殿，我來了！",
		},
		RESURRECTIONSTONE = "它能把我從英靈殿拉回來。",
		ROBIN =
		{
			GENERIC = "像血一樣紅。",
			HELD = "我更喜歡你黑色的同胞。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "這隻鳥瞭解寒冷。",
			HELD = "多麼蓬鬆的羽毛。",
		},
		ROBOT_PUPPET = "一個囚犯！",
		ROCK_LIGHT =
		{
			GENERIC = "岩漿殼很堅實。",
			OUT = "看上去很微弱。",
			LOW = "岩漿殼正在重新形成。",
			NORMAL = "美麗的光！",
		},
		ROCK = "打碎！",
		ROCK_ICE = 
		{
			GENERIC = "迷你冰山。",
			MELTED = "可憐的冰山！",
		},
		ROCK_ICE_MELTED = "可憐的冰山！",
		ICE = "讓我想起了家鄉。",
		ROCKS = "一些很普通的石頭。",
        ROOK = "充電！！！！",
		ROPE = "夠結實了，可以用來綁我的船帆。",
		ROTTENEGG = "無法吃了，但在戰鬥中很好用。",
		SANITYROCK =
		{
			ACTIVE = "我不認為我能在戰鬥中打敗這塊石頭。",
			INACTIVE = "聰明的石頭，你無法驚嚇一位勇士！",
		},
		SAPLING =
		{
			BURNING = "不！我的長矛！",
			WITHERED = "在高溫下乾枯了。",
			GENERIC = "我要把它做成長矛。",
			PICKED = "我幹掉了小樹苗！",
		},
		SEEDS = "微小的自然產物。",
		SEEDS_COOKED = "微小的自然產物，給烤死了。",
		SEWING_KIT = "雖然我不是女裁縫，但偶爾也得縫縫補補。",
		SHOVEL = "雖然我更喜歡船葬，但它可能有別的用處。",
		SILK = "可用於縫合東西和記住勝利事跡。",
		SKELETON = "在英靈殿中安息吧。",
		SKELETON_PLAYER = "這場戰鬥還沒有結束。",
		SKULLCHEST = "哦，那是場不錯的戰鬥。",
		SMALLBIRD =
		{
			GENERIC = "你還沒到凶的時候，小鳥。",
			HUNGRY = "你必須吃東西才能變得更強壯。",
			STARVING = "那小鳥看起來餓扁了。",
		},
		SMALLMEAT = "不錯的肉製零食。",
		SMALLMEAT_DRIED = "漫長戰役中的小小慰勞。",
		SPEAR = "它不是我最喜歡的長矛，但也能用。",
		SPIDER =
		{
			DEAD = "被我的長矛打倒，像它之前的眾多敵人一樣。",
			GENERIC = "哪怕你有八條腿也不是我的對手！",
			SLEEPING = "我會等待它醒來與我公平一戰。",
		},
		SPIDERDEN = "從源頭上摧毀它們！",
		SPIDEREGGSACK = "我可以捏碎這些卵，但這樣會錯過更多戰鬥。",
		SPIDERGLAND = "從殺死的蜘蛛腹部摘下。",
		SPIDERHAT = "混入敵營的極佳方式。",
		SPIDERQUEEN = "終於來了，對我能力的真正考驗。",
		SPIDER_WARRIOR =
		{
			DEAD = "薇格弗德再一次獲勝！",
			GENERIC = "蜘蛛捍衛者。戰鬥！",
			SLEEPING = "攻擊睡著的敵人是一種懦弱的行為。",
		},
		SPOILED_FOOD = "時間只是讓這食物變得噁心，而不是更有智慧。",
		STATUEHARP = "那肯定是貢納。蛇拿走了他的腦袋。",
		STATUEMAXWELL = "呸，魔鬼！",
		STINGER = "蜜蜂背上的劍。",
		STRAWHAT = "喧囂戰鬥之後用於冷靜的帽子。",
		STUFFEDEGGPLANT = "在蔬菜裡塞東西並不能把它變成肉。",
		SUNKBOAT = "難怪它會沉。它不是北歐長船。",
		SWEATERVEST = "這件背心雖然挺漂亮，但沒什麼保護效果。",
		REFLECTIVEVEST = "哈！如果太陽穿不透這東西，它就算不上是個勇士。",
		HAWAIIANSHIRT = "花朵阻止不了長矛。",
		TAFFY = "這塊太妃糖的傳奇故事將久久流傳。",
		TALLBIRD = "嚇人的鳥！但我並不害怕。",
		TALLBIRDEGG = "它將成長為一個令人敬畏的對手。",
		TALLBIRDEGG_COOKED = "不是你死就是我亡，小鳥。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "這個蛋在挪威的冬天可活不了。",
			GENERIC = "殺出一條路來，小鳥！",
			HOT = "自火焰中誕生吧！就是別烤死了。",
			LONG = "離這隻鳥誕生還有一段時間。",
			SHORT = "很快它就要看到這個世界。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "裡面潛伏著長羽毛的戰士。",
			PICKED = "年輕的戰鳥即將誕生。",
		},
		TEENBIRD =
		{
			GENERIC = "你還沒有準備好戰鬥，小鳥。",
			HUNGRY = "我希望你喜歡素食...肉是給我吃的。",
			STARVING = "是你選擇和我戰鬥的，小鳥。",
		},
		TELEBASE =
		{
			VALID = "它將利用我極快的速度。",
			GEMS = "它需要紫寶石。",
		},
		GEMSOCKET = 
		{
			VALID = "好戲上演！",
			GEMS = "它缺少寶石。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "上天堂！",
			GENERIC = "通向另一個世界的橋樑。",
			LOCKED = "這橋還不穩定。",
			PARTIAL = "這橋不完整。",
		},
		TELEPORTATO_BOX = "也許裡面隱藏著通向這塊土地的彩虹橋的秘密。",
		TELEPORTATO_CRANK = "一根結實的曲柄。",
		TELEPORTATO_POTATO = "沒天理。金屬物品也要做成蔬菜的樣子。",
		TELEPORTATO_RING = "它的樣子像彩虹橋。",
		TELESTAFF = "我穿越天空和海洋！",
		TENT = 
		{
			GENERIC = "今夜養精蓄銳，為明天的戰鬥做好準備。",
			BURNT = "它被徹底摧毀了。",
		},
		SIESTAHUT = 
		{
			GENERIC = "在這裡讓我因戰鬥而疲倦的腦袋得到休息。",
			BURNT = "它被徹底摧毀了。",
		},
		TENTACLE = "它看起來很兇猛。殺啊！",
		TENTACLESPIKE = "黏黏的，但很危險。我喜歡。",
		TENTACLESPOTS = "一塊堅韌的皮。",
		TENTACLE_PILLAR = "長著觸手的高大敵人。",
		TENTACLE_PILLAR_ARM = "噁心的抓握肢體。",
		TENTACLE_GARDEN = "我要把我的長矛擲向那一大堆觸手！",
		TOPHAT = "它跟我的服裝不搭。",
		TORCH = "夜襲的完美選擇。",
		TRANSISTOR = "科學的成就。",
		TRAP = "一個製作精良的陷阱。我的食物有著落了。",
		TRAP_TEETH = "一個危險的陷阱。",
		TRAP_TEETH_MAXWELL = "浪費了一根埋在土裡的優秀狼牙棒。",
		TREASURECHEST = 
		{
			GENERIC = "當我休息時存放我的頭盔和長矛的地方。",
			BURNT = "箱壁已被火焰燒燬。",
		},
		TREASURECHEST_TRAP = "我隨時準備就緒。",
		TREECLUMP = "一條死路！我必須勇敢戰鬥。",
		TRINKET_1 = "玩具吸引不了像我這樣的偉大戰士。",
		TRINKET_10 = "勝利的象徵。",
		TRINKET_11 = "穿著精良裝甲的戰士。",
		TRINKET_12 = "從醜陋的怪獸身上切下。",
		TRINKET_2 = "我的勝利之歌的伴奏。",
		TRINKET_3 = "就算用我的長矛也打不開這個結。",
		TRINKET_4 = "一個古怪的小人。",
		TRINKET_5 = "它能帶我上天堂嗎？",
		TRINKET_6 = "無用的科技。",
		TRINKET_7 = "沒時間玩了！戰鬥迫在眉睫！",
		TRINKET_8 = "必要時可以充當不錯的武器。",
		TRINKET_9 = "用它們可做不出好的盔甲。",
		TRUNKVEST_SUMMER = "它在冰凍荒原上可不頂用。",
		TRUNKVEST_WINTER = "來自戰敗生物的溫暖毛皮。不錯的服裝。",
		TRUNK_COOKED = "苦戰之後的多汁獎品。",
		TRUNK_SUMMER = "一根結實有力的象鼻，來自被殺死的毛不多的大象。",
		TRUNK_WINTER = "一根結實有力的象鼻，來自被殺死的毛很多的大象。",
		TUMBLEWEED = "逃吧，彈來彈去的膽小鬼！",
		TURKEYDINNER = "一場真正的盛宴。",
		TWIGS = "用來做長矛很好。",
		UMBRELLA = "用打獵戰利品製作的防雨用具。",
		GRASS_UMBRELLA = "我不喜歡花，但我更討厭盔甲被打濕。",
		PALMLEAF_UMBRELLA = "我不喜歡植物，但我更討厭盔甲被打濕。",
		UNIMPLEMENTED = "神秘的遺跡，肯定蘊含著偉大的力量。",
		WAFFLES = "鬆餅不適合即將出戰的勇士！",
		WALL_HAY = 
		{	
			GENERIC = "針對襲擊者的弱小阻礙物。",
			BURNT = "完全沒用了。",
		},
		WALL_HAY_ITEM = "也許我的敵人會在這些乾草中迷路。",
		WALL_STONE = "我的敵人們將在這些石頭上撞得頭破血流。",
		WALL_STONE_ITEM = "用石頭製作的結實的牆。",
		WALL_RUINS = "幾乎無法刺穿。",
		WALL_RUINS_ITEM = "我的堡壘只用最好的牆。",
		WALL_WOOD = 
		{
			GENERIC = "它也許能刺穿敵人。",
			BURNT = "火是木頭的唯一剋星！",
		},
		WALL_WOOD_ITEM = "品質一般的防禦工事。",
		WALRUS = "那些海象牙可以刺穿最好的盔甲。",
		WALRUSHAT = "高地污物！",
		WALRUS_CAMP =
		{
			EMPTY = "他們已踏上了偉大的旅程。",
			GENERIC = "不錯的冬季營地。",
		},
		WALRUS_TUSK = "得自海洋野獸之口。",
		WARG = "是你嗎，芬裡厄？",
		WASPHIVE = "戰鬥蜜蜂！",
		WATERMELON = "它拍起來的聲音挺好聽。",
		WATERMELON_COOKED = "熱的，紅色的，但不會流動。",
		WATERMELONHAT = "幾乎就像戴了塊皮一樣。",
		WETGOOP = "都流出來了。",
		WINTERHAT = "暖和，但不適合戰鬥。",
		WINTEROMETER = 
		{
			GENERIC = "要是能測量戰鬥的熱度就好了。",
			BURNT = "測量裝置被火神幹掉了。",
		},
		WORMHOLE =
		{
			GENERIC = "它是不是會吞掉在戰鬥中倒下的人？",
			OPEN = "它的胃歡迎我。",
		},
		WORMHOLE_LIMITED = "它蒼白而虛弱。",
		ACCOMPLISHMENT_SHRINE = "我的勝利將被銘記！",        
		LIVINGTREE = "一棵生命之樹，但它不是尤德希爾。",
		ICESTAFF = "來自雪神的禮物！",
		WATHGRITHRHAT = "獨角獸的力量是偉大的。",
		SPEAR_WATHGRITHR = "我忠實的戰友！",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		BACONEGGS = "豬和蛋！",
		BANANAPOP = "不知道怎麼的我把它做得更難看了！",
		BISQUE = "這道菜不錯。",
		CEVICHE = "對我來說味道有點怪，但能吃。",
		SEAFOODGUMBO = "女王最適合吃這個。",
		SURFNTURF = "呸！大排檔！",
		SHARKFINSOUP = "太好吃了！",
		LOBSTERDINNER = "我戰勝了我的龍蝦對手。",
		LOBSTERBISQUE = "這才對了嘛。",
		JELLYOPOP = "這些東西能讓我發瘋！",
		CALIFORNIAROLL = "那只是一點點用魚肉做的食物。",

		AERODYNAMICHAT = "戴上它後，我的腦袋可以將風劈開！",
		ANTIVENOM = "我的靜脈中不該有毒液流過！",
		ARMOR_LIFEJACKET = "冒險從無真正的安全可言！",
		ARMOR_SNAKESKIN = "雨被打敗了！",
		ARMOR_WINDBREAKER = "每一步都要做好防風工作！",
		ARMORLIMESTONE = "這麼重量級的盔甲穿在身上讓我覺得很安心。",
		ARMOROBSIDIAN = "現在來戰吧，惡魔們！",
		ARMORSEASHELL = "穿著這個，我應該不會被衝到英靈殿的岸上！",
		ARMOUREDBOAT = "現在這是一艘適合維京人的船了！",
		BABYOX = "When you grow up you will become even more meat, meat.",
		BALLPHIN = "要是打它一下，很可能會被彈開的。",
		BALLPHINPOD = "突擊隊！",
		BAMBOO = "用途廣泛的棍子。",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "這是洛基的玩具嗎？",
		BIOLUMINESCENCE = "這是什麼魔法？",
		BLOWDART_POISON = "遠距離削弱敵人的生命。至高神，請原諒我...",
		BOAT_INDICATOR = "我應該開動我的小艇。",
		BOAT_LANTERN = "看著我，黑暗大海中的邪惡怪物！",
		BOATCANNON = "它會為我消滅敵人！？",
		BOATREPAIRKIT = "最明智的貨物。",
		BOTTLELANTERN = "最奇妙的照明燈。",
		BURIEDTREASURE = "我要走好運了。",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "嗖~砰！",
		CAPTAINHAT = "有角就更好了。",
		CARGOBOAT = "適合長途旅行的船。",
		CHIMINEA = "什麼樣的火會躲在一個洞裡？",
		CIRCLINGSEAGULL = "天空中的不潔之物！",
		CLOTHSAIL = "不錯的船帆。",
		COCONADE = "Fire that can be thrown.",
		COCONUT = 
		{
		    GENERIC = "最硬的水果。",
		    PLANTED = "堅硬的果實長出脆弱的小樹。",
		},
		COFFEE = "味道苦，還會加速脈搏跳動。",
		COFFEEBEANS = "我要喝黑咖啡。",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "大海饋贈的禮物好奇怪。",
		CORALREEF = "又硬又脆的地方，我喜歡。",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "它們是因為羞愧而躲進這個洞裡的嗎？",
		CUTLASS = "哦，用死魚打造的寶劍，我應該帶著敬意使用你。",
		DEAD_SWORDFISH = "去英靈殿吧，勇敢的魚。",
		DEPLETED_BAMBOOTREE = "為你自己贏得一些尊重吧。",
		DEPLETED_BUSH_VINE = "不再相互糾纏了？",
		DOYDOY = "它面對我毫無畏懼！",
		DOYDOYBABY = "我尊敬你，年輕的渡渡鳥戰士。",
		DOYDOYEGG = "這個蛋裡生長著一隻像維京人一樣勇敢的鳥。",
		
		DOYDOYFEATHER = "這根珍貴的羽毛來自一隻倒下的鳥類戰士。",
		DOYDOYNEST = "更多勇敢的鳥將在這個鳥巢裡孵化出來！",
		DUBLOON = "前輩們留下的戰利品！",
		DUG_BAMBOOTREE = "如果我種下你，你會報答我嗎？",
		DUG_BERRYBUSH2 = "我自己的漿果來源！",
		DUG_BUSH_VINE = "繼續做籐蔓，還是不做？",
		DUG_COFFEEBUSH = "咖啡打包。",
		EARRING = "這不是我耳朵上的。",
		FABRIC = "縫縫補補不是勇士做的事...",
		FEATHERSAIL = "勇敢的鳥將它們輕快的羽毛賜給了我！",
		FIRERAIN = "屬於真正勇士的天氣！",
		FIRERAINSHADOW = "至高神發怒了！",
		FISHINHOLE = "想要投降嗎，魚兒？",
		FROG_POISON = "滾開，會帶來禍害的邪惡爬行動物！",
		GASHAT = "保護鼻子和咽喉的護甲！",
		GOLDENMACHETE = "我應該自豪地揮舞著你。",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "裝上這個，簡直就像騎著至高神的戰馬在馳騁！",
		JELLYFISH = "You are much too small to be a sea monster.",
		JELLYFISH_COOKED = "這個海怪烤熟之後味道不錯！",
		JELLYFISH_DEAD = "這隻海怪已經去了英靈殿！",
		JELLYFISH_PLANTED = "I expected sea monsters to be bigger.",
		JELLYJERKY = "要嚼爛你可不容易。",
		JUNGLETREE = "A mighty tree!",
		JUNGLETREE_BURNT = "再見了，巨人。",
		JUNGLETREE_STUMP = "英靈殿見吧，大樹。",
		JUNGLETREESEED =
        {
            GENERIC = "這顆種子裡濃縮了樹的力量。",
            PLANTED = "它將有力地成長。",
        },
		LAVAPOOL = "一灘火！",
		LIMESTONE = "硬得跟沒熟的果子似的。",
		LIMPETS = "長在石頭上的肉！",
		
		LOBSTER = "海洋居民，你全副武裝是要上戰場嗎？",
		LOBSTERHOLE = "那些穿著盔甲的傢伙就住在這裡...",
		LOGRAFT = "雖然你不能載我太遠，但至少可以載我一程。",
		MACHETE = "長度適中的刀。",
		MESSAGEBOTTLE = "來自英靈殿的訊息？",
		MESSAGEBOTTLEEMPTY = "裡面既沒有小紙條也沒有喝的東西，真遺憾。",
		MOSQUITO_POISON = "有毒！小人的作為！",
		MUSSEL = "你看起來不夠強悍。",
		MUSSEL_STICK = "愚蠢的貽貝應該會爬上這根棒子。",
		OBSIDIAN = "來自火山的卵石！",
		OBSIDIAN_WORKBENCH = "火的熔爐！",
		OBSIDIANAXE = "現在這是一把斧頭！",
		OBSIDIANCOCONADE = "扔燃燒彈是懦夫的行徑，但很有趣！",
		OBSIDIANFIREPIT =
		{
			EMBERS = "火快要滅了。",
			GENERIC = "一堆適合維京人的營火！",
			HIGH = "火焰在咆哮！",
			LOW = "火在慢慢熄滅。",
			NORMAL = "溫暖的火焰，溫暖的薇格弗德。",
			OUT = "火光搖搖曳曳地熄滅了。",
		},
		OBSIDIANMACHETE = "一把砍劈的工具。一把點火的工具。",
		SPEAR_OBSIDIAN = "我感覺到它的熱力了。",
		OBSIDIANSPEARGUN = "我平時更喜歡近距離放火。",
		OX = "感謝至高神賜予這頭有蹄的豐盛大餐！",
		PACKIM = "你會跟著我去英靈殿嗎？",
		PACKIM_FISHBONE = "古怪的小玩意。",
		PALMLEAF = "維京人大小的樹葉！",
		PALMTREE =
		{
			BURNING = "那根木頭著火了！",
			BURNT = "火神帶走了它。",
			CHOPPED = "被森林中的勇士所砍倒！",
			GENERIC = "大樹，你放棄了樹枝嗎？",
		},
		PALMTREE_BURNT = "我聞到了椰子燒焦的味道。",
		PALMTREE_STUMP = "在英靈殿，你將成為灶台的燃料。",
		PARROT = "閉嘴，你這隻鳥！",
		PEACOCK = "毀掉這些羽毛真是罪過，肉團。",
		PIRATEHAT = "這頂帽子攪亂了我的角色...我是指，我的靈魂。",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "地面噴著毒氣！",
		RAFT = "維京人不怕濕水！",
		ROWBOAT = "我天生就會划船。",
		SAIL = "奇怪的船帆，但應該有用。",
		SAND = "你是非常乾淨的塵土。",
		SAND_CASTLE = "A scale model of my future keep.",
		SANDBAG = "沙袋。",
		SANDBAG_ITEM = "擋住大水。",
		SANDHILL = "我不會用沙堆堆出一座山的。",
		SEAGULL = "骯髒的鳥！",
		SEAGULL_WATER = "你弄髒了你生存的這片水域！",
		SEASACK = "雖然噁心，但保鮮作用不錯。",
		SEASHELL = "來自海洋的貨幣。",
		SEASHELL_BEACHED = "一枚小小的精靈盾牌？",
		SEATRAP = "給我帶來海洋的戰利品吧！",
		SEAWEED = "水生植物真骯髒！",
		
		SEAWEED_PLANTED = "我沒辦法用靴子踩踏的野草。",
		SHARK_FIN = "倒下的戰士留下的紀念品。",
		SHARX = "啊，值得一戰的海洋對手！",
		SLOTMACHINE = "決定命運悲喜的機器。",
		SNAKE = "絕不要相信那些滑行生物。",
		SNAKE_FIRE = "它們能噴出火山之火！",
		SNAKE_POISON = "別想用你的毒牙咬我！",
		SNAKESKIN = "蛇脫掉了它的皮，不過是在外力的作用下...",
		SNAKESKINHAT = "我該把蛇戴在頭上嗎？",
		SOLOFISH = "似乎大海在請我吃大餐。",
		SPEAR_POISON = "這根長矛可以給懦夫帶來勝利。",
		SPEARGUN = "膽小鬼用的武器。",
		SPEARGUN_POISON = "我才不是那種用下流陰險手段的人！對嗎？",
		SPOILED_FISH = "你聞起來充滿了腐敗的氣味。",
		STUNGRAY = "臭魚，你們沒有尊嚴嗎？",
		SUPERTELESCOPE = "至高神將他的眼睛借給了我！",
		SWORDFISH = "我很鍾意這條魚！",
		TELESCOPE = "這是什麼招數？",
		TIGERSHARK = "來自海洋的魔鬼，帶我去英靈殿吧！",
		TIGERSHARKSHADOW = "怪獸的影子！",
		TORNADO = "風發怒了！",
		TOUCAN = "來跟我一戰吧，長嘴鳥！我們應該在英靈殿共進晚餐！",
		TRAWLNET = "我要將大海搜刮一空！",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "神的武器！",
		TRINKET_13 = "這是什麼古怪的蜂蜜酒？",
		TRINKET_14 = "是小寶寶的玩具，還是...？",
		TRINKET_15 = "擾亂人心的武器。",
		TRINKET_16 = "一小片盔甲？",
		TRINKET_17 = "一名戰士光腳走向了英靈殿...",
		TRINKET_18 = "我不認識這種工藝。",
		TRINKET_19 = "對於正義的勇士來說，總是一片晴空。",
		TURBINE_BLADES = "這是哪種奇怪的刀劍？",
		TURF_BEACH = "沙流過趾間的感覺很舒服。",
		TURF_JUNGLE = "在這裡面你會迷路的...",
		TWISTER = "你躲在風下面，壞蛋！",
		VENOMGLAND = "引起發燒的根源。",
		VINE = "你對我有什麼用？",
		VOLCANO = "一座火山！",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "一個武器熔爐被毫無意義地毀掉了...",
		VOLCANO_EXIT = "我受夠了這地獄般的地方。",
		VOLCANOSTAFF = "召喚火山之怒！",
		WALL_LIMESTONE = "做得不錯。",
		WALL_LIMESTONE_ITEM = "你會和我並肩作戰嗎？",
		WHALE_BLUE = "我將終結你的憂鬱，巨型怪！",
		WHALE_CARCASS_BLUE = "我會在英靈殿向你敬酒。",
		WHALE_CARCASS_WHITE = "天哪，好臭！",
		WHALE_WHITE = "幹掉你是一種榮譽。",
		NEEDLESPEAR = "這真是絕妙的戰矛！",
		ARMORCACTUS = "它將使我成為仙人掌的朋友。",
		BAMBOOTREE =
		{
			BURNT = "你的空心巫術沒能阻止你被燒掉。",
			CHOPPED = "你不能砍它！",
			GENERIC = "這是什麼巫術？空心的木頭？",
		},
		BLOWDART_FLUP = "鬼鬼祟祟的可憐生物掉落的武器，只有膽小鬼才會用它。",
		BLUBBER = "我的族人對它視若珍寶！",
		BLUBBERSUIT = "別妄想打濕我的鯨脂衣！",
		BOAT_TORCH = "夜晚的海被點亮了！",
		BRAINJELLYHAT = "我的腦袋和我的劍一樣好使！",
		BUOY = "在海上看到它讓我精神大振。",
		BUSH_VINE =
		{
			BURNT = "它燒燬了。攀附著它已經沒有意義了。",
			CHOPPED = "它需要修剪一下。",
			GENERIC = "這叢植物像戴過帽子後的髮型一樣亂。",
		},
		COCONADE =
		{
			BURNING = "這個椰子很快要噴火了！",
			GENERIC = "這不是尋常的椰子！",
		},
		COCONUT_COOKED = "我要盡情享用這個大椰子。",
		COCONUT_HALVED = "我劈開了這個椰子，看到了它裡面的樣子！",
		COFFEEBEANS_COOKED = "它聞起來十分提神。",
		COFFEEBUSH =
		{
			BARREN = "你抗爭過嗎？",
			GENERIC = "上面長著奇怪的火山果實。",
			PICKED = "它會重新長出果實。",
			WITHERED = "虛弱的植物！",
		},
		CORAL_BRAIN = "我吃掉它的話會學到它掌握的知識嗎？",
		CORAL_BRAIN_ROCK = "長在水中的無所不知的神秘石頭！",
		CRAB =
		{
			GENERIC = "來決鬥吧，穿著盔甲的傢伙！",
			HIDDEN = "給我出來，膽小鬼！",
		},
		CRATE = "交出你的秘密吧，箱子！",
		DOUBLE_UMBRELLAHAT = "這是哪種奇怪頭盔？",
		DOYDOYEGG_COOKED = "這是那隻大膽的鳥送給我的，我要吃掉它。",
		DOYDOYEGG_CRACKED = "它的大膽無畏流露出來了。",
		DRAGOON = "滿肚子火的狂暴戰士！",
		DRAGOONDEN = "這裡一定住著一位狂暴戰士。",
		DRAGOONEGG = "我可以聽見裡面有一顆戰士的心在跳動！",
		DRAGOONHEART = "倒下的敵人給我的禮物！",
		DRAGOONSPIT = "我希望我可以噴火...",
		DUG_ELEPHANTCACTUS = "我直說了。你現在屬於我了。",
		ELEPHANTCACTUS = "我感覺這株植物體內住著狂暴戰士的靈魂。",
		ELEPHANTCACTUS_ACTIVE = "大地上終於長出了一個值得較量的對手！",
		ELEPHANTCACTUS_STUMP = "懦夫！",
		FISH_RAW = "這塊海鮮肉可以讓我好好享用一番。",
		FISH_RAW_SMALL = "這塊海鮮肉可以讓我好好享用一番。",
		FISH_RAW_SMALL_COOKED = "這塊肉會在我的肚子裡游泳！",
		FLAMEGEYSER = "地面噴火了！",
		FLOTSAM = "我必須把它從海裡打撈上來才能知道它的秘密。",
		FLUP = "你這個潛伏在泥裡的膽小鬼！",
		FRESHFRUITCREPES = "鬆軟可口！",
		GRASS_WATER = "我可以從長船上摘的草！",
		HAIL_ICE = "天上在落冰雹！",
		HOME = "一定有人住在這裡。",
		ICEMAKER =
		{
			HIGH = "這台機器火力十足！",
			LOW = "它吐出的冰塊明顯變少了。",
			NORMAL = "用火製出的冰！",
			OUT = "火需要再旺點！",
			VERYLOW = "火快要熄了。",
		},
		JUNGLETREE =
		{
			BURNING = "樹在燃燒。",
			BURNT = "這棵樹已經不復存在了。",
			CHOPPED = "這棵樹很強壯，但我的斧頭更強。",
			GENERIC = "在我們那兒沒有這樣的樹。",
		},
		KNIGHTBOAT = "我的長船讓我更快上戰場！",
		KRAKEN = "我會把你送回地獄！",
		KRAKENCHEST = "戰利品！",
		KRAKEN_TENTACLE = "怪物的觸手！",
		LIMPETROCK =
		{
			GENERIC = "長滿肉的石頭！",
			PICKED = "現在這石頭上沒肉了...",
		},
		TREEGUARD = "拿起武器！",
		LIVINGJUNGLETREE = "大樹，我不喜歡你的臉！",
		LOBSTER_DEAD = "安息吧，穿著盔甲的傢伙。",
		LOBSTER_DEAD_COOKED = "盔甲裡藏著美味的肉。",
		LUGGAGECHEST = "希望這些來自海洋的戰利品能讓我樂壞！",
		MAGIC_SEAL = "這是一位勇猛的戰士留下的，我應該帶著敬意使用它。",
		MAGMAROCK = "用什麼才能讓這些石頭搖滾起來？",
		MAGMAROCK_FULL = "用什麼才能讓這些石頭搖滾起來？",
		MAGMAROCK_GOLD = "它閃著微光...",
		MAGMAROCK_GOLD_FULL = "它閃著微光...",
		MANGROVETREE = "我以前從未從長船上砍過樹！",
		MANGROVETREE_BURNT = "水上的部分都燒焦了。",
		MARSH_PLANT_TROPICAL = "一株貧瘠的植物。",
		MERMFISHER = "我不跟漁民吵架，只要他們沒有拿起武器。",
		MERMHOUSE_FISHER = "漁民住在這裡。",
		MONKEYBALL = "逗猴子的玩具。",
		MONSTERTARTARE = "肉還在顫動。",
		MOSQUITOSACK_YELLOW = "這只害蟲掉落了它的毒囊。",
		MUSSELBOUILLABAISE = "很清淡，但很溫暖。",
		MUSSEL_COOKED = "味道很濃烈。",
		MUSSEL_FARM =
		{
			GENERIC = "這裡有貽貝。",
			STICKPLANTED = "Become one with the stick...",
		},
		MYSTERYMEAT = "敵人孩子的食物...對我來說代表什麼？",
		OCTOPUSCHEST = "裝著回禮的箱子。",
		OCTOPUSKING = "好像可以跟他做實物交易。",
		OXHAT = "這個頭盔可以讓我的頭皮保持乾燥。",
		OX_FLUTE = "我吹不成調...",
		OX_HORN = "啊，它可以做成一個不錯的馬克杯！",
		PALMLEAF_HUT = "為我的頭盔擋雨。",
		PARROT_PIRATE = "你的話太多！",
		PEG_LEG = "這條假腿的打擊效果應該不錯！",
		PIGTENT = "聞起來像早餐的味道！",
		PIKE_SKULL = "讓我想起了家鄉。",
		PIRATEGHOST = "回地獄去吧，幽靈！",
		PIRATEPACK = "可以背著走的箱子。",
		PIRATIHATITATOR =
		{
			BURNT = "它的魔法化作灰燼消失了。",
			GENERIC = "這是什麼怪異的巫術？",
		},
		PORTAL_SHIPWRECKED = "這艘長船看起來不適合戰士。",
		PRIMEAPE = "你就像你滿身的毛一樣好笑。",
		PRIMEAPEBARREL = "又髒又亂，我簡直懷疑有個維京人住在這裡。",
		RAWLING = "終於有人陪我練習了！",
		REDBARREL = "這個桶裡聚集了巨大的力量！",
		ROCK_CHARCOAL = "燒焦的石頭？",
		ROCK_OBSIDIAN = "熔岩石！",
		SAIL_STICK = "我指揮著風！",
		SANDBAGSMALL = "這個沙包可以用來擋水！",
		SANDBAGSMALL_ITEM = "它讓水的撞擊變得柔弱無力！",
		SAND_CASTLE =
		{
			GENERIC = "我想假裝自己是一個巨人並碾碎它！",
			SAND = "時光碾碎了它。",
		},
		SEAWEED_COOKED = "來自海洋的零食。",
		SEAWEED_DRIED = "它很有嚼勁...",
		SHADOWSKITTISH_WATER = "敵人正在逼近！",
		SHARKITTEN = "我只想和你們的媽媽較量...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "有東西在埋伏等待！",
			INACTIVE = "現在只是...沙子...",
		},
		SHARK_GILLS = "鯊魚腮！",
		SHARK_TEETHHAT = "身為一個武士，我喜歡這個頭盔！",
		SHIPWRECKED_ENTRANCE = "可以掠奪戰利品的新大陸！",
		SHIPWRECKED_EXIT = "啟程前往新大陸...",
		SNAKEDEN =
		{
			BURNT = "它燒燬了。攀附著它已經沒有意義了。",
			CHOPPED = "它需要修剪一下。",
			GENERIC = "這叢植物像戴過帽子後的髮型一樣亂。",
		},
		SNAKEOIL = "這東西有什麼強大的功效？",
		SNAKESKINSAIL = "謀殺造就的船帆！",
		SPEAR_LAUNCHER = "來自至高神的禮物！",
		SUNKEN_BOAT =
		{
			ABANDONED = "大海又吞沒了一艘船！",
			GENERIC = "它有話想說！",
		},
		SUNKEN_BOAT_BURNT = "這裡舉行了一場維京式的葬禮...",
		SUNKEN_BOAT_TRINKET_1 = "某種粗製武器？", 
		SUNKEN_BOAT_TRINKET_2 = "孩子的玩具船。", 
		SUNKEN_BOAT_TRINKET_3 = "泡水的蠟燭。", 
		SUNKEN_BOAT_TRINKET_4 = "海洋巫術。", 
		SUNKEN_BOAT_TRINKET_5 = "不是我的尺碼。",
		SWEETPOTATOSOUFFLE = "好香啊！",
		SWEET_POTATO = "我以前從未聽說過馬鈴薯還有甜的！...真荒唐！",
		SWEET_POTATO_COOKED = "我不會吃它，但我喜歡它的顏色。",
		SWEET_POTATO_PLANTED = "土裡有不能吃的植物甜食！",
		SWEET_POTATO_SEEDS = "它們將甜蜜地生長。",
		SWIMMINGHORROR = "你在這裡是想給我舉行一場維京式的葬禮嗎？",
		TELEPORTATO_SW_BASE = "它還缺少一些零件。",
		TELEPORTATO_SW_BOX = "它是某個東西的零件。",
		TELEPORTATO_SW_CRANK = "它在轉動，但是為什麼？",
		TELEPORTATO_SW_POTATO = "這是什麼奇怪的裝置？",
		TELEPORTATO_SW_RING = "這個值錢嗎？",
		THATCHPACK = "希望我的長矛沒在它上面戳個洞。",
		TIDALPOOL = "一個小湖！",
		TIDAL_PLANT = "水中的植物。",
		TIGEREYE = "我得到了虎鯊的眼睛！",
		TRAWLNETDROPPED =
		{
			GENERIC = "好多戰利品！",
			SOON = "我的戰利品很快就會將網壓得沉下去。",
			SOONISH = "我覺得我的戰利品很快就會將網壓得沉下去。",
		},
		TRINKET_20 = "某種粗製武器？", 
		TRINKET_21 = "孩子的玩具船。",
		TRINKET_22 = "泡水的蠟燭。", 
		TRINKET_23 = "破損的設備。", 
		TROPICAL_FISH = "它裡面是肉的顏色！",
		TUNACAN = "可以維持航行的食物！",
		TURF_SANDY = "一塊戰場。",
		TURF_ASH = "一塊戰場。",
		TURF_BADLANDS = "一塊戰場。",
		TURF_DECIDUOUS = "一塊戰場。",
		TURF_DESERTDIRT = "一塊戰場。",
		TURF_FUNGUS_GREEN = "一塊戰場。",
		TURF_FUNGUS_RED = "一塊戰場。",
		TURF_MAGMAFIELD = "一塊戰場。",
		TURF_MEADOW = "一塊戰場。",
		TURF_SNAKESKINFLOOR = "把敵人的外皮踩在腳下感覺很好！",
		TURF_SWAMP = "一塊戰場。",
		TURF_TIDALMARSH = "一塊戰場。",
		TURF_VOLCANO = "一塊戰場。",
		TWISTER_SEAL = "你就是那個會召來颶風的小傢伙？！？",
		VOLCANO_ALTAR =
		{
			GENERIC = "火神的祭壇正在休眠。",
			OPEN = "它已經準備好接受獻祭了！",
		},
		VOLCANO_ALTAR_TOWER = "火神的祭壇！",
		VOLCANO_SHRUB = "你看上去已經燒成灰了。",
		WALLYINTRO_DEBRIS = "這是我那艘長船的殘骸嗎？",
		WATERMELON_SEEDS = "好多種子。",
		WATERYGRAVE = "下面有寶貝！",
		WHALE_BUBBLES = "有東西潛伏在下面。",
		WHALE_TRACK = "我會找到你並揍你一頓的！",
		WILBUR_CROWN = "我想知道這是什麼？",
		WILBUR_UNLOCK = "我不會向任何國王下跪的，哪怕他長得很可愛！",
		WILDBORE = "我與他志同道合！",
		WILDBOREHEAD = "給我在英靈殿留個位置。",
		WILDBOREHOUSE = "住在這裡太恐怖了！",
		WIND_CONCH = "我感到有風...",
		WOODLEGS_CAGE = "上鎖的籠子！",
		WOODLEGS_KEY1 = "它可以打開什麼？",
		WOODLEGS_KEY2 = "另一把鑰匙！",
		WOODLEGS_KEY3 = "一把奇怪的鑰匙！",
		WRECK = "長船散落在去英靈殿的路上。",
	},
	DESCRIBE_GENERIC = "它是這個王國的一個手工製品。",
	DESCRIBE_TOODARK = "即使對戰鬥來說也太黑了。",
	DESCRIBE_SMOLDERING = "火焰很快會將它吞噬。",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "最新鮮的肉！",
	},
}
