return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我会一直等到他闭眼为止。",
			GENERIC = "那个剃不了。",
			NOBITS = "已经没毛了，我剃不了。",
		},
		WRITE =
        {
            GENERIC = "沃尔夫冈不擅长写小字。",
        },
		RUMMAGE =
        {   
            GENERIC = "也许沃尔夫冈可以晚点来做。",
        },
		COOK =
        {
            GENERIC = "沃尔夫冈没心情烹饪。",
            TOOFAR = "锅是太小了，还是太远了？",
        },
		REPAIRBOAT =
		{
			GENERIC = "小船没有要修理的地方！沃尔夫冈给它来一拳？",
		},
		STORE =
		{
			GENERIC = "我会把它强塞进去！",
			NOTALLOWED = "呸！没用。",
		},
		GIVE =
        {
            DEAD = "你知道它死了，对吧？",
            SLEEPING = "它现在睡着了！",
            BUSY = "强壮的沃尔夫冈很快会再次尝试！",
        },
        CHANGEIN =
        {
            GENERIC = "衣服就是用来给强壮的肌肉撑裂的！",
            BURNING = "沃尔夫冈的工作日内衣烧掉了？沃尔夫冈很伤心。",
        },
        TEACH =
        {
            KNOWN = "沃尔夫冈已经知道这个了！",
            CANTLEARN = "我不明白。",
        },
	},
	ACTIONFAIL_GENERIC = "我不够强大，做不到。",
	
	ANNOUNCE_NORMALTOMIGHTY="我是最强壮的！",
	ANNOUNCE_NORMALTOWIMPY="我感觉不太好。",
	ANNOUNCE_WIMPYTONORMAL="沃尔夫冈感觉好些了。",
	ANNOUNCE_MIGHTYTONORMAL="我需要再次填饱我强大的胃！",

	ANNOUNCE_MAGIC_FAIL = "现在没法用魔法了。为什么？",
	ANNOUNCE_NOSLEEPONFIRE = "太热了，睡不了。",
	ANNOUNCE_NODANGERSIESTA = "沃尔夫冈喜欢战斗多过打盹。",
	ANNOUNCE_NONIGHTSIESTA = "沃尔夫冈的原则是不在夜间午休。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "沃尔夫冈很紧张。太紧张了，没法放松。",
	ANNOUNCE_NOHUNGERSIESTA = "沃尔夫冈只在吃过东西后午休。",
	ANNOUNCE_SHELTER = "沃尔夫冈躲在树下。",
	ANNOUNCE_BURNT = "燃烧是不公平的！",
	ANNOUNCE_TOOL_SLIP = "太滑了，握不住！",
	ANNOUNCE_DAMP = "雨季来临。",
	ANNOUNCE_WET = "沃尔夫冈不喜欢洗澡。",
	ANNOUNCE_WETTER = "就像坐在池塘里。",
	ANNOUNCE_SOAKED = "沃尔夫冈现在像是水里捞出来的。",
	ANNOUNCE_ADVENTUREFAIL = "下次我会聪明点的！",
	ANNOUNCE_BOOMERANG = "噢！你为什么伤害我，会飞的臭棍子？",
	ANNOUNCE_CHARLIE = "现身吧！",
	ANNOUNCE_CHARLIE_ATTACK = "噢！它击中我了！",
	ANNOUNCE_COLD = "嘶~~~~~~~！好冷！",
	ANNOUNCE_HOT = "哈，又黏又热！",
	ANNOUNCE_CRAFTING_FAIL = "我需要收集更多东西才能制造那个。",
	ANNOUNCE_DUSK = "令人恐慌的时刻即将到来。",

	ANNOUNCE_ENTER_DARK = "我看不见了！我害怕！",
	ANNOUNCE_ENTER_LIGHT = "我又可以看到东西了！",
	ANNOUNCE_HOUNDS = "我听到了小狗的声音！",
	ANNOUNCE_HUNGRY = "我硕大的肚子空了！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "动物在附近！",
	ANNOUNCE_HUNT_LOST_TRAIL = "这里没有动物。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "动物痕迹现在全成了泥浆。",
	ANNOUNCE_INV_FULL = "我再强壮也带不了更多东西了。",
	ANNOUNCE_FAN_OUT = "小扇子坏掉了！",
    ANNOUNCE_COMPASS_OUT = "小指针断了！",
	ANNOUNCE_PECKED = "为什么要这样对我？",
	ANNOUNCE_TORCH_OUT = "哦，不！火灭了！",
	ANNOUNCE_WORMHOLE = "它让我感到自己还活着！",
	ANNOUNCE_TRAP_WENT_OFF = "啊！别惊吓沃尔夫冈！",
    ANNOUNCE_QUAKE = "大地在震颤。沃尔夫冈讨厌摇晃的地面。",
    ANNOUNCE_NODANGERSLEEP = "沃尔夫冈喜欢战斗多过睡觉。",
    ANNOUNCE_UNIMPLEMENTED = "还没好。",
    ANNOUNCE_NOHUNGERSLEEP = "沃尔夫冈说，决不空腹睡觉。",
    ANNOUNCE_FREEDOM = "我自由了！大大的自由！",
    ANNOUNCE_RESEARCH = "好多信息。",
    ANNOUNCE_NO_TRAP = "像举重一样简单。",
    ANNOUNCE_HIGHRESEARCH = "也许信息太多了。",
    ANNOUNCE_THORNS = "尖刺是不公平的！",
    ANNOUNCE_NODAYSLEEP_CAVE = "洞穴里太吓人了。",
    ANNOUNCE_BEES = "蜜蜂！讨厌的蜇人虫子！",
    ANNOUNCE_KNOCKEDOUT = "呃，我一定是被砸到了脑袋。",
    ANNOUNCE_LOWRESEARCH = "一点点信息。",
    ANNOUNCE_DEERCLOPS = "听起来像是有一个强壮的巨人来了。",
    ANNOUNCE_MOSQUITOS = "沃尔夫冈需要血，该死的虫子快滚开！",
    ANNOUNCE_NODAYSLEEP = "天太亮了，睡不着。",
	ANNOUNCE_CANFIX = "\n聪明的头脑可以使这个变得更好！",
	ANNOUNCE_ACCOMPLISHMENT= "我用小小的箭头做伟大的事情！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "我打败了小箭头！",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "便便不够。",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "跟沃尔夫冈的衣服比，闪电很弱！",
	ANNOUNCE_WORMS = "大地在沃尔夫冈强劲的脚下颤抖！",

	ANNOUNCE_OTHER_WORLD_PLANT = "要在这里生长还不够强壮！不像沃尔夫冈！",

	ANNOUNCE_BOAT_DAMAGED = "船很弱！需要修理。",
	ANNOUNCE_BOAT_SINKING = "我将与大海战斗！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "沃尔夫冈要给死神来一拳！",
	ANNOUNCE_CRAB_ESCAPE = "螃蟹逃了。我不怪它。",
	ANNOUNCE_EAT =
	{
		GENERIC = "好的食物让沃尔夫冈强壮！",
		PAINFUL = "噢，我肚子疼。",
		SPOILED = "呕！味道像垃圾！",
		STALE = "味道怪怪的。",
		INVALID = "哈哈！那不是食物！",
		YUCKY = "胃不够强大，吃不了那个。",
	},
	ANNOUNCE_MAPWRAP_LOSECONTROL = "船不听强壮的沃尔夫冈的话！",
	ANNOUNCE_MAPWRAP_RETURN = "沃尔夫冈势不可挡！",
	ANNOUNCE_MAPWRAP_WARN = "越来越可怕了！",
	ANNOUNCE_MORETREASURE = "沃尔夫冈找到了更多的财宝！",
	ANNOUNCE_OTHER_WORLD_TREASURE = "看起来宝藏不在附近。",
	ANNOUNCE_SHARX = "沃尔夫冈交了新朋友！",
	ANNOUNCE_TRAWL_FULL = "网里装满了宝贝！",
	ANNOUNCE_TREASURE = "沃尔夫冈看到了礼物！",
	ANNOUNCE_VOLCANO_ERUPT = "哈哈！是时候与火山战斗了！",
	ANNOUNCE_WAVE_BOOST = "我是最强壮的！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "沃尔夫冈会找到你的，大鱼！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "啊！大鱼戏耍了沃尔夫冈！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "沃尔夫冈追踪不了大鱼！",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"呃...沃尔夫冈不识字。",
	},

	BATTLECRY =
	{
		GENERIC = "我要揍扁你！",
		PIG = "对不起，我的朋友！",
		PREY = "我踩！我踩！我踩！",
		SPIDER = "去死吧，邪恶可怕的虫子！",
		SPIDER_WARRIOR = "还是我更强壮，可怕的虫子！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "哈！我赢了！",
		PIG = "我原谅你，猪人。",
		PREY = "继续逃吧你！",
		SPIDER = "他逃走了。",
		SPIDER_WARRIOR = "他知道我更强壮。",
	},
	DESCRIBE =
	{
		BABYOX = "他会长得很壮！会不会是个女的？",
		BIGFISHINGROD = "抓大鱼？",
		BLOWDART_POISON = "就像许多小打孔机！",
		COFFEEBOT = "辛勤的工人。",
		COMPASS =
		{
			E = "东。",
			GENERIC = "全是指示，但没有方向。",
			N = "北。",
			NE = "东北。",
			NW = "西北。",
			S = "南。",
			SE = "东南。",
			SW = "西南。",
			W = "西。",
		},
		DEPLETED_BAMBOOTREE = "树丛完蛋了。",
		DEPLETED_BUSH_VINE = "藤蔓看上去很可怜！",
		DEPLETED_GRASS_WATER = "也许草需要吃东西。",
		DEVTOOL = "沃尔夫冈将砸烂它！",
		DEVTOOL_NODEV = "打碎！",
		MUSSELBOUILLABAISE = "它属于沃尔夫冈的嘴里。",
		OBSIDIANSPEARGUN = "不如用拳头爽，但还是很好！",
		RELIC =
		{
			BROKEN = "Tiny bits.",
			GENERIC = "Is dumb thing.",
		},
		SPEARGUN_POISON = "我的病毒发射器！",
		SUPERTELESCOPE = "让眼睛强大！",
		SWEETPOTATOSOUFFLE = "沃尔夫冈要开吃了！",
		TREASURECHEST_TRAP = "哇！",
		WOODLEGSBOAT = "非常坏的船。",
		WOODLEGSHAT = "戴在头上的。",
		WOODLEGSSAIL = "吓人的帆！",
		WORMHOLE_LIMITED = "It is weak and feeble.",
		GLOMMER = "你为什么跟着我，怪虫子？",
        GLOMMERFLOWER = 
        {
        	GENERIC = "发光的花。",
        	DEAD = "令人伤感的发光的花。",
        },
        GLOMMERWINGS = "好小，像精灵的翅膀。",
        GLOMMERFUEL = "古怪的虫子拉古怪的便便。",
        BELL = "铃铛发出悦耳的声音。",
        STATUEGLOMMER = 
        {	
        	GENERIC = "为什么雕像没有飞起来？",
        	EMPTY = "打碎！",
    	},
		WEBBERSKULL = "我要打碎头骨！",
		MOLE =
		{
			HELD = "沃尔夫冈对柔软的小动物很仁慈。",
			UNDERGROUND = "待在地下别出来，否则沃尔夫冈不保证你的安全。",
			ABOVEGROUND = "现在你会知道沃尔夫冈的厉害！",
		},
		MOLEHILL = "鼹鼠洞。",
		MOLEHAT = "鼹鼠皮弹性十足。",
		NIGHTSTICK = "沃尔夫冈更喜欢拳头。",
		RABBITHOUSE=
		{
			GENERIC = "我听见里面有吃东西的声音。",
			BURNT = "没声音了。",
		},
		TURF_DECIDUOUS = "踏脚石。",
		TURF_SANDY = "Step stones.",
		TURF_BADLANDS = "踏脚石。",
		BEARGER = "沃尔夫冈不想和大熊打架。",
		BEARGERVEST = "大熊衬衫。",
		ICEPACK = "毛皮袋子。",
		BEARGER_FUR = "像沃尔夫冈胸膛上的毛。",
		BIGFOOT = "脚太大了！",
		BONESHARD = "沃尔夫冈可以把它砸得更碎！",
		BUZZARD = "继续。",
		CACTUS = 
		{
			GENERIC = "沃尔夫冈不喜欢尖的植物。",
			PICKED = "哈！现在成了扁的植物。",
		},
		CACTUS_MEAT_COOKED = "现在安全了。",
		CACTUS_MEAT = "尖刺植物的肉。",
		CACTUS_FLOWER = "不值得摘。",
		COLDFIRE =
		{
			EMBERS = "黑暗来临了！",
			GENERIC = "再见了，黑暗时代！",
			HIGH = "火太大了！",
			LOW = "火不够冷。",
			NORMAL = "好火！",
			OUT = "啊哦。火灭了。",
		},
		CATCOON = "沃尔夫冈不相信它。",
		CATCOONDEN = 
		{
			GENERIC = "树桩很可疑。",
			EMPTY = "树桩是空的，沃尔夫冈现在更放心了。",
		},
		CATCOONHAT = "现在沃尔夫冈不相信自己了。",
		COONTAIL = "摆动的猫尾巴！",
		COOKPOT =
		{
			COOKING_LONG = "这需要很长时间。",
			COOKING_SHORT = "快熟了！",
			DONE = "吃饭时间到了！",
			EMPTY = "空锅子让沃尔夫冈产生了饥饿感。",
			BURNT = "锅没了。",
		},
		EYEBRELLAHAT =	"它总是向上看。",
		ARMORDRAGONFLY = "沃尔夫冈不需要保护。",
		DRAGON_SCALES = "发热的鳞片。",
		DRAGONFLYCHEST = "不怕火的箱子。",
		DECIDUOUSTREE = 
		{
			BURNING = "我弄死了它。",
			BURNT = "现在又小又破了。",
			CHOPPED = "哈！我赢了！",
			GENERIC = "你好，树！",
			POISON = "愤怒的大树。",
		},
		ACORN_COOKED = "沃尔夫冈烤熟了树上掉下来的坚果。",
		BIRCHNUTDRAKE = "愤怒的小坚果。",
		FARMPLOT =
		{
			GENERIC = "我会在这里种植强大的农作物！",
			GROWING = "长吧，我的小朋友！快快长大！",
			NEEDSFERTILIZER = "土对农作物来说不够肥。",
			BURNT = "种不了了。",
		},
		COLDFIREPIT =
		{
			EMBERS = "黑暗来临了！",
			GENERIC = "再见了，黑暗时代！",
			HIGH = "火太大了！",
			LOW = "火不够冷。",
			NORMAL = "好火！",
			OUT = "啊哦。火灭了。",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "我能丢得更准。",
			OFF = "机器知道沃尔夫冈更强壮。",
			LOWFUEL = "你饿了吗，机器？",
		},
		ICEHAT = "为什么要把大冰块放在头上？",
		LIGHTNINGGOAT = 
		{
			GENERIC = "你好，山羊。",
			CHARGED = "在眼前闪耀。",
		},
		LIGHTNINGGOATHORN = "放电的小骨头。",
		GOATMILK = "喝奶长肌肉！",
		MEATRACK =
		{
			DONE = "美味，像皮革一样有嚼劲的肉！",
			DRYING = "晾干肉！晾干！",
			DRYINGINRAIN = "走开，雨水！肉正在晾干！",
			GENERIC = "我能晾干肉！",
			BURNT = "现在晾不了肉了。",
		},
		MERMHEAD = 
		{
			GENERIC = "多么帅气的恶魔啊！",
			BURNT = "现在没那么帅了。",
		},
		MERMHOUSE = 
		{
			GENERIC = "这屋子不够结实。",
			BURNT = "这屋子真的不够结实。",
		},
		FLOWERSALAD = "不是菠菜，但或许也可以让我变成大力士！",
        ICECREAM = "嗯，毕竟是星期天。",
        WATERMELONICLE = "哈！插在棍子上的瓜。",
        TRAILMIX = "浆果和坚果，浆果和坚果！",
        HOTCHILI = "哈哈，沃尔夫冈不怕辣！",
        GUACAMOLE = "沃尔夫冈不相信绿糊糊。",
		MOOSE = "非常奇怪的生物。",
		MOOSEEGG = "能让全家吃饱的早餐！",
		MOSSLING = "嗯。还是早餐，我想。",
		FEATHERFAN = "哈！跟脑袋一样大！",
		MINIFAN = "我一跑它就转得飞快！哈哈！",
		TROPICALFAN = "哈！跟脑袋一样大！",
		GOOSE_FEATHER = "痒痒！",
		STAFF_TORNADO = "转啊转！",
		PIGHEAD = 
		{	
			GENERIC = "为什么一张苦脸？",
			BURNT = "为什么脸没了？",
		},
		PIGHOUSE =
		{
			FULL = "喂！出来吧，猪人！",
			GENERIC = "对我来说门太小了。",
			LIGHTSOUT = "他去哪儿了？",
			BURNT = "猪的家没了。",
		},
		FERTILIZER = "臭臭的一整桶。",
		RAINOMETER = 
		{	
			GENERIC = "嘀嘀！嗒嗒！",
			BURNT = "噼啪！",
		},
		RAINCOAT = "还是保持干燥好。",
		RAINHAT = "就像水从鼹鼠背上流下。",
		RESEARCHLAB = 
		{	
			GENERIC = "我不确定我对…科学的感觉。",
			BURNT = "科学毕竟不是那么强大。",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "我不确定我对…科学的感觉。",
			BURNT = "科学毕竟不是那么强大。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "沃尔夫冈做了什么？",
			BURNT = "得，烧掉了。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "帽子不光可以用来戴在头上。",
			BURNT = "帽子也可以用来烧。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "我不会死的。",
			BURNT = "是他好过是真实世界的沃尔夫冈。",
		},
		ROCK_ICE = 
		{
			GENERIC = "水做的石头。",
			MELTED = "我抓不住水。",
		},
		ROCK_ICE_MELTED = "我抓不住水。",
		ICE = "适合用来做提神的点心。",
        REFLECTIVEVEST = "马甲就是马甲。",
		HAWAIIANSHIRT = "度假衬衫。",
		TENT = 
		{
			GENERIC = "是时候好好睡一觉了。",
			BURNT = "没法再用来睡觉了。",
		},
		SIESTAHUT = 
		{
			GENERIC = "打盹的地方。",
			BURNT = "打盹的地方没了。",
		},
		TRANSISTOR = "科学豆子。",
		TREASURECHEST = 
		{
			GENERIC = "我把东西放在那里面！",
			BURNT = "什么也放不了了。",
		},
		TUMBLEWEED = "回来，小滚球！",
		GRASS_UMBRELLA = "我不喜欢小伞。",
		PALMLEAF_UMBRELLA = "我不喜欢小伞。",
		UNIMPLEMENTED = "我不相信未完成的东西。",
		WALL_HAY = 
		{	
			GENERIC = "墙是用草建成的！",
			BURNT = "草烧光了！",
		},
		WALL_WOOD = 
		{
			GENERIC = "你好，尖木头！",
			BURNT = "再见，尖木头！",
		},
		WARG = "Big puppy!",
		WATERMELON = "好多籽。",
		WATERMELON_COOKED = "我把西瓜籽烤出来了。",
		WATERMELONHAT = "头上戴个瓜有什么不好！哈哈！",
		WINTEROMETER = 
		{
			GENERIC = "气温降低！红色下降！",
			BURNT = "烈焰升腾！测量仪倒下！",
		},
		HOMESIGN = 
		{
			GENERIC = "没空看标志！",
			BURNT = "标志看不清了。",
		},
		BEEBOX =
		{
			GENERIC = "好多蜜蜂！",
			READY = "可以采集了！",
			FULLHONEY = "可以采集了！",
			NOHONEY = "没有蜂蜜。",
			SOMEHONEY = "蜜蜂很忙。",
			BURNT = "蜜蜂被烧死了。",
		},
		LIVINGTREE = "我不喜欢有眼睛的树。",
		ICESTAFF = "尖端结霜了。",
		WORMLIGHT = "漂亮的灯。",
		WORMLIGHT_LESSER = "不错的小灯。",
		WORM =
		{
		    PLANT = "漂亮的灯。",
		    DIRT = "土在动？",
		    WORM = "完全没料到！",
		},
		WORMLIGHT_PLANT = "漂亮的灯。",
		EEL = "我必须做熟了这个！",
		EEL_COOKED = "鳗鱼已经烤熟了。",
		UNAGI = "食物让我强大！",
		EYETURRET = "强大的建筑将帮助我战斗！",
		EYETURRET_ITEM = "我必须放置这个。",
		MINOTAURHORN = "强大对手掉落的战利品。",
		MINOTAURCHEST = "这箱子长着大尖角。",
		THULECITE_PIECES = "我能混到一起做成更大的一块！",
		POND_ALGAE = "这么小的植物！我觉得很有趣。",
		GREENSTAFF = "这根棍子上面有一颗绿宝石。",
		POTTEDFERN = "它让我很高兴。",

		SLURPER = "不！不！离我的头远点！",
		SLURPER_PELT = "它还在动！",
		SLURPERPELT = "一簇奇怪的毛皮。",
		ARMORSLURPER = "它随我的许多肌肉一起运动！",
		ORANGEAMULET = "我能把它戴在脖子上。",
		YELLOWSTAFF = "漂亮的宝石装在棍子上。",
		TREECLUMP = "别挡沃尔夫冈的路！",
		YELLOWGEM = "漂亮的石头。",
		ORANGEGEM = "漂亮的石头。",
		TELEBASE = 
		{
			VALID = "发光是好迹象。",
			GEMS = "不觉得它起作用了。",
		},
		GEMSOCKET = 
		{
			VALID = "漂亮的石头现在装好了。",
			GEMS = "它是空的。",
		},
		STAFFLIGHT = "摸了会手疼。",

        ANCIENT_ALTAR =
        {
        	WORKING = "肮脏诡异的祭坛。",
        	BROKEN = "破损的祭坛。",
        },  
        ANCIENT_ALTAR_BROKEN = "破损的祭坛。",

        ANCIENT_STATUE = "丑，丑，丑。",

        LICHEN = "我喜欢这个！",
		CUTLICHEN = "真难吃。",

        CAVE_BANANA = "真好吃！",
        CAVE_BANANA_COOKED = "温暖的食物，真好吃！",
        CAVE_BANANA_TREE = "你好，倒立的树。",
        CAVE_BANANA_BURNT = "烧焦了。",
        ROCKY = "他真强壮！就像我一样！",

        BLUEAMULET = "可以做出很好的冰块！",
		PURPLEAMULET = "这个护符...让沃尔夫冈感到害怕。",
		TELESTAFF = "它让我头疼。",
		MINERHAT = "放在脑袋上的灯。",
		MONKEY = "丑陋的猴人！",
		MONKEYBARREL = "这个...东西。气味不怎么好闻。",

		HOUNDSTOOTH="狗牙！",
		ARMORSNURTLESHELL="里面黏黏的。",
		BAT="会飞的老鼠！",
		BATBAT = "这根棒子让我感觉好好笑。",
		BATWING="长满了毛，很恶心",
		BATWING_COOKED="外酥里嫩！",
		BEDROLL_FURRY="真舒服！",
		BUNNYMAN="你好，兔子！",
		FLOWER_CAVE="发光的植物。",
		FLOWER_CAVE_DOUBLE="发光的植物。",
		FLOWER_CAVE_TRIPLE="发光的植物。",
		GUANO="更多便便。",
		LANTERN="让我在黑暗中很安全。",
		LIGHTBULB="能吃吗？",
		MANRABBIT_TAIL="毛茸茸的！",
		MUSHTREE_TALL  ="Big mushtree is big.",
		MUSHTREE_MEDIUM="Mushy bush.",
		MUSHTREE_SMALL ="Mushy shrub.",
		MUSHTREE_TALL=
		{
            GENERIC = "大蘑菇树确实很大。",
            BLOOM = "哇！它还更大！",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "蘑菇灌木。",
            BLOOM = "它正玩的高兴！",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "矮蘑菇树。",
            BLOOM = "连气味都很强！",
        },
        MUSHTREE_TALL_WEBBED = "啊，开心点！",
        SPORE_TALL = "是小虫子？",
        SPORE_MEDIUM = "是小虫子？",
        SPORE_SMALL = "是小虫子？",
        SPORE_TALL_INV = "我使它成为我的宠物。",
        SPORE_MEDIUM_INV = "我使它成为我的宠物。",
        SPORE_SMALL_INV = "我使它成为我的宠物。",

		SLURTLE="哈！你真慢！",
		SLURTLE_SHELLPIECES="碎掉了。",
		SLURTLEHAT="保护我脑袋的安全。",
		SLURTLEHOLE="洞里全是鼻涕虫。",
		SLURTLESLIME="一坨鼻涕！",
		SNURTLE="螺旋状的！",
		SPIDER_HIDER="是受惊的蜘蛛！",
		SPIDER_SPITTER="卟突！卟突！",
		SPIDERHOLE="到处都是蜘蛛。",
		STALAGMITE="尖尖的。",
		STALAGMITE_FULL="尖尖的。",
		STALAGMITE_LOW="尖尖的。",
		STALAGMITE_MED="尖尖的。",
		STALAGMITE_TALL="岩石从大地上冒出来。",
		STALAGMITE_TALL_FULL="岩石从大地上冒出来。",
		STALAGMITE_TALL_LOW="岩石从大地上冒出来。",
		STALAGMITE_TALL_MED="岩石从大地上冒出来。",

		TURF_CARPETFLOOR = "踏脚石。",
		TURF_CHECKERFLOOR = "踏脚石。",
		TURF_DIRT = "踏脚石。",
		TURF_FOREST = "踏脚石。",
		TURF_GRASS = "踏脚石。",
		TURF_MARSH = "踏脚石。",
		TURF_ROAD = "踏脚石。",
		TURF_ROCKY = "踏脚石。",
		TURF_SAVANNA = "踏脚石。",
		TURF_WOODFLOOR = "踏脚石。",

		TURF_CAVE="踏脚石。",
		TURF_FUNGUS="踏脚石。",
		TURF_SINKHOLE="踏脚石。",
		TURF_UNDERROCK="踏脚石。",
		TURF_MUD="踏脚石。",

		POWCAKE = "都不知道是什么做的！",
        CAVE_ENTRANCE = 
        {
            GENERIC="不管怎么说，谁会想钻进可怕的洞穴！",
            OPEN = "地球的肚脐眼！",
        },
        CAVE_EXIT = "Is dark and scary down here.",
        CAVE_EXIT = 
        {
            GENERIC = "让沃尔夫冈出去！",
            OPEN = "这下面又黑又恐怖。",
        },
        CAVE_ENTRANCE_RUINS = "连我也没那么大的力气。",

		MAXWELLPHONOGRAPH = "会唱歌的盒子！",
		BOOMERANG = "回旋！镖！哈！",
		PIGGUARD = "坏小猪！",
		ADVENTURE_PORTAL = "口字形的门！说“啊~！”",
		AMULET = "很漂亮。",
		ANIMAL_TRACK = "动物向这边走了。",
		ARMORGRASS = "扎人。",
		ARMORMARBLE = "我把石头绑在肌肉上。",
		ARMORWOOD = "几乎和肚子一样结实！",
		ARMOR_SANITY = "就像是穿着一块吓人的破布！",
		ASH =
		{
			GENERIC = "火焰的残骸。",
			REMAINS_GLOMMERFLOWER = "当我传送时被烧成灰烬的花！",
			REMAINS_EYE_BONE = "当我传送时被烧成灰烬的眼骨！",
			REMAINS_THINGIE = "某种被烧毁的东西。现在死了...",
		},
		AXE = "砍！",
		BABYBEEFALO = "小牦牛！",
		BACKPACK = "为了带更多的东西。",
		BACONEGGS = "食物里有蛋黄！还有肉！更强壮！",
		BANDAGE = "我能修好自己！",
		BASALT = "比我还强硬！",
		BEARDHAIR = "恶心。这些不是从我脸上剃下来的。",
		BEDROLL_STRAW = "休息时间到了！",
		BEE =
		{
			GENERIC = "又胖又生气的样子。",
			HELD = "在我的口袋里很安全。",
		},
		BEEFALO =
		{
			FOLLOWER = "牦牛跟着我！",
			GENERIC = "牦牛！",
			NAKED = "牦牛没毛了。",
			SLEEPING = "牦牛在睡觉。",
		},
		BEEFALOHAT = "这帽子不错！",
		BEEFALOWOOL = "我用牛毛做衣服。",
		BEEHAT = "防止蜜蜂蜇人的帽子。",
		BEEHIVE = "啊，蜂巢！",
		BEEMINE = "装满愤怒蜜蜂的球。",
		BEEMINE_MAXWELL = "装满愤怒咬人虫子的球。",
		BERRIES = "真好吃！",
		BERRIES_COOKED = "更好吃了！",
		BERRYBUSH =
		{
			BARREN = "我需要在上面施肥。",
			WITHERED = "对灌木来说太热了。",
			GENERIC = "长满了吃的！",
			PICKED = "能吃的部分没了。",
		},
		BIRDCAGE =
		{
			GENERIC = "小鸟的窝。",
			OCCUPIED = "你好，小鸟！",
			SLEEPING = "我应该保持安静！",
			HUNGRY = "我听到了小小的肚子咕咕叫的声音。",
			STARVING = "它的小肚子是空的！",
			DEAD = "鸟儿？你还好吗？",
			SKELETON = "它不太好。",
		},
		BIRDTRAP = "我要去抓鸟！",
		BIRD_EGG = "可怜的小鸟。",
		BIRD_EGG_COOKED = "好吃！",
		BISHOP = "神父！",
		BISHOP_CHARGE_HIT = "啊！",
		BLOWDART_FIRE = "当心，沃尔夫冈。",
		BLOWDART_SLEEP = "吹箭让敌人睡觉。",
		BLOWDART_PIPE = "让敌人痛苦的吹箭。",
		BLUEGEM = "漂亮的石头。",
		BLUEPRINT = "漂亮的图画！",
		BELL_BLUEPRINT = "漂亮的图画！",
		BLUE_CAP = "我想这对我有好处。",
		BLUE_CAP_COOKED = "变得不一样了。",
		BLUE_MUSHROOM =
		{
			GENERIC = "蘑菇。",
			INGROUND = "蘑菇藏起来了！",
			PICKED = "我已经采了那蘑菇。",
		},
		BOARDS = "我会劈开原木做木板！",
		BONESTEW = "全是好肉的炖菜。",
		BUGNET = "抓虫子用的。",
		BUSHHAT = "我真是太狡猾了！",
		BUTTER = "是黄油，尝起来像昆虫。",
		BUTTERFLY =
		{
			GENERIC = "蝴蝶飞舞！",
			HELD = "我的爱宠！",
		},
		BUTTERFLYMUFFIN = "沃尔夫冈没吃过虫子玛芬。我尝尝。",
		BUTTERFLYWINGS = "没有翅膀飞不起来！",
		CAMPFIRE =
		{
			EMBERS = "黑暗来临了！",
			GENERIC = "再见了，黑暗时代！",
			HIGH = "火太大了！",
			LOW = "火不够热。",
			NORMAL = "好火！",
			OUT = "啊哦。火灭了。",
		},
		CANE = "我可以一边走路一边战斗！",
		CARROT = "这是食物。我猜。",
		CARROT_COOKED = "烤过以后也没有更像肉。",
		CARROT_PLANTED = "藏着呢？",
		CARROT_SEEDS = "种子太小了。",
		CAVE_FERN = "漂亮的植物！",
		CHARCOAL = "像拿着小小的死树。",
        CHESSJUNK1 = "金属垃圾。",
        CHESSJUNK2 = "金属垃圾。",
        CHESSJUNK3 = "金属垃圾。",
		CHESTER = "有脚的奇怪箱子。",
		CHESTER_EYEBONE =
		{
			GENERIC = "这是眼骨。眼骨连着脸骨。",
			WAITING = "它现在睡着了。",
		},
		COOKEDMEAT = "我很会烤肉！",
		COOKEDMONSTERMEAT = "我还是不想吃这个。",
		COOKEDSMALLMEAT = "烤熟之后更小了！",
		CORN = "是玉米。你还想指望什么？",
		CORN_COOKED = "啵啵啵！哈哈，有趣的玉米。",
		CORN_SEEDS = "长玉米的种子。",
		CROW =
		{
			GENERIC = "我不喜欢鸟。太脆弱了。",
			HELD = "他叫得真难听。",
		},
		CUTGRASS = "我弄了一堆草。",
		CUTREEDS = "我弄了一堆芦苇。",
		CUTSTONE = "看我劈石作砖！",
		DEADLYFEAST = "看起来像邪恶的食物。",
		DEERCLOPS = "他看起来比我强壮！",
		DEERCLOPS_EYEBALL = "真恶心！",
		DEPLETED_GRASS =
		{
			GENERIC = "是一丛草。",
		},
		DIRTPILE = "肮脏的泥土。",
		DIVININGROD =
		{
			COLD = "机器人盒子在说话。",
			GENERIC = "机器人盒子。",
			HOT = "机器人盒子吓死我了！",
			WARM = "哈！那真不错，机器人盒子！",
			WARMER = "机器人盒子要发怒了...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "有什么用？",
			READY = "杖子需要钥匙启动。",
			UNLOCKED = "杖子打开了！",
		},
		DIVININGRODSTART = "古怪的杖子。",
		DRAGONFLY = "我弄不清...是蜻蜓还是龙蝇？",
		LAVASPIT = 
		{
			HOT = "热的熔岩坑。",
			COOL = "又冷又硬的熔岩坑。",
		},
		LAVA_POND = "不是游泳的时间！",
		LAVAE = "我必须逃跑！",
		LAVAE_PET = 
		{
			STARVING = "小宝宝快饿死了！",
			HUNGRY = "小宝宝饿了。",
			CONTENT = "小宝宝看起来吃饱了。",
			GENERIC = "小宝宝似乎很开心。",
		},
		LAVAE_EGG = 
		{
			GENERIC = "是用石头做的吗？",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "小蛋在打寒颤。",
			COMFY = "小蛋...似乎很舒服。",
		},
		LAVAE_TOOTH = "多么强劲的牙齿！",

		DRAGONFRUIT = "样子古怪的水果。",
		DRAGONFRUIT_COOKED = "熟了，但看起来还是怪怪的。",
		DRAGONFRUIT_SEEDS = "可以用来种古怪的水果，也许。",
		DRAGONPIE = "用奇怪的红色果实做的馅饼。",
		DRUMSTICK = "腿肉让腿更强壮。",
		DRUMSTICK_COOKED = "连骨头都吃掉就好。",
		DUG_BERRYBUSH = "他又冷又孤单。",
		DUG_GRASS = "他又冷又孤单。",
		DUG_MARSH_BUSH = "他又冷又孤单。",
		DUG_SAPLING = "他又冷又孤单。",
		DURIAN = "臭臭的带刺果实。",
		DURIAN_COOKED = "现在是热的、臭臭的带刺果实。",
		DURIAN_SEEDS = "尖刺水果植物的小宝宝。",
		EARMUFFSHAT = "现在我看起来像只小兔子！",
		EARMUFFHAT = "现在我看起来像只小兔子！",
		EGGPLANT = "这不是蛋！",
		EGGPLANT_COOKED = "没有蛋黄！蛋黄才是最精华的部分！",
		EGGPLANT_SEEDS = "小小的茄子种子。",
		STUFFEDEGGPLANT = "好吃到令其他食物羞愧。",
		ACORN = 
		{
		    GENERIC = "我能徒手捏碎这些树的种子！",
		    PLANTED = "它很快就会长成一棵树。",
		},
		EVERGREEN =
		{
			BURNING = "我弄死了它。",
			BURNT = "现在又小又破了。",
			CHOPPED = "哈！我赢了！",
			GENERIC = "你好，树！",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "我弄死了它。",
			BURNT = "现在又小又破了。",
			CHOPPED = "哈！我赢了！",
			GENERIC = "开心点，树！",
		},
		EYEPLANT = "它们可不像看起来那么可爱。",
		FEATHERHAT = "傻乎乎的羽毛帽子。沃尔夫冈现在成了鸟吗？",
		FEATHER_CROW = "黑鸟的羽毛。",
		FEATHER_ROBIN = "红鸟的羽毛。",
		FEATHER_ROBIN_WINTER = "白鸟的羽毛。",
		FEM_PUPPET = "恐怖的椅子吓坏了她！",
		FIREFLIES =
		{
			GENERIC = "闪闪发光！",
			HELD = "我的口袋闪闪发光！",
		},
		FIREHOUND = "汪汪！",
		FIREPIT =
		{
			EMBERS = "黑暗来临了！",
			GENERIC = "再见了，黑暗时代！",
			HIGH = "火太大了！",
			LOW = "火不够热。",
			NORMAL = "好火！",
			OUT = "啊哦。火灭了。",
		},
		FIRESTAFF = "生火的杖子。当心，沃尔夫冈。",
		FISH = "真腥。",
		FISHINGROD = "用来从池塘获得鱼肉。",
		FISHSTICKS = "哈哈，有趣的名字。",
		FISHTACOS = "希望对于沃尔夫冈来说不会太辣。",
		FISH_MED = "死了。",
		FISH_MED_COOKED = "来自水里的肉也可以让沃尔夫冈强壮。",
		FISH_COOKED = "来自水里的肉也可以让沃尔夫冈强壮。",
		FLINT = "是石头，但是很尖。",
		FLOWER = "它们很美。",
		FLOWER_WITHERED = "呃，这朵花好忧伤。",
		FLOWERHAT = "太美了！",
		FLOWER_EVIL = "不是土豆。",
		FOLIAGE = "我除掉了美丽的植物。",
		FOOTBALLHELMET = "抱摔专用帽子。",
		FROG =
		{
			DEAD = "在我的国家这就是美味佳肴。",
			GENERIC = "嘿，是小青蛙，青蛙。",
			SLEEPING = "睡着了。",
		},
		FROGLEGS = "在我的国家这就是美味佳肴！",
		FROGGLEBUNWICH = "夹了美味腿肉的三明治。",
		FROGLEGS_COOKED = "味道很像鸡肉。",
		FRUITMEDLEY = "一杯水果丁。",
		GEARS = "啊哈！现在谁的肌肉更大？",
		GHOST = "啊！啊！啊！",
		GOLDENAXE = "漂亮的斧子砍东西更好用。",
		GOLDENPICKAXE = "花哨的鹤嘴锄凿东西更好用。",
		GOLDENPITCHFORK = "漂亮的干草叉扒土更好用。",
		GOLDENSHOVEL = "花哨的铲子很好挖洞。",
		GOLDNUGGET = "钱是给小孩的！",
		GRASS =
		{
			BARREN = "它需要施肥。",
			WITHERED = "草被高温打败了。",
			BURNING = "不妙！",
			GENERIC = "是草。",
			PICKED = "草被打败了！",
		},
		GREEN_CAP = "用来做沙拉的。呸。",
		GREEN_CAP_COOKED = "变得不一样了。",
		GREEN_MUSHROOM =
		{
			GENERIC = "蘑菇。",
			INGROUND = "蘑菇藏起来了！",
			PICKED = "我已经采了那蘑菇。",
		},
		GUNPOWDER = "烈性胡椒粉！",
		HAMBAT = "还不错。",
		HAMMER = "再来把镰刀！",
		HEALINGSALVE = "它让我感到自己还活着！",
		HEATROCK =
		{
			FROZEN = "嘶~~~！冰冷的石头！",
			COLD = "石头有点冷。",
			GENERIC = "这块圆石像我的脑袋！",
			WARM = "相当普通的石头。",
			HOT = "对沃尔夫冈来说够热了！",
		},
		HONEY = "好甜！",
		HONEYCOMB = "蜜蜂曾生活在里面。",
		HONEYHAM = "带甜味的大肉是好肉。",
		HONEYNUGGETS = "带甜味的小肉仍是好肉。",
		HORN = "牦牛角。沃尔夫冈听到了牦牛的声音。",
		HOUND = "汪汪！",
		HOUNDMOUND = "骨头房子。",
		HOUNDBONE = "汪汪叫的弱狗不够强壮。",
		ICEBOX = "制冷的箱子！",
		ICEHOUND = "汪汪！",
		INSANITYROCK =
		{
			ACTIVE = "挡住我的路了。",
			INACTIVE = "哈。我踩到了小障碍物。",
		},
		JAMMYPRESERVES = "软泥般的质感，像我在手心捏扁的敌人。",
		KABOBS = "连棍子都吃掉就好。",
		KILLERBEE =
		{
			GENERIC = "愤怒的蜜蜂！",
			HELD = "我的愤怒的蜜蜂！",
		},
		KNIGHT = "像马的铁马！",
		KOALEFANT_SUMMER = "鼻子肉！",
		KOALEFANT_WINTER = "好软，我要挤扁他！",
		KRAMPUS = "可怕的山羊男！快跑！",
		KRAMPUS_SACK = "我拿到了山羊男的包。",
		LEIF = "木头人！",
		LEIF_SPARSE = "木头人！",
		LIGHTNING_ROD =
		{
			CHARGED = "噢，火花！",
			GENERIC = "天上的电线！",
		},
		LITTLE_WALRUS = "你觉得你比成年人更强大？",
		LIVINGLOG = "这木头长着一张恐怖的脸！",
		LOCKEDWES = "小个子给雕像人困住了。",
		LOG = "Is thick like my arm.",
		LOG =
		{
			BURNING = "When I stick my hand over it, it tickles.",
			GENERIC = "Remains of tree-fights!",
		},
		LUREPLANT = "你骗不了沃尔夫冈！",
		LUREPLANTBULB = "啊哈！现在谁狡猾？",
		MALE_PUPPET = "恐怖的椅子吓住了他！",
		MANDRAKE =
		{
			DEAD = "植物小人死了！",
			GENERIC = "奇怪的植物。",
			PICKED = "植物小人朋友！",
		},
		COOKEDMANDRAKE = "植物小人是食物？",
		MANDRAKESOUP = "植物小人是用来做汤的！",
		MARBLE = "我能举起来！",
		MARBLEPILLAR = "太重了，举不起来。",
		MARBLETREE = "别想用手击倒这棵树。",
		MARSH_BUSH =
		{
			BURNING = "啊哦。尖尖的火焰。",
			GENERIC = "好多刺。",
			PICKED = "刺扎手。",
		},
		BURNT_MARSH_BUSH = "现在烧没了。",
		MARSH_PLANT = "植物。",
		MARSH_TREE =
		{
			BURNING = "我烧掉了尖刺！",
			BURNT = "现在又黑又刺人。",
			CHOPPED = "我砍掉了尖刺！",
			GENERIC = "刺人。",
		},
		MAXWELL = "花哨的衣服比不上我的肌肉！",
		MAXWELLHEAD = "可怕的头有十二英尺高！",
		MAXWELLLIGHT = "恐怖的灯！",
		MAXWELLLOCK = "恐怖的锁！",
		MAXWELLTHRONE = "恐怖的椅子！",
		MEAT = "肉使我强壮！",
		MEATBALLS = "肉丸子让我更强壮！",
		MEAT_DRIED = "看起来像皮革，吃起来像肉。",
		MERM = "鱼人！",
		MONSTERLASAGNA = "味道像夹杂着毛和肉的面条。",
		MONSTERMEAT = "看起来不像是食物。",
		MONSTERMEAT_DRIED = "看起来像皮革，吃起来也像皮革。",
		MOSQUITO =
		{
			GENERIC = "让我想起了叔叔！",
			HELD = "不能再给你吸更多血了！",
		},
		MOSQUITOSACK = "叔叔可没这样的胆。",
		MOUND =
		{
			DUG = "对不住了，逝去的人们。",
			GENERIC = "怕怕！可能里边全是骨头！",
		},
		NIGHTLIGHT = "发出奇怪的光。",
		NIGHTMAREFUEL = "恐怖的东西。",
		NIGHTSWORD = "真的？不是真的？至少是锋利的！",
		NITRE = "是石头，但是不一样。",
		ONEMANBAND = "又大又响。我喜欢！",
		PANDORASCHEST = "漂亮的箱子！",
		PANFLUTE = "我能演奏民歌。",
		PAPYRUS = "像纸。",
		PENGUIN = "滑稽的陆行鸟！",
		PERD = "蠢鸟吃光了所有浆果！",
		PEROGIES = "沃尔夫冈爱吃饺子！",
		PETALS = "真香。",
		PETALS_EVIL = "它们让我脑子疼。",
		PHLEGM = "啊哈哈哈！鼻涕！哦嚯嚯！",
		PICKAXE = "凿！",
		PIGGYBACK = "臭烘烘的袋子！",
		PIGKING = "哈！他是好人！",
		PIGMAN =
		{
			DEAD = "不！猪死了！",
			FOLLOWER = "现在是朋友了！",
			GENERIC = "你好，猪兄。最近怎么样？",
			GUARD = "他练举重吗？",
			WEREPIG = "愤怒的小猪！",
		},
		PIGSKIN = "为什么屁股那么长？哈哈，沃尔夫冈真幽默。",
		PIGTORCH = "怎么点火？",
		PINECONE = 
		{
		    GENERIC = "我能徒手捏碎这些树的种子！",
		    PLANTED = "它很快就会长成一棵树。",
		},
		PINECONE_SAPLING = "它很快就会长成一棵树。",
        LUMPY_SAPLING = "它破土而出！",
		PITCHFORK = "让我想起了小时候。",
		PLANTMEAT = "这是啥玩意儿？给小孩子吃的肉？",
		PLANTMEAT_COOKED = "现在好一点了。",
		PLANT_NORMAL =
		{
			GENERIC = "枝繁叶茂！",
			GROWING = "还在生长。",
			READY = "啧~ 现在好吃了。",
			WITHERED = "可怜的枯萎植物。",
		},
		POMEGRANATE = "看起来像是机灵鬼的大脑。",
		POMEGRANATE_COOKED = "哈哈哈！我把它的脑子烤了！现在聪明不起来了。",
		POMEGRANATE_SEEDS = "大脑的组成部分？",
		POND = "全是水。",
		POOP = "真臭！",
		SCORCHED_SKELETON = "沃尔夫冈不喜欢这个！！",
		PUMPKIN = "像弱者的脑袋一样大！不是沃尔夫冈的脑袋。",
		PUMPKINCOOKIE = "好吃的饼干。",
		PUMPKIN_COOKED = "我把你的头烤了，弱小的人！我是最强壮的沃尔夫冈。",
		PUMPKIN_LANTERN = "现在真的是一个头了！沃尔夫冈害怕！",
		PUMPKIN_SEEDS = "这能长出脑袋大小的食物。",
		PURPLEGEM = "更漂亮的石头。",
		RABBIT =
		{
			GENERIC = "小兔子！躲远点吧！",
			HELD = "他是我的朋友。",
		},
		RABBITHOLE = 
		{
			GENERIC = "躲得了一时，躲不了一世，你这会跳的肥肉！",
			SPRING = "在兔子家，现在是繁忙时间。",
		},
		RATATOUILLE = "这是食物。算是吧。",
		RAZOR = "我的皮肤硬的连毛都长不出来！",
		REDGEM = "漂亮的石头。",
		RED_CAP = "哦！美丽又闪亮！",
		RED_CAP_COOKED = "变得不一样了。",
		RED_MUSHROOM =
		{
			GENERIC = "蘑菇。",
			INGROUND = "蘑菇藏起来了！",
			PICKED = "我已经采了那蘑菇。",
		},
		REEDS =
		{
			BURNING = "不妙！",
			GENERIC = "水草。",
			PICKED = "我打败了芦苇！",
		},
        RELIC = 
        {
            GENERIC = "House stuff.",
            BROKEN = "Smashed all the way!",
        },
        RUBBLE = "残破的房屋瓦砾。",
		RESURRECTIONSTONE = "在石头上跳起舞吧！",
		ROBIN =
		{
			GENERIC = "漂亮的红鸟。",
			HELD = "装在口袋里的快乐小鸟。",
		},
		MOOSE_NESTING_GROUND = "大鸟宝宝的床！",
		ROBIN_WINTER =
		{
			GENERIC = "漂亮的白鸟。",
			HELD = "毛茸茸的鸟。好鸟。",
		},
		ROBOT_PUPPET = "恐怖的椅子吓坏了它！",
		ROCK_LIGHT =
		{
			GENERIC = "一堆带壳的岩石！",
			OUT = "哈！又有东西可以砸了！",
			LOW = "起来越冷了。",
			NORMAL = "液态的火！",
        },
		ROCK = "真硬！就像我一样！",
		ROCKS = "是石头。你还缺什么？",
        ROOK = "这家伙可以越过皇后！",
		ROPE = "结实！就像我一样！",
		ROTTENEGG = "真臭！",
		SANITYROCK =
		{
			ACTIVE = "真美！",
			INACTIVE = "藏在地下。",
		},
		SAPLING =
		{
			BURNING = "哎呀。",
			WITHERED = "弱小的树受不了热。",
			GENERIC = "弱小的树！我比你强壮！",
			PICKED = "哈！哈！哈！树松松垂垂的！",
		},
		SEEDS = "小得不够塞牙缝。",
		SEEDS_COOKED = "火让它们变得更大，现在可以吃了。",
		SEWING_KIT = "会扎到手！",
		SHOVEL = "挖土的勺子！",
		SILK = "太奇特了。",
		SKELETON = "肌肉太少了。",
		SKELETON_PLAYER = "肌肉去哪儿了？！",
		SKULLCHEST = "这个人有个大脑袋！",
		SMALLBIRD =
		{
			GENERIC = "非常小的鸟。",
			HUNGRY = "小鸟饿了。",
			STARVING = "小鸟会饿死的。",
		},
		SMALLMEAT = "我要吃更多的肉！",
		SMALLMEAT_DRIED = "看起来像皮革，吃起来像肉。",
		SPAT = "看上去如此友好和逗人喜爱。",
		SPEAR = "它给了我一根长木条。",
		SPIDER =
		{
			DEAD = "一肚子黏乎乎的东西！",
			GENERIC = "他有张可怕的脸！",
			SLEEPING = "静悄悄地走，这样他可能不会发现我。",
		},
		SPIDERDEN = "虫子藏在那里面。",
		SPIDEREGGSACK = "恶心的蜘蛛卵。",
		SPIDERGLAND = "黏乎乎的，而且晃来晃去！",
		SPIDERHAT = "像是巨虫留下的污物。",
		SPIDERQUEEN = "哦，不！会走路的虫屋！",
		SPIDER_WARRIOR =
		{
			DEAD = "现在不可怕了！",
			GENERIC = "这只特别可怕。",
			SLEEPING = "去捅它可不太好。",
		},
		SPOILED_FOOD = "真恶心！",
		STATUEHARP = "优美的音乐在哪里？",
		STATUEMAXWELL = "他现在变成石头了！非常狡猾...",
		STEELWOOL = "像我的臂毛。",
		STINGER = "像烤肉叉一样尖！",
		STRAWHAT = "这帽子不错！",
		SUNKBOAT = "破船！",
		SWEATERVEST = "带图案的背心，适合花花公子。",
		TAFFY = "补充能量的太妃糖！",
		TALLBIRD = "世上最高的鸟！",
		TALLBIRDEGG = "里面有小鸟。",
		TALLBIRDEGG_COOKED = "烤熟的鸟。当早餐好极了！",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "小鸟冰冰凉！",
			GENERIC = "小鸟想要出来。",
			HOT = "对小鸟来说太热了！",
			LONG = "我等小鸟出来。",
			SHORT = "小鸟快出来了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "大鸟蛋！",
			PICKED = "空空如也的鸟巢。",
		},
		TEENBIRD =
		{
			GENERIC = "哈！没那么高。",
			HUNGRY = "它饿了，不停吵吵。",
			STARVING = "它饿了，不停吵吵还很愤怒！",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我无惧前方的挑战！",
			GENERIC = "奇怪的石头。我要坐上去吗？",
			LOCKED = "还是缺了什么东西。",
			PARTIAL = "现在都集齐了。",
		},
		TELEPORTATO_BOX = "有小手柄。",
		TELEPORTATO_CRANK = "这弯东西是金属做的！",
		TELEPORTATO_POTATO = "哈哈！哈哈！好丑的土豆！",
		TELEPORTATO_RING = "我会把它弯成完美的圆圈！",
		TENTACLE = "瘦长的怪物！",
		TENTACLESPOTS = "真恶心！黏黏的！",
        TENTACLESPIKE = "一钉一个准！",
		TENTACLE_PILLAR_HOLE = "你逃离强大的沃尔夫冈？",
		TENTACLE_PILLAR = "好多小朋友！",
		TENTACLE_PILLAR_ARM = "小触手崽子！哈！",
		TENTACLE_GARDEN = "嗯，看着可疑！",
		TOPHAT = "这帽子不错！",
		TORCH = "我用火把对抗黑夜。",
		TRAP = "没有陷阱能困住我！",
		TRAP_TEETH = "它会从下面咬屁股！",
		TRAP_TEETH_MAXWELL = "放这个的是个坏蛋！",
		TRINKET_1 = "玻璃球！",
		TRINKET_10 = "外观像珍珠的咀嚼者！",
		TRINKET_11 = "非常奇怪！",
		TRINKET_12 = "真讨厌。",
		TRINKET_2 = "假假的祝福你。",
		TRINKET_3 = "出乎沃尔夫冈的预料。",
		TRINKET_5 = "做什么用的？",
		TRINKET_6 = "机器人零件。",
		TRINKET_7 = "球进入木头孔。",
		TRINKET_8 = "经过硬化，像沃尔夫冈一样。",
		TRINKET_9 = "小小的钮扣。",
		TRUNKVEST_SUMMER = "暖和的毛茸茸的鼻子。",
		TRUNKVEST_WINTER = "舒服的大鼻子！",
		TRUNK_COOKED = "煮熟的鼻子。",
		TRUNK_SUMMER = "松垂的鼻子。",
		TRUNK_WINTER = "松垂的毛鼻子。",
		TURKEYDINNER = "鸟肉大餐。",
		TWIGS = "弱小的树枝！我可以轻松地折断它们！",
		UMBRELLA = "雨水对我健美的皮肤不好。",
		WAFFLES = "为什么面包上有孔？",
		WALL_HAY_ITEM = "杂乱的稻草！",
		WALL_STONE = "墙和我一样壮！",
		WALL_STONE_ITEM = "一堆石头！",
		WALL_RUINS = "古墙真结实！",
		WALL_RUINS_ITEM = "一堆古老的石头！",
		WALL_WOOD_ITEM = "扎人的棍子！",
		WALL_MOONROCK = "月亮石保护沃尔夫冈。",
		WALL_MOONROCK_ITEM = "可以用月亮的力量建造！",
		WALRUS = "哈哈，是个胖子。",
		WALRUSHAT = "海象的帽子！",
		WALRUS_CAMP =
		{
			EMPTY = "锁上了。",
			GENERIC = "他们怎么钻进去的？",
		},
		WALRUS_TUSK = "海牛男的牙齿！",
		WARDROBE = 
		{
			GENERIC = "衣箱！",
            BURNING = "火箱！",
			BURNT = "箱子没了。",
		},
		WARG = "大狗狗！",
		WASPHIVE = "脑袋说走。身体说上！",
		WETGOOP = "沃尔夫冈糟蹋了食物！",
		WINTERHAT = "它让耳朵在冷天很开心！",
		WORMHOLE =
		{
			GENERIC = "像个长在地上的软枕头。",
			OPEN = "它伤不到我这个汉子！",
		},
 		WORMHOLE_LIMITED = "看上去不太好。",
        ARMORRUINS = "保护我？我不需要！",
        BISHOP_NIGHTMARE = "愤怒的人。应该放松放松。",
        GREENAMULET = "这是啥玩意儿？", 
        GREENGEM = "漂亮而且压不碎。就像我一样！",
        KNIGHT_NIGHTMARE = "滑稽的金属人。",
        MINOTAUR = "强壮！就像我一样！我喜欢他！",    
        MULTITOOL_AXE_PICKAXE = "砍砍挖挖！我能干上一整天。",
        NIGHTMARELIGHT = "是灯，但不是什么好灯。",
        NIGHTMARE_TIMEPIECE =
        {
            WARN = "凶光快来了。",  
            WAXING = "凶光来了并且正在变强。", 
            STEADY = "我觉得凶光没有变强。", 
            WANING = "凶光时间正在结束。", 
            DAWN = "好时光快来了。", 
            CALM = "没有凶光。", 
            NOMAGIC = "没有凶光，安全了。", 
        },
        ORANGESTAFF = "我觉得还是走路好。",  
        ROOK_NIGHTMARE = "比不上我强壮的胸膛！",
        RELIC = "垃圾？",
        RUINS_RUBBLE = "打碎了更好。",  
        RUINS_BAT = "吓人。",
        RUINSHAT = "给国王戴的帽子。",
        SPIDER_DROPPER = "从天而降的可怕蜘蛛。", 
        THULECITE = "漂亮的石头。",
        YELLOWAMULET = "发黄光。",    
		ACCOMPLISHMENT_SHRINE = "我会打败你的，小箭头！",   

		WOODLEGS_CAGE = "锁上了。",
		AERODYNAMICHAT = "让强健的双腿一直自由地奔跑！",
		ANTIVENOM = "沃尔夫冈将用肌肉的力量把毒排出静脉。",
		ARMORCACTUS = "哈！现在来打沃尔夫冈试试。",
		ARMORLIMESTONE = "这件强大的护甲将保护我！",
		ARMOROBSIDIAN = "低劣的把戏，但沃尔夫冈喜欢！",
		ARMORSEASHELL = "现在来试试你们卑鄙的诡计吧，毒物们。",
		ARMOR_LIFEJACKET = "大海现在拿沃尔夫冈没办法了！",
		ARMOR_SNAKESKIN = "用来展示我强健的肌肉的。",
		ARMOR_WINDBREAKER = "沃尔夫冈是驭风大师！",
		ARMOUREDBOAT = "你很强壮，就像我一样。",
		BALLPHIN = "来和我战斗吧，海里的朋友！", 
		BAMBOO = "非常强大的建筑材料！",
		BAMBOOTREE =
		{
			BURNT = "现在不是很强大了。",
			CHOPPED = "我希望它长的很快。",
			GENERIC = "我很快将收割你，强大的植物！",
		},
		BERMUDATRIANGLE = "给我不安的感觉。",
		BIOLUMINESCENCE = "美丽的海上灯光！",
		BLOWDART_FLUP = "可以锻炼我强大的肺！",
		BLUBBER = "不是肌肉。",
		BLUBBERSUIT = "我宁愿穿一件肌肉套装！",
		BOAT = "强壮的船在和水战斗。",
		BOATCANNON = "威力最大的武器！",
		BOATREPAIRKIT = "修复我强大的船！",
		BOAT_LANTERN = "更安全的灯。",
		BOAT_TORCH = "船上装火把是个好主意！",
		BOTTLELANTERN = "驱逐黑暗的好方法。",
		BRAINJELLYHAT = "啊！它让沃尔夫冈思考！",
		BUOY = "啊，它标记着什么。",
		BURIEDTREASURE = "是我的！",
		BUSH_VINE =
		{
			BURNT = "化为灰烬。",
			CHOPPED = "我赢了。你输了。",
			GENERIC = "这是一丛藤蔓。",
		},
		CAPTAINHAT = "看沃尔夫冈！他现在是船长了！",
		CARGOBOAT = "多么强大的存储舱！",
		CHIMINEA = "别让风给吹灭了，小火苗。",
		CLOTHSAIL = "我将抓住你，风！",
		COCONADE =
		{
			BURNING = "烧得很快。",
			GENERIC = "威力巨大！",
		},
		COCONUT = 
		{
		    GENERIC = "沃尔夫冈要徒手把它压碎。",
		    PLANTED = "小树！非常小！",
		},
		COCONUT_COOKED = "椰子烤熟了。",
		COCONUT_HALVED = "劈开硬壳对沃尔夫冈来说不成问题。",
		COFFEE = "强劲，像沃尔夫冈一样！",
		COFFEEBEANS = "小豆子让沃尔夫冈有了力量！",
		COFFEEBEANS_COOKED = "苦味的豆子！",
		COFFEEBUSH =
		{
			BARREN = "好吃的豆子都去哪儿了？",
			GENERIC = "咖啡树很骄傲、强壮。",
			PICKED = "休息吧，朋友。",
			WITHERED = "它奄奄一息。",
		},
		CORAL = "非常漂亮！它会碎掉吗？",
		CORALREEF = "如此易碎！",
		CORAL_BRAIN = "嗬嗬。沃尔夫冈一碰它就咯吱吱响。",
		CORAL_BRAIN_ROCK = "沃尔夫冈的脑袋将打穿这个脑袋。",
		CRAB =
		{
			GENERIC = "在我一拳之下，它将变成食物。",
			HIDDEN = "别那么小气。",
		},
		CRABHOLE = "螃蟹是胆小鬼。",
		CRATE = "我能把它砸碎。",
		CUTLASS = "沃尔夫冈做好战斗准备了！",
		DEAD_SWORDFISH = "那是一场酣畅淋漓的战斗。",
		DOUBLE_UMBRELLAHAT = "两层伞好过一层。",
		DOYDOY = "小笨鸟！",
		DOYDOYBABY = "保护笨朋友，关爱笨朋友。",
		DOYDOYEGG = "生吃，对强壮的肌肉有好处！",
		DOYDOYEGG_COOKED = "傻乎乎的美味蛋白质。",
		DOYDOYEGG_CRACKED = "我应该在蠢鸟出来之前吃快点。",
		DOYDOYFEATHER = "为纪念善良的鸟。",
		DOYDOYNEST = "呆萌的朋友们睡觉的地方。",
		DRAGOON = "是时候进行肌肉屈伸比赛了？",
		DRAGOONDEN = "沃尔夫冈批准了。",
		DRAGOONEGG = "孵化出来和我战斗！",
		DRAGOONHEART = "在我手里胆战心惊。",
		DRAGOONSPIT = "哈！沃尔夫冈吐得远多了。",
		DUBLOON = "沃尔夫冈强有力的下颚在上面咬出了凹痕！",
		DUG_BAMBOOTREE = "我会把它带在身上。",
		DUG_BUSH_VINE = "我会把它带在身上。",
		DUG_COFFEEBUSH = "再也长不出这么给力的豆子了。",
		DUG_ELEPHANTCACTUS = "我要徒手把它拔出来！",
		EARRING = "也许是什么人掉的？",
		ELEPHANTCACTUS = "哎哟！还是很尖。",
		ELEPHANTCACTUS_ACTIVE = "弱小的仙人掌想挑战我！",
		ELEPHANTCACTUS_STUMP = "它没死，只是在睡觉。",
		FABRIC = "脆弱的织物。",
		FEATHERSAIL = "沃尔夫冈是大海的主人！",
		FISHINHOLE = "钓鱼的好地方。",
		FISH_RAW = "一块发臭的蛋白质。",
		FISH_RAW_SMALL = "可以吃的鱼块。",
		FISH_RAW_SMALL_COOKED = "现在看起来更好了。",
		FLAMEGEYSER = "看沃尔夫冈从这上面走过去！",
		FLOTSAM = "不是什么强大的船。",
		FLUP = "滚开！",
		FOOTBALLHAT = "它能保护我的脑袋！",
		FRESHFRUITCREPES = "男子汉的早午餐。",
		FROG_POISON = "懦弱的青蛙！",
		GASHAT = "小帽子五颜六色。",
		GOLDENMACHETE = "奢华的刀！",
		GRASS_WATER = "干渴的草。",
		HAIL_ICE = "冰冷的。",
		HOME = "待着的好地方。",
		HOUNDFIRE = "小火狗！",
		ICEMAKER =
		{
			HIGH = "机器精力充沛！",
			LOW = "小机器好像累了。",
			NORMAL = "感谢你的冰，机器。",
			OUT = "小机器没燃料了。",
			VERYLOW = "机器撑不了多久了。",
		},
		INVENTORYGRAVE = "有个小人来过这儿。",
		INVENTORYMOUND = "有个小人来过这儿。",
		IRONWIND = "旋转的帆！",
		JELLYFISH = "在我一拳之下，它将变成肉酱。",
		JELLYFISH_COOKED = "水母现在看上去很美味。",
		JELLYFISH_DEAD = "跟沃尔夫冈作对，它完全没有机会。",
		JELLYFISH_PLANTED = "它会掰腕子吗？",
		JELLYJERKY = "肉干很坚韧，像沃尔夫冈一样！",
		JUNGLETREE =
		{
			BURNING = "我弄死了它。",
			BURNT = "现在又小又破了。",
			CHOPPED = "哈！我赢了！",
			GENERIC = "树强壮而宏伟。",
		},
		JUNGLETREESEED =
        {
            GENERIC = "它可能成为树。",
            PLANTED = "现在它有更好的机会成为树。",
        },
		KNIGHTBOAT = "来战吧！",
		KRAKEN = "肮脏的流浪汉！",
		KRAKENCHEST = "它掉落了什么东西。",
		KRAKEN_TENTACLE = "你有好多手臂！",
		LAVAPOOL = "可惜。我忘了带游泳裤。",
		LIMESTONE = "为了制作小石头打碎了珊瑚。",
		LIMPETROCK =
		{
			GENERIC = "看上去像是用来吃的小蜗牛！",
			PICKED = "现在没有小蜗牛了。",
		},
		LIMPETS = "这是蜗牛？也许。",
		LIMPETS_COOKED = "滑溜溜的。",
		TREEGUARD = "树人！来跟我打一架！",
		LIVINGJUNGLETREE = "看上去像普通的树。",
		LOBSTER = "沃尔夫冈尊重带壳动物强有力的钳子。",
		LOBSTERHOLE = "甲壳生物的家。",
		LOBSTER_DEAD = "沃尔夫冈希望也有令人害怕的钳子！",
		LOBSTER_DEAD_COOKED = "现在可以吃了。",
		LOG =
		{
			BURNING = "沃尔夫冈的手伸到上面时感觉痒痒的。",
			GENERIC = "跟树搏斗留下的东西！",
		},
		LOGRAFT = "这个木筏...不太牢固。",
		LUGGAGECHEST = "沃尔夫冈将砸烂它并拿到财宝！",
		MACHETE = "啊！太好了！",
		MAGIC_SEAL = "为什么粘粘的？",
		MAGMAROCK = "愤怒的火山留下的岩石。",
		MAGMAROCK_FULL = "愤怒的火山留下的岩石。",
		MAGMAROCK_GOLD = "闪闪发亮的火山岩。",
		MAGMAROCK_GOLD_FULL = "闪闪发亮的火山岩。",
		MANDRAKE_COOKED = "植物小人可以吃了！",
		MANGROVETREE = "十分干渴。",
		MANGROVETREE_BURNT = "一点点热也承受不了！",
		MARSH_PLANT_TROPICAL = "弱小的灌木。",
		MERMFISHER = "来战吧！",
		MERMHOUSE_FISHER = "丑陋的房子！",
		MESSAGEBOTTLE = "沃尔夫冈的大手插不进去。",
		MESSAGEBOTTLEEMPTY = "只是个瓶子。",
		MONKEYBALL = "哈哈！愚蠢的猴人。",
		MOSQUITOSACK_YELLOW = "黄色吊袋。",
		MOSQUITO_POISON = "像个真正的男人一样战斗！",
		MUSSEL = "我的肌肉大了好多！",
		MUSSEL_COOKED = "贻贝成了长肌肉的蛋白质！",
		MUSSEL_FARM =
		{
			GENERIC = "名字真奇怪，它们明明没有肌肉。",
			STICKPLANTED = "可怜的生物，被我的棍子征服了！",
		},
		MUSSEL_STICK = "贻贝喜欢小棍子。",
		MYSTERYMEAT = "我强大的胃能对付它！",
		NEEDLESPEAR = "强大植物制作的武器！",
		OBSIDIAN = "这块石头中蕴藏着强大的火。",
		OBSIDIANAXE = "最强的斧子！",
		OBSIDIANCOCONADE = "威力更大！",
		OBSIDIANFIREPIT =
		{
			EMBERS = "黑暗来临了！",
			GENERIC = "沃尔夫冈干得不错！",
			HIGH = "火太大了！",
			LOW = "火不够热。",
			NORMAL = "熊熊的火焰温暖了沃尔夫冈的心。",
			OUT = "啊哦。火灭了。",
		},
		OBSIDIANMACHETE = "真锋利！",
		OBSIDIAN_WORKBENCH = "火桌子。",
		OCTOPUSCHEST = "把你的财宝给沃尔夫冈！",
		OCTOPUSKING = "强大的生物！给沃尔夫冈许多好东西！",
		OX = "多么强壮的野兽！",
		OXHAT = "我变得更强壮了！",
		OX_FLUTE = "沃尔夫冈将吹奏一首激昂的曲子。",
		OX_HORN = "强壮公牛的角！",
		PACKIM = "你好，可靠的朋友！",
		PACKIM_FISHBONE = "骨头。我喜欢。",
		PALMLEAF = "大绿叶。",
		PALMLEAF_HUT = "伟大的沃尔夫冈就该享受。",
		PALMTREE =
		{
			BURNING = "我弄死了它。",
			BURNT = "现在又小又破了。",
			CHOPPED = "哈！我赢了！",
			GENERIC = "多么快乐的树。",
		},
		PARROT = "爱唠叨的鸟！",
		PARROT_PIRATE = "它也许是个朋友？",
		PEACOCK = "爱现的鸟。",
		PEG_LEG = "最好的战利品！",
		PIGTENT = "猪的帐篷。",
		PIKE_SKULL = "沃尔夫冈不怕！",
		PIRATEGHOST = "啊~，妈呀！！",
		PIRATEHAT = "哈哈！我喜欢！",
		PIRATEPACK = "听起来叮当作响。",
		PIRATIHATITATOR =
		{
			BURNT = "它什么用也没有。",
			GENERIC = "奇怪的东西。",
		},
		POISONHOLE = "胆小的洞！",
		PORTAL_SHIPWRECKED = "你通往何处？",
		PRIMEAPE = "不像配得上我的样子。",
		PRIMEAPEBARREL = "小猴人的家。",
		RAFT = "小板子怎么承得起沃尔夫冈？",
		RAWLING = "沃尔夫冈球艺高超！",
		REDBARREL = "不要戳那个桶。",
		ROCK_CHARCOAL = "沃尔夫冈用它在眼睛下面涂抹以恐吓敌人！",
		ROCK_OBSIDIAN = "非常强大的岩石。沃尔夫冈想要拥有它。",
		ROWBOAT = "我将用强壮的手臂划船！",
		SAIL = "沃尔夫冈会爱上大海。",
		SAIL_STICK = "帆杆是航海神器！",
		SAND = "当沃尔夫冈握住它时，它从他强有力的大手中溜走了。",
		SANDBAG = "袋子可以吸水。",
		SANDBAGSMALL = "小袋子可以吸水。",
		SANDBAGSMALL_ITEM = "一大袋沙。",
		SANDBAG_ITEM = "袋子里装满了沙。",
		SANDHILL = "可轻松打碎的小丘。",
		SAND_CASTLE =
		{
			GENERIC = "用来踩不错！",
			SAND = "更像一堆沙子而不是城堡。",
		},
		SEAGULL = "它有一张大嘴。像我一样！",
		SEAGULL_WATER = "酣畅的战斗之后稍事休息，朋友？",
		SEASACK = "沃尔夫冈可以携带更多东西了！",
		SEASHELL = "小贝壳很容易压碎。",
		SEASHELL_BEACHED = "沃尔夫冈家里的桌上放着一碗这些东西。",
		SEATRAP = "小小的长钳子动物死定了。",
		SEAWEED = "来自大海的野草。",
		SEAWEED_COOKED = "沃尔夫冈强大的胃将摧毁这个！",
		SEAWEED_DRIED = "可以吃。",
		SEAWEED_PLANTED = "来自海洋的奇怪叶子。",
		SHADOWSKITTISH_WATER = "我不喜欢它！",
		SHARKITTEN = "沃尔夫冈是爱狗的人。",
		SHARKITTENSPAWNER =
		{
			GENERIC = "现在是小睡的时间吗？",
			INACTIVE = "只是沙而已。",
		},
		SHARK_FIN = "我弄丢了鲨鱼的其他部分。",
		SHARK_GILLS = "也许沃尔夫冈现在能在水下呼吸了？也许不能。",
		SHARK_TEETHHAT = "沃尔夫冈最喜欢的帽子！",
		SHARX = "我不信任这些海狗。",
		SHIPWRECKED_ENTRANCE = "是魔法传送门。全是沙...",
		SHIPWRECKED_EXIT = "是魔法传送门。长满了草...",
		SLOTMACHINE = "沃尔夫冈是个赌徒！",
		SNAKE = "我准备好战斗了！",
		SNAKEDEN =
		{
			BURNT = "化为灰烬。",
			CHOPPED = "我赢了。你输了。",
			GENERIC = "这是一丛藤蔓。",
		},
		SNAKEOIL = "适合用来让沃尔夫冈的肌肉变得油亮！",
		SNAKESKIN = "我会把它当做大围巾使用。",
		SNAKESKINHAT = "很好。",
		SNAKESKINSAIL = "死蛇的皮将帮助我航海。",
		SNAKE_FIRE = "你真是一条狡猾的蛇！",
		SNAKE_POISON = "毒液是懦夫用的武器！",
		SOLOFISH = "面对我吧，鱼！",
		SPEARGUN = "长矛现在可以发射了！",
		SPEAR_LAUNCHER = "远距离的猛击！",
		SPEAR_OBSIDIAN = "非常强大，热乎乎的矛。",
		SPEAR_POISON = "如果我用它，可不是因为懦弱。",
		SPOILED_FISH = "不再是好的了。",
		STUNGRAY = "看起来很光滑。我会摸摸它！",
		SUNKEN_BOAT =
		{
			ABANDONED = "没人在家。",
			GENERIC = "船长在哪？",
		},
		SUNKEN_BOAT_BURNT = "一堆烧焦的木头。",
		SUNKEN_BOAT_TRINKET_1 = "沃尔夫冈喜欢这些东西！",
		SUNKEN_BOAT_TRINKET_2 = "装不下沃尔夫冈！",
		SUNKEN_BOAT_TRINKET_3 = "湿得恰到好处。",
		SUNKEN_BOAT_TRINKET_4 = "金属小玩意儿很好玩。",
		SUNKEN_BOAT_TRINKET_5 = "坚韧的皮革很难嚼烂。",
		BANANAPOP = "沃尔夫冈一口就能吃光！",
		BISQUE = "给有力的拳击提供能量！",
		CEVICHE = "它在沃尔夫冈的肚子里更好！",
		SEAFOODGUMBO = "这将使沃尔夫冈变得非常强壮！",
		SURFNTURF = "很好。",
		SHARKFINSOUP = "里面有小鲨鱼？",
		MONSTERTARTARE = "太令人恶心了！",
		LOBSTERDINNER = "沃尔夫冈最适合吃这个！",
		LOBSTERBISQUE = "似乎很上档次。",
		JELLYOPOP = "看起来像糖果，但吃起来像肉！",
		SWEET_POTATO = "真甜！",
		SWEET_POTATO_COOKED = "可以吃了！",
		SWEET_POTATO_PLANTED = "这土豆里面的颜色很奇怪。",
		SWEET_POTATO_SEEDS = "土豆种子的味道更好。",
		SWIMMINGHORROR = "如果你想要战斗，沃尔夫冈奉陪！",
		SWORDFISH = "沃尔夫冈要跟你决斗！",
		TELEPORTATO_SW_BASE = "沃尔夫冈必须修好它。",
		TELEPORTATO_SW_BOX = "这个小盒子有什么用？沃尔夫冈想知道。",
		TELEPORTATO_SW_CRANK = "沃尔夫冈会紧紧抓住这个。",
		TELEPORTATO_SW_POTATO = "你好，矮挫子？",
		TELEPORTATO_SW_RING = "我会带上你。",
		TELESCOPE = "我看到了远方！",
		THATCHPACK = "沃尔夫冈强壮的肩膀能携带更多东西了！",
		TIDALPOOL = "脚趾头伸进去有鱼咬。",
		TIDAL_PLANT = "植物。",
		TIGEREYE = "它瞪了我一眼。",
		TIGERSHARK = "我会带你去兽栏！",
		TOUCAN = "鸟一看到沃尔夫冈就逃了。",
		TRAWLNET = "沃尔夫冈要把你困在网里！",
		TRAWLNETDROPPED =
		{
			GENERIC = "我会抓到什么鱼？",
			SOON = "真的在下沉了。",
			SOONISH = "在下沉了。",
		},
		TRIDENT = "我感觉像海洋之王。",
		TRINKET_13 = "沃尔夫冈不想喝。",
		TRINKET_14 = "沃尔夫冈不喜欢那个。",
		TRINKET_15 = "它不适合沃尔夫冈的大手。",
		TRINKET_16 = "我不知道这是什么。",
		TRINKET_17 = "坚韧的皮革很难嚼烂。",
		TRINKET_18 = "碎掉了。",
		TRINKET_19 = "沃尔夫冈才不会吃活络丸。",
		TRINKET_20 = "沃尔夫冈喜欢这些东西！",
		TRINKET_21 = "装不下沃尔夫冈！",
		TRINKET_22 = "看起来太干了。",
		TRINKET_23 = "彻底损坏了。",
		TROPICAL_FISH = "看起来很好吃。",
		TUNACAN = "我要徒手把它打开！",
		TURBINE_BLADES = "不能切东西的刀片。",
		TURF_SANDY = "踏脚石。",
		TURF_ASH = "踏脚石。",
		TURF_BEACH = "踏脚石。",
		TURF_DESERTDIRT = "踏脚石。",
		TURF_FUNGUS_GREEN = "踏脚石。",
		TURF_FUNGUS_RED = "踏脚石。",
		TURF_JUNGLE = "踏脚石。",
		TURF_MAGMAFIELD = "踏脚石。",
		TURF_MEADOW = "踏脚石。",
		TURF_SNAKESKINFLOOR = "踏脚石。",
		TURF_SWAMP = "踏脚石。",
		TURF_TIDALMARSH = "踏脚石。",
		TURF_VOLCANO = "踏脚石。",
		TWISTER = "多么强大！",
		TWISTER_SEAL = "哈哈！好朋友。",
		VENOMGLAND = "懦夫的武器。",
		VINE = "用来把敌人捆在一起。",
		VOLCANO = "它在呼唤我战斗！",
		VOLCANOSTAFF = "火山的力量在沃尔夫冈的手中！",
		VOLCANO_ALTAR =
		{
			GENERIC = "它现在不想要任何东西。",
			OPEN = "沃尔夫冈不敢用。",
		},
		VOLCANO_ALTAR_BROKEN = "用不了了。",
		VOLCANO_ALTAR_TOWER = "看起来很吓人。",
		VOLCANO_EXIT = "再见！",
		VOLCANO_SHRUB = "树太弱了。现在死了。",
		WALLYINTRO_DEBRIS = "它战败了。",
		WALL_LIMESTONE = "坚固耐用的墙。",
		WALL_LIMESTONE_ITEM = "我将搭建坚固的围墙。",
		WATERMELON_SEEDS = "也许能长成好吃的点心？",
		WATERYGRAVE = "我不喜欢这个，感觉毛骨悚然。",
		WHALE_BLUE = "我会吃了你！",
		WHALE_BUBBLES = "大鱼在下面。",
		WHALE_CARCASS_BLUE = "精彩的战斗，大鱼！",
		WHALE_CARCASS_WHITE = "威风不再。",
		WHALE_TRACK = "大鱼逃不出我的手掌心！",
		WHALE_WHITE = "大白鱼！跟沃尔夫冈战斗吧！",
		WILBUR_CROWN = "王冠要碎了！",
		WILBUR_UNLOCK = "欢迎，朋友！哈哈！",
		WILDBORE = "我要和你掰腕子。",
		WILDBOREHEAD = "真恶心！",
		WILDBOREHOUSE = "小房子装不下我。",
		WIND_CONCH = "海螺发出可怕的声音！",
		WOODLEGS_KEY1 = "吓人的钥匙！",
		WOODLEGS_KEY2 = "漂亮的钥匙！",
		WOODLEGS_KEY3 = "无趣的钥匙！",
		WRECK = "不够强壮，漂浮不了。",
		CALIFORNIAROLL = "到沃尔夫冈的肚子里来！",
		
	},
	DESCRIBE_GENERIC = "这是啥玩意儿？",
	DESCRIBE_TOODARK = "救命！太黑了！",
	DESCRIBE_SMOLDERING = "快要着火了。",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "现在没那么强大了！",
	},
}