return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "呃，為什麼我要現在幹那個？",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "也許我該等它沒注意的時候...",
			GENERIC = "不行。",
			NOBITS = "它已經剃毛了！",
		},
		WRITE =
        {
            GENERIC = "我不能在上面寫字。",
        },
		RUMMAGE =
        {   
            GENERIC = "我做不到。", 
        },
		COOK =
        {
            GENERIC = "我不太喜歡烹飪。",
            TOOFAR = "它離得那麼遠！",
        },
		STORE =
		{
			GENERIC = "已經滿了。",
			NOTALLOWED = "不讓放這裡。",
		},
		CHANGEIN =
        {
            GENERIC = "算了，太費勁了。",
            BURNING = "那比什麼愚蠢的衣服好多了！",
        },
        GIVE =
        {
            DEAD = "它們不會感激我的禮物。",
            SLEEPING = "現在不行。它在睡覺。",
            BUSY = "它在忙。",
        },
        TEACH =
        {
            KNOWN = "那個我早就知道了，老天！",
            CANTLEARN = "呃，隨便了，反正我也不想知道。",
        },
	},
	ACTIONFAIL_GENERIC = "我做不到！",
	ANNOUNCE_MAGIC_FAIL = "為什麼沒用！！",
	ANNOUNCE_ADVENTUREFAIL = "這次你贏了，麥斯威爾。",
	ANNOUNCE_BOOMERANG = "愚蠢的迴旋鏢！",
	ANNOUNCE_CHARLIE = "我不怕你！",
	ANNOUNCE_CHARLIE_ATTACK = "哎喲！你混蛋！",
	ANNOUNCE_COLD = "好冷！像冰火在燃燒！",
	ANNOUNCE_HOT = "這也太熱了點！",
	ANNOUNCE_DUSK = "夜晚就要來了。我需要火！",
	ANNOUNCE_WORMS = "我不想看到那個聲音是什麼東西發出來的！",
	ANNOUNCE_EAT =
	{
		GENERIC = "好吃！",
		PAINFUL = "呃！太難受了！",
		SPOILED = "太難吃了！",
		STALE = "吃起來有點噁心。",
		INVALID = "我怎麼可能吃那個！",
		YUCKY = "呸，絕不！",
	},
	ANNOUNCE_NOSLEEPONFIRE = "我擔心的只是坍塌而已。",
	ANNOUNCE_NODANGERSIESTA = "現在是戰鬥時間，不是午休時間！",
	ANNOUNCE_NONIGHTSIESTA = "待在那兒讓我覺得不舒服。",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "我寧願待在這裡面。",
	ANNOUNCE_NOHUNGERSIESTA = "肚子餓得咕咕叫時，我沒法午休！",
	ANNOUNCE_SHELTER = "除了可以燃燒以外，你還是有別的用處的。",
	ANNOUNCE_BURNT = "我真希望讓它就這樣燒掉...",
	ANNOUNCE_TOOL_SLIP = "幸好打火機還沒掉！",
	ANNOUNCE_DAMP = "啊哦！",
	ANNOUNCE_WET = "這可不是好事！",
	ANNOUNCE_WETTER = "我討厭這樣子！",
	ANNOUNCE_SOAKED = "啊，碰到最糟糕的情況了！",
	ANNOUNCE_HOUNDS = "現身吧！",
	ANNOUNCE_HUNGRY = "我需要食物！",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我會找到你的！",
	ANNOUNCE_HUNT_LOST_TRAIL = "噢...他消失了。",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "見鬼，它的蹤跡在這堆土裡消失不見了。",
	ANNOUNCE_ACCOMPLISHMENT= "轉動吧，箭頭！轉動吧！",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "搞定！",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "嘻嘻！",
		[2] = "好漂亮！",
		[3] = "哎呀！",
		[4] = "我放了一把火！",
		[5] = "燒吧！",
		[6] = "我忍不住！",
	},
	ANNOUNCE_PECKED = "不要！你這只壞鳥！",
	ANNOUNCE_TORCH_OUT = "我寶貴的光消失了！",
	ANNOUNCE_FAN_OUT = "愚蠢的東西壞掉了！",
    ANNOUNCE_COMPASS_OUT = "啊，指針卡住了！",
	ANNOUNCE_WORMHOLE = "我要把這些衣服全燒掉！",
	ANNOUNCE_TRAP_WENT_OFF = "啊！",
    ANNOUNCE_CRAFTING_FAIL = "我肯定是漏掉了什麼東西。",
    ANNOUNCE_QUAKE = "那個聲音聽起來不像是好事。",
    ANNOUNCE_NODANGERSLEEP = "沒時間睡覺，我必須得戰鬥！",
    ANNOUNCE_NOHUNGERSLEEP = "肚子餓得咕咕叫，睡不著！",
    ANNOUNCE_FREEDOM = "我自由了！該放火慶祝一下！",
    ANNOUNCE_RESEARCH = "這很有用，即使它跟火扯不上一點關係。",
    ANNOUNCE_NO_TRAP = "就像放火燒水桶裡的魚一樣白費力氣。",
    ANNOUNCE_HIGHRESEARCH = "好多資訊！",
    ANNOUNCE_THORNS = "哎喲！",
    ANNOUNCE_NODAYSLEEP_CAVE = "在這下面睡覺太恐怖了。",
    ANNOUNCE_BEES = "啊啊啊啊！螫人的蟲子！",
    ANNOUNCE_KNOCKEDOUT = "啊啊，我的小腦袋！",
    ANNOUNCE_LOWRESEARCH = "切，太無聊了。",
    ANNOUNCE_DEERCLOPS = "聽起來有一個怪物一樣的兇惡巨人走過來了！",
    ANNOUNCE_MOSQUITOS = "滾開，你這個吸血的混蛋！",
    ANNOUNCE_NODAYSLEEP = "當天空掛著一個大火球時，我是不會進裡面睡覺的。",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "它看起來開心一點了。",
	ANNOUNCE_CANFIX = "\n我覺得我能修好這個！",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "天上掉下來的火沒有燒到我。",
	ANNOUNCE_VOLCANO_ERUPT = "火山說話了！",
	ANNOUNCE_TREASURE = "這裡打了一個「X」！",
	ANNOUNCE_CRAB_ESCAPE = "可惡！它逃掉了！",
	ANNOUNCE_SHARX = "喂！別在那兒到處濺水了！",
	ANNOUNCE_MORETREASURE = "日子會越來越好的。",
	ANNOUNCE_OTHER_WORLD_TREASURE = "看起來不像這個地方的地圖。",
	ANNOUNCE_OTHER_WORLD_PLANT = "它不會生長的。也許我應該把它燒掉。",
	ANNOUNCE_MAPWRAP_WARN = "那片霧看起來很濃。",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "啊哦。我又走上了哪條路？",
	ANNOUNCE_MAPWRAP_RETURN = "我在那裡面什麼也看不到！",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"留言變模糊了。我看不清。",
	},
	ANNOUNCE_BOAT_DAMAGED = "我的船受傷了！",
	ANNOUNCE_BOAT_SINKING = "我要沉下去了！",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "永別了，殘酷的世界！",
	ANNOUNCE_ENTER_DARK = "我把打火機放哪兒了！？",
	ANNOUNCE_ENTER_LIGHT = "啊，我能看見了！我還以為我瞎了。",
	ANNOUNCE_INV_FULL = "我帶不了更多東西了！",
	ANNOUNCE_TRAWL_FULL = "可以收網了。",
	ANNOUNCE_UNIMPLEMENTED = "那個看起來很危險！燒了它！",
	ANNOUNCE_WAVE_BOOST = "嘩！",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "噢噢噢，附近有一條大魚。",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "噢，我追丟了！",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "水太湍急了，看不清！",

	BATTLECRY =
	{
		GENERIC = "不是你死，就是我活！",
		PIG = "蠢豬！",
		PREY = "放馬過來！",
		SPIDER = "咿咿咿咿呀！",
		SPIDER_WARRIOR = "呃，殺殺殺了它！",
	},
	COMBAT_QUIT =
	{
		GENERIC = "不出我所料！",
		PIG = "給我回來，豬排！",
		PREY = "下次我再來收拾你！",
		SPIDER = "切，下次我再幹掉他。",
		SPIDER_WARRIOR = "現在沒那麼強硬了！",
	},
	
	DESCRIBE =
	{
		BIGFISHINGROD = "好大！",
		DEVTOOL = "它在求人燒掉它。",
		DEVTOOL_NODEV = "它在求人燒掉它。",
		HOUNDFIRE = "我需要它！",
		INVENTORYGRAVE = "不是每個人都有本事來這裡混的。",
		INVENTORYMOUND = "不是每個人都有本事來這裡混的。",
		MANDRAKE_COOKED = "火焰讓這個植物傢伙安靜多了。",
		ROCK = "這個，像是一塊石頭。",
		SLURPERPELT = "如果我點著了它，它會發出很糟糕的氣味。非常糟糕。",
		TREECLUMP = "讓開。",
		TURF_DESERTDIRT = "地面太沒意思了。",
		TURF_FUNGUS_GREEN = "地面太沒意思了。",
		TURF_FUNGUS_RED = "地面太沒意思了。",
		TURF_SWAMP = "沼澤。",
		WATERMELON_SEEDS = "我可以種它們，但那聽起來很無聊。",
		WORMHOLE_LIMITED = "它幾乎奄奄一息了。",
		GLOMMER = "好毛茸茸啊！而且很黏...",
        GLOMMERFLOWER = 
        {
        	GENERIC = "為什麼不管什麼東西身上都長著一朵花？！",
        	DEAD = "不知道它可不可以燃燒...",
        },
        GLOMMERWINGS = "它們太小了！",
        GLOMMERFUEL = "又滑又膩，怪怪的。",
        BELL = "這是除夕嗎？會有焰火嗎？！",
        MOOSE_NESTING_GROUND = "呃，它聞起來像鳥屁股！",
        STATUEGLOMMER = 
        {	
        	GENERIC = "它應該是什麼東西嗎？",
        	EMPTY = "看上去好像是一樣的。",
    	},
		WEBBERSKULL = "雖然不是我的做事風格，但葬禮是一定要的。",
		MOLE =
		{
			HELD = "離開地面，投身火中。",
			UNDERGROUND = "不敢見光，嗯哼？",
			ABOVEGROUND = "鑽出地面偷瞄一眼！",
		},
		MOLEHILL = "它挖洞逃避烈日。違背自然規律。",
		MOLEHAT = "我不太確定這個...",
		NIGHTSTICK = "如果它下面有火的話，那會更酷的...",
		RABBITHOUSE=
		{
			GENERIC = "呃，愚蠢的兔子。",
			BURNT = "哈！幹得好。",
		},
		TURF_DECIDUOUS = "地面太沒意思了。",
		TURF_SANDY = "地面太沒意思了。",
		TURF_BADLANDS = "地面太沒意思了。",
		BEARGER = "哇哦！好...大的熊...",
		BEARGERVEST = "就像在軟軟的毛皮裡面游泳一樣。",
		ICEPACK = "毛茸茸的背包！",
		MOONROCKNUGGET = "對我來說只是另一塊石頭。",
		ROCK_MOON = "對我來說只是另一塊石頭。",
		BEARGER_FUR = "全都是毛皮。",
		FURTUFT = "黑白色的毛皮，上面全是毛！",
		BIGFOOT = "那究竟是個什麼鬼！",
		BONESHARD = "我不相信它們可以做成火種。",
		BUZZARD = "你的脖子太難看了。",
		CACTUS = 
		{
			GENERIC = "尖刺！這是我的弱點！你是怎麼知道的？",
			PICKED = "我們扯平了。",
		},
		CACTUS_MEAT_COOKED = "現在聞起來還不錯。",
		CACTUS_MEAT = "它看起來還是很危險。",
		CACTUS_FLOWER = "又是一種花。",
		COLDFIRE =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "不管什麼類型的火我都喜歡。",
			HIGH = "燒吧！燒得再旺點！再藍點！",
			LOW = "火太小了，真無聊。",
			NORMAL = "燒吧！",
			OUT = "嗚嗚嗚。一切都結束了。",
		},
		CATCOON = "這裡，貓咪！",
		CATCOONDEN = 
		{
			GENERIC = "有東西住在那裡時，我是不會燒掉它的。",
			EMPTY = "它已經完全乾枯了，可以燒了。",
		},
		CATCOONHAT = "好可愛的帽子。",
		COONTAIL = "我收藏過比這奇怪的東西。",
		COOKPOT =
		{
			COOKING_LONG = "火要做的工作還很多。",
			COOKING_SHORT = "火的工作就快完成了！",
			DONE = "很高興我用火做出食物了。",
			EMPTY = "我可以把食材放進去，然後在下面燒火。",
			BURNT = "至少它是在榮耀的火焰中毀滅的。",
		},
		EYEBRELLAHAT =	"如果戴上它的話，我不需要看它...",
		ARMORDRAGONFLY = "耶！讓火來得更猛烈些吧！！！",
		DRAGON_SCALES = "哇哦！我喜歡這個。",
		DRAGONFLYCHEST = "我搞不懂，你為什麼想要不能燃燒的東西...",
		DECIDUOUSTREE = 
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "燒了它更好。",
			GENERIC = "我猜它會燒得很旺。",
			POISON = "一把火就能讓它們老實。",
		},
		ACORN_COOKED = "看起來你終究變不成一棵樹了。",
		BIRCHNUTDRAKE = "啊！燒死它！",
		FARMPLOT =
		{
			GENERIC = "唉，這是一堆土。",
			GROWING = "加把勁，土堆。給我提供食物！",
			NEEDSFERTILIZER = "蠢東西又需要施肥了。",
			BURNT = "這是個不錯的結局。",
		},
		COLDFIREPIT =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "即使它是冷的火，我也可以盯著它幾個小時。",
			HIGH = "燒吧！燒得再旺點！再藍點！",
			LOW = "火太小了，真無聊。而且還是藍色的。",
			NORMAL = "燒吧！",
			OUT = "我應該重新把火點燃。",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "真希望你趕緊關上蓋子，不要再把火撲滅了。",
			OFF = "就保持這樣！",
			LOWFUEL = "燃料就快用完了。",
		},
		ICEHAT = "它真的會影響我心情。",
		LIGHTNINGGOAT = 
		{
			GENERIC = "好快活的山羊。",
			CHARGED = "你瘋了！",
		},
		LIGHTNINGGOATHORN = "把它放到耳朵上就能聽到雷電轟轟的聲音。",
		GOATMILK = "它被電給弄得不純了。真討厭。",
		MEATRACK =
		{
			DONE = "已經乾了！",
			DRYING = "拜託，肉塊，快點乾吧！",
			DRYINGINRAIN = "走開，討厭的雨！曬乾！",
			GENERIC = "我想要曬些肉乾！",
			BURNT = "也許火不是把肉弄乾的最好方法...",
		},
		MERMHEAD = 
		{
			GENERIC = "讓你這麼臭，這就是你的下場！",
			BURNT = "給你雙重打擊！",
		},
		MERMHOUSE = 
		{
			GENERIC = "沒人會在意它是否被燒燬。",
			BURNT = "真的沒有人在意。",
		},
		FLOWERSALAD = "我寧願吃一碗火苗。",
        ICECREAM = "嗯，有時候冷的東西也挺好的。",
        WATERMELONICLE = "在明明可以把水果燒掉的情況下，為什麼要把它凍住呢？",
        TRAILMIX = "嘎崩嘎崩嘎崩。",
        HOTCHILI = "這才是我要的那種火辣！",
        GUACAMOLE = "天啊，太好吃了！",
		MOOSE = "那究竟是個什麼鬼...",
		MOOSEEGG = "真的好大——！",
		MOSSLING = "它的羽毛看上去破破爛爛的。",
		FEATHERFAN = "我不知道...它可以滅火...",
		TROPICALFAN = "我不知道...它可以滅火...",
		GOOSE_FEATHER = "好暖和！",
		STAFF_TORNADO = "永遠在旋轉！轉向毀滅！",
		PIGHEAD = 
		{	
			GENERIC = "比起那傢伙，我的處境還不算太糟。",
			BURNT = "我猜它總是能變得更糟。",
		},
		PIGHOUSE =
		{
			FULL = "他在裡面幹一些豬的事情。",
			GENERIC = "這些豬在建築方面的品味真的很有問題",
			LIGHTSOUT = "你個蠢貨！讓我進去！",
			BURNT = "裝修工作做得不錯！",
		},
		FERTILIZER = "滿滿的一桶髒東西。",
		RAINOMETER = 
		{	
			GENERIC = "雨火不兩立。切！",
			BURNT = "嚐到我的厲害了吧，臭雨！",
		},
		RAINCOAT = "這會達到我要的效果的。",
		RAINHAT = "可以讓我不被雨淋的東西。",
		RESEARCHLAB = 
		{	
			GENERIC = "即使有些東西我不知道...這也只是暫時的。",
			BURNT = "現在再也無法從那裡學習新東西了。",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "即使有些東西我不知道...這也只是暫時的。",
			BURNT = "現在再也無法從那裡學習新東西了。",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "它散發著黑暗而強大的能量。",
			BURNT = "現在它只是黑，談不上強大了。",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "我可以把那個帽子當作巫師施符咒的大鍋！",
			BURNT = "不辭辛勞，不辭...哎呀，不好。它燒掉了。",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "那是我的保險單。",
			BURNT = "我的保險單作廢了。",
		},
		ROCK_ICE = 
		{
			GENERIC = "我覺得無論用什麼方法都不可能把它點燃。",
			MELTED = "就和水一樣毫無用處。",
		},
		ROCK_ICE_MELTED = "就和水一樣毫無用處。",
		ICE = "好冰。",
        REFLECTIVEVEST = "這背心太時髦了。",
		HAWAIIANSHIRT = "不知道它會不會和真花一樣那麼易燃。",
		TENT = 
		{
			GENERIC = "我可是獲得過所有勳章的女童子軍。",
			BURNT = "沒關係，我還有我的勳章。",
		},
		SIESTAHUT = 
		{
			GENERIC = "我在參加女童子軍的時候，學會了怎麼做這些東西。",
			BURNT = "我總是會讓它們著火。",
		},
		TRANSISTOR = "電子元件—元件—。",
		TREASURECHEST = 
		{
			GENERIC = "可以幫我裝東西的箱子。",
			BURNT = "箱子已經徹底燒燬了。",
		},
		TUMBLEWEED = "它看起來極易燃。",
		GRASS_UMBRELLA = "太漂亮了！",
		PALMLEAF_UMBRELLA = "真漂亮！",
		UNIMPLEMENTED = "還沒完成。但我打賭它還是能燃燒。",
		WALL_HAY = 
		{	
			GENERIC = "看起來是一點就燃！",
			BURNT = "它確實是易燃的！",
		},
		WALL_WOOD = 
		{
			GENERIC = "那東西很容易著火的。",
			BURNT = "它確實著火了！",
		},
		WARG = "You're a big mean jerk!",
		WATERMELON = "我以前認識一個叫西瓜的人。他是個混蛋。",
		WATERMELON_COOKED = "溫暖、甜蜜、多汁。",
		WATERMELONHAT = "好吧，這是這種水果的用途之一。",
		WINTEROMETER = 
		{
			GENERIC = "如果它能測量火的話會更好。",
			BURNT = "如果你能測量火的話，也許你就能早做準備，不會被燒了！",
		},
		HOME = "I'm gonna burn it.",
		HOMESIGN = 
		{
			GENERIC = "少讀！多燒！",
			UNWRITTEN = "我該在它上面燒出點什麼記號。",
			BURNT = "哈哈哈，沒錯，就是這樣！",
		},
		BEEBOX =
		{
			READY = "耶！我可以偷蜂蜜囉！",
			FULLHONEY = "耶！我可以偷蜂蜜囉！",
			GENERIC = "趕緊的，肥蜜蜂，趕緊給我產蜂蜜！",
			NOHONEY = "這裡什麼也沒有。",
			SOMEHONEY = "耐心點。",
			BURNT = "用煙把你燻出來！",
		},
		LIVINGTREE = "它也許是活的，不過它還是會燃燒。",
		ICESTAFF = "太太太太無趣了。",
		WORMLIGHT = "沒有火卻能發光。太不正常了。",
		WORMLIGHT_LESSER = "感覺像是奶奶的手。",
		WORM =
		{
		    PLANT = "沒有火卻能發光。太不正常了。",
		    DIRT = "泥土通常會動嗎？",
		    WORM = "它身上長了好多毛！",
		},
		WORMLIGHT_PLANT = "沒有火卻能發光。太不正常了。",
		EEL = "我不喜歡它的表情！",
		EEL_COOKED = "有了火，一切都變好了。",
		UNAGI = "你可以把它做得很漂亮，但它還是鰻魚。",
		EYETURRET = "我希望它能讓東西點燃。",
		EYETURRET_ITEM = "等我把它放好，它才能發揮作用。",
		MINOTAURHORN = "我想知道這些圈圈是否代表年齡。",
		MINOTAURCHEST = "我想要那樣的大角！",
		THULECITE_PIECES = "這塊銩礦已經成了碎片。",
		POND = "這片池塘肯定燒不起來。太無趣了。",
		POND_ALGAE = "它肯定需要大量的水。",
		GREENSTAFF = "雖然它無法用來生火，但我猜它還是很有用。",
		POTTEDFERN = "我寧願燒掉它們。",

		THULECITE = "我覺得它應該不會燃燒。",
		ARMORRUINS = "我不確定要不要穿這個。",
		RUINS_BAT = "這可以讓那些壞蛋不敢靠近我。",
		RUINSHAT = "似乎有什麼東西在其中流動。",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "感覺沒什麼異常。",	--Calm phase
			WARN = "它在警告我。",	--Before nightmare
			WAXING = "魔法能量甦醒了！", --Nightmare Phase first 33%
			STEADY = "它幾乎在嗡嗡作響。", --Nightmare 33% - 66%
			WANING = "魔法能量正在平靜下來。", --Nightmare 66% +
			DAWN = "我猜一切快結束了。", --After nightmare
			NOMAGIC = "它好像停止工作了。", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "啊——！",
		ROOK_NIGHTMARE = "它的笑容很猥瑣。",
		KNIGHT_NIGHTMARE = "它看上去很破舊。",
		MINOTAUR = "可憐的傢伙。被困在了這個迷宮裡。",	--Monster in labyrinth
		SPIDER_DROPPER = "它們是從上面下來的。",	--White spider that comes from the roof
		NIGHTMARELIGHT = "不用火就可以照明實在是不正常。",	--Lights that activate during nightmare.
		GREENGEM = "這個寶石感覺真的好亮。",
		RELIC = "I guess someone lived here before.",	--Fixed relic
		RUINS_RUBBLE = "也許我可以把它修好。",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "這東西太有用了！",	--Works as axe and pickaxe
		ORANGESTAFF = "它讓我頭疼。",	--Teleports player.
		YELLOWAMULET = "它似乎能夠把周圍的黑暗都吸進去。",	--Emits light, player walks faster.
		GREENAMULET = "戴著它我感覺自己的思維都開闊了。",	--Reduce cost of crafting

		SLURPER = "它們肚子裡有火嗎？",
		SLURPER_PELT = "咦，它還是活的！",
		ARMORSLURPER = "呃，呸！呸！呸！呸！真噁心！",
		ORANGEAMULET = "它在幫我撿燃料！",
		YELLOWSTAFF = "太神奇了。",
		YELLOWGEM = "它在閃閃發光。",
		ORANGEGEM = "這東西刺痛我的手指了。",
		PALMTREE =
        {
			BURNING = "哇！好多火！",
			BURNT = "重大改進。",
			CHOPPED = "好幾下才把它砍倒。",
			GENERIC = "你的樹枝少得出奇。",
		},
		TELEBASE = 
		{
			VALID = "我可以感覺到魔力的存在！",
			GEMS = "它還需要一些東西。",
		},
		GEMSOCKET = 
		{
			VALID = "它們究竟是如何浮在空中的？",
			GEMS = "上面是空的！",
		},
		STAFFLIGHT = "太漂亮了！",

        LIGHTER = "它是我的幸運打火機！",


        ANCIENT_ALTAR =
        {
        	WORKING = "哇！與來世相通。",
        	BROKEN = "死靈無法從這裡出去。",
        },  
        ANCIENT_ALTAR_BROKEN = "死靈無法從這裡出去。",

        ANCIENT_STATUE = "該死，又不會燃燒。",

        LICHEN = "一種令人噁心的、有硬皮的植物",
		CUTLICHEN = "呸，一股鋸屑的味道。",

        CAVE_BANANA = "香蕉！",
        CAVE_BANANA_COOKED = "好吃！",
        CAVE_BANANA_BURNT = "那就是我想要的一切！",
        CAVE_BANANA_TREE = "看起來可以燃燒！",
        ROCKY = "我們可沒有多少共同點。",

        BLUEAMULET = "切。",
		PURPLEAMULET = "這科技是不是有點走偏了？",
		TELESTAFF = "它用起來就像一陣風。",
		MINERHAT = "雖然不是真正的火光，但還是很有趣。",
		MONKEY = "開個玩笑！我可以點燃這坨便便。",
		MONKEYBARREL = "多麼棒的家，一下子就能燒起來。",

		HOUNDSTOOTH="好鋒利。我喜歡！",
		ARMORSNURTLESHELL="更少防守！更多進攻！",
		BAT="可愛的小傢伙！",
		BATBAT = "我可以用它來對付敵人。",
		BATWING="呸！",
		BATWING_COOKED="呸！",
		BEDROLL_FURRY="褶邊太多了。",
		BUNNYMAN="呃，它們看起來好蠢。",
		FLOWER_CAVE="它裡面在燃燒。",
		FLOWER_CAVE_DOUBLE="它裡面在燃燒。",
		FLOWER_CAVE_TRIPLE="它裡面在燃燒。",
		GUANO="它燒起來和普通糞便沒什麼區別。",
		LANTERN="烈火不應該受到這樣的束縛！",
		LIGHTBULB="這個燈泡有點重。",
		MANRABBIT_TAIL="我吵贏了。",
		MUSHTREE_TALL=
		{
            GENERIC = "Gross. This tree is sick all over.",
            BLOOM = "Ack! It stinks!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Gross. It smells like leprechaun butt.",
            BLOOM = "It's spreading junk everywhere.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Gross. It's all mushroomy.",
            BLOOM = "Ew, I don't want to get too close.",
        },
        MUSHTREE_TALL_WEBBED = "那一棵罪有應得。",
        SPORE_TALL = "它像五顏六色的火花！",
        SPORE_MEDIUM = "它像五顏六色的火花！",
        SPORE_SMALL = "它像五顏六色的火花！",
        SPORE_TALL_INV = "它很容易點燃的感覺。",
        SPORE_MEDIUM_INV = "它很容易點燃的感覺。",
        SPORE_SMALL_INV = "它很容易點燃的感覺。",
		MUSHTREE_TALL="噁心。這棵樹已經病入膏肓了。",
		MUSHTREE_MEDIUM="噁心。聞起來像小妖精的屁股",
		MUSHTREE_SMALL="噁心。它從頭到尾都像蘑菇。",

		SLURTLE="我想要把它炸飛！",
		SLURTLE_SHELLPIECES="呵呵。它碎了。",
		SLURTLEHAT="很適合我的腦袋。",
		SLURTLEHOLE="我應該把它們都燒掉。",
		SLURTLESLIME="我愛死這玩意兒了！",
		SNURTLE="砰！",
		SPIDER_HIDER="真是個難搞的傢伙！",
		SPIDER_SPITTER="放馬過來！",
		SPIDERHOLE="裡面全是蜘蛛。",
		STALAGMITE="石頭真無趣。",
		STALAGMITE_FULL="石頭真無趣。",
		STALAGMITE_LOW="石頭真無趣。",
		STALAGMITE_MED="石頭真無趣。",
		STALAGMITE_TALL="又是無趣的岩石。",
		STALAGMITE_TALL_FULL="又是無趣的岩石。",
		STALAGMITE_TALL_LOW="又是無趣的岩石。",
		STALAGMITE_TALL_MED="又是無趣的岩石。",

		TURF_CARPETFLOOR = "地面太沒意思了。",
		TURF_CHECKERFLOOR = "地面太沒意思了。",
		TURF_DIRT = "地面太沒意思了。",
		TURF_FOREST = "地面太沒意思了。",
		TURF_GRASS = "地面太沒意思了。",
		TURF_MARSH = "地面太沒意思了。",
		TURF_ROAD = "地面太沒意思了。",
		TURF_ROCKY = "地面太沒意思了。",
		TURF_SAVANNA = "地面太沒意思了。",
		TURF_WOODFLOOR = "地面太沒意思了。",
		TURF_DRAGONFLY = "我的打火機對它沒用。",

		TURF_CAVE="地面太沒意思了。",
		TURF_FUNGUS="地面太沒意思了。",
		TURF_SINKHOLE="地面太沒意思了。",
		TURF_UNDERROCK="地面太沒意思了。",
		TURF_MUD="地面太沒意思了。",
		
		TURKEYDINNER = "一場烤鳥盛宴！",
		TWIGS = "一堆小樹枝。和其他東西一樣，也是很好的燃料。",
		POWCAKE = "我想知道它能不能燃燒。",
        CAVE_ENTRANCE = 
        {
            GENERIC="Who plugged that hole?",
            OPEN = "I hope there's lava down there somewhere.",
        },
        CAVE_EXIT = "It's too dark and stuffy down here.",
        CAVE_ENTRANCE = "誰把那個洞給堵上的？",
        CAVE_ENTRANCE_RUINS = "誰把那個洞給堵上的？",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "我不想進去那個討厭的洞！",
            OPEN = "我希望下面某個地方會有熔岩。",
        },
        CAVE_EXIT = 
        {
            GENERIC = "反正這裡更陰涼。",
            OPEN = "這下面太黑又太悶。",
        },

		MAXWELLPHONOGRAPH = "我喜歡更刺激的音樂。",
		PIGGUARD = "我喜歡他的態度！",
		BOOMERANG = "它不是最讓人興奮的武器。",
		ADVENTURE_PORTAL = "也許那是回家的路。",
		AMULET = "我是無敵的！好吧，或許不是。但這樣感覺不錯。",
		ANIMAL_TRACK = "它會引導我找到新朋友。",
		ARMORGRASS = "浪費這麼多易燃材料。",
		ARMORMARBLE = "如果我要去戰鬥，最好先做好保護工作。",
		ARMORWOOD = "現在，我可以挑戰整個世界了！",
		ARMOR_SANITY = "像被包裹在煙霧裡一樣。",
		ASH =
		{
			GENERIC = "燒完後剩下的東西。真希望火還沒滅。",
			REMAINS_GLOMMERFLOWER = "真希望我看到了這朵奇怪的花是怎麼燃燒的。",
			REMAINS_EYE_BONE = "我猜這個長著眼睛的東西燃燒起來肯定相當壯觀！",
			REMAINS_THINGIE = "不管這東西是什麼，我都希望它能繼續燃燒。",
		},
		AXE = "它非常鋒利。",
		BABYBEEFALO =
		{
			GENERIC = "即使是犛牛寶寶，看上去也很醜。",
			SLEEPING = "醒醒！",
		},
		BACKPACK = "我可以往裡面裝比如說一百萬個打火機。",
		BACONEGGS = "溏心蛋黃部分有點噁心，但是培根非常美味！",
		BANDAGE = "呃，一定要這麼做嗎？",
		BASALT = "太難鑿碎了！",
		BEARDHAIR = "呃，這東西從哪兒來的？",
		BEDROLL_STRAW = "一股霉臭味。",
		BEE =
		{
			GENERIC = "很肥的蜜蜂，不過它的刺看起來很危險。",
			HELD = "滿袋子的蜜蜂！",
		},
		BEEFALO =
		{
			FOLLOWER = "呃，你在跟著我嗎？",
			GENERIC = "多麼噁心的長毛野獸！",
			NAKED = "哈！他身上一根毛也沒有了！",
			SLEEPING = "它們睡著的時候樣子更傻。",
		},
		BEEFALOHAT = "我剃了他的毛，做成帽子戴在自己的頭髮上！",
		BEEFALOWOOL = "哈！我偷了他的毛！",
		BEEHIVE = "裡面全是蜜蜂！",
		BEEMINE = "裡面有蜜蜂。應該再往那裡放點火。",
		BEEMINE_MAXWELL = "裡面有蚊子。它們聽起來可不太高興。",
		BEEHAT = "這可以防止那些螫人的蜜蜂接近我。",
		BERRIES = "紅色漿果最好吃。",
		BERRIES_COOKED = "烤過之後的紅色漿果味道更好。",
		BERRYBUSH =
		{
			BARREN = "吃屎吧，愚蠢的植物！",
			WITHERED = "全部乾枯了。正好用來點火！",
			GENERIC = "嗯。漿果。",
			PICKED = "我想要更多的漿果！",
		},
		BIRDCAGE =
		{
			GENERIC = "鳥的牢籠！",
			OCCUPIED = "哈！抓到你了！",
			SLEEPING = "蠢鳥。醒醒！",
			HUNGRY = "鬧什麼呢？",
			STARVING = "它不肯安靜！",
			DEAD = "至少他現在安靜了。",
			SKELETON = "我也許應該把那個清掃一下。",
		},
		BIRDTRAP = "我會抓住那些臭鳥的。",
		BIRD_EGG = "聞起來像鳥屁股一樣。",
		BIRD_EGG_COOKED = "呸。黃色的部分還沒凝固。",
		BISHOP = "是主教！",
		BISHOP_CHARGE_HIT = "哎喲！",
		BLOWDART_FIRE = "這是全世界我最喜歡的東西。",
		BLOWDART_SLEEP = "被催眠的東西容易點火。",
		BLOWDART_PIPE = "練好這個，給火吹風就不費勁了。",
		BLUEGEM = "呃，這玩意兒好醜。",
		BLUEPRINT = "這可以省去一些實驗。",
		BELL_BLUEPRINT = "這可以省去一些實驗。",
		BLUE_CAP = "一股運動後的臭襪子的味道！",
		BLUE_CAP_COOKED = "我用火改變了它！",
		BLUE_MUSHROOM =
		{
			GENERIC = "愚蠢的蘑菇。",
			INGROUND = "喂！你！給我出來！",
			PICKED = "也許有一天它會再長回來。",
		},
		BOARDS = "木板。它們也會燃燒，就和其他木材一樣。",
		BONESTEW = "只需要給食物加把火，瞧！",
		BUGNET = "我能抓到蟲子！",
		BUSHHAT = "太被動了！",
		BUTTER = "很美味，只是有點昆蟲的味道。",
		BUTTERFLY =
		{
			GENERIC = "飛走吧，蝴蝶！",
			HELD = "我想捏它。",
		},
		BUTTERFLYMUFFIN = "嘻嘻，看起來像蝴蝶被困在鬆餅蛋糕裡面一樣。",
		BUTTERFLYWINGS = "那隻蝴蝶不會再飛了！",
		CAMPFIRE =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "我喜歡火。",
			HIGH = "燒吧！燒得再旺點！",
			LOW = "火太小了，真無聊。",
			NORMAL = "燒吧！",
			OUT = "嗚嗚嗚。一切都結束了。",
		},
		CANE = "有了這個，走起路來容易多了！",
		CARROT = "呸。全是蔬菜。",
		CARROT_COOKED = "雖然還是一股蔬菜味，但經火烤過的味道要好些。",
		CARROT_PLANTED = "也許地下有它特別的胡蘿蔔朋友。",
		CARROT_SEEDS = "難吃的橙色蔬菜的種子。",
		CAVE_FERN = "看上去可以燃燒。",
		CHARCOAL = "嗯。火的味道。",
        CHESSJUNK1 = "上發條的馬，已經死了。",
        CHESSJUNK2 = "死去的發條主教。",
        CHESSJUNK3 = "上發條的城堡，已經死了。",
		CHESTER = "他毛茸茸的！",
		CHESTER_EYEBONE =
		{
			GENERIC = "盯著人看是很沒禮貌的。",
			WAITING = "至少它不再盯著我了。",
		},
		COOKEDMEAT = "沒有調味的肉...好極了。",
		COOKEDMONSTERMEAT = "還是很噁心。",
		COOKEDSMALLMEAT = "如果我想活下來的話，光開胃菜可是不夠的。",
		CORN = "甜甜的蔬菜，好吃！",
		CORN_COOKED = "哦，這東西丟進火裡會爆！",
		CORN_SEEDS = "玉米種子，會爆炸的玉米可是我最愛的蔬菜了。",
		CROW =
		{
			GENERIC = "我猜它是在等我死掉。",
			HELD = "聰明不起來了，對嗎？",
		},
		CUTGRASS = "乾草是很好的燃料，也可以用來合成其他東西。",
		CUTREEDS = "採下的蘆葦是很好的燃料。也可以用來合成其他東西。",
		CUTSTONE = "完全是四四方方的，看著真舒服。",
		DEADLYFEAST = "連火也治不了這盤菜的卑鄙本性。",
		DEERCLOPS = "哇靠！",
		DEERCLOPS_EYEBALL = "不准再盯著我！",
		DIRTPILE = "是誰走的時候在森林裡留下了這一堆泥土？",
		DIVININGROD =
		{
			COLD = "它在發出某種噪聲。",
			GENERIC = "它全身上下都是電子垃圾。",
			HOT = "討厭！別再嗶嗶嗶地叫了！",
			WARM = "這東西越來越吵了。",
			WARMER = "一定很近了！",
		},
		DIVININGRODBASE =
		{
			GENERIC = "不知道這是用來幹嘛的。看起來不像是能夠燃燒的東西。",
			READY = "只需要用鑰匙解鎖就可以了。很遺憾，不是用火來解鎖。",
			UNLOCKED = "它在發出呼呼的聲音！",
		},
		DIVININGRODSTART = "我要用它搞點名堂出來。",
		DRAGONFLY = "它肚子裡面都是火！",
		LAVASPIT = 
		{
			HOT = "全世界最酷的噴火坑！",
			COOL = "噴火坑變冷了。",
		},
		LAVA_POND = "好！太好了！",
		LAVAE = "為什麼我們不能做朋友？",
		LAVAE_PET = 
		{
			STARVING = "我能看到她的肋骨！",
			HUNGRY = "我覺得她想燒點東西。",
			CONTENT = "我自家的小火龍。",
			GENERIC = "她...太完美了。",
		},
		LAVAE_EGG = 
		{
			GENERIC = "我感覺有火焰想要逃出來。",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "它在打寒顫。",
			COMFY = "那隻蛋看起來很快樂。",
		},
		LAVAE_TOOTH = "希望她不會咬人。",
		DRAGONFRUIT = "它看上去有幾分像火！",
		DRAGONFRUIT_COOKED = "現在看起來更像是把水果放在烈火中一樣。",
		DRAGONFRUIT_SEEDS = "那個看起來像火一樣的水果的種子。",
		DRAGONPIE = "做成派的火龍果？我的乖乖！",
		DRUMSTICK = "整天都在砰砰砰擊鼓！",
		DRUMSTICK_COOKED = "我是用它來填飽肚子呢還是用它來敲鼓？",
		DURIAN = "呃，好臭！",
		DURIAN_COOKED = "呸，聞起來就像是東西煮壞了一樣！",
		DURIAN_SEEDS = "臭水果的臭種子。",
		EARMUFFSHAT = "聞上去像是兔子的屁股。",
		EGGPLANT = "絕對不是鳥。",
		EGGPLANT_COOKED = "火讓茄子變得更美味了。",
		EGGPLANT_SEEDS = "這些種子會長成一株植物還是一隻小鳥？",
		STUFFEDEGGPLANT = "它仍然不是鳥，不過我在它裡面塞了東西，現在看起來就像一隻鳥！",
		DUG_BERRYBUSH = "怎麼了，沒有土了嗎？",
		DUG_GRASS = "怎麼了，沒有土了嗎？",
		DUG_MARSH_BUSH = "怎麼了，沒有土了嗎？",
		DUG_SAPLING = "怎麼了，沒有土了嗎？",
		EARMUFFS = "聞上去像是兔子的屁股。",
		ACORN = 
		{
		    GENERIC = "嘿，你好啊，大樹種子。",
		    PLANTED = "你很快就會長成一棵真正的樹的。",
		},
		EVERGREEN =
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "世上又少了一棵樹。",
			GENERIC = "看起來它會燒得很旺。",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "世上又少了一棵樹。",
			GENERIC = "在火中結束吧！",
		},
		EYEPLANT = "它們像火一樣迅速擴散。",
		FEATHERHAT = "我就是涅槃的鳳凰！",
		FEATHER_CROW = "烏鴉羽毛。它燃燒起來也許很難聞。",
		FEATHER_ROBIN = "紅雀羽毛。它燃燒起來也許很難聞。",
		FEATHER_ROBIN_WINTER = "雪雀羽毛。它燃燒起來也許很難聞。",
		FEM_PUPPET = "她看起來已經被嚇得半死。",
		FIREFLIES =
		{
			GENERIC = "真希望它們沒有跑掉！",
			HELD = "它們就像是裝在我口袋裡的小火苗！",
		},
		FIREHOUND = "實際上我還挺喜歡那傢伙的。",
		FIREPIT =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "我可以幾個小時一直盯著它看。",
			HIGH = "燒吧！燒得再旺點！",
			LOW = "火太小了，真無聊。",
			NORMAL = "燒吧！",
			OUT = "我應該重新把火點燃。",
		},
		FIRESTAFF = "這絕對是我最喜愛的玩具。",
		FISH = "滑不溜秋的魚！",
		FISHINGROD = "用魚鉤、釣魚線和墜子來釣魚。",
		FISHSTICKS = "所見即所得。瞧，炸魚排。",
		FISHTACOS = "真是方便好拿的魚肉玉米捲。",
		FISH_MED = "是時候把它丟進火裡了！",
		FISH_MED_COOKED = "它確實有點像能吃的樣子。",
		FISH_COOKED = "烤過之後的魚沒之前那麼滑溜溜了。",
		FLINT = "可憐人的打火石。",
		FLOWER = "我可沒有時間浪費在花朵上。",
		FLOWERHAT = "花環。可惜不是正在燃燒的花環。",
		FLOWER_EVIL = "呃，太難聞了。",
		FOLIAGE = "不錯的燃料。",
		FOOTBALLHAT = "運動可不是那麼容易。",
		FROG =
		{
			DEAD = "我讓他嚐到我的厲害了！",
			GENERIC = "他太潮濕了，燒不起來。",
			SLEEPING = "他們睡著的時候好可愛。",
		},
		FROGGLEBUNWICH = "也許我不會注意到三明治裡面夾的是青蛙腿。",
		FROGLEGS = "它時不時的還在抽搐。太奇怪了。",
		FROGLEGS_COOKED = "是火讓它停止抽搐的。火最好了。",
		FRUITMEDLEY = "好吃的水果！",
		GEARS = "這些會讓它們動起來的。",
		GHOST = "我無法殺死一個本來就已經死了的人。",
		GOLDENAXE = "雖然它無法讓樹著火，但至少它會閃閃發光。",
		GOLDENPICKAXE = "雖然它無法讓石頭著火，但至少它會閃閃發光。",
		GOLDENPITCHFORK = "雖然它無法讓地面著火，但至少它會閃閃發光。",
		GOLDENSHOVEL = "雖然它無法用來挖火坑，但至少它會閃閃發光。",
		GOLDNUGGET = "我該在哪裡花掉這個。",
		GRASS =
		{
			BARREN = "它需要施肥。",
			WITHERED = "又乾又枯，正好燒掉！",
			BURNING = "燒吧！哇！",
			GENERIC = "一叢易燃的草。",
			PICKED = "草茬沒什麼用。",
		},
		GREEN_CAP = "真乏味！",
		GREEN_CAP_COOKED = "我用火改變了它！",
		GREEN_MUSHROOM =
		{
			GENERIC = "愚蠢的蘑菇。",
			INGROUND = "喂！你！給我出來！",
			PICKED = "也許有一天它會再長回來。",
		},
		GUNPOWDER = "哇哦！好閃亮！",
		HAMBAT = "很高興認識你，我的肉友！",
		HAMMER = "我喜歡鋒利的工具",
		HEALINGSALVE = "它燒著了！但是火在哪裡？",
		HEATROCK =
		{
			FROZEN = "冰冷刺骨的石頭。",
			COLD = "已經冷冰冰的了。",
			GENERIC = "火會讓這東西變暖！",
			WARM = "既沒有火焰，也沒有真正的熱量...有什麼好玩的？",
			HOT = "看看它是怎麼發光的！",
		},
		HONEY = "甜蜜而美味！",
		HONEYCOMB = "像蠟一樣。",
		HONEYHAM = "烈火、火腿和蜂蜜是絕配。",
		HONEYNUGGETS = "蜂蜜和肉塊遇到最可愛的火，就成了蜂蜜包肉。",
		HORN = "我可以聽到裡面有那些多毛動物的聲音。",
		HOUND = "真是個混蛋！",
		HOUNDMOUND = "啊哦，我不喜歡那東西的樣子。",
		HOUNDBONE = "噁心。",
		ICEBOX = "這是火的對立面。",
		ICEHOUND = "可惡！好冷！",
		INSANITYROCK =
		{
			ACTIVE = "是我看花眼了嗎？",
			INACTIVE = "看上去不像是能燃燒的。太無趣了。",
		},
		JAMMYPRESERVES = "舔，舔，舔！五秒搞定。",
		KABOBS = "火烤的肉，用籤子串起！",
		KILLERBEE =
		{
			GENERIC = "我喜歡那隻蜜蜂的樣子。",
			HELD = "嗡嗡！",
		},
		KNIGHT = "是馬兒耶！",
		KOALEFANT_SUMMER = "我們會成為很好的朋友的！",
		KOALEFANT_WINTER = "毫無疑問，他看上去很暖和...",
		KRAMPUS = "退後，你這個大混蛋！",
		KRAMPUS_SACK = "今年提前過聖誕！",
		LEIF = "他看上去一點就著！",
		LEIF_SPARSE = "他看上去一點就著！",
		LIGHTNING_ROD =
		{
			CHARGED = "哇，通體發光但沒有火。",
			GENERIC = "所有閃電都彙集到這裡！",
		},
		LITTLE_WALRUS = "他看上去很美味。",
		LIVINGLOG = "它看起來很煩躁。",
		LOCKEDWES = "他被那些卑鄙的雕像給困住了！",
		LOG =
		{
			BURNING = "燒吧，木頭，燒燒燒燒吧！",
			GENERIC = "木頭！容易燃燒的木頭！太好了！",
		},
		LUREPLANT = "我打賭一把火就可以解決它。",
		LUREPLANTBULB = "它現在歸我了。",
		MALE_PUPPET = "他看起來已經被嚇得半死。",
		MANDRAKE =
		{
			DEAD = "為什麼這植物長著一張臉？",
			GENERIC = "那株植物不太正常",
			PICKED = "現在它太嚇人了！",
		},
		COOKEDMANDRAKE = "火都沒能把它的臉燒掉。這讓我有點不安。",
		MANDRAKESOUP = "臉沒有洗掉！！",
		MARBLE = "它很重！",
		MARBLEPILLAR = "不知道其餘的燒燬了沒。",
		MARBLETREE = "世上最糟糕的樹，居然不能燃燒。",
		MARSH_BUSH =
		{
			BURNING = "燃燒吧，刺木！",
			GENERIC = "它看上去很尖銳。",
			PICKED = "這些刺木刺得人很痛！",
		},
		MARSH_PLANT = "徹頭徹尾的植物。",
		MARSH_TREE =
		{
			BURNING = "就是這樣！燒吧！",
			BURNT = "真希望火還沒滅。",
			CHOPPED = "現在沒那麼刺手了，對吧？",
			GENERIC = "它看起來很危險！",
		},
		MAXWELL = "他太傲慢了。",
		MAXWELLHEAD = "他顯然很愛講話。",
		MAXWELLLIGHT = "一點都不好玩。它們可以自己把自己點燃。",
		MAXWELLLOCK = "現在我只需要一把鑰匙。",
		MAXWELLTHRONE = "看上去很黏。",
		MEAT = "有火的話，味道更好！",
		MEATBALLS = "將肉做成丸子，用火烹飪一下就成了美味。",
		MEAT_DRIED = "雖然有點難嚼，但還不錯。",
		MERM = "又軟又濕，真噁心。",
		MONSTERLASAGNA = "麵條、肉和一團一團的毛髮。真噁心。",
		MONSTERMEAT = "噁心。到處都是毛。",
		MONSTERMEAT_DRIED = "乾的，聞起來怪怪的。",
		MOSQUITO =
		{
			GENERIC = "真煩人！",
			HELD = "讓你那張嘴離我遠點！",
		},
		MOSQUITOSACK = "在沉悶厚重的氣流中，血液必須沸騰起來。",
		MOUND =
		{
			DUG = "幸好是它不是我。",
			GENERIC = "我打賭裡面全是死去的東西。",
		},
		NIGHTLIGHT = "像火焰一樣，不過是紫色的！",
		NIGHTMAREFUEL = "噁心，還是溫熱的！",
		NIGHTSWORD = "好像我的夢境會對現實事物造成傷害！",
		NITRE = "裡面有一些小爆炸。",
		ONEMANBAND = "我還可以製作煙火！",
		PANDORASCHEST = "有點俗氣。",
		PANFLUTE = "音樂很無聊。",
		PAPYRUS = "我肯定它能夠燃燒！",
		PENGUIN = "快跑，小小舞蹈家。",
		PERD = "臭鳥！別靠近我美味的漿果！",
		PEROGIES = "用火來封口的美味餃子。",
		PETALS = "愚蠢的花。幾乎是毫無用處。",
		PETALS_EVIL = "好噁心，太黏了。",
		PICKAXE = "它很尖銳。",
		PIGGYBACK = "我用豬屁股做了個背包！",
		PIGKING = "呸，懶人一個。",
		PIGMAN =
		{
			DEAD = "真想嚐嚐它們的味道如何。",
			FOLLOWER = "討厭。它在跟著我。",
			GENERIC = "呃，真是臭死了。",
			GUARD = "他可不是我的Boss！",
			WEREPIG = "出招吧，小豬！",
		},
		PIGSKIN = "哈哈。豬屁股。",
		PIGTORCH = "這些豬可真知道享受。",
		PINECONE = 
		{
		    GENERIC = "嘿，你好啊，大樹種子。",
		    PLANTED = "你很快就會長成一棵真正的樹的。",
		},
		PITCHFORK = "三倍那麼尖。",
		PLANTMEAT = "真噁心，又黏又滑。",
		PLANTMEAT_COOKED = "火可以讓一切東西變得更好。",
		PLANT_NORMAL =
		{
			GENERIC = "如果沒得選的話，我會吃它的。",
			GROWING = "快點長，你個愚蠢的植物！",
			READY = "我的乖乖。新鮮的蔬菜。",
			WITHERED = "它已經乾枯而且裂開了。真是不錯的火種！",
		},
		POMEGRANATE = "為什麼它有這麼多部分？",
		POMEGRANATE_COOKED = "火總是讓東西變得更好。",
		POMEGRANATE_SEEDS = "看上去和果實裡面的東西很像。",
		POOP = "嘔...真噁心。不過很有用。",
		PUMPKIN = "我很好奇它用火烤後會變成什麼樣子。",
		SCORCHED_SKELETON = "嚇死人了！",
		PUMPKINCOOKIE = "小甜餅！！！",
		PUMPKIN_COOKED = "在外面用火烤出來的東西真的挺不錯的。",
		PUMPKIN_LANTERN = "裡面的火真是太神奇了！",
		PUMPKIN_SEEDS = "在蔬菜裡，南瓜是火最好的朋友，而這就是南瓜種子。",
		PURPLEGEM = "好奇異！",
		RABBIT =
		{
			GENERIC = "他看上去很美味。",
			HELD = "想抓住他的時候就得手了！",
		},
		RABBITHOLE = 
		{
			GENERIC = "蠢兔子，快出來，我要吃了你。",
			SPRING = "那些蠢兔子肯定被困在下面了。",
		},
		RATATOUILLE = "蔬菜。好多的蔬菜。",
		RAZOR = "我為什麼做了這玩意？",
		REDGEM = "真漂亮！",
		RED_CAP = "我喜歡這顏色。",
		RED_CAP_COOKED = "我用火改變了它！",
		RED_MUSHROOM =
		{
			GENERIC = "好漂亮！",
			INGROUND = "喂！你！給我出來！",
			PICKED = "也許有一天它會再長回來。",
		},
		REEDS =
		{
			BURNING = "燒吧！耶！",
			GENERIC = "這是一叢可以燒著的蘆葦。",
			PICKED = "我拿蘆葦茬毫無辦法。",
		},
        RELIC = 
        {
            GENERIC = "老古董。",
            BROKEN = "零七八碎，七零八碎。",
        },
        RUBBLE = "殘破的傢俱。",
		RESURRECTIONSTONE = "我是不是應該去摸一下它？",
		ROBIN =
		{
			GENERIC = "一隻紅雀。火一樣的顏色，但不是鳳凰。",
			HELD = "它在我口袋裡很舒服。",
		},
		ROBIN_WINTER =
		{
			GENERIC = "它看起來好冷。我猜它肯定想烤火。",
			HELD = "它的羽毛好軟。",
		},
		ROBOT_PUPPET = "它看起來已經被嚇得半死。",
		ROCK_LIGHT =
		{
			GENERIC = "那裡面有熱量，就等著出來呢！",
			OUT = "噢，它涼下來了。",
			LOW = "熔岩在冷卻。",
			NORMAL = "一個火塘！",
		},
		ROCKS = "又收集這些有什麼意義？",
        ROOK = "這是一個城堡！",
        ROPE = "我可以用這個來綁什麼？",
		ROTTENEGG = "好噁心！為什麼？為什麼會這樣？！",
		SANITYROCK =
		{
			ACTIVE = "我想知道這些標記有什麼含義。",
			INACTIVE = "它去了哪裡？",
		},
		SAPLING =
		{
			BURNING = "燒吧！耶！",
			WITHERED = "它都乾枯了，似乎想要著火一樣。",
			GENERIC = "我應該採摘它。",
			PICKED = "可憐的小樹苗。",
		},
		SEEDS = "耕種最無聊了。",
		SEEDS_COOKED = "現在不能用來耕種了。",
		SEWING_KIT = "但是搞破壞要有趣得多！",
		SHOVEL = "不太適合用來戰鬥。",
		SILK = "嗯。好光滑。",
		SKELETON = "天啊。真希望你至少是在榮耀的火焰中死去的。",
		SKELETON_PLAYER = "這讓我心驚肉跳。",
		SKULLCHEST = "哦哦哦，太可怕了！",
		SMALLBIRD =
		{
			GENERIC = "我覺得吧，雖然不太像鳳凰，但還是很可愛。",
			HUNGRY = "你餓了嗎？",
			STARVING = "好吧，好吧！我知道了，你餓了。",
		},
		SMALLMEAT = "有火的話，味道更好！",
		SMALLMEAT_DRIED = "雖然有點難嚼，但還不錯。",
		SPAT = "我不喜歡你的臉！",
		SPEAR = "感受我捅天戳地的憤怒吧！",
		SPIDER =
		{
			DEAD = "哈！嚐到我的厲害了吧！",
			GENERIC = "他很討厭。我應該殺了他。",
			SLEEPING = "我可以幹掉他。",
		},
		SPIDERDEN = "真髒。",
		SPIDEREGGSACK = "一大堆讓人噁心的小蜘蛛。",
		SPIDERGLAND = "好噁心，又黏又臭！",
		SPIDERHAT = "誰是你媽媽！",
		SPIDERQUEEN = "用火燒死它！",
		SPIDER_WARRIOR =
		{
			DEAD = "他活該。",
			GENERIC = "也許我可以...用火燒死它。",
			SLEEPING = "也許我不應該去打擾那傢伙。",
		},
		SPOILED_FOOD = "至少它仍然是可以燃燒的。",
		STATUEHARP = "多麼漂亮的雕像。弄壞了就可惜了。",
		STATUEMAXWELL = "我開始討厭那傢伙了。",
		STEELWOOL = "來個火花，它還是會燃燒。",
		STINGER = "好刺手！",
		STRAWHAT = "一頂稻草做的帽子。但是我覺得，它本來可以成為火種的。",
		SUNKBOAT = "它太遠了，我都燒不到它！",
		SWEATERVEST = "雖然沒有火焰背心那麼好，但還湊合。",
		TAFFY = "甜食燒起來感覺很棒，不過我應該把它吃下去，而不是燒掉。",
		TALLBIRD = "我覺得它不想和我交朋友。",
		TALLBIRDEGG = "它喜歡火嗎？",
		TALLBIRDEGG_COOKED = "經火烤之後好多了。",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "火需要再旺點！",
			GENERIC = "現身吧，我的鳳凰！",
			HOT = "火是不是太旺了？",
			LONG = "這需要多長時間？",
			SHORT = "我都等得不耐煩了。",
		},
		TALLBIRDNEST =
		{
			GENERIC = "可以用火來烤那個蛋！",
			PICKED = "巢是空的。",
		},
		TEENBIRD =
		{
			GENERIC = "我感覺他能理解我。",
			HUNGRY = "他的確吃得多。",
			STARVING = "不要看我！自己去找吃的。",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "我只想看著這個世界燒起來。",
			GENERIC = "我喜歡這些符號發亮的樣子。",
			LOCKED = "需要以某種方式解鎖。",
			PARTIAL = "我在創造怪物！",
		},
		TELEPORTATO_BOX = "感覺暖暖的。",
		TELEPORTATO_CRANK = "這部分有什麼用？",
		TELEPORTATO_POTATO = "也許我可以把它融化成更漂亮的形狀。",
		TELEPORTATO_RING = "這麼珍貴的東西燒了太可惜了！",
		TENTACLE = "一點都不討人喜歡。",
		TENTACLESPOTS = "呃，好噁心。",
		TENTACLESPIKE = "它又尖又黏。",
		TENTACLE_PILLAR = "它在顫抖。",
		TENTACLE_PILLAR_HOLE = "什麼鬼味道！下次點根火柴！",
		TENTACLE_PILLAR_ARM = "啊，它們想要擁抱！",
		TENTACLE_GARDEN = "我聽到有輕微的挖土的聲音。",
		
		LAVA_POND_ROCK = "哦，太好了，另一塊臭石頭！",
		LAVA_POND_ROCK2 = "哦，太好了，另一塊臭石頭！",
		LAVA_POND_ROCK3 = "哦，太好了，另一塊臭石頭！",
		LAVA_POND_ROCK4 = "哦，太好了，另一塊臭石頭！",
		LAVA_POND_ROCK5 = "哦，太好了，另一塊臭石頭！",
		LAVA_POND_ROCK6 = "哦，太好了，另一塊臭石頭！",
		LAVA_POND_ROCK7 = "哦，太好了，另一塊臭石頭！",

		TOPHAT = "高禮帽和打火機，真是絕配。",
		TORCH = "火焰太漂亮了。",
		TRAP = "雖然有點被動攻擊的意思，但有用就行。",
		TRAP_TEETH = "有火就更好了。",
		TRAP_TEETH_MAXWELL = "什麼樣的混蛋會在地上放這東西？",
		TRINKET_1 = "我猜，能夠把這些東西熔掉的火肯定溫度很高。",
		TRINKET_10 = "我覺得假牙不易燃。",
		TRINKET_11 = "哦，不知道他有沒有火焰噴射器！",
		TRINKET_12 = "全部萎縮了，就好像它過於靠近火一樣。",
		TRINKET_2 = "廉價的假玩意兒。它甚至也許都不能當柴火燒。",
		TRINKET_3 = "那是個死結。有火的話，誰還需要刀啊？",
		TRINKET_4 = "他看起來像是經過烈火鍛造的。",
		TRINKET_5 = "看看那些迷你推進器。真是驚人的爆發力！",
		TRINKET_6 = "連一點火花都沒有。",
		TRINKET_7 = "還是縱火比較有趣。",
		TRINKET_8 = "我從來不喜歡用水洗澡。",
		TRINKET_9 = "你可以在拉鍊上擦火柴，但無法在鈕釦上擦。",
		TRUNKVEST_SUMMER = "現在我要永遠和我的朋友待在一起了。",
		TRUNKVEST_WINTER = "雖然不像火焰那樣溫暖，但還不錯！",
		TRUNK_COOKED = "我還是不確定到底要不要吃它。",
		TRUNK_SUMMER = "其實，他有一部分還是挺惹人喜愛的。",
		TRUNK_WINTER = "又軟又黏！",
		UMBRELLA = "我愛這個顏色！",
		WAFFLES = "你好，鬆餅！",
		WALL_HAY_ITEM = "嗯。不知道這些東西會不會燒起來。",
		WALL_STONE = "嗯。我覺得還不錯。",
		WALL_STONE_ITEM = "沒想到這些東西這麼重。",
		WALL_RUINS = "壞蛋會來把它吹倒的！",
		WALL_RUINS_ITEM = "我的口袋裝得下它們嗎？",
		WALL_WOOD_ITEM = "我討厭躲起來。",
		WALL_MOONROCK = "現在安全了。",
		WALL_MOONROCK_ITEM = "我猜我可以帶著它。",
		WALRUS = "別跟著我！",
		WALRUSHAT = "我蠻喜歡這帽子的樣式。",
		WALRUS_CAMP =
		{
			EMPTY = "我才不會進去那裡。討厭！",
			GENERIC = "為什麼其他人的房子都比我的漂亮？",
		},
		WALRUS_TUSK = "吧唧吧唧吧唧。",
		WARDROBE = 
		{
			GENERIC = "我想把它燒了。",
            BURNING = "就是這樣！燒吧！",
			BURNT = "啊，火燒完了。",
		},
		WARG = "你是個卑鄙的大混蛋！",
		WASPHIVE = "我最好保持點距離。",
		WETGOOP = "怎麼會出錯呢？！它明明在火裡，而且我做了一切該做的事。",
		WINTERHAT = "這對我來說還不夠暖和。",
		WORMHOLE =
		{
			GENERIC = "用棍子戳一下！",
			OPEN = "不知道它喜不喜歡辛辣的食物？",
		},
		ACCOMPLISHMENT_SHRINE = "我討厭那個箭頭！", 

		------------------------------------------------------capy--------------------------------
		AERODYNAMICHAT = "走得太快火會熄掉的。",
		ARMOR_LIFEJACKET = "但它能讓我的打火機保持乾燥嗎？",
		ARMOR_SNAKESKIN = "這件衣服讓我感覺很危險。",
		ARMOR_WINDBREAKER = "風是火的敵人。",
		ARMORLIMESTONE = "好...沉啊。",
		ARMOROBSIDIAN = "敢碰我就要被燒死！",
		ARMORSEASHELL = "來試試看啊，壞蛋們。",
		ARMOUREDBOAT = "沒什麼能咬得動這艘船。",
		BABYOX = "You may be small, but you smell big.",
		BALLPHIN = "你看上去不是特別易燃。",
		BALLPHINPOD = "一大家子充滿活力的傢伙。",
		BAMBOOTREE = "A stick-y shrub.",
		BERRYBUSH2_SNAKE = "嗯。漿果。",--I don't think these should have diff name or examine text
		BERRYBUSH_SNAKE = "嗯。漿果。",--I don't think these should have diff name or examine text
		BIOLUMINESCENCE = "這是冷的光。一點也不像火焰。",
		BLOWDART_POISON = "致命一吻。",
		BOAT_LANTERN = "沒有火焰的燈。我一點兒也不喜歡它。",
		BOTTLELANTERN = "這光冰冷而疏遠。",
		BURIEDTREASURE = "如果我不喜歡裡面的東西，我就把箱子燒了。",
		BUSH_VINE = "I bet these crackle and pop when they burn.",
		SNAKEDEN = "I bet these crackle and pop when they burn.",--I don't think these should have diff name or examine text
		CANNONSHOT = "發射！",
		CAPTAINHAT = "我不再有那種要沉沒的感覺了。",
		CARGOBOAT = "這個可以裝好多易燃物。",
		CHIMINEA = "喜歡你的家嗎，親愛的火焰？不用謝。",
		CIRCLINGSEAGULL = "飛向太陽吧，笨蛋。",
		CLOTHSAIL = "縫得不錯。",
		COCONUT = 
		{
		    GENERIC = "可以吃的樹生東西。",
		    PLANTED = "快點長大，我想要樹蔭。",
		},
		COCONUT_COOKED = "嘖！熱烘烘的。",
		COFFEE = "我突然感覺有動力了。",
		COFFEEBEANS = "這些用得上火。",
		COFFEEBEANS_COOKED = "啊，太香了。",
		COFFEEBUSH = "This bush flourishes near the volcano's fire!",
		CORAL = "美麗的顏色。",
		CORALREEF = "真希望有水下呼吸管。",
		CUTLASS = "這把劍有臭味。",
		DEAD_SWORDFISH = "呃，火可以除掉那股味道。",
		DEPLETED_BAMBOOTREE = "還有竹子嗎？喂？",
		DEPLETED_BUSH_VINE = "回來！",
		DOYDOY = "它的眼裡沒有火花。",
		DOYDOYBABY = "你個可憐的小笨蛋。",
		DOYDOYEGG = "笨蛋。",
		DOYDOYEGG_COOKED = "聰明的我煎熟了這顆笨蛋。",
		DOYDOYEGG_CRACKED = "這個星球又變蠢了一點。",
		DOYDOYFEATHER = "這玩意是可以燒的。",
		DOYDOYNEST = "每秒鐘出生一個笨蛋。",
		DUBLOON = "海盜的錢！",
		DUG_BAMBOOTREE = "你需要土壤，立刻就需要。",
		DUG_BERRYBUSH2 = "你想再活一次嗎？",
		DUG_BUSH_VINE = "你想回到土裡嗎？",
		DUG_COFFEEBUSH = "我知道該怎麼對你。",
		EARRING = "好閃亮！",
		FABRIC = "竹子的用處真讓人驚奇。",
		FEATHERSAIL = "我要好好稱讚一下那些渡渡鳥...它們用來做船帆真不錯！",
		FIRERAIN = "火雨盡情下吧！",
		FIRERAINSHADOW = "馬上就好了！",
		FISHINHOLE = "魚兒們，你們為什麼在這裡？",
		GASHAT = "我不喜歡聞臭臭的味道。",
		GOLDENMACHETE = "我不想它被劃傷。",
		ICEMAKER = "It turns fire into ice. Boo.",
		IRONWIND = "現在總算有點進展了。",
		JELLYFISH = "它縮成一團。",
		JELLYFISH_DEAD = "現在再也不能蜇人了。",
		JELLYFISH_COOKED = "它確實看起來可以吃。",
		JELLYFISH_PLANTED = "我要叫你「傑拉德」。",
		JELLYJERKY = "看起來很耐嚼。",
		JUNGLETREESEED =
        {
            GENERIC = "未來的森林大火。",
            PLANTED = "不那麼遙遠的未來森林火災。",
        },
		LAVAPOOL = "多麼驚人的熱與怒！",
		LIMESTONE = "它是用碾碎的死魚做的。",
		LIMPETS = "稍微過一下火你就成了美味。",
		LIMPETS_COOKED = "非常好吃！",
		LOBSTERHOLE = "龍蝦幸福的家。",
		LOGRAFT = "很明顯，柴火還有其他用途！",
		MOSQUITO_POISON = "噓！走開！",
		MUSSEL = "打開你的殼，小子。",
		MUSSEL_COOKED = "火打開了它們的殼。",
		MUSSEL_STICK = "出於某種原因，貽貝喜歡這根棒子。",
		OBSIDIAN = "一塊火石！",
		OBSIDIAN_WORKBENCH = "在這裡可製造火屬性物品！",
		OBSIDIANAXE = "這樣一把斧頭！能劈能燒？！",
		OBSIDIANCOCONADE = "黑曜石增強了爆炸威力。",
		OBSIDIANFIREPIT =
		{
			EMBERS = "啊哦。就快要熄滅了！",
			GENERIC = "我可以幾個小時一直盯著它看。",
			HIGH = "燒吧！燒得再旺點！",
			LOW = "火太小了，真無聊。",
			NORMAL = "我覺得備受寵愛！",
			OUT = "我應該重新把火點燃。",
		},
		OBSIDIANMACHETE = "火砍刀是女孩最好的朋友！",
		SPEAR_OBSIDIAN = "一戳就著火！",
		OBSIDIANSPEARGUN = "我將射出我最火熱的一槍！",
		PACKIM = "是敵是友？",
		PACKIM_FISHBONE = "這看上去意味深長。",
		PALMLEAF = "你將燃燒。",
		PALMTREE_BURNT = "多麼迷人的氣味。",
		PALMTREE_STUMP = "又一棵命歸黃泉。",
		PARROT = "你的顏色像火一樣紅。",
		PIRATEHAT = "好有海盜的感覺。",
		PIRATIHATITATOR = "Cursed pirate magic?",
		POISONHOLE = "大自然真噁心。",
		RAFT = "在海上把這個點著是不明智的。",
		ROWBOAT = "划船？開玩笑吧？",
		SAIL = "它能利用風。",
		SAND = "有什麼了不起，就是沙子。",
		SANDBAG = "一袋沙。",
		SANDBAG_ITEM = "我就把這個放在地上？",
		SANDHILL = "哦，看！一些沙。",
		SEAGULL = "它怕火嗎？它應該怕。",
		SEASACK = "我一定要背上這個濕漉漉的東西？",
		SEASHELL = "只是一些愚蠢的海貝。",
		SEASHELL_BEACHED = "只是一些愚蠢的海貝。",
		SEATRAP = "快游到裡面去！那裡面可舒服了！",
		SEAWEED = "濕漉漉的海草。",
		SEAWEED_COOKED = "在火上燒熟後味道還不錯。",
		SEAWEED_DRIED = "健康的風乾食物。",
		SEAWEED_PLANTED = "濕漉漉的海草。",
		SHARX = "游泳的蠢貨。",
		SLOTMACHINE = "這好像是在浪費時間。",
		SNAKE = "滑行的混蛋。",
		SNAKE_FIRE = "我們有著相似的興趣，怪物。",
		SNAKESKIN = "絕對真皮。",
		SNAKESKINHAT = "水會從它上面流掉。",
		SPEAR_POISON = "我希望不要戳到自己。",
		SPEARGUN = "方便在海上使用的工具。",
		SPEARGUN_POISON = "這也太卑鄙了。",
		STUNGRAY = "這回我算是什麼味道都聞過了。",
		SUPERTELESCOPE = "我能看到大地的盡頭。",
		SWORDFISH = "準備戰鬥！",
		TELESCOPE = "現在你躲不了了，海島！",
		TIGERSHARK = "我的噩夢成真了！",
		TIGERSHARKSHADOW = "不妙！不妙！",
		TOUCAN = "我喜歡你的嘴巴。",
		TRAWLNET = "我會用這個撈到一堆濕東西。",
		TRAWLNETDROPPED = "Everything is going to be wet in there.",
		TREEGUARD = "我不喜歡你。你也不喜歡我。",
		TRIDENT = "從上到下都是濕的。",
		TRINKET_13 = "這是烈酒嗎？是橙色的。",
		TRINKET_14 = "我沒有針...",
		TRINKET_15 = "噢，這玩意是可以燒的。",
		TRINKET_16 = "垃圾真討厭。",
		TRINKET_17 = "不是我的風格。",
		TRINKET_18 = "我想知道這東西有沒有任何價值？",
		TRINKET_19 = "腦殘？聽起來很慘。",
		TURBINE_BLADES = "這些有什麼用？",
		TURF_BEACH = "地面太沒意思了。",
		TURF_JUNGLE = "地面太沒意思了。",
		VENOMGLAND = "好噁心！我要是有手套就好了。",
		VINE = "我可以用這個來做點什麼，或乾脆燒掉也行。",
		VOLCANO = "所有土地上最大最暴烈的火焰！",
		VOLCANO_ALTAR = "Why would I wanna appease the volcano? Then it wouldn't shoot fire!",
		VOLCANO_ALTAR_BROKEN = "現在沒有辦法壓制火山的飢渴了！",
		VOLCANO_EXIT = "我討厭離開這個地方...",
		VOLCANOSTAFF = "我是主宰熱焰的毀滅之神！",
		WALL_LIMESTONE = "凹凸不平的。",
		WALL_LIMESTONE_ITEM = "你看起來不太好燒。",
		WHALE_BLUE = "我都不知道他們竟然把魚做得那麼大。",
		WHALE_CARCASS_BLUE = "它開始腐爛了。真噁心。",
		WHALE_CARCASS_WHITE = "勝利的味道不太好聞...",
		WHALE_WHITE = "我在它的眼睛裡看到了火焰！",
		CRABHOLE = "出來和我一起玩吧！",
		CRAB =
		{
			GENERIC = "別再逃了！",
			HIDDEN = "我相當肯定有一隻螃蟹藏在那裡。",
		},
		BERMUDATRIANGLE = "看著它我感覺有點頭暈。",
		BOATCANNON = "不知道我能不能用這個放火？",
		BOATREPAIRKIT = "這應該能補上任何小漏洞。",
		MACHETE = "或者我可以燒出一條路來。",
		LUGGAGECHEST = "哦！希望裡面裝了有用的東西。",
		DRAGOON = "要是我能想出怎麼馴服一隻就好了。",
		ANTIVENOM = "在我中毒的時候這個能派上用場",
		BAMBOO = "看上去可以燃燒。",
		FROG_POISON = "呀！離我遠點。",
		OX = "你看起來很強壯。",
		PEACOCK = "好漂亮！",
		SEAGULL_WATER = "「嘎」你個頭。",
		SNAKE_POISON = "那些是尖銳的毒牙。",
		SOLOFISH = "看起來不太聰明。",
		SPOILED_FISH = "噁心。",
		TWISTER = "離我寶貴的火焰遠點！",
		SAND_CASTLE =
		{
			GENERIC = "應該挺可愛。",
			SAND = "沙子做的城堡。一座沙堡。",
		},
		SNAKEOIL = "我不相信。",
		LOBSTER = "過來，你！",
		MESSAGEBOTTLE = "裝在瓶子裡的紙條！",
		MESSAGEBOTTLEEMPTY = "一個瓶子。",
		SHARK_FIN = "鰭掉下來了。",
		VOLCANO_ALTAR =
		{
		 	GENERIC = "侍奉火神的祭壇！",
		 	OPEN = "準備給火焰獻祭！",
		},
		ELEPHANTCACTUS = "別碰我！",
		ELEPHANTCACTUS_ACTIVE = "哎喲！",
		ELEPHANTCACTUS_STUMP = "永遠別出來！",
		DOUBLE_UMBRELLAHAT = "如果我在商店裡買的這個，我會感覺虧大了。",
		MUSSEL_FARM =
		{
			GENERIC = "我搆不著。",
			STICKPLANTED = "很快你們就是我的了。",
		},
		WOODLEGS_CAGE = "他看上去有點狡詐。",

		 PIRATIHATITATOR =
		 {
		 	GENERIC = "這東西真可笑。",
		 	BURNT = "現在更像我的風格了。",
		 },
		 COFFEEBUSH =
		 {
		 	BARREN = "它完全被搾乾了。",
		 	PICKED = "呃，但我還想再來一杯...",
		 	WITHERED = "它需要灰燼和愛。主要是灰燼。",
		 	GENERIC = "來自熱火山的熱爪哇咖啡！",
		 },
		 DUG_ELEPHANTCACTUS = "我不必給你澆水，對吧？",
		 WHALE_BUBBLES = "那些泡泡是怎麼弄出來的？",

		ARMORCACTUS = "這樣我就不會被那些仙人掌刺到了。",
		BAMBOOTREE =
		{
			BURNT = "哦，我能再燒一次嗎？",
			CHOPPED = "它會長回來的。",
			GENERIC = "引火柴！",
		},
		BLOWDART_FLUP = "這個是吹的。",
		BLUBBER = "我敢打賭這個燒起來一定很亮！",
		BLUBBERSUIT = "我一動就發出咯吱咯吱的聲音...",
		BOAT = "不~可以~燒...！",
		BOAT_TORCH = "好奇怪，不是用來把船點著的。",
		BRAINJELLYHAT = "我感覺更聰明了，但也覺得更噁心了...",
		BUOY = "燈塔，很高興有它。",
		BUSH_VINE =
		{
			BURNT = "它們燒起來真好玩！",
			CHOPPED = "就該這樣解開它們。",
			GENERIC = "我敢打賭這些東西燒起來會辟啪作響。",
		},
		COCONADE =
		{
			BURNING = "就是這樣...",
			GENERIC = "它會先爆炸，再燃燒。",
		},
		COCONUT_HALVED = "啊哈！現在你成食物了！",
		COFFEEBOT = "它會煮咖啡！",
		COMPASS =
		{
			E = "東！",
			GENERIC = "我看不懂。",
			N = "北！",
			NE = "東北！",
			NW = "西北！",
			S = "南！",
			SE = "東南！",
			SW = "西南！",
			W = "西...",
		},
		CORAL_BRAIN = "我可以學著喜歡這種味道...",
		CORAL_BRAIN_ROCK = "天才的想法，躲在這些愚笨的普通珊瑚當中。",
		CRATE = "如果我燒了它，裡面的東西也會被燒掉...",
		DEPLETED_GRASS =
		{
			GENERIC = "樣子多麼淒慘的...草？",
		},
		DEPLETED_GRASS_WATER = "它在小憩。",
		DRAGOONDEN = "一群莽夫住在那裡。",
		DRAGOONEGG = "我想這塊熱石頭實際上是一顆熱蛋。",
		DRAGOONHEART = "沒什麼比一餐熱飯更好的了。",
		DRAGOONSPIT = "一攤燃燒著的嘔吐物。",
		FISH_RAW = "需要火！",
		FISH_RAW_SMALL = "我喜歡生魚片，但我更喜歡用火烤過的。",
		FISH_RAW_SMALL_COOKED = "魚和火是絕配。",
		FLAMEGEYSER = "令人愉快...",
		FLOTSAM = "它就在那，可是我卻在這。",
		FLUP = "滾開！",
		FRESHFRUITCREPES = "噢啦啦。",
		GRASS_WATER = "這個不需要澆水。",
		HAIL_ICE = "呃，已經在融化了。",
		HOME = "我想知道誰住在這裡？",
		ICEMAKER =
		{
			HIGH = "燃料充足！",
			LOW = "它需要更多燃料。",
			NORMAL = "製冰吧。",
			OUT = "它沒有燃料了。",
			VERYLOW = "它差不多沒有燃料了。",
		},
		JUNGLETREE =
		{
			BURNING = "哇！好多火！",
			BURNT = "重大改進。",
			CHOPPED = "好幾下才把它砍倒。",
			GENERIC = "好多好多的樹可以燒！",
		},
		KNIGHTBOAT = "檢查一下你的船，老兄。",
		KRAKEN = "用火燒死它！",
		KRAKENCHEST = "我就不客氣了。",
		KRAKEN_TENTACLE = "哎呀，離我遠點！",
		LIMPETROCK =
		{
			GENERIC = "那些令人噁心的食材正在嘗試吃掉那塊石頭。",
			PICKED = "這塊石頭暫時擺脫了那些玩意兒的煩擾。",
		},
		LIVINGJUNGLETREE = "這棵樹有點奇怪。",
		LOBSTER_DEAD = "必要時可以吃。",
		LOBSTER_DEAD_COOKED = "晚餐吃龍蝦！我不是在做夢吧！",
		MAGIC_SEAL = "它在發光。",
		MAGMAROCK = "岩漿，我喜歡！",
		MAGMAROCK_FULL = "岩漿，我喜歡！",
		MAGMAROCK_GOLD = "岩漿，我喜歡！",
		MAGMAROCK_GOLD_FULL = "岩漿，我喜歡！",
		MANGROVETREE = "不用給這傢伙澆水。",
		MANGROVETREE_BURNT = "全燒焦了，呃，我是說水上的部分。",
		MARSH_PLANT_TROPICAL = "草木。",
		MERMFISHER = "呃，我敢打賭你永遠也去不掉那股魚腥味。",
		MERMHOUSE_FISHER = "魚販子。",
		MONKEYBALL = "我敢打賭猴子喜歡這樣的球。",
		MONSTERTARTARE = "好噁心！",
		MOSQUITOSACK_YELLOW = "某個令人厭惡的傢伙掉落了這個。",
		MUSSELBOUILLABAISE = "嗯，真香！",
		MYSTERYMEAT = "養育子女真讓人噁心。",
		NEEDLESPEAR = "談到這玩意我可以說上一整天。",
		OCTOPUSCHEST = "裡面裝滿了海洋珍品！",
		OCTOPUSKING = "他看起來有點呆。",
		OXHAT = "太牛了！",
		OX_FLUTE = "我聽到有風暴即將來臨。",
		OX_HORN = "這個可以再來一支。",
		PALMLEAF_HUT = "遮風擋雨。但太好燒了。",
		PARROT_PIRATE = "你是一個喜歡尖叫的無賴。",
		PEG_LEG = "我還沒有確定這個是幹什麼用的。",
		PIGTENT = "太難聞了！",
		PIKE_SKULL = "真噁心。",
		PIRATEGHOST = "你是什麼東西？",
		PIRATEPACK = "背這個有助於鍛煉胸肌。",
		PORTAL_SHIPWRECKED = "是時候離開這裡了。",
		PRIMEAPE = "嗨，小兄弟，你也喜歡玩火嗎？",
		PRIMEAPEBARREL = "好一個猴子窩。",
		RAWLING = "他一直陪伴著我。",
		REDBARREL = "我最喜歡的那種桶！",
		ROCK_CHARCOAL = "It drops burned things!",
		ROCK_OBSIDIAN = "This rock makes me so excited, I just want to explode!",
		SAIL_STICK = "我是這艘船的女王！",
		SANDBAGSMALL = "讓家裡的火保持熊熊燃燒。",
		SANDBAGSMALL_ITEM = "讓家裡的火保持熊熊燃燒。",
		SHADOWSKITTISH_WATER = "那是什麼？？",
		SHARKITTEN = "嗨，小可愛，你媽媽在哪兒？",
		SHARKITTENSPAWNER =
		{
			GENERIC = "我的鯊魚雷達正在燃燒。",
			INACTIVE = "這個沙丘為什麼在這裡？",
		},
		SHARK_GILLS = "我猜它不再需要用這些來呼吸了。",
		SHARK_TEETHHAT = "戴著這個讓我露齒而笑。",
		SHIPWRECKED_ENTRANCE = "我們走！",
		SHIPWRECKED_EXIT = "我要離開這裡了。",
		SNAKEDEN =
		{
			BURNT = "它們燒起來真好玩！",
			CHOPPED = "就該這樣解開它們。",
			GENERIC = "我敢打賭這些東西燒起來會辟啪作響。",
		},
		SNAKESKINSAIL = "多麼令人毛骨悚然的船帆。",
		SPEAR_LAUNCHER = "唯一比矛更好的東西就是能發射它們的槍。",
		SUNKEN_BOAT =
		{
			ABANDONED = "他們去哪兒了？",
			GENERIC = "某個人全身濕透了。",
		},
		SUNKEN_BOAT_BURNT = "雙重打擊。",
		SUNKEN_BOAT_TRINKET_1 = "我不能說那個字！",
		SUNKEN_BOAT_TRINKET_2 = "我已經不是小孩了。",
		SUNKEN_BOAT_TRINKET_3 = "它想認識我的打火機。",
		SUNKEN_BOAT_TRINKET_4 = "完全不知道那是什麼東西。",
		SUNKEN_BOAT_TRINKET_5 = "不是我的尺碼。",
		SWEETPOTATOSOUFFLE = "完美的烹飪！",
		SWEET_POTATO = "紅漿果變成蕃薯，喜聞樂見。",
		SWEET_POTATO_COOKED = "烤過之後味道更棒了。",
		SWEET_POTATO_PLANTED = "它在火上更可愛！",
		SWEET_POTATO_SEEDS = "種子。甜甜的。",
		SWIMMINGHORROR = "你會游泳？太可怕了！",
		TELEPORTATO_SW_BASE = "似乎它少了一樣或兩樣東西。",
		TELEPORTATO_SW_BOX = "某個東西的一部分。",
		TELEPORTATO_SW_CRANK = "用來轉動手柄？",
		TELEPORTATO_SW_POTATO = "我想知道它有什麼用？",
		TELEPORTATO_SW_RING = "我覺得它應該和別的東西搭配使用。",
		THATCHPACK = "小草包，有勞你了。",
		TIDALPOOL = "我想知道如果用水沖它，它會往哪邊轉？",
		TIDAL_PLANT = "這是一株植物。",
		TIGEREYE = "別用那種眼神看我！",
		TRAWLNETDROPPED =
		{
			GENERIC = "網袋裡有什麼？",
			SOON = "它很快就要沉下去了！",
			SOONISH = "我相信那個網袋正在下沉。",
		},
		TREASURECHEST_TRAP = "卑鄙的詭計！",
		TRINKET_20 = "我不能說那個字！",
		TRINKET_21 = "我已經不是小孩了。",
		TRINKET_22 = "它想認識我的打火機。",
		TRINKET_23 = "壞的什麼？",
		TROPICAL_FISH = "多麼美麗的顏色。",
		TUNACAN = "噢，但我喜歡有海豚肉的！",
		TURF_ASH = "灰燼。",
		TURF_MAGMAFIELD = "易爆！",
		TURF_MEADOW = "寧靜。",
		TURF_SNAKESKINFLOOR = "噁心。",
		TURF_TIDALMARSH = "踩上去嘎吱響。",
		TURF_VOLCANO = "熱的地皮。",
		TWISTER_SEAL = "我以前也被很萌的傢伙弄得焦頭爛額過。",
		VOLCANO_ALTAR_TOWER = "火焰的紀念碑！",
		VOLCANO_SHRUB = "You come pre-burnt!",
		WALLYINTRO_DEBRIS = "那是我幹的嗎？",
		WATERYGRAVE = "這裡有什麼東西很可疑。",
		WHALE_TRACK = "哪裡有泡泡哪裡就有火！",
		WILBUR_CROWN = "你的腦袋必須夠小才能戴上這個。",
		WILBUR_UNLOCK = "尊貴的猴子。",
		WILDBORE = "不怎麼想靠近這傢伙。",
		WILDBOREHEAD = "太令人噁心了！",
		WILDBOREHOUSE = "放把火就能吃烤肉了！",
		WIND_CONCH = "希望不會把火吹滅。",
		WOODLEGSBOAT = "一艘不錯的船。",
		WOODLEGSHAT = "我不認為它是為我做的。",
		WOODLEGSSAIL = "這面船帆看上去對某個人有著特殊的意義。",
		WOODLEGS_KEY1 = "開什麼的鑰匙？",
		WOODLEGS_KEY2 = "某個地方肯定有某個上鎖的東西。",
		WOODLEGS_KEY3 = "另一把鑰匙。",
		WRECK = "某人有遺憾。",
		CALIFORNIAROLL = "哦，太好了，用海帶捲起的魚。",
		BANANAPOP = "這是燃燒的對立面。",
		BISQUE = "我猜這個能吃。",
		CEVICHE = "它還是黏乎乎的。",
		SEAFOODGUMBO = "好噁心，這是什麼啊？",
		SURFNTURF = "噢。這是給老人吃的！",
		SHARKFINSOUP = "我甚至沒有燒它！",
		LOBSTERDINNER = "太好吃了！",
		LOBSTERBISQUE = "我要把這個全吃光！",
		JELLYOPOP = "我要二十個！",
		VOLCANO_SHRUB = "不公平！我沒機會燒你！",
		ROCK_OBSIDIAN = "我...見過的...最...美麗的...石頭",
		ROCK_CHARCOAL = "全是炭！",
	},
	DESCRIBE_TOODARK = "我需要更多的光！",
	DESCRIBE_GENERIC = "它剛剛是在求人燒掉它。",
	DESCRIBE_SMOLDERING = "太棒了，它就要著火了！",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "啊！",
	},
}